.global gAxArcanine
gAxArcanine:
ax_siro sAxMainArcanine
sArcaninePose1:
ax_pose 0, 0x01e5, 0x80f4, 0x0c00
ax_pose_terminator
sArcaninePose2:
ax_pose 1, 0x01e7, 0x80f4, 0x0c00
ax_pose_terminator
sArcaninePose3:
ax_pose 2, 0x01e7, 0x80f4, 0x0c00
ax_pose_terminator
sArcaninePose4:
ax_pose 3, 0x01e5, 0x90f0, 0x0c00
ax_pose_terminator
sArcaninePose5:
ax_pose 4, 0x01e5, 0x90f0, 0x0c00
ax_pose_terminator
sArcaninePose6:
ax_pose 5, 0x01e7, 0x90f0, 0x0c00
ax_pose_terminator
sArcaninePose7:
ax_pose 6, 0x01e5, 0x90f0, 0x0c00
ax_pose_terminator
sArcaninePose8:
ax_pose 7, 0x01e5, 0x90f0, 0x0c00
ax_pose_terminator
sArcaninePose9:
ax_pose 8, 0x01e5, 0x90f0, 0x0c00
ax_pose_terminator
sArcaninePose10:
ax_pose 9, 0x01e5, 0x90f0, 0x0c00
ax_pose_terminator
sArcaninePose11:
ax_pose 10, 0x01e5, 0x90f0, 0x0c00
ax_pose_terminator
sArcaninePose12:
ax_pose 11, 0x01e7, 0x90f0, 0x0c00
ax_pose_terminator
sArcaninePose13:
ax_pose 12, 0x01e5, 0x80f4, 0x0c00
ax_pose_terminator
sArcaninePose14:
ax_pose 13, 0x01e7, 0x80f4, 0x0c00
ax_pose_terminator
sArcaninePose15:
ax_pose 14, 0x01e7, 0x80f4, 0x0c00
ax_pose_terminator
sArcaninePose16:
ax_pose 9, 0x01e5, 0x80f0, 0x0c00
ax_pose_terminator
sArcaninePose17:
ax_pose 10, 0x01e5, 0x80f0, 0x0c00
ax_pose_terminator
sArcaninePose18:
ax_pose 11, 0x01e7, 0x80f0, 0x0c00
ax_pose_terminator
sArcaninePose19:
ax_pose 6, 0x01e5, 0x80f0, 0x0c00
ax_pose_terminator
sArcaninePose20:
ax_pose 7, 0x01e5, 0x80f0, 0x0c00
ax_pose_terminator
sArcaninePose21:
ax_pose 8, 0x01e5, 0x80f0, 0x0c00
ax_pose_terminator
sArcaninePose22:
ax_pose 3, 0x01e5, 0x80f0, 0x0c00
ax_pose_terminator
sArcaninePose23:
ax_pose 4, 0x01e5, 0x80f0, 0x0c00
ax_pose_terminator
sArcaninePose24:
ax_pose 5, 0x01e7, 0x80f0, 0x0c00
ax_pose_terminator
sArcaninePose25:
ax_pose 0, 0x01e5, 0x80f4, 0x0c00
ax_pose_terminator
sArcaninePose26:
ax_pose 1, 0x01e7, 0x80f4, 0x0c00
ax_pose_terminator
sArcaninePose27:
ax_pose 2, 0x01e7, 0x80f4, 0x0c00
ax_pose_terminator
sArcaninePose28:
ax_pose 15, 0x01e4, 0x80f4, 0x0c00
ax_pose_terminator
sArcaninePose29:
ax_pose 16, 0x01e4, 0x80f4, 0x0c00
ax_pose_terminator
sArcaninePose30:
ax_pose 3, 0x01e5, 0x90f0, 0x0c00
ax_pose_terminator
sArcaninePose31:
ax_pose 4, 0x01e5, 0x90f0, 0x0c00
ax_pose_terminator
sArcaninePose32:
ax_pose 5, 0x01e7, 0x90f0, 0x0c00
ax_pose_terminator
sArcaninePose33:
ax_pose 17, 0x01e5, 0x90f0, 0x0c00
ax_pose_terminator
sArcaninePose34:
ax_pose 18, 0x01e5, 0x90f0, 0x0c00
ax_pose_terminator
sArcaninePose35:
ax_pose 6, 0x01e5, 0x90f0, 0x0c00
ax_pose_terminator
sArcaninePose36:
ax_pose 7, 0x01e5, 0x90f0, 0x0c00
ax_pose_terminator
sArcaninePose37:
ax_pose 8, 0x01e5, 0x90f0, 0x0c00
ax_pose_terminator
sArcaninePose38:
ax_pose 19, 0x41e5, 0x90f0, 0x0c00
ax_pose 20, 0x41f5, 0x50f0, 0x0c08
ax_pose 21, 0x01fd, 0x10f0, 0x0c0c
ax_pose 22, 0x01eb, 0x10e8, 0x0c0d
ax_pose 23, 0x01f3, 0x10e8, 0x0c0e
ax_pose_terminator
sArcaninePose39:
ax_pose 24, 0x01e5, 0x90f1, 0x0c00
ax_pose_terminator
sArcaninePose40:
ax_pose 9, 0x01e5, 0x90f0, 0x0c00
ax_pose_terminator
sArcaninePose41:
ax_pose 10, 0x01e5, 0x90f0, 0x0c00
ax_pose_terminator
sArcaninePose42:
ax_pose 11, 0x01e7, 0x90f0, 0x0c00
ax_pose_terminator
sArcaninePose43:
ax_pose 25, 0x01e5, 0x90f0, 0x0c00
ax_pose_terminator
sArcaninePose44:
ax_pose 26, 0x01e5, 0x90f0, 0x0c00
ax_pose_terminator
sArcaninePose45:
ax_pose 12, 0x01e5, 0x80f4, 0x0c00
ax_pose_terminator
sArcaninePose46:
ax_pose 13, 0x01e7, 0x80f4, 0x0c00
ax_pose_terminator
sArcaninePose47:
ax_pose 14, 0x01e7, 0x80f4, 0x0c00
ax_pose_terminator
sArcaninePose48:
ax_pose 27, 0x01e5, 0x80f4, 0x0c00
ax_pose_terminator
sArcaninePose49:
ax_pose 28, 0x01e3, 0x80f4, 0x0c00
ax_pose_terminator
sArcaninePose50:
ax_pose 9, 0x01e5, 0x80f0, 0x0c00
ax_pose_terminator
sArcaninePose51:
ax_pose 10, 0x01e5, 0x80f0, 0x0c00
ax_pose_terminator
sArcaninePose52:
ax_pose 11, 0x01e7, 0x80f0, 0x0c00
ax_pose_terminator
sArcaninePose53:
ax_pose 25, 0x01e5, 0x80f0, 0x0c00
ax_pose_terminator
sArcaninePose54:
ax_pose 26, 0x01e5, 0x80f0, 0x0c00
ax_pose_terminator
sArcaninePose55:
ax_pose 6, 0x01e5, 0x80f0, 0x0c00
ax_pose_terminator
sArcaninePose56:
ax_pose 7, 0x01e5, 0x80f0, 0x0c00
ax_pose_terminator
sArcaninePose57:
ax_pose 8, 0x01e5, 0x80f0, 0x0c00
ax_pose_terminator
sArcaninePose58:
ax_pose 19, 0x41e5, 0x80f0, 0x0c00
ax_pose 20, 0x41f5, 0x40f0, 0x0c08
ax_pose 21, 0x01fd, 0x0108, 0x0c0c
ax_pose 22, 0x01eb, 0x0110, 0x0c0d
ax_pose 23, 0x01f3, 0x0110, 0x0c0e
ax_pose_terminator
sArcaninePose59:
ax_pose 24, 0x01e5, 0x80ef, 0x0c00
ax_pose_terminator
sArcaninePose60:
ax_pose 3, 0x01e5, 0x80f0, 0x0c00
ax_pose_terminator
sArcaninePose61:
ax_pose 4, 0x01e5, 0x80f0, 0x0c00
ax_pose_terminator
sArcaninePose62:
ax_pose 5, 0x01e7, 0x80f0, 0x0c00
ax_pose_terminator
sArcaninePose63:
ax_pose 17, 0x01e5, 0x80f0, 0x0c00
ax_pose_terminator
sArcaninePose64:
ax_pose 18, 0x01e5, 0x80f0, 0x0c00
ax_pose_terminator
sArcaninePose65:
ax_pose 0, 0x01e5, 0x80f4, 0x0c00
ax_pose_terminator
sArcaninePose66:
ax_pose 1, 0x01e7, 0x80f4, 0x0c00
ax_pose_terminator
sArcaninePose67:
ax_pose 2, 0x01e7, 0x80f4, 0x0c00
ax_pose_terminator
sArcaninePose68:
ax_pose 15, 0x01e4, 0x80f4, 0x0c00
ax_pose_terminator
sArcaninePose69:
ax_pose 16, 0x01e4, 0x80f4, 0x0c00
ax_pose_terminator
sArcaninePose70:
ax_pose 3, 0x01e5, 0x90f0, 0x0c00
ax_pose_terminator
sArcaninePose71:
ax_pose 4, 0x01e5, 0x90f0, 0x0c00
ax_pose_terminator
sArcaninePose72:
ax_pose 5, 0x01e7, 0x90f0, 0x0c00
ax_pose_terminator
sArcaninePose73:
ax_pose 17, 0x01e5, 0x90f0, 0x0c00
ax_pose_terminator
sArcaninePose74:
ax_pose 18, 0x01e5, 0x90f0, 0x0c00
ax_pose_terminator
sArcaninePose75:
ax_pose 6, 0x01e5, 0x90f0, 0x0c00
ax_pose_terminator
sArcaninePose76:
ax_pose 7, 0x01e5, 0x90f0, 0x0c00
ax_pose_terminator
sArcaninePose77:
ax_pose 8, 0x01e5, 0x90f0, 0x0c00
ax_pose_terminator
sArcaninePose78:
ax_pose 19, 0x41e5, 0x90f0, 0x0c00
ax_pose 20, 0x41f5, 0x50f0, 0x0c08
ax_pose 21, 0x01fd, 0x10f0, 0x0c0c
ax_pose 22, 0x01eb, 0x10e8, 0x0c0d
ax_pose 23, 0x01f3, 0x10e8, 0x0c0e
ax_pose_terminator
sArcaninePose79:
ax_pose 24, 0x01e5, 0x90f1, 0x0c00
ax_pose_terminator
sArcaninePose80:
ax_pose 9, 0x01e5, 0x90f0, 0x0c00
ax_pose_terminator
sArcaninePose81:
ax_pose 10, 0x01e5, 0x90f0, 0x0c00
ax_pose_terminator
sArcaninePose82:
ax_pose 11, 0x01e7, 0x90f0, 0x0c00
ax_pose_terminator
sArcaninePose83:
ax_pose 25, 0x01e5, 0x90f0, 0x0c00
ax_pose_terminator
sArcaninePose84:
ax_pose 26, 0x01e5, 0x90f0, 0x0c00
ax_pose_terminator
sArcaninePose85:
ax_pose 12, 0x01e5, 0x80f4, 0x0c00
ax_pose_terminator
sArcaninePose86:
ax_pose 13, 0x01e7, 0x80f4, 0x0c00
ax_pose_terminator
sArcaninePose87:
ax_pose 14, 0x01e7, 0x80f4, 0x0c00
ax_pose_terminator
sArcaninePose88:
ax_pose 27, 0x01e5, 0x80f4, 0x0c00
ax_pose_terminator
sArcaninePose89:
ax_pose 28, 0x01e3, 0x80f4, 0x0c00
ax_pose_terminator
sArcaninePose90:
ax_pose 9, 0x01e5, 0x80f0, 0x0c00
ax_pose_terminator
sArcaninePose91:
ax_pose 10, 0x01e5, 0x80f0, 0x0c00
ax_pose_terminator
sArcaninePose92:
ax_pose 11, 0x01e7, 0x80f0, 0x0c00
ax_pose_terminator
sArcaninePose93:
ax_pose 25, 0x01e5, 0x80f0, 0x0c00
ax_pose_terminator
sArcaninePose94:
ax_pose 26, 0x01e5, 0x80f0, 0x0c00
ax_pose_terminator
sArcaninePose95:
ax_pose 6, 0x01e5, 0x80f0, 0x0c00
ax_pose_terminator
sArcaninePose96:
ax_pose 7, 0x01e5, 0x80f0, 0x0c00
ax_pose_terminator
sArcaninePose97:
ax_pose 8, 0x01e5, 0x80f0, 0x0c00
ax_pose_terminator
sArcaninePose98:
ax_pose 19, 0x41e5, 0x80f0, 0x0c00
ax_pose 20, 0x41f5, 0x40f0, 0x0c08
ax_pose 21, 0x01fd, 0x0108, 0x0c0c
ax_pose 22, 0x01eb, 0x0110, 0x0c0d
ax_pose 23, 0x01f3, 0x0110, 0x0c0e
ax_pose_terminator
sArcaninePose99:
ax_pose 24, 0x01e5, 0x80ef, 0x0c00
ax_pose_terminator
sArcaninePose100:
ax_pose 3, 0x01e5, 0x80f0, 0x0c00
ax_pose_terminator
sArcaninePose101:
ax_pose 4, 0x01e5, 0x80f0, 0x0c00
ax_pose_terminator
sArcaninePose102:
ax_pose 5, 0x01e7, 0x80f0, 0x0c00
ax_pose_terminator
sArcaninePose103:
ax_pose 17, 0x01e5, 0x80f0, 0x0c00
ax_pose_terminator
sArcaninePose104:
ax_pose 18, 0x01e5, 0x80f0, 0x0c00
ax_pose_terminator
sArcaninePose105:
ax_pose 0, 0x01e5, 0x80f4, 0x0c00
ax_pose_terminator
sArcaninePose106:
ax_pose 1, 0x01e7, 0x80f4, 0x0c00
ax_pose_terminator
sArcaninePose107:
ax_pose 29, 0x01e5, 0x80f4, 0x0c00
ax_pose_terminator
sArcaninePose108:
ax_pose 30, 0x01e4, 0x80f4, 0x0c00
ax_pose_terminator
sArcaninePose109:
ax_pose 3, 0x01e5, 0x90f0, 0x0c00
ax_pose_terminator
sArcaninePose110:
ax_pose 4, 0x01e5, 0x90f0, 0x0c00
ax_pose_terminator
sArcaninePose111:
ax_pose 31, 0x01e5, 0x90f0, 0x0c00
ax_pose_terminator
sArcaninePose112:
ax_pose 32, 0x01e5, 0x90f0, 0x0c00
ax_pose_terminator
sArcaninePose113:
ax_pose 6, 0x01e5, 0x90f0, 0x0c00
ax_pose_terminator
sArcaninePose114:
ax_pose 7, 0x01e5, 0x90f0, 0x0c00
ax_pose_terminator
sArcaninePose115:
ax_pose 33, 0x01e5, 0x90ee, 0x0c00
ax_pose_terminator
sArcaninePose116:
ax_pose 34, 0x01e5, 0x90f2, 0x0c00
ax_pose_terminator
sArcaninePose117:
ax_pose 9, 0x01e5, 0x90f0, 0x0c00
ax_pose_terminator
sArcaninePose118:
ax_pose 10, 0x01e5, 0x90f0, 0x0c00
ax_pose_terminator
sArcaninePose119:
ax_pose 35, 0x01e5, 0x90f0, 0x0c00
ax_pose_terminator
sArcaninePose120:
ax_pose 36, 0x01e5, 0x90f1, 0x0c00
ax_pose_terminator
sArcaninePose121:
ax_pose 12, 0x01e5, 0x80f4, 0x0c00
ax_pose_terminator
sArcaninePose122:
ax_pose 13, 0x01e7, 0x80f4, 0x0c00
ax_pose_terminator
sArcaninePose123:
ax_pose 37, 0x01e5, 0x80f4, 0x0c00
ax_pose_terminator
sArcaninePose124:
ax_pose 38, 0x01e5, 0x80f4, 0x0c00
ax_pose_terminator
sArcaninePose125:
ax_pose 9, 0x01e5, 0x80f0, 0x0c00
ax_pose_terminator
sArcaninePose126:
ax_pose 10, 0x01e5, 0x80f0, 0x0c00
ax_pose_terminator
sArcaninePose127:
ax_pose 35, 0x01e5, 0x80ef, 0x0c00
ax_pose_terminator
sArcaninePose128:
ax_pose 36, 0x01e5, 0x80ef, 0x0c00
ax_pose_terminator
sArcaninePose129:
ax_pose 6, 0x01e5, 0x80f0, 0x0c00
ax_pose_terminator
sArcaninePose130:
ax_pose 7, 0x01e5, 0x80f0, 0x0c00
ax_pose_terminator
sArcaninePose131:
ax_pose 33, 0x01e5, 0x80f2, 0x0c00
ax_pose_terminator
sArcaninePose132:
ax_pose 34, 0x01e5, 0x80ee, 0x0c00
ax_pose_terminator
sArcaninePose133:
ax_pose 3, 0x01e5, 0x80f0, 0x0c00
ax_pose_terminator
sArcaninePose134:
ax_pose 4, 0x01e5, 0x80f0, 0x0c00
ax_pose_terminator
sArcaninePose135:
ax_pose 31, 0x01e6, 0x80f0, 0x0c00
ax_pose_terminator
sArcaninePose136:
ax_pose 32, 0x01e5, 0x80f0, 0x0c00
ax_pose_terminator
sArcaninePose137:
ax_pose 0, 0x01e5, 0x80f4, 0x0c00
ax_pose_terminator
sArcaninePose138:
ax_pose 15, 0x01e4, 0x80f4, 0x0c00
ax_pose_terminator
sArcaninePose139:
ax_pose 29, 0x01e5, 0x80f4, 0x0c00
ax_pose_terminator
sArcaninePose140:
ax_pose 3, 0x01e5, 0x90f0, 0x0c00
ax_pose_terminator
sArcaninePose141:
ax_pose 17, 0x01e5, 0x90ef, 0x0c00
ax_pose_terminator
sArcaninePose142:
ax_pose 31, 0x01e5, 0x90f0, 0x0c00
ax_pose_terminator
sArcaninePose143:
ax_pose 6, 0x01e5, 0x90f0, 0x0c00
ax_pose_terminator
sArcaninePose144:
ax_pose 19, 0x41e5, 0x90f1, 0x0c00
ax_pose 20, 0x41f5, 0x50f1, 0x0c08
ax_pose 21, 0x01fd, 0x10f1, 0x0c0c
ax_pose 22, 0x01eb, 0x10e9, 0x0c0d
ax_pose 23, 0x01f3, 0x10e9, 0x0c0e
ax_pose_terminator
sArcaninePose145:
ax_pose 33, 0x01e5, 0x90f0, 0x0c00
ax_pose_terminator
sArcaninePose146:
ax_pose 9, 0x01e5, 0x90f0, 0x0c00
ax_pose_terminator
sArcaninePose147:
ax_pose 25, 0x01e5, 0x90ee, 0x0c00
ax_pose_terminator
sArcaninePose148:
ax_pose 35, 0x01e6, 0x90f0, 0x0c00
ax_pose_terminator
sArcaninePose149:
ax_pose 12, 0x01e5, 0x80f4, 0x0c00
ax_pose_terminator
sArcaninePose150:
ax_pose 27, 0x01e5, 0x80f4, 0x0c00
ax_pose_terminator
sArcaninePose151:
ax_pose 37, 0x01e9, 0x80f4, 0x0c00
ax_pose_terminator
sArcaninePose152:
ax_pose 9, 0x01e5, 0x80f0, 0x0c00
ax_pose_terminator
sArcaninePose153:
ax_pose 25, 0x01e5, 0x80f2, 0x0c00
ax_pose_terminator
sArcaninePose154:
ax_pose 35, 0x01e6, 0x80f0, 0x0c00
ax_pose_terminator
sArcaninePose155:
ax_pose 6, 0x01e5, 0x80f0, 0x0c00
ax_pose_terminator
sArcaninePose156:
ax_pose 19, 0x41e5, 0x80f0, 0x0c00
ax_pose 20, 0x41f5, 0x40f0, 0x0c08
ax_pose 21, 0x01fd, 0x0108, 0x0c0c
ax_pose 22, 0x01eb, 0x0110, 0x0c0d
ax_pose 23, 0x01f3, 0x0110, 0x0c0e
ax_pose_terminator
sArcaninePose157:
ax_pose 33, 0x01e5, 0x80f0, 0x0c00
ax_pose_terminator
sArcaninePose158:
ax_pose 3, 0x01e5, 0x80f0, 0x0c00
ax_pose_terminator
sArcaninePose159:
ax_pose 17, 0x01e5, 0x80f1, 0x0c00
ax_pose_terminator
sArcaninePose160:
ax_pose 31, 0x01e5, 0x80f0, 0x0c00
ax_pose_terminator
sArcaninePose161:
ax_pose 39, 0x01ee, 0x80f0, 0x0c00
ax_pose_terminator
sArcaninePose162:
ax_pose 40, 0x01ee, 0x80f0, 0x0c00
ax_pose_terminator
sArcaninePose163:
ax_pose 41, 0x01e3, 0x80f0, 0x0c00
ax_pose_terminator
sArcaninePose164:
ax_pose 42, 0x01e3, 0x90f0, 0x0c00
ax_pose_terminator
sArcaninePose165:
ax_pose 43, 0x01e3, 0x90f0, 0x0c00
ax_pose_terminator
sArcaninePose166:
ax_pose 44, 0x01e5, 0x90f0, 0x0c00
ax_pose_terminator
sArcaninePose167:
ax_pose 45, 0x01e4, 0x80f0, 0x0c00
ax_pose_terminator
sArcaninePose168:
ax_pose 44, 0x01e5, 0x80f0, 0x0c00
ax_pose_terminator
sArcaninePose169:
ax_pose 43, 0x01e3, 0x80f0, 0x0c00
ax_pose_terminator
sArcaninePose170:
ax_pose 42, 0x01e3, 0x80f0, 0x0c00
ax_pose_terminator
sArcaninePose171:
ax_pose 29, 0x01e5, 0x80f4, 0x0c00
ax_pose_terminator
sArcaninePose172:
ax_pose 31, 0x01e6, 0x80f0, 0x0c00
ax_pose_terminator
sArcaninePose173:
ax_pose 33, 0x01e5, 0x80f2, 0x0c00
ax_pose_terminator
sArcaninePose174:
ax_pose 35, 0x01e5, 0x80ef, 0x0c00
ax_pose_terminator
sArcaninePose175:
ax_pose 37, 0x01e4, 0x80f4, 0x0c00
ax_pose_terminator
sArcaninePose176:
ax_pose 35, 0x01e5, 0x90f0, 0x0c00
ax_pose_terminator
sArcaninePose177:
ax_pose 33, 0x01e5, 0x90ee, 0x0c00
ax_pose_terminator
sArcaninePose178:
ax_pose 31, 0x01e5, 0x90f0, 0x0c00
ax_pose_terminator
sArcaninePose179:
ax_pose 30, 0x01e4, 0x80f4, 0x0c00
ax_pose_terminator
sArcaninePose180:
ax_pose 32, 0x01e6, 0x80f0, 0x0c00
ax_pose_terminator
sArcaninePose181:
ax_pose 34, 0x01e5, 0x80ee, 0x0c00
ax_pose_terminator
sArcaninePose182:
ax_pose 36, 0x01e5, 0x80f0, 0x0c00
ax_pose_terminator
sArcaninePose183:
ax_pose 38, 0x01e5, 0x80f4, 0x0c00
ax_pose_terminator
sArcaninePose184:
ax_pose 36, 0x01e5, 0x90f0, 0x0c00
ax_pose_terminator
sArcaninePose185:
ax_pose 34, 0x01e5, 0x90f2, 0x0c00
ax_pose_terminator
sArcaninePose186:
ax_pose 32, 0x01e6, 0x90f0, 0x0c00
ax_pose_terminator
sArcaninePose187:
ax_pose 30, 0x01e4, 0x80f4, 0x0c00
ax_pose_terminator
sArcaninePose188:
ax_pose 32, 0x01e6, 0x90f0, 0x0c00
ax_pose_terminator
sArcaninePose189:
ax_pose 34, 0x01e5, 0x90f2, 0x0c00
ax_pose_terminator
sArcaninePose190:
ax_pose 36, 0x01e5, 0x90f0, 0x0c00
ax_pose_terminator
sArcaninePose191:
ax_pose 38, 0x01e5, 0x80f4, 0x0c00
ax_pose_terminator
sArcaninePose192:
ax_pose 36, 0x01e5, 0x80f0, 0x0c00
ax_pose_terminator
sArcaninePose193:
ax_pose 34, 0x01e5, 0x80ee, 0x0c00
ax_pose_terminator
sArcaninePose194:
ax_pose 32, 0x01e6, 0x80f0, 0x0c00
ax_pose_terminator
sArcaninePose195:
ax_pose 0, 0x01e5, 0x80f4, 0x0c00
ax_pose_terminator
sArcaninePose196:
ax_pose 15, 0x01e4, 0x80f4, 0x0c00
ax_pose_terminator
sArcaninePose197:
ax_pose 30, 0x01e4, 0x80f4, 0x0c00
ax_pose_terminator
sArcaninePose198:
ax_pose 3, 0x01e5, 0x90f0, 0x0c00
ax_pose_terminator
sArcaninePose199:
ax_pose 17, 0x01e5, 0x90ef, 0x0c00
ax_pose_terminator
sArcaninePose200:
ax_pose 32, 0x01e5, 0x90f0, 0x0c00
ax_pose_terminator
sArcaninePose201:
ax_pose 6, 0x01e5, 0x90f0, 0x0c00
ax_pose_terminator
sArcaninePose202:
ax_pose 19, 0x41e5, 0x90f0, 0x0c00
ax_pose 20, 0x41f5, 0x50f0, 0x0c08
ax_pose 21, 0x01fd, 0x10f0, 0x0c0c
ax_pose 22, 0x01eb, 0x10e8, 0x0c0d
ax_pose 23, 0x01f3, 0x10e8, 0x0c0e
ax_pose_terminator
sArcaninePose203:
ax_pose 34, 0x01e5, 0x90f1, 0x0c00
ax_pose_terminator
sArcaninePose204:
ax_pose 9, 0x01e5, 0x90f0, 0x0c00
ax_pose_terminator
sArcaninePose205:
ax_pose 25, 0x01e5, 0x90f0, 0x0c00
ax_pose_terminator
sArcaninePose206:
ax_pose 36, 0x01e5, 0x90ef, 0x0c00
ax_pose_terminator
sArcaninePose207:
ax_pose 12, 0x01e5, 0x80f4, 0x0c00
ax_pose_terminator
sArcaninePose208:
ax_pose 27, 0x01e5, 0x80f4, 0x0c00
ax_pose_terminator
sArcaninePose209:
ax_pose 38, 0x01e5, 0x80f4, 0x0c00
ax_pose_terminator
sArcaninePose210:
ax_pose 9, 0x01e5, 0x80f0, 0x0c00
ax_pose_terminator
sArcaninePose211:
ax_pose 25, 0x01e5, 0x80f0, 0x0c00
ax_pose_terminator
sArcaninePose212:
ax_pose 36, 0x01e5, 0x80f2, 0x0c00
ax_pose_terminator
sArcaninePose213:
ax_pose 6, 0x01e5, 0x80f0, 0x0c00
ax_pose_terminator
sArcaninePose214:
ax_pose 19, 0x41e5, 0x80f0, 0x0c00
ax_pose 20, 0x41f5, 0x40f0, 0x0c08
ax_pose 21, 0x01fd, 0x0108, 0x0c0c
ax_pose 22, 0x01eb, 0x0110, 0x0c0d
ax_pose 23, 0x01f3, 0x0110, 0x0c0e
ax_pose_terminator
sArcaninePose215:
ax_pose 34, 0x01e5, 0x80ef, 0x0c00
ax_pose_terminator
sArcaninePose216:
ax_pose 3, 0x01e5, 0x80f0, 0x0c00
ax_pose_terminator
sArcaninePose217:
ax_pose 17, 0x01e5, 0x80f1, 0x0c00
ax_pose_terminator
sArcaninePose218:
ax_pose 32, 0x01e5, 0x80f0, 0x0c00
ax_pose_terminator
sArcaninePose219:
ax_pose 29, 0x01e5, 0x80f4, 0x0c00
ax_pose_terminator
sArcaninePose220:
ax_pose 31, 0x01e6, 0x80f0, 0x0c00
ax_pose_terminator
sArcaninePose221:
ax_pose 33, 0x01e5, 0x80f2, 0x0c00
ax_pose_terminator
sArcaninePose222:
ax_pose 35, 0x01e5, 0x80ef, 0x0c00
ax_pose_terminator
sArcaninePose223:
ax_pose 37, 0x01e4, 0x80f4, 0x0c00
ax_pose_terminator
sArcaninePose224:
ax_pose 35, 0x01e5, 0x90f0, 0x0c00
ax_pose_terminator
sArcaninePose225:
ax_pose 33, 0x01e5, 0x90ee, 0x0c00
ax_pose_terminator
sArcaninePose226:
ax_pose 31, 0x01e5, 0x90f0, 0x0c00
ax_pose_terminator
sArcaninePose227:
ax_pose 0, 0x01e5, 0x80f4, 0x0c00
ax_pose_terminator
sArcaninePose228:
ax_pose 3, 0x01e5, 0x80f0, 0x0c00
ax_pose_terminator
sArcaninePose229:
ax_pose 6, 0x01e5, 0x80f0, 0x0c00
ax_pose_terminator
sArcaninePose230:
ax_pose 9, 0x01e5, 0x80f0, 0x0c00
ax_pose_terminator
sArcaninePose231:
ax_pose 12, 0x01e5, 0x80f4, 0x0c00
ax_pose_terminator
sArcaninePose232:
ax_pose 9, 0x01e5, 0x90f0, 0x0c00
ax_pose_terminator
sArcaninePose233:
ax_pose 6, 0x01e5, 0x90f0, 0x0c00
ax_pose_terminator
sArcaninePose234:
ax_pose 3, 0x01e5, 0x90f0, 0x0c00
ax_pose_terminator
.align 2
sArcanineAnims_1_1:
ax_anim 8, 0, 0, 0, 0, 0, 0,
ax_anim 10, 0, 1, 0, 0, 0, 0,
ax_anim 8, 0, 0, 0, 0, 0, 0,
ax_anim 10, 0, 2, 0, 0, 0, 0,
ax_anim_terminator
sArcanineAnims_1_2:
ax_anim 8, 0, 3, 0, 0, 0, 0,
ax_anim 10, 0, 4, 0, 0, 0, 0,
ax_anim 8, 0, 3, 0, 0, 0, 0,
ax_anim 10, 0, 5, 0, 0, 0, 0,
ax_anim_terminator
sArcanineAnims_1_3:
ax_anim 8, 0, 6, 0, 0, 0, 0,
ax_anim 10, 0, 7, 0, 0, 0, 0,
ax_anim 8, 0, 6, 0, 0, 0, 0,
ax_anim 10, 0, 8, 0, 0, 0, 0,
ax_anim_terminator
sArcanineAnims_1_4:
ax_anim 8, 0, 9, 0, 0, 0, 0,
ax_anim 10, 0, 10, 0, 0, 0, 0,
ax_anim 8, 0, 9, 0, 0, 0, 0,
ax_anim 10, 0, 11, 0, 0, 0, 0,
ax_anim_terminator
sArcanineAnims_1_5:
ax_anim 8, 0, 12, 0, 0, 0, 0,
ax_anim 10, 0, 13, 0, 0, 0, 0,
ax_anim 8, 0, 12, 0, 0, 0, 0,
ax_anim 10, 0, 14, 0, 0, 0, 0,
ax_anim_terminator
sArcanineAnims_1_6:
ax_anim 8, 0, 15, 0, 0, 0, 0,
ax_anim 10, 0, 16, 0, 0, 0, 0,
ax_anim 8, 0, 15, 0, 0, 0, 0,
ax_anim 10, 0, 17, 0, 0, 0, 0,
ax_anim_terminator
sArcanineAnims_1_7:
ax_anim 8, 0, 18, 0, 0, 0, 0,
ax_anim 10, 0, 19, 0, 0, 0, 0,
ax_anim 8, 0, 18, 0, 0, 0, 0,
ax_anim 10, 0, 20, 0, 0, 0, 0,
ax_anim_terminator
sArcanineAnims_1_8:
ax_anim 8, 0, 21, 0, 0, 0, 0,
ax_anim 10, 0, 22, 0, 0, 0, 0,
ax_anim 8, 0, 21, 0, 0, 0, 0,
ax_anim 10, 0, 23, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sArcanineAnims_2_1:
ax_anim 2, 0, 25, 0, -3, 0, -3,
ax_anim 2, 0, 26, 0, -6, 0, -6,
ax_anim 6, 0, 24, 0, -8, 0, -8,
ax_anim 1, 0, 27, 0, -2, 0, -2,
ax_anim 1, 0, 28, 0, 7, 0, 7,
ax_anim 2, 2, 27, 0, 9, 0, 9,
ax_anim 2, 0, 28, 0, 20, 0, 20,
ax_anim 2, 1, 28, -1, 20, -1, 20,
ax_anim 2, 0, 28, 0, 20, 0, 20,
ax_anim 2, 0, 28, -1, 20, -1, 20,
ax_anim 2, 0, 28, 0, 20, 0, 20,
ax_anim 2, 0, 25, 0, 11, 0, 11,
ax_anim 2, 0, 24, 0, 4, 0, 4,
ax_anim_terminator
sArcanineAnims_2_2:
ax_anim 2, 0, 30, -3, -3, -3, -3,
ax_anim 2, 0, 31, -6, -6, -6, -6,
ax_anim 6, 0, 29, -8, -8, -8, -8,
ax_anim 1, 0, 32, -2, -2, -2, -2,
ax_anim 1, 0, 33, 7, 7, 7, 7,
ax_anim 2, 2, 32, 11, 11, 11, 11,
ax_anim 2, 0, 33, 20, 18, 20, 18,
ax_anim 2, 1, 33, 19, 19, 19, 19,
ax_anim 2, 0, 33, 20, 18, 20, 18,
ax_anim 2, 0, 33, 19, 19, 19, 19,
ax_anim 2, 0, 33, 20, 18, 20, 18,
ax_anim 2, 0, 30, 11, 11, 11, 11,
ax_anim 2, 0, 29, 4, 4, 4, 4,
ax_anim_terminator
sArcanineAnims_2_3:
ax_anim 2, 0, 35, -3, 0, -3, 0,
ax_anim 2, 0, 36, -6, 0, -6, 0,
ax_anim 6, 0, 34, -8, 0, -8, 0,
ax_anim 1, 0, 37, -2, 0, -2, 0,
ax_anim 1, 0, 38, 5, 0, 5, 0,
ax_anim 2, 2, 37, 11, 0, 11, 0,
ax_anim 2, 0, 38, 18, 0, 18, 0,
ax_anim 2, 1, 38, 18, 1, 18, 1,
ax_anim 2, 0, 38, 18, 0, 18, 0,
ax_anim 2, 0, 38, 18, 1, 18, 1,
ax_anim 2, 0, 38, 18, 0, 18, 0,
ax_anim 2, 0, 35, 11, 0, 11, 0,
ax_anim 2, 0, 34, 4, 0, 4, 0,
ax_anim_terminator
sArcanineAnims_2_4:
ax_anim 2, 0, 40, -3, 3, -3, 3,
ax_anim 2, 0, 41, -6, 6, -6, 6,
ax_anim 6, 0, 39, -8, 8, -8, 8,
ax_anim 1, 0, 42, -2, 2, -2, 2,
ax_anim 1, 0, 43, 6, -9, 6, -9,
ax_anim 2, 2, 42, 9, -12, 9, -12,
ax_anim 2, 0, 43, 15, -21, 15, -21,
ax_anim 2, 1, 43, 14, -22, 14, -22,
ax_anim 2, 0, 43, 15, -21, 15, -21,
ax_anim 2, 0, 43, 14, -22, 14, -22,
ax_anim 2, 0, 43, 15, -21, 15, -21,
ax_anim 2, 0, 40, 9, -13, 9, -13,
ax_anim 2, 0, 39, 3, -5, 3, -5,
ax_anim_terminator
sArcanineAnims_2_5:
ax_anim 2, 0, 45, 0, 3, 0, 3,
ax_anim 2, 0, 46, 0, 6, 0, 6,
ax_anim 6, 0, 44, 0, 8, 0, 8,
ax_anim 1, 0, 47, 0, 2, 0, 2,
ax_anim 1, 0, 48, 0, -7, 0, -7,
ax_anim 2, 2, 47, 0, -9, 0, -9,
ax_anim 2, 0, 48, 0, -20, 0, -20,
ax_anim 2, 1, 48, -1, -20, -1, -20,
ax_anim 2, 0, 48, 0, -20, 0, -20,
ax_anim 2, 0, 48, -1, -20, -1, -20,
ax_anim 2, 0, 48, 0, -20, 0, -20,
ax_anim 2, 0, 45, 0, -11, 0, -11,
ax_anim 2, 0, 44, 0, -4, 0, -4,
ax_anim_terminator
sArcanineAnims_2_6:
ax_anim 2, 0, 50, 3, 3, 3, 3,
ax_anim 2, 0, 51, 6, 6, 6, 6,
ax_anim 6, 0, 49, 8, 8, 8, 8,
ax_anim 1, 0, 52, 2, 2, 2, 2,
ax_anim 1, 0, 53, -6, -9, -6, -9,
ax_anim 2, 2, 52, -9, -12, -9, -12,
ax_anim 2, 0, 53, -15, -21, -15, -21,
ax_anim 2, 1, 53, -14, -22, -14, -22,
ax_anim 2, 0, 53, -15, -21, -15, -21,
ax_anim 2, 0, 53, -14, -22, -14, -22,
ax_anim 2, 0, 53, -15, -21, -15, -21,
ax_anim 2, 0, 50, -9, -13, -9, -13,
ax_anim 2, 0, 49, -3, -5, -3, -5,
ax_anim_terminator
sArcanineAnims_2_7:
ax_anim 2, 0, 55, 3, 0, 3, 0,
ax_anim 2, 0, 56, 6, 0, 6, 0,
ax_anim 6, 0, 54, 8, 0, 8, 0,
ax_anim 1, 0, 57, 2, 0, 2, 0,
ax_anim 1, 0, 58, -5, 0, -5, 0,
ax_anim 2, 2, 57, -11, 0, -11, 0,
ax_anim 2, 0, 58, -18, 0, -18, 0,
ax_anim 2, 1, 58, -18, 1, -18, 1,
ax_anim 2, 0, 58, -18, 0, -18, 0,
ax_anim 2, 0, 58, -18, 1, -18, 1,
ax_anim 2, 0, 58, -18, 0, -18, 0,
ax_anim 2, 0, 55, -11, 0, -11, 0,
ax_anim 2, 0, 54, -4, 0, -4, 0,
ax_anim_terminator
sArcanineAnims_2_8:
ax_anim 2, 0, 60, 3, -3, 3, -3,
ax_anim 2, 0, 61, 6, -6, 6, -6,
ax_anim 6, 0, 59, 8, -8, 8, -8,
ax_anim 1, 0, 62, 2, -2, 2, -2,
ax_anim 1, 0, 63, -7, 7, -7, 7,
ax_anim 2, 2, 62, -9, 9, -9, 9,
ax_anim 2, 0, 63, -20, 18, -20, 18,
ax_anim 2, 1, 63, -19, 19, -19, 19,
ax_anim 2, 0, 63, -20, 18, -20, 18,
ax_anim 2, 0, 63, -19, 19, -19, 19,
ax_anim 2, 0, 63, -20, 18, -20, 18,
ax_anim 2, 0, 60, -11, 11, -11, 11,
ax_anim 2, 0, 59, -4, 4, -4, 4,
ax_anim_terminator
.align 2
sArcanineAnims_3_1:
ax_anim 2, 0, 65, 0, -3, 0, -3,
ax_anim 2, 0, 66, 0, -6, 0, -6,
ax_anim 6, 0, 64, 0, -8, 0, -8,
ax_anim 1, 0, 67, 0, 6, 0, 6,
ax_anim 1, 0, 68, 0, 23, 0, 23,
ax_anim 2, 2, 67, 0, 33, 0, 33,
ax_anim 2, 0, 68, 0, 44, 0, 44,
ax_anim 2, 1, 68, -1, 44, -1, 44,
ax_anim 2, 0, 68, 0, 44, 0, 44,
ax_anim 2, 0, 68, -1, 44, -1, 44,
ax_anim 2, 0, 68, 0, 44, 0, 44,
ax_anim 2, 0, 65, 0, 11, 0, 11,
ax_anim 2, 0, 64, 0, 4, 0, 4,
ax_anim_terminator
sArcanineAnims_3_2:
ax_anim 2, 0, 70, -3, -3, -3, -3,
ax_anim 2, 0, 71, -6, -6, -6, -6,
ax_anim 6, 0, 69, -8, -8, -8, -8,
ax_anim 1, 0, 72, -2, -2, -2, -2,
ax_anim 1, 0, 73, 15, 15, 15, 15,
ax_anim 2, 2, 72, 27, 27, 27, 27,
ax_anim 2, 0, 73, 44, 42, 44, 42,
ax_anim 2, 1, 73, 43, 43, 43, 43,
ax_anim 2, 0, 73, 44, 42, 44, 42,
ax_anim 2, 0, 73, 43, 43, 43, 43,
ax_anim 2, 0, 73, 44, 42, 44, 42,
ax_anim 2, 0, 70, 11, 11, 11, 11,
ax_anim 2, 0, 69, 4, 4, 4, 4,
ax_anim_terminator
sArcanineAnims_3_3:
ax_anim 2, 0, 75, -3, 0, -3, 0,
ax_anim 2, 0, 76, -6, 0, -6, 0,
ax_anim 6, 0, 74, -8, 0, -8, 0,
ax_anim 1, 0, 77, 6, 0, 6, 0,
ax_anim 1, 0, 78, 21, 0, 21, 0,
ax_anim 2, 2, 77, 35, 0, 35, 0,
ax_anim 2, 0, 78, 42, 0, 42, 0,
ax_anim 2, 1, 78, 42, 1, 42, 1,
ax_anim 2, 0, 78, 42, 0, 42, 0,
ax_anim 2, 0, 78, 42, 1, 42, 1,
ax_anim 2, 0, 78, 42, 0, 42, 0,
ax_anim 2, 0, 75, 11, 0, 11, 0,
ax_anim 2, 0, 74, 4, 0, 4, 0,
ax_anim_terminator
sArcanineAnims_3_4:
ax_anim 2, 0, 80, -3, 3, -3, 3,
ax_anim 2, 0, 81, -6, 6, -6, 6,
ax_anim 6, 0, 79, -8, 8, -8, 8,
ax_anim 1, 0, 82, 6, -6, 6, -6,
ax_anim 1, 0, 83, 22, -25, 22, -25,
ax_anim 2, 2, 82, 33, -36, 33, -36,
ax_anim 2, 0, 83, 39, -45, 39, -45,
ax_anim 2, 1, 83, 38, -46, 38, -46,
ax_anim 2, 0, 83, 39, -45, 39, -45,
ax_anim 2, 0, 83, 38, -46, 38, -46,
ax_anim 2, 0, 83, 39, -45, 39, -45,
ax_anim 2, 0, 80, 9, -13, 9, -13,
ax_anim 2, 0, 79, 3, -5, 3, -5,
ax_anim_terminator
sArcanineAnims_3_5:
ax_anim 2, 0, 85, 0, 3, 0, 3,
ax_anim 2, 0, 86, 0, 6, 0, 6,
ax_anim 6, 0, 84, 0, 8, 0, 8,
ax_anim 1, 0, 87, 0, -6, 0, -6,
ax_anim 1, 0, 88, 0, -23, 0, -23,
ax_anim 2, 2, 87, 0, -33, 0, -33,
ax_anim 2, 0, 88, 0, -44, 0, -44,
ax_anim 2, 1, 88, -1, -44, -1, -44,
ax_anim 2, 0, 88, 0, -44, 0, -44,
ax_anim 2, 0, 88, -1, -44, -1, -44,
ax_anim 2, 0, 88, 0, -44, 0, -44,
ax_anim 2, 0, 85, 0, -11, 0, -11,
ax_anim 2, 0, 84, 0, -4, 0, -4,
ax_anim_terminator
sArcanineAnims_3_6:
ax_anim 2, 0, 90, 3, 3, 3, 3,
ax_anim 2, 0, 91, 6, 6, 6, 6,
ax_anim 6, 0, 89, 8, 8, 8, 8,
ax_anim 1, 0, 92, -6, -6, -6, -6,
ax_anim 1, 0, 93, -22, -25, -22, -25,
ax_anim 2, 2, 92, -33, -36, -33, -36,
ax_anim 2, 0, 93, -39, -45, -39, -45,
ax_anim 2, 1, 93, -38, -46, -38, -46,
ax_anim 2, 0, 93, -39, -45, -39, -45,
ax_anim 2, 0, 93, -38, -46, -38, -46,
ax_anim 2, 0, 93, -39, -45, -39, -45,
ax_anim 2, 0, 90, -9, -13, -9, -13,
ax_anim 2, 0, 89, -3, -5, -3, -5,
ax_anim_terminator
sArcanineAnims_3_7:
ax_anim 2, 0, 95, 3, 0, 3, 0,
ax_anim 2, 0, 96, 6, 0, 6, 0,
ax_anim 6, 0, 94, 8, 0, 8, 0,
ax_anim 1, 0, 97, -6, 0, -6, 0,
ax_anim 1, 0, 98, -21, 0, -21, 0,
ax_anim 2, 2, 97, -35, 0, -35, 0,
ax_anim 2, 0, 98, -42, 0, -42, 0,
ax_anim 2, 1, 98, -42, 1, -42, 1,
ax_anim 2, 0, 98, -42, 0, -42, 0,
ax_anim 2, 0, 98, -42, 1, -42, 1,
ax_anim 2, 0, 98, -42, 0, -42, 0,
ax_anim 2, 0, 95, -11, 0, -11, 0,
ax_anim 2, 0, 94, -4, 0, -4, 0,
ax_anim_terminator
sArcanineAnims_3_8:
ax_anim 2, 0, 100, 3, -3, 3, -3,
ax_anim 2, 0, 101, 6, -6, 6, -6,
ax_anim 6, 0, 99, 8, -8, 8, -8,
ax_anim 1, 0, 102, -6, 6, -6, 6,
ax_anim 1, 0, 103, -23, 23, -23, 23,
ax_anim 2, 2, 102, -33, 33, -33, 33,
ax_anim 2, 0, 103, -44, 42, -44, 42,
ax_anim 2, 1, 103, -43, 43, -43, 43,
ax_anim 2, 0, 103, -44, 42, -44, 42,
ax_anim 2, 0, 103, -43, 43, -43, 43,
ax_anim 2, 0, 103, -44, 42, -44, 42,
ax_anim 2, 0, 100, -11, 11, -11, 11,
ax_anim 2, 0, 99, -4, 4, -4, 4,
ax_anim_terminator
.align 2
sArcanineAnims_4_1:
ax_anim 2, 0, 105, 0, -2, 0, -2,
ax_anim 2, 0, 104, 0, -4, 0, -4,
ax_anim 6, 2, 106, 0, -4, 0, -4,
ax_anim 1, 0, 106, 0, 0, 0, 0,
ax_anim 2, 0, 107, 0, 3, 0, 3,
ax_anim 2, 1, 107, 1, 3, 1, 3,
ax_anim 2, 0, 107, 0, 3, 0, 3,
ax_anim 2, 0, 107, 1, 3, 1, 3,
ax_anim 2, 0, 107, 0, 3, 0, 3,
ax_anim 2, 0, 107, 1, 3, 1, 3,
ax_anim 2, 0, 107, 0, 3, 0, 3,
ax_anim 2, 0, 104, 0, 1, 0, 1,
ax_anim_terminator
sArcanineAnims_4_2:
ax_anim 2, 0, 109, -2, -2, -2, -2,
ax_anim 2, 0, 109, -4, -4, -4, -4,
ax_anim 6, 2, 110, -5, -5, -5, -5,
ax_anim 1, 0, 110, 0, 0, 0, 0,
ax_anim 2, 0, 111, 3, 3, 3, 3,
ax_anim 2, 1, 111, 4, 2, 4, 2,
ax_anim 2, 0, 111, 3, 3, 3, 3,
ax_anim 2, 0, 111, 4, 2, 4, 2,
ax_anim 2, 0, 111, 3, 3, 3, 3,
ax_anim 2, 0, 111, 4, 2, 4, 2,
ax_anim 2, 0, 111, 3, 3, 3, 3,
ax_anim 2, 0, 108, 1, 1, 1, 1,
ax_anim_terminator
sArcanineAnims_4_3:
ax_anim 2, 0, 113, -2, 0, -2, 0,
ax_anim 2, 0, 113, -4, 0, -4, 0,
ax_anim 6, 2, 114, -5, 0, -5, 0,
ax_anim 1, 0, 114, 0, 0, 0, 0,
ax_anim 2, 0, 115, 3, 0, 3, 0,
ax_anim 2, 1, 115, 3, 1, 3, 1,
ax_anim 2, 0, 115, 3, 0, 3, 0,
ax_anim 2, 0, 115, 3, 1, 3, 1,
ax_anim 2, 0, 115, 3, 0, 3, 0,
ax_anim 2, 0, 115, 3, 1, 3, 1,
ax_anim 2, 0, 115, 3, 0, 3, 0,
ax_anim 2, 0, 112, 1, 0, 1, 0,
ax_anim_terminator
sArcanineAnims_4_4:
ax_anim 2, 0, 117, -2, 2, -2, 2,
ax_anim 2, 0, 117, -4, 4, -4, 4,
ax_anim 6, 2, 118, -5, 5, -5, 5,
ax_anim 1, 0, 118, 0, 0, 0, 0,
ax_anim 2, 0, 119, 3, -3, 3, -3,
ax_anim 2, 1, 119, 4, -2, 4, -2,
ax_anim 2, 0, 119, 3, -3, 3, -3,
ax_anim 2, 0, 119, 4, -2, 4, -2,
ax_anim 2, 0, 119, 3, -3, 3, -3,
ax_anim 2, 0, 119, 4, -2, 4, -2,
ax_anim 2, 0, 119, 3, -3, 3, -3,
ax_anim 2, 0, 116, 1, -1, 1, -1,
ax_anim_terminator
sArcanineAnims_4_5:
ax_anim 2, 0, 121, 0, 2, 0, 2,
ax_anim 2, 0, 121, 0, 3, 0, 3,
ax_anim 6, 2, 122, 0, 5, 0, 5,
ax_anim 1, 0, 122, 0, 0, 0, 0,
ax_anim 2, 0, 123, 0, -3, 0, -3,
ax_anim 2, 1, 123, 1, -3, 1, -3,
ax_anim 2, 0, 123, 0, -3, 0, -3,
ax_anim 2, 0, 123, 1, -3, 1, -3,
ax_anim 2, 0, 123, 0, -3, 0, -3,
ax_anim 2, 0, 123, 1, -3, 1, -3,
ax_anim 2, 0, 123, 0, -3, 0, -3,
ax_anim 2, 0, 120, 0, -2, 0, -2,
ax_anim_terminator
sArcanineAnims_4_6:
ax_anim 2, 0, 125, 2, 2, 2, 2,
ax_anim 2, 0, 125, 4, 4, 4, 4,
ax_anim 6, 2, 126, 5, 5, 5, 5,
ax_anim 1, 0, 126, 0, 0, 0, 0,
ax_anim 2, 0, 127, -3, -3, -3, -3,
ax_anim 2, 1, 127, -4, -2, -4, -2,
ax_anim 2, 0, 127, -3, -3, -3, -3,
ax_anim 2, 0, 127, -4, -2, -4, -2,
ax_anim 2, 0, 127, -3, -3, -3, -3,
ax_anim 2, 0, 127, -4, -2, -4, -2,
ax_anim 2, 0, 127, -3, -3, -3, -3,
ax_anim 2, 0, 124, -1, -1, -1, -1,
ax_anim_terminator
sArcanineAnims_4_7:
ax_anim 2, 0, 129, 2, 0, 2, 0,
ax_anim 2, 0, 129, 4, 0, 4, 0,
ax_anim 6, 2, 130, 5, 0, 5, 0,
ax_anim 1, 0, 130, 0, 0, 0, 0,
ax_anim 2, 0, 131, -3, 0, -3, 0,
ax_anim 2, 1, 131, -3, 1, -3, 1,
ax_anim 2, 0, 131, -3, 0, -3, 0,
ax_anim 2, 0, 131, -3, 1, -3, 1,
ax_anim 2, 0, 131, -3, 0, -3, 0,
ax_anim 2, 0, 131, -3, 1, -3, 1,
ax_anim 2, 0, 131, -3, 0, -3, 0,
ax_anim 2, 0, 128, -1, 0, -1, 0,
ax_anim_terminator
sArcanineAnims_4_8:
ax_anim 2, 0, 133, 2, -2, 2, -2,
ax_anim 2, 0, 133, 4, -4, 4, -4,
ax_anim 6, 2, 134, 5, -5, 5, -5,
ax_anim 1, 0, 134, 0, 0, 0, 0,
ax_anim 2, 0, 135, -3, 3, -3, 3,
ax_anim 2, 1, 135, -4, 2, -4, 2,
ax_anim 2, 0, 135, -3, 3, -3, 3,
ax_anim 2, 0, 135, -4, 2, -4, 2,
ax_anim 2, 0, 135, -3, 3, -3, 3,
ax_anim 2, 0, 135, -4, 2, -4, 2,
ax_anim 2, 0, 135, -3, 3, -3, 3,
ax_anim 2, 0, 132, -1, 1, -1, 1,
ax_anim_terminator
.align 2
sArcanineAnims_5_1:
ax_anim 2, 0, 137, 0, -1, 0, 0,
ax_anim 2, 0, 137, 0, -4, 0, 0,
ax_anim 3, 0, 137, 0, -8, 0, 0,
ax_anim 3, 0, 137, 0, -9, 0, 0,
ax_anim 3, 2, 137, 0, -8, 0, 0,
ax_anim 2, 0, 137, 0, -3, 0, 0,
ax_anim 4, 0, 136, 0, 0, 0, 0,
ax_anim 2, 0, 138, -1, 0, -1, 0,
ax_anim 2, 0, 138, 0, 0, 0, 0,
ax_anim 2, 1, 138, -1, 0, -1, 0,
ax_anim 2, 0, 138, 0, 0, 0, 0,
ax_anim 2, 0, 138, -1, 0, -1, 0,
ax_anim 2, 0, 138, 0, 0, 0, 0,
ax_anim_terminator
sArcanineAnims_5_2:
ax_anim 2, 0, 140, 0, 0, 0, 0,
ax_anim 2, 0, 140, 0, -3, 0, 0,
ax_anim 3, 0, 140, 0, -8, 0, 0,
ax_anim 3, 0, 140, 0, -9, 0, 0,
ax_anim 3, 2, 140, 0, -8, 0, 0,
ax_anim 2, 0, 140, 0, -2, 0, 0,
ax_anim 4, 0, 139, 0, 0, 0, 0,
ax_anim 2, 0, 141, -1, 1, -1, 1,
ax_anim 2, 0, 141, 0, 0, 0, 0,
ax_anim 2, 1, 141, -1, 1, -1, 1,
ax_anim 2, 0, 141, 0, 0, 0, 0,
ax_anim 2, 0, 141, -1, 1, -1, 1,
ax_anim 2, 0, 141, 0, 0, 0, 0,
ax_anim_terminator
sArcanineAnims_5_3:
ax_anim 2, 0, 143, 0, 0, 0, 0,
ax_anim 2, 0, 143, 0, -3, 0, 0,
ax_anim 3, 0, 143, 0, -8, 0, 0,
ax_anim 3, 0, 143, 0, -9, 0, 0,
ax_anim 3, 2, 143, 0, -8, 0, 0,
ax_anim 2, 0, 143, 0, -2, 0, 0,
ax_anim 4, 0, 142, 0, 0, 0, 0,
ax_anim 2, 0, 144, 0, 1, 0, 1,
ax_anim 2, 0, 144, 0, 0, 0, 0,
ax_anim 2, 1, 144, 0, 1, 0, 1,
ax_anim 2, 0, 144, 0, 0, 0, 0,
ax_anim 2, 0, 144, 0, 1, 0, 1,
ax_anim 2, 0, 144, 0, 0, 0, 0,
ax_anim_terminator
sArcanineAnims_5_4:
ax_anim 2, 0, 146, 0, 0, 0, 0,
ax_anim 2, 0, 146, 0, -3, 0, 0,
ax_anim 3, 0, 146, 0, -8, 0, 0,
ax_anim 3, 0, 146, 0, -9, 0, 0,
ax_anim 3, 2, 146, 0, -8, 0, 0,
ax_anim 2, 0, 146, 0, -2, 0, 0,
ax_anim 4, 0, 145, 0, 0, 0, 0,
ax_anim 2, 0, 147, 1, 1, 1, 1,
ax_anim 2, 0, 147, 0, 0, 0, 0,
ax_anim 2, 1, 147, 1, 1, 1, 1,
ax_anim 2, 0, 147, 0, 0, 0, 0,
ax_anim 2, 0, 147, 1, 1, 1, 1,
ax_anim 2, 0, 147, 0, 0, 0, 0,
ax_anim_terminator
sArcanineAnims_5_5:
ax_anim 2, 0, 149, 0, 0, 0, 0,
ax_anim 2, 0, 149, 0, -3, 0, 0,
ax_anim 3, 0, 149, 0, -8, 0, 0,
ax_anim 3, 0, 149, 0, -9, 0, 0,
ax_anim 3, 2, 149, 0, -8, 0, 0,
ax_anim 2, 0, 149, 0, -2, 0, 0,
ax_anim 4, 0, 148, 0, 0, 0, 0,
ax_anim 2, 0, 150, -1, 0, -1, 0,
ax_anim 2, 0, 150, 0, 0, 0, 0,
ax_anim 2, 1, 150, -1, 0, -1, 0,
ax_anim 2, 0, 150, 0, 0, 0, 0,
ax_anim 2, 0, 150, -1, 0, -1, 0,
ax_anim 2, 0, 150, 0, 0, 0, 0,
ax_anim_terminator
sArcanineAnims_5_6:
ax_anim 2, 0, 152, 0, 0, 0, 0,
ax_anim 2, 0, 152, 0, -3, 0, 0,
ax_anim 3, 0, 152, 0, -8, 0, 0,
ax_anim 3, 0, 152, 0, -9, 0, 0,
ax_anim 3, 2, 152, 0, -8, 0, 0,
ax_anim 2, 0, 152, 0, -2, 0, 0,
ax_anim 4, 0, 151, 0, 0, 0, 0,
ax_anim 2, 0, 153, -1, 1, -1, 1,
ax_anim 2, 0, 153, 0, 0, 0, 0,
ax_anim 2, 1, 153, -1, 1, -1, 1,
ax_anim 2, 0, 153, 0, 0, 0, 0,
ax_anim 2, 0, 153, -1, 1, -1, 1,
ax_anim 2, 0, 153, 0, 0, 0, 0,
ax_anim_terminator
sArcanineAnims_5_7:
ax_anim 2, 0, 155, 0, 0, 0, 0,
ax_anim 2, 0, 155, 0, -3, 0, 0,
ax_anim 3, 0, 155, 0, -8, 0, 0,
ax_anim 3, 0, 155, 0, -9, 0, 0,
ax_anim 3, 2, 155, 0, -8, 0, 0,
ax_anim 2, 0, 155, 0, -2, 0, 0,
ax_anim 4, 0, 154, 0, 0, 0, 0,
ax_anim 2, 0, 156, 0, 1, 0, 1,
ax_anim 2, 0, 156, 0, 0, 0, 0,
ax_anim 2, 1, 156, 0, 1, 0, 1,
ax_anim 2, 0, 156, 0, 0, 0, 0,
ax_anim 2, 0, 156, 0, 1, 0, 1,
ax_anim 2, 0, 156, 0, 0, 0, 0,
ax_anim_terminator
sArcanineAnims_5_8:
ax_anim 2, 0, 158, 0, 0, 0, 0,
ax_anim 2, 0, 158, 0, -3, 0, 0,
ax_anim 3, 0, 158, 0, -8, 0, 0,
ax_anim 3, 0, 158, 0, -9, 0, 0,
ax_anim 3, 2, 158, 0, -8, 0, 0,
ax_anim 2, 0, 158, 0, -2, 0, 0,
ax_anim 4, 0, 157, 0, 0, 0, 0,
ax_anim 2, 0, 159, 1, 1, 1, 1,
ax_anim 2, 0, 159, 0, 0, 0, 0,
ax_anim 2, 1, 159, 1, 1, 1, 1,
ax_anim 2, 0, 159, 0, 0, 0, 0,
ax_anim 2, 0, 159, 1, 1, 1, 1,
ax_anim 2, 0, 159, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sArcanineAnims_6_1:
ax_anim 30, 0, 160, 0, 0, 0, 0,
ax_anim 35, 0, 161, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sArcanineAnims_7_1:
ax_anim 2, 0, 162, 0, -2, 0, -2,
ax_anim 8, 0, 162, 0, -3, 0, -3,
ax_anim_terminator
sArcanineAnims_7_2:
ax_anim 2, 0, 163, -2, -2, -2, -2,
ax_anim 8, 0, 163, -3, -3, -3, -3,
ax_anim_terminator
sArcanineAnims_7_3:
ax_anim 2, 0, 164, -2, 0, -2, 0,
ax_anim 8, 0, 164, -3, 0, -3, 0,
ax_anim_terminator
sArcanineAnims_7_4:
ax_anim 2, 0, 165, -2, 2, -2, 2,
ax_anim 8, 0, 165, -3, 3, -3, 3,
ax_anim_terminator
sArcanineAnims_7_5:
ax_anim 2, 0, 166, 0, 2, 0, 2,
ax_anim 8, 0, 166, 0, 3, 0, 3,
ax_anim_terminator
sArcanineAnims_7_6:
ax_anim 2, 0, 167, 2, 2, 2, 2,
ax_anim 8, 0, 167, 3, 3, 3, 3,
ax_anim_terminator
sArcanineAnims_7_7:
ax_anim 2, 0, 168, 2, 0, 2, 0,
ax_anim 8, 0, 168, 3, 0, 3, 0,
ax_anim_terminator
sArcanineAnims_7_8:
ax_anim 2, 0, 169, 2, -2, 2, -2,
ax_anim 8, 0, 169, 3, -3, 3, -3,
ax_anim_terminator
.align 2
sArcanineAnims_8_1:
ax_anim 8, 0, 170, 0, 0, 0, 0,
ax_anim_terminator
sArcanineAnims_8_2:
ax_anim 8, 0, 177, 0, 0, 0, 0,
ax_anim_terminator
sArcanineAnims_8_3:
ax_anim 8, 0, 176, 0, 0, 0, 0,
ax_anim_terminator
sArcanineAnims_8_4:
ax_anim 8, 0, 175, 0, 0, 0, 0,
ax_anim_terminator
sArcanineAnims_8_5:
ax_anim 8, 0, 174, 0, 0, 0, 0,
ax_anim_terminator
sArcanineAnims_8_6:
ax_anim 8, 0, 173, 0, 0, 0, 0,
ax_anim_terminator
sArcanineAnims_8_7:
ax_anim 8, 0, 172, 0, 0, 0, 0,
ax_anim_terminator
sArcanineAnims_8_8:
ax_anim 8, 0, 171, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sArcanineAnims_9_1:
ax_anim 2, 0, 178, 0, 0, 0, 0,
ax_anim 1, 0, 179, 6, 3, 6, 3,
ax_anim 2, 0, 180, 8, 9, 8, 9,
ax_anim 2, 0, 181, 7, 16, 7, 16,
ax_anim 3, 0, 182, 0, 18, 0, 18,
ax_anim 2, 3, 183, -7, 16, -7, 16,
ax_anim 2, 0, 184, -8, 9, -8, 9,
ax_anim 1, 0, 185, -6, 3, -6, 3,
ax_anim 1, 0, 178, 0, 0, 0, 0,
ax_anim_terminator
sArcanineAnims_9_2:
ax_anim 2, 0, 185, 0, 0, 0, 0,
ax_anim 1, 0, 178, 8, 0, 8, 0,
ax_anim 2, 0, 179, 19, 3, 19, 3,
ax_anim 2, 0, 180, 21, 10, 21, 10,
ax_anim 3, 0, 181, 18, 19, 18, 19,
ax_anim 2, 3, 182, 11, 19, 11, 19,
ax_anim 2, 0, 183, 5, 14, 5, 14,
ax_anim 1, 0, 184, 0, 7, 0, 7,
ax_anim 1, 0, 185, 0, 0, 0, 0,
ax_anim_terminator
sArcanineAnims_9_3:
ax_anim 2, 0, 184, 0, 0, 0, 0,
ax_anim 1, 0, 185, 3, -5, 3, -5,
ax_anim 2, 0, 178, 11, -6, 11, -6,
ax_anim 2, 0, 179, 16, -5, 16, -5,
ax_anim 3, 0, 180, 18, -2, 18, -2,
ax_anim 2, 3, 181, 16, 4, 16, 4,
ax_anim 2, 0, 182, 12, 5, 12, 5,
ax_anim 1, 0, 183, 4, 5, 4, 5,
ax_anim 1, 0, 184, 0, 0, 0, 0,
ax_anim_terminator
sArcanineAnims_9_4:
ax_anim 2, 0, 183, 0, 0, 0, 0,
ax_anim 1, 0, 184, -1, -6, -1, -6,
ax_anim 2, 0, 185, 4, -16, 4, -16,
ax_anim 2, 0, 178, 12, -22, 12, -22,
ax_anim 3, 0, 179, 19, -21, 19, -21,
ax_anim 2, 3, 180, 22, -15, 22, -15,
ax_anim 2, 0, 181, 17, -4, 17, -4,
ax_anim 1, 0, 182, 7, -1, 7, -1,
ax_anim 1, 0, 183, 0, 0, 0, 0,
ax_anim_terminator
sArcanineAnims_9_5:
ax_anim 2, 0, 182, 0, 0, 0, 0,
ax_anim 1, 0, 183, -8, -4, -8, -4,
ax_anim 2, 0, 184, -9, -12, -9, -12,
ax_anim 2, 0, 185, -7, -18, -7, -18,
ax_anim 3, 0, 178, 0, -21, 0, -22,
ax_anim 2, 3, 179, 7, -18, 7, -18,
ax_anim 2, 0, 180, 9, -10, 9, -10,
ax_anim 1, 0, 181, 8, -4, 8, -4,
ax_anim 1, 0, 182, 0, 0, 0, 0,
ax_anim_terminator
sArcanineAnims_9_6:
ax_anim 2, 0, 181, 0, 0, 0, 0,
ax_anim 1, 0, 180, 1, -6, 1, -6,
ax_anim 2, 0, 179, -4, -16, -4, -16,
ax_anim 2, 0, 178, -12, -22, -12, -22,
ax_anim 3, 0, 185, -19, -21, -19, -21,
ax_anim 2, 3, 184, -22, -15, -22, -15,
ax_anim 2, 0, 183, -17, -4, -17, -4,
ax_anim 1, 0, 182, -7, -1, -7, -1,
ax_anim 1, 0, 181, 0, 0, 0, 0,
ax_anim_terminator
sArcanineAnims_9_7:
ax_anim 2, 0, 180, 0, 0, 0, 0,
ax_anim 1, 0, 179, -3, -5, -3, -5,
ax_anim 2, 0, 178, -11, -6, -11, -6,
ax_anim 2, 0, 185, -16, -5, -16, -5,
ax_anim 3, 0, 184, -18, -2, -18, -2,
ax_anim 2, 3, 183, -18, 4, -18, 4,
ax_anim 2, 0, 182, -12, 5, -12, 5,
ax_anim 1, 0, 181, -4, 5, -4, 5,
ax_anim 1, 0, 180, 0, 0, 0, 0,
ax_anim_terminator
sArcanineAnims_9_8:
ax_anim 2, 0, 179, 0, 0, 0, 0,
ax_anim 1, 0, 178, -8, 0, -8, 0,
ax_anim 2, 0, 185, -19, 3, -19, 3,
ax_anim 2, 0, 184, -21, 10, -21, 10,
ax_anim 3, 0, 183, -18, 19, -18, 19,
ax_anim 2, 3, 182, -11, 19, -11, 19,
ax_anim 2, 0, 181, -5, 14, -5, 14,
ax_anim 1, 0, 180, 0, 7, 0, 7,
ax_anim 1, 0, 179, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sArcanineAnims_10_1:
ax_anim 2, 0, 186, 0, 0, 0, 0,
ax_anim 2, 0, 186, 6, 0, 6, 0,
ax_anim 2, 0, 186, -6, 0, -6, 0,
ax_anim 2, 0, 186, 10, 0, 10, 0,
ax_anim 2, 0, 186, -10, 0, -10, 0,
ax_anim 2, 0, 186, 12, 0, 12, 0,
ax_anim 3, 0, 186, -12, 0, -12, 0,
ax_anim 3, 0, 186, 13, 0, 13, 0,
ax_anim 3, 0, 186, -13, 0, -13, 0,
ax_anim 2, 0, 186, 12, 0, 12, 0,
ax_anim 3, 0, 186, -12, 0, -12, 0,
ax_anim 2, 0, 186, 10, 0, 10, 0,
ax_anim 2, 0, 186, -10, 0, -10, 0,
ax_anim 2, 0, 186, 6, 0, 6, 0,
ax_anim 2, 0, 186, -6, 0, -6, 0,
ax_anim 2, 0, 186, 0, 0, 0, 0,
ax_anim_terminator
sArcanineAnims_10_2:
ax_anim 2, 0, 187, 0, 0, 0, 0,
ax_anim 2, 0, 187, 6, -6, 6, -6,
ax_anim 2, 0, 187, -6, 6, -6, 6,
ax_anim 2, 0, 187, 10, -10, 10, -10,
ax_anim 2, 0, 187, -10, 10, -10, 10,
ax_anim 2, 0, 187, 12, -12, 12, -12,
ax_anim 3, 0, 187, -12, 12, -12, 12,
ax_anim 3, 0, 187, 13, -13, 13, -13,
ax_anim 3, 0, 187, -13, 13, -13, 13,
ax_anim 2, 0, 187, 12, -12, 12, -12,
ax_anim 3, 0, 187, -12, 12, -12, 12,
ax_anim 2, 0, 187, 10, -10, 10, -10,
ax_anim 2, 0, 187, -10, 10, -10, 10,
ax_anim 2, 0, 187, 6, -6, 6, -6,
ax_anim 2, 0, 187, -6, 6, -6, 6,
ax_anim 2, 0, 187, 0, 0, 0, 0,
ax_anim_terminator
sArcanineAnims_10_3:
ax_anim 2, 0, 188, 0, 0, 0, 0,
ax_anim 2, 0, 188, 0, -6, 0, -6,
ax_anim 2, 0, 188, 0, 6, 0, 6,
ax_anim 2, 0, 188, 0, -10, 0, -10,
ax_anim 2, 0, 188, 0, 10, 0, 10,
ax_anim 2, 0, 188, 0, -12, 0, -12,
ax_anim 3, 0, 188, 0, 12, 0, 12,
ax_anim 3, 0, 188, 0, -13, 0, -13,
ax_anim 3, 0, 188, 0, 13, 0, 13,
ax_anim 2, 0, 188, 0, -12, 0, -12,
ax_anim 3, 0, 188, 0, 12, 0, 12,
ax_anim 2, 0, 188, 0, -10, 0, -10,
ax_anim 2, 0, 188, 0, 10, 0, 10,
ax_anim 2, 0, 188, 0, -6, 0, -6,
ax_anim 2, 0, 188, 0, 6, 0, 6,
ax_anim 2, 0, 188, 0, 0, 0, 0,
ax_anim_terminator
sArcanineAnims_10_4:
ax_anim 2, 0, 189, 0, 0, 0, 0,
ax_anim 2, 0, 189, -6, -6, -6, -6,
ax_anim 2, 0, 189, 6, 6, 6, 6,
ax_anim 2, 0, 189, -10, -10, -10, -10,
ax_anim 2, 0, 189, 10, 10, 10, 10,
ax_anim 2, 0, 189, -12, -12, -12, -12,
ax_anim 3, 0, 189, 12, 12, 12, 12,
ax_anim 3, 0, 189, -13, -13, -13, -13,
ax_anim 3, 0, 189, 13, 13, 13, 13,
ax_anim 2, 0, 189, -12, -12, -12, -12,
ax_anim 3, 0, 189, 12, 12, 12, 12,
ax_anim 2, 0, 189, -10, -10, -10, -10,
ax_anim 2, 0, 189, 10, 10, 10, 10,
ax_anim 2, 0, 189, -6, -6, -6, -6,
ax_anim 2, 0, 189, 6, 6, 6, 6,
ax_anim 2, 0, 189, 0, 0, 0, 0,
ax_anim_terminator
sArcanineAnims_10_5:
ax_anim 2, 0, 190, 0, 0, 0, 0,
ax_anim 2, 0, 190, 6, 0, 6, 0,
ax_anim 2, 0, 190, -6, 0, -6, 0,
ax_anim 2, 0, 190, 10, 0, 10, 0,
ax_anim 2, 0, 190, -10, 0, -10, 0,
ax_anim 2, 0, 190, 12, 0, 12, 0,
ax_anim 3, 0, 190, -12, 0, -12, 0,
ax_anim 3, 0, 190, 13, 0, 13, 0,
ax_anim 3, 0, 190, -13, 0, -13, 0,
ax_anim 2, 0, 190, 12, 0, 12, 0,
ax_anim 3, 0, 190, -12, 0, -12, 0,
ax_anim 2, 0, 190, 10, 0, 10, 0,
ax_anim 2, 0, 190, -10, 0, -10, 0,
ax_anim 2, 0, 190, 6, 0, 6, 0,
ax_anim 2, 0, 190, -6, 0, -6, 0,
ax_anim 2, 0, 190, 0, 0, 0, 0,
ax_anim_terminator
sArcanineAnims_10_6:
ax_anim 2, 0, 191, 0, 0, 0, 0,
ax_anim 2, 0, 191, 6, -6, 6, -6,
ax_anim 2, 0, 191, -6, 6, -6, 6,
ax_anim 2, 0, 191, 10, -10, 10, -10,
ax_anim 2, 0, 191, -10, 10, -10, 10,
ax_anim 2, 0, 191, 12, -12, 12, -12,
ax_anim 3, 0, 191, -12, 12, -12, 12,
ax_anim 3, 0, 191, 13, -13, 13, -13,
ax_anim 3, 0, 191, -13, 13, -13, 13,
ax_anim 2, 0, 191, 12, -12, 12, -12,
ax_anim 3, 0, 191, -12, 12, -12, 12,
ax_anim 2, 0, 191, 10, -10, 10, -10,
ax_anim 2, 0, 191, -10, 10, -10, 10,
ax_anim 2, 0, 191, 6, -6, 6, -6,
ax_anim 2, 0, 191, -6, 6, -6, 6,
ax_anim 2, 0, 191, 0, 0, 0, 0,
ax_anim_terminator
sArcanineAnims_10_7:
ax_anim 2, 0, 192, 0, 0, 0, 0,
ax_anim 2, 0, 192, 0, -6, 0, -6,
ax_anim 2, 0, 192, 0, 6, 0, 6,
ax_anim 2, 0, 192, 0, -10, 0, -10,
ax_anim 2, 0, 192, 0, 10, 0, 10,
ax_anim 2, 0, 192, 0, -12, 0, -12,
ax_anim 3, 0, 192, 0, 12, 0, 12,
ax_anim 3, 0, 192, 0, -13, 0, -13,
ax_anim 3, 0, 192, 0, 13, 0, 13,
ax_anim 2, 0, 192, 0, -12, 0, -12,
ax_anim 3, 0, 192, 0, 12, 0, 12,
ax_anim 2, 0, 192, 0, -10, 0, -10,
ax_anim 2, 0, 192, 0, 10, 0, 10,
ax_anim 2, 0, 192, 0, -6, 0, -6,
ax_anim 2, 0, 192, 0, 6, 0, 6,
ax_anim 2, 0, 192, 0, 0, 0, 0,
ax_anim_terminator
sArcanineAnims_10_8:
ax_anim 2, 0, 193, 0, 0, 0, 0,
ax_anim 2, 0, 193, -6, -6, -6, -6,
ax_anim 2, 0, 193, 6, 6, 6, 6,
ax_anim 2, 0, 193, -10, -10, -10, -10,
ax_anim 2, 0, 193, 10, 10, 10, 10,
ax_anim 2, 0, 193, -12, -12, -12, -12,
ax_anim 3, 0, 193, 12, 12, 12, 12,
ax_anim 3, 0, 193, -13, -13, -13, -13,
ax_anim 3, 0, 193, 13, 13, 13, 13,
ax_anim 2, 0, 193, -12, -12, -12, -12,
ax_anim 3, 0, 193, 12, 12, 12, 12,
ax_anim 2, 0, 193, -10, -10, -10, -10,
ax_anim 2, 0, 193, 10, 10, 10, 10,
ax_anim 2, 0, 193, -6, -6, -6, -6,
ax_anim 2, 0, 193, 6, 6, 6, 6,
ax_anim 2, 0, 193, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sArcanineAnims_11_1:
ax_anim 2, 0, 194, 0, 0, 0, 0,
ax_anim 1, 0, 195, 0, -10, 0, 0,
ax_anim 2, 0, 195, 0, -16, 0, 0,
ax_anim 3, 0, 195, 0, -20, 0, 0,
ax_anim 4, 0, 195, 0, -21, 0, 0,
ax_anim 4, 0, 196, 0, -23, 0, 0,
ax_anim 3, 0, 196, 0, -22, 0, 0,
ax_anim 2, 0, 196, 0, -18, 0, 0,
ax_anim 1, 0, 196, 0, -12, 0, 0,
ax_anim 2, 2, 194, 0, 0, 0, 0,
ax_anim_terminator
sArcanineAnims_11_2:
ax_anim 2, 0, 197, 0, 0, 0, 0,
ax_anim 1, 0, 198, 0, -10, 0, 0,
ax_anim 2, 0, 198, 0, -16, 0, 0,
ax_anim 3, 0, 198, 0, -20, 0, 0,
ax_anim 4, 0, 198, 0, -21, 0, 0,
ax_anim 4, 0, 199, 0, -23, 0, 0,
ax_anim 3, 0, 199, 0, -22, 0, 0,
ax_anim 2, 0, 199, 0, -18, 0, 0,
ax_anim 1, 0, 199, 0, -12, 0, 0,
ax_anim 2, 2, 197, 0, 0, 0, 0,
ax_anim_terminator
sArcanineAnims_11_3:
ax_anim 2, 0, 200, 0, 0, 0, 0,
ax_anim 1, 0, 201, 0, -10, 0, 0,
ax_anim 2, 0, 201, 0, -16, 0, 0,
ax_anim 3, 0, 201, 0, -20, 0, 0,
ax_anim 4, 0, 201, 0, -21, 0, 0,
ax_anim 4, 0, 202, 0, -23, 0, 0,
ax_anim 3, 0, 202, 0, -22, 0, 0,
ax_anim 2, 0, 202, 0, -18, 0, 0,
ax_anim 1, 0, 202, 0, -12, 0, 0,
ax_anim 2, 2, 200, 0, 0, 0, 0,
ax_anim_terminator
sArcanineAnims_11_4:
ax_anim 2, 0, 203, 0, 0, 0, 0,
ax_anim 1, 0, 204, 0, -10, 0, 0,
ax_anim 2, 0, 204, 0, -16, 0, 0,
ax_anim 3, 0, 204, 0, -20, 0, 0,
ax_anim 4, 0, 204, 0, -21, 0, 0,
ax_anim 4, 0, 205, 0, -22, 0, 0,
ax_anim 3, 0, 205, 0, -21, 0, 0,
ax_anim 2, 0, 205, 0, -17, 0, 0,
ax_anim 1, 0, 205, 0, -11, 0, 0,
ax_anim 2, 2, 203, 0, 0, 0, 0,
ax_anim_terminator
sArcanineAnims_11_5:
ax_anim 2, 0, 206, 0, 0, 0, 0,
ax_anim 1, 0, 207, 0, -10, 0, 0,
ax_anim 2, 0, 207, 0, -16, 0, 0,
ax_anim 3, 0, 207, 0, -20, 0, 0,
ax_anim 4, 0, 207, 0, -21, 0, 0,
ax_anim 4, 0, 208, 0, -23, 0, 0,
ax_anim 3, 0, 208, 0, -22, 0, 0,
ax_anim 2, 0, 208, 0, -18, 0, 0,
ax_anim 1, 0, 208, 0, -12, 0, 0,
ax_anim 2, 2, 206, 0, 0, 0, 0,
ax_anim_terminator
sArcanineAnims_11_6:
ax_anim 2, 0, 209, 0, 0, 0, 0,
ax_anim 1, 0, 210, 0, -10, 0, 0,
ax_anim 2, 0, 210, 0, -16, 0, 0,
ax_anim 3, 0, 210, 0, -20, 0, 0,
ax_anim 4, 0, 210, 0, -21, 0, 0,
ax_anim 4, 0, 211, 0, -22, 0, 0,
ax_anim 3, 0, 211, 0, -21, 0, 0,
ax_anim 2, 0, 211, 0, -17, 0, 0,
ax_anim 1, 0, 211, 0, -11, 0, 0,
ax_anim 2, 2, 209, 0, 0, 0, 0,
ax_anim_terminator
sArcanineAnims_11_7:
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 1, 0, 213, 0, -10, 0, 0,
ax_anim 2, 0, 213, 0, -16, 0, 0,
ax_anim 3, 0, 213, 0, -20, 0, 0,
ax_anim 4, 0, 213, 0, -21, 0, 0,
ax_anim 4, 0, 214, 0, -23, 0, 0,
ax_anim 3, 0, 214, 0, -22, 0, 0,
ax_anim 2, 0, 214, 0, -18, 0, 0,
ax_anim 1, 0, 214, 0, -12, 0, 0,
ax_anim 2, 2, 212, 0, 0, 0, 0,
ax_anim_terminator
sArcanineAnims_11_8:
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 1, 0, 216, 0, -10, 0, 0,
ax_anim 2, 0, 216, 0, -16, 0, 0,
ax_anim 3, 0, 216, 0, -20, 0, 0,
ax_anim 4, 0, 216, 0, -21, 0, 0,
ax_anim 4, 0, 217, 0, -23, 0, 0,
ax_anim 3, 0, 217, 0, -22, 0, 0,
ax_anim 2, 0, 217, 0, -18, 0, 0,
ax_anim 1, 0, 217, 0, -12, 0, 0,
ax_anim 2, 2, 215, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sArcanineAnims_12_1:
ax_anim 2, 0, 218, 1, 0, 1, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 218, 1, 0, 1, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 218, 1, 0, 1, 0,
ax_anim 2, 2, 218, 0, 0, 0, 0,
ax_anim 2, 0, 218, 1, 0, 1, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 218, 1, 0, 1, 0,
ax_anim 2, 1, 218, 0, 0, 0, 0,
ax_anim_terminator
sArcanineAnims_12_2:
ax_anim 2, 0, 225, 1, -1, 1, -1,
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 2, 0, 225, 1, -1, 1, -1,
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 2, 0, 225, 1, -1, 1, -1,
ax_anim 2, 2, 225, 0, 0, 0, 0,
ax_anim 2, 0, 225, 1, -1, 1, -1,
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 2, 0, 225, 1, -1, 1, -1,
ax_anim 2, 1, 225, 0, 0, 0, 0,
ax_anim_terminator
sArcanineAnims_12_3:
ax_anim 2, 0, 224, 0, -1, 0, -1,
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 2, 0, 224, 0, -1, 0, -1,
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 2, 0, 224, 0, -1, 0, -1,
ax_anim 2, 2, 224, 0, 0, 0, 0,
ax_anim 2, 0, 224, 0, -1, 0, -1,
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 2, 0, 224, 0, -1, 0, -1,
ax_anim 2, 1, 224, 0, 0, 0, 0,
ax_anim_terminator
sArcanineAnims_12_4:
ax_anim 2, 0, 223, -1, -1, -1, -1,
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 2, 0, 223, -1, -1, -1, -1,
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 2, 0, 223, -1, -1, -1, -1,
ax_anim 2, 2, 223, 0, 0, 0, 0,
ax_anim 2, 0, 223, -1, -1, -1, -1,
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 2, 0, 223, -1, -1, -1, -1,
ax_anim 2, 1, 223, 0, 0, 0, 0,
ax_anim_terminator
sArcanineAnims_12_5:
ax_anim 2, 0, 222, 1, 0, 1, 0,
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 0, 222, 1, 0, 1, 0,
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 0, 222, 1, 0, 1, 0,
ax_anim 2, 2, 222, 0, 0, 0, 0,
ax_anim 2, 0, 222, 1, 0, 1, 0,
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 0, 222, 1, 0, 1, 0,
ax_anim 2, 1, 222, 0, 0, 0, 0,
ax_anim_terminator
sArcanineAnims_12_6:
ax_anim 2, 0, 221, 1, -1, 1, -1,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 221, 1, -1, 1, -1,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 221, 1, -1, 1, -1,
ax_anim 2, 2, 221, 0, 0, 0, 0,
ax_anim 2, 0, 221, 1, -1, 1, -1,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 221, 1, -1, 1, -1,
ax_anim 2, 1, 221, 0, 0, 0, 0,
ax_anim_terminator
sArcanineAnims_12_7:
ax_anim 2, 0, 220, 0, -1, 0, -1,
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, -1, 0, -1,
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, -1, 0, -1,
ax_anim 2, 2, 220, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, -1, 0, -1,
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, -1, 0, -1,
ax_anim 2, 1, 220, 0, 0, 0, 0,
ax_anim_terminator
sArcanineAnims_12_8:
ax_anim 2, 0, 219, -1, -1, -1, -1,
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 0, 219, -1, -1, -1, -1,
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 0, 219, -1, -1, -1, -1,
ax_anim 2, 2, 219, 0, 0, 0, 0,
ax_anim 2, 0, 219, -1, -1, -1, -1,
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 0, 219, -1, -1, -1, -1,
ax_anim 2, 1, 219, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sArcanineAnims_13_1:
ax_anim 2, 0, 226, 0, 0, 0, 0,
ax_anim 2, 0, 227, 0, 0, 0, 0,
ax_anim 2, 0, 228, 0, 0, 0, 0,
ax_anim 2, 0, 229, 0, 0, 0, 0,
ax_anim 2, 0, 230, 0, 0, 0, 0,
ax_anim 2, 0, 231, 0, 0, 0, 0,
ax_anim 2, 0, 232, 0, 0, 0, 0,
ax_anim 2, 0, 233, 0, 0, 0, 0,
ax_anim 2, 2, 226, 0, 0, 0, 0,
ax_anim_terminator
sArcanineAnims_13_2:
ax_anim 2, 0, 233, 0, 0, 0, 0,
ax_anim 2, 0, 226, 0, 0, 0, 0,
ax_anim 2, 0, 227, 0, 0, 0, 0,
ax_anim 2, 0, 228, 0, 0, 0, 0,
ax_anim 2, 0, 229, 0, 0, 0, 0,
ax_anim 2, 0, 230, 0, 0, 0, 0,
ax_anim 2, 0, 231, 0, 0, 0, 0,
ax_anim 2, 0, 232, 0, 0, 0, 0,
ax_anim 2, 2, 233, 0, 0, 0, 0,
ax_anim_terminator
sArcanineAnims_13_3:
ax_anim 2, 0, 232, 0, 0, 0, 0,
ax_anim 2, 0, 233, 0, 0, 0, 0,
ax_anim 2, 0, 226, 0, 0, 0, 0,
ax_anim 2, 0, 227, 0, 0, 0, 0,
ax_anim 2, 0, 228, 0, 0, 0, 0,
ax_anim 2, 0, 229, 0, 0, 0, 0,
ax_anim 2, 0, 230, 0, 0, 0, 0,
ax_anim 2, 0, 231, 0, 0, 0, 0,
ax_anim 2, 2, 232, 0, 0, 0, 0,
ax_anim_terminator
sArcanineAnims_13_4:
ax_anim 2, 0, 231, 0, 0, 0, 0,
ax_anim 2, 0, 232, 0, 0, 0, 0,
ax_anim 2, 0, 233, 0, 0, 0, 0,
ax_anim 2, 0, 226, 0, 0, 0, 0,
ax_anim 2, 0, 227, 0, 0, 0, 0,
ax_anim 2, 0, 228, 0, 0, 0, 0,
ax_anim 2, 0, 229, 0, 0, 0, 0,
ax_anim 2, 0, 230, 0, 0, 0, 0,
ax_anim 2, 2, 231, 0, 0, 0, 0,
ax_anim_terminator
sArcanineAnims_13_5:
ax_anim 2, 0, 230, 0, 0, 0, 0,
ax_anim 2, 0, 231, 0, 0, 0, 0,
ax_anim 2, 0, 232, 0, 0, 0, 0,
ax_anim 2, 0, 233, 0, 0, 0, 0,
ax_anim 2, 0, 226, 0, 0, 0, 0,
ax_anim 2, 0, 227, 0, 0, 0, 0,
ax_anim 2, 0, 228, 0, 0, 0, 0,
ax_anim 2, 0, 229, 0, 0, 0, 0,
ax_anim 2, 2, 230, 0, 0, 0, 0,
ax_anim_terminator
sArcanineAnims_13_6:
ax_anim 2, 0, 229, 0, 0, 0, 0,
ax_anim 2, 0, 230, 0, 0, 0, 0,
ax_anim 2, 0, 231, 0, 0, 0, 0,
ax_anim 2, 0, 232, 0, 0, 0, 0,
ax_anim 2, 0, 233, 0, 0, 0, 0,
ax_anim 2, 0, 226, 0, 0, 0, 0,
ax_anim 2, 0, 227, 0, 0, 0, 0,
ax_anim 2, 0, 228, 0, 0, 0, 0,
ax_anim 2, 2, 229, 0, 0, 0, 0,
ax_anim_terminator
sArcanineAnims_13_7:
ax_anim 2, 0, 228, 0, 0, 0, 0,
ax_anim 2, 0, 229, 0, 0, 0, 0,
ax_anim 2, 0, 230, 0, 0, 0, 0,
ax_anim 2, 0, 231, 0, 0, 0, 0,
ax_anim 2, 0, 232, 0, 0, 0, 0,
ax_anim 2, 0, 233, 0, 0, 0, 0,
ax_anim 2, 0, 226, 0, 0, 0, 0,
ax_anim 2, 0, 227, 0, 0, 0, 0,
ax_anim 2, 2, 228, 0, 0, 0, 0,
ax_anim_terminator
sArcanineAnims_13_8:
ax_anim 2, 0, 227, 0, 0, 0, 0,
ax_anim 2, 0, 228, 0, 0, 0, 0,
ax_anim 2, 0, 229, 0, 0, 0, 0,
ax_anim 2, 0, 230, 0, 0, 0, 0,
ax_anim 2, 0, 231, 0, 0, 0, 0,
ax_anim 2, 0, 232, 0, 0, 0, 0,
ax_anim 2, 0, 233, 0, 0, 0, 0,
ax_anim 2, 0, 226, 0, 0, 0, 0,
ax_anim 2, 2, 227, 0, 0, 0, 0,
ax_anim_terminator
sArcanineGfx1:
.incbin "baserom.gba", 0x792594, 0x200
sArcanineSprites1:
ax_sprite sArcanineGfx1, 0x200
ax_sprite_terminator
sArcanineGfx2:
.incbin "baserom.gba", 0x7927A4, 0x200
sArcanineSprites2:
ax_sprite sArcanineGfx2, 0x200
ax_sprite_terminator
sArcanineGfx3:
.incbin "baserom.gba", 0x7929B4, 0x200
sArcanineSprites3:
ax_sprite sArcanineGfx3, 0x200
ax_sprite_terminator
sArcanineGfx4:
.incbin "baserom.gba", 0x792BC4, 0x200
sArcanineSprites4:
ax_sprite sArcanineGfx4, 0x200
ax_sprite_terminator
sArcanineGfx5:
.incbin "baserom.gba", 0x792DD4, 0x200
sArcanineSprites5:
ax_sprite sArcanineGfx5, 0x200
ax_sprite_terminator
sArcanineGfx6:
.incbin "baserom.gba", 0x792FE4, 0x200
sArcanineSprites6:
ax_sprite sArcanineGfx6, 0x200
ax_sprite_terminator
sArcanineGfx7:
.incbin "baserom.gba", 0x7931F4, 0x200
sArcanineSprites7:
ax_sprite sArcanineGfx7, 0x200
ax_sprite_terminator
sArcanineGfx8:
.incbin "baserom.gba", 0x793404, 0x200
sArcanineSprites8:
ax_sprite sArcanineGfx8, 0x200
ax_sprite_terminator
sArcanineGfx9:
.incbin "baserom.gba", 0x793614, 0x200
sArcanineSprites9:
ax_sprite sArcanineGfx9, 0x200
ax_sprite_terminator
sArcanineGfx10:
.incbin "baserom.gba", 0x793824, 0x200
sArcanineSprites10:
ax_sprite sArcanineGfx10, 0x200
ax_sprite_terminator
sArcanineGfx11:
.incbin "baserom.gba", 0x793A34, 0x200
sArcanineSprites11:
ax_sprite sArcanineGfx11, 0x200
ax_sprite_terminator
sArcanineGfx12:
.incbin "baserom.gba", 0x793C44, 0x200
sArcanineSprites12:
ax_sprite sArcanineGfx12, 0x200
ax_sprite_terminator
sArcanineGfx13:
.incbin "baserom.gba", 0x793E54, 0x200
sArcanineSprites13:
ax_sprite sArcanineGfx13, 0x200
ax_sprite_terminator
sArcanineGfx14:
.incbin "baserom.gba", 0x794064, 0x200
sArcanineSprites14:
ax_sprite sArcanineGfx14, 0x200
ax_sprite_terminator
sArcanineGfx15:
.incbin "baserom.gba", 0x794274, 0x200
sArcanineSprites15:
ax_sprite sArcanineGfx15, 0x200
ax_sprite_terminator
sArcanineGfx16:
.incbin "baserom.gba", 0x794484, 0x60
sArcanineGfx16_1:
.incbin "baserom.gba", 0x7944E4, 0x60
sArcanineGfx16_2:
.incbin "baserom.gba", 0x794544, 0x60
sArcanineGfx16_3:
.incbin "baserom.gba", 0x7945A4, 0x60
sArcanineSprites16:
ax_sprite sArcanineGfx16, 0x60
ax_sprite 0, 0x20
ax_sprite sArcanineGfx16_1, 0x60
ax_sprite 0, 0x20
ax_sprite sArcanineGfx16_2, 0x60
ax_sprite 0, 0x20
ax_sprite sArcanineGfx16_3, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sArcanineGfx17:
.incbin "baserom.gba", 0x79464C, 0x60
sArcanineGfx17_1:
.incbin "baserom.gba", 0x7946AC, 0x60
sArcanineGfx17_2:
.incbin "baserom.gba", 0x79470C, 0x60
sArcanineGfx17_3:
.incbin "baserom.gba", 0x79476C, 0x60
sArcanineSprites17:
ax_sprite sArcanineGfx17, 0x60
ax_sprite 0, 0x20
ax_sprite sArcanineGfx17_1, 0x60
ax_sprite 0, 0x20
ax_sprite sArcanineGfx17_2, 0x60
ax_sprite 0, 0x20
ax_sprite sArcanineGfx17_3, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sArcanineGfx18:
.incbin "baserom.gba", 0x794814, 0x200
sArcanineSprites18:
ax_sprite sArcanineGfx18, 0x200
ax_sprite_terminator
sArcanineGfx19:
.incbin "baserom.gba", 0x794A24, 0x1C0
sArcanineSprites19:
ax_sprite 0, 0x20
ax_sprite sArcanineGfx19, 0x1c0
ax_sprite 0, 0x20
ax_sprite_terminator
sArcanineGfx20:
.incbin "baserom.gba", 0x794C04, 0x100
sArcanineSprites20:
ax_sprite sArcanineGfx20, 0x100
ax_sprite_terminator
sArcanineGfx21:
.incbin "baserom.gba", 0x794D14, 0x80
sArcanineSprites21:
ax_sprite sArcanineGfx21, 0x80
ax_sprite_terminator
sArcanineGfx22:
.incbin "baserom.gba", 0x794DA4, 0x20
sArcanineSprites22:
ax_sprite sArcanineGfx22, 0x20
ax_sprite_terminator
sArcanineGfx23:
.incbin "baserom.gba", 0x794DD4, 0x20
sArcanineSprites23:
ax_sprite sArcanineGfx23, 0x20
ax_sprite_terminator
sArcanineGfx24:
.incbin "baserom.gba", 0x794E04, 0x20
sArcanineSprites24:
ax_sprite sArcanineGfx24, 0x20
ax_sprite_terminator
sArcanineGfx25:
.incbin "baserom.gba", 0x794E34, 0x180
sArcanineGfx25_1:
.incbin "baserom.gba", 0x794FB4, 0x60
sArcanineSprites25:
ax_sprite sArcanineGfx25, 0x180
ax_sprite 0, 0x20
ax_sprite sArcanineGfx25_1, 0x60
ax_sprite_terminator
sArcanineGfx26:
.incbin "baserom.gba", 0x795034, 0x60
sArcanineGfx26_1:
.incbin "baserom.gba", 0x795094, 0x100
sArcanineGfx26_2:
.incbin "baserom.gba", 0x795194, 0x60
sArcanineSprites26:
ax_sprite sArcanineGfx26, 0x60
ax_sprite 0, 0x20
ax_sprite sArcanineGfx26_1, 0x100
ax_sprite 0, 0x20
ax_sprite sArcanineGfx26_2, 0x60
ax_sprite_terminator
sArcanineGfx27:
.incbin "baserom.gba", 0x795224, 0x1E0
sArcanineSprites27:
ax_sprite sArcanineGfx27, 0x1e0
ax_sprite 0, 0x20
ax_sprite_terminator
sArcanineGfx28:
.incbin "baserom.gba", 0x79541C, 0x60
sArcanineGfx28_1:
.incbin "baserom.gba", 0x79547C, 0x60
sArcanineGfx28_2:
.incbin "baserom.gba", 0x7954DC, 0x60
sArcanineGfx28_3:
.incbin "baserom.gba", 0x79553C, 0x60
sArcanineSprites28:
ax_sprite sArcanineGfx28, 0x60
ax_sprite 0, 0x20
ax_sprite sArcanineGfx28_1, 0x60
ax_sprite 0, 0x20
ax_sprite sArcanineGfx28_2, 0x60
ax_sprite 0, 0x20
ax_sprite sArcanineGfx28_3, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sArcanineGfx29:
.incbin "baserom.gba", 0x7955E4, 0x60
sArcanineGfx29_1:
.incbin "baserom.gba", 0x795644, 0x60
sArcanineGfx29_2:
.incbin "baserom.gba", 0x7956A4, 0x60
sArcanineGfx29_3:
.incbin "baserom.gba", 0x795704, 0x60
sArcanineSprites29:
ax_sprite sArcanineGfx29, 0x60
ax_sprite 0, 0x20
ax_sprite sArcanineGfx29_1, 0x60
ax_sprite 0, 0x20
ax_sprite sArcanineGfx29_2, 0x60
ax_sprite 0, 0x20
ax_sprite sArcanineGfx29_3, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sArcanineGfx30:
.incbin "baserom.gba", 0x7957AC, 0x60
sArcanineGfx30_1:
.incbin "baserom.gba", 0x79580C, 0x60
sArcanineGfx30_2:
.incbin "baserom.gba", 0x79586C, 0x60
sArcanineGfx30_3:
.incbin "baserom.gba", 0x7958CC, 0x60
sArcanineSprites30:
ax_sprite sArcanineGfx30, 0x60
ax_sprite 0, 0x20
ax_sprite sArcanineGfx30_1, 0x60
ax_sprite 0, 0x20
ax_sprite sArcanineGfx30_2, 0x60
ax_sprite 0, 0x20
ax_sprite sArcanineGfx30_3, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sArcanineGfx31:
.incbin "baserom.gba", 0x795974, 0x60
sArcanineGfx31_1:
.incbin "baserom.gba", 0x7959D4, 0x60
sArcanineGfx31_2:
.incbin "baserom.gba", 0x795A34, 0x60
sArcanineGfx31_3:
.incbin "baserom.gba", 0x795A94, 0x60
sArcanineSprites31:
ax_sprite sArcanineGfx31, 0x60
ax_sprite 0, 0x20
ax_sprite sArcanineGfx31_1, 0x60
ax_sprite 0, 0x20
ax_sprite sArcanineGfx31_2, 0x60
ax_sprite 0, 0x20
ax_sprite sArcanineGfx31_3, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sArcanineGfx32:
.incbin "baserom.gba", 0x795B3C, 0x60
sArcanineGfx32_1:
.incbin "baserom.gba", 0x795B9C, 0x180
sArcanineSprites32:
ax_sprite sArcanineGfx32, 0x60
ax_sprite 0, 0x20
ax_sprite sArcanineGfx32_1, 0x180
ax_sprite_terminator
sArcanineGfx33:
.incbin "baserom.gba", 0x795D3C, 0x200
sArcanineSprites33:
ax_sprite sArcanineGfx33, 0x200
ax_sprite_terminator
sArcanineGfx34:
.incbin "baserom.gba", 0x795F4C, 0x60
sArcanineGfx34_1:
.incbin "baserom.gba", 0x795FAC, 0x180
sArcanineSprites34:
ax_sprite sArcanineGfx34, 0x60
ax_sprite 0, 0x20
ax_sprite sArcanineGfx34_1, 0x180
ax_sprite_terminator
sArcanineGfx35:
.incbin "baserom.gba", 0x79614C, 0x200
sArcanineSprites35:
ax_sprite sArcanineGfx35, 0x200
ax_sprite_terminator
sArcanineGfx36:
.incbin "baserom.gba", 0x79635C, 0x60
sArcanineGfx36_1:
.incbin "baserom.gba", 0x7963BC, 0x100
sArcanineGfx36_2:
.incbin "baserom.gba", 0x7964BC, 0x60
sArcanineSprites36:
ax_sprite sArcanineGfx36, 0x60
ax_sprite 0, 0x20
ax_sprite sArcanineGfx36_1, 0x100
ax_sprite 0, 0x20
ax_sprite sArcanineGfx36_2, 0x60
ax_sprite_terminator
sArcanineGfx37:
.incbin "baserom.gba", 0x79654C, 0x200
sArcanineSprites37:
ax_sprite sArcanineGfx37, 0x200
ax_sprite_terminator
sArcanineGfx38:
.incbin "baserom.gba", 0x79675C, 0x60
sArcanineGfx38_1:
.incbin "baserom.gba", 0x7967BC, 0x60
sArcanineGfx38_2:
.incbin "baserom.gba", 0x79681C, 0x60
sArcanineGfx38_3:
.incbin "baserom.gba", 0x79687C, 0x60
sArcanineSprites38:
ax_sprite sArcanineGfx38, 0x60
ax_sprite 0, 0x20
ax_sprite sArcanineGfx38_1, 0x60
ax_sprite 0, 0x20
ax_sprite sArcanineGfx38_2, 0x60
ax_sprite 0, 0x20
ax_sprite sArcanineGfx38_3, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sArcanineGfx39:
.incbin "baserom.gba", 0x796924, 0x60
sArcanineGfx39_1:
.incbin "baserom.gba", 0x796984, 0x60
sArcanineGfx39_2:
.incbin "baserom.gba", 0x7969E4, 0x60
sArcanineGfx39_3:
.incbin "baserom.gba", 0x796A44, 0x60
sArcanineSprites39:
ax_sprite sArcanineGfx39, 0x60
ax_sprite 0, 0x20
ax_sprite sArcanineGfx39_1, 0x60
ax_sprite 0, 0x20
ax_sprite sArcanineGfx39_2, 0x60
ax_sprite 0, 0x20
ax_sprite sArcanineGfx39_3, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sArcanineGfx40:
.incbin "baserom.gba", 0x796AEC, 0x200
sArcanineSprites40:
ax_sprite sArcanineGfx40, 0x200
ax_sprite_terminator
sArcanineGfx41:
.incbin "baserom.gba", 0x796CFC, 0x200
sArcanineSprites41:
ax_sprite sArcanineGfx41, 0x200
ax_sprite_terminator
sArcanineGfx42:
.incbin "baserom.gba", 0x796F0C, 0x200
sArcanineSprites42:
ax_sprite sArcanineGfx42, 0x200
ax_sprite_terminator
sArcanineGfx43:
.incbin "baserom.gba", 0x79711C, 0x200
sArcanineSprites43:
ax_sprite sArcanineGfx43, 0x200
ax_sprite_terminator
sArcanineGfx44:
.incbin "baserom.gba", 0x79732C, 0x200
sArcanineSprites44:
ax_sprite sArcanineGfx44, 0x200
ax_sprite_terminator
sArcanineGfx45:
.incbin "baserom.gba", 0x79753C, 0x200
sArcanineSprites45:
ax_sprite sArcanineGfx45, 0x200
ax_sprite_terminator
sArcanineGfx46:
.incbin "baserom.gba", 0x79774C, 0x200
sArcanineSprites46:
ax_sprite sArcanineGfx46, 0x200
ax_sprite_terminator
sAxPosesArcanine:
.4byte sArcaninePose1
.4byte sArcaninePose2
.4byte sArcaninePose3
.4byte sArcaninePose4
.4byte sArcaninePose5
.4byte sArcaninePose6
.4byte sArcaninePose7
.4byte sArcaninePose8
.4byte sArcaninePose9
.4byte sArcaninePose10
.4byte sArcaninePose11
.4byte sArcaninePose12
.4byte sArcaninePose13
.4byte sArcaninePose14
.4byte sArcaninePose15
.4byte sArcaninePose16
.4byte sArcaninePose17
.4byte sArcaninePose18
.4byte sArcaninePose19
.4byte sArcaninePose20
.4byte sArcaninePose21
.4byte sArcaninePose22
.4byte sArcaninePose23
.4byte sArcaninePose24
.4byte sArcaninePose25
.4byte sArcaninePose26
.4byte sArcaninePose27
.4byte sArcaninePose28
.4byte sArcaninePose29
.4byte sArcaninePose30
.4byte sArcaninePose31
.4byte sArcaninePose32
.4byte sArcaninePose33
.4byte sArcaninePose34
.4byte sArcaninePose35
.4byte sArcaninePose36
.4byte sArcaninePose37
.4byte sArcaninePose38
.4byte sArcaninePose39
.4byte sArcaninePose40
.4byte sArcaninePose41
.4byte sArcaninePose42
.4byte sArcaninePose43
.4byte sArcaninePose44
.4byte sArcaninePose45
.4byte sArcaninePose46
.4byte sArcaninePose47
.4byte sArcaninePose48
.4byte sArcaninePose49
.4byte sArcaninePose50
.4byte sArcaninePose51
.4byte sArcaninePose52
.4byte sArcaninePose53
.4byte sArcaninePose54
.4byte sArcaninePose55
.4byte sArcaninePose56
.4byte sArcaninePose57
.4byte sArcaninePose58
.4byte sArcaninePose59
.4byte sArcaninePose60
.4byte sArcaninePose61
.4byte sArcaninePose62
.4byte sArcaninePose63
.4byte sArcaninePose64
.4byte sArcaninePose65
.4byte sArcaninePose66
.4byte sArcaninePose67
.4byte sArcaninePose68
.4byte sArcaninePose69
.4byte sArcaninePose70
.4byte sArcaninePose71
.4byte sArcaninePose72
.4byte sArcaninePose73
.4byte sArcaninePose74
.4byte sArcaninePose75
.4byte sArcaninePose76
.4byte sArcaninePose77
.4byte sArcaninePose78
.4byte sArcaninePose79
.4byte sArcaninePose80
.4byte sArcaninePose81
.4byte sArcaninePose82
.4byte sArcaninePose83
.4byte sArcaninePose84
.4byte sArcaninePose85
.4byte sArcaninePose86
.4byte sArcaninePose87
.4byte sArcaninePose88
.4byte sArcaninePose89
.4byte sArcaninePose90
.4byte sArcaninePose91
.4byte sArcaninePose92
.4byte sArcaninePose93
.4byte sArcaninePose94
.4byte sArcaninePose95
.4byte sArcaninePose96
.4byte sArcaninePose97
.4byte sArcaninePose98
.4byte sArcaninePose99
.4byte sArcaninePose100
.4byte sArcaninePose101
.4byte sArcaninePose102
.4byte sArcaninePose103
.4byte sArcaninePose104
.4byte sArcaninePose105
.4byte sArcaninePose106
.4byte sArcaninePose107
.4byte sArcaninePose108
.4byte sArcaninePose109
.4byte sArcaninePose110
.4byte sArcaninePose111
.4byte sArcaninePose112
.4byte sArcaninePose113
.4byte sArcaninePose114
.4byte sArcaninePose115
.4byte sArcaninePose116
.4byte sArcaninePose117
.4byte sArcaninePose118
.4byte sArcaninePose119
.4byte sArcaninePose120
.4byte sArcaninePose121
.4byte sArcaninePose122
.4byte sArcaninePose123
.4byte sArcaninePose124
.4byte sArcaninePose125
.4byte sArcaninePose126
.4byte sArcaninePose127
.4byte sArcaninePose128
.4byte sArcaninePose129
.4byte sArcaninePose130
.4byte sArcaninePose131
.4byte sArcaninePose132
.4byte sArcaninePose133
.4byte sArcaninePose134
.4byte sArcaninePose135
.4byte sArcaninePose136
.4byte sArcaninePose137
.4byte sArcaninePose138
.4byte sArcaninePose139
.4byte sArcaninePose140
.4byte sArcaninePose141
.4byte sArcaninePose142
.4byte sArcaninePose143
.4byte sArcaninePose144
.4byte sArcaninePose145
.4byte sArcaninePose146
.4byte sArcaninePose147
.4byte sArcaninePose148
.4byte sArcaninePose149
.4byte sArcaninePose150
.4byte sArcaninePose151
.4byte sArcaninePose152
.4byte sArcaninePose153
.4byte sArcaninePose154
.4byte sArcaninePose155
.4byte sArcaninePose156
.4byte sArcaninePose157
.4byte sArcaninePose158
.4byte sArcaninePose159
.4byte sArcaninePose160
.4byte sArcaninePose161
.4byte sArcaninePose162
.4byte sArcaninePose163
.4byte sArcaninePose164
.4byte sArcaninePose165
.4byte sArcaninePose166
.4byte sArcaninePose167
.4byte sArcaninePose168
.4byte sArcaninePose169
.4byte sArcaninePose170
.4byte sArcaninePose171
.4byte sArcaninePose172
.4byte sArcaninePose173
.4byte sArcaninePose174
.4byte sArcaninePose175
.4byte sArcaninePose176
.4byte sArcaninePose177
.4byte sArcaninePose178
.4byte sArcaninePose179
.4byte sArcaninePose180
.4byte sArcaninePose181
.4byte sArcaninePose182
.4byte sArcaninePose183
.4byte sArcaninePose184
.4byte sArcaninePose185
.4byte sArcaninePose186
.4byte sArcaninePose187
.4byte sArcaninePose188
.4byte sArcaninePose189
.4byte sArcaninePose190
.4byte sArcaninePose191
.4byte sArcaninePose192
.4byte sArcaninePose193
.4byte sArcaninePose194
.4byte sArcaninePose195
.4byte sArcaninePose196
.4byte sArcaninePose197
.4byte sArcaninePose198
.4byte sArcaninePose199
.4byte sArcaninePose200
.4byte sArcaninePose201
.4byte sArcaninePose202
.4byte sArcaninePose203
.4byte sArcaninePose204
.4byte sArcaninePose205
.4byte sArcaninePose206
.4byte sArcaninePose207
.4byte sArcaninePose208
.4byte sArcaninePose209
.4byte sArcaninePose210
.4byte sArcaninePose211
.4byte sArcaninePose212
.4byte sArcaninePose213
.4byte sArcaninePose214
.4byte sArcaninePose215
.4byte sArcaninePose216
.4byte sArcaninePose217
.4byte sArcaninePose218
.4byte sArcaninePose219
.4byte sArcaninePose220
.4byte sArcaninePose221
.4byte sArcaninePose222
.4byte sArcaninePose223
.4byte sArcaninePose224
.4byte sArcaninePose225
.4byte sArcaninePose226
.4byte sArcaninePose227
.4byte sArcaninePose228
.4byte sArcaninePose229
.4byte sArcaninePose230
.4byte sArcaninePose231
.4byte sArcaninePose232
.4byte sArcaninePose233
.4byte sArcaninePose234
sAxPositionsArcanine:
.2byte    0,   -6, 	  -5,    2, 	   4,    2, 	   0,   -9
.2byte    0,   -5, 	  -4,    5, 	   3,    1, 	   0,   -8
.2byte    0,   -5, 	  -4,    1, 	   3,    5, 	   0,   -8
.2byte    8,   -7, 	   7,    0, 	   1,    2, 	  -1,   -9
.2byte    8,   -6, 	  10,    2, 	  -2,    2, 	  -1,   -8
.2byte    8,   -6, 	  -1,   -2, 	   4,    5, 	  -2,   -8
.2byte   10,   -9, 	   9,   -1, 	   8,    0, 	  -1,   -9
.2byte   10,   -8, 	  11,   -1, 	   4,    1, 	  -2,   -8
.2byte   10,   -8, 	   3,   -1, 	   9,    1, 	  -1,   -7
.2byte   10,  -12, 	   2,   -4, 	   7,   -2, 	   0,   -8
.2byte   10,  -11, 	   5,   -6, 	   5,    0, 	   0,   -8
.2byte   10,  -11, 	  -1,   -3, 	   9,   -2, 	  -1,   -8
.2byte    0,  -15, 	   5,   -7, 	  -6,   -7, 	   0,  -11
.2byte   -1,  -14, 	   6,   -7, 	  -6,   -4, 	   0,  -10
.2byte    1,  -14, 	   5,   -4, 	  -7,   -7, 	   0,  -10
.2byte  -11,  -12, 	  -3,   -4, 	  -8,   -2, 	  -1,   -8
.2byte  -11,  -11, 	  -6,   -6, 	  -6,    0, 	  -1,   -8
.2byte  -11,  -11, 	   0,   -3, 	 -10,   -2, 	   0,   -8
.2byte  -11,   -9, 	 -10,   -1, 	  -9,    0, 	   0,   -9
.2byte  -11,   -8, 	 -12,   -1, 	  -5,    1, 	   1,   -8
.2byte  -11,   -8, 	  -4,   -1, 	 -10,    1, 	   0,   -7
.2byte   -9,   -7, 	  -8,    0, 	  -2,    2, 	   0,   -9
.2byte   -9,   -6, 	 -11,    2, 	   1,    2, 	   0,   -8
.2byte   -9,   -6, 	   0,   -2, 	  -5,    5, 	   1,   -8
.2byte    0,   -6, 	  -5,    2, 	   4,    2, 	   0,   -9
.2byte    0,   -5, 	  -4,    5, 	   3,    1, 	   0,   -8
.2byte    0,   -5, 	  -4,    1, 	   3,    5, 	   0,   -8
.2byte    0,   -9, 	  -9,   -6, 	   8,   -6, 	   0,  -10
.2byte    0,   -5, 	  -3,    1, 	   2,    1, 	   0,  -11
.2byte    8,   -7, 	   7,    0, 	   1,    2, 	  -1,   -9
.2byte    8,   -6, 	  10,    2, 	  -2,    2, 	  -1,   -8
.2byte    8,   -6, 	  -1,   -2, 	   4,    5, 	  -2,   -8
.2byte    9,   -9, 	  13,   -7, 	   5,   -4, 	  -1,  -10
.2byte    8,   -4, 	   3,    1, 	  -3,    3, 	  -1,   -9
.2byte   10,   -9, 	   9,   -1, 	   8,    0, 	  -1,   -9
.2byte   10,   -8, 	  11,   -1, 	   4,    1, 	  -2,   -8
.2byte   10,   -8, 	   3,   -1, 	   9,    1, 	  -1,   -7
.2byte   12,  -14, 	  13,  -12, 	  12,   -9, 	  -1,  -13
.2byte   13,   -8, 	   1,   -2, 	  -1,    0, 	   0,  -10
.2byte   10,  -12, 	   2,   -4, 	   7,   -2, 	   0,   -8
.2byte   10,  -11, 	   5,   -6, 	   5,    0, 	   0,   -8
.2byte   10,  -11, 	  -1,   -3, 	   9,   -2, 	  -1,   -8
.2byte   11,  -15, 	   2,  -14, 	  11,  -11, 	   0,  -10
.2byte   13,   -8, 	  -4,   -2, 	   1,    1, 	   1,  -10
.2byte    0,  -15, 	   5,   -7, 	  -6,   -7, 	   0,  -11
.2byte   -1,  -14, 	   6,   -7, 	  -6,   -4, 	   0,  -10
.2byte    1,  -14, 	   5,   -4, 	  -7,   -7, 	   0,  -10
.2byte    0,  -20, 	   6,  -16, 	  -7,  -16, 	   0,  -13
.2byte    0,  -15, 	   2,   -1, 	  -3,   -1, 	   0,  -13
.2byte  -11,  -12, 	  -3,   -4, 	  -8,   -2, 	  -1,   -8
.2byte  -11,  -11, 	  -6,   -6, 	  -6,    0, 	  -1,   -8
.2byte  -11,  -11, 	   0,   -3, 	 -10,   -2, 	   0,   -8
.2byte  -12,  -15, 	  -3,  -14, 	 -12,  -11, 	  -1,  -10
.2byte  -14,   -8, 	   3,   -2, 	  -2,    1, 	  -2,  -10
.2byte  -11,   -9, 	 -10,   -1, 	  -9,    0, 	   0,   -9
.2byte  -11,   -8, 	 -12,   -1, 	  -5,    1, 	   1,   -8
.2byte  -11,   -8, 	  -4,   -1, 	 -10,    1, 	   0,   -7
.2byte  -13,  -14, 	 -14,  -12, 	 -13,   -9, 	   0,  -13
.2byte  -14,   -8, 	  -2,   -2, 	   0,    0, 	  -1,  -10
.2byte   -9,   -7, 	  -8,    0, 	  -2,    2, 	   0,   -9
.2byte   -9,   -6, 	 -11,    2, 	   1,    2, 	   0,   -8
.2byte   -9,   -6, 	   0,   -2, 	  -5,    5, 	   1,   -8
.2byte  -10,   -9, 	 -14,   -7, 	  -6,   -4, 	   0,  -10
.2byte   -9,   -4, 	  -4,    1, 	   2,    3, 	   0,   -9
.2byte    0,   -6, 	  -5,    2, 	   4,    2, 	   0,   -9
.2byte    0,   -5, 	  -4,    5, 	   3,    1, 	   0,   -8
.2byte    0,   -5, 	  -4,    1, 	   3,    5, 	   0,   -8
.2byte    0,   -9, 	  -9,   -6, 	   8,   -6, 	   0,  -10
.2byte    0,   -5, 	  -3,    1, 	   2,    1, 	   0,  -11
.2byte    8,   -7, 	   7,    0, 	   1,    2, 	  -1,   -9
.2byte    8,   -6, 	  10,    2, 	  -2,    2, 	  -1,   -8
.2byte    8,   -6, 	  -1,   -2, 	   4,    5, 	  -2,   -8
.2byte    9,   -9, 	  13,   -7, 	   5,   -4, 	  -1,  -10
.2byte    8,   -4, 	   3,    1, 	  -3,    3, 	  -1,   -9
.2byte   10,   -9, 	   9,   -1, 	   8,    0, 	  -1,   -9
.2byte   10,   -8, 	  11,   -1, 	   4,    1, 	  -2,   -8
.2byte   10,   -8, 	   3,   -1, 	   9,    1, 	  -1,   -7
.2byte   12,  -14, 	  13,  -12, 	  12,   -9, 	  -1,  -13
.2byte   13,   -8, 	   1,   -2, 	  -1,    0, 	   0,  -10
.2byte   10,  -12, 	   2,   -4, 	   7,   -2, 	   0,   -8
.2byte   10,  -11, 	   5,   -6, 	   5,    0, 	   0,   -8
.2byte   10,  -11, 	  -1,   -3, 	   9,   -2, 	  -1,   -8
.2byte   11,  -15, 	   2,  -14, 	  11,  -11, 	   0,  -10
.2byte   13,   -8, 	  -4,   -2, 	   1,    1, 	   1,  -10
.2byte    0,  -15, 	   5,   -7, 	  -6,   -7, 	   0,  -11
.2byte   -1,  -14, 	   6,   -7, 	  -6,   -4, 	   0,  -10
.2byte    1,  -14, 	   5,   -4, 	  -7,   -7, 	   0,  -10
.2byte    0,  -20, 	   6,  -16, 	  -7,  -16, 	   0,  -13
.2byte    0,  -15, 	   2,   -1, 	  -3,   -1, 	   0,  -13
.2byte  -11,  -12, 	  -3,   -4, 	  -8,   -2, 	  -1,   -8
.2byte  -11,  -11, 	  -6,   -6, 	  -6,    0, 	  -1,   -8
.2byte  -11,  -11, 	   0,   -3, 	 -10,   -2, 	   0,   -8
.2byte  -12,  -15, 	  -3,  -14, 	 -12,  -11, 	  -1,  -10
.2byte  -14,   -8, 	   3,   -2, 	  -2,    1, 	  -2,  -10
.2byte  -11,   -9, 	 -10,   -1, 	  -9,    0, 	   0,   -9
.2byte  -11,   -8, 	 -12,   -1, 	  -5,    1, 	   1,   -8
.2byte  -11,   -8, 	  -4,   -1, 	 -10,    1, 	   0,   -7
.2byte  -13,  -14, 	 -14,  -12, 	 -13,   -9, 	   0,  -13
.2byte  -14,   -8, 	  -2,   -2, 	   0,    0, 	  -1,  -10
.2byte   -9,   -7, 	  -8,    0, 	  -2,    2, 	   0,   -9
.2byte   -9,   -6, 	 -11,    2, 	   1,    2, 	   0,   -8
.2byte   -9,   -6, 	   0,   -2, 	  -5,    5, 	   1,   -8
.2byte  -10,   -9, 	 -14,   -7, 	  -6,   -4, 	   0,  -10
.2byte   -9,   -4, 	  -4,    1, 	   2,    3, 	   0,   -9
.2byte    0,   -6, 	  -5,    2, 	   4,    2, 	   0,   -9
.2byte    0,   -5, 	  -4,    5, 	   3,    1, 	   0,   -8
.2byte    0,  -10, 	  -5,    1, 	   4,    1, 	   0,  -11
.2byte    0,   -3, 	  -6,    2, 	   5,    2, 	   0,  -11
.2byte    8,   -7, 	   7,    0, 	   1,    2, 	  -1,   -9
.2byte    8,   -6, 	  10,    2, 	  -2,    2, 	  -1,   -8
.2byte    6,  -11, 	   7,   -2, 	   1,    2, 	  -2,  -10
.2byte   10,   -6, 	   9,   -1, 	   0,    2, 	   1,   -8
.2byte   10,   -9, 	   9,   -1, 	   8,    0, 	  -1,   -9
.2byte   10,   -8, 	  11,   -1, 	   4,    1, 	  -2,   -8
.2byte   10,  -13, 	   4,   -1, 	   4,    1, 	  -1,   -8
.2byte   13,   -8, 	   8,   -1, 	   7,    1, 	   0,   -8
.2byte   10,  -12, 	   2,   -4, 	   7,   -2, 	   0,   -8
.2byte   10,  -11, 	   5,   -6, 	   5,    0, 	   0,   -8
.2byte    7,  -15, 	   0,   -3, 	   5,   -1, 	  -2,  -11
.2byte   14,  -11, 	   1,   -5, 	   7,   -2, 	   1,  -11
.2byte    0,  -15, 	   5,   -7, 	  -6,   -7, 	   0,  -11
.2byte   -1,  -14, 	   6,   -7, 	  -6,   -4, 	   0,  -10
.2byte    0,  -20, 	   6,   -5, 	  -7,   -5, 	   0,  -11
.2byte    0,  -15, 	   4,   -7, 	  -5,   -7, 	   0,  -11
.2byte  -11,  -12, 	  -3,   -4, 	  -8,   -2, 	  -1,   -8
.2byte  -11,  -11, 	  -6,   -6, 	  -6,    0, 	  -1,   -8
.2byte   -9,  -15, 	  -2,   -3, 	  -7,   -1, 	   0,  -11
.2byte  -15,  -11, 	  -2,   -5, 	  -8,   -2, 	  -2,  -11
.2byte  -11,   -9, 	 -10,   -1, 	  -9,    0, 	   0,   -9
.2byte  -11,   -8, 	 -12,   -1, 	  -5,    1, 	   1,   -8
.2byte  -11,  -13, 	  -5,   -1, 	  -5,    1, 	   0,   -8
.2byte  -14,   -8, 	  -9,   -1, 	  -8,    1, 	  -1,   -8
.2byte   -9,   -7, 	  -8,    0, 	  -2,    2, 	   0,   -9
.2byte   -9,   -6, 	 -11,    2, 	   1,    2, 	   0,   -8
.2byte   -7,  -10, 	  -8,   -1, 	  -2,    3, 	   1,   -9
.2byte  -11,   -6, 	 -10,   -1, 	  -1,    2, 	  -2,   -8
.2byte    0,   -6, 	  -5,    2, 	   4,    2, 	   0,   -9
.2byte    0,   -9, 	  -9,   -6, 	   8,   -6, 	   0,  -10
.2byte    0,  -10, 	  -5,    1, 	   4,    1, 	   0,  -11
.2byte    8,   -7, 	   7,    0, 	   1,    2, 	  -1,   -9
.2byte    8,   -9, 	  12,   -7, 	   4,   -4, 	  -2,  -10
.2byte    6,  -11, 	   7,   -2, 	   1,    2, 	  -2,  -10
.2byte   10,   -9, 	   9,   -1, 	   8,    0, 	  -1,   -9
.2byte   13,  -14, 	  14,  -12, 	  13,   -9, 	   0,  -13
.2byte   12,  -13, 	   6,   -1, 	   6,    1, 	   1,   -8
.2byte   10,  -12, 	   2,   -4, 	   7,   -2, 	   0,   -8
.2byte    9,  -15, 	   0,  -14, 	   9,  -11, 	  -2,  -10
.2byte    7,  -14, 	   0,   -2, 	   5,    0, 	  -2,  -10
.2byte    0,  -15, 	   5,   -7, 	  -6,   -7, 	   0,  -11
.2byte    0,  -20, 	   6,  -16, 	  -7,  -16, 	   0,  -13
.2byte    0,  -16, 	   6,   -1, 	  -7,   -1, 	   0,   -7
.2byte  -11,  -12, 	  -3,   -4, 	  -8,   -2, 	  -1,   -8
.2byte  -10,  -15, 	  -1,  -14, 	 -10,  -11, 	   1,  -10
.2byte   -8,  -14, 	  -1,   -2, 	  -6,    0, 	   1,  -10
.2byte  -11,   -9, 	 -10,   -1, 	  -9,    0, 	   0,   -9
.2byte  -13,  -14, 	 -14,  -12, 	 -13,   -9, 	   0,  -13
.2byte  -13,  -13, 	  -7,   -1, 	  -7,    1, 	  -2,   -8
.2byte   -9,   -7, 	  -8,    0, 	  -2,    2, 	   0,   -9
.2byte   -9,   -9, 	 -13,   -7, 	  -5,   -4, 	   1,  -10
.2byte   -7,  -11, 	  -8,   -2, 	  -2,    2, 	   1,  -10
.2byte   -8,   -2, 	 -13,   -1, 	  -6,    3, 	   1,   -8
.2byte   -8,   -1, 	 -13,   -1, 	  -6,    3, 	   1,   -7
.2byte    0,   -5, 	  -9,    0, 	   8,    0, 	   0,  -11
.2byte    4,   -7, 	  11,   -3, 	  -6,    1, 	  -2,   -9
.2byte    8,   -9, 	  14,   -4, 	  10,    0, 	  -1,   -9
.2byte   10,  -11, 	   1,   -9, 	  11,   -2, 	   0,   -8
.2byte    0,  -12, 	   9,   -4, 	 -10,   -4, 	   0,   -9
.2byte  -11,  -11, 	  -2,   -9, 	 -12,   -2, 	  -1,   -8
.2byte   -9,   -9, 	 -15,   -4, 	 -11,    0, 	   0,   -9
.2byte   -5,   -7, 	 -12,   -3, 	   5,    1, 	   1,   -9
.2byte    0,  -10, 	  -5,    1, 	   4,    1, 	   0,  -11
.2byte   -7,  -10, 	  -8,   -1, 	  -2,    3, 	   1,   -9
.2byte  -11,  -13, 	  -5,   -1, 	  -5,    1, 	   0,   -8
.2byte   -9,  -15, 	  -2,   -3, 	  -7,   -1, 	   0,  -11
.2byte    0,  -21, 	   6,   -6, 	  -7,   -6, 	   0,  -12
.2byte    7,  -15, 	   0,   -3, 	   5,   -1, 	  -2,  -11
.2byte   10,  -13, 	   4,   -1, 	   4,    1, 	  -1,   -8
.2byte    6,  -11, 	   7,   -2, 	   1,    2, 	  -2,  -10
.2byte    0,   -3, 	  -6,    2, 	   5,    2, 	   0,  -11
.2byte  -11,   -5, 	 -10,    0, 	  -1,    3, 	  -2,   -7
.2byte  -14,   -8, 	  -9,   -1, 	  -8,    1, 	  -1,   -8
.2byte  -14,  -11, 	  -1,   -5, 	  -7,   -2, 	  -1,  -11
.2byte    0,  -15, 	   4,   -7, 	  -5,   -7, 	   0,  -11
.2byte   13,  -11, 	   0,   -5, 	   6,   -2, 	   0,  -11
.2byte   13,   -8, 	   8,   -1, 	   7,    1, 	   0,   -8
.2byte   10,   -5, 	   9,    0, 	   0,    3, 	   1,   -7
.2byte    0,   -3, 	  -6,    2, 	   5,    2, 	   0,  -11
.2byte   10,   -5, 	   9,    0, 	   0,    3, 	   1,   -7
.2byte   13,   -8, 	   8,   -1, 	   7,    1, 	   0,   -8
.2byte   13,  -11, 	   0,   -5, 	   6,   -2, 	   0,  -11
.2byte    0,  -15, 	   4,   -7, 	  -5,   -7, 	   0,  -11
.2byte  -14,  -11, 	  -1,   -5, 	  -7,   -2, 	  -1,  -11
.2byte  -14,   -8, 	  -9,   -1, 	  -8,    1, 	  -1,   -8
.2byte  -11,   -5, 	 -10,    0, 	  -1,    3, 	  -2,   -7
.2byte    0,   -6, 	  -5,    2, 	   4,    2, 	   0,   -9
.2byte    0,   -9, 	  -9,   -6, 	   8,   -6, 	   0,  -10
.2byte    0,   -3, 	  -6,    2, 	   5,    2, 	   0,  -11
.2byte    8,   -7, 	   7,    0, 	   1,    2, 	  -1,   -9
.2byte    8,   -9, 	  12,   -7, 	   4,   -4, 	  -2,  -10
.2byte   10,   -6, 	   9,   -1, 	   0,    2, 	   1,   -8
.2byte   10,   -9, 	   9,   -1, 	   8,    0, 	  -1,   -9
.2byte   12,  -14, 	  13,  -12, 	  12,   -9, 	  -1,  -13
.2byte   12,   -8, 	   7,   -1, 	   6,    1, 	  -1,   -8
.2byte   10,  -12, 	   2,   -4, 	   7,   -2, 	   0,   -8
.2byte   11,  -15, 	   2,  -14, 	  11,  -11, 	   0,  -10
.2byte   12,  -11, 	  -1,   -5, 	   5,   -2, 	  -1,  -11
.2byte    0,  -15, 	   5,   -7, 	  -6,   -7, 	   0,  -11
.2byte    0,  -20, 	   6,  -16, 	  -7,  -16, 	   0,  -13
.2byte    0,  -15, 	   4,   -7, 	  -5,   -7, 	   0,  -11
.2byte  -11,  -12, 	  -3,   -4, 	  -8,   -2, 	  -1,   -8
.2byte  -12,  -15, 	  -3,  -14, 	 -12,  -11, 	  -1,  -10
.2byte  -12,  -11, 	   1,   -5, 	  -5,   -2, 	   1,  -11
.2byte  -11,   -9, 	 -10,   -1, 	  -9,    0, 	   0,   -9
.2byte  -13,  -14, 	 -14,  -12, 	 -13,   -9, 	   0,  -13
.2byte  -13,   -8, 	  -8,   -1, 	  -7,    1, 	   0,   -8
.2byte   -9,   -7, 	  -8,    0, 	  -2,    2, 	   0,   -9
.2byte   -9,   -9, 	 -13,   -7, 	  -5,   -4, 	   1,  -10
.2byte  -11,   -6, 	 -10,   -1, 	  -1,    2, 	  -2,   -8
.2byte    0,  -10, 	  -5,    1, 	   4,    1, 	   0,  -11
.2byte   -7,  -10, 	  -8,   -1, 	  -2,    3, 	   1,   -9
.2byte  -11,  -13, 	  -5,   -1, 	  -5,    1, 	   0,   -8
.2byte   -9,  -15, 	  -2,   -3, 	  -7,   -1, 	   0,  -11
.2byte    0,  -21, 	   6,   -6, 	  -7,   -6, 	   0,  -12
.2byte    7,  -15, 	   0,   -3, 	   5,   -1, 	  -2,  -11
.2byte   10,  -13, 	   4,   -1, 	   4,    1, 	  -1,   -8
.2byte    6,  -11, 	   7,   -2, 	   1,    2, 	  -2,  -10
.2byte    0,   -6, 	  -5,    2, 	   4,    2, 	   0,   -9
.2byte   -9,   -7, 	  -8,    0, 	  -2,    2, 	   0,   -9
.2byte  -11,   -9, 	 -10,   -1, 	  -9,    0, 	   0,   -9
.2byte  -11,  -12, 	  -3,   -4, 	  -8,   -2, 	  -1,   -8
.2byte    0,  -15, 	   5,   -7, 	  -6,   -7, 	   0,  -11
.2byte   10,  -12, 	   2,   -4, 	   7,   -2, 	   0,   -8
.2byte   10,   -9, 	   9,   -1, 	   8,    0, 	  -1,   -9
.2byte    8,   -7, 	   7,    0, 	   1,    2, 	  -1,   -9
sArcanineAnimTable1:
.4byte sArcanineAnims_1_1
.4byte sArcanineAnims_1_2
.4byte sArcanineAnims_1_3
.4byte sArcanineAnims_1_4
.4byte sArcanineAnims_1_5
.4byte sArcanineAnims_1_6
.4byte sArcanineAnims_1_7
.4byte sArcanineAnims_1_8
sArcanineAnimTable2:
.4byte sArcanineAnims_2_1
.4byte sArcanineAnims_2_2
.4byte sArcanineAnims_2_3
.4byte sArcanineAnims_2_4
.4byte sArcanineAnims_2_5
.4byte sArcanineAnims_2_6
.4byte sArcanineAnims_2_7
.4byte sArcanineAnims_2_8
sArcanineAnimTable3:
.4byte sArcanineAnims_3_1
.4byte sArcanineAnims_3_2
.4byte sArcanineAnims_3_3
.4byte sArcanineAnims_3_4
.4byte sArcanineAnims_3_5
.4byte sArcanineAnims_3_6
.4byte sArcanineAnims_3_7
.4byte sArcanineAnims_3_8
sArcanineAnimTable4:
.4byte sArcanineAnims_4_1
.4byte sArcanineAnims_4_2
.4byte sArcanineAnims_4_3
.4byte sArcanineAnims_4_4
.4byte sArcanineAnims_4_5
.4byte sArcanineAnims_4_6
.4byte sArcanineAnims_4_7
.4byte sArcanineAnims_4_8
sArcanineAnimTable5:
.4byte sArcanineAnims_5_1
.4byte sArcanineAnims_5_2
.4byte sArcanineAnims_5_3
.4byte sArcanineAnims_5_4
.4byte sArcanineAnims_5_5
.4byte sArcanineAnims_5_6
.4byte sArcanineAnims_5_7
.4byte sArcanineAnims_5_8
sArcanineAnimTable6:
.4byte sArcanineAnims_6_1
.4byte sArcanineAnims_6_1
.4byte sArcanineAnims_6_1
.4byte sArcanineAnims_6_1
.4byte sArcanineAnims_6_1
.4byte sArcanineAnims_6_1
.4byte sArcanineAnims_6_1
.4byte sArcanineAnims_6_1
sArcanineAnimTable7:
.4byte sArcanineAnims_7_1
.4byte sArcanineAnims_7_2
.4byte sArcanineAnims_7_3
.4byte sArcanineAnims_7_4
.4byte sArcanineAnims_7_5
.4byte sArcanineAnims_7_6
.4byte sArcanineAnims_7_7
.4byte sArcanineAnims_7_8
sArcanineAnimTable8:
.4byte sArcanineAnims_8_1
.4byte sArcanineAnims_8_2
.4byte sArcanineAnims_8_3
.4byte sArcanineAnims_8_4
.4byte sArcanineAnims_8_5
.4byte sArcanineAnims_8_6
.4byte sArcanineAnims_8_7
.4byte sArcanineAnims_8_8
sArcanineAnimTable9:
.4byte sArcanineAnims_9_1
.4byte sArcanineAnims_9_2
.4byte sArcanineAnims_9_3
.4byte sArcanineAnims_9_4
.4byte sArcanineAnims_9_5
.4byte sArcanineAnims_9_6
.4byte sArcanineAnims_9_7
.4byte sArcanineAnims_9_8
sArcanineAnimTable10:
.4byte sArcanineAnims_10_1
.4byte sArcanineAnims_10_2
.4byte sArcanineAnims_10_3
.4byte sArcanineAnims_10_4
.4byte sArcanineAnims_10_5
.4byte sArcanineAnims_10_6
.4byte sArcanineAnims_10_7
.4byte sArcanineAnims_10_8
sArcanineAnimTable11:
.4byte sArcanineAnims_11_1
.4byte sArcanineAnims_11_2
.4byte sArcanineAnims_11_3
.4byte sArcanineAnims_11_4
.4byte sArcanineAnims_11_5
.4byte sArcanineAnims_11_6
.4byte sArcanineAnims_11_7
.4byte sArcanineAnims_11_8
sArcanineAnimTable12:
.4byte sArcanineAnims_12_1
.4byte sArcanineAnims_12_2
.4byte sArcanineAnims_12_3
.4byte sArcanineAnims_12_4
.4byte sArcanineAnims_12_5
.4byte sArcanineAnims_12_6
.4byte sArcanineAnims_12_7
.4byte sArcanineAnims_12_8
sArcanineAnimTable13:
.4byte sArcanineAnims_13_1
.4byte sArcanineAnims_13_2
.4byte sArcanineAnims_13_3
.4byte sArcanineAnims_13_4
.4byte sArcanineAnims_13_5
.4byte sArcanineAnims_13_6
.4byte sArcanineAnims_13_7
.4byte sArcanineAnims_13_8
sAxAnimationsArcanine:
.4byte sArcanineAnimTable1
.4byte sArcanineAnimTable2
.4byte sArcanineAnimTable3
.4byte sArcanineAnimTable4
.4byte sArcanineAnimTable5
.4byte sArcanineAnimTable6
.4byte sArcanineAnimTable7
.4byte sArcanineAnimTable8
.4byte sArcanineAnimTable9
.4byte sArcanineAnimTable10
.4byte sArcanineAnimTable11
.4byte sArcanineAnimTable12
.4byte sArcanineAnimTable13
sAxSpritesArcanine:
.4byte sArcanineSprites1
.4byte sArcanineSprites2
.4byte sArcanineSprites3
.4byte sArcanineSprites4
.4byte sArcanineSprites5
.4byte sArcanineSprites6
.4byte sArcanineSprites7
.4byte sArcanineSprites8
.4byte sArcanineSprites9
.4byte sArcanineSprites10
.4byte sArcanineSprites11
.4byte sArcanineSprites12
.4byte sArcanineSprites13
.4byte sArcanineSprites14
.4byte sArcanineSprites15
.4byte sArcanineSprites16
.4byte sArcanineSprites17
.4byte sArcanineSprites18
.4byte sArcanineSprites19
.4byte sArcanineSprites20
.4byte sArcanineSprites21
.4byte sArcanineSprites22
.4byte sArcanineSprites23
.4byte sArcanineSprites24
.4byte sArcanineSprites25
.4byte sArcanineSprites26
.4byte sArcanineSprites27
.4byte sArcanineSprites28
.4byte sArcanineSprites29
.4byte sArcanineSprites30
.4byte sArcanineSprites31
.4byte sArcanineSprites32
.4byte sArcanineSprites33
.4byte sArcanineSprites34
.4byte sArcanineSprites35
.4byte sArcanineSprites36
.4byte sArcanineSprites37
.4byte sArcanineSprites38
.4byte sArcanineSprites39
.4byte sArcanineSprites40
.4byte sArcanineSprites41
.4byte sArcanineSprites42
.4byte sArcanineSprites43
.4byte sArcanineSprites44
.4byte sArcanineSprites45
.4byte sArcanineSprites46
sAxMainArcanine:
ax_main sAxPosesArcanine, sAxAnimationsArcanine, 13, sAxSpritesArcanine, sAxPositionsArcanine
