.global gAxArmaldo
gAxArmaldo:
ax_siro sAxMainArmaldo
sArmaldoPose1:
ax_pose 0, 0x01ea, 0x80f4, 0x5c00
ax_pose_terminator
sArmaldoPose2:
ax_pose 1, 0x01e5, 0x80f4, 0x5c00
ax_pose_terminator
sArmaldoPose3:
ax_pose 2, 0x01e5, 0x80f4, 0x5c00
ax_pose_terminator
sArmaldoPose4:
ax_pose 3, 0x01e3, 0x90ef, 0x5c00
ax_pose_terminator
sArmaldoPose5:
ax_pose 4, 0x01e5, 0x90ed, 0x5c00
ax_pose_terminator
sArmaldoPose6:
ax_pose 5, 0x01e3, 0x90ef, 0x5c00
ax_pose_terminator
sArmaldoPose7:
ax_pose 6, 0x01e4, 0x90eb, 0x5c00
ax_pose_terminator
sArmaldoPose8:
ax_pose 7, 0x81e4, 0x90fe, 0x5c00
ax_pose 8, 0x81e4, 0x50f6, 0x5c08
ax_pose 9, 0x81f4, 0x10ee, 0x5c0c
ax_pose 10, 0x81f4, 0x10e6, 0x5c0e
ax_pose_terminator
sArmaldoPose9:
ax_pose 11, 0x81e4, 0x90fe, 0x5c00
ax_pose 12, 0x81e4, 0x50f6, 0x5c08
ax_pose 13, 0x81f4, 0x10ee, 0x5c0c
ax_pose 14, 0x01f4, 0x10e6, 0x5c0e
ax_pose_terminator
sArmaldoPose10:
ax_pose 15, 0x01e5, 0x90f0, 0x5c00
ax_pose_terminator
sArmaldoPose11:
ax_pose 16, 0x01e6, 0x90f0, 0x5c00
ax_pose_terminator
sArmaldoPose12:
ax_pose 17, 0x01e5, 0x90f0, 0x5c00
ax_pose_terminator
sArmaldoPose13:
ax_pose 18, 0x01e6, 0x80f4, 0x5c00
ax_pose_terminator
sArmaldoPose14:
ax_pose 19, 0x01e6, 0x80f0, 0x5c00
ax_pose_terminator
sArmaldoPose15:
ax_pose 20, 0x01e6, 0x80f0, 0x5c00
ax_pose_terminator
sArmaldoPose16:
ax_pose 15, 0x01e5, 0x80f0, 0x5c00
ax_pose_terminator
sArmaldoPose17:
ax_pose 16, 0x01e6, 0x80f0, 0x5c00
ax_pose_terminator
sArmaldoPose18:
ax_pose 17, 0x01e5, 0x80f0, 0x5c00
ax_pose_terminator
sArmaldoPose19:
ax_pose 6, 0x01e5, 0x80f4, 0x5c00
ax_pose_terminator
sArmaldoPose20:
ax_pose 7, 0x81e5, 0x80f1, 0x5c00
ax_pose 8, 0x81e5, 0x4101, 0x5c08
ax_pose 9, 0x81f5, 0x0109, 0x5c0c
ax_pose 10, 0x81f5, 0x0111, 0x5c0e
ax_pose_terminator
sArmaldoPose21:
ax_pose 11, 0x81e5, 0x80f1, 0x5c00
ax_pose 12, 0x81e5, 0x4101, 0x5c08
ax_pose 13, 0x81f5, 0x0109, 0x5c0c
ax_pose 14, 0x01f5, 0x0111, 0x5c0e
ax_pose_terminator
sArmaldoPose22:
ax_pose 3, 0x01e3, 0x80f0, 0x5c00
ax_pose_terminator
sArmaldoPose23:
ax_pose 4, 0x01e5, 0x80f2, 0x5c00
ax_pose_terminator
sArmaldoPose24:
ax_pose 5, 0x01e3, 0x80f0, 0x5c00
ax_pose_terminator
sArmaldoPose25:
ax_pose 0, 0x01ea, 0x80f4, 0x5c00
ax_pose_terminator
sArmaldoPose26:
ax_pose 1, 0x01e5, 0x80f4, 0x5c00
ax_pose_terminator
sArmaldoPose27:
ax_pose 2, 0x01e5, 0x80f4, 0x5c00
ax_pose_terminator
sArmaldoPose28:
ax_pose 21, 0x41e5, 0x80ef, 0x5c00
ax_pose 22, 0x41f5, 0x40ef, 0x5c08
ax_pose 23, 0x01fd, 0x0107, 0x5c0c
ax_pose 24, 0x41fd, 0x00f7, 0x5c0d
ax_pose 25, 0x01e8, 0x010f, 0x5c0f
ax_pose_terminator
sArmaldoPose29:
ax_pose 26, 0x01e5, 0x80ef, 0x5c00
ax_pose_terminator
sArmaldoPose30:
ax_pose 3, 0x01e3, 0x90ef, 0x5c00
ax_pose_terminator
sArmaldoPose31:
ax_pose 4, 0x01e5, 0x90ed, 0x5c00
ax_pose_terminator
sArmaldoPose32:
ax_pose 5, 0x01e3, 0x90ef, 0x5c00
ax_pose_terminator
sArmaldoPose33:
ax_pose 27, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sArmaldoPose34:
ax_pose 28, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sArmaldoPose35:
ax_pose 6, 0x01e4, 0x90eb, 0x5c00
ax_pose_terminator
sArmaldoPose36:
ax_pose 7, 0x81e4, 0x90fe, 0x5c00
ax_pose 8, 0x81e4, 0x50f6, 0x5c08
ax_pose 9, 0x81f4, 0x10ee, 0x5c0c
ax_pose 10, 0x81f4, 0x10e6, 0x5c0e
ax_pose_terminator
sArmaldoPose37:
ax_pose 11, 0x81e4, 0x90fe, 0x5c00
ax_pose 12, 0x81e4, 0x50f6, 0x5c08
ax_pose 13, 0x81f4, 0x10ee, 0x5c0c
ax_pose 14, 0x01f4, 0x10e6, 0x5c0e
ax_pose_terminator
sArmaldoPose38:
ax_pose 29, 0x41fb, 0x10f0, 0x5c00
ax_pose 30, 0x01fb, 0x1100, 0x5c02
ax_pose 31, 0x41f3, 0x50f0, 0x5c03
ax_pose 32, 0x41e3, 0x90f0, 0x5c07
ax_pose 33, 0x01f3, 0x10e8, 0x5c0f
ax_pose_terminator
sArmaldoPose39:
ax_pose 34, 0x41fd, 0x10f8, 0x5c00
ax_pose 35, 0x41f5, 0x10f8, 0x5c02
ax_pose 36, 0x01f5, 0x10f0, 0x5c04
ax_pose 37, 0x41e5, 0x90f0, 0x5c05
ax_pose 38, 0x81ed, 0x10e8, 0x5c0d
ax_pose_terminator
sArmaldoPose40:
ax_pose 15, 0x01e5, 0x90f0, 0x5c00
ax_pose_terminator
sArmaldoPose41:
ax_pose 16, 0x01e6, 0x90f0, 0x5c00
ax_pose_terminator
sArmaldoPose42:
ax_pose 17, 0x01e5, 0x90f0, 0x5c00
ax_pose_terminator
sArmaldoPose43:
ax_pose 39, 0x01e2, 0x90f1, 0x5c00
ax_pose_terminator
sArmaldoPose44:
ax_pose 40, 0x01e6, 0x90f1, 0x5c00
ax_pose_terminator
sArmaldoPose45:
ax_pose 18, 0x01e6, 0x80f4, 0x5c00
ax_pose_terminator
sArmaldoPose46:
ax_pose 19, 0x01e6, 0x80f0, 0x5c00
ax_pose_terminator
sArmaldoPose47:
ax_pose 20, 0x01e6, 0x80f0, 0x5c00
ax_pose_terminator
sArmaldoPose48:
ax_pose 41, 0x41e6, 0x80ee, 0x5c00
ax_pose 42, 0x41f6, 0x40ee, 0x5c08
ax_pose 43, 0x41fe, 0x00fc, 0x5c0c
ax_pose 44, 0x01fe, 0x00f4, 0x5c0e
ax_pose 45, 0x01e6, 0x010e, 0x5c0f
ax_pose_terminator
sArmaldoPose49:
ax_pose 46, 0x01e6, 0x80ef, 0x5c00
ax_pose_terminator
sArmaldoPose50:
ax_pose 15, 0x01e5, 0x80f0, 0x5c00
ax_pose_terminator
sArmaldoPose51:
ax_pose 16, 0x01e6, 0x80f0, 0x5c00
ax_pose_terminator
sArmaldoPose52:
ax_pose 17, 0x01e5, 0x80f0, 0x5c00
ax_pose_terminator
sArmaldoPose53:
ax_pose 39, 0x01e2, 0x80ef, 0x5c00
ax_pose_terminator
sArmaldoPose54:
ax_pose 40, 0x01e6, 0x80ef, 0x5c00
ax_pose_terminator
sArmaldoPose55:
ax_pose 6, 0x01e5, 0x80f4, 0x5c00
ax_pose_terminator
sArmaldoPose56:
ax_pose 7, 0x81e5, 0x80f1, 0x5c00
ax_pose 8, 0x81e5, 0x4101, 0x5c08
ax_pose 9, 0x81f5, 0x0109, 0x5c0c
ax_pose 10, 0x81f5, 0x0111, 0x5c0e
ax_pose_terminator
sArmaldoPose57:
ax_pose 11, 0x81e5, 0x80f1, 0x5c00
ax_pose 12, 0x81e5, 0x4101, 0x5c08
ax_pose 13, 0x81f5, 0x0109, 0x5c0c
ax_pose 14, 0x01f5, 0x0111, 0x5c0e
ax_pose_terminator
sArmaldoPose58:
ax_pose 29, 0x41fc, 0x00ff, 0x5c00
ax_pose 30, 0x01fc, 0x00f7, 0x5c02
ax_pose 31, 0x41f4, 0x40ef, 0x5c03
ax_pose 32, 0x41e4, 0x80ef, 0x5c07
ax_pose 33, 0x01f4, 0x010f, 0x5c0f
ax_pose_terminator
sArmaldoPose59:
ax_pose 34, 0x41fe, 0x00f7, 0x5c00
ax_pose 35, 0x41f6, 0x00f7, 0x5c02
ax_pose 36, 0x01f6, 0x0107, 0x5c04
ax_pose 37, 0x41e6, 0x80ef, 0x5c05
ax_pose 38, 0x81ee, 0x010f, 0x5c0d
ax_pose_terminator
sArmaldoPose60:
ax_pose 3, 0x01e3, 0x80f0, 0x5c00
ax_pose_terminator
sArmaldoPose61:
ax_pose 4, 0x01e5, 0x80f2, 0x5c00
ax_pose_terminator
sArmaldoPose62:
ax_pose 5, 0x01e3, 0x80f0, 0x5c00
ax_pose_terminator
sArmaldoPose63:
ax_pose 27, 0x01e4, 0x80f0, 0x5c00
ax_pose_terminator
sArmaldoPose64:
ax_pose 28, 0x01e4, 0x80f0, 0x5c00
ax_pose_terminator
sArmaldoPose65:
ax_pose 0, 0x01ea, 0x80f4, 0x5c00
ax_pose_terminator
sArmaldoPose66:
ax_pose 21, 0x41e5, 0x80ef, 0x5c00
ax_pose 22, 0x41f5, 0x40ef, 0x5c08
ax_pose 23, 0x01fd, 0x0107, 0x5c0c
ax_pose 24, 0x41fd, 0x00f7, 0x5c0d
ax_pose 25, 0x01e8, 0x010f, 0x5c0f
ax_pose_terminator
sArmaldoPose67:
ax_pose 47, 0x01e5, 0x80ef, 0x5c00
ax_pose 48, 0x01e5, 0x80ef, 0x5c10
ax_pose_terminator
sArmaldoPose68:
ax_pose 48, 0x01e5, 0x80ef, 0x5c00
ax_pose_terminator
sArmaldoPose69:
ax_pose 3, 0x01e3, 0x90ef, 0x5c00
ax_pose_terminator
sArmaldoPose70:
ax_pose 27, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sArmaldoPose71:
ax_pose 49, 0x01e4, 0x90f8, 0x5c00
ax_pose 50, 0x01e4, 0x90ef, 0x5c10
ax_pose_terminator
sArmaldoPose72:
ax_pose 50, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sArmaldoPose73:
ax_pose 6, 0x01e4, 0x90eb, 0x5c00
ax_pose_terminator
sArmaldoPose74:
ax_pose 29, 0x41fb, 0x10f0, 0x5c00
ax_pose 30, 0x01fb, 0x1100, 0x5c02
ax_pose 31, 0x41f3, 0x50f0, 0x5c03
ax_pose 32, 0x41e3, 0x90f0, 0x5c07
ax_pose 33, 0x01f3, 0x10e8, 0x5c0f
ax_pose_terminator
sArmaldoPose75:
ax_pose 51, 0x81e2, 0x9105, 0x5c00
ax_pose 52, 0x41f3, 0x90f0, 0x5c08
ax_pose 53, 0x41eb, 0x50f0, 0x5c10
ax_pose 54, 0x41e3, 0x1100, 0x5c14
ax_pose 55, 0x01eb, 0x10e8, 0x5c16
ax_pose 56, 0x01f3, 0x10e8, 0x5c17
ax_pose_terminator
sArmaldoPose76:
ax_pose 52, 0x41f3, 0x90f0, 0x5c00
ax_pose 53, 0x41eb, 0x50f0, 0x5c08
ax_pose 54, 0x41e3, 0x1100, 0x5c0c
ax_pose 55, 0x01eb, 0x10e8, 0x5c0e
ax_pose 56, 0x01f3, 0x10e8, 0x5c0f
ax_pose_terminator
sArmaldoPose77:
ax_pose 15, 0x01e5, 0x90f0, 0x5c00
ax_pose_terminator
sArmaldoPose78:
ax_pose 39, 0x01e2, 0x90f1, 0x5c00
ax_pose_terminator
sArmaldoPose79:
ax_pose 57, 0x01df, 0x90f5, 0x5c00
ax_pose 58, 0x01e6, 0x90f1, 0x5c10
ax_pose_terminator
sArmaldoPose80:
ax_pose 58, 0x01e6, 0x90f1, 0x5c00
ax_pose_terminator
sArmaldoPose81:
ax_pose 18, 0x01e6, 0x80f4, 0x5c00
ax_pose_terminator
sArmaldoPose82:
ax_pose 41, 0x41e6, 0x80ee, 0x5c00
ax_pose 42, 0x41f6, 0x40ee, 0x5c08
ax_pose 43, 0x41fe, 0x00fc, 0x5c0c
ax_pose 44, 0x01fe, 0x00f4, 0x5c0e
ax_pose 45, 0x01e6, 0x010e, 0x5c0f
ax_pose_terminator
sArmaldoPose83:
ax_pose 59, 0x41e0, 0x80f0, 0x5c00
ax_pose 60, 0x41f0, 0x40f0, 0x5c08
ax_pose 61, 0x01e8, 0x0110, 0x5c0c
ax_pose 62, 0x01e0, 0x0110, 0x5c0d
ax_pose 63, 0x01e6, 0x80ef, 0x5c0e
ax_pose_terminator
sArmaldoPose84:
ax_pose 63, 0x01e6, 0x80ef, 0x5c00
ax_pose_terminator
sArmaldoPose85:
ax_pose 15, 0x01e5, 0x80f0, 0x5c00
ax_pose_terminator
sArmaldoPose86:
ax_pose 39, 0x01e2, 0x80ef, 0x5c00
ax_pose_terminator
sArmaldoPose87:
ax_pose 57, 0x01df, 0x80eb, 0x5c00
ax_pose 58, 0x01e6, 0x80ef, 0x5c10
ax_pose_terminator
sArmaldoPose88:
ax_pose 58, 0x01e6, 0x80ef, 0x5c00
ax_pose_terminator
sArmaldoPose89:
ax_pose 6, 0x01e5, 0x80f4, 0x5c00
ax_pose_terminator
sArmaldoPose90:
ax_pose 29, 0x41fc, 0x00ff, 0x5c00
ax_pose 30, 0x01fc, 0x00f7, 0x5c02
ax_pose 31, 0x41f4, 0x40ef, 0x5c03
ax_pose 32, 0x41e4, 0x80ef, 0x5c07
ax_pose 33, 0x01f4, 0x010f, 0x5c0f
ax_pose_terminator
sArmaldoPose91:
ax_pose 51, 0x81e3, 0x80ea, 0x5c00
ax_pose 52, 0x41f4, 0x80ef, 0x5c08
ax_pose 53, 0x41ec, 0x40ef, 0x5c10
ax_pose 54, 0x41e4, 0x00ef, 0x5c14
ax_pose 55, 0x01ec, 0x010f, 0x5c16
ax_pose 56, 0x01f4, 0x010f, 0x5c17
ax_pose_terminator
sArmaldoPose92:
ax_pose 52, 0x41f4, 0x80ef, 0x5c00
ax_pose 53, 0x41ec, 0x40ef, 0x5c08
ax_pose 54, 0x41e4, 0x00ef, 0x5c0c
ax_pose 55, 0x01ec, 0x010f, 0x5c0e
ax_pose 56, 0x01f4, 0x010f, 0x5c0f
ax_pose_terminator
sArmaldoPose93:
ax_pose 3, 0x01e3, 0x80f0, 0x5c00
ax_pose_terminator
sArmaldoPose94:
ax_pose 27, 0x01e4, 0x80f0, 0x5c00
ax_pose_terminator
sArmaldoPose95:
ax_pose 49, 0x01e4, 0x80e7, 0x5c00
ax_pose 50, 0x01e4, 0x80f0, 0x5c10
ax_pose_terminator
sArmaldoPose96:
ax_pose 50, 0x01e4, 0x80f0, 0x5c00
ax_pose_terminator
sArmaldoPose97:
ax_pose 0, 0x01ea, 0x80f4, 0x5c00
ax_pose_terminator
sArmaldoPose98:
ax_pose 21, 0x41e5, 0x80ef, 0x5c00
ax_pose 22, 0x41f5, 0x40ef, 0x5c08
ax_pose 23, 0x01fd, 0x0107, 0x5c0c
ax_pose 24, 0x41fd, 0x00f7, 0x5c0d
ax_pose 25, 0x01e8, 0x010f, 0x5c0f
ax_pose_terminator
sArmaldoPose99:
ax_pose 26, 0x01e5, 0x80ef, 0x5c00
ax_pose_terminator
sArmaldoPose100:
ax_pose 3, 0x01e3, 0x90ef, 0x5c00
ax_pose_terminator
sArmaldoPose101:
ax_pose 27, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sArmaldoPose102:
ax_pose 28, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sArmaldoPose103:
ax_pose 6, 0x01e4, 0x90eb, 0x5c00
ax_pose_terminator
sArmaldoPose104:
ax_pose 29, 0x41fb, 0x10f0, 0x5c00
ax_pose 30, 0x01fb, 0x1100, 0x5c02
ax_pose 31, 0x41f3, 0x50f0, 0x5c03
ax_pose 32, 0x41e3, 0x90f0, 0x5c07
ax_pose 33, 0x01f3, 0x10e8, 0x5c0f
ax_pose_terminator
sArmaldoPose105:
ax_pose 34, 0x41fd, 0x10f8, 0x5c00
ax_pose 35, 0x41f5, 0x10f8, 0x5c02
ax_pose 36, 0x01f5, 0x10f0, 0x5c04
ax_pose 37, 0x41e5, 0x90f0, 0x5c05
ax_pose 38, 0x81ed, 0x10e8, 0x5c0d
ax_pose_terminator
sArmaldoPose106:
ax_pose 15, 0x01e5, 0x90f0, 0x5c00
ax_pose_terminator
sArmaldoPose107:
ax_pose 39, 0x01e2, 0x90f1, 0x5c00
ax_pose_terminator
sArmaldoPose108:
ax_pose 40, 0x01e6, 0x90f1, 0x5c00
ax_pose_terminator
sArmaldoPose109:
ax_pose 18, 0x01e6, 0x80f4, 0x5c00
ax_pose_terminator
sArmaldoPose110:
ax_pose 41, 0x41e6, 0x80ee, 0x5c00
ax_pose 42, 0x41f6, 0x40ee, 0x5c08
ax_pose 43, 0x41fe, 0x00fc, 0x5c0c
ax_pose 44, 0x01fe, 0x00f4, 0x5c0e
ax_pose 45, 0x01e6, 0x010e, 0x5c0f
ax_pose_terminator
sArmaldoPose111:
ax_pose 46, 0x01e6, 0x80ef, 0x5c00
ax_pose_terminator
sArmaldoPose112:
ax_pose 15, 0x01e5, 0x80f0, 0x5c00
ax_pose_terminator
sArmaldoPose113:
ax_pose 39, 0x01e2, 0x80ef, 0x5c00
ax_pose_terminator
sArmaldoPose114:
ax_pose 40, 0x01e6, 0x80ef, 0x5c00
ax_pose_terminator
sArmaldoPose115:
ax_pose 6, 0x01e5, 0x80f4, 0x5c00
ax_pose_terminator
sArmaldoPose116:
ax_pose 29, 0x41fc, 0x00ff, 0x5c00
ax_pose 30, 0x01fc, 0x00f7, 0x5c02
ax_pose 31, 0x41f4, 0x40ef, 0x5c03
ax_pose 32, 0x41e4, 0x80ef, 0x5c07
ax_pose 33, 0x01f4, 0x010f, 0x5c0f
ax_pose_terminator
sArmaldoPose117:
ax_pose 34, 0x41fe, 0x00f7, 0x5c00
ax_pose 35, 0x41f6, 0x00f7, 0x5c02
ax_pose 36, 0x01f6, 0x0107, 0x5c04
ax_pose 37, 0x41e6, 0x80ef, 0x5c05
ax_pose 38, 0x81ee, 0x010f, 0x5c0d
ax_pose_terminator
sArmaldoPose118:
ax_pose 3, 0x01e3, 0x80f0, 0x5c00
ax_pose_terminator
sArmaldoPose119:
ax_pose 27, 0x01e4, 0x80f0, 0x5c00
ax_pose_terminator
sArmaldoPose120:
ax_pose 28, 0x01e4, 0x80f0, 0x5c00
ax_pose_terminator
sArmaldoPose121:
ax_pose 0, 0x01ea, 0x80f4, 0x5c00
ax_pose_terminator
sArmaldoPose122:
ax_pose 3, 0x01e4, 0x80f1, 0x5c00
ax_pose_terminator
sArmaldoPose123:
ax_pose 6, 0x01e5, 0x80f5, 0x5c00
ax_pose_terminator
sArmaldoPose124:
ax_pose 15, 0x01e5, 0x80f1, 0x5c00
ax_pose_terminator
sArmaldoPose125:
ax_pose 18, 0x01e6, 0x80f4, 0x5c00
ax_pose_terminator
sArmaldoPose126:
ax_pose 15, 0x01e5, 0x90ef, 0x5c00
ax_pose_terminator
sArmaldoPose127:
ax_pose 6, 0x01e4, 0x90ec, 0x5c00
ax_pose_terminator
sArmaldoPose128:
ax_pose 3, 0x01e4, 0x90f0, 0x5c00
ax_pose_terminator
sArmaldoPose129:
ax_pose 64, 0x01e8, 0x80f2, 0x5c00
ax_pose_terminator
sArmaldoPose130:
ax_pose 65, 0x01e8, 0x80f2, 0x5c00
ax_pose_terminator
sArmaldoPose131:
ax_pose 66, 0x01e2, 0x80f2, 0x5c00
ax_pose_terminator
sArmaldoPose132:
ax_pose 67, 0x01e3, 0x90f0, 0x5c00
ax_pose_terminator
sArmaldoPose133:
ax_pose 68, 0x01e3, 0x90e9, 0x5c00
ax_pose_terminator
sArmaldoPose134:
ax_pose 69, 0x01e2, 0x90ef, 0x5c00
ax_pose_terminator
sArmaldoPose135:
ax_pose 70, 0x01e5, 0x80f1, 0x5c00
ax_pose_terminator
sArmaldoPose136:
ax_pose 69, 0x01e2, 0x80f1, 0x5c00
ax_pose_terminator
sArmaldoPose137:
ax_pose 68, 0x01e3, 0x80f7, 0x5c00
ax_pose_terminator
sArmaldoPose138:
ax_pose 67, 0x01e3, 0x80f0, 0x5c00
ax_pose_terminator
sArmaldoPose139:
ax_pose 0, 0x01ea, 0x80f4, 0x5c00
ax_pose_terminator
sArmaldoPose140:
ax_pose 21, 0x41e5, 0x80ef, 0x5c00
ax_pose 22, 0x41f5, 0x40ef, 0x5c08
ax_pose 23, 0x01fd, 0x0107, 0x5c0c
ax_pose 24, 0x41fd, 0x00f7, 0x5c0d
ax_pose 25, 0x01e8, 0x010f, 0x5c0f
ax_pose_terminator
sArmaldoPose141:
ax_pose 26, 0x01e5, 0x80ef, 0x5c00
ax_pose_terminator
sArmaldoPose142:
ax_pose 3, 0x01e3, 0x90ef, 0x5c00
ax_pose_terminator
sArmaldoPose143:
ax_pose 27, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sArmaldoPose144:
ax_pose 28, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sArmaldoPose145:
ax_pose 6, 0x01e4, 0x90eb, 0x5c00
ax_pose_terminator
sArmaldoPose146:
ax_pose 29, 0x41fb, 0x10f0, 0x5c00
ax_pose 30, 0x01fb, 0x1100, 0x5c02
ax_pose 31, 0x41f3, 0x50f0, 0x5c03
ax_pose 32, 0x41e3, 0x90f0, 0x5c07
ax_pose 33, 0x01f3, 0x10e8, 0x5c0f
ax_pose_terminator
sArmaldoPose147:
ax_pose 34, 0x41fd, 0x10f8, 0x5c00
ax_pose 35, 0x41f5, 0x10f8, 0x5c02
ax_pose 36, 0x01f5, 0x10f0, 0x5c04
ax_pose 37, 0x41e5, 0x90f0, 0x5c05
ax_pose 38, 0x81ed, 0x10e8, 0x5c0d
ax_pose_terminator
sArmaldoPose148:
ax_pose 15, 0x01e5, 0x90f0, 0x5c00
ax_pose_terminator
sArmaldoPose149:
ax_pose 39, 0x01e2, 0x90f1, 0x5c00
ax_pose_terminator
sArmaldoPose150:
ax_pose 40, 0x01e6, 0x90f1, 0x5c00
ax_pose_terminator
sArmaldoPose151:
ax_pose 18, 0x01e6, 0x80f4, 0x5c00
ax_pose_terminator
sArmaldoPose152:
ax_pose 41, 0x41e6, 0x80ee, 0x5c00
ax_pose 42, 0x41f6, 0x40ee, 0x5c08
ax_pose 43, 0x41fe, 0x00fc, 0x5c0c
ax_pose 44, 0x01fe, 0x00f4, 0x5c0e
ax_pose 45, 0x01e6, 0x010e, 0x5c0f
ax_pose_terminator
sArmaldoPose153:
ax_pose 46, 0x01e6, 0x80ef, 0x5c00
ax_pose_terminator
sArmaldoPose154:
ax_pose 15, 0x01e5, 0x80f0, 0x5c00
ax_pose_terminator
sArmaldoPose155:
ax_pose 39, 0x01e2, 0x80ef, 0x5c00
ax_pose_terminator
sArmaldoPose156:
ax_pose 40, 0x01e6, 0x80ef, 0x5c00
ax_pose_terminator
sArmaldoPose157:
ax_pose 6, 0x01e5, 0x80f4, 0x5c00
ax_pose_terminator
sArmaldoPose158:
ax_pose 29, 0x41fc, 0x00ff, 0x5c00
ax_pose 30, 0x01fc, 0x00f7, 0x5c02
ax_pose 31, 0x41f4, 0x40ef, 0x5c03
ax_pose 32, 0x41e4, 0x80ef, 0x5c07
ax_pose 33, 0x01f4, 0x010f, 0x5c0f
ax_pose_terminator
sArmaldoPose159:
ax_pose 34, 0x41fe, 0x00f7, 0x5c00
ax_pose 35, 0x41f6, 0x00f7, 0x5c02
ax_pose 36, 0x01f6, 0x0107, 0x5c04
ax_pose 37, 0x41e6, 0x80ef, 0x5c05
ax_pose 38, 0x81ee, 0x010f, 0x5c0d
ax_pose_terminator
sArmaldoPose160:
ax_pose 3, 0x01e3, 0x80f0, 0x5c00
ax_pose_terminator
sArmaldoPose161:
ax_pose 27, 0x01e4, 0x80f0, 0x5c00
ax_pose_terminator
sArmaldoPose162:
ax_pose 28, 0x01e4, 0x80f0, 0x5c00
ax_pose_terminator
sArmaldoPose163:
ax_pose 26, 0x01e6, 0x80ef, 0x5c00
ax_pose_terminator
sArmaldoPose164:
ax_pose 28, 0x01e6, 0x80f0, 0x5c00
ax_pose_terminator
sArmaldoPose165:
ax_pose 34, 0x41fe, 0x00f7, 0x5c00
ax_pose 35, 0x41f6, 0x00f7, 0x5c02
ax_pose 36, 0x01f6, 0x0107, 0x5c04
ax_pose 37, 0x41e6, 0x80ef, 0x5c05
ax_pose 38, 0x81ee, 0x010f, 0x5c0d
ax_pose_terminator
sArmaldoPose166:
ax_pose 40, 0x01e7, 0x80ef, 0x5c00
ax_pose_terminator
sArmaldoPose167:
ax_pose 46, 0x01e7, 0x80ef, 0x5c00
ax_pose_terminator
sArmaldoPose168:
ax_pose 40, 0x01e7, 0x90f1, 0x5c00
ax_pose_terminator
sArmaldoPose169:
ax_pose 34, 0x41fe, 0x10f8, 0x5c00
ax_pose 35, 0x41f6, 0x10f8, 0x5c02
ax_pose 36, 0x01f6, 0x10f0, 0x5c04
ax_pose 37, 0x41e6, 0x90f0, 0x5c05
ax_pose 38, 0x81ee, 0x10e8, 0x5c0d
ax_pose_terminator
sArmaldoPose170:
ax_pose 28, 0x01e6, 0x90f0, 0x5c00
ax_pose_terminator
sArmaldoPose171:
ax_pose 3, 0x01e3, 0x90ef, 0x5c00
ax_pose_terminator
sArmaldoPose172:
ax_pose 4, 0x01e5, 0x90ed, 0x5c00
ax_pose_terminator
sArmaldoPose173:
ax_pose 5, 0x01e3, 0x90ef, 0x5c00
ax_pose_terminator
sArmaldoPose174:
ax_pose 27, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sArmaldoPose175:
ax_pose 6, 0x01e4, 0x90eb, 0x5c00
ax_pose_terminator
sArmaldoPose176:
ax_pose 7, 0x81e4, 0x90fe, 0x5c00
ax_pose 8, 0x81e4, 0x50f6, 0x5c08
ax_pose 9, 0x81f4, 0x10ee, 0x5c0c
ax_pose 10, 0x81f4, 0x10e6, 0x5c0e
ax_pose_terminator
sArmaldoPose177:
ax_pose 11, 0x81e4, 0x90fe, 0x5c00
ax_pose 12, 0x81e4, 0x50f6, 0x5c08
ax_pose 13, 0x81f4, 0x10ee, 0x5c0c
ax_pose 14, 0x01f4, 0x10e6, 0x5c0e
ax_pose_terminator
sArmaldoPose178:
ax_pose 29, 0x41fb, 0x10f0, 0x5c00
ax_pose 30, 0x01fb, 0x1100, 0x5c02
ax_pose 31, 0x41f3, 0x50f0, 0x5c03
ax_pose 32, 0x41e3, 0x90f0, 0x5c07
ax_pose 33, 0x01f3, 0x10e8, 0x5c0f
ax_pose_terminator
sArmaldoPose179:
ax_pose 15, 0x01e5, 0x90f0, 0x5c00
ax_pose_terminator
sArmaldoPose180:
ax_pose 16, 0x01e6, 0x90f0, 0x5c00
ax_pose_terminator
sArmaldoPose181:
ax_pose 17, 0x01e5, 0x90f0, 0x5c00
ax_pose_terminator
sArmaldoPose182:
ax_pose 39, 0x01e2, 0x90f1, 0x5c00
ax_pose_terminator
sArmaldoPose183:
ax_pose 18, 0x01e6, 0x80f4, 0x5c00
ax_pose_terminator
sArmaldoPose184:
ax_pose 19, 0x01e6, 0x80f0, 0x5c00
ax_pose_terminator
sArmaldoPose185:
ax_pose 20, 0x01e6, 0x80f0, 0x5c00
ax_pose_terminator
sArmaldoPose186:
ax_pose 41, 0x41e6, 0x80ee, 0x5c00
ax_pose 42, 0x41f6, 0x40ee, 0x5c08
ax_pose 43, 0x41fe, 0x00fc, 0x5c0c
ax_pose 44, 0x01fe, 0x00f4, 0x5c0e
ax_pose 45, 0x01e6, 0x010e, 0x5c0f
ax_pose_terminator
sArmaldoPose187:
ax_pose 15, 0x01e5, 0x80f0, 0x5c00
ax_pose_terminator
sArmaldoPose188:
ax_pose 16, 0x01e6, 0x80f0, 0x5c00
ax_pose_terminator
sArmaldoPose189:
ax_pose 17, 0x01e5, 0x80f0, 0x5c00
ax_pose_terminator
sArmaldoPose190:
ax_pose 39, 0x01e2, 0x80ef, 0x5c00
ax_pose_terminator
sArmaldoPose191:
ax_pose 6, 0x01e5, 0x80f4, 0x5c00
ax_pose_terminator
sArmaldoPose192:
ax_pose 7, 0x81e5, 0x80f1, 0x5c00
ax_pose 8, 0x81e5, 0x4101, 0x5c08
ax_pose 9, 0x81f5, 0x0109, 0x5c0c
ax_pose 10, 0x81f5, 0x0111, 0x5c0e
ax_pose_terminator
sArmaldoPose193:
ax_pose 11, 0x81e5, 0x80f1, 0x5c00
ax_pose 12, 0x81e5, 0x4101, 0x5c08
ax_pose 13, 0x81f5, 0x0109, 0x5c0c
ax_pose 14, 0x01f5, 0x0111, 0x5c0e
ax_pose_terminator
sArmaldoPose194:
ax_pose 29, 0x41fc, 0x00ff, 0x5c00
ax_pose 30, 0x01fc, 0x00f7, 0x5c02
ax_pose 31, 0x41f4, 0x40ef, 0x5c03
ax_pose 32, 0x41e4, 0x80ef, 0x5c07
ax_pose 33, 0x01f4, 0x010f, 0x5c0f
ax_pose_terminator
sArmaldoPose195:
ax_pose 3, 0x01e3, 0x80f0, 0x5c00
ax_pose_terminator
sArmaldoPose196:
ax_pose 4, 0x01e5, 0x80f2, 0x5c00
ax_pose_terminator
sArmaldoPose197:
ax_pose 5, 0x01e3, 0x80f0, 0x5c00
ax_pose_terminator
sArmaldoPose198:
ax_pose 27, 0x01e4, 0x80f0, 0x5c00
ax_pose_terminator
sArmaldoPose199:
ax_pose 21, 0x41e6, 0x80ef, 0x5c00
ax_pose 22, 0x41f6, 0x40ef, 0x5c08
ax_pose 23, 0x01fe, 0x0107, 0x5c0c
ax_pose 24, 0x41fe, 0x00f7, 0x5c0d
ax_pose 25, 0x01e9, 0x010f, 0x5c0f
ax_pose_terminator
sArmaldoPose200:
ax_pose 27, 0x01e6, 0x90f0, 0x5c00
ax_pose_terminator
sArmaldoPose201:
ax_pose 29, 0x41fc, 0x10f0, 0x5c00
ax_pose 30, 0x01fc, 0x1100, 0x5c02
ax_pose 31, 0x41f4, 0x50f0, 0x5c03
ax_pose 32, 0x41e4, 0x90f0, 0x5c07
ax_pose 33, 0x01f4, 0x10e8, 0x5c0f
ax_pose_terminator
sArmaldoPose202:
ax_pose 39, 0x01e4, 0x90f1, 0x5c00
ax_pose_terminator
sArmaldoPose203:
ax_pose 41, 0x41e7, 0x80ee, 0x5c00
ax_pose 42, 0x41f7, 0x40ee, 0x5c08
ax_pose 43, 0x41ff, 0x00fc, 0x5c0c
ax_pose 44, 0x01ff, 0x00f4, 0x5c0e
ax_pose 45, 0x01e7, 0x010e, 0x5c0f
ax_pose_terminator
sArmaldoPose204:
ax_pose 39, 0x01e4, 0x80ef, 0x5c00
ax_pose_terminator
sArmaldoPose205:
ax_pose 29, 0x41fc, 0x0100, 0x5c00
ax_pose 30, 0x01fc, 0x00f8, 0x5c02
ax_pose 31, 0x41f4, 0x40f0, 0x5c03
ax_pose 32, 0x41e4, 0x80f0, 0x5c07
ax_pose 33, 0x01f4, 0x0110, 0x5c0f
ax_pose_terminator
sArmaldoPose206:
ax_pose 27, 0x01e6, 0x80f0, 0x5c00
ax_pose_terminator
sArmaldoPose207:
ax_pose 0, 0x01eb, 0x80f4, 0x5c00
ax_pose_terminator
sArmaldoPose208:
ax_pose 21, 0x41e6, 0x80ef, 0x5c00
ax_pose 22, 0x41f6, 0x40ef, 0x5c08
ax_pose 23, 0x01fe, 0x0107, 0x5c0c
ax_pose 24, 0x41fe, 0x00f7, 0x5c0d
ax_pose 25, 0x01e9, 0x010f, 0x5c0f
ax_pose_terminator
sArmaldoPose209:
ax_pose 26, 0x01e6, 0x80ef, 0x5c00
ax_pose_terminator
sArmaldoPose210:
ax_pose 3, 0x01e5, 0x90ef, 0x5c00
ax_pose_terminator
sArmaldoPose211:
ax_pose 27, 0x01e6, 0x90ef, 0x5c00
ax_pose_terminator
sArmaldoPose212:
ax_pose 28, 0x01e6, 0x90ee, 0x5c00
ax_pose_terminator
sArmaldoPose213:
ax_pose 6, 0x01e5, 0x90eb, 0x5c00
ax_pose_terminator
sArmaldoPose214:
ax_pose 29, 0x41fc, 0x10f0, 0x5c00
ax_pose 30, 0x01fc, 0x1100, 0x5c02
ax_pose 31, 0x41f4, 0x50f0, 0x5c03
ax_pose 32, 0x41e4, 0x90f0, 0x5c07
ax_pose 33, 0x01f4, 0x10e8, 0x5c0f
ax_pose_terminator
sArmaldoPose215:
ax_pose 34, 0x41fe, 0x10f7, 0x5c00
ax_pose 35, 0x41f6, 0x10f7, 0x5c02
ax_pose 36, 0x01f6, 0x10ef, 0x5c04
ax_pose 37, 0x41e6, 0x90ef, 0x5c05
ax_pose 38, 0x81ee, 0x10e7, 0x5c0d
ax_pose_terminator
sArmaldoPose216:
ax_pose 15, 0x01e6, 0x90f0, 0x5c00
ax_pose_terminator
sArmaldoPose217:
ax_pose 39, 0x01e3, 0x90f1, 0x5c00
ax_pose_terminator
sArmaldoPose218:
ax_pose 40, 0x01e7, 0x90f0, 0x5c00
ax_pose_terminator
sArmaldoPose219:
ax_pose 18, 0x01e7, 0x80f4, 0x5c00
ax_pose_terminator
sArmaldoPose220:
ax_pose 41, 0x41e7, 0x80ee, 0x5c00
ax_pose 42, 0x41f7, 0x40ee, 0x5c08
ax_pose 43, 0x41ff, 0x00fc, 0x5c0c
ax_pose 44, 0x01ff, 0x00f4, 0x5c0e
ax_pose 45, 0x01e7, 0x010e, 0x5c0f
ax_pose_terminator
sArmaldoPose221:
ax_pose 46, 0x01e7, 0x80ef, 0x5c00
ax_pose_terminator
sArmaldoPose222:
ax_pose 15, 0x01e6, 0x80f0, 0x5c00
ax_pose_terminator
sArmaldoPose223:
ax_pose 39, 0x01e3, 0x80ef, 0x5c00
ax_pose_terminator
sArmaldoPose224:
ax_pose 40, 0x01e7, 0x80f0, 0x5c00
ax_pose_terminator
sArmaldoPose225:
ax_pose 6, 0x01e5, 0x80f5, 0x5c00
ax_pose_terminator
sArmaldoPose226:
ax_pose 29, 0x41fc, 0x0100, 0x5c00
ax_pose 30, 0x01fc, 0x00f8, 0x5c02
ax_pose 31, 0x41f4, 0x40f0, 0x5c03
ax_pose 32, 0x41e4, 0x80f0, 0x5c07
ax_pose 33, 0x01f4, 0x0110, 0x5c0f
ax_pose_terminator
sArmaldoPose227:
ax_pose 34, 0x41fe, 0x00f9, 0x5c00
ax_pose 35, 0x41f6, 0x00f9, 0x5c02
ax_pose 36, 0x01f6, 0x0109, 0x5c04
ax_pose 37, 0x41e6, 0x80f1, 0x5c05
ax_pose 38, 0x81ee, 0x0111, 0x5c0d
ax_pose_terminator
sArmaldoPose228:
ax_pose 3, 0x01e5, 0x80f1, 0x5c00
ax_pose_terminator
sArmaldoPose229:
ax_pose 27, 0x01e6, 0x80f1, 0x5c00
ax_pose_terminator
sArmaldoPose230:
ax_pose 28, 0x01e6, 0x80f2, 0x5c00
ax_pose_terminator
sArmaldoPose231:
ax_pose 48, 0x01e4, 0x80ef, 0x5c00
ax_pose_terminator
sArmaldoPose232:
ax_pose 50, 0x01e4, 0x80f1, 0x5c00
ax_pose_terminator
sArmaldoPose233:
ax_pose 52, 0x41f4, 0x80ef, 0x5c00
ax_pose 53, 0x41ec, 0x40ef, 0x5c08
ax_pose 54, 0x41e4, 0x00ef, 0x5c0c
ax_pose 55, 0x01ec, 0x010f, 0x5c0e
ax_pose 56, 0x01f4, 0x010f, 0x5c0f
ax_pose_terminator
sArmaldoPose234:
ax_pose 58, 0x01e6, 0x80ef, 0x5c00
ax_pose_terminator
sArmaldoPose235:
ax_pose 63, 0x01e6, 0x80ef, 0x5c00
ax_pose_terminator
sArmaldoPose236:
ax_pose 58, 0x01e6, 0x90f1, 0x5c00
ax_pose_terminator
sArmaldoPose237:
ax_pose 52, 0x41f4, 0x90f1, 0x5c00
ax_pose 53, 0x41ec, 0x50f1, 0x5c08
ax_pose 54, 0x41e4, 0x1101, 0x5c0c
ax_pose 55, 0x01ec, 0x10e9, 0x5c0e
ax_pose 56, 0x01f4, 0x10e9, 0x5c0f
ax_pose_terminator
sArmaldoPose238:
ax_pose 50, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sArmaldoPose239:
ax_pose 0, 0x01ea, 0x80f4, 0x5c00
ax_pose_terminator
sArmaldoPose240:
ax_pose 3, 0x01e4, 0x80f1, 0x5c00
ax_pose_terminator
sArmaldoPose241:
ax_pose 6, 0x01e5, 0x80f5, 0x5c00
ax_pose_terminator
sArmaldoPose242:
ax_pose 15, 0x01e5, 0x80f1, 0x5c00
ax_pose_terminator
sArmaldoPose243:
ax_pose 18, 0x01e6, 0x80f4, 0x5c00
ax_pose_terminator
sArmaldoPose244:
ax_pose 15, 0x01e5, 0x90ef, 0x5c00
ax_pose_terminator
sArmaldoPose245:
ax_pose 6, 0x01e4, 0x90ec, 0x5c00
ax_pose_terminator
sArmaldoPose246:
ax_pose 3, 0x01e4, 0x90f0, 0x5c00
ax_pose_terminator
.align 2
sArmaldoAnims_1_1:
ax_anim 8, 0, 0, 0, 0, 0, 0,
ax_anim 12, 0, 1, 0, 0, 0, 0,
ax_anim 8, 0, 0, 0, 0, 0, 0,
ax_anim 12, 0, 2, 0, 0, 0, 0,
ax_anim_terminator
sArmaldoAnims_1_2:
ax_anim 8, 0, 3, 0, 0, 0, 0,
ax_anim 12, 0, 4, 0, 0, 0, 0,
ax_anim 8, 0, 3, 0, 0, 0, 0,
ax_anim 12, 0, 5, 0, 0, 0, 0,
ax_anim_terminator
sArmaldoAnims_1_3:
ax_anim 8, 0, 6, 0, 0, 0, 0,
ax_anim 12, 0, 7, 0, 0, 0, 0,
ax_anim 8, 0, 6, 0, 0, 0, 0,
ax_anim 12, 0, 8, 0, 0, 0, 0,
ax_anim_terminator
sArmaldoAnims_1_4:
ax_anim 8, 0, 9, 0, 0, 0, 0,
ax_anim 12, 0, 10, 0, 0, 0, 0,
ax_anim 8, 0, 9, 0, 0, 0, 0,
ax_anim 12, 0, 11, 0, 0, 0, 0,
ax_anim_terminator
sArmaldoAnims_1_5:
ax_anim 8, 0, 12, 0, 0, 0, 0,
ax_anim 12, 0, 13, 0, 0, 0, 0,
ax_anim 8, 0, 12, 0, 0, 0, 0,
ax_anim 12, 0, 14, 0, 0, 0, 0,
ax_anim_terminator
sArmaldoAnims_1_6:
ax_anim 8, 0, 15, 0, 0, 0, 0,
ax_anim 12, 0, 16, 0, 0, 0, 0,
ax_anim 8, 0, 15, 0, 0, 0, 0,
ax_anim 12, 0, 17, 0, 0, 0, 0,
ax_anim_terminator
sArmaldoAnims_1_7:
ax_anim 8, 0, 18, 0, 0, 0, 0,
ax_anim 12, 0, 19, 0, 0, 0, 0,
ax_anim 8, 0, 18, 0, 0, 0, 0,
ax_anim 12, 0, 20, 0, 0, 0, 0,
ax_anim_terminator
sArmaldoAnims_1_8:
ax_anim 8, 0, 21, 0, 0, 0, 0,
ax_anim 12, 0, 22, 0, 0, 0, 0,
ax_anim 8, 0, 21, 0, 0, 0, 0,
ax_anim 12, 0, 23, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sArmaldoAnims_2_1:
ax_anim 2, 0, 27, 0, -1, 0, -1,
ax_anim 6, 0, 27, 0, -2, 0, -2,
ax_anim 1, 0, 26, 0, 0, 0, 0,
ax_anim 1, 2, 25, 0, 4, 0, 4,
ax_anim 1, 0, 26, 0, 10, 0, 10,
ax_anim 2, 0, 28, 0, 21, 0, 21,
ax_anim 2, 1, 28, 1, 21, 1, 21,
ax_anim 2, 0, 28, 0, 21, 0, 21,
ax_anim 2, 0, 28, 1, 21, 1, 21,
ax_anim 2, 0, 24, 0, 6, 0, 6,
ax_anim_terminator
sArmaldoAnims_2_2:
ax_anim 2, 0, 32, -1, -1, -1, -1,
ax_anim 6, 0, 32, -2, -2, -2, -2,
ax_anim 1, 0, 31, 0, 0, 0, 0,
ax_anim 1, 2, 30, 4, 4, 4, 4,
ax_anim 1, 0, 31, 10, 11, 10, 11,
ax_anim 2, 0, 33, 18, 22, 18, 22,
ax_anim 2, 1, 33, 19, 21, 19, 21,
ax_anim 2, 0, 33, 18, 22, 18, 22,
ax_anim 2, 0, 33, 19, 21, 19, 21,
ax_anim 2, 0, 29, 6, 7, 6, 7,
ax_anim_terminator
sArmaldoAnims_2_3:
ax_anim 2, 0, 37, -1, 0, -1, 0,
ax_anim 6, 0, 37, -2, 0, -2, 0,
ax_anim 1, 0, 36, 0, 0, 0, 0,
ax_anim 1, 2, 35, 4, 0, 4, 0,
ax_anim 1, 0, 36, 10, 0, 10, 0,
ax_anim 2, 0, 38, 17, 0, 17, 0,
ax_anim 2, 1, 38, 17, 1, 17, 1,
ax_anim 2, 0, 38, 17, 0, 17, 0,
ax_anim 2, 0, 38, 17, 1, 17, 1,
ax_anim 2, 0, 34, 6, 0, 6, 0,
ax_anim_terminator
sArmaldoAnims_2_4:
ax_anim 2, 0, 42, -1, 1, -1, 1,
ax_anim 6, 0, 42, -2, 2, -2, 2,
ax_anim 1, 0, 41, 0, -1, 0, -1,
ax_anim 1, 2, 40, 6, -5, 6, -5,
ax_anim 1, 0, 41, 12, -11, 12, -11,
ax_anim 2, 0, 43, 16, -15, 16, -15,
ax_anim 2, 1, 43, 17, -14, 17, -14,
ax_anim 2, 0, 43, 16, -15, 16, -15,
ax_anim 2, 0, 43, 17, -14, 17, -14,
ax_anim 2, 0, 39, 7, -6, 7, -6,
ax_anim_terminator
sArmaldoAnims_2_5:
ax_anim 2, 0, 47, 0, 1, 0, 1,
ax_anim 6, 0, 47, 0, 2, 0, 2,
ax_anim 1, 0, 46, 0, 0, 0, 0,
ax_anim 1, 2, 45, 0, -2, 0, -2,
ax_anim 1, 0, 46, 0, -9, 0, -9,
ax_anim 2, 0, 48, 0, -16, 0, -16,
ax_anim 2, 1, 48, 1, -16, 1, -16,
ax_anim 2, 0, 48, 0, -16, 0, -16,
ax_anim 2, 0, 48, 1, -16, 1, -16,
ax_anim 2, 0, 44, 0, -4, 0, -4,
ax_anim_terminator
sArmaldoAnims_2_6:
ax_anim 2, 0, 52, 1, 1, 1, 1,
ax_anim 6, 0, 52, 2, 2, 2, 2,
ax_anim 1, 0, 51, 0, -1, 0, -1,
ax_anim 1, 2, 50, -6, -5, -6, -5,
ax_anim 1, 0, 51, -12, -11, -12, -11,
ax_anim 2, 0, 53, -16, -15, -16, -15,
ax_anim 2, 1, 53, -17, -14, -17, -14,
ax_anim 2, 0, 53, -16, -15, -16, -15,
ax_anim 2, 0, 53, -17, -14, -17, -14,
ax_anim 2, 0, 49, -7, -6, -7, -6,
ax_anim_terminator
sArmaldoAnims_2_7:
ax_anim 2, 0, 57, 1, 0, 1, 0,
ax_anim 6, 0, 57, 2, 0, 2, 0,
ax_anim 1, 0, 56, 0, 0, 0, 0,
ax_anim 1, 2, 55, -4, 0, -4, 0,
ax_anim 1, 0, 56, -10, 0, -10, 0,
ax_anim 2, 0, 58, -17, 0, -17, 0,
ax_anim 2, 1, 58, -17, 1, -17, 1,
ax_anim 2, 0, 58, -17, 0, -17, 0,
ax_anim 2, 0, 58, -17, 1, -17, 1,
ax_anim 2, 0, 54, -6, 0, -6, 0,
ax_anim_terminator
sArmaldoAnims_2_8:
ax_anim 2, 0, 62, 1, -1, 1, -1,
ax_anim 6, 0, 62, 2, -2, 2, -2,
ax_anim 1, 0, 61, 0, 0, 0, 0,
ax_anim 1, 2, 60, -4, 4, -4, 4,
ax_anim 1, 0, 61, -10, 11, -10, 11,
ax_anim 2, 0, 63, -18, 22, -18, 22,
ax_anim 2, 1, 63, -19, 21, -19, 21,
ax_anim 2, 0, 63, -18, 22, -18, 22,
ax_anim 2, 0, 63, -19, 21, -19, 21,
ax_anim 2, 0, 59, -6, 7, -6, 7,
ax_anim_terminator
.align 2
sArmaldoAnims_3_1:
ax_anim 2, 0, 64, 0, -2, 0, -2,
ax_anim 2, 0, 65, 0, -4, 0, -4,
ax_anim 6, 0, 65, 0, -5, 0, -5,
ax_anim 1, 2, 65, 0, 0, 0, 0,
ax_anim 1, 0, 65, 0, 8, 0, 8,
ax_anim 2, 0, 66, 0, 17, 0, 17,
ax_anim 2, 1, 67, 1, 17, 1, 17,
ax_anim 2, 0, 67, 0, 17, 0, 17,
ax_anim 2, 0, 67, 1, 17, 1, 17,
ax_anim 2, 0, 67, 0, 17, 0, 17,
ax_anim 2, 0, 67, 1, 17, 1, 17,
ax_anim 2, 0, 67, 0, 17, 0, 17,
ax_anim 1, 0, 64, 0, 8, 0, 8,
ax_anim 2, 0, 64, 0, 4, 0, 4,
ax_anim_terminator
sArmaldoAnims_3_2:
ax_anim 2, 0, 68, -2, -2, -2, -2,
ax_anim 2, 0, 69, -4, -4, -4, -4,
ax_anim 6, 0, 69, -5, -5, -5, -5,
ax_anim 1, 2, 69, 0, 0, 0, 0,
ax_anim 1, 0, 69, 8, 10, 8, 10,
ax_anim 2, 0, 70, 15, 19, 15, 19,
ax_anim 2, 1, 71, 16, 18, 16, 18,
ax_anim 2, 0, 71, 15, 19, 15, 19,
ax_anim 2, 0, 71, 16, 18, 16, 18,
ax_anim 2, 0, 71, 15, 19, 15, 19,
ax_anim 2, 0, 71, 16, 18, 16, 18,
ax_anim 2, 0, 71, 15, 19, 15, 19,
ax_anim 1, 0, 68, 8, 10, 8, 10,
ax_anim 2, 0, 68, 4, 4, 4, 4,
ax_anim_terminator
sArmaldoAnims_3_3:
ax_anim 2, 0, 72, -2, 0, -2, 0,
ax_anim 2, 0, 73, -4, 0, -4, 0,
ax_anim 6, 0, 73, -5, 0, -5, 0,
ax_anim 1, 2, 73, -2, 0, -2, 0,
ax_anim 1, 0, 73, 5, 0, 5, 0,
ax_anim 2, 0, 74, 11, 0, 11, 0,
ax_anim 2, 1, 75, 11, 1, 11, 1,
ax_anim 2, 0, 75, 11, 0, 11, 0,
ax_anim 2, 0, 75, 11, 1, 11, 1,
ax_anim 2, 0, 75, 11, 0, 11, 0,
ax_anim 2, 0, 75, 11, 1, 11, 1,
ax_anim 2, 0, 75, 11, 0, 11, 0,
ax_anim 1, 0, 72, 6, 0, 6, 0,
ax_anim 2, 0, 72, 2, 0, 2, 0,
ax_anim_terminator
sArmaldoAnims_3_4:
ax_anim 2, 0, 76, -2, 2, -2, 2,
ax_anim 2, 0, 77, -4, 4, -4, 4,
ax_anim 6, 0, 77, -5, 5, -5, 5,
ax_anim 1, 2, 77, 0, 0, 0, 0,
ax_anim 1, 0, 77, 9, -7, 9, -7,
ax_anim 2, 0, 78, 15, -12, 15, -12,
ax_anim 2, 1, 79, 16, -11, 16, -11,
ax_anim 2, 0, 79, 15, -12, 15, -12,
ax_anim 2, 0, 79, 16, -11, 16, -11,
ax_anim 2, 0, 79, 15, -12, 15, -12,
ax_anim 2, 0, 79, 16, -11, 16, -11,
ax_anim 2, 0, 79, 15, -12, 15, -12,
ax_anim 1, 0, 76, 10, -7, 10, -7,
ax_anim 2, 0, 76, 3, -3, 3, -3,
ax_anim_terminator
sArmaldoAnims_3_5:
ax_anim 2, 0, 80, 0, 2, 0, 2,
ax_anim 2, 0, 81, 0, 4, 0, 4,
ax_anim 6, 0, 81, 0, 5, 0, 5,
ax_anim 1, 2, 81, 0, 2, 0, 2,
ax_anim 1, 0, 81, 0, -4, 0, -4,
ax_anim 2, 0, 82, 0, -13, 0, -13,
ax_anim 2, 1, 83, 1, -13, 1, -13,
ax_anim 2, 0, 83, 0, -13, 0, -13,
ax_anim 2, 0, 83, 1, -13, 1, -13,
ax_anim 2, 0, 83, 0, -13, 0, -13,
ax_anim 2, 0, 83, 1, -13, 1, -13,
ax_anim 2, 0, 83, 0, -13, 0, -13,
ax_anim 1, 0, 80, 0, -6, 0, -6,
ax_anim 2, 0, 80, 0, -2, 0, -2,
ax_anim_terminator
sArmaldoAnims_3_6:
ax_anim 2, 0, 84, 2, 2, 2, 2,
ax_anim 2, 0, 85, 4, 4, 4, 4,
ax_anim 6, 0, 85, 5, 5, 5, 5,
ax_anim 1, 2, 85, 0, 0, 0, 0,
ax_anim 1, 0, 85, -9, -7, -9, -7,
ax_anim 2, 0, 86, -15, -12, -15, -12,
ax_anim 2, 1, 87, -16, -11, -16, -11,
ax_anim 2, 0, 87, -15, -12, -15, -12,
ax_anim 2, 0, 87, -16, -11, -16, -11,
ax_anim 2, 0, 87, -15, -12, -15, -12,
ax_anim 2, 0, 87, -16, -11, -16, -11,
ax_anim 2, 0, 87, -15, -12, -15, -12,
ax_anim 1, 0, 84, -10, -7, -10, -7,
ax_anim 2, 0, 84, -3, -3, -3, -3,
ax_anim_terminator
sArmaldoAnims_3_7:
ax_anim 2, 0, 88, 2, 0, 2, 0,
ax_anim 2, 0, 89, 4, 0, 4, 0,
ax_anim 6, 0, 89, 5, 0, 5, 0,
ax_anim 1, 2, 89, 2, 0, 2, 0,
ax_anim 1, 0, 89, -5, 0, -5, 0,
ax_anim 2, 0, 90, -11, 0, -11, 0,
ax_anim 2, 1, 91, -11, 1, -11, 1,
ax_anim 2, 0, 91, -11, 0, -11, 0,
ax_anim 2, 0, 91, -11, 1, -11, 1,
ax_anim 2, 0, 91, -11, 0, -11, 0,
ax_anim 2, 0, 91, -11, 1, -11, 1,
ax_anim 2, 0, 91, -11, 0, -11, 0,
ax_anim 1, 0, 88, -6, 0, -6, 0,
ax_anim 2, 0, 88, -2, 0, -2, 0,
ax_anim_terminator
sArmaldoAnims_3_8:
ax_anim 2, 0, 92, 2, -2, 2, -2,
ax_anim 2, 0, 93, 4, -4, 4, -4,
ax_anim 6, 0, 93, 5, -5, 5, -5,
ax_anim 1, 2, 93, 0, 0, 0, 0,
ax_anim 1, 0, 93, -8, 10, -8, 10,
ax_anim 2, 0, 94, -15, 19, -15, 19,
ax_anim 2, 1, 95, -16, 18, -16, 18,
ax_anim 2, 0, 95, -15, 19, -15, 19,
ax_anim 2, 0, 95, -16, 18, -16, 18,
ax_anim 2, 0, 95, -15, 19, -15, 19,
ax_anim 2, 0, 95, -16, 18, -16, 18,
ax_anim 2, 0, 95, -15, 19, -15, 19,
ax_anim 1, 0, 92, -8, 10, -8, 10,
ax_anim 2, 0, 92, -4, 4, -4, 4,
ax_anim_terminator
.align 2
sArmaldoAnims_4_1:
ax_anim 2, 0, 97, 0, -2, 0, -2,
ax_anim 6, 2, 97, 0, -3, 0, -3,
ax_anim 2, 0, 96, 0, -1, 0, -1,
ax_anim 2, 1, 98, 0, 3, 0, 3,
ax_anim 2, 0, 98, 1, 3, 1, 3,
ax_anim 2, 0, 98, 0, 3, 0, 3,
ax_anim 2, 0, 98, 1, 3, 1, 3,
ax_anim 2, 0, 98, 0, 3, 0, 3,
ax_anim 2, 0, 98, 1, 3, 1, 3,
ax_anim 2, 0, 98, 0, 3, 0, 3,
ax_anim 2, 0, 96, 0, 1, 0, 1,
ax_anim_terminator
sArmaldoAnims_4_2:
ax_anim 2, 0, 100, -2, -2, -2, -2,
ax_anim 6, 2, 100, -3, -3, -3, -3,
ax_anim 2, 0, 99, -1, -1, -1, -1,
ax_anim 2, 1, 101, 2, 2, 2, 2,
ax_anim 2, 0, 101, 3, 1, 3, 1,
ax_anim 2, 0, 101, 2, 2, 2, 2,
ax_anim 2, 0, 101, 3, 1, 3, 1,
ax_anim 2, 0, 101, 2, 2, 2, 2,
ax_anim 2, 0, 101, 3, 1, 3, 1,
ax_anim 2, 0, 101, 2, 2, 2, 2,
ax_anim 2, 0, 99, 1, 1, 1, 1,
ax_anim_terminator
sArmaldoAnims_4_3:
ax_anim 2, 0, 103, -2, 0, -2, 0,
ax_anim 6, 2, 103, -3, 0, -3, 0,
ax_anim 2, 0, 102, -1, 0, -1, 0,
ax_anim 2, 1, 104, 3, 0, 3, 0,
ax_anim 2, 0, 104, 3, 1, 3, 1,
ax_anim 2, 0, 104, 3, 0, 3, 0,
ax_anim 2, 0, 104, 3, 1, 3, 1,
ax_anim 2, 0, 104, 3, 0, 3, 0,
ax_anim 2, 0, 104, 3, 1, 3, 1,
ax_anim 2, 0, 104, 3, 0, 3, 0,
ax_anim 2, 0, 102, 1, 0, 1, 0,
ax_anim_terminator
sArmaldoAnims_4_4:
ax_anim 2, 0, 106, -2, 2, -2, 2,
ax_anim 6, 2, 106, -3, 3, -3, 3,
ax_anim 2, 0, 105, -1, 1, -1, 1,
ax_anim 2, 1, 107, 2, -2, 2, -2,
ax_anim 2, 0, 107, 3, -1, 3, -1,
ax_anim 2, 0, 107, 2, -2, 2, -2,
ax_anim 2, 0, 107, 3, -1, 3, -1,
ax_anim 2, 0, 107, 2, -2, 2, -2,
ax_anim 2, 0, 107, 3, -1, 3, -1,
ax_anim 2, 0, 107, 2, -2, 2, -2,
ax_anim 2, 0, 105, 1, -1, 1, -1,
ax_anim_terminator
sArmaldoAnims_4_5:
ax_anim 2, 0, 109, 0, 2, 0, 2,
ax_anim 6, 2, 109, 0, 3, 0, 3,
ax_anim 2, 0, 108, 0, 1, 0, 1,
ax_anim 2, 1, 110, 0, -3, 0, -3,
ax_anim 2, 0, 110, 1, -3, 1, -3,
ax_anim 2, 0, 110, 0, -3, 0, -3,
ax_anim 2, 0, 110, 1, -3, 1, -3,
ax_anim 2, 0, 110, 0, -3, 0, -3,
ax_anim 2, 0, 110, 1, -3, 1, -3,
ax_anim 2, 0, 110, 0, -3, 0, -3,
ax_anim 2, 0, 108, 0, -1, 0, -1,
ax_anim_terminator
sArmaldoAnims_4_6:
ax_anim 2, 0, 112, 2, 2, 2, 2,
ax_anim 6, 2, 112, 3, 3, 3, 3,
ax_anim 2, 0, 111, 1, 1, 1, 1,
ax_anim 2, 1, 113, -2, -2, -2, -2,
ax_anim 2, 0, 113, -3, -1, -3, -1,
ax_anim 2, 0, 113, -2, -2, -2, -2,
ax_anim 2, 0, 113, -3, -1, -3, -1,
ax_anim 2, 0, 113, -2, -2, -2, -2,
ax_anim 2, 0, 113, -3, -1, -3, -1,
ax_anim 2, 0, 113, -2, -2, -2, -2,
ax_anim 2, 0, 111, -1, -1, -1, -1,
ax_anim_terminator
sArmaldoAnims_4_7:
ax_anim 2, 0, 115, 2, 0, 2, 0,
ax_anim 6, 2, 115, 3, 0, 3, 0,
ax_anim 2, 0, 114, 1, 0, 1, 0,
ax_anim 2, 1, 116, -3, 0, -3, 0,
ax_anim 2, 0, 116, -3, 1, -3, 1,
ax_anim 2, 0, 116, -3, 0, -3, 0,
ax_anim 2, 0, 116, -3, 1, -3, 1,
ax_anim 2, 0, 116, -3, 0, -3, 0,
ax_anim 2, 0, 116, -3, 1, -3, 1,
ax_anim 2, 0, 116, -3, 0, -3, 0,
ax_anim 2, 0, 114, -1, 0, -1, 0,
ax_anim_terminator
sArmaldoAnims_4_8:
ax_anim 2, 0, 118, 2, -2, 2, -2,
ax_anim 6, 2, 118, 3, -3, 3, -3,
ax_anim 2, 0, 117, 1, -1, 1, -1,
ax_anim 2, 1, 119, -2, 2, -2, 2,
ax_anim 2, 0, 119, -3, 1, -3, 1,
ax_anim 2, 0, 119, -2, 2, -2, 2,
ax_anim 2, 0, 119, -3, 1, -3, 1,
ax_anim 2, 0, 119, -2, 2, -2, 2,
ax_anim 2, 0, 119, -3, 1, -3, 1,
ax_anim 2, 0, 119, -2, 2, -2, 2,
ax_anim 2, 0, 117, -1, 1, -1, 1,
ax_anim_terminator
.align 2
sArmaldoAnims_5_1:
ax_anim 2, 0, 120, 0, 0, 0, 0,
ax_anim 2, 0, 121, 0, 0, 0, 0,
ax_anim 2, 0, 122, 0, 0, 0, 0,
ax_anim 2, 0, 123, 0, 0, 0, 0,
ax_anim 2, 0, 124, 0, 0, 0, 0,
ax_anim 2, 0, 125, 0, 0, 0, 0,
ax_anim 2, 0, 126, 0, 0, 0, 0,
ax_anim 2, 0, 127, 0, 0, 0, 0,
ax_anim 2, 2, 120, 0, 0, 0, 0,
ax_anim_terminator
sArmaldoAnims_5_2:
ax_anim 2, 0, 127, 0, 0, 0, 0,
ax_anim 2, 0, 120, 0, 0, 0, 0,
ax_anim 2, 0, 121, 0, 0, 0, 0,
ax_anim 2, 0, 122, 0, 0, 0, 0,
ax_anim 2, 0, 123, 0, 0, 0, 0,
ax_anim 2, 0, 124, 0, 0, 0, 0,
ax_anim 2, 0, 125, 0, 0, 0, 0,
ax_anim 2, 0, 126, 0, 0, 0, 0,
ax_anim 2, 2, 127, 0, 0, 0, 0,
ax_anim_terminator
sArmaldoAnims_5_3:
ax_anim 2, 0, 126, 0, 0, 0, 0,
ax_anim 2, 0, 127, 0, 0, 0, 0,
ax_anim 2, 0, 120, 0, 0, 0, 0,
ax_anim 2, 0, 121, 0, 0, 0, 0,
ax_anim 2, 0, 122, 0, 0, 0, 0,
ax_anim 2, 0, 123, 0, 0, 0, 0,
ax_anim 2, 0, 124, 0, 0, 0, 0,
ax_anim 2, 0, 125, 0, 0, 0, 0,
ax_anim 2, 2, 126, 0, 0, 0, 0,
ax_anim_terminator
sArmaldoAnims_5_4:
ax_anim 2, 0, 125, 0, 0, 0, 0,
ax_anim 2, 0, 126, 0, 0, 0, 0,
ax_anim 2, 0, 127, 0, 0, 0, 0,
ax_anim 2, 0, 120, 0, 0, 0, 0,
ax_anim 2, 0, 121, 0, 0, 0, 0,
ax_anim 2, 0, 122, 0, 0, 0, 0,
ax_anim 2, 0, 123, 0, 0, 0, 0,
ax_anim 2, 0, 124, 0, 0, 0, 0,
ax_anim 2, 2, 125, 0, 0, 0, 0,
ax_anim_terminator
sArmaldoAnims_5_5:
ax_anim 2, 0, 124, 0, 0, 0, 0,
ax_anim 2, 0, 125, 0, 0, 0, 0,
ax_anim 2, 0, 126, 0, 0, 0, 0,
ax_anim 2, 0, 127, 0, 0, 0, 0,
ax_anim 2, 0, 120, 0, 0, 0, 0,
ax_anim 2, 0, 121, 0, 0, 0, 0,
ax_anim 2, 0, 122, 0, 0, 0, 0,
ax_anim 2, 0, 123, 0, 0, 0, 0,
ax_anim 2, 2, 124, 0, 0, 0, 0,
ax_anim_terminator
sArmaldoAnims_5_6:
ax_anim 2, 0, 123, 0, 0, 0, 0,
ax_anim 2, 0, 124, 0, 0, 0, 0,
ax_anim 2, 0, 125, 0, 0, 0, 0,
ax_anim 2, 0, 126, 0, 0, 0, 0,
ax_anim 2, 0, 127, 0, 0, 0, 0,
ax_anim 2, 0, 120, 0, 0, 0, 0,
ax_anim 2, 0, 121, 0, 0, 0, 0,
ax_anim 2, 0, 122, 0, 0, 0, 0,
ax_anim 2, 2, 123, 0, 0, 0, 0,
ax_anim_terminator
sArmaldoAnims_5_7:
ax_anim 2, 0, 122, 0, 0, 0, 0,
ax_anim 2, 0, 123, 0, 0, 0, 0,
ax_anim 2, 0, 124, 0, 0, 0, 0,
ax_anim 2, 0, 125, 0, 0, 0, 0,
ax_anim 2, 0, 126, 0, 0, 0, 0,
ax_anim 2, 0, 127, 0, 0, 0, 0,
ax_anim 2, 0, 120, 0, 0, 0, 0,
ax_anim 2, 0, 121, 0, 0, 0, 0,
ax_anim 2, 2, 122, 0, 0, 0, 0,
ax_anim_terminator
sArmaldoAnims_5_8:
ax_anim 2, 0, 121, 0, 0, 0, 0,
ax_anim 2, 0, 122, 0, 0, 0, 0,
ax_anim 2, 0, 123, 0, 0, 0, 0,
ax_anim 2, 0, 124, 0, 0, 0, 0,
ax_anim 2, 0, 125, 0, 0, 0, 0,
ax_anim 2, 0, 126, 0, 0, 0, 0,
ax_anim 2, 0, 127, 0, 0, 0, 0,
ax_anim 2, 0, 120, 0, 0, 0, 0,
ax_anim 2, 2, 121, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sArmaldoAnims_6_1:
ax_anim 30, 0, 128, 0, 0, 0, 0,
ax_anim 35, 0, 129, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sArmaldoAnims_7_1:
ax_anim 2, 0, 130, 0, -3, 0, -3,
ax_anim 8, 0, 130, 0, -4, 0, -4,
ax_anim_terminator
sArmaldoAnims_7_2:
ax_anim 2, 0, 131, -3, -3, -3, -3,
ax_anim 8, 0, 131, -4, -4, -4, -4,
ax_anim_terminator
sArmaldoAnims_7_3:
ax_anim 2, 0, 132, -3, 0, -3, 0,
ax_anim 8, 0, 132, -4, 0, -4, 0,
ax_anim_terminator
sArmaldoAnims_7_4:
ax_anim 2, 0, 133, -3, 3, -3, 3,
ax_anim 8, 0, 133, -4, 4, -4, 4,
ax_anim_terminator
sArmaldoAnims_7_5:
ax_anim 2, 0, 134, 0, 3, 0, 3,
ax_anim 8, 0, 134, 0, 4, 0, 4,
ax_anim_terminator
sArmaldoAnims_7_6:
ax_anim 2, 0, 135, 3, 3, 3, 3,
ax_anim 8, 0, 135, 4, 4, 4, 4,
ax_anim_terminator
sArmaldoAnims_7_7:
ax_anim 2, 0, 136, 3, 0, 3, 0,
ax_anim 8, 0, 136, 4, 0, 4, 0,
ax_anim_terminator
sArmaldoAnims_7_8:
ax_anim 2, 0, 137, 3, -3, 3, -3,
ax_anim 8, 0, 137, 4, -4, 4, -4,
ax_anim_terminator
.align 2
sArmaldoAnims_8_1:
ax_anim 60, 0, 138, 0, 0, 0, 0,
ax_anim 10, 0, 140, 0, 0, 0, 0,
ax_anim 2, 0, 140, -1, 0, -1, 0,
ax_anim 2, 0, 140, 0, 0, 0, 0,
ax_anim 2, 0, 140, -1, 0, -1, 0,
ax_anim 2, 0, 140, 0, 0, 0, 0,
ax_anim 2, 0, 140, -1, 0, -1, 0,
ax_anim 2, 0, 140, 0, 0, 0, 0,
ax_anim 2, 0, 140, -1, 0, -1, 0,
ax_anim 2, 0, 140, 0, 0, 0, 0,
ax_anim 2, 0, 140, -1, 0, -1, 0,
ax_anim 2, 0, 140, 0, 0, 0, 0,
ax_anim 2, 0, 140, -1, 0, -1, 0,
ax_anim 10, 0, 140, 0, 0, 0, 0,
ax_anim_terminator
sArmaldoAnims_8_2:
ax_anim 60, 0, 141, 0, 0, 0, 0,
ax_anim 10, 0, 143, 0, 0, 0, 0,
ax_anim 2, 0, 143, -1, 0, -1, 0,
ax_anim 2, 0, 143, 0, 0, 0, 0,
ax_anim 2, 0, 143, -1, 0, -1, 0,
ax_anim 2, 0, 143, 0, 0, 0, 0,
ax_anim 2, 0, 143, -1, 0, -1, 0,
ax_anim 2, 0, 143, 0, 0, 0, 0,
ax_anim 2, 0, 143, -1, 0, -1, 0,
ax_anim 2, 0, 143, 0, 0, 0, 0,
ax_anim 2, 0, 143, -1, 0, -1, 0,
ax_anim 2, 0, 143, 0, 0, 0, 0,
ax_anim 2, 0, 143, -1, 0, -1, 0,
ax_anim 10, 0, 143, 0, 0, 0, 0,
ax_anim_terminator
sArmaldoAnims_8_3:
ax_anim 60, 0, 144, 0, 0, 0, 0,
ax_anim 10, 0, 146, 0, 0, 0, 0,
ax_anim 2, 0, 146, -1, 0, -1, 0,
ax_anim 2, 0, 146, 0, 0, 0, 0,
ax_anim 2, 0, 146, -1, 0, -1, 0,
ax_anim 2, 0, 146, 0, 0, 0, 0,
ax_anim 2, 0, 146, -1, 0, -1, 0,
ax_anim 2, 0, 146, 0, 0, 0, 0,
ax_anim 2, 0, 146, -1, 0, -1, 0,
ax_anim 2, 0, 146, 0, 0, 0, 0,
ax_anim 2, 0, 146, -1, 0, -1, 0,
ax_anim 2, 0, 146, 0, 0, 0, 0,
ax_anim 2, 0, 146, -1, 0, -1, 0,
ax_anim 10, 0, 146, 0, 0, 0, 0,
ax_anim_terminator
sArmaldoAnims_8_4:
ax_anim 60, 0, 147, 0, 0, 0, 0,
ax_anim 10, 0, 149, 0, 0, 0, 0,
ax_anim 2, 0, 149, -1, 0, -1, 0,
ax_anim 2, 0, 149, 0, 0, 0, 0,
ax_anim 2, 0, 149, -1, 0, -1, 0,
ax_anim 2, 0, 149, 0, 0, 0, 0,
ax_anim 2, 0, 149, -1, 0, -1, 0,
ax_anim 2, 0, 149, 0, 0, 0, 0,
ax_anim 2, 0, 149, -1, 0, -1, 0,
ax_anim 2, 0, 149, 0, 0, 0, 0,
ax_anim 2, 0, 149, -1, 0, -1, 0,
ax_anim 2, 0, 149, 0, 0, 0, 0,
ax_anim 2, 0, 149, -1, 0, -1, 0,
ax_anim 10, 0, 149, 0, 0, 0, 0,
ax_anim_terminator
sArmaldoAnims_8_5:
ax_anim 60, 0, 150, 0, 0, 0, 0,
ax_anim 10, 0, 152, 0, 0, 0, 0,
ax_anim 2, 0, 152, -1, 0, -1, 0,
ax_anim 2, 0, 152, 0, 0, 0, 0,
ax_anim 2, 0, 152, -1, 0, -1, 0,
ax_anim 2, 0, 152, 0, 0, 0, 0,
ax_anim 2, 0, 152, -1, 0, -1, 0,
ax_anim 2, 0, 152, 0, 0, 0, 0,
ax_anim 2, 0, 152, -1, 0, -1, 0,
ax_anim 2, 0, 152, 0, 0, 0, 0,
ax_anim 2, 0, 152, -1, 0, -1, 0,
ax_anim 2, 0, 152, 0, 0, 0, 0,
ax_anim 2, 0, 152, -1, 0, -1, 0,
ax_anim 10, 0, 152, 0, 0, 0, 0,
ax_anim_terminator
sArmaldoAnims_8_6:
ax_anim 60, 0, 153, 0, 0, 0, 0,
ax_anim 10, 0, 155, 0, 0, 0, 0,
ax_anim 2, 0, 155, -1, 0, -1, 0,
ax_anim 2, 0, 155, 0, 0, 0, 0,
ax_anim 2, 0, 155, -1, 0, -1, 0,
ax_anim 2, 0, 155, 0, 0, 0, 0,
ax_anim 2, 0, 155, -1, 0, -1, 0,
ax_anim 2, 0, 155, 0, 0, 0, 0,
ax_anim 2, 0, 155, -1, 0, -1, 0,
ax_anim 2, 0, 155, 0, 0, 0, 0,
ax_anim 2, 0, 155, -1, 0, -1, 0,
ax_anim 2, 0, 155, 0, 0, 0, 0,
ax_anim 2, 0, 155, -1, 0, -1, 0,
ax_anim 10, 0, 155, 0, 0, 0, 0,
ax_anim_terminator
sArmaldoAnims_8_7:
ax_anim 60, 0, 156, 0, 0, 0, 0,
ax_anim 10, 0, 158, 0, 0, 0, 0,
ax_anim 2, 0, 158, -1, 0, -1, 0,
ax_anim 2, 0, 158, 0, 0, 0, 0,
ax_anim 2, 0, 158, -1, 0, -1, 0,
ax_anim 2, 0, 158, 0, 0, 0, 0,
ax_anim 2, 0, 158, -1, 0, -1, 0,
ax_anim 2, 0, 158, 0, 0, 0, 0,
ax_anim 2, 0, 158, -1, 0, -1, 0,
ax_anim 2, 0, 158, 0, 0, 0, 0,
ax_anim 2, 0, 158, -1, 0, -1, 0,
ax_anim 2, 0, 158, 0, 0, 0, 0,
ax_anim 2, 0, 158, -1, 0, -1, 0,
ax_anim 10, 0, 158, 0, 0, 0, 0,
ax_anim_terminator
sArmaldoAnims_8_8:
ax_anim 60, 0, 159, 0, 0, 0, 0,
ax_anim 10, 0, 161, 0, 0, 0, 0,
ax_anim 2, 0, 161, -1, 0, -1, 0,
ax_anim 2, 0, 161, 0, 0, 0, 0,
ax_anim 2, 0, 161, -1, 0, -1, 0,
ax_anim 2, 0, 161, 0, 0, 0, 0,
ax_anim 2, 0, 161, -1, 0, -1, 0,
ax_anim 2, 0, 161, 0, 0, 0, 0,
ax_anim 2, 0, 161, -1, 0, -1, 0,
ax_anim 2, 0, 161, 0, 0, 0, 0,
ax_anim 2, 0, 161, -1, 0, -1, 0,
ax_anim 2, 0, 161, 0, 0, 0, 0,
ax_anim 2, 0, 161, -1, 0, -1, 0,
ax_anim 10, 0, 161, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sArmaldoAnims_9_1:
ax_anim 2, 0, 162, 0, 0, 0, 0,
ax_anim 1, 0, 163, 9, 4, 9, 4,
ax_anim 2, 0, 164, 13, 11, 13, 11,
ax_anim 2, 0, 165, 11, 17, 11, 17,
ax_anim 3, 0, 166, 0, 20, 0, 20,
ax_anim 2, 3, 167, -10, 17, -10, 17,
ax_anim 2, 0, 168, -13, 11, -13, 11,
ax_anim 1, 0, 169, -9, 4, -9, 4,
ax_anim 1, 0, 162, 0, 0, 0, 0,
ax_anim_terminator
sArmaldoAnims_9_2:
ax_anim 2, 0, 169, 0, 0, 0, 0,
ax_anim 1, 0, 162, 9, 2, 9, 2,
ax_anim 2, 0, 163, 15, 6, 15, 6,
ax_anim 2, 0, 164, 20, 13, 20, 13,
ax_anim 3, 0, 165, 19, 19, 19, 19,
ax_anim 2, 3, 166, 9, 20, 9, 20,
ax_anim 2, 0, 167, 1, 15, 1, 15,
ax_anim 1, 0, 168, -1, 9, -1, 9,
ax_anim 1, 0, 169, 0, 0, 0, 0,
ax_anim_terminator
sArmaldoAnims_9_3:
ax_anim 2, 0, 168, 0, 0, 0, 0,
ax_anim 1, 0, 169, 3, -5, 3, -5,
ax_anim 2, 0, 162, 10, -6, 10, -6,
ax_anim 2, 0, 163, 15, -5, 15, -5,
ax_anim 3, 0, 164, 18, 0, 18, 0,
ax_anim 2, 3, 165, 16, 4, 16, 4,
ax_anim 2, 0, 166, 10, 7, 10, 7,
ax_anim 1, 0, 167, 3, 5, 3, 5,
ax_anim 1, 0, 168, 0, 0, 0, 0,
ax_anim_terminator
sArmaldoAnims_9_4:
ax_anim 2, 0, 167, 0, 0, 0, 0,
ax_anim 1, 0, 168, -1, -8, -1, -8,
ax_anim 2, 0, 169, 4, -16, 4, -16,
ax_anim 2, 0, 162, 11, -20, 11, -20,
ax_anim 3, 0, 163, 19, -21, 19, -21,
ax_anim 2, 3, 164, 22, -14, 22, -14,
ax_anim 2, 0, 165, 19, -8, 19, -8,
ax_anim 1, 0, 166, 12, -2, 12, -2,
ax_anim 1, 0, 167, 0, 0, 0, 0,
ax_anim_terminator
sArmaldoAnims_9_5:
ax_anim 2, 0, 166, 0, 0, 0, 0,
ax_anim 1, 0, 167, -11, -5, -11, -5,
ax_anim 2, 0, 168, -12, -12, -12, -12,
ax_anim 2, 0, 169, -7, -20, -7, -20,
ax_anim 3, 0, 162, 0, -22, 0, -22,
ax_anim 2, 3, 163, 7, -20, 7, -20,
ax_anim 2, 0, 164, 12, -12, 12, -12,
ax_anim 1, 0, 165, 11, -5, 11, -5,
ax_anim 1, 0, 166, 0, 0, 0, 0,
ax_anim_terminator
sArmaldoAnims_9_6:
ax_anim 2, 0, 165, 0, 0, 0, 0,
ax_anim 1, 0, 164, 1, -8, 1, -8,
ax_anim 2, 0, 163, -4, -16, -4, -16,
ax_anim 2, 0, 162, -11, -20, -11, -20,
ax_anim 3, 0, 169, -19, -21, -19, -21,
ax_anim 2, 3, 168, -22, -14, -22, -14,
ax_anim 2, 0, 167, -19, -8, -19, -8,
ax_anim 1, 0, 166, -12, -2, -12, -2,
ax_anim 1, 0, 165, 0, 0, 0, 0,
ax_anim_terminator
sArmaldoAnims_9_7:
ax_anim 2, 0, 164, 0, 0, 0, 0,
ax_anim 1, 0, 163, -3, -5, -3, -5,
ax_anim 2, 0, 162, -10, -6, -10, -6,
ax_anim 2, 0, 169, -15, -5, -15, -5,
ax_anim 3, 0, 168, -18, 0, -18, 0,
ax_anim 2, 3, 167, -16, 4, -16, 4,
ax_anim 2, 0, 166, -10, 7, -10, 7,
ax_anim 1, 0, 165, -3, 5, -3, 5,
ax_anim 1, 0, 164, 0, 0, 0, 0,
ax_anim_terminator
sArmaldoAnims_9_8:
ax_anim 2, 0, 163, 0, 0, 0, 0,
ax_anim 1, 0, 162, -9, 2, -9, 2,
ax_anim 2, 0, 169, -15, 6, -15, 6,
ax_anim 2, 0, 168, -20, 13, -20, 13,
ax_anim 3, 0, 167, -19, 19, -19, 19,
ax_anim 2, 3, 166, -9, 20, -9, 20,
ax_anim 2, 0, 165, -1, 15, -1, 15,
ax_anim 1, 0, 164, 1, 9, 1, 9,
ax_anim 1, 0, 163, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sArmaldoAnims_10_1:
ax_anim 2, 0, 198, 0, 0, 0, 0,
ax_anim 2, 0, 198, 6, 0, 6, 0,
ax_anim 2, 0, 198, -6, 0, -6, 0,
ax_anim 2, 0, 198, 10, 0, 10, 0,
ax_anim 2, 0, 198, -10, 0, -10, 0,
ax_anim 2, 0, 198, 12, 0, 12, 0,
ax_anim 3, 0, 198, -12, 0, -12, 0,
ax_anim 3, 0, 198, 13, 0, 13, 0,
ax_anim 3, 0, 198, -13, 0, -13, 0,
ax_anim 2, 0, 198, 12, 0, 12, 0,
ax_anim 3, 0, 198, -12, 0, -12, 0,
ax_anim 2, 0, 198, 10, 0, 10, 0,
ax_anim 2, 0, 198, -10, 0, -10, 0,
ax_anim 2, 0, 198, 6, 0, 6, 0,
ax_anim 2, 0, 198, -6, 0, -6, 0,
ax_anim 2, 0, 198, 0, 0, 0, 0,
ax_anim_terminator
sArmaldoAnims_10_2:
ax_anim 2, 0, 199, 0, 0, 0, 0,
ax_anim 2, 0, 199, 6, -6, 6, -6,
ax_anim 2, 0, 199, -6, 6, -6, 6,
ax_anim 2, 0, 199, 10, -10, 10, -10,
ax_anim 2, 0, 199, -10, 10, -10, 10,
ax_anim 2, 0, 199, 12, -12, 12, -12,
ax_anim 3, 0, 199, -12, 12, -12, 12,
ax_anim 3, 0, 199, 13, -13, 13, -13,
ax_anim 3, 0, 199, -13, 13, -13, 13,
ax_anim 2, 0, 199, 12, -12, 12, -12,
ax_anim 3, 0, 199, -12, 12, -12, 12,
ax_anim 2, 0, 199, 10, -10, 10, -10,
ax_anim 2, 0, 199, -10, 10, -10, 10,
ax_anim 2, 0, 199, 6, -6, 6, -6,
ax_anim 2, 0, 199, -6, 6, -6, 6,
ax_anim 2, 0, 199, 0, 0, 0, 0,
ax_anim_terminator
sArmaldoAnims_10_3:
ax_anim 2, 0, 200, 0, 0, 0, 0,
ax_anim 2, 0, 200, 0, -6, 0, -6,
ax_anim 2, 0, 200, 0, 6, 0, 6,
ax_anim 2, 0, 200, 0, -10, 0, -10,
ax_anim 2, 0, 200, 0, 10, 0, 10,
ax_anim 2, 0, 200, 0, -12, 0, -12,
ax_anim 3, 0, 200, 0, 12, 0, 12,
ax_anim 3, 0, 200, 0, -13, 0, -13,
ax_anim 3, 0, 200, 0, 13, 0, 13,
ax_anim 2, 0, 200, 0, -12, 0, -12,
ax_anim 3, 0, 200, 0, 12, 0, 12,
ax_anim 2, 0, 200, 0, -10, 0, -10,
ax_anim 2, 0, 200, 0, 10, 0, 10,
ax_anim 2, 0, 200, 0, -6, 0, -6,
ax_anim 2, 0, 200, 0, 6, 0, 6,
ax_anim 2, 0, 200, 0, 0, 0, 0,
ax_anim_terminator
sArmaldoAnims_10_4:
ax_anim 2, 0, 201, 0, 0, 0, 0,
ax_anim 2, 0, 201, -6, -6, -6, -6,
ax_anim 2, 0, 201, 6, 6, 6, 6,
ax_anim 2, 0, 201, -10, -10, -10, -10,
ax_anim 2, 0, 201, 10, 10, 10, 10,
ax_anim 2, 0, 201, -12, -12, -12, -12,
ax_anim 3, 0, 201, 12, 12, 12, 12,
ax_anim 3, 0, 201, -13, -13, -13, -13,
ax_anim 3, 0, 201, 13, 13, 13, 13,
ax_anim 2, 0, 201, -12, -12, -12, -12,
ax_anim 3, 0, 201, 12, 12, 12, 12,
ax_anim 2, 0, 201, -10, -10, -10, -10,
ax_anim 2, 0, 201, 10, 10, 10, 10,
ax_anim 2, 0, 201, -6, -6, -6, -6,
ax_anim 2, 0, 201, 6, 6, 6, 6,
ax_anim 2, 0, 201, 0, 0, 0, 0,
ax_anim_terminator
sArmaldoAnims_10_5:
ax_anim 2, 0, 202, 0, 0, 0, 0,
ax_anim 2, 0, 202, 6, 0, 6, 0,
ax_anim 2, 0, 202, -6, 0, -6, 0,
ax_anim 2, 0, 202, 10, 0, 10, 0,
ax_anim 2, 0, 202, -10, 0, -10, 0,
ax_anim 2, 0, 202, 12, 0, 12, 0,
ax_anim 3, 0, 202, -12, 0, -12, 0,
ax_anim 3, 0, 202, 13, 0, 13, 0,
ax_anim 3, 0, 202, -13, 0, -13, 0,
ax_anim 2, 0, 202, 12, 0, 12, 0,
ax_anim 3, 0, 202, -12, 0, -12, 0,
ax_anim 2, 0, 202, 10, 0, 10, 0,
ax_anim 2, 0, 202, -10, 0, -10, 0,
ax_anim 2, 0, 202, 6, 0, 6, 0,
ax_anim 2, 0, 202, -6, 0, -6, 0,
ax_anim 2, 0, 202, 0, 0, 0, 0,
ax_anim_terminator
sArmaldoAnims_10_6:
ax_anim 2, 0, 203, 0, 0, 0, 0,
ax_anim 2, 0, 203, 6, -6, 6, -6,
ax_anim 2, 0, 203, -6, 6, -6, 6,
ax_anim 2, 0, 203, 10, -10, 10, -10,
ax_anim 2, 0, 203, -10, 10, -10, 10,
ax_anim 2, 0, 203, 12, -12, 12, -12,
ax_anim 3, 0, 203, -12, 12, -12, 12,
ax_anim 3, 0, 203, 13, -13, 13, -13,
ax_anim 3, 0, 203, -13, 13, -13, 13,
ax_anim 2, 0, 203, 12, -12, 12, -12,
ax_anim 3, 0, 203, -12, 12, -12, 12,
ax_anim 2, 0, 203, 10, -10, 10, -10,
ax_anim 2, 0, 203, -10, 10, -10, 10,
ax_anim 2, 0, 203, 6, -6, 6, -6,
ax_anim 2, 0, 203, -6, 6, -6, 6,
ax_anim 2, 0, 203, 0, 0, 0, 0,
ax_anim_terminator
sArmaldoAnims_10_7:
ax_anim 2, 0, 204, 0, 0, 0, 0,
ax_anim 2, 0, 204, 0, -6, 0, -6,
ax_anim 2, 0, 204, 0, 6, 0, 6,
ax_anim 2, 0, 204, 0, -10, 0, -10,
ax_anim 2, 0, 204, 0, 10, 0, 10,
ax_anim 2, 0, 204, 0, -12, 0, -12,
ax_anim 3, 0, 204, 0, 12, 0, 12,
ax_anim 3, 0, 204, 0, -13, 0, -13,
ax_anim 3, 0, 204, 0, 13, 0, 13,
ax_anim 2, 0, 204, 0, -12, 0, -12,
ax_anim 3, 0, 204, 0, 12, 0, 12,
ax_anim 2, 0, 204, 0, -10, 0, -10,
ax_anim 2, 0, 204, 0, 10, 0, 10,
ax_anim 2, 0, 204, 0, -6, 0, -6,
ax_anim 2, 0, 204, 0, 6, 0, 6,
ax_anim 2, 0, 204, 0, 0, 0, 0,
ax_anim_terminator
sArmaldoAnims_10_8:
ax_anim 2, 0, 205, 0, 0, 0, 0,
ax_anim 2, 0, 205, -6, -6, -6, -6,
ax_anim 2, 0, 205, 6, 6, 6, 6,
ax_anim 2, 0, 205, -10, -10, -10, -10,
ax_anim 2, 0, 205, 10, 10, 10, 10,
ax_anim 2, 0, 205, -12, -12, -12, -12,
ax_anim 3, 0, 205, 12, 12, 12, 12,
ax_anim 3, 0, 205, -13, -13, -13, -13,
ax_anim 3, 0, 205, 13, 13, 13, 13,
ax_anim 2, 0, 205, -12, -12, -12, -12,
ax_anim 3, 0, 205, 12, 12, 12, 12,
ax_anim 2, 0, 205, -10, -10, -10, -10,
ax_anim 2, 0, 205, 10, 10, 10, 10,
ax_anim 2, 0, 205, -6, -6, -6, -6,
ax_anim 2, 0, 205, 6, 6, 6, 6,
ax_anim 2, 0, 205, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sArmaldoAnims_11_1:
ax_anim 2, 0, 206, 0, 0, 0, 0,
ax_anim 1, 0, 207, 0, -10, 0, 0,
ax_anim 2, 0, 207, 0, -16, 0, 0,
ax_anim 3, 0, 207, 0, -20, 0, 0,
ax_anim 4, 0, 207, 0, -21, 0, 0,
ax_anim 4, 0, 206, 0, -22, 0, 0,
ax_anim 3, 0, 208, 0, -21, 0, 0,
ax_anim 2, 0, 208, 0, -18, 0, 0,
ax_anim 1, 0, 208, 0, -12, 0, 0,
ax_anim 2, 2, 208, 0, 0, 0, 0,
ax_anim_terminator
sArmaldoAnims_11_2:
ax_anim 2, 0, 209, 0, 0, 0, 0,
ax_anim 1, 0, 210, 0, -10, 0, 0,
ax_anim 2, 0, 210, 0, -16, 0, 0,
ax_anim 3, 0, 210, 0, -20, 0, 0,
ax_anim 4, 0, 210, 0, -21, 0, 0,
ax_anim 4, 0, 209, 0, -22, 0, 0,
ax_anim 3, 0, 211, 0, -24, 0, 0,
ax_anim 2, 0, 211, 0, -19, 0, 0,
ax_anim 1, 0, 211, 0, -12, 0, 0,
ax_anim 2, 2, 211, 0, 0, 0, 0,
ax_anim_terminator
sArmaldoAnims_11_3:
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 1, 0, 213, 0, -10, 0, 0,
ax_anim 2, 0, 213, 0, -16, 0, 0,
ax_anim 3, 0, 213, 0, -20, 0, 0,
ax_anim 4, 0, 213, 0, -21, 0, 0,
ax_anim 4, 0, 212, 0, -22, 0, 0,
ax_anim 3, 0, 214, 0, -22, 0, 0,
ax_anim 2, 0, 214, 0, -18, 0, 0,
ax_anim 1, 0, 214, 0, -12, 0, 0,
ax_anim 2, 2, 214, 0, 0, 0, 0,
ax_anim_terminator
sArmaldoAnims_11_4:
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 1, 0, 216, 0, -10, 0, 0,
ax_anim 2, 0, 216, 0, -16, 0, 0,
ax_anim 3, 0, 216, 0, -20, 0, 0,
ax_anim 4, 0, 216, 0, -21, 0, 0,
ax_anim 4, 0, 215, 0, -22, 0, 0,
ax_anim 3, 0, 217, 0, -20, 0, 0,
ax_anim 2, 0, 217, 0, -17, 0, 0,
ax_anim 1, 0, 217, 0, -11, 0, 0,
ax_anim 2, 2, 217, 0, 0, 0, 0,
ax_anim_terminator
sArmaldoAnims_11_5:
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 1, 0, 219, 0, -10, 0, 0,
ax_anim 2, 0, 219, 0, -16, 0, 0,
ax_anim 3, 0, 219, 0, -20, 0, 0,
ax_anim 4, 0, 219, 0, -21, 0, 0,
ax_anim 4, 0, 218, 0, -23, 0, 0,
ax_anim 3, 0, 220, 0, -21, 0, 0,
ax_anim 2, 0, 220, 0, -17, 0, 0,
ax_anim 1, 0, 220, 0, -12, 0, 0,
ax_anim 2, 2, 220, 0, 0, 0, 0,
ax_anim_terminator
sArmaldoAnims_11_6:
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 1, 0, 222, 0, -10, 0, 0,
ax_anim 2, 0, 222, 0, -16, 0, 0,
ax_anim 3, 0, 222, 0, -20, 0, 0,
ax_anim 4, 0, 222, 0, -21, 0, 0,
ax_anim 4, 0, 221, 0, -22, 0, 0,
ax_anim 3, 0, 223, 0, -20, 0, 0,
ax_anim 2, 0, 223, 0, -17, 0, 0,
ax_anim 1, 0, 223, 0, -11, 0, 0,
ax_anim 2, 2, 223, 0, 0, 0, 0,
ax_anim_terminator
sArmaldoAnims_11_7:
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 1, 0, 225, 0, -10, 0, 0,
ax_anim 2, 0, 225, 0, -16, 0, 0,
ax_anim 3, 0, 225, 0, -20, 0, 0,
ax_anim 4, 0, 225, 0, -21, 0, 0,
ax_anim 4, 0, 224, 0, -22, 0, 0,
ax_anim 3, 0, 226, 0, -22, 0, 0,
ax_anim 2, 0, 226, 0, -18, 0, 0,
ax_anim 1, 0, 226, 0, -12, 0, 0,
ax_anim 2, 2, 226, 0, 0, 0, 0,
ax_anim_terminator
sArmaldoAnims_11_8:
ax_anim 2, 0, 227, 0, 0, 0, 0,
ax_anim 1, 0, 228, 0, -10, 0, 0,
ax_anim 2, 0, 228, 0, -16, 0, 0,
ax_anim 3, 0, 228, 0, -20, 0, 0,
ax_anim 4, 0, 228, 0, -21, 0, 0,
ax_anim 4, 0, 227, 0, -22, 0, 0,
ax_anim 3, 0, 229, 0, -24, 0, 0,
ax_anim 2, 0, 229, 0, -19, 0, 0,
ax_anim 1, 0, 229, 0, -12, 0, 0,
ax_anim 2, 2, 229, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sArmaldoAnims_12_1:
ax_anim 2, 0, 230, 1, 0, 1, 0,
ax_anim 2, 0, 230, 0, 0, 0, 0,
ax_anim 2, 0, 230, 1, 0, 1, 0,
ax_anim 2, 0, 230, 0, 0, 0, 0,
ax_anim 2, 0, 230, 1, 0, 1, 0,
ax_anim 2, 2, 230, 0, 0, 0, 0,
ax_anim 2, 0, 230, 1, 0, 1, 0,
ax_anim 2, 0, 230, 0, 0, 0, 0,
ax_anim 2, 0, 230, 1, 0, 1, 0,
ax_anim 2, 1, 230, 0, 0, 0, 0,
ax_anim_terminator
sArmaldoAnims_12_2:
ax_anim 2, 0, 237, 1, -1, 1, -1,
ax_anim 2, 0, 237, 0, 0, 0, 0,
ax_anim 2, 0, 237, 1, -1, 1, -1,
ax_anim 2, 0, 237, 0, 0, 0, 0,
ax_anim 2, 0, 237, 1, -1, 1, -1,
ax_anim 2, 2, 237, 0, 0, 0, 0,
ax_anim 2, 0, 237, 1, -1, 1, -1,
ax_anim 2, 0, 237, 0, 0, 0, 0,
ax_anim 2, 0, 237, 1, -1, 1, -1,
ax_anim 2, 1, 237, 0, 0, 0, 0,
ax_anim_terminator
sArmaldoAnims_12_3:
ax_anim 2, 0, 236, 0, -1, 0, -1,
ax_anim 2, 0, 236, 0, 0, 0, 0,
ax_anim 2, 0, 236, 0, -1, 0, -1,
ax_anim 2, 0, 236, 0, 0, 0, 0,
ax_anim 2, 0, 236, 0, -1, 0, -1,
ax_anim 2, 2, 236, 0, 0, 0, 0,
ax_anim 2, 0, 236, 0, -1, 0, -1,
ax_anim 2, 0, 236, 0, 0, 0, 0,
ax_anim 2, 0, 236, 0, -1, 0, -1,
ax_anim 2, 1, 236, 0, 0, 0, 0,
ax_anim_terminator
sArmaldoAnims_12_4:
ax_anim 2, 0, 235, -1, -1, -1, -1,
ax_anim 2, 0, 235, 0, 0, 0, 0,
ax_anim 2, 0, 235, -1, -1, -1, -1,
ax_anim 2, 0, 235, 0, 0, 0, 0,
ax_anim 2, 0, 235, -1, -1, -1, -1,
ax_anim 2, 2, 235, 0, 0, 0, 0,
ax_anim 2, 0, 235, -1, -1, -1, -1,
ax_anim 2, 0, 235, 0, 0, 0, 0,
ax_anim 2, 0, 235, -1, -1, -1, -1,
ax_anim 2, 1, 235, 0, 0, 0, 0,
ax_anim_terminator
sArmaldoAnims_12_5:
ax_anim 2, 0, 234, 1, 0, 1, 0,
ax_anim 2, 0, 234, 0, 0, 0, 0,
ax_anim 2, 0, 234, 1, 0, 1, 0,
ax_anim 2, 0, 234, 0, 0, 0, 0,
ax_anim 2, 0, 234, 1, 0, 1, 0,
ax_anim 2, 2, 234, 0, 0, 0, 0,
ax_anim 2, 0, 234, 1, 0, 1, 0,
ax_anim 2, 0, 234, 0, 0, 0, 0,
ax_anim 2, 0, 234, 1, 0, 1, 0,
ax_anim 2, 1, 234, 0, 0, 0, 0,
ax_anim_terminator
sArmaldoAnims_12_6:
ax_anim 2, 0, 233, 1, -1, 1, -1,
ax_anim 2, 0, 233, 0, 0, 0, 0,
ax_anim 2, 0, 233, 1, -1, 1, -1,
ax_anim 2, 0, 233, 0, 0, 0, 0,
ax_anim 2, 0, 233, 1, -1, 1, -1,
ax_anim 2, 2, 233, 0, 0, 0, 0,
ax_anim 2, 0, 233, 1, -1, 1, -1,
ax_anim 2, 0, 233, 0, 0, 0, 0,
ax_anim 2, 0, 233, 1, -1, 1, -1,
ax_anim 2, 1, 233, 0, 0, 0, 0,
ax_anim_terminator
sArmaldoAnims_12_7:
ax_anim 2, 0, 232, 0, -1, 0, -1,
ax_anim 2, 0, 232, 0, 0, 0, 0,
ax_anim 2, 0, 232, 0, -1, 0, -1,
ax_anim 2, 0, 232, 0, 0, 0, 0,
ax_anim 2, 0, 232, 0, -1, 0, -1,
ax_anim 2, 2, 232, 0, 0, 0, 0,
ax_anim 2, 0, 232, 0, -1, 0, -1,
ax_anim 2, 0, 232, 0, 0, 0, 0,
ax_anim 2, 0, 232, 0, -1, 0, -1,
ax_anim 2, 1, 232, 0, 0, 0, 0,
ax_anim_terminator
sArmaldoAnims_12_8:
ax_anim 2, 0, 231, -1, -1, -1, -1,
ax_anim 2, 0, 231, 0, 0, 0, 0,
ax_anim 2, 0, 231, -1, -1, -1, -1,
ax_anim 2, 0, 231, 0, 0, 0, 0,
ax_anim 2, 0, 231, -1, -1, -1, -1,
ax_anim 2, 2, 231, 0, 0, 0, 0,
ax_anim 2, 0, 231, -1, -1, -1, -1,
ax_anim 2, 0, 231, 0, 0, 0, 0,
ax_anim 2, 0, 231, -1, -1, -1, -1,
ax_anim 2, 1, 231, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sArmaldoAnims_13_1:
ax_anim 2, 0, 238, 0, 0, 0, 0,
ax_anim 2, 0, 239, 0, 0, 0, 0,
ax_anim 2, 0, 240, 0, 0, 0, 0,
ax_anim 2, 0, 241, 0, 0, 0, 0,
ax_anim 2, 0, 242, 0, 0, 0, 0,
ax_anim 2, 0, 243, 0, 0, 0, 0,
ax_anim 2, 0, 244, 0, 0, 0, 0,
ax_anim 2, 0, 245, 0, 0, 0, 0,
ax_anim 2, 2, 238, 0, 0, 0, 0,
ax_anim_terminator
sArmaldoAnims_13_2:
ax_anim 2, 0, 245, 0, 0, 0, 0,
ax_anim 2, 0, 238, 0, 0, 0, 0,
ax_anim 2, 0, 239, 0, 0, 0, 0,
ax_anim 2, 0, 240, 0, 0, 0, 0,
ax_anim 2, 0, 241, 0, 0, 0, 0,
ax_anim 2, 0, 242, 0, 0, 0, 0,
ax_anim 2, 0, 243, 0, 0, 0, 0,
ax_anim 2, 0, 244, 0, 0, 0, 0,
ax_anim 2, 2, 245, 0, 0, 0, 0,
ax_anim_terminator
sArmaldoAnims_13_3:
ax_anim 2, 0, 244, 0, 0, 0, 0,
ax_anim 2, 0, 245, 0, 0, 0, 0,
ax_anim 2, 0, 238, 0, 0, 0, 0,
ax_anim 2, 0, 239, 0, 0, 0, 0,
ax_anim 2, 0, 240, 0, 0, 0, 0,
ax_anim 2, 0, 241, 0, 0, 0, 0,
ax_anim 2, 0, 242, 0, 0, 0, 0,
ax_anim 2, 0, 243, 0, 0, 0, 0,
ax_anim 2, 2, 244, 0, 0, 0, 0,
ax_anim_terminator
sArmaldoAnims_13_4:
ax_anim 2, 0, 243, 0, 0, 0, 0,
ax_anim 2, 0, 244, 0, 0, 0, 0,
ax_anim 2, 0, 245, 0, 0, 0, 0,
ax_anim 2, 0, 238, 0, 0, 0, 0,
ax_anim 2, 0, 239, 0, 0, 0, 0,
ax_anim 2, 0, 240, 0, 0, 0, 0,
ax_anim 2, 0, 241, 0, 0, 0, 0,
ax_anim 2, 0, 242, 0, 0, 0, 0,
ax_anim 2, 2, 243, 0, 0, 0, 0,
ax_anim_terminator
sArmaldoAnims_13_5:
ax_anim 2, 0, 242, 0, 0, 0, 0,
ax_anim 2, 0, 243, 0, 0, 0, 0,
ax_anim 2, 0, 244, 0, 0, 0, 0,
ax_anim 2, 0, 245, 0, 0, 0, 0,
ax_anim 2, 0, 238, 0, 0, 0, 0,
ax_anim 2, 0, 239, 0, 0, 0, 0,
ax_anim 2, 0, 240, 0, 0, 0, 0,
ax_anim 2, 0, 241, 0, 0, 0, 0,
ax_anim 2, 2, 242, 0, 0, 0, 0,
ax_anim_terminator
sArmaldoAnims_13_6:
ax_anim 2, 0, 241, 0, 0, 0, 0,
ax_anim 2, 0, 242, 0, 0, 0, 0,
ax_anim 2, 0, 243, 0, 0, 0, 0,
ax_anim 2, 0, 244, 0, 0, 0, 0,
ax_anim 2, 0, 245, 0, 0, 0, 0,
ax_anim 2, 0, 238, 0, 0, 0, 0,
ax_anim 2, 0, 239, 0, 0, 0, 0,
ax_anim 2, 0, 240, 0, 0, 0, 0,
ax_anim 2, 2, 241, 0, 0, 0, 0,
ax_anim_terminator
sArmaldoAnims_13_7:
ax_anim 2, 0, 240, 0, 0, 0, 0,
ax_anim 2, 0, 241, 0, 0, 0, 0,
ax_anim 2, 0, 242, 0, 0, 0, 0,
ax_anim 2, 0, 243, 0, 0, 0, 0,
ax_anim 2, 0, 244, 0, 0, 0, 0,
ax_anim 2, 0, 245, 0, 0, 0, 0,
ax_anim 2, 0, 238, 0, 0, 0, 0,
ax_anim 2, 0, 239, 0, 0, 0, 0,
ax_anim 2, 2, 240, 0, 0, 0, 0,
ax_anim_terminator
sArmaldoAnims_13_8:
ax_anim 2, 0, 239, 0, 0, 0, 0,
ax_anim 2, 0, 240, 0, 0, 0, 0,
ax_anim 2, 0, 241, 0, 0, 0, 0,
ax_anim 2, 0, 242, 0, 0, 0, 0,
ax_anim 2, 0, 243, 0, 0, 0, 0,
ax_anim 2, 0, 244, 0, 0, 0, 0,
ax_anim 2, 0, 245, 0, 0, 0, 0,
ax_anim 2, 0, 238, 0, 0, 0, 0,
ax_anim 2, 2, 239, 0, 0, 0, 0,
ax_anim_terminator
sArmaldoGfx1:
.incbin "baserom.gba", 0x14333C0, 0x200
sArmaldoSprites1:
ax_sprite sArmaldoGfx1, 0x200
ax_sprite_terminator
sArmaldoGfx2:
.incbin "baserom.gba", 0x14335D0, 0x200
sArmaldoSprites2:
ax_sprite sArmaldoGfx2, 0x200
ax_sprite_terminator
sArmaldoGfx3:
.incbin "baserom.gba", 0x14337E0, 0x200
sArmaldoSprites3:
ax_sprite sArmaldoGfx3, 0x200
ax_sprite_terminator
sArmaldoGfx4:
.incbin "baserom.gba", 0x14339F0, 0x200
sArmaldoSprites4:
ax_sprite sArmaldoGfx4, 0x200
ax_sprite_terminator
sArmaldoGfx5:
.incbin "baserom.gba", 0x1433C00, 0x200
sArmaldoSprites5:
ax_sprite sArmaldoGfx5, 0x200
ax_sprite_terminator
sArmaldoGfx6:
.incbin "baserom.gba", 0x1433E10, 0x200
sArmaldoSprites6:
ax_sprite sArmaldoGfx6, 0x200
ax_sprite_terminator
sArmaldoGfx7:
.incbin "baserom.gba", 0x1434020, 0x200
sArmaldoSprites7:
ax_sprite sArmaldoGfx7, 0x200
ax_sprite_terminator
sArmaldoGfx8:
.incbin "baserom.gba", 0x1434230, 0x100
sArmaldoSprites8:
ax_sprite sArmaldoGfx8, 0x100
ax_sprite_terminator
sArmaldoGfx9:
.incbin "baserom.gba", 0x1434340, 0x80
sArmaldoSprites9:
ax_sprite sArmaldoGfx9, 0x80
ax_sprite_terminator
sArmaldoGfx10:
.incbin "baserom.gba", 0x14343D0, 0x40
sArmaldoSprites10:
ax_sprite sArmaldoGfx10, 0x40
ax_sprite_terminator
sArmaldoGfx11:
.incbin "baserom.gba", 0x1434420, 0x40
sArmaldoSprites11:
ax_sprite sArmaldoGfx11, 0x40
ax_sprite_terminator
sArmaldoGfx12:
.incbin "baserom.gba", 0x1434470, 0x100
sArmaldoSprites12:
ax_sprite sArmaldoGfx12, 0x100
ax_sprite_terminator
sArmaldoGfx13:
.incbin "baserom.gba", 0x1434580, 0x80
sArmaldoSprites13:
ax_sprite sArmaldoGfx13, 0x80
ax_sprite_terminator
sArmaldoGfx14:
.incbin "baserom.gba", 0x1434610, 0x40
sArmaldoSprites14:
ax_sprite sArmaldoGfx14, 0x40
ax_sprite_terminator
sArmaldoGfx15:
.incbin "baserom.gba", 0x1434660, 0x20
sArmaldoSprites15:
ax_sprite sArmaldoGfx15, 0x20
ax_sprite_terminator
sArmaldoGfx16:
.incbin "baserom.gba", 0x1434690, 0x200
sArmaldoSprites16:
ax_sprite sArmaldoGfx16, 0x200
ax_sprite_terminator
sArmaldoGfx17:
.incbin "baserom.gba", 0x14348A0, 0x200
sArmaldoSprites17:
ax_sprite sArmaldoGfx17, 0x200
ax_sprite_terminator
sArmaldoGfx18:
.incbin "baserom.gba", 0x1434AB0, 0x200
sArmaldoSprites18:
ax_sprite sArmaldoGfx18, 0x200
ax_sprite_terminator
sArmaldoGfx19:
.incbin "baserom.gba", 0x1434CC0, 0x200
sArmaldoSprites19:
ax_sprite sArmaldoGfx19, 0x200
ax_sprite_terminator
sArmaldoGfx20:
.incbin "baserom.gba", 0x1434ED0, 0x200
sArmaldoSprites20:
ax_sprite sArmaldoGfx20, 0x200
ax_sprite_terminator
sArmaldoGfx21:
.incbin "baserom.gba", 0x14350E0, 0x200
sArmaldoSprites21:
ax_sprite sArmaldoGfx21, 0x200
ax_sprite_terminator
sArmaldoGfx22:
.incbin "baserom.gba", 0x14352F0, 0x100
sArmaldoSprites22:
ax_sprite sArmaldoGfx22, 0x100
ax_sprite_terminator
sArmaldoGfx23:
.incbin "baserom.gba", 0x1435400, 0x80
sArmaldoSprites23:
ax_sprite sArmaldoGfx23, 0x80
ax_sprite_terminator
sArmaldoGfx24:
.incbin "baserom.gba", 0x1435490, 0x20
sArmaldoSprites24:
ax_sprite sArmaldoGfx24, 0x20
ax_sprite_terminator
sArmaldoGfx25:
.incbin "baserom.gba", 0x14354C0, 0x40
sArmaldoSprites25:
ax_sprite sArmaldoGfx25, 0x40
ax_sprite_terminator
sArmaldoGfx26:
.incbin "baserom.gba", 0x1435510, 0x20
sArmaldoSprites26:
ax_sprite sArmaldoGfx26, 0x20
ax_sprite_terminator
sArmaldoGfx27:
.incbin "baserom.gba", 0x1435540, 0x40
sArmaldoGfx27_1:
.incbin "baserom.gba", 0x1435580, 0x100
sArmaldoGfx27_2:
.incbin "baserom.gba", 0x1435680, 0x60
sArmaldoSprites27:
ax_sprite 0, 0x20
ax_sprite sArmaldoGfx27, 0x40
ax_sprite 0, 0x20
ax_sprite sArmaldoGfx27_1, 0x100
ax_sprite 0, 0x20
ax_sprite sArmaldoGfx27_2, 0x60
ax_sprite_terminator
sArmaldoGfx28:
.incbin "baserom.gba", 0x1435718, 0x60
sArmaldoGfx28_1:
.incbin "baserom.gba", 0x1435778, 0x80
sArmaldoGfx28_2:
.incbin "baserom.gba", 0x14357F8, 0x60
sArmaldoGfx28_3:
.incbin "baserom.gba", 0x1435858, 0x40
sArmaldoSprites28:
ax_sprite sArmaldoGfx28, 0x60
ax_sprite 0, 0x20
ax_sprite sArmaldoGfx28_1, 0x80
ax_sprite 0, 0x20
ax_sprite sArmaldoGfx28_2, 0x60
ax_sprite 0, 0x20
ax_sprite sArmaldoGfx28_3, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sArmaldoGfx29:
.incbin "baserom.gba", 0x14358E0, 0x20
sArmaldoGfx29_1:
.incbin "baserom.gba", 0x1435900, 0x140
sArmaldoGfx29_2:
.incbin "baserom.gba", 0x1435A40, 0x60
sArmaldoSprites29:
ax_sprite sArmaldoGfx29, 0x20
ax_sprite 0, 0x20
ax_sprite sArmaldoGfx29_1, 0x140
ax_sprite 0, 0x20
ax_sprite sArmaldoGfx29_2, 0x60
ax_sprite_terminator
sArmaldoGfx30:
.incbin "baserom.gba", 0x1435AD0, 0x40
sArmaldoSprites30:
ax_sprite sArmaldoGfx30, 0x40
ax_sprite_terminator
sArmaldoGfx31:
.incbin "baserom.gba", 0x1435B20, 0x20
sArmaldoSprites31:
ax_sprite sArmaldoGfx31, 0x20
ax_sprite_terminator
sArmaldoGfx32:
.incbin "baserom.gba", 0x1435B50, 0x60
sArmaldoSprites32:
ax_sprite 0, 0x20
ax_sprite sArmaldoGfx32, 0x60
ax_sprite_terminator
sArmaldoGfx33:
.incbin "baserom.gba", 0x1435BC8, 0x60
sArmaldoGfx33_1:
.incbin "baserom.gba", 0x1435C28, 0x60
sArmaldoSprites33:
ax_sprite sArmaldoGfx33, 0x60
ax_sprite 0, 0x20
ax_sprite sArmaldoGfx33_1, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sArmaldoGfx34:
.incbin "baserom.gba", 0x1435CB0, 0x20
sArmaldoSprites34:
ax_sprite sArmaldoGfx34, 0x20
ax_sprite_terminator
sArmaldoGfx35:
.incbin "baserom.gba", 0x1435CE0, 0x40
sArmaldoSprites35:
ax_sprite sArmaldoGfx35, 0x40
ax_sprite_terminator
sArmaldoGfx36:
.incbin "baserom.gba", 0x1435D30, 0x40
sArmaldoSprites36:
ax_sprite sArmaldoGfx36, 0x40
ax_sprite_terminator
sArmaldoGfx37:
.incbin "baserom.gba", 0x1435D80, 0x20
sArmaldoSprites37:
ax_sprite sArmaldoGfx37, 0x20
ax_sprite_terminator
sArmaldoGfx38:
.incbin "baserom.gba", 0x1435DB0, 0x60
sArmaldoGfx38_1:
.incbin "baserom.gba", 0x1435E10, 0x80
sArmaldoSprites38:
ax_sprite sArmaldoGfx38, 0x60
ax_sprite 0, 0x20
ax_sprite sArmaldoGfx38_1, 0x80
ax_sprite_terminator
sArmaldoGfx39:
.incbin "baserom.gba", 0x1435EB0, 0x40
sArmaldoSprites39:
ax_sprite sArmaldoGfx39, 0x40
ax_sprite_terminator
sArmaldoGfx40:
.incbin "baserom.gba", 0x1435F00, 0x160
sArmaldoGfx40_1:
.incbin "baserom.gba", 0x1436060, 0x60
sArmaldoSprites40:
ax_sprite 0, 0x20
ax_sprite sArmaldoGfx40, 0x160
ax_sprite 0, 0x20
ax_sprite sArmaldoGfx40_1, 0x60
ax_sprite_terminator
sArmaldoGfx41:
.incbin "baserom.gba", 0x14360E8, 0x60
sArmaldoGfx41_1:
.incbin "baserom.gba", 0x1436148, 0x100
sArmaldoGfx41_2:
.incbin "baserom.gba", 0x1436248, 0x60
sArmaldoSprites41:
ax_sprite sArmaldoGfx41, 0x60
ax_sprite 0, 0x20
ax_sprite sArmaldoGfx41_1, 0x100
ax_sprite 0, 0x20
ax_sprite sArmaldoGfx41_2, 0x60
ax_sprite_terminator
sArmaldoGfx42:
.incbin "baserom.gba", 0x14362D8, 0x100
sArmaldoSprites42:
ax_sprite sArmaldoGfx42, 0x100
ax_sprite_terminator
sArmaldoGfx43:
.incbin "baserom.gba", 0x14363E8, 0x80
sArmaldoSprites43:
ax_sprite sArmaldoGfx43, 0x80
ax_sprite_terminator
sArmaldoGfx44:
.incbin "baserom.gba", 0x1436478, 0x40
sArmaldoSprites44:
ax_sprite sArmaldoGfx44, 0x40
ax_sprite_terminator
sArmaldoGfx45:
.incbin "baserom.gba", 0x14364C8, 0x20
sArmaldoSprites45:
ax_sprite sArmaldoGfx45, 0x20
ax_sprite_terminator
sArmaldoGfx46:
.incbin "baserom.gba", 0x14364F8, 0x20
sArmaldoSprites46:
ax_sprite sArmaldoGfx46, 0x20
ax_sprite_terminator
sArmaldoGfx47:
.incbin "baserom.gba", 0x1436528, 0x200
sArmaldoSprites47:
ax_sprite sArmaldoGfx47, 0x200
ax_sprite_terminator
sArmaldoGfx48:
.incbin "baserom.gba", 0x1436738, 0x20
sArmaldoGfx48_1:
.incbin "baserom.gba", 0x1436758, 0x40
sArmaldoGfx48_2:
.incbin "baserom.gba", 0x1436798, 0x120
sArmaldoSprites48:
ax_sprite sArmaldoGfx48, 0x20
ax_sprite 0, 0x40
ax_sprite sArmaldoGfx48_1, 0x40
ax_sprite 0, 0x40
ax_sprite sArmaldoGfx48_2, 0x120
ax_sprite_terminator
sArmaldoGfx49:
.incbin "baserom.gba", 0x14368E8, 0x40
sArmaldoGfx49_1:
.incbin "baserom.gba", 0x1436928, 0x180
sArmaldoSprites49:
ax_sprite 0, 0x20
ax_sprite sArmaldoGfx49, 0x40
ax_sprite 0, 0x20
ax_sprite sArmaldoGfx49_1, 0x180
ax_sprite_terminator
sArmaldoGfx50:
.incbin "baserom.gba", 0x1436AD0, 0x40
sArmaldoGfx50_1:
.incbin "baserom.gba", 0x1436B10, 0x60
sArmaldoGfx50_2:
.incbin "baserom.gba", 0x1436B70, 0xA0
sArmaldoGfx50_3:
.incbin "baserom.gba", 0x1436C10, 0x40
sArmaldoSprites50:
ax_sprite sArmaldoGfx50, 0x40
ax_sprite 0, 0x20
ax_sprite sArmaldoGfx50_1, 0x60
ax_sprite 0, 0x20
ax_sprite sArmaldoGfx50_2, 0xa0
ax_sprite 0, 0x20
ax_sprite sArmaldoGfx50_3, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sArmaldoGfx51:
.incbin "baserom.gba", 0x1436C98, 0x20
sArmaldoGfx51_1:
.incbin "baserom.gba", 0x1436CB8, 0x1A0
sArmaldoSprites51:
ax_sprite sArmaldoGfx51, 0x20
ax_sprite 0, 0x20
ax_sprite sArmaldoGfx51_1, 0x1a0
ax_sprite 0, 0x20
ax_sprite_terminator
sArmaldoGfx52:
.incbin "baserom.gba", 0x1436E80, 0x100
sArmaldoSprites52:
ax_sprite sArmaldoGfx52, 0x100
ax_sprite_terminator
sArmaldoGfx53:
.incbin "baserom.gba", 0x1436F90, 0x100
sArmaldoSprites53:
ax_sprite sArmaldoGfx53, 0x100
ax_sprite_terminator
sArmaldoGfx54:
.incbin "baserom.gba", 0x14370A0, 0x80
sArmaldoSprites54:
ax_sprite sArmaldoGfx54, 0x80
ax_sprite_terminator
sArmaldoGfx55:
.incbin "baserom.gba", 0x1437130, 0x40
sArmaldoSprites55:
ax_sprite sArmaldoGfx55, 0x40
ax_sprite_terminator
sArmaldoGfx56:
.incbin "baserom.gba", 0x1437180, 0x20
sArmaldoSprites56:
ax_sprite sArmaldoGfx56, 0x20
ax_sprite_terminator
sArmaldoGfx57:
.incbin "baserom.gba", 0x14371B0, 0x20
sArmaldoSprites57:
ax_sprite sArmaldoGfx57, 0x20
ax_sprite_terminator
sArmaldoGfx58:
.incbin "baserom.gba", 0x14371E0, 0x60
sArmaldoGfx58_1:
.incbin "baserom.gba", 0x1437240, 0x60
sArmaldoGfx58_2:
.incbin "baserom.gba", 0x14372A0, 0x40
sArmaldoSprites58:
ax_sprite 0, 0x40
ax_sprite sArmaldoGfx58, 0x60
ax_sprite 0, 0x20
ax_sprite sArmaldoGfx58_1, 0x60
ax_sprite 0, 0x60
ax_sprite sArmaldoGfx58_2, 0x40
ax_sprite 0, 0x40
ax_sprite_terminator
sArmaldoGfx59:
.incbin "baserom.gba", 0x1437320, 0x60
sArmaldoGfx59_1:
.incbin "baserom.gba", 0x1437380, 0x100
sArmaldoGfx59_2:
.incbin "baserom.gba", 0x1437480, 0x60
sArmaldoSprites59:
ax_sprite sArmaldoGfx59, 0x60
ax_sprite 0, 0x20
ax_sprite sArmaldoGfx59_1, 0x100
ax_sprite 0, 0x20
ax_sprite sArmaldoGfx59_2, 0x60
ax_sprite_terminator
sArmaldoGfx60:
.incbin "baserom.gba", 0x1437510, 0x20
sArmaldoGfx60_1:
.incbin "baserom.gba", 0x1437530, 0x40
sArmaldoGfx60_2:
.incbin "baserom.gba", 0x1437570, 0x20
sArmaldoSprites60:
ax_sprite sArmaldoGfx60, 0x20
ax_sprite 0, 0x40
ax_sprite sArmaldoGfx60_1, 0x40
ax_sprite 0, 0x40
ax_sprite sArmaldoGfx60_2, 0x20
ax_sprite_terminator
sArmaldoGfx61:
.incbin "baserom.gba", 0x14375C0, 0x20
sArmaldoGfx61_1:
.incbin "baserom.gba", 0x14375E0, 0x20
sArmaldoSprites61:
ax_sprite sArmaldoGfx61, 0x20
ax_sprite 0, 0x40
ax_sprite sArmaldoGfx61_1, 0x20
ax_sprite_terminator
sArmaldoGfx62:
.incbin "baserom.gba", 0x1437620, 0x20
sArmaldoSprites62:
ax_sprite sArmaldoGfx62, 0x20
ax_sprite_terminator
sArmaldoGfx63:
.incbin "baserom.gba", 0x1437650, 0x20
sArmaldoSprites63:
ax_sprite sArmaldoGfx63, 0x20
ax_sprite_terminator
sArmaldoGfx64:
.incbin "baserom.gba", 0x1437680, 0x200
sArmaldoSprites64:
ax_sprite sArmaldoGfx64, 0x200
ax_sprite_terminator
sArmaldoGfx65:
.incbin "baserom.gba", 0x1437890, 0x200
sArmaldoSprites65:
ax_sprite sArmaldoGfx65, 0x200
ax_sprite_terminator
sArmaldoGfx66:
.incbin "baserom.gba", 0x1437AA0, 0x200
sArmaldoSprites66:
ax_sprite sArmaldoGfx66, 0x200
ax_sprite_terminator
sArmaldoGfx67:
.incbin "baserom.gba", 0x1437CB0, 0x200
sArmaldoSprites67:
ax_sprite sArmaldoGfx67, 0x200
ax_sprite_terminator
sArmaldoGfx68:
.incbin "baserom.gba", 0x1437EC0, 0x200
sArmaldoSprites68:
ax_sprite sArmaldoGfx68, 0x200
ax_sprite_terminator
sArmaldoGfx69:
.incbin "baserom.gba", 0x14380D0, 0x200
sArmaldoSprites69:
ax_sprite sArmaldoGfx69, 0x200
ax_sprite_terminator
sArmaldoGfx70:
.incbin "baserom.gba", 0x14382E0, 0x200
sArmaldoSprites70:
ax_sprite sArmaldoGfx70, 0x200
ax_sprite_terminator
sArmaldoGfx71:
.incbin "baserom.gba", 0x14384F0, 0x200
sArmaldoSprites71:
ax_sprite sArmaldoGfx71, 0x200
ax_sprite_terminator
sAxPosesArmaldo:
.4byte sArmaldoPose1
.4byte sArmaldoPose2
.4byte sArmaldoPose3
.4byte sArmaldoPose4
.4byte sArmaldoPose5
.4byte sArmaldoPose6
.4byte sArmaldoPose7
.4byte sArmaldoPose8
.4byte sArmaldoPose9
.4byte sArmaldoPose10
.4byte sArmaldoPose11
.4byte sArmaldoPose12
.4byte sArmaldoPose13
.4byte sArmaldoPose14
.4byte sArmaldoPose15
.4byte sArmaldoPose16
.4byte sArmaldoPose17
.4byte sArmaldoPose18
.4byte sArmaldoPose19
.4byte sArmaldoPose20
.4byte sArmaldoPose21
.4byte sArmaldoPose22
.4byte sArmaldoPose23
.4byte sArmaldoPose24
.4byte sArmaldoPose25
.4byte sArmaldoPose26
.4byte sArmaldoPose27
.4byte sArmaldoPose28
.4byte sArmaldoPose29
.4byte sArmaldoPose30
.4byte sArmaldoPose31
.4byte sArmaldoPose32
.4byte sArmaldoPose33
.4byte sArmaldoPose34
.4byte sArmaldoPose35
.4byte sArmaldoPose36
.4byte sArmaldoPose37
.4byte sArmaldoPose38
.4byte sArmaldoPose39
.4byte sArmaldoPose40
.4byte sArmaldoPose41
.4byte sArmaldoPose42
.4byte sArmaldoPose43
.4byte sArmaldoPose44
.4byte sArmaldoPose45
.4byte sArmaldoPose46
.4byte sArmaldoPose47
.4byte sArmaldoPose48
.4byte sArmaldoPose49
.4byte sArmaldoPose50
.4byte sArmaldoPose51
.4byte sArmaldoPose52
.4byte sArmaldoPose53
.4byte sArmaldoPose54
.4byte sArmaldoPose55
.4byte sArmaldoPose56
.4byte sArmaldoPose57
.4byte sArmaldoPose58
.4byte sArmaldoPose59
.4byte sArmaldoPose60
.4byte sArmaldoPose61
.4byte sArmaldoPose62
.4byte sArmaldoPose63
.4byte sArmaldoPose64
.4byte sArmaldoPose65
.4byte sArmaldoPose66
.4byte sArmaldoPose67
.4byte sArmaldoPose68
.4byte sArmaldoPose69
.4byte sArmaldoPose70
.4byte sArmaldoPose71
.4byte sArmaldoPose72
.4byte sArmaldoPose73
.4byte sArmaldoPose74
.4byte sArmaldoPose75
.4byte sArmaldoPose76
.4byte sArmaldoPose77
.4byte sArmaldoPose78
.4byte sArmaldoPose79
.4byte sArmaldoPose80
.4byte sArmaldoPose81
.4byte sArmaldoPose82
.4byte sArmaldoPose83
.4byte sArmaldoPose84
.4byte sArmaldoPose85
.4byte sArmaldoPose86
.4byte sArmaldoPose87
.4byte sArmaldoPose88
.4byte sArmaldoPose89
.4byte sArmaldoPose90
.4byte sArmaldoPose91
.4byte sArmaldoPose92
.4byte sArmaldoPose93
.4byte sArmaldoPose94
.4byte sArmaldoPose95
.4byte sArmaldoPose96
.4byte sArmaldoPose97
.4byte sArmaldoPose98
.4byte sArmaldoPose99
.4byte sArmaldoPose100
.4byte sArmaldoPose101
.4byte sArmaldoPose102
.4byte sArmaldoPose103
.4byte sArmaldoPose104
.4byte sArmaldoPose105
.4byte sArmaldoPose106
.4byte sArmaldoPose107
.4byte sArmaldoPose108
.4byte sArmaldoPose109
.4byte sArmaldoPose110
.4byte sArmaldoPose111
.4byte sArmaldoPose112
.4byte sArmaldoPose113
.4byte sArmaldoPose114
.4byte sArmaldoPose115
.4byte sArmaldoPose116
.4byte sArmaldoPose117
.4byte sArmaldoPose118
.4byte sArmaldoPose119
.4byte sArmaldoPose120
.4byte sArmaldoPose121
.4byte sArmaldoPose122
.4byte sArmaldoPose123
.4byte sArmaldoPose124
.4byte sArmaldoPose125
.4byte sArmaldoPose126
.4byte sArmaldoPose127
.4byte sArmaldoPose128
.4byte sArmaldoPose129
.4byte sArmaldoPose130
.4byte sArmaldoPose131
.4byte sArmaldoPose132
.4byte sArmaldoPose133
.4byte sArmaldoPose134
.4byte sArmaldoPose135
.4byte sArmaldoPose136
.4byte sArmaldoPose137
.4byte sArmaldoPose138
.4byte sArmaldoPose139
.4byte sArmaldoPose140
.4byte sArmaldoPose141
.4byte sArmaldoPose142
.4byte sArmaldoPose143
.4byte sArmaldoPose144
.4byte sArmaldoPose145
.4byte sArmaldoPose146
.4byte sArmaldoPose147
.4byte sArmaldoPose148
.4byte sArmaldoPose149
.4byte sArmaldoPose150
.4byte sArmaldoPose151
.4byte sArmaldoPose152
.4byte sArmaldoPose153
.4byte sArmaldoPose154
.4byte sArmaldoPose155
.4byte sArmaldoPose156
.4byte sArmaldoPose157
.4byte sArmaldoPose158
.4byte sArmaldoPose159
.4byte sArmaldoPose160
.4byte sArmaldoPose161
.4byte sArmaldoPose162
.4byte sArmaldoPose163
.4byte sArmaldoPose164
.4byte sArmaldoPose165
.4byte sArmaldoPose166
.4byte sArmaldoPose167
.4byte sArmaldoPose168
.4byte sArmaldoPose169
.4byte sArmaldoPose170
.4byte sArmaldoPose171
.4byte sArmaldoPose172
.4byte sArmaldoPose173
.4byte sArmaldoPose174
.4byte sArmaldoPose175
.4byte sArmaldoPose176
.4byte sArmaldoPose177
.4byte sArmaldoPose178
.4byte sArmaldoPose179
.4byte sArmaldoPose180
.4byte sArmaldoPose181
.4byte sArmaldoPose182
.4byte sArmaldoPose183
.4byte sArmaldoPose184
.4byte sArmaldoPose185
.4byte sArmaldoPose186
.4byte sArmaldoPose187
.4byte sArmaldoPose188
.4byte sArmaldoPose189
.4byte sArmaldoPose190
.4byte sArmaldoPose191
.4byte sArmaldoPose192
.4byte sArmaldoPose193
.4byte sArmaldoPose194
.4byte sArmaldoPose195
.4byte sArmaldoPose196
.4byte sArmaldoPose197
.4byte sArmaldoPose198
.4byte sArmaldoPose199
.4byte sArmaldoPose200
.4byte sArmaldoPose201
.4byte sArmaldoPose202
.4byte sArmaldoPose203
.4byte sArmaldoPose204
.4byte sArmaldoPose205
.4byte sArmaldoPose206
.4byte sArmaldoPose207
.4byte sArmaldoPose208
.4byte sArmaldoPose209
.4byte sArmaldoPose210
.4byte sArmaldoPose211
.4byte sArmaldoPose212
.4byte sArmaldoPose213
.4byte sArmaldoPose214
.4byte sArmaldoPose215
.4byte sArmaldoPose216
.4byte sArmaldoPose217
.4byte sArmaldoPose218
.4byte sArmaldoPose219
.4byte sArmaldoPose220
.4byte sArmaldoPose221
.4byte sArmaldoPose222
.4byte sArmaldoPose223
.4byte sArmaldoPose224
.4byte sArmaldoPose225
.4byte sArmaldoPose226
.4byte sArmaldoPose227
.4byte sArmaldoPose228
.4byte sArmaldoPose229
.4byte sArmaldoPose230
.4byte sArmaldoPose231
.4byte sArmaldoPose232
.4byte sArmaldoPose233
.4byte sArmaldoPose234
.4byte sArmaldoPose235
.4byte sArmaldoPose236
.4byte sArmaldoPose237
.4byte sArmaldoPose238
.4byte sArmaldoPose239
.4byte sArmaldoPose240
.4byte sArmaldoPose241
.4byte sArmaldoPose242
.4byte sArmaldoPose243
.4byte sArmaldoPose244
.4byte sArmaldoPose245
.4byte sArmaldoPose246
sAxPositionsArmaldo:
.2byte   -1,  -13, 	  -9,   -2, 	   7,   -2, 	  -1,   -9
.2byte   -1,  -11, 	  -8,   -2, 	   7,    1, 	   0,   -7
.2byte   -1,  -11, 	  -9,    1, 	   7,   -1, 	  -1,   -7
.2byte    4,  -14, 	  10,   -5, 	  -2,    1, 	  -1,  -10
.2byte    5,  -12, 	   8,   -4, 	   0,    3, 	   0,   -8
.2byte    5,  -12, 	  11,   -3, 	  -2,    0, 	   1,   -9
.2byte    9,  -18, 	   8,  -10, 	   8,   -3, 	  -2,  -10
.2byte   10,  -17, 	   9,   -8, 	  10,   -2, 	  -1,   -9
.2byte   10,  -17, 	  10,   -8, 	   6,   -1, 	  -1,   -9
.2byte    5,  -20, 	  -4,  -13, 	  10,   -6, 	  -2,  -11
.2byte    6,  -19, 	  -3,  -13, 	  11,   -6, 	  -2,  -10
.2byte    6,  -19, 	  -2,  -12, 	   8,   -5, 	   0,  -11
.2byte   -1,  -21, 	   6,   -9, 	  -6,   -9, 	   0,  -11
.2byte   -1,  -19, 	   6,   -8, 	  -6,   -9, 	  -1,  -10
.2byte    0,  -19, 	   8,   -8, 	  -5,   -7, 	   0,  -10
.2byte   -6,  -20, 	   3,  -13, 	 -11,   -6, 	   1,  -11
.2byte   -7,  -19, 	   2,  -13, 	 -12,   -6, 	   1,  -10
.2byte   -7,  -19, 	   1,  -12, 	  -9,   -5, 	  -1,  -11
.2byte  -11,  -17, 	 -10,   -9, 	 -10,   -2, 	   0,   -9
.2byte  -12,  -16, 	 -11,   -7, 	 -12,   -1, 	  -1,   -8
.2byte  -12,  -16, 	 -12,   -7, 	  -8,    0, 	  -1,   -8
.2byte   -6,  -14, 	 -12,   -5, 	   0,    1, 	  -1,  -10
.2byte   -7,  -12, 	 -10,   -4, 	  -2,    3, 	  -2,   -8
.2byte   -7,  -12, 	 -13,   -3, 	   0,    0, 	  -3,   -9
.2byte   -1,  -13, 	  -9,   -2, 	   7,   -2, 	  -1,   -9
.2byte   -1,  -11, 	  -8,   -2, 	   7,    1, 	   0,   -7
.2byte   -1,  -11, 	  -9,    1, 	   7,   -1, 	  -1,   -7
.2byte   -1,  -15, 	 -14,  -20, 	  13,  -20, 	   0,  -10
.2byte   -1,   -9, 	 -12,   -5, 	  12,   -5, 	   0,   -7
.2byte    4,  -14, 	  10,   -5, 	  -2,    1, 	  -1,  -10
.2byte    5,  -12, 	   8,   -4, 	   0,    3, 	   0,   -8
.2byte    5,  -12, 	  11,   -3, 	  -2,    0, 	   1,   -9
.2byte    3,  -16, 	  11,  -22, 	  -6,  -19, 	  -1,  -11
.2byte    7,  -11, 	   0,  -11, 	 -11,   -5, 	  -1,   -8
.2byte    9,  -18, 	   8,  -10, 	   8,   -3, 	  -2,  -10
.2byte   10,  -17, 	   9,   -8, 	  10,   -2, 	  -1,   -9
.2byte   10,  -17, 	  10,   -8, 	   6,   -1, 	  -1,   -9
.2byte    6,  -20, 	   9,  -26, 	   8,  -15, 	  -1,  -11
.2byte   12,  -16, 	  -1,  -11, 	  -3,   -3, 	   0,  -13
.2byte    5,  -20, 	  -4,  -13, 	  10,   -6, 	  -2,  -11
.2byte    6,  -19, 	  -3,  -13, 	  11,   -6, 	  -2,  -10
.2byte    6,  -19, 	  -2,  -12, 	   8,   -5, 	   0,  -11
.2byte    2,  -22, 	  -5,  -27, 	  14,  -20, 	  -2,  -12
.2byte    8,  -20, 	  -6,  -12, 	   7,   -3, 	  -1,  -13
.2byte   -1,  -21, 	   6,   -9, 	  -6,   -9, 	   0,  -11
.2byte   -1,  -19, 	   6,   -8, 	  -6,   -9, 	  -1,  -10
.2byte    0,  -19, 	   8,   -8, 	  -5,   -7, 	   0,  -10
.2byte   -1,  -22, 	  13,  -23, 	 -14,  -22, 	  -1,  -12
.2byte    0,  -20, 	  13,   -7, 	 -14,   -7, 	  -1,  -13
.2byte   -6,  -20, 	   3,  -13, 	 -11,   -6, 	   1,  -11
.2byte   -7,  -19, 	   2,  -13, 	 -12,   -6, 	   1,  -10
.2byte   -7,  -19, 	   1,  -12, 	  -9,   -5, 	  -1,  -11
.2byte   -3,  -22, 	   4,  -27, 	 -15,  -20, 	   1,  -12
.2byte   -9,  -20, 	   5,  -12, 	  -8,   -3, 	   0,  -13
.2byte  -11,  -17, 	 -10,   -9, 	 -10,   -2, 	   0,   -9
.2byte  -12,  -16, 	 -11,   -7, 	 -12,   -1, 	  -1,   -8
.2byte  -12,  -16, 	 -12,   -7, 	  -8,    0, 	  -1,   -8
.2byte   -8,  -19, 	 -11,  -25, 	 -10,  -14, 	  -1,  -10
.2byte  -14,  -15, 	  -1,  -10, 	   1,   -2, 	  -2,  -12
.2byte   -6,  -14, 	 -12,   -5, 	   0,    1, 	  -1,  -10
.2byte   -7,  -12, 	 -10,   -4, 	  -2,    3, 	  -2,   -8
.2byte   -7,  -12, 	 -13,   -3, 	   0,    0, 	  -3,   -9
.2byte   -5,  -16, 	 -13,  -22, 	   4,  -19, 	  -1,  -11
.2byte   -9,  -11, 	  -2,  -11, 	   9,   -5, 	  -1,   -8
.2byte   -1,  -13, 	  -9,   -2, 	   7,   -2, 	  -1,   -9
.2byte   -1,  -15, 	 -14,  -20, 	  13,  -20, 	   0,  -10
.2byte   -1,   -9, 	   7,    2, 	  -7,    3, 	   0,   -6
.2byte   -1,   -9, 	   7,    2, 	  -7,    3, 	   0,   -6
.2byte    4,  -14, 	  10,   -5, 	  -2,    1, 	  -1,  -10
.2byte    3,  -16, 	  11,  -22, 	  -6,  -19, 	  -1,  -11
.2byte    7,  -11, 	   5,    2, 	  11,   -1, 	  -1,   -9
.2byte    7,  -11, 	   5,    2, 	  11,   -1, 	  -1,   -9
.2byte    9,  -18, 	   8,  -10, 	   8,   -3, 	  -2,  -10
.2byte    6,  -20, 	   9,  -26, 	   8,  -15, 	  -1,  -11
.2byte   12,  -16, 	  10,   -1, 	  14,  -11, 	   0,  -11
.2byte   12,  -16, 	  10,   -1, 	  14,  -11, 	   0,  -11
.2byte    5,  -20, 	  -4,  -13, 	  10,   -6, 	  -2,  -11
.2byte    2,  -22, 	  -5,  -27, 	  14,  -20, 	  -2,  -12
.2byte    7,  -19, 	  10,   -6, 	  -1,  -13, 	  -2,  -11
.2byte    7,  -19, 	  10,   -6, 	  -1,  -13, 	  -2,  -11
.2byte   -1,  -21, 	   6,   -9, 	  -6,   -9, 	   0,  -11
.2byte   -1,  -22, 	  13,  -23, 	 -14,  -22, 	  -1,  -12
.2byte    0,  -20, 	   8,   -7, 	  -7,   -7, 	  -1,  -14
.2byte    0,  -20, 	   8,   -7, 	  -7,   -7, 	  -1,  -14
.2byte   -6,  -20, 	   3,  -13, 	 -11,   -6, 	   1,  -11
.2byte   -3,  -22, 	   4,  -27, 	 -15,  -20, 	   1,  -12
.2byte   -8,  -19, 	 -11,   -6, 	   0,  -13, 	   1,  -11
.2byte   -8,  -19, 	 -11,   -6, 	   0,  -13, 	   1,  -11
.2byte  -11,  -17, 	 -10,   -9, 	 -10,   -2, 	   0,   -9
.2byte   -8,  -19, 	 -11,  -25, 	 -10,  -14, 	  -1,  -10
.2byte  -14,  -15, 	 -12,    0, 	 -16,  -10, 	  -2,  -10
.2byte  -14,  -15, 	 -12,    0, 	 -16,  -10, 	  -2,  -10
.2byte   -6,  -14, 	 -12,   -5, 	   0,    1, 	  -1,  -10
.2byte   -5,  -16, 	 -13,  -22, 	   4,  -19, 	  -1,  -11
.2byte   -9,  -11, 	  -7,    2, 	 -13,   -1, 	  -1,   -9
.2byte   -9,  -11, 	  -7,    2, 	 -13,   -1, 	  -1,   -9
.2byte   -1,  -13, 	  -9,   -2, 	   7,   -2, 	  -1,   -9
.2byte   -1,  -15, 	 -14,  -20, 	  13,  -20, 	   0,  -10
.2byte   -1,   -9, 	 -12,   -5, 	  12,   -5, 	   0,   -7
.2byte    4,  -14, 	  10,   -5, 	  -2,    1, 	  -1,  -10
.2byte    3,  -16, 	  11,  -22, 	  -6,  -19, 	  -1,  -11
.2byte    7,  -11, 	   0,  -11, 	 -11,   -5, 	  -1,   -8
.2byte    9,  -18, 	   8,  -10, 	   8,   -3, 	  -2,  -10
.2byte    6,  -20, 	   9,  -26, 	   8,  -15, 	  -1,  -11
.2byte   12,  -16, 	  -1,  -11, 	  -3,   -3, 	   0,  -13
.2byte    5,  -20, 	  -4,  -13, 	  10,   -6, 	  -2,  -11
.2byte    2,  -22, 	  -5,  -27, 	  14,  -20, 	  -2,  -12
.2byte    8,  -20, 	  -6,  -12, 	   7,   -3, 	  -1,  -13
.2byte   -1,  -21, 	   6,   -9, 	  -6,   -9, 	   0,  -11
.2byte   -1,  -22, 	  13,  -23, 	 -14,  -22, 	  -1,  -12
.2byte    0,  -20, 	  13,   -7, 	 -14,   -7, 	  -1,  -13
.2byte   -6,  -20, 	   3,  -13, 	 -11,   -6, 	   1,  -11
.2byte   -3,  -22, 	   4,  -27, 	 -15,  -20, 	   1,  -12
.2byte   -9,  -20, 	   5,  -12, 	  -8,   -3, 	   0,  -13
.2byte  -11,  -17, 	 -10,   -9, 	 -10,   -2, 	   0,   -9
.2byte   -8,  -19, 	 -11,  -25, 	 -10,  -14, 	  -1,  -10
.2byte  -14,  -15, 	  -1,  -10, 	   1,   -2, 	  -2,  -12
.2byte   -6,  -14, 	 -12,   -5, 	   0,    1, 	  -1,  -10
.2byte   -5,  -16, 	 -13,  -22, 	   4,  -19, 	  -1,  -11
.2byte   -9,  -11, 	  -2,  -11, 	   9,   -5, 	  -1,   -8
.2byte   -1,  -13, 	  -9,   -2, 	   7,   -2, 	  -1,   -9
.2byte   -5,  -13, 	 -11,   -4, 	   1,    2, 	   0,   -9
.2byte  -10,  -17, 	  -9,   -9, 	  -9,   -2, 	   1,   -9
.2byte   -5,  -20, 	   4,  -13, 	 -10,   -6, 	   2,  -11
.2byte   -1,  -21, 	   6,   -9, 	  -6,   -9, 	   0,  -11
.2byte    4,  -20, 	  -5,  -13, 	   9,   -6, 	  -3,  -11
.2byte   10,  -18, 	   9,  -10, 	   9,   -3, 	  -1,  -10
.2byte    5,  -13, 	  11,   -4, 	  -1,    2, 	   0,   -9
.2byte   -5,  -11, 	 -11,   -3, 	   1,    2, 	  -1,   -6
.2byte   -6,  -10, 	 -12,   -2, 	   1,    3, 	  -1,   -5
.2byte   -1,  -18, 	 -12,   -9, 	  12,   -9, 	   0,   -9
.2byte    0,  -17, 	  11,  -10, 	 -10,   -3, 	  -1,   -9
.2byte    2,  -23, 	  -9,  -10, 	  -6,   -4, 	  -2,  -10
.2byte    2,  -22, 	  -8,  -11, 	   9,   -5, 	  -3,  -12
.2byte    0,  -19, 	  10,  -10, 	 -11,   -9, 	   0,   -9
.2byte   -3,  -22, 	   7,  -11, 	 -10,   -5, 	   2,  -12
.2byte   -3,  -23, 	   8,  -10, 	   5,   -4, 	   1,  -10
.2byte   -1,  -17, 	 -12,  -10, 	   9,   -3, 	   0,   -9
.2byte   -1,  -13, 	  -9,   -2, 	   7,   -2, 	  -1,   -9
.2byte   -1,  -15, 	 -14,  -20, 	  13,  -20, 	   0,  -10
.2byte   -1,   -9, 	 -12,   -5, 	  12,   -5, 	   0,   -7
.2byte    4,  -14, 	  10,   -5, 	  -2,    1, 	  -1,  -10
.2byte    3,  -16, 	  11,  -22, 	  -6,  -19, 	  -1,  -11
.2byte    7,  -11, 	   0,  -11, 	 -11,   -5, 	  -1,   -8
.2byte    9,  -18, 	   8,  -10, 	   8,   -3, 	  -2,  -10
.2byte    6,  -20, 	   9,  -26, 	   8,  -15, 	  -1,  -11
.2byte   12,  -16, 	  -1,  -11, 	  -3,   -3, 	   0,  -13
.2byte    5,  -20, 	  -4,  -13, 	  10,   -6, 	  -2,  -11
.2byte    2,  -22, 	  -5,  -27, 	  14,  -20, 	  -2,  -12
.2byte    8,  -20, 	  -6,  -12, 	   7,   -3, 	  -1,  -13
.2byte   -1,  -21, 	   6,   -9, 	  -6,   -9, 	   0,  -11
.2byte   -1,  -22, 	  13,  -23, 	 -14,  -22, 	  -1,  -12
.2byte    0,  -20, 	  13,   -7, 	 -14,   -7, 	  -1,  -13
.2byte   -6,  -20, 	   3,  -13, 	 -11,   -6, 	   1,  -11
.2byte   -3,  -22, 	   4,  -27, 	 -15,  -20, 	   1,  -12
.2byte   -9,  -20, 	   5,  -12, 	  -8,   -3, 	   0,  -13
.2byte  -11,  -17, 	 -10,   -9, 	 -10,   -2, 	   0,   -9
.2byte   -8,  -19, 	 -11,  -25, 	 -10,  -14, 	  -1,  -10
.2byte  -14,  -15, 	  -1,  -10, 	   1,   -2, 	  -2,  -12
.2byte   -6,  -14, 	 -12,   -5, 	   0,    1, 	  -1,  -10
.2byte   -5,  -16, 	 -13,  -22, 	   4,  -19, 	  -1,  -11
.2byte   -9,  -11, 	  -2,  -11, 	   9,   -5, 	  -1,   -8
.2byte   -1,   -8, 	 -12,   -4, 	  12,   -4, 	   0,   -6
.2byte   -9,   -9, 	  -2,   -9, 	   9,   -3, 	  -1,   -6
.2byte  -14,  -15, 	  -1,  -10, 	   1,   -2, 	  -2,  -12
.2byte   -9,  -19, 	   5,  -11, 	  -8,   -2, 	   0,  -12
.2byte    0,  -19, 	  13,   -6, 	 -14,   -6, 	  -1,  -12
.2byte    8,  -19, 	  -6,  -11, 	   7,   -2, 	  -1,  -12
.2byte   12,  -15, 	  -1,  -10, 	  -3,   -2, 	   0,  -12
.2byte    8,   -9, 	   1,   -9, 	 -10,   -3, 	   0,   -6
.2byte    4,  -14, 	  10,   -5, 	  -2,    1, 	  -1,  -10
.2byte    5,  -12, 	   8,   -4, 	   0,    3, 	   0,   -8
.2byte    5,  -12, 	  11,   -3, 	  -2,    0, 	   1,   -9
.2byte    3,  -16, 	  11,  -22, 	  -6,  -19, 	  -1,  -11
.2byte    9,  -18, 	   8,  -10, 	   8,   -3, 	  -2,  -10
.2byte   10,  -17, 	   9,   -8, 	  10,   -2, 	  -1,   -9
.2byte   10,  -17, 	  10,   -8, 	   6,   -1, 	  -1,   -9
.2byte    6,  -20, 	   9,  -26, 	   8,  -15, 	  -1,  -11
.2byte    5,  -20, 	  -4,  -13, 	  10,   -6, 	  -2,  -11
.2byte    6,  -19, 	  -3,  -13, 	  11,   -6, 	  -2,  -10
.2byte    6,  -19, 	  -2,  -12, 	   8,   -5, 	   0,  -11
.2byte    2,  -22, 	  -5,  -27, 	  14,  -20, 	  -2,  -12
.2byte   -1,  -21, 	   6,   -9, 	  -6,   -9, 	   0,  -11
.2byte   -1,  -19, 	   6,   -8, 	  -6,   -9, 	  -1,  -10
.2byte    0,  -19, 	   8,   -8, 	  -5,   -7, 	   0,  -10
.2byte   -1,  -22, 	  13,  -23, 	 -14,  -22, 	  -1,  -12
.2byte   -6,  -20, 	   3,  -13, 	 -11,   -6, 	   1,  -11
.2byte   -7,  -19, 	   2,  -13, 	 -12,   -6, 	   1,  -10
.2byte   -7,  -19, 	   1,  -12, 	  -9,   -5, 	  -1,  -11
.2byte   -3,  -22, 	   4,  -27, 	 -15,  -20, 	   1,  -12
.2byte  -11,  -17, 	 -10,   -9, 	 -10,   -2, 	   0,   -9
.2byte  -12,  -16, 	 -11,   -7, 	 -12,   -1, 	  -1,   -8
.2byte  -12,  -16, 	 -12,   -7, 	  -8,    0, 	  -1,   -8
.2byte   -8,  -19, 	 -11,  -25, 	 -10,  -14, 	  -1,  -10
.2byte   -6,  -14, 	 -12,   -5, 	   0,    1, 	  -1,  -10
.2byte   -7,  -12, 	 -10,   -4, 	  -2,    3, 	  -2,   -8
.2byte   -7,  -12, 	 -13,   -3, 	   0,    0, 	  -3,   -9
.2byte   -5,  -16, 	 -13,  -22, 	   4,  -19, 	  -1,  -11
.2byte   -1,  -14, 	 -14,  -19, 	  13,  -19, 	   0,   -9
.2byte    4,  -14, 	  12,  -20, 	  -5,  -17, 	   0,   -9
.2byte    6,  -19, 	   9,  -25, 	   8,  -14, 	  -1,  -10
.2byte    2,  -20, 	  -5,  -25, 	  14,  -18, 	  -2,  -10
.2byte   -1,  -21, 	  13,  -22, 	 -14,  -21, 	  -1,  -11
.2byte   -3,  -20, 	   4,  -25, 	 -15,  -18, 	   1,  -10
.2byte   -7,  -19, 	 -10,  -25, 	  -9,  -14, 	   0,  -10
.2byte   -5,  -14, 	 -13,  -20, 	   4,  -17, 	  -1,   -9
.2byte   -1,  -12, 	  -9,   -1, 	   7,   -1, 	  -1,   -8
.2byte   -1,  -14, 	 -14,  -19, 	  13,  -19, 	   0,   -9
.2byte   -1,   -8, 	 -12,   -4, 	  12,   -4, 	   0,   -6
.2byte    4,  -12, 	  10,   -3, 	  -2,    3, 	  -1,   -8
.2byte    3,  -14, 	  11,  -20, 	  -6,  -17, 	  -1,   -9
.2byte    6,   -9, 	  -1,   -9, 	 -12,   -3, 	  -2,   -6
.2byte    9,  -17, 	   8,   -9, 	   8,   -2, 	  -2,   -9
.2byte    6,  -19, 	   9,  -25, 	   8,  -14, 	  -1,  -10
.2byte   11,  -15, 	  -2,  -10, 	  -4,   -2, 	  -1,  -12
.2byte    5,  -19, 	  -4,  -12, 	  10,   -5, 	  -2,  -10
.2byte    2,  -21, 	  -5,  -26, 	  14,  -19, 	  -2,  -11
.2byte    7,  -19, 	  -7,  -11, 	   6,   -2, 	  -2,  -12
.2byte   -1,  -20, 	   6,   -8, 	  -6,   -8, 	   0,  -10
.2byte   -1,  -21, 	  13,  -22, 	 -14,  -21, 	  -1,  -11
.2byte    0,  -19, 	  13,   -6, 	 -14,   -6, 	  -1,  -12
.2byte   -6,  -19, 	   3,  -12, 	 -11,   -5, 	   1,  -10
.2byte   -3,  -21, 	   4,  -26, 	 -15,  -19, 	   1,  -11
.2byte   -8,  -19, 	   6,  -11, 	  -7,   -2, 	   1,  -12
.2byte  -10,  -17, 	  -9,   -9, 	  -9,   -2, 	   1,   -9
.2byte   -7,  -19, 	 -10,  -25, 	  -9,  -14, 	   0,  -10
.2byte  -12,  -15, 	   1,  -10, 	   3,   -2, 	   0,  -12
.2byte   -5,  -12, 	 -11,   -3, 	   1,    3, 	   0,   -8
.2byte   -4,  -14, 	 -12,  -20, 	   5,  -17, 	   0,   -9
.2byte   -7,   -9, 	   0,   -9, 	  11,   -3, 	   1,   -6
.2byte   -1,  -10, 	   7,    1, 	  -7,    2, 	   0,   -7
.2byte   -8,  -11, 	  -6,    2, 	 -12,   -1, 	   0,   -9
.2byte  -14,  -15, 	 -12,    0, 	 -16,  -10, 	  -2,  -10
.2byte   -8,  -19, 	 -11,   -6, 	   0,  -13, 	   1,  -11
.2byte    0,  -20, 	   8,   -7, 	  -7,   -7, 	  -1,  -14
.2byte    7,  -19, 	  10,   -6, 	  -1,  -13, 	  -2,  -11
.2byte   13,  -15, 	  11,    0, 	  15,  -10, 	   1,  -10
.2byte    7,  -11, 	   5,    2, 	  11,   -1, 	  -1,   -9
.2byte   -1,  -13, 	  -9,   -2, 	   7,   -2, 	  -1,   -9
.2byte   -5,  -13, 	 -11,   -4, 	   1,    2, 	   0,   -9
.2byte  -10,  -17, 	  -9,   -9, 	  -9,   -2, 	   1,   -9
.2byte   -5,  -20, 	   4,  -13, 	 -10,   -6, 	   2,  -11
.2byte   -1,  -21, 	   6,   -9, 	  -6,   -9, 	   0,  -11
.2byte    4,  -20, 	  -5,  -13, 	   9,   -6, 	  -3,  -11
.2byte   10,  -18, 	   9,  -10, 	   9,   -3, 	  -1,  -10
.2byte    5,  -13, 	  11,   -4, 	  -1,    2, 	   0,   -9
sArmaldoAnimTable1:
.4byte sArmaldoAnims_1_1
.4byte sArmaldoAnims_1_2
.4byte sArmaldoAnims_1_3
.4byte sArmaldoAnims_1_4
.4byte sArmaldoAnims_1_5
.4byte sArmaldoAnims_1_6
.4byte sArmaldoAnims_1_7
.4byte sArmaldoAnims_1_8
sArmaldoAnimTable2:
.4byte sArmaldoAnims_2_1
.4byte sArmaldoAnims_2_2
.4byte sArmaldoAnims_2_3
.4byte sArmaldoAnims_2_4
.4byte sArmaldoAnims_2_5
.4byte sArmaldoAnims_2_6
.4byte sArmaldoAnims_2_7
.4byte sArmaldoAnims_2_8
sArmaldoAnimTable3:
.4byte sArmaldoAnims_3_1
.4byte sArmaldoAnims_3_2
.4byte sArmaldoAnims_3_3
.4byte sArmaldoAnims_3_4
.4byte sArmaldoAnims_3_5
.4byte sArmaldoAnims_3_6
.4byte sArmaldoAnims_3_7
.4byte sArmaldoAnims_3_8
sArmaldoAnimTable4:
.4byte sArmaldoAnims_4_1
.4byte sArmaldoAnims_4_2
.4byte sArmaldoAnims_4_3
.4byte sArmaldoAnims_4_4
.4byte sArmaldoAnims_4_5
.4byte sArmaldoAnims_4_6
.4byte sArmaldoAnims_4_7
.4byte sArmaldoAnims_4_8
sArmaldoAnimTable5:
.4byte sArmaldoAnims_5_1
.4byte sArmaldoAnims_5_2
.4byte sArmaldoAnims_5_3
.4byte sArmaldoAnims_5_4
.4byte sArmaldoAnims_5_5
.4byte sArmaldoAnims_5_6
.4byte sArmaldoAnims_5_7
.4byte sArmaldoAnims_5_8
sArmaldoAnimTable6:
.4byte sArmaldoAnims_6_1
.4byte sArmaldoAnims_6_1
.4byte sArmaldoAnims_6_1
.4byte sArmaldoAnims_6_1
.4byte sArmaldoAnims_6_1
.4byte sArmaldoAnims_6_1
.4byte sArmaldoAnims_6_1
.4byte sArmaldoAnims_6_1
sArmaldoAnimTable7:
.4byte sArmaldoAnims_7_1
.4byte sArmaldoAnims_7_2
.4byte sArmaldoAnims_7_3
.4byte sArmaldoAnims_7_4
.4byte sArmaldoAnims_7_5
.4byte sArmaldoAnims_7_6
.4byte sArmaldoAnims_7_7
.4byte sArmaldoAnims_7_8
sArmaldoAnimTable8:
.4byte sArmaldoAnims_8_1
.4byte sArmaldoAnims_8_2
.4byte sArmaldoAnims_8_3
.4byte sArmaldoAnims_8_4
.4byte sArmaldoAnims_8_5
.4byte sArmaldoAnims_8_6
.4byte sArmaldoAnims_8_7
.4byte sArmaldoAnims_8_8
sArmaldoAnimTable9:
.4byte sArmaldoAnims_9_1
.4byte sArmaldoAnims_9_2
.4byte sArmaldoAnims_9_3
.4byte sArmaldoAnims_9_4
.4byte sArmaldoAnims_9_5
.4byte sArmaldoAnims_9_6
.4byte sArmaldoAnims_9_7
.4byte sArmaldoAnims_9_8
sArmaldoAnimTable10:
.4byte sArmaldoAnims_10_1
.4byte sArmaldoAnims_10_2
.4byte sArmaldoAnims_10_3
.4byte sArmaldoAnims_10_4
.4byte sArmaldoAnims_10_5
.4byte sArmaldoAnims_10_6
.4byte sArmaldoAnims_10_7
.4byte sArmaldoAnims_10_8
sArmaldoAnimTable11:
.4byte sArmaldoAnims_11_1
.4byte sArmaldoAnims_11_2
.4byte sArmaldoAnims_11_3
.4byte sArmaldoAnims_11_4
.4byte sArmaldoAnims_11_5
.4byte sArmaldoAnims_11_6
.4byte sArmaldoAnims_11_7
.4byte sArmaldoAnims_11_8
sArmaldoAnimTable12:
.4byte sArmaldoAnims_12_1
.4byte sArmaldoAnims_12_2
.4byte sArmaldoAnims_12_3
.4byte sArmaldoAnims_12_4
.4byte sArmaldoAnims_12_5
.4byte sArmaldoAnims_12_6
.4byte sArmaldoAnims_12_7
.4byte sArmaldoAnims_12_8
sArmaldoAnimTable13:
.4byte sArmaldoAnims_13_1
.4byte sArmaldoAnims_13_2
.4byte sArmaldoAnims_13_3
.4byte sArmaldoAnims_13_4
.4byte sArmaldoAnims_13_5
.4byte sArmaldoAnims_13_6
.4byte sArmaldoAnims_13_7
.4byte sArmaldoAnims_13_8
sAxAnimationsArmaldo:
.4byte sArmaldoAnimTable1
.4byte sArmaldoAnimTable2
.4byte sArmaldoAnimTable3
.4byte sArmaldoAnimTable4
.4byte sArmaldoAnimTable5
.4byte sArmaldoAnimTable6
.4byte sArmaldoAnimTable7
.4byte sArmaldoAnimTable8
.4byte sArmaldoAnimTable9
.4byte sArmaldoAnimTable10
.4byte sArmaldoAnimTable11
.4byte sArmaldoAnimTable12
.4byte sArmaldoAnimTable13
sAxSpritesArmaldo:
.4byte sArmaldoSprites1
.4byte sArmaldoSprites2
.4byte sArmaldoSprites3
.4byte sArmaldoSprites4
.4byte sArmaldoSprites5
.4byte sArmaldoSprites6
.4byte sArmaldoSprites7
.4byte sArmaldoSprites8
.4byte sArmaldoSprites9
.4byte sArmaldoSprites10
.4byte sArmaldoSprites11
.4byte sArmaldoSprites12
.4byte sArmaldoSprites13
.4byte sArmaldoSprites14
.4byte sArmaldoSprites15
.4byte sArmaldoSprites16
.4byte sArmaldoSprites17
.4byte sArmaldoSprites18
.4byte sArmaldoSprites19
.4byte sArmaldoSprites20
.4byte sArmaldoSprites21
.4byte sArmaldoSprites22
.4byte sArmaldoSprites23
.4byte sArmaldoSprites24
.4byte sArmaldoSprites25
.4byte sArmaldoSprites26
.4byte sArmaldoSprites27
.4byte sArmaldoSprites28
.4byte sArmaldoSprites29
.4byte sArmaldoSprites30
.4byte sArmaldoSprites31
.4byte sArmaldoSprites32
.4byte sArmaldoSprites33
.4byte sArmaldoSprites34
.4byte sArmaldoSprites35
.4byte sArmaldoSprites36
.4byte sArmaldoSprites37
.4byte sArmaldoSprites38
.4byte sArmaldoSprites39
.4byte sArmaldoSprites40
.4byte sArmaldoSprites41
.4byte sArmaldoSprites42
.4byte sArmaldoSprites43
.4byte sArmaldoSprites44
.4byte sArmaldoSprites45
.4byte sArmaldoSprites46
.4byte sArmaldoSprites47
.4byte sArmaldoSprites48
.4byte sArmaldoSprites49
.4byte sArmaldoSprites50
.4byte sArmaldoSprites51
.4byte sArmaldoSprites52
.4byte sArmaldoSprites53
.4byte sArmaldoSprites54
.4byte sArmaldoSprites55
.4byte sArmaldoSprites56
.4byte sArmaldoSprites57
.4byte sArmaldoSprites58
.4byte sArmaldoSprites59
.4byte sArmaldoSprites60
.4byte sArmaldoSprites61
.4byte sArmaldoSprites62
.4byte sArmaldoSprites63
.4byte sArmaldoSprites64
.4byte sArmaldoSprites65
.4byte sArmaldoSprites66
.4byte sArmaldoSprites67
.4byte sArmaldoSprites68
.4byte sArmaldoSprites69
.4byte sArmaldoSprites70
.4byte sArmaldoSprites71
sAxMainArmaldo:
ax_main sAxPosesArmaldo, sAxAnimationsArmaldo, 13, sAxSpritesArmaldo, sAxPositionsArmaldo
