.global gAxBanette
gAxBanette:
ax_siro sAxMainBanette
sBanettePose1:
ax_pose 0, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sBanettePose2:
ax_pose 1, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sBanettePose3:
ax_pose 2, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sBanettePose4:
ax_pose 3, 0x01e8, 0x80ec, 0x5c00
ax_pose_terminator
sBanettePose5:
ax_pose 4, 0x01e8, 0x80ec, 0x5c00
ax_pose_terminator
sBanettePose6:
ax_pose 5, 0x01e8, 0x80ec, 0x5c00
ax_pose_terminator
sBanettePose7:
ax_pose 6, 0x01e8, 0x80ec, 0x5c00
ax_pose_terminator
sBanettePose8:
ax_pose 7, 0x01e8, 0x80ec, 0x5c00
ax_pose_terminator
sBanettePose9:
ax_pose 8, 0x01e8, 0x80ec, 0x5c00
ax_pose_terminator
sBanettePose10:
ax_pose 9, 0x01e8, 0x80ec, 0x5c00
ax_pose_terminator
sBanettePose11:
ax_pose 10, 0x01e8, 0x80ec, 0x5c00
ax_pose_terminator
sBanettePose12:
ax_pose 11, 0x01e8, 0x80ec, 0x5c00
ax_pose_terminator
sBanettePose13:
ax_pose 12, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sBanettePose14:
ax_pose 13, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sBanettePose15:
ax_pose 14, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sBanettePose16:
ax_pose 15, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sBanettePose17:
ax_pose 16, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sBanettePose18:
ax_pose 17, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sBanettePose19:
ax_pose 18, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sBanettePose20:
ax_pose 19, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sBanettePose21:
ax_pose 20, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sBanettePose22:
ax_pose 21, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sBanettePose23:
ax_pose 22, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sBanettePose24:
ax_pose 23, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sBanettePose25:
ax_pose 0, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sBanettePose26:
ax_pose 24, 0x01e6, 0x80f1, 0x5c00
ax_pose_terminator
sBanettePose27:
ax_pose 3, 0x01e8, 0x80ec, 0x5c00
ax_pose_terminator
sBanettePose28:
ax_pose 25, 0x01e7, 0x80f0, 0x5c00
ax_pose_terminator
sBanettePose29:
ax_pose 6, 0x01e8, 0x80ec, 0x5c00
ax_pose_terminator
sBanettePose30:
ax_pose 26, 0x01e7, 0x80ee, 0x5c00
ax_pose_terminator
sBanettePose31:
ax_pose 9, 0x01e8, 0x80ec, 0x5c00
ax_pose_terminator
sBanettePose32:
ax_pose 27, 0x01e9, 0x80f0, 0x5c00
ax_pose_terminator
sBanettePose33:
ax_pose 12, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sBanettePose34:
ax_pose 28, 0x01e9, 0x80f4, 0x5c00
ax_pose_terminator
sBanettePose35:
ax_pose 15, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sBanettePose36:
ax_pose 29, 0x01e9, 0x80f0, 0x5c00
ax_pose_terminator
sBanettePose37:
ax_pose 18, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sBanettePose38:
ax_pose 30, 0x01e7, 0x80f2, 0x5c00
ax_pose_terminator
sBanettePose39:
ax_pose 21, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sBanettePose40:
ax_pose 31, 0x01e7, 0x80f0, 0x5c00
ax_pose_terminator
sBanettePose41:
ax_pose 0, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sBanettePose42:
ax_pose 32, 0x01e8, 0x80f1, 0x5c00
ax_pose_terminator
sBanettePose43:
ax_pose 33, 0x01e9, 0x80ef, 0x5c00
ax_pose 34, 0x01e8, 0x80f1, 0x5c10
ax_pose_terminator
sBanettePose44:
ax_pose 34, 0x01e8, 0x80f1, 0x5c00
ax_pose_terminator
sBanettePose45:
ax_pose 3, 0x01e8, 0x80ec, 0x5c00
ax_pose_terminator
sBanettePose46:
ax_pose 35, 0x01e8, 0x80ef, 0x5c00
ax_pose_terminator
sBanettePose47:
ax_pose 36, 0x01e6, 0x90f1, 0x5c00
ax_pose 37, 0x01e8, 0x80ef, 0x5c10
ax_pose_terminator
sBanettePose48:
ax_pose 37, 0x01e8, 0x80ef, 0x5c00
ax_pose_terminator
sBanettePose49:
ax_pose 6, 0x01e8, 0x80ec, 0x5c00
ax_pose_terminator
sBanettePose50:
ax_pose 38, 0x01e8, 0x80ef, 0x5c00
ax_pose_terminator
sBanettePose51:
ax_pose 39, 0x81e7, 0x9100, 0x5c00
ax_pose 40, 0x01e8, 0x80ef, 0x5c08
ax_pose_terminator
sBanettePose52:
ax_pose 40, 0x01e8, 0x80ef, 0x5c00
ax_pose_terminator
sBanettePose53:
ax_pose 9, 0x01e8, 0x80ec, 0x5c00
ax_pose_terminator
sBanettePose54:
ax_pose 41, 0x01e8, 0x90ef, 0x5c00
ax_pose_terminator
sBanettePose55:
ax_pose 42, 0x81e7, 0x9103, 0x5c00
ax_pose 43, 0x01e8, 0x80ef, 0x5c08
ax_pose_terminator
sBanettePose56:
ax_pose 43, 0x01e8, 0x80ef, 0x5c00
ax_pose_terminator
sBanettePose57:
ax_pose 12, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sBanettePose58:
ax_pose 44, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sBanettePose59:
ax_pose 45, 0x01e8, 0x80f4, 0x5c00
ax_pose 46, 0x01e8, 0x80ee, 0x5c10
ax_pose_terminator
sBanettePose60:
ax_pose 45, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sBanettePose61:
ax_pose 15, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sBanettePose62:
ax_pose 41, 0x01e8, 0x80f1, 0x5c00
ax_pose_terminator
sBanettePose63:
ax_pose 42, 0x81e7, 0x80ed, 0x5c00
ax_pose 47, 0x01e8, 0x80f1, 0x5c08
ax_pose_terminator
sBanettePose64:
ax_pose 47, 0x01e8, 0x80f1, 0x5c00
ax_pose_terminator
sBanettePose65:
ax_pose 18, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sBanettePose66:
ax_pose 48, 0x01e8, 0x80f1, 0x5c00
ax_pose_terminator
sBanettePose67:
ax_pose 39, 0x81e7, 0x80f0, 0x5c00
ax_pose 49, 0x01e8, 0x80f1, 0x5c08
ax_pose_terminator
sBanettePose68:
ax_pose 49, 0x01e8, 0x80f1, 0x5c00
ax_pose_terminator
sBanettePose69:
ax_pose 21, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sBanettePose70:
ax_pose 50, 0x01e8, 0x80f1, 0x5c00
ax_pose_terminator
sBanettePose71:
ax_pose 36, 0x01e6, 0x80ef, 0x5c00
ax_pose 51, 0x01e8, 0x80f1, 0x5c10
ax_pose_terminator
sBanettePose72:
ax_pose 51, 0x01e8, 0x80f1, 0x5c00
ax_pose_terminator
sBanettePose73:
ax_pose 1, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sBanettePose74:
ax_pose 22, 0x01e8, 0x80f5, 0x5c00
ax_pose_terminator
sBanettePose75:
ax_pose 19, 0x01e8, 0x80f5, 0x5c00
ax_pose_terminator
sBanettePose76:
ax_pose 16, 0x01e8, 0x80f6, 0x5c00
ax_pose_terminator
sBanettePose77:
ax_pose 13, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sBanettePose78:
ax_pose 10, 0x01e8, 0x80eb, 0x5c00
ax_pose_terminator
sBanettePose79:
ax_pose 7, 0x01e8, 0x80ec, 0x5c00
ax_pose_terminator
sBanettePose80:
ax_pose 4, 0x01e8, 0x80ec, 0x5c00
ax_pose_terminator
sBanettePose81:
ax_pose 0, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sBanettePose82:
ax_pose 52, 0x01f0, 0x00f8, 0x5c00
ax_pose -1, 0x01f0, 0x00ff, 0x5c00
ax_pose 53, 0x01e8, 0x80f4, 0x5c01
ax_pose_terminator
sBanettePose83:
ax_pose 54, 0x01f0, 0x00f8, 0x5c00
ax_pose -1, 0x01f0, 0x00ff, 0x5c00
ax_pose 53, 0x01e8, 0x80f4, 0x5c01
ax_pose_terminator
sBanettePose84:
ax_pose 55, 0x01f0, 0x00f8, 0x5c00
ax_pose -1, 0x01f0, 0x00ff, 0x5c00
ax_pose 53, 0x01e8, 0x80f4, 0x5c01
ax_pose_terminator
sBanettePose85:
ax_pose 56, 0x01ec, 0x40f4, 0x5c00
ax_pose -1, 0x01ec, 0x40fb, 0x5c00
ax_pose 53, 0x01e8, 0x80f4, 0x5c04
ax_pose_terminator
sBanettePose86:
ax_pose 57, 0x01ec, 0x40f4, 0x5c00
ax_pose -1, 0x01ec, 0x40fb, 0x5c00
ax_pose 53, 0x01e8, 0x80f4, 0x5c04
ax_pose_terminator
sBanettePose87:
ax_pose 58, 0x01ec, 0x40f4, 0x5c00
ax_pose -1, 0x01ec, 0x40fb, 0x5c00
ax_pose 53, 0x01e8, 0x80f4, 0x5c04
ax_pose_terminator
sBanettePose88:
ax_pose 53, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sBanettePose89:
ax_pose 3, 0x01e8, 0x80ec, 0x5c00
ax_pose_terminator
sBanettePose90:
ax_pose 52, 0x01ed, 0x0103, 0x5c00
ax_pose -1, 0x01f0, 0x00fd, 0x5c00
ax_pose 3, 0x01e8, 0x80ec, 0x5c01
ax_pose_terminator
sBanettePose91:
ax_pose 54, 0x01ed, 0x0103, 0x5c00
ax_pose -1, 0x01f0, 0x00fd, 0x5c00
ax_pose 3, 0x01e8, 0x80ec, 0x5c01
ax_pose_terminator
sBanettePose92:
ax_pose 55, 0x01ed, 0x0103, 0x5c00
ax_pose -1, 0x01f0, 0x00fd, 0x5c00
ax_pose 3, 0x01e8, 0x80ec, 0x5c01
ax_pose_terminator
sBanettePose93:
ax_pose 56, 0x01e9, 0x40ff, 0x5c00
ax_pose -1, 0x01ec, 0x40f9, 0x5c00
ax_pose 3, 0x01e8, 0x80ec, 0x5c04
ax_pose_terminator
sBanettePose94:
ax_pose 57, 0x01e9, 0x40ff, 0x5c00
ax_pose -1, 0x01ec, 0x40f9, 0x5c00
ax_pose 3, 0x01e8, 0x80ec, 0x5c04
ax_pose_terminator
sBanettePose95:
ax_pose 58, 0x01e9, 0x40ff, 0x5c00
ax_pose -1, 0x01ec, 0x40f9, 0x5c00
ax_pose 3, 0x01e8, 0x80ec, 0x5c04
ax_pose_terminator
sBanettePose96:
ax_pose 3, 0x01e8, 0x80ec, 0x5c00
ax_pose_terminator
sBanettePose97:
ax_pose 6, 0x01e8, 0x80ec, 0x5c00
ax_pose_terminator
sBanettePose98:
ax_pose 52, 0x01ee, 0x0101, 0x5c00
ax_pose 6, 0x01e8, 0x80ec, 0x5c01
ax_pose -1, 0x01ec, 0x0104, 0x5c00
ax_pose_terminator
sBanettePose99:
ax_pose 54, 0x01ee, 0x0101, 0x5c00
ax_pose 6, 0x01e8, 0x80ec, 0x5c01
ax_pose -1, 0x01ec, 0x0104, 0x5c00
ax_pose_terminator
sBanettePose100:
ax_pose 55, 0x01ee, 0x0101, 0x5c00
ax_pose 6, 0x01e8, 0x80ec, 0x5c01
ax_pose -1, 0x01ec, 0x0104, 0x5c00
ax_pose_terminator
sBanettePose101:
ax_pose 56, 0x01ea, 0x40fd, 0x5c00
ax_pose 6, 0x01e8, 0x80ec, 0x5c04
ax_pose -1, 0x01e8, 0x4100, 0x5c00
ax_pose_terminator
sBanettePose102:
ax_pose 57, 0x01ea, 0x40fd, 0x5c00
ax_pose 6, 0x01e8, 0x80ec, 0x5c04
ax_pose -1, 0x01e8, 0x4100, 0x5c00
ax_pose_terminator
sBanettePose103:
ax_pose 58, 0x01ea, 0x40fd, 0x5c00
ax_pose 6, 0x01e8, 0x80ec, 0x5c04
ax_pose -1, 0x01e8, 0x4100, 0x5c00
ax_pose_terminator
sBanettePose104:
ax_pose 6, 0x01e8, 0x80ec, 0x5c00
ax_pose_terminator
sBanettePose105:
ax_pose 9, 0x01e8, 0x80ec, 0x5c00
ax_pose_terminator
sBanettePose106:
ax_pose 9, 0x01e8, 0x80ec, 0x5c00
ax_pose 52, 0x01e9, 0x00ff, 0x5c10
ax_pose -1, 0x01ec, 0x0105, 0x5c10
ax_pose_terminator
sBanettePose107:
ax_pose 9, 0x01e8, 0x80ec, 0x5c00
ax_pose 54, 0x01e9, 0x00ff, 0x5c10
ax_pose -1, 0x01ec, 0x0105, 0x5c10
ax_pose_terminator
sBanettePose108:
ax_pose 9, 0x01e8, 0x80ec, 0x5c00
ax_pose 55, 0x01e9, 0x00ff, 0x5c10
ax_pose -1, 0x01ec, 0x0105, 0x5c10
ax_pose_terminator
sBanettePose109:
ax_pose 9, 0x01e8, 0x80ec, 0x5c00
ax_pose 56, 0x01e5, 0x40fb, 0x5c10
ax_pose -1, 0x01e8, 0x4101, 0x5c10
ax_pose_terminator
sBanettePose110:
ax_pose 9, 0x01e8, 0x80ec, 0x5c00
ax_pose 57, 0x01e5, 0x40fb, 0x5c10
ax_pose -1, 0x01e8, 0x4101, 0x5c10
ax_pose_terminator
sBanettePose111:
ax_pose 9, 0x01e8, 0x80ec, 0x5c00
ax_pose 58, 0x01e5, 0x40fb, 0x5c10
ax_pose -1, 0x01e8, 0x4101, 0x5c10
ax_pose_terminator
sBanettePose112:
ax_pose 12, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sBanettePose113:
ax_pose 12, 0x01e8, 0x80f4, 0x5c00
ax_pose 52, 0x01e8, 0x00f7, 0x5c10
ax_pose -1, 0x01e8, 0x0100, 0x5c10
ax_pose_terminator
sBanettePose114:
ax_pose 12, 0x01e8, 0x80f4, 0x5c00
ax_pose 54, 0x01e8, 0x00f7, 0x5c10
ax_pose -1, 0x01e8, 0x0100, 0x5c10
ax_pose_terminator
sBanettePose115:
ax_pose 12, 0x01e8, 0x80f4, 0x5c00
ax_pose 55, 0x01e8, 0x00f7, 0x5c10
ax_pose -1, 0x01e8, 0x0100, 0x5c10
ax_pose_terminator
sBanettePose116:
ax_pose 12, 0x01e8, 0x80f4, 0x5c00
ax_pose 56, 0x01e4, 0x40f3, 0x5c10
ax_pose -1, 0x01e4, 0x40fc, 0x5c10
ax_pose_terminator
sBanettePose117:
ax_pose 12, 0x01e8, 0x80f4, 0x5c00
ax_pose 57, 0x01e4, 0x40f3, 0x5c10
ax_pose -1, 0x01e4, 0x40fc, 0x5c10
ax_pose_terminator
sBanettePose118:
ax_pose 12, 0x01e8, 0x80f4, 0x5c00
ax_pose 58, 0x01e4, 0x40f3, 0x5c10
ax_pose -1, 0x01e4, 0x40fc, 0x5c10
ax_pose_terminator
sBanettePose119:
ax_pose 15, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sBanettePose120:
ax_pose 15, 0x01e8, 0x80f4, 0x5c00
ax_pose 52, 0x01e9, 0x00f7, 0x5c10
ax_pose -1, 0x01ec, 0x00f2, 0x5c10
ax_pose_terminator
sBanettePose121:
ax_pose 15, 0x01e8, 0x80f4, 0x5c00
ax_pose 54, 0x01e9, 0x00f7, 0x5c10
ax_pose -1, 0x01ec, 0x00f2, 0x5c10
ax_pose_terminator
sBanettePose122:
ax_pose 15, 0x01e8, 0x80f4, 0x5c00
ax_pose 55, 0x01e9, 0x00f7, 0x5c10
ax_pose -1, 0x01ec, 0x00f2, 0x5c10
ax_pose_terminator
sBanettePose123:
ax_pose 15, 0x01e8, 0x80f4, 0x5c00
ax_pose 56, 0x01e5, 0x40f3, 0x5c10
ax_pose -1, 0x01e8, 0x40ee, 0x5c10
ax_pose_terminator
sBanettePose124:
ax_pose 15, 0x01e8, 0x80f4, 0x5c00
ax_pose 57, 0x01e5, 0x40f3, 0x5c10
ax_pose -1, 0x01e8, 0x40ee, 0x5c10
ax_pose_terminator
sBanettePose125:
ax_pose 15, 0x01e8, 0x80f4, 0x5c00
ax_pose 58, 0x01e5, 0x40f3, 0x5c10
ax_pose -1, 0x01e8, 0x40ee, 0x5c10
ax_pose_terminator
sBanettePose126:
ax_pose 18, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sBanettePose127:
ax_pose 52, 0x01ee, 0x00f6, 0x5c00
ax_pose 59, 0x01e8, 0x80f4, 0x5c01
ax_pose -1, 0x01ec, 0x00f3, 0x5c00
ax_pose_terminator
sBanettePose128:
ax_pose 54, 0x01ee, 0x00f6, 0x5c00
ax_pose 59, 0x01e8, 0x80f4, 0x5c01
ax_pose -1, 0x01ec, 0x00f3, 0x5c00
ax_pose_terminator
sBanettePose129:
ax_pose 55, 0x01ee, 0x00f6, 0x5c00
ax_pose 59, 0x01e8, 0x80f4, 0x5c01
ax_pose -1, 0x01ec, 0x00f3, 0x5c00
ax_pose_terminator
sBanettePose130:
ax_pose 56, 0x01ea, 0x40f2, 0x5c00
ax_pose 59, 0x01e8, 0x80f4, 0x5c04
ax_pose -1, 0x01e8, 0x40ef, 0x5c00
ax_pose_terminator
sBanettePose131:
ax_pose 57, 0x01ea, 0x40f2, 0x5c00
ax_pose 59, 0x01e8, 0x80f4, 0x5c04
ax_pose -1, 0x01e8, 0x40ef, 0x5c00
ax_pose_terminator
sBanettePose132:
ax_pose 58, 0x01ea, 0x40f2, 0x5c00
ax_pose 59, 0x01e8, 0x80f4, 0x5c04
ax_pose -1, 0x01e8, 0x40ef, 0x5c00
ax_pose_terminator
sBanettePose133:
ax_pose 59, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sBanettePose134:
ax_pose 21, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sBanettePose135:
ax_pose 52, 0x01ed, 0x00f5, 0x5c00
ax_pose -1, 0x01f0, 0x00fa, 0x5c00
ax_pose 60, 0x01e8, 0x80f4, 0x5c01
ax_pose_terminator
sBanettePose136:
ax_pose 54, 0x01ed, 0x00f5, 0x5c00
ax_pose -1, 0x01f0, 0x00fa, 0x5c00
ax_pose 60, 0x01e8, 0x80f4, 0x5c01
ax_pose_terminator
sBanettePose137:
ax_pose 55, 0x01ed, 0x00f5, 0x5c00
ax_pose -1, 0x01f0, 0x00fa, 0x5c00
ax_pose 60, 0x01e8, 0x80f4, 0x5c01
ax_pose_terminator
sBanettePose138:
ax_pose 56, 0x01e9, 0x40f1, 0x5c00
ax_pose -1, 0x01ec, 0x40f6, 0x5c00
ax_pose 60, 0x01e8, 0x80f4, 0x5c04
ax_pose_terminator
sBanettePose139:
ax_pose 57, 0x01e9, 0x40f1, 0x5c00
ax_pose -1, 0x01ec, 0x40f6, 0x5c00
ax_pose 60, 0x01e8, 0x80f4, 0x5c04
ax_pose_terminator
sBanettePose140:
ax_pose 58, 0x01e9, 0x40f1, 0x5c00
ax_pose -1, 0x01ec, 0x40f6, 0x5c00
ax_pose 60, 0x01e8, 0x80f4, 0x5c04
ax_pose_terminator
sBanettePose141:
ax_pose 60, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sBanettePose142:
ax_pose 61, 0x01ec, 0x80f5, 0x5c00
ax_pose_terminator
sBanettePose143:
ax_pose 62, 0x01ec, 0x80f5, 0x5c00
ax_pose_terminator
sBanettePose144:
ax_pose 63, 0x01e0, 0x80f0, 0x5c00
ax_pose_terminator
sBanettePose145:
ax_pose 64, 0x01e1, 0x80eb, 0x5c00
ax_pose_terminator
sBanettePose146:
ax_pose 65, 0x01e3, 0x80e8, 0x5c00
ax_pose_terminator
sBanettePose147:
ax_pose 66, 0x01e4, 0x90e8, 0x5c00
ax_pose_terminator
sBanettePose148:
ax_pose 67, 0x01e4, 0x80f0, 0x5c00
ax_pose_terminator
sBanettePose149:
ax_pose 66, 0x01e4, 0x80f8, 0x5c00
ax_pose_terminator
sBanettePose150:
ax_pose 68, 0x01e3, 0x80f8, 0x5c00
ax_pose_terminator
sBanettePose151:
ax_pose 69, 0x01e1, 0x80f5, 0x5c00
ax_pose_terminator
sBanettePose152:
ax_pose 0, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sBanettePose153:
ax_pose 1, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sBanettePose154:
ax_pose 2, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sBanettePose155:
ax_pose 3, 0x01e8, 0x80ec, 0x5c00
ax_pose_terminator
sBanettePose156:
ax_pose 4, 0x01e8, 0x80ec, 0x5c00
ax_pose_terminator
sBanettePose157:
ax_pose 5, 0x01e8, 0x80ec, 0x5c00
ax_pose_terminator
sBanettePose158:
ax_pose 6, 0x01e8, 0x80ec, 0x5c00
ax_pose_terminator
sBanettePose159:
ax_pose 7, 0x01e8, 0x80ec, 0x5c00
ax_pose_terminator
sBanettePose160:
ax_pose 8, 0x01e8, 0x80ec, 0x5c00
ax_pose_terminator
sBanettePose161:
ax_pose 9, 0x01e8, 0x80ec, 0x5c00
ax_pose_terminator
sBanettePose162:
ax_pose 10, 0x01e8, 0x80ec, 0x5c00
ax_pose_terminator
sBanettePose163:
ax_pose 11, 0x01e8, 0x80ec, 0x5c00
ax_pose_terminator
sBanettePose164:
ax_pose 12, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sBanettePose165:
ax_pose 13, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sBanettePose166:
ax_pose 14, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sBanettePose167:
ax_pose 15, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sBanettePose168:
ax_pose 16, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sBanettePose169:
ax_pose 17, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sBanettePose170:
ax_pose 18, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sBanettePose171:
ax_pose 19, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sBanettePose172:
ax_pose 20, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sBanettePose173:
ax_pose 21, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sBanettePose174:
ax_pose 22, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sBanettePose175:
ax_pose 23, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sBanettePose176:
ax_pose 24, 0x01e7, 0x80f1, 0x5c00
ax_pose_terminator
sBanettePose177:
ax_pose 31, 0x01e8, 0x80f0, 0x5c00
ax_pose_terminator
sBanettePose178:
ax_pose 30, 0x01e8, 0x80f2, 0x5c00
ax_pose_terminator
sBanettePose179:
ax_pose 29, 0x01e9, 0x80f1, 0x5c00
ax_pose_terminator
sBanettePose180:
ax_pose 28, 0x01e9, 0x80f4, 0x5c00
ax_pose_terminator
sBanettePose181:
ax_pose 27, 0x01e9, 0x80ef, 0x5c00
ax_pose_terminator
sBanettePose182:
ax_pose 26, 0x01e8, 0x80ee, 0x5c00
ax_pose_terminator
sBanettePose183:
ax_pose 25, 0x01e8, 0x80f0, 0x5c00
ax_pose_terminator
sBanettePose184:
ax_pose 24, 0x01e6, 0x80f1, 0x5c00
ax_pose_terminator
sBanettePose185:
ax_pose 25, 0x01e7, 0x80ef, 0x5c00
ax_pose_terminator
sBanettePose186:
ax_pose 26, 0x01e7, 0x80ed, 0x5c00
ax_pose_terminator
sBanettePose187:
ax_pose 27, 0x01e9, 0x80ef, 0x5c00
ax_pose_terminator
sBanettePose188:
ax_pose 28, 0x01e9, 0x80f4, 0x5c00
ax_pose_terminator
sBanettePose189:
ax_pose 29, 0x01e9, 0x80f1, 0x5c00
ax_pose_terminator
sBanettePose190:
ax_pose 30, 0x01e7, 0x80f3, 0x5c00
ax_pose_terminator
sBanettePose191:
ax_pose 31, 0x01e7, 0x80f1, 0x5c00
ax_pose_terminator
sBanettePose192:
ax_pose 0, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sBanettePose193:
ax_pose 24, 0x01e6, 0x80f1, 0x5c00
ax_pose_terminator
sBanettePose194:
ax_pose 3, 0x01e8, 0x80ec, 0x5c00
ax_pose_terminator
sBanettePose195:
ax_pose 25, 0x01e7, 0x80ef, 0x5c00
ax_pose_terminator
sBanettePose196:
ax_pose 6, 0x01e8, 0x80ec, 0x5c00
ax_pose_terminator
sBanettePose197:
ax_pose 26, 0x01e7, 0x80ed, 0x5c00
ax_pose_terminator
sBanettePose198:
ax_pose 9, 0x01e8, 0x80ec, 0x5c00
ax_pose_terminator
sBanettePose199:
ax_pose 27, 0x01e9, 0x80ef, 0x5c00
ax_pose_terminator
sBanettePose200:
ax_pose 12, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sBanettePose201:
ax_pose 28, 0x01e9, 0x80f4, 0x5c00
ax_pose_terminator
sBanettePose202:
ax_pose 15, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sBanettePose203:
ax_pose 29, 0x01e9, 0x80f1, 0x5c00
ax_pose_terminator
sBanettePose204:
ax_pose 18, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sBanettePose205:
ax_pose 30, 0x01e7, 0x80f3, 0x5c00
ax_pose_terminator
sBanettePose206:
ax_pose 21, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sBanettePose207:
ax_pose 31, 0x01e7, 0x80f1, 0x5c00
ax_pose_terminator
sBanettePose208:
ax_pose 0, 0x01eb, 0x80f4, 0x5c00
ax_pose_terminator
sBanettePose209:
ax_pose 21, 0x01eb, 0x80f4, 0x5c00
ax_pose_terminator
sBanettePose210:
ax_pose 18, 0x01eb, 0x80f4, 0x5c00
ax_pose_terminator
sBanettePose211:
ax_pose 15, 0x01eb, 0x80f4, 0x5c00
ax_pose_terminator
sBanettePose212:
ax_pose 12, 0x01eb, 0x80f4, 0x5c00
ax_pose_terminator
sBanettePose213:
ax_pose 9, 0x01eb, 0x80ec, 0x5c00
ax_pose_terminator
sBanettePose214:
ax_pose 6, 0x01eb, 0x80ec, 0x5c00
ax_pose_terminator
sBanettePose215:
ax_pose 3, 0x01eb, 0x80ec, 0x5c00
ax_pose_terminator
sBanettePose216:
ax_pose 0, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sBanettePose217:
ax_pose 21, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sBanettePose218:
ax_pose 18, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sBanettePose219:
ax_pose 15, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sBanettePose220:
ax_pose 12, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sBanettePose221:
ax_pose 9, 0x01e8, 0x80ec, 0x5c00
ax_pose_terminator
sBanettePose222:
ax_pose 6, 0x01e8, 0x80ec, 0x5c00
ax_pose_terminator
sBanettePose223:
ax_pose 3, 0x01e8, 0x80ec, 0x5c00
ax_pose_terminator
.align 2
sBanetteAnims_1_1:
ax_anim 8, 0, 0, 0, 0, 0, 0,
ax_anim 10, 0, 1, 0, 0, 0, 0,
ax_anim 8, 0, 0, 0, 0, 0, 0,
ax_anim 10, 0, 2, 0, 0, 0, 0,
ax_anim_terminator
sBanetteAnims_1_2:
ax_anim 8, 0, 3, 0, 0, 0, 0,
ax_anim 10, 0, 4, 0, 0, 0, 0,
ax_anim 8, 0, 3, 0, 0, 0, 0,
ax_anim 10, 0, 5, 0, 0, 0, 0,
ax_anim_terminator
sBanetteAnims_1_3:
ax_anim 8, 0, 6, 0, 0, 0, 0,
ax_anim 10, 0, 7, 0, 0, 0, 0,
ax_anim 8, 0, 6, 0, 0, 0, 0,
ax_anim 10, 0, 8, 0, 0, 0, 0,
ax_anim_terminator
sBanetteAnims_1_4:
ax_anim 8, 0, 9, 0, 0, 0, 0,
ax_anim 10, 0, 10, 0, 0, 0, 0,
ax_anim 8, 0, 9, 0, 0, 0, 0,
ax_anim 10, 0, 11, 0, 0, 0, 0,
ax_anim_terminator
sBanetteAnims_1_5:
ax_anim 8, 0, 12, 0, 0, 0, 0,
ax_anim 10, 0, 13, 0, 0, 0, 0,
ax_anim 8, 0, 12, 0, 0, 0, 0,
ax_anim 10, 0, 14, 0, 0, 0, 0,
ax_anim_terminator
sBanetteAnims_1_6:
ax_anim 8, 0, 15, 0, 0, 0, 0,
ax_anim 10, 0, 16, 0, 0, 0, 0,
ax_anim 8, 0, 15, 0, 0, 0, 0,
ax_anim 10, 0, 17, 0, 0, 0, 0,
ax_anim_terminator
sBanetteAnims_1_7:
ax_anim 8, 0, 18, 0, 0, 0, 0,
ax_anim 10, 0, 19, 0, 0, 0, 0,
ax_anim 8, 0, 18, 0, 0, 0, 0,
ax_anim 10, 0, 20, 0, 0, 0, 0,
ax_anim_terminator
sBanetteAnims_1_8:
ax_anim 8, 0, 21, 0, 0, 0, 0,
ax_anim 10, 0, 22, 0, 0, 0, 0,
ax_anim 8, 0, 21, 0, 0, 0, 0,
ax_anim 10, 0, 23, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sBanetteAnims_2_1:
ax_anim 2, 0, 24, 0, -1, 0, -1,
ax_anim 4, 0, 24, 0, -2, 0, -2,
ax_anim 1, 0, 25, 0, 0, 0, 0,
ax_anim 1, 2, 25, 0, 6, 0, 5,
ax_anim 1, 0, 25, 0, 12, 0, 10,
ax_anim 2, 0, 25, 0, 26, 0, 22,
ax_anim 2, 1, 25, 1, 26, 1, 22,
ax_anim 2, 0, 25, 0, 26, 0, 22,
ax_anim 2, 0, 25, 1, 26, 1, 22,
ax_anim 2, 0, 24, 0, 9, 0, 9,
ax_anim_terminator
sBanetteAnims_2_2:
ax_anim 2, 0, 26, -1, -1, -1, -1,
ax_anim 4, 0, 26, -2, -2, -2, -2,
ax_anim 1, 0, 27, 0, 0, 0, 0,
ax_anim 1, 2, 27, 3, 6, 3, 3,
ax_anim 1, 0, 27, 9, 14, 9, 9,
ax_anim 2, 0, 27, 18, 26, 18, 18,
ax_anim 2, 1, 27, 19, 25, 19, 17,
ax_anim 2, 0, 27, 18, 26, 18, 18,
ax_anim 2, 0, 27, 19, 25, 19, 17,
ax_anim 2, 0, 26, 5, 5, 5, 5,
ax_anim_terminator
sBanetteAnims_2_3:
ax_anim 2, 0, 28, -1, 0, -1, 0,
ax_anim 4, 0, 28, -2, 0, -2, 0,
ax_anim 1, 0, 29, 0, 0, 0, 0,
ax_anim 1, 2, 29, 4, 1, 4, 0,
ax_anim 1, 0, 29, 10, 3, 10, 0,
ax_anim 2, 0, 29, 18, 5, 18, 0,
ax_anim 2, 1, 29, 18, 6, 18, 1,
ax_anim 2, 0, 29, 18, 5, 18, 0,
ax_anim 2, 0, 29, 18, 6, 18, 1,
ax_anim 2, 0, 28, 6, 2, 6, 0,
ax_anim_terminator
sBanetteAnims_2_4:
ax_anim 2, 0, 30, -1, 1, -1, 1,
ax_anim 4, 0, 30, -2, 2, -2, 2,
ax_anim 1, 0, 31, 0, -1, 0, -1,
ax_anim 1, 2, 31, 5, -5, 5, -5,
ax_anim 1, 0, 31, 11, -10, 11, -11,
ax_anim 2, 0, 31, 17, -14, 17, -17,
ax_anim 2, 1, 31, 18, -13, 18, -16,
ax_anim 2, 0, 31, 17, -14, 17, -17,
ax_anim 2, 0, 31, 18, -13, 18, -16,
ax_anim 2, 0, 30, 6, -6, 6, -6,
ax_anim_terminator
sBanetteAnims_2_5:
ax_anim 2, 0, 32, 0, 1, 0, 1,
ax_anim 4, 0, 32, 0, 2, 0, 2,
ax_anim 1, 0, 33, 0, 0, 0, 0,
ax_anim 1, 2, 33, 0, -4, 0, -4,
ax_anim 1, 0, 33, 0, -11, 0, -14,
ax_anim 2, 0, 33, 0, -16, 0, -22,
ax_anim 2, 1, 33, 1, -16, 1, -22,
ax_anim 2, 0, 33, 0, -16, 0, -22,
ax_anim 2, 0, 33, 1, -16, 1, -22,
ax_anim 2, 0, 32, 0, -6, 0, -8,
ax_anim_terminator
sBanetteAnims_2_6:
ax_anim 2, 0, 34, 1, 1, 1, 1,
ax_anim 4, 0, 34, 2, 2, 2, 2,
ax_anim 1, 0, 35, 0, -1, 0, -1,
ax_anim 1, 2, 35, -5, -5, -5, -5,
ax_anim 1, 0, 35, -11, -10, -11, -11,
ax_anim 2, 0, 35, -17, -14, -17, -17,
ax_anim 2, 1, 35, -18, -13, -18, -16,
ax_anim 2, 0, 35, -17, -14, -17, -17,
ax_anim 2, 0, 35, -18, -13, -18, -16,
ax_anim 2, 0, 34, -6, -6, -6, -6,
ax_anim_terminator
sBanetteAnims_2_7:
ax_anim 2, 0, 36, 1, 0, 1, 0,
ax_anim 4, 0, 36, 2, 0, 2, 0,
ax_anim 1, 0, 37, 0, 0, 0, 0,
ax_anim 1, 2, 37, -4, 1, -4, 0,
ax_anim 1, 0, 37, -10, 3, -10, 0,
ax_anim 2, 0, 37, -18, 5, -18, 0,
ax_anim 2, 1, 37, -18, 6, -18, 1,
ax_anim 2, 0, 37, -18, 5, -18, 0,
ax_anim 2, 0, 37, -18, 6, -18, 1,
ax_anim 2, 0, 36, -6, 2, -6, 0,
ax_anim_terminator
sBanetteAnims_2_8:
ax_anim 2, 0, 38, 1, -1, 1, -1,
ax_anim 4, 0, 38, 2, -2, 2, -2,
ax_anim 1, 0, 39, 0, 0, 0, 0,
ax_anim 1, 2, 39, -3, 6, -3, 3,
ax_anim 1, 0, 39, -9, 14, -9, 9,
ax_anim 2, 0, 39, -18, 26, -18, 18,
ax_anim 2, 1, 39, -19, 25, -19, 17,
ax_anim 2, 0, 39, -18, 26, -18, 18,
ax_anim 2, 0, 39, -19, 25, -19, 17,
ax_anim 2, 0, 38, -5, 5, -5, 5,
ax_anim_terminator
.align 2
sBanetteAnims_3_1:
ax_anim 2, 0, 40, 0, -2, 0, -2,
ax_anim 2, 0, 41, 0, -3, 0, -3,
ax_anim 6, 0, 41, 0, -4, 0, -4,
ax_anim 1, 2, 41, 0, 2, 0, 2,
ax_anim 1, 0, 41, 0, 12, 0, 12,
ax_anim 2, 0, 42, 0, 23, 0, 23,
ax_anim 1, 1, 43, 2, 24, 2, 24,
ax_anim 1, 0, 48, 4, 24, 4, 24,
ax_anim 1, 0, 52, 6, 18, 6, 18,
ax_anim 2, 0, 56, 7, 13, 7, 13,
ax_anim 2, 0, 60, 4, 6, 4, 6,
ax_anim 2, 0, 64, 2, 4, 2, 4,
ax_anim 2, 0, 68, 0, 0, 0, 0,
ax_anim 2, 0, 40, 0, 0, 0, 0,
ax_anim_terminator
sBanetteAnims_3_2:
ax_anim 2, 0, 44, -2, -2, -2, -2,
ax_anim 2, 0, 45, -3, -3, -3, -3,
ax_anim 6, 0, 45, -4, -4, -4, -4,
ax_anim 1, 2, 45, 2, 2, 2, 2,
ax_anim 1, 0, 45, 11, 13, 11, 13,
ax_anim 2, 0, 46, 20, 23, 20, 23,
ax_anim 1, 1, 47, 18, 24, 18, 24,
ax_anim 1, 0, 68, 16, 26, 16, 26,
ax_anim 1, 0, 64, 9, 20, 9, 20,
ax_anim 2, 0, 60, 4, 16, 4, 16,
ax_anim 2, 0, 56, 0, 9, 0, 9,
ax_anim 2, 0, 52, -1, 4, -1, 4,
ax_anim 2, 0, 48, 0, 0, 0, 0,
ax_anim 2, 0, 44, 0, 0, 0, 0,
ax_anim_terminator
sBanetteAnims_3_3:
ax_anim 2, 0, 48, -2, 0, -2, 0,
ax_anim 2, 0, 49, -3, 0, -3, 0,
ax_anim 6, 0, 49, -4, 0, -4, 0,
ax_anim 1, 2, 49, 2, 0, 2, 0,
ax_anim 1, 0, 49, 11, 0, 11, 0,
ax_anim 2, 0, 50, 20, 0, 20, 0,
ax_anim 1, 1, 51, 21, 3, 21, 3,
ax_anim 1, 0, 40, 19, 8, 19, 8,
ax_anim 1, 0, 68, 15, 11, 15, 11,
ax_anim 2, 0, 64, 9, 10, 9, 10,
ax_anim 2, 0, 60, 4, 5, 4, 5,
ax_anim 2, 0, 56, 1, 3, 1, 3,
ax_anim 2, 0, 52, 0, 0, 0, 0,
ax_anim 2, 0, 48, 0, 0, 0, 0,
ax_anim_terminator
sBanetteAnims_3_4:
ax_anim 2, 0, 52, -2, 2, -2, 2,
ax_anim 2, 0, 53, -3, 3, -3, 3,
ax_anim 6, 0, 53, -4, 4, -4, 4,
ax_anim 1, 2, 53, 2, -2, 2, -2,
ax_anim 1, 0, 53, 12, -10, 12, -10,
ax_anim 2, 0, 54, 18, -14, 18, -14,
ax_anim 1, 1, 55, 20, -12, 20, -12,
ax_anim 1, 0, 44, 21, -7, 21, -7,
ax_anim 1, 0, 40, 20, -4, 20, -4,
ax_anim 2, 0, 68, 17, -2, 17, -2,
ax_anim 2, 0, 64, 9, -1, 9, -1,
ax_anim 2, 0, 60, 4, 0, 4, 0,
ax_anim 2, 0, 56, 0, 0, 0, 0,
ax_anim 2, 0, 52, 0, 0, 0, 0,
ax_anim_terminator
sBanetteAnims_3_5:
ax_anim 2, 0, 56, 0, 2, 0, 2,
ax_anim 2, 0, 57, 0, 3, 0, 3,
ax_anim 6, 0, 57, 0, 4, 0, 4,
ax_anim 1, 2, 57, 0, -2, 0, -2,
ax_anim 1, 0, 57, 0, -12, 0, -12,
ax_anim 2, 0, 58, 0, -15, 0, -15,
ax_anim 1, 1, 59, -2, -16, -2, -16,
ax_anim 1, 0, 64, -5, -16, -5, -16,
ax_anim 1, 0, 68, -6, -13, -6, -13,
ax_anim 2, 0, 40, -8, -9, -8, -9,
ax_anim 2, 0, 44, -6, -4, -6, -4,
ax_anim 2, 0, 48, -2, -2, -2, -2,
ax_anim 2, 0, 52, 0, 0, 0, 0,
ax_anim 2, 0, 56, 0, 0, 0, 0,
ax_anim_terminator
sBanetteAnims_3_6:
ax_anim 2, 0, 60, 2, 2, 2, 2,
ax_anim 2, 0, 61, 3, 3, 3, 3,
ax_anim 6, 0, 61, 4, 4, 4, 4,
ax_anim 1, 2, 61, -2, -2, -2, -2,
ax_anim 1, 0, 61, -12, -10, -12, -10,
ax_anim 2, 0, 62, -18, -14, -18, -14,
ax_anim 1, 1, 63, -20, -12, -20, -12,
ax_anim 1, 0, 68, -21, -7, -21, -7,
ax_anim 1, 0, 40, -20, -4, -20, -4,
ax_anim 2, 0, 44, -17, -2, -17, -2,
ax_anim 2, 0, 48, -9, -1, -9, -1,
ax_anim 2, 0, 52, -4, 0, -4, 0,
ax_anim 2, 0, 56, 0, 0, 0, 0,
ax_anim 2, 0, 60, 0, 0, 0, 0,
ax_anim_terminator
sBanetteAnims_3_7:
ax_anim 2, 0, 64, 2, 0, 2, 0,
ax_anim 2, 0, 65, 3, 0, 3, 0,
ax_anim 6, 0, 65, 4, 0, 4, 0,
ax_anim 1, 2, 65, -2, 0, -2, 0,
ax_anim 1, 0, 65, -11, 0, -11, 0,
ax_anim 2, 0, 66, -20, 0, -20, 0,
ax_anim 1, 1, 67, -21, 3, -21, 3,
ax_anim 1, 0, 40, -19, 8, -19, 8,
ax_anim 1, 0, 44, -15, 11, -15, 11,
ax_anim 2, 0, 48, -9, 10, -9, 10,
ax_anim 2, 0, 52, -4, 5, -4, 5,
ax_anim 2, 0, 56, -1, 3, -1, 3,
ax_anim 2, 0, 60, 0, 0, 0, 0,
ax_anim 2, 0, 64, 0, 0, 0, 0,
ax_anim_terminator
sBanetteAnims_3_8:
ax_anim 2, 0, 68, 2, -2, 2, -2,
ax_anim 2, 0, 69, 3, -3, 3, -3,
ax_anim 6, 0, 69, 4, -4, 4, -4,
ax_anim 1, 2, 69, -2, 2, -2, 2,
ax_anim 1, 0, 69, -11, 13, -11, 13,
ax_anim 2, 0, 70, -20, 23, -20, 23,
ax_anim 1, 1, 71, -18, 24, -18, 24,
ax_anim 1, 0, 44, -16, 26, -16, 26,
ax_anim 1, 0, 48, -9, 20, -9, 20,
ax_anim 2, 0, 52, -4, 16, -4, 16,
ax_anim 2, 0, 56, 0, 9, 0, 9,
ax_anim 2, 0, 60, 1, 4, 1, 4,
ax_anim 2, 0, 64, 0, 0, 0, 0,
ax_anim 2, 0, 68, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sBanetteAnims_4_1:
ax_anim 2, 0, 72, 1, 0, 1, 0,
ax_anim 2, 0, 72, 0, 0, 0, 0,
ax_anim 2, 0, 72, 1, 0, 1, 0,
ax_anim 2, 0, 72, 0, 0, 0, 0,
ax_anim 2, 0, 72, 1, 0, 1, 0,
ax_anim 2, 2, 72, 0, 0, 0, 0,
ax_anim 2, 0, 72, 1, 0, 1, 0,
ax_anim 2, 0, 72, 0, 0, 0, 0,
ax_anim 2, 0, 72, 1, 0, 1, 0,
ax_anim 2, 1, 72, 0, 0, 0, 0,
ax_anim_terminator
sBanetteAnims_4_2:
ax_anim 2, 0, 79, 1, -1, 1, -1,
ax_anim 2, 0, 79, 0, 0, 0, 0,
ax_anim 2, 0, 79, 1, -1, 1, -1,
ax_anim 2, 0, 79, 0, 0, 0, 0,
ax_anim 2, 0, 79, 1, -1, 1, -1,
ax_anim 2, 2, 79, 0, 0, 0, 0,
ax_anim 2, 0, 79, 1, -1, 1, -1,
ax_anim 2, 0, 79, 0, 0, 0, 0,
ax_anim 2, 0, 79, 1, -1, 1, -1,
ax_anim 2, 1, 79, 0, 0, 0, 0,
ax_anim_terminator
sBanetteAnims_4_3:
ax_anim 2, 0, 78, 0, -1, 0, -1,
ax_anim 2, 0, 78, 0, 0, 0, 0,
ax_anim 2, 0, 78, 0, -1, 0, -1,
ax_anim 2, 0, 78, 0, 0, 0, 0,
ax_anim 2, 0, 78, 0, -1, 0, -1,
ax_anim 2, 2, 78, 0, 0, 0, 0,
ax_anim 2, 0, 78, 0, -1, 0, -1,
ax_anim 2, 0, 78, 0, 0, 0, 0,
ax_anim 2, 0, 78, 0, -1, 0, -1,
ax_anim 2, 1, 78, 0, 0, 0, 0,
ax_anim_terminator
sBanetteAnims_4_4:
ax_anim 2, 0, 77, -1, -1, -1, -1,
ax_anim 2, 0, 77, 0, 0, 0, 0,
ax_anim 2, 0, 77, -1, -1, -1, -1,
ax_anim 2, 0, 77, 0, 0, 0, 0,
ax_anim 2, 0, 77, -1, -1, -1, -1,
ax_anim 2, 2, 77, 0, 0, 0, 0,
ax_anim 2, 0, 77, -1, -1, -1, -1,
ax_anim 2, 0, 77, 0, 0, 0, 0,
ax_anim 2, 0, 77, -1, -1, -1, -1,
ax_anim 2, 1, 77, 0, 0, 0, 0,
ax_anim_terminator
sBanetteAnims_4_5:
ax_anim 2, 0, 76, 1, 0, 1, 0,
ax_anim 2, 0, 76, 0, 0, 0, 0,
ax_anim 2, 0, 76, 1, 0, 1, 0,
ax_anim 2, 0, 76, 0, 0, 0, 0,
ax_anim 2, 0, 76, 1, 0, 1, 0,
ax_anim 2, 2, 76, 0, 0, 0, 0,
ax_anim 2, 0, 76, 1, 0, 1, 0,
ax_anim 2, 0, 76, 0, 0, 0, 0,
ax_anim 2, 0, 76, 1, 0, 1, 0,
ax_anim 2, 1, 76, 0, 0, 0, 0,
ax_anim_terminator
sBanetteAnims_4_6:
ax_anim 2, 0, 75, 1, -1, 1, -1,
ax_anim 2, 0, 75, 0, 0, 0, 0,
ax_anim 2, 0, 75, 1, -1, 1, -1,
ax_anim 2, 0, 75, 0, 0, 0, 0,
ax_anim 2, 0, 75, 1, -1, 1, -1,
ax_anim 2, 2, 75, 0, 0, 0, 0,
ax_anim 2, 0, 75, 1, -1, 1, -1,
ax_anim 2, 0, 75, 0, 0, 0, 0,
ax_anim 2, 0, 75, 1, -1, 1, -1,
ax_anim 2, 1, 75, 0, 0, 0, 0,
ax_anim_terminator
sBanetteAnims_4_7:
ax_anim 2, 0, 74, 0, -1, 0, -1,
ax_anim 2, 0, 74, 0, 0, 0, 0,
ax_anim 2, 0, 74, 0, -1, 0, -1,
ax_anim 2, 0, 74, 0, 0, 0, 0,
ax_anim 2, 0, 74, 0, -1, 0, -1,
ax_anim 2, 2, 74, 0, 0, 0, 0,
ax_anim 2, 0, 74, 0, -1, 0, -1,
ax_anim 2, 0, 74, 0, 0, 0, 0,
ax_anim 2, 0, 74, 0, -1, 0, -1,
ax_anim 2, 1, 74, 0, 0, 0, 0,
ax_anim_terminator
sBanetteAnims_4_8:
ax_anim 2, 0, 73, -1, -1, -1, -1,
ax_anim 2, 0, 73, 0, 0, 0, 0,
ax_anim 2, 0, 73, -1, -1, -1, -1,
ax_anim 2, 0, 73, 0, 0, 0, 0,
ax_anim 2, 0, 73, -1, -1, -1, -1,
ax_anim 2, 2, 73, 0, 0, 0, 0,
ax_anim 2, 0, 73, -1, -1, -1, -1,
ax_anim 2, 0, 73, 0, 0, 0, 0,
ax_anim 2, 0, 73, -1, -1, -1, -1,
ax_anim 2, 1, 73, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sBanetteAnims_5_1:
ax_anim 3, 0, 88, 0, 0, 0, 0,
ax_anim 3, 0, 96, 0, 0, 0, 0,
ax_anim 2, 0, 104, 0, 0, 0, 0,
ax_anim 2, 0, 111, 0, 0, 0, 0,
ax_anim 1, 0, 118, 0, 0, 0, 0,
ax_anim 1, 0, 125, 0, 0, 0, 0,
ax_anim 1, 0, 133, 0, 0, 0, 0,
ax_anim 6, 0, 80, 0, 0, 0, 0,
ax_anim 3, 0, 87, 0, 0, 0, 0,
ax_anim 1, 0, 85, 0, 0, 0, 0,
ax_anim 1, 2, 86, 0, 0, 0, 0,
ax_anim 1, 0, 85, 0, 0, 0, 0,
ax_anim 1, 0, 83, 0, 0, 0, 0,
ax_anim 1, 0, 86, 0, 0, 0, 0,
ax_anim 1, 0, 85, 0, 0, 0, 0,
ax_anim 1, 0, 84, 0, 0, 0, 0,
ax_anim 1, 1, 82, 0, 0, 0, 0,
ax_anim 1, 0, 80, 0, 0, 0, 0,
ax_anim_terminator
sBanetteAnims_5_2:
ax_anim 3, 0, 96, 0, 0, 0, 0,
ax_anim 3, 0, 104, 0, 0, 0, 0,
ax_anim 2, 0, 111, 0, 0, 0, 0,
ax_anim 2, 0, 118, 0, 0, 0, 0,
ax_anim 1, 0, 125, 0, 0, 0, 0,
ax_anim 1, 0, 133, 0, 0, 0, 0,
ax_anim 1, 0, 80, 0, 0, 0, 0,
ax_anim 6, 0, 88, 0, 0, 0, 0,
ax_anim 3, 0, 95, 0, 0, 0, 0,
ax_anim 1, 0, 93, 0, 0, 0, 0,
ax_anim 1, 2, 94, 0, 0, 0, 0,
ax_anim 1, 0, 93, 0, 0, 0, 0,
ax_anim 1, 0, 91, 0, 0, 0, 0,
ax_anim 1, 0, 94, 0, 0, 0, 0,
ax_anim 1, 0, 93, 0, 0, 0, 0,
ax_anim 1, 0, 92, 0, 0, 0, 0,
ax_anim 1, 1, 90, 0, 0, 0, 0,
ax_anim 1, 0, 88, 0, 0, 0, 0,
ax_anim_terminator
sBanetteAnims_5_3:
ax_anim 3, 0, 104, 0, 0, 0, 0,
ax_anim 3, 0, 111, 0, 0, 0, 0,
ax_anim 2, 0, 118, 0, 0, 0, 0,
ax_anim 2, 0, 125, 0, 0, 0, 0,
ax_anim 1, 0, 133, 0, 0, 0, 0,
ax_anim 1, 0, 80, 0, 0, 0, 0,
ax_anim 1, 0, 88, 0, 0, 0, 0,
ax_anim 6, 0, 96, 0, 0, 0, 0,
ax_anim 3, 0, 103, 0, 0, 0, 0,
ax_anim 1, 0, 101, 0, 0, 0, 0,
ax_anim 1, 2, 102, 0, 0, 0, 0,
ax_anim 1, 0, 101, 0, 0, 0, 0,
ax_anim 1, 0, 99, 0, 0, 0, 0,
ax_anim 1, 0, 102, 0, 0, 0, 0,
ax_anim 1, 0, 101, 0, 0, 0, 0,
ax_anim 1, 0, 100, 0, 0, 0, 0,
ax_anim 1, 1, 98, 0, 0, 0, 0,
ax_anim 1, 0, 96, 0, 0, 0, 0,
ax_anim_terminator
sBanetteAnims_5_4:
ax_anim 3, 0, 111, 0, 0, 0, 0,
ax_anim 3, 0, 118, 0, 0, 0, 0,
ax_anim 2, 0, 125, 0, 0, 0, 0,
ax_anim 2, 0, 133, 0, 0, 0, 0,
ax_anim 1, 0, 80, 0, 0, 0, 0,
ax_anim 1, 0, 88, 0, 0, 0, 0,
ax_anim 1, 0, 96, 0, 0, 0, 0,
ax_anim 6, 0, 104, 0, 0, 0, 0,
ax_anim 3, 0, 104, 0, 0, 0, 0,
ax_anim 1, 0, 109, 0, 0, 0, 0,
ax_anim 1, 2, 110, 0, 0, 0, 0,
ax_anim 1, 0, 109, 0, 0, 0, 0,
ax_anim 1, 0, 107, 0, 0, 0, 0,
ax_anim 1, 0, 110, 0, 0, 0, 0,
ax_anim 1, 0, 109, 0, 0, 0, 0,
ax_anim 1, 0, 108, 0, 0, 0, 0,
ax_anim 1, 1, 106, 0, 0, 0, 0,
ax_anim 1, 0, 104, 0, 0, 0, 0,
ax_anim_terminator
sBanetteAnims_5_5:
ax_anim 3, 0, 118, 0, 0, 0, 0,
ax_anim 3, 0, 125, 0, 0, 0, 0,
ax_anim 2, 0, 133, 0, 0, 0, 0,
ax_anim 2, 0, 80, 0, 0, 0, 0,
ax_anim 1, 0, 88, 0, 0, 0, 0,
ax_anim 1, 0, 96, 0, 0, 0, 0,
ax_anim 1, 0, 104, 0, 0, 0, 0,
ax_anim 6, 0, 111, 0, 0, 0, 0,
ax_anim 3, 0, 111, 0, 0, 0, 0,
ax_anim 1, 0, 116, 0, 0, 0, 0,
ax_anim 1, 2, 117, 0, 0, 0, 0,
ax_anim 1, 0, 116, 0, 0, 0, 0,
ax_anim 1, 0, 114, 0, 0, 0, 0,
ax_anim 1, 0, 117, 0, 0, 0, 0,
ax_anim 1, 0, 116, 0, 0, 0, 0,
ax_anim 1, 0, 115, 0, 0, 0, 0,
ax_anim 1, 1, 113, 0, 0, 0, 0,
ax_anim 1, 0, 111, 0, 0, 0, 0,
ax_anim_terminator
sBanetteAnims_5_6:
ax_anim 3, 0, 125, 0, 0, 0, 0,
ax_anim 3, 0, 133, 0, 0, 0, 0,
ax_anim 2, 0, 80, 0, 0, 0, 0,
ax_anim 2, 0, 88, 0, 0, 0, 0,
ax_anim 1, 0, 96, 0, 0, 0, 0,
ax_anim 1, 0, 104, 0, 0, 0, 0,
ax_anim 1, 0, 111, 0, 0, 0, 0,
ax_anim 6, 0, 118, 0, 0, 0, 0,
ax_anim 3, 0, 118, 0, 0, 0, 0,
ax_anim 1, 0, 123, 0, 0, 0, 0,
ax_anim 1, 2, 124, 0, 0, 0, 0,
ax_anim 1, 0, 123, 0, 0, 0, 0,
ax_anim 1, 0, 121, 0, 0, 0, 0,
ax_anim 1, 0, 124, 0, 0, 0, 0,
ax_anim 1, 0, 123, 0, 0, 0, 0,
ax_anim 1, 0, 122, 0, 0, 0, 0,
ax_anim 1, 1, 120, 0, 0, 0, 0,
ax_anim 1, 0, 118, 0, 0, 0, 0,
ax_anim_terminator
sBanetteAnims_5_7:
ax_anim 3, 0, 133, 0, 0, 0, 0,
ax_anim 3, 0, 80, 0, 0, 0, 0,
ax_anim 2, 0, 88, 0, 0, 0, 0,
ax_anim 2, 0, 96, 0, 0, 0, 0,
ax_anim 1, 0, 104, 0, 0, 0, 0,
ax_anim 1, 0, 111, 0, 0, 0, 0,
ax_anim 1, 0, 118, 0, 0, 0, 0,
ax_anim 6, 0, 125, 0, 0, 0, 0,
ax_anim 3, 0, 132, 0, 0, 0, 0,
ax_anim 1, 0, 130, 0, 0, 0, 0,
ax_anim 1, 2, 131, 0, 0, 0, 0,
ax_anim 1, 0, 130, 0, 0, 0, 0,
ax_anim 1, 0, 128, 0, 0, 0, 0,
ax_anim 1, 0, 131, 0, 0, 0, 0,
ax_anim 1, 0, 130, 0, 0, 0, 0,
ax_anim 1, 0, 129, 0, 0, 0, 0,
ax_anim 1, 1, 127, 0, 0, 0, 0,
ax_anim 1, 0, 125, 0, 0, 0, 0,
ax_anim_terminator
sBanetteAnims_5_8:
ax_anim 3, 0, 80, 0, 0, 0, 0,
ax_anim 3, 0, 88, 0, 0, 0, 0,
ax_anim 2, 0, 96, 0, 0, 0, 0,
ax_anim 2, 0, 104, 0, 0, 0, 0,
ax_anim 1, 0, 111, 0, 0, 0, 0,
ax_anim 1, 0, 118, 0, 0, 0, 0,
ax_anim 1, 0, 125, 0, 0, 0, 0,
ax_anim 6, 0, 133, 0, 0, 0, 0,
ax_anim 3, 0, 140, 0, 0, 0, 0,
ax_anim 1, 0, 138, 0, 0, 0, 0,
ax_anim 1, 2, 139, 0, 0, 0, 0,
ax_anim 1, 0, 138, 0, 0, 0, 0,
ax_anim 1, 0, 136, 0, 0, 0, 0,
ax_anim 1, 0, 139, 0, 0, 0, 0,
ax_anim 1, 0, 138, 0, 0, 0, 0,
ax_anim 1, 0, 137, 0, 0, 0, 0,
ax_anim 1, 1, 135, 0, 0, 0, 0,
ax_anim 1, 0, 133, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sBanetteAnims_6_1:
ax_anim 30, 0, 141, 0, 0, 0, 0,
ax_anim 35, 0, 142, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sBanetteAnims_7_1:
ax_anim 2, 0, 143, 0, -2, 0, -2,
ax_anim 8, 0, 143, 0, -3, 0, -3,
ax_anim_terminator
sBanetteAnims_7_2:
ax_anim 2, 0, 144, -2, -2, -2, -2,
ax_anim 8, 0, 144, -3, -3, -3, -3,
ax_anim_terminator
sBanetteAnims_7_3:
ax_anim 2, 0, 145, -2, 0, -2, 0,
ax_anim 8, 0, 145, -3, 0, -3, 0,
ax_anim_terminator
sBanetteAnims_7_4:
ax_anim 2, 0, 146, -2, 2, -2, 2,
ax_anim 8, 0, 146, -3, 3, -3, 3,
ax_anim_terminator
sBanetteAnims_7_5:
ax_anim 2, 0, 147, 0, 2, 0, 2,
ax_anim 8, 0, 147, 0, 3, 0, 3,
ax_anim_terminator
sBanetteAnims_7_6:
ax_anim 2, 0, 148, 2, 2, 2, 2,
ax_anim 8, 0, 148, 3, 3, 3, 3,
ax_anim_terminator
sBanetteAnims_7_7:
ax_anim 2, 0, 149, 2, 0, 2, 0,
ax_anim 8, 0, 149, 3, 0, 3, 0,
ax_anim_terminator
sBanetteAnims_7_8:
ax_anim 2, 0, 150, 2, -2, 2, -2,
ax_anim 8, 0, 150, 3, -3, 3, -3,
ax_anim_terminator
.align 2
sBanetteAnims_8_1:
ax_anim 40, 0, 151, 0, 0, 0, 0,
ax_anim 1, 0, 151, 0, -2, 0, 0,
ax_anim 2, 0, 151, 0, -3, 0, 0,
ax_anim 4, 0, 152, 0, -5, 0, 0,
ax_anim 4, 0, 153, 0, -6, 0, 0,
ax_anim 4, 0, 152, 0, -6, 0, 0,
ax_anim 4, 0, 153, 0, -5, 0, 0,
ax_anim 2, 0, 151, 0, -3, 0, 0,
ax_anim 1, 0, 151, 0, -2, 0, 0,
ax_anim_terminator
sBanetteAnims_8_2:
ax_anim 40, 0, 154, 0, 0, 0, 0,
ax_anim 1, 0, 154, 0, -2, 0, 0,
ax_anim 2, 0, 154, 0, -3, 0, 0,
ax_anim 4, 0, 155, 0, -5, 0, 0,
ax_anim 4, 0, 156, 0, -6, 0, 0,
ax_anim 4, 0, 155, 0, -6, 0, 0,
ax_anim 4, 0, 156, 0, -5, 0, 0,
ax_anim 2, 0, 154, 0, -3, 0, 0,
ax_anim 1, 0, 154, 0, -2, 0, 0,
ax_anim_terminator
sBanetteAnims_8_3:
ax_anim 40, 0, 157, 0, 0, 0, 0,
ax_anim 1, 0, 157, 0, -2, 0, 0,
ax_anim 2, 0, 157, 0, -3, 0, 0,
ax_anim 4, 0, 158, 0, -5, 0, 0,
ax_anim 4, 0, 159, 0, -6, 0, 0,
ax_anim 4, 0, 158, 0, -6, 0, 0,
ax_anim 4, 0, 159, 0, -5, 0, 0,
ax_anim 2, 0, 157, 0, -3, 0, 0,
ax_anim 1, 0, 157, 0, -2, 0, 0,
ax_anim_terminator
sBanetteAnims_8_4:
ax_anim 40, 0, 160, 0, 0, 0, 0,
ax_anim 1, 0, 160, 0, -2, 0, 0,
ax_anim 2, 0, 160, 0, -3, 0, 0,
ax_anim 4, 0, 161, 0, -5, 0, 0,
ax_anim 4, 0, 162, 0, -6, 0, 0,
ax_anim 4, 0, 161, 0, -6, 0, 0,
ax_anim 4, 0, 162, 0, -5, 0, 0,
ax_anim 2, 0, 160, 0, -3, 0, 0,
ax_anim 1, 0, 160, 0, -2, 0, 0,
ax_anim_terminator
sBanetteAnims_8_5:
ax_anim 40, 0, 163, 0, 0, 0, 0,
ax_anim 1, 0, 163, 0, -2, 0, 0,
ax_anim 2, 0, 163, 0, -3, 0, 0,
ax_anim 4, 0, 164, 0, -5, 0, 0,
ax_anim 4, 0, 165, 0, -6, 0, 0,
ax_anim 4, 0, 164, 0, -6, 0, 0,
ax_anim 4, 0, 165, 0, -5, 0, 0,
ax_anim 2, 0, 163, 0, -3, 0, 0,
ax_anim 1, 0, 163, 0, -2, 0, 0,
ax_anim_terminator
sBanetteAnims_8_6:
ax_anim 40, 0, 166, 0, 0, 0, 0,
ax_anim 1, 0, 166, 0, -2, 0, 0,
ax_anim 2, 0, 166, 0, -3, 0, 0,
ax_anim 4, 0, 167, 0, -5, 0, 0,
ax_anim 4, 0, 168, 0, -6, 0, 0,
ax_anim 4, 0, 167, 0, -6, 0, 0,
ax_anim 4, 0, 168, 0, -5, 0, 0,
ax_anim 2, 0, 166, 0, -3, 0, 0,
ax_anim 1, 0, 166, 0, -2, 0, 0,
ax_anim_terminator
sBanetteAnims_8_7:
ax_anim 40, 0, 169, 0, 0, 0, 0,
ax_anim 1, 0, 169, 0, -2, 0, 0,
ax_anim 2, 0, 169, 0, -3, 0, 0,
ax_anim 4, 0, 170, 0, -5, 0, 0,
ax_anim 4, 0, 171, 0, -6, 0, 0,
ax_anim 4, 0, 170, 0, -6, 0, 0,
ax_anim 4, 0, 171, 0, -5, 0, 0,
ax_anim 2, 0, 169, 0, -3, 0, 0,
ax_anim 1, 0, 169, 0, -2, 0, 0,
ax_anim_terminator
sBanetteAnims_8_8:
ax_anim 40, 0, 172, 0, 0, 0, 0,
ax_anim 1, 0, 172, 0, -2, 0, 0,
ax_anim 2, 0, 172, 0, -3, 0, 0,
ax_anim 4, 0, 173, 0, -5, 0, 0,
ax_anim 4, 0, 174, 0, -6, 0, 0,
ax_anim 4, 0, 173, 0, -6, 0, 0,
ax_anim 4, 0, 174, 0, -5, 0, 0,
ax_anim 2, 0, 172, 0, -3, 0, 0,
ax_anim 1, 0, 172, 0, -2, 0, 0,
ax_anim_terminator
.align 2
sBanetteAnims_9_1:
ax_anim 2, 0, 175, 0, 0, 0, 0,
ax_anim 1, 0, 176, 6, 4, 6, 4,
ax_anim 2, 0, 177, 10, 12, 10, 12,
ax_anim 2, 0, 178, 7, 20, 7, 20,
ax_anim 3, 0, 179, 0, 23, 0, 23,
ax_anim 2, 3, 180, -7, 20, -7, 20,
ax_anim 2, 0, 181, -10, 12, -10, 12,
ax_anim 1, 0, 182, -6, 4, -6, 4,
ax_anim 1, 0, 175, 0, 0, 0, 0,
ax_anim_terminator
sBanetteAnims_9_2:
ax_anim 2, 0, 182, 0, 0, 0, 0,
ax_anim 1, 0, 175, 11, -2, 11, -2,
ax_anim 2, 0, 176, 21, 6, 21, 6,
ax_anim 2, 0, 177, 24, 16, 24, 16,
ax_anim 3, 0, 178, 20, 24, 20, 24,
ax_anim 2, 3, 179, 11, 24, 11, 24,
ax_anim 2, 0, 180, 4, 20, 4, 20,
ax_anim 1, 0, 181, -1, 10, -1, 10,
ax_anim 1, 0, 182, 0, 0, 0, 0,
ax_anim_terminator
sBanetteAnims_9_3:
ax_anim 2, 0, 181, 0, 0, 0, 0,
ax_anim 1, 0, 182, 4, -3, 4, -3,
ax_anim 2, 0, 175, 11, -5, 11, -5,
ax_anim 2, 0, 176, 17, -2, 17, -2,
ax_anim 3, 0, 177, 20, 3, 20, 3,
ax_anim 2, 3, 178, 17, 8, 17, 8,
ax_anim 2, 0, 179, 12, 9, 12, 9,
ax_anim 1, 0, 180, 3, 6, 3, 6,
ax_anim 1, 0, 181, 0, 0, 0, 0,
ax_anim_terminator
sBanetteAnims_9_4:
ax_anim 2, 0, 180, 0, 0, 0, 0,
ax_anim 1, 0, 181, 1, -5, 1, -5,
ax_anim 2, 0, 182, 5, -11, 5, -11,
ax_anim 2, 0, 175, 12, -16, 12, -16,
ax_anim 3, 0, 176, 21, -16, 21, -16,
ax_anim 2, 3, 177, 24, -10, 24, -10,
ax_anim 2, 0, 178, 19, -3, 19, -3,
ax_anim 1, 0, 179, 8, 1, 8, 1,
ax_anim 1, 0, 180, 0, 0, 0, 0,
ax_anim_terminator
sBanetteAnims_9_5:
ax_anim 2, 0, 179, 0, 0, 0, 0,
ax_anim 1, 0, 180, -7, -3, -7, -3,
ax_anim 2, 0, 181, -11, -8, -11, -8,
ax_anim 2, 0, 182, -8, -14, -8, -14,
ax_anim 3, 0, 175, 0, -16, 0, -16,
ax_anim 2, 3, 176, 8, -14, 8, -14,
ax_anim 2, 0, 177, 11, -6, 11, -6,
ax_anim 1, 0, 178, 8, -2, 8, -2,
ax_anim 1, 0, 179, 0, 0, 0, 0,
ax_anim_terminator
sBanetteAnims_9_6:
ax_anim 2, 0, 178, 0, 0, 0, 0,
ax_anim 1, 0, 177, -1, -5, -1, -5,
ax_anim 2, 0, 176, -5, -11, -5, -11,
ax_anim 2, 0, 175, -12, -16, -12, -16,
ax_anim 3, 0, 182, -21, -16, -21, -16,
ax_anim 2, 3, 181, -24, -10, -24, -10,
ax_anim 2, 0, 180, -19, -3, -19, -3,
ax_anim 1, 0, 179, -8, 1, -8, 1,
ax_anim 1, 0, 178, 0, 0, 0, 0,
ax_anim_terminator
sBanetteAnims_9_7:
ax_anim 2, 0, 177, 0, 0, 0, 0,
ax_anim 1, 0, 176, -4, -3, -4, -3,
ax_anim 2, 0, 175, -11, -5, -11, -5,
ax_anim 2, 0, 182, -17, -2, -17, -2,
ax_anim 3, 0, 181, -20, 3, -20, 3,
ax_anim 2, 3, 180, -17, 8, -17, 8,
ax_anim 2, 0, 179, -12, 9, -12, 9,
ax_anim 1, 0, 178, -3, 6, -3, 6,
ax_anim 1, 0, 177, 0, 0, 0, 0,
ax_anim_terminator
sBanetteAnims_9_8:
ax_anim 2, 0, 176, 0, 0, 0, 0,
ax_anim 1, 0, 175, -11, -2, -11, -2,
ax_anim 2, 0, 182, -21, 6, -21, 6,
ax_anim 2, 0, 181, -24, 16, -24, 16,
ax_anim 3, 0, 180, -20, 24, -20, 24,
ax_anim 2, 3, 179, -11, 24, -11, 24,
ax_anim 2, 0, 178, -4, 20, -4, 20,
ax_anim 1, 0, 177, 1, 10, 1, 10,
ax_anim 1, 0, 176, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sBanetteAnims_10_1:
ax_anim 2, 0, 183, 0, 0, 0, 0,
ax_anim 2, 0, 183, 6, 0, 6, 0,
ax_anim 2, 0, 183, -6, 0, -6, 0,
ax_anim 2, 0, 183, 10, 0, 10, 0,
ax_anim 2, 0, 183, -10, 0, -10, 0,
ax_anim 2, 0, 183, 12, 0, 12, 0,
ax_anim 3, 0, 183, -12, 0, -12, 0,
ax_anim 3, 0, 183, 13, 0, 13, 0,
ax_anim 3, 0, 183, -13, 0, -13, 0,
ax_anim 2, 0, 183, 12, 0, 12, 0,
ax_anim 3, 0, 183, -12, 0, -12, 0,
ax_anim 2, 0, 183, 10, 0, 10, 0,
ax_anim 2, 0, 183, -10, 0, -10, 0,
ax_anim 2, 0, 183, 6, 0, 6, 0,
ax_anim 2, 0, 183, -6, 0, -6, 0,
ax_anim 2, 0, 183, 0, 0, 0, 0,
ax_anim_terminator
sBanetteAnims_10_2:
ax_anim 2, 0, 184, 0, 0, 0, 0,
ax_anim 2, 0, 184, 6, -6, 6, -6,
ax_anim 2, 0, 184, -6, 6, -6, 6,
ax_anim 2, 0, 184, 10, -10, 10, -10,
ax_anim 2, 0, 184, -10, 10, -10, 10,
ax_anim 2, 0, 184, 12, -12, 12, -12,
ax_anim 3, 0, 184, -12, 12, -12, 12,
ax_anim 3, 0, 184, 13, -13, 13, -13,
ax_anim 3, 0, 184, -13, 13, -13, 13,
ax_anim 2, 0, 184, 12, -12, 12, -12,
ax_anim 3, 0, 184, -12, 12, -12, 12,
ax_anim 2, 0, 184, 10, -10, 10, -10,
ax_anim 2, 0, 184, -10, 10, -10, 10,
ax_anim 2, 0, 184, 6, -6, 6, -6,
ax_anim 2, 0, 184, -6, 6, -6, 6,
ax_anim 2, 0, 184, 0, 0, 0, 0,
ax_anim_terminator
sBanetteAnims_10_3:
ax_anim 2, 0, 185, 0, 0, 0, 0,
ax_anim 2, 0, 185, 0, -6, 0, -6,
ax_anim 2, 0, 185, 0, 6, 0, 6,
ax_anim 2, 0, 185, 0, -10, 0, -10,
ax_anim 2, 0, 185, 0, 10, 0, 10,
ax_anim 2, 0, 185, 0, -12, 0, -12,
ax_anim 3, 0, 185, 0, 12, 0, 12,
ax_anim 3, 0, 185, 0, -13, 0, -13,
ax_anim 3, 0, 185, 0, 13, 0, 13,
ax_anim 2, 0, 185, 0, -12, 0, -12,
ax_anim 3, 0, 185, 0, 12, 0, 12,
ax_anim 2, 0, 185, 0, -10, 0, -10,
ax_anim 2, 0, 185, 0, 10, 0, 10,
ax_anim 2, 0, 185, 0, -6, 0, -6,
ax_anim 2, 0, 185, 0, 6, 0, 6,
ax_anim 2, 0, 185, 0, 0, 0, 0,
ax_anim_terminator
sBanetteAnims_10_4:
ax_anim 2, 0, 186, 0, 0, 0, 0,
ax_anim 2, 0, 186, -6, -6, -6, -6,
ax_anim 2, 0, 186, 6, 6, 6, 6,
ax_anim 2, 0, 186, -10, -10, -10, -10,
ax_anim 2, 0, 186, 10, 10, 10, 10,
ax_anim 2, 0, 186, -12, -12, -12, -12,
ax_anim 3, 0, 186, 12, 12, 12, 12,
ax_anim 3, 0, 186, -13, -13, -13, -13,
ax_anim 3, 0, 186, 13, 13, 13, 13,
ax_anim 2, 0, 186, -12, -12, -12, -12,
ax_anim 3, 0, 186, 12, 12, 12, 12,
ax_anim 2, 0, 186, -10, -10, -10, -10,
ax_anim 2, 0, 186, 10, 10, 10, 10,
ax_anim 2, 0, 186, -6, -6, -6, -6,
ax_anim 2, 0, 186, 6, 6, 6, 6,
ax_anim 2, 0, 186, 0, 0, 0, 0,
ax_anim_terminator
sBanetteAnims_10_5:
ax_anim 2, 0, 187, 0, 0, 0, 0,
ax_anim 2, 0, 187, 6, 0, 6, 0,
ax_anim 2, 0, 187, -6, 0, -6, 0,
ax_anim 2, 0, 187, 10, 0, 10, 0,
ax_anim 2, 0, 187, -10, 0, -10, 0,
ax_anim 2, 0, 187, 12, 0, 12, 0,
ax_anim 3, 0, 187, -12, 0, -12, 0,
ax_anim 3, 0, 187, 13, 0, 13, 0,
ax_anim 3, 0, 187, -13, 0, -13, 0,
ax_anim 2, 0, 187, 12, 0, 12, 0,
ax_anim 3, 0, 187, -12, 0, -12, 0,
ax_anim 2, 0, 187, 10, 0, 10, 0,
ax_anim 2, 0, 187, -10, 0, -10, 0,
ax_anim 2, 0, 187, 6, 0, 6, 0,
ax_anim 2, 0, 187, -6, 0, -6, 0,
ax_anim 2, 0, 187, 0, 0, 0, 0,
ax_anim_terminator
sBanetteAnims_10_6:
ax_anim 2, 0, 188, 0, 0, 0, 0,
ax_anim 2, 0, 188, 6, -6, 6, -6,
ax_anim 2, 0, 188, -6, 6, -6, 6,
ax_anim 2, 0, 188, 10, -10, 10, -10,
ax_anim 2, 0, 188, -10, 10, -10, 10,
ax_anim 2, 0, 188, 12, -12, 12, -12,
ax_anim 3, 0, 188, -12, 12, -12, 12,
ax_anim 3, 0, 188, 13, -13, 13, -13,
ax_anim 3, 0, 188, -13, 13, -13, 13,
ax_anim 2, 0, 188, 12, -12, 12, -12,
ax_anim 3, 0, 188, -12, 12, -12, 12,
ax_anim 2, 0, 188, 10, -10, 10, -10,
ax_anim 2, 0, 188, -10, 10, -10, 10,
ax_anim 2, 0, 188, 6, -6, 6, -6,
ax_anim 2, 0, 188, -6, 6, -6, 6,
ax_anim 2, 0, 188, 0, 0, 0, 0,
ax_anim_terminator
sBanetteAnims_10_7:
ax_anim 2, 0, 189, 0, 0, 0, 0,
ax_anim 2, 0, 189, 0, -6, 0, -6,
ax_anim 2, 0, 189, 0, 6, 0, 6,
ax_anim 2, 0, 189, 0, -10, 0, -10,
ax_anim 2, 0, 189, 0, 10, 0, 10,
ax_anim 2, 0, 189, 0, -12, 0, -12,
ax_anim 3, 0, 189, 0, 12, 0, 12,
ax_anim 3, 0, 189, 0, -13, 0, -13,
ax_anim 3, 0, 189, 0, 13, 0, 13,
ax_anim 2, 0, 189, 0, -12, 0, -12,
ax_anim 3, 0, 189, 0, 12, 0, 12,
ax_anim 2, 0, 189, 0, -10, 0, -10,
ax_anim 2, 0, 189, 0, 10, 0, 10,
ax_anim 2, 0, 189, 0, -6, 0, -6,
ax_anim 2, 0, 189, 0, 6, 0, 6,
ax_anim 2, 0, 189, 0, 0, 0, 0,
ax_anim_terminator
sBanetteAnims_10_8:
ax_anim 2, 0, 190, 0, 0, 0, 0,
ax_anim 2, 0, 190, -6, -6, -6, -6,
ax_anim 2, 0, 190, 6, 6, 6, 6,
ax_anim 2, 0, 190, -10, -10, -10, -10,
ax_anim 2, 0, 190, 10, 10, 10, 10,
ax_anim 2, 0, 190, -12, -12, -12, -12,
ax_anim 3, 0, 190, 12, 12, 12, 12,
ax_anim 3, 0, 190, -13, -13, -13, -13,
ax_anim 3, 0, 190, 13, 13, 13, 13,
ax_anim 2, 0, 190, -12, -12, -12, -12,
ax_anim 3, 0, 190, 12, 12, 12, 12,
ax_anim 2, 0, 190, -10, -10, -10, -10,
ax_anim 2, 0, 190, 10, 10, 10, 10,
ax_anim 2, 0, 190, -6, -6, -6, -6,
ax_anim 2, 0, 190, 6, 6, 6, 6,
ax_anim 2, 0, 190, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sBanetteAnims_11_1:
ax_anim 2, 0, 191, 0, 0, 0, 0,
ax_anim 1, 0, 191, 0, -10, 0, 0,
ax_anim 2, 0, 191, 0, -16, 0, 0,
ax_anim 3, 0, 191, 0, -19, 0, 0,
ax_anim 4, 0, 191, 0, -20, 0, 0,
ax_anim 4, 0, 192, 0, -23, 0, 0,
ax_anim 3, 0, 192, 0, -22, 0, 0,
ax_anim 2, 0, 192, 0, -14, 0, 0,
ax_anim 1, 0, 192, 0, -3, 0, 0,
ax_anim 2, 2, 191, 0, 3, 0, 0,
ax_anim_terminator
sBanetteAnims_11_2:
ax_anim 2, 0, 193, 0, 0, 0, 0,
ax_anim 1, 0, 193, 0, -10, 0, 0,
ax_anim 2, 0, 193, 0, -16, 0, 0,
ax_anim 3, 0, 193, 0, -18, 0, 0,
ax_anim 4, 0, 193, 0, -19, 0, 0,
ax_anim 4, 0, 194, 0, -22, 0, 0,
ax_anim 3, 0, 194, 0, -21, 0, 0,
ax_anim 2, 0, 194, 0, -14, 0, 0,
ax_anim 1, 0, 194, 0, -3, 0, 0,
ax_anim 2, 2, 193, 0, 3, 0, 0,
ax_anim_terminator
sBanetteAnims_11_3:
ax_anim 2, 0, 195, 0, 0, 0, 0,
ax_anim 1, 0, 195, 0, -10, 0, 0,
ax_anim 2, 0, 195, 0, -16, 0, 0,
ax_anim 3, 0, 195, 0, -20, 0, 0,
ax_anim 4, 0, 195, 0, -21, 0, 0,
ax_anim 4, 0, 196, 0, -23, 0, 0,
ax_anim 3, 0, 196, 0, -21, 0, 0,
ax_anim 2, 0, 196, 0, -14, 0, 0,
ax_anim 1, 0, 196, 0, -3, 0, 0,
ax_anim 2, 2, 195, 0, 3, 0, 0,
ax_anim_terminator
sBanetteAnims_11_4:
ax_anim 2, 0, 197, 0, 0, 0, 0,
ax_anim 1, 0, 197, 0, -10, 0, 0,
ax_anim 2, 0, 197, 0, -16, 0, 0,
ax_anim 3, 0, 197, 0, -19, 0, 0,
ax_anim 4, 0, 197, 0, -20, 0, 0,
ax_anim 4, 0, 198, 0, -22, 0, 0,
ax_anim 3, 0, 198, 0, -21, 0, 0,
ax_anim 2, 0, 198, 0, -14, 0, 0,
ax_anim 1, 0, 198, 0, -3, 0, 0,
ax_anim 2, 2, 197, 0, 3, 0, 0,
ax_anim_terminator
sBanetteAnims_11_5:
ax_anim 2, 0, 199, 0, 0, 0, 0,
ax_anim 1, 0, 199, 0, -10, 0, 0,
ax_anim 2, 0, 199, 0, -16, 0, 0,
ax_anim 3, 0, 199, 0, -20, 0, 0,
ax_anim 4, 0, 199, 0, -21, 0, 0,
ax_anim 4, 0, 200, 0, -23, 0, 0,
ax_anim 3, 0, 200, 0, -22, 0, 0,
ax_anim 2, 0, 200, 0, -14, 0, 0,
ax_anim 1, 0, 200, 0, -3, 0, 0,
ax_anim 2, 2, 199, 0, 3, 0, 0,
ax_anim_terminator
sBanetteAnims_11_6:
ax_anim 2, 0, 201, 0, 0, 0, 0,
ax_anim 1, 0, 201, 0, -10, 0, 0,
ax_anim 2, 0, 201, 0, -16, 0, 0,
ax_anim 3, 0, 201, 0, -19, 0, 0,
ax_anim 4, 0, 201, 0, -20, 0, 0,
ax_anim 4, 0, 202, 0, -22, 0, 0,
ax_anim 3, 0, 202, 0, -21, 0, 0,
ax_anim 2, 0, 202, 0, -14, 0, 0,
ax_anim 1, 0, 202, 0, -3, 0, 0,
ax_anim 2, 2, 201, 0, 3, 0, 0,
ax_anim_terminator
sBanetteAnims_11_7:
ax_anim 2, 0, 203, 0, 0, 0, 0,
ax_anim 1, 0, 203, 0, -10, 0, 0,
ax_anim 2, 0, 203, 0, -16, 0, 0,
ax_anim 3, 0, 203, 0, -20, 0, 0,
ax_anim 4, 0, 203, 0, -21, 0, 0,
ax_anim 4, 0, 204, 0, -23, 0, 0,
ax_anim 3, 0, 204, 0, -21, 0, 0,
ax_anim 2, 0, 204, 0, -14, 0, 0,
ax_anim 1, 0, 204, 0, -3, 0, 0,
ax_anim 2, 2, 203, 0, 3, 0, 0,
ax_anim_terminator
sBanetteAnims_11_8:
ax_anim 2, 0, 205, 0, 0, 0, 0,
ax_anim 1, 0, 205, 0, -10, 0, 0,
ax_anim 2, 0, 205, 0, -16, 0, 0,
ax_anim 3, 0, 205, 0, -18, 0, 0,
ax_anim 4, 0, 205, 0, -19, 0, 0,
ax_anim 4, 0, 206, 0, -22, 0, 0,
ax_anim 3, 0, 206, 0, -21, 0, 0,
ax_anim 2, 0, 206, 0, -14, 0, 0,
ax_anim 1, 0, 206, 0, -3, 0, 0,
ax_anim 2, 2, 205, 0, 3, 0, 0,
ax_anim_terminator
.align 2
sBanetteAnims_12_1:
ax_anim 2, 0, 207, 1, 0, 1, 0,
ax_anim 2, 0, 207, 0, 0, 0, 0,
ax_anim 2, 0, 207, 1, 0, 1, 0,
ax_anim 2, 0, 207, 0, 0, 0, 0,
ax_anim 2, 0, 207, 1, 0, 1, 0,
ax_anim 2, 2, 207, 0, 0, 0, 0,
ax_anim 2, 0, 207, 1, 0, 1, 0,
ax_anim 2, 0, 207, 0, 0, 0, 0,
ax_anim 2, 0, 207, 1, 0, 1, 0,
ax_anim 2, 1, 207, 0, 0, 0, 0,
ax_anim_terminator
sBanetteAnims_12_2:
ax_anim 2, 0, 214, 1, -1, 1, -1,
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 2, 0, 214, 1, -1, 1, -1,
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 2, 0, 214, 1, -1, 1, -1,
ax_anim 2, 2, 214, 0, 0, 0, 0,
ax_anim 2, 0, 214, 1, -1, 1, -1,
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 2, 0, 214, 1, -1, 1, -1,
ax_anim 2, 1, 214, 0, 0, 0, 0,
ax_anim_terminator
sBanetteAnims_12_3:
ax_anim 2, 0, 213, 0, -1, 0, -1,
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 2, 0, 213, 0, -1, 0, -1,
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 2, 0, 213, 0, -1, 0, -1,
ax_anim 2, 2, 213, 0, 0, 0, 0,
ax_anim 2, 0, 213, 0, -1, 0, -1,
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 2, 0, 213, 0, -1, 0, -1,
ax_anim 2, 1, 213, 0, 0, 0, 0,
ax_anim_terminator
sBanetteAnims_12_4:
ax_anim 2, 0, 212, -1, -1, -1, -1,
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 2, 0, 212, -1, -1, -1, -1,
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 2, 0, 212, -1, -1, -1, -1,
ax_anim 2, 2, 212, 0, 0, 0, 0,
ax_anim 2, 0, 212, -1, -1, -1, -1,
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 2, 0, 212, -1, -1, -1, -1,
ax_anim 2, 1, 212, 0, 0, 0, 0,
ax_anim_terminator
sBanetteAnims_12_5:
ax_anim 2, 0, 211, 1, 0, 1, 0,
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 2, 0, 211, 1, 0, 1, 0,
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 2, 0, 211, 1, 0, 1, 0,
ax_anim 2, 2, 211, 0, 0, 0, 0,
ax_anim 2, 0, 211, 1, 0, 1, 0,
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 2, 0, 211, 1, 0, 1, 0,
ax_anim 2, 1, 211, 0, 0, 0, 0,
ax_anim_terminator
sBanetteAnims_12_6:
ax_anim 2, 0, 210, 1, -1, 1, -1,
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 2, 0, 210, 1, -1, 1, -1,
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 2, 0, 210, 1, -1, 1, -1,
ax_anim 2, 2, 210, 0, 0, 0, 0,
ax_anim 2, 0, 210, 1, -1, 1, -1,
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 2, 0, 210, 1, -1, 1, -1,
ax_anim 2, 1, 210, 0, 0, 0, 0,
ax_anim_terminator
sBanetteAnims_12_7:
ax_anim 2, 0, 209, 0, -1, 0, -1,
ax_anim 2, 0, 209, 0, 0, 0, 0,
ax_anim 2, 0, 209, 0, -1, 0, -1,
ax_anim 2, 0, 209, 0, 0, 0, 0,
ax_anim 2, 0, 209, 0, -1, 0, -1,
ax_anim 2, 2, 209, 0, 0, 0, 0,
ax_anim 2, 0, 209, 0, -1, 0, -1,
ax_anim 2, 0, 209, 0, 0, 0, 0,
ax_anim 2, 0, 209, 0, -1, 0, -1,
ax_anim 2, 1, 209, 0, 0, 0, 0,
ax_anim_terminator
sBanetteAnims_12_8:
ax_anim 2, 0, 208, -1, -1, -1, -1,
ax_anim 2, 0, 208, 0, 0, 0, 0,
ax_anim 2, 0, 208, -1, -1, -1, -1,
ax_anim 2, 0, 208, 0, 0, 0, 0,
ax_anim 2, 0, 208, -1, -1, -1, -1,
ax_anim 2, 2, 208, 0, 0, 0, 0,
ax_anim 2, 0, 208, -1, -1, -1, -1,
ax_anim 2, 0, 208, 0, 0, 0, 0,
ax_anim 2, 0, 208, -1, -1, -1, -1,
ax_anim 2, 1, 208, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sBanetteAnims_13_1:
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 2, 215, 0, 0, 0, 0,
ax_anim_terminator
sBanetteAnims_13_2:
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 2, 222, 0, 0, 0, 0,
ax_anim_terminator
sBanetteAnims_13_3:
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 2, 221, 0, 0, 0, 0,
ax_anim_terminator
sBanetteAnims_13_4:
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 2, 220, 0, 0, 0, 0,
ax_anim_terminator
sBanetteAnims_13_5:
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 2, 219, 0, 0, 0, 0,
ax_anim_terminator
sBanetteAnims_13_6:
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 2, 218, 0, 0, 0, 0,
ax_anim_terminator
sBanetteAnims_13_7:
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 2, 217, 0, 0, 0, 0,
ax_anim_terminator
sBanetteAnims_13_8:
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 2, 216, 0, 0, 0, 0,
ax_anim_terminator
sBanetteGfx1:
.incbin "baserom.gba", 0x149BED4, 0x200
sBanetteSprites1:
ax_sprite sBanetteGfx1, 0x200
ax_sprite_terminator
sBanetteGfx2:
.incbin "baserom.gba", 0x149C0E4, 0x200
sBanetteSprites2:
ax_sprite sBanetteGfx2, 0x200
ax_sprite_terminator
sBanetteGfx3:
.incbin "baserom.gba", 0x149C2F4, 0x200
sBanetteSprites3:
ax_sprite sBanetteGfx3, 0x200
ax_sprite_terminator
sBanetteGfx4:
.incbin "baserom.gba", 0x149C504, 0x200
sBanetteSprites4:
ax_sprite sBanetteGfx4, 0x200
ax_sprite_terminator
sBanetteGfx5:
.incbin "baserom.gba", 0x149C714, 0x200
sBanetteSprites5:
ax_sprite sBanetteGfx5, 0x200
ax_sprite_terminator
sBanetteGfx6:
.incbin "baserom.gba", 0x149C924, 0x200
sBanetteSprites6:
ax_sprite sBanetteGfx6, 0x200
ax_sprite_terminator
sBanetteGfx7:
.incbin "baserom.gba", 0x149CB34, 0x200
sBanetteSprites7:
ax_sprite sBanetteGfx7, 0x200
ax_sprite_terminator
sBanetteGfx8:
.incbin "baserom.gba", 0x149CD44, 0x200
sBanetteSprites8:
ax_sprite sBanetteGfx8, 0x200
ax_sprite_terminator
sBanetteGfx9:
.incbin "baserom.gba", 0x149CF54, 0x200
sBanetteSprites9:
ax_sprite sBanetteGfx9, 0x200
ax_sprite_terminator
sBanetteGfx10:
.incbin "baserom.gba", 0x149D164, 0x200
sBanetteSprites10:
ax_sprite sBanetteGfx10, 0x200
ax_sprite_terminator
sBanetteGfx11:
.incbin "baserom.gba", 0x149D374, 0x200
sBanetteSprites11:
ax_sprite sBanetteGfx11, 0x200
ax_sprite_terminator
sBanetteGfx12:
.incbin "baserom.gba", 0x149D584, 0x200
sBanetteSprites12:
ax_sprite sBanetteGfx12, 0x200
ax_sprite_terminator
sBanetteGfx13:
.incbin "baserom.gba", 0x149D794, 0x200
sBanetteSprites13:
ax_sprite sBanetteGfx13, 0x200
ax_sprite_terminator
sBanetteGfx14:
.incbin "baserom.gba", 0x149D9A4, 0x200
sBanetteSprites14:
ax_sprite sBanetteGfx14, 0x200
ax_sprite_terminator
sBanetteGfx15:
.incbin "baserom.gba", 0x149DBB4, 0x200
sBanetteSprites15:
ax_sprite sBanetteGfx15, 0x200
ax_sprite_terminator
sBanetteGfx16:
.incbin "baserom.gba", 0x149DDC4, 0x200
sBanetteSprites16:
ax_sprite sBanetteGfx16, 0x200
ax_sprite_terminator
sBanetteGfx17:
.incbin "baserom.gba", 0x149DFD4, 0x200
sBanetteSprites17:
ax_sprite sBanetteGfx17, 0x200
ax_sprite_terminator
sBanetteGfx18:
.incbin "baserom.gba", 0x149E1E4, 0x200
sBanetteSprites18:
ax_sprite sBanetteGfx18, 0x200
ax_sprite_terminator
sBanetteGfx19:
.incbin "baserom.gba", 0x149E3F4, 0x200
sBanetteSprites19:
ax_sprite sBanetteGfx19, 0x200
ax_sprite_terminator
sBanetteGfx20:
.incbin "baserom.gba", 0x149E604, 0x200
sBanetteSprites20:
ax_sprite sBanetteGfx20, 0x200
ax_sprite_terminator
sBanetteGfx21:
.incbin "baserom.gba", 0x149E814, 0x200
sBanetteSprites21:
ax_sprite sBanetteGfx21, 0x200
ax_sprite_terminator
sBanetteGfx22:
.incbin "baserom.gba", 0x149EA24, 0x200
sBanetteSprites22:
ax_sprite sBanetteGfx22, 0x200
ax_sprite_terminator
sBanetteGfx23:
.incbin "baserom.gba", 0x149EC34, 0x200
sBanetteSprites23:
ax_sprite sBanetteGfx23, 0x200
ax_sprite_terminator
sBanetteGfx24:
.incbin "baserom.gba", 0x149EE44, 0x200
sBanetteSprites24:
ax_sprite sBanetteGfx24, 0x200
ax_sprite_terminator
sBanetteGfx25:
.incbin "baserom.gba", 0x149F054, 0x40
sBanetteGfx25_1:
.incbin "baserom.gba", 0x149F094, 0x100
sBanetteSprites25:
ax_sprite 0, 0x20
ax_sprite sBanetteGfx25, 0x40
ax_sprite 0, 0x20
ax_sprite sBanetteGfx25_1, 0x100
ax_sprite 0, 0x80
ax_sprite_terminator
sBanetteGfx26:
.incbin "baserom.gba", 0x149F1C4, 0x100
sBanetteGfx26_1:
.incbin "baserom.gba", 0x149F2C4, 0x60
sBanetteSprites26:
ax_sprite sBanetteGfx26, 0x100
ax_sprite 0, 0x20
ax_sprite sBanetteGfx26_1, 0x60
ax_sprite 0, 0x80
ax_sprite_terminator
sBanetteGfx27:
.incbin "baserom.gba", 0x149F34C, 0xE0
sBanetteGfx27_1:
.incbin "baserom.gba", 0x149F42C, 0x60
sBanetteSprites27:
ax_sprite 0, 0x20
ax_sprite sBanetteGfx27, 0xe0
ax_sprite 0, 0x20
ax_sprite sBanetteGfx27_1, 0x60
ax_sprite 0, 0x80
ax_sprite_terminator
sBanetteGfx28:
.incbin "baserom.gba", 0x149F4BC, 0x140
sBanetteSprites28:
ax_sprite 0, 0x20
ax_sprite sBanetteGfx28, 0x140
ax_sprite 0, 0xa0
ax_sprite_terminator
sBanetteGfx29:
.incbin "baserom.gba", 0x149F61C, 0x60
sBanetteGfx29_1:
.incbin "baserom.gba", 0x149F67C, 0x60
sBanetteGfx29_2:
.incbin "baserom.gba", 0x149F6DC, 0x60
sBanetteGfx29_3:
.incbin "baserom.gba", 0x149F73C, 0x20
sBanetteSprites29:
ax_sprite sBanetteGfx29, 0x60
ax_sprite 0, 0x20
ax_sprite sBanetteGfx29_1, 0x60
ax_sprite 0, 0x20
ax_sprite sBanetteGfx29_2, 0x60
ax_sprite 0, 0x40
ax_sprite sBanetteGfx29_3, 0x20
ax_sprite 0, 0x40
ax_sprite_terminator
sBanetteGfx30:
.incbin "baserom.gba", 0x149F7A4, 0x60
sBanetteGfx30_1:
.incbin "baserom.gba", 0x149F804, 0x80
sBanetteGfx30_2:
.incbin "baserom.gba", 0x149F884, 0x60
sBanetteSprites30:
ax_sprite sBanetteGfx30, 0x60
ax_sprite 0, 0x20
ax_sprite sBanetteGfx30_1, 0x80
ax_sprite 0, 0x20
ax_sprite sBanetteGfx30_2, 0x60
ax_sprite 0, 0x80
ax_sprite_terminator
sBanetteGfx31:
.incbin "baserom.gba", 0x149F91C, 0x60
sBanetteGfx31_1:
.incbin "baserom.gba", 0x149F97C, 0xE0
sBanetteSprites31:
ax_sprite sBanetteGfx31, 0x60
ax_sprite 0, 0x20
ax_sprite sBanetteGfx31_1, 0xe0
ax_sprite 0, 0xa0
ax_sprite_terminator
sBanetteGfx32:
.incbin "baserom.gba", 0x149FA84, 0x160
sBanetteSprites32:
ax_sprite sBanetteGfx32, 0x160
ax_sprite 0, 0xa0
ax_sprite_terminator
sBanetteGfx33:
.incbin "baserom.gba", 0x149FBFC, 0x60
sBanetteGfx33_1:
.incbin "baserom.gba", 0x149FC5C, 0x60
sBanetteGfx33_2:
.incbin "baserom.gba", 0x149FCBC, 0x40
sBanetteSprites33:
ax_sprite sBanetteGfx33, 0x60
ax_sprite 0, 0x20
ax_sprite sBanetteGfx33_1, 0x60
ax_sprite 0, 0x40
ax_sprite sBanetteGfx33_2, 0x40
ax_sprite 0, 0xa0
ax_sprite_terminator
sBanetteGfx34:
.incbin "baserom.gba", 0x149FD34, 0x20
sBanetteGfx34_1:
.incbin "baserom.gba", 0x149FD54, 0x40
sBanetteGfx34_2:
.incbin "baserom.gba", 0x149FD94, 0x80
sBanetteSprites34:
ax_sprite sBanetteGfx34, 0x20
ax_sprite 0, 0x60
ax_sprite sBanetteGfx34_1, 0x40
ax_sprite 0, 0x40
ax_sprite sBanetteGfx34_2, 0x80
ax_sprite 0, 0x80
ax_sprite_terminator
sBanetteGfx35:
.incbin "baserom.gba", 0x149FE4C, 0x60
sBanetteGfx35_1:
.incbin "baserom.gba", 0x149FEAC, 0x60
sBanetteGfx35_2:
.incbin "baserom.gba", 0x149FF0C, 0x60
sBanetteSprites35:
ax_sprite sBanetteGfx35, 0x60
ax_sprite 0, 0x20
ax_sprite sBanetteGfx35_1, 0x60
ax_sprite 0, 0x40
ax_sprite sBanetteGfx35_2, 0x60
ax_sprite 0, 0x80
ax_sprite_terminator
sBanetteGfx36:
.incbin "baserom.gba", 0x149FFA4, 0x60
sBanetteGfx36_1:
.incbin "baserom.gba", 0x14A0004, 0x60
sBanetteGfx36_2:
.incbin "baserom.gba", 0x14A0064, 0x60
sBanetteSprites36:
ax_sprite 0, 0x20
ax_sprite sBanetteGfx36, 0x60
ax_sprite 0, 0x20
ax_sprite sBanetteGfx36_1, 0x60
ax_sprite 0, 0x20
ax_sprite sBanetteGfx36_2, 0x60
ax_sprite 0, 0x80
ax_sprite_terminator
sBanetteGfx37:
.incbin "baserom.gba", 0x14A0104, 0x40
sBanetteGfx37_1:
.incbin "baserom.gba", 0x14A0144, 0x20
sBanetteGfx37_2:
.incbin "baserom.gba", 0x14A0164, 0x60
sBanetteSprites37:
ax_sprite sBanetteGfx37, 0x40
ax_sprite 0, 0x40
ax_sprite sBanetteGfx37_1, 0x20
ax_sprite 0, 0x60
ax_sprite sBanetteGfx37_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sBanetteGfx38:
.incbin "baserom.gba", 0x14A01FC, 0x60
sBanetteGfx38_1:
.incbin "baserom.gba", 0x14A025C, 0x60
sBanetteGfx38_2:
.incbin "baserom.gba", 0x14A02BC, 0x40
sBanetteGfx38_3:
.incbin "baserom.gba", 0x14A02FC, 0x20
sBanetteSprites38:
ax_sprite 0, 0x20
ax_sprite sBanetteGfx38, 0x60
ax_sprite 0, 0x20
ax_sprite sBanetteGfx38_1, 0x60
ax_sprite 0, 0x20
ax_sprite sBanetteGfx38_2, 0x40
ax_sprite 0, 0x60
ax_sprite sBanetteGfx38_3, 0x20
ax_sprite 0, 0x20
ax_sprite_terminator
sBanetteGfx39:
.incbin "baserom.gba", 0x14A036C, 0x160
sBanetteSprites39:
ax_sprite 0, 0x20
ax_sprite sBanetteGfx39, 0x160
ax_sprite 0, 0x80
ax_sprite_terminator
sBanetteGfx40:
.incbin "baserom.gba", 0x14A04EC, 0x60
sBanetteGfx40_1:
.incbin "baserom.gba", 0x14A054C, 0x40
sBanetteSprites40:
ax_sprite sBanetteGfx40, 0x60
ax_sprite 0, 0x20
ax_sprite sBanetteGfx40_1, 0x40
ax_sprite 0, 0x40
ax_sprite_terminator
sBanetteGfx41:
.incbin "baserom.gba", 0x14A05B4, 0x60
sBanetteGfx41_1:
.incbin "baserom.gba", 0x14A0614, 0x60
sBanetteGfx41_2:
.incbin "baserom.gba", 0x14A0674, 0x60
sBanetteSprites41:
ax_sprite 0, 0x20
ax_sprite sBanetteGfx41, 0x60
ax_sprite 0, 0x20
ax_sprite sBanetteGfx41_1, 0x60
ax_sprite 0, 0x20
ax_sprite sBanetteGfx41_2, 0x60
ax_sprite 0, 0x80
ax_sprite_terminator
sBanetteGfx42:
.incbin "baserom.gba", 0x14A0714, 0x100
sBanetteGfx42_1:
.incbin "baserom.gba", 0x14A0814, 0x40
sBanetteSprites42:
ax_sprite sBanetteGfx42, 0x100
ax_sprite 0, 0x20
ax_sprite sBanetteGfx42_1, 0x40
ax_sprite 0, 0xa0
ax_sprite_terminator
sBanetteGfx43:
.incbin "baserom.gba", 0x14A087C, 0x60
sBanetteGfx43_1:
.incbin "baserom.gba", 0x14A08DC, 0x40
sBanetteSprites43:
ax_sprite sBanetteGfx43, 0x60
ax_sprite 0, 0x20
ax_sprite sBanetteGfx43_1, 0x40
ax_sprite 0, 0x40
ax_sprite_terminator
sBanetteGfx44:
.incbin "baserom.gba", 0x14A0944, 0x180
sBanetteSprites44:
ax_sprite sBanetteGfx44, 0x180
ax_sprite 0, 0x80
ax_sprite_terminator
sBanetteGfx45:
.incbin "baserom.gba", 0x14A0ADC, 0x60
sBanetteGfx45_1:
.incbin "baserom.gba", 0x14A0B3C, 0x60
sBanetteGfx45_2:
.incbin "baserom.gba", 0x14A0B9C, 0x60
sBanetteSprites45:
ax_sprite sBanetteGfx45, 0x60
ax_sprite 0, 0x20
ax_sprite sBanetteGfx45_1, 0x60
ax_sprite 0, 0x20
ax_sprite sBanetteGfx45_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sBanetteGfx46:
.incbin "baserom.gba", 0x14A0C34, 0x60
sBanetteGfx46_1:
.incbin "baserom.gba", 0x14A0C94, 0x60
sBanetteGfx46_2:
.incbin "baserom.gba", 0x14A0CF4, 0x60
sBanetteSprites46:
ax_sprite sBanetteGfx46, 0x60
ax_sprite 0, 0x20
ax_sprite sBanetteGfx46_1, 0x60
ax_sprite 0, 0x20
ax_sprite sBanetteGfx46_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sBanetteGfx47:
.incbin "baserom.gba", 0x14A0D8C, 0xA0
sBanetteSprites47:
ax_sprite sBanetteGfx47, 0xa0
ax_sprite 0, 0x160
ax_sprite_terminator
sBanetteGfx48:
.incbin "baserom.gba", 0x14A0E44, 0x180
sBanetteSprites48:
ax_sprite sBanetteGfx48, 0x180
ax_sprite 0, 0x80
ax_sprite_terminator
sBanetteGfx49:
.incbin "baserom.gba", 0x14A0FDC, 0x60
sBanetteGfx49_1:
.incbin "baserom.gba", 0x14A103C, 0x100
sBanetteSprites49:
ax_sprite sBanetteGfx49, 0x60
ax_sprite 0, 0x20
ax_sprite sBanetteGfx49_1, 0x100
ax_sprite 0, 0x80
ax_sprite_terminator
sBanetteGfx50:
.incbin "baserom.gba", 0x14A1164, 0x60
sBanetteGfx50_1:
.incbin "baserom.gba", 0x14A11C4, 0x60
sBanetteGfx50_2:
.incbin "baserom.gba", 0x14A1224, 0x60
sBanetteSprites50:
ax_sprite sBanetteGfx50, 0x60
ax_sprite 0, 0x20
ax_sprite sBanetteGfx50_1, 0x60
ax_sprite 0, 0x20
ax_sprite sBanetteGfx50_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sBanetteGfx51:
.incbin "baserom.gba", 0x14A12BC, 0x60
sBanetteGfx51_1:
.incbin "baserom.gba", 0x14A131C, 0x60
sBanetteGfx51_2:
.incbin "baserom.gba", 0x14A137C, 0x60
sBanetteSprites51:
ax_sprite sBanetteGfx51, 0x60
ax_sprite 0, 0x20
ax_sprite sBanetteGfx51_1, 0x60
ax_sprite 0, 0x20
ax_sprite sBanetteGfx51_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sBanetteGfx52:
.incbin "baserom.gba", 0x14A1414, 0x60
sBanetteGfx52_1:
.incbin "baserom.gba", 0x14A1474, 0x60
sBanetteGfx52_2:
.incbin "baserom.gba", 0x14A14D4, 0x60
sBanetteGfx52_3:
.incbin "baserom.gba", 0x14A1534, 0x20
sBanetteSprites52:
ax_sprite sBanetteGfx52, 0x60
ax_sprite 0, 0x20
ax_sprite sBanetteGfx52_1, 0x60
ax_sprite 0, 0x20
ax_sprite sBanetteGfx52_2, 0x60
ax_sprite 0, 0x40
ax_sprite sBanetteGfx52_3, 0x20
ax_sprite 0, 0x40
ax_sprite_terminator
sBanetteGfx53:
.incbin "baserom.gba", 0x14A159C, 0x20
sBanetteSprites53:
ax_sprite sBanetteGfx53, 0x20
ax_sprite_terminator
sBanetteGfx54:
.incbin "baserom.gba", 0x14A15CC, 0x60
sBanetteGfx54_1:
.incbin "baserom.gba", 0x14A162C, 0x60
sBanetteGfx54_2:
.incbin "baserom.gba", 0x14A168C, 0x60
sBanetteSprites54:
ax_sprite sBanetteGfx54, 0x60
ax_sprite 0, 0x20
ax_sprite sBanetteGfx54_1, 0x60
ax_sprite 0, 0x20
ax_sprite sBanetteGfx54_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sBanetteGfx55:
.incbin "baserom.gba", 0x14A1724, 0x20
sBanetteSprites55:
ax_sprite sBanetteGfx55, 0x20
ax_sprite_terminator
sBanetteGfx56:
.incbin "baserom.gba", 0x14A1754, 0x20
sBanetteSprites56:
ax_sprite sBanetteGfx56, 0x20
ax_sprite_terminator
sBanetteGfx57:
.incbin "baserom.gba", 0x14A1784, 0x80
sBanetteSprites57:
ax_sprite sBanetteGfx57, 0x80
ax_sprite_terminator
sBanetteGfx58:
.incbin "baserom.gba", 0x14A1814, 0x80
sBanetteSprites58:
ax_sprite sBanetteGfx58, 0x80
ax_sprite_terminator
sBanetteGfx59:
.incbin "baserom.gba", 0x14A18A4, 0x80
sBanetteSprites59:
ax_sprite sBanetteGfx59, 0x80
ax_sprite_terminator
sBanetteGfx60:
.incbin "baserom.gba", 0x14A1934, 0x60
sBanetteGfx60_1:
.incbin "baserom.gba", 0x14A1994, 0x60
sBanetteGfx60_2:
.incbin "baserom.gba", 0x14A19F4, 0x60
sBanetteSprites60:
ax_sprite sBanetteGfx60, 0x60
ax_sprite 0, 0x20
ax_sprite sBanetteGfx60_1, 0x60
ax_sprite 0, 0x20
ax_sprite sBanetteGfx60_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sBanetteGfx61:
.incbin "baserom.gba", 0x14A1A8C, 0x60
sBanetteGfx61_1:
.incbin "baserom.gba", 0x14A1AEC, 0x60
sBanetteGfx61_2:
.incbin "baserom.gba", 0x14A1B4C, 0x60
sBanetteSprites61:
ax_sprite sBanetteGfx61, 0x60
ax_sprite 0, 0x20
ax_sprite sBanetteGfx61_1, 0x60
ax_sprite 0, 0x20
ax_sprite sBanetteGfx61_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sBanetteGfx62:
.incbin "baserom.gba", 0x14A1BE4, 0x200
sBanetteSprites62:
ax_sprite sBanetteGfx62, 0x200
ax_sprite_terminator
sBanetteGfx63:
.incbin "baserom.gba", 0x14A1DF4, 0x200
sBanetteSprites63:
ax_sprite sBanetteGfx63, 0x200
ax_sprite_terminator
sBanetteGfx64:
.incbin "baserom.gba", 0x14A2004, 0x200
sBanetteSprites64:
ax_sprite sBanetteGfx64, 0x200
ax_sprite_terminator
sBanetteGfx65:
.incbin "baserom.gba", 0x14A2214, 0x200
sBanetteSprites65:
ax_sprite sBanetteGfx65, 0x200
ax_sprite_terminator
sBanetteGfx66:
.incbin "baserom.gba", 0x14A2424, 0x200
sBanetteSprites66:
ax_sprite sBanetteGfx66, 0x200
ax_sprite_terminator
sBanetteGfx67:
.incbin "baserom.gba", 0x14A2634, 0x200
sBanetteSprites67:
ax_sprite sBanetteGfx67, 0x200
ax_sprite_terminator
sBanetteGfx68:
.incbin "baserom.gba", 0x14A2844, 0x200
sBanetteSprites68:
ax_sprite sBanetteGfx68, 0x200
ax_sprite_terminator
sBanetteGfx69:
.incbin "baserom.gba", 0x14A2A54, 0x200
sBanetteSprites69:
ax_sprite sBanetteGfx69, 0x200
ax_sprite_terminator
sBanetteGfx70:
.incbin "baserom.gba", 0x14A2C64, 0x200
sBanetteSprites70:
ax_sprite sBanetteGfx70, 0x200
ax_sprite_terminator
sAxPosesBanette:
.4byte sBanettePose1
.4byte sBanettePose2
.4byte sBanettePose3
.4byte sBanettePose4
.4byte sBanettePose5
.4byte sBanettePose6
.4byte sBanettePose7
.4byte sBanettePose8
.4byte sBanettePose9
.4byte sBanettePose10
.4byte sBanettePose11
.4byte sBanettePose12
.4byte sBanettePose13
.4byte sBanettePose14
.4byte sBanettePose15
.4byte sBanettePose16
.4byte sBanettePose17
.4byte sBanettePose18
.4byte sBanettePose19
.4byte sBanettePose20
.4byte sBanettePose21
.4byte sBanettePose22
.4byte sBanettePose23
.4byte sBanettePose24
.4byte sBanettePose25
.4byte sBanettePose26
.4byte sBanettePose27
.4byte sBanettePose28
.4byte sBanettePose29
.4byte sBanettePose30
.4byte sBanettePose31
.4byte sBanettePose32
.4byte sBanettePose33
.4byte sBanettePose34
.4byte sBanettePose35
.4byte sBanettePose36
.4byte sBanettePose37
.4byte sBanettePose38
.4byte sBanettePose39
.4byte sBanettePose40
.4byte sBanettePose41
.4byte sBanettePose42
.4byte sBanettePose43
.4byte sBanettePose44
.4byte sBanettePose45
.4byte sBanettePose46
.4byte sBanettePose47
.4byte sBanettePose48
.4byte sBanettePose49
.4byte sBanettePose50
.4byte sBanettePose51
.4byte sBanettePose52
.4byte sBanettePose53
.4byte sBanettePose54
.4byte sBanettePose55
.4byte sBanettePose56
.4byte sBanettePose57
.4byte sBanettePose58
.4byte sBanettePose59
.4byte sBanettePose60
.4byte sBanettePose61
.4byte sBanettePose62
.4byte sBanettePose63
.4byte sBanettePose64
.4byte sBanettePose65
.4byte sBanettePose66
.4byte sBanettePose67
.4byte sBanettePose68
.4byte sBanettePose69
.4byte sBanettePose70
.4byte sBanettePose71
.4byte sBanettePose72
.4byte sBanettePose73
.4byte sBanettePose74
.4byte sBanettePose75
.4byte sBanettePose76
.4byte sBanettePose77
.4byte sBanettePose78
.4byte sBanettePose79
.4byte sBanettePose80
.4byte sBanettePose81
.4byte sBanettePose82
.4byte sBanettePose83
.4byte sBanettePose84
.4byte sBanettePose85
.4byte sBanettePose86
.4byte sBanettePose87
.4byte sBanettePose88
.4byte sBanettePose89
.4byte sBanettePose90
.4byte sBanettePose91
.4byte sBanettePose92
.4byte sBanettePose93
.4byte sBanettePose94
.4byte sBanettePose95
.4byte sBanettePose96
.4byte sBanettePose97
.4byte sBanettePose98
.4byte sBanettePose99
.4byte sBanettePose100
.4byte sBanettePose101
.4byte sBanettePose102
.4byte sBanettePose103
.4byte sBanettePose104
.4byte sBanettePose105
.4byte sBanettePose106
.4byte sBanettePose107
.4byte sBanettePose108
.4byte sBanettePose109
.4byte sBanettePose110
.4byte sBanettePose111
.4byte sBanettePose112
.4byte sBanettePose113
.4byte sBanettePose114
.4byte sBanettePose115
.4byte sBanettePose116
.4byte sBanettePose117
.4byte sBanettePose118
.4byte sBanettePose119
.4byte sBanettePose120
.4byte sBanettePose121
.4byte sBanettePose122
.4byte sBanettePose123
.4byte sBanettePose124
.4byte sBanettePose125
.4byte sBanettePose126
.4byte sBanettePose127
.4byte sBanettePose128
.4byte sBanettePose129
.4byte sBanettePose130
.4byte sBanettePose131
.4byte sBanettePose132
.4byte sBanettePose133
.4byte sBanettePose134
.4byte sBanettePose135
.4byte sBanettePose136
.4byte sBanettePose137
.4byte sBanettePose138
.4byte sBanettePose139
.4byte sBanettePose140
.4byte sBanettePose141
.4byte sBanettePose142
.4byte sBanettePose143
.4byte sBanettePose144
.4byte sBanettePose145
.4byte sBanettePose146
.4byte sBanettePose147
.4byte sBanettePose148
.4byte sBanettePose149
.4byte sBanettePose150
.4byte sBanettePose151
.4byte sBanettePose152
.4byte sBanettePose153
.4byte sBanettePose154
.4byte sBanettePose155
.4byte sBanettePose156
.4byte sBanettePose157
.4byte sBanettePose158
.4byte sBanettePose159
.4byte sBanettePose160
.4byte sBanettePose161
.4byte sBanettePose162
.4byte sBanettePose163
.4byte sBanettePose164
.4byte sBanettePose165
.4byte sBanettePose166
.4byte sBanettePose167
.4byte sBanettePose168
.4byte sBanettePose169
.4byte sBanettePose170
.4byte sBanettePose171
.4byte sBanettePose172
.4byte sBanettePose173
.4byte sBanettePose174
.4byte sBanettePose175
.4byte sBanettePose176
.4byte sBanettePose177
.4byte sBanettePose178
.4byte sBanettePose179
.4byte sBanettePose180
.4byte sBanettePose181
.4byte sBanettePose182
.4byte sBanettePose183
.4byte sBanettePose184
.4byte sBanettePose185
.4byte sBanettePose186
.4byte sBanettePose187
.4byte sBanettePose188
.4byte sBanettePose189
.4byte sBanettePose190
.4byte sBanettePose191
.4byte sBanettePose192
.4byte sBanettePose193
.4byte sBanettePose194
.4byte sBanettePose195
.4byte sBanettePose196
.4byte sBanettePose197
.4byte sBanettePose198
.4byte sBanettePose199
.4byte sBanettePose200
.4byte sBanettePose201
.4byte sBanettePose202
.4byte sBanettePose203
.4byte sBanettePose204
.4byte sBanettePose205
.4byte sBanettePose206
.4byte sBanettePose207
.4byte sBanettePose208
.4byte sBanettePose209
.4byte sBanettePose210
.4byte sBanettePose211
.4byte sBanettePose212
.4byte sBanettePose213
.4byte sBanettePose214
.4byte sBanettePose215
.4byte sBanettePose216
.4byte sBanettePose217
.4byte sBanettePose218
.4byte sBanettePose219
.4byte sBanettePose220
.4byte sBanettePose221
.4byte sBanettePose222
.4byte sBanettePose223
sAxPositionsBanette:
.2byte    0,  -10, 	  -8,   -6, 	   7,   -6, 	   0,  -11
.2byte    0,   -9, 	  -7,   -5, 	   6,   -3, 	   0,  -10
.2byte    0,   -9, 	  -7,   -3, 	   7,   -6, 	   0,  -10
.2byte    5,  -11, 	  -1,   -5, 	   7,   -8, 	   2,   -9
.2byte    4,  -10, 	   1,   -4, 	   5,   -7, 	   2,   -8
.2byte    4,  -10, 	  -3,   -4, 	   7,   -6, 	   2,   -8
.2byte    6,  -12, 	   5,   -6, 	   6,  -10, 	   1,   -9
.2byte    6,  -11, 	   7,   -5, 	   1,   -8, 	   0,   -8
.2byte    6,  -11, 	   4,   -4, 	   6,   -8, 	   1,   -8
.2byte    5,  -14, 	   7,   -8, 	  -1,  -10, 	   2,  -10
.2byte    5,  -13, 	   7,   -8, 	  -1,   -8, 	   2,   -9
.2byte    5,  -13, 	   6,   -6, 	   2,  -10, 	   1,   -9
.2byte    0,  -15, 	   6,  -10, 	  -7,  -10, 	   0,  -12
.2byte    0,  -15, 	   6,   -8, 	  -6,  -10, 	   0,  -10
.2byte    0,  -14, 	   4,  -10, 	  -7,   -8, 	   0,  -10
.2byte   -6,  -14, 	  -1,  -10, 	  -8,   -7, 	  -2,  -11
.2byte   -6,  -13, 	   0,   -9, 	  -7,   -7, 	  -2,  -10
.2byte   -6,  -13, 	  -3,  -10, 	  -7,   -5, 	  -2,  -10
.2byte   -7,  -12, 	  -7,  -10, 	  -7,   -6, 	  -2,  -11
.2byte   -7,  -11, 	  -2,   -9, 	  -8,   -5, 	  -2,  -10
.2byte   -7,  -11, 	  -7,   -8, 	  -6,   -4, 	  -2,   -9
.2byte   -5,  -11, 	  -8,   -8, 	  -1,   -5, 	  -2,  -12
.2byte   -5,  -10, 	  -7,   -6, 	  -2,   -3, 	  -2,  -11
.2byte   -5,  -10, 	  -8,   -6, 	   2,   -4, 	  -2,  -11
.2byte    0,  -10, 	  -8,   -6, 	   7,   -6, 	   0,  -11
.2byte    0,   -8, 	 -11,  -10, 	  10,  -10, 	   0,  -11
.2byte    5,  -11, 	  -1,   -5, 	   7,   -8, 	   2,   -9
.2byte    5,   -9, 	  -3,   -8, 	  12,  -12, 	   1,  -13
.2byte    6,  -12, 	   5,   -6, 	   6,  -10, 	   1,   -9
.2byte    6,  -11, 	   8,   -9, 	  11,  -14, 	   2,  -11
.2byte    5,  -14, 	   7,   -8, 	  -1,  -10, 	   2,  -10
.2byte    6,  -14, 	  11,  -11, 	   4,  -14, 	   1,  -10
.2byte    0,  -15, 	   6,  -10, 	  -7,  -10, 	   0,  -12
.2byte    0,  -17, 	   7,  -14, 	  -8,  -14, 	   0,  -11
.2byte   -6,  -14, 	  -1,  -10, 	  -8,   -7, 	  -2,  -11
.2byte   -7,  -13, 	  -3,  -15, 	 -12,  -11, 	  -1,  -11
.2byte   -7,  -12, 	  -7,  -10, 	  -7,   -6, 	  -2,  -11
.2byte   -8,  -11, 	 -12,  -14, 	  -9,   -9, 	  -1,  -10
.2byte   -5,  -11, 	  -8,   -8, 	  -1,   -5, 	  -2,  -12
.2byte   -7,  -10, 	 -13,  -12, 	   2,   -8, 	   0,  -12
.2byte    0,  -10, 	  -8,   -6, 	   7,   -6, 	   0,  -11
.2byte   -1,  -10, 	 -10,  -16, 	  -3,   -5, 	  -1,  -12
.2byte    4,  -10, 	   6,   -5, 	   6,  -11, 	   1,  -10
.2byte    4,  -10, 	   6,   -5, 	   6,  -11, 	   1,  -10
.2byte    5,  -11, 	  -1,   -5, 	   7,   -8, 	   2,   -9
.2byte    5,  -11, 	   5,   -5, 	   5,  -20, 	   0,  -10
.2byte    1,  -10, 	  -5,   -8, 	  -1,   -3, 	   1,  -11
.2byte    1,  -10, 	  -5,   -8, 	  -1,   -3, 	   1,  -11
.2byte    6,  -12, 	   5,   -6, 	   6,  -10, 	   1,   -9
.2byte    5,  -11, 	   8,   -7, 	  -4,  -13, 	   1,  -10
.2byte    5,  -11, 	  -2,   -6, 	   4,   -4, 	   1,  -10
.2byte    5,  -11, 	  -2,   -6, 	   4,   -4, 	   1,  -10
.2byte    5,  -14, 	   7,   -8, 	  -1,  -10, 	   2,  -10
.2byte    5,  -14, 	  -7,  -17, 	   9,  -11, 	   0,  -10
.2byte    5,  -11, 	   2,   -6, 	   7,   -5, 	   1,  -10
.2byte    5,  -11, 	   2,   -6, 	   7,   -5, 	   1,  -10
.2byte    0,  -15, 	   6,  -10, 	  -7,  -10, 	   0,  -12
.2byte    1,  -18, 	   9,  -16, 	  -3,  -14, 	   0,  -12
.2byte   -6,  -16, 	  -9,   -7, 	  -2,  -15, 	  -2,  -11
.2byte   -6,  -16, 	  -9,   -7, 	  -2,  -15, 	  -2,  -11
.2byte   -6,  -14, 	  -1,  -10, 	  -8,   -7, 	  -2,  -11
.2byte   -6,  -14, 	   6,  -17, 	 -10,  -11, 	  -1,  -10
.2byte   -6,  -11, 	  -7,   -8, 	  -3,   -6, 	  -2,  -10
.2byte   -6,  -11, 	  -7,   -8, 	  -3,   -6, 	  -2,  -10
.2byte   -7,  -12, 	  -7,  -10, 	  -7,   -6, 	  -2,  -11
.2byte   -6,  -11, 	   3,  -14, 	  -9,   -7, 	  -1,  -10
.2byte   -6,  -12, 	  -5,   -4, 	   1,   -7, 	  -2,   -9
.2byte   -6,  -12, 	  -5,   -4, 	   1,   -7, 	  -2,   -9
.2byte   -5,  -11, 	  -8,   -8, 	  -1,   -5, 	  -2,  -12
.2byte   -6,  -12, 	  -6,  -20, 	  -6,   -5, 	  -1,  -10
.2byte   -2,  -10, 	  -1,   -3, 	   4,   -8, 	  -2,   -8
.2byte   -2,  -10, 	  -1,   -3, 	   4,   -8, 	  -2,   -8
.2byte    0,   -9, 	  -7,   -5, 	   6,   -3, 	   0,  -10
.2byte   -4,  -10, 	  -6,   -6, 	  -1,   -3, 	  -1,  -11
.2byte   -6,  -11, 	  -1,   -9, 	  -7,   -5, 	  -1,  -10
.2byte   -4,  -13, 	   2,   -9, 	  -5,   -7, 	   0,  -10
.2byte    0,  -15, 	   6,   -8, 	  -6,  -10, 	   0,  -10
.2byte    4,  -13, 	   6,   -8, 	  -2,   -8, 	   1,   -9
.2byte    6,  -11, 	   7,   -5, 	   1,   -8, 	   0,   -8
.2byte    4,  -10, 	   1,   -4, 	   5,   -7, 	   2,   -8
.2byte    0,  -10, 	  -8,   -6, 	   7,   -6, 	   0,  -11
.2byte    0,  -10, 	  -7,   -7, 	   6,   -7, 	   0,   -9
.2byte    0,  -10, 	  -7,   -7, 	   6,   -7, 	   0,   -9
.2byte    0,  -10, 	  -7,   -7, 	   6,   -7, 	   0,   -9
.2byte    0,  -10, 	  -7,   -7, 	   6,   -7, 	   0,   -9
.2byte    0,  -10, 	  -7,   -7, 	   6,   -7, 	   0,   -9
.2byte    0,  -10, 	  -7,   -7, 	   6,   -7, 	   0,   -9
.2byte    0,  -10, 	  -7,   -7, 	   6,   -7, 	   0,   -9
.2byte    5,  -11, 	  -1,   -5, 	   7,   -8, 	   2,   -9
.2byte    5,  -11, 	  -1,   -5, 	   7,   -8, 	   2,   -9
.2byte    5,  -11, 	  -1,   -5, 	   7,   -8, 	   2,   -9
.2byte    5,  -11, 	  -1,   -5, 	   7,   -8, 	   2,   -9
.2byte    5,  -11, 	  -1,   -5, 	   7,   -8, 	   2,   -9
.2byte    5,  -11, 	  -1,   -5, 	   7,   -8, 	   2,   -9
.2byte    5,  -11, 	  -1,   -5, 	   7,   -8, 	   2,   -9
.2byte    5,  -11, 	  -1,   -5, 	   7,   -8, 	   2,   -9
.2byte    6,  -12, 	   5,   -6, 	   6,  -10, 	   1,   -9
.2byte    6,  -12, 	   5,   -6, 	   6,  -10, 	   1,   -9
.2byte    6,  -12, 	   5,   -6, 	   6,  -10, 	   1,   -9
.2byte    6,  -12, 	   5,   -6, 	   6,  -10, 	   1,   -9
.2byte    6,  -12, 	   5,   -6, 	   6,  -10, 	   1,   -9
.2byte    6,  -12, 	   5,   -6, 	   6,  -10, 	   1,   -9
.2byte    6,  -12, 	   5,   -6, 	   6,  -10, 	   1,   -9
.2byte    6,  -12, 	   5,   -6, 	   6,  -10, 	   1,   -9
.2byte    5,  -14, 	   7,   -8, 	  -1,  -10, 	   2,  -10
.2byte    5,  -14, 	   7,   -8, 	  -1,  -10, 	   2,  -10
.2byte    5,  -14, 	   7,   -8, 	  -1,  -10, 	   2,  -10
.2byte    5,  -14, 	   7,   -8, 	  -1,  -10, 	   2,  -10
.2byte    5,  -14, 	   7,   -8, 	  -1,  -10, 	   2,  -10
.2byte    5,  -14, 	   7,   -8, 	  -1,  -10, 	   2,  -10
.2byte    5,  -14, 	   7,   -8, 	  -1,  -10, 	   2,  -10
.2byte    0,  -15, 	   6,  -10, 	  -7,  -10, 	   0,  -12
.2byte    0,  -15, 	   6,  -10, 	  -7,  -10, 	   0,  -12
.2byte    0,  -15, 	   6,  -10, 	  -7,  -10, 	   0,  -12
.2byte    0,  -15, 	   6,  -10, 	  -7,  -10, 	   0,  -12
.2byte    0,  -15, 	   6,  -10, 	  -7,  -10, 	   0,  -12
.2byte    0,  -15, 	   6,  -10, 	  -7,  -10, 	   0,  -12
.2byte    0,  -15, 	   6,  -10, 	  -7,  -10, 	   0,  -12
.2byte   -6,  -14, 	  -1,  -10, 	  -8,   -7, 	  -2,  -11
.2byte   -6,  -14, 	  -1,  -10, 	  -8,   -7, 	  -2,  -11
.2byte   -6,  -14, 	  -1,  -10, 	  -8,   -7, 	  -2,  -11
.2byte   -6,  -14, 	  -1,  -10, 	  -8,   -7, 	  -2,  -11
.2byte   -6,  -14, 	  -1,  -10, 	  -8,   -7, 	  -2,  -11
.2byte   -6,  -14, 	  -1,  -10, 	  -8,   -7, 	  -2,  -11
.2byte   -6,  -14, 	  -1,  -10, 	  -8,   -7, 	  -2,  -11
.2byte   -7,  -12, 	  -7,  -10, 	  -7,   -6, 	  -2,  -11
.2byte   -7,  -12, 	  -7,  -10, 	  -7,   -6, 	  -2,  -10
.2byte   -7,  -12, 	  -7,  -10, 	  -7,   -6, 	  -2,  -10
.2byte   -7,  -12, 	  -7,  -10, 	  -7,   -6, 	  -2,  -10
.2byte   -7,  -12, 	  -7,  -10, 	  -7,   -6, 	  -2,  -10
.2byte   -7,  -12, 	  -7,  -10, 	  -7,   -6, 	  -2,  -10
.2byte   -7,  -12, 	  -7,  -10, 	  -7,   -6, 	  -2,  -10
.2byte   -7,  -12, 	  -7,  -10, 	  -7,   -6, 	  -2,  -10
.2byte   -5,  -11, 	  -8,   -8, 	  -1,   -5, 	  -2,  -12
.2byte   -5,  -11, 	  -7,   -8, 	  -1,   -6, 	  -2,  -10
.2byte   -5,  -11, 	  -7,   -8, 	  -1,   -6, 	  -2,  -10
.2byte   -5,  -11, 	  -7,   -8, 	  -1,   -6, 	  -2,  -10
.2byte   -5,  -11, 	  -7,   -8, 	  -1,   -6, 	  -2,  -10
.2byte   -5,  -11, 	  -7,   -8, 	  -1,   -6, 	  -2,  -10
.2byte   -5,  -11, 	  -7,   -8, 	  -1,   -6, 	  -2,  -10
.2byte   -5,  -11, 	  -7,   -8, 	  -1,   -6, 	  -2,  -10
.2byte   -4,   -5, 	  -7,   -4, 	   6,    0, 	   0,   -3
.2byte   -4,   -6, 	  -6,   -4, 	   6,    0, 	  -1,   -4
.2byte    0,  -14, 	 -11,  -18, 	  10,  -18, 	   0,  -10
.2byte   -1,  -12, 	   3,  -15, 	 -11,  -13, 	  -3,  -10
.2byte    0,  -13, 	  -7,  -16, 	  -9,  -12, 	  -5,  -10
.2byte   -2,  -15, 	  -8,  -13, 	   2,  -13, 	  -5,   -8
.2byte    0,  -14, 	   8,  -12, 	  -9,  -12, 	   0,   -9
.2byte    1,  -15, 	   7,  -13, 	  -3,  -13, 	   4,   -8
.2byte   -1,  -13, 	   6,  -13, 	   9,  -12, 	   4,  -10
.2byte    0,  -13, 	  -4,  -15, 	  10,  -13, 	   2,  -10
.2byte    0,  -10, 	  -8,   -6, 	   7,   -6, 	   0,  -11
.2byte    0,   -9, 	  -7,   -5, 	   6,   -3, 	   0,  -10
.2byte    0,   -9, 	  -7,   -3, 	   7,   -6, 	   0,  -10
.2byte    5,  -11, 	  -1,   -5, 	   7,   -8, 	   2,   -9
.2byte    4,  -10, 	   1,   -4, 	   5,   -7, 	   2,   -8
.2byte    4,  -10, 	  -3,   -4, 	   7,   -6, 	   2,   -8
.2byte    6,  -12, 	   5,   -6, 	   6,  -10, 	   1,   -9
.2byte    6,  -11, 	   7,   -5, 	   1,   -8, 	   0,   -8
.2byte    6,  -11, 	   4,   -4, 	   6,   -8, 	   1,   -8
.2byte    5,  -14, 	   7,   -8, 	  -1,  -10, 	   2,  -10
.2byte    5,  -13, 	   7,   -8, 	  -1,   -8, 	   2,   -9
.2byte    5,  -13, 	   6,   -6, 	   2,  -10, 	   1,   -9
.2byte    0,  -15, 	   6,  -10, 	  -7,  -10, 	   0,  -12
.2byte    0,  -15, 	   6,   -8, 	  -6,  -10, 	   0,  -10
.2byte    0,  -14, 	   4,  -10, 	  -7,   -8, 	   0,  -10
.2byte   -6,  -14, 	  -1,  -10, 	  -8,   -7, 	  -2,  -11
.2byte   -6,  -13, 	   0,   -9, 	  -7,   -7, 	  -2,  -10
.2byte   -6,  -13, 	  -3,  -10, 	  -7,   -5, 	  -2,  -10
.2byte   -7,  -12, 	  -7,  -10, 	  -7,   -6, 	  -2,  -11
.2byte   -7,  -11, 	  -2,   -9, 	  -8,   -5, 	  -2,  -10
.2byte   -7,  -11, 	  -7,   -8, 	  -6,   -4, 	  -2,   -9
.2byte   -5,  -11, 	  -8,   -8, 	  -1,   -5, 	  -2,  -12
.2byte   -5,  -10, 	  -7,   -6, 	  -2,   -3, 	  -2,  -11
.2byte   -5,  -10, 	  -8,   -6, 	   2,   -4, 	  -2,  -11
.2byte    0,   -7, 	 -11,   -9, 	  10,   -9, 	   0,  -10
.2byte   -7,   -9, 	 -13,  -11, 	   2,   -7, 	   0,  -11
.2byte   -8,  -10, 	 -12,  -13, 	  -9,   -8, 	  -1,   -9
.2byte   -6,  -13, 	  -2,  -15, 	 -11,  -11, 	   0,  -11
.2byte    0,  -17, 	   7,  -14, 	  -8,  -14, 	   0,  -11
.2byte    5,  -14, 	  10,  -11, 	   3,  -14, 	   0,  -10
.2byte    6,  -10, 	   8,   -8, 	  11,  -13, 	   2,  -10
.2byte    5,   -8, 	  -3,   -7, 	  12,  -11, 	   1,  -12
.2byte    0,   -8, 	 -11,  -10, 	  10,  -10, 	   0,  -11
.2byte    4,   -9, 	  -4,   -8, 	  11,  -12, 	   0,  -13
.2byte    5,  -11, 	   7,   -9, 	  10,  -14, 	   1,  -11
.2byte    5,  -14, 	  10,  -11, 	   3,  -14, 	   0,  -10
.2byte    0,  -17, 	   7,  -14, 	  -8,  -14, 	   0,  -11
.2byte   -6,  -13, 	  -2,  -15, 	 -11,  -11, 	   0,  -11
.2byte   -7,  -11, 	 -11,  -14, 	  -8,   -9, 	   0,  -10
.2byte   -6,  -10, 	 -12,  -12, 	   3,   -8, 	   1,  -12
.2byte    0,  -10, 	  -8,   -6, 	   7,   -6, 	   0,  -11
.2byte    0,   -8, 	 -11,  -10, 	  10,  -10, 	   0,  -11
.2byte    5,  -11, 	  -1,   -5, 	   7,   -8, 	   2,   -9
.2byte    4,   -9, 	  -4,   -8, 	  11,  -12, 	   0,  -13
.2byte    6,  -12, 	   5,   -6, 	   6,  -10, 	   1,   -9
.2byte    5,  -11, 	   7,   -9, 	  10,  -14, 	   1,  -11
.2byte    5,  -14, 	   7,   -8, 	  -1,  -10, 	   2,  -10
.2byte    5,  -14, 	  10,  -11, 	   3,  -14, 	   0,  -10
.2byte    0,  -15, 	   6,  -10, 	  -7,  -10, 	   0,  -12
.2byte    0,  -17, 	   7,  -14, 	  -8,  -14, 	   0,  -11
.2byte   -6,  -14, 	  -1,  -10, 	  -8,   -7, 	  -2,  -11
.2byte   -6,  -13, 	  -2,  -15, 	 -11,  -11, 	   0,  -11
.2byte   -7,  -12, 	  -7,  -10, 	  -7,   -6, 	  -2,  -11
.2byte   -7,  -11, 	 -11,  -14, 	  -8,   -9, 	   0,  -10
.2byte   -5,  -11, 	  -8,   -8, 	  -1,   -5, 	  -2,  -12
.2byte   -6,  -10, 	 -12,  -12, 	   3,   -8, 	   1,  -12
.2byte    0,   -7, 	  -8,   -3, 	   7,   -3, 	   0,   -8
.2byte   -5,   -8, 	  -8,   -5, 	  -1,   -2, 	  -2,   -9
.2byte   -7,   -9, 	  -7,   -7, 	  -7,   -3, 	  -2,   -8
.2byte   -6,  -11, 	  -1,   -7, 	  -8,   -4, 	  -2,   -8
.2byte    0,  -12, 	   6,   -7, 	  -7,   -7, 	   0,   -9
.2byte    5,  -11, 	   7,   -5, 	  -1,   -7, 	   2,   -7
.2byte    6,   -9, 	   5,   -3, 	   6,   -7, 	   1,   -6
.2byte    5,   -8, 	  -1,   -2, 	   7,   -5, 	   2,   -6
.2byte    0,  -10, 	  -8,   -6, 	   7,   -6, 	   0,  -11
.2byte   -5,  -11, 	  -8,   -8, 	  -1,   -5, 	  -2,  -12
.2byte   -7,  -12, 	  -7,  -10, 	  -7,   -6, 	  -2,  -11
.2byte   -6,  -14, 	  -1,  -10, 	  -8,   -7, 	  -2,  -11
.2byte    0,  -15, 	   6,  -10, 	  -7,  -10, 	   0,  -12
.2byte    5,  -14, 	   7,   -8, 	  -1,  -10, 	   2,  -10
.2byte    6,  -12, 	   5,   -6, 	   6,  -10, 	   1,   -9
.2byte    5,  -11, 	  -1,   -5, 	   7,   -8, 	   2,   -9
sBanetteAnimTable1:
.4byte sBanetteAnims_1_1
.4byte sBanetteAnims_1_2
.4byte sBanetteAnims_1_3
.4byte sBanetteAnims_1_4
.4byte sBanetteAnims_1_5
.4byte sBanetteAnims_1_6
.4byte sBanetteAnims_1_7
.4byte sBanetteAnims_1_8
sBanetteAnimTable2:
.4byte sBanetteAnims_2_1
.4byte sBanetteAnims_2_2
.4byte sBanetteAnims_2_3
.4byte sBanetteAnims_2_4
.4byte sBanetteAnims_2_5
.4byte sBanetteAnims_2_6
.4byte sBanetteAnims_2_7
.4byte sBanetteAnims_2_8
sBanetteAnimTable3:
.4byte sBanetteAnims_3_1
.4byte sBanetteAnims_3_2
.4byte sBanetteAnims_3_3
.4byte sBanetteAnims_3_4
.4byte sBanetteAnims_3_5
.4byte sBanetteAnims_3_6
.4byte sBanetteAnims_3_7
.4byte sBanetteAnims_3_8
sBanetteAnimTable4:
.4byte sBanetteAnims_4_1
.4byte sBanetteAnims_4_2
.4byte sBanetteAnims_4_3
.4byte sBanetteAnims_4_4
.4byte sBanetteAnims_4_5
.4byte sBanetteAnims_4_6
.4byte sBanetteAnims_4_7
.4byte sBanetteAnims_4_8
sBanetteAnimTable5:
.4byte sBanetteAnims_5_1
.4byte sBanetteAnims_5_2
.4byte sBanetteAnims_5_3
.4byte sBanetteAnims_5_4
.4byte sBanetteAnims_5_5
.4byte sBanetteAnims_5_6
.4byte sBanetteAnims_5_7
.4byte sBanetteAnims_5_8
sBanetteAnimTable6:
.4byte sBanetteAnims_6_1
.4byte sBanetteAnims_6_1
.4byte sBanetteAnims_6_1
.4byte sBanetteAnims_6_1
.4byte sBanetteAnims_6_1
.4byte sBanetteAnims_6_1
.4byte sBanetteAnims_6_1
.4byte sBanetteAnims_6_1
sBanetteAnimTable7:
.4byte sBanetteAnims_7_1
.4byte sBanetteAnims_7_2
.4byte sBanetteAnims_7_3
.4byte sBanetteAnims_7_4
.4byte sBanetteAnims_7_5
.4byte sBanetteAnims_7_6
.4byte sBanetteAnims_7_7
.4byte sBanetteAnims_7_8
sBanetteAnimTable8:
.4byte sBanetteAnims_8_1
.4byte sBanetteAnims_8_2
.4byte sBanetteAnims_8_3
.4byte sBanetteAnims_8_4
.4byte sBanetteAnims_8_5
.4byte sBanetteAnims_8_6
.4byte sBanetteAnims_8_7
.4byte sBanetteAnims_8_8
sBanetteAnimTable9:
.4byte sBanetteAnims_9_1
.4byte sBanetteAnims_9_2
.4byte sBanetteAnims_9_3
.4byte sBanetteAnims_9_4
.4byte sBanetteAnims_9_5
.4byte sBanetteAnims_9_6
.4byte sBanetteAnims_9_7
.4byte sBanetteAnims_9_8
sBanetteAnimTable10:
.4byte sBanetteAnims_10_1
.4byte sBanetteAnims_10_2
.4byte sBanetteAnims_10_3
.4byte sBanetteAnims_10_4
.4byte sBanetteAnims_10_5
.4byte sBanetteAnims_10_6
.4byte sBanetteAnims_10_7
.4byte sBanetteAnims_10_8
sBanetteAnimTable11:
.4byte sBanetteAnims_11_1
.4byte sBanetteAnims_11_2
.4byte sBanetteAnims_11_3
.4byte sBanetteAnims_11_4
.4byte sBanetteAnims_11_5
.4byte sBanetteAnims_11_6
.4byte sBanetteAnims_11_7
.4byte sBanetteAnims_11_8
sBanetteAnimTable12:
.4byte sBanetteAnims_12_1
.4byte sBanetteAnims_12_2
.4byte sBanetteAnims_12_3
.4byte sBanetteAnims_12_4
.4byte sBanetteAnims_12_5
.4byte sBanetteAnims_12_6
.4byte sBanetteAnims_12_7
.4byte sBanetteAnims_12_8
sBanetteAnimTable13:
.4byte sBanetteAnims_13_1
.4byte sBanetteAnims_13_2
.4byte sBanetteAnims_13_3
.4byte sBanetteAnims_13_4
.4byte sBanetteAnims_13_5
.4byte sBanetteAnims_13_6
.4byte sBanetteAnims_13_7
.4byte sBanetteAnims_13_8
sAxAnimationsBanette:
.4byte sBanetteAnimTable1
.4byte sBanetteAnimTable2
.4byte sBanetteAnimTable3
.4byte sBanetteAnimTable4
.4byte sBanetteAnimTable5
.4byte sBanetteAnimTable6
.4byte sBanetteAnimTable7
.4byte sBanetteAnimTable8
.4byte sBanetteAnimTable9
.4byte sBanetteAnimTable10
.4byte sBanetteAnimTable11
.4byte sBanetteAnimTable12
.4byte sBanetteAnimTable13
sAxSpritesBanette:
.4byte sBanetteSprites1
.4byte sBanetteSprites2
.4byte sBanetteSprites3
.4byte sBanetteSprites4
.4byte sBanetteSprites5
.4byte sBanetteSprites6
.4byte sBanetteSprites7
.4byte sBanetteSprites8
.4byte sBanetteSprites9
.4byte sBanetteSprites10
.4byte sBanetteSprites11
.4byte sBanetteSprites12
.4byte sBanetteSprites13
.4byte sBanetteSprites14
.4byte sBanetteSprites15
.4byte sBanetteSprites16
.4byte sBanetteSprites17
.4byte sBanetteSprites18
.4byte sBanetteSprites19
.4byte sBanetteSprites20
.4byte sBanetteSprites21
.4byte sBanetteSprites22
.4byte sBanetteSprites23
.4byte sBanetteSprites24
.4byte sBanetteSprites25
.4byte sBanetteSprites26
.4byte sBanetteSprites27
.4byte sBanetteSprites28
.4byte sBanetteSprites29
.4byte sBanetteSprites30
.4byte sBanetteSprites31
.4byte sBanetteSprites32
.4byte sBanetteSprites33
.4byte sBanetteSprites34
.4byte sBanetteSprites35
.4byte sBanetteSprites36
.4byte sBanetteSprites37
.4byte sBanetteSprites38
.4byte sBanetteSprites39
.4byte sBanetteSprites40
.4byte sBanetteSprites41
.4byte sBanetteSprites42
.4byte sBanetteSprites43
.4byte sBanetteSprites44
.4byte sBanetteSprites45
.4byte sBanetteSprites46
.4byte sBanetteSprites47
.4byte sBanetteSprites48
.4byte sBanetteSprites49
.4byte sBanetteSprites50
.4byte sBanetteSprites51
.4byte sBanetteSprites52
.4byte sBanetteSprites53
.4byte sBanetteSprites54
.4byte sBanetteSprites55
.4byte sBanetteSprites56
.4byte sBanetteSprites57
.4byte sBanetteSprites58
.4byte sBanetteSprites59
.4byte sBanetteSprites60
.4byte sBanetteSprites61
.4byte sBanetteSprites62
.4byte sBanetteSprites63
.4byte sBanetteSprites64
.4byte sBanetteSprites65
.4byte sBanetteSprites66
.4byte sBanetteSprites67
.4byte sBanetteSprites68
.4byte sBanetteSprites69
.4byte sBanetteSprites70
sAxMainBanette:
ax_main sAxPosesBanette, sAxAnimationsBanette, 13, sAxSpritesBanette, sAxPositionsBanette
