.global gAxBellsprout
gAxBellsprout:
ax_siro sAxMainBellsprout
sBellsproutPose1:
ax_pose 0, 0x01ee, 0x80f4, 0x3c00
ax_pose_terminator
sBellsproutPose2:
ax_pose 1, 0x01ee, 0x80f4, 0x3c00
ax_pose_terminator
sBellsproutPose3:
ax_pose 2, 0x01ee, 0x80f4, 0x3c00
ax_pose_terminator
sBellsproutPose4:
ax_pose 3, 0x81ee, 0x90f8, 0x3c00
ax_pose_terminator
sBellsproutPose5:
ax_pose 4, 0x81ee, 0x90f8, 0x3c00
ax_pose_terminator
sBellsproutPose6:
ax_pose 5, 0x81ee, 0x90f8, 0x3c00
ax_pose_terminator
sBellsproutPose7:
ax_pose 6, 0x81ee, 0x90f8, 0x3c00
ax_pose_terminator
sBellsproutPose8:
ax_pose 7, 0x81ee, 0x90f8, 0x3c00
ax_pose_terminator
sBellsproutPose9:
ax_pose 8, 0x81ee, 0x90f8, 0x3c00
ax_pose_terminator
sBellsproutPose10:
ax_pose 9, 0x81ec, 0x90f8, 0x3c00
ax_pose_terminator
sBellsproutPose11:
ax_pose 10, 0x81ec, 0x90f8, 0x3c00
ax_pose_terminator
sBellsproutPose12:
ax_pose 11, 0x81ec, 0x90f8, 0x3c00
ax_pose_terminator
sBellsproutPose13:
ax_pose 12, 0x01ec, 0x80f8, 0x3c00
ax_pose_terminator
sBellsproutPose14:
ax_pose 13, 0x81ec, 0x80f9, 0x3c00
ax_pose_terminator
sBellsproutPose15:
ax_pose 14, 0x81ec, 0x80f9, 0x3c00
ax_pose_terminator
sBellsproutPose16:
ax_pose 9, 0x81ec, 0x80f8, 0x3c00
ax_pose_terminator
sBellsproutPose17:
ax_pose 10, 0x81ec, 0x80f8, 0x3c00
ax_pose_terminator
sBellsproutPose18:
ax_pose 11, 0x81ec, 0x80f8, 0x3c00
ax_pose_terminator
sBellsproutPose19:
ax_pose 6, 0x81ee, 0x80f8, 0x3c00
ax_pose_terminator
sBellsproutPose20:
ax_pose 7, 0x81ee, 0x80f8, 0x3c00
ax_pose_terminator
sBellsproutPose21:
ax_pose 8, 0x81ee, 0x80f8, 0x3c00
ax_pose_terminator
sBellsproutPose22:
ax_pose 3, 0x81ee, 0x80f8, 0x3c00
ax_pose_terminator
sBellsproutPose23:
ax_pose 4, 0x81ee, 0x80f8, 0x3c00
ax_pose_terminator
sBellsproutPose24:
ax_pose 5, 0x81ee, 0x80f8, 0x3c00
ax_pose_terminator
sBellsproutPose25:
ax_pose 0, 0x01ee, 0x80f4, 0x3c00
ax_pose_terminator
sBellsproutPose26:
ax_pose 1, 0x01ee, 0x80f4, 0x3c00
ax_pose_terminator
sBellsproutPose27:
ax_pose 2, 0x01ee, 0x80f4, 0x3c00
ax_pose_terminator
sBellsproutPose28:
ax_pose 3, 0x81ee, 0x90f8, 0x3c00
ax_pose_terminator
sBellsproutPose29:
ax_pose 4, 0x81ee, 0x90f8, 0x3c00
ax_pose_terminator
sBellsproutPose30:
ax_pose 5, 0x81ee, 0x90f8, 0x3c00
ax_pose_terminator
sBellsproutPose31:
ax_pose 6, 0x81ee, 0x90f8, 0x3c00
ax_pose_terminator
sBellsproutPose32:
ax_pose 7, 0x81ee, 0x90f8, 0x3c00
ax_pose_terminator
sBellsproutPose33:
ax_pose 8, 0x81ee, 0x90f8, 0x3c00
ax_pose_terminator
sBellsproutPose34:
ax_pose 9, 0x81ec, 0x90f8, 0x3c00
ax_pose_terminator
sBellsproutPose35:
ax_pose 10, 0x81ec, 0x90f8, 0x3c00
ax_pose_terminator
sBellsproutPose36:
ax_pose 11, 0x81ec, 0x90f8, 0x3c00
ax_pose_terminator
sBellsproutPose37:
ax_pose 12, 0x01ec, 0x80f8, 0x3c00
ax_pose_terminator
sBellsproutPose38:
ax_pose 13, 0x81ec, 0x80f9, 0x3c00
ax_pose_terminator
sBellsproutPose39:
ax_pose 14, 0x81ec, 0x80f9, 0x3c00
ax_pose_terminator
sBellsproutPose40:
ax_pose 9, 0x81ec, 0x80f8, 0x3c00
ax_pose_terminator
sBellsproutPose41:
ax_pose 10, 0x81ec, 0x80f8, 0x3c00
ax_pose_terminator
sBellsproutPose42:
ax_pose 11, 0x81ec, 0x80f8, 0x3c00
ax_pose_terminator
sBellsproutPose43:
ax_pose 6, 0x81ee, 0x80f8, 0x3c00
ax_pose_terminator
sBellsproutPose44:
ax_pose 7, 0x81ee, 0x80f8, 0x3c00
ax_pose_terminator
sBellsproutPose45:
ax_pose 8, 0x81ee, 0x80f8, 0x3c00
ax_pose_terminator
sBellsproutPose46:
ax_pose 3, 0x81ee, 0x80f8, 0x3c00
ax_pose_terminator
sBellsproutPose47:
ax_pose 4, 0x81ee, 0x80f8, 0x3c00
ax_pose_terminator
sBellsproutPose48:
ax_pose 5, 0x81ee, 0x80f8, 0x3c00
ax_pose_terminator
sBellsproutPose49:
ax_pose 0, 0x01ee, 0x80f4, 0x3c00
ax_pose_terminator
sBellsproutPose50:
ax_pose 15, 0x01eb, 0x80f4, 0x3c00
ax_pose_terminator
sBellsproutPose51:
ax_pose 16, 0x81eb, 0x80f4, 0x3c00
ax_pose 17, 0x01eb, 0x80f4, 0x3c08
ax_pose_terminator
sBellsproutPose52:
ax_pose 17, 0x01eb, 0x80f4, 0x3c00
ax_pose_terminator
sBellsproutPose53:
ax_pose 3, 0x81ee, 0x90f8, 0x3c00
ax_pose_terminator
sBellsproutPose54:
ax_pose 18, 0x01ea, 0x90ed, 0x3c00
ax_pose_terminator
sBellsproutPose55:
ax_pose 19, 0x01ea, 0x90ed, 0x3c00
ax_pose 20, 0x81e8, 0x90fe, 0x3c10
ax_pose_terminator
sBellsproutPose56:
ax_pose 19, 0x01ea, 0x90ed, 0x3c00
ax_pose_terminator
sBellsproutPose57:
ax_pose 6, 0x81ee, 0x90f8, 0x3c00
ax_pose_terminator
sBellsproutPose58:
ax_pose 21, 0x01e8, 0x90ee, 0x3c00
ax_pose_terminator
sBellsproutPose59:
ax_pose 22, 0x01e8, 0x90ee, 0x3c00
ax_pose 23, 0x01e6, 0x90ee, 0x3c10
ax_pose_terminator
sBellsproutPose60:
ax_pose 22, 0x01e8, 0x90ee, 0x3c00
ax_pose_terminator
sBellsproutPose61:
ax_pose 9, 0x81ec, 0x90f8, 0x3c00
ax_pose_terminator
sBellsproutPose62:
ax_pose 24, 0x01ec, 0x90ed, 0x3c00
ax_pose_terminator
sBellsproutPose63:
ax_pose 25, 0x01ec, 0x90ed, 0x3c00
ax_pose 26, 0x01eb, 0x90ed, 0x3c10
ax_pose_terminator
sBellsproutPose64:
ax_pose 25, 0x01ec, 0x90ed, 0x3c00
ax_pose_terminator
sBellsproutPose65:
ax_pose 12, 0x01ec, 0x80f8, 0x3c00
ax_pose_terminator
sBellsproutPose66:
ax_pose 27, 0x01ec, 0x80f8, 0x3c00
ax_pose_terminator
sBellsproutPose67:
ax_pose 28, 0x01ec, 0x80f8, 0x3c00
ax_pose 29, 0x81e3, 0x80fb, 0x3c10
ax_pose_terminator
sBellsproutPose68:
ax_pose 28, 0x01ec, 0x80f8, 0x3c00
ax_pose_terminator
sBellsproutPose69:
ax_pose 9, 0x81ec, 0x80f8, 0x3c00
ax_pose_terminator
sBellsproutPose70:
ax_pose 24, 0x01ec, 0x80f3, 0x3c00
ax_pose_terminator
sBellsproutPose71:
ax_pose 25, 0x01ec, 0x80f3, 0x3c00
ax_pose 26, 0x01eb, 0x80f3, 0x3c10
ax_pose_terminator
sBellsproutPose72:
ax_pose 25, 0x01ec, 0x80f3, 0x3c00
ax_pose_terminator
sBellsproutPose73:
ax_pose 6, 0x81ee, 0x80f8, 0x3c00
ax_pose_terminator
sBellsproutPose74:
ax_pose 21, 0x01e8, 0x80f2, 0x3c00
ax_pose_terminator
sBellsproutPose75:
ax_pose 22, 0x01e8, 0x80f2, 0x3c00
ax_pose 23, 0x01e6, 0x80f2, 0x3c10
ax_pose_terminator
sBellsproutPose76:
ax_pose 22, 0x01e8, 0x80f2, 0x3c00
ax_pose_terminator
sBellsproutPose77:
ax_pose 3, 0x81ee, 0x80f8, 0x3c00
ax_pose_terminator
sBellsproutPose78:
ax_pose 18, 0x01ea, 0x80f3, 0x3c00
ax_pose_terminator
sBellsproutPose79:
ax_pose 19, 0x01ea, 0x80f3, 0x3c00
ax_pose 20, 0x81e8, 0x80f2, 0x3c10
ax_pose_terminator
sBellsproutPose80:
ax_pose 19, 0x01ea, 0x80f3, 0x3c00
ax_pose_terminator
sBellsproutPose81:
ax_pose 0, 0x01ee, 0x80f4, 0x3c00
ax_pose_terminator
sBellsproutPose82:
ax_pose 1, 0x01ee, 0x80f4, 0x3c00
ax_pose_terminator
sBellsproutPose83:
ax_pose 2, 0x01ee, 0x80f4, 0x3c00
ax_pose_terminator
sBellsproutPose84:
ax_pose 30, 0x01eb, 0x80f4, 0x3c00
ax_pose_terminator
sBellsproutPose85:
ax_pose 31, 0x01eb, 0x80f4, 0x3c00
ax_pose_terminator
sBellsproutPose86:
ax_pose 3, 0x81ee, 0x90f8, 0x3c00
ax_pose_terminator
sBellsproutPose87:
ax_pose 4, 0x81ee, 0x90f8, 0x3c00
ax_pose_terminator
sBellsproutPose88:
ax_pose 5, 0x81ee, 0x90f8, 0x3c00
ax_pose_terminator
sBellsproutPose89:
ax_pose 32, 0x01ea, 0x90ea, 0x3c00
ax_pose_terminator
sBellsproutPose90:
ax_pose 33, 0x01ea, 0x90eb, 0x3c00
ax_pose_terminator
sBellsproutPose91:
ax_pose 6, 0x81ee, 0x90f8, 0x3c00
ax_pose_terminator
sBellsproutPose92:
ax_pose 7, 0x81ee, 0x90f8, 0x3c00
ax_pose_terminator
sBellsproutPose93:
ax_pose 8, 0x81ee, 0x90f8, 0x3c00
ax_pose_terminator
sBellsproutPose94:
ax_pose 34, 0x01eb, 0x90ed, 0x3c00
ax_pose_terminator
sBellsproutPose95:
ax_pose 35, 0x01ea, 0x90ed, 0x3c00
ax_pose_terminator
sBellsproutPose96:
ax_pose 9, 0x81ec, 0x90f8, 0x3c00
ax_pose_terminator
sBellsproutPose97:
ax_pose 10, 0x81ec, 0x90f8, 0x3c00
ax_pose_terminator
sBellsproutPose98:
ax_pose 11, 0x81ec, 0x90f8, 0x3c00
ax_pose_terminator
sBellsproutPose99:
ax_pose 36, 0x01eb, 0x90ef, 0x3c00
ax_pose_terminator
sBellsproutPose100:
ax_pose 37, 0x01eb, 0x90ef, 0x3c00
ax_pose_terminator
sBellsproutPose101:
ax_pose 12, 0x01ec, 0x80f8, 0x3c00
ax_pose_terminator
sBellsproutPose102:
ax_pose 13, 0x81ec, 0x80f9, 0x3c00
ax_pose_terminator
sBellsproutPose103:
ax_pose 14, 0x81ec, 0x80f9, 0x3c00
ax_pose_terminator
sBellsproutPose104:
ax_pose 38, 0x01ea, 0x80f7, 0x3c00
ax_pose_terminator
sBellsproutPose105:
ax_pose 39, 0x01ea, 0x80f7, 0x3c00
ax_pose_terminator
sBellsproutPose106:
ax_pose 9, 0x81ec, 0x80f8, 0x3c00
ax_pose_terminator
sBellsproutPose107:
ax_pose 10, 0x81ec, 0x80f8, 0x3c00
ax_pose_terminator
sBellsproutPose108:
ax_pose 11, 0x81ec, 0x80f8, 0x3c00
ax_pose_terminator
sBellsproutPose109:
ax_pose 36, 0x01eb, 0x80f1, 0x3c00
ax_pose_terminator
sBellsproutPose110:
ax_pose 37, 0x01eb, 0x80f1, 0x3c00
ax_pose_terminator
sBellsproutPose111:
ax_pose 6, 0x81ee, 0x80f8, 0x3c00
ax_pose_terminator
sBellsproutPose112:
ax_pose 7, 0x81ee, 0x80f8, 0x3c00
ax_pose_terminator
sBellsproutPose113:
ax_pose 8, 0x81ee, 0x80f8, 0x3c00
ax_pose_terminator
sBellsproutPose114:
ax_pose 34, 0x01eb, 0x80f3, 0x3c00
ax_pose_terminator
sBellsproutPose115:
ax_pose 35, 0x01ea, 0x80f3, 0x3c00
ax_pose_terminator
sBellsproutPose116:
ax_pose 3, 0x81ee, 0x80f8, 0x3c00
ax_pose_terminator
sBellsproutPose117:
ax_pose 4, 0x81ee, 0x80f8, 0x3c00
ax_pose_terminator
sBellsproutPose118:
ax_pose 5, 0x81ee, 0x80f8, 0x3c00
ax_pose_terminator
sBellsproutPose119:
ax_pose 32, 0x01ea, 0x80f6, 0x3c00
ax_pose_terminator
sBellsproutPose120:
ax_pose 33, 0x01ea, 0x80f5, 0x3c00
ax_pose_terminator
sBellsproutPose121:
ax_pose 0, 0x01ee, 0x80f4, 0x3c00
ax_pose_terminator
sBellsproutPose122:
ax_pose 3, 0x81ee, 0x80f8, 0x3c00
ax_pose_terminator
sBellsproutPose123:
ax_pose 6, 0x81ee, 0x80f8, 0x3c00
ax_pose_terminator
sBellsproutPose124:
ax_pose 9, 0x81ec, 0x80f8, 0x3c00
ax_pose_terminator
sBellsproutPose125:
ax_pose 12, 0x01ec, 0x80f8, 0x3c00
ax_pose_terminator
sBellsproutPose126:
ax_pose 9, 0x81ec, 0x90f8, 0x3c00
ax_pose_terminator
sBellsproutPose127:
ax_pose 6, 0x81ee, 0x90f8, 0x3c00
ax_pose_terminator
sBellsproutPose128:
ax_pose 3, 0x81ee, 0x90f8, 0x3c00
ax_pose_terminator
sBellsproutPose129:
ax_pose 40, 0x01ee, 0x80f3, 0x3c00
ax_pose_terminator
sBellsproutPose130:
ax_pose 41, 0x01ee, 0x80f3, 0x3c00
ax_pose_terminator
sBellsproutPose131:
ax_pose 42, 0x01e9, 0x80f2, 0x3c00
ax_pose_terminator
sBellsproutPose132:
ax_pose 43, 0x01e7, 0x90ee, 0x3c00
ax_pose_terminator
sBellsproutPose133:
ax_pose 44, 0x01e8, 0x90ec, 0x3c00
ax_pose_terminator
sBellsproutPose134:
ax_pose 45, 0x01e9, 0x90ed, 0x3c00
ax_pose_terminator
sBellsproutPose135:
ax_pose 46, 0x01e7, 0x80f3, 0x3c00
ax_pose_terminator
sBellsproutPose136:
ax_pose 45, 0x01e9, 0x80f3, 0x3c00
ax_pose_terminator
sBellsproutPose137:
ax_pose 44, 0x01e8, 0x80f4, 0x3c00
ax_pose_terminator
sBellsproutPose138:
ax_pose 43, 0x01e7, 0x80f2, 0x3c00
ax_pose_terminator
sBellsproutPose139:
ax_pose 0, 0x01ee, 0x80f4, 0x3c00
ax_pose_terminator
sBellsproutPose140:
ax_pose 1, 0x01ee, 0x80f4, 0x3c00
ax_pose_terminator
sBellsproutPose141:
ax_pose 2, 0x01ee, 0x80f4, 0x3c00
ax_pose_terminator
sBellsproutPose142:
ax_pose 3, 0x81ee, 0x90f8, 0x3c00
ax_pose_terminator
sBellsproutPose143:
ax_pose 4, 0x81ee, 0x90f8, 0x3c00
ax_pose_terminator
sBellsproutPose144:
ax_pose 5, 0x81ee, 0x90f8, 0x3c00
ax_pose_terminator
sBellsproutPose145:
ax_pose 6, 0x81ee, 0x90f8, 0x3c00
ax_pose_terminator
sBellsproutPose146:
ax_pose 7, 0x81ee, 0x90f8, 0x3c00
ax_pose_terminator
sBellsproutPose147:
ax_pose 8, 0x81ee, 0x90f8, 0x3c00
ax_pose_terminator
sBellsproutPose148:
ax_pose 9, 0x81ec, 0x90f8, 0x3c00
ax_pose_terminator
sBellsproutPose149:
ax_pose 10, 0x81ec, 0x90f8, 0x3c00
ax_pose_terminator
sBellsproutPose150:
ax_pose 11, 0x81ec, 0x90f8, 0x3c00
ax_pose_terminator
sBellsproutPose151:
ax_pose 12, 0x01ec, 0x80f8, 0x3c00
ax_pose_terminator
sBellsproutPose152:
ax_pose 13, 0x81ec, 0x80f9, 0x3c00
ax_pose_terminator
sBellsproutPose153:
ax_pose 14, 0x81ec, 0x80f9, 0x3c00
ax_pose_terminator
sBellsproutPose154:
ax_pose 9, 0x81ec, 0x80f8, 0x3c00
ax_pose_terminator
sBellsproutPose155:
ax_pose 10, 0x81ec, 0x80f8, 0x3c00
ax_pose_terminator
sBellsproutPose156:
ax_pose 11, 0x81ec, 0x80f8, 0x3c00
ax_pose_terminator
sBellsproutPose157:
ax_pose 6, 0x81ee, 0x80f8, 0x3c00
ax_pose_terminator
sBellsproutPose158:
ax_pose 7, 0x81ee, 0x80f8, 0x3c00
ax_pose_terminator
sBellsproutPose159:
ax_pose 8, 0x81ee, 0x80f8, 0x3c00
ax_pose_terminator
sBellsproutPose160:
ax_pose 3, 0x81ee, 0x80f8, 0x3c00
ax_pose_terminator
sBellsproutPose161:
ax_pose 4, 0x81ee, 0x80f8, 0x3c00
ax_pose_terminator
sBellsproutPose162:
ax_pose 5, 0x81ee, 0x80f8, 0x3c00
ax_pose_terminator
sBellsproutPose163:
ax_pose 30, 0x01eb, 0x80f4, 0x3c00
ax_pose_terminator
sBellsproutPose164:
ax_pose 32, 0x01ea, 0x80f6, 0x3c00
ax_pose_terminator
sBellsproutPose165:
ax_pose 34, 0x01eb, 0x80f3, 0x3c00
ax_pose_terminator
sBellsproutPose166:
ax_pose 36, 0x01ea, 0x80f3, 0x3c00
ax_pose_terminator
sBellsproutPose167:
ax_pose 38, 0x01ea, 0x80f7, 0x3c00
ax_pose_terminator
sBellsproutPose168:
ax_pose 36, 0x01ea, 0x90ed, 0x3c00
ax_pose_terminator
sBellsproutPose169:
ax_pose 34, 0x01eb, 0x90ed, 0x3c00
ax_pose_terminator
sBellsproutPose170:
ax_pose 32, 0x01ea, 0x90ea, 0x3c00
ax_pose_terminator
sBellsproutPose171:
ax_pose 30, 0x01eb, 0x80f4, 0x3c00
ax_pose_terminator
sBellsproutPose172:
ax_pose 32, 0x01ea, 0x90ea, 0x3c00
ax_pose_terminator
sBellsproutPose173:
ax_pose 34, 0x01eb, 0x90ed, 0x3c00
ax_pose_terminator
sBellsproutPose174:
ax_pose 36, 0x01ea, 0x90ed, 0x3c00
ax_pose_terminator
sBellsproutPose175:
ax_pose 38, 0x01ea, 0x80f7, 0x3c00
ax_pose_terminator
sBellsproutPose176:
ax_pose 36, 0x01ea, 0x80f3, 0x3c00
ax_pose_terminator
sBellsproutPose177:
ax_pose 34, 0x01eb, 0x80f3, 0x3c00
ax_pose_terminator
sBellsproutPose178:
ax_pose 32, 0x01ea, 0x80f6, 0x3c00
ax_pose_terminator
sBellsproutPose179:
ax_pose 0, 0x01ee, 0x80f4, 0x3c00
ax_pose_terminator
sBellsproutPose180:
ax_pose 30, 0x01eb, 0x80f4, 0x3c00
ax_pose_terminator
sBellsproutPose181:
ax_pose 31, 0x01eb, 0x80f4, 0x3c00
ax_pose_terminator
sBellsproutPose182:
ax_pose 3, 0x81ee, 0x90f8, 0x3c00
ax_pose_terminator
sBellsproutPose183:
ax_pose 32, 0x01ea, 0x90ea, 0x3c00
ax_pose_terminator
sBellsproutPose184:
ax_pose 33, 0x01ea, 0x90ea, 0x3c00
ax_pose_terminator
sBellsproutPose185:
ax_pose 6, 0x81ee, 0x90f8, 0x3c00
ax_pose_terminator
sBellsproutPose186:
ax_pose 34, 0x01eb, 0x90ed, 0x3c00
ax_pose_terminator
sBellsproutPose187:
ax_pose 35, 0x01eb, 0x90ed, 0x3c00
ax_pose_terminator
sBellsproutPose188:
ax_pose 9, 0x81ec, 0x90f8, 0x3c00
ax_pose_terminator
sBellsproutPose189:
ax_pose 36, 0x01ea, 0x90ed, 0x3c00
ax_pose_terminator
sBellsproutPose190:
ax_pose 37, 0x01ea, 0x90ed, 0x3c00
ax_pose_terminator
sBellsproutPose191:
ax_pose 12, 0x01ec, 0x80f8, 0x3c00
ax_pose_terminator
sBellsproutPose192:
ax_pose 38, 0x01ea, 0x80f7, 0x3c00
ax_pose_terminator
sBellsproutPose193:
ax_pose 39, 0x01ea, 0x80f7, 0x3c00
ax_pose_terminator
sBellsproutPose194:
ax_pose 9, 0x81ec, 0x80f8, 0x3c00
ax_pose_terminator
sBellsproutPose195:
ax_pose 36, 0x01ea, 0x80f3, 0x3c00
ax_pose_terminator
sBellsproutPose196:
ax_pose 37, 0x01ea, 0x80f3, 0x3c00
ax_pose_terminator
sBellsproutPose197:
ax_pose 6, 0x81ee, 0x80f8, 0x3c00
ax_pose_terminator
sBellsproutPose198:
ax_pose 34, 0x01eb, 0x80f3, 0x3c00
ax_pose_terminator
sBellsproutPose199:
ax_pose 35, 0x01eb, 0x80f3, 0x3c00
ax_pose_terminator
sBellsproutPose200:
ax_pose 3, 0x81ee, 0x80f8, 0x3c00
ax_pose_terminator
sBellsproutPose201:
ax_pose 32, 0x01ea, 0x80f6, 0x3c00
ax_pose_terminator
sBellsproutPose202:
ax_pose 33, 0x01ea, 0x80f6, 0x3c00
ax_pose_terminator
sBellsproutPose203:
ax_pose 30, 0x01eb, 0x80f4, 0x3c00
ax_pose_terminator
sBellsproutPose204:
ax_pose 32, 0x01ea, 0x80f6, 0x3c00
ax_pose_terminator
sBellsproutPose205:
ax_pose 34, 0x01eb, 0x80f3, 0x3c00
ax_pose_terminator
sBellsproutPose206:
ax_pose 36, 0x01ea, 0x80f3, 0x3c00
ax_pose_terminator
sBellsproutPose207:
ax_pose 38, 0x01ea, 0x80f7, 0x3c00
ax_pose_terminator
sBellsproutPose208:
ax_pose 36, 0x01ea, 0x90ed, 0x3c00
ax_pose_terminator
sBellsproutPose209:
ax_pose 34, 0x01eb, 0x90ed, 0x3c00
ax_pose_terminator
sBellsproutPose210:
ax_pose 32, 0x01ea, 0x90ea, 0x3c00
ax_pose_terminator
sBellsproutPose211:
ax_pose 0, 0x01ee, 0x80f4, 0x3c00
ax_pose_terminator
sBellsproutPose212:
ax_pose 3, 0x81ee, 0x80f8, 0x3c00
ax_pose_terminator
sBellsproutPose213:
ax_pose 6, 0x81ee, 0x80f8, 0x3c00
ax_pose_terminator
sBellsproutPose214:
ax_pose 9, 0x81ec, 0x80f8, 0x3c00
ax_pose_terminator
sBellsproutPose215:
ax_pose 12, 0x01ec, 0x80f8, 0x3c00
ax_pose_terminator
sBellsproutPose216:
ax_pose 9, 0x81ec, 0x90f8, 0x3c00
ax_pose_terminator
sBellsproutPose217:
ax_pose 6, 0x81ee, 0x90f8, 0x3c00
ax_pose_terminator
sBellsproutPose218:
ax_pose 3, 0x81ee, 0x90f8, 0x3c00
ax_pose_terminator
.align 2
sBellsproutAnims_1_1:
ax_anim 8, 0, 0, 0, 0, 0, 0,
ax_anim 10, 0, 1, 0, 0, 0, 0,
ax_anim 8, 0, 0, 0, 0, 0, 0,
ax_anim 10, 0, 2, 0, 0, 0, 0,
ax_anim_terminator
sBellsproutAnims_1_2:
ax_anim 8, 0, 3, 0, 0, 0, 0,
ax_anim 10, 0, 4, 0, 0, 0, 0,
ax_anim 8, 0, 3, 0, 0, 0, 0,
ax_anim 10, 0, 5, 0, 0, 0, 0,
ax_anim_terminator
sBellsproutAnims_1_3:
ax_anim 8, 0, 6, 0, 0, 0, 0,
ax_anim 10, 0, 7, 0, 0, 0, 0,
ax_anim 8, 0, 6, 0, 0, 0, 0,
ax_anim 10, 0, 8, 0, 0, 0, 0,
ax_anim_terminator
sBellsproutAnims_1_4:
ax_anim 8, 0, 9, 0, 0, 0, 0,
ax_anim 10, 0, 10, 0, 0, 0, 0,
ax_anim 8, 0, 9, 0, 0, 0, 0,
ax_anim 10, 0, 11, 0, 0, 0, 0,
ax_anim_terminator
sBellsproutAnims_1_5:
ax_anim 8, 0, 12, 0, 0, 0, 0,
ax_anim 10, 0, 13, 0, 0, 0, 0,
ax_anim 8, 0, 12, 0, 0, 0, 0,
ax_anim 10, 0, 14, 0, 0, 0, 0,
ax_anim_terminator
sBellsproutAnims_1_6:
ax_anim 8, 0, 15, 0, 0, 0, 0,
ax_anim 10, 0, 16, 0, 0, 0, 0,
ax_anim 8, 0, 15, 0, 0, 0, 0,
ax_anim 10, 0, 17, 0, 0, 0, 0,
ax_anim_terminator
sBellsproutAnims_1_7:
ax_anim 8, 0, 18, 0, 0, 0, 0,
ax_anim 10, 0, 19, 0, 0, 0, 0,
ax_anim 8, 0, 18, 0, 0, 0, 0,
ax_anim 10, 0, 20, 0, 0, 0, 0,
ax_anim_terminator
sBellsproutAnims_1_8:
ax_anim 8, 0, 21, 0, 0, 0, 0,
ax_anim 10, 0, 22, 0, 0, 0, 0,
ax_anim 8, 0, 21, 0, 0, 0, 0,
ax_anim 10, 0, 23, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sBellsproutAnims_2_1:
ax_anim 2, 0, 25, 0, -1, 0, -1,
ax_anim 4, 0, 25, 0, -2, 0, -2,
ax_anim 1, 0, 26, 0, 0, 0, 0,
ax_anim 1, 2, 25, 0, 4, 0, 4,
ax_anim 1, 0, 26, 0, 10, 0, 10,
ax_anim 2, 0, 25, 0, 20, 0, 20,
ax_anim 2, 1, 25, 1, 20, 1, 20,
ax_anim 2, 0, 25, 0, 20, 0, 20,
ax_anim 2, 0, 25, 1, 20, 1, 20,
ax_anim 2, 0, 24, 0, 6, 0, 6,
ax_anim_terminator
sBellsproutAnims_2_2:
ax_anim 2, 0, 27, -1, -1, -1, -1,
ax_anim 4, 0, 27, -2, -2, -2, -2,
ax_anim 1, 0, 29, 0, -1, 0, -1,
ax_anim 1, 2, 28, 4, 4, 4, 4,
ax_anim 1, 0, 29, 10, 10, 10, 10,
ax_anim 2, 0, 28, 20, 20, 20, 20,
ax_anim 2, 1, 28, 21, 19, 21, 19,
ax_anim 2, 0, 28, 20, 20, 20, 20,
ax_anim 2, 0, 28, 21, 19, 21, 19,
ax_anim 2, 0, 27, 8, 8, 8, 8,
ax_anim_terminator
sBellsproutAnims_2_3:
ax_anim 2, 0, 30, -1, 0, -1, 0,
ax_anim 4, 0, 30, -2, 0, -2, 0,
ax_anim 1, 0, 32, 0, 0, 0, 0,
ax_anim 1, 2, 31, 4, 0, 4, 0,
ax_anim 1, 0, 32, 13, 0, 13, 0,
ax_anim 2, 0, 31, 23, 0, 23, 0,
ax_anim 2, 1, 31, 23, 1, 23, 1,
ax_anim 2, 0, 31, 23, 0, 23, 0,
ax_anim 2, 0, 31, 23, 1, 23, 1,
ax_anim 2, 0, 30, 6, 0, 6, 0,
ax_anim_terminator
sBellsproutAnims_2_4:
ax_anim 2, 0, 33, -1, 1, -1, 1,
ax_anim 4, 0, 33, -2, 2, -2, 2,
ax_anim 1, 0, 35, 0, -1, 0, -1,
ax_anim 1, 2, 34, 4, -6, 4, -6,
ax_anim 1, 0, 35, 11, -12, 11, -12,
ax_anim 2, 0, 34, 21, -23, 21, -23,
ax_anim 2, 1, 34, 22, -22, 22, -22,
ax_anim 2, 0, 34, 21, -23, 21, -23,
ax_anim 2, 0, 34, 22, -22, 22, -22,
ax_anim 2, 0, 33, 6, -6, 6, -6,
ax_anim_terminator
sBellsproutAnims_2_5:
ax_anim 2, 0, 36, 0, 1, 0, 1,
ax_anim 4, 0, 36, 0, 2, 0, 2,
ax_anim 1, 0, 38, 0, 0, 0, 0,
ax_anim 1, 2, 37, 0, -4, 0, -4,
ax_anim 1, 0, 38, 0, -11, 0, -11,
ax_anim 2, 0, 37, 0, -21, 0, -21,
ax_anim 2, 1, 37, 1, -21, 1, -21,
ax_anim 2, 0, 37, 0, -21, 0, -21,
ax_anim 2, 0, 37, 1, -21, 1, -21,
ax_anim 2, 0, 36, 0, -6, 0, -6,
ax_anim_terminator
sBellsproutAnims_2_6:
ax_anim 2, 0, 39, 1, 1, 1, 1,
ax_anim 4, 0, 39, 2, 2, 2, 2,
ax_anim 1, 0, 41, 0, -1, 0, -1,
ax_anim 1, 2, 40, -4, -6, -4, -6,
ax_anim 1, 0, 41, -11, -12, -11, -12,
ax_anim 2, 0, 40, -21, -23, -21, -23,
ax_anim 2, 1, 40, -22, -22, -22, -22,
ax_anim 2, 0, 40, -21, -23, -21, -23,
ax_anim 2, 0, 40, -22, -22, -22, -22,
ax_anim 2, 0, 39, -6, -6, -6, -6,
ax_anim_terminator
sBellsproutAnims_2_7:
ax_anim 2, 0, 42, 1, 0, 1, 0,
ax_anim 4, 0, 42, 2, 0, 2, 0,
ax_anim 1, 0, 44, 0, 0, 0, 0,
ax_anim 1, 2, 43, -4, 0, -4, 0,
ax_anim 1, 0, 44, -13, 0, -13, 0,
ax_anim 2, 0, 43, -23, 0, -23, 0,
ax_anim 2, 1, 43, -23, 1, -23, 1,
ax_anim 2, 0, 43, -23, 0, -23, 0,
ax_anim 2, 0, 43, -23, 1, -23, 1,
ax_anim 2, 0, 42, -6, 0, -6, 0,
ax_anim_terminator
sBellsproutAnims_2_8:
ax_anim 2, 0, 45, 1, -1, 1, -1,
ax_anim 4, 0, 45, 2, -2, 2, -2,
ax_anim 1, 0, 46, 0, 0, 0, 0,
ax_anim 1, 2, 47, -4, 4, -4, 4,
ax_anim 1, 0, 47, -10, 10, -10, 10,
ax_anim 2, 0, 46, -19, 21, -19, 21,
ax_anim 2, 1, 46, -20, 20, -20, 20,
ax_anim 2, 0, 46, -19, 21, -19, 21,
ax_anim 2, 0, 46, -19, 21, -19, 21,
ax_anim 2, 0, 45, -6, 6, -6, 6,
ax_anim_terminator
.align 2
sBellsproutAnims_3_1:
ax_anim 2, 0, 49, 0, -2, 0, -2,
ax_anim 6, 0, 49, 0, -3, 0, -3,
ax_anim 1, 2, 49, 0, 0, 0, 0,
ax_anim 1, 0, 49, 0, 9, 0, 9,
ax_anim 2, 0, 50, 0, 20, 0, 20,
ax_anim 2, 1, 51, 1, 20, 1, 20,
ax_anim 2, 0, 51, 0, 20, 0, 20,
ax_anim 2, 0, 51, 1, 20, 1, 20,
ax_anim 2, 0, 48, 0, 10, 0, 10,
ax_anim 2, 0, 48, 0, 3, 0, 3,
ax_anim_terminator
sBellsproutAnims_3_2:
ax_anim 2, 0, 53, -2, -2, -2, -2,
ax_anim 6, 0, 53, -3, -3, -3, -3,
ax_anim 1, 2, 53, 0, 0, 0, 0,
ax_anim 1, 0, 53, 9, 9, 9, 9,
ax_anim 2, 0, 54, 19, 20, 19, 20,
ax_anim 2, 1, 55, 20, 19, 20, 19,
ax_anim 2, 0, 55, 19, 20, 19, 20,
ax_anim 2, 0, 55, 20, 19, 20, 19,
ax_anim 2, 0, 52, 10, 10, 10, 10,
ax_anim 2, 0, 52, 3, 3, 3, 3,
ax_anim_terminator
sBellsproutAnims_3_3:
ax_anim 2, 0, 57, -2, 0, -2, 0,
ax_anim 6, 0, 57, -3, 0, -3, 0,
ax_anim 1, 2, 57, 0, 0, 0, 0,
ax_anim 1, 0, 57, 9, 0, 9, 0,
ax_anim 2, 0, 58, 17, 0, 17, 0,
ax_anim 2, 1, 59, 17, 1, 17, 1,
ax_anim 2, 0, 59, 17, 0, 17, 0,
ax_anim 2, 0, 59, 17, 1, 17, 1,
ax_anim 2, 0, 56, 10, 0, 10, 0,
ax_anim 2, 0, 56, 3, 0, 3, 0,
ax_anim_terminator
sBellsproutAnims_3_4:
ax_anim 2, 0, 61, -2, 2, -2, 2,
ax_anim 6, 0, 61, -3, 3, -3, 3,
ax_anim 1, 2, 61, 0, 0, 0, 0,
ax_anim 1, 0, 61, 9, -11, 9, -11,
ax_anim 2, 0, 62, 19, -23, 19, -23,
ax_anim 2, 1, 63, 19, -22, 19, -22,
ax_anim 2, 0, 63, 19, -23, 19, -23,
ax_anim 2, 0, 63, 19, -22, 19, -22,
ax_anim 2, 0, 60, 10, -10, 10, -10,
ax_anim 2, 0, 60, 3, -3, 3, -3,
ax_anim_terminator
sBellsproutAnims_3_5:
ax_anim 2, 0, 65, 0, 2, 0, 2,
ax_anim 6, 0, 65, 0, 3, 0, 3,
ax_anim 1, 2, 65, 0, 0, 0, 0,
ax_anim 1, 0, 65, 0, -11, 0, -11,
ax_anim 2, 0, 66, 0, -23, 0, -23,
ax_anim 2, 1, 67, -1, -23, -1, -23,
ax_anim 2, 0, 67, 0, -23, 0, -23,
ax_anim 2, 0, 67, -1, -23, -1, -23,
ax_anim 2, 0, 64, 0, -10, 0, -10,
ax_anim 2, 0, 64, 0, -3, 0, -3,
ax_anim_terminator
sBellsproutAnims_3_6:
ax_anim 2, 0, 69, 2, 2, 2, 2,
ax_anim 6, 0, 69, 3, 3, 3, 3,
ax_anim 1, 2, 69, 0, 0, 0, 0,
ax_anim 1, 0, 69, -9, -11, -9, -11,
ax_anim 2, 0, 70, -19, -23, -19, -23,
ax_anim 2, 1, 71, -19, -22, -19, -22,
ax_anim 2, 0, 71, -19, -23, -19, -23,
ax_anim 2, 0, 71, -19, -22, -19, -22,
ax_anim 2, 0, 68, -10, -10, -10, -10,
ax_anim 2, 0, 68, -3, -3, -3, -3,
ax_anim_terminator
sBellsproutAnims_3_7:
ax_anim 2, 0, 73, 2, 0, 2, 0,
ax_anim 6, 0, 73, 3, 0, 3, 0,
ax_anim 1, 2, 73, 0, 0, 0, 0,
ax_anim 1, 0, 73, -9, 0, -9, 0,
ax_anim 2, 0, 74, -17, 0, -17, 0,
ax_anim 2, 1, 75, -17, 1, -17, 1,
ax_anim 2, 0, 75, -17, 0, -17, 0,
ax_anim 2, 0, 75, -17, 1, -17, 1,
ax_anim 2, 0, 68, -10, 0, -10, 0,
ax_anim 2, 0, 72, -3, 0, -3, 0,
ax_anim_terminator
sBellsproutAnims_3_8:
ax_anim 2, 0, 77, 2, -2, 2, -2,
ax_anim 6, 0, 77, 3, -3, 3, -3,
ax_anim 1, 2, 77, 0, 0, 0, 0,
ax_anim 1, 0, 77, -9, 9, -9, 9,
ax_anim 2, 0, 78, -19, 20, -19, 20,
ax_anim 2, 1, 79, -20, 19, -20, 19,
ax_anim 2, 0, 79, -19, 20, -19, 20,
ax_anim 2, 0, 79, -20, 19, -20, 19,
ax_anim 2, 0, 76, -10, 10, -10, 10,
ax_anim 2, 0, 76, -3, 3, -3, 3,
ax_anim_terminator
.align 2
sBellsproutAnims_4_1:
ax_anim 2, 0, 82, 0, -2, 0, -2,
ax_anim 2, 0, 82, 0, -3, 0, -3,
ax_anim 4, 2, 83, 0, -2, 0, -2,
ax_anim 1, 0, 83, 0, 0, 0, 0,
ax_anim 2, 0, 83, 0, 4, 0, 4,
ax_anim 2, 0, 84, 0, 4, 0, 4,
ax_anim 2, 1, 83, 0, 4, 0, 4,
ax_anim 2, 0, 84, 0, 4, 0, 4,
ax_anim 2, 0, 83, 0, 4, 0, 4,
ax_anim 2, 0, 84, 0, 4, 0, 4,
ax_anim 2, 0, 80, 0, 2, 0, 2,
ax_anim_terminator
sBellsproutAnims_4_2:
ax_anim 2, 0, 87, -2, -2, -2, -2,
ax_anim 2, 0, 87, -3, -3, -3, -3,
ax_anim 4, 2, 88, -2, -2, -2, -2,
ax_anim 1, 0, 88, 0, 0, 0, 0,
ax_anim 2, 0, 88, 4, 4, 4, 4,
ax_anim 2, 0, 89, 4, 4, 4, 4,
ax_anim 2, 1, 88, 4, 4, 4, 4,
ax_anim 2, 0, 89, 4, 4, 4, 4,
ax_anim 2, 0, 88, 4, 4, 4, 4,
ax_anim 2, 0, 89, 4, 4, 4, 4,
ax_anim 2, 0, 85, 2, 2, 2, 2,
ax_anim_terminator
sBellsproutAnims_4_3:
ax_anim 2, 0, 92, -2, 0, -2, 0,
ax_anim 2, 0, 92, -3, 0, -3, 0,
ax_anim 4, 2, 93, -3, 0, -3, 0,
ax_anim 1, 0, 93, 0, 0, 0, 0,
ax_anim 2, 0, 93, 4, 0, 4, 0,
ax_anim 2, 0, 94, 4, 0, 4, 0,
ax_anim 2, 1, 93, 4, 0, 4, 0,
ax_anim 2, 0, 94, 4, 0, 4, 0,
ax_anim 2, 0, 93, 4, 0, 4, 0,
ax_anim 2, 0, 94, 4, 0, 4, 0,
ax_anim 2, 0, 90, 2, 0, 2, 0,
ax_anim_terminator
sBellsproutAnims_4_4:
ax_anim 2, 0, 97, -2, 2, -2, 2,
ax_anim 2, 0, 97, -3, 3, -3, 3,
ax_anim 4, 2, 98, -2, 2, -2, 2,
ax_anim 1, 0, 98, 0, 0, 0, 0,
ax_anim 2, 0, 98, 4, -4, 4, -4,
ax_anim 2, 0, 99, 4, -4, 4, -4,
ax_anim 2, 1, 98, 4, -4, 4, -4,
ax_anim 2, 0, 99, 4, -4, 4, -4,
ax_anim 2, 0, 98, 4, -4, 4, -4,
ax_anim 2, 0, 99, 4, -4, 4, -4,
ax_anim 2, 0, 95, 2, -2, 2, -2,
ax_anim_terminator
sBellsproutAnims_4_5:
ax_anim 2, 0, 102, 0, 2, 0, 2,
ax_anim 2, 0, 102, 0, 3, 0, 3,
ax_anim 4, 2, 103, 0, 2, 0, 2,
ax_anim 1, 0, 103, 0, 0, 0, 0,
ax_anim 2, 0, 103, 0, -4, 0, -4,
ax_anim 2, 0, 104, 0, -4, 0, -4,
ax_anim 2, 1, 103, 0, -4, 0, -4,
ax_anim 2, 0, 104, 0, -4, 0, -4,
ax_anim 2, 0, 103, 0, -4, 0, -4,
ax_anim 2, 0, 104, 0, -4, 0, -4,
ax_anim 2, 0, 100, 0, -2, 0, -2,
ax_anim_terminator
sBellsproutAnims_4_6:
ax_anim 2, 0, 107, 2, 2, 2, 2,
ax_anim 2, 0, 107, 3, 3, 3, 3,
ax_anim 4, 2, 108, 2, 2, 2, 2,
ax_anim 1, 0, 108, 0, 0, 0, 0,
ax_anim 2, 0, 108, -4, -4, -4, -4,
ax_anim 2, 0, 109, -4, -4, -4, -4,
ax_anim 2, 1, 108, -4, -4, -4, -4,
ax_anim 2, 0, 109, -4, -4, -4, -4,
ax_anim 2, 0, 108, -4, -4, -4, -4,
ax_anim 2, 0, 109, -4, -4, -4, -4,
ax_anim 2, 0, 105, -2, -2, -2, -2,
ax_anim_terminator
sBellsproutAnims_4_7:
ax_anim 2, 0, 112, 2, 0, 2, 0,
ax_anim 2, 0, 112, 3, 0, 3, 0,
ax_anim 4, 2, 113, 3, 0, 3, 0,
ax_anim 1, 0, 113, 0, 0, 0, 0,
ax_anim 2, 0, 113, -4, 0, -4, 0,
ax_anim 2, 0, 114, -4, 0, -4, 0,
ax_anim 2, 1, 113, -4, 0, -4, 0,
ax_anim 2, 0, 114, -4, 0, -4, 0,
ax_anim 2, 0, 113, -4, 0, -4, 0,
ax_anim 2, 0, 114, -4, 0, -4, 0,
ax_anim 2, 0, 110, -2, 0, -2, 0,
ax_anim_terminator
sBellsproutAnims_4_8:
ax_anim 2, 0, 117, 2, -2, 2, -2,
ax_anim 2, 0, 117, 3, -3, 3, -3,
ax_anim 4, 2, 118, 2, -2, 2, -2,
ax_anim 1, 0, 118, 0, 0, 0, 0,
ax_anim 2, 0, 118, -4, 4, -4, 4,
ax_anim 2, 0, 119, -4, 4, -4, 4,
ax_anim 2, 1, 118, -4, 4, -4, 4,
ax_anim 2, 0, 119, -4, 4, -4, 4,
ax_anim 2, 0, 118, -4, 4, -4, 4,
ax_anim 2, 0, 119, -4, 4, -4, 4,
ax_anim 2, 0, 115, -2, 2, -2, 2,
ax_anim_terminator
.align 2
sBellsproutAnims_5_1:
ax_anim 2, 0, 120, 0, 0, 0, 0,
ax_anim 2, 0, 121, 0, 0, 0, 0,
ax_anim 2, 0, 122, 0, 0, 0, 0,
ax_anim 2, 0, 123, 0, 0, 0, 0,
ax_anim 2, 0, 124, 0, 0, 0, 0,
ax_anim 2, 0, 125, 0, 0, 0, 0,
ax_anim 2, 0, 126, 0, 0, 0, 0,
ax_anim 2, 0, 127, 0, 0, 0, 0,
ax_anim 2, 2, 120, 0, 0, 0, 0,
ax_anim_terminator
sBellsproutAnims_5_2:
ax_anim 2, 0, 127, 0, 0, 0, 0,
ax_anim 2, 0, 120, 0, 0, 0, 0,
ax_anim 2, 0, 121, 0, 0, 0, 0,
ax_anim 2, 0, 122, 0, 0, 0, 0,
ax_anim 2, 0, 123, 0, 0, 0, 0,
ax_anim 2, 0, 124, 0, 0, 0, 0,
ax_anim 2, 0, 125, 0, 0, 0, 0,
ax_anim 2, 0, 126, 0, 0, 0, 0,
ax_anim 2, 2, 127, 0, 0, 0, 0,
ax_anim_terminator
sBellsproutAnims_5_3:
ax_anim 2, 0, 126, 0, 0, 0, 0,
ax_anim 2, 0, 127, 0, 0, 0, 0,
ax_anim 2, 0, 120, 0, 0, 0, 0,
ax_anim 2, 0, 121, 0, 0, 0, 0,
ax_anim 2, 0, 122, 0, 0, 0, 0,
ax_anim 2, 0, 123, 0, 0, 0, 0,
ax_anim 2, 0, 124, 0, 0, 0, 0,
ax_anim 2, 0, 125, 0, 0, 0, 0,
ax_anim 2, 2, 126, 0, 0, 0, 0,
ax_anim_terminator
sBellsproutAnims_5_4:
ax_anim 2, 0, 125, 0, 0, 0, 0,
ax_anim 2, 0, 126, 0, 0, 0, 0,
ax_anim 2, 0, 127, 0, 0, 0, 0,
ax_anim 2, 0, 120, 0, 0, 0, 0,
ax_anim 2, 0, 121, 0, 0, 0, 0,
ax_anim 2, 0, 122, 0, 0, 0, 0,
ax_anim 2, 0, 123, 0, 0, 0, 0,
ax_anim 2, 0, 124, 0, 0, 0, 0,
ax_anim 2, 2, 125, 0, 0, 0, 0,
ax_anim_terminator
sBellsproutAnims_5_5:
ax_anim 2, 0, 124, 0, 0, 0, 0,
ax_anim 2, 0, 125, 0, 0, 0, 0,
ax_anim 2, 0, 126, 0, 0, 0, 0,
ax_anim 2, 0, 127, 0, 0, 0, 0,
ax_anim 2, 0, 120, 0, 0, 0, 0,
ax_anim 2, 0, 121, 0, 0, 0, 0,
ax_anim 2, 0, 122, 0, 0, 0, 0,
ax_anim 2, 0, 123, 0, 0, 0, 0,
ax_anim 2, 2, 124, 0, 0, 0, 0,
ax_anim_terminator
sBellsproutAnims_5_6:
ax_anim 2, 0, 123, 0, 0, 0, 0,
ax_anim 2, 0, 124, 0, 0, 0, 0,
ax_anim 2, 0, 125, 0, 0, 0, 0,
ax_anim 2, 0, 126, 0, 0, 0, 0,
ax_anim 2, 0, 127, 0, 0, 0, 0,
ax_anim 2, 0, 120, 0, 0, 0, 0,
ax_anim 2, 0, 121, 0, 0, 0, 0,
ax_anim 2, 0, 122, 0, 0, 0, 0,
ax_anim 2, 2, 123, 0, 0, 0, 0,
ax_anim_terminator
sBellsproutAnims_5_7:
ax_anim 2, 0, 122, 0, 0, 0, 0,
ax_anim 2, 0, 123, 0, 0, 0, 0,
ax_anim 2, 0, 124, 0, 0, 0, 0,
ax_anim 2, 0, 125, 0, 0, 0, 0,
ax_anim 2, 0, 126, 0, 0, 0, 0,
ax_anim 2, 0, 127, 0, 0, 0, 0,
ax_anim 2, 0, 120, 0, 0, 0, 0,
ax_anim 2, 0, 121, 0, 0, 0, 0,
ax_anim 2, 2, 122, 0, 0, 0, 0,
ax_anim_terminator
sBellsproutAnims_5_8:
ax_anim 2, 0, 121, 0, 0, 0, 0,
ax_anim 2, 0, 122, 0, 0, 0, 0,
ax_anim 2, 0, 123, 0, 0, 0, 0,
ax_anim 2, 0, 124, 0, 0, 0, 0,
ax_anim 2, 0, 125, 0, 0, 0, 0,
ax_anim 2, 0, 126, 0, 0, 0, 0,
ax_anim 2, 0, 127, 0, 0, 0, 0,
ax_anim 2, 0, 120, 0, 0, 0, 0,
ax_anim 2, 2, 121, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sBellsproutAnims_6_1:
ax_anim 30, 0, 128, 0, 0, 0, 0,
ax_anim 35, 0, 129, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sBellsproutAnims_7_1:
ax_anim 2, 0, 130, 0, -2, 0, -2,
ax_anim 8, 0, 130, 0, -3, 0, -3,
ax_anim_terminator
sBellsproutAnims_7_2:
ax_anim 2, 0, 131, -2, -2, -2, -2,
ax_anim 8, 0, 131, -3, -3, -3, -3,
ax_anim_terminator
sBellsproutAnims_7_3:
ax_anim 2, 0, 132, -2, 0, -2, 0,
ax_anim 8, 0, 132, -3, 0, -3, 0,
ax_anim_terminator
sBellsproutAnims_7_4:
ax_anim 2, 0, 133, -2, 2, -2, 2,
ax_anim 8, 0, 133, -3, 3, -3, 3,
ax_anim_terminator
sBellsproutAnims_7_5:
ax_anim 2, 0, 134, 0, 2, 0, 2,
ax_anim 8, 0, 134, 0, 3, 0, 3,
ax_anim_terminator
sBellsproutAnims_7_6:
ax_anim 2, 0, 135, 2, 2, 2, 2,
ax_anim 8, 0, 135, 3, 3, 3, 3,
ax_anim_terminator
sBellsproutAnims_7_7:
ax_anim 2, 0, 136, 2, 0, 2, 0,
ax_anim 8, 0, 136, 3, 0, 3, 0,
ax_anim_terminator
sBellsproutAnims_7_8:
ax_anim 2, 0, 137, 2, -2, 2, -2,
ax_anim 8, 0, 137, 3, -3, 3, -3,
ax_anim_terminator
.align 2
sBellsproutAnims_8_1:
ax_anim 20, 0, 140, 0, 0, 0, 0,
ax_anim 22, 0, 139, 0, 0, 0, 0,
ax_anim_terminator
sBellsproutAnims_8_2:
ax_anim 20, 0, 143, 0, 0, 0, 0,
ax_anim 22, 0, 142, 0, 0, 0, 0,
ax_anim_terminator
sBellsproutAnims_8_3:
ax_anim 20, 0, 146, 0, 0, 0, 0,
ax_anim 22, 0, 145, 0, 0, 0, 0,
ax_anim_terminator
sBellsproutAnims_8_4:
ax_anim 20, 0, 149, 0, 0, 0, 0,
ax_anim 22, 0, 148, 0, 0, 0, 0,
ax_anim_terminator
sBellsproutAnims_8_5:
ax_anim 20, 0, 152, 0, 0, 0, 0,
ax_anim 22, 0, 151, 0, 0, 0, 0,
ax_anim_terminator
sBellsproutAnims_8_6:
ax_anim 20, 0, 155, 0, 0, 0, 0,
ax_anim 22, 0, 154, 0, 0, 0, 0,
ax_anim_terminator
sBellsproutAnims_8_7:
ax_anim 20, 0, 158, 0, 0, 0, 0,
ax_anim 22, 0, 157, 0, 0, 0, 0,
ax_anim_terminator
sBellsproutAnims_8_8:
ax_anim 20, 0, 161, 0, 0, 0, 0,
ax_anim 22, 0, 160, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sBellsproutAnims_9_1:
ax_anim 2, 0, 162, 0, 0, 0, 0,
ax_anim 1, 0, 163, 6, 4, 6, 4,
ax_anim 2, 0, 164, 8, 9, 8, 9,
ax_anim 2, 0, 165, 7, 19, 7, 19,
ax_anim 3, 0, 166, 0, 21, 0, 24,
ax_anim 2, 3, 167, -7, 19, -7, 19,
ax_anim 2, 0, 168, -8, 9, -8, 9,
ax_anim 1, 0, 169, -6, 4, -6, 4,
ax_anim 1, 0, 162, 0, 0, 0, 0,
ax_anim_terminator
sBellsproutAnims_9_2:
ax_anim 2, 0, 169, 0, 0, 0, 0,
ax_anim 1, 0, 162, 6, 0, 6, 0,
ax_anim 2, 0, 163, 17, 3, 17, 3,
ax_anim 2, 0, 164, 24, 9, 24, 9,
ax_anim 3, 0, 165, 20, 21, 20, 21,
ax_anim 2, 3, 166, 11, 21, 11, 21,
ax_anim 2, 0, 167, 2, 12, 2, 12,
ax_anim 1, 0, 168, 0, 7, 0, 7,
ax_anim 1, 0, 169, 0, 0, 0, 0,
ax_anim_terminator
sBellsproutAnims_9_3:
ax_anim 2, 0, 168, 0, 0, 0, 0,
ax_anim 1, 0, 169, 3, -4, 3, -4,
ax_anim 2, 0, 162, 11, -6, 11, -6,
ax_anim 2, 0, 163, 19, -4, 19, -4,
ax_anim 3, 0, 164, 22, 1, 22, 1,
ax_anim 2, 3, 165, 18, 6, 18, 6,
ax_anim 2, 0, 166, 12, 7, 12, 7,
ax_anim 1, 0, 167, 4, 5, 4, 5,
ax_anim 1, 0, 168, 0, 0, 0, 0,
ax_anim_terminator
sBellsproutAnims_9_4:
ax_anim 2, 0, 167, 0, 0, 0, 0,
ax_anim 1, 0, 168, -1, -6, -1, -6,
ax_anim 2, 0, 169, 2, -18, 2, -18,
ax_anim 2, 0, 162, 12, -22, 12, -22,
ax_anim 3, 0, 163, 21, -19, 21, -19,
ax_anim 2, 3, 164, 21, -15, 21, -15,
ax_anim 2, 0, 165, 16, -6, 16, -6,
ax_anim 1, 0, 166, 7, -1, 7, -1,
ax_anim 1, 0, 167, 0, 0, 0, 0,
ax_anim_terminator
sBellsproutAnims_9_5:
ax_anim 2, 0, 166, 0, 0, 0, 0,
ax_anim 1, 0, 167, -6, -4, -6, -4,
ax_anim 2, 0, 168, -8, -10, -8, -10,
ax_anim 2, 0, 169, -7, -16, -7, -16,
ax_anim 3, 0, 162, 0, -22, 0, -22,
ax_anim 2, 3, 163, 7, -16, 7, -16,
ax_anim 2, 0, 164, 8, -8, 8, -8,
ax_anim 1, 0, 165, 6, -4, 6, -4,
ax_anim 1, 0, 166, 0, 0, 0, 0,
ax_anim_terminator
sBellsproutAnims_9_6:
ax_anim 2, 0, 165, 0, 0, 0, 0,
ax_anim 1, 0, 164, 1, -6, 1, -6,
ax_anim 2, 0, 163, -2, -18, -2, -18,
ax_anim 2, 0, 162, -12, -22, -12, -22,
ax_anim 3, 0, 169, -21, -19, -21, -19,
ax_anim 2, 3, 168, -21, -15, -21, -15,
ax_anim 2, 0, 167, -16, -6, -16, -6,
ax_anim 1, 0, 166, -7, -1, -7, -1,
ax_anim 1, 0, 165, 0, 0, 0, 0,
ax_anim_terminator
sBellsproutAnims_9_7:
ax_anim 2, 0, 164, 0, 0, 0, 0,
ax_anim 1, 0, 163, -3, -4, -3, -4,
ax_anim 2, 0, 162, -11, -6, -11, -6,
ax_anim 2, 0, 169, -19, -4, -19, -4,
ax_anim 3, 0, 168, -22, 1, -22, 1,
ax_anim 2, 3, 167, -18, 6, -18, 6,
ax_anim 2, 0, 166, -12, 7, -12, 7,
ax_anim 1, 0, 165, -4, 5, -4, 5,
ax_anim 1, 0, 164, 0, 0, 0, 0,
ax_anim_terminator
sBellsproutAnims_9_8:
ax_anim 2, 0, 163, 0, 0, 0, 0,
ax_anim 1, 0, 162, -6, 0, -6, 0,
ax_anim 2, 0, 169, -17, 3, -17, 3,
ax_anim 2, 0, 168, -24, 9, -24, 9,
ax_anim 3, 0, 167, -20, 21, -20, 21,
ax_anim 2, 3, 166, -11, 21, -11, 16,
ax_anim 2, 0, 165, -2, 12, -4, 12,
ax_anim 1, 0, 164, 0, 7, -3, 7,
ax_anim 1, 0, 163, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sBellsproutAnims_10_1:
ax_anim 2, 0, 170, 0, 0, 0, 0,
ax_anim 2, 0, 170, 6, 0, 6, 0,
ax_anim 2, 0, 170, -6, 0, -6, 0,
ax_anim 2, 0, 170, 10, 0, 10, 0,
ax_anim 2, 0, 170, -10, 0, -10, 0,
ax_anim 2, 0, 170, 12, 0, 12, 0,
ax_anim 3, 0, 170, -12, 0, -12, 0,
ax_anim 3, 0, 170, 13, 0, 13, 0,
ax_anim 3, 0, 170, -13, 0, -13, 0,
ax_anim 2, 0, 170, 12, 0, 12, 0,
ax_anim 3, 0, 170, -12, 0, -12, 0,
ax_anim 2, 0, 170, 10, 0, 10, 0,
ax_anim 2, 0, 170, -10, 0, -10, 0,
ax_anim 2, 0, 170, 6, 0, 6, 0,
ax_anim 2, 0, 170, -6, 0, -6, 0,
ax_anim 2, 0, 170, 0, 0, 0, 0,
ax_anim_terminator
sBellsproutAnims_10_2:
ax_anim 2, 0, 171, 0, 0, 0, 0,
ax_anim 2, 0, 171, 6, -6, 6, -6,
ax_anim 2, 0, 171, -6, 6, -6, 6,
ax_anim 2, 0, 171, 10, -10, 10, -10,
ax_anim 2, 0, 171, -10, 10, -10, 10,
ax_anim 2, 0, 171, 12, -12, 12, -12,
ax_anim 3, 0, 171, -12, 12, -12, 12,
ax_anim 3, 0, 171, 13, -13, 13, -13,
ax_anim 3, 0, 171, -13, 13, -13, 13,
ax_anim 2, 0, 171, 12, -12, 12, -12,
ax_anim 3, 0, 171, -12, 12, -12, 12,
ax_anim 2, 0, 171, 10, -10, 10, -10,
ax_anim 2, 0, 171, -10, 10, -10, 10,
ax_anim 2, 0, 171, 6, -6, 6, -6,
ax_anim 2, 0, 171, -6, 6, -6, 6,
ax_anim 2, 0, 171, 0, 0, 0, 0,
ax_anim_terminator
sBellsproutAnims_10_3:
ax_anim 2, 0, 172, 0, 0, 0, 0,
ax_anim 2, 0, 172, 0, -6, 0, -6,
ax_anim 2, 0, 172, 0, 6, 0, 6,
ax_anim 2, 0, 172, 0, -10, 0, -10,
ax_anim 2, 0, 172, 0, 10, 0, 10,
ax_anim 2, 0, 172, 0, -12, 0, -12,
ax_anim 3, 0, 172, 0, 12, 0, 12,
ax_anim 3, 0, 172, 0, -13, 0, -13,
ax_anim 3, 0, 172, 0, 13, 0, 13,
ax_anim 2, 0, 172, 0, -12, 0, -12,
ax_anim 3, 0, 172, 0, 12, 0, 12,
ax_anim 2, 0, 172, 0, -10, 0, -10,
ax_anim 2, 0, 172, 0, 10, 0, 10,
ax_anim 2, 0, 172, 0, -6, 0, -6,
ax_anim 2, 0, 172, 0, 6, 0, 6,
ax_anim 2, 0, 172, 0, 0, 0, 0,
ax_anim_terminator
sBellsproutAnims_10_4:
ax_anim 2, 0, 173, 0, 0, 0, 0,
ax_anim 2, 0, 173, -6, -6, -6, -6,
ax_anim 2, 0, 173, 6, 6, 6, 6,
ax_anim 2, 0, 173, -10, -10, -10, -10,
ax_anim 2, 0, 173, 10, 10, 10, 10,
ax_anim 2, 0, 173, -12, -12, -12, -12,
ax_anim 3, 0, 173, 12, 12, 12, 12,
ax_anim 3, 0, 173, -13, -13, -13, -13,
ax_anim 3, 0, 173, 13, 13, 13, 13,
ax_anim 2, 0, 173, -12, -12, -12, -12,
ax_anim 3, 0, 173, 12, 12, 12, 12,
ax_anim 2, 0, 173, -10, -10, -10, -10,
ax_anim 2, 0, 173, 10, 10, 10, 10,
ax_anim 2, 0, 173, -6, -6, -6, -6,
ax_anim 2, 0, 173, 6, 6, 6, 6,
ax_anim 2, 0, 173, 0, 0, 0, 0,
ax_anim_terminator
sBellsproutAnims_10_5:
ax_anim 2, 0, 174, 0, 0, 0, 0,
ax_anim 2, 0, 174, 6, 0, 6, 0,
ax_anim 2, 0, 174, -6, 0, -6, 0,
ax_anim 2, 0, 174, 10, 0, 10, 0,
ax_anim 2, 0, 174, -10, 0, -10, 0,
ax_anim 2, 0, 174, 12, 0, 12, 0,
ax_anim 3, 0, 174, -12, 0, -12, 0,
ax_anim 3, 0, 174, 13, 0, 13, 0,
ax_anim 3, 0, 174, -13, 0, -13, 0,
ax_anim 2, 0, 174, 12, 0, 12, 0,
ax_anim 3, 0, 174, -12, 0, -12, 0,
ax_anim 2, 0, 174, 10, 0, 10, 0,
ax_anim 2, 0, 174, -10, 0, -10, 0,
ax_anim 2, 0, 174, 6, 0, 6, 0,
ax_anim 2, 0, 174, -6, 0, -6, 0,
ax_anim 2, 0, 174, 0, 0, 0, 0,
ax_anim_terminator
sBellsproutAnims_10_6:
ax_anim 2, 0, 175, 0, 0, 0, 0,
ax_anim 2, 0, 175, 6, -6, 6, -6,
ax_anim 2, 0, 175, -6, 6, -6, 6,
ax_anim 2, 0, 175, 10, -10, 10, -10,
ax_anim 2, 0, 175, -10, 10, -10, 10,
ax_anim 2, 0, 175, 12, -12, 12, -12,
ax_anim 3, 0, 175, -12, 12, -12, 12,
ax_anim 3, 0, 175, 13, -13, 13, -13,
ax_anim 3, 0, 175, -13, 13, -13, 13,
ax_anim 2, 0, 175, 12, -12, 12, -12,
ax_anim 3, 0, 175, -12, 12, -12, 12,
ax_anim 2, 0, 175, 10, -10, 10, -10,
ax_anim 2, 0, 175, -10, 10, -10, 10,
ax_anim 2, 0, 175, 6, -6, 6, -6,
ax_anim 2, 0, 175, -6, 6, -6, 6,
ax_anim 2, 0, 175, 0, 0, 0, 0,
ax_anim_terminator
sBellsproutAnims_10_7:
ax_anim 2, 0, 176, 0, 0, 0, 0,
ax_anim 2, 0, 176, 0, -6, 0, -6,
ax_anim 2, 0, 176, 0, 6, 0, 6,
ax_anim 2, 0, 176, 0, -10, 0, -10,
ax_anim 2, 0, 176, 0, 10, 0, 10,
ax_anim 2, 0, 176, 0, -12, 0, -12,
ax_anim 3, 0, 176, 0, 12, 0, 12,
ax_anim 3, 0, 176, 0, -13, 0, -13,
ax_anim 3, 0, 176, 0, 13, 0, 13,
ax_anim 2, 0, 176, 0, -12, 0, -12,
ax_anim 3, 0, 176, 0, 12, 0, 12,
ax_anim 2, 0, 176, 0, -10, 0, -10,
ax_anim 2, 0, 176, 0, 10, 0, 10,
ax_anim 2, 0, 176, 0, -6, 0, -6,
ax_anim 2, 0, 176, 0, 6, 0, 6,
ax_anim 2, 0, 176, 0, 0, 0, 0,
ax_anim_terminator
sBellsproutAnims_10_8:
ax_anim 2, 0, 177, 0, 0, 0, 0,
ax_anim 2, 0, 177, -6, -6, -6, -6,
ax_anim 2, 0, 177, 6, 6, 6, 6,
ax_anim 2, 0, 177, -10, -10, -10, -10,
ax_anim 2, 0, 177, 10, 10, 10, 10,
ax_anim 2, 0, 177, -12, -12, -12, -12,
ax_anim 3, 0, 177, 12, 12, 12, 12,
ax_anim 3, 0, 177, -13, -13, -13, -13,
ax_anim 3, 0, 177, 13, 13, 13, 13,
ax_anim 2, 0, 177, -12, -12, -12, -12,
ax_anim 3, 0, 177, 12, 12, 12, 12,
ax_anim 2, 0, 177, -10, -10, -10, -10,
ax_anim 2, 0, 177, 10, 10, 10, 10,
ax_anim 2, 0, 177, -6, -6, -6, -6,
ax_anim 2, 0, 177, 6, 6, 6, 6,
ax_anim 2, 0, 177, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sBellsproutAnims_11_1:
ax_anim 2, 0, 178, 0, 0, 0, 0,
ax_anim 1, 0, 180, 0, -10, 0, 0,
ax_anim 2, 0, 180, 0, -16, 0, 0,
ax_anim 3, 0, 180, 0, -20, 0, 0,
ax_anim 4, 0, 180, 0, -21, 0, 0,
ax_anim 4, 0, 179, 0, -23, 0, 0,
ax_anim 3, 0, 179, 0, -22, 0, 0,
ax_anim 2, 0, 179, 0, -18, 0, 0,
ax_anim 1, 0, 179, 0, -12, 0, 0,
ax_anim 2, 2, 179, 0, 0, 0, 0,
ax_anim_terminator
sBellsproutAnims_11_2:
ax_anim 2, 0, 181, 0, 0, 0, 0,
ax_anim 1, 0, 183, 0, -10, 0, 0,
ax_anim 2, 0, 183, 0, -16, 0, 0,
ax_anim 3, 0, 183, 0, -20, 0, 0,
ax_anim 4, 0, 183, 0, -21, 0, 0,
ax_anim 4, 0, 182, 0, -23, 0, 0,
ax_anim 3, 0, 182, 0, -22, 0, 0,
ax_anim 2, 0, 182, 0, -18, 0, 0,
ax_anim 1, 0, 182, 0, -12, 0, 0,
ax_anim 2, 2, 182, 0, 0, 0, 0,
ax_anim_terminator
sBellsproutAnims_11_3:
ax_anim 2, 0, 184, 0, 0, 0, 0,
ax_anim 1, 0, 186, 0, -10, 0, 0,
ax_anim 2, 0, 186, 0, -16, 0, 0,
ax_anim 3, 0, 186, 0, -20, 0, 0,
ax_anim 4, 0, 186, 0, -21, 0, 0,
ax_anim 4, 0, 185, 0, -23, 0, 0,
ax_anim 3, 0, 185, 0, -22, 0, 0,
ax_anim 2, 0, 185, 0, -18, 0, 0,
ax_anim 1, 0, 185, 0, -12, 0, 0,
ax_anim 2, 2, 185, 0, 0, 0, 0,
ax_anim_terminator
sBellsproutAnims_11_4:
ax_anim 2, 0, 187, 0, 0, 0, 0,
ax_anim 1, 0, 189, 0, -10, 0, 0,
ax_anim 2, 0, 189, 0, -16, 0, 0,
ax_anim 3, 0, 189, 0, -20, 0, 0,
ax_anim 4, 0, 189, 0, -21, 0, 0,
ax_anim 4, 0, 188, 0, -22, 0, 0,
ax_anim 3, 0, 188, 0, -21, 0, 0,
ax_anim 2, 0, 188, 0, -17, 0, 0,
ax_anim 1, 0, 188, 0, -11, 0, 0,
ax_anim 2, 2, 188, 0, 0, 0, 0,
ax_anim_terminator
sBellsproutAnims_11_5:
ax_anim 2, 0, 190, 0, 0, 0, 0,
ax_anim 1, 0, 192, 0, -10, 0, 0,
ax_anim 2, 0, 192, 0, -16, 0, 0,
ax_anim 3, 0, 192, 0, -20, 0, 0,
ax_anim 4, 0, 192, 0, -21, 0, 0,
ax_anim 4, 0, 191, 0, -23, 0, 0,
ax_anim 3, 0, 191, 0, -22, 0, 0,
ax_anim 2, 0, 191, 0, -18, 0, 0,
ax_anim 1, 0, 191, 0, -12, 0, 0,
ax_anim 2, 2, 191, 0, 0, 0, 0,
ax_anim_terminator
sBellsproutAnims_11_6:
ax_anim 2, 0, 193, 0, 0, 0, 0,
ax_anim 1, 0, 195, 0, -10, 0, 0,
ax_anim 2, 0, 195, 0, -16, 0, 0,
ax_anim 3, 0, 195, 0, -20, 0, 0,
ax_anim 4, 0, 195, 0, -21, 0, 0,
ax_anim 4, 0, 194, 0, -22, 0, 0,
ax_anim 3, 0, 194, 0, -21, 0, 0,
ax_anim 2, 0, 194, 0, -17, 0, 0,
ax_anim 1, 0, 194, 0, -11, 0, 0,
ax_anim 2, 2, 194, 0, 0, 0, 0,
ax_anim_terminator
sBellsproutAnims_11_7:
ax_anim 2, 0, 196, 0, 0, 0, 0,
ax_anim 1, 0, 198, 0, -10, 0, 0,
ax_anim 2, 0, 198, 0, -16, 0, 0,
ax_anim 3, 0, 198, 0, -20, 0, 0,
ax_anim 4, 0, 198, 0, -21, 0, 0,
ax_anim 4, 0, 197, 0, -23, 0, 0,
ax_anim 3, 0, 197, 0, -22, 0, 0,
ax_anim 2, 0, 197, 0, -18, 0, 0,
ax_anim 1, 0, 197, 0, -12, 0, 0,
ax_anim 2, 2, 197, 0, 0, 0, 0,
ax_anim_terminator
sBellsproutAnims_11_8:
ax_anim 2, 0, 199, 0, 0, 0, 0,
ax_anim 1, 0, 201, 0, -10, 0, 0,
ax_anim 2, 0, 201, 0, -16, 0, 0,
ax_anim 3, 0, 201, 0, -20, 0, 0,
ax_anim 4, 0, 201, 0, -21, 0, 0,
ax_anim 4, 0, 200, 0, -23, 0, 0,
ax_anim 3, 0, 200, 0, -22, 0, 0,
ax_anim 2, 0, 200, 0, -18, 0, 0,
ax_anim 1, 0, 200, 0, -12, 0, 0,
ax_anim 2, 2, 200, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sBellsproutAnims_12_1:
ax_anim 2, 0, 202, 1, 0, 1, 0,
ax_anim 2, 0, 202, 0, 0, 0, 0,
ax_anim 2, 0, 202, 1, 0, 1, 0,
ax_anim 2, 0, 202, 0, 0, 0, 0,
ax_anim 2, 0, 202, 1, 0, 1, 0,
ax_anim 2, 2, 202, 0, 0, 0, 0,
ax_anim 2, 0, 202, 1, 0, 1, 0,
ax_anim 2, 0, 202, 0, 0, 0, 0,
ax_anim 2, 0, 202, 1, 0, 1, 0,
ax_anim 2, 1, 202, 0, 0, 0, 0,
ax_anim_terminator
sBellsproutAnims_12_2:
ax_anim 2, 0, 209, 1, -1, 1, 0,
ax_anim 2, 0, 209, 0, 0, 0, 0,
ax_anim 2, 0, 209, 1, -1, 1, 0,
ax_anim 2, 0, 209, 0, 0, 0, 0,
ax_anim 2, 0, 209, 1, -1, 1, 0,
ax_anim 2, 2, 209, 0, 0, 0, 0,
ax_anim 2, 0, 209, 1, -1, 1, 0,
ax_anim 2, 0, 209, 0, 0, 0, 0,
ax_anim 2, 0, 209, 1, -1, 1, 0,
ax_anim 2, 1, 209, 0, 0, 0, 0,
ax_anim_terminator
sBellsproutAnims_12_3:
ax_anim 2, 0, 208, 0, -1, 0, -1,
ax_anim 2, 0, 208, 0, 0, 0, 0,
ax_anim 2, 0, 208, 0, -1, 0, -1,
ax_anim 2, 0, 208, 0, 0, 0, 0,
ax_anim 2, 0, 208, 0, -1, 0, -1,
ax_anim 2, 2, 208, 0, 0, 0, 0,
ax_anim 2, 0, 208, 0, -1, 0, -1,
ax_anim 2, 0, 208, 0, 0, 0, 0,
ax_anim 2, 0, 208, 0, -1, 0, -1,
ax_anim 2, 1, 208, 0, 0, 0, 0,
ax_anim_terminator
sBellsproutAnims_12_4:
ax_anim 2, 0, 207, -1, -1, -1, -1,
ax_anim 2, 0, 207, 0, 0, 0, 0,
ax_anim 2, 0, 207, -1, -1, -1, -1,
ax_anim 2, 0, 207, 0, 0, 0, 0,
ax_anim 2, 0, 207, -1, -1, -1, -1,
ax_anim 2, 2, 207, 0, 0, 0, 0,
ax_anim 2, 0, 207, -1, -1, -1, -1,
ax_anim 2, 0, 207, 0, 0, 0, 0,
ax_anim 2, 0, 207, -1, -1, -1, -1,
ax_anim 2, 1, 207, 0, 0, 0, 0,
ax_anim_terminator
sBellsproutAnims_12_5:
ax_anim 2, 0, 206, 1, 0, 1, 0,
ax_anim 2, 0, 206, 0, 0, 0, 0,
ax_anim 2, 0, 206, 1, 0, 1, 0,
ax_anim 2, 0, 206, 0, 0, 0, 0,
ax_anim 2, 0, 206, 1, 0, 1, 0,
ax_anim 2, 2, 206, 0, 0, 0, 0,
ax_anim 2, 0, 206, 1, 0, 1, 0,
ax_anim 2, 0, 206, 0, 0, 0, 0,
ax_anim 2, 0, 206, 1, 0, 1, 0,
ax_anim 2, 1, 206, 0, 0, 0, 0,
ax_anim_terminator
sBellsproutAnims_12_6:
ax_anim 2, 0, 205, 1, -1, 1, -1,
ax_anim 2, 0, 205, 0, 0, 0, 0,
ax_anim 2, 0, 205, 1, -1, 1, -1,
ax_anim 2, 0, 205, 0, 0, 0, 0,
ax_anim 2, 0, 205, 1, -1, 1, -1,
ax_anim 2, 2, 205, 0, 0, 0, 0,
ax_anim 2, 0, 205, 1, -1, 1, -1,
ax_anim 2, 0, 205, 0, 0, 0, 0,
ax_anim 2, 0, 205, 1, -1, 1, -1,
ax_anim 2, 1, 205, 0, 0, 0, 0,
ax_anim_terminator
sBellsproutAnims_12_7:
ax_anim 2, 0, 204, 0, -1, 0, -1,
ax_anim 2, 0, 204, 0, 0, 0, 0,
ax_anim 2, 0, 204, 0, -1, 0, -1,
ax_anim 2, 0, 204, 0, 0, 0, 0,
ax_anim 2, 0, 204, 0, -1, 0, -1,
ax_anim 2, 2, 204, 0, 0, 0, 0,
ax_anim 2, 0, 204, 0, -1, 0, -1,
ax_anim 2, 0, 204, 0, 0, 0, 0,
ax_anim 2, 0, 204, 0, -1, 0, -1,
ax_anim 2, 1, 204, 0, 0, 0, 0,
ax_anim_terminator
sBellsproutAnims_12_8:
ax_anim 2, 0, 203, -1, -1, -1, -1,
ax_anim 2, 0, 203, 0, 0, 0, 0,
ax_anim 2, 0, 203, -1, -1, -1, -1,
ax_anim 2, 0, 203, 0, 0, 0, 0,
ax_anim 2, 0, 203, -1, -1, -1, -1,
ax_anim 2, 2, 203, 0, 0, 0, 0,
ax_anim 2, 0, 203, -1, -1, -1, -1,
ax_anim 2, 0, 203, 0, 0, 0, 0,
ax_anim 2, 0, 203, -1, -1, -1, -1,
ax_anim 2, 1, 203, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sBellsproutAnims_13_1:
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 2, 210, 0, 0, 0, 0,
ax_anim_terminator
sBellsproutAnims_13_2:
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 2, 217, 0, 0, 0, 0,
ax_anim_terminator
sBellsproutAnims_13_3:
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 2, 216, 0, 0, 0, 0,
ax_anim_terminator
sBellsproutAnims_13_4:
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 2, 2, 215, 0, 0, 0, 0,
ax_anim_terminator
sBellsproutAnims_13_5:
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 2, 2, 214, 0, 0, 0, 0,
ax_anim_terminator
sBellsproutAnims_13_6:
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 2, 2, 213, 0, 0, 0, 0,
ax_anim_terminator
sBellsproutAnims_13_7:
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 2, 2, 212, 0, 0, 0, 0,
ax_anim_terminator
sBellsproutAnims_13_8:
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 2, 2, 211, 0, 0, 0, 0,
ax_anim_terminator
sBellsproutGfx1:
.incbin "baserom.gba", 0x802490, 0x200
sBellsproutSprites1:
ax_sprite sBellsproutGfx1, 0x200
ax_sprite_terminator
sBellsproutGfx2:
.incbin "baserom.gba", 0x8026A0, 0x200
sBellsproutSprites2:
ax_sprite sBellsproutGfx2, 0x200
ax_sprite_terminator
sBellsproutGfx3:
.incbin "baserom.gba", 0x8028B0, 0x200
sBellsproutSprites3:
ax_sprite sBellsproutGfx3, 0x200
ax_sprite_terminator
sBellsproutGfx4:
.incbin "baserom.gba", 0x802AC0, 0x100
sBellsproutSprites4:
ax_sprite sBellsproutGfx4, 0x100
ax_sprite_terminator
sBellsproutGfx5:
.incbin "baserom.gba", 0x802BD0, 0x100
sBellsproutSprites5:
ax_sprite sBellsproutGfx5, 0x100
ax_sprite_terminator
sBellsproutGfx6:
.incbin "baserom.gba", 0x802CE0, 0x100
sBellsproutSprites6:
ax_sprite sBellsproutGfx6, 0x100
ax_sprite_terminator
sBellsproutGfx7:
.incbin "baserom.gba", 0x802DF0, 0x100
sBellsproutSprites7:
ax_sprite sBellsproutGfx7, 0x100
ax_sprite_terminator
sBellsproutGfx8:
.incbin "baserom.gba", 0x802F00, 0x100
sBellsproutSprites8:
ax_sprite sBellsproutGfx8, 0x100
ax_sprite_terminator
sBellsproutGfx9:
.incbin "baserom.gba", 0x803010, 0x100
sBellsproutSprites9:
ax_sprite sBellsproutGfx9, 0x100
ax_sprite_terminator
sBellsproutGfx10:
.incbin "baserom.gba", 0x803120, 0x100
sBellsproutSprites10:
ax_sprite sBellsproutGfx10, 0x100
ax_sprite_terminator
sBellsproutGfx11:
.incbin "baserom.gba", 0x803230, 0x100
sBellsproutSprites11:
ax_sprite sBellsproutGfx11, 0x100
ax_sprite_terminator
sBellsproutGfx12:
.incbin "baserom.gba", 0x803340, 0x100
sBellsproutSprites12:
ax_sprite sBellsproutGfx12, 0x100
ax_sprite_terminator
sBellsproutGfx13:
.incbin "baserom.gba", 0x803450, 0x200
sBellsproutSprites13:
ax_sprite sBellsproutGfx13, 0x200
ax_sprite_terminator
sBellsproutGfx14:
.incbin "baserom.gba", 0x803660, 0x100
sBellsproutSprites14:
ax_sprite sBellsproutGfx14, 0x100
ax_sprite_terminator
sBellsproutGfx15:
.incbin "baserom.gba", 0x803770, 0x100
sBellsproutSprites15:
ax_sprite sBellsproutGfx15, 0x100
ax_sprite_terminator
sBellsproutGfx16:
.incbin "baserom.gba", 0x803880, 0x40
sBellsproutGfx16_1:
.incbin "baserom.gba", 0x8038C0, 0x60
sBellsproutGfx16_2:
.incbin "baserom.gba", 0x803920, 0x60
sBellsproutSprites16:
ax_sprite sBellsproutGfx16, 0x40
ax_sprite 0, 0x40
ax_sprite sBellsproutGfx16_1, 0x60
ax_sprite 0, 0x20
ax_sprite sBellsproutGfx16_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sBellsproutGfx17:
.incbin "baserom.gba", 0x8039B8, 0x20
sBellsproutGfx17_1:
.incbin "baserom.gba", 0x8039D8, 0x20
sBellsproutGfx17_2:
.incbin "baserom.gba", 0x8039F8, 0x40
sBellsproutSprites17:
ax_sprite sBellsproutGfx17, 0x20
ax_sprite 0, 0x20
ax_sprite sBellsproutGfx17_1, 0x20
ax_sprite 0, 0x20
ax_sprite sBellsproutGfx17_2, 0x40
ax_sprite 0, 0x40
ax_sprite_terminator
sBellsproutGfx18:
.incbin "baserom.gba", 0x803A70, 0x40
sBellsproutGfx18_1:
.incbin "baserom.gba", 0x803AB0, 0x60
sBellsproutGfx18_2:
.incbin "baserom.gba", 0x803B10, 0x60
sBellsproutSprites18:
ax_sprite 0, 0x20
ax_sprite sBellsproutGfx18, 0x40
ax_sprite 0, 0x20
ax_sprite sBellsproutGfx18_1, 0x60
ax_sprite 0, 0x20
ax_sprite sBellsproutGfx18_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sBellsproutGfx19:
.incbin "baserom.gba", 0x803BB0, 0x60
sBellsproutGfx19_1:
.incbin "baserom.gba", 0x803C10, 0x60
sBellsproutGfx19_2:
.incbin "baserom.gba", 0x803C70, 0x60
sBellsproutSprites19:
ax_sprite sBellsproutGfx19, 0x60
ax_sprite 0, 0x20
ax_sprite sBellsproutGfx19_1, 0x60
ax_sprite 0, 0x20
ax_sprite sBellsproutGfx19_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sBellsproutGfx20:
.incbin "baserom.gba", 0x803D08, 0x60
sBellsproutGfx20_1:
.incbin "baserom.gba", 0x803D68, 0x60
sBellsproutSprites20:
ax_sprite 0, 0x80
ax_sprite sBellsproutGfx20, 0x60
ax_sprite 0, 0x20
ax_sprite sBellsproutGfx20_1, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sBellsproutGfx21:
.incbin "baserom.gba", 0x803DF8, 0x60
sBellsproutGfx21_1:
.incbin "baserom.gba", 0x803E58, 0x20
sBellsproutSprites21:
ax_sprite sBellsproutGfx21, 0x60
ax_sprite 0, 0x20
ax_sprite sBellsproutGfx21_1, 0x20
ax_sprite 0, 0x60
ax_sprite_terminator
sBellsproutGfx22:
.incbin "baserom.gba", 0x803EA0, 0x40
sBellsproutGfx22_1:
.incbin "baserom.gba", 0x803EE0, 0x60
sBellsproutGfx22_2:
.incbin "baserom.gba", 0x803F40, 0x40
sBellsproutGfx22_3:
.incbin "baserom.gba", 0x803F80, 0x40
sBellsproutSprites22:
ax_sprite 0, 0x20
ax_sprite sBellsproutGfx22, 0x40
ax_sprite 0, 0x20
ax_sprite sBellsproutGfx22_1, 0x60
ax_sprite 0, 0x40
ax_sprite sBellsproutGfx22_2, 0x40
ax_sprite 0, 0x40
ax_sprite sBellsproutGfx22_3, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sBellsproutGfx23:
.incbin "baserom.gba", 0x804010, 0x40
sBellsproutGfx23_1:
.incbin "baserom.gba", 0x804050, 0x60
sBellsproutGfx23_2:
.incbin "baserom.gba", 0x8040B0, 0x40
sBellsproutSprites23:
ax_sprite 0, 0x80
ax_sprite sBellsproutGfx23, 0x40
ax_sprite 0, 0x40
ax_sprite sBellsproutGfx23_1, 0x60
ax_sprite 0, 0x40
ax_sprite sBellsproutGfx23_2, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sBellsproutGfx24:
.incbin "baserom.gba", 0x804130, 0x60
sBellsproutGfx24_1:
.incbin "baserom.gba", 0x804190, 0x40
sBellsproutGfx24_2:
.incbin "baserom.gba", 0x8041D0, 0x20
sBellsproutSprites24:
ax_sprite sBellsproutGfx24, 0x60
ax_sprite 0, 0x20
ax_sprite sBellsproutGfx24_1, 0x40
ax_sprite 0, 0x40
ax_sprite sBellsproutGfx24_2, 0x20
ax_sprite 0, 0xe0
ax_sprite_terminator
sBellsproutGfx25:
.incbin "baserom.gba", 0x804228, 0x40
sBellsproutGfx25_1:
.incbin "baserom.gba", 0x804268, 0x60
sBellsproutGfx25_2:
.incbin "baserom.gba", 0x8042C8, 0x40
sBellsproutSprites25:
ax_sprite 0, 0x20
ax_sprite sBellsproutGfx25, 0x40
ax_sprite 0, 0x20
ax_sprite sBellsproutGfx25_1, 0x60
ax_sprite 0, 0x40
ax_sprite sBellsproutGfx25_2, 0x40
ax_sprite 0, 0xa0
ax_sprite_terminator
sBellsproutGfx26:
.incbin "baserom.gba", 0x804348, 0x40
sBellsproutGfx26_1:
.incbin "baserom.gba", 0x804388, 0x60
sBellsproutGfx26_2:
.incbin "baserom.gba", 0x8043E8, 0x60
sBellsproutSprites26:
ax_sprite sBellsproutGfx26, 0x40
ax_sprite 0, 0x40
ax_sprite sBellsproutGfx26_1, 0x60
ax_sprite 0, 0x20
ax_sprite sBellsproutGfx26_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sBellsproutGfx27:
.incbin "baserom.gba", 0x804480, 0x60
sBellsproutGfx27_1:
.incbin "baserom.gba", 0x8044E0, 0xC0
sBellsproutSprites27:
ax_sprite sBellsproutGfx27, 0x60
ax_sprite 0, 0x20
ax_sprite sBellsproutGfx27_1, 0xc0
ax_sprite 0, 0xc0
ax_sprite_terminator
sBellsproutGfx28:
.incbin "baserom.gba", 0x8045C8, 0x40
sBellsproutGfx28_1:
.incbin "baserom.gba", 0x804608, 0x40
sBellsproutGfx28_2:
.incbin "baserom.gba", 0x804648, 0x40
sBellsproutSprites28:
ax_sprite sBellsproutGfx28, 0x40
ax_sprite 0, 0x40
ax_sprite sBellsproutGfx28_1, 0x40
ax_sprite 0, 0x40
ax_sprite sBellsproutGfx28_2, 0x40
ax_sprite 0, 0xc0
ax_sprite_terminator
sBellsproutGfx29:
.incbin "baserom.gba", 0x8046C0, 0x40
sBellsproutGfx29_1:
.incbin "baserom.gba", 0x804700, 0x40
sBellsproutGfx29_2:
.incbin "baserom.gba", 0x804740, 0x60
sBellsproutSprites29:
ax_sprite sBellsproutGfx29, 0x40
ax_sprite 0, 0x40
ax_sprite sBellsproutGfx29_1, 0x40
ax_sprite 0, 0x40
ax_sprite sBellsproutGfx29_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sBellsproutGfx30:
.incbin "baserom.gba", 0x8047D8, 0xC0
sBellsproutSprites30:
ax_sprite sBellsproutGfx30, 0xc0
ax_sprite 0, 0x40
ax_sprite_terminator
sBellsproutGfx31:
.incbin "baserom.gba", 0x8048B0, 0x40
sBellsproutGfx31_1:
.incbin "baserom.gba", 0x8048F0, 0x60
sBellsproutGfx31_2:
.incbin "baserom.gba", 0x804950, 0x60
sBellsproutSprites31:
ax_sprite sBellsproutGfx31, 0x40
ax_sprite 0, 0x40
ax_sprite sBellsproutGfx31_1, 0x60
ax_sprite 0, 0x20
ax_sprite sBellsproutGfx31_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sBellsproutGfx32:
.incbin "baserom.gba", 0x8049E8, 0x40
sBellsproutGfx32_1:
.incbin "baserom.gba", 0x804A28, 0x60
sBellsproutGfx32_2:
.incbin "baserom.gba", 0x804A88, 0x60
sBellsproutSprites32:
ax_sprite sBellsproutGfx32, 0x40
ax_sprite 0, 0x40
ax_sprite sBellsproutGfx32_1, 0x60
ax_sprite 0, 0x20
ax_sprite sBellsproutGfx32_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sBellsproutGfx33:
.incbin "baserom.gba", 0x804B20, 0x40
sBellsproutGfx33_1:
.incbin "baserom.gba", 0x804B60, 0x60
sBellsproutGfx33_2:
.incbin "baserom.gba", 0x804BC0, 0x60
sBellsproutSprites33:
ax_sprite sBellsproutGfx33, 0x40
ax_sprite 0, 0x40
ax_sprite sBellsproutGfx33_1, 0x60
ax_sprite 0, 0x20
ax_sprite sBellsproutGfx33_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sBellsproutGfx34:
.incbin "baserom.gba", 0x804C58, 0x40
sBellsproutGfx34_1:
.incbin "baserom.gba", 0x804C98, 0x60
sBellsproutGfx34_2:
.incbin "baserom.gba", 0x804CF8, 0x60
sBellsproutSprites34:
ax_sprite sBellsproutGfx34, 0x40
ax_sprite 0, 0x40
ax_sprite sBellsproutGfx34_1, 0x60
ax_sprite 0, 0x20
ax_sprite sBellsproutGfx34_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sBellsproutGfx35:
.incbin "baserom.gba", 0x804D90, 0x40
sBellsproutGfx35_1:
.incbin "baserom.gba", 0x804DD0, 0x60
sBellsproutGfx35_2:
.incbin "baserom.gba", 0x804E30, 0x40
sBellsproutSprites35:
ax_sprite sBellsproutGfx35, 0x40
ax_sprite 0, 0x40
ax_sprite sBellsproutGfx35_1, 0x60
ax_sprite 0, 0x40
ax_sprite sBellsproutGfx35_2, 0x40
ax_sprite 0, 0xa0
ax_sprite_terminator
sBellsproutGfx36:
.incbin "baserom.gba", 0x804EA8, 0x40
sBellsproutGfx36_1:
.incbin "baserom.gba", 0x804EE8, 0x60
sBellsproutGfx36_2:
.incbin "baserom.gba", 0x804F48, 0x40
sBellsproutSprites36:
ax_sprite sBellsproutGfx36, 0x40
ax_sprite 0, 0x40
ax_sprite sBellsproutGfx36_1, 0x60
ax_sprite 0, 0x40
ax_sprite sBellsproutGfx36_2, 0x40
ax_sprite 0, 0xa0
ax_sprite_terminator
sBellsproutGfx37:
.incbin "baserom.gba", 0x804FC0, 0x40
sBellsproutGfx37_1:
.incbin "baserom.gba", 0x805000, 0x60
sBellsproutGfx37_2:
.incbin "baserom.gba", 0x805060, 0x40
sBellsproutSprites37:
ax_sprite sBellsproutGfx37, 0x40
ax_sprite 0, 0x40
ax_sprite sBellsproutGfx37_1, 0x60
ax_sprite 0, 0x40
ax_sprite sBellsproutGfx37_2, 0x40
ax_sprite 0, 0xa0
ax_sprite_terminator
sBellsproutGfx38:
.incbin "baserom.gba", 0x8050D8, 0x40
sBellsproutGfx38_1:
.incbin "baserom.gba", 0x805118, 0x60
sBellsproutGfx38_2:
.incbin "baserom.gba", 0x805178, 0x40
sBellsproutSprites38:
ax_sprite sBellsproutGfx38, 0x40
ax_sprite 0, 0x40
ax_sprite sBellsproutGfx38_1, 0x60
ax_sprite 0, 0x40
ax_sprite sBellsproutGfx38_2, 0x40
ax_sprite 0, 0xa0
ax_sprite_terminator
sBellsproutGfx39:
.incbin "baserom.gba", 0x8051F0, 0x40
sBellsproutGfx39_1:
.incbin "baserom.gba", 0x805230, 0x60
sBellsproutGfx39_2:
.incbin "baserom.gba", 0x805290, 0x60
sBellsproutSprites39:
ax_sprite sBellsproutGfx39, 0x40
ax_sprite 0, 0x40
ax_sprite sBellsproutGfx39_1, 0x60
ax_sprite 0, 0x20
ax_sprite sBellsproutGfx39_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sBellsproutGfx40:
.incbin "baserom.gba", 0x805328, 0x40
sBellsproutGfx40_1:
.incbin "baserom.gba", 0x805368, 0x40
sBellsproutGfx40_2:
.incbin "baserom.gba", 0x8053A8, 0x60
sBellsproutSprites40:
ax_sprite sBellsproutGfx40, 0x40
ax_sprite 0, 0x40
ax_sprite sBellsproutGfx40_1, 0x40
ax_sprite 0, 0x40
ax_sprite sBellsproutGfx40_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sBellsproutGfx41:
.incbin "baserom.gba", 0x805440, 0x200
sBellsproutSprites41:
ax_sprite sBellsproutGfx41, 0x200
ax_sprite_terminator
sBellsproutGfx42:
.incbin "baserom.gba", 0x805650, 0x200
sBellsproutSprites42:
ax_sprite sBellsproutGfx42, 0x200
ax_sprite_terminator
sBellsproutGfx43:
.incbin "baserom.gba", 0x805860, 0x200
sBellsproutSprites43:
ax_sprite sBellsproutGfx43, 0x200
ax_sprite_terminator
sBellsproutGfx44:
.incbin "baserom.gba", 0x805A70, 0x200
sBellsproutSprites44:
ax_sprite sBellsproutGfx44, 0x200
ax_sprite_terminator
sBellsproutGfx45:
.incbin "baserom.gba", 0x805C80, 0x200
sBellsproutSprites45:
ax_sprite sBellsproutGfx45, 0x200
ax_sprite_terminator
sBellsproutGfx46:
.incbin "baserom.gba", 0x805E90, 0x200
sBellsproutSprites46:
ax_sprite sBellsproutGfx46, 0x200
ax_sprite_terminator
sBellsproutGfx47:
.incbin "baserom.gba", 0x8060A0, 0x200
sBellsproutSprites47:
ax_sprite sBellsproutGfx47, 0x200
ax_sprite_terminator
sAxPosesBellsprout:
.4byte sBellsproutPose1
.4byte sBellsproutPose2
.4byte sBellsproutPose3
.4byte sBellsproutPose4
.4byte sBellsproutPose5
.4byte sBellsproutPose6
.4byte sBellsproutPose7
.4byte sBellsproutPose8
.4byte sBellsproutPose9
.4byte sBellsproutPose10
.4byte sBellsproutPose11
.4byte sBellsproutPose12
.4byte sBellsproutPose13
.4byte sBellsproutPose14
.4byte sBellsproutPose15
.4byte sBellsproutPose16
.4byte sBellsproutPose17
.4byte sBellsproutPose18
.4byte sBellsproutPose19
.4byte sBellsproutPose20
.4byte sBellsproutPose21
.4byte sBellsproutPose22
.4byte sBellsproutPose23
.4byte sBellsproutPose24
.4byte sBellsproutPose25
.4byte sBellsproutPose26
.4byte sBellsproutPose27
.4byte sBellsproutPose28
.4byte sBellsproutPose29
.4byte sBellsproutPose30
.4byte sBellsproutPose31
.4byte sBellsproutPose32
.4byte sBellsproutPose33
.4byte sBellsproutPose34
.4byte sBellsproutPose35
.4byte sBellsproutPose36
.4byte sBellsproutPose37
.4byte sBellsproutPose38
.4byte sBellsproutPose39
.4byte sBellsproutPose40
.4byte sBellsproutPose41
.4byte sBellsproutPose42
.4byte sBellsproutPose43
.4byte sBellsproutPose44
.4byte sBellsproutPose45
.4byte sBellsproutPose46
.4byte sBellsproutPose47
.4byte sBellsproutPose48
.4byte sBellsproutPose49
.4byte sBellsproutPose50
.4byte sBellsproutPose51
.4byte sBellsproutPose52
.4byte sBellsproutPose53
.4byte sBellsproutPose54
.4byte sBellsproutPose55
.4byte sBellsproutPose56
.4byte sBellsproutPose57
.4byte sBellsproutPose58
.4byte sBellsproutPose59
.4byte sBellsproutPose60
.4byte sBellsproutPose61
.4byte sBellsproutPose62
.4byte sBellsproutPose63
.4byte sBellsproutPose64
.4byte sBellsproutPose65
.4byte sBellsproutPose66
.4byte sBellsproutPose67
.4byte sBellsproutPose68
.4byte sBellsproutPose69
.4byte sBellsproutPose70
.4byte sBellsproutPose71
.4byte sBellsproutPose72
.4byte sBellsproutPose73
.4byte sBellsproutPose74
.4byte sBellsproutPose75
.4byte sBellsproutPose76
.4byte sBellsproutPose77
.4byte sBellsproutPose78
.4byte sBellsproutPose79
.4byte sBellsproutPose80
.4byte sBellsproutPose81
.4byte sBellsproutPose82
.4byte sBellsproutPose83
.4byte sBellsproutPose84
.4byte sBellsproutPose85
.4byte sBellsproutPose86
.4byte sBellsproutPose87
.4byte sBellsproutPose88
.4byte sBellsproutPose89
.4byte sBellsproutPose90
.4byte sBellsproutPose91
.4byte sBellsproutPose92
.4byte sBellsproutPose93
.4byte sBellsproutPose94
.4byte sBellsproutPose95
.4byte sBellsproutPose96
.4byte sBellsproutPose97
.4byte sBellsproutPose98
.4byte sBellsproutPose99
.4byte sBellsproutPose100
.4byte sBellsproutPose101
.4byte sBellsproutPose102
.4byte sBellsproutPose103
.4byte sBellsproutPose104
.4byte sBellsproutPose105
.4byte sBellsproutPose106
.4byte sBellsproutPose107
.4byte sBellsproutPose108
.4byte sBellsproutPose109
.4byte sBellsproutPose110
.4byte sBellsproutPose111
.4byte sBellsproutPose112
.4byte sBellsproutPose113
.4byte sBellsproutPose114
.4byte sBellsproutPose115
.4byte sBellsproutPose116
.4byte sBellsproutPose117
.4byte sBellsproutPose118
.4byte sBellsproutPose119
.4byte sBellsproutPose120
.4byte sBellsproutPose121
.4byte sBellsproutPose122
.4byte sBellsproutPose123
.4byte sBellsproutPose124
.4byte sBellsproutPose125
.4byte sBellsproutPose126
.4byte sBellsproutPose127
.4byte sBellsproutPose128
.4byte sBellsproutPose129
.4byte sBellsproutPose130
.4byte sBellsproutPose131
.4byte sBellsproutPose132
.4byte sBellsproutPose133
.4byte sBellsproutPose134
.4byte sBellsproutPose135
.4byte sBellsproutPose136
.4byte sBellsproutPose137
.4byte sBellsproutPose138
.4byte sBellsproutPose139
.4byte sBellsproutPose140
.4byte sBellsproutPose141
.4byte sBellsproutPose142
.4byte sBellsproutPose143
.4byte sBellsproutPose144
.4byte sBellsproutPose145
.4byte sBellsproutPose146
.4byte sBellsproutPose147
.4byte sBellsproutPose148
.4byte sBellsproutPose149
.4byte sBellsproutPose150
.4byte sBellsproutPose151
.4byte sBellsproutPose152
.4byte sBellsproutPose153
.4byte sBellsproutPose154
.4byte sBellsproutPose155
.4byte sBellsproutPose156
.4byte sBellsproutPose157
.4byte sBellsproutPose158
.4byte sBellsproutPose159
.4byte sBellsproutPose160
.4byte sBellsproutPose161
.4byte sBellsproutPose162
.4byte sBellsproutPose163
.4byte sBellsproutPose164
.4byte sBellsproutPose165
.4byte sBellsproutPose166
.4byte sBellsproutPose167
.4byte sBellsproutPose168
.4byte sBellsproutPose169
.4byte sBellsproutPose170
.4byte sBellsproutPose171
.4byte sBellsproutPose172
.4byte sBellsproutPose173
.4byte sBellsproutPose174
.4byte sBellsproutPose175
.4byte sBellsproutPose176
.4byte sBellsproutPose177
.4byte sBellsproutPose178
.4byte sBellsproutPose179
.4byte sBellsproutPose180
.4byte sBellsproutPose181
.4byte sBellsproutPose182
.4byte sBellsproutPose183
.4byte sBellsproutPose184
.4byte sBellsproutPose185
.4byte sBellsproutPose186
.4byte sBellsproutPose187
.4byte sBellsproutPose188
.4byte sBellsproutPose189
.4byte sBellsproutPose190
.4byte sBellsproutPose191
.4byte sBellsproutPose192
.4byte sBellsproutPose193
.4byte sBellsproutPose194
.4byte sBellsproutPose195
.4byte sBellsproutPose196
.4byte sBellsproutPose197
.4byte sBellsproutPose198
.4byte sBellsproutPose199
.4byte sBellsproutPose200
.4byte sBellsproutPose201
.4byte sBellsproutPose202
.4byte sBellsproutPose203
.4byte sBellsproutPose204
.4byte sBellsproutPose205
.4byte sBellsproutPose206
.4byte sBellsproutPose207
.4byte sBellsproutPose208
.4byte sBellsproutPose209
.4byte sBellsproutPose210
.4byte sBellsproutPose211
.4byte sBellsproutPose212
.4byte sBellsproutPose213
.4byte sBellsproutPose214
.4byte sBellsproutPose215
.4byte sBellsproutPose216
.4byte sBellsproutPose217
.4byte sBellsproutPose218
sAxPositionsBellsprout:
.2byte   -2,   -8, 	  -7,   -6, 	   6,   -6, 	  -1,   -6
.2byte   -1,   -7, 	  -8,   -8, 	   6,   -8, 	   0,   -5
.2byte   -2,   -6, 	  -7,   -4, 	   5,   -4, 	  -1,   -4
.2byte    4,   -7, 	   2,   -7, 	  -5,   -4, 	  -1,   -7
.2byte    3,   -6, 	   2,   -6, 	  -6,   -7, 	  -1,   -6
.2byte    4,   -5, 	   5,   -5, 	  -5,   -1, 	   0,   -5
.2byte    5,   -8, 	   1,   -7, 	  -1,   -3, 	   0,   -8
.2byte    5,   -6, 	   2,   -8, 	  -2,   -5, 	   0,   -7
.2byte    4,   -7, 	   2,   -5, 	  -1,   -1, 	   0,   -5
.2byte    4,  -10, 	  -6,   -8, 	   3,   -3, 	  -2,  -10
.2byte    4,   -8, 	  -5,  -10, 	   3,   -6, 	  -2,   -8
.2byte    3,   -9, 	  -5,   -6, 	   2,   -2, 	  -2,   -8
.2byte    0,   -9, 	   6,   -6, 	  -5,   -6, 	   0,   -8
.2byte   -1,   -8, 	   6,   -8, 	  -5,   -8, 	   0,   -7
.2byte    2,   -8, 	   6,   -4, 	  -5,   -4, 	   1,   -7
.2byte   -5,  -10, 	   5,   -8, 	  -4,   -3, 	   1,  -10
.2byte   -5,   -8, 	   4,  -10, 	  -4,   -6, 	   1,   -8
.2byte   -4,   -9, 	   4,   -6, 	  -3,   -2, 	   1,   -8
.2byte   -6,   -8, 	  -2,   -7, 	   0,   -3, 	  -1,   -8
.2byte   -6,   -6, 	  -3,   -8, 	   1,   -5, 	  -1,   -7
.2byte   -5,   -7, 	  -3,   -5, 	   0,   -1, 	  -1,   -5
.2byte   -5,   -7, 	  -3,   -7, 	   4,   -4, 	   0,   -7
.2byte   -4,   -6, 	  -3,   -6, 	   5,   -7, 	   0,   -6
.2byte   -5,   -5, 	  -6,   -5, 	   4,   -1, 	  -1,   -5
.2byte   -2,   -8, 	  -7,   -6, 	   6,   -6, 	  -1,   -6
.2byte   -1,   -7, 	  -8,   -8, 	   6,   -8, 	   0,   -5
.2byte   -2,   -6, 	  -7,   -4, 	   5,   -4, 	  -1,   -4
.2byte    4,   -7, 	   2,   -7, 	  -5,   -4, 	  -1,   -7
.2byte    3,   -6, 	   2,   -6, 	  -6,   -7, 	  -1,   -6
.2byte    4,   -5, 	   5,   -5, 	  -5,   -1, 	   0,   -5
.2byte    5,   -8, 	   1,   -7, 	  -1,   -3, 	   0,   -8
.2byte    5,   -6, 	   2,   -8, 	  -2,   -5, 	   0,   -7
.2byte    4,   -7, 	   2,   -5, 	  -1,   -1, 	   0,   -5
.2byte    4,  -10, 	  -6,   -8, 	   3,   -3, 	  -2,  -10
.2byte    4,   -8, 	  -5,  -10, 	   3,   -6, 	  -2,   -8
.2byte    3,   -9, 	  -5,   -6, 	   2,   -2, 	  -2,   -8
.2byte    0,   -9, 	   6,   -6, 	  -5,   -6, 	   0,   -8
.2byte   -1,   -8, 	   6,   -8, 	  -5,   -8, 	   0,   -7
.2byte    2,   -8, 	   6,   -4, 	  -5,   -4, 	   1,   -7
.2byte   -5,  -10, 	   5,   -8, 	  -4,   -3, 	   1,  -10
.2byte   -5,   -8, 	   4,  -10, 	  -4,   -6, 	   1,   -8
.2byte   -4,   -9, 	   4,   -6, 	  -3,   -2, 	   1,   -8
.2byte   -6,   -8, 	  -2,   -7, 	   0,   -3, 	  -1,   -8
.2byte   -6,   -6, 	  -3,   -8, 	   1,   -5, 	  -1,   -7
.2byte   -5,   -7, 	  -3,   -5, 	   0,   -1, 	  -1,   -5
.2byte   -5,   -7, 	  -3,   -7, 	   4,   -4, 	   0,   -7
.2byte   -4,   -6, 	  -3,   -6, 	   5,   -7, 	   0,   -6
.2byte   -5,   -5, 	  -6,   -5, 	   4,   -1, 	  -1,   -5
.2byte   -2,   -8, 	  -7,   -6, 	   6,   -6, 	  -1,   -6
.2byte   -5,  -10, 	  -4,  -18, 	   3,   -5, 	   0,   -8
.2byte   -1,   -4, 	  -5,   -1, 	   4,  -12, 	  -2,   -6
.2byte   -1,   -4, 	  -5,   -1, 	   4,  -12, 	  -2,   -6
.2byte    4,   -7, 	   2,   -7, 	  -5,   -4, 	  -1,   -7
.2byte    6,  -12, 	  -1,  -19, 	   2,   -5, 	  -1,   -9
.2byte    6,   -4, 	   6,   -2, 	  -6,  -10, 	  -1,   -6
.2byte    6,   -4, 	   6,   -2, 	  -6,  -10, 	  -1,   -6
.2byte    5,   -8, 	   1,   -7, 	  -1,   -3, 	   0,   -8
.2byte    6,  -13, 	  -2,  -18, 	   4,   -6, 	  -1,  -10
.2byte    7,   -6, 	   4,   -5, 	  -5,   -6, 	   1,   -7
.2byte    7,   -6, 	   4,   -5, 	  -5,   -6, 	   1,   -7
.2byte    4,  -10, 	  -6,   -8, 	   3,   -3, 	  -2,  -10
.2byte    2,  -13, 	  -7,  -15, 	   3,   -6, 	  -3,   -9
.2byte    5,   -7, 	   1,   -6, 	  -7,   -6, 	  -2,  -10
.2byte    5,   -7, 	   1,   -6, 	  -7,   -6, 	  -2,  -10
.2byte    0,   -9, 	   6,   -6, 	  -5,   -6, 	   0,   -8
.2byte   -1,  -11, 	   5,  -16, 	  -5,   -6, 	   0,   -9
.2byte    0,   -8, 	   1,   -5, 	  -5,   -6, 	   0,   -6
.2byte    0,   -8, 	   1,   -5, 	  -5,   -6, 	   0,   -6
.2byte   -5,  -10, 	   5,   -8, 	  -4,   -3, 	   1,  -10
.2byte   -3,  -13, 	   6,  -15, 	  -4,   -6, 	   2,   -9
.2byte   -6,   -7, 	  -2,   -6, 	   6,   -6, 	   1,  -10
.2byte   -6,   -7, 	  -2,   -6, 	   6,   -6, 	   1,  -10
.2byte   -6,   -8, 	  -2,   -7, 	   0,   -3, 	  -1,   -8
.2byte   -7,  -13, 	   1,  -18, 	  -5,   -6, 	   0,  -10
.2byte   -8,   -6, 	  -5,   -5, 	   4,   -6, 	  -2,   -7
.2byte   -8,   -6, 	  -5,   -5, 	   4,   -6, 	  -2,   -7
.2byte   -5,   -7, 	  -3,   -7, 	   4,   -4, 	   0,   -7
.2byte   -7,  -12, 	   0,  -19, 	  -3,   -5, 	   0,   -9
.2byte   -7,   -4, 	  -7,   -2, 	   5,  -10, 	   0,   -6
.2byte   -7,   -4, 	  -7,   -2, 	   5,  -10, 	   0,   -6
.2byte   -2,   -8, 	  -7,   -6, 	   6,   -6, 	  -1,   -6
.2byte   -1,   -7, 	  -8,   -8, 	   6,   -8, 	   0,   -5
.2byte   -2,   -6, 	  -7,   -4, 	   5,   -4, 	  -1,   -4
.2byte   -2,  -12, 	  -8,   -9, 	   6,   -9, 	  -1,  -10
.2byte   -1,  -12, 	  -7,   -5, 	   5,   -5, 	  -1,   -9
.2byte    4,   -7, 	   2,   -7, 	  -5,   -4, 	  -1,   -7
.2byte    3,   -6, 	   2,   -6, 	  -6,   -7, 	  -1,   -6
.2byte    4,   -5, 	   5,   -5, 	  -5,   -1, 	   0,   -5
.2byte    6,  -13, 	   3,   -9, 	  -6,   -9, 	   0,   -9
.2byte    6,  -14, 	   3,   -8, 	  -6,   -5, 	   0,  -10
.2byte    5,   -8, 	   1,   -7, 	  -1,   -3, 	   0,   -8
.2byte    5,   -6, 	   2,   -8, 	  -2,   -5, 	   0,   -7
.2byte    4,   -7, 	   2,   -5, 	  -1,   -1, 	   0,   -5
.2byte   11,  -17, 	   4,  -10, 	  -8,   -7, 	  -1,  -11
.2byte   11,  -18, 	   0,   -8, 	  -7,   -3, 	  -2,  -11
.2byte    4,  -10, 	  -6,   -8, 	   3,   -3, 	  -2,  -10
.2byte    4,   -8, 	  -5,  -10, 	   3,   -6, 	  -2,   -8
.2byte    3,   -9, 	  -5,   -6, 	   2,   -2, 	  -2,   -8
.2byte   10,  -17, 	  -4,   -8, 	   5,   -6, 	  -1,   -9
.2byte   11,  -17, 	  -4,   -6, 	   5,   -1, 	  -1,   -9
.2byte    0,   -9, 	   6,   -6, 	  -5,   -6, 	   0,   -8
.2byte   -1,   -8, 	   6,   -8, 	  -5,   -8, 	   0,   -7
.2byte    2,   -8, 	   6,   -4, 	  -5,   -4, 	   1,   -7
.2byte    1,  -14, 	   7,   -8, 	  -7,   -8, 	   0,   -9
.2byte    1,  -16, 	   6,   -4, 	  -6,   -4, 	   0,   -9
.2byte   -5,  -10, 	   5,   -8, 	  -4,   -3, 	   1,  -10
.2byte   -5,   -8, 	   4,  -10, 	  -4,   -6, 	   1,   -8
.2byte   -4,   -9, 	   4,   -6, 	  -3,   -2, 	   1,   -8
.2byte  -11,  -17, 	   3,   -8, 	  -6,   -6, 	   0,   -9
.2byte  -12,  -17, 	   3,   -6, 	  -6,   -1, 	   0,   -9
.2byte   -6,   -8, 	  -2,   -7, 	   0,   -3, 	  -1,   -8
.2byte   -6,   -6, 	  -3,   -8, 	   1,   -5, 	  -1,   -7
.2byte   -5,   -7, 	  -3,   -5, 	   0,   -1, 	  -1,   -5
.2byte  -12,  -17, 	  -5,  -10, 	   7,   -7, 	   0,  -11
.2byte  -12,  -18, 	  -1,   -8, 	   6,   -3, 	   1,  -11
.2byte   -5,   -7, 	  -3,   -7, 	   4,   -4, 	   0,   -7
.2byte   -4,   -6, 	  -3,   -6, 	   5,   -7, 	   0,   -6
.2byte   -5,   -5, 	  -6,   -5, 	   4,   -1, 	  -1,   -5
.2byte   -7,  -13, 	  -4,   -9, 	   5,   -9, 	  -1,   -9
.2byte   -7,  -14, 	  -4,   -8, 	   5,   -5, 	  -1,  -10
.2byte   -2,   -8, 	  -7,   -6, 	   6,   -6, 	  -1,   -6
.2byte   -5,   -7, 	  -3,   -7, 	   4,   -4, 	   0,   -7
.2byte   -6,   -8, 	  -2,   -7, 	   0,   -3, 	  -1,   -8
.2byte   -5,  -10, 	   5,   -8, 	  -4,   -3, 	   1,  -10
.2byte    0,   -9, 	   6,   -6, 	  -5,   -6, 	   0,   -8
.2byte    4,  -10, 	  -6,   -8, 	   3,   -3, 	  -2,  -10
.2byte    5,   -8, 	   1,   -7, 	  -1,   -3, 	   0,   -8
.2byte    4,   -7, 	   2,   -7, 	  -5,   -4, 	  -1,   -7
.2byte   -5,   -5, 	  -4,   -4, 	   4,   -3, 	  -1,   -6
.2byte   -5,   -6, 	  -4,   -5, 	   4,   -4, 	  -1,   -6
.2byte    0,   -7, 	  -8,   -7, 	   6,   -8, 	   0,   -4
.2byte   -1,   -8, 	  -3,  -11, 	 -10,   -8, 	  -4,   -7
.2byte    0,   -9, 	  -5,  -10, 	  -7,   -8, 	  -3,   -6
.2byte    2,  -10, 	  -7,  -10, 	  -7,   -7, 	  -3,   -7
.2byte    0,   -9, 	   7,   -8, 	  -7,   -9, 	  -1,   -7
.2byte   -3,  -10, 	   6,  -10, 	   6,   -7, 	   2,   -7
.2byte   -1,   -9, 	   4,  -10, 	   6,   -8, 	   2,   -6
.2byte    0,   -8, 	   2,  -11, 	   9,   -8, 	   3,   -7
.2byte   -2,   -8, 	  -7,   -6, 	   6,   -6, 	  -1,   -6
.2byte   -1,   -7, 	  -8,   -8, 	   6,   -8, 	   0,   -5
.2byte   -2,   -6, 	  -7,   -4, 	   5,   -4, 	  -1,   -4
.2byte    4,   -7, 	   2,   -7, 	  -5,   -4, 	  -1,   -7
.2byte    3,   -6, 	   2,   -6, 	  -6,   -7, 	  -1,   -6
.2byte    4,   -5, 	   5,   -5, 	  -5,   -1, 	   0,   -5
.2byte    5,   -8, 	   1,   -7, 	  -1,   -3, 	   0,   -8
.2byte    5,   -6, 	   2,   -8, 	  -2,   -5, 	   0,   -7
.2byte    4,   -7, 	   2,   -5, 	  -1,   -1, 	   0,   -5
.2byte    4,  -10, 	  -6,   -8, 	   3,   -3, 	  -2,  -10
.2byte    4,   -8, 	  -5,  -10, 	   3,   -6, 	  -2,   -8
.2byte    3,   -9, 	  -5,   -6, 	   2,   -2, 	  -2,   -8
.2byte    0,   -9, 	   6,   -6, 	  -5,   -6, 	   0,   -8
.2byte   -1,   -8, 	   6,   -8, 	  -5,   -8, 	   0,   -7
.2byte    2,   -8, 	   6,   -4, 	  -5,   -4, 	   1,   -7
.2byte   -5,  -10, 	   5,   -8, 	  -4,   -3, 	   1,  -10
.2byte   -5,   -8, 	   4,  -10, 	  -4,   -6, 	   1,   -8
.2byte   -4,   -9, 	   4,   -6, 	  -3,   -2, 	   1,   -8
.2byte   -6,   -8, 	  -2,   -7, 	   0,   -3, 	  -1,   -8
.2byte   -6,   -6, 	  -3,   -8, 	   1,   -5, 	  -1,   -7
.2byte   -5,   -7, 	  -3,   -5, 	   0,   -1, 	  -1,   -5
.2byte   -5,   -7, 	  -3,   -7, 	   4,   -4, 	   0,   -7
.2byte   -4,   -6, 	  -3,   -6, 	   5,   -7, 	   0,   -6
.2byte   -5,   -5, 	  -6,   -5, 	   4,   -1, 	  -1,   -5
.2byte   -2,  -12, 	  -8,   -9, 	   6,   -9, 	  -1,  -10
.2byte   -7,  -13, 	  -4,   -9, 	   5,   -9, 	  -1,   -9
.2byte  -12,  -17, 	  -5,  -10, 	   7,   -7, 	   0,  -11
.2byte   -9,  -18, 	   5,   -9, 	  -4,   -7, 	   2,  -10
.2byte    1,  -14, 	   7,   -8, 	  -7,   -8, 	   0,   -9
.2byte    8,  -18, 	  -6,   -9, 	   3,   -7, 	  -3,  -10
.2byte   11,  -17, 	   4,  -10, 	  -8,   -7, 	  -1,  -11
.2byte    6,  -13, 	   3,   -9, 	  -6,   -9, 	   0,   -9
.2byte   -2,  -12, 	  -8,   -9, 	   6,   -9, 	  -1,  -10
.2byte    6,  -13, 	   3,   -9, 	  -6,   -9, 	   0,   -9
.2byte   11,  -17, 	   4,  -10, 	  -8,   -7, 	  -1,  -11
.2byte    8,  -18, 	  -6,   -9, 	   3,   -7, 	  -3,  -10
.2byte    1,  -14, 	   7,   -8, 	  -7,   -8, 	   0,   -9
.2byte   -9,  -18, 	   5,   -9, 	  -4,   -7, 	   2,  -10
.2byte  -12,  -17, 	  -5,  -10, 	   7,   -7, 	   0,  -11
.2byte   -7,  -13, 	  -4,   -9, 	   5,   -9, 	  -1,   -9
.2byte   -2,   -8, 	  -7,   -6, 	   6,   -6, 	  -1,   -6
.2byte   -2,  -12, 	  -8,   -9, 	   6,   -9, 	  -1,  -10
.2byte   -1,  -12, 	  -7,   -5, 	   5,   -5, 	  -1,   -9
.2byte    4,   -7, 	   2,   -7, 	  -5,   -4, 	  -1,   -7
.2byte    6,  -13, 	   3,   -9, 	  -6,   -9, 	   0,   -9
.2byte    5,  -14, 	   2,   -8, 	  -7,   -5, 	  -1,  -10
.2byte    5,   -8, 	   1,   -7, 	  -1,   -3, 	   0,   -8
.2byte   11,  -17, 	   4,  -10, 	  -8,   -7, 	  -1,  -11
.2byte   11,  -17, 	   0,   -7, 	  -7,   -2, 	  -2,  -10
.2byte    4,  -10, 	  -6,   -8, 	   3,   -3, 	  -2,  -10
.2byte    8,  -18, 	  -6,   -9, 	   3,   -7, 	  -3,  -10
.2byte    9,  -18, 	  -6,   -7, 	   3,   -2, 	  -3,  -10
.2byte    0,   -9, 	   6,   -6, 	  -5,   -6, 	   0,   -8
.2byte    1,  -14, 	   7,   -8, 	  -7,   -8, 	   0,   -9
.2byte    1,  -16, 	   6,   -4, 	  -6,   -4, 	   0,   -9
.2byte   -5,  -10, 	   5,   -8, 	  -4,   -3, 	   1,  -10
.2byte   -9,  -18, 	   5,   -9, 	  -4,   -7, 	   2,  -10
.2byte  -10,  -18, 	   5,   -7, 	  -4,   -2, 	   2,  -10
.2byte   -6,   -8, 	  -2,   -7, 	   0,   -3, 	  -1,   -8
.2byte  -12,  -17, 	  -5,  -10, 	   7,   -7, 	   0,  -11
.2byte  -12,  -17, 	  -1,   -7, 	   6,   -2, 	   1,  -10
.2byte   -5,   -7, 	  -3,   -7, 	   4,   -4, 	   0,   -7
.2byte   -7,  -13, 	  -4,   -9, 	   5,   -9, 	  -1,   -9
.2byte   -6,  -14, 	  -3,   -8, 	   6,   -5, 	   0,  -10
.2byte   -2,  -12, 	  -8,   -9, 	   6,   -9, 	  -1,  -10
.2byte   -7,  -13, 	  -4,   -9, 	   5,   -9, 	  -1,   -9
.2byte  -12,  -17, 	  -5,  -10, 	   7,   -7, 	   0,  -11
.2byte   -9,  -18, 	   5,   -9, 	  -4,   -7, 	   2,  -10
.2byte    1,  -14, 	   7,   -8, 	  -7,   -8, 	   0,   -9
.2byte    8,  -18, 	  -6,   -9, 	   3,   -7, 	  -3,  -10
.2byte   11,  -17, 	   4,  -10, 	  -8,   -7, 	  -1,  -11
.2byte    6,  -13, 	   3,   -9, 	  -6,   -9, 	   0,   -9
.2byte   -2,   -8, 	  -7,   -6, 	   6,   -6, 	  -1,   -6
.2byte   -5,   -7, 	  -3,   -7, 	   4,   -4, 	   0,   -7
.2byte   -6,   -8, 	  -2,   -7, 	   0,   -3, 	  -1,   -8
.2byte   -5,  -10, 	   5,   -8, 	  -4,   -3, 	   1,  -10
.2byte    0,   -9, 	   6,   -6, 	  -5,   -6, 	   0,   -8
.2byte    4,  -10, 	  -6,   -8, 	   3,   -3, 	  -2,  -10
.2byte    5,   -8, 	   1,   -7, 	  -1,   -3, 	   0,   -8
.2byte    4,   -7, 	   2,   -7, 	  -5,   -4, 	  -1,   -7
sBellsproutAnimTable1:
.4byte sBellsproutAnims_1_1
.4byte sBellsproutAnims_1_2
.4byte sBellsproutAnims_1_3
.4byte sBellsproutAnims_1_4
.4byte sBellsproutAnims_1_5
.4byte sBellsproutAnims_1_6
.4byte sBellsproutAnims_1_7
.4byte sBellsproutAnims_1_8
sBellsproutAnimTable2:
.4byte sBellsproutAnims_2_1
.4byte sBellsproutAnims_2_2
.4byte sBellsproutAnims_2_3
.4byte sBellsproutAnims_2_4
.4byte sBellsproutAnims_2_5
.4byte sBellsproutAnims_2_6
.4byte sBellsproutAnims_2_7
.4byte sBellsproutAnims_2_8
sBellsproutAnimTable3:
.4byte sBellsproutAnims_3_1
.4byte sBellsproutAnims_3_2
.4byte sBellsproutAnims_3_3
.4byte sBellsproutAnims_3_4
.4byte sBellsproutAnims_3_5
.4byte sBellsproutAnims_3_6
.4byte sBellsproutAnims_3_7
.4byte sBellsproutAnims_3_8
sBellsproutAnimTable4:
.4byte sBellsproutAnims_4_1
.4byte sBellsproutAnims_4_2
.4byte sBellsproutAnims_4_3
.4byte sBellsproutAnims_4_4
.4byte sBellsproutAnims_4_5
.4byte sBellsproutAnims_4_6
.4byte sBellsproutAnims_4_7
.4byte sBellsproutAnims_4_8
sBellsproutAnimTable5:
.4byte sBellsproutAnims_5_1
.4byte sBellsproutAnims_5_2
.4byte sBellsproutAnims_5_3
.4byte sBellsproutAnims_5_4
.4byte sBellsproutAnims_5_5
.4byte sBellsproutAnims_5_6
.4byte sBellsproutAnims_5_7
.4byte sBellsproutAnims_5_8
sBellsproutAnimTable6:
.4byte sBellsproutAnims_6_1
.4byte sBellsproutAnims_6_1
.4byte sBellsproutAnims_6_1
.4byte sBellsproutAnims_6_1
.4byte sBellsproutAnims_6_1
.4byte sBellsproutAnims_6_1
.4byte sBellsproutAnims_6_1
.4byte sBellsproutAnims_6_1
sBellsproutAnimTable7:
.4byte sBellsproutAnims_7_1
.4byte sBellsproutAnims_7_2
.4byte sBellsproutAnims_7_3
.4byte sBellsproutAnims_7_4
.4byte sBellsproutAnims_7_5
.4byte sBellsproutAnims_7_6
.4byte sBellsproutAnims_7_7
.4byte sBellsproutAnims_7_8
sBellsproutAnimTable8:
.4byte sBellsproutAnims_8_1
.4byte sBellsproutAnims_8_2
.4byte sBellsproutAnims_8_3
.4byte sBellsproutAnims_8_4
.4byte sBellsproutAnims_8_5
.4byte sBellsproutAnims_8_6
.4byte sBellsproutAnims_8_7
.4byte sBellsproutAnims_8_8
sBellsproutAnimTable9:
.4byte sBellsproutAnims_9_1
.4byte sBellsproutAnims_9_2
.4byte sBellsproutAnims_9_3
.4byte sBellsproutAnims_9_4
.4byte sBellsproutAnims_9_5
.4byte sBellsproutAnims_9_6
.4byte sBellsproutAnims_9_7
.4byte sBellsproutAnims_9_8
sBellsproutAnimTable10:
.4byte sBellsproutAnims_10_1
.4byte sBellsproutAnims_10_2
.4byte sBellsproutAnims_10_3
.4byte sBellsproutAnims_10_4
.4byte sBellsproutAnims_10_5
.4byte sBellsproutAnims_10_6
.4byte sBellsproutAnims_10_7
.4byte sBellsproutAnims_10_8
sBellsproutAnimTable11:
.4byte sBellsproutAnims_11_1
.4byte sBellsproutAnims_11_2
.4byte sBellsproutAnims_11_3
.4byte sBellsproutAnims_11_4
.4byte sBellsproutAnims_11_5
.4byte sBellsproutAnims_11_6
.4byte sBellsproutAnims_11_7
.4byte sBellsproutAnims_11_8
sBellsproutAnimTable12:
.4byte sBellsproutAnims_12_1
.4byte sBellsproutAnims_12_2
.4byte sBellsproutAnims_12_3
.4byte sBellsproutAnims_12_4
.4byte sBellsproutAnims_12_5
.4byte sBellsproutAnims_12_6
.4byte sBellsproutAnims_12_7
.4byte sBellsproutAnims_12_8
sBellsproutAnimTable13:
.4byte sBellsproutAnims_13_1
.4byte sBellsproutAnims_13_2
.4byte sBellsproutAnims_13_3
.4byte sBellsproutAnims_13_4
.4byte sBellsproutAnims_13_5
.4byte sBellsproutAnims_13_6
.4byte sBellsproutAnims_13_7
.4byte sBellsproutAnims_13_8
sAxAnimationsBellsprout:
.4byte sBellsproutAnimTable1
.4byte sBellsproutAnimTable2
.4byte sBellsproutAnimTable3
.4byte sBellsproutAnimTable4
.4byte sBellsproutAnimTable5
.4byte sBellsproutAnimTable6
.4byte sBellsproutAnimTable7
.4byte sBellsproutAnimTable8
.4byte sBellsproutAnimTable9
.4byte sBellsproutAnimTable10
.4byte sBellsproutAnimTable11
.4byte sBellsproutAnimTable12
.4byte sBellsproutAnimTable13
sAxSpritesBellsprout:
.4byte sBellsproutSprites1
.4byte sBellsproutSprites2
.4byte sBellsproutSprites3
.4byte sBellsproutSprites4
.4byte sBellsproutSprites5
.4byte sBellsproutSprites6
.4byte sBellsproutSprites7
.4byte sBellsproutSprites8
.4byte sBellsproutSprites9
.4byte sBellsproutSprites10
.4byte sBellsproutSprites11
.4byte sBellsproutSprites12
.4byte sBellsproutSprites13
.4byte sBellsproutSprites14
.4byte sBellsproutSprites15
.4byte sBellsproutSprites16
.4byte sBellsproutSprites17
.4byte sBellsproutSprites18
.4byte sBellsproutSprites19
.4byte sBellsproutSprites20
.4byte sBellsproutSprites21
.4byte sBellsproutSprites22
.4byte sBellsproutSprites23
.4byte sBellsproutSprites24
.4byte sBellsproutSprites25
.4byte sBellsproutSprites26
.4byte sBellsproutSprites27
.4byte sBellsproutSprites28
.4byte sBellsproutSprites29
.4byte sBellsproutSprites30
.4byte sBellsproutSprites31
.4byte sBellsproutSprites32
.4byte sBellsproutSprites33
.4byte sBellsproutSprites34
.4byte sBellsproutSprites35
.4byte sBellsproutSprites36
.4byte sBellsproutSprites37
.4byte sBellsproutSprites38
.4byte sBellsproutSprites39
.4byte sBellsproutSprites40
.4byte sBellsproutSprites41
.4byte sBellsproutSprites42
.4byte sBellsproutSprites43
.4byte sBellsproutSprites44
.4byte sBellsproutSprites45
.4byte sBellsproutSprites46
.4byte sBellsproutSprites47
sAxMainBellsprout:
ax_main sAxPosesBellsprout, sAxAnimationsBellsprout, 13, sAxSpritesBellsprout, sAxPositionsBellsprout
