.global gAxCacnea
gAxCacnea:
ax_siro sAxMainCacnea
sCacneaPose1:
ax_pose 0, 0x01ed, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose2:
ax_pose 1, 0x01ed, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose3:
ax_pose 2, 0x01ed, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose4:
ax_pose 3, 0x01ef, 0x90ef, 0x3c00
ax_pose_terminator
sCacneaPose5:
ax_pose 4, 0x01ef, 0x90ef, 0x3c00
ax_pose_terminator
sCacneaPose6:
ax_pose 5, 0x01ef, 0x90ef, 0x3c00
ax_pose_terminator
sCacneaPose7:
ax_pose 6, 0x01ee, 0x90ef, 0x3c00
ax_pose_terminator
sCacneaPose8:
ax_pose 7, 0x01ee, 0x90ef, 0x3c00
ax_pose_terminator
sCacneaPose9:
ax_pose 8, 0x01ee, 0x90ef, 0x3c00
ax_pose_terminator
sCacneaPose10:
ax_pose 9, 0x01ed, 0x90ef, 0x3c00
ax_pose_terminator
sCacneaPose11:
ax_pose 10, 0x01ed, 0x90ef, 0x3c00
ax_pose_terminator
sCacneaPose12:
ax_pose 11, 0x01ed, 0x90ef, 0x3c00
ax_pose_terminator
sCacneaPose13:
ax_pose 12, 0x01ed, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose14:
ax_pose 13, 0x01ed, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose15:
ax_pose 14, 0x01ed, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose16:
ax_pose 9, 0x01ed, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose17:
ax_pose 10, 0x01ed, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose18:
ax_pose 11, 0x01ed, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose19:
ax_pose 6, 0x01ee, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose20:
ax_pose 7, 0x01ee, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose21:
ax_pose 8, 0x01ee, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose22:
ax_pose 3, 0x01ef, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose23:
ax_pose 4, 0x01ef, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose24:
ax_pose 5, 0x01ef, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose25:
ax_pose 0, 0x01ed, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose26:
ax_pose 1, 0x01ed, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose27:
ax_pose 2, 0x01ed, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose28:
ax_pose 15, 0x01ed, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose29:
ax_pose 3, 0x01ef, 0x90ef, 0x3c00
ax_pose_terminator
sCacneaPose30:
ax_pose 4, 0x01ef, 0x90ef, 0x3c00
ax_pose_terminator
sCacneaPose31:
ax_pose 5, 0x01ef, 0x90ef, 0x3c00
ax_pose_terminator
sCacneaPose32:
ax_pose 16, 0x01ee, 0x90ef, 0x3c00
ax_pose_terminator
sCacneaPose33:
ax_pose 17, 0x01ef, 0x90ef, 0x3c00
ax_pose_terminator
sCacneaPose34:
ax_pose 18, 0x01ee, 0x90f1, 0x3c00
ax_pose_terminator
sCacneaPose35:
ax_pose 6, 0x01ee, 0x90ef, 0x3c00
ax_pose_terminator
sCacneaPose36:
ax_pose 7, 0x01ee, 0x90ef, 0x3c00
ax_pose_terminator
sCacneaPose37:
ax_pose 8, 0x01ee, 0x90ef, 0x3c00
ax_pose_terminator
sCacneaPose38:
ax_pose 19, 0x01ee, 0x90ef, 0x3c00
ax_pose_terminator
sCacneaPose39:
ax_pose 20, 0x01ee, 0x90ef, 0x3c00
ax_pose_terminator
sCacneaPose40:
ax_pose 21, 0x01ee, 0x90ef, 0x3c00
ax_pose_terminator
sCacneaPose41:
ax_pose 9, 0x01ed, 0x90ef, 0x3c00
ax_pose_terminator
sCacneaPose42:
ax_pose 10, 0x01ed, 0x90ef, 0x3c00
ax_pose_terminator
sCacneaPose43:
ax_pose 11, 0x01ed, 0x90ef, 0x3c00
ax_pose_terminator
sCacneaPose44:
ax_pose 22, 0x01ed, 0x90ef, 0x3c00
ax_pose_terminator
sCacneaPose45:
ax_pose 23, 0x01ed, 0x90ef, 0x3c00
ax_pose_terminator
sCacneaPose46:
ax_pose 24, 0x01ed, 0x90f0, 0x3c00
ax_pose_terminator
sCacneaPose47:
ax_pose 12, 0x01ed, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose48:
ax_pose 13, 0x01ed, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose49:
ax_pose 14, 0x01ed, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose50:
ax_pose 25, 0x01ed, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose51:
ax_pose 26, 0x01ed, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose52:
ax_pose 27, 0x01ed, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose53:
ax_pose 9, 0x01ed, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose54:
ax_pose 10, 0x01ed, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose55:
ax_pose 11, 0x01ed, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose56:
ax_pose 22, 0x01ed, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose57:
ax_pose 23, 0x01ed, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose58:
ax_pose 24, 0x01ed, 0x80ef, 0x3c00
ax_pose_terminator
sCacneaPose59:
ax_pose 6, 0x01ee, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose60:
ax_pose 7, 0x01ee, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose61:
ax_pose 8, 0x01ee, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose62:
ax_pose 19, 0x01ee, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose63:
ax_pose 20, 0x01ee, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose64:
ax_pose 21, 0x01ee, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose65:
ax_pose 3, 0x01ef, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose66:
ax_pose 4, 0x01ef, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose67:
ax_pose 5, 0x01ef, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose68:
ax_pose 16, 0x01ee, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose69:
ax_pose 17, 0x01ef, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose70:
ax_pose 18, 0x01ee, 0x80ee, 0x3c00
ax_pose_terminator
sCacneaPose71:
ax_pose 0, 0x01ed, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose72:
ax_pose 1, 0x01ed, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose73:
ax_pose 2, 0x01ed, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose74:
ax_pose 15, 0x01ed, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose75:
ax_pose 3, 0x01ef, 0x90ef, 0x3c00
ax_pose_terminator
sCacneaPose76:
ax_pose 4, 0x01ef, 0x90ef, 0x3c00
ax_pose_terminator
sCacneaPose77:
ax_pose 5, 0x01ef, 0x90ef, 0x3c00
ax_pose_terminator
sCacneaPose78:
ax_pose 16, 0x01ee, 0x90ef, 0x3c00
ax_pose_terminator
sCacneaPose79:
ax_pose 17, 0x01ef, 0x90ef, 0x3c00
ax_pose_terminator
sCacneaPose80:
ax_pose 18, 0x01ee, 0x90f1, 0x3c00
ax_pose_terminator
sCacneaPose81:
ax_pose 6, 0x01ee, 0x90ef, 0x3c00
ax_pose_terminator
sCacneaPose82:
ax_pose 7, 0x01ee, 0x90ef, 0x3c00
ax_pose_terminator
sCacneaPose83:
ax_pose 8, 0x01ee, 0x90ef, 0x3c00
ax_pose_terminator
sCacneaPose84:
ax_pose 19, 0x01ee, 0x90ef, 0x3c00
ax_pose_terminator
sCacneaPose85:
ax_pose 20, 0x01ee, 0x90ef, 0x3c00
ax_pose_terminator
sCacneaPose86:
ax_pose 21, 0x01ee, 0x90ef, 0x3c00
ax_pose_terminator
sCacneaPose87:
ax_pose 9, 0x01ed, 0x90ef, 0x3c00
ax_pose_terminator
sCacneaPose88:
ax_pose 10, 0x01ed, 0x90ef, 0x3c00
ax_pose_terminator
sCacneaPose89:
ax_pose 11, 0x01ed, 0x90ef, 0x3c00
ax_pose_terminator
sCacneaPose90:
ax_pose 22, 0x01ed, 0x90ef, 0x3c00
ax_pose_terminator
sCacneaPose91:
ax_pose 23, 0x01ed, 0x90ef, 0x3c00
ax_pose_terminator
sCacneaPose92:
ax_pose 24, 0x01ed, 0x90f0, 0x3c00
ax_pose_terminator
sCacneaPose93:
ax_pose 12, 0x01ed, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose94:
ax_pose 13, 0x01ed, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose95:
ax_pose 14, 0x01ed, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose96:
ax_pose 25, 0x01ed, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose97:
ax_pose 26, 0x01ed, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose98:
ax_pose 27, 0x01ed, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose99:
ax_pose 9, 0x01ed, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose100:
ax_pose 10, 0x01ed, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose101:
ax_pose 11, 0x01ed, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose102:
ax_pose 22, 0x01ed, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose103:
ax_pose 23, 0x01ed, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose104:
ax_pose 24, 0x01ed, 0x80ef, 0x3c00
ax_pose_terminator
sCacneaPose105:
ax_pose 6, 0x01ee, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose106:
ax_pose 7, 0x01ee, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose107:
ax_pose 8, 0x01ee, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose108:
ax_pose 19, 0x01ee, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose109:
ax_pose 20, 0x01ee, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose110:
ax_pose 21, 0x01ee, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose111:
ax_pose 3, 0x01ef, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose112:
ax_pose 4, 0x01ef, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose113:
ax_pose 5, 0x01ef, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose114:
ax_pose 16, 0x01ee, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose115:
ax_pose 17, 0x01ef, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose116:
ax_pose 18, 0x01ee, 0x80ee, 0x3c00
ax_pose_terminator
sCacneaPose117:
ax_pose 0, 0x01ed, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose118:
ax_pose 15, 0x01ed, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose119:
ax_pose 28, 0x01ed, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose120:
ax_pose 3, 0x01ef, 0x90ef, 0x3c00
ax_pose_terminator
sCacneaPose121:
ax_pose 16, 0x01ee, 0x90ef, 0x3c00
ax_pose_terminator
sCacneaPose122:
ax_pose 17, 0x01ef, 0x90ef, 0x3c00
ax_pose_terminator
sCacneaPose123:
ax_pose 6, 0x01ee, 0x90ef, 0x3c00
ax_pose_terminator
sCacneaPose124:
ax_pose 19, 0x01ee, 0x90ef, 0x3c00
ax_pose_terminator
sCacneaPose125:
ax_pose 20, 0x01ee, 0x90ef, 0x3c00
ax_pose_terminator
sCacneaPose126:
ax_pose 9, 0x01ed, 0x90ef, 0x3c00
ax_pose_terminator
sCacneaPose127:
ax_pose 22, 0x01ed, 0x90ef, 0x3c00
ax_pose_terminator
sCacneaPose128:
ax_pose 23, 0x01ed, 0x90ef, 0x3c00
ax_pose_terminator
sCacneaPose129:
ax_pose 12, 0x01ed, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose130:
ax_pose 25, 0x01ed, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose131:
ax_pose 26, 0x01ed, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose132:
ax_pose 9, 0x01ed, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose133:
ax_pose 22, 0x01ed, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose134:
ax_pose 23, 0x01ed, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose135:
ax_pose 6, 0x01ee, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose136:
ax_pose 19, 0x01ee, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose137:
ax_pose 20, 0x01ee, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose138:
ax_pose 3, 0x01ef, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose139:
ax_pose 16, 0x01ee, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose140:
ax_pose 17, 0x01ef, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose141:
ax_pose 0, 0x01ed, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose142:
ax_pose 15, 0x01ed, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose143:
ax_pose 28, 0x01ed, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose144:
ax_pose 29, 0x01eb, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose145:
ax_pose 30, 0x01f4, 0x40f4, 0x3c00
ax_pose -1, 0x01f4, 0x40fc, 0x3c00
ax_pose 29, 0x01eb, 0x80f0, 0x3c04
ax_pose_terminator
sCacneaPose146:
ax_pose 31, 0x01f4, 0x40f4, 0x3c00
ax_pose -1, 0x01f4, 0x40fc, 0x3c00
ax_pose 29, 0x01eb, 0x80f0, 0x3c04
ax_pose_terminator
sCacneaPose147:
ax_pose 32, 0x01f4, 0x40f4, 0x3c00
ax_pose -1, 0x01f4, 0x40fc, 0x3c00
ax_pose 29, 0x01eb, 0x80f0, 0x3c04
ax_pose_terminator
sCacneaPose148:
ax_pose 33, 0x01f4, 0x40f4, 0x3c00
ax_pose -1, 0x01f4, 0x40fc, 0x3c00
ax_pose 29, 0x01eb, 0x80f0, 0x3c04
ax_pose_terminator
sCacneaPose149:
ax_pose 34, 0x01f4, 0x40f4, 0x3c00
ax_pose -1, 0x01f4, 0x40fc, 0x3c00
ax_pose 29, 0x01eb, 0x80f0, 0x3c04
ax_pose_terminator
sCacneaPose150:
ax_pose 35, 0x01f4, 0x40f4, 0x3c00
ax_pose -1, 0x01f4, 0x40fc, 0x3c00
ax_pose 29, 0x01eb, 0x80f0, 0x3c04
ax_pose_terminator
sCacneaPose151:
ax_pose 3, 0x01ef, 0x90ef, 0x3c00
ax_pose_terminator
sCacneaPose152:
ax_pose 16, 0x01ee, 0x90ef, 0x3c00
ax_pose_terminator
sCacneaPose153:
ax_pose 17, 0x01ef, 0x90ef, 0x3c00
ax_pose_terminator
sCacneaPose154:
ax_pose 18, 0x01ed, 0x90f1, 0x3c00
ax_pose_terminator
sCacneaPose155:
ax_pose 30, 0x01f1, 0x4101, 0x3c00
ax_pose -1, 0x01f5, 0x40fb, 0x3c00
ax_pose 18, 0x01ed, 0x90f1, 0x3c04
ax_pose_terminator
sCacneaPose156:
ax_pose 31, 0x01f1, 0x4101, 0x3c00
ax_pose -1, 0x01f5, 0x40fb, 0x3c00
ax_pose 18, 0x01ed, 0x90f1, 0x3c04
ax_pose_terminator
sCacneaPose157:
ax_pose 32, 0x01f1, 0x4101, 0x3c00
ax_pose -1, 0x01f5, 0x40fb, 0x3c00
ax_pose 18, 0x01ed, 0x90f1, 0x3c04
ax_pose_terminator
sCacneaPose158:
ax_pose 33, 0x01f1, 0x4101, 0x3c00
ax_pose -1, 0x01f5, 0x40fb, 0x3c00
ax_pose 18, 0x01ed, 0x90f1, 0x3c04
ax_pose_terminator
sCacneaPose159:
ax_pose 34, 0x01f1, 0x4101, 0x3c00
ax_pose -1, 0x01f5, 0x40fb, 0x3c00
ax_pose 18, 0x01ed, 0x90f1, 0x3c04
ax_pose_terminator
sCacneaPose160:
ax_pose 35, 0x01f1, 0x4101, 0x3c00
ax_pose -1, 0x01f5, 0x40fb, 0x3c00
ax_pose 18, 0x01ed, 0x90f1, 0x3c04
ax_pose_terminator
sCacneaPose161:
ax_pose 6, 0x01ee, 0x90ef, 0x3c00
ax_pose_terminator
sCacneaPose162:
ax_pose 19, 0x01ee, 0x90ef, 0x3c00
ax_pose_terminator
sCacneaPose163:
ax_pose 20, 0x01ee, 0x90ef, 0x3c00
ax_pose_terminator
sCacneaPose164:
ax_pose 21, 0x01ec, 0x90ef, 0x3c00
ax_pose_terminator
sCacneaPose165:
ax_pose 36, 0x01f4, 0x50ff, 0x3c00
ax_pose 30, 0x01ee, 0x4101, 0x3c04
ax_pose -1, 0x01eb, 0x4103, 0x3c04
ax_pose 21, 0x01ec, 0x90ef, 0x3c08
ax_pose_terminator
sCacneaPose166:
ax_pose 36, 0x01f4, 0x50ff, 0x3c00
ax_pose 31, 0x01ee, 0x4101, 0x3c04
ax_pose -1, 0x01eb, 0x4103, 0x3c04
ax_pose 21, 0x01ec, 0x90ef, 0x3c08
ax_pose_terminator
sCacneaPose167:
ax_pose 36, 0x01f4, 0x50ff, 0x3c00
ax_pose 32, 0x01ee, 0x4101, 0x3c04
ax_pose -1, 0x01eb, 0x4103, 0x3c04
ax_pose 21, 0x01ec, 0x90ef, 0x3c08
ax_pose_terminator
sCacneaPose168:
ax_pose 36, 0x01f4, 0x50ff, 0x3c00
ax_pose 33, 0x01ee, 0x4101, 0x3c04
ax_pose -1, 0x01eb, 0x4103, 0x3c04
ax_pose 21, 0x01ec, 0x90ef, 0x3c08
ax_pose_terminator
sCacneaPose169:
ax_pose 36, 0x01f4, 0x50ff, 0x3c00
ax_pose 34, 0x01ee, 0x4101, 0x3c04
ax_pose -1, 0x01eb, 0x4103, 0x3c04
ax_pose 21, 0x01ec, 0x90ef, 0x3c08
ax_pose_terminator
sCacneaPose170:
ax_pose 36, 0x01f4, 0x50ff, 0x3c00
ax_pose 35, 0x01ee, 0x4101, 0x3c04
ax_pose -1, 0x01eb, 0x4103, 0x3c04
ax_pose 21, 0x01ec, 0x90ef, 0x3c08
ax_pose_terminator
sCacneaPose171:
ax_pose 9, 0x01ed, 0x90ef, 0x3c00
ax_pose_terminator
sCacneaPose172:
ax_pose 22, 0x01ed, 0x90ef, 0x3c00
ax_pose_terminator
sCacneaPose173:
ax_pose 23, 0x01ed, 0x90ef, 0x3c00
ax_pose_terminator
sCacneaPose174:
ax_pose 24, 0x01eb, 0x90f0, 0x3c00
ax_pose_terminator
sCacneaPose175:
ax_pose 24, 0x01eb, 0x90f0, 0x3c00
ax_pose 30, 0x01ea, 0x4102, 0x3c10
ax_pose -1, 0x01e6, 0x40fc, 0x3c10
ax_pose_terminator
sCacneaPose176:
ax_pose 24, 0x01eb, 0x90f0, 0x3c00
ax_pose 31, 0x01ea, 0x4102, 0x3c10
ax_pose -1, 0x01e6, 0x40fc, 0x3c10
ax_pose_terminator
sCacneaPose177:
ax_pose 24, 0x01eb, 0x90f0, 0x3c00
ax_pose 32, 0x01ea, 0x4102, 0x3c10
ax_pose -1, 0x01e6, 0x40fc, 0x3c10
ax_pose_terminator
sCacneaPose178:
ax_pose 24, 0x01eb, 0x90f0, 0x3c00
ax_pose 33, 0x01ea, 0x4102, 0x3c10
ax_pose -1, 0x01e6, 0x40fc, 0x3c10
ax_pose_terminator
sCacneaPose179:
ax_pose 24, 0x01eb, 0x90f0, 0x3c00
ax_pose 34, 0x01ea, 0x4102, 0x3c10
ax_pose -1, 0x01e6, 0x40fc, 0x3c10
ax_pose_terminator
sCacneaPose180:
ax_pose 24, 0x01eb, 0x90f0, 0x3c00
ax_pose 35, 0x01ea, 0x4102, 0x3c10
ax_pose -1, 0x01e6, 0x40fc, 0x3c10
ax_pose_terminator
sCacneaPose181:
ax_pose 12, 0x01ed, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose182:
ax_pose 25, 0x01ed, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose183:
ax_pose 26, 0x01ed, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose184:
ax_pose 27, 0x01eb, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose185:
ax_pose 27, 0x01eb, 0x80f0, 0x3c00
ax_pose 30, 0x01e6, 0x40fd, 0x3c10
ax_pose -1, 0x01e6, 0x40f3, 0x3c10
ax_pose_terminator
sCacneaPose186:
ax_pose 27, 0x01eb, 0x80f0, 0x3c00
ax_pose 31, 0x01e6, 0x40fd, 0x3c10
ax_pose -1, 0x01e6, 0x40f3, 0x3c10
ax_pose_terminator
sCacneaPose187:
ax_pose 27, 0x01eb, 0x80f0, 0x3c00
ax_pose 32, 0x01e6, 0x40fd, 0x3c10
ax_pose -1, 0x01e6, 0x40f3, 0x3c10
ax_pose_terminator
sCacneaPose188:
ax_pose 27, 0x01eb, 0x80f0, 0x3c00
ax_pose 33, 0x01e6, 0x40fd, 0x3c10
ax_pose -1, 0x01e6, 0x40f3, 0x3c10
ax_pose_terminator
sCacneaPose189:
ax_pose 27, 0x01eb, 0x80f0, 0x3c00
ax_pose 34, 0x01e6, 0x40fd, 0x3c10
ax_pose -1, 0x01e6, 0x40f3, 0x3c10
ax_pose_terminator
sCacneaPose190:
ax_pose 27, 0x01eb, 0x80f0, 0x3c00
ax_pose 35, 0x01e6, 0x40fd, 0x3c10
ax_pose -1, 0x01e6, 0x40f3, 0x3c10
ax_pose_terminator
sCacneaPose191:
ax_pose 9, 0x01ed, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose192:
ax_pose 22, 0x01ed, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose193:
ax_pose 23, 0x01ed, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose194:
ax_pose 24, 0x01eb, 0x80ef, 0x3c00
ax_pose_terminator
sCacneaPose195:
ax_pose 24, 0x01eb, 0x80ef, 0x3c00
ax_pose 30, 0x01ea, 0x40ed, 0x3c10
ax_pose -1, 0x01e6, 0x40f3, 0x3c10
ax_pose_terminator
sCacneaPose196:
ax_pose 24, 0x01eb, 0x80ef, 0x3c00
ax_pose 31, 0x01ea, 0x40ed, 0x3c10
ax_pose -1, 0x01e6, 0x40f3, 0x3c10
ax_pose_terminator
sCacneaPose197:
ax_pose 24, 0x01eb, 0x80ef, 0x3c00
ax_pose 32, 0x01ea, 0x40ed, 0x3c10
ax_pose -1, 0x01e6, 0x40f3, 0x3c10
ax_pose_terminator
sCacneaPose198:
ax_pose 24, 0x01eb, 0x80ef, 0x3c00
ax_pose 33, 0x01ea, 0x40ed, 0x3c10
ax_pose -1, 0x01e6, 0x40f3, 0x3c10
ax_pose_terminator
sCacneaPose199:
ax_pose 24, 0x01eb, 0x80ef, 0x3c00
ax_pose 34, 0x01ea, 0x40ed, 0x3c10
ax_pose -1, 0x01e6, 0x40f3, 0x3c10
ax_pose_terminator
sCacneaPose200:
ax_pose 24, 0x01eb, 0x80ef, 0x3c00
ax_pose 35, 0x01ea, 0x40ed, 0x3c10
ax_pose -1, 0x01e6, 0x40f3, 0x3c10
ax_pose_terminator
sCacneaPose201:
ax_pose 6, 0x01ee, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose202:
ax_pose 19, 0x01ee, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose203:
ax_pose 20, 0x01ee, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose204:
ax_pose 21, 0x01ec, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose205:
ax_pose 36, 0x01f4, 0x40f0, 0x3c00
ax_pose 30, 0x01ee, 0x40ee, 0x3c04
ax_pose -1, 0x01eb, 0x40ec, 0x3c04
ax_pose 21, 0x01ec, 0x80f0, 0x3c08
ax_pose_terminator
sCacneaPose206:
ax_pose 36, 0x01f4, 0x40f0, 0x3c00
ax_pose 31, 0x01ee, 0x40ee, 0x3c04
ax_pose -1, 0x01eb, 0x40ec, 0x3c04
ax_pose 21, 0x01ec, 0x80f0, 0x3c08
ax_pose_terminator
sCacneaPose207:
ax_pose 36, 0x01f4, 0x40f0, 0x3c00
ax_pose 32, 0x01ee, 0x40ee, 0x3c04
ax_pose -1, 0x01eb, 0x40ec, 0x3c04
ax_pose 21, 0x01ec, 0x80f0, 0x3c08
ax_pose_terminator
sCacneaPose208:
ax_pose 36, 0x01f4, 0x40f0, 0x3c00
ax_pose 33, 0x01ee, 0x40ee, 0x3c04
ax_pose -1, 0x01eb, 0x40ec, 0x3c04
ax_pose 21, 0x01ec, 0x80f0, 0x3c08
ax_pose_terminator
sCacneaPose209:
ax_pose 36, 0x01f4, 0x40f0, 0x3c00
ax_pose 34, 0x01ee, 0x40ee, 0x3c04
ax_pose -1, 0x01eb, 0x40ec, 0x3c04
ax_pose 21, 0x01ec, 0x80f0, 0x3c08
ax_pose_terminator
sCacneaPose210:
ax_pose 36, 0x01f4, 0x40f0, 0x3c00
ax_pose 35, 0x01ee, 0x40ee, 0x3c04
ax_pose -1, 0x01eb, 0x40ec, 0x3c04
ax_pose 21, 0x01ec, 0x80f0, 0x3c08
ax_pose_terminator
sCacneaPose211:
ax_pose 3, 0x01ef, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose212:
ax_pose 16, 0x01ee, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose213:
ax_pose 17, 0x01ef, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose214:
ax_pose 18, 0x01ed, 0x80ee, 0x3c00
ax_pose_terminator
sCacneaPose215:
ax_pose 30, 0x01f1, 0x40ee, 0x3c00
ax_pose -1, 0x01f5, 0x40f4, 0x3c00
ax_pose 18, 0x01ed, 0x80ee, 0x3c04
ax_pose_terminator
sCacneaPose216:
ax_pose 31, 0x01f1, 0x40ee, 0x3c00
ax_pose -1, 0x01f5, 0x40f4, 0x3c00
ax_pose 18, 0x01ed, 0x80ee, 0x3c04
ax_pose_terminator
sCacneaPose217:
ax_pose 32, 0x01f1, 0x40ee, 0x3c00
ax_pose -1, 0x01f5, 0x40f4, 0x3c00
ax_pose 18, 0x01ed, 0x80ee, 0x3c04
ax_pose_terminator
sCacneaPose218:
ax_pose 33, 0x01f1, 0x40ee, 0x3c00
ax_pose -1, 0x01f5, 0x40f4, 0x3c00
ax_pose 18, 0x01ed, 0x80ee, 0x3c04
ax_pose_terminator
sCacneaPose219:
ax_pose 34, 0x01f1, 0x40ee, 0x3c00
ax_pose -1, 0x01f5, 0x40f4, 0x3c00
ax_pose 18, 0x01ed, 0x80ee, 0x3c04
ax_pose_terminator
sCacneaPose220:
ax_pose 35, 0x01f1, 0x40ee, 0x3c00
ax_pose -1, 0x01f5, 0x40f4, 0x3c00
ax_pose 18, 0x01ed, 0x80ee, 0x3c04
ax_pose_terminator
sCacneaPose221:
ax_pose 37, 0x01ee, 0x80f5, 0x3c00
ax_pose_terminator
sCacneaPose222:
ax_pose 38, 0x01ee, 0x80f5, 0x3c00
ax_pose_terminator
sCacneaPose223:
ax_pose 39, 0x01e6, 0x80f1, 0x3c00
ax_pose_terminator
sCacneaPose224:
ax_pose 40, 0x01e6, 0x90ed, 0x3c00
ax_pose_terminator
sCacneaPose225:
ax_pose 41, 0x01e9, 0x90ec, 0x3c00
ax_pose_terminator
sCacneaPose226:
ax_pose 42, 0x01e9, 0x90ed, 0x3c00
ax_pose_terminator
sCacneaPose227:
ax_pose 43, 0x01e6, 0x80f1, 0x3c00
ax_pose_terminator
sCacneaPose228:
ax_pose 42, 0x01e9, 0x80f3, 0x3c00
ax_pose_terminator
sCacneaPose229:
ax_pose 41, 0x01e9, 0x80f4, 0x3c00
ax_pose_terminator
sCacneaPose230:
ax_pose 40, 0x01e6, 0x80f3, 0x3c00
ax_pose_terminator
sCacneaPose231:
ax_pose 0, 0x01ed, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose232:
ax_pose 15, 0x01ed, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose233:
ax_pose 3, 0x01ef, 0x90ef, 0x3c00
ax_pose_terminator
sCacneaPose234:
ax_pose 16, 0x01ee, 0x90f0, 0x3c00
ax_pose_terminator
sCacneaPose235:
ax_pose 6, 0x01ee, 0x90ef, 0x3c00
ax_pose_terminator
sCacneaPose236:
ax_pose 19, 0x01ee, 0x90ef, 0x3c00
ax_pose_terminator
sCacneaPose237:
ax_pose 9, 0x01ed, 0x90ef, 0x3c00
ax_pose_terminator
sCacneaPose238:
ax_pose 22, 0x01ed, 0x90ef, 0x3c00
ax_pose_terminator
sCacneaPose239:
ax_pose 12, 0x01ed, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose240:
ax_pose 25, 0x01ed, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose241:
ax_pose 9, 0x01ed, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose242:
ax_pose 22, 0x01ed, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose243:
ax_pose 6, 0x01ee, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose244:
ax_pose 19, 0x01ee, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose245:
ax_pose 3, 0x01ef, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose246:
ax_pose 16, 0x01ee, 0x80ef, 0x3c00
ax_pose_terminator
sCacneaPose247:
ax_pose 28, 0x01ed, 0x80f1, 0x3c00
ax_pose_terminator
sCacneaPose248:
ax_pose 17, 0x01ef, 0x80f2, 0x3c00
ax_pose_terminator
sCacneaPose249:
ax_pose 20, 0x01ee, 0x80f3, 0x3c00
ax_pose_terminator
sCacneaPose250:
ax_pose 23, 0x01ee, 0x80f2, 0x3c00
ax_pose_terminator
sCacneaPose251:
ax_pose 26, 0x01ee, 0x80f1, 0x3c00
ax_pose_terminator
sCacneaPose252:
ax_pose 23, 0x01ee, 0x90ef, 0x3c00
ax_pose_terminator
sCacneaPose253:
ax_pose 20, 0x01ee, 0x90ee, 0x3c00
ax_pose_terminator
sCacneaPose254:
ax_pose 17, 0x01ef, 0x90ee, 0x3c00
ax_pose_terminator
sCacneaPose255:
ax_pose 15, 0x01ee, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose256:
ax_pose 16, 0x01ef, 0x90f0, 0x3c00
ax_pose_terminator
sCacneaPose257:
ax_pose 19, 0x01ee, 0x90f0, 0x3c00
ax_pose_terminator
sCacneaPose258:
ax_pose 22, 0x01ec, 0x90f0, 0x3c00
ax_pose_terminator
sCacneaPose259:
ax_pose 25, 0x01ec, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose260:
ax_pose 22, 0x01ec, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose261:
ax_pose 19, 0x01ee, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose262:
ax_pose 16, 0x01ef, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose263:
ax_pose 0, 0x01ed, 0x80f1, 0x3c00
ax_pose_terminator
sCacneaPose264:
ax_pose 15, 0x01ee, 0x80f1, 0x3c00
ax_pose_terminator
sCacneaPose265:
ax_pose 28, 0x01ec, 0x80f1, 0x3c00
ax_pose_terminator
sCacneaPose266:
ax_pose 3, 0x01ef, 0x90ef, 0x3c00
ax_pose_terminator
sCacneaPose267:
ax_pose 16, 0x01ee, 0x90f1, 0x3c00
ax_pose_terminator
sCacneaPose268:
ax_pose 17, 0x01ef, 0x90ee, 0x3c00
ax_pose_terminator
sCacneaPose269:
ax_pose 6, 0x01ee, 0x90ef, 0x3c00
ax_pose_terminator
sCacneaPose270:
ax_pose 19, 0x01ee, 0x90f0, 0x3c00
ax_pose_terminator
sCacneaPose271:
ax_pose 20, 0x01ee, 0x90ee, 0x3c00
ax_pose_terminator
sCacneaPose272:
ax_pose 9, 0x01ed, 0x90ef, 0x3c00
ax_pose_terminator
sCacneaPose273:
ax_pose 22, 0x01ec, 0x90f0, 0x3c00
ax_pose_terminator
sCacneaPose274:
ax_pose 23, 0x01ed, 0x90ee, 0x3c00
ax_pose_terminator
sCacneaPose275:
ax_pose 12, 0x01ed, 0x80f1, 0x3c00
ax_pose_terminator
sCacneaPose276:
ax_pose 25, 0x01ec, 0x80f1, 0x3c00
ax_pose_terminator
sCacneaPose277:
ax_pose 26, 0x01ee, 0x80f1, 0x3c00
ax_pose_terminator
sCacneaPose278:
ax_pose 9, 0x01ed, 0x80f1, 0x3c00
ax_pose_terminator
sCacneaPose279:
ax_pose 22, 0x01ec, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose280:
ax_pose 23, 0x01ed, 0x80f2, 0x3c00
ax_pose_terminator
sCacneaPose281:
ax_pose 6, 0x01ee, 0x80f1, 0x3c00
ax_pose_terminator
sCacneaPose282:
ax_pose 19, 0x01ee, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose283:
ax_pose 20, 0x01ee, 0x80f2, 0x3c00
ax_pose_terminator
sCacneaPose284:
ax_pose 3, 0x01ef, 0x80f1, 0x3c00
ax_pose_terminator
sCacneaPose285:
ax_pose 16, 0x01ee, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose286:
ax_pose 17, 0x01ef, 0x80f2, 0x3c00
ax_pose_terminator
sCacneaPose287:
ax_pose 28, 0x01ed, 0x80f1, 0x3c00
ax_pose_terminator
sCacneaPose288:
ax_pose 17, 0x01ef, 0x80f2, 0x3c00
ax_pose_terminator
sCacneaPose289:
ax_pose 20, 0x01ee, 0x80f3, 0x3c00
ax_pose_terminator
sCacneaPose290:
ax_pose 23, 0x01ee, 0x80f2, 0x3c00
ax_pose_terminator
sCacneaPose291:
ax_pose 26, 0x01ee, 0x80f1, 0x3c00
ax_pose_terminator
sCacneaPose292:
ax_pose 23, 0x01ee, 0x90ee, 0x3c00
ax_pose_terminator
sCacneaPose293:
ax_pose 20, 0x01ee, 0x90ed, 0x3c00
ax_pose_terminator
sCacneaPose294:
ax_pose 17, 0x01ef, 0x90ee, 0x3c00
ax_pose_terminator
sCacneaPose295:
ax_pose 0, 0x01ed, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose296:
ax_pose 3, 0x01ef, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose297:
ax_pose 6, 0x01ee, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose298:
ax_pose 9, 0x01ed, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose299:
ax_pose 12, 0x01ed, 0x80f0, 0x3c00
ax_pose_terminator
sCacneaPose300:
ax_pose 9, 0x01ed, 0x90ef, 0x3c00
ax_pose_terminator
sCacneaPose301:
ax_pose 6, 0x01ee, 0x90ef, 0x3c00
ax_pose_terminator
sCacneaPose302:
ax_pose 3, 0x01ef, 0x90ef, 0x3c00
ax_pose_terminator
.align 2
sCacneaAnims_1_1:
ax_anim 8, 0, 0, 0, 0, 0, 0,
ax_anim 10, 0, 1, 0, 0, 0, 0,
ax_anim 8, 0, 0, 0, 0, 0, 0,
ax_anim 10, 0, 2, 0, 0, 0, 0,
ax_anim_terminator
sCacneaAnims_1_2:
ax_anim 8, 0, 3, 0, 0, 0, 0,
ax_anim 10, 0, 4, 0, 0, 0, 0,
ax_anim 8, 0, 3, 0, 0, 0, 0,
ax_anim 10, 0, 5, 0, 0, 0, 0,
ax_anim_terminator
sCacneaAnims_1_3:
ax_anim 8, 0, 6, 0, 0, 0, 0,
ax_anim 10, 0, 7, 0, 0, 0, 0,
ax_anim 8, 0, 6, 0, 0, 0, 0,
ax_anim 10, 0, 8, 0, 0, 0, 0,
ax_anim_terminator
sCacneaAnims_1_4:
ax_anim 8, 0, 9, 0, 0, 0, 0,
ax_anim 10, 0, 10, 0, 0, 0, 0,
ax_anim 8, 0, 9, 0, 0, 0, 0,
ax_anim 10, 0, 11, 0, 0, 0, 0,
ax_anim_terminator
sCacneaAnims_1_5:
ax_anim 8, 0, 12, 0, 0, 0, 0,
ax_anim 10, 0, 13, 0, 0, 0, 0,
ax_anim 8, 0, 12, 0, 0, 0, 0,
ax_anim 10, 0, 14, 0, 0, 0, 0,
ax_anim_terminator
sCacneaAnims_1_6:
ax_anim 8, 0, 15, 0, 0, 0, 0,
ax_anim 10, 0, 16, 0, 0, 0, 0,
ax_anim 8, 0, 15, 0, 0, 0, 0,
ax_anim 10, 0, 17, 0, 0, 0, 0,
ax_anim_terminator
sCacneaAnims_1_7:
ax_anim 8, 0, 18, 0, 0, 0, 0,
ax_anim 10, 0, 19, 0, 0, 0, 0,
ax_anim 8, 0, 18, 0, 0, 0, 0,
ax_anim 10, 0, 20, 0, 0, 0, 0,
ax_anim_terminator
sCacneaAnims_1_8:
ax_anim 8, 0, 21, 0, 0, 0, 0,
ax_anim 10, 0, 22, 0, 0, 0, 0,
ax_anim 8, 0, 21, 0, 0, 0, 0,
ax_anim 10, 0, 23, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sCacneaAnims_2_1:
ax_anim 2, 0, 24, 0, -1, 0, -1,
ax_anim 4, 0, 24, 0, -2, 0, -2,
ax_anim 1, 0, 26, 0, 0, 0, 0,
ax_anim 1, 2, 25, 0, 4, 0, 4,
ax_anim 1, 0, 26, 0, 10, 0, 10,
ax_anim 2, 0, 27, 0, 21, 0, 21,
ax_anim 2, 1, 27, 1, 21, 1, 21,
ax_anim 2, 0, 27, 0, 21, 0, 21,
ax_anim 2, 0, 27, 1, 21, 1, 21,
ax_anim 2, 0, 24, 0, 6, 0, 6,
ax_anim_terminator
sCacneaAnims_2_2:
ax_anim 2, 0, 28, -1, -1, -1, -1,
ax_anim 4, 0, 28, -2, -2, -2, -2,
ax_anim 1, 0, 30, 0, 0, 0, 0,
ax_anim 1, 2, 29, 4, 4, 4, 4,
ax_anim 1, 0, 30, 10, 9, 10, 9,
ax_anim 2, 0, 31, 22, 20, 22, 20,
ax_anim 2, 1, 31, 23, 19, 23, 19,
ax_anim 2, 0, 31, 22, 20, 22, 20,
ax_anim 2, 0, 31, 23, 19, 23, 19,
ax_anim 2, 0, 28, 6, 6, 6, 6,
ax_anim_terminator
sCacneaAnims_2_3:
ax_anim 2, 0, 34, -1, 0, -1, 0,
ax_anim 4, 0, 34, -2, 0, -2, 0,
ax_anim 1, 0, 36, 0, 0, 0, 0,
ax_anim 1, 2, 35, 4, 0, 4, 0,
ax_anim 1, 0, 36, 10, 0, 10, 0,
ax_anim 2, 0, 37, 22, 0, 22, 0,
ax_anim 2, 1, 37, 22, 1, 22, 1,
ax_anim 2, 0, 37, 22, 0, 22, 0,
ax_anim 2, 0, 37, 22, 1, 22, 1,
ax_anim 2, 0, 34, 6, 0, 6, 0,
ax_anim_terminator
sCacneaAnims_2_4:
ax_anim 2, 0, 40, -1, 1, -1, 1,
ax_anim 4, 0, 40, -2, 2, -2, 2,
ax_anim 1, 0, 42, 0, -1, 0, -1,
ax_anim 1, 2, 41, 5, -6, 5, -6,
ax_anim 1, 0, 42, 11, -12, 11, -12,
ax_anim 2, 0, 43, 22, -23, 22, -23,
ax_anim 2, 1, 43, 23, -22, 23, -22,
ax_anim 2, 0, 43, 22, -23, 22, -23,
ax_anim 2, 0, 43, 23, -22, 23, -22,
ax_anim 2, 0, 40, 6, -6, 6, -6,
ax_anim_terminator
sCacneaAnims_2_5:
ax_anim 2, 0, 46, 0, 1, 0, 1,
ax_anim 4, 0, 46, 0, 2, 0, 2,
ax_anim 1, 0, 48, 0, 0, 0, 0,
ax_anim 1, 2, 47, 0, -4, 0, -4,
ax_anim 1, 0, 48, 0, -11, 0, -11,
ax_anim 2, 0, 49, 0, -24, 0, -24,
ax_anim 2, 1, 49, 1, -24, 1, -24,
ax_anim 2, 0, 49, 0, -24, 0, -24,
ax_anim 2, 0, 49, 1, -24, 1, -24,
ax_anim 2, 0, 46, 0, -6, 0, -6,
ax_anim_terminator
sCacneaAnims_2_6:
ax_anim 2, 0, 52, 1, 1, 1, 1,
ax_anim 4, 0, 52, 2, 2, 2, 2,
ax_anim 1, 0, 54, 0, -1, 0, -1,
ax_anim 1, 2, 53, -5, -6, -5, -6,
ax_anim 1, 0, 54, -11, -12, -11, -12,
ax_anim 2, 0, 55, -22, -23, -22, -23,
ax_anim 2, 1, 55, -23, -22, -23, -22,
ax_anim 2, 0, 55, -22, -23, -22, -23,
ax_anim 2, 0, 55, -23, -22, -23, -22,
ax_anim 2, 0, 52, -6, -6, -6, -6,
ax_anim_terminator
sCacneaAnims_2_7:
ax_anim 2, 0, 58, 1, 0, 1, 0,
ax_anim 4, 0, 58, 2, 0, 2, 0,
ax_anim 1, 0, 60, 0, 0, 0, 0,
ax_anim 1, 2, 59, -4, 0, -4, 0,
ax_anim 1, 0, 60, -10, 0, -10, 0,
ax_anim 2, 0, 61, -22, 0, -22, 0,
ax_anim 2, 1, 61, -22, 1, -22, 1,
ax_anim 2, 0, 61, -22, 0, -22, 0,
ax_anim 2, 0, 61, -22, 1, -22, 1,
ax_anim 2, 0, 58, -6, 0, -6, 0,
ax_anim_terminator
sCacneaAnims_2_8:
ax_anim 2, 0, 64, 1, -1, 1, -1,
ax_anim 4, 0, 64, 2, -2, 2, -2,
ax_anim 1, 0, 66, 0, 0, 0, 0,
ax_anim 1, 2, 65, -4, 4, -4, 4,
ax_anim 1, 0, 66, -10, 9, -10, 9,
ax_anim 2, 0, 67, -22, 20, -22, 20,
ax_anim 2, 1, 67, -23, 19, -23, 19,
ax_anim 2, 0, 67, -22, 20, -22, 20,
ax_anim 2, 0, 67, -23, 19, -23, 19,
ax_anim 2, 0, 64, -6, 6, -6, 6,
ax_anim_terminator
.align 2
sCacneaAnims_3_1:
ax_anim 2, 0, 70, 0, -1, 0, -1,
ax_anim 4, 0, 70, 0, -2, 0, -2,
ax_anim 1, 0, 72, 0, 0, 0, 0,
ax_anim 1, 2, 71, 0, 4, 0, 4,
ax_anim 1, 0, 72, 0, 10, 0, 10,
ax_anim 2, 0, 73, 0, 21, 0, 21,
ax_anim 2, 1, 73, 1, 21, 1, 21,
ax_anim 2, 0, 73, 0, 21, 0, 21,
ax_anim 2, 0, 73, 1, 21, 1, 21,
ax_anim 2, 0, 70, 0, 6, 0, 6,
ax_anim_terminator
sCacneaAnims_3_2:
ax_anim 2, 0, 74, -1, -1, -1, -1,
ax_anim 4, 0, 74, -2, -2, -2, -2,
ax_anim 1, 0, 76, 0, 0, 0, 0,
ax_anim 1, 2, 75, 4, 4, 4, 4,
ax_anim 1, 0, 76, 10, 9, 10, 9,
ax_anim 2, 0, 77, 22, 20, 22, 20,
ax_anim 2, 1, 77, 23, 19, 23, 19,
ax_anim 2, 0, 77, 22, 20, 22, 20,
ax_anim 2, 0, 77, 23, 19, 23, 19,
ax_anim 2, 0, 74, 6, 6, 6, 6,
ax_anim_terminator
sCacneaAnims_3_3:
ax_anim 2, 0, 80, -1, 0, -1, 0,
ax_anim 4, 0, 80, -2, 0, -2, 0,
ax_anim 1, 0, 82, 0, 0, 0, 0,
ax_anim 1, 2, 81, 4, 0, 4, 0,
ax_anim 1, 0, 82, 10, 0, 10, 0,
ax_anim 2, 0, 83, 22, 0, 22, 0,
ax_anim 2, 1, 83, 22, 1, 22, 1,
ax_anim 2, 0, 83, 22, 0, 22, 0,
ax_anim 2, 0, 83, 22, 1, 22, 1,
ax_anim 2, 0, 80, 6, 0, 6, 0,
ax_anim_terminator
sCacneaAnims_3_4:
ax_anim 2, 0, 86, -1, 1, -1, 1,
ax_anim 4, 0, 86, -2, 2, -2, 2,
ax_anim 1, 0, 88, 0, -1, 0, -1,
ax_anim 1, 2, 87, 5, -6, 5, -6,
ax_anim 1, 0, 88, 11, -12, 11, -12,
ax_anim 2, 0, 89, 22, -23, 22, -23,
ax_anim 2, 1, 89, 23, -22, 23, -22,
ax_anim 2, 0, 89, 22, -23, 22, -23,
ax_anim 2, 0, 89, 23, -22, 23, -22,
ax_anim 2, 0, 86, 6, -6, 6, -6,
ax_anim_terminator
sCacneaAnims_3_5:
ax_anim 2, 0, 92, 0, 1, 0, 1,
ax_anim 4, 0, 92, 0, 2, 0, 2,
ax_anim 1, 0, 94, 0, 0, 0, 0,
ax_anim 1, 2, 93, 0, -4, 0, -4,
ax_anim 1, 0, 94, 0, -11, 0, -11,
ax_anim 2, 0, 95, 0, -24, 0, -24,
ax_anim 2, 1, 95, 1, -24, 1, -24,
ax_anim 2, 0, 95, 0, -24, 0, -24,
ax_anim 2, 0, 95, 1, -24, 1, -24,
ax_anim 2, 0, 92, 0, -6, 0, -6,
ax_anim_terminator
sCacneaAnims_3_6:
ax_anim 2, 0, 98, 1, 1, 1, 1,
ax_anim 4, 0, 98, 2, 2, 2, 2,
ax_anim 1, 0, 100, 0, -1, 0, -1,
ax_anim 1, 2, 99, -5, -6, -5, -6,
ax_anim 1, 0, 100, -11, -12, -11, -12,
ax_anim 2, 0, 101, -22, -23, -22, -23,
ax_anim 2, 1, 101, -23, -22, -23, -22,
ax_anim 2, 0, 101, -22, -23, -22, -23,
ax_anim 2, 0, 101, -23, -22, -23, -22,
ax_anim 2, 0, 98, -6, -6, -6, -6,
ax_anim_terminator
sCacneaAnims_3_7:
ax_anim 2, 0, 104, 1, 0, 1, 0,
ax_anim 4, 0, 104, 2, 0, 2, 0,
ax_anim 1, 0, 106, 0, 0, 0, 0,
ax_anim 1, 2, 105, -4, 0, -4, 0,
ax_anim 1, 0, 106, -10, 0, -10, 0,
ax_anim 2, 0, 107, -22, 0, -22, 0,
ax_anim 2, 1, 107, -22, 1, -22, 1,
ax_anim 2, 0, 107, -22, 0, -22, 0,
ax_anim 2, 0, 107, -22, 1, -22, 1,
ax_anim 2, 0, 104, -6, 0, -6, 0,
ax_anim_terminator
sCacneaAnims_3_8:
ax_anim 2, 0, 110, 1, -1, 1, -1,
ax_anim 4, 0, 110, 2, -2, 2, -2,
ax_anim 1, 0, 112, 0, 0, 0, 0,
ax_anim 1, 2, 111, -4, 4, -4, 4,
ax_anim 1, 0, 112, -10, 9, -10, 9,
ax_anim 2, 0, 113, -22, 20, -22, 20,
ax_anim 2, 1, 113, -23, 19, -23, 19,
ax_anim 2, 0, 113, -22, 20, -22, 20,
ax_anim 2, 0, 113, -23, 19, -23, 19,
ax_anim 2, 0, 110, -6, 6, -6, 6,
ax_anim_terminator
.align 2
sCacneaAnims_4_1:
ax_anim 2, 0, 117, 0, -2, 0, -2,
ax_anim 6, 2, 117, 0, -3, 0, -3,
ax_anim 2, 0, 116, 0, -1, 0, -1,
ax_anim 2, 1, 118, 0, 3, 0, 3,
ax_anim 2, 0, 118, 1, 3, 1, 3,
ax_anim 2, 0, 118, 0, 3, 0, 3,
ax_anim 2, 0, 118, 1, 3, 1, 3,
ax_anim 2, 0, 118, 0, 3, 0, 3,
ax_anim 2, 0, 118, 1, 3, 1, 3,
ax_anim 2, 0, 118, 0, 3, 0, 3,
ax_anim 2, 0, 116, 0, 1, 0, 1,
ax_anim_terminator
sCacneaAnims_4_2:
ax_anim 2, 0, 120, -2, -2, -2, -2,
ax_anim 6, 2, 120, -3, -3, -3, -3,
ax_anim 2, 0, 119, -1, -1, -1, -1,
ax_anim 2, 1, 121, 2, 2, 2, 2,
ax_anim 2, 0, 121, 3, 1, 3, 1,
ax_anim 2, 0, 121, 2, 2, 2, 2,
ax_anim 2, 0, 121, 3, 1, 3, 1,
ax_anim 2, 0, 121, 2, 2, 2, 2,
ax_anim 2, 0, 121, 3, 1, 3, 1,
ax_anim 2, 0, 121, 2, 2, 2, 2,
ax_anim 2, 0, 119, 1, 1, 1, 1,
ax_anim_terminator
sCacneaAnims_4_3:
ax_anim 2, 0, 123, -2, 0, -2, 0,
ax_anim 6, 2, 123, -3, 0, -3, 0,
ax_anim 2, 0, 122, -1, 0, -1, 0,
ax_anim 2, 1, 124, 2, 0, 2, 0,
ax_anim 2, 0, 124, 2, 1, 2, 1,
ax_anim 2, 0, 124, 2, 0, 2, 0,
ax_anim 2, 0, 124, 2, 1, 2, 1,
ax_anim 2, 0, 124, 2, 0, 2, 0,
ax_anim 2, 0, 124, 2, 1, 2, 1,
ax_anim 2, 0, 124, 2, 0, 2, 0,
ax_anim 2, 0, 122, 1, 0, 1, 0,
ax_anim_terminator
sCacneaAnims_4_4:
ax_anim 2, 0, 126, -2, 2, -2, 2,
ax_anim 6, 2, 126, -3, 3, -3, 3,
ax_anim 2, 0, 125, -1, 1, -1, 1,
ax_anim 2, 1, 127, 2, -2, 2, -2,
ax_anim 2, 0, 127, 3, -1, 3, -1,
ax_anim 2, 0, 127, 2, -2, 2, -2,
ax_anim 2, 0, 127, 3, -1, 3, -1,
ax_anim 2, 0, 127, 2, -2, 2, -2,
ax_anim 2, 0, 127, 3, -1, 3, -1,
ax_anim 2, 0, 127, 2, -2, 2, -2,
ax_anim 2, 0, 125, 1, -1, 1, -1,
ax_anim_terminator
sCacneaAnims_4_5:
ax_anim 2, 0, 129, 0, 2, 0, 2,
ax_anim 6, 2, 129, 0, 3, 0, 3,
ax_anim 2, 0, 128, 0, 1, 0, 1,
ax_anim 2, 1, 130, 0, -3, 0, -3,
ax_anim 2, 0, 130, 1, -3, 1, -3,
ax_anim 2, 0, 130, 0, -3, 0, -3,
ax_anim 2, 0, 130, 1, -3, 1, -3,
ax_anim 2, 0, 130, 0, -3, 0, -3,
ax_anim 2, 0, 130, 1, -3, 1, -3,
ax_anim 2, 0, 130, 0, -3, 0, -3,
ax_anim 2, 0, 128, 0, -1, 0, -1,
ax_anim_terminator
sCacneaAnims_4_6:
ax_anim 2, 0, 132, 2, 2, 2, 2,
ax_anim 6, 2, 132, 3, 3, 3, 3,
ax_anim 2, 0, 131, 1, 1, 1, 1,
ax_anim 2, 1, 133, -2, -2, -2, -2,
ax_anim 2, 0, 133, -3, -1, -3, -1,
ax_anim 2, 0, 133, -2, -2, -2, -2,
ax_anim 2, 0, 133, -3, -1, -3, -1,
ax_anim 2, 0, 133, -2, -2, -2, -2,
ax_anim 2, 0, 133, -3, -1, -3, -1,
ax_anim 2, 0, 133, -2, -2, -2, -2,
ax_anim 2, 0, 131, -1, -1, -1, -1,
ax_anim_terminator
sCacneaAnims_4_7:
ax_anim 2, 0, 135, 2, 0, 2, 0,
ax_anim 6, 2, 135, 3, 0, 3, 0,
ax_anim 2, 0, 134, 1, 0, 1, 0,
ax_anim 2, 1, 136, -2, 0, -2, 0,
ax_anim 2, 0, 136, -2, 1, -2, 1,
ax_anim 2, 0, 136, -2, 0, -2, 0,
ax_anim 2, 0, 136, -2, 1, -2, 1,
ax_anim 2, 0, 136, -2, 0, -2, 0,
ax_anim 2, 0, 136, -2, 1, -2, 1,
ax_anim 2, 0, 136, -2, 0, -2, 0,
ax_anim 2, 0, 134, -1, 0, -1, 0,
ax_anim_terminator
sCacneaAnims_4_8:
ax_anim 2, 0, 138, 2, -2, 2, -2,
ax_anim 6, 2, 138, 3, -3, 3, -3,
ax_anim 2, 0, 137, 1, -1, 1, -1,
ax_anim 2, 1, 139, -2, 2, -2, 2,
ax_anim 2, 0, 139, -3, 1, -3, 1,
ax_anim 2, 0, 139, -2, 2, -2, 2,
ax_anim 2, 0, 139, -3, 1, -3, 1,
ax_anim 2, 0, 139, -2, 2, -2, 2,
ax_anim 2, 0, 139, -3, 1, -3, 1,
ax_anim 2, 0, 139, -2, 2, -2, 2,
ax_anim 2, 0, 137, -1, 1, -1, 1,
ax_anim_terminator
.align 2
sCacneaAnims_5_1:
ax_anim 2, 0, 141, 0, -2, 0, -2,
ax_anim 4, 0, 141, 0, -3, 0, -3,
ax_anim 2, 0, 140, 0, -1, 0, -1,
ax_anim 4, 0, 142, 0, 0, 0, 0,
ax_anim 6, 0, 143, 0, 0, 0, 0,
ax_anim 1, 0, 146, 0, 0, 0, 0,
ax_anim 1, 0, 147, 0, 0, 0, 0,
ax_anim 1, 0, 148, 0, 0, 0, 0,
ax_anim 1, 0, 149, 0, 0, 0, 0,
ax_anim 4, 2, 143, 0, 0, 0, 0,
ax_anim 4, 0, 142, 0, 0, 0, 0,
ax_anim_terminator
sCacneaAnims_5_2:
ax_anim 2, 0, 151, -2, -2, -2, -2,
ax_anim 4, 0, 151, -3, -3, -3, -3,
ax_anim 2, 0, 150, -1, -1, -1, -1,
ax_anim 4, 0, 152, 0, 0, 0, 0,
ax_anim 6, 0, 153, 0, 0, 0, 0,
ax_anim 1, 0, 156, 0, 0, 0, 0,
ax_anim 1, 0, 157, 0, 0, 0, 0,
ax_anim 1, 0, 158, 0, 0, 0, 0,
ax_anim 1, 0, 159, 0, 0, 0, 0,
ax_anim 4, 2, 153, 0, 0, 0, 0,
ax_anim 4, 0, 152, 0, 0, 0, 0,
ax_anim_terminator
sCacneaAnims_5_3:
ax_anim 2, 0, 161, -2, 0, -2, 0,
ax_anim 4, 0, 161, -3, 0, -3, 0,
ax_anim 2, 0, 160, -1, 0, -1, 0,
ax_anim 4, 0, 162, 0, 0, 0, 0,
ax_anim 6, 0, 163, 0, 0, 0, 0,
ax_anim 1, 0, 166, 0, 0, 0, 0,
ax_anim 1, 0, 167, 0, 0, 0, 0,
ax_anim 1, 0, 168, 0, 0, 0, 0,
ax_anim 1, 0, 169, 0, 0, 0, 0,
ax_anim 4, 2, 163, 0, 0, 0, 0,
ax_anim 4, 0, 162, 0, 0, 0, 0,
ax_anim_terminator
sCacneaAnims_5_4:
ax_anim 2, 0, 171, -2, 2, -2, 2,
ax_anim 4, 0, 171, -3, 3, -3, 3,
ax_anim 2, 0, 170, -1, 1, -1, 1,
ax_anim 4, 0, 172, 0, 0, 0, 0,
ax_anim 6, 0, 173, 0, 0, 0, 0,
ax_anim 1, 0, 176, 0, 0, 0, 0,
ax_anim 1, 0, 177, 0, 0, 0, 0,
ax_anim 1, 0, 178, 0, 0, 0, 0,
ax_anim 1, 0, 179, 0, 0, 0, 0,
ax_anim 4, 2, 173, 0, 0, 0, 0,
ax_anim 4, 0, 172, 0, 0, 0, 0,
ax_anim_terminator
sCacneaAnims_5_5:
ax_anim 2, 0, 181, 0, 2, 0, 2,
ax_anim 4, 0, 181, 0, 3, 0, 3,
ax_anim 2, 0, 180, 0, 1, 0, 1,
ax_anim 4, 0, 182, 0, 0, 0, 0,
ax_anim 6, 0, 183, 0, 0, 0, 0,
ax_anim 1, 0, 186, 0, 0, 0, 0,
ax_anim 1, 0, 187, 0, 0, 0, 0,
ax_anim 1, 0, 188, 0, 0, 0, 0,
ax_anim 1, 0, 189, 0, 0, 0, 0,
ax_anim 4, 2, 183, 0, 0, 0, 0,
ax_anim 4, 0, 182, 0, 0, 0, 0,
ax_anim_terminator
sCacneaAnims_5_6:
ax_anim 2, 0, 191, 2, 2, 2, 2,
ax_anim 4, 0, 191, 3, 3, 3, 3,
ax_anim 2, 0, 190, 1, 1, 1, 1,
ax_anim 4, 0, 192, 0, 0, 0, 0,
ax_anim 6, 0, 193, 0, 0, 0, 0,
ax_anim 1, 0, 196, 0, 0, 0, 0,
ax_anim 1, 0, 197, 0, 0, 0, 0,
ax_anim 1, 0, 198, 0, 0, 0, 0,
ax_anim 1, 0, 199, 0, 0, 0, 0,
ax_anim 4, 2, 193, 0, 0, 0, 0,
ax_anim 4, 0, 192, 0, 0, 0, 0,
ax_anim_terminator
sCacneaAnims_5_7:
ax_anim 2, 0, 201, 2, 0, 2, 0,
ax_anim 4, 0, 201, 3, 0, 3, 0,
ax_anim 2, 0, 200, 1, 0, 1, 0,
ax_anim 4, 0, 202, 0, 0, 0, 0,
ax_anim 6, 0, 203, 0, 0, 0, 0,
ax_anim 1, 0, 206, 0, 0, 0, 0,
ax_anim 1, 0, 207, 0, 0, 0, 0,
ax_anim 1, 0, 208, 0, 0, 0, 0,
ax_anim 1, 0, 209, 0, 0, 0, 0,
ax_anim 4, 2, 203, 0, 0, 0, 0,
ax_anim 4, 0, 202, 0, 0, 0, 0,
ax_anim_terminator
sCacneaAnims_5_8:
ax_anim 2, 0, 211, 2, -2, 2, -2,
ax_anim 4, 0, 211, 3, -3, 3, -3,
ax_anim 2, 0, 210, 1, -1, 1, -1,
ax_anim 4, 0, 212, 0, 0, 0, 0,
ax_anim 6, 0, 213, 0, 0, 0, 0,
ax_anim 1, 0, 216, 0, 0, 0, 0,
ax_anim 1, 0, 217, 0, 0, 0, 0,
ax_anim 1, 0, 218, 0, 0, 0, 0,
ax_anim 1, 0, 219, 0, 0, 0, 0,
ax_anim 4, 2, 213, 0, 0, 0, 0,
ax_anim 4, 0, 212, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sCacneaAnims_6_1:
ax_anim 30, 0, 220, 0, 0, 0, 0,
ax_anim 35, 0, 221, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sCacneaAnims_7_1:
ax_anim 2, 0, 222, 0, -4, 0, -4,
ax_anim 8, 0, 222, 0, -5, 0, -5,
ax_anim_terminator
sCacneaAnims_7_2:
ax_anim 2, 0, 223, -4, -4, -4, -4,
ax_anim 8, 0, 223, -5, -5, -5, -5,
ax_anim_terminator
sCacneaAnims_7_3:
ax_anim 2, 0, 224, -4, 0, -4, 0,
ax_anim 8, 0, 224, -5, 0, -5, 0,
ax_anim_terminator
sCacneaAnims_7_4:
ax_anim 2, 0, 225, -4, 4, -4, 4,
ax_anim 8, 0, 225, -5, 5, -5, 5,
ax_anim_terminator
sCacneaAnims_7_5:
ax_anim 2, 0, 226, 0, 4, 0, 4,
ax_anim 8, 0, 226, 0, 5, 0, 5,
ax_anim_terminator
sCacneaAnims_7_6:
ax_anim 2, 0, 227, 4, 4, 4, 4,
ax_anim 8, 0, 227, 5, 5, 5, 5,
ax_anim_terminator
sCacneaAnims_7_7:
ax_anim 2, 0, 228, 4, 0, 4, 0,
ax_anim 8, 0, 228, 5, 0, 5, 0,
ax_anim_terminator
sCacneaAnims_7_8:
ax_anim 2, 0, 229, 4, -4, 4, -4,
ax_anim 8, 0, 229, 5, -5, 5, -5,
ax_anim_terminator
.align 2
sCacneaAnims_8_1:
ax_anim 40, 0, 230, 0, 0, 0, 0,
ax_anim 10, 0, 231, 0, 0, 0, 0,
ax_anim 16, 0, 230, 0, 0, 0, 0,
ax_anim 10, 0, 231, 0, 0, 0, 0,
ax_anim_terminator
sCacneaAnims_8_2:
ax_anim 40, 0, 232, 0, 0, 0, 0,
ax_anim 10, 0, 233, 0, 0, 0, 0,
ax_anim 16, 0, 232, 0, 0, 0, 0,
ax_anim 10, 0, 233, 0, 0, 0, 0,
ax_anim_terminator
sCacneaAnims_8_3:
ax_anim 40, 0, 234, 0, 0, 0, 0,
ax_anim 10, 0, 235, 0, 0, 0, 0,
ax_anim 16, 0, 234, 0, 0, 0, 0,
ax_anim 10, 0, 235, 0, 0, 0, 0,
ax_anim_terminator
sCacneaAnims_8_4:
ax_anim 40, 0, 236, 0, 0, 0, 0,
ax_anim 10, 0, 237, 0, 0, 0, 0,
ax_anim 16, 0, 236, 0, 0, 0, 0,
ax_anim 10, 0, 237, 0, 0, 0, 0,
ax_anim_terminator
sCacneaAnims_8_5:
ax_anim 40, 0, 238, 0, 0, 0, 0,
ax_anim 10, 0, 239, 0, 0, 0, 0,
ax_anim 16, 0, 238, 0, 0, 0, 0,
ax_anim 10, 0, 239, 0, 0, 0, 0,
ax_anim_terminator
sCacneaAnims_8_6:
ax_anim 40, 0, 240, 0, 0, 0, 0,
ax_anim 10, 0, 241, 0, 0, 0, 0,
ax_anim 16, 0, 240, 0, 0, 0, 0,
ax_anim 10, 0, 241, 0, 0, 0, 0,
ax_anim_terminator
sCacneaAnims_8_7:
ax_anim 40, 0, 242, 0, 0, 0, 0,
ax_anim 10, 0, 243, 0, 0, 0, 0,
ax_anim 16, 0, 242, 0, 0, 0, 0,
ax_anim 10, 0, 243, 0, 0, 0, 0,
ax_anim_terminator
sCacneaAnims_8_8:
ax_anim 40, 0, 244, 0, 0, 0, 0,
ax_anim 10, 0, 245, 0, 0, 0, 0,
ax_anim 16, 0, 244, 0, 0, 0, 0,
ax_anim 10, 0, 245, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sCacneaAnims_9_1:
ax_anim 2, 0, 246, 0, 0, 0, 0,
ax_anim 1, 0, 247, 9, 6, 9, 6,
ax_anim 2, 0, 248, 11, 13, 11, 13,
ax_anim 2, 0, 249, 9, 18, 9, 18,
ax_anim 3, 0, 250, 0, 21, 0, 21,
ax_anim 2, 3, 251, -9, 18, -9, 18,
ax_anim 2, 0, 252, -11, 13, -11, 13,
ax_anim 1, 0, 253, -9, 6, -9, 6,
ax_anim 1, 0, 246, 0, 0, 0, 0,
ax_anim_terminator
sCacneaAnims_9_2:
ax_anim 2, 0, 253, 0, 0, 0, 0,
ax_anim 1, 0, 246, 10, -1, 10, -1,
ax_anim 2, 0, 247, 18, 4, 18, 4,
ax_anim 2, 0, 248, 23, 12, 23, 12,
ax_anim 3, 0, 249, 22, 20, 22, 20,
ax_anim 2, 3, 250, 11, 20, 11, 20,
ax_anim 2, 0, 251, 3, 16, 3, 16,
ax_anim 1, 0, 252, 0, 7, 0, 7,
ax_anim 1, 0, 253, 0, 0, 0, 0,
ax_anim_terminator
sCacneaAnims_9_3:
ax_anim 2, 0, 252, 0, 0, 0, 0,
ax_anim 1, 0, 253, 5, -4, 5, -4,
ax_anim 2, 0, 246, 13, -6, 13, -6,
ax_anim 2, 0, 247, 20, -3, 20, -3,
ax_anim 3, 0, 248, 23, -1, 23, -1,
ax_anim 2, 3, 249, 21, 4, 21, 4,
ax_anim 2, 0, 250, 12, 5, 12, 5,
ax_anim 1, 0, 251, 6, 4, 6, 4,
ax_anim 1, 0, 252, 0, 0, 0, 0,
ax_anim_terminator
sCacneaAnims_9_4:
ax_anim 2, 0, 251, 0, 0, 0, 0,
ax_anim 1, 0, 252, 0, -9, 0, -9,
ax_anim 2, 0, 253, 6, -17, 6, -17,
ax_anim 2, 0, 246, 13, -24, 13, -24,
ax_anim 3, 0, 247, 23, -23, 23, -23,
ax_anim 2, 3, 248, 27, -15, 27, -15,
ax_anim 2, 0, 249, 21, -7, 21, -7,
ax_anim 1, 0, 250, 12, -1, 12, -1,
ax_anim 1, 0, 251, 0, 0, 0, 0,
ax_anim_terminator
sCacneaAnims_9_5:
ax_anim 2, 0, 250, 0, 0, 0, 0,
ax_anim 1, 0, 251, -10, -4, -10, -4,
ax_anim 2, 0, 252, -12, -11, -12, -11,
ax_anim 2, 0, 253, -9, -19, -9, -19,
ax_anim 3, 0, 246, 0, -25, 0, -25,
ax_anim 2, 3, 247, 9, -19, 9, -19,
ax_anim 2, 0, 248, 12, -11, 12, -11,
ax_anim 1, 0, 249, 10, -4, 10, -4,
ax_anim 1, 0, 250, 0, 0, 0, 0,
ax_anim_terminator
sCacneaAnims_9_6:
ax_anim 2, 0, 249, 0, 0, 0, 0,
ax_anim 1, 0, 248, 0, -9, 0, -9,
ax_anim 2, 0, 247, -6, -17, -6, -17,
ax_anim 2, 0, 246, -13, -24, -13, -24,
ax_anim 3, 0, 253, -23, -23, -23, -23,
ax_anim 2, 3, 252, -27, -15, -27, -15,
ax_anim 2, 0, 251, -21, -7, -21, -7,
ax_anim 1, 0, 250, -12, -1, -12, -1,
ax_anim 1, 0, 249, 0, 0, 0, 0,
ax_anim_terminator
sCacneaAnims_9_7:
ax_anim 2, 0, 248, 0, 0, 0, 0,
ax_anim 1, 0, 247, -5, -4, -5, -4,
ax_anim 2, 0, 246, -13, -6, -13, -6,
ax_anim 2, 0, 253, -20, -4, -20, -4,
ax_anim 3, 0, 252, -23, -1, -23, -1,
ax_anim 2, 3, 251, -21, 4, -21, 4,
ax_anim 2, 0, 250, -12, 5, -12, 5,
ax_anim 1, 0, 249, -6, 4, -6, 4,
ax_anim 1, 0, 248, 0, 0, 0, 0,
ax_anim_terminator
sCacneaAnims_9_8:
ax_anim 2, 0, 247, 0, 0, 0, 0,
ax_anim 1, 0, 246, -10, -1, -10, -1,
ax_anim 2, 0, 253, -18, 4, -18, 4,
ax_anim 2, 0, 252, -23, 12, -23, 12,
ax_anim 3, 0, 251, -22, 20, -22, 20,
ax_anim 2, 3, 250, -11, 20, -11, 20,
ax_anim 2, 0, 249, -3, 16, -3, 16,
ax_anim 1, 0, 248, 0, 7, 0, 7,
ax_anim 1, 0, 247, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sCacneaAnims_10_1:
ax_anim 2, 0, 254, 0, 0, 0, 0,
ax_anim 2, 0, 254, 6, 0, 6, 0,
ax_anim 2, 0, 254, -6, 0, -6, 0,
ax_anim 2, 0, 254, 10, 0, 10, 0,
ax_anim 2, 0, 254, -10, 0, -10, 0,
ax_anim 2, 0, 254, 12, 0, 12, 0,
ax_anim 3, 0, 254, -12, 0, -12, 0,
ax_anim 3, 0, 254, 13, 0, 13, 0,
ax_anim 3, 0, 254, -13, 0, -13, 0,
ax_anim 2, 0, 254, 12, 0, 12, 0,
ax_anim 3, 0, 254, -12, 0, -12, 0,
ax_anim 2, 0, 254, 10, 0, 10, 0,
ax_anim 2, 0, 254, -10, 0, -10, 0,
ax_anim 2, 0, 254, 6, 0, 6, 0,
ax_anim 2, 0, 254, -6, 0, -6, 0,
ax_anim 2, 0, 254, 0, 0, 0, 0,
ax_anim_terminator
sCacneaAnims_10_2:
ax_anim 2, 0, 255, 0, 0, 0, 0,
ax_anim 2, 0, 255, 6, -6, 6, -6,
ax_anim 2, 0, 255, -6, 6, -6, 6,
ax_anim 2, 0, 255, 10, -10, 10, -10,
ax_anim 2, 0, 255, -10, 10, -10, 10,
ax_anim 2, 0, 255, 12, -12, 12, -12,
ax_anim 3, 0, 255, -12, 12, -12, 12,
ax_anim 3, 0, 255, 13, -13, 13, -13,
ax_anim 3, 0, 255, -13, 13, -13, 13,
ax_anim 2, 0, 255, 12, -12, 12, -12,
ax_anim 3, 0, 255, -12, 12, -12, 12,
ax_anim 2, 0, 255, 10, -10, 10, -10,
ax_anim 2, 0, 255, -10, 10, -10, 10,
ax_anim 2, 0, 255, 6, -6, 6, -6,
ax_anim 2, 0, 255, -6, 6, -6, 6,
ax_anim 2, 0, 255, 0, 0, 0, 0,
ax_anim_terminator
sCacneaAnims_10_3:
ax_anim 2, 0, 256, 0, 0, 0, 0,
ax_anim 2, 0, 256, 0, -6, 0, -6,
ax_anim 2, 0, 256, 0, 6, 0, 6,
ax_anim 2, 0, 256, 0, -10, 0, -10,
ax_anim 2, 0, 256, 0, 10, 0, 10,
ax_anim 2, 0, 256, 0, -12, 0, -12,
ax_anim 3, 0, 256, 0, 12, 0, 12,
ax_anim 3, 0, 256, 0, -13, 0, -13,
ax_anim 3, 0, 256, 0, 13, 0, 13,
ax_anim 2, 0, 256, 0, -12, 0, -12,
ax_anim 3, 0, 256, 0, 12, 0, 12,
ax_anim 2, 0, 256, 0, -10, 0, -10,
ax_anim 2, 0, 256, 0, 10, 0, 10,
ax_anim 2, 0, 256, 0, -6, 0, -6,
ax_anim 2, 0, 256, 0, 6, 0, 6,
ax_anim 2, 0, 256, 0, 0, 0, 0,
ax_anim_terminator
sCacneaAnims_10_4:
ax_anim 2, 0, 257, 0, 0, 0, 0,
ax_anim 2, 0, 257, -6, -6, -6, -6,
ax_anim 2, 0, 257, 6, 6, 6, 6,
ax_anim 2, 0, 257, -10, -10, -10, -10,
ax_anim 2, 0, 257, 10, 10, 10, 10,
ax_anim 2, 0, 257, -12, -12, -12, -12,
ax_anim 3, 0, 257, 12, 12, 12, 12,
ax_anim 3, 0, 257, -13, -13, -13, -13,
ax_anim 3, 0, 257, 13, 13, 13, 13,
ax_anim 2, 0, 257, -12, -12, -12, -12,
ax_anim 3, 0, 257, 12, 12, 12, 12,
ax_anim 2, 0, 257, -10, -10, -10, -10,
ax_anim 2, 0, 257, 10, 10, 10, 10,
ax_anim 2, 0, 257, -6, -6, -6, -6,
ax_anim 2, 0, 257, 6, 6, 6, 6,
ax_anim 2, 0, 257, 0, 0, 0, 0,
ax_anim_terminator
sCacneaAnims_10_5:
ax_anim 2, 0, 258, 0, 0, 0, 0,
ax_anim 2, 0, 258, 6, 0, 6, 0,
ax_anim 2, 0, 258, -6, 0, -6, 0,
ax_anim 2, 0, 258, 10, 0, 10, 0,
ax_anim 2, 0, 258, -10, 0, -10, 0,
ax_anim 2, 0, 258, 12, 0, 12, 0,
ax_anim 3, 0, 258, -12, 0, -12, 0,
ax_anim 3, 0, 258, 13, 0, 13, 0,
ax_anim 3, 0, 258, -13, 0, -13, 0,
ax_anim 2, 0, 258, 12, 0, 12, 0,
ax_anim 3, 0, 258, -12, 0, -12, 0,
ax_anim 2, 0, 258, 10, 0, 10, 0,
ax_anim 2, 0, 258, -10, 0, -10, 0,
ax_anim 2, 0, 258, 6, 0, 6, 0,
ax_anim 2, 0, 258, -6, 0, -6, 0,
ax_anim 2, 0, 258, 0, 0, 0, 0,
ax_anim_terminator
sCacneaAnims_10_6:
ax_anim 2, 0, 259, 0, 0, 0, 0,
ax_anim 2, 0, 259, 6, -6, 6, -6,
ax_anim 2, 0, 259, -6, 6, -6, 6,
ax_anim 2, 0, 259, 10, -10, 10, -10,
ax_anim 2, 0, 259, -10, 10, -10, 10,
ax_anim 2, 0, 259, 12, -12, 12, -12,
ax_anim 3, 0, 259, -12, 12, -12, 12,
ax_anim 3, 0, 259, 13, -13, 13, -13,
ax_anim 3, 0, 259, -13, 13, -13, 13,
ax_anim 2, 0, 259, 12, -12, 12, -12,
ax_anim 3, 0, 259, -12, 12, -12, 12,
ax_anim 2, 0, 259, 10, -10, 10, -10,
ax_anim 2, 0, 259, -10, 10, -10, 10,
ax_anim 2, 0, 259, 6, -6, 6, -6,
ax_anim 2, 0, 259, -6, 6, -6, 6,
ax_anim 2, 0, 259, 0, 0, 0, 0,
ax_anim_terminator
sCacneaAnims_10_7:
ax_anim 2, 0, 260, 0, 0, 0, 0,
ax_anim 2, 0, 260, 0, -6, 0, -6,
ax_anim 2, 0, 260, 0, 6, 0, 6,
ax_anim 2, 0, 260, 0, -10, 0, -10,
ax_anim 2, 0, 260, 0, 10, 0, 10,
ax_anim 2, 0, 260, 0, -12, 0, -12,
ax_anim 3, 0, 260, 0, 12, 0, 12,
ax_anim 3, 0, 260, 0, -13, 0, -13,
ax_anim 3, 0, 260, 0, 13, 0, 13,
ax_anim 2, 0, 260, 0, -12, 0, -12,
ax_anim 3, 0, 260, 0, 12, 0, 12,
ax_anim 2, 0, 260, 0, -10, 0, -10,
ax_anim 2, 0, 260, 0, 10, 0, 10,
ax_anim 2, 0, 260, 0, -6, 0, -6,
ax_anim 2, 0, 260, 0, 6, 0, 6,
ax_anim 2, 0, 260, 0, 0, 0, 0,
ax_anim_terminator
sCacneaAnims_10_8:
ax_anim 2, 0, 261, 0, 0, 0, 0,
ax_anim 2, 0, 261, -6, -6, -6, -6,
ax_anim 2, 0, 261, 6, 6, 6, 6,
ax_anim 2, 0, 261, -10, -10, -10, -10,
ax_anim 2, 0, 261, 10, 10, 10, 10,
ax_anim 2, 0, 261, -12, -12, -12, -12,
ax_anim 3, 0, 261, 12, 12, 12, 12,
ax_anim 3, 0, 261, -13, -13, -13, -13,
ax_anim 3, 0, 261, 13, 13, 13, 13,
ax_anim 2, 0, 261, -12, -12, -12, -12,
ax_anim 3, 0, 261, 12, 12, 12, 12,
ax_anim 2, 0, 261, -10, -10, -10, -10,
ax_anim 2, 0, 261, 10, 10, 10, 10,
ax_anim 2, 0, 261, -6, -6, -6, -6,
ax_anim 2, 0, 261, 6, 6, 6, 6,
ax_anim 2, 0, 261, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sCacneaAnims_11_1:
ax_anim 2, 0, 262, 0, 0, 0, 0,
ax_anim 1, 0, 263, 0, -10, 0, 0,
ax_anim 2, 0, 263, 0, -16, 0, 0,
ax_anim 3, 0, 263, 0, -20, 0, 0,
ax_anim 4, 0, 263, 0, -21, 0, 0,
ax_anim 4, 0, 262, 0, -23, 0, 0,
ax_anim 3, 0, 264, 0, -23, 0, 0,
ax_anim 2, 0, 264, 0, -18, 0, 0,
ax_anim 1, 0, 264, 0, -12, 0, 0,
ax_anim 2, 2, 264, 0, 0, 0, 0,
ax_anim_terminator
sCacneaAnims_11_2:
ax_anim 2, 0, 265, 0, 0, 0, 0,
ax_anim 1, 0, 266, 0, -10, 0, 0,
ax_anim 2, 0, 266, 0, -16, 0, 0,
ax_anim 3, 0, 266, 0, -20, 0, 0,
ax_anim 4, 0, 266, 0, -21, 0, 0,
ax_anim 4, 0, 265, 0, -23, 0, 0,
ax_anim 3, 0, 267, 0, -22, 0, 0,
ax_anim 2, 0, 267, 0, -18, 0, 0,
ax_anim 1, 0, 267, 0, -12, 0, 0,
ax_anim 2, 2, 267, 0, 0, 0, 0,
ax_anim_terminator
sCacneaAnims_11_3:
ax_anim 2, 0, 268, 0, 0, 0, 0,
ax_anim 1, 0, 269, 0, -10, 0, 0,
ax_anim 2, 0, 269, 0, -16, 0, 0,
ax_anim 3, 0, 269, 0, -20, 0, 0,
ax_anim 4, 0, 269, 0, -21, 0, 0,
ax_anim 4, 0, 268, 0, -22, 0, 0,
ax_anim 3, 0, 270, 0, -21, 0, 0,
ax_anim 2, 0, 270, 0, -18, 0, 0,
ax_anim 1, 0, 270, 0, -12, 0, 0,
ax_anim 2, 2, 270, 0, 0, 0, 0,
ax_anim_terminator
sCacneaAnims_11_4:
ax_anim 2, 0, 271, 0, 0, 0, 0,
ax_anim 1, 0, 272, 0, -10, 0, 0,
ax_anim 2, 0, 272, 0, -16, 0, 0,
ax_anim 3, 0, 272, 0, -20, 0, 0,
ax_anim 4, 0, 272, 0, -21, 0, 0,
ax_anim 4, 0, 271, 0, -22, 0, 0,
ax_anim 3, 0, 273, 0, -21, 0, 0,
ax_anim 2, 0, 273, 0, -17, 0, 0,
ax_anim 1, 0, 273, 0, -11, 0, 0,
ax_anim 2, 2, 273, 0, 0, 0, 0,
ax_anim_terminator
sCacneaAnims_11_5:
ax_anim 2, 0, 274, 0, 0, 0, 0,
ax_anim 1, 0, 275, 0, -10, 0, 0,
ax_anim 2, 0, 275, 0, -16, 0, 0,
ax_anim 3, 0, 275, 0, -20, 0, 0,
ax_anim 4, 0, 275, 0, -21, 0, 0,
ax_anim 4, 0, 274, 0, -22, 0, 0,
ax_anim 3, 0, 276, 0, -21, 0, 0,
ax_anim 2, 0, 276, 0, -18, 0, 0,
ax_anim 1, 0, 276, 0, -12, 0, 0,
ax_anim 2, 2, 276, 0, 0, 0, 0,
ax_anim_terminator
sCacneaAnims_11_6:
ax_anim 2, 0, 277, 0, 0, 0, 0,
ax_anim 1, 0, 278, 0, -10, 0, 0,
ax_anim 2, 0, 278, 0, -16, 0, 0,
ax_anim 3, 0, 278, 0, -20, 0, 0,
ax_anim 4, 0, 278, 0, -21, 0, 0,
ax_anim 4, 0, 277, 0, -22, 0, 0,
ax_anim 3, 0, 279, 0, -21, 0, 0,
ax_anim 2, 0, 279, 0, -17, 0, 0,
ax_anim 1, 0, 279, 0, -11, 0, 0,
ax_anim 2, 2, 279, 0, 0, 0, 0,
ax_anim_terminator
sCacneaAnims_11_7:
ax_anim 2, 0, 280, 0, 0, 0, 0,
ax_anim 1, 0, 281, 0, -10, 0, 0,
ax_anim 2, 0, 281, 0, -16, 0, 0,
ax_anim 3, 0, 281, 0, -20, 0, 0,
ax_anim 4, 0, 281, 0, -21, 0, 0,
ax_anim 4, 0, 280, 0, -22, 0, 0,
ax_anim 3, 0, 282, 0, -21, 0, 0,
ax_anim 2, 0, 282, 0, -18, 0, 0,
ax_anim 1, 0, 282, 0, -12, 0, 0,
ax_anim 2, 2, 282, 0, 0, 0, 0,
ax_anim_terminator
sCacneaAnims_11_8:
ax_anim 2, 0, 283, 0, 0, 0, 0,
ax_anim 1, 0, 284, 0, -10, 0, 0,
ax_anim 2, 0, 284, 0, -16, 0, 0,
ax_anim 3, 0, 284, 0, -20, 0, 0,
ax_anim 4, 0, 284, 0, -21, 0, 0,
ax_anim 4, 0, 283, 0, -23, 0, 0,
ax_anim 3, 0, 285, 0, -22, 0, 0,
ax_anim 2, 0, 285, 0, -18, 0, 0,
ax_anim 1, 0, 285, 0, -12, 0, 0,
ax_anim 2, 2, 285, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sCacneaAnims_12_1:
ax_anim 2, 0, 286, 1, 0, 1, 0,
ax_anim 2, 0, 286, 0, 0, 0, 0,
ax_anim 2, 0, 286, 1, 0, 1, 0,
ax_anim 2, 0, 286, 0, 0, 0, 0,
ax_anim 2, 0, 286, 1, 0, 1, 0,
ax_anim 2, 2, 286, 0, 0, 0, 0,
ax_anim 2, 0, 286, 1, 0, 1, 0,
ax_anim 2, 0, 286, 0, 0, 0, 0,
ax_anim 2, 0, 286, 1, 0, 1, 0,
ax_anim 2, 1, 286, 0, 0, 0, 0,
ax_anim_terminator
sCacneaAnims_12_2:
ax_anim 2, 0, 293, 1, -1, 1, -1,
ax_anim 2, 0, 293, 0, 0, 0, 0,
ax_anim 2, 0, 293, 1, -1, 1, -1,
ax_anim 2, 0, 293, 0, 0, 0, 0,
ax_anim 2, 0, 293, 1, -1, 1, -1,
ax_anim 2, 2, 293, 0, 0, 0, 0,
ax_anim 2, 0, 293, 1, -1, 1, -1,
ax_anim 2, 0, 293, 0, 0, 0, 0,
ax_anim 2, 0, 293, 1, -1, 1, -1,
ax_anim 2, 1, 293, 0, 0, 0, 0,
ax_anim_terminator
sCacneaAnims_12_3:
ax_anim 2, 0, 292, 0, -1, 0, -1,
ax_anim 2, 0, 292, 0, 0, 0, 0,
ax_anim 2, 0, 292, 0, -1, 0, -1,
ax_anim 2, 0, 292, 0, 0, 0, 0,
ax_anim 2, 0, 292, 0, -1, 0, -1,
ax_anim 2, 2, 292, 0, 0, 0, 0,
ax_anim 2, 0, 292, 0, -1, 0, -1,
ax_anim 2, 0, 292, 0, 0, 0, 0,
ax_anim 2, 0, 292, 0, -1, 0, -1,
ax_anim 2, 1, 292, 0, 0, 0, 0,
ax_anim_terminator
sCacneaAnims_12_4:
ax_anim 2, 0, 291, -1, -1, -1, -1,
ax_anim 2, 0, 291, 0, 0, 0, 0,
ax_anim 2, 0, 291, -1, -1, -1, -1,
ax_anim 2, 0, 291, 0, 0, 0, 0,
ax_anim 2, 0, 291, -1, -1, -1, -1,
ax_anim 2, 2, 291, 0, 0, 0, 0,
ax_anim 2, 0, 291, -1, -1, -1, -1,
ax_anim 2, 0, 291, 0, 0, 0, 0,
ax_anim 2, 0, 291, -1, -1, -1, -1,
ax_anim 2, 1, 291, 0, 0, 0, 0,
ax_anim_terminator
sCacneaAnims_12_5:
ax_anim 2, 0, 290, 1, 0, 1, 0,
ax_anim 2, 0, 290, 0, 0, 0, 0,
ax_anim 2, 0, 290, 1, 0, 1, 0,
ax_anim 2, 0, 290, 0, 0, 0, 0,
ax_anim 2, 0, 290, 1, 0, 1, 0,
ax_anim 2, 2, 290, 0, 0, 0, 0,
ax_anim 2, 0, 290, 1, 0, 1, 0,
ax_anim 2, 0, 290, 0, 0, 0, 0,
ax_anim 2, 0, 290, 1, 0, 1, 0,
ax_anim 2, 1, 290, 0, 0, 0, 0,
ax_anim_terminator
sCacneaAnims_12_6:
ax_anim 2, 0, 289, 1, -1, 1, -1,
ax_anim 2, 0, 289, 0, 0, 0, 0,
ax_anim 2, 0, 289, 1, -1, 1, -1,
ax_anim 2, 0, 289, 0, 0, 0, 0,
ax_anim 2, 0, 289, 1, -1, 1, -1,
ax_anim 2, 2, 289, 0, 0, 0, 0,
ax_anim 2, 0, 289, 1, -1, 1, -1,
ax_anim 2, 0, 289, 0, 0, 0, 0,
ax_anim 2, 0, 289, 1, -1, 1, -1,
ax_anim 2, 1, 289, 0, 0, 0, 0,
ax_anim_terminator
sCacneaAnims_12_7:
ax_anim 2, 0, 288, 0, -1, 0, -1,
ax_anim 2, 0, 288, 0, 0, 0, 0,
ax_anim 2, 0, 288, 0, -1, 0, -1,
ax_anim 2, 0, 288, 0, 0, 0, 0,
ax_anim 2, 0, 288, 0, -1, 0, -1,
ax_anim 2, 2, 288, 0, 0, 0, 0,
ax_anim 2, 0, 288, 0, -1, 0, -1,
ax_anim 2, 0, 288, 0, 0, 0, 0,
ax_anim 2, 0, 288, 0, -1, 0, -1,
ax_anim 2, 1, 288, 0, 0, 0, 0,
ax_anim_terminator
sCacneaAnims_12_8:
ax_anim 2, 0, 287, -1, -1, -1, -1,
ax_anim 2, 0, 287, 0, 0, 0, 0,
ax_anim 2, 0, 287, -1, -1, -1, -1,
ax_anim 2, 0, 287, 0, 0, 0, 0,
ax_anim 2, 0, 287, -1, -1, -1, -1,
ax_anim 2, 2, 287, 0, 0, 0, 0,
ax_anim 2, 0, 287, -1, -1, -1, -1,
ax_anim 2, 0, 287, 0, 0, 0, 0,
ax_anim 2, 0, 287, -1, -1, -1, -1,
ax_anim 2, 1, 287, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sCacneaAnims_13_1:
ax_anim 2, 0, 294, 0, 0, 0, 0,
ax_anim 2, 0, 295, 0, 0, 0, 0,
ax_anim 2, 0, 296, 0, 0, 0, 0,
ax_anim 2, 0, 297, 0, 0, 0, 0,
ax_anim 2, 0, 298, 0, 0, 0, 0,
ax_anim 2, 0, 299, 0, 0, 0, 0,
ax_anim 2, 0, 300, 0, 0, 0, 0,
ax_anim 2, 0, 301, 0, 0, 0, 0,
ax_anim 2, 2, 294, 0, 0, 0, 0,
ax_anim_terminator
sCacneaAnims_13_2:
ax_anim 2, 0, 301, 0, 0, 0, 0,
ax_anim 2, 0, 294, 0, 0, 0, 0,
ax_anim 2, 0, 295, 0, 0, 0, 0,
ax_anim 2, 0, 296, 0, 0, 0, 0,
ax_anim 2, 0, 297, 0, 0, 0, 0,
ax_anim 2, 0, 298, 0, 0, 0, 0,
ax_anim 2, 0, 299, 0, 0, 0, 0,
ax_anim 2, 0, 300, 0, 0, 0, 0,
ax_anim 2, 2, 301, 0, 0, 0, 0,
ax_anim_terminator
sCacneaAnims_13_3:
ax_anim 2, 0, 300, 0, 0, 0, 0,
ax_anim 2, 0, 301, 0, 0, 0, 0,
ax_anim 2, 0, 294, 0, 0, 0, 0,
ax_anim 2, 0, 295, 0, 0, 0, 0,
ax_anim 2, 0, 296, 0, 0, 0, 0,
ax_anim 2, 0, 297, 0, 0, 0, 0,
ax_anim 2, 0, 298, 0, 0, 0, 0,
ax_anim 2, 0, 299, 0, 0, 0, 0,
ax_anim 2, 2, 300, 0, 0, 0, 0,
ax_anim_terminator
sCacneaAnims_13_4:
ax_anim 2, 0, 299, 0, 0, 0, 0,
ax_anim 2, 0, 300, 0, 0, 0, 0,
ax_anim 2, 0, 301, 0, 0, 0, 0,
ax_anim 2, 0, 294, 0, 0, 0, 0,
ax_anim 2, 0, 295, 0, 0, 0, 0,
ax_anim 2, 0, 296, 0, 0, 0, 0,
ax_anim 2, 0, 297, 0, 0, 0, 0,
ax_anim 2, 0, 298, 0, 0, 0, 0,
ax_anim 2, 2, 299, 0, 0, 0, 0,
ax_anim_terminator
sCacneaAnims_13_5:
ax_anim 2, 0, 298, 0, 0, 0, 0,
ax_anim 2, 0, 299, 0, 0, 0, 0,
ax_anim 2, 0, 300, 0, 0, 0, 0,
ax_anim 2, 0, 301, 0, 0, 0, 0,
ax_anim 2, 0, 294, 0, 0, 0, 0,
ax_anim 2, 0, 295, 0, 0, 0, 0,
ax_anim 2, 0, 296, 0, 0, 0, 0,
ax_anim 2, 0, 297, 0, 0, 0, 0,
ax_anim 2, 2, 298, 0, 0, 0, 0,
ax_anim_terminator
sCacneaAnims_13_6:
ax_anim 2, 0, 297, 0, 0, 0, 0,
ax_anim 2, 0, 298, 0, 0, 0, 0,
ax_anim 2, 0, 299, 0, 0, 0, 0,
ax_anim 2, 0, 300, 0, 0, 0, 0,
ax_anim 2, 0, 301, 0, 0, 0, 0,
ax_anim 2, 0, 294, 0, 0, 0, 0,
ax_anim 2, 0, 295, 0, 0, 0, 0,
ax_anim 2, 0, 296, 0, 0, 0, 0,
ax_anim 2, 2, 297, 0, 0, 0, 0,
ax_anim_terminator
sCacneaAnims_13_7:
ax_anim 2, 0, 296, 0, 0, 0, 0,
ax_anim 2, 0, 297, 0, 0, 0, 0,
ax_anim 2, 0, 298, 0, 0, 0, 0,
ax_anim 2, 0, 299, 0, 0, 0, 0,
ax_anim 2, 0, 300, 0, 0, 0, 0,
ax_anim 2, 0, 301, 0, 0, 0, 0,
ax_anim 2, 0, 294, 0, 0, 0, 0,
ax_anim 2, 0, 295, 0, 0, 0, 0,
ax_anim 2, 2, 296, 0, 0, 0, 0,
ax_anim_terminator
sCacneaAnims_13_8:
ax_anim 2, 0, 295, 0, 0, 0, 0,
ax_anim 2, 0, 296, 0, 0, 0, 0,
ax_anim 2, 0, 297, 0, 0, 0, 0,
ax_anim 2, 0, 298, 0, 0, 0, 0,
ax_anim 2, 0, 299, 0, 0, 0, 0,
ax_anim 2, 0, 300, 0, 0, 0, 0,
ax_anim 2, 0, 301, 0, 0, 0, 0,
ax_anim 2, 0, 294, 0, 0, 0, 0,
ax_anim 2, 2, 295, 0, 0, 0, 0,
ax_anim_terminator
sCacneaGfx1:
.incbin "baserom.gba", 0x138283C, 0x200
sCacneaSprites1:
ax_sprite sCacneaGfx1, 0x200
ax_sprite_terminator
sCacneaGfx2:
.incbin "baserom.gba", 0x1382A4C, 0x200
sCacneaSprites2:
ax_sprite sCacneaGfx2, 0x200
ax_sprite_terminator
sCacneaGfx3:
.incbin "baserom.gba", 0x1382C5C, 0x200
sCacneaSprites3:
ax_sprite sCacneaGfx3, 0x200
ax_sprite_terminator
sCacneaGfx4:
.incbin "baserom.gba", 0x1382E6C, 0x200
sCacneaSprites4:
ax_sprite sCacneaGfx4, 0x200
ax_sprite_terminator
sCacneaGfx5:
.incbin "baserom.gba", 0x138307C, 0x200
sCacneaSprites5:
ax_sprite sCacneaGfx5, 0x200
ax_sprite_terminator
sCacneaGfx6:
.incbin "baserom.gba", 0x138328C, 0x200
sCacneaSprites6:
ax_sprite sCacneaGfx6, 0x200
ax_sprite_terminator
sCacneaGfx7:
.incbin "baserom.gba", 0x138349C, 0x200
sCacneaSprites7:
ax_sprite sCacneaGfx7, 0x200
ax_sprite_terminator
sCacneaGfx8:
.incbin "baserom.gba", 0x13836AC, 0x200
sCacneaSprites8:
ax_sprite sCacneaGfx8, 0x200
ax_sprite_terminator
sCacneaGfx9:
.incbin "baserom.gba", 0x13838BC, 0x200
sCacneaSprites9:
ax_sprite sCacneaGfx9, 0x200
ax_sprite_terminator
sCacneaGfx10:
.incbin "baserom.gba", 0x1383ACC, 0x200
sCacneaSprites10:
ax_sprite sCacneaGfx10, 0x200
ax_sprite_terminator
sCacneaGfx11:
.incbin "baserom.gba", 0x1383CDC, 0x200
sCacneaSprites11:
ax_sprite sCacneaGfx11, 0x200
ax_sprite_terminator
sCacneaGfx12:
.incbin "baserom.gba", 0x1383EEC, 0x200
sCacneaSprites12:
ax_sprite sCacneaGfx12, 0x200
ax_sprite_terminator
sCacneaGfx13:
.incbin "baserom.gba", 0x13840FC, 0x200
sCacneaSprites13:
ax_sprite sCacneaGfx13, 0x200
ax_sprite_terminator
sCacneaGfx14:
.incbin "baserom.gba", 0x138430C, 0x200
sCacneaSprites14:
ax_sprite sCacneaGfx14, 0x200
ax_sprite_terminator
sCacneaGfx15:
.incbin "baserom.gba", 0x138451C, 0x200
sCacneaSprites15:
ax_sprite sCacneaGfx15, 0x200
ax_sprite_terminator
sCacneaGfx16:
.incbin "baserom.gba", 0x138472C, 0x60
sCacneaGfx16_1:
.incbin "baserom.gba", 0x138478C, 0x80
sCacneaGfx16_2:
.incbin "baserom.gba", 0x138480C, 0x40
sCacneaSprites16:
ax_sprite sCacneaGfx16, 0x60
ax_sprite 0, 0x20
ax_sprite sCacneaGfx16_1, 0x80
ax_sprite 0, 0x20
ax_sprite sCacneaGfx16_2, 0x40
ax_sprite 0, 0xa0
ax_sprite_terminator
sCacneaGfx17:
.incbin "baserom.gba", 0x1384884, 0x60
sCacneaGfx17_1:
.incbin "baserom.gba", 0x13848E4, 0x60
sCacneaGfx17_2:
.incbin "baserom.gba", 0x1384944, 0x60
sCacneaSprites17:
ax_sprite 0, 0x20
ax_sprite sCacneaGfx17, 0x60
ax_sprite 0, 0x20
ax_sprite sCacneaGfx17_1, 0x60
ax_sprite 0, 0x20
ax_sprite sCacneaGfx17_2, 0x60
ax_sprite 0, 0x80
ax_sprite_terminator
sCacneaGfx18:
.incbin "baserom.gba", 0x13849E4, 0x60
sCacneaGfx18_1:
.incbin "baserom.gba", 0x1384A44, 0x60
sCacneaGfx18_2:
.incbin "baserom.gba", 0x1384AA4, 0x40
sCacneaSprites18:
ax_sprite sCacneaGfx18, 0x60
ax_sprite 0, 0x20
ax_sprite sCacneaGfx18_1, 0x60
ax_sprite 0, 0x40
ax_sprite sCacneaGfx18_2, 0x40
ax_sprite 0, 0xa0
ax_sprite_terminator
sCacneaGfx19:
.incbin "baserom.gba", 0x1384B1C, 0x100
sCacneaGfx19_1:
.incbin "baserom.gba", 0x1384C1C, 0x60
sCacneaSprites19:
ax_sprite sCacneaGfx19, 0x100
ax_sprite 0, 0x20
ax_sprite sCacneaGfx19_1, 0x60
ax_sprite 0, 0x80
ax_sprite_terminator
sCacneaGfx20:
.incbin "baserom.gba", 0x1384CA4, 0x40
sCacneaGfx20_1:
.incbin "baserom.gba", 0x1384CE4, 0x60
sCacneaGfx20_2:
.incbin "baserom.gba", 0x1384D44, 0x60
sCacneaSprites20:
ax_sprite 0, 0x20
ax_sprite sCacneaGfx20, 0x40
ax_sprite 0, 0x40
ax_sprite sCacneaGfx20_1, 0x60
ax_sprite 0, 0x20
ax_sprite sCacneaGfx20_2, 0x60
ax_sprite 0, 0x80
ax_sprite_terminator
sCacneaGfx21:
.incbin "baserom.gba", 0x1384DE4, 0x60
sCacneaGfx21_1:
.incbin "baserom.gba", 0x1384E44, 0x60
sCacneaGfx21_2:
.incbin "baserom.gba", 0x1384EA4, 0x60
sCacneaSprites21:
ax_sprite sCacneaGfx21, 0x60
ax_sprite 0, 0x20
ax_sprite sCacneaGfx21_1, 0x60
ax_sprite 0, 0x20
ax_sprite sCacneaGfx21_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sCacneaGfx22:
.incbin "baserom.gba", 0x1384F3C, 0x60
sCacneaGfx22_1:
.incbin "baserom.gba", 0x1384F9C, 0x60
sCacneaGfx22_2:
.incbin "baserom.gba", 0x1384FFC, 0x60
sCacneaSprites22:
ax_sprite sCacneaGfx22, 0x60
ax_sprite 0, 0x20
ax_sprite sCacneaGfx22_1, 0x60
ax_sprite 0, 0x20
ax_sprite sCacneaGfx22_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sCacneaGfx23:
.incbin "baserom.gba", 0x1385094, 0x40
sCacneaGfx23_1:
.incbin "baserom.gba", 0x13850D4, 0xE0
sCacneaGfx23_2:
.incbin "baserom.gba", 0x13851B4, 0x20
sCacneaSprites23:
ax_sprite 0, 0x20
ax_sprite sCacneaGfx23, 0x40
ax_sprite 0, 0x40
ax_sprite sCacneaGfx23_1, 0xe0
ax_sprite 0, 0x20
ax_sprite sCacneaGfx23_2, 0x20
ax_sprite 0, 0x40
ax_sprite_terminator
sCacneaGfx24:
.incbin "baserom.gba", 0x1385214, 0x60
sCacneaGfx24_1:
.incbin "baserom.gba", 0x1385274, 0x60
sCacneaGfx24_2:
.incbin "baserom.gba", 0x13852D4, 0x60
sCacneaSprites24:
ax_sprite sCacneaGfx24, 0x60
ax_sprite 0, 0x20
ax_sprite sCacneaGfx24_1, 0x60
ax_sprite 0, 0x20
ax_sprite sCacneaGfx24_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sCacneaGfx25:
.incbin "baserom.gba", 0x138536C, 0x60
sCacneaGfx25_1:
.incbin "baserom.gba", 0x13853CC, 0x100
sCacneaSprites25:
ax_sprite sCacneaGfx25, 0x60
ax_sprite 0, 0x20
ax_sprite sCacneaGfx25_1, 0x100
ax_sprite 0, 0x80
ax_sprite_terminator
sCacneaGfx26:
.incbin "baserom.gba", 0x13854F4, 0x40
sCacneaGfx26_1:
.incbin "baserom.gba", 0x1385534, 0x100
sCacneaSprites26:
ax_sprite 0, 0x20
ax_sprite sCacneaGfx26, 0x40
ax_sprite 0, 0x20
ax_sprite sCacneaGfx26_1, 0x100
ax_sprite 0, 0x80
ax_sprite_terminator
sCacneaGfx27:
.incbin "baserom.gba", 0x1385664, 0x100
sCacneaGfx27_1:
.incbin "baserom.gba", 0x1385764, 0x40
sCacneaSprites27:
ax_sprite sCacneaGfx27, 0x100
ax_sprite 0, 0x20
ax_sprite sCacneaGfx27_1, 0x40
ax_sprite 0, 0xa0
ax_sprite_terminator
sCacneaGfx28:
.incbin "baserom.gba", 0x13857CC, 0x160
sCacneaSprites28:
ax_sprite sCacneaGfx28, 0x160
ax_sprite 0, 0xa0
ax_sprite_terminator
sCacneaGfx29:
.incbin "baserom.gba", 0x1385944, 0x40
sCacneaGfx29_1:
.incbin "baserom.gba", 0x1385984, 0x100
sCacneaSprites29:
ax_sprite 0, 0x20
ax_sprite sCacneaGfx29, 0x40
ax_sprite 0, 0x20
ax_sprite sCacneaGfx29_1, 0x100
ax_sprite 0, 0x80
ax_sprite_terminator
sCacneaGfx30:
.incbin "baserom.gba", 0x1385AB4, 0x40
sCacneaGfx30_1:
.incbin "baserom.gba", 0x1385AF4, 0x120
sCacneaGfx30_2:
.incbin "baserom.gba", 0x1385C14, 0x20
sCacneaSprites30:
ax_sprite 0, 0x20
ax_sprite sCacneaGfx30, 0x40
ax_sprite 0, 0x20
ax_sprite sCacneaGfx30_1, 0x120
ax_sprite 0, 0x40
ax_sprite sCacneaGfx30_2, 0x20
ax_sprite_terminator
sCacneaGfx31:
.incbin "baserom.gba", 0x1385C6C, 0x80
sCacneaSprites31:
ax_sprite sCacneaGfx31, 0x80
ax_sprite_terminator
sCacneaGfx32:
.incbin "baserom.gba", 0x1385CFC, 0x80
sCacneaSprites32:
ax_sprite sCacneaGfx32, 0x80
ax_sprite_terminator
sCacneaGfx33:
.incbin "baserom.gba", 0x1385D8C, 0x80
sCacneaSprites33:
ax_sprite sCacneaGfx33, 0x80
ax_sprite_terminator
sCacneaGfx34:
.incbin "baserom.gba", 0x1385E1C, 0x80
sCacneaSprites34:
ax_sprite sCacneaGfx34, 0x80
ax_sprite_terminator
sCacneaGfx35:
.incbin "baserom.gba", 0x1385EAC, 0x80
sCacneaSprites35:
ax_sprite sCacneaGfx35, 0x80
ax_sprite_terminator
sCacneaGfx36:
.incbin "baserom.gba", 0x1385F3C, 0x80
sCacneaSprites36:
ax_sprite sCacneaGfx36, 0x80
ax_sprite_terminator
sCacneaGfx37:
.incbin "baserom.gba", 0x1385FCC, 0x80
sCacneaSprites37:
ax_sprite sCacneaGfx37, 0x80
ax_sprite_terminator
sCacneaGfx38:
.incbin "baserom.gba", 0x138605C, 0x200
sCacneaSprites38:
ax_sprite sCacneaGfx38, 0x200
ax_sprite_terminator
sCacneaGfx39:
.incbin "baserom.gba", 0x138626C, 0x200
sCacneaSprites39:
ax_sprite sCacneaGfx39, 0x200
ax_sprite_terminator
sCacneaGfx40:
.incbin "baserom.gba", 0x138647C, 0x200
sCacneaSprites40:
ax_sprite sCacneaGfx40, 0x200
ax_sprite_terminator
sCacneaGfx41:
.incbin "baserom.gba", 0x138668C, 0x200
sCacneaSprites41:
ax_sprite sCacneaGfx41, 0x200
ax_sprite_terminator
sCacneaGfx42:
.incbin "baserom.gba", 0x138689C, 0x200
sCacneaSprites42:
ax_sprite sCacneaGfx42, 0x200
ax_sprite_terminator
sCacneaGfx43:
.incbin "baserom.gba", 0x1386AAC, 0x200
sCacneaSprites43:
ax_sprite sCacneaGfx43, 0x200
ax_sprite_terminator
sCacneaGfx44:
.incbin "baserom.gba", 0x1386CBC, 0x200
sCacneaSprites44:
ax_sprite sCacneaGfx44, 0x200
ax_sprite_terminator
sAxPosesCacnea:
.4byte sCacneaPose1
.4byte sCacneaPose2
.4byte sCacneaPose3
.4byte sCacneaPose4
.4byte sCacneaPose5
.4byte sCacneaPose6
.4byte sCacneaPose7
.4byte sCacneaPose8
.4byte sCacneaPose9
.4byte sCacneaPose10
.4byte sCacneaPose11
.4byte sCacneaPose12
.4byte sCacneaPose13
.4byte sCacneaPose14
.4byte sCacneaPose15
.4byte sCacneaPose16
.4byte sCacneaPose17
.4byte sCacneaPose18
.4byte sCacneaPose19
.4byte sCacneaPose20
.4byte sCacneaPose21
.4byte sCacneaPose22
.4byte sCacneaPose23
.4byte sCacneaPose24
.4byte sCacneaPose25
.4byte sCacneaPose26
.4byte sCacneaPose27
.4byte sCacneaPose28
.4byte sCacneaPose29
.4byte sCacneaPose30
.4byte sCacneaPose31
.4byte sCacneaPose32
.4byte sCacneaPose33
.4byte sCacneaPose34
.4byte sCacneaPose35
.4byte sCacneaPose36
.4byte sCacneaPose37
.4byte sCacneaPose38
.4byte sCacneaPose39
.4byte sCacneaPose40
.4byte sCacneaPose41
.4byte sCacneaPose42
.4byte sCacneaPose43
.4byte sCacneaPose44
.4byte sCacneaPose45
.4byte sCacneaPose46
.4byte sCacneaPose47
.4byte sCacneaPose48
.4byte sCacneaPose49
.4byte sCacneaPose50
.4byte sCacneaPose51
.4byte sCacneaPose52
.4byte sCacneaPose53
.4byte sCacneaPose54
.4byte sCacneaPose55
.4byte sCacneaPose56
.4byte sCacneaPose57
.4byte sCacneaPose58
.4byte sCacneaPose59
.4byte sCacneaPose60
.4byte sCacneaPose61
.4byte sCacneaPose62
.4byte sCacneaPose63
.4byte sCacneaPose64
.4byte sCacneaPose65
.4byte sCacneaPose66
.4byte sCacneaPose67
.4byte sCacneaPose68
.4byte sCacneaPose69
.4byte sCacneaPose70
.4byte sCacneaPose71
.4byte sCacneaPose72
.4byte sCacneaPose73
.4byte sCacneaPose74
.4byte sCacneaPose75
.4byte sCacneaPose76
.4byte sCacneaPose77
.4byte sCacneaPose78
.4byte sCacneaPose79
.4byte sCacneaPose80
.4byte sCacneaPose81
.4byte sCacneaPose82
.4byte sCacneaPose83
.4byte sCacneaPose84
.4byte sCacneaPose85
.4byte sCacneaPose86
.4byte sCacneaPose87
.4byte sCacneaPose88
.4byte sCacneaPose89
.4byte sCacneaPose90
.4byte sCacneaPose91
.4byte sCacneaPose92
.4byte sCacneaPose93
.4byte sCacneaPose94
.4byte sCacneaPose95
.4byte sCacneaPose96
.4byte sCacneaPose97
.4byte sCacneaPose98
.4byte sCacneaPose99
.4byte sCacneaPose100
.4byte sCacneaPose101
.4byte sCacneaPose102
.4byte sCacneaPose103
.4byte sCacneaPose104
.4byte sCacneaPose105
.4byte sCacneaPose106
.4byte sCacneaPose107
.4byte sCacneaPose108
.4byte sCacneaPose109
.4byte sCacneaPose110
.4byte sCacneaPose111
.4byte sCacneaPose112
.4byte sCacneaPose113
.4byte sCacneaPose114
.4byte sCacneaPose115
.4byte sCacneaPose116
.4byte sCacneaPose117
.4byte sCacneaPose118
.4byte sCacneaPose119
.4byte sCacneaPose120
.4byte sCacneaPose121
.4byte sCacneaPose122
.4byte sCacneaPose123
.4byte sCacneaPose124
.4byte sCacneaPose125
.4byte sCacneaPose126
.4byte sCacneaPose127
.4byte sCacneaPose128
.4byte sCacneaPose129
.4byte sCacneaPose130
.4byte sCacneaPose131
.4byte sCacneaPose132
.4byte sCacneaPose133
.4byte sCacneaPose134
.4byte sCacneaPose135
.4byte sCacneaPose136
.4byte sCacneaPose137
.4byte sCacneaPose138
.4byte sCacneaPose139
.4byte sCacneaPose140
.4byte sCacneaPose141
.4byte sCacneaPose142
.4byte sCacneaPose143
.4byte sCacneaPose144
.4byte sCacneaPose145
.4byte sCacneaPose146
.4byte sCacneaPose147
.4byte sCacneaPose148
.4byte sCacneaPose149
.4byte sCacneaPose150
.4byte sCacneaPose151
.4byte sCacneaPose152
.4byte sCacneaPose153
.4byte sCacneaPose154
.4byte sCacneaPose155
.4byte sCacneaPose156
.4byte sCacneaPose157
.4byte sCacneaPose158
.4byte sCacneaPose159
.4byte sCacneaPose160
.4byte sCacneaPose161
.4byte sCacneaPose162
.4byte sCacneaPose163
.4byte sCacneaPose164
.4byte sCacneaPose165
.4byte sCacneaPose166
.4byte sCacneaPose167
.4byte sCacneaPose168
.4byte sCacneaPose169
.4byte sCacneaPose170
.4byte sCacneaPose171
.4byte sCacneaPose172
.4byte sCacneaPose173
.4byte sCacneaPose174
.4byte sCacneaPose175
.4byte sCacneaPose176
.4byte sCacneaPose177
.4byte sCacneaPose178
.4byte sCacneaPose179
.4byte sCacneaPose180
.4byte sCacneaPose181
.4byte sCacneaPose182
.4byte sCacneaPose183
.4byte sCacneaPose184
.4byte sCacneaPose185
.4byte sCacneaPose186
.4byte sCacneaPose187
.4byte sCacneaPose188
.4byte sCacneaPose189
.4byte sCacneaPose190
.4byte sCacneaPose191
.4byte sCacneaPose192
.4byte sCacneaPose193
.4byte sCacneaPose194
.4byte sCacneaPose195
.4byte sCacneaPose196
.4byte sCacneaPose197
.4byte sCacneaPose198
.4byte sCacneaPose199
.4byte sCacneaPose200
.4byte sCacneaPose201
.4byte sCacneaPose202
.4byte sCacneaPose203
.4byte sCacneaPose204
.4byte sCacneaPose205
.4byte sCacneaPose206
.4byte sCacneaPose207
.4byte sCacneaPose208
.4byte sCacneaPose209
.4byte sCacneaPose210
.4byte sCacneaPose211
.4byte sCacneaPose212
.4byte sCacneaPose213
.4byte sCacneaPose214
.4byte sCacneaPose215
.4byte sCacneaPose216
.4byte sCacneaPose217
.4byte sCacneaPose218
.4byte sCacneaPose219
.4byte sCacneaPose220
.4byte sCacneaPose221
.4byte sCacneaPose222
.4byte sCacneaPose223
.4byte sCacneaPose224
.4byte sCacneaPose225
.4byte sCacneaPose226
.4byte sCacneaPose227
.4byte sCacneaPose228
.4byte sCacneaPose229
.4byte sCacneaPose230
.4byte sCacneaPose231
.4byte sCacneaPose232
.4byte sCacneaPose233
.4byte sCacneaPose234
.4byte sCacneaPose235
.4byte sCacneaPose236
.4byte sCacneaPose237
.4byte sCacneaPose238
.4byte sCacneaPose239
.4byte sCacneaPose240
.4byte sCacneaPose241
.4byte sCacneaPose242
.4byte sCacneaPose243
.4byte sCacneaPose244
.4byte sCacneaPose245
.4byte sCacneaPose246
.4byte sCacneaPose247
.4byte sCacneaPose248
.4byte sCacneaPose249
.4byte sCacneaPose250
.4byte sCacneaPose251
.4byte sCacneaPose252
.4byte sCacneaPose253
.4byte sCacneaPose254
.4byte sCacneaPose255
.4byte sCacneaPose256
.4byte sCacneaPose257
.4byte sCacneaPose258
.4byte sCacneaPose259
.4byte sCacneaPose260
.4byte sCacneaPose261
.4byte sCacneaPose262
.4byte sCacneaPose263
.4byte sCacneaPose264
.4byte sCacneaPose265
.4byte sCacneaPose266
.4byte sCacneaPose267
.4byte sCacneaPose268
.4byte sCacneaPose269
.4byte sCacneaPose270
.4byte sCacneaPose271
.4byte sCacneaPose272
.4byte sCacneaPose273
.4byte sCacneaPose274
.4byte sCacneaPose275
.4byte sCacneaPose276
.4byte sCacneaPose277
.4byte sCacneaPose278
.4byte sCacneaPose279
.4byte sCacneaPose280
.4byte sCacneaPose281
.4byte sCacneaPose282
.4byte sCacneaPose283
.4byte sCacneaPose284
.4byte sCacneaPose285
.4byte sCacneaPose286
.4byte sCacneaPose287
.4byte sCacneaPose288
.4byte sCacneaPose289
.4byte sCacneaPose290
.4byte sCacneaPose291
.4byte sCacneaPose292
.4byte sCacneaPose293
.4byte sCacneaPose294
.4byte sCacneaPose295
.4byte sCacneaPose296
.4byte sCacneaPose297
.4byte sCacneaPose298
.4byte sCacneaPose299
.4byte sCacneaPose300
.4byte sCacneaPose301
.4byte sCacneaPose302
sAxPositionsCacnea:
.2byte   -1,   -3, 	 -12,   -3, 	  11,   -3, 	  -1,   -6
.2byte    0,   -2, 	 -10,    0, 	  11,   -4, 	   0,   -5
.2byte   -2,   -2, 	 -12,   -5, 	   8,    1, 	  -2,   -5
.2byte    4,   -4, 	   9,   -7, 	  -7,    0, 	   0,   -6
.2byte    3,   -3, 	  10,   -5, 	 -11,    1, 	   0,   -5
.2byte    5,   -3, 	   8,   -8, 	  -3,    3, 	   0,   -5
.2byte    5,   -4, 	   0,   -8, 	   1,    1, 	  -2,   -6
.2byte    5,   -3, 	   7,   -6, 	  -4,    1, 	  -2,   -6
.2byte    4,   -5, 	  -4,   -8, 	   5,    0, 	  -2,   -6
.2byte    1,   -7, 	 -10,   -9, 	   9,   -2, 	  -3,   -7
.2byte    2,   -5, 	   0,  -10, 	   7,    1, 	  -3,   -5
.2byte   -1,   -5, 	 -11,   -7, 	  11,   -5, 	  -3,   -5
.2byte   -1,   -6, 	  11,   -5, 	 -12,   -4, 	  -1,   -4
.2byte   -1,   -6, 	  10,   -8, 	 -11,   -2, 	   0,   -4
.2byte    0,   -5, 	   9,   -3, 	 -12,   -8, 	  -2,   -4
.2byte   -3,   -7, 	   8,   -9, 	 -11,   -2, 	   1,   -7
.2byte   -4,   -5, 	  -2,  -10, 	  -9,    1, 	   1,   -5
.2byte   -1,   -5, 	   9,   -7, 	 -13,   -5, 	   1,   -5
.2byte   -7,   -4, 	  -2,   -8, 	  -3,    1, 	   0,   -6
.2byte   -7,   -3, 	  -9,   -6, 	   2,    1, 	   0,   -6
.2byte   -6,   -5, 	   2,   -8, 	  -7,    0, 	   0,   -6
.2byte   -6,   -4, 	 -11,   -7, 	   5,    0, 	  -2,   -6
.2byte   -5,   -3, 	 -12,   -5, 	   9,    1, 	  -2,   -5
.2byte   -7,   -3, 	 -10,   -8, 	   1,    3, 	  -2,   -5
.2byte   -1,   -3, 	 -12,   -3, 	  11,   -3, 	  -1,   -6
.2byte    0,   -2, 	 -10,    0, 	  11,   -4, 	   0,   -5
.2byte   -2,   -2, 	 -12,   -5, 	   8,    1, 	  -2,   -5
.2byte   -1,   -5, 	 -12,   -8, 	  11,   -7, 	  -1,   -7
.2byte    4,   -4, 	   9,   -7, 	  -7,    0, 	   0,   -6
.2byte    3,   -3, 	  10,   -5, 	 -11,    1, 	   0,   -5
.2byte    5,   -3, 	   8,   -8, 	  -3,    3, 	   0,   -5
.2byte    2,   -5, 	   2,  -10, 	 -12,   -4, 	  -1,   -7
.2byte    4,   -2, 	  12,   -9, 	  -2,    0, 	   0,   -7
.2byte    5,   -1, 	  13,  -10, 	  -2,    1, 	   0,   -6
.2byte    5,   -4, 	   0,   -8, 	   1,    1, 	  -2,   -6
.2byte    5,   -3, 	   7,   -6, 	  -4,    1, 	  -2,   -6
.2byte    4,   -5, 	  -4,   -8, 	   5,    0, 	  -2,   -6
.2byte    5,   -6, 	  -5,  -10, 	  -8,    1, 	  -3,   -5
.2byte    4,   -4, 	   9,  -12, 	   8,   -5, 	   0,   -6
.2byte    5,   -4, 	  11,  -13, 	   9,   -4, 	  -1,   -6
.2byte    1,   -7, 	 -10,   -9, 	   9,   -2, 	  -3,   -7
.2byte    2,   -5, 	   0,  -10, 	   7,    1, 	  -3,   -5
.2byte   -1,   -5, 	 -11,   -7, 	  11,   -5, 	  -3,   -5
.2byte    0,   -4, 	 -11,   -4, 	   3,    3, 	  -3,   -5
.2byte    4,   -7, 	  -4,  -15, 	  11,   -9, 	  -2,   -7
.2byte    2,   -6, 	  -5,  -16, 	  12,   -9, 	  -3,   -7
.2byte   -1,   -6, 	  11,   -5, 	 -12,   -4, 	  -1,   -4
.2byte   -1,   -6, 	  10,   -8, 	 -11,   -2, 	   0,   -4
.2byte    0,   -5, 	   9,   -3, 	 -12,   -8, 	  -2,   -4
.2byte   -1,   -6, 	   9,   -1, 	 -10,   -1, 	  -1,   -4
.2byte   -1,   -8, 	   7,  -14, 	 -10,  -14, 	  -1,   -6
.2byte   -1,   -8, 	   9,  -14, 	 -12,  -15, 	  -1,   -5
.2byte   -3,   -7, 	   8,   -9, 	 -11,   -2, 	   1,   -7
.2byte   -4,   -5, 	  -2,  -10, 	  -9,    1, 	   1,   -5
.2byte   -1,   -5, 	   9,   -7, 	 -13,   -5, 	   1,   -5
.2byte   -2,   -4, 	   9,   -4, 	  -5,    3, 	   1,   -5
.2byte   -6,   -7, 	   2,  -15, 	 -13,   -9, 	   0,   -7
.2byte   -4,   -6, 	   3,  -16, 	 -14,   -9, 	   1,   -7
.2byte   -7,   -4, 	  -2,   -8, 	  -3,    1, 	   0,   -6
.2byte   -7,   -3, 	  -9,   -6, 	   2,    1, 	   0,   -6
.2byte   -6,   -5, 	   2,   -8, 	  -7,    0, 	   0,   -6
.2byte   -7,   -6, 	   3,  -10, 	   6,    1, 	   1,   -5
.2byte   -6,   -4, 	 -11,  -12, 	 -10,   -5, 	  -2,   -6
.2byte   -7,   -4, 	 -13,  -13, 	 -11,   -4, 	  -1,   -6
.2byte   -6,   -4, 	 -11,   -7, 	   5,    0, 	  -2,   -6
.2byte   -5,   -3, 	 -12,   -5, 	   9,    1, 	  -2,   -5
.2byte   -7,   -3, 	 -10,   -8, 	   1,    3, 	  -2,   -5
.2byte   -4,   -5, 	  -4,  -10, 	  10,   -4, 	  -1,   -7
.2byte   -6,   -2, 	 -14,   -9, 	   0,    0, 	  -2,   -7
.2byte   -7,   -1, 	 -15,  -10, 	   0,    1, 	  -2,   -6
.2byte   -1,   -3, 	 -12,   -3, 	  11,   -3, 	  -1,   -6
.2byte    0,   -2, 	 -10,    0, 	  11,   -4, 	   0,   -5
.2byte   -2,   -2, 	 -12,   -5, 	   8,    1, 	  -2,   -5
.2byte   -1,   -5, 	 -12,   -8, 	  11,   -7, 	  -1,   -7
.2byte    4,   -4, 	   9,   -7, 	  -7,    0, 	   0,   -6
.2byte    3,   -3, 	  10,   -5, 	 -11,    1, 	   0,   -5
.2byte    5,   -3, 	   8,   -8, 	  -3,    3, 	   0,   -5
.2byte    2,   -5, 	   2,  -10, 	 -12,   -4, 	  -1,   -7
.2byte    4,   -2, 	  12,   -9, 	  -2,    0, 	   0,   -7
.2byte    5,   -1, 	  13,  -10, 	  -2,    1, 	   0,   -6
.2byte    5,   -4, 	   0,   -8, 	   1,    1, 	  -2,   -6
.2byte    5,   -3, 	   7,   -6, 	  -4,    1, 	  -2,   -6
.2byte    4,   -5, 	  -4,   -8, 	   5,    0, 	  -2,   -6
.2byte    5,   -6, 	  -5,  -10, 	  -8,    1, 	  -3,   -5
.2byte    4,   -4, 	   9,  -12, 	   8,   -5, 	   0,   -6
.2byte    5,   -4, 	  11,  -13, 	   9,   -4, 	  -1,   -6
.2byte    1,   -7, 	 -10,   -9, 	   9,   -2, 	  -3,   -7
.2byte    2,   -5, 	   0,  -10, 	   7,    1, 	  -3,   -5
.2byte   -1,   -5, 	 -11,   -7, 	  11,   -5, 	  -3,   -5
.2byte    0,   -4, 	 -11,   -4, 	   3,    3, 	  -3,   -5
.2byte    4,   -7, 	  -4,  -15, 	  11,   -9, 	  -2,   -7
.2byte    2,   -6, 	  -5,  -16, 	  12,   -9, 	  -3,   -7
.2byte   -1,   -6, 	  11,   -5, 	 -12,   -4, 	  -1,   -4
.2byte   -1,   -6, 	  10,   -8, 	 -11,   -2, 	   0,   -4
.2byte    0,   -5, 	   9,   -3, 	 -12,   -8, 	  -2,   -4
.2byte   -1,   -6, 	   9,   -1, 	 -10,   -1, 	  -1,   -4
.2byte   -1,   -8, 	   7,  -14, 	 -10,  -14, 	  -1,   -6
.2byte   -1,   -8, 	   9,  -14, 	 -12,  -15, 	  -1,   -5
.2byte   -3,   -7, 	   8,   -9, 	 -11,   -2, 	   1,   -7
.2byte   -4,   -5, 	  -2,  -10, 	  -9,    1, 	   1,   -5
.2byte   -1,   -5, 	   9,   -7, 	 -13,   -5, 	   1,   -5
.2byte   -2,   -4, 	   9,   -4, 	  -5,    3, 	   1,   -5
.2byte   -6,   -7, 	   2,  -15, 	 -13,   -9, 	   0,   -7
.2byte   -4,   -6, 	   3,  -16, 	 -14,   -9, 	   1,   -7
.2byte   -7,   -4, 	  -2,   -8, 	  -3,    1, 	   0,   -6
.2byte   -7,   -3, 	  -9,   -6, 	   2,    1, 	   0,   -6
.2byte   -6,   -5, 	   2,   -8, 	  -7,    0, 	   0,   -6
.2byte   -7,   -6, 	   3,  -10, 	   6,    1, 	   1,   -5
.2byte   -6,   -4, 	 -11,  -12, 	 -10,   -5, 	  -2,   -6
.2byte   -7,   -4, 	 -13,  -13, 	 -11,   -4, 	  -1,   -6
.2byte   -6,   -4, 	 -11,   -7, 	   5,    0, 	  -2,   -6
.2byte   -5,   -3, 	 -12,   -5, 	   9,    1, 	  -2,   -5
.2byte   -7,   -3, 	 -10,   -8, 	   1,    3, 	  -2,   -5
.2byte   -4,   -5, 	  -4,  -10, 	  10,   -4, 	  -1,   -7
.2byte   -6,   -2, 	 -14,   -9, 	   0,    0, 	  -2,   -7
.2byte   -7,   -1, 	 -15,  -10, 	   0,    1, 	  -2,   -6
.2byte   -1,   -3, 	 -12,   -3, 	  11,   -3, 	  -1,   -6
.2byte   -1,   -5, 	 -12,   -8, 	  11,   -7, 	  -1,   -7
.2byte   -1,   -1, 	 -10,    0, 	   9,    0, 	  -1,   -4
.2byte    4,   -4, 	   9,   -7, 	  -7,    0, 	   0,   -6
.2byte    2,   -5, 	   2,  -10, 	 -12,   -4, 	  -1,   -7
.2byte    4,   -2, 	  12,   -9, 	  -2,    0, 	   0,   -7
.2byte    5,   -4, 	   0,   -8, 	   1,    1, 	  -2,   -6
.2byte    5,   -6, 	  -5,  -10, 	  -8,    1, 	  -3,   -5
.2byte    4,   -4, 	   9,  -12, 	   8,   -5, 	   0,   -6
.2byte    1,   -7, 	 -10,   -9, 	   9,   -2, 	  -3,   -7
.2byte    0,   -4, 	 -11,   -4, 	   3,    3, 	  -3,   -5
.2byte    4,   -7, 	  -4,  -15, 	  11,   -9, 	  -2,   -7
.2byte   -1,   -6, 	  11,   -5, 	 -12,   -4, 	  -1,   -4
.2byte   -1,   -6, 	   9,   -1, 	 -10,   -1, 	  -1,   -4
.2byte   -1,   -8, 	   7,  -14, 	 -10,  -14, 	  -1,   -6
.2byte   -3,   -7, 	   8,   -9, 	 -11,   -2, 	   1,   -7
.2byte   -2,   -4, 	   9,   -4, 	  -5,    3, 	   1,   -5
.2byte   -6,   -7, 	   2,  -15, 	 -13,   -9, 	   0,   -7
.2byte   -7,   -4, 	  -2,   -8, 	  -3,    1, 	   0,   -6
.2byte   -7,   -6, 	   3,  -10, 	   6,    1, 	   1,   -5
.2byte   -6,   -4, 	 -11,  -12, 	 -10,   -5, 	  -2,   -6
.2byte   -6,   -4, 	 -11,   -7, 	   5,    0, 	  -2,   -6
.2byte   -4,   -5, 	  -4,  -10, 	  10,   -4, 	  -1,   -7
.2byte   -6,   -2, 	 -14,   -9, 	   0,    0, 	  -2,   -7
.2byte   -1,   -3, 	 -12,   -3, 	  11,   -3, 	  -1,   -6
.2byte   -1,   -5, 	 -12,   -8, 	  11,   -7, 	  -1,   -7
.2byte   -1,   -1, 	 -10,    0, 	   9,    0, 	  -1,   -4
.2byte   -1,   -1, 	 -11,    0, 	  10,    1, 	  -1,   -5
.2byte   -1,   -1, 	 -11,    0, 	  10,    1, 	  -1,   -5
.2byte   -1,   -1, 	 -11,    0, 	  10,    1, 	  -1,   -5
.2byte   -1,   -1, 	 -11,    0, 	  10,    1, 	  -1,   -5
.2byte   -1,   -1, 	 -11,    0, 	  10,    1, 	  -1,   -5
.2byte   -1,   -1, 	 -11,    0, 	  10,    1, 	  -1,   -5
.2byte   -1,   -1, 	 -11,    0, 	  10,    1, 	  -1,   -5
.2byte    4,   -4, 	   9,   -7, 	  -7,    0, 	   0,   -6
.2byte    2,   -5, 	   2,  -10, 	 -12,   -4, 	  -1,   -7
.2byte    4,   -2, 	  12,   -9, 	  -2,    0, 	   0,   -7
.2byte    5,   -2, 	  13,  -11, 	  -2,    0, 	   0,   -7
.2byte    5,   -2, 	  13,  -11, 	  -2,    0, 	   0,   -7
.2byte    5,   -2, 	  13,  -11, 	  -2,    0, 	   0,   -7
.2byte    5,   -2, 	  13,  -11, 	  -2,    0, 	   0,   -7
.2byte    5,   -2, 	  13,  -11, 	  -2,    0, 	   0,   -7
.2byte    5,   -2, 	  13,  -11, 	  -2,    0, 	   0,   -7
.2byte    5,   -2, 	  13,  -11, 	  -2,    0, 	   0,   -7
.2byte    5,   -4, 	   0,   -8, 	   1,    1, 	  -2,   -6
.2byte    5,   -6, 	  -5,  -10, 	  -8,    1, 	  -3,   -5
.2byte    4,   -4, 	   9,  -12, 	   8,   -5, 	   0,   -6
.2byte    5,   -6, 	  11,  -15, 	   9,   -6, 	  -1,   -8
.2byte    5,   -6, 	  11,  -15, 	   9,   -6, 	  -1,   -8
.2byte    5,   -6, 	  11,  -15, 	   9,   -6, 	  -1,   -8
.2byte    5,   -6, 	  11,  -15, 	   9,   -6, 	  -1,   -8
.2byte    5,   -6, 	  11,  -15, 	   9,   -6, 	  -1,   -8
.2byte    5,   -6, 	  11,  -15, 	   9,   -6, 	  -1,   -8
.2byte    5,   -6, 	  11,  -15, 	   9,   -6, 	  -1,   -8
.2byte    1,   -7, 	 -10,   -9, 	   9,   -2, 	  -3,   -7
.2byte    0,   -4, 	 -11,   -4, 	   3,    3, 	  -3,   -5
.2byte    4,   -7, 	  -4,  -15, 	  11,   -9, 	  -2,   -7
.2byte    2,   -8, 	  -5,  -18, 	  12,  -11, 	  -3,   -9
.2byte    2,   -8, 	  -5,  -18, 	  12,  -11, 	  -3,   -9
.2byte    2,   -8, 	  -5,  -18, 	  12,  -11, 	  -3,   -9
.2byte    2,   -8, 	  -5,  -18, 	  12,  -11, 	  -3,   -9
.2byte    2,   -8, 	  -5,  -18, 	  12,  -11, 	  -3,   -9
.2byte    2,   -8, 	  -5,  -18, 	  12,  -11, 	  -3,   -9
.2byte    2,   -8, 	  -5,  -18, 	  12,  -11, 	  -3,   -9
.2byte   -1,   -6, 	  11,   -5, 	 -12,   -4, 	  -1,   -4
.2byte   -1,   -6, 	   9,   -1, 	 -10,   -1, 	  -1,   -4
.2byte   -1,   -8, 	   7,  -14, 	 -10,  -14, 	  -1,   -6
.2byte   -1,  -10, 	   9,  -16, 	 -12,  -17, 	  -1,   -7
.2byte   -1,  -10, 	   9,  -16, 	 -12,  -17, 	  -1,   -7
.2byte   -1,  -10, 	   9,  -16, 	 -12,  -17, 	  -1,   -7
.2byte   -1,  -10, 	   9,  -16, 	 -12,  -17, 	  -1,   -7
.2byte   -1,  -10, 	   9,  -16, 	 -12,  -17, 	  -1,   -7
.2byte   -1,  -10, 	   9,  -16, 	 -12,  -17, 	  -1,   -7
.2byte   -1,  -10, 	   9,  -16, 	 -12,  -17, 	  -1,   -7
.2byte   -3,   -7, 	   8,   -9, 	 -11,   -2, 	   1,   -7
.2byte   -2,   -4, 	   9,   -4, 	  -5,    3, 	   1,   -5
.2byte   -6,   -7, 	   2,  -15, 	 -13,   -9, 	   0,   -7
.2byte   -4,   -8, 	   3,  -18, 	 -14,  -11, 	   1,   -9
.2byte   -4,   -8, 	   3,  -18, 	 -14,  -11, 	   1,   -9
.2byte   -4,   -8, 	   3,  -18, 	 -14,  -11, 	   1,   -9
.2byte   -4,   -8, 	   3,  -18, 	 -14,  -11, 	   1,   -9
.2byte   -4,   -8, 	   3,  -18, 	 -14,  -11, 	   1,   -9
.2byte   -4,   -8, 	   3,  -18, 	 -14,  -11, 	   1,   -9
.2byte   -4,   -8, 	   3,  -18, 	 -14,  -11, 	   1,   -9
.2byte   -7,   -4, 	  -2,   -8, 	  -3,    1, 	   0,   -6
.2byte   -7,   -6, 	   3,  -10, 	   6,    1, 	   1,   -5
.2byte   -6,   -4, 	 -11,  -12, 	 -10,   -5, 	  -2,   -6
.2byte   -7,   -6, 	 -13,  -15, 	 -11,   -6, 	  -1,   -8
.2byte   -7,   -6, 	 -13,  -15, 	 -11,   -6, 	  -1,   -8
.2byte   -7,   -6, 	 -13,  -15, 	 -11,   -6, 	  -1,   -8
.2byte   -7,   -6, 	 -13,  -15, 	 -11,   -6, 	  -1,   -8
.2byte   -7,   -6, 	 -13,  -15, 	 -11,   -6, 	  -1,   -8
.2byte   -7,   -6, 	 -13,  -15, 	 -11,   -6, 	  -1,   -8
.2byte   -7,   -6, 	 -13,  -15, 	 -11,   -6, 	  -1,   -8
.2byte   -6,   -4, 	 -11,   -7, 	   5,    0, 	  -2,   -6
.2byte   -4,   -5, 	  -4,  -10, 	  10,   -4, 	  -1,   -7
.2byte   -6,   -2, 	 -14,   -9, 	   0,    0, 	  -2,   -7
.2byte   -7,   -2, 	 -15,  -11, 	   0,    0, 	  -2,   -7
.2byte   -7,   -2, 	 -15,  -11, 	   0,    0, 	  -2,   -7
.2byte   -7,   -2, 	 -15,  -11, 	   0,    0, 	  -2,   -7
.2byte   -7,   -2, 	 -15,  -11, 	   0,    0, 	  -2,   -7
.2byte   -7,   -2, 	 -15,  -11, 	   0,    0, 	  -2,   -7
.2byte   -7,   -2, 	 -15,  -11, 	   0,    0, 	  -2,   -7
.2byte   -7,   -2, 	 -15,  -11, 	   0,    0, 	  -2,   -7
.2byte   -3,   -4, 	  -9,   -9, 	  11,    1, 	   1,   -5
.2byte   -4,   -2, 	  -9,   -6, 	   8,    2, 	   0,   -4
.2byte    0,   -1, 	 -12,   -4, 	  13,   -5, 	   0,   -4
.2byte    1,   -3, 	   9,  -10, 	 -13,    1, 	  -1,   -5
.2byte    0,   -2, 	  -1,  -12, 	  -3,    5, 	  -2,   -6
.2byte    0,   -3, 	  -6,  -11, 	   9,    1, 	  -3,   -6
.2byte    0,   -3, 	  13,   -2, 	 -12,   -2, 	   0,   -5
.2byte   -1,   -3, 	   5,  -11, 	 -10,    1, 	   2,   -6
.2byte   -1,   -2, 	   0,  -12, 	   2,    5, 	   1,   -6
.2byte   -2,   -3, 	 -10,  -10, 	  12,    1, 	   0,   -5
.2byte   -1,   -3, 	 -12,   -3, 	  11,   -3, 	  -1,   -6
.2byte   -1,   -5, 	 -12,   -8, 	  11,   -7, 	  -1,   -7
.2byte    4,   -4, 	   9,   -7, 	  -7,    0, 	   0,   -6
.2byte    3,   -5, 	   3,  -10, 	 -11,   -4, 	   0,   -7
.2byte    5,   -4, 	   0,   -8, 	   1,    1, 	  -2,   -6
.2byte    5,   -6, 	  -5,  -10, 	  -8,    1, 	  -3,   -5
.2byte    1,   -7, 	 -10,   -9, 	   9,   -2, 	  -3,   -7
.2byte    0,   -4, 	 -11,   -4, 	   3,    3, 	  -3,   -5
.2byte   -1,   -6, 	  11,   -5, 	 -12,   -4, 	  -1,   -4
.2byte   -1,   -6, 	   9,   -1, 	 -10,   -1, 	  -1,   -4
.2byte   -3,   -7, 	   8,   -9, 	 -11,   -2, 	   1,   -7
.2byte   -2,   -4, 	   9,   -4, 	  -5,    3, 	   1,   -5
.2byte   -7,   -4, 	  -2,   -8, 	  -3,    1, 	   0,   -6
.2byte   -7,   -6, 	   3,  -10, 	   6,    1, 	   1,   -5
.2byte   -6,   -4, 	 -11,   -7, 	   5,    0, 	  -2,   -6
.2byte   -5,   -5, 	  -5,  -10, 	   9,   -4, 	  -2,   -7
.2byte    0,   -1, 	  -9,    0, 	  10,    0, 	   0,   -4
.2byte   -4,   -2, 	 -12,   -9, 	   2,    0, 	   0,   -7
.2byte   -3,   -4, 	  -8,  -12, 	  -7,   -5, 	   1,   -6
.2byte   -4,   -6, 	   4,  -14, 	 -11,   -8, 	   2,   -6
.2byte    0,   -7, 	   8,  -13, 	  -9,  -13, 	   0,   -5
.2byte    4,   -6, 	  -4,  -14, 	  11,   -8, 	  -2,   -6
.2byte    3,   -4, 	   8,  -12, 	   7,   -5, 	  -1,   -6
.2byte    3,   -2, 	  11,   -9, 	  -3,    0, 	  -1,   -7
.2byte   -1,   -4, 	 -12,   -7, 	  11,   -6, 	  -1,   -6
.2byte    3,   -4, 	   3,   -9, 	 -11,   -3, 	   0,   -6
.2byte    6,   -6, 	  -4,  -10, 	  -7,    1, 	  -2,   -5
.2byte    1,   -5, 	 -10,   -5, 	   4,    2, 	  -2,   -6
.2byte   -1,   -7, 	   9,   -2, 	 -10,   -2, 	  -1,   -5
.2byte   -2,   -5, 	   9,   -5, 	  -5,    2, 	   1,   -6
.2byte   -7,   -6, 	   3,  -10, 	   6,    1, 	   1,   -5
.2byte   -4,   -4, 	  -4,   -9, 	  10,   -3, 	  -1,   -6
.2byte    0,   -3, 	 -11,   -3, 	  12,   -3, 	   0,   -6
.2byte    0,   -4, 	 -11,   -7, 	  12,   -6, 	   0,   -6
.2byte    0,   -2, 	  -9,   -1, 	  10,   -1, 	   0,   -5
.2byte    4,   -4, 	   9,   -7, 	  -7,    0, 	   0,   -6
.2byte    4,   -5, 	   4,  -10, 	 -10,   -4, 	   1,   -7
.2byte    3,   -2, 	  11,   -9, 	  -3,    0, 	  -1,   -7
.2byte    5,   -4, 	   0,   -8, 	   1,    1, 	  -2,   -6
.2byte    6,   -6, 	  -4,  -10, 	  -7,    1, 	  -2,   -5
.2byte    3,   -4, 	   8,  -12, 	   7,   -5, 	  -1,   -6
.2byte    1,   -7, 	 -10,   -9, 	   9,   -2, 	  -3,   -7
.2byte    1,   -5, 	 -10,   -5, 	   4,    2, 	  -2,   -6
.2byte    3,   -7, 	  -5,  -15, 	  10,   -9, 	  -3,   -7
.2byte    0,   -6, 	  12,   -5, 	 -11,   -4, 	   0,   -4
.2byte    0,   -7, 	  10,   -2, 	  -9,   -2, 	   0,   -5
.2byte    0,   -7, 	   8,  -13, 	  -9,  -13, 	   0,   -5
.2byte   -2,   -7, 	   9,   -9, 	 -10,   -2, 	   2,   -7
.2byte   -2,   -5, 	   9,   -5, 	  -5,    2, 	   1,   -6
.2byte   -4,   -7, 	   4,  -15, 	 -11,   -9, 	   2,   -7
.2byte   -6,   -4, 	  -1,   -8, 	  -2,    1, 	   1,   -6
.2byte   -7,   -6, 	   3,  -10, 	   6,    1, 	   1,   -5
.2byte   -4,   -4, 	  -9,  -12, 	  -8,   -5, 	   0,   -6
.2byte   -5,   -4, 	 -10,   -7, 	   6,    0, 	  -1,   -6
.2byte   -4,   -5, 	  -4,  -10, 	  10,   -4, 	  -1,   -7
.2byte   -4,   -2, 	 -12,   -9, 	   2,    0, 	   0,   -7
.2byte    0,   -1, 	  -9,    0, 	  10,    0, 	   0,   -4
.2byte   -4,   -2, 	 -12,   -9, 	   2,    0, 	   0,   -7
.2byte   -3,   -4, 	  -8,  -12, 	  -7,   -5, 	   1,   -6
.2byte   -4,   -6, 	   4,  -14, 	 -11,   -8, 	   2,   -6
.2byte    0,   -7, 	   8,  -13, 	  -9,  -13, 	   0,   -5
.2byte    3,   -6, 	  -5,  -14, 	  10,   -8, 	  -3,   -6
.2byte    2,   -4, 	   7,  -12, 	   6,   -5, 	  -2,   -6
.2byte    3,   -2, 	  11,   -9, 	  -3,    0, 	  -1,   -7
.2byte   -1,   -3, 	 -12,   -3, 	  11,   -3, 	  -1,   -6
.2byte   -6,   -4, 	 -11,   -7, 	   5,    0, 	  -2,   -6
.2byte   -7,   -4, 	  -2,   -8, 	  -3,    1, 	   0,   -6
.2byte   -3,   -7, 	   8,   -9, 	 -11,   -2, 	   1,   -7
.2byte   -1,   -6, 	  11,   -5, 	 -12,   -4, 	  -1,   -4
.2byte    1,   -7, 	 -10,   -9, 	   9,   -2, 	  -3,   -7
.2byte    5,   -4, 	   0,   -8, 	   1,    1, 	  -2,   -6
.2byte    4,   -4, 	   9,   -7, 	  -7,    0, 	   0,   -6
sCacneaAnimTable1:
.4byte sCacneaAnims_1_1
.4byte sCacneaAnims_1_2
.4byte sCacneaAnims_1_3
.4byte sCacneaAnims_1_4
.4byte sCacneaAnims_1_5
.4byte sCacneaAnims_1_6
.4byte sCacneaAnims_1_7
.4byte sCacneaAnims_1_8
sCacneaAnimTable2:
.4byte sCacneaAnims_2_1
.4byte sCacneaAnims_2_2
.4byte sCacneaAnims_2_3
.4byte sCacneaAnims_2_4
.4byte sCacneaAnims_2_5
.4byte sCacneaAnims_2_6
.4byte sCacneaAnims_2_7
.4byte sCacneaAnims_2_8
sCacneaAnimTable3:
.4byte sCacneaAnims_3_1
.4byte sCacneaAnims_3_2
.4byte sCacneaAnims_3_3
.4byte sCacneaAnims_3_4
.4byte sCacneaAnims_3_5
.4byte sCacneaAnims_3_6
.4byte sCacneaAnims_3_7
.4byte sCacneaAnims_3_8
sCacneaAnimTable4:
.4byte sCacneaAnims_4_1
.4byte sCacneaAnims_4_2
.4byte sCacneaAnims_4_3
.4byte sCacneaAnims_4_4
.4byte sCacneaAnims_4_5
.4byte sCacneaAnims_4_6
.4byte sCacneaAnims_4_7
.4byte sCacneaAnims_4_8
sCacneaAnimTable5:
.4byte sCacneaAnims_5_1
.4byte sCacneaAnims_5_2
.4byte sCacneaAnims_5_3
.4byte sCacneaAnims_5_4
.4byte sCacneaAnims_5_5
.4byte sCacneaAnims_5_6
.4byte sCacneaAnims_5_7
.4byte sCacneaAnims_5_8
sCacneaAnimTable6:
.4byte sCacneaAnims_6_1
.4byte sCacneaAnims_6_1
.4byte sCacneaAnims_6_1
.4byte sCacneaAnims_6_1
.4byte sCacneaAnims_6_1
.4byte sCacneaAnims_6_1
.4byte sCacneaAnims_6_1
.4byte sCacneaAnims_6_1
sCacneaAnimTable7:
.4byte sCacneaAnims_7_1
.4byte sCacneaAnims_7_2
.4byte sCacneaAnims_7_3
.4byte sCacneaAnims_7_4
.4byte sCacneaAnims_7_5
.4byte sCacneaAnims_7_6
.4byte sCacneaAnims_7_7
.4byte sCacneaAnims_7_8
sCacneaAnimTable8:
.4byte sCacneaAnims_8_1
.4byte sCacneaAnims_8_2
.4byte sCacneaAnims_8_3
.4byte sCacneaAnims_8_4
.4byte sCacneaAnims_8_5
.4byte sCacneaAnims_8_6
.4byte sCacneaAnims_8_7
.4byte sCacneaAnims_8_8
sCacneaAnimTable9:
.4byte sCacneaAnims_9_1
.4byte sCacneaAnims_9_2
.4byte sCacneaAnims_9_3
.4byte sCacneaAnims_9_4
.4byte sCacneaAnims_9_5
.4byte sCacneaAnims_9_6
.4byte sCacneaAnims_9_7
.4byte sCacneaAnims_9_8
sCacneaAnimTable10:
.4byte sCacneaAnims_10_1
.4byte sCacneaAnims_10_2
.4byte sCacneaAnims_10_3
.4byte sCacneaAnims_10_4
.4byte sCacneaAnims_10_5
.4byte sCacneaAnims_10_6
.4byte sCacneaAnims_10_7
.4byte sCacneaAnims_10_8
sCacneaAnimTable11:
.4byte sCacneaAnims_11_1
.4byte sCacneaAnims_11_2
.4byte sCacneaAnims_11_3
.4byte sCacneaAnims_11_4
.4byte sCacneaAnims_11_5
.4byte sCacneaAnims_11_6
.4byte sCacneaAnims_11_7
.4byte sCacneaAnims_11_8
sCacneaAnimTable12:
.4byte sCacneaAnims_12_1
.4byte sCacneaAnims_12_2
.4byte sCacneaAnims_12_3
.4byte sCacneaAnims_12_4
.4byte sCacneaAnims_12_5
.4byte sCacneaAnims_12_6
.4byte sCacneaAnims_12_7
.4byte sCacneaAnims_12_8
sCacneaAnimTable13:
.4byte sCacneaAnims_13_1
.4byte sCacneaAnims_13_2
.4byte sCacneaAnims_13_3
.4byte sCacneaAnims_13_4
.4byte sCacneaAnims_13_5
.4byte sCacneaAnims_13_6
.4byte sCacneaAnims_13_7
.4byte sCacneaAnims_13_8
sAxAnimationsCacnea:
.4byte sCacneaAnimTable1
.4byte sCacneaAnimTable2
.4byte sCacneaAnimTable3
.4byte sCacneaAnimTable4
.4byte sCacneaAnimTable5
.4byte sCacneaAnimTable6
.4byte sCacneaAnimTable7
.4byte sCacneaAnimTable8
.4byte sCacneaAnimTable9
.4byte sCacneaAnimTable10
.4byte sCacneaAnimTable11
.4byte sCacneaAnimTable12
.4byte sCacneaAnimTable13
sAxSpritesCacnea:
.4byte sCacneaSprites1
.4byte sCacneaSprites2
.4byte sCacneaSprites3
.4byte sCacneaSprites4
.4byte sCacneaSprites5
.4byte sCacneaSprites6
.4byte sCacneaSprites7
.4byte sCacneaSprites8
.4byte sCacneaSprites9
.4byte sCacneaSprites10
.4byte sCacneaSprites11
.4byte sCacneaSprites12
.4byte sCacneaSprites13
.4byte sCacneaSprites14
.4byte sCacneaSprites15
.4byte sCacneaSprites16
.4byte sCacneaSprites17
.4byte sCacneaSprites18
.4byte sCacneaSprites19
.4byte sCacneaSprites20
.4byte sCacneaSprites21
.4byte sCacneaSprites22
.4byte sCacneaSprites23
.4byte sCacneaSprites24
.4byte sCacneaSprites25
.4byte sCacneaSprites26
.4byte sCacneaSprites27
.4byte sCacneaSprites28
.4byte sCacneaSprites29
.4byte sCacneaSprites30
.4byte sCacneaSprites31
.4byte sCacneaSprites32
.4byte sCacneaSprites33
.4byte sCacneaSprites34
.4byte sCacneaSprites35
.4byte sCacneaSprites36
.4byte sCacneaSprites37
.4byte sCacneaSprites38
.4byte sCacneaSprites39
.4byte sCacneaSprites40
.4byte sCacneaSprites41
.4byte sCacneaSprites42
.4byte sCacneaSprites43
.4byte sCacneaSprites44
sAxMainCacnea:
ax_main sAxPosesCacnea, sAxAnimationsCacnea, 13, sAxSpritesCacnea, sAxPositionsCacnea
