.global gAxCastformRainy
gAxCastformRainy:
ax_siro sAxMainCastformRainy
sCastformRainyPose1:
ax_pose 0, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose2:
ax_pose 1, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose3:
ax_pose 2, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose4:
ax_pose 3, 0x81e7, 0x90f7, 0x7c00
ax_pose_terminator
sCastformRainyPose5:
ax_pose 4, 0x81e7, 0x90f7, 0x7c00
ax_pose_terminator
sCastformRainyPose6:
ax_pose 5, 0x81e7, 0x90f7, 0x7c00
ax_pose_terminator
sCastformRainyPose7:
ax_pose 6, 0x81e7, 0x90f7, 0x7c00
ax_pose_terminator
sCastformRainyPose8:
ax_pose 7, 0x81e7, 0x90f7, 0x7c00
ax_pose_terminator
sCastformRainyPose9:
ax_pose 8, 0x81e7, 0x90f7, 0x7c00
ax_pose_terminator
sCastformRainyPose10:
ax_pose 9, 0x81e7, 0x90f7, 0x7c00
ax_pose_terminator
sCastformRainyPose11:
ax_pose 10, 0x81e7, 0x90f7, 0x7c00
ax_pose_terminator
sCastformRainyPose12:
ax_pose 11, 0x81e7, 0x90f7, 0x7c00
ax_pose_terminator
sCastformRainyPose13:
ax_pose 12, 0x81e8, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose14:
ax_pose 13, 0x81e8, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose15:
ax_pose 14, 0x81e8, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose16:
ax_pose 9, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose17:
ax_pose 10, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose18:
ax_pose 11, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose19:
ax_pose 6, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose20:
ax_pose 7, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose21:
ax_pose 8, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose22:
ax_pose 3, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose23:
ax_pose 4, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose24:
ax_pose 5, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose25:
ax_pose 0, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose26:
ax_pose 15, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose27:
ax_pose 16, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose28:
ax_pose 3, 0x81e7, 0x90f7, 0x7c00
ax_pose_terminator
sCastformRainyPose29:
ax_pose 17, 0x81e7, 0x90f7, 0x7c00
ax_pose_terminator
sCastformRainyPose30:
ax_pose 18, 0x81e7, 0x90f8, 0x7c00
ax_pose_terminator
sCastformRainyPose31:
ax_pose 6, 0x81e7, 0x90f7, 0x7c00
ax_pose_terminator
sCastformRainyPose32:
ax_pose 19, 0x01e7, 0x90e7, 0x7c00
ax_pose_terminator
sCastformRainyPose33:
ax_pose 20, 0x81e7, 0x90f9, 0x7c00
ax_pose_terminator
sCastformRainyPose34:
ax_pose 9, 0x81e7, 0x90f7, 0x7c00
ax_pose_terminator
sCastformRainyPose35:
ax_pose 21, 0x81e7, 0x90f6, 0x7c00
ax_pose_terminator
sCastformRainyPose36:
ax_pose 22, 0x81e7, 0x90f9, 0x7c00
ax_pose_terminator
sCastformRainyPose37:
ax_pose 12, 0x81e8, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose38:
ax_pose 23, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose39:
ax_pose 24, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose40:
ax_pose 9, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose41:
ax_pose 21, 0x81e7, 0x80f9, 0x7c00
ax_pose_terminator
sCastformRainyPose42:
ax_pose 22, 0x81e7, 0x80f6, 0x7c00
ax_pose_terminator
sCastformRainyPose43:
ax_pose 6, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose44:
ax_pose 19, 0x01e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose45:
ax_pose 20, 0x81e7, 0x80f6, 0x7c00
ax_pose_terminator
sCastformRainyPose46:
ax_pose 3, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose47:
ax_pose 17, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose48:
ax_pose 18, 0x81e7, 0x80f7, 0x7c00
ax_pose_terminator
sCastformRainyPose49:
ax_pose 0, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose50:
ax_pose 15, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose51:
ax_pose 16, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose52:
ax_pose 3, 0x81e7, 0x90f7, 0x7c00
ax_pose_terminator
sCastformRainyPose53:
ax_pose 17, 0x81e7, 0x90f7, 0x7c00
ax_pose_terminator
sCastformRainyPose54:
ax_pose 18, 0x81e7, 0x90f8, 0x7c00
ax_pose_terminator
sCastformRainyPose55:
ax_pose 6, 0x81e7, 0x90f7, 0x7c00
ax_pose_terminator
sCastformRainyPose56:
ax_pose 19, 0x01e7, 0x90e7, 0x7c00
ax_pose_terminator
sCastformRainyPose57:
ax_pose 20, 0x81e7, 0x90f9, 0x7c00
ax_pose_terminator
sCastformRainyPose58:
ax_pose 9, 0x81e7, 0x90f7, 0x7c00
ax_pose_terminator
sCastformRainyPose59:
ax_pose 21, 0x81e7, 0x90f6, 0x7c00
ax_pose_terminator
sCastformRainyPose60:
ax_pose 22, 0x81e7, 0x90f9, 0x7c00
ax_pose_terminator
sCastformRainyPose61:
ax_pose 12, 0x81e8, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose62:
ax_pose 23, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose63:
ax_pose 24, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose64:
ax_pose 9, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose65:
ax_pose 21, 0x81e7, 0x80f9, 0x7c00
ax_pose_terminator
sCastformRainyPose66:
ax_pose 22, 0x81e7, 0x80f6, 0x7c00
ax_pose_terminator
sCastformRainyPose67:
ax_pose 6, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose68:
ax_pose 19, 0x01e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose69:
ax_pose 20, 0x81e7, 0x80f6, 0x7c00
ax_pose_terminator
sCastformRainyPose70:
ax_pose 3, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose71:
ax_pose 17, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose72:
ax_pose 18, 0x81e7, 0x80f7, 0x7c00
ax_pose_terminator
sCastformRainyPose73:
ax_pose 0, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose74:
ax_pose 15, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose75:
ax_pose 16, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose76:
ax_pose 3, 0x81e7, 0x90f7, 0x7c00
ax_pose_terminator
sCastformRainyPose77:
ax_pose 17, 0x81e7, 0x90f7, 0x7c00
ax_pose_terminator
sCastformRainyPose78:
ax_pose 18, 0x81e8, 0x90f8, 0x7c00
ax_pose_terminator
sCastformRainyPose79:
ax_pose 6, 0x81e7, 0x90f7, 0x7c00
ax_pose_terminator
sCastformRainyPose80:
ax_pose 19, 0x01e7, 0x90e7, 0x7c00
ax_pose_terminator
sCastformRainyPose81:
ax_pose 20, 0x81e7, 0x90fa, 0x7c00
ax_pose_terminator
sCastformRainyPose82:
ax_pose 9, 0x81e7, 0x90f7, 0x7c00
ax_pose_terminator
sCastformRainyPose83:
ax_pose 21, 0x81e7, 0x90f6, 0x7c00
ax_pose_terminator
sCastformRainyPose84:
ax_pose 22, 0x81e6, 0x90f9, 0x7c00
ax_pose_terminator
sCastformRainyPose85:
ax_pose 12, 0x81e8, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose86:
ax_pose 23, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose87:
ax_pose 24, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose88:
ax_pose 9, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose89:
ax_pose 21, 0x81e7, 0x80f9, 0x7c00
ax_pose_terminator
sCastformRainyPose90:
ax_pose 22, 0x81e6, 0x80f6, 0x7c00
ax_pose_terminator
sCastformRainyPose91:
ax_pose 6, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose92:
ax_pose 19, 0x01e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose93:
ax_pose 20, 0x81e7, 0x80f5, 0x7c00
ax_pose_terminator
sCastformRainyPose94:
ax_pose 3, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose95:
ax_pose 17, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose96:
ax_pose 18, 0x81e8, 0x80f7, 0x7c00
ax_pose_terminator
sCastformRainyPose97:
ax_pose 0, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose98:
ax_pose 3, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose99:
ax_pose 6, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose100:
ax_pose 9, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose101:
ax_pose 12, 0x81e8, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose102:
ax_pose 9, 0x81e7, 0x90f7, 0x7c00
ax_pose_terminator
sCastformRainyPose103:
ax_pose 6, 0x81e7, 0x90f7, 0x7c00
ax_pose_terminator
sCastformRainyPose104:
ax_pose 3, 0x81e7, 0x90f7, 0x7c00
ax_pose_terminator
sCastformRainyPose105:
ax_pose 3, 0x81e7, 0x90f7, 0x7c00
ax_pose_terminator
sCastformRainyPose106:
ax_pose 0, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose107:
ax_pose 3, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose108:
ax_pose 6, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose109:
ax_pose 9, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose110:
ax_pose 12, 0x81e8, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose111:
ax_pose 9, 0x81e7, 0x90f7, 0x7c00
ax_pose_terminator
sCastformRainyPose112:
ax_pose 6, 0x81e7, 0x90f7, 0x7c00
ax_pose_terminator
sCastformRainyPose113:
ax_pose 6, 0x81e7, 0x90f7, 0x7c00
ax_pose_terminator
sCastformRainyPose114:
ax_pose 3, 0x81e7, 0x90f7, 0x7c00
ax_pose_terminator
sCastformRainyPose115:
ax_pose 0, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose116:
ax_pose 3, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose117:
ax_pose 6, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose118:
ax_pose 9, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose119:
ax_pose 12, 0x81e8, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose120:
ax_pose 9, 0x81e7, 0x90f7, 0x7c00
ax_pose_terminator
sCastformRainyPose121:
ax_pose 9, 0x81e7, 0x90f7, 0x7c00
ax_pose_terminator
sCastformRainyPose122:
ax_pose 6, 0x81e7, 0x90f7, 0x7c00
ax_pose_terminator
sCastformRainyPose123:
ax_pose 3, 0x81e7, 0x90f7, 0x7c00
ax_pose_terminator
sCastformRainyPose124:
ax_pose 0, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose125:
ax_pose 3, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose126:
ax_pose 6, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose127:
ax_pose 9, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose128:
ax_pose 12, 0x81e8, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose129:
ax_pose 12, 0x81e8, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose130:
ax_pose 9, 0x81e7, 0x90f7, 0x7c00
ax_pose_terminator
sCastformRainyPose131:
ax_pose 6, 0x81e7, 0x90f7, 0x7c00
ax_pose_terminator
sCastformRainyPose132:
ax_pose 3, 0x81e7, 0x90f7, 0x7c00
ax_pose_terminator
sCastformRainyPose133:
ax_pose 0, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose134:
ax_pose 3, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose135:
ax_pose 6, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose136:
ax_pose 9, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose137:
ax_pose 9, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose138:
ax_pose 12, 0x81e8, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose139:
ax_pose 9, 0x81e7, 0x90f7, 0x7c00
ax_pose_terminator
sCastformRainyPose140:
ax_pose 6, 0x81e7, 0x90f7, 0x7c00
ax_pose_terminator
sCastformRainyPose141:
ax_pose 3, 0x81e7, 0x90f7, 0x7c00
ax_pose_terminator
sCastformRainyPose142:
ax_pose 0, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose143:
ax_pose 3, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose144:
ax_pose 6, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose145:
ax_pose 6, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose146:
ax_pose 9, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose147:
ax_pose 12, 0x81e8, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose148:
ax_pose 9, 0x81e7, 0x90f7, 0x7c00
ax_pose_terminator
sCastformRainyPose149:
ax_pose 6, 0x81e7, 0x90f7, 0x7c00
ax_pose_terminator
sCastformRainyPose150:
ax_pose 3, 0x81e7, 0x90f7, 0x7c00
ax_pose_terminator
sCastformRainyPose151:
ax_pose 0, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose152:
ax_pose 3, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose153:
ax_pose 3, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose154:
ax_pose 6, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose155:
ax_pose 9, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose156:
ax_pose 12, 0x81e8, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose157:
ax_pose 9, 0x81e7, 0x90f7, 0x7c00
ax_pose_terminator
sCastformRainyPose158:
ax_pose 6, 0x81e7, 0x90f7, 0x7c00
ax_pose_terminator
sCastformRainyPose159:
ax_pose 3, 0x81e7, 0x90f7, 0x7c00
ax_pose_terminator
sCastformRainyPose160:
ax_pose 0, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose161:
ax_pose 25, 0x01e7, 0x80f3, 0x7c00
ax_pose_terminator
sCastformRainyPose162:
ax_pose 26, 0x01e7, 0x80f3, 0x7c00
ax_pose_terminator
sCastformRainyPose163:
ax_pose 27, 0x01e0, 0x80f1, 0x7c00
ax_pose_terminator
sCastformRainyPose164:
ax_pose 28, 0x01e0, 0x90e8, 0x7c00
ax_pose_terminator
sCastformRainyPose165:
ax_pose 29, 0x01e2, 0x90e8, 0x7c00
ax_pose_terminator
sCastformRainyPose166:
ax_pose 30, 0x01e5, 0x90e7, 0x7c00
ax_pose_terminator
sCastformRainyPose167:
ax_pose 31, 0x01e4, 0x80f1, 0x7c00
ax_pose_terminator
sCastformRainyPose168:
ax_pose 30, 0x01e5, 0x80f9, 0x7c00
ax_pose_terminator
sCastformRainyPose169:
ax_pose 29, 0x01e2, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose170:
ax_pose 28, 0x01e0, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose171:
ax_pose 0, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose172:
ax_pose 1, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose173:
ax_pose 2, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose174:
ax_pose 3, 0x81e7, 0x90f7, 0x7c00
ax_pose_terminator
sCastformRainyPose175:
ax_pose 4, 0x81e7, 0x90f7, 0x7c00
ax_pose_terminator
sCastformRainyPose176:
ax_pose 5, 0x81e7, 0x90f7, 0x7c00
ax_pose_terminator
sCastformRainyPose177:
ax_pose 6, 0x81e7, 0x90f7, 0x7c00
ax_pose_terminator
sCastformRainyPose178:
ax_pose 7, 0x81e7, 0x90f7, 0x7c00
ax_pose_terminator
sCastformRainyPose179:
ax_pose 8, 0x81e7, 0x90f7, 0x7c00
ax_pose_terminator
sCastformRainyPose180:
ax_pose 9, 0x81e7, 0x90f7, 0x7c00
ax_pose_terminator
sCastformRainyPose181:
ax_pose 10, 0x81e7, 0x90f7, 0x7c00
ax_pose_terminator
sCastformRainyPose182:
ax_pose 11, 0x81e7, 0x90f7, 0x7c00
ax_pose_terminator
sCastformRainyPose183:
ax_pose 12, 0x81e8, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose184:
ax_pose 13, 0x81e8, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose185:
ax_pose 14, 0x81e8, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose186:
ax_pose 9, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose187:
ax_pose 10, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose188:
ax_pose 11, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose189:
ax_pose 6, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose190:
ax_pose 7, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose191:
ax_pose 8, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose192:
ax_pose 3, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose193:
ax_pose 4, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose194:
ax_pose 5, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose195:
ax_pose 16, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose196:
ax_pose 18, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose197:
ax_pose 20, 0x81e7, 0x80f7, 0x7c00
ax_pose_terminator
sCastformRainyPose198:
ax_pose 22, 0x81e7, 0x80f7, 0x7c00
ax_pose_terminator
sCastformRainyPose199:
ax_pose 24, 0x81e9, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose200:
ax_pose 22, 0x81e7, 0x90f9, 0x7c00
ax_pose_terminator
sCastformRainyPose201:
ax_pose 20, 0x81e7, 0x90f9, 0x7c00
ax_pose_terminator
sCastformRainyPose202:
ax_pose 18, 0x81e7, 0x90f8, 0x7c00
ax_pose_terminator
sCastformRainyPose203:
ax_pose 15, 0x81e8, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose204:
ax_pose 17, 0x81e8, 0x90f8, 0x7c00
ax_pose_terminator
sCastformRainyPose205:
ax_pose 19, 0x01e7, 0x90e9, 0x7c00
ax_pose_terminator
sCastformRainyPose206:
ax_pose 21, 0x81e6, 0x90f7, 0x7c00
ax_pose_terminator
sCastformRainyPose207:
ax_pose 23, 0x81e6, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose208:
ax_pose 21, 0x81e6, 0x80f9, 0x7c00
ax_pose_terminator
sCastformRainyPose209:
ax_pose 19, 0x01e7, 0x80f7, 0x7c00
ax_pose_terminator
sCastformRainyPose210:
ax_pose 17, 0x81e9, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose211:
ax_pose 0, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose212:
ax_pose 15, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose213:
ax_pose 16, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose214:
ax_pose 3, 0x81e7, 0x90f7, 0x7c00
ax_pose_terminator
sCastformRainyPose215:
ax_pose 17, 0x81e7, 0x90f7, 0x7c00
ax_pose_terminator
sCastformRainyPose216:
ax_pose 18, 0x81e8, 0x90f8, 0x7c00
ax_pose_terminator
sCastformRainyPose217:
ax_pose 6, 0x81e7, 0x90f7, 0x7c00
ax_pose_terminator
sCastformRainyPose218:
ax_pose 19, 0x01e7, 0x90e8, 0x7c00
ax_pose_terminator
sCastformRainyPose219:
ax_pose 20, 0x81e7, 0x90f9, 0x7c00
ax_pose_terminator
sCastformRainyPose220:
ax_pose 9, 0x81e7, 0x90f7, 0x7c00
ax_pose_terminator
sCastformRainyPose221:
ax_pose 21, 0x81e7, 0x90f6, 0x7c00
ax_pose_terminator
sCastformRainyPose222:
ax_pose 22, 0x81e6, 0x90f8, 0x7c00
ax_pose_terminator
sCastformRainyPose223:
ax_pose 12, 0x81e8, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose224:
ax_pose 23, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose225:
ax_pose 24, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose226:
ax_pose 9, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose227:
ax_pose 21, 0x81e7, 0x80f9, 0x7c00
ax_pose_terminator
sCastformRainyPose228:
ax_pose 22, 0x81e6, 0x80f7, 0x7c00
ax_pose_terminator
sCastformRainyPose229:
ax_pose 6, 0x81e7, 0x80f9, 0x7c00
ax_pose_terminator
sCastformRainyPose230:
ax_pose 19, 0x01e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose231:
ax_pose 20, 0x81e7, 0x80f7, 0x7c00
ax_pose_terminator
sCastformRainyPose232:
ax_pose 3, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose233:
ax_pose 17, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose234:
ax_pose 18, 0x81e8, 0x80f7, 0x7c00
ax_pose_terminator
sCastformRainyPose235:
ax_pose 16, 0x81e6, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose236:
ax_pose 18, 0x81e6, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose237:
ax_pose 20, 0x81e6, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose238:
ax_pose 22, 0x81e5, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose239:
ax_pose 24, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose240:
ax_pose 22, 0x81e5, 0x90f8, 0x7c00
ax_pose_terminator
sCastformRainyPose241:
ax_pose 20, 0x81e6, 0x90f8, 0x7c00
ax_pose_terminator
sCastformRainyPose242:
ax_pose 18, 0x81e6, 0x90f8, 0x7c00
ax_pose_terminator
sCastformRainyPose243:
ax_pose 0, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose244:
ax_pose 3, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose245:
ax_pose 6, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose246:
ax_pose 9, 0x81e7, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose247:
ax_pose 12, 0x81e8, 0x80f8, 0x7c00
ax_pose_terminator
sCastformRainyPose248:
ax_pose 9, 0x81e7, 0x90f7, 0x7c00
ax_pose_terminator
sCastformRainyPose249:
ax_pose 6, 0x81e7, 0x90f7, 0x7c00
ax_pose_terminator
sCastformRainyPose250:
ax_pose 3, 0x81e7, 0x90f7, 0x7c00
ax_pose_terminator
.align 2
sCastformRainyAnims_1_1:
ax_anim 6, 0, 0, 0, 0, 0, 0,
ax_anim 6, 0, 1, 0, -1, 0, 0,
ax_anim 6, 0, 0, 0, -2, 0, 0,
ax_anim 6, 0, 2, 0, -3, 0, 0,
ax_anim 6, 0, 0, 0, -3, 0, 0,
ax_anim 6, 0, 1, 0, -2, 0, 0,
ax_anim 6, 0, 0, 0, -1, 0, 0,
ax_anim 6, 0, 2, 0, 0, 0, 0,
ax_anim_terminator
sCastformRainyAnims_1_2:
ax_anim 6, 0, 3, 0, 0, 0, 0,
ax_anim 6, 0, 4, 0, -1, 0, 0,
ax_anim 6, 0, 3, 0, -2, 0, 0,
ax_anim 6, 0, 5, 0, -3, 0, 0,
ax_anim 6, 0, 3, 0, -3, 0, 0,
ax_anim 6, 0, 4, 0, -2, 0, 0,
ax_anim 6, 0, 3, 0, -1, 0, 0,
ax_anim 6, 0, 5, 0, 0, 0, 0,
ax_anim_terminator
sCastformRainyAnims_1_3:
ax_anim 6, 0, 6, 0, 0, 0, 0,
ax_anim 6, 0, 7, 0, -1, 0, 0,
ax_anim 6, 0, 6, 0, -2, 0, 0,
ax_anim 6, 0, 8, 0, -3, 0, 0,
ax_anim 6, 0, 6, 0, -3, 0, 0,
ax_anim 6, 0, 7, 0, -2, 0, 0,
ax_anim 6, 0, 6, 0, -1, 0, 0,
ax_anim 6, 0, 8, 0, 0, 0, 0,
ax_anim_terminator
sCastformRainyAnims_1_4:
ax_anim 6, 0, 9, 0, 0, 0, 0,
ax_anim 6, 0, 10, 0, -1, 0, 0,
ax_anim 6, 0, 9, 0, -2, 0, 0,
ax_anim 6, 0, 11, 0, -3, 0, 0,
ax_anim 6, 0, 9, 0, -3, 0, 0,
ax_anim 6, 0, 10, 0, -2, 0, 0,
ax_anim 6, 0, 9, 0, -1, 0, 0,
ax_anim 6, 0, 11, 0, 0, 0, 0,
ax_anim_terminator
sCastformRainyAnims_1_5:
ax_anim 6, 0, 12, 0, 0, 0, 0,
ax_anim 6, 0, 13, 0, -1, 0, 0,
ax_anim 6, 0, 12, 0, -2, 0, 0,
ax_anim 6, 0, 14, 0, -3, 0, 0,
ax_anim 6, 0, 12, 0, -3, 0, 0,
ax_anim 6, 0, 13, 0, -2, 0, 0,
ax_anim 6, 0, 12, 0, -1, 0, 0,
ax_anim 6, 0, 14, 0, 0, 0, 0,
ax_anim_terminator
sCastformRainyAnims_1_6:
ax_anim 6, 0, 15, 0, 0, 0, 0,
ax_anim 6, 0, 16, 0, -1, 0, 0,
ax_anim 6, 0, 15, 0, -2, 0, 0,
ax_anim 6, 0, 17, 0, -3, 0, 0,
ax_anim 6, 0, 15, 0, -3, 0, 0,
ax_anim 6, 0, 16, 0, -2, 0, 0,
ax_anim 6, 0, 15, 0, -1, 0, 0,
ax_anim 6, 0, 17, 0, 0, 0, 0,
ax_anim_terminator
sCastformRainyAnims_1_7:
ax_anim 6, 0, 18, 0, 0, 0, 0,
ax_anim 6, 0, 19, 0, -1, 0, 0,
ax_anim 6, 0, 18, 0, -2, 0, 0,
ax_anim 6, 0, 20, 0, -3, 0, 0,
ax_anim 6, 0, 18, 0, -3, 0, 0,
ax_anim 6, 0, 19, 0, -2, 0, 0,
ax_anim 6, 0, 18, 0, -1, 0, 0,
ax_anim 6, 0, 20, 0, 0, 0, 0,
ax_anim_terminator
sCastformRainyAnims_1_8:
ax_anim 6, 0, 21, 0, 0, 0, 0,
ax_anim 6, 0, 22, 0, -1, 0, 0,
ax_anim 6, 0, 21, 0, -2, 0, 0,
ax_anim 6, 0, 23, 0, -3, 0, 0,
ax_anim 6, 0, 21, 0, -3, 0, 0,
ax_anim 6, 0, 22, 0, -2, 0, 0,
ax_anim 6, 0, 21, 0, -1, 0, 0,
ax_anim 6, 0, 23, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sCastformRainyAnims_2_1:
ax_anim 2, 0, 24, 0, -1, 0, -1,
ax_anim 6, 0, 25, 0, -2, 0, -2,
ax_anim 1, 0, 24, 0, 0, 0, 0,
ax_anim 1, 2, 24, 0, 4, 0, 4,
ax_anim 1, 0, 24, 0, 13, 0, 13,
ax_anim 2, 0, 26, 0, 21, 0, 22,
ax_anim 2, 1, 26, 1, 21, 1, 22,
ax_anim 2, 0, 26, 0, 21, 0, 22,
ax_anim 2, 0, 26, 1, 21, 1, 22,
ax_anim 2, 0, 24, 0, 8, 0, 8,
ax_anim_terminator
sCastformRainyAnims_2_2:
ax_anim 2, 0, 27, -1, -1, -1, -1,
ax_anim 6, 0, 28, -2, -2, -2, -2,
ax_anim 1, 0, 27, 0, 0, 0, 0,
ax_anim 1, 2, 27, 4, 4, 4, 4,
ax_anim 1, 0, 27, 13, 14, 13, 13,
ax_anim 2, 0, 29, 22, 21, 22, 21,
ax_anim 2, 1, 29, 23, 20, 23, 20,
ax_anim 2, 0, 29, 22, 21, 22, 21,
ax_anim 2, 0, 29, 23, 20, 23, 20,
ax_anim 2, 0, 27, 8, 8, 8, 8,
ax_anim_terminator
sCastformRainyAnims_2_3:
ax_anim 2, 0, 30, -1, 0, -1, 0,
ax_anim 6, 0, 31, -2, 0, -2, 0,
ax_anim 1, 0, 30, 0, 0, 0, 0,
ax_anim 1, 2, 30, 4, 0, 4, 0,
ax_anim 1, 0, 30, 14, 0, 13, 0,
ax_anim 2, 0, 32, 21, 0, 21, -1,
ax_anim 2, 1, 32, 21, 1, 21, 0,
ax_anim 2, 0, 32, 21, 0, 21, -1,
ax_anim 2, 0, 32, 21, 1, 21, 0,
ax_anim 2, 0, 30, 8, 0, 8, 0,
ax_anim_terminator
sCastformRainyAnims_2_4:
ax_anim 2, 0, 33, -1, 1, -1, 1,
ax_anim 6, 0, 34, -2, 2, -2, 2,
ax_anim 1, 0, 33, 0, -1, 0, -1,
ax_anim 1, 2, 33, 4, -4, 4, -4,
ax_anim 1, 0, 33, 12, -11, 12, -11,
ax_anim 2, 0, 35, 21, -19, 21, -20,
ax_anim 2, 1, 35, 22, -18, 22, -19,
ax_anim 2, 0, 35, 21, -19, 21, -20,
ax_anim 2, 0, 35, 22, -18, 22, -19,
ax_anim 2, 0, 33, 8, -8, 8, -8,
ax_anim_terminator
sCastformRainyAnims_2_5:
ax_anim 2, 0, 36, 0, 1, 0, 1,
ax_anim 6, 0, 37, 0, 2, 0, 2,
ax_anim 1, 0, 36, 0, 0, 0, 0,
ax_anim 1, 2, 36, 0, -4, 0, -4,
ax_anim 1, 0, 36, 0, -9, 0, -10,
ax_anim 2, 0, 38, 0, -16, 0, -19,
ax_anim 2, 1, 38, 1, -16, 1, -19,
ax_anim 2, 0, 38, 0, -16, 0, -19,
ax_anim 2, 0, 38, 1, -16, 1, -19,
ax_anim 2, 0, 36, 0, -6, 0, -6,
ax_anim_terminator
sCastformRainyAnims_2_6:
ax_anim 2, 0, 39, 1, 1, 1, 1,
ax_anim 6, 0, 40, 2, 2, 2, 2,
ax_anim 1, 0, 39, 0, -1, 0, -1,
ax_anim 1, 2, 39, -4, -4, -4, -4,
ax_anim 1, 0, 39, -12, -11, -12, -11,
ax_anim 2, 0, 41, -21, -19, -21, -20,
ax_anim 2, 1, 41, -22, -18, -22, -19,
ax_anim 2, 0, 41, -21, -19, -21, -20,
ax_anim 2, 0, 41, -22, -18, -22, -19,
ax_anim 2, 0, 39, -8, -8, -8, -8,
ax_anim_terminator
sCastformRainyAnims_2_7:
ax_anim 2, 0, 42, 1, 0, 1, 0,
ax_anim 6, 0, 43, 2, 0, 2, 0,
ax_anim 1, 0, 42, 0, 0, 0, 0,
ax_anim 1, 2, 42, -4, 0, -4, 0,
ax_anim 1, 0, 42, -14, 0, -13, 0,
ax_anim 2, 0, 44, -21, 0, -21, -1,
ax_anim 2, 1, 44, -21, 1, -21, 0,
ax_anim 2, 0, 44, -21, 0, -21, -1,
ax_anim 2, 0, 44, -21, 1, -21, 0,
ax_anim 2, 0, 42, -8, 0, -8, 0,
ax_anim_terminator
sCastformRainyAnims_2_8:
ax_anim 2, 0, 45, 1, -1, 1, -1,
ax_anim 6, 0, 46, 2, -2, 2, -2,
ax_anim 1, 0, 45, 0, 0, 0, 0,
ax_anim 1, 2, 45, -4, 4, -4, 4,
ax_anim 1, 0, 45, -13, 14, -13, 13,
ax_anim 2, 0, 47, -22, 21, -22, 21,
ax_anim 2, 1, 47, -23, 20, -23, 20,
ax_anim 2, 0, 47, -22, 21, -22, 21,
ax_anim 2, 0, 47, -23, 20, -23, 20,
ax_anim 2, 0, 45, -8, 8, -8, 8,
ax_anim_terminator
.align 2
sCastformRainyAnims_3_1:
ax_anim 2, 0, 48, 0, -1, 0, -1,
ax_anim 6, 0, 49, 0, -2, 0, -2,
ax_anim 1, 0, 48, 0, 0, 0, 0,
ax_anim 1, 2, 48, 0, 4, 0, 4,
ax_anim 1, 0, 48, 0, 13, 0, 13,
ax_anim 2, 0, 50, 0, 21, 0, 22,
ax_anim 2, 1, 50, 1, 21, 1, 22,
ax_anim 2, 0, 50, 0, 21, 0, 22,
ax_anim 2, 0, 50, 1, 21, 1, 22,
ax_anim 2, 0, 48, 0, 8, 0, 8,
ax_anim_terminator
sCastformRainyAnims_3_2:
ax_anim 2, 0, 51, -1, -1, -1, -1,
ax_anim 6, 0, 52, -2, -2, -2, -2,
ax_anim 1, 0, 51, 0, 0, 0, 0,
ax_anim 1, 2, 51, 4, 4, 4, 4,
ax_anim 1, 0, 51, 13, 14, 13, 13,
ax_anim 2, 0, 53, 22, 21, 22, 21,
ax_anim 2, 1, 53, 23, 20, 23, 20,
ax_anim 2, 0, 53, 22, 21, 22, 21,
ax_anim 2, 0, 53, 23, 20, 23, 20,
ax_anim 2, 0, 51, 8, 8, 8, 8,
ax_anim_terminator
sCastformRainyAnims_3_3:
ax_anim 2, 0, 54, -1, 0, -1, 0,
ax_anim 6, 0, 55, -2, 0, -2, 0,
ax_anim 1, 0, 54, 0, 0, 0, 0,
ax_anim 1, 2, 54, 4, 0, 4, 0,
ax_anim 1, 0, 54, 14, 0, 13, 0,
ax_anim 2, 0, 56, 21, 0, 21, -1,
ax_anim 2, 1, 56, 21, 1, 21, 0,
ax_anim 2, 0, 56, 21, 0, 21, -1,
ax_anim 2, 0, 56, 21, 1, 21, 0,
ax_anim 2, 0, 54, 8, 0, 8, 0,
ax_anim_terminator
sCastformRainyAnims_3_4:
ax_anim 2, 0, 57, -1, 1, -1, 1,
ax_anim 6, 0, 58, -2, 2, -2, 2,
ax_anim 1, 0, 57, 0, -1, 0, -1,
ax_anim 1, 2, 57, 4, -4, 4, -4,
ax_anim 1, 0, 57, 12, -11, 12, -11,
ax_anim 2, 0, 59, 21, -19, 21, -20,
ax_anim 2, 1, 59, 22, -18, 22, -19,
ax_anim 2, 0, 59, 21, -19, 21, -20,
ax_anim 2, 0, 59, 22, -18, 22, -19,
ax_anim 2, 0, 57, 8, -8, 8, -8,
ax_anim_terminator
sCastformRainyAnims_3_5:
ax_anim 2, 0, 60, 0, 1, 0, 1,
ax_anim 6, 0, 61, 0, 2, 0, 2,
ax_anim 1, 0, 60, 0, 0, 0, 0,
ax_anim 1, 2, 60, 0, -4, 0, -4,
ax_anim 1, 0, 60, 0, -9, 0, -10,
ax_anim 2, 0, 62, 0, -16, 0, -19,
ax_anim 2, 1, 62, 1, -16, 1, -19,
ax_anim 2, 0, 62, 0, -16, 0, -19,
ax_anim 2, 0, 62, 1, -16, 1, -19,
ax_anim 2, 0, 60, 0, -6, 0, -6,
ax_anim_terminator
sCastformRainyAnims_3_6:
ax_anim 2, 0, 63, 1, 1, 1, 1,
ax_anim 6, 0, 64, 2, 2, 2, 2,
ax_anim 1, 0, 63, 0, -1, 0, -1,
ax_anim 1, 2, 63, -4, -4, -4, -4,
ax_anim 1, 0, 63, -12, -11, -12, -11,
ax_anim 2, 0, 65, -21, -19, -21, -20,
ax_anim 2, 1, 65, -22, -18, -22, -19,
ax_anim 2, 0, 65, -21, -19, -21, -20,
ax_anim 2, 0, 65, -22, -18, -22, -19,
ax_anim 2, 0, 63, -8, -8, -8, -8,
ax_anim_terminator
sCastformRainyAnims_3_7:
ax_anim 2, 0, 66, 1, 0, 1, 0,
ax_anim 6, 0, 67, 2, 0, 2, 0,
ax_anim 1, 0, 66, 0, 0, 0, 0,
ax_anim 1, 2, 66, -4, 0, -4, 0,
ax_anim 1, 0, 66, -14, 0, -13, 0,
ax_anim 2, 0, 68, -21, 0, -21, -1,
ax_anim 2, 1, 68, -21, 1, -21, 0,
ax_anim 2, 0, 68, -21, 0, -21, -1,
ax_anim 2, 0, 68, -21, 1, -21, 0,
ax_anim 2, 0, 66, -8, 0, -8, 0,
ax_anim_terminator
sCastformRainyAnims_3_8:
ax_anim 2, 0, 69, 1, -1, 1, -1,
ax_anim 6, 0, 70, 2, -2, 2, -2,
ax_anim 1, 0, 69, 0, 0, 0, 0,
ax_anim 1, 2, 69, -4, 4, -4, 4,
ax_anim 1, 0, 69, -13, 14, -13, 13,
ax_anim 2, 0, 71, -22, 21, -22, 21,
ax_anim 2, 1, 71, -23, 20, -23, 20,
ax_anim 2, 0, 71, -22, 21, -22, 21,
ax_anim 2, 0, 71, -23, 20, -23, 20,
ax_anim 2, 0, 69, -8, 8, -8, 8,
ax_anim_terminator
.align 2
sCastformRainyAnims_4_1:
ax_anim 2, 0, 73, 0, -2, 0, -2,
ax_anim 6, 2, 73, 0, -3, 0, -3,
ax_anim 2, 0, 72, 0, -1, 0, -1,
ax_anim 2, 1, 74, 0, 3, 0, 3,
ax_anim 2, 0, 74, 1, 3, 1, 3,
ax_anim 2, 0, 74, 0, 3, 0, 3,
ax_anim 2, 0, 74, 1, 3, 1, 3,
ax_anim 2, 0, 74, 0, 3, 0, 3,
ax_anim 2, 0, 74, 1, 3, 1, 3,
ax_anim 2, 0, 74, 0, 3, 0, 3,
ax_anim 2, 0, 72, 0, 1, 0, 1,
ax_anim_terminator
sCastformRainyAnims_4_2:
ax_anim 2, 0, 76, -2, -2, -2, -2,
ax_anim 6, 2, 76, -3, -3, -3, -3,
ax_anim 2, 0, 75, -1, -1, -1, -1,
ax_anim 2, 1, 77, 2, 2, 2, 2,
ax_anim 2, 0, 77, 3, 1, 3, 1,
ax_anim 2, 0, 77, 2, 2, 2, 2,
ax_anim 2, 0, 77, 3, 1, 3, 1,
ax_anim 2, 0, 77, 2, 2, 2, 2,
ax_anim 2, 0, 77, 3, 1, 3, 1,
ax_anim 2, 0, 77, 2, 2, 2, 2,
ax_anim 2, 0, 75, 1, 1, 1, 1,
ax_anim_terminator
sCastformRainyAnims_4_3:
ax_anim 2, 0, 79, -2, 0, -2, 0,
ax_anim 6, 2, 79, -3, 0, -3, 0,
ax_anim 2, 0, 78, -1, 0, -1, 0,
ax_anim 2, 1, 80, 2, 0, 2, 0,
ax_anim 2, 0, 80, 2, 1, 2, 1,
ax_anim 2, 0, 80, 2, 0, 2, 0,
ax_anim 2, 0, 80, 2, 1, 2, 1,
ax_anim 2, 0, 80, 2, 0, 2, 0,
ax_anim 2, 0, 80, 2, 1, 2, 1,
ax_anim 2, 0, 80, 2, 0, 2, 0,
ax_anim 2, 0, 78, 1, 0, 1, 0,
ax_anim_terminator
sCastformRainyAnims_4_4:
ax_anim 2, 0, 82, -2, 2, -2, 2,
ax_anim 6, 2, 82, -3, 3, -3, 3,
ax_anim 2, 0, 81, -1, 1, -1, 1,
ax_anim 2, 1, 83, 2, -2, 2, -2,
ax_anim 2, 0, 83, 3, -1, 3, -1,
ax_anim 2, 0, 83, 2, -2, 2, -2,
ax_anim 2, 0, 83, 3, -1, 3, -1,
ax_anim 2, 0, 83, 2, -2, 2, -2,
ax_anim 2, 0, 83, 3, -1, 3, -1,
ax_anim 2, 0, 83, 2, -2, 2, -2,
ax_anim 2, 0, 81, 1, -1, 1, -1,
ax_anim_terminator
sCastformRainyAnims_4_5:
ax_anim 2, 0, 85, 0, 2, 0, 2,
ax_anim 6, 2, 85, 0, 3, 0, 3,
ax_anim 2, 0, 84, 0, 1, 0, 1,
ax_anim 2, 1, 86, 0, -3, 0, -3,
ax_anim 2, 0, 86, 1, -3, 1, -3,
ax_anim 2, 0, 86, 0, -3, 0, -3,
ax_anim 2, 0, 86, 1, -3, 1, -3,
ax_anim 2, 0, 86, 0, -3, 0, -3,
ax_anim 2, 0, 86, 1, -3, 1, -3,
ax_anim 2, 0, 86, 0, -3, 0, -3,
ax_anim 2, 0, 84, 0, -1, 0, -1,
ax_anim_terminator
sCastformRainyAnims_4_6:
ax_anim 2, 0, 88, 2, 2, 2, 2,
ax_anim 6, 2, 88, 3, 3, 3, 3,
ax_anim 2, 0, 87, 1, 1, 1, 1,
ax_anim 2, 1, 89, -2, -2, -2, -2,
ax_anim 2, 0, 89, -3, -1, -3, -1,
ax_anim 2, 0, 89, -2, -2, -2, -2,
ax_anim 2, 0, 89, -3, -1, -3, -1,
ax_anim 2, 0, 89, -2, -2, -2, -2,
ax_anim 2, 0, 89, -3, -1, -3, -1,
ax_anim 2, 0, 89, -2, -2, -2, -2,
ax_anim 2, 0, 87, -1, -1, -1, -1,
ax_anim_terminator
sCastformRainyAnims_4_7:
ax_anim 2, 0, 91, 2, 0, 2, 0,
ax_anim 6, 2, 91, 3, 0, 3, 0,
ax_anim 2, 0, 90, 1, 0, 1, 0,
ax_anim 2, 1, 92, -2, 0, -2, 0,
ax_anim 2, 0, 92, -2, 1, -2, 1,
ax_anim 2, 0, 92, -2, 0, -2, 0,
ax_anim 2, 0, 92, -2, 1, -2, 1,
ax_anim 2, 0, 92, -2, 0, -2, 0,
ax_anim 2, 0, 92, -2, 1, -2, 1,
ax_anim 2, 0, 92, -2, 0, -2, 0,
ax_anim 2, 0, 90, -1, 0, -1, 0,
ax_anim_terminator
sCastformRainyAnims_4_8:
ax_anim 2, 0, 94, 2, -2, 2, -2,
ax_anim 6, 2, 94, 3, -3, 3, -3,
ax_anim 2, 0, 93, 1, -1, 1, -1,
ax_anim 2, 1, 95, -2, 2, -2, 2,
ax_anim 2, 0, 95, -3, 1, -3, 1,
ax_anim 2, 0, 95, -2, 2, -2, 2,
ax_anim 2, 0, 95, -3, 1, -3, 1,
ax_anim 2, 0, 95, -2, 2, -2, 2,
ax_anim 2, 0, 95, -3, 1, -3, 1,
ax_anim 2, 0, 95, -2, 2, -2, 2,
ax_anim 2, 0, 93, -1, 1, -1, 1,
ax_anim_terminator
.align 2
sCastformRainyAnims_5_1:
ax_anim 6, 0, 97, 0, 0, 0, 0,
ax_anim 2, 0, 96, 0, -2, 0, 0,
ax_anim 1, 0, 103, 0, -4, 0, 0,
ax_anim 1, 0, 102, 0, -5, 0, 0,
ax_anim 1, 0, 101, 0, -6, 0, 0,
ax_anim 1, 2, 100, 0, -7, 0, 0,
ax_anim 1, 0, 99, 0, -8, 0, 0,
ax_anim 1, 0, 98, 0, -9, 0, 0,
ax_anim 1, 0, 97, 0, -9, 0, 0,
ax_anim 1, 0, 96, 0, -9, 0, 0,
ax_anim 1, 0, 103, 0, -9, 0, 0,
ax_anim 1, 0, 102, 0, -8, 0, 0,
ax_anim 1, 0, 101, 0, -7, 0, 0,
ax_anim 1, 0, 100, 0, -6, 0, 0,
ax_anim 1, 0, 99, 0, -5, 0, 0,
ax_anim 1, 1, 98, 0, -4, 0, 0,
ax_anim 2, 0, 97, 0, -2, 0, 0,
ax_anim 2, 0, 96, 0, 0, 0, 0,
ax_anim_terminator
sCastformRainyAnims_5_2:
ax_anim 6, 0, 105, 0, 0, 0, 0,
ax_anim 2, 0, 104, 0, -2, 0, 0,
ax_anim 1, 0, 111, 0, -4, 0, 0,
ax_anim 1, 0, 110, 0, -5, 0, 0,
ax_anim 1, 0, 109, 0, -6, 0, 0,
ax_anim 1, 2, 108, 0, -7, 0, 0,
ax_anim 1, 0, 107, 0, -8, 0, 0,
ax_anim 1, 0, 106, 0, -9, 0, 0,
ax_anim 1, 0, 105, 0, -9, 0, 0,
ax_anim 1, 0, 104, 0, -9, 0, 0,
ax_anim 1, 0, 111, 0, -9, 0, 0,
ax_anim 1, 0, 110, 0, -8, 0, 0,
ax_anim 1, 0, 109, 0, -7, 0, 0,
ax_anim 1, 0, 108, 0, -6, 0, 0,
ax_anim 1, 0, 107, 0, -5, 0, 0,
ax_anim 1, 1, 106, 0, -4, 0, 0,
ax_anim 2, 0, 105, 0, -2, 0, 0,
ax_anim 2, 0, 104, 0, 0, 0, 0,
ax_anim_terminator
sCastformRainyAnims_5_3:
ax_anim 6, 0, 113, 0, 0, 0, 0,
ax_anim 2, 0, 112, 0, -2, 0, 0,
ax_anim 1, 0, 119, 0, -4, 0, 0,
ax_anim 1, 0, 118, 0, -5, 0, 0,
ax_anim 1, 0, 117, 0, -6, 0, 0,
ax_anim 1, 2, 116, 0, -7, 0, 0,
ax_anim 1, 0, 115, 0, -8, 0, 0,
ax_anim 1, 0, 114, 0, -9, 0, 0,
ax_anim 1, 0, 113, 0, -9, 0, 0,
ax_anim 1, 0, 112, 0, -9, 0, 0,
ax_anim 1, 0, 119, 0, -9, 0, 0,
ax_anim 1, 0, 118, 0, -8, 0, 0,
ax_anim 1, 0, 117, 0, -7, 0, 0,
ax_anim 1, 0, 116, 0, -6, 0, 0,
ax_anim 1, 0, 115, 0, -5, 0, 0,
ax_anim 1, 1, 114, 0, -4, 0, 0,
ax_anim 2, 0, 113, 0, -2, 0, 0,
ax_anim 2, 0, 112, 0, 0, 0, 0,
ax_anim_terminator
sCastformRainyAnims_5_4:
ax_anim 6, 0, 121, 0, 0, 0, 0,
ax_anim 2, 0, 120, 0, -2, 0, 0,
ax_anim 1, 0, 127, 0, -4, 0, 0,
ax_anim 1, 0, 126, 0, -5, 0, 0,
ax_anim 1, 0, 125, 0, -6, 0, 0,
ax_anim 1, 2, 124, 0, -7, 0, 0,
ax_anim 1, 0, 123, 0, -8, 0, 0,
ax_anim 1, 0, 122, 0, -9, 0, 0,
ax_anim 1, 0, 121, 0, -9, 0, 0,
ax_anim 1, 0, 120, 0, -9, 0, 0,
ax_anim 1, 0, 127, 0, -9, 0, 0,
ax_anim 1, 0, 126, 0, -8, 0, 0,
ax_anim 1, 0, 125, 0, -7, 0, 0,
ax_anim 1, 0, 124, 0, -6, 0, 0,
ax_anim 1, 0, 123, 0, -5, 0, 0,
ax_anim 1, 1, 122, 0, -4, 0, 0,
ax_anim 2, 0, 121, 0, -2, 0, 0,
ax_anim 2, 0, 120, 0, 0, 0, 0,
ax_anim_terminator
sCastformRainyAnims_5_5:
ax_anim 6, 0, 129, 0, 0, 0, 0,
ax_anim 2, 0, 128, 0, -2, 0, 0,
ax_anim 1, 0, 135, 0, -4, 0, 0,
ax_anim 1, 0, 134, 0, -5, 0, 0,
ax_anim 1, 0, 133, 0, -6, 0, 0,
ax_anim 1, 2, 132, 0, -7, 0, 0,
ax_anim 1, 0, 131, 0, -8, 0, 0,
ax_anim 1, 0, 130, 0, -9, 0, 0,
ax_anim 1, 0, 129, 0, -9, 0, 0,
ax_anim 1, 0, 128, 0, -9, 0, 0,
ax_anim 1, 0, 135, 0, -9, 0, 0,
ax_anim 1, 0, 134, 0, -8, 0, 0,
ax_anim 1, 0, 133, 0, -7, 0, 0,
ax_anim 1, 0, 132, 0, -6, 0, 0,
ax_anim 1, 0, 131, 0, -5, 0, 0,
ax_anim 1, 1, 130, 0, -4, 0, 0,
ax_anim 2, 0, 129, 0, -2, 0, 0,
ax_anim 2, 0, 128, 0, 0, 0, 0,
ax_anim_terminator
sCastformRainyAnims_5_6:
ax_anim 6, 0, 137, 0, 0, 0, 0,
ax_anim 2, 0, 136, 0, -2, 0, 0,
ax_anim 1, 0, 143, 0, -4, 0, 0,
ax_anim 1, 0, 142, 0, -5, 0, 0,
ax_anim 1, 0, 141, 0, -6, 0, 0,
ax_anim 1, 2, 140, 0, -7, 0, 0,
ax_anim 1, 0, 139, 0, -8, 0, 0,
ax_anim 1, 0, 138, 0, -9, 0, 0,
ax_anim 1, 0, 137, 0, -9, 0, 0,
ax_anim 1, 0, 136, 0, -9, 0, 0,
ax_anim 1, 0, 143, 0, -9, 0, 0,
ax_anim 1, 0, 142, 0, -8, 0, 0,
ax_anim 1, 0, 141, 0, -7, 0, 0,
ax_anim 1, 0, 140, 0, -6, 0, 0,
ax_anim 1, 0, 139, 0, -5, 0, 0,
ax_anim 1, 1, 138, 0, -4, 0, 0,
ax_anim 2, 0, 137, 0, -2, 0, 0,
ax_anim 2, 0, 136, 0, 0, 0, 0,
ax_anim_terminator
sCastformRainyAnims_5_7:
ax_anim 6, 0, 145, 0, 0, 0, 0,
ax_anim 2, 0, 144, 0, -2, 0, 0,
ax_anim 1, 0, 151, 0, -4, 0, 0,
ax_anim 1, 0, 150, 0, -5, 0, 0,
ax_anim 1, 0, 149, 0, -6, 0, 0,
ax_anim 1, 2, 148, 0, -7, 0, 0,
ax_anim 1, 0, 147, 0, -8, 0, 0,
ax_anim 1, 0, 146, 0, -9, 0, 0,
ax_anim 1, 0, 145, 0, -9, 0, 0,
ax_anim 1, 0, 144, 0, -9, 0, 0,
ax_anim 1, 0, 151, 0, -9, 0, 0,
ax_anim 1, 0, 150, 0, -8, 0, 0,
ax_anim 1, 0, 149, 0, -7, 0, 0,
ax_anim 1, 0, 148, 0, -6, 0, 0,
ax_anim 1, 0, 147, 0, -5, 0, 0,
ax_anim 1, 1, 146, 0, -4, 0, 0,
ax_anim 2, 0, 145, 0, -2, 0, 0,
ax_anim 2, 0, 144, 0, 0, 0, 0,
ax_anim_terminator
sCastformRainyAnims_5_8:
ax_anim 6, 0, 153, 0, 0, 0, 0,
ax_anim 2, 0, 152, 0, -2, 0, 0,
ax_anim 1, 0, 159, 0, -4, 0, 0,
ax_anim 1, 0, 158, 0, -5, 0, 0,
ax_anim 1, 0, 157, 0, -6, 0, 0,
ax_anim 1, 2, 156, 0, -7, 0, 0,
ax_anim 1, 0, 155, 0, -8, 0, 0,
ax_anim 1, 0, 154, 0, -9, 0, 0,
ax_anim 1, 0, 153, 0, -9, 0, 0,
ax_anim 1, 0, 152, 0, -9, 0, 0,
ax_anim 1, 0, 159, 0, -9, 0, 0,
ax_anim 1, 0, 158, 0, -8, 0, 0,
ax_anim 1, 0, 157, 0, -7, 0, 0,
ax_anim 1, 0, 156, 0, -6, 0, 0,
ax_anim 1, 0, 155, 0, -5, 0, 0,
ax_anim 1, 1, 154, 0, -4, 0, 0,
ax_anim 2, 0, 153, 0, -2, 0, 0,
ax_anim 2, 0, 152, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sCastformRainyAnims_6_1:
ax_anim 10, 0, 160, 0, 0, 0, 0,
ax_anim 10, 0, 160, 0, -1, 0, 0,
ax_anim 16, 0, 160, 0, -2, 0, 0,
ax_anim 10, 0, 161, 0, -2, 0, 0,
ax_anim 10, 0, 161, 0, -1, 0, 0,
ax_anim 16, 0, 161, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sCastformRainyAnims_7_1:
ax_anim 2, 0, 162, 0, -2, 0, -2,
ax_anim 8, 0, 162, 0, -3, 0, -3,
ax_anim_terminator
sCastformRainyAnims_7_2:
ax_anim 2, 0, 163, -2, -2, -2, -2,
ax_anim 8, 0, 163, -3, -3, -3, -3,
ax_anim_terminator
sCastformRainyAnims_7_3:
ax_anim 2, 0, 164, -2, 0, -2, 0,
ax_anim 8, 0, 164, -3, 0, -3, 0,
ax_anim_terminator
sCastformRainyAnims_7_4:
ax_anim 2, 0, 165, -2, 2, -2, 2,
ax_anim 8, 0, 165, -3, 3, -3, 3,
ax_anim_terminator
sCastformRainyAnims_7_5:
ax_anim 2, 0, 166, 0, 2, 0, 2,
ax_anim 8, 0, 166, 0, 3, 0, 3,
ax_anim_terminator
sCastformRainyAnims_7_6:
ax_anim 2, 0, 167, 2, 2, 2, 2,
ax_anim 8, 0, 167, 3, 3, 3, 3,
ax_anim_terminator
sCastformRainyAnims_7_7:
ax_anim 2, 0, 168, 2, 0, 2, 0,
ax_anim 8, 0, 168, 3, 0, 3, 0,
ax_anim_terminator
sCastformRainyAnims_7_8:
ax_anim 2, 0, 169, 2, -2, 2, -2,
ax_anim 8, 0, 169, 3, -3, 3, -3,
ax_anim_terminator
.align 2
sCastformRainyAnims_8_1:
ax_anim 6, 0, 170, 0, 0, 0, 0,
ax_anim 6, 0, 171, 0, -1, 0, 0,
ax_anim 6, 0, 172, 0, -2, 0, 0,
ax_anim 6, 0, 171, 0, -2, 0, 0,
ax_anim 6, 0, 170, 0, -1, 0, 0,
ax_anim 6, 0, 171, 0, 0, 0, 0,
ax_anim 6, 0, 172, 0, 1, 0, 0,
ax_anim 6, 0, 171, 0, 1, 0, 0,
ax_anim_terminator
sCastformRainyAnims_8_2:
ax_anim 6, 0, 173, 0, 0, 0, 0,
ax_anim 6, 0, 174, 0, -1, 0, 0,
ax_anim 6, 0, 175, 0, -2, 0, 0,
ax_anim 6, 0, 174, 0, -2, 0, 0,
ax_anim 6, 0, 173, 0, -1, 0, 0,
ax_anim 6, 0, 174, 0, 0, 0, 0,
ax_anim 6, 0, 175, 0, 1, 0, 0,
ax_anim 6, 0, 174, 0, 1, 0, 0,
ax_anim_terminator
sCastformRainyAnims_8_3:
ax_anim 6, 0, 176, 0, 0, 0, 0,
ax_anim 6, 0, 177, 0, -1, 0, 0,
ax_anim 6, 0, 178, 0, -2, 0, 0,
ax_anim 6, 0, 177, 0, -2, 0, 0,
ax_anim 6, 0, 176, 0, -1, 0, 0,
ax_anim 6, 0, 177, 0, 0, 0, 0,
ax_anim 6, 0, 178, 0, 1, 0, 0,
ax_anim 6, 0, 177, 0, 1, 0, 0,
ax_anim_terminator
sCastformRainyAnims_8_4:
ax_anim 6, 0, 179, 0, 0, 0, 0,
ax_anim 6, 0, 180, 0, -1, 0, 0,
ax_anim 6, 0, 181, 0, -2, 0, 0,
ax_anim 6, 0, 180, 0, -2, 0, 0,
ax_anim 6, 0, 179, 0, -1, 0, 0,
ax_anim 6, 0, 180, 0, 0, 0, 0,
ax_anim 6, 0, 181, 0, 1, 0, 0,
ax_anim 6, 0, 180, 0, 1, 0, 0,
ax_anim_terminator
sCastformRainyAnims_8_5:
ax_anim 6, 0, 182, 0, 0, 0, 0,
ax_anim 6, 0, 183, 0, -1, 0, 0,
ax_anim 6, 0, 184, 0, -2, 0, 0,
ax_anim 6, 0, 183, 0, -2, 0, 0,
ax_anim 6, 0, 182, 0, -1, 0, 0,
ax_anim 6, 0, 183, 0, 0, 0, 0,
ax_anim 6, 0, 184, 0, 1, 0, 0,
ax_anim 6, 0, 183, 0, 1, 0, 0,
ax_anim_terminator
sCastformRainyAnims_8_6:
ax_anim 6, 0, 185, 0, 0, 0, 0,
ax_anim 6, 0, 186, 0, -1, 0, 0,
ax_anim 6, 0, 187, 0, -2, 0, 0,
ax_anim 6, 0, 186, 0, -2, 0, 0,
ax_anim 6, 0, 185, 0, -1, 0, 0,
ax_anim 6, 0, 186, 0, 0, 0, 0,
ax_anim 6, 0, 187, 0, 1, 0, 0,
ax_anim 6, 0, 186, 0, 1, 0, 0,
ax_anim_terminator
sCastformRainyAnims_8_7:
ax_anim 6, 0, 188, 0, 0, 0, 0,
ax_anim 6, 0, 189, 0, -1, 0, 0,
ax_anim 6, 0, 190, 0, -2, 0, 0,
ax_anim 6, 0, 189, 0, -2, 0, 0,
ax_anim 6, 0, 188, 0, -1, 0, 0,
ax_anim 6, 0, 189, 0, 0, 0, 0,
ax_anim 6, 0, 190, 0, 1, 0, 0,
ax_anim 6, 0, 189, 0, 1, 0, 0,
ax_anim_terminator
sCastformRainyAnims_8_8:
ax_anim 6, 0, 191, 0, 0, 0, 0,
ax_anim 6, 0, 192, 0, -1, 0, 0,
ax_anim 6, 0, 193, 0, -2, 0, 0,
ax_anim 6, 0, 192, 0, -2, 0, 0,
ax_anim 6, 0, 191, 0, -1, 0, 0,
ax_anim 6, 0, 192, 0, 0, 0, 0,
ax_anim 6, 0, 193, 0, 1, 0, 0,
ax_anim 6, 0, 192, 0, 1, 0, 0,
ax_anim_terminator
.align 2
sCastformRainyAnims_9_1:
ax_anim 2, 0, 194, 0, 0, 0, 0,
ax_anim 1, 0, 195, 6, 3, 6, 3,
ax_anim 2, 0, 196, 10, 11, 10, 11,
ax_anim 2, 0, 197, 7, 19, 7, 19,
ax_anim 3, 0, 198, 0, 22, 0, 22,
ax_anim 2, 3, 199, -7, 19, -7, 19,
ax_anim 2, 0, 200, -10, 11, -10, 11,
ax_anim 1, 0, 201, -6, 3, -6, 3,
ax_anim 1, 0, 194, 0, 0, 0, 0,
ax_anim_terminator
sCastformRainyAnims_9_2:
ax_anim 2, 0, 201, 0, 0, 0, 0,
ax_anim 1, 0, 194, 10, 2, 10, 2,
ax_anim 2, 0, 195, 18, 6, 18, 6,
ax_anim 2, 0, 196, 25, 15, 25, 15,
ax_anim 3, 0, 197, 24, 22, 24, 22,
ax_anim 2, 3, 198, 14, 22, 14, 22,
ax_anim 2, 0, 199, 5, 18, 5, 18,
ax_anim 1, 0, 200, 0, 7, 0, 7,
ax_anim 1, 0, 201, 0, 0, 0, 0,
ax_anim_terminator
sCastformRainyAnims_9_3:
ax_anim 2, 0, 200, 0, 0, 0, 0,
ax_anim 1, 0, 201, 4, -3, 4, -3,
ax_anim 2, 0, 194, 11, -4, 11, -4,
ax_anim 2, 0, 195, 18, -3, 18, -3,
ax_anim 3, 0, 196, 24, 0, 24, 0,
ax_anim 2, 3, 197, 20, 4, 20, 4,
ax_anim 2, 0, 198, 12, 6, 12, 6,
ax_anim 1, 0, 199, 5, 5, 5, 5,
ax_anim 1, 0, 200, 0, 0, 0, 0,
ax_anim_terminator
sCastformRainyAnims_9_4:
ax_anim 2, 0, 199, 0, 0, 0, 0,
ax_anim 1, 0, 200, 0, -8, 0, -8,
ax_anim 2, 0, 201, 6, -16, 6, -16,
ax_anim 2, 0, 194, 15, -20, 15, -20,
ax_anim 3, 0, 195, 23, -20, 23, -20,
ax_anim 2, 3, 196, 25, -12, 25, -12,
ax_anim 2, 0, 197, 19, -4, 19, -4,
ax_anim 1, 0, 198, 9, 0, 9, 0,
ax_anim 1, 0, 199, 0, 0, 0, 0,
ax_anim_terminator
sCastformRainyAnims_9_5:
ax_anim 2, 0, 198, 0, 0, 0, 0,
ax_anim 1, 0, 199, -5, -2, -5, -2,
ax_anim 2, 0, 200, -9, -11, -9, -11,
ax_anim 2, 0, 201, -6, -18, -6, -18,
ax_anim 3, 0, 194, 0, -20, 0, -20,
ax_anim 2, 3, 195, 6, -18, 6, -18,
ax_anim 2, 0, 196, 9, -11, 9, -11,
ax_anim 1, 0, 197, 5, -2, 5, -2,
ax_anim 1, 0, 198, 0, 0, 0, 0,
ax_anim_terminator
sCastformRainyAnims_9_6:
ax_anim 2, 0, 197, 0, 0, 0, 0,
ax_anim 1, 0, 196, 0, -8, 0, -8,
ax_anim 2, 0, 195, -6, -16, -6, -16,
ax_anim 2, 0, 194, -15, -20, -15, -20,
ax_anim 3, 0, 201, -23, -20, -23, -20,
ax_anim 2, 3, 200, -25, -12, -25, -12,
ax_anim 2, 0, 199, -19, -4, -19, -4,
ax_anim 1, 0, 198, -9, 0, -9, 0,
ax_anim 1, 0, 197, 0, 0, 0, 0,
ax_anim_terminator
sCastformRainyAnims_9_7:
ax_anim 2, 0, 196, 0, 0, 0, 0,
ax_anim 1, 0, 195, -4, -3, -4, -3,
ax_anim 2, 0, 194, -11, -4, -11, -4,
ax_anim 2, 0, 201, -18, -3, -18, -3,
ax_anim 3, 0, 200, -24, 0, -24, 0,
ax_anim 2, 3, 199, -20, 4, -20, 4,
ax_anim 2, 0, 198, -12, 6, -12, 6,
ax_anim 1, 0, 197, -5, 5, -5, 5,
ax_anim 1, 0, 196, 0, 0, 0, 0,
ax_anim_terminator
sCastformRainyAnims_9_8:
ax_anim 2, 0, 195, 0, 0, 0, 0,
ax_anim 1, 0, 194, -10, 2, -10, 2,
ax_anim 2, 0, 201, -18, 6, -18, 6,
ax_anim 2, 0, 200, -25, 15, -25, 15,
ax_anim 3, 0, 199, -24, 22, -24, 22,
ax_anim 2, 3, 198, -14, 22, -14, 22,
ax_anim 2, 0, 197, -5, 18, -5, 18,
ax_anim 1, 0, 196, 0, 7, 0, 7,
ax_anim 1, 0, 195, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sCastformRainyAnims_10_1:
ax_anim 2, 0, 202, 0, 0, 0, 0,
ax_anim 2, 0, 202, 6, 0, 6, 0,
ax_anim 2, 0, 202, -6, 0, -6, 0,
ax_anim 2, 0, 202, 10, 0, 10, 0,
ax_anim 2, 0, 202, -10, 0, -10, 0,
ax_anim 2, 0, 202, 12, 0, 12, 0,
ax_anim 3, 0, 202, -12, 0, -12, 0,
ax_anim 3, 0, 202, 13, 0, 13, 0,
ax_anim 3, 0, 202, -13, 0, -13, 0,
ax_anim 2, 0, 202, 12, 0, 12, 0,
ax_anim 3, 0, 202, -12, 0, -12, 0,
ax_anim 2, 0, 202, 10, 0, 10, 0,
ax_anim 2, 0, 202, -10, 0, -10, 0,
ax_anim 2, 0, 202, 6, 0, 6, 0,
ax_anim 2, 0, 202, -6, 0, -6, 0,
ax_anim 2, 0, 202, 0, 0, 0, 0,
ax_anim_terminator
sCastformRainyAnims_10_2:
ax_anim 2, 0, 203, 0, 0, 0, 0,
ax_anim 2, 0, 203, 6, -6, 6, -6,
ax_anim 2, 0, 203, -6, 6, -6, 6,
ax_anim 2, 0, 203, 10, -10, 10, -10,
ax_anim 2, 0, 203, -10, 10, -10, 10,
ax_anim 2, 0, 203, 12, -12, 12, -12,
ax_anim 3, 0, 203, -12, 12, -12, 12,
ax_anim 3, 0, 203, 13, -13, 13, -13,
ax_anim 3, 0, 203, -13, 13, -13, 13,
ax_anim 2, 0, 203, 12, -12, 12, -12,
ax_anim 3, 0, 203, -12, 12, -12, 12,
ax_anim 2, 0, 203, 10, -10, 10, -10,
ax_anim 2, 0, 203, -10, 10, -10, 10,
ax_anim 2, 0, 203, 6, -6, 6, -6,
ax_anim 2, 0, 203, -6, 6, -6, 6,
ax_anim 2, 0, 203, 0, 0, 0, 0,
ax_anim_terminator
sCastformRainyAnims_10_3:
ax_anim 2, 0, 204, 0, 0, 0, 0,
ax_anim 2, 0, 204, 0, -6, 0, -6,
ax_anim 2, 0, 204, 0, 6, 0, 6,
ax_anim 2, 0, 204, 0, -10, 0, -10,
ax_anim 2, 0, 204, 0, 10, 0, 10,
ax_anim 2, 0, 204, 0, -12, 0, -12,
ax_anim 3, 0, 204, 0, 12, 0, 12,
ax_anim 3, 0, 204, 0, -13, 0, -13,
ax_anim 3, 0, 204, 0, 13, 0, 13,
ax_anim 2, 0, 204, 0, -12, 0, -12,
ax_anim 3, 0, 204, 0, 12, 0, 12,
ax_anim 2, 0, 204, 0, -10, 0, -10,
ax_anim 2, 0, 204, 0, 10, 0, 10,
ax_anim 2, 0, 204, 0, -6, 0, -6,
ax_anim 2, 0, 204, 0, 6, 0, 6,
ax_anim 2, 0, 204, 0, 0, 0, 0,
ax_anim_terminator
sCastformRainyAnims_10_4:
ax_anim 2, 0, 205, 0, 0, 0, 0,
ax_anim 2, 0, 205, -6, -6, -6, -6,
ax_anim 2, 0, 205, 6, 6, 6, 6,
ax_anim 2, 0, 205, -10, -10, -10, -10,
ax_anim 2, 0, 205, 10, 10, 10, 10,
ax_anim 2, 0, 205, -12, -12, -12, -12,
ax_anim 3, 0, 205, 12, 12, 12, 12,
ax_anim 3, 0, 205, -13, -13, -13, -13,
ax_anim 3, 0, 205, 13, 13, 13, 13,
ax_anim 2, 0, 205, -12, -12, -12, -12,
ax_anim 3, 0, 205, 12, 12, 12, 12,
ax_anim 2, 0, 205, -10, -10, -10, -10,
ax_anim 2, 0, 205, 10, 10, 10, 10,
ax_anim 2, 0, 205, -6, -6, -6, -6,
ax_anim 2, 0, 205, 6, 6, 6, 6,
ax_anim 2, 0, 205, 0, 0, 0, 0,
ax_anim_terminator
sCastformRainyAnims_10_5:
ax_anim 2, 0, 206, 0, 0, 0, 0,
ax_anim 2, 0, 206, 6, 0, 6, 0,
ax_anim 2, 0, 206, -6, 0, -6, 0,
ax_anim 2, 0, 206, 10, 0, 10, 0,
ax_anim 2, 0, 206, -10, 0, -10, 0,
ax_anim 2, 0, 206, 12, 0, 12, 0,
ax_anim 3, 0, 206, -12, 0, -12, 0,
ax_anim 3, 0, 206, 13, 0, 13, 0,
ax_anim 3, 0, 206, -13, 0, -13, 0,
ax_anim 2, 0, 206, 12, 0, 12, 0,
ax_anim 3, 0, 206, -12, 0, -12, 0,
ax_anim 2, 0, 206, 10, 0, 10, 0,
ax_anim 2, 0, 206, -10, 0, -10, 0,
ax_anim 2, 0, 206, 6, 0, 6, 0,
ax_anim 2, 0, 206, -6, 0, -6, 0,
ax_anim 2, 0, 206, 0, 0, 0, 0,
ax_anim_terminator
sCastformRainyAnims_10_6:
ax_anim 2, 0, 207, 0, 0, 0, 0,
ax_anim 2, 0, 207, 6, -6, 6, -6,
ax_anim 2, 0, 207, -6, 6, -6, 6,
ax_anim 2, 0, 207, 10, -10, 10, -10,
ax_anim 2, 0, 207, -10, 10, -10, 10,
ax_anim 2, 0, 207, 12, -12, 12, -12,
ax_anim 3, 0, 207, -12, 12, -12, 12,
ax_anim 3, 0, 207, 13, -13, 13, -13,
ax_anim 3, 0, 207, -13, 13, -13, 13,
ax_anim 2, 0, 207, 12, -12, 12, -12,
ax_anim 3, 0, 207, -12, 12, -12, 12,
ax_anim 2, 0, 207, 10, -10, 10, -10,
ax_anim 2, 0, 207, -10, 10, -10, 10,
ax_anim 2, 0, 207, 6, -6, 6, -6,
ax_anim 2, 0, 207, -6, 6, -6, 6,
ax_anim 2, 0, 207, 0, 0, 0, 0,
ax_anim_terminator
sCastformRainyAnims_10_7:
ax_anim 2, 0, 208, 0, 0, 0, 0,
ax_anim 2, 0, 208, 0, -6, 0, -6,
ax_anim 2, 0, 208, 0, 6, 0, 6,
ax_anim 2, 0, 208, 0, -10, 0, -10,
ax_anim 2, 0, 208, 0, 10, 0, 10,
ax_anim 2, 0, 208, 0, -12, 0, -12,
ax_anim 3, 0, 208, 0, 12, 0, 12,
ax_anim 3, 0, 208, 0, -13, 0, -13,
ax_anim 3, 0, 208, 0, 13, 0, 13,
ax_anim 2, 0, 208, 0, -12, 0, -12,
ax_anim 3, 0, 208, 0, 12, 0, 12,
ax_anim 2, 0, 208, 0, -10, 0, -10,
ax_anim 2, 0, 208, 0, 10, 0, 10,
ax_anim 2, 0, 208, 0, -6, 0, -6,
ax_anim 2, 0, 208, 0, 6, 0, 6,
ax_anim 2, 0, 208, 0, 0, 0, 0,
ax_anim_terminator
sCastformRainyAnims_10_8:
ax_anim 2, 0, 209, 0, 0, 0, 0,
ax_anim 2, 0, 209, -6, -6, -6, -6,
ax_anim 2, 0, 209, 6, 6, 6, 6,
ax_anim 2, 0, 209, -10, -10, -10, -10,
ax_anim 2, 0, 209, 10, 10, 10, 10,
ax_anim 2, 0, 209, -12, -12, -12, -12,
ax_anim 3, 0, 209, 12, 12, 12, 12,
ax_anim 3, 0, 209, -13, -13, -13, -13,
ax_anim 3, 0, 209, 13, 13, 13, 13,
ax_anim 2, 0, 209, -12, -12, -12, -12,
ax_anim 3, 0, 209, 12, 12, 12, 12,
ax_anim 2, 0, 209, -10, -10, -10, -10,
ax_anim 2, 0, 209, 10, 10, 10, 10,
ax_anim 2, 0, 209, -6, -6, -6, -6,
ax_anim 2, 0, 209, 6, 6, 6, 6,
ax_anim 2, 0, 209, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sCastformRainyAnims_11_1:
ax_anim 2, 0, 210, 0, 3, 0, 0,
ax_anim 1, 0, 211, 0, -10, 0, 0,
ax_anim 2, 0, 211, 0, -16, 0, 0,
ax_anim 3, 0, 211, 0, -20, 0, 0,
ax_anim 4, 0, 211, 0, -21, 0, 0,
ax_anim 4, 0, 210, 0, -23, 0, 0,
ax_anim 3, 0, 212, 0, -22, 0, 0,
ax_anim 2, 0, 212, 0, -18, 0, 0,
ax_anim 1, 0, 212, 0, -8, 0, 0,
ax_anim 2, 2, 210, 0, 3, 0, 0,
ax_anim_terminator
sCastformRainyAnims_11_2:
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 1, 0, 214, 0, -10, 0, 0,
ax_anim 2, 0, 214, 0, -16, 0, 0,
ax_anim 3, 0, 214, 0, -20, 0, 0,
ax_anim 4, 0, 214, 0, -21, 0, 0,
ax_anim 4, 0, 213, 0, -23, 0, 0,
ax_anim 3, 0, 215, 0, -22, 0, 0,
ax_anim 2, 0, 215, 0, -18, 0, 0,
ax_anim 1, 0, 215, 0, -8, 0, 0,
ax_anim 2, 2, 213, 0, 3, 0, 0,
ax_anim_terminator
sCastformRainyAnims_11_3:
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 1, 0, 217, 0, -10, 0, 0,
ax_anim 2, 0, 217, 0, -16, 0, 0,
ax_anim 3, 0, 217, 0, -20, 0, 0,
ax_anim 4, 0, 217, 0, -21, 0, 0,
ax_anim 4, 0, 216, 0, -22, 0, 0,
ax_anim 3, 0, 218, 0, -21, 0, 0,
ax_anim 2, 0, 218, 0, -18, 0, 0,
ax_anim 1, 0, 218, 0, -8, 0, 0,
ax_anim 2, 2, 216, 0, 3, 0, 0,
ax_anim_terminator
sCastformRainyAnims_11_4:
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 1, 0, 220, 0, -10, 0, 0,
ax_anim 2, 0, 220, 0, -16, 0, 0,
ax_anim 3, 0, 220, 0, -20, 0, 0,
ax_anim 4, 0, 220, 0, -21, 0, 0,
ax_anim 4, 0, 219, 0, -22, 0, 0,
ax_anim 3, 0, 221, 0, -21, 0, 0,
ax_anim 2, 0, 221, 0, -17, 0, 0,
ax_anim 1, 0, 221, 0, -8, 0, 0,
ax_anim 2, 2, 219, 0, 3, 0, 0,
ax_anim_terminator
sCastformRainyAnims_11_5:
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 1, 0, 223, 0, -10, 0, 0,
ax_anim 2, 0, 223, 0, -16, 0, 0,
ax_anim 3, 0, 223, 0, -20, 0, 0,
ax_anim 4, 0, 223, 0, -21, 0, 0,
ax_anim 4, 0, 222, 0, -21, 0, 0,
ax_anim 3, 0, 224, 0, -19, 0, 0,
ax_anim 2, 0, 224, 0, -18, 0, 0,
ax_anim 1, 0, 224, 0, -8, 0, 0,
ax_anim 2, 2, 222, 0, 3, 0, 0,
ax_anim_terminator
sCastformRainyAnims_11_6:
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 1, 0, 226, 0, -10, 0, 0,
ax_anim 2, 0, 226, 0, -16, 0, 0,
ax_anim 3, 0, 226, 0, -20, 0, 0,
ax_anim 4, 0, 226, 0, -21, 0, 0,
ax_anim 4, 0, 225, 0, -22, 0, 0,
ax_anim 3, 0, 227, 0, -21, 0, 0,
ax_anim 2, 0, 227, 0, -17, 0, 0,
ax_anim 1, 0, 227, 0, -8, 0, 0,
ax_anim 2, 2, 225, 0, 3, 0, 0,
ax_anim_terminator
sCastformRainyAnims_11_7:
ax_anim 2, 0, 228, 0, 0, 0, 0,
ax_anim 1, 0, 229, 0, -10, 0, 0,
ax_anim 2, 0, 229, 0, -16, 0, 0,
ax_anim 3, 0, 229, 0, -20, 0, 0,
ax_anim 4, 0, 229, 0, -21, 0, 0,
ax_anim 4, 0, 228, 0, -22, 0, 0,
ax_anim 3, 0, 230, 0, -21, 0, 0,
ax_anim 2, 0, 230, 0, -18, 0, 0,
ax_anim 1, 0, 230, 0, -8, 0, 0,
ax_anim 2, 2, 228, 0, 3, 0, 0,
ax_anim_terminator
sCastformRainyAnims_11_8:
ax_anim 2, 0, 231, 0, 0, 0, 0,
ax_anim 1, 0, 232, 0, -10, 0, 0,
ax_anim 2, 0, 232, 0, -16, 0, 0,
ax_anim 3, 0, 232, 0, -20, 0, 0,
ax_anim 4, 0, 232, 0, -21, 0, 0,
ax_anim 4, 0, 231, 0, -23, 0, 0,
ax_anim 3, 0, 233, 0, -22, 0, 0,
ax_anim 2, 0, 233, 0, -18, 0, 0,
ax_anim 1, 0, 233, 0, -8, 0, 0,
ax_anim 2, 2, 231, 0, 3, 0, 0,
ax_anim_terminator
.align 2
sCastformRainyAnims_12_1:
ax_anim 2, 0, 234, 1, 0, 1, 0,
ax_anim 2, 0, 234, 0, 0, 0, 0,
ax_anim 2, 0, 234, 1, 0, 1, 0,
ax_anim 2, 0, 234, 0, 0, 0, 0,
ax_anim 2, 0, 234, 1, 0, 1, 0,
ax_anim 2, 2, 234, 0, 0, 0, 0,
ax_anim 2, 0, 234, 1, 0, 1, 0,
ax_anim 2, 0, 234, 0, 0, 0, 0,
ax_anim 2, 0, 234, 1, 0, 1, 0,
ax_anim 2, 1, 234, 0, 0, 0, 0,
ax_anim_terminator
sCastformRainyAnims_12_2:
ax_anim 2, 0, 241, 1, -1, 1, -1,
ax_anim 2, 0, 241, 0, 0, 0, 0,
ax_anim 2, 0, 241, 1, -1, 1, -1,
ax_anim 2, 0, 241, 0, 0, 0, 0,
ax_anim 2, 0, 241, 1, -1, 1, -1,
ax_anim 2, 2, 241, 0, 0, 0, 0,
ax_anim 2, 0, 241, 1, -1, 1, -1,
ax_anim 2, 0, 241, 0, 0, 0, 0,
ax_anim 2, 0, 241, 1, -1, 1, -1,
ax_anim 2, 1, 241, 0, 0, 0, 0,
ax_anim_terminator
sCastformRainyAnims_12_3:
ax_anim 2, 0, 240, 0, -1, 0, -1,
ax_anim 2, 0, 240, 0, 0, 0, 0,
ax_anim 2, 0, 240, 0, -1, 0, -1,
ax_anim 2, 0, 240, 0, 0, 0, 0,
ax_anim 2, 0, 240, 0, -1, 0, -1,
ax_anim 2, 2, 240, 0, 0, 0, 0,
ax_anim 2, 0, 240, 0, -1, 0, -1,
ax_anim 2, 0, 240, 0, 0, 0, 0,
ax_anim 2, 0, 240, 0, -1, 0, -1,
ax_anim 2, 1, 240, 0, 0, 0, 0,
ax_anim_terminator
sCastformRainyAnims_12_4:
ax_anim 2, 0, 239, -1, -1, -1, -1,
ax_anim 2, 0, 239, 0, 0, 0, 0,
ax_anim 2, 0, 239, -1, -1, -1, -1,
ax_anim 2, 0, 239, 0, 0, 0, 0,
ax_anim 2, 0, 239, -1, -1, -1, -1,
ax_anim 2, 2, 239, 0, 0, 0, 0,
ax_anim 2, 0, 239, -1, -1, -1, -1,
ax_anim 2, 0, 239, 0, 0, 0, 0,
ax_anim 2, 0, 239, -1, -1, -1, -1,
ax_anim 2, 1, 239, 0, 0, 0, 0,
ax_anim_terminator
sCastformRainyAnims_12_5:
ax_anim 2, 0, 238, 1, 0, 1, 0,
ax_anim 2, 0, 238, 0, 0, 0, 0,
ax_anim 2, 0, 238, 1, 0, 1, 0,
ax_anim 2, 0, 238, 0, 0, 0, 0,
ax_anim 2, 0, 238, 1, 0, 1, 0,
ax_anim 2, 2, 238, 0, 0, 0, 0,
ax_anim 2, 0, 238, 1, 0, 1, 0,
ax_anim 2, 0, 238, 0, 0, 0, 0,
ax_anim 2, 0, 238, 1, 0, 1, 0,
ax_anim 2, 1, 238, 0, 0, 0, 0,
ax_anim_terminator
sCastformRainyAnims_12_6:
ax_anim 2, 0, 237, 1, -1, 1, -1,
ax_anim 2, 0, 237, 0, 0, 0, 0,
ax_anim 2, 0, 237, 1, -1, 1, -1,
ax_anim 2, 0, 237, 0, 0, 0, 0,
ax_anim 2, 0, 237, 1, -1, 1, -1,
ax_anim 2, 2, 237, 0, 0, 0, 0,
ax_anim 2, 0, 237, 1, -1, 1, -1,
ax_anim 2, 0, 237, 0, 0, 0, 0,
ax_anim 2, 0, 237, 1, -1, 1, -1,
ax_anim 2, 1, 237, 0, 0, 0, 0,
ax_anim_terminator
sCastformRainyAnims_12_7:
ax_anim 2, 0, 236, 0, -1, 0, -1,
ax_anim 2, 0, 236, 0, 0, 0, 0,
ax_anim 2, 0, 236, 0, -1, 0, -1,
ax_anim 2, 0, 236, 0, 0, 0, 0,
ax_anim 2, 0, 236, 0, -1, 0, -1,
ax_anim 2, 2, 236, 0, 0, 0, 0,
ax_anim 2, 0, 236, 0, -1, 0, -1,
ax_anim 2, 0, 236, 0, 0, 0, 0,
ax_anim 2, 0, 236, 0, -1, 0, -1,
ax_anim 2, 1, 236, 0, 0, 0, 0,
ax_anim_terminator
sCastformRainyAnims_12_8:
ax_anim 2, 0, 235, -1, -1, -1, -1,
ax_anim 2, 0, 235, 0, 0, 0, 0,
ax_anim 2, 0, 235, -1, -1, -1, -1,
ax_anim 2, 0, 235, 0, 0, 0, 0,
ax_anim 2, 0, 235, -1, -1, -1, -1,
ax_anim 2, 2, 235, 0, 0, 0, 0,
ax_anim 2, 0, 235, -1, -1, -1, -1,
ax_anim 2, 0, 235, 0, 0, 0, 0,
ax_anim 2, 0, 235, -1, -1, -1, -1,
ax_anim 2, 1, 235, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sCastformRainyAnims_13_1:
ax_anim 2, 0, 242, 0, 0, 0, 0,
ax_anim 2, 0, 243, 0, 0, 0, 0,
ax_anim 2, 0, 244, 0, 0, 0, 0,
ax_anim 2, 0, 245, 0, 0, 0, 0,
ax_anim 2, 0, 246, 0, 0, 0, 0,
ax_anim 2, 0, 247, 0, 0, 0, 0,
ax_anim 2, 0, 248, 0, 0, 0, 0,
ax_anim 2, 0, 249, 0, 0, 0, 0,
ax_anim 2, 2, 242, 0, 0, 0, 0,
ax_anim_terminator
sCastformRainyAnims_13_2:
ax_anim 2, 0, 249, 0, 0, 0, 0,
ax_anim 2, 0, 242, 0, 0, 0, 0,
ax_anim 2, 0, 243, 0, 0, 0, 0,
ax_anim 2, 0, 244, 0, 0, 0, 0,
ax_anim 2, 0, 245, 0, 0, 0, 0,
ax_anim 2, 0, 246, 0, 0, 0, 0,
ax_anim 2, 0, 247, 0, 0, 0, 0,
ax_anim 2, 0, 248, 0, 0, 0, 0,
ax_anim 2, 2, 249, 0, 0, 0, 0,
ax_anim_terminator
sCastformRainyAnims_13_3:
ax_anim 2, 0, 248, 0, 0, 0, 0,
ax_anim 2, 0, 249, 0, 0, 0, 0,
ax_anim 2, 0, 242, 0, 0, 0, 0,
ax_anim 2, 0, 243, 0, 0, 0, 0,
ax_anim 2, 0, 244, 0, 0, 0, 0,
ax_anim 2, 0, 245, 0, 0, 0, 0,
ax_anim 2, 0, 246, 0, 0, 0, 0,
ax_anim 2, 0, 247, 0, 0, 0, 0,
ax_anim 2, 2, 248, 0, 0, 0, 0,
ax_anim_terminator
sCastformRainyAnims_13_4:
ax_anim 2, 0, 247, 0, 0, 0, 0,
ax_anim 2, 0, 248, 0, 0, 0, 0,
ax_anim 2, 0, 249, 0, 0, 0, 0,
ax_anim 2, 0, 242, 0, 0, 0, 0,
ax_anim 2, 0, 243, 0, 0, 0, 0,
ax_anim 2, 0, 244, 0, 0, 0, 0,
ax_anim 2, 0, 245, 0, 0, 0, 0,
ax_anim 2, 0, 246, 0, 0, 0, 0,
ax_anim 2, 2, 247, 0, 0, 0, 0,
ax_anim_terminator
sCastformRainyAnims_13_5:
ax_anim 2, 0, 246, 0, 0, 0, 0,
ax_anim 2, 0, 247, 0, 0, 0, 0,
ax_anim 2, 0, 248, 0, 0, 0, 0,
ax_anim 2, 0, 249, 0, 0, 0, 0,
ax_anim 2, 0, 242, 0, 0, 0, 0,
ax_anim 2, 0, 243, 0, 0, 0, 0,
ax_anim 2, 0, 244, 0, 0, 0, 0,
ax_anim 2, 0, 245, 0, 0, 0, 0,
ax_anim 2, 2, 246, 0, 0, 0, 0,
ax_anim_terminator
sCastformRainyAnims_13_6:
ax_anim 2, 0, 245, 0, 0, 0, 0,
ax_anim 2, 0, 246, 0, 0, 0, 0,
ax_anim 2, 0, 247, 0, 0, 0, 0,
ax_anim 2, 0, 248, 0, 0, 0, 0,
ax_anim 2, 0, 249, 0, 0, 0, 0,
ax_anim 2, 0, 242, 0, 0, 0, 0,
ax_anim 2, 0, 243, 0, 0, 0, 0,
ax_anim 2, 0, 244, 0, 0, 0, 0,
ax_anim 2, 2, 245, 0, 0, 0, 0,
ax_anim_terminator
sCastformRainyAnims_13_7:
ax_anim 2, 0, 244, 0, 0, 0, 0,
ax_anim 2, 0, 245, 0, 0, 0, 0,
ax_anim 2, 0, 246, 0, 0, 0, 0,
ax_anim 2, 0, 247, 0, 0, 0, 0,
ax_anim 2, 0, 248, 0, 0, 0, 0,
ax_anim 2, 0, 249, 0, 0, 0, 0,
ax_anim 2, 0, 242, 0, 0, 0, 0,
ax_anim 2, 0, 243, 0, 0, 0, 0,
ax_anim 2, 2, 244, 0, 0, 0, 0,
ax_anim_terminator
sCastformRainyAnims_13_8:
ax_anim 2, 0, 243, 0, 0, 0, 0,
ax_anim 2, 0, 244, 0, 0, 0, 0,
ax_anim 2, 0, 245, 0, 0, 0, 0,
ax_anim 2, 0, 246, 0, 0, 0, 0,
ax_anim 2, 0, 247, 0, 0, 0, 0,
ax_anim 2, 0, 248, 0, 0, 0, 0,
ax_anim 2, 0, 249, 0, 0, 0, 0,
ax_anim 2, 0, 242, 0, 0, 0, 0,
ax_anim 2, 2, 243, 0, 0, 0, 0,
ax_anim_terminator
sCastformRainyGfx1:
.incbin "baserom.gba", 0x147E914, 0x100
sCastformRainySprites1:
ax_sprite sCastformRainyGfx1, 0x100
ax_sprite_terminator
sCastformRainyGfx2:
.incbin "baserom.gba", 0x147EA24, 0x100
sCastformRainySprites2:
ax_sprite sCastformRainyGfx2, 0x100
ax_sprite_terminator
sCastformRainyGfx3:
.incbin "baserom.gba", 0x147EB34, 0x100
sCastformRainySprites3:
ax_sprite sCastformRainyGfx3, 0x100
ax_sprite_terminator
sCastformRainyGfx4:
.incbin "baserom.gba", 0x147EC44, 0x100
sCastformRainySprites4:
ax_sprite sCastformRainyGfx4, 0x100
ax_sprite_terminator
sCastformRainyGfx5:
.incbin "baserom.gba", 0x147ED54, 0x100
sCastformRainySprites5:
ax_sprite sCastformRainyGfx5, 0x100
ax_sprite_terminator
sCastformRainyGfx6:
.incbin "baserom.gba", 0x147EE64, 0x100
sCastformRainySprites6:
ax_sprite sCastformRainyGfx6, 0x100
ax_sprite_terminator
sCastformRainyGfx7:
.incbin "baserom.gba", 0x147EF74, 0x100
sCastformRainySprites7:
ax_sprite sCastformRainyGfx7, 0x100
ax_sprite_terminator
sCastformRainyGfx8:
.incbin "baserom.gba", 0x147F084, 0x100
sCastformRainySprites8:
ax_sprite sCastformRainyGfx8, 0x100
ax_sprite_terminator
sCastformRainyGfx9:
.incbin "baserom.gba", 0x147F194, 0x100
sCastformRainySprites9:
ax_sprite sCastformRainyGfx9, 0x100
ax_sprite_terminator
sCastformRainyGfx10:
.incbin "baserom.gba", 0x147F2A4, 0x100
sCastformRainySprites10:
ax_sprite sCastformRainyGfx10, 0x100
ax_sprite_terminator
sCastformRainyGfx11:
.incbin "baserom.gba", 0x147F3B4, 0x100
sCastformRainySprites11:
ax_sprite sCastformRainyGfx11, 0x100
ax_sprite_terminator
sCastformRainyGfx12:
.incbin "baserom.gba", 0x147F4C4, 0x100
sCastformRainySprites12:
ax_sprite sCastformRainyGfx12, 0x100
ax_sprite_terminator
sCastformRainyGfx13:
.incbin "baserom.gba", 0x147F5D4, 0x100
sCastformRainySprites13:
ax_sprite sCastformRainyGfx13, 0x100
ax_sprite_terminator
sCastformRainyGfx14:
.incbin "baserom.gba", 0x147F6E4, 0x100
sCastformRainySprites14:
ax_sprite sCastformRainyGfx14, 0x100
ax_sprite_terminator
sCastformRainyGfx15:
.incbin "baserom.gba", 0x147F7F4, 0x100
sCastformRainySprites15:
ax_sprite sCastformRainyGfx15, 0x100
ax_sprite_terminator
sCastformRainyGfx16:
.incbin "baserom.gba", 0x147F904, 0xC0
sCastformRainySprites16:
ax_sprite sCastformRainyGfx16, 0xc0
ax_sprite 0, 0x40
ax_sprite_terminator
sCastformRainyGfx17:
.incbin "baserom.gba", 0x147F9DC, 0x100
sCastformRainySprites17:
ax_sprite sCastformRainyGfx17, 0x100
ax_sprite_terminator
sCastformRainyGfx18:
.incbin "baserom.gba", 0x147FAEC, 0xC0
sCastformRainySprites18:
ax_sprite sCastformRainyGfx18, 0xc0
ax_sprite 0, 0x40
ax_sprite_terminator
sCastformRainyGfx19:
.incbin "baserom.gba", 0x147FBC4, 0x100
sCastformRainySprites19:
ax_sprite sCastformRainyGfx19, 0x100
ax_sprite_terminator
sCastformRainyGfx20:
.incbin "baserom.gba", 0x147FCD4, 0x60
sCastformRainyGfx20_1:
.incbin "baserom.gba", 0x147FD34, 0x60
sCastformRainyGfx20_2:
.incbin "baserom.gba", 0x147FD94, 0x60
sCastformRainyGfx20_3:
.incbin "baserom.gba", 0x147FDF4, 0x20
sCastformRainySprites20:
ax_sprite sCastformRainyGfx20, 0x60
ax_sprite 0, 0x20
ax_sprite sCastformRainyGfx20_1, 0x60
ax_sprite 0, 0x20
ax_sprite sCastformRainyGfx20_2, 0x60
ax_sprite 0, 0x40
ax_sprite sCastformRainyGfx20_3, 0x20
ax_sprite 0, 0x40
ax_sprite_terminator
sCastformRainyGfx21:
.incbin "baserom.gba", 0x147FE5C, 0x100
sCastformRainySprites21:
ax_sprite sCastformRainyGfx21, 0x100
ax_sprite_terminator
sCastformRainyGfx22:
.incbin "baserom.gba", 0x147FF6C, 0x100
sCastformRainySprites22:
ax_sprite sCastformRainyGfx22, 0x100
ax_sprite_terminator
sCastformRainyGfx23:
.incbin "baserom.gba", 0x148007C, 0x100
sCastformRainySprites23:
ax_sprite sCastformRainyGfx23, 0x100
ax_sprite_terminator
sCastformRainyGfx24:
.incbin "baserom.gba", 0x148018C, 0x100
sCastformRainySprites24:
ax_sprite sCastformRainyGfx24, 0x100
ax_sprite_terminator
sCastformRainyGfx25:
.incbin "baserom.gba", 0x148029C, 0xC0
sCastformRainySprites25:
ax_sprite sCastformRainyGfx25, 0xc0
ax_sprite 0, 0x40
ax_sprite_terminator
sCastformRainyGfx26:
.incbin "baserom.gba", 0x1480374, 0x200
sCastformRainySprites26:
ax_sprite sCastformRainyGfx26, 0x200
ax_sprite_terminator
sCastformRainyGfx27:
.incbin "baserom.gba", 0x1480584, 0x200
sCastformRainySprites27:
ax_sprite sCastformRainyGfx27, 0x200
ax_sprite_terminator
sCastformRainyGfx28:
.incbin "baserom.gba", 0x1480794, 0x200
sCastformRainySprites28:
ax_sprite sCastformRainyGfx28, 0x200
ax_sprite_terminator
sCastformRainyGfx29:
.incbin "baserom.gba", 0x14809A4, 0x200
sCastformRainySprites29:
ax_sprite sCastformRainyGfx29, 0x200
ax_sprite_terminator
sCastformRainyGfx30:
.incbin "baserom.gba", 0x1480BB4, 0x200
sCastformRainySprites30:
ax_sprite sCastformRainyGfx30, 0x200
ax_sprite_terminator
sCastformRainyGfx31:
.incbin "baserom.gba", 0x1480DC4, 0x200
sCastformRainySprites31:
ax_sprite sCastformRainyGfx31, 0x200
ax_sprite_terminator
sCastformRainyGfx32:
.incbin "baserom.gba", 0x1480FD4, 0x200
sCastformRainySprites32:
ax_sprite sCastformRainyGfx32, 0x200
ax_sprite_terminator
sAxPosesCastformRainy:
.4byte sCastformRainyPose1
.4byte sCastformRainyPose2
.4byte sCastformRainyPose3
.4byte sCastformRainyPose4
.4byte sCastformRainyPose5
.4byte sCastformRainyPose6
.4byte sCastformRainyPose7
.4byte sCastformRainyPose8
.4byte sCastformRainyPose9
.4byte sCastformRainyPose10
.4byte sCastformRainyPose11
.4byte sCastformRainyPose12
.4byte sCastformRainyPose13
.4byte sCastformRainyPose14
.4byte sCastformRainyPose15
.4byte sCastformRainyPose16
.4byte sCastformRainyPose17
.4byte sCastformRainyPose18
.4byte sCastformRainyPose19
.4byte sCastformRainyPose20
.4byte sCastformRainyPose21
.4byte sCastformRainyPose22
.4byte sCastformRainyPose23
.4byte sCastformRainyPose24
.4byte sCastformRainyPose25
.4byte sCastformRainyPose26
.4byte sCastformRainyPose27
.4byte sCastformRainyPose28
.4byte sCastformRainyPose29
.4byte sCastformRainyPose30
.4byte sCastformRainyPose31
.4byte sCastformRainyPose32
.4byte sCastformRainyPose33
.4byte sCastformRainyPose34
.4byte sCastformRainyPose35
.4byte sCastformRainyPose36
.4byte sCastformRainyPose37
.4byte sCastformRainyPose38
.4byte sCastformRainyPose39
.4byte sCastformRainyPose40
.4byte sCastformRainyPose41
.4byte sCastformRainyPose42
.4byte sCastformRainyPose43
.4byte sCastformRainyPose44
.4byte sCastformRainyPose45
.4byte sCastformRainyPose46
.4byte sCastformRainyPose47
.4byte sCastformRainyPose48
.4byte sCastformRainyPose49
.4byte sCastformRainyPose50
.4byte sCastformRainyPose51
.4byte sCastformRainyPose52
.4byte sCastformRainyPose53
.4byte sCastformRainyPose54
.4byte sCastformRainyPose55
.4byte sCastformRainyPose56
.4byte sCastformRainyPose57
.4byte sCastformRainyPose58
.4byte sCastformRainyPose59
.4byte sCastformRainyPose60
.4byte sCastformRainyPose61
.4byte sCastformRainyPose62
.4byte sCastformRainyPose63
.4byte sCastformRainyPose64
.4byte sCastformRainyPose65
.4byte sCastformRainyPose66
.4byte sCastformRainyPose67
.4byte sCastformRainyPose68
.4byte sCastformRainyPose69
.4byte sCastformRainyPose70
.4byte sCastformRainyPose71
.4byte sCastformRainyPose72
.4byte sCastformRainyPose73
.4byte sCastformRainyPose74
.4byte sCastformRainyPose75
.4byte sCastformRainyPose76
.4byte sCastformRainyPose77
.4byte sCastformRainyPose78
.4byte sCastformRainyPose79
.4byte sCastformRainyPose80
.4byte sCastformRainyPose81
.4byte sCastformRainyPose82
.4byte sCastformRainyPose83
.4byte sCastformRainyPose84
.4byte sCastformRainyPose85
.4byte sCastformRainyPose86
.4byte sCastformRainyPose87
.4byte sCastformRainyPose88
.4byte sCastformRainyPose89
.4byte sCastformRainyPose90
.4byte sCastformRainyPose91
.4byte sCastformRainyPose92
.4byte sCastformRainyPose93
.4byte sCastformRainyPose94
.4byte sCastformRainyPose95
.4byte sCastformRainyPose96
.4byte sCastformRainyPose97
.4byte sCastformRainyPose98
.4byte sCastformRainyPose99
.4byte sCastformRainyPose100
.4byte sCastformRainyPose101
.4byte sCastformRainyPose102
.4byte sCastformRainyPose103
.4byte sCastformRainyPose104
.4byte sCastformRainyPose105
.4byte sCastformRainyPose106
.4byte sCastformRainyPose107
.4byte sCastformRainyPose108
.4byte sCastformRainyPose109
.4byte sCastformRainyPose110
.4byte sCastformRainyPose111
.4byte sCastformRainyPose112
.4byte sCastformRainyPose113
.4byte sCastformRainyPose114
.4byte sCastformRainyPose115
.4byte sCastformRainyPose116
.4byte sCastformRainyPose117
.4byte sCastformRainyPose118
.4byte sCastformRainyPose119
.4byte sCastformRainyPose120
.4byte sCastformRainyPose121
.4byte sCastformRainyPose122
.4byte sCastformRainyPose123
.4byte sCastformRainyPose124
.4byte sCastformRainyPose125
.4byte sCastformRainyPose126
.4byte sCastformRainyPose127
.4byte sCastformRainyPose128
.4byte sCastformRainyPose129
.4byte sCastformRainyPose130
.4byte sCastformRainyPose131
.4byte sCastformRainyPose132
.4byte sCastformRainyPose133
.4byte sCastformRainyPose134
.4byte sCastformRainyPose135
.4byte sCastformRainyPose136
.4byte sCastformRainyPose137
.4byte sCastformRainyPose138
.4byte sCastformRainyPose139
.4byte sCastformRainyPose140
.4byte sCastformRainyPose141
.4byte sCastformRainyPose142
.4byte sCastformRainyPose143
.4byte sCastformRainyPose144
.4byte sCastformRainyPose145
.4byte sCastformRainyPose146
.4byte sCastformRainyPose147
.4byte sCastformRainyPose148
.4byte sCastformRainyPose149
.4byte sCastformRainyPose150
.4byte sCastformRainyPose151
.4byte sCastformRainyPose152
.4byte sCastformRainyPose153
.4byte sCastformRainyPose154
.4byte sCastformRainyPose155
.4byte sCastformRainyPose156
.4byte sCastformRainyPose157
.4byte sCastformRainyPose158
.4byte sCastformRainyPose159
.4byte sCastformRainyPose160
.4byte sCastformRainyPose161
.4byte sCastformRainyPose162
.4byte sCastformRainyPose163
.4byte sCastformRainyPose164
.4byte sCastformRainyPose165
.4byte sCastformRainyPose166
.4byte sCastformRainyPose167
.4byte sCastformRainyPose168
.4byte sCastformRainyPose169
.4byte sCastformRainyPose170
.4byte sCastformRainyPose171
.4byte sCastformRainyPose172
.4byte sCastformRainyPose173
.4byte sCastformRainyPose174
.4byte sCastformRainyPose175
.4byte sCastformRainyPose176
.4byte sCastformRainyPose177
.4byte sCastformRainyPose178
.4byte sCastformRainyPose179
.4byte sCastformRainyPose180
.4byte sCastformRainyPose181
.4byte sCastformRainyPose182
.4byte sCastformRainyPose183
.4byte sCastformRainyPose184
.4byte sCastformRainyPose185
.4byte sCastformRainyPose186
.4byte sCastformRainyPose187
.4byte sCastformRainyPose188
.4byte sCastformRainyPose189
.4byte sCastformRainyPose190
.4byte sCastformRainyPose191
.4byte sCastformRainyPose192
.4byte sCastformRainyPose193
.4byte sCastformRainyPose194
.4byte sCastformRainyPose195
.4byte sCastformRainyPose196
.4byte sCastformRainyPose197
.4byte sCastformRainyPose198
.4byte sCastformRainyPose199
.4byte sCastformRainyPose200
.4byte sCastformRainyPose201
.4byte sCastformRainyPose202
.4byte sCastformRainyPose203
.4byte sCastformRainyPose204
.4byte sCastformRainyPose205
.4byte sCastformRainyPose206
.4byte sCastformRainyPose207
.4byte sCastformRainyPose208
.4byte sCastformRainyPose209
.4byte sCastformRainyPose210
.4byte sCastformRainyPose211
.4byte sCastformRainyPose212
.4byte sCastformRainyPose213
.4byte sCastformRainyPose214
.4byte sCastformRainyPose215
.4byte sCastformRainyPose216
.4byte sCastformRainyPose217
.4byte sCastformRainyPose218
.4byte sCastformRainyPose219
.4byte sCastformRainyPose220
.4byte sCastformRainyPose221
.4byte sCastformRainyPose222
.4byte sCastformRainyPose223
.4byte sCastformRainyPose224
.4byte sCastformRainyPose225
.4byte sCastformRainyPose226
.4byte sCastformRainyPose227
.4byte sCastformRainyPose228
.4byte sCastformRainyPose229
.4byte sCastformRainyPose230
.4byte sCastformRainyPose231
.4byte sCastformRainyPose232
.4byte sCastformRainyPose233
.4byte sCastformRainyPose234
.4byte sCastformRainyPose235
.4byte sCastformRainyPose236
.4byte sCastformRainyPose237
.4byte sCastformRainyPose238
.4byte sCastformRainyPose239
.4byte sCastformRainyPose240
.4byte sCastformRainyPose241
.4byte sCastformRainyPose242
.4byte sCastformRainyPose243
.4byte sCastformRainyPose244
.4byte sCastformRainyPose245
.4byte sCastformRainyPose246
.4byte sCastformRainyPose247
.4byte sCastformRainyPose248
.4byte sCastformRainyPose249
.4byte sCastformRainyPose250
sAxPositionsCastformRainy:
.2byte   -1,   -7, 	  -5,   -4, 	   3,   -4, 	  -1,  -10
.2byte   -1,   -7, 	  -5,   -4, 	   3,   -4, 	  -1,  -10
.2byte   -1,   -7, 	  -5,   -4, 	   3,   -4, 	  -1,  -10
.2byte    0,   -7, 	   3,   -4, 	  -3,   -3, 	  -1,  -10
.2byte    0,   -7, 	   3,   -4, 	  -3,   -3, 	  -1,  -10
.2byte    0,   -7, 	   3,   -4, 	  -3,   -3, 	  -1,  -10
.2byte    2,   -7, 	   1,   -5, 	   1,   -3, 	  -2,  -11
.2byte    2,   -7, 	   1,   -5, 	   1,   -3, 	  -2,  -11
.2byte    2,   -7, 	   1,   -5, 	   1,   -3, 	  -2,  -11
.2byte    0,   -8, 	  -1,   -5, 	   2,   -3, 	  -1,  -10
.2byte    0,   -8, 	  -1,   -6, 	   2,   -3, 	  -2,  -10
.2byte    1,   -8, 	  -1,   -6, 	   2,   -3, 	  -2,  -10
.2byte   -1,  -11, 	   4,   -5, 	  -6,   -5, 	  -1,  -10
.2byte   -1,  -11, 	   4,   -5, 	  -6,   -5, 	  -1,  -10
.2byte   -1,  -11, 	   4,   -5, 	  -6,   -5, 	  -1,  -10
.2byte   -2,   -8, 	  -1,   -5, 	  -4,   -3, 	  -1,  -10
.2byte   -2,   -8, 	  -1,   -6, 	  -4,   -3, 	   0,  -10
.2byte   -3,   -8, 	  -1,   -6, 	  -4,   -3, 	   0,  -10
.2byte   -4,   -7, 	  -3,   -5, 	  -3,   -3, 	   0,  -11
.2byte   -4,   -7, 	  -3,   -5, 	  -3,   -3, 	   0,  -11
.2byte   -4,   -7, 	  -3,   -5, 	  -3,   -3, 	   0,  -11
.2byte   -2,   -7, 	  -5,   -4, 	   1,   -3, 	  -1,  -10
.2byte   -2,   -7, 	  -5,   -4, 	   1,   -3, 	  -1,  -10
.2byte   -2,   -7, 	  -5,   -4, 	   1,   -3, 	  -1,  -10
.2byte   -1,   -7, 	  -5,   -4, 	   3,   -4, 	  -1,  -10
.2byte   -1,  -11, 	  -5,   -6, 	   3,   -6, 	  -1,  -13
.2byte   -1,   -4, 	  -5,   -3, 	   3,   -3, 	  -1,   -8
.2byte    0,   -7, 	   3,   -4, 	  -3,   -3, 	  -1,  -10
.2byte    0,  -11, 	   3,   -7, 	  -2,   -5, 	  -2,  -13
.2byte    1,   -4, 	   3,   -2, 	  -3,   -1, 	   0,   -8
.2byte    2,   -7, 	   1,   -5, 	   1,   -3, 	  -2,  -11
.2byte    1,  -10, 	   1,   -6, 	   2,   -4, 	  -3,  -10
.2byte    4,   -5, 	   1,   -3, 	   1,   -1, 	   0,   -8
.2byte    0,   -8, 	  -1,   -5, 	   2,   -3, 	  -1,  -10
.2byte    0,  -10, 	  -1,   -5, 	   3,   -3, 	  -2,   -8
.2byte    3,   -6, 	   0,   -4, 	   3,   -2, 	   0,   -8
.2byte   -1,  -11, 	   4,   -5, 	  -6,   -5, 	  -1,  -10
.2byte   -1,  -11, 	   4,   -4, 	  -6,   -4, 	  -1,   -8
.2byte   -1,  -12, 	   3,   -6, 	  -4,   -6, 	  -1,  -13
.2byte   -2,   -8, 	  -1,   -5, 	  -4,   -3, 	  -1,  -10
.2byte   -2,  -10, 	  -1,   -5, 	  -5,   -3, 	   0,   -8
.2byte   -5,   -6, 	  -2,   -4, 	  -5,   -2, 	  -2,   -8
.2byte   -4,   -7, 	  -3,   -5, 	  -3,   -3, 	   0,  -11
.2byte   -3,  -10, 	  -3,   -6, 	  -4,   -4, 	   1,  -10
.2byte   -6,   -5, 	  -3,   -3, 	  -3,   -1, 	  -2,   -8
.2byte   -2,   -7, 	  -5,   -4, 	   1,   -3, 	  -1,  -10
.2byte   -2,  -11, 	  -5,   -7, 	   0,   -5, 	   0,  -13
.2byte   -3,   -4, 	  -5,   -2, 	   1,   -1, 	  -2,   -8
.2byte   -1,   -7, 	  -5,   -4, 	   3,   -4, 	  -1,  -10
.2byte   -1,  -11, 	  -5,   -6, 	   3,   -6, 	  -1,  -13
.2byte   -1,   -4, 	  -5,   -3, 	   3,   -3, 	  -1,   -8
.2byte    0,   -7, 	   3,   -4, 	  -3,   -3, 	  -1,  -10
.2byte    0,  -11, 	   3,   -7, 	  -2,   -5, 	  -2,  -13
.2byte    1,   -4, 	   3,   -2, 	  -3,   -1, 	   0,   -8
.2byte    2,   -7, 	   1,   -5, 	   1,   -3, 	  -2,  -11
.2byte    1,  -10, 	   1,   -6, 	   2,   -4, 	  -3,  -10
.2byte    4,   -5, 	   1,   -3, 	   1,   -1, 	   0,   -8
.2byte    0,   -8, 	  -1,   -5, 	   2,   -3, 	  -1,  -10
.2byte    0,  -10, 	  -1,   -5, 	   3,   -3, 	  -2,   -8
.2byte    3,   -6, 	   0,   -4, 	   3,   -2, 	   0,   -8
.2byte   -1,  -11, 	   4,   -5, 	  -6,   -5, 	  -1,  -10
.2byte   -1,  -11, 	   4,   -4, 	  -6,   -4, 	  -1,   -8
.2byte   -1,  -12, 	   3,   -6, 	  -4,   -6, 	  -1,  -13
.2byte   -2,   -8, 	  -1,   -5, 	  -4,   -3, 	  -1,  -10
.2byte   -2,  -10, 	  -1,   -5, 	  -5,   -3, 	   0,   -8
.2byte   -5,   -6, 	  -2,   -4, 	  -5,   -2, 	  -2,   -8
.2byte   -4,   -7, 	  -3,   -5, 	  -3,   -3, 	   0,  -11
.2byte   -3,  -10, 	  -3,   -6, 	  -4,   -4, 	   1,  -10
.2byte   -6,   -5, 	  -3,   -3, 	  -3,   -1, 	  -2,   -8
.2byte   -2,   -7, 	  -5,   -4, 	   1,   -3, 	  -1,  -10
.2byte   -2,  -11, 	  -5,   -7, 	   0,   -5, 	   0,  -13
.2byte   -3,   -4, 	  -5,   -2, 	   1,   -1, 	  -2,   -8
.2byte   -1,   -7, 	  -5,   -4, 	   3,   -4, 	  -1,  -10
.2byte   -1,  -11, 	  -5,   -6, 	   3,   -6, 	  -1,  -13
.2byte   -1,   -4, 	  -5,   -3, 	   3,   -3, 	  -1,   -8
.2byte    0,   -7, 	   3,   -4, 	  -3,   -3, 	  -1,  -10
.2byte    0,  -11, 	   3,   -7, 	  -2,   -5, 	  -2,  -13
.2byte    1,   -3, 	   3,   -1, 	  -3,    0, 	   0,   -7
.2byte    2,   -7, 	   1,   -5, 	   1,   -3, 	  -2,  -11
.2byte    1,  -10, 	   1,   -6, 	   2,   -4, 	  -3,  -10
.2byte    5,   -5, 	   2,   -3, 	   2,   -1, 	   1,   -8
.2byte    0,   -8, 	  -1,   -5, 	   2,   -3, 	  -1,  -10
.2byte    0,  -10, 	  -1,   -5, 	   3,   -3, 	  -2,   -8
.2byte    3,   -7, 	   0,   -5, 	   3,   -3, 	   0,   -9
.2byte   -1,  -11, 	   4,   -5, 	  -6,   -5, 	  -1,  -10
.2byte   -1,  -11, 	   4,   -4, 	  -6,   -4, 	  -1,   -8
.2byte   -1,  -12, 	   3,   -6, 	  -4,   -6, 	  -1,  -13
.2byte   -2,   -8, 	  -1,   -5, 	  -4,   -3, 	  -1,  -10
.2byte   -2,  -10, 	  -1,   -5, 	  -5,   -3, 	   0,   -8
.2byte   -5,   -7, 	  -2,   -5, 	  -5,   -3, 	  -2,   -9
.2byte   -4,   -7, 	  -3,   -5, 	  -3,   -3, 	   0,  -11
.2byte   -3,  -10, 	  -3,   -6, 	  -4,   -4, 	   1,  -10
.2byte   -7,   -5, 	  -4,   -3, 	  -4,   -1, 	  -3,   -8
.2byte   -2,   -7, 	  -5,   -4, 	   1,   -3, 	  -1,  -10
.2byte   -2,  -11, 	  -5,   -7, 	   0,   -5, 	   0,  -13
.2byte   -3,   -3, 	  -5,   -1, 	   1,    0, 	  -2,   -7
.2byte   -1,   -7, 	  -5,   -4, 	   3,   -4, 	  -1,  -10
.2byte   -2,   -7, 	  -5,   -4, 	   1,   -3, 	  -1,  -10
.2byte   -4,   -7, 	  -3,   -5, 	  -3,   -3, 	   0,  -11
.2byte   -2,   -8, 	  -1,   -5, 	  -4,   -3, 	  -1,  -10
.2byte   -1,  -11, 	   4,   -5, 	  -6,   -5, 	  -1,  -10
.2byte    0,   -8, 	  -1,   -5, 	   2,   -3, 	  -1,  -10
.2byte    2,   -7, 	   1,   -5, 	   1,   -3, 	  -2,  -11
.2byte    0,   -7, 	   3,   -4, 	  -3,   -3, 	  -1,  -10
.2byte    0,   -7, 	   3,   -4, 	  -3,   -3, 	  -1,  -10
.2byte   -1,   -7, 	  -5,   -4, 	   3,   -4, 	  -1,  -10
.2byte   -2,   -7, 	  -5,   -4, 	   1,   -3, 	  -1,  -10
.2byte   -4,   -7, 	  -3,   -5, 	  -3,   -3, 	   0,  -11
.2byte   -2,   -8, 	  -1,   -5, 	  -4,   -3, 	  -1,  -10
.2byte   -1,  -11, 	   4,   -5, 	  -6,   -5, 	  -1,  -10
.2byte    0,   -8, 	  -1,   -5, 	   2,   -3, 	  -1,  -10
.2byte    2,   -7, 	   1,   -5, 	   1,   -3, 	  -2,  -11
.2byte    2,   -7, 	   1,   -5, 	   1,   -3, 	  -2,  -11
.2byte    0,   -7, 	   3,   -4, 	  -3,   -3, 	  -1,  -10
.2byte   -1,   -7, 	  -5,   -4, 	   3,   -4, 	  -1,  -10
.2byte   -2,   -7, 	  -5,   -4, 	   1,   -3, 	  -1,  -10
.2byte   -4,   -7, 	  -3,   -5, 	  -3,   -3, 	   0,  -11
.2byte   -2,   -8, 	  -1,   -5, 	  -4,   -3, 	  -1,  -10
.2byte   -1,  -11, 	   4,   -5, 	  -6,   -5, 	  -1,  -10
.2byte    0,   -8, 	  -1,   -5, 	   2,   -3, 	  -1,  -10
.2byte    0,   -8, 	  -1,   -5, 	   2,   -3, 	  -1,  -10
.2byte    2,   -7, 	   1,   -5, 	   1,   -3, 	  -2,  -11
.2byte    0,   -7, 	   3,   -4, 	  -3,   -3, 	  -1,  -10
.2byte   -1,   -7, 	  -5,   -4, 	   3,   -4, 	  -1,  -10
.2byte   -2,   -7, 	  -5,   -4, 	   1,   -3, 	  -1,  -10
.2byte   -4,   -7, 	  -3,   -5, 	  -3,   -3, 	   0,  -11
.2byte   -2,   -8, 	  -1,   -5, 	  -4,   -3, 	  -1,  -10
.2byte   -1,  -11, 	   4,   -5, 	  -6,   -5, 	  -1,  -10
.2byte   -1,  -11, 	   4,   -5, 	  -6,   -5, 	  -1,  -10
.2byte    0,   -8, 	  -1,   -5, 	   2,   -3, 	  -1,  -10
.2byte    2,   -7, 	   1,   -5, 	   1,   -3, 	  -2,  -11
.2byte    0,   -7, 	   3,   -4, 	  -3,   -3, 	  -1,  -10
.2byte   -1,   -7, 	  -5,   -4, 	   3,   -4, 	  -1,  -10
.2byte   -2,   -7, 	  -5,   -4, 	   1,   -3, 	  -1,  -10
.2byte   -4,   -7, 	  -3,   -5, 	  -3,   -3, 	   0,  -11
.2byte   -2,   -8, 	  -1,   -5, 	  -4,   -3, 	  -1,  -10
.2byte   -2,   -8, 	  -1,   -5, 	  -4,   -3, 	  -1,  -10
.2byte   -1,  -11, 	   4,   -5, 	  -6,   -5, 	  -1,  -10
.2byte    0,   -8, 	  -1,   -5, 	   2,   -3, 	  -1,  -10
.2byte    2,   -7, 	   1,   -5, 	   1,   -3, 	  -2,  -11
.2byte    0,   -7, 	   3,   -4, 	  -3,   -3, 	  -1,  -10
.2byte   -1,   -7, 	  -5,   -4, 	   3,   -4, 	  -1,  -10
.2byte   -2,   -7, 	  -5,   -4, 	   1,   -3, 	  -1,  -10
.2byte   -4,   -7, 	  -3,   -5, 	  -3,   -3, 	   0,  -11
.2byte   -4,   -7, 	  -3,   -5, 	  -3,   -3, 	   0,  -11
.2byte   -2,   -8, 	  -1,   -5, 	  -4,   -3, 	  -1,  -10
.2byte   -1,  -11, 	   4,   -5, 	  -6,   -5, 	  -1,  -10
.2byte    0,   -8, 	  -1,   -5, 	   2,   -3, 	  -1,  -10
.2byte    2,   -7, 	   1,   -5, 	   1,   -3, 	  -2,  -11
.2byte    0,   -7, 	   3,   -4, 	  -3,   -3, 	  -1,  -10
.2byte   -1,   -7, 	  -5,   -4, 	   3,   -4, 	  -1,  -10
.2byte   -2,   -7, 	  -5,   -4, 	   1,   -3, 	  -1,  -10
.2byte   -2,   -7, 	  -5,   -4, 	   1,   -3, 	  -1,  -10
.2byte   -4,   -7, 	  -3,   -5, 	  -3,   -3, 	   0,  -11
.2byte   -2,   -8, 	  -1,   -5, 	  -4,   -3, 	  -1,  -10
.2byte   -1,  -11, 	   4,   -5, 	  -6,   -5, 	  -1,  -10
.2byte    0,   -8, 	  -1,   -5, 	   2,   -3, 	  -1,  -10
.2byte    2,   -7, 	   1,   -5, 	   1,   -3, 	  -2,  -11
.2byte    0,   -7, 	   3,   -4, 	  -3,   -3, 	  -1,  -10
.2byte   -1,   -7, 	  -5,   -4, 	   3,   -4, 	  -1,  -10
.2byte   -2,   -7, 	  -5,   -4, 	   1,   -3, 	  -1,  -10
.2byte   -2,   -6, 	  -5,   -4, 	   1,   -3, 	  -1,   -9
.2byte    0,   -8, 	  -4,   -5, 	   4,   -5, 	   0,  -11
.2byte   -1,   -8, 	   2,   -5, 	  -3,   -3, 	  -2,  -11
.2byte    1,   -8, 	   2,   -6, 	   3,   -4, 	  -3,  -10
.2byte    1,   -9, 	  -1,   -6, 	   3,   -4, 	  -3,  -10
.2byte    0,   -9, 	   5,   -4, 	  -5,   -4, 	   0,   -7
.2byte   -2,   -9, 	   0,   -6, 	  -4,   -4, 	   2,  -10
.2byte   -2,   -8, 	  -3,   -6, 	  -4,   -4, 	   2,  -10
.2byte    0,   -8, 	  -3,   -5, 	   2,   -3, 	   1,  -11
.2byte   -1,   -7, 	  -5,   -4, 	   3,   -4, 	  -1,  -10
.2byte   -1,   -7, 	  -5,   -4, 	   3,   -4, 	  -1,  -10
.2byte   -1,   -7, 	  -5,   -4, 	   3,   -4, 	  -1,  -10
.2byte    0,   -7, 	   3,   -4, 	  -3,   -3, 	  -1,  -10
.2byte    0,   -7, 	   3,   -4, 	  -3,   -3, 	  -1,  -10
.2byte    0,   -7, 	   3,   -4, 	  -3,   -3, 	  -1,  -10
.2byte    2,   -7, 	   1,   -5, 	   1,   -3, 	  -2,  -11
.2byte    2,   -7, 	   1,   -5, 	   1,   -3, 	  -2,  -11
.2byte    2,   -7, 	   1,   -5, 	   1,   -3, 	  -2,  -11
.2byte    0,   -8, 	  -1,   -5, 	   2,   -3, 	  -1,  -10
.2byte    0,   -8, 	  -1,   -6, 	   2,   -3, 	  -2,  -10
.2byte    1,   -8, 	  -1,   -6, 	   2,   -3, 	  -2,  -10
.2byte   -1,  -11, 	   4,   -5, 	  -6,   -5, 	  -1,  -10
.2byte   -1,  -11, 	   4,   -5, 	  -6,   -5, 	  -1,  -10
.2byte   -1,  -11, 	   4,   -5, 	  -6,   -5, 	  -1,  -10
.2byte   -2,   -8, 	  -1,   -5, 	  -4,   -3, 	  -1,  -10
.2byte   -2,   -8, 	  -1,   -6, 	  -4,   -3, 	   0,  -10
.2byte   -3,   -8, 	  -1,   -6, 	  -4,   -3, 	   0,  -10
.2byte   -4,   -7, 	  -3,   -5, 	  -3,   -3, 	   0,  -11
.2byte   -4,   -7, 	  -3,   -5, 	  -3,   -3, 	   0,  -11
.2byte   -4,   -7, 	  -3,   -5, 	  -3,   -3, 	   0,  -11
.2byte   -2,   -7, 	  -5,   -4, 	   1,   -3, 	  -1,  -10
.2byte   -2,   -7, 	  -5,   -4, 	   1,   -3, 	  -1,  -10
.2byte   -2,   -7, 	  -5,   -4, 	   1,   -3, 	  -1,  -10
.2byte   -1,   -4, 	  -5,   -3, 	   3,   -3, 	  -1,   -8
.2byte   -2,   -4, 	  -4,   -2, 	   2,   -1, 	  -1,   -8
.2byte   -5,   -5, 	  -2,   -3, 	  -2,   -1, 	  -1,   -8
.2byte   -4,   -6, 	  -1,   -4, 	  -4,   -2, 	  -1,   -8
.2byte   -1,  -10, 	   3,   -4, 	  -4,   -4, 	  -1,  -11
.2byte    3,   -6, 	   0,   -4, 	   3,   -2, 	   0,   -8
.2byte    4,   -5, 	   1,   -3, 	   1,   -1, 	   0,   -8
.2byte    1,   -4, 	   3,   -2, 	  -3,   -1, 	   0,   -8
.2byte   -1,  -10, 	  -5,   -5, 	   3,   -5, 	  -1,  -12
.2byte    1,  -10, 	   4,   -6, 	  -1,   -4, 	  -1,  -12
.2byte    3,  -10, 	   3,   -6, 	   4,   -4, 	  -1,  -10
.2byte    1,  -11, 	   0,   -6, 	   4,   -4, 	  -1,   -9
.2byte   -1,  -12, 	   4,   -5, 	  -6,   -5, 	  -1,   -9
.2byte   -2,  -11, 	  -1,   -6, 	  -5,   -4, 	   0,   -9
.2byte   -4,  -10, 	  -4,   -6, 	  -5,   -4, 	   0,  -10
.2byte   -2,   -9, 	  -5,   -5, 	   0,   -3, 	   0,  -11
.2byte   -1,   -7, 	  -5,   -4, 	   3,   -4, 	  -1,  -10
.2byte   -1,  -11, 	  -5,   -6, 	   3,   -6, 	  -1,  -13
.2byte   -1,   -4, 	  -5,   -3, 	   3,   -3, 	  -1,   -8
.2byte    0,   -7, 	   3,   -4, 	  -3,   -3, 	  -1,  -10
.2byte    0,  -11, 	   3,   -7, 	  -2,   -5, 	  -2,  -13
.2byte    1,   -3, 	   3,   -1, 	  -3,    0, 	   0,   -7
.2byte    2,   -7, 	   1,   -5, 	   1,   -3, 	  -2,  -11
.2byte    2,  -10, 	   2,   -6, 	   3,   -4, 	  -2,  -10
.2byte    4,   -5, 	   1,   -3, 	   1,   -1, 	   0,   -8
.2byte    0,   -8, 	  -1,   -5, 	   2,   -3, 	  -1,  -10
.2byte    0,  -10, 	  -1,   -5, 	   3,   -3, 	  -2,   -8
.2byte    2,   -7, 	  -1,   -5, 	   2,   -3, 	  -1,   -9
.2byte   -1,  -11, 	   4,   -5, 	  -6,   -5, 	  -1,  -10
.2byte   -1,  -11, 	   4,   -4, 	  -6,   -4, 	  -1,   -8
.2byte   -1,  -12, 	   3,   -6, 	  -4,   -6, 	  -1,  -13
.2byte   -2,   -8, 	  -1,   -5, 	  -4,   -3, 	  -1,  -10
.2byte   -2,  -10, 	  -1,   -5, 	  -5,   -3, 	   0,   -8
.2byte   -4,   -7, 	  -1,   -5, 	  -4,   -3, 	  -1,   -9
.2byte   -3,   -7, 	  -2,   -5, 	  -2,   -3, 	   1,  -11
.2byte   -3,  -10, 	  -3,   -6, 	  -4,   -4, 	   1,  -10
.2byte   -5,   -5, 	  -2,   -3, 	  -2,   -1, 	  -1,   -8
.2byte   -2,   -7, 	  -5,   -4, 	   1,   -3, 	  -1,  -10
.2byte   -2,  -11, 	  -5,   -7, 	   0,   -5, 	   0,  -13
.2byte   -3,   -3, 	  -5,   -1, 	   1,    0, 	  -2,   -7
.2byte   -1,   -5, 	  -5,   -4, 	   3,   -4, 	  -1,   -9
.2byte   -2,   -5, 	  -4,   -3, 	   2,   -2, 	  -1,   -9
.2byte   -4,   -6, 	  -1,   -4, 	  -1,   -2, 	   0,   -9
.2byte   -3,   -8, 	   0,   -6, 	  -3,   -4, 	   0,  -10
.2byte   -1,  -12, 	   3,   -6, 	  -4,   -6, 	  -1,  -13
.2byte    2,   -8, 	  -1,   -6, 	   2,   -4, 	  -1,  -10
.2byte    3,   -6, 	   0,   -4, 	   0,   -2, 	  -1,   -9
.2byte    1,   -5, 	   3,   -3, 	  -3,   -2, 	   0,   -9
.2byte   -1,   -7, 	  -5,   -4, 	   3,   -4, 	  -1,  -10
.2byte   -2,   -7, 	  -5,   -4, 	   1,   -3, 	  -1,  -10
.2byte   -4,   -7, 	  -3,   -5, 	  -3,   -3, 	   0,  -11
.2byte   -2,   -8, 	  -1,   -5, 	  -4,   -3, 	  -1,  -10
.2byte   -1,  -11, 	   4,   -5, 	  -6,   -5, 	  -1,  -10
.2byte    0,   -8, 	  -1,   -5, 	   2,   -3, 	  -1,  -10
.2byte    2,   -7, 	   1,   -5, 	   1,   -3, 	  -2,  -11
.2byte    0,   -7, 	   3,   -4, 	  -3,   -3, 	  -1,  -10
sCastformRainyAnimTable1:
.4byte sCastformRainyAnims_1_1
.4byte sCastformRainyAnims_1_2
.4byte sCastformRainyAnims_1_3
.4byte sCastformRainyAnims_1_4
.4byte sCastformRainyAnims_1_5
.4byte sCastformRainyAnims_1_6
.4byte sCastformRainyAnims_1_7
.4byte sCastformRainyAnims_1_8
sCastformRainyAnimTable2:
.4byte sCastformRainyAnims_2_1
.4byte sCastformRainyAnims_2_2
.4byte sCastformRainyAnims_2_3
.4byte sCastformRainyAnims_2_4
.4byte sCastformRainyAnims_2_5
.4byte sCastformRainyAnims_2_6
.4byte sCastformRainyAnims_2_7
.4byte sCastformRainyAnims_2_8
sCastformRainyAnimTable3:
.4byte sCastformRainyAnims_3_1
.4byte sCastformRainyAnims_3_2
.4byte sCastformRainyAnims_3_3
.4byte sCastformRainyAnims_3_4
.4byte sCastformRainyAnims_3_5
.4byte sCastformRainyAnims_3_6
.4byte sCastformRainyAnims_3_7
.4byte sCastformRainyAnims_3_8
sCastformRainyAnimTable4:
.4byte sCastformRainyAnims_4_1
.4byte sCastformRainyAnims_4_2
.4byte sCastformRainyAnims_4_3
.4byte sCastformRainyAnims_4_4
.4byte sCastformRainyAnims_4_5
.4byte sCastformRainyAnims_4_6
.4byte sCastformRainyAnims_4_7
.4byte sCastformRainyAnims_4_8
sCastformRainyAnimTable5:
.4byte sCastformRainyAnims_5_1
.4byte sCastformRainyAnims_5_2
.4byte sCastformRainyAnims_5_3
.4byte sCastformRainyAnims_5_4
.4byte sCastformRainyAnims_5_5
.4byte sCastformRainyAnims_5_6
.4byte sCastformRainyAnims_5_7
.4byte sCastformRainyAnims_5_8
sCastformRainyAnimTable6:
.4byte sCastformRainyAnims_6_1
.4byte sCastformRainyAnims_6_1
.4byte sCastformRainyAnims_6_1
.4byte sCastformRainyAnims_6_1
.4byte sCastformRainyAnims_6_1
.4byte sCastformRainyAnims_6_1
.4byte sCastformRainyAnims_6_1
.4byte sCastformRainyAnims_6_1
sCastformRainyAnimTable7:
.4byte sCastformRainyAnims_7_1
.4byte sCastformRainyAnims_7_2
.4byte sCastformRainyAnims_7_3
.4byte sCastformRainyAnims_7_4
.4byte sCastformRainyAnims_7_5
.4byte sCastformRainyAnims_7_6
.4byte sCastformRainyAnims_7_7
.4byte sCastformRainyAnims_7_8
sCastformRainyAnimTable8:
.4byte sCastformRainyAnims_8_1
.4byte sCastformRainyAnims_8_2
.4byte sCastformRainyAnims_8_3
.4byte sCastformRainyAnims_8_4
.4byte sCastformRainyAnims_8_5
.4byte sCastformRainyAnims_8_6
.4byte sCastformRainyAnims_8_7
.4byte sCastformRainyAnims_8_8
sCastformRainyAnimTable9:
.4byte sCastformRainyAnims_9_1
.4byte sCastformRainyAnims_9_2
.4byte sCastformRainyAnims_9_3
.4byte sCastformRainyAnims_9_4
.4byte sCastformRainyAnims_9_5
.4byte sCastformRainyAnims_9_6
.4byte sCastformRainyAnims_9_7
.4byte sCastformRainyAnims_9_8
sCastformRainyAnimTable10:
.4byte sCastformRainyAnims_10_1
.4byte sCastformRainyAnims_10_2
.4byte sCastformRainyAnims_10_3
.4byte sCastformRainyAnims_10_4
.4byte sCastformRainyAnims_10_5
.4byte sCastformRainyAnims_10_6
.4byte sCastformRainyAnims_10_7
.4byte sCastformRainyAnims_10_8
sCastformRainyAnimTable11:
.4byte sCastformRainyAnims_11_1
.4byte sCastformRainyAnims_11_2
.4byte sCastformRainyAnims_11_3
.4byte sCastformRainyAnims_11_4
.4byte sCastformRainyAnims_11_5
.4byte sCastformRainyAnims_11_6
.4byte sCastformRainyAnims_11_7
.4byte sCastformRainyAnims_11_8
sCastformRainyAnimTable12:
.4byte sCastformRainyAnims_12_1
.4byte sCastformRainyAnims_12_2
.4byte sCastformRainyAnims_12_3
.4byte sCastformRainyAnims_12_4
.4byte sCastformRainyAnims_12_5
.4byte sCastformRainyAnims_12_6
.4byte sCastformRainyAnims_12_7
.4byte sCastformRainyAnims_12_8
sCastformRainyAnimTable13:
.4byte sCastformRainyAnims_13_1
.4byte sCastformRainyAnims_13_2
.4byte sCastformRainyAnims_13_3
.4byte sCastformRainyAnims_13_4
.4byte sCastformRainyAnims_13_5
.4byte sCastformRainyAnims_13_6
.4byte sCastformRainyAnims_13_7
.4byte sCastformRainyAnims_13_8
sAxAnimationsCastformRainy:
.4byte sCastformRainyAnimTable1
.4byte sCastformRainyAnimTable2
.4byte sCastformRainyAnimTable3
.4byte sCastformRainyAnimTable4
.4byte sCastformRainyAnimTable5
.4byte sCastformRainyAnimTable6
.4byte sCastformRainyAnimTable7
.4byte sCastformRainyAnimTable8
.4byte sCastformRainyAnimTable9
.4byte sCastformRainyAnimTable10
.4byte sCastformRainyAnimTable11
.4byte sCastformRainyAnimTable12
.4byte sCastformRainyAnimTable13
sAxSpritesCastformRainy:
.4byte sCastformRainySprites1
.4byte sCastformRainySprites2
.4byte sCastformRainySprites3
.4byte sCastformRainySprites4
.4byte sCastformRainySprites5
.4byte sCastformRainySprites6
.4byte sCastformRainySprites7
.4byte sCastformRainySprites8
.4byte sCastformRainySprites9
.4byte sCastformRainySprites10
.4byte sCastformRainySprites11
.4byte sCastformRainySprites12
.4byte sCastformRainySprites13
.4byte sCastformRainySprites14
.4byte sCastformRainySprites15
.4byte sCastformRainySprites16
.4byte sCastformRainySprites17
.4byte sCastformRainySprites18
.4byte sCastformRainySprites19
.4byte sCastformRainySprites20
.4byte sCastformRainySprites21
.4byte sCastformRainySprites22
.4byte sCastformRainySprites23
.4byte sCastformRainySprites24
.4byte sCastformRainySprites25
.4byte sCastformRainySprites26
.4byte sCastformRainySprites27
.4byte sCastformRainySprites28
.4byte sCastformRainySprites29
.4byte sCastformRainySprites30
.4byte sCastformRainySprites31
.4byte sCastformRainySprites32
sAxMainCastformRainy:
ax_main sAxPosesCastformRainy, sAxAnimationsCastformRainy, 13, sAxSpritesCastformRainy, sAxPositionsCastformRainy
