.global gAxCleffa
gAxCleffa:
ax_siro sAxMainCleffa
sCleffaPose1:
ax_pose 0, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose2:
ax_pose 1, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose3:
ax_pose 2, 0x01ed, 0x80f3, 0x1c00
ax_pose_terminator
sCleffaPose4:
ax_pose 3, 0x01ed, 0x90eb, 0x1c00
ax_pose_terminator
sCleffaPose5:
ax_pose 4, 0x01ed, 0x90eb, 0x1c00
ax_pose_terminator
sCleffaPose6:
ax_pose 5, 0x01ed, 0x90eb, 0x1c00
ax_pose_terminator
sCleffaPose7:
ax_pose 6, 0x01ed, 0x90eb, 0x1c00
ax_pose_terminator
sCleffaPose8:
ax_pose 7, 0x01ed, 0x90eb, 0x1c00
ax_pose_terminator
sCleffaPose9:
ax_pose 8, 0x01ed, 0x90eb, 0x1c00
ax_pose_terminator
sCleffaPose10:
ax_pose 9, 0x01ed, 0x90eb, 0x1c00
ax_pose_terminator
sCleffaPose11:
ax_pose 10, 0x01ed, 0x90eb, 0x1c00
ax_pose_terminator
sCleffaPose12:
ax_pose 11, 0x01ed, 0x90eb, 0x1c00
ax_pose_terminator
sCleffaPose13:
ax_pose 12, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose14:
ax_pose 13, 0x01ee, 0x80f3, 0x1c00
ax_pose_terminator
sCleffaPose15:
ax_pose 14, 0x01ee, 0x80f5, 0x1c00
ax_pose_terminator
sCleffaPose16:
ax_pose 9, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose17:
ax_pose 10, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose18:
ax_pose 11, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose19:
ax_pose 6, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose20:
ax_pose 7, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose21:
ax_pose 8, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose22:
ax_pose 3, 0x01ed, 0x80f5, 0x1c00
ax_pose_terminator
sCleffaPose23:
ax_pose 4, 0x01ed, 0x80f5, 0x1c00
ax_pose_terminator
sCleffaPose24:
ax_pose 5, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose25:
ax_pose 0, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose26:
ax_pose 15, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose27:
ax_pose 16, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose28:
ax_pose 3, 0x01ed, 0x90eb, 0x1c00
ax_pose_terminator
sCleffaPose29:
ax_pose 17, 0x01ed, 0x90eb, 0x1c00
ax_pose_terminator
sCleffaPose30:
ax_pose 18, 0x01ed, 0x90eb, 0x1c00
ax_pose_terminator
sCleffaPose31:
ax_pose 6, 0x01ed, 0x90eb, 0x1c00
ax_pose_terminator
sCleffaPose32:
ax_pose 19, 0x01ed, 0x90eb, 0x1c00
ax_pose_terminator
sCleffaPose33:
ax_pose 20, 0x01ed, 0x90eb, 0x1c00
ax_pose_terminator
sCleffaPose34:
ax_pose 9, 0x01ed, 0x90eb, 0x1c00
ax_pose_terminator
sCleffaPose35:
ax_pose 21, 0x01ed, 0x90eb, 0x1c00
ax_pose_terminator
sCleffaPose36:
ax_pose 22, 0x01ed, 0x90eb, 0x1c00
ax_pose_terminator
sCleffaPose37:
ax_pose 12, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose38:
ax_pose 23, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose39:
ax_pose 24, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose40:
ax_pose 9, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose41:
ax_pose 21, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose42:
ax_pose 22, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose43:
ax_pose 6, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose44:
ax_pose 19, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose45:
ax_pose 20, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose46:
ax_pose 3, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose47:
ax_pose 17, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose48:
ax_pose 18, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose49:
ax_pose 0, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose50:
ax_pose 15, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose51:
ax_pose 16, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose52:
ax_pose 3, 0x01ed, 0x90eb, 0x1c00
ax_pose_terminator
sCleffaPose53:
ax_pose 17, 0x01ed, 0x90eb, 0x1c00
ax_pose_terminator
sCleffaPose54:
ax_pose 18, 0x01ed, 0x90eb, 0x1c00
ax_pose_terminator
sCleffaPose55:
ax_pose 6, 0x01ed, 0x90eb, 0x1c00
ax_pose_terminator
sCleffaPose56:
ax_pose 19, 0x01ed, 0x90eb, 0x1c00
ax_pose_terminator
sCleffaPose57:
ax_pose 20, 0x01ed, 0x90eb, 0x1c00
ax_pose_terminator
sCleffaPose58:
ax_pose 9, 0x01ed, 0x90eb, 0x1c00
ax_pose_terminator
sCleffaPose59:
ax_pose 21, 0x01ed, 0x90eb, 0x1c00
ax_pose_terminator
sCleffaPose60:
ax_pose 22, 0x01ed, 0x90eb, 0x1c00
ax_pose_terminator
sCleffaPose61:
ax_pose 12, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose62:
ax_pose 23, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose63:
ax_pose 24, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose64:
ax_pose 9, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose65:
ax_pose 21, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose66:
ax_pose 22, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose67:
ax_pose 6, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose68:
ax_pose 19, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose69:
ax_pose 20, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose70:
ax_pose 3, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose71:
ax_pose 17, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose72:
ax_pose 18, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose73:
ax_pose 0, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose74:
ax_pose 15, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose75:
ax_pose 16, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose76:
ax_pose 3, 0x01ed, 0x90eb, 0x1c00
ax_pose_terminator
sCleffaPose77:
ax_pose 17, 0x01ed, 0x90eb, 0x1c00
ax_pose_terminator
sCleffaPose78:
ax_pose 18, 0x01ed, 0x90eb, 0x1c00
ax_pose_terminator
sCleffaPose79:
ax_pose 6, 0x01ed, 0x90eb, 0x1c00
ax_pose_terminator
sCleffaPose80:
ax_pose 19, 0x01ed, 0x90eb, 0x1c00
ax_pose_terminator
sCleffaPose81:
ax_pose 20, 0x01ed, 0x90eb, 0x1c00
ax_pose_terminator
sCleffaPose82:
ax_pose 9, 0x01ed, 0x90eb, 0x1c00
ax_pose_terminator
sCleffaPose83:
ax_pose 21, 0x01ed, 0x90eb, 0x1c00
ax_pose_terminator
sCleffaPose84:
ax_pose 22, 0x01ed, 0x90eb, 0x1c00
ax_pose_terminator
sCleffaPose85:
ax_pose 12, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose86:
ax_pose 23, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose87:
ax_pose 24, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose88:
ax_pose 9, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose89:
ax_pose 21, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose90:
ax_pose 22, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose91:
ax_pose 6, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose92:
ax_pose 19, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose93:
ax_pose 20, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose94:
ax_pose 3, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose95:
ax_pose 17, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose96:
ax_pose 18, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose97:
ax_pose 0, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose98:
ax_pose 1, 0x01ee, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose99:
ax_pose 2, 0x01ee, 0x80f3, 0x1c00
ax_pose_terminator
sCleffaPose100:
ax_pose 3, 0x01ed, 0x90eb, 0x1c00
ax_pose_terminator
sCleffaPose101:
ax_pose 4, 0x01ee, 0x90eb, 0x1c00
ax_pose_terminator
sCleffaPose102:
ax_pose 5, 0x01ed, 0x90ec, 0x1c00
ax_pose_terminator
sCleffaPose103:
ax_pose 6, 0x01ed, 0x90eb, 0x1c00
ax_pose_terminator
sCleffaPose104:
ax_pose 7, 0x01ee, 0x90eb, 0x1c00
ax_pose_terminator
sCleffaPose105:
ax_pose 8, 0x01ee, 0x90eb, 0x1c00
ax_pose_terminator
sCleffaPose106:
ax_pose 9, 0x01ed, 0x90eb, 0x1c00
ax_pose_terminator
sCleffaPose107:
ax_pose 10, 0x01ee, 0x90eb, 0x1c00
ax_pose_terminator
sCleffaPose108:
ax_pose 11, 0x01ee, 0x90ea, 0x1c00
ax_pose_terminator
sCleffaPose109:
ax_pose 12, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose110:
ax_pose 13, 0x01ef, 0x80f3, 0x1c00
ax_pose_terminator
sCleffaPose111:
ax_pose 14, 0x01ef, 0x80f5, 0x1c00
ax_pose_terminator
sCleffaPose112:
ax_pose 9, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose113:
ax_pose 10, 0x01ee, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose114:
ax_pose 11, 0x01ee, 0x80f5, 0x1c00
ax_pose_terminator
sCleffaPose115:
ax_pose 6, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose116:
ax_pose 7, 0x01ee, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose117:
ax_pose 8, 0x01ee, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose118:
ax_pose 3, 0x01ed, 0x80f5, 0x1c00
ax_pose_terminator
sCleffaPose119:
ax_pose 4, 0x01ee, 0x80f5, 0x1c00
ax_pose_terminator
sCleffaPose120:
ax_pose 5, 0x01ee, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose121:
ax_pose 25, 0x01ee, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose122:
ax_pose 26, 0x01ee, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose123:
ax_pose 27, 0x01e4, 0x80f1, 0x1c00
ax_pose_terminator
sCleffaPose124:
ax_pose 28, 0x01e5, 0x90ed, 0x1c00
ax_pose_terminator
sCleffaPose125:
ax_pose 29, 0x01e5, 0x90ed, 0x1c00
ax_pose_terminator
sCleffaPose126:
ax_pose 30, 0x01e6, 0x90ee, 0x1c00
ax_pose_terminator
sCleffaPose127:
ax_pose 31, 0x01e5, 0x80f2, 0x1c00
ax_pose_terminator
sCleffaPose128:
ax_pose 30, 0x01e6, 0x80f2, 0x1c00
ax_pose_terminator
sCleffaPose129:
ax_pose 29, 0x01e5, 0x80f3, 0x1c00
ax_pose_terminator
sCleffaPose130:
ax_pose 28, 0x01e5, 0x80f3, 0x1c00
ax_pose_terminator
sCleffaPose131:
ax_pose 0, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose132:
ax_pose 15, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose133:
ax_pose 3, 0x01ed, 0x90eb, 0x1c00
ax_pose_terminator
sCleffaPose134:
ax_pose 17, 0x01ed, 0x90eb, 0x1c00
ax_pose_terminator
sCleffaPose135:
ax_pose 6, 0x01ed, 0x90eb, 0x1c00
ax_pose_terminator
sCleffaPose136:
ax_pose 19, 0x01ed, 0x90eb, 0x1c00
ax_pose_terminator
sCleffaPose137:
ax_pose 9, 0x01ed, 0x90eb, 0x1c00
ax_pose_terminator
sCleffaPose138:
ax_pose 21, 0x01ed, 0x90eb, 0x1c00
ax_pose_terminator
sCleffaPose139:
ax_pose 12, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose140:
ax_pose 23, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose141:
ax_pose 9, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose142:
ax_pose 21, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose143:
ax_pose 6, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose144:
ax_pose 19, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose145:
ax_pose 3, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose146:
ax_pose 17, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose147:
ax_pose 15, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose148:
ax_pose 17, 0x01ed, 0x80f5, 0x1c00
ax_pose_terminator
sCleffaPose149:
ax_pose 19, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose150:
ax_pose 21, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose151:
ax_pose 23, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose152:
ax_pose 21, 0x01ed, 0x90eb, 0x1c00
ax_pose_terminator
sCleffaPose153:
ax_pose 19, 0x01ed, 0x90eb, 0x1c00
ax_pose_terminator
sCleffaPose154:
ax_pose 17, 0x01ed, 0x90eb, 0x1c00
ax_pose_terminator
sCleffaPose155:
ax_pose 15, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose156:
ax_pose 17, 0x01ed, 0x90eb, 0x1c00
ax_pose_terminator
sCleffaPose157:
ax_pose 19, 0x01ed, 0x90eb, 0x1c00
ax_pose_terminator
sCleffaPose158:
ax_pose 21, 0x01ed, 0x90eb, 0x1c00
ax_pose_terminator
sCleffaPose159:
ax_pose 23, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose160:
ax_pose 21, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose161:
ax_pose 19, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose162:
ax_pose 17, 0x01ed, 0x80f5, 0x1c00
ax_pose_terminator
sCleffaPose163:
ax_pose 0, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose164:
ax_pose 15, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose165:
ax_pose 16, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose166:
ax_pose 3, 0x01ed, 0x90eb, 0x1c00
ax_pose_terminator
sCleffaPose167:
ax_pose 17, 0x01ed, 0x90eb, 0x1c00
ax_pose_terminator
sCleffaPose168:
ax_pose 18, 0x01ed, 0x90eb, 0x1c00
ax_pose_terminator
sCleffaPose169:
ax_pose 6, 0x01ed, 0x90eb, 0x1c00
ax_pose_terminator
sCleffaPose170:
ax_pose 19, 0x01ed, 0x90eb, 0x1c00
ax_pose_terminator
sCleffaPose171:
ax_pose 20, 0x01ed, 0x90eb, 0x1c00
ax_pose_terminator
sCleffaPose172:
ax_pose 9, 0x01ed, 0x90eb, 0x1c00
ax_pose_terminator
sCleffaPose173:
ax_pose 21, 0x01ed, 0x90eb, 0x1c00
ax_pose_terminator
sCleffaPose174:
ax_pose 22, 0x01ed, 0x90eb, 0x1c00
ax_pose_terminator
sCleffaPose175:
ax_pose 12, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose176:
ax_pose 23, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose177:
ax_pose 24, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose178:
ax_pose 9, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose179:
ax_pose 21, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose180:
ax_pose 22, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose181:
ax_pose 6, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose182:
ax_pose 19, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose183:
ax_pose 20, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose184:
ax_pose 3, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose185:
ax_pose 17, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose186:
ax_pose 18, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose187:
ax_pose 16, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose188:
ax_pose 18, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose189:
ax_pose 20, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose190:
ax_pose 22, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose191:
ax_pose 24, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose192:
ax_pose 22, 0x01ed, 0x90eb, 0x1c00
ax_pose_terminator
sCleffaPose193:
ax_pose 20, 0x01ed, 0x90eb, 0x1c00
ax_pose_terminator
sCleffaPose194:
ax_pose 18, 0x01ed, 0x90eb, 0x1c00
ax_pose_terminator
sCleffaPose195:
ax_pose 0, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose196:
ax_pose 3, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose197:
ax_pose 6, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose198:
ax_pose 9, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose199:
ax_pose 12, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sCleffaPose200:
ax_pose 9, 0x01ed, 0x90eb, 0x1c00
ax_pose_terminator
sCleffaPose201:
ax_pose 6, 0x01ed, 0x90eb, 0x1c00
ax_pose_terminator
sCleffaPose202:
ax_pose 3, 0x01ed, 0x90eb, 0x1c00
ax_pose_terminator
.align 2
sCleffaAnims_1_1:
ax_anim 8, 0, 0, 0, 0, 0, 0,
ax_anim 6, 0, 1, 0, 0, 1, 0,
ax_anim 6, 0, 1, 0, -1, 1, 0,
ax_anim 6, 0, 1, 0, 0, 1, 0,
ax_anim 8, 0, 0, 0, 0, 0, 0,
ax_anim 6, 0, 2, 0, 0, -1, 0,
ax_anim 6, 0, 2, 0, -1, -1, 0,
ax_anim 6, 0, 2, 0, 0, -1, 0,
ax_anim_terminator
sCleffaAnims_1_2:
ax_anim 8, 0, 3, 0, 0, 0, 0,
ax_anim 6, 0, 4, 0, 0, -1, 1,
ax_anim 6, 0, 4, 0, -1, -1, 1,
ax_anim 6, 0, 4, 0, 0, -1, 1,
ax_anim 8, 0, 3, 0, 0, 0, 0,
ax_anim 6, 0, 5, 1, 0, 1, -1,
ax_anim 6, 0, 5, 1, -1, 1, -1,
ax_anim 6, 0, 5, 1, 0, 1, -1,
ax_anim_terminator
sCleffaAnims_1_3:
ax_anim 8, 0, 6, 0, 0, 0, 0,
ax_anim 6, 0, 7, 0, 0, 0, 1,
ax_anim 6, 0, 7, 0, -1, 0, 1,
ax_anim 6, 0, 7, 0, 0, 0, 1,
ax_anim 8, 0, 6, 0, 0, 0, 0,
ax_anim 6, 0, 8, 0, 0, 0, -1,
ax_anim 6, 0, 8, 0, -1, 0, -1,
ax_anim 6, 0, 8, 0, 0, 0, -1,
ax_anim_terminator
sCleffaAnims_1_4:
ax_anim 8, 0, 9, 0, 0, 0, 0,
ax_anim 6, 0, 10, 0, 0, 1, 1,
ax_anim 6, 0, 10, 0, -1, 1, 1,
ax_anim 6, 0, 10, 0, 0, 1, 1,
ax_anim 8, 0, 9, 0, 0, 0, 0,
ax_anim 6, 0, 11, 0, 0, -1, -1,
ax_anim 6, 0, 11, 0, -1, -1, -1,
ax_anim 6, 0, 11, 0, 0, -1, -1,
ax_anim_terminator
sCleffaAnims_1_5:
ax_anim 8, 0, 12, 0, 0, 0, 0,
ax_anim 6, 0, 13, 0, 0, -1, 0,
ax_anim 6, 0, 13, 0, -1, -1, 0,
ax_anim 6, 0, 13, 0, 0, -1, 0,
ax_anim 8, 0, 12, 0, 0, 0, 0,
ax_anim 6, 0, 14, 0, 0, 1, 0,
ax_anim 6, 0, 14, 0, -1, 1, 0,
ax_anim 6, 0, 14, 0, 0, 1, 0,
ax_anim_terminator
sCleffaAnims_1_6:
ax_anim 8, 0, 15, 0, 0, 0, 0,
ax_anim 6, 0, 16, 0, 0, -1, 1,
ax_anim 6, 0, 16, 0, -1, -1, 1,
ax_anim 6, 0, 16, 0, 0, -1, 1,
ax_anim 8, 0, 15, 0, 0, 0, 0,
ax_anim 6, 0, 17, 0, 0, 1, -1,
ax_anim 6, 0, 17, 0, -1, 1, -1,
ax_anim 6, 0, 17, 0, 0, 1, -1,
ax_anim_terminator
sCleffaAnims_1_7:
ax_anim 8, 0, 18, 0, 0, 0, 0,
ax_anim 6, 0, 19, 0, 0, 0, 1,
ax_anim 6, 0, 19, 0, -1, 0, 1,
ax_anim 6, 0, 19, 0, 0, 0, 1,
ax_anim 8, 0, 18, 0, 0, 0, 0,
ax_anim 6, 0, 20, 0, 0, 0, -1,
ax_anim 6, 0, 20, 0, -1, 0, -1,
ax_anim 6, 0, 20, 0, 0, 0, -1,
ax_anim_terminator
sCleffaAnims_1_8:
ax_anim 8, 0, 21, 0, 0, 0, 0,
ax_anim 6, 0, 22, 0, 0, 1, 1,
ax_anim 6, 0, 22, 0, -1, 1, 1,
ax_anim 6, 0, 22, 0, 0, 1, 1,
ax_anim 8, 0, 21, 0, 0, 0, 0,
ax_anim 6, 0, 23, 1, 0, -1, -1,
ax_anim 6, 0, 23, 1, -1, -1, -1,
ax_anim 6, 0, 23, 1, 0, -1, -1,
ax_anim_terminator
.align 2
sCleffaAnims_2_1:
ax_anim 2, 0, 25, 0, -1, 0, -1,
ax_anim 6, 0, 25, 0, -2, 0, -2,
ax_anim 1, 0, 25, 0, 0, 0, 0,
ax_anim 1, 2, 25, 0, 4, 0, 4,
ax_anim 1, 0, 26, 0, 10, 0, 10,
ax_anim 2, 0, 26, 0, 19, 0, 19,
ax_anim 2, 1, 26, 1, 19, 1, 19,
ax_anim 2, 0, 26, 0, 19, 0, 19,
ax_anim 2, 0, 26, 1, 19, 1, 19,
ax_anim 2, 0, 24, 0, 7, 0, 7,
ax_anim_terminator
sCleffaAnims_2_2:
ax_anim 2, 0, 28, -1, -1, -1, -1,
ax_anim 6, 0, 28, -2, -2, -2, -2,
ax_anim 1, 0, 28, 0, 0, 0, 0,
ax_anim 1, 2, 28, 4, 4, 4, 4,
ax_anim 1, 0, 29, 10, 10, 10, 10,
ax_anim 2, 0, 29, 20, 20, 20, 20,
ax_anim 2, 1, 29, 21, 19, 21, 19,
ax_anim 2, 0, 29, 20, 20, 20, 20,
ax_anim 2, 0, 29, 21, 19, 21, 19,
ax_anim 2, 0, 27, 7, 7, 7, 7,
ax_anim_terminator
sCleffaAnims_2_3:
ax_anim 2, 0, 31, -1, 0, -1, 0,
ax_anim 6, 0, 31, -2, 0, -2, 0,
ax_anim 1, 0, 31, 0, 0, 0, 0,
ax_anim 1, 2, 31, 4, 0, 4, 0,
ax_anim 1, 0, 32, 10, 0, 10, 0,
ax_anim 2, 0, 32, 22, 0, 22, 0,
ax_anim 2, 1, 32, 22, 1, 22, 1,
ax_anim 2, 0, 32, 22, 0, 22, 0,
ax_anim 2, 0, 32, 22, 1, 22, 1,
ax_anim 2, 0, 30, 7, 0, 7, 0,
ax_anim_terminator
sCleffaAnims_2_4:
ax_anim 2, 0, 34, -1, 1, -1, 1,
ax_anim 6, 0, 34, -2, 2, -2, 2,
ax_anim 1, 0, 34, 0, -1, 0, -1,
ax_anim 1, 2, 34, 5, -6, 5, -6,
ax_anim 1, 0, 35, 12, -13, 12, -13,
ax_anim 2, 0, 35, 21, -22, 21, -22,
ax_anim 2, 1, 35, 22, -21, 22, -21,
ax_anim 2, 0, 35, 21, -22, 21, -22,
ax_anim 2, 0, 35, 22, -21, 22, -21,
ax_anim 2, 0, 33, 7, -7, 7, -7,
ax_anim_terminator
sCleffaAnims_2_5:
ax_anim 2, 0, 37, 0, 1, 0, 1,
ax_anim 6, 0, 37, 0, 2, 0, 2,
ax_anim 1, 0, 37, 0, 0, 0, 0,
ax_anim 1, 2, 37, 0, -4, 0, -4,
ax_anim 1, 0, 38, 0, -11, 0, -11,
ax_anim 2, 0, 38, 0, -21, 0, -21,
ax_anim 2, 1, 38, 1, -21, 1, -21,
ax_anim 2, 0, 38, 0, -21, 0, -21,
ax_anim 2, 0, 38, 1, -21, 1, -21,
ax_anim 2, 0, 36, 0, -7, 0, -7,
ax_anim_terminator
sCleffaAnims_2_6:
ax_anim 2, 0, 40, 1, 1, 1, 1,
ax_anim 6, 0, 40, 2, 2, 2, 2,
ax_anim 1, 0, 40, 0, -1, 0, -1,
ax_anim 1, 2, 40, -5, -6, -5, -6,
ax_anim 1, 0, 41, -12, -13, -12, -13,
ax_anim 2, 0, 41, -21, -22, -21, -22,
ax_anim 2, 1, 41, -22, -21, -22, -21,
ax_anim 2, 0, 41, -21, -22, -21, -22,
ax_anim 2, 0, 41, -22, -21, -22, -21,
ax_anim 2, 0, 39, -7, -7, -7, -7,
ax_anim_terminator
sCleffaAnims_2_7:
ax_anim 2, 0, 43, 1, 0, 1, 0,
ax_anim 6, 0, 43, 2, 0, 2, 0,
ax_anim 1, 0, 43, 0, 0, 0, 0,
ax_anim 1, 2, 43, -4, 0, -4, 0,
ax_anim 1, 0, 44, -10, 0, -10, 0,
ax_anim 2, 0, 44, -22, 0, -22, 0,
ax_anim 2, 1, 44, -22, 1, -22, 1,
ax_anim 2, 0, 44, -22, 0, -22, 0,
ax_anim 2, 0, 44, -22, 1, -22, 1,
ax_anim 2, 0, 42, -7, 0, -7, 0,
ax_anim_terminator
sCleffaAnims_2_8:
ax_anim 2, 0, 46, 1, -1, 1, -1,
ax_anim 6, 0, 46, 2, -2, 2, -2,
ax_anim 1, 0, 46, 0, 0, 0, 0,
ax_anim 1, 2, 46, -4, 4, -4, 4,
ax_anim 1, 0, 47, -10, 10, -10, 10,
ax_anim 2, 0, 47, -20, 20, -20, 20,
ax_anim 2, 1, 47, -21, 19, -21, 19,
ax_anim 2, 0, 47, -20, 20, -20, 20,
ax_anim 2, 0, 47, -21, 19, -21, 19,
ax_anim 2, 0, 45, -7, 7, -7, 7,
ax_anim_terminator
.align 2
sCleffaAnims_3_1:
ax_anim 2, 0, 49, 0, -1, 0, -1,
ax_anim 6, 0, 49, 0, -2, 0, -2,
ax_anim 1, 0, 49, 0, 0, 0, 0,
ax_anim 1, 2, 49, 0, 4, 0, 4,
ax_anim 1, 0, 50, 0, 10, 0, 10,
ax_anim 2, 0, 50, 0, 19, 0, 19,
ax_anim 2, 1, 50, 1, 19, 1, 19,
ax_anim 2, 0, 50, 0, 19, 0, 19,
ax_anim 2, 0, 50, 1, 19, 1, 19,
ax_anim 2, 0, 48, 0, 7, 0, 7,
ax_anim_terminator
sCleffaAnims_3_2:
ax_anim 2, 0, 52, -1, -1, -1, -1,
ax_anim 6, 0, 52, -2, -2, -2, -2,
ax_anim 1, 0, 52, 0, 0, 0, 0,
ax_anim 1, 2, 52, 4, 4, 4, 4,
ax_anim 1, 0, 53, 10, 10, 10, 10,
ax_anim 2, 0, 53, 20, 20, 20, 20,
ax_anim 2, 1, 53, 21, 19, 21, 19,
ax_anim 2, 0, 53, 20, 20, 20, 20,
ax_anim 2, 0, 53, 21, 19, 21, 19,
ax_anim 2, 0, 51, 7, 7, 7, 7,
ax_anim_terminator
sCleffaAnims_3_3:
ax_anim 2, 0, 55, -1, 0, -1, 0,
ax_anim 6, 0, 55, -2, 0, -2, 0,
ax_anim 1, 0, 55, 0, 0, 0, 0,
ax_anim 1, 2, 55, 4, 0, 4, 0,
ax_anim 1, 0, 56, 10, 0, 10, 0,
ax_anim 2, 0, 56, 22, 0, 22, 0,
ax_anim 2, 1, 56, 22, 1, 22, 1,
ax_anim 2, 0, 56, 22, 0, 22, 0,
ax_anim 2, 0, 56, 22, 1, 22, 1,
ax_anim 2, 0, 54, 7, 0, 7, 0,
ax_anim_terminator
sCleffaAnims_3_4:
ax_anim 2, 0, 58, -1, 1, -1, 1,
ax_anim 6, 0, 58, -2, 2, -2, 2,
ax_anim 1, 0, 58, 0, -1, 0, -1,
ax_anim 1, 2, 58, 5, -6, 5, -6,
ax_anim 1, 0, 59, 12, -13, 12, -13,
ax_anim 2, 0, 59, 21, -22, 21, -22,
ax_anim 2, 1, 59, 22, -21, 22, -21,
ax_anim 2, 0, 59, 21, -22, 21, -22,
ax_anim 2, 0, 59, 22, -21, 22, -21,
ax_anim 2, 0, 57, 7, -7, 7, -7,
ax_anim_terminator
sCleffaAnims_3_5:
ax_anim 2, 0, 61, 0, 1, 0, 1,
ax_anim 6, 0, 61, 0, 2, 0, 2,
ax_anim 1, 0, 61, 0, 0, 0, 0,
ax_anim 1, 2, 61, 0, -4, 0, -4,
ax_anim 1, 0, 62, 0, -11, 0, -11,
ax_anim 2, 0, 62, 0, -21, 0, -21,
ax_anim 2, 1, 62, 1, -21, 1, -21,
ax_anim 2, 0, 62, 0, -21, 0, -21,
ax_anim 2, 0, 62, 1, -21, 1, -21,
ax_anim 2, 0, 60, 0, -7, 0, -7,
ax_anim_terminator
sCleffaAnims_3_6:
ax_anim 2, 0, 64, 1, 1, 1, 1,
ax_anim 6, 0, 64, 2, 2, 2, 2,
ax_anim 1, 0, 64, 0, -1, 0, -1,
ax_anim 1, 2, 64, -5, -6, -5, -6,
ax_anim 1, 0, 65, -12, -13, -12, -13,
ax_anim 2, 0, 65, -21, -22, -21, -22,
ax_anim 2, 1, 65, -22, -21, -22, -21,
ax_anim 2, 0, 65, -21, -22, -21, -22,
ax_anim 2, 0, 65, -22, -21, -22, -21,
ax_anim 2, 0, 63, -7, -7, -7, -7,
ax_anim_terminator
sCleffaAnims_3_7:
ax_anim 2, 0, 67, 1, 0, 1, 0,
ax_anim 6, 0, 67, 2, 0, 2, 0,
ax_anim 1, 0, 67, 0, 0, 0, 0,
ax_anim 1, 2, 67, -4, 0, -4, 0,
ax_anim 1, 0, 68, -10, 0, -10, 0,
ax_anim 2, 0, 68, -22, 0, -22, 0,
ax_anim 2, 1, 68, -22, 1, -22, 1,
ax_anim 2, 0, 68, -22, 0, -22, 0,
ax_anim 2, 0, 68, -22, 1, -22, 1,
ax_anim 2, 0, 66, -7, 0, -7, 0,
ax_anim_terminator
sCleffaAnims_3_8:
ax_anim 2, 0, 70, 1, -1, 1, -1,
ax_anim 6, 0, 70, 2, -2, 2, -2,
ax_anim 1, 0, 70, 0, 0, 0, 0,
ax_anim 1, 2, 70, -4, 4, -4, 4,
ax_anim 1, 0, 71, -10, 10, -10, 10,
ax_anim 2, 0, 71, -20, 20, -20, 20,
ax_anim 2, 1, 71, -21, 19, -21, 19,
ax_anim 2, 0, 71, -20, 20, -20, 20,
ax_anim 2, 0, 71, -21, 19, -21, 19,
ax_anim 2, 0, 69, -7, 7, -7, 7,
ax_anim_terminator
.align 2
sCleffaAnims_4_1:
ax_anim 2, 0, 73, 0, 0, 0, 0,
ax_anim 4, 0, 77, 0, 0, 0, 0,
ax_anim 4, 0, 76, 0, 0, 0, 0,
ax_anim 4, 2, 74, 0, 0, 0, 0,
ax_anim 4, 0, 73, 0, 0, 0, 0,
ax_anim 4, 0, 95, 0, 0, 0, 0,
ax_anim 4, 0, 94, 0, 0, 0, 0,
ax_anim 4, 1, 74, 0, 0, 0, 0,
ax_anim 2, 0, 73, 0, 0, 0, 0,
ax_anim_terminator
sCleffaAnims_4_2:
ax_anim 2, 0, 76, 0, 0, 0, 0,
ax_anim 4, 0, 80, 0, 0, 0, 0,
ax_anim 4, 0, 79, 0, 0, 0, 0,
ax_anim 4, 2, 77, 0, 0, 0, 0,
ax_anim 4, 0, 76, 0, 0, 0, 0,
ax_anim 4, 0, 74, 0, 0, 0, 0,
ax_anim 4, 0, 73, 0, 0, 0, 0,
ax_anim 4, 1, 77, 0, 0, 0, 0,
ax_anim 2, 0, 76, 0, 0, 0, 0,
ax_anim_terminator
sCleffaAnims_4_3:
ax_anim 2, 0, 79, 0, 0, 0, 0,
ax_anim 4, 0, 83, 0, 0, 0, 0,
ax_anim 4, 0, 82, 0, 0, 0, 0,
ax_anim 4, 2, 80, 0, 0, 0, 0,
ax_anim 4, 0, 79, 0, 0, 0, 0,
ax_anim 4, 0, 77, 0, 0, 0, 0,
ax_anim 4, 0, 76, 0, 0, 0, 0,
ax_anim 4, 1, 80, 0, 0, 0, 0,
ax_anim 2, 0, 79, 0, 0, 0, 0,
ax_anim_terminator
sCleffaAnims_4_4:
ax_anim 2, 0, 82, 0, 0, 0, 0,
ax_anim 4, 0, 86, 0, 0, 0, 0,
ax_anim 4, 0, 85, 0, 0, 0, 0,
ax_anim 4, 2, 83, 0, 0, 0, 0,
ax_anim 4, 0, 82, 0, 0, 0, 0,
ax_anim 4, 0, 80, 0, 0, 0, 0,
ax_anim 4, 0, 79, 0, 0, 0, 0,
ax_anim 4, 1, 83, 0, 0, 0, 0,
ax_anim 2, 0, 82, 0, 0, 0, 0,
ax_anim_terminator
sCleffaAnims_4_5:
ax_anim 2, 0, 85, 0, 0, 0, 0,
ax_anim 4, 0, 89, 0, 0, 0, 0,
ax_anim 4, 0, 88, 0, 0, 0, 0,
ax_anim 4, 2, 86, 0, 0, 0, 0,
ax_anim 4, 0, 85, 0, 0, 0, 0,
ax_anim 4, 0, 83, 0, 0, 0, 0,
ax_anim 4, 0, 82, 0, 0, 0, 0,
ax_anim 4, 1, 86, 0, 0, 0, 0,
ax_anim 2, 0, 85, 0, 0, 0, 0,
ax_anim_terminator
sCleffaAnims_4_6:
ax_anim 2, 0, 88, 0, 0, 0, 0,
ax_anim 4, 0, 92, 0, 0, 0, 0,
ax_anim 4, 0, 91, 0, 0, 0, 0,
ax_anim 4, 2, 89, 0, 0, 0, 0,
ax_anim 4, 0, 88, 0, 0, 0, 0,
ax_anim 4, 0, 86, 0, 0, 0, 0,
ax_anim 4, 0, 85, 0, 0, 0, 0,
ax_anim 4, 1, 89, 0, 0, 0, 0,
ax_anim 2, 0, 88, 0, 0, 0, 0,
ax_anim_terminator
sCleffaAnims_4_7:
ax_anim 2, 0, 91, 0, 0, 0, 0,
ax_anim 4, 0, 95, 0, 0, 0, 0,
ax_anim 4, 0, 94, 0, 0, 0, 0,
ax_anim 4, 2, 92, 0, 0, 0, 0,
ax_anim 4, 0, 91, 0, 0, 0, 0,
ax_anim 4, 0, 89, 0, 0, 0, 0,
ax_anim 4, 0, 88, 0, 0, 0, 0,
ax_anim 4, 1, 92, 0, 0, 0, 0,
ax_anim 2, 0, 91, 0, 0, 0, 0,
ax_anim_terminator
sCleffaAnims_4_8:
ax_anim 2, 0, 94, 0, 0, 0, 0,
ax_anim 4, 0, 74, 0, 0, 0, 0,
ax_anim 4, 0, 73, 0, 0, 0, 0,
ax_anim 4, 2, 95, 0, 0, 0, 0,
ax_anim 4, 0, 94, 0, 0, 0, 0,
ax_anim 4, 0, 92, 0, 0, 0, 0,
ax_anim 4, 0, 91, 0, 0, 0, 0,
ax_anim 4, 1, 95, 0, 0, 0, 0,
ax_anim 2, 0, 94, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sCleffaAnims_5_1:
ax_anim 6, 0, 97, 0, 0, 0, 0,
ax_anim 5, 2, 96, 0, 0, 0, 0,
ax_anim 6, 0, 98, 0, 0, 0, 0,
ax_anim 5, 0, 96, 0, 0, 0, 0,
ax_anim 6, 0, 97, 0, 0, 0, 0,
ax_anim 4, 1, 96, 0, 0, 0, 0,
ax_anim_terminator
sCleffaAnims_5_2:
ax_anim 6, 0, 100, 0, 0, 0, 0,
ax_anim 5, 2, 99, 0, 0, 0, 0,
ax_anim 6, 0, 101, 0, 0, 0, 0,
ax_anim 5, 0, 99, 0, 0, 0, 0,
ax_anim 6, 0, 100, 0, 0, 0, 0,
ax_anim 4, 1, 99, 0, 0, 0, 0,
ax_anim_terminator
sCleffaAnims_5_3:
ax_anim 6, 0, 103, 0, 0, 0, 0,
ax_anim 5, 2, 102, 0, 0, 0, 0,
ax_anim 6, 0, 104, 0, 0, 0, 0,
ax_anim 5, 0, 102, 0, 0, 0, 0,
ax_anim 6, 0, 103, 0, 0, 0, 0,
ax_anim 4, 1, 102, 0, 0, 0, 0,
ax_anim_terminator
sCleffaAnims_5_4:
ax_anim 6, 0, 106, 0, 0, 0, 0,
ax_anim 5, 2, 105, 0, 0, 0, 0,
ax_anim 6, 0, 107, 0, 0, 0, 0,
ax_anim 5, 0, 105, 0, 0, 0, 0,
ax_anim 6, 0, 106, 0, 0, 0, 0,
ax_anim 4, 1, 105, 0, 0, 0, 0,
ax_anim_terminator
sCleffaAnims_5_5:
ax_anim 6, 0, 109, 0, 0, 0, 0,
ax_anim 5, 2, 108, 0, 0, 0, 0,
ax_anim 6, 0, 110, 0, 0, 0, 0,
ax_anim 5, 0, 108, 0, 0, 0, 0,
ax_anim 6, 0, 109, 0, 0, 0, 0,
ax_anim 4, 1, 108, 0, 0, 0, 0,
ax_anim_terminator
sCleffaAnims_5_6:
ax_anim 6, 0, 112, 0, 0, 0, 0,
ax_anim 5, 2, 111, 0, 0, 0, 0,
ax_anim 6, 0, 113, 0, 0, 0, 0,
ax_anim 5, 0, 111, 0, 0, 0, 0,
ax_anim 6, 0, 112, 0, 0, 0, 0,
ax_anim 4, 1, 111, 0, 0, 0, 0,
ax_anim_terminator
sCleffaAnims_5_7:
ax_anim 6, 0, 115, 0, 0, 0, 0,
ax_anim 5, 2, 114, 0, 0, 0, 0,
ax_anim 6, 0, 116, 0, 0, 0, 0,
ax_anim 5, 0, 114, 0, 0, 0, 0,
ax_anim 6, 0, 115, 0, 0, 0, 0,
ax_anim 4, 1, 114, 0, 0, 0, 0,
ax_anim_terminator
sCleffaAnims_5_8:
ax_anim 6, 0, 118, 0, 0, 0, 0,
ax_anim 5, 2, 117, 0, 0, 0, 0,
ax_anim 6, 0, 119, 0, 0, 0, 0,
ax_anim 5, 0, 117, 0, 0, 0, 0,
ax_anim 6, 0, 118, 0, 0, 0, 0,
ax_anim 4, 1, 117, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sCleffaAnims_6_1:
ax_anim 30, 0, 120, 0, 0, 0, 0,
ax_anim 35, 0, 121, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sCleffaAnims_7_1:
ax_anim 2, 0, 122, 0, -4, 0, -4,
ax_anim 8, 0, 122, 0, -5, 0, -5,
ax_anim_terminator
sCleffaAnims_7_2:
ax_anim 2, 0, 123, -4, -4, -4, -4,
ax_anim 8, 0, 123, -5, -5, -5, -5,
ax_anim_terminator
sCleffaAnims_7_3:
ax_anim 2, 0, 124, -4, 0, -4, 0,
ax_anim 8, 0, 124, -5, 0, -5, 0,
ax_anim_terminator
sCleffaAnims_7_4:
ax_anim 2, 0, 125, -4, 4, -4, 4,
ax_anim 8, 0, 125, -5, 5, -5, 5,
ax_anim_terminator
sCleffaAnims_7_5:
ax_anim 2, 0, 126, 0, 4, 0, 4,
ax_anim 8, 0, 126, 0, 5, 0, 5,
ax_anim_terminator
sCleffaAnims_7_6:
ax_anim 2, 0, 127, 4, 4, 4, 4,
ax_anim 8, 0, 127, 5, 5, 5, 5,
ax_anim_terminator
sCleffaAnims_7_7:
ax_anim 2, 0, 128, 4, 0, 4, 0,
ax_anim 8, 0, 128, 5, 0, 5, 0,
ax_anim_terminator
sCleffaAnims_7_8:
ax_anim 2, 0, 129, 4, -4, 4, -4,
ax_anim 8, 0, 129, 5, -5, 5, -5,
ax_anim_terminator
.align 2
sCleffaAnims_8_1:
ax_anim 36, 0, 130, 0, 0, 0, 0,
ax_anim 18, 0, 131, 0, 0, 0, 0,
ax_anim_terminator
sCleffaAnims_8_2:
ax_anim 36, 0, 132, 0, 0, 0, 0,
ax_anim 18, 0, 133, 0, 0, 0, 0,
ax_anim_terminator
sCleffaAnims_8_3:
ax_anim 36, 0, 134, 0, 0, 0, 0,
ax_anim 18, 0, 135, 0, 0, 0, 0,
ax_anim_terminator
sCleffaAnims_8_4:
ax_anim 36, 0, 136, 0, 0, 0, 0,
ax_anim 18, 0, 137, 0, 0, 0, 0,
ax_anim_terminator
sCleffaAnims_8_5:
ax_anim 36, 0, 138, 0, 0, 0, 0,
ax_anim 18, 0, 139, 0, 0, 0, 0,
ax_anim_terminator
sCleffaAnims_8_6:
ax_anim 36, 0, 140, 0, 0, 0, 0,
ax_anim 18, 0, 141, 0, 0, 0, 0,
ax_anim_terminator
sCleffaAnims_8_7:
ax_anim 36, 0, 142, 0, 0, 0, 0,
ax_anim 18, 0, 143, 0, 0, 0, 0,
ax_anim_terminator
sCleffaAnims_8_8:
ax_anim 36, 0, 144, 0, 0, 0, 0,
ax_anim 18, 0, 145, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sCleffaAnims_9_1:
ax_anim 2, 0, 146, 0, 0, 0, 0,
ax_anim 1, 0, 147, 7, 3, 7, 3,
ax_anim 2, 0, 148, 10, 9, 10, 9,
ax_anim 2, 0, 149, 8, 19, 8, 19,
ax_anim 3, 0, 150, 0, 21, 0, 21,
ax_anim 2, 3, 151, -8, 19, -8, 19,
ax_anim 2, 0, 152, -10, 9, -10, 9,
ax_anim 1, 0, 153, -7, 3, -7, 3,
ax_anim 1, 0, 146, 0, 0, 0, 0,
ax_anim_terminator
sCleffaAnims_9_2:
ax_anim 2, 0, 153, 0, 0, 0, 0,
ax_anim 1, 0, 146, 9, 1, 9, 1,
ax_anim 2, 0, 147, 17, 4, 17, 4,
ax_anim 2, 0, 148, 22, 14, 22, 14,
ax_anim 3, 0, 149, 21, 21, 21, 21,
ax_anim 2, 3, 150, 11, 21, 11, 21,
ax_anim 2, 0, 151, 3, 15, 3, 15,
ax_anim 1, 0, 152, 0, 7, 0, 7,
ax_anim 1, 0, 153, 0, 0, 0, 0,
ax_anim_terminator
sCleffaAnims_9_3:
ax_anim 2, 0, 152, 0, 0, 0, 0,
ax_anim 1, 0, 153, 3, -5, 3, -5,
ax_anim 2, 0, 146, 11, -6, 11, -6,
ax_anim 2, 0, 147, 18, -5, 18, -5,
ax_anim 3, 0, 148, 21, 0, 21, 0,
ax_anim 2, 3, 149, 18, 4, 18, 4,
ax_anim 2, 0, 150, 12, 5, 12, 5,
ax_anim 1, 0, 151, 4, 5, 4, 5,
ax_anim 1, 0, 152, 0, 0, 0, 0,
ax_anim_terminator
sCleffaAnims_9_4:
ax_anim 2, 0, 151, 0, 0, 0, 0,
ax_anim 1, 0, 152, -1, -8, -1, -8,
ax_anim 2, 0, 153, 3, -16, 3, -16,
ax_anim 2, 0, 146, 12, -22, 12, -22,
ax_anim 3, 0, 147, 21, -22, 21, -22,
ax_anim 2, 3, 148, 22, -14, 22, -14,
ax_anim 2, 0, 149, 17, -4, 17, -4,
ax_anim 1, 0, 150, 7, -1, 7, -1,
ax_anim 1, 0, 151, 0, 0, 0, 0,
ax_anim_terminator
sCleffaAnims_9_5:
ax_anim 2, 0, 150, 0, 0, 0, 0,
ax_anim 1, 0, 151, -8, -4, -8, -4,
ax_anim 2, 0, 152, -9, -12, -9, -12,
ax_anim 2, 0, 153, -8, -19, -8, -19,
ax_anim 3, 0, 146, 0, -22, 0, -22,
ax_anim 2, 3, 147, 9, -19, 9, -19,
ax_anim 2, 0, 148, 11, -10, 11, -10,
ax_anim 1, 0, 149, 8, -4, 8, -4,
ax_anim 1, 0, 150, 0, 0, 0, 0,
ax_anim_terminator
sCleffaAnims_9_6:
ax_anim 2, 0, 149, 0, 0, 0, 0,
ax_anim 1, 0, 148, 1, -8, 1, -8,
ax_anim 2, 0, 147, -3, -16, -3, -16,
ax_anim 2, 0, 146, -12, -22, -12, -22,
ax_anim 3, 0, 153, -21, -22, -21, -22,
ax_anim 2, 3, 152, -22, -14, -22, -14,
ax_anim 2, 0, 151, -17, -4, -17, -4,
ax_anim 1, 0, 150, -7, -1, -7, -1,
ax_anim 1, 0, 149, 0, 0, 0, 0,
ax_anim_terminator
sCleffaAnims_9_7:
ax_anim 2, 0, 148, 0, 0, 0, 0,
ax_anim 1, 0, 147, -3, -5, -3, -5,
ax_anim 2, 0, 146, -11, -6, -11, -6,
ax_anim 2, 0, 153, -18, -5, -18, -5,
ax_anim 3, 0, 152, -21, 0, -21, 0,
ax_anim 2, 3, 151, -18, 4, -18, 4,
ax_anim 2, 0, 150, -12, 5, -12, 5,
ax_anim 1, 0, 149, -4, 5, -4, 5,
ax_anim 1, 0, 148, 0, 0, 0, 0,
ax_anim_terminator
sCleffaAnims_9_8:
ax_anim 2, 0, 147, 0, 0, 0, 0,
ax_anim 1, 0, 146, -9, 1, -9, 1,
ax_anim 2, 0, 153, -17, 4, -17, 4,
ax_anim 2, 0, 152, -22, 14, -22, 14,
ax_anim 3, 0, 151, -21, 21, -21, 21,
ax_anim 2, 3, 150, -11, 21, -11, 21,
ax_anim 2, 0, 149, -3, 15, -3, 15,
ax_anim 1, 0, 148, 0, 7, 0, 7,
ax_anim 1, 0, 147, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sCleffaAnims_10_1:
ax_anim 2, 0, 154, 0, 0, 0, 0,
ax_anim 2, 0, 154, 6, 0, 6, 0,
ax_anim 2, 0, 154, -6, 0, -6, 0,
ax_anim 2, 0, 154, 10, 0, 10, 0,
ax_anim 2, 0, 154, -10, 0, -10, 0,
ax_anim 2, 0, 154, 12, 0, 12, 0,
ax_anim 3, 0, 154, -12, 0, -12, 0,
ax_anim 3, 0, 154, 13, 0, 13, 0,
ax_anim 3, 0, 154, -13, 0, -13, 0,
ax_anim 2, 0, 154, 12, 0, 12, 0,
ax_anim 3, 0, 154, -12, 0, -12, 0,
ax_anim 2, 0, 154, 10, 0, 10, 0,
ax_anim 2, 0, 154, -10, 0, -10, 0,
ax_anim 2, 0, 154, 6, 0, 6, 0,
ax_anim 2, 0, 154, -6, 0, -6, 0,
ax_anim 2, 0, 154, 0, 0, 0, 0,
ax_anim_terminator
sCleffaAnims_10_2:
ax_anim 2, 0, 155, 0, 0, 0, 0,
ax_anim 2, 0, 155, 6, -6, 6, -6,
ax_anim 2, 0, 155, -6, 6, -6, 6,
ax_anim 2, 0, 155, 10, -10, 10, -10,
ax_anim 2, 0, 155, -10, 10, -10, 10,
ax_anim 2, 0, 155, 12, -12, 12, -12,
ax_anim 3, 0, 155, -12, 12, -12, 12,
ax_anim 3, 0, 155, 13, -13, 13, -13,
ax_anim 3, 0, 155, -13, 13, -13, 13,
ax_anim 2, 0, 155, 12, -12, 12, -12,
ax_anim 3, 0, 155, -12, 12, -12, 12,
ax_anim 2, 0, 155, 10, -10, 10, -10,
ax_anim 2, 0, 155, -10, 10, -10, 10,
ax_anim 2, 0, 155, 6, -6, 6, -6,
ax_anim 2, 0, 155, -6, 6, -6, 6,
ax_anim 2, 0, 155, 0, 0, 0, 0,
ax_anim_terminator
sCleffaAnims_10_3:
ax_anim 2, 0, 156, 0, 0, 0, 0,
ax_anim 2, 0, 156, 0, -6, 0, -6,
ax_anim 2, 0, 156, 0, 6, 0, 6,
ax_anim 2, 0, 156, 0, -10, 0, -10,
ax_anim 2, 0, 156, 0, 10, 0, 10,
ax_anim 2, 0, 156, 0, -12, 0, -12,
ax_anim 3, 0, 156, 0, 12, 0, 12,
ax_anim 3, 0, 156, 0, -13, 0, -13,
ax_anim 3, 0, 156, 0, 13, 0, 13,
ax_anim 2, 0, 156, 0, -12, 0, -12,
ax_anim 3, 0, 156, 0, 12, 0, 12,
ax_anim 2, 0, 156, 0, -10, 0, -10,
ax_anim 2, 0, 156, 0, 10, 0, 10,
ax_anim 2, 0, 156, 0, -6, 0, -6,
ax_anim 2, 0, 156, 0, 6, 0, 6,
ax_anim 2, 0, 156, 0, 0, 0, 0,
ax_anim_terminator
sCleffaAnims_10_4:
ax_anim 2, 0, 157, 0, 0, 0, 0,
ax_anim 2, 0, 157, -6, -6, -6, -6,
ax_anim 2, 0, 157, 6, 6, 6, 6,
ax_anim 2, 0, 157, -10, -10, -10, -10,
ax_anim 2, 0, 157, 10, 10, 10, 10,
ax_anim 2, 0, 157, -12, -12, -12, -12,
ax_anim 3, 0, 157, 12, 12, 12, 12,
ax_anim 3, 0, 157, -13, -13, -13, -13,
ax_anim 3, 0, 157, 13, 13, 13, 13,
ax_anim 2, 0, 157, -12, -12, -12, -12,
ax_anim 3, 0, 157, 12, 12, 12, 12,
ax_anim 2, 0, 157, -10, -10, -10, -10,
ax_anim 2, 0, 157, 10, 10, 10, 10,
ax_anim 2, 0, 157, -6, -6, -6, -6,
ax_anim 2, 0, 157, 6, 6, 6, 6,
ax_anim 2, 0, 157, 0, 0, 0, 0,
ax_anim_terminator
sCleffaAnims_10_5:
ax_anim 2, 0, 158, 0, 0, 0, 0,
ax_anim 2, 0, 158, 6, 0, 6, 0,
ax_anim 2, 0, 158, -6, 0, -6, 0,
ax_anim 2, 0, 158, 10, 0, 10, 0,
ax_anim 2, 0, 158, -10, 0, -10, 0,
ax_anim 2, 0, 158, 12, 0, 12, 0,
ax_anim 3, 0, 158, -12, 0, -12, 0,
ax_anim 3, 0, 158, 13, 0, 13, 0,
ax_anim 3, 0, 158, -13, 0, -13, 0,
ax_anim 2, 0, 158, 12, 0, 12, 0,
ax_anim 3, 0, 158, -12, 0, -12, 0,
ax_anim 2, 0, 158, 10, 0, 10, 0,
ax_anim 2, 0, 158, -10, 0, -10, 0,
ax_anim 2, 0, 158, 6, 0, 6, 0,
ax_anim 2, 0, 158, -6, 0, -6, 0,
ax_anim 2, 0, 158, 0, 0, 0, 0,
ax_anim_terminator
sCleffaAnims_10_6:
ax_anim 2, 0, 159, 0, 0, 0, 0,
ax_anim 2, 0, 159, 6, -6, 6, -6,
ax_anim 2, 0, 159, -6, 6, -6, 6,
ax_anim 2, 0, 159, 10, -10, 10, -10,
ax_anim 2, 0, 159, -10, 10, -10, 10,
ax_anim 2, 0, 159, 12, -12, 12, -12,
ax_anim 3, 0, 159, -12, 12, -12, 12,
ax_anim 3, 0, 159, 13, -13, 13, -13,
ax_anim 3, 0, 159, -13, 13, -13, 13,
ax_anim 2, 0, 159, 12, -12, 12, -12,
ax_anim 3, 0, 159, -12, 12, -12, 12,
ax_anim 2, 0, 159, 10, -10, 10, -10,
ax_anim 2, 0, 159, -10, 10, -10, 10,
ax_anim 2, 0, 159, 6, -6, 6, -6,
ax_anim 2, 0, 159, -6, 6, -6, 6,
ax_anim 2, 0, 159, 0, 0, 0, 0,
ax_anim_terminator
sCleffaAnims_10_7:
ax_anim 2, 0, 160, 0, 0, 0, 0,
ax_anim 2, 0, 160, 0, -6, 0, -6,
ax_anim 2, 0, 160, 0, 6, 0, 6,
ax_anim 2, 0, 160, 0, -10, 0, -10,
ax_anim 2, 0, 160, 0, 10, 0, 10,
ax_anim 2, 0, 160, 0, -12, 0, -12,
ax_anim 3, 0, 160, 0, 12, 0, 12,
ax_anim 3, 0, 160, 0, -13, 0, -13,
ax_anim 3, 0, 160, 0, 13, 0, 13,
ax_anim 2, 0, 160, 0, -12, 0, -12,
ax_anim 3, 0, 160, 0, 12, 0, 12,
ax_anim 2, 0, 160, 0, -10, 0, -10,
ax_anim 2, 0, 160, 0, 10, 0, 10,
ax_anim 2, 0, 160, 0, -6, 0, -6,
ax_anim 2, 0, 160, 0, 6, 0, 6,
ax_anim 2, 0, 160, 0, 0, 0, 0,
ax_anim_terminator
sCleffaAnims_10_8:
ax_anim 2, 0, 161, 0, 0, 0, 0,
ax_anim 2, 0, 161, -6, -6, -6, -6,
ax_anim 2, 0, 161, 6, 6, 6, 6,
ax_anim 2, 0, 161, -10, -10, -10, -10,
ax_anim 2, 0, 161, 10, 10, 10, 10,
ax_anim 2, 0, 161, -12, -12, -12, -12,
ax_anim 3, 0, 161, 12, 12, 12, 12,
ax_anim 3, 0, 161, -13, -13, -13, -13,
ax_anim 3, 0, 161, 13, 13, 13, 13,
ax_anim 2, 0, 161, -12, -12, -12, -12,
ax_anim 3, 0, 161, 12, 12, 12, 12,
ax_anim 2, 0, 161, -10, -10, -10, -10,
ax_anim 2, 0, 161, 10, 10, 10, 10,
ax_anim 2, 0, 161, -6, -6, -6, -6,
ax_anim 2, 0, 161, 6, 6, 6, 6,
ax_anim 2, 0, 161, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sCleffaAnims_11_1:
ax_anim 2, 0, 162, 0, 0, 0, 0,
ax_anim 1, 0, 163, 0, -10, 0, 0,
ax_anim 2, 0, 163, 0, -16, 0, 0,
ax_anim 3, 0, 163, 0, -20, 0, 0,
ax_anim 4, 0, 163, 0, -21, 0, 0,
ax_anim 4, 0, 162, 0, -24, 0, 0,
ax_anim 3, 0, 164, 0, -23, 0, 0,
ax_anim 2, 0, 164, 0, -18, 0, 0,
ax_anim 1, 0, 164, 0, -12, 0, 0,
ax_anim 2, 2, 162, 0, 0, 0, 0,
ax_anim_terminator
sCleffaAnims_11_2:
ax_anim 2, 0, 165, 0, 0, 0, 0,
ax_anim 1, 0, 166, 0, -10, 0, 0,
ax_anim 2, 0, 166, 0, -16, 0, 0,
ax_anim 3, 0, 166, 0, -20, 0, 0,
ax_anim 4, 0, 166, 0, -21, 0, 0,
ax_anim 4, 0, 165, 0, -23, 0, 0,
ax_anim 3, 0, 167, 0, -22, 0, 0,
ax_anim 2, 0, 167, 0, -18, 0, 0,
ax_anim 1, 0, 167, 0, -12, 0, 0,
ax_anim 2, 2, 165, 0, 0, 0, 0,
ax_anim_terminator
sCleffaAnims_11_3:
ax_anim 2, 0, 168, 0, 0, 0, 0,
ax_anim 1, 0, 169, 0, -10, 0, 0,
ax_anim 2, 0, 169, 0, -16, 0, 0,
ax_anim 3, 0, 169, 0, -20, 0, 0,
ax_anim 4, 0, 169, 0, -21, 0, 0,
ax_anim 4, 0, 168, 0, -24, 0, 0,
ax_anim 3, 0, 170, 0, -23, 0, 0,
ax_anim 2, 0, 170, 0, -20, 0, 0,
ax_anim 1, 0, 170, 0, -12, 0, 0,
ax_anim 2, 2, 168, 0, 0, 0, 0,
ax_anim_terminator
sCleffaAnims_11_4:
ax_anim 2, 0, 171, 0, 0, 0, 0,
ax_anim 1, 0, 172, 0, -10, 0, 0,
ax_anim 2, 0, 172, 0, -16, 0, 0,
ax_anim 3, 0, 172, 0, -20, 0, 0,
ax_anim 4, 0, 172, 0, -21, 0, 0,
ax_anim 4, 0, 172, 0, -22, 0, 0,
ax_anim 3, 0, 173, 0, -23, 0, 0,
ax_anim 2, 0, 173, 0, -19, 0, 0,
ax_anim 1, 0, 173, 0, -11, 0, 0,
ax_anim 2, 2, 171, 0, 0, 0, 0,
ax_anim_terminator
sCleffaAnims_11_5:
ax_anim 2, 0, 174, 0, 0, 0, 0,
ax_anim 1, 0, 175, 0, -10, 0, 0,
ax_anim 2, 0, 175, 0, -16, 0, 0,
ax_anim 3, 0, 175, 0, -20, 0, 0,
ax_anim 4, 0, 175, 0, -21, 0, 0,
ax_anim 4, 0, 175, 0, -23, 0, 0,
ax_anim 3, 0, 176, 0, -22, 0, 0,
ax_anim 2, 0, 176, 0, -18, 0, 0,
ax_anim 1, 0, 176, 0, -12, 0, 0,
ax_anim 2, 2, 174, 0, 0, 0, 0,
ax_anim_terminator
sCleffaAnims_11_6:
ax_anim 2, 0, 177, 0, 0, 0, 0,
ax_anim 1, 0, 178, 0, -10, 0, 0,
ax_anim 2, 0, 178, 0, -16, 0, 0,
ax_anim 3, 0, 178, 0, -20, 0, 0,
ax_anim 4, 0, 178, 0, -21, 0, 0,
ax_anim 4, 0, 178, 0, -22, 0, 0,
ax_anim 3, 0, 179, 0, -23, 0, 0,
ax_anim 2, 0, 179, 0, -19, 0, 0,
ax_anim 1, 0, 179, 0, -11, 0, 0,
ax_anim 2, 2, 177, 0, 0, 0, 0,
ax_anim_terminator
sCleffaAnims_11_7:
ax_anim 2, 0, 180, 0, 0, 0, 0,
ax_anim 1, 0, 181, 0, -10, 0, 0,
ax_anim 2, 0, 181, 0, -16, 0, 0,
ax_anim 3, 0, 181, 0, -20, 0, 0,
ax_anim 4, 0, 181, 0, -21, 0, 0,
ax_anim 4, 0, 180, 0, -24, 0, 0,
ax_anim 3, 0, 182, 0, -23, 0, 0,
ax_anim 2, 0, 182, 0, -20, 0, 0,
ax_anim 1, 0, 182, 0, -12, 0, 0,
ax_anim 2, 2, 180, 0, 0, 0, 0,
ax_anim_terminator
sCleffaAnims_11_8:
ax_anim 2, 0, 183, 0, 0, 0, 0,
ax_anim 1, 0, 184, 0, -10, 0, 0,
ax_anim 2, 0, 184, 0, -16, 0, 0,
ax_anim 3, 0, 184, 0, -20, 0, 0,
ax_anim 4, 0, 184, 0, -21, 0, 0,
ax_anim 4, 0, 183, 0, -23, 0, 0,
ax_anim 3, 0, 185, 0, -22, 0, 0,
ax_anim 2, 0, 185, 0, -18, 0, 0,
ax_anim 1, 0, 185, 0, -12, 0, 0,
ax_anim 2, 2, 183, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sCleffaAnims_12_1:
ax_anim 2, 0, 186, 1, 0, 1, 0,
ax_anim 2, 0, 186, 0, 0, 0, 0,
ax_anim 2, 0, 186, 1, 0, 1, 0,
ax_anim 2, 0, 186, 0, 0, 0, 0,
ax_anim 2, 0, 186, 1, 0, 1, 0,
ax_anim 2, 2, 186, 0, 0, 0, 0,
ax_anim 2, 0, 186, 1, 0, 1, 0,
ax_anim 2, 0, 186, 0, 0, 0, 0,
ax_anim 2, 0, 186, 1, 0, 1, 0,
ax_anim 2, 1, 186, 0, 0, 0, 0,
ax_anim_terminator
sCleffaAnims_12_2:
ax_anim 2, 0, 193, 1, -1, 1, -1,
ax_anim 2, 0, 193, 0, 0, 0, 0,
ax_anim 2, 0, 193, 1, -1, 1, -1,
ax_anim 2, 0, 193, 0, 0, 0, 0,
ax_anim 2, 0, 193, 1, -1, 1, -1,
ax_anim 2, 2, 193, 0, 0, 0, 0,
ax_anim 2, 0, 193, 1, -1, 1, -1,
ax_anim 2, 0, 193, 0, 0, 0, 0,
ax_anim 2, 0, 193, 1, -1, 1, -1,
ax_anim 2, 1, 193, 0, 0, 0, 0,
ax_anim_terminator
sCleffaAnims_12_3:
ax_anim 2, 0, 192, 0, -1, 0, -1,
ax_anim 2, 0, 192, 0, 0, 0, 0,
ax_anim 2, 0, 192, 0, -1, 0, -1,
ax_anim 2, 0, 192, 0, 0, 0, 0,
ax_anim 2, 0, 192, 0, -1, 0, -1,
ax_anim 2, 2, 192, 0, 0, 0, 0,
ax_anim 2, 0, 192, 0, -1, 0, -1,
ax_anim 2, 0, 192, 0, 0, 0, 0,
ax_anim 2, 0, 192, 0, -1, 0, -1,
ax_anim 2, 1, 192, 0, 0, 0, 0,
ax_anim_terminator
sCleffaAnims_12_4:
ax_anim 2, 0, 191, -1, -1, -1, -1,
ax_anim 2, 0, 191, 0, 0, 0, 0,
ax_anim 2, 0, 191, -1, -1, -1, -1,
ax_anim 2, 0, 191, 0, 0, 0, 0,
ax_anim 2, 0, 191, -1, -1, -1, -1,
ax_anim 2, 2, 191, 0, 0, 0, 0,
ax_anim 2, 0, 191, -1, -1, -1, -1,
ax_anim 2, 0, 191, 0, 0, 0, 0,
ax_anim 2, 0, 191, -1, -1, -1, -1,
ax_anim 2, 1, 191, 0, 0, 0, 0,
ax_anim_terminator
sCleffaAnims_12_5:
ax_anim 2, 0, 190, 1, 0, 1, 0,
ax_anim 2, 0, 190, 0, 0, 0, 0,
ax_anim 2, 0, 190, 1, 0, 1, 0,
ax_anim 2, 0, 190, 0, 0, 0, 0,
ax_anim 2, 0, 190, 1, 0, 1, 0,
ax_anim 2, 2, 190, 0, 0, 0, 0,
ax_anim 2, 0, 190, 1, 0, 1, 0,
ax_anim 2, 0, 190, 0, 0, 0, 0,
ax_anim 2, 0, 190, 1, 0, 1, 0,
ax_anim 2, 1, 190, 0, 0, 0, 0,
ax_anim_terminator
sCleffaAnims_12_6:
ax_anim 2, 0, 189, 1, -1, 1, -1,
ax_anim 2, 0, 189, 0, 0, 0, 0,
ax_anim 2, 0, 189, 1, -1, 1, -1,
ax_anim 2, 0, 189, 0, 0, 0, 0,
ax_anim 2, 0, 189, 1, -1, 1, -1,
ax_anim 2, 2, 189, 0, 0, 0, 0,
ax_anim 2, 0, 189, 1, -1, 1, -1,
ax_anim 2, 0, 189, 0, 0, 0, 0,
ax_anim 2, 0, 189, 1, -1, 1, -1,
ax_anim 2, 1, 189, 0, 0, 0, 0,
ax_anim_terminator
sCleffaAnims_12_7:
ax_anim 2, 0, 188, 0, -1, 0, -1,
ax_anim 2, 0, 188, 0, 0, 0, 0,
ax_anim 2, 0, 188, 0, -1, 0, -1,
ax_anim 2, 0, 188, 0, 0, 0, 0,
ax_anim 2, 0, 188, 0, -1, 0, -1,
ax_anim 2, 2, 188, 0, 0, 0, 0,
ax_anim 2, 0, 188, 0, -1, 0, -1,
ax_anim 2, 0, 188, 0, 0, 0, 0,
ax_anim 2, 0, 188, 0, -1, 0, -1,
ax_anim 2, 1, 188, 0, 0, 0, 0,
ax_anim_terminator
sCleffaAnims_12_8:
ax_anim 2, 0, 187, -1, -1, -1, -1,
ax_anim 2, 0, 187, 0, 0, 0, 0,
ax_anim 2, 0, 187, -1, -1, -1, -1,
ax_anim 2, 0, 187, 0, 0, 0, 0,
ax_anim 2, 0, 187, -1, -1, -1, -1,
ax_anim 2, 2, 187, 0, 0, 0, 0,
ax_anim 2, 0, 187, -1, -1, -1, -1,
ax_anim 2, 0, 187, 0, 0, 0, 0,
ax_anim 2, 0, 187, -1, -1, -1, -1,
ax_anim 2, 1, 187, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sCleffaAnims_13_1:
ax_anim 2, 0, 194, 0, 0, 0, 0,
ax_anim 2, 0, 195, 0, 0, 0, 0,
ax_anim 2, 0, 196, 0, 0, 0, 0,
ax_anim 2, 0, 197, 0, 0, 0, 0,
ax_anim 2, 0, 198, 0, 0, 0, 0,
ax_anim 2, 0, 199, 0, 0, 0, 0,
ax_anim 2, 0, 200, 0, 0, 0, 0,
ax_anim 2, 0, 201, 0, 0, 0, 0,
ax_anim 2, 2, 194, 0, 0, 0, 0,
ax_anim_terminator
sCleffaAnims_13_2:
ax_anim 2, 0, 201, 0, 0, 0, 0,
ax_anim 2, 0, 194, 0, 0, 0, 0,
ax_anim 2, 0, 195, 0, 0, 0, 0,
ax_anim 2, 0, 196, 0, 0, 0, 0,
ax_anim 2, 0, 197, 0, 0, 0, 0,
ax_anim 2, 0, 198, 0, 0, 0, 0,
ax_anim 2, 0, 199, 0, 0, 0, 0,
ax_anim 2, 0, 200, 0, 0, 0, 0,
ax_anim 2, 2, 201, 0, 0, 0, 0,
ax_anim_terminator
sCleffaAnims_13_3:
ax_anim 2, 0, 200, 0, 0, 0, 0,
ax_anim 2, 0, 201, 0, 0, 0, 0,
ax_anim 2, 0, 194, 0, 0, 0, 0,
ax_anim 2, 0, 195, 0, 0, 0, 0,
ax_anim 2, 0, 196, 0, 0, 0, 0,
ax_anim 2, 0, 197, 0, 0, 0, 0,
ax_anim 2, 0, 198, 0, 0, 0, 0,
ax_anim 2, 0, 199, 0, 0, 0, 0,
ax_anim 2, 2, 200, 0, 0, 0, 0,
ax_anim_terminator
sCleffaAnims_13_4:
ax_anim 2, 0, 199, 0, 0, 0, 0,
ax_anim 2, 0, 200, 0, 0, 0, 0,
ax_anim 2, 0, 201, 0, 0, 0, 0,
ax_anim 2, 0, 194, 0, 0, 0, 0,
ax_anim 2, 0, 195, 0, 0, 0, 0,
ax_anim 2, 0, 196, 0, 0, 0, 0,
ax_anim 2, 0, 197, 0, 0, 0, 0,
ax_anim 2, 0, 198, 0, 0, 0, 0,
ax_anim 2, 2, 199, 0, 0, 0, 0,
ax_anim_terminator
sCleffaAnims_13_5:
ax_anim 2, 0, 198, 0, 0, 0, 0,
ax_anim 2, 0, 199, 0, 0, 0, 0,
ax_anim 2, 0, 200, 0, 0, 0, 0,
ax_anim 2, 0, 201, 0, 0, 0, 0,
ax_anim 2, 0, 194, 0, 0, 0, 0,
ax_anim 2, 0, 195, 0, 0, 0, 0,
ax_anim 2, 0, 196, 0, 0, 0, 0,
ax_anim 2, 0, 197, 0, 0, 0, 0,
ax_anim 2, 2, 198, 0, 0, 0, 0,
ax_anim_terminator
sCleffaAnims_13_6:
ax_anim 2, 0, 197, 0, 0, 0, 0,
ax_anim 2, 0, 198, 0, 0, 0, 0,
ax_anim 2, 0, 199, 0, 0, 0, 0,
ax_anim 2, 0, 200, 0, 0, 0, 0,
ax_anim 2, 0, 201, 0, 0, 0, 0,
ax_anim 2, 0, 194, 0, 0, 0, 0,
ax_anim 2, 0, 195, 0, 0, 0, 0,
ax_anim 2, 0, 196, 0, 0, 0, 0,
ax_anim 2, 2, 197, 0, 0, 0, 0,
ax_anim_terminator
sCleffaAnims_13_7:
ax_anim 2, 0, 196, 0, 0, 0, 0,
ax_anim 2, 0, 197, 0, 0, 0, 0,
ax_anim 2, 0, 198, 0, 0, 0, 0,
ax_anim 2, 0, 199, 0, 0, 0, 0,
ax_anim 2, 0, 200, 0, 0, 0, 0,
ax_anim 2, 0, 201, 0, 0, 0, 0,
ax_anim 2, 0, 194, 0, 0, 0, 0,
ax_anim 2, 0, 195, 0, 0, 0, 0,
ax_anim 2, 2, 196, 0, 0, 0, 0,
ax_anim_terminator
sCleffaAnims_13_8:
ax_anim 2, 0, 195, 0, 0, 0, 0,
ax_anim 2, 0, 196, 0, 0, 0, 0,
ax_anim 2, 0, 197, 0, 0, 0, 0,
ax_anim 2, 0, 198, 0, 0, 0, 0,
ax_anim 2, 0, 199, 0, 0, 0, 0,
ax_anim 2, 0, 200, 0, 0, 0, 0,
ax_anim 2, 0, 201, 0, 0, 0, 0,
ax_anim 2, 0, 194, 0, 0, 0, 0,
ax_anim 2, 2, 195, 0, 0, 0, 0,
ax_anim_terminator
sCleffaGfx1:
.incbin "baserom.gba", 0xC8E31C, 0x200
sCleffaSprites1:
ax_sprite sCleffaGfx1, 0x200
ax_sprite_terminator
sCleffaGfx2:
.incbin "baserom.gba", 0xC8E52C, 0x200
sCleffaSprites2:
ax_sprite sCleffaGfx2, 0x200
ax_sprite_terminator
sCleffaGfx3:
.incbin "baserom.gba", 0xC8E73C, 0x200
sCleffaSprites3:
ax_sprite sCleffaGfx3, 0x200
ax_sprite_terminator
sCleffaGfx4:
.incbin "baserom.gba", 0xC8E94C, 0x200
sCleffaSprites4:
ax_sprite sCleffaGfx4, 0x200
ax_sprite_terminator
sCleffaGfx5:
.incbin "baserom.gba", 0xC8EB5C, 0x200
sCleffaSprites5:
ax_sprite sCleffaGfx5, 0x200
ax_sprite_terminator
sCleffaGfx6:
.incbin "baserom.gba", 0xC8ED6C, 0x200
sCleffaSprites6:
ax_sprite sCleffaGfx6, 0x200
ax_sprite_terminator
sCleffaGfx7:
.incbin "baserom.gba", 0xC8EF7C, 0x200
sCleffaSprites7:
ax_sprite sCleffaGfx7, 0x200
ax_sprite_terminator
sCleffaGfx8:
.incbin "baserom.gba", 0xC8F18C, 0x200
sCleffaSprites8:
ax_sprite sCleffaGfx8, 0x200
ax_sprite_terminator
sCleffaGfx9:
.incbin "baserom.gba", 0xC8F39C, 0x200
sCleffaSprites9:
ax_sprite sCleffaGfx9, 0x200
ax_sprite_terminator
sCleffaGfx10:
.incbin "baserom.gba", 0xC8F5AC, 0x200
sCleffaSprites10:
ax_sprite sCleffaGfx10, 0x200
ax_sprite_terminator
sCleffaGfx11:
.incbin "baserom.gba", 0xC8F7BC, 0x200
sCleffaSprites11:
ax_sprite sCleffaGfx11, 0x200
ax_sprite_terminator
sCleffaGfx12:
.incbin "baserom.gba", 0xC8F9CC, 0x200
sCleffaSprites12:
ax_sprite sCleffaGfx12, 0x200
ax_sprite_terminator
sCleffaGfx13:
.incbin "baserom.gba", 0xC8FBDC, 0x200
sCleffaSprites13:
ax_sprite sCleffaGfx13, 0x200
ax_sprite_terminator
sCleffaGfx14:
.incbin "baserom.gba", 0xC8FDEC, 0x200
sCleffaSprites14:
ax_sprite sCleffaGfx14, 0x200
ax_sprite_terminator
sCleffaGfx15:
.incbin "baserom.gba", 0xC8FFFC, 0x200
sCleffaSprites15:
ax_sprite sCleffaGfx15, 0x200
ax_sprite_terminator
sCleffaGfx16:
.incbin "baserom.gba", 0xC9020C, 0x60
sCleffaGfx16_1:
.incbin "baserom.gba", 0xC9026C, 0x60
sCleffaGfx16_2:
.incbin "baserom.gba", 0xC902CC, 0x60
sCleffaSprites16:
ax_sprite sCleffaGfx16, 0x60
ax_sprite 0, 0x20
ax_sprite sCleffaGfx16_1, 0x60
ax_sprite 0, 0x20
ax_sprite sCleffaGfx16_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sCleffaGfx17:
.incbin "baserom.gba", 0xC90364, 0x60
sCleffaGfx17_1:
.incbin "baserom.gba", 0xC903C4, 0x60
sCleffaGfx17_2:
.incbin "baserom.gba", 0xC90424, 0x60
sCleffaSprites17:
ax_sprite sCleffaGfx17, 0x60
ax_sprite 0, 0x20
ax_sprite sCleffaGfx17_1, 0x60
ax_sprite 0, 0x20
ax_sprite sCleffaGfx17_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sCleffaGfx18:
.incbin "baserom.gba", 0xC904BC, 0x60
sCleffaGfx18_1:
.incbin "baserom.gba", 0xC9051C, 0x60
sCleffaGfx18_2:
.incbin "baserom.gba", 0xC9057C, 0x60
sCleffaSprites18:
ax_sprite sCleffaGfx18, 0x60
ax_sprite 0, 0x20
ax_sprite sCleffaGfx18_1, 0x60
ax_sprite 0, 0x20
ax_sprite sCleffaGfx18_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sCleffaGfx19:
.incbin "baserom.gba", 0xC90614, 0x40
sCleffaGfx19_1:
.incbin "baserom.gba", 0xC90654, 0x60
sCleffaGfx19_2:
.incbin "baserom.gba", 0xC906B4, 0x60
sCleffaSprites19:
ax_sprite sCleffaGfx19, 0x40
ax_sprite 0, 0x40
ax_sprite sCleffaGfx19_1, 0x60
ax_sprite 0, 0x20
ax_sprite sCleffaGfx19_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sCleffaGfx20:
.incbin "baserom.gba", 0xC9074C, 0x60
sCleffaGfx20_1:
.incbin "baserom.gba", 0xC907AC, 0x60
sCleffaGfx20_2:
.incbin "baserom.gba", 0xC9080C, 0x60
sCleffaSprites20:
ax_sprite sCleffaGfx20, 0x60
ax_sprite 0, 0x20
ax_sprite sCleffaGfx20_1, 0x60
ax_sprite 0, 0x20
ax_sprite sCleffaGfx20_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sCleffaGfx21:
.incbin "baserom.gba", 0xC908A4, 0x40
sCleffaGfx21_1:
.incbin "baserom.gba", 0xC908E4, 0x60
sCleffaGfx21_2:
.incbin "baserom.gba", 0xC90944, 0x60
sCleffaSprites21:
ax_sprite sCleffaGfx21, 0x40
ax_sprite 0, 0x40
ax_sprite sCleffaGfx21_1, 0x60
ax_sprite 0, 0x20
ax_sprite sCleffaGfx21_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sCleffaGfx22:
.incbin "baserom.gba", 0xC909DC, 0x60
sCleffaGfx22_1:
.incbin "baserom.gba", 0xC90A3C, 0x60
sCleffaGfx22_2:
.incbin "baserom.gba", 0xC90A9C, 0x60
sCleffaSprites22:
ax_sprite sCleffaGfx22, 0x60
ax_sprite 0, 0x20
ax_sprite sCleffaGfx22_1, 0x60
ax_sprite 0, 0x20
ax_sprite sCleffaGfx22_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sCleffaGfx23:
.incbin "baserom.gba", 0xC90B34, 0x60
sCleffaGfx23_1:
.incbin "baserom.gba", 0xC90B94, 0x60
sCleffaGfx23_2:
.incbin "baserom.gba", 0xC90BF4, 0x60
sCleffaSprites23:
ax_sprite sCleffaGfx23, 0x60
ax_sprite 0, 0x20
ax_sprite sCleffaGfx23_1, 0x60
ax_sprite 0, 0x20
ax_sprite sCleffaGfx23_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sCleffaGfx24:
.incbin "baserom.gba", 0xC90C8C, 0x60
sCleffaGfx24_1:
.incbin "baserom.gba", 0xC90CEC, 0x60
sCleffaGfx24_2:
.incbin "baserom.gba", 0xC90D4C, 0x60
sCleffaSprites24:
ax_sprite sCleffaGfx24, 0x60
ax_sprite 0, 0x20
ax_sprite sCleffaGfx24_1, 0x60
ax_sprite 0, 0x20
ax_sprite sCleffaGfx24_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sCleffaGfx25:
.incbin "baserom.gba", 0xC90DE4, 0x60
sCleffaGfx25_1:
.incbin "baserom.gba", 0xC90E44, 0x60
sCleffaGfx25_2:
.incbin "baserom.gba", 0xC90EA4, 0x60
sCleffaSprites25:
ax_sprite sCleffaGfx25, 0x60
ax_sprite 0, 0x20
ax_sprite sCleffaGfx25_1, 0x60
ax_sprite 0, 0x20
ax_sprite sCleffaGfx25_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sCleffaGfx26:
.incbin "baserom.gba", 0xC90F3C, 0x200
sCleffaSprites26:
ax_sprite sCleffaGfx26, 0x200
ax_sprite_terminator
sCleffaGfx27:
.incbin "baserom.gba", 0xC9114C, 0x200
sCleffaSprites27:
ax_sprite sCleffaGfx27, 0x200
ax_sprite_terminator
sCleffaGfx28:
.incbin "baserom.gba", 0xC9135C, 0x200
sCleffaSprites28:
ax_sprite sCleffaGfx28, 0x200
ax_sprite_terminator
sCleffaGfx29:
.incbin "baserom.gba", 0xC9156C, 0x200
sCleffaSprites29:
ax_sprite sCleffaGfx29, 0x200
ax_sprite_terminator
sCleffaGfx30:
.incbin "baserom.gba", 0xC9177C, 0x200
sCleffaSprites30:
ax_sprite sCleffaGfx30, 0x200
ax_sprite_terminator
sCleffaGfx31:
.incbin "baserom.gba", 0xC9198C, 0x200
sCleffaSprites31:
ax_sprite sCleffaGfx31, 0x200
ax_sprite_terminator
sCleffaGfx32:
.incbin "baserom.gba", 0xC91B9C, 0x200
sCleffaSprites32:
ax_sprite sCleffaGfx32, 0x200
ax_sprite_terminator
sAxPosesCleffa:
.4byte sCleffaPose1
.4byte sCleffaPose2
.4byte sCleffaPose3
.4byte sCleffaPose4
.4byte sCleffaPose5
.4byte sCleffaPose6
.4byte sCleffaPose7
.4byte sCleffaPose8
.4byte sCleffaPose9
.4byte sCleffaPose10
.4byte sCleffaPose11
.4byte sCleffaPose12
.4byte sCleffaPose13
.4byte sCleffaPose14
.4byte sCleffaPose15
.4byte sCleffaPose16
.4byte sCleffaPose17
.4byte sCleffaPose18
.4byte sCleffaPose19
.4byte sCleffaPose20
.4byte sCleffaPose21
.4byte sCleffaPose22
.4byte sCleffaPose23
.4byte sCleffaPose24
.4byte sCleffaPose25
.4byte sCleffaPose26
.4byte sCleffaPose27
.4byte sCleffaPose28
.4byte sCleffaPose29
.4byte sCleffaPose30
.4byte sCleffaPose31
.4byte sCleffaPose32
.4byte sCleffaPose33
.4byte sCleffaPose34
.4byte sCleffaPose35
.4byte sCleffaPose36
.4byte sCleffaPose37
.4byte sCleffaPose38
.4byte sCleffaPose39
.4byte sCleffaPose40
.4byte sCleffaPose41
.4byte sCleffaPose42
.4byte sCleffaPose43
.4byte sCleffaPose44
.4byte sCleffaPose45
.4byte sCleffaPose46
.4byte sCleffaPose47
.4byte sCleffaPose48
.4byte sCleffaPose49
.4byte sCleffaPose50
.4byte sCleffaPose51
.4byte sCleffaPose52
.4byte sCleffaPose53
.4byte sCleffaPose54
.4byte sCleffaPose55
.4byte sCleffaPose56
.4byte sCleffaPose57
.4byte sCleffaPose58
.4byte sCleffaPose59
.4byte sCleffaPose60
.4byte sCleffaPose61
.4byte sCleffaPose62
.4byte sCleffaPose63
.4byte sCleffaPose64
.4byte sCleffaPose65
.4byte sCleffaPose66
.4byte sCleffaPose67
.4byte sCleffaPose68
.4byte sCleffaPose69
.4byte sCleffaPose70
.4byte sCleffaPose71
.4byte sCleffaPose72
.4byte sCleffaPose73
.4byte sCleffaPose74
.4byte sCleffaPose75
.4byte sCleffaPose76
.4byte sCleffaPose77
.4byte sCleffaPose78
.4byte sCleffaPose79
.4byte sCleffaPose80
.4byte sCleffaPose81
.4byte sCleffaPose82
.4byte sCleffaPose83
.4byte sCleffaPose84
.4byte sCleffaPose85
.4byte sCleffaPose86
.4byte sCleffaPose87
.4byte sCleffaPose88
.4byte sCleffaPose89
.4byte sCleffaPose90
.4byte sCleffaPose91
.4byte sCleffaPose92
.4byte sCleffaPose93
.4byte sCleffaPose94
.4byte sCleffaPose95
.4byte sCleffaPose96
.4byte sCleffaPose97
.4byte sCleffaPose98
.4byte sCleffaPose99
.4byte sCleffaPose100
.4byte sCleffaPose101
.4byte sCleffaPose102
.4byte sCleffaPose103
.4byte sCleffaPose104
.4byte sCleffaPose105
.4byte sCleffaPose106
.4byte sCleffaPose107
.4byte sCleffaPose108
.4byte sCleffaPose109
.4byte sCleffaPose110
.4byte sCleffaPose111
.4byte sCleffaPose112
.4byte sCleffaPose113
.4byte sCleffaPose114
.4byte sCleffaPose115
.4byte sCleffaPose116
.4byte sCleffaPose117
.4byte sCleffaPose118
.4byte sCleffaPose119
.4byte sCleffaPose120
.4byte sCleffaPose121
.4byte sCleffaPose122
.4byte sCleffaPose123
.4byte sCleffaPose124
.4byte sCleffaPose125
.4byte sCleffaPose126
.4byte sCleffaPose127
.4byte sCleffaPose128
.4byte sCleffaPose129
.4byte sCleffaPose130
.4byte sCleffaPose131
.4byte sCleffaPose132
.4byte sCleffaPose133
.4byte sCleffaPose134
.4byte sCleffaPose135
.4byte sCleffaPose136
.4byte sCleffaPose137
.4byte sCleffaPose138
.4byte sCleffaPose139
.4byte sCleffaPose140
.4byte sCleffaPose141
.4byte sCleffaPose142
.4byte sCleffaPose143
.4byte sCleffaPose144
.4byte sCleffaPose145
.4byte sCleffaPose146
.4byte sCleffaPose147
.4byte sCleffaPose148
.4byte sCleffaPose149
.4byte sCleffaPose150
.4byte sCleffaPose151
.4byte sCleffaPose152
.4byte sCleffaPose153
.4byte sCleffaPose154
.4byte sCleffaPose155
.4byte sCleffaPose156
.4byte sCleffaPose157
.4byte sCleffaPose158
.4byte sCleffaPose159
.4byte sCleffaPose160
.4byte sCleffaPose161
.4byte sCleffaPose162
.4byte sCleffaPose163
.4byte sCleffaPose164
.4byte sCleffaPose165
.4byte sCleffaPose166
.4byte sCleffaPose167
.4byte sCleffaPose168
.4byte sCleffaPose169
.4byte sCleffaPose170
.4byte sCleffaPose171
.4byte sCleffaPose172
.4byte sCleffaPose173
.4byte sCleffaPose174
.4byte sCleffaPose175
.4byte sCleffaPose176
.4byte sCleffaPose177
.4byte sCleffaPose178
.4byte sCleffaPose179
.4byte sCleffaPose180
.4byte sCleffaPose181
.4byte sCleffaPose182
.4byte sCleffaPose183
.4byte sCleffaPose184
.4byte sCleffaPose185
.4byte sCleffaPose186
.4byte sCleffaPose187
.4byte sCleffaPose188
.4byte sCleffaPose189
.4byte sCleffaPose190
.4byte sCleffaPose191
.4byte sCleffaPose192
.4byte sCleffaPose193
.4byte sCleffaPose194
.4byte sCleffaPose195
.4byte sCleffaPose196
.4byte sCleffaPose197
.4byte sCleffaPose198
.4byte sCleffaPose199
.4byte sCleffaPose200
.4byte sCleffaPose201
.4byte sCleffaPose202
sAxPositionsCleffa:
.2byte   -1,   -3, 	  -5,   -3, 	   3,   -3, 	  -1,   -5
.2byte    0,   -4, 	  -4,   -6, 	   4,   -4, 	   1,   -7
.2byte   -2,   -4, 	  -6,   -4, 	   2,   -6, 	  -3,   -7
.2byte    1,   -3, 	   5,   -4, 	  -3,   -3, 	  -1,   -5
.2byte    0,   -5, 	   4,   -7, 	  -4,   -4, 	  -2,   -7
.2byte    0,   -4, 	   4,   -4, 	  -4,   -6, 	  -1,   -7
.2byte    4,   -3, 	   3,   -7, 	   1,   -3, 	  -1,   -6
.2byte    4,   -4, 	  -1,  -11, 	   2,   -2, 	  -2,   -8
.2byte    4,   -6, 	   2,   -7, 	   1,   -6, 	  -1,   -8
.2byte    0,   -7, 	  -5,   -7, 	   3,   -4, 	  -1,   -7
.2byte    1,   -9, 	  -4,  -11, 	   5,   -4, 	  -1,   -8
.2byte   -2,   -9, 	  -6,   -7, 	   5,   -8, 	  -2,   -8
.2byte   -1,   -9, 	   3,   -5, 	  -5,   -5, 	  -1,   -6
.2byte   -4,  -10, 	   2,   -9, 	  -6,   -5, 	  -3,   -8
.2byte    2,  -10, 	   4,   -5, 	  -4,   -9, 	   1,   -8
.2byte   -2,   -7, 	   3,   -7, 	  -5,   -4, 	  -1,   -7
.2byte   -3,   -9, 	   2,  -11, 	  -7,   -4, 	  -1,   -8
.2byte    0,   -9, 	   4,   -7, 	  -7,   -8, 	   0,   -8
.2byte   -6,   -3, 	  -5,   -7, 	  -3,   -3, 	  -1,   -6
.2byte   -6,   -4, 	  -1,  -11, 	  -4,   -2, 	   0,   -8
.2byte   -6,   -6, 	  -4,   -7, 	  -3,   -6, 	  -1,   -8
.2byte   -2,   -3, 	  -6,   -4, 	   2,   -3, 	   0,   -5
.2byte   -1,   -5, 	  -5,   -7, 	   3,   -4, 	   1,   -7
.2byte   -2,   -4, 	  -6,   -4, 	   2,   -6, 	  -1,   -7
.2byte   -1,   -3, 	  -5,   -3, 	   3,   -3, 	  -1,   -5
.2byte   -1,   -5, 	  -8,   -5, 	   6,   -5, 	  -1,   -6
.2byte   -1,   -3, 	  -5,   -2, 	   3,   -2, 	  -1,   -4
.2byte    1,   -3, 	   5,   -4, 	  -3,   -3, 	  -1,   -5
.2byte    1,   -4, 	   6,   -5, 	  -4,   -4, 	  -1,   -7
.2byte    1,   -3, 	   5,   -5, 	  -3,   -3, 	  -1,   -6
.2byte    4,   -3, 	   3,   -7, 	   1,   -3, 	  -1,   -6
.2byte    4,   -5, 	   1,   -7, 	   0,   -5, 	  -1,   -7
.2byte    4,   -2, 	   2,   -4, 	   1,   -1, 	  -2,   -5
.2byte    0,   -7, 	  -5,   -7, 	   3,   -4, 	  -1,   -7
.2byte   -1,   -9, 	  -5,   -8, 	   4,   -5, 	  -1,   -8
.2byte   -1,   -7, 	  -4,   -5, 	   4,   -3, 	  -1,   -6
.2byte   -1,   -9, 	   3,   -5, 	  -5,   -5, 	  -1,   -6
.2byte   -1,  -11, 	   6,   -6, 	  -8,   -6, 	  -1,   -7
.2byte   -1,   -9, 	   5,   -3, 	  -7,   -3, 	  -1,   -6
.2byte   -2,   -7, 	   3,   -7, 	  -5,   -4, 	  -1,   -7
.2byte   -1,   -9, 	   3,   -8, 	  -6,   -5, 	  -1,   -8
.2byte   -1,   -7, 	   2,   -5, 	  -6,   -3, 	  -1,   -6
.2byte   -6,   -3, 	  -5,   -7, 	  -3,   -3, 	  -1,   -6
.2byte   -6,   -5, 	  -3,   -7, 	  -2,   -5, 	  -1,   -7
.2byte   -6,   -2, 	  -4,   -4, 	  -3,   -1, 	   0,   -5
.2byte   -3,   -3, 	  -7,   -4, 	   1,   -3, 	  -1,   -5
.2byte   -3,   -4, 	  -8,   -5, 	   2,   -4, 	  -1,   -7
.2byte   -3,   -3, 	  -7,   -5, 	   1,   -3, 	  -1,   -6
.2byte   -1,   -3, 	  -5,   -3, 	   3,   -3, 	  -1,   -5
.2byte   -1,   -5, 	  -8,   -5, 	   6,   -5, 	  -1,   -6
.2byte   -1,   -3, 	  -5,   -2, 	   3,   -2, 	  -1,   -4
.2byte    1,   -3, 	   5,   -4, 	  -3,   -3, 	  -1,   -5
.2byte    1,   -4, 	   6,   -5, 	  -4,   -4, 	  -1,   -7
.2byte    1,   -3, 	   5,   -5, 	  -3,   -3, 	  -1,   -6
.2byte    4,   -3, 	   3,   -7, 	   1,   -3, 	  -1,   -6
.2byte    4,   -5, 	   1,   -7, 	   0,   -5, 	  -1,   -7
.2byte    4,   -2, 	   2,   -4, 	   1,   -1, 	  -2,   -5
.2byte    0,   -7, 	  -5,   -7, 	   3,   -4, 	  -1,   -7
.2byte   -1,   -9, 	  -5,   -8, 	   4,   -5, 	  -1,   -8
.2byte   -1,   -7, 	  -4,   -5, 	   4,   -3, 	  -1,   -6
.2byte   -1,   -9, 	   3,   -5, 	  -5,   -5, 	  -1,   -6
.2byte   -1,  -11, 	   6,   -6, 	  -8,   -6, 	  -1,   -7
.2byte   -1,   -9, 	   5,   -3, 	  -7,   -3, 	  -1,   -6
.2byte   -2,   -7, 	   3,   -7, 	  -5,   -4, 	  -1,   -7
.2byte   -1,   -9, 	   3,   -8, 	  -6,   -5, 	  -1,   -8
.2byte   -1,   -7, 	   2,   -5, 	  -6,   -3, 	  -1,   -6
.2byte   -6,   -3, 	  -5,   -7, 	  -3,   -3, 	  -1,   -6
.2byte   -6,   -5, 	  -3,   -7, 	  -2,   -5, 	  -1,   -7
.2byte   -6,   -2, 	  -4,   -4, 	  -3,   -1, 	   0,   -5
.2byte   -3,   -3, 	  -7,   -4, 	   1,   -3, 	  -1,   -5
.2byte   -3,   -4, 	  -8,   -5, 	   2,   -4, 	  -1,   -7
.2byte   -3,   -3, 	  -7,   -5, 	   1,   -3, 	  -1,   -6
.2byte   -1,   -3, 	  -5,   -3, 	   3,   -3, 	  -1,   -5
.2byte   -1,   -5, 	  -8,   -5, 	   6,   -5, 	  -1,   -6
.2byte   -1,   -3, 	  -5,   -2, 	   3,   -2, 	  -1,   -4
.2byte    1,   -3, 	   5,   -4, 	  -3,   -3, 	  -1,   -5
.2byte    1,   -4, 	   6,   -5, 	  -4,   -4, 	  -1,   -7
.2byte    1,   -3, 	   5,   -5, 	  -3,   -3, 	  -1,   -6
.2byte    4,   -3, 	   3,   -7, 	   1,   -3, 	  -1,   -6
.2byte    4,   -5, 	   1,   -7, 	   0,   -5, 	  -1,   -7
.2byte    4,   -2, 	   2,   -4, 	   1,   -1, 	  -2,   -5
.2byte    0,   -7, 	  -5,   -7, 	   3,   -4, 	  -1,   -7
.2byte   -1,   -9, 	  -5,   -8, 	   4,   -5, 	  -1,   -8
.2byte   -1,   -7, 	  -4,   -5, 	   4,   -3, 	  -1,   -6
.2byte   -1,   -9, 	   3,   -5, 	  -5,   -5, 	  -1,   -6
.2byte   -1,  -11, 	   6,   -6, 	  -8,   -6, 	  -1,   -7
.2byte   -1,   -9, 	   5,   -3, 	  -7,   -3, 	  -1,   -6
.2byte   -2,   -7, 	   3,   -7, 	  -5,   -4, 	  -1,   -7
.2byte   -1,   -9, 	   3,   -8, 	  -6,   -5, 	  -1,   -8
.2byte   -1,   -7, 	   2,   -5, 	  -6,   -3, 	  -1,   -6
.2byte   -6,   -3, 	  -5,   -7, 	  -3,   -3, 	  -1,   -6
.2byte   -6,   -5, 	  -3,   -7, 	  -2,   -5, 	  -1,   -7
.2byte   -6,   -2, 	  -4,   -4, 	  -3,   -1, 	   0,   -5
.2byte   -3,   -3, 	  -7,   -4, 	   1,   -3, 	  -1,   -5
.2byte   -3,   -4, 	  -8,   -5, 	   2,   -4, 	  -1,   -7
.2byte   -3,   -3, 	  -7,   -5, 	   1,   -3, 	  -1,   -6
.2byte   -1,   -3, 	  -5,   -3, 	   3,   -3, 	  -1,   -5
.2byte    0,   -3, 	  -4,   -5, 	   4,   -3, 	   1,   -6
.2byte   -2,   -3, 	  -6,   -3, 	   2,   -5, 	  -3,   -6
.2byte    1,   -3, 	   5,   -4, 	  -3,   -3, 	  -1,   -5
.2byte    0,   -4, 	   4,   -6, 	  -4,   -3, 	  -2,   -6
.2byte    1,   -4, 	   5,   -4, 	  -3,   -6, 	   0,   -7
.2byte    4,   -3, 	   3,   -7, 	   1,   -3, 	  -1,   -6
.2byte    4,   -3, 	  -1,  -10, 	   2,   -1, 	  -2,   -7
.2byte    4,   -5, 	   2,   -6, 	   1,   -5, 	  -1,   -7
.2byte    0,   -7, 	  -5,   -7, 	   3,   -4, 	  -1,   -7
.2byte    1,   -8, 	  -4,  -10, 	   5,   -3, 	  -1,   -7
.2byte   -3,   -8, 	  -7,   -6, 	   4,   -7, 	  -3,   -7
.2byte   -1,   -9, 	   3,   -5, 	  -5,   -5, 	  -1,   -6
.2byte   -4,   -9, 	   2,   -8, 	  -6,   -4, 	  -3,   -7
.2byte    2,   -9, 	   4,   -4, 	  -4,   -8, 	   1,   -7
.2byte   -2,   -7, 	   3,   -7, 	  -5,   -4, 	  -1,   -7
.2byte   -3,   -8, 	   2,  -10, 	  -7,   -3, 	  -1,   -7
.2byte    1,   -8, 	   5,   -6, 	  -6,   -7, 	   1,   -7
.2byte   -6,   -3, 	  -5,   -7, 	  -3,   -3, 	  -1,   -6
.2byte   -6,   -3, 	  -1,  -10, 	  -4,   -1, 	   0,   -7
.2byte   -6,   -5, 	  -4,   -6, 	  -3,   -5, 	  -1,   -7
.2byte   -2,   -3, 	  -6,   -4, 	   2,   -3, 	   0,   -5
.2byte   -1,   -4, 	  -5,   -6, 	   3,   -3, 	   1,   -6
.2byte   -2,   -3, 	  -6,   -3, 	   2,   -5, 	  -1,   -6
.2byte   -3,   -1, 	  -6,   -2, 	   3,   -1, 	   0,   -5
.2byte   -2,   -1, 	  -5,   -1, 	   3,    0, 	  -1,   -5
.2byte    0,   -5, 	  -4,   -6, 	   4,   -6, 	   0,   -7
.2byte    1,   -5, 	   5,   -8, 	  -3,   -5, 	  -1,   -7
.2byte    5,   -5, 	   2,   -9, 	   1,   -6, 	  -1,   -7
.2byte    1,  -10, 	  -3,  -11, 	   3,  -10, 	  -1,   -7
.2byte    0,   -8, 	   3,   -6, 	  -3,   -6, 	   0,   -6
.2byte   -2,  -10, 	   2,  -11, 	  -4,  -10, 	   0,   -7
.2byte   -6,   -5, 	  -3,   -9, 	  -2,   -6, 	   0,   -7
.2byte   -2,   -5, 	  -6,   -8, 	   2,   -5, 	   0,   -7
.2byte   -1,   -3, 	  -5,   -3, 	   3,   -3, 	  -1,   -5
.2byte   -1,   -5, 	  -8,   -5, 	   6,   -5, 	  -1,   -6
.2byte    1,   -3, 	   5,   -4, 	  -3,   -3, 	  -1,   -5
.2byte    1,   -4, 	   6,   -5, 	  -4,   -4, 	  -1,   -7
.2byte    4,   -3, 	   3,   -7, 	   1,   -3, 	  -1,   -6
.2byte    4,   -5, 	   1,   -7, 	   0,   -5, 	  -1,   -7
.2byte    0,   -7, 	  -5,   -7, 	   3,   -4, 	  -1,   -7
.2byte   -1,   -9, 	  -5,   -8, 	   4,   -5, 	  -1,   -8
.2byte   -1,   -9, 	   3,   -5, 	  -5,   -5, 	  -1,   -6
.2byte   -1,  -11, 	   6,   -6, 	  -8,   -6, 	  -1,   -7
.2byte   -2,   -7, 	   3,   -7, 	  -5,   -4, 	  -1,   -7
.2byte   -1,   -9, 	   3,   -8, 	  -6,   -5, 	  -1,   -8
.2byte   -6,   -3, 	  -5,   -7, 	  -3,   -3, 	  -1,   -6
.2byte   -6,   -5, 	  -3,   -7, 	  -2,   -5, 	  -1,   -7
.2byte   -3,   -3, 	  -7,   -4, 	   1,   -3, 	  -1,   -5
.2byte   -3,   -4, 	  -8,   -5, 	   2,   -4, 	  -1,   -7
.2byte   -1,   -5, 	  -8,   -5, 	   6,   -5, 	  -1,   -6
.2byte   -2,   -4, 	  -7,   -5, 	   3,   -4, 	   0,   -7
.2byte   -6,   -5, 	  -3,   -7, 	  -2,   -5, 	  -1,   -7
.2byte   -1,   -9, 	   3,   -8, 	  -6,   -5, 	  -1,   -8
.2byte   -1,  -11, 	   6,   -6, 	  -8,   -6, 	  -1,   -7
.2byte   -1,   -9, 	  -5,   -8, 	   4,   -5, 	  -1,   -8
.2byte    4,   -5, 	   1,   -7, 	   0,   -5, 	  -1,   -7
.2byte    1,   -4, 	   6,   -5, 	  -4,   -4, 	  -1,   -7
.2byte   -1,   -5, 	  -8,   -5, 	   6,   -5, 	  -1,   -6
.2byte    1,   -4, 	   6,   -5, 	  -4,   -4, 	  -1,   -7
.2byte    4,   -5, 	   1,   -7, 	   0,   -5, 	  -1,   -7
.2byte   -1,   -9, 	  -5,   -8, 	   4,   -5, 	  -1,   -8
.2byte   -1,  -11, 	   6,   -6, 	  -8,   -6, 	  -1,   -7
.2byte   -1,   -9, 	   3,   -8, 	  -6,   -5, 	  -1,   -8
.2byte   -6,   -5, 	  -3,   -7, 	  -2,   -5, 	  -1,   -7
.2byte   -2,   -4, 	  -7,   -5, 	   3,   -4, 	   0,   -7
.2byte   -1,   -3, 	  -5,   -3, 	   3,   -3, 	  -1,   -5
.2byte   -1,   -5, 	  -8,   -5, 	   6,   -5, 	  -1,   -6
.2byte   -1,   -3, 	  -5,   -2, 	   3,   -2, 	  -1,   -4
.2byte    1,   -3, 	   5,   -4, 	  -3,   -3, 	  -1,   -5
.2byte    1,   -4, 	   6,   -5, 	  -4,   -4, 	  -1,   -7
.2byte    1,   -3, 	   5,   -5, 	  -3,   -3, 	  -1,   -6
.2byte    4,   -3, 	   3,   -7, 	   1,   -3, 	  -1,   -6
.2byte    4,   -5, 	   1,   -7, 	   0,   -5, 	  -1,   -7
.2byte    4,   -2, 	   2,   -4, 	   1,   -1, 	  -2,   -5
.2byte    0,   -7, 	  -5,   -7, 	   3,   -4, 	  -1,   -7
.2byte   -1,   -9, 	  -5,   -8, 	   4,   -5, 	  -1,   -8
.2byte   -1,   -7, 	  -4,   -5, 	   4,   -3, 	  -1,   -6
.2byte   -1,   -9, 	   3,   -5, 	  -5,   -5, 	  -1,   -6
.2byte   -1,  -11, 	   6,   -6, 	  -8,   -6, 	  -1,   -7
.2byte   -1,   -9, 	   5,   -3, 	  -7,   -3, 	  -1,   -6
.2byte   -2,   -7, 	   3,   -7, 	  -5,   -4, 	  -1,   -7
.2byte   -1,   -9, 	   3,   -8, 	  -6,   -5, 	  -1,   -8
.2byte   -1,   -7, 	   2,   -5, 	  -6,   -3, 	  -1,   -6
.2byte   -6,   -3, 	  -5,   -7, 	  -3,   -3, 	  -1,   -6
.2byte   -6,   -5, 	  -3,   -7, 	  -2,   -5, 	  -1,   -7
.2byte   -6,   -2, 	  -4,   -4, 	  -3,   -1, 	   0,   -5
.2byte   -3,   -3, 	  -7,   -4, 	   1,   -3, 	  -1,   -5
.2byte   -3,   -4, 	  -8,   -5, 	   2,   -4, 	  -1,   -7
.2byte   -3,   -3, 	  -7,   -5, 	   1,   -3, 	  -1,   -6
.2byte   -1,   -3, 	  -5,   -2, 	   3,   -2, 	  -1,   -4
.2byte   -3,   -3, 	  -7,   -5, 	   1,   -3, 	  -1,   -6
.2byte   -6,   -2, 	  -4,   -4, 	  -3,   -1, 	   0,   -5
.2byte   -1,   -7, 	   2,   -5, 	  -6,   -3, 	  -1,   -6
.2byte   -1,   -9, 	   5,   -3, 	  -7,   -3, 	  -1,   -6
.2byte   -1,   -7, 	  -4,   -5, 	   4,   -3, 	  -1,   -6
.2byte    4,   -2, 	   2,   -4, 	   1,   -1, 	  -2,   -5
.2byte    1,   -3, 	   5,   -5, 	  -3,   -3, 	  -1,   -6
.2byte   -1,   -3, 	  -5,   -3, 	   3,   -3, 	  -1,   -5
.2byte   -3,   -3, 	  -7,   -4, 	   1,   -3, 	  -1,   -5
.2byte   -6,   -3, 	  -5,   -7, 	  -3,   -3, 	  -1,   -6
.2byte   -2,   -7, 	   3,   -7, 	  -5,   -4, 	  -1,   -7
.2byte   -1,   -9, 	   3,   -5, 	  -5,   -5, 	  -1,   -6
.2byte    0,   -7, 	  -5,   -7, 	   3,   -4, 	  -1,   -7
.2byte    4,   -3, 	   3,   -7, 	   1,   -3, 	  -1,   -6
.2byte    1,   -3, 	   5,   -4, 	  -3,   -3, 	  -1,   -5
sCleffaAnimTable1:
.4byte sCleffaAnims_1_1
.4byte sCleffaAnims_1_2
.4byte sCleffaAnims_1_3
.4byte sCleffaAnims_1_4
.4byte sCleffaAnims_1_5
.4byte sCleffaAnims_1_6
.4byte sCleffaAnims_1_7
.4byte sCleffaAnims_1_8
sCleffaAnimTable2:
.4byte sCleffaAnims_2_1
.4byte sCleffaAnims_2_2
.4byte sCleffaAnims_2_3
.4byte sCleffaAnims_2_4
.4byte sCleffaAnims_2_5
.4byte sCleffaAnims_2_6
.4byte sCleffaAnims_2_7
.4byte sCleffaAnims_2_8
sCleffaAnimTable3:
.4byte sCleffaAnims_3_1
.4byte sCleffaAnims_3_2
.4byte sCleffaAnims_3_3
.4byte sCleffaAnims_3_4
.4byte sCleffaAnims_3_5
.4byte sCleffaAnims_3_6
.4byte sCleffaAnims_3_7
.4byte sCleffaAnims_3_8
sCleffaAnimTable4:
.4byte sCleffaAnims_4_1
.4byte sCleffaAnims_4_2
.4byte sCleffaAnims_4_3
.4byte sCleffaAnims_4_4
.4byte sCleffaAnims_4_5
.4byte sCleffaAnims_4_6
.4byte sCleffaAnims_4_7
.4byte sCleffaAnims_4_8
sCleffaAnimTable5:
.4byte sCleffaAnims_5_1
.4byte sCleffaAnims_5_2
.4byte sCleffaAnims_5_3
.4byte sCleffaAnims_5_4
.4byte sCleffaAnims_5_5
.4byte sCleffaAnims_5_6
.4byte sCleffaAnims_5_7
.4byte sCleffaAnims_5_8
sCleffaAnimTable6:
.4byte sCleffaAnims_6_1
.4byte sCleffaAnims_6_1
.4byte sCleffaAnims_6_1
.4byte sCleffaAnims_6_1
.4byte sCleffaAnims_6_1
.4byte sCleffaAnims_6_1
.4byte sCleffaAnims_6_1
.4byte sCleffaAnims_6_1
sCleffaAnimTable7:
.4byte sCleffaAnims_7_1
.4byte sCleffaAnims_7_2
.4byte sCleffaAnims_7_3
.4byte sCleffaAnims_7_4
.4byte sCleffaAnims_7_5
.4byte sCleffaAnims_7_6
.4byte sCleffaAnims_7_7
.4byte sCleffaAnims_7_8
sCleffaAnimTable8:
.4byte sCleffaAnims_8_1
.4byte sCleffaAnims_8_2
.4byte sCleffaAnims_8_3
.4byte sCleffaAnims_8_4
.4byte sCleffaAnims_8_5
.4byte sCleffaAnims_8_6
.4byte sCleffaAnims_8_7
.4byte sCleffaAnims_8_8
sCleffaAnimTable9:
.4byte sCleffaAnims_9_1
.4byte sCleffaAnims_9_2
.4byte sCleffaAnims_9_3
.4byte sCleffaAnims_9_4
.4byte sCleffaAnims_9_5
.4byte sCleffaAnims_9_6
.4byte sCleffaAnims_9_7
.4byte sCleffaAnims_9_8
sCleffaAnimTable10:
.4byte sCleffaAnims_10_1
.4byte sCleffaAnims_10_2
.4byte sCleffaAnims_10_3
.4byte sCleffaAnims_10_4
.4byte sCleffaAnims_10_5
.4byte sCleffaAnims_10_6
.4byte sCleffaAnims_10_7
.4byte sCleffaAnims_10_8
sCleffaAnimTable11:
.4byte sCleffaAnims_11_1
.4byte sCleffaAnims_11_2
.4byte sCleffaAnims_11_3
.4byte sCleffaAnims_11_4
.4byte sCleffaAnims_11_5
.4byte sCleffaAnims_11_6
.4byte sCleffaAnims_11_7
.4byte sCleffaAnims_11_8
sCleffaAnimTable12:
.4byte sCleffaAnims_12_1
.4byte sCleffaAnims_12_2
.4byte sCleffaAnims_12_3
.4byte sCleffaAnims_12_4
.4byte sCleffaAnims_12_5
.4byte sCleffaAnims_12_6
.4byte sCleffaAnims_12_7
.4byte sCleffaAnims_12_8
sCleffaAnimTable13:
.4byte sCleffaAnims_13_1
.4byte sCleffaAnims_13_2
.4byte sCleffaAnims_13_3
.4byte sCleffaAnims_13_4
.4byte sCleffaAnims_13_5
.4byte sCleffaAnims_13_6
.4byte sCleffaAnims_13_7
.4byte sCleffaAnims_13_8
sAxAnimationsCleffa:
.4byte sCleffaAnimTable1
.4byte sCleffaAnimTable2
.4byte sCleffaAnimTable3
.4byte sCleffaAnimTable4
.4byte sCleffaAnimTable5
.4byte sCleffaAnimTable6
.4byte sCleffaAnimTable7
.4byte sCleffaAnimTable8
.4byte sCleffaAnimTable9
.4byte sCleffaAnimTable10
.4byte sCleffaAnimTable11
.4byte sCleffaAnimTable12
.4byte sCleffaAnimTable13
sAxSpritesCleffa:
.4byte sCleffaSprites1
.4byte sCleffaSprites2
.4byte sCleffaSprites3
.4byte sCleffaSprites4
.4byte sCleffaSprites5
.4byte sCleffaSprites6
.4byte sCleffaSprites7
.4byte sCleffaSprites8
.4byte sCleffaSprites9
.4byte sCleffaSprites10
.4byte sCleffaSprites11
.4byte sCleffaSprites12
.4byte sCleffaSprites13
.4byte sCleffaSprites14
.4byte sCleffaSprites15
.4byte sCleffaSprites16
.4byte sCleffaSprites17
.4byte sCleffaSprites18
.4byte sCleffaSprites19
.4byte sCleffaSprites20
.4byte sCleffaSprites21
.4byte sCleffaSprites22
.4byte sCleffaSprites23
.4byte sCleffaSprites24
.4byte sCleffaSprites25
.4byte sCleffaSprites26
.4byte sCleffaSprites27
.4byte sCleffaSprites28
.4byte sCleffaSprites29
.4byte sCleffaSprites30
.4byte sCleffaSprites31
.4byte sCleffaSprites32
sAxMainCleffa:
ax_main sAxPosesCleffa, sAxAnimationsCleffa, 13, sAxSpritesCleffa, sAxPositionsCleffa
