.global gAxDelcatty
gAxDelcatty:
ax_siro sAxMainDelcatty
sDelcattyPose1:
ax_pose 0, 0x01e5, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose2:
ax_pose 1, 0x01e5, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose3:
ax_pose 2, 0x01e5, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose4:
ax_pose 3, 0x01e5, 0x90ef, 0x7c00
ax_pose_terminator
sDelcattyPose5:
ax_pose 4, 0x01e5, 0x90ef, 0x7c00
ax_pose_terminator
sDelcattyPose6:
ax_pose 5, 0x01e5, 0x90ef, 0x7c00
ax_pose_terminator
sDelcattyPose7:
ax_pose 6, 0x01e5, 0x90ef, 0x7c00
ax_pose_terminator
sDelcattyPose8:
ax_pose 7, 0x01e5, 0x90ef, 0x7c00
ax_pose_terminator
sDelcattyPose9:
ax_pose 8, 0x01e5, 0x90ef, 0x7c00
ax_pose_terminator
sDelcattyPose10:
ax_pose 9, 0x01e6, 0x90ef, 0x7c00
ax_pose_terminator
sDelcattyPose11:
ax_pose 10, 0x01e6, 0x90ef, 0x7c00
ax_pose_terminator
sDelcattyPose12:
ax_pose 11, 0x01e6, 0x90ef, 0x7c00
ax_pose_terminator
sDelcattyPose13:
ax_pose 12, 0x01e7, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose14:
ax_pose 13, 0x01e7, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose15:
ax_pose 14, 0x01e7, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose16:
ax_pose 9, 0x01e6, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose17:
ax_pose 10, 0x01e6, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose18:
ax_pose 11, 0x01e6, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose19:
ax_pose 6, 0x01e5, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose20:
ax_pose 7, 0x01e5, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose21:
ax_pose 8, 0x01e5, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose22:
ax_pose 3, 0x01e5, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose23:
ax_pose 4, 0x01e5, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose24:
ax_pose 5, 0x01e5, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose25:
ax_pose 0, 0x01e5, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose26:
ax_pose 15, 0x01e5, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose27:
ax_pose 16, 0x01e5, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose28:
ax_pose 17, 0x01e5, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose29:
ax_pose 3, 0x01e5, 0x90ef, 0x7c00
ax_pose_terminator
sDelcattyPose30:
ax_pose 18, 0x01e5, 0x90ef, 0x7c00
ax_pose_terminator
sDelcattyPose31:
ax_pose 19, 0x01e5, 0x90ef, 0x7c00
ax_pose_terminator
sDelcattyPose32:
ax_pose 20, 0x01e6, 0x90f0, 0x7c00
ax_pose_terminator
sDelcattyPose33:
ax_pose 6, 0x01e5, 0x90ef, 0x7c00
ax_pose_terminator
sDelcattyPose34:
ax_pose 21, 0x01e5, 0x90ef, 0x7c00
ax_pose_terminator
sDelcattyPose35:
ax_pose 22, 0x01e5, 0x90ef, 0x7c00
ax_pose_terminator
sDelcattyPose36:
ax_pose 23, 0x01e5, 0x90f0, 0x7c00
ax_pose_terminator
sDelcattyPose37:
ax_pose 9, 0x01e6, 0x90ef, 0x7c00
ax_pose_terminator
sDelcattyPose38:
ax_pose 24, 0x01e6, 0x90ef, 0x7c00
ax_pose_terminator
sDelcattyPose39:
ax_pose 25, 0x01e6, 0x90ef, 0x7c00
ax_pose_terminator
sDelcattyPose40:
ax_pose 26, 0x01e7, 0x90ef, 0x7c00
ax_pose_terminator
sDelcattyPose41:
ax_pose 12, 0x01e7, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose42:
ax_pose 27, 0x01e7, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose43:
ax_pose 28, 0x01e7, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose44:
ax_pose 29, 0x01e9, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose45:
ax_pose 9, 0x01e6, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose46:
ax_pose 24, 0x01e6, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose47:
ax_pose 25, 0x01e6, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose48:
ax_pose 26, 0x01e7, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose49:
ax_pose 6, 0x01e5, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose50:
ax_pose 21, 0x01e5, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose51:
ax_pose 22, 0x01e5, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose52:
ax_pose 23, 0x01e5, 0x80ef, 0x7c00
ax_pose_terminator
sDelcattyPose53:
ax_pose 3, 0x01e5, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose54:
ax_pose 18, 0x01e5, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose55:
ax_pose 19, 0x01e5, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose56:
ax_pose 20, 0x01e6, 0x80ef, 0x7c00
ax_pose_terminator
sDelcattyPose57:
ax_pose 0, 0x01e5, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose58:
ax_pose 15, 0x01e5, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose59:
ax_pose 16, 0x01e5, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose60:
ax_pose 17, 0x01e5, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose61:
ax_pose 3, 0x01e5, 0x90ef, 0x7c00
ax_pose_terminator
sDelcattyPose62:
ax_pose 18, 0x01e5, 0x90ef, 0x7c00
ax_pose_terminator
sDelcattyPose63:
ax_pose 19, 0x01e5, 0x90ef, 0x7c00
ax_pose_terminator
sDelcattyPose64:
ax_pose 20, 0x01e6, 0x90f0, 0x7c00
ax_pose_terminator
sDelcattyPose65:
ax_pose 6, 0x01e5, 0x90ef, 0x7c00
ax_pose_terminator
sDelcattyPose66:
ax_pose 21, 0x01e5, 0x90ef, 0x7c00
ax_pose_terminator
sDelcattyPose67:
ax_pose 22, 0x01e5, 0x90ef, 0x7c00
ax_pose_terminator
sDelcattyPose68:
ax_pose 23, 0x01e5, 0x90f0, 0x7c00
ax_pose_terminator
sDelcattyPose69:
ax_pose 9, 0x01e6, 0x90ef, 0x7c00
ax_pose_terminator
sDelcattyPose70:
ax_pose 24, 0x01e6, 0x90ef, 0x7c00
ax_pose_terminator
sDelcattyPose71:
ax_pose 25, 0x01e6, 0x90ef, 0x7c00
ax_pose_terminator
sDelcattyPose72:
ax_pose 26, 0x01e7, 0x90ef, 0x7c00
ax_pose_terminator
sDelcattyPose73:
ax_pose 12, 0x01e7, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose74:
ax_pose 27, 0x01e7, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose75:
ax_pose 28, 0x01e7, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose76:
ax_pose 29, 0x01e9, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose77:
ax_pose 9, 0x01e6, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose78:
ax_pose 24, 0x01e6, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose79:
ax_pose 25, 0x01e6, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose80:
ax_pose 26, 0x01e7, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose81:
ax_pose 6, 0x01e5, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose82:
ax_pose 21, 0x01e5, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose83:
ax_pose 22, 0x01e5, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose84:
ax_pose 23, 0x01e5, 0x80ef, 0x7c00
ax_pose_terminator
sDelcattyPose85:
ax_pose 3, 0x01e5, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose86:
ax_pose 18, 0x01e5, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose87:
ax_pose 19, 0x01e5, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose88:
ax_pose 20, 0x01e6, 0x80ef, 0x7c00
ax_pose_terminator
sDelcattyPose89:
ax_pose 0, 0x01e5, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose90:
ax_pose 15, 0x01e5, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose91:
ax_pose 16, 0x01e5, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose92:
ax_pose 17, 0x01e5, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose93:
ax_pose 3, 0x01e5, 0x90ef, 0x7c00
ax_pose_terminator
sDelcattyPose94:
ax_pose 18, 0x01e5, 0x90ef, 0x7c00
ax_pose_terminator
sDelcattyPose95:
ax_pose 19, 0x01e5, 0x90ef, 0x7c00
ax_pose_terminator
sDelcattyPose96:
ax_pose 20, 0x01e6, 0x90f0, 0x7c00
ax_pose_terminator
sDelcattyPose97:
ax_pose 6, 0x01e5, 0x90ef, 0x7c00
ax_pose_terminator
sDelcattyPose98:
ax_pose 21, 0x01e5, 0x90ef, 0x7c00
ax_pose_terminator
sDelcattyPose99:
ax_pose 22, 0x01e5, 0x90ef, 0x7c00
ax_pose_terminator
sDelcattyPose100:
ax_pose 23, 0x01e5, 0x90f0, 0x7c00
ax_pose_terminator
sDelcattyPose101:
ax_pose 9, 0x01e6, 0x90ef, 0x7c00
ax_pose_terminator
sDelcattyPose102:
ax_pose 24, 0x01e6, 0x90ef, 0x7c00
ax_pose_terminator
sDelcattyPose103:
ax_pose 25, 0x01e6, 0x90ef, 0x7c00
ax_pose_terminator
sDelcattyPose104:
ax_pose 26, 0x01e7, 0x90ef, 0x7c00
ax_pose_terminator
sDelcattyPose105:
ax_pose 12, 0x01e7, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose106:
ax_pose 27, 0x01e7, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose107:
ax_pose 28, 0x01e7, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose108:
ax_pose 29, 0x01e9, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose109:
ax_pose 9, 0x01e6, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose110:
ax_pose 24, 0x01e6, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose111:
ax_pose 25, 0x01e6, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose112:
ax_pose 26, 0x01e7, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose113:
ax_pose 6, 0x01e5, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose114:
ax_pose 21, 0x01e5, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose115:
ax_pose 22, 0x01e5, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose116:
ax_pose 23, 0x01e5, 0x80ef, 0x7c00
ax_pose_terminator
sDelcattyPose117:
ax_pose 3, 0x01e5, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose118:
ax_pose 18, 0x01e5, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose119:
ax_pose 19, 0x01e5, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose120:
ax_pose 20, 0x01e6, 0x80ef, 0x7c00
ax_pose_terminator
sDelcattyPose121:
ax_pose 0, 0x01e5, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose122:
ax_pose 30, 0x01e5, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose123:
ax_pose 31, 0x01e5, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose124:
ax_pose 3, 0x01e5, 0x90ef, 0x7c00
ax_pose_terminator
sDelcattyPose125:
ax_pose 32, 0x01e5, 0x90ef, 0x7c00
ax_pose_terminator
sDelcattyPose126:
ax_pose 33, 0x01e5, 0x90ef, 0x7c00
ax_pose_terminator
sDelcattyPose127:
ax_pose 6, 0x01e5, 0x90ef, 0x7c00
ax_pose_terminator
sDelcattyPose128:
ax_pose 34, 0x01e5, 0x90ef, 0x7c00
ax_pose_terminator
sDelcattyPose129:
ax_pose 35, 0x01e5, 0x90ef, 0x7c00
ax_pose_terminator
sDelcattyPose130:
ax_pose 9, 0x01e6, 0x90ef, 0x7c00
ax_pose_terminator
sDelcattyPose131:
ax_pose 36, 0x01e6, 0x90ef, 0x7c00
ax_pose_terminator
sDelcattyPose132:
ax_pose 37, 0x01e6, 0x90ef, 0x7c00
ax_pose_terminator
sDelcattyPose133:
ax_pose 12, 0x01e7, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose134:
ax_pose 38, 0x01e7, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose135:
ax_pose 39, 0x01e7, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose136:
ax_pose 9, 0x01e6, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose137:
ax_pose 36, 0x01e6, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose138:
ax_pose 37, 0x01e6, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose139:
ax_pose 6, 0x01e5, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose140:
ax_pose 34, 0x01e5, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose141:
ax_pose 35, 0x01e5, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose142:
ax_pose 3, 0x01e5, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose143:
ax_pose 32, 0x01e5, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose144:
ax_pose 33, 0x01e5, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose145:
ax_pose 40, 0x01eb, 0x80f5, 0x7c00
ax_pose_terminator
sDelcattyPose146:
ax_pose 41, 0x01eb, 0x80f5, 0x7c00
ax_pose_terminator
sDelcattyPose147:
ax_pose 42, 0x81e2, 0x4105, 0x7c00
ax_pose 43, 0x01da, 0x0100, 0x7c04
ax_pose 44, 0x81e2, 0x80f5, 0x7c05
ax_pose_terminator
sDelcattyPose148:
ax_pose 45, 0x81e3, 0x90fc, 0x7c00
ax_pose 46, 0x01db, 0x10f4, 0x7c08
ax_pose 47, 0x81e3, 0x10ec, 0x7c09
ax_pose 48, 0x81e3, 0x50f4, 0x7c0b
ax_pose_terminator
sDelcattyPose149:
ax_pose 49, 0x01e3, 0x90ea, 0x7c00
ax_pose_terminator
sDelcattyPose150:
ax_pose 50, 0x01e3, 0x90ea, 0x7c00
ax_pose_terminator
sDelcattyPose151:
ax_pose 51, 0x01e2, 0x80f1, 0x7c00
ax_pose_terminator
sDelcattyPose152:
ax_pose 50, 0x01e3, 0x80f6, 0x7c00
ax_pose_terminator
sDelcattyPose153:
ax_pose 49, 0x01e3, 0x80f6, 0x7c00
ax_pose_terminator
sDelcattyPose154:
ax_pose 45, 0x81e3, 0x80f4, 0x7c00
ax_pose 46, 0x01db, 0x0104, 0x7c08
ax_pose 47, 0x81e3, 0x010c, 0x7c09
ax_pose 48, 0x81e3, 0x4104, 0x7c0b
ax_pose_terminator
sDelcattyPose155:
ax_pose 0, 0x01e5, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose156:
ax_pose 30, 0x01e5, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose157:
ax_pose 31, 0x01e5, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose158:
ax_pose 17, 0x01e6, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose159:
ax_pose 3, 0x01e5, 0x90ef, 0x7c00
ax_pose_terminator
sDelcattyPose160:
ax_pose 32, 0x01e5, 0x90ef, 0x7c00
ax_pose_terminator
sDelcattyPose161:
ax_pose 33, 0x01e5, 0x90ef, 0x7c00
ax_pose_terminator
sDelcattyPose162:
ax_pose 20, 0x01e6, 0x90f0, 0x7c00
ax_pose_terminator
sDelcattyPose163:
ax_pose 6, 0x01e5, 0x90ef, 0x7c00
ax_pose_terminator
sDelcattyPose164:
ax_pose 34, 0x01e5, 0x90ef, 0x7c00
ax_pose_terminator
sDelcattyPose165:
ax_pose 35, 0x01e5, 0x90ef, 0x7c00
ax_pose_terminator
sDelcattyPose166:
ax_pose 23, 0x01e6, 0x90f0, 0x7c00
ax_pose_terminator
sDelcattyPose167:
ax_pose 9, 0x01e6, 0x90ef, 0x7c00
ax_pose_terminator
sDelcattyPose168:
ax_pose 36, 0x01e6, 0x90ef, 0x7c00
ax_pose_terminator
sDelcattyPose169:
ax_pose 37, 0x01e6, 0x90ef, 0x7c00
ax_pose_terminator
sDelcattyPose170:
ax_pose 26, 0x01e6, 0x90ef, 0x7c00
ax_pose_terminator
sDelcattyPose171:
ax_pose 12, 0x01e7, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose172:
ax_pose 38, 0x01e7, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose173:
ax_pose 39, 0x01e7, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose174:
ax_pose 29, 0x01e8, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose175:
ax_pose 9, 0x01e6, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose176:
ax_pose 36, 0x01e6, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose177:
ax_pose 37, 0x01e6, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose178:
ax_pose 26, 0x01e6, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose179:
ax_pose 6, 0x01e5, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose180:
ax_pose 34, 0x01e5, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose181:
ax_pose 35, 0x01e5, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose182:
ax_pose 23, 0x01e6, 0x80ef, 0x7c00
ax_pose_terminator
sDelcattyPose183:
ax_pose 3, 0x01e5, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose184:
ax_pose 32, 0x01e5, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose185:
ax_pose 33, 0x01e5, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose186:
ax_pose 20, 0x01e6, 0x80ef, 0x7c00
ax_pose_terminator
sDelcattyPose187:
ax_pose 16, 0x01e5, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose188:
ax_pose 19, 0x01e5, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose189:
ax_pose 22, 0x01e5, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose190:
ax_pose 25, 0x01e6, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose191:
ax_pose 28, 0x01e7, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose192:
ax_pose 25, 0x01e6, 0x90ef, 0x7c00
ax_pose_terminator
sDelcattyPose193:
ax_pose 22, 0x01e5, 0x90ef, 0x7c00
ax_pose_terminator
sDelcattyPose194:
ax_pose 19, 0x01e5, 0x90ef, 0x7c00
ax_pose_terminator
sDelcattyPose195:
ax_pose 15, 0x01e6, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose196:
ax_pose 18, 0x01e5, 0x90f1, 0x7c00
ax_pose_terminator
sDelcattyPose197:
ax_pose 21, 0x01e5, 0x90f0, 0x7c00
ax_pose_terminator
sDelcattyPose198:
ax_pose 24, 0x01e6, 0x90f0, 0x7c00
ax_pose_terminator
sDelcattyPose199:
ax_pose 27, 0x01e6, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose200:
ax_pose 24, 0x01e6, 0x80ef, 0x7c00
ax_pose_terminator
sDelcattyPose201:
ax_pose 21, 0x01e5, 0x80ef, 0x7c00
ax_pose_terminator
sDelcattyPose202:
ax_pose 18, 0x01e5, 0x80ef, 0x7c00
ax_pose_terminator
sDelcattyPose203:
ax_pose 0, 0x01e5, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose204:
ax_pose 15, 0x01e5, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose205:
ax_pose 16, 0x01e5, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose206:
ax_pose 3, 0x01e5, 0x90ef, 0x7c00
ax_pose_terminator
sDelcattyPose207:
ax_pose 18, 0x01e5, 0x90ef, 0x7c00
ax_pose_terminator
sDelcattyPose208:
ax_pose 19, 0x01e5, 0x90ef, 0x7c00
ax_pose_terminator
sDelcattyPose209:
ax_pose 6, 0x01e5, 0x90ef, 0x7c00
ax_pose_terminator
sDelcattyPose210:
ax_pose 21, 0x01e5, 0x90ef, 0x7c00
ax_pose_terminator
sDelcattyPose211:
ax_pose 22, 0x01e5, 0x90ee, 0x7c00
ax_pose_terminator
sDelcattyPose212:
ax_pose 9, 0x01e6, 0x90ef, 0x7c00
ax_pose_terminator
sDelcattyPose213:
ax_pose 24, 0x01e6, 0x90ef, 0x7c00
ax_pose_terminator
sDelcattyPose214:
ax_pose 25, 0x01e6, 0x90ee, 0x7c00
ax_pose_terminator
sDelcattyPose215:
ax_pose 12, 0x01e7, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose216:
ax_pose 27, 0x01e7, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose217:
ax_pose 28, 0x01e5, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose218:
ax_pose 9, 0x01e6, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose219:
ax_pose 24, 0x01e6, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose220:
ax_pose 25, 0x01e6, 0x80f1, 0x7c00
ax_pose_terminator
sDelcattyPose221:
ax_pose 6, 0x01e5, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose222:
ax_pose 21, 0x01e5, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose223:
ax_pose 22, 0x01e5, 0x80f1, 0x7c00
ax_pose_terminator
sDelcattyPose224:
ax_pose 3, 0x01e5, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose225:
ax_pose 18, 0x01e5, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose226:
ax_pose 19, 0x01e5, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose227:
ax_pose 16, 0x01e5, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose228:
ax_pose 19, 0x01e5, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose229:
ax_pose 22, 0x01e5, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose230:
ax_pose 25, 0x01e6, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose231:
ax_pose 28, 0x01e7, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose232:
ax_pose 25, 0x01e6, 0x90ef, 0x7c00
ax_pose_terminator
sDelcattyPose233:
ax_pose 22, 0x01e5, 0x90ef, 0x7c00
ax_pose_terminator
sDelcattyPose234:
ax_pose 19, 0x01e5, 0x90ef, 0x7c00
ax_pose_terminator
sDelcattyPose235:
ax_pose 0, 0x01e5, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose236:
ax_pose 3, 0x01e5, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose237:
ax_pose 6, 0x01e5, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose238:
ax_pose 9, 0x01e6, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose239:
ax_pose 12, 0x01e7, 0x80f0, 0x7c00
ax_pose_terminator
sDelcattyPose240:
ax_pose 9, 0x01e6, 0x90ef, 0x7c00
ax_pose_terminator
sDelcattyPose241:
ax_pose 6, 0x01e5, 0x90ef, 0x7c00
ax_pose_terminator
sDelcattyPose242:
ax_pose 3, 0x01e5, 0x90ef, 0x7c00
ax_pose_terminator
.align 2
sDelcattyAnims_1_1:
ax_anim 8, 0, 0, 0, 0, 0, 0,
ax_anim 10, 0, 1, 0, 0, 0, 0,
ax_anim 8, 0, 0, 0, 0, 0, 0,
ax_anim 10, 0, 2, 0, 0, 0, 0,
ax_anim_terminator
sDelcattyAnims_1_2:
ax_anim 8, 0, 3, 0, 0, 0, 0,
ax_anim 10, 0, 4, 0, 0, 0, 0,
ax_anim 8, 0, 3, 0, 0, 0, 0,
ax_anim 10, 0, 5, 0, 0, 0, 0,
ax_anim_terminator
sDelcattyAnims_1_3:
ax_anim 8, 0, 6, 0, 0, 0, 0,
ax_anim 10, 0, 7, 0, 0, 0, 0,
ax_anim 8, 0, 6, 0, 0, 0, 0,
ax_anim 10, 0, 8, 0, 0, 0, 0,
ax_anim_terminator
sDelcattyAnims_1_4:
ax_anim 8, 0, 9, 0, 0, 0, 0,
ax_anim 10, 0, 10, 0, 0, 0, 0,
ax_anim 8, 0, 9, 0, 0, 0, 0,
ax_anim 10, 0, 11, 0, 0, 0, 0,
ax_anim_terminator
sDelcattyAnims_1_5:
ax_anim 8, 0, 12, 0, 0, 0, 0,
ax_anim 10, 0, 13, 0, 0, 0, 0,
ax_anim 8, 0, 12, 0, 0, 0, 0,
ax_anim 10, 0, 14, 0, 0, 0, 0,
ax_anim_terminator
sDelcattyAnims_1_6:
ax_anim 8, 0, 15, 0, 0, 0, 0,
ax_anim 10, 0, 16, 0, 0, 0, 0,
ax_anim 8, 0, 15, 0, 0, 0, 0,
ax_anim 10, 0, 17, 0, 0, 0, 0,
ax_anim_terminator
sDelcattyAnims_1_7:
ax_anim 8, 0, 18, 0, 0, 0, 0,
ax_anim 10, 0, 19, 0, 0, 0, 0,
ax_anim 8, 0, 18, 0, 0, 0, 0,
ax_anim 10, 0, 20, 0, 0, 0, 0,
ax_anim_terminator
sDelcattyAnims_1_8:
ax_anim 8, 0, 21, 0, 0, 0, 0,
ax_anim 10, 0, 22, 0, 0, 0, 0,
ax_anim 8, 0, 21, 0, 0, 0, 0,
ax_anim 10, 0, 23, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sDelcattyAnims_2_1:
ax_anim 2, 0, 24, 0, -1, 0, -1,
ax_anim 4, 0, 25, 0, -2, 0, -2,
ax_anim 1, 0, 25, 0, 0, 0, 0,
ax_anim 1, 2, 24, 0, 4, 0, 4,
ax_anim 1, 0, 24, 0, 10, 0, 10,
ax_anim 2, 0, 26, 0, 20, 0, 20,
ax_anim 2, 1, 26, 1, 20, 1, 20,
ax_anim 2, 0, 26, 0, 20, 0, 20,
ax_anim 2, 0, 26, 1, 20, 1, 20,
ax_anim 2, 0, 24, 0, 6, 0, 6,
ax_anim_terminator
sDelcattyAnims_2_2:
ax_anim 2, 0, 28, -1, -1, -1, -1,
ax_anim 4, 0, 29, -2, -2, -2, -2,
ax_anim 1, 0, 29, 0, 0, 0, 0,
ax_anim 1, 2, 28, 4, 4, 4, 4,
ax_anim 1, 0, 28, 10, 10, 10, 10,
ax_anim 2, 0, 30, 21, 19, 21, 19,
ax_anim 2, 1, 30, 22, 18, 22, 18,
ax_anim 2, 0, 30, 21, 19, 21, 19,
ax_anim 2, 0, 30, 22, 18, 22, 18,
ax_anim 2, 0, 28, 6, 6, 6, 6,
ax_anim_terminator
sDelcattyAnims_2_3:
ax_anim 2, 0, 32, -1, 0, -1, 0,
ax_anim 4, 0, 33, -2, 0, -2, 0,
ax_anim 1, 0, 33, 0, 0, 0, 0,
ax_anim 1, 2, 32, 4, 0, 4, 0,
ax_anim 1, 0, 32, 12, 0, 12, 0,
ax_anim 2, 0, 34, 19, 0, 19, 0,
ax_anim 2, 1, 34, 19, 1, 19, 1,
ax_anim 2, 0, 34, 19, 0, 19, 0,
ax_anim 2, 0, 34, 19, 1, 19, 1,
ax_anim 2, 0, 32, 6, 0, 6, 0,
ax_anim_terminator
sDelcattyAnims_2_4:
ax_anim 2, 0, 36, -1, 1, -1, 1,
ax_anim 4, 0, 37, -2, 2, -2, 2,
ax_anim 1, 0, 37, 0, -1, 0, -1,
ax_anim 1, 2, 36, 5, -6, 5, -6,
ax_anim 1, 0, 36, 11, -12, 11, -12,
ax_anim 2, 0, 38, 19, -18, 19, -18,
ax_anim 2, 1, 38, 20, -17, 20, -17,
ax_anim 2, 0, 38, 19, -18, 19, -18,
ax_anim 2, 0, 38, 20, -17, 20, -17,
ax_anim 2, 0, 36, 6, -6, 6, -6,
ax_anim_terminator
sDelcattyAnims_2_5:
ax_anim 2, 0, 40, 0, 1, 0, 1,
ax_anim 4, 0, 41, 0, 2, 0, 2,
ax_anim 1, 0, 41, 0, 0, 0, 0,
ax_anim 1, 2, 40, 0, -4, 0, -4,
ax_anim 1, 0, 40, 0, -11, 0, -11,
ax_anim 2, 0, 42, 0, -20, 0, -20,
ax_anim 2, 1, 42, 1, -20, 1, -20,
ax_anim 2, 0, 42, 0, -20, 0, -20,
ax_anim 2, 0, 42, 1, -20, 1, -20,
ax_anim 2, 0, 40, 0, -6, 0, -6,
ax_anim_terminator
sDelcattyAnims_2_6:
ax_anim 2, 0, 44, 1, 1, 1, 1,
ax_anim 4, 0, 45, 2, 2, 2, 2,
ax_anim 1, 0, 45, 0, -1, 0, -1,
ax_anim 1, 2, 44, -5, -6, -5, -6,
ax_anim 1, 0, 44, -11, -12, -11, -12,
ax_anim 2, 0, 46, -19, -18, -19, -18,
ax_anim 2, 1, 46, -20, -17, -20, -17,
ax_anim 2, 0, 46, -19, -18, -19, -18,
ax_anim 2, 0, 46, -20, -17, -20, -17,
ax_anim 2, 0, 44, -6, -6, -6, -6,
ax_anim_terminator
sDelcattyAnims_2_7:
ax_anim 2, 0, 48, 1, 0, 1, 0,
ax_anim 4, 0, 49, 2, 0, 2, 0,
ax_anim 1, 0, 49, 0, 0, 0, 0,
ax_anim 1, 2, 48, -4, 0, -4, 0,
ax_anim 1, 0, 48, -12, 0, -12, 0,
ax_anim 2, 0, 50, -19, 0, -19, 0,
ax_anim 2, 1, 50, -19, 1, -19, 1,
ax_anim 2, 0, 50, -19, 0, -19, 0,
ax_anim 2, 0, 50, -19, 1, -19, 1,
ax_anim 2, 0, 48, -6, 0, -6, 0,
ax_anim_terminator
sDelcattyAnims_2_8:
ax_anim 2, 0, 52, 1, -1, 1, -1,
ax_anim 4, 0, 53, 2, -2, 2, -2,
ax_anim 1, 0, 53, 0, 0, 0, 0,
ax_anim 1, 2, 52, -4, 4, -4, 4,
ax_anim 1, 0, 52, -10, 10, -10, 10,
ax_anim 2, 0, 54, -21, 19, -21, 19,
ax_anim 2, 1, 54, -22, 18, -22, 18,
ax_anim 2, 0, 54, -21, 19, -21, 19,
ax_anim 2, 0, 54, -22, 18, -22, 18,
ax_anim 2, 0, 52, -6, 6, -6, 6,
ax_anim_terminator
.align 2
sDelcattyAnims_3_1:
ax_anim 2, 0, 56, 0, -1, 0, -1,
ax_anim 4, 0, 57, 0, -2, 0, -2,
ax_anim 1, 0, 57, 0, 0, 0, 0,
ax_anim 1, 2, 56, 0, 4, 0, 4,
ax_anim 1, 0, 56, 0, 10, 0, 10,
ax_anim 2, 0, 58, 0, 20, 0, 20,
ax_anim 2, 1, 58, 1, 20, 1, 20,
ax_anim 2, 0, 58, 0, 20, 0, 20,
ax_anim 2, 0, 58, 1, 20, 1, 20,
ax_anim 2, 0, 56, 0, 6, 0, 6,
ax_anim_terminator
sDelcattyAnims_3_2:
ax_anim 2, 0, 60, -1, -1, -1, -1,
ax_anim 4, 0, 61, -2, -2, -2, -2,
ax_anim 1, 0, 61, 0, 0, 0, 0,
ax_anim 1, 2, 60, 4, 4, 4, 4,
ax_anim 1, 0, 60, 10, 10, 10, 10,
ax_anim 2, 0, 62, 21, 19, 21, 19,
ax_anim 2, 1, 62, 22, 18, 22, 18,
ax_anim 2, 0, 62, 21, 19, 21, 19,
ax_anim 2, 0, 62, 22, 18, 22, 18,
ax_anim 2, 0, 60, 6, 6, 6, 6,
ax_anim_terminator
sDelcattyAnims_3_3:
ax_anim 2, 0, 64, -1, 0, -1, 0,
ax_anim 4, 0, 65, -2, 0, -2, 0,
ax_anim 1, 0, 65, 0, 0, 0, 0,
ax_anim 1, 2, 64, 4, 0, 4, 0,
ax_anim 1, 0, 64, 12, 0, 12, 0,
ax_anim 2, 0, 66, 19, 0, 19, 0,
ax_anim 2, 1, 66, 19, 1, 19, 1,
ax_anim 2, 0, 66, 19, 0, 19, 0,
ax_anim 2, 0, 66, 19, 1, 19, 1,
ax_anim 2, 0, 64, 6, 0, 6, 0,
ax_anim_terminator
sDelcattyAnims_3_4:
ax_anim 2, 0, 68, -1, 1, -1, 1,
ax_anim 4, 0, 69, -2, 2, -2, 2,
ax_anim 1, 0, 69, 0, -1, 0, -1,
ax_anim 1, 2, 68, 5, -6, 5, -6,
ax_anim 1, 0, 68, 11, -12, 11, -12,
ax_anim 2, 0, 70, 19, -18, 19, -18,
ax_anim 2, 1, 70, 20, -17, 20, -17,
ax_anim 2, 0, 70, 19, -18, 19, -18,
ax_anim 2, 0, 70, 20, -17, 20, -17,
ax_anim 2, 0, 68, 6, -6, 6, -6,
ax_anim_terminator
sDelcattyAnims_3_5:
ax_anim 2, 0, 72, 0, 1, 0, 1,
ax_anim 4, 0, 73, 0, 2, 0, 2,
ax_anim 1, 0, 73, 0, 0, 0, 0,
ax_anim 1, 2, 72, 0, -4, 0, -4,
ax_anim 1, 0, 72, 0, -11, 0, -11,
ax_anim 2, 0, 74, 0, -20, 0, -20,
ax_anim 2, 1, 74, 1, -20, 1, -20,
ax_anim 2, 0, 74, 0, -20, 0, -20,
ax_anim 2, 0, 74, 1, -20, 1, -20,
ax_anim 2, 0, 72, 0, -6, 0, -6,
ax_anim_terminator
sDelcattyAnims_3_6:
ax_anim 2, 0, 76, 1, 1, 1, 1,
ax_anim 4, 0, 77, 2, 2, 2, 2,
ax_anim 1, 0, 77, 0, -1, 0, -1,
ax_anim 1, 2, 76, -5, -6, -5, -6,
ax_anim 1, 0, 76, -11, -12, -11, -12,
ax_anim 2, 0, 78, -19, -18, -19, -18,
ax_anim 2, 1, 78, -20, -17, -20, -17,
ax_anim 2, 0, 78, -19, -18, -19, -18,
ax_anim 2, 0, 78, -20, -17, -20, -17,
ax_anim 2, 0, 76, -6, -6, -6, -6,
ax_anim_terminator
sDelcattyAnims_3_7:
ax_anim 2, 0, 80, 1, 0, 1, 0,
ax_anim 4, 0, 81, 2, 0, 2, 0,
ax_anim 1, 0, 81, 0, 0, 0, 0,
ax_anim 1, 2, 80, -4, 0, -4, 0,
ax_anim 1, 0, 80, -12, 0, -12, 0,
ax_anim 2, 0, 82, -19, 0, -19, 0,
ax_anim 2, 1, 82, -19, 1, -19, 1,
ax_anim 2, 0, 82, -19, 0, -19, 0,
ax_anim 2, 0, 82, -19, 1, -19, 1,
ax_anim 2, 0, 80, -6, 0, -6, 0,
ax_anim_terminator
sDelcattyAnims_3_8:
ax_anim 2, 0, 84, 1, -1, 1, -1,
ax_anim 4, 0, 85, 2, -2, 2, -2,
ax_anim 1, 0, 85, 0, 0, 0, 0,
ax_anim 1, 2, 84, -4, 4, -4, 4,
ax_anim 1, 0, 84, -10, 10, -10, 10,
ax_anim 2, 0, 86, -21, 19, -21, 19,
ax_anim 2, 1, 86, -22, 18, -22, 18,
ax_anim 2, 0, 86, -21, 19, -21, 19,
ax_anim 2, 0, 86, -22, 18, -22, 18,
ax_anim 2, 0, 84, -6, 6, -6, 6,
ax_anim_terminator
.align 2
sDelcattyAnims_4_1:
ax_anim 6, 0, 91, 0, 0, 0, 0,
ax_anim 2, 0, 89, 0, -2, 0, -2,
ax_anim 2, 2, 89, 0, -3, 0, -3,
ax_anim 4, 0, 89, 0, -4, 0, -4,
ax_anim 1, 0, 90, 0, -1, 0, -1,
ax_anim 1, 0, 90, 0, 4, 0, 4,
ax_anim 2, 1, 90, 0, 5, 0, 5,
ax_anim 2, 0, 90, 1, 5, 1, 5,
ax_anim 2, 0, 90, 0, 5, 0, 5,
ax_anim 2, 0, 90, 1, 5, 1, 5,
ax_anim 2, 0, 90, 0, 5, 0, 5,
ax_anim 2, 0, 90, 1, 5, 1, 5,
ax_anim 2, 0, 88, 0, 2, 0, 2,
ax_anim_terminator
sDelcattyAnims_4_2:
ax_anim 6, 0, 95, 0, 0, 0, 0,
ax_anim 2, 0, 93, -2, -2, -1, -1,
ax_anim 2, 2, 93, -3, -3, -3, -3,
ax_anim 4, 0, 93, -4, -4, -4, -4,
ax_anim 1, 0, 94, -1, -1, -1, -1,
ax_anim 1, 0, 94, 4, 4, 4, 4,
ax_anim 2, 1, 94, 6, 6, 6, 6,
ax_anim 2, 0, 94, 7, 5, 7, 5,
ax_anim 2, 0, 94, 6, 6, 6, 6,
ax_anim 2, 0, 94, 7, 5, 7, 5,
ax_anim 2, 0, 94, 6, 6, 6, 6,
ax_anim 2, 0, 94, 7, 5, 7, 5,
ax_anim 2, 0, 92, 2, 2, 2, 2,
ax_anim_terminator
sDelcattyAnims_4_3:
ax_anim 6, 0, 99, 0, 0, 0, 0,
ax_anim 2, 0, 97, -2, 0, -2, 0,
ax_anim 2, 2, 97, -3, 0, -3, 0,
ax_anim 4, 0, 97, -4, 0, -4, 0,
ax_anim 1, 0, 98, -1, 0, -1, 0,
ax_anim 1, 0, 98, 4, 0, 4, 0,
ax_anim 2, 1, 98, 6, 0, 6, 0,
ax_anim 2, 0, 98, 6, 1, 6, 1,
ax_anim 2, 0, 98, 6, 0, 6, 0,
ax_anim 2, 0, 98, 6, 1, 6, 1,
ax_anim 2, 0, 98, 6, 0, 6, 0,
ax_anim 2, 0, 98, 6, 1, 6, 1,
ax_anim 2, 0, 96, 2, 0, 2, 0,
ax_anim_terminator
sDelcattyAnims_4_4:
ax_anim 6, 0, 103, 0, 0, 0, 0,
ax_anim 2, 0, 101, -1, 1, -1, 1,
ax_anim 2, 2, 101, -3, 3, -3, 3,
ax_anim 4, 0, 101, -4, 4, -4, 4,
ax_anim 1, 0, 102, -1, 1, -1, 1,
ax_anim 1, 0, 102, 4, -4, 4, -4,
ax_anim 2, 1, 102, 6, -6, 6, -6,
ax_anim 2, 0, 102, 7, -5, 7, -5,
ax_anim 2, 0, 102, 6, -6, 6, -6,
ax_anim 2, 0, 102, 7, -5, 7, -5,
ax_anim 2, 0, 102, 6, -6, 6, -6,
ax_anim 2, 0, 102, 7, -5, 7, -5,
ax_anim 2, 0, 100, 2, -2, 2, -2,
ax_anim_terminator
sDelcattyAnims_4_5:
ax_anim 6, 0, 107, 0, 0, 0, 0,
ax_anim 2, 0, 105, 0, 1, 0, 1,
ax_anim 2, 2, 105, 0, 3, 0, 3,
ax_anim 4, 0, 105, 0, 4, 0, 4,
ax_anim 1, 0, 106, 0, 1, 0, 1,
ax_anim 1, 0, 106, 0, -4, 0, -4,
ax_anim 2, 1, 106, 0, -6, 0, -5,
ax_anim 2, 0, 106, 1, -6, 1, -5,
ax_anim 2, 0, 106, 0, -6, 0, -5,
ax_anim 2, 0, 106, 1, -6, 1, -5,
ax_anim 2, 0, 106, 0, -6, 0, -5,
ax_anim 2, 0, 106, 1, -6, 1, -5,
ax_anim 2, 0, 104, 0, -2, 0, -2,
ax_anim_terminator
sDelcattyAnims_4_6:
ax_anim 6, 0, 111, 0, 0, 0, 0,
ax_anim 2, 0, 109, 1, 1, 1, 1,
ax_anim 2, 2, 109, 3, 3, 3, 3,
ax_anim 4, 0, 109, 4, 4, 4, 4,
ax_anim 1, 0, 110, 1, 1, 1, 1,
ax_anim 1, 0, 110, -4, -4, -4, -4,
ax_anim 2, 1, 110, -6, -6, -6, -6,
ax_anim 2, 0, 110, -7, -5, -7, -5,
ax_anim 2, 0, 110, -6, -6, -6, -6,
ax_anim 2, 0, 110, -7, -5, -7, -5,
ax_anim 2, 0, 110, -6, -6, -6, -6,
ax_anim 2, 0, 110, -7, -5, -7, -5,
ax_anim 2, 0, 108, -2, -2, -2, -2,
ax_anim_terminator
sDelcattyAnims_4_7:
ax_anim 6, 0, 115, 0, 0, 0, 0,
ax_anim 2, 0, 113, 2, 0, 2, 0,
ax_anim 2, 2, 113, 3, 0, 3, 0,
ax_anim 4, 0, 113, 4, 0, 4, 0,
ax_anim 1, 0, 114, 1, 0, 1, 0,
ax_anim 1, 0, 114, -4, 0, -4, 0,
ax_anim 2, 1, 114, -6, 0, -6, 0,
ax_anim 2, 0, 114, -6, 1, -6, 1,
ax_anim 2, 0, 114, -6, 0, -6, 0,
ax_anim 2, 0, 114, -6, 1, -6, 1,
ax_anim 2, 0, 114, -6, 0, -6, 0,
ax_anim 2, 0, 114, -6, 1, -6, 1,
ax_anim 2, 0, 112, -2, 0, -2, 0,
ax_anim_terminator
sDelcattyAnims_4_8:
ax_anim 6, 0, 119, 0, 0, 0, 0,
ax_anim 2, 0, 117, 2, -2, 2, -2,
ax_anim 2, 2, 117, 3, -3, 3, -3,
ax_anim 4, 0, 117, 4, -4, 4, -4,
ax_anim 1, 0, 118, 1, -1, 1, -1,
ax_anim 1, 0, 118, -4, 4, -4, 4,
ax_anim 2, 1, 118, -6, 6, -6, 6,
ax_anim 2, 0, 118, -7, 5, -7, 5,
ax_anim 2, 0, 118, -6, 6, -6, 6,
ax_anim 2, 0, 118, -7, 5, -7, 5,
ax_anim 2, 0, 118, -6, 6, -6, 6,
ax_anim 2, 0, 118, -7, 5, -7, 5,
ax_anim 2, 0, 116, -2, 2, -2, 2,
ax_anim_terminator
.align 2
sDelcattyAnims_5_1:
ax_anim 4, 0, 121, 0, 0, 0, 0,
ax_anim 2, 0, 120, 0, 0, 0, 0,
ax_anim 4, 0, 122, 0, 0, 0, 0,
ax_anim 2, 0, 120, 0, 0, 0, 0,
ax_anim 4, 0, 121, 0, 0, 0, 0,
ax_anim 2, 2, 120, 0, 0, 0, 0,
ax_anim 4, 0, 122, 0, 0, 0, 0,
ax_anim 2, 0, 120, 0, 0, 0, 0,
ax_anim 4, 0, 121, 0, 0, 0, 0,
ax_anim 2, 0, 120, 0, 0, 0, 0,
ax_anim_terminator
sDelcattyAnims_5_2:
ax_anim 4, 0, 124, 0, 0, 0, 0,
ax_anim 2, 0, 123, 0, 0, 0, 0,
ax_anim 4, 0, 125, 0, 0, 0, 0,
ax_anim 2, 0, 123, 0, 0, 0, 0,
ax_anim 4, 0, 124, 0, 0, 0, 0,
ax_anim 2, 2, 123, 0, 0, 0, 0,
ax_anim 4, 0, 125, 0, 0, 0, 0,
ax_anim 2, 0, 123, 0, 0, 0, 0,
ax_anim 4, 0, 124, 0, 0, 0, 0,
ax_anim 2, 0, 123, 0, 0, 0, 0,
ax_anim_terminator
sDelcattyAnims_5_3:
ax_anim 4, 0, 127, 0, 0, 0, 0,
ax_anim 2, 0, 126, 0, 0, 0, 0,
ax_anim 4, 0, 128, 0, 0, 0, 0,
ax_anim 2, 0, 126, 0, 0, 0, 0,
ax_anim 4, 0, 127, 0, 0, 0, 0,
ax_anim 2, 2, 126, 0, 0, 0, 0,
ax_anim 4, 0, 128, 0, 0, 0, 0,
ax_anim 2, 0, 126, 0, 0, 0, 0,
ax_anim 4, 0, 127, 0, 0, 0, 0,
ax_anim 2, 0, 126, 0, 0, 0, 0,
ax_anim_terminator
sDelcattyAnims_5_4:
ax_anim 4, 0, 130, 0, 0, 0, 0,
ax_anim 2, 0, 129, 0, 0, 0, 0,
ax_anim 4, 0, 131, 0, 0, 0, 0,
ax_anim 2, 0, 129, 0, 0, 0, 0,
ax_anim 4, 0, 130, 0, 0, 0, 0,
ax_anim 2, 2, 129, 0, 0, 0, 0,
ax_anim 4, 0, 131, 0, 0, 0, 0,
ax_anim 2, 0, 129, 0, 0, 0, 0,
ax_anim 4, 0, 130, 0, 0, 0, 0,
ax_anim 2, 0, 129, 0, 0, 0, 0,
ax_anim_terminator
sDelcattyAnims_5_5:
ax_anim 4, 0, 133, 0, 0, 0, 0,
ax_anim 2, 0, 132, 0, 0, 0, 0,
ax_anim 4, 0, 134, 0, 0, 0, 0,
ax_anim 2, 0, 132, 0, 0, 0, 0,
ax_anim 4, 0, 133, 0, 0, 0, 0,
ax_anim 2, 2, 132, 0, 0, 0, 0,
ax_anim 4, 0, 134, 0, 0, 0, 0,
ax_anim 2, 0, 132, 0, 0, 0, 0,
ax_anim 4, 0, 133, 0, 0, 0, 0,
ax_anim 2, 0, 132, 0, 0, 0, 0,
ax_anim_terminator
sDelcattyAnims_5_6:
ax_anim 4, 0, 136, 0, 0, 0, 0,
ax_anim 2, 0, 135, 0, 0, 0, 0,
ax_anim 4, 0, 137, 0, 0, 0, 0,
ax_anim 2, 0, 135, 0, 0, 0, 0,
ax_anim 4, 0, 136, 0, 0, 0, 0,
ax_anim 2, 2, 135, 0, 0, 0, 0,
ax_anim 4, 0, 137, 0, 0, 0, 0,
ax_anim 2, 0, 135, 0, 0, 0, 0,
ax_anim 4, 0, 136, 0, 0, 0, 0,
ax_anim 2, 0, 135, 0, 0, 0, 0,
ax_anim_terminator
sDelcattyAnims_5_7:
ax_anim 4, 0, 139, 0, 0, 0, 0,
ax_anim 2, 0, 138, 0, 0, 0, 0,
ax_anim 4, 0, 140, 0, 0, 0, 0,
ax_anim 2, 0, 138, 0, 0, 0, 0,
ax_anim 4, 0, 139, 0, 0, 0, 0,
ax_anim 2, 2, 138, 0, 0, 0, 0,
ax_anim 4, 0, 140, 0, 0, 0, 0,
ax_anim 2, 0, 138, 0, 0, 0, 0,
ax_anim 4, 0, 139, 0, 0, 0, 0,
ax_anim 2, 0, 138, 0, 0, 0, 0,
ax_anim_terminator
sDelcattyAnims_5_8:
ax_anim 4, 0, 142, 0, 0, 0, 0,
ax_anim 2, 0, 141, 0, 0, 0, 0,
ax_anim 4, 0, 143, 0, 0, 0, 0,
ax_anim 2, 0, 141, 0, 0, 0, 0,
ax_anim 4, 0, 142, 0, 0, 0, 0,
ax_anim 2, 2, 141, 0, 0, 0, 0,
ax_anim 4, 0, 143, 0, 0, 0, 0,
ax_anim 2, 0, 141, 0, 0, 0, 0,
ax_anim 4, 0, 142, 0, 0, 0, 0,
ax_anim 2, 0, 141, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sDelcattyAnims_6_1:
ax_anim 30, 0, 144, 0, 0, 0, 0,
ax_anim 35, 0, 145, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sDelcattyAnims_7_1:
ax_anim 2, 0, 146, 0, -2, 0, -2,
ax_anim 8, 0, 146, 0, -3, 0, -3,
ax_anim_terminator
sDelcattyAnims_7_2:
ax_anim 2, 0, 147, -2, -2, -2, -2,
ax_anim 8, 0, 147, -3, -3, -3, -3,
ax_anim_terminator
sDelcattyAnims_7_3:
ax_anim 2, 0, 148, -2, 0, -2, 0,
ax_anim 8, 0, 148, -3, 0, -3, 0,
ax_anim_terminator
sDelcattyAnims_7_4:
ax_anim 2, 0, 149, -2, 2, -2, 2,
ax_anim 8, 0, 149, -3, 3, -3, 3,
ax_anim_terminator
sDelcattyAnims_7_5:
ax_anim 2, 0, 150, 0, 2, 0, 2,
ax_anim 8, 0, 150, 0, 3, 0, 3,
ax_anim_terminator
sDelcattyAnims_7_6:
ax_anim 2, 0, 151, 2, 2, 2, 2,
ax_anim 8, 0, 151, 3, 3, 3, 3,
ax_anim_terminator
sDelcattyAnims_7_7:
ax_anim 2, 0, 152, 2, 0, 2, 0,
ax_anim 8, 0, 152, 3, 0, 3, 0,
ax_anim_terminator
sDelcattyAnims_7_8:
ax_anim 2, 0, 153, 2, -2, 2, -2,
ax_anim 8, 0, 153, 3, -3, 3, -3,
ax_anim_terminator
.align 2
sDelcattyAnims_8_1:
ax_anim 60, 0, 157, 0, 0, 0, 0,
ax_anim 10, 0, 154, 0, 0, 0, 0,
ax_anim 5, 0, 155, 0, 0, 0, 0,
ax_anim 5, 0, 156, 0, 0, 0, 0,
ax_anim 5, 0, 155, 0, 0, 0, 0,
ax_anim 5, 0, 156, 0, 0, 0, 0,
ax_anim 5, 0, 155, 0, 0, 0, 0,
ax_anim 5, 0, 156, 0, 0, 0, 0,
ax_anim 10, 0, 154, 0, 0, 0, 0,
ax_anim_terminator
sDelcattyAnims_8_2:
ax_anim 60, 0, 161, 0, 0, 0, 0,
ax_anim 10, 0, 158, 0, 0, 0, 0,
ax_anim 5, 0, 159, 0, 0, 0, 0,
ax_anim 5, 0, 160, 0, 0, 0, 0,
ax_anim 5, 0, 159, 0, 0, 0, 0,
ax_anim 5, 0, 160, 0, 0, 0, 0,
ax_anim 5, 0, 159, 0, 0, 0, 0,
ax_anim 5, 0, 160, 0, 0, 0, 0,
ax_anim 10, 0, 158, 0, 0, 0, 0,
ax_anim_terminator
sDelcattyAnims_8_3:
ax_anim 60, 0, 165, 0, 0, 0, 0,
ax_anim 10, 0, 162, 0, 0, 0, 0,
ax_anim 5, 0, 163, 0, 0, 0, 0,
ax_anim 5, 0, 164, 0, 0, 0, 0,
ax_anim 5, 0, 163, 0, 0, 0, 0,
ax_anim 5, 0, 164, 0, 0, 0, 0,
ax_anim 5, 0, 163, 0, 0, 0, 0,
ax_anim 5, 0, 164, 0, 0, 0, 0,
ax_anim 10, 0, 162, 0, 0, 0, 0,
ax_anim_terminator
sDelcattyAnims_8_4:
ax_anim 60, 0, 169, 0, 0, 0, 0,
ax_anim 10, 0, 166, 0, 0, 0, 0,
ax_anim 5, 0, 167, 0, 0, 0, 0,
ax_anim 5, 0, 168, 0, 0, 0, 0,
ax_anim 5, 0, 167, 0, 0, 0, 0,
ax_anim 5, 0, 168, 0, 0, 0, 0,
ax_anim 5, 0, 167, 0, 0, 0, 0,
ax_anim 5, 0, 168, 0, 0, 0, 0,
ax_anim 10, 0, 166, 0, 0, 0, 0,
ax_anim_terminator
sDelcattyAnims_8_5:
ax_anim 60, 0, 173, 0, 0, 0, 0,
ax_anim 10, 0, 170, 0, 0, 0, 0,
ax_anim 5, 0, 171, 0, 0, 0, 0,
ax_anim 5, 0, 172, 0, 0, 0, 0,
ax_anim 5, 0, 171, 0, 0, 0, 0,
ax_anim 5, 0, 172, 0, 0, 0, 0,
ax_anim 5, 0, 171, 0, 0, 0, 0,
ax_anim 5, 0, 172, 0, 0, 0, 0,
ax_anim 10, 0, 170, 0, 0, 0, 0,
ax_anim_terminator
sDelcattyAnims_8_6:
ax_anim 60, 0, 177, 0, 0, 0, 0,
ax_anim 10, 0, 174, 0, 0, 0, 0,
ax_anim 5, 0, 175, 0, 0, 0, 0,
ax_anim 5, 0, 176, 0, 0, 0, 0,
ax_anim 5, 0, 175, 0, 0, 0, 0,
ax_anim 5, 0, 176, 0, 0, 0, 0,
ax_anim 5, 0, 175, 0, 0, 0, 0,
ax_anim 5, 0, 176, 0, 0, 0, 0,
ax_anim 10, 0, 174, 0, 0, 0, 0,
ax_anim_terminator
sDelcattyAnims_8_7:
ax_anim 60, 0, 181, 0, 0, 0, 0,
ax_anim 10, 0, 178, 0, 0, 0, 0,
ax_anim 5, 0, 179, 0, 0, 0, 0,
ax_anim 5, 0, 180, 0, 0, 0, 0,
ax_anim 5, 0, 179, 0, 0, 0, 0,
ax_anim 5, 0, 180, 0, 0, 0, 0,
ax_anim 5, 0, 179, 0, 0, 0, 0,
ax_anim 5, 0, 180, 0, 0, 0, 0,
ax_anim 10, 0, 178, 0, 0, 0, 0,
ax_anim_terminator
sDelcattyAnims_8_8:
ax_anim 60, 0, 185, 0, 0, 0, 0,
ax_anim 10, 0, 182, 0, 0, 0, 0,
ax_anim 5, 0, 183, 0, 0, 0, 0,
ax_anim 5, 0, 184, 0, 0, 0, 0,
ax_anim 5, 0, 183, 0, 0, 0, 0,
ax_anim 5, 0, 184, 0, 0, 0, 0,
ax_anim 5, 0, 183, 0, 0, 0, 0,
ax_anim 5, 0, 184, 0, 0, 0, 0,
ax_anim 10, 0, 182, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sDelcattyAnims_9_1:
ax_anim 2, 0, 186, 0, 0, 0, 0,
ax_anim 1, 0, 187, 7, 4, 7, 4,
ax_anim 2, 0, 188, 10, 10, 10, 10,
ax_anim 2, 0, 189, 7, 16, 7, 16,
ax_anim 3, 0, 190, 0, 19, 0, 19,
ax_anim 2, 3, 191, -7, 16, -7, 16,
ax_anim 2, 0, 192, -10, 10, -10, 10,
ax_anim 1, 0, 193, -7, 4, -7, 4,
ax_anim 1, 0, 186, 0, 0, 0, 0,
ax_anim_terminator
sDelcattyAnims_9_2:
ax_anim 2, 0, 193, 0, 0, 0, 0,
ax_anim 1, 0, 186, 8, 0, 8, 0,
ax_anim 2, 0, 187, 17, 3, 17, 3,
ax_anim 2, 0, 188, 25, 10, 25, 10,
ax_anim 3, 0, 189, 23, 19, 23, 19,
ax_anim 2, 3, 190, 12, 19, 12, 19,
ax_anim 2, 0, 191, 3, 15, 3, 15,
ax_anim 1, 0, 192, 0, 7, 0, 7,
ax_anim 1, 0, 193, 0, 0, 0, 0,
ax_anim_terminator
sDelcattyAnims_9_3:
ax_anim 2, 0, 192, 0, 0, 0, 0,
ax_anim 1, 0, 193, 3, -5, 3, -5,
ax_anim 2, 0, 186, 11, -6, 11, -6,
ax_anim 2, 0, 187, 16, -5, 16, -5,
ax_anim 3, 0, 188, 24, 0, 24, 0,
ax_anim 2, 3, 189, 20, 4, 20, 4,
ax_anim 2, 0, 190, 12, 5, 12, 5,
ax_anim 1, 0, 191, 4, 5, 4, 5,
ax_anim 1, 0, 192, 0, 0, 0, 0,
ax_anim_terminator
sDelcattyAnims_9_4:
ax_anim 2, 0, 191, 0, 0, 0, 0,
ax_anim 1, 0, 192, -1, -8, -1, -8,
ax_anim 2, 0, 193, 4, -16, 4, -16,
ax_anim 2, 0, 186, 12, -22, 12, -22,
ax_anim 3, 0, 187, 23, -21, 23, -21,
ax_anim 2, 3, 188, 25, -14, 25, -14,
ax_anim 2, 0, 189, 19, -4, 19, -4,
ax_anim 1, 0, 190, 10, -1, 10, -1,
ax_anim 1, 0, 191, 0, 0, 0, 0,
ax_anim_terminator
sDelcattyAnims_9_5:
ax_anim 2, 0, 190, 0, 0, 0, 0,
ax_anim 1, 0, 191, -9, -2, -9, -2,
ax_anim 2, 0, 192, -11, -11, -11, -11,
ax_anim 2, 0, 193, -7, -18, -7, -18,
ax_anim 3, 0, 186, 0, -22, 0, -22,
ax_anim 2, 3, 187, 7, -18, 7, -18,
ax_anim 2, 0, 188, 11, -11, 11, -11,
ax_anim 1, 0, 189, 9, -2, 9, -2,
ax_anim 1, 0, 190, 0, 0, 0, 0,
ax_anim_terminator
sDelcattyAnims_9_6:
ax_anim 2, 0, 189, 0, 0, 0, 0,
ax_anim 1, 0, 188, 1, -8, 1, -8,
ax_anim 2, 0, 187, -4, -16, -4, -16,
ax_anim 2, 0, 186, -12, -22, -12, -22,
ax_anim 3, 0, 193, -23, -21, -23, -21,
ax_anim 2, 3, 192, -25, -14, -25, -14,
ax_anim 2, 0, 191, -19, -5, -19, -5,
ax_anim 1, 0, 190, -10, -1, -10, -1,
ax_anim 1, 0, 189, 0, 0, 0, 0,
ax_anim_terminator
sDelcattyAnims_9_7:
ax_anim 2, 0, 188, 0, 0, 0, 0,
ax_anim 1, 0, 187, -3, -5, -3, -5,
ax_anim 2, 0, 186, -11, -6, -11, -6,
ax_anim 2, 0, 193, -16, -5, -16, -5,
ax_anim 3, 0, 192, -24, 0, -24, 0,
ax_anim 2, 3, 191, -20, 4, -20, 4,
ax_anim 2, 0, 190, -12, 5, -12, 5,
ax_anim 1, 0, 189, -4, 5, -4, 5,
ax_anim 1, 0, 188, 0, 0, 0, 0,
ax_anim_terminator
sDelcattyAnims_9_8:
ax_anim 2, 0, 187, 0, 0, 0, 0,
ax_anim 1, 0, 186, -8, 0, -8, 0,
ax_anim 2, 0, 193, -17, 3, -17, 3,
ax_anim 2, 0, 192, -25, 10, -25, 10,
ax_anim 3, 0, 191, -23, 19, -23, 19,
ax_anim 2, 3, 190, -12, 19, -12, 19,
ax_anim 2, 0, 189, -3, 15, -3, 15,
ax_anim 1, 0, 188, 0, 7, 0, 7,
ax_anim 1, 0, 187, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sDelcattyAnims_10_1:
ax_anim 2, 0, 194, 0, 0, 0, 0,
ax_anim 2, 0, 194, 6, 0, 6, 0,
ax_anim 2, 0, 194, -6, 0, -6, 0,
ax_anim 2, 0, 194, 10, 0, 10, 0,
ax_anim 2, 0, 194, -10, 0, -10, 0,
ax_anim 2, 0, 194, 12, 0, 12, 0,
ax_anim 3, 0, 194, -12, 0, -12, 0,
ax_anim 3, 0, 194, 13, 0, 13, 0,
ax_anim 3, 0, 194, -13, 0, -13, 0,
ax_anim 2, 0, 194, 12, 0, 12, 0,
ax_anim 3, 0, 194, -12, 0, -12, 0,
ax_anim 2, 0, 194, 10, 0, 10, 0,
ax_anim 2, 0, 194, -10, 0, -10, 0,
ax_anim 2, 0, 194, 6, 0, 6, 0,
ax_anim 2, 0, 194, -6, 0, -6, 0,
ax_anim 2, 0, 194, 0, 0, 0, 0,
ax_anim_terminator
sDelcattyAnims_10_2:
ax_anim 2, 0, 195, 0, 0, 0, 0,
ax_anim 2, 0, 195, 6, -6, 6, -6,
ax_anim 2, 0, 195, -6, 6, -6, 6,
ax_anim 2, 0, 195, 10, -10, 10, -10,
ax_anim 2, 0, 195, -10, 10, -10, 10,
ax_anim 2, 0, 195, 12, -12, 12, -12,
ax_anim 3, 0, 195, -12, 12, -12, 12,
ax_anim 3, 0, 195, 13, -13, 13, -13,
ax_anim 3, 0, 195, -13, 13, -13, 13,
ax_anim 2, 0, 195, 12, -12, 12, -12,
ax_anim 3, 0, 195, -12, 12, -12, 12,
ax_anim 2, 0, 195, 10, -10, 10, -10,
ax_anim 2, 0, 195, -10, 10, -10, 10,
ax_anim 2, 0, 195, 6, -6, 6, -6,
ax_anim 2, 0, 195, -6, 6, -6, 6,
ax_anim 2, 0, 195, 0, 0, 0, 0,
ax_anim_terminator
sDelcattyAnims_10_3:
ax_anim 2, 0, 196, 0, 0, 0, 0,
ax_anim 2, 0, 196, 0, -6, 0, -6,
ax_anim 2, 0, 196, 0, 6, 0, 6,
ax_anim 2, 0, 196, 0, -10, 0, -10,
ax_anim 2, 0, 196, 0, 10, 0, 10,
ax_anim 2, 0, 196, 0, -12, 0, -12,
ax_anim 3, 0, 196, 0, 12, 0, 12,
ax_anim 3, 0, 196, 0, -13, 0, -13,
ax_anim 3, 0, 196, 0, 13, 0, 13,
ax_anim 2, 0, 196, 0, -12, 0, -12,
ax_anim 3, 0, 196, 0, 12, 0, 12,
ax_anim 2, 0, 196, 0, -10, 0, -10,
ax_anim 2, 0, 196, 0, 10, 0, 10,
ax_anim 2, 0, 196, 0, -6, 0, -6,
ax_anim 2, 0, 196, 0, 6, 0, 6,
ax_anim 2, 0, 196, 0, 0, 0, 0,
ax_anim_terminator
sDelcattyAnims_10_4:
ax_anim 2, 0, 197, 0, 0, 0, 0,
ax_anim 2, 0, 197, -6, -6, -6, -6,
ax_anim 2, 0, 197, 6, 6, 6, 6,
ax_anim 2, 0, 197, -10, -10, -10, -10,
ax_anim 2, 0, 197, 10, 10, 10, 10,
ax_anim 2, 0, 197, -12, -12, -12, -12,
ax_anim 3, 0, 197, 12, 12, 12, 12,
ax_anim 3, 0, 197, -13, -13, -13, -13,
ax_anim 3, 0, 197, 13, 13, 13, 13,
ax_anim 2, 0, 197, -12, -12, -12, -12,
ax_anim 3, 0, 197, 12, 12, 12, 12,
ax_anim 2, 0, 197, -10, -10, -10, -10,
ax_anim 2, 0, 197, 10, 10, 10, 10,
ax_anim 2, 0, 197, -6, -6, -6, -6,
ax_anim 2, 0, 197, 6, 6, 6, 6,
ax_anim 2, 0, 197, 0, 0, 0, 0,
ax_anim_terminator
sDelcattyAnims_10_5:
ax_anim 2, 0, 198, 0, 0, 0, 0,
ax_anim 2, 0, 198, 6, 0, 6, 0,
ax_anim 2, 0, 198, -6, 0, -6, 0,
ax_anim 2, 0, 198, 10, 0, 10, 0,
ax_anim 2, 0, 198, -10, 0, -10, 0,
ax_anim 2, 0, 198, 12, 0, 12, 0,
ax_anim 3, 0, 198, -12, 0, -12, 0,
ax_anim 3, 0, 198, 13, 0, 13, 0,
ax_anim 3, 0, 198, -13, 0, -13, 0,
ax_anim 2, 0, 198, 12, 0, 12, 0,
ax_anim 3, 0, 198, -12, 0, -12, 0,
ax_anim 2, 0, 198, 10, 0, 10, 0,
ax_anim 2, 0, 198, -10, 0, -10, 0,
ax_anim 2, 0, 198, 6, 0, 6, 0,
ax_anim 2, 0, 198, -6, 0, -6, 0,
ax_anim 2, 0, 198, 0, 0, 0, 0,
ax_anim_terminator
sDelcattyAnims_10_6:
ax_anim 2, 0, 199, 0, 0, 0, 0,
ax_anim 2, 0, 199, 6, -6, 6, -6,
ax_anim 2, 0, 199, -6, 6, -6, 6,
ax_anim 2, 0, 199, 10, -10, 10, -10,
ax_anim 2, 0, 199, -10, 10, -10, 10,
ax_anim 2, 0, 199, 12, -12, 12, -12,
ax_anim 3, 0, 199, -12, 12, -12, 12,
ax_anim 3, 0, 199, 13, -13, 13, -13,
ax_anim 3, 0, 199, -13, 13, -13, 13,
ax_anim 2, 0, 199, 12, -12, 12, -12,
ax_anim 3, 0, 199, -12, 12, -12, 12,
ax_anim 2, 0, 199, 10, -10, 10, -10,
ax_anim 2, 0, 199, -10, 10, -10, 10,
ax_anim 2, 0, 199, 6, -6, 6, -6,
ax_anim 2, 0, 199, -6, 6, -6, 6,
ax_anim 2, 0, 199, 0, 0, 0, 0,
ax_anim_terminator
sDelcattyAnims_10_7:
ax_anim 2, 0, 200, 0, 0, 0, 0,
ax_anim 2, 0, 200, 0, -6, 0, -6,
ax_anim 2, 0, 200, 0, 6, 0, 6,
ax_anim 2, 0, 200, 0, -10, 0, -10,
ax_anim 2, 0, 200, 0, 10, 0, 10,
ax_anim 2, 0, 200, 0, -12, 0, -12,
ax_anim 3, 0, 200, 0, 12, 0, 12,
ax_anim 3, 0, 200, 0, -13, 0, -13,
ax_anim 3, 0, 200, 0, 13, 0, 13,
ax_anim 2, 0, 200, 0, -12, 0, -12,
ax_anim 3, 0, 200, 0, 12, 0, 12,
ax_anim 2, 0, 200, 0, -10, 0, -10,
ax_anim 2, 0, 200, 0, 10, 0, 10,
ax_anim 2, 0, 200, 0, -6, 0, -6,
ax_anim 2, 0, 200, 0, 6, 0, 6,
ax_anim 2, 0, 200, 0, 0, 0, 0,
ax_anim_terminator
sDelcattyAnims_10_8:
ax_anim 2, 0, 201, 0, 0, 0, 0,
ax_anim 2, 0, 201, -6, -6, -6, -6,
ax_anim 2, 0, 201, 6, 6, 6, 6,
ax_anim 2, 0, 201, -10, -10, -10, -10,
ax_anim 2, 0, 201, 10, 10, 10, 10,
ax_anim 2, 0, 201, -12, -12, -12, -12,
ax_anim 3, 0, 201, 12, 12, 12, 12,
ax_anim 3, 0, 201, -13, -13, -13, -13,
ax_anim 3, 0, 201, 13, 13, 13, 13,
ax_anim 2, 0, 201, -12, -12, -12, -12,
ax_anim 3, 0, 201, 12, 12, 12, 12,
ax_anim 2, 0, 201, -10, -10, -10, -10,
ax_anim 2, 0, 201, 10, 10, 10, 10,
ax_anim 2, 0, 201, -6, -6, -6, -6,
ax_anim 2, 0, 201, 6, 6, 6, 6,
ax_anim 2, 0, 201, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sDelcattyAnims_11_1:
ax_anim 2, 0, 202, 0, 0, 0, 0,
ax_anim 1, 0, 203, 0, -10, 0, 0,
ax_anim 2, 0, 203, 0, -16, 0, 0,
ax_anim 3, 0, 203, 0, -19, 0, 0,
ax_anim 4, 0, 203, 0, -20, 0, 0,
ax_anim 4, 0, 202, 0, -24, 0, 0,
ax_anim 3, 0, 204, 0, -24, 0, 0,
ax_anim 2, 0, 204, 0, -20, 0, 0,
ax_anim 1, 0, 204, 0, -12, 0, 0,
ax_anim 2, 2, 204, 0, 2, 0, 0,
ax_anim_terminator
sDelcattyAnims_11_2:
ax_anim 2, 0, 205, 0, 0, 0, 0,
ax_anim 1, 0, 206, 0, -10, 0, 0,
ax_anim 2, 0, 206, 0, -16, 0, 0,
ax_anim 3, 0, 206, 0, -20, 0, 0,
ax_anim 4, 0, 206, 0, -21, 0, 0,
ax_anim 4, 0, 205, 0, -22, 0, 0,
ax_anim 3, 0, 207, 0, -23, 0, 0,
ax_anim 2, 0, 207, 0, -19, 0, 0,
ax_anim 1, 0, 207, 0, -12, 0, 0,
ax_anim 2, 2, 207, 0, 0, 0, 0,
ax_anim_terminator
sDelcattyAnims_11_3:
ax_anim 2, 0, 208, 0, 0, 0, 0,
ax_anim 1, 0, 209, 0, -10, 0, 0,
ax_anim 2, 0, 209, 0, -16, 0, 0,
ax_anim 3, 0, 209, 0, -20, 0, 0,
ax_anim 4, 0, 209, 0, -21, 0, 0,
ax_anim 4, 0, 208, 0, -22, 0, 0,
ax_anim 3, 0, 210, 0, -23, 0, 0,
ax_anim 2, 0, 210, 0, -19, 0, 0,
ax_anim 1, 0, 210, 0, -12, 0, 0,
ax_anim 2, 2, 210, 0, 0, 0, 0,
ax_anim_terminator
sDelcattyAnims_11_4:
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 1, 0, 212, 0, -10, 0, 0,
ax_anim 2, 0, 212, 0, -16, 0, 0,
ax_anim 3, 0, 212, 0, -20, 0, 0,
ax_anim 4, 0, 212, 0, -21, 0, 0,
ax_anim 4, 0, 211, 0, -22, 0, 0,
ax_anim 3, 0, 213, 0, -23, 0, 0,
ax_anim 2, 0, 213, 0, -20, 0, 0,
ax_anim 1, 0, 213, 0, -11, 0, 0,
ax_anim 2, 2, 213, 0, 0, 0, 0,
ax_anim_terminator
sDelcattyAnims_11_5:
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 1, 0, 215, 0, -10, 0, 0,
ax_anim 2, 0, 215, 0, -16, 0, 0,
ax_anim 3, 0, 215, 0, -20, 0, 0,
ax_anim 4, 0, 215, 0, -21, 0, 0,
ax_anim 4, 0, 214, 0, -22, 0, 0,
ax_anim 3, 0, 216, 0, -21, 0, 0,
ax_anim 2, 0, 216, 0, -18, 0, 0,
ax_anim 1, 0, 216, 0, -12, 0, 0,
ax_anim 2, 2, 216, 0, 0, 0, 0,
ax_anim_terminator
sDelcattyAnims_11_6:
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 1, 0, 218, 0, -10, 0, 0,
ax_anim 2, 0, 218, 0, -16, 0, 0,
ax_anim 3, 0, 218, 0, -20, 0, 0,
ax_anim 4, 0, 218, 0, -21, 0, 0,
ax_anim 4, 0, 217, 0, -22, 0, 0,
ax_anim 3, 0, 219, 0, -23, 0, 0,
ax_anim 2, 0, 219, 0, -20, 0, 0,
ax_anim 1, 0, 219, 0, -11, 0, 0,
ax_anim 2, 2, 219, 0, 0, 0, 0,
ax_anim_terminator
sDelcattyAnims_11_7:
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 1, 0, 221, 0, -10, 0, 0,
ax_anim 2, 0, 221, 0, -16, 0, 0,
ax_anim 3, 0, 221, 0, -20, 0, 0,
ax_anim 4, 0, 221, 0, -21, 0, 0,
ax_anim 4, 0, 220, 0, -22, 0, 0,
ax_anim 3, 0, 222, 0, -23, 0, 0,
ax_anim 2, 0, 222, 0, -19, 0, 0,
ax_anim 1, 0, 222, 0, -12, 0, 0,
ax_anim 2, 2, 222, 0, 0, 0, 0,
ax_anim_terminator
sDelcattyAnims_11_8:
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 1, 0, 224, 0, -10, 0, 0,
ax_anim 2, 0, 224, 0, -16, 0, 0,
ax_anim 3, 0, 224, 0, -20, 0, 0,
ax_anim 4, 0, 224, 0, -21, 0, 0,
ax_anim 4, 0, 223, 0, -22, 0, 0,
ax_anim 3, 0, 225, 0, -23, 0, 0,
ax_anim 2, 0, 225, 0, -19, 0, 0,
ax_anim 1, 0, 225, 0, -12, 0, 0,
ax_anim 2, 2, 225, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sDelcattyAnims_12_1:
ax_anim 2, 0, 226, 1, 0, 1, 0,
ax_anim 2, 0, 226, 0, 0, 0, 0,
ax_anim 2, 0, 226, 1, 0, 1, 0,
ax_anim 2, 0, 226, 0, 0, 0, 0,
ax_anim 2, 0, 226, 1, 0, 1, 0,
ax_anim 2, 2, 226, 0, 0, 0, 0,
ax_anim 2, 0, 226, 1, 0, 1, 0,
ax_anim 2, 0, 226, 0, 0, 0, 0,
ax_anim 2, 0, 226, 1, 0, 1, 0,
ax_anim 2, 1, 226, 0, 0, 0, 0,
ax_anim_terminator
sDelcattyAnims_12_2:
ax_anim 2, 0, 233, 1, -1, 1, -1,
ax_anim 2, 0, 233, 0, 0, 0, 0,
ax_anim 2, 0, 233, 1, -1, 1, -1,
ax_anim 2, 0, 233, 0, 0, 0, 0,
ax_anim 2, 0, 233, 1, -1, 1, -1,
ax_anim 2, 2, 233, 0, 0, 0, 0,
ax_anim 2, 0, 233, 1, -1, 1, -1,
ax_anim 2, 0, 233, 0, 0, 0, 0,
ax_anim 2, 0, 233, 1, -1, 1, -1,
ax_anim 2, 1, 233, 0, 0, 0, 0,
ax_anim_terminator
sDelcattyAnims_12_3:
ax_anim 2, 0, 232, 0, -1, 0, -1,
ax_anim 2, 0, 232, 0, 0, 0, 0,
ax_anim 2, 0, 232, 0, -1, 0, -1,
ax_anim 2, 0, 232, 0, 0, 0, 0,
ax_anim 2, 0, 232, 0, -1, 0, -1,
ax_anim 2, 2, 232, 0, 0, 0, 0,
ax_anim 2, 0, 232, 0, -1, 0, -1,
ax_anim 2, 0, 232, 0, 0, 0, 0,
ax_anim 2, 0, 232, 0, -1, 0, -1,
ax_anim 2, 1, 232, 0, 0, 0, 0,
ax_anim_terminator
sDelcattyAnims_12_4:
ax_anim 2, 0, 231, -1, -1, -1, -1,
ax_anim 2, 0, 231, 0, 0, 0, 0,
ax_anim 2, 0, 231, -1, -1, -1, -1,
ax_anim 2, 0, 231, 0, 0, 0, 0,
ax_anim 2, 0, 231, -1, -1, -1, -1,
ax_anim 2, 2, 231, 0, 0, 0, 0,
ax_anim 2, 0, 231, -1, -1, -1, -1,
ax_anim 2, 0, 231, 0, 0, 0, 0,
ax_anim 2, 0, 231, -1, -1, -1, -1,
ax_anim 2, 1, 231, 0, 0, 0, 0,
ax_anim_terminator
sDelcattyAnims_12_5:
ax_anim 2, 0, 230, 1, 0, 1, 0,
ax_anim 2, 0, 230, 0, 0, 0, 0,
ax_anim 2, 0, 230, 1, 0, 1, 0,
ax_anim 2, 0, 230, 0, 0, 0, 0,
ax_anim 2, 0, 230, 1, 0, 1, 0,
ax_anim 2, 2, 230, 0, 0, 0, 0,
ax_anim 2, 0, 230, 1, 0, 1, 0,
ax_anim 2, 0, 230, 0, 0, 0, 0,
ax_anim 2, 0, 230, 1, 0, 1, 0,
ax_anim 2, 1, 230, 0, 0, 0, 0,
ax_anim_terminator
sDelcattyAnims_12_6:
ax_anim 2, 0, 229, 1, -1, 1, -1,
ax_anim 2, 0, 229, 0, 0, 0, 0,
ax_anim 2, 0, 229, 1, -1, 1, -1,
ax_anim 2, 0, 229, 0, 0, 0, 0,
ax_anim 2, 0, 229, 1, -1, 1, -1,
ax_anim 2, 2, 229, 0, 0, 0, 0,
ax_anim 2, 0, 229, 1, -1, 1, -1,
ax_anim 2, 0, 229, 0, 0, 0, 0,
ax_anim 2, 0, 229, 1, -1, 1, -1,
ax_anim 2, 1, 229, 0, 0, 0, 0,
ax_anim_terminator
sDelcattyAnims_12_7:
ax_anim 2, 0, 228, 0, -1, 0, -1,
ax_anim 2, 0, 228, 0, 0, 0, 0,
ax_anim 2, 0, 228, 0, -1, 0, -1,
ax_anim 2, 0, 228, 0, 0, 0, 0,
ax_anim 2, 0, 228, 0, -1, 0, -1,
ax_anim 2, 2, 228, 0, 0, 0, 0,
ax_anim 2, 0, 228, 0, -1, 0, -1,
ax_anim 2, 0, 228, 0, 0, 0, 0,
ax_anim 2, 0, 228, 0, -1, 0, -1,
ax_anim 2, 1, 228, 0, 0, 0, 0,
ax_anim_terminator
sDelcattyAnims_12_8:
ax_anim 2, 0, 227, -1, -1, -1, -1,
ax_anim 2, 0, 227, 0, 0, 0, 0,
ax_anim 2, 0, 227, -1, -1, -1, -1,
ax_anim 2, 0, 227, 0, 0, 0, 0,
ax_anim 2, 0, 227, -1, -1, -1, -1,
ax_anim 2, 2, 227, 0, 0, 0, 0,
ax_anim 2, 0, 227, -1, -1, -1, -1,
ax_anim 2, 0, 227, 0, 0, 0, 0,
ax_anim 2, 0, 227, -1, -1, -1, -1,
ax_anim 2, 1, 227, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sDelcattyAnims_13_1:
ax_anim 2, 0, 234, 0, 0, 0, 0,
ax_anim 2, 0, 235, 0, 0, 0, 0,
ax_anim 2, 0, 236, 0, 0, 0, 0,
ax_anim 2, 0, 237, 0, 0, 0, 0,
ax_anim 2, 0, 238, 0, 0, 0, 0,
ax_anim 2, 0, 239, 0, 0, 0, 0,
ax_anim 2, 0, 240, 0, 0, 0, 0,
ax_anim 2, 0, 241, 0, 0, 0, 0,
ax_anim 2, 2, 234, 0, 0, 0, 0,
ax_anim_terminator
sDelcattyAnims_13_2:
ax_anim 2, 0, 241, 0, 0, 0, 0,
ax_anim 2, 0, 234, 0, 0, 0, 0,
ax_anim 2, 0, 235, 0, 0, 0, 0,
ax_anim 2, 0, 236, 0, 0, 0, 0,
ax_anim 2, 0, 237, 0, 0, 0, 0,
ax_anim 2, 0, 238, 0, 0, 0, 0,
ax_anim 2, 0, 239, 0, 0, 0, 0,
ax_anim 2, 0, 240, 0, 0, 0, 0,
ax_anim 2, 2, 241, 0, 0, 0, 0,
ax_anim_terminator
sDelcattyAnims_13_3:
ax_anim 2, 0, 240, 0, 0, 0, 0,
ax_anim 2, 0, 241, 0, 0, 0, 0,
ax_anim 2, 0, 234, 0, 0, 0, 0,
ax_anim 2, 0, 235, 0, 0, 0, 0,
ax_anim 2, 0, 236, 0, 0, 0, 0,
ax_anim 2, 0, 237, 0, 0, 0, 0,
ax_anim 2, 0, 238, 0, 0, 0, 0,
ax_anim 2, 0, 239, 0, 0, 0, 0,
ax_anim 2, 2, 240, 0, 0, 0, 0,
ax_anim_terminator
sDelcattyAnims_13_4:
ax_anim 2, 0, 239, 0, 0, 0, 0,
ax_anim 2, 0, 240, 0, 0, 0, 0,
ax_anim 2, 0, 241, 0, 0, 0, 0,
ax_anim 2, 0, 234, 0, 0, 0, 0,
ax_anim 2, 0, 235, 0, 0, 0, 0,
ax_anim 2, 0, 236, 0, 0, 0, 0,
ax_anim 2, 0, 237, 0, 0, 0, 0,
ax_anim 2, 0, 238, 0, 0, 0, 0,
ax_anim 2, 2, 239, 0, 0, 0, 0,
ax_anim_terminator
sDelcattyAnims_13_5:
ax_anim 2, 0, 238, 0, 0, 0, 0,
ax_anim 2, 0, 239, 0, 0, 0, 0,
ax_anim 2, 0, 240, 0, 0, 0, 0,
ax_anim 2, 0, 241, 0, 0, 0, 0,
ax_anim 2, 0, 234, 0, 0, 0, 0,
ax_anim 2, 0, 235, 0, 0, 0, 0,
ax_anim 2, 0, 236, 0, 0, 0, 0,
ax_anim 2, 0, 237, 0, 0, 0, 0,
ax_anim 2, 2, 238, 0, 0, 0, 0,
ax_anim_terminator
sDelcattyAnims_13_6:
ax_anim 2, 0, 237, 0, 0, 0, 0,
ax_anim 2, 0, 238, 0, 0, 0, 0,
ax_anim 2, 0, 239, 0, 0, 0, 0,
ax_anim 2, 0, 240, 0, 0, 0, 0,
ax_anim 2, 0, 241, 0, 0, 0, 0,
ax_anim 2, 0, 234, 0, 0, 0, 0,
ax_anim 2, 0, 235, 0, 0, 0, 0,
ax_anim 2, 0, 236, 0, 0, 0, 0,
ax_anim 2, 2, 237, 0, 0, 0, 0,
ax_anim_terminator
sDelcattyAnims_13_7:
ax_anim 2, 0, 236, 0, 0, 0, 0,
ax_anim 2, 0, 237, 0, 0, 0, 0,
ax_anim 2, 0, 238, 0, 0, 0, 0,
ax_anim 2, 0, 239, 0, 0, 0, 0,
ax_anim 2, 0, 240, 0, 0, 0, 0,
ax_anim 2, 0, 241, 0, 0, 0, 0,
ax_anim 2, 0, 234, 0, 0, 0, 0,
ax_anim 2, 0, 235, 0, 0, 0, 0,
ax_anim 2, 2, 236, 0, 0, 0, 0,
ax_anim_terminator
sDelcattyAnims_13_8:
ax_anim 2, 0, 235, 0, 0, 0, 0,
ax_anim 2, 0, 236, 0, 0, 0, 0,
ax_anim 2, 0, 237, 0, 0, 0, 0,
ax_anim 2, 0, 238, 0, 0, 0, 0,
ax_anim 2, 0, 239, 0, 0, 0, 0,
ax_anim 2, 0, 240, 0, 0, 0, 0,
ax_anim 2, 0, 241, 0, 0, 0, 0,
ax_anim 2, 0, 234, 0, 0, 0, 0,
ax_anim 2, 2, 235, 0, 0, 0, 0,
ax_anim_terminator
sDelcattyGfx1:
.incbin "baserom.gba", 0x123E058, 0x200
sDelcattySprites1:
ax_sprite sDelcattyGfx1, 0x200
ax_sprite_terminator
sDelcattyGfx2:
.incbin "baserom.gba", 0x123E268, 0x200
sDelcattySprites2:
ax_sprite sDelcattyGfx2, 0x200
ax_sprite_terminator
sDelcattyGfx3:
.incbin "baserom.gba", 0x123E478, 0x200
sDelcattySprites3:
ax_sprite sDelcattyGfx3, 0x200
ax_sprite_terminator
sDelcattyGfx4:
.incbin "baserom.gba", 0x123E688, 0x200
sDelcattySprites4:
ax_sprite sDelcattyGfx4, 0x200
ax_sprite_terminator
sDelcattyGfx5:
.incbin "baserom.gba", 0x123E898, 0x200
sDelcattySprites5:
ax_sprite sDelcattyGfx5, 0x200
ax_sprite_terminator
sDelcattyGfx6:
.incbin "baserom.gba", 0x123EAA8, 0x200
sDelcattySprites6:
ax_sprite sDelcattyGfx6, 0x200
ax_sprite_terminator
sDelcattyGfx7:
.incbin "baserom.gba", 0x123ECB8, 0x200
sDelcattySprites7:
ax_sprite sDelcattyGfx7, 0x200
ax_sprite_terminator
sDelcattyGfx8:
.incbin "baserom.gba", 0x123EEC8, 0x200
sDelcattySprites8:
ax_sprite sDelcattyGfx8, 0x200
ax_sprite_terminator
sDelcattyGfx9:
.incbin "baserom.gba", 0x123F0D8, 0x200
sDelcattySprites9:
ax_sprite sDelcattyGfx9, 0x200
ax_sprite_terminator
sDelcattyGfx10:
.incbin "baserom.gba", 0x123F2E8, 0x200
sDelcattySprites10:
ax_sprite sDelcattyGfx10, 0x200
ax_sprite_terminator
sDelcattyGfx11:
.incbin "baserom.gba", 0x123F4F8, 0x200
sDelcattySprites11:
ax_sprite sDelcattyGfx11, 0x200
ax_sprite_terminator
sDelcattyGfx12:
.incbin "baserom.gba", 0x123F708, 0x200
sDelcattySprites12:
ax_sprite sDelcattyGfx12, 0x200
ax_sprite_terminator
sDelcattyGfx13:
.incbin "baserom.gba", 0x123F918, 0x200
sDelcattySprites13:
ax_sprite sDelcattyGfx13, 0x200
ax_sprite_terminator
sDelcattyGfx14:
.incbin "baserom.gba", 0x123FB28, 0x200
sDelcattySprites14:
ax_sprite sDelcattyGfx14, 0x200
ax_sprite_terminator
sDelcattyGfx15:
.incbin "baserom.gba", 0x123FD38, 0x200
sDelcattySprites15:
ax_sprite sDelcattyGfx15, 0x200
ax_sprite_terminator
sDelcattyGfx16:
.incbin "baserom.gba", 0x123FF48, 0x160
sDelcattyGfx16_1:
.incbin "baserom.gba", 0x12400A8, 0x40
sDelcattySprites16:
ax_sprite sDelcattyGfx16, 0x160
ax_sprite 0, 0x40
ax_sprite sDelcattyGfx16_1, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sDelcattyGfx17:
.incbin "baserom.gba", 0x1240110, 0x40
sDelcattyGfx17_1:
.incbin "baserom.gba", 0x1240150, 0x80
sDelcattyGfx17_2:
.incbin "baserom.gba", 0x12401D0, 0x40
sDelcattyGfx17_3:
.incbin "baserom.gba", 0x1240210, 0x40
sDelcattySprites17:
ax_sprite 0, 0x20
ax_sprite sDelcattyGfx17, 0x40
ax_sprite 0, 0x20
ax_sprite sDelcattyGfx17_1, 0x80
ax_sprite 0, 0x20
ax_sprite sDelcattyGfx17_2, 0x40
ax_sprite 0, 0x40
ax_sprite sDelcattyGfx17_3, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sDelcattyGfx18:
.incbin "baserom.gba", 0x12402A0, 0x160
sDelcattyGfx18_1:
.incbin "baserom.gba", 0x1240400, 0x40
sDelcattySprites18:
ax_sprite sDelcattyGfx18, 0x160
ax_sprite 0, 0x40
ax_sprite sDelcattyGfx18_1, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sDelcattyGfx19:
.incbin "baserom.gba", 0x1240468, 0x60
sDelcattyGfx19_1:
.incbin "baserom.gba", 0x12404C8, 0x60
sDelcattyGfx19_2:
.incbin "baserom.gba", 0x1240528, 0x60
sDelcattyGfx19_3:
.incbin "baserom.gba", 0x1240588, 0x40
sDelcattySprites19:
ax_sprite 0, 0x20
ax_sprite sDelcattyGfx19, 0x60
ax_sprite 0, 0x20
ax_sprite sDelcattyGfx19_1, 0x60
ax_sprite 0, 0x20
ax_sprite sDelcattyGfx19_2, 0x60
ax_sprite 0, 0x20
ax_sprite sDelcattyGfx19_3, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sDelcattyGfx20:
.incbin "baserom.gba", 0x1240618, 0x160
sDelcattyGfx20_1:
.incbin "baserom.gba", 0x1240778, 0x60
sDelcattySprites20:
ax_sprite sDelcattyGfx20, 0x160
ax_sprite 0, 0x20
ax_sprite sDelcattyGfx20_1, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sDelcattyGfx21:
.incbin "baserom.gba", 0x1240800, 0x60
sDelcattyGfx21_1:
.incbin "baserom.gba", 0x1240860, 0x60
sDelcattyGfx21_2:
.incbin "baserom.gba", 0x12408C0, 0x60
sDelcattyGfx21_3:
.incbin "baserom.gba", 0x1240920, 0x40
sDelcattySprites21:
ax_sprite 0, 0x20
ax_sprite sDelcattyGfx21, 0x60
ax_sprite 0, 0x20
ax_sprite sDelcattyGfx21_1, 0x60
ax_sprite 0, 0x20
ax_sprite sDelcattyGfx21_2, 0x60
ax_sprite 0, 0x20
ax_sprite sDelcattyGfx21_3, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sDelcattyGfx22:
.incbin "baserom.gba", 0x12409B0, 0x40
sDelcattyGfx22_1:
.incbin "baserom.gba", 0x12409F0, 0xE0
sDelcattyGfx22_2:
.incbin "baserom.gba", 0x1240AD0, 0x40
sDelcattySprites22:
ax_sprite 0, 0x20
ax_sprite sDelcattyGfx22, 0x40
ax_sprite 0, 0x40
ax_sprite sDelcattyGfx22_1, 0xe0
ax_sprite 0, 0x20
ax_sprite sDelcattyGfx22_2, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sDelcattyGfx23:
.incbin "baserom.gba", 0x1240B50, 0x20
sDelcattyGfx23_1:
.incbin "baserom.gba", 0x1240B70, 0x180
sDelcattySprites23:
ax_sprite 0, 0x20
ax_sprite sDelcattyGfx23, 0x20
ax_sprite 0, 0x20
ax_sprite sDelcattyGfx23_1, 0x180
ax_sprite 0, 0x20
ax_sprite_terminator
sDelcattyGfx24:
.incbin "baserom.gba", 0x1240D20, 0x40
sDelcattyGfx24_1:
.incbin "baserom.gba", 0x1240D60, 0x60
sDelcattyGfx24_2:
.incbin "baserom.gba", 0x1240DC0, 0x60
sDelcattyGfx24_3:
.incbin "baserom.gba", 0x1240E20, 0x40
sDelcattySprites24:
ax_sprite 0, 0x20
ax_sprite sDelcattyGfx24, 0x40
ax_sprite 0, 0x40
ax_sprite sDelcattyGfx24_1, 0x60
ax_sprite 0, 0x20
ax_sprite sDelcattyGfx24_2, 0x60
ax_sprite 0, 0x20
ax_sprite sDelcattyGfx24_3, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sDelcattyGfx25:
.incbin "baserom.gba", 0x1240EB0, 0x60
sDelcattyGfx25_1:
.incbin "baserom.gba", 0x1240F10, 0x60
sDelcattyGfx25_2:
.incbin "baserom.gba", 0x1240F70, 0x60
sDelcattyGfx25_3:
.incbin "baserom.gba", 0x1240FD0, 0x60
sDelcattySprites25:
ax_sprite 0, 0x20
ax_sprite sDelcattyGfx25, 0x60
ax_sprite 0, 0x20
ax_sprite sDelcattyGfx25_1, 0x60
ax_sprite 0, 0x20
ax_sprite sDelcattyGfx25_2, 0x60
ax_sprite 0, 0x20
ax_sprite sDelcattyGfx25_3, 0x60
ax_sprite_terminator
sDelcattyGfx26:
.incbin "baserom.gba", 0x1241078, 0x40
sDelcattyGfx26_1:
.incbin "baserom.gba", 0x12410B8, 0x100
sDelcattyGfx26_2:
.incbin "baserom.gba", 0x12411B8, 0x40
sDelcattySprites26:
ax_sprite 0, 0x20
ax_sprite sDelcattyGfx26, 0x40
ax_sprite 0, 0x20
ax_sprite sDelcattyGfx26_1, 0x100
ax_sprite 0, 0x20
ax_sprite sDelcattyGfx26_2, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sDelcattyGfx27:
.incbin "baserom.gba", 0x1241238, 0x100
sDelcattyGfx27_1:
.incbin "baserom.gba", 0x1241338, 0x60
sDelcattyGfx27_2:
.incbin "baserom.gba", 0x1241398, 0x60
sDelcattySprites27:
ax_sprite sDelcattyGfx27, 0x100
ax_sprite 0, 0x20
ax_sprite sDelcattyGfx27_1, 0x60
ax_sprite 0, 0x20
ax_sprite sDelcattyGfx27_2, 0x60
ax_sprite_terminator
sDelcattyGfx28:
.incbin "baserom.gba", 0x1241428, 0x40
sDelcattyGfx28_1:
.incbin "baserom.gba", 0x1241468, 0xE0
sDelcattyGfx28_2:
.incbin "baserom.gba", 0x1241548, 0x40
sDelcattySprites28:
ax_sprite 0, 0x20
ax_sprite sDelcattyGfx28, 0x40
ax_sprite 0, 0x20
ax_sprite sDelcattyGfx28_1, 0xe0
ax_sprite 0, 0x40
ax_sprite sDelcattyGfx28_2, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sDelcattyGfx29:
.incbin "baserom.gba", 0x12415C8, 0x100
sDelcattyGfx29_1:
.incbin "baserom.gba", 0x12416C8, 0x40
sDelcattyGfx29_2:
.incbin "baserom.gba", 0x1241708, 0x40
sDelcattySprites29:
ax_sprite sDelcattyGfx29, 0x100
ax_sprite 0, 0x20
ax_sprite sDelcattyGfx29_1, 0x40
ax_sprite 0, 0x40
ax_sprite sDelcattyGfx29_2, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sDelcattyGfx30:
.incbin "baserom.gba", 0x1241780, 0x100
sDelcattyGfx30_1:
.incbin "baserom.gba", 0x1241880, 0x40
sDelcattyGfx30_2:
.incbin "baserom.gba", 0x12418C0, 0x40
sDelcattySprites30:
ax_sprite sDelcattyGfx30, 0x100
ax_sprite 0, 0x20
ax_sprite sDelcattyGfx30_1, 0x40
ax_sprite 0, 0x40
ax_sprite sDelcattyGfx30_2, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sDelcattyGfx31:
.incbin "baserom.gba", 0x1241938, 0x160
sDelcattyGfx31_1:
.incbin "baserom.gba", 0x1241A98, 0x40
sDelcattySprites31:
ax_sprite sDelcattyGfx31, 0x160
ax_sprite 0, 0x40
ax_sprite sDelcattyGfx31_1, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sDelcattyGfx32:
.incbin "baserom.gba", 0x1241B00, 0x100
sDelcattyGfx32_1:
.incbin "baserom.gba", 0x1241C00, 0x60
sDelcattyGfx32_2:
.incbin "baserom.gba", 0x1241C60, 0x40
sDelcattySprites32:
ax_sprite sDelcattyGfx32, 0x100
ax_sprite 0, 0x20
ax_sprite sDelcattyGfx32_1, 0x60
ax_sprite 0, 0x20
ax_sprite sDelcattyGfx32_2, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sDelcattyGfx33:
.incbin "baserom.gba", 0x1241CD8, 0x40
sDelcattyGfx33_1:
.incbin "baserom.gba", 0x1241D18, 0x120
sDelcattyGfx33_2:
.incbin "baserom.gba", 0x1241E38, 0x40
sDelcattySprites33:
ax_sprite sDelcattyGfx33, 0x40
ax_sprite 0, 0x20
ax_sprite sDelcattyGfx33_1, 0x120
ax_sprite 0, 0x20
ax_sprite sDelcattyGfx33_2, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sDelcattyGfx34:
.incbin "baserom.gba", 0x1241EB0, 0x60
sDelcattyGfx34_1:
.incbin "baserom.gba", 0x1241F10, 0x60
sDelcattyGfx34_2:
.incbin "baserom.gba", 0x1241F70, 0x60
sDelcattyGfx34_3:
.incbin "baserom.gba", 0x1241FD0, 0x40
sDelcattySprites34:
ax_sprite sDelcattyGfx34, 0x60
ax_sprite 0, 0x20
ax_sprite sDelcattyGfx34_1, 0x60
ax_sprite 0, 0x20
ax_sprite sDelcattyGfx34_2, 0x60
ax_sprite 0, 0x40
ax_sprite sDelcattyGfx34_3, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sDelcattyGfx35:
.incbin "baserom.gba", 0x1242058, 0x60
sDelcattyGfx35_1:
.incbin "baserom.gba", 0x12420B8, 0x100
sDelcattyGfx35_2:
.incbin "baserom.gba", 0x12421B8, 0x40
sDelcattySprites35:
ax_sprite sDelcattyGfx35, 0x60
ax_sprite 0, 0x20
ax_sprite sDelcattyGfx35_1, 0x100
ax_sprite 0, 0x20
ax_sprite sDelcattyGfx35_2, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sDelcattyGfx36:
.incbin "baserom.gba", 0x1242230, 0x160
sDelcattyGfx36_1:
.incbin "baserom.gba", 0x1242390, 0x40
sDelcattySprites36:
ax_sprite 0, 0x20
ax_sprite sDelcattyGfx36, 0x160
ax_sprite 0, 0x20
ax_sprite sDelcattyGfx36_1, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sDelcattyGfx37:
.incbin "baserom.gba", 0x1242400, 0x180
sDelcattyGfx37_1:
.incbin "baserom.gba", 0x1242580, 0x40
sDelcattySprites37:
ax_sprite sDelcattyGfx37, 0x180
ax_sprite 0, 0x20
ax_sprite sDelcattyGfx37_1, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sDelcattyGfx38:
.incbin "baserom.gba", 0x12425E8, 0x60
sDelcattyGfx38_1:
.incbin "baserom.gba", 0x1242648, 0x100
sDelcattyGfx38_2:
.incbin "baserom.gba", 0x1242748, 0x40
sDelcattySprites38:
ax_sprite sDelcattyGfx38, 0x60
ax_sprite 0, 0x20
ax_sprite sDelcattyGfx38_1, 0x100
ax_sprite 0, 0x20
ax_sprite sDelcattyGfx38_2, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sDelcattyGfx39:
.incbin "baserom.gba", 0x12427C0, 0x100
sDelcattyGfx39_1:
.incbin "baserom.gba", 0x12428C0, 0x60
sDelcattyGfx39_2:
.incbin "baserom.gba", 0x1242920, 0x40
sDelcattySprites39:
ax_sprite sDelcattyGfx39, 0x100
ax_sprite 0, 0x20
ax_sprite sDelcattyGfx39_1, 0x60
ax_sprite 0, 0x20
ax_sprite sDelcattyGfx39_2, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sDelcattyGfx40:
.incbin "baserom.gba", 0x1242998, 0x160
sDelcattyGfx40_1:
.incbin "baserom.gba", 0x1242AF8, 0x40
sDelcattySprites40:
ax_sprite sDelcattyGfx40, 0x160
ax_sprite 0, 0x40
ax_sprite sDelcattyGfx40_1, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sDelcattyGfx41:
.incbin "baserom.gba", 0x1242B60, 0x200
sDelcattySprites41:
ax_sprite sDelcattyGfx41, 0x200
ax_sprite_terminator
sDelcattyGfx42:
.incbin "baserom.gba", 0x1242D70, 0x200
sDelcattySprites42:
ax_sprite sDelcattyGfx42, 0x200
ax_sprite_terminator
sDelcattyGfx43:
.incbin "baserom.gba", 0x1242F80, 0x80
sDelcattySprites43:
ax_sprite sDelcattyGfx43, 0x80
ax_sprite_terminator
sDelcattyGfx44:
.incbin "baserom.gba", 0x1243010, 0x20
sDelcattySprites44:
ax_sprite sDelcattyGfx44, 0x20
ax_sprite_terminator
sDelcattyGfx45:
.incbin "baserom.gba", 0x1243040, 0x100
sDelcattySprites45:
ax_sprite sDelcattyGfx45, 0x100
ax_sprite_terminator
sDelcattyGfx46:
.incbin "baserom.gba", 0x1243150, 0x100
sDelcattySprites46:
ax_sprite sDelcattyGfx46, 0x100
ax_sprite_terminator
sDelcattyGfx47:
.incbin "baserom.gba", 0x1243260, 0x20
sDelcattySprites47:
ax_sprite sDelcattyGfx47, 0x20
ax_sprite_terminator
sDelcattyGfx48:
.incbin "baserom.gba", 0x1243290, 0x40
sDelcattySprites48:
ax_sprite sDelcattyGfx48, 0x40
ax_sprite_terminator
sDelcattyGfx49:
.incbin "baserom.gba", 0x12432E0, 0x80
sDelcattySprites49:
ax_sprite sDelcattyGfx49, 0x80
ax_sprite_terminator
sDelcattyGfx50:
.incbin "baserom.gba", 0x1243370, 0x200
sDelcattySprites50:
ax_sprite sDelcattyGfx50, 0x200
ax_sprite_terminator
sDelcattyGfx51:
.incbin "baserom.gba", 0x1243580, 0x200
sDelcattySprites51:
ax_sprite sDelcattyGfx51, 0x200
ax_sprite_terminator
sDelcattyGfx52:
.incbin "baserom.gba", 0x1243790, 0x200
sDelcattySprites52:
ax_sprite sDelcattyGfx52, 0x200
ax_sprite_terminator
sAxPosesDelcatty:
.4byte sDelcattyPose1
.4byte sDelcattyPose2
.4byte sDelcattyPose3
.4byte sDelcattyPose4
.4byte sDelcattyPose5
.4byte sDelcattyPose6
.4byte sDelcattyPose7
.4byte sDelcattyPose8
.4byte sDelcattyPose9
.4byte sDelcattyPose10
.4byte sDelcattyPose11
.4byte sDelcattyPose12
.4byte sDelcattyPose13
.4byte sDelcattyPose14
.4byte sDelcattyPose15
.4byte sDelcattyPose16
.4byte sDelcattyPose17
.4byte sDelcattyPose18
.4byte sDelcattyPose19
.4byte sDelcattyPose20
.4byte sDelcattyPose21
.4byte sDelcattyPose22
.4byte sDelcattyPose23
.4byte sDelcattyPose24
.4byte sDelcattyPose25
.4byte sDelcattyPose26
.4byte sDelcattyPose27
.4byte sDelcattyPose28
.4byte sDelcattyPose29
.4byte sDelcattyPose30
.4byte sDelcattyPose31
.4byte sDelcattyPose32
.4byte sDelcattyPose33
.4byte sDelcattyPose34
.4byte sDelcattyPose35
.4byte sDelcattyPose36
.4byte sDelcattyPose37
.4byte sDelcattyPose38
.4byte sDelcattyPose39
.4byte sDelcattyPose40
.4byte sDelcattyPose41
.4byte sDelcattyPose42
.4byte sDelcattyPose43
.4byte sDelcattyPose44
.4byte sDelcattyPose45
.4byte sDelcattyPose46
.4byte sDelcattyPose47
.4byte sDelcattyPose48
.4byte sDelcattyPose49
.4byte sDelcattyPose50
.4byte sDelcattyPose51
.4byte sDelcattyPose52
.4byte sDelcattyPose53
.4byte sDelcattyPose54
.4byte sDelcattyPose55
.4byte sDelcattyPose56
.4byte sDelcattyPose57
.4byte sDelcattyPose58
.4byte sDelcattyPose59
.4byte sDelcattyPose60
.4byte sDelcattyPose61
.4byte sDelcattyPose62
.4byte sDelcattyPose63
.4byte sDelcattyPose64
.4byte sDelcattyPose65
.4byte sDelcattyPose66
.4byte sDelcattyPose67
.4byte sDelcattyPose68
.4byte sDelcattyPose69
.4byte sDelcattyPose70
.4byte sDelcattyPose71
.4byte sDelcattyPose72
.4byte sDelcattyPose73
.4byte sDelcattyPose74
.4byte sDelcattyPose75
.4byte sDelcattyPose76
.4byte sDelcattyPose77
.4byte sDelcattyPose78
.4byte sDelcattyPose79
.4byte sDelcattyPose80
.4byte sDelcattyPose81
.4byte sDelcattyPose82
.4byte sDelcattyPose83
.4byte sDelcattyPose84
.4byte sDelcattyPose85
.4byte sDelcattyPose86
.4byte sDelcattyPose87
.4byte sDelcattyPose88
.4byte sDelcattyPose89
.4byte sDelcattyPose90
.4byte sDelcattyPose91
.4byte sDelcattyPose92
.4byte sDelcattyPose93
.4byte sDelcattyPose94
.4byte sDelcattyPose95
.4byte sDelcattyPose96
.4byte sDelcattyPose97
.4byte sDelcattyPose98
.4byte sDelcattyPose99
.4byte sDelcattyPose100
.4byte sDelcattyPose101
.4byte sDelcattyPose102
.4byte sDelcattyPose103
.4byte sDelcattyPose104
.4byte sDelcattyPose105
.4byte sDelcattyPose106
.4byte sDelcattyPose107
.4byte sDelcattyPose108
.4byte sDelcattyPose109
.4byte sDelcattyPose110
.4byte sDelcattyPose111
.4byte sDelcattyPose112
.4byte sDelcattyPose113
.4byte sDelcattyPose114
.4byte sDelcattyPose115
.4byte sDelcattyPose116
.4byte sDelcattyPose117
.4byte sDelcattyPose118
.4byte sDelcattyPose119
.4byte sDelcattyPose120
.4byte sDelcattyPose121
.4byte sDelcattyPose122
.4byte sDelcattyPose123
.4byte sDelcattyPose124
.4byte sDelcattyPose125
.4byte sDelcattyPose126
.4byte sDelcattyPose127
.4byte sDelcattyPose128
.4byte sDelcattyPose129
.4byte sDelcattyPose130
.4byte sDelcattyPose131
.4byte sDelcattyPose132
.4byte sDelcattyPose133
.4byte sDelcattyPose134
.4byte sDelcattyPose135
.4byte sDelcattyPose136
.4byte sDelcattyPose137
.4byte sDelcattyPose138
.4byte sDelcattyPose139
.4byte sDelcattyPose140
.4byte sDelcattyPose141
.4byte sDelcattyPose142
.4byte sDelcattyPose143
.4byte sDelcattyPose144
.4byte sDelcattyPose145
.4byte sDelcattyPose146
.4byte sDelcattyPose147
.4byte sDelcattyPose148
.4byte sDelcattyPose149
.4byte sDelcattyPose150
.4byte sDelcattyPose151
.4byte sDelcattyPose152
.4byte sDelcattyPose153
.4byte sDelcattyPose154
.4byte sDelcattyPose155
.4byte sDelcattyPose156
.4byte sDelcattyPose157
.4byte sDelcattyPose158
.4byte sDelcattyPose159
.4byte sDelcattyPose160
.4byte sDelcattyPose161
.4byte sDelcattyPose162
.4byte sDelcattyPose163
.4byte sDelcattyPose164
.4byte sDelcattyPose165
.4byte sDelcattyPose166
.4byte sDelcattyPose167
.4byte sDelcattyPose168
.4byte sDelcattyPose169
.4byte sDelcattyPose170
.4byte sDelcattyPose171
.4byte sDelcattyPose172
.4byte sDelcattyPose173
.4byte sDelcattyPose174
.4byte sDelcattyPose175
.4byte sDelcattyPose176
.4byte sDelcattyPose177
.4byte sDelcattyPose178
.4byte sDelcattyPose179
.4byte sDelcattyPose180
.4byte sDelcattyPose181
.4byte sDelcattyPose182
.4byte sDelcattyPose183
.4byte sDelcattyPose184
.4byte sDelcattyPose185
.4byte sDelcattyPose186
.4byte sDelcattyPose187
.4byte sDelcattyPose188
.4byte sDelcattyPose189
.4byte sDelcattyPose190
.4byte sDelcattyPose191
.4byte sDelcattyPose192
.4byte sDelcattyPose193
.4byte sDelcattyPose194
.4byte sDelcattyPose195
.4byte sDelcattyPose196
.4byte sDelcattyPose197
.4byte sDelcattyPose198
.4byte sDelcattyPose199
.4byte sDelcattyPose200
.4byte sDelcattyPose201
.4byte sDelcattyPose202
.4byte sDelcattyPose203
.4byte sDelcattyPose204
.4byte sDelcattyPose205
.4byte sDelcattyPose206
.4byte sDelcattyPose207
.4byte sDelcattyPose208
.4byte sDelcattyPose209
.4byte sDelcattyPose210
.4byte sDelcattyPose211
.4byte sDelcattyPose212
.4byte sDelcattyPose213
.4byte sDelcattyPose214
.4byte sDelcattyPose215
.4byte sDelcattyPose216
.4byte sDelcattyPose217
.4byte sDelcattyPose218
.4byte sDelcattyPose219
.4byte sDelcattyPose220
.4byte sDelcattyPose221
.4byte sDelcattyPose222
.4byte sDelcattyPose223
.4byte sDelcattyPose224
.4byte sDelcattyPose225
.4byte sDelcattyPose226
.4byte sDelcattyPose227
.4byte sDelcattyPose228
.4byte sDelcattyPose229
.4byte sDelcattyPose230
.4byte sDelcattyPose231
.4byte sDelcattyPose232
.4byte sDelcattyPose233
.4byte sDelcattyPose234
.4byte sDelcattyPose235
.4byte sDelcattyPose236
.4byte sDelcattyPose237
.4byte sDelcattyPose238
.4byte sDelcattyPose239
.4byte sDelcattyPose240
.4byte sDelcattyPose241
.4byte sDelcattyPose242
sAxPositionsDelcatty:
.2byte   -1,   -9, 	  -3,    0, 	   1,    0, 	  -1,   -8
.2byte   -2,   -8, 	  -2,    2, 	  -1,    0, 	  -1,   -7
.2byte    0,   -8, 	  -1,    0, 	   0,    2, 	  -1,   -7
.2byte    3,   -9, 	   3,   -1, 	  -1,    1, 	   0,   -8
.2byte    4,   -8, 	   4,    2, 	  -2,    0, 	   0,   -7
.2byte    2,   -8, 	   1,   -1, 	   1,    3, 	   0,   -7
.2byte    6,  -11, 	   4,   -3, 	   2,    0, 	   0,   -8
.2byte    7,  -11, 	   6,   -1, 	  -1,    1, 	   1,   -7
.2byte    6,  -10, 	   1,   -2, 	   6,    0, 	   1,   -7
.2byte    2,  -13, 	  -2,   -2, 	   3,   -1, 	  -1,   -9
.2byte    2,  -12, 	  -2,   -4, 	   1,    1, 	  -1,   -8
.2byte    2,  -12, 	  -2,   -2, 	   6,   -2, 	   0,   -8
.2byte   -1,  -14, 	   1,   -3, 	  -3,   -3, 	  -1,  -11
.2byte    2,  -12, 	   0,   -5, 	  -3,   -2, 	  -1,  -10
.2byte   -4,  -12, 	   1,   -2, 	  -3,   -5, 	  -1,  -10
.2byte   -4,  -13, 	   0,   -2, 	  -5,   -1, 	  -1,   -9
.2byte   -4,  -12, 	   0,   -4, 	  -3,    1, 	  -1,   -8
.2byte   -4,  -12, 	   0,   -2, 	  -8,   -2, 	  -2,   -8
.2byte   -8,  -11, 	  -6,   -3, 	  -4,    0, 	  -2,   -8
.2byte   -9,  -11, 	  -8,   -1, 	  -1,    1, 	  -3,   -7
.2byte   -8,  -10, 	  -3,   -2, 	  -8,    0, 	  -3,   -7
.2byte   -5,   -9, 	  -5,   -1, 	  -1,    1, 	  -2,   -8
.2byte   -6,   -8, 	  -6,    2, 	   0,    0, 	  -2,   -7
.2byte   -4,   -8, 	  -3,   -1, 	  -3,    3, 	  -2,   -7
.2byte   -1,   -9, 	  -3,    0, 	   1,    0, 	  -1,   -8
.2byte   -1,  -12, 	  -3,    0, 	   1,    0, 	  -1,  -10
.2byte   -1,   -6, 	  -5,    0, 	   3,    0, 	  -1,   -8
.2byte   -1,  -11, 	  -2,    0, 	   0,    0, 	  -1,  -10
.2byte    3,   -9, 	   3,   -1, 	  -1,    1, 	   0,   -8
.2byte    2,  -11, 	   3,   -1, 	  -1,    1, 	  -1,   -9
.2byte    4,   -7, 	   4,   -1, 	  -3,    1, 	   0,   -7
.2byte    2,  -10, 	   2,   -1, 	  -1,    1, 	  -2,   -9
.2byte    6,  -11, 	   4,   -3, 	   2,    0, 	   0,   -8
.2byte    4,  -12, 	   4,   -3, 	   2,    0, 	  -1,   -8
.2byte    9,   -9, 	   4,   -3, 	   1,    0, 	   1,   -7
.2byte    5,  -12, 	   1,   -3, 	   1,   -1, 	   0,   -9
.2byte    2,  -13, 	  -2,   -2, 	   3,   -1, 	  -1,   -9
.2byte    2,  -12, 	  -3,   -3, 	   3,   -1, 	  -2,   -9
.2byte    6,  -12, 	  -3,   -5, 	   4,   -1, 	   1,   -9
.2byte    3,  -12, 	   0,   -1, 	   2,    0, 	   0,   -9
.2byte   -1,  -14, 	   1,   -3, 	  -3,   -3, 	  -1,  -11
.2byte   -1,  -13, 	   1,   -3, 	  -3,   -3, 	  -1,   -9
.2byte   -1,  -12, 	   4,   -4, 	  -6,   -4, 	  -1,  -10
.2byte   -1,  -13, 	   1,   -3, 	  -3,   -3, 	  -1,   -9
.2byte   -4,  -13, 	   0,   -2, 	  -5,   -1, 	  -1,   -9
.2byte   -4,  -12, 	   1,   -3, 	  -5,   -1, 	   0,   -9
.2byte   -8,  -12, 	   1,   -5, 	  -6,   -1, 	  -3,   -9
.2byte   -5,  -12, 	  -2,   -1, 	  -4,    0, 	  -2,   -9
.2byte   -8,  -11, 	  -6,   -3, 	  -4,    0, 	  -2,   -8
.2byte   -6,  -12, 	  -6,   -3, 	  -4,    0, 	  -1,   -8
.2byte  -11,   -9, 	  -6,   -3, 	  -3,    0, 	  -3,   -7
.2byte   -7,  -12, 	  -3,   -3, 	  -3,   -1, 	  -2,   -9
.2byte   -5,   -9, 	  -5,   -1, 	  -1,    1, 	  -2,   -8
.2byte   -4,  -11, 	  -5,   -1, 	  -1,    1, 	  -1,   -9
.2byte   -6,   -7, 	  -6,   -1, 	   1,    1, 	  -2,   -7
.2byte   -4,  -10, 	  -4,   -1, 	  -1,    1, 	   0,   -9
.2byte   -1,   -9, 	  -3,    0, 	   1,    0, 	  -1,   -8
.2byte   -1,  -12, 	  -3,    0, 	   1,    0, 	  -1,  -10
.2byte   -1,   -6, 	  -5,    0, 	   3,    0, 	  -1,   -8
.2byte   -1,  -11, 	  -2,    0, 	   0,    0, 	  -1,  -10
.2byte    3,   -9, 	   3,   -1, 	  -1,    1, 	   0,   -8
.2byte    2,  -11, 	   3,   -1, 	  -1,    1, 	  -1,   -9
.2byte    4,   -7, 	   4,   -1, 	  -3,    1, 	   0,   -7
.2byte    2,  -10, 	   2,   -1, 	  -1,    1, 	  -2,   -9
.2byte    6,  -11, 	   4,   -3, 	   2,    0, 	   0,   -8
.2byte    4,  -12, 	   4,   -3, 	   2,    0, 	  -1,   -8
.2byte    9,   -9, 	   4,   -3, 	   1,    0, 	   1,   -7
.2byte    5,  -12, 	   1,   -3, 	   1,   -1, 	   0,   -9
.2byte    2,  -13, 	  -2,   -2, 	   3,   -1, 	  -1,   -9
.2byte    2,  -12, 	  -3,   -3, 	   3,   -1, 	  -2,   -9
.2byte    6,  -12, 	  -3,   -5, 	   4,   -1, 	   1,   -9
.2byte    3,  -12, 	   0,   -1, 	   2,    0, 	   0,   -9
.2byte   -1,  -14, 	   1,   -3, 	  -3,   -3, 	  -1,  -11
.2byte   -1,  -13, 	   1,   -3, 	  -3,   -3, 	  -1,   -9
.2byte   -1,  -12, 	   4,   -4, 	  -6,   -4, 	  -1,  -10
.2byte   -1,  -13, 	   1,   -3, 	  -3,   -3, 	  -1,   -9
.2byte   -4,  -13, 	   0,   -2, 	  -5,   -1, 	  -1,   -9
.2byte   -4,  -12, 	   1,   -3, 	  -5,   -1, 	   0,   -9
.2byte   -8,  -12, 	   1,   -5, 	  -6,   -1, 	  -3,   -9
.2byte   -5,  -12, 	  -2,   -1, 	  -4,    0, 	  -2,   -9
.2byte   -8,  -11, 	  -6,   -3, 	  -4,    0, 	  -2,   -8
.2byte   -6,  -12, 	  -6,   -3, 	  -4,    0, 	  -1,   -8
.2byte  -11,   -9, 	  -6,   -3, 	  -3,    0, 	  -3,   -7
.2byte   -7,  -12, 	  -3,   -3, 	  -3,   -1, 	  -2,   -9
.2byte   -5,   -9, 	  -5,   -1, 	  -1,    1, 	  -2,   -8
.2byte   -4,  -11, 	  -5,   -1, 	  -1,    1, 	  -1,   -9
.2byte   -6,   -7, 	  -6,   -1, 	   1,    1, 	  -2,   -7
.2byte   -4,  -10, 	  -4,   -1, 	  -1,    1, 	   0,   -9
.2byte   -1,   -9, 	  -3,    0, 	   1,    0, 	  -1,   -8
.2byte   -1,  -12, 	  -3,    0, 	   1,    0, 	  -1,  -10
.2byte   -1,   -6, 	  -5,    0, 	   3,    0, 	  -1,   -8
.2byte   -1,  -11, 	  -2,    0, 	   0,    0, 	  -1,  -10
.2byte    3,   -9, 	   3,   -1, 	  -1,    1, 	   0,   -8
.2byte    2,  -11, 	   3,   -1, 	  -1,    1, 	  -1,   -9
.2byte    4,   -7, 	   4,   -1, 	  -3,    1, 	   0,   -7
.2byte    2,  -10, 	   2,   -1, 	  -1,    1, 	  -2,   -9
.2byte    6,  -11, 	   4,   -3, 	   2,    0, 	   0,   -8
.2byte    4,  -12, 	   4,   -3, 	   2,    0, 	  -1,   -8
.2byte    9,   -9, 	   4,   -3, 	   1,    0, 	   1,   -7
.2byte    5,  -12, 	   1,   -3, 	   1,   -1, 	   0,   -9
.2byte    2,  -13, 	  -2,   -2, 	   3,   -1, 	  -1,   -9
.2byte    2,  -12, 	  -3,   -3, 	   3,   -1, 	  -2,   -9
.2byte    6,  -12, 	  -3,   -5, 	   4,   -1, 	   1,   -9
.2byte    3,  -12, 	   0,   -1, 	   2,    0, 	   0,   -9
.2byte   -1,  -14, 	   1,   -3, 	  -3,   -3, 	  -1,  -11
.2byte   -1,  -13, 	   1,   -3, 	  -3,   -3, 	  -1,   -9
.2byte   -1,  -12, 	   4,   -4, 	  -6,   -4, 	  -1,  -10
.2byte   -1,  -13, 	   1,   -3, 	  -3,   -3, 	  -1,   -9
.2byte   -4,  -13, 	   0,   -2, 	  -5,   -1, 	  -1,   -9
.2byte   -4,  -12, 	   1,   -3, 	  -5,   -1, 	   0,   -9
.2byte   -8,  -12, 	   1,   -5, 	  -6,   -1, 	  -3,   -9
.2byte   -5,  -12, 	  -2,   -1, 	  -4,    0, 	  -2,   -9
.2byte   -8,  -11, 	  -6,   -3, 	  -4,    0, 	  -2,   -8
.2byte   -6,  -12, 	  -6,   -3, 	  -4,    0, 	  -1,   -8
.2byte  -11,   -9, 	  -6,   -3, 	  -3,    0, 	  -3,   -7
.2byte   -7,  -12, 	  -3,   -3, 	  -3,   -1, 	  -2,   -9
.2byte   -5,   -9, 	  -5,   -1, 	  -1,    1, 	  -2,   -8
.2byte   -4,  -11, 	  -5,   -1, 	  -1,    1, 	  -1,   -9
.2byte   -6,   -7, 	  -6,   -1, 	   1,    1, 	  -2,   -7
.2byte   -4,  -10, 	  -4,   -1, 	  -1,    1, 	   0,   -9
.2byte   -1,   -9, 	  -3,    0, 	   1,    0, 	  -1,   -8
.2byte   -3,   -9, 	  -3,    0, 	   1,    0, 	  -2,   -8
.2byte    1,   -9, 	  -3,    0, 	   1,    0, 	   0,   -8
.2byte    3,   -9, 	   3,   -1, 	  -1,    1, 	   0,   -8
.2byte    4,   -9, 	   3,   -1, 	  -1,    1, 	   0,   -8
.2byte    2,   -9, 	   3,   -1, 	  -1,    1, 	   0,   -8
.2byte    6,  -11, 	   4,   -3, 	   2,    0, 	   0,   -8
.2byte    6,  -12, 	   4,   -3, 	   2,    0, 	   0,   -9
.2byte    6,  -10, 	   4,   -3, 	   2,    0, 	   0,   -7
.2byte    2,  -13, 	  -2,   -2, 	   3,   -1, 	  -1,   -9
.2byte    0,  -13, 	  -3,   -4, 	   3,   -1, 	   0,  -10
.2byte    4,  -12, 	  -3,   -4, 	   3,   -1, 	   0,   -9
.2byte   -1,  -14, 	   1,   -3, 	  -3,   -3, 	  -1,  -11
.2byte    2,  -13, 	   1,   -2, 	  -3,   -2, 	  -1,  -11
.2byte   -4,  -13, 	   1,   -2, 	  -3,   -2, 	  -2,  -11
.2byte   -4,  -13, 	   0,   -2, 	  -5,   -1, 	  -1,   -9
.2byte   -2,  -13, 	   1,   -4, 	  -5,   -1, 	  -2,  -10
.2byte   -6,  -12, 	   1,   -4, 	  -5,   -1, 	  -2,   -9
.2byte   -8,  -11, 	  -6,   -3, 	  -4,    0, 	  -2,   -8
.2byte   -8,  -12, 	  -6,   -3, 	  -4,    0, 	  -2,   -9
.2byte   -8,  -10, 	  -6,   -3, 	  -4,    0, 	  -2,   -7
.2byte   -5,   -9, 	  -5,   -1, 	  -1,    1, 	  -2,   -8
.2byte   -6,   -9, 	  -5,   -1, 	  -1,    1, 	  -2,   -8
.2byte   -4,   -9, 	  -5,   -1, 	  -1,    1, 	  -2,   -8
.2byte   -4,   -4, 	  -6,    0, 	  -4,    0, 	   0,   -4
.2byte   -5,   -3, 	  -6,    0, 	  -4,    0, 	  -1,   -4
.2byte    0,   -9, 	  -4,    0, 	   4,    0, 	   0,   -8
.2byte    2,   -9, 	   6,   -3, 	   2,    1, 	   0,   -8
.2byte    4,   -8, 	   8,   -3, 	   5,    0, 	  -1,   -7
.2byte    1,  -12, 	  -1,   -5, 	   5,   -3, 	  -2,  -10
.2byte    0,  -10, 	   3,   -5, 	  -3,   -5, 	   0,  -11
.2byte   -2,  -12, 	   0,   -5, 	  -6,   -3, 	   1,  -10
.2byte   -5,   -8, 	  -9,   -3, 	  -6,    0, 	   0,   -7
.2byte   -3,   -9, 	  -7,   -3, 	  -3,    1, 	  -1,   -8
.2byte   -1,   -9, 	  -3,    0, 	   1,    0, 	  -1,   -8
.2byte   -3,   -9, 	  -3,    0, 	   1,    0, 	  -2,   -8
.2byte    1,   -9, 	  -3,    0, 	   1,    0, 	   0,   -8
.2byte   -1,  -10, 	  -2,    1, 	   0,    1, 	  -1,   -9
.2byte    3,   -9, 	   3,   -1, 	  -1,    1, 	   0,   -8
.2byte    4,   -9, 	   3,   -1, 	  -1,    1, 	   0,   -8
.2byte    2,   -9, 	   3,   -1, 	  -1,    1, 	   0,   -8
.2byte    2,  -10, 	   2,   -1, 	  -1,    1, 	  -2,   -9
.2byte    6,  -11, 	   4,   -3, 	   2,    0, 	   0,   -8
.2byte    6,  -12, 	   4,   -3, 	   2,    0, 	   0,   -9
.2byte    6,  -10, 	   4,   -3, 	   2,    0, 	   0,   -7
.2byte    5,  -11, 	   1,   -2, 	   1,    0, 	   0,   -8
.2byte    2,  -13, 	  -2,   -2, 	   3,   -1, 	  -1,   -9
.2byte    0,  -13, 	  -3,   -4, 	   3,   -1, 	   0,  -10
.2byte    4,  -12, 	  -3,   -4, 	   3,   -1, 	   0,   -9
.2byte    3,  -13, 	   0,   -2, 	   2,   -1, 	   0,  -10
.2byte   -1,  -14, 	   1,   -3, 	  -3,   -3, 	  -1,  -11
.2byte    2,  -13, 	   1,   -2, 	  -3,   -2, 	  -1,  -11
.2byte   -4,  -13, 	   1,   -2, 	  -3,   -2, 	  -2,  -11
.2byte   -1,  -14, 	   1,   -4, 	  -3,   -4, 	  -1,  -10
.2byte   -4,  -13, 	   0,   -2, 	  -5,   -1, 	  -1,   -9
.2byte   -2,  -13, 	   1,   -4, 	  -5,   -1, 	  -2,  -10
.2byte   -6,  -12, 	   1,   -4, 	  -5,   -1, 	  -2,   -9
.2byte   -5,  -13, 	  -2,   -2, 	  -4,   -1, 	  -2,  -10
.2byte   -8,  -11, 	  -6,   -3, 	  -4,    0, 	  -2,   -8
.2byte   -8,  -12, 	  -6,   -3, 	  -4,    0, 	  -2,   -9
.2byte   -8,  -10, 	  -6,   -3, 	  -4,    0, 	  -2,   -7
.2byte   -7,  -11, 	  -3,   -2, 	  -3,    0, 	  -2,   -8
.2byte   -5,   -9, 	  -5,   -1, 	  -1,    1, 	  -2,   -8
.2byte   -6,   -9, 	  -5,   -1, 	  -1,    1, 	  -2,   -8
.2byte   -4,   -9, 	  -5,   -1, 	  -1,    1, 	  -2,   -8
.2byte   -4,  -10, 	  -4,   -1, 	  -1,    1, 	   0,   -9
.2byte   -1,   -6, 	  -5,    0, 	   3,    0, 	  -1,   -8
.2byte   -6,   -7, 	  -6,   -1, 	   1,    1, 	  -2,   -7
.2byte  -11,   -9, 	  -6,   -3, 	  -3,    0, 	  -3,   -7
.2byte   -8,  -12, 	   1,   -5, 	  -6,   -1, 	  -3,   -9
.2byte   -1,  -12, 	   4,   -4, 	  -6,   -4, 	  -1,  -10
.2byte    6,  -12, 	  -3,   -5, 	   4,   -1, 	   1,   -9
.2byte    9,   -9, 	   4,   -3, 	   1,    0, 	   1,   -7
.2byte    4,   -7, 	   4,   -1, 	  -3,    1, 	   0,   -7
.2byte   -1,  -11, 	  -3,    1, 	   1,    1, 	  -1,   -9
.2byte    4,  -11, 	   5,   -1, 	   1,    1, 	   1,   -9
.2byte    5,  -12, 	   5,   -3, 	   3,    0, 	   0,   -8
.2byte    3,  -12, 	  -2,   -3, 	   4,   -1, 	  -1,   -9
.2byte   -1,  -14, 	   1,   -4, 	  -3,   -4, 	  -1,  -10
.2byte   -5,  -12, 	   0,   -3, 	  -6,   -1, 	  -1,   -9
.2byte   -7,  -12, 	  -7,   -3, 	  -5,    0, 	  -2,   -8
.2byte   -5,  -11, 	  -6,   -1, 	  -2,    1, 	  -2,   -9
.2byte   -1,   -9, 	  -3,    0, 	   1,    0, 	  -1,   -8
.2byte   -1,  -12, 	  -3,    0, 	   1,    0, 	  -1,  -10
.2byte   -1,   -6, 	  -5,    0, 	   3,    0, 	  -1,   -8
.2byte    3,   -9, 	   3,   -1, 	  -1,    1, 	   0,   -8
.2byte    2,  -11, 	   3,   -1, 	  -1,    1, 	  -1,   -9
.2byte    4,   -7, 	   4,   -1, 	  -3,    1, 	   0,   -7
.2byte    6,  -11, 	   4,   -3, 	   2,    0, 	   0,   -8
.2byte    4,  -12, 	   4,   -3, 	   2,    0, 	  -1,   -8
.2byte    8,   -9, 	   3,   -3, 	   0,    0, 	   0,   -7
.2byte    2,  -13, 	  -2,   -2, 	   3,   -1, 	  -1,   -9
.2byte    2,  -12, 	  -3,   -3, 	   3,   -1, 	  -2,   -9
.2byte    5,  -12, 	  -4,   -5, 	   3,   -1, 	   0,   -9
.2byte   -1,  -14, 	   1,   -3, 	  -3,   -3, 	  -1,  -11
.2byte   -1,  -13, 	   1,   -3, 	  -3,   -3, 	  -1,   -9
.2byte   -1,  -14, 	   4,   -6, 	  -6,   -6, 	  -1,  -12
.2byte   -4,  -13, 	   0,   -2, 	  -5,   -1, 	  -1,   -9
.2byte   -4,  -12, 	   1,   -3, 	  -5,   -1, 	   0,   -9
.2byte   -7,  -12, 	   2,   -5, 	  -5,   -1, 	  -2,   -9
.2byte   -8,  -11, 	  -6,   -3, 	  -4,    0, 	  -2,   -8
.2byte   -6,  -12, 	  -6,   -3, 	  -4,    0, 	  -1,   -8
.2byte  -10,   -9, 	  -5,   -3, 	  -2,    0, 	  -2,   -7
.2byte   -5,   -9, 	  -5,   -1, 	  -1,    1, 	  -2,   -8
.2byte   -4,  -11, 	  -5,   -1, 	  -1,    1, 	  -1,   -9
.2byte   -6,   -7, 	  -6,   -1, 	   1,    1, 	  -2,   -7
.2byte   -1,   -6, 	  -5,    0, 	   3,    0, 	  -1,   -8
.2byte   -6,   -7, 	  -6,   -1, 	   1,    1, 	  -2,   -7
.2byte  -11,   -9, 	  -6,   -3, 	  -3,    0, 	  -3,   -7
.2byte   -8,  -12, 	   1,   -5, 	  -6,   -1, 	  -3,   -9
.2byte   -1,  -12, 	   4,   -4, 	  -6,   -4, 	  -1,  -10
.2byte    6,  -12, 	  -3,   -5, 	   4,   -1, 	   1,   -9
.2byte    9,   -9, 	   4,   -3, 	   1,    0, 	   1,   -7
.2byte    4,   -7, 	   4,   -1, 	  -3,    1, 	   0,   -7
.2byte   -1,   -9, 	  -3,    0, 	   1,    0, 	  -1,   -8
.2byte   -5,   -9, 	  -5,   -1, 	  -1,    1, 	  -2,   -8
.2byte   -8,  -11, 	  -6,   -3, 	  -4,    0, 	  -2,   -8
.2byte   -4,  -13, 	   0,   -2, 	  -5,   -1, 	  -1,   -9
.2byte   -1,  -14, 	   1,   -3, 	  -3,   -3, 	  -1,  -11
.2byte    2,  -13, 	  -2,   -2, 	   3,   -1, 	  -1,   -9
.2byte    6,  -11, 	   4,   -3, 	   2,    0, 	   0,   -8
.2byte    3,   -9, 	   3,   -1, 	  -1,    1, 	   0,   -8
sDelcattyAnimTable1:
.4byte sDelcattyAnims_1_1
.4byte sDelcattyAnims_1_2
.4byte sDelcattyAnims_1_3
.4byte sDelcattyAnims_1_4
.4byte sDelcattyAnims_1_5
.4byte sDelcattyAnims_1_6
.4byte sDelcattyAnims_1_7
.4byte sDelcattyAnims_1_8
sDelcattyAnimTable2:
.4byte sDelcattyAnims_2_1
.4byte sDelcattyAnims_2_2
.4byte sDelcattyAnims_2_3
.4byte sDelcattyAnims_2_4
.4byte sDelcattyAnims_2_5
.4byte sDelcattyAnims_2_6
.4byte sDelcattyAnims_2_7
.4byte sDelcattyAnims_2_8
sDelcattyAnimTable3:
.4byte sDelcattyAnims_3_1
.4byte sDelcattyAnims_3_2
.4byte sDelcattyAnims_3_3
.4byte sDelcattyAnims_3_4
.4byte sDelcattyAnims_3_5
.4byte sDelcattyAnims_3_6
.4byte sDelcattyAnims_3_7
.4byte sDelcattyAnims_3_8
sDelcattyAnimTable4:
.4byte sDelcattyAnims_4_1
.4byte sDelcattyAnims_4_2
.4byte sDelcattyAnims_4_3
.4byte sDelcattyAnims_4_4
.4byte sDelcattyAnims_4_5
.4byte sDelcattyAnims_4_6
.4byte sDelcattyAnims_4_7
.4byte sDelcattyAnims_4_8
sDelcattyAnimTable5:
.4byte sDelcattyAnims_5_1
.4byte sDelcattyAnims_5_2
.4byte sDelcattyAnims_5_3
.4byte sDelcattyAnims_5_4
.4byte sDelcattyAnims_5_5
.4byte sDelcattyAnims_5_6
.4byte sDelcattyAnims_5_7
.4byte sDelcattyAnims_5_8
sDelcattyAnimTable6:
.4byte sDelcattyAnims_6_1
.4byte sDelcattyAnims_6_1
.4byte sDelcattyAnims_6_1
.4byte sDelcattyAnims_6_1
.4byte sDelcattyAnims_6_1
.4byte sDelcattyAnims_6_1
.4byte sDelcattyAnims_6_1
.4byte sDelcattyAnims_6_1
sDelcattyAnimTable7:
.4byte sDelcattyAnims_7_1
.4byte sDelcattyAnims_7_2
.4byte sDelcattyAnims_7_3
.4byte sDelcattyAnims_7_4
.4byte sDelcattyAnims_7_5
.4byte sDelcattyAnims_7_6
.4byte sDelcattyAnims_7_7
.4byte sDelcattyAnims_7_8
sDelcattyAnimTable8:
.4byte sDelcattyAnims_8_1
.4byte sDelcattyAnims_8_2
.4byte sDelcattyAnims_8_3
.4byte sDelcattyAnims_8_4
.4byte sDelcattyAnims_8_5
.4byte sDelcattyAnims_8_6
.4byte sDelcattyAnims_8_7
.4byte sDelcattyAnims_8_8
sDelcattyAnimTable9:
.4byte sDelcattyAnims_9_1
.4byte sDelcattyAnims_9_2
.4byte sDelcattyAnims_9_3
.4byte sDelcattyAnims_9_4
.4byte sDelcattyAnims_9_5
.4byte sDelcattyAnims_9_6
.4byte sDelcattyAnims_9_7
.4byte sDelcattyAnims_9_8
sDelcattyAnimTable10:
.4byte sDelcattyAnims_10_1
.4byte sDelcattyAnims_10_2
.4byte sDelcattyAnims_10_3
.4byte sDelcattyAnims_10_4
.4byte sDelcattyAnims_10_5
.4byte sDelcattyAnims_10_6
.4byte sDelcattyAnims_10_7
.4byte sDelcattyAnims_10_8
sDelcattyAnimTable11:
.4byte sDelcattyAnims_11_1
.4byte sDelcattyAnims_11_2
.4byte sDelcattyAnims_11_3
.4byte sDelcattyAnims_11_4
.4byte sDelcattyAnims_11_5
.4byte sDelcattyAnims_11_6
.4byte sDelcattyAnims_11_7
.4byte sDelcattyAnims_11_8
sDelcattyAnimTable12:
.4byte sDelcattyAnims_12_1
.4byte sDelcattyAnims_12_2
.4byte sDelcattyAnims_12_3
.4byte sDelcattyAnims_12_4
.4byte sDelcattyAnims_12_5
.4byte sDelcattyAnims_12_6
.4byte sDelcattyAnims_12_7
.4byte sDelcattyAnims_12_8
sDelcattyAnimTable13:
.4byte sDelcattyAnims_13_1
.4byte sDelcattyAnims_13_2
.4byte sDelcattyAnims_13_3
.4byte sDelcattyAnims_13_4
.4byte sDelcattyAnims_13_5
.4byte sDelcattyAnims_13_6
.4byte sDelcattyAnims_13_7
.4byte sDelcattyAnims_13_8
sAxAnimationsDelcatty:
.4byte sDelcattyAnimTable1
.4byte sDelcattyAnimTable2
.4byte sDelcattyAnimTable3
.4byte sDelcattyAnimTable4
.4byte sDelcattyAnimTable5
.4byte sDelcattyAnimTable6
.4byte sDelcattyAnimTable7
.4byte sDelcattyAnimTable8
.4byte sDelcattyAnimTable9
.4byte sDelcattyAnimTable10
.4byte sDelcattyAnimTable11
.4byte sDelcattyAnimTable12
.4byte sDelcattyAnimTable13
sAxSpritesDelcatty:
.4byte sDelcattySprites1
.4byte sDelcattySprites2
.4byte sDelcattySprites3
.4byte sDelcattySprites4
.4byte sDelcattySprites5
.4byte sDelcattySprites6
.4byte sDelcattySprites7
.4byte sDelcattySprites8
.4byte sDelcattySprites9
.4byte sDelcattySprites10
.4byte sDelcattySprites11
.4byte sDelcattySprites12
.4byte sDelcattySprites13
.4byte sDelcattySprites14
.4byte sDelcattySprites15
.4byte sDelcattySprites16
.4byte sDelcattySprites17
.4byte sDelcattySprites18
.4byte sDelcattySprites19
.4byte sDelcattySprites20
.4byte sDelcattySprites21
.4byte sDelcattySprites22
.4byte sDelcattySprites23
.4byte sDelcattySprites24
.4byte sDelcattySprites25
.4byte sDelcattySprites26
.4byte sDelcattySprites27
.4byte sDelcattySprites28
.4byte sDelcattySprites29
.4byte sDelcattySprites30
.4byte sDelcattySprites31
.4byte sDelcattySprites32
.4byte sDelcattySprites33
.4byte sDelcattySprites34
.4byte sDelcattySprites35
.4byte sDelcattySprites36
.4byte sDelcattySprites37
.4byte sDelcattySprites38
.4byte sDelcattySprites39
.4byte sDelcattySprites40
.4byte sDelcattySprites41
.4byte sDelcattySprites42
.4byte sDelcattySprites43
.4byte sDelcattySprites44
.4byte sDelcattySprites45
.4byte sDelcattySprites46
.4byte sDelcattySprites47
.4byte sDelcattySprites48
.4byte sDelcattySprites49
.4byte sDelcattySprites50
.4byte sDelcattySprites51
.4byte sDelcattySprites52
sAxMainDelcatty:
ax_main sAxPosesDelcatty, sAxAnimationsDelcatty, 13, sAxSpritesDelcatty, sAxPositionsDelcatty
