.global gAxDunsparce
gAxDunsparce:
ax_siro sAxMainDunsparce
sDunsparcePose1:
ax_pose 0, 0x81ef, 0x80f8, 0x0c00
ax_pose_terminator
sDunsparcePose2:
ax_pose 1, 0x81ef, 0x80f8, 0x0c00
ax_pose_terminator
sDunsparcePose3:
ax_pose 2, 0x01eb, 0x80f8, 0x0c00
ax_pose_terminator
sDunsparcePose4:
ax_pose 3, 0x01ef, 0x90f1, 0x0c00
ax_pose_terminator
sDunsparcePose5:
ax_pose 4, 0x01ef, 0x90f1, 0x0c00
ax_pose_terminator
sDunsparcePose6:
ax_pose 5, 0x01eb, 0x90f1, 0x0c00
ax_pose_terminator
sDunsparcePose7:
ax_pose 6, 0x41f3, 0x90f1, 0x0c00
ax_pose_terminator
sDunsparcePose8:
ax_pose 7, 0x41f3, 0x90f1, 0x0c00
ax_pose_terminator
sDunsparcePose9:
ax_pose 8, 0x01eb, 0x90f1, 0x0c00
ax_pose_terminator
sDunsparcePose10:
ax_pose 9, 0x01ef, 0x90f1, 0x0c00
ax_pose_terminator
sDunsparcePose11:
ax_pose 10, 0x01eb, 0x90f1, 0x0c00
ax_pose_terminator
sDunsparcePose12:
ax_pose 11, 0x01eb, 0x90f1, 0x0c00
ax_pose_terminator
sDunsparcePose13:
ax_pose 12, 0x81ef, 0x80f8, 0x0c00
ax_pose_terminator
sDunsparcePose14:
ax_pose 13, 0x81ef, 0x80f8, 0x0c00
ax_pose_terminator
sDunsparcePose15:
ax_pose 14, 0x41f7, 0x80f8, 0x0c00
ax_pose_terminator
sDunsparcePose16:
ax_pose 9, 0x01ef, 0x80f0, 0x0c00
ax_pose_terminator
sDunsparcePose17:
ax_pose 10, 0x01eb, 0x80f0, 0x0c00
ax_pose_terminator
sDunsparcePose18:
ax_pose 11, 0x01eb, 0x80f0, 0x0c00
ax_pose_terminator
sDunsparcePose19:
ax_pose 6, 0x41f3, 0x80f0, 0x0c00
ax_pose_terminator
sDunsparcePose20:
ax_pose 7, 0x41f3, 0x80f0, 0x0c00
ax_pose_terminator
sDunsparcePose21:
ax_pose 8, 0x01eb, 0x80f0, 0x0c00
ax_pose_terminator
sDunsparcePose22:
ax_pose 3, 0x01ef, 0x80f0, 0x0c00
ax_pose_terminator
sDunsparcePose23:
ax_pose 4, 0x01ef, 0x80f0, 0x0c00
ax_pose_terminator
sDunsparcePose24:
ax_pose 5, 0x01eb, 0x80f0, 0x0c00
ax_pose_terminator
sDunsparcePose25:
ax_pose 0, 0x81ef, 0x80f8, 0x0c00
ax_pose_terminator
sDunsparcePose26:
ax_pose 1, 0x81ef, 0x80f8, 0x0c00
ax_pose_terminator
sDunsparcePose27:
ax_pose 2, 0x01eb, 0x80f8, 0x0c00
ax_pose_terminator
sDunsparcePose28:
ax_pose 15, 0x81eb, 0x80f7, 0x0c00
ax_pose_terminator
sDunsparcePose29:
ax_pose 3, 0x01ef, 0x90f1, 0x0c00
ax_pose_terminator
sDunsparcePose30:
ax_pose 4, 0x01ef, 0x90f1, 0x0c00
ax_pose_terminator
sDunsparcePose31:
ax_pose 5, 0x01ec, 0x90f1, 0x0c00
ax_pose_terminator
sDunsparcePose32:
ax_pose 16, 0x81ea, 0x90f6, 0x0c00
ax_pose 17, 0x01fa, 0x10ee, 0x0c08
ax_pose_terminator
sDunsparcePose33:
ax_pose 6, 0x41f3, 0x90f1, 0x0c00
ax_pose_terminator
sDunsparcePose34:
ax_pose 7, 0x41f3, 0x90f1, 0x0c00
ax_pose_terminator
sDunsparcePose35:
ax_pose 8, 0x01ed, 0x90f0, 0x0c00
ax_pose_terminator
sDunsparcePose36:
ax_pose 18, 0x81ec, 0x90f6, 0x0c00
ax_pose 19, 0x01fc, 0x10ee, 0x0c08
ax_pose_terminator
sDunsparcePose37:
ax_pose 9, 0x01ef, 0x90f1, 0x0c00
ax_pose_terminator
sDunsparcePose38:
ax_pose 10, 0x01ee, 0x90f1, 0x0c00
ax_pose_terminator
sDunsparcePose39:
ax_pose 11, 0x01ee, 0x90ef, 0x0c00
ax_pose_terminator
sDunsparcePose40:
ax_pose 20, 0x81eb, 0x90f6, 0x0c00
ax_pose 21, 0x01f3, 0x10ee, 0x0c08
ax_pose_terminator
sDunsparcePose41:
ax_pose 12, 0x81ef, 0x80f8, 0x0c00
ax_pose_terminator
sDunsparcePose42:
ax_pose 13, 0x81ed, 0x80f8, 0x0c00
ax_pose_terminator
sDunsparcePose43:
ax_pose 14, 0x41f4, 0x80f8, 0x0c00
ax_pose_terminator
sDunsparcePose44:
ax_pose 22, 0x81eb, 0x80f8, 0x0c00
ax_pose_terminator
sDunsparcePose45:
ax_pose 9, 0x01ef, 0x80f0, 0x0c00
ax_pose_terminator
sDunsparcePose46:
ax_pose 10, 0x01ee, 0x80f0, 0x0c00
ax_pose_terminator
sDunsparcePose47:
ax_pose 11, 0x01ee, 0x80f2, 0x0c00
ax_pose_terminator
sDunsparcePose48:
ax_pose 20, 0x81eb, 0x80fa, 0x0c00
ax_pose 21, 0x01f3, 0x010a, 0x0c08
ax_pose_terminator
sDunsparcePose49:
ax_pose 6, 0x41f3, 0x80f0, 0x0c00
ax_pose_terminator
sDunsparcePose50:
ax_pose 7, 0x41f3, 0x80f0, 0x0c00
ax_pose_terminator
sDunsparcePose51:
ax_pose 8, 0x01ed, 0x80f1, 0x0c00
ax_pose_terminator
sDunsparcePose52:
ax_pose 18, 0x81ec, 0x80fa, 0x0c00
ax_pose 19, 0x01fc, 0x010a, 0x0c08
ax_pose_terminator
sDunsparcePose53:
ax_pose 3, 0x01ef, 0x80f0, 0x0c00
ax_pose_terminator
sDunsparcePose54:
ax_pose 4, 0x01ef, 0x80f0, 0x0c00
ax_pose_terminator
sDunsparcePose55:
ax_pose 5, 0x01ec, 0x80f0, 0x0c00
ax_pose_terminator
sDunsparcePose56:
ax_pose 16, 0x81ea, 0x80fa, 0x0c00
ax_pose 17, 0x01fa, 0x010a, 0x0c08
ax_pose_terminator
sDunsparcePose57:
ax_pose 0, 0x81ef, 0x80f8, 0x0c00
ax_pose_terminator
sDunsparcePose58:
ax_pose 1, 0x81ef, 0x80f8, 0x0c00
ax_pose_terminator
sDunsparcePose59:
ax_pose 2, 0x01eb, 0x80f8, 0x0c00
ax_pose_terminator
sDunsparcePose60:
ax_pose 15, 0x81eb, 0x80f7, 0x0c00
ax_pose_terminator
sDunsparcePose61:
ax_pose 3, 0x01ef, 0x90f1, 0x0c00
ax_pose_terminator
sDunsparcePose62:
ax_pose 4, 0x01ef, 0x90f1, 0x0c00
ax_pose_terminator
sDunsparcePose63:
ax_pose 5, 0x01ec, 0x90f1, 0x0c00
ax_pose_terminator
sDunsparcePose64:
ax_pose 16, 0x81ea, 0x90f6, 0x0c00
ax_pose 17, 0x01fa, 0x10ee, 0x0c08
ax_pose_terminator
sDunsparcePose65:
ax_pose 6, 0x41f3, 0x90f1, 0x0c00
ax_pose_terminator
sDunsparcePose66:
ax_pose 7, 0x41f3, 0x90f1, 0x0c00
ax_pose_terminator
sDunsparcePose67:
ax_pose 8, 0x01ed, 0x90f0, 0x0c00
ax_pose_terminator
sDunsparcePose68:
ax_pose 18, 0x81ec, 0x90f6, 0x0c00
ax_pose 19, 0x01fc, 0x10ee, 0x0c08
ax_pose_terminator
sDunsparcePose69:
ax_pose 9, 0x01ef, 0x90f1, 0x0c00
ax_pose_terminator
sDunsparcePose70:
ax_pose 10, 0x01ee, 0x90f1, 0x0c00
ax_pose_terminator
sDunsparcePose71:
ax_pose 11, 0x01ee, 0x90ef, 0x0c00
ax_pose_terminator
sDunsparcePose72:
ax_pose 20, 0x81eb, 0x90f6, 0x0c00
ax_pose 21, 0x01f3, 0x10ee, 0x0c08
ax_pose_terminator
sDunsparcePose73:
ax_pose 12, 0x81ef, 0x80f8, 0x0c00
ax_pose_terminator
sDunsparcePose74:
ax_pose 13, 0x81ed, 0x80f8, 0x0c00
ax_pose_terminator
sDunsparcePose75:
ax_pose 14, 0x41f4, 0x80f8, 0x0c00
ax_pose_terminator
sDunsparcePose76:
ax_pose 22, 0x81eb, 0x80f8, 0x0c00
ax_pose_terminator
sDunsparcePose77:
ax_pose 9, 0x01ef, 0x80f0, 0x0c00
ax_pose_terminator
sDunsparcePose78:
ax_pose 10, 0x01ee, 0x80f0, 0x0c00
ax_pose_terminator
sDunsparcePose79:
ax_pose 11, 0x01ee, 0x80f2, 0x0c00
ax_pose_terminator
sDunsparcePose80:
ax_pose 20, 0x81eb, 0x80fa, 0x0c00
ax_pose 21, 0x01f3, 0x010a, 0x0c08
ax_pose_terminator
sDunsparcePose81:
ax_pose 6, 0x41f3, 0x80f0, 0x0c00
ax_pose_terminator
sDunsparcePose82:
ax_pose 7, 0x41f3, 0x80f0, 0x0c00
ax_pose_terminator
sDunsparcePose83:
ax_pose 8, 0x01ed, 0x80f1, 0x0c00
ax_pose_terminator
sDunsparcePose84:
ax_pose 18, 0x81ec, 0x80fa, 0x0c00
ax_pose 19, 0x01fc, 0x010a, 0x0c08
ax_pose_terminator
sDunsparcePose85:
ax_pose 3, 0x01ef, 0x80f0, 0x0c00
ax_pose_terminator
sDunsparcePose86:
ax_pose 4, 0x01ef, 0x80f0, 0x0c00
ax_pose_terminator
sDunsparcePose87:
ax_pose 5, 0x01ec, 0x80f0, 0x0c00
ax_pose_terminator
sDunsparcePose88:
ax_pose 16, 0x81ea, 0x80fa, 0x0c00
ax_pose 17, 0x01fa, 0x010a, 0x0c08
ax_pose_terminator
sDunsparcePose89:
ax_pose 0, 0x81ef, 0x80f8, 0x0c00
ax_pose_terminator
sDunsparcePose90:
ax_pose 1, 0x81ef, 0x80f8, 0x0c00
ax_pose_terminator
sDunsparcePose91:
ax_pose 2, 0x01eb, 0x80f8, 0x0c00
ax_pose_terminator
sDunsparcePose92:
ax_pose 15, 0x81eb, 0x80f7, 0x0c00
ax_pose_terminator
sDunsparcePose93:
ax_pose 3, 0x01ef, 0x90f1, 0x0c00
ax_pose_terminator
sDunsparcePose94:
ax_pose 4, 0x01ef, 0x90f1, 0x0c00
ax_pose_terminator
sDunsparcePose95:
ax_pose 5, 0x01ec, 0x90f1, 0x0c00
ax_pose_terminator
sDunsparcePose96:
ax_pose 16, 0x81ea, 0x90f6, 0x0c00
ax_pose 17, 0x01fa, 0x10ee, 0x0c08
ax_pose_terminator
sDunsparcePose97:
ax_pose 6, 0x41f3, 0x90f1, 0x0c00
ax_pose_terminator
sDunsparcePose98:
ax_pose 7, 0x41f3, 0x90f1, 0x0c00
ax_pose_terminator
sDunsparcePose99:
ax_pose 8, 0x01ed, 0x90f0, 0x0c00
ax_pose_terminator
sDunsparcePose100:
ax_pose 18, 0x81ec, 0x90f6, 0x0c00
ax_pose 19, 0x01fc, 0x10ee, 0x0c08
ax_pose_terminator
sDunsparcePose101:
ax_pose 9, 0x01ef, 0x90f1, 0x0c00
ax_pose_terminator
sDunsparcePose102:
ax_pose 10, 0x01ee, 0x90f1, 0x0c00
ax_pose_terminator
sDunsparcePose103:
ax_pose 11, 0x01ee, 0x90ef, 0x0c00
ax_pose_terminator
sDunsparcePose104:
ax_pose 20, 0x81eb, 0x90f6, 0x0c00
ax_pose 21, 0x01f3, 0x10ee, 0x0c08
ax_pose_terminator
sDunsparcePose105:
ax_pose 12, 0x81ef, 0x80f8, 0x0c00
ax_pose_terminator
sDunsparcePose106:
ax_pose 13, 0x81ed, 0x80f8, 0x0c00
ax_pose_terminator
sDunsparcePose107:
ax_pose 14, 0x41f4, 0x80f8, 0x0c00
ax_pose_terminator
sDunsparcePose108:
ax_pose 22, 0x81eb, 0x80f8, 0x0c00
ax_pose_terminator
sDunsparcePose109:
ax_pose 9, 0x01ef, 0x80f0, 0x0c00
ax_pose_terminator
sDunsparcePose110:
ax_pose 10, 0x01ee, 0x80f0, 0x0c00
ax_pose_terminator
sDunsparcePose111:
ax_pose 11, 0x01ee, 0x80f2, 0x0c00
ax_pose_terminator
sDunsparcePose112:
ax_pose 20, 0x81eb, 0x80fa, 0x0c00
ax_pose 21, 0x01f3, 0x010a, 0x0c08
ax_pose_terminator
sDunsparcePose113:
ax_pose 6, 0x41f3, 0x80f0, 0x0c00
ax_pose_terminator
sDunsparcePose114:
ax_pose 7, 0x41f3, 0x80f0, 0x0c00
ax_pose_terminator
sDunsparcePose115:
ax_pose 8, 0x01ed, 0x80f1, 0x0c00
ax_pose_terminator
sDunsparcePose116:
ax_pose 18, 0x81ec, 0x80fa, 0x0c00
ax_pose 19, 0x01fc, 0x010a, 0x0c08
ax_pose_terminator
sDunsparcePose117:
ax_pose 3, 0x01ef, 0x80f0, 0x0c00
ax_pose_terminator
sDunsparcePose118:
ax_pose 4, 0x01ef, 0x80f0, 0x0c00
ax_pose_terminator
sDunsparcePose119:
ax_pose 5, 0x01ec, 0x80f0, 0x0c00
ax_pose_terminator
sDunsparcePose120:
ax_pose 16, 0x81ea, 0x80fa, 0x0c00
ax_pose 17, 0x01fa, 0x010a, 0x0c08
ax_pose_terminator
sDunsparcePose121:
ax_pose 0, 0x81ef, 0x80f8, 0x0c00
ax_pose_terminator
sDunsparcePose122:
ax_pose 23, 0x01f6, 0x40f7, 0x0c00
ax_pose 24, 0x81f6, 0x0107, 0x0c04
ax_pose_terminator
sDunsparcePose123:
ax_pose 25, 0x81f0, 0x80f9, 0x0c00
ax_pose_terminator
sDunsparcePose124:
ax_pose 3, 0x01ef, 0x90f1, 0x0c00
ax_pose_terminator
sDunsparcePose125:
ax_pose 26, 0x81f3, 0x9100, 0x0c00
ax_pose 27, 0x81f3, 0x10f8, 0x0c08
ax_pose_terminator
sDunsparcePose126:
ax_pose 28, 0x41f7, 0x90ef, 0x0c00
ax_pose 29, 0x01ef, 0x10ff, 0x0c08
ax_pose_terminator
sDunsparcePose127:
ax_pose 6, 0x41f3, 0x90f1, 0x0c00
ax_pose_terminator
sDunsparcePose128:
ax_pose 30, 0x01f3, 0x50fd, 0x0c00
ax_pose 31, 0x81f3, 0x10f5, 0x0c04
ax_pose_terminator
sDunsparcePose129:
ax_pose 32, 0x41f6, 0x90f1, 0x0c00
ax_pose 33, 0x01ee, 0x10f9, 0x0c08
ax_pose_terminator
sDunsparcePose130:
ax_pose 9, 0x01ef, 0x90f1, 0x0c00
ax_pose_terminator
sDunsparcePose131:
ax_pose 34, 0x81ef, 0x90fb, 0x0c00
ax_pose 35, 0x81f7, 0x10f3, 0x0c08
ax_pose_terminator
sDunsparcePose132:
ax_pose 36, 0x01f5, 0x5100, 0x0c00
ax_pose 37, 0x81f5, 0x50f8, 0x0c04
ax_pose_terminator
sDunsparcePose133:
ax_pose 12, 0x81ef, 0x80f8, 0x0c00
ax_pose_terminator
sDunsparcePose134:
ax_pose 38, 0x81ef, 0x80f8, 0x0c00
ax_pose_terminator
sDunsparcePose135:
ax_pose 39, 0x81ef, 0x80f8, 0x0c00
ax_pose_terminator
sDunsparcePose136:
ax_pose 9, 0x01ef, 0x80f0, 0x0c00
ax_pose_terminator
sDunsparcePose137:
ax_pose 34, 0x81ef, 0x80f6, 0x0c00
ax_pose 35, 0x81f7, 0x0106, 0x0c08
ax_pose_terminator
sDunsparcePose138:
ax_pose 36, 0x01f5, 0x40f1, 0x0c00
ax_pose 37, 0x81f5, 0x4101, 0x0c04
ax_pose_terminator
sDunsparcePose139:
ax_pose 6, 0x41f3, 0x80f0, 0x0c00
ax_pose_terminator
sDunsparcePose140:
ax_pose 30, 0x01f3, 0x40f4, 0x0c00
ax_pose 31, 0x81f3, 0x0104, 0x0c04
ax_pose_terminator
sDunsparcePose141:
ax_pose 32, 0x41f6, 0x80f0, 0x0c00
ax_pose 33, 0x01ee, 0x0100, 0x0c08
ax_pose_terminator
sDunsparcePose142:
ax_pose 3, 0x01ef, 0x80f0, 0x0c00
ax_pose_terminator
sDunsparcePose143:
ax_pose 26, 0x81f3, 0x80f1, 0x0c00
ax_pose 27, 0x81f3, 0x0101, 0x0c08
ax_pose_terminator
sDunsparcePose144:
ax_pose 28, 0x41f7, 0x80f2, 0x0c00
ax_pose 29, 0x01ef, 0x00fa, 0x0c08
ax_pose_terminator
sDunsparcePose145:
ax_pose 40, 0x41f6, 0x80f1, 0x0c00
ax_pose_terminator
sDunsparcePose146:
ax_pose 41, 0x41f6, 0x80f1, 0x0c00
ax_pose_terminator
sDunsparcePose147:
ax_pose 42, 0x01e1, 0x80f1, 0x0c00
ax_pose_terminator
sDunsparcePose148:
ax_pose 43, 0x01e1, 0x90ef, 0x0c00
ax_pose_terminator
sDunsparcePose149:
ax_pose 44, 0x01e1, 0x90ed, 0x0c00
ax_pose_terminator
sDunsparcePose150:
ax_pose 45, 0x01e3, 0x90ed, 0x0c00
ax_pose_terminator
sDunsparcePose151:
ax_pose 46, 0x01e3, 0x80f1, 0x0c00
ax_pose_terminator
sDunsparcePose152:
ax_pose 45, 0x01e3, 0x80f3, 0x0c00
ax_pose_terminator
sDunsparcePose153:
ax_pose 44, 0x01e3, 0x80f3, 0x0c00
ax_pose_terminator
sDunsparcePose154:
ax_pose 43, 0x01e3, 0x80f1, 0x0c00
ax_pose_terminator
sDunsparcePose155:
ax_pose 0, 0x81ef, 0x80f8, 0x0c00
ax_pose_terminator
sDunsparcePose156:
ax_pose 23, 0x01f6, 0x40f7, 0x0c00
ax_pose 24, 0x81f6, 0x0107, 0x0c04
ax_pose_terminator
sDunsparcePose157:
ax_pose 25, 0x81f0, 0x80f9, 0x0c00
ax_pose_terminator
sDunsparcePose158:
ax_pose 3, 0x01ef, 0x90f1, 0x0c00
ax_pose_terminator
sDunsparcePose159:
ax_pose 26, 0x81f3, 0x9100, 0x0c00
ax_pose 27, 0x81f3, 0x10f8, 0x0c08
ax_pose_terminator
sDunsparcePose160:
ax_pose 28, 0x41f7, 0x90ef, 0x0c00
ax_pose 29, 0x01ef, 0x10ff, 0x0c08
ax_pose_terminator
sDunsparcePose161:
ax_pose 6, 0x41f3, 0x90f1, 0x0c00
ax_pose_terminator
sDunsparcePose162:
ax_pose 30, 0x01f3, 0x50fd, 0x0c00
ax_pose 31, 0x81f3, 0x10f5, 0x0c04
ax_pose_terminator
sDunsparcePose163:
ax_pose 32, 0x41f6, 0x90f1, 0x0c00
ax_pose 33, 0x01ee, 0x10f9, 0x0c08
ax_pose_terminator
sDunsparcePose164:
ax_pose 9, 0x01ef, 0x90f1, 0x0c00
ax_pose_terminator
sDunsparcePose165:
ax_pose 34, 0x81ef, 0x90fb, 0x0c00
ax_pose 35, 0x81f7, 0x10f3, 0x0c08
ax_pose_terminator
sDunsparcePose166:
ax_pose 36, 0x01f5, 0x5100, 0x0c00
ax_pose 37, 0x81f5, 0x50f8, 0x0c04
ax_pose_terminator
sDunsparcePose167:
ax_pose 12, 0x81ef, 0x80f8, 0x0c00
ax_pose_terminator
sDunsparcePose168:
ax_pose 38, 0x81ef, 0x80f8, 0x0c00
ax_pose_terminator
sDunsparcePose169:
ax_pose 39, 0x81ef, 0x80f8, 0x0c00
ax_pose_terminator
sDunsparcePose170:
ax_pose 9, 0x01ef, 0x80f0, 0x0c00
ax_pose_terminator
sDunsparcePose171:
ax_pose 34, 0x81ef, 0x80f6, 0x0c00
ax_pose 35, 0x81f7, 0x0106, 0x0c08
ax_pose_terminator
sDunsparcePose172:
ax_pose 36, 0x01f5, 0x40f1, 0x0c00
ax_pose 37, 0x81f5, 0x4101, 0x0c04
ax_pose_terminator
sDunsparcePose173:
ax_pose 6, 0x41f3, 0x80f0, 0x0c00
ax_pose_terminator
sDunsparcePose174:
ax_pose 30, 0x01f3, 0x40f4, 0x0c00
ax_pose 31, 0x81f3, 0x0104, 0x0c04
ax_pose_terminator
sDunsparcePose175:
ax_pose 32, 0x41f6, 0x80f0, 0x0c00
ax_pose 33, 0x01ee, 0x0100, 0x0c08
ax_pose_terminator
sDunsparcePose176:
ax_pose 3, 0x01ef, 0x80f0, 0x0c00
ax_pose_terminator
sDunsparcePose177:
ax_pose 26, 0x81f3, 0x80f1, 0x0c00
ax_pose 27, 0x81f3, 0x0101, 0x0c08
ax_pose_terminator
sDunsparcePose178:
ax_pose 28, 0x41f7, 0x80f2, 0x0c00
ax_pose 29, 0x01ef, 0x00fa, 0x0c08
ax_pose_terminator
sDunsparcePose179:
ax_pose 0, 0x81ef, 0x80f8, 0x0c00
ax_pose_terminator
sDunsparcePose180:
ax_pose 3, 0x01ef, 0x80f0, 0x0c00
ax_pose_terminator
sDunsparcePose181:
ax_pose 6, 0x41f3, 0x80f0, 0x0c00
ax_pose_terminator
sDunsparcePose182:
ax_pose 9, 0x01ef, 0x80f0, 0x0c00
ax_pose_terminator
sDunsparcePose183:
ax_pose 12, 0x81ef, 0x80f8, 0x0c00
ax_pose_terminator
sDunsparcePose184:
ax_pose 9, 0x01ef, 0x90f1, 0x0c00
ax_pose_terminator
sDunsparcePose185:
ax_pose 6, 0x41f3, 0x90f1, 0x0c00
ax_pose_terminator
sDunsparcePose186:
ax_pose 3, 0x01ef, 0x90f1, 0x0c00
ax_pose_terminator
sDunsparcePose187:
ax_pose 15, 0x81eb, 0x80f7, 0x0c00
ax_pose_terminator
sDunsparcePose188:
ax_pose 16, 0x81ea, 0x90f7, 0x0c00
ax_pose 17, 0x01fa, 0x10ef, 0x0c08
ax_pose_terminator
sDunsparcePose189:
ax_pose 18, 0x81eb, 0x90f8, 0x0c00
ax_pose 19, 0x01fb, 0x10f0, 0x0c08
ax_pose_terminator
sDunsparcePose190:
ax_pose 20, 0x81e9, 0x90f8, 0x0c00
ax_pose 21, 0x01f1, 0x10f0, 0x0c08
ax_pose_terminator
sDunsparcePose191:
ax_pose 22, 0x81e9, 0x80f8, 0x0c00
ax_pose_terminator
sDunsparcePose192:
ax_pose 20, 0x81e9, 0x80f8, 0x0c00
ax_pose 21, 0x01f1, 0x0108, 0x0c08
ax_pose_terminator
sDunsparcePose193:
ax_pose 18, 0x81eb, 0x80f8, 0x0c00
ax_pose 19, 0x01fb, 0x0108, 0x0c08
ax_pose_terminator
sDunsparcePose194:
ax_pose 16, 0x81ea, 0x80f9, 0x0c00
ax_pose 17, 0x01fa, 0x0109, 0x0c08
ax_pose_terminator
sDunsparcePose195:
ax_pose 0, 0x81ef, 0x80f8, 0x0c00
ax_pose_terminator
sDunsparcePose196:
ax_pose 1, 0x81ef, 0x80f8, 0x0c00
ax_pose_terminator
sDunsparcePose197:
ax_pose 2, 0x01eb, 0x80f8, 0x0c00
ax_pose_terminator
sDunsparcePose198:
ax_pose 3, 0x01ef, 0x90f1, 0x0c00
ax_pose_terminator
sDunsparcePose199:
ax_pose 4, 0x01ef, 0x90f1, 0x0c00
ax_pose_terminator
sDunsparcePose200:
ax_pose 5, 0x01ec, 0x90f1, 0x0c00
ax_pose_terminator
sDunsparcePose201:
ax_pose 6, 0x41f3, 0x90f1, 0x0c00
ax_pose_terminator
sDunsparcePose202:
ax_pose 7, 0x41f3, 0x90f1, 0x0c00
ax_pose_terminator
sDunsparcePose203:
ax_pose 8, 0x01ed, 0x90f0, 0x0c00
ax_pose_terminator
sDunsparcePose204:
ax_pose 9, 0x01ef, 0x90f1, 0x0c00
ax_pose_terminator
sDunsparcePose205:
ax_pose 10, 0x01ee, 0x90f1, 0x0c00
ax_pose_terminator
sDunsparcePose206:
ax_pose 11, 0x01ee, 0x90f0, 0x0c00
ax_pose_terminator
sDunsparcePose207:
ax_pose 12, 0x81ef, 0x80f8, 0x0c00
ax_pose_terminator
sDunsparcePose208:
ax_pose 13, 0x81ed, 0x80f8, 0x0c00
ax_pose_terminator
sDunsparcePose209:
ax_pose 14, 0x41f4, 0x80f8, 0x0c00
ax_pose_terminator
sDunsparcePose210:
ax_pose 9, 0x01ef, 0x80ef, 0x0c00
ax_pose_terminator
sDunsparcePose211:
ax_pose 10, 0x01ee, 0x80ef, 0x0c00
ax_pose_terminator
sDunsparcePose212:
ax_pose 11, 0x01ee, 0x80f0, 0x0c00
ax_pose_terminator
sDunsparcePose213:
ax_pose 6, 0x41f3, 0x80ef, 0x0c00
ax_pose_terminator
sDunsparcePose214:
ax_pose 7, 0x41f3, 0x80ef, 0x0c00
ax_pose_terminator
sDunsparcePose215:
ax_pose 8, 0x01ed, 0x80f0, 0x0c00
ax_pose_terminator
sDunsparcePose216:
ax_pose 3, 0x01ef, 0x80ef, 0x0c00
ax_pose_terminator
sDunsparcePose217:
ax_pose 4, 0x01ef, 0x80ef, 0x0c00
ax_pose_terminator
sDunsparcePose218:
ax_pose 5, 0x01ec, 0x80ef, 0x0c00
ax_pose_terminator
sDunsparcePose219:
ax_pose 25, 0x81f0, 0x80f9, 0x0c00
ax_pose_terminator
sDunsparcePose220:
ax_pose 28, 0x41f7, 0x80f2, 0x0c00
ax_pose 29, 0x01ef, 0x00fa, 0x0c08
ax_pose_terminator
sDunsparcePose221:
ax_pose 32, 0x41f6, 0x80f0, 0x0c00
ax_pose 33, 0x01ee, 0x0100, 0x0c08
ax_pose_terminator
sDunsparcePose222:
ax_pose 36, 0x01f5, 0x40f1, 0x0c00
ax_pose 37, 0x81f5, 0x4101, 0x0c04
ax_pose_terminator
sDunsparcePose223:
ax_pose 39, 0x81ef, 0x80f8, 0x0c00
ax_pose_terminator
sDunsparcePose224:
ax_pose 36, 0x01f5, 0x5100, 0x0c00
ax_pose 37, 0x81f5, 0x50f8, 0x0c04
ax_pose_terminator
sDunsparcePose225:
ax_pose 32, 0x41f6, 0x90f1, 0x0c00
ax_pose 33, 0x01ee, 0x10f9, 0x0c08
ax_pose_terminator
sDunsparcePose226:
ax_pose 28, 0x41f7, 0x90ef, 0x0c00
ax_pose 29, 0x01ef, 0x10ff, 0x0c08
ax_pose_terminator
sDunsparcePose227:
ax_pose 0, 0x81ef, 0x80f8, 0x0c00
ax_pose_terminator
sDunsparcePose228:
ax_pose 3, 0x01ef, 0x80f0, 0x0c00
ax_pose_terminator
sDunsparcePose229:
ax_pose 6, 0x41f3, 0x80f0, 0x0c00
ax_pose_terminator
sDunsparcePose230:
ax_pose 9, 0x01ef, 0x80f0, 0x0c00
ax_pose_terminator
sDunsparcePose231:
ax_pose 12, 0x81ef, 0x80f8, 0x0c00
ax_pose_terminator
sDunsparcePose232:
ax_pose 9, 0x01ef, 0x90f1, 0x0c00
ax_pose_terminator
sDunsparcePose233:
ax_pose 6, 0x41f3, 0x90f1, 0x0c00
ax_pose_terminator
sDunsparcePose234:
ax_pose 3, 0x01ef, 0x90f1, 0x0c00
ax_pose_terminator
.align 2
sDunsparceAnims_1_1:
ax_anim 8, 0, 0, 0, 0, 0, 0,
ax_anim 6, 0, 1, 0, -1, 0, 0,
ax_anim 6, 0, 1, 0, -4, 0, 0,
ax_anim 6, 0, 2, 0, -4, 0, 0,
ax_anim 6, 0, 2, 0, -1, 0, 0,
ax_anim_terminator
sDunsparceAnims_1_2:
ax_anim 8, 0, 3, 0, 0, 0, 0,
ax_anim 6, 0, 4, 0, -1, 0, 0,
ax_anim 6, 0, 4, 0, -4, 0, 0,
ax_anim 6, 0, 5, 0, -3, 0, 0,
ax_anim 6, 0, 5, 0, -1, 0, 0,
ax_anim_terminator
sDunsparceAnims_1_3:
ax_anim 8, 0, 6, 0, 0, 0, 0,
ax_anim 6, 0, 7, 0, -1, 0, 0,
ax_anim 6, 0, 7, 0, -6, 0, 0,
ax_anim 6, 0, 8, 0, -3, 0, 0,
ax_anim 6, 0, 8, 0, -1, 0, 0,
ax_anim_terminator
sDunsparceAnims_1_4:
ax_anim 8, 0, 9, 0, 0, 0, 0,
ax_anim 6, 0, 10, 0, -1, 0, 0,
ax_anim 6, 0, 10, 0, -6, 0, 0,
ax_anim 6, 0, 11, 0, -3, 0, 0,
ax_anim 6, 0, 11, 0, -1, 0, 0,
ax_anim_terminator
sDunsparceAnims_1_5:
ax_anim 8, 0, 12, 0, 0, 0, 0,
ax_anim 6, 0, 13, 0, -3, 0, 0,
ax_anim 6, 0, 13, 0, -8, 0, 0,
ax_anim 6, 0, 14, 0, -7, 0, 0,
ax_anim 6, 0, 14, 0, -3, 0, 0,
ax_anim_terminator
sDunsparceAnims_1_6:
ax_anim 8, 0, 15, 0, 0, 0, 0,
ax_anim 6, 0, 16, 0, -1, 0, 0,
ax_anim 6, 0, 16, 0, -6, 0, 0,
ax_anim 6, 0, 17, 0, -3, 0, 0,
ax_anim 6, 0, 17, 0, -1, 0, 0,
ax_anim_terminator
sDunsparceAnims_1_7:
ax_anim 8, 0, 18, 0, 0, 0, 0,
ax_anim 6, 0, 19, 0, -1, 0, 0,
ax_anim 6, 0, 19, 0, -6, 0, 0,
ax_anim 6, 0, 20, 0, -3, 0, 0,
ax_anim 6, 0, 20, 0, -1, 0, 0,
ax_anim_terminator
sDunsparceAnims_1_8:
ax_anim 8, 0, 21, 0, 0, 0, 0,
ax_anim 6, 0, 22, 0, -1, 0, 0,
ax_anim 6, 0, 22, 0, -4, 0, 0,
ax_anim 6, 0, 23, 0, -3, 0, 0,
ax_anim 6, 0, 23, 0, -1, 0, 0,
ax_anim_terminator
.align 2
sDunsparceAnims_2_1:
ax_anim 2, 0, 27, 0, 0, 0, 0,
ax_anim 2, 0, 27, 0, -1, 0, -1,
ax_anim 4, 0, 27, 0, -2, 0, -2,
ax_anim 1, 0, 25, 0, -3, 0, 2,
ax_anim 2, 2, 25, 0, 3, 0, 7,
ax_anim 2, 0, 26, 0, 9, 0, 10,
ax_anim 2, 1, 26, 0, 12, 0, 12,
ax_anim 2, 0, 26, -1, 12, -1, 12,
ax_anim 2, 0, 26, 0, 12, 0, 12,
ax_anim 2, 0, 26, -1, 12, -1, 12,
ax_anim 2, 0, 24, 0, 6, 0, 6,
ax_anim_terminator
sDunsparceAnims_2_2:
ax_anim 2, 0, 31, 0, 0, 0, 0,
ax_anim 2, 0, 31, -1, -1, -1, -1,
ax_anim 4, 0, 31, -2, -2, -2, -2,
ax_anim 1, 0, 29, 4, -1, 4, 2,
ax_anim 2, 2, 29, 10, 3, 10, 8,
ax_anim 2, 0, 30, 15, 7, 15, 13,
ax_anim 2, 1, 30, 18, 16, 18, 16,
ax_anim 2, 0, 30, 19, 15, 19, 15,
ax_anim 2, 0, 30, 18, 16, 18, 16,
ax_anim 2, 0, 30, 19, 15, 19, 15,
ax_anim 2, 0, 28, 6, 6, 6, 6,
ax_anim_terminator
sDunsparceAnims_2_3:
ax_anim 2, 0, 35, 0, 0, 0, 0,
ax_anim 2, 0, 35, -1, 0, -1, 0,
ax_anim 4, 0, 35, -2, 0, -2, 0,
ax_anim 1, 0, 33, 2, -3, 2, 0,
ax_anim 2, 2, 33, 7, -5, 7, 0,
ax_anim 2, 0, 34, 13, -5, 13, 0,
ax_anim 2, 1, 34, 18, -1, 18, -1,
ax_anim 2, 0, 34, 18, 0, 18, 0,
ax_anim 2, 0, 34, 18, -1, 18, -1,
ax_anim 2, 0, 34, 18, 0, 18, 0,
ax_anim 2, 0, 32, 6, 0, 6, 0,
ax_anim_terminator
sDunsparceAnims_2_4:
ax_anim 2, 0, 39, 0, 0, 0, 0,
ax_anim 2, 0, 39, -1, 1, -1, 1,
ax_anim 4, 0, 39, -2, 2, -2, 2,
ax_anim 1, 0, 37, 0, -6, 0, -1,
ax_anim 2, 2, 37, 6, -15, 6, -9,
ax_anim 2, 0, 38, 12, -22, 12, -17,
ax_anim 2, 1, 38, 18, -25, 18, -25,
ax_anim 2, 0, 38, 17, -26, 17, -26,
ax_anim 2, 0, 38, 18, -25, 18, -25,
ax_anim 2, 0, 38, 17, -26, 17, -26,
ax_anim 2, 0, 36, 6, -9, 6, -9,
ax_anim_terminator
sDunsparceAnims_2_5:
ax_anim 2, 0, 43, 0, 0, 0, 0,
ax_anim 2, 0, 43, 0, 1, 0, 1,
ax_anim 4, 0, 43, 0, 2, 0, 2,
ax_anim 1, 0, 41, 0, -4, 0, -2,
ax_anim 2, 2, 41, 0, -12, 0, -9,
ax_anim 2, 0, 42, 0, -19, 0, -17,
ax_anim 2, 1, 42, 0, -23, 0, -23,
ax_anim 2, 0, 42, -1, -23, -1, -23,
ax_anim 2, 0, 42, 0, -23, 0, -23,
ax_anim 2, 0, 42, -1, -23, -1, -23,
ax_anim 2, 0, 40, 0, -6, 0, -6,
ax_anim_terminator
sDunsparceAnims_2_6:
ax_anim 2, 0, 47, 0, 0, 0, 0,
ax_anim 2, 0, 47, 1, 1, 1, 1,
ax_anim 4, 0, 47, 2, 2, 2, 2,
ax_anim 1, 0, 45, 0, -6, 0, -1,
ax_anim 2, 2, 45, -6, -15, -6, -9,
ax_anim 2, 0, 46, -12, -22, -12, -17,
ax_anim 2, 1, 46, -18, -25, -18, -25,
ax_anim 2, 0, 46, -17, -26, -17, -26,
ax_anim 2, 0, 46, -18, -25, -18, -25,
ax_anim 2, 0, 46, -17, -26, -17, -26,
ax_anim 2, 0, 44, -6, -9, -6, -9,
ax_anim_terminator
sDunsparceAnims_2_7:
ax_anim 2, 0, 51, 0, 0, 0, 0,
ax_anim 2, 0, 51, 1, 0, 1, 0,
ax_anim 4, 0, 51, 2, 0, 2, 0,
ax_anim 1, 0, 49, -2, -3, -2, 0,
ax_anim 2, 2, 49, -7, -5, -7, 0,
ax_anim 2, 0, 50, -13, -5, -13, 0,
ax_anim 2, 1, 50, -17, -1, -17, -1,
ax_anim 2, 0, 50, -17, 0, -17, 0,
ax_anim 2, 0, 50, -17, -1, -17, -1,
ax_anim 2, 0, 50, -17, 0, -17, 0,
ax_anim 2, 0, 48, -6, 0, -6, 0,
ax_anim_terminator
sDunsparceAnims_2_8:
ax_anim 2, 0, 55, 0, 0, 0, 0,
ax_anim 2, 0, 55, 1, -1, 1, -1,
ax_anim 4, 0, 55, 2, -2, 2, -2,
ax_anim 1, 0, 53, -4, -1, -4, 2,
ax_anim 2, 2, 53, -10, 3, -10, 8,
ax_anim 2, 0, 54, -15, 7, -15, 13,
ax_anim 2, 1, 54, -18, 16, -18, 16,
ax_anim 2, 0, 54, -19, 15, -19, 15,
ax_anim 2, 0, 54, -18, 16, -18, 16,
ax_anim 2, 0, 54, -19, 15, -19, 15,
ax_anim 2, 0, 52, -6, 6, -6, 6,
ax_anim_terminator
.align 2
sDunsparceAnims_3_1:
ax_anim 2, 0, 59, 0, 0, 0, 0,
ax_anim 2, 0, 59, 0, -1, 0, -1,
ax_anim 4, 0, 59, 0, -2, 0, -2,
ax_anim 1, 0, 57, 0, -3, 0, 2,
ax_anim 2, 2, 57, 0, 3, 0, 7,
ax_anim 2, 0, 58, 0, 9, 0, 10,
ax_anim 2, 1, 58, 0, 12, 0, 12,
ax_anim 2, 0, 58, -1, 12, -1, 12,
ax_anim 2, 0, 58, 0, 12, 0, 12,
ax_anim 2, 0, 58, -1, 12, -1, 12,
ax_anim 2, 0, 56, 0, 6, 0, 6,
ax_anim_terminator
sDunsparceAnims_3_2:
ax_anim 2, 0, 63, 0, 0, 0, 0,
ax_anim 2, 0, 63, -1, -1, -1, -1,
ax_anim 4, 0, 63, -2, -2, -2, -2,
ax_anim 1, 0, 61, 4, -1, 4, 2,
ax_anim 2, 2, 61, 10, 3, 10, 8,
ax_anim 2, 0, 62, 15, 7, 15, 13,
ax_anim 2, 1, 62, 18, 16, 18, 16,
ax_anim 2, 0, 62, 19, 15, 19, 15,
ax_anim 2, 0, 62, 18, 16, 18, 16,
ax_anim 2, 0, 62, 19, 15, 19, 15,
ax_anim 2, 0, 60, 6, 6, 6, 6,
ax_anim_terminator
sDunsparceAnims_3_3:
ax_anim 2, 0, 67, 0, 0, 0, 0,
ax_anim 2, 0, 67, -1, 0, -1, 0,
ax_anim 4, 0, 67, -2, 0, -2, 0,
ax_anim 1, 0, 65, 2, -3, 2, 0,
ax_anim 2, 2, 65, 7, -5, 7, 0,
ax_anim 2, 0, 66, 13, -5, 13, 0,
ax_anim 2, 1, 66, 18, -1, 18, -1,
ax_anim 2, 0, 66, 18, 0, 18, 0,
ax_anim 2, 0, 66, 18, -1, 18, -1,
ax_anim 2, 0, 66, 18, 0, 18, 0,
ax_anim 2, 0, 64, 6, 0, 6, 0,
ax_anim_terminator
sDunsparceAnims_3_4:
ax_anim 2, 0, 71, 0, 0, 0, 0,
ax_anim 2, 0, 71, -1, 1, -1, 1,
ax_anim 4, 0, 71, -2, 2, -2, 2,
ax_anim 1, 0, 69, 0, -6, 0, -1,
ax_anim 2, 2, 69, 6, -15, 6, -9,
ax_anim 2, 0, 70, 12, -22, 12, -17,
ax_anim 2, 1, 70, 18, -25, 18, -25,
ax_anim 2, 0, 70, 17, -26, 17, -26,
ax_anim 2, 0, 70, 18, -25, 18, -25,
ax_anim 2, 0, 70, 17, -26, 17, -26,
ax_anim 2, 0, 68, 6, -9, 6, -9,
ax_anim_terminator
sDunsparceAnims_3_5:
ax_anim 2, 0, 75, 0, 0, 0, 0,
ax_anim 2, 0, 75, 0, 1, 0, 1,
ax_anim 4, 0, 75, 0, 2, 0, 2,
ax_anim 1, 0, 73, 0, -4, 0, -2,
ax_anim 2, 2, 73, 0, -12, 0, -9,
ax_anim 2, 0, 74, 0, -19, 0, -17,
ax_anim 2, 1, 74, 0, -23, 0, -23,
ax_anim 2, 0, 74, -1, -23, -1, -23,
ax_anim 2, 0, 74, 0, -23, 0, -23,
ax_anim 2, 0, 74, -1, -23, -1, -23,
ax_anim 2, 0, 72, 0, -6, 0, -6,
ax_anim_terminator
sDunsparceAnims_3_6:
ax_anim 2, 0, 79, 0, 0, 0, 0,
ax_anim 2, 0, 79, 1, 1, 1, 1,
ax_anim 4, 0, 79, 2, 2, 2, 2,
ax_anim 1, 0, 77, 0, -6, 0, -1,
ax_anim 2, 2, 77, -6, -15, -6, -9,
ax_anim 2, 0, 78, -12, -22, -12, -17,
ax_anim 2, 1, 78, -18, -25, -18, -25,
ax_anim 2, 0, 78, -17, -26, -17, -26,
ax_anim 2, 0, 78, -18, -25, -18, -25,
ax_anim 2, 0, 78, -17, -26, -17, -26,
ax_anim 2, 0, 76, -6, -9, -6, -9,
ax_anim_terminator
sDunsparceAnims_3_7:
ax_anim 2, 0, 83, 0, 0, 0, 0,
ax_anim 2, 0, 83, 1, 0, 1, 0,
ax_anim 4, 0, 83, 2, 0, 2, 0,
ax_anim 1, 0, 81, -2, -3, -2, 0,
ax_anim 2, 2, 81, -7, -5, -7, 0,
ax_anim 2, 0, 82, -13, -5, -13, 0,
ax_anim 2, 1, 82, -17, -1, -17, -1,
ax_anim 2, 0, 82, -17, 0, -17, 0,
ax_anim 2, 0, 82, -17, -1, -17, -1,
ax_anim 2, 0, 82, -17, 0, -17, 0,
ax_anim 2, 0, 80, -6, 0, -6, 0,
ax_anim_terminator
sDunsparceAnims_3_8:
ax_anim 2, 0, 87, 0, 0, 0, 0,
ax_anim 2, 0, 87, 1, -1, 1, -1,
ax_anim 4, 0, 87, 2, -2, 2, -2,
ax_anim 1, 0, 85, -4, -1, -4, 2,
ax_anim 2, 2, 85, -10, 3, -10, 8,
ax_anim 2, 0, 86, -15, 7, -15, 13,
ax_anim 2, 1, 86, -18, 16, -18, 16,
ax_anim 2, 0, 86, -19, 15, -19, 15,
ax_anim 2, 0, 86, -18, 16, -18, 16,
ax_anim 2, 0, 86, -19, 15, -19, 15,
ax_anim 2, 0, 84, -6, 6, -6, 6,
ax_anim_terminator
.align 2
sDunsparceAnims_4_1:
ax_anim 2, 0, 91, 0, -2, 0, -2,
ax_anim 6, 2, 91, 0, -3, 0, -3,
ax_anim 2, 0, 88, 0, -1, 0, -1,
ax_anim 2, 1, 90, 0, 3, 0, 2,
ax_anim 2, 0, 90, 1, 3, 1, 2,
ax_anim 2, 0, 90, 0, 3, 0, 2,
ax_anim 2, 0, 90, 1, 3, 1, 2,
ax_anim 2, 0, 90, 0, 3, 0, 2,
ax_anim 2, 0, 90, 1, 3, 1, 2,
ax_anim 2, 0, 90, 0, 3, 0, 2,
ax_anim 2, 0, 88, 0, 1, 0, 1,
ax_anim_terminator
sDunsparceAnims_4_2:
ax_anim 2, 0, 95, -2, -2, -2, -2,
ax_anim 6, 2, 95, -3, -3, -3, -3,
ax_anim 2, 0, 92, -1, -1, -1, -1,
ax_anim 2, 1, 94, 2, 2, 1, 1,
ax_anim 2, 0, 94, 3, 1, 2, 0,
ax_anim 2, 0, 94, 2, 2, 1, 1,
ax_anim 2, 0, 94, 3, 1, 2, 0,
ax_anim 2, 0, 94, 2, 2, 1, 1,
ax_anim 2, 0, 94, 3, 1, 2, 0,
ax_anim 2, 0, 94, 2, 2, 1, 1,
ax_anim 2, 0, 92, 1, 1, 1, 1,
ax_anim_terminator
sDunsparceAnims_4_3:
ax_anim 2, 0, 99, -2, 0, -2, 0,
ax_anim 6, 2, 99, -3, 0, -3, 0,
ax_anim 2, 0, 96, -1, 0, -1, 0,
ax_anim 2, 1, 98, 2, 0, 2, 0,
ax_anim 2, 0, 98, 2, 1, 2, 1,
ax_anim 2, 0, 98, 2, 0, 2, 0,
ax_anim 2, 0, 98, 2, 1, 2, 1,
ax_anim 2, 0, 98, 2, 0, 2, 0,
ax_anim 2, 0, 98, 2, 1, 2, 1,
ax_anim 2, 0, 98, 2, 0, 2, 0,
ax_anim 2, 0, 96, 1, 0, 1, 0,
ax_anim_terminator
sDunsparceAnims_4_4:
ax_anim 2, 0, 103, -2, 2, -2, 2,
ax_anim 6, 2, 103, -3, 3, -3, 3,
ax_anim 2, 0, 100, -1, 1, -1, 1,
ax_anim 2, 1, 102, 2, -2, 1, -1,
ax_anim 2, 0, 102, 3, -1, 2, 0,
ax_anim 2, 0, 102, 2, -2, 1, -1,
ax_anim 2, 0, 102, 3, -1, 2, 0,
ax_anim 2, 0, 102, 2, -2, 1, -1,
ax_anim 2, 0, 102, 3, -1, 2, 0,
ax_anim 2, 0, 102, 2, -2, 1, -1,
ax_anim 2, 0, 100, 1, -1, 1, -1,
ax_anim_terminator
sDunsparceAnims_4_5:
ax_anim 2, 0, 107, 0, 2, 0, 2,
ax_anim 6, 2, 107, 0, 3, 0, 3,
ax_anim 2, 0, 104, 0, 1, 0, 1,
ax_anim 2, 1, 106, 0, -3, 0, -2,
ax_anim 2, 0, 106, 1, -3, 1, -2,
ax_anim 2, 0, 106, 0, -3, 0, -2,
ax_anim 2, 0, 106, 1, -3, 1, -2,
ax_anim 2, 0, 106, 0, -3, 0, -2,
ax_anim 2, 0, 106, 1, -3, 1, -2,
ax_anim 2, 0, 106, 0, -3, 0, -2,
ax_anim 2, 0, 104, 0, -1, 0, -1,
ax_anim_terminator
sDunsparceAnims_4_6:
ax_anim 2, 0, 111, 2, 2, 2, 2,
ax_anim 6, 2, 111, 3, 3, 3, 3,
ax_anim 2, 0, 108, 1, 1, 1, 1,
ax_anim 2, 1, 110, -2, -2, -1, -1,
ax_anim 2, 0, 110, -3, -1, -2, 0,
ax_anim 2, 0, 110, -2, -2, -1, -1,
ax_anim 2, 0, 110, -3, -1, -2, 0,
ax_anim 2, 0, 110, -2, -2, -1, -1,
ax_anim 2, 0, 110, -3, -1, -2, 0,
ax_anim 2, 0, 110, -2, -2, -1, -1,
ax_anim 2, 0, 108, -1, -1, -1, -1,
ax_anim_terminator
sDunsparceAnims_4_7:
ax_anim 2, 0, 115, 2, 0, 2, 0,
ax_anim 6, 2, 115, 3, 0, 3, 0,
ax_anim 2, 0, 112, 1, 0, 1, 0,
ax_anim 2, 1, 114, -2, 0, -2, 0,
ax_anim 2, 0, 114, -2, 1, -2, 1,
ax_anim 2, 0, 114, -2, 0, -2, 0,
ax_anim 2, 0, 114, -2, 1, -2, 1,
ax_anim 2, 0, 114, -2, 0, -2, 0,
ax_anim 2, 0, 114, -2, 1, -2, 1,
ax_anim 2, 0, 114, -2, 0, -2, 0,
ax_anim 2, 0, 112, -1, 0, -1, 0,
ax_anim_terminator
sDunsparceAnims_4_8:
ax_anim 2, 0, 119, 2, -2, 2, -2,
ax_anim 6, 2, 119, 3, -3, 3, -3,
ax_anim 2, 0, 116, 1, -1, 1, -1,
ax_anim 2, 1, 118, -2, 2, -1, 1,
ax_anim 2, 0, 118, -3, 1, -2, 0,
ax_anim 2, 0, 118, -2, 2, -1, 1,
ax_anim 2, 0, 118, -3, 1, -2, 0,
ax_anim 2, 0, 118, -2, 2, -1, 1,
ax_anim 2, 0, 118, -3, 1, -2, 0,
ax_anim 2, 0, 118, -2, 2, -1, 1,
ax_anim 2, 0, 116, -1, 1, -1, 1,
ax_anim_terminator
.align 2
sDunsparceAnims_5_1:
ax_anim 6, 0, 121, 0, 0, 0, 0,
ax_anim 2, 0, 120, 0, 0, 0, 0,
ax_anim 6, 2, 122, 0, 0, 0, 0,
ax_anim 2, 0, 120, 0, 0, 0, 0,
ax_anim 6, 0, 121, 0, 0, 0, 0,
ax_anim 2, 0, 120, 0, 0, 0, 0,
ax_anim 6, 0, 122, 0, 0, 0, 0,
ax_anim_terminator
sDunsparceAnims_5_2:
ax_anim 6, 0, 124, 0, 0, 0, 0,
ax_anim 2, 0, 123, 0, 0, 0, 0,
ax_anim 6, 2, 125, 0, 0, 0, 0,
ax_anim 2, 0, 123, 0, 0, 0, 0,
ax_anim 6, 0, 124, 0, 0, 0, 0,
ax_anim 2, 0, 123, 0, 0, 0, 0,
ax_anim 6, 0, 125, 0, 0, 0, 0,
ax_anim_terminator
sDunsparceAnims_5_3:
ax_anim 6, 0, 127, 0, 0, 0, 0,
ax_anim 2, 0, 126, 0, 0, 0, 0,
ax_anim 6, 2, 128, 0, 0, 0, 0,
ax_anim 2, 0, 126, 0, 0, 0, 0,
ax_anim 6, 0, 127, 0, 0, 0, 0,
ax_anim 2, 0, 126, 0, 0, 0, 0,
ax_anim 6, 0, 128, 0, 0, 0, 0,
ax_anim_terminator
sDunsparceAnims_5_4:
ax_anim 6, 0, 130, 0, 0, 0, 0,
ax_anim 2, 0, 129, 0, 0, 0, 0,
ax_anim 6, 2, 131, 0, 0, 0, 0,
ax_anim 2, 0, 129, 0, 0, 0, 0,
ax_anim 6, 0, 130, 0, 0, 0, 0,
ax_anim 2, 0, 129, 0, 0, 0, 0,
ax_anim 6, 0, 131, 0, 0, 0, 0,
ax_anim_terminator
sDunsparceAnims_5_5:
ax_anim 6, 0, 133, 0, 0, 0, 0,
ax_anim 2, 0, 132, 0, 0, 0, 0,
ax_anim 6, 2, 134, 0, 0, 0, 0,
ax_anim 2, 0, 132, 0, 0, 0, 0,
ax_anim 6, 0, 133, 0, 0, 0, 0,
ax_anim 2, 0, 132, 0, 0, 0, 0,
ax_anim 6, 0, 134, 0, 0, 0, 0,
ax_anim_terminator
sDunsparceAnims_5_6:
ax_anim 6, 0, 136, 0, 0, 0, 0,
ax_anim 2, 0, 135, 0, 0, 0, 0,
ax_anim 6, 2, 137, 0, 0, 0, 0,
ax_anim 2, 0, 135, 0, 0, 0, 0,
ax_anim 6, 0, 136, 0, 0, 0, 0,
ax_anim 2, 0, 135, 0, 0, 0, 0,
ax_anim 6, 0, 137, 0, 0, 0, 0,
ax_anim_terminator
sDunsparceAnims_5_7:
ax_anim 6, 0, 139, 0, 0, 0, 0,
ax_anim 2, 0, 138, 0, 0, 0, 0,
ax_anim 6, 2, 140, 0, 0, 0, 0,
ax_anim 2, 0, 138, 0, 0, 0, 0,
ax_anim 6, 0, 139, 0, 0, 0, 0,
ax_anim 2, 0, 138, 0, 0, 0, 0,
ax_anim 6, 0, 140, 0, 0, 0, 0,
ax_anim_terminator
sDunsparceAnims_5_8:
ax_anim 6, 0, 142, 0, 0, 0, 0,
ax_anim 2, 0, 141, 0, 0, 0, 0,
ax_anim 6, 2, 143, 0, 0, 0, 0,
ax_anim 2, 0, 141, 0, 0, 0, 0,
ax_anim 6, 0, 142, 0, 0, 0, 0,
ax_anim 2, 0, 141, 0, 0, 0, 0,
ax_anim 6, 0, 143, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sDunsparceAnims_6_1:
ax_anim 30, 0, 144, 0, 0, 0, 0,
ax_anim 35, 0, 145, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sDunsparceAnims_7_1:
ax_anim 2, 0, 146, 0, -4, 0, -4,
ax_anim 8, 0, 146, 0, -5, 0, -5,
ax_anim_terminator
sDunsparceAnims_7_2:
ax_anim 2, 0, 147, -4, -4, -4, -4,
ax_anim 8, 0, 147, -5, -5, -5, -5,
ax_anim_terminator
sDunsparceAnims_7_3:
ax_anim 2, 0, 148, -4, 0, -4, 0,
ax_anim 8, 0, 148, -5, 0, -5, 0,
ax_anim_terminator
sDunsparceAnims_7_4:
ax_anim 2, 0, 149, -4, 4, -4, 4,
ax_anim 8, 0, 149, -5, 5, -5, 5,
ax_anim_terminator
sDunsparceAnims_7_5:
ax_anim 2, 0, 150, 0, 4, 0, 4,
ax_anim 8, 0, 150, 0, 5, 0, 5,
ax_anim_terminator
sDunsparceAnims_7_6:
ax_anim 2, 0, 151, 4, 4, 4, 4,
ax_anim 8, 0, 151, 5, 5, 5, 5,
ax_anim_terminator
sDunsparceAnims_7_7:
ax_anim 2, 0, 152, 4, 0, 4, 0,
ax_anim 8, 0, 152, 5, 0, 5, 0,
ax_anim_terminator
sDunsparceAnims_7_8:
ax_anim 2, 0, 153, 4, -4, 4, -4,
ax_anim 8, 0, 153, 5, -5, 5, -5,
ax_anim_terminator
.align 2
sDunsparceAnims_8_1:
ax_anim 36, 0, 154, 0, 0, 0, 0,
ax_anim 19, 0, 156, 0, 0, 0, 0,
ax_anim_terminator
sDunsparceAnims_8_2:
ax_anim 36, 0, 157, 0, 0, 0, 0,
ax_anim 19, 0, 158, 0, 0, 0, 0,
ax_anim_terminator
sDunsparceAnims_8_3:
ax_anim 36, 0, 160, 0, 0, 0, 0,
ax_anim 19, 0, 161, 0, 0, 0, 0,
ax_anim_terminator
sDunsparceAnims_8_4:
ax_anim 36, 0, 163, 0, 0, 0, 0,
ax_anim 19, 0, 164, 0, 0, 0, 0,
ax_anim_terminator
sDunsparceAnims_8_5:
ax_anim 36, 0, 166, 0, 0, 0, 0,
ax_anim 19, 0, 167, 0, 0, 0, 0,
ax_anim_terminator
sDunsparceAnims_8_6:
ax_anim 36, 0, 169, 0, 0, 0, 0,
ax_anim 19, 0, 170, 0, 0, 0, 0,
ax_anim_terminator
sDunsparceAnims_8_7:
ax_anim 36, 0, 172, 0, 0, 0, 0,
ax_anim 19, 0, 173, 0, 0, 0, 0,
ax_anim_terminator
sDunsparceAnims_8_8:
ax_anim 36, 0, 175, 0, 0, 0, 0,
ax_anim 19, 0, 176, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sDunsparceAnims_9_1:
ax_anim 2, 0, 178, 0, 0, 0, 0,
ax_anim 1, 0, 179, 6, 3, 6, 3,
ax_anim 2, 0, 180, 8, 7, 8, 7,
ax_anim 2, 0, 181, 7, 14, 7, 14,
ax_anim 3, 0, 182, 0, 17, 0, 17,
ax_anim 2, 3, 183, -7, 14, -7, 14,
ax_anim 2, 0, 184, -8, 7, -8, 7,
ax_anim 1, 0, 185, -6, 3, -6, 3,
ax_anim 1, 0, 178, 0, 0, 0, 0,
ax_anim_terminator
sDunsparceAnims_9_2:
ax_anim 2, 0, 185, 0, 0, 0, 0,
ax_anim 1, 0, 178, 8, -1, 8, -1,
ax_anim 2, 0, 179, 17, 3, 17, 3,
ax_anim 2, 0, 180, 21, 10, 21, 10,
ax_anim 3, 0, 181, 20, 18, 20, 18,
ax_anim 2, 3, 182, 11, 20, 11, 20,
ax_anim 2, 0, 183, 3, 15, 3, 15,
ax_anim 1, 0, 184, 0, 7, 0, 7,
ax_anim 1, 0, 185, 0, 0, 0, 0,
ax_anim_terminator
sDunsparceAnims_9_3:
ax_anim 2, 0, 184, 0, 0, 0, 0,
ax_anim 1, 0, 185, 2, -5, 2, -5,
ax_anim 2, 0, 178, 11, -8, 11, -8,
ax_anim 2, 0, 179, 17, -6, 17, -6,
ax_anim 3, 0, 180, 19, -2, 19, -2,
ax_anim 2, 3, 181, 17, 6, 17, 6,
ax_anim 2, 0, 182, 12, 9, 12, 9,
ax_anim 1, 0, 183, 5, 7, 5, 7,
ax_anim 1, 0, 184, 0, 0, 0, 0,
ax_anim_terminator
sDunsparceAnims_9_4:
ax_anim 2, 0, 183, 0, 0, 0, 0,
ax_anim 1, 0, 184, -2, -8, -2, -8,
ax_anim 2, 0, 185, 1, -16, 1, -16,
ax_anim 2, 0, 178, 10, -24, 10, -24,
ax_anim 3, 0, 179, 18, -25, 18, -25,
ax_anim 2, 3, 180, 22, -16, 22, -16,
ax_anim 2, 0, 181, 18, -4, 18, -4,
ax_anim 1, 0, 182, 8, 1, 8, 1,
ax_anim 1, 0, 183, 0, 0, 0, 0,
ax_anim_terminator
sDunsparceAnims_9_5:
ax_anim 2, 0, 182, 0, 0, 0, 0,
ax_anim 1, 0, 183, -8, -4, -8, -4,
ax_anim 2, 0, 184, -10, -12, -10, -12,
ax_anim 2, 0, 185, -7, -21, -7, -21,
ax_anim 3, 0, 178, 0, -25, 0, -25,
ax_anim 2, 3, 179, 7, -21, 7, -21,
ax_anim 2, 0, 180, 10, -12, 10, -12,
ax_anim 1, 0, 181, 8, -4, 8, -4,
ax_anim 1, 0, 182, 0, 0, 0, 0,
ax_anim_terminator
sDunsparceAnims_9_6:
ax_anim 2, 0, 181, 0, 0, 0, 0,
ax_anim 1, 0, 180, 2, -8, 2, -8,
ax_anim 2, 0, 179, -1, -16, -1, -16,
ax_anim 2, 0, 178, -10, -24, -10, -24,
ax_anim 3, 0, 185, -18, -25, -18, -25,
ax_anim 2, 3, 184, -22, -16, -22, -16,
ax_anim 2, 0, 183, -18, -4, -18, -4,
ax_anim 1, 0, 182, -8, -1, -8, -1,
ax_anim 1, 0, 181, 0, 0, 0, 0,
ax_anim_terminator
sDunsparceAnims_9_7:
ax_anim 2, 0, 180, 0, 0, 0, 0,
ax_anim 1, 0, 179, -2, -5, -2, -5,
ax_anim 2, 0, 178, -11, -8, -11, -8,
ax_anim 2, 0, 185, -17, -6, -17, -6,
ax_anim 3, 0, 184, -19, -2, -19, -2,
ax_anim 2, 3, 183, -17, 6, -17, 6,
ax_anim 2, 0, 182, -12, 9, -12, 9,
ax_anim 1, 0, 181, -5, 7, -5, 7,
ax_anim 1, 0, 180, 0, 0, 0, 0,
ax_anim_terminator
sDunsparceAnims_9_8:
ax_anim 2, 0, 179, 0, 0, 0, 0,
ax_anim 1, 0, 178, -8, -1, -8, -1,
ax_anim 2, 0, 185, -17, 3, -17, 3,
ax_anim 2, 0, 184, -21, 10, -21, 10,
ax_anim 3, 0, 183, -20, 18, -20, 18,
ax_anim 2, 3, 182, -11, 20, -11, 20,
ax_anim 2, 0, 181, -3, 15, -3, 15,
ax_anim 1, 0, 180, 0, 7, 0, 7,
ax_anim 1, 0, 179, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sDunsparceAnims_10_1:
ax_anim 2, 0, 186, 0, 0, 0, 0,
ax_anim 2, 0, 186, 6, 0, 6, 0,
ax_anim 2, 0, 186, -6, 0, -6, 0,
ax_anim 2, 0, 186, 10, 0, 10, 0,
ax_anim 2, 0, 186, -10, 0, -10, 0,
ax_anim 2, 0, 186, 12, 0, 12, 0,
ax_anim 3, 0, 186, -12, 0, -12, 0,
ax_anim 3, 0, 186, 13, 0, 13, 0,
ax_anim 3, 0, 186, -13, 0, -13, 0,
ax_anim 2, 0, 186, 12, 0, 12, 0,
ax_anim 3, 0, 186, -12, 0, -12, 0,
ax_anim 2, 0, 186, 10, 0, 10, 0,
ax_anim 2, 0, 186, -10, 0, -10, 0,
ax_anim 2, 0, 186, 6, 0, 6, 0,
ax_anim 2, 0, 186, -6, 0, -6, 0,
ax_anim 2, 0, 186, 0, 0, 0, 0,
ax_anim_terminator
sDunsparceAnims_10_2:
ax_anim 2, 0, 187, 0, 0, 0, 0,
ax_anim 2, 0, 187, 6, -6, 6, -6,
ax_anim 2, 0, 187, -6, 6, -6, 6,
ax_anim 2, 0, 187, 10, -10, 10, -10,
ax_anim 2, 0, 187, -10, 10, -10, 10,
ax_anim 2, 0, 187, 12, -12, 12, -12,
ax_anim 3, 0, 187, -12, 12, -12, 12,
ax_anim 3, 0, 187, 13, -13, 13, -13,
ax_anim 3, 0, 187, -13, 13, -13, 13,
ax_anim 2, 0, 187, 12, -12, 12, -12,
ax_anim 3, 0, 187, -12, 12, -12, 12,
ax_anim 2, 0, 187, 10, -10, 10, -10,
ax_anim 2, 0, 187, -10, 10, -10, 10,
ax_anim 2, 0, 187, 6, -6, 6, -6,
ax_anim 2, 0, 187, -6, 6, -6, 6,
ax_anim 2, 0, 187, 0, 0, 0, 0,
ax_anim_terminator
sDunsparceAnims_10_3:
ax_anim 2, 0, 188, 0, 0, 0, 0,
ax_anim 2, 0, 188, 0, -6, 0, -6,
ax_anim 2, 0, 188, 0, 6, 0, 6,
ax_anim 2, 0, 188, 0, -10, 0, -10,
ax_anim 2, 0, 188, 0, 10, 0, 10,
ax_anim 2, 0, 188, 0, -12, 0, -12,
ax_anim 3, 0, 188, 0, 12, 0, 12,
ax_anim 3, 0, 188, 0, -13, 0, -13,
ax_anim 3, 0, 188, 0, 13, 0, 13,
ax_anim 2, 0, 188, 0, -12, 0, -12,
ax_anim 3, 0, 188, 0, 12, 0, 12,
ax_anim 2, 0, 188, 0, -10, 0, -10,
ax_anim 2, 0, 188, 0, 10, 0, 10,
ax_anim 2, 0, 188, 0, -6, 0, -6,
ax_anim 2, 0, 188, 0, 6, 0, 6,
ax_anim 2, 0, 188, 0, 0, 0, 0,
ax_anim_terminator
sDunsparceAnims_10_4:
ax_anim 2, 0, 189, 0, 0, 0, 0,
ax_anim 2, 0, 189, -6, -6, -6, -6,
ax_anim 2, 0, 189, 6, 6, 6, 6,
ax_anim 2, 0, 189, -10, -10, -10, -10,
ax_anim 2, 0, 189, 10, 10, 10, 10,
ax_anim 2, 0, 189, -12, -12, -12, -12,
ax_anim 3, 0, 189, 12, 12, 12, 12,
ax_anim 3, 0, 189, -13, -13, -13, -13,
ax_anim 3, 0, 189, 13, 13, 13, 13,
ax_anim 2, 0, 189, -12, -12, -12, -12,
ax_anim 3, 0, 189, 12, 12, 12, 12,
ax_anim 2, 0, 189, -10, -10, -10, -10,
ax_anim 2, 0, 189, 10, 10, 10, 10,
ax_anim 2, 0, 189, -6, -6, -6, -6,
ax_anim 2, 0, 189, 6, 6, 6, 6,
ax_anim 2, 0, 189, 0, 0, 0, 0,
ax_anim_terminator
sDunsparceAnims_10_5:
ax_anim 2, 0, 190, 0, 0, 0, 0,
ax_anim 2, 0, 190, 6, 0, 6, 0,
ax_anim 2, 0, 190, -6, 0, -6, 0,
ax_anim 2, 0, 190, 10, 0, 10, 0,
ax_anim 2, 0, 190, -10, 0, -10, 0,
ax_anim 2, 0, 190, 12, 0, 12, 0,
ax_anim 3, 0, 190, -12, 0, -12, 0,
ax_anim 3, 0, 190, 13, 0, 13, 0,
ax_anim 3, 0, 190, -13, 0, -13, 0,
ax_anim 2, 0, 190, 12, 0, 12, 0,
ax_anim 3, 0, 190, -12, 0, -12, 0,
ax_anim 2, 0, 190, 10, 0, 10, 0,
ax_anim 2, 0, 190, -10, 0, -10, 0,
ax_anim 2, 0, 190, 6, 0, 6, 0,
ax_anim 2, 0, 190, -6, 0, -6, 0,
ax_anim 2, 0, 190, 0, 0, 0, 0,
ax_anim_terminator
sDunsparceAnims_10_6:
ax_anim 2, 0, 191, 0, 0, 0, 0,
ax_anim 2, 0, 191, 6, -6, 6, -6,
ax_anim 2, 0, 191, -6, 6, -6, 6,
ax_anim 2, 0, 191, 10, -10, 10, -10,
ax_anim 2, 0, 191, -10, 10, -10, 10,
ax_anim 2, 0, 191, 12, -12, 12, -12,
ax_anim 3, 0, 191, -12, 12, -12, 12,
ax_anim 3, 0, 191, 13, -13, 13, -13,
ax_anim 3, 0, 191, -13, 13, -13, 13,
ax_anim 2, 0, 191, 12, -12, 12, -12,
ax_anim 3, 0, 191, -12, 12, -12, 12,
ax_anim 2, 0, 191, 10, -10, 10, -10,
ax_anim 2, 0, 191, -10, 10, -10, 10,
ax_anim 2, 0, 191, 6, -6, 6, -6,
ax_anim 2, 0, 191, -6, 6, -6, 6,
ax_anim 2, 0, 191, 0, 0, 0, 0,
ax_anim_terminator
sDunsparceAnims_10_7:
ax_anim 2, 0, 192, 0, 0, 0, 0,
ax_anim 2, 0, 192, 0, -6, 0, -6,
ax_anim 2, 0, 192, 0, 6, 0, 6,
ax_anim 2, 0, 192, 0, -10, 0, -10,
ax_anim 2, 0, 192, 0, 10, 0, 10,
ax_anim 2, 0, 192, 0, -12, 0, -12,
ax_anim 3, 0, 192, 0, 12, 0, 12,
ax_anim 3, 0, 192, 0, -13, 0, -13,
ax_anim 3, 0, 192, 0, 13, 0, 13,
ax_anim 2, 0, 192, 0, -12, 0, -12,
ax_anim 3, 0, 192, 0, 12, 0, 12,
ax_anim 2, 0, 192, 0, -10, 0, -10,
ax_anim 2, 0, 192, 0, 10, 0, 10,
ax_anim 2, 0, 192, 0, -6, 0, -6,
ax_anim 2, 0, 192, 0, 6, 0, 6,
ax_anim 2, 0, 192, 0, 0, 0, 0,
ax_anim_terminator
sDunsparceAnims_10_8:
ax_anim 2, 0, 193, 0, 0, 0, 0,
ax_anim 2, 0, 193, -6, -6, -6, -6,
ax_anim 2, 0, 193, 6, 6, 6, 6,
ax_anim 2, 0, 193, -10, -10, -10, -10,
ax_anim 2, 0, 193, 10, 10, 10, 10,
ax_anim 2, 0, 193, -12, -12, -12, -12,
ax_anim 3, 0, 193, 12, 12, 12, 12,
ax_anim 3, 0, 193, -13, -13, -13, -13,
ax_anim 3, 0, 193, 13, 13, 13, 13,
ax_anim 2, 0, 193, -12, -12, -12, -12,
ax_anim 3, 0, 193, 12, 12, 12, 12,
ax_anim 2, 0, 193, -10, -10, -10, -10,
ax_anim 2, 0, 193, 10, 10, 10, 10,
ax_anim 2, 0, 193, -6, -6, -6, -6,
ax_anim 2, 0, 193, 6, 6, 6, 6,
ax_anim 2, 0, 193, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sDunsparceAnims_11_1:
ax_anim 2, 0, 194, 0, 0, 0, 0,
ax_anim 1, 0, 195, 0, -10, 0, 0,
ax_anim 2, 0, 195, 0, -16, 0, 0,
ax_anim 3, 0, 195, 0, -20, 0, 0,
ax_anim 4, 0, 195, 0, -21, 0, 0,
ax_anim 4, 0, 194, 0, -23, 0, 0,
ax_anim 3, 0, 196, 0, -22, 0, 0,
ax_anim 2, 0, 196, 0, -18, 0, 0,
ax_anim 1, 0, 196, 0, -12, 0, 0,
ax_anim 2, 2, 194, 0, 0, 0, 0,
ax_anim_terminator
sDunsparceAnims_11_2:
ax_anim 2, 0, 197, 0, 0, 0, 0,
ax_anim 1, 0, 198, 0, -10, 0, 0,
ax_anim 2, 0, 198, 0, -16, 0, 0,
ax_anim 3, 0, 198, 0, -20, 0, 0,
ax_anim 4, 0, 198, 0, -21, 0, 0,
ax_anim 4, 0, 197, 0, -24, 0, 0,
ax_anim 3, 0, 199, 0, -18, 0, 0,
ax_anim 2, 0, 199, 0, -12, 0, 0,
ax_anim 1, 0, 199, 0, -8, 0, 0,
ax_anim 2, 2, 197, 0, 0, 0, 0,
ax_anim_terminator
sDunsparceAnims_11_3:
ax_anim 2, 0, 200, 0, 0, 0, 0,
ax_anim 1, 0, 201, 0, -10, 0, 0,
ax_anim 2, 0, 201, 0, -16, 0, 0,
ax_anim 3, 0, 201, 0, -20, 0, 0,
ax_anim 4, 0, 201, 0, -21, 0, 0,
ax_anim 4, 0, 200, 0, -23, 0, 0,
ax_anim 3, 0, 202, 0, -18, 0, 0,
ax_anim 2, 0, 202, 0, -14, 0, 0,
ax_anim 1, 0, 202, 0, -10, 0, 0,
ax_anim 2, 2, 200, 0, 0, 0, 0,
ax_anim_terminator
sDunsparceAnims_11_4:
ax_anim 2, 0, 203, 0, 0, 0, 0,
ax_anim 1, 0, 204, 0, -10, 0, 0,
ax_anim 2, 0, 204, 0, -16, 0, 0,
ax_anim 3, 0, 204, 0, -19, 0, 0,
ax_anim 4, 0, 204, 0, -22, 0, 0,
ax_anim 4, 0, 203, 0, -24, 0, 0,
ax_anim 3, 0, 205, 0, -19, 0, 0,
ax_anim 2, 0, 205, 0, -13, 0, 0,
ax_anim 1, 0, 205, 0, -9, 0, 0,
ax_anim 2, 2, 203, 0, 0, 0, 0,
ax_anim_terminator
sDunsparceAnims_11_5:
ax_anim 2, 0, 206, 0, 0, 0, 0,
ax_anim 1, 0, 207, 0, -10, 0, 0,
ax_anim 2, 0, 207, 0, -16, 0, 0,
ax_anim 3, 0, 207, 0, -20, 0, 0,
ax_anim 4, 0, 207, 0, -21, 0, 0,
ax_anim 4, 0, 206, 0, -23, 0, 0,
ax_anim 3, 0, 208, 0, -22, 0, 0,
ax_anim 2, 0, 208, 0, -18, 0, 0,
ax_anim 1, 0, 208, 0, -12, 0, 0,
ax_anim 2, 2, 206, 0, 0, 0, 0,
ax_anim_terminator
sDunsparceAnims_11_6:
ax_anim 2, 0, 209, 0, 0, 0, 0,
ax_anim 1, 0, 210, 0, -10, 0, 0,
ax_anim 2, 0, 210, 0, -16, 0, 0,
ax_anim 3, 0, 210, 0, -19, 0, 0,
ax_anim 4, 0, 210, 0, -22, 0, 0,
ax_anim 4, 0, 209, 0, -24, 0, 0,
ax_anim 3, 0, 211, 0, -19, 0, 0,
ax_anim 2, 0, 211, 0, -13, 0, 0,
ax_anim 1, 0, 211, 0, -9, 0, 0,
ax_anim 2, 2, 209, 0, 0, 0, 0,
ax_anim_terminator
sDunsparceAnims_11_7:
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 1, 0, 213, 0, -10, 0, 0,
ax_anim 2, 0, 213, 0, -16, 0, 0,
ax_anim 3, 0, 213, 0, -20, 0, 0,
ax_anim 4, 0, 213, 0, -21, 0, 0,
ax_anim 4, 0, 212, 0, -23, 0, 0,
ax_anim 3, 0, 214, 0, -18, 0, 0,
ax_anim 2, 0, 214, 0, -14, 0, 0,
ax_anim 1, 0, 214, 0, -10, 0, 0,
ax_anim 2, 2, 212, 0, 0, 0, 0,
ax_anim_terminator
sDunsparceAnims_11_8:
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 1, 0, 216, 0, -10, 0, 0,
ax_anim 2, 0, 216, 0, -16, 0, 0,
ax_anim 3, 0, 216, 0, -20, 0, 0,
ax_anim 4, 0, 216, 0, -21, 0, 0,
ax_anim 4, 0, 215, 0, -24, 0, 0,
ax_anim 3, 0, 217, 0, -18, 0, 0,
ax_anim 2, 0, 217, 0, -12, 0, 0,
ax_anim 1, 0, 217, 0, -8, 0, 0,
ax_anim 2, 2, 215, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sDunsparceAnims_12_1:
ax_anim 2, 0, 218, 1, 0, 1, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 218, 1, 0, 1, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 218, 1, 0, 1, 0,
ax_anim 2, 2, 218, 0, 0, 0, 0,
ax_anim 2, 0, 218, 1, 0, 1, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 218, 1, 0, 1, 0,
ax_anim 2, 1, 218, 0, 0, 0, 0,
ax_anim_terminator
sDunsparceAnims_12_2:
ax_anim 2, 0, 225, 1, -1, 1, -1,
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 2, 0, 225, 1, -1, 1, -1,
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 2, 0, 225, 1, -1, 1, -1,
ax_anim 2, 2, 225, 0, 0, 0, 0,
ax_anim 2, 0, 225, 1, -1, 1, -1,
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 2, 0, 225, 1, -1, 1, -1,
ax_anim 2, 1, 225, 0, 0, 0, 0,
ax_anim_terminator
sDunsparceAnims_12_3:
ax_anim 2, 0, 224, 0, -1, 0, -1,
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 2, 0, 224, 0, -1, 0, -1,
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 2, 0, 224, 0, -1, 0, -1,
ax_anim 2, 2, 224, 0, 0, 0, 0,
ax_anim 2, 0, 224, 0, -1, 0, -1,
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 2, 0, 224, 0, -1, 0, -1,
ax_anim 2, 1, 224, 0, 0, 0, 0,
ax_anim_terminator
sDunsparceAnims_12_4:
ax_anim 2, 0, 223, -1, -1, -1, -1,
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 2, 0, 223, -1, -1, -1, -1,
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 2, 0, 223, -1, -1, -1, -1,
ax_anim 2, 2, 223, 0, 0, 0, 0,
ax_anim 2, 0, 223, -1, -1, -1, -1,
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 2, 0, 223, -1, -1, -1, -1,
ax_anim 2, 1, 223, 0, 0, 0, 0,
ax_anim_terminator
sDunsparceAnims_12_5:
ax_anim 2, 0, 222, 1, 0, 1, 0,
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 0, 222, 1, 0, 1, 0,
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 0, 222, 1, 0, 1, 0,
ax_anim 2, 2, 222, 0, 0, 0, 0,
ax_anim 2, 0, 222, 1, 0, 1, 0,
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 0, 222, 1, 0, 1, 0,
ax_anim 2, 1, 222, 0, 0, 0, 0,
ax_anim_terminator
sDunsparceAnims_12_6:
ax_anim 2, 0, 221, 1, -1, 1, -1,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 221, 1, -1, 1, -1,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 221, 1, -1, 1, -1,
ax_anim 2, 2, 221, 0, 0, 0, 0,
ax_anim 2, 0, 221, 1, -1, 1, -1,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 221, 1, -1, 1, -1,
ax_anim 2, 1, 221, 0, 0, 0, 0,
ax_anim_terminator
sDunsparceAnims_12_7:
ax_anim 2, 0, 220, 0, -1, 0, -1,
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, -1, 0, -1,
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, -1, 0, -1,
ax_anim 2, 2, 220, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, -1, 0, -1,
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, -1, 0, -1,
ax_anim 2, 1, 220, 0, 0, 0, 0,
ax_anim_terminator
sDunsparceAnims_12_8:
ax_anim 2, 0, 219, -1, -1, -1, -1,
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 0, 219, -1, -1, -1, -1,
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 0, 219, -1, -1, -1, -1,
ax_anim 2, 2, 219, 0, 0, 0, 0,
ax_anim 2, 0, 219, -1, -1, -1, -1,
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 0, 219, -1, -1, -1, -1,
ax_anim 2, 1, 219, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sDunsparceAnims_13_1:
ax_anim 2, 0, 226, 0, 0, 0, 0,
ax_anim 2, 0, 227, 0, 0, 0, 0,
ax_anim 2, 0, 228, 0, 0, 0, 0,
ax_anim 2, 0, 229, 0, 0, 0, 0,
ax_anim 2, 0, 230, 0, 0, 0, 0,
ax_anim 2, 0, 231, 0, 0, 0, 0,
ax_anim 2, 0, 232, 0, 0, 0, 0,
ax_anim 2, 0, 233, 0, 0, 0, 0,
ax_anim 2, 2, 226, 0, 0, 0, 0,
ax_anim_terminator
sDunsparceAnims_13_2:
ax_anim 2, 0, 233, 0, 0, 0, 0,
ax_anim 2, 0, 226, 0, 0, 0, 0,
ax_anim 2, 0, 227, 0, 0, 0, 0,
ax_anim 2, 0, 228, 0, 0, 0, 0,
ax_anim 2, 0, 229, 0, 0, 0, 0,
ax_anim 2, 0, 230, 0, 0, 0, 0,
ax_anim 2, 0, 231, 0, 0, 0, 0,
ax_anim 2, 0, 232, 0, 0, 0, 0,
ax_anim 2, 2, 233, 0, 0, 0, 0,
ax_anim_terminator
sDunsparceAnims_13_3:
ax_anim 2, 0, 232, 0, 0, 0, 0,
ax_anim 2, 0, 233, 0, 0, 0, 0,
ax_anim 2, 0, 226, 0, 0, 0, 0,
ax_anim 2, 0, 227, 0, 0, 0, 0,
ax_anim 2, 0, 228, 0, 0, 0, 0,
ax_anim 2, 0, 229, 0, 0, 0, 0,
ax_anim 2, 0, 230, 0, 0, 0, 0,
ax_anim 2, 0, 231, 0, 0, 0, 0,
ax_anim 2, 2, 232, 0, 0, 0, 0,
ax_anim_terminator
sDunsparceAnims_13_4:
ax_anim 2, 0, 231, 0, 0, 0, 0,
ax_anim 2, 0, 232, 0, 0, 0, 0,
ax_anim 2, 0, 233, 0, 0, 0, 0,
ax_anim 2, 0, 226, 0, 0, 0, 0,
ax_anim 2, 0, 227, 0, 0, 0, 0,
ax_anim 2, 0, 228, 0, 0, 0, 0,
ax_anim 2, 0, 229, 0, 0, 0, 0,
ax_anim 2, 0, 230, 0, 0, 0, 0,
ax_anim 2, 2, 231, 0, 0, 0, 0,
ax_anim_terminator
sDunsparceAnims_13_5:
ax_anim 2, 0, 230, 0, 0, 0, 0,
ax_anim 2, 0, 231, 0, 0, 0, 0,
ax_anim 2, 0, 232, 0, 0, 0, 0,
ax_anim 2, 0, 233, 0, 0, 0, 0,
ax_anim 2, 0, 226, 0, 0, 0, 0,
ax_anim 2, 0, 227, 0, 0, 0, 0,
ax_anim 2, 0, 228, 0, 0, 0, 0,
ax_anim 2, 0, 229, 0, 0, 0, 0,
ax_anim 2, 2, 230, 0, 0, 0, 0,
ax_anim_terminator
sDunsparceAnims_13_6:
ax_anim 2, 0, 229, 0, 0, 0, 0,
ax_anim 2, 0, 230, 0, 0, 0, 0,
ax_anim 2, 0, 231, 0, 0, 0, 0,
ax_anim 2, 0, 232, 0, 0, 0, 0,
ax_anim 2, 0, 233, 0, 0, 0, 0,
ax_anim 2, 0, 226, 0, 0, 0, 0,
ax_anim 2, 0, 227, 0, 0, 0, 0,
ax_anim 2, 0, 228, 0, 0, 0, 0,
ax_anim 2, 2, 229, 0, 0, 0, 0,
ax_anim_terminator
sDunsparceAnims_13_7:
ax_anim 2, 0, 228, 0, 0, 0, 0,
ax_anim 2, 0, 229, 0, 0, 0, 0,
ax_anim 2, 0, 230, 0, 0, 0, 0,
ax_anim 2, 0, 231, 0, 0, 0, 0,
ax_anim 2, 0, 232, 0, 0, 0, 0,
ax_anim 2, 0, 233, 0, 0, 0, 0,
ax_anim 2, 0, 226, 0, 0, 0, 0,
ax_anim 2, 0, 227, 0, 0, 0, 0,
ax_anim 2, 2, 228, 0, 0, 0, 0,
ax_anim_terminator
sDunsparceAnims_13_8:
ax_anim 2, 0, 227, 0, 0, 0, 0,
ax_anim 2, 0, 228, 0, 0, 0, 0,
ax_anim 2, 0, 229, 0, 0, 0, 0,
ax_anim 2, 0, 230, 0, 0, 0, 0,
ax_anim 2, 0, 231, 0, 0, 0, 0,
ax_anim 2, 0, 232, 0, 0, 0, 0,
ax_anim 2, 0, 233, 0, 0, 0, 0,
ax_anim 2, 0, 226, 0, 0, 0, 0,
ax_anim 2, 2, 227, 0, 0, 0, 0,
ax_anim_terminator
sDunsparceGfx1:
.incbin "baserom.gba", 0xE4F704, 0x100
sDunsparceSprites1:
ax_sprite sDunsparceGfx1, 0x100
ax_sprite_terminator
sDunsparceGfx2:
.incbin "baserom.gba", 0xE4F814, 0x100
sDunsparceSprites2:
ax_sprite sDunsparceGfx2, 0x100
ax_sprite_terminator
sDunsparceGfx3:
.incbin "baserom.gba", 0xE4F924, 0x200
sDunsparceSprites3:
ax_sprite sDunsparceGfx3, 0x200
ax_sprite_terminator
sDunsparceGfx4:
.incbin "baserom.gba", 0xE4FB34, 0x200
sDunsparceSprites4:
ax_sprite sDunsparceGfx4, 0x200
ax_sprite_terminator
sDunsparceGfx5:
.incbin "baserom.gba", 0xE4FD44, 0x200
sDunsparceSprites5:
ax_sprite sDunsparceGfx5, 0x200
ax_sprite_terminator
sDunsparceGfx6:
.incbin "baserom.gba", 0xE4FF54, 0x200
sDunsparceSprites6:
ax_sprite sDunsparceGfx6, 0x200
ax_sprite_terminator
sDunsparceGfx7:
.incbin "baserom.gba", 0xE50164, 0x100
sDunsparceSprites7:
ax_sprite sDunsparceGfx7, 0x100
ax_sprite_terminator
sDunsparceGfx8:
.incbin "baserom.gba", 0xE50274, 0x100
sDunsparceSprites8:
ax_sprite sDunsparceGfx8, 0x100
ax_sprite_terminator
sDunsparceGfx9:
.incbin "baserom.gba", 0xE50384, 0x200
sDunsparceSprites9:
ax_sprite sDunsparceGfx9, 0x200
ax_sprite_terminator
sDunsparceGfx10:
.incbin "baserom.gba", 0xE50594, 0x200
sDunsparceSprites10:
ax_sprite sDunsparceGfx10, 0x200
ax_sprite_terminator
sDunsparceGfx11:
.incbin "baserom.gba", 0xE507A4, 0x200
sDunsparceSprites11:
ax_sprite sDunsparceGfx11, 0x200
ax_sprite_terminator
sDunsparceGfx12:
.incbin "baserom.gba", 0xE509B4, 0x200
sDunsparceSprites12:
ax_sprite sDunsparceGfx12, 0x200
ax_sprite_terminator
sDunsparceGfx13:
.incbin "baserom.gba", 0xE50BC4, 0x100
sDunsparceSprites13:
ax_sprite sDunsparceGfx13, 0x100
ax_sprite_terminator
sDunsparceGfx14:
.incbin "baserom.gba", 0xE50CD4, 0x100
sDunsparceSprites14:
ax_sprite sDunsparceGfx14, 0x100
ax_sprite_terminator
sDunsparceGfx15:
.incbin "baserom.gba", 0xE50DE4, 0x100
sDunsparceSprites15:
ax_sprite sDunsparceGfx15, 0x100
ax_sprite_terminator
sDunsparceGfx16:
.incbin "baserom.gba", 0xE50EF4, 0xC0
sDunsparceSprites16:
ax_sprite sDunsparceGfx16, 0xc0
ax_sprite 0, 0x40
ax_sprite_terminator
sDunsparceGfx17:
.incbin "baserom.gba", 0xE50FCC, 0xC0
sDunsparceSprites17:
ax_sprite sDunsparceGfx17, 0xc0
ax_sprite 0, 0x40
ax_sprite_terminator
sDunsparceGfx18:
.incbin "baserom.gba", 0xE510A4, 0x20
sDunsparceSprites18:
ax_sprite sDunsparceGfx18, 0x20
ax_sprite_terminator
sDunsparceGfx19:
.incbin "baserom.gba", 0xE510D4, 0xC0
sDunsparceSprites19:
ax_sprite sDunsparceGfx19, 0xc0
ax_sprite 0, 0x40
ax_sprite_terminator
sDunsparceGfx20:
.incbin "baserom.gba", 0xE511AC, 0x20
sDunsparceSprites20:
ax_sprite sDunsparceGfx20, 0x20
ax_sprite_terminator
sDunsparceGfx21:
.incbin "baserom.gba", 0xE511DC, 0x100
sDunsparceSprites21:
ax_sprite sDunsparceGfx21, 0x100
ax_sprite_terminator
sDunsparceGfx22:
.incbin "baserom.gba", 0xE512EC, 0x20
sDunsparceSprites22:
ax_sprite sDunsparceGfx22, 0x20
ax_sprite_terminator
sDunsparceGfx23:
.incbin "baserom.gba", 0xE5131C, 0x100
sDunsparceSprites23:
ax_sprite sDunsparceGfx23, 0x100
ax_sprite_terminator
sDunsparceGfx24:
.incbin "baserom.gba", 0xE5142C, 0x80
sDunsparceSprites24:
ax_sprite sDunsparceGfx24, 0x80
ax_sprite_terminator
sDunsparceGfx25:
.incbin "baserom.gba", 0xE514BC, 0x40
sDunsparceSprites25:
ax_sprite sDunsparceGfx25, 0x40
ax_sprite_terminator
sDunsparceGfx26:
.incbin "baserom.gba", 0xE5150C, 0xC0
sDunsparceSprites26:
ax_sprite sDunsparceGfx26, 0xc0
ax_sprite 0, 0x40
ax_sprite_terminator
sDunsparceGfx27:
.incbin "baserom.gba", 0xE515E4, 0xC0
sDunsparceSprites27:
ax_sprite sDunsparceGfx27, 0xc0
ax_sprite 0, 0x40
ax_sprite_terminator
sDunsparceGfx28:
.incbin "baserom.gba", 0xE516BC, 0x40
sDunsparceSprites28:
ax_sprite sDunsparceGfx28, 0x40
ax_sprite_terminator
sDunsparceGfx29:
.incbin "baserom.gba", 0xE5170C, 0x100
sDunsparceSprites29:
ax_sprite sDunsparceGfx29, 0x100
ax_sprite_terminator
sDunsparceGfx30:
.incbin "baserom.gba", 0xE5181C, 0x20
sDunsparceSprites30:
ax_sprite sDunsparceGfx30, 0x20
ax_sprite_terminator
sDunsparceGfx31:
.incbin "baserom.gba", 0xE5184C, 0x80
sDunsparceSprites31:
ax_sprite sDunsparceGfx31, 0x80
ax_sprite_terminator
sDunsparceGfx32:
.incbin "baserom.gba", 0xE518DC, 0x40
sDunsparceSprites32:
ax_sprite sDunsparceGfx32, 0x40
ax_sprite_terminator
sDunsparceGfx33:
.incbin "baserom.gba", 0xE5192C, 0x100
sDunsparceSprites33:
ax_sprite sDunsparceGfx33, 0x100
ax_sprite_terminator
sDunsparceGfx34:
.incbin "baserom.gba", 0xE51A3C, 0x20
sDunsparceSprites34:
ax_sprite sDunsparceGfx34, 0x20
ax_sprite_terminator
sDunsparceGfx35:
.incbin "baserom.gba", 0xE51A6C, 0xC0
sDunsparceSprites35:
ax_sprite sDunsparceGfx35, 0xc0
ax_sprite 0, 0x40
ax_sprite_terminator
sDunsparceGfx36:
.incbin "baserom.gba", 0xE51B44, 0x40
sDunsparceSprites36:
ax_sprite sDunsparceGfx36, 0x40
ax_sprite_terminator
sDunsparceGfx37:
.incbin "baserom.gba", 0xE51B94, 0x80
sDunsparceSprites37:
ax_sprite sDunsparceGfx37, 0x80
ax_sprite_terminator
sDunsparceGfx38:
.incbin "baserom.gba", 0xE51C24, 0x60
sDunsparceSprites38:
ax_sprite sDunsparceGfx38, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sDunsparceGfx39:
.incbin "baserom.gba", 0xE51C9C, 0xC0
sDunsparceSprites39:
ax_sprite sDunsparceGfx39, 0xc0
ax_sprite 0, 0x40
ax_sprite_terminator
sDunsparceGfx40:
.incbin "baserom.gba", 0xE51D74, 0xC0
sDunsparceSprites40:
ax_sprite sDunsparceGfx40, 0xc0
ax_sprite 0, 0x40
ax_sprite_terminator
sDunsparceGfx41:
.incbin "baserom.gba", 0xE51E4C, 0x100
sDunsparceSprites41:
ax_sprite sDunsparceGfx41, 0x100
ax_sprite_terminator
sDunsparceGfx42:
.incbin "baserom.gba", 0xE51F5C, 0x100
sDunsparceSprites42:
ax_sprite sDunsparceGfx42, 0x100
ax_sprite_terminator
sDunsparceGfx43:
.incbin "baserom.gba", 0xE5206C, 0x200
sDunsparceSprites43:
ax_sprite sDunsparceGfx43, 0x200
ax_sprite_terminator
sDunsparceGfx44:
.incbin "baserom.gba", 0xE5227C, 0x200
sDunsparceSprites44:
ax_sprite sDunsparceGfx44, 0x200
ax_sprite_terminator
sDunsparceGfx45:
.incbin "baserom.gba", 0xE5248C, 0x200
sDunsparceSprites45:
ax_sprite sDunsparceGfx45, 0x200
ax_sprite_terminator
sDunsparceGfx46:
.incbin "baserom.gba", 0xE5269C, 0x200
sDunsparceSprites46:
ax_sprite sDunsparceGfx46, 0x200
ax_sprite_terminator
sDunsparceGfx47:
.incbin "baserom.gba", 0xE528AC, 0x200
sDunsparceSprites47:
ax_sprite sDunsparceGfx47, 0x200
ax_sprite_terminator
sAxPosesDunsparce:
.4byte sDunsparcePose1
.4byte sDunsparcePose2
.4byte sDunsparcePose3
.4byte sDunsparcePose4
.4byte sDunsparcePose5
.4byte sDunsparcePose6
.4byte sDunsparcePose7
.4byte sDunsparcePose8
.4byte sDunsparcePose9
.4byte sDunsparcePose10
.4byte sDunsparcePose11
.4byte sDunsparcePose12
.4byte sDunsparcePose13
.4byte sDunsparcePose14
.4byte sDunsparcePose15
.4byte sDunsparcePose16
.4byte sDunsparcePose17
.4byte sDunsparcePose18
.4byte sDunsparcePose19
.4byte sDunsparcePose20
.4byte sDunsparcePose21
.4byte sDunsparcePose22
.4byte sDunsparcePose23
.4byte sDunsparcePose24
.4byte sDunsparcePose25
.4byte sDunsparcePose26
.4byte sDunsparcePose27
.4byte sDunsparcePose28
.4byte sDunsparcePose29
.4byte sDunsparcePose30
.4byte sDunsparcePose31
.4byte sDunsparcePose32
.4byte sDunsparcePose33
.4byte sDunsparcePose34
.4byte sDunsparcePose35
.4byte sDunsparcePose36
.4byte sDunsparcePose37
.4byte sDunsparcePose38
.4byte sDunsparcePose39
.4byte sDunsparcePose40
.4byte sDunsparcePose41
.4byte sDunsparcePose42
.4byte sDunsparcePose43
.4byte sDunsparcePose44
.4byte sDunsparcePose45
.4byte sDunsparcePose46
.4byte sDunsparcePose47
.4byte sDunsparcePose48
.4byte sDunsparcePose49
.4byte sDunsparcePose50
.4byte sDunsparcePose51
.4byte sDunsparcePose52
.4byte sDunsparcePose53
.4byte sDunsparcePose54
.4byte sDunsparcePose55
.4byte sDunsparcePose56
.4byte sDunsparcePose57
.4byte sDunsparcePose58
.4byte sDunsparcePose59
.4byte sDunsparcePose60
.4byte sDunsparcePose61
.4byte sDunsparcePose62
.4byte sDunsparcePose63
.4byte sDunsparcePose64
.4byte sDunsparcePose65
.4byte sDunsparcePose66
.4byte sDunsparcePose67
.4byte sDunsparcePose68
.4byte sDunsparcePose69
.4byte sDunsparcePose70
.4byte sDunsparcePose71
.4byte sDunsparcePose72
.4byte sDunsparcePose73
.4byte sDunsparcePose74
.4byte sDunsparcePose75
.4byte sDunsparcePose76
.4byte sDunsparcePose77
.4byte sDunsparcePose78
.4byte sDunsparcePose79
.4byte sDunsparcePose80
.4byte sDunsparcePose81
.4byte sDunsparcePose82
.4byte sDunsparcePose83
.4byte sDunsparcePose84
.4byte sDunsparcePose85
.4byte sDunsparcePose86
.4byte sDunsparcePose87
.4byte sDunsparcePose88
.4byte sDunsparcePose89
.4byte sDunsparcePose90
.4byte sDunsparcePose91
.4byte sDunsparcePose92
.4byte sDunsparcePose93
.4byte sDunsparcePose94
.4byte sDunsparcePose95
.4byte sDunsparcePose96
.4byte sDunsparcePose97
.4byte sDunsparcePose98
.4byte sDunsparcePose99
.4byte sDunsparcePose100
.4byte sDunsparcePose101
.4byte sDunsparcePose102
.4byte sDunsparcePose103
.4byte sDunsparcePose104
.4byte sDunsparcePose105
.4byte sDunsparcePose106
.4byte sDunsparcePose107
.4byte sDunsparcePose108
.4byte sDunsparcePose109
.4byte sDunsparcePose110
.4byte sDunsparcePose111
.4byte sDunsparcePose112
.4byte sDunsparcePose113
.4byte sDunsparcePose114
.4byte sDunsparcePose115
.4byte sDunsparcePose116
.4byte sDunsparcePose117
.4byte sDunsparcePose118
.4byte sDunsparcePose119
.4byte sDunsparcePose120
.4byte sDunsparcePose121
.4byte sDunsparcePose122
.4byte sDunsparcePose123
.4byte sDunsparcePose124
.4byte sDunsparcePose125
.4byte sDunsparcePose126
.4byte sDunsparcePose127
.4byte sDunsparcePose128
.4byte sDunsparcePose129
.4byte sDunsparcePose130
.4byte sDunsparcePose131
.4byte sDunsparcePose132
.4byte sDunsparcePose133
.4byte sDunsparcePose134
.4byte sDunsparcePose135
.4byte sDunsparcePose136
.4byte sDunsparcePose137
.4byte sDunsparcePose138
.4byte sDunsparcePose139
.4byte sDunsparcePose140
.4byte sDunsparcePose141
.4byte sDunsparcePose142
.4byte sDunsparcePose143
.4byte sDunsparcePose144
.4byte sDunsparcePose145
.4byte sDunsparcePose146
.4byte sDunsparcePose147
.4byte sDunsparcePose148
.4byte sDunsparcePose149
.4byte sDunsparcePose150
.4byte sDunsparcePose151
.4byte sDunsparcePose152
.4byte sDunsparcePose153
.4byte sDunsparcePose154
.4byte sDunsparcePose155
.4byte sDunsparcePose156
.4byte sDunsparcePose157
.4byte sDunsparcePose158
.4byte sDunsparcePose159
.4byte sDunsparcePose160
.4byte sDunsparcePose161
.4byte sDunsparcePose162
.4byte sDunsparcePose163
.4byte sDunsparcePose164
.4byte sDunsparcePose165
.4byte sDunsparcePose166
.4byte sDunsparcePose167
.4byte sDunsparcePose168
.4byte sDunsparcePose169
.4byte sDunsparcePose170
.4byte sDunsparcePose171
.4byte sDunsparcePose172
.4byte sDunsparcePose173
.4byte sDunsparcePose174
.4byte sDunsparcePose175
.4byte sDunsparcePose176
.4byte sDunsparcePose177
.4byte sDunsparcePose178
.4byte sDunsparcePose179
.4byte sDunsparcePose180
.4byte sDunsparcePose181
.4byte sDunsparcePose182
.4byte sDunsparcePose183
.4byte sDunsparcePose184
.4byte sDunsparcePose185
.4byte sDunsparcePose186
.4byte sDunsparcePose187
.4byte sDunsparcePose188
.4byte sDunsparcePose189
.4byte sDunsparcePose190
.4byte sDunsparcePose191
.4byte sDunsparcePose192
.4byte sDunsparcePose193
.4byte sDunsparcePose194
.4byte sDunsparcePose195
.4byte sDunsparcePose196
.4byte sDunsparcePose197
.4byte sDunsparcePose198
.4byte sDunsparcePose199
.4byte sDunsparcePose200
.4byte sDunsparcePose201
.4byte sDunsparcePose202
.4byte sDunsparcePose203
.4byte sDunsparcePose204
.4byte sDunsparcePose205
.4byte sDunsparcePose206
.4byte sDunsparcePose207
.4byte sDunsparcePose208
.4byte sDunsparcePose209
.4byte sDunsparcePose210
.4byte sDunsparcePose211
.4byte sDunsparcePose212
.4byte sDunsparcePose213
.4byte sDunsparcePose214
.4byte sDunsparcePose215
.4byte sDunsparcePose216
.4byte sDunsparcePose217
.4byte sDunsparcePose218
.4byte sDunsparcePose219
.4byte sDunsparcePose220
.4byte sDunsparcePose221
.4byte sDunsparcePose222
.4byte sDunsparcePose223
.4byte sDunsparcePose224
.4byte sDunsparcePose225
.4byte sDunsparcePose226
.4byte sDunsparcePose227
.4byte sDunsparcePose228
.4byte sDunsparcePose229
.4byte sDunsparcePose230
.4byte sDunsparcePose231
.4byte sDunsparcePose232
.4byte sDunsparcePose233
.4byte sDunsparcePose234
sAxPositionsDunsparce:
.2byte    0,    4, 	  -6,   -7, 	   6,   -7, 	   0,   -3
.2byte    0,    0, 	  -4,  -11, 	   4,  -11, 	   0,   -4
.2byte    0,    6, 	  -7,   -6, 	   7,   -6, 	   0,   -1
.2byte    8,    2, 	   2,   -9, 	  -5,   -3, 	   0,   -2
.2byte    8,   -5, 	  -2,  -12, 	  -7,   -7, 	  -1,   -5
.2byte    9,    1, 	   5,  -10, 	  -5,   -3, 	   1,   -4
.2byte   10,   -1, 	  -3,   -9, 	  -3,   -1, 	   1,   -3
.2byte    9,   -8, 	  -5,   -7, 	  -4,   -3, 	   0,   -5
.2byte   12,   -2, 	   1,  -13, 	  -2,   -8, 	   3,   -6
.2byte    8,   -7, 	  -5,   -7, 	   1,   -1, 	   0,   -4
.2byte    8,  -11, 	  -4,   -9, 	   1,   -5, 	  -1,   -7
.2byte    9,   -6, 	  -3,  -11, 	   4,   -4, 	   2,   -7
.2byte    0,  -12, 	   5,   -5, 	  -5,   -5, 	   0,   -6
.2byte    0,  -12, 	   4,   -2, 	  -4,   -2, 	   0,   -4
.2byte    0,   -4, 	   6,   -1, 	  -6,   -1, 	   0,   -2
.2byte   -8,   -7, 	   5,   -7, 	  -1,   -1, 	   0,   -4
.2byte   -8,  -11, 	   4,   -9, 	  -1,   -5, 	   1,   -7
.2byte   -9,   -6, 	   3,  -11, 	  -4,   -4, 	  -2,   -7
.2byte  -10,   -1, 	   3,   -9, 	   3,   -1, 	  -1,   -3
.2byte   -9,   -8, 	   5,   -7, 	   4,   -3, 	   0,   -5
.2byte  -12,   -2, 	  -1,  -13, 	   2,   -8, 	  -3,   -6
.2byte   -8,    2, 	  -2,   -9, 	   5,   -3, 	   0,   -2
.2byte   -8,   -5, 	   2,  -12, 	   7,   -7, 	   1,   -5
.2byte   -9,    1, 	  -5,  -10, 	   5,   -3, 	  -1,   -4
.2byte    0,    4, 	  -6,   -7, 	   6,   -7, 	   0,   -3
.2byte    0,    0, 	  -4,  -11, 	   4,  -11, 	   0,   -4
.2byte    0,    6, 	  -7,   -6, 	   7,   -6, 	   0,   -1
.2byte    0,  -12, 	  -4,  -16, 	   4,  -16, 	   0,   -7
.2byte    8,    2, 	   2,   -9, 	  -5,   -3, 	   0,   -2
.2byte    8,   -5, 	  -2,  -12, 	  -7,   -7, 	  -1,   -5
.2byte    9,    2, 	   5,   -9, 	  -5,   -2, 	   1,   -3
.2byte    1,  -15, 	  -2,  -10, 	  -8,   -7, 	   0,   -8
.2byte   10,   -1, 	  -3,   -9, 	  -3,   -1, 	   1,   -3
.2byte    9,   -8, 	  -5,   -7, 	  -4,   -3, 	   0,   -5
.2byte   11,    0, 	   0,  -11, 	  -3,   -6, 	   2,   -4
.2byte    3,  -16, 	  -7,   -9, 	  -5,   -3, 	  -1,   -7
.2byte    8,   -7, 	  -5,   -7, 	   1,   -1, 	   0,   -4
.2byte    8,   -8, 	  -4,   -6, 	   1,   -2, 	  -1,   -4
.2byte    7,   -3, 	  -5,   -8, 	   2,   -1, 	   0,   -4
.2byte    1,  -15, 	  -9,   -9, 	  -1,   -7, 	  -2,   -6
.2byte    0,  -12, 	   5,   -5, 	  -5,   -5, 	   0,   -6
.2byte    0,  -14, 	   4,   -4, 	  -4,   -4, 	   0,   -6
.2byte    0,   -7, 	   6,   -4, 	  -6,   -4, 	   0,   -5
.2byte    0,  -15, 	   5,   -7, 	  -5,   -7, 	   0,   -6
.2byte   -8,   -7, 	   5,   -7, 	  -1,   -1, 	   0,   -4
.2byte   -8,   -8, 	   4,   -6, 	  -1,   -2, 	   1,   -4
.2byte   -7,   -3, 	   5,   -8, 	  -2,   -1, 	   0,   -4
.2byte   -2,  -15, 	   8,   -9, 	   0,   -7, 	   1,   -6
.2byte  -10,   -1, 	   3,   -9, 	   3,   -1, 	  -1,   -3
.2byte   -9,   -8, 	   5,   -7, 	   4,   -3, 	   0,   -5
.2byte  -11,    0, 	   0,  -11, 	   3,   -6, 	  -2,   -4
.2byte   -4,  -16, 	   6,   -9, 	   4,   -3, 	   0,   -7
.2byte   -8,    2, 	  -2,   -9, 	   5,   -3, 	   0,   -2
.2byte   -8,   -5, 	   2,  -12, 	   7,   -7, 	   1,   -5
.2byte   -9,    2, 	  -5,   -9, 	   5,   -2, 	  -1,   -3
.2byte   -2,  -15, 	   1,  -10, 	   7,   -7, 	  -1,   -8
.2byte    0,    4, 	  -6,   -7, 	   6,   -7, 	   0,   -3
.2byte    0,    0, 	  -4,  -11, 	   4,  -11, 	   0,   -4
.2byte    0,    6, 	  -7,   -6, 	   7,   -6, 	   0,   -1
.2byte    0,  -12, 	  -4,  -16, 	   4,  -16, 	   0,   -7
.2byte    8,    2, 	   2,   -9, 	  -5,   -3, 	   0,   -2
.2byte    8,   -5, 	  -2,  -12, 	  -7,   -7, 	  -1,   -5
.2byte    9,    2, 	   5,   -9, 	  -5,   -2, 	   1,   -3
.2byte    1,  -15, 	  -2,  -10, 	  -8,   -7, 	   0,   -8
.2byte   10,   -1, 	  -3,   -9, 	  -3,   -1, 	   1,   -3
.2byte    9,   -8, 	  -5,   -7, 	  -4,   -3, 	   0,   -5
.2byte   11,    0, 	   0,  -11, 	  -3,   -6, 	   2,   -4
.2byte    3,  -16, 	  -7,   -9, 	  -5,   -3, 	  -1,   -7
.2byte    8,   -7, 	  -5,   -7, 	   1,   -1, 	   0,   -4
.2byte    8,   -8, 	  -4,   -6, 	   1,   -2, 	  -1,   -4
.2byte    7,   -3, 	  -5,   -8, 	   2,   -1, 	   0,   -4
.2byte    1,  -15, 	  -9,   -9, 	  -1,   -7, 	  -2,   -6
.2byte    0,  -12, 	   5,   -5, 	  -5,   -5, 	   0,   -6
.2byte    0,  -14, 	   4,   -4, 	  -4,   -4, 	   0,   -6
.2byte    0,   -7, 	   6,   -4, 	  -6,   -4, 	   0,   -5
.2byte    0,  -15, 	   5,   -7, 	  -5,   -7, 	   0,   -6
.2byte   -8,   -7, 	   5,   -7, 	  -1,   -1, 	   0,   -4
.2byte   -8,   -8, 	   4,   -6, 	  -1,   -2, 	   1,   -4
.2byte   -7,   -3, 	   5,   -8, 	  -2,   -1, 	   0,   -4
.2byte   -2,  -15, 	   8,   -9, 	   0,   -7, 	   1,   -6
.2byte  -10,   -1, 	   3,   -9, 	   3,   -1, 	  -1,   -3
.2byte   -9,   -8, 	   5,   -7, 	   4,   -3, 	   0,   -5
.2byte  -11,    0, 	   0,  -11, 	   3,   -6, 	  -2,   -4
.2byte   -4,  -16, 	   6,   -9, 	   4,   -3, 	   0,   -7
.2byte   -8,    2, 	  -2,   -9, 	   5,   -3, 	   0,   -2
.2byte   -8,   -5, 	   2,  -12, 	   7,   -7, 	   1,   -5
.2byte   -9,    2, 	  -5,   -9, 	   5,   -2, 	  -1,   -3
.2byte   -2,  -15, 	   1,  -10, 	   7,   -7, 	  -1,   -8
.2byte    0,    4, 	  -6,   -7, 	   6,   -7, 	   0,   -3
.2byte    0,    0, 	  -4,  -11, 	   4,  -11, 	   0,   -4
.2byte    0,    6, 	  -7,   -6, 	   7,   -6, 	   0,   -1
.2byte    0,  -12, 	  -4,  -16, 	   4,  -16, 	   0,   -7
.2byte    8,    2, 	   2,   -9, 	  -5,   -3, 	   0,   -2
.2byte    8,   -5, 	  -2,  -12, 	  -7,   -7, 	  -1,   -5
.2byte    9,    2, 	   5,   -9, 	  -5,   -2, 	   1,   -3
.2byte    1,  -15, 	  -2,  -10, 	  -8,   -7, 	   0,   -8
.2byte   10,   -1, 	  -3,   -9, 	  -3,   -1, 	   1,   -3
.2byte    9,   -8, 	  -5,   -7, 	  -4,   -3, 	   0,   -5
.2byte   11,    0, 	   0,  -11, 	  -3,   -6, 	   2,   -4
.2byte    3,  -16, 	  -7,   -9, 	  -5,   -3, 	  -1,   -7
.2byte    8,   -7, 	  -5,   -7, 	   1,   -1, 	   0,   -4
.2byte    8,   -8, 	  -4,   -6, 	   1,   -2, 	  -1,   -4
.2byte    7,   -3, 	  -5,   -8, 	   2,   -1, 	   0,   -4
.2byte    1,  -15, 	  -9,   -9, 	  -1,   -7, 	  -2,   -6
.2byte    0,  -12, 	   5,   -5, 	  -5,   -5, 	   0,   -6
.2byte    0,  -14, 	   4,   -4, 	  -4,   -4, 	   0,   -6
.2byte    0,   -7, 	   6,   -4, 	  -6,   -4, 	   0,   -5
.2byte    0,  -15, 	   5,   -7, 	  -5,   -7, 	   0,   -6
.2byte   -8,   -7, 	   5,   -7, 	  -1,   -1, 	   0,   -4
.2byte   -8,   -8, 	   4,   -6, 	  -1,   -2, 	   1,   -4
.2byte   -7,   -3, 	   5,   -8, 	  -2,   -1, 	   0,   -4
.2byte   -2,  -15, 	   8,   -9, 	   0,   -7, 	   1,   -6
.2byte  -10,   -1, 	   3,   -9, 	   3,   -1, 	  -1,   -3
.2byte   -9,   -8, 	   5,   -7, 	   4,   -3, 	   0,   -5
.2byte  -11,    0, 	   0,  -11, 	   3,   -6, 	  -2,   -4
.2byte   -4,  -16, 	   6,   -9, 	   4,   -3, 	   0,   -7
.2byte   -8,    2, 	  -2,   -9, 	   5,   -3, 	   0,   -2
.2byte   -8,   -5, 	   2,  -12, 	   7,   -7, 	   1,   -5
.2byte   -9,    2, 	  -5,   -9, 	   5,   -2, 	  -1,   -3
.2byte   -2,  -15, 	   1,  -10, 	   7,   -7, 	  -1,   -8
.2byte    0,    4, 	  -6,   -7, 	   6,   -7, 	   0,   -3
.2byte    0,    3, 	  -8,   -3, 	   7,   -3, 	   0,   -2
.2byte    0,    5, 	  -5,   -7, 	   5,   -7, 	   0,   -2
.2byte    8,    2, 	   2,   -9, 	  -5,   -3, 	   0,   -2
.2byte    8,    1, 	   4,   -9, 	  -5,    0, 	   1,   -3
.2byte    8,    3, 	   1,   -9, 	  -4,   -5, 	  -1,   -2
.2byte   10,   -1, 	  -3,   -9, 	  -3,   -1, 	   1,   -3
.2byte   10,   -4, 	  -2,   -8, 	  -3,    0, 	   1,   -4
.2byte   10,    1, 	  -1,  -10, 	  -1,   -5, 	   1,   -2
.2byte    8,   -7, 	  -5,   -7, 	   1,   -1, 	   0,   -4
.2byte    6,  -10, 	  -5,   -6, 	   2,   -1, 	  -1,   -4
.2byte    9,   -5, 	  -4,   -9, 	   2,   -3, 	   1,   -4
.2byte    0,  -12, 	   5,   -5, 	  -5,   -5, 	   0,   -6
.2byte    0,  -12, 	   5,   -3, 	  -5,   -3, 	   0,   -5
.2byte    0,   -9, 	   5,   -7, 	  -5,   -7, 	   0,   -4
.2byte   -8,   -7, 	   5,   -7, 	  -1,   -1, 	   0,   -4
.2byte   -6,  -10, 	   5,   -6, 	  -2,   -1, 	   1,   -4
.2byte   -9,   -5, 	   4,   -9, 	  -2,   -3, 	  -1,   -4
.2byte  -10,   -1, 	   3,   -9, 	   3,   -1, 	  -1,   -3
.2byte  -10,   -4, 	   2,   -8, 	   3,    0, 	  -1,   -4
.2byte  -10,    1, 	   1,  -10, 	   1,   -5, 	  -1,   -2
.2byte   -8,    2, 	  -2,   -9, 	   5,   -3, 	   0,   -2
.2byte   -8,    1, 	  -4,   -9, 	   5,    0, 	  -1,   -3
.2byte   -8,    3, 	  -1,   -9, 	   4,   -5, 	   1,   -2
.2byte   -9,    2, 	  -4,   -7, 	   6,    0, 	   0,   -3
.2byte   -9,    1, 	  -4,   -7, 	   5,    0, 	   0,   -4
.2byte    0,  -11, 	  -7,  -11, 	   7,  -11, 	   0,  -10
.2byte    8,  -16, 	   3,  -18, 	  -3,  -14, 	   1,  -13
.2byte    9,  -19, 	  -6,  -16, 	  -3,  -12, 	   1,  -12
.2byte    8,  -19, 	  -4,  -14, 	   2,  -11, 	   1,  -11
.2byte    0,  -21, 	   5,  -11, 	  -5,  -11, 	   0,  -13
.2byte   -9,  -19, 	   3,  -14, 	  -3,  -11, 	  -2,  -11
.2byte  -10,  -17, 	   5,  -14, 	   2,  -10, 	  -2,  -10
.2byte   -9,  -14, 	  -4,  -16, 	   2,  -12, 	  -2,  -11
.2byte    0,    4, 	  -6,   -7, 	   6,   -7, 	   0,   -3
.2byte    0,    3, 	  -8,   -3, 	   7,   -3, 	   0,   -2
.2byte    0,    5, 	  -5,   -7, 	   5,   -7, 	   0,   -2
.2byte    8,    2, 	   2,   -9, 	  -5,   -3, 	   0,   -2
.2byte    8,    1, 	   4,   -9, 	  -5,    0, 	   1,   -3
.2byte    8,    3, 	   1,   -9, 	  -4,   -5, 	  -1,   -2
.2byte   10,   -1, 	  -3,   -9, 	  -3,   -1, 	   1,   -3
.2byte   10,   -4, 	  -2,   -8, 	  -3,    0, 	   1,   -4
.2byte   10,    1, 	  -1,  -10, 	  -1,   -5, 	   1,   -2
.2byte    8,   -7, 	  -5,   -7, 	   1,   -1, 	   0,   -4
.2byte    6,  -10, 	  -5,   -6, 	   2,   -1, 	  -1,   -4
.2byte    9,   -5, 	  -4,   -9, 	   2,   -3, 	   1,   -4
.2byte    0,  -12, 	   5,   -5, 	  -5,   -5, 	   0,   -6
.2byte    0,  -12, 	   5,   -3, 	  -5,   -3, 	   0,   -5
.2byte    0,   -9, 	   5,   -7, 	  -5,   -7, 	   0,   -4
.2byte   -8,   -7, 	   5,   -7, 	  -1,   -1, 	   0,   -4
.2byte   -6,  -10, 	   5,   -6, 	  -2,   -1, 	   1,   -4
.2byte   -9,   -5, 	   4,   -9, 	  -2,   -3, 	  -1,   -4
.2byte  -10,   -1, 	   3,   -9, 	   3,   -1, 	  -1,   -3
.2byte  -10,   -4, 	   2,   -8, 	   3,    0, 	  -1,   -4
.2byte  -10,    1, 	   1,  -10, 	   1,   -5, 	  -1,   -2
.2byte   -8,    2, 	  -2,   -9, 	   5,   -3, 	   0,   -2
.2byte   -8,    1, 	  -4,   -9, 	   5,    0, 	  -1,   -3
.2byte   -8,    3, 	  -1,   -9, 	   4,   -5, 	   1,   -2
.2byte    0,    4, 	  -6,   -7, 	   6,   -7, 	   0,   -3
.2byte   -8,    2, 	  -2,   -9, 	   5,   -3, 	   0,   -2
.2byte  -10,   -1, 	   3,   -9, 	   3,   -1, 	  -1,   -3
.2byte   -8,   -7, 	   5,   -7, 	  -1,   -1, 	   0,   -4
.2byte    0,  -12, 	   5,   -5, 	  -5,   -5, 	   0,   -6
.2byte    8,   -7, 	  -5,   -7, 	   1,   -1, 	   0,   -4
.2byte   10,   -1, 	  -3,   -9, 	  -3,   -1, 	   1,   -3
.2byte    8,    2, 	   2,   -9, 	  -5,   -3, 	   0,   -2
.2byte    0,  -12, 	  -4,  -16, 	   4,  -16, 	   0,   -7
.2byte    2,  -15, 	  -1,  -10, 	  -7,   -7, 	   1,   -8
.2byte    5,  -17, 	  -5,  -10, 	  -3,   -4, 	   1,   -8
.2byte    3,  -17, 	  -7,  -11, 	   1,   -9, 	   0,   -8
.2byte    0,  -17, 	   5,   -9, 	  -5,   -9, 	   0,   -8
.2byte   -4,  -17, 	   6,  -11, 	  -2,   -9, 	  -1,   -8
.2byte   -6,  -17, 	   4,  -10, 	   2,   -4, 	  -2,   -8
.2byte   -3,  -15, 	   0,  -10, 	   6,   -7, 	  -2,   -8
.2byte    0,    4, 	  -6,   -7, 	   6,   -7, 	   0,   -3
.2byte    0,    0, 	  -4,  -11, 	   4,  -11, 	   0,   -4
.2byte    0,    6, 	  -7,   -6, 	   7,   -6, 	   0,   -1
.2byte    8,    2, 	   2,   -9, 	  -5,   -3, 	   0,   -2
.2byte    8,   -5, 	  -2,  -12, 	  -7,   -7, 	  -1,   -5
.2byte    9,    2, 	   5,   -9, 	  -5,   -2, 	   1,   -3
.2byte   10,   -1, 	  -3,   -9, 	  -3,   -1, 	   1,   -3
.2byte    9,   -8, 	  -5,   -7, 	  -4,   -3, 	   0,   -5
.2byte   11,    0, 	   0,  -11, 	  -3,   -6, 	   2,   -4
.2byte    8,   -7, 	  -5,   -7, 	   1,   -1, 	   0,   -4
.2byte    8,   -8, 	  -4,   -6, 	   1,   -2, 	  -1,   -4
.2byte    8,   -3, 	  -4,   -8, 	   3,   -1, 	   1,   -4
.2byte    0,  -12, 	   5,   -5, 	  -5,   -5, 	   0,   -6
.2byte    0,  -14, 	   4,   -4, 	  -4,   -4, 	   0,   -6
.2byte    0,   -7, 	   6,   -4, 	  -6,   -4, 	   0,   -5
.2byte   -9,   -7, 	   4,   -7, 	  -2,   -1, 	  -1,   -4
.2byte   -9,   -8, 	   3,   -6, 	  -2,   -2, 	   0,   -4
.2byte   -9,   -3, 	   3,   -8, 	  -4,   -1, 	  -2,   -4
.2byte  -11,   -1, 	   2,   -9, 	   2,   -1, 	  -2,   -3
.2byte  -10,   -8, 	   4,   -7, 	   3,   -3, 	  -1,   -5
.2byte  -12,    0, 	  -1,  -11, 	   2,   -6, 	  -3,   -4
.2byte   -9,    2, 	  -3,   -9, 	   4,   -3, 	  -1,   -2
.2byte   -9,   -5, 	   1,  -12, 	   6,   -7, 	   0,   -5
.2byte  -10,    2, 	  -6,   -9, 	   4,   -2, 	  -2,   -3
.2byte    0,    5, 	  -5,   -7, 	   5,   -7, 	   0,   -2
.2byte   -8,    3, 	  -1,   -9, 	   4,   -5, 	   1,   -2
.2byte  -10,    1, 	   1,  -10, 	   1,   -5, 	  -1,   -2
.2byte   -9,   -5, 	   4,   -9, 	  -2,   -3, 	  -1,   -4
.2byte    0,   -9, 	   5,   -7, 	  -5,   -7, 	   0,   -4
.2byte    9,   -5, 	  -4,   -9, 	   2,   -3, 	   1,   -4
.2byte   10,    1, 	  -1,  -10, 	  -1,   -5, 	   1,   -2
.2byte    8,    3, 	   1,   -9, 	  -4,   -5, 	  -1,   -2
.2byte    0,    4, 	  -6,   -7, 	   6,   -7, 	   0,   -3
.2byte   -8,    2, 	  -2,   -9, 	   5,   -3, 	   0,   -2
.2byte  -10,   -1, 	   3,   -9, 	   3,   -1, 	  -1,   -3
.2byte   -8,   -7, 	   5,   -7, 	  -1,   -1, 	   0,   -4
.2byte    0,  -12, 	   5,   -5, 	  -5,   -5, 	   0,   -6
.2byte    8,   -7, 	  -5,   -7, 	   1,   -1, 	   0,   -4
.2byte   10,   -1, 	  -3,   -9, 	  -3,   -1, 	   1,   -3
.2byte    8,    2, 	   2,   -9, 	  -5,   -3, 	   0,   -2
sDunsparceAnimTable1:
.4byte sDunsparceAnims_1_1
.4byte sDunsparceAnims_1_2
.4byte sDunsparceAnims_1_3
.4byte sDunsparceAnims_1_4
.4byte sDunsparceAnims_1_5
.4byte sDunsparceAnims_1_6
.4byte sDunsparceAnims_1_7
.4byte sDunsparceAnims_1_8
sDunsparceAnimTable2:
.4byte sDunsparceAnims_2_1
.4byte sDunsparceAnims_2_2
.4byte sDunsparceAnims_2_3
.4byte sDunsparceAnims_2_4
.4byte sDunsparceAnims_2_5
.4byte sDunsparceAnims_2_6
.4byte sDunsparceAnims_2_7
.4byte sDunsparceAnims_2_8
sDunsparceAnimTable3:
.4byte sDunsparceAnims_3_1
.4byte sDunsparceAnims_3_2
.4byte sDunsparceAnims_3_3
.4byte sDunsparceAnims_3_4
.4byte sDunsparceAnims_3_5
.4byte sDunsparceAnims_3_6
.4byte sDunsparceAnims_3_7
.4byte sDunsparceAnims_3_8
sDunsparceAnimTable4:
.4byte sDunsparceAnims_4_1
.4byte sDunsparceAnims_4_2
.4byte sDunsparceAnims_4_3
.4byte sDunsparceAnims_4_4
.4byte sDunsparceAnims_4_5
.4byte sDunsparceAnims_4_6
.4byte sDunsparceAnims_4_7
.4byte sDunsparceAnims_4_8
sDunsparceAnimTable5:
.4byte sDunsparceAnims_5_1
.4byte sDunsparceAnims_5_2
.4byte sDunsparceAnims_5_3
.4byte sDunsparceAnims_5_4
.4byte sDunsparceAnims_5_5
.4byte sDunsparceAnims_5_6
.4byte sDunsparceAnims_5_7
.4byte sDunsparceAnims_5_8
sDunsparceAnimTable6:
.4byte sDunsparceAnims_6_1
.4byte sDunsparceAnims_6_1
.4byte sDunsparceAnims_6_1
.4byte sDunsparceAnims_6_1
.4byte sDunsparceAnims_6_1
.4byte sDunsparceAnims_6_1
.4byte sDunsparceAnims_6_1
.4byte sDunsparceAnims_6_1
sDunsparceAnimTable7:
.4byte sDunsparceAnims_7_1
.4byte sDunsparceAnims_7_2
.4byte sDunsparceAnims_7_3
.4byte sDunsparceAnims_7_4
.4byte sDunsparceAnims_7_5
.4byte sDunsparceAnims_7_6
.4byte sDunsparceAnims_7_7
.4byte sDunsparceAnims_7_8
sDunsparceAnimTable8:
.4byte sDunsparceAnims_8_1
.4byte sDunsparceAnims_8_2
.4byte sDunsparceAnims_8_3
.4byte sDunsparceAnims_8_4
.4byte sDunsparceAnims_8_5
.4byte sDunsparceAnims_8_6
.4byte sDunsparceAnims_8_7
.4byte sDunsparceAnims_8_8
sDunsparceAnimTable9:
.4byte sDunsparceAnims_9_1
.4byte sDunsparceAnims_9_2
.4byte sDunsparceAnims_9_3
.4byte sDunsparceAnims_9_4
.4byte sDunsparceAnims_9_5
.4byte sDunsparceAnims_9_6
.4byte sDunsparceAnims_9_7
.4byte sDunsparceAnims_9_8
sDunsparceAnimTable10:
.4byte sDunsparceAnims_10_1
.4byte sDunsparceAnims_10_2
.4byte sDunsparceAnims_10_3
.4byte sDunsparceAnims_10_4
.4byte sDunsparceAnims_10_5
.4byte sDunsparceAnims_10_6
.4byte sDunsparceAnims_10_7
.4byte sDunsparceAnims_10_8
sDunsparceAnimTable11:
.4byte sDunsparceAnims_11_1
.4byte sDunsparceAnims_11_2
.4byte sDunsparceAnims_11_3
.4byte sDunsparceAnims_11_4
.4byte sDunsparceAnims_11_5
.4byte sDunsparceAnims_11_6
.4byte sDunsparceAnims_11_7
.4byte sDunsparceAnims_11_8
sDunsparceAnimTable12:
.4byte sDunsparceAnims_12_1
.4byte sDunsparceAnims_12_2
.4byte sDunsparceAnims_12_3
.4byte sDunsparceAnims_12_4
.4byte sDunsparceAnims_12_5
.4byte sDunsparceAnims_12_6
.4byte sDunsparceAnims_12_7
.4byte sDunsparceAnims_12_8
sDunsparceAnimTable13:
.4byte sDunsparceAnims_13_1
.4byte sDunsparceAnims_13_2
.4byte sDunsparceAnims_13_3
.4byte sDunsparceAnims_13_4
.4byte sDunsparceAnims_13_5
.4byte sDunsparceAnims_13_6
.4byte sDunsparceAnims_13_7
.4byte sDunsparceAnims_13_8
sAxAnimationsDunsparce:
.4byte sDunsparceAnimTable1
.4byte sDunsparceAnimTable2
.4byte sDunsparceAnimTable3
.4byte sDunsparceAnimTable4
.4byte sDunsparceAnimTable5
.4byte sDunsparceAnimTable6
.4byte sDunsparceAnimTable7
.4byte sDunsparceAnimTable8
.4byte sDunsparceAnimTable9
.4byte sDunsparceAnimTable10
.4byte sDunsparceAnimTable11
.4byte sDunsparceAnimTable12
.4byte sDunsparceAnimTable13
sAxSpritesDunsparce:
.4byte sDunsparceSprites1
.4byte sDunsparceSprites2
.4byte sDunsparceSprites3
.4byte sDunsparceSprites4
.4byte sDunsparceSprites5
.4byte sDunsparceSprites6
.4byte sDunsparceSprites7
.4byte sDunsparceSprites8
.4byte sDunsparceSprites9
.4byte sDunsparceSprites10
.4byte sDunsparceSprites11
.4byte sDunsparceSprites12
.4byte sDunsparceSprites13
.4byte sDunsparceSprites14
.4byte sDunsparceSprites15
.4byte sDunsparceSprites16
.4byte sDunsparceSprites17
.4byte sDunsparceSprites18
.4byte sDunsparceSprites19
.4byte sDunsparceSprites20
.4byte sDunsparceSprites21
.4byte sDunsparceSprites22
.4byte sDunsparceSprites23
.4byte sDunsparceSprites24
.4byte sDunsparceSprites25
.4byte sDunsparceSprites26
.4byte sDunsparceSprites27
.4byte sDunsparceSprites28
.4byte sDunsparceSprites29
.4byte sDunsparceSprites30
.4byte sDunsparceSprites31
.4byte sDunsparceSprites32
.4byte sDunsparceSprites33
.4byte sDunsparceSprites34
.4byte sDunsparceSprites35
.4byte sDunsparceSprites36
.4byte sDunsparceSprites37
.4byte sDunsparceSprites38
.4byte sDunsparceSprites39
.4byte sDunsparceSprites40
.4byte sDunsparceSprites41
.4byte sDunsparceSprites42
.4byte sDunsparceSprites43
.4byte sDunsparceSprites44
.4byte sDunsparceSprites45
.4byte sDunsparceSprites46
.4byte sDunsparceSprites47
sAxMainDunsparce:
ax_main sAxPosesDunsparce, sAxAnimationsDunsparce, 13, sAxSpritesDunsparce, sAxPositionsDunsparce
