.global gAxEntei
gAxEntei:
ax_siro sAxMainEntei
sEnteiPose1:
ax_pose 0, 0x01e4, 0x80f0, 0xcc00
ax_pose_terminator
sEnteiPose2:
ax_pose 1, 0x01e6, 0x80f0, 0xcc00
ax_pose_terminator
sEnteiPose3:
ax_pose 2, 0x01e6, 0x80f0, 0xcc00
ax_pose_terminator
sEnteiPose4:
ax_pose 3, 0x01e4, 0x90f1, 0xcc00
ax_pose_terminator
sEnteiPose5:
ax_pose 4, 0x01e6, 0x90f1, 0xcc00
ax_pose_terminator
sEnteiPose6:
ax_pose 5, 0x01e6, 0x90f1, 0xcc00
ax_pose_terminator
sEnteiPose7:
ax_pose 6, 0x01e4, 0x90f2, 0xcc00
ax_pose_terminator
sEnteiPose8:
ax_pose 7, 0x01e4, 0x90f2, 0xcc00
ax_pose_terminator
sEnteiPose9:
ax_pose 8, 0x01e4, 0x90f2, 0xcc00
ax_pose_terminator
sEnteiPose10:
ax_pose 9, 0x01e4, 0x90f1, 0xcc00
ax_pose_terminator
sEnteiPose11:
ax_pose 10, 0x01e4, 0x90f1, 0xcc00
ax_pose_terminator
sEnteiPose12:
ax_pose 11, 0x81e3, 0x9100, 0xcc00
ax_pose 12, 0x81e3, 0x50f8, 0xcc08
ax_pose 13, 0x81eb, 0x10f0, 0xcc0c
ax_pose 14, 0x01fb, 0x10f0, 0xcc0e
ax_pose 15, 0x0203, 0x10f8, 0xcc0f
ax_pose_terminator
sEnteiPose13:
ax_pose 16, 0x01e3, 0x80f0, 0xcc00
ax_pose_terminator
sEnteiPose14:
ax_pose 17, 0x81e3, 0x80f0, 0xcc00
ax_pose 18, 0x81e3, 0x4100, 0xcc08
ax_pose 19, 0x0203, 0x0100, 0xcc0c
ax_pose 20, 0x01eb, 0x0108, 0xcc0d
ax_pose 21, 0x81f3, 0x0108, 0xcc0e
ax_pose_terminator
sEnteiPose15:
ax_pose 22, 0x81e3, 0x80f0, 0xcc00
ax_pose 23, 0x81e3, 0x4100, 0xcc08
ax_pose 24, 0x81eb, 0x0108, 0xcc0c
ax_pose 25, 0x01fb, 0x0108, 0xcc0e
ax_pose 26, 0x0203, 0x00f8, 0xcc0f
ax_pose_terminator
sEnteiPose16:
ax_pose 9, 0x01e4, 0x80f0, 0xcc00
ax_pose_terminator
sEnteiPose17:
ax_pose 10, 0x01e4, 0x80f0, 0xcc00
ax_pose_terminator
sEnteiPose18:
ax_pose 11, 0x81e3, 0x80f1, 0xcc00
ax_pose 12, 0x81e3, 0x4101, 0xcc08
ax_pose 15, 0x0203, 0x0101, 0xcc0c
ax_pose 13, 0x81eb, 0x0109, 0xcc0d
ax_pose 14, 0x01fb, 0x0109, 0xcc0f
ax_pose_terminator
sEnteiPose19:
ax_pose 6, 0x01e4, 0x80ef, 0xcc00
ax_pose_terminator
sEnteiPose20:
ax_pose 7, 0x01e4, 0x80ef, 0xcc00
ax_pose_terminator
sEnteiPose21:
ax_pose 8, 0x01e4, 0x80ef, 0xcc00
ax_pose_terminator
sEnteiPose22:
ax_pose 3, 0x01e4, 0x80f0, 0xcc00
ax_pose_terminator
sEnteiPose23:
ax_pose 4, 0x01e6, 0x80f0, 0xcc00
ax_pose_terminator
sEnteiPose24:
ax_pose 5, 0x01e6, 0x80f0, 0xcc00
ax_pose_terminator
sEnteiPose25:
ax_pose 0, 0x01e4, 0x80f0, 0xcc00
ax_pose_terminator
sEnteiPose26:
ax_pose 1, 0x01e6, 0x80f0, 0xcc00
ax_pose_terminator
sEnteiPose27:
ax_pose 2, 0x01e6, 0x80f0, 0xcc00
ax_pose_terminator
sEnteiPose28:
ax_pose 3, 0x01e4, 0x90f1, 0xcc00
ax_pose_terminator
sEnteiPose29:
ax_pose 4, 0x01e6, 0x90f1, 0xcc00
ax_pose_terminator
sEnteiPose30:
ax_pose 5, 0x01e6, 0x90f1, 0xcc00
ax_pose_terminator
sEnteiPose31:
ax_pose 6, 0x01e4, 0x90f2, 0xcc00
ax_pose_terminator
sEnteiPose32:
ax_pose 7, 0x01e4, 0x90f2, 0xcc00
ax_pose_terminator
sEnteiPose33:
ax_pose 8, 0x01e4, 0x90f2, 0xcc00
ax_pose_terminator
sEnteiPose34:
ax_pose 9, 0x01e4, 0x90f1, 0xcc00
ax_pose_terminator
sEnteiPose35:
ax_pose 10, 0x01e4, 0x90f1, 0xcc00
ax_pose_terminator
sEnteiPose36:
ax_pose 11, 0x81e3, 0x9100, 0xcc00
ax_pose 12, 0x81e3, 0x50f8, 0xcc08
ax_pose 13, 0x81eb, 0x10f0, 0xcc0c
ax_pose 14, 0x01fb, 0x10f0, 0xcc0e
ax_pose 15, 0x0203, 0x10f8, 0xcc0f
ax_pose_terminator
sEnteiPose37:
ax_pose 16, 0x01e3, 0x80f0, 0xcc00
ax_pose_terminator
sEnteiPose38:
ax_pose 17, 0x81e3, 0x80f0, 0xcc00
ax_pose 18, 0x81e3, 0x4100, 0xcc08
ax_pose 19, 0x0203, 0x0100, 0xcc0c
ax_pose 20, 0x01eb, 0x0108, 0xcc0d
ax_pose 21, 0x81f3, 0x0108, 0xcc0e
ax_pose_terminator
sEnteiPose39:
ax_pose 22, 0x81e3, 0x80f0, 0xcc00
ax_pose 23, 0x81e3, 0x4100, 0xcc08
ax_pose 24, 0x81eb, 0x0108, 0xcc0c
ax_pose 25, 0x01fb, 0x0108, 0xcc0e
ax_pose 26, 0x0203, 0x00f8, 0xcc0f
ax_pose_terminator
sEnteiPose40:
ax_pose 9, 0x01e4, 0x80f0, 0xcc00
ax_pose_terminator
sEnteiPose41:
ax_pose 10, 0x01e4, 0x80f0, 0xcc00
ax_pose_terminator
sEnteiPose42:
ax_pose 11, 0x81e3, 0x80f1, 0xcc00
ax_pose 12, 0x81e3, 0x4101, 0xcc08
ax_pose 15, 0x0203, 0x0101, 0xcc0c
ax_pose 13, 0x81eb, 0x0109, 0xcc0d
ax_pose 14, 0x01fb, 0x0109, 0xcc0f
ax_pose_terminator
sEnteiPose43:
ax_pose 6, 0x01e4, 0x80ef, 0xcc00
ax_pose_terminator
sEnteiPose44:
ax_pose 7, 0x01e4, 0x80ef, 0xcc00
ax_pose_terminator
sEnteiPose45:
ax_pose 8, 0x01e4, 0x80ef, 0xcc00
ax_pose_terminator
sEnteiPose46:
ax_pose 3, 0x01e4, 0x80f0, 0xcc00
ax_pose_terminator
sEnteiPose47:
ax_pose 4, 0x01e6, 0x80f0, 0xcc00
ax_pose_terminator
sEnteiPose48:
ax_pose 5, 0x01e6, 0x80f0, 0xcc00
ax_pose_terminator
sEnteiPose49:
ax_pose 0, 0x01e4, 0x80f0, 0xcc00
ax_pose_terminator
sEnteiPose50:
ax_pose 1, 0x01e6, 0x80f0, 0xcc00
ax_pose_terminator
sEnteiPose51:
ax_pose 2, 0x01e6, 0x80f0, 0xcc00
ax_pose_terminator
sEnteiPose52:
ax_pose 3, 0x01e4, 0x90f1, 0xcc00
ax_pose_terminator
sEnteiPose53:
ax_pose 4, 0x01e6, 0x90f1, 0xcc00
ax_pose_terminator
sEnteiPose54:
ax_pose 5, 0x01e6, 0x90f1, 0xcc00
ax_pose_terminator
sEnteiPose55:
ax_pose 6, 0x01e4, 0x90f2, 0xcc00
ax_pose_terminator
sEnteiPose56:
ax_pose 7, 0x01e4, 0x90f2, 0xcc00
ax_pose_terminator
sEnteiPose57:
ax_pose 8, 0x01e4, 0x90f2, 0xcc00
ax_pose_terminator
sEnteiPose58:
ax_pose 9, 0x01e4, 0x90f1, 0xcc00
ax_pose_terminator
sEnteiPose59:
ax_pose 10, 0x01e4, 0x90f1, 0xcc00
ax_pose_terminator
sEnteiPose60:
ax_pose 11, 0x81e3, 0x9100, 0xcc00
ax_pose 12, 0x81e3, 0x50f8, 0xcc08
ax_pose 13, 0x81eb, 0x10f0, 0xcc0c
ax_pose 14, 0x01fb, 0x10f0, 0xcc0e
ax_pose 15, 0x0203, 0x10f8, 0xcc0f
ax_pose_terminator
sEnteiPose61:
ax_pose 16, 0x01e3, 0x80f0, 0xcc00
ax_pose_terminator
sEnteiPose62:
ax_pose 17, 0x81e3, 0x80f0, 0xcc00
ax_pose 18, 0x81e3, 0x4100, 0xcc08
ax_pose 19, 0x0203, 0x0100, 0xcc0c
ax_pose 20, 0x01eb, 0x0108, 0xcc0d
ax_pose 21, 0x81f3, 0x0108, 0xcc0e
ax_pose_terminator
sEnteiPose63:
ax_pose 22, 0x81e3, 0x80f0, 0xcc00
ax_pose 23, 0x81e3, 0x4100, 0xcc08
ax_pose 24, 0x81eb, 0x0108, 0xcc0c
ax_pose 25, 0x01fb, 0x0108, 0xcc0e
ax_pose 26, 0x0203, 0x00f8, 0xcc0f
ax_pose_terminator
sEnteiPose64:
ax_pose 9, 0x01e4, 0x80f0, 0xcc00
ax_pose_terminator
sEnteiPose65:
ax_pose 10, 0x01e4, 0x80f0, 0xcc00
ax_pose_terminator
sEnteiPose66:
ax_pose 11, 0x81e3, 0x80f1, 0xcc00
ax_pose 12, 0x81e3, 0x4101, 0xcc08
ax_pose 15, 0x0203, 0x0101, 0xcc0c
ax_pose 13, 0x81eb, 0x0109, 0xcc0d
ax_pose 14, 0x01fb, 0x0109, 0xcc0f
ax_pose_terminator
sEnteiPose67:
ax_pose 6, 0x01e4, 0x80ef, 0xcc00
ax_pose_terminator
sEnteiPose68:
ax_pose 7, 0x01e4, 0x80ef, 0xcc00
ax_pose_terminator
sEnteiPose69:
ax_pose 8, 0x01e4, 0x80ef, 0xcc00
ax_pose_terminator
sEnteiPose70:
ax_pose 3, 0x01e4, 0x80f0, 0xcc00
ax_pose_terminator
sEnteiPose71:
ax_pose 4, 0x01e6, 0x80f0, 0xcc00
ax_pose_terminator
sEnteiPose72:
ax_pose 5, 0x01e6, 0x80f0, 0xcc00
ax_pose_terminator
sEnteiPose73:
ax_pose 0, 0x01e4, 0x80f0, 0xcc00
ax_pose_terminator
sEnteiPose74:
ax_pose 27, 0x81e4, 0x80ff, 0xcc00
ax_pose 28, 0x81e4, 0x40f7, 0xcc08
ax_pose 29, 0x81e4, 0x00ef, 0xcc0c
ax_pose 30, 0x01f4, 0x00ef, 0xcc0e
ax_pose 31, 0x01dc, 0x00fc, 0xcc0f
ax_pose_terminator
sEnteiPose75:
ax_pose 32, 0x01e4, 0x80f0, 0xcc00
ax_pose_terminator
sEnteiPose76:
ax_pose 3, 0x01e4, 0x90f1, 0xcc00
ax_pose_terminator
sEnteiPose77:
ax_pose 33, 0x81e4, 0x90fc, 0xcc00
ax_pose 34, 0x81e4, 0x50f4, 0xcc08
ax_pose 35, 0x01ec, 0x10ec, 0xcc0c
ax_pose 36, 0x01dc, 0x1104, 0xcc0d
ax_pose 37, 0x01dc, 0x10fc, 0xcc0e
ax_pose_terminator
sEnteiPose78:
ax_pose 38, 0x01e4, 0x90f3, 0xcc00
ax_pose_terminator
sEnteiPose79:
ax_pose 6, 0x01e4, 0x90f2, 0xcc00
ax_pose_terminator
sEnteiPose80:
ax_pose 39, 0x01e3, 0x50fd, 0xcc00
ax_pose 40, 0x81e3, 0x10f5, 0xcc04
ax_pose 41, 0x01db, 0x1105, 0xcc06
ax_pose 42, 0x01db, 0x10fd, 0xcc07
ax_pose 43, 0x41f3, 0x50ed, 0xcc08
ax_pose 44, 0x41fb, 0x10fb, 0xcc0c
ax_pose 45, 0x01fb, 0x10f3, 0xcc0e
ax_pose_terminator
sEnteiPose81:
ax_pose 46, 0x01e3, 0x5104, 0xcc00
ax_pose 47, 0x81e3, 0x50fc, 0xcc04
ax_pose 48, 0x01eb, 0x1114, 0xcc08
ax_pose 49, 0x01eb, 0x10f4, 0xcc09
ax_pose 50, 0x81f3, 0x10f4, 0xcc0a
ax_pose 51, 0x01f3, 0x1114, 0xcc0c
ax_pose 52, 0x41f3, 0x1104, 0xcc0d
ax_pose 53, 0x01fb, 0x1104, 0xcc0f
ax_pose_terminator
sEnteiPose82:
ax_pose 9, 0x01e4, 0x90f1, 0xcc00
ax_pose_terminator
sEnteiPose83:
ax_pose 54, 0x81e4, 0x90f3, 0xcc00
ax_pose 55, 0x81e4, 0x5103, 0xcc08
ax_pose 56, 0x01dc, 0x1103, 0xcc0c
ax_pose 57, 0x01dc, 0x10fb, 0xcc0d
ax_pose 58, 0x01fc, 0x110b, 0xcc0e
ax_pose_terminator
sEnteiPose84:
ax_pose 59, 0x01e4, 0x90f1, 0xcc00
ax_pose_terminator
sEnteiPose85:
ax_pose 16, 0x01e3, 0x80f0, 0xcc00
ax_pose_terminator
sEnteiPose86:
ax_pose 60, 0x81e3, 0x80ff, 0xcc00
ax_pose 61, 0x81e3, 0x40f7, 0xcc08
ax_pose 62, 0x01eb, 0x00ef, 0xcc0c
ax_pose 63, 0x01f3, 0x00ef, 0xcc0d
ax_pose 64, 0x01db, 0x00ff, 0xcc0e
ax_pose 65, 0x01db, 0x00f7, 0xcc0f
ax_pose_terminator
sEnteiPose87:
ax_pose 66, 0x01e3, 0x80f0, 0xcc00
ax_pose_terminator
sEnteiPose88:
ax_pose 9, 0x01e4, 0x80f0, 0xcc00
ax_pose_terminator
sEnteiPose89:
ax_pose 54, 0x81e4, 0x80fe, 0xcc00
ax_pose 55, 0x81e4, 0x40f6, 0xcc08
ax_pose 56, 0x01dc, 0x00f6, 0xcc0c
ax_pose 57, 0x01dc, 0x00fe, 0xcc0d
ax_pose 58, 0x01fc, 0x00ee, 0xcc0e
ax_pose_terminator
sEnteiPose90:
ax_pose 59, 0x01e4, 0x80f0, 0xcc00
ax_pose_terminator
sEnteiPose91:
ax_pose 6, 0x01e4, 0x80ef, 0xcc00
ax_pose_terminator
sEnteiPose92:
ax_pose 39, 0x01e3, 0x40f4, 0xcc00
ax_pose 40, 0x81e3, 0x0104, 0xcc04
ax_pose 41, 0x01db, 0x00f4, 0xcc06
ax_pose 42, 0x01db, 0x00fc, 0xcc07
ax_pose 43, 0x41f3, 0x40f4, 0xcc08
ax_pose 44, 0x41fb, 0x00f6, 0xcc0c
ax_pose 45, 0x01fb, 0x0106, 0xcc0e
ax_pose_terminator
sEnteiPose93:
ax_pose 46, 0x01e3, 0x40ed, 0xcc00
ax_pose 47, 0x81e3, 0x40fd, 0xcc04
ax_pose 48, 0x01eb, 0x00e5, 0xcc08
ax_pose 49, 0x01eb, 0x0105, 0xcc09
ax_pose 50, 0x81f3, 0x0105, 0xcc0a
ax_pose 51, 0x01f3, 0x00e5, 0xcc0c
ax_pose 52, 0x41f3, 0x00ed, 0xcc0d
ax_pose 53, 0x01fb, 0x00f5, 0xcc0f
ax_pose_terminator
sEnteiPose94:
ax_pose 3, 0x01e4, 0x80f0, 0xcc00
ax_pose_terminator
sEnteiPose95:
ax_pose 33, 0x81e4, 0x80f5, 0xcc00
ax_pose 34, 0x81e4, 0x4105, 0xcc08
ax_pose 35, 0x01ec, 0x010d, 0xcc0c
ax_pose 36, 0x01dc, 0x00f5, 0xcc0d
ax_pose 37, 0x01dc, 0x00fd, 0xcc0e
ax_pose_terminator
sEnteiPose96:
ax_pose 38, 0x01e4, 0x80ee, 0xcc00
ax_pose_terminator
sEnteiPose97:
ax_pose 0, 0x01e4, 0x80f0, 0xcc00
ax_pose_terminator
sEnteiPose98:
ax_pose 27, 0x81e4, 0x80ff, 0xcc00
ax_pose 28, 0x81e4, 0x40f7, 0xcc08
ax_pose 29, 0x81e4, 0x00ef, 0xcc0c
ax_pose 30, 0x01f4, 0x00ef, 0xcc0e
ax_pose 31, 0x01dc, 0x00fc, 0xcc0f
ax_pose_terminator
sEnteiPose99:
ax_pose 32, 0x01e4, 0x80f0, 0xcc00
ax_pose_terminator
sEnteiPose100:
ax_pose 67, 0x01e8, 0x80f0, 0xcc00
ax_pose_terminator
sEnteiPose101:
ax_pose 3, 0x01e4, 0x90f1, 0xcc00
ax_pose_terminator
sEnteiPose102:
ax_pose 33, 0x81e4, 0x90fc, 0xcc00
ax_pose 34, 0x81e4, 0x50f4, 0xcc08
ax_pose 35, 0x01ec, 0x10ec, 0xcc0c
ax_pose 36, 0x01dc, 0x1104, 0xcc0d
ax_pose 37, 0x01dc, 0x10fc, 0xcc0e
ax_pose_terminator
sEnteiPose103:
ax_pose 38, 0x01e4, 0x90f3, 0xcc00
ax_pose_terminator
sEnteiPose104:
ax_pose 68, 0x01e9, 0x90f4, 0xcc00
ax_pose_terminator
sEnteiPose105:
ax_pose 6, 0x01e4, 0x90f2, 0xcc00
ax_pose_terminator
sEnteiPose106:
ax_pose 39, 0x01e3, 0x50fd, 0xcc00
ax_pose 40, 0x81e3, 0x10f5, 0xcc04
ax_pose 41, 0x01db, 0x1105, 0xcc06
ax_pose 42, 0x01db, 0x10fd, 0xcc07
ax_pose 43, 0x41f3, 0x50ed, 0xcc08
ax_pose 44, 0x41fb, 0x10fb, 0xcc0c
ax_pose 45, 0x01fb, 0x10f3, 0xcc0e
ax_pose_terminator
sEnteiPose107:
ax_pose 46, 0x01e3, 0x5104, 0xcc00
ax_pose 47, 0x81e3, 0x50fc, 0xcc04
ax_pose 48, 0x01eb, 0x1114, 0xcc08
ax_pose 49, 0x01eb, 0x10f4, 0xcc09
ax_pose 50, 0x81f3, 0x10f4, 0xcc0a
ax_pose 51, 0x01f3, 0x1114, 0xcc0c
ax_pose 52, 0x41f3, 0x1104, 0xcc0d
ax_pose 53, 0x01fb, 0x1104, 0xcc0f
ax_pose_terminator
sEnteiPose108:
ax_pose 69, 0x01f4, 0x5101, 0xcc00
ax_pose 70, 0x01ec, 0x1111, 0xcc04
ax_pose 71, 0x01e4, 0x1101, 0xcc05
ax_pose 72, 0x41ec, 0x1101, 0xcc06
ax_pose 73, 0x81e4, 0x50f9, 0xcc08
ax_pose 74, 0x01f4, 0x1111, 0xcc0c
ax_pose 75, 0x01ec, 0x10f1, 0xcc0d
ax_pose 76, 0x81f4, 0x10f1, 0xcc0e
ax_pose_terminator
sEnteiPose109:
ax_pose 9, 0x01e4, 0x90f1, 0xcc00
ax_pose_terminator
sEnteiPose110:
ax_pose 54, 0x81e4, 0x90f3, 0xcc00
ax_pose 55, 0x81e4, 0x5103, 0xcc08
ax_pose 56, 0x01dc, 0x1103, 0xcc0c
ax_pose 57, 0x01dc, 0x10fb, 0xcc0d
ax_pose 58, 0x01fc, 0x110b, 0xcc0e
ax_pose_terminator
sEnteiPose111:
ax_pose 59, 0x01e4, 0x90f1, 0xcc00
ax_pose_terminator
sEnteiPose112:
ax_pose 77, 0x01e9, 0x90f2, 0xcc00
ax_pose_terminator
sEnteiPose113:
ax_pose 16, 0x01e3, 0x80f0, 0xcc00
ax_pose_terminator
sEnteiPose114:
ax_pose 60, 0x81e3, 0x80ff, 0xcc00
ax_pose 61, 0x81e3, 0x40f7, 0xcc08
ax_pose 62, 0x01eb, 0x00ef, 0xcc0c
ax_pose 63, 0x01f3, 0x00ef, 0xcc0d
ax_pose 64, 0x01db, 0x00ff, 0xcc0e
ax_pose 65, 0x01db, 0x00f7, 0xcc0f
ax_pose_terminator
sEnteiPose115:
ax_pose 66, 0x01e3, 0x80f0, 0xcc00
ax_pose_terminator
sEnteiPose116:
ax_pose 78, 0x01e5, 0x80f0, 0xcc00
ax_pose_terminator
sEnteiPose117:
ax_pose 9, 0x01e4, 0x80f0, 0xcc00
ax_pose_terminator
sEnteiPose118:
ax_pose 54, 0x81e4, 0x80fe, 0xcc00
ax_pose 55, 0x81e4, 0x40f6, 0xcc08
ax_pose 56, 0x01dc, 0x00f6, 0xcc0c
ax_pose 57, 0x01dc, 0x00fe, 0xcc0d
ax_pose 58, 0x01fc, 0x00ee, 0xcc0e
ax_pose_terminator
sEnteiPose119:
ax_pose 59, 0x01e4, 0x80f0, 0xcc00
ax_pose_terminator
sEnteiPose120:
ax_pose 77, 0x01e9, 0x80f1, 0xcc00
ax_pose_terminator
sEnteiPose121:
ax_pose 6, 0x01e4, 0x80ef, 0xcc00
ax_pose_terminator
sEnteiPose122:
ax_pose 39, 0x01e3, 0x40f4, 0xcc00
ax_pose 40, 0x81e3, 0x0104, 0xcc04
ax_pose 41, 0x01db, 0x00f4, 0xcc06
ax_pose 42, 0x01db, 0x00fc, 0xcc07
ax_pose 43, 0x41f3, 0x40f4, 0xcc08
ax_pose 44, 0x41fb, 0x00f6, 0xcc0c
ax_pose 45, 0x01fb, 0x0106, 0xcc0e
ax_pose_terminator
sEnteiPose123:
ax_pose 46, 0x01e3, 0x40ed, 0xcc00
ax_pose 47, 0x81e3, 0x40fd, 0xcc04
ax_pose 48, 0x01eb, 0x00e5, 0xcc08
ax_pose 49, 0x01eb, 0x0105, 0xcc09
ax_pose 50, 0x81f3, 0x0105, 0xcc0a
ax_pose 51, 0x01f3, 0x00e5, 0xcc0c
ax_pose 52, 0x41f3, 0x00ed, 0xcc0d
ax_pose 53, 0x01fb, 0x00f5, 0xcc0f
ax_pose_terminator
sEnteiPose124:
ax_pose 69, 0x01f4, 0x40ef, 0xcc00
ax_pose 70, 0x01ec, 0x00e7, 0xcc04
ax_pose 71, 0x01e4, 0x00f7, 0xcc05
ax_pose 72, 0x41ec, 0x00ef, 0xcc06
ax_pose 73, 0x81e4, 0x40ff, 0xcc08
ax_pose 74, 0x01f4, 0x00e7, 0xcc0c
ax_pose 75, 0x01ec, 0x0107, 0xcc0d
ax_pose 76, 0x81f4, 0x0107, 0xcc0e
ax_pose_terminator
sEnteiPose125:
ax_pose 3, 0x01e4, 0x80f0, 0xcc00
ax_pose_terminator
sEnteiPose126:
ax_pose 33, 0x81e4, 0x80f5, 0xcc00
ax_pose 34, 0x81e4, 0x4105, 0xcc08
ax_pose 35, 0x01ec, 0x010d, 0xcc0c
ax_pose 36, 0x01dc, 0x00f5, 0xcc0d
ax_pose 37, 0x01dc, 0x00fd, 0xcc0e
ax_pose_terminator
sEnteiPose127:
ax_pose 38, 0x01e4, 0x80ee, 0xcc00
ax_pose_terminator
sEnteiPose128:
ax_pose 68, 0x01e9, 0x80ed, 0xcc00
ax_pose_terminator
sEnteiPose129:
ax_pose 79, 0x01e4, 0x80f0, 0xcc00
ax_pose_terminator
sEnteiPose130:
ax_pose 80, 0x01e4, 0x80f0, 0xcc00
ax_pose_terminator
sEnteiPose131:
ax_pose 81, 0x01e4, 0x80f0, 0xcc00
ax_pose_terminator
sEnteiPose132:
ax_pose 82, 0x01e4, 0x90f0, 0xcc00
ax_pose_terminator
sEnteiPose133:
ax_pose 83, 0x01e4, 0x90f1, 0xcc00
ax_pose_terminator
sEnteiPose134:
ax_pose 84, 0x01e6, 0x90f0, 0xcc00
ax_pose_terminator
sEnteiPose135:
ax_pose 85, 0x01e5, 0x80f0, 0xcc00
ax_pose_terminator
sEnteiPose136:
ax_pose 84, 0x01e6, 0x80f0, 0xcc00
ax_pose_terminator
sEnteiPose137:
ax_pose 83, 0x01e4, 0x80ef, 0xcc00
ax_pose_terminator
sEnteiPose138:
ax_pose 82, 0x01e4, 0x80f0, 0xcc00
ax_pose_terminator
sEnteiPose139:
ax_pose 0, 0x01e4, 0x80f0, 0xcc00
ax_pose_terminator
sEnteiPose140:
ax_pose 27, 0x81e4, 0x80ff, 0xcc00
ax_pose 28, 0x81e4, 0x40f7, 0xcc08
ax_pose 29, 0x81e4, 0x00ef, 0xcc0c
ax_pose 30, 0x01f4, 0x00ef, 0xcc0e
ax_pose 31, 0x01dc, 0x00fc, 0xcc0f
ax_pose_terminator
sEnteiPose141:
ax_pose 32, 0x01e4, 0x80f0, 0xcc00
ax_pose_terminator
sEnteiPose142:
ax_pose 3, 0x01e4, 0x90f1, 0xcc00
ax_pose_terminator
sEnteiPose143:
ax_pose 33, 0x81e4, 0x90fc, 0xcc00
ax_pose 34, 0x81e4, 0x50f4, 0xcc08
ax_pose 35, 0x01ec, 0x10ec, 0xcc0c
ax_pose 36, 0x01dc, 0x1104, 0xcc0d
ax_pose 37, 0x01dc, 0x10fc, 0xcc0e
ax_pose_terminator
sEnteiPose144:
ax_pose 38, 0x01e4, 0x90f3, 0xcc00
ax_pose_terminator
sEnteiPose145:
ax_pose 6, 0x01e4, 0x90f2, 0xcc00
ax_pose_terminator
sEnteiPose146:
ax_pose 39, 0x01e3, 0x50fd, 0xcc00
ax_pose 40, 0x81e3, 0x10f5, 0xcc04
ax_pose 41, 0x01db, 0x1105, 0xcc06
ax_pose 42, 0x01db, 0x10fd, 0xcc07
ax_pose 43, 0x41f3, 0x50ed, 0xcc08
ax_pose 44, 0x41fb, 0x10fb, 0xcc0c
ax_pose 45, 0x01fb, 0x10f3, 0xcc0e
ax_pose_terminator
sEnteiPose147:
ax_pose 46, 0x01e3, 0x5104, 0xcc00
ax_pose 47, 0x81e3, 0x50fc, 0xcc04
ax_pose 48, 0x01eb, 0x1114, 0xcc08
ax_pose 49, 0x01eb, 0x10f4, 0xcc09
ax_pose 50, 0x81f3, 0x10f4, 0xcc0a
ax_pose 51, 0x01f3, 0x1114, 0xcc0c
ax_pose 52, 0x41f3, 0x1104, 0xcc0d
ax_pose 53, 0x01fb, 0x1104, 0xcc0f
ax_pose_terminator
sEnteiPose148:
ax_pose 9, 0x01e4, 0x90f1, 0xcc00
ax_pose_terminator
sEnteiPose149:
ax_pose 54, 0x81e4, 0x90f3, 0xcc00
ax_pose 55, 0x81e4, 0x5103, 0xcc08
ax_pose 56, 0x01dc, 0x1103, 0xcc0c
ax_pose 57, 0x01dc, 0x10fb, 0xcc0d
ax_pose 58, 0x01fc, 0x110b, 0xcc0e
ax_pose_terminator
sEnteiPose150:
ax_pose 59, 0x01e4, 0x90f1, 0xcc00
ax_pose_terminator
sEnteiPose151:
ax_pose 16, 0x01e3, 0x80f0, 0xcc00
ax_pose_terminator
sEnteiPose152:
ax_pose 60, 0x81e3, 0x80ff, 0xcc00
ax_pose 61, 0x81e3, 0x40f7, 0xcc08
ax_pose 62, 0x01eb, 0x00ef, 0xcc0c
ax_pose 63, 0x01f3, 0x00ef, 0xcc0d
ax_pose 64, 0x01db, 0x00ff, 0xcc0e
ax_pose 65, 0x01db, 0x00f7, 0xcc0f
ax_pose_terminator
sEnteiPose153:
ax_pose 66, 0x01e3, 0x80f0, 0xcc00
ax_pose_terminator
sEnteiPose154:
ax_pose 9, 0x01e4, 0x80f0, 0xcc00
ax_pose_terminator
sEnteiPose155:
ax_pose 54, 0x81e4, 0x80fe, 0xcc00
ax_pose 55, 0x81e4, 0x40f6, 0xcc08
ax_pose 56, 0x01dc, 0x00f6, 0xcc0c
ax_pose 57, 0x01dc, 0x00fe, 0xcc0d
ax_pose 58, 0x01fc, 0x00ee, 0xcc0e
ax_pose_terminator
sEnteiPose156:
ax_pose 59, 0x01e4, 0x80f0, 0xcc00
ax_pose_terminator
sEnteiPose157:
ax_pose 6, 0x01e4, 0x80ef, 0xcc00
ax_pose_terminator
sEnteiPose158:
ax_pose 39, 0x01e3, 0x40f4, 0xcc00
ax_pose 40, 0x81e3, 0x0104, 0xcc04
ax_pose 41, 0x01db, 0x00f4, 0xcc06
ax_pose 42, 0x01db, 0x00fc, 0xcc07
ax_pose 43, 0x41f3, 0x40f4, 0xcc08
ax_pose 44, 0x41fb, 0x00f6, 0xcc0c
ax_pose 45, 0x01fb, 0x0106, 0xcc0e
ax_pose_terminator
sEnteiPose159:
ax_pose 46, 0x01e3, 0x40ed, 0xcc00
ax_pose 47, 0x81e3, 0x40fd, 0xcc04
ax_pose 48, 0x01eb, 0x00e5, 0xcc08
ax_pose 49, 0x01eb, 0x0105, 0xcc09
ax_pose 50, 0x81f3, 0x0105, 0xcc0a
ax_pose 51, 0x01f3, 0x00e5, 0xcc0c
ax_pose 52, 0x41f3, 0x00ed, 0xcc0d
ax_pose 53, 0x01fb, 0x00f5, 0xcc0f
ax_pose_terminator
sEnteiPose160:
ax_pose 3, 0x01e4, 0x80f0, 0xcc00
ax_pose_terminator
sEnteiPose161:
ax_pose 33, 0x81e4, 0x80f5, 0xcc00
ax_pose 34, 0x81e4, 0x4105, 0xcc08
ax_pose 35, 0x01ec, 0x010d, 0xcc0c
ax_pose 36, 0x01dc, 0x00f5, 0xcc0d
ax_pose 37, 0x01dc, 0x00fd, 0xcc0e
ax_pose_terminator
sEnteiPose162:
ax_pose 38, 0x01e4, 0x80ee, 0xcc00
ax_pose_terminator
sEnteiPose163:
ax_pose 2, 0x01e6, 0x80f0, 0xcc00
ax_pose_terminator
sEnteiPose164:
ax_pose 5, 0x01e6, 0x80f0, 0xcc00
ax_pose_terminator
sEnteiPose165:
ax_pose 8, 0x01e4, 0x80ef, 0xcc00
ax_pose_terminator
sEnteiPose166:
ax_pose 11, 0x81e3, 0x80f1, 0xcc00
ax_pose 12, 0x81e3, 0x4101, 0xcc08
ax_pose 15, 0x0203, 0x0101, 0xcc0c
ax_pose 13, 0x81eb, 0x0109, 0xcc0d
ax_pose 14, 0x01fb, 0x0109, 0xcc0f
ax_pose_terminator
sEnteiPose167:
ax_pose 22, 0x81e3, 0x80f0, 0xcc00
ax_pose 23, 0x81e3, 0x4100, 0xcc08
ax_pose 24, 0x81eb, 0x0108, 0xcc0c
ax_pose 25, 0x01fb, 0x0108, 0xcc0e
ax_pose 26, 0x0203, 0x00f8, 0xcc0f
ax_pose_terminator
sEnteiPose168:
ax_pose 11, 0x81e3, 0x9100, 0xcc00
ax_pose 12, 0x81e3, 0x50f8, 0xcc08
ax_pose 13, 0x81eb, 0x10f0, 0xcc0c
ax_pose 14, 0x01fb, 0x10f0, 0xcc0e
ax_pose 15, 0x0203, 0x10f8, 0xcc0f
ax_pose_terminator
sEnteiPose169:
ax_pose 8, 0x01e4, 0x90f2, 0xcc00
ax_pose_terminator
sEnteiPose170:
ax_pose 5, 0x01e6, 0x90f1, 0xcc00
ax_pose_terminator
sEnteiPose171:
ax_pose 67, 0x01e8, 0x80f0, 0xcc00
ax_pose_terminator
sEnteiPose172:
ax_pose 68, 0x01e8, 0x90f2, 0xcc00
ax_pose_terminator
sEnteiPose173:
ax_pose 69, 0x01f4, 0x5101, 0xcc00
ax_pose 70, 0x01ec, 0x1111, 0xcc04
ax_pose 71, 0x01e4, 0x1101, 0xcc05
ax_pose 72, 0x41ec, 0x1101, 0xcc06
ax_pose 73, 0x81e4, 0x50f9, 0xcc08
ax_pose 74, 0x01f4, 0x1111, 0xcc0c
ax_pose 75, 0x01ec, 0x10f1, 0xcc0d
ax_pose 76, 0x81f4, 0x10f1, 0xcc0e
ax_pose_terminator
sEnteiPose174:
ax_pose 77, 0x01e8, 0x90f0, 0xcc00
ax_pose_terminator
sEnteiPose175:
ax_pose 78, 0x01e7, 0x80f0, 0xcc00
ax_pose_terminator
sEnteiPose176:
ax_pose 77, 0x01e8, 0x80f1, 0xcc00
ax_pose_terminator
sEnteiPose177:
ax_pose 69, 0x01f4, 0x40ef, 0xcc00
ax_pose 70, 0x01ec, 0x00e7, 0xcc04
ax_pose 71, 0x01e4, 0x00f7, 0xcc05
ax_pose 72, 0x41ec, 0x00ef, 0xcc06
ax_pose 73, 0x81e4, 0x40ff, 0xcc08
ax_pose 74, 0x01f4, 0x00e7, 0xcc0c
ax_pose 75, 0x01ec, 0x0107, 0xcc0d
ax_pose 76, 0x81f4, 0x0107, 0xcc0e
ax_pose_terminator
sEnteiPose178:
ax_pose 68, 0x01e8, 0x80ef, 0xcc00
ax_pose_terminator
sEnteiPose179:
ax_pose 0, 0x01e4, 0x80f0, 0xcc00
ax_pose_terminator
sEnteiPose180:
ax_pose 27, 0x81e4, 0x80ff, 0xcc00
ax_pose 28, 0x81e4, 0x40f7, 0xcc08
ax_pose 29, 0x81e4, 0x00ef, 0xcc0c
ax_pose 30, 0x01f4, 0x00ef, 0xcc0e
ax_pose 31, 0x01dc, 0x00fc, 0xcc0f
ax_pose_terminator
sEnteiPose181:
ax_pose 67, 0x01e8, 0x80f0, 0xcc00
ax_pose_terminator
sEnteiPose182:
ax_pose 3, 0x01e4, 0x90f1, 0xcc00
ax_pose_terminator
sEnteiPose183:
ax_pose 33, 0x81e4, 0x90fc, 0xcc00
ax_pose 34, 0x81e4, 0x50f4, 0xcc08
ax_pose 35, 0x01ec, 0x10ec, 0xcc0c
ax_pose 36, 0x01dc, 0x1104, 0xcc0d
ax_pose 37, 0x01dc, 0x10fc, 0xcc0e
ax_pose_terminator
sEnteiPose184:
ax_pose 68, 0x01e8, 0x90f1, 0xcc00
ax_pose_terminator
sEnteiPose185:
ax_pose 6, 0x01e4, 0x90f2, 0xcc00
ax_pose_terminator
sEnteiPose186:
ax_pose 39, 0x01e3, 0x50fd, 0xcc00
ax_pose 40, 0x81e3, 0x10f5, 0xcc04
ax_pose 41, 0x01db, 0x1105, 0xcc06
ax_pose 42, 0x01db, 0x10fd, 0xcc07
ax_pose 43, 0x41f3, 0x50ed, 0xcc08
ax_pose 44, 0x41fb, 0x10fb, 0xcc0c
ax_pose 45, 0x01fb, 0x10f3, 0xcc0e
ax_pose_terminator
sEnteiPose187:
ax_pose 69, 0x01f4, 0x5100, 0xcc00
ax_pose 70, 0x01ec, 0x1110, 0xcc04
ax_pose 71, 0x01e4, 0x1100, 0xcc05
ax_pose 72, 0x41ec, 0x1100, 0xcc06
ax_pose 73, 0x81e4, 0x50f8, 0xcc08
ax_pose 74, 0x01f4, 0x1110, 0xcc0c
ax_pose 75, 0x01ec, 0x10f0, 0xcc0d
ax_pose 76, 0x81f4, 0x10f0, 0xcc0e
ax_pose_terminator
sEnteiPose188:
ax_pose 9, 0x01e4, 0x90f1, 0xcc00
ax_pose_terminator
sEnteiPose189:
ax_pose 54, 0x81e4, 0x90f3, 0xcc00
ax_pose 55, 0x81e4, 0x5103, 0xcc08
ax_pose 56, 0x01dc, 0x1103, 0xcc0c
ax_pose 57, 0x01dc, 0x10fb, 0xcc0d
ax_pose 58, 0x01fc, 0x110b, 0xcc0e
ax_pose_terminator
sEnteiPose190:
ax_pose 77, 0x01e6, 0x90f1, 0xcc00
ax_pose_terminator
sEnteiPose191:
ax_pose 16, 0x01e3, 0x80f0, 0xcc00
ax_pose_terminator
sEnteiPose192:
ax_pose 60, 0x81e3, 0x80ff, 0xcc00
ax_pose 61, 0x81e3, 0x40f7, 0xcc08
ax_pose 62, 0x01eb, 0x00ef, 0xcc0c
ax_pose 63, 0x01f3, 0x00ef, 0xcc0d
ax_pose 64, 0x01db, 0x00ff, 0xcc0e
ax_pose 65, 0x01db, 0x00f7, 0xcc0f
ax_pose_terminator
sEnteiPose193:
ax_pose 78, 0x01e7, 0x80f0, 0xcc00
ax_pose_terminator
sEnteiPose194:
ax_pose 9, 0x01e4, 0x80f0, 0xcc00
ax_pose_terminator
sEnteiPose195:
ax_pose 54, 0x81e4, 0x80fe, 0xcc00
ax_pose 55, 0x81e4, 0x40f6, 0xcc08
ax_pose 56, 0x01dc, 0x00f6, 0xcc0c
ax_pose 57, 0x01dc, 0x00fe, 0xcc0d
ax_pose 58, 0x01fc, 0x00ee, 0xcc0e
ax_pose_terminator
sEnteiPose196:
ax_pose 77, 0x01e6, 0x80f0, 0xcc00
ax_pose_terminator
sEnteiPose197:
ax_pose 6, 0x01e4, 0x80ef, 0xcc00
ax_pose_terminator
sEnteiPose198:
ax_pose 39, 0x01e3, 0x40f4, 0xcc00
ax_pose 40, 0x81e3, 0x0104, 0xcc04
ax_pose 41, 0x01db, 0x00f4, 0xcc06
ax_pose 42, 0x01db, 0x00fc, 0xcc07
ax_pose 43, 0x41f3, 0x40f4, 0xcc08
ax_pose 44, 0x41fb, 0x00f6, 0xcc0c
ax_pose 45, 0x01fb, 0x0106, 0xcc0e
ax_pose_terminator
sEnteiPose199:
ax_pose 69, 0x01f4, 0x40f1, 0xcc00
ax_pose 70, 0x01ec, 0x00e9, 0xcc04
ax_pose 71, 0x01e4, 0x00f9, 0xcc05
ax_pose 72, 0x41ec, 0x00f1, 0xcc06
ax_pose 73, 0x81e4, 0x4101, 0xcc08
ax_pose 74, 0x01f4, 0x00e9, 0xcc0c
ax_pose 75, 0x01ec, 0x0109, 0xcc0d
ax_pose 76, 0x81f4, 0x0109, 0xcc0e
ax_pose_terminator
sEnteiPose200:
ax_pose 3, 0x01e4, 0x80f0, 0xcc00
ax_pose_terminator
sEnteiPose201:
ax_pose 33, 0x81e4, 0x80f5, 0xcc00
ax_pose 34, 0x81e4, 0x4105, 0xcc08
ax_pose 35, 0x01ec, 0x010d, 0xcc0c
ax_pose 36, 0x01dc, 0x00f5, 0xcc0d
ax_pose 37, 0x01dc, 0x00fd, 0xcc0e
ax_pose_terminator
sEnteiPose202:
ax_pose 68, 0x01e8, 0x80f0, 0xcc00
ax_pose_terminator
sEnteiPose203:
ax_pose 27, 0x81e4, 0x80ff, 0xcc00
ax_pose 28, 0x81e4, 0x40f7, 0xcc08
ax_pose 29, 0x81e4, 0x00ef, 0xcc0c
ax_pose 30, 0x01f4, 0x00ef, 0xcc0e
ax_pose 31, 0x01dc, 0x00fc, 0xcc0f
ax_pose_terminator
sEnteiPose204:
ax_pose 33, 0x81e4, 0x80f5, 0xcc00
ax_pose 34, 0x81e4, 0x4105, 0xcc08
ax_pose 35, 0x01ec, 0x010d, 0xcc0c
ax_pose 36, 0x01dc, 0x00f5, 0xcc0d
ax_pose 37, 0x01dc, 0x00fd, 0xcc0e
ax_pose_terminator
sEnteiPose205:
ax_pose 39, 0x01e3, 0x40f4, 0xcc00
ax_pose 40, 0x81e3, 0x0104, 0xcc04
ax_pose 41, 0x01db, 0x00f4, 0xcc06
ax_pose 42, 0x01db, 0x00fc, 0xcc07
ax_pose 43, 0x41f3, 0x40f4, 0xcc08
ax_pose 44, 0x41fb, 0x00f6, 0xcc0c
ax_pose 45, 0x01fb, 0x0106, 0xcc0e
ax_pose_terminator
sEnteiPose206:
ax_pose 54, 0x81e4, 0x80fe, 0xcc00
ax_pose 55, 0x81e4, 0x40f6, 0xcc08
ax_pose 56, 0x01dc, 0x00f6, 0xcc0c
ax_pose 57, 0x01dc, 0x00fe, 0xcc0d
ax_pose 58, 0x01fc, 0x00ee, 0xcc0e
ax_pose_terminator
sEnteiPose207:
ax_pose 60, 0x81e3, 0x80ff, 0xcc00
ax_pose 61, 0x81e3, 0x40f7, 0xcc08
ax_pose 62, 0x01eb, 0x00ef, 0xcc0c
ax_pose 63, 0x01f3, 0x00ef, 0xcc0d
ax_pose 64, 0x01db, 0x00ff, 0xcc0e
ax_pose 65, 0x01db, 0x00f7, 0xcc0f
ax_pose_terminator
sEnteiPose208:
ax_pose 54, 0x81e4, 0x90f3, 0xcc00
ax_pose 55, 0x81e4, 0x5103, 0xcc08
ax_pose 56, 0x01dc, 0x1103, 0xcc0c
ax_pose 57, 0x01dc, 0x10fb, 0xcc0d
ax_pose 58, 0x01fc, 0x110b, 0xcc0e
ax_pose_terminator
sEnteiPose209:
ax_pose 39, 0x01e3, 0x50fd, 0xcc00
ax_pose 40, 0x81e3, 0x10f5, 0xcc04
ax_pose 41, 0x01db, 0x1105, 0xcc06
ax_pose 42, 0x01db, 0x10fd, 0xcc07
ax_pose 43, 0x41f3, 0x50ed, 0xcc08
ax_pose 44, 0x41fb, 0x10fb, 0xcc0c
ax_pose 45, 0x01fb, 0x10f3, 0xcc0e
ax_pose_terminator
sEnteiPose210:
ax_pose 33, 0x81e4, 0x90fc, 0xcc00
ax_pose 34, 0x81e4, 0x50f4, 0xcc08
ax_pose 35, 0x01ec, 0x10ec, 0xcc0c
ax_pose 36, 0x01dc, 0x1104, 0xcc0d
ax_pose 37, 0x01dc, 0x10fc, 0xcc0e
ax_pose_terminator
sEnteiPose211:
ax_pose 0, 0x01e4, 0x80f0, 0xcc00
ax_pose_terminator
sEnteiPose212:
ax_pose 3, 0x01e4, 0x80f0, 0xcc00
ax_pose_terminator
sEnteiPose213:
ax_pose 6, 0x01e4, 0x80ef, 0xcc00
ax_pose_terminator
sEnteiPose214:
ax_pose 9, 0x01e4, 0x80f0, 0xcc00
ax_pose_terminator
sEnteiPose215:
ax_pose 16, 0x01e3, 0x80f0, 0xcc00
ax_pose_terminator
sEnteiPose216:
ax_pose 9, 0x01e4, 0x90f1, 0xcc00
ax_pose_terminator
sEnteiPose217:
ax_pose 6, 0x01e4, 0x90f2, 0xcc00
ax_pose_terminator
sEnteiPose218:
ax_pose 3, 0x01e4, 0x90f1, 0xcc00
ax_pose_terminator
sEnteiPose219:
ax_pose 0, 0x01e4, 0x80f0, 0xcc00
ax_pose_terminator
sEnteiPose220:
ax_pose 27, 0x81e4, 0x80ff, 0xcc00
ax_pose 28, 0x81e4, 0x40f7, 0xcc08
ax_pose 29, 0x81e4, 0x00ef, 0xcc0c
ax_pose 30, 0x01f4, 0x00ef, 0xcc0e
ax_pose 31, 0x01dc, 0x00fc, 0xcc0f
ax_pose_terminator
sEnteiPose221:
ax_pose 86, 0x01e4, 0x80f0, 0xcc00
ax_pose_terminator
sEnteiPose222:
ax_pose 32, 0x01e4, 0x80f0, 0xcc00
ax_pose_terminator
.align 2
sEnteiAnims_1_1:
ax_anim 10, 0, 0, 0, 0, 0, 0,
ax_anim 12, 0, 1, 0, 0, 0, 0,
ax_anim 10, 0, 0, 0, 0, 0, 0,
ax_anim 12, 0, 2, 0, 0, 0, 0,
ax_anim_terminator
sEnteiAnims_1_2:
ax_anim 10, 0, 3, 0, 0, 0, 0,
ax_anim 12, 0, 4, 0, 0, 0, 0,
ax_anim 10, 0, 3, 0, 0, 0, 0,
ax_anim 12, 0, 5, 0, 0, 0, 0,
ax_anim_terminator
sEnteiAnims_1_3:
ax_anim 10, 0, 6, 0, 0, 0, 0,
ax_anim 12, 0, 7, 0, 0, 0, 0,
ax_anim 10, 0, 6, 0, 0, 0, 0,
ax_anim 12, 0, 8, 0, 0, 0, 0,
ax_anim_terminator
sEnteiAnims_1_4:
ax_anim 10, 0, 9, 0, 0, 0, 0,
ax_anim 12, 0, 10, 0, 0, 0, 0,
ax_anim 10, 0, 9, 0, 0, 0, 0,
ax_anim 12, 0, 11, 0, 0, 0, 0,
ax_anim_terminator
sEnteiAnims_1_5:
ax_anim 10, 0, 12, 0, 0, 0, 0,
ax_anim 12, 0, 13, 0, 0, 0, 0,
ax_anim 10, 0, 12, 0, 0, 0, 0,
ax_anim 12, 0, 14, 0, 0, 0, 0,
ax_anim_terminator
sEnteiAnims_1_6:
ax_anim 10, 0, 15, 0, 0, 0, 0,
ax_anim 12, 0, 16, 0, 0, 0, 0,
ax_anim 10, 0, 15, 0, 0, 0, 0,
ax_anim 12, 0, 17, 0, 0, 0, 0,
ax_anim_terminator
sEnteiAnims_1_7:
ax_anim 10, 0, 18, 0, 0, 0, 0,
ax_anim 12, 0, 19, 0, 0, 0, 0,
ax_anim 10, 0, 18, 0, 0, 0, 0,
ax_anim 12, 0, 20, 0, 0, 0, 0,
ax_anim_terminator
sEnteiAnims_1_8:
ax_anim 10, 0, 21, 0, 0, 0, 0,
ax_anim 12, 0, 22, 0, 0, 0, 0,
ax_anim 10, 0, 21, 0, 0, 0, 0,
ax_anim 12, 0, 23, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sEnteiAnims_2_1:
ax_anim 2, 0, 25, 0, -1, 0, -1,
ax_anim 3, 0, 25, 0, -3, 0, -3,
ax_anim 6, 0, 25, 0, -6, 0, -6,
ax_anim 1, 0, 24, 0, 0, 0, 0,
ax_anim 1, 2, 26, 0, 4, 0, 4,
ax_anim 1, 0, 26, 0, 10, 0, 10,
ax_anim 2, 0, 28, 1, 16, 0, 16,
ax_anim 2, 1, 28, 0, 16, -1, 16,
ax_anim 2, 0, 28, 1, 16, 0, 16,
ax_anim 2, 0, 28, 0, 16, -1, 16,
ax_anim 2, 0, 24, 0, 6, 0, 6,
ax_anim_terminator
sEnteiAnims_2_2:
ax_anim 2, 0, 28, -1, -1, -1, -1,
ax_anim 3, 0, 28, -3, -3, -3, -3,
ax_anim 6, 0, 28, -6, -6, -6, -6,
ax_anim 1, 0, 27, 0, 0, 0, 0,
ax_anim 1, 2, 29, 4, 4, 4, 4,
ax_anim 1, 0, 29, 11, 10, 11, 10,
ax_anim 2, 0, 31, 18, 18, 18, 18,
ax_anim 2, 1, 31, 17, 19, 17, 19,
ax_anim 2, 0, 31, 18, 18, 18, 18,
ax_anim 2, 0, 31, 17, 19, 17, 19,
ax_anim 2, 0, 27, 6, 6, 6, 6,
ax_anim_terminator
sEnteiAnims_2_3:
ax_anim 2, 0, 31, -1, 0, -1, 0,
ax_anim 3, 0, 31, -3, 0, -3, 0,
ax_anim 6, 0, 31, -6, 0, -6, 0,
ax_anim 1, 0, 30, 0, 0, 0, 0,
ax_anim 1, 2, 32, 4, 0, 4, 0,
ax_anim 1, 0, 32, 10, 0, 10, 0,
ax_anim 2, 0, 34, 16, 0, 16, 0,
ax_anim 2, 1, 34, 16, 1, 16, 1,
ax_anim 2, 0, 34, 16, 0, 16, 0,
ax_anim 2, 0, 34, 16, 1, 16, 1,
ax_anim 2, 0, 30, 6, 0, 6, 0,
ax_anim_terminator
sEnteiAnims_2_4:
ax_anim 2, 0, 34, -1, 1, -1, 1,
ax_anim 3, 0, 34, -3, 3, -3, 3,
ax_anim 6, 0, 34, -6, 6, -6, 6,
ax_anim 1, 0, 33, 0, 0, 0, 0,
ax_anim 1, 2, 35, 4, -4, 4, -4,
ax_anim 1, 0, 35, 11, -10, 11, -10,
ax_anim 2, 0, 38, 16, -14, 16, -14,
ax_anim 2, 1, 38, 15, -15, 15, -15,
ax_anim 2, 0, 38, 16, -14, 16, -14,
ax_anim 2, 0, 38, 15, -15, 15, -15,
ax_anim 2, 0, 33, 6, -6, 6, -6,
ax_anim_terminator
sEnteiAnims_2_5:
ax_anim 2, 0, 37, 0, 1, 0, 1,
ax_anim 3, 0, 37, 0, 3, 0, 3,
ax_anim 6, 0, 37, 0, 6, 0, 6,
ax_anim 1, 0, 36, 0, 0, 0, 0,
ax_anim 1, 2, 38, 0, -4, 0, -4,
ax_anim 1, 0, 38, 0, -10, 0, -10,
ax_anim 2, 0, 41, 0, -15, 0, -15,
ax_anim 2, 1, 41, -1, -15, -1, -15,
ax_anim 2, 0, 41, 0, -15, 0, -15,
ax_anim 2, 0, 41, -1, -15, -1, -15,
ax_anim 2, 0, 36, 0, -6, 0, -6,
ax_anim_terminator
sEnteiAnims_2_6:
ax_anim 2, 0, 40, 1, 1, 1, 1,
ax_anim 3, 0, 40, 3, 3, 3, 3,
ax_anim 6, 0, 40, 6, 6, 6, 6,
ax_anim 1, 0, 39, 0, 0, 0, 0,
ax_anim 1, 2, 41, -4, -4, -4, -4,
ax_anim 1, 0, 41, -11, -10, -11, -10,
ax_anim 2, 0, 44, -16, -18, -16, -18,
ax_anim 2, 1, 44, -15, -19, -15, -19,
ax_anim 2, 0, 44, -16, -18, -16, -18,
ax_anim 2, 0, 44, -15, -19, -15, -19,
ax_anim 2, 0, 39, -6, -6, -6, -6,
ax_anim_terminator
sEnteiAnims_2_7:
ax_anim 2, 0, 43, 1, 0, 1, 0,
ax_anim 3, 0, 43, 3, 0, 3, 0,
ax_anim 6, 0, 43, 6, 0, 6, 0,
ax_anim 1, 0, 42, 0, 0, 0, 0,
ax_anim 1, 2, 44, -4, 0, -4, 0,
ax_anim 1, 0, 44, -8, 0, -8, 0,
ax_anim 2, 0, 47, -18, -1, -18, -1,
ax_anim 2, 1, 47, -18, 0, -18, 0,
ax_anim 2, 0, 47, -18, -1, -18, -1,
ax_anim 2, 0, 47, -18, 0, -18, 0,
ax_anim 2, 0, 42, -6, 0, -6, 0,
ax_anim_terminator
sEnteiAnims_2_8:
ax_anim 2, 0, 46, 1, -1, 1, -1,
ax_anim 3, 0, 46, 3, -3, 3, -3,
ax_anim 6, 0, 46, 6, -6, 6, -6,
ax_anim 1, 0, 45, 0, 0, 0, 0,
ax_anim 1, 2, 47, -4, 4, -4, 4,
ax_anim 1, 0, 47, -11, 10, -11, 10,
ax_anim 2, 0, 26, -20, 18, -20, 18,
ax_anim 2, 1, 26, -19, 19, -19, 19,
ax_anim 2, 0, 26, -20, 18, -20, 18,
ax_anim 2, 0, 26, -19, 19, -19, 19,
ax_anim 2, 0, 45, -6, 6, -6, 6,
ax_anim_terminator
.align 2
sEnteiAnims_3_1:
ax_anim 2, 0, 49, 0, -1, 0, -1,
ax_anim 3, 0, 49, 0, -3, 0, -3,
ax_anim 6, 0, 49, 0, -6, 0, -6,
ax_anim 1, 0, 48, 0, 0, 0, 0,
ax_anim 1, 2, 50, 0, 4, 0, 4,
ax_anim 1, 0, 50, 0, 10, 0, 10,
ax_anim 2, 0, 52, 1, 16, 0, 16,
ax_anim 2, 1, 52, 0, 16, -1, 16,
ax_anim 2, 0, 52, 1, 16, 0, 16,
ax_anim 2, 0, 52, 0, 16, -1, 16,
ax_anim 2, 0, 48, 0, 6, 0, 6,
ax_anim_terminator
sEnteiAnims_3_2:
ax_anim 2, 0, 52, -1, -1, -1, -1,
ax_anim 3, 0, 52, -3, -3, -3, -3,
ax_anim 6, 0, 52, -6, -6, -6, -6,
ax_anim 1, 0, 51, 0, 0, 0, 0,
ax_anim 1, 2, 53, 4, 4, 4, 4,
ax_anim 1, 0, 53, 11, 10, 11, 10,
ax_anim 2, 0, 55, 18, 18, 18, 18,
ax_anim 2, 1, 55, 17, 19, 17, 19,
ax_anim 2, 0, 55, 18, 18, 18, 18,
ax_anim 2, 0, 55, 17, 19, 17, 19,
ax_anim 2, 0, 51, 6, 6, 6, 6,
ax_anim_terminator
sEnteiAnims_3_3:
ax_anim 2, 0, 55, -1, 0, -1, 0,
ax_anim 3, 0, 55, -3, 0, -3, 0,
ax_anim 6, 0, 55, -6, 0, -6, 0,
ax_anim 1, 0, 54, 0, 0, 0, 0,
ax_anim 1, 2, 56, 4, 0, 4, 0,
ax_anim 1, 0, 56, 10, 0, 10, 0,
ax_anim 2, 0, 58, 16, 0, 16, 0,
ax_anim 2, 1, 58, 16, 1, 16, 1,
ax_anim 2, 0, 58, 16, 0, 16, 0,
ax_anim 2, 0, 58, 16, 1, 16, 1,
ax_anim 2, 0, 54, 6, 0, 6, 0,
ax_anim_terminator
sEnteiAnims_3_4:
ax_anim 2, 0, 58, -1, 1, -1, 1,
ax_anim 3, 0, 58, -3, 3, -3, 3,
ax_anim 6, 0, 58, -6, 6, -6, 6,
ax_anim 1, 0, 57, 0, 0, 0, 0,
ax_anim 1, 2, 59, 4, -4, 4, -4,
ax_anim 1, 0, 59, 11, -10, 11, -10,
ax_anim 2, 0, 62, 16, -14, 16, -14,
ax_anim 2, 1, 62, 15, -15, 15, -15,
ax_anim 2, 0, 62, 16, -14, 16, -14,
ax_anim 2, 0, 62, 15, -15, 15, -15,
ax_anim 2, 0, 57, 6, -6, 6, -6,
ax_anim_terminator
sEnteiAnims_3_5:
ax_anim 2, 0, 61, 0, 1, 0, 1,
ax_anim 3, 0, 61, 0, 3, 0, 3,
ax_anim 6, 0, 61, 0, 6, 0, 6,
ax_anim 1, 0, 60, 0, 0, 0, 0,
ax_anim 1, 2, 62, 0, -4, 0, -4,
ax_anim 1, 0, 62, 0, -10, 0, -10,
ax_anim 2, 0, 65, 0, -15, 0, -15,
ax_anim 2, 1, 65, -1, -15, -1, -15,
ax_anim 2, 0, 65, 0, -15, 0, -15,
ax_anim 2, 0, 65, -1, -15, -1, -15,
ax_anim 2, 0, 60, 0, -6, 0, -6,
ax_anim_terminator
sEnteiAnims_3_6:
ax_anim 2, 0, 64, 1, 1, 1, 1,
ax_anim 3, 0, 64, 3, 3, 3, 3,
ax_anim 6, 0, 64, 6, 6, 6, 6,
ax_anim 1, 0, 63, 0, 0, 0, 0,
ax_anim 1, 2, 65, -4, -4, -4, -4,
ax_anim 1, 0, 65, -11, -10, -11, -10,
ax_anim 2, 0, 68, -16, -18, -16, -18,
ax_anim 2, 1, 68, -15, -19, -15, -19,
ax_anim 2, 0, 68, -16, -18, -16, -18,
ax_anim 2, 0, 68, -15, -19, -15, -19,
ax_anim 2, 0, 63, -6, -6, -6, -6,
ax_anim_terminator
sEnteiAnims_3_7:
ax_anim 2, 0, 67, 1, 0, 1, 0,
ax_anim 3, 0, 67, 3, 0, 3, 0,
ax_anim 6, 0, 67, 6, 0, 6, 0,
ax_anim 1, 0, 66, 0, 0, 0, 0,
ax_anim 1, 2, 68, -4, 0, -4, 0,
ax_anim 1, 0, 68, -8, 0, -8, 0,
ax_anim 2, 0, 71, -18, -1, -18, -1,
ax_anim 2, 1, 71, -18, 0, -18, 0,
ax_anim 2, 0, 71, -18, -1, -18, -1,
ax_anim 2, 0, 71, -18, 0, -18, 0,
ax_anim 2, 0, 66, -6, 0, -6, 0,
ax_anim_terminator
sEnteiAnims_3_8:
ax_anim 2, 0, 70, 1, -1, 1, -1,
ax_anim 3, 0, 70, 3, -3, 3, -3,
ax_anim 6, 0, 70, 6, -6, 6, -6,
ax_anim 1, 0, 69, 0, 0, 0, 0,
ax_anim 1, 2, 71, -4, 4, -4, 4,
ax_anim 1, 0, 71, -11, 10, -11, 10,
ax_anim 2, 0, 50, -20, 18, -20, 18,
ax_anim 2, 1, 50, -19, 19, -19, 19,
ax_anim 2, 0, 50, -20, 18, -20, 18,
ax_anim 2, 0, 50, -19, 19, -19, 19,
ax_anim 2, 0, 69, -6, 6, -6, 6,
ax_anim_terminator
.align 2
sEnteiAnims_4_1:
ax_anim 2, 0, 72, 0, -2, 0, -2,
ax_anim 2, 0, 73, 0, -3, 0, -3,
ax_anim 6, 0, 73, 0, -4, 0, -4,
ax_anim 1, 0, 74, 0, -2, 0, -2,
ax_anim 2, 2, 74, 0, 2, 0, 2,
ax_anim 2, 0, 74, -1, 2, -1, 2,
ax_anim 2, 0, 74, 0, 2, 0, 2,
ax_anim 2, 0, 74, -1, 2, -1, 2,
ax_anim 2, 1, 74, 0, 2, 0, 2,
ax_anim 2, 0, 74, -1, 2, -1, 2,
ax_anim 2, 0, 74, 0, 2, 0, 2,
ax_anim 2, 0, 74, -1, 2, -1, 2,
ax_anim 4, 0, 72, 0, 1, 0, 1,
ax_anim_terminator
sEnteiAnims_4_2:
ax_anim 2, 0, 75, -2, -2, -2, -2,
ax_anim 2, 0, 76, -3, -3, -3, -3,
ax_anim 6, 0, 76, -4, -4, -4, -4,
ax_anim 1, 0, 77, -2, -2, -2, -2,
ax_anim 2, 2, 77, 2, 2, 2, 2,
ax_anim 2, 0, 77, 1, 3, 1, 3,
ax_anim 2, 0, 77, 2, 2, 2, 2,
ax_anim 2, 0, 77, 1, 3, 1, 3,
ax_anim 2, 1, 77, 2, 2, 2, 2,
ax_anim 2, 0, 77, 1, 3, 1, 3,
ax_anim 2, 0, 77, 2, 2, 2, 2,
ax_anim 2, 0, 77, 1, 3, 1, 3,
ax_anim 4, 0, 75, 1, 1, 1, 1,
ax_anim_terminator
sEnteiAnims_4_3:
ax_anim 2, 0, 78, -2, 0, -2, 0,
ax_anim 2, 0, 79, -3, 0, -3, 0,
ax_anim 6, 0, 79, -4, 0, -4, 0,
ax_anim 1, 0, 80, -2, 0, -2, 0,
ax_anim 2, 2, 80, 2, 0, 2, 0,
ax_anim 2, 0, 80, 2, -1, 2, -1,
ax_anim 2, 0, 80, 2, 0, 2, 0,
ax_anim 2, 0, 80, 2, -1, 2, -1,
ax_anim 2, 1, 80, 2, 0, 2, 0,
ax_anim 2, 0, 80, 2, -1, 2, -1,
ax_anim 2, 0, 80, 2, 0, 2, 0,
ax_anim 2, 0, 80, 2, -1, 2, -1,
ax_anim 4, 0, 78, 1, 0, 1, 0,
ax_anim_terminator
sEnteiAnims_4_4:
ax_anim 2, 0, 81, -2, 2, -2, 2,
ax_anim 2, 0, 82, -3, 3, -3, 3,
ax_anim 6, 0, 82, -4, 4, -4, 4,
ax_anim 1, 0, 83, -2, 2, -2, 2,
ax_anim 2, 2, 83, 2, -2, 2, -2,
ax_anim 2, 0, 83, 1, -3, 1, -3,
ax_anim 2, 0, 83, 2, -2, 2, -2,
ax_anim 2, 0, 83, 1, -3, 1, -3,
ax_anim 2, 1, 83, 2, -2, 2, -2,
ax_anim 2, 0, 83, 1, -3, 1, -3,
ax_anim 2, 0, 83, 2, -2, 2, -2,
ax_anim 2, 0, 83, 1, -3, 1, -3,
ax_anim 4, 0, 81, 1, -1, 1, -1,
ax_anim_terminator
sEnteiAnims_4_5:
ax_anim 2, 0, 84, 0, 2, 0, 2,
ax_anim 2, 0, 85, 0, 3, 0, 3,
ax_anim 6, 0, 85, 0, 4, 0, 4,
ax_anim 1, 0, 86, 0, 2, 0, 2,
ax_anim 2, 2, 86, 0, -3, 0, -2,
ax_anim 2, 0, 86, -1, -3, -1, -2,
ax_anim 2, 0, 86, 0, -3, 0, -2,
ax_anim 2, 0, 86, -1, -3, -1, -2,
ax_anim 2, 1, 86, 0, -3, 0, -2,
ax_anim 2, 0, 86, -1, -3, -1, -2,
ax_anim 2, 0, 86, 0, -3, 0, -2,
ax_anim 2, 0, 86, -1, -3, -1, -2,
ax_anim 4, 0, 84, 0, -1, 0, -1,
ax_anim_terminator
sEnteiAnims_4_6:
ax_anim 2, 0, 87, 2, 2, 2, 2,
ax_anim 2, 0, 88, 3, 3, 3, 3,
ax_anim 6, 0, 88, 4, 4, 4, 4,
ax_anim 1, 0, 89, 2, 2, 2, 2,
ax_anim 2, 2, 89, -2, -2, -2, -2,
ax_anim 2, 0, 89, -1, -3, -1, -3,
ax_anim 2, 0, 89, -2, -2, -2, -2,
ax_anim 2, 0, 89, -1, -3, -1, -3,
ax_anim 2, 1, 89, -2, -2, -2, -2,
ax_anim 2, 0, 89, -1, -3, -1, -3,
ax_anim 2, 0, 89, -2, -2, -2, -2,
ax_anim 2, 0, 89, -1, -3, -1, -3,
ax_anim 4, 0, 87, -1, -1, -1, -1,
ax_anim_terminator
sEnteiAnims_4_7:
ax_anim 2, 0, 90, 2, 0, 2, 0,
ax_anim 2, 0, 91, 3, 0, 3, 0,
ax_anim 6, 0, 91, 4, 0, 4, 0,
ax_anim 1, 0, 92, 2, 0, 2, 0,
ax_anim 2, 2, 92, -2, 0, -2, 0,
ax_anim 2, 0, 92, -2, -1, -2, -1,
ax_anim 2, 0, 92, -2, 0, -2, 0,
ax_anim 2, 0, 92, -2, -1, -2, -1,
ax_anim 2, 1, 92, -2, 0, -2, 0,
ax_anim 2, 0, 92, -2, -1, -2, -1,
ax_anim 2, 0, 92, -2, 0, -2, 0,
ax_anim 2, 0, 92, -2, -1, -2, -1,
ax_anim 4, 0, 90, -1, 0, -1, 0,
ax_anim_terminator
sEnteiAnims_4_8:
ax_anim 2, 0, 93, 2, -2, 2, -2,
ax_anim 2, 0, 94, 3, -3, 3, -3,
ax_anim 6, 0, 94, 4, -4, 4, -4,
ax_anim 1, 0, 95, 2, -2, 2, -2,
ax_anim 2, 2, 95, -2, 2, -2, 2,
ax_anim 2, 0, 95, -1, 3, -1, 3,
ax_anim 2, 0, 95, -2, 2, -2, 2,
ax_anim 2, 0, 95, -1, 3, -1, 3,
ax_anim 2, 1, 95, -2, 2, -2, 2,
ax_anim 2, 0, 95, -1, 3, -1, 3,
ax_anim 2, 0, 95, -2, 2, -2, 2,
ax_anim 2, 0, 95, -1, 3, -1, 3,
ax_anim 4, 0, 93, -1, 1, -1, 1,
ax_anim_terminator
.align 2
sEnteiAnims_5_1:
ax_anim 2, 0, 96, 0, -2, 0, -2,
ax_anim 2, 0, 97, 0, -3, 0, -3,
ax_anim 2, 0, 97, -1, -3, -1, -3,
ax_anim 2, 2, 97, 0, -3, 0, -3,
ax_anim 2, 0, 97, -1, -3, -1, -3,
ax_anim 2, 0, 97, 0, -3, 0, -3,
ax_anim 2, 0, 97, -1, -3, -1, -3,
ax_anim 1, 0, 98, 0, 0, 0, 0,
ax_anim 2, 0, 99, 0, 2, 0, 2,
ax_anim 2, 0, 99, -1, 2, -1, 2,
ax_anim 2, 0, 99, 0, 2, 0, 2,
ax_anim 2, 0, 99, -1, 2, -1, 2,
ax_anim 2, 1, 99, 0, 2, 0, 2,
ax_anim 3, 0, 98, 0, 0, 0, 0,
ax_anim_terminator
sEnteiAnims_5_2:
ax_anim 2, 0, 100, -2, -2, -2, -2,
ax_anim 2, 0, 101, -3, -3, -3, -3,
ax_anim 2, 0, 101, -2, -4, -2, -4,
ax_anim 2, 2, 101, -3, -3, -3, -3,
ax_anim 2, 0, 101, -2, -4, -2, -4,
ax_anim 2, 0, 101, -3, -3, -3, -3,
ax_anim 1, 0, 102, 0, 0, 0, 0,
ax_anim 2, 0, 103, 2, 2, 2, 2,
ax_anim 2, 0, 103, 1, 3, 1, 3,
ax_anim 2, 0, 103, 2, 2, 2, 2,
ax_anim 2, 0, 103, 1, 3, 1, 3,
ax_anim 2, 0, 103, 2, 2, 2, 2,
ax_anim 2, 1, 103, 1, 3, 1, 3,
ax_anim 3, 0, 102, 0, 0, 0, 0,
ax_anim_terminator
sEnteiAnims_5_3:
ax_anim 2, 0, 104, -2, 0, -2, 0,
ax_anim 2, 0, 105, -3, 0, -3, 0,
ax_anim 2, 0, 105, -3, -1, -3, -1,
ax_anim 2, 2, 105, -3, 0, -3, 0,
ax_anim 2, 0, 105, -3, -1, -3, -1,
ax_anim 2, 0, 105, -3, 0, -3, 0,
ax_anim 1, 0, 106, 0, 0, 0, 0,
ax_anim 2, 0, 107, 4, 0, 4, 0,
ax_anim 2, 0, 107, 3, 0, 3, 0,
ax_anim 2, 0, 107, 3, -1, 3, -1,
ax_anim 2, 0, 107, 3, 0, 3, 0,
ax_anim 2, 0, 107, 3, -1, 3, -1,
ax_anim 2, 1, 107, 1, 0, 1, 0,
ax_anim 3, 0, 106, 0, 0, 0, 0,
ax_anim_terminator
sEnteiAnims_5_4:
ax_anim 2, 0, 108, -2, 2, -2, 2,
ax_anim 2, 0, 109, -3, 3, -3, 3,
ax_anim 2, 0, 109, -2, 4, -2, 4,
ax_anim 2, 2, 109, -3, 3, -3, 3,
ax_anim 2, 0, 109, -2, 4, -2, 4,
ax_anim 2, 0, 109, -3, 3, -3, 3,
ax_anim 1, 0, 110, 0, 0, 0, 0,
ax_anim 2, 0, 111, 2, -2, 2, -2,
ax_anim 2, 0, 111, 1, -3, 1, -3,
ax_anim 2, 0, 111, 2, -2, 2, -2,
ax_anim 2, 0, 111, 1, -3, 1, -3,
ax_anim 2, 0, 111, 2, -2, 2, -2,
ax_anim 2, 1, 111, 1, -3, 1, -3,
ax_anim 3, 0, 110, 0, 0, 0, 0,
ax_anim_terminator
sEnteiAnims_5_5:
ax_anim 2, 0, 112, 0, 2, 0, 2,
ax_anim 2, 0, 113, 0, 3, 0, 3,
ax_anim 2, 0, 113, -1, 3, -1, 3,
ax_anim 2, 2, 113, 0, 3, 0, 3,
ax_anim 2, 0, 113, -1, 3, -1, 3,
ax_anim 2, 0, 113, 0, 3, 0, 3,
ax_anim 1, 0, 114, 0, 0, 0, 0,
ax_anim 2, 0, 115, 0, -3, 0, -3,
ax_anim 2, 0, 115, -1, -3, -1, -3,
ax_anim 2, 0, 115, 0, -3, 0, -3,
ax_anim 2, 0, 115, -1, -3, -1, -3,
ax_anim 2, 0, 115, 0, -3, 0, -3,
ax_anim 2, 1, 115, -1, -3, -1, -3,
ax_anim 3, 0, 114, 0, 0, 0, 0,
ax_anim_terminator
sEnteiAnims_5_6:
ax_anim 2, 0, 116, 2, 2, 2, 2,
ax_anim 2, 0, 117, 3, 3, 3, 3,
ax_anim 2, 0, 117, 2, 4, 2, 4,
ax_anim 2, 2, 117, 3, 3, 3, 3,
ax_anim 2, 0, 117, 2, 4, 2, 4,
ax_anim 2, 0, 117, 3, 3, 3, 3,
ax_anim 1, 0, 118, 0, 0, 0, 0,
ax_anim 2, 0, 119, -2, -2, -2, -2,
ax_anim 2, 0, 119, -1, -3, -1, -3,
ax_anim 2, 0, 119, -2, -2, -2, -2,
ax_anim 2, 0, 119, -1, -3, -1, -3,
ax_anim 2, 0, 119, -2, -2, -2, -2,
ax_anim 2, 1, 119, -1, -3, -1, -3,
ax_anim 3, 0, 118, 0, 0, 0, 0,
ax_anim_terminator
sEnteiAnims_5_7:
ax_anim 2, 0, 120, 2, 0, 2, 0,
ax_anim 2, 0, 121, 3, 0, 3, 0,
ax_anim 2, 0, 121, 3, -1, 3, -1,
ax_anim 2, 2, 121, 3, 0, 3, 0,
ax_anim 2, 0, 121, 3, -1, 3, -1,
ax_anim 2, 0, 121, 3, 0, 3, 0,
ax_anim 1, 0, 122, 0, 0, 0, 0,
ax_anim 2, 0, 123, -4, 0, -4, 0,
ax_anim 2, 0, 123, -3, 0, -3, 0,
ax_anim 2, 0, 123, -3, -1, -3, -1,
ax_anim 2, 0, 123, -3, 0, -3, 0,
ax_anim 2, 0, 123, -3, -1, -3, -1,
ax_anim 2, 1, 123, -1, 0, -1, 0,
ax_anim 3, 0, 122, 0, 0, 0, 0,
ax_anim_terminator
sEnteiAnims_5_8:
ax_anim 2, 0, 124, 2, -2, 2, -2,
ax_anim 2, 0, 125, 3, -3, 3, -3,
ax_anim 2, 0, 125, 2, -4, 2, -4,
ax_anim 2, 2, 125, 3, -3, 3, -3,
ax_anim 2, 0, 125, 2, -4, 2, -4,
ax_anim 2, 0, 125, 3, -3, 3, -3,
ax_anim 1, 0, 126, 0, 0, 0, 0,
ax_anim 2, 0, 127, -2, 2, -2, 2,
ax_anim 2, 0, 127, -1, 3, -1, 3,
ax_anim 2, 0, 127, -2, 2, -2, 2,
ax_anim 2, 0, 127, -1, 3, -1, 3,
ax_anim 2, 0, 127, -2, 2, -2, 2,
ax_anim 2, 1, 127, -1, 3, -1, 3,
ax_anim 3, 0, 126, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sEnteiAnims_6_1:
ax_anim 30, 0, 128, 0, 0, 0, 0,
ax_anim 35, 0, 129, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sEnteiAnims_7_1:
ax_anim 2, 0, 130, 0, -4, 0, -4,
ax_anim 8, 0, 130, 0, -5, 0, -5,
ax_anim_terminator
sEnteiAnims_7_2:
ax_anim 2, 0, 131, -4, -4, -4, -4,
ax_anim 8, 0, 131, -5, -5, -5, -5,
ax_anim_terminator
sEnteiAnims_7_3:
ax_anim 2, 0, 132, -4, 0, -4, 0,
ax_anim 8, 0, 132, -5, 0, -5, 0,
ax_anim_terminator
sEnteiAnims_7_4:
ax_anim 2, 0, 133, -4, 4, -4, 4,
ax_anim 8, 0, 133, -5, 5, -5, 5,
ax_anim_terminator
sEnteiAnims_7_5:
ax_anim 2, 0, 134, 0, 4, 0, 4,
ax_anim 8, 0, 134, 0, 5, 0, 5,
ax_anim_terminator
sEnteiAnims_7_6:
ax_anim 2, 0, 135, 4, 4, 4, 4,
ax_anim 8, 0, 135, 5, 5, 5, 5,
ax_anim_terminator
sEnteiAnims_7_7:
ax_anim 2, 0, 136, 4, 0, 4, 0,
ax_anim 8, 0, 136, 5, 0, 5, 0,
ax_anim_terminator
sEnteiAnims_7_8:
ax_anim 2, 0, 137, 4, -4, 4, -4,
ax_anim 8, 0, 137, 5, -5, 5, -5,
ax_anim_terminator
.align 2
sEnteiAnims_8_1:
ax_anim 60, 0, 138, 0, 0, 0, 0,
ax_anim 10, 0, 140, 0, 0, 0, 0,
ax_anim 2, 0, 140, -1, 0, -1, 0,
ax_anim 2, 0, 140, 0, 0, 0, 0,
ax_anim 2, 0, 140, -1, 0, -1, 0,
ax_anim 2, 0, 140, 0, 0, 0, 0,
ax_anim 2, 0, 140, -1, 0, -1, 0,
ax_anim 2, 0, 140, 0, 0, 0, 0,
ax_anim 2, 0, 140, -1, 0, -1, 0,
ax_anim 2, 0, 140, 0, 0, 0, 0,
ax_anim 2, 0, 140, -1, 0, -1, 0,
ax_anim 2, 0, 140, 0, 0, 0, 0,
ax_anim 2, 0, 140, -1, 0, -1, 0,
ax_anim 10, 0, 140, 0, 0, 0, 0,
ax_anim_terminator
sEnteiAnims_8_2:
ax_anim 60, 0, 141, 0, 0, 0, 0,
ax_anim 10, 0, 143, 0, 0, 0, 0,
ax_anim 2, 0, 143, -1, 0, -1, 0,
ax_anim 2, 0, 143, 0, 0, 0, 0,
ax_anim 2, 0, 143, -1, 0, -1, 0,
ax_anim 2, 0, 143, 0, 0, 0, 0,
ax_anim 2, 0, 143, -1, 0, -1, 0,
ax_anim 2, 0, 143, 0, 0, 0, 0,
ax_anim 2, 0, 143, -1, 0, -1, 0,
ax_anim 2, 0, 143, 0, 0, 0, 0,
ax_anim 2, 0, 143, -1, 0, -1, 0,
ax_anim 2, 0, 143, 0, 0, 0, 0,
ax_anim 2, 0, 143, -1, 0, -1, 0,
ax_anim 10, 0, 143, 0, 0, 0, 0,
ax_anim_terminator
sEnteiAnims_8_3:
ax_anim 60, 0, 144, 0, 0, 0, 0,
ax_anim 10, 0, 146, 0, 0, 0, 0,
ax_anim 2, 0, 146, -1, 0, -1, 0,
ax_anim 2, 0, 146, 0, 0, 0, 0,
ax_anim 2, 0, 146, -1, 0, -1, 0,
ax_anim 2, 0, 146, 0, 0, 0, 0,
ax_anim 2, 0, 146, -1, 0, -1, 0,
ax_anim 2, 0, 146, 0, 0, 0, 0,
ax_anim 2, 0, 146, -1, 0, -1, 0,
ax_anim 2, 0, 146, 0, 0, 0, 0,
ax_anim 2, 0, 146, -1, 0, -1, 0,
ax_anim 2, 0, 146, 0, 0, 0, 0,
ax_anim 2, 0, 146, -1, 0, -1, 0,
ax_anim 10, 0, 146, 0, 0, 0, 0,
ax_anim_terminator
sEnteiAnims_8_4:
ax_anim 60, 0, 147, 0, 0, 0, 0,
ax_anim 10, 0, 149, 0, 0, 0, 0,
ax_anim 2, 0, 149, -1, 0, -1, 0,
ax_anim 2, 0, 149, 0, 0, 0, 0,
ax_anim 2, 0, 149, -1, 0, -1, 0,
ax_anim 2, 0, 149, 0, 0, 0, 0,
ax_anim 2, 0, 149, -1, 0, -1, 0,
ax_anim 2, 0, 149, 0, 0, 0, 0,
ax_anim 2, 0, 149, -1, 0, -1, 0,
ax_anim 2, 0, 149, 0, 0, 0, 0,
ax_anim 2, 0, 149, -1, 0, -1, 0,
ax_anim 2, 0, 149, 0, 0, 0, 0,
ax_anim 2, 0, 149, -1, 0, -1, 0,
ax_anim 10, 0, 149, 0, 0, 0, 0,
ax_anim_terminator
sEnteiAnims_8_5:
ax_anim 60, 0, 150, 0, 0, 0, 0,
ax_anim 10, 0, 152, 0, 0, 0, 0,
ax_anim 2, 0, 152, -1, 0, -1, 0,
ax_anim 2, 0, 152, 0, 0, 0, 0,
ax_anim 2, 0, 152, -1, 0, -1, 0,
ax_anim 2, 0, 152, 0, 0, 0, 0,
ax_anim 2, 0, 152, -1, 0, -1, 0,
ax_anim 2, 0, 152, 0, 0, 0, 0,
ax_anim 2, 0, 152, -1, 0, -1, 0,
ax_anim 2, 0, 152, 0, 0, 0, 0,
ax_anim 2, 0, 152, -1, 0, -1, 0,
ax_anim 2, 0, 152, 0, 0, 0, 0,
ax_anim 2, 0, 152, -1, 0, -1, 0,
ax_anim 10, 0, 152, 0, 0, 0, 0,
ax_anim_terminator
sEnteiAnims_8_6:
ax_anim 60, 0, 153, 0, 0, 0, 0,
ax_anim 10, 0, 155, 0, 0, 0, 0,
ax_anim 2, 0, 155, -1, 0, -1, 0,
ax_anim 2, 0, 155, 0, 0, 0, 0,
ax_anim 2, 0, 155, -1, 0, -1, 0,
ax_anim 2, 0, 155, 0, 0, 0, 0,
ax_anim 2, 0, 155, -1, 0, -1, 0,
ax_anim 2, 0, 155, 0, 0, 0, 0,
ax_anim 2, 0, 155, -1, 0, -1, 0,
ax_anim 2, 0, 155, 0, 0, 0, 0,
ax_anim 2, 0, 155, -1, 0, -1, 0,
ax_anim 2, 0, 155, 0, 0, 0, 0,
ax_anim 2, 0, 155, -1, 0, -1, 0,
ax_anim 10, 0, 155, 0, 0, 0, 0,
ax_anim_terminator
sEnteiAnims_8_7:
ax_anim 60, 0, 156, 0, 0, 0, 0,
ax_anim 10, 0, 158, 0, 0, 0, 0,
ax_anim 2, 0, 158, -1, 0, -1, 0,
ax_anim 2, 0, 158, 0, 0, 0, 0,
ax_anim 2, 0, 158, -1, 0, -1, 0,
ax_anim 2, 0, 158, 0, 0, 0, 0,
ax_anim 2, 0, 158, -1, 0, -1, 0,
ax_anim 2, 0, 158, 0, 0, 0, 0,
ax_anim 2, 0, 158, -1, 0, -1, 0,
ax_anim 2, 0, 158, 0, 0, 0, 0,
ax_anim 2, 0, 158, -1, 0, -1, 0,
ax_anim 2, 0, 158, 0, 0, 0, 0,
ax_anim 2, 0, 158, -1, 0, -1, 0,
ax_anim 10, 0, 158, 0, 0, 0, 0,
ax_anim_terminator
sEnteiAnims_8_8:
ax_anim 60, 0, 159, 0, 0, 0, 0,
ax_anim 10, 0, 161, 0, 0, 0, 0,
ax_anim 2, 0, 161, -1, 0, -1, 0,
ax_anim 2, 0, 161, 0, 0, 0, 0,
ax_anim 2, 0, 161, -1, 0, -1, 0,
ax_anim 2, 0, 161, 0, 0, 0, 0,
ax_anim 2, 0, 161, -1, 0, -1, 0,
ax_anim 2, 0, 161, 0, 0, 0, 0,
ax_anim 2, 0, 161, -1, 0, -1, 0,
ax_anim 2, 0, 161, 0, 0, 0, 0,
ax_anim 2, 0, 161, -1, 0, -1, 0,
ax_anim 2, 0, 161, 0, 0, 0, 0,
ax_anim 2, 0, 161, -1, 0, -1, 0,
ax_anim 10, 0, 161, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sEnteiAnims_9_1:
ax_anim 2, 0, 162, 0, 0, 0, 0,
ax_anim 1, 0, 163, 6, 4, 6, 4,
ax_anim 2, 0, 164, 10, 9, 10, 9,
ax_anim 2, 0, 165, 7, 19, 7, 19,
ax_anim 3, 0, 166, 0, 22, 0, 22,
ax_anim 2, 3, 167, -7, 19, -7, 19,
ax_anim 2, 0, 168, -10, 9, -10, 9,
ax_anim 1, 0, 169, -6, 4, -6, 4,
ax_anim 1, 0, 162, 0, 0, 0, 0,
ax_anim_terminator
sEnteiAnims_9_2:
ax_anim 2, 0, 169, 0, 0, 0, 0,
ax_anim 1, 0, 162, 6, 0, 6, 0,
ax_anim 2, 0, 163, 17, 3, 17, 3,
ax_anim 2, 0, 164, 24, 9, 24, 9,
ax_anim 3, 0, 165, 21, 18, 21, 18,
ax_anim 2, 3, 166, 11, 21, 11, 21,
ax_anim 2, 0, 167, 2, 12, 2, 12,
ax_anim 1, 0, 168, 0, 7, 0, 7,
ax_anim 1, 0, 169, 0, 0, 0, 0,
ax_anim_terminator
sEnteiAnims_9_3:
ax_anim 2, 0, 168, 0, 0, 0, 0,
ax_anim 1, 0, 169, 3, -4, 3, -4,
ax_anim 2, 0, 162, 11, -6, 11, -6,
ax_anim 2, 0, 163, 17, -4, 17, -4,
ax_anim 3, 0, 164, 20, 1, 20, 1,
ax_anim 2, 3, 165, 17, 5, 17, 5,
ax_anim 2, 0, 166, 12, 7, 12, 7,
ax_anim 1, 0, 167, 4, 5, 4, 5,
ax_anim 1, 0, 168, 0, 0, 0, 0,
ax_anim_terminator
sEnteiAnims_9_4:
ax_anim 2, 0, 167, 0, 0, 0, 0,
ax_anim 1, 0, 168, -3, -6, -3, -6,
ax_anim 2, 0, 169, 4, -16, 4, -16,
ax_anim 2, 0, 162, 10, -20, 10, -20,
ax_anim 3, 0, 163, 16, -20, 16, -20,
ax_anim 2, 3, 164, 20, -12, 20, -12,
ax_anim 2, 0, 165, 17, -4, 17, -4,
ax_anim 1, 0, 166, 7, -1, 7, -1,
ax_anim 1, 0, 167, 0, 0, 0, 0,
ax_anim_terminator
sEnteiAnims_9_5:
ax_anim 2, 0, 166, 0, 0, 0, 0,
ax_anim 1, 0, 167, -6, -4, -6, -4,
ax_anim 2, 0, 168, -10, -10, -10, -10,
ax_anim 2, 0, 169, -8, -16, -8, -16,
ax_anim 3, 0, 162, 0, -17, 0, -17,
ax_anim 2, 3, 163, 8, -16, 8, -16,
ax_anim 2, 0, 164, 10, -10, 10, -10,
ax_anim 1, 0, 165, 6, -4, 6, -4,
ax_anim 1, 0, 166, 0, 0, 0, 0,
ax_anim_terminator
sEnteiAnims_9_6:
ax_anim 2, 0, 165, 0, 0, 0, 0,
ax_anim 1, 0, 164, 3, -6, 3, -6,
ax_anim 2, 0, 163, -4, -16, -4, -16,
ax_anim 2, 0, 162, -10, -20, -10, -20,
ax_anim 3, 0, 169, -16, -20, -16, -20,
ax_anim 2, 3, 168, -20, -12, -20, -12,
ax_anim 2, 0, 167, -17, -4, -17, -4,
ax_anim 1, 0, 166, -7, -1, -7, -1,
ax_anim 1, 0, 165, 0, 0, 0, 0,
ax_anim_terminator
sEnteiAnims_9_7:
ax_anim 2, 0, 164, 0, 0, 0, 0,
ax_anim 1, 0, 163, -3, -4, -3, -4,
ax_anim 2, 0, 162, -11, -6, -11, -6,
ax_anim 2, 0, 169, -17, -4, -17, -4,
ax_anim 3, 0, 168, -20, 1, -20, 1,
ax_anim 2, 3, 167, -17, 5, -17, 5,
ax_anim 2, 0, 166, -12, 7, -12, 7,
ax_anim 1, 0, 165, -4, 5, -4, 5,
ax_anim 1, 0, 164, 0, 0, 0, 0,
ax_anim_terminator
sEnteiAnims_9_8:
ax_anim 2, 0, 163, 0, 0, 0, 0,
ax_anim 1, 0, 162, -6, 0, -6, 0,
ax_anim 2, 0, 169, -17, 3, -17, 3,
ax_anim 2, 0, 168, -24, 9, -24, 9,
ax_anim 3, 0, 167, -21, 18, -21, 18,
ax_anim 2, 3, 166, -11, 21, -11, 21,
ax_anim 2, 0, 165, -2, 12, -2, 12,
ax_anim 1, 0, 164, 0, 7, 0, 7,
ax_anim 1, 0, 163, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sEnteiAnims_10_1:
ax_anim 2, 0, 170, 0, 0, 0, 0,
ax_anim 2, 0, 170, 6, 0, 6, 0,
ax_anim 2, 0, 170, -6, 0, -6, 0,
ax_anim 2, 0, 170, 10, 0, 10, 0,
ax_anim 2, 0, 170, -10, 0, -10, 0,
ax_anim 2, 0, 170, 12, 0, 12, 0,
ax_anim 3, 0, 170, -12, 0, -12, 0,
ax_anim 3, 0, 170, 13, 0, 13, 0,
ax_anim 3, 0, 170, -13, 0, -13, 0,
ax_anim 2, 0, 170, 12, 0, 12, 0,
ax_anim 3, 0, 170, -12, 0, -12, 0,
ax_anim 2, 0, 170, 10, 0, 10, 0,
ax_anim 2, 0, 170, -10, 0, -10, 0,
ax_anim 2, 0, 170, 6, 0, 6, 0,
ax_anim 2, 0, 170, -6, 0, -6, 0,
ax_anim 2, 0, 170, 0, 0, 0, 0,
ax_anim_terminator
sEnteiAnims_10_2:
ax_anim 2, 0, 171, 0, 0, 0, 0,
ax_anim 2, 0, 171, 6, -6, 6, -6,
ax_anim 2, 0, 171, -6, 6, -6, 6,
ax_anim 2, 0, 171, 10, -10, 10, -10,
ax_anim 2, 0, 171, -10, 10, -10, 10,
ax_anim 2, 0, 171, 12, -12, 12, -12,
ax_anim 3, 0, 171, -12, 12, -12, 12,
ax_anim 3, 0, 171, 13, -13, 13, -13,
ax_anim 3, 0, 171, -13, 13, -13, 13,
ax_anim 2, 0, 171, 12, -12, 12, -12,
ax_anim 3, 0, 171, -12, 12, -12, 12,
ax_anim 2, 0, 171, 10, -10, 10, -10,
ax_anim 2, 0, 171, -10, 10, -10, 10,
ax_anim 2, 0, 171, 6, -6, 6, -6,
ax_anim 2, 0, 171, -6, 6, -6, 6,
ax_anim 2, 0, 171, 0, 0, 0, 0,
ax_anim_terminator
sEnteiAnims_10_3:
ax_anim 2, 0, 172, 0, 0, 0, 0,
ax_anim 2, 0, 172, 0, -6, 0, -6,
ax_anim 2, 0, 172, 0, 6, 0, 6,
ax_anim 2, 0, 172, 0, -10, 0, -10,
ax_anim 2, 0, 172, 0, 10, 0, 10,
ax_anim 2, 0, 172, 0, -12, 0, -12,
ax_anim 3, 0, 172, 0, 12, 0, 12,
ax_anim 3, 0, 172, 0, -13, 0, -13,
ax_anim 3, 0, 172, 0, 13, 0, 13,
ax_anim 2, 0, 172, 0, -12, 0, -12,
ax_anim 3, 0, 172, 0, 12, 0, 12,
ax_anim 2, 0, 172, 0, -10, 0, -10,
ax_anim 2, 0, 172, 0, 10, 0, 10,
ax_anim 2, 0, 172, 0, -6, 0, -6,
ax_anim 2, 0, 172, 0, 6, 0, 6,
ax_anim 2, 0, 172, 0, 0, 0, 0,
ax_anim_terminator
sEnteiAnims_10_4:
ax_anim 2, 0, 173, 0, 0, 0, 0,
ax_anim 2, 0, 173, -6, -6, -6, -6,
ax_anim 2, 0, 173, 6, 6, 6, 6,
ax_anim 2, 0, 173, -10, -10, -10, -10,
ax_anim 2, 0, 173, 10, 10, 10, 10,
ax_anim 2, 0, 173, -12, -12, -12, -12,
ax_anim 3, 0, 173, 12, 12, 12, 12,
ax_anim 3, 0, 173, -13, -13, -13, -13,
ax_anim 3, 0, 173, 13, 13, 13, 13,
ax_anim 2, 0, 173, -12, -12, -12, -12,
ax_anim 3, 0, 173, 12, 12, 12, 12,
ax_anim 2, 0, 173, -10, -10, -10, -10,
ax_anim 2, 0, 173, 10, 10, 10, 10,
ax_anim 2, 0, 173, -6, -6, -6, -6,
ax_anim 2, 0, 173, 6, 6, 6, 6,
ax_anim 2, 0, 173, 0, 0, 0, 0,
ax_anim_terminator
sEnteiAnims_10_5:
ax_anim 2, 0, 174, 0, 0, 0, 0,
ax_anim 2, 0, 174, 6, 0, 6, 0,
ax_anim 2, 0, 174, -6, 0, -6, 0,
ax_anim 2, 0, 174, 10, 0, 10, 0,
ax_anim 2, 0, 174, -10, 0, -10, 0,
ax_anim 2, 0, 174, 12, 0, 12, 0,
ax_anim 3, 0, 174, -12, 0, -12, 0,
ax_anim 3, 0, 174, 13, 0, 13, 0,
ax_anim 3, 0, 174, -13, 0, -13, 0,
ax_anim 2, 0, 174, 12, 0, 12, 0,
ax_anim 3, 0, 174, -12, 0, -12, 0,
ax_anim 2, 0, 174, 10, 0, 10, 0,
ax_anim 2, 0, 174, -10, 0, -10, 0,
ax_anim 2, 0, 174, 6, 0, 6, 0,
ax_anim 2, 0, 174, -6, 0, -6, 0,
ax_anim 2, 0, 174, 0, 0, 0, 0,
ax_anim_terminator
sEnteiAnims_10_6:
ax_anim 2, 0, 175, 0, 0, 0, 0,
ax_anim 2, 0, 175, 6, -6, 6, -6,
ax_anim 2, 0, 175, -6, 6, -6, 6,
ax_anim 2, 0, 175, 10, -10, 10, -10,
ax_anim 2, 0, 175, -10, 10, -10, 10,
ax_anim 2, 0, 175, 12, -12, 12, -12,
ax_anim 3, 0, 175, -12, 12, -12, 12,
ax_anim 3, 0, 175, 13, -13, 13, -13,
ax_anim 3, 0, 175, -13, 13, -13, 13,
ax_anim 2, 0, 175, 12, -12, 12, -12,
ax_anim 3, 0, 175, -12, 12, -12, 12,
ax_anim 2, 0, 175, 10, -10, 10, -10,
ax_anim 2, 0, 175, -10, 10, -10, 10,
ax_anim 2, 0, 175, 6, -6, 6, -6,
ax_anim 2, 0, 175, -6, 6, -6, 6,
ax_anim 2, 0, 175, 0, 0, 0, 0,
ax_anim_terminator
sEnteiAnims_10_7:
ax_anim 2, 0, 176, 0, 0, 0, 0,
ax_anim 2, 0, 176, 0, -6, 0, -6,
ax_anim 2, 0, 176, 0, 6, 0, 6,
ax_anim 2, 0, 176, 0, -10, 0, -10,
ax_anim 2, 0, 176, 0, 10, 0, 10,
ax_anim 2, 0, 176, 0, -12, 0, -12,
ax_anim 3, 0, 176, 0, 12, 0, 12,
ax_anim 3, 0, 176, 0, -13, 0, -13,
ax_anim 3, 0, 176, 0, 13, 0, 13,
ax_anim 2, 0, 176, 0, -12, 0, -12,
ax_anim 3, 0, 176, 0, 12, 0, 12,
ax_anim 2, 0, 176, 0, -10, 0, -10,
ax_anim 2, 0, 176, 0, 10, 0, 10,
ax_anim 2, 0, 176, 0, -6, 0, -6,
ax_anim 2, 0, 176, 0, 6, 0, 6,
ax_anim 2, 0, 176, 0, 0, 0, 0,
ax_anim_terminator
sEnteiAnims_10_8:
ax_anim 2, 0, 177, 0, 0, 0, 0,
ax_anim 2, 0, 177, -6, -6, -6, -6,
ax_anim 2, 0, 177, 6, 6, 6, 6,
ax_anim 2, 0, 177, -10, -10, -10, -10,
ax_anim 2, 0, 177, 10, 10, 10, 10,
ax_anim 2, 0, 177, -12, -12, -12, -12,
ax_anim 3, 0, 177, 12, 12, 12, 12,
ax_anim 3, 0, 177, -13, -13, -13, -13,
ax_anim 3, 0, 177, 13, 13, 13, 13,
ax_anim 2, 0, 177, -12, -12, -12, -12,
ax_anim 3, 0, 177, 12, 12, 12, 12,
ax_anim 2, 0, 177, -10, -10, -10, -10,
ax_anim 2, 0, 177, 10, 10, 10, 10,
ax_anim 2, 0, 177, -6, -6, -6, -6,
ax_anim 2, 0, 177, 6, 6, 6, 6,
ax_anim 2, 0, 177, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sEnteiAnims_11_1:
ax_anim 2, 0, 178, 0, 0, 0, 0,
ax_anim 1, 0, 179, 0, -10, 0, 0,
ax_anim 2, 0, 179, 0, -16, 0, 0,
ax_anim 3, 0, 179, 0, -20, 0, 0,
ax_anim 4, 0, 179, 0, -21, 0, 0,
ax_anim 4, 0, 178, 0, -23, 0, 0,
ax_anim 3, 0, 178, 0, -19, 0, 0,
ax_anim 2, 0, 178, 0, -15, 0, 0,
ax_anim 1, 0, 178, 0, -9, 0, 0,
ax_anim 2, 2, 180, 0, 0, 0, 0,
ax_anim_terminator
sEnteiAnims_11_2:
ax_anim 2, 0, 181, 0, 0, 0, 0,
ax_anim 1, 0, 182, 0, -10, 0, 0,
ax_anim 2, 0, 182, 0, -16, 0, 0,
ax_anim 3, 0, 182, 0, -20, 0, 0,
ax_anim 4, 0, 182, 0, -21, 0, 0,
ax_anim 4, 0, 181, 0, -23, 0, 0,
ax_anim 3, 0, 181, 0, -22, 0, 0,
ax_anim 2, 0, 181, 0, -18, 0, 0,
ax_anim 1, 0, 181, 0, -12, 0, 0,
ax_anim 2, 2, 183, 0, 0, 0, 0,
ax_anim_terminator
sEnteiAnims_11_3:
ax_anim 2, 0, 184, 0, 0, 0, 0,
ax_anim 1, 0, 185, 0, -10, 0, 0,
ax_anim 2, 0, 185, 0, -16, 0, 0,
ax_anim 3, 0, 185, 0, -20, 0, 0,
ax_anim 4, 0, 185, 0, -21, 0, 0,
ax_anim 4, 0, 184, 0, -23, 0, 0,
ax_anim 3, 0, 184, 0, -22, 0, 0,
ax_anim 2, 0, 184, 0, -18, 0, 0,
ax_anim 1, 0, 184, 0, -12, 0, 0,
ax_anim 2, 2, 186, 0, 0, 0, 0,
ax_anim_terminator
sEnteiAnims_11_4:
ax_anim 2, 0, 187, 0, 0, 0, 0,
ax_anim 1, 0, 188, 0, -10, 0, 0,
ax_anim 2, 0, 188, 0, -16, 0, 0,
ax_anim 3, 0, 188, 0, -20, 0, 0,
ax_anim 4, 0, 188, 0, -21, 0, 0,
ax_anim 4, 0, 187, 0, -22, 0, 0,
ax_anim 3, 0, 187, 0, -21, 0, 0,
ax_anim 2, 0, 187, 0, -17, 0, 0,
ax_anim 1, 0, 187, 0, -11, 0, 0,
ax_anim 2, 2, 189, 0, 0, 0, 0,
ax_anim_terminator
sEnteiAnims_11_5:
ax_anim 2, 0, 190, 0, 0, 0, 0,
ax_anim 1, 0, 191, 0, -10, 0, 0,
ax_anim 2, 0, 191, 0, -16, 0, 0,
ax_anim 3, 0, 191, 0, -20, 0, 0,
ax_anim 4, 0, 191, 0, -21, 0, 0,
ax_anim 4, 0, 190, 0, -23, 0, 0,
ax_anim 3, 0, 190, 0, -22, 0, 0,
ax_anim 2, 0, 190, 0, -18, 0, 0,
ax_anim 1, 0, 190, 0, -12, 0, 0,
ax_anim 2, 2, 192, 0, 0, 0, 0,
ax_anim_terminator
sEnteiAnims_11_6:
ax_anim 2, 0, 193, 0, 0, 0, 0,
ax_anim 1, 0, 194, 0, -10, 0, 0,
ax_anim 2, 0, 194, 0, -16, 0, 0,
ax_anim 3, 0, 194, 0, -20, 0, 0,
ax_anim 4, 0, 194, 0, -21, 0, 0,
ax_anim 4, 0, 193, 0, -22, 0, 0,
ax_anim 3, 0, 193, 0, -21, 0, 0,
ax_anim 2, 0, 193, 0, -17, 0, 0,
ax_anim 1, 0, 193, 0, -11, 0, 0,
ax_anim 2, 2, 195, 0, 0, 0, 0,
ax_anim_terminator
sEnteiAnims_11_7:
ax_anim 2, 0, 196, 0, 0, 0, 0,
ax_anim 1, 0, 197, 0, -10, 0, 0,
ax_anim 2, 0, 197, 0, -16, 0, 0,
ax_anim 3, 0, 197, 0, -20, 0, 0,
ax_anim 4, 0, 197, 0, -21, 0, 0,
ax_anim 4, 0, 196, 0, -23, 0, 0,
ax_anim 3, 0, 196, 0, -22, 0, 0,
ax_anim 2, 0, 196, 0, -18, 0, 0,
ax_anim 1, 0, 196, 0, -12, 0, 0,
ax_anim 2, 2, 198, 0, 0, 0, 0,
ax_anim_terminator
sEnteiAnims_11_8:
ax_anim 2, 0, 199, 0, 0, 0, 0,
ax_anim 1, 0, 200, 0, -10, 0, 0,
ax_anim 2, 0, 200, 0, -16, 0, 0,
ax_anim 3, 0, 200, 0, -20, 0, 0,
ax_anim 4, 0, 200, 0, -21, 0, 0,
ax_anim 4, 0, 199, 0, -23, 0, 0,
ax_anim 3, 0, 199, 0, -22, 0, 0,
ax_anim 2, 0, 199, 0, -18, 0, 0,
ax_anim 1, 0, 199, 0, -12, 0, 0,
ax_anim 2, 2, 201, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sEnteiAnims_12_1:
ax_anim 2, 0, 202, 1, 0, 1, 0,
ax_anim 2, 0, 202, 0, 0, 0, 0,
ax_anim 2, 0, 202, 1, 0, 1, 0,
ax_anim 2, 0, 202, 0, 0, 0, 0,
ax_anim 2, 0, 202, 1, 0, 1, 0,
ax_anim 2, 2, 202, 0, 0, 0, 0,
ax_anim 2, 0, 202, 1, 0, 1, 0,
ax_anim 2, 0, 202, 0, 0, 0, 0,
ax_anim 2, 0, 202, 1, 0, 1, 0,
ax_anim 2, 1, 202, 0, 0, 0, 0,
ax_anim_terminator
sEnteiAnims_12_2:
ax_anim 2, 0, 209, 1, -1, 1, 0,
ax_anim 2, 0, 209, 0, 0, 0, 0,
ax_anim 2, 0, 209, 1, -1, 1, 0,
ax_anim 2, 0, 209, 0, 0, 0, 0,
ax_anim 2, 0, 209, 1, -1, 1, 0,
ax_anim 2, 2, 209, 0, 0, 0, 0,
ax_anim 2, 0, 209, 1, -1, 1, 0,
ax_anim 2, 0, 209, 0, 0, 0, 0,
ax_anim 2, 0, 209, 1, -1, 1, 0,
ax_anim 2, 1, 209, 0, 0, 0, 0,
ax_anim_terminator
sEnteiAnims_12_3:
ax_anim 2, 0, 208, 0, -1, 0, -1,
ax_anim 2, 0, 208, 0, 0, 0, 0,
ax_anim 2, 0, 208, 0, -1, 0, -1,
ax_anim 2, 0, 208, 0, 0, 0, 0,
ax_anim 2, 0, 208, 0, -1, 0, -1,
ax_anim 2, 2, 208, 0, 0, 0, 0,
ax_anim 2, 0, 208, 0, -1, 0, -1,
ax_anim 2, 0, 208, 0, 0, 0, 0,
ax_anim 2, 0, 208, 0, -1, 0, -1,
ax_anim 2, 1, 208, 0, 0, 0, 0,
ax_anim_terminator
sEnteiAnims_12_4:
ax_anim 2, 0, 207, -1, -1, -1, -1,
ax_anim 2, 0, 207, 0, 0, 0, 0,
ax_anim 2, 0, 207, -1, -1, -1, -1,
ax_anim 2, 0, 207, 0, 0, 0, 0,
ax_anim 2, 0, 207, -1, -1, -1, -1,
ax_anim 2, 2, 207, 0, 0, 0, 0,
ax_anim 2, 0, 207, -1, -1, -1, -1,
ax_anim 2, 0, 207, 0, 0, 0, 0,
ax_anim 2, 0, 207, -1, -1, -1, -1,
ax_anim 2, 1, 207, 0, 0, 0, 0,
ax_anim_terminator
sEnteiAnims_12_5:
ax_anim 2, 0, 206, 1, 0, 1, 0,
ax_anim 2, 0, 206, 0, 0, 0, 0,
ax_anim 2, 0, 206, 1, 0, 1, 0,
ax_anim 2, 0, 206, 0, 0, 0, 0,
ax_anim 2, 0, 206, 1, 0, 1, 0,
ax_anim 2, 2, 206, 0, 0, 0, 0,
ax_anim 2, 0, 206, 1, 0, 1, 0,
ax_anim 2, 0, 206, 0, 0, 0, 0,
ax_anim 2, 0, 206, 1, 0, 1, 0,
ax_anim 2, 1, 206, 0, 0, 0, 0,
ax_anim_terminator
sEnteiAnims_12_6:
ax_anim 2, 0, 205, 1, -1, 1, -1,
ax_anim 2, 0, 205, 0, 0, 0, 0,
ax_anim 2, 0, 205, 1, -1, 1, -1,
ax_anim 2, 0, 205, 0, 0, 0, 0,
ax_anim 2, 0, 205, 1, -1, 1, -1,
ax_anim 2, 2, 205, 0, 0, 0, 0,
ax_anim 2, 0, 205, 1, -1, 1, -1,
ax_anim 2, 0, 205, 0, 0, 0, 0,
ax_anim 2, 0, 205, 1, -1, 1, -1,
ax_anim 2, 1, 205, 0, 0, 0, 0,
ax_anim_terminator
sEnteiAnims_12_7:
ax_anim 2, 0, 204, 0, -1, 0, -1,
ax_anim 2, 0, 204, 0, 0, 0, 0,
ax_anim 2, 0, 204, 0, -1, 0, -1,
ax_anim 2, 0, 204, 0, 0, 0, 0,
ax_anim 2, 0, 204, 0, -1, 0, -1,
ax_anim 2, 2, 204, 0, 0, 0, 0,
ax_anim 2, 0, 204, 0, -1, 0, -1,
ax_anim 2, 0, 204, 0, 0, 0, 0,
ax_anim 2, 0, 204, 0, -1, 0, -1,
ax_anim 2, 1, 204, 0, 0, 0, 0,
ax_anim_terminator
sEnteiAnims_12_8:
ax_anim 2, 0, 203, -1, -1, -1, -1,
ax_anim 2, 0, 203, 0, 0, 0, 0,
ax_anim 2, 0, 203, -1, -1, -1, -1,
ax_anim 2, 0, 203, 0, 0, 0, 0,
ax_anim 2, 0, 203, -1, -1, -1, -1,
ax_anim 2, 2, 203, 0, 0, 0, 0,
ax_anim 2, 0, 203, -1, -1, -1, -1,
ax_anim 2, 0, 203, 0, 0, 0, 0,
ax_anim 2, 0, 203, -1, -1, -1, -1,
ax_anim 2, 1, 203, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sEnteiAnims_13_1:
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 2, 210, 0, 0, 0, 0,
ax_anim_terminator
sEnteiAnims_13_2:
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 2, 217, 0, 0, 0, 0,
ax_anim_terminator
sEnteiAnims_13_3:
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 2, 216, 0, 0, 0, 0,
ax_anim_terminator
sEnteiAnims_13_4:
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 2, 2, 215, 0, 0, 0, 0,
ax_anim_terminator
sEnteiAnims_13_5:
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 2, 2, 214, 0, 0, 0, 0,
ax_anim_terminator
sEnteiAnims_13_6:
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 2, 2, 213, 0, 0, 0, 0,
ax_anim_terminator
sEnteiAnims_13_7:
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 2, 2, 212, 0, 0, 0, 0,
ax_anim_terminator
sEnteiAnims_13_8:
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 2, 2, 211, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sEnteiAnims_14_1:
ax_anim 4, 0, 218, 0, 0, 0, 0,
ax_anim 4, 0, 220, 0, 0, 0, 0,
ax_anim 14, 0, 219, 0, 0, 0, 0,
ax_anim 4, 0, 220, 0, 0, 0, 0,
ax_anim 1, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 221, 0, 2, 0, 2,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 221, 0, 2, 0, 2,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 1, 0, 221, 0, 1, 0, 1,
ax_anim 1, 0, 221, 0, 0, 0, 0,
ax_anim 1, 0, 221, 0, 1, 0, 1,
ax_anim 1, 0, 221, 0, 0, 0, 0,
ax_anim 1, 0, 221, 0, 1, 0, 1,
ax_anim 14, 0, 221, 0, 0, 0, 0,
ax_anim 4, 0, 218, 0, 0, 0, 0,
ax_anim_terminator
sEnteiAnims_14_2:
ax_anim 4, 0, 218, 0, 0, 0, 0,
ax_anim 4, 0, 220, 0, 0, 0, 0,
ax_anim 14, 0, 219, 0, 0, 0, 0,
ax_anim 4, 0, 220, 0, 0, 0, 0,
ax_anim 1, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 221, 0, 2, 0, 2,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 221, 0, 2, 0, 2,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 1, 0, 221, 0, 1, 0, 1,
ax_anim 1, 0, 221, 0, 0, 0, 0,
ax_anim 1, 0, 221, 0, 1, 0, 1,
ax_anim 1, 0, 221, 0, 0, 0, 0,
ax_anim 1, 0, 221, 0, 1, 0, 1,
ax_anim 14, 0, 221, 0, 0, 0, 0,
ax_anim 4, 0, 218, 0, 0, 0, 0,
ax_anim_terminator
sEnteiAnims_14_3:
ax_anim 4, 0, 218, 0, 0, 0, 0,
ax_anim 4, 0, 220, 0, 0, 0, 0,
ax_anim 14, 0, 219, 0, 0, 0, 0,
ax_anim 4, 0, 220, 0, 0, 0, 0,
ax_anim 1, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 221, 0, 2, 0, 2,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 221, 0, 2, 0, 2,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 1, 0, 221, 0, 1, 0, 1,
ax_anim 1, 0, 221, 0, 0, 0, 0,
ax_anim 1, 0, 221, 0, 1, 0, 1,
ax_anim 1, 0, 221, 0, 0, 0, 0,
ax_anim 1, 0, 221, 0, 1, 0, 1,
ax_anim 14, 0, 221, 0, 0, 0, 0,
ax_anim 4, 0, 218, 0, 0, 0, 0,
ax_anim_terminator
sEnteiAnims_14_4:
ax_anim 4, 0, 218, 0, 0, 0, 0,
ax_anim 4, 0, 220, 0, 0, 0, 0,
ax_anim 14, 0, 219, 0, 0, 0, 0,
ax_anim 4, 0, 220, 0, 0, 0, 0,
ax_anim 1, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 221, 0, 2, 0, 2,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 221, 0, 2, 0, 2,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 1, 0, 221, 0, 1, 0, 1,
ax_anim 1, 0, 221, 0, 0, 0, 0,
ax_anim 1, 0, 221, 0, 1, 0, 1,
ax_anim 1, 0, 221, 0, 0, 0, 0,
ax_anim 1, 0, 221, 0, 1, 0, 1,
ax_anim 14, 0, 221, 0, 0, 0, 0,
ax_anim 4, 0, 218, 0, 0, 0, 0,
ax_anim_terminator
sEnteiAnims_14_5:
ax_anim 4, 0, 218, 0, 0, 0, 0,
ax_anim 4, 0, 220, 0, 0, 0, 0,
ax_anim 14, 0, 219, 0, 0, 0, 0,
ax_anim 4, 0, 220, 0, 0, 0, 0,
ax_anim 1, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 221, 0, 2, 0, 2,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 221, 0, 2, 0, 2,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 1, 0, 221, 0, 1, 0, 1,
ax_anim 1, 0, 221, 0, 0, 0, 0,
ax_anim 1, 0, 221, 0, 1, 0, 1,
ax_anim 1, 0, 221, 0, 0, 0, 0,
ax_anim 1, 0, 221, 0, 1, 0, 1,
ax_anim 14, 0, 221, 0, 0, 0, 0,
ax_anim 4, 0, 218, 0, 0, 0, 0,
ax_anim_terminator
sEnteiAnims_14_6:
ax_anim 4, 0, 218, 0, 0, 0, 0,
ax_anim 4, 0, 220, 0, 0, 0, 0,
ax_anim 14, 0, 219, 0, 0, 0, 0,
ax_anim 4, 0, 220, 0, 0, 0, 0,
ax_anim 1, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 221, 0, 2, 0, 2,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 221, 0, 2, 0, 2,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 1, 0, 221, 0, 1, 0, 1,
ax_anim 1, 0, 221, 0, 0, 0, 0,
ax_anim 1, 0, 221, 0, 1, 0, 1,
ax_anim 1, 0, 221, 0, 0, 0, 0,
ax_anim 1, 0, 221, 0, 1, 0, 1,
ax_anim 14, 0, 221, 0, 0, 0, 0,
ax_anim 4, 0, 218, 0, 0, 0, 0,
ax_anim_terminator
sEnteiAnims_14_7:
ax_anim 4, 0, 218, 0, 0, 0, 0,
ax_anim 4, 0, 220, 0, 0, 0, 0,
ax_anim 14, 0, 219, 0, 0, 0, 0,
ax_anim 4, 0, 220, 0, 0, 0, 0,
ax_anim 1, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 221, 0, 2, 0, 2,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 221, 0, 2, 0, 2,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 1, 0, 221, 0, 1, 0, 1,
ax_anim 1, 0, 221, 0, 0, 0, 0,
ax_anim 1, 0, 221, 0, 1, 0, 1,
ax_anim 1, 0, 221, 0, 0, 0, 0,
ax_anim 1, 0, 221, 0, 1, 0, 1,
ax_anim 14, 0, 221, 0, 0, 0, 0,
ax_anim 4, 0, 218, 0, 0, 0, 0,
ax_anim_terminator
sEnteiAnims_14_8:
ax_anim 4, 0, 218, 0, 0, 0, 0,
ax_anim 4, 0, 220, 0, 0, 0, 0,
ax_anim 14, 0, 219, 0, 0, 0, 0,
ax_anim 4, 0, 220, 0, 0, 0, 0,
ax_anim 1, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 221, 0, 2, 0, 2,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 221, 0, 2, 0, 2,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 1, 0, 221, 0, 1, 0, 1,
ax_anim 1, 0, 221, 0, 0, 0, 0,
ax_anim 1, 0, 221, 0, 1, 0, 1,
ax_anim 1, 0, 221, 0, 0, 0, 0,
ax_anim 1, 0, 221, 0, 1, 0, 1,
ax_anim 14, 0, 221, 0, 0, 0, 0,
ax_anim 4, 0, 218, 0, 0, 0, 0,
ax_anim_terminator
sEnteiGfx1:
.incbin "baserom.gba", 0xFEBC30, 0x200
sEnteiSprites1:
ax_sprite sEnteiGfx1, 0x200
ax_sprite_terminator
sEnteiGfx2:
.incbin "baserom.gba", 0xFEBE40, 0x200
sEnteiSprites2:
ax_sprite sEnteiGfx2, 0x200
ax_sprite_terminator
sEnteiGfx3:
.incbin "baserom.gba", 0xFEC050, 0x200
sEnteiSprites3:
ax_sprite sEnteiGfx3, 0x200
ax_sprite_terminator
sEnteiGfx4:
.incbin "baserom.gba", 0xFEC260, 0x200
sEnteiSprites4:
ax_sprite sEnteiGfx4, 0x200
ax_sprite_terminator
sEnteiGfx5:
.incbin "baserom.gba", 0xFEC470, 0x200
sEnteiSprites5:
ax_sprite sEnteiGfx5, 0x200
ax_sprite_terminator
sEnteiGfx6:
.incbin "baserom.gba", 0xFEC680, 0x200
sEnteiSprites6:
ax_sprite sEnteiGfx6, 0x200
ax_sprite_terminator
sEnteiGfx7:
.incbin "baserom.gba", 0xFEC890, 0x200
sEnteiSprites7:
ax_sprite sEnteiGfx7, 0x200
ax_sprite_terminator
sEnteiGfx8:
.incbin "baserom.gba", 0xFECAA0, 0x200
sEnteiSprites8:
ax_sprite sEnteiGfx8, 0x200
ax_sprite_terminator
sEnteiGfx9:
.incbin "baserom.gba", 0xFECCB0, 0x200
sEnteiSprites9:
ax_sprite sEnteiGfx9, 0x200
ax_sprite_terminator
sEnteiGfx10:
.incbin "baserom.gba", 0xFECEC0, 0x200
sEnteiSprites10:
ax_sprite sEnteiGfx10, 0x200
ax_sprite_terminator
sEnteiGfx11:
.incbin "baserom.gba", 0xFED0D0, 0x200
sEnteiSprites11:
ax_sprite sEnteiGfx11, 0x200
ax_sprite_terminator
sEnteiGfx12:
.incbin "baserom.gba", 0xFED2E0, 0x100
sEnteiSprites12:
ax_sprite sEnteiGfx12, 0x100
ax_sprite_terminator
sEnteiGfx13:
.incbin "baserom.gba", 0xFED3F0, 0x80
sEnteiSprites13:
ax_sprite sEnteiGfx13, 0x80
ax_sprite_terminator
sEnteiGfx14:
.incbin "baserom.gba", 0xFED480, 0x40
sEnteiSprites14:
ax_sprite sEnteiGfx14, 0x40
ax_sprite_terminator
sEnteiGfx15:
.incbin "baserom.gba", 0xFED4D0, 0x20
sEnteiSprites15:
ax_sprite sEnteiGfx15, 0x20
ax_sprite_terminator
sEnteiGfx16:
.incbin "baserom.gba", 0xFED500, 0x20
sEnteiSprites16:
ax_sprite sEnteiGfx16, 0x20
ax_sprite_terminator
sEnteiGfx17:
.incbin "baserom.gba", 0xFED530, 0x200
sEnteiSprites17:
ax_sprite sEnteiGfx17, 0x200
ax_sprite_terminator
sEnteiGfx18:
.incbin "baserom.gba", 0xFED740, 0x100
sEnteiSprites18:
ax_sprite sEnteiGfx18, 0x100
ax_sprite_terminator
sEnteiGfx19:
.incbin "baserom.gba", 0xFED850, 0x80
sEnteiSprites19:
ax_sprite sEnteiGfx19, 0x80
ax_sprite_terminator
sEnteiGfx20:
.incbin "baserom.gba", 0xFED8E0, 0x20
sEnteiSprites20:
ax_sprite sEnteiGfx20, 0x20
ax_sprite_terminator
sEnteiGfx21:
.incbin "baserom.gba", 0xFED910, 0x20
sEnteiSprites21:
ax_sprite sEnteiGfx21, 0x20
ax_sprite_terminator
sEnteiGfx22:
.incbin "baserom.gba", 0xFED940, 0x40
sEnteiSprites22:
ax_sprite sEnteiGfx22, 0x40
ax_sprite_terminator
sEnteiGfx23:
.incbin "baserom.gba", 0xFED990, 0x100
sEnteiSprites23:
ax_sprite sEnteiGfx23, 0x100
ax_sprite_terminator
sEnteiGfx24:
.incbin "baserom.gba", 0xFEDAA0, 0x80
sEnteiSprites24:
ax_sprite sEnteiGfx24, 0x80
ax_sprite_terminator
sEnteiGfx25:
.incbin "baserom.gba", 0xFEDB30, 0x40
sEnteiSprites25:
ax_sprite sEnteiGfx25, 0x40
ax_sprite_terminator
sEnteiGfx26:
.incbin "baserom.gba", 0xFEDB80, 0x20
sEnteiSprites26:
ax_sprite sEnteiGfx26, 0x20
ax_sprite_terminator
sEnteiGfx27:
.incbin "baserom.gba", 0xFEDBB0, 0x20
sEnteiSprites27:
ax_sprite sEnteiGfx27, 0x20
ax_sprite_terminator
sEnteiGfx28:
.incbin "baserom.gba", 0xFEDBE0, 0x100
sEnteiSprites28:
ax_sprite sEnteiGfx28, 0x100
ax_sprite_terminator
sEnteiGfx29:
.incbin "baserom.gba", 0xFEDCF0, 0x80
sEnteiSprites29:
ax_sprite sEnteiGfx29, 0x80
ax_sprite_terminator
sEnteiGfx30:
.incbin "baserom.gba", 0xFEDD80, 0x40
sEnteiSprites30:
ax_sprite sEnteiGfx30, 0x40
ax_sprite_terminator
sEnteiGfx31:
.incbin "baserom.gba", 0xFEDDD0, 0x20
sEnteiSprites31:
ax_sprite sEnteiGfx31, 0x20
ax_sprite_terminator
sEnteiGfx32:
.incbin "baserom.gba", 0xFEDE00, 0x20
sEnteiSprites32:
ax_sprite sEnteiGfx32, 0x20
ax_sprite_terminator
sEnteiGfx33:
.incbin "baserom.gba", 0xFEDE30, 0x40
sEnteiGfx33_1:
.incbin "baserom.gba", 0xFEDE70, 0x180
sEnteiSprites33:
ax_sprite 0, 0x20
ax_sprite sEnteiGfx33, 0x40
ax_sprite 0, 0x20
ax_sprite sEnteiGfx33_1, 0x180
ax_sprite_terminator
sEnteiGfx34:
.incbin "baserom.gba", 0xFEE018, 0x100
sEnteiSprites34:
ax_sprite sEnteiGfx34, 0x100
ax_sprite_terminator
sEnteiGfx35:
.incbin "baserom.gba", 0xFEE128, 0x80
sEnteiSprites35:
ax_sprite sEnteiGfx35, 0x80
ax_sprite_terminator
sEnteiGfx36:
.incbin "baserom.gba", 0xFEE1B8, 0x20
sEnteiSprites36:
ax_sprite sEnteiGfx36, 0x20
ax_sprite_terminator
sEnteiGfx37:
.incbin "baserom.gba", 0xFEE1E8, 0x20
sEnteiSprites37:
ax_sprite sEnteiGfx37, 0x20
ax_sprite_terminator
sEnteiGfx38:
.incbin "baserom.gba", 0xFEE218, 0x20
sEnteiSprites38:
ax_sprite sEnteiGfx38, 0x20
ax_sprite_terminator
sEnteiGfx39:
.incbin "baserom.gba", 0xFEE248, 0x60
sEnteiGfx39_1:
.incbin "baserom.gba", 0xFEE2A8, 0x180
sEnteiSprites39:
ax_sprite sEnteiGfx39, 0x60
ax_sprite 0, 0x20
ax_sprite sEnteiGfx39_1, 0x180
ax_sprite_terminator
sEnteiGfx40:
.incbin "baserom.gba", 0xFEE448, 0x80
sEnteiSprites40:
ax_sprite sEnteiGfx40, 0x80
ax_sprite_terminator
sEnteiGfx41:
.incbin "baserom.gba", 0xFEE4D8, 0x40
sEnteiSprites41:
ax_sprite sEnteiGfx41, 0x40
ax_sprite_terminator
sEnteiGfx42:
.incbin "baserom.gba", 0xFEE528, 0x20
sEnteiSprites42:
ax_sprite sEnteiGfx42, 0x20
ax_sprite_terminator
sEnteiGfx43:
.incbin "baserom.gba", 0xFEE558, 0x20
sEnteiSprites43:
ax_sprite sEnteiGfx43, 0x20
ax_sprite_terminator
sEnteiGfx44:
.incbin "baserom.gba", 0xFEE588, 0x80
sEnteiSprites44:
ax_sprite sEnteiGfx44, 0x80
ax_sprite_terminator
sEnteiGfx45:
.incbin "baserom.gba", 0xFEE618, 0x40
sEnteiSprites45:
ax_sprite sEnteiGfx45, 0x40
ax_sprite_terminator
sEnteiGfx46:
.incbin "baserom.gba", 0xFEE668, 0x20
sEnteiSprites46:
ax_sprite sEnteiGfx46, 0x20
ax_sprite_terminator
sEnteiGfx47:
.incbin "baserom.gba", 0xFEE698, 0x80
sEnteiSprites47:
ax_sprite sEnteiGfx47, 0x80
ax_sprite_terminator
sEnteiGfx48:
.incbin "baserom.gba", 0xFEE728, 0x80
sEnteiSprites48:
ax_sprite sEnteiGfx48, 0x80
ax_sprite_terminator
sEnteiGfx49:
.incbin "baserom.gba", 0xFEE7B8, 0x20
sEnteiSprites49:
ax_sprite sEnteiGfx49, 0x20
ax_sprite_terminator
sEnteiGfx50:
.incbin "baserom.gba", 0xFEE7E8, 0x20
sEnteiSprites50:
ax_sprite sEnteiGfx50, 0x20
ax_sprite_terminator
sEnteiGfx51:
.incbin "baserom.gba", 0xFEE818, 0x40
sEnteiSprites51:
ax_sprite sEnteiGfx51, 0x40
ax_sprite_terminator
sEnteiGfx52:
.incbin "baserom.gba", 0xFEE868, 0x20
sEnteiSprites52:
ax_sprite sEnteiGfx52, 0x20
ax_sprite_terminator
sEnteiGfx53:
.incbin "baserom.gba", 0xFEE898, 0x40
sEnteiSprites53:
ax_sprite sEnteiGfx53, 0x40
ax_sprite_terminator
sEnteiGfx54:
.incbin "baserom.gba", 0xFEE8E8, 0x20
sEnteiSprites54:
ax_sprite sEnteiGfx54, 0x20
ax_sprite_terminator
sEnteiGfx55:
.incbin "baserom.gba", 0xFEE918, 0x100
sEnteiSprites55:
ax_sprite sEnteiGfx55, 0x100
ax_sprite_terminator
sEnteiGfx56:
.incbin "baserom.gba", 0xFEEA28, 0x80
sEnteiSprites56:
ax_sprite sEnteiGfx56, 0x80
ax_sprite_terminator
sEnteiGfx57:
.incbin "baserom.gba", 0xFEEAB8, 0x20
sEnteiSprites57:
ax_sprite sEnteiGfx57, 0x20
ax_sprite_terminator
sEnteiGfx58:
.incbin "baserom.gba", 0xFEEAE8, 0x20
sEnteiSprites58:
ax_sprite sEnteiGfx58, 0x20
ax_sprite_terminator
sEnteiGfx59:
.incbin "baserom.gba", 0xFEEB18, 0x20
sEnteiSprites59:
ax_sprite sEnteiGfx59, 0x20
ax_sprite_terminator
sEnteiGfx60:
.incbin "baserom.gba", 0xFEEB48, 0x200
sEnteiSprites60:
ax_sprite sEnteiGfx60, 0x200
ax_sprite_terminator
sEnteiGfx61:
.incbin "baserom.gba", 0xFEED58, 0x100
sEnteiSprites61:
ax_sprite sEnteiGfx61, 0x100
ax_sprite_terminator
sEnteiGfx62:
.incbin "baserom.gba", 0xFEEE68, 0x80
sEnteiSprites62:
ax_sprite sEnteiGfx62, 0x80
ax_sprite_terminator
sEnteiGfx63:
.incbin "baserom.gba", 0xFEEEF8, 0x20
sEnteiSprites63:
ax_sprite sEnteiGfx63, 0x20
ax_sprite_terminator
sEnteiGfx64:
.incbin "baserom.gba", 0xFEEF28, 0x20
sEnteiSprites64:
ax_sprite sEnteiGfx64, 0x20
ax_sprite_terminator
sEnteiGfx65:
.incbin "baserom.gba", 0xFEEF58, 0x20
sEnteiSprites65:
ax_sprite sEnteiGfx65, 0x20
ax_sprite_terminator
sEnteiGfx66:
.incbin "baserom.gba", 0xFEEF88, 0x20
sEnteiSprites66:
ax_sprite sEnteiGfx66, 0x20
ax_sprite_terminator
sEnteiGfx67:
.incbin "baserom.gba", 0xFEEFB8, 0x100
sEnteiGfx67_1:
.incbin "baserom.gba", 0xFEF0B8, 0xE0
sEnteiSprites67:
ax_sprite sEnteiGfx67, 0x100
ax_sprite 0, 0x20
ax_sprite sEnteiGfx67_1, 0xe0
ax_sprite_terminator
sEnteiGfx68:
.incbin "baserom.gba", 0xFEF1B8, 0x200
sEnteiSprites68:
ax_sprite sEnteiGfx68, 0x200
ax_sprite_terminator
sEnteiGfx69:
.incbin "baserom.gba", 0xFEF3C8, 0x1E0
sEnteiSprites69:
ax_sprite sEnteiGfx69, 0x1e0
ax_sprite 0, 0x20
ax_sprite_terminator
sEnteiGfx70:
.incbin "baserom.gba", 0xFEF5C0, 0x80
sEnteiSprites70:
ax_sprite sEnteiGfx70, 0x80
ax_sprite_terminator
sEnteiGfx71:
.incbin "baserom.gba", 0xFEF650, 0x20
sEnteiSprites71:
ax_sprite sEnteiGfx71, 0x20
ax_sprite_terminator
sEnteiGfx72:
.incbin "baserom.gba", 0xFEF680, 0x20
sEnteiSprites72:
ax_sprite sEnteiGfx72, 0x20
ax_sprite_terminator
sEnteiGfx73:
.incbin "baserom.gba", 0xFEF6B0, 0x40
sEnteiSprites73:
ax_sprite sEnteiGfx73, 0x40
ax_sprite_terminator
sEnteiGfx74:
.incbin "baserom.gba", 0xFEF700, 0x80
sEnteiSprites74:
ax_sprite sEnteiGfx74, 0x80
ax_sprite_terminator
sEnteiGfx75:
.incbin "baserom.gba", 0xFEF790, 0x20
sEnteiSprites75:
ax_sprite sEnteiGfx75, 0x20
ax_sprite_terminator
sEnteiGfx76:
.incbin "baserom.gba", 0xFEF7C0, 0x20
sEnteiSprites76:
ax_sprite sEnteiGfx76, 0x20
ax_sprite_terminator
sEnteiGfx77:
.incbin "baserom.gba", 0xFEF7F0, 0x40
sEnteiSprites77:
ax_sprite sEnteiGfx77, 0x40
ax_sprite_terminator
sEnteiGfx78:
.incbin "baserom.gba", 0xFEF840, 0x180
sEnteiGfx78_1:
.incbin "baserom.gba", 0xFEF9C0, 0x40
sEnteiSprites78:
ax_sprite sEnteiGfx78, 0x180
ax_sprite 0, 0x40
ax_sprite sEnteiGfx78_1, 0x40
ax_sprite_terminator
sEnteiGfx79:
.incbin "baserom.gba", 0xFEFA20, 0x40
sEnteiGfx79_1:
.incbin "baserom.gba", 0xFEFA60, 0x180
sEnteiSprites79:
ax_sprite 0, 0x20
ax_sprite sEnteiGfx79, 0x40
ax_sprite 0, 0x20
ax_sprite sEnteiGfx79_1, 0x180
ax_sprite_terminator
sEnteiGfx80:
.incbin "baserom.gba", 0xFEFC08, 0x200
sEnteiSprites80:
ax_sprite sEnteiGfx80, 0x200
ax_sprite_terminator
sEnteiGfx81:
.incbin "baserom.gba", 0xFEFE18, 0x200
sEnteiSprites81:
ax_sprite sEnteiGfx81, 0x200
ax_sprite_terminator
sEnteiGfx82:
.incbin "baserom.gba", 0xFF0028, 0x200
sEnteiSprites82:
ax_sprite sEnteiGfx82, 0x200
ax_sprite_terminator
sEnteiGfx83:
.incbin "baserom.gba", 0xFF0238, 0x200
sEnteiSprites83:
ax_sprite sEnteiGfx83, 0x200
ax_sprite_terminator
sEnteiGfx84:
.incbin "baserom.gba", 0xFF0448, 0x200
sEnteiSprites84:
ax_sprite sEnteiGfx84, 0x200
ax_sprite_terminator
sEnteiGfx85:
.incbin "baserom.gba", 0xFF0658, 0x200
sEnteiSprites85:
ax_sprite sEnteiGfx85, 0x200
ax_sprite_terminator
sEnteiGfx86:
.incbin "baserom.gba", 0xFF0868, 0x200
sEnteiSprites86:
ax_sprite sEnteiGfx86, 0x200
ax_sprite_terminator
sEnteiGfx87:
.incbin "baserom.gba", 0xFF0A78, 0x200
sEnteiSprites87:
ax_sprite sEnteiGfx87, 0x200
ax_sprite_terminator
sAxPosesEntei:
.4byte sEnteiPose1
.4byte sEnteiPose2
.4byte sEnteiPose3
.4byte sEnteiPose4
.4byte sEnteiPose5
.4byte sEnteiPose6
.4byte sEnteiPose7
.4byte sEnteiPose8
.4byte sEnteiPose9
.4byte sEnteiPose10
.4byte sEnteiPose11
.4byte sEnteiPose12
.4byte sEnteiPose13
.4byte sEnteiPose14
.4byte sEnteiPose15
.4byte sEnteiPose16
.4byte sEnteiPose17
.4byte sEnteiPose18
.4byte sEnteiPose19
.4byte sEnteiPose20
.4byte sEnteiPose21
.4byte sEnteiPose22
.4byte sEnteiPose23
.4byte sEnteiPose24
.4byte sEnteiPose25
.4byte sEnteiPose26
.4byte sEnteiPose27
.4byte sEnteiPose28
.4byte sEnteiPose29
.4byte sEnteiPose30
.4byte sEnteiPose31
.4byte sEnteiPose32
.4byte sEnteiPose33
.4byte sEnteiPose34
.4byte sEnteiPose35
.4byte sEnteiPose36
.4byte sEnteiPose37
.4byte sEnteiPose38
.4byte sEnteiPose39
.4byte sEnteiPose40
.4byte sEnteiPose41
.4byte sEnteiPose42
.4byte sEnteiPose43
.4byte sEnteiPose44
.4byte sEnteiPose45
.4byte sEnteiPose46
.4byte sEnteiPose47
.4byte sEnteiPose48
.4byte sEnteiPose49
.4byte sEnteiPose50
.4byte sEnteiPose51
.4byte sEnteiPose52
.4byte sEnteiPose53
.4byte sEnteiPose54
.4byte sEnteiPose55
.4byte sEnteiPose56
.4byte sEnteiPose57
.4byte sEnteiPose58
.4byte sEnteiPose59
.4byte sEnteiPose60
.4byte sEnteiPose61
.4byte sEnteiPose62
.4byte sEnteiPose63
.4byte sEnteiPose64
.4byte sEnteiPose65
.4byte sEnteiPose66
.4byte sEnteiPose67
.4byte sEnteiPose68
.4byte sEnteiPose69
.4byte sEnteiPose70
.4byte sEnteiPose71
.4byte sEnteiPose72
.4byte sEnteiPose73
.4byte sEnteiPose74
.4byte sEnteiPose75
.4byte sEnteiPose76
.4byte sEnteiPose77
.4byte sEnteiPose78
.4byte sEnteiPose79
.4byte sEnteiPose80
.4byte sEnteiPose81
.4byte sEnteiPose82
.4byte sEnteiPose83
.4byte sEnteiPose84
.4byte sEnteiPose85
.4byte sEnteiPose86
.4byte sEnteiPose87
.4byte sEnteiPose88
.4byte sEnteiPose89
.4byte sEnteiPose90
.4byte sEnteiPose91
.4byte sEnteiPose92
.4byte sEnteiPose93
.4byte sEnteiPose94
.4byte sEnteiPose95
.4byte sEnteiPose96
.4byte sEnteiPose97
.4byte sEnteiPose98
.4byte sEnteiPose99
.4byte sEnteiPose100
.4byte sEnteiPose101
.4byte sEnteiPose102
.4byte sEnteiPose103
.4byte sEnteiPose104
.4byte sEnteiPose105
.4byte sEnteiPose106
.4byte sEnteiPose107
.4byte sEnteiPose108
.4byte sEnteiPose109
.4byte sEnteiPose110
.4byte sEnteiPose111
.4byte sEnteiPose112
.4byte sEnteiPose113
.4byte sEnteiPose114
.4byte sEnteiPose115
.4byte sEnteiPose116
.4byte sEnteiPose117
.4byte sEnteiPose118
.4byte sEnteiPose119
.4byte sEnteiPose120
.4byte sEnteiPose121
.4byte sEnteiPose122
.4byte sEnteiPose123
.4byte sEnteiPose124
.4byte sEnteiPose125
.4byte sEnteiPose126
.4byte sEnteiPose127
.4byte sEnteiPose128
.4byte sEnteiPose129
.4byte sEnteiPose130
.4byte sEnteiPose131
.4byte sEnteiPose132
.4byte sEnteiPose133
.4byte sEnteiPose134
.4byte sEnteiPose135
.4byte sEnteiPose136
.4byte sEnteiPose137
.4byte sEnteiPose138
.4byte sEnteiPose139
.4byte sEnteiPose140
.4byte sEnteiPose141
.4byte sEnteiPose142
.4byte sEnteiPose143
.4byte sEnteiPose144
.4byte sEnteiPose145
.4byte sEnteiPose146
.4byte sEnteiPose147
.4byte sEnteiPose148
.4byte sEnteiPose149
.4byte sEnteiPose150
.4byte sEnteiPose151
.4byte sEnteiPose152
.4byte sEnteiPose153
.4byte sEnteiPose154
.4byte sEnteiPose155
.4byte sEnteiPose156
.4byte sEnteiPose157
.4byte sEnteiPose158
.4byte sEnteiPose159
.4byte sEnteiPose160
.4byte sEnteiPose161
.4byte sEnteiPose162
.4byte sEnteiPose163
.4byte sEnteiPose164
.4byte sEnteiPose165
.4byte sEnteiPose166
.4byte sEnteiPose167
.4byte sEnteiPose168
.4byte sEnteiPose169
.4byte sEnteiPose170
.4byte sEnteiPose171
.4byte sEnteiPose172
.4byte sEnteiPose173
.4byte sEnteiPose174
.4byte sEnteiPose175
.4byte sEnteiPose176
.4byte sEnteiPose177
.4byte sEnteiPose178
.4byte sEnteiPose179
.4byte sEnteiPose180
.4byte sEnteiPose181
.4byte sEnteiPose182
.4byte sEnteiPose183
.4byte sEnteiPose184
.4byte sEnteiPose185
.4byte sEnteiPose186
.4byte sEnteiPose187
.4byte sEnteiPose188
.4byte sEnteiPose189
.4byte sEnteiPose190
.4byte sEnteiPose191
.4byte sEnteiPose192
.4byte sEnteiPose193
.4byte sEnteiPose194
.4byte sEnteiPose195
.4byte sEnteiPose196
.4byte sEnteiPose197
.4byte sEnteiPose198
.4byte sEnteiPose199
.4byte sEnteiPose200
.4byte sEnteiPose201
.4byte sEnteiPose202
.4byte sEnteiPose203
.4byte sEnteiPose204
.4byte sEnteiPose205
.4byte sEnteiPose206
.4byte sEnteiPose207
.4byte sEnteiPose208
.4byte sEnteiPose209
.4byte sEnteiPose210
.4byte sEnteiPose211
.4byte sEnteiPose212
.4byte sEnteiPose213
.4byte sEnteiPose214
.4byte sEnteiPose215
.4byte sEnteiPose216
.4byte sEnteiPose217
.4byte sEnteiPose218
.4byte sEnteiPose219
.4byte sEnteiPose220
.4byte sEnteiPose221
.4byte sEnteiPose222
sAxPositionsEntei:
.2byte    0,  -11, 	  -7,    2, 	   7,    2, 	   0,   -9
.2byte    0,  -10, 	  -7,    4, 	   6,    2, 	   0,   -8
.2byte    0,  -10, 	  -6,    2, 	   7,    4, 	   0,   -8
.2byte    9,  -12, 	   9,    0, 	   0,    2, 	   1,  -12
.2byte    9,  -11, 	  11,    2, 	  -2,    1, 	   0,  -11
.2byte    9,  -11, 	   8,    0, 	   1,    4, 	  -1,  -12
.2byte   15,  -15, 	   8,   -3, 	   8,    1, 	   3,  -13
.2byte   15,  -14, 	  13,   -2, 	   5,    1, 	   3,  -12
.2byte   15,  -14, 	   3,   -1, 	  12,    1, 	   1,  -12
.2byte   10,  -20, 	   1,   -7, 	  10,   -4, 	   1,  -13
.2byte   10,  -19, 	   6,   -8, 	   8,   -2, 	   1,  -13
.2byte   10,  -19, 	   0,   -4, 	  11,   -4, 	   1,  -12
.2byte    0,  -24, 	   5,   -6, 	  -5,   -6, 	   0,  -16
.2byte    0,  -23, 	   4,   -5, 	  -5,   -7, 	   0,  -15
.2byte    0,  -21, 	   5,   -6, 	  -4,   -3, 	   1,  -14
.2byte  -10,  -20, 	  -1,   -7, 	 -10,   -4, 	  -1,  -13
.2byte  -10,  -19, 	  -6,   -8, 	  -8,   -2, 	  -1,  -13
.2byte  -10,  -19, 	   0,   -4, 	 -11,   -4, 	  -1,  -12
.2byte  -15,  -15, 	  -8,   -3, 	  -8,    1, 	  -3,  -13
.2byte  -15,  -14, 	 -13,   -2, 	  -5,    1, 	  -3,  -12
.2byte  -15,  -14, 	  -3,   -1, 	 -12,    1, 	  -1,  -12
.2byte   -9,  -12, 	  -9,    0, 	   0,    2, 	  -1,  -12
.2byte   -9,  -11, 	 -11,    2, 	   2,    1, 	   0,  -11
.2byte   -9,  -11, 	  -8,    0, 	  -1,    4, 	   1,  -12
.2byte    0,  -11, 	  -7,    2, 	   7,    2, 	   0,   -9
.2byte    0,  -10, 	  -7,    4, 	   6,    2, 	   0,   -8
.2byte    0,  -10, 	  -6,    2, 	   7,    4, 	   0,   -8
.2byte    9,  -12, 	   9,    0, 	   0,    2, 	   1,  -12
.2byte    9,  -11, 	  11,    2, 	  -2,    1, 	   0,  -11
.2byte    9,  -11, 	   8,    0, 	   1,    4, 	  -1,  -12
.2byte   15,  -15, 	   8,   -3, 	   8,    1, 	   3,  -13
.2byte   15,  -14, 	  13,   -2, 	   5,    1, 	   3,  -12
.2byte   15,  -14, 	   3,   -1, 	  12,    1, 	   1,  -12
.2byte   10,  -20, 	   1,   -7, 	  10,   -4, 	   1,  -13
.2byte   10,  -19, 	   6,   -8, 	   8,   -2, 	   1,  -13
.2byte   10,  -19, 	   0,   -4, 	  11,   -4, 	   1,  -12
.2byte    0,  -24, 	   5,   -6, 	  -5,   -6, 	   0,  -16
.2byte    0,  -23, 	   4,   -5, 	  -5,   -7, 	   0,  -15
.2byte    0,  -21, 	   5,   -6, 	  -4,   -3, 	   1,  -14
.2byte  -10,  -20, 	  -1,   -7, 	 -10,   -4, 	  -1,  -13
.2byte  -10,  -19, 	  -6,   -8, 	  -8,   -2, 	  -1,  -13
.2byte  -10,  -19, 	   0,   -4, 	 -11,   -4, 	  -1,  -12
.2byte  -15,  -15, 	  -8,   -3, 	  -8,    1, 	  -3,  -13
.2byte  -15,  -14, 	 -13,   -2, 	  -5,    1, 	  -3,  -12
.2byte  -15,  -14, 	  -3,   -1, 	 -12,    1, 	  -1,  -12
.2byte   -9,  -12, 	  -9,    0, 	   0,    2, 	  -1,  -12
.2byte   -9,  -11, 	 -11,    2, 	   2,    1, 	   0,  -11
.2byte   -9,  -11, 	  -8,    0, 	  -1,    4, 	   1,  -12
.2byte    0,  -11, 	  -7,    2, 	   7,    2, 	   0,   -9
.2byte    0,  -10, 	  -7,    4, 	   6,    2, 	   0,   -8
.2byte    0,  -10, 	  -6,    2, 	   7,    4, 	   0,   -8
.2byte    9,  -12, 	   9,    0, 	   0,    2, 	   1,  -12
.2byte    9,  -11, 	  11,    2, 	  -2,    1, 	   0,  -11
.2byte    9,  -11, 	   8,    0, 	   1,    4, 	  -1,  -12
.2byte   15,  -15, 	   8,   -3, 	   8,    1, 	   3,  -13
.2byte   15,  -14, 	  13,   -2, 	   5,    1, 	   3,  -12
.2byte   15,  -14, 	   3,   -1, 	  12,    1, 	   1,  -12
.2byte   10,  -20, 	   1,   -7, 	  10,   -4, 	   1,  -13
.2byte   10,  -19, 	   6,   -8, 	   8,   -2, 	   1,  -13
.2byte   10,  -19, 	   0,   -4, 	  11,   -4, 	   1,  -12
.2byte    0,  -24, 	   5,   -6, 	  -5,   -6, 	   0,  -16
.2byte    0,  -23, 	   4,   -5, 	  -5,   -7, 	   0,  -15
.2byte    0,  -21, 	   5,   -6, 	  -4,   -3, 	   1,  -14
.2byte  -10,  -20, 	  -1,   -7, 	 -10,   -4, 	  -1,  -13
.2byte  -10,  -19, 	  -6,   -8, 	  -8,   -2, 	  -1,  -13
.2byte  -10,  -19, 	   0,   -4, 	 -11,   -4, 	  -1,  -12
.2byte  -15,  -15, 	  -8,   -3, 	  -8,    1, 	  -3,  -13
.2byte  -15,  -14, 	 -13,   -2, 	  -5,    1, 	  -3,  -12
.2byte  -15,  -14, 	  -3,   -1, 	 -12,    1, 	  -1,  -12
.2byte   -9,  -12, 	  -9,    0, 	   0,    2, 	  -1,  -12
.2byte   -9,  -11, 	 -11,    2, 	   2,    1, 	   0,  -11
.2byte   -9,  -11, 	  -8,    0, 	  -1,    4, 	   1,  -12
.2byte    0,  -11, 	  -7,    2, 	   7,    2, 	   0,   -9
.2byte    0,  -22, 	  -7,    2, 	   7,    2, 	   0,  -13
.2byte    0,   -7, 	  -7,    2, 	   7,    2, 	   0,   -9
.2byte    9,  -12, 	   9,    0, 	   0,    2, 	   1,  -12
.2byte    7,  -21, 	   9,    0, 	   0,    2, 	   0,  -14
.2byte   13,   -9, 	   9,    0, 	   0,    2, 	   2,  -11
.2byte   15,  -15, 	   8,   -3, 	   8,    1, 	   3,  -13
.2byte   11,  -24, 	   7,   -1, 	   8,    1, 	   2,  -17
.2byte   19,  -10, 	   6,   -1, 	   8,    1, 	   5,  -11
.2byte   10,  -20, 	   1,   -7, 	  10,   -4, 	   1,  -13
.2byte    8,  -24, 	   1,   -5, 	  10,   -4, 	   0,  -16
.2byte   13,  -17, 	   6,   -7, 	  10,   -4, 	   3,  -15
.2byte    0,  -24, 	   5,   -6, 	  -5,   -6, 	   0,  -16
.2byte    0,  -25, 	   5,   -3, 	  -5,   -3, 	   0,  -15
.2byte    0,  -21, 	   5,   -4, 	  -5,   -4, 	   0,  -16
.2byte  -10,  -20, 	  -1,   -7, 	 -10,   -4, 	  -1,  -13
.2byte   -8,  -24, 	  -1,   -5, 	 -10,   -4, 	   0,  -16
.2byte  -13,  -17, 	  -6,   -7, 	 -10,   -4, 	  -3,  -15
.2byte  -15,  -15, 	  -8,   -3, 	  -8,    1, 	  -3,  -13
.2byte  -11,  -24, 	  -7,   -1, 	  -8,    1, 	  -2,  -17
.2byte  -19,  -10, 	  -6,   -1, 	  -8,    1, 	  -5,  -11
.2byte   -9,  -12, 	  -9,    0, 	   0,    2, 	  -1,  -12
.2byte   -7,  -21, 	  -9,    0, 	   0,    2, 	   0,  -14
.2byte  -13,   -9, 	  -9,    0, 	   0,    2, 	  -2,  -11
.2byte    0,  -11, 	  -7,    2, 	   7,    2, 	   0,   -9
.2byte    0,  -22, 	  -7,    2, 	   7,    2, 	   0,  -13
.2byte    0,   -7, 	  -7,    2, 	   7,    2, 	   0,   -9
.2byte    0,   -4, 	  -7,    3, 	   7,    6, 	   0,   -6
.2byte    9,  -12, 	   9,    0, 	   0,    2, 	   1,  -12
.2byte    7,  -21, 	   9,    0, 	   0,    2, 	   0,  -14
.2byte   13,   -9, 	   9,    0, 	   0,    2, 	   2,  -11
.2byte   13,   -4, 	  11,    1, 	   7,    6, 	   2,   -9
.2byte   15,  -15, 	   8,   -3, 	   8,    1, 	   3,  -13
.2byte   11,  -24, 	   7,   -1, 	   8,    1, 	   2,  -17
.2byte   19,  -10, 	   6,   -1, 	   8,    1, 	   5,  -11
.2byte   17,   -7, 	   6,   -1, 	  15,    1, 	   1,  -10
.2byte   10,  -20, 	   1,   -7, 	  10,   -4, 	   1,  -13
.2byte    8,  -24, 	   1,   -5, 	  10,   -4, 	   0,  -16
.2byte   13,  -17, 	   6,   -7, 	  10,   -4, 	   3,  -15
.2byte   12,  -12, 	   9,  -10, 	  15,   -6, 	   2,  -11
.2byte    0,  -24, 	   5,   -6, 	  -5,   -6, 	   0,  -16
.2byte    0,  -25, 	   5,   -3, 	  -5,   -3, 	   0,  -15
.2byte    0,  -21, 	   5,   -4, 	  -5,   -4, 	   0,  -16
.2byte    0,  -18, 	   5,  -10, 	  -5,   -4, 	   0,  -13
.2byte  -10,  -20, 	  -1,   -7, 	 -10,   -4, 	  -1,  -13
.2byte   -8,  -24, 	  -1,   -5, 	 -10,   -4, 	   0,  -16
.2byte  -13,  -17, 	  -6,   -7, 	 -10,   -4, 	  -3,  -15
.2byte  -10,  -12, 	  -7,  -10, 	 -13,   -6, 	   0,  -11
.2byte  -15,  -15, 	  -8,   -3, 	  -8,    1, 	  -3,  -13
.2byte  -11,  -24, 	  -7,   -1, 	  -8,    1, 	  -2,  -17
.2byte  -19,  -10, 	  -6,   -1, 	  -8,    1, 	  -5,  -11
.2byte  -18,   -7, 	  -7,   -1, 	 -16,    1, 	  -2,  -10
.2byte   -9,  -12, 	  -9,    0, 	   0,    2, 	  -1,  -12
.2byte   -7,  -21, 	  -9,    0, 	   0,    2, 	   0,  -14
.2byte  -13,   -9, 	  -9,    0, 	   0,    2, 	  -2,  -11
.2byte  -13,   -4, 	 -11,    1, 	  -7,    6, 	  -2,   -9
.2byte   -9,   -5, 	 -14,   -1, 	  -4,    2, 	   1,  -10
.2byte   -9,   -5, 	 -14,   -1, 	  -4,    2, 	   1,   -9
.2byte    0,   -7, 	 -11,    2, 	  11,    2, 	   0,  -10
.2byte    8,   -6, 	  13,   -1, 	  -8,    1, 	  -3,  -10
.2byte   13,   -9, 	  12,   -3, 	   6,    2, 	  -1,  -10
.2byte   11,  -15, 	   2,  -14, 	  14,   -3, 	   1,  -12
.2byte    0,  -20, 	   7,   -2, 	  -7,   -2, 	   0,  -13
.2byte  -12,  -15, 	  -3,  -14, 	 -15,   -3, 	  -2,  -12
.2byte  -14,   -9, 	 -13,   -3, 	  -7,    2, 	   0,  -10
.2byte   -9,   -6, 	 -14,   -1, 	   7,    1, 	   2,  -10
.2byte    0,  -11, 	  -7,    2, 	   7,    2, 	   0,   -9
.2byte    0,  -22, 	  -7,    2, 	   7,    2, 	   0,  -13
.2byte    0,   -7, 	  -7,    2, 	   7,    2, 	   0,   -9
.2byte    9,  -12, 	   9,    0, 	   0,    2, 	   1,  -12
.2byte    7,  -21, 	   9,    0, 	   0,    2, 	   0,  -14
.2byte   13,   -9, 	   9,    0, 	   0,    2, 	   2,  -11
.2byte   15,  -15, 	   8,   -3, 	   8,    1, 	   3,  -13
.2byte   11,  -24, 	   7,   -1, 	   8,    1, 	   2,  -17
.2byte   19,  -10, 	   6,   -1, 	   8,    1, 	   5,  -11
.2byte   10,  -20, 	   1,   -7, 	  10,   -4, 	   1,  -13
.2byte    8,  -24, 	   1,   -5, 	  10,   -4, 	   0,  -16
.2byte   13,  -17, 	   6,   -7, 	  10,   -4, 	   3,  -15
.2byte    0,  -24, 	   5,   -6, 	  -5,   -6, 	   0,  -16
.2byte    0,  -25, 	   5,   -3, 	  -5,   -3, 	   0,  -15
.2byte    0,  -21, 	   5,   -4, 	  -5,   -4, 	   0,  -16
.2byte  -10,  -20, 	  -1,   -7, 	 -10,   -4, 	  -1,  -13
.2byte   -8,  -24, 	  -1,   -5, 	 -10,   -4, 	   0,  -16
.2byte  -13,  -17, 	  -6,   -7, 	 -10,   -4, 	  -3,  -15
.2byte  -15,  -15, 	  -8,   -3, 	  -8,    1, 	  -3,  -13
.2byte  -11,  -24, 	  -7,   -1, 	  -8,    1, 	  -2,  -17
.2byte  -19,  -10, 	  -6,   -1, 	  -8,    1, 	  -5,  -11
.2byte   -9,  -12, 	  -9,    0, 	   0,    2, 	  -1,  -12
.2byte   -7,  -21, 	  -9,    0, 	   0,    2, 	   0,  -14
.2byte  -13,   -9, 	  -9,    0, 	   0,    2, 	  -2,  -11
.2byte    0,  -10, 	  -6,    2, 	   7,    4, 	   0,   -8
.2byte   -9,  -11, 	  -8,    0, 	  -1,    4, 	   1,  -12
.2byte  -15,  -14, 	  -3,   -1, 	 -12,    1, 	  -1,  -12
.2byte  -10,  -19, 	   0,   -4, 	 -11,   -4, 	  -1,  -12
.2byte    0,  -21, 	   5,   -6, 	  -4,   -3, 	   1,  -14
.2byte   10,  -19, 	   0,   -4, 	  11,   -4, 	   1,  -12
.2byte   15,  -14, 	   3,   -1, 	  12,    1, 	   1,  -12
.2byte    9,  -11, 	   8,    0, 	   1,    4, 	  -1,  -12
.2byte    0,   -4, 	  -7,    3, 	   7,    6, 	   0,   -6
.2byte   11,   -5, 	   9,    0, 	   5,    5, 	   0,  -10
.2byte   17,   -7, 	   6,   -1, 	  15,    1, 	   1,  -10
.2byte   10,  -13, 	   7,  -11, 	  13,   -7, 	   0,  -12
.2byte    0,  -16, 	   5,   -8, 	  -5,   -2, 	   0,  -11
.2byte  -10,  -13, 	  -7,  -11, 	 -13,   -7, 	   0,  -12
.2byte  -18,   -7, 	  -7,   -1, 	 -16,    1, 	  -2,  -10
.2byte  -11,   -5, 	  -9,    0, 	  -5,    5, 	   0,  -10
.2byte    0,  -11, 	  -7,    2, 	   7,    2, 	   0,   -9
.2byte    0,  -22, 	  -7,    2, 	   7,    2, 	   0,  -13
.2byte    0,   -4, 	  -7,    3, 	   7,    6, 	   0,   -6
.2byte    9,  -12, 	   9,    0, 	   0,    2, 	   1,  -12
.2byte    7,  -21, 	   9,    0, 	   0,    2, 	   0,  -14
.2byte   10,   -5, 	   8,    0, 	   4,    5, 	  -1,  -10
.2byte   15,  -15, 	   8,   -3, 	   8,    1, 	   3,  -13
.2byte   11,  -24, 	   7,   -1, 	   8,    1, 	   2,  -17
.2byte   16,   -7, 	   5,   -1, 	  14,    1, 	   0,  -10
.2byte   10,  -20, 	   1,   -7, 	  10,   -4, 	   1,  -13
.2byte    8,  -24, 	   1,   -5, 	  10,   -4, 	   0,  -16
.2byte   11,  -15, 	   8,  -13, 	  14,   -9, 	   1,  -14
.2byte    0,  -24, 	   5,   -6, 	  -5,   -6, 	   0,  -16
.2byte    0,  -25, 	   5,   -3, 	  -5,   -3, 	   0,  -15
.2byte    0,  -16, 	   5,   -8, 	  -5,   -2, 	   0,  -11
.2byte  -10,  -20, 	  -1,   -7, 	 -10,   -4, 	  -1,  -13
.2byte   -8,  -24, 	  -1,   -5, 	 -10,   -4, 	   0,  -16
.2byte  -11,  -15, 	  -8,  -13, 	 -14,   -9, 	  -1,  -14
.2byte  -15,  -15, 	  -8,   -3, 	  -8,    1, 	  -3,  -13
.2byte  -11,  -24, 	  -7,   -1, 	  -8,    1, 	  -2,  -17
.2byte  -16,   -7, 	  -5,   -1, 	 -14,    1, 	   0,  -10
.2byte   -9,  -12, 	  -9,    0, 	   0,    2, 	  -1,  -12
.2byte   -7,  -21, 	  -9,    0, 	   0,    2, 	   0,  -14
.2byte  -10,   -5, 	  -8,    0, 	  -4,    5, 	   1,  -10
.2byte    0,  -22, 	  -7,    2, 	   7,    2, 	   0,  -13
.2byte   -7,  -21, 	  -9,    0, 	   0,    2, 	   0,  -14
.2byte  -11,  -24, 	  -7,   -1, 	  -8,    1, 	  -2,  -17
.2byte   -8,  -24, 	  -1,   -5, 	 -10,   -4, 	   0,  -16
.2byte    0,  -25, 	   5,   -3, 	  -5,   -3, 	   0,  -15
.2byte    8,  -24, 	   1,   -5, 	  10,   -4, 	   0,  -16
.2byte   11,  -24, 	   7,   -1, 	   8,    1, 	   2,  -17
.2byte    7,  -21, 	   9,    0, 	   0,    2, 	   0,  -14
.2byte    0,  -11, 	  -7,    2, 	   7,    2, 	   0,   -9
.2byte   -9,  -12, 	  -9,    0, 	   0,    2, 	  -1,  -12
.2byte  -15,  -15, 	  -8,   -3, 	  -8,    1, 	  -3,  -13
.2byte  -10,  -20, 	  -1,   -7, 	 -10,   -4, 	  -1,  -13
.2byte    0,  -24, 	   5,   -6, 	  -5,   -6, 	   0,  -16
.2byte   10,  -20, 	   1,   -7, 	  10,   -4, 	   1,  -13
.2byte   15,  -15, 	   8,   -3, 	   8,    1, 	   3,  -13
.2byte    9,  -12, 	   9,    0, 	   0,    2, 	   1,  -12
.2byte    0,  -11, 	  -7,    2, 	   7,    2, 	   0,   -9
.2byte    0,  -22, 	  -7,    2, 	   7,    2, 	   0,  -13
.2byte    0,  -16, 	  -7,    2, 	   7,    2, 	   0,  -11
.2byte    0,   -7, 	  -7,    2, 	   7,    2, 	   0,   -9
sEnteiAnimTable1:
.4byte sEnteiAnims_1_1
.4byte sEnteiAnims_1_2
.4byte sEnteiAnims_1_3
.4byte sEnteiAnims_1_4
.4byte sEnteiAnims_1_5
.4byte sEnteiAnims_1_6
.4byte sEnteiAnims_1_7
.4byte sEnteiAnims_1_8
sEnteiAnimTable2:
.4byte sEnteiAnims_2_1
.4byte sEnteiAnims_2_2
.4byte sEnteiAnims_2_3
.4byte sEnteiAnims_2_4
.4byte sEnteiAnims_2_5
.4byte sEnteiAnims_2_6
.4byte sEnteiAnims_2_7
.4byte sEnteiAnims_2_8
sEnteiAnimTable3:
.4byte sEnteiAnims_3_1
.4byte sEnteiAnims_3_2
.4byte sEnteiAnims_3_3
.4byte sEnteiAnims_3_4
.4byte sEnteiAnims_3_5
.4byte sEnteiAnims_3_6
.4byte sEnteiAnims_3_7
.4byte sEnteiAnims_3_8
sEnteiAnimTable4:
.4byte sEnteiAnims_4_1
.4byte sEnteiAnims_4_2
.4byte sEnteiAnims_4_3
.4byte sEnteiAnims_4_4
.4byte sEnteiAnims_4_5
.4byte sEnteiAnims_4_6
.4byte sEnteiAnims_4_7
.4byte sEnteiAnims_4_8
sEnteiAnimTable5:
.4byte sEnteiAnims_5_1
.4byte sEnteiAnims_5_2
.4byte sEnteiAnims_5_3
.4byte sEnteiAnims_5_4
.4byte sEnteiAnims_5_5
.4byte sEnteiAnims_5_6
.4byte sEnteiAnims_5_7
.4byte sEnteiAnims_5_8
sEnteiAnimTable6:
.4byte sEnteiAnims_6_1
.4byte sEnteiAnims_6_1
.4byte sEnteiAnims_6_1
.4byte sEnteiAnims_6_1
.4byte sEnteiAnims_6_1
.4byte sEnteiAnims_6_1
.4byte sEnteiAnims_6_1
.4byte sEnteiAnims_6_1
sEnteiAnimTable7:
.4byte sEnteiAnims_7_1
.4byte sEnteiAnims_7_2
.4byte sEnteiAnims_7_3
.4byte sEnteiAnims_7_4
.4byte sEnteiAnims_7_5
.4byte sEnteiAnims_7_6
.4byte sEnteiAnims_7_7
.4byte sEnteiAnims_7_8
sEnteiAnimTable8:
.4byte sEnteiAnims_8_1
.4byte sEnteiAnims_8_2
.4byte sEnteiAnims_8_3
.4byte sEnteiAnims_8_4
.4byte sEnteiAnims_8_5
.4byte sEnteiAnims_8_6
.4byte sEnteiAnims_8_7
.4byte sEnteiAnims_8_8
sEnteiAnimTable9:
.4byte sEnteiAnims_9_1
.4byte sEnteiAnims_9_2
.4byte sEnteiAnims_9_3
.4byte sEnteiAnims_9_4
.4byte sEnteiAnims_9_5
.4byte sEnteiAnims_9_6
.4byte sEnteiAnims_9_7
.4byte sEnteiAnims_9_8
sEnteiAnimTable10:
.4byte sEnteiAnims_10_1
.4byte sEnteiAnims_10_2
.4byte sEnteiAnims_10_3
.4byte sEnteiAnims_10_4
.4byte sEnteiAnims_10_5
.4byte sEnteiAnims_10_6
.4byte sEnteiAnims_10_7
.4byte sEnteiAnims_10_8
sEnteiAnimTable11:
.4byte sEnteiAnims_11_1
.4byte sEnteiAnims_11_2
.4byte sEnteiAnims_11_3
.4byte sEnteiAnims_11_4
.4byte sEnteiAnims_11_5
.4byte sEnteiAnims_11_6
.4byte sEnteiAnims_11_7
.4byte sEnteiAnims_11_8
sEnteiAnimTable12:
.4byte sEnteiAnims_12_1
.4byte sEnteiAnims_12_2
.4byte sEnteiAnims_12_3
.4byte sEnteiAnims_12_4
.4byte sEnteiAnims_12_5
.4byte sEnteiAnims_12_6
.4byte sEnteiAnims_12_7
.4byte sEnteiAnims_12_8
sEnteiAnimTable13:
.4byte sEnteiAnims_13_1
.4byte sEnteiAnims_13_2
.4byte sEnteiAnims_13_3
.4byte sEnteiAnims_13_4
.4byte sEnteiAnims_13_5
.4byte sEnteiAnims_13_6
.4byte sEnteiAnims_13_7
.4byte sEnteiAnims_13_8
sEnteiAnimTable14:
.4byte sEnteiAnims_14_1
.4byte sEnteiAnims_14_2
.4byte sEnteiAnims_14_3
.4byte sEnteiAnims_14_4
.4byte sEnteiAnims_14_5
.4byte sEnteiAnims_14_6
.4byte sEnteiAnims_14_7
.4byte sEnteiAnims_14_8
sAxAnimationsEntei:
.4byte sEnteiAnimTable1
.4byte sEnteiAnimTable2
.4byte sEnteiAnimTable3
.4byte sEnteiAnimTable4
.4byte sEnteiAnimTable5
.4byte sEnteiAnimTable6
.4byte sEnteiAnimTable7
.4byte sEnteiAnimTable8
.4byte sEnteiAnimTable9
.4byte sEnteiAnimTable10
.4byte sEnteiAnimTable11
.4byte sEnteiAnimTable12
.4byte sEnteiAnimTable13
.4byte sEnteiAnimTable14
sAxSpritesEntei:
.4byte sEnteiSprites1
.4byte sEnteiSprites2
.4byte sEnteiSprites3
.4byte sEnteiSprites4
.4byte sEnteiSprites5
.4byte sEnteiSprites6
.4byte sEnteiSprites7
.4byte sEnteiSprites8
.4byte sEnteiSprites9
.4byte sEnteiSprites10
.4byte sEnteiSprites11
.4byte sEnteiSprites12
.4byte sEnteiSprites13
.4byte sEnteiSprites14
.4byte sEnteiSprites15
.4byte sEnteiSprites16
.4byte sEnteiSprites17
.4byte sEnteiSprites18
.4byte sEnteiSprites19
.4byte sEnteiSprites20
.4byte sEnteiSprites21
.4byte sEnteiSprites22
.4byte sEnteiSprites23
.4byte sEnteiSprites24
.4byte sEnteiSprites25
.4byte sEnteiSprites26
.4byte sEnteiSprites27
.4byte sEnteiSprites28
.4byte sEnteiSprites29
.4byte sEnteiSprites30
.4byte sEnteiSprites31
.4byte sEnteiSprites32
.4byte sEnteiSprites33
.4byte sEnteiSprites34
.4byte sEnteiSprites35
.4byte sEnteiSprites36
.4byte sEnteiSprites37
.4byte sEnteiSprites38
.4byte sEnteiSprites39
.4byte sEnteiSprites40
.4byte sEnteiSprites41
.4byte sEnteiSprites42
.4byte sEnteiSprites43
.4byte sEnteiSprites44
.4byte sEnteiSprites45
.4byte sEnteiSprites46
.4byte sEnteiSprites47
.4byte sEnteiSprites48
.4byte sEnteiSprites49
.4byte sEnteiSprites50
.4byte sEnteiSprites51
.4byte sEnteiSprites52
.4byte sEnteiSprites53
.4byte sEnteiSprites54
.4byte sEnteiSprites55
.4byte sEnteiSprites56
.4byte sEnteiSprites57
.4byte sEnteiSprites58
.4byte sEnteiSprites59
.4byte sEnteiSprites60
.4byte sEnteiSprites61
.4byte sEnteiSprites62
.4byte sEnteiSprites63
.4byte sEnteiSprites64
.4byte sEnteiSprites65
.4byte sEnteiSprites66
.4byte sEnteiSprites67
.4byte sEnteiSprites68
.4byte sEnteiSprites69
.4byte sEnteiSprites70
.4byte sEnteiSprites71
.4byte sEnteiSprites72
.4byte sEnteiSprites73
.4byte sEnteiSprites74
.4byte sEnteiSprites75
.4byte sEnteiSprites76
.4byte sEnteiSprites77
.4byte sEnteiSprites78
.4byte sEnteiSprites79
.4byte sEnteiSprites80
.4byte sEnteiSprites81
.4byte sEnteiSprites82
.4byte sEnteiSprites83
.4byte sEnteiSprites84
.4byte sEnteiSprites85
.4byte sEnteiSprites86
.4byte sEnteiSprites87
sAxMainEntei:
ax_main sAxPosesEntei, sAxAnimationsEntei, 14, sAxSpritesEntei, sAxPositionsEntei
