.global gAxFeebas
gAxFeebas:
ax_siro sAxMainFeebas
sFeebasPose1:
ax_pose 0, 0x01e9, 0x80f4, 0x0c00
ax_pose_terminator
sFeebasPose2:
ax_pose 1, 0x01e9, 0x80f4, 0x0c00
ax_pose_terminator
sFeebasPose3:
ax_pose 2, 0x01e9, 0x80f4, 0x0c00
ax_pose_terminator
sFeebasPose4:
ax_pose 3, 0x01e9, 0x90eb, 0x0c00
ax_pose_terminator
sFeebasPose5:
ax_pose 4, 0x01e9, 0x90eb, 0x0c00
ax_pose_terminator
sFeebasPose6:
ax_pose 5, 0x01e9, 0x90eb, 0x0c00
ax_pose_terminator
sFeebasPose7:
ax_pose 6, 0x01e9, 0x90f1, 0x0c00
ax_pose_terminator
sFeebasPose8:
ax_pose 7, 0x01e9, 0x90ea, 0x0c00
ax_pose_terminator
sFeebasPose9:
ax_pose 8, 0x01e9, 0x90f1, 0x0c00
ax_pose_terminator
sFeebasPose10:
ax_pose 9, 0x01e7, 0x90ec, 0x0c00
ax_pose_terminator
sFeebasPose11:
ax_pose 10, 0x01e7, 0x90ec, 0x0c00
ax_pose_terminator
sFeebasPose12:
ax_pose 11, 0x01e7, 0x90ec, 0x0c00
ax_pose_terminator
sFeebasPose13:
ax_pose 12, 0x01e7, 0x80f4, 0x0c00
ax_pose_terminator
sFeebasPose14:
ax_pose 13, 0x01e7, 0x80f4, 0x0c00
ax_pose_terminator
sFeebasPose15:
ax_pose 14, 0x01e7, 0x80f4, 0x0c00
ax_pose_terminator
sFeebasPose16:
ax_pose 9, 0x01e7, 0x80f5, 0x0c00
ax_pose_terminator
sFeebasPose17:
ax_pose 10, 0x01e7, 0x80f5, 0x0c00
ax_pose_terminator
sFeebasPose18:
ax_pose 11, 0x01e7, 0x80f5, 0x0c00
ax_pose_terminator
sFeebasPose19:
ax_pose 6, 0x01e9, 0x80f0, 0x0c00
ax_pose_terminator
sFeebasPose20:
ax_pose 7, 0x01e9, 0x80f7, 0x0c00
ax_pose_terminator
sFeebasPose21:
ax_pose 8, 0x01e9, 0x80f0, 0x0c00
ax_pose_terminator
sFeebasPose22:
ax_pose 3, 0x01e9, 0x80f6, 0x0c00
ax_pose_terminator
sFeebasPose23:
ax_pose 4, 0x01e9, 0x80f6, 0x0c00
ax_pose_terminator
sFeebasPose24:
ax_pose 5, 0x01e9, 0x80f6, 0x0c00
ax_pose_terminator
sFeebasPose25:
ax_pose 0, 0x01e9, 0x80f4, 0x0c00
ax_pose_terminator
sFeebasPose26:
ax_pose 1, 0x01e9, 0x80f4, 0x0c00
ax_pose_terminator
sFeebasPose27:
ax_pose 2, 0x01e9, 0x80f4, 0x0c00
ax_pose_terminator
sFeebasPose28:
ax_pose 3, 0x01e9, 0x90eb, 0x0c00
ax_pose_terminator
sFeebasPose29:
ax_pose 4, 0x01e9, 0x90eb, 0x0c00
ax_pose_terminator
sFeebasPose30:
ax_pose 5, 0x01e9, 0x90eb, 0x0c00
ax_pose_terminator
sFeebasPose31:
ax_pose 6, 0x01e9, 0x90f1, 0x0c00
ax_pose_terminator
sFeebasPose32:
ax_pose 7, 0x01e9, 0x90ea, 0x0c00
ax_pose_terminator
sFeebasPose33:
ax_pose 8, 0x01e9, 0x90f1, 0x0c00
ax_pose_terminator
sFeebasPose34:
ax_pose 9, 0x01e7, 0x90ec, 0x0c00
ax_pose_terminator
sFeebasPose35:
ax_pose 10, 0x01e7, 0x90ec, 0x0c00
ax_pose_terminator
sFeebasPose36:
ax_pose 11, 0x01e7, 0x90ec, 0x0c00
ax_pose_terminator
sFeebasPose37:
ax_pose 12, 0x01e7, 0x80f4, 0x0c00
ax_pose_terminator
sFeebasPose38:
ax_pose 13, 0x01e7, 0x80f4, 0x0c00
ax_pose_terminator
sFeebasPose39:
ax_pose 14, 0x01e7, 0x80f4, 0x0c00
ax_pose_terminator
sFeebasPose40:
ax_pose 9, 0x01e7, 0x80f5, 0x0c00
ax_pose_terminator
sFeebasPose41:
ax_pose 10, 0x01e7, 0x80f5, 0x0c00
ax_pose_terminator
sFeebasPose42:
ax_pose 11, 0x01e7, 0x80f5, 0x0c00
ax_pose_terminator
sFeebasPose43:
ax_pose 6, 0x01e9, 0x80f0, 0x0c00
ax_pose_terminator
sFeebasPose44:
ax_pose 7, 0x01e9, 0x80f7, 0x0c00
ax_pose_terminator
sFeebasPose45:
ax_pose 8, 0x01e9, 0x80f0, 0x0c00
ax_pose_terminator
sFeebasPose46:
ax_pose 3, 0x01e9, 0x80f6, 0x0c00
ax_pose_terminator
sFeebasPose47:
ax_pose 4, 0x01e9, 0x80f6, 0x0c00
ax_pose_terminator
sFeebasPose48:
ax_pose 5, 0x01e9, 0x80f6, 0x0c00
ax_pose_terminator
sFeebasPose49:
ax_pose 0, 0x01e9, 0x80f4, 0x0c00
ax_pose_terminator
sFeebasPose50:
ax_pose 1, 0x01e9, 0x80f4, 0x0c00
ax_pose_terminator
sFeebasPose51:
ax_pose 2, 0x01e9, 0x80f4, 0x0c00
ax_pose_terminator
sFeebasPose52:
ax_pose 3, 0x01e9, 0x90eb, 0x0c00
ax_pose_terminator
sFeebasPose53:
ax_pose 4, 0x01e9, 0x90eb, 0x0c00
ax_pose_terminator
sFeebasPose54:
ax_pose 5, 0x01e9, 0x90eb, 0x0c00
ax_pose_terminator
sFeebasPose55:
ax_pose 6, 0x01e9, 0x90f1, 0x0c00
ax_pose_terminator
sFeebasPose56:
ax_pose 7, 0x01e9, 0x90ea, 0x0c00
ax_pose_terminator
sFeebasPose57:
ax_pose 8, 0x01e9, 0x90f1, 0x0c00
ax_pose_terminator
sFeebasPose58:
ax_pose 9, 0x01e7, 0x90ec, 0x0c00
ax_pose_terminator
sFeebasPose59:
ax_pose 10, 0x01e7, 0x90ec, 0x0c00
ax_pose_terminator
sFeebasPose60:
ax_pose 11, 0x01e7, 0x90ec, 0x0c00
ax_pose_terminator
sFeebasPose61:
ax_pose 12, 0x01e7, 0x80f4, 0x0c00
ax_pose_terminator
sFeebasPose62:
ax_pose 13, 0x01e7, 0x80f4, 0x0c00
ax_pose_terminator
sFeebasPose63:
ax_pose 14, 0x01e7, 0x80f4, 0x0c00
ax_pose_terminator
sFeebasPose64:
ax_pose 9, 0x01e7, 0x80f5, 0x0c00
ax_pose_terminator
sFeebasPose65:
ax_pose 10, 0x01e7, 0x80f5, 0x0c00
ax_pose_terminator
sFeebasPose66:
ax_pose 11, 0x01e7, 0x80f5, 0x0c00
ax_pose_terminator
sFeebasPose67:
ax_pose 6, 0x01e9, 0x80f0, 0x0c00
ax_pose_terminator
sFeebasPose68:
ax_pose 7, 0x01e9, 0x80f7, 0x0c00
ax_pose_terminator
sFeebasPose69:
ax_pose 8, 0x01e9, 0x80f0, 0x0c00
ax_pose_terminator
sFeebasPose70:
ax_pose 3, 0x01e9, 0x80f6, 0x0c00
ax_pose_terminator
sFeebasPose71:
ax_pose 4, 0x01e9, 0x80f6, 0x0c00
ax_pose_terminator
sFeebasPose72:
ax_pose 5, 0x01e9, 0x80f6, 0x0c00
ax_pose_terminator
sFeebasPose73:
ax_pose 0, 0x01e9, 0x80f4, 0x0c00
ax_pose_terminator
sFeebasPose74:
ax_pose 1, 0x01e9, 0x80f4, 0x0c00
ax_pose_terminator
sFeebasPose75:
ax_pose 2, 0x01e9, 0x80f4, 0x0c00
ax_pose_terminator
sFeebasPose76:
ax_pose 15, 0x01e9, 0x80f4, 0x0c00
ax_pose_terminator
sFeebasPose77:
ax_pose 3, 0x01e9, 0x90eb, 0x0c00
ax_pose_terminator
sFeebasPose78:
ax_pose 4, 0x01e9, 0x90eb, 0x0c00
ax_pose_terminator
sFeebasPose79:
ax_pose 5, 0x01e9, 0x90eb, 0x0c00
ax_pose_terminator
sFeebasPose80:
ax_pose 16, 0x01e9, 0x90eb, 0x0c00
ax_pose_terminator
sFeebasPose81:
ax_pose 6, 0x01e9, 0x90f1, 0x0c00
ax_pose_terminator
sFeebasPose82:
ax_pose 7, 0x01e9, 0x90ea, 0x0c00
ax_pose_terminator
sFeebasPose83:
ax_pose 8, 0x01e9, 0x90f1, 0x0c00
ax_pose_terminator
sFeebasPose84:
ax_pose 17, 0x01e9, 0x90f1, 0x0c00
ax_pose_terminator
sFeebasPose85:
ax_pose 9, 0x01e7, 0x90ec, 0x0c00
ax_pose_terminator
sFeebasPose86:
ax_pose 10, 0x01e7, 0x90ec, 0x0c00
ax_pose_terminator
sFeebasPose87:
ax_pose 11, 0x01e7, 0x90ec, 0x0c00
ax_pose_terminator
sFeebasPose88:
ax_pose 18, 0x01e7, 0x90ec, 0x0c00
ax_pose_terminator
sFeebasPose89:
ax_pose 12, 0x01e7, 0x80f4, 0x0c00
ax_pose_terminator
sFeebasPose90:
ax_pose 13, 0x01e7, 0x80f4, 0x0c00
ax_pose_terminator
sFeebasPose91:
ax_pose 14, 0x01e7, 0x80f4, 0x0c00
ax_pose_terminator
sFeebasPose92:
ax_pose 19, 0x01e7, 0x80f4, 0x0c00
ax_pose_terminator
sFeebasPose93:
ax_pose 9, 0x01e7, 0x80f5, 0x0c00
ax_pose_terminator
sFeebasPose94:
ax_pose 10, 0x01e7, 0x80f5, 0x0c00
ax_pose_terminator
sFeebasPose95:
ax_pose 11, 0x01e7, 0x80f5, 0x0c00
ax_pose_terminator
sFeebasPose96:
ax_pose 18, 0x01e7, 0x80f5, 0x0c00
ax_pose_terminator
sFeebasPose97:
ax_pose 6, 0x01e9, 0x80f0, 0x0c00
ax_pose_terminator
sFeebasPose98:
ax_pose 7, 0x01e9, 0x80f7, 0x0c00
ax_pose_terminator
sFeebasPose99:
ax_pose 8, 0x01e9, 0x80f0, 0x0c00
ax_pose_terminator
sFeebasPose100:
ax_pose 17, 0x01e9, 0x80f0, 0x0c00
ax_pose_terminator
sFeebasPose101:
ax_pose 3, 0x01e9, 0x80f6, 0x0c00
ax_pose_terminator
sFeebasPose102:
ax_pose 4, 0x01e9, 0x80f6, 0x0c00
ax_pose_terminator
sFeebasPose103:
ax_pose 5, 0x01e9, 0x80f6, 0x0c00
ax_pose_terminator
sFeebasPose104:
ax_pose 16, 0x01e9, 0x80f6, 0x0c00
ax_pose_terminator
sFeebasPose105:
ax_pose 0, 0x01e9, 0x80f4, 0x0c00
ax_pose_terminator
sFeebasPose106:
ax_pose 1, 0x01e9, 0x80f4, 0x0c00
ax_pose_terminator
sFeebasPose107:
ax_pose 2, 0x01e9, 0x80f4, 0x0c00
ax_pose_terminator
sFeebasPose108:
ax_pose 15, 0x01e9, 0x80f4, 0x0c00
ax_pose_terminator
sFeebasPose109:
ax_pose 3, 0x01e9, 0x90eb, 0x0c00
ax_pose_terminator
sFeebasPose110:
ax_pose 5, 0x01e9, 0x90eb, 0x0c00
ax_pose_terminator
sFeebasPose111:
ax_pose 4, 0x01e9, 0x90eb, 0x0c00
ax_pose_terminator
sFeebasPose112:
ax_pose 16, 0x01e9, 0x90eb, 0x0c00
ax_pose_terminator
sFeebasPose113:
ax_pose 6, 0x01e9, 0x90f1, 0x0c00
ax_pose_terminator
sFeebasPose114:
ax_pose 8, 0x01e9, 0x90f1, 0x0c00
ax_pose_terminator
sFeebasPose115:
ax_pose 7, 0x01e9, 0x90ea, 0x0c00
ax_pose_terminator
sFeebasPose116:
ax_pose 17, 0x01e9, 0x90f1, 0x0c00
ax_pose_terminator
sFeebasPose117:
ax_pose 9, 0x01e7, 0x90ec, 0x0c00
ax_pose_terminator
sFeebasPose118:
ax_pose 11, 0x01e7, 0x90eb, 0x0c00
ax_pose_terminator
sFeebasPose119:
ax_pose 10, 0x01e7, 0x90ec, 0x0c00
ax_pose_terminator
sFeebasPose120:
ax_pose 18, 0x01e7, 0x90ec, 0x0c00
ax_pose_terminator
sFeebasPose121:
ax_pose 12, 0x01e7, 0x80f4, 0x0c00
ax_pose_terminator
sFeebasPose122:
ax_pose 13, 0x01e7, 0x80f4, 0x0c00
ax_pose_terminator
sFeebasPose123:
ax_pose 14, 0x01e7, 0x80f4, 0x0c00
ax_pose_terminator
sFeebasPose124:
ax_pose 19, 0x01e7, 0x80f4, 0x0c00
ax_pose_terminator
sFeebasPose125:
ax_pose 9, 0x01e7, 0x80f5, 0x0c00
ax_pose_terminator
sFeebasPose126:
ax_pose 10, 0x01e7, 0x80f5, 0x0c00
ax_pose_terminator
sFeebasPose127:
ax_pose 11, 0x01e7, 0x80f5, 0x0c00
ax_pose_terminator
sFeebasPose128:
ax_pose 18, 0x01e7, 0x80f5, 0x0c00
ax_pose_terminator
sFeebasPose129:
ax_pose 6, 0x01e9, 0x80f0, 0x0c00
ax_pose_terminator
sFeebasPose130:
ax_pose 7, 0x01e9, 0x80f7, 0x0c00
ax_pose_terminator
sFeebasPose131:
ax_pose 8, 0x01e9, 0x80f0, 0x0c00
ax_pose_terminator
sFeebasPose132:
ax_pose 17, 0x01e9, 0x80f0, 0x0c00
ax_pose_terminator
sFeebasPose133:
ax_pose 3, 0x01e9, 0x80f6, 0x0c00
ax_pose_terminator
sFeebasPose134:
ax_pose 4, 0x01e9, 0x80f6, 0x0c00
ax_pose_terminator
sFeebasPose135:
ax_pose 5, 0x01e9, 0x80f6, 0x0c00
ax_pose_terminator
sFeebasPose136:
ax_pose 16, 0x01e9, 0x80f6, 0x0c00
ax_pose_terminator
sFeebasPose137:
ax_pose 20, 0x01e8, 0x80f6, 0x0c00
ax_pose_terminator
sFeebasPose138:
ax_pose 21, 0x01e8, 0x80f6, 0x0c00
ax_pose_terminator
sFeebasPose139:
ax_pose 22, 0x01e6, 0x80f2, 0x0c00
ax_pose_terminator
sFeebasPose140:
ax_pose 23, 0x01e6, 0x90ec, 0x0c00
ax_pose_terminator
sFeebasPose141:
ax_pose 24, 0x01e7, 0x90f1, 0x0c00
ax_pose_terminator
sFeebasPose142:
ax_pose 25, 0x01e6, 0x90ea, 0x0c00
ax_pose_terminator
sFeebasPose143:
ax_pose 26, 0x01e5, 0x80f4, 0x0c00
ax_pose_terminator
sFeebasPose144:
ax_pose 25, 0x01e6, 0x80f6, 0x0c00
ax_pose_terminator
sFeebasPose145:
ax_pose 24, 0x01e7, 0x80ef, 0x0c00
ax_pose_terminator
sFeebasPose146:
ax_pose 23, 0x01e6, 0x80f4, 0x0c00
ax_pose_terminator
sFeebasPose147:
ax_pose 0, 0x01e9, 0x80f4, 0x0c00
ax_pose_terminator
sFeebasPose148:
ax_pose 1, 0x01e9, 0x80f4, 0x0c00
ax_pose_terminator
sFeebasPose149:
ax_pose 2, 0x01e9, 0x80f4, 0x0c00
ax_pose_terminator
sFeebasPose150:
ax_pose 3, 0x01e9, 0x90eb, 0x0c00
ax_pose_terminator
sFeebasPose151:
ax_pose 4, 0x01e9, 0x90eb, 0x0c00
ax_pose_terminator
sFeebasPose152:
ax_pose 5, 0x01e9, 0x90eb, 0x0c00
ax_pose_terminator
sFeebasPose153:
ax_pose 6, 0x01e9, 0x90f1, 0x0c00
ax_pose_terminator
sFeebasPose154:
ax_pose 7, 0x01e9, 0x90ea, 0x0c00
ax_pose_terminator
sFeebasPose155:
ax_pose 8, 0x01e9, 0x90f1, 0x0c00
ax_pose_terminator
sFeebasPose156:
ax_pose 9, 0x01e7, 0x90ec, 0x0c00
ax_pose_terminator
sFeebasPose157:
ax_pose 10, 0x01e7, 0x90ec, 0x0c00
ax_pose_terminator
sFeebasPose158:
ax_pose 11, 0x01e7, 0x90ec, 0x0c00
ax_pose_terminator
sFeebasPose159:
ax_pose 12, 0x01e7, 0x80f4, 0x0c00
ax_pose_terminator
sFeebasPose160:
ax_pose 13, 0x01e7, 0x80f4, 0x0c00
ax_pose_terminator
sFeebasPose161:
ax_pose 14, 0x01e7, 0x80f4, 0x0c00
ax_pose_terminator
sFeebasPose162:
ax_pose 9, 0x01e7, 0x80f5, 0x0c00
ax_pose_terminator
sFeebasPose163:
ax_pose 10, 0x01e7, 0x80f5, 0x0c00
ax_pose_terminator
sFeebasPose164:
ax_pose 11, 0x01e7, 0x80f5, 0x0c00
ax_pose_terminator
sFeebasPose165:
ax_pose 6, 0x01e9, 0x80f0, 0x0c00
ax_pose_terminator
sFeebasPose166:
ax_pose 7, 0x01e9, 0x80f7, 0x0c00
ax_pose_terminator
sFeebasPose167:
ax_pose 8, 0x01e9, 0x80f0, 0x0c00
ax_pose_terminator
sFeebasPose168:
ax_pose 3, 0x01e9, 0x80f6, 0x0c00
ax_pose_terminator
sFeebasPose169:
ax_pose 4, 0x01e9, 0x80f6, 0x0c00
ax_pose_terminator
sFeebasPose170:
ax_pose 5, 0x01e9, 0x80f6, 0x0c00
ax_pose_terminator
sFeebasPose171:
ax_pose 15, 0x01e9, 0x80f4, 0x0c00
ax_pose_terminator
sFeebasPose172:
ax_pose 16, 0x01e9, 0x80f6, 0x0c00
ax_pose_terminator
sFeebasPose173:
ax_pose 17, 0x01e9, 0x80f0, 0x0c00
ax_pose_terminator
sFeebasPose174:
ax_pose 18, 0x01e7, 0x80f6, 0x0c00
ax_pose_terminator
sFeebasPose175:
ax_pose 19, 0x01e7, 0x80f4, 0x0c00
ax_pose_terminator
sFeebasPose176:
ax_pose 18, 0x01e7, 0x90eb, 0x0c00
ax_pose_terminator
sFeebasPose177:
ax_pose 17, 0x01e9, 0x90f1, 0x0c00
ax_pose_terminator
sFeebasPose178:
ax_pose 16, 0x01e9, 0x90eb, 0x0c00
ax_pose_terminator
sFeebasPose179:
ax_pose 15, 0x01e9, 0x80f4, 0x0c00
ax_pose_terminator
sFeebasPose180:
ax_pose 16, 0x01e9, 0x90eb, 0x0c00
ax_pose_terminator
sFeebasPose181:
ax_pose 17, 0x01e9, 0x90f1, 0x0c00
ax_pose_terminator
sFeebasPose182:
ax_pose 18, 0x01e7, 0x90eb, 0x0c00
ax_pose_terminator
sFeebasPose183:
ax_pose 19, 0x01e7, 0x80f4, 0x0c00
ax_pose_terminator
sFeebasPose184:
ax_pose 18, 0x01e7, 0x80f6, 0x0c00
ax_pose_terminator
sFeebasPose185:
ax_pose 17, 0x01e9, 0x80f0, 0x0c00
ax_pose_terminator
sFeebasPose186:
ax_pose 16, 0x01e9, 0x80f6, 0x0c00
ax_pose_terminator
sFeebasPose187:
ax_pose 0, 0x01e9, 0x80f4, 0x0c00
ax_pose_terminator
sFeebasPose188:
ax_pose 1, 0x01e9, 0x80f4, 0x0c00
ax_pose_terminator
sFeebasPose189:
ax_pose 2, 0x01e9, 0x80f4, 0x0c00
ax_pose_terminator
sFeebasPose190:
ax_pose 3, 0x01e9, 0x90eb, 0x0c00
ax_pose_terminator
sFeebasPose191:
ax_pose 4, 0x01e9, 0x90eb, 0x0c00
ax_pose_terminator
sFeebasPose192:
ax_pose 5, 0x01e9, 0x90eb, 0x0c00
ax_pose_terminator
sFeebasPose193:
ax_pose 6, 0x01e9, 0x90f1, 0x0c00
ax_pose_terminator
sFeebasPose194:
ax_pose 7, 0x01e9, 0x90ea, 0x0c00
ax_pose_terminator
sFeebasPose195:
ax_pose 8, 0x01e9, 0x90f1, 0x0c00
ax_pose_terminator
sFeebasPose196:
ax_pose 9, 0x01e7, 0x90ec, 0x0c00
ax_pose_terminator
sFeebasPose197:
ax_pose 10, 0x01e7, 0x90ec, 0x0c00
ax_pose_terminator
sFeebasPose198:
ax_pose 11, 0x01e7, 0x90ec, 0x0c00
ax_pose_terminator
sFeebasPose199:
ax_pose 12, 0x01e7, 0x80f4, 0x0c00
ax_pose_terminator
sFeebasPose200:
ax_pose 13, 0x01e7, 0x80f4, 0x0c00
ax_pose_terminator
sFeebasPose201:
ax_pose 14, 0x01e7, 0x80f4, 0x0c00
ax_pose_terminator
sFeebasPose202:
ax_pose 9, 0x01e7, 0x80f5, 0x0c00
ax_pose_terminator
sFeebasPose203:
ax_pose 10, 0x01e7, 0x80f5, 0x0c00
ax_pose_terminator
sFeebasPose204:
ax_pose 11, 0x01e7, 0x80f5, 0x0c00
ax_pose_terminator
sFeebasPose205:
ax_pose 6, 0x01e9, 0x80f0, 0x0c00
ax_pose_terminator
sFeebasPose206:
ax_pose 7, 0x01e9, 0x80f7, 0x0c00
ax_pose_terminator
sFeebasPose207:
ax_pose 8, 0x01e9, 0x80f0, 0x0c00
ax_pose_terminator
sFeebasPose208:
ax_pose 3, 0x01e9, 0x80f6, 0x0c00
ax_pose_terminator
sFeebasPose209:
ax_pose 4, 0x01e9, 0x80f6, 0x0c00
ax_pose_terminator
sFeebasPose210:
ax_pose 5, 0x01e9, 0x80f6, 0x0c00
ax_pose_terminator
sFeebasPose211:
ax_pose 15, 0x01e9, 0x80f4, 0x0c00
ax_pose_terminator
sFeebasPose212:
ax_pose 16, 0x01e9, 0x80f6, 0x0c00
ax_pose_terminator
sFeebasPose213:
ax_pose 17, 0x01e9, 0x80f0, 0x0c00
ax_pose_terminator
sFeebasPose214:
ax_pose 18, 0x01e7, 0x80f6, 0x0c00
ax_pose_terminator
sFeebasPose215:
ax_pose 19, 0x01e7, 0x80f4, 0x0c00
ax_pose_terminator
sFeebasPose216:
ax_pose 18, 0x01e7, 0x90eb, 0x0c00
ax_pose_terminator
sFeebasPose217:
ax_pose 17, 0x01e9, 0x90f1, 0x0c00
ax_pose_terminator
sFeebasPose218:
ax_pose 16, 0x01e9, 0x90eb, 0x0c00
ax_pose_terminator
sFeebasPose219:
ax_pose 0, 0x01e9, 0x80f4, 0x0c00
ax_pose_terminator
sFeebasPose220:
ax_pose 3, 0x01e9, 0x80f6, 0x0c00
ax_pose_terminator
sFeebasPose221:
ax_pose 6, 0x01e9, 0x80f0, 0x0c00
ax_pose_terminator
sFeebasPose222:
ax_pose 9, 0x01e7, 0x80f5, 0x0c00
ax_pose_terminator
sFeebasPose223:
ax_pose 12, 0x01e7, 0x80f4, 0x0c00
ax_pose_terminator
sFeebasPose224:
ax_pose 9, 0x01e7, 0x90ec, 0x0c00
ax_pose_terminator
sFeebasPose225:
ax_pose 6, 0x01e9, 0x90f1, 0x0c00
ax_pose_terminator
sFeebasPose226:
ax_pose 3, 0x01e9, 0x90eb, 0x0c00
ax_pose_terminator
.align 2
sFeebasAnims_1_1:
ax_anim 8, 0, 0, 0, 0, 0, 0,
ax_anim 10, 0, 1, 0, -1, 0, 0,
ax_anim 8, 0, 0, 0, -2, 0, 0,
ax_anim 10, 0, 2, 0, -3, 0, 0,
ax_anim 8, 0, 0, 0, -3, 0, 0,
ax_anim 10, 0, 1, 0, -2, 0, 0,
ax_anim 8, 0, 0, 0, -1, 0, 0,
ax_anim 10, 0, 2, 0, 0, 0, 0,
ax_anim_terminator
sFeebasAnims_1_2:
ax_anim 8, 0, 3, 0, 0, 0, 0,
ax_anim 10, 0, 4, 0, -1, 0, 0,
ax_anim 8, 0, 3, 0, -2, 0, 0,
ax_anim 10, 0, 5, 0, -3, 0, 0,
ax_anim 8, 0, 3, 0, -3, 0, 0,
ax_anim 10, 0, 4, 0, -2, 0, 0,
ax_anim 8, 0, 3, 0, -1, 0, 0,
ax_anim 10, 0, 5, 0, 0, 0, 0,
ax_anim_terminator
sFeebasAnims_1_3:
ax_anim 8, 0, 6, 0, 0, 0, 0,
ax_anim 10, 0, 7, 0, -1, 0, 0,
ax_anim 8, 0, 6, 0, -2, 0, 0,
ax_anim 10, 0, 8, 0, -3, 0, 0,
ax_anim 8, 0, 6, 0, -3, 0, 0,
ax_anim 10, 0, 7, 0, -2, 0, 0,
ax_anim 8, 0, 6, 0, -1, 0, 0,
ax_anim 10, 0, 8, 0, 0, 0, 0,
ax_anim_terminator
sFeebasAnims_1_4:
ax_anim 8, 0, 9, 0, 0, 0, 0,
ax_anim 10, 0, 10, 0, -1, 0, 0,
ax_anim 8, 0, 9, 0, -2, 0, 0,
ax_anim 10, 0, 11, 0, -3, 0, 0,
ax_anim 8, 0, 9, 0, -3, 0, 0,
ax_anim 10, 0, 10, 0, -2, 0, 0,
ax_anim 8, 0, 9, 0, -1, 0, 0,
ax_anim 10, 0, 11, 0, 0, 0, 0,
ax_anim_terminator
sFeebasAnims_1_5:
ax_anim 8, 0, 12, 0, 0, 0, 0,
ax_anim 10, 0, 13, 0, -1, 0, 0,
ax_anim 8, 0, 12, 0, -2, 0, 0,
ax_anim 10, 0, 14, 0, -3, 0, 0,
ax_anim 8, 0, 12, 0, -3, 0, 0,
ax_anim 10, 0, 13, 0, -2, 0, 0,
ax_anim 8, 0, 12, 0, -1, 0, 0,
ax_anim 10, 0, 14, 0, 0, 0, 0,
ax_anim_terminator
sFeebasAnims_1_6:
ax_anim 8, 0, 15, 0, 0, 0, 0,
ax_anim 10, 0, 16, 0, -1, 0, 0,
ax_anim 8, 0, 15, 0, -2, 0, 0,
ax_anim 10, 0, 17, 0, -3, 0, 0,
ax_anim 8, 0, 15, 0, -3, 0, 0,
ax_anim 10, 0, 16, 0, -2, 0, 0,
ax_anim 8, 0, 15, 0, -1, 0, 0,
ax_anim 10, 0, 17, 0, 0, 0, 0,
ax_anim_terminator
sFeebasAnims_1_7:
ax_anim 8, 0, 18, 0, 0, 0, 0,
ax_anim 10, 0, 19, 0, -1, 0, 0,
ax_anim 8, 0, 18, 0, -2, 0, 0,
ax_anim 10, 0, 20, 0, -3, 0, 0,
ax_anim 8, 0, 18, 0, -3, 0, 0,
ax_anim 10, 0, 19, 0, -2, 0, 0,
ax_anim 8, 0, 18, 0, -1, 0, 0,
ax_anim 10, 0, 20, 0, 0, 0, 0,
ax_anim_terminator
sFeebasAnims_1_8:
ax_anim 8, 0, 21, 0, 0, 0, 0,
ax_anim 10, 0, 22, 0, -1, 0, 0,
ax_anim 8, 0, 21, 0, -2, 0, 0,
ax_anim 10, 0, 23, 0, -3, 0, 0,
ax_anim 8, 0, 21, 0, -3, 0, 0,
ax_anim 10, 0, 22, 0, -2, 0, 0,
ax_anim 8, 0, 21, 0, -1, 0, 0,
ax_anim 10, 0, 23, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sFeebasAnims_2_1:
ax_anim 2, 0, 25, 0, -1, 0, -1,
ax_anim 2, 0, 26, 0, -2, 0, -2,
ax_anim 2, 0, 25, 0, -2, 0, -2,
ax_anim 2, 0, 26, 0, -2, 0, -2,
ax_anim 2, 0, 25, 0, -2, 0, -2,
ax_anim 4, 0, 24, 0, -2, 0, -2,
ax_anim 1, 0, 24, 0, 0, 0, 0,
ax_anim 1, 2, 24, 0, 4, 0, 4,
ax_anim 1, 0, 24, 0, 10, 0, 10,
ax_anim 2, 0, 24, 0, 22, 0, 22,
ax_anim 2, 1, 24, 1, 22, 1, 22,
ax_anim 2, 0, 24, 0, 22, 0, 22,
ax_anim 2, 0, 24, 1, 22, 1, 22,
ax_anim 2, 0, 24, 0, 6, 0, 6,
ax_anim_terminator
sFeebasAnims_2_2:
ax_anim 2, 0, 28, -1, -1, -1, -1,
ax_anim 2, 0, 29, -2, -2, -2, -2,
ax_anim 2, 0, 28, -2, -2, -2, -2,
ax_anim 2, 0, 29, -2, -2, -2, -2,
ax_anim 2, 0, 28, -2, -2, -2, -2,
ax_anim 4, 0, 27, -2, -2, -2, -2,
ax_anim 1, 0, 27, 0, 0, 0, 0,
ax_anim 1, 2, 27, 4, 4, 4, 4,
ax_anim 1, 0, 27, 10, 10, 10, 10,
ax_anim 2, 0, 27, 20, 22, 20, 22,
ax_anim 2, 1, 27, 21, 21, 21, 21,
ax_anim 2, 0, 27, 20, 22, 20, 22,
ax_anim 2, 0, 27, 21, 21, 21, 21,
ax_anim 2, 0, 27, 6, 6, 6, 6,
ax_anim_terminator
sFeebasAnims_2_3:
ax_anim 2, 0, 31, -1, 0, -1, 0,
ax_anim 2, 0, 32, -2, 0, -2, 0,
ax_anim 2, 0, 31, -2, 0, -2, 0,
ax_anim 2, 0, 32, -2, 0, -2, 0,
ax_anim 2, 0, 31, -2, 0, -2, 0,
ax_anim 4, 0, 30, -2, 0, -2, 0,
ax_anim 1, 0, 30, 0, 0, 0, 0,
ax_anim 1, 2, 30, 4, 0, 4, 0,
ax_anim 1, 0, 30, 10, 0, 10, 0,
ax_anim 2, 0, 30, 18, 0, 18, 0,
ax_anim 2, 1, 30, 18, 1, 18, 1,
ax_anim 2, 0, 30, 18, 0, 18, 0,
ax_anim 2, 0, 30, 18, 1, 18, 1,
ax_anim 2, 0, 30, 6, 0, 6, 0,
ax_anim_terminator
sFeebasAnims_2_4:
ax_anim 2, 0, 34, -1, 1, -1, 1,
ax_anim 2, 0, 35, -2, 2, -2, 2,
ax_anim 2, 0, 34, -2, 2, -2, 2,
ax_anim 2, 0, 35, -2, 2, -2, 2,
ax_anim 2, 0, 34, -2, 2, -2, 2,
ax_anim 4, 0, 33, -2, 2, -2, 2,
ax_anim 1, 0, 33, 0, -1, 0, -1,
ax_anim 1, 2, 33, 4, -6, 4, -6,
ax_anim 1, 0, 33, 11, -13, 11, -13,
ax_anim 2, 0, 33, 18, -20, 18, -20,
ax_anim 2, 1, 33, 19, -19, 19, -19,
ax_anim 2, 0, 33, 18, -20, 18, -20,
ax_anim 2, 0, 33, 19, -19, 19, -19,
ax_anim 2, 0, 33, 5, -7, 5, -7,
ax_anim_terminator
sFeebasAnims_2_5:
ax_anim 2, 0, 37, 0, 1, 0, 1,
ax_anim 2, 0, 38, 0, 2, 0, 2,
ax_anim 2, 0, 37, 0, 2, 0, 2,
ax_anim 2, 0, 38, 0, 2, 0, 2,
ax_anim 2, 0, 37, 0, 2, 0, 2,
ax_anim 4, 0, 36, 0, 2, 0, 2,
ax_anim 1, 0, 36, 0, 0, 0, 0,
ax_anim 1, 2, 36, 0, -4, 0, -4,
ax_anim 1, 0, 36, 0, -9, 0, -9,
ax_anim 2, 0, 36, 0, -19, 0, -19,
ax_anim 2, 1, 36, 1, -19, 1, -19,
ax_anim 2, 0, 36, 0, -19, 0, -19,
ax_anim 2, 0, 36, 1, -19, 1, -19,
ax_anim 2, 0, 36, 0, -6, 0, -6,
ax_anim_terminator
sFeebasAnims_2_6:
ax_anim 2, 0, 40, 1, 1, 1, 1,
ax_anim 2, 0, 41, 2, 2, 2, 2,
ax_anim 2, 0, 40, 2, 2, 2, 2,
ax_anim 2, 0, 41, 2, 2, 2, 2,
ax_anim 2, 0, 40, 2, 2, 2, 2,
ax_anim 4, 0, 39, 2, 2, 2, 2,
ax_anim 1, 0, 39, 0, -1, 0, -1,
ax_anim 1, 2, 39, -4, -6, -4, -6,
ax_anim 1, 0, 39, -11, -13, -11, -13,
ax_anim 2, 0, 39, -18, -20, -18, -20,
ax_anim 2, 1, 39, -19, -19, -19, -19,
ax_anim 2, 0, 39, -18, -20, -18, -20,
ax_anim 2, 0, 39, -19, -19, -19, -19,
ax_anim 2, 0, 39, -5, -7, -5, -7,
ax_anim_terminator
sFeebasAnims_2_7:
ax_anim 2, 0, 43, 1, 0, 1, 0,
ax_anim 2, 0, 44, 2, 0, 2, 0,
ax_anim 2, 0, 43, 2, 0, 2, 0,
ax_anim 2, 0, 44, 2, 0, 2, 0,
ax_anim 2, 0, 43, 2, 0, 2, 0,
ax_anim 4, 0, 42, 2, 0, 2, 0,
ax_anim 1, 0, 42, 0, 0, 0, 0,
ax_anim 1, 2, 42, -4, 0, -4, 0,
ax_anim 1, 0, 42, -10, 0, -10, 0,
ax_anim 2, 0, 42, -18, 0, -18, 0,
ax_anim 2, 1, 42, -18, 1, -18, 1,
ax_anim 2, 0, 42, -18, 0, -18, 0,
ax_anim 2, 0, 42, -18, 1, -18, 1,
ax_anim 2, 0, 42, -6, 0, -6, 0,
ax_anim_terminator
sFeebasAnims_2_8:
ax_anim 2, 0, 46, 1, -1, 1, -1,
ax_anim 2, 0, 47, 2, -2, 2, -2,
ax_anim 2, 0, 46, 2, -2, 2, -2,
ax_anim 2, 0, 47, 2, -2, 2, -2,
ax_anim 2, 0, 46, 2, -2, 2, -2,
ax_anim 4, 0, 45, 2, -2, 2, -2,
ax_anim 1, 0, 45, 0, 0, 0, 0,
ax_anim 1, 2, 45, -4, 4, -4, 4,
ax_anim 1, 0, 45, -10, 10, -10, 10,
ax_anim 2, 0, 45, -20, 22, -20, 22,
ax_anim 2, 1, 45, -21, 21, -21, 21,
ax_anim 2, 0, 45, -20, 22, -20, 22,
ax_anim 2, 0, 45, -21, 21, -21, 21,
ax_anim 2, 0, 45, -6, 6, -6, 6,
ax_anim_terminator
.align 2
sFeebasAnims_3_1:
ax_anim 2, 0, 49, 0, -1, 0, -1,
ax_anim 2, 0, 50, 0, -2, 0, -2,
ax_anim 2, 0, 49, 0, -2, 0, -2,
ax_anim 2, 0, 50, 0, -2, 0, -2,
ax_anim 2, 0, 49, 0, -2, 0, -2,
ax_anim 4, 0, 48, 0, -2, 0, -2,
ax_anim 1, 0, 48, 0, 0, 0, 0,
ax_anim 1, 2, 48, 0, 4, 0, 4,
ax_anim 1, 0, 48, 0, 10, 0, 10,
ax_anim 2, 0, 48, 0, 22, 0, 22,
ax_anim 2, 1, 48, 1, 22, 1, 22,
ax_anim 2, 0, 48, 0, 22, 0, 22,
ax_anim 2, 0, 48, 1, 22, 1, 22,
ax_anim 2, 0, 48, 0, 6, 0, 6,
ax_anim_terminator
sFeebasAnims_3_2:
ax_anim 2, 0, 52, -1, -1, -1, -1,
ax_anim 2, 0, 53, -2, -2, -2, -2,
ax_anim 2, 0, 52, -2, -2, -2, -2,
ax_anim 2, 0, 53, -2, -2, -2, -2,
ax_anim 2, 0, 52, -2, -2, -2, -2,
ax_anim 4, 0, 51, -2, -2, -2, -2,
ax_anim 1, 0, 51, 0, 0, 0, 0,
ax_anim 1, 2, 51, 4, 4, 4, 4,
ax_anim 1, 0, 51, 10, 10, 10, 10,
ax_anim 2, 0, 51, 20, 22, 20, 22,
ax_anim 2, 1, 51, 21, 21, 21, 21,
ax_anim 2, 0, 51, 20, 22, 20, 22,
ax_anim 2, 0, 51, 21, 21, 21, 21,
ax_anim 2, 0, 51, 6, 6, 6, 6,
ax_anim_terminator
sFeebasAnims_3_3:
ax_anim 2, 0, 55, -1, 0, -1, 0,
ax_anim 2, 0, 56, -2, 0, -2, 0,
ax_anim 2, 0, 55, -2, 0, -2, 0,
ax_anim 2, 0, 56, -2, 0, -2, 0,
ax_anim 2, 0, 55, -2, 0, -2, 0,
ax_anim 4, 0, 54, -2, 0, -2, 0,
ax_anim 1, 0, 54, 0, 0, 0, 0,
ax_anim 1, 2, 54, 4, 0, 4, 0,
ax_anim 1, 0, 54, 10, 0, 10, 0,
ax_anim 2, 0, 54, 18, 0, 18, 0,
ax_anim 2, 1, 54, 18, 1, 18, 1,
ax_anim 2, 0, 54, 18, 0, 18, 0,
ax_anim 2, 0, 54, 18, 1, 18, 1,
ax_anim 2, 0, 54, 6, 0, 6, 0,
ax_anim_terminator
sFeebasAnims_3_4:
ax_anim 2, 0, 58, -1, 1, -1, 1,
ax_anim 2, 0, 59, -2, 2, -2, 2,
ax_anim 2, 0, 58, -2, 2, -2, 2,
ax_anim 2, 0, 59, -2, 2, -2, 2,
ax_anim 2, 0, 58, -2, 2, -2, 2,
ax_anim 4, 0, 57, -2, 2, -2, 2,
ax_anim 1, 0, 57, 0, -1, 0, -1,
ax_anim 1, 2, 57, 4, -6, 4, -6,
ax_anim 1, 0, 57, 11, -13, 11, -13,
ax_anim 2, 0, 57, 18, -20, 18, -20,
ax_anim 2, 1, 57, 19, -19, 19, -19,
ax_anim 2, 0, 57, 18, -20, 18, -20,
ax_anim 2, 0, 57, 19, -19, 19, -19,
ax_anim 2, 0, 57, 5, -7, 5, -7,
ax_anim_terminator
sFeebasAnims_3_5:
ax_anim 2, 0, 61, 0, 1, 0, 1,
ax_anim 2, 0, 62, 0, 2, 0, 2,
ax_anim 2, 0, 61, 0, 2, 0, 2,
ax_anim 2, 0, 62, 0, 2, 0, 2,
ax_anim 2, 0, 61, 0, 2, 0, 2,
ax_anim 4, 0, 60, 0, 2, 0, 2,
ax_anim 1, 0, 60, 0, 0, 0, 0,
ax_anim 1, 2, 60, 0, -4, 0, -4,
ax_anim 1, 0, 60, 0, -9, 0, -9,
ax_anim 2, 0, 60, 0, -19, 0, -19,
ax_anim 2, 1, 60, 1, -19, 1, -19,
ax_anim 2, 0, 60, 0, -19, 0, -19,
ax_anim 2, 0, 60, 1, -19, 1, -19,
ax_anim 2, 0, 60, 0, -6, 0, -6,
ax_anim_terminator
sFeebasAnims_3_6:
ax_anim 2, 0, 64, 1, 1, 1, 1,
ax_anim 2, 0, 65, 2, 2, 2, 2,
ax_anim 2, 0, 64, 2, 2, 2, 2,
ax_anim 2, 0, 65, 2, 2, 2, 2,
ax_anim 2, 0, 64, 2, 2, 2, 2,
ax_anim 4, 0, 63, 2, 2, 2, 2,
ax_anim 1, 0, 63, 0, -1, 0, -1,
ax_anim 1, 2, 63, -4, -6, -4, -6,
ax_anim 1, 0, 63, -11, -13, -11, -13,
ax_anim 2, 0, 63, -18, -20, -18, -20,
ax_anim 2, 1, 63, -19, -19, -19, -19,
ax_anim 2, 0, 63, -18, -20, -18, -20,
ax_anim 2, 0, 63, -19, -19, -19, -19,
ax_anim 2, 0, 63, -5, -7, -5, -7,
ax_anim_terminator
sFeebasAnims_3_7:
ax_anim 2, 0, 67, 1, 0, 1, 0,
ax_anim 2, 0, 68, 2, 0, 2, 0,
ax_anim 2, 0, 67, 2, 0, 2, 0,
ax_anim 2, 0, 68, 2, 0, 2, 0,
ax_anim 2, 0, 67, 2, 0, 2, 0,
ax_anim 4, 0, 66, 2, 0, 2, 0,
ax_anim 1, 0, 66, 0, 0, 0, 0,
ax_anim 1, 2, 66, -4, 0, -4, 0,
ax_anim 1, 0, 66, -10, 0, -10, 0,
ax_anim 2, 0, 66, -18, 0, -18, 0,
ax_anim 2, 1, 66, -18, 1, -18, 1,
ax_anim 2, 0, 66, -18, 0, -18, 0,
ax_anim 2, 0, 66, -18, 1, -18, 1,
ax_anim 2, 0, 66, -6, 0, -6, 0,
ax_anim_terminator
sFeebasAnims_3_8:
ax_anim 2, 0, 70, 1, -1, 1, -1,
ax_anim 2, 0, 71, 2, -2, 2, -2,
ax_anim 2, 0, 70, 2, -2, 2, -2,
ax_anim 2, 0, 71, 2, -2, 2, -2,
ax_anim 2, 0, 70, 2, -2, 2, -2,
ax_anim 4, 0, 69, 2, -2, 2, -2,
ax_anim 1, 0, 69, 0, 0, 0, 0,
ax_anim 1, 2, 69, -4, 4, -4, 4,
ax_anim 1, 0, 69, -10, 10, -10, 10,
ax_anim 2, 0, 69, -20, 22, -20, 22,
ax_anim 2, 1, 69, -21, 21, -21, 21,
ax_anim 2, 0, 69, -20, 22, -20, 22,
ax_anim 2, 0, 69, -21, 21, -21, 21,
ax_anim 2, 0, 69, -6, 6, -6, 6,
ax_anim_terminator
.align 2
sFeebasAnims_4_1:
ax_anim 2, 0, 73, 0, -2, 0, -2,
ax_anim 6, 2, 74, 0, -3, 0, -3,
ax_anim 2, 0, 72, 0, -1, 0, -1,
ax_anim 2, 1, 75, 0, 3, 0, 2,
ax_anim 2, 0, 75, 1, 3, 1, 2,
ax_anim 2, 0, 75, 0, 3, 0, 2,
ax_anim 2, 0, 75, 1, 3, 1, 2,
ax_anim 2, 0, 75, 0, 3, 0, 2,
ax_anim 2, 0, 75, 1, 3, 1, 2,
ax_anim 2, 0, 75, 0, 3, 0, 2,
ax_anim 2, 0, 72, 0, 1, 0, 1,
ax_anim_terminator
sFeebasAnims_4_2:
ax_anim 2, 0, 77, -2, -2, -2, -2,
ax_anim 6, 2, 78, -3, -3, -3, -3,
ax_anim 2, 0, 76, -1, -1, -1, -1,
ax_anim 2, 1, 79, 2, 2, 1, 1,
ax_anim 2, 0, 79, 3, 1, 2, 0,
ax_anim 2, 0, 79, 2, 2, 1, 1,
ax_anim 2, 0, 79, 3, 1, 2, 0,
ax_anim 2, 0, 79, 2, 2, 1, 1,
ax_anim 2, 0, 79, 3, 1, 2, 0,
ax_anim 2, 0, 79, 2, 2, 1, 1,
ax_anim 2, 0, 76, 1, 1, 1, 1,
ax_anim_terminator
sFeebasAnims_4_3:
ax_anim 2, 0, 81, -2, 0, -2, 0,
ax_anim 6, 2, 82, -3, 0, -3, 0,
ax_anim 2, 0, 80, -1, 0, -1, 0,
ax_anim 2, 1, 83, 2, 0, 2, 0,
ax_anim 2, 0, 83, 2, 1, 2, 1,
ax_anim 2, 0, 83, 2, 0, 2, 0,
ax_anim 2, 0, 83, 2, 1, 2, 1,
ax_anim 2, 0, 83, 2, 0, 2, 0,
ax_anim 2, 0, 83, 2, 1, 2, 1,
ax_anim 2, 0, 83, 2, 0, 2, 0,
ax_anim 2, 0, 80, 1, 0, 1, 0,
ax_anim_terminator
sFeebasAnims_4_4:
ax_anim 2, 0, 85, -2, 2, -2, 2,
ax_anim 6, 2, 86, -3, 3, -3, 3,
ax_anim 2, 0, 84, -1, 1, -1, 1,
ax_anim 2, 1, 87, 2, -2, 1, -1,
ax_anim 2, 0, 87, 3, -1, 2, 0,
ax_anim 2, 0, 87, 2, -2, 1, -1,
ax_anim 2, 0, 87, 3, -1, 2, 0,
ax_anim 2, 0, 87, 2, -2, 1, -1,
ax_anim 2, 0, 87, 3, -1, 2, 0,
ax_anim 2, 0, 87, 2, -2, 1, -1,
ax_anim 2, 0, 84, 1, -1, 1, -1,
ax_anim_terminator
sFeebasAnims_4_5:
ax_anim 2, 0, 89, 0, 2, 0, 2,
ax_anim 6, 2, 90, 0, 3, 0, 3,
ax_anim 2, 0, 88, 0, 1, 0, 1,
ax_anim 2, 1, 91, 0, -3, 0, -2,
ax_anim 2, 0, 91, 1, -3, 1, -2,
ax_anim 2, 0, 91, 0, -3, 0, -2,
ax_anim 2, 0, 91, 1, -3, 1, -2,
ax_anim 2, 0, 91, 0, -3, 0, -2,
ax_anim 2, 0, 91, 1, -3, 1, -2,
ax_anim 2, 0, 91, 0, -3, 0, -2,
ax_anim 2, 0, 88, 0, -1, 0, -1,
ax_anim_terminator
sFeebasAnims_4_6:
ax_anim 2, 0, 93, 2, 2, 2, 2,
ax_anim 6, 2, 94, 3, 3, 3, 3,
ax_anim 2, 0, 92, 1, 1, 1, 1,
ax_anim 2, 1, 95, -2, -2, -1, -1,
ax_anim 2, 0, 95, -3, -1, -2, 0,
ax_anim 2, 0, 95, -2, -2, -1, -1,
ax_anim 2, 0, 95, -3, -1, -2, 0,
ax_anim 2, 0, 95, -2, -2, -1, -1,
ax_anim 2, 0, 95, -3, -1, -2, 0,
ax_anim 2, 0, 95, -2, -2, -1, -1,
ax_anim 2, 0, 92, -1, -1, -1, -1,
ax_anim_terminator
sFeebasAnims_4_7:
ax_anim 2, 0, 97, 2, 0, 2, 0,
ax_anim 6, 2, 98, 3, 0, 3, 0,
ax_anim 2, 0, 96, 1, 0, 1, 0,
ax_anim 2, 1, 99, -2, 0, -2, 0,
ax_anim 2, 0, 99, -2, 1, -2, 1,
ax_anim 2, 0, 99, -2, 0, -2, 0,
ax_anim 2, 0, 99, -2, 1, -2, 1,
ax_anim 2, 0, 99, -2, 0, -2, 0,
ax_anim 2, 0, 99, -2, 1, -2, 1,
ax_anim 2, 0, 99, -2, 0, -2, 0,
ax_anim 2, 0, 96, -1, 0, -1, 0,
ax_anim_terminator
sFeebasAnims_4_8:
ax_anim 2, 0, 101, 2, -2, 2, -2,
ax_anim 6, 2, 102, 3, -3, 3, -3,
ax_anim 2, 0, 100, 1, -1, 1, -1,
ax_anim 2, 1, 103, -2, 2, -1, 1,
ax_anim 2, 0, 103, -3, 1, -2, 0,
ax_anim 2, 0, 103, -2, 2, -1, 1,
ax_anim 2, 0, 103, -3, 1, -2, 0,
ax_anim 2, 0, 103, -2, 2, -1, 1,
ax_anim 2, 0, 103, -3, 1, -2, 0,
ax_anim 2, 0, 103, -2, 2, -1, 1,
ax_anim 2, 0, 100, -1, 1, -1, 1,
ax_anim_terminator
.align 2
sFeebasAnims_5_1:
ax_anim 2, 0, 105, 0, 0, 0, 0,
ax_anim 4, 0, 110, 0, 0, 0, 0,
ax_anim 4, 0, 105, 0, 0, 0, 0,
ax_anim 2, 2, 133, 0, 0, 0, 0,
ax_anim 2, 0, 134, 0, 0, 0, 0,
ax_anim 2, 0, 106, 0, 0, 0, 0,
ax_anim 2, 0, 105, 0, 0, 0, 0,
ax_anim 4, 0, 110, 0, 0, 0, 0,
ax_anim 4, 0, 105, 0, 0, 0, 0,
ax_anim 2, 0, 133, 0, 0, 0, 0,
ax_anim 2, 1, 134, 0, 0, 0, 0,
ax_anim 2, 0, 106, 0, 0, 0, 0,
ax_anim_terminator
sFeebasAnims_5_2:
ax_anim 2, 0, 109, 0, 0, 0, 0,
ax_anim 4, 0, 114, 0, 0, 0, 0,
ax_anim 4, 0, 109, 0, 0, 0, 0,
ax_anim 2, 2, 105, 0, 0, 0, 0,
ax_anim 2, 0, 106, 0, 0, 0, 0,
ax_anim 2, 0, 110, 0, 0, 0, 0,
ax_anim 2, 0, 109, 0, 0, 0, 0,
ax_anim 4, 0, 114, 0, 0, 0, 0,
ax_anim 4, 0, 109, 0, 0, 0, 0,
ax_anim 2, 0, 105, 0, 0, 0, 0,
ax_anim 2, 1, 106, 0, 0, 0, 0,
ax_anim 2, 0, 110, 0, 0, 0, 0,
ax_anim_terminator
sFeebasAnims_5_3:
ax_anim 2, 0, 113, 0, 0, 0, 0,
ax_anim 4, 0, 118, 0, 0, 0, 0,
ax_anim 4, 0, 113, 0, 0, 0, 0,
ax_anim 2, 2, 109, 0, 0, 0, 0,
ax_anim 2, 0, 110, 0, 0, 0, 0,
ax_anim 2, 0, 114, 0, 0, 0, 0,
ax_anim 2, 0, 113, 0, 0, 0, 0,
ax_anim 4, 0, 118, 0, 0, 0, 0,
ax_anim 4, 0, 113, 0, 0, 0, 0,
ax_anim 2, 0, 109, 0, 0, 0, 0,
ax_anim 2, 1, 110, 0, 0, 0, 0,
ax_anim 2, 0, 114, 0, 0, 0, 0,
ax_anim_terminator
sFeebasAnims_5_4:
ax_anim 2, 0, 117, 0, 0, 0, 0,
ax_anim 4, 0, 122, 0, 0, 0, 0,
ax_anim 4, 0, 117, 0, 0, 0, 0,
ax_anim 2, 2, 113, 0, 0, 0, 0,
ax_anim 2, 0, 114, 0, 0, 0, 0,
ax_anim 2, 0, 118, 0, 0, 0, 0,
ax_anim 2, 0, 117, 0, 0, 0, 0,
ax_anim 4, 0, 122, 0, 0, 0, 0,
ax_anim 4, 0, 117, 0, 0, 0, 0,
ax_anim 2, 0, 113, 0, 0, 0, 0,
ax_anim 2, 1, 114, 0, 0, 0, 0,
ax_anim 2, 0, 118, 0, 0, 0, 0,
ax_anim_terminator
sFeebasAnims_5_5:
ax_anim 2, 0, 121, 0, 0, 0, 0,
ax_anim 4, 0, 126, 0, 0, 0, 0,
ax_anim 4, 0, 121, 0, 0, 0, 0,
ax_anim 2, 2, 117, 0, 0, 0, 0,
ax_anim 2, 0, 118, 0, 0, 0, 0,
ax_anim 2, 0, 122, 0, 0, 0, 0,
ax_anim 2, 0, 121, 0, 0, 0, 0,
ax_anim 4, 0, 126, 0, 0, 0, 0,
ax_anim 4, 0, 121, 0, 0, 0, 0,
ax_anim 2, 0, 117, 0, 0, 0, 0,
ax_anim 2, 1, 118, 0, 0, 0, 0,
ax_anim 2, 0, 122, 0, 0, 0, 0,
ax_anim_terminator
sFeebasAnims_5_6:
ax_anim 2, 0, 125, 0, 0, 0, 0,
ax_anim 4, 0, 130, 0, 0, 0, 0,
ax_anim 4, 0, 125, 0, 0, 0, 0,
ax_anim 2, 2, 121, 0, 0, 0, 0,
ax_anim 2, 0, 122, 0, 0, 0, 0,
ax_anim 2, 0, 126, 0, 0, 0, 0,
ax_anim 2, 0, 125, 0, 0, 0, 0,
ax_anim 4, 0, 130, 0, 0, 0, 0,
ax_anim 4, 0, 125, 0, 0, 0, 0,
ax_anim 2, 0, 121, 0, 0, 0, 0,
ax_anim 2, 1, 122, 0, 0, 0, 0,
ax_anim 2, 0, 126, 0, 0, 0, 0,
ax_anim_terminator
sFeebasAnims_5_7:
ax_anim 2, 0, 129, 0, 0, 0, 0,
ax_anim 4, 0, 134, 0, 0, 0, 0,
ax_anim 4, 0, 129, 0, 0, 0, 0,
ax_anim 2, 2, 125, 0, 0, 0, 0,
ax_anim 2, 0, 126, 0, 0, 0, 0,
ax_anim 2, 0, 130, 0, 0, 0, 0,
ax_anim 2, 0, 129, 0, 0, 0, 0,
ax_anim 4, 0, 134, 0, 0, 0, 0,
ax_anim 4, 0, 129, 0, 0, 0, 0,
ax_anim 2, 0, 125, 0, 0, 0, 0,
ax_anim 2, 1, 126, 0, 0, 0, 0,
ax_anim 2, 0, 130, 0, 0, 0, 0,
ax_anim_terminator
sFeebasAnims_5_8:
ax_anim 2, 0, 133, 0, 0, 0, 0,
ax_anim 4, 0, 106, 0, 0, 0, 0,
ax_anim 4, 0, 133, 0, 0, 0, 0,
ax_anim 2, 2, 129, 0, 0, 0, 0,
ax_anim 2, 0, 130, 0, 0, 0, 0,
ax_anim 2, 0, 134, 0, 0, 0, 0,
ax_anim 2, 0, 133, 0, 0, 0, 0,
ax_anim 4, 0, 106, 0, 0, 0, 0,
ax_anim 4, 0, 133, 0, 0, 0, 0,
ax_anim 2, 0, 129, 0, 0, 0, 0,
ax_anim 2, 1, 130, 0, 0, 0, 0,
ax_anim 2, 0, 134, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sFeebasAnims_6_1:
ax_anim 16, 0, 136, 0, 0, 0, 0,
ax_anim 12, 0, 136, 0, -1, 0, 0,
ax_anim 16, 0, 136, 0, -2, 0, 0,
ax_anim 16, 0, 137, 0, -2, 0, 0,
ax_anim 12, 0, 137, 0, -1, 0, 0,
ax_anim 16, 0, 137, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sFeebasAnims_7_1:
ax_anim 2, 0, 138, 0, -4, 0, -4,
ax_anim 8, 0, 138, 0, -5, 0, -5,
ax_anim_terminator
sFeebasAnims_7_2:
ax_anim 2, 0, 139, -4, -4, -4, -4,
ax_anim 8, 0, 139, -5, -5, -5, -5,
ax_anim_terminator
sFeebasAnims_7_3:
ax_anim 2, 0, 140, -4, 0, -4, 0,
ax_anim 8, 0, 140, -5, 0, -5, 0,
ax_anim_terminator
sFeebasAnims_7_4:
ax_anim 2, 0, 141, -4, 4, -4, 4,
ax_anim 8, 0, 141, -5, 5, -5, 5,
ax_anim_terminator
sFeebasAnims_7_5:
ax_anim 2, 0, 142, 0, 4, 0, 4,
ax_anim 8, 0, 142, 0, 5, 0, 5,
ax_anim_terminator
sFeebasAnims_7_6:
ax_anim 2, 0, 143, 4, 4, 4, 4,
ax_anim 8, 0, 143, 5, 5, 5, 5,
ax_anim_terminator
sFeebasAnims_7_7:
ax_anim 2, 0, 144, 4, 0, 4, 0,
ax_anim 8, 0, 144, 5, 0, 5, 0,
ax_anim_terminator
sFeebasAnims_7_8:
ax_anim 2, 0, 145, 4, -4, 4, -4,
ax_anim 8, 0, 145, 5, -5, 5, -5,
ax_anim_terminator
.align 2
sFeebasAnims_8_1:
ax_anim 12, 0, 146, 0, 0, 0, 0,
ax_anim 14, 0, 147, 0, 0, 0, 0,
ax_anim 12, 0, 146, 0, 0, 0, 0,
ax_anim 14, 0, 148, 0, 0, 0, 0,
ax_anim_terminator
sFeebasAnims_8_2:
ax_anim 12, 0, 149, 0, 0, 0, 0,
ax_anim 14, 0, 150, 0, 0, 0, 0,
ax_anim 12, 0, 149, 0, 0, 0, 0,
ax_anim 14, 0, 151, 0, 0, 0, 0,
ax_anim_terminator
sFeebasAnims_8_3:
ax_anim 12, 0, 152, 0, 0, 0, 0,
ax_anim 14, 0, 153, 0, 0, 0, 0,
ax_anim 12, 0, 152, 0, 0, 0, 0,
ax_anim 14, 0, 154, 0, 0, 0, 0,
ax_anim_terminator
sFeebasAnims_8_4:
ax_anim 12, 0, 155, 0, 0, 0, 0,
ax_anim 14, 0, 156, 0, 0, 0, 0,
ax_anim 12, 0, 155, 0, 0, 0, 0,
ax_anim 14, 0, 157, 0, 0, 0, 0,
ax_anim_terminator
sFeebasAnims_8_5:
ax_anim 12, 0, 158, 0, 0, 0, 0,
ax_anim 14, 0, 159, 0, 0, 0, 0,
ax_anim 12, 0, 158, 0, 0, 0, 0,
ax_anim 14, 0, 160, 0, 0, 0, 0,
ax_anim_terminator
sFeebasAnims_8_6:
ax_anim 12, 0, 161, 0, 0, 0, 0,
ax_anim 14, 0, 162, 0, 0, 0, 0,
ax_anim 12, 0, 161, 0, 0, 0, 0,
ax_anim 14, 0, 163, 0, 0, 0, 0,
ax_anim_terminator
sFeebasAnims_8_7:
ax_anim 12, 0, 164, 0, 0, 0, 0,
ax_anim 14, 0, 165, 0, 0, 0, 0,
ax_anim 12, 0, 164, 0, 0, 0, 0,
ax_anim 14, 0, 166, 0, 0, 0, 0,
ax_anim_terminator
sFeebasAnims_8_8:
ax_anim 12, 0, 167, 0, 0, 0, 0,
ax_anim 14, 0, 168, 0, 0, 0, 0,
ax_anim 12, 0, 167, 0, 0, 0, 0,
ax_anim 14, 0, 169, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sFeebasAnims_9_1:
ax_anim 2, 0, 170, 0, 0, 0, 0,
ax_anim 1, 0, 171, 6, 3, 6, 3,
ax_anim 2, 0, 172, 8, 9, 8, 9,
ax_anim 2, 0, 173, 7, 15, 7, 15,
ax_anim 3, 0, 174, 0, 18, 0, 18,
ax_anim 2, 3, 175, -7, 15, -7, 15,
ax_anim 2, 0, 176, -8, 9, -8, 9,
ax_anim 1, 0, 177, -6, 3, -6, 3,
ax_anim 1, 0, 170, 0, 0, 0, 0,
ax_anim_terminator
sFeebasAnims_9_2:
ax_anim 2, 0, 177, 0, 0, 0, 0,
ax_anim 1, 0, 170, 8, 0, 8, 0,
ax_anim 2, 0, 171, 17, 3, 17, 3,
ax_anim 2, 0, 172, 19, 10, 19, 10,
ax_anim 3, 0, 173, 17, 19, 17, 19,
ax_anim 2, 3, 174, 11, 19, 11, 19,
ax_anim 2, 0, 175, 3, 15, 3, 15,
ax_anim 1, 0, 176, 0, 7, 0, 7,
ax_anim 1, 0, 177, 0, 0, 0, 0,
ax_anim_terminator
sFeebasAnims_9_3:
ax_anim 2, 0, 176, 0, 0, 0, 0,
ax_anim 1, 0, 177, 3, -5, 3, -5,
ax_anim 2, 0, 170, 11, -6, 11, -6,
ax_anim 2, 0, 171, 17, -3, 17, -3,
ax_anim 3, 0, 172, 18, 1, 18, 1,
ax_anim 2, 3, 173, 17, 7, 17, 7,
ax_anim 2, 0, 174, 12, 8, 12, 8,
ax_anim 1, 0, 175, 4, 5, 4, 5,
ax_anim 1, 0, 176, 0, 0, 0, 0,
ax_anim_terminator
sFeebasAnims_9_4:
ax_anim 2, 0, 175, 0, 0, 0, 0,
ax_anim 1, 0, 176, -1, -8, -1, -8,
ax_anim 2, 0, 177, 4, -16, 4, -16,
ax_anim 2, 0, 170, 12, -21, 12, -21,
ax_anim 3, 0, 171, 18, -19, 18, -19,
ax_anim 2, 3, 172, 20, -13, 20, -13,
ax_anim 2, 0, 173, 16, -5, 16, -5,
ax_anim 1, 0, 174, 7, -1, 7, -1,
ax_anim 1, 0, 175, 0, 0, 0, 0,
ax_anim_terminator
sFeebasAnims_9_5:
ax_anim 2, 0, 174, 0, 0, 0, 0,
ax_anim 1, 0, 175, -8, -4, -8, -4,
ax_anim 2, 0, 176, -9, -12, -9, -12,
ax_anim 2, 0, 177, -7, -18, -7, -18,
ax_anim 3, 0, 170, 0, -20, 0, -20,
ax_anim 2, 3, 171, 7, -18, 7, -18,
ax_anim 2, 0, 172, 9, -12, 9, -12,
ax_anim 1, 0, 173, 8, -4, 8, -4,
ax_anim 1, 0, 174, 0, 0, 0, 0,
ax_anim_terminator
sFeebasAnims_9_6:
ax_anim 2, 0, 173, 0, 0, 0, 0,
ax_anim 1, 0, 172, 1, -8, 1, -8,
ax_anim 2, 0, 171, -4, -16, -4, -16,
ax_anim 2, 0, 170, -12, -21, -12, -21,
ax_anim 3, 0, 177, -18, -19, -18, -19,
ax_anim 2, 3, 176, -20, -13, -20, -13,
ax_anim 2, 0, 175, -16, -5, -16, -5,
ax_anim 1, 0, 174, -7, -1, -7, -1,
ax_anim 1, 0, 173, 0, 0, 0, 0,
ax_anim_terminator
sFeebasAnims_9_7:
ax_anim 2, 0, 172, 0, 0, 0, 0,
ax_anim 1, 0, 171, -3, -5, -3, -5,
ax_anim 2, 0, 170, -11, -6, -11, -6,
ax_anim 2, 0, 177, -17, -3, -17, -3,
ax_anim 3, 0, 176, -18, -1, -18, -1,
ax_anim 2, 3, 175, -17, 7, -17, 7,
ax_anim 2, 0, 174, -12, 8, -12, 8,
ax_anim 1, 0, 173, -4, 5, -4, 5,
ax_anim 1, 0, 172, 0, 0, 0, 0,
ax_anim_terminator
sFeebasAnims_9_8:
ax_anim 2, 0, 171, 0, 0, 0, 0,
ax_anim 1, 0, 170, -8, 0, -8, 0,
ax_anim 2, 0, 177, -17, 3, -17, 3,
ax_anim 2, 0, 176, -19, 10, -19, 10,
ax_anim 3, 0, 175, -17, 19, -17, 19,
ax_anim 2, 3, 174, -11, 19, -11, 19,
ax_anim 2, 0, 173, -3, 15, -3, 15,
ax_anim 1, 0, 172, 0, 7, 0, 7,
ax_anim 1, 0, 171, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sFeebasAnims_10_1:
ax_anim 2, 0, 178, 0, 0, 0, 0,
ax_anim 2, 0, 178, 6, 0, 6, 0,
ax_anim 2, 0, 178, -6, 0, -6, 0,
ax_anim 2, 0, 178, 10, 0, 10, 0,
ax_anim 2, 0, 178, -10, 0, -10, 0,
ax_anim 2, 0, 178, 12, 0, 12, 0,
ax_anim 3, 0, 178, -12, 0, -12, 0,
ax_anim 3, 0, 178, 13, 0, 13, 0,
ax_anim 3, 0, 178, -13, 0, -13, 0,
ax_anim 2, 0, 178, 12, 0, 12, 0,
ax_anim 3, 0, 178, -12, 0, -12, 0,
ax_anim 2, 0, 178, 10, 0, 10, 0,
ax_anim 2, 0, 178, -10, 0, -10, 0,
ax_anim 2, 0, 178, 6, 0, 6, 0,
ax_anim 2, 0, 178, -6, 0, -6, 0,
ax_anim 2, 0, 178, 0, 0, 0, 0,
ax_anim_terminator
sFeebasAnims_10_2:
ax_anim 2, 0, 179, 0, 0, 0, 0,
ax_anim 2, 0, 179, 6, -6, 6, -6,
ax_anim 2, 0, 179, -6, 6, -6, 6,
ax_anim 2, 0, 179, 10, -10, 10, -10,
ax_anim 2, 0, 179, -10, 10, -10, 10,
ax_anim 2, 0, 179, 12, -12, 12, -12,
ax_anim 3, 0, 179, -12, 12, -12, 12,
ax_anim 3, 0, 179, 13, -13, 13, -13,
ax_anim 3, 0, 179, -13, 13, -13, 13,
ax_anim 2, 0, 179, 12, -12, 12, -12,
ax_anim 3, 0, 179, -12, 12, -12, 12,
ax_anim 2, 0, 179, 10, -10, 10, -10,
ax_anim 2, 0, 179, -10, 10, -10, 10,
ax_anim 2, 0, 179, 6, -6, 6, -6,
ax_anim 2, 0, 179, -6, 6, -6, 6,
ax_anim 2, 0, 179, 0, 0, 0, 0,
ax_anim_terminator
sFeebasAnims_10_3:
ax_anim 2, 0, 180, 0, 0, 0, 0,
ax_anim 2, 0, 180, 0, -6, 0, -6,
ax_anim 2, 0, 180, 0, 6, 0, 6,
ax_anim 2, 0, 180, 0, -10, 0, -10,
ax_anim 2, 0, 180, 0, 10, 0, 10,
ax_anim 2, 0, 180, 0, -12, 0, -12,
ax_anim 3, 0, 180, 0, 12, 0, 12,
ax_anim 3, 0, 180, 0, -13, 0, -13,
ax_anim 3, 0, 180, 0, 13, 0, 13,
ax_anim 2, 0, 180, 0, -12, 0, -12,
ax_anim 3, 0, 180, 0, 12, 0, 12,
ax_anim 2, 0, 180, 0, -10, 0, -10,
ax_anim 2, 0, 180, 0, 10, 0, 10,
ax_anim 2, 0, 180, 0, -6, 0, -6,
ax_anim 2, 0, 180, 0, 6, 0, 6,
ax_anim 2, 0, 180, 0, 0, 0, 0,
ax_anim_terminator
sFeebasAnims_10_4:
ax_anim 2, 0, 181, 0, 0, 0, 0,
ax_anim 2, 0, 181, -6, -6, -6, -6,
ax_anim 2, 0, 181, 6, 6, 6, 6,
ax_anim 2, 0, 181, -10, -10, -10, -10,
ax_anim 2, 0, 181, 10, 10, 10, 10,
ax_anim 2, 0, 181, -12, -12, -12, -12,
ax_anim 3, 0, 181, 12, 12, 12, 12,
ax_anim 3, 0, 181, -13, -13, -13, -13,
ax_anim 3, 0, 181, 13, 13, 13, 13,
ax_anim 2, 0, 181, -12, -12, -12, -12,
ax_anim 3, 0, 181, 12, 12, 12, 12,
ax_anim 2, 0, 181, -10, -10, -10, -10,
ax_anim 2, 0, 181, 10, 10, 10, 10,
ax_anim 2, 0, 181, -6, -6, -6, -6,
ax_anim 2, 0, 181, 6, 6, 6, 6,
ax_anim 2, 0, 181, 0, 0, 0, 0,
ax_anim_terminator
sFeebasAnims_10_5:
ax_anim 2, 0, 182, 0, 0, 0, 0,
ax_anim 2, 0, 182, 6, 0, 6, 0,
ax_anim 2, 0, 182, -6, 0, -6, 0,
ax_anim 2, 0, 182, 10, 0, 10, 0,
ax_anim 2, 0, 182, -10, 0, -10, 0,
ax_anim 2, 0, 182, 12, 0, 12, 0,
ax_anim 3, 0, 182, -12, 0, -12, 0,
ax_anim 3, 0, 182, 13, 0, 13, 0,
ax_anim 3, 0, 182, -13, 0, -13, 0,
ax_anim 2, 0, 182, 12, 0, 12, 0,
ax_anim 3, 0, 182, -12, 0, -12, 0,
ax_anim 2, 0, 182, 10, 0, 10, 0,
ax_anim 2, 0, 182, -10, 0, -10, 0,
ax_anim 2, 0, 182, 6, 0, 6, 0,
ax_anim 2, 0, 182, -6, 0, -6, 0,
ax_anim 2, 0, 182, 0, 0, 0, 0,
ax_anim_terminator
sFeebasAnims_10_6:
ax_anim 2, 0, 183, 0, 0, 0, 0,
ax_anim 2, 0, 183, 6, -6, 6, -6,
ax_anim 2, 0, 183, -6, 6, -6, 6,
ax_anim 2, 0, 183, 10, -10, 10, -10,
ax_anim 2, 0, 183, -10, 10, -10, 10,
ax_anim 2, 0, 183, 12, -12, 12, -12,
ax_anim 3, 0, 183, -12, 12, -12, 12,
ax_anim 3, 0, 183, 13, -13, 13, -13,
ax_anim 3, 0, 183, -13, 13, -13, 13,
ax_anim 2, 0, 183, 12, -12, 12, -12,
ax_anim 3, 0, 183, -12, 12, -12, 12,
ax_anim 2, 0, 183, 10, -10, 10, -10,
ax_anim 2, 0, 183, -10, 10, -10, 10,
ax_anim 2, 0, 183, 6, -6, 6, -6,
ax_anim 2, 0, 183, -6, 6, -6, 6,
ax_anim 2, 0, 183, 0, 0, 0, 0,
ax_anim_terminator
sFeebasAnims_10_7:
ax_anim 2, 0, 184, 0, 0, 0, 0,
ax_anim 2, 0, 184, 0, -6, 0, -6,
ax_anim 2, 0, 184, 0, 6, 0, 6,
ax_anim 2, 0, 184, 0, -10, 0, -10,
ax_anim 2, 0, 184, 0, 10, 0, 10,
ax_anim 2, 0, 184, 0, -12, 0, -12,
ax_anim 3, 0, 184, 0, 12, 0, 12,
ax_anim 3, 0, 184, 0, -13, 0, -13,
ax_anim 3, 0, 184, 0, 13, 0, 13,
ax_anim 2, 0, 184, 0, -12, 0, -12,
ax_anim 3, 0, 184, 0, 12, 0, 12,
ax_anim 2, 0, 184, 0, -10, 0, -10,
ax_anim 2, 0, 184, 0, 10, 0, 10,
ax_anim 2, 0, 184, 0, -6, 0, -6,
ax_anim 2, 0, 184, 0, 6, 0, 6,
ax_anim 2, 0, 184, 0, 0, 0, 0,
ax_anim_terminator
sFeebasAnims_10_8:
ax_anim 2, 0, 185, 0, 0, 0, 0,
ax_anim 2, 0, 185, -6, -6, -6, -6,
ax_anim 2, 0, 185, 6, 6, 6, 6,
ax_anim 2, 0, 185, -10, -10, -10, -10,
ax_anim 2, 0, 185, 10, 10, 10, 10,
ax_anim 2, 0, 185, -12, -12, -12, -12,
ax_anim 3, 0, 185, 12, 12, 12, 12,
ax_anim 3, 0, 185, -13, -13, -13, -13,
ax_anim 3, 0, 185, 13, 13, 13, 13,
ax_anim 2, 0, 185, -12, -12, -12, -12,
ax_anim 3, 0, 185, 12, 12, 12, 12,
ax_anim 2, 0, 185, -10, -10, -10, -10,
ax_anim 2, 0, 185, 10, 10, 10, 10,
ax_anim 2, 0, 185, -6, -6, -6, -6,
ax_anim 2, 0, 185, 6, 6, 6, 6,
ax_anim 2, 0, 185, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sFeebasAnims_11_1:
ax_anim 2, 0, 186, 0, 0, 0, 0,
ax_anim 1, 0, 187, 0, -10, 0, 0,
ax_anim 2, 0, 187, 0, -16, 0, 0,
ax_anim 3, 0, 187, 0, -20, 0, 0,
ax_anim 4, 0, 187, 0, -21, 0, 0,
ax_anim 4, 0, 186, 0, -22, 0, 0,
ax_anim 3, 0, 188, 0, -21, 0, 0,
ax_anim 2, 0, 188, 0, -18, 0, 0,
ax_anim 1, 0, 188, 0, -12, 0, 0,
ax_anim 2, 2, 186, 0, 3, 0, 0,
ax_anim_terminator
sFeebasAnims_11_2:
ax_anim 2, 0, 189, 0, 0, 0, 0,
ax_anim 1, 0, 190, 0, -10, 0, 0,
ax_anim 2, 0, 190, 0, -16, 0, 0,
ax_anim 3, 0, 190, 0, -20, 0, 0,
ax_anim 4, 0, 190, 0, -21, 0, 0,
ax_anim 4, 0, 189, 0, -22, 0, 0,
ax_anim 3, 0, 191, 0, -21, 0, 0,
ax_anim 2, 0, 191, 0, -18, 0, 0,
ax_anim 1, 0, 191, 0, -12, 0, 0,
ax_anim 2, 2, 189, 0, 3, 0, 0,
ax_anim_terminator
sFeebasAnims_11_3:
ax_anim 2, 0, 192, 0, 0, 0, 0,
ax_anim 1, 0, 193, 0, -10, 0, 0,
ax_anim 2, 0, 193, 0, -16, 0, 0,
ax_anim 3, 0, 193, 0, -20, 0, 0,
ax_anim 4, 0, 193, 0, -21, 0, 0,
ax_anim 4, 0, 192, 0, -22, 0, 0,
ax_anim 3, 0, 194, 0, -21, 0, 0,
ax_anim 2, 0, 194, 0, -18, 0, 0,
ax_anim 1, 0, 194, 0, -12, 0, 0,
ax_anim 2, 2, 192, 0, 4, 0, 0,
ax_anim_terminator
sFeebasAnims_11_4:
ax_anim 2, 0, 195, 0, 0, 0, 0,
ax_anim 1, 0, 196, 0, -10, 0, 0,
ax_anim 2, 0, 196, 0, -16, 0, 0,
ax_anim 3, 0, 196, 0, -20, 0, 0,
ax_anim 4, 0, 196, 0, -21, 0, 0,
ax_anim 4, 0, 195, 0, -22, 0, 0,
ax_anim 3, 0, 197, 0, -21, 0, 0,
ax_anim 2, 0, 197, 0, -17, 0, 0,
ax_anim 1, 0, 197, 0, -11, 0, 0,
ax_anim 2, 2, 195, 0, 4, 0, 0,
ax_anim_terminator
sFeebasAnims_11_5:
ax_anim 2, 0, 198, 0, 0, 0, 0,
ax_anim 1, 0, 199, 0, -10, 0, 0,
ax_anim 2, 0, 199, 0, -16, 0, 0,
ax_anim 3, 0, 199, 0, -20, 0, 0,
ax_anim 4, 0, 199, 0, -21, 0, 0,
ax_anim 4, 0, 198, 0, -22, 0, 0,
ax_anim 3, 0, 200, 0, -21, 0, 0,
ax_anim 2, 0, 200, 0, -18, 0, 0,
ax_anim 1, 0, 200, 0, -12, 0, 0,
ax_anim 2, 2, 198, 0, 4, 0, 0,
ax_anim_terminator
sFeebasAnims_11_6:
ax_anim 2, 0, 201, 0, 0, 0, 0,
ax_anim 1, 0, 202, 0, -10, 0, 0,
ax_anim 2, 0, 202, 0, -16, 0, 0,
ax_anim 3, 0, 202, 0, -20, 0, 0,
ax_anim 4, 0, 202, 0, -21, 0, 0,
ax_anim 4, 0, 201, 0, -22, 0, 0,
ax_anim 3, 0, 203, 0, -21, 0, 0,
ax_anim 2, 0, 203, 0, -17, 0, 0,
ax_anim 1, 0, 203, 0, -11, 0, 0,
ax_anim 2, 2, 201, 0, 4, 0, 0,
ax_anim_terminator
sFeebasAnims_11_7:
ax_anim 2, 0, 204, 0, 0, 0, 0,
ax_anim 1, 0, 205, 0, -10, 0, 0,
ax_anim 2, 0, 205, 0, -16, 0, 0,
ax_anim 3, 0, 205, 0, -20, 0, 0,
ax_anim 4, 0, 205, 0, -21, 0, 0,
ax_anim 4, 0, 204, 0, -22, 0, 0,
ax_anim 3, 0, 206, 0, -21, 0, 0,
ax_anim 2, 0, 206, 0, -18, 0, 0,
ax_anim 1, 0, 206, 0, -12, 0, 0,
ax_anim 2, 2, 204, 0, 4, 0, 0,
ax_anim_terminator
sFeebasAnims_11_8:
ax_anim 2, 0, 207, 0, 0, 0, 0,
ax_anim 1, 0, 208, 0, -10, 0, 0,
ax_anim 2, 0, 208, 0, -16, 0, 0,
ax_anim 3, 0, 208, 0, -20, 0, 0,
ax_anim 4, 0, 208, 0, -21, 0, 0,
ax_anim 4, 0, 207, 0, -22, 0, 0,
ax_anim 3, 0, 209, 0, -21, 0, 0,
ax_anim 2, 0, 209, 0, -18, 0, 0,
ax_anim 1, 0, 209, 0, -12, 0, 0,
ax_anim 2, 2, 207, 0, 3, 0, 0,
ax_anim_terminator
.align 2
sFeebasAnims_12_1:
ax_anim 2, 0, 210, 1, 0, 1, 0,
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 2, 0, 210, 1, 0, 1, 0,
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 2, 0, 210, 1, 0, 1, 0,
ax_anim 2, 2, 210, 0, 0, 0, 0,
ax_anim 2, 0, 210, 1, 0, 1, 0,
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 2, 0, 210, 1, 0, 1, 0,
ax_anim 2, 1, 210, 0, 0, 0, 0,
ax_anim_terminator
sFeebasAnims_12_2:
ax_anim 2, 0, 217, 1, -1, 1, -1,
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 0, 217, 1, -1, 1, -1,
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 0, 217, 1, -1, 1, -1,
ax_anim 2, 2, 217, 0, 0, 0, 0,
ax_anim 2, 0, 217, 1, -1, 1, -1,
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 0, 217, 1, -1, 1, -1,
ax_anim 2, 1, 217, 0, 0, 0, 0,
ax_anim_terminator
sFeebasAnims_12_3:
ax_anim 2, 0, 216, 0, -1, 0, -1,
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, -1, 0, -1,
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, -1, 0, -1,
ax_anim 2, 2, 216, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, -1, 0, -1,
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, -1, 0, -1,
ax_anim 2, 1, 216, 0, 0, 0, 0,
ax_anim_terminator
sFeebasAnims_12_4:
ax_anim 2, 0, 215, -1, -1, -1, -1,
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 0, 215, -1, -1, -1, -1,
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 0, 215, -1, -1, -1, -1,
ax_anim 2, 2, 215, 0, 0, 0, 0,
ax_anim 2, 0, 215, -1, -1, -1, -1,
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 0, 215, -1, -1, -1, -1,
ax_anim 2, 1, 215, 0, 0, 0, 0,
ax_anim_terminator
sFeebasAnims_12_5:
ax_anim 2, 0, 214, 1, 0, 1, 0,
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 2, 0, 214, 1, 0, 1, 0,
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 2, 0, 214, 1, 0, 1, 0,
ax_anim 2, 2, 214, 0, 0, 0, 0,
ax_anim 2, 0, 214, 1, 0, 1, 0,
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 2, 0, 214, 1, 0, 1, 0,
ax_anim 2, 1, 214, 0, 0, 0, 0,
ax_anim_terminator
sFeebasAnims_12_6:
ax_anim 2, 0, 213, 1, -1, 1, -1,
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 2, 0, 213, 1, -1, 1, -1,
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 2, 0, 213, 1, -1, 1, -1,
ax_anim 2, 2, 213, 0, 0, 0, 0,
ax_anim 2, 0, 213, 1, -1, 1, -1,
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 2, 0, 213, 1, -1, 1, -1,
ax_anim 2, 1, 213, 0, 0, 0, 0,
ax_anim_terminator
sFeebasAnims_12_7:
ax_anim 2, 0, 212, 0, -1, 0, -1,
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 2, 0, 212, 0, -1, 0, -1,
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 2, 0, 212, 0, -1, 0, -1,
ax_anim 2, 2, 212, 0, 0, 0, 0,
ax_anim 2, 0, 212, 0, -1, 0, -1,
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 2, 0, 212, 0, -1, 0, -1,
ax_anim 2, 1, 212, 0, 0, 0, 0,
ax_anim_terminator
sFeebasAnims_12_8:
ax_anim 2, 0, 211, -1, -1, -1, -1,
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 2, 0, 211, -1, -1, -1, -1,
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 2, 0, 211, -1, -1, -1, -1,
ax_anim 2, 2, 211, 0, 0, 0, 0,
ax_anim 2, 0, 211, -1, -1, -1, -1,
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 2, 0, 211, -1, -1, -1, -1,
ax_anim 2, 1, 211, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sFeebasAnims_13_1:
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 2, 2, 218, 0, 0, 0, 0,
ax_anim_terminator
sFeebasAnims_13_2:
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 2, 2, 225, 0, 0, 0, 0,
ax_anim_terminator
sFeebasAnims_13_3:
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 2, 2, 224, 0, 0, 0, 0,
ax_anim_terminator
sFeebasAnims_13_4:
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 2, 223, 0, 0, 0, 0,
ax_anim_terminator
sFeebasAnims_13_5:
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 2, 222, 0, 0, 0, 0,
ax_anim_terminator
sFeebasAnims_13_6:
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 2, 221, 0, 0, 0, 0,
ax_anim_terminator
sFeebasAnims_13_7:
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 2, 220, 0, 0, 0, 0,
ax_anim_terminator
sFeebasAnims_13_8:
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 2, 219, 0, 0, 0, 0,
ax_anim_terminator
sFeebasGfx1:
.incbin "baserom.gba", 0x143E068, 0x200
sFeebasSprites1:
ax_sprite sFeebasGfx1, 0x200
ax_sprite_terminator
sFeebasGfx2:
.incbin "baserom.gba", 0x143E278, 0x200
sFeebasSprites2:
ax_sprite sFeebasGfx2, 0x200
ax_sprite_terminator
sFeebasGfx3:
.incbin "baserom.gba", 0x143E488, 0x200
sFeebasSprites3:
ax_sprite sFeebasGfx3, 0x200
ax_sprite_terminator
sFeebasGfx4:
.incbin "baserom.gba", 0x143E698, 0x200
sFeebasSprites4:
ax_sprite sFeebasGfx4, 0x200
ax_sprite_terminator
sFeebasGfx5:
.incbin "baserom.gba", 0x143E8A8, 0x200
sFeebasSprites5:
ax_sprite sFeebasGfx5, 0x200
ax_sprite_terminator
sFeebasGfx6:
.incbin "baserom.gba", 0x143EAB8, 0x200
sFeebasSprites6:
ax_sprite sFeebasGfx6, 0x200
ax_sprite_terminator
sFeebasGfx7:
.incbin "baserom.gba", 0x143ECC8, 0x200
sFeebasSprites7:
ax_sprite sFeebasGfx7, 0x200
ax_sprite_terminator
sFeebasGfx8:
.incbin "baserom.gba", 0x143EED8, 0x200
sFeebasSprites8:
ax_sprite sFeebasGfx8, 0x200
ax_sprite_terminator
sFeebasGfx9:
.incbin "baserom.gba", 0x143F0E8, 0x200
sFeebasSprites9:
ax_sprite sFeebasGfx9, 0x200
ax_sprite_terminator
sFeebasGfx10:
.incbin "baserom.gba", 0x143F2F8, 0x200
sFeebasSprites10:
ax_sprite sFeebasGfx10, 0x200
ax_sprite_terminator
sFeebasGfx11:
.incbin "baserom.gba", 0x143F508, 0x200
sFeebasSprites11:
ax_sprite sFeebasGfx11, 0x200
ax_sprite_terminator
sFeebasGfx12:
.incbin "baserom.gba", 0x143F718, 0x200
sFeebasSprites12:
ax_sprite sFeebasGfx12, 0x200
ax_sprite_terminator
sFeebasGfx13:
.incbin "baserom.gba", 0x143F928, 0x200
sFeebasSprites13:
ax_sprite sFeebasGfx13, 0x200
ax_sprite_terminator
sFeebasGfx14:
.incbin "baserom.gba", 0x143FB38, 0x200
sFeebasSprites14:
ax_sprite sFeebasGfx14, 0x200
ax_sprite_terminator
sFeebasGfx15:
.incbin "baserom.gba", 0x143FD48, 0x200
sFeebasSprites15:
ax_sprite sFeebasGfx15, 0x200
ax_sprite_terminator
sFeebasGfx16:
.incbin "baserom.gba", 0x143FF58, 0x40
sFeebasGfx16_1:
.incbin "baserom.gba", 0x143FF98, 0x60
sFeebasGfx16_2:
.incbin "baserom.gba", 0x143FFF8, 0x60
sFeebasGfx16_3:
.incbin "baserom.gba", 0x1440058, 0x20
sFeebasSprites16:
ax_sprite 0, 0x20
ax_sprite sFeebasGfx16, 0x40
ax_sprite 0, 0x20
ax_sprite sFeebasGfx16_1, 0x60
ax_sprite 0, 0x20
ax_sprite sFeebasGfx16_2, 0x60
ax_sprite 0, 0x40
ax_sprite sFeebasGfx16_3, 0x20
ax_sprite 0, 0x40
ax_sprite_terminator
sFeebasGfx17:
.incbin "baserom.gba", 0x14400C8, 0x40
sFeebasGfx17_1:
.incbin "baserom.gba", 0x1440108, 0x60
sFeebasGfx17_2:
.incbin "baserom.gba", 0x1440168, 0x60
sFeebasSprites17:
ax_sprite 0, 0x20
ax_sprite sFeebasGfx17, 0x40
ax_sprite 0, 0x20
ax_sprite sFeebasGfx17_1, 0x60
ax_sprite 0, 0x20
ax_sprite sFeebasGfx17_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sFeebasGfx18:
.incbin "baserom.gba", 0x1440208, 0x160
sFeebasSprites18:
ax_sprite 0, 0x20
ax_sprite sFeebasGfx18, 0x160
ax_sprite 0, 0x80
ax_sprite_terminator
sFeebasGfx19:
.incbin "baserom.gba", 0x1440388, 0x20
sFeebasGfx19_1:
.incbin "baserom.gba", 0x14403A8, 0x60
sFeebasGfx19_2:
.incbin "baserom.gba", 0x1440408, 0x60
sFeebasGfx19_3:
.incbin "baserom.gba", 0x1440468, 0x20
sFeebasGfx19_4:
.incbin "baserom.gba", 0x1440488, 0x20
sFeebasSprites19:
ax_sprite 0, 0x20
ax_sprite sFeebasGfx19, 0x20
ax_sprite 0, 0x40
ax_sprite sFeebasGfx19_1, 0x60
ax_sprite 0, 0x20
ax_sprite sFeebasGfx19_2, 0x60
ax_sprite 0, 0x20
ax_sprite sFeebasGfx19_3, 0x20
ax_sprite 0, 0x20
ax_sprite sFeebasGfx19_4, 0x20
ax_sprite 0, 0x20
ax_sprite_terminator
sFeebasGfx20:
.incbin "baserom.gba", 0x1440508, 0x20
sFeebasGfx20_1:
.incbin "baserom.gba", 0x1440528, 0x60
sFeebasGfx20_2:
.incbin "baserom.gba", 0x1440588, 0x60
sFeebasGfx20_3:
.incbin "baserom.gba", 0x14405E8, 0x20
sFeebasSprites20:
ax_sprite 0, 0x20
ax_sprite sFeebasGfx20, 0x20
ax_sprite 0, 0x40
ax_sprite sFeebasGfx20_1, 0x60
ax_sprite 0, 0x20
ax_sprite sFeebasGfx20_2, 0x60
ax_sprite 0, 0x40
ax_sprite sFeebasGfx20_3, 0x20
ax_sprite 0, 0x40
ax_sprite_terminator
sFeebasGfx21:
.incbin "baserom.gba", 0x1440658, 0x200
sFeebasSprites21:
ax_sprite sFeebasGfx21, 0x200
ax_sprite_terminator
sFeebasGfx22:
.incbin "baserom.gba", 0x1440868, 0x200
sFeebasSprites22:
ax_sprite sFeebasGfx22, 0x200
ax_sprite_terminator
sFeebasGfx23:
.incbin "baserom.gba", 0x1440A78, 0x200
sFeebasSprites23:
ax_sprite sFeebasGfx23, 0x200
ax_sprite_terminator
sFeebasGfx24:
.incbin "baserom.gba", 0x1440C88, 0x200
sFeebasSprites24:
ax_sprite sFeebasGfx24, 0x200
ax_sprite_terminator
sFeebasGfx25:
.incbin "baserom.gba", 0x1440E98, 0x200
sFeebasSprites25:
ax_sprite sFeebasGfx25, 0x200
ax_sprite_terminator
sFeebasGfx26:
.incbin "baserom.gba", 0x14410A8, 0x200
sFeebasSprites26:
ax_sprite sFeebasGfx26, 0x200
ax_sprite_terminator
sFeebasGfx27:
.incbin "baserom.gba", 0x14412B8, 0x200
sFeebasSprites27:
ax_sprite sFeebasGfx27, 0x200
ax_sprite_terminator
sAxPosesFeebas:
.4byte sFeebasPose1
.4byte sFeebasPose2
.4byte sFeebasPose3
.4byte sFeebasPose4
.4byte sFeebasPose5
.4byte sFeebasPose6
.4byte sFeebasPose7
.4byte sFeebasPose8
.4byte sFeebasPose9
.4byte sFeebasPose10
.4byte sFeebasPose11
.4byte sFeebasPose12
.4byte sFeebasPose13
.4byte sFeebasPose14
.4byte sFeebasPose15
.4byte sFeebasPose16
.4byte sFeebasPose17
.4byte sFeebasPose18
.4byte sFeebasPose19
.4byte sFeebasPose20
.4byte sFeebasPose21
.4byte sFeebasPose22
.4byte sFeebasPose23
.4byte sFeebasPose24
.4byte sFeebasPose25
.4byte sFeebasPose26
.4byte sFeebasPose27
.4byte sFeebasPose28
.4byte sFeebasPose29
.4byte sFeebasPose30
.4byte sFeebasPose31
.4byte sFeebasPose32
.4byte sFeebasPose33
.4byte sFeebasPose34
.4byte sFeebasPose35
.4byte sFeebasPose36
.4byte sFeebasPose37
.4byte sFeebasPose38
.4byte sFeebasPose39
.4byte sFeebasPose40
.4byte sFeebasPose41
.4byte sFeebasPose42
.4byte sFeebasPose43
.4byte sFeebasPose44
.4byte sFeebasPose45
.4byte sFeebasPose46
.4byte sFeebasPose47
.4byte sFeebasPose48
.4byte sFeebasPose49
.4byte sFeebasPose50
.4byte sFeebasPose51
.4byte sFeebasPose52
.4byte sFeebasPose53
.4byte sFeebasPose54
.4byte sFeebasPose55
.4byte sFeebasPose56
.4byte sFeebasPose57
.4byte sFeebasPose58
.4byte sFeebasPose59
.4byte sFeebasPose60
.4byte sFeebasPose61
.4byte sFeebasPose62
.4byte sFeebasPose63
.4byte sFeebasPose64
.4byte sFeebasPose65
.4byte sFeebasPose66
.4byte sFeebasPose67
.4byte sFeebasPose68
.4byte sFeebasPose69
.4byte sFeebasPose70
.4byte sFeebasPose71
.4byte sFeebasPose72
.4byte sFeebasPose73
.4byte sFeebasPose74
.4byte sFeebasPose75
.4byte sFeebasPose76
.4byte sFeebasPose77
.4byte sFeebasPose78
.4byte sFeebasPose79
.4byte sFeebasPose80
.4byte sFeebasPose81
.4byte sFeebasPose82
.4byte sFeebasPose83
.4byte sFeebasPose84
.4byte sFeebasPose85
.4byte sFeebasPose86
.4byte sFeebasPose87
.4byte sFeebasPose88
.4byte sFeebasPose89
.4byte sFeebasPose90
.4byte sFeebasPose91
.4byte sFeebasPose92
.4byte sFeebasPose93
.4byte sFeebasPose94
.4byte sFeebasPose95
.4byte sFeebasPose96
.4byte sFeebasPose97
.4byte sFeebasPose98
.4byte sFeebasPose99
.4byte sFeebasPose100
.4byte sFeebasPose101
.4byte sFeebasPose102
.4byte sFeebasPose103
.4byte sFeebasPose104
.4byte sFeebasPose105
.4byte sFeebasPose106
.4byte sFeebasPose107
.4byte sFeebasPose108
.4byte sFeebasPose109
.4byte sFeebasPose110
.4byte sFeebasPose111
.4byte sFeebasPose112
.4byte sFeebasPose113
.4byte sFeebasPose114
.4byte sFeebasPose115
.4byte sFeebasPose116
.4byte sFeebasPose117
.4byte sFeebasPose118
.4byte sFeebasPose119
.4byte sFeebasPose120
.4byte sFeebasPose121
.4byte sFeebasPose122
.4byte sFeebasPose123
.4byte sFeebasPose124
.4byte sFeebasPose125
.4byte sFeebasPose126
.4byte sFeebasPose127
.4byte sFeebasPose128
.4byte sFeebasPose129
.4byte sFeebasPose130
.4byte sFeebasPose131
.4byte sFeebasPose132
.4byte sFeebasPose133
.4byte sFeebasPose134
.4byte sFeebasPose135
.4byte sFeebasPose136
.4byte sFeebasPose137
.4byte sFeebasPose138
.4byte sFeebasPose139
.4byte sFeebasPose140
.4byte sFeebasPose141
.4byte sFeebasPose142
.4byte sFeebasPose143
.4byte sFeebasPose144
.4byte sFeebasPose145
.4byte sFeebasPose146
.4byte sFeebasPose147
.4byte sFeebasPose148
.4byte sFeebasPose149
.4byte sFeebasPose150
.4byte sFeebasPose151
.4byte sFeebasPose152
.4byte sFeebasPose153
.4byte sFeebasPose154
.4byte sFeebasPose155
.4byte sFeebasPose156
.4byte sFeebasPose157
.4byte sFeebasPose158
.4byte sFeebasPose159
.4byte sFeebasPose160
.4byte sFeebasPose161
.4byte sFeebasPose162
.4byte sFeebasPose163
.4byte sFeebasPose164
.4byte sFeebasPose165
.4byte sFeebasPose166
.4byte sFeebasPose167
.4byte sFeebasPose168
.4byte sFeebasPose169
.4byte sFeebasPose170
.4byte sFeebasPose171
.4byte sFeebasPose172
.4byte sFeebasPose173
.4byte sFeebasPose174
.4byte sFeebasPose175
.4byte sFeebasPose176
.4byte sFeebasPose177
.4byte sFeebasPose178
.4byte sFeebasPose179
.4byte sFeebasPose180
.4byte sFeebasPose181
.4byte sFeebasPose182
.4byte sFeebasPose183
.4byte sFeebasPose184
.4byte sFeebasPose185
.4byte sFeebasPose186
.4byte sFeebasPose187
.4byte sFeebasPose188
.4byte sFeebasPose189
.4byte sFeebasPose190
.4byte sFeebasPose191
.4byte sFeebasPose192
.4byte sFeebasPose193
.4byte sFeebasPose194
.4byte sFeebasPose195
.4byte sFeebasPose196
.4byte sFeebasPose197
.4byte sFeebasPose198
.4byte sFeebasPose199
.4byte sFeebasPose200
.4byte sFeebasPose201
.4byte sFeebasPose202
.4byte sFeebasPose203
.4byte sFeebasPose204
.4byte sFeebasPose205
.4byte sFeebasPose206
.4byte sFeebasPose207
.4byte sFeebasPose208
.4byte sFeebasPose209
.4byte sFeebasPose210
.4byte sFeebasPose211
.4byte sFeebasPose212
.4byte sFeebasPose213
.4byte sFeebasPose214
.4byte sFeebasPose215
.4byte sFeebasPose216
.4byte sFeebasPose217
.4byte sFeebasPose218
.4byte sFeebasPose219
.4byte sFeebasPose220
.4byte sFeebasPose221
.4byte sFeebasPose222
.4byte sFeebasPose223
.4byte sFeebasPose224
.4byte sFeebasPose225
.4byte sFeebasPose226
sAxPositionsFeebas:
.2byte    0,   -2, 	  -6,   -5, 	   6,   -5, 	   0,   -9
.2byte    1,   -2, 	  -6,   -6, 	   6,   -6, 	   1,   -9
.2byte   -1,   -2, 	  -6,   -4, 	   6,   -4, 	   0,   -9
.2byte    5,   -3, 	   3,   -7, 	  -5,   -4, 	  -1,   -9
.2byte    4,   -3, 	   3,   -8, 	  -5,   -4, 	  -2,   -9
.2byte    5,   -3, 	   4,   -6, 	  -4,   -3, 	  -1,   -9
.2byte    9,   -6, 	  -1,   -8, 	  -1,   -3, 	   0,  -10
.2byte    8,   -5, 	  -1,   -8, 	  -2,   -3, 	   0,   -9
.2byte    9,   -6, 	   0,   -8, 	   1,   -3, 	   0,   -9
.2byte    8,  -10, 	  -2,   -5, 	   6,   -4, 	   2,  -10
.2byte    8,   -9, 	  -2,   -7, 	   5,   -4, 	   2,  -10
.2byte    9,  -10, 	  -1,   -8, 	   7,   -4, 	   2,  -10
.2byte    0,  -13, 	   7,   -6, 	  -6,   -6, 	   0,  -11
.2byte    0,  -13, 	   7,   -5, 	  -6,   -6, 	   0,  -11
.2byte    1,  -13, 	   7,   -7, 	  -7,   -7, 	   1,  -11
.2byte   -8,  -10, 	   2,   -5, 	  -6,   -4, 	  -2,  -10
.2byte   -8,   -9, 	   2,   -7, 	  -5,   -4, 	  -2,  -10
.2byte   -9,  -10, 	   1,   -8, 	  -7,   -4, 	  -2,  -10
.2byte   -9,   -6, 	   1,   -8, 	   1,   -3, 	   0,  -10
.2byte   -8,   -5, 	   1,   -8, 	   2,   -3, 	   0,   -9
.2byte   -9,   -6, 	   0,   -8, 	  -1,   -3, 	   0,   -9
.2byte   -5,   -3, 	  -3,   -7, 	   5,   -4, 	   1,   -9
.2byte   -4,   -3, 	  -3,   -8, 	   5,   -4, 	   2,   -9
.2byte   -5,   -3, 	  -4,   -6, 	   4,   -3, 	   1,   -9
.2byte    0,   -2, 	  -6,   -5, 	   6,   -5, 	   0,   -9
.2byte    1,   -2, 	  -6,   -6, 	   6,   -6, 	   1,   -9
.2byte   -1,   -2, 	  -6,   -4, 	   6,   -4, 	   0,   -9
.2byte    5,   -3, 	   3,   -7, 	  -5,   -4, 	  -1,   -9
.2byte    4,   -3, 	   3,   -8, 	  -5,   -4, 	  -2,   -9
.2byte    5,   -3, 	   4,   -6, 	  -4,   -3, 	  -1,   -9
.2byte    9,   -6, 	  -1,   -8, 	  -1,   -3, 	   0,  -10
.2byte    8,   -5, 	  -1,   -8, 	  -2,   -3, 	   0,   -9
.2byte    9,   -6, 	   0,   -8, 	   1,   -3, 	   0,   -9
.2byte    8,  -10, 	  -2,   -5, 	   6,   -4, 	   2,  -10
.2byte    8,   -9, 	  -2,   -7, 	   5,   -4, 	   2,  -10
.2byte    9,  -10, 	  -1,   -8, 	   7,   -4, 	   2,  -10
.2byte    0,  -13, 	   7,   -6, 	  -6,   -6, 	   0,  -11
.2byte    0,  -13, 	   7,   -5, 	  -6,   -6, 	   0,  -11
.2byte    1,  -13, 	   7,   -7, 	  -7,   -7, 	   1,  -11
.2byte   -8,  -10, 	   2,   -5, 	  -6,   -4, 	  -2,  -10
.2byte   -8,   -9, 	   2,   -7, 	  -5,   -4, 	  -2,  -10
.2byte   -9,  -10, 	   1,   -8, 	  -7,   -4, 	  -2,  -10
.2byte   -9,   -6, 	   1,   -8, 	   1,   -3, 	   0,  -10
.2byte   -8,   -5, 	   1,   -8, 	   2,   -3, 	   0,   -9
.2byte   -9,   -6, 	   0,   -8, 	  -1,   -3, 	   0,   -9
.2byte   -5,   -3, 	  -3,   -7, 	   5,   -4, 	   1,   -9
.2byte   -4,   -3, 	  -3,   -8, 	   5,   -4, 	   2,   -9
.2byte   -5,   -3, 	  -4,   -6, 	   4,   -3, 	   1,   -9
.2byte    0,   -2, 	  -6,   -5, 	   6,   -5, 	   0,   -9
.2byte    1,   -2, 	  -6,   -6, 	   6,   -6, 	   1,   -9
.2byte   -1,   -2, 	  -6,   -4, 	   6,   -4, 	   0,   -9
.2byte    5,   -3, 	   3,   -7, 	  -5,   -4, 	  -1,   -9
.2byte    4,   -3, 	   3,   -8, 	  -5,   -4, 	  -2,   -9
.2byte    5,   -3, 	   4,   -6, 	  -4,   -3, 	  -1,   -9
.2byte    9,   -6, 	  -1,   -8, 	  -1,   -3, 	   0,  -10
.2byte    8,   -5, 	  -1,   -8, 	  -2,   -3, 	   0,   -9
.2byte    9,   -6, 	   0,   -8, 	   1,   -3, 	   0,   -9
.2byte    8,  -10, 	  -2,   -5, 	   6,   -4, 	   2,  -10
.2byte    8,   -9, 	  -2,   -7, 	   5,   -4, 	   2,  -10
.2byte    9,  -10, 	  -1,   -8, 	   7,   -4, 	   2,  -10
.2byte    0,  -13, 	   7,   -6, 	  -6,   -6, 	   0,  -11
.2byte    0,  -13, 	   7,   -5, 	  -6,   -6, 	   0,  -11
.2byte    1,  -13, 	   7,   -7, 	  -7,   -7, 	   1,  -11
.2byte   -8,  -10, 	   2,   -5, 	  -6,   -4, 	  -2,  -10
.2byte   -8,   -9, 	   2,   -7, 	  -5,   -4, 	  -2,  -10
.2byte   -9,  -10, 	   1,   -8, 	  -7,   -4, 	  -2,  -10
.2byte   -9,   -6, 	   1,   -8, 	   1,   -3, 	   0,  -10
.2byte   -8,   -5, 	   1,   -8, 	   2,   -3, 	   0,   -9
.2byte   -9,   -6, 	   0,   -8, 	  -1,   -3, 	   0,   -9
.2byte   -5,   -3, 	  -3,   -7, 	   5,   -4, 	   1,   -9
.2byte   -4,   -3, 	  -3,   -8, 	   5,   -4, 	   2,   -9
.2byte   -5,   -3, 	  -4,   -6, 	   4,   -3, 	   1,   -9
.2byte    0,   -2, 	  -6,   -5, 	   6,   -5, 	   0,   -9
.2byte    1,   -2, 	  -6,   -6, 	   6,   -6, 	   1,   -9
.2byte   -1,   -2, 	  -6,   -4, 	   6,   -4, 	   0,   -9
.2byte    0,   -3, 	  -6,   -5, 	   6,   -5, 	   0,   -9
.2byte    5,   -3, 	   3,   -7, 	  -5,   -4, 	  -1,   -9
.2byte    4,   -3, 	   3,   -8, 	  -5,   -4, 	  -2,   -9
.2byte    5,   -3, 	   4,   -6, 	  -4,   -3, 	  -1,   -9
.2byte    5,   -4, 	   3,   -7, 	  -5,   -4, 	   0,   -9
.2byte    9,   -6, 	  -1,   -8, 	  -1,   -3, 	   0,  -10
.2byte    8,   -5, 	  -1,   -8, 	  -2,   -3, 	   0,   -9
.2byte    9,   -6, 	   0,   -8, 	   1,   -3, 	   0,   -9
.2byte    8,   -6, 	  -2,   -8, 	  -2,   -3, 	   0,  -10
.2byte    8,  -10, 	  -2,   -5, 	   6,   -4, 	   2,  -10
.2byte    8,   -9, 	  -2,   -7, 	   5,   -4, 	   2,  -10
.2byte    9,  -10, 	  -1,   -8, 	   7,   -4, 	   2,  -10
.2byte    8,   -9, 	  -2,   -8, 	   5,   -4, 	   1,  -10
.2byte    0,  -13, 	   7,   -6, 	  -6,   -6, 	   0,  -11
.2byte    0,  -13, 	   7,   -5, 	  -6,   -6, 	   0,  -11
.2byte    1,  -13, 	   7,   -7, 	  -7,   -7, 	   1,  -11
.2byte    0,  -13, 	   6,   -6, 	  -6,   -6, 	   0,  -10
.2byte   -8,  -10, 	   2,   -5, 	  -6,   -4, 	  -2,  -10
.2byte   -8,   -9, 	   2,   -7, 	  -5,   -4, 	  -2,  -10
.2byte   -9,  -10, 	   1,   -8, 	  -7,   -4, 	  -2,  -10
.2byte   -8,   -9, 	   2,   -8, 	  -5,   -4, 	  -1,  -10
.2byte   -9,   -6, 	   1,   -8, 	   1,   -3, 	   0,  -10
.2byte   -8,   -5, 	   1,   -8, 	   2,   -3, 	   0,   -9
.2byte   -9,   -6, 	   0,   -8, 	  -1,   -3, 	   0,   -9
.2byte   -8,   -6, 	   2,   -8, 	   2,   -3, 	   0,  -10
.2byte   -5,   -3, 	  -3,   -7, 	   5,   -4, 	   1,   -9
.2byte   -4,   -3, 	  -3,   -8, 	   5,   -4, 	   2,   -9
.2byte   -5,   -3, 	  -4,   -6, 	   4,   -3, 	   1,   -9
.2byte   -5,   -4, 	  -3,   -7, 	   5,   -4, 	   0,   -9
.2byte    0,   -2, 	  -6,   -5, 	   6,   -5, 	   0,   -9
.2byte    1,   -2, 	  -6,   -6, 	   6,   -6, 	   1,   -9
.2byte   -1,   -2, 	  -6,   -4, 	   6,   -4, 	   0,   -9
.2byte    0,   -3, 	  -6,   -5, 	   6,   -5, 	   0,   -9
.2byte    5,   -3, 	   3,   -7, 	  -5,   -4, 	  -1,   -9
.2byte    5,   -3, 	   4,   -6, 	  -4,   -3, 	  -1,   -9
.2byte    4,   -3, 	   3,   -8, 	  -5,   -4, 	  -2,   -9
.2byte    5,   -4, 	   3,   -7, 	  -5,   -4, 	   0,   -9
.2byte    9,   -6, 	  -1,   -8, 	  -1,   -3, 	   0,  -10
.2byte    9,   -6, 	   0,   -8, 	   1,   -3, 	   0,   -9
.2byte    8,   -5, 	  -1,   -8, 	  -2,   -3, 	   0,   -9
.2byte    8,   -6, 	  -2,   -8, 	  -2,   -3, 	   0,  -10
.2byte    8,  -10, 	  -2,   -5, 	   6,   -4, 	   2,  -10
.2byte    8,  -10, 	  -2,   -8, 	   6,   -4, 	   1,  -10
.2byte    8,   -9, 	  -2,   -7, 	   5,   -4, 	   2,  -10
.2byte    8,   -9, 	  -2,   -8, 	   5,   -4, 	   1,  -10
.2byte    0,  -13, 	   7,   -6, 	  -6,   -6, 	   0,  -11
.2byte    0,  -13, 	   7,   -5, 	  -6,   -6, 	   0,  -11
.2byte    1,  -13, 	   7,   -7, 	  -7,   -7, 	   1,  -11
.2byte    0,  -13, 	   6,   -6, 	  -6,   -6, 	   0,  -10
.2byte   -8,  -10, 	   2,   -5, 	  -6,   -4, 	  -2,  -10
.2byte   -8,   -9, 	   2,   -7, 	  -5,   -4, 	  -2,  -10
.2byte   -9,  -10, 	   1,   -8, 	  -7,   -4, 	  -2,  -10
.2byte   -8,   -9, 	   2,   -8, 	  -5,   -4, 	  -1,  -10
.2byte   -9,   -6, 	   1,   -8, 	   1,   -3, 	   0,  -10
.2byte   -8,   -5, 	   1,   -8, 	   2,   -3, 	   0,   -9
.2byte   -9,   -6, 	   0,   -8, 	  -1,   -3, 	   0,   -9
.2byte   -8,   -6, 	   2,   -8, 	   2,   -3, 	   0,  -10
.2byte   -5,   -3, 	  -3,   -7, 	   5,   -4, 	   1,   -9
.2byte   -4,   -3, 	  -3,   -8, 	   5,   -4, 	   2,   -9
.2byte   -5,   -3, 	  -4,   -6, 	   4,   -3, 	   1,   -9
.2byte   -5,   -4, 	  -3,   -7, 	   5,   -4, 	   0,   -9
.2byte   -5,   -4, 	  -2,  -10, 	   5,   -6, 	   1,  -10
.2byte   -5,   -3, 	  -2,   -9, 	   6,   -6, 	   1,   -9
.2byte   -1,   -1, 	  -5,   -5, 	   6,   -4, 	   0,   -9
.2byte    3,   -2, 	   2,   -8, 	  -7,   -7, 	  -1,   -8
.2byte    8,   -3, 	   0,   -9, 	  -2,   -4, 	   0,   -7
.2byte    7,   -5, 	  -3,   -7, 	   3,   -3, 	   0,   -8
.2byte   -1,   -8, 	   7,   -9, 	  -7,   -6, 	   0,   -8
.2byte   -8,   -5, 	   2,   -7, 	  -4,   -3, 	  -1,   -8
.2byte   -9,   -3, 	  -1,   -9, 	   1,   -4, 	  -1,   -7
.2byte   -4,   -2, 	  -3,   -8, 	   6,   -7, 	   0,   -8
.2byte    0,   -2, 	  -6,   -5, 	   6,   -5, 	   0,   -9
.2byte    1,   -2, 	  -6,   -6, 	   6,   -6, 	   1,   -9
.2byte   -1,   -2, 	  -6,   -4, 	   6,   -4, 	   0,   -9
.2byte    5,   -3, 	   3,   -7, 	  -5,   -4, 	  -1,   -9
.2byte    4,   -3, 	   3,   -8, 	  -5,   -4, 	  -2,   -9
.2byte    5,   -3, 	   4,   -6, 	  -4,   -3, 	  -1,   -9
.2byte    9,   -6, 	  -1,   -8, 	  -1,   -3, 	   0,  -10
.2byte    8,   -5, 	  -1,   -8, 	  -2,   -3, 	   0,   -9
.2byte    9,   -6, 	   0,   -8, 	   1,   -3, 	   0,   -9
.2byte    8,  -10, 	  -2,   -5, 	   6,   -4, 	   2,  -10
.2byte    8,   -9, 	  -2,   -7, 	   5,   -4, 	   2,  -10
.2byte    9,  -10, 	  -1,   -8, 	   7,   -4, 	   2,  -10
.2byte    0,  -13, 	   7,   -6, 	  -6,   -6, 	   0,  -11
.2byte    0,  -13, 	   7,   -5, 	  -6,   -6, 	   0,  -11
.2byte    1,  -13, 	   7,   -7, 	  -7,   -7, 	   1,  -11
.2byte   -8,  -10, 	   2,   -5, 	  -6,   -4, 	  -2,  -10
.2byte   -8,   -9, 	   2,   -7, 	  -5,   -4, 	  -2,  -10
.2byte   -9,  -10, 	   1,   -8, 	  -7,   -4, 	  -2,  -10
.2byte   -9,   -6, 	   1,   -8, 	   1,   -3, 	   0,  -10
.2byte   -8,   -5, 	   1,   -8, 	   2,   -3, 	   0,   -9
.2byte   -9,   -6, 	   0,   -8, 	  -1,   -3, 	   0,   -9
.2byte   -5,   -3, 	  -3,   -7, 	   5,   -4, 	   1,   -9
.2byte   -4,   -3, 	  -3,   -8, 	   5,   -4, 	   2,   -9
.2byte   -5,   -3, 	  -4,   -6, 	   4,   -3, 	   1,   -9
.2byte    0,   -3, 	  -6,   -5, 	   6,   -5, 	   0,   -9
.2byte   -5,   -4, 	  -3,   -7, 	   5,   -4, 	   0,   -9
.2byte   -8,   -6, 	   2,   -8, 	   2,   -3, 	   0,  -10
.2byte   -7,   -9, 	   3,   -8, 	  -4,   -4, 	   0,  -10
.2byte    0,  -13, 	   6,   -6, 	  -6,   -6, 	   0,  -10
.2byte    7,   -9, 	  -3,   -8, 	   4,   -4, 	   0,  -10
.2byte    8,   -6, 	  -2,   -8, 	  -2,   -3, 	   0,  -10
.2byte    5,   -4, 	   3,   -7, 	  -5,   -4, 	   0,   -9
.2byte    0,   -3, 	  -6,   -5, 	   6,   -5, 	   0,   -9
.2byte    5,   -4, 	   3,   -7, 	  -5,   -4, 	   0,   -9
.2byte    8,   -6, 	  -2,   -8, 	  -2,   -3, 	   0,  -10
.2byte    7,   -9, 	  -3,   -8, 	   4,   -4, 	   0,  -10
.2byte    0,  -13, 	   6,   -6, 	  -6,   -6, 	   0,  -10
.2byte   -7,   -9, 	   3,   -8, 	  -4,   -4, 	   0,  -10
.2byte   -8,   -6, 	   2,   -8, 	   2,   -3, 	   0,  -10
.2byte   -5,   -4, 	  -3,   -7, 	   5,   -4, 	   0,   -9
.2byte    0,   -2, 	  -6,   -5, 	   6,   -5, 	   0,   -9
.2byte    1,   -2, 	  -6,   -6, 	   6,   -6, 	   1,   -9
.2byte   -1,   -2, 	  -6,   -4, 	   6,   -4, 	   0,   -9
.2byte    5,   -3, 	   3,   -7, 	  -5,   -4, 	  -1,   -9
.2byte    4,   -3, 	   3,   -8, 	  -5,   -4, 	  -2,   -9
.2byte    5,   -3, 	   4,   -6, 	  -4,   -3, 	  -1,   -9
.2byte    9,   -6, 	  -1,   -8, 	  -1,   -3, 	   0,  -10
.2byte    8,   -5, 	  -1,   -8, 	  -2,   -3, 	   0,   -9
.2byte    9,   -6, 	   0,   -8, 	   1,   -3, 	   0,   -9
.2byte    8,  -10, 	  -2,   -5, 	   6,   -4, 	   2,  -10
.2byte    8,   -9, 	  -2,   -7, 	   5,   -4, 	   2,  -10
.2byte    9,  -10, 	  -1,   -8, 	   7,   -4, 	   2,  -10
.2byte    0,  -13, 	   7,   -6, 	  -6,   -6, 	   0,  -11
.2byte    0,  -13, 	   7,   -5, 	  -6,   -6, 	   0,  -11
.2byte    1,  -13, 	   7,   -7, 	  -7,   -7, 	   1,  -11
.2byte   -8,  -10, 	   2,   -5, 	  -6,   -4, 	  -2,  -10
.2byte   -8,   -9, 	   2,   -7, 	  -5,   -4, 	  -2,  -10
.2byte   -9,  -10, 	   1,   -8, 	  -7,   -4, 	  -2,  -10
.2byte   -9,   -6, 	   1,   -8, 	   1,   -3, 	   0,  -10
.2byte   -8,   -5, 	   1,   -8, 	   2,   -3, 	   0,   -9
.2byte   -9,   -6, 	   0,   -8, 	  -1,   -3, 	   0,   -9
.2byte   -5,   -3, 	  -3,   -7, 	   5,   -4, 	   1,   -9
.2byte   -4,   -3, 	  -3,   -8, 	   5,   -4, 	   2,   -9
.2byte   -5,   -3, 	  -4,   -6, 	   4,   -3, 	   1,   -9
.2byte    0,   -3, 	  -6,   -5, 	   6,   -5, 	   0,   -9
.2byte   -5,   -4, 	  -3,   -7, 	   5,   -4, 	   0,   -9
.2byte   -8,   -6, 	   2,   -8, 	   2,   -3, 	   0,  -10
.2byte   -7,   -9, 	   3,   -8, 	  -4,   -4, 	   0,  -10
.2byte    0,  -13, 	   6,   -6, 	  -6,   -6, 	   0,  -10
.2byte    7,   -9, 	  -3,   -8, 	   4,   -4, 	   0,  -10
.2byte    8,   -6, 	  -2,   -8, 	  -2,   -3, 	   0,  -10
.2byte    5,   -4, 	   3,   -7, 	  -5,   -4, 	   0,   -9
.2byte    0,   -2, 	  -6,   -5, 	   6,   -5, 	   0,   -9
.2byte   -5,   -3, 	  -3,   -7, 	   5,   -4, 	   1,   -9
.2byte   -9,   -6, 	   1,   -8, 	   1,   -3, 	   0,  -10
.2byte   -8,  -10, 	   2,   -5, 	  -6,   -4, 	  -2,  -10
.2byte    0,  -13, 	   7,   -6, 	  -6,   -6, 	   0,  -11
.2byte    8,  -10, 	  -2,   -5, 	   6,   -4, 	   2,  -10
.2byte    9,   -6, 	  -1,   -8, 	  -1,   -3, 	   0,  -10
.2byte    5,   -3, 	   3,   -7, 	  -5,   -4, 	  -1,   -9
sFeebasAnimTable1:
.4byte sFeebasAnims_1_1
.4byte sFeebasAnims_1_2
.4byte sFeebasAnims_1_3
.4byte sFeebasAnims_1_4
.4byte sFeebasAnims_1_5
.4byte sFeebasAnims_1_6
.4byte sFeebasAnims_1_7
.4byte sFeebasAnims_1_8
sFeebasAnimTable2:
.4byte sFeebasAnims_2_1
.4byte sFeebasAnims_2_2
.4byte sFeebasAnims_2_3
.4byte sFeebasAnims_2_4
.4byte sFeebasAnims_2_5
.4byte sFeebasAnims_2_6
.4byte sFeebasAnims_2_7
.4byte sFeebasAnims_2_8
sFeebasAnimTable3:
.4byte sFeebasAnims_3_1
.4byte sFeebasAnims_3_2
.4byte sFeebasAnims_3_3
.4byte sFeebasAnims_3_4
.4byte sFeebasAnims_3_5
.4byte sFeebasAnims_3_6
.4byte sFeebasAnims_3_7
.4byte sFeebasAnims_3_8
sFeebasAnimTable4:
.4byte sFeebasAnims_4_1
.4byte sFeebasAnims_4_2
.4byte sFeebasAnims_4_3
.4byte sFeebasAnims_4_4
.4byte sFeebasAnims_4_5
.4byte sFeebasAnims_4_6
.4byte sFeebasAnims_4_7
.4byte sFeebasAnims_4_8
sFeebasAnimTable5:
.4byte sFeebasAnims_5_1
.4byte sFeebasAnims_5_2
.4byte sFeebasAnims_5_3
.4byte sFeebasAnims_5_4
.4byte sFeebasAnims_5_5
.4byte sFeebasAnims_5_6
.4byte sFeebasAnims_5_7
.4byte sFeebasAnims_5_8
sFeebasAnimTable6:
.4byte sFeebasAnims_6_1
.4byte sFeebasAnims_6_1
.4byte sFeebasAnims_6_1
.4byte sFeebasAnims_6_1
.4byte sFeebasAnims_6_1
.4byte sFeebasAnims_6_1
.4byte sFeebasAnims_6_1
.4byte sFeebasAnims_6_1
sFeebasAnimTable7:
.4byte sFeebasAnims_7_1
.4byte sFeebasAnims_7_2
.4byte sFeebasAnims_7_3
.4byte sFeebasAnims_7_4
.4byte sFeebasAnims_7_5
.4byte sFeebasAnims_7_6
.4byte sFeebasAnims_7_7
.4byte sFeebasAnims_7_8
sFeebasAnimTable8:
.4byte sFeebasAnims_8_1
.4byte sFeebasAnims_8_2
.4byte sFeebasAnims_8_3
.4byte sFeebasAnims_8_4
.4byte sFeebasAnims_8_5
.4byte sFeebasAnims_8_6
.4byte sFeebasAnims_8_7
.4byte sFeebasAnims_8_8
sFeebasAnimTable9:
.4byte sFeebasAnims_9_1
.4byte sFeebasAnims_9_2
.4byte sFeebasAnims_9_3
.4byte sFeebasAnims_9_4
.4byte sFeebasAnims_9_5
.4byte sFeebasAnims_9_6
.4byte sFeebasAnims_9_7
.4byte sFeebasAnims_9_8
sFeebasAnimTable10:
.4byte sFeebasAnims_10_1
.4byte sFeebasAnims_10_2
.4byte sFeebasAnims_10_3
.4byte sFeebasAnims_10_4
.4byte sFeebasAnims_10_5
.4byte sFeebasAnims_10_6
.4byte sFeebasAnims_10_7
.4byte sFeebasAnims_10_8
sFeebasAnimTable11:
.4byte sFeebasAnims_11_1
.4byte sFeebasAnims_11_2
.4byte sFeebasAnims_11_3
.4byte sFeebasAnims_11_4
.4byte sFeebasAnims_11_5
.4byte sFeebasAnims_11_6
.4byte sFeebasAnims_11_7
.4byte sFeebasAnims_11_8
sFeebasAnimTable12:
.4byte sFeebasAnims_12_1
.4byte sFeebasAnims_12_2
.4byte sFeebasAnims_12_3
.4byte sFeebasAnims_12_4
.4byte sFeebasAnims_12_5
.4byte sFeebasAnims_12_6
.4byte sFeebasAnims_12_7
.4byte sFeebasAnims_12_8
sFeebasAnimTable13:
.4byte sFeebasAnims_13_1
.4byte sFeebasAnims_13_2
.4byte sFeebasAnims_13_3
.4byte sFeebasAnims_13_4
.4byte sFeebasAnims_13_5
.4byte sFeebasAnims_13_6
.4byte sFeebasAnims_13_7
.4byte sFeebasAnims_13_8
sAxAnimationsFeebas:
.4byte sFeebasAnimTable1
.4byte sFeebasAnimTable2
.4byte sFeebasAnimTable3
.4byte sFeebasAnimTable4
.4byte sFeebasAnimTable5
.4byte sFeebasAnimTable6
.4byte sFeebasAnimTable7
.4byte sFeebasAnimTable8
.4byte sFeebasAnimTable9
.4byte sFeebasAnimTable10
.4byte sFeebasAnimTable11
.4byte sFeebasAnimTable12
.4byte sFeebasAnimTable13
sAxSpritesFeebas:
.4byte sFeebasSprites1
.4byte sFeebasSprites2
.4byte sFeebasSprites3
.4byte sFeebasSprites4
.4byte sFeebasSprites5
.4byte sFeebasSprites6
.4byte sFeebasSprites7
.4byte sFeebasSprites8
.4byte sFeebasSprites9
.4byte sFeebasSprites10
.4byte sFeebasSprites11
.4byte sFeebasSprites12
.4byte sFeebasSprites13
.4byte sFeebasSprites14
.4byte sFeebasSprites15
.4byte sFeebasSprites16
.4byte sFeebasSprites17
.4byte sFeebasSprites18
.4byte sFeebasSprites19
.4byte sFeebasSprites20
.4byte sFeebasSprites21
.4byte sFeebasSprites22
.4byte sFeebasSprites23
.4byte sFeebasSprites24
.4byte sFeebasSprites25
.4byte sFeebasSprites26
.4byte sFeebasSprites27
sAxMainFeebas:
ax_main sAxPosesFeebas, sAxAnimationsFeebas, 13, sAxSpritesFeebas, sAxPositionsFeebas
