.global gAxFlygon
gAxFlygon:
ax_siro sAxMainFlygon
sFlygonPose1:
ax_pose 0, 0x01df, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose2:
ax_pose 1, 0x01df, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose3:
ax_pose 2, 0x01df, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose4:
ax_pose 3, 0x01df, 0x90f0, 0x3c00
ax_pose_terminator
sFlygonPose5:
ax_pose 4, 0x01e0, 0x90f0, 0x3c00
ax_pose_terminator
sFlygonPose6:
ax_pose 5, 0x01df, 0x90f0, 0x3c00
ax_pose_terminator
sFlygonPose7:
ax_pose 6, 0x01df, 0x90f0, 0x3c00
ax_pose_terminator
sFlygonPose8:
ax_pose 7, 0x01e0, 0x90f0, 0x3c00
ax_pose_terminator
sFlygonPose9:
ax_pose 8, 0x01df, 0x90f0, 0x3c00
ax_pose_terminator
sFlygonPose10:
ax_pose 9, 0x01df, 0x90f0, 0x3c00
ax_pose_terminator
sFlygonPose11:
ax_pose 10, 0x01e0, 0x90f0, 0x3c00
ax_pose_terminator
sFlygonPose12:
ax_pose 11, 0x01df, 0x90f0, 0x3c00
ax_pose_terminator
sFlygonPose13:
ax_pose 12, 0x01df, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose14:
ax_pose 13, 0x01df, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose15:
ax_pose 14, 0x81de, 0x80f0, 0x3c00
ax_pose 15, 0x81de, 0x4100, 0x3c08
ax_pose 16, 0x81ee, 0x0108, 0x3c0c
ax_pose 17, 0x01fe, 0x00f8, 0x3c0e
ax_pose_terminator
sFlygonPose16:
ax_pose 9, 0x01df, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose17:
ax_pose 10, 0x01e0, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose18:
ax_pose 11, 0x01df, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose19:
ax_pose 6, 0x01df, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose20:
ax_pose 7, 0x01e0, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose21:
ax_pose 8, 0x01df, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose22:
ax_pose 3, 0x01df, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose23:
ax_pose 4, 0x01e0, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose24:
ax_pose 5, 0x01df, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose25:
ax_pose 0, 0x01df, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose26:
ax_pose 1, 0x01de, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose27:
ax_pose 2, 0x01e0, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose28:
ax_pose 18, 0x81df, 0x8100, 0x3c00
ax_pose 19, 0x81df, 0x40f8, 0x3c08
ax_pose 20, 0x81e7, 0x00f0, 0x3c0c
ax_pose 21, 0x01d7, 0x00fc, 0x3c0e
ax_pose_terminator
sFlygonPose29:
ax_pose 22, 0x81e0, 0x8100, 0x3c00
ax_pose 23, 0x81e0, 0x40f8, 0x3c08
ax_pose 24, 0x81e8, 0x00f0, 0x3c0c
ax_pose 25, 0x01d8, 0x00fc, 0x3c0e
ax_pose_terminator
sFlygonPose30:
ax_pose 3, 0x01df, 0x90f0, 0x3c00
ax_pose_terminator
sFlygonPose31:
ax_pose 4, 0x01df, 0x90f0, 0x3c00
ax_pose_terminator
sFlygonPose32:
ax_pose 5, 0x01e0, 0x90f0, 0x3c00
ax_pose_terminator
sFlygonPose33:
ax_pose 26, 0x01df, 0x90f0, 0x3c00
ax_pose_terminator
sFlygonPose34:
ax_pose 27, 0x01df, 0x90f0, 0x3c00
ax_pose_terminator
sFlygonPose35:
ax_pose 6, 0x01df, 0x90f0, 0x3c00
ax_pose_terminator
sFlygonPose36:
ax_pose 7, 0x01df, 0x90f0, 0x3c00
ax_pose_terminator
sFlygonPose37:
ax_pose 8, 0x01e0, 0x90f0, 0x3c00
ax_pose_terminator
sFlygonPose38:
ax_pose 28, 0x41e7, 0x90f0, 0x3c00
ax_pose 29, 0x41f7, 0x50f0, 0x3c08
ax_pose 30, 0x41f3, 0x10e0, 0x3c0c
ax_pose 31, 0x01fb, 0x10e0, 0x3c0e
ax_pose_terminator
sFlygonPose39:
ax_pose 32, 0x41e7, 0x90f0, 0x3c00
ax_pose 33, 0x41f7, 0x50f0, 0x3c08
ax_pose 34, 0x41f3, 0x10e0, 0x3c0c
ax_pose 35, 0x01fb, 0x10e0, 0x3c0e
ax_pose_terminator
sFlygonPose40:
ax_pose 9, 0x01df, 0x90f0, 0x3c00
ax_pose_terminator
sFlygonPose41:
ax_pose 10, 0x01df, 0x90f0, 0x3c00
ax_pose_terminator
sFlygonPose42:
ax_pose 11, 0x01e0, 0x90f0, 0x3c00
ax_pose_terminator
sFlygonPose43:
ax_pose 36, 0x81df, 0x9100, 0x3c00
ax_pose 37, 0x01e7, 0x50f0, 0x3c08
ax_pose 38, 0x41f7, 0x10f0, 0x3c0c
ax_pose 39, 0x01ff, 0x10f0, 0x3c0e
ax_pose 40, 0x01fe, 0x10e8, 0x3c0f
ax_pose_terminator
sFlygonPose44:
ax_pose 41, 0x81df, 0x9100, 0x3c00
ax_pose 42, 0x01e7, 0x50f0, 0x3c08
ax_pose 43, 0x41f7, 0x10f0, 0x3c0c
ax_pose 44, 0x01ff, 0x10f0, 0x3c0e
ax_pose 45, 0x01fe, 0x10e8, 0x3c0f
ax_pose_terminator
sFlygonPose45:
ax_pose 12, 0x01df, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose46:
ax_pose 13, 0x01de, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose47:
ax_pose 14, 0x81df, 0x80f0, 0x3c00
ax_pose 15, 0x81df, 0x4100, 0x3c08
ax_pose 16, 0x81ef, 0x0108, 0x3c0c
ax_pose 17, 0x01ff, 0x00f8, 0x3c0e
ax_pose_terminator
sFlygonPose48:
ax_pose 46, 0x81e3, 0x80f8, 0x3c00
ax_pose 47, 0x81eb, 0x00f0, 0x3c08
ax_pose 48, 0x81eb, 0x0108, 0x3c0a
ax_pose 49, 0x0203, 0x00f8, 0x3c0c
ax_pose 50, 0x0203, 0x0100, 0x3c0d
ax_pose 51, 0x020b, 0x00fe, 0x3c0e
ax_pose_terminator
sFlygonPose49:
ax_pose 52, 0x81e3, 0x80f8, 0x3c00
ax_pose 53, 0x81eb, 0x00f0, 0x3c08
ax_pose 54, 0x81eb, 0x0108, 0x3c0a
ax_pose 55, 0x0203, 0x00f8, 0x3c0c
ax_pose 56, 0x0203, 0x0100, 0x3c0d
ax_pose 57, 0x020b, 0x00fe, 0x3c0e
ax_pose_terminator
sFlygonPose50:
ax_pose 9, 0x01df, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose51:
ax_pose 10, 0x01df, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose52:
ax_pose 11, 0x01e0, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose53:
ax_pose 36, 0x81df, 0x80f0, 0x3c00
ax_pose 37, 0x01e7, 0x4100, 0x3c08
ax_pose 38, 0x41f7, 0x0100, 0x3c0c
ax_pose 39, 0x01ff, 0x0108, 0x3c0e
ax_pose 40, 0x01fe, 0x0110, 0x3c0f
ax_pose_terminator
sFlygonPose54:
ax_pose 41, 0x81df, 0x80f0, 0x3c00
ax_pose 42, 0x01e7, 0x4100, 0x3c08
ax_pose 43, 0x41f7, 0x0100, 0x3c0c
ax_pose 44, 0x01ff, 0x0108, 0x3c0e
ax_pose 45, 0x01fe, 0x0110, 0x3c0f
ax_pose_terminator
sFlygonPose55:
ax_pose 6, 0x01df, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose56:
ax_pose 7, 0x01df, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose57:
ax_pose 8, 0x01e0, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose58:
ax_pose 28, 0x41e7, 0x80f0, 0x3c00
ax_pose 29, 0x41f7, 0x40f0, 0x3c08
ax_pose 30, 0x41f3, 0x0110, 0x3c0c
ax_pose 31, 0x01fb, 0x0118, 0x3c0e
ax_pose_terminator
sFlygonPose59:
ax_pose 32, 0x41e7, 0x80f0, 0x3c00
ax_pose 33, 0x41f7, 0x40f0, 0x3c08
ax_pose 34, 0x41f3, 0x0110, 0x3c0c
ax_pose 35, 0x01fb, 0x0118, 0x3c0e
ax_pose_terminator
sFlygonPose60:
ax_pose 3, 0x01df, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose61:
ax_pose 4, 0x01df, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose62:
ax_pose 5, 0x01e0, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose63:
ax_pose 26, 0x01df, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose64:
ax_pose 27, 0x01df, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose65:
ax_pose 0, 0x01df, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose66:
ax_pose 1, 0x01de, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose67:
ax_pose 2, 0x01e0, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose68:
ax_pose 18, 0x81df, 0x8100, 0x3c00
ax_pose 19, 0x81df, 0x40f8, 0x3c08
ax_pose 20, 0x81e7, 0x00f0, 0x3c0c
ax_pose 21, 0x01d7, 0x00fc, 0x3c0e
ax_pose_terminator
sFlygonPose69:
ax_pose 22, 0x81e0, 0x8100, 0x3c00
ax_pose 23, 0x81e0, 0x40f8, 0x3c08
ax_pose 24, 0x81e8, 0x00f0, 0x3c0c
ax_pose 25, 0x01d8, 0x00fc, 0x3c0e
ax_pose_terminator
sFlygonPose70:
ax_pose 3, 0x01df, 0x90f0, 0x3c00
ax_pose_terminator
sFlygonPose71:
ax_pose 4, 0x01df, 0x90f0, 0x3c00
ax_pose_terminator
sFlygonPose72:
ax_pose 5, 0x01e0, 0x90f0, 0x3c00
ax_pose_terminator
sFlygonPose73:
ax_pose 26, 0x01df, 0x90f0, 0x3c00
ax_pose_terminator
sFlygonPose74:
ax_pose 27, 0x01df, 0x90f0, 0x3c00
ax_pose_terminator
sFlygonPose75:
ax_pose 6, 0x01df, 0x90f0, 0x3c00
ax_pose_terminator
sFlygonPose76:
ax_pose 7, 0x01df, 0x90f0, 0x3c00
ax_pose_terminator
sFlygonPose77:
ax_pose 8, 0x01e0, 0x90f0, 0x3c00
ax_pose_terminator
sFlygonPose78:
ax_pose 28, 0x41e7, 0x90f0, 0x3c00
ax_pose 29, 0x41f7, 0x50f0, 0x3c08
ax_pose 30, 0x41f3, 0x10e0, 0x3c0c
ax_pose 31, 0x01fb, 0x10e0, 0x3c0e
ax_pose_terminator
sFlygonPose79:
ax_pose 32, 0x41e7, 0x90f0, 0x3c00
ax_pose 33, 0x41f7, 0x50f0, 0x3c08
ax_pose 34, 0x41f3, 0x10e0, 0x3c0c
ax_pose 35, 0x01fb, 0x10e0, 0x3c0e
ax_pose_terminator
sFlygonPose80:
ax_pose 9, 0x01df, 0x90f0, 0x3c00
ax_pose_terminator
sFlygonPose81:
ax_pose 10, 0x01df, 0x90f0, 0x3c00
ax_pose_terminator
sFlygonPose82:
ax_pose 11, 0x01e0, 0x90f0, 0x3c00
ax_pose_terminator
sFlygonPose83:
ax_pose 36, 0x81df, 0x9100, 0x3c00
ax_pose 37, 0x01e7, 0x50f0, 0x3c08
ax_pose 38, 0x41f7, 0x10f0, 0x3c0c
ax_pose 39, 0x01ff, 0x10f0, 0x3c0e
ax_pose 40, 0x01fe, 0x10e8, 0x3c0f
ax_pose_terminator
sFlygonPose84:
ax_pose 41, 0x81df, 0x9100, 0x3c00
ax_pose 42, 0x01e7, 0x50f0, 0x3c08
ax_pose 43, 0x41f7, 0x10f0, 0x3c0c
ax_pose 44, 0x01ff, 0x10f0, 0x3c0e
ax_pose 45, 0x01fe, 0x10e8, 0x3c0f
ax_pose_terminator
sFlygonPose85:
ax_pose 12, 0x01df, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose86:
ax_pose 13, 0x01de, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose87:
ax_pose 14, 0x81df, 0x80f0, 0x3c00
ax_pose 15, 0x81df, 0x4100, 0x3c08
ax_pose 16, 0x81ef, 0x0108, 0x3c0c
ax_pose 17, 0x01ff, 0x00f8, 0x3c0e
ax_pose_terminator
sFlygonPose88:
ax_pose 46, 0x81e3, 0x80f8, 0x3c00
ax_pose 47, 0x81eb, 0x00f0, 0x3c08
ax_pose 48, 0x81eb, 0x0108, 0x3c0a
ax_pose 49, 0x0203, 0x00f8, 0x3c0c
ax_pose 50, 0x0203, 0x0100, 0x3c0d
ax_pose 51, 0x020b, 0x00fe, 0x3c0e
ax_pose_terminator
sFlygonPose89:
ax_pose 52, 0x81e3, 0x80f8, 0x3c00
ax_pose 53, 0x81eb, 0x00f0, 0x3c08
ax_pose 54, 0x81eb, 0x0108, 0x3c0a
ax_pose 55, 0x0203, 0x00f8, 0x3c0c
ax_pose 56, 0x0203, 0x0100, 0x3c0d
ax_pose 57, 0x020b, 0x00fe, 0x3c0e
ax_pose_terminator
sFlygonPose90:
ax_pose 9, 0x01df, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose91:
ax_pose 10, 0x01df, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose92:
ax_pose 11, 0x01e0, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose93:
ax_pose 36, 0x81df, 0x80f0, 0x3c00
ax_pose 37, 0x01e7, 0x4100, 0x3c08
ax_pose 38, 0x41f7, 0x0100, 0x3c0c
ax_pose 39, 0x01ff, 0x0108, 0x3c0e
ax_pose 40, 0x01fe, 0x0110, 0x3c0f
ax_pose_terminator
sFlygonPose94:
ax_pose 41, 0x81df, 0x80f0, 0x3c00
ax_pose 42, 0x01e7, 0x4100, 0x3c08
ax_pose 43, 0x41f7, 0x0100, 0x3c0c
ax_pose 44, 0x01ff, 0x0108, 0x3c0e
ax_pose 45, 0x01fe, 0x0110, 0x3c0f
ax_pose_terminator
sFlygonPose95:
ax_pose 6, 0x01df, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose96:
ax_pose 7, 0x01df, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose97:
ax_pose 8, 0x01e0, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose98:
ax_pose 28, 0x41e7, 0x80f0, 0x3c00
ax_pose 29, 0x41f7, 0x40f0, 0x3c08
ax_pose 30, 0x41f3, 0x0110, 0x3c0c
ax_pose 31, 0x01fb, 0x0118, 0x3c0e
ax_pose_terminator
sFlygonPose99:
ax_pose 32, 0x41e7, 0x80f0, 0x3c00
ax_pose 33, 0x41f7, 0x40f0, 0x3c08
ax_pose 34, 0x41f3, 0x0110, 0x3c0c
ax_pose 35, 0x01fb, 0x0118, 0x3c0e
ax_pose_terminator
sFlygonPose100:
ax_pose 3, 0x01df, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose101:
ax_pose 4, 0x01df, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose102:
ax_pose 5, 0x01e0, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose103:
ax_pose 26, 0x01df, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose104:
ax_pose 27, 0x01df, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose105:
ax_pose 0, 0x01df, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose106:
ax_pose 1, 0x01df, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose107:
ax_pose 2, 0x01df, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose108:
ax_pose 58, 0x01dd, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose109:
ax_pose 59, 0x01de, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose110:
ax_pose 3, 0x01df, 0x90f0, 0x3c00
ax_pose_terminator
sFlygonPose111:
ax_pose 4, 0x01e0, 0x90f0, 0x3c00
ax_pose_terminator
sFlygonPose112:
ax_pose 5, 0x01df, 0x90f0, 0x3c00
ax_pose_terminator
sFlygonPose113:
ax_pose 60, 0x01df, 0x90f0, 0x3c00
ax_pose_terminator
sFlygonPose114:
ax_pose 61, 0x01e0, 0x90f0, 0x3c00
ax_pose_terminator
sFlygonPose115:
ax_pose 6, 0x01df, 0x90f0, 0x3c00
ax_pose_terminator
sFlygonPose116:
ax_pose 7, 0x01e0, 0x90f0, 0x3c00
ax_pose_terminator
sFlygonPose117:
ax_pose 8, 0x01df, 0x90f0, 0x3c00
ax_pose_terminator
sFlygonPose118:
ax_pose 62, 0x01df, 0x90f0, 0x3c00
ax_pose_terminator
sFlygonPose119:
ax_pose 63, 0x01e0, 0x90f0, 0x3c00
ax_pose_terminator
sFlygonPose120:
ax_pose 9, 0x01df, 0x90f0, 0x3c00
ax_pose_terminator
sFlygonPose121:
ax_pose 10, 0x01e0, 0x90f0, 0x3c00
ax_pose_terminator
sFlygonPose122:
ax_pose 11, 0x01df, 0x90f0, 0x3c00
ax_pose_terminator
sFlygonPose123:
ax_pose 64, 0x01df, 0x90f0, 0x3c00
ax_pose_terminator
sFlygonPose124:
ax_pose 65, 0x01e0, 0x90f0, 0x3c00
ax_pose_terminator
sFlygonPose125:
ax_pose 12, 0x01df, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose126:
ax_pose 13, 0x01df, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose127:
ax_pose 14, 0x81de, 0x80f0, 0x3c00
ax_pose 15, 0x81de, 0x4100, 0x3c08
ax_pose 16, 0x81ee, 0x0108, 0x3c0c
ax_pose 17, 0x01fe, 0x00f8, 0x3c0e
ax_pose_terminator
sFlygonPose128:
ax_pose 66, 0x01df, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose129:
ax_pose 67, 0x01e0, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose130:
ax_pose 9, 0x01df, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose131:
ax_pose 10, 0x01e0, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose132:
ax_pose 11, 0x01df, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose133:
ax_pose 64, 0x01df, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose134:
ax_pose 65, 0x01e0, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose135:
ax_pose 6, 0x01df, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose136:
ax_pose 7, 0x01e0, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose137:
ax_pose 8, 0x01df, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose138:
ax_pose 62, 0x01df, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose139:
ax_pose 63, 0x01e0, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose140:
ax_pose 3, 0x01df, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose141:
ax_pose 4, 0x01e0, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose142:
ax_pose 5, 0x01df, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose143:
ax_pose 60, 0x01df, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose144:
ax_pose 61, 0x01e0, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose145:
ax_pose 58, 0x01dd, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose146:
ax_pose 59, 0x01dd, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose147:
ax_pose 60, 0x01df, 0x90f0, 0x3c00
ax_pose_terminator
sFlygonPose148:
ax_pose 61, 0x01df, 0x90f0, 0x3c00
ax_pose_terminator
sFlygonPose149:
ax_pose 62, 0x01df, 0x90f0, 0x3c00
ax_pose_terminator
sFlygonPose150:
ax_pose 63, 0x01df, 0x90f0, 0x3c00
ax_pose_terminator
sFlygonPose151:
ax_pose 64, 0x01df, 0x90f0, 0x3c00
ax_pose_terminator
sFlygonPose152:
ax_pose 65, 0x01df, 0x90f0, 0x3c00
ax_pose_terminator
sFlygonPose153:
ax_pose 66, 0x01df, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose154:
ax_pose 67, 0x01df, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose155:
ax_pose 64, 0x01df, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose156:
ax_pose 65, 0x01df, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose157:
ax_pose 62, 0x01df, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose158:
ax_pose 63, 0x01df, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose159:
ax_pose 60, 0x01df, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose160:
ax_pose 61, 0x01df, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose161:
ax_pose 68, 0x01df, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose162:
ax_pose 69, 0x01de, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose163:
ax_pose 70, 0x01dd, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose164:
ax_pose 71, 0x01dd, 0x90ee, 0x3c00
ax_pose_terminator
sFlygonPose165:
ax_pose 72, 0x01de, 0x90ec, 0x3c00
ax_pose_terminator
sFlygonPose166:
ax_pose 73, 0x01dd, 0x90eb, 0x3c00
ax_pose_terminator
sFlygonPose167:
ax_pose 74, 0x01df, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose168:
ax_pose 73, 0x01dd, 0x80f5, 0x3c00
ax_pose_terminator
sFlygonPose169:
ax_pose 72, 0x01de, 0x80f4, 0x3c00
ax_pose_terminator
sFlygonPose170:
ax_pose 71, 0x01dd, 0x80f2, 0x3c00
ax_pose_terminator
sFlygonPose171:
ax_pose 0, 0x01df, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose172:
ax_pose 1, 0x01df, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose173:
ax_pose 2, 0x01df, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose174:
ax_pose 3, 0x01df, 0x90f0, 0x3c00
ax_pose_terminator
sFlygonPose175:
ax_pose 4, 0x01e0, 0x90f0, 0x3c00
ax_pose_terminator
sFlygonPose176:
ax_pose 5, 0x01df, 0x90f0, 0x3c00
ax_pose_terminator
sFlygonPose177:
ax_pose 6, 0x01df, 0x90f0, 0x3c00
ax_pose_terminator
sFlygonPose178:
ax_pose 7, 0x01e0, 0x90f0, 0x3c00
ax_pose_terminator
sFlygonPose179:
ax_pose 8, 0x01df, 0x90f0, 0x3c00
ax_pose_terminator
sFlygonPose180:
ax_pose 9, 0x01df, 0x90f0, 0x3c00
ax_pose_terminator
sFlygonPose181:
ax_pose 10, 0x01e0, 0x90f0, 0x3c00
ax_pose_terminator
sFlygonPose182:
ax_pose 11, 0x01df, 0x90f0, 0x3c00
ax_pose_terminator
sFlygonPose183:
ax_pose 12, 0x01df, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose184:
ax_pose 13, 0x01df, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose185:
ax_pose 14, 0x81de, 0x80f0, 0x3c00
ax_pose 15, 0x81de, 0x4100, 0x3c08
ax_pose 16, 0x81ee, 0x0108, 0x3c0c
ax_pose 17, 0x01fe, 0x00f8, 0x3c0e
ax_pose_terminator
sFlygonPose186:
ax_pose 9, 0x01df, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose187:
ax_pose 10, 0x01e0, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose188:
ax_pose 11, 0x01df, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose189:
ax_pose 6, 0x01df, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose190:
ax_pose 7, 0x01e0, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose191:
ax_pose 8, 0x01df, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose192:
ax_pose 3, 0x01df, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose193:
ax_pose 4, 0x01e0, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose194:
ax_pose 5, 0x01df, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose195:
ax_pose 58, 0x01dd, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose196:
ax_pose 60, 0x01df, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose197:
ax_pose 62, 0x01df, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose198:
ax_pose 64, 0x01df, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose199:
ax_pose 66, 0x01df, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose200:
ax_pose 64, 0x01df, 0x90f0, 0x3c00
ax_pose_terminator
sFlygonPose201:
ax_pose 62, 0x01df, 0x90f0, 0x3c00
ax_pose_terminator
sFlygonPose202:
ax_pose 60, 0x01df, 0x90f0, 0x3c00
ax_pose_terminator
sFlygonPose203:
ax_pose 58, 0x01dd, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose204:
ax_pose 60, 0x01df, 0x90ee, 0x3c00
ax_pose_terminator
sFlygonPose205:
ax_pose 62, 0x01df, 0x90ef, 0x3c00
ax_pose_terminator
sFlygonPose206:
ax_pose 64, 0x01df, 0x90ed, 0x3c00
ax_pose_terminator
sFlygonPose207:
ax_pose 66, 0x01df, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose208:
ax_pose 64, 0x01df, 0x80f3, 0x3c00
ax_pose_terminator
sFlygonPose209:
ax_pose 62, 0x01df, 0x80f1, 0x3c00
ax_pose_terminator
sFlygonPose210:
ax_pose 60, 0x01df, 0x80f2, 0x3c00
ax_pose_terminator
sFlygonPose211:
ax_pose 0, 0x01df, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose212:
ax_pose 2, 0x01e0, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose213:
ax_pose 1, 0x01de, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose214:
ax_pose 3, 0x01df, 0x90f0, 0x3c00
ax_pose_terminator
sFlygonPose215:
ax_pose 5, 0x01e0, 0x90f0, 0x3c00
ax_pose_terminator
sFlygonPose216:
ax_pose 4, 0x01df, 0x90f0, 0x3c00
ax_pose_terminator
sFlygonPose217:
ax_pose 6, 0x01df, 0x90f0, 0x3c00
ax_pose_terminator
sFlygonPose218:
ax_pose 8, 0x01e0, 0x90f0, 0x3c00
ax_pose_terminator
sFlygonPose219:
ax_pose 7, 0x01df, 0x90f0, 0x3c00
ax_pose_terminator
sFlygonPose220:
ax_pose 9, 0x01df, 0x90f0, 0x3c00
ax_pose_terminator
sFlygonPose221:
ax_pose 11, 0x01e0, 0x90f0, 0x3c00
ax_pose_terminator
sFlygonPose222:
ax_pose 10, 0x01df, 0x90f0, 0x3c00
ax_pose_terminator
sFlygonPose223:
ax_pose 12, 0x01df, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose224:
ax_pose 14, 0x81df, 0x80f0, 0x3c00
ax_pose 15, 0x81df, 0x4100, 0x3c08
ax_pose 16, 0x81ef, 0x0108, 0x3c0c
ax_pose 17, 0x01ff, 0x00f8, 0x3c0e
ax_pose_terminator
sFlygonPose225:
ax_pose 13, 0x01de, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose226:
ax_pose 9, 0x01df, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose227:
ax_pose 11, 0x01e0, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose228:
ax_pose 10, 0x01df, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose229:
ax_pose 6, 0x01df, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose230:
ax_pose 8, 0x01e0, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose231:
ax_pose 7, 0x01df, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose232:
ax_pose 3, 0x01df, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose233:
ax_pose 5, 0x01e0, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose234:
ax_pose 4, 0x01df, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose235:
ax_pose 1, 0x01e0, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose236:
ax_pose 4, 0x01e2, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose237:
ax_pose 7, 0x01e2, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose238:
ax_pose 10, 0x01e2, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose239:
ax_pose 13, 0x01e3, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose240:
ax_pose 10, 0x01e2, 0x90f0, 0x3c00
ax_pose_terminator
sFlygonPose241:
ax_pose 7, 0x01e2, 0x90f0, 0x3c00
ax_pose_terminator
sFlygonPose242:
ax_pose 4, 0x01e2, 0x90f0, 0x3c00
ax_pose_terminator
sFlygonPose243:
ax_pose 0, 0x01df, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose244:
ax_pose 3, 0x01df, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose245:
ax_pose 6, 0x01df, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose246:
ax_pose 9, 0x01df, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose247:
ax_pose 12, 0x01df, 0x80f0, 0x3c00
ax_pose_terminator
sFlygonPose248:
ax_pose 9, 0x01df, 0x90f0, 0x3c00
ax_pose_terminator
sFlygonPose249:
ax_pose 6, 0x01df, 0x90f0, 0x3c00
ax_pose_terminator
sFlygonPose250:
ax_pose 3, 0x01df, 0x90f0, 0x3c00
ax_pose_terminator
.align 2
sFlygonAnims_1_1:
ax_anim 8, 0, 0, 0, 0, 0, 0,
ax_anim 8, 0, 1, 0, 0, 0, 0,
ax_anim 8, 0, 0, 0, 0, 0, 0,
ax_anim 8, 0, 2, 0, 0, 0, 0,
ax_anim_terminator
sFlygonAnims_1_2:
ax_anim 8, 0, 3, 0, 0, 0, 0,
ax_anim 8, 0, 4, 0, 0, 0, 0,
ax_anim 8, 0, 3, 0, 0, 0, 0,
ax_anim 8, 0, 5, 0, 0, 0, 0,
ax_anim_terminator
sFlygonAnims_1_3:
ax_anim 8, 0, 6, 0, 0, 0, 0,
ax_anim 8, 0, 7, 0, 0, 0, 0,
ax_anim 8, 0, 6, 0, 0, 0, 0,
ax_anim 8, 0, 8, 0, 0, 0, 0,
ax_anim_terminator
sFlygonAnims_1_4:
ax_anim 8, 0, 9, 0, 0, 0, 0,
ax_anim 8, 0, 10, 0, 0, 0, 0,
ax_anim 8, 0, 9, 0, 0, 0, 0,
ax_anim 8, 0, 11, 0, 0, 0, 0,
ax_anim_terminator
sFlygonAnims_1_5:
ax_anim 8, 0, 12, 0, 0, 0, 0,
ax_anim 8, 0, 13, 0, 0, 0, 0,
ax_anim 8, 0, 12, 0, 0, 0, 0,
ax_anim 8, 0, 14, 0, 0, 0, 0,
ax_anim_terminator
sFlygonAnims_1_6:
ax_anim 8, 0, 15, 0, 0, 0, 0,
ax_anim 8, 0, 16, 0, 0, 0, 0,
ax_anim 8, 0, 15, 0, 0, 0, 0,
ax_anim 8, 0, 17, 0, 0, 0, 0,
ax_anim_terminator
sFlygonAnims_1_7:
ax_anim 8, 0, 18, 0, 0, 0, 0,
ax_anim 8, 0, 19, 0, 0, 0, 0,
ax_anim 8, 0, 18, 0, 0, 0, 0,
ax_anim 8, 0, 20, 0, 0, 0, 0,
ax_anim_terminator
sFlygonAnims_1_8:
ax_anim 8, 0, 21, 0, 0, 0, 0,
ax_anim 8, 0, 22, 0, 0, 0, 0,
ax_anim 8, 0, 21, 0, 0, 0, 0,
ax_anim 8, 0, 23, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sFlygonAnims_2_1:
ax_anim 2, 0, 25, 0, -2, 0, -2,
ax_anim 2, 0, 26, 0, -3, 0, -3,
ax_anim 2, 0, 25, 0, -4, 0, -4,
ax_anim 6, 0, 24, 0, -5, 0, -5,
ax_anim 1, 2, 27, 0, 5, 0, 5,
ax_anim 2, 0, 27, 0, 11, 0, 11,
ax_anim 2, 1, 28, 0, 22, 0, 22,
ax_anim 2, 0, 28, 1, 22, 1, 22,
ax_anim 2, 0, 28, 0, 22, 0, 22,
ax_anim 2, 0, 28, 1, 22, 1, 22,
ax_anim 2, 0, 24, 0, 13, 0, 13,
ax_anim_terminator
sFlygonAnims_2_2:
ax_anim 2, 0, 30, -2, -2, -2, -2,
ax_anim 2, 0, 31, -3, -3, -3, -3,
ax_anim 2, 0, 30, -4, -4, -4, -4,
ax_anim 6, 0, 29, -5, -5, -5, -5,
ax_anim 1, 2, 32, 5, 8, 5, 8,
ax_anim 2, 0, 32, 11, 16, 11, 16,
ax_anim 2, 1, 33, 15, 23, 15, 21,
ax_anim 2, 0, 33, 16, 22, 16, 20,
ax_anim 2, 0, 33, 15, 23, 15, 21,
ax_anim 2, 0, 33, 16, 22, 16, 20,
ax_anim 2, 0, 29, 9, 13, 9, 13,
ax_anim_terminator
sFlygonAnims_2_3:
ax_anim 2, 0, 35, -2, 0, -2, 0,
ax_anim 2, 0, 36, -3, 0, -3, 0,
ax_anim 2, 0, 35, -4, 0, -4, 0,
ax_anim 6, 0, 34, -5, 0, -5, 0,
ax_anim 1, 2, 37, 5, 0, 5, 0,
ax_anim 2, 0, 37, 11, 1, 11, 0,
ax_anim 2, 1, 38, 16, 2, 16, 0,
ax_anim 2, 0, 38, 16, 3, 16, 1,
ax_anim 2, 0, 38, 16, 2, 16, 0,
ax_anim 2, 0, 38, 16, 3, 16, 1,
ax_anim 2, 0, 34, 9, 0, 9, 0,
ax_anim_terminator
sFlygonAnims_2_4:
ax_anim 2, 0, 40, -2, 2, -2, 2,
ax_anim 2, 0, 41, -3, 3, -3, 3,
ax_anim 2, 0, 40, -4, 4, -4, 4,
ax_anim 6, 0, 39, -5, 5, -5, 5,
ax_anim 1, 2, 42, 5, -4, 7, -7,
ax_anim 2, 0, 42, 11, -8, 13, -13,
ax_anim 2, 1, 43, 15, -11, 18, -18,
ax_anim 2, 0, 43, 16, -10, 19, -17,
ax_anim 2, 0, 43, 15, -11, 18, -18,
ax_anim 2, 0, 43, 16, -10, 19, -17,
ax_anim 2, 0, 39, 9, -6, 9, -6,
ax_anim_terminator
sFlygonAnims_2_5:
ax_anim 2, 0, 45, 0, 2, 0, 2,
ax_anim 2, 0, 46, 0, 3, 0, 3,
ax_anim 2, 0, 45, 0, 4, 0, 4,
ax_anim 6, 0, 44, 0, 5, 0, 5,
ax_anim 1, 2, 47, 0, -2, 0, -2,
ax_anim 2, 0, 47, 0, -8, 0, -11,
ax_anim 2, 1, 48, 0, -13, 0, -20,
ax_anim 2, 0, 48, 1, -13, 1, -20,
ax_anim 2, 0, 48, 0, -13, 0, -20,
ax_anim 2, 0, 48, 1, -13, 1, -20,
ax_anim 2, 0, 44, 0, -6, 0, -10,
ax_anim_terminator
sFlygonAnims_2_6:
ax_anim 2, 0, 50, 2, 2, 2, 2,
ax_anim 2, 0, 51, 3, 3, 3, 3,
ax_anim 2, 0, 50, 4, 4, 4, 4,
ax_anim 6, 0, 49, 5, 5, 5, 5,
ax_anim 1, 2, 52, -5, -4, -7, -7,
ax_anim 2, 0, 52, -11, -8, -13, -13,
ax_anim 2, 1, 53, -15, -11, -18, -18,
ax_anim 2, 0, 53, -16, -10, -19, -17,
ax_anim 2, 0, 53, -15, -11, -18, -18,
ax_anim 2, 0, 53, -16, -10, -19, -17,
ax_anim 2, 0, 49, -9, -6, -9, -6,
ax_anim_terminator
sFlygonAnims_2_7:
ax_anim 2, 0, 55, 2, 0, 2, 0,
ax_anim 2, 0, 56, 3, 0, 3, 0,
ax_anim 2, 0, 55, 4, 0, 4, 0,
ax_anim 6, 0, 54, 5, 0, 5, 0,
ax_anim 1, 2, 57, -5, 0, -5, 0,
ax_anim 2, 0, 57, -11, 1, -11, 0,
ax_anim 2, 1, 58, -16, 2, -16, 0,
ax_anim 2, 0, 58, -16, 3, -16, 1,
ax_anim 2, 0, 58, -16, 2, -16, 0,
ax_anim 2, 0, 58, -16, 3, -16, 1,
ax_anim 2, 0, 54, -9, 0, -9, 0,
ax_anim_terminator
sFlygonAnims_2_8:
ax_anim 2, 0, 60, 2, -2, 2, -2,
ax_anim 2, 0, 61, 3, -3, 3, -3,
ax_anim 2, 0, 60, 4, -4, 4, -4,
ax_anim 6, 0, 59, 5, -5, 5, -5,
ax_anim 1, 2, 62, -5, 8, -5, 8,
ax_anim 2, 0, 62, -11, 16, -11, 16,
ax_anim 2, 1, 63, -15, 23, -15, 21,
ax_anim 2, 0, 63, -16, 22, -16, 20,
ax_anim 2, 0, 63, -15, 23, -15, 21,
ax_anim 2, 0, 63, -16, 22, -16, 20,
ax_anim 2, 0, 59, -9, 13, -9, 13,
ax_anim_terminator
.align 2
sFlygonAnims_3_1:
ax_anim 2, 0, 65, 0, -2, 0, -2,
ax_anim 2, 0, 66, 0, -3, 0, -3,
ax_anim 2, 0, 65, 0, -4, 0, -4,
ax_anim 6, 0, 64, 0, -5, 0, -5,
ax_anim 1, 2, 67, 0, 5, 0, 5,
ax_anim 2, 0, 67, 0, 11, 0, 11,
ax_anim 2, 1, 68, 0, 22, 0, 22,
ax_anim 2, 0, 68, 1, 22, 1, 22,
ax_anim 2, 0, 68, 0, 22, 0, 22,
ax_anim 2, 0, 68, 1, 22, 1, 22,
ax_anim 2, 0, 64, 0, 13, 0, 13,
ax_anim_terminator
sFlygonAnims_3_2:
ax_anim 2, 0, 70, -2, -2, -2, -2,
ax_anim 2, 0, 71, -3, -3, -3, -3,
ax_anim 2, 0, 70, -4, -4, -4, -4,
ax_anim 6, 0, 69, -5, -5, -5, -5,
ax_anim 1, 2, 72, 5, 8, 5, 8,
ax_anim 2, 0, 72, 11, 16, 11, 16,
ax_anim 2, 1, 73, 15, 23, 15, 21,
ax_anim 2, 0, 73, 16, 22, 16, 20,
ax_anim 2, 0, 73, 15, 23, 15, 21,
ax_anim 2, 0, 73, 16, 22, 16, 20,
ax_anim 2, 0, 69, 9, 13, 9, 13,
ax_anim_terminator
sFlygonAnims_3_3:
ax_anim 2, 0, 75, -2, 0, -2, 0,
ax_anim 2, 0, 76, -3, 0, -3, 0,
ax_anim 2, 0, 75, -4, 0, -4, 0,
ax_anim 6, 0, 74, -5, 0, -5, 0,
ax_anim 1, 2, 77, 5, 0, 5, 0,
ax_anim 2, 0, 77, 11, 1, 11, 0,
ax_anim 2, 1, 78, 16, 2, 16, 0,
ax_anim 2, 0, 78, 16, 3, 16, 1,
ax_anim 2, 0, 78, 16, 2, 16, 0,
ax_anim 2, 0, 78, 16, 3, 16, 1,
ax_anim 2, 0, 74, 9, 0, 9, 0,
ax_anim_terminator
sFlygonAnims_3_4:
ax_anim 2, 0, 80, -2, 2, -2, 2,
ax_anim 2, 0, 81, -3, 3, -3, 3,
ax_anim 2, 0, 80, -4, 4, -4, 4,
ax_anim 6, 0, 79, -5, 5, -5, 5,
ax_anim 1, 2, 82, 5, -4, 7, -7,
ax_anim 2, 0, 82, 11, -8, 13, -13,
ax_anim 2, 1, 83, 15, -11, 18, -18,
ax_anim 2, 0, 83, 16, -10, 19, -17,
ax_anim 2, 0, 83, 15, -11, 18, -18,
ax_anim 2, 0, 83, 16, -10, 19, -17,
ax_anim 2, 0, 79, 9, -6, 9, -6,
ax_anim_terminator
sFlygonAnims_3_5:
ax_anim 2, 0, 85, 0, 2, 0, 2,
ax_anim 2, 0, 86, 0, 3, 0, 3,
ax_anim 2, 0, 85, 0, 4, 0, 4,
ax_anim 6, 0, 84, 0, 5, 0, 5,
ax_anim 1, 2, 87, 0, -2, 0, -2,
ax_anim 2, 0, 87, 0, -8, 0, -11,
ax_anim 2, 1, 88, 0, -13, 0, -20,
ax_anim 2, 0, 88, 1, -13, 1, -20,
ax_anim 2, 0, 88, 0, -13, 0, -20,
ax_anim 2, 0, 88, 1, -13, 1, -20,
ax_anim 2, 0, 84, 0, -6, 0, -10,
ax_anim_terminator
sFlygonAnims_3_6:
ax_anim 2, 0, 90, 2, 2, 2, 2,
ax_anim 2, 0, 91, 3, 3, 3, 3,
ax_anim 2, 0, 90, 4, 4, 4, 4,
ax_anim 6, 0, 89, 5, 5, 5, 5,
ax_anim 1, 2, 92, -5, -4, -7, -7,
ax_anim 2, 0, 92, -11, -8, -13, -13,
ax_anim 2, 1, 93, -15, -11, -18, -18,
ax_anim 2, 0, 93, -16, -10, -19, -17,
ax_anim 2, 0, 93, -15, -11, -18, -18,
ax_anim 2, 0, 93, -16, -10, -19, -17,
ax_anim 2, 0, 89, -9, -6, -9, -6,
ax_anim_terminator
sFlygonAnims_3_7:
ax_anim 2, 0, 95, 2, 0, 2, 0,
ax_anim 2, 0, 96, 3, 0, 3, 0,
ax_anim 2, 0, 95, 4, 0, 4, 0,
ax_anim 6, 0, 94, 5, 0, 5, 0,
ax_anim 1, 2, 97, -5, 0, -5, 0,
ax_anim 2, 0, 97, -11, 1, -11, 0,
ax_anim 2, 1, 98, -16, 2, -16, 0,
ax_anim 2, 0, 98, -16, 3, -16, 1,
ax_anim 2, 0, 98, -16, 2, -16, 0,
ax_anim 2, 0, 98, -16, 3, -16, 1,
ax_anim 2, 0, 94, -9, 0, -9, 0,
ax_anim_terminator
sFlygonAnims_3_8:
ax_anim 2, 0, 100, 2, -2, 2, -2,
ax_anim 2, 0, 101, 3, -3, 3, -3,
ax_anim 2, 0, 100, 4, -4, 4, -4,
ax_anim 6, 0, 99, 5, -5, 5, -5,
ax_anim 1, 2, 102, -5, 8, -5, 8,
ax_anim 2, 0, 102, -11, 16, -11, 16,
ax_anim 2, 1, 103, -15, 23, -15, 21,
ax_anim 2, 0, 103, -16, 22, -16, 20,
ax_anim 2, 0, 103, -15, 23, -15, 21,
ax_anim 2, 0, 103, -16, 22, -16, 20,
ax_anim 2, 0, 99, -9, 13, -9, 13,
ax_anim_terminator
.align 2
sFlygonAnims_4_1:
ax_anim 2, 0, 104, 0, -1, 0, -1,
ax_anim 2, 0, 105, 0, -2, 0, -2,
ax_anim 2, 0, 104, 0, -3, 0, -3,
ax_anim 2, 0, 106, 0, -4, 0, -4,
ax_anim 2, 0, 104, 0, -5, 0, -5,
ax_anim 2, 2, 105, 0, -5, 0, -5,
ax_anim 4, 0, 104, 0, -5, 0, -5,
ax_anim 1, 0, 108, 0, -2, 0, -2,
ax_anim 1, 0, 107, 0, 2, 0, 2,
ax_anim 2, 1, 107, 0, 6, 0, 6,
ax_anim 2, 0, 107, 1, 6, 1, 6,
ax_anim 2, 0, 107, 0, 6, 0, 6,
ax_anim 2, 0, 107, 1, 6, 1, 6,
ax_anim 2, 0, 104, 0, 3, 0, 3,
ax_anim_terminator
sFlygonAnims_4_2:
ax_anim 2, 0, 109, -1, -1, -1, -1,
ax_anim 2, 0, 110, -2, -2, -2, -2,
ax_anim 2, 0, 109, -3, -3, -3, -3,
ax_anim 2, 0, 111, -4, -4, -4, -4,
ax_anim 2, 0, 109, -5, -5, -5, -5,
ax_anim 2, 2, 110, -5, -5, -5, -5,
ax_anim 4, 0, 109, -5, -5, -5, -5,
ax_anim 1, 0, 113, -2, -2, -2, -2,
ax_anim 1, 0, 112, 2, 2, 2, 2,
ax_anim 2, 1, 112, 6, 6, 6, 6,
ax_anim 2, 0, 112, 7, 5, 7, 5,
ax_anim 2, 0, 112, 6, 6, 6, 6,
ax_anim 2, 0, 112, 7, 5, 7, 5,
ax_anim 2, 0, 109, 3, 3, 3, 3,
ax_anim_terminator
sFlygonAnims_4_3:
ax_anim 2, 0, 114, -1, 0, -1, 0,
ax_anim 2, 0, 115, -2, 0, -2, 0,
ax_anim 2, 0, 114, -3, 0, -3, 0,
ax_anim 2, 0, 116, -4, 0, -4, 0,
ax_anim 2, 0, 114, -5, 0, -5, 0,
ax_anim 2, 2, 115, -5, 0, -5, 0,
ax_anim 4, 0, 114, -5, 0, -5, 0,
ax_anim 1, 0, 118, -2, 0, -2, 0,
ax_anim 1, 0, 117, 2, 0, 2, 0,
ax_anim 2, 1, 117, 6, 0, 6, 0,
ax_anim 2, 0, 117, 6, 1, 6, 1,
ax_anim 2, 0, 117, 6, 0, 6, 0,
ax_anim 2, 0, 117, 6, 1, 6, 1,
ax_anim 2, 0, 114, 3, 0, 3, 0,
ax_anim_terminator
sFlygonAnims_4_4:
ax_anim 2, 0, 119, -1, 1, -1, 1,
ax_anim 2, 0, 120, -2, 2, -2, 2,
ax_anim 2, 0, 119, -3, 3, -3, 3,
ax_anim 2, 0, 121, -4, 4, -4, 4,
ax_anim 2, 0, 119, -5, 5, -5, 5,
ax_anim 2, 2, 120, -5, 5, -5, 5,
ax_anim 4, 0, 119, -5, 5, -5, 5,
ax_anim 1, 0, 123, -2, 2, -2, 2,
ax_anim 1, 0, 122, 2, -2, 2, -2,
ax_anim 2, 1, 122, 6, -6, 6, -6,
ax_anim 2, 0, 122, 7, -5, 7, -5,
ax_anim 2, 0, 122, 6, -6, 6, -6,
ax_anim 2, 0, 122, 7, -5, 7, -5,
ax_anim 2, 0, 119, 3, -3, 3, -3,
ax_anim_terminator
sFlygonAnims_4_5:
ax_anim 2, 0, 124, 0, 1, 0, 1,
ax_anim 2, 0, 125, 0, 2, 0, 2,
ax_anim 2, 0, 124, 0, 3, 0, 3,
ax_anim 2, 0, 126, 0, 4, 0, 4,
ax_anim 2, 0, 124, 0, 5, 0, 5,
ax_anim 2, 2, 125, 0, 5, 0, 5,
ax_anim 4, 0, 124, 0, 5, 0, 5,
ax_anim 1, 0, 128, 0, 2, 0, 2,
ax_anim 1, 0, 127, 0, -2, 0, -2,
ax_anim 2, 1, 127, 0, -6, 0, -6,
ax_anim 2, 0, 127, 1, -6, 1, -6,
ax_anim 2, 0, 127, 0, -6, 0, -6,
ax_anim 2, 0, 127, 1, -6, 1, -6,
ax_anim 2, 0, 124, 0, -3, 0, -3,
ax_anim_terminator
sFlygonAnims_4_6:
ax_anim 2, 0, 129, 1, 1, 1, 1,
ax_anim 2, 0, 130, 2, 2, 2, 2,
ax_anim 2, 0, 129, 3, 3, 3, 3,
ax_anim 2, 0, 131, 4, 4, 4, 4,
ax_anim 2, 0, 129, 5, 5, 5, 5,
ax_anim 2, 2, 130, 5, 5, 5, 5,
ax_anim 4, 0, 129, 5, 5, 5, 5,
ax_anim 1, 0, 133, 2, 2, 2, 2,
ax_anim 1, 0, 132, -2, -2, -2, -2,
ax_anim 2, 1, 132, -6, -6, -6, -6,
ax_anim 2, 0, 132, -7, -5, -7, -5,
ax_anim 2, 0, 132, -6, -6, -6, -6,
ax_anim 2, 0, 132, -7, -5, -7, -5,
ax_anim 2, 0, 129, -3, -3, -3, -3,
ax_anim_terminator
sFlygonAnims_4_7:
ax_anim 2, 0, 134, 1, 0, 1, 0,
ax_anim 2, 0, 135, 2, 0, 2, 0,
ax_anim 2, 0, 134, 3, 0, 3, 0,
ax_anim 2, 0, 136, 4, 0, 4, 0,
ax_anim 2, 0, 134, 5, 0, 5, 0,
ax_anim 2, 2, 135, 5, 0, 5, 0,
ax_anim 4, 0, 134, 5, 0, 5, 0,
ax_anim 1, 0, 138, 2, 0, 2, 0,
ax_anim 1, 0, 137, -2, 0, -2, 0,
ax_anim 2, 1, 137, -6, 0, -6, 0,
ax_anim 2, 0, 137, -6, 1, -6, 1,
ax_anim 2, 0, 137, -6, 0, -6, 0,
ax_anim 2, 0, 137, -6, 1, -6, 1,
ax_anim 2, 0, 134, -3, 0, -3, 0,
ax_anim_terminator
sFlygonAnims_4_8:
ax_anim 2, 0, 139, 1, -1, 1, -1,
ax_anim 2, 0, 140, 2, -2, 2, -2,
ax_anim 2, 0, 139, 3, -3, 3, -3,
ax_anim 2, 0, 141, 4, -4, 4, -4,
ax_anim 2, 0, 139, 5, -5, 5, -5,
ax_anim 2, 2, 140, 5, -5, 5, -5,
ax_anim 4, 0, 139, 5, -5, 5, -5,
ax_anim 1, 0, 143, 2, -2, 2, -2,
ax_anim 1, 0, 142, -2, 2, -2, 2,
ax_anim 2, 1, 142, -6, 6, -6, 6,
ax_anim 2, 0, 142, -7, 5, -7, 5,
ax_anim 2, 0, 142, -6, 6, -6, 6,
ax_anim 2, 0, 142, -7, 5, -7, 5,
ax_anim 2, 0, 139, -3, 3, -3, 3,
ax_anim_terminator
.align 2
sFlygonAnims_5_1:
ax_anim 2, 2, 144, 0, 0, 0, 0,
ax_anim 1, 0, 145, 0, 0, 0, 0,
ax_anim 2, 0, 146, 0, 0, 0, 0,
ax_anim 1, 0, 147, 0, 0, 0, 0,
ax_anim 2, 0, 148, 0, 0, 0, 0,
ax_anim 1, 1, 149, 0, 0, 0, 0,
ax_anim 2, 0, 150, 0, 0, 0, 0,
ax_anim 1, 0, 151, 0, 0, 0, 0,
ax_anim 2, 0, 152, 0, 0, 0, 0,
ax_anim 1, 0, 153, 0, 0, 0, 0,
ax_anim 2, 0, 154, 0, 0, 0, 0,
ax_anim 1, 0, 155, 0, 0, 0, 0,
ax_anim 2, 0, 156, 0, 0, 0, 0,
ax_anim 1, 0, 157, 0, 0, 0, 0,
ax_anim 2, 0, 158, 0, 0, 0, 0,
ax_anim 1, 0, 159, 0, 0, 0, 0,
ax_anim 2, 0, 144, 0, 0, 0, 0,
ax_anim 2, 0, 145, 0, 0, 0, 0,
ax_anim 2, 0, 144, 0, 0, 0, 0,
ax_anim_terminator
sFlygonAnims_5_2:
ax_anim 2, 2, 146, 0, 0, 0, 0,
ax_anim 1, 0, 147, 0, 0, 0, 0,
ax_anim 2, 0, 148, 0, 0, 0, 0,
ax_anim 1, 0, 149, 0, 0, 0, 0,
ax_anim 2, 0, 150, 0, 0, 0, 0,
ax_anim 1, 1, 151, 0, 0, 0, 0,
ax_anim 2, 0, 152, 0, 0, 0, 0,
ax_anim 1, 0, 153, 0, 0, 0, 0,
ax_anim 2, 0, 154, 0, 0, 0, 0,
ax_anim 1, 0, 155, 0, 0, 0, 0,
ax_anim 2, 0, 156, 0, 0, 0, 0,
ax_anim 1, 0, 157, 0, 0, 0, 0,
ax_anim 2, 0, 158, 0, 0, 0, 0,
ax_anim 1, 0, 159, 0, 0, 0, 0,
ax_anim 2, 0, 144, 0, 0, 0, 0,
ax_anim 1, 0, 145, 0, 0, 0, 0,
ax_anim 2, 0, 146, 0, 0, 0, 0,
ax_anim 2, 0, 147, 0, 0, 0, 0,
ax_anim 2, 0, 146, 0, 0, 0, 0,
ax_anim_terminator
sFlygonAnims_5_3:
ax_anim 2, 2, 148, 0, 0, 0, 0,
ax_anim 1, 0, 149, 0, 0, 0, 0,
ax_anim 2, 0, 150, 0, 0, 0, 0,
ax_anim 1, 0, 151, 0, 0, 0, 0,
ax_anim 2, 0, 152, 0, 0, 0, 0,
ax_anim 1, 1, 153, 0, 0, 0, 0,
ax_anim 2, 0, 154, 0, 0, 0, 0,
ax_anim 1, 0, 155, 0, 0, 0, 0,
ax_anim 2, 0, 156, 0, 0, 0, 0,
ax_anim 1, 0, 157, 0, 0, 0, 0,
ax_anim 2, 0, 158, 0, 0, 0, 0,
ax_anim 1, 0, 159, 0, 0, 0, 0,
ax_anim 2, 0, 144, 0, 0, 0, 0,
ax_anim 1, 0, 145, 0, 0, 0, 0,
ax_anim 2, 0, 146, 0, 0, 0, 0,
ax_anim 1, 0, 147, 0, 0, 0, 0,
ax_anim 2, 0, 148, 0, 0, 0, 0,
ax_anim 2, 0, 149, 0, 0, 0, 0,
ax_anim 2, 0, 148, 0, 0, 0, 0,
ax_anim_terminator
sFlygonAnims_5_4:
ax_anim 2, 2, 150, 0, 0, 0, 0,
ax_anim 1, 0, 151, 0, 0, 0, 0,
ax_anim 2, 0, 152, 0, 0, 0, 0,
ax_anim 1, 0, 153, 0, 0, 0, 0,
ax_anim 2, 0, 154, 0, 0, 0, 0,
ax_anim 1, 1, 155, 0, 0, 0, 0,
ax_anim 2, 0, 156, 0, 0, 0, 0,
ax_anim 1, 0, 157, 0, 0, 0, 0,
ax_anim 2, 0, 158, 0, 0, 0, 0,
ax_anim 1, 0, 159, 0, 0, 0, 0,
ax_anim 2, 0, 144, 0, 0, 0, 0,
ax_anim 1, 0, 145, 0, 0, 0, 0,
ax_anim 2, 0, 146, 0, 0, 0, 0,
ax_anim 1, 0, 147, 0, 0, 0, 0,
ax_anim 2, 0, 148, 0, 0, 0, 0,
ax_anim 1, 0, 149, 0, 0, 0, 0,
ax_anim 2, 0, 150, 0, 0, 0, 0,
ax_anim 2, 0, 151, 0, 0, 0, 0,
ax_anim 2, 0, 150, 0, 0, 0, 0,
ax_anim_terminator
sFlygonAnims_5_5:
ax_anim 2, 2, 152, 0, 0, 0, 0,
ax_anim 1, 0, 153, 0, 0, 0, 0,
ax_anim 2, 0, 154, 0, 0, 0, 0,
ax_anim 1, 0, 155, 0, 0, 0, 0,
ax_anim 2, 0, 156, 0, 0, 0, 0,
ax_anim 1, 1, 157, 0, 0, 0, 0,
ax_anim 2, 0, 158, 0, 0, 0, 0,
ax_anim 1, 0, 159, 0, 0, 0, 0,
ax_anim 2, 0, 144, 0, 0, 0, 0,
ax_anim 1, 0, 145, 0, 0, 0, 0,
ax_anim 2, 0, 146, 0, 0, 0, 0,
ax_anim 1, 0, 147, 0, 0, 0, 0,
ax_anim 2, 0, 148, 0, 0, 0, 0,
ax_anim 1, 0, 149, 0, 0, 0, 0,
ax_anim 2, 0, 150, 0, 0, 0, 0,
ax_anim 1, 0, 151, 0, 0, 0, 0,
ax_anim 2, 0, 152, 0, 0, 0, 0,
ax_anim 2, 0, 153, 0, 0, 0, 0,
ax_anim 2, 0, 152, 0, 0, 0, 0,
ax_anim_terminator
sFlygonAnims_5_6:
ax_anim 2, 2, 154, 0, 0, 0, 0,
ax_anim 1, 0, 155, 0, 0, 0, 0,
ax_anim 2, 0, 156, 0, 0, 0, 0,
ax_anim 1, 0, 157, 0, 0, 0, 0,
ax_anim 2, 0, 158, 0, 0, 0, 0,
ax_anim 1, 1, 159, 0, 0, 0, 0,
ax_anim 2, 0, 144, 0, 0, 0, 0,
ax_anim 1, 0, 145, 0, 0, 0, 0,
ax_anim 2, 0, 146, 0, 0, 0, 0,
ax_anim 1, 0, 147, 0, 0, 0, 0,
ax_anim 2, 0, 148, 0, 0, 0, 0,
ax_anim 1, 0, 149, 0, 0, 0, 0,
ax_anim 2, 0, 150, 0, 0, 0, 0,
ax_anim 1, 0, 151, 0, 0, 0, 0,
ax_anim 2, 0, 152, 0, 0, 0, 0,
ax_anim 1, 0, 153, 0, 0, 0, 0,
ax_anim 2, 0, 154, 0, 0, 0, 0,
ax_anim 2, 0, 155, 0, 0, 0, 0,
ax_anim 2, 0, 154, 0, 0, 0, 0,
ax_anim_terminator
sFlygonAnims_5_7:
ax_anim 2, 2, 156, 0, 0, 0, 0,
ax_anim 1, 0, 157, 0, 0, 0, 0,
ax_anim 2, 0, 158, 0, 0, 0, 0,
ax_anim 1, 0, 159, 0, 0, 0, 0,
ax_anim 2, 0, 144, 0, 0, 0, 0,
ax_anim 1, 1, 145, 0, 0, 0, 0,
ax_anim 2, 0, 146, 0, 0, 0, 0,
ax_anim 1, 0, 147, 0, 0, 0, 0,
ax_anim 2, 0, 148, 0, 0, 0, 0,
ax_anim 1, 0, 149, 0, 0, 0, 0,
ax_anim 2, 0, 150, 0, 0, 0, 0,
ax_anim 1, 0, 151, 0, 0, 0, 0,
ax_anim 2, 0, 152, 0, 0, 0, 0,
ax_anim 1, 0, 153, 0, 0, 0, 0,
ax_anim 2, 0, 154, 0, 0, 0, 0,
ax_anim 1, 0, 155, 0, 0, 0, 0,
ax_anim 2, 0, 156, 0, 0, 0, 0,
ax_anim 2, 0, 157, 0, 0, 0, 0,
ax_anim 2, 0, 156, 0, 0, 0, 0,
ax_anim_terminator
sFlygonAnims_5_8:
ax_anim 2, 2, 158, 0, 0, 0, 0,
ax_anim 1, 0, 159, 0, 0, 0, 0,
ax_anim 2, 0, 144, 0, 0, 0, 0,
ax_anim 1, 0, 145, 0, 0, 0, 0,
ax_anim 2, 0, 146, 0, 0, 0, 0,
ax_anim 1, 1, 147, 0, 0, 0, 0,
ax_anim 2, 0, 148, 0, 0, 0, 0,
ax_anim 1, 0, 149, 0, 0, 0, 0,
ax_anim 2, 0, 150, 0, 0, 0, 0,
ax_anim 1, 0, 151, 0, 0, 0, 0,
ax_anim 2, 0, 152, 0, 0, 0, 0,
ax_anim 1, 0, 153, 0, 0, 0, 0,
ax_anim 2, 0, 154, 0, 0, 0, 0,
ax_anim 1, 0, 155, 0, 0, 0, 0,
ax_anim 2, 0, 156, 0, 0, 0, 0,
ax_anim 1, 0, 157, 0, 0, 0, 0,
ax_anim 2, 0, 158, 0, 0, 0, 0,
ax_anim 2, 0, 159, 0, 0, 0, 0,
ax_anim 2, 0, 158, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sFlygonAnims_6_1:
ax_anim 16, 0, 160, 0, 0, 0, 0,
ax_anim 12, 0, 160, 0, -1, 0, 0,
ax_anim 16, 0, 160, 0, -2, 0, 0,
ax_anim 16, 0, 161, 0, -2, 0, 0,
ax_anim 12, 0, 161, 0, -1, 0, 0,
ax_anim 16, 0, 161, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sFlygonAnims_7_1:
ax_anim 2, 0, 162, 0, -2, 0, -2,
ax_anim 8, 0, 162, 0, -3, 0, -3,
ax_anim_terminator
sFlygonAnims_7_2:
ax_anim 2, 0, 163, -2, -2, -2, -2,
ax_anim 8, 0, 163, -3, -3, -3, -3,
ax_anim_terminator
sFlygonAnims_7_3:
ax_anim 2, 0, 164, -2, 0, -2, 0,
ax_anim 8, 0, 164, -3, 0, -3, 0,
ax_anim_terminator
sFlygonAnims_7_4:
ax_anim 2, 0, 165, -2, 2, -2, 2,
ax_anim 8, 0, 165, -3, 3, -3, 3,
ax_anim_terminator
sFlygonAnims_7_5:
ax_anim 2, 0, 166, 0, 2, 0, 2,
ax_anim 8, 0, 166, 0, 3, 0, 3,
ax_anim_terminator
sFlygonAnims_7_6:
ax_anim 2, 0, 167, 2, 2, 2, 2,
ax_anim 8, 0, 167, 3, 3, 3, 3,
ax_anim_terminator
sFlygonAnims_7_7:
ax_anim 2, 0, 168, 2, 0, 2, 0,
ax_anim 8, 0, 168, 3, 0, 3, 0,
ax_anim_terminator
sFlygonAnims_7_8:
ax_anim 2, 0, 169, 2, -2, 2, -2,
ax_anim 8, 0, 169, 3, -3, 3, -3,
ax_anim_terminator
.align 2
sFlygonAnims_8_1:
ax_anim 8, 0, 171, 0, -2, 0, 0,
ax_anim 9, 0, 170, 0, 0, 0, 0,
ax_anim 8, 0, 172, 0, 0, 0, 0,
ax_anim 8, 0, 172, 0, -1, 0, 0,
ax_anim 11, 0, 172, 0, -2, 0, 0,
ax_anim 8, 0, 170, 0, -4, 0, 0,
ax_anim 8, 0, 171, 0, -4, 0, 0,
ax_anim_terminator
sFlygonAnims_8_2:
ax_anim 8, 0, 174, 0, -2, 0, 0,
ax_anim 9, 0, 173, 0, 0, 0, 0,
ax_anim 8, 0, 175, 0, 0, 0, 0,
ax_anim 8, 0, 175, 0, -1, 0, 0,
ax_anim 11, 0, 175, 0, -2, 0, 0,
ax_anim 8, 0, 173, 0, -4, 0, 0,
ax_anim 8, 0, 174, 0, -4, 0, 0,
ax_anim_terminator
sFlygonAnims_8_3:
ax_anim 8, 0, 177, 0, -2, 0, 0,
ax_anim 9, 0, 176, 0, 0, 0, 0,
ax_anim 8, 0, 178, 0, 0, 0, 0,
ax_anim 8, 0, 178, 0, -1, 0, 0,
ax_anim 11, 0, 178, 0, -2, 0, 0,
ax_anim 8, 0, 176, 0, -4, 0, 0,
ax_anim 8, 0, 177, 0, -4, 0, 0,
ax_anim_terminator
sFlygonAnims_8_4:
ax_anim 8, 0, 180, 0, -2, 0, 0,
ax_anim 9, 0, 179, 0, 0, 0, 0,
ax_anim 8, 0, 181, 0, 0, 0, 0,
ax_anim 8, 0, 181, 0, -1, 0, 0,
ax_anim 11, 0, 181, 0, -2, 0, 0,
ax_anim 8, 0, 179, 0, -4, 0, 0,
ax_anim 8, 0, 180, 0, -4, 0, 0,
ax_anim_terminator
sFlygonAnims_8_5:
ax_anim 8, 0, 183, 0, -2, 0, 0,
ax_anim 9, 0, 182, 0, 0, 0, 0,
ax_anim 8, 0, 184, 0, 0, 0, 0,
ax_anim 8, 0, 184, 0, -1, 0, 0,
ax_anim 11, 0, 184, 0, -2, 0, 0,
ax_anim 8, 0, 182, 0, -4, 0, 0,
ax_anim 8, 0, 183, 0, -4, 0, 0,
ax_anim_terminator
sFlygonAnims_8_6:
ax_anim 8, 0, 186, 0, -2, 0, 0,
ax_anim 9, 0, 185, 0, 0, 0, 0,
ax_anim 8, 0, 187, 0, 0, 0, 0,
ax_anim 8, 0, 187, 0, -1, 0, 0,
ax_anim 11, 0, 187, 0, -2, 0, 0,
ax_anim 8, 0, 185, 0, -4, 0, 0,
ax_anim 8, 0, 186, 0, -4, 0, 0,
ax_anim_terminator
sFlygonAnims_8_7:
ax_anim 8, 0, 189, 0, -2, 0, 0,
ax_anim 9, 0, 188, 0, 0, 0, 0,
ax_anim 8, 0, 190, 0, 0, 0, 0,
ax_anim 8, 0, 190, 0, -1, 0, 0,
ax_anim 11, 0, 190, 0, -2, 0, 0,
ax_anim 8, 0, 188, 0, -4, 0, 0,
ax_anim 8, 0, 189, 0, -4, 0, 0,
ax_anim_terminator
sFlygonAnims_8_8:
ax_anim 8, 0, 192, 0, -2, 0, 0,
ax_anim 9, 0, 191, 0, 0, 0, 0,
ax_anim 8, 0, 193, 0, 0, 0, 0,
ax_anim 8, 0, 193, 0, -1, 0, 0,
ax_anim 11, 0, 193, 0, -2, 0, 0,
ax_anim 8, 0, 191, 0, -4, 0, 0,
ax_anim 8, 0, 192, 0, -4, 0, 0,
ax_anim_terminator
.align 2
sFlygonAnims_9_1:
ax_anim 2, 0, 194, 0, 0, 0, 0,
ax_anim 1, 0, 195, 6, 3, 6, 3,
ax_anim 2, 0, 196, 9, 13, 9, 13,
ax_anim 2, 0, 197, 7, 23, 7, 21,
ax_anim 3, 0, 198, 0, 25, 0, 22,
ax_anim 2, 3, 199, -7, 23, -7, 21,
ax_anim 2, 0, 200, -9, 13, -9, 13,
ax_anim 1, 0, 201, -6, 3, -6, 3,
ax_anim 1, 0, 194, 0, 0, 0, 0,
ax_anim_terminator
sFlygonAnims_9_2:
ax_anim 2, 0, 201, 0, 0, 0, 0,
ax_anim 1, 0, 194, 8, 2, 8, 2,
ax_anim 2, 0, 195, 19, 10, 19, 10,
ax_anim 2, 0, 196, 20, 20, 20, 18,
ax_anim 3, 0, 197, 17, 26, 17, 23,
ax_anim 2, 3, 198, 10, 25, 10, 23,
ax_anim 2, 0, 199, 4, 18, 4, 18,
ax_anim 1, 0, 200, 0, 7, 0, 7,
ax_anim 1, 0, 201, 0, 0, 0, 0,
ax_anim_terminator
sFlygonAnims_9_3:
ax_anim 2, 0, 200, 0, 0, 0, 0,
ax_anim 1, 0, 201, 4, -3, 4, -3,
ax_anim 2, 0, 194, 11, -3, 11, -3,
ax_anim 2, 0, 195, 15, -1, 15, -2,
ax_anim 3, 0, 196, 17, 3, 17, 0,
ax_anim 2, 3, 197, 15, 8, 15, 7,
ax_anim 2, 0, 198, 9, 10, 9, 10,
ax_anim 1, 0, 199, 4, 5, 4, 5,
ax_anim 1, 0, 200, 0, 0, 0, 0,
ax_anim_terminator
sFlygonAnims_9_4:
ax_anim 2, 0, 199, 0, 0, 0, 0,
ax_anim 1, 0, 200, 1, -8, 1, -8,
ax_anim 2, 0, 201, 4, -16, 4, -16,
ax_anim 2, 0, 194, 12, -20, 12, -22,
ax_anim 3, 0, 195, 18, -18, 18, -21,
ax_anim 2, 3, 196, 20, -12, 20, -14,
ax_anim 2, 0, 197, 17, -4, 17, -4,
ax_anim 1, 0, 198, 7, -1, 7, -1,
ax_anim 1, 0, 199, 0, 0, 0, 0,
ax_anim_terminator
sFlygonAnims_9_5:
ax_anim 2, 0, 198, 0, 0, 0, 0,
ax_anim 1, 0, 199, -7, -4, -7, -4,
ax_anim 2, 0, 200, -9, -12, -9, -12,
ax_anim 2, 0, 201, -7, -18, -7, -20,
ax_anim 3, 0, 194, 0, -19, 0, -23,
ax_anim 2, 3, 195, 7, -18, 7, -20,
ax_anim 2, 0, 196, 9, -12, 9, -12,
ax_anim 1, 0, 197, 7, -4, 7, -4,
ax_anim 1, 0, 198, 0, 0, 0, 0,
ax_anim_terminator
sFlygonAnims_9_6:
ax_anim 2, 0, 197, 0, 0, 0, 0,
ax_anim 1, 0, 196, 1, -8, 1, -8,
ax_anim 2, 0, 195, -4, -16, -4, -16,
ax_anim 2, 0, 194, -12, -20, -12, -22,
ax_anim 3, 0, 201, -18, -18, -18, -21,
ax_anim 2, 3, 200, -20, -12, -20, -14,
ax_anim 2, 0, 199, -17, -4, -17, -4,
ax_anim 1, 0, 198, -7, -1, -7, -1,
ax_anim 1, 0, 197, 0, 0, 0, 0,
ax_anim_terminator
sFlygonAnims_9_7:
ax_anim 2, 0, 196, 0, 0, 0, 0,
ax_anim 1, 0, 195, -4, -3, -4, -3,
ax_anim 2, 0, 194, -11, -3, -11, -3,
ax_anim 2, 0, 201, -15, -1, -15, -2,
ax_anim 3, 0, 200, -17, 3, -17, 0,
ax_anim 2, 3, 199, -15, 8, -15, 7,
ax_anim 2, 0, 198, -9, 10, -9, 10,
ax_anim 1, 0, 197, -4, 5, -4, 5,
ax_anim 1, 0, 196, 0, 0, 0, 0,
ax_anim_terminator
sFlygonAnims_9_8:
ax_anim 2, 0, 195, 0, 0, 0, 0,
ax_anim 1, 0, 194, -8, 2, -8, 2,
ax_anim 2, 0, 201, -19, 10, -19, 10,
ax_anim 2, 0, 200, -20, 20, -20, 18,
ax_anim 3, 0, 199, -17, 26, -17, 23,
ax_anim 2, 3, 198, -10, 25, -10, 23,
ax_anim 2, 0, 197, -4, 18, -4, 18,
ax_anim 1, 0, 196, 0, 7, 0, 7,
ax_anim 1, 0, 195, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sFlygonAnims_10_1:
ax_anim 2, 0, 202, 0, 0, 0, 0,
ax_anim 2, 0, 202, 6, 0, 6, 0,
ax_anim 2, 0, 202, -6, 0, -6, 0,
ax_anim 2, 0, 202, 10, 0, 10, 0,
ax_anim 2, 0, 202, -10, 0, -10, 0,
ax_anim 2, 0, 202, 12, 0, 12, 0,
ax_anim 3, 0, 202, -12, 0, -12, 0,
ax_anim 3, 0, 202, 13, 0, 13, 0,
ax_anim 3, 0, 202, -13, 0, -13, 0,
ax_anim 2, 0, 202, 12, 0, 12, 0,
ax_anim 3, 0, 202, -12, 0, -12, 0,
ax_anim 2, 0, 202, 10, 0, 10, 0,
ax_anim 2, 0, 202, -10, 0, -10, 0,
ax_anim 2, 0, 202, 6, 0, 6, 0,
ax_anim 2, 0, 202, -6, 0, -6, 0,
ax_anim 2, 0, 202, 0, 0, 0, 0,
ax_anim_terminator
sFlygonAnims_10_2:
ax_anim 2, 0, 203, 0, 0, 0, 0,
ax_anim 2, 0, 203, 6, -6, 6, -6,
ax_anim 2, 0, 203, -6, 6, -6, 6,
ax_anim 2, 0, 203, 10, -10, 10, -10,
ax_anim 2, 0, 203, -10, 10, -10, 10,
ax_anim 2, 0, 203, 12, -12, 12, -12,
ax_anim 3, 0, 203, -12, 12, -12, 12,
ax_anim 3, 0, 203, 13, -13, 13, -13,
ax_anim 3, 0, 203, -13, 13, -13, 13,
ax_anim 2, 0, 203, 12, -12, 12, -12,
ax_anim 3, 0, 203, -12, 12, -12, 12,
ax_anim 2, 0, 203, 10, -10, 10, -10,
ax_anim 2, 0, 203, -10, 10, -10, 10,
ax_anim 2, 0, 203, 6, -6, 6, -6,
ax_anim 2, 0, 203, -6, 6, -6, 6,
ax_anim 2, 0, 203, 0, 0, 0, 0,
ax_anim_terminator
sFlygonAnims_10_3:
ax_anim 2, 0, 204, 0, 0, 0, 0,
ax_anim 2, 0, 204, 0, -6, 0, -6,
ax_anim 2, 0, 204, 0, 6, 0, 6,
ax_anim 2, 0, 204, 0, -10, 0, -10,
ax_anim 2, 0, 204, 0, 10, 0, 10,
ax_anim 2, 0, 204, 0, -12, 0, -12,
ax_anim 3, 0, 204, 0, 12, 0, 12,
ax_anim 3, 0, 204, 0, -13, 0, -13,
ax_anim 3, 0, 204, 0, 13, 0, 13,
ax_anim 2, 0, 204, 0, -12, 0, -12,
ax_anim 3, 0, 204, 0, 12, 0, 12,
ax_anim 2, 0, 204, 0, -10, 0, -10,
ax_anim 2, 0, 204, 0, 10, 0, 10,
ax_anim 2, 0, 204, 0, -6, 0, -6,
ax_anim 2, 0, 204, 0, 6, 0, 6,
ax_anim 2, 0, 204, 0, 0, 0, 0,
ax_anim_terminator
sFlygonAnims_10_4:
ax_anim 2, 0, 205, 0, 0, 0, 0,
ax_anim 2, 0, 205, -6, -6, -6, -6,
ax_anim 2, 0, 205, 6, 6, 6, 6,
ax_anim 2, 0, 205, -10, -10, -10, -10,
ax_anim 2, 0, 205, 10, 10, 10, 10,
ax_anim 2, 0, 205, -12, -12, -12, -12,
ax_anim 3, 0, 205, 12, 12, 12, 12,
ax_anim 3, 0, 205, -13, -13, -13, -13,
ax_anim 3, 0, 205, 13, 13, 13, 13,
ax_anim 2, 0, 205, -12, -12, -12, -12,
ax_anim 3, 0, 205, 12, 12, 12, 12,
ax_anim 2, 0, 205, -10, -10, -10, -10,
ax_anim 2, 0, 205, 10, 10, 10, 10,
ax_anim 2, 0, 205, -6, -6, -6, -6,
ax_anim 2, 0, 205, 6, 6, 6, 6,
ax_anim 2, 0, 205, 0, 0, 0, 0,
ax_anim_terminator
sFlygonAnims_10_5:
ax_anim 2, 0, 206, 0, 0, 0, 0,
ax_anim 2, 0, 206, 6, 0, 6, 0,
ax_anim 2, 0, 206, -6, 0, -6, 0,
ax_anim 2, 0, 206, 10, 0, 10, 0,
ax_anim 2, 0, 206, -10, 0, -10, 0,
ax_anim 2, 0, 206, 12, 0, 12, 0,
ax_anim 3, 0, 206, -12, 0, -12, 0,
ax_anim 3, 0, 206, 13, 0, 13, 0,
ax_anim 3, 0, 206, -13, 0, -13, 0,
ax_anim 2, 0, 206, 12, 0, 12, 0,
ax_anim 3, 0, 206, -12, 0, -12, 0,
ax_anim 2, 0, 206, 10, 0, 10, 0,
ax_anim 2, 0, 206, -10, 0, -10, 0,
ax_anim 2, 0, 206, 6, 0, 6, 0,
ax_anim 2, 0, 206, -6, 0, -6, 0,
ax_anim 2, 0, 206, 0, 0, 0, 0,
ax_anim_terminator
sFlygonAnims_10_6:
ax_anim 2, 0, 207, 0, 0, 0, 0,
ax_anim 2, 0, 207, 6, -6, 6, -6,
ax_anim 2, 0, 207, -6, 6, -6, 6,
ax_anim 2, 0, 207, 10, -10, 10, -10,
ax_anim 2, 0, 207, -10, 10, -10, 10,
ax_anim 2, 0, 207, 12, -12, 12, -12,
ax_anim 3, 0, 207, -12, 12, -12, 12,
ax_anim 3, 0, 207, 13, -13, 13, -13,
ax_anim 3, 0, 207, -13, 13, -13, 13,
ax_anim 2, 0, 207, 12, -12, 12, -12,
ax_anim 3, 0, 207, -12, 12, -12, 12,
ax_anim 2, 0, 207, 10, -10, 10, -10,
ax_anim 2, 0, 207, -10, 10, -10, 10,
ax_anim 2, 0, 207, 6, -6, 6, -6,
ax_anim 2, 0, 207, -6, 6, -6, 6,
ax_anim 2, 0, 207, 0, 0, 0, 0,
ax_anim_terminator
sFlygonAnims_10_7:
ax_anim 2, 0, 208, 0, 0, 0, 0,
ax_anim 2, 0, 208, 0, -6, 0, -6,
ax_anim 2, 0, 208, 0, 6, 0, 6,
ax_anim 2, 0, 208, 0, -10, 0, -10,
ax_anim 2, 0, 208, 0, 10, 0, 10,
ax_anim 2, 0, 208, 0, -12, 0, -12,
ax_anim 3, 0, 208, 0, 12, 0, 12,
ax_anim 3, 0, 208, 0, -13, 0, -13,
ax_anim 3, 0, 208, 0, 13, 0, 13,
ax_anim 2, 0, 208, 0, -12, 0, -12,
ax_anim 3, 0, 208, 0, 12, 0, 12,
ax_anim 2, 0, 208, 0, -10, 0, -10,
ax_anim 2, 0, 208, 0, 10, 0, 10,
ax_anim 2, 0, 208, 0, -6, 0, -6,
ax_anim 2, 0, 208, 0, 6, 0, 6,
ax_anim 2, 0, 208, 0, 0, 0, 0,
ax_anim_terminator
sFlygonAnims_10_8:
ax_anim 2, 0, 209, 0, 0, 0, 0,
ax_anim 2, 0, 209, -6, -6, -6, -6,
ax_anim 2, 0, 209, 6, 6, 6, 6,
ax_anim 2, 0, 209, -10, -10, -10, -10,
ax_anim 2, 0, 209, 10, 10, 10, 10,
ax_anim 2, 0, 209, -12, -12, -12, -12,
ax_anim 3, 0, 209, 12, 12, 12, 12,
ax_anim 3, 0, 209, -13, -13, -13, -13,
ax_anim 3, 0, 209, 13, 13, 13, 13,
ax_anim 2, 0, 209, -12, -12, -12, -12,
ax_anim 3, 0, 209, 12, 12, 12, 12,
ax_anim 2, 0, 209, -10, -10, -10, -10,
ax_anim 2, 0, 209, 10, 10, 10, 10,
ax_anim 2, 0, 209, -6, -6, -6, -6,
ax_anim 2, 0, 209, 6, 6, 6, 6,
ax_anim 2, 0, 209, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sFlygonAnims_11_1:
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 1, 0, 211, 0, -10, 0, 0,
ax_anim 2, 0, 211, 0, -16, 0, 0,
ax_anim 3, 0, 211, 0, -19, 0, 0,
ax_anim 4, 0, 211, 0, -21, 0, 0,
ax_anim 4, 0, 210, 0, -23, 0, 0,
ax_anim 3, 0, 212, 0, -22, 0, 0,
ax_anim 2, 0, 212, 0, -18, 0, 0,
ax_anim 1, 0, 212, 0, -12, 0, 0,
ax_anim 2, 2, 210, 0, 3, 0, 0,
ax_anim_terminator
sFlygonAnims_11_2:
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 1, 0, 214, 0, -10, 0, 0,
ax_anim 2, 0, 214, 0, -16, 0, 0,
ax_anim 3, 0, 214, 0, -20, 0, 0,
ax_anim 4, 0, 214, 0, -21, 0, 0,
ax_anim 4, 0, 213, 0, -23, 0, 0,
ax_anim 3, 0, 215, 0, -22, 0, 0,
ax_anim 2, 0, 215, 0, -18, 0, 0,
ax_anim 1, 0, 215, 0, -12, 0, 0,
ax_anim 2, 2, 213, 0, 3, 0, 0,
ax_anim_terminator
sFlygonAnims_11_3:
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 1, 0, 217, 0, -10, 0, 0,
ax_anim 2, 0, 217, 0, -16, 0, 0,
ax_anim 3, 0, 217, 0, -20, 0, 0,
ax_anim 4, 0, 217, 0, -21, 0, 0,
ax_anim 4, 0, 216, 0, -23, 0, 0,
ax_anim 3, 0, 218, 0, -22, 0, 0,
ax_anim 2, 0, 218, 0, -18, 0, 0,
ax_anim 1, 0, 218, 0, -12, 0, 0,
ax_anim 2, 2, 216, 0, 3, 0, 0,
ax_anim_terminator
sFlygonAnims_11_4:
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 1, 0, 220, 0, -10, 0, 0,
ax_anim 2, 0, 220, 0, -16, 0, 0,
ax_anim 3, 0, 220, 0, -20, 0, 0,
ax_anim 4, 0, 220, 0, -21, 0, 0,
ax_anim 4, 0, 219, 0, -22, 0, 0,
ax_anim 3, 0, 221, 0, -21, 0, 0,
ax_anim 2, 0, 221, 0, -17, 0, 0,
ax_anim 1, 0, 221, 0, -11, 0, 0,
ax_anim 2, 2, 219, 0, 3, 0, 0,
ax_anim_terminator
sFlygonAnims_11_5:
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 1, 0, 223, 0, -10, 0, 0,
ax_anim 2, 0, 223, 0, -16, 0, 0,
ax_anim 3, 0, 223, 0, -20, 0, 0,
ax_anim 4, 0, 223, 0, -21, 0, 0,
ax_anim 4, 0, 222, 0, -23, 0, 0,
ax_anim 3, 0, 224, 0, -22, 0, 0,
ax_anim 2, 0, 224, 0, -18, 0, 0,
ax_anim 1, 0, 224, 0, -12, 0, 0,
ax_anim 2, 2, 222, 0, 4, 0, 0,
ax_anim_terminator
sFlygonAnims_11_6:
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 1, 0, 226, 0, -10, 0, 0,
ax_anim 2, 0, 226, 0, -16, 0, 0,
ax_anim 3, 0, 226, 0, -20, 0, 0,
ax_anim 4, 0, 226, 0, -21, 0, 0,
ax_anim 4, 0, 225, 0, -22, 0, 0,
ax_anim 3, 0, 227, 0, -21, 0, 0,
ax_anim 2, 0, 227, 0, -17, 0, 0,
ax_anim 1, 0, 227, 0, -11, 0, 0,
ax_anim 2, 2, 225, 0, 3, 0, 0,
ax_anim_terminator
sFlygonAnims_11_7:
ax_anim 2, 0, 228, 0, 0, 0, 0,
ax_anim 1, 0, 229, 0, -10, 0, 0,
ax_anim 2, 0, 229, 0, -16, 0, 0,
ax_anim 3, 0, 229, 0, -20, 0, 0,
ax_anim 4, 0, 229, 0, -21, 0, 0,
ax_anim 4, 0, 228, 0, -23, 0, 0,
ax_anim 3, 0, 230, 0, -22, 0, 0,
ax_anim 2, 0, 230, 0, -18, 0, 0,
ax_anim 1, 0, 230, 0, -12, 0, 0,
ax_anim 2, 2, 228, 0, 3, 0, 0,
ax_anim_terminator
sFlygonAnims_11_8:
ax_anim 2, 0, 231, 0, 0, 0, 0,
ax_anim 1, 0, 232, 0, -10, 0, 0,
ax_anim 2, 0, 232, 0, -16, 0, 0,
ax_anim 3, 0, 232, 0, -20, 0, 0,
ax_anim 4, 0, 232, 0, -21, 0, 0,
ax_anim 4, 0, 231, 0, -23, 0, 0,
ax_anim 3, 0, 233, 0, -22, 0, 0,
ax_anim 2, 0, 233, 0, -18, 0, 0,
ax_anim 1, 0, 233, 0, -12, 0, 0,
ax_anim 2, 2, 231, 0, 3, 0, 0,
ax_anim_terminator
.align 2
sFlygonAnims_12_1:
ax_anim 2, 0, 234, 1, 0, 1, 0,
ax_anim 2, 0, 234, 0, 0, 0, 0,
ax_anim 2, 0, 234, 1, 0, 1, 0,
ax_anim 2, 0, 234, 0, 0, 0, 0,
ax_anim 2, 0, 234, 1, 0, 1, 0,
ax_anim 2, 2, 234, 0, 0, 0, 0,
ax_anim 2, 0, 234, 1, 0, 1, 0,
ax_anim 2, 0, 234, 0, 0, 0, 0,
ax_anim 2, 0, 234, 1, 0, 1, 0,
ax_anim 2, 1, 234, 0, 0, 0, 0,
ax_anim_terminator
sFlygonAnims_12_2:
ax_anim 2, 0, 241, 1, -1, 1, -1,
ax_anim 2, 0, 241, 0, 0, 0, 0,
ax_anim 2, 0, 241, 1, -1, 1, -1,
ax_anim 2, 0, 241, 0, 0, 0, 0,
ax_anim 2, 0, 241, 1, -1, 1, -1,
ax_anim 2, 2, 241, 0, 0, 0, 0,
ax_anim 2, 0, 241, 1, -1, 1, -1,
ax_anim 2, 0, 241, 0, 0, 0, 0,
ax_anim 2, 0, 241, 1, -1, 1, -1,
ax_anim 2, 1, 241, 0, 0, 0, 0,
ax_anim_terminator
sFlygonAnims_12_3:
ax_anim 2, 0, 240, 0, -1, 0, -1,
ax_anim 2, 0, 240, 0, 0, 0, 0,
ax_anim 2, 0, 240, 0, -1, 0, -1,
ax_anim 2, 0, 240, 0, 0, 0, 0,
ax_anim 2, 0, 240, 0, -1, 0, -1,
ax_anim 2, 2, 240, 0, 0, 0, 0,
ax_anim 2, 0, 240, 0, -1, 0, -1,
ax_anim 2, 0, 240, 0, 0, 0, 0,
ax_anim 2, 0, 240, 0, -1, 0, -1,
ax_anim 2, 1, 240, 0, 0, 0, 0,
ax_anim_terminator
sFlygonAnims_12_4:
ax_anim 2, 0, 239, -1, -1, -1, -1,
ax_anim 2, 0, 239, 0, 0, 0, 0,
ax_anim 2, 0, 239, -1, -1, -1, -1,
ax_anim 2, 0, 239, 0, 0, 0, 0,
ax_anim 2, 0, 239, -1, -1, -1, -1,
ax_anim 2, 2, 239, 0, 0, 0, 0,
ax_anim 2, 0, 239, -1, -1, -1, -1,
ax_anim 2, 0, 239, 0, 0, 0, 0,
ax_anim 2, 0, 239, -1, -1, -1, -1,
ax_anim 2, 1, 239, 0, 0, 0, 0,
ax_anim_terminator
sFlygonAnims_12_5:
ax_anim 2, 0, 238, 1, 0, 1, 0,
ax_anim 2, 0, 238, 0, 0, 0, 0,
ax_anim 2, 0, 238, 1, 0, 1, 0,
ax_anim 2, 0, 238, 0, 0, 0, 0,
ax_anim 2, 0, 238, 1, 0, 1, 0,
ax_anim 2, 2, 238, 0, 0, 0, 0,
ax_anim 2, 0, 238, 1, 0, 1, 0,
ax_anim 2, 0, 238, 0, 0, 0, 0,
ax_anim 2, 0, 238, 1, 0, 1, 0,
ax_anim 2, 1, 238, 0, 0, 0, 0,
ax_anim_terminator
sFlygonAnims_12_6:
ax_anim 2, 0, 237, 1, -1, 1, -1,
ax_anim 2, 0, 237, 0, 0, 0, 0,
ax_anim 2, 0, 237, 1, -1, 1, -1,
ax_anim 2, 0, 237, 0, 0, 0, 0,
ax_anim 2, 0, 237, 1, -1, 1, -1,
ax_anim 2, 2, 237, 0, 0, 0, 0,
ax_anim 2, 0, 237, 1, -1, 1, -1,
ax_anim 2, 0, 237, 0, 0, 0, 0,
ax_anim 2, 0, 237, 1, -1, 1, -1,
ax_anim 2, 1, 237, 0, 0, 0, 0,
ax_anim_terminator
sFlygonAnims_12_7:
ax_anim 2, 0, 236, 0, -1, 0, -1,
ax_anim 2, 0, 236, 0, 0, 0, 0,
ax_anim 2, 0, 236, 0, -1, 0, -1,
ax_anim 2, 0, 236, 0, 0, 0, 0,
ax_anim 2, 0, 236, 0, -1, 0, -1,
ax_anim 2, 2, 236, 0, 0, 0, 0,
ax_anim 2, 0, 236, 0, -1, 0, -1,
ax_anim 2, 0, 236, 0, 0, 0, 0,
ax_anim 2, 0, 236, 0, -1, 0, -1,
ax_anim 2, 1, 236, 0, 0, 0, 0,
ax_anim_terminator
sFlygonAnims_12_8:
ax_anim 2, 0, 235, -1, -1, -1, -1,
ax_anim 2, 0, 235, 0, 0, 0, 0,
ax_anim 2, 0, 235, -1, -1, -1, -1,
ax_anim 2, 0, 235, 0, 0, 0, 0,
ax_anim 2, 0, 235, -1, -1, -1, -1,
ax_anim 2, 2, 235, 0, 0, 0, 0,
ax_anim 2, 0, 235, -1, -1, -1, -1,
ax_anim 2, 0, 235, 0, 0, 0, 0,
ax_anim 2, 0, 235, -1, -1, -1, -1,
ax_anim 2, 1, 235, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sFlygonAnims_13_1:
ax_anim 2, 0, 242, 0, 0, 0, 0,
ax_anim 2, 0, 243, 0, 0, 0, 0,
ax_anim 2, 0, 244, 0, 0, 0, 0,
ax_anim 2, 0, 245, 0, 0, 0, 0,
ax_anim 2, 0, 246, 0, 0, 0, 0,
ax_anim 2, 0, 247, 0, 0, 0, 0,
ax_anim 2, 0, 248, 0, 0, 0, 0,
ax_anim 2, 0, 249, 0, 0, 0, 0,
ax_anim 2, 2, 242, 0, 0, 0, 0,
ax_anim_terminator
sFlygonAnims_13_2:
ax_anim 2, 0, 249, 0, 0, 0, 0,
ax_anim 2, 0, 242, 0, 0, 0, 0,
ax_anim 2, 0, 243, 0, 0, 0, 0,
ax_anim 2, 0, 244, 0, 0, 0, 0,
ax_anim 2, 0, 245, 0, 0, 0, 0,
ax_anim 2, 0, 246, 0, 0, 0, 0,
ax_anim 2, 0, 247, 0, 0, 0, 0,
ax_anim 2, 0, 248, 0, 0, 0, 0,
ax_anim 2, 2, 249, 0, 0, 0, 0,
ax_anim_terminator
sFlygonAnims_13_3:
ax_anim 2, 0, 248, 0, 0, 0, 0,
ax_anim 2, 0, 249, 0, 0, 0, 0,
ax_anim 2, 0, 242, 0, 0, 0, 0,
ax_anim 2, 0, 243, 0, 0, 0, 0,
ax_anim 2, 0, 244, 0, 0, 0, 0,
ax_anim 2, 0, 245, 0, 0, 0, 0,
ax_anim 2, 0, 246, 0, 0, 0, 0,
ax_anim 2, 0, 247, 0, 0, 0, 0,
ax_anim 2, 2, 248, 0, 0, 0, 0,
ax_anim_terminator
sFlygonAnims_13_4:
ax_anim 2, 0, 247, 0, 0, 0, 0,
ax_anim 2, 0, 248, 0, 0, 0, 0,
ax_anim 2, 0, 249, 0, 0, 0, 0,
ax_anim 2, 0, 242, 0, 0, 0, 0,
ax_anim 2, 0, 243, 0, 0, 0, 0,
ax_anim 2, 0, 244, 0, 0, 0, 0,
ax_anim 2, 0, 245, 0, 0, 0, 0,
ax_anim 2, 0, 246, 0, 0, 0, 0,
ax_anim 2, 2, 247, 0, 0, 0, 0,
ax_anim_terminator
sFlygonAnims_13_5:
ax_anim 2, 0, 246, 0, 0, 0, 0,
ax_anim 2, 0, 247, 0, 0, 0, 0,
ax_anim 2, 0, 248, 0, 0, 0, 0,
ax_anim 2, 0, 249, 0, 0, 0, 0,
ax_anim 2, 0, 242, 0, 0, 0, 0,
ax_anim 2, 0, 243, 0, 0, 0, 0,
ax_anim 2, 0, 244, 0, 0, 0, 0,
ax_anim 2, 0, 245, 0, 0, 0, 0,
ax_anim 2, 2, 246, 0, 0, 0, 0,
ax_anim_terminator
sFlygonAnims_13_6:
ax_anim 2, 0, 245, 0, 0, 0, 0,
ax_anim 2, 0, 246, 0, 0, 0, 0,
ax_anim 2, 0, 247, 0, 0, 0, 0,
ax_anim 2, 0, 248, 0, 0, 0, 0,
ax_anim 2, 0, 249, 0, 0, 0, 0,
ax_anim 2, 0, 242, 0, 0, 0, 0,
ax_anim 2, 0, 243, 0, 0, 0, 0,
ax_anim 2, 0, 244, 0, 0, 0, 0,
ax_anim 2, 2, 245, 0, 0, 0, 0,
ax_anim_terminator
sFlygonAnims_13_7:
ax_anim 2, 0, 244, 0, 0, 0, 0,
ax_anim 2, 0, 245, 0, 0, 0, 0,
ax_anim 2, 0, 246, 0, 0, 0, 0,
ax_anim 2, 0, 247, 0, 0, 0, 0,
ax_anim 2, 0, 248, 0, 0, 0, 0,
ax_anim 2, 0, 249, 0, 0, 0, 0,
ax_anim 2, 0, 242, 0, 0, 0, 0,
ax_anim 2, 0, 243, 0, 0, 0, 0,
ax_anim 2, 2, 244, 0, 0, 0, 0,
ax_anim_terminator
sFlygonAnims_13_8:
ax_anim 2, 0, 243, 0, 0, 0, 0,
ax_anim 2, 0, 244, 0, 0, 0, 0,
ax_anim 2, 0, 245, 0, 0, 0, 0,
ax_anim 2, 0, 246, 0, 0, 0, 0,
ax_anim 2, 0, 247, 0, 0, 0, 0,
ax_anim 2, 0, 248, 0, 0, 0, 0,
ax_anim 2, 0, 249, 0, 0, 0, 0,
ax_anim 2, 0, 242, 0, 0, 0, 0,
ax_anim 2, 2, 243, 0, 0, 0, 0,
ax_anim_terminator
sFlygonGfx1:
.incbin "baserom.gba", 0x1377534, 0x200
sFlygonSprites1:
ax_sprite sFlygonGfx1, 0x200
ax_sprite_terminator
sFlygonGfx2:
.incbin "baserom.gba", 0x1377744, 0x200
sFlygonSprites2:
ax_sprite sFlygonGfx2, 0x200
ax_sprite_terminator
sFlygonGfx3:
.incbin "baserom.gba", 0x1377954, 0x200
sFlygonSprites3:
ax_sprite sFlygonGfx3, 0x200
ax_sprite_terminator
sFlygonGfx4:
.incbin "baserom.gba", 0x1377B64, 0x200
sFlygonSprites4:
ax_sprite sFlygonGfx4, 0x200
ax_sprite_terminator
sFlygonGfx5:
.incbin "baserom.gba", 0x1377D74, 0x200
sFlygonSprites5:
ax_sprite sFlygonGfx5, 0x200
ax_sprite_terminator
sFlygonGfx6:
.incbin "baserom.gba", 0x1377F84, 0x200
sFlygonSprites6:
ax_sprite sFlygonGfx6, 0x200
ax_sprite_terminator
sFlygonGfx7:
.incbin "baserom.gba", 0x1378194, 0x200
sFlygonSprites7:
ax_sprite sFlygonGfx7, 0x200
ax_sprite_terminator
sFlygonGfx8:
.incbin "baserom.gba", 0x13783A4, 0x200
sFlygonSprites8:
ax_sprite sFlygonGfx8, 0x200
ax_sprite_terminator
sFlygonGfx9:
.incbin "baserom.gba", 0x13785B4, 0x200
sFlygonSprites9:
ax_sprite sFlygonGfx9, 0x200
ax_sprite_terminator
sFlygonGfx10:
.incbin "baserom.gba", 0x13787C4, 0x200
sFlygonSprites10:
ax_sprite sFlygonGfx10, 0x200
ax_sprite_terminator
sFlygonGfx11:
.incbin "baserom.gba", 0x13789D4, 0x200
sFlygonSprites11:
ax_sprite sFlygonGfx11, 0x200
ax_sprite_terminator
sFlygonGfx12:
.incbin "baserom.gba", 0x1378BE4, 0x200
sFlygonSprites12:
ax_sprite sFlygonGfx12, 0x200
ax_sprite_terminator
sFlygonGfx13:
.incbin "baserom.gba", 0x1378DF4, 0x200
sFlygonSprites13:
ax_sprite sFlygonGfx13, 0x200
ax_sprite_terminator
sFlygonGfx14:
.incbin "baserom.gba", 0x1379004, 0x200
sFlygonSprites14:
ax_sprite sFlygonGfx14, 0x200
ax_sprite_terminator
sFlygonGfx15:
.incbin "baserom.gba", 0x1379214, 0x100
sFlygonSprites15:
ax_sprite sFlygonGfx15, 0x100
ax_sprite_terminator
sFlygonGfx16:
.incbin "baserom.gba", 0x1379324, 0x80
sFlygonSprites16:
ax_sprite sFlygonGfx16, 0x80
ax_sprite_terminator
sFlygonGfx17:
.incbin "baserom.gba", 0x13793B4, 0x40
sFlygonSprites17:
ax_sprite sFlygonGfx17, 0x40
ax_sprite_terminator
sFlygonGfx18:
.incbin "baserom.gba", 0x1379404, 0x20
sFlygonSprites18:
ax_sprite sFlygonGfx18, 0x20
ax_sprite_terminator
sFlygonGfx19:
.incbin "baserom.gba", 0x1379434, 0x20
sFlygonGfx19_1:
.incbin "baserom.gba", 0x1379454, 0xA0
sFlygonSprites19:
ax_sprite sFlygonGfx19, 0x20
ax_sprite 0, 0x20
ax_sprite sFlygonGfx19_1, 0xa0
ax_sprite 0, 0x20
ax_sprite_terminator
sFlygonGfx20:
.incbin "baserom.gba", 0x137951C, 0x80
sFlygonSprites20:
ax_sprite sFlygonGfx20, 0x80
ax_sprite_terminator
sFlygonGfx21:
.incbin "baserom.gba", 0x13795AC, 0x40
sFlygonSprites21:
ax_sprite sFlygonGfx21, 0x40
ax_sprite_terminator
sFlygonGfx22:
.incbin "baserom.gba", 0x13795FC, 0x20
sFlygonSprites22:
ax_sprite sFlygonGfx22, 0x20
ax_sprite_terminator
sFlygonGfx23:
.incbin "baserom.gba", 0x137962C, 0x20
sFlygonGfx23_1:
.incbin "baserom.gba", 0x137964C, 0xA0
sFlygonSprites23:
ax_sprite sFlygonGfx23, 0x20
ax_sprite 0, 0x20
ax_sprite sFlygonGfx23_1, 0xa0
ax_sprite 0, 0x20
ax_sprite_terminator
sFlygonGfx24:
.incbin "baserom.gba", 0x1379714, 0x80
sFlygonSprites24:
ax_sprite sFlygonGfx24, 0x80
ax_sprite_terminator
sFlygonGfx25:
.incbin "baserom.gba", 0x13797A4, 0x40
sFlygonSprites25:
ax_sprite sFlygonGfx25, 0x40
ax_sprite_terminator
sFlygonGfx26:
.incbin "baserom.gba", 0x13797F4, 0x20
sFlygonSprites26:
ax_sprite sFlygonGfx26, 0x20
ax_sprite_terminator
sFlygonGfx27:
.incbin "baserom.gba", 0x1379824, 0x160
sFlygonSprites27:
ax_sprite 0, 0x80
ax_sprite sFlygonGfx27, 0x160
ax_sprite 0, 0x20
ax_sprite_terminator
sFlygonGfx28:
.incbin "baserom.gba", 0x13799A4, 0x160
sFlygonSprites28:
ax_sprite 0, 0x80
ax_sprite sFlygonGfx28, 0x160
ax_sprite 0, 0x20
ax_sprite_terminator
sFlygonGfx29:
.incbin "baserom.gba", 0x1379B24, 0x100
sFlygonSprites29:
ax_sprite sFlygonGfx29, 0x100
ax_sprite_terminator
sFlygonGfx30:
.incbin "baserom.gba", 0x1379C34, 0x60
sFlygonSprites30:
ax_sprite 0, 0x20
ax_sprite sFlygonGfx30, 0x60
ax_sprite_terminator
sFlygonGfx31:
.incbin "baserom.gba", 0x1379CAC, 0x40
sFlygonSprites31:
ax_sprite sFlygonGfx31, 0x40
ax_sprite_terminator
sFlygonGfx32:
.incbin "baserom.gba", 0x1379CFC, 0x20
sFlygonSprites32:
ax_sprite sFlygonGfx32, 0x20
ax_sprite_terminator
sFlygonGfx33:
.incbin "baserom.gba", 0x1379D2C, 0x100
sFlygonSprites33:
ax_sprite sFlygonGfx33, 0x100
ax_sprite_terminator
sFlygonGfx34:
.incbin "baserom.gba", 0x1379E3C, 0x60
sFlygonSprites34:
ax_sprite 0, 0x20
ax_sprite sFlygonGfx34, 0x60
ax_sprite_terminator
sFlygonGfx35:
.incbin "baserom.gba", 0x1379EB4, 0x40
sFlygonSprites35:
ax_sprite sFlygonGfx35, 0x40
ax_sprite_terminator
sFlygonGfx36:
.incbin "baserom.gba", 0x1379F04, 0x20
sFlygonSprites36:
ax_sprite sFlygonGfx36, 0x20
ax_sprite_terminator
sFlygonGfx37:
.incbin "baserom.gba", 0x1379F34, 0x100
sFlygonSprites37:
ax_sprite sFlygonGfx37, 0x100
ax_sprite_terminator
sFlygonGfx38:
.incbin "baserom.gba", 0x137A044, 0x60
sFlygonSprites38:
ax_sprite sFlygonGfx38, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sFlygonGfx39:
.incbin "baserom.gba", 0x137A0BC, 0x40
sFlygonSprites39:
ax_sprite sFlygonGfx39, 0x40
ax_sprite_terminator
sFlygonGfx40:
.incbin "baserom.gba", 0x137A10C, 0x20
sFlygonSprites40:
ax_sprite sFlygonGfx40, 0x20
ax_sprite_terminator
sFlygonGfx41:
.incbin "baserom.gba", 0x137A13C, 0x20
sFlygonSprites41:
ax_sprite sFlygonGfx41, 0x20
ax_sprite_terminator
sFlygonGfx42:
.incbin "baserom.gba", 0x137A16C, 0x100
sFlygonSprites42:
ax_sprite sFlygonGfx42, 0x100
ax_sprite_terminator
sFlygonGfx43:
.incbin "baserom.gba", 0x137A27C, 0x60
sFlygonSprites43:
ax_sprite sFlygonGfx43, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sFlygonGfx44:
.incbin "baserom.gba", 0x137A2F4, 0x40
sFlygonSprites44:
ax_sprite sFlygonGfx44, 0x40
ax_sprite_terminator
sFlygonGfx45:
.incbin "baserom.gba", 0x137A344, 0x20
sFlygonSprites45:
ax_sprite sFlygonGfx45, 0x20
ax_sprite_terminator
sFlygonGfx46:
.incbin "baserom.gba", 0x137A374, 0x20
sFlygonSprites46:
ax_sprite sFlygonGfx46, 0x20
ax_sprite_terminator
sFlygonGfx47:
.incbin "baserom.gba", 0x137A3A4, 0x100
sFlygonSprites47:
ax_sprite sFlygonGfx47, 0x100
ax_sprite_terminator
sFlygonGfx48:
.incbin "baserom.gba", 0x137A4B4, 0x40
sFlygonSprites48:
ax_sprite sFlygonGfx48, 0x40
ax_sprite_terminator
sFlygonGfx49:
.incbin "baserom.gba", 0x137A504, 0x40
sFlygonSprites49:
ax_sprite sFlygonGfx49, 0x40
ax_sprite_terminator
sFlygonGfx50:
.incbin "baserom.gba", 0x137A554, 0x20
sFlygonSprites50:
ax_sprite sFlygonGfx50, 0x20
ax_sprite_terminator
sFlygonGfx51:
.incbin "baserom.gba", 0x137A584, 0x20
sFlygonSprites51:
ax_sprite sFlygonGfx51, 0x20
ax_sprite_terminator
sFlygonGfx52:
.incbin "baserom.gba", 0x137A5B4, 0x20
sFlygonSprites52:
ax_sprite sFlygonGfx52, 0x20
ax_sprite_terminator
sFlygonGfx53:
.incbin "baserom.gba", 0x137A5E4, 0x100
sFlygonSprites53:
ax_sprite sFlygonGfx53, 0x100
ax_sprite_terminator
sFlygonGfx54:
.incbin "baserom.gba", 0x137A6F4, 0x40
sFlygonSprites54:
ax_sprite sFlygonGfx54, 0x40
ax_sprite_terminator
sFlygonGfx55:
.incbin "baserom.gba", 0x137A744, 0x40
sFlygonSprites55:
ax_sprite sFlygonGfx55, 0x40
ax_sprite_terminator
sFlygonGfx56:
.incbin "baserom.gba", 0x137A794, 0x20
sFlygonSprites56:
ax_sprite sFlygonGfx56, 0x20
ax_sprite_terminator
sFlygonGfx57:
.incbin "baserom.gba", 0x137A7C4, 0x20
sFlygonSprites57:
ax_sprite sFlygonGfx57, 0x20
ax_sprite_terminator
sFlygonGfx58:
.incbin "baserom.gba", 0x137A7F4, 0x20
sFlygonSprites58:
ax_sprite sFlygonGfx58, 0x20
ax_sprite_terminator
sFlygonGfx59:
.incbin "baserom.gba", 0x137A824, 0x140
sFlygonGfx59_1:
.incbin "baserom.gba", 0x137A964, 0x60
sFlygonSprites59:
ax_sprite 0, 0x40
ax_sprite sFlygonGfx59, 0x140
ax_sprite 0, 0x20
ax_sprite sFlygonGfx59_1, 0x60
ax_sprite_terminator
sFlygonGfx60:
.incbin "baserom.gba", 0x137A9EC, 0x40
sFlygonGfx60_1:
.incbin "baserom.gba", 0x137AA2C, 0x160
sFlygonSprites60:
ax_sprite 0, 0x40
ax_sprite sFlygonGfx60, 0x40
ax_sprite 0, 0x20
ax_sprite sFlygonGfx60_1, 0x160
ax_sprite_terminator
sFlygonGfx61:
.incbin "baserom.gba", 0x137ABB4, 0x180
sFlygonGfx61_1:
.incbin "baserom.gba", 0x137AD34, 0x60
sFlygonSprites61:
ax_sprite sFlygonGfx61, 0x180
ax_sprite 0, 0x20
ax_sprite sFlygonGfx61_1, 0x60
ax_sprite_terminator
sFlygonGfx62:
.incbin "baserom.gba", 0x137ADB4, 0x1E0
sFlygonSprites62:
ax_sprite 0, 0x20
ax_sprite sFlygonGfx62, 0x1e0
ax_sprite_terminator
sFlygonGfx63:
.incbin "baserom.gba", 0x137AFAC, 0x1C0
sFlygonSprites63:
ax_sprite 0, 0x40
ax_sprite sFlygonGfx63, 0x1c0
ax_sprite_terminator
sFlygonGfx64:
.incbin "baserom.gba", 0x137B184, 0x1E0
sFlygonSprites64:
ax_sprite 0, 0x20
ax_sprite sFlygonGfx64, 0x1e0
ax_sprite_terminator
sFlygonGfx65:
.incbin "baserom.gba", 0x137B37C, 0x160
sFlygonGfx65_1:
.incbin "baserom.gba", 0x137B4DC, 0x60
sFlygonSprites65:
ax_sprite 0, 0x20
ax_sprite sFlygonGfx65, 0x160
ax_sprite 0, 0x20
ax_sprite sFlygonGfx65_1, 0x60
ax_sprite_terminator
sFlygonGfx66:
.incbin "baserom.gba", 0x137B564, 0x200
sFlygonSprites66:
ax_sprite sFlygonGfx66, 0x200
ax_sprite_terminator
sFlygonGfx67:
.incbin "baserom.gba", 0x137B774, 0x40
sFlygonGfx67_1:
.incbin "baserom.gba", 0x137B7B4, 0x100
sFlygonGfx67_2:
.incbin "baserom.gba", 0x137B8B4, 0x40
sFlygonSprites67:
ax_sprite 0, 0x20
ax_sprite sFlygonGfx67, 0x40
ax_sprite 0, 0x20
ax_sprite sFlygonGfx67_1, 0x100
ax_sprite 0, 0x20
ax_sprite sFlygonGfx67_2, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sFlygonGfx68:
.incbin "baserom.gba", 0x137B934, 0x40
sFlygonGfx68_1:
.incbin "baserom.gba", 0x137B974, 0x40
sFlygonGfx68_2:
.incbin "baserom.gba", 0x137B9B4, 0x100
sFlygonSprites68:
ax_sprite 0, 0x20
ax_sprite sFlygonGfx68, 0x40
ax_sprite 0, 0x40
ax_sprite sFlygonGfx68_1, 0x40
ax_sprite 0, 0x20
ax_sprite sFlygonGfx68_2, 0x100
ax_sprite_terminator
sFlygonGfx69:
.incbin "baserom.gba", 0x137BAEC, 0x200
sFlygonSprites69:
ax_sprite sFlygonGfx69, 0x200
ax_sprite_terminator
sFlygonGfx70:
.incbin "baserom.gba", 0x137BCFC, 0x200
sFlygonSprites70:
ax_sprite sFlygonGfx70, 0x200
ax_sprite_terminator
sFlygonGfx71:
.incbin "baserom.gba", 0x137BF0C, 0x200
sFlygonSprites71:
ax_sprite sFlygonGfx71, 0x200
ax_sprite_terminator
sFlygonGfx72:
.incbin "baserom.gba", 0x137C11C, 0x200
sFlygonSprites72:
ax_sprite sFlygonGfx72, 0x200
ax_sprite_terminator
sFlygonGfx73:
.incbin "baserom.gba", 0x137C32C, 0x200
sFlygonSprites73:
ax_sprite sFlygonGfx73, 0x200
ax_sprite_terminator
sFlygonGfx74:
.incbin "baserom.gba", 0x137C53C, 0x200
sFlygonSprites74:
ax_sprite sFlygonGfx74, 0x200
ax_sprite_terminator
sFlygonGfx75:
.incbin "baserom.gba", 0x137C74C, 0x200
sFlygonSprites75:
ax_sprite sFlygonGfx75, 0x200
ax_sprite_terminator
sAxPosesFlygon:
.4byte sFlygonPose1
.4byte sFlygonPose2
.4byte sFlygonPose3
.4byte sFlygonPose4
.4byte sFlygonPose5
.4byte sFlygonPose6
.4byte sFlygonPose7
.4byte sFlygonPose8
.4byte sFlygonPose9
.4byte sFlygonPose10
.4byte sFlygonPose11
.4byte sFlygonPose12
.4byte sFlygonPose13
.4byte sFlygonPose14
.4byte sFlygonPose15
.4byte sFlygonPose16
.4byte sFlygonPose17
.4byte sFlygonPose18
.4byte sFlygonPose19
.4byte sFlygonPose20
.4byte sFlygonPose21
.4byte sFlygonPose22
.4byte sFlygonPose23
.4byte sFlygonPose24
.4byte sFlygonPose25
.4byte sFlygonPose26
.4byte sFlygonPose27
.4byte sFlygonPose28
.4byte sFlygonPose29
.4byte sFlygonPose30
.4byte sFlygonPose31
.4byte sFlygonPose32
.4byte sFlygonPose33
.4byte sFlygonPose34
.4byte sFlygonPose35
.4byte sFlygonPose36
.4byte sFlygonPose37
.4byte sFlygonPose38
.4byte sFlygonPose39
.4byte sFlygonPose40
.4byte sFlygonPose41
.4byte sFlygonPose42
.4byte sFlygonPose43
.4byte sFlygonPose44
.4byte sFlygonPose45
.4byte sFlygonPose46
.4byte sFlygonPose47
.4byte sFlygonPose48
.4byte sFlygonPose49
.4byte sFlygonPose50
.4byte sFlygonPose51
.4byte sFlygonPose52
.4byte sFlygonPose53
.4byte sFlygonPose54
.4byte sFlygonPose55
.4byte sFlygonPose56
.4byte sFlygonPose57
.4byte sFlygonPose58
.4byte sFlygonPose59
.4byte sFlygonPose60
.4byte sFlygonPose61
.4byte sFlygonPose62
.4byte sFlygonPose63
.4byte sFlygonPose64
.4byte sFlygonPose65
.4byte sFlygonPose66
.4byte sFlygonPose67
.4byte sFlygonPose68
.4byte sFlygonPose69
.4byte sFlygonPose70
.4byte sFlygonPose71
.4byte sFlygonPose72
.4byte sFlygonPose73
.4byte sFlygonPose74
.4byte sFlygonPose75
.4byte sFlygonPose76
.4byte sFlygonPose77
.4byte sFlygonPose78
.4byte sFlygonPose79
.4byte sFlygonPose80
.4byte sFlygonPose81
.4byte sFlygonPose82
.4byte sFlygonPose83
.4byte sFlygonPose84
.4byte sFlygonPose85
.4byte sFlygonPose86
.4byte sFlygonPose87
.4byte sFlygonPose88
.4byte sFlygonPose89
.4byte sFlygonPose90
.4byte sFlygonPose91
.4byte sFlygonPose92
.4byte sFlygonPose93
.4byte sFlygonPose94
.4byte sFlygonPose95
.4byte sFlygonPose96
.4byte sFlygonPose97
.4byte sFlygonPose98
.4byte sFlygonPose99
.4byte sFlygonPose100
.4byte sFlygonPose101
.4byte sFlygonPose102
.4byte sFlygonPose103
.4byte sFlygonPose104
.4byte sFlygonPose105
.4byte sFlygonPose106
.4byte sFlygonPose107
.4byte sFlygonPose108
.4byte sFlygonPose109
.4byte sFlygonPose110
.4byte sFlygonPose111
.4byte sFlygonPose112
.4byte sFlygonPose113
.4byte sFlygonPose114
.4byte sFlygonPose115
.4byte sFlygonPose116
.4byte sFlygonPose117
.4byte sFlygonPose118
.4byte sFlygonPose119
.4byte sFlygonPose120
.4byte sFlygonPose121
.4byte sFlygonPose122
.4byte sFlygonPose123
.4byte sFlygonPose124
.4byte sFlygonPose125
.4byte sFlygonPose126
.4byte sFlygonPose127
.4byte sFlygonPose128
.4byte sFlygonPose129
.4byte sFlygonPose130
.4byte sFlygonPose131
.4byte sFlygonPose132
.4byte sFlygonPose133
.4byte sFlygonPose134
.4byte sFlygonPose135
.4byte sFlygonPose136
.4byte sFlygonPose137
.4byte sFlygonPose138
.4byte sFlygonPose139
.4byte sFlygonPose140
.4byte sFlygonPose141
.4byte sFlygonPose142
.4byte sFlygonPose143
.4byte sFlygonPose144
.4byte sFlygonPose145
.4byte sFlygonPose146
.4byte sFlygonPose147
.4byte sFlygonPose148
.4byte sFlygonPose149
.4byte sFlygonPose150
.4byte sFlygonPose151
.4byte sFlygonPose152
.4byte sFlygonPose153
.4byte sFlygonPose154
.4byte sFlygonPose155
.4byte sFlygonPose156
.4byte sFlygonPose157
.4byte sFlygonPose158
.4byte sFlygonPose159
.4byte sFlygonPose160
.4byte sFlygonPose161
.4byte sFlygonPose162
.4byte sFlygonPose163
.4byte sFlygonPose164
.4byte sFlygonPose165
.4byte sFlygonPose166
.4byte sFlygonPose167
.4byte sFlygonPose168
.4byte sFlygonPose169
.4byte sFlygonPose170
.4byte sFlygonPose171
.4byte sFlygonPose172
.4byte sFlygonPose173
.4byte sFlygonPose174
.4byte sFlygonPose175
.4byte sFlygonPose176
.4byte sFlygonPose177
.4byte sFlygonPose178
.4byte sFlygonPose179
.4byte sFlygonPose180
.4byte sFlygonPose181
.4byte sFlygonPose182
.4byte sFlygonPose183
.4byte sFlygonPose184
.4byte sFlygonPose185
.4byte sFlygonPose186
.4byte sFlygonPose187
.4byte sFlygonPose188
.4byte sFlygonPose189
.4byte sFlygonPose190
.4byte sFlygonPose191
.4byte sFlygonPose192
.4byte sFlygonPose193
.4byte sFlygonPose194
.4byte sFlygonPose195
.4byte sFlygonPose196
.4byte sFlygonPose197
.4byte sFlygonPose198
.4byte sFlygonPose199
.4byte sFlygonPose200
.4byte sFlygonPose201
.4byte sFlygonPose202
.4byte sFlygonPose203
.4byte sFlygonPose204
.4byte sFlygonPose205
.4byte sFlygonPose206
.4byte sFlygonPose207
.4byte sFlygonPose208
.4byte sFlygonPose209
.4byte sFlygonPose210
.4byte sFlygonPose211
.4byte sFlygonPose212
.4byte sFlygonPose213
.4byte sFlygonPose214
.4byte sFlygonPose215
.4byte sFlygonPose216
.4byte sFlygonPose217
.4byte sFlygonPose218
.4byte sFlygonPose219
.4byte sFlygonPose220
.4byte sFlygonPose221
.4byte sFlygonPose222
.4byte sFlygonPose223
.4byte sFlygonPose224
.4byte sFlygonPose225
.4byte sFlygonPose226
.4byte sFlygonPose227
.4byte sFlygonPose228
.4byte sFlygonPose229
.4byte sFlygonPose230
.4byte sFlygonPose231
.4byte sFlygonPose232
.4byte sFlygonPose233
.4byte sFlygonPose234
.4byte sFlygonPose235
.4byte sFlygonPose236
.4byte sFlygonPose237
.4byte sFlygonPose238
.4byte sFlygonPose239
.4byte sFlygonPose240
.4byte sFlygonPose241
.4byte sFlygonPose242
.4byte sFlygonPose243
.4byte sFlygonPose244
.4byte sFlygonPose245
.4byte sFlygonPose246
.4byte sFlygonPose247
.4byte sFlygonPose248
.4byte sFlygonPose249
.4byte sFlygonPose250
sAxPositionsFlygon:
.2byte   -1,  -17, 	  -4,  -11, 	   2,  -11, 	  -1,  -13
.2byte   -1,  -15, 	  -4,  -10, 	   2,  -10, 	  -1,  -12
.2byte   -1,  -19, 	  -4,  -12, 	   2,  -12, 	  -1,  -14
.2byte    7,  -19, 	   7,  -13, 	   4,  -11, 	   0,  -13
.2byte    8,  -17, 	   7,  -12, 	   4,  -10, 	   0,  -12
.2byte    6,  -21, 	   7,  -14, 	   4,  -12, 	   1,  -14
.2byte   10,  -20, 	   8,  -14, 	   7,  -12, 	   1,  -14
.2byte   11,  -18, 	   8,  -13, 	   7,  -11, 	   1,  -14
.2byte    9,  -22, 	   8,  -15, 	   7,  -13, 	   1,  -15
.2byte    6,  -22, 	   2,  -18, 	  10,  -15, 	   1,  -15
.2byte    7,  -19, 	   3,  -16, 	   9,  -14, 	   1,  -14
.2byte    5,  -24, 	   1,  -17, 	   6,  -15, 	   1,  -14
.2byte    0,  -24, 	   2,  -16, 	  -2,  -16, 	  -1,  -14
.2byte   -1,  -23, 	   2,  -16, 	  -2,  -16, 	  -1,  -14
.2byte   -1,  -26, 	   2,  -17, 	  -3,  -17, 	  -1,  -16
.2byte   -7,  -22, 	  -3,  -18, 	 -11,  -15, 	  -2,  -15
.2byte   -8,  -19, 	  -4,  -16, 	 -10,  -14, 	  -2,  -14
.2byte   -6,  -24, 	  -2,  -17, 	  -7,  -15, 	  -2,  -14
.2byte  -11,  -20, 	  -9,  -14, 	  -8,  -12, 	  -2,  -14
.2byte  -12,  -18, 	  -9,  -13, 	  -8,  -11, 	  -2,  -14
.2byte  -10,  -22, 	  -9,  -15, 	  -8,  -13, 	  -2,  -15
.2byte   -8,  -19, 	  -8,  -13, 	  -5,  -11, 	  -1,  -13
.2byte   -9,  -17, 	  -8,  -12, 	  -5,  -10, 	  -1,  -12
.2byte   -7,  -21, 	  -8,  -14, 	  -5,  -12, 	  -2,  -14
.2byte   -1,  -17, 	  -4,  -11, 	   2,  -11, 	  -1,  -13
.2byte   -1,  -16, 	  -4,  -11, 	   2,  -11, 	  -1,  -13
.2byte   -1,  -18, 	  -4,  -11, 	   2,  -11, 	  -1,  -13
.2byte   -1,   -3, 	  -6,  -10, 	   3,  -10, 	  -1,  -15
.2byte   -1,   -2, 	  -6,  -10, 	   3,  -10, 	  -1,  -14
.2byte    7,  -19, 	   7,  -13, 	   4,  -11, 	   0,  -13
.2byte    8,  -18, 	   7,  -13, 	   4,  -11, 	   0,  -13
.2byte    6,  -20, 	   7,  -13, 	   4,  -11, 	   1,  -13
.2byte   12,   -6, 	   7,  -10, 	   2,   -6, 	   3,  -13
.2byte   12,   -4, 	   8,   -9, 	   2,   -6, 	   4,  -12
.2byte   10,  -20, 	   8,  -14, 	   7,  -12, 	   1,  -14
.2byte   11,  -19, 	   8,  -14, 	   7,  -12, 	   1,  -15
.2byte    9,  -21, 	   8,  -14, 	   7,  -12, 	   1,  -14
.2byte   13,  -12, 	   4,   -7, 	   1,   -6, 	  -1,  -12
.2byte   13,  -11, 	   4,   -7, 	   1,   -6, 	   0,  -13
.2byte    6,  -22, 	   2,  -18, 	  10,  -15, 	   1,  -15
.2byte    7,  -20, 	   3,  -17, 	   9,  -15, 	   1,  -15
.2byte    5,  -23, 	   1,  -16, 	   6,  -14, 	   1,  -13
.2byte   11,  -24, 	   2,  -20, 	   7,  -17, 	   2,  -17
.2byte   11,  -23, 	   1,  -20, 	   6,  -17, 	   2,  -17
.2byte    0,  -24, 	   2,  -16, 	  -2,  -16, 	  -1,  -14
.2byte   -1,  -24, 	   2,  -17, 	  -2,  -17, 	  -1,  -15
.2byte   -1,  -25, 	   2,  -16, 	  -3,  -16, 	  -1,  -15
.2byte   -1,  -23, 	   3,  -17, 	  -4,  -17, 	  -1,  -14
.2byte   -1,  -23, 	   3,  -17, 	  -4,  -17, 	  -1,  -14
.2byte   -7,  -22, 	  -3,  -18, 	 -11,  -15, 	  -2,  -15
.2byte   -8,  -20, 	  -4,  -17, 	 -10,  -15, 	  -2,  -15
.2byte   -6,  -23, 	  -2,  -16, 	  -7,  -14, 	  -2,  -13
.2byte  -12,  -24, 	  -3,  -20, 	  -8,  -17, 	  -3,  -17
.2byte  -12,  -23, 	  -2,  -20, 	  -7,  -17, 	  -3,  -17
.2byte  -11,  -20, 	  -9,  -14, 	  -8,  -12, 	  -2,  -14
.2byte  -12,  -19, 	  -9,  -14, 	  -8,  -12, 	  -2,  -15
.2byte  -10,  -21, 	  -9,  -14, 	  -8,  -12, 	  -2,  -14
.2byte  -14,  -12, 	  -5,   -7, 	  -2,   -6, 	   0,  -12
.2byte  -14,  -11, 	  -5,   -7, 	  -2,   -6, 	  -1,  -13
.2byte   -8,  -19, 	  -8,  -13, 	  -5,  -11, 	  -1,  -13
.2byte   -9,  -18, 	  -8,  -13, 	  -5,  -11, 	  -1,  -13
.2byte   -7,  -20, 	  -8,  -13, 	  -5,  -11, 	  -2,  -13
.2byte  -13,   -6, 	  -8,  -10, 	  -3,   -6, 	  -4,  -13
.2byte  -13,   -4, 	  -9,   -9, 	  -3,   -6, 	  -5,  -12
.2byte   -1,  -17, 	  -4,  -11, 	   2,  -11, 	  -1,  -13
.2byte   -1,  -16, 	  -4,  -11, 	   2,  -11, 	  -1,  -13
.2byte   -1,  -18, 	  -4,  -11, 	   2,  -11, 	  -1,  -13
.2byte   -1,   -3, 	  -6,  -10, 	   3,  -10, 	  -1,  -15
.2byte   -1,   -2, 	  -6,  -10, 	   3,  -10, 	  -1,  -14
.2byte    7,  -19, 	   7,  -13, 	   4,  -11, 	   0,  -13
.2byte    8,  -18, 	   7,  -13, 	   4,  -11, 	   0,  -13
.2byte    6,  -20, 	   7,  -13, 	   4,  -11, 	   1,  -13
.2byte   12,   -6, 	   7,  -10, 	   2,   -6, 	   3,  -13
.2byte   12,   -4, 	   8,   -9, 	   2,   -6, 	   4,  -12
.2byte   10,  -20, 	   8,  -14, 	   7,  -12, 	   1,  -14
.2byte   11,  -19, 	   8,  -14, 	   7,  -12, 	   1,  -15
.2byte    9,  -21, 	   8,  -14, 	   7,  -12, 	   1,  -14
.2byte   13,  -12, 	   4,   -7, 	   1,   -6, 	  -1,  -12
.2byte   13,  -11, 	   4,   -7, 	   1,   -6, 	   0,  -13
.2byte    6,  -22, 	   2,  -18, 	  10,  -15, 	   1,  -15
.2byte    7,  -20, 	   3,  -17, 	   9,  -15, 	   1,  -15
.2byte    5,  -23, 	   1,  -16, 	   6,  -14, 	   1,  -13
.2byte   11,  -24, 	   2,  -20, 	   7,  -17, 	   2,  -17
.2byte   11,  -23, 	   1,  -20, 	   6,  -17, 	   2,  -17
.2byte    0,  -24, 	   2,  -16, 	  -2,  -16, 	  -1,  -14
.2byte   -1,  -24, 	   2,  -17, 	  -2,  -17, 	  -1,  -15
.2byte   -1,  -25, 	   2,  -16, 	  -3,  -16, 	  -1,  -15
.2byte   -1,  -23, 	   3,  -17, 	  -4,  -17, 	  -1,  -14
.2byte   -1,  -23, 	   3,  -17, 	  -4,  -17, 	  -1,  -14
.2byte   -7,  -22, 	  -3,  -18, 	 -11,  -15, 	  -2,  -15
.2byte   -8,  -20, 	  -4,  -17, 	 -10,  -15, 	  -2,  -15
.2byte   -6,  -23, 	  -2,  -16, 	  -7,  -14, 	  -2,  -13
.2byte  -12,  -24, 	  -3,  -20, 	  -8,  -17, 	  -3,  -17
.2byte  -12,  -23, 	  -2,  -20, 	  -7,  -17, 	  -3,  -17
.2byte  -11,  -20, 	  -9,  -14, 	  -8,  -12, 	  -2,  -14
.2byte  -12,  -19, 	  -9,  -14, 	  -8,  -12, 	  -2,  -15
.2byte  -10,  -21, 	  -9,  -14, 	  -8,  -12, 	  -2,  -14
.2byte  -14,  -12, 	  -5,   -7, 	  -2,   -6, 	   0,  -12
.2byte  -14,  -11, 	  -5,   -7, 	  -2,   -6, 	  -1,  -13
.2byte   -8,  -19, 	  -8,  -13, 	  -5,  -11, 	  -1,  -13
.2byte   -9,  -18, 	  -8,  -13, 	  -5,  -11, 	  -1,  -13
.2byte   -7,  -20, 	  -8,  -13, 	  -5,  -11, 	  -2,  -13
.2byte  -13,   -6, 	  -8,  -10, 	  -3,   -6, 	  -4,  -13
.2byte  -13,   -4, 	  -9,   -9, 	  -3,   -6, 	  -5,  -12
.2byte   -1,  -17, 	  -4,  -11, 	   2,  -11, 	  -1,  -13
.2byte   -1,  -15, 	  -4,  -10, 	   2,  -10, 	  -1,  -12
.2byte   -1,  -19, 	  -4,  -12, 	   2,  -12, 	  -1,  -14
.2byte   -1,  -12, 	  -5,   -9, 	   3,   -9, 	  -1,  -10
.2byte   -1,  -13, 	  -5,   -9, 	   3,   -9, 	  -1,  -10
.2byte    7,  -19, 	   7,  -13, 	   4,  -11, 	   0,  -13
.2byte    8,  -17, 	   7,  -12, 	   4,  -10, 	   0,  -12
.2byte    6,  -21, 	   7,  -14, 	   4,  -12, 	   1,  -14
.2byte   10,  -13, 	   9,  -11, 	   2,   -9, 	   1,  -11
.2byte    9,  -14, 	  10,  -11, 	   2,   -9, 	   2,  -11
.2byte   10,  -20, 	   8,  -14, 	   7,  -12, 	   1,  -14
.2byte   11,  -18, 	   8,  -13, 	   7,  -11, 	   1,  -14
.2byte    9,  -22, 	   8,  -15, 	   7,  -13, 	   1,  -15
.2byte   13,  -14, 	   9,  -12, 	   7,   -9, 	   1,  -13
.2byte   12,  -15, 	   9,  -12, 	   7,   -9, 	   1,  -12
.2byte    6,  -22, 	   2,  -18, 	  10,  -15, 	   1,  -15
.2byte    7,  -19, 	   3,  -16, 	   9,  -14, 	   1,  -14
.2byte    5,  -24, 	   1,  -17, 	   6,  -15, 	   1,  -14
.2byte   10,  -16, 	   6,  -16, 	  11,  -12, 	   2,  -14
.2byte    9,  -16, 	   5,  -16, 	  11,  -12, 	   2,  -13
.2byte    0,  -24, 	   2,  -16, 	  -2,  -16, 	  -1,  -14
.2byte   -1,  -23, 	   2,  -16, 	  -2,  -16, 	  -1,  -14
.2byte   -1,  -26, 	   2,  -17, 	  -3,  -17, 	  -1,  -16
.2byte   -1,  -22, 	   3,  -17, 	  -4,  -17, 	   0,  -13
.2byte   -1,  -21, 	   2,  -14, 	  -4,  -14, 	  -1,  -12
.2byte   -7,  -22, 	  -3,  -18, 	 -11,  -15, 	  -2,  -15
.2byte   -8,  -19, 	  -4,  -16, 	 -10,  -14, 	  -2,  -14
.2byte   -6,  -24, 	  -2,  -17, 	  -7,  -15, 	  -2,  -14
.2byte  -11,  -16, 	  -7,  -16, 	 -12,  -12, 	  -3,  -14
.2byte  -10,  -16, 	  -6,  -16, 	 -12,  -12, 	  -3,  -13
.2byte  -11,  -20, 	  -9,  -14, 	  -8,  -12, 	  -2,  -14
.2byte  -12,  -18, 	  -9,  -13, 	  -8,  -11, 	  -2,  -14
.2byte  -10,  -22, 	  -9,  -15, 	  -8,  -13, 	  -2,  -15
.2byte  -14,  -14, 	 -10,  -12, 	  -8,   -9, 	  -2,  -13
.2byte  -13,  -15, 	 -10,  -12, 	  -8,   -9, 	  -2,  -12
.2byte   -8,  -19, 	  -8,  -13, 	  -5,  -11, 	  -1,  -13
.2byte   -9,  -17, 	  -8,  -12, 	  -5,  -10, 	  -1,  -12
.2byte   -7,  -21, 	  -8,  -14, 	  -5,  -12, 	  -2,  -14
.2byte  -11,  -13, 	 -10,  -11, 	  -3,   -9, 	  -2,  -11
.2byte  -10,  -14, 	 -11,  -11, 	  -3,   -9, 	  -3,  -11
.2byte   -1,  -12, 	  -5,   -9, 	   3,   -9, 	  -1,  -10
.2byte   -1,  -14, 	  -5,  -10, 	   3,  -10, 	  -1,  -11
.2byte   10,  -13, 	   9,  -11, 	   2,   -9, 	   1,  -11
.2byte    9,  -15, 	  10,  -12, 	   2,  -10, 	   2,  -12
.2byte   13,  -14, 	   9,  -12, 	   7,   -9, 	   1,  -13
.2byte   12,  -16, 	   9,  -13, 	   7,  -10, 	   1,  -13
.2byte   10,  -16, 	   6,  -16, 	  11,  -12, 	   2,  -14
.2byte    9,  -17, 	   5,  -17, 	  11,  -13, 	   2,  -14
.2byte   -1,  -22, 	   3,  -17, 	  -4,  -17, 	   0,  -13
.2byte   -1,  -22, 	   2,  -15, 	  -4,  -15, 	  -1,  -13
.2byte  -11,  -16, 	  -7,  -16, 	 -12,  -12, 	  -3,  -14
.2byte  -10,  -17, 	  -6,  -17, 	 -12,  -13, 	  -3,  -14
.2byte  -14,  -14, 	 -10,  -12, 	  -8,   -9, 	  -2,  -13
.2byte  -13,  -16, 	 -10,  -13, 	  -8,  -10, 	  -2,  -13
.2byte  -11,  -13, 	 -10,  -11, 	  -3,   -9, 	  -2,  -11
.2byte  -10,  -15, 	 -11,  -12, 	  -3,  -10, 	  -3,  -12
.2byte   -8,  -19, 	  -8,  -13, 	  -5,  -11, 	  -1,  -13
.2byte   -9,  -19, 	  -8,  -12, 	  -5,  -10, 	  -1,  -14
.2byte   -1,  -22, 	  -5,  -21, 	   3,  -20, 	  -1,  -15
.2byte    3,  -25, 	   7,  -23, 	   1,  -20, 	   2,  -14
.2byte    5,  -24, 	   7,  -22, 	   4,  -19, 	   1,  -15
.2byte    6,  -26, 	   3,  -23, 	   7,  -22, 	   0,  -17
.2byte   -1,  -27, 	   6,  -23, 	  -7,  -23, 	  -1,  -15
.2byte   -7,  -26, 	  -4,  -23, 	  -8,  -22, 	  -1,  -17
.2byte   -6,  -24, 	  -8,  -22, 	  -5,  -19, 	  -2,  -15
.2byte   -4,  -25, 	  -8,  -23, 	  -2,  -20, 	  -3,  -14
.2byte   -1,  -17, 	  -4,  -11, 	   2,  -11, 	  -1,  -13
.2byte   -1,  -15, 	  -4,  -10, 	   2,  -10, 	  -1,  -12
.2byte   -1,  -19, 	  -4,  -12, 	   2,  -12, 	  -1,  -14
.2byte    7,  -19, 	   7,  -13, 	   4,  -11, 	   0,  -13
.2byte    8,  -17, 	   7,  -12, 	   4,  -10, 	   0,  -12
.2byte    6,  -21, 	   7,  -14, 	   4,  -12, 	   1,  -14
.2byte   10,  -20, 	   8,  -14, 	   7,  -12, 	   1,  -14
.2byte   11,  -18, 	   8,  -13, 	   7,  -11, 	   1,  -14
.2byte    9,  -22, 	   8,  -15, 	   7,  -13, 	   1,  -15
.2byte    6,  -22, 	   2,  -18, 	  10,  -15, 	   1,  -15
.2byte    7,  -19, 	   3,  -16, 	   9,  -14, 	   1,  -14
.2byte    5,  -24, 	   1,  -17, 	   6,  -15, 	   1,  -14
.2byte    0,  -24, 	   2,  -16, 	  -2,  -16, 	  -1,  -14
.2byte   -1,  -23, 	   2,  -16, 	  -2,  -16, 	  -1,  -14
.2byte   -1,  -26, 	   2,  -17, 	  -3,  -17, 	  -1,  -16
.2byte   -7,  -22, 	  -3,  -18, 	 -11,  -15, 	  -2,  -15
.2byte   -8,  -19, 	  -4,  -16, 	 -10,  -14, 	  -2,  -14
.2byte   -6,  -24, 	  -2,  -17, 	  -7,  -15, 	  -2,  -14
.2byte  -11,  -20, 	  -9,  -14, 	  -8,  -12, 	  -2,  -14
.2byte  -12,  -18, 	  -9,  -13, 	  -8,  -11, 	  -2,  -14
.2byte  -10,  -22, 	  -9,  -15, 	  -8,  -13, 	  -2,  -15
.2byte   -8,  -19, 	  -8,  -13, 	  -5,  -11, 	  -1,  -13
.2byte   -9,  -17, 	  -8,  -12, 	  -5,  -10, 	  -1,  -12
.2byte   -7,  -21, 	  -8,  -14, 	  -5,  -12, 	  -2,  -14
.2byte   -1,  -12, 	  -5,   -9, 	   3,   -9, 	  -1,  -10
.2byte  -11,  -13, 	 -10,  -11, 	  -3,   -9, 	  -2,  -11
.2byte  -14,  -14, 	 -10,  -12, 	  -8,   -9, 	  -2,  -13
.2byte  -11,  -16, 	  -7,  -16, 	 -12,  -12, 	  -3,  -14
.2byte   -1,  -22, 	   3,  -17, 	  -4,  -17, 	   0,  -13
.2byte   10,  -16, 	   6,  -16, 	  11,  -12, 	   2,  -14
.2byte   13,  -14, 	   9,  -12, 	   7,   -9, 	   1,  -13
.2byte   10,  -13, 	   9,  -11, 	   2,   -9, 	   1,  -11
.2byte   -1,  -12, 	  -5,   -9, 	   3,   -9, 	  -1,  -10
.2byte    8,  -13, 	   7,  -11, 	   0,   -9, 	  -1,  -11
.2byte   12,  -14, 	   8,  -12, 	   6,   -9, 	   0,  -13
.2byte    7,  -16, 	   3,  -16, 	   8,  -12, 	  -1,  -14
.2byte   -1,  -22, 	   3,  -17, 	  -4,  -17, 	   0,  -13
.2byte   -8,  -16, 	  -4,  -16, 	  -9,  -12, 	   0,  -14
.2byte  -13,  -14, 	  -9,  -12, 	  -7,   -9, 	  -1,  -13
.2byte   -9,  -13, 	  -8,  -11, 	  -1,   -9, 	   0,  -11
.2byte   -1,  -17, 	  -4,  -11, 	   2,  -11, 	  -1,  -13
.2byte   -1,  -18, 	  -4,  -11, 	   2,  -11, 	  -1,  -13
.2byte   -1,  -16, 	  -4,  -11, 	   2,  -11, 	  -1,  -13
.2byte    7,  -19, 	   7,  -13, 	   4,  -11, 	   0,  -13
.2byte    6,  -20, 	   7,  -13, 	   4,  -11, 	   1,  -13
.2byte    8,  -18, 	   7,  -13, 	   4,  -11, 	   0,  -13
.2byte   10,  -20, 	   8,  -14, 	   7,  -12, 	   1,  -14
.2byte    9,  -21, 	   8,  -14, 	   7,  -12, 	   1,  -14
.2byte   11,  -19, 	   8,  -14, 	   7,  -12, 	   1,  -15
.2byte    6,  -22, 	   2,  -18, 	  10,  -15, 	   1,  -15
.2byte    5,  -23, 	   1,  -16, 	   6,  -14, 	   1,  -13
.2byte    7,  -20, 	   3,  -17, 	   9,  -15, 	   1,  -15
.2byte    0,  -24, 	   2,  -16, 	  -2,  -16, 	  -1,  -14
.2byte   -1,  -25, 	   2,  -16, 	  -3,  -16, 	  -1,  -15
.2byte   -1,  -24, 	   2,  -17, 	  -2,  -17, 	  -1,  -15
.2byte   -7,  -22, 	  -3,  -18, 	 -11,  -15, 	  -2,  -15
.2byte   -6,  -23, 	  -2,  -16, 	  -7,  -14, 	  -2,  -13
.2byte   -8,  -20, 	  -4,  -17, 	 -10,  -15, 	  -2,  -15
.2byte  -11,  -20, 	  -9,  -14, 	  -8,  -12, 	  -2,  -14
.2byte  -10,  -21, 	  -9,  -14, 	  -8,  -12, 	  -2,  -14
.2byte  -12,  -19, 	  -9,  -14, 	  -8,  -12, 	  -2,  -15
.2byte   -8,  -19, 	  -8,  -13, 	  -5,  -11, 	  -1,  -13
.2byte   -7,  -20, 	  -8,  -13, 	  -5,  -11, 	  -2,  -13
.2byte   -9,  -18, 	  -8,  -13, 	  -5,  -11, 	  -1,  -13
.2byte   -1,  -14, 	  -4,   -9, 	   2,   -9, 	  -1,  -11
.2byte   -9,  -15, 	  -8,  -10, 	  -5,   -8, 	  -1,  -10
.2byte  -12,  -16, 	  -9,  -11, 	  -8,   -9, 	  -2,  -12
.2byte   -8,  -17, 	  -4,  -14, 	 -10,  -12, 	  -2,  -12
.2byte   -1,  -19, 	   2,  -12, 	  -2,  -12, 	  -1,  -10
.2byte    7,  -17, 	   3,  -14, 	   9,  -12, 	   1,  -12
.2byte   11,  -16, 	   8,  -11, 	   7,   -9, 	   1,  -12
.2byte    8,  -15, 	   7,  -10, 	   4,   -8, 	   0,  -10
.2byte   -1,  -17, 	  -4,  -11, 	   2,  -11, 	  -1,  -13
.2byte   -8,  -19, 	  -8,  -13, 	  -5,  -11, 	  -1,  -13
.2byte  -11,  -20, 	  -9,  -14, 	  -8,  -12, 	  -2,  -14
.2byte   -7,  -22, 	  -3,  -18, 	 -11,  -15, 	  -2,  -15
.2byte    0,  -24, 	   2,  -16, 	  -2,  -16, 	  -1,  -14
.2byte    6,  -22, 	   2,  -18, 	  10,  -15, 	   1,  -15
.2byte   10,  -20, 	   8,  -14, 	   7,  -12, 	   1,  -14
.2byte    7,  -19, 	   7,  -13, 	   4,  -11, 	   0,  -13
sFlygonAnimTable1:
.4byte sFlygonAnims_1_1
.4byte sFlygonAnims_1_2
.4byte sFlygonAnims_1_3
.4byte sFlygonAnims_1_4
.4byte sFlygonAnims_1_5
.4byte sFlygonAnims_1_6
.4byte sFlygonAnims_1_7
.4byte sFlygonAnims_1_8
sFlygonAnimTable2:
.4byte sFlygonAnims_2_1
.4byte sFlygonAnims_2_2
.4byte sFlygonAnims_2_3
.4byte sFlygonAnims_2_4
.4byte sFlygonAnims_2_5
.4byte sFlygonAnims_2_6
.4byte sFlygonAnims_2_7
.4byte sFlygonAnims_2_8
sFlygonAnimTable3:
.4byte sFlygonAnims_3_1
.4byte sFlygonAnims_3_2
.4byte sFlygonAnims_3_3
.4byte sFlygonAnims_3_4
.4byte sFlygonAnims_3_5
.4byte sFlygonAnims_3_6
.4byte sFlygonAnims_3_7
.4byte sFlygonAnims_3_8
sFlygonAnimTable4:
.4byte sFlygonAnims_4_1
.4byte sFlygonAnims_4_2
.4byte sFlygonAnims_4_3
.4byte sFlygonAnims_4_4
.4byte sFlygonAnims_4_5
.4byte sFlygonAnims_4_6
.4byte sFlygonAnims_4_7
.4byte sFlygonAnims_4_8
sFlygonAnimTable5:
.4byte sFlygonAnims_5_1
.4byte sFlygonAnims_5_2
.4byte sFlygonAnims_5_3
.4byte sFlygonAnims_5_4
.4byte sFlygonAnims_5_5
.4byte sFlygonAnims_5_6
.4byte sFlygonAnims_5_7
.4byte sFlygonAnims_5_8
sFlygonAnimTable6:
.4byte sFlygonAnims_6_1
.4byte sFlygonAnims_6_1
.4byte sFlygonAnims_6_1
.4byte sFlygonAnims_6_1
.4byte sFlygonAnims_6_1
.4byte sFlygonAnims_6_1
.4byte sFlygonAnims_6_1
.4byte sFlygonAnims_6_1
sFlygonAnimTable7:
.4byte sFlygonAnims_7_1
.4byte sFlygonAnims_7_2
.4byte sFlygonAnims_7_3
.4byte sFlygonAnims_7_4
.4byte sFlygonAnims_7_5
.4byte sFlygonAnims_7_6
.4byte sFlygonAnims_7_7
.4byte sFlygonAnims_7_8
sFlygonAnimTable8:
.4byte sFlygonAnims_8_1
.4byte sFlygonAnims_8_2
.4byte sFlygonAnims_8_3
.4byte sFlygonAnims_8_4
.4byte sFlygonAnims_8_5
.4byte sFlygonAnims_8_6
.4byte sFlygonAnims_8_7
.4byte sFlygonAnims_8_8
sFlygonAnimTable9:
.4byte sFlygonAnims_9_1
.4byte sFlygonAnims_9_2
.4byte sFlygonAnims_9_3
.4byte sFlygonAnims_9_4
.4byte sFlygonAnims_9_5
.4byte sFlygonAnims_9_6
.4byte sFlygonAnims_9_7
.4byte sFlygonAnims_9_8
sFlygonAnimTable10:
.4byte sFlygonAnims_10_1
.4byte sFlygonAnims_10_2
.4byte sFlygonAnims_10_3
.4byte sFlygonAnims_10_4
.4byte sFlygonAnims_10_5
.4byte sFlygonAnims_10_6
.4byte sFlygonAnims_10_7
.4byte sFlygonAnims_10_8
sFlygonAnimTable11:
.4byte sFlygonAnims_11_1
.4byte sFlygonAnims_11_2
.4byte sFlygonAnims_11_3
.4byte sFlygonAnims_11_4
.4byte sFlygonAnims_11_5
.4byte sFlygonAnims_11_6
.4byte sFlygonAnims_11_7
.4byte sFlygonAnims_11_8
sFlygonAnimTable12:
.4byte sFlygonAnims_12_1
.4byte sFlygonAnims_12_2
.4byte sFlygonAnims_12_3
.4byte sFlygonAnims_12_4
.4byte sFlygonAnims_12_5
.4byte sFlygonAnims_12_6
.4byte sFlygonAnims_12_7
.4byte sFlygonAnims_12_8
sFlygonAnimTable13:
.4byte sFlygonAnims_13_1
.4byte sFlygonAnims_13_2
.4byte sFlygonAnims_13_3
.4byte sFlygonAnims_13_4
.4byte sFlygonAnims_13_5
.4byte sFlygonAnims_13_6
.4byte sFlygonAnims_13_7
.4byte sFlygonAnims_13_8
sAxAnimationsFlygon:
.4byte sFlygonAnimTable1
.4byte sFlygonAnimTable2
.4byte sFlygonAnimTable3
.4byte sFlygonAnimTable4
.4byte sFlygonAnimTable5
.4byte sFlygonAnimTable6
.4byte sFlygonAnimTable7
.4byte sFlygonAnimTable8
.4byte sFlygonAnimTable9
.4byte sFlygonAnimTable10
.4byte sFlygonAnimTable11
.4byte sFlygonAnimTable12
.4byte sFlygonAnimTable13
sAxSpritesFlygon:
.4byte sFlygonSprites1
.4byte sFlygonSprites2
.4byte sFlygonSprites3
.4byte sFlygonSprites4
.4byte sFlygonSprites5
.4byte sFlygonSprites6
.4byte sFlygonSprites7
.4byte sFlygonSprites8
.4byte sFlygonSprites9
.4byte sFlygonSprites10
.4byte sFlygonSprites11
.4byte sFlygonSprites12
.4byte sFlygonSprites13
.4byte sFlygonSprites14
.4byte sFlygonSprites15
.4byte sFlygonSprites16
.4byte sFlygonSprites17
.4byte sFlygonSprites18
.4byte sFlygonSprites19
.4byte sFlygonSprites20
.4byte sFlygonSprites21
.4byte sFlygonSprites22
.4byte sFlygonSprites23
.4byte sFlygonSprites24
.4byte sFlygonSprites25
.4byte sFlygonSprites26
.4byte sFlygonSprites27
.4byte sFlygonSprites28
.4byte sFlygonSprites29
.4byte sFlygonSprites30
.4byte sFlygonSprites31
.4byte sFlygonSprites32
.4byte sFlygonSprites33
.4byte sFlygonSprites34
.4byte sFlygonSprites35
.4byte sFlygonSprites36
.4byte sFlygonSprites37
.4byte sFlygonSprites38
.4byte sFlygonSprites39
.4byte sFlygonSprites40
.4byte sFlygonSprites41
.4byte sFlygonSprites42
.4byte sFlygonSprites43
.4byte sFlygonSprites44
.4byte sFlygonSprites45
.4byte sFlygonSprites46
.4byte sFlygonSprites47
.4byte sFlygonSprites48
.4byte sFlygonSprites49
.4byte sFlygonSprites50
.4byte sFlygonSprites51
.4byte sFlygonSprites52
.4byte sFlygonSprites53
.4byte sFlygonSprites54
.4byte sFlygonSprites55
.4byte sFlygonSprites56
.4byte sFlygonSprites57
.4byte sFlygonSprites58
.4byte sFlygonSprites59
.4byte sFlygonSprites60
.4byte sFlygonSprites61
.4byte sFlygonSprites62
.4byte sFlygonSprites63
.4byte sFlygonSprites64
.4byte sFlygonSprites65
.4byte sFlygonSprites66
.4byte sFlygonSprites67
.4byte sFlygonSprites68
.4byte sFlygonSprites69
.4byte sFlygonSprites70
.4byte sFlygonSprites71
.4byte sFlygonSprites72
.4byte sFlygonSprites73
.4byte sFlygonSprites74
.4byte sFlygonSprites75
sAxMainFlygon:
ax_main sAxPosesFlygon, sAxAnimationsFlygon, 13, sAxSpritesFlygon, sAxPositionsFlygon
