.global gAxGrowlithe
gAxGrowlithe:
ax_siro sAxMainGrowlithe
sGrowlithePose1:
ax_pose 0, 0x81e6, 0x80f8, 0x0c00
ax_pose_terminator
sGrowlithePose2:
ax_pose 1, 0x81e6, 0x80f8, 0x0c00
ax_pose_terminator
sGrowlithePose3:
ax_pose 2, 0x81e6, 0x80f8, 0x0c00
ax_pose_terminator
sGrowlithePose4:
ax_pose 3, 0x01e6, 0x90ed, 0x0c00
ax_pose_terminator
sGrowlithePose5:
ax_pose 4, 0x01e6, 0x90ed, 0x0c00
ax_pose_terminator
sGrowlithePose6:
ax_pose 5, 0x01e6, 0x90ed, 0x0c00
ax_pose_terminator
sGrowlithePose7:
ax_pose 6, 0x01ec, 0x90f0, 0x0c00
ax_pose_terminator
sGrowlithePose8:
ax_pose 7, 0x01ec, 0x90f0, 0x0c00
ax_pose_terminator
sGrowlithePose9:
ax_pose 8, 0x01ec, 0x90f0, 0x0c00
ax_pose_terminator
sGrowlithePose10:
ax_pose 9, 0x01e6, 0x90eb, 0x0c00
ax_pose_terminator
sGrowlithePose11:
ax_pose 10, 0x01e6, 0x90eb, 0x0c00
ax_pose_terminator
sGrowlithePose12:
ax_pose 11, 0x01e6, 0x90eb, 0x0c00
ax_pose_terminator
sGrowlithePose13:
ax_pose 12, 0x81e6, 0x80f8, 0x0c00
ax_pose_terminator
sGrowlithePose14:
ax_pose 13, 0x81e6, 0x80f8, 0x0c00
ax_pose_terminator
sGrowlithePose15:
ax_pose 14, 0x81e6, 0x80f8, 0x0c00
ax_pose_terminator
sGrowlithePose16:
ax_pose 9, 0x01e6, 0x80f5, 0x0c00
ax_pose_terminator
sGrowlithePose17:
ax_pose 10, 0x01e6, 0x80f5, 0x0c00
ax_pose_terminator
sGrowlithePose18:
ax_pose 11, 0x01e6, 0x80f5, 0x0c00
ax_pose_terminator
sGrowlithePose19:
ax_pose 6, 0x01ec, 0x80f0, 0x0c00
ax_pose_terminator
sGrowlithePose20:
ax_pose 7, 0x01ec, 0x80f0, 0x0c00
ax_pose_terminator
sGrowlithePose21:
ax_pose 8, 0x01ec, 0x80f0, 0x0c00
ax_pose_terminator
sGrowlithePose22:
ax_pose 3, 0x01e6, 0x80f3, 0x0c00
ax_pose_terminator
sGrowlithePose23:
ax_pose 4, 0x01e6, 0x80f3, 0x0c00
ax_pose_terminator
sGrowlithePose24:
ax_pose 5, 0x01e6, 0x80f3, 0x0c00
ax_pose_terminator
sGrowlithePose25:
ax_pose 0, 0x81e6, 0x80f8, 0x0c00
ax_pose_terminator
sGrowlithePose26:
ax_pose 1, 0x81e6, 0x80f8, 0x0c00
ax_pose_terminator
sGrowlithePose27:
ax_pose 2, 0x81e6, 0x80f8, 0x0c00
ax_pose_terminator
sGrowlithePose28:
ax_pose 15, 0x01e6, 0x80f7, 0x0c00
ax_pose_terminator
sGrowlithePose29:
ax_pose 16, 0x01e6, 0x80f7, 0x0c00
ax_pose_terminator
sGrowlithePose30:
ax_pose 3, 0x01e6, 0x90ed, 0x0c00
ax_pose_terminator
sGrowlithePose31:
ax_pose 4, 0x01e6, 0x90ed, 0x0c00
ax_pose_terminator
sGrowlithePose32:
ax_pose 5, 0x01e6, 0x90ed, 0x0c00
ax_pose_terminator
sGrowlithePose33:
ax_pose 17, 0x01e6, 0x90ef, 0x0c00
ax_pose_terminator
sGrowlithePose34:
ax_pose 18, 0x01e6, 0x90ef, 0x0c00
ax_pose_terminator
sGrowlithePose35:
ax_pose 6, 0x01ec, 0x90f0, 0x0c00
ax_pose_terminator
sGrowlithePose36:
ax_pose 7, 0x01ec, 0x90f0, 0x0c00
ax_pose_terminator
sGrowlithePose37:
ax_pose 8, 0x01ec, 0x90f0, 0x0c00
ax_pose_terminator
sGrowlithePose38:
ax_pose 19, 0x01e8, 0x90f0, 0x0c00
ax_pose_terminator
sGrowlithePose39:
ax_pose 20, 0x01e8, 0x90f0, 0x0c00
ax_pose_terminator
sGrowlithePose40:
ax_pose 9, 0x01e6, 0x90eb, 0x0c00
ax_pose_terminator
sGrowlithePose41:
ax_pose 10, 0x01e6, 0x90eb, 0x0c00
ax_pose_terminator
sGrowlithePose42:
ax_pose 11, 0x01e6, 0x90eb, 0x0c00
ax_pose_terminator
sGrowlithePose43:
ax_pose 21, 0x01e6, 0x90ed, 0x0c00
ax_pose_terminator
sGrowlithePose44:
ax_pose 22, 0x01e6, 0x90ed, 0x0c00
ax_pose_terminator
sGrowlithePose45:
ax_pose 12, 0x81e6, 0x80f8, 0x0c00
ax_pose_terminator
sGrowlithePose46:
ax_pose 13, 0x81e6, 0x80f8, 0x0c00
ax_pose_terminator
sGrowlithePose47:
ax_pose 14, 0x81e6, 0x80f8, 0x0c00
ax_pose_terminator
sGrowlithePose48:
ax_pose 23, 0x81e6, 0x80f8, 0x0c00
ax_pose_terminator
sGrowlithePose49:
ax_pose 24, 0x01e6, 0x80f7, 0x0c00
ax_pose_terminator
sGrowlithePose50:
ax_pose 9, 0x01e6, 0x80f5, 0x0c00
ax_pose_terminator
sGrowlithePose51:
ax_pose 10, 0x01e6, 0x80f5, 0x0c00
ax_pose_terminator
sGrowlithePose52:
ax_pose 11, 0x01e6, 0x80f5, 0x0c00
ax_pose_terminator
sGrowlithePose53:
ax_pose 21, 0x01e6, 0x80f3, 0x0c00
ax_pose_terminator
sGrowlithePose54:
ax_pose 22, 0x01e6, 0x80f3, 0x0c00
ax_pose_terminator
sGrowlithePose55:
ax_pose 6, 0x01ec, 0x80f0, 0x0c00
ax_pose_terminator
sGrowlithePose56:
ax_pose 7, 0x01ec, 0x80f0, 0x0c00
ax_pose_terminator
sGrowlithePose57:
ax_pose 8, 0x01ec, 0x80f0, 0x0c00
ax_pose_terminator
sGrowlithePose58:
ax_pose 19, 0x01e8, 0x80f0, 0x0c00
ax_pose_terminator
sGrowlithePose59:
ax_pose 20, 0x01e8, 0x80f0, 0x0c00
ax_pose_terminator
sGrowlithePose60:
ax_pose 3, 0x01e6, 0x80f3, 0x0c00
ax_pose_terminator
sGrowlithePose61:
ax_pose 4, 0x01e6, 0x80f3, 0x0c00
ax_pose_terminator
sGrowlithePose62:
ax_pose 5, 0x01e6, 0x80f3, 0x0c00
ax_pose_terminator
sGrowlithePose63:
ax_pose 17, 0x01e6, 0x80f1, 0x0c00
ax_pose_terminator
sGrowlithePose64:
ax_pose 18, 0x01e6, 0x80f1, 0x0c00
ax_pose_terminator
sGrowlithePose65:
ax_pose 0, 0x81e6, 0x80f8, 0x0c00
ax_pose_terminator
sGrowlithePose66:
ax_pose 1, 0x81e6, 0x80f8, 0x0c00
ax_pose_terminator
sGrowlithePose67:
ax_pose 2, 0x81e6, 0x80f8, 0x0c00
ax_pose_terminator
sGrowlithePose68:
ax_pose 15, 0x01e6, 0x80f7, 0x0c00
ax_pose_terminator
sGrowlithePose69:
ax_pose 16, 0x01e6, 0x80f7, 0x0c00
ax_pose_terminator
sGrowlithePose70:
ax_pose 3, 0x01e6, 0x90ed, 0x0c00
ax_pose_terminator
sGrowlithePose71:
ax_pose 4, 0x01e6, 0x90ed, 0x0c00
ax_pose_terminator
sGrowlithePose72:
ax_pose 5, 0x01e6, 0x90ed, 0x0c00
ax_pose_terminator
sGrowlithePose73:
ax_pose 17, 0x01e6, 0x90ef, 0x0c00
ax_pose_terminator
sGrowlithePose74:
ax_pose 18, 0x01e6, 0x90ef, 0x0c00
ax_pose_terminator
sGrowlithePose75:
ax_pose 6, 0x01ec, 0x90f0, 0x0c00
ax_pose_terminator
sGrowlithePose76:
ax_pose 7, 0x01ec, 0x90f0, 0x0c00
ax_pose_terminator
sGrowlithePose77:
ax_pose 8, 0x01ec, 0x90f0, 0x0c00
ax_pose_terminator
sGrowlithePose78:
ax_pose 19, 0x01e8, 0x90f0, 0x0c00
ax_pose_terminator
sGrowlithePose79:
ax_pose 20, 0x01e8, 0x90f0, 0x0c00
ax_pose_terminator
sGrowlithePose80:
ax_pose 9, 0x01e6, 0x90eb, 0x0c00
ax_pose_terminator
sGrowlithePose81:
ax_pose 10, 0x01e6, 0x90eb, 0x0c00
ax_pose_terminator
sGrowlithePose82:
ax_pose 11, 0x01e6, 0x90eb, 0x0c00
ax_pose_terminator
sGrowlithePose83:
ax_pose 21, 0x01e6, 0x90ed, 0x0c00
ax_pose_terminator
sGrowlithePose84:
ax_pose 22, 0x01e6, 0x90ed, 0x0c00
ax_pose_terminator
sGrowlithePose85:
ax_pose 12, 0x81e6, 0x80f8, 0x0c00
ax_pose_terminator
sGrowlithePose86:
ax_pose 13, 0x81e6, 0x80f8, 0x0c00
ax_pose_terminator
sGrowlithePose87:
ax_pose 14, 0x81e6, 0x80f8, 0x0c00
ax_pose_terminator
sGrowlithePose88:
ax_pose 23, 0x81e6, 0x80f8, 0x0c00
ax_pose_terminator
sGrowlithePose89:
ax_pose 24, 0x01e6, 0x80f7, 0x0c00
ax_pose_terminator
sGrowlithePose90:
ax_pose 9, 0x01e6, 0x80f5, 0x0c00
ax_pose_terminator
sGrowlithePose91:
ax_pose 10, 0x01e6, 0x80f5, 0x0c00
ax_pose_terminator
sGrowlithePose92:
ax_pose 11, 0x01e6, 0x80f5, 0x0c00
ax_pose_terminator
sGrowlithePose93:
ax_pose 21, 0x01e6, 0x80f3, 0x0c00
ax_pose_terminator
sGrowlithePose94:
ax_pose 22, 0x01e6, 0x80f3, 0x0c00
ax_pose_terminator
sGrowlithePose95:
ax_pose 6, 0x01ec, 0x80f0, 0x0c00
ax_pose_terminator
sGrowlithePose96:
ax_pose 7, 0x01ec, 0x80f0, 0x0c00
ax_pose_terminator
sGrowlithePose97:
ax_pose 8, 0x01ec, 0x80f0, 0x0c00
ax_pose_terminator
sGrowlithePose98:
ax_pose 19, 0x01e8, 0x80f0, 0x0c00
ax_pose_terminator
sGrowlithePose99:
ax_pose 20, 0x01e8, 0x80f0, 0x0c00
ax_pose_terminator
sGrowlithePose100:
ax_pose 3, 0x01e6, 0x80f3, 0x0c00
ax_pose_terminator
sGrowlithePose101:
ax_pose 4, 0x01e6, 0x80f3, 0x0c00
ax_pose_terminator
sGrowlithePose102:
ax_pose 5, 0x01e6, 0x80f3, 0x0c00
ax_pose_terminator
sGrowlithePose103:
ax_pose 17, 0x01e6, 0x80f1, 0x0c00
ax_pose_terminator
sGrowlithePose104:
ax_pose 18, 0x01e6, 0x80f1, 0x0c00
ax_pose_terminator
sGrowlithePose105:
ax_pose 0, 0x81e6, 0x80f8, 0x0c00
ax_pose_terminator
sGrowlithePose106:
ax_pose 1, 0x81e6, 0x80f8, 0x0c00
ax_pose_terminator
sGrowlithePose107:
ax_pose 2, 0x81e6, 0x80f8, 0x0c00
ax_pose_terminator
sGrowlithePose108:
ax_pose 25, 0x01e6, 0x80f7, 0x0c00
ax_pose_terminator
sGrowlithePose109:
ax_pose 3, 0x01e6, 0x90ed, 0x0c00
ax_pose_terminator
sGrowlithePose110:
ax_pose 4, 0x01e6, 0x90ed, 0x0c00
ax_pose_terminator
sGrowlithePose111:
ax_pose 5, 0x01e6, 0x90ed, 0x0c00
ax_pose_terminator
sGrowlithePose112:
ax_pose 26, 0x01e6, 0x90ee, 0x0c00
ax_pose_terminator
sGrowlithePose113:
ax_pose 6, 0x01ec, 0x90f0, 0x0c00
ax_pose_terminator
sGrowlithePose114:
ax_pose 7, 0x01ec, 0x90f0, 0x0c00
ax_pose_terminator
sGrowlithePose115:
ax_pose 8, 0x01ec, 0x90f0, 0x0c00
ax_pose_terminator
sGrowlithePose116:
ax_pose 27, 0x01ec, 0x90f0, 0x0c00
ax_pose_terminator
sGrowlithePose117:
ax_pose 9, 0x01e6, 0x90eb, 0x0c00
ax_pose_terminator
sGrowlithePose118:
ax_pose 10, 0x01e6, 0x90eb, 0x0c00
ax_pose_terminator
sGrowlithePose119:
ax_pose 11, 0x01e6, 0x90eb, 0x0c00
ax_pose_terminator
sGrowlithePose120:
ax_pose 28, 0x01e6, 0x90ed, 0x0c00
ax_pose_terminator
sGrowlithePose121:
ax_pose 12, 0x81e6, 0x80f8, 0x0c00
ax_pose_terminator
sGrowlithePose122:
ax_pose 13, 0x81e6, 0x80f8, 0x0c00
ax_pose_terminator
sGrowlithePose123:
ax_pose 14, 0x81e6, 0x80f8, 0x0c00
ax_pose_terminator
sGrowlithePose124:
ax_pose 29, 0x81e6, 0x80f8, 0x0c00
ax_pose_terminator
sGrowlithePose125:
ax_pose 9, 0x01e6, 0x80f5, 0x0c00
ax_pose_terminator
sGrowlithePose126:
ax_pose 10, 0x01e6, 0x80f5, 0x0c00
ax_pose_terminator
sGrowlithePose127:
ax_pose 11, 0x01e6, 0x80f5, 0x0c00
ax_pose_terminator
sGrowlithePose128:
ax_pose 28, 0x01e6, 0x80f3, 0x0c00
ax_pose_terminator
sGrowlithePose129:
ax_pose 6, 0x01ec, 0x80f0, 0x0c00
ax_pose_terminator
sGrowlithePose130:
ax_pose 7, 0x01ec, 0x80f0, 0x0c00
ax_pose_terminator
sGrowlithePose131:
ax_pose 8, 0x01ec, 0x80f0, 0x0c00
ax_pose_terminator
sGrowlithePose132:
ax_pose 27, 0x01ec, 0x80f0, 0x0c00
ax_pose_terminator
sGrowlithePose133:
ax_pose 3, 0x01e6, 0x80f3, 0x0c00
ax_pose_terminator
sGrowlithePose134:
ax_pose 4, 0x01e6, 0x80f3, 0x0c00
ax_pose_terminator
sGrowlithePose135:
ax_pose 5, 0x01e6, 0x80f3, 0x0c00
ax_pose_terminator
sGrowlithePose136:
ax_pose 26, 0x01e6, 0x80f2, 0x0c00
ax_pose_terminator
sGrowlithePose137:
ax_pose 0, 0x81e6, 0x80f8, 0x0c00
ax_pose_terminator
sGrowlithePose138:
ax_pose 15, 0x01e6, 0x80f7, 0x0c00
ax_pose_terminator
sGrowlithePose139:
ax_pose 30, 0x81e6, 0x80f8, 0x0c00
ax_pose_terminator
sGrowlithePose140:
ax_pose 3, 0x01e6, 0x90ed, 0x0c00
ax_pose_terminator
sGrowlithePose141:
ax_pose 17, 0x01e6, 0x90ee, 0x0c00
ax_pose_terminator
sGrowlithePose142:
ax_pose 31, 0x01e6, 0x90ed, 0x0c00
ax_pose_terminator
sGrowlithePose143:
ax_pose 6, 0x01ec, 0x90f0, 0x0c00
ax_pose_terminator
sGrowlithePose144:
ax_pose 19, 0x01e8, 0x90f0, 0x0c00
ax_pose_terminator
sGrowlithePose145:
ax_pose 32, 0x01ea, 0x90f1, 0x0c00
ax_pose_terminator
sGrowlithePose146:
ax_pose 9, 0x01e6, 0x90eb, 0x0c00
ax_pose_terminator
sGrowlithePose147:
ax_pose 21, 0x01e6, 0x90ed, 0x0c00
ax_pose_terminator
sGrowlithePose148:
ax_pose 33, 0x01e6, 0x90eb, 0x0c00
ax_pose_terminator
sGrowlithePose149:
ax_pose 12, 0x81e6, 0x80f8, 0x0c00
ax_pose_terminator
sGrowlithePose150:
ax_pose 23, 0x81e6, 0x80f8, 0x0c00
ax_pose_terminator
sGrowlithePose151:
ax_pose 34, 0x81e6, 0x80f8, 0x0c00
ax_pose_terminator
sGrowlithePose152:
ax_pose 9, 0x01e6, 0x80f5, 0x0c00
ax_pose_terminator
sGrowlithePose153:
ax_pose 21, 0x01e6, 0x80f3, 0x0c00
ax_pose_terminator
sGrowlithePose154:
ax_pose 33, 0x01e6, 0x80f5, 0x0c00
ax_pose_terminator
sGrowlithePose155:
ax_pose 6, 0x01ec, 0x80f0, 0x0c00
ax_pose_terminator
sGrowlithePose156:
ax_pose 19, 0x01e8, 0x80f0, 0x0c00
ax_pose_terminator
sGrowlithePose157:
ax_pose 32, 0x01ea, 0x80f1, 0x0c00
ax_pose_terminator
sGrowlithePose158:
ax_pose 3, 0x01e6, 0x80f3, 0x0c00
ax_pose_terminator
sGrowlithePose159:
ax_pose 17, 0x01e6, 0x80f2, 0x0c00
ax_pose_terminator
sGrowlithePose160:
ax_pose 31, 0x01e6, 0x80f3, 0x0c00
ax_pose_terminator
sGrowlithePose161:
ax_pose 35, 0x01ee, 0x80f0, 0x0c00
ax_pose_terminator
sGrowlithePose162:
ax_pose 36, 0x01ee, 0x80f0, 0x0c00
ax_pose_terminator
sGrowlithePose163:
ax_pose 37, 0x01e9, 0x80f0, 0x0c00
ax_pose_terminator
sGrowlithePose164:
ax_pose 38, 0x01e6, 0x90f0, 0x0c00
ax_pose_terminator
sGrowlithePose165:
ax_pose 39, 0x01e6, 0x90ee, 0x0c00
ax_pose_terminator
sGrowlithePose166:
ax_pose 40, 0x01e8, 0x90ed, 0x0c00
ax_pose_terminator
sGrowlithePose167:
ax_pose 41, 0x01ea, 0x80f0, 0x0c00
ax_pose_terminator
sGrowlithePose168:
ax_pose 40, 0x01e8, 0x80f3, 0x0c00
ax_pose_terminator
sGrowlithePose169:
ax_pose 39, 0x01e6, 0x80f2, 0x0c00
ax_pose_terminator
sGrowlithePose170:
ax_pose 38, 0x01e6, 0x80f0, 0x0c00
ax_pose_terminator
sGrowlithePose171:
ax_pose 30, 0x81e6, 0x80f8, 0x0c00
ax_pose_terminator
sGrowlithePose172:
ax_pose 31, 0x01e6, 0x90ed, 0x0c00
ax_pose_terminator
sGrowlithePose173:
ax_pose 32, 0x01ea, 0x90f1, 0x0c00
ax_pose_terminator
sGrowlithePose174:
ax_pose 33, 0x01e6, 0x90eb, 0x0c00
ax_pose_terminator
sGrowlithePose175:
ax_pose 34, 0x81e6, 0x80f8, 0x0c00
ax_pose_terminator
sGrowlithePose176:
ax_pose 33, 0x01e6, 0x80f5, 0x0c00
ax_pose_terminator
sGrowlithePose177:
ax_pose 32, 0x01ea, 0x80f1, 0x0c00
ax_pose_terminator
sGrowlithePose178:
ax_pose 31, 0x01e6, 0x80f3, 0x0c00
ax_pose_terminator
sGrowlithePose179:
ax_pose 16, 0x01e6, 0x80f7, 0x0c00
ax_pose_terminator
sGrowlithePose180:
ax_pose 18, 0x01e6, 0x80f1, 0x0c00
ax_pose_terminator
sGrowlithePose181:
ax_pose 20, 0x01e8, 0x80f0, 0x0c00
ax_pose_terminator
sGrowlithePose182:
ax_pose 22, 0x01e6, 0x80f4, 0x0c00
ax_pose_terminator
sGrowlithePose183:
ax_pose 24, 0x01e7, 0x80f7, 0x0c00
ax_pose_terminator
sGrowlithePose184:
ax_pose 22, 0x01e6, 0x90ec, 0x0c00
ax_pose_terminator
sGrowlithePose185:
ax_pose 20, 0x01e8, 0x90f0, 0x0c00
ax_pose_terminator
sGrowlithePose186:
ax_pose 18, 0x01e6, 0x90ef, 0x0c00
ax_pose_terminator
sGrowlithePose187:
ax_pose 25, 0x01e6, 0x80f7, 0x0c00
ax_pose_terminator
sGrowlithePose188:
ax_pose 26, 0x01e6, 0x90ee, 0x0c00
ax_pose_terminator
sGrowlithePose189:
ax_pose 27, 0x01ec, 0x90f0, 0x0c00
ax_pose_terminator
sGrowlithePose190:
ax_pose 28, 0x01e6, 0x90ed, 0x0c00
ax_pose_terminator
sGrowlithePose191:
ax_pose 29, 0x81e6, 0x80f8, 0x0c00
ax_pose_terminator
sGrowlithePose192:
ax_pose 28, 0x01e6, 0x80f3, 0x0c00
ax_pose_terminator
sGrowlithePose193:
ax_pose 27, 0x01ec, 0x80f0, 0x0c00
ax_pose_terminator
sGrowlithePose194:
ax_pose 26, 0x01e6, 0x80f2, 0x0c00
ax_pose_terminator
sGrowlithePose195:
ax_pose 0, 0x81e6, 0x80f8, 0x0c00
ax_pose_terminator
sGrowlithePose196:
ax_pose 15, 0x01e6, 0x80f7, 0x0c00
ax_pose_terminator
sGrowlithePose197:
ax_pose 16, 0x01e6, 0x80f7, 0x0c00
ax_pose_terminator
sGrowlithePose198:
ax_pose 3, 0x01e6, 0x90ed, 0x0c00
ax_pose_terminator
sGrowlithePose199:
ax_pose 17, 0x01e6, 0x90ef, 0x0c00
ax_pose_terminator
sGrowlithePose200:
ax_pose 18, 0x01e6, 0x90ef, 0x0c00
ax_pose_terminator
sGrowlithePose201:
ax_pose 6, 0x01ec, 0x90f0, 0x0c00
ax_pose_terminator
sGrowlithePose202:
ax_pose 19, 0x01e8, 0x90f0, 0x0c00
ax_pose_terminator
sGrowlithePose203:
ax_pose 20, 0x01e8, 0x90f0, 0x0c00
ax_pose_terminator
sGrowlithePose204:
ax_pose 9, 0x01e6, 0x90eb, 0x0c00
ax_pose_terminator
sGrowlithePose205:
ax_pose 21, 0x01e6, 0x90ed, 0x0c00
ax_pose_terminator
sGrowlithePose206:
ax_pose 22, 0x01e6, 0x90ed, 0x0c00
ax_pose_terminator
sGrowlithePose207:
ax_pose 12, 0x81e6, 0x80f8, 0x0c00
ax_pose_terminator
sGrowlithePose208:
ax_pose 23, 0x81e6, 0x80f8, 0x0c00
ax_pose_terminator
sGrowlithePose209:
ax_pose 24, 0x01e6, 0x80f7, 0x0c00
ax_pose_terminator
sGrowlithePose210:
ax_pose 9, 0x01e6, 0x80f5, 0x0c00
ax_pose_terminator
sGrowlithePose211:
ax_pose 21, 0x01e6, 0x80f3, 0x0c00
ax_pose_terminator
sGrowlithePose212:
ax_pose 22, 0x01e6, 0x80f3, 0x0c00
ax_pose_terminator
sGrowlithePose213:
ax_pose 6, 0x01ec, 0x80f0, 0x0c00
ax_pose_terminator
sGrowlithePose214:
ax_pose 19, 0x01e8, 0x80f0, 0x0c00
ax_pose_terminator
sGrowlithePose215:
ax_pose 20, 0x01e8, 0x80f0, 0x0c00
ax_pose_terminator
sGrowlithePose216:
ax_pose 3, 0x01e6, 0x80f3, 0x0c00
ax_pose_terminator
sGrowlithePose217:
ax_pose 17, 0x01e6, 0x80f1, 0x0c00
ax_pose_terminator
sGrowlithePose218:
ax_pose 18, 0x01e6, 0x80f1, 0x0c00
ax_pose_terminator
sGrowlithePose219:
ax_pose 30, 0x81e6, 0x80f8, 0x0c00
ax_pose_terminator
sGrowlithePose220:
ax_pose 31, 0x01e6, 0x80f3, 0x0c00
ax_pose_terminator
sGrowlithePose221:
ax_pose 32, 0x01ea, 0x80ef, 0x0c00
ax_pose_terminator
sGrowlithePose222:
ax_pose 33, 0x01e6, 0x80f4, 0x0c00
ax_pose_terminator
sGrowlithePose223:
ax_pose 34, 0x81e7, 0x80f8, 0x0c00
ax_pose_terminator
sGrowlithePose224:
ax_pose 33, 0x01e6, 0x90ec, 0x0c00
ax_pose_terminator
sGrowlithePose225:
ax_pose 32, 0x01ea, 0x90f1, 0x0c00
ax_pose_terminator
sGrowlithePose226:
ax_pose 31, 0x01e6, 0x90ed, 0x0c00
ax_pose_terminator
sGrowlithePose227:
ax_pose 0, 0x81e6, 0x80f8, 0x0c00
ax_pose_terminator
sGrowlithePose228:
ax_pose 3, 0x01e6, 0x80f3, 0x0c00
ax_pose_terminator
sGrowlithePose229:
ax_pose 6, 0x01ec, 0x80f0, 0x0c00
ax_pose_terminator
sGrowlithePose230:
ax_pose 9, 0x01e6, 0x80f5, 0x0c00
ax_pose_terminator
sGrowlithePose231:
ax_pose 12, 0x81e6, 0x80f8, 0x0c00
ax_pose_terminator
sGrowlithePose232:
ax_pose 9, 0x01e6, 0x90eb, 0x0c00
ax_pose_terminator
sGrowlithePose233:
ax_pose 6, 0x01ec, 0x90f0, 0x0c00
ax_pose_terminator
sGrowlithePose234:
ax_pose 3, 0x01e6, 0x90ed, 0x0c00
ax_pose_terminator
.align 2
sGrowlitheAnims_1_1:
ax_anim 6, 0, 0, 0, 0, 0, 0,
ax_anim 8, 0, 1, 0, 0, 0, 0,
ax_anim 6, 0, 0, 0, 0, 0, 0,
ax_anim 8, 0, 2, 0, 0, 0, 0,
ax_anim_terminator
sGrowlitheAnims_1_2:
ax_anim 6, 0, 3, 0, 0, 0, 0,
ax_anim 8, 0, 4, 0, 0, 0, 0,
ax_anim 6, 0, 3, 0, 0, 0, 0,
ax_anim 8, 0, 5, 0, 0, 0, 0,
ax_anim_terminator
sGrowlitheAnims_1_3:
ax_anim 6, 0, 6, 0, 0, 0, 0,
ax_anim 8, 0, 7, 0, 0, 0, 0,
ax_anim 6, 0, 6, 0, 0, 0, 0,
ax_anim 8, 0, 8, 0, 0, 0, 0,
ax_anim_terminator
sGrowlitheAnims_1_4:
ax_anim 6, 0, 9, 0, 0, 0, 0,
ax_anim 8, 0, 10, 0, 0, 0, 0,
ax_anim 6, 0, 9, 0, 0, 0, 0,
ax_anim 8, 0, 11, 0, 0, 0, 0,
ax_anim_terminator
sGrowlitheAnims_1_5:
ax_anim 6, 0, 12, 0, 0, 0, 0,
ax_anim 8, 0, 13, 0, 0, 0, 0,
ax_anim 6, 0, 12, 0, 0, 0, 0,
ax_anim 8, 0, 14, 0, 0, 0, 0,
ax_anim_terminator
sGrowlitheAnims_1_6:
ax_anim 6, 0, 15, 0, 0, 0, 0,
ax_anim 8, 0, 16, 0, 0, 0, 0,
ax_anim 6, 0, 15, 0, 0, 0, 0,
ax_anim 8, 0, 17, 0, 0, 0, 0,
ax_anim_terminator
sGrowlitheAnims_1_7:
ax_anim 6, 0, 18, 0, 0, 0, 0,
ax_anim 8, 0, 19, 0, 0, 0, 0,
ax_anim 6, 0, 18, 0, 0, 0, 0,
ax_anim 8, 0, 20, 0, 0, 0, 0,
ax_anim_terminator
sGrowlitheAnims_1_8:
ax_anim 6, 0, 21, 0, 0, 0, 0,
ax_anim 8, 0, 22, 0, 0, 0, 0,
ax_anim 6, 0, 21, 0, 0, 0, 0,
ax_anim 8, 0, 23, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sGrowlitheAnims_2_1:
ax_anim 2, 0, 25, 0, -3, 0, -3,
ax_anim 2, 0, 26, 0, -6, 0, -6,
ax_anim 6, 0, 24, 0, -8, 0, -8,
ax_anim 2, 0, 27, 0, -2, 0, -2,
ax_anim 2, 2, 28, 0, 7, 0, 7,
ax_anim 2, 0, 27, 0, 9, 0, 9,
ax_anim 2, 0, 28, 0, 20, 0, 20,
ax_anim 2, 1, 28, -1, 20, -1, 20,
ax_anim 2, 0, 28, 0, 20, 0, 20,
ax_anim 2, 0, 28, -1, 20, -1, 20,
ax_anim 2, 0, 28, 0, 20, 0, 20,
ax_anim 2, 0, 25, 0, 11, 0, 11,
ax_anim 2, 0, 24, 0, 4, 0, 4,
ax_anim_terminator
sGrowlitheAnims_2_2:
ax_anim 2, 0, 30, -3, -3, -3, -3,
ax_anim 2, 0, 31, -6, -6, -6, -6,
ax_anim 6, 0, 29, -8, -8, -8, -8,
ax_anim 2, 0, 32, -2, -2, -2, -2,
ax_anim 2, 2, 33, 5, 5, 5, 5,
ax_anim 2, 0, 32, 11, 11, 11, 11,
ax_anim 2, 0, 33, 20, 18, 20, 18,
ax_anim 2, 1, 33, 19, 19, 19, 19,
ax_anim 2, 0, 33, 20, 18, 20, 18,
ax_anim 2, 0, 33, 19, 19, 19, 19,
ax_anim 2, 0, 33, 20, 18, 20, 18,
ax_anim 2, 0, 30, 11, 11, 11, 11,
ax_anim 2, 0, 29, 4, 4, 4, 4,
ax_anim_terminator
sGrowlitheAnims_2_3:
ax_anim 2, 0, 35, -3, 0, -3, 0,
ax_anim 2, 0, 36, -6, 0, -6, 0,
ax_anim 6, 0, 34, -8, 0, -8, 0,
ax_anim 2, 0, 37, -2, 0, -2, 0,
ax_anim 2, 2, 38, 5, 0, 5, 0,
ax_anim 2, 0, 37, 11, 0, 11, 0,
ax_anim 2, 0, 38, 16, 0, 16, 0,
ax_anim 2, 1, 38, 16, 1, 16, 1,
ax_anim 2, 0, 38, 16, 0, 16, 0,
ax_anim 2, 0, 38, 16, 1, 16, 1,
ax_anim 2, 0, 38, 16, 0, 16, 0,
ax_anim 2, 0, 35, 11, 0, 11, 0,
ax_anim 2, 0, 34, 4, 0, 4, 0,
ax_anim_terminator
sGrowlitheAnims_2_4:
ax_anim 2, 0, 40, -3, 3, -3, 3,
ax_anim 2, 0, 41, -6, 6, -6, 6,
ax_anim 6, 0, 39, -8, 8, -8, 8,
ax_anim 2, 0, 42, -2, 2, -2, 2,
ax_anim 2, 2, 43, 4, -7, 4, -7,
ax_anim 2, 0, 42, 11, -14, 11, -14,
ax_anim 2, 0, 43, 15, -21, 15, -21,
ax_anim 2, 1, 43, 14, -22, 14, -22,
ax_anim 2, 0, 43, 15, -21, 15, -21,
ax_anim 2, 0, 43, 14, -22, 14, -22,
ax_anim 2, 0, 43, 15, -21, 15, -21,
ax_anim 2, 0, 40, 9, -13, 9, -13,
ax_anim 2, 0, 39, 3, -5, 3, -5,
ax_anim_terminator
sGrowlitheAnims_2_5:
ax_anim 2, 0, 45, 0, 3, 0, 3,
ax_anim 2, 0, 46, 0, 6, 0, 6,
ax_anim 6, 0, 44, 0, 8, 0, 8,
ax_anim 2, 0, 47, 0, 2, 0, 2,
ax_anim 2, 2, 48, 0, -7, 0, -7,
ax_anim 2, 0, 47, 0, -11, 0, -11,
ax_anim 2, 0, 48, 0, -20, 0, -20,
ax_anim 2, 1, 48, -1, -20, -1, -20,
ax_anim 2, 0, 48, 0, -20, 0, -20,
ax_anim 2, 0, 48, -1, -20, -1, -20,
ax_anim 2, 0, 48, 0, -20, 0, -20,
ax_anim 2, 0, 45, 0, -11, 0, -11,
ax_anim 2, 0, 44, 0, -4, 0, -4,
ax_anim_terminator
sGrowlitheAnims_2_6:
ax_anim 2, 0, 50, 3, 3, 3, 3,
ax_anim 2, 0, 51, 6, 6, 6, 6,
ax_anim 6, 0, 49, 8, 8, 8, 8,
ax_anim 2, 0, 52, 2, 2, 2, 2,
ax_anim 2, 2, 53, -4, -7, -4, -7,
ax_anim 2, 0, 52, -11, -14, -11, -14,
ax_anim 2, 0, 53, -15, -21, -15, -21,
ax_anim 2, 1, 53, -14, -22, -14, -22,
ax_anim 2, 0, 53, -15, -21, -15, -21,
ax_anim 2, 0, 53, -14, -22, -14, -22,
ax_anim 2, 0, 53, -15, -21, -15, -21,
ax_anim 2, 0, 50, -9, -13, -9, -13,
ax_anim 2, 0, 49, -3, -5, -3, -5,
ax_anim_terminator
sGrowlitheAnims_2_7:
ax_anim 2, 0, 55, 3, 0, 3, 0,
ax_anim 2, 0, 56, 6, 0, 6, 0,
ax_anim 6, 0, 54, 8, 0, 8, 0,
ax_anim 2, 0, 57, 2, 0, 2, 0,
ax_anim 2, 2, 58, -5, 0, -5, 0,
ax_anim 2, 0, 57, -11, 0, -11, 0,
ax_anim 2, 0, 58, -16, 0, -16, 0,
ax_anim 2, 1, 58, -16, 1, -16, 1,
ax_anim 2, 0, 58, -16, 0, -16, 0,
ax_anim 2, 0, 58, -16, 1, -16, 1,
ax_anim 2, 0, 58, -16, 0, -16, 0,
ax_anim 2, 0, 55, -11, 0, -11, 0,
ax_anim 2, 0, 54, -4, 0, -4, 0,
ax_anim_terminator
sGrowlitheAnims_2_8:
ax_anim 2, 0, 60, 3, -3, 3, -3,
ax_anim 2, 0, 61, 6, -6, 6, -6,
ax_anim 6, 0, 59, 8, -8, 8, -8,
ax_anim 2, 0, 62, 2, -2, 2, -2,
ax_anim 2, 2, 63, -5, 5, -5, 5,
ax_anim 2, 0, 62, -11, 11, -11, 11,
ax_anim 2, 0, 63, -20, 18, -20, 18,
ax_anim 2, 1, 63, -19, 19, -19, 19,
ax_anim 2, 0, 63, -20, 18, -20, 18,
ax_anim 2, 0, 63, -19, 19, -19, 19,
ax_anim 2, 0, 63, -20, 18, -20, 18,
ax_anim 2, 0, 60, -11, 11, -11, 11,
ax_anim 2, 0, 59, -4, 4, -4, 4,
ax_anim_terminator
.align 2
sGrowlitheAnims_3_1:
ax_anim 2, 0, 65, 0, -3, 0, -3,
ax_anim 2, 0, 66, 0, -6, 0, -6,
ax_anim 6, 0, 64, 0, -8, 0, -8,
ax_anim 2, 0, 67, 0, -2, 0, -2,
ax_anim 2, 2, 68, 0, 7, 0, 7,
ax_anim 2, 0, 67, 0, 9, 0, 9,
ax_anim 2, 0, 68, 0, 20, 0, 20,
ax_anim 2, 1, 68, -1, 20, -1, 20,
ax_anim 2, 0, 68, 0, 20, 0, 20,
ax_anim 2, 0, 68, -1, 20, -1, 20,
ax_anim 2, 0, 68, 0, 20, 0, 20,
ax_anim 2, 0, 65, 0, 11, 0, 11,
ax_anim 2, 0, 64, 0, 4, 0, 4,
ax_anim_terminator
sGrowlitheAnims_3_2:
ax_anim 2, 0, 70, -3, -3, -3, -3,
ax_anim 2, 0, 71, -6, -6, -6, -6,
ax_anim 6, 0, 69, -8, -8, -8, -8,
ax_anim 2, 0, 72, -2, -2, -2, -2,
ax_anim 2, 2, 73, 5, 5, 5, 5,
ax_anim 2, 0, 72, 11, 11, 11, 11,
ax_anim 2, 0, 73, 20, 18, 20, 18,
ax_anim 2, 1, 73, 19, 19, 19, 19,
ax_anim 2, 0, 73, 20, 18, 20, 18,
ax_anim 2, 0, 73, 19, 19, 19, 19,
ax_anim 2, 0, 73, 20, 18, 20, 18,
ax_anim 2, 0, 70, 11, 11, 11, 11,
ax_anim 2, 0, 69, 4, 4, 4, 4,
ax_anim_terminator
sGrowlitheAnims_3_3:
ax_anim 2, 0, 75, -3, 0, -3, 0,
ax_anim 2, 0, 76, -6, 0, -6, 0,
ax_anim 6, 0, 74, -8, 0, -8, 0,
ax_anim 2, 0, 77, -2, 0, -2, 0,
ax_anim 2, 2, 78, 5, 0, 5, 0,
ax_anim 2, 0, 77, 11, 0, 11, 0,
ax_anim 2, 0, 78, 16, 0, 16, 0,
ax_anim 2, 1, 78, 16, 1, 16, 1,
ax_anim 2, 0, 78, 16, 0, 16, 0,
ax_anim 2, 0, 78, 16, 1, 16, 1,
ax_anim 2, 0, 78, 16, 0, 16, 0,
ax_anim 2, 0, 75, 11, 0, 11, 0,
ax_anim 2, 0, 74, 4, 0, 4, 0,
ax_anim_terminator
sGrowlitheAnims_3_4:
ax_anim 2, 0, 80, -3, 3, -3, 3,
ax_anim 2, 0, 81, -6, 6, -6, 6,
ax_anim 6, 0, 79, -8, 8, -8, 8,
ax_anim 2, 0, 82, -2, 2, -2, 2,
ax_anim 2, 2, 83, 4, -7, 4, -7,
ax_anim 2, 0, 82, 11, -14, 11, -14,
ax_anim 2, 0, 83, 15, -21, 15, -21,
ax_anim 2, 1, 83, 14, -22, 14, -22,
ax_anim 2, 0, 83, 15, -21, 15, -21,
ax_anim 2, 0, 83, 14, -22, 14, -22,
ax_anim 2, 0, 83, 15, -21, 15, -21,
ax_anim 2, 0, 80, 9, -13, 9, -13,
ax_anim 2, 0, 79, 3, -5, 3, -5,
ax_anim_terminator
sGrowlitheAnims_3_5:
ax_anim 2, 0, 85, 0, 3, 0, 3,
ax_anim 2, 0, 86, 0, 6, 0, 6,
ax_anim 6, 0, 84, 0, 8, 0, 8,
ax_anim 2, 0, 87, 0, 2, 0, 2,
ax_anim 2, 2, 88, 0, -7, 0, -7,
ax_anim 2, 0, 87, 0, -11, 0, -11,
ax_anim 2, 0, 88, 0, -20, 0, -20,
ax_anim 2, 1, 88, -1, -20, -1, -20,
ax_anim 2, 0, 88, 0, -20, 0, -20,
ax_anim 2, 0, 88, -1, -20, -1, -20,
ax_anim 2, 0, 88, 0, -20, 0, -20,
ax_anim 2, 0, 85, 0, -11, 0, -11,
ax_anim 2, 0, 84, 0, -4, 0, -4,
ax_anim_terminator
sGrowlitheAnims_3_6:
ax_anim 2, 0, 90, 3, 3, 3, 3,
ax_anim 2, 0, 91, 6, 6, 6, 6,
ax_anim 6, 0, 89, 8, 8, 8, 8,
ax_anim 2, 0, 92, 2, 2, 2, 2,
ax_anim 2, 2, 93, -4, -7, -4, -7,
ax_anim 2, 0, 92, -11, -14, -11, -14,
ax_anim 2, 0, 93, -15, -21, -15, -21,
ax_anim 2, 1, 93, -14, -22, -14, -22,
ax_anim 2, 0, 93, -15, -21, -15, -21,
ax_anim 2, 0, 93, -14, -22, -14, -22,
ax_anim 2, 0, 93, -15, -21, -15, -21,
ax_anim 2, 0, 90, -9, -13, -9, -13,
ax_anim 2, 0, 89, -3, -5, -3, -5,
ax_anim_terminator
sGrowlitheAnims_3_7:
ax_anim 2, 0, 95, 3, 0, 3, 0,
ax_anim 2, 0, 96, 6, 0, 6, 0,
ax_anim 6, 0, 94, 8, 0, 8, 0,
ax_anim 2, 0, 97, 2, 0, 2, 0,
ax_anim 2, 2, 98, -5, 0, -5, 0,
ax_anim 2, 0, 97, -11, 0, -11, 0,
ax_anim 2, 0, 98, -16, 0, -16, 0,
ax_anim 2, 1, 98, -16, 1, -16, 1,
ax_anim 2, 0, 98, -16, 0, -16, 0,
ax_anim 2, 0, 98, -16, 1, -16, 1,
ax_anim 2, 0, 98, -16, 0, -16, 0,
ax_anim 2, 0, 95, -11, 0, -11, 0,
ax_anim 2, 0, 94, -4, 0, -4, 0,
ax_anim_terminator
sGrowlitheAnims_3_8:
ax_anim 2, 0, 100, 3, -3, 3, -3,
ax_anim 2, 0, 101, 6, -6, 6, -6,
ax_anim 6, 0, 99, 8, -8, 8, -8,
ax_anim 2, 0, 102, 2, -2, 2, -2,
ax_anim 2, 2, 103, -5, 5, -5, 5,
ax_anim 2, 0, 102, -11, 11, -11, 11,
ax_anim 2, 0, 103, -20, 18, -20, 18,
ax_anim 2, 1, 103, -19, 19, -19, 19,
ax_anim 2, 0, 103, -20, 18, -20, 18,
ax_anim 2, 0, 103, -19, 19, -19, 19,
ax_anim 2, 0, 103, -20, 18, -20, 18,
ax_anim 2, 0, 100, -11, 11, -11, 11,
ax_anim 2, 0, 99, -4, 4, -4, 4,
ax_anim_terminator
.align 2
sGrowlitheAnims_4_1:
ax_anim 2, 0, 105, 0, -2, 0, -2,
ax_anim 2, 0, 105, 0, -4, 0, -4,
ax_anim 6, 2, 104, 0, -4, 0, -5,
ax_anim 1, 0, 107, 0, 0, 0, 0,
ax_anim 2, 0, 107, 0, 3, 0, 3,
ax_anim 2, 1, 107, 1, 3, 1, 3,
ax_anim 2, 0, 107, 0, 3, 0, 3,
ax_anim 2, 0, 107, 1, 3, 1, 3,
ax_anim 2, 0, 107, 0, 3, 0, 3,
ax_anim 2, 0, 107, 1, 3, 1, 3,
ax_anim 2, 0, 107, 0, 3, 0, 3,
ax_anim 2, 0, 104, 0, 1, 0, 1,
ax_anim_terminator
sGrowlitheAnims_4_2:
ax_anim 2, 0, 109, -2, -2, -2, -2,
ax_anim 2, 0, 109, -4, -4, -4, -4,
ax_anim 6, 2, 108, -5, -5, -5, -5,
ax_anim 1, 0, 111, 0, 0, 0, 0,
ax_anim 2, 0, 111, 3, 3, 3, 3,
ax_anim 2, 1, 111, 4, 2, 4, 2,
ax_anim 2, 0, 111, 3, 3, 3, 3,
ax_anim 2, 0, 111, 4, 2, 4, 2,
ax_anim 2, 0, 111, 3, 3, 3, 3,
ax_anim 2, 0, 111, 4, 2, 4, 2,
ax_anim 2, 0, 111, 3, 3, 3, 3,
ax_anim 2, 0, 108, 1, 1, 1, 1,
ax_anim_terminator
sGrowlitheAnims_4_3:
ax_anim 2, 0, 113, -2, 0, -2, 0,
ax_anim 2, 0, 113, -4, 0, -4, 0,
ax_anim 6, 2, 112, -5, 0, -5, 0,
ax_anim 1, 0, 115, 0, 0, 0, 0,
ax_anim 2, 0, 115, 3, 0, 3, 0,
ax_anim 2, 1, 115, 3, 1, 3, 1,
ax_anim 2, 0, 115, 3, 0, 3, 0,
ax_anim 2, 0, 115, 3, 1, 3, 1,
ax_anim 2, 0, 115, 3, 0, 3, 0,
ax_anim 2, 0, 115, 3, 1, 3, 1,
ax_anim 2, 0, 115, 3, 0, 3, 0,
ax_anim 2, 0, 112, 1, 0, 1, 0,
ax_anim_terminator
sGrowlitheAnims_4_4:
ax_anim 2, 0, 117, -2, 2, -2, 2,
ax_anim 2, 0, 117, -4, 4, -4, 4,
ax_anim 6, 2, 116, -5, 5, -5, 5,
ax_anim 1, 0, 119, 0, 0, 0, 0,
ax_anim 2, 0, 119, 3, -3, 3, -3,
ax_anim 2, 1, 119, 4, -2, 4, -2,
ax_anim 2, 0, 119, 3, -3, 3, -3,
ax_anim 2, 0, 119, 4, -2, 4, -2,
ax_anim 2, 0, 119, 3, -3, 3, -3,
ax_anim 2, 0, 119, 4, -2, 4, -2,
ax_anim 2, 0, 119, 3, -3, 3, -3,
ax_anim 2, 0, 116, 1, -1, 1, -1,
ax_anim_terminator
sGrowlitheAnims_4_5:
ax_anim 2, 0, 121, 0, 2, 0, 2,
ax_anim 2, 0, 121, 0, 3, 0, 3,
ax_anim 6, 2, 120, 0, 5, 0, 5,
ax_anim 1, 0, 123, 0, 0, 0, 0,
ax_anim 2, 0, 123, 0, -3, 0, -3,
ax_anim 2, 1, 123, 1, -3, 1, -3,
ax_anim 2, 0, 123, 0, -3, 0, -3,
ax_anim 2, 0, 123, 1, -3, 1, -3,
ax_anim 2, 0, 123, 0, -3, 0, -3,
ax_anim 2, 0, 123, 1, -3, 1, -3,
ax_anim 2, 0, 123, 0, -3, 0, -3,
ax_anim 2, 0, 120, 0, -2, 0, -2,
ax_anim_terminator
sGrowlitheAnims_4_6:
ax_anim 2, 0, 125, 2, 2, 2, 2,
ax_anim 2, 0, 125, 4, 4, 4, 4,
ax_anim 6, 2, 124, 5, 5, 5, 5,
ax_anim 1, 0, 127, 0, 0, 0, 0,
ax_anim 2, 0, 127, -3, -3, -3, -3,
ax_anim 2, 1, 127, -4, -2, -4, -2,
ax_anim 2, 0, 127, -3, -3, -3, -3,
ax_anim 2, 0, 127, -4, -2, -4, -2,
ax_anim 2, 0, 127, -3, -3, -3, -3,
ax_anim 2, 0, 127, -4, -2, -4, -2,
ax_anim 2, 0, 127, -3, -3, -3, -3,
ax_anim 2, 0, 124, -1, -1, -1, -1,
ax_anim_terminator
sGrowlitheAnims_4_7:
ax_anim 2, 0, 129, 2, 0, 2, 0,
ax_anim 2, 0, 129, 4, 0, 4, 0,
ax_anim 6, 2, 128, 5, 0, 5, 0,
ax_anim 1, 0, 131, 0, 0, 0, 0,
ax_anim 2, 0, 131, -3, 0, -3, 0,
ax_anim 2, 1, 131, -3, 1, -3, 1,
ax_anim 2, 0, 131, -3, 0, -3, 0,
ax_anim 2, 0, 131, -3, 1, -3, 1,
ax_anim 2, 0, 131, -3, 0, -3, 0,
ax_anim 2, 0, 131, -3, 1, -3, 1,
ax_anim 2, 0, 131, -3, 0, -3, 0,
ax_anim 2, 0, 128, -1, 0, -1, 0,
ax_anim_terminator
sGrowlitheAnims_4_8:
ax_anim 2, 0, 133, 2, -2, 2, -2,
ax_anim 2, 0, 133, 4, -4, 4, -4,
ax_anim 6, 2, 132, 5, -5, 5, -5,
ax_anim 1, 0, 135, 0, 0, 0, 0,
ax_anim 2, 0, 135, -3, 3, -3, 3,
ax_anim 2, 1, 135, -4, 2, -4, 2,
ax_anim 2, 0, 135, -3, 3, -3, 3,
ax_anim 2, 0, 135, -4, 2, -4, 2,
ax_anim 2, 0, 135, -3, 3, -3, 3,
ax_anim 2, 0, 135, -4, 2, -4, 2,
ax_anim 2, 0, 135, -3, 3, -3, 3,
ax_anim 2, 0, 132, -1, 1, -1, 1,
ax_anim_terminator
.align 2
sGrowlitheAnims_5_1:
ax_anim 2, 0, 137, 0, -1, 0, 0,
ax_anim 2, 0, 137, 0, -4, 0, 0,
ax_anim 3, 0, 137, 0, -8, 0, 0,
ax_anim 3, 0, 137, 0, -9, 0, 0,
ax_anim 3, 2, 137, 0, -8, 0, 0,
ax_anim 2, 0, 137, 0, -3, 0, 0,
ax_anim 4, 0, 136, 0, 0, 0, 0,
ax_anim 2, 0, 138, -1, 0, -1, 0,
ax_anim 2, 0, 138, 0, 0, 0, 0,
ax_anim 2, 1, 138, -1, 0, -1, 0,
ax_anim 2, 0, 138, 0, 0, 0, 0,
ax_anim 2, 0, 138, -1, 0, -1, 0,
ax_anim 2, 0, 138, 0, 0, 0, 0,
ax_anim_terminator
sGrowlitheAnims_5_2:
ax_anim 2, 0, 140, 0, 0, 0, 0,
ax_anim 2, 0, 140, 0, -3, 0, 0,
ax_anim 3, 0, 140, 0, -8, 0, 0,
ax_anim 3, 0, 140, 0, -9, 0, 0,
ax_anim 3, 2, 140, 0, -8, 0, 0,
ax_anim 2, 0, 140, 0, -2, 0, 0,
ax_anim 4, 0, 139, 0, 0, 0, 0,
ax_anim 2, 0, 141, -1, 1, -1, 1,
ax_anim 2, 0, 141, 0, 0, 0, 0,
ax_anim 2, 1, 141, -1, 1, -1, 1,
ax_anim 2, 0, 141, 0, 0, 0, 0,
ax_anim 2, 0, 141, -1, 1, -1, 1,
ax_anim 2, 0, 141, 0, 0, 0, 0,
ax_anim_terminator
sGrowlitheAnims_5_3:
ax_anim 2, 0, 143, 0, 0, 0, 0,
ax_anim 2, 0, 143, 0, -3, 0, 0,
ax_anim 3, 0, 143, 0, -8, 0, 0,
ax_anim 3, 0, 143, 0, -9, 0, 0,
ax_anim 3, 2, 143, 0, -8, 0, 0,
ax_anim 2, 0, 143, 0, -2, 0, 0,
ax_anim 4, 0, 142, 0, 0, 0, 0,
ax_anim 2, 0, 144, 0, 1, 0, 1,
ax_anim 2, 0, 144, 0, 0, 0, 0,
ax_anim 2, 1, 144, 0, 1, 0, 1,
ax_anim 2, 0, 144, 0, 0, 0, 0,
ax_anim 2, 0, 144, 0, 1, 0, 1,
ax_anim 2, 0, 144, 0, 0, 0, 0,
ax_anim_terminator
sGrowlitheAnims_5_4:
ax_anim 2, 0, 146, 0, 0, 0, 0,
ax_anim 2, 0, 146, 0, -3, 0, 0,
ax_anim 3, 0, 146, 0, -8, 0, 0,
ax_anim 3, 0, 146, 0, -9, 0, 0,
ax_anim 3, 2, 146, 0, -8, 0, 0,
ax_anim 2, 0, 146, 0, -2, 0, 0,
ax_anim 4, 0, 145, 0, 0, 0, 0,
ax_anim 2, 0, 147, 1, 1, 1, 1,
ax_anim 2, 0, 147, 0, 0, 0, 0,
ax_anim 2, 1, 147, 1, 1, 1, 1,
ax_anim 2, 0, 147, 0, 0, 0, 0,
ax_anim 2, 0, 147, 1, 1, 1, 1,
ax_anim 2, 0, 147, 0, 0, 0, 0,
ax_anim_terminator
sGrowlitheAnims_5_5:
ax_anim 2, 0, 149, 0, 0, 0, 0,
ax_anim 2, 0, 149, 0, -3, 0, 0,
ax_anim 3, 0, 149, 0, -8, 0, 0,
ax_anim 3, 0, 149, 0, -9, 0, 0,
ax_anim 3, 2, 149, 0, -8, 0, 0,
ax_anim 2, 0, 149, 0, -2, 0, 0,
ax_anim 4, 0, 148, 0, 0, 0, 0,
ax_anim 2, 0, 150, -1, 0, -1, 0,
ax_anim 2, 0, 150, 0, 0, 0, 0,
ax_anim 2, 1, 150, -1, 0, -1, 0,
ax_anim 2, 0, 150, 0, 0, 0, 0,
ax_anim 2, 0, 150, -1, 0, -1, 0,
ax_anim 2, 0, 150, 0, 0, 0, 0,
ax_anim_terminator
sGrowlitheAnims_5_6:
ax_anim 2, 0, 152, 0, 0, 0, 0,
ax_anim 2, 0, 152, 0, -3, 0, 0,
ax_anim 3, 0, 152, 0, -8, 0, 0,
ax_anim 3, 0, 152, 0, -9, 0, 0,
ax_anim 3, 2, 152, 0, -8, 0, 0,
ax_anim 2, 0, 152, 0, -2, 0, 0,
ax_anim 4, 0, 151, 0, 0, 0, 0,
ax_anim 2, 0, 153, -1, 1, -1, 1,
ax_anim 2, 0, 153, 0, 0, 0, 0,
ax_anim 2, 1, 153, -1, 1, -1, 1,
ax_anim 2, 0, 153, 0, 0, 0, 0,
ax_anim 2, 0, 153, -1, 1, -1, 1,
ax_anim 2, 0, 153, 0, 0, 0, 0,
ax_anim_terminator
sGrowlitheAnims_5_7:
ax_anim 2, 0, 155, 0, 0, 0, 0,
ax_anim 2, 0, 155, 0, -3, 0, 0,
ax_anim 3, 0, 155, 0, -8, 0, 0,
ax_anim 3, 0, 155, 0, -9, 0, 0,
ax_anim 3, 2, 155, 0, -8, 0, 0,
ax_anim 2, 0, 155, 0, -2, 0, 0,
ax_anim 4, 0, 154, 0, 0, 0, 0,
ax_anim 2, 0, 156, 0, 1, 0, 1,
ax_anim 2, 0, 156, 0, 0, 0, 0,
ax_anim 2, 1, 156, 0, 1, 0, 1,
ax_anim 2, 0, 156, 0, 0, 0, 0,
ax_anim 2, 0, 156, 0, 1, 0, 1,
ax_anim 2, 0, 156, 0, 0, 0, 0,
ax_anim_terminator
sGrowlitheAnims_5_8:
ax_anim 2, 0, 158, 0, 0, 0, 0,
ax_anim 2, 0, 158, 0, -3, 0, 0,
ax_anim 3, 0, 158, 0, -8, 0, 0,
ax_anim 3, 0, 158, 0, -9, 0, 0,
ax_anim 3, 2, 158, 0, -8, 0, 0,
ax_anim 2, 0, 158, 0, -2, 0, 0,
ax_anim 4, 0, 157, 0, 0, 0, 0,
ax_anim 2, 0, 159, 1, 1, 1, 1,
ax_anim 2, 0, 159, 0, 0, 0, 0,
ax_anim 2, 1, 159, 1, 1, 1, 1,
ax_anim 2, 0, 159, 0, 0, 0, 0,
ax_anim 2, 0, 159, 1, 1, 1, 1,
ax_anim 2, 0, 159, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sGrowlitheAnims_6_1:
ax_anim 30, 0, 160, 0, 0, 0, 0,
ax_anim 35, 0, 161, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sGrowlitheAnims_7_1:
ax_anim 2, 0, 162, 0, -2, 0, -2,
ax_anim 8, 0, 162, 0, -3, 0, -3,
ax_anim_terminator
sGrowlitheAnims_7_2:
ax_anim 2, 0, 163, -2, -2, -2, -2,
ax_anim 8, 0, 163, -3, -3, -3, -3,
ax_anim_terminator
sGrowlitheAnims_7_3:
ax_anim 2, 0, 164, -2, 0, -2, 0,
ax_anim 8, 0, 164, -3, 0, -3, 0,
ax_anim_terminator
sGrowlitheAnims_7_4:
ax_anim 2, 0, 165, -2, 2, -2, 2,
ax_anim 8, 0, 165, -3, 3, -3, 3,
ax_anim_terminator
sGrowlitheAnims_7_5:
ax_anim 2, 0, 166, 0, 2, 0, 2,
ax_anim 8, 0, 166, 0, 3, 0, 3,
ax_anim_terminator
sGrowlitheAnims_7_6:
ax_anim 2, 0, 167, 2, 2, 2, 2,
ax_anim 8, 0, 167, 3, 3, 3, 3,
ax_anim_terminator
sGrowlitheAnims_7_7:
ax_anim 2, 0, 168, 2, 0, 2, 0,
ax_anim 8, 0, 168, 3, 0, 3, 0,
ax_anim_terminator
sGrowlitheAnims_7_8:
ax_anim 2, 0, 169, 2, -2, 2, -2,
ax_anim 8, 0, 169, 3, -3, 3, -3,
ax_anim_terminator
.align 2
sGrowlitheAnims_8_1:
ax_anim 40, 0, 170, 0, -1, 0, 0,
ax_anim 4, 0, 170, 0, -2, 0, 0,
ax_anim 2, 0, 170, 0, -1, 0, 0,
ax_anim_terminator
sGrowlitheAnims_8_2:
ax_anim 40, 0, 171, 0, -1, 0, 0,
ax_anim 4, 0, 171, 0, -2, 0, 0,
ax_anim 2, 0, 171, 0, -1, 0, 0,
ax_anim_terminator
sGrowlitheAnims_8_3:
ax_anim 40, 0, 172, 0, -1, 0, 0,
ax_anim 4, 0, 172, 0, -2, 0, 0,
ax_anim 2, 0, 172, 0, -1, 0, 0,
ax_anim_terminator
sGrowlitheAnims_8_4:
ax_anim 40, 0, 173, 0, -1, 0, 0,
ax_anim 4, 0, 173, 0, -2, 0, 0,
ax_anim 2, 0, 173, 0, -1, 0, 0,
ax_anim_terminator
sGrowlitheAnims_8_5:
ax_anim 40, 0, 174, 0, -1, 0, 0,
ax_anim 4, 0, 174, 0, -2, 0, 0,
ax_anim 2, 0, 174, 0, -1, 0, 0,
ax_anim_terminator
sGrowlitheAnims_8_6:
ax_anim 40, 0, 175, 0, -1, 0, 0,
ax_anim 4, 0, 175, 0, -2, 0, 0,
ax_anim 2, 0, 175, 0, -1, 0, 0,
ax_anim_terminator
sGrowlitheAnims_8_7:
ax_anim 40, 0, 176, 0, -1, 0, 0,
ax_anim 4, 0, 176, 0, -2, 0, 0,
ax_anim 2, 0, 176, 0, -1, 0, 0,
ax_anim_terminator
sGrowlitheAnims_8_8:
ax_anim 40, 0, 177, 0, -1, 0, 0,
ax_anim 4, 0, 177, 0, -2, 0, 0,
ax_anim 2, 0, 177, 0, -1, 0, 0,
ax_anim_terminator
.align 2
sGrowlitheAnims_9_1:
ax_anim 2, 0, 178, 0, 0, 0, 0,
ax_anim 1, 0, 179, 6, 3, 6, 3,
ax_anim 2, 0, 180, 8, 9, 8, 9,
ax_anim 2, 0, 181, 7, 16, 7, 16,
ax_anim 3, 0, 182, 0, 22, 0, 22,
ax_anim 2, 3, 183, -7, 16, -7, 16,
ax_anim 2, 0, 184, -8, 9, -8, 9,
ax_anim 1, 0, 185, -6, 3, -6, 3,
ax_anim 1, 0, 178, 0, 0, 0, 0,
ax_anim_terminator
sGrowlitheAnims_9_2:
ax_anim 2, 0, 185, 0, 0, 0, 0,
ax_anim 1, 0, 178, 8, 0, 8, 0,
ax_anim 2, 0, 179, 19, 3, 19, 3,
ax_anim 2, 0, 180, 23, 10, 23, 10,
ax_anim 3, 0, 181, 20, 21, 20, 21,
ax_anim 2, 3, 182, 11, 19, 11, 19,
ax_anim 2, 0, 183, 3, 15, 3, 15,
ax_anim 1, 0, 184, 0, 7, 0, 7,
ax_anim 1, 0, 185, 0, 0, 0, 0,
ax_anim_terminator
sGrowlitheAnims_9_3:
ax_anim 2, 0, 184, 0, 0, 0, 0,
ax_anim 1, 0, 185, 3, -5, 3, -5,
ax_anim 2, 0, 178, 11, -6, 11, -6,
ax_anim 2, 0, 179, 18, -5, 18, -5,
ax_anim 3, 0, 180, 21, -2, 21, -2,
ax_anim 2, 3, 181, 18, 4, 18, 4,
ax_anim 2, 0, 182, 12, 7, 12, 7,
ax_anim 1, 0, 183, 4, 5, 4, 5,
ax_anim 1, 0, 184, 0, 0, 0, 0,
ax_anim_terminator
sGrowlitheAnims_9_4:
ax_anim 2, 0, 183, 0, 0, 0, 0,
ax_anim 1, 0, 184, -1, -6, -1, -6,
ax_anim 2, 0, 185, 2, -16, 2, -16,
ax_anim 2, 0, 178, 12, -20, 12, -20,
ax_anim 3, 0, 179, 21, -21, 21, -21,
ax_anim 2, 3, 180, 22, -13, 22, -13,
ax_anim 2, 0, 181, 17, -4, 17, -4,
ax_anim 1, 0, 182, 9, 0, 9, 0,
ax_anim 1, 0, 183, 0, 0, 0, 0,
ax_anim_terminator
sGrowlitheAnims_9_5:
ax_anim 2, 0, 182, 0, 0, 0, 0,
ax_anim 1, 0, 183, -8, -4, -8, -4,
ax_anim 2, 0, 184, -9, -12, -9, -12,
ax_anim 2, 0, 185, -7, -18, -7, -18,
ax_anim 3, 0, 178, 0, -20, 0, -20,
ax_anim 2, 3, 179, 7, -18, 7, -18,
ax_anim 2, 0, 180, 9, -10, 9, -10,
ax_anim 1, 0, 181, 8, -4, 8, -4,
ax_anim 1, 0, 182, 0, 0, 0, 0,
ax_anim_terminator
sGrowlitheAnims_9_6:
ax_anim 2, 0, 181, 0, 0, 0, 0,
ax_anim 1, 0, 180, 1, -6, 1, -6,
ax_anim 2, 0, 179, -2, -16, -2, -16,
ax_anim 2, 0, 178, -12, -20, -12, -20,
ax_anim 3, 0, 185, -21, -21, -21, -21,
ax_anim 2, 3, 184, -22, -13, -22, -13,
ax_anim 2, 0, 183, -17, -4, -17, -4,
ax_anim 1, 0, 182, -9, 0, -9, 0,
ax_anim 1, 0, 181, 0, 0, 0, 0,
ax_anim_terminator
sGrowlitheAnims_9_7:
ax_anim 2, 0, 180, 0, 0, 0, 0,
ax_anim 1, 0, 179, -3, -5, -3, -5,
ax_anim 2, 0, 178, -11, -6, -11, -6,
ax_anim 2, 0, 185, -18, -5, -18, -5,
ax_anim 3, 0, 184, -21, -2, -21, -2,
ax_anim 2, 3, 183, -18, 4, -18, 4,
ax_anim 2, 0, 182, -12, 7, -12, 7,
ax_anim 1, 0, 181, -4, 5, -4, 5,
ax_anim 1, 0, 180, 0, 0, 0, 0,
ax_anim_terminator
sGrowlitheAnims_9_8:
ax_anim 2, 0, 179, 0, 0, 0, 0,
ax_anim 1, 0, 178, -8, 0, -8, 0,
ax_anim 2, 0, 185, -19, 3, -19, 3,
ax_anim 2, 0, 184, -23, 10, -23, 10,
ax_anim 3, 0, 183, -20, 21, -20, 21,
ax_anim 2, 3, 182, -11, 19, -11, 19,
ax_anim 2, 0, 181, -3, 15, -3, 15,
ax_anim 1, 0, 180, 0, 7, 0, 7,
ax_anim 1, 0, 179, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sGrowlitheAnims_10_1:
ax_anim 2, 0, 186, 0, 0, 0, 0,
ax_anim 2, 0, 186, 6, 0, 6, 0,
ax_anim 2, 0, 186, -6, 0, -6, 0,
ax_anim 2, 0, 186, 10, 0, 10, 0,
ax_anim 2, 0, 186, -10, 0, -10, 0,
ax_anim 2, 0, 186, 12, 0, 12, 0,
ax_anim 3, 0, 186, -12, 0, -12, 0,
ax_anim 3, 0, 186, 13, 0, 13, 0,
ax_anim 3, 0, 186, -13, 0, -13, 0,
ax_anim 2, 0, 186, 12, 0, 12, 0,
ax_anim 3, 0, 186, -12, 0, -12, 0,
ax_anim 2, 0, 186, 10, 0, 10, 0,
ax_anim 2, 0, 186, -10, 0, -10, 0,
ax_anim 2, 0, 186, 6, 0, 6, 0,
ax_anim 2, 0, 186, -6, 0, -6, 0,
ax_anim 2, 0, 186, 0, 0, 0, 0,
ax_anim_terminator
sGrowlitheAnims_10_2:
ax_anim 2, 0, 187, 0, 0, 0, 0,
ax_anim 2, 0, 187, 6, -6, 6, -6,
ax_anim 2, 0, 187, -6, 6, -6, 6,
ax_anim 2, 0, 187, 10, -10, 10, -10,
ax_anim 2, 0, 187, -10, 10, -10, 10,
ax_anim 2, 0, 187, 12, -12, 12, -12,
ax_anim 3, 0, 187, -12, 12, -12, 12,
ax_anim 3, 0, 187, 13, -13, 13, -13,
ax_anim 3, 0, 187, -13, 13, -13, 13,
ax_anim 2, 0, 187, 12, -12, 12, -12,
ax_anim 3, 0, 187, -12, 12, -12, 12,
ax_anim 2, 0, 187, 10, -10, 10, -10,
ax_anim 2, 0, 187, -10, 10, -10, 10,
ax_anim 2, 0, 187, 6, -6, 6, -6,
ax_anim 2, 0, 187, -6, 6, -6, 6,
ax_anim 2, 0, 187, 0, 0, 0, 0,
ax_anim_terminator
sGrowlitheAnims_10_3:
ax_anim 2, 0, 188, 0, 0, 0, 0,
ax_anim 2, 0, 188, 0, -6, 0, -6,
ax_anim 2, 0, 188, 0, 6, 0, 6,
ax_anim 2, 0, 188, 0, -10, 0, -10,
ax_anim 2, 0, 188, 0, 10, 0, 10,
ax_anim 2, 0, 188, 0, -12, 0, -12,
ax_anim 3, 0, 188, 0, 12, 0, 12,
ax_anim 3, 0, 188, 0, -13, 0, -13,
ax_anim 3, 0, 188, 0, 13, 0, 13,
ax_anim 2, 0, 188, 0, -12, 0, -12,
ax_anim 3, 0, 188, 0, 12, 0, 12,
ax_anim 2, 0, 188, 0, -10, 0, -10,
ax_anim 2, 0, 188, 0, 10, 0, 10,
ax_anim 2, 0, 188, 0, -6, 0, -6,
ax_anim 2, 0, 188, 0, 6, 0, 6,
ax_anim 2, 0, 188, 0, 0, 0, 0,
ax_anim_terminator
sGrowlitheAnims_10_4:
ax_anim 2, 0, 189, 0, 0, 0, 0,
ax_anim 2, 0, 189, -6, -6, -6, -6,
ax_anim 2, 0, 189, 6, 6, 6, 6,
ax_anim 2, 0, 189, -10, -10, -10, -10,
ax_anim 2, 0, 189, 10, 10, 10, 10,
ax_anim 2, 0, 189, -12, -12, -12, -12,
ax_anim 3, 0, 189, 12, 12, 12, 12,
ax_anim 3, 0, 189, -13, -13, -13, -13,
ax_anim 3, 0, 189, 13, 13, 13, 13,
ax_anim 2, 0, 189, -12, -12, -12, -12,
ax_anim 3, 0, 189, 12, 12, 12, 12,
ax_anim 2, 0, 189, -10, -10, -10, -10,
ax_anim 2, 0, 189, 10, 10, 10, 10,
ax_anim 2, 0, 189, -6, -6, -6, -6,
ax_anim 2, 0, 189, 6, 6, 6, 6,
ax_anim 2, 0, 189, 0, 0, 0, 0,
ax_anim_terminator
sGrowlitheAnims_10_5:
ax_anim 2, 0, 190, 0, 0, 0, 0,
ax_anim 2, 0, 190, 6, 0, 6, 0,
ax_anim 2, 0, 190, -6, 0, -6, 0,
ax_anim 2, 0, 190, 10, 0, 10, 0,
ax_anim 2, 0, 190, -10, 0, -10, 0,
ax_anim 2, 0, 190, 12, 0, 12, 0,
ax_anim 3, 0, 190, -12, 0, -12, 0,
ax_anim 3, 0, 190, 13, 0, 13, 0,
ax_anim 3, 0, 190, -13, 0, -13, 0,
ax_anim 2, 0, 190, 12, 0, 12, 0,
ax_anim 3, 0, 190, -12, 0, -12, 0,
ax_anim 2, 0, 190, 10, 0, 10, 0,
ax_anim 2, 0, 190, -10, 0, -10, 0,
ax_anim 2, 0, 190, 6, 0, 6, 0,
ax_anim 2, 0, 190, -6, 0, -6, 0,
ax_anim 2, 0, 190, 0, 0, 0, 0,
ax_anim_terminator
sGrowlitheAnims_10_6:
ax_anim 2, 0, 191, 0, 0, 0, 0,
ax_anim 2, 0, 191, 6, -6, 6, -6,
ax_anim 2, 0, 191, -6, 6, -6, 6,
ax_anim 2, 0, 191, 10, -10, 10, -10,
ax_anim 2, 0, 191, -10, 10, -10, 10,
ax_anim 2, 0, 191, 12, -12, 12, -12,
ax_anim 3, 0, 191, -12, 12, -12, 12,
ax_anim 3, 0, 191, 13, -13, 13, -13,
ax_anim 3, 0, 191, -13, 13, -13, 13,
ax_anim 2, 0, 191, 12, -12, 12, -12,
ax_anim 3, 0, 191, -12, 12, -12, 12,
ax_anim 2, 0, 191, 10, -10, 10, -10,
ax_anim 2, 0, 191, -10, 10, -10, 10,
ax_anim 2, 0, 191, 6, -6, 6, -6,
ax_anim 2, 0, 191, -6, 6, -6, 6,
ax_anim 2, 0, 191, 0, 0, 0, 0,
ax_anim_terminator
sGrowlitheAnims_10_7:
ax_anim 2, 0, 192, 0, 0, 0, 0,
ax_anim 2, 0, 192, 0, -6, 0, -6,
ax_anim 2, 0, 192, 0, 6, 0, 6,
ax_anim 2, 0, 192, 0, -10, 0, -10,
ax_anim 2, 0, 192, 0, 10, 0, 10,
ax_anim 2, 0, 192, 0, -12, 0, -12,
ax_anim 3, 0, 192, 0, 12, 0, 12,
ax_anim 3, 0, 192, 0, -13, 0, -13,
ax_anim 3, 0, 192, 0, 13, 0, 13,
ax_anim 2, 0, 192, 0, -12, 0, -12,
ax_anim 3, 0, 192, 0, 12, 0, 12,
ax_anim 2, 0, 192, 0, -10, 0, -10,
ax_anim 2, 0, 192, 0, 10, 0, 10,
ax_anim 2, 0, 192, 0, -6, 0, -6,
ax_anim 2, 0, 192, 0, 6, 0, 6,
ax_anim 2, 0, 192, 0, 0, 0, 0,
ax_anim_terminator
sGrowlitheAnims_10_8:
ax_anim 2, 0, 193, 0, 0, 0, 0,
ax_anim 2, 0, 193, -6, -6, -6, -6,
ax_anim 2, 0, 193, 6, 6, 6, 6,
ax_anim 2, 0, 193, -10, -10, -10, -10,
ax_anim 2, 0, 193, 10, 10, 10, 10,
ax_anim 2, 0, 193, -12, -12, -12, -12,
ax_anim 3, 0, 193, 12, 12, 12, 12,
ax_anim 3, 0, 193, -13, -13, -13, -13,
ax_anim 3, 0, 193, 13, 13, 13, 13,
ax_anim 2, 0, 193, -12, -12, -12, -12,
ax_anim 3, 0, 193, 12, 12, 12, 12,
ax_anim 2, 0, 193, -10, -10, -10, -10,
ax_anim 2, 0, 193, 10, 10, 10, 10,
ax_anim 2, 0, 193, -6, -6, -6, -6,
ax_anim 2, 0, 193, 6, 6, 6, 6,
ax_anim 2, 0, 193, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sGrowlitheAnims_11_1:
ax_anim 2, 0, 194, 0, 0, 0, 0,
ax_anim 1, 0, 195, 0, -10, 0, 0,
ax_anim 2, 0, 195, 0, -16, 0, 0,
ax_anim 3, 0, 195, 0, -20, 0, 0,
ax_anim 4, 0, 195, 0, -21, 0, 0,
ax_anim 4, 0, 196, 0, -23, 0, 0,
ax_anim 3, 0, 196, 0, -22, 0, 0,
ax_anim 2, 0, 196, 0, -18, 0, 0,
ax_anim 1, 0, 196, 0, -12, 0, 0,
ax_anim 2, 2, 194, 0, 0, 0, 0,
ax_anim_terminator
sGrowlitheAnims_11_2:
ax_anim 2, 0, 197, 0, 0, 0, 0,
ax_anim 1, 0, 198, 0, -10, 0, 0,
ax_anim 2, 0, 198, 0, -16, 0, 0,
ax_anim 3, 0, 198, 0, -20, 0, 0,
ax_anim 4, 0, 198, 0, -21, 0, 0,
ax_anim 4, 0, 199, 0, -23, 0, 0,
ax_anim 3, 0, 199, 0, -22, 0, 0,
ax_anim 2, 0, 199, 0, -18, 0, 0,
ax_anim 1, 0, 199, 0, -12, 0, 0,
ax_anim 2, 2, 197, 0, 0, 0, 0,
ax_anim_terminator
sGrowlitheAnims_11_3:
ax_anim 2, 0, 200, 0, 0, 0, 0,
ax_anim 1, 0, 201, 0, -10, 0, 0,
ax_anim 2, 0, 201, 0, -16, 0, 0,
ax_anim 3, 0, 201, 0, -20, 0, 0,
ax_anim 4, 0, 201, 0, -21, 0, 0,
ax_anim 4, 0, 202, 0, -23, 0, 0,
ax_anim 3, 0, 202, 0, -22, 0, 0,
ax_anim 2, 0, 202, 0, -18, 0, 0,
ax_anim 1, 0, 202, 0, -12, 0, 0,
ax_anim 2, 2, 200, 0, 0, 0, 0,
ax_anim_terminator
sGrowlitheAnims_11_4:
ax_anim 2, 0, 203, 0, 0, 0, 0,
ax_anim 1, 0, 204, 0, -10, 0, 0,
ax_anim 2, 0, 204, 0, -16, 0, 0,
ax_anim 3, 0, 204, 0, -20, 0, 0,
ax_anim 4, 0, 204, 0, -21, 0, 0,
ax_anim 4, 0, 205, 0, -22, 0, 0,
ax_anim 3, 0, 205, 0, -21, 0, 0,
ax_anim 2, 0, 205, 0, -17, 0, 0,
ax_anim 1, 0, 205, 0, -11, 0, 0,
ax_anim 2, 2, 203, 0, 0, 0, 0,
ax_anim_terminator
sGrowlitheAnims_11_5:
ax_anim 2, 0, 206, 0, 0, 0, 0,
ax_anim 1, 0, 207, 0, -10, 0, 0,
ax_anim 2, 0, 207, 0, -16, 0, 0,
ax_anim 3, 0, 207, 0, -20, 0, 0,
ax_anim 4, 0, 207, 0, -21, 0, 0,
ax_anim 4, 0, 208, 0, -23, 0, 0,
ax_anim 3, 0, 208, 0, -22, 0, 0,
ax_anim 2, 0, 208, 0, -18, 0, 0,
ax_anim 1, 0, 208, 0, -12, 0, 0,
ax_anim 2, 2, 206, 0, 0, 0, 0,
ax_anim_terminator
sGrowlitheAnims_11_6:
ax_anim 2, 0, 209, 0, 0, 0, 0,
ax_anim 1, 0, 210, 0, -10, 0, 0,
ax_anim 2, 0, 210, 0, -16, 0, 0,
ax_anim 3, 0, 210, 0, -20, 0, 0,
ax_anim 4, 0, 210, 0, -21, 0, 0,
ax_anim 4, 0, 211, 0, -22, 0, 0,
ax_anim 3, 0, 211, 0, -21, 0, 0,
ax_anim 2, 0, 211, 0, -17, 0, 0,
ax_anim 1, 0, 211, 0, -11, 0, 0,
ax_anim 2, 2, 209, 0, 0, 0, 0,
ax_anim_terminator
sGrowlitheAnims_11_7:
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 1, 0, 213, 0, -10, 0, 0,
ax_anim 2, 0, 213, 0, -16, 0, 0,
ax_anim 3, 0, 213, 0, -20, 0, 0,
ax_anim 4, 0, 213, 0, -21, 0, 0,
ax_anim 4, 0, 214, 0, -23, 0, 0,
ax_anim 3, 0, 214, 0, -22, 0, 0,
ax_anim 2, 0, 214, 0, -18, 0, 0,
ax_anim 1, 0, 214, 0, -12, 0, 0,
ax_anim 2, 2, 212, 0, 0, 0, 0,
ax_anim_terminator
sGrowlitheAnims_11_8:
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 1, 0, 216, 0, -10, 0, 0,
ax_anim 2, 0, 216, 0, -16, 0, 0,
ax_anim 3, 0, 216, 0, -20, 0, 0,
ax_anim 4, 0, 216, 0, -21, 0, 0,
ax_anim 4, 0, 217, 0, -23, 0, 0,
ax_anim 3, 0, 217, 0, -22, 0, 0,
ax_anim 2, 0, 217, 0, -18, 0, 0,
ax_anim 1, 0, 217, 0, -12, 0, 0,
ax_anim 2, 2, 215, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sGrowlitheAnims_12_1:
ax_anim 2, 0, 218, 1, 0, 1, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 218, 1, 0, 1, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 218, 1, 0, 1, 0,
ax_anim 2, 2, 218, 0, 0, 0, 0,
ax_anim 2, 0, 218, 1, 0, 1, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 218, 1, 0, 1, 0,
ax_anim 2, 1, 218, 0, 0, 0, 0,
ax_anim_terminator
sGrowlitheAnims_12_2:
ax_anim 2, 0, 225, 1, -1, 1, -1,
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 2, 0, 225, 1, -1, 1, -1,
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 2, 0, 225, 1, -1, 1, -1,
ax_anim 2, 2, 225, 0, 0, 0, 0,
ax_anim 2, 0, 225, 1, -1, 1, -1,
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 2, 0, 225, 1, -1, 1, -1,
ax_anim 2, 1, 225, 0, 0, 0, 0,
ax_anim_terminator
sGrowlitheAnims_12_3:
ax_anim 2, 0, 224, 0, -1, 0, -1,
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 2, 0, 224, 0, -1, 0, -1,
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 2, 0, 224, 0, -1, 0, -1,
ax_anim 2, 2, 224, 0, 0, 0, 0,
ax_anim 2, 0, 224, 0, -1, 0, -1,
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 2, 0, 224, 0, -1, 0, -1,
ax_anim 2, 1, 224, 0, 0, 0, 0,
ax_anim_terminator
sGrowlitheAnims_12_4:
ax_anim 2, 0, 223, -1, -1, -1, -1,
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 2, 0, 223, -1, -1, -1, -1,
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 2, 0, 223, -1, -1, -1, -1,
ax_anim 2, 2, 223, 0, 0, 0, 0,
ax_anim 2, 0, 223, -1, -1, -1, -1,
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 2, 0, 223, -1, -1, -1, -1,
ax_anim 2, 1, 223, 0, 0, 0, 0,
ax_anim_terminator
sGrowlitheAnims_12_5:
ax_anim 2, 0, 222, 1, 0, 1, 0,
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 0, 222, 1, 0, 1, 0,
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 0, 222, 1, 0, 1, 0,
ax_anim 2, 2, 222, 0, 0, 0, 0,
ax_anim 2, 0, 222, 1, 0, 1, 0,
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 0, 222, 1, 0, 1, 0,
ax_anim 2, 1, 222, 0, 0, 0, 0,
ax_anim_terminator
sGrowlitheAnims_12_6:
ax_anim 2, 0, 221, 1, -1, 1, -1,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 221, 1, -1, 1, -1,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 221, 1, -1, 1, -1,
ax_anim 2, 2, 221, 0, 0, 0, 0,
ax_anim 2, 0, 221, 1, -1, 1, -1,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 221, 1, -1, 1, -1,
ax_anim 2, 1, 221, 0, 0, 0, 0,
ax_anim_terminator
sGrowlitheAnims_12_7:
ax_anim 2, 0, 220, 0, -1, 0, -1,
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, -1, 0, -1,
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, -1, 0, -1,
ax_anim 2, 2, 220, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, -1, 0, -1,
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, -1, 0, -1,
ax_anim 2, 1, 220, 0, 0, 0, 0,
ax_anim_terminator
sGrowlitheAnims_12_8:
ax_anim 2, 0, 219, -1, -1, -1, -1,
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 0, 219, -1, -1, -1, -1,
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 0, 219, -1, -1, -1, -1,
ax_anim 2, 2, 219, 0, 0, 0, 0,
ax_anim 2, 0, 219, -1, -1, -1, -1,
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 0, 219, -1, -1, -1, -1,
ax_anim 2, 1, 219, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sGrowlitheAnims_13_1:
ax_anim 2, 0, 226, 0, 0, 0, 0,
ax_anim 2, 0, 227, 0, 0, 0, 0,
ax_anim 2, 0, 228, 0, 0, 0, 0,
ax_anim 2, 0, 229, 0, 0, 0, 0,
ax_anim 2, 0, 230, 0, 0, 0, 0,
ax_anim 2, 0, 231, 0, 0, 0, 0,
ax_anim 2, 0, 232, 0, 0, 0, 0,
ax_anim 2, 0, 233, 0, 0, 0, 0,
ax_anim 2, 2, 226, 0, 0, 0, 0,
ax_anim_terminator
sGrowlitheAnims_13_2:
ax_anim 2, 0, 233, 0, 0, 0, 0,
ax_anim 2, 0, 226, 0, 0, 0, 0,
ax_anim 2, 0, 227, 0, 0, 0, 0,
ax_anim 2, 0, 228, 0, 0, 0, 0,
ax_anim 2, 0, 229, 0, 0, 0, 0,
ax_anim 2, 0, 230, 0, 0, 0, 0,
ax_anim 2, 0, 231, 0, 0, 0, 0,
ax_anim 2, 0, 232, 0, 0, 0, 0,
ax_anim 2, 2, 233, 0, 0, 0, 0,
ax_anim_terminator
sGrowlitheAnims_13_3:
ax_anim 2, 0, 232, 0, 0, 0, 0,
ax_anim 2, 0, 233, 0, 0, 0, 0,
ax_anim 2, 0, 226, 0, 0, 0, 0,
ax_anim 2, 0, 227, 0, 0, 0, 0,
ax_anim 2, 0, 228, 0, 0, 0, 0,
ax_anim 2, 0, 229, 0, 0, 0, 0,
ax_anim 2, 0, 230, 0, 0, 0, 0,
ax_anim 2, 0, 231, 0, 0, 0, 0,
ax_anim 2, 2, 232, 0, 0, 0, 0,
ax_anim_terminator
sGrowlitheAnims_13_4:
ax_anim 2, 0, 231, 0, 0, 0, 0,
ax_anim 2, 0, 232, 0, 0, 0, 0,
ax_anim 2, 0, 233, 0, 0, 0, 0,
ax_anim 2, 0, 226, 0, 0, 0, 0,
ax_anim 2, 0, 227, 0, 0, 0, 0,
ax_anim 2, 0, 228, 0, 0, 0, 0,
ax_anim 2, 0, 229, 0, 0, 0, 0,
ax_anim 2, 0, 230, 0, 0, 0, 0,
ax_anim 2, 2, 231, 0, 0, 0, 0,
ax_anim_terminator
sGrowlitheAnims_13_5:
ax_anim 2, 0, 230, 0, 0, 0, 0,
ax_anim 2, 0, 231, 0, 0, 0, 0,
ax_anim 2, 0, 232, 0, 0, 0, 0,
ax_anim 2, 0, 233, 0, 0, 0, 0,
ax_anim 2, 0, 226, 0, 0, 0, 0,
ax_anim 2, 0, 227, 0, 0, 0, 0,
ax_anim 2, 0, 228, 0, 0, 0, 0,
ax_anim 2, 0, 229, 0, 0, 0, 0,
ax_anim 2, 2, 230, 0, 0, 0, 0,
ax_anim_terminator
sGrowlitheAnims_13_6:
ax_anim 2, 0, 229, 0, 0, 0, 0,
ax_anim 2, 0, 230, 0, 0, 0, 0,
ax_anim 2, 0, 231, 0, 0, 0, 0,
ax_anim 2, 0, 232, 0, 0, 0, 0,
ax_anim 2, 0, 233, 0, 0, 0, 0,
ax_anim 2, 0, 226, 0, 0, 0, 0,
ax_anim 2, 0, 227, 0, 0, 0, 0,
ax_anim 2, 0, 228, 0, 0, 0, 0,
ax_anim 2, 2, 229, 0, 0, 0, 0,
ax_anim_terminator
sGrowlitheAnims_13_7:
ax_anim 2, 0, 228, 0, 0, 0, 0,
ax_anim 2, 0, 229, 0, 0, 0, 0,
ax_anim 2, 0, 230, 0, 0, 0, 0,
ax_anim 2, 0, 231, 0, 0, 0, 0,
ax_anim 2, 0, 232, 0, 0, 0, 0,
ax_anim 2, 0, 233, 0, 0, 0, 0,
ax_anim 2, 0, 226, 0, 0, 0, 0,
ax_anim 2, 0, 227, 0, 0, 0, 0,
ax_anim 2, 2, 228, 0, 0, 0, 0,
ax_anim_terminator
sGrowlitheAnims_13_8:
ax_anim 2, 0, 227, 0, 0, 0, 0,
ax_anim 2, 0, 228, 0, 0, 0, 0,
ax_anim 2, 0, 229, 0, 0, 0, 0,
ax_anim 2, 0, 230, 0, 0, 0, 0,
ax_anim 2, 0, 231, 0, 0, 0, 0,
ax_anim 2, 0, 232, 0, 0, 0, 0,
ax_anim 2, 0, 233, 0, 0, 0, 0,
ax_anim 2, 0, 226, 0, 0, 0, 0,
ax_anim 2, 2, 227, 0, 0, 0, 0,
ax_anim_terminator
sGrowlitheGfx1:
.incbin "baserom.gba", 0x788860, 0x100
sGrowlitheSprites1:
ax_sprite sGrowlitheGfx1, 0x100
ax_sprite_terminator
sGrowlitheGfx2:
.incbin "baserom.gba", 0x788970, 0x100
sGrowlitheSprites2:
ax_sprite sGrowlitheGfx2, 0x100
ax_sprite_terminator
sGrowlitheGfx3:
.incbin "baserom.gba", 0x788A80, 0x100
sGrowlitheSprites3:
ax_sprite sGrowlitheGfx3, 0x100
ax_sprite_terminator
sGrowlitheGfx4:
.incbin "baserom.gba", 0x788B90, 0x200
sGrowlitheSprites4:
ax_sprite sGrowlitheGfx4, 0x200
ax_sprite_terminator
sGrowlitheGfx5:
.incbin "baserom.gba", 0x788DA0, 0x200
sGrowlitheSprites5:
ax_sprite sGrowlitheGfx5, 0x200
ax_sprite_terminator
sGrowlitheGfx6:
.incbin "baserom.gba", 0x788FB0, 0x200
sGrowlitheSprites6:
ax_sprite sGrowlitheGfx6, 0x200
ax_sprite_terminator
sGrowlitheGfx7:
.incbin "baserom.gba", 0x7891C0, 0x200
sGrowlitheSprites7:
ax_sprite sGrowlitheGfx7, 0x200
ax_sprite_terminator
sGrowlitheGfx8:
.incbin "baserom.gba", 0x7893D0, 0x200
sGrowlitheSprites8:
ax_sprite sGrowlitheGfx8, 0x200
ax_sprite_terminator
sGrowlitheGfx9:
.incbin "baserom.gba", 0x7895E0, 0x200
sGrowlitheSprites9:
ax_sprite sGrowlitheGfx9, 0x200
ax_sprite_terminator
sGrowlitheGfx10:
.incbin "baserom.gba", 0x7897F0, 0x200
sGrowlitheSprites10:
ax_sprite sGrowlitheGfx10, 0x200
ax_sprite_terminator
sGrowlitheGfx11:
.incbin "baserom.gba", 0x789A00, 0x200
sGrowlitheSprites11:
ax_sprite sGrowlitheGfx11, 0x200
ax_sprite_terminator
sGrowlitheGfx12:
.incbin "baserom.gba", 0x789C10, 0x200
sGrowlitheSprites12:
ax_sprite sGrowlitheGfx12, 0x200
ax_sprite_terminator
sGrowlitheGfx13:
.incbin "baserom.gba", 0x789E20, 0x100
sGrowlitheSprites13:
ax_sprite sGrowlitheGfx13, 0x100
ax_sprite_terminator
sGrowlitheGfx14:
.incbin "baserom.gba", 0x789F30, 0x100
sGrowlitheSprites14:
ax_sprite sGrowlitheGfx14, 0x100
ax_sprite_terminator
sGrowlitheGfx15:
.incbin "baserom.gba", 0x78A040, 0x100
sGrowlitheSprites15:
ax_sprite sGrowlitheGfx15, 0x100
ax_sprite_terminator
sGrowlitheGfx16:
.incbin "baserom.gba", 0x78A150, 0x40
sGrowlitheGfx16_1:
.incbin "baserom.gba", 0x78A190, 0x60
sGrowlitheGfx16_2:
.incbin "baserom.gba", 0x78A1F0, 0x60
sGrowlitheSprites16:
ax_sprite sGrowlitheGfx16, 0x40
ax_sprite 0, 0x40
ax_sprite sGrowlitheGfx16_1, 0x60
ax_sprite 0, 0x20
ax_sprite sGrowlitheGfx16_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sGrowlitheGfx17:
.incbin "baserom.gba", 0x78A288, 0x40
sGrowlitheGfx17_1:
.incbin "baserom.gba", 0x78A2C8, 0x60
sGrowlitheGfx17_2:
.incbin "baserom.gba", 0x78A328, 0x60
sGrowlitheGfx17_3:
.incbin "baserom.gba", 0x78A388, 0x40
sGrowlitheSprites17:
ax_sprite sGrowlitheGfx17, 0x40
ax_sprite 0, 0x40
ax_sprite sGrowlitheGfx17_1, 0x60
ax_sprite 0, 0x20
ax_sprite sGrowlitheGfx17_2, 0x60
ax_sprite 0, 0x20
ax_sprite sGrowlitheGfx17_3, 0x40
ax_sprite 0, 0x40
ax_sprite_terminator
sGrowlitheGfx18:
.incbin "baserom.gba", 0x78A410, 0x180
sGrowlitheGfx18_1:
.incbin "baserom.gba", 0x78A590, 0x20
sGrowlitheSprites18:
ax_sprite sGrowlitheGfx18, 0x180
ax_sprite 0, 0x40
ax_sprite sGrowlitheGfx18_1, 0x20
ax_sprite 0, 0x20
ax_sprite_terminator
sGrowlitheGfx19:
.incbin "baserom.gba", 0x78A5D8, 0x40
sGrowlitheGfx19_1:
.incbin "baserom.gba", 0x78A618, 0x60
sGrowlitheGfx19_2:
.incbin "baserom.gba", 0x78A678, 0x60
sGrowlitheGfx19_3:
.incbin "baserom.gba", 0x78A6D8, 0x60
sGrowlitheSprites19:
ax_sprite 0, 0x20
ax_sprite sGrowlitheGfx19, 0x40
ax_sprite 0, 0x20
ax_sprite sGrowlitheGfx19_1, 0x60
ax_sprite 0, 0x20
ax_sprite sGrowlitheGfx19_2, 0x60
ax_sprite 0, 0x20
ax_sprite sGrowlitheGfx19_3, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sGrowlitheGfx20:
.incbin "baserom.gba", 0x78A788, 0x180
sGrowlitheGfx20_1:
.incbin "baserom.gba", 0x78A908, 0x40
sGrowlitheSprites20:
ax_sprite sGrowlitheGfx20, 0x180
ax_sprite 0, 0x40
ax_sprite sGrowlitheGfx20_1, 0x40
ax_sprite_terminator
sGrowlitheGfx21:
.incbin "baserom.gba", 0x78A968, 0x140
sGrowlitheGfx21_1:
.incbin "baserom.gba", 0x78AAA8, 0x40
sGrowlitheSprites21:
ax_sprite 0, 0x40
ax_sprite sGrowlitheGfx21, 0x140
ax_sprite 0, 0x20
ax_sprite sGrowlitheGfx21_1, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sGrowlitheGfx22:
.incbin "baserom.gba", 0x78AB18, 0x60
sGrowlitheGfx22_1:
.incbin "baserom.gba", 0x78AB78, 0x100
sGrowlitheGfx22_2:
.incbin "baserom.gba", 0x78AC78, 0x60
sGrowlitheSprites22:
ax_sprite sGrowlitheGfx22, 0x60
ax_sprite 0, 0x20
ax_sprite sGrowlitheGfx22_1, 0x100
ax_sprite 0, 0x20
ax_sprite sGrowlitheGfx22_2, 0x60
ax_sprite_terminator
sGrowlitheGfx23:
.incbin "baserom.gba", 0x78AD08, 0x40
sGrowlitheGfx23_1:
.incbin "baserom.gba", 0x78AD48, 0x60
sGrowlitheGfx23_2:
.incbin "baserom.gba", 0x78ADA8, 0x60
sGrowlitheGfx23_3:
.incbin "baserom.gba", 0x78AE08, 0x40
sGrowlitheSprites23:
ax_sprite 0, 0x20
ax_sprite sGrowlitheGfx23, 0x40
ax_sprite 0, 0x20
ax_sprite sGrowlitheGfx23_1, 0x60
ax_sprite 0, 0x20
ax_sprite sGrowlitheGfx23_2, 0x60
ax_sprite 0, 0x40
ax_sprite sGrowlitheGfx23_3, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sGrowlitheGfx24:
.incbin "baserom.gba", 0x78AE98, 0x100
sGrowlitheSprites24:
ax_sprite sGrowlitheGfx24, 0x100
ax_sprite_terminator
sGrowlitheGfx25:
.incbin "baserom.gba", 0x78AFA8, 0x40
sGrowlitheGfx25_1:
.incbin "baserom.gba", 0x78AFE8, 0x60
sGrowlitheGfx25_2:
.incbin "baserom.gba", 0x78B048, 0x60
sGrowlitheGfx25_3:
.incbin "baserom.gba", 0x78B0A8, 0x40
sGrowlitheSprites25:
ax_sprite sGrowlitheGfx25, 0x40
ax_sprite 0, 0x40
ax_sprite sGrowlitheGfx25_1, 0x60
ax_sprite 0, 0x20
ax_sprite sGrowlitheGfx25_2, 0x60
ax_sprite 0, 0x20
ax_sprite sGrowlitheGfx25_3, 0x40
ax_sprite 0, 0x40
ax_sprite_terminator
sGrowlitheGfx26:
.incbin "baserom.gba", 0x78B130, 0x40
sGrowlitheGfx26_1:
.incbin "baserom.gba", 0x78B170, 0x40
sGrowlitheGfx26_2:
.incbin "baserom.gba", 0x78B1B0, 0x60
sGrowlitheGfx26_3:
.incbin "baserom.gba", 0x78B210, 0x60
sGrowlitheSprites26:
ax_sprite sGrowlitheGfx26, 0x40
ax_sprite 0, 0x40
ax_sprite sGrowlitheGfx26_1, 0x40
ax_sprite 0, 0x40
ax_sprite sGrowlitheGfx26_2, 0x60
ax_sprite 0, 0x20
ax_sprite sGrowlitheGfx26_3, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sGrowlitheGfx27:
.incbin "baserom.gba", 0x78B2B8, 0x40
sGrowlitheGfx27_1:
.incbin "baserom.gba", 0x78B2F8, 0x60
sGrowlitheGfx27_2:
.incbin "baserom.gba", 0x78B358, 0x60
sGrowlitheGfx27_3:
.incbin "baserom.gba", 0x78B3B8, 0x60
sGrowlitheSprites27:
ax_sprite 0, 0x20
ax_sprite sGrowlitheGfx27, 0x40
ax_sprite 0, 0x20
ax_sprite sGrowlitheGfx27_1, 0x60
ax_sprite 0, 0x20
ax_sprite sGrowlitheGfx27_2, 0x60
ax_sprite 0, 0x20
ax_sprite sGrowlitheGfx27_3, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sGrowlitheGfx28:
.incbin "baserom.gba", 0x78B468, 0x180
sGrowlitheSprites28:
ax_sprite sGrowlitheGfx28, 0x180
ax_sprite 0, 0x80
ax_sprite_terminator
sGrowlitheGfx29:
.incbin "baserom.gba", 0x78B600, 0x20
sGrowlitheGfx29_1:
.incbin "baserom.gba", 0x78B620, 0x60
sGrowlitheGfx29_2:
.incbin "baserom.gba", 0x78B680, 0x60
sGrowlitheGfx29_3:
.incbin "baserom.gba", 0x78B6E0, 0x60
sGrowlitheSprites29:
ax_sprite sGrowlitheGfx29, 0x20
ax_sprite 0, 0x60
ax_sprite sGrowlitheGfx29_1, 0x60
ax_sprite 0, 0x20
ax_sprite sGrowlitheGfx29_2, 0x60
ax_sprite 0, 0x20
ax_sprite sGrowlitheGfx29_3, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sGrowlitheGfx30:
.incbin "baserom.gba", 0x78B788, 0x100
sGrowlitheSprites30:
ax_sprite sGrowlitheGfx30, 0x100
ax_sprite_terminator
sGrowlitheGfx31:
.incbin "baserom.gba", 0x78B898, 0x100
sGrowlitheSprites31:
ax_sprite sGrowlitheGfx31, 0x100
ax_sprite_terminator
sGrowlitheGfx32:
.incbin "baserom.gba", 0x78B9A8, 0x40
sGrowlitheGfx32_1:
.incbin "baserom.gba", 0x78B9E8, 0x160
sGrowlitheSprites32:
ax_sprite sGrowlitheGfx32, 0x40
ax_sprite 0, 0x40
ax_sprite sGrowlitheGfx32_1, 0x160
ax_sprite 0, 0x20
ax_sprite_terminator
sGrowlitheGfx33:
.incbin "baserom.gba", 0x78BB70, 0x60
sGrowlitheGfx33_1:
.incbin "baserom.gba", 0x78BBD0, 0x80
sGrowlitheGfx33_2:
.incbin "baserom.gba", 0x78BC50, 0x60
sGrowlitheGfx33_3:
.incbin "baserom.gba", 0x78BCB0, 0x40
sGrowlitheSprites33:
ax_sprite sGrowlitheGfx33, 0x60
ax_sprite 0, 0x20
ax_sprite sGrowlitheGfx33_1, 0x80
ax_sprite 0, 0x20
ax_sprite sGrowlitheGfx33_2, 0x60
ax_sprite 0, 0x20
ax_sprite sGrowlitheGfx33_3, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sGrowlitheGfx34:
.incbin "baserom.gba", 0x78BD38, 0x60
sGrowlitheGfx34_1:
.incbin "baserom.gba", 0x78BD98, 0x60
sGrowlitheGfx34_2:
.incbin "baserom.gba", 0x78BDF8, 0x60
sGrowlitheGfx34_3:
.incbin "baserom.gba", 0x78BE58, 0x60
sGrowlitheSprites34:
ax_sprite sGrowlitheGfx34, 0x60
ax_sprite 0, 0x20
ax_sprite sGrowlitheGfx34_1, 0x60
ax_sprite 0, 0x20
ax_sprite sGrowlitheGfx34_2, 0x60
ax_sprite 0, 0x20
ax_sprite sGrowlitheGfx34_3, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sGrowlitheGfx35:
.incbin "baserom.gba", 0x78BF00, 0x100
sGrowlitheSprites35:
ax_sprite sGrowlitheGfx35, 0x100
ax_sprite_terminator
sGrowlitheGfx36:
.incbin "baserom.gba", 0x78C010, 0x200
sGrowlitheSprites36:
ax_sprite sGrowlitheGfx36, 0x200
ax_sprite_terminator
sGrowlitheGfx37:
.incbin "baserom.gba", 0x78C220, 0x200
sGrowlitheSprites37:
ax_sprite sGrowlitheGfx37, 0x200
ax_sprite_terminator
sGrowlitheGfx38:
.incbin "baserom.gba", 0x78C430, 0x200
sGrowlitheSprites38:
ax_sprite sGrowlitheGfx38, 0x200
ax_sprite_terminator
sGrowlitheGfx39:
.incbin "baserom.gba", 0x78C640, 0x200
sGrowlitheSprites39:
ax_sprite sGrowlitheGfx39, 0x200
ax_sprite_terminator
sGrowlitheGfx40:
.incbin "baserom.gba", 0x78C850, 0x200
sGrowlitheSprites40:
ax_sprite sGrowlitheGfx40, 0x200
ax_sprite_terminator
sGrowlitheGfx41:
.incbin "baserom.gba", 0x78CA60, 0x200
sGrowlitheSprites41:
ax_sprite sGrowlitheGfx41, 0x200
ax_sprite_terminator
sGrowlitheGfx42:
.incbin "baserom.gba", 0x78CC70, 0x200
sGrowlitheSprites42:
ax_sprite sGrowlitheGfx42, 0x200
ax_sprite_terminator
sAxPosesGrowlithe:
.4byte sGrowlithePose1
.4byte sGrowlithePose2
.4byte sGrowlithePose3
.4byte sGrowlithePose4
.4byte sGrowlithePose5
.4byte sGrowlithePose6
.4byte sGrowlithePose7
.4byte sGrowlithePose8
.4byte sGrowlithePose9
.4byte sGrowlithePose10
.4byte sGrowlithePose11
.4byte sGrowlithePose12
.4byte sGrowlithePose13
.4byte sGrowlithePose14
.4byte sGrowlithePose15
.4byte sGrowlithePose16
.4byte sGrowlithePose17
.4byte sGrowlithePose18
.4byte sGrowlithePose19
.4byte sGrowlithePose20
.4byte sGrowlithePose21
.4byte sGrowlithePose22
.4byte sGrowlithePose23
.4byte sGrowlithePose24
.4byte sGrowlithePose25
.4byte sGrowlithePose26
.4byte sGrowlithePose27
.4byte sGrowlithePose28
.4byte sGrowlithePose29
.4byte sGrowlithePose30
.4byte sGrowlithePose31
.4byte sGrowlithePose32
.4byte sGrowlithePose33
.4byte sGrowlithePose34
.4byte sGrowlithePose35
.4byte sGrowlithePose36
.4byte sGrowlithePose37
.4byte sGrowlithePose38
.4byte sGrowlithePose39
.4byte sGrowlithePose40
.4byte sGrowlithePose41
.4byte sGrowlithePose42
.4byte sGrowlithePose43
.4byte sGrowlithePose44
.4byte sGrowlithePose45
.4byte sGrowlithePose46
.4byte sGrowlithePose47
.4byte sGrowlithePose48
.4byte sGrowlithePose49
.4byte sGrowlithePose50
.4byte sGrowlithePose51
.4byte sGrowlithePose52
.4byte sGrowlithePose53
.4byte sGrowlithePose54
.4byte sGrowlithePose55
.4byte sGrowlithePose56
.4byte sGrowlithePose57
.4byte sGrowlithePose58
.4byte sGrowlithePose59
.4byte sGrowlithePose60
.4byte sGrowlithePose61
.4byte sGrowlithePose62
.4byte sGrowlithePose63
.4byte sGrowlithePose64
.4byte sGrowlithePose65
.4byte sGrowlithePose66
.4byte sGrowlithePose67
.4byte sGrowlithePose68
.4byte sGrowlithePose69
.4byte sGrowlithePose70
.4byte sGrowlithePose71
.4byte sGrowlithePose72
.4byte sGrowlithePose73
.4byte sGrowlithePose74
.4byte sGrowlithePose75
.4byte sGrowlithePose76
.4byte sGrowlithePose77
.4byte sGrowlithePose78
.4byte sGrowlithePose79
.4byte sGrowlithePose80
.4byte sGrowlithePose81
.4byte sGrowlithePose82
.4byte sGrowlithePose83
.4byte sGrowlithePose84
.4byte sGrowlithePose85
.4byte sGrowlithePose86
.4byte sGrowlithePose87
.4byte sGrowlithePose88
.4byte sGrowlithePose89
.4byte sGrowlithePose90
.4byte sGrowlithePose91
.4byte sGrowlithePose92
.4byte sGrowlithePose93
.4byte sGrowlithePose94
.4byte sGrowlithePose95
.4byte sGrowlithePose96
.4byte sGrowlithePose97
.4byte sGrowlithePose98
.4byte sGrowlithePose99
.4byte sGrowlithePose100
.4byte sGrowlithePose101
.4byte sGrowlithePose102
.4byte sGrowlithePose103
.4byte sGrowlithePose104
.4byte sGrowlithePose105
.4byte sGrowlithePose106
.4byte sGrowlithePose107
.4byte sGrowlithePose108
.4byte sGrowlithePose109
.4byte sGrowlithePose110
.4byte sGrowlithePose111
.4byte sGrowlithePose112
.4byte sGrowlithePose113
.4byte sGrowlithePose114
.4byte sGrowlithePose115
.4byte sGrowlithePose116
.4byte sGrowlithePose117
.4byte sGrowlithePose118
.4byte sGrowlithePose119
.4byte sGrowlithePose120
.4byte sGrowlithePose121
.4byte sGrowlithePose122
.4byte sGrowlithePose123
.4byte sGrowlithePose124
.4byte sGrowlithePose125
.4byte sGrowlithePose126
.4byte sGrowlithePose127
.4byte sGrowlithePose128
.4byte sGrowlithePose129
.4byte sGrowlithePose130
.4byte sGrowlithePose131
.4byte sGrowlithePose132
.4byte sGrowlithePose133
.4byte sGrowlithePose134
.4byte sGrowlithePose135
.4byte sGrowlithePose136
.4byte sGrowlithePose137
.4byte sGrowlithePose138
.4byte sGrowlithePose139
.4byte sGrowlithePose140
.4byte sGrowlithePose141
.4byte sGrowlithePose142
.4byte sGrowlithePose143
.4byte sGrowlithePose144
.4byte sGrowlithePose145
.4byte sGrowlithePose146
.4byte sGrowlithePose147
.4byte sGrowlithePose148
.4byte sGrowlithePose149
.4byte sGrowlithePose150
.4byte sGrowlithePose151
.4byte sGrowlithePose152
.4byte sGrowlithePose153
.4byte sGrowlithePose154
.4byte sGrowlithePose155
.4byte sGrowlithePose156
.4byte sGrowlithePose157
.4byte sGrowlithePose158
.4byte sGrowlithePose159
.4byte sGrowlithePose160
.4byte sGrowlithePose161
.4byte sGrowlithePose162
.4byte sGrowlithePose163
.4byte sGrowlithePose164
.4byte sGrowlithePose165
.4byte sGrowlithePose166
.4byte sGrowlithePose167
.4byte sGrowlithePose168
.4byte sGrowlithePose169
.4byte sGrowlithePose170
.4byte sGrowlithePose171
.4byte sGrowlithePose172
.4byte sGrowlithePose173
.4byte sGrowlithePose174
.4byte sGrowlithePose175
.4byte sGrowlithePose176
.4byte sGrowlithePose177
.4byte sGrowlithePose178
.4byte sGrowlithePose179
.4byte sGrowlithePose180
.4byte sGrowlithePose181
.4byte sGrowlithePose182
.4byte sGrowlithePose183
.4byte sGrowlithePose184
.4byte sGrowlithePose185
.4byte sGrowlithePose186
.4byte sGrowlithePose187
.4byte sGrowlithePose188
.4byte sGrowlithePose189
.4byte sGrowlithePose190
.4byte sGrowlithePose191
.4byte sGrowlithePose192
.4byte sGrowlithePose193
.4byte sGrowlithePose194
.4byte sGrowlithePose195
.4byte sGrowlithePose196
.4byte sGrowlithePose197
.4byte sGrowlithePose198
.4byte sGrowlithePose199
.4byte sGrowlithePose200
.4byte sGrowlithePose201
.4byte sGrowlithePose202
.4byte sGrowlithePose203
.4byte sGrowlithePose204
.4byte sGrowlithePose205
.4byte sGrowlithePose206
.4byte sGrowlithePose207
.4byte sGrowlithePose208
.4byte sGrowlithePose209
.4byte sGrowlithePose210
.4byte sGrowlithePose211
.4byte sGrowlithePose212
.4byte sGrowlithePose213
.4byte sGrowlithePose214
.4byte sGrowlithePose215
.4byte sGrowlithePose216
.4byte sGrowlithePose217
.4byte sGrowlithePose218
.4byte sGrowlithePose219
.4byte sGrowlithePose220
.4byte sGrowlithePose221
.4byte sGrowlithePose222
.4byte sGrowlithePose223
.4byte sGrowlithePose224
.4byte sGrowlithePose225
.4byte sGrowlithePose226
.4byte sGrowlithePose227
.4byte sGrowlithePose228
.4byte sGrowlithePose229
.4byte sGrowlithePose230
.4byte sGrowlithePose231
.4byte sGrowlithePose232
.4byte sGrowlithePose233
.4byte sGrowlithePose234
sAxPositionsGrowlithe:
.2byte    0,   -3, 	  -5,    2, 	   4,    2, 	   0,   -7
.2byte    0,   -2, 	  -5,    4, 	   3,    1, 	   0,   -6
.2byte    0,   -2, 	  -4,    1, 	   4,    4, 	  -1,   -6
.2byte    6,   -5, 	   7,    0, 	   2,    2, 	  -1,   -8
.2byte    6,   -4, 	   9,    1, 	  -1,    1, 	   0,   -7
.2byte    6,   -4, 	   6,    0, 	   3,    4, 	   0,   -7
.2byte   10,   -8, 	   7,   -3, 	   5,    1, 	  -1,   -8
.2byte   10,   -7, 	  10,   -2, 	   3,    1, 	  -1,   -7
.2byte   10,   -7, 	   1,   -2, 	   8,    1, 	  -1,   -7
.2byte    9,  -14, 	   1,   -4, 	   6,   -2, 	  -2,   -8
.2byte    9,  -13, 	   3,   -4, 	   5,    0, 	  -3,   -7
.2byte    9,  -13, 	  -1,   -3, 	   8,   -2, 	  -2,   -7
.2byte    0,  -16, 	   3,   -6, 	  -4,   -6, 	   0,  -11
.2byte    0,  -15, 	   2,   -9, 	  -4,   -3, 	   0,   -9
.2byte    0,  -15, 	   3,   -3, 	  -4,   -9, 	   0,   -9
.2byte  -10,  -14, 	  -2,   -4, 	  -7,   -2, 	   1,   -8
.2byte  -10,  -13, 	  -4,   -4, 	  -6,    0, 	   2,   -7
.2byte  -10,  -13, 	   0,   -3, 	  -9,   -2, 	   1,   -7
.2byte  -11,   -8, 	  -8,   -3, 	  -6,    1, 	   0,   -8
.2byte  -11,   -7, 	 -11,   -2, 	  -4,    1, 	   0,   -7
.2byte  -11,   -7, 	  -2,   -2, 	  -9,    1, 	   0,   -7
.2byte   -7,   -5, 	  -8,    0, 	  -3,    2, 	   0,   -8
.2byte   -7,   -4, 	 -10,    1, 	   0,    1, 	  -1,   -7
.2byte   -7,   -4, 	  -7,    0, 	  -4,    4, 	  -1,   -7
.2byte    0,   -3, 	  -5,    2, 	   4,    2, 	   0,   -7
.2byte    0,   -2, 	  -5,    4, 	   3,    1, 	   0,   -6
.2byte    0,   -2, 	  -4,    1, 	   4,    4, 	  -1,   -6
.2byte    0,   -9, 	  -7,   -9, 	   6,   -9, 	   0,  -11
.2byte    0,   -2, 	  -3,    0, 	   2,    0, 	   0,  -11
.2byte    6,   -5, 	   7,    0, 	   2,    2, 	  -1,   -8
.2byte    6,   -4, 	   9,    1, 	  -1,    1, 	   0,   -7
.2byte    6,   -4, 	   6,    0, 	   3,    4, 	   0,   -7
.2byte    8,   -8, 	  11,   -7, 	   5,   -5, 	   0,  -10
.2byte    9,   -3, 	   0,   -1, 	  -3,    0, 	   1,   -8
.2byte   10,   -8, 	   7,   -3, 	   5,    1, 	  -1,   -8
.2byte   10,   -7, 	  10,   -2, 	   3,    1, 	  -1,   -7
.2byte   10,   -7, 	   1,   -2, 	   8,    1, 	  -1,   -7
.2byte   10,  -10, 	  11,   -8, 	   9,   -6, 	  -1,   -9
.2byte   10,   -4, 	   1,   -1, 	  -2,    0, 	   0,  -10
.2byte    9,  -14, 	   1,   -4, 	   6,   -2, 	  -2,   -8
.2byte    9,  -13, 	   3,   -4, 	   5,    0, 	  -3,   -7
.2byte    9,  -13, 	  -1,   -3, 	   8,   -2, 	  -2,   -7
.2byte    7,  -16, 	   0,  -13, 	   7,  -10, 	  -3,  -11
.2byte   10,   -7, 	  -4,   -2, 	  -2,   -1, 	   1,  -10
.2byte    0,  -16, 	   3,   -6, 	  -4,   -6, 	   0,  -11
.2byte    0,  -15, 	   2,   -9, 	  -4,   -3, 	   0,   -9
.2byte    0,  -15, 	   3,   -3, 	  -4,   -9, 	   0,   -9
.2byte   -1,  -18, 	   6,  -13, 	  -7,  -13, 	  -1,  -10
.2byte   -1,  -14, 	   1,   -3, 	  -2,   -3, 	  -1,  -12
.2byte  -10,  -14, 	  -2,   -4, 	  -7,   -2, 	   1,   -8
.2byte  -10,  -13, 	  -4,   -4, 	  -6,    0, 	   2,   -7
.2byte  -10,  -13, 	   0,   -3, 	  -9,   -2, 	   1,   -7
.2byte   -8,  -16, 	  -1,  -13, 	  -8,  -10, 	   2,  -11
.2byte  -11,   -7, 	   3,   -2, 	   1,   -1, 	  -2,  -10
.2byte  -11,   -8, 	  -8,   -3, 	  -6,    1, 	   0,   -8
.2byte  -11,   -7, 	 -11,   -2, 	  -4,    1, 	   0,   -7
.2byte  -11,   -7, 	  -2,   -2, 	  -9,    1, 	   0,   -7
.2byte  -11,  -10, 	 -12,   -8, 	 -10,   -6, 	   0,   -9
.2byte  -11,   -4, 	  -2,   -1, 	   1,    0, 	  -1,  -10
.2byte   -7,   -5, 	  -8,    0, 	  -3,    2, 	   0,   -8
.2byte   -7,   -4, 	 -10,    1, 	   0,    1, 	  -1,   -7
.2byte   -7,   -4, 	  -7,    0, 	  -4,    4, 	  -1,   -7
.2byte   -9,   -8, 	 -12,   -7, 	  -6,   -5, 	  -1,  -10
.2byte  -10,   -3, 	  -1,   -1, 	   2,    0, 	  -2,   -8
.2byte    0,   -3, 	  -5,    2, 	   4,    2, 	   0,   -7
.2byte    0,   -2, 	  -5,    4, 	   3,    1, 	   0,   -6
.2byte    0,   -2, 	  -4,    1, 	   4,    4, 	  -1,   -6
.2byte    0,   -9, 	  -7,   -9, 	   6,   -9, 	   0,  -11
.2byte    0,   -2, 	  -3,    0, 	   2,    0, 	   0,  -11
.2byte    6,   -5, 	   7,    0, 	   2,    2, 	  -1,   -8
.2byte    6,   -4, 	   9,    1, 	  -1,    1, 	   0,   -7
.2byte    6,   -4, 	   6,    0, 	   3,    4, 	   0,   -7
.2byte    8,   -8, 	  11,   -7, 	   5,   -5, 	   0,  -10
.2byte    9,   -3, 	   0,   -1, 	  -3,    0, 	   1,   -8
.2byte   10,   -8, 	   7,   -3, 	   5,    1, 	  -1,   -8
.2byte   10,   -7, 	  10,   -2, 	   3,    1, 	  -1,   -7
.2byte   10,   -7, 	   1,   -2, 	   8,    1, 	  -1,   -7
.2byte   10,  -10, 	  11,   -8, 	   9,   -6, 	  -1,   -9
.2byte   10,   -4, 	   1,   -1, 	  -2,    0, 	   0,  -10
.2byte    9,  -14, 	   1,   -4, 	   6,   -2, 	  -2,   -8
.2byte    9,  -13, 	   3,   -4, 	   5,    0, 	  -3,   -7
.2byte    9,  -13, 	  -1,   -3, 	   8,   -2, 	  -2,   -7
.2byte    7,  -16, 	   0,  -13, 	   7,  -10, 	  -3,  -11
.2byte   10,   -7, 	  -4,   -2, 	  -2,   -1, 	   1,  -10
.2byte    0,  -16, 	   3,   -6, 	  -4,   -6, 	   0,  -11
.2byte    0,  -15, 	   2,   -9, 	  -4,   -3, 	   0,   -9
.2byte    0,  -15, 	   3,   -3, 	  -4,   -9, 	   0,   -9
.2byte   -1,  -18, 	   6,  -13, 	  -7,  -13, 	  -1,  -10
.2byte   -1,  -14, 	   1,   -3, 	  -2,   -3, 	  -1,  -12
.2byte  -10,  -14, 	  -2,   -4, 	  -7,   -2, 	   1,   -8
.2byte  -10,  -13, 	  -4,   -4, 	  -6,    0, 	   2,   -7
.2byte  -10,  -13, 	   0,   -3, 	  -9,   -2, 	   1,   -7
.2byte   -8,  -16, 	  -1,  -13, 	  -8,  -10, 	   2,  -11
.2byte  -11,   -7, 	   3,   -2, 	   1,   -1, 	  -2,  -10
.2byte  -11,   -8, 	  -8,   -3, 	  -6,    1, 	   0,   -8
.2byte  -11,   -7, 	 -11,   -2, 	  -4,    1, 	   0,   -7
.2byte  -11,   -7, 	  -2,   -2, 	  -9,    1, 	   0,   -7
.2byte  -11,  -10, 	 -12,   -8, 	 -10,   -6, 	   0,   -9
.2byte  -11,   -4, 	  -2,   -1, 	   1,    0, 	  -1,  -10
.2byte   -7,   -5, 	  -8,    0, 	  -3,    2, 	   0,   -8
.2byte   -7,   -4, 	 -10,    1, 	   0,    1, 	  -1,   -7
.2byte   -7,   -4, 	  -7,    0, 	  -4,    4, 	  -1,   -7
.2byte   -9,   -8, 	 -12,   -7, 	  -6,   -5, 	  -1,  -10
.2byte  -10,   -3, 	  -1,   -1, 	   2,    0, 	  -2,   -8
.2byte    0,   -3, 	  -5,    2, 	   4,    2, 	   0,   -7
.2byte    0,   -2, 	  -5,    4, 	   3,    1, 	   0,   -6
.2byte    0,   -2, 	  -4,    1, 	   4,    4, 	  -1,   -6
.2byte    0,   -2, 	  -7,    1, 	   6,    1, 	   0,  -10
.2byte    6,   -5, 	   7,    0, 	   2,    2, 	  -1,   -8
.2byte    6,   -4, 	   9,    1, 	  -1,    1, 	   0,   -7
.2byte    6,   -4, 	   6,    0, 	   3,    4, 	   0,   -7
.2byte    9,   -4, 	   9,   -1, 	   1,    2, 	   0,   -7
.2byte   10,   -8, 	   7,   -3, 	   5,    1, 	  -1,   -8
.2byte   10,   -7, 	  10,   -2, 	   3,    1, 	  -1,   -7
.2byte   10,   -7, 	   1,   -2, 	   8,    1, 	  -1,   -7
.2byte   11,   -6, 	   6,   -3, 	   4,    1, 	   0,   -7
.2byte    9,  -14, 	   1,   -4, 	   6,   -2, 	  -2,   -8
.2byte    9,  -13, 	   3,   -4, 	   5,    0, 	  -3,   -7
.2byte    9,  -13, 	  -1,   -3, 	   8,   -2, 	  -2,   -7
.2byte   10,  -11, 	   0,   -4, 	   5,   -2, 	   0,   -8
.2byte    0,  -16, 	   3,   -6, 	  -4,   -6, 	   0,  -11
.2byte    0,  -15, 	   2,   -9, 	  -4,   -3, 	   0,   -9
.2byte    0,  -15, 	   3,   -3, 	  -4,   -9, 	   0,   -9
.2byte   -1,  -14, 	   4,  -14, 	  -5,  -14, 	  -1,  -10
.2byte  -10,  -14, 	  -2,   -4, 	  -7,   -2, 	   1,   -8
.2byte  -10,  -13, 	  -4,   -4, 	  -6,    0, 	   2,   -7
.2byte  -10,  -13, 	   0,   -3, 	  -9,   -2, 	   1,   -7
.2byte  -11,  -11, 	  -1,   -4, 	  -6,   -2, 	  -1,   -8
.2byte  -11,   -8, 	  -8,   -3, 	  -6,    1, 	   0,   -8
.2byte  -11,   -7, 	 -11,   -2, 	  -4,    1, 	   0,   -7
.2byte  -11,   -7, 	  -2,   -2, 	  -9,    1, 	   0,   -7
.2byte  -12,   -6, 	  -7,   -3, 	  -5,    1, 	  -1,   -7
.2byte   -7,   -5, 	  -8,    0, 	  -3,    2, 	   0,   -8
.2byte   -7,   -4, 	 -10,    1, 	   0,    1, 	  -1,   -7
.2byte   -7,   -4, 	  -7,    0, 	  -4,    4, 	  -1,   -7
.2byte  -10,   -4, 	 -10,   -1, 	  -2,    2, 	  -1,   -7
.2byte    0,   -3, 	  -5,    2, 	   4,    2, 	   0,   -7
.2byte    0,   -9, 	  -7,   -9, 	   6,   -9, 	   0,  -11
.2byte    0,   -8, 	  -4,    1, 	   3,    1, 	   0,   -7
.2byte    6,   -5, 	   7,    0, 	   2,    2, 	  -1,   -8
.2byte    7,   -8, 	  10,   -7, 	   4,   -5, 	  -1,  -10
.2byte    5,   -9, 	   7,   -1, 	   1,    1, 	  -2,   -7
.2byte   10,   -8, 	   7,   -3, 	   5,    1, 	  -1,   -8
.2byte   10,  -10, 	  11,   -8, 	   9,   -6, 	  -1,   -9
.2byte    8,  -10, 	   6,   -3, 	   4,    1, 	  -1,   -7
.2byte    9,  -14, 	   1,   -4, 	   6,   -2, 	  -2,   -8
.2byte    7,  -16, 	   0,  -13, 	   7,  -10, 	  -3,  -11
.2byte    6,  -14, 	  -1,   -2, 	   4,   -1, 	  -2,   -8
.2byte    0,  -16, 	   3,   -6, 	  -4,   -6, 	   0,  -11
.2byte   -1,  -18, 	   6,  -13, 	  -7,  -13, 	  -1,  -10
.2byte   -1,  -19, 	   3,   -6, 	  -4,   -6, 	  -1,  -10
.2byte  -10,  -14, 	  -2,   -4, 	  -7,   -2, 	   1,   -8
.2byte   -8,  -16, 	  -1,  -13, 	  -8,  -10, 	   2,  -11
.2byte   -7,  -14, 	   0,   -2, 	  -5,   -1, 	   1,   -8
.2byte  -11,   -8, 	  -8,   -3, 	  -6,    1, 	   0,   -8
.2byte  -11,  -10, 	 -12,   -8, 	 -10,   -6, 	   0,   -9
.2byte   -7,  -10, 	  -5,   -3, 	  -3,    1, 	   2,   -7
.2byte   -7,   -5, 	  -8,    0, 	  -3,    2, 	   0,   -8
.2byte   -8,   -8, 	 -11,   -7, 	  -5,   -5, 	   0,  -10
.2byte   -6,   -9, 	  -8,   -1, 	  -2,    1, 	   1,   -7
.2byte   -5,    0, 	 -10,    0, 	  -3,    2, 	   0,   -7
.2byte   -5,    1, 	 -10,    0, 	  -3,    2, 	   0,   -6
.2byte    0,    0, 	  -7,    2, 	   6,    2, 	   0,   -8
.2byte    6,   -2, 	  13,   -5, 	   2,    0, 	  -1,   -8
.2byte    8,   -4, 	  12,   -6, 	  11,   -2, 	  -4,   -7
.2byte    7,   -9, 	   3,  -11, 	   9,   -8, 	  -4,   -5
.2byte    0,  -10, 	   6,  -12, 	  -7,  -12, 	   0,   -5
.2byte   -8,   -9, 	  -4,  -11, 	 -10,   -8, 	   3,   -5
.2byte   -9,   -4, 	 -13,   -6, 	 -12,   -2, 	   3,   -7
.2byte   -7,   -2, 	 -14,   -5, 	  -3,    0, 	   0,   -8
.2byte    0,   -8, 	  -4,    1, 	   3,    1, 	   0,   -7
.2byte    5,   -9, 	   7,   -1, 	   1,    1, 	  -2,   -7
.2byte    8,  -10, 	   6,   -3, 	   4,    1, 	  -1,   -7
.2byte    6,  -14, 	  -1,   -2, 	   4,   -1, 	  -2,   -8
.2byte   -1,  -19, 	   3,   -6, 	  -4,   -6, 	  -1,  -10
.2byte   -7,  -14, 	   0,   -2, 	  -5,   -1, 	   1,   -8
.2byte   -7,  -10, 	  -5,   -3, 	  -3,    1, 	   2,   -7
.2byte   -6,   -9, 	  -8,   -1, 	  -2,    1, 	   1,   -7
.2byte    0,   -2, 	  -3,    0, 	   2,    0, 	   0,  -11
.2byte  -10,   -3, 	  -1,   -1, 	   2,    0, 	  -2,   -8
.2byte  -11,   -4, 	  -2,   -1, 	   1,    0, 	  -1,  -10
.2byte  -10,   -7, 	   4,   -2, 	   2,   -1, 	  -1,  -10
.2byte   -1,  -13, 	   1,   -2, 	  -2,   -2, 	  -1,  -11
.2byte    9,   -7, 	  -5,   -2, 	  -3,   -1, 	   0,  -10
.2byte   10,   -4, 	   1,   -1, 	  -2,    0, 	   0,  -10
.2byte    9,   -3, 	   0,   -1, 	  -3,    0, 	   1,   -8
.2byte    0,   -2, 	  -7,    1, 	   6,    1, 	   0,  -10
.2byte    9,   -4, 	   9,   -1, 	   1,    2, 	   0,   -7
.2byte   11,   -6, 	   6,   -3, 	   4,    1, 	   0,   -7
.2byte   10,  -11, 	   0,   -4, 	   5,   -2, 	   0,   -8
.2byte   -1,  -14, 	   4,  -14, 	  -5,  -14, 	  -1,  -10
.2byte  -11,  -11, 	  -1,   -4, 	  -6,   -2, 	  -1,   -8
.2byte  -12,   -6, 	  -7,   -3, 	  -5,    1, 	  -1,   -7
.2byte  -10,   -4, 	 -10,   -1, 	  -2,    2, 	  -1,   -7
.2byte    0,   -3, 	  -5,    2, 	   4,    2, 	   0,   -7
.2byte    0,   -9, 	  -7,   -9, 	   6,   -9, 	   0,  -11
.2byte    0,   -2, 	  -3,    0, 	   2,    0, 	   0,  -11
.2byte    6,   -5, 	   7,    0, 	   2,    2, 	  -1,   -8
.2byte    8,   -8, 	  11,   -7, 	   5,   -5, 	   0,  -10
.2byte    9,   -3, 	   0,   -1, 	  -3,    0, 	   1,   -8
.2byte   10,   -8, 	   7,   -3, 	   5,    1, 	  -1,   -8
.2byte   10,  -10, 	  11,   -8, 	   9,   -6, 	  -1,   -9
.2byte   10,   -4, 	   1,   -1, 	  -2,    0, 	   0,  -10
.2byte    9,  -14, 	   1,   -4, 	   6,   -2, 	  -2,   -8
.2byte    7,  -16, 	   0,  -13, 	   7,  -10, 	  -3,  -11
.2byte   10,   -7, 	  -4,   -2, 	  -2,   -1, 	   1,  -10
.2byte    0,  -16, 	   3,   -6, 	  -4,   -6, 	   0,  -11
.2byte   -1,  -18, 	   6,  -13, 	  -7,  -13, 	  -1,  -10
.2byte   -1,  -14, 	   1,   -3, 	  -2,   -3, 	  -1,  -12
.2byte  -10,  -14, 	  -2,   -4, 	  -7,   -2, 	   1,   -8
.2byte   -8,  -16, 	  -1,  -13, 	  -8,  -10, 	   2,  -11
.2byte  -11,   -7, 	   3,   -2, 	   1,   -1, 	  -2,  -10
.2byte  -11,   -8, 	  -8,   -3, 	  -6,    1, 	   0,   -8
.2byte  -11,  -10, 	 -12,   -8, 	 -10,   -6, 	   0,   -9
.2byte  -11,   -4, 	  -2,   -1, 	   1,    0, 	  -1,  -10
.2byte   -7,   -5, 	  -8,    0, 	  -3,    2, 	   0,   -8
.2byte   -9,   -8, 	 -12,   -7, 	  -6,   -5, 	  -1,  -10
.2byte  -10,   -3, 	  -1,   -1, 	   2,    0, 	  -2,   -8
.2byte    0,   -8, 	  -4,    1, 	   3,    1, 	   0,   -7
.2byte   -6,   -9, 	  -8,   -1, 	  -2,    1, 	   1,   -7
.2byte   -9,  -10, 	  -7,   -3, 	  -5,    1, 	   0,   -7
.2byte   -8,  -14, 	  -1,   -2, 	  -6,   -1, 	   0,   -8
.2byte   -1,  -18, 	   3,   -5, 	  -4,   -5, 	  -1,   -9
.2byte    7,  -14, 	   0,   -2, 	   5,   -1, 	  -1,   -8
.2byte    8,  -10, 	   6,   -3, 	   4,    1, 	  -1,   -7
.2byte    5,   -9, 	   7,   -1, 	   1,    1, 	  -2,   -7
.2byte    0,   -3, 	  -5,    2, 	   4,    2, 	   0,   -7
.2byte   -7,   -5, 	  -8,    0, 	  -3,    2, 	   0,   -8
.2byte  -11,   -8, 	  -8,   -3, 	  -6,    1, 	   0,   -8
.2byte  -10,  -14, 	  -2,   -4, 	  -7,   -2, 	   1,   -8
.2byte    0,  -16, 	   3,   -6, 	  -4,   -6, 	   0,  -11
.2byte    9,  -14, 	   1,   -4, 	   6,   -2, 	  -2,   -8
.2byte   10,   -8, 	   7,   -3, 	   5,    1, 	  -1,   -8
.2byte    6,   -5, 	   7,    0, 	   2,    2, 	  -1,   -8
sGrowlitheAnimTable1:
.4byte sGrowlitheAnims_1_1
.4byte sGrowlitheAnims_1_2
.4byte sGrowlitheAnims_1_3
.4byte sGrowlitheAnims_1_4
.4byte sGrowlitheAnims_1_5
.4byte sGrowlitheAnims_1_6
.4byte sGrowlitheAnims_1_7
.4byte sGrowlitheAnims_1_8
sGrowlitheAnimTable2:
.4byte sGrowlitheAnims_2_1
.4byte sGrowlitheAnims_2_2
.4byte sGrowlitheAnims_2_3
.4byte sGrowlitheAnims_2_4
.4byte sGrowlitheAnims_2_5
.4byte sGrowlitheAnims_2_6
.4byte sGrowlitheAnims_2_7
.4byte sGrowlitheAnims_2_8
sGrowlitheAnimTable3:
.4byte sGrowlitheAnims_3_1
.4byte sGrowlitheAnims_3_2
.4byte sGrowlitheAnims_3_3
.4byte sGrowlitheAnims_3_4
.4byte sGrowlitheAnims_3_5
.4byte sGrowlitheAnims_3_6
.4byte sGrowlitheAnims_3_7
.4byte sGrowlitheAnims_3_8
sGrowlitheAnimTable4:
.4byte sGrowlitheAnims_4_1
.4byte sGrowlitheAnims_4_2
.4byte sGrowlitheAnims_4_3
.4byte sGrowlitheAnims_4_4
.4byte sGrowlitheAnims_4_5
.4byte sGrowlitheAnims_4_6
.4byte sGrowlitheAnims_4_7
.4byte sGrowlitheAnims_4_8
sGrowlitheAnimTable5:
.4byte sGrowlitheAnims_5_1
.4byte sGrowlitheAnims_5_2
.4byte sGrowlitheAnims_5_3
.4byte sGrowlitheAnims_5_4
.4byte sGrowlitheAnims_5_5
.4byte sGrowlitheAnims_5_6
.4byte sGrowlitheAnims_5_7
.4byte sGrowlitheAnims_5_8
sGrowlitheAnimTable6:
.4byte sGrowlitheAnims_6_1
.4byte sGrowlitheAnims_6_1
.4byte sGrowlitheAnims_6_1
.4byte sGrowlitheAnims_6_1
.4byte sGrowlitheAnims_6_1
.4byte sGrowlitheAnims_6_1
.4byte sGrowlitheAnims_6_1
.4byte sGrowlitheAnims_6_1
sGrowlitheAnimTable7:
.4byte sGrowlitheAnims_7_1
.4byte sGrowlitheAnims_7_2
.4byte sGrowlitheAnims_7_3
.4byte sGrowlitheAnims_7_4
.4byte sGrowlitheAnims_7_5
.4byte sGrowlitheAnims_7_6
.4byte sGrowlitheAnims_7_7
.4byte sGrowlitheAnims_7_8
sGrowlitheAnimTable8:
.4byte sGrowlitheAnims_8_1
.4byte sGrowlitheAnims_8_2
.4byte sGrowlitheAnims_8_3
.4byte sGrowlitheAnims_8_4
.4byte sGrowlitheAnims_8_5
.4byte sGrowlitheAnims_8_6
.4byte sGrowlitheAnims_8_7
.4byte sGrowlitheAnims_8_8
sGrowlitheAnimTable9:
.4byte sGrowlitheAnims_9_1
.4byte sGrowlitheAnims_9_2
.4byte sGrowlitheAnims_9_3
.4byte sGrowlitheAnims_9_4
.4byte sGrowlitheAnims_9_5
.4byte sGrowlitheAnims_9_6
.4byte sGrowlitheAnims_9_7
.4byte sGrowlitheAnims_9_8
sGrowlitheAnimTable10:
.4byte sGrowlitheAnims_10_1
.4byte sGrowlitheAnims_10_2
.4byte sGrowlitheAnims_10_3
.4byte sGrowlitheAnims_10_4
.4byte sGrowlitheAnims_10_5
.4byte sGrowlitheAnims_10_6
.4byte sGrowlitheAnims_10_7
.4byte sGrowlitheAnims_10_8
sGrowlitheAnimTable11:
.4byte sGrowlitheAnims_11_1
.4byte sGrowlitheAnims_11_2
.4byte sGrowlitheAnims_11_3
.4byte sGrowlitheAnims_11_4
.4byte sGrowlitheAnims_11_5
.4byte sGrowlitheAnims_11_6
.4byte sGrowlitheAnims_11_7
.4byte sGrowlitheAnims_11_8
sGrowlitheAnimTable12:
.4byte sGrowlitheAnims_12_1
.4byte sGrowlitheAnims_12_2
.4byte sGrowlitheAnims_12_3
.4byte sGrowlitheAnims_12_4
.4byte sGrowlitheAnims_12_5
.4byte sGrowlitheAnims_12_6
.4byte sGrowlitheAnims_12_7
.4byte sGrowlitheAnims_12_8
sGrowlitheAnimTable13:
.4byte sGrowlitheAnims_13_1
.4byte sGrowlitheAnims_13_2
.4byte sGrowlitheAnims_13_3
.4byte sGrowlitheAnims_13_4
.4byte sGrowlitheAnims_13_5
.4byte sGrowlitheAnims_13_6
.4byte sGrowlitheAnims_13_7
.4byte sGrowlitheAnims_13_8
sAxAnimationsGrowlithe:
.4byte sGrowlitheAnimTable1
.4byte sGrowlitheAnimTable2
.4byte sGrowlitheAnimTable3
.4byte sGrowlitheAnimTable4
.4byte sGrowlitheAnimTable5
.4byte sGrowlitheAnimTable6
.4byte sGrowlitheAnimTable7
.4byte sGrowlitheAnimTable8
.4byte sGrowlitheAnimTable9
.4byte sGrowlitheAnimTable10
.4byte sGrowlitheAnimTable11
.4byte sGrowlitheAnimTable12
.4byte sGrowlitheAnimTable13
sAxSpritesGrowlithe:
.4byte sGrowlitheSprites1
.4byte sGrowlitheSprites2
.4byte sGrowlitheSprites3
.4byte sGrowlitheSprites4
.4byte sGrowlitheSprites5
.4byte sGrowlitheSprites6
.4byte sGrowlitheSprites7
.4byte sGrowlitheSprites8
.4byte sGrowlitheSprites9
.4byte sGrowlitheSprites10
.4byte sGrowlitheSprites11
.4byte sGrowlitheSprites12
.4byte sGrowlitheSprites13
.4byte sGrowlitheSprites14
.4byte sGrowlitheSprites15
.4byte sGrowlitheSprites16
.4byte sGrowlitheSprites17
.4byte sGrowlitheSprites18
.4byte sGrowlitheSprites19
.4byte sGrowlitheSprites20
.4byte sGrowlitheSprites21
.4byte sGrowlitheSprites22
.4byte sGrowlitheSprites23
.4byte sGrowlitheSprites24
.4byte sGrowlitheSprites25
.4byte sGrowlitheSprites26
.4byte sGrowlitheSprites27
.4byte sGrowlitheSprites28
.4byte sGrowlitheSprites29
.4byte sGrowlitheSprites30
.4byte sGrowlitheSprites31
.4byte sGrowlitheSprites32
.4byte sGrowlitheSprites33
.4byte sGrowlitheSprites34
.4byte sGrowlitheSprites35
.4byte sGrowlitheSprites36
.4byte sGrowlitheSprites37
.4byte sGrowlitheSprites38
.4byte sGrowlitheSprites39
.4byte sGrowlitheSprites40
.4byte sGrowlitheSprites41
.4byte sGrowlitheSprites42
sAxMainGrowlithe:
ax_main sAxPosesGrowlithe, sAxAnimationsGrowlithe, 13, sAxSpritesGrowlithe, sAxPositionsGrowlithe
