.global gAxGulpin
gAxGulpin:
ax_siro sAxMainGulpin
sGulpinPose1:
ax_pose 0, 0x01ee, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose2:
ax_pose 1, 0x01ee, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose3:
ax_pose 2, 0x01ee, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose4:
ax_pose 3, 0x01ee, 0x90ec, 0xac00
ax_pose_terminator
sGulpinPose5:
ax_pose 4, 0x01ee, 0x90ec, 0xac00
ax_pose_terminator
sGulpinPose6:
ax_pose 5, 0x01ee, 0x90ec, 0xac00
ax_pose_terminator
sGulpinPose7:
ax_pose 6, 0x01ee, 0x90ed, 0xac00
ax_pose_terminator
sGulpinPose8:
ax_pose 7, 0x01ee, 0x90ed, 0xac00
ax_pose_terminator
sGulpinPose9:
ax_pose 8, 0x01ee, 0x90ed, 0xac00
ax_pose_terminator
sGulpinPose10:
ax_pose 9, 0x01ee, 0x90ec, 0xac00
ax_pose_terminator
sGulpinPose11:
ax_pose 10, 0x01ee, 0x90ec, 0xac00
ax_pose_terminator
sGulpinPose12:
ax_pose 11, 0x41f3, 0x90ec, 0xac00
ax_pose_terminator
sGulpinPose13:
ax_pose 12, 0x01ee, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose14:
ax_pose 13, 0x01ee, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose15:
ax_pose 14, 0x01ee, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose16:
ax_pose 9, 0x01ee, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose17:
ax_pose 10, 0x01ee, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose18:
ax_pose 11, 0x41f3, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose19:
ax_pose 6, 0x01ee, 0x80f3, 0xac00
ax_pose_terminator
sGulpinPose20:
ax_pose 7, 0x01ee, 0x80f3, 0xac00
ax_pose_terminator
sGulpinPose21:
ax_pose 8, 0x01ee, 0x80f3, 0xac00
ax_pose_terminator
sGulpinPose22:
ax_pose 3, 0x01ee, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose23:
ax_pose 4, 0x01ee, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose24:
ax_pose 5, 0x01ee, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose25:
ax_pose 0, 0x01ee, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose26:
ax_pose 1, 0x01ee, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose27:
ax_pose 2, 0x01ee, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose28:
ax_pose 15, 0x01ee, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose29:
ax_pose 16, 0x81ed, 0x80f7, 0xac00
ax_pose 17, 0x01fd, 0x0107, 0xac08
ax_pose_terminator
sGulpinPose30:
ax_pose 3, 0x01ee, 0x90ec, 0xac00
ax_pose_terminator
sGulpinPose31:
ax_pose 4, 0x01ee, 0x90ec, 0xac00
ax_pose_terminator
sGulpinPose32:
ax_pose 5, 0x01ee, 0x90ec, 0xac00
ax_pose_terminator
sGulpinPose33:
ax_pose 18, 0x01ee, 0x90ec, 0xac00
ax_pose_terminator
sGulpinPose34:
ax_pose 19, 0x01ee, 0x90ec, 0xac00
ax_pose_terminator
sGulpinPose35:
ax_pose 6, 0x01ee, 0x90ed, 0xac00
ax_pose_terminator
sGulpinPose36:
ax_pose 7, 0x01ee, 0x90ed, 0xac00
ax_pose_terminator
sGulpinPose37:
ax_pose 8, 0x01ee, 0x90ed, 0xac00
ax_pose_terminator
sGulpinPose38:
ax_pose 20, 0x01ee, 0x90ee, 0xac00
ax_pose_terminator
sGulpinPose39:
ax_pose 21, 0x81ec, 0x90fa, 0xac00
ax_pose 22, 0x01fc, 0x10f2, 0xac08
ax_pose_terminator
sGulpinPose40:
ax_pose 9, 0x01ee, 0x90ec, 0xac00
ax_pose_terminator
sGulpinPose41:
ax_pose 10, 0x01ee, 0x90ec, 0xac00
ax_pose_terminator
sGulpinPose42:
ax_pose 11, 0x41f3, 0x90ec, 0xac00
ax_pose_terminator
sGulpinPose43:
ax_pose 23, 0x41f3, 0x90ec, 0xac00
ax_pose_terminator
sGulpinPose44:
ax_pose 24, 0x01ee, 0x90ec, 0xac00
ax_pose_terminator
sGulpinPose45:
ax_pose 12, 0x01ee, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose46:
ax_pose 13, 0x01ee, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose47:
ax_pose 14, 0x01ee, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose48:
ax_pose 25, 0x01ee, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose49:
ax_pose 26, 0x01f0, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose50:
ax_pose 9, 0x01ee, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose51:
ax_pose 10, 0x01ee, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose52:
ax_pose 11, 0x41f3, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose53:
ax_pose 23, 0x41f3, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose54:
ax_pose 24, 0x01ee, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose55:
ax_pose 6, 0x01ee, 0x80f3, 0xac00
ax_pose_terminator
sGulpinPose56:
ax_pose 7, 0x01ee, 0x80f3, 0xac00
ax_pose_terminator
sGulpinPose57:
ax_pose 8, 0x01ee, 0x80f3, 0xac00
ax_pose_terminator
sGulpinPose58:
ax_pose 20, 0x01ee, 0x80f2, 0xac00
ax_pose_terminator
sGulpinPose59:
ax_pose 21, 0x81ec, 0x80f6, 0xac00
ax_pose 22, 0x01fc, 0x0106, 0xac08
ax_pose_terminator
sGulpinPose60:
ax_pose 3, 0x01ee, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose61:
ax_pose 4, 0x01ee, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose62:
ax_pose 5, 0x01ee, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose63:
ax_pose 18, 0x01ee, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose64:
ax_pose 19, 0x01ee, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose65:
ax_pose 0, 0x01ee, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose66:
ax_pose 1, 0x01ee, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose67:
ax_pose 2, 0x01ee, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose68:
ax_pose 15, 0x01ee, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose69:
ax_pose 16, 0x81ed, 0x80f7, 0xac00
ax_pose 17, 0x01fd, 0x0107, 0xac08
ax_pose_terminator
sGulpinPose70:
ax_pose 3, 0x01ee, 0x90ec, 0xac00
ax_pose_terminator
sGulpinPose71:
ax_pose 4, 0x01ee, 0x90ec, 0xac00
ax_pose_terminator
sGulpinPose72:
ax_pose 5, 0x01ee, 0x90ec, 0xac00
ax_pose_terminator
sGulpinPose73:
ax_pose 18, 0x01ee, 0x90ec, 0xac00
ax_pose_terminator
sGulpinPose74:
ax_pose 19, 0x01ee, 0x90ec, 0xac00
ax_pose_terminator
sGulpinPose75:
ax_pose 6, 0x01ee, 0x90ed, 0xac00
ax_pose_terminator
sGulpinPose76:
ax_pose 7, 0x01ee, 0x90ed, 0xac00
ax_pose_terminator
sGulpinPose77:
ax_pose 8, 0x01ee, 0x90ed, 0xac00
ax_pose_terminator
sGulpinPose78:
ax_pose 20, 0x01ee, 0x90ee, 0xac00
ax_pose_terminator
sGulpinPose79:
ax_pose 21, 0x81ec, 0x90fa, 0xac00
ax_pose 22, 0x01fc, 0x10f2, 0xac08
ax_pose_terminator
sGulpinPose80:
ax_pose 9, 0x01ee, 0x90ec, 0xac00
ax_pose_terminator
sGulpinPose81:
ax_pose 10, 0x01ee, 0x90ec, 0xac00
ax_pose_terminator
sGulpinPose82:
ax_pose 11, 0x41f3, 0x90ec, 0xac00
ax_pose_terminator
sGulpinPose83:
ax_pose 23, 0x41f3, 0x90ec, 0xac00
ax_pose_terminator
sGulpinPose84:
ax_pose 24, 0x01ee, 0x90ec, 0xac00
ax_pose_terminator
sGulpinPose85:
ax_pose 12, 0x01ee, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose86:
ax_pose 13, 0x01ee, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose87:
ax_pose 14, 0x01ee, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose88:
ax_pose 25, 0x01ee, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose89:
ax_pose 26, 0x01f0, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose90:
ax_pose 9, 0x01ee, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose91:
ax_pose 10, 0x01ee, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose92:
ax_pose 11, 0x41f3, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose93:
ax_pose 23, 0x41f3, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose94:
ax_pose 24, 0x01ee, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose95:
ax_pose 6, 0x01ee, 0x80f3, 0xac00
ax_pose_terminator
sGulpinPose96:
ax_pose 7, 0x01ee, 0x80f3, 0xac00
ax_pose_terminator
sGulpinPose97:
ax_pose 8, 0x01ee, 0x80f3, 0xac00
ax_pose_terminator
sGulpinPose98:
ax_pose 20, 0x01ee, 0x80f2, 0xac00
ax_pose_terminator
sGulpinPose99:
ax_pose 21, 0x81ec, 0x80f6, 0xac00
ax_pose 22, 0x01fc, 0x0106, 0xac08
ax_pose_terminator
sGulpinPose100:
ax_pose 3, 0x01ee, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose101:
ax_pose 4, 0x01ee, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose102:
ax_pose 5, 0x01ee, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose103:
ax_pose 18, 0x01ee, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose104:
ax_pose 19, 0x01ee, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose105:
ax_pose 0, 0x01ee, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose106:
ax_pose 27, 0x01ee, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose107:
ax_pose 28, 0x01e9, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose108:
ax_pose 3, 0x01ee, 0x90ec, 0xac00
ax_pose_terminator
sGulpinPose109:
ax_pose 29, 0x01ee, 0x90ed, 0xac00
ax_pose_terminator
sGulpinPose110:
ax_pose 30, 0x01ed, 0x90ec, 0xac00
ax_pose_terminator
sGulpinPose111:
ax_pose 6, 0x01ee, 0x90ed, 0xac00
ax_pose_terminator
sGulpinPose112:
ax_pose 31, 0x01ee, 0x90ec, 0xac00
ax_pose_terminator
sGulpinPose113:
ax_pose 32, 0x01eb, 0x90ec, 0xac00
ax_pose_terminator
sGulpinPose114:
ax_pose 9, 0x01ee, 0x90ec, 0xac00
ax_pose_terminator
sGulpinPose115:
ax_pose 33, 0x01ef, 0x90ec, 0xac00
ax_pose_terminator
sGulpinPose116:
ax_pose 34, 0x01ec, 0x90ec, 0xac00
ax_pose_terminator
sGulpinPose117:
ax_pose 12, 0x01ee, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose118:
ax_pose 35, 0x81f0, 0x80f6, 0xac00
ax_pose 36, 0x81f0, 0x0106, 0xac08
ax_pose_terminator
sGulpinPose119:
ax_pose 37, 0x01ee, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose120:
ax_pose 9, 0x01ee, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose121:
ax_pose 33, 0x01ef, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose122:
ax_pose 34, 0x01ec, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose123:
ax_pose 6, 0x01ee, 0x80f3, 0xac00
ax_pose_terminator
sGulpinPose124:
ax_pose 31, 0x01ee, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose125:
ax_pose 32, 0x01eb, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose126:
ax_pose 3, 0x01ee, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose127:
ax_pose 29, 0x01ee, 0x80f3, 0xac00
ax_pose_terminator
sGulpinPose128:
ax_pose 30, 0x01ed, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose129:
ax_pose 0, 0x01ee, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose130:
ax_pose 28, 0x01e9, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose131:
ax_pose 38, 0x01e7, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose132:
ax_pose 3, 0x01ee, 0x90ec, 0xac00
ax_pose_terminator
sGulpinPose133:
ax_pose 30, 0x01ed, 0x90ec, 0xac00
ax_pose_terminator
sGulpinPose134:
ax_pose 39, 0x01ed, 0x90ec, 0xac00
ax_pose_terminator
sGulpinPose135:
ax_pose 6, 0x01ee, 0x90ed, 0xac00
ax_pose_terminator
sGulpinPose136:
ax_pose 32, 0x01eb, 0x90ec, 0xac00
ax_pose_terminator
sGulpinPose137:
ax_pose 40, 0x01ea, 0x90ee, 0xac00
ax_pose_terminator
sGulpinPose138:
ax_pose 9, 0x01ee, 0x90ec, 0xac00
ax_pose_terminator
sGulpinPose139:
ax_pose 34, 0x01ec, 0x90ec, 0xac00
ax_pose_terminator
sGulpinPose140:
ax_pose 41, 0x01ed, 0x90eb, 0xac00
ax_pose_terminator
sGulpinPose141:
ax_pose 12, 0x01ee, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose142:
ax_pose 37, 0x01ee, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose143:
ax_pose 42, 0x01ed, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose144:
ax_pose 9, 0x01ee, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose145:
ax_pose 34, 0x01ec, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose146:
ax_pose 41, 0x01ed, 0x80f5, 0xac00
ax_pose_terminator
sGulpinPose147:
ax_pose 6, 0x01ee, 0x80f3, 0xac00
ax_pose_terminator
sGulpinPose148:
ax_pose 32, 0x01eb, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose149:
ax_pose 40, 0x01ea, 0x80f2, 0xac00
ax_pose_terminator
sGulpinPose150:
ax_pose 3, 0x01ee, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose151:
ax_pose 30, 0x01ed, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose152:
ax_pose 39, 0x01ed, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose153:
ax_pose 43, 0x01ee, 0x80f3, 0xac00
ax_pose_terminator
sGulpinPose154:
ax_pose 44, 0x01ee, 0x80f3, 0xac00
ax_pose_terminator
sGulpinPose155:
ax_pose 45, 0x01e6, 0x80f0, 0xac00
ax_pose_terminator
sGulpinPose156:
ax_pose 46, 0x01e4, 0x90ed, 0xac00
ax_pose_terminator
sGulpinPose157:
ax_pose 47, 0x01e9, 0x90ec, 0xac00
ax_pose_terminator
sGulpinPose158:
ax_pose 48, 0x01e9, 0x90ec, 0xac00
ax_pose_terminator
sGulpinPose159:
ax_pose 49, 0x01e9, 0x80f0, 0xac00
ax_pose_terminator
sGulpinPose160:
ax_pose 48, 0x01e9, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose161:
ax_pose 47, 0x01e9, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose162:
ax_pose 46, 0x01e4, 0x80f3, 0xac00
ax_pose_terminator
sGulpinPose163:
ax_pose 0, 0x01ee, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose164:
ax_pose 1, 0x01ee, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose165:
ax_pose 2, 0x01ee, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose166:
ax_pose 3, 0x01ee, 0x90ec, 0xac00
ax_pose_terminator
sGulpinPose167:
ax_pose 4, 0x01ee, 0x90ec, 0xac00
ax_pose_terminator
sGulpinPose168:
ax_pose 5, 0x01ee, 0x90ec, 0xac00
ax_pose_terminator
sGulpinPose169:
ax_pose 6, 0x01ee, 0x90ed, 0xac00
ax_pose_terminator
sGulpinPose170:
ax_pose 7, 0x01ee, 0x90ed, 0xac00
ax_pose_terminator
sGulpinPose171:
ax_pose 8, 0x01ee, 0x90ed, 0xac00
ax_pose_terminator
sGulpinPose172:
ax_pose 9, 0x01ee, 0x90ec, 0xac00
ax_pose_terminator
sGulpinPose173:
ax_pose 10, 0x01ee, 0x90ec, 0xac00
ax_pose_terminator
sGulpinPose174:
ax_pose 11, 0x41f3, 0x90ec, 0xac00
ax_pose_terminator
sGulpinPose175:
ax_pose 12, 0x01ee, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose176:
ax_pose 13, 0x01ee, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose177:
ax_pose 14, 0x01ee, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose178:
ax_pose 9, 0x01ee, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose179:
ax_pose 10, 0x01ee, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose180:
ax_pose 11, 0x41f3, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose181:
ax_pose 6, 0x01ee, 0x80f3, 0xac00
ax_pose_terminator
sGulpinPose182:
ax_pose 7, 0x01ee, 0x80f3, 0xac00
ax_pose_terminator
sGulpinPose183:
ax_pose 8, 0x01ee, 0x80f3, 0xac00
ax_pose_terminator
sGulpinPose184:
ax_pose 3, 0x01ee, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose185:
ax_pose 4, 0x01ee, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose186:
ax_pose 5, 0x01ee, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose187:
ax_pose 38, 0x01e7, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose188:
ax_pose 39, 0x01eb, 0x80f5, 0xac00
ax_pose_terminator
sGulpinPose189:
ax_pose 40, 0x01eb, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose190:
ax_pose 41, 0x01ec, 0x80f5, 0xac00
ax_pose_terminator
sGulpinPose191:
ax_pose 42, 0x01ec, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose192:
ax_pose 41, 0x01ec, 0x90ec, 0xac00
ax_pose_terminator
sGulpinPose193:
ax_pose 40, 0x01ea, 0x90ed, 0xac00
ax_pose_terminator
sGulpinPose194:
ax_pose 39, 0x01eb, 0x90ec, 0xac00
ax_pose_terminator
sGulpinPose195:
ax_pose 16, 0x81ed, 0x80f7, 0xac00
ax_pose 17, 0x01fd, 0x0107, 0xac08
ax_pose_terminator
sGulpinPose196:
ax_pose 19, 0x01ed, 0x90eb, 0xac00
ax_pose_terminator
sGulpinPose197:
ax_pose 21, 0x81ed, 0x90f9, 0xac00
ax_pose 22, 0x01fd, 0x10f1, 0xac08
ax_pose_terminator
sGulpinPose198:
ax_pose 24, 0x01ef, 0x90eb, 0xac00
ax_pose_terminator
sGulpinPose199:
ax_pose 26, 0x01f0, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose200:
ax_pose 24, 0x01ef, 0x80f5, 0xac00
ax_pose_terminator
sGulpinPose201:
ax_pose 21, 0x81ed, 0x80f7, 0xac00
ax_pose 22, 0x01fd, 0x0107, 0xac08
ax_pose_terminator
sGulpinPose202:
ax_pose 19, 0x01ed, 0x80f5, 0xac00
ax_pose_terminator
sGulpinPose203:
ax_pose 0, 0x01ee, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose204:
ax_pose 1, 0x01ed, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose205:
ax_pose 27, 0x01ef, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose206:
ax_pose 3, 0x01ee, 0x90ec, 0xac00
ax_pose_terminator
sGulpinPose207:
ax_pose 4, 0x01ee, 0x90eb, 0xac00
ax_pose_terminator
sGulpinPose208:
ax_pose 29, 0x01ee, 0x90ed, 0xac00
ax_pose_terminator
sGulpinPose209:
ax_pose 6, 0x01ee, 0x90ed, 0xac00
ax_pose_terminator
sGulpinPose210:
ax_pose 7, 0x01ee, 0x90eb, 0xac00
ax_pose_terminator
sGulpinPose211:
ax_pose 31, 0x01ef, 0x90ed, 0xac00
ax_pose_terminator
sGulpinPose212:
ax_pose 9, 0x01ee, 0x90ec, 0xac00
ax_pose_terminator
sGulpinPose213:
ax_pose 10, 0x01ef, 0x90ec, 0xac00
ax_pose_terminator
sGulpinPose214:
ax_pose 33, 0x01ef, 0x90ec, 0xac00
ax_pose_terminator
sGulpinPose215:
ax_pose 12, 0x01ee, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose216:
ax_pose 13, 0x01ef, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose217:
ax_pose 35, 0x81f0, 0x80f6, 0xac00
ax_pose 36, 0x81f0, 0x0106, 0xac08
ax_pose_terminator
sGulpinPose218:
ax_pose 9, 0x01ee, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose219:
ax_pose 10, 0x01ef, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose220:
ax_pose 33, 0x01ef, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose221:
ax_pose 6, 0x01ee, 0x80f3, 0xac00
ax_pose_terminator
sGulpinPose222:
ax_pose 7, 0x01ee, 0x80f5, 0xac00
ax_pose_terminator
sGulpinPose223:
ax_pose 31, 0x01ef, 0x80f3, 0xac00
ax_pose_terminator
sGulpinPose224:
ax_pose 3, 0x01ee, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose225:
ax_pose 4, 0x01ee, 0x80f5, 0xac00
ax_pose_terminator
sGulpinPose226:
ax_pose 29, 0x01ee, 0x80f3, 0xac00
ax_pose_terminator
sGulpinPose227:
ax_pose 28, 0x01ea, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose228:
ax_pose 30, 0x01eb, 0x80f5, 0xac00
ax_pose_terminator
sGulpinPose229:
ax_pose 32, 0x01eb, 0x80f5, 0xac00
ax_pose_terminator
sGulpinPose230:
ax_pose 34, 0x01ec, 0x80f5, 0xac00
ax_pose_terminator
sGulpinPose231:
ax_pose 37, 0x01ed, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose232:
ax_pose 34, 0x01ec, 0x90eb, 0xac00
ax_pose_terminator
sGulpinPose233:
ax_pose 32, 0x01eb, 0x90eb, 0xac00
ax_pose_terminator
sGulpinPose234:
ax_pose 30, 0x01eb, 0x90eb, 0xac00
ax_pose_terminator
sGulpinPose235:
ax_pose 0, 0x01ee, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose236:
ax_pose 3, 0x01ee, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose237:
ax_pose 6, 0x01ee, 0x80f3, 0xac00
ax_pose_terminator
sGulpinPose238:
ax_pose 9, 0x01ee, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose239:
ax_pose 12, 0x01ee, 0x80f4, 0xac00
ax_pose_terminator
sGulpinPose240:
ax_pose 9, 0x01ee, 0x90ec, 0xac00
ax_pose_terminator
sGulpinPose241:
ax_pose 6, 0x01ee, 0x90ed, 0xac00
ax_pose_terminator
sGulpinPose242:
ax_pose 3, 0x01ee, 0x90ec, 0xac00
ax_pose_terminator
.align 2
sGulpinAnims_1_1:
ax_anim 8, 0, 0, 0, 0, 0, 0,
ax_anim 8, 0, 1, 0, 1, 0, 1,
ax_anim 10, 0, 1, 0, 2, 0, 2,
ax_anim 8, 0, 2, 0, 3, 0, 2,
ax_anim 8, 0, 2, 0, 2, 0, 1,
ax_anim 10, 0, 2, 0, 1, 0, 0,
ax_anim_terminator
sGulpinAnims_1_2:
ax_anim 8, 0, 3, 0, 0, 0, 0,
ax_anim 8, 0, 4, 1, 1, 1, 1,
ax_anim 10, 0, 4, 2, 2, 2, 2,
ax_anim 8, 0, 5, 2, 2, 2, 2,
ax_anim 8, 0, 5, 1, 1, 2, 2,
ax_anim 10, 0, 5, 0, 0, 1, 1,
ax_anim_terminator
sGulpinAnims_1_3:
ax_anim 8, 0, 6, 0, 0, 0, 0,
ax_anim 8, 0, 7, 1, 0, 1, 0,
ax_anim 10, 0, 7, 2, 0, 2, 0,
ax_anim 8, 0, 8, 2, 0, 2, 0,
ax_anim 8, 0, 8, 1, 0, 1, 0,
ax_anim 10, 0, 8, 0, 0, 0, 0,
ax_anim_terminator
sGulpinAnims_1_4:
ax_anim 8, 0, 9, 0, 0, 0, 0,
ax_anim 8, 0, 10, 1, -1, 1, -1,
ax_anim 10, 0, 10, 2, -2, 2, -2,
ax_anim 8, 0, 11, 2, -2, 2, -2,
ax_anim 8, 0, 11, 1, -1, 1, -1,
ax_anim 10, 0, 11, 0, 0, 0, 0,
ax_anim_terminator
sGulpinAnims_1_5:
ax_anim 8, 0, 12, 0, 0, 0, 0,
ax_anim 8, 0, 13, 0, -1, 0, -1,
ax_anim 10, 0, 13, 0, -2, 0, -2,
ax_anim 8, 0, 14, 0, -2, 0, -2,
ax_anim 8, 0, 14, 0, -1, 0, -1,
ax_anim 10, 0, 14, 0, 0, 0, 0,
ax_anim_terminator
sGulpinAnims_1_6:
ax_anim 8, 0, 15, 0, 0, 0, 0,
ax_anim 8, 0, 16, -1, -1, -1, -1,
ax_anim 10, 0, 16, -2, -2, -2, -2,
ax_anim 8, 0, 17, -2, -2, -2, -2,
ax_anim 8, 0, 17, -1, -1, -1, -1,
ax_anim 10, 0, 17, 0, 0, 0, 0,
ax_anim_terminator
sGulpinAnims_1_7:
ax_anim 8, 0, 18, 0, 0, 0, 0,
ax_anim 8, 0, 19, -1, 0, -1, 0,
ax_anim 10, 0, 19, -2, 0, -2, 0,
ax_anim 8, 0, 20, -2, 0, -2, 0,
ax_anim 8, 0, 20, -1, 0, -1, 0,
ax_anim 10, 0, 20, 0, 0, 0, 0,
ax_anim_terminator
sGulpinAnims_1_8:
ax_anim 8, 0, 21, 0, 0, 0, 0,
ax_anim 8, 0, 22, -1, 1, -1, 1,
ax_anim 10, 0, 22, -2, 2, -2, 2,
ax_anim 8, 0, 23, -2, 2, -2, 2,
ax_anim 8, 0, 23, -1, 1, -2, 2,
ax_anim 10, 0, 23, 0, 0, -1, 1,
ax_anim_terminator
.align 2
sGulpinAnims_2_1:
ax_anim 2, 0, 24, 0, -2, 0, -2,
ax_anim 2, 0, 24, 0, -4, 0, -4,
ax_anim 2, 0, 24, 0, -5, 0, -5,
ax_anim 4, 0, 27, 0, -5, 0, -5,
ax_anim 1, 0, 28, 0, -9, 0, -3,
ax_anim 2, 0, 28, 0, -2, 0, 5,
ax_anim 2, 2, 28, 0, 10, 0, 15,
ax_anim 2, 0, 27, 0, 18, 0, 18,
ax_anim 2, 1, 28, 0, 18, 0, 17,
ax_anim 2, 0, 27, 0, 18, 0, 18,
ax_anim 2, 0, 28, 0, 18, 0, 17,
ax_anim 2, 0, 27, 0, 18, 0, 18,
ax_anim 2, 0, 28, 0, 18, 0, 17,
ax_anim 2, 0, 24, 0, 7, 0, 7,
ax_anim_terminator
sGulpinAnims_2_2:
ax_anim 2, 0, 29, -2, -2, -2, -2,
ax_anim 2, 0, 29, -4, -4, -4, -4,
ax_anim 2, 0, 29, -5, -5, -5, -5,
ax_anim 4, 0, 32, -5, -5, -5, -5,
ax_anim 1, 0, 33, 1, -5, 1, 2,
ax_anim 2, 0, 33, 11, 0, 11, 11,
ax_anim 2, 2, 33, 16, 8, 16, 15,
ax_anim 2, 0, 32, 18, 17, 18, 17,
ax_anim 2, 1, 33, 18, 17, 18, 17,
ax_anim 2, 0, 32, 18, 17, 18, 17,
ax_anim 2, 0, 33, 18, 17, 18, 17,
ax_anim 2, 0, 32, 18, 17, 18, 17,
ax_anim 2, 0, 33, 18, 17, 18, 17,
ax_anim 2, 0, 29, 7, 7, 7, 7,
ax_anim_terminator
sGulpinAnims_2_3:
ax_anim 2, 0, 34, -2, 0, -2, 0,
ax_anim 2, 0, 34, -4, 0, -4, 0,
ax_anim 2, 0, 34, -5, 0, -5, 0,
ax_anim 4, 0, 37, -5, 0, -5, 0,
ax_anim 1, 0, 38, 2, -3, 2, 0,
ax_anim 2, 0, 38, 7, -4, 7, 0,
ax_anim 2, 2, 38, 13, -3, 13, 0,
ax_anim 2, 0, 37, 18, 0, 18, 0,
ax_anim 2, 1, 38, 18, 0, 18, 0,
ax_anim 2, 0, 37, 18, 0, 18, 0,
ax_anim 2, 0, 38, 18, 0, 18, 0,
ax_anim 2, 0, 37, 18, 0, 18, 0,
ax_anim 2, 0, 38, 18, 0, 18, 0,
ax_anim 2, 0, 34, 7, 0, 7, 0,
ax_anim_terminator
sGulpinAnims_2_4:
ax_anim 2, 0, 39, -2, 2, -2, 2,
ax_anim 2, 0, 39, -4, 4, -4, 4,
ax_anim 2, 0, 39, -5, 5, -5, 5,
ax_anim 4, 0, 42, -5, 5, -5, 5,
ax_anim 1, 0, 43, -2, -3, -2, 2,
ax_anim 2, 0, 43, 3, -14, 3, -4,
ax_anim 2, 2, 43, 12, -20, 12, -16,
ax_anim 2, 0, 42, 18, -24, 18, -24,
ax_anim 2, 1, 43, 18, -24, 19, -25,
ax_anim 2, 0, 42, 18, -24, 18, -24,
ax_anim 2, 0, 43, 18, -24, 19, -25,
ax_anim 2, 0, 42, 18, -24, 18, -24,
ax_anim 2, 0, 43, 18, -24, 19, -25,
ax_anim 2, 0, 39, 7, -9, 7, -9,
ax_anim_terminator
sGulpinAnims_2_5:
ax_anim 2, 0, 44, 0, 2, 0, 2,
ax_anim 2, 0, 44, 0, 4, 0, 4,
ax_anim 2, 0, 44, 0, 5, 0, 5,
ax_anim 4, 0, 47, 0, 5, 0, 5,
ax_anim 1, 0, 48, 0, -3, 0, -1,
ax_anim 2, 0, 48, 0, -14, 0, -10,
ax_anim 2, 2, 48, 0, -20, 0, -20,
ax_anim 2, 0, 47, 0, -24, 0, -24,
ax_anim 2, 1, 48, 0, -24, 0, -24,
ax_anim 2, 0, 47, 0, -24, 0, -24,
ax_anim 2, 0, 48, 0, -24, 0, -24,
ax_anim 2, 0, 47, 0, -24, 0, -24,
ax_anim 2, 0, 48, 0, -24, 0, -24,
ax_anim 2, 0, 44, 0, -9, 0, -9,
ax_anim_terminator
sGulpinAnims_2_6:
ax_anim 2, 0, 49, 2, 2, 2, 2,
ax_anim 2, 0, 49, 4, 4, 4, 4,
ax_anim 2, 0, 49, 5, 5, 5, 5,
ax_anim 4, 0, 52, 5, 5, 5, 5,
ax_anim 1, 0, 53, 2, -3, 2, 2,
ax_anim 2, 0, 53, -3, -14, -3, -4,
ax_anim 2, 2, 53, -12, -20, -12, -16,
ax_anim 2, 0, 52, -18, -24, -18, -24,
ax_anim 2, 1, 53, -18, -24, -19, -25,
ax_anim 2, 0, 52, -18, -24, -18, -24,
ax_anim 2, 0, 53, -18, -24, -19, -25,
ax_anim 2, 0, 52, -18, -24, -18, -24,
ax_anim 2, 0, 53, -18, -24, -19, -25,
ax_anim 2, 0, 49, -7, -9, -7, -9,
ax_anim_terminator
sGulpinAnims_2_7:
ax_anim 2, 0, 54, 2, 0, 2, 0,
ax_anim 2, 0, 54, 4, 0, 4, 0,
ax_anim 2, 0, 54, 5, 0, 5, 0,
ax_anim 4, 0, 57, 5, 0, 5, 0,
ax_anim 1, 0, 58, -2, -3, -2, 0,
ax_anim 2, 0, 58, -7, -4, -7, 0,
ax_anim 2, 2, 58, -13, -3, -13, 0,
ax_anim 2, 0, 57, -18, 0, -18, 0,
ax_anim 2, 1, 58, -18, 0, -19, 0,
ax_anim 2, 0, 57, -18, 0, -18, 0,
ax_anim 2, 0, 58, -18, 0, -19, 0,
ax_anim 2, 0, 57, -18, 0, -18, 0,
ax_anim 2, 0, 58, -18, 0, -19, 0,
ax_anim 2, 0, 54, -7, 0, -7, 0,
ax_anim_terminator
sGulpinAnims_2_8:
ax_anim 2, 0, 59, 2, -2, 2, -2,
ax_anim 2, 0, 59, 4, -4, 4, -4,
ax_anim 2, 0, 59, 5, -5, 5, -5,
ax_anim 4, 0, 62, 5, -5, 5, -5,
ax_anim 1, 0, 63, -1, -5, -1, 2,
ax_anim 2, 0, 63, -11, 0, -11, 11,
ax_anim 2, 2, 63, -16, 8, -16, 15,
ax_anim 2, 0, 62, -18, 17, -18, 17,
ax_anim 2, 1, 63, -18, 17, -18, 17,
ax_anim 2, 0, 62, -18, 17, -18, 17,
ax_anim 2, 0, 63, -18, 17, -18, 17,
ax_anim 2, 0, 62, -18, 17, -18, 17,
ax_anim 2, 0, 63, -18, 17, -18, 17,
ax_anim 2, 0, 59, -7, 7, -7, 7,
ax_anim_terminator
.align 2
sGulpinAnims_3_1:
ax_anim 2, 0, 64, 0, -2, 0, -2,
ax_anim 2, 0, 64, 0, -4, 0, -4,
ax_anim 2, 0, 64, 0, -5, 0, -5,
ax_anim 4, 0, 67, 0, -5, 0, -5,
ax_anim 1, 0, 68, 0, -9, 0, -3,
ax_anim 2, 0, 68, 0, -2, 0, 5,
ax_anim 2, 2, 68, 0, 10, 0, 15,
ax_anim 2, 0, 67, 0, 18, 0, 18,
ax_anim 2, 1, 68, 0, 18, 0, 17,
ax_anim 2, 0, 67, 0, 18, 0, 18,
ax_anim 2, 0, 68, 0, 18, 0, 17,
ax_anim 2, 0, 67, 0, 18, 0, 18,
ax_anim 2, 0, 68, 0, 18, 0, 17,
ax_anim 2, 0, 64, 0, 7, 0, 7,
ax_anim_terminator
sGulpinAnims_3_2:
ax_anim 2, 0, 69, -2, -2, -2, -2,
ax_anim 2, 0, 69, -4, -4, -4, -4,
ax_anim 2, 0, 69, -5, -5, -5, -5,
ax_anim 4, 0, 72, -5, -5, -5, -5,
ax_anim 1, 0, 73, 1, -5, 1, 2,
ax_anim 2, 0, 73, 11, 0, 11, 11,
ax_anim 2, 2, 73, 16, 8, 16, 15,
ax_anim 2, 0, 72, 18, 17, 18, 17,
ax_anim 2, 1, 73, 18, 17, 18, 17,
ax_anim 2, 0, 72, 18, 17, 18, 17,
ax_anim 2, 0, 73, 18, 17, 18, 17,
ax_anim 2, 0, 72, 18, 17, 18, 17,
ax_anim 2, 0, 73, 18, 17, 18, 17,
ax_anim 2, 0, 69, 7, 7, 7, 7,
ax_anim_terminator
sGulpinAnims_3_3:
ax_anim 2, 0, 74, -2, 0, -2, 0,
ax_anim 2, 0, 74, -4, 0, -4, 0,
ax_anim 2, 0, 74, -5, 0, -5, 0,
ax_anim 4, 0, 77, -5, 0, -5, 0,
ax_anim 1, 0, 78, 2, -3, 2, 0,
ax_anim 2, 0, 78, 7, -4, 7, 0,
ax_anim 2, 2, 78, 13, -3, 13, 0,
ax_anim 2, 0, 77, 18, 0, 18, 0,
ax_anim 2, 1, 78, 18, 0, 18, 0,
ax_anim 2, 0, 77, 18, 0, 18, 0,
ax_anim 2, 0, 78, 18, 0, 18, 0,
ax_anim 2, 0, 77, 18, 0, 18, 0,
ax_anim 2, 0, 78, 18, 0, 18, 0,
ax_anim 2, 0, 74, 7, 0, 7, 0,
ax_anim_terminator
sGulpinAnims_3_4:
ax_anim 2, 0, 79, -2, 2, -2, 2,
ax_anim 2, 0, 79, -4, 4, -4, 4,
ax_anim 2, 0, 79, -5, 5, -5, 5,
ax_anim 4, 0, 82, -5, 5, -5, 5,
ax_anim 1, 0, 83, -2, -3, -2, 2,
ax_anim 2, 0, 83, 3, -14, 3, -4,
ax_anim 2, 2, 83, 12, -20, 12, -16,
ax_anim 2, 0, 82, 18, -24, 18, -24,
ax_anim 2, 1, 83, 18, -24, 19, -25,
ax_anim 2, 0, 82, 18, -24, 18, -24,
ax_anim 2, 0, 83, 18, -24, 19, -25,
ax_anim 2, 0, 82, 18, -24, 18, -24,
ax_anim 2, 0, 83, 18, -24, 19, -25,
ax_anim 2, 0, 79, 7, -9, 7, -9,
ax_anim_terminator
sGulpinAnims_3_5:
ax_anim 2, 0, 84, 0, 2, 0, 2,
ax_anim 2, 0, 84, 0, 4, 0, 4,
ax_anim 2, 0, 84, 0, 5, 0, 5,
ax_anim 4, 0, 87, 0, 5, 0, 5,
ax_anim 1, 0, 88, 0, -3, 0, -1,
ax_anim 2, 0, 88, 0, -14, 0, -10,
ax_anim 2, 2, 88, 0, -20, 0, -20,
ax_anim 2, 0, 87, 0, -24, 0, -24,
ax_anim 2, 1, 88, 0, -24, 0, -24,
ax_anim 2, 0, 87, 0, -24, 0, -24,
ax_anim 2, 0, 88, 0, -24, 0, -24,
ax_anim 2, 0, 87, 0, -24, 0, -24,
ax_anim 2, 0, 88, 0, -24, 0, -24,
ax_anim 2, 0, 84, 0, -9, 0, -9,
ax_anim_terminator
sGulpinAnims_3_6:
ax_anim 2, 0, 89, 2, 2, 2, 2,
ax_anim 2, 0, 89, 4, 4, 4, 4,
ax_anim 2, 0, 89, 5, 5, 5, 5,
ax_anim 4, 0, 92, 5, 5, 5, 5,
ax_anim 1, 0, 93, 2, -3, 2, 2,
ax_anim 2, 0, 93, -3, -14, -3, -4,
ax_anim 2, 2, 93, -12, -20, -12, -16,
ax_anim 2, 0, 92, -18, -24, -18, -24,
ax_anim 2, 1, 93, -18, -24, -19, -25,
ax_anim 2, 0, 92, -18, -24, -18, -24,
ax_anim 2, 0, 93, -18, -24, -19, -25,
ax_anim 2, 0, 92, -18, -24, -18, -24,
ax_anim 2, 0, 93, -18, -24, -19, -25,
ax_anim 2, 0, 89, -7, -9, -7, -9,
ax_anim_terminator
sGulpinAnims_3_7:
ax_anim 2, 0, 94, 2, 0, 2, 0,
ax_anim 2, 0, 94, 4, 0, 4, 0,
ax_anim 2, 0, 94, 5, 0, 5, 0,
ax_anim 4, 0, 97, 5, 0, 5, 0,
ax_anim 1, 0, 98, -2, -3, -2, 0,
ax_anim 2, 0, 98, -7, -4, -7, 0,
ax_anim 2, 2, 98, -13, -3, -13, 0,
ax_anim 2, 0, 97, -18, 0, -18, 0,
ax_anim 2, 1, 98, -18, 0, -19, 0,
ax_anim 2, 0, 97, -18, 0, -18, 0,
ax_anim 2, 0, 98, -18, 0, -19, 0,
ax_anim 2, 0, 97, -18, 0, -18, 0,
ax_anim 2, 0, 98, -18, 0, -19, 0,
ax_anim 2, 0, 94, -7, 0, -7, 0,
ax_anim_terminator
sGulpinAnims_3_8:
ax_anim 2, 0, 99, 2, -2, 2, -2,
ax_anim 2, 0, 99, 4, -4, 4, -4,
ax_anim 2, 0, 99, 5, -5, 5, -5,
ax_anim 4, 0, 102, 5, -5, 5, -5,
ax_anim 1, 0, 103, -1, -5, -1, 2,
ax_anim 2, 0, 103, -11, 0, -11, 11,
ax_anim 2, 2, 103, -16, 8, -16, 15,
ax_anim 2, 0, 102, -18, 17, -18, 17,
ax_anim 2, 1, 103, -18, 17, -18, 17,
ax_anim 2, 0, 102, -18, 17, -18, 17,
ax_anim 2, 0, 103, -18, 17, -18, 17,
ax_anim 2, 0, 102, -18, 17, -18, 17,
ax_anim 2, 0, 103, -18, 17, -18, 17,
ax_anim 2, 0, 99, -7, 7, -7, 7,
ax_anim_terminator
.align 2
sGulpinAnims_4_1:
ax_anim 2, 0, 104, 0, -2, 0, -2,
ax_anim 2, 0, 105, 0, -3, 0, -3,
ax_anim 5, 0, 105, 0, -4, 0, -4,
ax_anim 3, 2, 105, 0, -4, 0, -4,
ax_anim 1, 0, 106, 0, -3, 0, -3,
ax_anim 2, 0, 106, 0, 0, 0, 0,
ax_anim 2, 0, 106, 0, 3, 0, 3,
ax_anim 2, 1, 106, -1, 3, -1, 3,
ax_anim 2, 0, 106, 0, 3, 0, 3,
ax_anim 2, 0, 106, -1, 3, -1, 3,
ax_anim 2, 0, 106, 0, 3, 0, 3,
ax_anim 2, 0, 106, -1, 3, -1, 3,
ax_anim 2, 0, 104, 0, 1, 0, 1,
ax_anim_terminator
sGulpinAnims_4_2:
ax_anim 2, 0, 107, -2, -2, -2, -2,
ax_anim 2, 0, 108, -3, -3, -3, -3,
ax_anim 5, 0, 108, -4, -4, -4, -4,
ax_anim 3, 2, 108, -4, -4, -4, -4,
ax_anim 1, 0, 109, -3, -3, -3, -3,
ax_anim 2, 0, 109, 0, 0, 0, 0,
ax_anim 2, 0, 109, 3, 3, 3, 3,
ax_anim 2, 1, 109, 2, 4, 2, 4,
ax_anim 2, 0, 109, 3, 3, 3, 3,
ax_anim 2, 0, 109, 2, 4, 2, 4,
ax_anim 2, 0, 109, 3, 3, 3, 3,
ax_anim 2, 0, 109, 2, 4, 2, 4,
ax_anim 2, 0, 107, 1, 1, 1, 1,
ax_anim_terminator
sGulpinAnims_4_3:
ax_anim 2, 0, 110, -2, 0, -2, 0,
ax_anim 2, 0, 111, -3, 0, -3, 0,
ax_anim 5, 0, 111, -4, 0, -4, 0,
ax_anim 3, 2, 111, -4, 0, -4, 0,
ax_anim 1, 0, 112, -3, 0, -3, 0,
ax_anim 2, 0, 112, 0, 0, 0, 0,
ax_anim 2, 0, 112, 3, 0, 3, 0,
ax_anim 2, 1, 112, 3, 1, 3, 1,
ax_anim 2, 0, 112, 3, 0, 3, 0,
ax_anim 2, 0, 112, 3, 1, 3, 1,
ax_anim 2, 0, 112, 3, 0, 3, 0,
ax_anim 2, 0, 112, 3, 1, 3, 1,
ax_anim 2, 0, 110, 1, 0, 1, 0,
ax_anim_terminator
sGulpinAnims_4_4:
ax_anim 2, 0, 113, -2, 2, -2, 2,
ax_anim 2, 0, 114, -3, 3, -3, 3,
ax_anim 5, 0, 114, -4, 4, -4, 4,
ax_anim 3, 2, 114, -4, 4, -4, 4,
ax_anim 1, 0, 115, -3, 3, -3, 3,
ax_anim 2, 0, 115, 0, 0, 0, 0,
ax_anim 2, 0, 115, 3, -3, 3, -3,
ax_anim 2, 1, 115, 2, -4, 2, -4,
ax_anim 2, 0, 115, 3, -3, 3, -3,
ax_anim 2, 0, 115, 2, -4, 2, -4,
ax_anim 2, 0, 115, 3, -3, 3, -3,
ax_anim 2, 0, 115, 2, -4, 2, -4,
ax_anim 2, 0, 113, 1, -1, 1, -1,
ax_anim_terminator
sGulpinAnims_4_5:
ax_anim 2, 0, 116, 0, 2, 0, 2,
ax_anim 2, 0, 117, 0, 3, 0, 3,
ax_anim 5, 0, 117, 0, 4, 0, 4,
ax_anim 3, 2, 117, 0, 4, 0, 4,
ax_anim 1, 0, 118, 0, 3, 0, 3,
ax_anim 2, 0, 118, 0, 0, 0, 0,
ax_anim 2, 0, 118, 0, -3, 0, -3,
ax_anim 2, 1, 118, -1, -3, -1, -3,
ax_anim 2, 0, 118, 0, -3, 0, -3,
ax_anim 2, 0, 118, -1, -3, -1, -3,
ax_anim 2, 0, 118, 0, -3, 0, -3,
ax_anim 2, 0, 118, -1, -3, -1, -3,
ax_anim 2, 0, 116, 0, -1, 0, -1,
ax_anim_terminator
sGulpinAnims_4_6:
ax_anim 2, 0, 119, 2, 2, 2, 2,
ax_anim 2, 0, 120, 3, 3, 3, 3,
ax_anim 5, 0, 120, 4, 4, 4, 4,
ax_anim 3, 2, 120, 4, 4, 4, 4,
ax_anim 1, 0, 121, 3, 3, 3, 3,
ax_anim 2, 0, 121, 0, 0, 0, 0,
ax_anim 2, 0, 121, -3, -3, -3, -3,
ax_anim 2, 1, 121, -2, -4, -2, -4,
ax_anim 2, 0, 121, -3, -3, -3, -3,
ax_anim 2, 0, 121, -2, -4, -2, -4,
ax_anim 2, 0, 121, -3, -3, -3, -3,
ax_anim 2, 0, 121, -2, -4, -2, -4,
ax_anim 2, 0, 119, -1, -1, -1, -1,
ax_anim_terminator
sGulpinAnims_4_7:
ax_anim 2, 0, 122, 2, 0, 2, 0,
ax_anim 2, 0, 123, 3, 0, 3, 0,
ax_anim 5, 0, 123, 4, 0, 4, 0,
ax_anim 3, 2, 123, 4, 0, 4, 0,
ax_anim 1, 0, 124, 3, 0, 3, 0,
ax_anim 2, 0, 124, 0, 0, 0, 0,
ax_anim 2, 0, 124, -3, 0, -3, 0,
ax_anim 2, 1, 124, -3, 1, -3, 1,
ax_anim 2, 0, 124, -3, 0, -3, 0,
ax_anim 2, 0, 124, -3, 1, -3, 1,
ax_anim 2, 0, 124, -3, 0, -3, 0,
ax_anim 2, 0, 124, -3, 1, -3, 1,
ax_anim 2, 0, 122, -1, 0, -1, 0,
ax_anim_terminator
sGulpinAnims_4_8:
ax_anim 2, 0, 125, 2, -2, 2, -2,
ax_anim 2, 0, 126, 3, -3, 3, -3,
ax_anim 5, 0, 126, 4, -4, 4, -4,
ax_anim 3, 2, 126, 4, -4, 4, -4,
ax_anim 1, 0, 127, 3, -3, 3, -3,
ax_anim 2, 0, 127, 0, 0, 0, 0,
ax_anim 2, 0, 127, -3, 3, -3, 3,
ax_anim 2, 1, 127, -2, 4, -2, 4,
ax_anim 2, 0, 127, -3, 3, -3, 3,
ax_anim 2, 0, 127, -2, 4, -2, 4,
ax_anim 2, 0, 127, -3, 3, -3, 3,
ax_anim 2, 0, 127, -2, 4, -2, 4,
ax_anim 2, 0, 125, -1, 1, -1, 1,
ax_anim_terminator
.align 2
sGulpinAnims_5_1:
ax_anim 2, 0, 129, 0, -2, 0, -2,
ax_anim 6, 0, 130, 0, -3, 0, -3,
ax_anim 1, 0, 130, 0, -1, 0, -1,
ax_anim 2, 0, 130, 0, 3, 0, 3,
ax_anim 2, 0, 130, 0, 3, 0, 3,
ax_anim 2, 2, 130, 0, 3, 0, 3,
ax_anim 2, 0, 130, 1, 3, 1, 3,
ax_anim 2, 0, 130, 0, 3, 0, 3,
ax_anim 2, 1, 129, 1, 3, 1, 3,
ax_anim 2, 0, 128, 0, 3, 0, 3,
ax_anim 2, 0, 128, 1, 3, 1, 3,
ax_anim 2, 0, 128, 0, 1, 0, 1,
ax_anim_terminator
sGulpinAnims_5_2:
ax_anim 2, 0, 132, -2, -2, -2, -2,
ax_anim 6, 0, 133, -3, -3, -3, -3,
ax_anim 1, 0, 133, -1, -1, -1, -1,
ax_anim 2, 0, 133, 3, 3, 3, 3,
ax_anim 2, 0, 133, 3, 3, 3, 3,
ax_anim 2, 2, 133, 3, 3, 3, 3,
ax_anim 2, 0, 133, 4, 2, 4, 2,
ax_anim 2, 0, 133, 3, 3, 3, 3,
ax_anim 2, 1, 132, 4, 2, 4, 2,
ax_anim 2, 0, 131, 3, 3, 3, 3,
ax_anim 2, 0, 131, 4, 2, 4, 2,
ax_anim 2, 0, 131, 1, 1, 1, 1,
ax_anim_terminator
sGulpinAnims_5_3:
ax_anim 2, 0, 135, -2, 0, -2, 0,
ax_anim 6, 0, 136, -3, 0, -3, 0,
ax_anim 1, 0, 136, -1, 0, -1, 0,
ax_anim 2, 0, 136, 3, 0, 3, 0,
ax_anim 2, 0, 136, 3, 0, 3, 0,
ax_anim 2, 2, 136, 3, 0, 3, 0,
ax_anim 2, 0, 136, 3, 1, 3, 1,
ax_anim 2, 0, 136, 3, 0, 3, 0,
ax_anim 2, 1, 135, 3, 1, 3, 1,
ax_anim 2, 0, 134, 3, 0, 3, 0,
ax_anim 2, 0, 134, 3, 1, 3, 1,
ax_anim 2, 0, 134, 1, 0, 1, 0,
ax_anim_terminator
sGulpinAnims_5_4:
ax_anim 2, 0, 138, -2, 2, -2, 2,
ax_anim 6, 0, 139, -3, 3, -3, 3,
ax_anim 1, 0, 139, -1, 1, -1, 1,
ax_anim 2, 0, 139, 3, -3, 3, -3,
ax_anim 2, 0, 139, 3, -3, 3, -3,
ax_anim 2, 2, 139, 3, -3, 3, -3,
ax_anim 2, 0, 139, 4, -2, 4, -2,
ax_anim 2, 0, 139, 3, -3, 3, -3,
ax_anim 2, 1, 138, 4, -2, 4, -2,
ax_anim 2, 0, 137, 3, -3, 3, -3,
ax_anim 2, 0, 137, 4, -2, 4, -2,
ax_anim 2, 0, 137, 1, -1, 1, -1,
ax_anim_terminator
sGulpinAnims_5_5:
ax_anim 2, 0, 141, 0, 2, 0, 2,
ax_anim 6, 0, 142, 0, 3, 0, 3,
ax_anim 1, 0, 142, 0, 1, 0, 1,
ax_anim 2, 0, 142, 0, -3, 0, -3,
ax_anim 2, 0, 142, 0, -3, 0, -3,
ax_anim 2, 2, 142, 0, -3, 0, -3,
ax_anim 2, 0, 142, 1, -3, 1, -3,
ax_anim 2, 0, 142, 0, -3, 0, -3,
ax_anim 2, 1, 141, 1, -3, 1, -3,
ax_anim 2, 0, 140, 0, -3, 0, -3,
ax_anim 2, 0, 140, 1, -3, 1, -3,
ax_anim 2, 0, 140, 0, -1, 0, -1,
ax_anim_terminator
sGulpinAnims_5_6:
ax_anim 2, 0, 144, 2, 2, 2, 2,
ax_anim 6, 0, 145, 3, 3, 3, 3,
ax_anim 1, 0, 145, 1, 1, 1, 1,
ax_anim 2, 0, 145, -3, -3, -3, -3,
ax_anim 2, 0, 145, -3, -3, -3, -3,
ax_anim 2, 2, 145, -3, -3, -3, -3,
ax_anim 2, 0, 145, -4, -2, -4, -2,
ax_anim 2, 0, 145, -3, -3, -3, -3,
ax_anim 2, 1, 144, -4, -2, -4, -2,
ax_anim 2, 0, 143, -3, -3, -3, -3,
ax_anim 2, 0, 143, -4, -2, -4, -2,
ax_anim 2, 0, 143, -1, -1, -1, -1,
ax_anim_terminator
sGulpinAnims_5_7:
ax_anim 2, 0, 147, 2, 0, 2, 0,
ax_anim 6, 0, 148, 3, 0, 3, 0,
ax_anim 1, 0, 148, 1, 0, 1, 0,
ax_anim 2, 0, 148, -3, 0, -3, 0,
ax_anim 2, 0, 148, -3, 0, -3, 0,
ax_anim 2, 2, 148, -3, 0, -3, 0,
ax_anim 2, 0, 148, -3, 1, -3, 1,
ax_anim 2, 0, 148, -3, 0, -3, 0,
ax_anim 2, 1, 147, -3, 1, -3, 1,
ax_anim 2, 0, 146, -3, 0, -3, 0,
ax_anim 2, 0, 146, -3, 1, -3, 1,
ax_anim 2, 0, 146, -1, 0, -1, 0,
ax_anim_terminator
sGulpinAnims_5_8:
ax_anim 2, 0, 150, 2, -2, 2, -2,
ax_anim 6, 0, 151, 3, -3, 3, -3,
ax_anim 1, 0, 151, 1, -1, 1, -1,
ax_anim 2, 0, 151, -3, 3, -3, 3,
ax_anim 2, 0, 151, -3, 3, -3, 3,
ax_anim 2, 2, 151, -3, 3, -3, 3,
ax_anim 2, 0, 151, -4, 2, -4, 2,
ax_anim 2, 0, 151, -3, 3, -3, 3,
ax_anim 2, 1, 150, -4, 2, -4, 2,
ax_anim 2, 0, 149, -3, 3, -3, 3,
ax_anim 2, 0, 149, -4, 2, -4, 2,
ax_anim 2, 0, 149, -1, 1, -1, 1,
ax_anim_terminator
.align 2
sGulpinAnims_6_1:
ax_anim 30, 0, 152, 0, 0, 0, 0,
ax_anim 35, 0, 153, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sGulpinAnims_7_1:
ax_anim 2, 0, 154, 0, -2, 0, -2,
ax_anim 8, 0, 154, 0, -3, 0, -3,
ax_anim_terminator
sGulpinAnims_7_2:
ax_anim 2, 0, 155, -2, -2, -2, -2,
ax_anim 8, 0, 155, -3, -3, -3, -3,
ax_anim_terminator
sGulpinAnims_7_3:
ax_anim 2, 0, 156, -2, 0, -2, 0,
ax_anim 8, 0, 156, -3, 0, -3, 0,
ax_anim_terminator
sGulpinAnims_7_4:
ax_anim 2, 0, 157, -2, 2, -2, 2,
ax_anim 8, 0, 157, -3, 3, -3, 3,
ax_anim_terminator
sGulpinAnims_7_5:
ax_anim 2, 0, 158, 0, 2, 0, 2,
ax_anim 8, 0, 158, 0, 3, 0, 3,
ax_anim_terminator
sGulpinAnims_7_6:
ax_anim 2, 0, 159, 2, 2, 2, 2,
ax_anim 8, 0, 159, 3, 3, 3, 3,
ax_anim_terminator
sGulpinAnims_7_7:
ax_anim 2, 0, 160, 2, 0, 2, 0,
ax_anim 8, 0, 160, 3, 0, 3, 0,
ax_anim_terminator
sGulpinAnims_7_8:
ax_anim 2, 0, 161, 2, -2, 2, -2,
ax_anim 8, 0, 161, 3, -3, 3, -3,
ax_anim_terminator
.align 2
sGulpinAnims_8_1:
ax_anim 20, 0, 162, 0, 0, 0, 0,
ax_anim 30, 0, 163, 0, 0, 0, 0,
ax_anim_terminator
sGulpinAnims_8_2:
ax_anim 20, 0, 165, 0, 0, 0, 0,
ax_anim 30, 0, 166, 0, 0, 0, 0,
ax_anim_terminator
sGulpinAnims_8_3:
ax_anim 20, 0, 168, 0, 0, 0, 0,
ax_anim 30, 0, 169, 0, 0, 0, 0,
ax_anim_terminator
sGulpinAnims_8_4:
ax_anim 20, 0, 171, 0, 0, 0, 0,
ax_anim 30, 0, 172, 0, 0, 0, 0,
ax_anim_terminator
sGulpinAnims_8_5:
ax_anim 20, 0, 174, 0, 0, 0, 0,
ax_anim 30, 0, 175, 0, 0, 0, 0,
ax_anim_terminator
sGulpinAnims_8_6:
ax_anim 20, 0, 177, 0, 0, 0, 0,
ax_anim 30, 0, 178, 0, 0, 0, 0,
ax_anim_terminator
sGulpinAnims_8_7:
ax_anim 20, 0, 180, 0, 0, 0, 0,
ax_anim 30, 0, 181, 0, 0, 0, 0,
ax_anim_terminator
sGulpinAnims_8_8:
ax_anim 20, 0, 183, 0, 0, 0, 0,
ax_anim 30, 0, 184, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sGulpinAnims_9_1:
ax_anim 2, 0, 186, 0, 0, 0, 0,
ax_anim 1, 0, 187, 6, 3, 6, 3,
ax_anim 2, 0, 188, 8, 9, 8, 9,
ax_anim 2, 0, 189, 7, 15, 7, 15,
ax_anim 3, 0, 190, 0, 18, 0, 18,
ax_anim 2, 3, 191, -7, 15, -7, 15,
ax_anim 2, 0, 192, -8, 9, -8, 9,
ax_anim 1, 0, 193, -6, 3, -6, 3,
ax_anim 1, 0, 186, 0, 0, 0, 0,
ax_anim_terminator
sGulpinAnims_9_2:
ax_anim 2, 0, 193, 0, 0, 0, 0,
ax_anim 1, 0, 186, 8, 0, 8, 0,
ax_anim 2, 0, 187, 16, 4, 16, 4,
ax_anim 2, 0, 188, 22, 10, 22, 10,
ax_anim 3, 0, 189, 21, 19, 21, 19,
ax_anim 2, 3, 190, 11, 19, 11, 19,
ax_anim 2, 0, 191, 3, 15, 3, 15,
ax_anim 1, 0, 192, 0, 7, 0, 7,
ax_anim 1, 0, 193, 0, 0, 0, 0,
ax_anim_terminator
sGulpinAnims_9_3:
ax_anim 2, 0, 192, 0, 0, 0, 0,
ax_anim 1, 0, 193, 3, -5, 3, -5,
ax_anim 2, 0, 186, 11, -7, 11, -7,
ax_anim 2, 0, 187, 16, -6, 16, -6,
ax_anim 3, 0, 188, 20, -1, 20, -1,
ax_anim 2, 3, 189, 18, 4, 18, 4,
ax_anim 2, 0, 190, 12, 5, 12, 5,
ax_anim 1, 0, 191, 3, 4, 3, 4,
ax_anim 1, 0, 192, 0, 0, 0, 0,
ax_anim_terminator
sGulpinAnims_9_4:
ax_anim 2, 0, 191, 0, 0, 0, 0,
ax_anim 1, 0, 192, -1, -8, -1, -8,
ax_anim 2, 0, 193, 3, -17, 3, -17,
ax_anim 2, 0, 186, 12, -22, 12, -22,
ax_anim 3, 0, 187, 20, -21, 20, -21,
ax_anim 2, 3, 188, 22, -13, 22, -13,
ax_anim 2, 0, 189, 19, -3, 19, -3,
ax_anim 1, 0, 190, 8, 1, 8, 1,
ax_anim 1, 0, 191, 0, 0, 0, 0,
ax_anim_terminator
sGulpinAnims_9_5:
ax_anim 2, 0, 190, 0, 0, 0, 0,
ax_anim 1, 0, 191, -10, -3, -10, -3,
ax_anim 2, 0, 192, -11, -8, -11, -8,
ax_anim 2, 0, 193, -9, -18, -9, -18,
ax_anim 3, 0, 186, 0, -22, 0, -22,
ax_anim 2, 3, 187, 9, -18, 9, -18,
ax_anim 2, 0, 188, 11, -8, 11, -8,
ax_anim 1, 0, 189, 10, -3, 10, -3,
ax_anim 1, 0, 190, 0, 0, 0, 0,
ax_anim_terminator
sGulpinAnims_9_6:
ax_anim 2, 0, 189, 0, 0, 0, 0,
ax_anim 1, 0, 188, 1, -8, 1, -8,
ax_anim 2, 0, 187, -3, -17, -3, -17,
ax_anim 2, 0, 186, -12, -22, -12, -22,
ax_anim 3, 0, 193, -20, -21, -20, -21,
ax_anim 2, 3, 192, -22, -13, -22, -13,
ax_anim 2, 0, 191, -19, -3, -19, -3,
ax_anim 1, 0, 190, -8, 1, -8, 1,
ax_anim 1, 0, 189, 0, 0, 0, 0,
ax_anim_terminator
sGulpinAnims_9_7:
ax_anim 2, 0, 188, 0, 0, 0, 0,
ax_anim 1, 0, 187, -3, -5, -3, -5,
ax_anim 2, 0, 186, -11, -7, -11, -7,
ax_anim 2, 0, 193, -16, -6, -16, -6,
ax_anim 3, 0, 192, -20, -1, -20, -1,
ax_anim 2, 3, 191, -18, 4, -18, 4,
ax_anim 2, 0, 190, -12, 5, -12, 5,
ax_anim 1, 0, 189, -3, 4, -3, 4,
ax_anim 1, 0, 188, 0, 0, 0, 0,
ax_anim_terminator
sGulpinAnims_9_8:
ax_anim 2, 0, 187, 0, 0, 0, 0,
ax_anim 1, 0, 186, -8, 0, -8, 0,
ax_anim 2, 0, 193, -16, 4, -16, 4,
ax_anim 2, 0, 192, -22, 10, -22, 10,
ax_anim 3, 0, 191, -21, 19, -21, 19,
ax_anim 2, 3, 190, -11, 19, -11, 19,
ax_anim 2, 0, 189, -3, 15, -3, 15,
ax_anim 1, 0, 188, 0, 7, 0, 7,
ax_anim 1, 0, 187, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sGulpinAnims_10_1:
ax_anim 2, 0, 194, 0, 0, 0, 0,
ax_anim 2, 0, 194, 6, 0, 6, 0,
ax_anim 2, 0, 194, -6, 0, -6, 0,
ax_anim 2, 0, 194, 10, 0, 10, 0,
ax_anim 2, 0, 194, -10, 0, -10, 0,
ax_anim 2, 0, 194, 12, 0, 12, 0,
ax_anim 3, 0, 194, -12, 0, -12, 0,
ax_anim 3, 0, 194, 13, 0, 13, 0,
ax_anim 3, 0, 194, -13, 0, -13, 0,
ax_anim 2, 0, 194, 12, 0, 12, 0,
ax_anim 3, 0, 194, -12, 0, -12, 0,
ax_anim 2, 0, 194, 10, 0, 10, 0,
ax_anim 2, 0, 194, -10, 0, -10, 0,
ax_anim 2, 0, 194, 6, 0, 6, 0,
ax_anim 2, 0, 194, -6, 0, -6, 0,
ax_anim 2, 0, 194, 0, 0, 0, 0,
ax_anim_terminator
sGulpinAnims_10_2:
ax_anim 2, 0, 195, 0, 0, 0, 0,
ax_anim 2, 0, 195, 6, -6, 6, -6,
ax_anim 2, 0, 195, -6, 6, -6, 6,
ax_anim 2, 0, 195, 10, -10, 10, -10,
ax_anim 2, 0, 195, -10, 10, -10, 10,
ax_anim 2, 0, 195, 12, -12, 12, -12,
ax_anim 3, 0, 195, -12, 12, -12, 12,
ax_anim 3, 0, 195, 13, -13, 13, -13,
ax_anim 3, 0, 195, -13, 13, -13, 13,
ax_anim 2, 0, 195, 12, -12, 12, -12,
ax_anim 3, 0, 195, -12, 12, -12, 12,
ax_anim 2, 0, 195, 10, -10, 10, -10,
ax_anim 2, 0, 195, -10, 10, -10, 10,
ax_anim 2, 0, 195, 6, -6, 6, -6,
ax_anim 2, 0, 195, -6, 6, -6, 6,
ax_anim 2, 0, 195, 0, 0, 0, 0,
ax_anim_terminator
sGulpinAnims_10_3:
ax_anim 2, 0, 196, 0, 0, 0, 0,
ax_anim 2, 0, 196, 0, -6, 0, -6,
ax_anim 2, 0, 196, 0, 6, 0, 6,
ax_anim 2, 0, 196, 0, -10, 0, -10,
ax_anim 2, 0, 196, 0, 10, 0, 10,
ax_anim 2, 0, 196, 0, -12, 0, -12,
ax_anim 3, 0, 196, 0, 12, 0, 12,
ax_anim 3, 0, 196, 0, -13, 0, -13,
ax_anim 3, 0, 196, 0, 13, 0, 13,
ax_anim 2, 0, 196, 0, -12, 0, -12,
ax_anim 3, 0, 196, 0, 12, 0, 12,
ax_anim 2, 0, 196, 0, -10, 0, -10,
ax_anim 2, 0, 196, 0, 10, 0, 10,
ax_anim 2, 0, 196, 0, -6, 0, -6,
ax_anim 2, 0, 196, 0, 6, 0, 6,
ax_anim 2, 0, 196, 0, 0, 0, 0,
ax_anim_terminator
sGulpinAnims_10_4:
ax_anim 2, 0, 197, 0, 0, 0, 0,
ax_anim 2, 0, 197, -6, -6, -6, -6,
ax_anim 2, 0, 197, 6, 6, 6, 6,
ax_anim 2, 0, 197, -10, -10, -10, -10,
ax_anim 2, 0, 197, 10, 10, 10, 10,
ax_anim 2, 0, 197, -12, -12, -12, -12,
ax_anim 3, 0, 197, 12, 12, 12, 12,
ax_anim 3, 0, 197, -13, -13, -13, -13,
ax_anim 3, 0, 197, 13, 13, 13, 13,
ax_anim 2, 0, 197, -12, -12, -12, -12,
ax_anim 3, 0, 197, 12, 12, 12, 12,
ax_anim 2, 0, 197, -10, -10, -10, -10,
ax_anim 2, 0, 197, 10, 10, 10, 10,
ax_anim 2, 0, 197, -6, -6, -6, -6,
ax_anim 2, 0, 197, 6, 6, 6, 6,
ax_anim 2, 0, 197, 0, 0, 0, 0,
ax_anim_terminator
sGulpinAnims_10_5:
ax_anim 2, 0, 198, 0, 0, 0, 0,
ax_anim 2, 0, 198, 6, 0, 6, 0,
ax_anim 2, 0, 198, -6, 0, -6, 0,
ax_anim 2, 0, 198, 10, 0, 10, 0,
ax_anim 2, 0, 198, -10, 0, -10, 0,
ax_anim 2, 0, 198, 12, 0, 12, 0,
ax_anim 3, 0, 198, -12, 0, -12, 0,
ax_anim 3, 0, 198, 13, 0, 13, 0,
ax_anim 3, 0, 198, -13, 0, -13, 0,
ax_anim 2, 0, 198, 12, 0, 12, 0,
ax_anim 3, 0, 198, -12, 0, -12, 0,
ax_anim 2, 0, 198, 10, 0, 10, 0,
ax_anim 2, 0, 198, -10, 0, -10, 0,
ax_anim 2, 0, 198, 6, 0, 6, 0,
ax_anim 2, 0, 198, -6, 0, -6, 0,
ax_anim 2, 0, 198, 0, 0, 0, 0,
ax_anim_terminator
sGulpinAnims_10_6:
ax_anim 2, 0, 199, 0, 0, 0, 0,
ax_anim 2, 0, 199, 6, -6, 6, -6,
ax_anim 2, 0, 199, -6, 6, -6, 6,
ax_anim 2, 0, 199, 10, -10, 10, -10,
ax_anim 2, 0, 199, -10, 10, -10, 10,
ax_anim 2, 0, 199, 12, -12, 12, -12,
ax_anim 3, 0, 199, -12, 12, -12, 12,
ax_anim 3, 0, 199, 13, -13, 13, -13,
ax_anim 3, 0, 199, -13, 13, -13, 13,
ax_anim 2, 0, 199, 12, -12, 12, -12,
ax_anim 3, 0, 199, -12, 12, -12, 12,
ax_anim 2, 0, 199, 10, -10, 10, -10,
ax_anim 2, 0, 199, -10, 10, -10, 10,
ax_anim 2, 0, 199, 6, -6, 6, -6,
ax_anim 2, 0, 199, -6, 6, -6, 6,
ax_anim 2, 0, 199, 0, 0, 0, 0,
ax_anim_terminator
sGulpinAnims_10_7:
ax_anim 2, 0, 200, 0, 0, 0, 0,
ax_anim 2, 0, 200, 0, -6, 0, -6,
ax_anim 2, 0, 200, 0, 6, 0, 6,
ax_anim 2, 0, 200, 0, -10, 0, -10,
ax_anim 2, 0, 200, 0, 10, 0, 10,
ax_anim 2, 0, 200, 0, -12, 0, -12,
ax_anim 3, 0, 200, 0, 12, 0, 12,
ax_anim 3, 0, 200, 0, -13, 0, -13,
ax_anim 3, 0, 200, 0, 13, 0, 13,
ax_anim 2, 0, 200, 0, -12, 0, -12,
ax_anim 3, 0, 200, 0, 12, 0, 12,
ax_anim 2, 0, 200, 0, -10, 0, -10,
ax_anim 2, 0, 200, 0, 10, 0, 10,
ax_anim 2, 0, 200, 0, -6, 0, -6,
ax_anim 2, 0, 200, 0, 6, 0, 6,
ax_anim 2, 0, 200, 0, 0, 0, 0,
ax_anim_terminator
sGulpinAnims_10_8:
ax_anim 2, 0, 201, 0, 0, 0, 0,
ax_anim 2, 0, 201, -6, -6, -6, -6,
ax_anim 2, 0, 201, 6, 6, 6, 6,
ax_anim 2, 0, 201, -10, -10, -10, -10,
ax_anim 2, 0, 201, 10, 10, 10, 10,
ax_anim 2, 0, 201, -12, -12, -12, -12,
ax_anim 3, 0, 201, 12, 12, 12, 12,
ax_anim 3, 0, 201, -13, -13, -13, -13,
ax_anim 3, 0, 201, 13, 13, 13, 13,
ax_anim 2, 0, 201, -12, -12, -12, -12,
ax_anim 3, 0, 201, 12, 12, 12, 12,
ax_anim 2, 0, 201, -10, -10, -10, -10,
ax_anim 2, 0, 201, 10, 10, 10, 10,
ax_anim 2, 0, 201, -6, -6, -6, -6,
ax_anim 2, 0, 201, 6, 6, 6, 6,
ax_anim 2, 0, 201, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sGulpinAnims_11_1:
ax_anim 2, 0, 202, 0, 0, 0, 0,
ax_anim 1, 0, 204, 0, -10, 0, 0,
ax_anim 2, 0, 204, 0, -16, 0, 0,
ax_anim 3, 0, 204, 0, -20, 0, 0,
ax_anim 4, 0, 204, 0, -21, 0, 0,
ax_anim 4, 0, 202, 0, -23, 0, 0,
ax_anim 3, 0, 203, 0, -22, 0, 0,
ax_anim 2, 0, 203, 0, -18, 0, 0,
ax_anim 1, 0, 203, 0, -12, 0, 0,
ax_anim 2, 2, 202, 0, 0, 0, 0,
ax_anim_terminator
sGulpinAnims_11_2:
ax_anim 2, 0, 205, 0, 0, 0, 0,
ax_anim 1, 0, 207, 0, -10, 0, 0,
ax_anim 2, 0, 207, 0, -16, 0, 0,
ax_anim 3, 0, 207, 0, -20, 0, 0,
ax_anim 4, 0, 207, 0, -21, 0, 0,
ax_anim 4, 0, 205, 0, -24, 0, 0,
ax_anim 3, 0, 206, 0, -22, 0, 0,
ax_anim 2, 0, 206, 0, -18, 0, 0,
ax_anim 1, 0, 206, 0, -12, 0, 0,
ax_anim 2, 2, 205, 0, 0, 0, 0,
ax_anim_terminator
sGulpinAnims_11_3:
ax_anim 2, 0, 208, 0, 0, 0, 0,
ax_anim 1, 0, 210, 0, -10, 0, 0,
ax_anim 2, 0, 210, 0, -16, 0, 0,
ax_anim 3, 0, 210, 0, -20, 0, 0,
ax_anim 4, 0, 210, 0, -21, 0, 0,
ax_anim 4, 0, 208, 0, -25, 0, 0,
ax_anim 3, 0, 209, 0, -22, 0, 0,
ax_anim 2, 0, 209, 0, -18, 0, 0,
ax_anim 1, 0, 209, 0, -12, 0, 0,
ax_anim 2, 2, 208, 0, 0, 0, 0,
ax_anim_terminator
sGulpinAnims_11_4:
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 1, 0, 213, 0, -10, 0, 0,
ax_anim 2, 0, 213, 0, -16, 0, 0,
ax_anim 3, 0, 213, 0, -20, 0, 0,
ax_anim 4, 0, 213, 0, -21, 0, 0,
ax_anim 4, 0, 211, 0, -21, 0, 0,
ax_anim 3, 0, 212, 0, -19, 0, 0,
ax_anim 2, 0, 212, 0, -16, 0, 0,
ax_anim 1, 0, 212, 0, -11, 0, 0,
ax_anim 2, 2, 211, 0, 0, 0, 0,
ax_anim_terminator
sGulpinAnims_11_5:
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 1, 0, 216, 0, -10, 0, 0,
ax_anim 2, 0, 216, 0, -16, 0, 0,
ax_anim 3, 0, 216, 0, -20, 0, 0,
ax_anim 4, 0, 216, 0, -21, 0, 0,
ax_anim 4, 0, 214, 0, -23, 0, 0,
ax_anim 3, 0, 215, 0, -20, 0, 0,
ax_anim 2, 0, 215, 0, -18, 0, 0,
ax_anim 1, 0, 215, 0, -12, 0, 0,
ax_anim 2, 2, 214, 0, 0, 0, 0,
ax_anim_terminator
sGulpinAnims_11_6:
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 1, 0, 219, 0, -10, 0, 0,
ax_anim 2, 0, 219, 0, -16, 0, 0,
ax_anim 3, 0, 219, 0, -20, 0, 0,
ax_anim 4, 0, 219, 0, -21, 0, 0,
ax_anim 4, 0, 217, 0, -21, 0, 0,
ax_anim 3, 0, 218, 0, -19, 0, 0,
ax_anim 2, 0, 218, 0, -16, 0, 0,
ax_anim 1, 0, 218, 0, -11, 0, 0,
ax_anim 2, 2, 217, 0, 0, 0, 0,
ax_anim_terminator
sGulpinAnims_11_7:
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 1, 0, 222, 0, -10, 0, 0,
ax_anim 2, 0, 222, 0, -16, 0, 0,
ax_anim 3, 0, 222, 0, -20, 0, 0,
ax_anim 4, 0, 222, 0, -21, 0, 0,
ax_anim 4, 0, 220, 0, -25, 0, 0,
ax_anim 3, 0, 221, 0, -22, 0, 0,
ax_anim 2, 0, 221, 0, -18, 0, 0,
ax_anim 1, 0, 221, 0, -12, 0, 0,
ax_anim 2, 2, 220, 0, 0, 0, 0,
ax_anim_terminator
sGulpinAnims_11_8:
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 1, 0, 225, 0, -10, 0, 0,
ax_anim 2, 0, 225, 0, -16, 0, 0,
ax_anim 3, 0, 225, 0, -20, 0, 0,
ax_anim 4, 0, 225, 0, -21, 0, 0,
ax_anim 4, 0, 223, 0, -24, 0, 0,
ax_anim 3, 0, 224, 0, -22, 0, 0,
ax_anim 2, 0, 224, 0, -18, 0, 0,
ax_anim 1, 0, 224, 0, -12, 0, 0,
ax_anim 2, 2, 223, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sGulpinAnims_12_1:
ax_anim 2, 0, 226, 1, 0, 1, 0,
ax_anim 2, 0, 226, 0, 0, 0, 0,
ax_anim 2, 0, 226, 1, 0, 1, 0,
ax_anim 2, 0, 226, 0, 0, 0, 0,
ax_anim 2, 0, 226, 1, 0, 1, 0,
ax_anim 2, 2, 226, 0, 0, 0, 0,
ax_anim 2, 0, 226, 1, 0, 1, 0,
ax_anim 2, 0, 226, 0, 0, 0, 0,
ax_anim 2, 0, 226, 1, 0, 1, 0,
ax_anim 2, 1, 226, 0, 0, 0, 0,
ax_anim_terminator
sGulpinAnims_12_2:
ax_anim 2, 0, 233, 1, -1, 1, -1,
ax_anim 2, 0, 233, 0, 0, 0, 0,
ax_anim 2, 0, 233, 1, -1, 1, -1,
ax_anim 2, 0, 233, 0, 0, 0, 0,
ax_anim 2, 0, 233, 1, -1, 1, -1,
ax_anim 2, 2, 233, 0, 0, 0, 0,
ax_anim 2, 0, 233, 1, -1, 1, -1,
ax_anim 2, 0, 233, 0, 0, 0, 0,
ax_anim 2, 0, 233, 1, -1, 1, -1,
ax_anim 2, 1, 233, 0, 0, 0, 0,
ax_anim_terminator
sGulpinAnims_12_3:
ax_anim 2, 0, 232, 0, -1, 0, -1,
ax_anim 2, 0, 232, 0, 0, 0, 0,
ax_anim 2, 0, 232, 0, -1, 0, -1,
ax_anim 2, 0, 232, 0, 0, 0, 0,
ax_anim 2, 0, 232, 0, -1, 0, -1,
ax_anim 2, 2, 232, 0, 0, 0, 0,
ax_anim 2, 0, 232, 0, -1, 0, -1,
ax_anim 2, 0, 232, 0, 0, 0, 0,
ax_anim 2, 0, 232, 0, -1, 0, -1,
ax_anim 2, 1, 232, 0, 0, 0, 0,
ax_anim_terminator
sGulpinAnims_12_4:
ax_anim 2, 0, 231, -1, -1, -1, -1,
ax_anim 2, 0, 231, 0, 0, 0, 0,
ax_anim 2, 0, 231, -1, -1, -1, -1,
ax_anim 2, 0, 231, 0, 0, 0, 0,
ax_anim 2, 0, 231, -1, -1, -1, -1,
ax_anim 2, 2, 231, 0, 0, 0, 0,
ax_anim 2, 0, 231, -1, -1, -1, -1,
ax_anim 2, 0, 231, 0, 0, 0, 0,
ax_anim 2, 0, 231, -1, -1, -1, -1,
ax_anim 2, 1, 231, 0, 0, 0, 0,
ax_anim_terminator
sGulpinAnims_12_5:
ax_anim 2, 0, 230, 1, 0, 1, 0,
ax_anim 2, 0, 230, 0, 0, 0, 0,
ax_anim 2, 0, 230, 1, 0, 1, 0,
ax_anim 2, 0, 230, 0, 0, 0, 0,
ax_anim 2, 0, 230, 1, 0, 1, 0,
ax_anim 2, 2, 230, 0, 0, 0, 0,
ax_anim 2, 0, 230, 1, 0, 1, 0,
ax_anim 2, 0, 230, 0, 0, 0, 0,
ax_anim 2, 0, 230, 1, 0, 1, 0,
ax_anim 2, 1, 230, 0, 0, 0, 0,
ax_anim_terminator
sGulpinAnims_12_6:
ax_anim 2, 0, 229, 1, -1, 1, -1,
ax_anim 2, 0, 229, 0, 0, 0, 0,
ax_anim 2, 0, 229, 1, -1, 1, -1,
ax_anim 2, 0, 229, 0, 0, 0, 0,
ax_anim 2, 0, 229, 1, -1, 1, -1,
ax_anim 2, 2, 229, 0, 0, 0, 0,
ax_anim 2, 0, 229, 1, -1, 1, -1,
ax_anim 2, 0, 229, 0, 0, 0, 0,
ax_anim 2, 0, 229, 1, -1, 1, -1,
ax_anim 2, 1, 229, 0, 0, 0, 0,
ax_anim_terminator
sGulpinAnims_12_7:
ax_anim 2, 0, 228, 0, -1, 0, -1,
ax_anim 2, 0, 228, 0, 0, 0, 0,
ax_anim 2, 0, 228, 0, -1, 0, -1,
ax_anim 2, 0, 228, 0, 0, 0, 0,
ax_anim 2, 0, 228, 0, -1, 0, -1,
ax_anim 2, 2, 228, 0, 0, 0, 0,
ax_anim 2, 0, 228, 0, -1, 0, -1,
ax_anim 2, 0, 228, 0, 0, 0, 0,
ax_anim 2, 0, 228, 0, -1, 0, -1,
ax_anim 2, 1, 228, 0, 0, 0, 0,
ax_anim_terminator
sGulpinAnims_12_8:
ax_anim 2, 0, 227, -1, -1, -1, -1,
ax_anim 2, 0, 227, 0, 0, 0, 0,
ax_anim 2, 0, 227, -1, -1, -1, -1,
ax_anim 2, 0, 227, 0, 0, 0, 0,
ax_anim 2, 0, 227, -1, -1, -1, -1,
ax_anim 2, 2, 227, 0, 0, 0, 0,
ax_anim 2, 0, 227, -1, -1, -1, -1,
ax_anim 2, 0, 227, 0, 0, 0, 0,
ax_anim 2, 0, 227, -1, -1, -1, -1,
ax_anim 2, 1, 227, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sGulpinAnims_13_1:
ax_anim 2, 0, 234, 0, 0, 0, 0,
ax_anim 2, 0, 235, 0, 0, 0, 0,
ax_anim 2, 0, 236, 0, 0, 0, 0,
ax_anim 2, 0, 237, 0, 0, 0, 0,
ax_anim 2, 0, 238, 0, 0, 0, 0,
ax_anim 2, 0, 239, 0, 0, 0, 0,
ax_anim 2, 0, 240, 0, 0, 0, 0,
ax_anim 2, 0, 241, 0, 0, 0, 0,
ax_anim 2, 2, 234, 0, 0, 0, 0,
ax_anim_terminator
sGulpinAnims_13_2:
ax_anim 2, 0, 241, 0, 0, 0, 0,
ax_anim 2, 0, 234, 0, 0, 0, 0,
ax_anim 2, 0, 235, 0, 0, 0, 0,
ax_anim 2, 0, 236, 0, 0, 0, 0,
ax_anim 2, 0, 237, 0, 0, 0, 0,
ax_anim 2, 0, 238, 0, 0, 0, 0,
ax_anim 2, 0, 239, 0, 0, 0, 0,
ax_anim 2, 0, 240, 0, 0, 0, 0,
ax_anim 2, 2, 241, 0, 0, 0, 0,
ax_anim_terminator
sGulpinAnims_13_3:
ax_anim 2, 0, 240, 0, 0, 0, 0,
ax_anim 2, 0, 241, 0, 0, 0, 0,
ax_anim 2, 0, 234, 0, 0, 0, 0,
ax_anim 2, 0, 235, 0, 0, 0, 0,
ax_anim 2, 0, 236, 0, 0, 0, 0,
ax_anim 2, 0, 237, 0, 0, 0, 0,
ax_anim 2, 0, 238, 0, 0, 0, 0,
ax_anim 2, 0, 239, 0, 0, 0, 0,
ax_anim 2, 2, 240, 0, 0, 0, 0,
ax_anim_terminator
sGulpinAnims_13_4:
ax_anim 2, 0, 239, 0, 0, 0, 0,
ax_anim 2, 0, 240, 0, 0, 0, 0,
ax_anim 2, 0, 241, 0, 0, 0, 0,
ax_anim 2, 0, 234, 0, 0, 0, 0,
ax_anim 2, 0, 235, 0, 0, 0, 0,
ax_anim 2, 0, 236, 0, 0, 0, 0,
ax_anim 2, 0, 237, 0, 0, 0, 0,
ax_anim 2, 0, 238, 0, 0, 0, 0,
ax_anim 2, 2, 239, 0, 0, 0, 0,
ax_anim_terminator
sGulpinAnims_13_5:
ax_anim 2, 0, 238, 0, 0, 0, 0,
ax_anim 2, 0, 239, 0, 0, 0, 0,
ax_anim 2, 0, 240, 0, 0, 0, 0,
ax_anim 2, 0, 241, 0, 0, 0, 0,
ax_anim 2, 0, 234, 0, 0, 0, 0,
ax_anim 2, 0, 235, 0, 0, 0, 0,
ax_anim 2, 0, 236, 0, 0, 0, 0,
ax_anim 2, 0, 237, 0, 0, 0, 0,
ax_anim 2, 2, 238, 0, 0, 0, 0,
ax_anim_terminator
sGulpinAnims_13_6:
ax_anim 2, 0, 237, 0, 0, 0, 0,
ax_anim 2, 0, 238, 0, 0, 0, 0,
ax_anim 2, 0, 239, 0, 0, 0, 0,
ax_anim 2, 0, 240, 0, 0, 0, 0,
ax_anim 2, 0, 241, 0, 0, 0, 0,
ax_anim 2, 0, 234, 0, 0, 0, 0,
ax_anim 2, 0, 235, 0, 0, 0, 0,
ax_anim 2, 0, 236, 0, 0, 0, 0,
ax_anim 2, 2, 237, 0, 0, 0, 0,
ax_anim_terminator
sGulpinAnims_13_7:
ax_anim 2, 0, 236, 0, 0, 0, 0,
ax_anim 2, 0, 237, 0, 0, 0, 0,
ax_anim 2, 0, 238, 0, 0, 0, 0,
ax_anim 2, 0, 239, 0, 0, 0, 0,
ax_anim 2, 0, 240, 0, 0, 0, 0,
ax_anim 2, 0, 241, 0, 0, 0, 0,
ax_anim 2, 0, 234, 0, 0, 0, 0,
ax_anim 2, 0, 235, 0, 0, 0, 0,
ax_anim 2, 2, 236, 0, 0, 0, 0,
ax_anim_terminator
sGulpinAnims_13_8:
ax_anim 2, 0, 235, 0, 0, 0, 0,
ax_anim 2, 0, 236, 0, 0, 0, 0,
ax_anim 2, 0, 237, 0, 0, 0, 0,
ax_anim 2, 0, 238, 0, 0, 0, 0,
ax_anim 2, 0, 239, 0, 0, 0, 0,
ax_anim 2, 0, 240, 0, 0, 0, 0,
ax_anim 2, 0, 241, 0, 0, 0, 0,
ax_anim 2, 0, 234, 0, 0, 0, 0,
ax_anim 2, 2, 235, 0, 0, 0, 0,
ax_anim_terminator
sGulpinGfx1:
.incbin "baserom.gba", 0x12E0264, 0x200
sGulpinSprites1:
ax_sprite sGulpinGfx1, 0x200
ax_sprite_terminator
sGulpinGfx2:
.incbin "baserom.gba", 0x12E0474, 0x200
sGulpinSprites2:
ax_sprite sGulpinGfx2, 0x200
ax_sprite_terminator
sGulpinGfx3:
.incbin "baserom.gba", 0x12E0684, 0x200
sGulpinSprites3:
ax_sprite sGulpinGfx3, 0x200
ax_sprite_terminator
sGulpinGfx4:
.incbin "baserom.gba", 0x12E0894, 0x200
sGulpinSprites4:
ax_sprite sGulpinGfx4, 0x200
ax_sprite_terminator
sGulpinGfx5:
.incbin "baserom.gba", 0x12E0AA4, 0x200
sGulpinSprites5:
ax_sprite sGulpinGfx5, 0x200
ax_sprite_terminator
sGulpinGfx6:
.incbin "baserom.gba", 0x12E0CB4, 0x200
sGulpinSprites6:
ax_sprite sGulpinGfx6, 0x200
ax_sprite_terminator
sGulpinGfx7:
.incbin "baserom.gba", 0x12E0EC4, 0x200
sGulpinSprites7:
ax_sprite sGulpinGfx7, 0x200
ax_sprite_terminator
sGulpinGfx8:
.incbin "baserom.gba", 0x12E10D4, 0x200
sGulpinSprites8:
ax_sprite sGulpinGfx8, 0x200
ax_sprite_terminator
sGulpinGfx9:
.incbin "baserom.gba", 0x12E12E4, 0x200
sGulpinSprites9:
ax_sprite sGulpinGfx9, 0x200
ax_sprite_terminator
sGulpinGfx10:
.incbin "baserom.gba", 0x12E14F4, 0x200
sGulpinSprites10:
ax_sprite sGulpinGfx10, 0x200
ax_sprite_terminator
sGulpinGfx11:
.incbin "baserom.gba", 0x12E1704, 0x200
sGulpinSprites11:
ax_sprite sGulpinGfx11, 0x200
ax_sprite_terminator
sGulpinGfx12:
.incbin "baserom.gba", 0x12E1914, 0x100
sGulpinSprites12:
ax_sprite sGulpinGfx12, 0x100
ax_sprite_terminator
sGulpinGfx13:
.incbin "baserom.gba", 0x12E1A24, 0x200
sGulpinSprites13:
ax_sprite sGulpinGfx13, 0x200
ax_sprite_terminator
sGulpinGfx14:
.incbin "baserom.gba", 0x12E1C34, 0x200
sGulpinSprites14:
ax_sprite sGulpinGfx14, 0x200
ax_sprite_terminator
sGulpinGfx15:
.incbin "baserom.gba", 0x12E1E44, 0x200
sGulpinSprites15:
ax_sprite sGulpinGfx15, 0x200
ax_sprite_terminator
sGulpinGfx16:
.incbin "baserom.gba", 0x12E2054, 0x20
sGulpinGfx16_1:
.incbin "baserom.gba", 0x12E2074, 0x60
sGulpinGfx16_2:
.incbin "baserom.gba", 0x12E20D4, 0x60
sGulpinSprites16:
ax_sprite 0, 0x20
ax_sprite sGulpinGfx16, 0x20
ax_sprite 0, 0x40
ax_sprite sGulpinGfx16_1, 0x60
ax_sprite 0, 0x20
ax_sprite sGulpinGfx16_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sGulpinGfx17:
.incbin "baserom.gba", 0x12E2174, 0xC0
sGulpinSprites17:
ax_sprite sGulpinGfx17, 0xc0
ax_sprite 0, 0x40
ax_sprite_terminator
sGulpinGfx18:
.incbin "baserom.gba", 0x12E224C, 0x20
sGulpinSprites18:
ax_sprite sGulpinGfx18, 0x20
ax_sprite_terminator
sGulpinGfx19:
.incbin "baserom.gba", 0x12E227C, 0x40
sGulpinGfx19_1:
.incbin "baserom.gba", 0x12E22BC, 0x60
sGulpinGfx19_2:
.incbin "baserom.gba", 0x12E231C, 0x60
sGulpinSprites19:
ax_sprite 0, 0x20
ax_sprite sGulpinGfx19, 0x40
ax_sprite 0, 0x20
ax_sprite sGulpinGfx19_1, 0x60
ax_sprite 0, 0x20
ax_sprite sGulpinGfx19_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sGulpinGfx20:
.incbin "baserom.gba", 0x12E23BC, 0x60
sGulpinGfx20_1:
.incbin "baserom.gba", 0x12E241C, 0x60
sGulpinGfx20_2:
.incbin "baserom.gba", 0x12E247C, 0x60
sGulpinSprites20:
ax_sprite sGulpinGfx20, 0x60
ax_sprite 0, 0x20
ax_sprite sGulpinGfx20_1, 0x60
ax_sprite 0, 0x20
ax_sprite sGulpinGfx20_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sGulpinGfx21:
.incbin "baserom.gba", 0x12E2514, 0x40
sGulpinGfx21_1:
.incbin "baserom.gba", 0x12E2554, 0x100
sGulpinSprites21:
ax_sprite 0, 0x20
ax_sprite sGulpinGfx21, 0x40
ax_sprite 0, 0x20
ax_sprite sGulpinGfx21_1, 0x100
ax_sprite 0, 0x80
ax_sprite_terminator
sGulpinGfx22:
.incbin "baserom.gba", 0x12E2684, 0xC0
sGulpinSprites22:
ax_sprite sGulpinGfx22, 0xc0
ax_sprite 0, 0x40
ax_sprite_terminator
sGulpinGfx23:
.incbin "baserom.gba", 0x12E275C, 0x20
sGulpinSprites23:
ax_sprite sGulpinGfx23, 0x20
ax_sprite_terminator
sGulpinGfx24:
.incbin "baserom.gba", 0x12E278C, 0x60
sGulpinGfx24_1:
.incbin "baserom.gba", 0x12E27EC, 0x60
sGulpinSprites24:
ax_sprite sGulpinGfx24, 0x60
ax_sprite 0, 0x20
ax_sprite sGulpinGfx24_1, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sGulpinGfx25:
.incbin "baserom.gba", 0x12E2874, 0x60
sGulpinGfx25_1:
.incbin "baserom.gba", 0x12E28D4, 0x60
sGulpinGfx25_2:
.incbin "baserom.gba", 0x12E2934, 0x60
sGulpinSprites25:
ax_sprite sGulpinGfx25, 0x60
ax_sprite 0, 0x20
ax_sprite sGulpinGfx25_1, 0x60
ax_sprite 0, 0x20
ax_sprite sGulpinGfx25_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sGulpinGfx26:
.incbin "baserom.gba", 0x12E29CC, 0x60
sGulpinGfx26_1:
.incbin "baserom.gba", 0x12E2A2C, 0x60
sGulpinGfx26_2:
.incbin "baserom.gba", 0x12E2A8C, 0x60
sGulpinSprites26:
ax_sprite sGulpinGfx26, 0x60
ax_sprite 0, 0x20
ax_sprite sGulpinGfx26_1, 0x60
ax_sprite 0, 0x20
ax_sprite sGulpinGfx26_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sGulpinGfx27:
.incbin "baserom.gba", 0x12E2B24, 0x60
sGulpinGfx27_1:
.incbin "baserom.gba", 0x12E2B84, 0x60
sGulpinGfx27_2:
.incbin "baserom.gba", 0x12E2BE4, 0x60
sGulpinSprites27:
ax_sprite sGulpinGfx27, 0x60
ax_sprite 0, 0x20
ax_sprite sGulpinGfx27_1, 0x60
ax_sprite 0, 0x20
ax_sprite sGulpinGfx27_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sGulpinGfx28:
.incbin "baserom.gba", 0x12E2C7C, 0x60
sGulpinGfx28_1:
.incbin "baserom.gba", 0x12E2CDC, 0x60
sGulpinGfx28_2:
.incbin "baserom.gba", 0x12E2D3C, 0x60
sGulpinSprites28:
ax_sprite sGulpinGfx28, 0x60
ax_sprite 0, 0x20
ax_sprite sGulpinGfx28_1, 0x60
ax_sprite 0, 0x20
ax_sprite sGulpinGfx28_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sGulpinGfx29:
.incbin "baserom.gba", 0x12E2DD4, 0x20
sGulpinGfx29_1:
.incbin "baserom.gba", 0x12E2DF4, 0x60
sGulpinGfx29_2:
.incbin "baserom.gba", 0x12E2E54, 0x60
sGulpinGfx29_3:
.incbin "baserom.gba", 0x12E2EB4, 0x60
sGulpinSprites29:
ax_sprite 0, 0x20
ax_sprite sGulpinGfx29, 0x20
ax_sprite 0, 0x40
ax_sprite sGulpinGfx29_1, 0x60
ax_sprite 0, 0x20
ax_sprite sGulpinGfx29_2, 0x60
ax_sprite 0, 0x20
ax_sprite sGulpinGfx29_3, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sGulpinGfx30:
.incbin "baserom.gba", 0x12E2F64, 0x60
sGulpinGfx30_1:
.incbin "baserom.gba", 0x12E2FC4, 0x60
sGulpinGfx30_2:
.incbin "baserom.gba", 0x12E3024, 0x60
sGulpinSprites30:
ax_sprite sGulpinGfx30, 0x60
ax_sprite 0, 0x20
ax_sprite sGulpinGfx30_1, 0x60
ax_sprite 0, 0x20
ax_sprite sGulpinGfx30_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sGulpinGfx31:
.incbin "baserom.gba", 0x12E30BC, 0x60
sGulpinGfx31_1:
.incbin "baserom.gba", 0x12E311C, 0x60
sGulpinGfx31_2:
.incbin "baserom.gba", 0x12E317C, 0x60
sGulpinGfx31_3:
.incbin "baserom.gba", 0x12E31DC, 0x20
sGulpinSprites31:
ax_sprite sGulpinGfx31, 0x60
ax_sprite 0, 0x20
ax_sprite sGulpinGfx31_1, 0x60
ax_sprite 0, 0x20
ax_sprite sGulpinGfx31_2, 0x60
ax_sprite 0, 0x40
ax_sprite sGulpinGfx31_3, 0x20
ax_sprite 0, 0x40
ax_sprite_terminator
sGulpinGfx32:
.incbin "baserom.gba", 0x12E3244, 0xE0
sGulpinGfx32_1:
.incbin "baserom.gba", 0x12E3324, 0x60
sGulpinSprites32:
ax_sprite sGulpinGfx32, 0xe0
ax_sprite 0, 0x20
ax_sprite sGulpinGfx32_1, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sGulpinGfx33:
.incbin "baserom.gba", 0x12E33AC, 0x60
sGulpinGfx33_1:
.incbin "baserom.gba", 0x12E340C, 0x60
sGulpinGfx33_2:
.incbin "baserom.gba", 0x12E346C, 0x60
sGulpinSprites33:
ax_sprite sGulpinGfx33, 0x60
ax_sprite 0, 0x20
ax_sprite sGulpinGfx33_1, 0x60
ax_sprite 0, 0x20
ax_sprite sGulpinGfx33_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sGulpinGfx34:
.incbin "baserom.gba", 0x12E3504, 0x60
sGulpinGfx34_1:
.incbin "baserom.gba", 0x12E3564, 0x60
sGulpinGfx34_2:
.incbin "baserom.gba", 0x12E35C4, 0x60
sGulpinSprites34:
ax_sprite sGulpinGfx34, 0x60
ax_sprite 0, 0x20
ax_sprite sGulpinGfx34_1, 0x60
ax_sprite 0, 0x20
ax_sprite sGulpinGfx34_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sGulpinGfx35:
.incbin "baserom.gba", 0x12E365C, 0x60
sGulpinGfx35_1:
.incbin "baserom.gba", 0x12E36BC, 0x60
sGulpinGfx35_2:
.incbin "baserom.gba", 0x12E371C, 0x60
sGulpinSprites35:
ax_sprite sGulpinGfx35, 0x60
ax_sprite 0, 0x20
ax_sprite sGulpinGfx35_1, 0x60
ax_sprite 0, 0x20
ax_sprite sGulpinGfx35_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sGulpinGfx36:
.incbin "baserom.gba", 0x12E37B4, 0xC0
sGulpinSprites36:
ax_sprite sGulpinGfx36, 0xc0
ax_sprite 0, 0x40
ax_sprite_terminator
sGulpinGfx37:
.incbin "baserom.gba", 0x12E388C, 0x40
sGulpinSprites37:
ax_sprite sGulpinGfx37, 0x40
ax_sprite_terminator
sGulpinGfx38:
.incbin "baserom.gba", 0x12E38DC, 0x60
sGulpinGfx38_1:
.incbin "baserom.gba", 0x12E393C, 0x60
sGulpinGfx38_2:
.incbin "baserom.gba", 0x12E399C, 0x60
sGulpinSprites38:
ax_sprite sGulpinGfx38, 0x60
ax_sprite 0, 0x20
ax_sprite sGulpinGfx38_1, 0x60
ax_sprite 0, 0x20
ax_sprite sGulpinGfx38_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sGulpinGfx39:
.incbin "baserom.gba", 0x12E3A34, 0x20
sGulpinGfx39_1:
.incbin "baserom.gba", 0x12E3A54, 0x60
sGulpinGfx39_2:
.incbin "baserom.gba", 0x12E3AB4, 0x60
sGulpinGfx39_3:
.incbin "baserom.gba", 0x12E3B14, 0x60
sGulpinSprites39:
ax_sprite 0, 0x20
ax_sprite sGulpinGfx39, 0x20
ax_sprite 0, 0x40
ax_sprite sGulpinGfx39_1, 0x60
ax_sprite 0, 0x20
ax_sprite sGulpinGfx39_2, 0x60
ax_sprite 0, 0x20
ax_sprite sGulpinGfx39_3, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sGulpinGfx40:
.incbin "baserom.gba", 0x12E3BC4, 0x60
sGulpinGfx40_1:
.incbin "baserom.gba", 0x12E3C24, 0x60
sGulpinGfx40_2:
.incbin "baserom.gba", 0x12E3C84, 0x60
sGulpinGfx40_3:
.incbin "baserom.gba", 0x12E3CE4, 0x20
sGulpinSprites40:
ax_sprite sGulpinGfx40, 0x60
ax_sprite 0, 0x20
ax_sprite sGulpinGfx40_1, 0x60
ax_sprite 0, 0x20
ax_sprite sGulpinGfx40_2, 0x60
ax_sprite 0, 0x40
ax_sprite sGulpinGfx40_3, 0x20
ax_sprite 0, 0x40
ax_sprite_terminator
sGulpinGfx41:
.incbin "baserom.gba", 0x12E3D4C, 0xE0
sGulpinGfx41_1:
.incbin "baserom.gba", 0x12E3E2C, 0x60
sGulpinGfx41_2:
.incbin "baserom.gba", 0x12E3E8C, 0x20
sGulpinSprites41:
ax_sprite sGulpinGfx41, 0xe0
ax_sprite 0, 0x20
ax_sprite sGulpinGfx41_1, 0x60
ax_sprite 0, 0x40
ax_sprite sGulpinGfx41_2, 0x20
ax_sprite 0, 0x40
ax_sprite_terminator
sGulpinGfx42:
.incbin "baserom.gba", 0x12E3EE4, 0x60
sGulpinGfx42_1:
.incbin "baserom.gba", 0x12E3F44, 0x60
sGulpinGfx42_2:
.incbin "baserom.gba", 0x12E3FA4, 0x60
sGulpinSprites42:
ax_sprite sGulpinGfx42, 0x60
ax_sprite 0, 0x20
ax_sprite sGulpinGfx42_1, 0x60
ax_sprite 0, 0x20
ax_sprite sGulpinGfx42_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sGulpinGfx43:
.incbin "baserom.gba", 0x12E403C, 0x60
sGulpinGfx43_1:
.incbin "baserom.gba", 0x12E409C, 0x60
sGulpinGfx43_2:
.incbin "baserom.gba", 0x12E40FC, 0x60
sGulpinGfx43_3:
.incbin "baserom.gba", 0x12E415C, 0x20
sGulpinSprites43:
ax_sprite sGulpinGfx43, 0x60
ax_sprite 0, 0x20
ax_sprite sGulpinGfx43_1, 0x60
ax_sprite 0, 0x20
ax_sprite sGulpinGfx43_2, 0x60
ax_sprite 0, 0x40
ax_sprite sGulpinGfx43_3, 0x20
ax_sprite 0, 0x40
ax_sprite_terminator
sGulpinGfx44:
.incbin "baserom.gba", 0x12E41C4, 0x200
sGulpinSprites44:
ax_sprite sGulpinGfx44, 0x200
ax_sprite_terminator
sGulpinGfx45:
.incbin "baserom.gba", 0x12E43D4, 0x200
sGulpinSprites45:
ax_sprite sGulpinGfx45, 0x200
ax_sprite_terminator
sGulpinGfx46:
.incbin "baserom.gba", 0x12E45E4, 0x200
sGulpinSprites46:
ax_sprite sGulpinGfx46, 0x200
ax_sprite_terminator
sGulpinGfx47:
.incbin "baserom.gba", 0x12E47F4, 0x200
sGulpinSprites47:
ax_sprite sGulpinGfx47, 0x200
ax_sprite_terminator
sGulpinGfx48:
.incbin "baserom.gba", 0x12E4A04, 0x200
sGulpinSprites48:
ax_sprite sGulpinGfx48, 0x200
ax_sprite_terminator
sGulpinGfx49:
.incbin "baserom.gba", 0x12E4C14, 0x200
sGulpinSprites49:
ax_sprite sGulpinGfx49, 0x200
ax_sprite_terminator
sGulpinGfx50:
.incbin "baserom.gba", 0x12E4E24, 0x200
sGulpinSprites50:
ax_sprite sGulpinGfx50, 0x200
ax_sprite_terminator
sAxPosesGulpin:
.4byte sGulpinPose1
.4byte sGulpinPose2
.4byte sGulpinPose3
.4byte sGulpinPose4
.4byte sGulpinPose5
.4byte sGulpinPose6
.4byte sGulpinPose7
.4byte sGulpinPose8
.4byte sGulpinPose9
.4byte sGulpinPose10
.4byte sGulpinPose11
.4byte sGulpinPose12
.4byte sGulpinPose13
.4byte sGulpinPose14
.4byte sGulpinPose15
.4byte sGulpinPose16
.4byte sGulpinPose17
.4byte sGulpinPose18
.4byte sGulpinPose19
.4byte sGulpinPose20
.4byte sGulpinPose21
.4byte sGulpinPose22
.4byte sGulpinPose23
.4byte sGulpinPose24
.4byte sGulpinPose25
.4byte sGulpinPose26
.4byte sGulpinPose27
.4byte sGulpinPose28
.4byte sGulpinPose29
.4byte sGulpinPose30
.4byte sGulpinPose31
.4byte sGulpinPose32
.4byte sGulpinPose33
.4byte sGulpinPose34
.4byte sGulpinPose35
.4byte sGulpinPose36
.4byte sGulpinPose37
.4byte sGulpinPose38
.4byte sGulpinPose39
.4byte sGulpinPose40
.4byte sGulpinPose41
.4byte sGulpinPose42
.4byte sGulpinPose43
.4byte sGulpinPose44
.4byte sGulpinPose45
.4byte sGulpinPose46
.4byte sGulpinPose47
.4byte sGulpinPose48
.4byte sGulpinPose49
.4byte sGulpinPose50
.4byte sGulpinPose51
.4byte sGulpinPose52
.4byte sGulpinPose53
.4byte sGulpinPose54
.4byte sGulpinPose55
.4byte sGulpinPose56
.4byte sGulpinPose57
.4byte sGulpinPose58
.4byte sGulpinPose59
.4byte sGulpinPose60
.4byte sGulpinPose61
.4byte sGulpinPose62
.4byte sGulpinPose63
.4byte sGulpinPose64
.4byte sGulpinPose65
.4byte sGulpinPose66
.4byte sGulpinPose67
.4byte sGulpinPose68
.4byte sGulpinPose69
.4byte sGulpinPose70
.4byte sGulpinPose71
.4byte sGulpinPose72
.4byte sGulpinPose73
.4byte sGulpinPose74
.4byte sGulpinPose75
.4byte sGulpinPose76
.4byte sGulpinPose77
.4byte sGulpinPose78
.4byte sGulpinPose79
.4byte sGulpinPose80
.4byte sGulpinPose81
.4byte sGulpinPose82
.4byte sGulpinPose83
.4byte sGulpinPose84
.4byte sGulpinPose85
.4byte sGulpinPose86
.4byte sGulpinPose87
.4byte sGulpinPose88
.4byte sGulpinPose89
.4byte sGulpinPose90
.4byte sGulpinPose91
.4byte sGulpinPose92
.4byte sGulpinPose93
.4byte sGulpinPose94
.4byte sGulpinPose95
.4byte sGulpinPose96
.4byte sGulpinPose97
.4byte sGulpinPose98
.4byte sGulpinPose99
.4byte sGulpinPose100
.4byte sGulpinPose101
.4byte sGulpinPose102
.4byte sGulpinPose103
.4byte sGulpinPose104
.4byte sGulpinPose105
.4byte sGulpinPose106
.4byte sGulpinPose107
.4byte sGulpinPose108
.4byte sGulpinPose109
.4byte sGulpinPose110
.4byte sGulpinPose111
.4byte sGulpinPose112
.4byte sGulpinPose113
.4byte sGulpinPose114
.4byte sGulpinPose115
.4byte sGulpinPose116
.4byte sGulpinPose117
.4byte sGulpinPose118
.4byte sGulpinPose119
.4byte sGulpinPose120
.4byte sGulpinPose121
.4byte sGulpinPose122
.4byte sGulpinPose123
.4byte sGulpinPose124
.4byte sGulpinPose125
.4byte sGulpinPose126
.4byte sGulpinPose127
.4byte sGulpinPose128
.4byte sGulpinPose129
.4byte sGulpinPose130
.4byte sGulpinPose131
.4byte sGulpinPose132
.4byte sGulpinPose133
.4byte sGulpinPose134
.4byte sGulpinPose135
.4byte sGulpinPose136
.4byte sGulpinPose137
.4byte sGulpinPose138
.4byte sGulpinPose139
.4byte sGulpinPose140
.4byte sGulpinPose141
.4byte sGulpinPose142
.4byte sGulpinPose143
.4byte sGulpinPose144
.4byte sGulpinPose145
.4byte sGulpinPose146
.4byte sGulpinPose147
.4byte sGulpinPose148
.4byte sGulpinPose149
.4byte sGulpinPose150
.4byte sGulpinPose151
.4byte sGulpinPose152
.4byte sGulpinPose153
.4byte sGulpinPose154
.4byte sGulpinPose155
.4byte sGulpinPose156
.4byte sGulpinPose157
.4byte sGulpinPose158
.4byte sGulpinPose159
.4byte sGulpinPose160
.4byte sGulpinPose161
.4byte sGulpinPose162
.4byte sGulpinPose163
.4byte sGulpinPose164
.4byte sGulpinPose165
.4byte sGulpinPose166
.4byte sGulpinPose167
.4byte sGulpinPose168
.4byte sGulpinPose169
.4byte sGulpinPose170
.4byte sGulpinPose171
.4byte sGulpinPose172
.4byte sGulpinPose173
.4byte sGulpinPose174
.4byte sGulpinPose175
.4byte sGulpinPose176
.4byte sGulpinPose177
.4byte sGulpinPose178
.4byte sGulpinPose179
.4byte sGulpinPose180
.4byte sGulpinPose181
.4byte sGulpinPose182
.4byte sGulpinPose183
.4byte sGulpinPose184
.4byte sGulpinPose185
.4byte sGulpinPose186
.4byte sGulpinPose187
.4byte sGulpinPose188
.4byte sGulpinPose189
.4byte sGulpinPose190
.4byte sGulpinPose191
.4byte sGulpinPose192
.4byte sGulpinPose193
.4byte sGulpinPose194
.4byte sGulpinPose195
.4byte sGulpinPose196
.4byte sGulpinPose197
.4byte sGulpinPose198
.4byte sGulpinPose199
.4byte sGulpinPose200
.4byte sGulpinPose201
.4byte sGulpinPose202
.4byte sGulpinPose203
.4byte sGulpinPose204
.4byte sGulpinPose205
.4byte sGulpinPose206
.4byte sGulpinPose207
.4byte sGulpinPose208
.4byte sGulpinPose209
.4byte sGulpinPose210
.4byte sGulpinPose211
.4byte sGulpinPose212
.4byte sGulpinPose213
.4byte sGulpinPose214
.4byte sGulpinPose215
.4byte sGulpinPose216
.4byte sGulpinPose217
.4byte sGulpinPose218
.4byte sGulpinPose219
.4byte sGulpinPose220
.4byte sGulpinPose221
.4byte sGulpinPose222
.4byte sGulpinPose223
.4byte sGulpinPose224
.4byte sGulpinPose225
.4byte sGulpinPose226
.4byte sGulpinPose227
.4byte sGulpinPose228
.4byte sGulpinPose229
.4byte sGulpinPose230
.4byte sGulpinPose231
.4byte sGulpinPose232
.4byte sGulpinPose233
.4byte sGulpinPose234
.4byte sGulpinPose235
.4byte sGulpinPose236
.4byte sGulpinPose237
.4byte sGulpinPose238
.4byte sGulpinPose239
.4byte sGulpinPose240
.4byte sGulpinPose241
.4byte sGulpinPose242
sAxPositionsGulpin:
.2byte    0,    0, 	  -7,   -1, 	   6,   -1, 	   0,   -4
.2byte    0,    2, 	  -7,   -2, 	   7,   -2, 	   0,   -3
.2byte    0,   -2, 	  -6,   -1, 	   5,   -1, 	   0,   -6
.2byte    5,   -1, 	   8,   -3, 	  -1,    1, 	   0,   -6
.2byte    7,    0, 	   9,   -3, 	  -2,    1, 	   1,   -5
.2byte    6,   -2, 	   9,   -2, 	   1,    1, 	   1,   -5
.2byte    8,   -6, 	   3,   -7, 	   5,    0, 	  -1,   -6
.2byte    9,   -4, 	   5,   -5, 	   5,    0, 	   1,   -5
.2byte    7,   -6, 	   3,   -6, 	   6,   -1, 	   0,   -5
.2byte    7,   -8, 	   2,   -8, 	   7,   -3, 	   0,   -6
.2byte    8,   -8, 	   0,   -9, 	   7,   -3, 	   1,   -7
.2byte    7,   -9, 	   2,   -9, 	   8,   -4, 	   0,   -6
.2byte    0,   -9, 	   7,   -6, 	  -8,   -6, 	   0,   -6
.2byte    0,  -12, 	   7,   -7, 	  -8,   -7, 	   0,   -9
.2byte    0,   -8, 	   7,   -7, 	  -8,   -7, 	   0,   -5
.2byte   -8,   -8, 	  -3,   -8, 	  -8,   -3, 	  -1,   -6
.2byte   -9,   -8, 	  -1,   -9, 	  -8,   -3, 	  -2,   -7
.2byte   -8,   -9, 	  -3,   -9, 	  -9,   -4, 	  -1,   -6
.2byte   -9,   -6, 	  -4,   -7, 	  -6,    0, 	   0,   -6
.2byte  -10,   -4, 	  -6,   -5, 	  -6,    0, 	  -2,   -5
.2byte   -8,   -6, 	  -4,   -6, 	  -7,   -1, 	  -1,   -5
.2byte   -6,   -1, 	  -9,   -3, 	   0,    1, 	  -1,   -6
.2byte   -8,    0, 	 -10,   -3, 	   1,    1, 	  -2,   -5
.2byte   -7,   -2, 	 -10,   -2, 	  -2,    1, 	  -2,   -5
.2byte    0,    0, 	  -7,   -1, 	   6,   -1, 	   0,   -4
.2byte    0,    2, 	  -7,   -2, 	   7,   -2, 	   0,   -3
.2byte    0,   -2, 	  -6,   -1, 	   5,   -1, 	   0,   -6
.2byte   -1,    1, 	  -8,   -1, 	   7,   -1, 	   0,   -4
.2byte   -1,   -1, 	  -6,   -1, 	   5,   -1, 	   0,   -6
.2byte    5,   -1, 	   8,   -3, 	  -1,    1, 	   0,   -6
.2byte    7,    0, 	   9,   -3, 	  -2,    1, 	   1,   -5
.2byte    6,   -2, 	   9,   -2, 	   1,    1, 	   1,   -5
.2byte    6,    1, 	   9,   -3, 	  -2,    2, 	   1,   -4
.2byte    5,   -1, 	   7,   -2, 	   0,    2, 	   0,   -6
.2byte    8,   -6, 	   3,   -7, 	   5,    0, 	  -1,   -6
.2byte    9,   -4, 	   5,   -5, 	   5,    0, 	   1,   -5
.2byte    7,   -6, 	   3,   -6, 	   6,   -1, 	   0,   -5
.2byte   11,   -5, 	   5,   -8, 	   8,    0, 	   0,   -5
.2byte    8,   -7, 	   4,   -8, 	   5,    0, 	   0,   -6
.2byte    7,   -8, 	   2,   -8, 	   7,   -3, 	   0,   -6
.2byte    8,   -8, 	   0,   -9, 	   7,   -3, 	   1,   -7
.2byte    7,   -9, 	   2,   -9, 	   8,   -4, 	   0,   -6
.2byte    8,   -8, 	   2,   -9, 	   9,   -3, 	  -1,   -6
.2byte    6,   -9, 	  -2,  -10, 	   7,   -4, 	  -1,   -8
.2byte    0,   -9, 	   7,   -6, 	  -8,   -6, 	   0,   -6
.2byte    0,  -12, 	   7,   -7, 	  -8,   -7, 	   0,   -9
.2byte    0,   -8, 	   7,   -7, 	  -8,   -7, 	   0,   -5
.2byte    0,   -9, 	   8,   -7, 	  -9,   -7, 	   0,   -5
.2byte   -1,   -9, 	   6,   -2, 	  -7,   -2, 	  -1,   -6
.2byte   -8,   -8, 	  -3,   -8, 	  -8,   -3, 	  -1,   -6
.2byte   -9,   -8, 	  -1,   -9, 	  -8,   -3, 	  -2,   -7
.2byte   -8,   -9, 	  -3,   -9, 	  -9,   -4, 	  -1,   -6
.2byte   -9,   -8, 	  -3,   -9, 	 -10,   -3, 	   0,   -6
.2byte   -7,   -9, 	   1,  -10, 	  -8,   -4, 	   0,   -8
.2byte   -9,   -6, 	  -4,   -7, 	  -6,    0, 	   0,   -6
.2byte  -10,   -4, 	  -6,   -5, 	  -6,    0, 	  -2,   -5
.2byte   -8,   -6, 	  -4,   -6, 	  -7,   -1, 	  -1,   -5
.2byte  -12,   -5, 	  -6,   -8, 	  -9,    0, 	  -1,   -5
.2byte   -9,   -7, 	  -5,   -8, 	  -6,    0, 	  -1,   -6
.2byte   -6,   -1, 	  -9,   -3, 	   0,    1, 	  -1,   -6
.2byte   -8,    0, 	 -10,   -3, 	   1,    1, 	  -2,   -5
.2byte   -7,   -2, 	 -10,   -2, 	  -2,    1, 	  -2,   -5
.2byte   -7,    1, 	 -10,   -3, 	   1,    2, 	  -2,   -4
.2byte   -6,   -1, 	  -8,   -2, 	  -1,    2, 	  -1,   -6
.2byte    0,    0, 	  -7,   -1, 	   6,   -1, 	   0,   -4
.2byte    0,    2, 	  -7,   -2, 	   7,   -2, 	   0,   -3
.2byte    0,   -2, 	  -6,   -1, 	   5,   -1, 	   0,   -6
.2byte   -1,    1, 	  -8,   -1, 	   7,   -1, 	   0,   -4
.2byte   -1,   -1, 	  -6,   -1, 	   5,   -1, 	   0,   -6
.2byte    5,   -1, 	   8,   -3, 	  -1,    1, 	   0,   -6
.2byte    7,    0, 	   9,   -3, 	  -2,    1, 	   1,   -5
.2byte    6,   -2, 	   9,   -2, 	   1,    1, 	   1,   -5
.2byte    6,    1, 	   9,   -3, 	  -2,    2, 	   1,   -4
.2byte    5,   -1, 	   7,   -2, 	   0,    2, 	   0,   -6
.2byte    8,   -6, 	   3,   -7, 	   5,    0, 	  -1,   -6
.2byte    9,   -4, 	   5,   -5, 	   5,    0, 	   1,   -5
.2byte    7,   -6, 	   3,   -6, 	   6,   -1, 	   0,   -5
.2byte   11,   -5, 	   5,   -8, 	   8,    0, 	   0,   -5
.2byte    8,   -7, 	   4,   -8, 	   5,    0, 	   0,   -6
.2byte    7,   -8, 	   2,   -8, 	   7,   -3, 	   0,   -6
.2byte    8,   -8, 	   0,   -9, 	   7,   -3, 	   1,   -7
.2byte    7,   -9, 	   2,   -9, 	   8,   -4, 	   0,   -6
.2byte    8,   -8, 	   2,   -9, 	   9,   -3, 	  -1,   -6
.2byte    6,   -9, 	  -2,  -10, 	   7,   -4, 	  -1,   -8
.2byte    0,   -9, 	   7,   -6, 	  -8,   -6, 	   0,   -6
.2byte    0,  -12, 	   7,   -7, 	  -8,   -7, 	   0,   -9
.2byte    0,   -8, 	   7,   -7, 	  -8,   -7, 	   0,   -5
.2byte    0,   -9, 	   8,   -7, 	  -9,   -7, 	   0,   -5
.2byte   -1,   -9, 	   6,   -2, 	  -7,   -2, 	  -1,   -6
.2byte   -8,   -8, 	  -3,   -8, 	  -8,   -3, 	  -1,   -6
.2byte   -9,   -8, 	  -1,   -9, 	  -8,   -3, 	  -2,   -7
.2byte   -8,   -9, 	  -3,   -9, 	  -9,   -4, 	  -1,   -6
.2byte   -9,   -8, 	  -3,   -9, 	 -10,   -3, 	   0,   -6
.2byte   -7,   -9, 	   1,  -10, 	  -8,   -4, 	   0,   -8
.2byte   -9,   -6, 	  -4,   -7, 	  -6,    0, 	   0,   -6
.2byte  -10,   -4, 	  -6,   -5, 	  -6,    0, 	  -2,   -5
.2byte   -8,   -6, 	  -4,   -6, 	  -7,   -1, 	  -1,   -5
.2byte  -12,   -5, 	  -6,   -8, 	  -9,    0, 	  -1,   -5
.2byte   -9,   -7, 	  -5,   -8, 	  -6,    0, 	  -1,   -6
.2byte   -6,   -1, 	  -9,   -3, 	   0,    1, 	  -1,   -6
.2byte   -8,    0, 	 -10,   -3, 	   1,    1, 	  -2,   -5
.2byte   -7,   -2, 	 -10,   -2, 	  -2,    1, 	  -2,   -5
.2byte   -7,    1, 	 -10,   -3, 	   1,    2, 	  -2,   -4
.2byte   -6,   -1, 	  -8,   -2, 	  -1,    2, 	  -1,   -6
.2byte    0,    0, 	  -7,   -1, 	   6,   -1, 	   0,   -4
.2byte   -1,   -6, 	  -7,   -3, 	   6,   -3, 	   0,   -6
.2byte    0,   -4, 	  -8,   -3, 	   8,   -3, 	   0,   -7
.2byte    5,   -1, 	   8,   -3, 	  -1,    1, 	   0,   -6
.2byte    4,   -7, 	   8,   -6, 	  -1,   -1, 	  -1,   -6
.2byte    3,   -1, 	   9,   -2, 	  -5,    2, 	  -1,   -4
.2byte    8,   -6, 	   3,   -7, 	   5,    0, 	  -1,   -6
.2byte    7,  -11, 	  -1,  -11, 	   5,   -4, 	  -2,   -7
.2byte    5,   -6, 	   7,   -5, 	   3,    0, 	  -1,   -8
.2byte    7,   -8, 	   2,   -8, 	   7,   -3, 	   0,   -6
.2byte    6,  -10, 	  -2,   -9, 	   8,   -4, 	  -2,   -6
.2byte    5,   -7, 	   2,   -4, 	   7,   -1, 	  -2,   -8
.2byte    0,   -9, 	   7,   -6, 	  -8,   -6, 	   0,   -6
.2byte    0,   -9, 	   7,   -7, 	  -8,   -7, 	   0,   -6
.2byte    0,  -12, 	   7,   -4, 	  -8,   -4, 	   0,   -6
.2byte   -8,   -8, 	  -3,   -8, 	  -8,   -3, 	  -1,   -6
.2byte   -7,  -10, 	   1,   -9, 	  -9,   -4, 	   1,   -6
.2byte   -6,   -7, 	  -3,   -4, 	  -8,   -1, 	   1,   -8
.2byte   -9,   -6, 	  -4,   -7, 	  -6,    0, 	   0,   -6
.2byte   -8,  -11, 	   0,  -11, 	  -6,   -4, 	   1,   -7
.2byte   -6,   -6, 	  -8,   -5, 	  -4,    0, 	   0,   -8
.2byte   -6,   -1, 	  -9,   -3, 	   0,    1, 	  -1,   -6
.2byte   -5,   -7, 	  -9,   -6, 	   0,   -1, 	   0,   -6
.2byte   -4,   -1, 	 -10,   -2, 	   4,    2, 	   0,   -4
.2byte    0,    0, 	  -7,   -1, 	   6,   -1, 	   0,   -4
.2byte    0,   -4, 	  -8,   -3, 	   8,   -3, 	   0,   -7
.2byte    0,   -5, 	  -9,   -2, 	   8,   -1, 	   0,   -8
.2byte    5,   -1, 	   8,   -3, 	  -1,    1, 	   0,   -6
.2byte    3,   -1, 	   9,   -2, 	  -5,    2, 	  -1,   -4
.2byte    0,   -3, 	   7,   -2, 	  -4,    3, 	  -2,   -5
.2byte    8,   -6, 	   3,   -7, 	   5,    0, 	  -1,   -6
.2byte    5,   -6, 	   7,   -5, 	   3,    0, 	  -1,   -8
.2byte    3,   -7, 	   5,   -3, 	   5,    0, 	  -2,   -7
.2byte    7,   -8, 	   2,   -8, 	   7,   -3, 	   0,   -6
.2byte    5,   -7, 	   2,   -4, 	   7,   -1, 	  -2,   -8
.2byte    2,   -7, 	   4,   -3, 	   5,    0, 	  -3,   -6
.2byte    0,   -9, 	   7,   -6, 	  -8,   -6, 	   0,   -6
.2byte    0,  -12, 	   7,   -4, 	  -8,   -4, 	   0,   -6
.2byte    0,  -13, 	   7,   -3, 	  -8,   -3, 	   0,   -7
.2byte   -8,   -8, 	  -3,   -8, 	  -8,   -3, 	  -1,   -6
.2byte   -6,   -7, 	  -3,   -4, 	  -8,   -1, 	   1,   -8
.2byte   -3,   -7, 	  -5,   -3, 	  -6,    0, 	   2,   -6
.2byte   -9,   -6, 	  -4,   -7, 	  -6,    0, 	   0,   -6
.2byte   -6,   -6, 	  -8,   -5, 	  -4,    0, 	   0,   -8
.2byte   -4,   -7, 	  -6,   -3, 	  -6,    0, 	   1,   -7
.2byte   -6,   -1, 	  -9,   -3, 	   0,    1, 	  -1,   -6
.2byte   -4,   -1, 	 -10,   -2, 	   4,    2, 	   0,   -4
.2byte   -1,   -3, 	  -8,   -2, 	   3,    3, 	   1,   -5
.2byte   -7,   -1, 	 -10,   -1, 	   3,    2, 	  -1,   -3
.2byte   -7,    0, 	 -10,    0, 	   4,    2, 	  -1,   -2
.2byte    0,   -1, 	 -10,   -3, 	   9,   -2, 	   0,   -4
.2byte    4,   -2, 	   9,   -5, 	  -8,   -1, 	  -1,   -4
.2byte    7,   -4, 	   6,   -7, 	   4,    1, 	  -2,   -4
.2byte    7,   -7, 	   1,   -8, 	   8,   -2, 	  -2,   -3
.2byte    0,   -5, 	  10,   -3, 	 -11,   -3, 	   0,   -1
.2byte   -8,   -7, 	  -2,   -8, 	  -9,   -2, 	   1,   -3
.2byte   -8,   -4, 	  -7,   -7, 	  -5,    1, 	   1,   -4
.2byte   -5,   -2, 	 -10,   -5, 	   7,   -1, 	   0,   -4
.2byte    0,    0, 	  -7,   -1, 	   6,   -1, 	   0,   -4
.2byte    0,    2, 	  -7,   -2, 	   7,   -2, 	   0,   -3
.2byte    0,   -2, 	  -6,   -1, 	   5,   -1, 	   0,   -6
.2byte    5,   -1, 	   8,   -3, 	  -1,    1, 	   0,   -6
.2byte    7,    0, 	   9,   -3, 	  -2,    1, 	   1,   -5
.2byte    6,   -2, 	   9,   -2, 	   1,    1, 	   1,   -5
.2byte    8,   -6, 	   3,   -7, 	   5,    0, 	  -1,   -6
.2byte    9,   -4, 	   5,   -5, 	   5,    0, 	   1,   -5
.2byte    7,   -6, 	   3,   -6, 	   6,   -1, 	   0,   -5
.2byte    7,   -8, 	   2,   -8, 	   7,   -3, 	   0,   -6
.2byte    8,   -8, 	   0,   -9, 	   7,   -3, 	   1,   -7
.2byte    7,   -9, 	   2,   -9, 	   8,   -4, 	   0,   -6
.2byte    0,   -9, 	   7,   -6, 	  -8,   -6, 	   0,   -6
.2byte    0,  -12, 	   7,   -7, 	  -8,   -7, 	   0,   -9
.2byte    0,   -8, 	   7,   -7, 	  -8,   -7, 	   0,   -5
.2byte   -8,   -8, 	  -3,   -8, 	  -8,   -3, 	  -1,   -6
.2byte   -9,   -8, 	  -1,   -9, 	  -8,   -3, 	  -2,   -7
.2byte   -8,   -9, 	  -3,   -9, 	  -9,   -4, 	  -1,   -6
.2byte   -9,   -6, 	  -4,   -7, 	  -6,    0, 	   0,   -6
.2byte  -10,   -4, 	  -6,   -5, 	  -6,    0, 	  -2,   -5
.2byte   -8,   -6, 	  -4,   -6, 	  -7,   -1, 	  -1,   -5
.2byte   -6,   -1, 	  -9,   -3, 	   0,    1, 	  -1,   -6
.2byte   -8,    0, 	 -10,   -3, 	   1,    1, 	  -2,   -5
.2byte   -7,   -2, 	 -10,   -2, 	  -2,    1, 	  -2,   -5
.2byte    0,   -5, 	  -9,   -2, 	   8,   -1, 	   0,   -8
.2byte    0,   -5, 	  -7,   -4, 	   4,    1, 	   2,   -7
.2byte   -2,   -6, 	  -4,   -2, 	  -4,    1, 	   3,   -6
.2byte   -3,   -8, 	  -5,   -4, 	  -6,   -1, 	   2,   -7
.2byte    0,  -14, 	   7,   -4, 	  -8,   -4, 	   0,   -8
.2byte    3,   -8, 	   5,   -4, 	   6,   -1, 	  -2,   -7
.2byte    2,   -7, 	   4,   -3, 	   4,    0, 	  -3,   -7
.2byte    0,   -5, 	   7,   -4, 	  -4,    1, 	  -2,   -7
.2byte   -1,   -1, 	  -6,   -1, 	   5,   -1, 	   0,   -6
.2byte    4,   -2, 	   6,   -3, 	  -1,    1, 	  -1,   -7
.2byte    7,   -6, 	   3,   -7, 	   4,    1, 	  -1,   -5
.2byte    5,   -8, 	  -3,   -9, 	   6,   -3, 	  -2,   -7
.2byte   -1,   -9, 	   6,   -2, 	  -7,   -2, 	  -1,   -6
.2byte   -6,   -8, 	   2,   -9, 	  -7,   -3, 	   1,   -7
.2byte   -8,   -6, 	  -4,   -7, 	  -5,    1, 	   0,   -5
.2byte   -5,   -2, 	  -7,   -3, 	   0,    1, 	   0,   -7
.2byte    0,    0, 	  -7,   -1, 	   6,   -1, 	   0,   -4
.2byte    0,    1, 	  -7,   -3, 	   7,   -3, 	   0,   -4
.2byte   -1,   -5, 	  -7,   -2, 	   6,   -2, 	   0,   -5
.2byte    5,   -1, 	   8,   -3, 	  -1,    1, 	   0,   -6
.2byte    6,    0, 	   8,   -3, 	  -3,    1, 	   0,   -5
.2byte    4,   -7, 	   8,   -6, 	  -1,   -1, 	  -1,   -6
.2byte    8,   -6, 	   3,   -7, 	   5,    0, 	  -1,   -6
.2byte    7,   -4, 	   3,   -5, 	   3,    0, 	  -1,   -5
.2byte    8,  -10, 	   0,  -10, 	   6,   -3, 	  -1,   -6
.2byte    7,   -8, 	   2,   -8, 	   7,   -3, 	   0,   -6
.2byte    8,   -7, 	   0,   -8, 	   7,   -2, 	   1,   -6
.2byte    6,  -10, 	  -2,   -9, 	   8,   -4, 	  -2,   -6
.2byte    0,   -9, 	   7,   -6, 	  -8,   -6, 	   0,   -6
.2byte    0,  -11, 	   7,   -6, 	  -8,   -6, 	   0,   -8
.2byte    0,   -9, 	   7,   -7, 	  -8,   -7, 	   0,   -6
.2byte   -8,   -8, 	  -3,   -8, 	  -8,   -3, 	  -1,   -6
.2byte   -9,   -7, 	  -1,   -8, 	  -8,   -2, 	  -2,   -6
.2byte   -7,  -10, 	   1,   -9, 	  -9,   -4, 	   1,   -6
.2byte   -9,   -6, 	  -4,   -7, 	  -6,    0, 	   0,   -6
.2byte   -8,   -4, 	  -4,   -5, 	  -4,    0, 	   0,   -5
.2byte   -9,  -10, 	  -1,  -10, 	  -7,   -3, 	   0,   -6
.2byte   -6,   -1, 	  -9,   -3, 	   0,    1, 	  -1,   -6
.2byte   -7,    0, 	  -9,   -3, 	   2,    1, 	  -1,   -5
.2byte   -5,   -7, 	  -9,   -6, 	   0,   -1, 	   0,   -6
.2byte    0,   -3, 	  -8,   -2, 	   8,   -2, 	   0,   -6
.2byte   -3,   -3, 	  -9,   -4, 	   5,    0, 	   1,   -6
.2byte   -5,   -6, 	  -7,   -5, 	  -3,    0, 	   1,   -8
.2byte   -5,   -7, 	  -2,   -4, 	  -7,   -1, 	   2,   -8
.2byte    0,  -13, 	   7,   -5, 	  -8,   -5, 	   0,   -7
.2byte    4,   -7, 	   1,   -4, 	   6,   -1, 	  -3,   -8
.2byte    4,   -6, 	   6,   -5, 	   2,    0, 	  -2,   -8
.2byte    2,   -3, 	   8,   -4, 	  -6,    0, 	  -2,   -6
.2byte    0,    0, 	  -7,   -1, 	   6,   -1, 	   0,   -4
.2byte   -6,   -1, 	  -9,   -3, 	   0,    1, 	  -1,   -6
.2byte   -9,   -6, 	  -4,   -7, 	  -6,    0, 	   0,   -6
.2byte   -8,   -8, 	  -3,   -8, 	  -8,   -3, 	  -1,   -6
.2byte    0,   -9, 	   7,   -6, 	  -8,   -6, 	   0,   -6
.2byte    7,   -8, 	   2,   -8, 	   7,   -3, 	   0,   -6
.2byte    8,   -6, 	   3,   -7, 	   5,    0, 	  -1,   -6
.2byte    5,   -1, 	   8,   -3, 	  -1,    1, 	   0,   -6
sGulpinAnimTable1:
.4byte sGulpinAnims_1_1
.4byte sGulpinAnims_1_2
.4byte sGulpinAnims_1_3
.4byte sGulpinAnims_1_4
.4byte sGulpinAnims_1_5
.4byte sGulpinAnims_1_6
.4byte sGulpinAnims_1_7
.4byte sGulpinAnims_1_8
sGulpinAnimTable2:
.4byte sGulpinAnims_2_1
.4byte sGulpinAnims_2_2
.4byte sGulpinAnims_2_3
.4byte sGulpinAnims_2_4
.4byte sGulpinAnims_2_5
.4byte sGulpinAnims_2_6
.4byte sGulpinAnims_2_7
.4byte sGulpinAnims_2_8
sGulpinAnimTable3:
.4byte sGulpinAnims_3_1
.4byte sGulpinAnims_3_2
.4byte sGulpinAnims_3_3
.4byte sGulpinAnims_3_4
.4byte sGulpinAnims_3_5
.4byte sGulpinAnims_3_6
.4byte sGulpinAnims_3_7
.4byte sGulpinAnims_3_8
sGulpinAnimTable4:
.4byte sGulpinAnims_4_1
.4byte sGulpinAnims_4_2
.4byte sGulpinAnims_4_3
.4byte sGulpinAnims_4_4
.4byte sGulpinAnims_4_5
.4byte sGulpinAnims_4_6
.4byte sGulpinAnims_4_7
.4byte sGulpinAnims_4_8
sGulpinAnimTable5:
.4byte sGulpinAnims_5_1
.4byte sGulpinAnims_5_2
.4byte sGulpinAnims_5_3
.4byte sGulpinAnims_5_4
.4byte sGulpinAnims_5_5
.4byte sGulpinAnims_5_6
.4byte sGulpinAnims_5_7
.4byte sGulpinAnims_5_8
sGulpinAnimTable6:
.4byte sGulpinAnims_6_1
.4byte sGulpinAnims_6_1
.4byte sGulpinAnims_6_1
.4byte sGulpinAnims_6_1
.4byte sGulpinAnims_6_1
.4byte sGulpinAnims_6_1
.4byte sGulpinAnims_6_1
.4byte sGulpinAnims_6_1
sGulpinAnimTable7:
.4byte sGulpinAnims_7_1
.4byte sGulpinAnims_7_2
.4byte sGulpinAnims_7_3
.4byte sGulpinAnims_7_4
.4byte sGulpinAnims_7_5
.4byte sGulpinAnims_7_6
.4byte sGulpinAnims_7_7
.4byte sGulpinAnims_7_8
sGulpinAnimTable8:
.4byte sGulpinAnims_8_1
.4byte sGulpinAnims_8_2
.4byte sGulpinAnims_8_3
.4byte sGulpinAnims_8_4
.4byte sGulpinAnims_8_5
.4byte sGulpinAnims_8_6
.4byte sGulpinAnims_8_7
.4byte sGulpinAnims_8_8
sGulpinAnimTable9:
.4byte sGulpinAnims_9_1
.4byte sGulpinAnims_9_2
.4byte sGulpinAnims_9_3
.4byte sGulpinAnims_9_4
.4byte sGulpinAnims_9_5
.4byte sGulpinAnims_9_6
.4byte sGulpinAnims_9_7
.4byte sGulpinAnims_9_8
sGulpinAnimTable10:
.4byte sGulpinAnims_10_1
.4byte sGulpinAnims_10_2
.4byte sGulpinAnims_10_3
.4byte sGulpinAnims_10_4
.4byte sGulpinAnims_10_5
.4byte sGulpinAnims_10_6
.4byte sGulpinAnims_10_7
.4byte sGulpinAnims_10_8
sGulpinAnimTable11:
.4byte sGulpinAnims_11_1
.4byte sGulpinAnims_11_2
.4byte sGulpinAnims_11_3
.4byte sGulpinAnims_11_4
.4byte sGulpinAnims_11_5
.4byte sGulpinAnims_11_6
.4byte sGulpinAnims_11_7
.4byte sGulpinAnims_11_8
sGulpinAnimTable12:
.4byte sGulpinAnims_12_1
.4byte sGulpinAnims_12_2
.4byte sGulpinAnims_12_3
.4byte sGulpinAnims_12_4
.4byte sGulpinAnims_12_5
.4byte sGulpinAnims_12_6
.4byte sGulpinAnims_12_7
.4byte sGulpinAnims_12_8
sGulpinAnimTable13:
.4byte sGulpinAnims_13_1
.4byte sGulpinAnims_13_2
.4byte sGulpinAnims_13_3
.4byte sGulpinAnims_13_4
.4byte sGulpinAnims_13_5
.4byte sGulpinAnims_13_6
.4byte sGulpinAnims_13_7
.4byte sGulpinAnims_13_8
sAxAnimationsGulpin:
.4byte sGulpinAnimTable1
.4byte sGulpinAnimTable2
.4byte sGulpinAnimTable3
.4byte sGulpinAnimTable4
.4byte sGulpinAnimTable5
.4byte sGulpinAnimTable6
.4byte sGulpinAnimTable7
.4byte sGulpinAnimTable8
.4byte sGulpinAnimTable9
.4byte sGulpinAnimTable10
.4byte sGulpinAnimTable11
.4byte sGulpinAnimTable12
.4byte sGulpinAnimTable13
sAxSpritesGulpin:
.4byte sGulpinSprites1
.4byte sGulpinSprites2
.4byte sGulpinSprites3
.4byte sGulpinSprites4
.4byte sGulpinSprites5
.4byte sGulpinSprites6
.4byte sGulpinSprites7
.4byte sGulpinSprites8
.4byte sGulpinSprites9
.4byte sGulpinSprites10
.4byte sGulpinSprites11
.4byte sGulpinSprites12
.4byte sGulpinSprites13
.4byte sGulpinSprites14
.4byte sGulpinSprites15
.4byte sGulpinSprites16
.4byte sGulpinSprites17
.4byte sGulpinSprites18
.4byte sGulpinSprites19
.4byte sGulpinSprites20
.4byte sGulpinSprites21
.4byte sGulpinSprites22
.4byte sGulpinSprites23
.4byte sGulpinSprites24
.4byte sGulpinSprites25
.4byte sGulpinSprites26
.4byte sGulpinSprites27
.4byte sGulpinSprites28
.4byte sGulpinSprites29
.4byte sGulpinSprites30
.4byte sGulpinSprites31
.4byte sGulpinSprites32
.4byte sGulpinSprites33
.4byte sGulpinSprites34
.4byte sGulpinSprites35
.4byte sGulpinSprites36
.4byte sGulpinSprites37
.4byte sGulpinSprites38
.4byte sGulpinSprites39
.4byte sGulpinSprites40
.4byte sGulpinSprites41
.4byte sGulpinSprites42
.4byte sGulpinSprites43
.4byte sGulpinSprites44
.4byte sGulpinSprites45
.4byte sGulpinSprites46
.4byte sGulpinSprites47
.4byte sGulpinSprites48
.4byte sGulpinSprites49
.4byte sGulpinSprites50
sAxMainGulpin:
ax_main sAxPosesGulpin, sAxAnimationsGulpin, 13, sAxSpritesGulpin, sAxPositionsGulpin
