.global gAxHoOh
gAxHoOh:
ax_siro sAxMainHoOh
sHoOhPose1:
ax_pose 0, 0x01c6, 0xc0e4, 0x3c00
ax_pose_terminator
sHoOhPose2:
ax_pose 1, 0x41c9, 0x40f0, 0x3c00
ax_pose 2, 0x41d1, 0x80e0, 0x3c04
ax_pose 3, 0x41d1, 0x8100, 0x3c0c
ax_pose 4, 0x01de, 0x00d8, 0x3c14
ax_pose 5, 0x01de, 0x0120, 0x3c15
ax_pose 6, 0x41e1, 0xc0e0, 0x3c16
ax_pose_terminator
sHoOhPose3:
ax_pose 7, 0x01cd, 0xc0e8, 0x3c00
ax_pose_terminator
sHoOhPose4:
ax_pose 8, 0x01c6, 0xd0db, 0x3c00
ax_pose_terminator
sHoOhPose5:
ax_pose 9, 0x01c6, 0xd0dd, 0x3c00
ax_pose_terminator
sHoOhPose6:
ax_pose 10, 0x01c6, 0xd0d7, 0x3c00
ax_pose_terminator
sHoOhPose7:
ax_pose 11, 0x01c6, 0xd0df, 0x3c00
ax_pose_terminator
sHoOhPose8:
ax_pose 12, 0x41ee, 0x90ff, 0x3c00
ax_pose 13, 0x41ce, 0xd0df, 0x3c08
ax_pose 14, 0x41ee, 0x90df, 0x3c28
ax_pose_terminator
sHoOhPose9:
ax_pose 15, 0x81c6, 0xd0df, 0x3c00
ax_pose 16, 0x01d6, 0x90ff, 0x3c20
ax_pose 17, 0x01f6, 0x50ff, 0x3c30
ax_pose_terminator
sHoOhPose10:
ax_pose 18, 0x01c6, 0xd0df, 0x3c00
ax_pose_terminator
sHoOhPose11:
ax_pose 19, 0x01e2, 0x111f, 0x3c00
ax_pose 20, 0x01c6, 0x90df, 0x3c01
ax_pose 21, 0x41d6, 0x90ff, 0x3c11
ax_pose 22, 0x41e6, 0xd0df, 0x3c19
ax_pose_terminator
sHoOhPose12:
ax_pose 23, 0x41d6, 0x90df, 0x3c00
ax_pose 24, 0x41d6, 0x90ff, 0x3c08
ax_pose 25, 0x41e6, 0xd0df, 0x3c10
ax_pose_terminator
sHoOhPose13:
ax_pose 26, 0x01c6, 0xc0e4, 0x3c00
ax_pose_terminator
sHoOhPose14:
ax_pose 27, 0x01de, 0x0120, 0x3c00
ax_pose 28, 0x81db, 0x00d8, 0x3c01
ax_pose 29, 0x41d6, 0x8100, 0x3c03
ax_pose 30, 0x41d6, 0x80e0, 0x3c0b
ax_pose 31, 0x41e6, 0xc0e0, 0x3c13
ax_pose_terminator
sHoOhPose15:
ax_pose 32, 0x01d0, 0x00fc, 0x3c00
ax_pose 33, 0x01d8, 0x4104, 0x3c01
ax_pose 34, 0x41d8, 0x80e4, 0x3c05
ax_pose 35, 0x41e8, 0xc0e4, 0x3c0d
ax_pose_terminator
sHoOhPose16:
ax_pose 18, 0x01c6, 0xc0e0, 0x3c00
ax_pose_terminator
sHoOhPose17:
ax_pose 22, 0x41e6, 0xc0e0, 0x3c00
ax_pose 21, 0x41d6, 0x80e0, 0x3c20
ax_pose 20, 0x01c6, 0x8100, 0x3c28
ax_pose 19, 0x01e2, 0x00d8, 0x3c38
ax_pose_terminator
sHoOhPose18:
ax_pose 25, 0x41e6, 0xc0e1, 0x3c00
ax_pose 23, 0x41d6, 0x8101, 0x3c20
ax_pose 24, 0x41d6, 0x80e1, 0x3c28
ax_pose_terminator
sHoOhPose19:
ax_pose 11, 0x01c6, 0xc0e0, 0x3c00
ax_pose_terminator
sHoOhPose20:
ax_pose 13, 0x41ce, 0xc0e0, 0x3c00
ax_pose 12, 0x41ee, 0x80e0, 0x3c20
ax_pose 14, 0x41ee, 0x8100, 0x3c28
ax_pose_terminator
sHoOhPose21:
ax_pose 15, 0x81c6, 0xc100, 0x3c00
ax_pose 16, 0x01d6, 0x80e0, 0x3c20
ax_pose 17, 0x01f6, 0x40f0, 0x3c30
ax_pose_terminator
sHoOhPose22:
ax_pose 8, 0x01c6, 0xc0e4, 0x3c00
ax_pose_terminator
sHoOhPose23:
ax_pose 9, 0x01c6, 0xc0e2, 0x3c00
ax_pose_terminator
sHoOhPose24:
ax_pose 10, 0x01c6, 0xc0e8, 0x3c00
ax_pose_terminator
sHoOhPose25:
ax_pose 0, 0x01c6, 0xc0e4, 0x3c00
ax_pose_terminator
sHoOhPose26:
ax_pose 1, 0x41c9, 0x40f0, 0x3c00
ax_pose 2, 0x41d1, 0x80e0, 0x3c04
ax_pose 3, 0x41d1, 0x8100, 0x3c0c
ax_pose 4, 0x01de, 0x00d8, 0x3c14
ax_pose 5, 0x01de, 0x0120, 0x3c15
ax_pose 6, 0x41e1, 0xc0e0, 0x3c16
ax_pose_terminator
sHoOhPose27:
ax_pose 7, 0x01cd, 0xc0e8, 0x3c00
ax_pose_terminator
sHoOhPose28:
ax_pose 8, 0x01c6, 0xd0db, 0x3c00
ax_pose_terminator
sHoOhPose29:
ax_pose 9, 0x01c6, 0xd0dd, 0x3c00
ax_pose_terminator
sHoOhPose30:
ax_pose 10, 0x01c6, 0xd0d7, 0x3c00
ax_pose_terminator
sHoOhPose31:
ax_pose 11, 0x01c6, 0xd0df, 0x3c00
ax_pose_terminator
sHoOhPose32:
ax_pose 12, 0x41ee, 0x90ff, 0x3c00
ax_pose 13, 0x41ce, 0xd0df, 0x3c08
ax_pose 14, 0x41ee, 0x90df, 0x3c28
ax_pose_terminator
sHoOhPose33:
ax_pose 15, 0x81c6, 0xd0df, 0x3c00
ax_pose 16, 0x01d6, 0x90ff, 0x3c20
ax_pose 17, 0x01f6, 0x50ff, 0x3c30
ax_pose_terminator
sHoOhPose34:
ax_pose 18, 0x01c6, 0xd0df, 0x3c00
ax_pose_terminator
sHoOhPose35:
ax_pose 19, 0x01e2, 0x111f, 0x3c00
ax_pose 20, 0x01c6, 0x90df, 0x3c01
ax_pose 21, 0x41d6, 0x90ff, 0x3c11
ax_pose 22, 0x41e6, 0xd0df, 0x3c19
ax_pose_terminator
sHoOhPose36:
ax_pose 23, 0x41d6, 0x90df, 0x3c00
ax_pose 24, 0x41d6, 0x90ff, 0x3c08
ax_pose 25, 0x41e6, 0xd0df, 0x3c10
ax_pose_terminator
sHoOhPose37:
ax_pose 26, 0x01c6, 0xc0e4, 0x3c00
ax_pose_terminator
sHoOhPose38:
ax_pose 27, 0x01de, 0x0120, 0x3c00
ax_pose 28, 0x81db, 0x00d8, 0x3c01
ax_pose 29, 0x41d6, 0x8100, 0x3c03
ax_pose 30, 0x41d6, 0x80e0, 0x3c0b
ax_pose 31, 0x41e6, 0xc0e0, 0x3c13
ax_pose_terminator
sHoOhPose39:
ax_pose 32, 0x01d0, 0x00fc, 0x3c00
ax_pose 33, 0x01d8, 0x4104, 0x3c01
ax_pose 34, 0x41d8, 0x80e4, 0x3c05
ax_pose 35, 0x41e8, 0xc0e4, 0x3c0d
ax_pose_terminator
sHoOhPose40:
ax_pose 18, 0x01c6, 0xc0e0, 0x3c00
ax_pose_terminator
sHoOhPose41:
ax_pose 22, 0x41e6, 0xc0e0, 0x3c00
ax_pose 21, 0x41d6, 0x80e0, 0x3c20
ax_pose 20, 0x01c6, 0x8100, 0x3c28
ax_pose 19, 0x01e2, 0x00d8, 0x3c38
ax_pose_terminator
sHoOhPose42:
ax_pose 25, 0x41e6, 0xc0e1, 0x3c00
ax_pose 23, 0x41d6, 0x8101, 0x3c20
ax_pose 24, 0x41d6, 0x80e1, 0x3c28
ax_pose_terminator
sHoOhPose43:
ax_pose 11, 0x01c6, 0xc0e0, 0x3c00
ax_pose_terminator
sHoOhPose44:
ax_pose 13, 0x41ce, 0xc0e0, 0x3c00
ax_pose 12, 0x41ee, 0x80e0, 0x3c20
ax_pose 14, 0x41ee, 0x8100, 0x3c28
ax_pose_terminator
sHoOhPose45:
ax_pose 15, 0x81c6, 0xc100, 0x3c00
ax_pose 16, 0x01d6, 0x80e0, 0x3c20
ax_pose 17, 0x01f6, 0x40f0, 0x3c30
ax_pose_terminator
sHoOhPose46:
ax_pose 8, 0x01c6, 0xc0e4, 0x3c00
ax_pose_terminator
sHoOhPose47:
ax_pose 9, 0x01c6, 0xc0e2, 0x3c00
ax_pose_terminator
sHoOhPose48:
ax_pose 10, 0x01c6, 0xc0e8, 0x3c00
ax_pose_terminator
sHoOhPose49:
ax_pose 0, 0x01c6, 0xc0e4, 0x3c00
ax_pose_terminator
sHoOhPose50:
ax_pose 1, 0x41c9, 0x40f0, 0x3c00
ax_pose 2, 0x41d1, 0x80e0, 0x3c04
ax_pose 3, 0x41d1, 0x8100, 0x3c0c
ax_pose 4, 0x01de, 0x00d8, 0x3c14
ax_pose 5, 0x01de, 0x0120, 0x3c15
ax_pose 6, 0x41e1, 0xc0e0, 0x3c16
ax_pose_terminator
sHoOhPose51:
ax_pose 7, 0x01cd, 0xc0e8, 0x3c00
ax_pose_terminator
sHoOhPose52:
ax_pose 36, 0x81c9, 0xc0f0, 0x3c00
ax_pose 37, 0x41e3, 0x80d0, 0x3c20
ax_pose -1, 0x41e3, 0x910f, 0x3c20
ax_pose_terminator
sHoOhPose53:
ax_pose 8, 0x01c6, 0xd0db, 0x3c00
ax_pose_terminator
sHoOhPose54:
ax_pose 9, 0x01c6, 0xd0dd, 0x3c00
ax_pose_terminator
sHoOhPose55:
ax_pose 10, 0x01c6, 0xd0d7, 0x3c00
ax_pose_terminator
sHoOhPose56:
ax_pose 38, 0x41d0, 0xd0dd, 0x3c00
ax_pose 39, 0x41f0, 0x90fe, 0x3c20
ax_pose 40, 0x41f0, 0x90de, 0x3c28
ax_pose 41, 0x0200, 0x1112, 0x3c30
ax_pose 42, 0x01f5, 0x10d6, 0x3c31
ax_pose_terminator
sHoOhPose57:
ax_pose 11, 0x01c6, 0xd0df, 0x3c00
ax_pose_terminator
sHoOhPose58:
ax_pose 12, 0x41ee, 0x90ff, 0x3c00
ax_pose 13, 0x41ce, 0xd0df, 0x3c08
ax_pose 14, 0x41ee, 0x90df, 0x3c28
ax_pose_terminator
sHoOhPose59:
ax_pose 15, 0x81c6, 0xd0df, 0x3c00
ax_pose 16, 0x01d6, 0x90ff, 0x3c20
ax_pose 17, 0x01f6, 0x50ff, 0x3c30
ax_pose_terminator
sHoOhPose60:
ax_pose 43, 0x41d8, 0xd0df, 0x3c00
ax_pose 44, 0x01f8, 0x50f5, 0x3c20
ax_pose_terminator
sHoOhPose61:
ax_pose 18, 0x01c6, 0xd0df, 0x3c00
ax_pose_terminator
sHoOhPose62:
ax_pose 19, 0x01e2, 0x111f, 0x3c00
ax_pose 20, 0x01c6, 0x90df, 0x3c01
ax_pose 21, 0x41d6, 0x90ff, 0x3c11
ax_pose 22, 0x41e6, 0xd0df, 0x3c19
ax_pose_terminator
sHoOhPose63:
ax_pose 23, 0x41d6, 0x90df, 0x3c00
ax_pose 24, 0x41d6, 0x90ff, 0x3c08
ax_pose 25, 0x41e6, 0xd0df, 0x3c10
ax_pose_terminator
sHoOhPose64:
ax_pose 45, 0x41d8, 0xd0df, 0x3c00
ax_pose 46, 0x41f8, 0x50ff, 0x3c20
ax_pose 47, 0x41f8, 0x90df, 0x3c24
ax_pose_terminator
sHoOhPose65:
ax_pose 26, 0x01c6, 0xc0e4, 0x3c00
ax_pose_terminator
sHoOhPose66:
ax_pose 27, 0x01de, 0x0120, 0x3c00
ax_pose 28, 0x81db, 0x00d8, 0x3c01
ax_pose 29, 0x41d6, 0x8100, 0x3c03
ax_pose 30, 0x41d6, 0x80e0, 0x3c0b
ax_pose 31, 0x41e6, 0xc0e0, 0x3c13
ax_pose_terminator
sHoOhPose67:
ax_pose 32, 0x01d0, 0x00fc, 0x3c00
ax_pose 33, 0x01d8, 0x4104, 0x3c01
ax_pose 34, 0x41d8, 0x80e4, 0x3c05
ax_pose 35, 0x41e8, 0xc0e4, 0x3c0d
ax_pose_terminator
sHoOhPose68:
ax_pose 48, 0x81ce, 0xc0f4, 0x3c00
ax_pose 49, 0x81ee, 0x40ec, 0x3c20
ax_pose 50, 0x41e3, 0x80d4, 0x3c24
ax_pose -1, 0x41e3, 0x910b, 0x3c24
ax_pose_terminator
sHoOhPose69:
ax_pose 18, 0x01c6, 0xc0e0, 0x3c00
ax_pose_terminator
sHoOhPose70:
ax_pose 22, 0x41e6, 0xc0e0, 0x3c00
ax_pose 21, 0x41d6, 0x80e0, 0x3c20
ax_pose 20, 0x01c6, 0x8100, 0x3c28
ax_pose 19, 0x01e2, 0x00d8, 0x3c38
ax_pose_terminator
sHoOhPose71:
ax_pose 25, 0x41e6, 0xc0e1, 0x3c00
ax_pose 23, 0x41d6, 0x8101, 0x3c20
ax_pose 24, 0x41d6, 0x80e1, 0x3c28
ax_pose_terminator
sHoOhPose72:
ax_pose 45, 0x41d8, 0xc0e1, 0x3c00
ax_pose 46, 0x41f8, 0x40e1, 0x3c20
ax_pose 47, 0x41f8, 0x8101, 0x3c24
ax_pose_terminator
sHoOhPose73:
ax_pose 11, 0x01c6, 0xc0e0, 0x3c00
ax_pose_terminator
sHoOhPose74:
ax_pose 13, 0x41ce, 0xc0e0, 0x3c00
ax_pose 12, 0x41ee, 0x80e0, 0x3c20
ax_pose 14, 0x41ee, 0x8100, 0x3c28
ax_pose_terminator
sHoOhPose75:
ax_pose 15, 0x81c6, 0xc100, 0x3c00
ax_pose 16, 0x01d6, 0x80e0, 0x3c20
ax_pose 17, 0x01f6, 0x40f0, 0x3c30
ax_pose_terminator
sHoOhPose76:
ax_pose 43, 0x41d8, 0xc0e1, 0x3c00
ax_pose 44, 0x01f8, 0x40fb, 0x3c20
ax_pose_terminator
sHoOhPose77:
ax_pose 8, 0x01c6, 0xc0e4, 0x3c00
ax_pose_terminator
sHoOhPose78:
ax_pose 9, 0x01c6, 0xc0e2, 0x3c00
ax_pose_terminator
sHoOhPose79:
ax_pose 10, 0x01c6, 0xc0e8, 0x3c00
ax_pose_terminator
sHoOhPose80:
ax_pose 38, 0x41d0, 0xc0e3, 0x3c00
ax_pose 39, 0x41f0, 0x80e2, 0x3c20
ax_pose 40, 0x41f0, 0x8102, 0x3c28
ax_pose 41, 0x0200, 0x00e6, 0x3c30
ax_pose 42, 0x01f5, 0x0122, 0x3c31
ax_pose_terminator
sHoOhPose81:
ax_pose 0, 0x01c6, 0xc0e4, 0x3c00
ax_pose_terminator
sHoOhPose82:
ax_pose 1, 0x41c9, 0x40f0, 0x3c00
ax_pose 2, 0x41d1, 0x80e0, 0x3c04
ax_pose 3, 0x41d1, 0x8100, 0x3c0c
ax_pose 4, 0x01de, 0x00d8, 0x3c14
ax_pose 5, 0x01de, 0x0120, 0x3c15
ax_pose 6, 0x41e1, 0xc0e0, 0x3c16
ax_pose_terminator
sHoOhPose83:
ax_pose 7, 0x01cd, 0xc0e8, 0x3c00
ax_pose_terminator
sHoOhPose84:
ax_pose 51, 0x41d8, 0xc0e0, 0x3c00
ax_pose_terminator
sHoOhPose85:
ax_pose 52, 0x01c6, 0x80e4, 0x3c00
ax_pose -1, 0x01c6, 0x90fb, 0x3c00
ax_pose 53, 0x81e6, 0x80e4, 0x3c10
ax_pose 54, 0x81e6, 0x40f4, 0x3c18
ax_pose 55, 0x81e6, 0x40fc, 0x3c1c
ax_pose -1, 0x81e6, 0x910b, 0x3c10
ax_pose -1, 0x81e6, 0x5103, 0x3c18
ax_pose_terminator
sHoOhPose86:
ax_pose 8, 0x01c6, 0xd0db, 0x3c00
ax_pose_terminator
sHoOhPose87:
ax_pose 9, 0x01c6, 0xd0dd, 0x3c00
ax_pose_terminator
sHoOhPose88:
ax_pose 10, 0x01c6, 0xd0d7, 0x3c00
ax_pose_terminator
sHoOhPose89:
ax_pose 56, 0x41d4, 0xd0db, 0x3c00
ax_pose 57, 0x41f4, 0x50eb, 0x3c20
ax_pose_terminator
sHoOhPose90:
ax_pose 58, 0x01c6, 0xd0db, 0x3c00
ax_pose_terminator
sHoOhPose91:
ax_pose 11, 0x01c6, 0xd0df, 0x3c00
ax_pose_terminator
sHoOhPose92:
ax_pose 12, 0x41ee, 0x90ff, 0x3c00
ax_pose 13, 0x41ce, 0xd0df, 0x3c08
ax_pose 14, 0x41ee, 0x90df, 0x3c28
ax_pose_terminator
sHoOhPose93:
ax_pose 15, 0x81c6, 0xd0df, 0x3c00
ax_pose 16, 0x01d6, 0x90ff, 0x3c20
ax_pose 17, 0x01f6, 0x50ff, 0x3c30
ax_pose_terminator
sHoOhPose94:
ax_pose 59, 0x41d1, 0xd0df, 0x3c00
ax_pose 60, 0x41f1, 0x90df, 0x3c20
ax_pose 61, 0x41f1, 0x50ff, 0x3c28
ax_pose_terminator
sHoOhPose95:
ax_pose 62, 0x01c6, 0xd0df, 0x3c00
ax_pose_terminator
sHoOhPose96:
ax_pose 18, 0x01c6, 0xd0df, 0x3c00
ax_pose_terminator
sHoOhPose97:
ax_pose 19, 0x01e2, 0x111f, 0x3c00
ax_pose 20, 0x01c6, 0x90df, 0x3c01
ax_pose 21, 0x41d6, 0x90ff, 0x3c11
ax_pose 22, 0x41e6, 0xd0df, 0x3c19
ax_pose_terminator
sHoOhPose98:
ax_pose 23, 0x41d6, 0x90df, 0x3c00
ax_pose 24, 0x41d6, 0x90ff, 0x3c08
ax_pose 25, 0x41e6, 0xd0df, 0x3c10
ax_pose_terminator
sHoOhPose99:
ax_pose 63, 0x01c6, 0xd0df, 0x3c00
ax_pose_terminator
sHoOhPose100:
ax_pose 64, 0x01c6, 0xd0df, 0x3c00
ax_pose_terminator
sHoOhPose101:
ax_pose 26, 0x01c6, 0xc0e4, 0x3c00
ax_pose_terminator
sHoOhPose102:
ax_pose 27, 0x01de, 0x0120, 0x3c00
ax_pose 28, 0x81db, 0x00d8, 0x3c01
ax_pose 29, 0x41d6, 0x8100, 0x3c03
ax_pose 30, 0x41d6, 0x80e0, 0x3c0b
ax_pose 31, 0x41e6, 0xc0e0, 0x3c13
ax_pose_terminator
sHoOhPose103:
ax_pose 32, 0x01d0, 0x00fc, 0x3c00
ax_pose 33, 0x01d8, 0x4104, 0x3c01
ax_pose 34, 0x41d8, 0x80e4, 0x3c05
ax_pose 35, 0x41e8, 0xc0e4, 0x3c0d
ax_pose_terminator
sHoOhPose104:
ax_pose 65, 0x01cc, 0xc0e4, 0x3c00
ax_pose_terminator
sHoOhPose105:
ax_pose 66, 0x01c6, 0xc0e4, 0x3c00
ax_pose_terminator
sHoOhPose106:
ax_pose 18, 0x01c6, 0xc0e0, 0x3c00
ax_pose_terminator
sHoOhPose107:
ax_pose 22, 0x41e6, 0xc0e0, 0x3c00
ax_pose 21, 0x41d6, 0x80e0, 0x3c20
ax_pose 20, 0x01c6, 0x8100, 0x3c28
ax_pose 19, 0x01e2, 0x00d8, 0x3c38
ax_pose_terminator
sHoOhPose108:
ax_pose 25, 0x41e6, 0xc0e1, 0x3c00
ax_pose 23, 0x41d6, 0x8101, 0x3c20
ax_pose 24, 0x41d6, 0x80e1, 0x3c28
ax_pose_terminator
sHoOhPose109:
ax_pose 63, 0x01c6, 0xc0e0, 0x3c00
ax_pose_terminator
sHoOhPose110:
ax_pose 64, 0x01c6, 0xc0e0, 0x3c00
ax_pose_terminator
sHoOhPose111:
ax_pose 11, 0x01c6, 0xc0e0, 0x3c00
ax_pose_terminator
sHoOhPose112:
ax_pose 13, 0x41ce, 0xc0e0, 0x3c00
ax_pose 12, 0x41ee, 0x80e0, 0x3c20
ax_pose 14, 0x41ee, 0x8100, 0x3c28
ax_pose_terminator
sHoOhPose113:
ax_pose 15, 0x81c6, 0xc100, 0x3c00
ax_pose 16, 0x01d6, 0x80e0, 0x3c20
ax_pose 17, 0x01f6, 0x40f0, 0x3c30
ax_pose_terminator
sHoOhPose114:
ax_pose 59, 0x41d1, 0xc0e1, 0x3c00
ax_pose 60, 0x41f1, 0x8101, 0x3c20
ax_pose 61, 0x41f1, 0x40e1, 0x3c28
ax_pose_terminator
sHoOhPose115:
ax_pose 62, 0x01c6, 0xc0e0, 0x3c00
ax_pose_terminator
sHoOhPose116:
ax_pose 8, 0x01c6, 0xc0e4, 0x3c00
ax_pose_terminator
sHoOhPose117:
ax_pose 9, 0x01c6, 0xc0e2, 0x3c00
ax_pose_terminator
sHoOhPose118:
ax_pose 10, 0x01c6, 0xc0e8, 0x3c00
ax_pose_terminator
sHoOhPose119:
ax_pose 56, 0x41d4, 0xc0e5, 0x3c00
ax_pose 57, 0x41f4, 0x40f5, 0x3c20
ax_pose_terminator
sHoOhPose120:
ax_pose 58, 0x01c6, 0xc0e4, 0x3c00
ax_pose_terminator
sHoOhPose121:
ax_pose 0, 0x01c6, 0xc0e4, 0x3c00
ax_pose_terminator
sHoOhPose122:
ax_pose 1, 0x41c9, 0x40f0, 0x3c00
ax_pose 2, 0x41d1, 0x80e0, 0x3c04
ax_pose 3, 0x41d1, 0x8100, 0x3c0c
ax_pose 4, 0x01de, 0x00d8, 0x3c14
ax_pose 5, 0x01de, 0x0120, 0x3c15
ax_pose 6, 0x41e1, 0xc0e0, 0x3c16
ax_pose_terminator
sHoOhPose123:
ax_pose 7, 0x01cd, 0xc0e8, 0x3c00
ax_pose_terminator
sHoOhPose124:
ax_pose 8, 0x01c6, 0xd0db, 0x3c00
ax_pose_terminator
sHoOhPose125:
ax_pose 9, 0x01c6, 0xd0dd, 0x3c00
ax_pose_terminator
sHoOhPose126:
ax_pose 10, 0x01c6, 0xd0d7, 0x3c00
ax_pose_terminator
sHoOhPose127:
ax_pose 11, 0x01c6, 0xd0df, 0x3c00
ax_pose_terminator
sHoOhPose128:
ax_pose 12, 0x41ee, 0x90ff, 0x3c00
ax_pose 13, 0x41ce, 0xd0df, 0x3c08
ax_pose 14, 0x41ee, 0x90df, 0x3c28
ax_pose_terminator
sHoOhPose129:
ax_pose 15, 0x81c6, 0xd0df, 0x3c00
ax_pose 16, 0x01d6, 0x90ff, 0x3c20
ax_pose 17, 0x01f6, 0x50ff, 0x3c30
ax_pose_terminator
sHoOhPose130:
ax_pose 18, 0x01c6, 0xd0df, 0x3c00
ax_pose_terminator
sHoOhPose131:
ax_pose 19, 0x01e2, 0x111f, 0x3c00
ax_pose 20, 0x01c6, 0x90df, 0x3c01
ax_pose 21, 0x41d6, 0x90ff, 0x3c11
ax_pose 22, 0x41e6, 0xd0df, 0x3c19
ax_pose_terminator
sHoOhPose132:
ax_pose 23, 0x41d6, 0x90df, 0x3c00
ax_pose 24, 0x41d6, 0x90ff, 0x3c08
ax_pose 25, 0x41e6, 0xd0df, 0x3c10
ax_pose_terminator
sHoOhPose133:
ax_pose 26, 0x01c6, 0xc0e4, 0x3c00
ax_pose_terminator
sHoOhPose134:
ax_pose 27, 0x01de, 0x0120, 0x3c00
ax_pose 28, 0x81db, 0x00d8, 0x3c01
ax_pose 29, 0x41d6, 0x8100, 0x3c03
ax_pose 30, 0x41d6, 0x80e0, 0x3c0b
ax_pose 31, 0x41e6, 0xc0e0, 0x3c13
ax_pose_terminator
sHoOhPose135:
ax_pose 32, 0x01d0, 0x00fc, 0x3c00
ax_pose 33, 0x01d8, 0x4104, 0x3c01
ax_pose 34, 0x41d8, 0x80e4, 0x3c05
ax_pose 35, 0x41e8, 0xc0e4, 0x3c0d
ax_pose_terminator
sHoOhPose136:
ax_pose 18, 0x01c6, 0xc0e0, 0x3c00
ax_pose_terminator
sHoOhPose137:
ax_pose 22, 0x41e6, 0xc0e0, 0x3c00
ax_pose 21, 0x41d6, 0x80e0, 0x3c20
ax_pose 20, 0x01c6, 0x8100, 0x3c28
ax_pose 19, 0x01e2, 0x00d8, 0x3c38
ax_pose_terminator
sHoOhPose138:
ax_pose 25, 0x41e6, 0xc0e1, 0x3c00
ax_pose 23, 0x41d6, 0x8101, 0x3c20
ax_pose 24, 0x41d6, 0x80e1, 0x3c28
ax_pose_terminator
sHoOhPose139:
ax_pose 11, 0x01c6, 0xc0e0, 0x3c00
ax_pose_terminator
sHoOhPose140:
ax_pose 13, 0x41ce, 0xc0e0, 0x3c00
ax_pose 12, 0x41ee, 0x80e0, 0x3c20
ax_pose 14, 0x41ee, 0x8100, 0x3c28
ax_pose_terminator
sHoOhPose141:
ax_pose 15, 0x81c6, 0xc100, 0x3c00
ax_pose 16, 0x01d6, 0x80e0, 0x3c20
ax_pose 17, 0x01f6, 0x40f0, 0x3c30
ax_pose_terminator
sHoOhPose142:
ax_pose 8, 0x01c6, 0xc0e4, 0x3c00
ax_pose_terminator
sHoOhPose143:
ax_pose 9, 0x01c6, 0xc0e2, 0x3c00
ax_pose_terminator
sHoOhPose144:
ax_pose 10, 0x01c6, 0xc0e8, 0x3c00
ax_pose_terminator
sHoOhPose145:
ax_pose 67, 0x01e0, 0x80fe, 0x3c00
ax_pose 68, 0x41f7, 0x80de, 0x3c10
ax_pose 69, 0x41ef, 0x40de, 0x3c18
ax_pose 70, 0x01e7, 0x00f6, 0x3c1c
ax_pose 71, 0x0200, 0x00fe, 0x3c1d
ax_pose 72, 0x4200, 0x0106, 0x3c1e
ax_pose_terminator
sHoOhPose146:
ax_pose 73, 0x01e0, 0x80fe, 0x3c00
ax_pose 74, 0x81e9, 0x80ee, 0x3c10
ax_pose 75, 0x01f1, 0x00e6, 0x3c18
ax_pose 76, 0x81f9, 0x00e6, 0x3c19
ax_pose 77, 0x0200, 0x00fe, 0x3c1b
ax_pose 78, 0x0200, 0x010a, 0x3c1c
ax_pose_terminator
sHoOhPose147:
ax_pose 79, 0x01c2, 0xc0e1, 0x3c00
ax_pose_terminator
sHoOhPose148:
ax_pose 80, 0x01c2, 0xd0d4, 0x3c00
ax_pose_terminator
sHoOhPose149:
ax_pose 81, 0x01c7, 0xd0da, 0x3c00
ax_pose_terminator
sHoOhPose150:
ax_pose 82, 0x01c3, 0xd0dd, 0x3c00
ax_pose_terminator
sHoOhPose151:
ax_pose 83, 0x01c3, 0xc0e1, 0x3c00
ax_pose_terminator
sHoOhPose152:
ax_pose 82, 0x01c3, 0xc0e3, 0x3c00
ax_pose_terminator
sHoOhPose153:
ax_pose 81, 0x01c7, 0xc0e5, 0x3c00
ax_pose_terminator
sHoOhPose154:
ax_pose 80, 0x01c2, 0xc0ec, 0x3c00
ax_pose_terminator
sHoOhPose155:
ax_pose 0, 0x01c6, 0xc0e4, 0x3c00
ax_pose_terminator
sHoOhPose156:
ax_pose 1, 0x41c9, 0x40f0, 0x3c00
ax_pose 2, 0x41d1, 0x80e0, 0x3c04
ax_pose 3, 0x41d1, 0x8100, 0x3c0c
ax_pose 4, 0x01de, 0x00d8, 0x3c14
ax_pose 5, 0x01de, 0x0120, 0x3c15
ax_pose 6, 0x41e1, 0xc0e0, 0x3c16
ax_pose_terminator
sHoOhPose157:
ax_pose 7, 0x01cd, 0xc0e8, 0x3c00
ax_pose_terminator
sHoOhPose158:
ax_pose 8, 0x01c6, 0xd0db, 0x3c00
ax_pose_terminator
sHoOhPose159:
ax_pose 9, 0x01c6, 0xd0dd, 0x3c00
ax_pose_terminator
sHoOhPose160:
ax_pose 10, 0x01c6, 0xd0d7, 0x3c00
ax_pose_terminator
sHoOhPose161:
ax_pose 11, 0x01c6, 0xd0df, 0x3c00
ax_pose_terminator
sHoOhPose162:
ax_pose 12, 0x41ee, 0x90ff, 0x3c00
ax_pose 13, 0x41ce, 0xd0df, 0x3c08
ax_pose 14, 0x41ee, 0x90df, 0x3c28
ax_pose_terminator
sHoOhPose163:
ax_pose 15, 0x81c6, 0xd0df, 0x3c00
ax_pose 16, 0x01d6, 0x90ff, 0x3c20
ax_pose 17, 0x01f6, 0x50ff, 0x3c30
ax_pose_terminator
sHoOhPose164:
ax_pose 18, 0x01c6, 0xd0df, 0x3c00
ax_pose_terminator
sHoOhPose165:
ax_pose 19, 0x01e2, 0x111f, 0x3c00
ax_pose 20, 0x01c6, 0x90df, 0x3c01
ax_pose 21, 0x41d6, 0x90ff, 0x3c11
ax_pose 22, 0x41e6, 0xd0df, 0x3c19
ax_pose_terminator
sHoOhPose166:
ax_pose 23, 0x41d6, 0x90df, 0x3c00
ax_pose 24, 0x41d6, 0x90ff, 0x3c08
ax_pose 25, 0x41e6, 0xd0df, 0x3c10
ax_pose_terminator
sHoOhPose167:
ax_pose 26, 0x01c6, 0xc0e4, 0x3c00
ax_pose_terminator
sHoOhPose168:
ax_pose 27, 0x01de, 0x0120, 0x3c00
ax_pose 28, 0x81db, 0x00d8, 0x3c01
ax_pose 29, 0x41d6, 0x8100, 0x3c03
ax_pose 30, 0x41d6, 0x80e0, 0x3c0b
ax_pose 31, 0x41e6, 0xc0e0, 0x3c13
ax_pose_terminator
sHoOhPose169:
ax_pose 32, 0x01d0, 0x00fc, 0x3c00
ax_pose 33, 0x01d8, 0x4104, 0x3c01
ax_pose 34, 0x41d8, 0x80e4, 0x3c05
ax_pose 35, 0x41e8, 0xc0e4, 0x3c0d
ax_pose_terminator
sHoOhPose170:
ax_pose 18, 0x01c6, 0xc0e0, 0x3c00
ax_pose_terminator
sHoOhPose171:
ax_pose 22, 0x41e6, 0xc0e0, 0x3c00
ax_pose 21, 0x41d6, 0x80e0, 0x3c20
ax_pose 20, 0x01c6, 0x8100, 0x3c28
ax_pose 19, 0x01e2, 0x00d8, 0x3c38
ax_pose_terminator
sHoOhPose172:
ax_pose 25, 0x41e6, 0xc0e1, 0x3c00
ax_pose 23, 0x41d6, 0x8101, 0x3c20
ax_pose 24, 0x41d6, 0x80e1, 0x3c28
ax_pose_terminator
sHoOhPose173:
ax_pose 11, 0x01c6, 0xc0e0, 0x3c00
ax_pose_terminator
sHoOhPose174:
ax_pose 13, 0x41ce, 0xc0e0, 0x3c00
ax_pose 12, 0x41ee, 0x80e0, 0x3c20
ax_pose 14, 0x41ee, 0x8100, 0x3c28
ax_pose_terminator
sHoOhPose175:
ax_pose 15, 0x81c6, 0xc100, 0x3c00
ax_pose 16, 0x01d6, 0x80e0, 0x3c20
ax_pose 17, 0x01f6, 0x40f0, 0x3c30
ax_pose_terminator
sHoOhPose176:
ax_pose 8, 0x01c6, 0xc0e4, 0x3c00
ax_pose_terminator
sHoOhPose177:
ax_pose 9, 0x01c6, 0xc0e2, 0x3c00
ax_pose_terminator
sHoOhPose178:
ax_pose 10, 0x01c6, 0xc0e8, 0x3c00
ax_pose_terminator
sHoOhPose179:
ax_pose 0, 0x01c6, 0xc0e4, 0x3c00
ax_pose_terminator
sHoOhPose180:
ax_pose 8, 0x01c6, 0xc0e4, 0x3c00
ax_pose_terminator
sHoOhPose181:
ax_pose 11, 0x01c6, 0xc0e0, 0x3c00
ax_pose_terminator
sHoOhPose182:
ax_pose 18, 0x01c6, 0xc0e0, 0x3c00
ax_pose_terminator
sHoOhPose183:
ax_pose 26, 0x01c6, 0xc0e4, 0x3c00
ax_pose_terminator
sHoOhPose184:
ax_pose 18, 0x01c6, 0xd0df, 0x3c00
ax_pose_terminator
sHoOhPose185:
ax_pose 11, 0x01c6, 0xd0df, 0x3c00
ax_pose_terminator
sHoOhPose186:
ax_pose 8, 0x01c6, 0xd0db, 0x3c00
ax_pose_terminator
sHoOhPose187:
ax_pose 52, 0x01c6, 0x80e4, 0x3c00
ax_pose -1, 0x01c6, 0x90fb, 0x3c00
ax_pose 53, 0x81e6, 0x80e4, 0x3c10
ax_pose 54, 0x81e6, 0x40f4, 0x3c18
ax_pose 55, 0x81e6, 0x40fc, 0x3c1c
ax_pose -1, 0x81e6, 0x910b, 0x3c10
ax_pose -1, 0x81e6, 0x5103, 0x3c18
ax_pose_terminator
sHoOhPose188:
ax_pose 58, 0x01c6, 0xd0db, 0x3c00
ax_pose_terminator
sHoOhPose189:
ax_pose 62, 0x01c6, 0xd0df, 0x3c00
ax_pose_terminator
sHoOhPose190:
ax_pose 64, 0x01c6, 0xd0df, 0x3c00
ax_pose_terminator
sHoOhPose191:
ax_pose 66, 0x01c6, 0xc0e4, 0x3c00
ax_pose_terminator
sHoOhPose192:
ax_pose 64, 0x01c6, 0xc0e0, 0x3c00
ax_pose_terminator
sHoOhPose193:
ax_pose 62, 0x01c6, 0xc0e0, 0x3c00
ax_pose_terminator
sHoOhPose194:
ax_pose 58, 0x01c6, 0xc0e4, 0x3c00
ax_pose_terminator
sHoOhPose195:
ax_pose 0, 0x01c6, 0xc0e4, 0x3c00
ax_pose_terminator
sHoOhPose196:
ax_pose 1, 0x41c9, 0x40f0, 0x3c00
ax_pose 2, 0x41d1, 0x80e0, 0x3c04
ax_pose 3, 0x41d1, 0x8100, 0x3c0c
ax_pose 4, 0x01de, 0x00d8, 0x3c14
ax_pose 5, 0x01de, 0x0120, 0x3c15
ax_pose 6, 0x41e1, 0xc0e0, 0x3c16
ax_pose_terminator
sHoOhPose197:
ax_pose 7, 0x01cd, 0xc0e8, 0x3c00
ax_pose_terminator
sHoOhPose198:
ax_pose 51, 0x41da, 0xc0e0, 0x3c00
ax_pose_terminator
sHoOhPose199:
ax_pose 8, 0x01c6, 0xd0db, 0x3c00
ax_pose_terminator
sHoOhPose200:
ax_pose 9, 0x01c6, 0xd0dd, 0x3c00
ax_pose_terminator
sHoOhPose201:
ax_pose 10, 0x01c6, 0xd0d7, 0x3c00
ax_pose_terminator
sHoOhPose202:
ax_pose 56, 0x41d6, 0xd0db, 0x3c00
ax_pose 57, 0x41f6, 0x50eb, 0x3c20
ax_pose_terminator
sHoOhPose203:
ax_pose 11, 0x01c6, 0xd0df, 0x3c00
ax_pose_terminator
sHoOhPose204:
ax_pose 12, 0x41ee, 0x90ff, 0x3c00
ax_pose 13, 0x41ce, 0xd0df, 0x3c08
ax_pose 14, 0x41ee, 0x90df, 0x3c28
ax_pose_terminator
sHoOhPose205:
ax_pose 15, 0x81c6, 0xd0df, 0x3c00
ax_pose 16, 0x01d6, 0x90ff, 0x3c20
ax_pose 17, 0x01f6, 0x50ff, 0x3c30
ax_pose_terminator
sHoOhPose206:
ax_pose 59, 0x41dc, 0xd0df, 0x3c00
ax_pose 60, 0x41fc, 0x90df, 0x3c20
ax_pose 61, 0x41fc, 0x50ff, 0x3c28
ax_pose_terminator
sHoOhPose207:
ax_pose 18, 0x01c6, 0xd0df, 0x3c00
ax_pose_terminator
sHoOhPose208:
ax_pose 19, 0x01e2, 0x111f, 0x3c00
ax_pose 20, 0x01c6, 0x90df, 0x3c01
ax_pose 21, 0x41d6, 0x90ff, 0x3c11
ax_pose 22, 0x41e6, 0xd0df, 0x3c19
ax_pose_terminator
sHoOhPose209:
ax_pose 23, 0x41d6, 0x90df, 0x3c00
ax_pose 24, 0x41d6, 0x90ff, 0x3c08
ax_pose 25, 0x41e6, 0xd0df, 0x3c10
ax_pose_terminator
sHoOhPose210:
ax_pose 63, 0x01d6, 0xd0df, 0x3c00
ax_pose_terminator
sHoOhPose211:
ax_pose 26, 0x01c6, 0xc0e4, 0x3c00
ax_pose_terminator
sHoOhPose212:
ax_pose 27, 0x01de, 0x0120, 0x3c00
ax_pose 28, 0x81db, 0x00d8, 0x3c01
ax_pose 29, 0x41d6, 0x8100, 0x3c03
ax_pose 30, 0x41d6, 0x80e0, 0x3c0b
ax_pose 31, 0x41e6, 0xc0e0, 0x3c13
ax_pose_terminator
sHoOhPose213:
ax_pose 32, 0x01d0, 0x00fc, 0x3c00
ax_pose 33, 0x01d8, 0x4104, 0x3c01
ax_pose 34, 0x41d8, 0x80e4, 0x3c05
ax_pose 35, 0x41e8, 0xc0e4, 0x3c0d
ax_pose_terminator
sHoOhPose214:
ax_pose 65, 0x01db, 0xc0e4, 0x3c00
ax_pose_terminator
sHoOhPose215:
ax_pose 18, 0x01c6, 0xc0e0, 0x3c00
ax_pose_terminator
sHoOhPose216:
ax_pose 22, 0x41e6, 0xc0e0, 0x3c00
ax_pose 21, 0x41d6, 0x80e0, 0x3c20
ax_pose 20, 0x01c6, 0x8100, 0x3c28
ax_pose 19, 0x01e2, 0x00d8, 0x3c38
ax_pose_terminator
sHoOhPose217:
ax_pose 25, 0x41e6, 0xc0e1, 0x3c00
ax_pose 23, 0x41d6, 0x8101, 0x3c20
ax_pose 24, 0x41d6, 0x80e1, 0x3c28
ax_pose_terminator
sHoOhPose218:
ax_pose 63, 0x01d6, 0xc0e1, 0x3c00
ax_pose_terminator
sHoOhPose219:
ax_pose 11, 0x01c6, 0xc0e0, 0x3c00
ax_pose_terminator
sHoOhPose220:
ax_pose 13, 0x41ce, 0xc0e0, 0x3c00
ax_pose 12, 0x41ee, 0x80e0, 0x3c20
ax_pose 14, 0x41ee, 0x8100, 0x3c28
ax_pose_terminator
sHoOhPose221:
ax_pose 15, 0x81c6, 0xc100, 0x3c00
ax_pose 16, 0x01d6, 0x80e0, 0x3c20
ax_pose 17, 0x01f6, 0x40f0, 0x3c30
ax_pose_terminator
sHoOhPose222:
ax_pose 59, 0x41dc, 0xc0e1, 0x3c00
ax_pose 60, 0x41fc, 0x8101, 0x3c20
ax_pose 61, 0x41fc, 0x40e1, 0x3c28
ax_pose_terminator
sHoOhPose223:
ax_pose 8, 0x01c6, 0xc0e5, 0x3c00
ax_pose_terminator
sHoOhPose224:
ax_pose 9, 0x01c6, 0xc0e3, 0x3c00
ax_pose_terminator
sHoOhPose225:
ax_pose 10, 0x01c6, 0xc0e9, 0x3c00
ax_pose_terminator
sHoOhPose226:
ax_pose 56, 0x41d6, 0xc0e5, 0x3c00
ax_pose 57, 0x41f6, 0x40f5, 0x3c20
ax_pose_terminator
sHoOhPose227:
ax_pose 52, 0x01c6, 0x80e4, 0x3c00
ax_pose -1, 0x01c6, 0x90fb, 0x3c00
ax_pose 53, 0x81e6, 0x80e4, 0x3c10
ax_pose 54, 0x81e6, 0x40f4, 0x3c18
ax_pose 55, 0x81e6, 0x40fc, 0x3c1c
ax_pose -1, 0x81e6, 0x910b, 0x3c10
ax_pose -1, 0x81e6, 0x5103, 0x3c18
ax_pose_terminator
sHoOhPose228:
ax_pose 58, 0x01c6, 0xd0db, 0x3c00
ax_pose_terminator
sHoOhPose229:
ax_pose 62, 0x01c6, 0xd0df, 0x3c00
ax_pose_terminator
sHoOhPose230:
ax_pose 64, 0x01c6, 0xd0df, 0x3c00
ax_pose_terminator
sHoOhPose231:
ax_pose 66, 0x01c6, 0xc0e4, 0x3c00
ax_pose_terminator
sHoOhPose232:
ax_pose 64, 0x01c6, 0xc0e0, 0x3c00
ax_pose_terminator
sHoOhPose233:
ax_pose 62, 0x01c6, 0xc0e0, 0x3c00
ax_pose_terminator
sHoOhPose234:
ax_pose 58, 0x01c6, 0xc0e4, 0x3c00
ax_pose_terminator
sHoOhPose235:
ax_pose 0, 0x01c6, 0xc0e4, 0x3c00
ax_pose_terminator
sHoOhPose236:
ax_pose 8, 0x01c6, 0xc0e4, 0x3c00
ax_pose_terminator
sHoOhPose237:
ax_pose 11, 0x01c6, 0xc0e0, 0x3c00
ax_pose_terminator
sHoOhPose238:
ax_pose 18, 0x01c6, 0xc0e0, 0x3c00
ax_pose_terminator
sHoOhPose239:
ax_pose 26, 0x01c6, 0xc0e4, 0x3c00
ax_pose_terminator
sHoOhPose240:
ax_pose 18, 0x01c6, 0xd0df, 0x3c00
ax_pose_terminator
sHoOhPose241:
ax_pose 11, 0x01c6, 0xd0df, 0x3c00
ax_pose_terminator
sHoOhPose242:
ax_pose 8, 0x01c6, 0xd0db, 0x3c00
ax_pose_terminator
.align 2
sHoOhAnims_1_1:
ax_anim 8, 0, 0, 0, 0, 0, 0,
ax_anim 6, 0, 1, 0, 0, 0, 0,
ax_anim 8, 0, 2, 0, 0, 0, 0,
ax_anim 6, 0, 2, 0, -1, 0, 0,
ax_anim 8, 0, 1, 0, 0, 0, 0,
ax_anim_terminator
sHoOhAnims_1_2:
ax_anim 8, 0, 3, 0, 0, 0, 0,
ax_anim 6, 0, 4, 0, 0, 0, 0,
ax_anim 8, 0, 5, 0, 0, 0, 0,
ax_anim 6, 0, 5, 0, -1, 0, 0,
ax_anim 8, 0, 4, 0, 0, 0, 0,
ax_anim_terminator
sHoOhAnims_1_3:
ax_anim 8, 0, 6, 0, 0, 0, 0,
ax_anim 6, 0, 7, 0, 0, 0, 0,
ax_anim 8, 0, 8, 0, 0, 0, 0,
ax_anim 6, 0, 8, 0, -1, 0, 0,
ax_anim 8, 0, 7, 0, 0, 0, 0,
ax_anim_terminator
sHoOhAnims_1_4:
ax_anim 8, 0, 9, 0, 0, 0, 0,
ax_anim 6, 0, 10, 0, 0, 0, 0,
ax_anim 8, 0, 11, 0, 0, 0, 0,
ax_anim 6, 0, 11, 0, -1, 0, 0,
ax_anim 8, 0, 10, 0, 0, 0, 0,
ax_anim_terminator
sHoOhAnims_1_5:
ax_anim 8, 0, 12, 0, 0, 0, 0,
ax_anim 6, 0, 13, 0, 0, 0, 0,
ax_anim 8, 0, 14, 0, 0, 0, 0,
ax_anim 6, 0, 14, 0, -1, 0, 0,
ax_anim 8, 0, 13, 0, 0, 0, 0,
ax_anim_terminator
sHoOhAnims_1_6:
ax_anim 8, 0, 15, 0, 0, 0, 0,
ax_anim 6, 0, 16, 0, 0, 0, 0,
ax_anim 8, 0, 17, 0, 0, 0, 0,
ax_anim 6, 0, 17, 0, -1, 0, 0,
ax_anim 8, 0, 16, 0, 0, 0, 0,
ax_anim_terminator
sHoOhAnims_1_7:
ax_anim 8, 0, 18, 0, 0, 0, 0,
ax_anim 6, 0, 19, 0, 0, 0, 0,
ax_anim 8, 0, 20, 0, 0, 0, 0,
ax_anim 6, 0, 20, 0, -1, 0, 0,
ax_anim 8, 0, 19, 0, 0, 0, 0,
ax_anim_terminator
sHoOhAnims_1_8:
ax_anim 8, 0, 21, 0, 0, 0, 0,
ax_anim 6, 0, 22, 0, 0, 0, 0,
ax_anim 8, 0, 23, 0, 0, 0, 0,
ax_anim 6, 0, 23, 0, -1, 0, 0,
ax_anim 8, 0, 22, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sHoOhAnims_2_1:
ax_anim 2, 0, 24, 0, -1, 0, -1,
ax_anim 2, 0, 24, 0, -3, 0, -3,
ax_anim 2, 0, 24, 0, -4, 0, -4,
ax_anim 2, 0, 25, 0, -4, 0, -4,
ax_anim 2, 0, 26, 0, -4, 0, -4,
ax_anim 2, 0, 25, 0, -4, 0, -4,
ax_anim 2, 0, 24, 0, -4, 0, -4,
ax_anim 1, 0, 25, 0, 0, 0, 0,
ax_anim 1, 2, 26, 0, 4, 0, 4,
ax_anim 1, 0, 25, 0, 10, 0, 10,
ax_anim 2, 0, 24, 0, 22, 0, 22,
ax_anim 2, 1, 24, 1, 22, 1, 22,
ax_anim 2, 0, 24, 0, 22, 0, 22,
ax_anim 2, 0, 24, 1, 22, 1, 22,
ax_anim 2, 0, 24, 0, 6, 0, 6,
ax_anim_terminator
sHoOhAnims_2_2:
ax_anim 2, 0, 27, -1, -1, -1, -1,
ax_anim 2, 0, 27, -3, -3, -3, -3,
ax_anim 2, 0, 27, -4, -4, -4, -4,
ax_anim 2, 0, 28, -4, -4, -4, -4,
ax_anim 2, 0, 29, -4, -4, -4, -4,
ax_anim 2, 0, 28, -4, -4, -4, -4,
ax_anim 2, 0, 27, -4, -4, -4, -4,
ax_anim 1, 0, 28, 0, 0, 0, 0,
ax_anim 1, 2, 29, 4, 7, 4, 5,
ax_anim 1, 0, 28, 10, 14, 10, 10,
ax_anim 2, 0, 27, 15, 22, 15, 18,
ax_anim 2, 1, 27, 16, 21, 16, 17,
ax_anim 2, 0, 27, 15, 22, 15, 18,
ax_anim 2, 0, 27, 16, 21, 16, 17,
ax_anim 2, 0, 27, 6, 6, 6, 6,
ax_anim_terminator
sHoOhAnims_2_3:
ax_anim 2, 0, 30, -1, 0, -1, 0,
ax_anim 2, 0, 30, -3, 0, -3, 0,
ax_anim 2, 0, 30, -4, 0, -4, 0,
ax_anim 2, 0, 31, -4, 0, -4, 0,
ax_anim 2, 0, 32, -4, 0, -4, 0,
ax_anim 2, 0, 31, -4, 0, -4, 0,
ax_anim 2, 0, 30, -4, 0, -4, 0,
ax_anim 1, 0, 31, 0, 0, 0, 0,
ax_anim 1, 2, 32, 4, 2, 4, 0,
ax_anim 1, 0, 31, 10, 4, 10, 0,
ax_anim 2, 0, 30, 15, 5, 15, 1,
ax_anim 2, 1, 30, 15, 4, 15, 0,
ax_anim 2, 0, 30, 15, 5, 15, 1,
ax_anim 2, 0, 30, 15, 4, 15, 0,
ax_anim 2, 0, 30, 6, 0, 6, 0,
ax_anim_terminator
sHoOhAnims_2_4:
ax_anim 2, 0, 33, -1, 1, -1, 1,
ax_anim 2, 0, 33, -3, 3, -3, 3,
ax_anim 2, 0, 33, -4, 4, -4, 4,
ax_anim 2, 0, 34, -4, 4, -4, 4,
ax_anim 2, 0, 35, -4, 4, -4, 4,
ax_anim 2, 0, 34, -4, 4, -4, 4,
ax_anim 2, 0, 33, -4, 4, -4, 4,
ax_anim 1, 0, 34, 0, 0, 0, 0,
ax_anim 1, 2, 35, 4, -1, 4, -4,
ax_anim 1, 0, 34, 8, -4, 8, -8,
ax_anim 2, 0, 33, 10, -3, 10, -10,
ax_anim 2, 1, 33, 9, -4, 9, -11,
ax_anim 2, 0, 33, 10, -3, 10, -10,
ax_anim 2, 0, 33, 9, -4, 9, -11,
ax_anim 2, 0, 33, 6, -1, 6, -1,
ax_anim_terminator
sHoOhAnims_2_5:
ax_anim 2, 0, 36, 0, 1, 0, 1,
ax_anim 2, 0, 36, 0, 3, 0, 3,
ax_anim 2, 0, 36, 0, 4, 0, 4,
ax_anim 2, 0, 37, 0, 4, 0, 4,
ax_anim 2, 0, 38, 0, 4, 0, 4,
ax_anim 2, 0, 37, 0, 4, 0, 4,
ax_anim 2, 0, 36, 0, 4, 0, 4,
ax_anim 1, 0, 37, 0, 0, 0, 0,
ax_anim 1, 2, 38, 0, -1, 0, -4,
ax_anim 1, 0, 37, 0, -4, 0, -12,
ax_anim 2, 0, 36, 0, -4, 0, -12,
ax_anim 2, 1, 36, 1, -4, 1, -12,
ax_anim 2, 0, 36, 0, -4, 0, -12,
ax_anim 2, 0, 36, 1, -4, 1, -12,
ax_anim 2, 0, 36, 0, -1, 0, -4,
ax_anim_terminator
sHoOhAnims_2_6:
ax_anim 2, 0, 39, 1, 1, 1, 1,
ax_anim 2, 0, 39, 3, 3, 3, 3,
ax_anim 2, 0, 39, 4, 4, 4, 4,
ax_anim 2, 0, 40, 4, 4, 4, 4,
ax_anim 2, 0, 41, 4, 4, 4, 4,
ax_anim 2, 0, 40, 4, 4, 4, 4,
ax_anim 2, 0, 39, 4, 4, 4, 4,
ax_anim 1, 0, 40, 0, 0, 0, 0,
ax_anim 1, 2, 41, -4, -1, -4, -4,
ax_anim 1, 0, 40, -8, -4, -8, -8,
ax_anim 2, 0, 39, -10, -3, -10, -10,
ax_anim 2, 1, 39, -9, -4, -9, -11,
ax_anim 2, 0, 39, -10, -3, -10, -10,
ax_anim 2, 0, 39, -9, -4, -9, -11,
ax_anim 2, 0, 39, -6, -1, -6, -1,
ax_anim_terminator
sHoOhAnims_2_7:
ax_anim 2, 0, 42, 1, 0, 1, 0,
ax_anim 2, 0, 42, 3, 0, 3, 0,
ax_anim 2, 0, 42, 4, 0, 4, 0,
ax_anim 2, 0, 43, 4, 0, 4, 0,
ax_anim 2, 0, 44, 4, 0, 4, 0,
ax_anim 2, 0, 43, 4, 0, 4, 0,
ax_anim 2, 0, 42, 4, 0, 4, 0,
ax_anim 1, 0, 43, 0, 0, 0, 0,
ax_anim 1, 2, 44, -4, 2, -4, 0,
ax_anim 1, 0, 43, -10, 4, -10, 0,
ax_anim 2, 0, 42, -15, 5, -15, 1,
ax_anim 2, 1, 42, -15, 4, -15, 0,
ax_anim 2, 0, 42, -15, 5, -15, 1,
ax_anim 2, 0, 42, -15, 4, -15, 0,
ax_anim 2, 0, 42, -6, 0, -6, 0,
ax_anim_terminator
sHoOhAnims_2_8:
ax_anim 2, 0, 45, 1, -1, 1, -1,
ax_anim 2, 0, 45, 3, -3, 3, -3,
ax_anim 2, 0, 45, 4, -4, 4, -4,
ax_anim 2, 0, 46, 4, -4, 4, -4,
ax_anim 2, 0, 47, 4, -4, 4, -4,
ax_anim 2, 0, 46, 4, -4, 4, -4,
ax_anim 2, 0, 45, 4, -4, 4, -4,
ax_anim 1, 0, 46, 0, 0, 0, 0,
ax_anim 1, 2, 47, -4, 7, -4, 5,
ax_anim 1, 0, 46, -10, 14, -10, 10,
ax_anim 2, 0, 45, -15, 22, -15, 18,
ax_anim 2, 1, 45, -16, 21, -16, 17,
ax_anim 2, 0, 45, -15, 22, -15, 18,
ax_anim 2, 0, 45, -16, 21, -16, 17,
ax_anim 2, 0, 45, -6, 6, -6, 6,
ax_anim_terminator
.align 2
sHoOhAnims_3_1:
ax_anim 2, 0, 48, 0, -1, 0, -1,
ax_anim 2, 0, 49, 0, -3, 0, -3,
ax_anim 2, 0, 50, 0, -5, 0, -5,
ax_anim 2, 0, 50, 0, -7, 0, -7,
ax_anim 2, 0, 49, 0, -7, 0, -7,
ax_anim 2, 0, 48, 0, -6, 0, -6,
ax_anim 2, 0, 48, 0, -4, 0, -4,
ax_anim 1, 0, 49, 0, 0, 0, 0,
ax_anim 1, 2, 51, 0, 4, 0, 4,
ax_anim 1, 0, 51, 0, 10, 0, 10,
ax_anim 2, 0, 51, 0, 22, 0, 22,
ax_anim 2, 1, 51, 1, 22, 1, 22,
ax_anim 2, 0, 51, 0, 22, 0, 22,
ax_anim 2, 0, 51, 1, 22, 1, 22,
ax_anim 2, 0, 48, 0, 6, 0, 6,
ax_anim_terminator
sHoOhAnims_3_2:
ax_anim 2, 0, 52, -1, -1, -1, -1,
ax_anim 2, 0, 53, -3, -3, -3, -3,
ax_anim 2, 0, 54, -5, -5, -5, -5,
ax_anim 2, 0, 54, -7, -7, -7, -7,
ax_anim 2, 0, 53, -7, -7, -7, -7,
ax_anim 2, 0, 52, -6, -6, -6, -6,
ax_anim 2, 0, 52, -4, -4, -4, -4,
ax_anim 1, 0, 53, 0, 0, 0, 0,
ax_anim 1, 2, 55, 4, 9, 4, 5,
ax_anim 1, 0, 55, 8, 13, 8, 10,
ax_anim 2, 0, 55, 12, 24, 12, 14,
ax_anim 2, 1, 55, 13, 23, 13, 13,
ax_anim 2, 0, 55, 12, 24, 12, 14,
ax_anim 2, 0, 55, 13, 23, 13, 13,
ax_anim 2, 0, 52, 6, 6, 6, 7,
ax_anim_terminator
sHoOhAnims_3_3:
ax_anim 2, 0, 56, -1, 0, -1, 0,
ax_anim 2, 0, 57, -3, 0, -3, 0,
ax_anim 2, 0, 58, -5, 0, -5, 0,
ax_anim 2, 0, 58, -7, 0, -7, 0,
ax_anim 2, 0, 57, -7, 0, -7, 0,
ax_anim 2, 0, 56, -6, 0, -6, 0,
ax_anim 2, 0, 56, -4, 0, -4, 0,
ax_anim 1, 0, 57, 0, 2, 0, 0,
ax_anim 1, 2, 59, 2, 6, 2, 0,
ax_anim 1, 0, 59, 7, 8, 7, 0,
ax_anim 2, 0, 59, 11, 12, 11, 0,
ax_anim 2, 1, 59, 11, 11, 11, -1,
ax_anim 2, 0, 59, 11, 12, 11, 0,
ax_anim 2, 0, 59, 11, 11, 11, -1,
ax_anim 2, 0, 56, 6, 5, 6, 0,
ax_anim_terminator
sHoOhAnims_3_4:
ax_anim 2, 0, 60, -1, 1, -1, 1,
ax_anim 2, 0, 61, -3, 3, -3, 3,
ax_anim 2, 0, 62, -5, 5, -5, 5,
ax_anim 2, 0, 62, -7, 7, -7, 7,
ax_anim 2, 0, 61, -7, 7, -7, 7,
ax_anim 2, 0, 60, -6, 6, -6, 6,
ax_anim 2, 0, 60, -4, 4, -4, 4,
ax_anim 1, 0, 61, 0, 2, 0, -1,
ax_anim 1, 2, 63, 4, 0, 4, -6,
ax_anim 1, 0, 63, 10, -2, 10, -12,
ax_anim 2, 0, 63, 12, -6, 12, -14,
ax_anim 2, 1, 63, 13, -5, 13, -13,
ax_anim 2, 0, 63, 12, -6, 12, -14,
ax_anim 2, 0, 63, 13, -5, 13, -13,
ax_anim 2, 0, 60, 6, -6, 6, -7,
ax_anim_terminator
sHoOhAnims_3_5:
ax_anim 2, 0, 64, 0, 1, 0, 1,
ax_anim 2, 0, 65, 0, 4, 0, 4,
ax_anim 2, 0, 66, 0, 7, 0, 7,
ax_anim 2, 0, 66, 0, 8, 0, 8,
ax_anim 2, 0, 65, 0, 7, 0, 7,
ax_anim 2, 0, 64, 0, 6, 0, 6,
ax_anim 2, 0, 64, 0, 4, 0, 4,
ax_anim 1, 0, 65, 0, 2, 0, 2,
ax_anim 1, 2, 67, 0, 0, 0, -4,
ax_anim 1, 0, 67, 0, -1, 0, -9,
ax_anim 2, 0, 67, 0, -3, 0, -9,
ax_anim 2, 1, 67, 1, -3, 1, -9,
ax_anim 2, 0, 67, 0, -3, 0, -9,
ax_anim 2, 0, 67, 1, -3, 1, -9,
ax_anim 2, 0, 64, 0, -3, 0, -5,
ax_anim_terminator
sHoOhAnims_3_6:
ax_anim 2, 0, 68, 1, 1, 1, 1,
ax_anim 2, 0, 69, 3, 3, 3, 3,
ax_anim 2, 0, 70, 5, 5, 5, 5,
ax_anim 2, 0, 70, 7, 7, 7, 7,
ax_anim 2, 0, 69, 7, 7, 7, 7,
ax_anim 2, 0, 68, 6, 6, 6, 6,
ax_anim 2, 0, 68, 4, 4, 4, 4,
ax_anim 1, 0, 69, 0, 2, 0, -1,
ax_anim 1, 2, 71, -4, 0, -4, -6,
ax_anim 1, 0, 71, -10, -2, -10, -12,
ax_anim 2, 0, 71, -12, -6, -12, -14,
ax_anim 2, 1, 71, -13, -5, -13, -13,
ax_anim 2, 0, 71, -12, -6, -12, -14,
ax_anim 2, 0, 71, -13, -5, -13, -13,
ax_anim 2, 0, 68, -6, -6, -6, -7,
ax_anim_terminator
sHoOhAnims_3_7:
ax_anim 2, 0, 72, 1, 0, 1, 0,
ax_anim 2, 0, 73, 3, 0, 3, 0,
ax_anim 2, 0, 74, 5, 0, 5, 0,
ax_anim 2, 0, 74, 7, 0, 7, 0,
ax_anim 2, 0, 73, 7, 0, 7, 0,
ax_anim 2, 0, 72, 6, 0, 6, 0,
ax_anim 2, 0, 72, 4, 0, 4, 0,
ax_anim 1, 0, 73, 0, 2, 0, 0,
ax_anim 1, 2, 75, -2, 6, -2, 0,
ax_anim 1, 0, 75, -7, 8, -7, 0,
ax_anim 2, 0, 75, -11, 12, -11, 0,
ax_anim 2, 1, 75, -11, 11, -11, -1,
ax_anim 2, 0, 75, -11, 12, -11, 0,
ax_anim 2, 0, 75, -11, 11, -11, -1,
ax_anim 2, 0, 72, -6, 5, -6, 0,
ax_anim_terminator
sHoOhAnims_3_8:
ax_anim 2, 0, 76, 1, -1, 1, -1,
ax_anim 2, 0, 77, 3, -3, 3, -3,
ax_anim 2, 0, 78, 5, -5, 5, -5,
ax_anim 2, 0, 78, 7, -7, 7, -7,
ax_anim 2, 0, 77, 7, -7, 7, -7,
ax_anim 2, 0, 76, 6, -6, 6, -6,
ax_anim 2, 0, 76, 4, -4, 4, -4,
ax_anim 1, 0, 77, 0, 0, 0, 0,
ax_anim 1, 2, 79, -4, 9, -4, 5,
ax_anim 1, 0, 79, -8, 13, -8, 10,
ax_anim 2, 0, 79, -12, 24, -12, 14,
ax_anim 2, 1, 79, -13, 23, -13, 13,
ax_anim 2, 0, 79, -12, 24, -12, 14,
ax_anim 2, 0, 79, -13, 23, -13, 13,
ax_anim 2, 0, 76, -6, 6, -6, 7,
ax_anim_terminator
.align 2
sHoOhAnims_4_1:
ax_anim 4, 0, 82, 0, 0, 0, 0,
ax_anim 2, 0, 81, 0, 0, 0, 0,
ax_anim 4, 0, 80, 0, 0, 0, 0,
ax_anim 2, 0, 81, 0, 0, 0, 0,
ax_anim 1, 0, 82, 0, -1, 0, -1,
ax_anim 1, 0, 82, 0, -2, 0, -1,
ax_anim 1, 0, 83, 0, -3, 0, -1,
ax_anim 2, 0, 83, 0, -4, 0, -3,
ax_anim 4, 2, 83, 0, -5, 0, -5,
ax_anim 2, 0, 81, 0, -2, 0, -2,
ax_anim 2, 0, 84, 0, 1, 0, 1,
ax_anim 2, 1, 84, 0, 5, 0, 5,
ax_anim 2, 0, 84, 1, 5, 1, 5,
ax_anim 2, 0, 84, 0, 5, 0, 5,
ax_anim 2, 0, 84, 1, 5, 1, 5,
ax_anim 2, 0, 84, 0, 5, 0, 5,
ax_anim 2, 0, 84, 1, 5, 1, 5,
ax_anim 4, 0, 84, 0, 2, 0, 2,
ax_anim_terminator
sHoOhAnims_4_2:
ax_anim 4, 0, 87, 0, 0, 0, 0,
ax_anim 2, 0, 86, 0, 0, 0, 0,
ax_anim 4, 0, 85, 0, 0, 0, 0,
ax_anim 2, 0, 86, 0, 0, 0, 0,
ax_anim 1, 0, 87, -1, -1, -1, -1,
ax_anim 1, 0, 87, -2, -2, -2, -2,
ax_anim 1, 0, 88, -3, -3, -3, -3,
ax_anim 2, 0, 88, -4, -4, -4, -4,
ax_anim 4, 2, 88, -5, -5, -5, -5,
ax_anim 2, 0, 86, -2, -2, -2, -2,
ax_anim 2, 0, 89, 1, 1, 1, 1,
ax_anim 2, 1, 89, 5, 5, 5, 5,
ax_anim 2, 0, 89, 6, 4, 6, 4,
ax_anim 2, 0, 89, 5, 5, 5, 5,
ax_anim 2, 0, 89, 6, 4, 6, 4,
ax_anim 2, 0, 89, 5, 5, 5, 5,
ax_anim 2, 0, 89, 6, 4, 6, 4,
ax_anim 4, 0, 89, 2, 2, 2, 2,
ax_anim_terminator
sHoOhAnims_4_3:
ax_anim 4, 0, 92, 0, 0, 0, 0,
ax_anim 2, 0, 91, 0, 0, 0, 0,
ax_anim 4, 0, 90, 0, 0, 0, 0,
ax_anim 2, 0, 91, 0, 0, 0, 0,
ax_anim 1, 0, 92, -1, 0, -1, 0,
ax_anim 1, 0, 92, -2, 0, -2, 0,
ax_anim 1, 0, 93, -5, 0, -5, 0,
ax_anim 2, 0, 93, -6, 0, -6, 0,
ax_anim 4, 2, 93, -7, 0, -7, 0,
ax_anim 2, 0, 91, -2, 0, -2, 0,
ax_anim 2, 0, 94, 1, 0, 1, 0,
ax_anim 2, 1, 94, 5, 0, 5, 0,
ax_anim 2, 0, 94, 5, 1, 5, 1,
ax_anim 2, 0, 94, 5, 0, 5, 0,
ax_anim 2, 0, 94, 5, 1, 5, 1,
ax_anim 2, 0, 94, 5, 0, 5, 0,
ax_anim 2, 0, 94, 5, 1, 5, 1,
ax_anim 4, 0, 94, 2, 0, 2, 0,
ax_anim_terminator
sHoOhAnims_4_4:
ax_anim 4, 0, 97, 0, 0, 0, 0,
ax_anim 2, 0, 96, 0, 0, 0, 0,
ax_anim 4, 0, 95, 0, 0, 0, 0,
ax_anim 2, 0, 96, 0, 0, 0, 0,
ax_anim 1, 0, 97, -1, 1, -1, 1,
ax_anim 1, 0, 97, -2, 2, -2, 2,
ax_anim 1, 0, 98, -5, 5, -5, 5,
ax_anim 2, 0, 98, -6, 6, -6, 6,
ax_anim 4, 2, 98, -7, 7, -7, 7,
ax_anim 2, 0, 96, -2, 2, -2, 2,
ax_anim 2, 0, 99, 1, -1, 1, -1,
ax_anim 2, 1, 99, 5, -5, 5, -5,
ax_anim 2, 0, 99, 6, -4, 6, -4,
ax_anim 2, 0, 99, 5, -5, 5, -5,
ax_anim 2, 0, 99, 6, -4, 6, -4,
ax_anim 2, 0, 99, 5, -5, 5, -5,
ax_anim 2, 0, 99, 6, -4, 6, -4,
ax_anim 4, 0, 99, 2, -2, 2, -2,
ax_anim_terminator
sHoOhAnims_4_5:
ax_anim 4, 0, 102, 0, 0, 0, 0,
ax_anim 2, 0, 101, 0, 0, 0, 0,
ax_anim 4, 0, 100, 0, 0, 0, 0,
ax_anim 2, 0, 101, 0, 0, 0, 0,
ax_anim 1, 0, 102, 0, 1, 0, 1,
ax_anim 1, 0, 102, 0, 2, 0, 2,
ax_anim 1, 0, 103, 0, 3, 0, 3,
ax_anim 2, 0, 103, 0, 4, 0, 4,
ax_anim 4, 2, 103, 0, 5, 0, 5,
ax_anim 2, 0, 101, 0, 2, 0, 2,
ax_anim 2, 0, 104, 0, -1, 0, -1,
ax_anim 2, 1, 104, 0, -5, -5, -5,
ax_anim 2, 0, 104, 0, -4, -6, -4,
ax_anim 2, 0, 104, 0, -5, -5, -5,
ax_anim 2, 0, 104, 0, -4, -6, -4,
ax_anim 2, 0, 104, 0, -5, -5, -5,
ax_anim 2, 0, 104, 0, -4, -6, -4,
ax_anim 4, 0, 104, 0, -2, -2, -2,
ax_anim_terminator
sHoOhAnims_4_6:
ax_anim 4, 0, 107, 0, 0, 0, 0,
ax_anim 2, 0, 106, 0, 0, 0, 0,
ax_anim 4, 0, 105, 0, 0, 0, 0,
ax_anim 2, 0, 106, 0, 0, 0, 0,
ax_anim 1, 0, 107, 1, 1, 1, 1,
ax_anim 1, 0, 107, 2, 2, 2, 2,
ax_anim 1, 0, 108, 5, 5, 5, 5,
ax_anim 2, 0, 108, 6, 6, 6, 6,
ax_anim 4, 2, 108, 7, 7, 7, 7,
ax_anim 2, 0, 106, 2, 2, 2, 2,
ax_anim 2, 0, 109, -1, -1, -1, -1,
ax_anim 2, 1, 109, -5, -5, -5, -5,
ax_anim 2, 0, 109, -6, -4, -6, -4,
ax_anim 2, 0, 109, -5, -5, -5, -5,
ax_anim 2, 0, 109, -6, -4, -6, -4,
ax_anim 2, 0, 109, -5, -5, -5, -5,
ax_anim 2, 0, 109, -6, -4, -6, -4,
ax_anim 4, 0, 109, -2, -2, -2, -2,
ax_anim_terminator
sHoOhAnims_4_7:
ax_anim 4, 0, 112, 0, 0, 0, 0,
ax_anim 2, 0, 111, 0, 0, 0, 0,
ax_anim 4, 0, 110, 0, 0, 0, 0,
ax_anim 2, 0, 111, 0, 0, 0, 0,
ax_anim 1, 0, 112, 1, 0, 1, 0,
ax_anim 1, 0, 112, 2, 0, 2, 0,
ax_anim 1, 0, 113, 5, 0, 5, 0,
ax_anim 2, 0, 113, 6, 0, 6, 0,
ax_anim 4, 2, 113, 7, 0, 7, 0,
ax_anim 2, 0, 111, 2, 0, 2, 0,
ax_anim 2, 0, 114, -1, 0, -1, 0,
ax_anim 2, 1, 114, -5, 0, -5, 0,
ax_anim 2, 0, 114, -5, 1, -5, 1,
ax_anim 2, 0, 114, -5, 0, -5, 0,
ax_anim 2, 0, 114, -5, 1, -5, 1,
ax_anim 2, 0, 114, -5, 0, -5, 0,
ax_anim 2, 0, 114, -5, 1, -5, 1,
ax_anim 4, 0, 114, -2, 0, -2, 0,
ax_anim_terminator
sHoOhAnims_4_8:
ax_anim 4, 0, 117, 0, 0, 0, 0,
ax_anim 2, 0, 116, 0, 0, 0, 0,
ax_anim 4, 0, 115, 0, 0, 0, 0,
ax_anim 2, 0, 116, 0, 0, 0, 0,
ax_anim 1, 0, 117, 1, -1, 1, -1,
ax_anim 1, 0, 117, 2, -2, 2, -2,
ax_anim 1, 0, 118, 3, -3, 3, -3,
ax_anim 2, 0, 118, 4, -4, 4, -4,
ax_anim 4, 2, 118, 5, -5, 5, -5,
ax_anim 2, 0, 116, 2, -2, 2, -2,
ax_anim 2, 0, 119, -1, 1, -1, 1,
ax_anim 2, 1, 119, -5, 5, -5, 5,
ax_anim 2, 0, 119, -6, 4, -6, 4,
ax_anim 2, 0, 119, -5, 5, -5, 5,
ax_anim 2, 0, 119, -6, 4, -6, 4,
ax_anim 2, 0, 119, -5, 5, -5, 5,
ax_anim 2, 0, 119, -6, 4, -6, 4,
ax_anim 4, 0, 119, -2, 2, -2, 2,
ax_anim_terminator
.align 2
sHoOhAnims_5_1:
ax_anim 2, 0, 120, 0, 0, 0, 0,
ax_anim 1, 0, 121, 0, 0, 0, 0,
ax_anim 2, 0, 122, 0, 0, 0, 0,
ax_anim 1, 0, 122, 0, -1, 0, 0,
ax_anim 2, 0, 121, 0, 0, 0, 0,
ax_anim 2, 2, 120, 0, 0, 0, 0,
ax_anim 1, 0, 121, 0, 0, 0, 0,
ax_anim 2, 0, 122, 0, 0, 0, 0,
ax_anim 1, 0, 122, 0, -1, 0, 0,
ax_anim 2, 0, 121, 0, 0, 0, 0,
ax_anim 2, 0, 120, 0, 0, 0, 0,
ax_anim 1, 0, 121, 0, 0, 0, 0,
ax_anim 2, 0, 122, 0, 0, 0, 0,
ax_anim 1, 0, 122, 0, -1, 0, 0,
ax_anim 2, 0, 121, 0, 0, 0, 0,
ax_anim 2, 1, 120, 0, 0, 0, 0,
ax_anim 1, 0, 121, 0, 0, 0, 0,
ax_anim 2, 0, 122, 0, 0, 0, 0,
ax_anim 1, 0, 122, 0, -1, 0, 0,
ax_anim 2, 0, 121, 0, 0, 0, 0,
ax_anim_terminator
sHoOhAnims_5_2:
ax_anim 2, 0, 123, 0, 0, 0, 0,
ax_anim 1, 0, 124, 0, 0, 0, 0,
ax_anim 2, 0, 125, 0, 0, 0, 0,
ax_anim 1, 0, 125, 0, -1, 0, 0,
ax_anim 2, 0, 124, 0, 0, 0, 0,
ax_anim 2, 2, 123, 0, 0, 0, 0,
ax_anim 1, 0, 124, 0, 0, 0, 0,
ax_anim 2, 0, 125, 0, 0, 0, 0,
ax_anim 1, 0, 125, 0, -1, 0, 0,
ax_anim 2, 0, 124, 0, 0, 0, 0,
ax_anim 2, 0, 123, 0, 0, 0, 0,
ax_anim 1, 0, 124, 0, 0, 0, 0,
ax_anim 2, 0, 125, 0, 0, 0, 0,
ax_anim 1, 0, 125, 0, -1, 0, 0,
ax_anim 2, 0, 124, 0, 0, 0, 0,
ax_anim 2, 1, 123, 0, 0, 0, 0,
ax_anim 1, 0, 124, 0, 0, 0, 0,
ax_anim 2, 0, 125, 0, 0, 0, 0,
ax_anim 1, 0, 125, 0, -1, 0, 0,
ax_anim 2, 0, 124, 0, 0, 0, 0,
ax_anim_terminator
sHoOhAnims_5_3:
ax_anim 2, 0, 126, 0, 0, 0, 0,
ax_anim 1, 0, 127, 0, 0, 0, 0,
ax_anim 2, 0, 128, 0, 0, 0, 0,
ax_anim 1, 0, 128, 0, -1, 0, 0,
ax_anim 2, 0, 127, 0, 0, 0, 0,
ax_anim 2, 2, 126, 0, 0, 0, 0,
ax_anim 1, 0, 127, 0, 0, 0, 0,
ax_anim 2, 0, 128, 0, 0, 0, 0,
ax_anim 1, 0, 128, 0, -1, 0, 0,
ax_anim 2, 0, 127, 0, 0, 0, 0,
ax_anim 2, 0, 126, 0, 0, 0, 0,
ax_anim 1, 0, 127, 0, 0, 0, 0,
ax_anim 2, 0, 128, 0, 0, 0, 0,
ax_anim 1, 0, 128, 0, -1, 0, 0,
ax_anim 2, 0, 127, 0, 0, 0, 0,
ax_anim 2, 1, 126, 0, 0, 0, 0,
ax_anim 1, 0, 127, 0, 0, 0, 0,
ax_anim 2, 0, 128, 0, 0, 0, 0,
ax_anim 1, 0, 128, 0, -1, 0, 0,
ax_anim 2, 0, 127, 0, 0, 0, 0,
ax_anim_terminator
sHoOhAnims_5_4:
ax_anim 2, 0, 129, 0, 0, 0, 0,
ax_anim 1, 0, 130, 0, 0, 0, 0,
ax_anim 2, 0, 131, 0, 0, 0, 0,
ax_anim 1, 0, 131, 0, -1, 0, 0,
ax_anim 2, 0, 130, 0, 0, 0, 0,
ax_anim 2, 2, 129, 0, 0, 0, 0,
ax_anim 1, 0, 130, 0, 0, 0, 0,
ax_anim 2, 0, 131, 0, 0, 0, 0,
ax_anim 1, 0, 131, 0, -1, 0, 0,
ax_anim 2, 0, 130, 0, 0, 0, 0,
ax_anim 2, 0, 129, 0, 0, 0, 0,
ax_anim 1, 0, 130, 0, 0, 0, 0,
ax_anim 2, 0, 131, 0, 0, 0, 0,
ax_anim 1, 0, 131, 0, -1, 0, 0,
ax_anim 2, 0, 130, 0, 0, 0, 0,
ax_anim 2, 1, 129, 0, 0, 0, 0,
ax_anim 1, 0, 130, 0, 0, 0, 0,
ax_anim 2, 0, 131, 0, 0, 0, 0,
ax_anim 1, 0, 131, 0, -1, 0, 0,
ax_anim 2, 0, 130, 0, 0, 0, 0,
ax_anim_terminator
sHoOhAnims_5_5:
ax_anim 2, 0, 132, 0, 0, 0, 0,
ax_anim 1, 0, 133, 0, 0, 0, 0,
ax_anim 2, 0, 134, 0, 0, 0, 0,
ax_anim 1, 0, 134, 0, -1, 0, 0,
ax_anim 2, 0, 133, 0, 0, 0, 0,
ax_anim 2, 2, 132, 0, 0, 0, 0,
ax_anim 1, 0, 133, 0, 0, 0, 0,
ax_anim 2, 0, 134, 0, 0, 0, 0,
ax_anim 1, 0, 134, 0, -1, 0, 0,
ax_anim 2, 0, 133, 0, 0, 0, 0,
ax_anim 2, 0, 132, 0, 0, 0, 0,
ax_anim 1, 0, 133, 0, 0, 0, 0,
ax_anim 2, 0, 134, 0, 0, 0, 0,
ax_anim 1, 0, 134, 0, -1, 0, 0,
ax_anim 2, 0, 133, 0, 0, 0, 0,
ax_anim 2, 1, 132, 0, 0, 0, 0,
ax_anim 1, 0, 133, 0, 0, 0, 0,
ax_anim 2, 0, 134, 0, 0, 0, 0,
ax_anim 1, 0, 134, 0, -1, 0, 0,
ax_anim 2, 0, 133, 0, 0, 0, 0,
ax_anim_terminator
sHoOhAnims_5_6:
ax_anim 2, 0, 135, 0, 0, 0, 0,
ax_anim 1, 0, 136, 0, 0, 0, 0,
ax_anim 2, 0, 137, 0, 0, 0, 0,
ax_anim 1, 0, 137, 0, -1, 0, 0,
ax_anim 2, 0, 136, 0, 0, 0, 0,
ax_anim 2, 2, 135, 0, 0, 0, 0,
ax_anim 1, 0, 136, 0, 0, 0, 0,
ax_anim 2, 0, 137, 0, 0, 0, 0,
ax_anim 1, 0, 137, 0, -1, 0, 0,
ax_anim 2, 0, 136, 0, 0, 0, 0,
ax_anim 2, 0, 135, 0, 0, 0, 0,
ax_anim 1, 0, 136, 0, 0, 0, 0,
ax_anim 2, 0, 137, 0, 0, 0, 0,
ax_anim 1, 0, 137, 0, -1, 0, 0,
ax_anim 2, 0, 136, 0, 0, 0, 0,
ax_anim 2, 1, 135, 0, 0, 0, 0,
ax_anim 1, 0, 136, 0, 0, 0, 0,
ax_anim 2, 0, 137, 0, 0, 0, 0,
ax_anim 1, 0, 137, 0, -1, 0, 0,
ax_anim 2, 0, 136, 0, 0, 0, 0,
ax_anim_terminator
sHoOhAnims_5_7:
ax_anim 2, 0, 138, 0, 0, 0, 0,
ax_anim 1, 0, 139, 0, 0, 0, 0,
ax_anim 2, 0, 140, 0, 0, 0, 0,
ax_anim 1, 0, 140, 0, -1, 0, 0,
ax_anim 2, 0, 139, 0, 0, 0, 0,
ax_anim 2, 2, 138, 0, 0, 0, 0,
ax_anim 1, 0, 139, 0, 0, 0, 0,
ax_anim 2, 0, 140, 0, 0, 0, 0,
ax_anim 1, 0, 140, 0, -1, 0, 0,
ax_anim 2, 0, 139, 0, 0, 0, 0,
ax_anim 2, 0, 138, 0, 0, 0, 0,
ax_anim 1, 0, 139, 0, 0, 0, 0,
ax_anim 2, 0, 140, 0, 0, 0, 0,
ax_anim 1, 0, 140, 0, -1, 0, 0,
ax_anim 2, 0, 139, 0, 0, 0, 0,
ax_anim 2, 1, 138, 0, 0, 0, 0,
ax_anim 1, 0, 139, 0, 0, 0, 0,
ax_anim 2, 0, 140, 0, 0, 0, 0,
ax_anim 1, 0, 140, 0, -1, 0, 0,
ax_anim 2, 0, 139, 0, 0, 0, 0,
ax_anim_terminator
sHoOhAnims_5_8:
ax_anim 2, 0, 141, 0, 0, 0, 0,
ax_anim 1, 0, 142, 0, 0, 0, 0,
ax_anim 2, 0, 143, 0, 0, 0, 0,
ax_anim 1, 0, 143, 0, -1, 0, 0,
ax_anim 2, 0, 142, 0, 0, 0, 0,
ax_anim 2, 2, 141, 0, 0, 0, 0,
ax_anim 1, 0, 142, 0, 0, 0, 0,
ax_anim 2, 0, 143, 0, 0, 0, 0,
ax_anim 1, 0, 143, 0, -1, 0, 0,
ax_anim 2, 0, 142, 0, 0, 0, 0,
ax_anim 2, 0, 141, 0, 0, 0, 0,
ax_anim 1, 0, 142, 0, 0, 0, 0,
ax_anim 2, 0, 143, 0, 0, 0, 0,
ax_anim 1, 0, 143, 0, -1, 0, 0,
ax_anim 2, 0, 142, 0, 0, 0, 0,
ax_anim 2, 1, 141, 0, 0, 0, 0,
ax_anim 1, 0, 142, 0, 0, 0, 0,
ax_anim 2, 0, 143, 0, 0, 0, 0,
ax_anim 1, 0, 143, 0, -1, 0, 0,
ax_anim 2, 0, 142, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sHoOhAnims_6_1:
ax_anim 30, 0, 144, 0, 0, 0, 0,
ax_anim 35, 0, 145, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sHoOhAnims_7_1:
ax_anim 2, 0, 146, 0, -4, 0, -4,
ax_anim 8, 0, 146, 0, -5, 0, -5,
ax_anim_terminator
sHoOhAnims_7_2:
ax_anim 2, 0, 147, -4, -4, -4, -4,
ax_anim 8, 0, 147, -5, -5, -5, -5,
ax_anim_terminator
sHoOhAnims_7_3:
ax_anim 2, 0, 148, -4, 0, -4, 0,
ax_anim 8, 0, 148, -5, 0, -5, 0,
ax_anim_terminator
sHoOhAnims_7_4:
ax_anim 2, 0, 149, -4, 4, -4, 4,
ax_anim 8, 0, 149, -5, 5, -5, 5,
ax_anim_terminator
sHoOhAnims_7_5:
ax_anim 2, 0, 150, 0, 4, 0, 4,
ax_anim 8, 0, 150, 0, 5, 0, 5,
ax_anim_terminator
sHoOhAnims_7_6:
ax_anim 2, 0, 151, 4, 4, 4, 4,
ax_anim 8, 0, 151, 5, 5, 5, 5,
ax_anim_terminator
sHoOhAnims_7_7:
ax_anim 2, 0, 152, 4, 0, 4, 0,
ax_anim 8, 0, 152, 5, 0, 5, 0,
ax_anim_terminator
sHoOhAnims_7_8:
ax_anim 2, 0, 153, 4, -4, 4, -4,
ax_anim 8, 0, 153, 5, -5, 5, -5,
ax_anim_terminator
.align 2
sHoOhAnims_8_1:
ax_anim 12, 0, 154, 0, 0, 0, 0,
ax_anim 10, 0, 155, 0, 0, 0, 0,
ax_anim 12, 0, 156, 0, 0, 0, 0,
ax_anim 10, 0, 156, 0, -1, 0, 0,
ax_anim 12, 0, 155, 0, 0, 0, 0,
ax_anim_terminator
sHoOhAnims_8_2:
ax_anim 12, 0, 157, 0, 0, 0, 0,
ax_anim 10, 0, 158, 0, 0, 0, 0,
ax_anim 12, 0, 159, 0, 0, 0, 0,
ax_anim 10, 0, 159, 0, -1, 0, 0,
ax_anim 12, 0, 158, 0, 0, 0, 0,
ax_anim_terminator
sHoOhAnims_8_3:
ax_anim 12, 0, 160, 0, 0, 0, 0,
ax_anim 10, 0, 161, 0, 0, 0, 0,
ax_anim 12, 0, 162, 0, 0, 0, 0,
ax_anim 10, 0, 162, 0, -1, 0, 0,
ax_anim 12, 0, 161, 0, 0, 0, 0,
ax_anim_terminator
sHoOhAnims_8_4:
ax_anim 12, 0, 163, 0, 0, 0, 0,
ax_anim 10, 0, 164, 0, 0, 0, 0,
ax_anim 12, 0, 165, 0, 0, 0, 0,
ax_anim 10, 0, 165, 0, -1, 0, 0,
ax_anim 12, 0, 164, 0, 0, 0, 0,
ax_anim_terminator
sHoOhAnims_8_5:
ax_anim 12, 0, 166, 0, 0, 0, 0,
ax_anim 10, 0, 167, 0, 0, 0, 0,
ax_anim 12, 0, 168, 0, 0, 0, 0,
ax_anim 10, 0, 168, 0, -1, 0, 0,
ax_anim 12, 0, 167, 0, 0, 0, 0,
ax_anim_terminator
sHoOhAnims_8_6:
ax_anim 12, 0, 169, 0, 0, 0, 0,
ax_anim 10, 0, 170, 0, 0, 0, 0,
ax_anim 12, 0, 171, 0, 0, 0, 0,
ax_anim 10, 0, 171, 0, -1, 0, 0,
ax_anim 12, 0, 170, 0, 0, 0, 0,
ax_anim_terminator
sHoOhAnims_8_7:
ax_anim 12, 0, 172, 0, 0, 0, 0,
ax_anim 10, 0, 173, 0, 0, 0, 0,
ax_anim 12, 0, 174, 0, 0, 0, 0,
ax_anim 10, 0, 174, 0, -1, 0, 0,
ax_anim 12, 0, 173, 0, 0, 0, 0,
ax_anim_terminator
sHoOhAnims_8_8:
ax_anim 12, 0, 175, 0, 0, 0, 0,
ax_anim 10, 0, 176, 0, 0, 0, 0,
ax_anim 12, 0, 177, 0, 0, 0, 0,
ax_anim 10, 0, 177, 0, -1, 0, 0,
ax_anim 12, 0, 176, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sHoOhAnims_9_1:
ax_anim 2, 0, 178, 0, 0, 0, 0,
ax_anim 1, 0, 179, 6, 4, 6, 4,
ax_anim 2, 0, 180, 8, 9, 8, 9,
ax_anim 2, 0, 181, 7, 19, 7, 19,
ax_anim 3, 0, 182, 0, 24, 0, 24,
ax_anim 2, 3, 183, -7, 19, -7, 19,
ax_anim 2, 0, 184, -8, 9, -8, 9,
ax_anim 1, 0, 185, -6, 4, -6, 4,
ax_anim 1, 0, 178, 0, 0, 0, 0,
ax_anim_terminator
sHoOhAnims_9_2:
ax_anim 2, 0, 185, 0, 0, 0, 0,
ax_anim 1, 0, 178, 6, 0, 6, 0,
ax_anim 2, 0, 179, 11, 3, 11, 3,
ax_anim 2, 0, 180, 15, 9, 15, 9,
ax_anim 3, 0, 181, 12, 21, 12, 21,
ax_anim 2, 3, 182, 11, 21, 11, 21,
ax_anim 2, 0, 183, 2, 16, 2, 16,
ax_anim 1, 0, 184, 0, 7, 0, 7,
ax_anim 1, 0, 185, 0, 0, 0, 0,
ax_anim_terminator
sHoOhAnims_9_3:
ax_anim 2, 0, 184, 0, 0, 0, 0,
ax_anim 1, 0, 185, 3, -4, 3, -4,
ax_anim 2, 0, 178, 11, -6, 11, -6,
ax_anim 2, 0, 179, 11, -4, 11, -4,
ax_anim 3, 0, 180, 10, 1, 10, 1,
ax_anim 2, 3, 181, 12, 5, 12, 5,
ax_anim 2, 0, 182, 12, 7, 12, 7,
ax_anim 1, 0, 183, 4, 5, 4, 5,
ax_anim 1, 0, 184, 0, 0, 0, 0,
ax_anim_terminator
sHoOhAnims_9_4:
ax_anim 2, 0, 183, 0, 0, 0, 0,
ax_anim 1, 0, 184, 2, -3, 2, -3,
ax_anim 2, 0, 185, 4, -7, 4, -7,
ax_anim 2, 0, 178, 11, -6, 11, -6,
ax_anim 3, 0, 179, 10, -3, 10, -3,
ax_anim 2, 3, 180, 9, 0, 9, 0,
ax_anim 2, 0, 181, 8, 0, 8, 0,
ax_anim 1, 0, 182, 7, 1, 7, 1,
ax_anim 1, 0, 183, 0, 0, 0, 0,
ax_anim_terminator
sHoOhAnims_9_5:
ax_anim 2, 0, 182, 0, 0, 0, 0,
ax_anim 1, 0, 183, -6, -1, -6, -1,
ax_anim 2, 0, 184, -8, -3, -8, -3,
ax_anim 2, 0, 185, -7, -5, -7, -5,
ax_anim 3, 0, 178, 0, -6, 0, -6,
ax_anim 2, 3, 179, 7, -5, 7, -5,
ax_anim 2, 0, 180, 8, -3, 8, -3,
ax_anim 1, 0, 181, 6, -1, 6, -1,
ax_anim 1, 0, 182, 0, 0, 0, 0,
ax_anim_terminator
sHoOhAnims_9_6:
ax_anim 2, 0, 181, 0, 0, 0, 0,
ax_anim 1, 0, 180, -2, -3, -2, -3,
ax_anim 2, 0, 179, -4, -7, -4, -7,
ax_anim 2, 0, 178, -11, -6, -11, -6,
ax_anim 3, 0, 185, -10, -3, -10, -3,
ax_anim 2, 3, 184, -9, 0, -9, 0,
ax_anim 2, 0, 183, -8, 0, -8, 0,
ax_anim 1, 0, 182, -7, -1, -7, -1,
ax_anim 1, 0, 181, 0, 0, 0, 0,
ax_anim_terminator
sHoOhAnims_9_7:
ax_anim 2, 0, 180, 0, 0, 0, 0,
ax_anim 1, 0, 179, -3, -4, -3, -4,
ax_anim 2, 0, 178, -11, -6, -11, -6,
ax_anim 2, 0, 185, -11, -4, -11, -4,
ax_anim 3, 0, 184, -10, 1, -10, 1,
ax_anim 2, 3, 183, -12, 5, -12, 5,
ax_anim 2, 0, 182, -12, 7, -12, 7,
ax_anim 1, 0, 181, -4, 5, -4, 5,
ax_anim 1, 0, 180, 0, 0, 0, 0,
ax_anim_terminator
sHoOhAnims_9_8:
ax_anim 2, 0, 179, 0, 0, 0, 0,
ax_anim 1, 0, 178, -6, 0, -6, 0,
ax_anim 2, 0, 185, -11, 3, -11, 3,
ax_anim 2, 0, 184, -15, 9, -15, 9,
ax_anim 3, 0, 183, -12, 21, -12, 21,
ax_anim 2, 3, 182, -11, 21, -11, 21,
ax_anim 2, 0, 181, -2, 16, -2, 16,
ax_anim 1, 0, 180, 0, 7, 0, 7,
ax_anim 1, 0, 179, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sHoOhAnims_10_1:
ax_anim 2, 0, 186, 0, 0, 0, 0,
ax_anim 2, 0, 186, 6, 0, 6, 0,
ax_anim 2, 0, 186, -6, 0, -6, 0,
ax_anim 2, 0, 186, 10, 0, 10, 0,
ax_anim 2, 0, 186, -10, 0, -10, 0,
ax_anim 2, 0, 186, 12, 0, 12, 0,
ax_anim 3, 0, 186, -12, 0, -12, 0,
ax_anim 3, 0, 186, 13, 0, 13, 0,
ax_anim 3, 0, 186, -13, 0, -13, 0,
ax_anim 2, 0, 186, 12, 0, 12, 0,
ax_anim 3, 0, 186, -12, 0, -12, 0,
ax_anim 2, 0, 186, 10, 0, 10, 0,
ax_anim 2, 0, 186, -10, 0, -10, 0,
ax_anim 2, 0, 186, 6, 0, 6, 0,
ax_anim 2, 0, 186, -6, 0, -6, 0,
ax_anim 2, 0, 186, 0, 0, 0, 0,
ax_anim_terminator
sHoOhAnims_10_2:
ax_anim 2, 0, 187, 0, 0, 0, 0,
ax_anim 2, 0, 187, 6, -6, 6, -6,
ax_anim 2, 0, 187, -6, 6, -6, 6,
ax_anim 2, 0, 187, 10, -10, 10, -10,
ax_anim 2, 0, 187, -10, 10, -10, 10,
ax_anim 2, 0, 187, 12, -12, 12, -12,
ax_anim 3, 0, 187, -12, 12, -12, 12,
ax_anim 3, 0, 187, 13, -13, 13, -13,
ax_anim 3, 0, 187, -13, 13, -13, 13,
ax_anim 2, 0, 187, 12, -12, 12, -12,
ax_anim 3, 0, 187, -12, 12, -12, 12,
ax_anim 2, 0, 187, 10, -10, 10, -10,
ax_anim 2, 0, 187, -10, 10, -10, 10,
ax_anim 2, 0, 187, 6, -6, 6, -6,
ax_anim 2, 0, 187, -6, 6, -6, 6,
ax_anim 2, 0, 187, 0, 0, 0, 0,
ax_anim_terminator
sHoOhAnims_10_3:
ax_anim 2, 0, 188, 0, 0, 0, 0,
ax_anim 2, 0, 188, 0, -6, 0, -6,
ax_anim 2, 0, 188, 0, 6, 0, 6,
ax_anim 2, 0, 188, 0, -10, 0, -10,
ax_anim 2, 0, 188, 0, 10, 0, 10,
ax_anim 2, 0, 188, 0, -12, 0, -12,
ax_anim 3, 0, 188, 0, 12, 0, 12,
ax_anim 3, 0, 188, 0, -13, 0, -13,
ax_anim 3, 0, 188, 0, 13, 0, 13,
ax_anim 2, 0, 188, 0, -12, 0, -12,
ax_anim 3, 0, 188, 0, 12, 0, 12,
ax_anim 2, 0, 188, 0, -10, 0, -10,
ax_anim 2, 0, 188, 0, 10, 0, 10,
ax_anim 2, 0, 188, 0, -6, 0, -6,
ax_anim 2, 0, 188, 0, 6, 0, 6,
ax_anim 2, 0, 188, 0, 0, 0, 0,
ax_anim_terminator
sHoOhAnims_10_4:
ax_anim 2, 0, 189, 0, 0, 0, 0,
ax_anim 2, 0, 189, -6, -6, -6, -6,
ax_anim 2, 0, 189, 6, 6, 6, 6,
ax_anim 2, 0, 189, -10, -10, -10, -10,
ax_anim 2, 0, 189, 10, 10, 10, 10,
ax_anim 2, 0, 189, -12, -12, -12, -12,
ax_anim 3, 0, 189, 12, 12, 12, 12,
ax_anim 3, 0, 189, -13, -13, -13, -13,
ax_anim 3, 0, 189, 13, 13, 13, 13,
ax_anim 2, 0, 189, -12, -12, -12, -12,
ax_anim 3, 0, 189, 12, 12, 12, 12,
ax_anim 2, 0, 189, -10, -10, -10, -10,
ax_anim 2, 0, 189, 10, 10, 10, 10,
ax_anim 2, 0, 189, -6, -6, -6, -6,
ax_anim 2, 0, 189, 6, 6, 6, 6,
ax_anim 2, 0, 189, 0, 0, 0, 0,
ax_anim_terminator
sHoOhAnims_10_5:
ax_anim 2, 0, 190, 0, 0, 0, 0,
ax_anim 2, 0, 190, 6, 0, 6, 0,
ax_anim 2, 0, 190, -6, 0, -6, 0,
ax_anim 2, 0, 190, 10, 0, 10, 0,
ax_anim 2, 0, 190, -10, 0, -10, 0,
ax_anim 2, 0, 190, 12, 0, 12, 0,
ax_anim 3, 0, 190, -12, 0, -12, 0,
ax_anim 3, 0, 190, 13, 0, 13, 0,
ax_anim 3, 0, 190, -13, 0, -13, 0,
ax_anim 2, 0, 190, 12, 0, 12, 0,
ax_anim 3, 0, 190, -12, 0, -12, 0,
ax_anim 2, 0, 190, 10, 0, 10, 0,
ax_anim 2, 0, 190, -10, 0, -10, 0,
ax_anim 2, 0, 190, 6, 0, 6, 0,
ax_anim 2, 0, 190, -6, 0, -6, 0,
ax_anim 2, 0, 190, 0, 0, 0, 0,
ax_anim_terminator
sHoOhAnims_10_6:
ax_anim 2, 0, 191, 0, 0, 0, 0,
ax_anim 2, 0, 191, 6, -6, 6, -6,
ax_anim 2, 0, 191, -6, 6, -6, 6,
ax_anim 2, 0, 191, 10, -10, 10, -10,
ax_anim 2, 0, 191, -10, 10, -10, 10,
ax_anim 2, 0, 191, 12, -12, 12, -12,
ax_anim 3, 0, 191, -12, 12, -12, 12,
ax_anim 3, 0, 191, 13, -13, 13, -13,
ax_anim 3, 0, 191, -13, 13, -13, 13,
ax_anim 2, 0, 191, 12, -12, 12, -12,
ax_anim 3, 0, 191, -12, 12, -12, 12,
ax_anim 2, 0, 191, 10, -10, 10, -10,
ax_anim 2, 0, 191, -10, 10, -10, 10,
ax_anim 2, 0, 191, 6, -6, 6, -6,
ax_anim 2, 0, 191, -6, 6, -6, 6,
ax_anim 2, 0, 191, 0, 0, 0, 0,
ax_anim_terminator
sHoOhAnims_10_7:
ax_anim 2, 0, 192, 0, 0, 0, 0,
ax_anim 2, 0, 192, 0, -6, 0, -6,
ax_anim 2, 0, 192, 0, 6, 0, 6,
ax_anim 2, 0, 192, 0, -10, 0, -10,
ax_anim 2, 0, 192, 0, 10, 0, 10,
ax_anim 2, 0, 192, 0, -12, 0, -12,
ax_anim 3, 0, 192, 0, 12, 0, 12,
ax_anim 3, 0, 192, 0, -13, 0, -13,
ax_anim 3, 0, 192, 0, 13, 0, 13,
ax_anim 2, 0, 192, 0, -12, 0, -12,
ax_anim 3, 0, 192, 0, 12, 0, 12,
ax_anim 2, 0, 192, 0, -10, 0, -10,
ax_anim 2, 0, 192, 0, 10, 0, 10,
ax_anim 2, 0, 192, 0, -6, 0, -6,
ax_anim 2, 0, 192, 0, 6, 0, 6,
ax_anim 2, 0, 192, 0, 0, 0, 0,
ax_anim_terminator
sHoOhAnims_10_8:
ax_anim 2, 0, 193, 0, 0, 0, 0,
ax_anim 2, 0, 193, -6, -6, -6, -6,
ax_anim 2, 0, 193, 6, 6, 6, 6,
ax_anim 2, 0, 193, -10, -10, -10, -10,
ax_anim 2, 0, 193, 10, 10, 10, 10,
ax_anim 2, 0, 193, -12, -12, -12, -12,
ax_anim 3, 0, 193, 12, 12, 12, 12,
ax_anim 3, 0, 193, -13, -13, -13, -13,
ax_anim 3, 0, 193, 13, 13, 13, 13,
ax_anim 2, 0, 193, -12, -12, -12, -12,
ax_anim 3, 0, 193, 12, 12, 12, 12,
ax_anim 2, 0, 193, -10, -10, -10, -10,
ax_anim 2, 0, 193, 10, 10, 10, 10,
ax_anim 2, 0, 193, -6, -6, -6, -6,
ax_anim 2, 0, 193, 6, 6, 6, 6,
ax_anim 2, 0, 193, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sHoOhAnims_11_1:
ax_anim 2, 0, 194, 0, 0, 0, 0,
ax_anim 1, 0, 195, 0, -10, 0, 0,
ax_anim 2, 0, 196, 0, -16, 0, 0,
ax_anim 3, 0, 196, 0, -20, 0, 0,
ax_anim 4, 0, 196, 0, -21, 0, 0,
ax_anim 4, 0, 196, 0, -23, 0, 0,
ax_anim 3, 0, 195, 0, -22, 0, 0,
ax_anim 2, 0, 194, 0, -18, 0, 0,
ax_anim 1, 0, 194, 0, -11, 0, 0,
ax_anim 2, 2, 197, 0, 9, 0, 0,
ax_anim_terminator
sHoOhAnims_11_2:
ax_anim 2, 0, 198, 0, 0, 0, 0,
ax_anim 1, 0, 199, 0, -10, 0, 0,
ax_anim 2, 0, 200, 0, -16, 0, 0,
ax_anim 3, 0, 200, 0, -20, 0, 0,
ax_anim 4, 0, 200, 0, -21, 0, 0,
ax_anim 4, 0, 200, 0, -23, 0, 0,
ax_anim 3, 0, 199, 0, -22, 0, 0,
ax_anim 2, 0, 198, 0, -18, 0, 0,
ax_anim 1, 0, 198, 0, -8, 0, 0,
ax_anim 2, 2, 201, 0, 12, 0, 0,
ax_anim_terminator
sHoOhAnims_11_3:
ax_anim 2, 0, 202, 0, 0, 0, 0,
ax_anim 1, 0, 203, 0, -10, 0, 0,
ax_anim 2, 0, 204, 0, -16, 0, 0,
ax_anim 3, 0, 204, 0, -20, 0, 0,
ax_anim 4, 0, 204, 0, -21, 0, 0,
ax_anim 4, 0, 204, 0, -23, 0, 0,
ax_anim 3, 0, 203, 0, -22, 0, 0,
ax_anim 2, 0, 202, 0, -18, 0, 0,
ax_anim 1, 0, 202, 0, -8, 0, 0,
ax_anim 2, 2, 205, 0, 0, 0, 0,
ax_anim_terminator
sHoOhAnims_11_4:
ax_anim 2, 0, 206, 0, 0, 0, 0,
ax_anim 1, 0, 207, 0, -10, 0, 0,
ax_anim 2, 0, 208, 0, -16, 0, 0,
ax_anim 3, 0, 208, 0, -20, 0, 0,
ax_anim 4, 0, 208, 0, -21, 0, 0,
ax_anim 4, 0, 208, 0, -22, 0, 0,
ax_anim 3, 0, 207, 0, -21, 0, 0,
ax_anim 2, 0, 206, 0, -17, 0, 0,
ax_anim 1, 0, 206, 0, -8, 0, 0,
ax_anim 2, 2, 209, 0, 0, 0, 0,
ax_anim_terminator
sHoOhAnims_11_5:
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 1, 0, 211, 0, -10, 0, 0,
ax_anim 2, 0, 212, 0, -16, 0, 0,
ax_anim 3, 0, 212, 0, -20, 0, 0,
ax_anim 4, 0, 212, 0, -21, 0, 0,
ax_anim 4, 0, 212, 0, -23, 0, 0,
ax_anim 3, 0, 211, 0, -22, 0, 0,
ax_anim 2, 0, 210, 0, -18, 0, 0,
ax_anim 1, 0, 210, 0, -8, 0, 0,
ax_anim 2, 2, 213, 0, 0, 0, 0,
ax_anim_terminator
sHoOhAnims_11_6:
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 1, 0, 215, 0, -10, 0, 0,
ax_anim 2, 0, 216, 0, -16, 0, 0,
ax_anim 3, 0, 216, 0, -20, 0, 0,
ax_anim 4, 0, 216, 0, -21, 0, 0,
ax_anim 4, 0, 216, 0, -22, 0, 0,
ax_anim 3, 0, 215, 0, -21, 0, 0,
ax_anim 2, 0, 214, 0, -17, 0, 0,
ax_anim 1, 0, 214, 0, -8, 0, 0,
ax_anim 2, 2, 217, 0, 0, 0, 0,
ax_anim_terminator
sHoOhAnims_11_7:
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 1, 0, 219, 0, -10, 0, 0,
ax_anim 2, 0, 220, 0, -16, 0, 0,
ax_anim 3, 0, 220, 0, -20, 0, 0,
ax_anim 4, 0, 220, 0, -21, 0, 0,
ax_anim 4, 0, 220, 0, -23, 0, 0,
ax_anim 3, 0, 219, 0, -22, 0, 0,
ax_anim 2, 0, 218, 0, -18, 0, 0,
ax_anim 1, 0, 218, 0, -8, 0, 0,
ax_anim 2, 2, 221, 0, 0, 0, 0,
ax_anim_terminator
sHoOhAnims_11_8:
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 1, 0, 223, 0, -10, 0, 0,
ax_anim 2, 0, 224, 0, -16, 0, 0,
ax_anim 3, 0, 224, 0, -20, 0, 0,
ax_anim 4, 0, 224, 0, -21, 0, 0,
ax_anim 4, 0, 224, 0, -23, 0, 0,
ax_anim 3, 0, 223, 0, -22, 0, 0,
ax_anim 2, 0, 222, 0, -18, 0, 0,
ax_anim 1, 0, 222, 0, -8, 0, 0,
ax_anim 2, 2, 225, 0, 12, 0, 0,
ax_anim_terminator
.align 2
sHoOhAnims_12_1:
ax_anim 2, 0, 226, 1, 0, 1, 0,
ax_anim 2, 0, 226, 0, 0, 0, 0,
ax_anim 2, 0, 226, 1, 0, 1, 0,
ax_anim 2, 0, 226, 0, 0, 0, 0,
ax_anim 2, 0, 226, 1, 0, 1, 0,
ax_anim 2, 2, 226, 0, 0, 0, 0,
ax_anim 2, 0, 226, 1, 0, 1, 0,
ax_anim 2, 0, 226, 0, 0, 0, 0,
ax_anim 2, 0, 226, 1, 0, 1, 0,
ax_anim 2, 1, 226, 0, 0, 0, 0,
ax_anim_terminator
sHoOhAnims_12_2:
ax_anim 2, 0, 227, 1, -1, 1, 0,
ax_anim 2, 0, 227, 0, 0, 0, 0,
ax_anim 2, 0, 227, 1, -1, 1, 0,
ax_anim 2, 0, 227, 0, 0, 0, 0,
ax_anim 2, 0, 227, 1, -1, 1, 0,
ax_anim 2, 2, 227, 0, 0, 0, 0,
ax_anim 2, 0, 227, 1, -1, 1, 0,
ax_anim 2, 0, 227, 0, 0, 0, 0,
ax_anim 2, 0, 227, 1, -1, 1, 0,
ax_anim 2, 1, 227, 0, 0, 0, 0,
ax_anim_terminator
sHoOhAnims_12_3:
ax_anim 2, 0, 228, 0, -1, 0, -1,
ax_anim 2, 0, 228, 0, 0, 0, 0,
ax_anim 2, 0, 228, 0, -1, 0, -1,
ax_anim 2, 0, 228, 0, 0, 0, 0,
ax_anim 2, 0, 228, 0, -1, 0, -1,
ax_anim 2, 2, 228, 0, 0, 0, 0,
ax_anim 2, 0, 228, 0, -1, 0, -1,
ax_anim 2, 0, 228, 0, 0, 0, 0,
ax_anim 2, 0, 228, 0, -1, 0, -1,
ax_anim 2, 1, 228, 0, 0, 0, 0,
ax_anim_terminator
sHoOhAnims_12_4:
ax_anim 2, 0, 229, -1, -1, -1, -1,
ax_anim 2, 0, 229, 0, 0, 0, 0,
ax_anim 2, 0, 229, -1, -1, -1, -1,
ax_anim 2, 0, 229, 0, 0, 0, 0,
ax_anim 2, 0, 229, -1, -1, -1, -1,
ax_anim 2, 2, 229, 0, 0, 0, 0,
ax_anim 2, 0, 229, -1, -1, -1, -1,
ax_anim 2, 0, 229, 0, 0, 0, 0,
ax_anim 2, 0, 229, -1, -1, -1, -1,
ax_anim 2, 1, 229, 0, 0, 0, 0,
ax_anim_terminator
sHoOhAnims_12_5:
ax_anim 2, 0, 230, 1, 0, 1, 0,
ax_anim 2, 0, 230, 0, 0, 0, 0,
ax_anim 2, 0, 230, 1, 0, 1, 0,
ax_anim 2, 0, 230, 0, 0, 0, 0,
ax_anim 2, 0, 230, 1, 0, 1, 0,
ax_anim 2, 2, 230, 0, 0, 0, 0,
ax_anim 2, 0, 230, 1, 0, 1, 0,
ax_anim 2, 0, 230, 0, 0, 0, 0,
ax_anim 2, 0, 230, 1, 0, 1, 0,
ax_anim 2, 1, 230, 0, 0, 0, 0,
ax_anim_terminator
sHoOhAnims_12_6:
ax_anim 2, 0, 231, 1, -1, 1, -1,
ax_anim 2, 0, 231, 0, 0, 0, 0,
ax_anim 2, 0, 231, 1, -1, 1, -1,
ax_anim 2, 0, 231, 0, 0, 0, 0,
ax_anim 2, 0, 231, 1, -1, 1, -1,
ax_anim 2, 2, 231, 0, 0, 0, 0,
ax_anim 2, 0, 231, 1, -1, 1, -1,
ax_anim 2, 0, 231, 0, 0, 0, 0,
ax_anim 2, 0, 231, 1, -1, 1, -1,
ax_anim 2, 1, 231, 0, 0, 0, 0,
ax_anim_terminator
sHoOhAnims_12_7:
ax_anim 2, 0, 232, 0, -1, 0, -1,
ax_anim 2, 0, 232, 0, 0, 0, 0,
ax_anim 2, 0, 232, 0, -1, 0, -1,
ax_anim 2, 0, 232, 0, 0, 0, 0,
ax_anim 2, 0, 232, 0, -1, 0, -1,
ax_anim 2, 2, 232, 0, 0, 0, 0,
ax_anim 2, 0, 232, 0, -1, 0, -1,
ax_anim 2, 0, 232, 0, 0, 0, 0,
ax_anim 2, 0, 232, 0, -1, 0, -1,
ax_anim 2, 1, 232, 0, 0, 0, 0,
ax_anim_terminator
sHoOhAnims_12_8:
ax_anim 2, 0, 233, -1, -1, -1, -1,
ax_anim 2, 0, 233, 0, 0, 0, 0,
ax_anim 2, 0, 233, -1, -1, -1, -1,
ax_anim 2, 0, 233, 0, 0, 0, 0,
ax_anim 2, 0, 233, -1, -1, -1, -1,
ax_anim 2, 2, 233, 0, 0, 0, 0,
ax_anim 2, 0, 233, -1, -1, -1, -1,
ax_anim 2, 0, 233, 0, 0, 0, 0,
ax_anim 2, 0, 233, -1, -1, -1, -1,
ax_anim 2, 1, 233, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sHoOhAnims_13_1:
ax_anim 2, 0, 234, 0, 0, 0, 0,
ax_anim 2, 0, 235, 0, 0, 0, 0,
ax_anim 2, 0, 236, 0, 0, 0, 0,
ax_anim 2, 0, 237, 0, 0, 0, 0,
ax_anim 2, 0, 238, 0, 0, 0, 0,
ax_anim 2, 0, 239, 0, 0, 0, 0,
ax_anim 2, 0, 240, 0, 0, 0, 0,
ax_anim 2, 0, 241, 0, 0, 0, 0,
ax_anim 2, 2, 234, 0, 0, 0, 0,
ax_anim_terminator
sHoOhAnims_13_2:
ax_anim 2, 0, 241, 0, 0, 0, 0,
ax_anim 2, 0, 234, 0, 0, 0, 0,
ax_anim 2, 0, 235, 0, 0, 0, 0,
ax_anim 2, 0, 236, 0, 0, 0, 0,
ax_anim 2, 0, 237, 0, 0, 0, 0,
ax_anim 2, 0, 238, 0, 0, 0, 0,
ax_anim 2, 0, 239, 0, 0, 0, 0,
ax_anim 2, 0, 240, 0, 0, 0, 0,
ax_anim 2, 2, 241, 0, 0, 0, 0,
ax_anim_terminator
sHoOhAnims_13_3:
ax_anim 2, 0, 240, 0, 0, 0, 0,
ax_anim 2, 0, 241, 0, 0, 0, 0,
ax_anim 2, 0, 234, 0, 0, 0, 0,
ax_anim 2, 0, 235, 0, 0, 0, 0,
ax_anim 2, 0, 236, 0, 0, 0, 0,
ax_anim 2, 0, 237, 0, 0, 0, 0,
ax_anim 2, 0, 238, 0, 0, 0, 0,
ax_anim 2, 0, 239, 0, 0, 0, 0,
ax_anim 2, 2, 240, 0, 0, 0, 0,
ax_anim_terminator
sHoOhAnims_13_4:
ax_anim 2, 0, 239, 0, 0, 0, 0,
ax_anim 2, 0, 240, 0, 0, 0, 0,
ax_anim 2, 0, 241, 0, 0, 0, 0,
ax_anim 2, 0, 234, 0, 0, 0, 0,
ax_anim 2, 0, 235, 0, 0, 0, 0,
ax_anim 2, 0, 236, 0, 0, 0, 0,
ax_anim 2, 0, 237, 0, 0, 0, 0,
ax_anim 2, 0, 238, 0, 0, 0, 0,
ax_anim 2, 2, 239, 0, 0, 0, 0,
ax_anim_terminator
sHoOhAnims_13_5:
ax_anim 2, 0, 238, 0, 0, 0, 0,
ax_anim 2, 0, 239, 0, 0, 0, 0,
ax_anim 2, 0, 240, 0, 0, 0, 0,
ax_anim 2, 0, 241, 0, 0, 0, 0,
ax_anim 2, 0, 234, 0, 0, 0, 0,
ax_anim 2, 0, 235, 0, 0, 0, 0,
ax_anim 2, 0, 236, 0, 0, 0, 0,
ax_anim 2, 0, 237, 0, 0, 0, 0,
ax_anim 2, 2, 238, 0, 0, 0, 0,
ax_anim_terminator
sHoOhAnims_13_6:
ax_anim 2, 0, 237, 0, 0, 0, 0,
ax_anim 2, 0, 238, 0, 0, 0, 0,
ax_anim 2, 0, 239, 0, 0, 0, 0,
ax_anim 2, 0, 240, 0, 0, 0, 0,
ax_anim 2, 0, 241, 0, 0, 0, 0,
ax_anim 2, 0, 234, 0, 0, 0, 0,
ax_anim 2, 0, 235, 0, 0, 0, 0,
ax_anim 2, 0, 236, 0, 0, 0, 0,
ax_anim 2, 2, 237, 0, 0, 0, 0,
ax_anim_terminator
sHoOhAnims_13_7:
ax_anim 2, 0, 236, 0, 0, 0, 0,
ax_anim 2, 0, 237, 0, 0, 0, 0,
ax_anim 2, 0, 238, 0, 0, 0, 0,
ax_anim 2, 0, 239, 0, 0, 0, 0,
ax_anim 2, 0, 240, 0, 0, 0, 0,
ax_anim 2, 0, 241, 0, 0, 0, 0,
ax_anim 2, 0, 234, 0, 0, 0, 0,
ax_anim 2, 0, 235, 0, 0, 0, 0,
ax_anim 2, 2, 236, 0, 0, 0, 0,
ax_anim_terminator
sHoOhAnims_13_8:
ax_anim 2, 0, 235, 0, 0, 0, 0,
ax_anim 2, 0, 236, 0, 0, 0, 0,
ax_anim 2, 0, 237, 0, 0, 0, 0,
ax_anim 2, 0, 238, 0, 0, 0, 0,
ax_anim 2, 0, 239, 0, 0, 0, 0,
ax_anim 2, 0, 240, 0, 0, 0, 0,
ax_anim 2, 0, 241, 0, 0, 0, 0,
ax_anim 2, 0, 234, 0, 0, 0, 0,
ax_anim 2, 2, 235, 0, 0, 0, 0,
ax_anim_terminator
sHoOhGfx1:
.incbin "baserom.gba", 0x1034D5C, 0xE0
sHoOhGfx1_1:
.incbin "baserom.gba", 0x1034E3C, 0xE0
sHoOhGfx1_2:
.incbin "baserom.gba", 0x1034F1C, 0xE0
sHoOhGfx1_3:
.incbin "baserom.gba", 0x1034FFC, 0xE0
sHoOhGfx1_4:
.incbin "baserom.gba", 0x10350DC, 0xE0
sHoOhGfx1_5:
.incbin "baserom.gba", 0x10351BC, 0xE0
sHoOhGfx1_6:
.incbin "baserom.gba", 0x103529C, 0xA0
sHoOhGfx1_7:
.incbin "baserom.gba", 0x103533C, 0x60
sHoOhSprites1:
ax_sprite sHoOhGfx1, 0xe0
ax_sprite 0, 0x20
ax_sprite sHoOhGfx1_1, 0xe0
ax_sprite 0, 0x20
ax_sprite sHoOhGfx1_2, 0xe0
ax_sprite 0, 0x20
ax_sprite sHoOhGfx1_3, 0xe0
ax_sprite 0, 0x20
ax_sprite sHoOhGfx1_4, 0xe0
ax_sprite 0, 0x20
ax_sprite sHoOhGfx1_5, 0xe0
ax_sprite 0, 0x40
ax_sprite sHoOhGfx1_6, 0xa0
ax_sprite 0, 0x80
ax_sprite sHoOhGfx1_7, 0x60
ax_sprite 0, 0x60
ax_sprite_terminator
sHoOhGfx2:
.incbin "baserom.gba", 0x1035424, 0x60
sHoOhSprites2:
ax_sprite sHoOhGfx2, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sHoOhGfx3:
.incbin "baserom.gba", 0x103549C, 0xE0
sHoOhSprites3:
ax_sprite 0, 0x20
ax_sprite sHoOhGfx3, 0xe0
ax_sprite_terminator
sHoOhGfx4:
.incbin "baserom.gba", 0x1035594, 0x60
sHoOhGfx4_1:
.incbin "baserom.gba", 0x10355F4, 0x80
sHoOhSprites4:
ax_sprite sHoOhGfx4, 0x60
ax_sprite 0, 0x20
ax_sprite sHoOhGfx4_1, 0x80
ax_sprite_terminator
sHoOhGfx5:
.incbin "baserom.gba", 0x1035694, 0x20
sHoOhSprites5:
ax_sprite sHoOhGfx5, 0x20
ax_sprite_terminator
sHoOhGfx6:
.incbin "baserom.gba", 0x10356C4, 0x20
sHoOhSprites6:
ax_sprite sHoOhGfx6, 0x20
ax_sprite_terminator
sHoOhGfx7:
.incbin "baserom.gba", 0x10356F4, 0x200
sHoOhGfx7_1:
.incbin "baserom.gba", 0x10358F4, 0xC0
sHoOhGfx7_2:
.incbin "baserom.gba", 0x10359B4, 0x80
sHoOhSprites7:
ax_sprite sHoOhGfx7, 0x200
ax_sprite 0, 0x20
ax_sprite sHoOhGfx7_1, 0xc0
ax_sprite 0, 0x60
ax_sprite sHoOhGfx7_2, 0x80
ax_sprite 0, 0x40
ax_sprite_terminator
sHoOhGfx8:
.incbin "baserom.gba", 0x1035A6C, 0x80
sHoOhGfx8_1:
.incbin "baserom.gba", 0x1035AEC, 0xC0
sHoOhGfx8_2:
.incbin "baserom.gba", 0x1035BAC, 0xC0
sHoOhGfx8_3:
.incbin "baserom.gba", 0x1035C6C, 0xC0
sHoOhGfx8_4:
.incbin "baserom.gba", 0x1035D2C, 0xC0
sHoOhGfx8_5:
.incbin "baserom.gba", 0x1035DEC, 0xC0
sHoOhGfx8_6:
.incbin "baserom.gba", 0x1035EAC, 0x20
sHoOhGfx8_7:
.incbin "baserom.gba", 0x1035ECC, 0x20
sHoOhGfx8_8:
.incbin "baserom.gba", 0x1035EEC, 0x20
sHoOhSprites8:
ax_sprite 0, 0x20
ax_sprite sHoOhGfx8, 0x80
ax_sprite 0, 0x60
ax_sprite sHoOhGfx8_1, 0xc0
ax_sprite 0, 0x40
ax_sprite sHoOhGfx8_2, 0xc0
ax_sprite 0, 0x40
ax_sprite sHoOhGfx8_3, 0xc0
ax_sprite 0, 0x40
ax_sprite sHoOhGfx8_4, 0xc0
ax_sprite 0, 0x40
ax_sprite sHoOhGfx8_5, 0xc0
ax_sprite 0, 0x40
ax_sprite sHoOhGfx8_6, 0x20
ax_sprite 0, 0x20
ax_sprite sHoOhGfx8_7, 0x20
ax_sprite 0, 0x40
ax_sprite sHoOhGfx8_8, 0x20
ax_sprite 0, 0x140
ax_sprite_terminator
sHoOhGfx9:
.incbin "baserom.gba", 0x1035FAC, 0xA0
sHoOhGfx9_1:
.incbin "baserom.gba", 0x103604C, 0xE0
sHoOhGfx9_2:
.incbin "baserom.gba", 0x103612C, 0xE0
sHoOhGfx9_3:
.incbin "baserom.gba", 0x103620C, 0xE0
sHoOhGfx9_4:
.incbin "baserom.gba", 0x10362EC, 0xC0
sHoOhGfx9_5:
.incbin "baserom.gba", 0x10363AC, 0xE0
sHoOhGfx9_6:
.incbin "baserom.gba", 0x103648C, 0xE0
sHoOhSprites9:
ax_sprite sHoOhGfx9, 0xa0
ax_sprite 0, 0x60
ax_sprite sHoOhGfx9_1, 0xe0
ax_sprite 0, 0x20
ax_sprite sHoOhGfx9_2, 0xe0
ax_sprite 0, 0x20
ax_sprite sHoOhGfx9_3, 0xe0
ax_sprite 0, 0x40
ax_sprite sHoOhGfx9_4, 0xc0
ax_sprite 0, 0x20
ax_sprite sHoOhGfx9_5, 0xe0
ax_sprite 0, 0x20
ax_sprite sHoOhGfx9_6, 0xe0
ax_sprite 0, 0x120
ax_sprite_terminator
sHoOhGfx10:
.incbin "baserom.gba", 0x10365E4, 0x60
sHoOhGfx10_1:
.incbin "baserom.gba", 0x1036644, 0x80
sHoOhGfx10_2:
.incbin "baserom.gba", 0x10366C4, 0x200
sHoOhGfx10_3:
.incbin "baserom.gba", 0x10368C4, 0xE0
sHoOhGfx10_4:
.incbin "baserom.gba", 0x10369A4, 0xE0
sHoOhGfx10_5:
.incbin "baserom.gba", 0x1036A84, 0xC0
sHoOhSprites10:
ax_sprite 0, 0x60
ax_sprite sHoOhGfx10, 0x60
ax_sprite 0, 0xa0
ax_sprite sHoOhGfx10_1, 0x80
ax_sprite 0, 0x20
ax_sprite sHoOhGfx10_2, 0x200
ax_sprite 0, 0x20
ax_sprite sHoOhGfx10_3, 0xe0
ax_sprite 0, 0x20
ax_sprite sHoOhGfx10_4, 0xe0
ax_sprite 0, 0x20
ax_sprite sHoOhGfx10_5, 0xc0
ax_sprite 0, 0x120
ax_sprite_terminator
sHoOhGfx11:
.incbin "baserom.gba", 0x1036BB4, 0x60
sHoOhGfx11_1:
.incbin "baserom.gba", 0x1036C14, 0xA0
sHoOhGfx11_2:
.incbin "baserom.gba", 0x1036CB4, 0xA0
sHoOhGfx11_3:
.incbin "baserom.gba", 0x1036D54, 0xE0
sHoOhGfx11_4:
.incbin "baserom.gba", 0x1036E34, 0xE0
sHoOhGfx11_5:
.incbin "baserom.gba", 0x1036F14, 0xE0
sHoOhGfx11_6:
.incbin "baserom.gba", 0x1036FF4, 0x40
sHoOhGfx11_7:
.incbin "baserom.gba", 0x1037034, 0x60
sHoOhGfx11_8:
.incbin "baserom.gba", 0x1037094, 0x40
sHoOhSprites11:
ax_sprite 0, 0x60
ax_sprite sHoOhGfx11, 0x60
ax_sprite 0, 0x80
ax_sprite sHoOhGfx11_1, 0xa0
ax_sprite 0, 0x60
ax_sprite sHoOhGfx11_2, 0xa0
ax_sprite 0, 0x20
ax_sprite sHoOhGfx11_3, 0xe0
ax_sprite 0, 0x20
ax_sprite sHoOhGfx11_4, 0xe0
ax_sprite 0, 0x20
ax_sprite sHoOhGfx11_5, 0xe0
ax_sprite 0, 0x20
ax_sprite sHoOhGfx11_6, 0x40
ax_sprite 0, 0x20
ax_sprite sHoOhGfx11_7, 0x60
ax_sprite 0, 0xc0
ax_sprite sHoOhGfx11_8, 0x40
ax_sprite 0, 0x40
ax_sprite_terminator
sHoOhGfx12:
.incbin "baserom.gba", 0x1037174, 0x40
sHoOhGfx12_1:
.incbin "baserom.gba", 0x10371B4, 0x40
sHoOhGfx12_2:
.incbin "baserom.gba", 0x10371F4, 0x60
sHoOhGfx12_3:
.incbin "baserom.gba", 0x1037254, 0x40
sHoOhGfx12_4:
.incbin "baserom.gba", 0x1037294, 0x60
sHoOhGfx12_5:
.incbin "baserom.gba", 0x10372F4, 0x2E0
sHoOhGfx12_6:
.incbin "baserom.gba", 0x10375D4, 0x40
sHoOhGfx12_7:
.incbin "baserom.gba", 0x1037614, 0x60
sHoOhGfx12_8:
.incbin "baserom.gba", 0x1037674, 0x20
sHoOhSprites12:
ax_sprite 0, 0x40
ax_sprite sHoOhGfx12, 0x40
ax_sprite 0, 0xc0
ax_sprite sHoOhGfx12_1, 0x40
ax_sprite 0, 0x20
ax_sprite sHoOhGfx12_2, 0x60
ax_sprite 0, 0x40
ax_sprite sHoOhGfx12_3, 0x40
ax_sprite 0, 0x20
ax_sprite sHoOhGfx12_4, 0x60
ax_sprite 0, 0x20
ax_sprite sHoOhGfx12_5, 0x2e0
ax_sprite 0, 0x40
ax_sprite sHoOhGfx12_6, 0x40
ax_sprite 0, 0x20
ax_sprite sHoOhGfx12_7, 0x60
ax_sprite 0, 0xc0
ax_sprite sHoOhGfx12_8, 0x20
ax_sprite 0, 0x20
ax_sprite_terminator
sHoOhGfx13:
.incbin "baserom.gba", 0x1037734, 0x80
sHoOhGfx13_1:
.incbin "baserom.gba", 0x10377B4, 0x20
sHoOhSprites13:
ax_sprite sHoOhGfx13, 0x80
ax_sprite 0, 0x60
ax_sprite sHoOhGfx13_1, 0x20
ax_sprite_terminator
sHoOhGfx14:
.incbin "baserom.gba", 0x10377F4, 0x20
sHoOhGfx14_1:
.incbin "baserom.gba", 0x1037814, 0x60
sHoOhGfx14_2:
.incbin "baserom.gba", 0x1037874, 0x40
sHoOhGfx14_3:
.incbin "baserom.gba", 0x10378B4, 0x60
sHoOhGfx14_4:
.incbin "baserom.gba", 0x1037914, 0x1E0
sHoOhSprites14:
ax_sprite 0, 0x40
ax_sprite sHoOhGfx14, 0x20
ax_sprite 0, 0x40
ax_sprite sHoOhGfx14_1, 0x60
ax_sprite 0, 0x40
ax_sprite sHoOhGfx14_2, 0x40
ax_sprite 0, 0x20
ax_sprite sHoOhGfx14_3, 0x60
ax_sprite 0, 0x20
ax_sprite sHoOhGfx14_4, 0x1e0
ax_sprite_terminator
sHoOhGfx15:
.incbin "baserom.gba", 0x1037B4C, 0x80
sHoOhGfx15_1:
.incbin "baserom.gba", 0x1037BCC, 0x40
sHoOhSprites15:
ax_sprite sHoOhGfx15, 0x80
ax_sprite 0, 0x40
ax_sprite sHoOhGfx15_1, 0x40
ax_sprite_terminator
sHoOhGfx16:
.incbin "baserom.gba", 0x1037C2C, 0x60
sHoOhGfx16_1:
.incbin "baserom.gba", 0x1037C8C, 0x2A0
sHoOhSprites16:
ax_sprite 0, 0xa0
ax_sprite sHoOhGfx16, 0x60
ax_sprite 0, 0x20
ax_sprite sHoOhGfx16_1, 0x2a0
ax_sprite 0, 0x40
ax_sprite_terminator
sHoOhGfx17:
.incbin "baserom.gba", 0x1037F5C, 0x40
sHoOhGfx17_1:
.incbin "baserom.gba", 0x1037F9C, 0x100
sHoOhGfx17_2:
.incbin "baserom.gba", 0x103809C, 0x60
sHoOhSprites17:
ax_sprite 0, 0x20
ax_sprite sHoOhGfx17, 0x40
ax_sprite 0, 0x20
ax_sprite sHoOhGfx17_1, 0x100
ax_sprite 0, 0x20
ax_sprite sHoOhGfx17_2, 0x60
ax_sprite_terminator
sHoOhGfx18:
.incbin "baserom.gba", 0x1038134, 0x40
sHoOhGfx18_1:
.incbin "baserom.gba", 0x1038174, 0x20
sHoOhSprites18:
ax_sprite sHoOhGfx18, 0x40
ax_sprite 0, 0x20
ax_sprite sHoOhGfx18_1, 0x20
ax_sprite_terminator
sHoOhGfx19:
.incbin "baserom.gba", 0x10381B4, 0xA0
sHoOhGfx19_1:
.incbin "baserom.gba", 0x1038254, 0x60
sHoOhGfx19_2:
.incbin "baserom.gba", 0x10382B4, 0x60
sHoOhGfx19_3:
.incbin "baserom.gba", 0x1038314, 0x200
sHoOhGfx19_4:
.incbin "baserom.gba", 0x1038514, 0xE0
sHoOhGfx19_5:
.incbin "baserom.gba", 0x10385F4, 0xE0
sHoOhGfx19_6:
.incbin "baserom.gba", 0x10386D4, 0xC0
sHoOhGfx19_7:
.incbin "baserom.gba", 0x1038794, 0x60
sHoOhSprites19:
ax_sprite 0, 0x20
ax_sprite sHoOhGfx19, 0xa0
ax_sprite 0, 0x40
ax_sprite sHoOhGfx19_1, 0x60
ax_sprite 0, 0x20
ax_sprite sHoOhGfx19_2, 0x60
ax_sprite 0, 0x20
ax_sprite sHoOhGfx19_3, 0x200
ax_sprite 0, 0x20
ax_sprite sHoOhGfx19_4, 0xe0
ax_sprite 0, 0x20
ax_sprite sHoOhGfx19_5, 0xe0
ax_sprite 0, 0x40
ax_sprite sHoOhGfx19_6, 0xc0
ax_sprite 0, 0x80
ax_sprite sHoOhGfx19_7, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sHoOhGfx20:
.incbin "baserom.gba", 0x1038884, 0x20
sHoOhSprites20:
ax_sprite sHoOhGfx20, 0x20
ax_sprite_terminator
sHoOhGfx21:
.incbin "baserom.gba", 0x10388B4, 0x20
sHoOhGfx21_1:
.incbin "baserom.gba", 0x10388D4, 0x100
sHoOhSprites21:
ax_sprite 0, 0xc0
ax_sprite sHoOhGfx21, 0x20
ax_sprite 0, 0x20
ax_sprite sHoOhGfx21_1, 0x100
ax_sprite_terminator
sHoOhGfx22:
.incbin "baserom.gba", 0x10389FC, 0xC0
sHoOhSprites22:
ax_sprite 0, 0x40
ax_sprite sHoOhGfx22, 0xc0
ax_sprite_terminator
sHoOhGfx23:
.incbin "baserom.gba", 0x1038AD4, 0x200
sHoOhGfx23_1:
.incbin "baserom.gba", 0x1038CD4, 0xA0
sHoOhGfx23_2:
.incbin "baserom.gba", 0x1038D74, 0x60
sHoOhSprites23:
ax_sprite sHoOhGfx23, 0x200
ax_sprite 0, 0x60
ax_sprite sHoOhGfx23_1, 0xa0
ax_sprite 0, 0x80
ax_sprite sHoOhGfx23_2, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sHoOhGfx24:
.incbin "baserom.gba", 0x1038E0C, 0x100
sHoOhSprites24:
ax_sprite sHoOhGfx24, 0x100
ax_sprite_terminator
sHoOhGfx25:
.incbin "baserom.gba", 0x1038F1C, 0x40
sHoOhGfx25_1:
.incbin "baserom.gba", 0x1038F5C, 0x60
sHoOhSprites25:
ax_sprite 0, 0x40
ax_sprite sHoOhGfx25, 0x40
ax_sprite 0, 0x20
ax_sprite sHoOhGfx25_1, 0x60
ax_sprite_terminator
sHoOhGfx26:
.incbin "baserom.gba", 0x1038FE4, 0xE0
sHoOhGfx26_1:
.incbin "baserom.gba", 0x10390C4, 0xE0
sHoOhGfx26_2:
.incbin "baserom.gba", 0x10391A4, 0xE0
sHoOhGfx26_3:
.incbin "baserom.gba", 0x1039284, 0x40
sHoOhGfx26_4:
.incbin "baserom.gba", 0x10392C4, 0x60
sHoOhSprites26:
ax_sprite 0, 0x20
ax_sprite sHoOhGfx26, 0xe0
ax_sprite 0, 0x20
ax_sprite sHoOhGfx26_1, 0xe0
ax_sprite 0, 0x20
ax_sprite sHoOhGfx26_2, 0xe0
ax_sprite 0, 0x20
ax_sprite sHoOhGfx26_3, 0x40
ax_sprite 0, 0x20
ax_sprite sHoOhGfx26_4, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sHoOhGfx27:
.incbin "baserom.gba", 0x1039384, 0xE0
sHoOhGfx27_1:
.incbin "baserom.gba", 0x1039464, 0x60
sHoOhGfx27_2:
.incbin "baserom.gba", 0x10394C4, 0x60
sHoOhGfx27_3:
.incbin "baserom.gba", 0x1039524, 0xE0
sHoOhGfx27_4:
.incbin "baserom.gba", 0x1039604, 0xE0
sHoOhGfx27_5:
.incbin "baserom.gba", 0x10396E4, 0xE0
sHoOhGfx27_6:
.incbin "baserom.gba", 0x10397C4, 0xE0
sHoOhGfx27_7:
.incbin "baserom.gba", 0x10398A4, 0xC0
sHoOhGfx27_8:
.incbin "baserom.gba", 0x1039964, 0xA0
sHoOhSprites27:
ax_sprite sHoOhGfx27, 0xe0
ax_sprite 0, 0x20
ax_sprite sHoOhGfx27_1, 0x60
ax_sprite 0, 0x20
ax_sprite sHoOhGfx27_2, 0x60
ax_sprite 0, 0x20
ax_sprite sHoOhGfx27_3, 0xe0
ax_sprite 0, 0x20
ax_sprite sHoOhGfx27_4, 0xe0
ax_sprite 0, 0x20
ax_sprite sHoOhGfx27_5, 0xe0
ax_sprite 0, 0x20
ax_sprite sHoOhGfx27_6, 0xe0
ax_sprite 0, 0x20
ax_sprite sHoOhGfx27_7, 0xc0
ax_sprite 0, 0x60
ax_sprite sHoOhGfx27_8, 0xa0
ax_sprite 0, 0x40
ax_sprite_terminator
sHoOhGfx28:
.incbin "baserom.gba", 0x1039A9C, 0x20
sHoOhSprites28:
ax_sprite sHoOhGfx28, 0x20
ax_sprite_terminator
sHoOhGfx29:
.incbin "baserom.gba", 0x1039ACC, 0x40
sHoOhSprites29:
ax_sprite sHoOhGfx29, 0x40
ax_sprite_terminator
sHoOhGfx30:
.incbin "baserom.gba", 0x1039B1C, 0x40
sHoOhGfx30_1:
.incbin "baserom.gba", 0x1039B5C, 0xA0
sHoOhSprites30:
ax_sprite sHoOhGfx30, 0x40
ax_sprite 0, 0x20
ax_sprite sHoOhGfx30_1, 0xa0
ax_sprite_terminator
sHoOhGfx31:
.incbin "baserom.gba", 0x1039C1C, 0x20
sHoOhGfx31_1:
.incbin "baserom.gba", 0x1039C3C, 0xC0
sHoOhSprites31:
ax_sprite sHoOhGfx31, 0x20
ax_sprite 0, 0x20
ax_sprite sHoOhGfx31_1, 0xc0
ax_sprite_terminator
sHoOhGfx32:
.incbin "baserom.gba", 0x1039D1C, 0x200
sHoOhGfx32_1:
.incbin "baserom.gba", 0x1039F1C, 0xC0
sHoOhGfx32_2:
.incbin "baserom.gba", 0x1039FDC, 0x80
sHoOhSprites32:
ax_sprite sHoOhGfx32, 0x200
ax_sprite 0, 0x20
ax_sprite sHoOhGfx32_1, 0xc0
ax_sprite 0, 0x60
ax_sprite sHoOhGfx32_2, 0x80
ax_sprite 0, 0x40
ax_sprite_terminator
sHoOhGfx33:
.incbin "baserom.gba", 0x103A094, 0x20
sHoOhSprites33:
ax_sprite sHoOhGfx33, 0x20
ax_sprite_terminator
sHoOhGfx34:
.incbin "baserom.gba", 0x103A0C4, 0x20
sHoOhGfx34_1:
.incbin "baserom.gba", 0x103A0E4, 0x40
sHoOhSprites34:
ax_sprite sHoOhGfx34, 0x20
ax_sprite 0, 0x20
ax_sprite sHoOhGfx34_1, 0x40
ax_sprite_terminator
sHoOhGfx35:
.incbin "baserom.gba", 0x103A144, 0x40
sHoOhGfx35_1:
.incbin "baserom.gba", 0x103A184, 0x60
sHoOhSprites35:
ax_sprite 0, 0x40
ax_sprite sHoOhGfx35, 0x40
ax_sprite 0, 0x20
ax_sprite sHoOhGfx35_1, 0x60
ax_sprite_terminator
sHoOhGfx36:
.incbin "baserom.gba", 0x103A20C, 0xC0
sHoOhGfx36_1:
.incbin "baserom.gba", 0x103A2CC, 0xE0
sHoOhGfx36_2:
.incbin "baserom.gba", 0x103A3AC, 0xE0
sHoOhGfx36_3:
.incbin "baserom.gba", 0x103A48C, 0xE0
sHoOhSprites36:
ax_sprite sHoOhGfx36, 0xc0
ax_sprite 0, 0x40
ax_sprite sHoOhGfx36_1, 0xe0
ax_sprite 0, 0x20
ax_sprite sHoOhGfx36_2, 0xe0
ax_sprite 0, 0x20
ax_sprite sHoOhGfx36_3, 0xe0
ax_sprite 0, 0x20
ax_sprite_terminator
sHoOhGfx37:
.incbin "baserom.gba", 0x103A5B4, 0x300
sHoOhGfx37_1:
.incbin "baserom.gba", 0x103A8B4, 0x40
sHoOhGfx37_2:
.incbin "baserom.gba", 0x103A8F4, 0x40
sHoOhSprites37:
ax_sprite sHoOhGfx37, 0x300
ax_sprite 0, 0x20
ax_sprite sHoOhGfx37_1, 0x40
ax_sprite 0, 0x40
ax_sprite sHoOhGfx37_2, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sHoOhGfx38:
.incbin "baserom.gba", 0x103A96C, 0x100
sHoOhSprites38:
ax_sprite sHoOhGfx38, 0x100
ax_sprite_terminator
sHoOhGfx39:
.incbin "baserom.gba", 0x103AA7C, 0x80
sHoOhGfx39_1:
.incbin "baserom.gba", 0x103AAFC, 0x200
sHoOhGfx39_2:
.incbin "baserom.gba", 0x103ACFC, 0xE0
sHoOhSprites39:
ax_sprite 0, 0x60
ax_sprite sHoOhGfx39, 0x80
ax_sprite 0, 0x20
ax_sprite sHoOhGfx39_1, 0x200
ax_sprite 0, 0x20
ax_sprite sHoOhGfx39_2, 0xe0
ax_sprite_terminator
sHoOhGfx40:
.incbin "baserom.gba", 0x103AE14, 0xC0
sHoOhSprites40:
ax_sprite 0, 0x20
ax_sprite sHoOhGfx40, 0xc0
ax_sprite 0, 0x20
ax_sprite_terminator
sHoOhGfx41:
.incbin "baserom.gba", 0x103AEF4, 0x80
sHoOhGfx41_1:
.incbin "baserom.gba", 0x103AF74, 0x20
sHoOhSprites41:
ax_sprite sHoOhGfx41, 0x80
ax_sprite 0, 0x60
ax_sprite sHoOhGfx41_1, 0x20
ax_sprite_terminator
sHoOhGfx42:
.incbin "baserom.gba", 0x103AFB4, 0x20
sHoOhSprites42:
ax_sprite sHoOhGfx42, 0x20
ax_sprite_terminator
sHoOhGfx43:
.incbin "baserom.gba", 0x103AFE4, 0x20
sHoOhSprites43:
ax_sprite sHoOhGfx43, 0x20
ax_sprite_terminator
sHoOhGfx44:
.incbin "baserom.gba", 0x103B014, 0xA0
sHoOhGfx44_1:
.incbin "baserom.gba", 0x103B0B4, 0x220
sHoOhGfx44_2:
.incbin "baserom.gba", 0x103B2D4, 0xA0
sHoOhSprites44:
ax_sprite 0, 0x60
ax_sprite sHoOhGfx44, 0xa0
ax_sprite 0, 0x20
ax_sprite sHoOhGfx44_1, 0x220
ax_sprite 0, 0x20
ax_sprite sHoOhGfx44_2, 0xa0
ax_sprite_terminator
sHoOhGfx45:
.incbin "baserom.gba", 0x103B3AC, 0x80
sHoOhSprites45:
ax_sprite sHoOhGfx45, 0x80
ax_sprite_terminator
sHoOhGfx46:
.incbin "baserom.gba", 0x103B43C, 0xA0
sHoOhGfx46_1:
.incbin "baserom.gba", 0x103B4DC, 0xE0
sHoOhGfx46_2:
.incbin "baserom.gba", 0x103B5BC, 0x1E0
sHoOhSprites46:
ax_sprite 0, 0x40
ax_sprite sHoOhGfx46, 0xa0
ax_sprite 0, 0x40
ax_sprite sHoOhGfx46_1, 0xe0
ax_sprite 0, 0x20
ax_sprite sHoOhGfx46_2, 0x1e0
ax_sprite_terminator
sHoOhGfx47:
.incbin "baserom.gba", 0x103B7D4, 0x80
sHoOhSprites47:
ax_sprite sHoOhGfx47, 0x80
ax_sprite_terminator
sHoOhGfx48:
.incbin "baserom.gba", 0x103B864, 0xE0
sHoOhSprites48:
ax_sprite sHoOhGfx48, 0xe0
ax_sprite 0, 0x20
ax_sprite_terminator
sHoOhGfx49:
.incbin "baserom.gba", 0x103B95C, 0x20
sHoOhGfx49_1:
.incbin "baserom.gba", 0x103B97C, 0x60
sHoOhGfx49_2:
.incbin "baserom.gba", 0x103B9DC, 0x60
sHoOhGfx49_3:
.incbin "baserom.gba", 0x103BA3C, 0x1E0
sHoOhSprites49:
ax_sprite 0, 0xa0
ax_sprite sHoOhGfx49, 0x20
ax_sprite 0, 0x40
ax_sprite sHoOhGfx49_1, 0x60
ax_sprite 0, 0x20
ax_sprite sHoOhGfx49_2, 0x60
ax_sprite 0, 0x20
ax_sprite sHoOhGfx49_3, 0x1e0
ax_sprite 0, 0x20
ax_sprite_terminator
sHoOhGfx50:
.incbin "baserom.gba", 0x103BC6C, 0x80
sHoOhSprites50:
ax_sprite sHoOhGfx50, 0x80
ax_sprite_terminator
sHoOhGfx51:
.incbin "baserom.gba", 0x103BCFC, 0x100
sHoOhSprites51:
ax_sprite sHoOhGfx51, 0x100
ax_sprite_terminator
sHoOhGfx52:
.incbin "baserom.gba", 0x103BE0C, 0xC0
sHoOhGfx52_1:
.incbin "baserom.gba", 0x103BECC, 0xC0
sHoOhGfx52_2:
.incbin "baserom.gba", 0x103BF8C, 0xC0
sHoOhGfx52_3:
.incbin "baserom.gba", 0x103C04C, 0x60
sHoOhSprites52:
ax_sprite 0, 0x20
ax_sprite sHoOhGfx52, 0xc0
ax_sprite 0, 0x40
ax_sprite sHoOhGfx52_1, 0xc0
ax_sprite 0, 0x40
ax_sprite sHoOhGfx52_2, 0xc0
ax_sprite 0, 0x80
ax_sprite sHoOhGfx52_3, 0x60
ax_sprite 0, 0x40
ax_sprite_terminator
sHoOhGfx53:
.incbin "baserom.gba", 0x103C0FC, 0x200
sHoOhSprites53:
ax_sprite sHoOhGfx53, 0x200
ax_sprite_terminator
sHoOhGfx54:
.incbin "baserom.gba", 0x103C30C, 0x80
sHoOhGfx54_1:
.incbin "baserom.gba", 0x103C38C, 0x20
sHoOhSprites54:
ax_sprite sHoOhGfx54, 0x80
ax_sprite 0, 0x20
ax_sprite sHoOhGfx54_1, 0x20
ax_sprite 0, 0x40
ax_sprite_terminator
sHoOhGfx55:
.incbin "baserom.gba", 0x103C3D4, 0x80
sHoOhSprites55:
ax_sprite sHoOhGfx55, 0x80
ax_sprite_terminator
sHoOhGfx56:
.incbin "baserom.gba", 0x103C464, 0x80
sHoOhSprites56:
ax_sprite sHoOhGfx56, 0x80
ax_sprite_terminator
sHoOhGfx57:
.incbin "baserom.gba", 0x103C4F4, 0xC0
sHoOhGfx57_1:
.incbin "baserom.gba", 0x103C5B4, 0xC0
sHoOhGfx57_2:
.incbin "baserom.gba", 0x103C674, 0xE0
sHoOhGfx57_3:
.incbin "baserom.gba", 0x103C754, 0xA0
sHoOhSprites57:
ax_sprite sHoOhGfx57, 0xc0
ax_sprite 0, 0x40
ax_sprite sHoOhGfx57_1, 0xc0
ax_sprite 0, 0x40
ax_sprite sHoOhGfx57_2, 0xe0
ax_sprite 0, 0x60
ax_sprite sHoOhGfx57_3, 0xa0
ax_sprite 0, 0x20
ax_sprite_terminator
sHoOhGfx58:
.incbin "baserom.gba", 0x103C83C, 0x80
sHoOhSprites58:
ax_sprite sHoOhGfx58, 0x80
ax_sprite_terminator
sHoOhGfx59:
.incbin "baserom.gba", 0x103C8CC, 0xA0
sHoOhGfx59_1:
.incbin "baserom.gba", 0x103C96C, 0xE0
sHoOhGfx59_2:
.incbin "baserom.gba", 0x103CA4C, 0xE0
sHoOhGfx59_3:
.incbin "baserom.gba", 0x103CB2C, 0xE0
sHoOhGfx59_4:
.incbin "baserom.gba", 0x103CC0C, 0xC0
sHoOhGfx59_5:
.incbin "baserom.gba", 0x103CCCC, 0xE0
sHoOhGfx59_6:
.incbin "baserom.gba", 0x103CDAC, 0xE0
sHoOhSprites59:
ax_sprite sHoOhGfx59, 0xa0
ax_sprite 0, 0x60
ax_sprite sHoOhGfx59_1, 0xe0
ax_sprite 0, 0x20
ax_sprite sHoOhGfx59_2, 0xe0
ax_sprite 0, 0x20
ax_sprite sHoOhGfx59_3, 0xe0
ax_sprite 0, 0x40
ax_sprite sHoOhGfx59_4, 0xc0
ax_sprite 0, 0x20
ax_sprite sHoOhGfx59_5, 0xe0
ax_sprite 0, 0x20
ax_sprite sHoOhGfx59_6, 0xe0
ax_sprite 0, 0x120
ax_sprite_terminator
sHoOhGfx60:
.incbin "baserom.gba", 0x103CF04, 0x60
sHoOhGfx60_1:
.incbin "baserom.gba", 0x103CF64, 0x80
sHoOhGfx60_2:
.incbin "baserom.gba", 0x103CFE4, 0xA0
sHoOhGfx60_3:
.incbin "baserom.gba", 0x103D084, 0xC0
sHoOhSprites60:
ax_sprite 0, 0x20
ax_sprite sHoOhGfx60, 0x60
ax_sprite 0, 0xa0
ax_sprite sHoOhGfx60_1, 0x80
ax_sprite 0, 0x80
ax_sprite sHoOhGfx60_2, 0xa0
ax_sprite 0, 0x60
ax_sprite sHoOhGfx60_3, 0xc0
ax_sprite 0, 0x20
ax_sprite_terminator
sHoOhGfx61:
.incbin "baserom.gba", 0x103D194, 0x80
sHoOhGfx61_1:
.incbin "baserom.gba", 0x103D214, 0x60
sHoOhSprites61:
ax_sprite sHoOhGfx61, 0x80
ax_sprite 0, 0x20
ax_sprite sHoOhGfx61_1, 0x60
ax_sprite_terminator
sHoOhGfx62:
.incbin "baserom.gba", 0x103D294, 0x60
sHoOhSprites62:
ax_sprite 0, 0x20
ax_sprite sHoOhGfx62, 0x60
ax_sprite_terminator
sHoOhGfx63:
.incbin "baserom.gba", 0x103D30C, 0x40
sHoOhGfx63_1:
.incbin "baserom.gba", 0x103D34C, 0x40
sHoOhGfx63_2:
.incbin "baserom.gba", 0x103D38C, 0x60
sHoOhGfx63_3:
.incbin "baserom.gba", 0x103D3EC, 0x60
sHoOhGfx63_4:
.incbin "baserom.gba", 0x103D44C, 0x260
sHoOhGfx63_5:
.incbin "baserom.gba", 0x103D6AC, 0xE0
sHoOhGfx63_6:
.incbin "baserom.gba", 0x103D78C, 0x40
sHoOhGfx63_7:
.incbin "baserom.gba", 0x103D7CC, 0x60
sHoOhGfx63_8:
.incbin "baserom.gba", 0x103D82C, 0x20
sHoOhSprites63:
ax_sprite 0, 0x40
ax_sprite sHoOhGfx63, 0x40
ax_sprite 0, 0xc0
ax_sprite sHoOhGfx63_1, 0x40
ax_sprite 0, 0x20
ax_sprite sHoOhGfx63_2, 0x60
ax_sprite 0, 0x20
ax_sprite sHoOhGfx63_3, 0x60
ax_sprite 0, 0x20
ax_sprite sHoOhGfx63_4, 0x260
ax_sprite 0, 0x20
ax_sprite sHoOhGfx63_5, 0xe0
ax_sprite 0, 0x40
ax_sprite sHoOhGfx63_6, 0x40
ax_sprite 0, 0x20
ax_sprite sHoOhGfx63_7, 0x60
ax_sprite 0, 0xc0
ax_sprite sHoOhGfx63_8, 0x20
ax_sprite 0, 0x20
ax_sprite_terminator
sHoOhGfx64:
.incbin "baserom.gba", 0x103D8EC, 0x40
sHoOhGfx64_1:
.incbin "baserom.gba", 0x103D92C, 0xA0
sHoOhGfx64_2:
.incbin "baserom.gba", 0x103D9CC, 0xC0
sHoOhGfx64_3:
.incbin "baserom.gba", 0x103DA8C, 0xC0
sHoOhGfx64_4:
.incbin "baserom.gba", 0x103DB4C, 0xC0
sHoOhGfx64_5:
.incbin "baserom.gba", 0x103DC0C, 0xC0
sHoOhGfx64_6:
.incbin "baserom.gba", 0x103DCCC, 0x60
sHoOhGfx64_7:
.incbin "baserom.gba", 0x103DD2C, 0x80
sHoOhSprites64:
ax_sprite 0, 0x60
ax_sprite sHoOhGfx64, 0x40
ax_sprite 0, 0x80
ax_sprite sHoOhGfx64_1, 0xa0
ax_sprite 0, 0x40
ax_sprite sHoOhGfx64_2, 0xc0
ax_sprite 0, 0x40
ax_sprite sHoOhGfx64_3, 0xc0
ax_sprite 0, 0x40
ax_sprite sHoOhGfx64_4, 0xc0
ax_sprite 0, 0x60
ax_sprite sHoOhGfx64_5, 0xc0
ax_sprite 0, 0xa0
ax_sprite sHoOhGfx64_6, 0x60
ax_sprite 0, 0xa0
ax_sprite sHoOhGfx64_7, 0x80
ax_sprite_terminator
sHoOhGfx65:
.incbin "baserom.gba", 0x103DE34, 0xA0
sHoOhGfx65_1:
.incbin "baserom.gba", 0x103DED4, 0x60
sHoOhGfx65_2:
.incbin "baserom.gba", 0x103DF34, 0x60
sHoOhGfx65_3:
.incbin "baserom.gba", 0x103DF94, 0x200
sHoOhGfx65_4:
.incbin "baserom.gba", 0x103E194, 0xE0
sHoOhGfx65_5:
.incbin "baserom.gba", 0x103E274, 0xE0
sHoOhGfx65_6:
.incbin "baserom.gba", 0x103E354, 0xC0
sHoOhGfx65_7:
.incbin "baserom.gba", 0x103E414, 0x60
sHoOhSprites65:
ax_sprite 0, 0x20
ax_sprite sHoOhGfx65, 0xa0
ax_sprite 0, 0x40
ax_sprite sHoOhGfx65_1, 0x60
ax_sprite 0, 0x20
ax_sprite sHoOhGfx65_2, 0x60
ax_sprite 0, 0x20
ax_sprite sHoOhGfx65_3, 0x200
ax_sprite 0, 0x20
ax_sprite sHoOhGfx65_4, 0xe0
ax_sprite 0, 0x20
ax_sprite sHoOhGfx65_5, 0xe0
ax_sprite 0, 0x40
ax_sprite sHoOhGfx65_6, 0xc0
ax_sprite 0, 0x80
ax_sprite sHoOhGfx65_7, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sHoOhGfx66:
.incbin "baserom.gba", 0x103E504, 0x60
sHoOhGfx66_1:
.incbin "baserom.gba", 0x103E564, 0x60
sHoOhGfx66_2:
.incbin "baserom.gba", 0x103E5C4, 0xE0
sHoOhGfx66_3:
.incbin "baserom.gba", 0x103E6A4, 0x80
sHoOhGfx66_4:
.incbin "baserom.gba", 0x103E724, 0x40
sHoOhGfx66_5:
.incbin "baserom.gba", 0x103E764, 0xE0
sHoOhGfx66_6:
.incbin "baserom.gba", 0x103E844, 0xA0
sHoOhGfx66_7:
.incbin "baserom.gba", 0x103E8E4, 0x60
sHoOhGfx66_8:
.incbin "baserom.gba", 0x103E944, 0x60
sHoOhGfx66_9:
.incbin "baserom.gba", 0x103E9A4, 0x60
sHoOhSprites66:
ax_sprite sHoOhGfx66, 0x60
ax_sprite 0, 0x20
ax_sprite sHoOhGfx66_1, 0x60
ax_sprite 0, 0x20
ax_sprite sHoOhGfx66_2, 0xe0
ax_sprite 0, 0x20
ax_sprite sHoOhGfx66_3, 0x80
ax_sprite 0, 0x20
ax_sprite sHoOhGfx66_4, 0x40
ax_sprite 0, 0x20
ax_sprite sHoOhGfx66_5, 0xe0
ax_sprite 0, 0x40
ax_sprite sHoOhGfx66_6, 0xa0
ax_sprite 0, 0x80
ax_sprite sHoOhGfx66_7, 0x60
ax_sprite 0, 0xa0
ax_sprite sHoOhGfx66_8, 0x60
ax_sprite 0, 0xa0
ax_sprite sHoOhGfx66_9, 0x60
ax_sprite 0, 0x60
ax_sprite_terminator
sHoOhGfx67:
.incbin "baserom.gba", 0x103EAAC, 0xE0
sHoOhGfx67_1:
.incbin "baserom.gba", 0x103EB8C, 0x60
sHoOhGfx67_2:
.incbin "baserom.gba", 0x103EBEC, 0x60
sHoOhGfx67_3:
.incbin "baserom.gba", 0x103EC4C, 0xE0
sHoOhGfx67_4:
.incbin "baserom.gba", 0x103ED2C, 0xE0
sHoOhGfx67_5:
.incbin "baserom.gba", 0x103EE0C, 0xE0
sHoOhGfx67_6:
.incbin "baserom.gba", 0x103EEEC, 0xE0
sHoOhGfx67_7:
.incbin "baserom.gba", 0x103EFCC, 0xC0
sHoOhGfx67_8:
.incbin "baserom.gba", 0x103F08C, 0xA0
sHoOhSprites67:
ax_sprite sHoOhGfx67, 0xe0
ax_sprite 0, 0x20
ax_sprite sHoOhGfx67_1, 0x60
ax_sprite 0, 0x20
ax_sprite sHoOhGfx67_2, 0x60
ax_sprite 0, 0x20
ax_sprite sHoOhGfx67_3, 0xe0
ax_sprite 0, 0x20
ax_sprite sHoOhGfx67_4, 0xe0
ax_sprite 0, 0x20
ax_sprite sHoOhGfx67_5, 0xe0
ax_sprite 0, 0x20
ax_sprite sHoOhGfx67_6, 0xe0
ax_sprite 0, 0x20
ax_sprite sHoOhGfx67_7, 0xc0
ax_sprite 0, 0x60
ax_sprite sHoOhGfx67_8, 0xa0
ax_sprite 0, 0x40
ax_sprite_terminator
sHoOhGfx68:
.incbin "baserom.gba", 0x103F1C4, 0x200
sHoOhSprites68:
ax_sprite sHoOhGfx68, 0x200
ax_sprite_terminator
sHoOhGfx69:
.incbin "baserom.gba", 0x103F3D4, 0xE0
sHoOhSprites69:
ax_sprite 0, 0x20
ax_sprite sHoOhGfx69, 0xe0
ax_sprite_terminator
sHoOhGfx70:
.incbin "baserom.gba", 0x103F4CC, 0x60
sHoOhSprites70:
ax_sprite 0, 0x20
ax_sprite sHoOhGfx70, 0x60
ax_sprite_terminator
sHoOhGfx71:
.incbin "baserom.gba", 0x103F544, 0x20
sHoOhSprites71:
ax_sprite sHoOhGfx71, 0x20
ax_sprite_terminator
sHoOhGfx72:
.incbin "baserom.gba", 0x103F574, 0x20
sHoOhSprites72:
ax_sprite sHoOhGfx72, 0x20
ax_sprite_terminator
sHoOhGfx73:
.incbin "baserom.gba", 0x103F5A4, 0x40
sHoOhSprites73:
ax_sprite sHoOhGfx73, 0x40
ax_sprite_terminator
sHoOhGfx74:
.incbin "baserom.gba", 0x103F5F4, 0x200
sHoOhSprites74:
ax_sprite sHoOhGfx74, 0x200
ax_sprite_terminator
sHoOhGfx75:
.incbin "baserom.gba", 0x103F804, 0xE0
sHoOhSprites75:
ax_sprite 0, 0x20
ax_sprite sHoOhGfx75, 0xe0
ax_sprite_terminator
sHoOhGfx76:
.incbin "baserom.gba", 0x103F8FC, 0x20
sHoOhSprites76:
ax_sprite sHoOhGfx76, 0x20
ax_sprite_terminator
sHoOhGfx77:
.incbin "baserom.gba", 0x103F92C, 0x40
sHoOhSprites77:
ax_sprite sHoOhGfx77, 0x40
ax_sprite_terminator
sHoOhGfx78:
.incbin "baserom.gba", 0x103F97C, 0x20
sHoOhSprites78:
ax_sprite sHoOhGfx78, 0x20
ax_sprite_terminator
sHoOhGfx79:
.incbin "baserom.gba", 0x103F9AC, 0x20
sHoOhSprites79:
ax_sprite sHoOhGfx79, 0x20
ax_sprite_terminator
sHoOhGfx80:
.incbin "baserom.gba", 0x103F9DC, 0x40
sHoOhGfx80_1:
.incbin "baserom.gba", 0x103FA1C, 0x60
sHoOhGfx80_2:
.incbin "baserom.gba", 0x103FA7C, 0xE0
sHoOhGfx80_3:
.incbin "baserom.gba", 0x103FB5C, 0x400
sHoOhGfx80_4:
.incbin "baserom.gba", 0x103FF5C, 0xC0
sHoOhGfx80_5:
.incbin "baserom.gba", 0x104001C, 0xC0
sHoOhSprites80:
ax_sprite sHoOhGfx80, 0x40
ax_sprite 0, 0x20
ax_sprite sHoOhGfx80_1, 0x60
ax_sprite 0, 0x40
ax_sprite sHoOhGfx80_2, 0xe0
ax_sprite 0, 0x20
ax_sprite sHoOhGfx80_3, 0x400
ax_sprite 0, 0x20
ax_sprite sHoOhGfx80_4, 0xc0
ax_sprite 0, 0x40
ax_sprite sHoOhGfx80_5, 0xc0
ax_sprite 0, 0x20
ax_sprite_terminator
sHoOhGfx81:
.incbin "baserom.gba", 0x1040144, 0x80
sHoOhGfx81_1:
.incbin "baserom.gba", 0x10401C4, 0x20
sHoOhGfx81_2:
.incbin "baserom.gba", 0x10401E4, 0xA0
sHoOhGfx81_3:
.incbin "baserom.gba", 0x1040284, 0x40
sHoOhGfx81_4:
.incbin "baserom.gba", 0x10402C4, 0xA0
sHoOhGfx81_5:
.incbin "baserom.gba", 0x1040364, 0x500
sHoOhSprites81:
ax_sprite sHoOhGfx81, 0x80
ax_sprite 0, 0x40
ax_sprite sHoOhGfx81_1, 0x20
ax_sprite 0, 0x20
ax_sprite sHoOhGfx81_2, 0xa0
ax_sprite 0, 0x20
ax_sprite sHoOhGfx81_3, 0x40
ax_sprite 0, 0x20
ax_sprite sHoOhGfx81_4, 0xa0
ax_sprite 0, 0x40
ax_sprite sHoOhGfx81_5, 0x500
ax_sprite_terminator
sHoOhGfx82:
.incbin "baserom.gba", 0x10408C4, 0x40
sHoOhGfx82_1:
.incbin "baserom.gba", 0x1040904, 0xC0
sHoOhGfx82_2:
.incbin "baserom.gba", 0x10409C4, 0x20
sHoOhGfx82_3:
.incbin "baserom.gba", 0x10409E4, 0xA0
sHoOhGfx82_4:
.incbin "baserom.gba", 0x1040A84, 0x3E0
sHoOhGfx82_5:
.incbin "baserom.gba", 0x1040E64, 0x80
sHoOhSprites82:
ax_sprite 0, 0x40
ax_sprite sHoOhGfx82, 0x40
ax_sprite 0, 0xc0
ax_sprite sHoOhGfx82_1, 0xc0
ax_sprite 0, 0x20
ax_sprite sHoOhGfx82_2, 0x20
ax_sprite 0, 0x20
ax_sprite sHoOhGfx82_3, 0xa0
ax_sprite 0, 0x20
ax_sprite sHoOhGfx82_4, 0x3e0
ax_sprite 0, 0x20
ax_sprite sHoOhGfx82_5, 0x80
ax_sprite 0, 0x60
ax_sprite_terminator
sHoOhGfx83:
.incbin "baserom.gba", 0x1040F54, 0xC0
sHoOhGfx83_1:
.incbin "baserom.gba", 0x1041014, 0x2A0
sHoOhGfx83_2:
.incbin "baserom.gba", 0x10412B4, 0xE0
sHoOhGfx83_3:
.incbin "baserom.gba", 0x1041394, 0xC0
sHoOhGfx83_4:
.incbin "baserom.gba", 0x1041454, 0xE0
sHoOhGfx83_5:
.incbin "baserom.gba", 0x1041534, 0xA0
sHoOhSprites83:
ax_sprite 0, 0x40
ax_sprite sHoOhGfx83, 0xc0
ax_sprite 0, 0x40
ax_sprite sHoOhGfx83_1, 0x2a0
ax_sprite 0, 0x20
ax_sprite sHoOhGfx83_2, 0xe0
ax_sprite 0, 0x40
ax_sprite sHoOhGfx83_3, 0xc0
ax_sprite 0, 0x20
ax_sprite sHoOhGfx83_4, 0xe0
ax_sprite 0, 0x40
ax_sprite sHoOhGfx83_5, 0xa0
ax_sprite 0, 0x40
ax_sprite_terminator
sHoOhGfx84:
.incbin "baserom.gba", 0x1041644, 0x40
sHoOhGfx84_1:
.incbin "baserom.gba", 0x1041684, 0x20
sHoOhGfx84_2:
.incbin "baserom.gba", 0x10416A4, 0x20
sHoOhGfx84_3:
.incbin "baserom.gba", 0x10416C4, 0x20
sHoOhGfx84_4:
.incbin "baserom.gba", 0x10416E4, 0x3E0
sHoOhGfx84_5:
.incbin "baserom.gba", 0x1041AC4, 0xE0
sHoOhGfx84_6:
.incbin "baserom.gba", 0x1041BA4, 0xE0
sHoOhSprites84:
ax_sprite 0, 0x40
ax_sprite sHoOhGfx84, 0x40
ax_sprite 0, 0x40
ax_sprite sHoOhGfx84_1, 0x20
ax_sprite 0, 0x60
ax_sprite sHoOhGfx84_2, 0x20
ax_sprite 0, 0x60
ax_sprite sHoOhGfx84_3, 0x20
ax_sprite 0, 0x20
ax_sprite sHoOhGfx84_4, 0x3e0
ax_sprite 0, 0x20
ax_sprite sHoOhGfx84_5, 0xe0
ax_sprite 0, 0x20
ax_sprite sHoOhGfx84_6, 0xe0
ax_sprite 0, 0x20
ax_sprite_terminator
sAxPosesHoOh:
.4byte sHoOhPose1
.4byte sHoOhPose2
.4byte sHoOhPose3
.4byte sHoOhPose4
.4byte sHoOhPose5
.4byte sHoOhPose6
.4byte sHoOhPose7
.4byte sHoOhPose8
.4byte sHoOhPose9
.4byte sHoOhPose10
.4byte sHoOhPose11
.4byte sHoOhPose12
.4byte sHoOhPose13
.4byte sHoOhPose14
.4byte sHoOhPose15
.4byte sHoOhPose16
.4byte sHoOhPose17
.4byte sHoOhPose18
.4byte sHoOhPose19
.4byte sHoOhPose20
.4byte sHoOhPose21
.4byte sHoOhPose22
.4byte sHoOhPose23
.4byte sHoOhPose24
.4byte sHoOhPose25
.4byte sHoOhPose26
.4byte sHoOhPose27
.4byte sHoOhPose28
.4byte sHoOhPose29
.4byte sHoOhPose30
.4byte sHoOhPose31
.4byte sHoOhPose32
.4byte sHoOhPose33
.4byte sHoOhPose34
.4byte sHoOhPose35
.4byte sHoOhPose36
.4byte sHoOhPose37
.4byte sHoOhPose38
.4byte sHoOhPose39
.4byte sHoOhPose40
.4byte sHoOhPose41
.4byte sHoOhPose42
.4byte sHoOhPose43
.4byte sHoOhPose44
.4byte sHoOhPose45
.4byte sHoOhPose46
.4byte sHoOhPose47
.4byte sHoOhPose48
.4byte sHoOhPose49
.4byte sHoOhPose50
.4byte sHoOhPose51
.4byte sHoOhPose52
.4byte sHoOhPose53
.4byte sHoOhPose54
.4byte sHoOhPose55
.4byte sHoOhPose56
.4byte sHoOhPose57
.4byte sHoOhPose58
.4byte sHoOhPose59
.4byte sHoOhPose60
.4byte sHoOhPose61
.4byte sHoOhPose62
.4byte sHoOhPose63
.4byte sHoOhPose64
.4byte sHoOhPose65
.4byte sHoOhPose66
.4byte sHoOhPose67
.4byte sHoOhPose68
.4byte sHoOhPose69
.4byte sHoOhPose70
.4byte sHoOhPose71
.4byte sHoOhPose72
.4byte sHoOhPose73
.4byte sHoOhPose74
.4byte sHoOhPose75
.4byte sHoOhPose76
.4byte sHoOhPose77
.4byte sHoOhPose78
.4byte sHoOhPose79
.4byte sHoOhPose80
.4byte sHoOhPose81
.4byte sHoOhPose82
.4byte sHoOhPose83
.4byte sHoOhPose84
.4byte sHoOhPose85
.4byte sHoOhPose86
.4byte sHoOhPose87
.4byte sHoOhPose88
.4byte sHoOhPose89
.4byte sHoOhPose90
.4byte sHoOhPose91
.4byte sHoOhPose92
.4byte sHoOhPose93
.4byte sHoOhPose94
.4byte sHoOhPose95
.4byte sHoOhPose96
.4byte sHoOhPose97
.4byte sHoOhPose98
.4byte sHoOhPose99
.4byte sHoOhPose100
.4byte sHoOhPose101
.4byte sHoOhPose102
.4byte sHoOhPose103
.4byte sHoOhPose104
.4byte sHoOhPose105
.4byte sHoOhPose106
.4byte sHoOhPose107
.4byte sHoOhPose108
.4byte sHoOhPose109
.4byte sHoOhPose110
.4byte sHoOhPose111
.4byte sHoOhPose112
.4byte sHoOhPose113
.4byte sHoOhPose114
.4byte sHoOhPose115
.4byte sHoOhPose116
.4byte sHoOhPose117
.4byte sHoOhPose118
.4byte sHoOhPose119
.4byte sHoOhPose120
.4byte sHoOhPose121
.4byte sHoOhPose122
.4byte sHoOhPose123
.4byte sHoOhPose124
.4byte sHoOhPose125
.4byte sHoOhPose126
.4byte sHoOhPose127
.4byte sHoOhPose128
.4byte sHoOhPose129
.4byte sHoOhPose130
.4byte sHoOhPose131
.4byte sHoOhPose132
.4byte sHoOhPose133
.4byte sHoOhPose134
.4byte sHoOhPose135
.4byte sHoOhPose136
.4byte sHoOhPose137
.4byte sHoOhPose138
.4byte sHoOhPose139
.4byte sHoOhPose140
.4byte sHoOhPose141
.4byte sHoOhPose142
.4byte sHoOhPose143
.4byte sHoOhPose144
.4byte sHoOhPose145
.4byte sHoOhPose146
.4byte sHoOhPose147
.4byte sHoOhPose148
.4byte sHoOhPose149
.4byte sHoOhPose150
.4byte sHoOhPose151
.4byte sHoOhPose152
.4byte sHoOhPose153
.4byte sHoOhPose154
.4byte sHoOhPose155
.4byte sHoOhPose156
.4byte sHoOhPose157
.4byte sHoOhPose158
.4byte sHoOhPose159
.4byte sHoOhPose160
.4byte sHoOhPose161
.4byte sHoOhPose162
.4byte sHoOhPose163
.4byte sHoOhPose164
.4byte sHoOhPose165
.4byte sHoOhPose166
.4byte sHoOhPose167
.4byte sHoOhPose168
.4byte sHoOhPose169
.4byte sHoOhPose170
.4byte sHoOhPose171
.4byte sHoOhPose172
.4byte sHoOhPose173
.4byte sHoOhPose174
.4byte sHoOhPose175
.4byte sHoOhPose176
.4byte sHoOhPose177
.4byte sHoOhPose178
.4byte sHoOhPose179
.4byte sHoOhPose180
.4byte sHoOhPose181
.4byte sHoOhPose182
.4byte sHoOhPose183
.4byte sHoOhPose184
.4byte sHoOhPose185
.4byte sHoOhPose186
.4byte sHoOhPose187
.4byte sHoOhPose188
.4byte sHoOhPose189
.4byte sHoOhPose190
.4byte sHoOhPose191
.4byte sHoOhPose192
.4byte sHoOhPose193
.4byte sHoOhPose194
.4byte sHoOhPose195
.4byte sHoOhPose196
.4byte sHoOhPose197
.4byte sHoOhPose198
.4byte sHoOhPose199
.4byte sHoOhPose200
.4byte sHoOhPose201
.4byte sHoOhPose202
.4byte sHoOhPose203
.4byte sHoOhPose204
.4byte sHoOhPose205
.4byte sHoOhPose206
.4byte sHoOhPose207
.4byte sHoOhPose208
.4byte sHoOhPose209
.4byte sHoOhPose210
.4byte sHoOhPose211
.4byte sHoOhPose212
.4byte sHoOhPose213
.4byte sHoOhPose214
.4byte sHoOhPose215
.4byte sHoOhPose216
.4byte sHoOhPose217
.4byte sHoOhPose218
.4byte sHoOhPose219
.4byte sHoOhPose220
.4byte sHoOhPose221
.4byte sHoOhPose222
.4byte sHoOhPose223
.4byte sHoOhPose224
.4byte sHoOhPose225
.4byte sHoOhPose226
.4byte sHoOhPose227
.4byte sHoOhPose228
.4byte sHoOhPose229
.4byte sHoOhPose230
.4byte sHoOhPose231
.4byte sHoOhPose232
.4byte sHoOhPose233
.4byte sHoOhPose234
.4byte sHoOhPose235
.4byte sHoOhPose236
.4byte sHoOhPose237
.4byte sHoOhPose238
.4byte sHoOhPose239
.4byte sHoOhPose240
.4byte sHoOhPose241
.4byte sHoOhPose242
sAxPositionsHoOh:
.2byte   -1,   -4, 	 -12,  -47, 	  10,  -47, 	  -1,  -20
.2byte   -1,   -6, 	 -28,  -31, 	  26,  -31, 	  -1,  -24
.2byte   -1,   -9, 	 -21,   -7, 	  19,   -7, 	  -1,  -23
.2byte   14,   -9, 	  -3,  -46, 	  14,  -50, 	   0,  -23
.2byte   14,  -11, 	 -29,  -22, 	  21,  -35, 	   0,  -24
.2byte   13,  -14, 	 -18,   -3, 	  19,   -9, 	   0,  -25
.2byte   18,  -18, 	   4,  -44, 	   5,  -51, 	  -2,  -22
.2byte   18,  -20, 	   1,  -30, 	   7,  -35, 	  -4,  -24
.2byte   18,  -23, 	  -7,   -4, 	   4,   -8, 	  -2,  -26
.2byte   13,  -26, 	  13,  -48, 	  -7,  -49, 	  -1,  -25
.2byte   12,  -26, 	  25,  -27, 	 -21,  -37, 	  -2,  -26
.2byte   12,  -28, 	  13,   -3, 	 -18,  -11, 	  -1,  -26
.2byte   -1,  -29, 	  11,  -50, 	 -12,  -50, 	  -1,  -21
.2byte   -1,  -30, 	  26,  -29, 	 -28,  -29, 	  -1,  -21
.2byte   -1,  -32, 	  21,    0, 	 -23,    0, 	  -1,  -21
.2byte  -15,  -26, 	   5,  -49, 	 -15,  -48, 	  -1,  -25
.2byte  -14,  -26, 	  19,  -37, 	 -27,  -27, 	   0,  -26
.2byte  -13,  -28, 	  17,  -11, 	 -14,   -3, 	   0,  -26
.2byte  -20,  -18, 	  -7,  -51, 	  -6,  -44, 	   0,  -22
.2byte  -20,  -20, 	  -9,  -35, 	  -3,  -30, 	   2,  -24
.2byte  -20,  -23, 	  -6,   -8, 	   5,   -4, 	   0,  -26
.2byte  -16,   -9, 	 -16,  -50, 	   1,  -46, 	  -2,  -23
.2byte  -16,  -11, 	 -23,  -35, 	  27,  -22, 	  -2,  -24
.2byte  -15,  -14, 	 -21,   -9, 	  16,   -3, 	  -2,  -25
.2byte   -1,   -4, 	 -12,  -47, 	  10,  -47, 	  -1,  -20
.2byte   -1,   -6, 	 -28,  -31, 	  26,  -31, 	  -1,  -24
.2byte   -1,   -9, 	 -21,   -7, 	  19,   -7, 	  -1,  -23
.2byte   14,   -9, 	  -3,  -46, 	  14,  -50, 	   0,  -23
.2byte   14,  -11, 	 -29,  -22, 	  21,  -35, 	   0,  -24
.2byte   13,  -14, 	 -18,   -3, 	  19,   -9, 	   0,  -25
.2byte   18,  -18, 	   4,  -44, 	   5,  -51, 	  -2,  -22
.2byte   18,  -20, 	   1,  -30, 	   7,  -35, 	  -4,  -24
.2byte   18,  -23, 	  -7,   -4, 	   4,   -8, 	  -2,  -26
.2byte   13,  -26, 	  13,  -48, 	  -7,  -49, 	  -1,  -25
.2byte   12,  -26, 	  25,  -27, 	 -21,  -37, 	  -2,  -26
.2byte   12,  -28, 	  13,   -3, 	 -18,  -11, 	  -1,  -26
.2byte   -1,  -29, 	  11,  -50, 	 -12,  -50, 	  -1,  -21
.2byte   -1,  -30, 	  26,  -29, 	 -28,  -29, 	  -1,  -21
.2byte   -1,  -32, 	  21,    0, 	 -23,    0, 	  -1,  -21
.2byte  -15,  -26, 	   5,  -49, 	 -15,  -48, 	  -1,  -25
.2byte  -14,  -26, 	  19,  -37, 	 -27,  -27, 	   0,  -26
.2byte  -13,  -28, 	  17,  -11, 	 -14,   -3, 	   0,  -26
.2byte  -20,  -18, 	  -7,  -51, 	  -6,  -44, 	   0,  -22
.2byte  -20,  -20, 	  -9,  -35, 	  -3,  -30, 	   2,  -24
.2byte  -20,  -23, 	  -6,   -8, 	   5,   -4, 	   0,  -26
.2byte  -16,   -9, 	 -16,  -50, 	   1,  -46, 	  -2,  -23
.2byte  -16,  -11, 	 -23,  -35, 	  27,  -22, 	  -2,  -24
.2byte  -15,  -14, 	 -21,   -9, 	  16,   -3, 	  -2,  -25
.2byte   -1,   -4, 	 -12,  -47, 	  10,  -47, 	  -1,  -20
.2byte   -1,   -6, 	 -28,  -31, 	  26,  -31, 	  -1,  -24
.2byte   -1,   -9, 	 -21,   -7, 	  19,   -7, 	  -1,  -23
.2byte   -1,    3, 	 -33,  -22, 	  31,  -22, 	  -1,  -22
.2byte   14,   -9, 	  -3,  -46, 	  14,  -50, 	   0,  -23
.2byte   14,  -11, 	 -29,  -22, 	  21,  -35, 	   0,  -24
.2byte   13,  -14, 	 -18,   -3, 	  19,   -9, 	   0,  -25
.2byte   17,   -4, 	 -29,  -12, 	  20,  -32, 	  -1,  -22
.2byte   18,  -18, 	   4,  -44, 	   5,  -51, 	  -2,  -22
.2byte   18,  -20, 	   1,  -30, 	   7,  -35, 	  -4,  -24
.2byte   18,  -23, 	  -7,   -4, 	   4,   -8, 	  -2,  -26
.2byte   21,  -18, 	  -2,   -4, 	   0,  -37, 	  -2,  -22
.2byte   13,  -26, 	  13,  -48, 	  -7,  -49, 	  -1,  -25
.2byte   12,  -26, 	  25,  -27, 	 -21,  -37, 	  -2,  -26
.2byte   12,  -28, 	  13,   -3, 	 -18,  -11, 	  -1,  -26
.2byte   18,  -30, 	  22,   -9, 	 -19,  -32, 	  -1,  -23
.2byte   -1,  -29, 	  11,  -50, 	 -12,  -50, 	  -1,  -21
.2byte   -1,  -30, 	  26,  -29, 	 -28,  -29, 	  -1,  -21
.2byte   -1,  -32, 	  21,    0, 	 -23,    0, 	  -1,  -21
.2byte   -1,  -33, 	 -33,  -23, 	  31,  -23, 	  -1,  -23
.2byte  -15,  -26, 	   5,  -49, 	 -15,  -48, 	  -1,  -25
.2byte  -14,  -26, 	  19,  -37, 	 -27,  -27, 	   0,  -26
.2byte  -13,  -28, 	  17,  -11, 	 -14,   -3, 	   0,  -26
.2byte  -19,  -30, 	  18,  -32, 	 -23,   -9, 	   0,  -23
.2byte  -20,  -18, 	  -7,  -51, 	  -6,  -44, 	   0,  -22
.2byte  -20,  -20, 	  -9,  -35, 	  -3,  -30, 	   2,  -24
.2byte  -20,  -23, 	  -6,   -8, 	   5,   -4, 	   0,  -26
.2byte  -22,  -18, 	  -1,  -37, 	   1,   -4, 	   1,  -22
.2byte  -16,   -9, 	 -16,  -50, 	   1,  -46, 	  -2,  -23
.2byte  -16,  -11, 	 -23,  -35, 	  27,  -22, 	  -2,  -24
.2byte  -15,  -14, 	 -21,   -9, 	  16,   -3, 	  -2,  -25
.2byte  -18,   -4, 	 -21,  -32, 	  28,  -12, 	   0,  -22
.2byte   -1,   -4, 	 -12,  -47, 	  10,  -47, 	  -1,  -20
.2byte   -1,   -6, 	 -28,  -31, 	  26,  -31, 	  -1,  -24
.2byte   -1,   -9, 	 -21,   -7, 	  19,   -7, 	  -1,  -23
.2byte   -1,  -23, 	 -14,  -35, 	  12,  -35, 	  -1,  -24
.2byte   -1,   -3, 	 -12,  -47, 	  10,  -47, 	  -1,  -22
.2byte   14,   -9, 	  -3,  -46, 	  14,  -50, 	   0,  -23
.2byte   14,  -11, 	 -29,  -22, 	  21,  -35, 	   0,  -24
.2byte   13,  -14, 	 -18,   -3, 	  19,   -9, 	   0,  -25
.2byte    3,  -26, 	 -10,  -36, 	  15,  -42, 	  -1,  -26
.2byte   13,  -12, 	  -3,  -46, 	  14,  -51, 	  -3,  -24
.2byte   18,  -18, 	   4,  -44, 	   5,  -51, 	  -2,  -22
.2byte   18,  -20, 	   1,  -30, 	   7,  -35, 	  -4,  -24
.2byte   18,  -23, 	  -7,   -4, 	   4,   -8, 	  -2,  -26
.2byte    4,  -26, 	  12,  -25, 	  13,  -39, 	  -2,  -24
.2byte   18,  -20, 	   5,  -44, 	   5,  -51, 	  -4,  -22
.2byte   13,  -26, 	  13,  -48, 	  -7,  -49, 	  -1,  -25
.2byte   12,  -26, 	  25,  -27, 	 -21,  -37, 	  -2,  -26
.2byte   12,  -28, 	  13,   -3, 	 -18,  -11, 	  -1,  -26
.2byte    3,  -34, 	  13,  -42, 	  -6,  -48, 	  -6,  -26
.2byte   10,  -28, 	  12,  -49, 	  -4,  -52, 	   0,  -25
.2byte   -1,  -29, 	  11,  -50, 	 -12,  -50, 	  -1,  -21
.2byte   -1,  -30, 	  26,  -29, 	 -28,  -29, 	  -1,  -21
.2byte   -1,  -32, 	  21,    0, 	 -23,    0, 	  -1,  -21
.2byte   -1,  -33, 	  12,  -42, 	 -13,  -42, 	  -1,  -22
.2byte   -1,  -31, 	  11,  -50, 	 -13,  -50, 	  -1,  -24
.2byte  -15,  -26, 	   5,  -49, 	 -15,  -48, 	  -1,  -25
.2byte  -14,  -26, 	  19,  -37, 	 -27,  -27, 	   0,  -26
.2byte  -13,  -28, 	  17,  -11, 	 -14,   -3, 	   0,  -26
.2byte   -5,  -34, 	   4,  -48, 	 -15,  -42, 	   4,  -26
.2byte  -12,  -28, 	   2,  -52, 	 -14,  -49, 	  -2,  -25
.2byte  -20,  -18, 	  -7,  -51, 	  -6,  -44, 	   0,  -22
.2byte  -20,  -20, 	  -9,  -35, 	  -3,  -30, 	   2,  -24
.2byte  -20,  -23, 	  -6,   -8, 	   5,   -4, 	   0,  -26
.2byte   -5,  -26, 	 -14,  -39, 	 -13,  -25, 	   1,  -24
.2byte  -20,  -20, 	  -7,  -51, 	  -7,  -44, 	   2,  -22
.2byte  -16,   -9, 	 -16,  -50, 	   1,  -46, 	  -2,  -23
.2byte  -16,  -11, 	 -23,  -35, 	  27,  -22, 	  -2,  -24
.2byte  -15,  -14, 	 -21,   -9, 	  16,   -3, 	  -2,  -25
.2byte   -4,  -26, 	 -16,  -42, 	   9,  -36, 	   0,  -26
.2byte  -15,  -12, 	 -16,  -51, 	   1,  -46, 	   1,  -24
.2byte   -1,   -4, 	 -12,  -47, 	  10,  -47, 	  -1,  -20
.2byte   -1,   -6, 	 -28,  -31, 	  26,  -31, 	  -1,  -24
.2byte   -1,   -9, 	 -21,   -7, 	  19,   -7, 	  -1,  -23
.2byte   14,   -9, 	  -3,  -46, 	  14,  -50, 	   0,  -23
.2byte   14,  -11, 	 -29,  -22, 	  21,  -35, 	   0,  -24
.2byte   13,  -14, 	 -18,   -3, 	  19,   -9, 	   0,  -25
.2byte   18,  -18, 	   4,  -44, 	   5,  -51, 	  -2,  -22
.2byte   18,  -20, 	   1,  -30, 	   7,  -35, 	  -4,  -24
.2byte   18,  -23, 	  -7,   -4, 	   4,   -8, 	  -2,  -26
.2byte   13,  -26, 	  13,  -48, 	  -7,  -49, 	  -1,  -25
.2byte   12,  -26, 	  25,  -27, 	 -21,  -37, 	  -2,  -26
.2byte   12,  -28, 	  13,   -3, 	 -18,  -11, 	  -1,  -26
.2byte   -1,  -29, 	  11,  -50, 	 -12,  -50, 	  -1,  -21
.2byte   -1,  -30, 	  26,  -29, 	 -28,  -29, 	  -1,  -21
.2byte   -1,  -32, 	  21,    0, 	 -23,    0, 	  -1,  -21
.2byte  -15,  -26, 	   5,  -49, 	 -15,  -48, 	  -1,  -25
.2byte  -14,  -26, 	  19,  -37, 	 -27,  -27, 	   0,  -26
.2byte  -13,  -28, 	  17,  -11, 	 -14,   -3, 	   0,  -26
.2byte  -20,  -18, 	  -7,  -51, 	  -6,  -44, 	   0,  -22
.2byte  -20,  -20, 	  -9,  -35, 	  -3,  -30, 	   2,  -24
.2byte  -20,  -23, 	  -6,   -8, 	   5,   -4, 	   0,  -26
.2byte  -16,   -9, 	 -16,  -50, 	   1,  -46, 	  -2,  -23
.2byte  -16,  -11, 	 -23,  -35, 	  27,  -22, 	  -2,  -24
.2byte  -15,  -14, 	 -21,   -9, 	  16,   -3, 	  -2,  -25
.2byte  -20,    0, 	   0,  -17, 	   4,  -16, 	  -2,  -12
.2byte  -20,    4, 	   0,  -17, 	   4,  -16, 	  -2,  -12
.2byte    0,  -53, 	 -14,  -46, 	  14,  -46, 	   0,  -26
.2byte  -14,  -44, 	 -34,  -28, 	  -6,  -56, 	  -1,  -30
.2byte  -11,  -40, 	 -29,  -24, 	 -25,  -41, 	   2,  -26
.2byte  -10,  -39, 	  -1,  -48, 	 -23,  -47, 	   0,  -23
.2byte    0,  -39, 	  19,  -37, 	 -19,  -37, 	   0,  -22
.2byte    9,  -39, 	  22,  -47, 	   0,  -48, 	  -1,  -23
.2byte    9,  -40, 	  23,  -41, 	  27,  -24, 	  -4,  -26
.2byte   13,  -44, 	   5,  -56, 	  33,  -28, 	   0,  -30
.2byte   -1,   -4, 	 -12,  -47, 	  10,  -47, 	  -1,  -20
.2byte   -1,   -6, 	 -28,  -31, 	  26,  -31, 	  -1,  -24
.2byte   -1,   -9, 	 -21,   -7, 	  19,   -7, 	  -1,  -23
.2byte   14,   -9, 	  -3,  -46, 	  14,  -50, 	   0,  -23
.2byte   14,  -11, 	 -29,  -22, 	  21,  -35, 	   0,  -24
.2byte   13,  -14, 	 -18,   -3, 	  19,   -9, 	   0,  -25
.2byte   18,  -18, 	   4,  -44, 	   5,  -51, 	  -2,  -22
.2byte   18,  -20, 	   1,  -30, 	   7,  -35, 	  -4,  -24
.2byte   18,  -23, 	  -7,   -4, 	   4,   -8, 	  -2,  -26
.2byte   13,  -26, 	  13,  -48, 	  -7,  -49, 	  -1,  -25
.2byte   12,  -26, 	  25,  -27, 	 -21,  -37, 	  -2,  -26
.2byte   12,  -28, 	  13,   -3, 	 -18,  -11, 	  -1,  -26
.2byte   -1,  -29, 	  11,  -50, 	 -12,  -50, 	  -1,  -21
.2byte   -1,  -30, 	  26,  -29, 	 -28,  -29, 	  -1,  -21
.2byte   -1,  -32, 	  21,    0, 	 -23,    0, 	  -1,  -21
.2byte  -15,  -26, 	   5,  -49, 	 -15,  -48, 	  -1,  -25
.2byte  -14,  -26, 	  19,  -37, 	 -27,  -27, 	   0,  -26
.2byte  -13,  -28, 	  17,  -11, 	 -14,   -3, 	   0,  -26
.2byte  -20,  -18, 	  -7,  -51, 	  -6,  -44, 	   0,  -22
.2byte  -20,  -20, 	  -9,  -35, 	  -3,  -30, 	   2,  -24
.2byte  -20,  -23, 	  -6,   -8, 	   5,   -4, 	   0,  -26
.2byte  -16,   -9, 	 -16,  -50, 	   1,  -46, 	  -2,  -23
.2byte  -16,  -11, 	 -23,  -35, 	  27,  -22, 	  -2,  -24
.2byte  -15,  -14, 	 -21,   -9, 	  16,   -3, 	  -2,  -25
.2byte   -1,   -4, 	 -12,  -47, 	  10,  -47, 	  -1,  -20
.2byte  -16,   -9, 	 -16,  -50, 	   1,  -46, 	  -2,  -23
.2byte  -20,  -18, 	  -7,  -51, 	  -6,  -44, 	   0,  -22
.2byte  -15,  -26, 	   5,  -49, 	 -15,  -48, 	  -1,  -25
.2byte   -1,  -29, 	  11,  -50, 	 -12,  -50, 	  -1,  -21
.2byte   13,  -26, 	  13,  -48, 	  -7,  -49, 	  -1,  -25
.2byte   18,  -18, 	   4,  -44, 	   5,  -51, 	  -2,  -22
.2byte   14,   -9, 	  -3,  -46, 	  14,  -50, 	   0,  -23
.2byte   -1,   -3, 	 -12,  -47, 	  10,  -47, 	  -1,  -22
.2byte   13,  -12, 	  -3,  -46, 	  14,  -51, 	  -3,  -24
.2byte   18,  -20, 	   5,  -44, 	   5,  -51, 	  -4,  -22
.2byte   10,  -28, 	  12,  -49, 	  -4,  -52, 	   0,  -25
.2byte   -1,  -31, 	  11,  -50, 	 -13,  -50, 	  -1,  -24
.2byte  -12,  -28, 	   2,  -52, 	 -14,  -49, 	  -2,  -25
.2byte  -20,  -20, 	  -7,  -51, 	  -7,  -44, 	   2,  -22
.2byte  -15,  -12, 	 -16,  -51, 	   1,  -46, 	   1,  -24
.2byte   -1,   -4, 	 -12,  -47, 	  10,  -47, 	  -1,  -20
.2byte   -1,   -6, 	 -28,  -31, 	  26,  -31, 	  -1,  -24
.2byte   -1,   -9, 	 -21,   -7, 	  19,   -7, 	  -1,  -23
.2byte   -1,  -21, 	 -14,  -33, 	  12,  -33, 	  -1,  -22
.2byte   14,   -9, 	  -3,  -46, 	  14,  -50, 	   0,  -23
.2byte   14,  -11, 	 -29,  -22, 	  21,  -35, 	   0,  -24
.2byte   13,  -14, 	 -18,   -3, 	  19,   -9, 	   0,  -25
.2byte    3,  -24, 	 -10,  -34, 	  15,  -40, 	  -1,  -24
.2byte   18,  -18, 	   4,  -44, 	   5,  -51, 	  -2,  -22
.2byte   18,  -20, 	   1,  -30, 	   7,  -35, 	  -4,  -24
.2byte   18,  -23, 	  -7,   -4, 	   4,   -8, 	  -2,  -26
.2byte    4,  -15, 	  12,  -14, 	  13,  -28, 	  -2,  -13
.2byte   13,  -26, 	  13,  -48, 	  -7,  -49, 	  -1,  -25
.2byte   12,  -26, 	  25,  -27, 	 -21,  -37, 	  -2,  -26
.2byte   12,  -28, 	  13,   -3, 	 -18,  -11, 	  -1,  -26
.2byte    3,  -18, 	  13,  -26, 	  -6,  -32, 	  -6,  -10
.2byte   -1,  -29, 	  11,  -50, 	 -12,  -50, 	  -1,  -21
.2byte   -1,  -30, 	  26,  -29, 	 -28,  -29, 	  -1,  -21
.2byte   -1,  -32, 	  21,    0, 	 -23,    0, 	  -1,  -21
.2byte   -1,  -18, 	  12,  -27, 	 -13,  -27, 	  -1,   -7
.2byte  -15,  -26, 	   5,  -49, 	 -15,  -48, 	  -1,  -25
.2byte  -14,  -26, 	  19,  -37, 	 -27,  -27, 	   0,  -26
.2byte  -13,  -28, 	  17,  -11, 	 -14,   -3, 	   0,  -26
.2byte   -4,  -18, 	   5,  -32, 	 -14,  -26, 	   5,  -10
.2byte  -20,  -18, 	  -7,  -51, 	  -6,  -44, 	   0,  -22
.2byte  -20,  -20, 	  -9,  -35, 	  -3,  -30, 	   2,  -24
.2byte  -20,  -23, 	  -6,   -8, 	   5,   -4, 	   0,  -26
.2byte   -5,  -15, 	 -14,  -28, 	 -13,  -14, 	   1,  -13
.2byte  -15,   -9, 	 -15,  -50, 	   2,  -46, 	  -1,  -23
.2byte  -15,  -11, 	 -22,  -35, 	  28,  -22, 	  -1,  -24
.2byte  -14,  -14, 	 -20,   -9, 	  17,   -3, 	  -1,  -25
.2byte   -4,  -24, 	 -16,  -40, 	   9,  -34, 	   0,  -24
.2byte   -1,   -3, 	 -12,  -47, 	  10,  -47, 	  -1,  -22
.2byte   13,  -12, 	  -3,  -46, 	  14,  -51, 	  -3,  -24
.2byte   18,  -20, 	   5,  -44, 	   5,  -51, 	  -4,  -22
.2byte   10,  -28, 	  12,  -49, 	  -4,  -52, 	   0,  -25
.2byte   -1,  -31, 	  11,  -50, 	 -13,  -50, 	  -1,  -24
.2byte  -12,  -28, 	   2,  -52, 	 -14,  -49, 	  -2,  -25
.2byte  -20,  -20, 	  -7,  -51, 	  -7,  -44, 	   2,  -22
.2byte  -15,  -12, 	 -16,  -51, 	   1,  -46, 	   1,  -24
.2byte   -1,   -4, 	 -12,  -47, 	  10,  -47, 	  -1,  -20
.2byte  -16,   -9, 	 -16,  -50, 	   1,  -46, 	  -2,  -23
.2byte  -20,  -18, 	  -7,  -51, 	  -6,  -44, 	   0,  -22
.2byte  -15,  -26, 	   5,  -49, 	 -15,  -48, 	  -1,  -25
.2byte   -1,  -29, 	  11,  -50, 	 -12,  -50, 	  -1,  -21
.2byte   13,  -26, 	  13,  -48, 	  -7,  -49, 	  -1,  -25
.2byte   18,  -18, 	   4,  -44, 	   5,  -51, 	  -2,  -22
.2byte   14,   -9, 	  -3,  -46, 	  14,  -50, 	   0,  -23
sHoOhAnimTable1:
.4byte sHoOhAnims_1_1
.4byte sHoOhAnims_1_2
.4byte sHoOhAnims_1_3
.4byte sHoOhAnims_1_4
.4byte sHoOhAnims_1_5
.4byte sHoOhAnims_1_6
.4byte sHoOhAnims_1_7
.4byte sHoOhAnims_1_8
sHoOhAnimTable2:
.4byte sHoOhAnims_2_1
.4byte sHoOhAnims_2_2
.4byte sHoOhAnims_2_3
.4byte sHoOhAnims_2_4
.4byte sHoOhAnims_2_5
.4byte sHoOhAnims_2_6
.4byte sHoOhAnims_2_7
.4byte sHoOhAnims_2_8
sHoOhAnimTable3:
.4byte sHoOhAnims_3_1
.4byte sHoOhAnims_3_2
.4byte sHoOhAnims_3_3
.4byte sHoOhAnims_3_4
.4byte sHoOhAnims_3_5
.4byte sHoOhAnims_3_6
.4byte sHoOhAnims_3_7
.4byte sHoOhAnims_3_8
sHoOhAnimTable4:
.4byte sHoOhAnims_4_1
.4byte sHoOhAnims_4_2
.4byte sHoOhAnims_4_3
.4byte sHoOhAnims_4_4
.4byte sHoOhAnims_4_5
.4byte sHoOhAnims_4_6
.4byte sHoOhAnims_4_7
.4byte sHoOhAnims_4_8
sHoOhAnimTable5:
.4byte sHoOhAnims_5_1
.4byte sHoOhAnims_5_2
.4byte sHoOhAnims_5_3
.4byte sHoOhAnims_5_4
.4byte sHoOhAnims_5_5
.4byte sHoOhAnims_5_6
.4byte sHoOhAnims_5_7
.4byte sHoOhAnims_5_8
sHoOhAnimTable6:
.4byte sHoOhAnims_6_1
.4byte sHoOhAnims_6_1
.4byte sHoOhAnims_6_1
.4byte sHoOhAnims_6_1
.4byte sHoOhAnims_6_1
.4byte sHoOhAnims_6_1
.4byte sHoOhAnims_6_1
.4byte sHoOhAnims_6_1
sHoOhAnimTable7:
.4byte sHoOhAnims_7_1
.4byte sHoOhAnims_7_2
.4byte sHoOhAnims_7_3
.4byte sHoOhAnims_7_4
.4byte sHoOhAnims_7_5
.4byte sHoOhAnims_7_6
.4byte sHoOhAnims_7_7
.4byte sHoOhAnims_7_8
sHoOhAnimTable8:
.4byte sHoOhAnims_8_1
.4byte sHoOhAnims_8_2
.4byte sHoOhAnims_8_3
.4byte sHoOhAnims_8_4
.4byte sHoOhAnims_8_5
.4byte sHoOhAnims_8_6
.4byte sHoOhAnims_8_7
.4byte sHoOhAnims_8_8
sHoOhAnimTable9:
.4byte sHoOhAnims_9_1
.4byte sHoOhAnims_9_2
.4byte sHoOhAnims_9_3
.4byte sHoOhAnims_9_4
.4byte sHoOhAnims_9_5
.4byte sHoOhAnims_9_6
.4byte sHoOhAnims_9_7
.4byte sHoOhAnims_9_8
sHoOhAnimTable10:
.4byte sHoOhAnims_10_1
.4byte sHoOhAnims_10_2
.4byte sHoOhAnims_10_3
.4byte sHoOhAnims_10_4
.4byte sHoOhAnims_10_5
.4byte sHoOhAnims_10_6
.4byte sHoOhAnims_10_7
.4byte sHoOhAnims_10_8
sHoOhAnimTable11:
.4byte sHoOhAnims_11_1
.4byte sHoOhAnims_11_2
.4byte sHoOhAnims_11_3
.4byte sHoOhAnims_11_4
.4byte sHoOhAnims_11_5
.4byte sHoOhAnims_11_6
.4byte sHoOhAnims_11_7
.4byte sHoOhAnims_11_8
sHoOhAnimTable12:
.4byte sHoOhAnims_12_1
.4byte sHoOhAnims_12_2
.4byte sHoOhAnims_12_3
.4byte sHoOhAnims_12_4
.4byte sHoOhAnims_12_5
.4byte sHoOhAnims_12_6
.4byte sHoOhAnims_12_7
.4byte sHoOhAnims_12_8
sHoOhAnimTable13:
.4byte sHoOhAnims_13_1
.4byte sHoOhAnims_13_2
.4byte sHoOhAnims_13_3
.4byte sHoOhAnims_13_4
.4byte sHoOhAnims_13_5
.4byte sHoOhAnims_13_6
.4byte sHoOhAnims_13_7
.4byte sHoOhAnims_13_8
sAxAnimationsHoOh:
.4byte sHoOhAnimTable1
.4byte sHoOhAnimTable2
.4byte sHoOhAnimTable3
.4byte sHoOhAnimTable4
.4byte sHoOhAnimTable5
.4byte sHoOhAnimTable6
.4byte sHoOhAnimTable7
.4byte sHoOhAnimTable8
.4byte sHoOhAnimTable9
.4byte sHoOhAnimTable10
.4byte sHoOhAnimTable11
.4byte sHoOhAnimTable12
.4byte sHoOhAnimTable13
sAxSpritesHoOh:
.4byte sHoOhSprites1
.4byte sHoOhSprites2
.4byte sHoOhSprites3
.4byte sHoOhSprites4
.4byte sHoOhSprites5
.4byte sHoOhSprites6
.4byte sHoOhSprites7
.4byte sHoOhSprites8
.4byte sHoOhSprites9
.4byte sHoOhSprites10
.4byte sHoOhSprites11
.4byte sHoOhSprites12
.4byte sHoOhSprites13
.4byte sHoOhSprites14
.4byte sHoOhSprites15
.4byte sHoOhSprites16
.4byte sHoOhSprites17
.4byte sHoOhSprites18
.4byte sHoOhSprites19
.4byte sHoOhSprites20
.4byte sHoOhSprites21
.4byte sHoOhSprites22
.4byte sHoOhSprites23
.4byte sHoOhSprites24
.4byte sHoOhSprites25
.4byte sHoOhSprites26
.4byte sHoOhSprites27
.4byte sHoOhSprites28
.4byte sHoOhSprites29
.4byte sHoOhSprites30
.4byte sHoOhSprites31
.4byte sHoOhSprites32
.4byte sHoOhSprites33
.4byte sHoOhSprites34
.4byte sHoOhSprites35
.4byte sHoOhSprites36
.4byte sHoOhSprites37
.4byte sHoOhSprites38
.4byte sHoOhSprites39
.4byte sHoOhSprites40
.4byte sHoOhSprites41
.4byte sHoOhSprites42
.4byte sHoOhSprites43
.4byte sHoOhSprites44
.4byte sHoOhSprites45
.4byte sHoOhSprites46
.4byte sHoOhSprites47
.4byte sHoOhSprites48
.4byte sHoOhSprites49
.4byte sHoOhSprites50
.4byte sHoOhSprites51
.4byte sHoOhSprites52
.4byte sHoOhSprites53
.4byte sHoOhSprites54
.4byte sHoOhSprites55
.4byte sHoOhSprites56
.4byte sHoOhSprites57
.4byte sHoOhSprites58
.4byte sHoOhSprites59
.4byte sHoOhSprites60
.4byte sHoOhSprites61
.4byte sHoOhSprites62
.4byte sHoOhSprites63
.4byte sHoOhSprites64
.4byte sHoOhSprites65
.4byte sHoOhSprites66
.4byte sHoOhSprites67
.4byte sHoOhSprites68
.4byte sHoOhSprites69
.4byte sHoOhSprites70
.4byte sHoOhSprites71
.4byte sHoOhSprites72
.4byte sHoOhSprites73
.4byte sHoOhSprites74
.4byte sHoOhSprites75
.4byte sHoOhSprites76
.4byte sHoOhSprites77
.4byte sHoOhSprites78
.4byte sHoOhSprites79
.4byte sHoOhSprites80
.4byte sHoOhSprites81
.4byte sHoOhSprites82
.4byte sHoOhSprites83
.4byte sHoOhSprites84
sAxMainHoOh:
ax_main sAxPosesHoOh, sAxAnimationsHoOh, 13, sAxSpritesHoOh, sAxPositionsHoOh
