.global gAxHoppip
gAxHoppip:
ax_siro sAxMainHoppip
sHoppipPose1:
ax_pose 0, 0x41e7, 0x80f0, 0xac00
ax_pose 1, 0x41ee, 0x80f4, 0xac08
ax_pose_terminator
sHoppipPose2:
ax_pose 2, 0x41e7, 0x80f0, 0xac00
ax_pose 1, 0x41ee, 0x80f4, 0xac08
ax_pose_terminator
sHoppipPose3:
ax_pose 3, 0x01e7, 0x40f8, 0xac00
ax_pose 1, 0x41ee, 0x80f4, 0xac04
ax_pose_terminator
sHoppipPose4:
ax_pose 4, 0x41e7, 0x80f0, 0xac00
ax_pose 1, 0x41ee, 0x80f4, 0xac08
ax_pose_terminator
sHoppipPose5:
ax_pose 5, 0x41e7, 0x80f0, 0xac00
ax_pose 1, 0x41ee, 0x80f4, 0xac08
ax_pose_terminator
sHoppipPose6:
ax_pose 4, 0x41e7, 0x90f0, 0xac00
ax_pose 1, 0x41ee, 0x80f4, 0xac08
ax_pose_terminator
sHoppipPose7:
ax_pose 3, 0x01e7, 0x50f8, 0xac00
ax_pose 1, 0x41ee, 0x80f4, 0xac04
ax_pose_terminator
sHoppipPose8:
ax_pose 2, 0x41e7, 0x90f0, 0xac00
ax_pose 1, 0x41ee, 0x80f4, 0xac08
ax_pose_terminator
sHoppipPose9:
ax_pose 0, 0x41e5, 0x80f0, 0xac00
ax_pose 6, 0x41ee, 0x90ea, 0xac08
ax_pose_terminator
sHoppipPose10:
ax_pose 2, 0x41e5, 0x80f0, 0xac00
ax_pose 6, 0x41ee, 0x90ea, 0xac08
ax_pose_terminator
sHoppipPose11:
ax_pose 3, 0x01e5, 0x40f8, 0xac00
ax_pose 6, 0x41ee, 0x90ea, 0xac04
ax_pose_terminator
sHoppipPose12:
ax_pose 4, 0x41e5, 0x80f0, 0xac00
ax_pose 6, 0x41ee, 0x90ea, 0xac08
ax_pose_terminator
sHoppipPose13:
ax_pose 5, 0x41e5, 0x80f0, 0xac00
ax_pose 6, 0x41ee, 0x90ea, 0xac08
ax_pose_terminator
sHoppipPose14:
ax_pose 4, 0x41e5, 0x90f0, 0xac00
ax_pose 6, 0x41ee, 0x90ea, 0xac08
ax_pose_terminator
sHoppipPose15:
ax_pose 3, 0x01e5, 0x50f8, 0xac00
ax_pose 6, 0x41ee, 0x90ea, 0xac04
ax_pose_terminator
sHoppipPose16:
ax_pose 2, 0x41e5, 0x90f0, 0xac00
ax_pose 6, 0x41ee, 0x90ea, 0xac08
ax_pose_terminator
sHoppipPose17:
ax_pose 0, 0x41e4, 0x80f0, 0xac00
ax_pose 7, 0x41ed, 0x90ec, 0xac08
ax_pose_terminator
sHoppipPose18:
ax_pose 2, 0x41e4, 0x80f0, 0xac00
ax_pose 7, 0x41ed, 0x90ec, 0xac08
ax_pose_terminator
sHoppipPose19:
ax_pose 3, 0x01e4, 0x40f8, 0xac00
ax_pose 7, 0x41ed, 0x90ec, 0xac04
ax_pose_terminator
sHoppipPose20:
ax_pose 4, 0x41e4, 0x80f0, 0xac00
ax_pose 7, 0x41ed, 0x90ec, 0xac08
ax_pose_terminator
sHoppipPose21:
ax_pose 5, 0x41e4, 0x80f0, 0xac00
ax_pose 7, 0x41ed, 0x90ec, 0xac08
ax_pose_terminator
sHoppipPose22:
ax_pose 4, 0x41e4, 0x90f0, 0xac00
ax_pose 7, 0x41ed, 0x90ec, 0xac08
ax_pose_terminator
sHoppipPose23:
ax_pose 3, 0x01e4, 0x50f8, 0xac00
ax_pose 7, 0x41ed, 0x90ec, 0xac04
ax_pose_terminator
sHoppipPose24:
ax_pose 2, 0x41e4, 0x90f0, 0xac00
ax_pose 7, 0x41ed, 0x90ec, 0xac08
ax_pose_terminator
sHoppipPose25:
ax_pose 0, 0x41e6, 0x80f0, 0xac00
ax_pose 8, 0x81e7, 0x90f8, 0xac08
ax_pose_terminator
sHoppipPose26:
ax_pose 2, 0x41e6, 0x80f0, 0xac00
ax_pose 8, 0x81e7, 0x90f8, 0xac08
ax_pose_terminator
sHoppipPose27:
ax_pose 3, 0x01e6, 0x40f8, 0xac00
ax_pose 8, 0x81e7, 0x90f8, 0xac04
ax_pose_terminator
sHoppipPose28:
ax_pose 4, 0x41e6, 0x80f0, 0xac00
ax_pose 8, 0x81e7, 0x90f8, 0xac08
ax_pose_terminator
sHoppipPose29:
ax_pose 5, 0x41e6, 0x80f0, 0xac00
ax_pose 8, 0x81e7, 0x90f8, 0xac08
ax_pose_terminator
sHoppipPose30:
ax_pose 4, 0x41e6, 0x90f0, 0xac00
ax_pose 8, 0x81e7, 0x90f8, 0xac08
ax_pose_terminator
sHoppipPose31:
ax_pose 3, 0x01e6, 0x50f8, 0xac00
ax_pose 8, 0x81e7, 0x90f8, 0xac04
ax_pose_terminator
sHoppipPose32:
ax_pose 2, 0x41e6, 0x90f0, 0xac00
ax_pose 8, 0x81e7, 0x90f8, 0xac08
ax_pose_terminator
sHoppipPose33:
ax_pose 0, 0x41e6, 0x80f0, 0xac00
ax_pose 9, 0x41f0, 0x80f4, 0xac08
ax_pose_terminator
sHoppipPose34:
ax_pose 2, 0x41e6, 0x80f0, 0xac00
ax_pose 9, 0x41f0, 0x80f4, 0xac08
ax_pose_terminator
sHoppipPose35:
ax_pose 3, 0x01e6, 0x40f8, 0xac00
ax_pose 9, 0x41f0, 0x80f4, 0xac04
ax_pose_terminator
sHoppipPose36:
ax_pose 4, 0x41e6, 0x80f0, 0xac00
ax_pose 9, 0x41f0, 0x80f4, 0xac08
ax_pose_terminator
sHoppipPose37:
ax_pose 5, 0x41e6, 0x80f0, 0xac00
ax_pose 9, 0x41f0, 0x80f4, 0xac08
ax_pose_terminator
sHoppipPose38:
ax_pose 4, 0x41e6, 0x90f0, 0xac00
ax_pose 9, 0x41f0, 0x80f4, 0xac08
ax_pose_terminator
sHoppipPose39:
ax_pose 3, 0x01e6, 0x50f8, 0xac00
ax_pose 9, 0x41f0, 0x80f4, 0xac04
ax_pose_terminator
sHoppipPose40:
ax_pose 2, 0x41e6, 0x90f0, 0xac00
ax_pose 9, 0x41f0, 0x80f4, 0xac08
ax_pose_terminator
sHoppipPose41:
ax_pose 0, 0x41e6, 0x80f0, 0xac00
ax_pose 8, 0x81e7, 0x80f8, 0xac08
ax_pose_terminator
sHoppipPose42:
ax_pose 2, 0x41e6, 0x80f0, 0xac00
ax_pose 8, 0x81e7, 0x80f8, 0xac08
ax_pose_terminator
sHoppipPose43:
ax_pose 3, 0x01e6, 0x40f8, 0xac00
ax_pose 8, 0x81e7, 0x80f8, 0xac04
ax_pose_terminator
sHoppipPose44:
ax_pose 4, 0x41e6, 0x80f0, 0xac00
ax_pose 8, 0x81e7, 0x80f8, 0xac08
ax_pose_terminator
sHoppipPose45:
ax_pose 5, 0x41e6, 0x80f0, 0xac00
ax_pose 8, 0x81e7, 0x80f8, 0xac08
ax_pose_terminator
sHoppipPose46:
ax_pose 4, 0x41e6, 0x90f0, 0xac00
ax_pose 8, 0x81e7, 0x80f8, 0xac08
ax_pose_terminator
sHoppipPose47:
ax_pose 3, 0x01e6, 0x50f8, 0xac00
ax_pose 8, 0x81e7, 0x80f8, 0xac04
ax_pose_terminator
sHoppipPose48:
ax_pose 2, 0x41e6, 0x90f0, 0xac00
ax_pose 8, 0x81e7, 0x80f8, 0xac08
ax_pose_terminator
sHoppipPose49:
ax_pose 0, 0x41e4, 0x80f0, 0xac00
ax_pose 7, 0x41ed, 0x80f4, 0xac08
ax_pose_terminator
sHoppipPose50:
ax_pose 2, 0x41e4, 0x80f0, 0xac00
ax_pose 7, 0x41ed, 0x80f4, 0xac08
ax_pose_terminator
sHoppipPose51:
ax_pose 3, 0x01e4, 0x40f8, 0xac00
ax_pose 7, 0x41ed, 0x80f4, 0xac04
ax_pose_terminator
sHoppipPose52:
ax_pose 4, 0x41e4, 0x80f0, 0xac00
ax_pose 7, 0x41ed, 0x80f4, 0xac08
ax_pose_terminator
sHoppipPose53:
ax_pose 5, 0x41e4, 0x80f0, 0xac00
ax_pose 7, 0x41ed, 0x80f4, 0xac08
ax_pose_terminator
sHoppipPose54:
ax_pose 4, 0x41e4, 0x90f0, 0xac00
ax_pose 7, 0x41ed, 0x80f4, 0xac08
ax_pose_terminator
sHoppipPose55:
ax_pose 3, 0x01e4, 0x50f8, 0xac00
ax_pose 7, 0x41ed, 0x80f4, 0xac04
ax_pose_terminator
sHoppipPose56:
ax_pose 2, 0x41e4, 0x90f0, 0xac00
ax_pose 7, 0x41ed, 0x80f4, 0xac08
ax_pose_terminator
sHoppipPose57:
ax_pose 0, 0x41e5, 0x80f0, 0xac00
ax_pose 6, 0x41ee, 0x80f6, 0xac08
ax_pose_terminator
sHoppipPose58:
ax_pose 2, 0x41e5, 0x80f0, 0xac00
ax_pose 6, 0x41ee, 0x80f6, 0xac08
ax_pose_terminator
sHoppipPose59:
ax_pose 3, 0x01e5, 0x40f8, 0xac00
ax_pose 6, 0x41ee, 0x80f6, 0xac04
ax_pose_terminator
sHoppipPose60:
ax_pose 4, 0x41e5, 0x80f0, 0xac00
ax_pose 6, 0x41ee, 0x80f6, 0xac08
ax_pose_terminator
sHoppipPose61:
ax_pose 5, 0x41e5, 0x80f0, 0xac00
ax_pose 6, 0x41ee, 0x80f6, 0xac08
ax_pose_terminator
sHoppipPose62:
ax_pose 4, 0x41e5, 0x90f0, 0xac00
ax_pose 6, 0x41ee, 0x80f6, 0xac08
ax_pose_terminator
sHoppipPose63:
ax_pose 3, 0x01e5, 0x50f8, 0xac00
ax_pose 6, 0x41ee, 0x80f6, 0xac04
ax_pose_terminator
sHoppipPose64:
ax_pose 2, 0x41e5, 0x90f0, 0xac00
ax_pose 6, 0x41ee, 0x80f6, 0xac08
ax_pose_terminator
sHoppipPose65:
ax_pose 10, 0x01e6, 0x80f4, 0xac00
ax_pose_terminator
sHoppipPose66:
ax_pose 11, 0x01e6, 0x80f4, 0xac00
ax_pose_terminator
sHoppipPose67:
ax_pose 12, 0x01e6, 0x80f0, 0xac00
ax_pose_terminator
sHoppipPose68:
ax_pose 13, 0x01e6, 0x90ea, 0xac00
ax_pose_terminator
sHoppipPose69:
ax_pose 14, 0x01e6, 0x90ea, 0xac00
ax_pose_terminator
sHoppipPose70:
ax_pose 15, 0x01e6, 0x90ea, 0xac00
ax_pose_terminator
sHoppipPose71:
ax_pose 16, 0x01e3, 0x90ec, 0xac00
ax_pose_terminator
sHoppipPose72:
ax_pose 17, 0x01e6, 0x90ec, 0xac00
ax_pose_terminator
sHoppipPose73:
ax_pose 18, 0x01e6, 0x90ec, 0xac00
ax_pose_terminator
sHoppipPose74:
ax_pose 19, 0x01e7, 0x90ec, 0xac00
ax_pose_terminator
sHoppipPose75:
ax_pose 20, 0x01e3, 0x90ec, 0xac00
ax_pose_terminator
sHoppipPose76:
ax_pose 21, 0x01e7, 0x90ec, 0xac00
ax_pose_terminator
sHoppipPose77:
ax_pose 22, 0x01e8, 0x80f4, 0xac00
ax_pose_terminator
sHoppipPose78:
ax_pose 23, 0x01e7, 0x80f4, 0xac00
ax_pose_terminator
sHoppipPose79:
ax_pose 24, 0x01e7, 0x80f0, 0xac00
ax_pose_terminator
sHoppipPose80:
ax_pose 19, 0x01e7, 0x80f4, 0xac00
ax_pose_terminator
sHoppipPose81:
ax_pose 20, 0x01e3, 0x80f4, 0xac00
ax_pose_terminator
sHoppipPose82:
ax_pose 21, 0x01e7, 0x80f4, 0xac00
ax_pose_terminator
sHoppipPose83:
ax_pose 16, 0x01e3, 0x80f4, 0xac00
ax_pose_terminator
sHoppipPose84:
ax_pose 17, 0x01e6, 0x80f4, 0xac00
ax_pose_terminator
sHoppipPose85:
ax_pose 18, 0x01e6, 0x80f4, 0xac00
ax_pose_terminator
sHoppipPose86:
ax_pose 13, 0x01e6, 0x80f6, 0xac00
ax_pose_terminator
sHoppipPose87:
ax_pose 14, 0x01e6, 0x80f6, 0xac00
ax_pose_terminator
sHoppipPose88:
ax_pose 15, 0x01e6, 0x80f6, 0xac00
ax_pose_terminator
sHoppipPose89:
ax_pose 10, 0x01e6, 0x80f4, 0xac00
ax_pose_terminator
sHoppipPose90:
ax_pose 11, 0x01e6, 0x80f4, 0xac00
ax_pose_terminator
sHoppipPose91:
ax_pose 12, 0x01e6, 0x80f0, 0xac00
ax_pose_terminator
sHoppipPose92:
ax_pose 13, 0x01e6, 0x90ea, 0xac00
ax_pose_terminator
sHoppipPose93:
ax_pose 14, 0x01e6, 0x90ea, 0xac00
ax_pose_terminator
sHoppipPose94:
ax_pose 15, 0x01e6, 0x90ea, 0xac00
ax_pose_terminator
sHoppipPose95:
ax_pose 16, 0x01e3, 0x90ec, 0xac00
ax_pose_terminator
sHoppipPose96:
ax_pose 17, 0x01e6, 0x90ec, 0xac00
ax_pose_terminator
sHoppipPose97:
ax_pose 18, 0x01e6, 0x90ec, 0xac00
ax_pose_terminator
sHoppipPose98:
ax_pose 19, 0x01e7, 0x90ec, 0xac00
ax_pose_terminator
sHoppipPose99:
ax_pose 20, 0x01e3, 0x90ec, 0xac00
ax_pose_terminator
sHoppipPose100:
ax_pose 21, 0x01e7, 0x90ec, 0xac00
ax_pose_terminator
sHoppipPose101:
ax_pose 22, 0x01e8, 0x80f4, 0xac00
ax_pose_terminator
sHoppipPose102:
ax_pose 23, 0x01e7, 0x80f4, 0xac00
ax_pose_terminator
sHoppipPose103:
ax_pose 24, 0x01e7, 0x80f0, 0xac00
ax_pose_terminator
sHoppipPose104:
ax_pose 19, 0x01e7, 0x80f4, 0xac00
ax_pose_terminator
sHoppipPose105:
ax_pose 20, 0x01e3, 0x80f4, 0xac00
ax_pose_terminator
sHoppipPose106:
ax_pose 21, 0x01e7, 0x80f4, 0xac00
ax_pose_terminator
sHoppipPose107:
ax_pose 16, 0x01e3, 0x80f4, 0xac00
ax_pose_terminator
sHoppipPose108:
ax_pose 17, 0x01e6, 0x80f4, 0xac00
ax_pose_terminator
sHoppipPose109:
ax_pose 18, 0x01e6, 0x80f4, 0xac00
ax_pose_terminator
sHoppipPose110:
ax_pose 13, 0x01e6, 0x80f6, 0xac00
ax_pose_terminator
sHoppipPose111:
ax_pose 14, 0x01e6, 0x80f6, 0xac00
ax_pose_terminator
sHoppipPose112:
ax_pose 15, 0x01e6, 0x80f6, 0xac00
ax_pose_terminator
sHoppipPose113:
ax_pose 10, 0x01e6, 0x80f4, 0xac00
ax_pose_terminator
sHoppipPose114:
ax_pose 25, 0x01e6, 0x80f3, 0xac00
ax_pose_terminator
sHoppipPose115:
ax_pose 12, 0x01e6, 0x80f0, 0xac00
ax_pose_terminator
sHoppipPose116:
ax_pose 13, 0x01e6, 0x90ea, 0xac00
ax_pose_terminator
sHoppipPose117:
ax_pose 26, 0x01e6, 0x90ea, 0xac00
ax_pose_terminator
sHoppipPose118:
ax_pose 15, 0x01e6, 0x90ea, 0xac00
ax_pose_terminator
sHoppipPose119:
ax_pose 16, 0x01e3, 0x90ec, 0xac00
ax_pose_terminator
sHoppipPose120:
ax_pose 27, 0x01e3, 0x90ec, 0xac00
ax_pose_terminator
sHoppipPose121:
ax_pose 18, 0x01e6, 0x90ec, 0xac00
ax_pose_terminator
sHoppipPose122:
ax_pose 19, 0x01e7, 0x90ec, 0xac00
ax_pose_terminator
sHoppipPose123:
ax_pose 28, 0x01e7, 0x90ec, 0xac00
ax_pose_terminator
sHoppipPose124:
ax_pose 21, 0x01e7, 0x90ec, 0xac00
ax_pose_terminator
sHoppipPose125:
ax_pose 22, 0x01e8, 0x80f4, 0xac00
ax_pose_terminator
sHoppipPose126:
ax_pose 29, 0x01e8, 0x80f3, 0xac00
ax_pose_terminator
sHoppipPose127:
ax_pose 24, 0x01e7, 0x80f0, 0xac00
ax_pose_terminator
sHoppipPose128:
ax_pose 19, 0x01e7, 0x80f4, 0xac00
ax_pose_terminator
sHoppipPose129:
ax_pose 28, 0x01e7, 0x80f4, 0xac00
ax_pose_terminator
sHoppipPose130:
ax_pose 21, 0x01e7, 0x80f4, 0xac00
ax_pose_terminator
sHoppipPose131:
ax_pose 16, 0x01e3, 0x80f4, 0xac00
ax_pose_terminator
sHoppipPose132:
ax_pose 27, 0x01e3, 0x80f4, 0xac00
ax_pose_terminator
sHoppipPose133:
ax_pose 18, 0x01e6, 0x80f4, 0xac00
ax_pose_terminator
sHoppipPose134:
ax_pose 13, 0x01e6, 0x80f6, 0xac00
ax_pose_terminator
sHoppipPose135:
ax_pose 26, 0x01e6, 0x80f6, 0xac00
ax_pose_terminator
sHoppipPose136:
ax_pose 15, 0x01e6, 0x80f6, 0xac00
ax_pose_terminator
sHoppipPose137:
ax_pose 12, 0x01e6, 0x80f0, 0xac00
ax_pose_terminator
sHoppipPose138:
ax_pose 15, 0x01e6, 0x80f6, 0xac00
ax_pose_terminator
sHoppipPose139:
ax_pose 18, 0x01e6, 0x80f4, 0xac00
ax_pose_terminator
sHoppipPose140:
ax_pose 21, 0x01e7, 0x80f4, 0xac00
ax_pose_terminator
sHoppipPose141:
ax_pose 24, 0x01e7, 0x80f0, 0xac00
ax_pose_terminator
sHoppipPose142:
ax_pose 21, 0x01e7, 0x90ec, 0xac00
ax_pose_terminator
sHoppipPose143:
ax_pose 18, 0x01e6, 0x90ec, 0xac00
ax_pose_terminator
sHoppipPose144:
ax_pose 15, 0x01e6, 0x90ea, 0xac00
ax_pose_terminator
sHoppipPose145:
ax_pose 30, 0x01e9, 0x80f5, 0xac00
ax_pose_terminator
sHoppipPose146:
ax_pose 31, 0x01e9, 0x80f5, 0xac00
ax_pose_terminator
sHoppipPose147:
ax_pose 32, 0x01dd, 0x80f0, 0xac00
ax_pose_terminator
sHoppipPose148:
ax_pose 33, 0x01dd, 0x90ea, 0xac00
ax_pose_terminator
sHoppipPose149:
ax_pose 34, 0x01dd, 0x90eb, 0xac00
ax_pose_terminator
sHoppipPose150:
ax_pose 35, 0x01dc, 0x90ee, 0xac00
ax_pose_terminator
sHoppipPose151:
ax_pose 36, 0x01de, 0x80f0, 0xac00
ax_pose_terminator
sHoppipPose152:
ax_pose 35, 0x01dc, 0x80f2, 0xac00
ax_pose_terminator
sHoppipPose153:
ax_pose 34, 0x01dd, 0x80f5, 0xac00
ax_pose_terminator
sHoppipPose154:
ax_pose 33, 0x01dd, 0x80f6, 0xac00
ax_pose_terminator
sHoppipPose155:
ax_pose 10, 0x01e6, 0x80f4, 0xac00
ax_pose_terminator
sHoppipPose156:
ax_pose 13, 0x01e6, 0x80f6, 0xac00
ax_pose_terminator
sHoppipPose157:
ax_pose 16, 0x01e3, 0x80f4, 0xac00
ax_pose_terminator
sHoppipPose158:
ax_pose 19, 0x01e6, 0x80f4, 0xac00
ax_pose_terminator
sHoppipPose159:
ax_pose 22, 0x01e7, 0x80f4, 0xac00
ax_pose_terminator
sHoppipPose160:
ax_pose 19, 0x01e7, 0x90ec, 0xac00
ax_pose_terminator
sHoppipPose161:
ax_pose 16, 0x01e3, 0x90ec, 0xac00
ax_pose_terminator
sHoppipPose162:
ax_pose 13, 0x01e6, 0x90ea, 0xac00
ax_pose_terminator
sHoppipPose163:
ax_pose 11, 0x01e6, 0x80f4, 0xac00
ax_pose_terminator
sHoppipPose164:
ax_pose 14, 0x01e6, 0x80f6, 0xac00
ax_pose_terminator
sHoppipPose165:
ax_pose 17, 0x01e6, 0x80f4, 0xac00
ax_pose_terminator
sHoppipPose166:
ax_pose 20, 0x01e2, 0x80f4, 0xac00
ax_pose_terminator
sHoppipPose167:
ax_pose 23, 0x01e6, 0x80f4, 0xac00
ax_pose_terminator
sHoppipPose168:
ax_pose 20, 0x01e3, 0x90ec, 0xac00
ax_pose_terminator
sHoppipPose169:
ax_pose 17, 0x01e6, 0x90ec, 0xac00
ax_pose_terminator
sHoppipPose170:
ax_pose 14, 0x01e6, 0x90ea, 0xac00
ax_pose_terminator
sHoppipPose171:
ax_pose 12, 0x01e6, 0x80f0, 0xac00
ax_pose_terminator
sHoppipPose172:
ax_pose 15, 0x01e6, 0x80f6, 0xac00
ax_pose_terminator
sHoppipPose173:
ax_pose 18, 0x01e6, 0x80f4, 0xac00
ax_pose_terminator
sHoppipPose174:
ax_pose 21, 0x01e6, 0x80f4, 0xac00
ax_pose_terminator
sHoppipPose175:
ax_pose 24, 0x01e6, 0x80f0, 0xac00
ax_pose_terminator
sHoppipPose176:
ax_pose 21, 0x01e7, 0x90ec, 0xac00
ax_pose_terminator
sHoppipPose177:
ax_pose 18, 0x01e6, 0x90ec, 0xac00
ax_pose_terminator
sHoppipPose178:
ax_pose 15, 0x01e6, 0x90ea, 0xac00
ax_pose_terminator
sHoppipPose179:
ax_pose 10, 0x01e6, 0x80f4, 0xac00
ax_pose_terminator
sHoppipPose180:
ax_pose 13, 0x01e6, 0x80f6, 0xac00
ax_pose_terminator
sHoppipPose181:
ax_pose 16, 0x01e4, 0x80f5, 0xac00
ax_pose_terminator
sHoppipPose182:
ax_pose 19, 0x01e7, 0x80f4, 0xac00
ax_pose_terminator
sHoppipPose183:
ax_pose 22, 0x01e8, 0x80f4, 0xac00
ax_pose_terminator
sHoppipPose184:
ax_pose 19, 0x01e7, 0x90ec, 0xac00
ax_pose_terminator
sHoppipPose185:
ax_pose 16, 0x01e4, 0x90eb, 0xac00
ax_pose_terminator
sHoppipPose186:
ax_pose 13, 0x01e6, 0x90ea, 0xac00
ax_pose_terminator
sHoppipPose187:
ax_pose 25, 0x01e6, 0x80f3, 0xac00
ax_pose_terminator
sHoppipPose188:
ax_pose 26, 0x01e7, 0x90ea, 0xac00
ax_pose_terminator
sHoppipPose189:
ax_pose 27, 0x01e4, 0x90ed, 0xac00
ax_pose_terminator
sHoppipPose190:
ax_pose 28, 0x01e6, 0x90ec, 0xac00
ax_pose_terminator
sHoppipPose191:
ax_pose 29, 0x01e8, 0x80f3, 0xac00
ax_pose_terminator
sHoppipPose192:
ax_pose 28, 0x01e6, 0x80f4, 0xac00
ax_pose_terminator
sHoppipPose193:
ax_pose 27, 0x01e4, 0x80f4, 0xac00
ax_pose_terminator
sHoppipPose194:
ax_pose 26, 0x01e7, 0x80f6, 0xac00
ax_pose_terminator
sHoppipPose195:
ax_pose 10, 0x01e6, 0x80f4, 0xac00
ax_pose_terminator
sHoppipPose196:
ax_pose 25, 0x01e6, 0x80f3, 0xac00
ax_pose_terminator
sHoppipPose197:
ax_pose 11, 0x01e6, 0x80f4, 0xac00
ax_pose_terminator
sHoppipPose198:
ax_pose 13, 0x01e6, 0x90ea, 0xac00
ax_pose_terminator
sHoppipPose199:
ax_pose 26, 0x01e6, 0x90ea, 0xac00
ax_pose_terminator
sHoppipPose200:
ax_pose 14, 0x01e6, 0x90ea, 0xac00
ax_pose_terminator
sHoppipPose201:
ax_pose 16, 0x01e3, 0x90ec, 0xac00
ax_pose_terminator
sHoppipPose202:
ax_pose 27, 0x01e3, 0x90ed, 0xac00
ax_pose_terminator
sHoppipPose203:
ax_pose 17, 0x01e6, 0x90ec, 0xac00
ax_pose_terminator
sHoppipPose204:
ax_pose 19, 0x01e7, 0x90ec, 0xac00
ax_pose_terminator
sHoppipPose205:
ax_pose 28, 0x01e7, 0x90ec, 0xac00
ax_pose_terminator
sHoppipPose206:
ax_pose 20, 0x01e3, 0x90ec, 0xac00
ax_pose_terminator
sHoppipPose207:
ax_pose 22, 0x01e8, 0x80f4, 0xac00
ax_pose_terminator
sHoppipPose208:
ax_pose 29, 0x01e8, 0x80f3, 0xac00
ax_pose_terminator
sHoppipPose209:
ax_pose 23, 0x01e7, 0x80f4, 0xac00
ax_pose_terminator
sHoppipPose210:
ax_pose 19, 0x01e7, 0x80f4, 0xac00
ax_pose_terminator
sHoppipPose211:
ax_pose 28, 0x01e7, 0x80f4, 0xac00
ax_pose_terminator
sHoppipPose212:
ax_pose 20, 0x01e3, 0x80f4, 0xac00
ax_pose_terminator
sHoppipPose213:
ax_pose 16, 0x01e3, 0x80f4, 0xac00
ax_pose_terminator
sHoppipPose214:
ax_pose 27, 0x01e3, 0x80f3, 0xac00
ax_pose_terminator
sHoppipPose215:
ax_pose 17, 0x01e6, 0x80f4, 0xac00
ax_pose_terminator
sHoppipPose216:
ax_pose 13, 0x01e6, 0x80f6, 0xac00
ax_pose_terminator
sHoppipPose217:
ax_pose 26, 0x01e6, 0x80f6, 0xac00
ax_pose_terminator
sHoppipPose218:
ax_pose 14, 0x01e6, 0x80f6, 0xac00
ax_pose_terminator
sHoppipPose219:
ax_pose 12, 0x01e6, 0x80f0, 0xac00
ax_pose_terminator
sHoppipPose220:
ax_pose 15, 0x01e6, 0x80f6, 0xac00
ax_pose_terminator
sHoppipPose221:
ax_pose 18, 0x01e6, 0x80f4, 0xac00
ax_pose_terminator
sHoppipPose222:
ax_pose 21, 0x01e7, 0x80f4, 0xac00
ax_pose_terminator
sHoppipPose223:
ax_pose 24, 0x01e7, 0x80f0, 0xac00
ax_pose_terminator
sHoppipPose224:
ax_pose 21, 0x01e7, 0x90ec, 0xac00
ax_pose_terminator
sHoppipPose225:
ax_pose 18, 0x01e6, 0x90ec, 0xac00
ax_pose_terminator
sHoppipPose226:
ax_pose 15, 0x01e6, 0x90ea, 0xac00
ax_pose_terminator
sHoppipPose227:
ax_pose 10, 0x01e6, 0x80f4, 0xac00
ax_pose_terminator
sHoppipPose228:
ax_pose 13, 0x01e6, 0x80f6, 0xac00
ax_pose_terminator
sHoppipPose229:
ax_pose 16, 0x01e3, 0x80f4, 0xac00
ax_pose_terminator
sHoppipPose230:
ax_pose 19, 0x01e7, 0x80f4, 0xac00
ax_pose_terminator
sHoppipPose231:
ax_pose 22, 0x01e8, 0x80f4, 0xac00
ax_pose_terminator
sHoppipPose232:
ax_pose 19, 0x01e7, 0x90ec, 0xac00
ax_pose_terminator
sHoppipPose233:
ax_pose 16, 0x01e3, 0x90ec, 0xac00
ax_pose_terminator
sHoppipPose234:
ax_pose 13, 0x01e6, 0x90ea, 0xac00
ax_pose_terminator
.align 2
sHoppipAnims_1_1:
ax_anim 4, 0, 0, 0, 0, 0, 0,
ax_anim 4, 0, 1, 0, -1, 0, 0,
ax_anim 4, 0, 2, 0, -2, 0, 0,
ax_anim 4, 0, 3, 0, -3, 0, 0,
ax_anim 4, 0, 4, 0, -3, 0, 0,
ax_anim 4, 0, 5, 0, -2, 0, 0,
ax_anim 4, 0, 6, 0, -1, 0, 0,
ax_anim 4, 0, 7, 0, 0, 0, 0,
ax_anim_terminator
sHoppipAnims_1_2:
ax_anim 4, 0, 8, 0, 0, 0, 0,
ax_anim 4, 0, 9, 0, -1, 0, 0,
ax_anim 4, 0, 10, 0, -2, 0, 0,
ax_anim 4, 0, 11, 0, -3, 0, 0,
ax_anim 4, 0, 12, 0, -3, 0, 0,
ax_anim 4, 0, 13, 0, -2, 0, 0,
ax_anim 4, 0, 14, 0, -1, 0, 0,
ax_anim 4, 0, 15, 0, 0, 0, 0,
ax_anim_terminator
sHoppipAnims_1_3:
ax_anim 4, 0, 16, 0, 0, 0, 0,
ax_anim 4, 0, 17, 0, -1, 0, 0,
ax_anim 4, 0, 18, 0, -2, 0, 0,
ax_anim 4, 0, 19, 0, -3, 0, 0,
ax_anim 4, 0, 20, 0, -3, 0, 0,
ax_anim 4, 0, 21, 0, -2, 0, 0,
ax_anim 4, 0, 22, 0, -1, 0, 0,
ax_anim 4, 0, 23, 0, 0, 0, 0,
ax_anim_terminator
sHoppipAnims_1_4:
ax_anim 4, 0, 24, 0, 0, 0, 0,
ax_anim 4, 0, 25, 0, -1, 0, 0,
ax_anim 4, 0, 26, 0, -2, 0, 0,
ax_anim 4, 0, 27, 0, -3, 0, 0,
ax_anim 4, 0, 28, 0, -3, 0, 0,
ax_anim 4, 0, 29, 0, -2, 0, 0,
ax_anim 4, 0, 30, 0, -1, 0, 0,
ax_anim 4, 0, 31, 0, 0, 0, 0,
ax_anim_terminator
sHoppipAnims_1_5:
ax_anim 4, 0, 32, 0, 0, 0, 0,
ax_anim 4, 0, 33, 0, -1, 0, 0,
ax_anim 4, 0, 34, 0, -2, 0, 0,
ax_anim 4, 0, 35, 0, -3, 0, 0,
ax_anim 4, 0, 36, 0, -3, 0, 0,
ax_anim 4, 0, 37, 0, -2, 0, 0,
ax_anim 4, 0, 38, 0, -1, 0, 0,
ax_anim 4, 0, 39, 0, 0, 0, 0,
ax_anim_terminator
sHoppipAnims_1_6:
ax_anim 4, 0, 40, 0, 0, 0, 0,
ax_anim 4, 0, 41, 0, -1, 0, 0,
ax_anim 4, 0, 42, 0, -2, 0, 0,
ax_anim 4, 0, 43, 0, -3, 0, 0,
ax_anim 4, 0, 44, 0, -3, 0, 0,
ax_anim 4, 0, 45, 0, -2, 0, 0,
ax_anim 4, 0, 46, 0, -1, 0, 0,
ax_anim 4, 0, 47, 0, 0, 0, 0,
ax_anim_terminator
sHoppipAnims_1_7:
ax_anim 4, 0, 48, 0, 0, 0, 0,
ax_anim 4, 0, 49, 0, -1, 0, 0,
ax_anim 4, 0, 50, 0, -2, 0, 0,
ax_anim 4, 0, 51, 0, -3, 0, 0,
ax_anim 4, 0, 52, 0, -3, 0, 0,
ax_anim 4, 0, 53, 0, -2, 0, 0,
ax_anim 4, 0, 54, 0, -1, 0, 0,
ax_anim 4, 0, 55, 0, 0, 0, 0,
ax_anim_terminator
sHoppipAnims_1_8:
ax_anim 4, 0, 56, 0, 0, 0, 0,
ax_anim 4, 0, 57, 0, -1, 0, 0,
ax_anim 4, 0, 58, 0, -2, 0, 0,
ax_anim 4, 0, 59, 0, -3, 0, 0,
ax_anim 4, 0, 60, 0, -3, 0, 0,
ax_anim 4, 0, 61, 0, -2, 0, 0,
ax_anim 4, 0, 62, 0, -1, 0, 0,
ax_anim 4, 0, 63, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sHoppipAnims_2_1:
ax_anim 2, 0, 64, 0, -1, 0, 0,
ax_anim 2, 0, 65, 0, -2, 0, 0,
ax_anim 2, 0, 64, 0, -3, 0, 0,
ax_anim 2, 0, 66, 0, -4, 0, 0,
ax_anim 2, 0, 64, 0, -5, 0, 0,
ax_anim 2, 0, 65, 0, -6, 0, 0,
ax_anim 1, 0, 64, 0, -2, 0, 3,
ax_anim 1, 0, 66, 0, 2, 0, 6,
ax_anim 1, 2, 64, 0, 6, 0, 9,
ax_anim 1, 0, 65, 0, 14, 0, 12,
ax_anim 2, 0, 64, 0, 22, 0, 16,
ax_anim 2, 1, 66, -1, 22, -1, 16,
ax_anim 2, 0, 64, 0, 22, 0, 16,
ax_anim 2, 0, 65, -1, 22, -1, 16,
ax_anim 2, 0, 64, 0, 22, 0, 16,
ax_anim 1, 0, 66, 0, 8, 0, 0,
ax_anim 1, 0, 64, 0, 2, 0, 0,
ax_anim 1, 0, 65, 0, 1, 0, 0,
ax_anim_terminator
sHoppipAnims_2_2:
ax_anim 2, 0, 67, 0, -1, 0, 0,
ax_anim 2, 0, 68, 0, -2, 0, 0,
ax_anim 2, 0, 67, 0, -3, 0, 0,
ax_anim 2, 0, 69, 0, -4, 0, 0,
ax_anim 2, 0, 67, 0, -5, 0, 0,
ax_anim 2, 0, 68, 0, -6, 0, 0,
ax_anim 1, 0, 67, 3, -2, 3, 3,
ax_anim 1, 0, 69, 6, 2, 6, 6,
ax_anim 1, 2, 67, 9, 6, 9, 8,
ax_anim 1, 0, 68, 14, 14, 12, 10,
ax_anim 2, 0, 67, 22, 22, 22, 19,
ax_anim 2, 1, 69, 21, 23, 21, 20,
ax_anim 2, 0, 67, 22, 22, 22, 19,
ax_anim 2, 0, 68, 21, 23, 21, 20,
ax_anim 2, 0, 67, 22, 22, 22, 19,
ax_anim 1, 0, 69, 8, 4, 8, 8,
ax_anim 1, 0, 67, 4, 0, 4, 4,
ax_anim 1, 0, 68, 2, -1, 2, 2,
ax_anim_terminator
sHoppipAnims_2_3:
ax_anim 2, 0, 70, 0, -1, 0, 0,
ax_anim 2, 0, 71, 0, -2, 0, 0,
ax_anim 2, 0, 70, 0, -3, 0, 0,
ax_anim 2, 0, 72, 0, -4, 0, 0,
ax_anim 2, 0, 70, 0, -5, 0, 0,
ax_anim 2, 0, 71, 0, -6, 0, 0,
ax_anim 1, 0, 70, 3, -5, 3, 0,
ax_anim 1, 0, 72, 6, -4, 6, 0,
ax_anim 1, 2, 70, 9, -3, 9, 0,
ax_anim 1, 0, 71, 12, -2, 12, 0,
ax_anim 2, 0, 70, 18, -1, 18, 0,
ax_anim 2, 1, 72, 18, -2, 17, 0,
ax_anim 2, 0, 70, 18, -1, 18, 0,
ax_anim 2, 0, 71, 18, -2, 17, 0,
ax_anim 2, 0, 70, 18, -1, 18, 0,
ax_anim 1, 0, 72, 8, -3, 8, 0,
ax_anim 1, 0, 70, 4, -2, 4, 0,
ax_anim 1, 0, 71, 2, -1, 2, 0,
ax_anim_terminator
sHoppipAnims_2_4:
ax_anim 2, 0, 73, 0, -1, 0, 0,
ax_anim 2, 0, 74, 0, -2, 0, 0,
ax_anim 2, 0, 73, 0, -3, 0, 0,
ax_anim 2, 0, 75, 0, -4, 0, 0,
ax_anim 2, 0, 73, 0, -5, 0, 0,
ax_anim 2, 0, 74, 0, -6, 0, 0,
ax_anim 1, 0, 73, 3, -8, 3, -3,
ax_anim 1, 0, 75, 6, -10, 6, -6,
ax_anim 1, 2, 73, 9, -13, 9, -9,
ax_anim 1, 0, 74, 12, -15, 12, -12,
ax_anim 2, 0, 73, 18, -18, 18, -18,
ax_anim 2, 1, 75, 17, -19, 17, -19,
ax_anim 2, 0, 73, 18, -18, 18, -18,
ax_anim 2, 0, 74, 17, -19, 17, -19,
ax_anim 2, 0, 73, 18, -18, 18, -18,
ax_anim 1, 0, 75, 8, -12, 8, -8,
ax_anim 1, 0, 73, 4, -8, 4, -4,
ax_anim 1, 0, 74, 2, -4, 2, -2,
ax_anim_terminator
sHoppipAnims_2_5:
ax_anim 2, 0, 76, 0, -1, 0, 0,
ax_anim 2, 0, 77, 0, -2, 0, 0,
ax_anim 2, 0, 76, 0, -3, 0, 0,
ax_anim 2, 0, 78, 0, -4, 0, 0,
ax_anim 2, 0, 76, 0, -5, 0, 0,
ax_anim 2, 0, 77, 0, -6, 0, 0,
ax_anim 1, 0, 76, 0, -8, 0, -3,
ax_anim 1, 0, 78, 0, -10, 0, -6,
ax_anim 1, 2, 76, 0, -13, 0, -9,
ax_anim 1, 0, 77, 0, -15, 0, -12,
ax_anim 2, 0, 76, 0, -18, 0, -18,
ax_anim 2, 1, 78, -1, -18, -1, -18,
ax_anim 2, 0, 76, 0, -18, 0, -18,
ax_anim 2, 0, 77, -1, -18, -1, -18,
ax_anim 2, 0, 76, 0, -18, 0, -18,
ax_anim 1, 0, 78, 0, -12, 0, -8,
ax_anim 1, 0, 76, 0, -8, 0, -4,
ax_anim 1, 0, 77, 0, -4, 0, -2,
ax_anim_terminator
sHoppipAnims_2_6:
ax_anim 2, 0, 79, 0, -1, 0, 0,
ax_anim 2, 0, 80, 0, -2, 0, 0,
ax_anim 2, 0, 79, 0, -3, 0, 0,
ax_anim 2, 0, 81, 0, -4, 0, 0,
ax_anim 2, 0, 79, 0, -5, 0, 0,
ax_anim 2, 0, 80, 0, -6, 0, 0,
ax_anim 1, 0, 79, -3, -8, -3, -3,
ax_anim 1, 0, 81, -6, -10, -6, -6,
ax_anim 1, 2, 79, -9, -13, -9, -9,
ax_anim 1, 0, 80, -12, -15, -12, -12,
ax_anim 2, 0, 79, -18, -18, -18, -18,
ax_anim 2, 1, 81, -17, -19, -17, -19,
ax_anim 2, 0, 79, -18, -18, -18, -18,
ax_anim 2, 0, 80, -17, -19, -17, -19,
ax_anim 2, 0, 79, -18, -18, -18, -18,
ax_anim 1, 0, 81, -8, -12, -8, -8,
ax_anim 1, 0, 79, -4, -8, -4, -4,
ax_anim 1, 0, 80, -2, -4, -2, -2,
ax_anim_terminator
sHoppipAnims_2_7:
ax_anim 2, 0, 82, 0, -1, 0, 0,
ax_anim 2, 0, 83, 0, -2, 0, 0,
ax_anim 2, 0, 82, 0, -3, 0, 0,
ax_anim 2, 0, 84, 0, -4, 0, 0,
ax_anim 2, 0, 82, 0, -5, 0, 0,
ax_anim 2, 0, 83, 0, -6, 0, 0,
ax_anim 1, 0, 82, -3, -5, -3, 0,
ax_anim 1, 0, 84, -6, -4, -6, 0,
ax_anim 1, 2, 82, -9, -3, -9, 0,
ax_anim 1, 0, 83, -12, -2, -12, 0,
ax_anim 2, 0, 82, -18, -1, -18, 0,
ax_anim 2, 1, 84, -18, -2, -17, 0,
ax_anim 2, 0, 82, -18, -1, -18, 0,
ax_anim 2, 0, 83, -18, -2, -17, 0,
ax_anim 2, 0, 82, -18, -1, -18, 0,
ax_anim 1, 0, 84, -8, -3, -8, 0,
ax_anim 1, 0, 82, -4, -2, -4, 0,
ax_anim 1, 0, 83, -2, -1, -2, 0,
ax_anim_terminator
sHoppipAnims_2_8:
ax_anim 2, 0, 85, 0, -1, 0, 0,
ax_anim 2, 0, 86, 0, -2, 0, 0,
ax_anim 2, 0, 85, 0, -3, 0, 0,
ax_anim 2, 0, 87, 0, -4, 0, 0,
ax_anim 2, 0, 85, 0, -5, 0, 0,
ax_anim 2, 0, 86, 0, -6, 0, 0,
ax_anim 1, 0, 85, -3, -2, -3, 3,
ax_anim 1, 0, 87, -6, 2, -6, 6,
ax_anim 1, 2, 85, -9, 6, -9, 8,
ax_anim 1, 0, 86, -14, 14, -12, 10,
ax_anim 2, 0, 85, -22, 22, -22, 19,
ax_anim 2, 1, 87, -21, 23, -21, 20,
ax_anim 2, 0, 85, -22, 22, -22, 19,
ax_anim 2, 0, 86, -21, 23, -21, 20,
ax_anim 2, 0, 85, -22, 22, -22, 19,
ax_anim 1, 0, 87, -8, 4, -8, 8,
ax_anim 1, 0, 85, -4, 0, -4, 4,
ax_anim 1, 0, 86, -2, -1, -2, 2,
ax_anim_terminator
.align 2
sHoppipAnims_3_1:
ax_anim 2, 0, 88, 0, -1, 0, 0,
ax_anim 2, 0, 89, 0, -2, 0, 0,
ax_anim 2, 0, 88, 0, -3, 0, 0,
ax_anim 2, 0, 90, 0, -4, 0, 0,
ax_anim 2, 0, 88, 0, -5, 0, 0,
ax_anim 2, 0, 89, 0, -6, 0, 0,
ax_anim 1, 0, 88, 0, -2, 0, 3,
ax_anim 1, 0, 90, 0, 2, 0, 6,
ax_anim 1, 2, 88, 0, 6, 0, 9,
ax_anim 1, 0, 89, 0, 14, 0, 12,
ax_anim 2, 0, 88, 0, 22, 0, 16,
ax_anim 2, 1, 90, -1, 22, -1, 16,
ax_anim 2, 0, 88, 0, 22, 0, 16,
ax_anim 2, 0, 89, -1, 22, -1, 16,
ax_anim 2, 0, 88, 0, 22, 0, 16,
ax_anim 1, 0, 90, 0, 8, 0, 0,
ax_anim 1, 0, 88, 0, 2, 0, 0,
ax_anim 1, 0, 89, 0, 1, 0, 0,
ax_anim_terminator
sHoppipAnims_3_2:
ax_anim 2, 0, 91, 0, -1, 0, 0,
ax_anim 2, 0, 92, 0, -2, 0, 0,
ax_anim 2, 0, 91, 0, -3, 0, 0,
ax_anim 2, 0, 93, 0, -4, 0, 0,
ax_anim 2, 0, 91, 0, -5, 0, 0,
ax_anim 2, 0, 92, 0, -6, 0, 0,
ax_anim 1, 0, 91, 3, -2, 3, 3,
ax_anim 1, 0, 93, 6, 2, 6, 6,
ax_anim 1, 2, 91, 9, 6, 9, 8,
ax_anim 1, 0, 92, 14, 14, 12, 10,
ax_anim 2, 0, 91, 22, 22, 22, 19,
ax_anim 2, 1, 93, 21, 23, 21, 20,
ax_anim 2, 0, 91, 22, 22, 22, 19,
ax_anim 2, 0, 92, 21, 23, 21, 20,
ax_anim 2, 0, 91, 22, 22, 22, 19,
ax_anim 1, 0, 93, 8, 4, 8, 8,
ax_anim 1, 0, 91, 4, 0, 4, 4,
ax_anim 1, 0, 92, 2, -1, 2, 2,
ax_anim_terminator
sHoppipAnims_3_3:
ax_anim 2, 0, 94, 0, -1, 0, 0,
ax_anim 2, 0, 95, 0, -2, 0, 0,
ax_anim 2, 0, 94, 0, -3, 0, 0,
ax_anim 2, 0, 96, 0, -4, 0, 0,
ax_anim 2, 0, 94, 0, -5, 0, 0,
ax_anim 2, 0, 95, 0, -6, 0, 0,
ax_anim 1, 0, 94, 3, -5, 3, 0,
ax_anim 1, 0, 96, 6, -4, 6, 0,
ax_anim 1, 2, 94, 9, -3, 9, 0,
ax_anim 1, 0, 95, 12, -2, 12, 0,
ax_anim 2, 0, 94, 18, -1, 18, 0,
ax_anim 2, 1, 96, 18, -2, 17, 0,
ax_anim 2, 0, 94, 18, -1, 18, 0,
ax_anim 2, 0, 95, 18, -2, 17, 0,
ax_anim 2, 0, 94, 18, -1, 18, 0,
ax_anim 1, 0, 96, 8, -3, 8, 0,
ax_anim 1, 0, 94, 4, -2, 4, 0,
ax_anim 1, 0, 95, 2, -1, 2, 0,
ax_anim_terminator
sHoppipAnims_3_4:
ax_anim 2, 0, 97, 0, -1, 0, 0,
ax_anim 2, 0, 98, 0, -2, 0, 0,
ax_anim 2, 0, 97, 0, -3, 0, 0,
ax_anim 2, 0, 99, 0, -4, 0, 0,
ax_anim 2, 0, 97, 0, -5, 0, 0,
ax_anim 2, 0, 98, 0, -6, 0, 0,
ax_anim 1, 0, 97, 3, -8, 3, -3,
ax_anim 1, 0, 99, 6, -10, 6, -6,
ax_anim 1, 2, 97, 9, -13, 9, -9,
ax_anim 1, 0, 98, 12, -15, 12, -12,
ax_anim 2, 0, 97, 18, -18, 18, -18,
ax_anim 2, 1, 99, 17, -19, 17, -19,
ax_anim 2, 0, 97, 18, -18, 18, -18,
ax_anim 2, 0, 98, 17, -19, 17, -19,
ax_anim 2, 0, 97, 18, -18, 18, -18,
ax_anim 1, 0, 99, 8, -12, 8, -8,
ax_anim 1, 0, 97, 4, -8, 4, -4,
ax_anim 1, 0, 98, 2, -4, 2, -2,
ax_anim_terminator
sHoppipAnims_3_5:
ax_anim 2, 0, 100, 0, -1, 0, 0,
ax_anim 2, 0, 101, 0, -2, 0, 0,
ax_anim 2, 0, 100, 0, -3, 0, 0,
ax_anim 2, 0, 102, 0, -4, 0, 0,
ax_anim 2, 0, 100, 0, -5, 0, 0,
ax_anim 2, 0, 101, 0, -6, 0, 0,
ax_anim 1, 0, 100, 0, -8, 0, -3,
ax_anim 1, 0, 102, 0, -10, 0, -6,
ax_anim 1, 2, 100, 0, -13, 0, -9,
ax_anim 1, 0, 101, 0, -15, 0, -12,
ax_anim 2, 0, 100, 0, -18, 0, -18,
ax_anim 2, 1, 102, -1, -18, -1, -18,
ax_anim 2, 0, 100, 0, -18, 0, -18,
ax_anim 2, 0, 101, -1, -18, -1, -18,
ax_anim 2, 0, 100, 0, -18, 0, -18,
ax_anim 1, 0, 102, 0, -12, 0, -8,
ax_anim 1, 0, 100, 0, -8, 0, -4,
ax_anim 1, 0, 101, 0, -4, 0, -2,
ax_anim_terminator
sHoppipAnims_3_6:
ax_anim 2, 0, 103, 0, -1, 0, 0,
ax_anim 2, 0, 104, 0, -2, 0, 0,
ax_anim 2, 0, 103, 0, -3, 0, 0,
ax_anim 2, 0, 105, 0, -4, 0, 0,
ax_anim 2, 0, 103, 0, -5, 0, 0,
ax_anim 2, 0, 104, 0, -6, 0, 0,
ax_anim 1, 0, 103, -3, -8, -3, -3,
ax_anim 1, 0, 105, -6, -10, -6, -6,
ax_anim 1, 2, 103, -9, -13, -9, -9,
ax_anim 1, 0, 104, -12, -15, -12, -12,
ax_anim 2, 0, 103, -18, -18, -18, -18,
ax_anim 2, 1, 105, -17, -19, -17, -19,
ax_anim 2, 0, 103, -18, -18, -18, -18,
ax_anim 2, 0, 104, -17, -19, -17, -19,
ax_anim 2, 0, 103, -18, -18, -18, -18,
ax_anim 1, 0, 105, -8, -12, -8, -8,
ax_anim 1, 0, 103, -4, -8, -4, -4,
ax_anim 1, 0, 104, -2, -4, -2, -2,
ax_anim_terminator
sHoppipAnims_3_7:
ax_anim 2, 0, 106, 0, -1, 0, 0,
ax_anim 2, 0, 107, 0, -2, 0, 0,
ax_anim 2, 0, 106, 0, -3, 0, 0,
ax_anim 2, 0, 108, 0, -4, 0, 0,
ax_anim 2, 0, 106, 0, -5, 0, 0,
ax_anim 2, 0, 107, 0, -6, 0, 0,
ax_anim 1, 0, 106, -3, -5, -3, 0,
ax_anim 1, 0, 108, -6, -4, -6, 0,
ax_anim 1, 2, 106, -9, -3, -9, 0,
ax_anim 1, 0, 107, -12, -2, -12, 0,
ax_anim 2, 0, 106, -18, -1, -18, 0,
ax_anim 2, 1, 108, -18, -2, -17, 0,
ax_anim 2, 0, 106, -18, -1, -18, 0,
ax_anim 2, 0, 107, -18, -2, -17, 0,
ax_anim 2, 0, 106, -18, -1, -18, 0,
ax_anim 1, 0, 108, -8, -3, -8, 0,
ax_anim 1, 0, 106, -4, -2, -4, 0,
ax_anim 1, 0, 107, -2, -1, -2, 0,
ax_anim_terminator
sHoppipAnims_3_8:
ax_anim 2, 0, 109, 0, -1, 0, 0,
ax_anim 2, 0, 110, 0, -2, 0, 0,
ax_anim 2, 0, 109, 0, -3, 0, 0,
ax_anim 2, 0, 111, 0, -4, 0, 0,
ax_anim 2, 0, 109, 0, -5, 0, 0,
ax_anim 2, 0, 110, 0, -6, 0, 0,
ax_anim 1, 0, 109, -3, -2, -3, 3,
ax_anim 1, 0, 111, -6, 2, -6, 6,
ax_anim 1, 2, 109, -9, 6, -9, 8,
ax_anim 1, 0, 110, -14, 14, -12, 10,
ax_anim 2, 0, 109, -22, 22, -22, 19,
ax_anim 2, 1, 111, -21, 23, -21, 20,
ax_anim 2, 0, 109, -22, 22, -22, 19,
ax_anim 2, 0, 110, -21, 23, -21, 20,
ax_anim 2, 0, 109, -22, 22, -22, 19,
ax_anim 1, 0, 111, -8, 4, -8, 8,
ax_anim 1, 0, 109, -4, 0, -4, 4,
ax_anim 1, 0, 110, -2, -1, -2, 2,
ax_anim_terminator
.align 2
sHoppipAnims_4_1:
ax_anim 2, 0, 112, 0, -1, 0, -1,
ax_anim 2, 0, 113, 0, -2, 0, -2,
ax_anim 2, 0, 113, 0, -4, 0, -4,
ax_anim 6, 2, 113, 0, -5, 0, -5,
ax_anim 1, 0, 114, 0, -3, 0, -3,
ax_anim 1, 0, 114, 0, 0, 0, 0,
ax_anim 2, 1, 114, 0, 5, 0, 5,
ax_anim 2, 0, 114, 1, 5, 1, 5,
ax_anim 2, 0, 114, 0, 5, 0, 5,
ax_anim 2, 0, 114, 1, 5, 1, 5,
ax_anim 2, 0, 114, 0, 5, 0, 5,
ax_anim 2, 0, 114, 1, 5, 1, 5,
ax_anim 2, 0, 112, 0, 2, 0, 2,
ax_anim_terminator
sHoppipAnims_4_2:
ax_anim 2, 0, 115, -1, -1, -1, -1,
ax_anim 2, 0, 116, -2, -2, -2, -2,
ax_anim 2, 0, 116, -4, -4, -4, -4,
ax_anim 6, 2, 116, -5, -5, -5, -5,
ax_anim 1, 0, 117, -3, -3, -3, -3,
ax_anim 1, 0, 117, 0, 0, 0, 0,
ax_anim 2, 1, 117, 5, 5, 5, 5,
ax_anim 2, 0, 117, 6, 4, 6, 4,
ax_anim 2, 0, 117, 5, 5, 5, 5,
ax_anim 2, 0, 117, 6, 4, 6, 4,
ax_anim 2, 0, 117, 5, 5, 5, 5,
ax_anim 2, 0, 117, 6, 4, 6, 4,
ax_anim 2, 0, 115, 2, 2, 2, 2,
ax_anim_terminator
sHoppipAnims_4_3:
ax_anim 2, 0, 118, -1, 0, -1, 0,
ax_anim 2, 0, 119, -2, 0, -2, 0,
ax_anim 2, 0, 119, -4, 0, -4, 0,
ax_anim 6, 2, 119, -5, 0, -5, 0,
ax_anim 1, 0, 120, -3, 0, -3, 0,
ax_anim 1, 0, 120, 0, 0, 0, 0,
ax_anim 2, 1, 120, 5, 0, 5, 0,
ax_anim 2, 0, 120, 5, -1, 5, -1,
ax_anim 2, 0, 120, 5, 0, 5, 0,
ax_anim 2, 0, 120, 5, -1, 5, -1,
ax_anim 2, 0, 120, 5, 0, 5, 0,
ax_anim 2, 0, 120, 5, -1, 5, -1,
ax_anim 2, 0, 118, 2, 0, 2, 0,
ax_anim_terminator
sHoppipAnims_4_4:
ax_anim 2, 0, 121, -1, 1, -1, 1,
ax_anim 2, 0, 122, -2, 2, -2, 2,
ax_anim 2, 0, 122, -4, 4, -4, 4,
ax_anim 6, 2, 122, -5, 5, -5, 5,
ax_anim 1, 0, 123, -3, 3, -3, 3,
ax_anim 1, 0, 123, 0, 0, 0, 0,
ax_anim 2, 1, 123, 5, -5, 5, -5,
ax_anim 2, 0, 123, 6, -4, 6, -4,
ax_anim 2, 0, 123, 5, -5, 5, -5,
ax_anim 2, 0, 123, 6, -4, 6, -4,
ax_anim 2, 0, 123, 5, -5, 5, -5,
ax_anim 2, 0, 123, 6, -4, 6, -4,
ax_anim 2, 0, 121, 2, -2, 2, -2,
ax_anim_terminator
sHoppipAnims_4_5:
ax_anim 2, 0, 124, 0, 1, 0, 1,
ax_anim 2, 0, 125, 0, 2, 0, 2,
ax_anim 2, 0, 125, 0, 4, 0, 4,
ax_anim 6, 2, 125, 0, 5, 0, 5,
ax_anim 1, 0, 126, 0, 3, 0, 3,
ax_anim 1, 0, 126, 0, 0, 0, 0,
ax_anim 2, 1, 126, 0, -5, 0, -5,
ax_anim 2, 0, 126, 1, -5, 1, -5,
ax_anim 2, 0, 126, 0, -5, 0, -5,
ax_anim 2, 0, 126, 1, -5, 1, -5,
ax_anim 2, 0, 126, 0, -5, 0, -5,
ax_anim 2, 0, 126, 1, -5, 1, -5,
ax_anim 2, 0, 124, 0, -2, 0, -2,
ax_anim_terminator
sHoppipAnims_4_6:
ax_anim 2, 0, 127, 1, 1, 1, 1,
ax_anim 2, 0, 128, 2, 2, 2, 2,
ax_anim 2, 0, 128, 4, 4, 4, 4,
ax_anim 6, 2, 128, 5, 5, 5, 5,
ax_anim 1, 0, 129, 3, 3, 3, 3,
ax_anim 1, 0, 129, 0, 0, 0, 0,
ax_anim 2, 1, 129, -5, -5, -5, -5,
ax_anim 2, 0, 129, -6, -4, -6, -4,
ax_anim 2, 0, 129, -5, -5, -5, -5,
ax_anim 2, 0, 129, -6, -4, -6, -4,
ax_anim 2, 0, 129, -5, -5, -5, -5,
ax_anim 2, 0, 129, -6, -4, -6, -4,
ax_anim 2, 0, 127, -2, -2, -2, -2,
ax_anim_terminator
sHoppipAnims_4_7:
ax_anim 2, 0, 130, 1, 0, 1, 0,
ax_anim 2, 0, 131, 2, 0, 2, 0,
ax_anim 2, 0, 131, 4, 0, 4, 0,
ax_anim 6, 2, 131, 5, 0, 5, 0,
ax_anim 1, 0, 132, 3, 0, 3, 0,
ax_anim 1, 0, 132, 0, 0, 0, 0,
ax_anim 2, 1, 132, -5, 0, -5, 0,
ax_anim 2, 0, 132, -5, -1, -5, -1,
ax_anim 2, 0, 132, -5, 0, -5, 0,
ax_anim 2, 0, 132, -5, -1, -5, -1,
ax_anim 2, 0, 132, -5, 0, -5, 0,
ax_anim 2, 0, 132, -5, -1, -5, -1,
ax_anim 2, 0, 130, -2, 0, -2, 0,
ax_anim_terminator
sHoppipAnims_4_8:
ax_anim 2, 0, 133, 1, -1, 1, -1,
ax_anim 2, 0, 134, 2, -2, 2, -2,
ax_anim 2, 0, 134, 4, -4, 4, -4,
ax_anim 6, 2, 134, 5, -5, 5, -5,
ax_anim 1, 0, 135, 3, -3, 3, -3,
ax_anim 1, 0, 135, 0, 0, 0, 0,
ax_anim 2, 1, 135, -5, 5, -5, 5,
ax_anim 2, 0, 135, -6, 4, -6, 4,
ax_anim 2, 0, 135, -5, 5, -5, 5,
ax_anim 2, 0, 135, -6, 4, -6, 4,
ax_anim 2, 0, 135, -5, 5, -5, 5,
ax_anim 2, 0, 135, -6, 4, -6, 4,
ax_anim 2, 0, 133, -2, 2, -2, 2,
ax_anim_terminator
.align 2
sHoppipAnims_5_1:
ax_anim 1, 0, 136, 0, -1, 0, 0,
ax_anim 1, 0, 137, 0, -3, 0, 0,
ax_anim 1, 0, 138, 0, -5, 0, 0,
ax_anim 1, 0, 139, 0, -6, 0, 0,
ax_anim 1, 0, 140, 0, -7, 0, 0,
ax_anim 1, 0, 141, 0, -8, 0, 0,
ax_anim 1, 0, 142, 0, -9, 0, 0,
ax_anim 1, 0, 143, 0, -9, 0, 0,
ax_anim 1, 0, 136, 0, -9, 0, 0,
ax_anim 1, 2, 137, 0, -9, 0, 0,
ax_anim 1, 0, 138, 0, -9, 0, 0,
ax_anim 2, 0, 139, 0, -9, 0, 0,
ax_anim 2, 0, 140, 0, -9, 0, 0,
ax_anim 2, 0, 141, 0, -8, 0, 0,
ax_anim 2, 0, 142, 0, -5, 0, 0,
ax_anim 2, 0, 143, 0, -3, 0, 0,
ax_anim 4, 0, 136, 0, -1, 0, 0,
ax_anim_terminator
sHoppipAnims_5_2:
ax_anim 1, 0, 143, 0, -1, 0, 0,
ax_anim 1, 0, 136, 0, -3, 0, 0,
ax_anim 1, 0, 137, 0, -5, 0, 0,
ax_anim 1, 0, 138, 0, -6, 0, 0,
ax_anim 1, 0, 139, 0, -7, 0, 0,
ax_anim 1, 0, 140, 0, -8, 0, 0,
ax_anim 1, 0, 141, 0, -9, 0, 0,
ax_anim 1, 0, 142, 0, -9, 0, 0,
ax_anim 1, 0, 143, 0, -9, 0, 0,
ax_anim 1, 2, 136, 0, -9, 0, 0,
ax_anim 1, 0, 137, 0, -9, 0, 0,
ax_anim 2, 0, 138, 0, -9, 0, 0,
ax_anim 2, 0, 139, 0, -9, 0, 0,
ax_anim 2, 0, 140, 0, -8, 0, 0,
ax_anim 2, 0, 141, 0, -5, 0, 0,
ax_anim 2, 0, 142, 0, -3, 0, 0,
ax_anim 4, 0, 143, 0, -1, 0, 0,
ax_anim_terminator
sHoppipAnims_5_3:
ax_anim 1, 0, 142, 0, -1, 0, 0,
ax_anim 1, 0, 143, 0, -3, 0, 0,
ax_anim 1, 0, 136, 0, -5, 0, 0,
ax_anim 1, 0, 137, 0, -6, 0, 0,
ax_anim 1, 0, 138, 0, -7, 0, 0,
ax_anim 1, 0, 139, 0, -8, 0, 0,
ax_anim 1, 0, 140, 0, -9, 0, 0,
ax_anim 1, 0, 141, 0, -9, 0, 0,
ax_anim 1, 0, 142, 0, -9, 0, 0,
ax_anim 1, 2, 143, 0, -9, 0, 0,
ax_anim 1, 0, 136, 0, -9, 0, 0,
ax_anim 2, 0, 137, 0, -9, 0, 0,
ax_anim 2, 0, 138, 0, -9, 0, 0,
ax_anim 2, 0, 139, 0, -8, 0, 0,
ax_anim 2, 0, 140, 0, -5, 0, 0,
ax_anim 2, 0, 141, 0, -3, 0, 0,
ax_anim 4, 0, 142, 0, -1, 0, 0,
ax_anim_terminator
sHoppipAnims_5_4:
ax_anim 1, 0, 141, 0, -1, 0, 0,
ax_anim 1, 0, 142, 0, -3, 0, 0,
ax_anim 1, 0, 143, 0, -5, 0, 0,
ax_anim 1, 0, 136, 0, -6, 0, 0,
ax_anim 1, 0, 137, 0, -7, 0, 0,
ax_anim 1, 0, 138, 0, -8, 0, 0,
ax_anim 1, 0, 139, 0, -9, 0, 0,
ax_anim 1, 0, 140, 0, -9, 0, 0,
ax_anim 1, 0, 141, 0, -9, 0, 0,
ax_anim 1, 2, 142, 0, -9, 0, 0,
ax_anim 1, 0, 143, 0, -9, 0, 0,
ax_anim 2, 0, 136, 0, -9, 0, 0,
ax_anim 2, 0, 137, 0, -9, 0, 0,
ax_anim 2, 0, 138, 0, -8, 0, 0,
ax_anim 2, 0, 139, 0, -5, 0, 0,
ax_anim 2, 0, 140, 0, -3, 0, 0,
ax_anim 4, 0, 141, 0, -1, 0, 0,
ax_anim_terminator
sHoppipAnims_5_5:
ax_anim 1, 0, 140, 0, -1, 0, 0,
ax_anim 1, 0, 141, 0, -3, 0, 0,
ax_anim 1, 0, 142, 0, -5, 0, 0,
ax_anim 1, 0, 143, 0, -6, 0, 0,
ax_anim 1, 0, 136, 0, -7, 0, 0,
ax_anim 1, 0, 137, 0, -8, 0, 0,
ax_anim 1, 0, 138, 0, -9, 0, 0,
ax_anim 1, 0, 139, 0, -9, 0, 0,
ax_anim 1, 0, 140, 0, -9, 0, 0,
ax_anim 1, 2, 141, 0, -9, 0, 0,
ax_anim 1, 0, 142, 0, -9, 0, 0,
ax_anim 2, 0, 143, 0, -9, 0, 0,
ax_anim 2, 0, 136, 0, -9, 0, 0,
ax_anim 2, 0, 137, 0, -8, 0, 0,
ax_anim 2, 0, 138, 0, -5, 0, 0,
ax_anim 2, 0, 139, 0, -3, 0, 0,
ax_anim 4, 0, 140, 0, -1, 0, 0,
ax_anim_terminator
sHoppipAnims_5_6:
ax_anim 1, 0, 139, 0, -1, 0, 0,
ax_anim 1, 0, 140, 0, -3, 0, 0,
ax_anim 1, 0, 141, 0, -5, 0, 0,
ax_anim 1, 0, 142, 0, -6, 0, 0,
ax_anim 1, 0, 143, 0, -7, 0, 0,
ax_anim 1, 0, 136, 0, -8, 0, 0,
ax_anim 1, 0, 137, 0, -9, 0, 0,
ax_anim 1, 0, 138, 0, -9, 0, 0,
ax_anim 1, 0, 139, 0, -9, 0, 0,
ax_anim 1, 2, 140, 0, -9, 0, 0,
ax_anim 1, 0, 141, 0, -9, 0, 0,
ax_anim 2, 0, 142, 0, -9, 0, 0,
ax_anim 2, 0, 143, 0, -9, 0, 0,
ax_anim 2, 0, 136, 0, -8, 0, 0,
ax_anim 2, 0, 137, 0, -5, 0, 0,
ax_anim 2, 0, 138, 0, -3, 0, 0,
ax_anim 4, 0, 139, 0, -1, 0, 0,
ax_anim_terminator
sHoppipAnims_5_7:
ax_anim 1, 0, 138, 0, -1, 0, 0,
ax_anim 1, 0, 139, 0, -3, 0, 0,
ax_anim 1, 0, 140, 0, -5, 0, 0,
ax_anim 1, 0, 141, 0, -6, 0, 0,
ax_anim 1, 0, 142, 0, -7, 0, 0,
ax_anim 1, 0, 143, 0, -8, 0, 0,
ax_anim 1, 0, 136, 0, -9, 0, 0,
ax_anim 1, 0, 137, 0, -9, 0, 0,
ax_anim 1, 0, 138, 0, -9, 0, 0,
ax_anim 1, 2, 139, 0, -9, 0, 0,
ax_anim 1, 0, 140, 0, -9, 0, 0,
ax_anim 2, 0, 141, 0, -9, 0, 0,
ax_anim 2, 0, 142, 0, -9, 0, 0,
ax_anim 2, 0, 143, 0, -8, 0, 0,
ax_anim 2, 0, 136, 0, -5, 0, 0,
ax_anim 2, 0, 137, 0, -3, 0, 0,
ax_anim 4, 0, 138, 0, -1, 0, 0,
ax_anim_terminator
sHoppipAnims_5_8:
ax_anim 1, 0, 137, 0, -1, 0, 0,
ax_anim 1, 0, 138, 0, -3, 0, 0,
ax_anim 1, 0, 139, 0, -5, 0, 0,
ax_anim 1, 0, 140, 0, -6, 0, 0,
ax_anim 1, 0, 141, 0, -7, 0, 0,
ax_anim 1, 0, 142, 0, -8, 0, 0,
ax_anim 1, 0, 143, 0, -9, 0, 0,
ax_anim 1, 0, 136, 0, -9, 0, 0,
ax_anim 1, 0, 137, 0, -9, 0, 0,
ax_anim 1, 2, 138, 0, -9, 0, 0,
ax_anim 1, 0, 139, 0, -9, 0, 0,
ax_anim 2, 0, 140, 0, -9, 0, 0,
ax_anim 2, 0, 141, 0, -9, 0, 0,
ax_anim 2, 0, 142, 0, -8, 0, 0,
ax_anim 2, 0, 143, 0, -5, 0, 0,
ax_anim 2, 0, 136, 0, -3, 0, 0,
ax_anim 4, 0, 137, 0, -1, 0, 0,
ax_anim_terminator
.align 2
sHoppipAnims_6_1:
ax_anim 8, 0, 144, 0, 0, 0, 0,
ax_anim 8, 0, 144, 0, -1, 0, 0,
ax_anim 26, 0, 144, 0, -2, 0, 0,
ax_anim 8, 0, 145, 0, -2, 0, 0,
ax_anim 8, 0, 145, 0, -1, 0, 0,
ax_anim 26, 0, 145, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sHoppipAnims_7_1:
ax_anim 2, 0, 146, 0, -2, 0, -2,
ax_anim 8, 0, 146, 0, -3, 0, -3,
ax_anim_terminator
sHoppipAnims_7_2:
ax_anim 2, 0, 147, -2, -2, -2, -2,
ax_anim 8, 0, 147, -3, -3, -3, -3,
ax_anim_terminator
sHoppipAnims_7_3:
ax_anim 2, 0, 148, -2, 0, -2, 0,
ax_anim 8, 0, 148, -3, 0, -3, 0,
ax_anim_terminator
sHoppipAnims_7_4:
ax_anim 2, 0, 149, -2, 2, -2, 2,
ax_anim 8, 0, 149, -3, 3, -3, 3,
ax_anim_terminator
sHoppipAnims_7_5:
ax_anim 2, 0, 150, 0, 2, 0, 2,
ax_anim 8, 0, 150, 0, 3, 0, 3,
ax_anim_terminator
sHoppipAnims_7_6:
ax_anim 2, 0, 151, 2, 2, 2, 2,
ax_anim 8, 0, 151, 3, 3, 3, 3,
ax_anim_terminator
sHoppipAnims_7_7:
ax_anim 2, 0, 152, 2, 0, 2, 0,
ax_anim 8, 0, 152, 3, 0, 3, 0,
ax_anim_terminator
sHoppipAnims_7_8:
ax_anim 2, 0, 153, 2, -2, 2, -2,
ax_anim 8, 0, 153, 3, -3, 3, -3,
ax_anim_terminator
.align 2
sHoppipAnims_8_1:
ax_anim 60, 0, 154, 0, 3, 0, 0,
ax_anim 10, 0, 162, -1, 2, 0, 0,
ax_anim 8, 0, 162, 0, 3, 0, 0,
ax_anim 10, 0, 162, 0, 3, 0, 0,
ax_anim 8, 0, 162, -1, 2, 0, 0,
ax_anim 6, 0, 162, 0, 3, 0, 0,
ax_anim 4, 0, 162, -1, 2, 0, 0,
ax_anim 2, 0, 162, 0, 3, 0, 0,
ax_anim 8, 0, 163, -1, -1, 0, 0,
ax_anim 8, 0, 164, -1, -2, 0, 0,
ax_anim 8, 0, 165, -2, -3, 0, 0,
ax_anim 8, 0, 158, -2, -3, 0, 0,
ax_anim 8, 0, 159, -1, -2, 0, 0,
ax_anim 8, 0, 160, -1, -1, 0, 0,
ax_anim 8, 0, 161, 0, 1, 0, 0,
ax_anim_terminator
sHoppipAnims_8_2:
ax_anim 60, 0, 161, 0, 3, 0, 0,
ax_anim 10, 0, 169, 1, 2, 0, 0,
ax_anim 8, 0, 169, 0, 3, 0, 0,
ax_anim 10, 0, 169, 0, 3, 0, 0,
ax_anim 8, 0, 169, 1, 2, 0, 0,
ax_anim 6, 0, 169, 0, 3, 0, 0,
ax_anim 4, 0, 169, 1, 2, 0, 0,
ax_anim 2, 0, 169, 0, 3, 0, 0,
ax_anim 8, 0, 162, 1, -1, 0, 0,
ax_anim 8, 0, 163, 1, -2, 0, 0,
ax_anim 8, 0, 164, 2, -3, 0, 0,
ax_anim 8, 0, 157, 2, -3, 0, 0,
ax_anim 8, 0, 158, 1, -2, 0, 0,
ax_anim 8, 0, 159, 1, -1, 0, 0,
ax_anim 8, 0, 160, 0, 1, 0, 0,
ax_anim_terminator
sHoppipAnims_8_3:
ax_anim 60, 0, 160, 0, 3, 0, 0,
ax_anim 10, 0, 168, 0, 2, 0, 0,
ax_anim 8, 0, 168, 0, 3, 0, 0,
ax_anim 10, 0, 168, 0, 3, 0, 0,
ax_anim 8, 0, 168, 0, 2, 0, 0,
ax_anim 6, 0, 168, 0, 3, 0, 0,
ax_anim 4, 0, 168, 0, 2, 0, 0,
ax_anim 2, 0, 168, 0, 3, 0, 0,
ax_anim 8, 0, 169, 0, -1, 0, 0,
ax_anim 8, 0, 162, 1, -2, 0, 0,
ax_anim 8, 0, 163, 2, -3, 0, 0,
ax_anim 8, 0, 156, 2, -3, 0, 0,
ax_anim 8, 0, 157, 1, -2, 0, 0,
ax_anim 8, 0, 158, 1, -1, 0, 0,
ax_anim 8, 0, 159, 0, 1, 0, 0,
ax_anim_terminator
sHoppipAnims_8_4:
ax_anim 60, 0, 159, 0, 3, 0, 0,
ax_anim 10, 0, 167, -1, 2, 0, 0,
ax_anim 8, 0, 167, 0, 3, 0, 0,
ax_anim 10, 0, 167, 0, 3, 0, 0,
ax_anim 8, 0, 167, -1, 2, 0, 0,
ax_anim 6, 0, 167, 0, 3, 0, 0,
ax_anim 4, 0, 167, -1, 2, 0, 0,
ax_anim 2, 0, 167, 0, 3, 0, 0,
ax_anim 8, 0, 168, -1, -1, 0, 0,
ax_anim 8, 0, 169, 1, -2, 0, 0,
ax_anim 8, 0, 162, 2, -3, 0, 0,
ax_anim 8, 0, 155, 2, -3, 0, 0,
ax_anim 8, 0, 156, 1, -2, 0, 0,
ax_anim 8, 0, 157, 1, -1, 0, 0,
ax_anim 8, 0, 158, 0, 1, 0, 0,
ax_anim_terminator
sHoppipAnims_8_5:
ax_anim 60, 0, 158, 0, 3, 0, 0,
ax_anim 10, 0, 166, 1, 2, 0, 0,
ax_anim 8, 0, 166, 0, 3, 0, 0,
ax_anim 10, 0, 166, 0, 3, 0, 0,
ax_anim 8, 0, 166, 1, 2, 0, 0,
ax_anim 6, 0, 166, 0, 3, 0, 0,
ax_anim 4, 0, 166, 1, 2, 0, 0,
ax_anim 2, 0, 166, 0, 3, 0, 0,
ax_anim 8, 0, 167, 1, -1, 0, 0,
ax_anim 8, 0, 168, 1, -2, 0, 0,
ax_anim 8, 0, 169, 2, -3, 0, 0,
ax_anim 8, 0, 154, 2, -3, 0, 0,
ax_anim 8, 0, 155, 1, -2, 0, 0,
ax_anim 8, 0, 156, 1, -1, 0, 0,
ax_anim 8, 0, 157, 0, 1, 0, 0,
ax_anim_terminator
sHoppipAnims_8_6:
ax_anim 60, 0, 157, 0, 3, 0, 0,
ax_anim 10, 0, 165, 1, 2, 0, 0,
ax_anim 8, 0, 165, 0, 3, 0, 0,
ax_anim 10, 0, 165, 0, 3, 0, 0,
ax_anim 8, 0, 165, 1, 2, 0, 0,
ax_anim 6, 0, 165, 0, 3, 0, 0,
ax_anim 4, 0, 165, 1, 2, 0, 0,
ax_anim 2, 0, 165, 0, 3, 0, 0,
ax_anim 8, 0, 166, 1, -1, 0, 0,
ax_anim 8, 0, 167, 1, -2, 0, 0,
ax_anim 8, 0, 168, 2, -3, 0, 0,
ax_anim 8, 0, 161, 2, -3, 0, 0,
ax_anim 8, 0, 154, 1, -2, 0, 0,
ax_anim 8, 0, 155, 1, -1, 0, 0,
ax_anim 8, 0, 156, 0, 1, 0, 0,
ax_anim_terminator
sHoppipAnims_8_7:
ax_anim 60, 0, 156, 0, 3, 0, 0,
ax_anim 10, 0, 164, -1, 2, 0, 0,
ax_anim 8, 0, 164, 0, 3, 0, 0,
ax_anim 10, 0, 164, 0, 3, 0, 0,
ax_anim 8, 0, 164, -1, 2, 0, 0,
ax_anim 6, 0, 164, 0, 3, 0, 0,
ax_anim 4, 0, 164, -1, 2, 0, 0,
ax_anim 2, 0, 164, 0, 3, 0, 0,
ax_anim 8, 0, 165, -1, -1, 0, 0,
ax_anim 8, 0, 166, -1, -2, 0, 0,
ax_anim 8, 0, 167, -2, -3, 0, 0,
ax_anim 8, 0, 168, -2, -3, 0, 0,
ax_anim 8, 0, 177, -1, -2, 0, 0,
ax_anim 8, 0, 154, -1, -1, 0, 0,
ax_anim 8, 0, 155, 0, 1, 0, 0,
ax_anim_terminator
sHoppipAnims_8_8:
ax_anim 60, 0, 155, 0, 3, 0, 0,
ax_anim 10, 0, 163, -1, 2, 0, 0,
ax_anim 8, 0, 163, 0, 3, 0, 0,
ax_anim 10, 0, 163, 0, 3, 0, 0,
ax_anim 8, 0, 163, -1, 2, 0, 0,
ax_anim 6, 0, 163, 0, 3, 0, 0,
ax_anim 4, 0, 163, -1, 2, 0, 0,
ax_anim 2, 0, 163, 0, 3, 0, 0,
ax_anim 8, 0, 164, -1, -1, 0, 0,
ax_anim 8, 0, 165, -1, -2, 0, 0,
ax_anim 8, 0, 166, -2, -3, 0, 0,
ax_anim 8, 0, 159, -2, -3, 0, 0,
ax_anim 8, 0, 160, -1, -2, 0, 0,
ax_anim 8, 0, 161, -1, -1, 0, 0,
ax_anim 8, 0, 154, 0, 1, 0, 0,
ax_anim_terminator
.align 2
sHoppipAnims_9_1:
ax_anim 2, 0, 178, 0, 0, 0, 0,
ax_anim 1, 0, 179, 6, 3, 6, 3,
ax_anim 2, 0, 180, 8, 11, 8, 11,
ax_anim 2, 0, 181, 7, 20, 7, 20,
ax_anim 3, 0, 182, 0, 23, 0, 22,
ax_anim 2, 3, 183, -7, 20, -7, 20,
ax_anim 2, 0, 184, -8, 11, -8, 11,
ax_anim 1, 0, 185, -6, 3, -6, 3,
ax_anim 1, 0, 178, 0, 0, 0, 0,
ax_anim_terminator
sHoppipAnims_9_2:
ax_anim 2, 0, 185, 0, 0, 0, 0,
ax_anim 1, 0, 178, 8, 0, 8, 0,
ax_anim 2, 0, 179, 18, 5, 18, 5,
ax_anim 2, 0, 180, 21, 13, 21, 13,
ax_anim 3, 0, 181, 21, 22, 21, 21,
ax_anim 2, 3, 182, 11, 25, 11, 23,
ax_anim 2, 0, 183, 4, 18, 4, 18,
ax_anim 1, 0, 184, 0, 7, 0, 7,
ax_anim 1, 0, 185, 0, 0, 0, 0,
ax_anim_terminator
sHoppipAnims_9_3:
ax_anim 2, 0, 184, 0, 0, 0, 0,
ax_anim 1, 0, 185, 3, -5, 3, -5,
ax_anim 2, 0, 178, 11, -6, 11, -6,
ax_anim 2, 0, 179, 17, -3, 17, -3,
ax_anim 3, 0, 180, 19, 2, 19, 0,
ax_anim 2, 3, 181, 18, 7, 18, 6,
ax_anim 2, 0, 182, 12, 8, 12, 8,
ax_anim 1, 0, 183, 4, 5, 4, 5,
ax_anim 1, 0, 184, 0, 0, 0, 0,
ax_anim_terminator
sHoppipAnims_9_4:
ax_anim 2, 0, 183, 0, 0, 0, 0,
ax_anim 1, 0, 184, 0, -8, 0, -8,
ax_anim 2, 0, 185, 4, -16, 4, -16,
ax_anim 2, 0, 178, 12, -20, 12, -21,
ax_anim 3, 0, 179, 20, -18, 20, -20,
ax_anim 2, 3, 180, 21, -12, 21, -13,
ax_anim 2, 0, 181, 18, -4, 18, -4,
ax_anim 1, 0, 182, 8, 0, 8, 0,
ax_anim 1, 0, 183, 0, 0, 0, 0,
ax_anim_terminator
sHoppipAnims_9_5:
ax_anim 2, 0, 182, 0, 0, 0, 0,
ax_anim 1, 0, 183, -8, -4, -8, -4,
ax_anim 2, 0, 184, -9, -10, -9, -10,
ax_anim 2, 0, 185, -7, -17, -7, -18,
ax_anim 3, 0, 178, 0, -19, 0, -21,
ax_anim 2, 3, 179, 7, -17, 7, -18,
ax_anim 2, 0, 180, 9, -10, 9, -10,
ax_anim 1, 0, 181, 8, -4, 8, -4,
ax_anim 1, 0, 182, 0, 0, 0, 0,
ax_anim_terminator
sHoppipAnims_9_6:
ax_anim 2, 0, 181, 0, 0, 0, 0,
ax_anim 1, 0, 180, 0, -8, 0, -8,
ax_anim 2, 0, 179, -4, -16, -4, -16,
ax_anim 2, 0, 178, -12, -20, -12, -19,
ax_anim 3, 0, 185, -20, -18, -20, -16,
ax_anim 2, 3, 184, -21, -12, -21, -11,
ax_anim 2, 0, 183, -18, -4, -18, -4,
ax_anim 1, 0, 182, -8, 0, -8, 0,
ax_anim 1, 0, 181, 0, 0, 0, 0,
ax_anim_terminator
sHoppipAnims_9_7:
ax_anim 2, 0, 180, 0, 0, 0, 0,
ax_anim 1, 0, 179, -3, -5, -3, -5,
ax_anim 2, 0, 178, -11, -6, -11, -6,
ax_anim 2, 0, 185, -17, -3, -17, -3,
ax_anim 3, 0, 184, -19, 2, -19, 0,
ax_anim 2, 3, 183, -18, 7, -18, 6,
ax_anim 2, 0, 182, -12, 8, -12, 8,
ax_anim 1, 0, 181, -4, 5, -4, 5,
ax_anim 1, 0, 180, 0, 0, 0, 0,
ax_anim_terminator
sHoppipAnims_9_8:
ax_anim 2, 0, 179, 0, 0, 0, 0,
ax_anim 1, 0, 178, -8, 0, -8, 0,
ax_anim 2, 0, 185, -18, 5, -18, 5,
ax_anim 2, 0, 184, -21, 13, -21, 13,
ax_anim 3, 0, 183, -21, 22, -21, 21,
ax_anim 2, 3, 182, -11, 25, -11, 23,
ax_anim 2, 0, 181, -4, 18, -4, 18,
ax_anim 1, 0, 180, 0, 7, 0, 7,
ax_anim 1, 0, 179, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sHoppipAnims_10_1:
ax_anim 2, 0, 186, 0, 0, 0, 0,
ax_anim 2, 0, 186, 6, 0, 6, 0,
ax_anim 2, 0, 186, -6, 0, -6, 0,
ax_anim 2, 0, 186, 10, 0, 10, 0,
ax_anim 2, 0, 186, -10, 0, -10, 0,
ax_anim 2, 0, 186, 12, 0, 12, 0,
ax_anim 3, 0, 186, -12, 0, -12, 0,
ax_anim 3, 0, 186, 13, 0, 13, 0,
ax_anim 3, 0, 186, -13, 0, -13, 0,
ax_anim 2, 0, 186, 12, 0, 12, 0,
ax_anim 3, 0, 186, -12, 0, -12, 0,
ax_anim 2, 0, 186, 10, 0, 10, 0,
ax_anim 2, 0, 186, -10, 0, -10, 0,
ax_anim 2, 0, 186, 6, 0, 6, 0,
ax_anim 2, 0, 186, -6, 0, -6, 0,
ax_anim 2, 0, 186, 0, 0, 0, 0,
ax_anim_terminator
sHoppipAnims_10_2:
ax_anim 2, 0, 187, 0, 0, 0, 0,
ax_anim 2, 0, 187, 6, -6, 6, -6,
ax_anim 2, 0, 187, -6, 6, -6, 6,
ax_anim 2, 0, 187, 10, -10, 10, -10,
ax_anim 2, 0, 187, -10, 10, -10, 10,
ax_anim 2, 0, 187, 12, -12, 12, -12,
ax_anim 3, 0, 187, -12, 12, -12, 12,
ax_anim 3, 0, 187, 13, -13, 13, -13,
ax_anim 3, 0, 187, -13, 13, -13, 13,
ax_anim 2, 0, 187, 12, -12, 12, -12,
ax_anim 3, 0, 187, -12, 12, -12, 12,
ax_anim 2, 0, 187, 10, -10, 10, -10,
ax_anim 2, 0, 187, -10, 10, -10, 10,
ax_anim 2, 0, 187, 6, -6, 6, -6,
ax_anim 2, 0, 187, -6, 6, -6, 6,
ax_anim 2, 0, 187, 0, 0, 0, 0,
ax_anim_terminator
sHoppipAnims_10_3:
ax_anim 2, 0, 188, 0, 0, 0, 0,
ax_anim 2, 0, 188, 0, -6, 0, -6,
ax_anim 2, 0, 188, 0, 6, 0, 6,
ax_anim 2, 0, 188, 0, -10, 0, -10,
ax_anim 2, 0, 188, 0, 10, 0, 10,
ax_anim 2, 0, 188, 0, -12, 0, -12,
ax_anim 3, 0, 188, 0, 12, 0, 12,
ax_anim 3, 0, 188, 0, -13, 0, -13,
ax_anim 3, 0, 188, 0, 13, 0, 13,
ax_anim 2, 0, 188, 0, -12, 0, -12,
ax_anim 3, 0, 188, 0, 12, 0, 12,
ax_anim 2, 0, 188, 0, -10, 0, -10,
ax_anim 2, 0, 188, 0, 10, 0, 10,
ax_anim 2, 0, 188, 0, -6, 0, -6,
ax_anim 2, 0, 188, 0, 6, 0, 6,
ax_anim 2, 0, 188, 0, 0, 0, 0,
ax_anim_terminator
sHoppipAnims_10_4:
ax_anim 2, 0, 189, 0, 0, 0, 0,
ax_anim 2, 0, 189, -6, -6, -6, -6,
ax_anim 2, 0, 189, 6, 6, 6, 6,
ax_anim 2, 0, 189, -10, -10, -10, -10,
ax_anim 2, 0, 189, 10, 10, 10, 10,
ax_anim 2, 0, 189, -12, -12, -12, -12,
ax_anim 3, 0, 189, 12, 12, 12, 12,
ax_anim 3, 0, 189, -13, -13, -13, -13,
ax_anim 3, 0, 189, 13, 13, 13, 13,
ax_anim 2, 0, 189, -12, -12, -12, -12,
ax_anim 3, 0, 189, 12, 12, 12, 12,
ax_anim 2, 0, 189, -10, -10, -10, -10,
ax_anim 2, 0, 189, 10, 10, 10, 10,
ax_anim 2, 0, 189, -6, -6, -6, -6,
ax_anim 2, 0, 189, 6, 6, 6, 6,
ax_anim 2, 0, 189, 0, 0, 0, 0,
ax_anim_terminator
sHoppipAnims_10_5:
ax_anim 2, 0, 190, 0, 0, 0, 0,
ax_anim 2, 0, 190, 6, 0, 6, 0,
ax_anim 2, 0, 190, -6, 0, -6, 0,
ax_anim 2, 0, 190, 10, 0, 10, 0,
ax_anim 2, 0, 190, -10, 0, -10, 0,
ax_anim 2, 0, 190, 12, 0, 12, 0,
ax_anim 3, 0, 190, -12, 0, -12, 0,
ax_anim 3, 0, 190, 13, 0, 13, 0,
ax_anim 3, 0, 190, -13, 0, -13, 0,
ax_anim 2, 0, 190, 12, 0, 12, 0,
ax_anim 3, 0, 190, -12, 0, -12, 0,
ax_anim 2, 0, 190, 10, 0, 10, 0,
ax_anim 2, 0, 190, -10, 0, -10, 0,
ax_anim 2, 0, 190, 6, 0, 6, 0,
ax_anim 2, 0, 190, -6, 0, -6, 0,
ax_anim 2, 0, 190, 0, 0, 0, 0,
ax_anim_terminator
sHoppipAnims_10_6:
ax_anim 2, 0, 191, 0, 0, 0, 0,
ax_anim 2, 0, 191, 6, -6, 6, -6,
ax_anim 2, 0, 191, -6, 6, -6, 6,
ax_anim 2, 0, 191, 10, -10, 10, -10,
ax_anim 2, 0, 191, -10, 10, -10, 10,
ax_anim 2, 0, 191, 12, -12, 12, -12,
ax_anim 3, 0, 191, -12, 12, -12, 12,
ax_anim 3, 0, 191, 13, -13, 13, -13,
ax_anim 3, 0, 191, -13, 13, -13, 13,
ax_anim 2, 0, 191, 12, -12, 12, -12,
ax_anim 3, 0, 191, -12, 12, -12, 12,
ax_anim 2, 0, 191, 10, -10, 10, -10,
ax_anim 2, 0, 191, -10, 10, -10, 10,
ax_anim 2, 0, 191, 6, -6, 6, -6,
ax_anim 2, 0, 191, -6, 6, -6, 6,
ax_anim 2, 0, 191, 0, 0, 0, 0,
ax_anim_terminator
sHoppipAnims_10_7:
ax_anim 2, 0, 192, 0, 0, 0, 0,
ax_anim 2, 0, 192, 0, -6, 0, -6,
ax_anim 2, 0, 192, 0, 6, 0, 6,
ax_anim 2, 0, 192, 0, -10, 0, -10,
ax_anim 2, 0, 192, 0, 10, 0, 10,
ax_anim 2, 0, 192, 0, -12, 0, -12,
ax_anim 3, 0, 192, 0, 12, 0, 12,
ax_anim 3, 0, 192, 0, -13, 0, -13,
ax_anim 3, 0, 192, 0, 13, 0, 13,
ax_anim 2, 0, 192, 0, -12, 0, -12,
ax_anim 3, 0, 192, 0, 12, 0, 12,
ax_anim 2, 0, 192, 0, -10, 0, -10,
ax_anim 2, 0, 192, 0, 10, 0, 10,
ax_anim 2, 0, 192, 0, -6, 0, -6,
ax_anim 2, 0, 192, 0, 6, 0, 6,
ax_anim 2, 0, 192, 0, 0, 0, 0,
ax_anim_terminator
sHoppipAnims_10_8:
ax_anim 2, 0, 193, 0, 0, 0, 0,
ax_anim 2, 0, 193, -6, -6, -6, -6,
ax_anim 2, 0, 193, 6, 6, 6, 6,
ax_anim 2, 0, 193, -10, -10, -10, -10,
ax_anim 2, 0, 193, 10, 10, 10, 10,
ax_anim 2, 0, 193, -12, -12, -12, -12,
ax_anim 3, 0, 193, 12, 12, 12, 12,
ax_anim 3, 0, 193, -13, -13, -13, -13,
ax_anim 3, 0, 193, 13, 13, 13, 13,
ax_anim 2, 0, 193, -12, -12, -12, -12,
ax_anim 3, 0, 193, 12, 12, 12, 12,
ax_anim 2, 0, 193, -10, -10, -10, -10,
ax_anim 2, 0, 193, 10, 10, 10, 10,
ax_anim 2, 0, 193, -6, -6, -6, -6,
ax_anim 2, 0, 193, 6, 6, 6, 6,
ax_anim 2, 0, 193, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sHoppipAnims_11_1:
ax_anim 2, 0, 194, 0, 0, 0, 0,
ax_anim 1, 0, 195, 0, -10, 0, 0,
ax_anim 2, 0, 195, 0, -16, 0, 0,
ax_anim 3, 0, 195, 0, -20, 0, 0,
ax_anim 4, 0, 195, 0, -21, 0, 0,
ax_anim 4, 0, 194, 0, -23, 0, 0,
ax_anim 3, 0, 196, 0, -22, 0, 0,
ax_anim 2, 0, 196, 0, -18, 0, 0,
ax_anim 1, 0, 196, 0, -12, 0, 0,
ax_anim 2, 2, 194, 0, 3, 0, 0,
ax_anim_terminator
sHoppipAnims_11_2:
ax_anim 2, 0, 197, 0, 0, 0, 0,
ax_anim 1, 0, 198, 0, -10, 0, 0,
ax_anim 2, 0, 198, 0, -16, 0, 0,
ax_anim 3, 0, 198, 0, -20, 0, 0,
ax_anim 4, 0, 198, 0, -21, 0, 0,
ax_anim 4, 0, 197, 0, -23, 0, 0,
ax_anim 3, 0, 199, 0, -22, 0, 0,
ax_anim 2, 0, 199, 0, -18, 0, 0,
ax_anim 1, 0, 199, 0, -12, 0, 0,
ax_anim 2, 2, 197, 0, 3, 0, 0,
ax_anim_terminator
sHoppipAnims_11_3:
ax_anim 2, 0, 200, 0, 0, 0, 0,
ax_anim 1, 0, 201, 0, -10, 0, 0,
ax_anim 2, 0, 201, 0, -16, 0, 0,
ax_anim 3, 0, 201, 0, -20, 0, 0,
ax_anim 4, 0, 201, 0, -21, 0, 0,
ax_anim 4, 0, 200, 0, -23, 0, 0,
ax_anim 3, 0, 202, 0, -22, 0, 0,
ax_anim 2, 0, 202, 0, -18, 0, 0,
ax_anim 1, 0, 202, 0, -12, 0, 0,
ax_anim 2, 2, 200, 0, 4, 0, 0,
ax_anim_terminator
sHoppipAnims_11_4:
ax_anim 2, 0, 203, 0, 0, 0, 0,
ax_anim 1, 0, 204, 0, -10, 0, 0,
ax_anim 2, 0, 204, 0, -16, 0, 0,
ax_anim 3, 0, 204, 0, -20, 0, 0,
ax_anim 4, 0, 204, 0, -21, 0, 0,
ax_anim 4, 0, 203, 0, -22, 0, 0,
ax_anim 3, 0, 205, 0, -21, 0, 0,
ax_anim 2, 0, 205, 0, -17, 0, 0,
ax_anim 1, 0, 205, 0, -11, 0, 0,
ax_anim 2, 2, 203, 0, 4, 0, 0,
ax_anim_terminator
sHoppipAnims_11_5:
ax_anim 2, 0, 206, 0, 0, 0, 0,
ax_anim 1, 0, 207, 0, -10, 0, 0,
ax_anim 2, 0, 207, 0, -16, 0, 0,
ax_anim 3, 0, 207, 0, -20, 0, 0,
ax_anim 4, 0, 207, 0, -21, 0, 0,
ax_anim 4, 0, 206, 0, -23, 0, 0,
ax_anim 3, 0, 208, 0, -22, 0, 0,
ax_anim 2, 0, 208, 0, -18, 0, 0,
ax_anim 1, 0, 208, 0, -12, 0, 0,
ax_anim 2, 2, 206, 0, 4, 0, 0,
ax_anim_terminator
sHoppipAnims_11_6:
ax_anim 2, 0, 209, 0, 0, 0, 0,
ax_anim 1, 0, 210, 0, -10, 0, 0,
ax_anim 2, 0, 210, 0, -16, 0, 0,
ax_anim 3, 0, 210, 0, -20, 0, 0,
ax_anim 4, 0, 210, 0, -21, 0, 0,
ax_anim 4, 0, 209, 0, -22, 0, 0,
ax_anim 3, 0, 211, 0, -21, 0, 0,
ax_anim 2, 0, 211, 0, -17, 0, 0,
ax_anim 1, 0, 211, 0, -11, 0, 0,
ax_anim 2, 2, 209, 0, 4, 0, 0,
ax_anim_terminator
sHoppipAnims_11_7:
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 1, 0, 213, 0, -10, 0, 0,
ax_anim 2, 0, 213, 0, -16, 0, 0,
ax_anim 3, 0, 213, 0, -20, 0, 0,
ax_anim 4, 0, 213, 0, -21, 0, 0,
ax_anim 4, 0, 212, 0, -23, 0, 0,
ax_anim 3, 0, 214, 0, -22, 0, 0,
ax_anim 2, 0, 214, 0, -18, 0, 0,
ax_anim 1, 0, 214, 0, -12, 0, 0,
ax_anim 2, 2, 212, 0, 4, 0, 0,
ax_anim_terminator
sHoppipAnims_11_8:
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 1, 0, 216, 0, -10, 0, 0,
ax_anim 2, 0, 216, 0, -16, 0, 0,
ax_anim 3, 0, 216, 0, -20, 0, 0,
ax_anim 4, 0, 216, 0, -21, 0, 0,
ax_anim 4, 0, 215, 0, -23, 0, 0,
ax_anim 3, 0, 217, 0, -22, 0, 0,
ax_anim 2, 0, 217, 0, -18, 0, 0,
ax_anim 1, 0, 217, 0, -12, 0, 0,
ax_anim 2, 2, 215, 0, 3, 0, 0,
ax_anim_terminator
.align 2
sHoppipAnims_12_1:
ax_anim 2, 0, 218, 1, 0, 1, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 218, 1, 0, 1, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 218, 1, 0, 1, 0,
ax_anim 2, 2, 218, 0, 0, 0, 0,
ax_anim 2, 0, 218, 1, 0, 1, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 218, 1, 0, 1, 0,
ax_anim 2, 1, 218, 0, 0, 0, 0,
ax_anim_terminator
sHoppipAnims_12_2:
ax_anim 2, 0, 225, 1, -1, 1, -1,
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 2, 0, 225, 1, -1, 1, -1,
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 2, 0, 225, 1, -1, 1, -1,
ax_anim 2, 2, 225, 0, 0, 0, 0,
ax_anim 2, 0, 225, 1, -1, 1, -1,
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 2, 0, 225, 1, -1, 1, -1,
ax_anim 2, 1, 225, 0, 0, 0, 0,
ax_anim_terminator
sHoppipAnims_12_3:
ax_anim 2, 0, 224, 0, -1, 0, -1,
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 2, 0, 224, 0, -1, 0, -1,
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 2, 0, 224, 0, -1, 0, -1,
ax_anim 2, 2, 224, 0, 0, 0, 0,
ax_anim 2, 0, 224, 0, -1, 0, -1,
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 2, 0, 224, 0, -1, 0, -1,
ax_anim 2, 1, 224, 0, 0, 0, 0,
ax_anim_terminator
sHoppipAnims_12_4:
ax_anim 2, 0, 223, -1, -1, -1, -1,
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 2, 0, 223, -1, -1, -1, -1,
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 2, 0, 223, -1, -1, -1, -1,
ax_anim 2, 2, 223, 0, 0, 0, 0,
ax_anim 2, 0, 223, -1, -1, -1, -1,
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 2, 0, 223, -1, -1, -1, -1,
ax_anim 2, 1, 223, 0, 0, 0, 0,
ax_anim_terminator
sHoppipAnims_12_5:
ax_anim 2, 0, 222, 1, 0, 1, 0,
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 0, 222, 1, 0, 1, 0,
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 0, 222, 1, 0, 1, 0,
ax_anim 2, 2, 222, 0, 0, 0, 0,
ax_anim 2, 0, 222, 1, 0, 1, 0,
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 0, 222, 1, 0, 1, 0,
ax_anim 2, 1, 222, 0, 0, 0, 0,
ax_anim_terminator
sHoppipAnims_12_6:
ax_anim 2, 0, 221, 1, -1, 1, -1,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 221, 1, -1, 1, -1,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 221, 1, -1, 1, -1,
ax_anim 2, 2, 221, 0, 0, 0, 0,
ax_anim 2, 0, 221, 1, -1, 1, -1,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 221, 1, -1, 1, -1,
ax_anim 2, 1, 221, 0, 0, 0, 0,
ax_anim_terminator
sHoppipAnims_12_7:
ax_anim 2, 0, 220, 0, -1, 0, -1,
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, -1, 0, -1,
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, -1, 0, -1,
ax_anim 2, 2, 220, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, -1, 0, -1,
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, -1, 0, -1,
ax_anim 2, 1, 220, 0, 0, 0, 0,
ax_anim_terminator
sHoppipAnims_12_8:
ax_anim 2, 0, 219, -1, -1, -1, -1,
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 0, 219, -1, -1, -1, -1,
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 0, 219, -1, -1, -1, -1,
ax_anim 2, 2, 219, 0, 0, 0, 0,
ax_anim 2, 0, 219, -1, -1, -1, -1,
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 0, 219, -1, -1, -1, -1,
ax_anim 2, 1, 219, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sHoppipAnims_13_1:
ax_anim 2, 0, 226, 0, 0, 0, 0,
ax_anim 2, 0, 227, 0, 0, 0, 0,
ax_anim 2, 0, 228, 0, 0, 0, 0,
ax_anim 2, 0, 229, 0, 0, 0, 0,
ax_anim 2, 0, 230, 0, 0, 0, 0,
ax_anim 2, 0, 231, 0, 0, 0, 0,
ax_anim 2, 0, 232, 0, 0, 0, 0,
ax_anim 2, 0, 233, 0, 0, 0, 0,
ax_anim 2, 2, 226, 0, 0, 0, 0,
ax_anim_terminator
sHoppipAnims_13_2:
ax_anim 2, 0, 233, 0, 0, 0, 0,
ax_anim 2, 0, 226, 0, 0, 0, 0,
ax_anim 2, 0, 227, 0, 0, 0, 0,
ax_anim 2, 0, 228, 0, 0, 0, 0,
ax_anim 2, 0, 229, 0, 0, 0, 0,
ax_anim 2, 0, 230, 0, 0, 0, 0,
ax_anim 2, 0, 231, 0, 0, 0, 0,
ax_anim 2, 0, 232, 0, 0, 0, 0,
ax_anim 2, 2, 233, 0, 0, 0, 0,
ax_anim_terminator
sHoppipAnims_13_3:
ax_anim 2, 0, 232, 0, 0, 0, 0,
ax_anim 2, 0, 233, 0, 0, 0, 0,
ax_anim 2, 0, 226, 0, 0, 0, 0,
ax_anim 2, 0, 227, 0, 0, 0, 0,
ax_anim 2, 0, 228, 0, 0, 0, 0,
ax_anim 2, 0, 229, 0, 0, 0, 0,
ax_anim 2, 0, 230, 0, 0, 0, 0,
ax_anim 2, 0, 231, 0, 0, 0, 0,
ax_anim 2, 2, 232, 0, 0, 0, 0,
ax_anim_terminator
sHoppipAnims_13_4:
ax_anim 2, 0, 231, 0, 0, 0, 0,
ax_anim 2, 0, 232, 0, 0, 0, 0,
ax_anim 2, 0, 233, 0, 0, 0, 0,
ax_anim 2, 0, 226, 0, 0, 0, 0,
ax_anim 2, 0, 227, 0, 0, 0, 0,
ax_anim 2, 0, 228, 0, 0, 0, 0,
ax_anim 2, 0, 229, 0, 0, 0, 0,
ax_anim 2, 0, 230, 0, 0, 0, 0,
ax_anim 2, 2, 231, 0, 0, 0, 0,
ax_anim_terminator
sHoppipAnims_13_5:
ax_anim 2, 0, 230, 0, 0, 0, 0,
ax_anim 2, 0, 231, 0, 0, 0, 0,
ax_anim 2, 0, 232, 0, 0, 0, 0,
ax_anim 2, 0, 233, 0, 0, 0, 0,
ax_anim 2, 0, 226, 0, 0, 0, 0,
ax_anim 2, 0, 227, 0, 0, 0, 0,
ax_anim 2, 0, 228, 0, 0, 0, 0,
ax_anim 2, 0, 229, 0, 0, 0, 0,
ax_anim 2, 2, 230, 0, 0, 0, 0,
ax_anim_terminator
sHoppipAnims_13_6:
ax_anim 2, 0, 229, 0, 0, 0, 0,
ax_anim 2, 0, 230, 0, 0, 0, 0,
ax_anim 2, 0, 231, 0, 0, 0, 0,
ax_anim 2, 0, 232, 0, 0, 0, 0,
ax_anim 2, 0, 233, 0, 0, 0, 0,
ax_anim 2, 0, 226, 0, 0, 0, 0,
ax_anim 2, 0, 227, 0, 0, 0, 0,
ax_anim 2, 0, 228, 0, 0, 0, 0,
ax_anim 2, 2, 229, 0, 0, 0, 0,
ax_anim_terminator
sHoppipAnims_13_7:
ax_anim 2, 0, 228, 0, 0, 0, 0,
ax_anim 2, 0, 229, 0, 0, 0, 0,
ax_anim 2, 0, 230, 0, 0, 0, 0,
ax_anim 2, 0, 231, 0, 0, 0, 0,
ax_anim 2, 0, 232, 0, 0, 0, 0,
ax_anim 2, 0, 233, 0, 0, 0, 0,
ax_anim 2, 0, 226, 0, 0, 0, 0,
ax_anim 2, 0, 227, 0, 0, 0, 0,
ax_anim 2, 2, 228, 0, 0, 0, 0,
ax_anim_terminator
sHoppipAnims_13_8:
ax_anim 2, 0, 227, 0, 0, 0, 0,
ax_anim 2, 0, 228, 0, 0, 0, 0,
ax_anim 2, 0, 229, 0, 0, 0, 0,
ax_anim 2, 0, 230, 0, 0, 0, 0,
ax_anim 2, 0, 231, 0, 0, 0, 0,
ax_anim 2, 0, 232, 0, 0, 0, 0,
ax_anim 2, 0, 233, 0, 0, 0, 0,
ax_anim 2, 0, 226, 0, 0, 0, 0,
ax_anim 2, 2, 227, 0, 0, 0, 0,
ax_anim_terminator
sHoppipGfx1:
.incbin "baserom.gba", 0xD13F74, 0x100
sHoppipSprites1:
ax_sprite sHoppipGfx1, 0x100
ax_sprite_terminator
sHoppipGfx2:
.incbin "baserom.gba", 0xD14084, 0x100
sHoppipSprites2:
ax_sprite sHoppipGfx2, 0x100
ax_sprite_terminator
sHoppipGfx3:
.incbin "baserom.gba", 0xD14194, 0x100
sHoppipSprites3:
ax_sprite sHoppipGfx3, 0x100
ax_sprite_terminator
sHoppipGfx4:
.incbin "baserom.gba", 0xD142A4, 0x80
sHoppipSprites4:
ax_sprite sHoppipGfx4, 0x80
ax_sprite_terminator
sHoppipGfx5:
.incbin "baserom.gba", 0xD14334, 0x100
sHoppipSprites5:
ax_sprite sHoppipGfx5, 0x100
ax_sprite_terminator
sHoppipGfx6:
.incbin "baserom.gba", 0xD14444, 0x100
sHoppipSprites6:
ax_sprite sHoppipGfx6, 0x100
ax_sprite_terminator
sHoppipGfx7:
.incbin "baserom.gba", 0xD14554, 0x100
sHoppipSprites7:
ax_sprite sHoppipGfx7, 0x100
ax_sprite_terminator
sHoppipGfx8:
.incbin "baserom.gba", 0xD14664, 0x100
sHoppipSprites8:
ax_sprite sHoppipGfx8, 0x100
ax_sprite_terminator
sHoppipGfx9:
.incbin "baserom.gba", 0xD14774, 0x100
sHoppipSprites9:
ax_sprite sHoppipGfx9, 0x100
ax_sprite_terminator
sHoppipGfx10:
.incbin "baserom.gba", 0xD14884, 0x100
sHoppipSprites10:
ax_sprite sHoppipGfx10, 0x100
ax_sprite_terminator
sHoppipGfx11:
.incbin "baserom.gba", 0xD14994, 0x60
sHoppipGfx11_1:
.incbin "baserom.gba", 0xD149F4, 0x60
sHoppipGfx11_2:
.incbin "baserom.gba", 0xD14A54, 0x60
sHoppipSprites11:
ax_sprite sHoppipGfx11, 0x60
ax_sprite 0, 0x20
ax_sprite sHoppipGfx11_1, 0x60
ax_sprite 0, 0x20
ax_sprite sHoppipGfx11_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sHoppipGfx12:
.incbin "baserom.gba", 0xD14AEC, 0x60
sHoppipGfx12_1:
.incbin "baserom.gba", 0xD14B4C, 0x60
sHoppipGfx12_2:
.incbin "baserom.gba", 0xD14BAC, 0x60
sHoppipSprites12:
ax_sprite sHoppipGfx12, 0x60
ax_sprite 0, 0x20
ax_sprite sHoppipGfx12_1, 0x60
ax_sprite 0, 0x20
ax_sprite sHoppipGfx12_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sHoppipGfx13:
.incbin "baserom.gba", 0xD14C44, 0x100
sHoppipGfx13_1:
.incbin "baserom.gba", 0xD14D44, 0x40
sHoppipSprites13:
ax_sprite sHoppipGfx13, 0x100
ax_sprite 0, 0x20
ax_sprite sHoppipGfx13_1, 0x40
ax_sprite 0, 0xa0
ax_sprite_terminator
sHoppipGfx14:
.incbin "baserom.gba", 0xD14DAC, 0x60
sHoppipGfx14_1:
.incbin "baserom.gba", 0xD14E0C, 0x60
sHoppipGfx14_2:
.incbin "baserom.gba", 0xD14E6C, 0x60
sHoppipSprites14:
ax_sprite sHoppipGfx14, 0x60
ax_sprite 0, 0x20
ax_sprite sHoppipGfx14_1, 0x60
ax_sprite 0, 0x20
ax_sprite sHoppipGfx14_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sHoppipGfx15:
.incbin "baserom.gba", 0xD14F04, 0x60
sHoppipGfx15_1:
.incbin "baserom.gba", 0xD14F64, 0x60
sHoppipGfx15_2:
.incbin "baserom.gba", 0xD14FC4, 0x60
sHoppipSprites15:
ax_sprite sHoppipGfx15, 0x60
ax_sprite 0, 0x20
ax_sprite sHoppipGfx15_1, 0x60
ax_sprite 0, 0x20
ax_sprite sHoppipGfx15_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sHoppipGfx16:
.incbin "baserom.gba", 0xD1505C, 0x40
sHoppipGfx16_1:
.incbin "baserom.gba", 0xD1509C, 0x60
sHoppipGfx16_2:
.incbin "baserom.gba", 0xD150FC, 0x60
sHoppipSprites16:
ax_sprite sHoppipGfx16, 0x40
ax_sprite 0, 0x40
ax_sprite sHoppipGfx16_1, 0x60
ax_sprite 0, 0x20
ax_sprite sHoppipGfx16_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sHoppipGfx17:
.incbin "baserom.gba", 0xD15194, 0x40
sHoppipGfx17_1:
.incbin "baserom.gba", 0xD151D4, 0x60
sHoppipGfx17_2:
.incbin "baserom.gba", 0xD15234, 0x60
sHoppipGfx17_3:
.incbin "baserom.gba", 0xD15294, 0x60
sHoppipSprites17:
ax_sprite 0, 0x20
ax_sprite sHoppipGfx17, 0x40
ax_sprite 0, 0x20
ax_sprite sHoppipGfx17_1, 0x60
ax_sprite 0, 0x20
ax_sprite sHoppipGfx17_2, 0x60
ax_sprite 0, 0x20
ax_sprite sHoppipGfx17_3, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sHoppipGfx18:
.incbin "baserom.gba", 0xD15344, 0x40
sHoppipGfx18_1:
.incbin "baserom.gba", 0xD15384, 0x60
sHoppipGfx18_2:
.incbin "baserom.gba", 0xD153E4, 0x60
sHoppipSprites18:
ax_sprite 0, 0x20
ax_sprite sHoppipGfx18, 0x40
ax_sprite 0, 0x20
ax_sprite sHoppipGfx18_1, 0x60
ax_sprite 0, 0x20
ax_sprite sHoppipGfx18_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sHoppipGfx19:
.incbin "baserom.gba", 0xD15484, 0x40
sHoppipGfx19_1:
.incbin "baserom.gba", 0xD154C4, 0x60
sHoppipGfx19_2:
.incbin "baserom.gba", 0xD15524, 0x60
sHoppipSprites19:
ax_sprite 0, 0x20
ax_sprite sHoppipGfx19, 0x40
ax_sprite 0, 0x20
ax_sprite sHoppipGfx19_1, 0x60
ax_sprite 0, 0x20
ax_sprite sHoppipGfx19_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sHoppipGfx20:
.incbin "baserom.gba", 0xD155C4, 0x60
sHoppipGfx20_1:
.incbin "baserom.gba", 0xD15624, 0x60
sHoppipGfx20_2:
.incbin "baserom.gba", 0xD15684, 0x60
sHoppipGfx20_3:
.incbin "baserom.gba", 0xD156E4, 0x20
sHoppipSprites20:
ax_sprite sHoppipGfx20, 0x60
ax_sprite 0, 0x20
ax_sprite sHoppipGfx20_1, 0x60
ax_sprite 0, 0x20
ax_sprite sHoppipGfx20_2, 0x60
ax_sprite 0, 0x40
ax_sprite sHoppipGfx20_3, 0x20
ax_sprite 0, 0x40
ax_sprite_terminator
sHoppipGfx21:
.incbin "baserom.gba", 0xD1574C, 0x60
sHoppipGfx21_1:
.incbin "baserom.gba", 0xD157AC, 0x60
sHoppipGfx21_2:
.incbin "baserom.gba", 0xD1580C, 0x60
sHoppipGfx21_3:
.incbin "baserom.gba", 0xD1586C, 0x60
sHoppipSprites21:
ax_sprite sHoppipGfx21, 0x60
ax_sprite 0, 0x20
ax_sprite sHoppipGfx21_1, 0x60
ax_sprite 0, 0x20
ax_sprite sHoppipGfx21_2, 0x60
ax_sprite 0, 0x20
ax_sprite sHoppipGfx21_3, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sHoppipGfx22:
.incbin "baserom.gba", 0xD15914, 0x40
sHoppipGfx22_1:
.incbin "baserom.gba", 0xD15954, 0x60
sHoppipGfx22_2:
.incbin "baserom.gba", 0xD159B4, 0x60
sHoppipGfx22_3:
.incbin "baserom.gba", 0xD15A14, 0x20
sHoppipSprites22:
ax_sprite 0, 0x20
ax_sprite sHoppipGfx22, 0x40
ax_sprite 0, 0x20
ax_sprite sHoppipGfx22_1, 0x60
ax_sprite 0, 0x20
ax_sprite sHoppipGfx22_2, 0x60
ax_sprite 0, 0x40
ax_sprite sHoppipGfx22_3, 0x20
ax_sprite 0, 0x40
ax_sprite_terminator
sHoppipGfx23:
.incbin "baserom.gba", 0xD15A84, 0x60
sHoppipGfx23_1:
.incbin "baserom.gba", 0xD15AE4, 0x60
sHoppipGfx23_2:
.incbin "baserom.gba", 0xD15B44, 0x60
sHoppipSprites23:
ax_sprite sHoppipGfx23, 0x60
ax_sprite 0, 0x20
ax_sprite sHoppipGfx23_1, 0x60
ax_sprite 0, 0x20
ax_sprite sHoppipGfx23_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sHoppipGfx24:
.incbin "baserom.gba", 0xD15BDC, 0x60
sHoppipGfx24_1:
.incbin "baserom.gba", 0xD15C3C, 0x60
sHoppipGfx24_2:
.incbin "baserom.gba", 0xD15C9C, 0x60
sHoppipSprites24:
ax_sprite sHoppipGfx24, 0x60
ax_sprite 0, 0x20
ax_sprite sHoppipGfx24_1, 0x60
ax_sprite 0, 0x20
ax_sprite sHoppipGfx24_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sHoppipGfx25:
.incbin "baserom.gba", 0xD15D34, 0x100
sHoppipGfx25_1:
.incbin "baserom.gba", 0xD15E34, 0x40
sHoppipSprites25:
ax_sprite sHoppipGfx25, 0x100
ax_sprite 0, 0x20
ax_sprite sHoppipGfx25_1, 0x40
ax_sprite 0, 0xa0
ax_sprite_terminator
sHoppipGfx26:
.incbin "baserom.gba", 0xD15E9C, 0x160
sHoppipGfx26_1:
.incbin "baserom.gba", 0xD15FFC, 0x20
sHoppipSprites26:
ax_sprite sHoppipGfx26, 0x160
ax_sprite 0, 0x40
ax_sprite sHoppipGfx26_1, 0x20
ax_sprite 0, 0x40
ax_sprite_terminator
sHoppipGfx27:
.incbin "baserom.gba", 0xD16044, 0x60
sHoppipGfx27_1:
.incbin "baserom.gba", 0xD160A4, 0xE0
sHoppipSprites27:
ax_sprite sHoppipGfx27, 0x60
ax_sprite 0, 0x20
ax_sprite sHoppipGfx27_1, 0xe0
ax_sprite 0, 0xa0
ax_sprite_terminator
sHoppipGfx28:
.incbin "baserom.gba", 0xD161AC, 0x40
sHoppipGfx28_1:
.incbin "baserom.gba", 0xD161EC, 0x60
sHoppipGfx28_2:
.incbin "baserom.gba", 0xD1624C, 0x60
sHoppipGfx28_3:
.incbin "baserom.gba", 0xD162AC, 0x40
sHoppipSprites28:
ax_sprite 0, 0x20
ax_sprite sHoppipGfx28, 0x40
ax_sprite 0, 0x20
ax_sprite sHoppipGfx28_1, 0x60
ax_sprite 0, 0x20
ax_sprite sHoppipGfx28_2, 0x60
ax_sprite 0, 0x40
ax_sprite sHoppipGfx28_3, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sHoppipGfx29:
.incbin "baserom.gba", 0xD1633C, 0x40
sHoppipGfx29_1:
.incbin "baserom.gba", 0xD1637C, 0x60
sHoppipGfx29_2:
.incbin "baserom.gba", 0xD163DC, 0x60
sHoppipGfx29_3:
.incbin "baserom.gba", 0xD1643C, 0x40
sHoppipSprites29:
ax_sprite 0, 0x20
ax_sprite sHoppipGfx29, 0x40
ax_sprite 0, 0x20
ax_sprite sHoppipGfx29_1, 0x60
ax_sprite 0, 0x20
ax_sprite sHoppipGfx29_2, 0x60
ax_sprite 0, 0x40
ax_sprite sHoppipGfx29_3, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sHoppipGfx30:
.incbin "baserom.gba", 0xD164CC, 0x40
sHoppipGfx30_1:
.incbin "baserom.gba", 0xD1650C, 0xE0
sHoppipGfx30_2:
.incbin "baserom.gba", 0xD165EC, 0x20
sHoppipSprites30:
ax_sprite 0, 0x20
ax_sprite sHoppipGfx30, 0x40
ax_sprite 0, 0x20
ax_sprite sHoppipGfx30_1, 0xe0
ax_sprite 0, 0x40
ax_sprite sHoppipGfx30_2, 0x20
ax_sprite 0, 0x40
ax_sprite_terminator
sHoppipGfx31:
.incbin "baserom.gba", 0xD1664C, 0x200
sHoppipSprites31:
ax_sprite sHoppipGfx31, 0x200
ax_sprite_terminator
sHoppipGfx32:
.incbin "baserom.gba", 0xD1685C, 0x200
sHoppipSprites32:
ax_sprite sHoppipGfx32, 0x200
ax_sprite_terminator
sHoppipGfx33:
.incbin "baserom.gba", 0xD16A6C, 0x200
sHoppipSprites33:
ax_sprite sHoppipGfx33, 0x200
ax_sprite_terminator
sHoppipGfx34:
.incbin "baserom.gba", 0xD16C7C, 0x200
sHoppipSprites34:
ax_sprite sHoppipGfx34, 0x200
ax_sprite_terminator
sHoppipGfx35:
.incbin "baserom.gba", 0xD16E8C, 0x200
sHoppipSprites35:
ax_sprite sHoppipGfx35, 0x200
ax_sprite_terminator
sHoppipGfx36:
.incbin "baserom.gba", 0xD1709C, 0x200
sHoppipSprites36:
ax_sprite sHoppipGfx36, 0x200
ax_sprite_terminator
sHoppipGfx37:
.incbin "baserom.gba", 0xD172AC, 0x200
sHoppipSprites37:
ax_sprite sHoppipGfx37, 0x200
ax_sprite_terminator
sAxPosesHoppip:
.4byte sHoppipPose1
.4byte sHoppipPose2
.4byte sHoppipPose3
.4byte sHoppipPose4
.4byte sHoppipPose5
.4byte sHoppipPose6
.4byte sHoppipPose7
.4byte sHoppipPose8
.4byte sHoppipPose9
.4byte sHoppipPose10
.4byte sHoppipPose11
.4byte sHoppipPose12
.4byte sHoppipPose13
.4byte sHoppipPose14
.4byte sHoppipPose15
.4byte sHoppipPose16
.4byte sHoppipPose17
.4byte sHoppipPose18
.4byte sHoppipPose19
.4byte sHoppipPose20
.4byte sHoppipPose21
.4byte sHoppipPose22
.4byte sHoppipPose23
.4byte sHoppipPose24
.4byte sHoppipPose25
.4byte sHoppipPose26
.4byte sHoppipPose27
.4byte sHoppipPose28
.4byte sHoppipPose29
.4byte sHoppipPose30
.4byte sHoppipPose31
.4byte sHoppipPose32
.4byte sHoppipPose33
.4byte sHoppipPose34
.4byte sHoppipPose35
.4byte sHoppipPose36
.4byte sHoppipPose37
.4byte sHoppipPose38
.4byte sHoppipPose39
.4byte sHoppipPose40
.4byte sHoppipPose41
.4byte sHoppipPose42
.4byte sHoppipPose43
.4byte sHoppipPose44
.4byte sHoppipPose45
.4byte sHoppipPose46
.4byte sHoppipPose47
.4byte sHoppipPose48
.4byte sHoppipPose49
.4byte sHoppipPose50
.4byte sHoppipPose51
.4byte sHoppipPose52
.4byte sHoppipPose53
.4byte sHoppipPose54
.4byte sHoppipPose55
.4byte sHoppipPose56
.4byte sHoppipPose57
.4byte sHoppipPose58
.4byte sHoppipPose59
.4byte sHoppipPose60
.4byte sHoppipPose61
.4byte sHoppipPose62
.4byte sHoppipPose63
.4byte sHoppipPose64
.4byte sHoppipPose65
.4byte sHoppipPose66
.4byte sHoppipPose67
.4byte sHoppipPose68
.4byte sHoppipPose69
.4byte sHoppipPose70
.4byte sHoppipPose71
.4byte sHoppipPose72
.4byte sHoppipPose73
.4byte sHoppipPose74
.4byte sHoppipPose75
.4byte sHoppipPose76
.4byte sHoppipPose77
.4byte sHoppipPose78
.4byte sHoppipPose79
.4byte sHoppipPose80
.4byte sHoppipPose81
.4byte sHoppipPose82
.4byte sHoppipPose83
.4byte sHoppipPose84
.4byte sHoppipPose85
.4byte sHoppipPose86
.4byte sHoppipPose87
.4byte sHoppipPose88
.4byte sHoppipPose89
.4byte sHoppipPose90
.4byte sHoppipPose91
.4byte sHoppipPose92
.4byte sHoppipPose93
.4byte sHoppipPose94
.4byte sHoppipPose95
.4byte sHoppipPose96
.4byte sHoppipPose97
.4byte sHoppipPose98
.4byte sHoppipPose99
.4byte sHoppipPose100
.4byte sHoppipPose101
.4byte sHoppipPose102
.4byte sHoppipPose103
.4byte sHoppipPose104
.4byte sHoppipPose105
.4byte sHoppipPose106
.4byte sHoppipPose107
.4byte sHoppipPose108
.4byte sHoppipPose109
.4byte sHoppipPose110
.4byte sHoppipPose111
.4byte sHoppipPose112
.4byte sHoppipPose113
.4byte sHoppipPose114
.4byte sHoppipPose115
.4byte sHoppipPose116
.4byte sHoppipPose117
.4byte sHoppipPose118
.4byte sHoppipPose119
.4byte sHoppipPose120
.4byte sHoppipPose121
.4byte sHoppipPose122
.4byte sHoppipPose123
.4byte sHoppipPose124
.4byte sHoppipPose125
.4byte sHoppipPose126
.4byte sHoppipPose127
.4byte sHoppipPose128
.4byte sHoppipPose129
.4byte sHoppipPose130
.4byte sHoppipPose131
.4byte sHoppipPose132
.4byte sHoppipPose133
.4byte sHoppipPose134
.4byte sHoppipPose135
.4byte sHoppipPose136
.4byte sHoppipPose137
.4byte sHoppipPose138
.4byte sHoppipPose139
.4byte sHoppipPose140
.4byte sHoppipPose141
.4byte sHoppipPose142
.4byte sHoppipPose143
.4byte sHoppipPose144
.4byte sHoppipPose145
.4byte sHoppipPose146
.4byte sHoppipPose147
.4byte sHoppipPose148
.4byte sHoppipPose149
.4byte sHoppipPose150
.4byte sHoppipPose151
.4byte sHoppipPose152
.4byte sHoppipPose153
.4byte sHoppipPose154
.4byte sHoppipPose155
.4byte sHoppipPose156
.4byte sHoppipPose157
.4byte sHoppipPose158
.4byte sHoppipPose159
.4byte sHoppipPose160
.4byte sHoppipPose161
.4byte sHoppipPose162
.4byte sHoppipPose163
.4byte sHoppipPose164
.4byte sHoppipPose165
.4byte sHoppipPose166
.4byte sHoppipPose167
.4byte sHoppipPose168
.4byte sHoppipPose169
.4byte sHoppipPose170
.4byte sHoppipPose171
.4byte sHoppipPose172
.4byte sHoppipPose173
.4byte sHoppipPose174
.4byte sHoppipPose175
.4byte sHoppipPose176
.4byte sHoppipPose177
.4byte sHoppipPose178
.4byte sHoppipPose179
.4byte sHoppipPose180
.4byte sHoppipPose181
.4byte sHoppipPose182
.4byte sHoppipPose183
.4byte sHoppipPose184
.4byte sHoppipPose185
.4byte sHoppipPose186
.4byte sHoppipPose187
.4byte sHoppipPose188
.4byte sHoppipPose189
.4byte sHoppipPose190
.4byte sHoppipPose191
.4byte sHoppipPose192
.4byte sHoppipPose193
.4byte sHoppipPose194
.4byte sHoppipPose195
.4byte sHoppipPose196
.4byte sHoppipPose197
.4byte sHoppipPose198
.4byte sHoppipPose199
.4byte sHoppipPose200
.4byte sHoppipPose201
.4byte sHoppipPose202
.4byte sHoppipPose203
.4byte sHoppipPose204
.4byte sHoppipPose205
.4byte sHoppipPose206
.4byte sHoppipPose207
.4byte sHoppipPose208
.4byte sHoppipPose209
.4byte sHoppipPose210
.4byte sHoppipPose211
.4byte sHoppipPose212
.4byte sHoppipPose213
.4byte sHoppipPose214
.4byte sHoppipPose215
.4byte sHoppipPose216
.4byte sHoppipPose217
.4byte sHoppipPose218
.4byte sHoppipPose219
.4byte sHoppipPose220
.4byte sHoppipPose221
.4byte sHoppipPose222
.4byte sHoppipPose223
.4byte sHoppipPose224
.4byte sHoppipPose225
.4byte sHoppipPose226
.4byte sHoppipPose227
.4byte sHoppipPose228
.4byte sHoppipPose229
.4byte sHoppipPose230
.4byte sHoppipPose231
.4byte sHoppipPose232
.4byte sHoppipPose233
.4byte sHoppipPose234
sAxPositionsHoppip:
.2byte   -1,   -8, 	  -3,   -5, 	   2,   -5, 	   0,   -8
.2byte   -1,   -8, 	  -3,   -5, 	   2,   -5, 	   0,   -8
.2byte   -1,   -8, 	  -3,   -5, 	   2,   -5, 	   0,   -8
.2byte   -1,   -8, 	  -3,   -5, 	   2,   -5, 	   0,   -8
.2byte   -1,   -8, 	  -3,   -5, 	   2,   -5, 	   0,   -8
.2byte   -1,   -8, 	  -3,   -5, 	   2,   -5, 	   0,   -8
.2byte   -1,   -8, 	  -3,   -5, 	   2,   -5, 	   0,   -8
.2byte   -1,   -8, 	  -3,   -5, 	   2,   -5, 	   0,   -8
.2byte    2,   -9, 	   6,   -6, 	   1,   -4, 	   0,   -9
.2byte    2,   -9, 	   6,   -6, 	   1,   -4, 	   0,   -9
.2byte    2,   -9, 	   6,   -6, 	   1,   -4, 	   0,   -9
.2byte    2,   -9, 	   6,   -6, 	   1,   -4, 	   0,   -9
.2byte    2,   -9, 	   6,   -6, 	   1,   -4, 	   0,   -9
.2byte    2,   -9, 	   6,   -6, 	   1,   -4, 	   0,   -9
.2byte    2,   -9, 	   6,   -6, 	   1,   -4, 	   0,   -9
.2byte    2,   -9, 	   6,   -6, 	   1,   -4, 	   0,   -9
.2byte    6,  -10, 	   7,   -8, 	   5,   -5, 	   0,  -10
.2byte    6,  -10, 	   7,   -8, 	   5,   -5, 	   0,  -10
.2byte    6,  -10, 	   7,   -8, 	   5,   -5, 	   0,  -10
.2byte    6,  -10, 	   7,   -8, 	   5,   -5, 	   0,  -10
.2byte    6,  -10, 	   7,   -8, 	   5,   -5, 	   0,  -10
.2byte    6,  -10, 	   7,   -8, 	   5,   -5, 	   0,  -10
.2byte    6,  -10, 	   7,   -8, 	   5,   -5, 	   0,  -10
.2byte    6,  -10, 	   7,   -8, 	   5,   -5, 	   0,  -10
.2byte    3,  -12, 	  -1,   -9, 	   6,   -6, 	   0,  -10
.2byte    3,  -12, 	  -1,   -9, 	   6,   -6, 	   0,  -10
.2byte    3,  -12, 	  -1,   -9, 	   6,   -6, 	   0,  -10
.2byte    3,  -12, 	  -1,   -9, 	   6,   -6, 	   0,  -10
.2byte    3,  -12, 	  -1,   -9, 	   6,   -6, 	   0,  -10
.2byte    3,  -12, 	  -1,   -9, 	   6,   -6, 	   0,  -10
.2byte    3,  -12, 	  -1,   -9, 	   6,   -6, 	   0,  -10
.2byte    3,  -12, 	  -1,   -9, 	   6,   -6, 	   0,  -10
.2byte    0,   -9, 	   2,   -7, 	  -3,   -7, 	   0,  -10
.2byte    0,   -9, 	   2,   -7, 	  -3,   -7, 	   0,  -10
.2byte    0,   -9, 	   2,   -7, 	  -3,   -7, 	   0,  -10
.2byte    0,   -9, 	   2,   -7, 	  -3,   -7, 	   0,  -10
.2byte    0,   -9, 	   2,   -7, 	  -3,   -7, 	   0,  -10
.2byte    0,   -9, 	   2,   -7, 	  -3,   -7, 	   0,  -10
.2byte    0,   -9, 	   2,   -7, 	  -3,   -7, 	   0,  -10
.2byte    0,   -9, 	   2,   -7, 	  -3,   -7, 	   0,  -10
.2byte   -4,  -12, 	   0,   -9, 	  -7,   -6, 	  -1,  -10
.2byte   -4,  -12, 	   0,   -9, 	  -7,   -6, 	  -1,  -10
.2byte   -4,  -12, 	   0,   -9, 	  -7,   -6, 	  -1,  -10
.2byte   -4,  -12, 	   0,   -9, 	  -7,   -6, 	  -1,  -10
.2byte   -4,  -12, 	   0,   -9, 	  -7,   -6, 	  -1,  -10
.2byte   -4,  -12, 	   0,   -9, 	  -7,   -6, 	  -1,  -10
.2byte   -4,  -12, 	   0,   -9, 	  -7,   -6, 	  -1,  -10
.2byte   -4,  -12, 	   0,   -9, 	  -7,   -6, 	  -1,  -10
.2byte   -7,  -10, 	  -8,   -8, 	  -6,   -5, 	  -1,  -10
.2byte   -7,  -10, 	  -8,   -8, 	  -6,   -5, 	  -1,  -10
.2byte   -7,  -10, 	  -8,   -8, 	  -6,   -5, 	  -1,  -10
.2byte   -7,  -10, 	  -8,   -8, 	  -6,   -5, 	  -1,  -10
.2byte   -7,  -10, 	  -8,   -8, 	  -6,   -5, 	  -1,  -10
.2byte   -7,  -10, 	  -8,   -8, 	  -6,   -5, 	  -1,  -10
.2byte   -7,  -10, 	  -8,   -8, 	  -6,   -5, 	  -1,  -10
.2byte   -7,  -10, 	  -8,   -8, 	  -6,   -5, 	  -1,  -10
.2byte   -3,   -9, 	  -7,   -6, 	  -2,   -4, 	  -1,   -9
.2byte   -3,   -9, 	  -7,   -6, 	  -2,   -4, 	  -1,   -9
.2byte   -3,   -9, 	  -7,   -6, 	  -2,   -4, 	  -1,   -9
.2byte   -3,   -9, 	  -7,   -6, 	  -2,   -4, 	  -1,   -9
.2byte   -3,   -9, 	  -7,   -6, 	  -2,   -4, 	  -1,   -9
.2byte   -3,   -9, 	  -7,   -6, 	  -2,   -4, 	  -1,   -9
.2byte   -3,   -9, 	  -7,   -6, 	  -2,   -4, 	  -1,   -9
.2byte   -3,   -9, 	  -7,   -6, 	  -2,   -4, 	  -1,   -9
.2byte   -1,   -8, 	  -3,   -5, 	   2,   -5, 	   0,   -9
.2byte   -1,   -8, 	  -3,   -5, 	   2,   -5, 	  -1,   -9
.2byte   -1,   -8, 	  -3,   -5, 	   2,   -5, 	   0,   -9
.2byte    2,   -9, 	   6,   -6, 	   1,   -4, 	   0,   -9
.2byte    2,   -9, 	   6,   -6, 	   1,   -4, 	   0,   -9
.2byte    2,   -9, 	   6,   -6, 	   1,   -4, 	   0,   -9
.2byte    5,   -9, 	   7,   -8, 	   5,   -5, 	   0,  -10
.2byte    5,   -9, 	   7,   -8, 	   5,   -5, 	   0,  -10
.2byte    5,   -9, 	   7,   -8, 	   5,   -5, 	   0,  -10
.2byte    2,  -11, 	   0,   -9, 	   6,   -6, 	   0,  -10
.2byte    2,  -12, 	  -1,   -9, 	   6,   -6, 	  -1,  -10
.2byte    1,  -10, 	   0,   -9, 	   6,   -6, 	  -1,  -10
.2byte    0,  -10, 	   2,   -8, 	  -3,   -8, 	  -1,   -9
.2byte    0,  -10, 	   2,   -8, 	  -3,   -8, 	  -1,   -9
.2byte    0,  -10, 	   2,   -8, 	  -3,   -8, 	  -1,   -9
.2byte   -3,  -11, 	  -1,   -9, 	  -7,   -6, 	  -1,  -10
.2byte   -3,  -12, 	   0,   -9, 	  -7,   -6, 	   0,  -10
.2byte   -2,  -10, 	  -1,   -9, 	  -7,   -6, 	   0,  -10
.2byte   -6,   -9, 	  -8,   -8, 	  -6,   -5, 	  -1,  -10
.2byte   -6,   -9, 	  -8,   -8, 	  -6,   -5, 	  -1,  -10
.2byte   -6,   -9, 	  -8,   -8, 	  -6,   -5, 	  -1,  -10
.2byte   -3,   -9, 	  -7,   -6, 	  -2,   -4, 	  -1,   -9
.2byte   -3,   -9, 	  -7,   -6, 	  -2,   -4, 	  -1,   -9
.2byte   -3,   -9, 	  -7,   -6, 	  -2,   -4, 	  -1,   -9
.2byte   -1,   -8, 	  -3,   -5, 	   2,   -5, 	   0,   -9
.2byte   -1,   -8, 	  -3,   -5, 	   2,   -5, 	  -1,   -9
.2byte   -1,   -8, 	  -3,   -5, 	   2,   -5, 	   0,   -9
.2byte    2,   -9, 	   6,   -6, 	   1,   -4, 	   0,   -9
.2byte    2,   -9, 	   6,   -6, 	   1,   -4, 	   0,   -9
.2byte    2,   -9, 	   6,   -6, 	   1,   -4, 	   0,   -9
.2byte    5,   -9, 	   7,   -8, 	   5,   -5, 	   0,  -10
.2byte    5,   -9, 	   7,   -8, 	   5,   -5, 	   0,  -10
.2byte    5,   -9, 	   7,   -8, 	   5,   -5, 	   0,  -10
.2byte    2,  -11, 	   0,   -9, 	   6,   -6, 	   0,  -10
.2byte    2,  -12, 	  -1,   -9, 	   6,   -6, 	  -1,  -10
.2byte    1,  -10, 	   0,   -9, 	   6,   -6, 	  -1,  -10
.2byte    0,  -10, 	   2,   -8, 	  -3,   -8, 	  -1,   -9
.2byte    0,  -10, 	   2,   -8, 	  -3,   -8, 	  -1,   -9
.2byte    0,  -10, 	   2,   -8, 	  -3,   -8, 	  -1,   -9
.2byte   -3,  -11, 	  -1,   -9, 	  -7,   -6, 	  -1,  -10
.2byte   -3,  -12, 	   0,   -9, 	  -7,   -6, 	   0,  -10
.2byte   -2,  -10, 	  -1,   -9, 	  -7,   -6, 	   0,  -10
.2byte   -6,   -9, 	  -8,   -8, 	  -6,   -5, 	  -1,  -10
.2byte   -6,   -9, 	  -8,   -8, 	  -6,   -5, 	  -1,  -10
.2byte   -6,   -9, 	  -8,   -8, 	  -6,   -5, 	  -1,  -10
.2byte   -3,   -9, 	  -7,   -6, 	  -2,   -4, 	  -1,   -9
.2byte   -3,   -9, 	  -7,   -6, 	  -2,   -4, 	  -1,   -9
.2byte   -3,   -9, 	  -7,   -6, 	  -2,   -4, 	  -1,   -9
.2byte   -1,   -8, 	  -3,   -5, 	   2,   -5, 	   0,   -9
.2byte    0,  -12, 	  -7,   -9, 	   6,   -9, 	  -1,  -10
.2byte   -1,   -8, 	  -3,   -5, 	   2,   -5, 	   0,   -9
.2byte    2,   -9, 	   6,   -6, 	   1,   -4, 	   0,   -9
.2byte    2,  -13, 	   6,  -12, 	  -2,   -9, 	   0,  -12
.2byte    2,   -9, 	   6,   -6, 	   1,   -4, 	   0,   -9
.2byte    5,   -9, 	   7,   -8, 	   5,   -5, 	   0,  -10
.2byte    5,  -13, 	   6,  -14, 	   5,  -10, 	  -1,  -11
.2byte    5,   -9, 	   7,   -8, 	   5,   -5, 	   0,  -10
.2byte    2,  -11, 	   0,   -9, 	   6,   -6, 	   0,  -10
.2byte    1,  -13, 	  -3,  -15, 	   4,  -12, 	  -1,   -9
.2byte    1,  -10, 	   0,   -9, 	   6,   -6, 	  -1,  -10
.2byte    0,  -10, 	   2,   -8, 	  -3,   -8, 	  -1,   -9
.2byte    0,  -16, 	   8,  -11, 	  -9,  -11, 	  -1,  -11
.2byte    0,  -10, 	   2,   -8, 	  -3,   -8, 	  -1,   -9
.2byte   -3,  -11, 	  -1,   -9, 	  -7,   -6, 	  -1,  -10
.2byte   -2,  -13, 	   2,  -15, 	  -5,  -12, 	   0,   -9
.2byte   -2,  -10, 	  -1,   -9, 	  -7,   -6, 	   0,  -10
.2byte   -6,   -9, 	  -8,   -8, 	  -6,   -5, 	  -1,  -10
.2byte   -6,  -13, 	  -7,  -14, 	  -6,  -10, 	   0,  -11
.2byte   -6,   -9, 	  -8,   -8, 	  -6,   -5, 	  -1,  -10
.2byte   -3,   -9, 	  -7,   -6, 	  -2,   -4, 	  -1,   -9
.2byte   -3,  -13, 	  -7,  -12, 	   1,   -9, 	  -1,  -12
.2byte   -3,   -9, 	  -7,   -6, 	  -2,   -4, 	  -1,   -9
.2byte   -1,   -8, 	  -3,   -5, 	   2,   -5, 	   0,   -9
.2byte   -3,   -9, 	  -7,   -6, 	  -2,   -4, 	  -1,   -9
.2byte   -6,   -9, 	  -8,   -8, 	  -6,   -5, 	  -1,  -10
.2byte   -2,  -10, 	  -1,   -9, 	  -7,   -6, 	   0,  -10
.2byte    0,  -10, 	   2,   -8, 	  -3,   -8, 	  -1,   -9
.2byte    1,  -10, 	   0,   -9, 	   6,   -6, 	  -1,  -10
.2byte    5,   -9, 	   7,   -8, 	   5,   -5, 	   0,  -10
.2byte    2,   -9, 	   6,   -6, 	   1,   -4, 	   0,   -9
.2byte   -4,   -7, 	  -6,   -5, 	  -1,   -3, 	  -1,   -8
.2byte   -4,   -6, 	  -6,   -4, 	  -1,   -2, 	  -2,   -7
.2byte   -1,  -12, 	  -5,   -8, 	   4,   -8, 	  -1,  -11
.2byte    1,  -13, 	   6,  -10, 	   1,   -8, 	  -1,  -11
.2byte    4,  -14, 	   7,  -13, 	   4,   -9, 	  -1,  -12
.2byte    0,  -14, 	  -1,  -14, 	   7,  -11, 	  -1,  -12
.2byte   -1,  -12, 	   3,  -11, 	  -4,  -11, 	   0,  -12
.2byte   -1,  -14, 	   0,  -14, 	  -8,  -11, 	   0,  -12
.2byte   -5,  -14, 	  -8,  -13, 	  -5,   -9, 	   0,  -12
.2byte   -2,  -13, 	  -7,  -10, 	  -2,   -8, 	   0,  -11
.2byte   -1,   -8, 	  -3,   -5, 	   2,   -5, 	   0,   -9
.2byte   -3,   -9, 	  -7,   -6, 	  -2,   -4, 	  -1,   -9
.2byte   -6,   -9, 	  -8,   -8, 	  -6,   -5, 	  -1,  -10
.2byte   -3,  -12, 	  -1,  -10, 	  -7,   -7, 	  -1,  -11
.2byte    0,  -11, 	   2,   -9, 	  -3,   -9, 	  -1,  -10
.2byte    2,  -11, 	   0,   -9, 	   6,   -6, 	   0,  -10
.2byte    5,   -9, 	   7,   -8, 	   5,   -5, 	   0,  -10
.2byte    2,   -9, 	   6,   -6, 	   1,   -4, 	   0,   -9
.2byte   -1,   -8, 	  -3,   -5, 	   2,   -5, 	  -1,   -9
.2byte   -3,   -9, 	  -7,   -6, 	  -2,   -4, 	  -1,   -9
.2byte   -6,   -9, 	  -8,   -8, 	  -6,   -5, 	  -1,  -10
.2byte   -3,  -13, 	   0,  -10, 	  -7,   -7, 	   0,  -11
.2byte    0,  -11, 	   2,   -9, 	  -3,   -9, 	  -1,  -10
.2byte    2,  -12, 	  -1,   -9, 	   6,   -6, 	  -1,  -10
.2byte    5,   -9, 	   7,   -8, 	   5,   -5, 	   0,  -10
.2byte    2,   -9, 	   6,   -6, 	   1,   -4, 	   0,   -9
.2byte   -1,   -8, 	  -3,   -5, 	   2,   -5, 	   0,   -9
.2byte   -3,   -9, 	  -7,   -6, 	  -2,   -4, 	  -1,   -9
.2byte   -6,   -9, 	  -8,   -8, 	  -6,   -5, 	  -1,  -10
.2byte   -2,  -11, 	  -1,  -10, 	  -7,   -7, 	   0,  -11
.2byte    0,  -11, 	   2,   -9, 	  -3,   -9, 	  -1,  -10
.2byte    1,  -10, 	   0,   -9, 	   6,   -6, 	  -1,  -10
.2byte    5,   -9, 	   7,   -8, 	   5,   -5, 	   0,  -10
.2byte    2,   -9, 	   6,   -6, 	   1,   -4, 	   0,   -9
.2byte   -1,   -8, 	  -3,   -5, 	   2,   -5, 	   0,   -9
.2byte   -3,   -9, 	  -7,   -6, 	  -2,   -4, 	  -1,   -9
.2byte   -5,   -8, 	  -7,   -7, 	  -5,   -4, 	   0,   -9
.2byte   -3,  -11, 	  -1,   -9, 	  -7,   -6, 	  -1,  -10
.2byte    0,  -10, 	   2,   -8, 	  -3,   -8, 	  -1,   -9
.2byte    2,  -11, 	   0,   -9, 	   6,   -6, 	   0,  -10
.2byte    4,   -8, 	   6,   -7, 	   4,   -4, 	  -1,   -9
.2byte    2,   -9, 	   6,   -6, 	   1,   -4, 	   0,   -9
.2byte    0,  -12, 	  -7,   -9, 	   6,   -9, 	  -1,  -10
.2byte    2,  -12, 	   6,  -11, 	  -2,   -8, 	   0,  -11
.2byte    6,  -12, 	   7,  -13, 	   6,   -9, 	   0,  -10
.2byte    1,  -14, 	  -3,  -16, 	   4,  -13, 	  -1,  -10
.2byte    0,  -16, 	   8,  -11, 	  -9,  -11, 	  -1,  -11
.2byte   -2,  -14, 	   2,  -16, 	  -5,  -13, 	   0,  -10
.2byte   -6,  -12, 	  -7,  -13, 	  -6,   -9, 	   0,  -10
.2byte   -3,  -12, 	  -7,  -11, 	   1,   -8, 	  -1,  -11
.2byte   -1,   -8, 	  -3,   -5, 	   2,   -5, 	   0,   -9
.2byte    0,  -12, 	  -7,   -9, 	   6,   -9, 	  -1,  -10
.2byte   -1,   -8, 	  -3,   -5, 	   2,   -5, 	  -1,   -9
.2byte    2,   -9, 	   6,   -6, 	   1,   -4, 	   0,   -9
.2byte    2,  -13, 	   6,  -12, 	  -2,   -9, 	   0,  -12
.2byte    2,   -9, 	   6,   -6, 	   1,   -4, 	   0,   -9
.2byte    5,   -9, 	   7,   -8, 	   5,   -5, 	   0,  -10
.2byte    6,  -13, 	   7,  -14, 	   6,  -10, 	   0,  -11
.2byte    5,   -9, 	   7,   -8, 	   5,   -5, 	   0,  -10
.2byte    2,  -11, 	   0,   -9, 	   6,   -6, 	   0,  -10
.2byte    1,  -13, 	  -3,  -15, 	   4,  -12, 	  -1,   -9
.2byte    2,  -12, 	  -1,   -9, 	   6,   -6, 	  -1,  -10
.2byte    0,  -10, 	   2,   -8, 	  -3,   -8, 	  -1,   -9
.2byte    0,  -16, 	   8,  -11, 	  -9,  -11, 	  -1,  -11
.2byte    0,  -10, 	   2,   -8, 	  -3,   -8, 	  -1,   -9
.2byte   -3,  -11, 	  -1,   -9, 	  -7,   -6, 	  -1,  -10
.2byte   -2,  -13, 	   2,  -15, 	  -5,  -12, 	   0,   -9
.2byte   -3,  -12, 	   0,   -9, 	  -7,   -6, 	   0,  -10
.2byte   -6,   -9, 	  -8,   -8, 	  -6,   -5, 	  -1,  -10
.2byte   -7,  -13, 	  -8,  -14, 	  -7,  -10, 	  -1,  -11
.2byte   -6,   -9, 	  -8,   -8, 	  -6,   -5, 	  -1,  -10
.2byte   -3,   -9, 	  -7,   -6, 	  -2,   -4, 	  -1,   -9
.2byte   -3,  -13, 	  -7,  -12, 	   1,   -9, 	  -1,  -12
.2byte   -3,   -9, 	  -7,   -6, 	  -2,   -4, 	  -1,   -9
.2byte   -1,   -8, 	  -3,   -5, 	   2,   -5, 	   0,   -9
.2byte   -3,   -9, 	  -7,   -6, 	  -2,   -4, 	  -1,   -9
.2byte   -6,   -9, 	  -8,   -8, 	  -6,   -5, 	  -1,  -10
.2byte   -2,  -10, 	  -1,   -9, 	  -7,   -6, 	   0,  -10
.2byte    0,  -10, 	   2,   -8, 	  -3,   -8, 	  -1,   -9
.2byte    1,  -10, 	   0,   -9, 	   6,   -6, 	  -1,  -10
.2byte    5,   -9, 	   7,   -8, 	   5,   -5, 	   0,  -10
.2byte    2,   -9, 	   6,   -6, 	   1,   -4, 	   0,   -9
.2byte   -1,   -8, 	  -3,   -5, 	   2,   -5, 	   0,   -9
.2byte   -3,   -9, 	  -7,   -6, 	  -2,   -4, 	  -1,   -9
.2byte   -6,   -9, 	  -8,   -8, 	  -6,   -5, 	  -1,  -10
.2byte   -3,  -11, 	  -1,   -9, 	  -7,   -6, 	  -1,  -10
.2byte    0,  -10, 	   2,   -8, 	  -3,   -8, 	  -1,   -9
.2byte    2,  -11, 	   0,   -9, 	   6,   -6, 	   0,  -10
.2byte    5,   -9, 	   7,   -8, 	   5,   -5, 	   0,  -10
.2byte    2,   -9, 	   6,   -6, 	   1,   -4, 	   0,   -9
sHoppipAnimTable1:
.4byte sHoppipAnims_1_1
.4byte sHoppipAnims_1_2
.4byte sHoppipAnims_1_3
.4byte sHoppipAnims_1_4
.4byte sHoppipAnims_1_5
.4byte sHoppipAnims_1_6
.4byte sHoppipAnims_1_7
.4byte sHoppipAnims_1_8
sHoppipAnimTable2:
.4byte sHoppipAnims_2_1
.4byte sHoppipAnims_2_2
.4byte sHoppipAnims_2_3
.4byte sHoppipAnims_2_4
.4byte sHoppipAnims_2_5
.4byte sHoppipAnims_2_6
.4byte sHoppipAnims_2_7
.4byte sHoppipAnims_2_8
sHoppipAnimTable3:
.4byte sHoppipAnims_3_1
.4byte sHoppipAnims_3_2
.4byte sHoppipAnims_3_3
.4byte sHoppipAnims_3_4
.4byte sHoppipAnims_3_5
.4byte sHoppipAnims_3_6
.4byte sHoppipAnims_3_7
.4byte sHoppipAnims_3_8
sHoppipAnimTable4:
.4byte sHoppipAnims_4_1
.4byte sHoppipAnims_4_2
.4byte sHoppipAnims_4_3
.4byte sHoppipAnims_4_4
.4byte sHoppipAnims_4_5
.4byte sHoppipAnims_4_6
.4byte sHoppipAnims_4_7
.4byte sHoppipAnims_4_8
sHoppipAnimTable5:
.4byte sHoppipAnims_5_1
.4byte sHoppipAnims_5_2
.4byte sHoppipAnims_5_3
.4byte sHoppipAnims_5_4
.4byte sHoppipAnims_5_5
.4byte sHoppipAnims_5_6
.4byte sHoppipAnims_5_7
.4byte sHoppipAnims_5_8
sHoppipAnimTable6:
.4byte sHoppipAnims_6_1
.4byte sHoppipAnims_6_1
.4byte sHoppipAnims_6_1
.4byte sHoppipAnims_6_1
.4byte sHoppipAnims_6_1
.4byte sHoppipAnims_6_1
.4byte sHoppipAnims_6_1
.4byte sHoppipAnims_6_1
sHoppipAnimTable7:
.4byte sHoppipAnims_7_1
.4byte sHoppipAnims_7_2
.4byte sHoppipAnims_7_3
.4byte sHoppipAnims_7_4
.4byte sHoppipAnims_7_5
.4byte sHoppipAnims_7_6
.4byte sHoppipAnims_7_7
.4byte sHoppipAnims_7_8
sHoppipAnimTable8:
.4byte sHoppipAnims_8_1
.4byte sHoppipAnims_8_2
.4byte sHoppipAnims_8_3
.4byte sHoppipAnims_8_4
.4byte sHoppipAnims_8_5
.4byte sHoppipAnims_8_6
.4byte sHoppipAnims_8_7
.4byte sHoppipAnims_8_8
sHoppipAnimTable9:
.4byte sHoppipAnims_9_1
.4byte sHoppipAnims_9_2
.4byte sHoppipAnims_9_3
.4byte sHoppipAnims_9_4
.4byte sHoppipAnims_9_5
.4byte sHoppipAnims_9_6
.4byte sHoppipAnims_9_7
.4byte sHoppipAnims_9_8
sHoppipAnimTable10:
.4byte sHoppipAnims_10_1
.4byte sHoppipAnims_10_2
.4byte sHoppipAnims_10_3
.4byte sHoppipAnims_10_4
.4byte sHoppipAnims_10_5
.4byte sHoppipAnims_10_6
.4byte sHoppipAnims_10_7
.4byte sHoppipAnims_10_8
sHoppipAnimTable11:
.4byte sHoppipAnims_11_1
.4byte sHoppipAnims_11_2
.4byte sHoppipAnims_11_3
.4byte sHoppipAnims_11_4
.4byte sHoppipAnims_11_5
.4byte sHoppipAnims_11_6
.4byte sHoppipAnims_11_7
.4byte sHoppipAnims_11_8
sHoppipAnimTable12:
.4byte sHoppipAnims_12_1
.4byte sHoppipAnims_12_2
.4byte sHoppipAnims_12_3
.4byte sHoppipAnims_12_4
.4byte sHoppipAnims_12_5
.4byte sHoppipAnims_12_6
.4byte sHoppipAnims_12_7
.4byte sHoppipAnims_12_8
sHoppipAnimTable13:
.4byte sHoppipAnims_13_1
.4byte sHoppipAnims_13_2
.4byte sHoppipAnims_13_3
.4byte sHoppipAnims_13_4
.4byte sHoppipAnims_13_5
.4byte sHoppipAnims_13_6
.4byte sHoppipAnims_13_7
.4byte sHoppipAnims_13_8
sAxAnimationsHoppip:
.4byte sHoppipAnimTable1
.4byte sHoppipAnimTable2
.4byte sHoppipAnimTable3
.4byte sHoppipAnimTable4
.4byte sHoppipAnimTable5
.4byte sHoppipAnimTable6
.4byte sHoppipAnimTable7
.4byte sHoppipAnimTable8
.4byte sHoppipAnimTable9
.4byte sHoppipAnimTable10
.4byte sHoppipAnimTable11
.4byte sHoppipAnimTable12
.4byte sHoppipAnimTable13
sAxSpritesHoppip:
.4byte sHoppipSprites1
.4byte sHoppipSprites2
.4byte sHoppipSprites3
.4byte sHoppipSprites4
.4byte sHoppipSprites5
.4byte sHoppipSprites6
.4byte sHoppipSprites7
.4byte sHoppipSprites8
.4byte sHoppipSprites9
.4byte sHoppipSprites10
.4byte sHoppipSprites11
.4byte sHoppipSprites12
.4byte sHoppipSprites13
.4byte sHoppipSprites14
.4byte sHoppipSprites15
.4byte sHoppipSprites16
.4byte sHoppipSprites17
.4byte sHoppipSprites18
.4byte sHoppipSprites19
.4byte sHoppipSprites20
.4byte sHoppipSprites21
.4byte sHoppipSprites22
.4byte sHoppipSprites23
.4byte sHoppipSprites24
.4byte sHoppipSprites25
.4byte sHoppipSprites26
.4byte sHoppipSprites27
.4byte sHoppipSprites28
.4byte sHoppipSprites29
.4byte sHoppipSprites30
.4byte sHoppipSprites31
.4byte sHoppipSprites32
.4byte sHoppipSprites33
.4byte sHoppipSprites34
.4byte sHoppipSprites35
.4byte sHoppipSprites36
.4byte sHoppipSprites37
sAxMainHoppip:
ax_main sAxPosesHoppip, sAxAnimationsHoppip, 13, sAxSpritesHoppip, sAxPositionsHoppip
