.global gAxHoundoom
gAxHoundoom:
ax_siro sAxMainHoundoom
sHoundoomPose1:
ax_pose 0, 0x01e7, 0x0107, 0x6c00
ax_pose 1, 0x81e7, 0x80f7, 0x6c01
ax_pose_terminator
sHoundoomPose2:
ax_pose 2, 0x01ea, 0x80f7, 0x6c00
ax_pose_terminator
sHoundoomPose3:
ax_pose 3, 0x01ea, 0x80ef, 0x6c00
ax_pose_terminator
sHoundoomPose4:
ax_pose 4, 0x0207, 0x10fe, 0x6c00
ax_pose 5, 0x81ef, 0x10ee, 0x6c01
ax_pose 6, 0x81e7, 0x50f6, 0x6c03
ax_pose 7, 0x81e7, 0x90fe, 0x6c07
ax_pose_terminator
sHoundoomPose5:
ax_pose 8, 0x01e7, 0x90ef, 0x6c00
ax_pose_terminator
sHoundoomPose6:
ax_pose 9, 0x0208, 0x1100, 0x6c00
ax_pose 10, 0x81ef, 0x10f0, 0x6c01
ax_pose 11, 0x81e7, 0x50f8, 0x6c03
ax_pose 12, 0x81e8, 0x9100, 0x6c07
ax_pose_terminator
sHoundoomPose7:
ax_pose 13, 0x01fb, 0x10e9, 0x6c00
ax_pose 14, 0x01ec, 0x10f1, 0x6c01
ax_pose 15, 0x81f4, 0x10f1, 0x6c02
ax_pose 16, 0x81e4, 0x50f9, 0x6c04
ax_pose 17, 0x81e4, 0x9101, 0x6c08
ax_pose_terminator
sHoundoomPose8:
ax_pose 18, 0x01fd, 0x10e9, 0x6c00
ax_pose 19, 0x01fd, 0x10f1, 0x6c01
ax_pose 20, 0x81ed, 0x10f1, 0x6c02
ax_pose 21, 0x81e5, 0x50f9, 0x6c04
ax_pose 22, 0x81e5, 0x9101, 0x6c08
ax_pose_terminator
sHoundoomPose9:
ax_pose 23, 0x01e5, 0x90f1, 0x6c00
ax_pose_terminator
sHoundoomPose10:
ax_pose 24, 0x0202, 0x10f1, 0x6c00
ax_pose 25, 0x0202, 0x10f9, 0x6c01
ax_pose 26, 0x01fa, 0x10ed, 0x6c02
ax_pose 27, 0x81e2, 0x50f5, 0x6c03
ax_pose 28, 0x81e2, 0x90fd, 0x6c07
ax_pose_terminator
sHoundoomPose11:
ax_pose 29, 0x0202, 0x10fa, 0x6c00
ax_pose 30, 0x0202, 0x10f2, 0x6c01
ax_pose 31, 0x81f2, 0x10ed, 0x6c02
ax_pose 32, 0x81e2, 0x50f5, 0x6c04
ax_pose 33, 0x81e2, 0x90fd, 0x6c08
ax_pose_terminator
sHoundoomPose12:
ax_pose 34, 0x0202, 0x10f5, 0x6c00
ax_pose 35, 0x81f2, 0x10ed, 0x6c01
ax_pose 36, 0x81e2, 0x50f5, 0x6c03
ax_pose 37, 0x81e2, 0x90fd, 0x6c07
ax_pose_terminator
sHoundoomPose13:
ax_pose 38, 0x4202, 0x00f8, 0x6c00
ax_pose 39, 0x81e2, 0x80f8, 0x6c02
ax_pose_terminator
sHoundoomPose14:
ax_pose 40, 0x4202, 0x00f8, 0x6c00
ax_pose 41, 0x81e2, 0x80f8, 0x6c02
ax_pose_terminator
sHoundoomPose15:
ax_pose 42, 0x0202, 0x0108, 0x6c00
ax_pose 43, 0x01fa, 0x0108, 0x6c01
ax_pose 44, 0x4202, 0x00f8, 0x6c02
ax_pose 45, 0x81e2, 0x80f8, 0x6c04
ax_pose_terminator
sHoundoomPose16:
ax_pose 24, 0x0202, 0x0107, 0x6c00
ax_pose 25, 0x0202, 0x00ff, 0x6c01
ax_pose 26, 0x01fa, 0x010b, 0x6c02
ax_pose 27, 0x81e2, 0x4103, 0x6c03
ax_pose 28, 0x81e2, 0x80f3, 0x6c07
ax_pose_terminator
sHoundoomPose17:
ax_pose 29, 0x0202, 0x00fe, 0x6c00
ax_pose 30, 0x0202, 0x0106, 0x6c01
ax_pose 31, 0x81f2, 0x010b, 0x6c02
ax_pose 32, 0x81e2, 0x4103, 0x6c04
ax_pose 33, 0x81e2, 0x80f3, 0x6c08
ax_pose_terminator
sHoundoomPose18:
ax_pose 34, 0x0202, 0x0103, 0x6c00
ax_pose 35, 0x81f2, 0x010b, 0x6c01
ax_pose 36, 0x81e2, 0x4103, 0x6c03
ax_pose 37, 0x81e2, 0x80f3, 0x6c07
ax_pose_terminator
sHoundoomPose19:
ax_pose 13, 0x01fb, 0x010f, 0x6c00
ax_pose 14, 0x01ec, 0x0107, 0x6c01
ax_pose 15, 0x81f4, 0x0107, 0x6c02
ax_pose 16, 0x81e4, 0x40ff, 0x6c04
ax_pose 17, 0x81e4, 0x80ef, 0x6c08
ax_pose_terminator
sHoundoomPose20:
ax_pose 18, 0x01fd, 0x010f, 0x6c00
ax_pose 19, 0x01fd, 0x0107, 0x6c01
ax_pose 20, 0x81ed, 0x0107, 0x6c02
ax_pose 21, 0x81e5, 0x40ff, 0x6c04
ax_pose 22, 0x81e5, 0x80ef, 0x6c08
ax_pose_terminator
sHoundoomPose21:
ax_pose 23, 0x01e5, 0x80ef, 0x6c00
ax_pose_terminator
sHoundoomPose22:
ax_pose 4, 0x0207, 0x00fa, 0x6c00
ax_pose 5, 0x81ef, 0x010a, 0x6c01
ax_pose 6, 0x81e7, 0x4102, 0x6c03
ax_pose 7, 0x81e7, 0x80f2, 0x6c07
ax_pose_terminator
sHoundoomPose23:
ax_pose 8, 0x01e7, 0x80f1, 0x6c00
ax_pose_terminator
sHoundoomPose24:
ax_pose 9, 0x0208, 0x00f8, 0x6c00
ax_pose 10, 0x81ef, 0x0108, 0x6c01
ax_pose 11, 0x81e7, 0x4100, 0x6c03
ax_pose 12, 0x81e8, 0x80f0, 0x6c07
ax_pose_terminator
sHoundoomPose25:
ax_pose 0, 0x01e7, 0x0107, 0x6c00
ax_pose 1, 0x81e7, 0x80f7, 0x6c01
ax_pose_terminator
sHoundoomPose26:
ax_pose 2, 0x01ea, 0x80f7, 0x6c00
ax_pose_terminator
sHoundoomPose27:
ax_pose 3, 0x01ea, 0x80ef, 0x6c00
ax_pose_terminator
sHoundoomPose28:
ax_pose 46, 0x01e7, 0x80f7, 0x6c00
ax_pose_terminator
sHoundoomPose29:
ax_pose 4, 0x0207, 0x10fe, 0x6c00
ax_pose 5, 0x81ef, 0x10ee, 0x6c01
ax_pose 6, 0x81e7, 0x50f6, 0x6c03
ax_pose 7, 0x81e7, 0x90fe, 0x6c07
ax_pose_terminator
sHoundoomPose30:
ax_pose 8, 0x01e7, 0x90ef, 0x6c00
ax_pose_terminator
sHoundoomPose31:
ax_pose 9, 0x0208, 0x1100, 0x6c00
ax_pose 10, 0x81ef, 0x10f0, 0x6c01
ax_pose 11, 0x81e7, 0x50f8, 0x6c03
ax_pose 12, 0x81e8, 0x9100, 0x6c07
ax_pose_terminator
sHoundoomPose32:
ax_pose 47, 0x01e8, 0x90ee, 0x6c00
ax_pose_terminator
sHoundoomPose33:
ax_pose 13, 0x01fb, 0x10e9, 0x6c00
ax_pose 14, 0x01ec, 0x10f1, 0x6c01
ax_pose 15, 0x81f4, 0x10f1, 0x6c02
ax_pose 16, 0x81e4, 0x50f9, 0x6c04
ax_pose 17, 0x81e4, 0x9101, 0x6c08
ax_pose_terminator
sHoundoomPose34:
ax_pose 18, 0x01fd, 0x10e9, 0x6c00
ax_pose 19, 0x01fd, 0x10f1, 0x6c01
ax_pose 20, 0x81ed, 0x10f1, 0x6c02
ax_pose 21, 0x81e5, 0x50f9, 0x6c04
ax_pose 22, 0x81e5, 0x9101, 0x6c08
ax_pose_terminator
sHoundoomPose35:
ax_pose 23, 0x01e5, 0x90f1, 0x6c00
ax_pose_terminator
sHoundoomPose36:
ax_pose 48, 0x81e4, 0x110c, 0x6c00
ax_pose 49, 0x81e4, 0x5104, 0x6c02
ax_pose 50, 0x01dc, 0x1104, 0x6c06
ax_pose 51, 0x01f4, 0x50f4, 0x6c07
ax_pose 52, 0x41ec, 0x10f4, 0x6c0b
ax_pose 53, 0x01f4, 0x10ec, 0x6c0d
ax_pose 54, 0x01fc, 0x10ec, 0x6c0e
ax_pose_terminator
sHoundoomPose37:
ax_pose 24, 0x0202, 0x10f1, 0x6c00
ax_pose 25, 0x0202, 0x10f9, 0x6c01
ax_pose 26, 0x01fa, 0x10ed, 0x6c02
ax_pose 27, 0x81e2, 0x50f5, 0x6c03
ax_pose 28, 0x81e2, 0x90fd, 0x6c07
ax_pose_terminator
sHoundoomPose38:
ax_pose 29, 0x0202, 0x10fa, 0x6c00
ax_pose 30, 0x0202, 0x10f2, 0x6c01
ax_pose 31, 0x81f2, 0x10ed, 0x6c02
ax_pose 32, 0x81e2, 0x50f5, 0x6c04
ax_pose 33, 0x81e2, 0x90fd, 0x6c08
ax_pose_terminator
sHoundoomPose39:
ax_pose 34, 0x0202, 0x10f5, 0x6c00
ax_pose 35, 0x81f2, 0x10ed, 0x6c01
ax_pose 36, 0x81e2, 0x50f5, 0x6c03
ax_pose 37, 0x81e2, 0x90fd, 0x6c07
ax_pose_terminator
sHoundoomPose40:
ax_pose 55, 0x81e1, 0x90ff, 0x6c00
ax_pose 56, 0x01f1, 0x50ef, 0x6c08
ax_pose 57, 0x0201, 0x10ef, 0x6c0c
ax_pose 58, 0x0201, 0x10f7, 0x6c0d
ax_pose 59, 0x81e1, 0x10f7, 0x6c0e
ax_pose_terminator
sHoundoomPose41:
ax_pose 38, 0x4202, 0x00f8, 0x6c00
ax_pose 39, 0x81e2, 0x80f8, 0x6c02
ax_pose_terminator
sHoundoomPose42:
ax_pose 40, 0x4202, 0x00f8, 0x6c00
ax_pose 41, 0x81e2, 0x80f8, 0x6c02
ax_pose_terminator
sHoundoomPose43:
ax_pose 42, 0x0202, 0x0108, 0x6c00
ax_pose 43, 0x01fa, 0x0108, 0x6c01
ax_pose 44, 0x4202, 0x00f8, 0x6c02
ax_pose 45, 0x81e2, 0x80f8, 0x6c04
ax_pose_terminator
sHoundoomPose44:
ax_pose 60, 0x0201, 0x00f8, 0x6c00
ax_pose 61, 0x0201, 0x0100, 0x6c01
ax_pose 62, 0x81e1, 0x80f8, 0x6c02
ax_pose_terminator
sHoundoomPose45:
ax_pose 24, 0x0202, 0x0107, 0x6c00
ax_pose 25, 0x0202, 0x00ff, 0x6c01
ax_pose 26, 0x01fa, 0x010b, 0x6c02
ax_pose 27, 0x81e2, 0x4103, 0x6c03
ax_pose 28, 0x81e2, 0x80f3, 0x6c07
ax_pose_terminator
sHoundoomPose46:
ax_pose 29, 0x0202, 0x00fe, 0x6c00
ax_pose 30, 0x0202, 0x0106, 0x6c01
ax_pose 31, 0x81f2, 0x010b, 0x6c02
ax_pose 32, 0x81e2, 0x4103, 0x6c04
ax_pose 33, 0x81e2, 0x80f3, 0x6c08
ax_pose_terminator
sHoundoomPose47:
ax_pose 34, 0x0202, 0x0103, 0x6c00
ax_pose 35, 0x81f2, 0x010b, 0x6c01
ax_pose 36, 0x81e2, 0x4103, 0x6c03
ax_pose 37, 0x81e2, 0x80f3, 0x6c07
ax_pose_terminator
sHoundoomPose48:
ax_pose 55, 0x81e1, 0x80f1, 0x6c00
ax_pose 56, 0x01f1, 0x4101, 0x6c08
ax_pose 57, 0x0201, 0x0109, 0x6c0c
ax_pose 58, 0x0201, 0x0101, 0x6c0d
ax_pose 59, 0x81e1, 0x0101, 0x6c0e
ax_pose_terminator
sHoundoomPose49:
ax_pose 13, 0x01fb, 0x010f, 0x6c00
ax_pose 14, 0x01ec, 0x0107, 0x6c01
ax_pose 15, 0x81f4, 0x0107, 0x6c02
ax_pose 16, 0x81e4, 0x40ff, 0x6c04
ax_pose 17, 0x81e4, 0x80ef, 0x6c08
ax_pose_terminator
sHoundoomPose50:
ax_pose 18, 0x01fd, 0x010f, 0x6c00
ax_pose 19, 0x01fd, 0x0107, 0x6c01
ax_pose 20, 0x81ed, 0x0107, 0x6c02
ax_pose 21, 0x81e5, 0x40ff, 0x6c04
ax_pose 22, 0x81e5, 0x80ef, 0x6c08
ax_pose_terminator
sHoundoomPose51:
ax_pose 23, 0x01e5, 0x80ef, 0x6c00
ax_pose_terminator
sHoundoomPose52:
ax_pose 48, 0x81e4, 0x00ec, 0x6c00
ax_pose 49, 0x81e4, 0x40f4, 0x6c02
ax_pose 50, 0x01dc, 0x00f4, 0x6c06
ax_pose 51, 0x01f4, 0x40fc, 0x6c07
ax_pose 52, 0x41ec, 0x00fc, 0x6c0b
ax_pose 53, 0x01f4, 0x010c, 0x6c0d
ax_pose 54, 0x01fc, 0x010c, 0x6c0e
ax_pose_terminator
sHoundoomPose53:
ax_pose 4, 0x0207, 0x00fa, 0x6c00
ax_pose 5, 0x81ef, 0x010a, 0x6c01
ax_pose 6, 0x81e7, 0x4102, 0x6c03
ax_pose 7, 0x81e7, 0x80f2, 0x6c07
ax_pose_terminator
sHoundoomPose54:
ax_pose 8, 0x01e7, 0x80f1, 0x6c00
ax_pose_terminator
sHoundoomPose55:
ax_pose 9, 0x0208, 0x00f8, 0x6c00
ax_pose 10, 0x81ef, 0x0108, 0x6c01
ax_pose 11, 0x81e7, 0x4100, 0x6c03
ax_pose 12, 0x81e8, 0x80f0, 0x6c07
ax_pose_terminator
sHoundoomPose56:
ax_pose 47, 0x01e8, 0x80f2, 0x6c00
ax_pose_terminator
sHoundoomPose57:
ax_pose 0, 0x01e7, 0x0107, 0x6c00
ax_pose 1, 0x81e7, 0x80f7, 0x6c01
ax_pose_terminator
sHoundoomPose58:
ax_pose 2, 0x01ea, 0x80f7, 0x6c00
ax_pose_terminator
sHoundoomPose59:
ax_pose 3, 0x01ea, 0x80ef, 0x6c00
ax_pose_terminator
sHoundoomPose60:
ax_pose 46, 0x01e7, 0x80f7, 0x6c00
ax_pose_terminator
sHoundoomPose61:
ax_pose 4, 0x0207, 0x10fe, 0x6c00
ax_pose 5, 0x81ef, 0x10ee, 0x6c01
ax_pose 6, 0x81e7, 0x50f6, 0x6c03
ax_pose 7, 0x81e7, 0x90fe, 0x6c07
ax_pose_terminator
sHoundoomPose62:
ax_pose 8, 0x01e7, 0x90ef, 0x6c00
ax_pose_terminator
sHoundoomPose63:
ax_pose 9, 0x0208, 0x1100, 0x6c00
ax_pose 10, 0x81ef, 0x10f0, 0x6c01
ax_pose 11, 0x81e7, 0x50f8, 0x6c03
ax_pose 12, 0x81e8, 0x9100, 0x6c07
ax_pose_terminator
sHoundoomPose64:
ax_pose 47, 0x01e8, 0x90ee, 0x6c00
ax_pose_terminator
sHoundoomPose65:
ax_pose 13, 0x01fb, 0x10e9, 0x6c00
ax_pose 14, 0x01ec, 0x10f1, 0x6c01
ax_pose 15, 0x81f4, 0x10f1, 0x6c02
ax_pose 16, 0x81e4, 0x50f9, 0x6c04
ax_pose 17, 0x81e4, 0x9101, 0x6c08
ax_pose_terminator
sHoundoomPose66:
ax_pose 18, 0x01fd, 0x10e9, 0x6c00
ax_pose 19, 0x01fd, 0x10f1, 0x6c01
ax_pose 20, 0x81ed, 0x10f1, 0x6c02
ax_pose 21, 0x81e5, 0x50f9, 0x6c04
ax_pose 22, 0x81e5, 0x9101, 0x6c08
ax_pose_terminator
sHoundoomPose67:
ax_pose 23, 0x01e5, 0x90f1, 0x6c00
ax_pose_terminator
sHoundoomPose68:
ax_pose 48, 0x81e4, 0x110c, 0x6c00
ax_pose 49, 0x81e4, 0x5104, 0x6c02
ax_pose 50, 0x01dc, 0x1104, 0x6c06
ax_pose 51, 0x01f4, 0x50f4, 0x6c07
ax_pose 52, 0x41ec, 0x10f4, 0x6c0b
ax_pose 53, 0x01f4, 0x10ec, 0x6c0d
ax_pose 54, 0x01fc, 0x10ec, 0x6c0e
ax_pose_terminator
sHoundoomPose69:
ax_pose 24, 0x0202, 0x10f1, 0x6c00
ax_pose 25, 0x0202, 0x10f9, 0x6c01
ax_pose 26, 0x01fa, 0x10ed, 0x6c02
ax_pose 27, 0x81e2, 0x50f5, 0x6c03
ax_pose 28, 0x81e2, 0x90fd, 0x6c07
ax_pose_terminator
sHoundoomPose70:
ax_pose 29, 0x0202, 0x10fa, 0x6c00
ax_pose 30, 0x0202, 0x10f2, 0x6c01
ax_pose 31, 0x81f2, 0x10ed, 0x6c02
ax_pose 32, 0x81e2, 0x50f5, 0x6c04
ax_pose 33, 0x81e2, 0x90fd, 0x6c08
ax_pose_terminator
sHoundoomPose71:
ax_pose 34, 0x0202, 0x10f5, 0x6c00
ax_pose 35, 0x81f2, 0x10ed, 0x6c01
ax_pose 36, 0x81e2, 0x50f5, 0x6c03
ax_pose 37, 0x81e2, 0x90fd, 0x6c07
ax_pose_terminator
sHoundoomPose72:
ax_pose 55, 0x81e1, 0x90ff, 0x6c00
ax_pose 56, 0x01f1, 0x50ef, 0x6c08
ax_pose 57, 0x0201, 0x10ef, 0x6c0c
ax_pose 58, 0x0201, 0x10f7, 0x6c0d
ax_pose 59, 0x81e1, 0x10f7, 0x6c0e
ax_pose_terminator
sHoundoomPose73:
ax_pose 38, 0x4202, 0x00f8, 0x6c00
ax_pose 39, 0x81e2, 0x80f8, 0x6c02
ax_pose_terminator
sHoundoomPose74:
ax_pose 40, 0x4202, 0x00f8, 0x6c00
ax_pose 41, 0x81e2, 0x80f8, 0x6c02
ax_pose_terminator
sHoundoomPose75:
ax_pose 42, 0x0202, 0x0108, 0x6c00
ax_pose 43, 0x01fa, 0x0108, 0x6c01
ax_pose 44, 0x4202, 0x00f8, 0x6c02
ax_pose 45, 0x81e2, 0x80f8, 0x6c04
ax_pose_terminator
sHoundoomPose76:
ax_pose 60, 0x0201, 0x00f8, 0x6c00
ax_pose 61, 0x0201, 0x0100, 0x6c01
ax_pose 62, 0x81e1, 0x80f8, 0x6c02
ax_pose_terminator
sHoundoomPose77:
ax_pose 24, 0x0202, 0x0107, 0x6c00
ax_pose 25, 0x0202, 0x00ff, 0x6c01
ax_pose 26, 0x01fa, 0x010b, 0x6c02
ax_pose 27, 0x81e2, 0x4103, 0x6c03
ax_pose 28, 0x81e2, 0x80f3, 0x6c07
ax_pose_terminator
sHoundoomPose78:
ax_pose 29, 0x0202, 0x00fe, 0x6c00
ax_pose 30, 0x0202, 0x0106, 0x6c01
ax_pose 31, 0x81f2, 0x010b, 0x6c02
ax_pose 32, 0x81e2, 0x4103, 0x6c04
ax_pose 33, 0x81e2, 0x80f3, 0x6c08
ax_pose_terminator
sHoundoomPose79:
ax_pose 34, 0x0202, 0x0103, 0x6c00
ax_pose 35, 0x81f2, 0x010b, 0x6c01
ax_pose 36, 0x81e2, 0x4103, 0x6c03
ax_pose 37, 0x81e2, 0x80f3, 0x6c07
ax_pose_terminator
sHoundoomPose80:
ax_pose 55, 0x81e1, 0x80f1, 0x6c00
ax_pose 56, 0x01f1, 0x4101, 0x6c08
ax_pose 57, 0x0201, 0x0109, 0x6c0c
ax_pose 58, 0x0201, 0x0101, 0x6c0d
ax_pose 59, 0x81e1, 0x0101, 0x6c0e
ax_pose_terminator
sHoundoomPose81:
ax_pose 13, 0x01fb, 0x010f, 0x6c00
ax_pose 14, 0x01ec, 0x0107, 0x6c01
ax_pose 15, 0x81f4, 0x0107, 0x6c02
ax_pose 16, 0x81e4, 0x40ff, 0x6c04
ax_pose 17, 0x81e4, 0x80ef, 0x6c08
ax_pose_terminator
sHoundoomPose82:
ax_pose 18, 0x01fd, 0x010f, 0x6c00
ax_pose 19, 0x01fd, 0x0107, 0x6c01
ax_pose 20, 0x81ed, 0x0107, 0x6c02
ax_pose 21, 0x81e5, 0x40ff, 0x6c04
ax_pose 22, 0x81e5, 0x80ef, 0x6c08
ax_pose_terminator
sHoundoomPose83:
ax_pose 23, 0x01e5, 0x80ef, 0x6c00
ax_pose_terminator
sHoundoomPose84:
ax_pose 48, 0x81e4, 0x00ec, 0x6c00
ax_pose 49, 0x81e4, 0x40f4, 0x6c02
ax_pose 50, 0x01dc, 0x00f4, 0x6c06
ax_pose 51, 0x01f4, 0x40fc, 0x6c07
ax_pose 52, 0x41ec, 0x00fc, 0x6c0b
ax_pose 53, 0x01f4, 0x010c, 0x6c0d
ax_pose 54, 0x01fc, 0x010c, 0x6c0e
ax_pose_terminator
sHoundoomPose85:
ax_pose 4, 0x0207, 0x00fa, 0x6c00
ax_pose 5, 0x81ef, 0x010a, 0x6c01
ax_pose 6, 0x81e7, 0x4102, 0x6c03
ax_pose 7, 0x81e7, 0x80f2, 0x6c07
ax_pose_terminator
sHoundoomPose86:
ax_pose 8, 0x01e7, 0x80f1, 0x6c00
ax_pose_terminator
sHoundoomPose87:
ax_pose 9, 0x0208, 0x00f8, 0x6c00
ax_pose 10, 0x81ef, 0x0108, 0x6c01
ax_pose 11, 0x81e7, 0x4100, 0x6c03
ax_pose 12, 0x81e8, 0x80f0, 0x6c07
ax_pose_terminator
sHoundoomPose88:
ax_pose 47, 0x01e8, 0x80f2, 0x6c00
ax_pose_terminator
sHoundoomPose89:
ax_pose 0, 0x01e7, 0x0107, 0x6c00
ax_pose 1, 0x81e7, 0x80f7, 0x6c01
ax_pose_terminator
sHoundoomPose90:
ax_pose 2, 0x01ea, 0x80f7, 0x6c00
ax_pose_terminator
sHoundoomPose91:
ax_pose 63, 0x01e6, 0x80f7, 0x6c00
ax_pose_terminator
sHoundoomPose92:
ax_pose 46, 0x01e7, 0x80f7, 0x6c00
ax_pose_terminator
sHoundoomPose93:
ax_pose 64, 0x81e5, 0x80f7, 0x6c00
ax_pose 65, 0x01e5, 0x0107, 0x6c08
ax_pose_terminator
sHoundoomPose94:
ax_pose 4, 0x0207, 0x10fe, 0x6c00
ax_pose 5, 0x81ef, 0x10ee, 0x6c01
ax_pose 6, 0x81e7, 0x50f6, 0x6c03
ax_pose 7, 0x81e7, 0x90fe, 0x6c07
ax_pose_terminator
sHoundoomPose95:
ax_pose 8, 0x01e7, 0x90ef, 0x6c00
ax_pose_terminator
sHoundoomPose96:
ax_pose 66, 0x01e8, 0x90ee, 0x6c00
ax_pose_terminator
sHoundoomPose97:
ax_pose 47, 0x01e8, 0x90ee, 0x6c00
ax_pose_terminator
sHoundoomPose98:
ax_pose 67, 0x81e6, 0x90fe, 0x6c00
ax_pose 68, 0x81e6, 0x50f6, 0x6c08
ax_pose 69, 0x01de, 0x10f6, 0x6c0c
ax_pose 70, 0x01de, 0x10fe, 0x6c0d
ax_pose 71, 0x01f6, 0x10ee, 0x6c0e
ax_pose_terminator
sHoundoomPose99:
ax_pose 13, 0x01fb, 0x10e9, 0x6c00
ax_pose 14, 0x01ec, 0x10f1, 0x6c01
ax_pose 15, 0x81f4, 0x10f1, 0x6c02
ax_pose 16, 0x81e4, 0x50f9, 0x6c04
ax_pose 17, 0x81e4, 0x9101, 0x6c08
ax_pose_terminator
sHoundoomPose100:
ax_pose 18, 0x01fd, 0x10e9, 0x6c00
ax_pose 19, 0x01fd, 0x10f1, 0x6c01
ax_pose 20, 0x81ed, 0x10f1, 0x6c02
ax_pose 21, 0x81e5, 0x50f9, 0x6c04
ax_pose 22, 0x81e5, 0x9101, 0x6c08
ax_pose_terminator
sHoundoomPose101:
ax_pose 72, 0x81e4, 0x90fb, 0x6c00
ax_pose 73, 0x01f4, 0x50eb, 0x6c08
ax_pose 74, 0x01ec, 0x10f3, 0x6c0c
ax_pose 75, 0x01dc, 0x1103, 0x6c0d
ax_pose_terminator
sHoundoomPose102:
ax_pose 48, 0x81e4, 0x110c, 0x6c00
ax_pose 49, 0x81e4, 0x5104, 0x6c02
ax_pose 50, 0x01dc, 0x1104, 0x6c06
ax_pose 51, 0x01f4, 0x50f4, 0x6c07
ax_pose 52, 0x41ec, 0x10f4, 0x6c0b
ax_pose 53, 0x01f4, 0x10ec, 0x6c0d
ax_pose 54, 0x01fc, 0x10ec, 0x6c0e
ax_pose_terminator
sHoundoomPose103:
ax_pose 76, 0x81e4, 0x90fc, 0x6c00
ax_pose 77, 0x01ec, 0x10f4, 0x6c08
ax_pose 78, 0x81f4, 0x10ec, 0x6c09
ax_pose 79, 0x41dc, 0x10fc, 0x6c0b
ax_pose 80, 0x81f4, 0x10f4, 0x6c0d
ax_pose_terminator
sHoundoomPose104:
ax_pose 24, 0x0202, 0x10f1, 0x6c00
ax_pose 25, 0x0202, 0x10f9, 0x6c01
ax_pose 26, 0x01fa, 0x10ed, 0x6c02
ax_pose 27, 0x81e2, 0x50f5, 0x6c03
ax_pose 28, 0x81e2, 0x90fd, 0x6c07
ax_pose_terminator
sHoundoomPose105:
ax_pose 29, 0x0202, 0x10fa, 0x6c00
ax_pose 30, 0x0202, 0x10f2, 0x6c01
ax_pose 31, 0x81f2, 0x10ed, 0x6c02
ax_pose 32, 0x81e2, 0x50f5, 0x6c04
ax_pose 33, 0x81e2, 0x90fd, 0x6c08
ax_pose_terminator
sHoundoomPose106:
ax_pose 81, 0x81e2, 0x90fb, 0x6c00
ax_pose 82, 0x01f2, 0x50eb, 0x6c08
ax_pose 83, 0x01da, 0x1103, 0x6c0c
ax_pose 84, 0x4202, 0x10f3, 0x6c0d
ax_pose_terminator
sHoundoomPose107:
ax_pose 55, 0x81e1, 0x90ff, 0x6c00
ax_pose 56, 0x01f1, 0x50ef, 0x6c08
ax_pose 57, 0x0201, 0x10ef, 0x6c0c
ax_pose 58, 0x0201, 0x10f7, 0x6c0d
ax_pose 59, 0x81e1, 0x10f7, 0x6c0e
ax_pose_terminator
sHoundoomPose108:
ax_pose 85, 0x81e5, 0x90fd, 0x6c00
ax_pose 86, 0x01ed, 0x10f5, 0x6c08
ax_pose 87, 0x01f5, 0x50ed, 0x6c09
ax_pose 88, 0x41dd, 0x10f5, 0x6c0d
ax_pose_terminator
sHoundoomPose109:
ax_pose 38, 0x4202, 0x00f8, 0x6c00
ax_pose 39, 0x81e2, 0x80f8, 0x6c02
ax_pose_terminator
sHoundoomPose110:
ax_pose 40, 0x4202, 0x00f8, 0x6c00
ax_pose 41, 0x81e2, 0x80f8, 0x6c02
ax_pose_terminator
sHoundoomPose111:
ax_pose 89, 0x01df, 0x0100, 0x6c00
ax_pose 90, 0x01df, 0x00f8, 0x6c01
ax_pose 91, 0x81e7, 0x80f8, 0x6c02
ax_pose 92, 0x81e7, 0x0108, 0x6c0a
ax_pose_terminator
sHoundoomPose112:
ax_pose 60, 0x0201, 0x00f8, 0x6c00
ax_pose 61, 0x0201, 0x0100, 0x6c01
ax_pose 62, 0x81e1, 0x80f8, 0x6c02
ax_pose_terminator
sHoundoomPose113:
ax_pose 93, 0x81e1, 0x80f8, 0x6c00
ax_pose 94, 0x4201, 0x00f8, 0x6c08
ax_pose_terminator
sHoundoomPose114:
ax_pose 24, 0x0202, 0x0107, 0x6c00
ax_pose 25, 0x0202, 0x00ff, 0x6c01
ax_pose 26, 0x01fa, 0x010b, 0x6c02
ax_pose 27, 0x81e2, 0x4103, 0x6c03
ax_pose 28, 0x81e2, 0x80f3, 0x6c07
ax_pose_terminator
sHoundoomPose115:
ax_pose 29, 0x0202, 0x00fe, 0x6c00
ax_pose 30, 0x0202, 0x0106, 0x6c01
ax_pose 31, 0x81f2, 0x010b, 0x6c02
ax_pose 32, 0x81e2, 0x4103, 0x6c04
ax_pose 33, 0x81e2, 0x80f3, 0x6c08
ax_pose_terminator
sHoundoomPose116:
ax_pose 81, 0x81e2, 0x80f5, 0x6c00
ax_pose 82, 0x01f2, 0x4105, 0x6c08
ax_pose 83, 0x01da, 0x00f5, 0x6c0c
ax_pose 84, 0x4202, 0x00fd, 0x6c0d
ax_pose_terminator
sHoundoomPose117:
ax_pose 55, 0x81e1, 0x80f1, 0x6c00
ax_pose 56, 0x01f1, 0x4101, 0x6c08
ax_pose 57, 0x0201, 0x0109, 0x6c0c
ax_pose 58, 0x0201, 0x0101, 0x6c0d
ax_pose 59, 0x81e1, 0x0101, 0x6c0e
ax_pose_terminator
sHoundoomPose118:
ax_pose 85, 0x81e5, 0x80f3, 0x6c00
ax_pose 86, 0x01ed, 0x0103, 0x6c08
ax_pose 87, 0x01f5, 0x4103, 0x6c09
ax_pose 88, 0x41dd, 0x00fb, 0x6c0d
ax_pose_terminator
sHoundoomPose119:
ax_pose 13, 0x01fb, 0x010f, 0x6c00
ax_pose 14, 0x01ec, 0x0107, 0x6c01
ax_pose 15, 0x81f4, 0x0107, 0x6c02
ax_pose 16, 0x81e4, 0x40ff, 0x6c04
ax_pose 17, 0x81e4, 0x80ef, 0x6c08
ax_pose_terminator
sHoundoomPose120:
ax_pose 18, 0x01fd, 0x010f, 0x6c00
ax_pose 19, 0x01fd, 0x0107, 0x6c01
ax_pose 20, 0x81ed, 0x0107, 0x6c02
ax_pose 21, 0x81e5, 0x40ff, 0x6c04
ax_pose 22, 0x81e5, 0x80ef, 0x6c08
ax_pose_terminator
sHoundoomPose121:
ax_pose 72, 0x81e4, 0x80f5, 0x6c00
ax_pose 73, 0x01f4, 0x4105, 0x6c08
ax_pose 74, 0x01ec, 0x0105, 0x6c0c
ax_pose 75, 0x01dc, 0x00f5, 0x6c0d
ax_pose_terminator
sHoundoomPose122:
ax_pose 48, 0x81e4, 0x00ec, 0x6c00
ax_pose 49, 0x81e4, 0x40f4, 0x6c02
ax_pose 50, 0x01dc, 0x00f4, 0x6c06
ax_pose 51, 0x01f4, 0x40fc, 0x6c07
ax_pose 52, 0x41ec, 0x00fc, 0x6c0b
ax_pose 53, 0x01f4, 0x010c, 0x6c0d
ax_pose 54, 0x01fc, 0x010c, 0x6c0e
ax_pose_terminator
sHoundoomPose123:
ax_pose 76, 0x81e4, 0x80f4, 0x6c00
ax_pose 77, 0x01ec, 0x0104, 0x6c08
ax_pose 78, 0x81f4, 0x010c, 0x6c09
ax_pose 79, 0x41dc, 0x00f4, 0x6c0b
ax_pose 80, 0x81f4, 0x0104, 0x6c0d
ax_pose_terminator
sHoundoomPose124:
ax_pose 4, 0x0207, 0x00fa, 0x6c00
ax_pose 5, 0x81ef, 0x010a, 0x6c01
ax_pose 6, 0x81e7, 0x4102, 0x6c03
ax_pose 7, 0x81e7, 0x80f2, 0x6c07
ax_pose_terminator
sHoundoomPose125:
ax_pose 8, 0x01e7, 0x80f1, 0x6c00
ax_pose_terminator
sHoundoomPose126:
ax_pose 66, 0x01e8, 0x80f2, 0x6c00
ax_pose_terminator
sHoundoomPose127:
ax_pose 47, 0x01e8, 0x80f2, 0x6c00
ax_pose_terminator
sHoundoomPose128:
ax_pose 67, 0x81e6, 0x80f2, 0x6c00
ax_pose 68, 0x81e6, 0x4102, 0x6c08
ax_pose 69, 0x01de, 0x0102, 0x6c0c
ax_pose 70, 0x01de, 0x00fa, 0x6c0d
ax_pose 71, 0x01f6, 0x010a, 0x6c0e
ax_pose_terminator
sHoundoomPose129:
ax_pose 0, 0x01e7, 0x0107, 0x6c00
ax_pose 1, 0x81e7, 0x80f7, 0x6c01
ax_pose_terminator
sHoundoomPose130:
ax_pose 63, 0x01e6, 0x80f7, 0x6c00
ax_pose_terminator
sHoundoomPose131:
ax_pose 4, 0x0207, 0x10fe, 0x6c00
ax_pose 5, 0x81ef, 0x10ee, 0x6c01
ax_pose 6, 0x81e7, 0x50f6, 0x6c03
ax_pose 7, 0x81e7, 0x90fe, 0x6c07
ax_pose_terminator
sHoundoomPose132:
ax_pose 66, 0x01e8, 0x90ee, 0x6c00
ax_pose_terminator
sHoundoomPose133:
ax_pose 13, 0x01fb, 0x10e9, 0x6c00
ax_pose 14, 0x01ec, 0x10f1, 0x6c01
ax_pose 15, 0x81f4, 0x10f1, 0x6c02
ax_pose 16, 0x81e4, 0x50f9, 0x6c04
ax_pose 17, 0x81e4, 0x9101, 0x6c08
ax_pose_terminator
sHoundoomPose134:
ax_pose 72, 0x81e4, 0x90fb, 0x6c00
ax_pose 73, 0x01f4, 0x50eb, 0x6c08
ax_pose 74, 0x01ec, 0x10f3, 0x6c0c
ax_pose 75, 0x01dc, 0x1103, 0x6c0d
ax_pose_terminator
sHoundoomPose135:
ax_pose 24, 0x0202, 0x10f1, 0x6c00
ax_pose 25, 0x0202, 0x10f9, 0x6c01
ax_pose 26, 0x01fa, 0x10ed, 0x6c02
ax_pose 27, 0x81e2, 0x50f5, 0x6c03
ax_pose 28, 0x81e2, 0x90fd, 0x6c07
ax_pose_terminator
sHoundoomPose136:
ax_pose 81, 0x81e2, 0x90fb, 0x6c00
ax_pose 82, 0x01f2, 0x50eb, 0x6c08
ax_pose 83, 0x01da, 0x1103, 0x6c0c
ax_pose 84, 0x4202, 0x10f3, 0x6c0d
ax_pose_terminator
sHoundoomPose137:
ax_pose 38, 0x4202, 0x00f8, 0x6c00
ax_pose 39, 0x81e2, 0x80f8, 0x6c02
ax_pose_terminator
sHoundoomPose138:
ax_pose 89, 0x01df, 0x0100, 0x6c00
ax_pose 90, 0x01df, 0x00f8, 0x6c01
ax_pose 91, 0x81e7, 0x80f8, 0x6c02
ax_pose 92, 0x81e7, 0x0108, 0x6c0a
ax_pose_terminator
sHoundoomPose139:
ax_pose 24, 0x0202, 0x0107, 0x6c00
ax_pose 25, 0x0202, 0x00ff, 0x6c01
ax_pose 26, 0x01fa, 0x010b, 0x6c02
ax_pose 27, 0x81e2, 0x4103, 0x6c03
ax_pose 28, 0x81e2, 0x80f3, 0x6c07
ax_pose_terminator
sHoundoomPose140:
ax_pose 81, 0x81e2, 0x80f5, 0x6c00
ax_pose 82, 0x01f2, 0x4105, 0x6c08
ax_pose 83, 0x01da, 0x00f5, 0x6c0c
ax_pose 84, 0x4202, 0x00fd, 0x6c0d
ax_pose_terminator
sHoundoomPose141:
ax_pose 13, 0x01fb, 0x010f, 0x6c00
ax_pose 14, 0x01ec, 0x0107, 0x6c01
ax_pose 15, 0x81f4, 0x0107, 0x6c02
ax_pose 16, 0x81e4, 0x40ff, 0x6c04
ax_pose 17, 0x81e4, 0x80ef, 0x6c08
ax_pose_terminator
sHoundoomPose142:
ax_pose 72, 0x81e4, 0x80f5, 0x6c00
ax_pose 73, 0x01f4, 0x4105, 0x6c08
ax_pose 74, 0x01ec, 0x0105, 0x6c0c
ax_pose 75, 0x01dc, 0x00f5, 0x6c0d
ax_pose_terminator
sHoundoomPose143:
ax_pose 4, 0x0207, 0x00fa, 0x6c00
ax_pose 5, 0x81ef, 0x010a, 0x6c01
ax_pose 6, 0x81e7, 0x4102, 0x6c03
ax_pose 7, 0x81e7, 0x80f2, 0x6c07
ax_pose_terminator
sHoundoomPose144:
ax_pose 66, 0x01e8, 0x80f2, 0x6c00
ax_pose_terminator
sHoundoomPose145:
ax_pose 95, 0x01ec, 0x80f3, 0x6c00
ax_pose_terminator
sHoundoomPose146:
ax_pose 96, 0x01ec, 0x80f3, 0x6c00
ax_pose_terminator
sHoundoomPose147:
ax_pose 97, 0x81e7, 0x80f4, 0x6c00
ax_pose 98, 0x81e7, 0x4104, 0x6c08
ax_pose 99, 0x01e7, 0x010c, 0x6c0c
ax_pose 100, 0x01df, 0x0100, 0x6c0d
ax_pose_terminator
sHoundoomPose148:
ax_pose 101, 0x01e6, 0x90f1, 0x6c00
ax_pose_terminator
sHoundoomPose149:
ax_pose 102, 0x01e4, 0x90f1, 0x6c00
ax_pose_terminator
sHoundoomPose150:
ax_pose 103, 0x81e5, 0x90fe, 0x6c00
ax_pose 104, 0x01e2, 0x10f6, 0x6c08
ax_pose 105, 0x0205, 0x10f7, 0x6c09
ax_pose 106, 0x41ed, 0x10ee, 0x6c0a
ax_pose 107, 0x01f5, 0x50ee, 0x6c0c
ax_pose_terminator
sHoundoomPose151:
ax_pose 108, 0x0201, 0x00f5, 0x6c00
ax_pose -1, 0x0201, 0x1102, 0x6c00
ax_pose 109, 0x81e6, 0x80f1, 0x6c01
ax_pose 110, 0x81e6, 0x4101, 0x6c09
ax_pose_terminator
sHoundoomPose152:
ax_pose 103, 0x81e5, 0x80f1, 0x6c00
ax_pose 104, 0x01e2, 0x0101, 0x6c08
ax_pose 105, 0x0205, 0x0100, 0x6c09
ax_pose 106, 0x41ed, 0x0101, 0x6c0a
ax_pose 107, 0x01f5, 0x4101, 0x6c0c
ax_pose_terminator
sHoundoomPose153:
ax_pose 102, 0x01e4, 0x80f0, 0x6c00
ax_pose_terminator
sHoundoomPose154:
ax_pose 101, 0x01e6, 0x80f1, 0x6c00
ax_pose_terminator
sHoundoomPose155:
ax_pose 0, 0x01e7, 0x0107, 0x6c00
ax_pose 1, 0x81e7, 0x80f7, 0x6c01
ax_pose_terminator
sHoundoomPose156:
ax_pose 2, 0x01ea, 0x80f7, 0x6c00
ax_pose_terminator
sHoundoomPose157:
ax_pose 63, 0x01e6, 0x80f7, 0x6c00
ax_pose_terminator
sHoundoomPose158:
ax_pose 46, 0x01e7, 0x80f7, 0x6c00
ax_pose_terminator
sHoundoomPose159:
ax_pose 64, 0x81e5, 0x80f7, 0x6c00
ax_pose 65, 0x01e5, 0x0107, 0x6c08
ax_pose_terminator
sHoundoomPose160:
ax_pose 4, 0x0207, 0x10fe, 0x6c00
ax_pose 5, 0x81ef, 0x10ee, 0x6c01
ax_pose 6, 0x81e7, 0x50f6, 0x6c03
ax_pose 7, 0x81e7, 0x90fe, 0x6c07
ax_pose_terminator
sHoundoomPose161:
ax_pose 8, 0x01e7, 0x90ef, 0x6c00
ax_pose_terminator
sHoundoomPose162:
ax_pose 66, 0x01e8, 0x90ee, 0x6c00
ax_pose_terminator
sHoundoomPose163:
ax_pose 47, 0x01e8, 0x90ee, 0x6c00
ax_pose_terminator
sHoundoomPose164:
ax_pose 67, 0x81e6, 0x90fe, 0x6c00
ax_pose 68, 0x81e6, 0x50f6, 0x6c08
ax_pose 69, 0x01de, 0x10f6, 0x6c0c
ax_pose 70, 0x01de, 0x10fe, 0x6c0d
ax_pose 71, 0x01f6, 0x10ee, 0x6c0e
ax_pose_terminator
sHoundoomPose165:
ax_pose 13, 0x01fb, 0x10e9, 0x6c00
ax_pose 14, 0x01ec, 0x10f1, 0x6c01
ax_pose 15, 0x81f4, 0x10f1, 0x6c02
ax_pose 16, 0x81e4, 0x50f9, 0x6c04
ax_pose 17, 0x81e4, 0x9101, 0x6c08
ax_pose_terminator
sHoundoomPose166:
ax_pose 18, 0x01fd, 0x10e9, 0x6c00
ax_pose 19, 0x01fd, 0x10f1, 0x6c01
ax_pose 20, 0x81ed, 0x10f1, 0x6c02
ax_pose 21, 0x81e5, 0x50f9, 0x6c04
ax_pose 22, 0x81e5, 0x9101, 0x6c08
ax_pose_terminator
sHoundoomPose167:
ax_pose 72, 0x81e4, 0x90fb, 0x6c00
ax_pose 73, 0x01f4, 0x50eb, 0x6c08
ax_pose 74, 0x01ec, 0x10f3, 0x6c0c
ax_pose 75, 0x01dc, 0x1103, 0x6c0d
ax_pose_terminator
sHoundoomPose168:
ax_pose 48, 0x81e4, 0x110c, 0x6c00
ax_pose 49, 0x81e4, 0x5104, 0x6c02
ax_pose 50, 0x01dc, 0x1104, 0x6c06
ax_pose 51, 0x01f4, 0x50f4, 0x6c07
ax_pose 52, 0x41ec, 0x10f4, 0x6c0b
ax_pose 53, 0x01f4, 0x10ec, 0x6c0d
ax_pose 54, 0x01fc, 0x10ec, 0x6c0e
ax_pose_terminator
sHoundoomPose169:
ax_pose 76, 0x81e4, 0x90fc, 0x6c00
ax_pose 77, 0x01ec, 0x10f4, 0x6c08
ax_pose 78, 0x81f4, 0x10ec, 0x6c09
ax_pose 79, 0x41dc, 0x10fc, 0x6c0b
ax_pose 80, 0x81f4, 0x10f4, 0x6c0d
ax_pose_terminator
sHoundoomPose170:
ax_pose 24, 0x0202, 0x10f1, 0x6c00
ax_pose 25, 0x0202, 0x10f9, 0x6c01
ax_pose 26, 0x01fa, 0x10ed, 0x6c02
ax_pose 27, 0x81e2, 0x50f5, 0x6c03
ax_pose 28, 0x81e2, 0x90fd, 0x6c07
ax_pose_terminator
sHoundoomPose171:
ax_pose 29, 0x0202, 0x10fa, 0x6c00
ax_pose 30, 0x0202, 0x10f2, 0x6c01
ax_pose 31, 0x81f2, 0x10ed, 0x6c02
ax_pose 32, 0x81e2, 0x50f5, 0x6c04
ax_pose 33, 0x81e2, 0x90fd, 0x6c08
ax_pose_terminator
sHoundoomPose172:
ax_pose 81, 0x81e2, 0x90fb, 0x6c00
ax_pose 82, 0x01f2, 0x50eb, 0x6c08
ax_pose 83, 0x01da, 0x1103, 0x6c0c
ax_pose 84, 0x4202, 0x10f3, 0x6c0d
ax_pose_terminator
sHoundoomPose173:
ax_pose 55, 0x81e1, 0x90ff, 0x6c00
ax_pose 56, 0x01f1, 0x50ef, 0x6c08
ax_pose 57, 0x0201, 0x10ef, 0x6c0c
ax_pose 58, 0x0201, 0x10f7, 0x6c0d
ax_pose 59, 0x81e1, 0x10f7, 0x6c0e
ax_pose_terminator
sHoundoomPose174:
ax_pose 85, 0x81e5, 0x90fd, 0x6c00
ax_pose 86, 0x01ed, 0x10f5, 0x6c08
ax_pose 87, 0x01f5, 0x50ed, 0x6c09
ax_pose 88, 0x41dd, 0x10f5, 0x6c0d
ax_pose_terminator
sHoundoomPose175:
ax_pose 38, 0x4202, 0x00f8, 0x6c00
ax_pose 39, 0x81e2, 0x80f8, 0x6c02
ax_pose_terminator
sHoundoomPose176:
ax_pose 40, 0x4202, 0x00f8, 0x6c00
ax_pose 41, 0x81e2, 0x80f8, 0x6c02
ax_pose_terminator
sHoundoomPose177:
ax_pose 89, 0x01df, 0x0100, 0x6c00
ax_pose 90, 0x01df, 0x00f8, 0x6c01
ax_pose 91, 0x81e7, 0x80f8, 0x6c02
ax_pose 92, 0x81e7, 0x0108, 0x6c0a
ax_pose_terminator
sHoundoomPose178:
ax_pose 60, 0x0201, 0x00f8, 0x6c00
ax_pose 61, 0x0201, 0x0100, 0x6c01
ax_pose 62, 0x81e1, 0x80f8, 0x6c02
ax_pose_terminator
sHoundoomPose179:
ax_pose 93, 0x81e1, 0x80f8, 0x6c00
ax_pose 94, 0x4201, 0x00f8, 0x6c08
ax_pose_terminator
sHoundoomPose180:
ax_pose 24, 0x0202, 0x0107, 0x6c00
ax_pose 25, 0x0202, 0x00ff, 0x6c01
ax_pose 26, 0x01fa, 0x010b, 0x6c02
ax_pose 27, 0x81e2, 0x4103, 0x6c03
ax_pose 28, 0x81e2, 0x80f3, 0x6c07
ax_pose_terminator
sHoundoomPose181:
ax_pose 29, 0x0202, 0x00fe, 0x6c00
ax_pose 30, 0x0202, 0x0106, 0x6c01
ax_pose 31, 0x81f2, 0x010b, 0x6c02
ax_pose 32, 0x81e2, 0x4103, 0x6c04
ax_pose 33, 0x81e2, 0x80f3, 0x6c08
ax_pose_terminator
sHoundoomPose182:
ax_pose 81, 0x81e2, 0x80f5, 0x6c00
ax_pose 82, 0x01f2, 0x4105, 0x6c08
ax_pose 83, 0x01da, 0x00f5, 0x6c0c
ax_pose 84, 0x4202, 0x00fd, 0x6c0d
ax_pose_terminator
sHoundoomPose183:
ax_pose 55, 0x81e1, 0x80f1, 0x6c00
ax_pose 56, 0x01f1, 0x4101, 0x6c08
ax_pose 57, 0x0201, 0x0109, 0x6c0c
ax_pose 58, 0x0201, 0x0101, 0x6c0d
ax_pose 59, 0x81e1, 0x0101, 0x6c0e
ax_pose_terminator
sHoundoomPose184:
ax_pose 85, 0x81e5, 0x80f3, 0x6c00
ax_pose 86, 0x01ed, 0x0103, 0x6c08
ax_pose 87, 0x01f5, 0x4103, 0x6c09
ax_pose 88, 0x41dd, 0x00fb, 0x6c0d
ax_pose_terminator
sHoundoomPose185:
ax_pose 13, 0x01fb, 0x010f, 0x6c00
ax_pose 14, 0x01ec, 0x0107, 0x6c01
ax_pose 15, 0x81f4, 0x0107, 0x6c02
ax_pose 16, 0x81e4, 0x40ff, 0x6c04
ax_pose 17, 0x81e4, 0x80ef, 0x6c08
ax_pose_terminator
sHoundoomPose186:
ax_pose 18, 0x01fd, 0x010f, 0x6c00
ax_pose 19, 0x01fd, 0x0107, 0x6c01
ax_pose 20, 0x81ed, 0x0107, 0x6c02
ax_pose 21, 0x81e5, 0x40ff, 0x6c04
ax_pose 22, 0x81e5, 0x80ef, 0x6c08
ax_pose_terminator
sHoundoomPose187:
ax_pose 72, 0x81e4, 0x80f5, 0x6c00
ax_pose 73, 0x01f4, 0x4105, 0x6c08
ax_pose 74, 0x01ec, 0x0105, 0x6c0c
ax_pose 75, 0x01dc, 0x00f5, 0x6c0d
ax_pose_terminator
sHoundoomPose188:
ax_pose 48, 0x81e4, 0x00ec, 0x6c00
ax_pose 49, 0x81e4, 0x40f4, 0x6c02
ax_pose 50, 0x01dc, 0x00f4, 0x6c06
ax_pose 51, 0x01f4, 0x40fc, 0x6c07
ax_pose 52, 0x41ec, 0x00fc, 0x6c0b
ax_pose 53, 0x01f4, 0x010c, 0x6c0d
ax_pose 54, 0x01fc, 0x010c, 0x6c0e
ax_pose_terminator
sHoundoomPose189:
ax_pose 76, 0x81e4, 0x80f4, 0x6c00
ax_pose 77, 0x01ec, 0x0104, 0x6c08
ax_pose 78, 0x81f4, 0x010c, 0x6c09
ax_pose 79, 0x41dc, 0x00f4, 0x6c0b
ax_pose 80, 0x81f4, 0x0104, 0x6c0d
ax_pose_terminator
sHoundoomPose190:
ax_pose 4, 0x0207, 0x00fa, 0x6c00
ax_pose 5, 0x81ef, 0x010a, 0x6c01
ax_pose 6, 0x81e7, 0x4102, 0x6c03
ax_pose 7, 0x81e7, 0x80f2, 0x6c07
ax_pose_terminator
sHoundoomPose191:
ax_pose 8, 0x01e7, 0x80f1, 0x6c00
ax_pose_terminator
sHoundoomPose192:
ax_pose 66, 0x01e8, 0x80f2, 0x6c00
ax_pose_terminator
sHoundoomPose193:
ax_pose 47, 0x01e8, 0x80f2, 0x6c00
ax_pose_terminator
sHoundoomPose194:
ax_pose 67, 0x81e6, 0x80f2, 0x6c00
ax_pose 68, 0x81e6, 0x4102, 0x6c08
ax_pose 69, 0x01de, 0x0102, 0x6c0c
ax_pose 70, 0x01de, 0x00fa, 0x6c0d
ax_pose 71, 0x01f6, 0x010a, 0x6c0e
ax_pose_terminator
sHoundoomPose195:
ax_pose 46, 0x01e7, 0x80f7, 0x6c00
ax_pose_terminator
sHoundoomPose196:
ax_pose 47, 0x01e8, 0x80f2, 0x6c00
ax_pose_terminator
sHoundoomPose197:
ax_pose 48, 0x81e4, 0x00ec, 0x6c00
ax_pose 49, 0x81e4, 0x40f4, 0x6c02
ax_pose 50, 0x01dc, 0x00f4, 0x6c06
ax_pose 51, 0x01f4, 0x40fc, 0x6c07
ax_pose 52, 0x41ec, 0x00fc, 0x6c0b
ax_pose 53, 0x01f4, 0x010c, 0x6c0d
ax_pose 54, 0x01fc, 0x010c, 0x6c0e
ax_pose_terminator
sHoundoomPose198:
ax_pose 55, 0x81e1, 0x80f1, 0x6c00
ax_pose 56, 0x01f1, 0x4101, 0x6c08
ax_pose 57, 0x0201, 0x0109, 0x6c0c
ax_pose 58, 0x0201, 0x0101, 0x6c0d
ax_pose 59, 0x81e1, 0x0101, 0x6c0e
ax_pose_terminator
sHoundoomPose199:
ax_pose 60, 0x0201, 0x00f8, 0x6c00
ax_pose 61, 0x0201, 0x0100, 0x6c01
ax_pose 62, 0x81e1, 0x80f8, 0x6c02
ax_pose_terminator
sHoundoomPose200:
ax_pose 55, 0x81e1, 0x90ff, 0x6c00
ax_pose 56, 0x01f1, 0x50ef, 0x6c08
ax_pose 57, 0x0201, 0x10ef, 0x6c0c
ax_pose 58, 0x0201, 0x10f7, 0x6c0d
ax_pose 59, 0x81e1, 0x10f7, 0x6c0e
ax_pose_terminator
sHoundoomPose201:
ax_pose 48, 0x81e4, 0x110c, 0x6c00
ax_pose 49, 0x81e4, 0x5104, 0x6c02
ax_pose 50, 0x01dc, 0x1104, 0x6c06
ax_pose 51, 0x01f4, 0x50f4, 0x6c07
ax_pose 52, 0x41ec, 0x10f4, 0x6c0b
ax_pose 53, 0x01f4, 0x10ec, 0x6c0d
ax_pose 54, 0x01fc, 0x10ec, 0x6c0e
ax_pose_terminator
sHoundoomPose202:
ax_pose 47, 0x01e8, 0x90ee, 0x6c00
ax_pose_terminator
sHoundoomPose203:
ax_pose 63, 0x01e7, 0x80f7, 0x6c00
ax_pose_terminator
sHoundoomPose204:
ax_pose 66, 0x01e7, 0x90ee, 0x6c00
ax_pose_terminator
sHoundoomPose205:
ax_pose 72, 0x81e4, 0x90fc, 0x6c00
ax_pose 73, 0x01f4, 0x50ec, 0x6c08
ax_pose 74, 0x01ec, 0x10f4, 0x6c0c
ax_pose 75, 0x01dc, 0x1104, 0x6c0d
ax_pose_terminator
sHoundoomPose206:
ax_pose 81, 0x81e3, 0x90fc, 0x6c00
ax_pose 82, 0x01f3, 0x50ec, 0x6c08
ax_pose 83, 0x01db, 0x1104, 0x6c0c
ax_pose 84, 0x4203, 0x10f4, 0x6c0d
ax_pose_terminator
sHoundoomPose207:
ax_pose 89, 0x01e0, 0x0100, 0x6c00
ax_pose 90, 0x01e0, 0x00f8, 0x6c01
ax_pose 91, 0x81e8, 0x80f8, 0x6c02
ax_pose 92, 0x81e8, 0x0108, 0x6c0a
ax_pose_terminator
sHoundoomPose208:
ax_pose 81, 0x81e3, 0x80f4, 0x6c00
ax_pose 82, 0x01f3, 0x4104, 0x6c08
ax_pose 83, 0x01db, 0x00f4, 0x6c0c
ax_pose 84, 0x4203, 0x00fc, 0x6c0d
ax_pose_terminator
sHoundoomPose209:
ax_pose 72, 0x81e4, 0x80f4, 0x6c00
ax_pose 73, 0x01f4, 0x4104, 0x6c08
ax_pose 74, 0x01ec, 0x0104, 0x6c0c
ax_pose 75, 0x01dc, 0x00f4, 0x6c0d
ax_pose_terminator
sHoundoomPose210:
ax_pose 66, 0x01e7, 0x80f2, 0x6c00
ax_pose_terminator
sHoundoomPose211:
ax_pose 0, 0x01e7, 0x0107, 0x6c00
ax_pose 1, 0x81e7, 0x80f7, 0x6c01
ax_pose_terminator
sHoundoomPose212:
ax_pose 63, 0x01e6, 0x80f7, 0x6c00
ax_pose_terminator
sHoundoomPose213:
ax_pose 46, 0x01e7, 0x80f7, 0x6c00
ax_pose_terminator
sHoundoomPose214:
ax_pose 4, 0x0207, 0x10fe, 0x6c00
ax_pose 5, 0x81ef, 0x10ee, 0x6c01
ax_pose 6, 0x81e7, 0x50f6, 0x6c03
ax_pose 7, 0x81e7, 0x90fe, 0x6c07
ax_pose_terminator
sHoundoomPose215:
ax_pose 66, 0x01e8, 0x90ee, 0x6c00
ax_pose_terminator
sHoundoomPose216:
ax_pose 47, 0x01e8, 0x90ee, 0x6c00
ax_pose_terminator
sHoundoomPose217:
ax_pose 13, 0x01fb, 0x10e9, 0x6c00
ax_pose 14, 0x01ec, 0x10f1, 0x6c01
ax_pose 15, 0x81f4, 0x10f1, 0x6c02
ax_pose 16, 0x81e4, 0x50f9, 0x6c04
ax_pose 17, 0x81e4, 0x9101, 0x6c08
ax_pose_terminator
sHoundoomPose218:
ax_pose 72, 0x81e4, 0x90fb, 0x6c00
ax_pose 73, 0x01f4, 0x50eb, 0x6c08
ax_pose 74, 0x01ec, 0x10f3, 0x6c0c
ax_pose 75, 0x01dc, 0x1103, 0x6c0d
ax_pose_terminator
sHoundoomPose219:
ax_pose 48, 0x81e4, 0x110b, 0x6c00
ax_pose 49, 0x81e4, 0x5103, 0x6c02
ax_pose 50, 0x01dc, 0x1103, 0x6c06
ax_pose 51, 0x01f4, 0x50f3, 0x6c07
ax_pose 52, 0x41ec, 0x10f3, 0x6c0b
ax_pose 53, 0x01f4, 0x10eb, 0x6c0d
ax_pose 54, 0x01fc, 0x10eb, 0x6c0e
ax_pose_terminator
sHoundoomPose220:
ax_pose 24, 0x0202, 0x10f1, 0x6c00
ax_pose 25, 0x0202, 0x10f9, 0x6c01
ax_pose 26, 0x01fa, 0x10ed, 0x6c02
ax_pose 27, 0x81e2, 0x50f5, 0x6c03
ax_pose 28, 0x81e2, 0x90fd, 0x6c07
ax_pose_terminator
sHoundoomPose221:
ax_pose 81, 0x81e2, 0x90fb, 0x6c00
ax_pose 82, 0x01f2, 0x50eb, 0x6c08
ax_pose 83, 0x01da, 0x1103, 0x6c0c
ax_pose 84, 0x4202, 0x10f3, 0x6c0d
ax_pose_terminator
sHoundoomPose222:
ax_pose 55, 0x81e1, 0x90fe, 0x6c00
ax_pose 56, 0x01f1, 0x50ee, 0x6c08
ax_pose 57, 0x0201, 0x10ee, 0x6c0c
ax_pose 58, 0x0201, 0x10f6, 0x6c0d
ax_pose 59, 0x81e1, 0x10f6, 0x6c0e
ax_pose_terminator
sHoundoomPose223:
ax_pose 38, 0x4202, 0x00f8, 0x6c00
ax_pose 39, 0x81e2, 0x80f8, 0x6c02
ax_pose_terminator
sHoundoomPose224:
ax_pose 89, 0x01df, 0x0100, 0x6c00
ax_pose 90, 0x01df, 0x00f8, 0x6c01
ax_pose 91, 0x81e7, 0x80f8, 0x6c02
ax_pose 92, 0x81e7, 0x0108, 0x6c0a
ax_pose_terminator
sHoundoomPose225:
ax_pose 60, 0x0201, 0x00f8, 0x6c00
ax_pose 61, 0x0201, 0x0100, 0x6c01
ax_pose 62, 0x81e1, 0x80f8, 0x6c02
ax_pose_terminator
sHoundoomPose226:
ax_pose 24, 0x0202, 0x0107, 0x6c00
ax_pose 25, 0x0202, 0x00ff, 0x6c01
ax_pose 26, 0x01fa, 0x010b, 0x6c02
ax_pose 27, 0x81e2, 0x4103, 0x6c03
ax_pose 28, 0x81e2, 0x80f3, 0x6c07
ax_pose_terminator
sHoundoomPose227:
ax_pose 81, 0x81e2, 0x80f5, 0x6c00
ax_pose 82, 0x01f2, 0x4105, 0x6c08
ax_pose 83, 0x01da, 0x00f5, 0x6c0c
ax_pose 84, 0x4202, 0x00fd, 0x6c0d
ax_pose_terminator
sHoundoomPose228:
ax_pose 55, 0x81e1, 0x80f2, 0x6c00
ax_pose 56, 0x01f1, 0x4102, 0x6c08
ax_pose 57, 0x0201, 0x010a, 0x6c0c
ax_pose 58, 0x0201, 0x0102, 0x6c0d
ax_pose 59, 0x81e1, 0x0102, 0x6c0e
ax_pose_terminator
sHoundoomPose229:
ax_pose 13, 0x01fb, 0x010f, 0x6c00
ax_pose 14, 0x01ec, 0x0107, 0x6c01
ax_pose 15, 0x81f4, 0x0107, 0x6c02
ax_pose 16, 0x81e4, 0x40ff, 0x6c04
ax_pose 17, 0x81e4, 0x80ef, 0x6c08
ax_pose_terminator
sHoundoomPose230:
ax_pose 72, 0x81e4, 0x80f5, 0x6c00
ax_pose 73, 0x01f4, 0x4105, 0x6c08
ax_pose 74, 0x01ec, 0x0105, 0x6c0c
ax_pose 75, 0x01dc, 0x00f5, 0x6c0d
ax_pose_terminator
sHoundoomPose231:
ax_pose 48, 0x81e4, 0x00ed, 0x6c00
ax_pose 49, 0x81e4, 0x40f5, 0x6c02
ax_pose 50, 0x01dc, 0x00f5, 0x6c06
ax_pose 51, 0x01f4, 0x40fd, 0x6c07
ax_pose 52, 0x41ec, 0x00fd, 0x6c0b
ax_pose 53, 0x01f4, 0x010d, 0x6c0d
ax_pose 54, 0x01fc, 0x010d, 0x6c0e
ax_pose_terminator
sHoundoomPose232:
ax_pose 4, 0x0207, 0x00fa, 0x6c00
ax_pose 5, 0x81ef, 0x010a, 0x6c01
ax_pose 6, 0x81e7, 0x4102, 0x6c03
ax_pose 7, 0x81e7, 0x80f2, 0x6c07
ax_pose_terminator
sHoundoomPose233:
ax_pose 66, 0x01e8, 0x80f2, 0x6c00
ax_pose_terminator
sHoundoomPose234:
ax_pose 47, 0x01e8, 0x80f2, 0x6c00
ax_pose_terminator
sHoundoomPose235:
ax_pose 46, 0x01e7, 0x80f7, 0x6c00
ax_pose_terminator
sHoundoomPose236:
ax_pose 47, 0x01e8, 0x80f2, 0x6c00
ax_pose_terminator
sHoundoomPose237:
ax_pose 48, 0x81e4, 0x00ec, 0x6c00
ax_pose 49, 0x81e4, 0x40f4, 0x6c02
ax_pose 50, 0x01dc, 0x00f4, 0x6c06
ax_pose 51, 0x01f4, 0x40fc, 0x6c07
ax_pose 52, 0x41ec, 0x00fc, 0x6c0b
ax_pose 53, 0x01f4, 0x010c, 0x6c0d
ax_pose 54, 0x01fc, 0x010c, 0x6c0e
ax_pose_terminator
sHoundoomPose238:
ax_pose 55, 0x81e1, 0x80f1, 0x6c00
ax_pose 56, 0x01f1, 0x4101, 0x6c08
ax_pose 57, 0x0201, 0x0109, 0x6c0c
ax_pose 58, 0x0201, 0x0101, 0x6c0d
ax_pose 59, 0x81e1, 0x0101, 0x6c0e
ax_pose_terminator
sHoundoomPose239:
ax_pose 60, 0x0201, 0x00f8, 0x6c00
ax_pose 61, 0x0201, 0x0100, 0x6c01
ax_pose 62, 0x81e1, 0x80f8, 0x6c02
ax_pose_terminator
sHoundoomPose240:
ax_pose 55, 0x81e1, 0x90ff, 0x6c00
ax_pose 56, 0x01f1, 0x50ef, 0x6c08
ax_pose 57, 0x0201, 0x10ef, 0x6c0c
ax_pose 58, 0x0201, 0x10f7, 0x6c0d
ax_pose 59, 0x81e1, 0x10f7, 0x6c0e
ax_pose_terminator
sHoundoomPose241:
ax_pose 48, 0x81e4, 0x110c, 0x6c00
ax_pose 49, 0x81e4, 0x5104, 0x6c02
ax_pose 50, 0x01dc, 0x1104, 0x6c06
ax_pose 51, 0x01f4, 0x50f4, 0x6c07
ax_pose 52, 0x41ec, 0x10f4, 0x6c0b
ax_pose 53, 0x01f4, 0x10ec, 0x6c0d
ax_pose 54, 0x01fc, 0x10ec, 0x6c0e
ax_pose_terminator
sHoundoomPose242:
ax_pose 47, 0x01e8, 0x90ee, 0x6c00
ax_pose_terminator
sHoundoomPose243:
ax_pose 0, 0x01e7, 0x0107, 0x6c00
ax_pose 1, 0x81e7, 0x80f7, 0x6c01
ax_pose_terminator
sHoundoomPose244:
ax_pose 4, 0x0207, 0x00fa, 0x6c00
ax_pose 5, 0x81ef, 0x010a, 0x6c01
ax_pose 6, 0x81e7, 0x4102, 0x6c03
ax_pose 7, 0x81e7, 0x80f2, 0x6c07
ax_pose_terminator
sHoundoomPose245:
ax_pose 13, 0x01fb, 0x010f, 0x6c00
ax_pose 14, 0x01ec, 0x0107, 0x6c01
ax_pose 15, 0x81f4, 0x0107, 0x6c02
ax_pose 16, 0x81e4, 0x40ff, 0x6c04
ax_pose 17, 0x81e4, 0x80ef, 0x6c08
ax_pose_terminator
sHoundoomPose246:
ax_pose 24, 0x0202, 0x0107, 0x6c00
ax_pose 25, 0x0202, 0x00ff, 0x6c01
ax_pose 26, 0x01fa, 0x010b, 0x6c02
ax_pose 27, 0x81e2, 0x4103, 0x6c03
ax_pose 28, 0x81e2, 0x80f3, 0x6c07
ax_pose_terminator
sHoundoomPose247:
ax_pose 38, 0x4202, 0x00f8, 0x6c00
ax_pose 39, 0x81e2, 0x80f8, 0x6c02
ax_pose_terminator
sHoundoomPose248:
ax_pose 24, 0x0202, 0x10f1, 0x6c00
ax_pose 25, 0x0202, 0x10f9, 0x6c01
ax_pose 26, 0x01fa, 0x10ed, 0x6c02
ax_pose 27, 0x81e2, 0x50f5, 0x6c03
ax_pose 28, 0x81e2, 0x90fd, 0x6c07
ax_pose_terminator
sHoundoomPose249:
ax_pose 13, 0x01fb, 0x10e9, 0x6c00
ax_pose 14, 0x01ec, 0x10f1, 0x6c01
ax_pose 15, 0x81f4, 0x10f1, 0x6c02
ax_pose 16, 0x81e4, 0x50f9, 0x6c04
ax_pose 17, 0x81e4, 0x9101, 0x6c08
ax_pose_terminator
sHoundoomPose250:
ax_pose 4, 0x0207, 0x10fe, 0x6c00
ax_pose 5, 0x81ef, 0x10ee, 0x6c01
ax_pose 6, 0x81e7, 0x50f6, 0x6c03
ax_pose 7, 0x81e7, 0x90fe, 0x6c07
ax_pose_terminator
.align 2
sHoundoomAnims_1_1:
ax_anim 8, 0, 0, 0, 0, 0, 0,
ax_anim 12, 0, 1, 0, 0, 0, 0,
ax_anim 8, 0, 0, 0, 0, 0, 0,
ax_anim 12, 0, 2, 0, 0, 0, 0,
ax_anim_terminator
sHoundoomAnims_1_2:
ax_anim 8, 0, 3, 0, 0, 0, 0,
ax_anim 12, 0, 4, 0, 0, 0, 0,
ax_anim 8, 0, 3, 0, 0, 0, 0,
ax_anim 12, 0, 5, 0, 0, 0, 0,
ax_anim_terminator
sHoundoomAnims_1_3:
ax_anim 8, 0, 6, 0, 0, 0, 0,
ax_anim 12, 0, 7, 0, 0, 0, 0,
ax_anim 8, 0, 6, 0, 0, 0, 0,
ax_anim 12, 0, 8, 0, 0, 0, 0,
ax_anim_terminator
sHoundoomAnims_1_4:
ax_anim 8, 0, 9, 0, 0, 0, 0,
ax_anim 12, 0, 10, 0, 0, 0, 0,
ax_anim 8, 0, 9, 0, 0, 0, 0,
ax_anim 12, 0, 11, 0, 0, 0, 0,
ax_anim_terminator
sHoundoomAnims_1_5:
ax_anim 8, 0, 12, 0, 0, 0, 0,
ax_anim 12, 0, 13, 0, 0, 0, 0,
ax_anim 8, 0, 12, 0, 0, 0, 0,
ax_anim 12, 0, 14, 0, 0, 0, 0,
ax_anim_terminator
sHoundoomAnims_1_6:
ax_anim 8, 0, 15, 0, 0, 0, 0,
ax_anim 12, 0, 16, 0, 0, 0, 0,
ax_anim 8, 0, 15, 0, 0, 0, 0,
ax_anim 12, 0, 17, 0, 0, 0, 0,
ax_anim_terminator
sHoundoomAnims_1_7:
ax_anim 8, 0, 18, 0, 0, 0, 0,
ax_anim 12, 0, 19, 0, 0, 0, 0,
ax_anim 8, 0, 18, 0, 0, 0, 0,
ax_anim 12, 0, 20, 0, 0, 0, 0,
ax_anim_terminator
sHoundoomAnims_1_8:
ax_anim 8, 0, 21, 0, 0, 0, 0,
ax_anim 12, 0, 22, 0, 0, 0, 0,
ax_anim 8, 0, 21, 0, 0, 0, 0,
ax_anim 12, 0, 23, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sHoundoomAnims_2_1:
ax_anim 2, 0, 25, 0, -1, 0, -1,
ax_anim 4, 0, 25, 0, -2, 0, -2,
ax_anim 1, 0, 26, 0, 0, 0, 0,
ax_anim 1, 2, 26, 0, 4, 0, 4,
ax_anim 1, 0, 26, 0, 10, 0, 10,
ax_anim 2, 0, 27, 0, 16, 0, 16,
ax_anim 2, 1, 27, 1, 16, 1, 16,
ax_anim 2, 0, 27, 0, 16, 0, 16,
ax_anim 2, 0, 27, 1, 16, 1, 16,
ax_anim 2, 0, 24, 0, 6, 0, 6,
ax_anim_terminator
sHoundoomAnims_2_2:
ax_anim 2, 0, 29, -1, -1, -1, -1,
ax_anim 4, 0, 29, -2, -2, -2, -2,
ax_anim 1, 0, 30, 0, 0, 0, 0,
ax_anim 1, 2, 30, 4, 4, 4, 4,
ax_anim 1, 0, 30, 10, 10, 10, 10,
ax_anim 2, 0, 31, 16, 15, 16, 15,
ax_anim 2, 1, 31, 17, 14, 17, 14,
ax_anim 2, 0, 31, 16, 15, 16, 15,
ax_anim 2, 0, 31, 17, 14, 17, 14,
ax_anim 2, 0, 28, 6, 6, 6, 6,
ax_anim_terminator
sHoundoomAnims_2_3:
ax_anim 2, 0, 33, -1, 0, -1, 0,
ax_anim 4, 0, 33, -2, 0, -2, 0,
ax_anim 1, 0, 34, 0, 0, 0, 0,
ax_anim 1, 2, 34, 4, 0, 4, 0,
ax_anim 1, 0, 34, 6, 0, 6, 0,
ax_anim 2, 0, 35, 11, 0, 11, 0,
ax_anim 2, 1, 35, 11, 1, 11, 1,
ax_anim 2, 0, 35, 11, 0, 11, 0,
ax_anim 2, 0, 35, 11, 1, 11, 1,
ax_anim 2, 0, 32, 6, 0, 6, 0,
ax_anim_terminator
sHoundoomAnims_2_4:
ax_anim 2, 0, 37, -1, 1, -1, 1,
ax_anim 4, 0, 37, -2, 2, -2, 2,
ax_anim 1, 0, 38, 0, -1, 0, -1,
ax_anim 1, 2, 38, 5, -5, 5, -5,
ax_anim 1, 0, 38, 10, -10, 10, -10,
ax_anim 2, 0, 39, 15, -13, 15, -13,
ax_anim 2, 1, 39, 16, -12, 16, -12,
ax_anim 2, 0, 39, 15, -13, 15, -13,
ax_anim 2, 0, 39, 16, -12, 16, -12,
ax_anim 2, 0, 36, 6, -6, 6, -6,
ax_anim_terminator
sHoundoomAnims_2_5:
ax_anim 2, 0, 41, 0, 1, 0, 1,
ax_anim 4, 0, 41, 0, 2, 0, 2,
ax_anim 1, 0, 42, 0, 0, 0, 0,
ax_anim 1, 2, 42, 0, -4, 0, -4,
ax_anim 1, 0, 42, 0, -6, 0, -6,
ax_anim 2, 0, 43, 0, -12, 0, -12,
ax_anim 2, 1, 43, 1, -12, 1, -12,
ax_anim 2, 0, 43, 0, -12, 0, -12,
ax_anim 2, 0, 43, 1, -12, 1, -12,
ax_anim 2, 0, 40, 0, -6, 0, -6,
ax_anim_terminator
sHoundoomAnims_2_6:
ax_anim 2, 0, 45, 1, 1, 1, 1,
ax_anim 4, 0, 45, 2, 2, 2, 2,
ax_anim 1, 0, 46, 0, -1, 0, -1,
ax_anim 1, 2, 46, -5, -5, -5, -5,
ax_anim 1, 0, 46, -10, -10, -10, -10,
ax_anim 2, 0, 47, -15, -13, -15, -13,
ax_anim 2, 1, 47, -16, -12, -16, -12,
ax_anim 2, 0, 47, -15, -13, -15, -13,
ax_anim 2, 0, 47, -16, -12, -16, -12,
ax_anim 2, 0, 44, -6, -6, -6, -6,
ax_anim_terminator
sHoundoomAnims_2_7:
ax_anim 2, 0, 49, 1, 0, 1, 0,
ax_anim 4, 0, 49, 2, 0, 2, 0,
ax_anim 1, 0, 50, 0, 0, 0, 0,
ax_anim 1, 2, 50, -4, 0, -4, 0,
ax_anim 1, 0, 50, -6, 0, -6, 0,
ax_anim 2, 0, 51, -11, 0, -11, 0,
ax_anim 2, 1, 51, -11, 1, -11, 1,
ax_anim 2, 0, 51, -11, 0, -11, 0,
ax_anim 2, 0, 51, -11, 1, -11, 1,
ax_anim 2, 0, 48, -6, 0, -6, 0,
ax_anim_terminator
sHoundoomAnims_2_8:
ax_anim 2, 0, 53, 1, -1, 1, -1,
ax_anim 4, 0, 53, 2, -2, 2, -2,
ax_anim 1, 0, 54, 0, 0, 0, 0,
ax_anim 1, 2, 54, -4, 4, -4, 4,
ax_anim 1, 0, 54, -10, 10, -10, 10,
ax_anim 2, 0, 55, -16, 15, -16, 15,
ax_anim 2, 1, 55, -17, 14, -17, 14,
ax_anim 2, 0, 55, -16, 15, -16, 15,
ax_anim 2, 0, 55, -17, 14, -17, 14,
ax_anim 2, 0, 52, -6, 6, -6, 6,
ax_anim_terminator
.align 2
sHoundoomAnims_3_1:
ax_anim 2, 0, 57, 0, -1, 0, -1,
ax_anim 4, 0, 57, 0, -2, 0, -2,
ax_anim 1, 0, 58, 0, 0, 0, 0,
ax_anim 1, 2, 58, 0, 4, 0, 4,
ax_anim 1, 0, 58, 0, 10, 0, 10,
ax_anim 2, 0, 59, 0, 16, 0, 16,
ax_anim 2, 1, 59, 1, 16, 1, 16,
ax_anim 2, 0, 59, 0, 16, 0, 16,
ax_anim 2, 0, 59, 1, 16, 1, 16,
ax_anim 2, 0, 56, 0, 6, 0, 6,
ax_anim_terminator
sHoundoomAnims_3_2:
ax_anim 2, 0, 61, -1, -1, -1, -1,
ax_anim 4, 0, 61, -2, -2, -2, -2,
ax_anim 1, 0, 62, 0, 0, 0, 0,
ax_anim 1, 2, 62, 4, 4, 4, 4,
ax_anim 1, 0, 62, 10, 10, 10, 10,
ax_anim 2, 0, 63, 16, 15, 16, 15,
ax_anim 2, 1, 63, 17, 14, 17, 14,
ax_anim 2, 0, 63, 16, 15, 16, 15,
ax_anim 2, 0, 63, 17, 14, 17, 14,
ax_anim 2, 0, 60, 6, 6, 6, 6,
ax_anim_terminator
sHoundoomAnims_3_3:
ax_anim 2, 0, 65, -1, 0, -1, 0,
ax_anim 4, 0, 65, -2, 0, -2, 0,
ax_anim 1, 0, 66, 0, 0, 0, 0,
ax_anim 1, 2, 66, 4, 0, 4, 0,
ax_anim 1, 0, 66, 6, 0, 6, 0,
ax_anim 2, 0, 67, 11, 0, 11, 0,
ax_anim 2, 1, 67, 11, 1, 11, 1,
ax_anim 2, 0, 67, 11, 0, 11, 0,
ax_anim 2, 0, 67, 11, 1, 11, 1,
ax_anim 2, 0, 64, 6, 0, 6, 0,
ax_anim_terminator
sHoundoomAnims_3_4:
ax_anim 2, 0, 69, -1, 1, -1, 1,
ax_anim 4, 0, 69, -2, 2, -2, 2,
ax_anim 1, 0, 70, 0, -1, 0, -1,
ax_anim 1, 2, 70, 5, -5, 5, -5,
ax_anim 1, 0, 70, 10, -10, 10, -10,
ax_anim 2, 0, 71, 15, -13, 15, -13,
ax_anim 2, 1, 71, 16, -12, 16, -12,
ax_anim 2, 0, 71, 15, -13, 15, -13,
ax_anim 2, 0, 71, 16, -12, 16, -12,
ax_anim 2, 0, 68, 6, -6, 6, -6,
ax_anim_terminator
sHoundoomAnims_3_5:
ax_anim 2, 0, 73, 0, 1, 0, 1,
ax_anim 4, 0, 73, 0, 2, 0, 2,
ax_anim 1, 0, 74, 0, 0, 0, 0,
ax_anim 1, 2, 74, 0, -4, 0, -4,
ax_anim 1, 0, 74, 0, -6, 0, -6,
ax_anim 2, 0, 75, 0, -12, 0, -12,
ax_anim 2, 1, 75, 1, -12, 1, -12,
ax_anim 2, 0, 75, 0, -12, 0, -12,
ax_anim 2, 0, 75, 1, -12, 1, -12,
ax_anim 2, 0, 72, 0, -6, 0, -6,
ax_anim_terminator
sHoundoomAnims_3_6:
ax_anim 2, 0, 77, 1, 1, 1, 1,
ax_anim 4, 0, 77, 2, 2, 2, 2,
ax_anim 1, 0, 78, 0, -1, 0, -1,
ax_anim 1, 2, 78, -5, -5, -5, -5,
ax_anim 1, 0, 78, -10, -10, -10, -10,
ax_anim 2, 0, 79, -15, -13, -15, -13,
ax_anim 2, 1, 79, -16, -12, -16, -12,
ax_anim 2, 0, 79, -15, -13, -15, -13,
ax_anim 2, 0, 79, -16, -12, -16, -12,
ax_anim 2, 0, 76, -6, -6, -6, -6,
ax_anim_terminator
sHoundoomAnims_3_7:
ax_anim 2, 0, 81, 1, 0, 1, 0,
ax_anim 4, 0, 81, 2, 0, 2, 0,
ax_anim 1, 0, 82, 0, 0, 0, 0,
ax_anim 1, 2, 82, -4, 0, -4, 0,
ax_anim 1, 0, 82, -6, 0, -6, 0,
ax_anim 2, 0, 83, -11, 0, -11, 0,
ax_anim 2, 1, 83, -11, 1, -11, 1,
ax_anim 2, 0, 83, -11, 0, -11, 0,
ax_anim 2, 0, 83, -11, 1, -11, 1,
ax_anim 2, 0, 80, -6, 0, -6, 0,
ax_anim_terminator
sHoundoomAnims_3_8:
ax_anim 2, 0, 85, 1, -1, 1, -1,
ax_anim 4, 0, 85, 2, -2, 2, -2,
ax_anim 1, 0, 86, 0, 0, 0, 0,
ax_anim 1, 2, 86, -4, 4, -4, 4,
ax_anim 1, 0, 86, -10, 10, -10, 10,
ax_anim 2, 0, 87, -16, 15, -16, 15,
ax_anim 2, 1, 87, -17, 14, -17, 14,
ax_anim 2, 0, 87, -16, 15, -16, 15,
ax_anim 2, 0, 87, -17, 14, -17, 14,
ax_anim 2, 0, 84, -6, 6, -6, 6,
ax_anim_terminator
.align 2
sHoundoomAnims_4_1:
ax_anim 6, 0, 92, 0, -2, 0, -2,
ax_anim 2, 0, 90, 0, -2, 0, -2,
ax_anim 6, 2, 90, 0, -3, 0, -3,
ax_anim 1, 0, 90, 0, -1, 0, -1,
ax_anim 1, 0, 91, 0, 3, 0, 2,
ax_anim 2, 1, 91, 1, 3, 1, 2,
ax_anim 2, 0, 91, 0, 3, 0, 2,
ax_anim 2, 0, 91, 1, 3, 1, 2,
ax_anim 2, 0, 91, 0, 3, 0, 2,
ax_anim 2, 0, 91, 1, 3, 1, 2,
ax_anim 2, 0, 91, 0, 3, 0, 2,
ax_anim 2, 0, 88, 0, 3, 0, 2,
ax_anim_terminator
sHoundoomAnims_4_2:
ax_anim 6, 0, 97, -2, -2, -2, -2,
ax_anim 2, 0, 95, -2, -2, -2, -2,
ax_anim 6, 2, 95, -3, -3, -3, -3,
ax_anim 1, 0, 95, -1, -1, -1, -1,
ax_anim 1, 0, 96, 2, 2, 1, 1,
ax_anim 2, 1, 96, 3, 1, 2, 0,
ax_anim 2, 0, 96, 2, 2, 1, 1,
ax_anim 2, 0, 96, 3, 1, 2, 0,
ax_anim 2, 0, 96, 2, 2, 1, 1,
ax_anim 2, 0, 96, 3, 1, 2, 0,
ax_anim 2, 0, 96, 2, 2, 1, 1,
ax_anim 2, 0, 93, 2, 2, 1, 1,
ax_anim_terminator
sHoundoomAnims_4_3:
ax_anim 6, 0, 102, -2, 0, -2, 0,
ax_anim 2, 0, 100, -2, 0, -2, 0,
ax_anim 6, 2, 100, -3, 0, -3, 0,
ax_anim 1, 0, 100, -1, 0, -1, 0,
ax_anim 1, 0, 101, 2, 0, 2, 0,
ax_anim 2, 1, 101, 2, 1, 2, 1,
ax_anim 2, 0, 101, 2, 0, 2, 0,
ax_anim 2, 0, 101, 2, 1, 2, 1,
ax_anim 2, 0, 101, 2, 0, 2, 0,
ax_anim 2, 0, 101, 2, 1, 2, 1,
ax_anim 2, 0, 101, 2, 0, 2, 0,
ax_anim 2, 0, 98, 2, 0, 2, 0,
ax_anim_terminator
sHoundoomAnims_4_4:
ax_anim 6, 0, 107, -2, 2, -2, 2,
ax_anim 2, 0, 105, -2, 2, -2, 2,
ax_anim 6, 2, 105, -3, 3, -3, 3,
ax_anim 1, 0, 105, -1, 1, -1, 1,
ax_anim 1, 0, 106, 2, -2, 1, -1,
ax_anim 2, 1, 106, 3, -1, 2, 0,
ax_anim 2, 0, 106, 2, -2, 1, -1,
ax_anim 2, 0, 106, 3, -1, 2, 0,
ax_anim 2, 0, 106, 2, -2, 1, -1,
ax_anim 2, 0, 106, 3, -1, 2, 0,
ax_anim 2, 0, 106, 2, -2, 1, -1,
ax_anim 2, 0, 103, 2, -2, 1, -1,
ax_anim_terminator
sHoundoomAnims_4_5:
ax_anim 6, 0, 112, 0, 2, 0, 2,
ax_anim 2, 0, 110, 0, 2, 0, 2,
ax_anim 6, 2, 110, 0, 3, 0, 3,
ax_anim 1, 0, 110, 0, 1, 0, 1,
ax_anim 1, 0, 111, 0, -1, 0, -1,
ax_anim 2, 1, 111, 1, -1, 1, -1,
ax_anim 2, 0, 111, 0, -1, 0, -1,
ax_anim 2, 0, 111, 1, -1, 1, -1,
ax_anim 2, 0, 111, 0, -1, 0, -1,
ax_anim 2, 0, 111, 1, -1, 1, -1,
ax_anim 2, 0, 111, 0, -1, 0, -1,
ax_anim 2, 0, 108, 0, -1, 0, -1,
ax_anim_terminator
sHoundoomAnims_4_6:
ax_anim 6, 0, 117, 2, 2, 2, 2,
ax_anim 2, 0, 115, 2, 2, 2, 2,
ax_anim 6, 2, 115, 3, 3, 3, 3,
ax_anim 1, 0, 115, 1, 1, 1, 1,
ax_anim 1, 0, 116, -2, -2, -1, -1,
ax_anim 2, 1, 116, -3, -1, -2, 0,
ax_anim 2, 0, 116, -2, -2, -1, -1,
ax_anim 2, 0, 116, -3, -1, -2, 0,
ax_anim 2, 0, 116, -2, -2, -1, -1,
ax_anim 2, 0, 116, -3, -1, -2, 0,
ax_anim 2, 0, 116, -2, -2, -1, -1,
ax_anim 2, 0, 113, -2, -2, -1, -1,
ax_anim_terminator
sHoundoomAnims_4_7:
ax_anim 6, 0, 122, 2, 0, 2, 0,
ax_anim 2, 0, 120, 2, 0, 2, 0,
ax_anim 6, 2, 120, 3, 0, 3, 0,
ax_anim 1, 0, 120, 1, 0, 1, 0,
ax_anim 1, 0, 121, -2, 0, -2, 0,
ax_anim 2, 1, 121, -2, 1, -2, 1,
ax_anim 2, 0, 121, -2, 0, -2, 0,
ax_anim 2, 0, 121, -2, 1, -2, 1,
ax_anim 2, 0, 121, -2, 0, -2, 0,
ax_anim 2, 0, 121, -2, 1, -2, 1,
ax_anim 2, 0, 121, -2, 0, -2, 0,
ax_anim 2, 0, 118, -2, 0, -2, 0,
ax_anim_terminator
sHoundoomAnims_4_8:
ax_anim 6, 0, 127, 2, -2, 2, -2,
ax_anim 2, 0, 125, 2, -2, 2, -2,
ax_anim 6, 2, 125, 3, -3, 3, -3,
ax_anim 1, 0, 125, 1, -1, 1, -1,
ax_anim 1, 0, 126, -2, 2, -1, 1,
ax_anim 2, 1, 126, -3, 1, -2, 0,
ax_anim 2, 0, 126, -2, 2, -1, 1,
ax_anim 2, 0, 126, -3, 1, -2, 0,
ax_anim 2, 0, 126, -2, 2, -1, 1,
ax_anim 2, 0, 126, -3, 1, -2, 0,
ax_anim 2, 0, 126, -2, 2, -1, 1,
ax_anim 2, 0, 123, -2, 2, -1, 1,
ax_anim_terminator
.align 2
sHoundoomAnims_5_1:
ax_anim 10, 0, 129, 0, 0, 0, 0,
ax_anim 6, 2, 129, 1, 0, 1, 0,
ax_anim 2, 0, 129, 0, 0, 0, 0,
ax_anim 2, 0, 129, 1, 0, 1, 0,
ax_anim 2, 0, 129, 0, 0, 0, 0,
ax_anim 2, 0, 129, 1, 0, 1, 0,
ax_anim_terminator
sHoundoomAnims_5_2:
ax_anim 10, 0, 131, 0, 0, 0, 0,
ax_anim 6, 2, 131, 1, -1, 1, -1,
ax_anim 2, 0, 131, 0, 0, 0, 0,
ax_anim 2, 0, 131, 1, -1, 1, -1,
ax_anim 2, 0, 131, 0, 0, 0, 0,
ax_anim 2, 0, 131, 1, -1, 1, -1,
ax_anim_terminator
sHoundoomAnims_5_3:
ax_anim 10, 0, 133, 0, 0, 0, 0,
ax_anim 6, 2, 133, 0, 1, 0, 1,
ax_anim 2, 0, 133, 0, 0, 0, 0,
ax_anim 2, 0, 133, 0, 1, 0, 1,
ax_anim 2, 0, 133, 0, 0, 0, 0,
ax_anim 2, 0, 133, 0, 1, 0, 1,
ax_anim_terminator
sHoundoomAnims_5_4:
ax_anim 10, 0, 135, 0, 0, 0, 0,
ax_anim 6, 2, 135, 1, 1, 1, 1,
ax_anim 2, 0, 135, 0, 0, 0, 0,
ax_anim 2, 0, 135, 1, 1, 1, 1,
ax_anim 2, 0, 135, 0, 0, 0, 0,
ax_anim 2, 0, 135, 1, 1, 1, 1,
ax_anim_terminator
sHoundoomAnims_5_5:
ax_anim 10, 0, 137, 0, 0, 0, 0,
ax_anim 6, 2, 137, 1, 0, 1, 0,
ax_anim 2, 0, 137, 0, 0, 0, 0,
ax_anim 2, 0, 137, 1, 0, 1, 0,
ax_anim 2, 0, 137, 0, 0, 0, 0,
ax_anim 2, 0, 137, 1, 0, 1, 0,
ax_anim_terminator
sHoundoomAnims_5_6:
ax_anim 10, 0, 139, 0, 0, 0, 0,
ax_anim 6, 2, 139, -1, 1, -1, 1,
ax_anim 2, 0, 139, 0, 0, 0, 0,
ax_anim 2, 0, 139, -1, 1, -1, 1,
ax_anim 2, 0, 139, 0, 0, 0, 0,
ax_anim 2, 0, 139, -1, 1, -1, 1,
ax_anim_terminator
sHoundoomAnims_5_7:
ax_anim 10, 0, 141, 0, 0, 0, 0,
ax_anim 6, 2, 141, 0, 1, 0, 1,
ax_anim 2, 0, 141, 0, 0, 0, 0,
ax_anim 2, 0, 141, 0, 1, 0, 1,
ax_anim 2, 0, 141, 0, 0, 0, 0,
ax_anim 2, 0, 141, 0, 1, 0, 1,
ax_anim_terminator
sHoundoomAnims_5_8:
ax_anim 10, 0, 143, 0, 0, 0, 0,
ax_anim 6, 2, 143, -1, -1, -1, -1,
ax_anim 2, 0, 143, 0, 0, 0, 0,
ax_anim 2, 0, 143, -1, -1, -1, -1,
ax_anim 2, 0, 143, 0, 0, 0, 0,
ax_anim 2, 0, 143, -1, -1, -1, -1,
ax_anim_terminator
.align 2
sHoundoomAnims_6_1:
ax_anim 30, 0, 144, 0, 0, 0, 0,
ax_anim 35, 0, 145, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sHoundoomAnims_7_1:
ax_anim 2, 0, 146, 0, -4, 0, -4,
ax_anim 8, 0, 146, 0, -5, 0, -5,
ax_anim_terminator
sHoundoomAnims_7_2:
ax_anim 2, 0, 147, -4, -4, -4, -4,
ax_anim 8, 0, 147, -5, -5, -5, -5,
ax_anim_terminator
sHoundoomAnims_7_3:
ax_anim 2, 0, 148, -4, 0, -4, 0,
ax_anim 8, 0, 148, -5, 0, -5, 0,
ax_anim_terminator
sHoundoomAnims_7_4:
ax_anim 2, 0, 149, -4, 4, -4, 4,
ax_anim 8, 0, 149, -5, 5, -5, 5,
ax_anim_terminator
sHoundoomAnims_7_5:
ax_anim 2, 0, 150, 0, 4, 0, 4,
ax_anim 8, 0, 150, 0, 5, 0, 5,
ax_anim_terminator
sHoundoomAnims_7_6:
ax_anim 2, 0, 151, 4, 4, 4, 4,
ax_anim 8, 0, 151, 5, 5, 5, 5,
ax_anim_terminator
sHoundoomAnims_7_7:
ax_anim 2, 0, 152, 4, 0, 4, 0,
ax_anim 8, 0, 152, 5, 0, 5, 0,
ax_anim_terminator
sHoundoomAnims_7_8:
ax_anim 2, 0, 153, 4, -4, 4, -4,
ax_anim 8, 0, 153, 5, -5, 5, -5,
ax_anim_terminator
.align 2
sHoundoomAnims_8_1:
ax_anim 60, 0, 154, 0, 0, 0, 0,
ax_anim 10, 0, 156, 0, 0, 0, 0,
ax_anim 2, 0, 156, -1, 0, -1, 0,
ax_anim 2, 0, 156, 0, 0, 0, 0,
ax_anim 2, 0, 156, -1, 0, -1, 0,
ax_anim 2, 0, 156, 0, 0, 0, 0,
ax_anim 2, 0, 156, -1, 0, -1, 0,
ax_anim 2, 0, 156, 0, 0, 0, 0,
ax_anim 2, 0, 156, -1, 0, -1, 0,
ax_anim 2, 0, 156, 0, 0, 0, 0,
ax_anim 2, 0, 156, -1, 0, -1, 0,
ax_anim 2, 0, 156, 0, 0, 0, 0,
ax_anim 2, 0, 156, -1, 0, -1, 0,
ax_anim 10, 0, 156, 0, 0, 0, 0,
ax_anim_terminator
sHoundoomAnims_8_2:
ax_anim 60, 0, 159, 0, 0, 0, 0,
ax_anim 10, 0, 161, 0, 0, 0, 0,
ax_anim 2, 0, 161, -1, 0, -1, 0,
ax_anim 2, 0, 161, 0, 0, 0, 0,
ax_anim 2, 0, 161, -1, 0, -1, 0,
ax_anim 2, 0, 161, 0, 0, 0, 0,
ax_anim 2, 0, 161, -1, 0, -1, 0,
ax_anim 2, 0, 161, 0, 0, 0, 0,
ax_anim 2, 0, 161, -1, 0, -1, 0,
ax_anim 2, 0, 161, 0, 0, 0, 0,
ax_anim 2, 0, 161, -1, 0, -1, 0,
ax_anim 2, 0, 161, 0, 0, 0, 0,
ax_anim 2, 0, 161, -1, 0, -1, 0,
ax_anim 10, 0, 161, 0, 0, 0, 0,
ax_anim_terminator
sHoundoomAnims_8_3:
ax_anim 60, 0, 164, 0, 0, 0, 0,
ax_anim 10, 0, 166, 0, 0, 0, 0,
ax_anim 2, 0, 166, -1, 0, -1, 0,
ax_anim 2, 0, 166, 0, 0, 0, 0,
ax_anim 2, 0, 166, -1, 0, -1, 0,
ax_anim 2, 0, 166, 0, 0, 0, 0,
ax_anim 2, 0, 166, -1, 0, -1, 0,
ax_anim 2, 0, 166, 0, 0, 0, 0,
ax_anim 2, 0, 166, -1, 0, -1, 0,
ax_anim 2, 0, 166, 0, 0, 0, 0,
ax_anim 2, 0, 166, -1, 0, -1, 0,
ax_anim 2, 0, 166, 0, 0, 0, 0,
ax_anim 2, 0, 166, -1, 0, -1, 0,
ax_anim 10, 0, 166, 0, 0, 0, 0,
ax_anim_terminator
sHoundoomAnims_8_4:
ax_anim 60, 0, 169, 0, 0, 0, 0,
ax_anim 10, 0, 171, 0, 0, 0, 0,
ax_anim 2, 0, 171, -1, 0, -1, 0,
ax_anim 2, 0, 171, 0, 0, 0, 0,
ax_anim 2, 0, 171, -1, 0, -1, 0,
ax_anim 2, 0, 171, 0, 0, 0, 0,
ax_anim 2, 0, 171, -1, 0, -1, 0,
ax_anim 2, 0, 171, 0, 0, 0, 0,
ax_anim 2, 0, 171, -1, 0, -1, 0,
ax_anim 2, 0, 171, 0, 0, 0, 0,
ax_anim 2, 0, 171, -1, 0, -1, 0,
ax_anim 2, 0, 171, 0, 0, 0, 0,
ax_anim 2, 0, 171, -1, 0, -1, 0,
ax_anim 10, 0, 171, 0, 0, 0, 0,
ax_anim_terminator
sHoundoomAnims_8_5:
ax_anim 60, 0, 174, 0, 0, 0, 0,
ax_anim 10, 0, 176, 0, 0, 0, 0,
ax_anim 2, 0, 176, -1, 0, -1, 0,
ax_anim 2, 0, 176, 0, 0, 0, 0,
ax_anim 2, 0, 176, -1, 0, -1, 0,
ax_anim 2, 0, 176, 0, 0, 0, 0,
ax_anim 2, 0, 176, -1, 0, -1, 0,
ax_anim 2, 0, 176, 0, 0, 0, 0,
ax_anim 2, 0, 176, -1, 0, -1, 0,
ax_anim 2, 0, 176, 0, 0, 0, 0,
ax_anim 2, 0, 176, -1, 0, -1, 0,
ax_anim 2, 0, 176, 0, 0, 0, 0,
ax_anim 2, 0, 176, -1, 0, -1, 0,
ax_anim 10, 0, 176, 0, 0, 0, 0,
ax_anim_terminator
sHoundoomAnims_8_6:
ax_anim 60, 0, 179, 0, 0, 0, 0,
ax_anim 10, 0, 181, 0, 0, 0, 0,
ax_anim 2, 0, 181, -1, 0, -1, 0,
ax_anim 2, 0, 181, 0, 0, 0, 0,
ax_anim 2, 0, 181, -1, 0, -1, 0,
ax_anim 2, 0, 181, 0, 0, 0, 0,
ax_anim 2, 0, 181, -1, 0, -1, 0,
ax_anim 2, 0, 181, 0, 0, 0, 0,
ax_anim 2, 0, 181, -1, 0, -1, 0,
ax_anim 2, 0, 181, 0, 0, 0, 0,
ax_anim 2, 0, 181, -1, 0, -1, 0,
ax_anim 2, 0, 181, 0, 0, 0, 0,
ax_anim 2, 0, 181, -1, 0, -1, 0,
ax_anim 10, 0, 181, 0, 0, 0, 0,
ax_anim_terminator
sHoundoomAnims_8_7:
ax_anim 60, 0, 184, 0, 0, 0, 0,
ax_anim 10, 0, 186, 0, 0, 0, 0,
ax_anim 2, 0, 186, -1, 0, -1, 0,
ax_anim 2, 0, 186, 0, 0, 0, 0,
ax_anim 2, 0, 186, -1, 0, -1, 0,
ax_anim 2, 0, 186, 0, 0, 0, 0,
ax_anim 2, 0, 186, -1, 0, -1, 0,
ax_anim 2, 0, 186, 0, 0, 0, 0,
ax_anim 2, 0, 186, -1, 0, -1, 0,
ax_anim 2, 0, 186, 0, 0, 0, 0,
ax_anim 2, 0, 186, -1, 0, -1, 0,
ax_anim 2, 0, 186, 0, 0, 0, 0,
ax_anim 2, 0, 186, -1, 0, -1, 0,
ax_anim 10, 0, 186, 0, 0, 0, 0,
ax_anim_terminator
sHoundoomAnims_8_8:
ax_anim 60, 0, 189, 0, 0, 0, 0,
ax_anim 10, 0, 191, 0, 0, 0, 0,
ax_anim 2, 0, 191, -1, 0, -1, 0,
ax_anim 2, 0, 191, 0, 0, 0, 0,
ax_anim 2, 0, 191, -1, 0, -1, 0,
ax_anim 2, 0, 191, 0, 0, 0, 0,
ax_anim 2, 0, 191, -1, 0, -1, 0,
ax_anim 2, 0, 191, 0, 0, 0, 0,
ax_anim 2, 0, 191, -1, 0, -1, 0,
ax_anim 2, 0, 191, 0, 0, 0, 0,
ax_anim 2, 0, 191, -1, 0, -1, 0,
ax_anim 2, 0, 191, 0, 0, 0, 0,
ax_anim 2, 0, 191, -1, 0, -1, 0,
ax_anim 10, 0, 191, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sHoundoomAnims_9_1:
ax_anim 2, 0, 194, 0, 0, 0, 0,
ax_anim 1, 0, 195, 10, 2, 10, 2,
ax_anim 2, 0, 196, 16, 10, 16, 10,
ax_anim 2, 0, 197, 11, 15, 11, 15,
ax_anim 3, 0, 198, 0, 18, 0, 18,
ax_anim 2, 3, 199, -11, 15, -11, 15,
ax_anim 2, 0, 200, -16, 10, -16, 10,
ax_anim 1, 0, 201, -10, 2, -10, 2,
ax_anim 1, 0, 194, 0, 0, 0, 0,
ax_anim_terminator
sHoundoomAnims_9_2:
ax_anim 2, 0, 201, 0, 0, 0, 0,
ax_anim 1, 0, 194, 11, 0, 11, 0,
ax_anim 2, 0, 195, 22, 2, 22, 2,
ax_anim 2, 0, 196, 25, 11, 25, 11,
ax_anim 3, 0, 197, 19, 17, 19, 17,
ax_anim 2, 3, 198, 9, 21, 9, 21,
ax_anim 2, 0, 199, -2, 16, -2, 16,
ax_anim 1, 0, 200, -6, 10, -6, 10,
ax_anim 1, 0, 201, 0, 0, 0, 0,
ax_anim_terminator
sHoundoomAnims_9_3:
ax_anim 2, 0, 200, 0, 0, 0, 0,
ax_anim 1, 0, 201, 5, -6, 5, -6,
ax_anim 2, 0, 194, 10, -6, 10, -6,
ax_anim 2, 0, 195, 17, -6, 17, -6,
ax_anim 3, 0, 196, 19, 0, 19, 0,
ax_anim 2, 3, 197, 16, 3, 16, 3,
ax_anim 2, 0, 198, 8, 5, 8, 5,
ax_anim 1, 0, 199, 3, 4, 3, 4,
ax_anim 1, 0, 200, 0, 0, 0, 0,
ax_anim_terminator
sHoundoomAnims_9_4:
ax_anim 2, 0, 199, 0, 0, 0, 0,
ax_anim 1, 0, 200, -4, -8, -4, -8,
ax_anim 2, 0, 201, 2, -17, 2, -17,
ax_anim 2, 0, 194, 10, -23, 10, -23,
ax_anim 3, 0, 195, 19, -20, 19, -20,
ax_anim 2, 3, 196, 24, -11, 24, -11,
ax_anim 2, 0, 197, 23, -4, 23, -4,
ax_anim 1, 0, 198, 13, 0, 13, 0,
ax_anim 1, 0, 199, 0, 0, 0, 0,
ax_anim_terminator
sHoundoomAnims_9_5:
ax_anim 2, 0, 198, 0, 0, 0, 0,
ax_anim 1, 0, 199, -13, -5, -13, -5,
ax_anim 2, 0, 200, -18, -10, -18, -10,
ax_anim 2, 0, 201, -11, -20, -11, -20,
ax_anim 3, 0, 194, 0, -22, 0, -22,
ax_anim 2, 3, 195, 11, -20, 11, -20,
ax_anim 2, 0, 196, 18, -10, 18, -10,
ax_anim 1, 0, 197, 13, -5, 13, -5,
ax_anim 1, 0, 198, 0, 0, 0, 0,
ax_anim_terminator
sHoundoomAnims_9_6:
ax_anim 2, 0, 197, 0, 0, 0, 0,
ax_anim 1, 0, 196, 4, -8, 4, -8,
ax_anim 2, 0, 195, -2, -17, -2, -17,
ax_anim 2, 0, 194, -10, -23, -10, -23,
ax_anim 3, 0, 201, -19, -20, -19, -20,
ax_anim 2, 3, 200, -24, -11, -24, -11,
ax_anim 2, 0, 199, -23, -4, -23, -4,
ax_anim 1, 0, 198, -13, 0, -13, 0,
ax_anim 1, 0, 197, 0, 0, 0, 0,
ax_anim_terminator
sHoundoomAnims_9_7:
ax_anim 2, 0, 196, 0, 0, 0, 0,
ax_anim 1, 0, 195, -5, -6, -5, -6,
ax_anim 2, 0, 194, -10, -6, -10, -6,
ax_anim 2, 0, 201, -17, -6, -17, -6,
ax_anim 3, 0, 200, -19, 0, -19, 0,
ax_anim 2, 3, 199, -16, 3, -16, 3,
ax_anim 2, 0, 198, -8, 5, -8, 5,
ax_anim 1, 0, 197, -3, 4, -3, 4,
ax_anim 1, 0, 196, 0, 0, 0, 0,
ax_anim_terminator
sHoundoomAnims_9_8:
ax_anim 2, 0, 195, 0, 0, 0, 0,
ax_anim 1, 0, 194, -11, 0, -11, 0,
ax_anim 2, 0, 201, -22, 2, -22, 2,
ax_anim 2, 0, 200, -25, 11, -25, 11,
ax_anim 3, 0, 199, -19, 17, -19, 17,
ax_anim 2, 3, 198, -9, 21, -9, 21,
ax_anim 2, 0, 197, 2, 16, 2, 16,
ax_anim 1, 0, 196, 6, 10, 6, 10,
ax_anim 1, 0, 195, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sHoundoomAnims_10_1:
ax_anim 2, 0, 202, 0, 0, 0, 0,
ax_anim 2, 0, 202, 6, 0, 6, 0,
ax_anim 2, 0, 202, -6, 0, -6, 0,
ax_anim 2, 0, 202, 10, 0, 10, 0,
ax_anim 2, 0, 202, -10, 0, -10, 0,
ax_anim 2, 0, 202, 12, 0, 12, 0,
ax_anim 3, 0, 202, -12, 0, -12, 0,
ax_anim 3, 0, 202, 13, 0, 13, 0,
ax_anim 3, 0, 202, -13, 0, -13, 0,
ax_anim 2, 0, 202, 12, 0, 12, 0,
ax_anim 3, 0, 202, -12, 0, -12, 0,
ax_anim 2, 0, 202, 10, 0, 10, 0,
ax_anim 2, 0, 202, -10, 0, -10, 0,
ax_anim 2, 0, 202, 6, 0, 6, 0,
ax_anim 2, 0, 202, -6, 0, -6, 0,
ax_anim 2, 0, 202, 0, 0, 0, 0,
ax_anim_terminator
sHoundoomAnims_10_2:
ax_anim 2, 0, 203, 0, 0, 0, 0,
ax_anim 2, 0, 203, 6, -6, 6, -6,
ax_anim 2, 0, 203, -6, 6, -6, 6,
ax_anim 2, 0, 203, 10, -10, 10, -10,
ax_anim 2, 0, 203, -10, 10, -10, 10,
ax_anim 2, 0, 203, 12, -12, 12, -12,
ax_anim 3, 0, 203, -12, 12, -12, 12,
ax_anim 3, 0, 203, 13, -13, 13, -13,
ax_anim 3, 0, 203, -13, 13, -13, 13,
ax_anim 2, 0, 203, 12, -12, 12, -12,
ax_anim 3, 0, 203, -12, 12, -12, 12,
ax_anim 2, 0, 203, 10, -10, 10, -10,
ax_anim 2, 0, 203, -10, 10, -10, 10,
ax_anim 2, 0, 203, 6, -6, 6, -6,
ax_anim 2, 0, 203, -6, 6, -6, 6,
ax_anim 2, 0, 203, 0, 0, 0, 0,
ax_anim_terminator
sHoundoomAnims_10_3:
ax_anim 2, 0, 204, 0, 0, 0, 0,
ax_anim 2, 0, 204, 0, -6, 0, -6,
ax_anim 2, 0, 204, 0, 6, 0, 6,
ax_anim 2, 0, 204, 0, -10, 0, -10,
ax_anim 2, 0, 204, 0, 10, 0, 10,
ax_anim 2, 0, 204, 0, -12, 0, -12,
ax_anim 3, 0, 204, 0, 12, 0, 12,
ax_anim 3, 0, 204, 0, -13, 0, -13,
ax_anim 3, 0, 204, 0, 13, 0, 13,
ax_anim 2, 0, 204, 0, -12, 0, -12,
ax_anim 3, 0, 204, 0, 12, 0, 12,
ax_anim 2, 0, 204, 0, -10, 0, -10,
ax_anim 2, 0, 204, 0, 10, 0, 10,
ax_anim 2, 0, 204, 0, -6, 0, -6,
ax_anim 2, 0, 204, 0, 6, 0, 6,
ax_anim 2, 0, 204, 0, 0, 0, 0,
ax_anim_terminator
sHoundoomAnims_10_4:
ax_anim 2, 0, 205, 0, 0, 0, 0,
ax_anim 2, 0, 205, -6, -6, -6, -6,
ax_anim 2, 0, 205, 6, 6, 6, 6,
ax_anim 2, 0, 205, -10, -10, -10, -10,
ax_anim 2, 0, 205, 10, 10, 10, 10,
ax_anim 2, 0, 205, -12, -12, -12, -12,
ax_anim 3, 0, 205, 12, 12, 12, 12,
ax_anim 3, 0, 205, -13, -13, -13, -13,
ax_anim 3, 0, 205, 13, 13, 13, 13,
ax_anim 2, 0, 205, -12, -12, -12, -12,
ax_anim 3, 0, 205, 12, 12, 12, 12,
ax_anim 2, 0, 205, -10, -10, -10, -10,
ax_anim 2, 0, 205, 10, 10, 10, 10,
ax_anim 2, 0, 205, -6, -6, -6, -6,
ax_anim 2, 0, 205, 6, 6, 6, 6,
ax_anim 2, 0, 205, 0, 0, 0, 0,
ax_anim_terminator
sHoundoomAnims_10_5:
ax_anim 2, 0, 206, 0, 0, 0, 0,
ax_anim 2, 0, 206, 6, 0, 6, 0,
ax_anim 2, 0, 206, -6, 0, -6, 0,
ax_anim 2, 0, 206, 10, 0, 10, 0,
ax_anim 2, 0, 206, -10, 0, -10, 0,
ax_anim 2, 0, 206, 12, 0, 12, 0,
ax_anim 3, 0, 206, -12, 0, -12, 0,
ax_anim 3, 0, 206, 13, 0, 13, 0,
ax_anim 3, 0, 206, -13, 0, -13, 0,
ax_anim 2, 0, 206, 12, 0, 12, 0,
ax_anim 3, 0, 206, -12, 0, -12, 0,
ax_anim 2, 0, 206, 10, 0, 10, 0,
ax_anim 2, 0, 206, -10, 0, -10, 0,
ax_anim 2, 0, 206, 6, 0, 6, 0,
ax_anim 2, 0, 206, -6, 0, -6, 0,
ax_anim 2, 0, 206, 0, 0, 0, 0,
ax_anim_terminator
sHoundoomAnims_10_6:
ax_anim 2, 0, 207, 0, 0, 0, 0,
ax_anim 2, 0, 207, 6, -6, 6, -6,
ax_anim 2, 0, 207, -6, 6, -6, 6,
ax_anim 2, 0, 207, 10, -10, 10, -10,
ax_anim 2, 0, 207, -10, 10, -10, 10,
ax_anim 2, 0, 207, 12, -12, 12, -12,
ax_anim 3, 0, 207, -12, 12, -12, 12,
ax_anim 3, 0, 207, 13, -13, 13, -13,
ax_anim 3, 0, 207, -13, 13, -13, 13,
ax_anim 2, 0, 207, 12, -12, 12, -12,
ax_anim 3, 0, 207, -12, 12, -12, 12,
ax_anim 2, 0, 207, 10, -10, 10, -10,
ax_anim 2, 0, 207, -10, 10, -10, 10,
ax_anim 2, 0, 207, 6, -6, 6, -6,
ax_anim 2, 0, 207, -6, 6, -6, 6,
ax_anim 2, 0, 207, 0, 0, 0, 0,
ax_anim_terminator
sHoundoomAnims_10_7:
ax_anim 2, 0, 208, 0, 0, 0, 0,
ax_anim 2, 0, 208, 0, -6, 0, -6,
ax_anim 2, 0, 208, 0, 6, 0, 6,
ax_anim 2, 0, 208, 0, -10, 0, -10,
ax_anim 2, 0, 208, 0, 10, 0, 10,
ax_anim 2, 0, 208, 0, -12, 0, -12,
ax_anim 3, 0, 208, 0, 12, 0, 12,
ax_anim 3, 0, 208, 0, -13, 0, -13,
ax_anim 3, 0, 208, 0, 13, 0, 13,
ax_anim 2, 0, 208, 0, -12, 0, -12,
ax_anim 3, 0, 208, 0, 12, 0, 12,
ax_anim 2, 0, 208, 0, -10, 0, -10,
ax_anim 2, 0, 208, 0, 10, 0, 10,
ax_anim 2, 0, 208, 0, -6, 0, -6,
ax_anim 2, 0, 208, 0, 6, 0, 6,
ax_anim 2, 0, 208, 0, 0, 0, 0,
ax_anim_terminator
sHoundoomAnims_10_8:
ax_anim 2, 0, 209, 0, 0, 0, 0,
ax_anim 2, 0, 209, -6, -6, -6, -6,
ax_anim 2, 0, 209, 6, 6, 6, 6,
ax_anim 2, 0, 209, -10, -10, -10, -10,
ax_anim 2, 0, 209, 10, 10, 10, 10,
ax_anim 2, 0, 209, -12, -12, -12, -12,
ax_anim 3, 0, 209, 12, 12, 12, 12,
ax_anim 3, 0, 209, -13, -13, -13, -13,
ax_anim 3, 0, 209, 13, 13, 13, 13,
ax_anim 2, 0, 209, -12, -12, -12, -12,
ax_anim 3, 0, 209, 12, 12, 12, 12,
ax_anim 2, 0, 209, -10, -10, -10, -10,
ax_anim 2, 0, 209, 10, 10, 10, 10,
ax_anim 2, 0, 209, -6, -6, -6, -6,
ax_anim 2, 0, 209, 6, 6, 6, 6,
ax_anim 2, 0, 209, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sHoundoomAnims_11_1:
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 1, 0, 211, 0, -10, 0, 0,
ax_anim 2, 0, 211, 0, -16, 0, 0,
ax_anim 3, 0, 211, 0, -20, 0, 0,
ax_anim 4, 0, 211, 0, -21, 0, 0,
ax_anim 4, 0, 210, 0, -24, 0, 0,
ax_anim 3, 0, 212, 0, -23, 0, 0,
ax_anim 2, 0, 212, 0, -18, 0, 0,
ax_anim 1, 0, 212, 0, -12, 0, 0,
ax_anim 2, 2, 212, 0, 0, 0, 0,
ax_anim_terminator
sHoundoomAnims_11_2:
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 1, 0, 214, 0, -10, 0, 0,
ax_anim 2, 0, 214, 0, -16, 0, 0,
ax_anim 3, 0, 214, 0, -20, 0, 0,
ax_anim 4, 0, 214, 0, -21, 0, 0,
ax_anim 4, 0, 213, 0, -24, 0, 0,
ax_anim 3, 0, 215, 0, -24, 0, 0,
ax_anim 2, 0, 215, 0, -20, 0, 0,
ax_anim 1, 0, 215, 0, -12, 0, 0,
ax_anim 2, 2, 215, 0, 0, 0, 0,
ax_anim_terminator
sHoundoomAnims_11_3:
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 1, 0, 217, 0, -10, 0, 0,
ax_anim 2, 0, 217, 0, -16, 0, 0,
ax_anim 3, 0, 217, 0, -20, 0, 0,
ax_anim 4, 0, 217, 0, -21, 0, 0,
ax_anim 4, 0, 216, 0, -23, 0, 0,
ax_anim 3, 0, 218, 0, -20, 0, 0,
ax_anim 2, 0, 218, 0, -18, 0, 0,
ax_anim 1, 0, 218, 0, -12, 0, 0,
ax_anim 2, 2, 218, 0, 0, 0, 0,
ax_anim_terminator
sHoundoomAnims_11_4:
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 1, 0, 220, 0, -10, 0, 0,
ax_anim 2, 0, 220, 0, -16, 0, 0,
ax_anim 3, 0, 220, 0, -20, 0, 0,
ax_anim 4, 0, 220, 0, -21, 0, 0,
ax_anim 4, 0, 219, 0, -21, 0, 0,
ax_anim 3, 0, 221, 0, -19, 0, 0,
ax_anim 2, 0, 221, 0, -17, 0, 0,
ax_anim 1, 0, 221, 0, -11, 0, 0,
ax_anim 2, 2, 221, 0, 0, 0, 0,
ax_anim_terminator
sHoundoomAnims_11_5:
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 1, 0, 223, 0, -10, 0, 0,
ax_anim 2, 0, 223, 0, -16, 0, 0,
ax_anim 3, 0, 223, 0, -20, 0, 0,
ax_anim 4, 0, 223, 0, -21, 0, 0,
ax_anim 4, 0, 224, 0, -22, 0, 0,
ax_anim 3, 0, 224, 0, -21, 0, 0,
ax_anim 2, 0, 224, 0, -18, 0, 0,
ax_anim 1, 0, 224, 0, -11, 0, 0,
ax_anim 2, 2, 224, 0, 0, 0, 0,
ax_anim_terminator
sHoundoomAnims_11_6:
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 1, 0, 226, 0, -10, 0, 0,
ax_anim 2, 0, 226, 0, -16, 0, 0,
ax_anim 3, 0, 226, 0, -20, 0, 0,
ax_anim 4, 0, 226, 0, -21, 0, 0,
ax_anim 4, 0, 225, 0, -21, 0, 0,
ax_anim 3, 0, 227, 0, -19, 0, 0,
ax_anim 2, 0, 227, 0, -17, 0, 0,
ax_anim 1, 0, 227, 0, -11, 0, 0,
ax_anim 2, 2, 227, 0, 0, 0, 0,
ax_anim_terminator
sHoundoomAnims_11_7:
ax_anim 2, 0, 228, 0, 0, 0, 0,
ax_anim 1, 0, 229, 0, -10, 0, 0,
ax_anim 2, 0, 229, 0, -16, 0, 0,
ax_anim 3, 0, 229, 0, -20, 0, 0,
ax_anim 4, 0, 229, 0, -21, 0, 0,
ax_anim 4, 0, 228, 0, -23, 0, 0,
ax_anim 3, 0, 230, 0, -20, 0, 0,
ax_anim 2, 0, 230, 0, -18, 0, 0,
ax_anim 1, 0, 230, 0, -12, 0, 0,
ax_anim 2, 2, 230, 0, 0, 0, 0,
ax_anim_terminator
sHoundoomAnims_11_8:
ax_anim 2, 0, 231, 0, 0, 0, 0,
ax_anim 1, 0, 232, 0, -10, 0, 0,
ax_anim 2, 0, 232, 0, -16, 0, 0,
ax_anim 3, 0, 232, 0, -20, 0, 0,
ax_anim 4, 0, 232, 0, -21, 0, 0,
ax_anim 4, 0, 231, 0, -24, 0, 0,
ax_anim 3, 0, 233, 0, -24, 0, 0,
ax_anim 2, 0, 233, 0, -20, 0, 0,
ax_anim 1, 0, 233, 0, -12, 0, 0,
ax_anim 2, 2, 233, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sHoundoomAnims_12_1:
ax_anim 2, 0, 234, 1, 0, 1, 0,
ax_anim 2, 0, 234, 0, 0, 0, 0,
ax_anim 2, 0, 234, 1, 0, 1, 0,
ax_anim 2, 0, 234, 0, 0, 0, 0,
ax_anim 2, 0, 234, 1, 0, 1, 0,
ax_anim 2, 2, 234, 0, 0, 0, 0,
ax_anim 2, 0, 234, 1, 0, 1, 0,
ax_anim 2, 0, 234, 0, 0, 0, 0,
ax_anim 2, 0, 234, 1, 0, 1, 0,
ax_anim 2, 1, 234, 0, 0, 0, 0,
ax_anim_terminator
sHoundoomAnims_12_2:
ax_anim 2, 0, 241, 1, -1, 1, -1,
ax_anim 2, 0, 241, 0, 0, 0, 0,
ax_anim 2, 0, 241, 1, -1, 1, -1,
ax_anim 2, 0, 241, 0, 0, 0, 0,
ax_anim 2, 0, 241, 1, -1, 1, -1,
ax_anim 2, 2, 241, 0, 0, 0, 0,
ax_anim 2, 0, 241, 1, -1, 1, -1,
ax_anim 2, 0, 241, 0, 0, 0, 0,
ax_anim 2, 0, 241, 1, -1, 1, -1,
ax_anim 2, 1, 241, 0, 0, 0, 0,
ax_anim_terminator
sHoundoomAnims_12_3:
ax_anim 2, 0, 240, 0, -1, 0, -1,
ax_anim 2, 0, 240, 0, 0, 0, 0,
ax_anim 2, 0, 240, 0, -1, 0, -1,
ax_anim 2, 0, 240, 0, 0, 0, 0,
ax_anim 2, 0, 240, 0, -1, 0, -1,
ax_anim 2, 2, 240, 0, 0, 0, 0,
ax_anim 2, 0, 240, 0, -1, 0, -1,
ax_anim 2, 0, 240, 0, 0, 0, 0,
ax_anim 2, 0, 240, 0, -1, 0, -1,
ax_anim 2, 1, 240, 0, 0, 0, 0,
ax_anim_terminator
sHoundoomAnims_12_4:
ax_anim 2, 0, 239, -1, -1, -1, -1,
ax_anim 2, 0, 239, 0, 0, 0, 0,
ax_anim 2, 0, 239, -1, -1, -1, -1,
ax_anim 2, 0, 239, 0, 0, 0, 0,
ax_anim 2, 0, 239, -1, -1, -1, -1,
ax_anim 2, 2, 239, 0, 0, 0, 0,
ax_anim 2, 0, 239, -1, -1, -1, -1,
ax_anim 2, 0, 239, 0, 0, 0, 0,
ax_anim 2, 0, 239, -1, -1, -1, -1,
ax_anim 2, 1, 239, 0, 0, 0, 0,
ax_anim_terminator
sHoundoomAnims_12_5:
ax_anim 2, 0, 238, 1, 0, 1, 0,
ax_anim 2, 0, 238, 0, 0, 0, 0,
ax_anim 2, 0, 238, 1, 0, 1, 0,
ax_anim 2, 0, 238, 0, 0, 0, 0,
ax_anim 2, 0, 238, 1, 0, 1, 0,
ax_anim 2, 2, 238, 0, 0, 0, 0,
ax_anim 2, 0, 238, 1, 0, 1, 0,
ax_anim 2, 0, 238, 0, 0, 0, 0,
ax_anim 2, 0, 238, 1, 0, 1, 0,
ax_anim 2, 1, 238, 0, 0, 0, 0,
ax_anim_terminator
sHoundoomAnims_12_6:
ax_anim 2, 0, 237, 1, -1, 1, -1,
ax_anim 2, 0, 237, 0, 0, 0, 0,
ax_anim 2, 0, 237, 1, -1, 1, -1,
ax_anim 2, 0, 237, 0, 0, 0, 0,
ax_anim 2, 0, 237, 1, -1, 1, -1,
ax_anim 2, 2, 237, 0, 0, 0, 0,
ax_anim 2, 0, 237, 1, -1, 1, -1,
ax_anim 2, 0, 237, 0, 0, 0, 0,
ax_anim 2, 0, 237, 1, -1, 1, -1,
ax_anim 2, 1, 237, 0, 0, 0, 0,
ax_anim_terminator
sHoundoomAnims_12_7:
ax_anim 2, 0, 236, 0, -1, 0, -1,
ax_anim 2, 0, 236, 0, 0, 0, 0,
ax_anim 2, 0, 236, 0, -1, 0, -1,
ax_anim 2, 0, 236, 0, 0, 0, 0,
ax_anim 2, 0, 236, 0, -1, 0, -1,
ax_anim 2, 2, 236, 0, 0, 0, 0,
ax_anim 2, 0, 236, 0, -1, 0, -1,
ax_anim 2, 0, 236, 0, 0, 0, 0,
ax_anim 2, 0, 236, 0, -1, 0, -1,
ax_anim 2, 1, 236, 0, 0, 0, 0,
ax_anim_terminator
sHoundoomAnims_12_8:
ax_anim 2, 0, 235, -1, -1, -1, -1,
ax_anim 2, 0, 235, 0, 0, 0, 0,
ax_anim 2, 0, 235, -1, -1, -1, -1,
ax_anim 2, 0, 235, 0, 0, 0, 0,
ax_anim 2, 0, 235, -1, -1, -1, -1,
ax_anim 2, 2, 235, 0, 0, 0, 0,
ax_anim 2, 0, 235, -1, -1, -1, -1,
ax_anim 2, 0, 235, 0, 0, 0, 0,
ax_anim 2, 0, 235, -1, -1, -1, -1,
ax_anim 2, 1, 235, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sHoundoomAnims_13_1:
ax_anim 2, 0, 242, 0, 0, 0, 0,
ax_anim 2, 0, 243, 0, 0, 0, 0,
ax_anim 2, 0, 244, 0, 0, 0, 0,
ax_anim 2, 0, 245, 0, 0, 0, 0,
ax_anim 2, 0, 246, 0, 0, 0, 0,
ax_anim 2, 0, 247, 0, 0, 0, 0,
ax_anim 2, 0, 248, 0, 0, 0, 0,
ax_anim 2, 0, 249, 0, 0, 0, 0,
ax_anim 2, 2, 242, 0, 0, 0, 0,
ax_anim_terminator
sHoundoomAnims_13_2:
ax_anim 2, 0, 249, 0, 0, 0, 0,
ax_anim 2, 0, 242, 0, 0, 0, 0,
ax_anim 2, 0, 243, 0, 0, 0, 0,
ax_anim 2, 0, 244, 0, 0, 0, 0,
ax_anim 2, 0, 245, 0, 0, 0, 0,
ax_anim 2, 0, 246, 0, 0, 0, 0,
ax_anim 2, 0, 247, 0, 0, 0, 0,
ax_anim 2, 0, 248, 0, 0, 0, 0,
ax_anim 2, 2, 249, 0, 0, 0, 0,
ax_anim_terminator
sHoundoomAnims_13_3:
ax_anim 2, 0, 248, 0, 0, 0, 0,
ax_anim 2, 0, 249, 0, 0, 0, 0,
ax_anim 2, 0, 242, 0, 0, 0, 0,
ax_anim 2, 0, 243, 0, 0, 0, 0,
ax_anim 2, 0, 244, 0, 0, 0, 0,
ax_anim 2, 0, 245, 0, 0, 0, 0,
ax_anim 2, 0, 246, 0, 0, 0, 0,
ax_anim 2, 0, 247, 0, 0, 0, 0,
ax_anim 2, 2, 248, 0, 0, 0, 0,
ax_anim_terminator
sHoundoomAnims_13_4:
ax_anim 2, 0, 247, 0, 0, 0, 0,
ax_anim 2, 0, 248, 0, 0, 0, 0,
ax_anim 2, 0, 249, 0, 0, 0, 0,
ax_anim 2, 0, 242, 0, 0, 0, 0,
ax_anim 2, 0, 243, 0, 0, 0, 0,
ax_anim 2, 0, 244, 0, 0, 0, 0,
ax_anim 2, 0, 245, 0, 0, 0, 0,
ax_anim 2, 0, 246, 0, 0, 0, 0,
ax_anim 2, 2, 247, 0, 0, 0, 0,
ax_anim_terminator
sHoundoomAnims_13_5:
ax_anim 2, 0, 246, 0, 0, 0, 0,
ax_anim 2, 0, 247, 0, 0, 0, 0,
ax_anim 2, 0, 248, 0, 0, 0, 0,
ax_anim 2, 0, 249, 0, 0, 0, 0,
ax_anim 2, 0, 242, 0, 0, 0, 0,
ax_anim 2, 0, 243, 0, 0, 0, 0,
ax_anim 2, 0, 244, 0, 0, 0, 0,
ax_anim 2, 0, 245, 0, 0, 0, 0,
ax_anim 2, 2, 246, 0, 0, 0, 0,
ax_anim_terminator
sHoundoomAnims_13_6:
ax_anim 2, 0, 245, 0, 0, 0, 0,
ax_anim 2, 0, 246, 0, 0, 0, 0,
ax_anim 2, 0, 247, 0, 0, 0, 0,
ax_anim 2, 0, 248, 0, 0, 0, 0,
ax_anim 2, 0, 249, 0, 0, 0, 0,
ax_anim 2, 0, 242, 0, 0, 0, 0,
ax_anim 2, 0, 243, 0, 0, 0, 0,
ax_anim 2, 0, 244, 0, 0, 0, 0,
ax_anim 2, 2, 245, 0, 0, 0, 0,
ax_anim_terminator
sHoundoomAnims_13_7:
ax_anim 2, 0, 244, 0, 0, 0, 0,
ax_anim 2, 0, 245, 0, 0, 0, 0,
ax_anim 2, 0, 246, 0, 0, 0, 0,
ax_anim 2, 0, 247, 0, 0, 0, 0,
ax_anim 2, 0, 248, 0, 0, 0, 0,
ax_anim 2, 0, 249, 0, 0, 0, 0,
ax_anim 2, 0, 242, 0, 0, 0, 0,
ax_anim 2, 0, 243, 0, 0, 0, 0,
ax_anim 2, 2, 244, 0, 0, 0, 0,
ax_anim_terminator
sHoundoomAnims_13_8:
ax_anim 2, 0, 243, 0, 0, 0, 0,
ax_anim 2, 0, 244, 0, 0, 0, 0,
ax_anim 2, 0, 245, 0, 0, 0, 0,
ax_anim 2, 0, 246, 0, 0, 0, 0,
ax_anim 2, 0, 247, 0, 0, 0, 0,
ax_anim 2, 0, 248, 0, 0, 0, 0,
ax_anim 2, 0, 249, 0, 0, 0, 0,
ax_anim 2, 0, 242, 0, 0, 0, 0,
ax_anim 2, 2, 243, 0, 0, 0, 0,
ax_anim_terminator
sHoundoomGfx1:
.incbin "baserom.gba", 0xF4BF38, 0x20
sHoundoomSprites1:
ax_sprite sHoundoomGfx1, 0x20
ax_sprite_terminator
sHoundoomGfx2:
.incbin "baserom.gba", 0xF4BF68, 0x100
sHoundoomSprites2:
ax_sprite sHoundoomGfx2, 0x100
ax_sprite_terminator
sHoundoomGfx3:
.incbin "baserom.gba", 0xF4C078, 0x200
sHoundoomSprites3:
ax_sprite sHoundoomGfx3, 0x200
ax_sprite_terminator
sHoundoomGfx4:
.incbin "baserom.gba", 0xF4C288, 0x200
sHoundoomSprites4:
ax_sprite sHoundoomGfx4, 0x200
ax_sprite_terminator
sHoundoomGfx5:
.incbin "baserom.gba", 0xF4C498, 0x20
sHoundoomSprites5:
ax_sprite sHoundoomGfx5, 0x20
ax_sprite_terminator
sHoundoomGfx6:
.incbin "baserom.gba", 0xF4C4C8, 0x40
sHoundoomSprites6:
ax_sprite sHoundoomGfx6, 0x40
ax_sprite_terminator
sHoundoomGfx7:
.incbin "baserom.gba", 0xF4C518, 0x80
sHoundoomSprites7:
ax_sprite sHoundoomGfx7, 0x80
ax_sprite_terminator
sHoundoomGfx8:
.incbin "baserom.gba", 0xF4C5A8, 0x100
sHoundoomSprites8:
ax_sprite sHoundoomGfx8, 0x100
ax_sprite_terminator
sHoundoomGfx9:
.incbin "baserom.gba", 0xF4C6B8, 0x200
sHoundoomSprites9:
ax_sprite sHoundoomGfx9, 0x200
ax_sprite_terminator
sHoundoomGfx10:
.incbin "baserom.gba", 0xF4C8C8, 0x20
sHoundoomSprites10:
ax_sprite sHoundoomGfx10, 0x20
ax_sprite_terminator
sHoundoomGfx11:
.incbin "baserom.gba", 0xF4C8F8, 0x40
sHoundoomSprites11:
ax_sprite sHoundoomGfx11, 0x40
ax_sprite_terminator
sHoundoomGfx12:
.incbin "baserom.gba", 0xF4C948, 0x80
sHoundoomSprites12:
ax_sprite sHoundoomGfx12, 0x80
ax_sprite_terminator
sHoundoomGfx13:
.incbin "baserom.gba", 0xF4C9D8, 0x100
sHoundoomSprites13:
ax_sprite sHoundoomGfx13, 0x100
ax_sprite_terminator
sHoundoomGfx14:
.incbin "baserom.gba", 0xF4CAE8, 0x20
sHoundoomSprites14:
ax_sprite sHoundoomGfx14, 0x20
ax_sprite_terminator
sHoundoomGfx15:
.incbin "baserom.gba", 0xF4CB18, 0x20
sHoundoomSprites15:
ax_sprite sHoundoomGfx15, 0x20
ax_sprite_terminator
sHoundoomGfx16:
.incbin "baserom.gba", 0xF4CB48, 0x40
sHoundoomSprites16:
ax_sprite sHoundoomGfx16, 0x40
ax_sprite_terminator
sHoundoomGfx17:
.incbin "baserom.gba", 0xF4CB98, 0x80
sHoundoomSprites17:
ax_sprite sHoundoomGfx17, 0x80
ax_sprite_terminator
sHoundoomGfx18:
.incbin "baserom.gba", 0xF4CC28, 0x100
sHoundoomSprites18:
ax_sprite sHoundoomGfx18, 0x100
ax_sprite_terminator
sHoundoomGfx19:
.incbin "baserom.gba", 0xF4CD38, 0x20
sHoundoomSprites19:
ax_sprite sHoundoomGfx19, 0x20
ax_sprite_terminator
sHoundoomGfx20:
.incbin "baserom.gba", 0xF4CD68, 0x20
sHoundoomSprites20:
ax_sprite sHoundoomGfx20, 0x20
ax_sprite_terminator
sHoundoomGfx21:
.incbin "baserom.gba", 0xF4CD98, 0x40
sHoundoomSprites21:
ax_sprite sHoundoomGfx21, 0x40
ax_sprite_terminator
sHoundoomGfx22:
.incbin "baserom.gba", 0xF4CDE8, 0x80
sHoundoomSprites22:
ax_sprite sHoundoomGfx22, 0x80
ax_sprite_terminator
sHoundoomGfx23:
.incbin "baserom.gba", 0xF4CE78, 0x100
sHoundoomSprites23:
ax_sprite sHoundoomGfx23, 0x100
ax_sprite_terminator
sHoundoomGfx24:
.incbin "baserom.gba", 0xF4CF88, 0x200
sHoundoomSprites24:
ax_sprite sHoundoomGfx24, 0x200
ax_sprite_terminator
sHoundoomGfx25:
.incbin "baserom.gba", 0xF4D198, 0x20
sHoundoomSprites25:
ax_sprite sHoundoomGfx25, 0x20
ax_sprite_terminator
sHoundoomGfx26:
.incbin "baserom.gba", 0xF4D1C8, 0x20
sHoundoomSprites26:
ax_sprite sHoundoomGfx26, 0x20
ax_sprite_terminator
sHoundoomGfx27:
.incbin "baserom.gba", 0xF4D1F8, 0x20
sHoundoomSprites27:
ax_sprite sHoundoomGfx27, 0x20
ax_sprite_terminator
sHoundoomGfx28:
.incbin "baserom.gba", 0xF4D228, 0x80
sHoundoomSprites28:
ax_sprite sHoundoomGfx28, 0x80
ax_sprite_terminator
sHoundoomGfx29:
.incbin "baserom.gba", 0xF4D2B8, 0x100
sHoundoomSprites29:
ax_sprite sHoundoomGfx29, 0x100
ax_sprite_terminator
sHoundoomGfx30:
.incbin "baserom.gba", 0xF4D3C8, 0x20
sHoundoomSprites30:
ax_sprite sHoundoomGfx30, 0x20
ax_sprite_terminator
sHoundoomGfx31:
.incbin "baserom.gba", 0xF4D3F8, 0x20
sHoundoomSprites31:
ax_sprite sHoundoomGfx31, 0x20
ax_sprite_terminator
sHoundoomGfx32:
.incbin "baserom.gba", 0xF4D428, 0x40
sHoundoomSprites32:
ax_sprite sHoundoomGfx32, 0x40
ax_sprite_terminator
sHoundoomGfx33:
.incbin "baserom.gba", 0xF4D478, 0x80
sHoundoomSprites33:
ax_sprite sHoundoomGfx33, 0x80
ax_sprite_terminator
sHoundoomGfx34:
.incbin "baserom.gba", 0xF4D508, 0x100
sHoundoomSprites34:
ax_sprite sHoundoomGfx34, 0x100
ax_sprite_terminator
sHoundoomGfx35:
.incbin "baserom.gba", 0xF4D618, 0x20
sHoundoomSprites35:
ax_sprite sHoundoomGfx35, 0x20
ax_sprite_terminator
sHoundoomGfx36:
.incbin "baserom.gba", 0xF4D648, 0x40
sHoundoomSprites36:
ax_sprite sHoundoomGfx36, 0x40
ax_sprite_terminator
sHoundoomGfx37:
.incbin "baserom.gba", 0xF4D698, 0x80
sHoundoomSprites37:
ax_sprite sHoundoomGfx37, 0x80
ax_sprite_terminator
sHoundoomGfx38:
.incbin "baserom.gba", 0xF4D728, 0x100
sHoundoomSprites38:
ax_sprite sHoundoomGfx38, 0x100
ax_sprite_terminator
sHoundoomGfx39:
.incbin "baserom.gba", 0xF4D838, 0x40
sHoundoomSprites39:
ax_sprite sHoundoomGfx39, 0x40
ax_sprite_terminator
sHoundoomGfx40:
.incbin "baserom.gba", 0xF4D888, 0x100
sHoundoomSprites40:
ax_sprite sHoundoomGfx40, 0x100
ax_sprite_terminator
sHoundoomGfx41:
.incbin "baserom.gba", 0xF4D998, 0x40
sHoundoomSprites41:
ax_sprite sHoundoomGfx41, 0x40
ax_sprite_terminator
sHoundoomGfx42:
.incbin "baserom.gba", 0xF4D9E8, 0x100
sHoundoomSprites42:
ax_sprite sHoundoomGfx42, 0x100
ax_sprite_terminator
sHoundoomGfx43:
.incbin "baserom.gba", 0xF4DAF8, 0x20
sHoundoomSprites43:
ax_sprite sHoundoomGfx43, 0x20
ax_sprite_terminator
sHoundoomGfx44:
.incbin "baserom.gba", 0xF4DB28, 0x20
sHoundoomSprites44:
ax_sprite sHoundoomGfx44, 0x20
ax_sprite_terminator
sHoundoomGfx45:
.incbin "baserom.gba", 0xF4DB58, 0x40
sHoundoomSprites45:
ax_sprite sHoundoomGfx45, 0x40
ax_sprite_terminator
sHoundoomGfx46:
.incbin "baserom.gba", 0xF4DBA8, 0x100
sHoundoomSprites46:
ax_sprite sHoundoomGfx46, 0x100
ax_sprite_terminator
sHoundoomGfx47:
.incbin "baserom.gba", 0xF4DCB8, 0x60
sHoundoomGfx47_1:
.incbin "baserom.gba", 0xF4DD18, 0x40
sHoundoomGfx47_2:
.incbin "baserom.gba", 0xF4DD58, 0x40
sHoundoomGfx47_3:
.incbin "baserom.gba", 0xF4DD98, 0x60
sHoundoomSprites47:
ax_sprite sHoundoomGfx47, 0x60
ax_sprite 0, 0x20
ax_sprite sHoundoomGfx47_1, 0x40
ax_sprite 0, 0x40
ax_sprite sHoundoomGfx47_2, 0x40
ax_sprite 0, 0x40
ax_sprite sHoundoomGfx47_3, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sHoundoomGfx48:
.incbin "baserom.gba", 0xF4DE40, 0x60
sHoundoomGfx48_1:
.incbin "baserom.gba", 0xF4DEA0, 0x140
sHoundoomSprites48:
ax_sprite sHoundoomGfx48, 0x60
ax_sprite 0, 0x20
ax_sprite sHoundoomGfx48_1, 0x140
ax_sprite 0, 0x40
ax_sprite_terminator
sHoundoomGfx49:
.incbin "baserom.gba", 0xF4E008, 0x40
sHoundoomSprites49:
ax_sprite sHoundoomGfx49, 0x40
ax_sprite_terminator
sHoundoomGfx50:
.incbin "baserom.gba", 0xF4E058, 0x80
sHoundoomSprites50:
ax_sprite sHoundoomGfx50, 0x80
ax_sprite_terminator
sHoundoomGfx51:
.incbin "baserom.gba", 0xF4E0E8, 0x20
sHoundoomSprites51:
ax_sprite sHoundoomGfx51, 0x20
ax_sprite_terminator
sHoundoomGfx52:
.incbin "baserom.gba", 0xF4E118, 0x80
sHoundoomSprites52:
ax_sprite sHoundoomGfx52, 0x80
ax_sprite_terminator
sHoundoomGfx53:
.incbin "baserom.gba", 0xF4E1A8, 0x40
sHoundoomSprites53:
ax_sprite sHoundoomGfx53, 0x40
ax_sprite_terminator
sHoundoomGfx54:
.incbin "baserom.gba", 0xF4E1F8, 0x20
sHoundoomSprites54:
ax_sprite sHoundoomGfx54, 0x20
ax_sprite_terminator
sHoundoomGfx55:
.incbin "baserom.gba", 0xF4E228, 0x20
sHoundoomSprites55:
ax_sprite sHoundoomGfx55, 0x20
ax_sprite_terminator
sHoundoomGfx56:
.incbin "baserom.gba", 0xF4E258, 0x100
sHoundoomSprites56:
ax_sprite sHoundoomGfx56, 0x100
ax_sprite_terminator
sHoundoomGfx57:
.incbin "baserom.gba", 0xF4E368, 0x80
sHoundoomSprites57:
ax_sprite sHoundoomGfx57, 0x80
ax_sprite_terminator
sHoundoomGfx58:
.incbin "baserom.gba", 0xF4E3F8, 0x20
sHoundoomSprites58:
ax_sprite sHoundoomGfx58, 0x20
ax_sprite_terminator
sHoundoomGfx59:
.incbin "baserom.gba", 0xF4E428, 0x20
sHoundoomSprites59:
ax_sprite sHoundoomGfx59, 0x20
ax_sprite_terminator
sHoundoomGfx60:
.incbin "baserom.gba", 0xF4E458, 0x40
sHoundoomSprites60:
ax_sprite sHoundoomGfx60, 0x40
ax_sprite_terminator
sHoundoomGfx61:
.incbin "baserom.gba", 0xF4E4A8, 0x20
sHoundoomSprites61:
ax_sprite sHoundoomGfx61, 0x20
ax_sprite_terminator
sHoundoomGfx62:
.incbin "baserom.gba", 0xF4E4D8, 0x20
sHoundoomSprites62:
ax_sprite sHoundoomGfx62, 0x20
ax_sprite_terminator
sHoundoomGfx63:
.incbin "baserom.gba", 0xF4E508, 0x100
sHoundoomSprites63:
ax_sprite sHoundoomGfx63, 0x100
ax_sprite_terminator
sHoundoomGfx64:
.incbin "baserom.gba", 0xF4E618, 0x60
sHoundoomGfx64_1:
.incbin "baserom.gba", 0xF4E678, 0x60
sHoundoomGfx64_2:
.incbin "baserom.gba", 0xF4E6D8, 0x40
sHoundoomGfx64_3:
.incbin "baserom.gba", 0xF4E718, 0x40
sHoundoomSprites64:
ax_sprite sHoundoomGfx64, 0x60
ax_sprite 0, 0x20
ax_sprite sHoundoomGfx64_1, 0x60
ax_sprite 0, 0x20
ax_sprite sHoundoomGfx64_2, 0x40
ax_sprite 0, 0x40
ax_sprite sHoundoomGfx64_3, 0x40
ax_sprite 0, 0x40
ax_sprite_terminator
sHoundoomGfx65:
.incbin "baserom.gba", 0xF4E7A0, 0x100
sHoundoomSprites65:
ax_sprite sHoundoomGfx65, 0x100
ax_sprite_terminator
sHoundoomGfx66:
.incbin "baserom.gba", 0xF4E8B0, 0x20
sHoundoomSprites66:
ax_sprite sHoundoomGfx66, 0x20
ax_sprite_terminator
sHoundoomGfx67:
.incbin "baserom.gba", 0xF4E8E0, 0x60
sHoundoomGfx67_1:
.incbin "baserom.gba", 0xF4E940, 0x140
sHoundoomSprites67:
ax_sprite sHoundoomGfx67, 0x60
ax_sprite 0, 0x20
ax_sprite sHoundoomGfx67_1, 0x140
ax_sprite 0, 0x40
ax_sprite_terminator
sHoundoomGfx68:
.incbin "baserom.gba", 0xF4EAA8, 0x100
sHoundoomSprites68:
ax_sprite sHoundoomGfx68, 0x100
ax_sprite_terminator
sHoundoomGfx69:
.incbin "baserom.gba", 0xF4EBB8, 0x80
sHoundoomSprites69:
ax_sprite sHoundoomGfx69, 0x80
ax_sprite_terminator
sHoundoomGfx70:
.incbin "baserom.gba", 0xF4EC48, 0x20
sHoundoomSprites70:
ax_sprite sHoundoomGfx70, 0x20
ax_sprite_terminator
sHoundoomGfx71:
.incbin "baserom.gba", 0xF4EC78, 0x20
sHoundoomSprites71:
ax_sprite sHoundoomGfx71, 0x20
ax_sprite_terminator
sHoundoomGfx72:
.incbin "baserom.gba", 0xF4ECA8, 0x20
sHoundoomSprites72:
ax_sprite sHoundoomGfx72, 0x20
ax_sprite_terminator
sHoundoomGfx73:
.incbin "baserom.gba", 0xF4ECD8, 0x100
sHoundoomSprites73:
ax_sprite sHoundoomGfx73, 0x100
ax_sprite_terminator
sHoundoomGfx74:
.incbin "baserom.gba", 0xF4EDE8, 0x80
sHoundoomSprites74:
ax_sprite sHoundoomGfx74, 0x80
ax_sprite_terminator
sHoundoomGfx75:
.incbin "baserom.gba", 0xF4EE78, 0x20
sHoundoomSprites75:
ax_sprite sHoundoomGfx75, 0x20
ax_sprite_terminator
sHoundoomGfx76:
.incbin "baserom.gba", 0xF4EEA8, 0x20
sHoundoomSprites76:
ax_sprite sHoundoomGfx76, 0x20
ax_sprite_terminator
sHoundoomGfx77:
.incbin "baserom.gba", 0xF4EED8, 0x100
sHoundoomSprites77:
ax_sprite sHoundoomGfx77, 0x100
ax_sprite_terminator
sHoundoomGfx78:
.incbin "baserom.gba", 0xF4EFE8, 0x20
sHoundoomSprites78:
ax_sprite sHoundoomGfx78, 0x20
ax_sprite_terminator
sHoundoomGfx79:
.incbin "baserom.gba", 0xF4F018, 0x40
sHoundoomSprites79:
ax_sprite sHoundoomGfx79, 0x40
ax_sprite_terminator
sHoundoomGfx80:
.incbin "baserom.gba", 0xF4F068, 0x40
sHoundoomSprites80:
ax_sprite sHoundoomGfx80, 0x40
ax_sprite_terminator
sHoundoomGfx81:
.incbin "baserom.gba", 0xF4F0B8, 0x40
sHoundoomSprites81:
ax_sprite sHoundoomGfx81, 0x40
ax_sprite_terminator
sHoundoomGfx82:
.incbin "baserom.gba", 0xF4F108, 0x100
sHoundoomSprites82:
ax_sprite sHoundoomGfx82, 0x100
ax_sprite_terminator
sHoundoomGfx83:
.incbin "baserom.gba", 0xF4F218, 0x20
sHoundoomGfx83_1:
.incbin "baserom.gba", 0xF4F238, 0x20
sHoundoomSprites83:
ax_sprite sHoundoomGfx83, 0x20
ax_sprite 0, 0x20
ax_sprite sHoundoomGfx83_1, 0x20
ax_sprite 0, 0x20
ax_sprite_terminator
sHoundoomGfx84:
.incbin "baserom.gba", 0xF4F280, 0x20
sHoundoomSprites84:
ax_sprite sHoundoomGfx84, 0x20
ax_sprite_terminator
sHoundoomGfx85:
.incbin "baserom.gba", 0xF4F2B0, 0x40
sHoundoomSprites85:
ax_sprite sHoundoomGfx85, 0x40
ax_sprite_terminator
sHoundoomGfx86:
.incbin "baserom.gba", 0xF4F300, 0x40
sHoundoomGfx86_1:
.incbin "baserom.gba", 0xF4F340, 0xA0
sHoundoomSprites86:
ax_sprite sHoundoomGfx86, 0x40
ax_sprite 0, 0x20
ax_sprite sHoundoomGfx86_1, 0xa0
ax_sprite_terminator
sHoundoomGfx87:
.incbin "baserom.gba", 0xF4F400, 0x20
sHoundoomSprites87:
ax_sprite sHoundoomGfx87, 0x20
ax_sprite_terminator
sHoundoomGfx88:
.incbin "baserom.gba", 0xF4F430, 0x20
sHoundoomGfx88_1:
.incbin "baserom.gba", 0xF4F450, 0x40
sHoundoomSprites88:
ax_sprite sHoundoomGfx88, 0x20
ax_sprite 0, 0x20
ax_sprite sHoundoomGfx88_1, 0x40
ax_sprite_terminator
sHoundoomGfx89:
.incbin "baserom.gba", 0xF4F4B0, 0x40
sHoundoomSprites89:
ax_sprite sHoundoomGfx89, 0x40
ax_sprite_terminator
sHoundoomGfx90:
.incbin "baserom.gba", 0xF4F500, 0x20
sHoundoomSprites90:
ax_sprite sHoundoomGfx90, 0x20
ax_sprite_terminator
sHoundoomGfx91:
.incbin "baserom.gba", 0xF4F530, 0x20
sHoundoomSprites91:
ax_sprite sHoundoomGfx91, 0x20
ax_sprite_terminator
sHoundoomGfx92:
.incbin "baserom.gba", 0xF4F560, 0x100
sHoundoomSprites92:
ax_sprite sHoundoomGfx92, 0x100
ax_sprite_terminator
sHoundoomGfx93:
.incbin "baserom.gba", 0xF4F670, 0x20
sHoundoomSprites93:
ax_sprite sHoundoomGfx93, 0x20
ax_sprite 0, 0x20
ax_sprite_terminator
sHoundoomGfx94:
.incbin "baserom.gba", 0xF4F6A8, 0x100
sHoundoomSprites94:
ax_sprite sHoundoomGfx94, 0x100
ax_sprite_terminator
sHoundoomGfx95:
.incbin "baserom.gba", 0xF4F7B8, 0x40
sHoundoomSprites95:
ax_sprite sHoundoomGfx95, 0x40
ax_sprite_terminator
sHoundoomGfx96:
.incbin "baserom.gba", 0xF4F808, 0x200
sHoundoomSprites96:
ax_sprite sHoundoomGfx96, 0x200
ax_sprite_terminator
sHoundoomGfx97:
.incbin "baserom.gba", 0xF4FA18, 0x200
sHoundoomSprites97:
ax_sprite sHoundoomGfx97, 0x200
ax_sprite_terminator
sHoundoomGfx98:
.incbin "baserom.gba", 0xF4FC28, 0x100
sHoundoomSprites98:
ax_sprite sHoundoomGfx98, 0x100
ax_sprite_terminator
sHoundoomGfx99:
.incbin "baserom.gba", 0xF4FD38, 0x80
sHoundoomSprites99:
ax_sprite sHoundoomGfx99, 0x80
ax_sprite_terminator
sHoundoomGfx100:
.incbin "baserom.gba", 0xF4FDC8, 0x20
sHoundoomSprites100:
ax_sprite sHoundoomGfx100, 0x20
ax_sprite_terminator
sHoundoomGfx101:
.incbin "baserom.gba", 0xF4FDF8, 0x20
sHoundoomSprites101:
ax_sprite sHoundoomGfx101, 0x20
ax_sprite_terminator
sHoundoomGfx102:
.incbin "baserom.gba", 0xF4FE28, 0x200
sHoundoomSprites102:
ax_sprite sHoundoomGfx102, 0x200
ax_sprite_terminator
sHoundoomGfx103:
.incbin "baserom.gba", 0xF50038, 0x200
sHoundoomSprites103:
ax_sprite sHoundoomGfx103, 0x200
ax_sprite_terminator
sHoundoomGfx104:
.incbin "baserom.gba", 0xF50248, 0x100
sHoundoomSprites104:
ax_sprite sHoundoomGfx104, 0x100
ax_sprite_terminator
sHoundoomGfx105:
.incbin "baserom.gba", 0xF50358, 0x20
sHoundoomSprites105:
ax_sprite sHoundoomGfx105, 0x20
ax_sprite_terminator
sHoundoomGfx106:
.incbin "baserom.gba", 0xF50388, 0x20
sHoundoomSprites106:
ax_sprite sHoundoomGfx106, 0x20
ax_sprite_terminator
sHoundoomGfx107:
.incbin "baserom.gba", 0xF503B8, 0x40
sHoundoomSprites107:
ax_sprite sHoundoomGfx107, 0x40
ax_sprite_terminator
sHoundoomGfx108:
.incbin "baserom.gba", 0xF50408, 0x80
sHoundoomSprites108:
ax_sprite sHoundoomGfx108, 0x80
ax_sprite_terminator
sHoundoomGfx109:
.incbin "baserom.gba", 0xF50498, 0x20
sHoundoomSprites109:
ax_sprite sHoundoomGfx109, 0x20
ax_sprite_terminator
sHoundoomGfx110:
.incbin "baserom.gba", 0xF504C8, 0x100
sHoundoomSprites110:
ax_sprite sHoundoomGfx110, 0x100
ax_sprite_terminator
sHoundoomGfx111:
.incbin "baserom.gba", 0xF505D8, 0x80
sHoundoomSprites111:
ax_sprite sHoundoomGfx111, 0x80
ax_sprite_terminator
sAxPosesHoundoom:
.4byte sHoundoomPose1
.4byte sHoundoomPose2
.4byte sHoundoomPose3
.4byte sHoundoomPose4
.4byte sHoundoomPose5
.4byte sHoundoomPose6
.4byte sHoundoomPose7
.4byte sHoundoomPose8
.4byte sHoundoomPose9
.4byte sHoundoomPose10
.4byte sHoundoomPose11
.4byte sHoundoomPose12
.4byte sHoundoomPose13
.4byte sHoundoomPose14
.4byte sHoundoomPose15
.4byte sHoundoomPose16
.4byte sHoundoomPose17
.4byte sHoundoomPose18
.4byte sHoundoomPose19
.4byte sHoundoomPose20
.4byte sHoundoomPose21
.4byte sHoundoomPose22
.4byte sHoundoomPose23
.4byte sHoundoomPose24
.4byte sHoundoomPose25
.4byte sHoundoomPose26
.4byte sHoundoomPose27
.4byte sHoundoomPose28
.4byte sHoundoomPose29
.4byte sHoundoomPose30
.4byte sHoundoomPose31
.4byte sHoundoomPose32
.4byte sHoundoomPose33
.4byte sHoundoomPose34
.4byte sHoundoomPose35
.4byte sHoundoomPose36
.4byte sHoundoomPose37
.4byte sHoundoomPose38
.4byte sHoundoomPose39
.4byte sHoundoomPose40
.4byte sHoundoomPose41
.4byte sHoundoomPose42
.4byte sHoundoomPose43
.4byte sHoundoomPose44
.4byte sHoundoomPose45
.4byte sHoundoomPose46
.4byte sHoundoomPose47
.4byte sHoundoomPose48
.4byte sHoundoomPose49
.4byte sHoundoomPose50
.4byte sHoundoomPose51
.4byte sHoundoomPose52
.4byte sHoundoomPose53
.4byte sHoundoomPose54
.4byte sHoundoomPose55
.4byte sHoundoomPose56
.4byte sHoundoomPose57
.4byte sHoundoomPose58
.4byte sHoundoomPose59
.4byte sHoundoomPose60
.4byte sHoundoomPose61
.4byte sHoundoomPose62
.4byte sHoundoomPose63
.4byte sHoundoomPose64
.4byte sHoundoomPose65
.4byte sHoundoomPose66
.4byte sHoundoomPose67
.4byte sHoundoomPose68
.4byte sHoundoomPose69
.4byte sHoundoomPose70
.4byte sHoundoomPose71
.4byte sHoundoomPose72
.4byte sHoundoomPose73
.4byte sHoundoomPose74
.4byte sHoundoomPose75
.4byte sHoundoomPose76
.4byte sHoundoomPose77
.4byte sHoundoomPose78
.4byte sHoundoomPose79
.4byte sHoundoomPose80
.4byte sHoundoomPose81
.4byte sHoundoomPose82
.4byte sHoundoomPose83
.4byte sHoundoomPose84
.4byte sHoundoomPose85
.4byte sHoundoomPose86
.4byte sHoundoomPose87
.4byte sHoundoomPose88
.4byte sHoundoomPose89
.4byte sHoundoomPose90
.4byte sHoundoomPose91
.4byte sHoundoomPose92
.4byte sHoundoomPose93
.4byte sHoundoomPose94
.4byte sHoundoomPose95
.4byte sHoundoomPose96
.4byte sHoundoomPose97
.4byte sHoundoomPose98
.4byte sHoundoomPose99
.4byte sHoundoomPose100
.4byte sHoundoomPose101
.4byte sHoundoomPose102
.4byte sHoundoomPose103
.4byte sHoundoomPose104
.4byte sHoundoomPose105
.4byte sHoundoomPose106
.4byte sHoundoomPose107
.4byte sHoundoomPose108
.4byte sHoundoomPose109
.4byte sHoundoomPose110
.4byte sHoundoomPose111
.4byte sHoundoomPose112
.4byte sHoundoomPose113
.4byte sHoundoomPose114
.4byte sHoundoomPose115
.4byte sHoundoomPose116
.4byte sHoundoomPose117
.4byte sHoundoomPose118
.4byte sHoundoomPose119
.4byte sHoundoomPose120
.4byte sHoundoomPose121
.4byte sHoundoomPose122
.4byte sHoundoomPose123
.4byte sHoundoomPose124
.4byte sHoundoomPose125
.4byte sHoundoomPose126
.4byte sHoundoomPose127
.4byte sHoundoomPose128
.4byte sHoundoomPose129
.4byte sHoundoomPose130
.4byte sHoundoomPose131
.4byte sHoundoomPose132
.4byte sHoundoomPose133
.4byte sHoundoomPose134
.4byte sHoundoomPose135
.4byte sHoundoomPose136
.4byte sHoundoomPose137
.4byte sHoundoomPose138
.4byte sHoundoomPose139
.4byte sHoundoomPose140
.4byte sHoundoomPose141
.4byte sHoundoomPose142
.4byte sHoundoomPose143
.4byte sHoundoomPose144
.4byte sHoundoomPose145
.4byte sHoundoomPose146
.4byte sHoundoomPose147
.4byte sHoundoomPose148
.4byte sHoundoomPose149
.4byte sHoundoomPose150
.4byte sHoundoomPose151
.4byte sHoundoomPose152
.4byte sHoundoomPose153
.4byte sHoundoomPose154
.4byte sHoundoomPose155
.4byte sHoundoomPose156
.4byte sHoundoomPose157
.4byte sHoundoomPose158
.4byte sHoundoomPose159
.4byte sHoundoomPose160
.4byte sHoundoomPose161
.4byte sHoundoomPose162
.4byte sHoundoomPose163
.4byte sHoundoomPose164
.4byte sHoundoomPose165
.4byte sHoundoomPose166
.4byte sHoundoomPose167
.4byte sHoundoomPose168
.4byte sHoundoomPose169
.4byte sHoundoomPose170
.4byte sHoundoomPose171
.4byte sHoundoomPose172
.4byte sHoundoomPose173
.4byte sHoundoomPose174
.4byte sHoundoomPose175
.4byte sHoundoomPose176
.4byte sHoundoomPose177
.4byte sHoundoomPose178
.4byte sHoundoomPose179
.4byte sHoundoomPose180
.4byte sHoundoomPose181
.4byte sHoundoomPose182
.4byte sHoundoomPose183
.4byte sHoundoomPose184
.4byte sHoundoomPose185
.4byte sHoundoomPose186
.4byte sHoundoomPose187
.4byte sHoundoomPose188
.4byte sHoundoomPose189
.4byte sHoundoomPose190
.4byte sHoundoomPose191
.4byte sHoundoomPose192
.4byte sHoundoomPose193
.4byte sHoundoomPose194
.4byte sHoundoomPose195
.4byte sHoundoomPose196
.4byte sHoundoomPose197
.4byte sHoundoomPose198
.4byte sHoundoomPose199
.4byte sHoundoomPose200
.4byte sHoundoomPose201
.4byte sHoundoomPose202
.4byte sHoundoomPose203
.4byte sHoundoomPose204
.4byte sHoundoomPose205
.4byte sHoundoomPose206
.4byte sHoundoomPose207
.4byte sHoundoomPose208
.4byte sHoundoomPose209
.4byte sHoundoomPose210
.4byte sHoundoomPose211
.4byte sHoundoomPose212
.4byte sHoundoomPose213
.4byte sHoundoomPose214
.4byte sHoundoomPose215
.4byte sHoundoomPose216
.4byte sHoundoomPose217
.4byte sHoundoomPose218
.4byte sHoundoomPose219
.4byte sHoundoomPose220
.4byte sHoundoomPose221
.4byte sHoundoomPose222
.4byte sHoundoomPose223
.4byte sHoundoomPose224
.4byte sHoundoomPose225
.4byte sHoundoomPose226
.4byte sHoundoomPose227
.4byte sHoundoomPose228
.4byte sHoundoomPose229
.4byte sHoundoomPose230
.4byte sHoundoomPose231
.4byte sHoundoomPose232
.4byte sHoundoomPose233
.4byte sHoundoomPose234
.4byte sHoundoomPose235
.4byte sHoundoomPose236
.4byte sHoundoomPose237
.4byte sHoundoomPose238
.4byte sHoundoomPose239
.4byte sHoundoomPose240
.4byte sHoundoomPose241
.4byte sHoundoomPose242
.4byte sHoundoomPose243
.4byte sHoundoomPose244
.4byte sHoundoomPose245
.4byte sHoundoomPose246
.4byte sHoundoomPose247
.4byte sHoundoomPose248
.4byte sHoundoomPose249
.4byte sHoundoomPose250
sAxPositionsHoundoom:
.2byte   -1,   -8, 	  -6,    4, 	   4,    4, 	  -1,   -7
.2byte   -1,   -6, 	  -5,    7, 	   2,    1, 	  -1,   -7
.2byte   -1,   -6, 	  -4,    1, 	   3,    7, 	  -1,   -7
.2byte    9,   -9, 	   8,    2, 	   1,    5, 	   0,   -8
.2byte    9,   -7, 	   9,    4, 	  -3,    4, 	   0,   -7
.2byte    9,   -7, 	   5,    1, 	   4,    8, 	   0,   -6
.2byte   13,  -15, 	   8,   -5, 	   7,    1, 	   2,  -10
.2byte   13,  -13, 	   9,   -4, 	   1,    2, 	   1,   -9
.2byte   13,  -13, 	  -1,   -4, 	  11,    2, 	   4,   -8
.2byte   10,  -21, 	   2,   -8, 	   7,   -4, 	   1,  -13
.2byte   10,  -20, 	   1,   -8, 	   2,   -1, 	  -1,  -12
.2byte    9,  -20, 	  -1,   -6, 	   8,   -5, 	   1,  -12
.2byte    0,  -22, 	   5,   -4, 	  -5,   -4, 	   0,  -12
.2byte    0,  -20, 	   6,   -8, 	  -5,   -4, 	   1,  -11
.2byte    0,  -20, 	   5,   -4, 	  -6,   -8, 	  -1,  -11
.2byte  -11,  -21, 	  -3,   -8, 	  -8,   -4, 	  -2,  -13
.2byte  -11,  -20, 	  -2,   -8, 	  -3,   -1, 	   0,  -12
.2byte  -10,  -20, 	   0,   -6, 	  -9,   -5, 	  -2,  -12
.2byte  -14,  -15, 	  -9,   -5, 	  -8,    1, 	  -3,  -10
.2byte  -14,  -13, 	 -10,   -4, 	  -2,    2, 	  -2,   -9
.2byte  -14,  -13, 	   0,   -4, 	 -12,    2, 	  -5,   -8
.2byte  -10,   -9, 	  -9,    2, 	  -2,    5, 	  -1,   -8
.2byte  -10,   -7, 	 -10,    4, 	   2,    4, 	  -1,   -7
.2byte  -10,   -7, 	  -6,    1, 	  -5,    8, 	  -1,   -6
.2byte   -1,   -8, 	  -6,    4, 	   4,    4, 	  -1,   -7
.2byte   -1,   -6, 	  -5,    7, 	   2,    1, 	  -1,   -7
.2byte   -1,   -6, 	  -4,    1, 	   3,    7, 	  -1,   -7
.2byte   -1,   -7, 	  -7,    4, 	   5,    4, 	  -1,   -8
.2byte    9,   -9, 	   8,    2, 	   1,    5, 	   0,   -8
.2byte    9,   -7, 	   9,    4, 	  -3,    4, 	   0,   -7
.2byte    9,   -7, 	   5,    1, 	   4,    8, 	   0,   -6
.2byte    8,   -8, 	   8,    2, 	   1,    5, 	   0,   -9
.2byte   13,  -15, 	   8,   -5, 	   7,    1, 	   2,  -10
.2byte   13,  -13, 	   9,   -4, 	   1,    2, 	   1,   -9
.2byte   13,  -13, 	  -1,   -4, 	  11,    2, 	   4,   -8
.2byte   15,  -16, 	   8,   -5, 	   7,    1, 	   2,  -11
.2byte   10,  -21, 	   2,   -8, 	   7,   -4, 	   1,  -13
.2byte   10,  -20, 	   1,   -8, 	   2,   -1, 	  -1,  -12
.2byte    9,  -20, 	  -1,   -6, 	   8,   -5, 	   1,  -12
.2byte   11,  -21, 	   3,   -8, 	   6,   -4, 	   0,  -13
.2byte    0,  -22, 	   5,   -4, 	  -5,   -4, 	   0,  -12
.2byte    0,  -20, 	   6,   -8, 	  -5,   -4, 	   1,  -11
.2byte    0,  -20, 	   5,   -4, 	  -6,   -8, 	  -1,  -11
.2byte    0,  -28, 	   5,   -5, 	  -5,   -5, 	   0,  -12
.2byte  -11,  -21, 	  -3,   -8, 	  -8,   -4, 	  -2,  -13
.2byte  -11,  -20, 	  -2,   -8, 	  -3,   -1, 	   0,  -12
.2byte  -10,  -20, 	   0,   -6, 	  -9,   -5, 	  -2,  -12
.2byte  -12,  -21, 	  -4,   -8, 	  -7,   -4, 	  -1,  -13
.2byte  -14,  -15, 	  -9,   -5, 	  -8,    1, 	  -3,  -10
.2byte  -14,  -13, 	 -10,   -4, 	  -2,    2, 	  -2,   -9
.2byte  -14,  -13, 	   0,   -4, 	 -12,    2, 	  -5,   -8
.2byte  -16,  -16, 	  -9,   -5, 	  -8,    1, 	  -3,  -11
.2byte  -10,   -9, 	  -9,    2, 	  -2,    5, 	  -1,   -8
.2byte  -10,   -7, 	 -10,    4, 	   2,    4, 	  -1,   -7
.2byte  -10,   -7, 	  -6,    1, 	  -5,    8, 	  -1,   -6
.2byte   -9,   -8, 	  -9,    2, 	  -2,    5, 	  -1,   -9
.2byte   -1,   -8, 	  -6,    4, 	   4,    4, 	  -1,   -7
.2byte   -1,   -6, 	  -5,    7, 	   2,    1, 	  -1,   -7
.2byte   -1,   -6, 	  -4,    1, 	   3,    7, 	  -1,   -7
.2byte   -1,   -7, 	  -7,    4, 	   5,    4, 	  -1,   -8
.2byte    9,   -9, 	   8,    2, 	   1,    5, 	   0,   -8
.2byte    9,   -7, 	   9,    4, 	  -3,    4, 	   0,   -7
.2byte    9,   -7, 	   5,    1, 	   4,    8, 	   0,   -6
.2byte    8,   -8, 	   8,    2, 	   1,    5, 	   0,   -9
.2byte   13,  -15, 	   8,   -5, 	   7,    1, 	   2,  -10
.2byte   13,  -13, 	   9,   -4, 	   1,    2, 	   1,   -9
.2byte   13,  -13, 	  -1,   -4, 	  11,    2, 	   4,   -8
.2byte   15,  -16, 	   8,   -5, 	   7,    1, 	   2,  -11
.2byte   10,  -21, 	   2,   -8, 	   7,   -4, 	   1,  -13
.2byte   10,  -20, 	   1,   -8, 	   2,   -1, 	  -1,  -12
.2byte    9,  -20, 	  -1,   -6, 	   8,   -5, 	   1,  -12
.2byte   11,  -21, 	   3,   -8, 	   6,   -4, 	   0,  -13
.2byte    0,  -22, 	   5,   -4, 	  -5,   -4, 	   0,  -12
.2byte    0,  -20, 	   6,   -8, 	  -5,   -4, 	   1,  -11
.2byte    0,  -20, 	   5,   -4, 	  -6,   -8, 	  -1,  -11
.2byte    0,  -28, 	   5,   -5, 	  -5,   -5, 	   0,  -12
.2byte  -11,  -21, 	  -3,   -8, 	  -8,   -4, 	  -2,  -13
.2byte  -11,  -20, 	  -2,   -8, 	  -3,   -1, 	   0,  -12
.2byte  -10,  -20, 	   0,   -6, 	  -9,   -5, 	  -2,  -12
.2byte  -12,  -21, 	  -4,   -8, 	  -7,   -4, 	  -1,  -13
.2byte  -14,  -15, 	  -9,   -5, 	  -8,    1, 	  -3,  -10
.2byte  -14,  -13, 	 -10,   -4, 	  -2,    2, 	  -2,   -9
.2byte  -14,  -13, 	   0,   -4, 	 -12,    2, 	  -5,   -8
.2byte  -16,  -16, 	  -9,   -5, 	  -8,    1, 	  -3,  -11
.2byte  -10,   -9, 	  -9,    2, 	  -2,    5, 	  -1,   -8
.2byte  -10,   -7, 	 -10,    4, 	   2,    4, 	  -1,   -7
.2byte  -10,   -7, 	  -6,    1, 	  -5,    8, 	  -1,   -6
.2byte   -9,   -8, 	  -9,    2, 	  -2,    5, 	  -1,   -9
.2byte   -1,   -8, 	  -6,    4, 	   4,    4, 	  -1,   -7
.2byte   -1,   -6, 	  -5,    7, 	   2,    1, 	  -1,   -7
.2byte   -1,  -24, 	  -6,    4, 	   4,    4, 	  -1,  -10
.2byte   -1,   -7, 	  -7,    4, 	   5,    4, 	  -1,   -8
.2byte   -1,  -11, 	  -6,    3, 	   4,    3, 	  -1,  -10
.2byte    9,   -9, 	   8,    2, 	   1,    5, 	   0,   -8
.2byte    9,   -7, 	   9,    4, 	  -3,    4, 	   0,   -7
.2byte    7,  -20, 	   8,    2, 	   1,    5, 	  -1,  -10
.2byte    8,   -8, 	   8,    2, 	   1,    5, 	   0,   -9
.2byte    6,  -14, 	   6,    0, 	   0,    3, 	  -2,  -10
.2byte   13,  -15, 	   8,   -5, 	   7,    1, 	   2,  -10
.2byte   13,  -13, 	   9,   -4, 	   1,    2, 	   1,   -9
.2byte    9,  -28, 	   7,   -5, 	   6,    1, 	   0,  -10
.2byte   15,  -16, 	   8,   -5, 	   7,    1, 	   2,  -11
.2byte    9,  -18, 	   6,   -6, 	   5,    1, 	  -1,  -10
.2byte   10,  -21, 	   2,   -8, 	   7,   -4, 	   1,  -13
.2byte   10,  -20, 	   1,   -8, 	   2,   -1, 	  -1,  -12
.2byte    9,  -28, 	   4,   -6, 	   6,   -4, 	  -2,  -11
.2byte   11,  -21, 	   3,   -8, 	   6,   -4, 	   0,  -13
.2byte    7,  -23, 	   0,   -5, 	   5,   -3, 	  -3,  -12
.2byte    0,  -22, 	   5,   -4, 	  -5,   -4, 	   0,  -12
.2byte    0,  -20, 	   6,   -8, 	  -5,   -4, 	   1,  -11
.2byte    0,  -32, 	   5,   -5, 	  -5,   -5, 	   0,  -11
.2byte    0,  -28, 	   5,   -5, 	  -5,   -5, 	   0,  -12
.2byte    0,  -25, 	   5,   -4, 	  -5,   -4, 	   0,  -13
.2byte  -11,  -21, 	  -3,   -8, 	  -8,   -4, 	  -2,  -13
.2byte  -11,  -20, 	  -2,   -8, 	  -3,   -1, 	   0,  -12
.2byte  -10,  -28, 	  -5,   -6, 	  -7,   -4, 	   1,  -11
.2byte  -12,  -21, 	  -4,   -8, 	  -7,   -4, 	  -1,  -13
.2byte   -8,  -23, 	  -1,   -5, 	  -6,   -3, 	   2,  -12
.2byte  -14,  -15, 	  -9,   -5, 	  -8,    1, 	  -3,  -10
.2byte  -14,  -13, 	 -10,   -4, 	  -2,    2, 	  -2,   -9
.2byte  -10,  -28, 	  -8,   -5, 	  -7,    1, 	  -1,  -10
.2byte  -16,  -16, 	  -9,   -5, 	  -8,    1, 	  -3,  -11
.2byte  -10,  -18, 	  -7,   -6, 	  -6,    1, 	   0,  -10
.2byte  -10,   -9, 	  -9,    2, 	  -2,    5, 	  -1,   -8
.2byte  -10,   -7, 	 -10,    4, 	   2,    4, 	  -1,   -7
.2byte   -8,  -20, 	  -9,    2, 	  -2,    5, 	   0,  -10
.2byte   -9,   -8, 	  -9,    2, 	  -2,    5, 	  -1,   -9
.2byte   -7,  -14, 	  -7,    0, 	  -1,    3, 	   1,  -10
.2byte   -1,   -8, 	  -6,    4, 	   4,    4, 	  -1,   -7
.2byte   -1,  -24, 	  -6,    4, 	   4,    4, 	  -1,  -10
.2byte    9,   -9, 	   8,    2, 	   1,    5, 	   0,   -8
.2byte    7,  -20, 	   8,    2, 	   1,    5, 	  -1,  -10
.2byte   13,  -15, 	   8,   -5, 	   7,    1, 	   2,  -10
.2byte    9,  -28, 	   7,   -5, 	   6,    1, 	   0,  -10
.2byte   10,  -21, 	   2,   -8, 	   7,   -4, 	   1,  -13
.2byte    9,  -28, 	   4,   -6, 	   6,   -4, 	  -2,  -11
.2byte    0,  -22, 	   5,   -4, 	  -5,   -4, 	   0,  -12
.2byte    0,  -32, 	   5,   -5, 	  -5,   -5, 	   0,  -11
.2byte  -11,  -21, 	  -3,   -8, 	  -8,   -4, 	  -2,  -13
.2byte  -10,  -28, 	  -5,   -6, 	  -7,   -4, 	   1,  -11
.2byte  -14,  -15, 	  -9,   -5, 	  -8,    1, 	  -3,  -10
.2byte  -10,  -28, 	  -8,   -5, 	  -7,    1, 	  -1,  -10
.2byte  -10,   -9, 	  -9,    2, 	  -2,    5, 	  -1,   -8
.2byte   -8,  -20, 	  -9,    2, 	  -2,    5, 	   0,  -10
.2byte  -11,   -2, 	 -11,    0, 	  -9,    2, 	   0,   -5
.2byte  -11,   -2, 	 -11,    0, 	  -9,    2, 	   0,   -5
.2byte   -2,   -5, 	  -7,    3, 	   8,    5, 	   0,   -7
.2byte   11,   -7, 	  12,   -1, 	   2,    3, 	   2,  -10
.2byte   13,  -11, 	   9,   -6, 	   8,    1, 	   3,  -10
.2byte   11,  -17, 	   4,   -8, 	   9,   -3, 	   1,  -13
.2byte    3,  -17, 	   5,   -6, 	  -7,   -6, 	  -1,  -10
.2byte  -13,  -17, 	  -6,   -8, 	 -11,   -3, 	  -3,  -13
.2byte  -13,  -11, 	  -9,   -6, 	  -8,    1, 	  -3,  -10
.2byte  -10,   -7, 	 -11,   -1, 	  -1,    3, 	  -1,  -10
.2byte   -1,   -8, 	  -6,    4, 	   4,    4, 	  -1,   -7
.2byte   -1,   -6, 	  -5,    7, 	   2,    1, 	  -1,   -7
.2byte   -1,  -24, 	  -6,    4, 	   4,    4, 	  -1,  -10
.2byte   -1,   -7, 	  -7,    4, 	   5,    4, 	  -1,   -8
.2byte   -1,  -11, 	  -6,    3, 	   4,    3, 	  -1,  -10
.2byte    9,   -9, 	   8,    2, 	   1,    5, 	   0,   -8
.2byte    9,   -7, 	   9,    4, 	  -3,    4, 	   0,   -7
.2byte    7,  -20, 	   8,    2, 	   1,    5, 	  -1,  -10
.2byte    8,   -8, 	   8,    2, 	   1,    5, 	   0,   -9
.2byte    6,  -14, 	   6,    0, 	   0,    3, 	  -2,  -10
.2byte   13,  -15, 	   8,   -5, 	   7,    1, 	   2,  -10
.2byte   13,  -13, 	   9,   -4, 	   1,    2, 	   1,   -9
.2byte    9,  -28, 	   7,   -5, 	   6,    1, 	   0,  -10
.2byte   15,  -16, 	   8,   -5, 	   7,    1, 	   2,  -11
.2byte    9,  -18, 	   6,   -6, 	   5,    1, 	  -1,  -10
.2byte   10,  -21, 	   2,   -8, 	   7,   -4, 	   1,  -13
.2byte   10,  -20, 	   1,   -8, 	   2,   -1, 	  -1,  -12
.2byte    9,  -28, 	   4,   -6, 	   6,   -4, 	  -2,  -11
.2byte   11,  -21, 	   3,   -8, 	   6,   -4, 	   0,  -13
.2byte    7,  -23, 	   0,   -5, 	   5,   -3, 	  -3,  -12
.2byte    0,  -22, 	   5,   -4, 	  -5,   -4, 	   0,  -12
.2byte    0,  -20, 	   6,   -8, 	  -5,   -4, 	   1,  -11
.2byte    0,  -32, 	   5,   -5, 	  -5,   -5, 	   0,  -11
.2byte    0,  -28, 	   5,   -5, 	  -5,   -5, 	   0,  -12
.2byte    0,  -25, 	   5,   -4, 	  -5,   -4, 	   0,  -13
.2byte  -11,  -21, 	  -3,   -8, 	  -8,   -4, 	  -2,  -13
.2byte  -11,  -20, 	  -2,   -8, 	  -3,   -1, 	   0,  -12
.2byte  -10,  -28, 	  -5,   -6, 	  -7,   -4, 	   1,  -11
.2byte  -12,  -21, 	  -4,   -8, 	  -7,   -4, 	  -1,  -13
.2byte   -8,  -23, 	  -1,   -5, 	  -6,   -3, 	   2,  -12
.2byte  -14,  -15, 	  -9,   -5, 	  -8,    1, 	  -3,  -10
.2byte  -14,  -13, 	 -10,   -4, 	  -2,    2, 	  -2,   -9
.2byte  -10,  -28, 	  -8,   -5, 	  -7,    1, 	  -1,  -10
.2byte  -16,  -16, 	  -9,   -5, 	  -8,    1, 	  -3,  -11
.2byte  -10,  -18, 	  -7,   -6, 	  -6,    1, 	   0,  -10
.2byte  -10,   -9, 	  -9,    2, 	  -2,    5, 	  -1,   -8
.2byte  -10,   -7, 	 -10,    4, 	   2,    4, 	  -1,   -7
.2byte   -8,  -20, 	  -9,    2, 	  -2,    5, 	   0,  -10
.2byte   -9,   -8, 	  -9,    2, 	  -2,    5, 	  -1,   -9
.2byte   -7,  -14, 	  -7,    0, 	  -1,    3, 	   1,  -10
.2byte   -1,   -7, 	  -7,    4, 	   5,    4, 	  -1,   -8
.2byte   -9,   -8, 	  -9,    2, 	  -2,    5, 	  -1,   -9
.2byte  -16,  -16, 	  -9,   -5, 	  -8,    1, 	  -3,  -11
.2byte  -12,  -21, 	  -4,   -8, 	  -7,   -4, 	  -1,  -13
.2byte    0,  -28, 	   5,   -5, 	  -5,   -5, 	   0,  -12
.2byte   11,  -21, 	   3,   -8, 	   6,   -4, 	   0,  -13
.2byte   15,  -16, 	   8,   -5, 	   7,    1, 	   2,  -11
.2byte    8,   -8, 	   8,    2, 	   1,    5, 	   0,   -9
.2byte   -1,  -23, 	  -6,    5, 	   4,    5, 	  -1,   -9
.2byte    7,  -21, 	   8,    1, 	   1,    4, 	  -1,  -11
.2byte   10,  -28, 	   8,   -5, 	   7,    1, 	   1,  -10
.2byte   10,  -27, 	   5,   -5, 	   7,   -3, 	  -1,  -10
.2byte    0,  -31, 	   5,   -4, 	  -5,   -4, 	   0,  -10
.2byte  -11,  -27, 	  -6,   -5, 	  -8,   -3, 	   0,  -10
.2byte  -11,  -28, 	  -9,   -5, 	  -8,    1, 	  -2,  -10
.2byte   -8,  -21, 	  -9,    1, 	  -2,    4, 	   0,  -11
.2byte   -1,   -8, 	  -6,    4, 	   4,    4, 	  -1,   -7
.2byte   -1,  -24, 	  -6,    4, 	   4,    4, 	  -1,  -10
.2byte   -1,   -7, 	  -7,    4, 	   5,    4, 	  -1,   -8
.2byte    9,   -9, 	   8,    2, 	   1,    5, 	   0,   -8
.2byte    7,  -20, 	   8,    2, 	   1,    5, 	  -1,  -10
.2byte    8,   -8, 	   8,    2, 	   1,    5, 	   0,   -9
.2byte   13,  -15, 	   8,   -5, 	   7,    1, 	   2,  -10
.2byte    9,  -28, 	   7,   -5, 	   6,    1, 	   0,  -10
.2byte   14,  -16, 	   7,   -5, 	   6,    1, 	   1,  -11
.2byte   10,  -21, 	   2,   -8, 	   7,   -4, 	   1,  -13
.2byte    9,  -28, 	   4,   -6, 	   6,   -4, 	  -2,  -11
.2byte   10,  -21, 	   2,   -8, 	   5,   -4, 	  -1,  -13
.2byte    0,  -22, 	   5,   -4, 	  -5,   -4, 	   0,  -12
.2byte    0,  -32, 	   5,   -5, 	  -5,   -5, 	   0,  -11
.2byte    0,  -28, 	   5,   -5, 	  -5,   -5, 	   0,  -12
.2byte  -11,  -21, 	  -3,   -8, 	  -8,   -4, 	  -2,  -13
.2byte  -10,  -28, 	  -5,   -6, 	  -7,   -4, 	   1,  -11
.2byte  -11,  -21, 	  -3,   -8, 	  -6,   -4, 	   0,  -13
.2byte  -14,  -15, 	  -9,   -5, 	  -8,    1, 	  -3,  -10
.2byte  -10,  -28, 	  -8,   -5, 	  -7,    1, 	  -1,  -10
.2byte  -15,  -16, 	  -8,   -5, 	  -7,    1, 	  -2,  -11
.2byte  -10,   -9, 	  -9,    2, 	  -2,    5, 	  -1,   -8
.2byte   -8,  -20, 	  -9,    2, 	  -2,    5, 	   0,  -10
.2byte   -9,   -8, 	  -9,    2, 	  -2,    5, 	  -1,   -9
.2byte   -1,   -7, 	  -7,    4, 	   5,    4, 	  -1,   -8
.2byte   -9,   -8, 	  -9,    2, 	  -2,    5, 	  -1,   -9
.2byte  -16,  -16, 	  -9,   -5, 	  -8,    1, 	  -3,  -11
.2byte  -12,  -21, 	  -4,   -8, 	  -7,   -4, 	  -1,  -13
.2byte    0,  -28, 	   5,   -5, 	  -5,   -5, 	   0,  -12
.2byte   11,  -21, 	   3,   -8, 	   6,   -4, 	   0,  -13
.2byte   15,  -16, 	   8,   -5, 	   7,    1, 	   2,  -11
.2byte    8,   -8, 	   8,    2, 	   1,    5, 	   0,   -9
.2byte   -1,   -8, 	  -6,    4, 	   4,    4, 	  -1,   -7
.2byte  -10,   -9, 	  -9,    2, 	  -2,    5, 	  -1,   -8
.2byte  -14,  -15, 	  -9,   -5, 	  -8,    1, 	  -3,  -10
.2byte  -11,  -21, 	  -3,   -8, 	  -8,   -4, 	  -2,  -13
.2byte    0,  -22, 	   5,   -4, 	  -5,   -4, 	   0,  -12
.2byte   10,  -21, 	   2,   -8, 	   7,   -4, 	   1,  -13
.2byte   13,  -15, 	   8,   -5, 	   7,    1, 	   2,  -10
.2byte    9,   -9, 	   8,    2, 	   1,    5, 	   0,   -8
sHoundoomAnimTable1:
.4byte sHoundoomAnims_1_1
.4byte sHoundoomAnims_1_2
.4byte sHoundoomAnims_1_3
.4byte sHoundoomAnims_1_4
.4byte sHoundoomAnims_1_5
.4byte sHoundoomAnims_1_6
.4byte sHoundoomAnims_1_7
.4byte sHoundoomAnims_1_8
sHoundoomAnimTable2:
.4byte sHoundoomAnims_2_1
.4byte sHoundoomAnims_2_2
.4byte sHoundoomAnims_2_3
.4byte sHoundoomAnims_2_4
.4byte sHoundoomAnims_2_5
.4byte sHoundoomAnims_2_6
.4byte sHoundoomAnims_2_7
.4byte sHoundoomAnims_2_8
sHoundoomAnimTable3:
.4byte sHoundoomAnims_3_1
.4byte sHoundoomAnims_3_2
.4byte sHoundoomAnims_3_3
.4byte sHoundoomAnims_3_4
.4byte sHoundoomAnims_3_5
.4byte sHoundoomAnims_3_6
.4byte sHoundoomAnims_3_7
.4byte sHoundoomAnims_3_8
sHoundoomAnimTable4:
.4byte sHoundoomAnims_4_1
.4byte sHoundoomAnims_4_2
.4byte sHoundoomAnims_4_3
.4byte sHoundoomAnims_4_4
.4byte sHoundoomAnims_4_5
.4byte sHoundoomAnims_4_6
.4byte sHoundoomAnims_4_7
.4byte sHoundoomAnims_4_8
sHoundoomAnimTable5:
.4byte sHoundoomAnims_5_1
.4byte sHoundoomAnims_5_2
.4byte sHoundoomAnims_5_3
.4byte sHoundoomAnims_5_4
.4byte sHoundoomAnims_5_5
.4byte sHoundoomAnims_5_6
.4byte sHoundoomAnims_5_7
.4byte sHoundoomAnims_5_8
sHoundoomAnimTable6:
.4byte sHoundoomAnims_6_1
.4byte sHoundoomAnims_6_1
.4byte sHoundoomAnims_6_1
.4byte sHoundoomAnims_6_1
.4byte sHoundoomAnims_6_1
.4byte sHoundoomAnims_6_1
.4byte sHoundoomAnims_6_1
.4byte sHoundoomAnims_6_1
sHoundoomAnimTable7:
.4byte sHoundoomAnims_7_1
.4byte sHoundoomAnims_7_2
.4byte sHoundoomAnims_7_3
.4byte sHoundoomAnims_7_4
.4byte sHoundoomAnims_7_5
.4byte sHoundoomAnims_7_6
.4byte sHoundoomAnims_7_7
.4byte sHoundoomAnims_7_8
sHoundoomAnimTable8:
.4byte sHoundoomAnims_8_1
.4byte sHoundoomAnims_8_2
.4byte sHoundoomAnims_8_3
.4byte sHoundoomAnims_8_4
.4byte sHoundoomAnims_8_5
.4byte sHoundoomAnims_8_6
.4byte sHoundoomAnims_8_7
.4byte sHoundoomAnims_8_8
sHoundoomAnimTable9:
.4byte sHoundoomAnims_9_1
.4byte sHoundoomAnims_9_2
.4byte sHoundoomAnims_9_3
.4byte sHoundoomAnims_9_4
.4byte sHoundoomAnims_9_5
.4byte sHoundoomAnims_9_6
.4byte sHoundoomAnims_9_7
.4byte sHoundoomAnims_9_8
sHoundoomAnimTable10:
.4byte sHoundoomAnims_10_1
.4byte sHoundoomAnims_10_2
.4byte sHoundoomAnims_10_3
.4byte sHoundoomAnims_10_4
.4byte sHoundoomAnims_10_5
.4byte sHoundoomAnims_10_6
.4byte sHoundoomAnims_10_7
.4byte sHoundoomAnims_10_8
sHoundoomAnimTable11:
.4byte sHoundoomAnims_11_1
.4byte sHoundoomAnims_11_2
.4byte sHoundoomAnims_11_3
.4byte sHoundoomAnims_11_4
.4byte sHoundoomAnims_11_5
.4byte sHoundoomAnims_11_6
.4byte sHoundoomAnims_11_7
.4byte sHoundoomAnims_11_8
sHoundoomAnimTable12:
.4byte sHoundoomAnims_12_1
.4byte sHoundoomAnims_12_2
.4byte sHoundoomAnims_12_3
.4byte sHoundoomAnims_12_4
.4byte sHoundoomAnims_12_5
.4byte sHoundoomAnims_12_6
.4byte sHoundoomAnims_12_7
.4byte sHoundoomAnims_12_8
sHoundoomAnimTable13:
.4byte sHoundoomAnims_13_1
.4byte sHoundoomAnims_13_2
.4byte sHoundoomAnims_13_3
.4byte sHoundoomAnims_13_4
.4byte sHoundoomAnims_13_5
.4byte sHoundoomAnims_13_6
.4byte sHoundoomAnims_13_7
.4byte sHoundoomAnims_13_8
sAxAnimationsHoundoom:
.4byte sHoundoomAnimTable1
.4byte sHoundoomAnimTable2
.4byte sHoundoomAnimTable3
.4byte sHoundoomAnimTable4
.4byte sHoundoomAnimTable5
.4byte sHoundoomAnimTable6
.4byte sHoundoomAnimTable7
.4byte sHoundoomAnimTable8
.4byte sHoundoomAnimTable9
.4byte sHoundoomAnimTable10
.4byte sHoundoomAnimTable11
.4byte sHoundoomAnimTable12
.4byte sHoundoomAnimTable13
sAxSpritesHoundoom:
.4byte sHoundoomSprites1
.4byte sHoundoomSprites2
.4byte sHoundoomSprites3
.4byte sHoundoomSprites4
.4byte sHoundoomSprites5
.4byte sHoundoomSprites6
.4byte sHoundoomSprites7
.4byte sHoundoomSprites8
.4byte sHoundoomSprites9
.4byte sHoundoomSprites10
.4byte sHoundoomSprites11
.4byte sHoundoomSprites12
.4byte sHoundoomSprites13
.4byte sHoundoomSprites14
.4byte sHoundoomSprites15
.4byte sHoundoomSprites16
.4byte sHoundoomSprites17
.4byte sHoundoomSprites18
.4byte sHoundoomSprites19
.4byte sHoundoomSprites20
.4byte sHoundoomSprites21
.4byte sHoundoomSprites22
.4byte sHoundoomSprites23
.4byte sHoundoomSprites24
.4byte sHoundoomSprites25
.4byte sHoundoomSprites26
.4byte sHoundoomSprites27
.4byte sHoundoomSprites28
.4byte sHoundoomSprites29
.4byte sHoundoomSprites30
.4byte sHoundoomSprites31
.4byte sHoundoomSprites32
.4byte sHoundoomSprites33
.4byte sHoundoomSprites34
.4byte sHoundoomSprites35
.4byte sHoundoomSprites36
.4byte sHoundoomSprites37
.4byte sHoundoomSprites38
.4byte sHoundoomSprites39
.4byte sHoundoomSprites40
.4byte sHoundoomSprites41
.4byte sHoundoomSprites42
.4byte sHoundoomSprites43
.4byte sHoundoomSprites44
.4byte sHoundoomSprites45
.4byte sHoundoomSprites46
.4byte sHoundoomSprites47
.4byte sHoundoomSprites48
.4byte sHoundoomSprites49
.4byte sHoundoomSprites50
.4byte sHoundoomSprites51
.4byte sHoundoomSprites52
.4byte sHoundoomSprites53
.4byte sHoundoomSprites54
.4byte sHoundoomSprites55
.4byte sHoundoomSprites56
.4byte sHoundoomSprites57
.4byte sHoundoomSprites58
.4byte sHoundoomSprites59
.4byte sHoundoomSprites60
.4byte sHoundoomSprites61
.4byte sHoundoomSprites62
.4byte sHoundoomSprites63
.4byte sHoundoomSprites64
.4byte sHoundoomSprites65
.4byte sHoundoomSprites66
.4byte sHoundoomSprites67
.4byte sHoundoomSprites68
.4byte sHoundoomSprites69
.4byte sHoundoomSprites70
.4byte sHoundoomSprites71
.4byte sHoundoomSprites72
.4byte sHoundoomSprites73
.4byte sHoundoomSprites74
.4byte sHoundoomSprites75
.4byte sHoundoomSprites76
.4byte sHoundoomSprites77
.4byte sHoundoomSprites78
.4byte sHoundoomSprites79
.4byte sHoundoomSprites80
.4byte sHoundoomSprites81
.4byte sHoundoomSprites82
.4byte sHoundoomSprites83
.4byte sHoundoomSprites84
.4byte sHoundoomSprites85
.4byte sHoundoomSprites86
.4byte sHoundoomSprites87
.4byte sHoundoomSprites88
.4byte sHoundoomSprites89
.4byte sHoundoomSprites90
.4byte sHoundoomSprites91
.4byte sHoundoomSprites92
.4byte sHoundoomSprites93
.4byte sHoundoomSprites94
.4byte sHoundoomSprites95
.4byte sHoundoomSprites96
.4byte sHoundoomSprites97
.4byte sHoundoomSprites98
.4byte sHoundoomSprites99
.4byte sHoundoomSprites100
.4byte sHoundoomSprites101
.4byte sHoundoomSprites102
.4byte sHoundoomSprites103
.4byte sHoundoomSprites104
.4byte sHoundoomSprites105
.4byte sHoundoomSprites106
.4byte sHoundoomSprites107
.4byte sHoundoomSprites108
.4byte sHoundoomSprites109
.4byte sHoundoomSprites110
.4byte sHoundoomSprites111
sAxMainHoundoom:
ax_main sAxPosesHoundoom, sAxAnimationsHoundoom, 13, sAxSpritesHoundoom, sAxPositionsHoundoom
