.global gAxHypno
gAxHypno:
ax_siro sAxMainHypno
sHypnoPose1:
ax_pose 0, 0x01eb, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose2:
ax_pose 1, 0x01eb, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose3:
ax_pose 2, 0x01eb, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose4:
ax_pose 3, 0x01e6, 0x80f4, 0x2c00
ax_pose_terminator
sHypnoPose5:
ax_pose 4, 0x01e6, 0x80f4, 0x2c00
ax_pose_terminator
sHypnoPose6:
ax_pose 5, 0x01e6, 0x80f4, 0x2c00
ax_pose_terminator
sHypnoPose7:
ax_pose 6, 0x01e6, 0x80f6, 0x2c00
ax_pose_terminator
sHypnoPose8:
ax_pose 7, 0x01e6, 0x80f6, 0x2c00
ax_pose_terminator
sHypnoPose9:
ax_pose 8, 0x01e6, 0x80f6, 0x2c00
ax_pose_terminator
sHypnoPose10:
ax_pose 9, 0x01e6, 0x80f4, 0x2c00
ax_pose_terminator
sHypnoPose11:
ax_pose 10, 0x01e6, 0x80f4, 0x2c00
ax_pose_terminator
sHypnoPose12:
ax_pose 11, 0x01e6, 0x80f4, 0x2c00
ax_pose_terminator
sHypnoPose13:
ax_pose 12, 0x01e6, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose14:
ax_pose 13, 0x01e6, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose15:
ax_pose 14, 0x01e6, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose16:
ax_pose 15, 0x01e6, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose17:
ax_pose 16, 0x01e6, 0x80ef, 0x2c00
ax_pose_terminator
sHypnoPose18:
ax_pose 17, 0x01e6, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose19:
ax_pose 18, 0x01e6, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose20:
ax_pose 19, 0x01e6, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose21:
ax_pose 20, 0x01e6, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose22:
ax_pose 21, 0x01e6, 0x80f3, 0x2c00
ax_pose_terminator
sHypnoPose23:
ax_pose 22, 0x01e6, 0x80f3, 0x2c00
ax_pose_terminator
sHypnoPose24:
ax_pose 23, 0x01e6, 0x80f3, 0x2c00
ax_pose_terminator
sHypnoPose25:
ax_pose 0, 0x01eb, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose26:
ax_pose 1, 0x01eb, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose27:
ax_pose 2, 0x01eb, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose28:
ax_pose 3, 0x01e6, 0x80f4, 0x2c00
ax_pose_terminator
sHypnoPose29:
ax_pose 4, 0x01e6, 0x80f4, 0x2c00
ax_pose_terminator
sHypnoPose30:
ax_pose 5, 0x01e6, 0x80f4, 0x2c00
ax_pose_terminator
sHypnoPose31:
ax_pose 6, 0x01e6, 0x80f6, 0x2c00
ax_pose_terminator
sHypnoPose32:
ax_pose 7, 0x01e6, 0x80f6, 0x2c00
ax_pose_terminator
sHypnoPose33:
ax_pose 8, 0x01e6, 0x80f6, 0x2c00
ax_pose_terminator
sHypnoPose34:
ax_pose 9, 0x01e6, 0x80f4, 0x2c00
ax_pose_terminator
sHypnoPose35:
ax_pose 10, 0x01e6, 0x80f4, 0x2c00
ax_pose_terminator
sHypnoPose36:
ax_pose 11, 0x01e6, 0x80f4, 0x2c00
ax_pose_terminator
sHypnoPose37:
ax_pose 12, 0x01e6, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose38:
ax_pose 13, 0x01e6, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose39:
ax_pose 14, 0x01e6, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose40:
ax_pose 15, 0x01e6, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose41:
ax_pose 16, 0x01e6, 0x80ef, 0x2c00
ax_pose_terminator
sHypnoPose42:
ax_pose 17, 0x01e6, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose43:
ax_pose 18, 0x01e6, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose44:
ax_pose 19, 0x01e6, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose45:
ax_pose 20, 0x01e6, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose46:
ax_pose 21, 0x01e6, 0x80f3, 0x2c00
ax_pose_terminator
sHypnoPose47:
ax_pose 22, 0x01e6, 0x80f3, 0x2c00
ax_pose_terminator
sHypnoPose48:
ax_pose 23, 0x01e6, 0x80f3, 0x2c00
ax_pose_terminator
sHypnoPose49:
ax_pose 0, 0x01eb, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose50:
ax_pose 1, 0x01eb, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose51:
ax_pose 2, 0x01eb, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose52:
ax_pose 24, 0x01ea, 0x80ef, 0x2c00
ax_pose_terminator
sHypnoPose53:
ax_pose 25, 0x01ea, 0x80f1, 0x2c00
ax_pose 26, 0x01ea, 0x80f1, 0x2c10
ax_pose_terminator
sHypnoPose54:
ax_pose 26, 0x01ea, 0x80f1, 0x2c00
ax_pose_terminator
sHypnoPose55:
ax_pose 3, 0x01e6, 0x80f4, 0x2c00
ax_pose_terminator
sHypnoPose56:
ax_pose 4, 0x01e6, 0x80f4, 0x2c00
ax_pose_terminator
sHypnoPose57:
ax_pose 5, 0x01e6, 0x80f4, 0x2c00
ax_pose_terminator
sHypnoPose58:
ax_pose 27, 0x01e6, 0x80f2, 0x2c00
ax_pose_terminator
sHypnoPose59:
ax_pose 28, 0x01e6, 0x80f0, 0x2c00
ax_pose 29, 0x01e6, 0x80f0, 0x2c10
ax_pose_terminator
sHypnoPose60:
ax_pose 29, 0x01e6, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose61:
ax_pose 6, 0x01e6, 0x80f6, 0x2c00
ax_pose_terminator
sHypnoPose62:
ax_pose 7, 0x01e6, 0x80f6, 0x2c00
ax_pose_terminator
sHypnoPose63:
ax_pose 8, 0x01e6, 0x80f6, 0x2c00
ax_pose_terminator
sHypnoPose64:
ax_pose 30, 0x01e6, 0x80f3, 0x2c00
ax_pose_terminator
sHypnoPose65:
ax_pose 31, 0x41f2, 0x80ee, 0x2c00
ax_pose 32, 0x01e6, 0x80ee, 0x2c08
ax_pose_terminator
sHypnoPose66:
ax_pose 32, 0x01e6, 0x80ee, 0x2c00
ax_pose_terminator
sHypnoPose67:
ax_pose 9, 0x01e6, 0x80f4, 0x2c00
ax_pose_terminator
sHypnoPose68:
ax_pose 10, 0x01e6, 0x80f4, 0x2c00
ax_pose_terminator
sHypnoPose69:
ax_pose 11, 0x01e6, 0x80f4, 0x2c00
ax_pose_terminator
sHypnoPose70:
ax_pose 33, 0x01e7, 0x80f1, 0x2c00
ax_pose_terminator
sHypnoPose71:
ax_pose 34, 0x01e5, 0x80ef, 0x2c00
ax_pose 35, 0x01e5, 0x80ef, 0x2c10
ax_pose_terminator
sHypnoPose72:
ax_pose 35, 0x01e5, 0x80ef, 0x2c00
ax_pose_terminator
sHypnoPose73:
ax_pose 12, 0x01e6, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose74:
ax_pose 13, 0x01e6, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose75:
ax_pose 14, 0x01e6, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose76:
ax_pose 36, 0x01e5, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose77:
ax_pose 37, 0x01e5, 0x80f0, 0x2c00
ax_pose 38, 0x01e5, 0x80f0, 0x2c10
ax_pose_terminator
sHypnoPose78:
ax_pose 38, 0x01e5, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose79:
ax_pose 15, 0x01e6, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose80:
ax_pose 16, 0x01e6, 0x80ef, 0x2c00
ax_pose_terminator
sHypnoPose81:
ax_pose 17, 0x01e6, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose82:
ax_pose 39, 0x01e5, 0x80ef, 0x2c00
ax_pose_terminator
sHypnoPose83:
ax_pose 40, 0x01e5, 0x80f5, 0x2c00
ax_pose 41, 0x01e5, 0x80f5, 0x2c10
ax_pose_terminator
sHypnoPose84:
ax_pose 41, 0x01e5, 0x80f5, 0x2c00
ax_pose_terminator
sHypnoPose85:
ax_pose 18, 0x01e6, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose86:
ax_pose 19, 0x01e6, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose87:
ax_pose 20, 0x01e6, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose88:
ax_pose 42, 0x01e6, 0x80ee, 0x2c00
ax_pose_terminator
sHypnoPose89:
ax_pose 43, 0x01e6, 0x80f0, 0x2c00
ax_pose 44, 0x01e6, 0x80f0, 0x2c10
ax_pose_terminator
sHypnoPose90:
ax_pose 44, 0x01e6, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose91:
ax_pose 21, 0x01e6, 0x80f3, 0x2c00
ax_pose_terminator
sHypnoPose92:
ax_pose 22, 0x01e6, 0x80f3, 0x2c00
ax_pose_terminator
sHypnoPose93:
ax_pose 23, 0x01e6, 0x80f3, 0x2c00
ax_pose_terminator
sHypnoPose94:
ax_pose 45, 0x01e6, 0x80f3, 0x2c00
ax_pose_terminator
sHypnoPose95:
ax_pose 46, 0x01e9, 0x80f0, 0x2c00
ax_pose 47, 0x01e9, 0x80f0, 0x2c10
ax_pose_terminator
sHypnoPose96:
ax_pose 47, 0x01e9, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose97:
ax_pose 0, 0x01eb, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose98:
ax_pose 1, 0x01eb, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose99:
ax_pose 2, 0x01eb, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose100:
ax_pose 48, 0x01f4, 0x04f3, 0x4c00
ax_pose 24, 0x01ea, 0x80ef, 0x2c01
ax_pose_terminator
sHypnoPose101:
ax_pose 49, 0x01f2, 0x44ed, 0x4c00
ax_pose 50, 0x01eb, 0x80f0, 0x2c04
ax_pose_terminator
sHypnoPose102:
ax_pose 51, 0x01eb, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose103:
ax_pose 49, 0x01f0, 0x44ef, 0x4c00
ax_pose 24, 0x01ea, 0x80ef, 0x2c04
ax_pose_terminator
sHypnoPose104:
ax_pose 48, 0x01f7, 0x04f6, 0x4c00
ax_pose 51, 0x01eb, 0x80f0, 0x2c01
ax_pose_terminator
sHypnoPose105:
ax_pose 49, 0x01f3, 0x44f2, 0x4c00
ax_pose 51, 0x01eb, 0x80f0, 0x2c04
ax_pose_terminator
sHypnoPose106:
ax_pose 3, 0x01e6, 0x80f4, 0x2c00
ax_pose_terminator
sHypnoPose107:
ax_pose 4, 0x01e6, 0x80f4, 0x2c00
ax_pose_terminator
sHypnoPose108:
ax_pose 5, 0x01e6, 0x80f4, 0x2c00
ax_pose_terminator
sHypnoPose109:
ax_pose 48, 0x01ee, 0x04ef, 0x4c00
ax_pose 27, 0x01e6, 0x80f2, 0x2c01
ax_pose_terminator
sHypnoPose110:
ax_pose 49, 0x01f5, 0x44f7, 0x4c00
ax_pose 52, 0x01e6, 0x80f1, 0x2c04
ax_pose_terminator
sHypnoPose111:
ax_pose 53, 0x01e6, 0x80f1, 0x2c00
ax_pose_terminator
sHypnoPose112:
ax_pose 49, 0x01ea, 0x44eb, 0x4c00
ax_pose 27, 0x01e6, 0x80f2, 0x2c04
ax_pose_terminator
sHypnoPose113:
ax_pose 48, 0x01f9, 0x0500, 0x4c00
ax_pose 53, 0x01e6, 0x80f1, 0x2c01
ax_pose_terminator
sHypnoPose114:
ax_pose 49, 0x01f5, 0x44fc, 0x4c00
ax_pose 53, 0x01e6, 0x80f1, 0x2c04
ax_pose_terminator
sHypnoPose115:
ax_pose 6, 0x01e6, 0x80f6, 0x2c00
ax_pose_terminator
sHypnoPose116:
ax_pose 7, 0x01e6, 0x80f6, 0x2c00
ax_pose_terminator
sHypnoPose117:
ax_pose 8, 0x01e6, 0x80f6, 0x2c00
ax_pose_terminator
sHypnoPose118:
ax_pose 48, 0x01f4, 0x04f1, 0x4c00
ax_pose 30, 0x01e6, 0x80f3, 0x2c01
ax_pose_terminator
sHypnoPose119:
ax_pose 49, 0x01f2, 0x4500, 0x4c00
ax_pose 54, 0x01e6, 0x80f0, 0x2c04
ax_pose_terminator
sHypnoPose120:
ax_pose 55, 0x01e6, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose121:
ax_pose 49, 0x01f0, 0x44ed, 0x4c00
ax_pose 30, 0x01e6, 0x80f3, 0x2c04
ax_pose_terminator
sHypnoPose122:
ax_pose 48, 0x01f4, 0x0507, 0x4c00
ax_pose 55, 0x01e6, 0x80f0, 0x2c01
ax_pose_terminator
sHypnoPose123:
ax_pose 49, 0x01f0, 0x4503, 0x4c00
ax_pose 55, 0x01e6, 0x80f0, 0x2c04
ax_pose_terminator
sHypnoPose124:
ax_pose 9, 0x01e6, 0x80f4, 0x2c00
ax_pose_terminator
sHypnoPose125:
ax_pose 10, 0x01e6, 0x80f4, 0x2c00
ax_pose_terminator
sHypnoPose126:
ax_pose 11, 0x01e6, 0x80f4, 0x2c00
ax_pose_terminator
sHypnoPose127:
ax_pose 48, 0x01fa, 0x04f8, 0x4c00
ax_pose 33, 0x01e7, 0x80f1, 0x2c01
ax_pose_terminator
sHypnoPose128:
ax_pose 49, 0x01ed, 0x4508, 0x4c00
ax_pose 56, 0x01e6, 0x80f2, 0x2c04
ax_pose_terminator
sHypnoPose129:
ax_pose 57, 0x01e6, 0x80f2, 0x2c00
ax_pose_terminator
sHypnoPose130:
ax_pose 49, 0x01f6, 0x44f4, 0x4c00
ax_pose 33, 0x01e7, 0x80f1, 0x2c04
ax_pose_terminator
sHypnoPose131:
ax_pose 48, 0x01f0, 0x050a, 0x4c00
ax_pose 57, 0x01e6, 0x80f2, 0x2c01
ax_pose_terminator
sHypnoPose132:
ax_pose 49, 0x01ec, 0x4506, 0x4c00
ax_pose 57, 0x01e6, 0x80f2, 0x2c04
ax_pose_terminator
sHypnoPose133:
ax_pose 12, 0x01e6, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose134:
ax_pose 13, 0x01e6, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose135:
ax_pose 14, 0x01e6, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose136:
ax_pose 48, 0x01f9, 0x0505, 0x4c00
ax_pose 36, 0x01e4, 0x80f0, 0x2c01
ax_pose_terminator
sHypnoPose137:
ax_pose 58, 0x01e6, 0x80ef, 0x2c00
ax_pose 49, 0x01e8, 0x4500, 0x4c10
ax_pose_terminator
sHypnoPose138:
ax_pose 59, 0x01e6, 0x80ef, 0x2c00
ax_pose_terminator
sHypnoPose139:
ax_pose 49, 0x01f5, 0x4501, 0x4c00
ax_pose 36, 0x01e4, 0x80f0, 0x2c04
ax_pose_terminator
sHypnoPose140:
ax_pose 59, 0x01e6, 0x80ef, 0x2c00
ax_pose 48, 0x01ed, 0x0501, 0x4c10
ax_pose_terminator
sHypnoPose141:
ax_pose 59, 0x01e6, 0x80ef, 0x2c00
ax_pose 49, 0x01e9, 0x44fd, 0x4c10
ax_pose_terminator
sHypnoPose142:
ax_pose 15, 0x01e6, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose143:
ax_pose 16, 0x01e6, 0x80ef, 0x2c00
ax_pose_terminator
sHypnoPose144:
ax_pose 17, 0x01e6, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose145:
ax_pose 48, 0x01f8, 0x050a, 0x4c00
ax_pose 39, 0x01e6, 0x80f0, 0x2c01
ax_pose_terminator
sHypnoPose146:
ax_pose 60, 0x01e6, 0x80ed, 0x2c00
ax_pose 49, 0x01e9, 0x44f9, 0x4c10
ax_pose_terminator
sHypnoPose147:
ax_pose 61, 0x01e6, 0x80ed, 0x2c00
ax_pose_terminator
sHypnoPose148:
ax_pose 49, 0x01f4, 0x4506, 0x4c00
ax_pose 39, 0x01e6, 0x80f0, 0x2c04
ax_pose_terminator
sHypnoPose149:
ax_pose 61, 0x01e6, 0x80ed, 0x2c00
ax_pose 48, 0x01eb, 0x04f7, 0x4c10
ax_pose_terminator
sHypnoPose150:
ax_pose 61, 0x01e6, 0x80ed, 0x2c00
ax_pose 49, 0x01e7, 0x44f3, 0x4c10
ax_pose_terminator
sHypnoPose151:
ax_pose 18, 0x01e6, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose152:
ax_pose 19, 0x01e6, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose153:
ax_pose 20, 0x01e6, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose154:
ax_pose 42, 0x01e6, 0x80ee, 0x2c00
ax_pose 48, 0x01f4, 0x0507, 0x4c10
ax_pose_terminator
sHypnoPose155:
ax_pose 62, 0x01e6, 0x80ef, 0x2c00
ax_pose 49, 0x01ea, 0x44ea, 0x4c10
ax_pose_terminator
sHypnoPose156:
ax_pose 63, 0x01e6, 0x80ef, 0x2c00
ax_pose_terminator
sHypnoPose157:
ax_pose 42, 0x01e6, 0x80ee, 0x2c00
ax_pose 49, 0x01f0, 0x4503, 0x4c10
ax_pose_terminator
sHypnoPose158:
ax_pose 63, 0x01e6, 0x80ef, 0x2c00
ax_pose 48, 0x01f4, 0x04ec, 0x4c10
ax_pose_terminator
sHypnoPose159:
ax_pose 63, 0x01e6, 0x80ef, 0x2c00
ax_pose 49, 0x01f0, 0x44e8, 0x4c10
ax_pose_terminator
sHypnoPose160:
ax_pose 21, 0x01e6, 0x80f3, 0x2c00
ax_pose_terminator
sHypnoPose161:
ax_pose 22, 0x01e6, 0x80f3, 0x2c00
ax_pose_terminator
sHypnoPose162:
ax_pose 23, 0x01e6, 0x80f3, 0x2c00
ax_pose_terminator
sHypnoPose163:
ax_pose 45, 0x01e6, 0x80f3, 0x2c00
ax_pose 48, 0x01f0, 0x04f7, 0x4c10
ax_pose_terminator
sHypnoPose164:
ax_pose 49, 0x01f0, 0x44e9, 0x4c00
ax_pose 64, 0x01e6, 0x80f0, 0x2c04
ax_pose_terminator
sHypnoPose165:
ax_pose 65, 0x01e6, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose166:
ax_pose 45, 0x01e6, 0x80f3, 0x2c00
ax_pose 49, 0x01ec, 0x44f3, 0x4c10
ax_pose_terminator
sHypnoPose167:
ax_pose 48, 0x01f7, 0x04ee, 0x4c00
ax_pose 65, 0x01e6, 0x80f0, 0x2c01
ax_pose_terminator
sHypnoPose168:
ax_pose 49, 0x01f3, 0x44ea, 0x4c00
ax_pose 65, 0x01e6, 0x80f0, 0x2c04
ax_pose_terminator
sHypnoPose169:
ax_pose 50, 0x01eb, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose170:
ax_pose 49, 0x01f2, 0x44ed, 0x4c00
ax_pose 50, 0x01eb, 0x80f0, 0x2c04
ax_pose_terminator
sHypnoPose171:
ax_pose 51, 0x01eb, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose172:
ax_pose 48, 0x01f7, 0x04f6, 0x4c00
ax_pose 51, 0x01eb, 0x80f0, 0x2c01
ax_pose_terminator
sHypnoPose173:
ax_pose 49, 0x01f3, 0x44f2, 0x4c00
ax_pose 51, 0x01eb, 0x80f0, 0x2c04
ax_pose_terminator
sHypnoPose174:
ax_pose 52, 0x01e6, 0x80f1, 0x2c00
ax_pose_terminator
sHypnoPose175:
ax_pose 49, 0x01f5, 0x44f7, 0x4c00
ax_pose 52, 0x01e6, 0x80f1, 0x2c04
ax_pose_terminator
sHypnoPose176:
ax_pose 53, 0x01e6, 0x80f1, 0x2c00
ax_pose_terminator
sHypnoPose177:
ax_pose 48, 0x01f9, 0x0500, 0x4c00
ax_pose 53, 0x01e6, 0x80f1, 0x2c01
ax_pose_terminator
sHypnoPose178:
ax_pose 49, 0x01f5, 0x44fc, 0x4c00
ax_pose 53, 0x01e6, 0x80f1, 0x2c04
ax_pose_terminator
sHypnoPose179:
ax_pose 54, 0x01e6, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose180:
ax_pose 49, 0x01f2, 0x4500, 0x4c00
ax_pose 54, 0x01e6, 0x80f0, 0x2c04
ax_pose_terminator
sHypnoPose181:
ax_pose 55, 0x01e6, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose182:
ax_pose 48, 0x01f4, 0x0507, 0x4c00
ax_pose 55, 0x01e6, 0x80f0, 0x2c01
ax_pose_terminator
sHypnoPose183:
ax_pose 49, 0x01f0, 0x4503, 0x4c00
ax_pose 55, 0x01e6, 0x80f0, 0x2c04
ax_pose_terminator
sHypnoPose184:
ax_pose 56, 0x01e6, 0x80f2, 0x2c00
ax_pose_terminator
sHypnoPose185:
ax_pose 49, 0x01ed, 0x4508, 0x4c00
ax_pose 56, 0x01e6, 0x80f2, 0x2c04
ax_pose_terminator
sHypnoPose186:
ax_pose 57, 0x01e6, 0x80f2, 0x2c00
ax_pose_terminator
sHypnoPose187:
ax_pose 48, 0x01f0, 0x050a, 0x4c00
ax_pose 57, 0x01e6, 0x80f2, 0x2c01
ax_pose_terminator
sHypnoPose188:
ax_pose 49, 0x01ec, 0x4506, 0x4c00
ax_pose 57, 0x01e6, 0x80f2, 0x2c04
ax_pose_terminator
sHypnoPose189:
ax_pose 58, 0x01e6, 0x80ef, 0x2c00
ax_pose_terminator
sHypnoPose190:
ax_pose 58, 0x01e6, 0x80ef, 0x2c00
ax_pose 49, 0x01e8, 0x4500, 0x4c10
ax_pose_terminator
sHypnoPose191:
ax_pose 59, 0x01e6, 0x80ef, 0x2c00
ax_pose_terminator
sHypnoPose192:
ax_pose 59, 0x01e6, 0x80ef, 0x2c00
ax_pose 48, 0x01ed, 0x0501, 0x4c10
ax_pose_terminator
sHypnoPose193:
ax_pose 59, 0x01e6, 0x80ef, 0x2c00
ax_pose 49, 0x01e9, 0x44fd, 0x4c10
ax_pose_terminator
sHypnoPose194:
ax_pose 60, 0x01e6, 0x80ed, 0x2c00
ax_pose_terminator
sHypnoPose195:
ax_pose 60, 0x01e6, 0x80ed, 0x2c00
ax_pose 49, 0x01e9, 0x44f9, 0x4c10
ax_pose_terminator
sHypnoPose196:
ax_pose 61, 0x01e6, 0x80ed, 0x2c00
ax_pose_terminator
sHypnoPose197:
ax_pose 61, 0x01e6, 0x80ed, 0x2c00
ax_pose 48, 0x01eb, 0x04f7, 0x4c10
ax_pose_terminator
sHypnoPose198:
ax_pose 61, 0x01e6, 0x80ed, 0x2c00
ax_pose 49, 0x01e7, 0x44f3, 0x4c10
ax_pose_terminator
sHypnoPose199:
ax_pose 62, 0x01e6, 0x80ef, 0x2c00
ax_pose_terminator
sHypnoPose200:
ax_pose 62, 0x01e6, 0x80ef, 0x2c00
ax_pose 49, 0x01ea, 0x44ea, 0x4c10
ax_pose_terminator
sHypnoPose201:
ax_pose 63, 0x01e6, 0x80ef, 0x2c00
ax_pose_terminator
sHypnoPose202:
ax_pose 63, 0x01e6, 0x80ef, 0x2c00
ax_pose 48, 0x01f4, 0x04ec, 0x4c10
ax_pose_terminator
sHypnoPose203:
ax_pose 63, 0x01e6, 0x80ef, 0x2c00
ax_pose 49, 0x01f0, 0x44e8, 0x4c10
ax_pose_terminator
sHypnoPose204:
ax_pose 64, 0x01e6, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose205:
ax_pose 48, 0x01f4, 0x04ed, 0x4c00
ax_pose 64, 0x01e6, 0x80f0, 0x2c01
ax_pose_terminator
sHypnoPose206:
ax_pose 65, 0x01e6, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose207:
ax_pose 49, 0x01f3, 0x44ea, 0x4c00
ax_pose 65, 0x01e6, 0x80f0, 0x2c04
ax_pose_terminator
sHypnoPose208:
ax_pose 48, 0x01f7, 0x04ee, 0x4c00
ax_pose 65, 0x01e6, 0x80f0, 0x2c01
ax_pose_terminator
sHypnoPose209:
ax_pose 66, 0x01ec, 0x80f4, 0x2c00
ax_pose_terminator
sHypnoPose210:
ax_pose 67, 0x01ec, 0x80f4, 0x2c00
ax_pose_terminator
sHypnoPose211:
ax_pose 68, 0x01e2, 0x80f2, 0x2c00
ax_pose_terminator
sHypnoPose212:
ax_pose 69, 0x01e1, 0x90ee, 0x2c00
ax_pose_terminator
sHypnoPose213:
ax_pose 70, 0x01e0, 0x90ee, 0x2c00
ax_pose_terminator
sHypnoPose214:
ax_pose 71, 0x01e1, 0x90ed, 0x2c00
ax_pose_terminator
sHypnoPose215:
ax_pose 72, 0x01e1, 0x80ef, 0x2c00
ax_pose_terminator
sHypnoPose216:
ax_pose 71, 0x01e1, 0x80f2, 0x2c00
ax_pose_terminator
sHypnoPose217:
ax_pose 70, 0x01e0, 0x80f3, 0x2c00
ax_pose_terminator
sHypnoPose218:
ax_pose 69, 0x01e1, 0x80f2, 0x2c00
ax_pose_terminator
sHypnoPose219:
ax_pose 0, 0x01eb, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose220:
ax_pose 1, 0x01eb, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose221:
ax_pose 2, 0x01eb, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose222:
ax_pose 3, 0x01e6, 0x80f4, 0x2c00
ax_pose_terminator
sHypnoPose223:
ax_pose 4, 0x01e6, 0x80f4, 0x2c00
ax_pose_terminator
sHypnoPose224:
ax_pose 5, 0x01e6, 0x80f4, 0x2c00
ax_pose_terminator
sHypnoPose225:
ax_pose 6, 0x01e6, 0x80f6, 0x2c00
ax_pose_terminator
sHypnoPose226:
ax_pose 7, 0x01e6, 0x80f6, 0x2c00
ax_pose_terminator
sHypnoPose227:
ax_pose 8, 0x01e6, 0x80f6, 0x2c00
ax_pose_terminator
sHypnoPose228:
ax_pose 9, 0x01e6, 0x80f4, 0x2c00
ax_pose_terminator
sHypnoPose229:
ax_pose 10, 0x01e6, 0x80f4, 0x2c00
ax_pose_terminator
sHypnoPose230:
ax_pose 11, 0x01e6, 0x80f4, 0x2c00
ax_pose_terminator
sHypnoPose231:
ax_pose 12, 0x01e6, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose232:
ax_pose 13, 0x01e6, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose233:
ax_pose 14, 0x01e6, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose234:
ax_pose 15, 0x01e6, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose235:
ax_pose 16, 0x01e6, 0x80ef, 0x2c00
ax_pose_terminator
sHypnoPose236:
ax_pose 17, 0x01e6, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose237:
ax_pose 18, 0x01e6, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose238:
ax_pose 19, 0x01e6, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose239:
ax_pose 20, 0x01e6, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose240:
ax_pose 21, 0x01e6, 0x80f3, 0x2c00
ax_pose_terminator
sHypnoPose241:
ax_pose 22, 0x01e6, 0x80f3, 0x2c00
ax_pose_terminator
sHypnoPose242:
ax_pose 23, 0x01e6, 0x80f3, 0x2c00
ax_pose_terminator
sHypnoPose243:
ax_pose 50, 0x01eb, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose244:
ax_pose 64, 0x01e6, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose245:
ax_pose 62, 0x01e6, 0x80ef, 0x2c00
ax_pose_terminator
sHypnoPose246:
ax_pose 60, 0x01e6, 0x80ed, 0x2c00
ax_pose_terminator
sHypnoPose247:
ax_pose 58, 0x01e6, 0x80ef, 0x2c00
ax_pose_terminator
sHypnoPose248:
ax_pose 56, 0x01e6, 0x80f2, 0x2c00
ax_pose_terminator
sHypnoPose249:
ax_pose 54, 0x01e6, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose250:
ax_pose 52, 0x01e6, 0x80f1, 0x2c00
ax_pose_terminator
sHypnoPose251:
ax_pose 50, 0x01eb, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose252:
ax_pose 52, 0x01e6, 0x80f1, 0x2c00
ax_pose_terminator
sHypnoPose253:
ax_pose 54, 0x01e6, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose254:
ax_pose 56, 0x01e6, 0x80f2, 0x2c00
ax_pose_terminator
sHypnoPose255:
ax_pose 58, 0x01e6, 0x80ef, 0x2c00
ax_pose_terminator
sHypnoPose256:
ax_pose 60, 0x01e6, 0x80ed, 0x2c00
ax_pose_terminator
sHypnoPose257:
ax_pose 62, 0x01e6, 0x80ef, 0x2c00
ax_pose_terminator
sHypnoPose258:
ax_pose 64, 0x01e6, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose259:
ax_pose 50, 0x01eb, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose260:
ax_pose 0, 0x01eb, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose261:
ax_pose 24, 0x01ea, 0x80ef, 0x2c00
ax_pose_terminator
sHypnoPose262:
ax_pose 51, 0x01eb, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose263:
ax_pose 3, 0x01e6, 0x80f4, 0x2c00
ax_pose_terminator
sHypnoPose264:
ax_pose 27, 0x01e6, 0x80f2, 0x2c00
ax_pose_terminator
sHypnoPose265:
ax_pose 53, 0x01e6, 0x80f1, 0x2c00
ax_pose_terminator
sHypnoPose266:
ax_pose 6, 0x01e6, 0x80f6, 0x2c00
ax_pose_terminator
sHypnoPose267:
ax_pose 30, 0x01e6, 0x80f3, 0x2c00
ax_pose_terminator
sHypnoPose268:
ax_pose 55, 0x01e6, 0x80ef, 0x2c00
ax_pose_terminator
sHypnoPose269:
ax_pose 9, 0x01e6, 0x80f4, 0x2c00
ax_pose_terminator
sHypnoPose270:
ax_pose 33, 0x01e7, 0x80f1, 0x2c00
ax_pose_terminator
sHypnoPose271:
ax_pose 57, 0x01e6, 0x80f1, 0x2c00
ax_pose_terminator
sHypnoPose272:
ax_pose 12, 0x01e6, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose273:
ax_pose 36, 0x01e6, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose274:
ax_pose 59, 0x01e6, 0x80ef, 0x2c00
ax_pose_terminator
sHypnoPose275:
ax_pose 15, 0x01e6, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose276:
ax_pose 39, 0x01e5, 0x80ef, 0x2c00
ax_pose_terminator
sHypnoPose277:
ax_pose 61, 0x01e5, 0x80ed, 0x2c00
ax_pose_terminator
sHypnoPose278:
ax_pose 18, 0x01e6, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose279:
ax_pose 42, 0x01e6, 0x80ee, 0x2c00
ax_pose_terminator
sHypnoPose280:
ax_pose 63, 0x01e6, 0x80f1, 0x2c00
ax_pose_terminator
sHypnoPose281:
ax_pose 21, 0x01e6, 0x80f3, 0x2c00
ax_pose_terminator
sHypnoPose282:
ax_pose 45, 0x01e6, 0x80f3, 0x2c00
ax_pose_terminator
sHypnoPose283:
ax_pose 65, 0x01e6, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose284:
ax_pose 50, 0x01eb, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose285:
ax_pose 64, 0x01e6, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose286:
ax_pose 62, 0x01e6, 0x80ef, 0x2c00
ax_pose_terminator
sHypnoPose287:
ax_pose 60, 0x01e6, 0x80ed, 0x2c00
ax_pose_terminator
sHypnoPose288:
ax_pose 58, 0x01e6, 0x80ef, 0x2c00
ax_pose_terminator
sHypnoPose289:
ax_pose 56, 0x01e6, 0x80f2, 0x2c00
ax_pose_terminator
sHypnoPose290:
ax_pose 54, 0x01e6, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose291:
ax_pose 52, 0x01e6, 0x80f1, 0x2c00
ax_pose_terminator
sHypnoPose292:
ax_pose 50, 0x01eb, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose293:
ax_pose 0, 0x01eb, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose294:
ax_pose 21, 0x01e6, 0x80f3, 0x2c00
ax_pose_terminator
sHypnoPose295:
ax_pose 18, 0x01e6, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose296:
ax_pose 15, 0x01e6, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose297:
ax_pose 12, 0x01e6, 0x80f0, 0x2c00
ax_pose_terminator
sHypnoPose298:
ax_pose 9, 0x01e6, 0x80f4, 0x2c00
ax_pose_terminator
sHypnoPose299:
ax_pose 6, 0x01e6, 0x80f6, 0x2c00
ax_pose_terminator
sHypnoPose300:
ax_pose 3, 0x01e6, 0x80f4, 0x2c00
ax_pose_terminator
.align 2
sHypnoAnims_1_1:
ax_anim 8, 0, 0, 0, 0, 0, 0,
ax_anim 10, 0, 1, 0, 0, 0, 0,
ax_anim 8, 0, 0, 0, 0, 0, 0,
ax_anim 10, 0, 2, 0, 0, 0, 0,
ax_anim_terminator
sHypnoAnims_1_2:
ax_anim 8, 0, 3, 0, 0, 0, 0,
ax_anim 10, 0, 4, 0, 0, 0, 0,
ax_anim 8, 0, 3, 0, 0, 0, 0,
ax_anim 10, 0, 5, 0, 0, 0, 0,
ax_anim_terminator
sHypnoAnims_1_3:
ax_anim 8, 0, 6, 0, 0, 0, 0,
ax_anim 10, 0, 7, 0, 0, 0, 0,
ax_anim 8, 0, 6, 0, 0, 0, 0,
ax_anim 10, 0, 8, 0, 0, 0, 0,
ax_anim_terminator
sHypnoAnims_1_4:
ax_anim 8, 0, 9, 0, 0, 0, 0,
ax_anim 10, 0, 10, 0, 0, 0, 0,
ax_anim 8, 0, 9, 0, 0, 0, 0,
ax_anim 10, 0, 11, 0, 0, 0, 0,
ax_anim_terminator
sHypnoAnims_1_5:
ax_anim 8, 0, 12, 0, 0, 0, 0,
ax_anim 10, 0, 13, 0, 0, 0, 0,
ax_anim 8, 0, 12, 0, 0, 0, 0,
ax_anim 10, 0, 14, 0, 0, 0, 0,
ax_anim_terminator
sHypnoAnims_1_6:
ax_anim 8, 0, 15, 0, 0, 0, 0,
ax_anim 10, 0, 16, 0, 0, 0, 0,
ax_anim 8, 0, 15, 0, 0, 0, 0,
ax_anim 10, 0, 17, 0, 0, 0, 0,
ax_anim_terminator
sHypnoAnims_1_7:
ax_anim 8, 0, 18, 0, 0, 0, 0,
ax_anim 10, 0, 19, 0, 0, 0, 0,
ax_anim 8, 0, 18, 0, 0, 0, 0,
ax_anim 10, 0, 20, 0, 0, 0, 0,
ax_anim_terminator
sHypnoAnims_1_8:
ax_anim 8, 0, 21, 0, 0, 0, 0,
ax_anim 10, 0, 22, 0, 0, 0, 0,
ax_anim 8, 0, 21, 0, 0, 0, 0,
ax_anim 10, 0, 23, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sHypnoAnims_2_1:
ax_anim 2, 0, 45, 0, -1, 0, -1,
ax_anim 4, 0, 45, 0, -2, 0, -2,
ax_anim 1, 0, 26, 0, 0, 0, 0,
ax_anim 1, 2, 25, 0, 4, 0, 4,
ax_anim 1, 0, 26, 0, 10, 0, 10,
ax_anim 2, 0, 25, 0, 20, 0, 20,
ax_anim 2, 1, 25, 1, 20, 1, 20,
ax_anim 2, 0, 25, 0, 20, 0, 20,
ax_anim 2, 0, 25, 1, 20, 1, 20,
ax_anim 2, 0, 24, 0, 6, 0, 6,
ax_anim_terminator
sHypnoAnims_2_2:
ax_anim 2, 0, 24, -1, -1, -1, -1,
ax_anim 4, 0, 24, -2, -2, -2, -2,
ax_anim 1, 0, 29, 0, 0, 0, 0,
ax_anim 1, 2, 28, 4, 4, 4, 4,
ax_anim 1, 0, 29, 10, 10, 10, 10,
ax_anim 2, 0, 28, 19, 20, 19, 20,
ax_anim 2, 1, 28, 20, 19, 20, 19,
ax_anim 2, 0, 28, 19, 20, 19, 20,
ax_anim 2, 0, 28, 20, 19, 20, 19,
ax_anim 2, 0, 27, 6, 6, 6, 6,
ax_anim_terminator
sHypnoAnims_2_3:
ax_anim 2, 0, 27, -1, 0, -1, 0,
ax_anim 4, 0, 27, -2, 0, -2, 0,
ax_anim 1, 0, 32, 0, 0, 0, 0,
ax_anim 1, 2, 31, 4, 0, 4, 0,
ax_anim 1, 0, 32, 10, 0, 10, 0,
ax_anim 2, 0, 31, 20, 0, 20, 0,
ax_anim 2, 1, 31, 20, 1, 20, 1,
ax_anim 2, 0, 31, 20, 0, 20, 0,
ax_anim 2, 0, 31, 20, 1, 20, 1,
ax_anim 2, 0, 30, 6, 0, 6, 0,
ax_anim_terminator
sHypnoAnims_2_4:
ax_anim 2, 0, 30, -1, 1, -1, 1,
ax_anim 4, 0, 30, -2, 2, -2, 2,
ax_anim 1, 0, 35, 0, -1, 0, -1,
ax_anim 1, 2, 34, 5, -6, 5, -6,
ax_anim 1, 0, 35, 12, -12, 12, -12,
ax_anim 2, 0, 34, 20, -19, 20, -19,
ax_anim 2, 1, 34, 21, -18, 21, -18,
ax_anim 2, 0, 34, 20, -19, 20, -19,
ax_anim 2, 0, 34, 21, -18, 21, -18,
ax_anim 2, 0, 33, 6, -6, 6, -6,
ax_anim_terminator
sHypnoAnims_2_5:
ax_anim 2, 0, 33, 0, 1, 0, 1,
ax_anim 4, 0, 33, 0, 2, 0, 2,
ax_anim 1, 0, 38, 0, 0, 0, 0,
ax_anim 1, 2, 37, 0, -4, 0, -4,
ax_anim 1, 0, 38, 0, -11, 0, -11,
ax_anim 2, 0, 37, 0, -19, 0, -19,
ax_anim 2, 1, 37, 1, -19, 1, -19,
ax_anim 2, 0, 37, 0, -19, 0, -19,
ax_anim 2, 0, 37, 1, -19, 1, -19,
ax_anim 2, 0, 36, 0, -6, 0, -6,
ax_anim_terminator
sHypnoAnims_2_6:
ax_anim 2, 0, 36, 1, 1, 1, 1,
ax_anim 4, 0, 36, 2, 2, 2, 2,
ax_anim 1, 0, 41, 0, -1, 0, -1,
ax_anim 1, 2, 40, -6, -6, -6, -6,
ax_anim 1, 0, 41, -11, -12, -11, -12,
ax_anim 2, 0, 40, -18, -19, -18, -19,
ax_anim 2, 1, 40, -19, -18, -19, -18,
ax_anim 2, 0, 40, -18, -19, -18, -19,
ax_anim 2, 0, 40, -19, -18, -19, -18,
ax_anim 2, 0, 39, -6, -6, -6, -6,
ax_anim_terminator
sHypnoAnims_2_7:
ax_anim 2, 0, 39, 1, 0, 1, 0,
ax_anim 4, 0, 39, 2, 0, 2, 0,
ax_anim 1, 0, 44, 0, 0, 0, 0,
ax_anim 1, 2, 43, -4, 0, -4, 0,
ax_anim 1, 0, 44, -10, 0, -10, 0,
ax_anim 2, 0, 43, -20, 0, -20, 0,
ax_anim 2, 1, 43, -20, 1, -20, 1,
ax_anim 2, 0, 43, -20, 0, -20, 0,
ax_anim 2, 0, 43, -20, 1, -20, 1,
ax_anim 2, 0, 42, -6, 0, -6, 0,
ax_anim_terminator
sHypnoAnims_2_8:
ax_anim 2, 0, 42, 1, -1, 1, -1,
ax_anim 4, 0, 42, 2, -2, 2, -2,
ax_anim 1, 0, 47, 0, 0, 0, 0,
ax_anim 1, 2, 46, -4, 4, -4, 4,
ax_anim 1, 0, 47, -10, 10, -10, 10,
ax_anim 2, 0, 46, -19, 20, -19, 20,
ax_anim 2, 1, 46, -20, 19, -20, 19,
ax_anim 2, 0, 46, -19, 20, -19, 20,
ax_anim 2, 0, 46, -20, 19, -20, 19,
ax_anim 2, 0, 45, -6, 6, -6, 6,
ax_anim_terminator
.align 2
sHypnoAnims_3_1:
ax_anim 2, 0, 49, 0, -2, 0, -2,
ax_anim 2, 0, 51, 0, -4, 0, -4,
ax_anim 4, 0, 93, 0, -5, 0, -5,
ax_anim 1, 0, 93, 0, -2, 0, -2,
ax_anim 1, 2, 51, -1, 4, -1, 4,
ax_anim 1, 0, 51, -2, 10, -2, 10,
ax_anim 2, 0, 52, 0, 18, 0, 18,
ax_anim 2, 1, 53, 2, 19, 2, 19,
ax_anim 2, 0, 53, 1, 19, 1, 19,
ax_anim 2, 0, 53, 2, 19, 2, 19,
ax_anim 2, 0, 53, 1, 19, 1, 19,
ax_anim 2, 0, 53, 2, 19, 2, 19,
ax_anim 2, 0, 48, 0, 11, 0, 11,
ax_anim 2, 0, 49, 0, 4, 0, 4,
ax_anim_terminator
sHypnoAnims_3_2:
ax_anim 2, 0, 55, -2, -2, -2, -2,
ax_anim 2, 0, 57, -4, -4, -4, -4,
ax_anim 4, 0, 51, -5, -5, -5, -5,
ax_anim 1, 0, 51, -2, -2, -2, -2,
ax_anim 1, 2, 57, 4, 6, 4, 6,
ax_anim 1, 0, 57, 9, 13, 9, 13,
ax_anim 2, 0, 58, 15, 16, 15, 16,
ax_anim 2, 1, 59, 15, 17, 15, 17,
ax_anim 2, 0, 59, 16, 16, 16, 16,
ax_anim 2, 0, 59, 15, 17, 15, 17,
ax_anim 2, 0, 59, 16, 16, 16, 16,
ax_anim 2, 0, 59, 15, 17, 15, 17,
ax_anim 2, 0, 54, 13, 11, 13, 11,
ax_anim 2, 0, 55, 4, 5, 4, 5,
ax_anim_terminator
sHypnoAnims_3_3:
ax_anim 2, 0, 61, -2, 0, -2, 0,
ax_anim 2, 0, 63, -4, 0, -4, 0,
ax_anim 4, 0, 57, -5, -2, -5, -2,
ax_anim 1, 0, 57, -2, -2, -2, -2,
ax_anim 1, 2, 63, 4, 1, 4, 1,
ax_anim 1, 0, 63, 10, 1, 10, 1,
ax_anim 2, 0, 64, 15, 0, 15, 0,
ax_anim 2, 1, 65, 16, 0, 16, 0,
ax_anim 2, 0, 65, 16, -1, 16, -1,
ax_anim 2, 0, 65, 16, 0, 16, 0,
ax_anim 2, 0, 65, 16, -1, 16, -1,
ax_anim 2, 0, 65, 16, 0, 16, 0,
ax_anim 2, 0, 60, 10, 0, 10, 0,
ax_anim 2, 0, 61, 4, 0, 4, 0,
ax_anim_terminator
sHypnoAnims_3_4:
ax_anim 2, 0, 67, -2, 2, -2, 2,
ax_anim 2, 0, 69, -4, 4, -4, 4,
ax_anim 4, 0, 63, -7, 5, -7, 5,
ax_anim 1, 0, 63, -4, 2, -4, 2,
ax_anim 1, 2, 69, 5, -5, 5, -5,
ax_anim 1, 0, 69, 12, -12, 12, -12,
ax_anim 2, 0, 70, 17, -15, 17, -15,
ax_anim 2, 1, 71, 17, -16, 17, -16,
ax_anim 2, 0, 71, 16, -17, 16, -17,
ax_anim 2, 0, 71, 17, -16, 17, -16,
ax_anim 2, 0, 71, 16, -17, 16, -17,
ax_anim 2, 0, 71, 17, -16, 17, -16,
ax_anim 2, 0, 66, 11, -13, 11, -13,
ax_anim 2, 0, 67, 4, -5, 4, -5,
ax_anim_terminator
sHypnoAnims_3_5:
ax_anim 2, 0, 73, 0, 2, 0, 2,
ax_anim 2, 0, 75, 0, 4, 0, 4,
ax_anim 4, 0, 69, -3, 8, -3, 8,
ax_anim 1, 0, 69, -3, 5, -3, 5,
ax_anim 1, 2, 75, 1, -4, 1, -4,
ax_anim 1, 0, 75, 2, -8, 2, -8,
ax_anim 2, 0, 76, 1, -14, 1, -14,
ax_anim 2, 1, 77, -1, -15, -1, -15,
ax_anim 2, 0, 77, 0, -15, 0, -15,
ax_anim 2, 0, 77, -1, -15, -1, -15,
ax_anim 2, 0, 77, 0, -15, 0, -15,
ax_anim 2, 0, 77, -1, -15, -1, -15,
ax_anim 2, 0, 72, 0, -11, 0, -11,
ax_anim 2, 0, 73, 0, -4, 0, -4,
ax_anim_terminator
sHypnoAnims_3_6:
ax_anim 2, 0, 79, 2, 2, 2, 2,
ax_anim 2, 0, 81, 4, 4, 4, 4,
ax_anim 4, 0, 75, 5, 5, 5, 5,
ax_anim 1, 0, 75, 2, 2, 2, 2,
ax_anim 1, 2, 81, -5, -5, -5, -5,
ax_anim 1, 0, 81, -12, -9, -12, -9,
ax_anim 2, 0, 82, -18, -12, -18, -12,
ax_anim 2, 1, 83, -19, -12, -19, -12,
ax_anim 2, 0, 83, -18, -13, -18, -13,
ax_anim 2, 0, 83, -19, -12, -19, -12,
ax_anim 2, 0, 83, -18, -13, -18, -13,
ax_anim 2, 0, 83, -19, -12, -19, -12,
ax_anim 2, 0, 78, -13, -9, -13, -9,
ax_anim 2, 0, 79, -6, -4, -6, -4,
ax_anim_terminator
sHypnoAnims_3_7:
ax_anim 2, 0, 85, 2, 0, 2, 0,
ax_anim 2, 0, 87, 4, 0, 4, 0,
ax_anim 4, 0, 81, 6, 1, 6, 1,
ax_anim 1, 0, 81, 3, 1, 3, 1,
ax_anim 1, 2, 87, -4, -1, -4, -1,
ax_anim 1, 0, 87, -10, -1, -10, -1,
ax_anim 2, 0, 88, -14, 0, -14, 0,
ax_anim 2, 1, 89, -15, 1, -15, 1,
ax_anim 2, 0, 89, -15, 0, -15, 0,
ax_anim 2, 0, 89, -15, 1, -15, 1,
ax_anim 2, 0, 89, -15, 0, -15, 0,
ax_anim 2, 0, 89, -15, 1, -15, 1,
ax_anim 2, 0, 84, -10, 0, -10, 0,
ax_anim 2, 0, 85, -4, 0, -4, 0,
ax_anim_terminator
sHypnoAnims_3_8:
ax_anim 2, 0, 91, 2, -2, 2, -2,
ax_anim 2, 0, 93, 4, -4, 4, -4,
ax_anim 4, 0, 87, 12, -5, 12, -5,
ax_anim 1, 0, 87, 9, -2, 9, -2,
ax_anim 1, 2, 93, -1, 2, -1, 2,
ax_anim 1, 0, 93, -8, 8, -8, 8,
ax_anim 2, 0, 94, -14, 16, -14, 16,
ax_anim 2, 1, 95, -14, 17, -14, 17,
ax_anim 2, 0, 95, -15, 16, -15, 16,
ax_anim 2, 0, 95, -14, 17, -14, 17,
ax_anim 2, 0, 95, -15, 16, -15, 16,
ax_anim 2, 0, 95, -14, 17, -14, 17,
ax_anim 2, 0, 90, -9, 12, -9, 12,
ax_anim 2, 0, 91, -4, 4, -4, 4,
ax_anim_terminator
.align 2
sHypnoAnims_4_1:
ax_anim 2, 0, 99, 0, -1, 0, -1,
ax_anim 2, 0, 102, 0, -3, 0, -3,
ax_anim 2, 0, 99, 0, -4, 0, -4,
ax_anim 2, 2, 102, 0, -4, 0, -4,
ax_anim 2, 0, 99, 0, -4, 0, -4,
ax_anim 1, 0, 102, 0, -3, 0, -3,
ax_anim 1, 0, 100, 0, 1, 0, 1,
ax_anim 2, 0, 103, 0, 6, 0, 6,
ax_anim 2, 1, 104, 1, 6, 1, 6,
ax_anim 2, 0, 101, 0, 6, 0, 6,
ax_anim 2, 0, 101, 1, 6, 1, 6,
ax_anim 2, 0, 101, 0, 6, 0, 6,
ax_anim 2, 0, 101, 1, 6, 1, 6,
ax_anim 2, 0, 96, 0, 3, 0, 3,
ax_anim_terminator
sHypnoAnims_4_2:
ax_anim 2, 0, 108, -1, -1, -1, -1,
ax_anim 2, 0, 111, -3, -3, -3, -3,
ax_anim 2, 0, 108, -4, -4, -4, -4,
ax_anim 2, 2, 111, -4, -4, -4, -4,
ax_anim 2, 0, 108, -4, -4, -4, -4,
ax_anim 1, 0, 111, -3, -3, -3, -3,
ax_anim 1, 0, 109, 1, 1, 1, 1,
ax_anim 2, 0, 112, 6, 6, 6, 6,
ax_anim 2, 1, 113, 7, 6, 7, 6,
ax_anim 2, 0, 110, 6, 6, 6, 6,
ax_anim 2, 0, 110, 7, 6, 7, 6,
ax_anim 2, 0, 110, 6, 6, 6, 6,
ax_anim 2, 0, 110, 7, 6, 7, 6,
ax_anim 2, 0, 106, 3, 3, 3, 3,
ax_anim_terminator
sHypnoAnims_4_3:
ax_anim 2, 0, 117, -1, 0, -1, 0,
ax_anim 2, 0, 120, -3, 0, -3, 0,
ax_anim 2, 0, 117, -4, 0, -4, 0,
ax_anim 2, 2, 120, -4, 0, -4, 0,
ax_anim 2, 0, 117, -4, 0, -4, 0,
ax_anim 1, 0, 120, -3, 0, -3, 0,
ax_anim 1, 0, 118, 1, 0, 1, 0,
ax_anim 2, 0, 121, 6, 0, 6, 0,
ax_anim 2, 1, 122, 7, 0, 7, 0,
ax_anim 2, 0, 119, 6, 0, 6, 0,
ax_anim 2, 0, 119, 7, 0, 7, 0,
ax_anim 2, 0, 119, 6, 0, 6, 0,
ax_anim 2, 0, 119, 7, 0, 7, 0,
ax_anim 2, 0, 115, 3, 0, 3, 0,
ax_anim_terminator
sHypnoAnims_4_4:
ax_anim 2, 0, 126, -1, 1, -1, 1,
ax_anim 2, 0, 129, -3, 3, -3, 3,
ax_anim 2, 0, 126, -4, 4, -4, 4,
ax_anim 2, 2, 129, -4, 4, -4, 4,
ax_anim 2, 0, 126, -4, 4, -4, 4,
ax_anim 1, 0, 129, -3, 3, -3, 3,
ax_anim 1, 0, 127, 1, -1, 1, -1,
ax_anim 2, 0, 130, 6, -6, 6, -6,
ax_anim 2, 1, 131, 7, -6, 7, -6,
ax_anim 2, 0, 128, 6, -6, 6, -6,
ax_anim 2, 0, 128, 7, -6, 7, -6,
ax_anim 2, 0, 128, 6, -6, 6, -6,
ax_anim 2, 0, 128, 7, -6, 7, -6,
ax_anim 2, 0, 124, 3, -3, 3, -3,
ax_anim_terminator
sHypnoAnims_4_5:
ax_anim 2, 0, 135, 0, 1, 0, 1,
ax_anim 2, 0, 138, 0, 3, 0, 3,
ax_anim 2, 0, 135, 0, 4, 0, 4,
ax_anim 2, 2, 138, 0, 4, 0, 4,
ax_anim 2, 0, 135, 0, 4, 0, 4,
ax_anim 1, 0, 138, 0, 3, 0, 3,
ax_anim 1, 0, 136, 0, -1, 0, -1,
ax_anim 2, 0, 139, 0, -6, 0, -6,
ax_anim 2, 1, 140, -1, -6, -1, -6,
ax_anim 2, 0, 137, 0, -6, 0, -6,
ax_anim 2, 0, 137, -1, -6, -1, -6,
ax_anim 2, 0, 137, 0, -6, 0, -6,
ax_anim 2, 0, 137, -1, -6, -1, -6,
ax_anim 2, 0, 133, 0, -3, 0, -3,
ax_anim_terminator
sHypnoAnims_4_6:
ax_anim 2, 0, 144, 1, 1, 1, 1,
ax_anim 2, 0, 147, 3, 3, 3, 3,
ax_anim 2, 0, 144, 4, 4, 4, 4,
ax_anim 2, 2, 147, 4, 4, 4, 4,
ax_anim 2, 0, 144, 4, 4, 4, 4,
ax_anim 1, 0, 147, 3, 3, 3, 3,
ax_anim 1, 0, 145, -1, -1, -1, -1,
ax_anim 2, 0, 148, -6, -6, -6, -6,
ax_anim 2, 1, 149, -7, -6, -7, -6,
ax_anim 2, 0, 146, -6, -6, -6, -6,
ax_anim 2, 0, 146, -7, -6, -7, -6,
ax_anim 2, 0, 146, -6, -6, -6, -6,
ax_anim 2, 0, 146, -7, -6, -7, -6,
ax_anim 2, 0, 142, -3, -3, -3, -3,
ax_anim_terminator
sHypnoAnims_4_7:
ax_anim 2, 0, 153, 1, 0, 1, 0,
ax_anim 2, 0, 156, 3, 0, 3, 0,
ax_anim 2, 0, 153, 4, 0, 4, 0,
ax_anim 2, 2, 156, 4, 0, 4, 0,
ax_anim 2, 0, 153, 4, 0, 4, 0,
ax_anim 1, 0, 156, 3, 0, 3, 0,
ax_anim 1, 0, 154, -1, 0, -1, 0,
ax_anim 2, 0, 157, -6, 0, -6, 0,
ax_anim 2, 1, 158, -7, 0, -7, 0,
ax_anim 2, 0, 155, -6, 0, -6, 0,
ax_anim 2, 0, 155, -7, 0, -7, 0,
ax_anim 2, 0, 155, -6, 0, -6, 0,
ax_anim 2, 0, 155, -7, 0, -7, 0,
ax_anim 2, 0, 151, -3, 0, -3, 0,
ax_anim_terminator
sHypnoAnims_4_8:
ax_anim 2, 0, 162, 1, -1, 1, -1,
ax_anim 2, 0, 165, 3, -3, 3, -3,
ax_anim 2, 0, 162, 4, -4, 4, -4,
ax_anim 2, 2, 165, 4, -4, 4, -4,
ax_anim 2, 0, 162, 4, -4, 4, -4,
ax_anim 1, 0, 165, 3, -3, 3, -3,
ax_anim 1, 0, 163, -1, 1, -1, 1,
ax_anim 2, 0, 166, -6, 6, -6, 6,
ax_anim 2, 1, 167, -7, 6, -7, 6,
ax_anim 2, 0, 164, -6, 6, -6, 6,
ax_anim 2, 0, 164, -7, 6, -7, 6,
ax_anim 2, 0, 164, -6, 6, -6, 6,
ax_anim 2, 0, 164, -7, 6, -7, 6,
ax_anim 2, 0, 160, -3, 3, -3, 3,
ax_anim_terminator
.align 2
sHypnoAnims_5_1:
ax_anim 2, 0, 168, 0, 0, 0, 0,
ax_anim 2, 0, 169, 0, 0, 0, 0,
ax_anim 2, 0, 168, 0, 0, 0, 0,
ax_anim 2, 0, 169, 0, 0, 0, 0,
ax_anim 2, 0, 170, 0, 0, 0, 0,
ax_anim 1, 0, 171, 0, 0, 0, 0,
ax_anim 1, 2, 172, 0, 0, 0, 0,
ax_anim 1, 0, 170, 0, 0, 0, 0,
ax_anim 1, 0, 171, 0, 0, 0, 0,
ax_anim 1, 0, 172, 0, 0, 0, 0,
ax_anim 1, 0, 170, 0, 0, 0, 0,
ax_anim 1, 0, 171, 0, 0, 0, 0,
ax_anim 1, 0, 172, 0, 0, 0, 0,
ax_anim 1, 0, 170, 0, 0, 0, 0,
ax_anim 1, 1, 171, 0, 0, 0, 0,
ax_anim 1, 0, 172, 0, 0, 0, 0,
ax_anim 1, 0, 170, 0, 0, 0, 0,
ax_anim 1, 0, 171, 0, 0, 0, 0,
ax_anim 1, 0, 172, 0, 0, 0, 0,
ax_anim 1, 0, 170, 0, 0, 0, 0,
ax_anim 1, 0, 171, 0, 0, 0, 0,
ax_anim 1, 0, 172, 0, 0, 0, 0,
ax_anim_terminator
sHypnoAnims_5_2:
ax_anim 2, 0, 173, 0, 0, 0, 0,
ax_anim 2, 0, 174, 0, 0, 0, 0,
ax_anim 2, 0, 173, 0, 0, 0, 0,
ax_anim 2, 0, 174, 0, 0, 0, 0,
ax_anim 2, 0, 175, 0, 0, 0, 0,
ax_anim 1, 0, 176, 0, 0, 0, 0,
ax_anim 1, 2, 177, 0, 0, 0, 0,
ax_anim 1, 0, 175, 0, 0, 0, 0,
ax_anim 1, 0, 176, 0, 0, 0, 0,
ax_anim 1, 0, 177, 0, 0, 0, 0,
ax_anim 1, 0, 175, 0, 0, 0, 0,
ax_anim 1, 0, 176, 0, 0, 0, 0,
ax_anim 1, 0, 177, 0, 0, 0, 0,
ax_anim 1, 0, 175, 0, 0, 0, 0,
ax_anim 1, 1, 176, 0, 0, 0, 0,
ax_anim 1, 0, 177, 0, 0, 0, 0,
ax_anim 1, 0, 175, 0, 0, 0, 0,
ax_anim 1, 0, 176, 0, 0, 0, 0,
ax_anim 1, 0, 177, 0, 0, 0, 0,
ax_anim 1, 0, 175, 0, 0, 0, 0,
ax_anim 1, 0, 176, 0, 0, 0, 0,
ax_anim 1, 0, 177, 0, 0, 0, 0,
ax_anim_terminator
sHypnoAnims_5_3:
ax_anim 2, 0, 178, 0, 0, 0, 0,
ax_anim 2, 0, 179, 0, 0, 0, 0,
ax_anim 2, 0, 178, 0, 0, 0, 0,
ax_anim 2, 0, 179, 0, 0, 0, 0,
ax_anim 2, 0, 180, 0, 0, 0, 0,
ax_anim 1, 0, 181, 0, 0, 0, 0,
ax_anim 1, 2, 182, 0, 0, 0, 0,
ax_anim 1, 0, 180, 0, 0, 0, 0,
ax_anim 1, 0, 181, 0, 0, 0, 0,
ax_anim 1, 0, 182, 0, 0, 0, 0,
ax_anim 1, 0, 180, 0, 0, 0, 0,
ax_anim 1, 0, 181, 0, 0, 0, 0,
ax_anim 1, 0, 182, 0, 0, 0, 0,
ax_anim 1, 0, 180, 0, 0, 0, 0,
ax_anim 1, 1, 181, 0, 0, 0, 0,
ax_anim 1, 0, 182, 0, 0, 0, 0,
ax_anim 1, 0, 180, 0, 0, 0, 0,
ax_anim 1, 0, 181, 0, 0, 0, 0,
ax_anim 1, 0, 182, 0, 0, 0, 0,
ax_anim 1, 0, 180, 0, 0, 0, 0,
ax_anim 1, 0, 181, 0, 0, 0, 0,
ax_anim 1, 0, 182, 0, 0, 0, 0,
ax_anim_terminator
sHypnoAnims_5_4:
ax_anim 2, 0, 183, 0, 0, 0, 0,
ax_anim 2, 0, 184, 0, 0, 0, 0,
ax_anim 2, 0, 183, 0, 0, 0, 0,
ax_anim 2, 0, 184, 0, 0, 0, 0,
ax_anim 2, 0, 185, 0, 0, 0, 0,
ax_anim 1, 0, 186, 0, 0, 0, 0,
ax_anim 1, 2, 187, 0, 0, 0, 0,
ax_anim 1, 0, 185, 0, 0, 0, 0,
ax_anim 1, 0, 186, 0, 0, 0, 0,
ax_anim 1, 0, 187, 0, 0, 0, 0,
ax_anim 1, 0, 185, 0, 0, 0, 0,
ax_anim 1, 0, 186, 0, 0, 0, 0,
ax_anim 1, 0, 187, 0, 0, 0, 0,
ax_anim 1, 0, 185, 0, 0, 0, 0,
ax_anim 1, 1, 186, 0, 0, 0, 0,
ax_anim 1, 0, 187, 0, 0, 0, 0,
ax_anim 1, 0, 185, 0, 0, 0, 0,
ax_anim 1, 0, 186, 0, 0, 0, 0,
ax_anim 1, 0, 187, 0, 0, 0, 0,
ax_anim 1, 0, 185, 0, 0, 0, 0,
ax_anim 1, 0, 186, 0, 0, 0, 0,
ax_anim 1, 0, 187, 0, 0, 0, 0,
ax_anim_terminator
sHypnoAnims_5_5:
ax_anim 2, 0, 188, 0, 0, 0, 0,
ax_anim 2, 0, 189, 0, 0, 0, 0,
ax_anim 2, 0, 188, 0, 0, 0, 0,
ax_anim 2, 0, 189, 0, 0, 0, 0,
ax_anim 2, 0, 190, 0, 0, 0, 0,
ax_anim 1, 0, 191, 0, 0, 0, 0,
ax_anim 1, 2, 192, 0, 0, 0, 0,
ax_anim 1, 0, 190, 0, 0, 0, 0,
ax_anim 1, 0, 191, 0, 0, 0, 0,
ax_anim 1, 0, 192, 0, 0, 0, 0,
ax_anim 1, 0, 190, 0, 0, 0, 0,
ax_anim 1, 0, 191, 0, 0, 0, 0,
ax_anim 1, 0, 192, 0, 0, 0, 0,
ax_anim 1, 0, 190, 0, 0, 0, 0,
ax_anim 1, 1, 191, 0, 0, 0, 0,
ax_anim 1, 0, 192, 0, 0, 0, 0,
ax_anim 1, 0, 190, 0, 0, 0, 0,
ax_anim 1, 0, 191, 0, 0, 0, 0,
ax_anim 1, 0, 192, 0, 0, 0, 0,
ax_anim 1, 0, 190, 0, 0, 0, 0,
ax_anim 1, 0, 191, 0, 0, 0, 0,
ax_anim 1, 0, 192, 0, 0, 0, 0,
ax_anim_terminator
sHypnoAnims_5_6:
ax_anim 2, 0, 193, 0, 0, 0, 0,
ax_anim 2, 0, 194, 0, 0, 0, 0,
ax_anim 2, 0, 193, 0, 0, 0, 0,
ax_anim 2, 0, 194, 0, 0, 0, 0,
ax_anim 2, 0, 195, 0, 0, 0, 0,
ax_anim 1, 0, 196, 0, 0, 0, 0,
ax_anim 1, 2, 197, 0, 0, 0, 0,
ax_anim 1, 0, 195, 0, 0, 0, 0,
ax_anim 1, 0, 196, 0, 0, 0, 0,
ax_anim 1, 0, 197, 0, 0, 0, 0,
ax_anim 1, 0, 195, 0, 0, 0, 0,
ax_anim 1, 0, 196, 0, 0, 0, 0,
ax_anim 1, 0, 197, 0, 0, 0, 0,
ax_anim 1, 0, 195, 0, 0, 0, 0,
ax_anim 1, 1, 196, 0, 0, 0, 0,
ax_anim 1, 0, 197, 0, 0, 0, 0,
ax_anim 1, 0, 195, 0, 0, 0, 0,
ax_anim 1, 0, 196, 0, 0, 0, 0,
ax_anim 1, 0, 197, 0, 0, 0, 0,
ax_anim 1, 0, 195, 0, 0, 0, 0,
ax_anim 1, 0, 196, 0, 0, 0, 0,
ax_anim 1, 0, 197, 0, 0, 0, 0,
ax_anim_terminator
sHypnoAnims_5_7:
ax_anim 2, 0, 198, 0, 0, 0, 0,
ax_anim 2, 0, 199, 0, 0, 0, 0,
ax_anim 2, 0, 198, 0, 0, 0, 0,
ax_anim 2, 0, 199, 0, 0, 0, 0,
ax_anim 2, 0, 200, 0, 0, 0, 0,
ax_anim 1, 0, 201, 0, 0, 0, 0,
ax_anim 1, 2, 202, 0, 0, 0, 0,
ax_anim 1, 0, 200, 0, 0, 0, 0,
ax_anim 1, 0, 201, 0, 0, 0, 0,
ax_anim 1, 0, 202, 0, 0, 0, 0,
ax_anim 1, 0, 200, 0, 0, 0, 0,
ax_anim 1, 0, 201, 0, 0, 0, 0,
ax_anim 1, 0, 202, 0, 0, 0, 0,
ax_anim 1, 0, 200, 0, 0, 0, 0,
ax_anim 1, 1, 201, 0, 0, 0, 0,
ax_anim 1, 0, 202, 0, 0, 0, 0,
ax_anim 1, 0, 200, 0, 0, 0, 0,
ax_anim 1, 0, 201, 0, 0, 0, 0,
ax_anim 1, 0, 202, 0, 0, 0, 0,
ax_anim 1, 0, 200, 0, 0, 0, 0,
ax_anim 1, 0, 201, 0, 0, 0, 0,
ax_anim 1, 0, 202, 0, 0, 0, 0,
ax_anim_terminator
sHypnoAnims_5_8:
ax_anim 2, 0, 203, 0, 0, 0, 0,
ax_anim 2, 0, 204, 0, 0, 0, 0,
ax_anim 2, 0, 203, 0, 0, 0, 0,
ax_anim 2, 0, 204, 0, 0, 0, 0,
ax_anim 2, 0, 205, 0, 0, 0, 0,
ax_anim 1, 0, 206, 0, 0, 0, 0,
ax_anim 1, 2, 207, 0, 0, 0, 0,
ax_anim 1, 0, 205, 0, 0, 0, 0,
ax_anim 1, 0, 206, 0, 0, 0, 0,
ax_anim 1, 0, 207, 0, 0, 0, 0,
ax_anim 1, 0, 205, 0, 0, 0, 0,
ax_anim 1, 0, 206, 0, 0, 0, 0,
ax_anim 1, 0, 207, 0, 0, 0, 0,
ax_anim 1, 0, 205, 0, 0, 0, 0,
ax_anim 1, 1, 206, 0, 0, 0, 0,
ax_anim 1, 0, 207, 0, 0, 0, 0,
ax_anim 1, 0, 205, 0, 0, 0, 0,
ax_anim 1, 0, 206, 0, 0, 0, 0,
ax_anim 1, 0, 207, 0, 0, 0, 0,
ax_anim 1, 0, 205, 0, 0, 0, 0,
ax_anim 1, 0, 206, 0, 0, 0, 0,
ax_anim 1, 0, 207, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sHypnoAnims_6_1:
ax_anim 35, 0, 208, 0, 0, 0, 0,
ax_anim 35, 0, 209, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sHypnoAnims_7_1:
ax_anim 2, 0, 210, 0, -2, 0, -2,
ax_anim 8, 0, 210, 0, -3, 0, -3,
ax_anim_terminator
sHypnoAnims_7_2:
ax_anim 2, 0, 211, -2, -2, -2, -2,
ax_anim 8, 0, 211, -3, -3, -3, -3,
ax_anim_terminator
sHypnoAnims_7_3:
ax_anim 2, 0, 212, -2, 0, -2, 0,
ax_anim 8, 0, 212, -3, 0, -3, 0,
ax_anim_terminator
sHypnoAnims_7_4:
ax_anim 2, 0, 213, -2, 2, -2, 2,
ax_anim 8, 0, 213, -3, 3, -3, 3,
ax_anim_terminator
sHypnoAnims_7_5:
ax_anim 2, 0, 214, 0, 2, 0, 2,
ax_anim 8, 0, 214, 0, 3, 0, 3,
ax_anim_terminator
sHypnoAnims_7_6:
ax_anim 2, 0, 215, 2, 2, 2, 2,
ax_anim 8, 0, 215, 3, 3, 3, 3,
ax_anim_terminator
sHypnoAnims_7_7:
ax_anim 2, 0, 216, 2, 0, 2, 0,
ax_anim 8, 0, 216, 3, 0, 3, 0,
ax_anim_terminator
sHypnoAnims_7_8:
ax_anim 2, 0, 217, 2, -2, 2, -2,
ax_anim 8, 0, 217, 3, -3, 3, -3,
ax_anim_terminator
.align 2
sHypnoAnims_8_1:
ax_anim 30, 0, 218, 0, 0, 0, 0,
ax_anim 1, 0, 219, 0, -2, 0, 0,
ax_anim 2, 0, 219, 0, -4, 0, 0,
ax_anim 3, 0, 219, 0, -5, 0, 0,
ax_anim 3, 0, 218, 0, -5, 0, 0,
ax_anim 3, 0, 220, 0, -5, 0, 0,
ax_anim 2, 0, 220, 0, -4, 0, 0,
ax_anim 1, 0, 220, 0, -2, 0, 0,
ax_anim_terminator
sHypnoAnims_8_2:
ax_anim 30, 0, 221, 0, 0, 0, 0,
ax_anim 1, 0, 222, 0, -2, 0, 0,
ax_anim 2, 0, 222, 0, -4, 0, 0,
ax_anim 3, 0, 222, 0, -5, 0, 0,
ax_anim 3, 0, 221, 0, -5, 0, 0,
ax_anim 3, 0, 223, 0, -5, 0, 0,
ax_anim 2, 0, 223, 0, -4, 0, 0,
ax_anim 1, 0, 223, 0, -2, 0, 0,
ax_anim_terminator
sHypnoAnims_8_3:
ax_anim 30, 0, 224, 0, 0, 0, 0,
ax_anim 1, 0, 225, 0, -2, 0, 0,
ax_anim 2, 0, 225, 0, -4, 0, 0,
ax_anim 3, 0, 225, 0, -5, 0, 0,
ax_anim 3, 0, 224, 0, -5, 0, 0,
ax_anim 3, 0, 226, 0, -5, 0, 0,
ax_anim 2, 0, 226, 0, -4, 0, 0,
ax_anim 1, 0, 226, 0, -2, 0, 0,
ax_anim_terminator
sHypnoAnims_8_4:
ax_anim 30, 0, 227, 0, 0, 0, 0,
ax_anim 1, 0, 228, 0, -2, 0, 0,
ax_anim 2, 0, 228, 0, -4, 0, 0,
ax_anim 3, 0, 228, 0, -5, 0, 0,
ax_anim 3, 0, 227, 0, -5, 0, 0,
ax_anim 3, 0, 229, 0, -5, 0, 0,
ax_anim 2, 0, 229, 0, -4, 0, 0,
ax_anim 1, 0, 229, 0, -2, 0, 0,
ax_anim_terminator
sHypnoAnims_8_5:
ax_anim 30, 0, 230, 0, 0, 0, 0,
ax_anim 1, 0, 231, 0, -2, 0, 0,
ax_anim 2, 0, 231, 0, -4, 0, 0,
ax_anim 3, 0, 231, 0, -5, 0, 0,
ax_anim 3, 0, 230, 0, -5, 0, 0,
ax_anim 3, 0, 232, 0, -5, 0, 0,
ax_anim 2, 0, 232, 0, -4, 0, 0,
ax_anim 1, 0, 232, 0, -2, 0, 0,
ax_anim_terminator
sHypnoAnims_8_6:
ax_anim 30, 0, 233, 0, 0, 0, 0,
ax_anim 1, 0, 234, 0, -2, 0, 0,
ax_anim 2, 0, 234, 0, -4, 0, 0,
ax_anim 3, 0, 234, 0, -5, 0, 0,
ax_anim 3, 0, 233, 0, -5, 0, 0,
ax_anim 3, 0, 235, 0, -5, 0, 0,
ax_anim 2, 0, 235, 0, -4, 0, 0,
ax_anim 1, 0, 235, 0, -2, 0, 0,
ax_anim_terminator
sHypnoAnims_8_7:
ax_anim 30, 0, 236, 0, 0, 0, 0,
ax_anim 1, 0, 237, 0, -2, 0, 0,
ax_anim 2, 0, 237, 0, -4, 0, 0,
ax_anim 3, 0, 237, 0, -5, 0, 0,
ax_anim 3, 0, 236, 0, -5, 0, 0,
ax_anim 3, 0, 238, 0, -5, 0, 0,
ax_anim 2, 0, 238, 0, -4, 0, 0,
ax_anim 1, 0, 238, 0, -2, 0, 0,
ax_anim_terminator
sHypnoAnims_8_8:
ax_anim 30, 0, 239, 0, 0, 0, 0,
ax_anim 1, 0, 240, 0, -2, 0, 0,
ax_anim 2, 0, 240, 0, -4, 0, 0,
ax_anim 3, 0, 240, 0, -5, 0, 0,
ax_anim 3, 0, 239, 0, -5, 0, 0,
ax_anim 3, 0, 241, 0, -5, 0, 0,
ax_anim 2, 0, 241, 0, -4, 0, 0,
ax_anim 1, 0, 241, 0, -2, 0, 0,
ax_anim_terminator
.align 2
sHypnoAnims_9_1:
ax_anim 2, 0, 242, 0, 0, 0, 0,
ax_anim 1, 0, 243, 6, 3, 6, 3,
ax_anim 2, 0, 244, 8, 9, 8, 9,
ax_anim 2, 0, 245, 7, 18, 7, 18,
ax_anim 3, 0, 246, 0, 21, 0, 21,
ax_anim 2, 3, 247, -7, 18, -7, 18,
ax_anim 2, 0, 248, -8, 9, -8, 9,
ax_anim 1, 0, 249, -6, 3, -6, 3,
ax_anim 1, 0, 242, 0, 0, 0, 0,
ax_anim_terminator
sHypnoAnims_9_2:
ax_anim 2, 0, 249, 0, 0, 0, 0,
ax_anim 1, 0, 242, 10, 0, 10, 0,
ax_anim 2, 0, 243, 19, 5, 19, 5,
ax_anim 2, 0, 244, 23, 12, 23, 12,
ax_anim 3, 0, 245, 23, 20, 23, 20,
ax_anim 2, 3, 246, 13, 22, 13, 22,
ax_anim 2, 0, 247, 3, 17, 3, 17,
ax_anim 1, 0, 248, 0, 7, 0, 7,
ax_anim 1, 0, 249, 0, 0, 0, 0,
ax_anim_terminator
sHypnoAnims_9_3:
ax_anim 2, 0, 248, 0, 0, 0, 0,
ax_anim 1, 0, 249, 3, -5, 3, -5,
ax_anim 2, 0, 242, 11, -5, 11, -6,
ax_anim 2, 0, 243, 18, -5, 18, -5,
ax_anim 3, 0, 244, 23, -2, 23, -2,
ax_anim 2, 3, 245, 20, 4, 20, 4,
ax_anim 2, 0, 246, 12, 5, 12, 5,
ax_anim 1, 0, 247, 4, 5, 4, 5,
ax_anim 1, 0, 248, 0, 0, 0, 0,
ax_anim_terminator
sHypnoAnims_9_4:
ax_anim 2, 0, 247, 0, 0, 0, 0,
ax_anim 1, 0, 248, -1, -8, -1, -8,
ax_anim 2, 0, 249, 2, -16, 2, -16,
ax_anim 2, 0, 242, 11, -20, 11, -20,
ax_anim 3, 0, 243, 22, -22, 22, -22,
ax_anim 2, 3, 244, 23, -13, 23, -13,
ax_anim 2, 0, 245, 17, -4, 17, -4,
ax_anim 1, 0, 246, 8, -1, 8, -1,
ax_anim 1, 0, 247, 0, 0, 0, 0,
ax_anim_terminator
sHypnoAnims_9_5:
ax_anim 2, 0, 246, 0, 0, 0, 0,
ax_anim 1, 0, 247, -8, -4, -8, -4,
ax_anim 2, 0, 248, -9, -12, -9, -12,
ax_anim 2, 0, 249, -7, -18, -7, -18,
ax_anim 3, 0, 242, 0, -21, 0, -22,
ax_anim 2, 3, 243, 7, -18, 7, -18,
ax_anim 2, 0, 244, 9, -10, 9, -10,
ax_anim 1, 0, 245, 8, -4, 8, -4,
ax_anim 1, 0, 246, 0, 0, 0, 0,
ax_anim_terminator
sHypnoAnims_9_6:
ax_anim 2, 0, 245, 0, 0, 0, 0,
ax_anim 1, 0, 244, 1, -8, 1, -8,
ax_anim 2, 0, 243, -2, -16, -2, -16,
ax_anim 2, 0, 242, -11, -20, -11, -20,
ax_anim 3, 0, 249, -22, -22, -22, -22,
ax_anim 2, 3, 248, -23, -13, -23, -13,
ax_anim 2, 0, 247, -17, -4, -17, -4,
ax_anim 1, 0, 246, -8, -1, -8, -1,
ax_anim 1, 0, 245, 0, 0, 0, 0,
ax_anim_terminator
sHypnoAnims_9_7:
ax_anim 2, 0, 244, 0, 0, 0, 0,
ax_anim 1, 0, 243, -3, -5, -3, -5,
ax_anim 2, 0, 242, -11, -5, -11, -6,
ax_anim 2, 0, 249, -18, -5, -18, -5,
ax_anim 3, 0, 248, -23, -2, -23, -2,
ax_anim 2, 3, 247, -20, 4, -20, 4,
ax_anim 2, 0, 246, -12, 5, -12, 5,
ax_anim 1, 0, 245, -4, 5, -4, 5,
ax_anim 1, 0, 244, 0, 0, 0, 0,
ax_anim_terminator
sHypnoAnims_9_8:
ax_anim 2, 0, 243, 0, 0, 0, 0,
ax_anim 1, 0, 242, -10, 0, -10, 0,
ax_anim 2, 0, 249, -19, 5, -19, 5,
ax_anim 2, 0, 248, -23, 12, -23, 12,
ax_anim 3, 0, 247, -23, 20, -23, 20,
ax_anim 2, 3, 246, -13, 22, -13, 22,
ax_anim 2, 0, 245, -3, 17, -3, 17,
ax_anim 1, 0, 244, 0, 7, 0, 7,
ax_anim 1, 0, 243, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sHypnoAnims_10_1:
ax_anim 2, 0, 250, 0, 0, 0, 0,
ax_anim 2, 0, 250, 6, 0, 6, 0,
ax_anim 2, 0, 250, -6, 0, -6, 0,
ax_anim 2, 0, 250, 10, 0, 10, 0,
ax_anim 2, 0, 250, -10, 0, -10, 0,
ax_anim 2, 0, 250, 12, 0, 12, 0,
ax_anim 3, 0, 250, -12, 0, -12, 0,
ax_anim 3, 0, 250, 13, 0, 13, 0,
ax_anim 3, 0, 250, -13, 0, -13, 0,
ax_anim 2, 0, 250, 12, 0, 12, 0,
ax_anim 3, 0, 250, -12, 0, -12, 0,
ax_anim 2, 0, 250, 10, 0, 10, 0,
ax_anim 2, 0, 250, -10, 0, -10, 0,
ax_anim 2, 0, 250, 6, 0, 6, 0,
ax_anim 2, 0, 250, -6, 0, -6, 0,
ax_anim 2, 0, 250, 0, 0, 0, 0,
ax_anim_terminator
sHypnoAnims_10_2:
ax_anim 2, 0, 251, 0, 0, 0, 0,
ax_anim 2, 0, 251, 6, -6, 6, -6,
ax_anim 2, 0, 251, -6, 6, -6, 6,
ax_anim 2, 0, 251, 10, -10, 10, -10,
ax_anim 2, 0, 251, -10, 10, -10, 10,
ax_anim 2, 0, 251, 12, -12, 12, -12,
ax_anim 3, 0, 251, -12, 12, -12, 12,
ax_anim 3, 0, 251, 13, -13, 13, -13,
ax_anim 3, 0, 251, -13, 13, -13, 13,
ax_anim 2, 0, 251, 12, -12, 12, -12,
ax_anim 3, 0, 251, -12, 12, -12, 12,
ax_anim 2, 0, 251, 10, -10, 10, -10,
ax_anim 2, 0, 251, -10, 10, -10, 10,
ax_anim 2, 0, 251, 6, -6, 6, -6,
ax_anim 2, 0, 251, -6, 6, -6, 6,
ax_anim 2, 0, 251, 0, 0, 0, 0,
ax_anim_terminator
sHypnoAnims_10_3:
ax_anim 2, 0, 252, 0, 0, 0, 0,
ax_anim 2, 0, 252, 0, -6, 0, -6,
ax_anim 2, 0, 252, 0, 6, 0, 6,
ax_anim 2, 0, 252, 0, -10, 0, -10,
ax_anim 2, 0, 252, 0, 10, 0, 10,
ax_anim 2, 0, 252, 0, -12, 0, -12,
ax_anim 3, 0, 252, 0, 12, 0, 12,
ax_anim 3, 0, 252, 0, -13, 0, -13,
ax_anim 3, 0, 252, 0, 13, 0, 13,
ax_anim 2, 0, 252, 0, -12, 0, -12,
ax_anim 3, 0, 252, 0, 12, 0, 12,
ax_anim 2, 0, 252, 0, -10, 0, -10,
ax_anim 2, 0, 252, 0, 10, 0, 10,
ax_anim 2, 0, 252, 0, -6, 0, -6,
ax_anim 2, 0, 252, 0, 6, 0, 6,
ax_anim 2, 0, 252, 0, 0, 0, 0,
ax_anim_terminator
sHypnoAnims_10_4:
ax_anim 2, 0, 253, 0, 0, 0, 0,
ax_anim 2, 0, 253, -6, -6, -6, -6,
ax_anim 2, 0, 253, 6, 6, 6, 6,
ax_anim 2, 0, 253, -10, -10, -10, -10,
ax_anim 2, 0, 253, 10, 10, 10, 10,
ax_anim 2, 0, 253, -12, -12, -12, -12,
ax_anim 3, 0, 253, 12, 12, 12, 12,
ax_anim 3, 0, 253, -13, -13, -13, -13,
ax_anim 3, 0, 253, 13, 13, 13, 13,
ax_anim 2, 0, 253, -12, -12, -12, -12,
ax_anim 3, 0, 253, 12, 12, 12, 12,
ax_anim 2, 0, 253, -10, -10, -10, -10,
ax_anim 2, 0, 253, 10, 10, 10, 10,
ax_anim 2, 0, 253, -6, -6, -6, -6,
ax_anim 2, 0, 253, 6, 6, 6, 6,
ax_anim 2, 0, 253, 0, 0, 0, 0,
ax_anim_terminator
sHypnoAnims_10_5:
ax_anim 2, 0, 254, 0, 0, 0, 0,
ax_anim 2, 0, 254, 6, 0, 6, 0,
ax_anim 2, 0, 254, -6, 0, -6, 0,
ax_anim 2, 0, 254, 10, 0, 10, 0,
ax_anim 2, 0, 254, -10, 0, -10, 0,
ax_anim 2, 0, 254, 12, 0, 12, 0,
ax_anim 3, 0, 254, -12, 0, -12, 0,
ax_anim 3, 0, 254, 13, 0, 13, 0,
ax_anim 3, 0, 254, -13, 0, -13, 0,
ax_anim 2, 0, 254, 12, 0, 12, 0,
ax_anim 3, 0, 254, -12, 0, -12, 0,
ax_anim 2, 0, 254, 10, 0, 10, 0,
ax_anim 2, 0, 254, -10, 0, -10, 0,
ax_anim 2, 0, 254, 6, 0, 6, 0,
ax_anim 2, 0, 254, -6, 0, -6, 0,
ax_anim 2, 0, 254, 0, 0, 0, 0,
ax_anim_terminator
sHypnoAnims_10_6:
ax_anim 2, 0, 255, 0, 0, 0, 0,
ax_anim 2, 0, 255, 6, -6, 6, -6,
ax_anim 2, 0, 255, -6, 6, -6, 6,
ax_anim 2, 0, 255, 10, -10, 10, -10,
ax_anim 2, 0, 255, -10, 10, -10, 10,
ax_anim 2, 0, 255, 12, -12, 12, -12,
ax_anim 3, 0, 255, -12, 12, -12, 12,
ax_anim 3, 0, 255, 13, -13, 13, -13,
ax_anim 3, 0, 255, -13, 13, -13, 13,
ax_anim 2, 0, 255, 12, -12, 12, -12,
ax_anim 3, 0, 255, -12, 12, -12, 12,
ax_anim 2, 0, 255, 10, -10, 10, -10,
ax_anim 2, 0, 255, -10, 10, -10, 10,
ax_anim 2, 0, 255, 6, -6, 6, -6,
ax_anim 2, 0, 255, -6, 6, -6, 6,
ax_anim 2, 0, 255, 0, 0, 0, 0,
ax_anim_terminator
sHypnoAnims_10_7:
ax_anim 2, 0, 256, 0, 0, 0, 0,
ax_anim 2, 0, 256, 0, -6, 0, -6,
ax_anim 2, 0, 256, 0, 6, 0, 6,
ax_anim 2, 0, 256, 0, -10, 0, -10,
ax_anim 2, 0, 256, 0, 10, 0, 10,
ax_anim 2, 0, 256, 0, -12, 0, -12,
ax_anim 3, 0, 256, 0, 12, 0, 12,
ax_anim 3, 0, 256, 0, -13, 0, -13,
ax_anim 3, 0, 256, 0, 13, 0, 13,
ax_anim 2, 0, 256, 0, -12, 0, -12,
ax_anim 3, 0, 256, 0, 12, 0, 12,
ax_anim 2, 0, 256, 0, -10, 0, -10,
ax_anim 2, 0, 256, 0, 10, 0, 10,
ax_anim 2, 0, 256, 0, -6, 0, -6,
ax_anim 2, 0, 256, 0, 6, 0, 6,
ax_anim 2, 0, 256, 0, 0, 0, 0,
ax_anim_terminator
sHypnoAnims_10_8:
ax_anim 2, 0, 257, 0, 0, 0, 0,
ax_anim 2, 0, 257, -6, -6, -6, -6,
ax_anim 2, 0, 257, 6, 6, 6, 6,
ax_anim 2, 0, 257, -10, -10, -10, -10,
ax_anim 2, 0, 257, 10, 10, 10, 10,
ax_anim 2, 0, 257, -12, -12, -12, -12,
ax_anim 3, 0, 257, 12, 12, 12, 12,
ax_anim 3, 0, 257, -13, -13, -13, -13,
ax_anim 3, 0, 257, 13, 13, 13, 13,
ax_anim 2, 0, 257, -12, -12, -12, -12,
ax_anim 3, 0, 257, 12, 12, 12, 12,
ax_anim 2, 0, 257, -10, -10, -10, -10,
ax_anim 2, 0, 257, 10, 10, 10, 10,
ax_anim 2, 0, 257, -6, -6, -6, -6,
ax_anim 2, 0, 257, 6, 6, 6, 6,
ax_anim 2, 0, 257, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sHypnoAnims_11_1:
ax_anim 2, 0, 259, 0, 0, 0, 0,
ax_anim 1, 0, 260, 0, -10, 0, 0,
ax_anim 2, 0, 260, 0, -16, 0, 0,
ax_anim 3, 0, 260, 0, -20, 0, 0,
ax_anim 4, 0, 260, 0, -21, 0, 0,
ax_anim 4, 0, 261, 0, -25, 0, 0,
ax_anim 3, 0, 261, 0, -23, 0, 0,
ax_anim 2, 0, 261, 0, -18, 0, 0,
ax_anim 1, 0, 261, 0, -12, 0, 0,
ax_anim 2, 2, 261, 0, 0, 0, 0,
ax_anim_terminator
sHypnoAnims_11_2:
ax_anim 2, 0, 262, 0, 0, 0, 0,
ax_anim 1, 0, 263, 0, -10, 0, 0,
ax_anim 2, 0, 263, 0, -16, 0, 0,
ax_anim 3, 0, 263, 0, -20, 0, 0,
ax_anim 4, 0, 263, 0, -21, 0, 0,
ax_anim 4, 0, 264, 0, -23, 0, 0,
ax_anim 3, 0, 264, 0, -22, 0, 0,
ax_anim 2, 0, 264, 0, -18, 0, 0,
ax_anim 1, 0, 264, 0, -12, 0, 0,
ax_anim 2, 2, 264, 0, 0, 0, 0,
ax_anim_terminator
sHypnoAnims_11_3:
ax_anim 2, 0, 265, 0, 0, 0, 0,
ax_anim 1, 0, 266, 0, -10, 0, 0,
ax_anim 2, 0, 266, 0, -16, 0, 0,
ax_anim 3, 0, 266, 0, -20, 0, 0,
ax_anim 4, 0, 266, 0, -21, 0, 0,
ax_anim 4, 0, 267, 0, -25, 0, 0,
ax_anim 3, 0, 267, 0, -24, 0, 0,
ax_anim 2, 0, 267, 0, -18, 0, 0,
ax_anim 1, 0, 267, 0, -12, 0, 0,
ax_anim 2, 2, 267, 0, 0, 0, 0,
ax_anim_terminator
sHypnoAnims_11_4:
ax_anim 2, 0, 268, 0, 0, 0, 0,
ax_anim 1, 0, 269, 0, -10, 0, 0,
ax_anim 2, 0, 269, 0, -16, 0, 0,
ax_anim 3, 0, 269, 0, -20, 0, 0,
ax_anim 4, 0, 269, 0, -21, 0, 0,
ax_anim 4, 0, 270, 0, -22, 0, 0,
ax_anim 3, 0, 270, 0, -21, 0, 0,
ax_anim 2, 0, 270, 0, -17, 0, 0,
ax_anim 1, 0, 270, 0, -11, 0, 0,
ax_anim 2, 2, 270, 0, 0, 0, 0,
ax_anim_terminator
sHypnoAnims_11_5:
ax_anim 2, 0, 271, 0, 0, 0, 0,
ax_anim 1, 0, 272, 0, -10, 0, 0,
ax_anim 2, 0, 272, 0, -16, 0, 0,
ax_anim 3, 0, 272, 0, -20, 0, 0,
ax_anim 4, 0, 272, 0, -21, 0, 0,
ax_anim 4, 0, 273, 0, -24, 0, 0,
ax_anim 3, 0, 273, 0, -23, 0, 0,
ax_anim 2, 0, 273, 0, -18, 0, 0,
ax_anim 1, 0, 273, 0, -12, 0, 0,
ax_anim 2, 2, 273, 0, 0, 0, 0,
ax_anim_terminator
sHypnoAnims_11_6:
ax_anim 2, 0, 274, 0, 0, 0, 0,
ax_anim 1, 0, 275, 0, -10, 0, 0,
ax_anim 2, 0, 275, 0, -16, 0, 0,
ax_anim 3, 0, 275, 0, -20, 0, 0,
ax_anim 4, 0, 275, 0, -21, 0, 0,
ax_anim 4, 0, 276, 0, -23, 0, 0,
ax_anim 3, 0, 276, 0, -21, 0, 0,
ax_anim 2, 0, 276, 0, -17, 0, 0,
ax_anim 1, 0, 276, 0, -11, 0, 0,
ax_anim 2, 2, 276, 0, 0, 0, 0,
ax_anim_terminator
sHypnoAnims_11_7:
ax_anim 2, 0, 277, 0, 0, 0, 0,
ax_anim 1, 0, 278, 0, -10, 0, 0,
ax_anim 2, 0, 278, 0, -16, 0, 0,
ax_anim 3, 0, 278, 0, -20, 0, 0,
ax_anim 4, 0, 278, 0, -21, 0, 0,
ax_anim 4, 0, 279, 0, -25, 0, 0,
ax_anim 3, 0, 279, 0, -24, 0, 0,
ax_anim 2, 0, 279, 0, -18, 0, 0,
ax_anim 1, 0, 279, 0, -12, 0, 0,
ax_anim 2, 2, 279, 0, 0, 0, 0,
ax_anim_terminator
sHypnoAnims_11_8:
ax_anim 2, 0, 280, 0, 0, 0, 0,
ax_anim 1, 0, 281, 0, -10, 0, 0,
ax_anim 2, 0, 281, 0, -16, 0, 0,
ax_anim 3, 0, 281, 0, -20, 0, 0,
ax_anim 4, 0, 281, 0, -21, 0, 0,
ax_anim 4, 0, 282, 0, -24, 0, 0,
ax_anim 3, 0, 282, 0, -23, 0, 0,
ax_anim 2, 0, 282, 0, -18, 0, 0,
ax_anim 1, 0, 282, 0, -12, 0, 0,
ax_anim 2, 2, 282, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sHypnoAnims_12_1:
ax_anim 2, 0, 283, 1, 0, 1, 0,
ax_anim 2, 0, 283, 0, 0, 0, 0,
ax_anim 2, 0, 283, 1, 0, 1, 0,
ax_anim 2, 0, 283, 0, 0, 0, 0,
ax_anim 2, 0, 283, 1, 0, 1, 0,
ax_anim 2, 2, 283, 0, 0, 0, 0,
ax_anim 2, 0, 283, 1, 0, 1, 0,
ax_anim 2, 0, 283, 0, 0, 0, 0,
ax_anim 2, 0, 283, 1, 0, 1, 0,
ax_anim 2, 1, 283, 0, 0, 0, 0,
ax_anim_terminator
sHypnoAnims_12_2:
ax_anim 2, 0, 290, 1, -1, 1, -1,
ax_anim 2, 0, 290, 0, 0, 0, 0,
ax_anim 2, 0, 290, 1, -1, 1, -1,
ax_anim 2, 0, 290, 0, 0, 0, 0,
ax_anim 2, 0, 290, 1, -1, 1, -1,
ax_anim 2, 2, 290, 0, 0, 0, 0,
ax_anim 2, 0, 290, 1, -1, 1, -1,
ax_anim 2, 0, 290, 0, 0, 0, 0,
ax_anim 2, 0, 290, 1, -1, 1, -1,
ax_anim 2, 1, 290, 0, 0, 0, 0,
ax_anim_terminator
sHypnoAnims_12_3:
ax_anim 2, 0, 289, 0, -1, 0, -1,
ax_anim 2, 0, 289, 0, 0, 0, 0,
ax_anim 2, 0, 289, 0, -1, 0, -1,
ax_anim 2, 0, 289, 0, 0, 0, 0,
ax_anim 2, 0, 289, 0, -1, 0, -1,
ax_anim 2, 2, 289, 0, 0, 0, 0,
ax_anim 2, 0, 289, 0, -1, 0, -1,
ax_anim 2, 0, 289, 0, 0, 0, 0,
ax_anim 2, 0, 289, 0, -1, 0, -1,
ax_anim 2, 1, 289, 0, 0, 0, 0,
ax_anim_terminator
sHypnoAnims_12_4:
ax_anim 2, 0, 288, -1, -1, -1, -1,
ax_anim 2, 0, 288, 0, 0, 0, 0,
ax_anim 2, 0, 288, -1, -1, -1, -1,
ax_anim 2, 0, 288, 0, 0, 0, 0,
ax_anim 2, 0, 288, -1, -1, -1, -1,
ax_anim 2, 2, 288, 0, 0, 0, 0,
ax_anim 2, 0, 288, -1, -1, -1, -1,
ax_anim 2, 0, 288, 0, 0, 0, 0,
ax_anim 2, 0, 288, -1, -1, -1, -1,
ax_anim 2, 1, 288, 0, 0, 0, 0,
ax_anim_terminator
sHypnoAnims_12_5:
ax_anim 2, 0, 287, 1, 0, 1, 0,
ax_anim 2, 0, 287, 0, 0, 0, 0,
ax_anim 2, 0, 287, 1, 0, 1, 0,
ax_anim 2, 0, 287, 0, 0, 0, 0,
ax_anim 2, 0, 287, 1, 0, 1, 0,
ax_anim 2, 2, 287, 0, 0, 0, 0,
ax_anim 2, 0, 287, 1, 0, 1, 0,
ax_anim 2, 0, 287, 0, 0, 0, 0,
ax_anim 2, 0, 287, 1, 0, 1, 0,
ax_anim 2, 1, 287, 0, 0, 0, 0,
ax_anim_terminator
sHypnoAnims_12_6:
ax_anim 2, 0, 286, 1, -1, 1, -1,
ax_anim 2, 0, 286, 0, 0, 0, 0,
ax_anim 2, 0, 286, 1, -1, 1, -1,
ax_anim 2, 0, 286, 0, 0, 0, 0,
ax_anim 2, 0, 286, 1, -1, 1, -1,
ax_anim 2, 2, 286, 0, 0, 0, 0,
ax_anim 2, 0, 286, 1, -1, 1, -1,
ax_anim 2, 0, 286, 0, 0, 0, 0,
ax_anim 2, 0, 286, 1, -1, 1, -1,
ax_anim 2, 1, 286, 0, 0, 0, 0,
ax_anim_terminator
sHypnoAnims_12_7:
ax_anim 2, 0, 285, 0, -1, 0, -1,
ax_anim 2, 0, 285, 0, 0, 0, 0,
ax_anim 2, 0, 285, 0, -1, 0, -1,
ax_anim 2, 0, 285, 0, 0, 0, 0,
ax_anim 2, 0, 285, 0, -1, 0, -1,
ax_anim 2, 2, 285, 0, 0, 0, 0,
ax_anim 2, 0, 285, 0, -1, 0, -1,
ax_anim 2, 0, 285, 0, 0, 0, 0,
ax_anim 2, 0, 285, 0, -1, 0, -1,
ax_anim 2, 1, 285, 0, 0, 0, 0,
ax_anim_terminator
sHypnoAnims_12_8:
ax_anim 2, 0, 284, -1, -1, -1, -1,
ax_anim 2, 0, 284, 0, 0, 0, 0,
ax_anim 2, 0, 284, -1, -1, -1, -1,
ax_anim 2, 0, 284, 0, 0, 0, 0,
ax_anim 2, 0, 284, -1, -1, -1, -1,
ax_anim 2, 2, 284, 0, 0, 0, 0,
ax_anim 2, 0, 284, -1, -1, -1, -1,
ax_anim 2, 0, 284, 0, 0, 0, 0,
ax_anim 2, 0, 284, -1, -1, -1, -1,
ax_anim 2, 1, 284, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sHypnoAnims_13_1:
ax_anim 2, 0, 292, 0, 0, 0, 0,
ax_anim 2, 0, 293, 0, 0, 0, 0,
ax_anim 2, 0, 294, 0, 0, 0, 0,
ax_anim 2, 0, 295, 0, 0, 0, 0,
ax_anim 2, 0, 296, 0, 0, 0, 0,
ax_anim 2, 0, 297, 0, 0, 0, 0,
ax_anim 2, 0, 298, 0, 0, 0, 0,
ax_anim 2, 0, 299, 0, 0, 0, 0,
ax_anim 2, 2, 292, 0, 0, 0, 0,
ax_anim_terminator
sHypnoAnims_13_2:
ax_anim 2, 0, 299, 0, 0, 0, 0,
ax_anim 2, 0, 292, 0, 0, 0, 0,
ax_anim 2, 0, 293, 0, 0, 0, 0,
ax_anim 2, 0, 294, 0, 0, 0, 0,
ax_anim 2, 0, 295, 0, 0, 0, 0,
ax_anim 2, 0, 296, 0, 0, 0, 0,
ax_anim 2, 0, 297, 0, 0, 0, 0,
ax_anim 2, 0, 298, 0, 0, 0, 0,
ax_anim 2, 2, 299, 0, 0, 0, 0,
ax_anim_terminator
sHypnoAnims_13_3:
ax_anim 2, 0, 298, 0, 0, 0, 0,
ax_anim 2, 0, 299, 0, 0, 0, 0,
ax_anim 2, 0, 292, 0, 0, 0, 0,
ax_anim 2, 0, 293, 0, 0, 0, 0,
ax_anim 2, 0, 294, 0, 0, 0, 0,
ax_anim 2, 0, 295, 0, 0, 0, 0,
ax_anim 2, 0, 296, 0, 0, 0, 0,
ax_anim 2, 0, 297, 0, 0, 0, 0,
ax_anim 2, 2, 298, 0, 0, 0, 0,
ax_anim_terminator
sHypnoAnims_13_4:
ax_anim 2, 0, 297, 0, 0, 0, 0,
ax_anim 2, 0, 298, 0, 0, 0, 0,
ax_anim 2, 0, 299, 0, 0, 0, 0,
ax_anim 2, 0, 292, 0, 0, 0, 0,
ax_anim 2, 0, 293, 0, 0, 0, 0,
ax_anim 2, 0, 294, 0, 0, 0, 0,
ax_anim 2, 0, 295, 0, 0, 0, 0,
ax_anim 2, 0, 296, 0, 0, 0, 0,
ax_anim 2, 2, 297, 0, 0, 0, 0,
ax_anim_terminator
sHypnoAnims_13_5:
ax_anim 2, 0, 296, 0, 0, 0, 0,
ax_anim 2, 0, 297, 0, 0, 0, 0,
ax_anim 2, 0, 298, 0, 0, 0, 0,
ax_anim 2, 0, 299, 0, 0, 0, 0,
ax_anim 2, 0, 292, 0, 0, 0, 0,
ax_anim 2, 0, 293, 0, 0, 0, 0,
ax_anim 2, 0, 294, 0, 0, 0, 0,
ax_anim 2, 0, 295, 0, 0, 0, 0,
ax_anim 2, 2, 296, 0, 0, 0, 0,
ax_anim_terminator
sHypnoAnims_13_6:
ax_anim 2, 0, 295, 0, 0, 0, 0,
ax_anim 2, 0, 296, 0, 0, 0, 0,
ax_anim 2, 0, 297, 0, 0, 0, 0,
ax_anim 2, 0, 298, 0, 0, 0, 0,
ax_anim 2, 0, 299, 0, 0, 0, 0,
ax_anim 2, 0, 292, 0, 0, 0, 0,
ax_anim 2, 0, 293, 0, 0, 0, 0,
ax_anim 2, 0, 294, 0, 0, 0, 0,
ax_anim 2, 2, 295, 0, 0, 0, 0,
ax_anim_terminator
sHypnoAnims_13_7:
ax_anim 2, 0, 294, 0, 0, 0, 0,
ax_anim 2, 0, 295, 0, 0, 0, 0,
ax_anim 2, 0, 296, 0, 0, 0, 0,
ax_anim 2, 0, 297, 0, 0, 0, 0,
ax_anim 2, 0, 298, 0, 0, 0, 0,
ax_anim 2, 0, 299, 0, 0, 0, 0,
ax_anim 2, 0, 292, 0, 0, 0, 0,
ax_anim 2, 0, 293, 0, 0, 0, 0,
ax_anim 2, 2, 294, 0, 0, 0, 0,
ax_anim_terminator
sHypnoAnims_13_8:
ax_anim 2, 0, 293, 0, 0, 0, 0,
ax_anim 2, 0, 294, 0, 0, 0, 0,
ax_anim 2, 0, 295, 0, 0, 0, 0,
ax_anim 2, 0, 296, 0, 0, 0, 0,
ax_anim 2, 0, 297, 0, 0, 0, 0,
ax_anim 2, 0, 298, 0, 0, 0, 0,
ax_anim 2, 0, 299, 0, 0, 0, 0,
ax_anim 2, 0, 292, 0, 0, 0, 0,
ax_anim 2, 2, 293, 0, 0, 0, 0,
ax_anim_terminator
sHypnoGfx1:
.incbin "baserom.gba", 0x9220B4, 0x200
sHypnoSprites1:
ax_sprite sHypnoGfx1, 0x200
ax_sprite_terminator
sHypnoGfx2:
.incbin "baserom.gba", 0x9222C4, 0x200
sHypnoSprites2:
ax_sprite sHypnoGfx2, 0x200
ax_sprite_terminator
sHypnoGfx3:
.incbin "baserom.gba", 0x9224D4, 0x200
sHypnoSprites3:
ax_sprite sHypnoGfx3, 0x200
ax_sprite_terminator
sHypnoGfx4:
.incbin "baserom.gba", 0x9226E4, 0x200
sHypnoSprites4:
ax_sprite sHypnoGfx4, 0x200
ax_sprite_terminator
sHypnoGfx5:
.incbin "baserom.gba", 0x9228F4, 0x200
sHypnoSprites5:
ax_sprite sHypnoGfx5, 0x200
ax_sprite_terminator
sHypnoGfx6:
.incbin "baserom.gba", 0x922B04, 0x200
sHypnoSprites6:
ax_sprite sHypnoGfx6, 0x200
ax_sprite_terminator
sHypnoGfx7:
.incbin "baserom.gba", 0x922D14, 0x200
sHypnoSprites7:
ax_sprite sHypnoGfx7, 0x200
ax_sprite_terminator
sHypnoGfx8:
.incbin "baserom.gba", 0x922F24, 0x200
sHypnoSprites8:
ax_sprite sHypnoGfx8, 0x200
ax_sprite_terminator
sHypnoGfx9:
.incbin "baserom.gba", 0x923134, 0x200
sHypnoSprites9:
ax_sprite sHypnoGfx9, 0x200
ax_sprite_terminator
sHypnoGfx10:
.incbin "baserom.gba", 0x923344, 0x200
sHypnoSprites10:
ax_sprite sHypnoGfx10, 0x200
ax_sprite_terminator
sHypnoGfx11:
.incbin "baserom.gba", 0x923554, 0x200
sHypnoSprites11:
ax_sprite sHypnoGfx11, 0x200
ax_sprite_terminator
sHypnoGfx12:
.incbin "baserom.gba", 0x923764, 0x200
sHypnoSprites12:
ax_sprite sHypnoGfx12, 0x200
ax_sprite_terminator
sHypnoGfx13:
.incbin "baserom.gba", 0x923974, 0x200
sHypnoSprites13:
ax_sprite sHypnoGfx13, 0x200
ax_sprite_terminator
sHypnoGfx14:
.incbin "baserom.gba", 0x923B84, 0x200
sHypnoSprites14:
ax_sprite sHypnoGfx14, 0x200
ax_sprite_terminator
sHypnoGfx15:
.incbin "baserom.gba", 0x923D94, 0x200
sHypnoSprites15:
ax_sprite sHypnoGfx15, 0x200
ax_sprite_terminator
sHypnoGfx16:
.incbin "baserom.gba", 0x923FA4, 0x200
sHypnoSprites16:
ax_sprite sHypnoGfx16, 0x200
ax_sprite_terminator
sHypnoGfx17:
.incbin "baserom.gba", 0x9241B4, 0x200
sHypnoSprites17:
ax_sprite sHypnoGfx17, 0x200
ax_sprite_terminator
sHypnoGfx18:
.incbin "baserom.gba", 0x9243C4, 0x200
sHypnoSprites18:
ax_sprite sHypnoGfx18, 0x200
ax_sprite_terminator
sHypnoGfx19:
.incbin "baserom.gba", 0x9245D4, 0x200
sHypnoSprites19:
ax_sprite sHypnoGfx19, 0x200
ax_sprite_terminator
sHypnoGfx20:
.incbin "baserom.gba", 0x9247E4, 0x200
sHypnoSprites20:
ax_sprite sHypnoGfx20, 0x200
ax_sprite_terminator
sHypnoGfx21:
.incbin "baserom.gba", 0x9249F4, 0x200
sHypnoSprites21:
ax_sprite sHypnoGfx21, 0x200
ax_sprite_terminator
sHypnoGfx22:
.incbin "baserom.gba", 0x924C04, 0x200
sHypnoSprites22:
ax_sprite sHypnoGfx22, 0x200
ax_sprite_terminator
sHypnoGfx23:
.incbin "baserom.gba", 0x924E14, 0x200
sHypnoSprites23:
ax_sprite sHypnoGfx23, 0x200
ax_sprite_terminator
sHypnoGfx24:
.incbin "baserom.gba", 0x925024, 0x200
sHypnoSprites24:
ax_sprite sHypnoGfx24, 0x200
ax_sprite_terminator
sHypnoGfx25:
.incbin "baserom.gba", 0x925234, 0x40
sHypnoGfx25_1:
.incbin "baserom.gba", 0x925274, 0x60
sHypnoGfx25_2:
.incbin "baserom.gba", 0x9252D4, 0x60
sHypnoSprites25:
ax_sprite 0, 0x20
ax_sprite sHypnoGfx25, 0x40
ax_sprite 0, 0x20
ax_sprite sHypnoGfx25_1, 0x60
ax_sprite 0, 0x40
ax_sprite sHypnoGfx25_2, 0x60
ax_sprite 0, 0x80
ax_sprite_terminator
sHypnoGfx26:
.incbin "baserom.gba", 0x925374, 0x20
sHypnoGfx26_1:
.incbin "baserom.gba", 0x925394, 0x40
sHypnoGfx26_2:
.incbin "baserom.gba", 0x9253D4, 0x60
sHypnoGfx26_3:
.incbin "baserom.gba", 0x925434, 0x20
sHypnoSprites26:
ax_sprite sHypnoGfx26, 0x20
ax_sprite 0, 0x60
ax_sprite sHypnoGfx26_1, 0x40
ax_sprite 0, 0x40
ax_sprite sHypnoGfx26_2, 0x60
ax_sprite 0, 0x40
ax_sprite sHypnoGfx26_3, 0x20
ax_sprite 0, 0x40
ax_sprite_terminator
sHypnoGfx27:
.incbin "baserom.gba", 0x92549C, 0x40
sHypnoGfx27_1:
.incbin "baserom.gba", 0x9254DC, 0x120
sHypnoSprites27:
ax_sprite 0, 0x20
ax_sprite sHypnoGfx27, 0x40
ax_sprite 0, 0x40
ax_sprite sHypnoGfx27_1, 0x120
ax_sprite 0, 0x40
ax_sprite_terminator
sHypnoGfx28:
.incbin "baserom.gba", 0x92562C, 0x40
sHypnoGfx28_1:
.incbin "baserom.gba", 0x92566C, 0x60
sHypnoGfx28_2:
.incbin "baserom.gba", 0x9256CC, 0x60
sHypnoGfx28_3:
.incbin "baserom.gba", 0x92572C, 0x60
sHypnoSprites28:
ax_sprite 0, 0x20
ax_sprite sHypnoGfx28, 0x40
ax_sprite 0, 0x20
ax_sprite sHypnoGfx28_1, 0x60
ax_sprite 0, 0x20
ax_sprite sHypnoGfx28_2, 0x60
ax_sprite 0, 0x20
ax_sprite sHypnoGfx28_3, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sHypnoGfx29:
.incbin "baserom.gba", 0x9257DC, 0x20
sHypnoGfx29_1:
.incbin "baserom.gba", 0x9257FC, 0x80
sHypnoGfx29_2:
.incbin "baserom.gba", 0x92587C, 0x60
sHypnoSprites29:
ax_sprite 0, 0x80
ax_sprite sHypnoGfx29, 0x20
ax_sprite 0, 0x60
ax_sprite sHypnoGfx29_1, 0x80
ax_sprite 0, 0x20
ax_sprite sHypnoGfx29_2, 0x60
ax_sprite_terminator
sHypnoGfx30:
.incbin "baserom.gba", 0x925914, 0x60
sHypnoGfx30_1:
.incbin "baserom.gba", 0x925974, 0x60
sHypnoGfx30_2:
.incbin "baserom.gba", 0x9259D4, 0x60
sHypnoSprites30:
ax_sprite 0, 0xa0
ax_sprite sHypnoGfx30, 0x60
ax_sprite 0, 0x20
ax_sprite sHypnoGfx30_1, 0x60
ax_sprite 0, 0x20
ax_sprite sHypnoGfx30_2, 0x60
ax_sprite_terminator
sHypnoGfx31:
.incbin "baserom.gba", 0x925A6C, 0x40
sHypnoGfx31_1:
.incbin "baserom.gba", 0x925AAC, 0x160
sHypnoSprites31:
ax_sprite 0, 0x20
ax_sprite sHypnoGfx31, 0x40
ax_sprite 0, 0x20
ax_sprite sHypnoGfx31_1, 0x160
ax_sprite 0, 0x20
ax_sprite_terminator
sHypnoGfx32:
.incbin "baserom.gba", 0x925C3C, 0xC0
sHypnoSprites32:
ax_sprite 0, 0x40
ax_sprite sHypnoGfx32, 0xc0
ax_sprite_terminator
sHypnoGfx33:
.incbin "baserom.gba", 0x925D14, 0x20
sHypnoGfx33_1:
.incbin "baserom.gba", 0x925D34, 0x100
sHypnoGfx33_2:
.incbin "baserom.gba", 0x925E34, 0x60
sHypnoSprites33:
ax_sprite 0, 0x40
ax_sprite sHypnoGfx33, 0x20
ax_sprite 0, 0x20
ax_sprite sHypnoGfx33_1, 0x100
ax_sprite 0, 0x20
ax_sprite sHypnoGfx33_2, 0x60
ax_sprite_terminator
sHypnoGfx34:
.incbin "baserom.gba", 0x925ECC, 0x1A0
sHypnoSprites34:
ax_sprite 0, 0x20
ax_sprite sHypnoGfx34, 0x1a0
ax_sprite 0, 0x40
ax_sprite_terminator
sHypnoGfx35:
.incbin "baserom.gba", 0x92608C, 0x40
sHypnoGfx35_1:
.incbin "baserom.gba", 0x9260CC, 0x40
sHypnoGfx35_2:
.incbin "baserom.gba", 0x92610C, 0x40
sHypnoGfx35_3:
.incbin "baserom.gba", 0x92614C, 0x40
sHypnoSprites35:
ax_sprite 0, 0x40
ax_sprite sHypnoGfx35, 0x40
ax_sprite 0, 0x40
ax_sprite sHypnoGfx35_1, 0x40
ax_sprite 0, 0x40
ax_sprite sHypnoGfx35_2, 0x40
ax_sprite 0, 0x20
ax_sprite sHypnoGfx35_3, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sHypnoGfx36:
.incbin "baserom.gba", 0x9261DC, 0x160
sHypnoGfx36_1:
.incbin "baserom.gba", 0x92633C, 0x20
sHypnoSprites36:
ax_sprite 0, 0x20
ax_sprite sHypnoGfx36, 0x160
ax_sprite 0, 0x20
ax_sprite sHypnoGfx36_1, 0x20
ax_sprite 0, 0x40
ax_sprite_terminator
sHypnoGfx37:
.incbin "baserom.gba", 0x92638C, 0x40
sHypnoGfx37_1:
.incbin "baserom.gba", 0x9263CC, 0x40
sHypnoGfx37_2:
.incbin "baserom.gba", 0x92640C, 0xE0
sHypnoSprites37:
ax_sprite 0, 0x20
ax_sprite sHypnoGfx37, 0x40
ax_sprite 0, 0x40
ax_sprite sHypnoGfx37_1, 0x40
ax_sprite 0, 0x40
ax_sprite sHypnoGfx37_2, 0xe0
ax_sprite_terminator
sHypnoGfx38:
.incbin "baserom.gba", 0x926524, 0x60
sHypnoGfx38_1:
.incbin "baserom.gba", 0x926584, 0x40
sHypnoGfx38_2:
.incbin "baserom.gba", 0x9265C4, 0x20
sHypnoGfx38_3:
.incbin "baserom.gba", 0x9265E4, 0x20
sHypnoSprites38:
ax_sprite 0, 0x20
ax_sprite sHypnoGfx38, 0x60
ax_sprite 0, 0x40
ax_sprite sHypnoGfx38_1, 0x40
ax_sprite 0, 0x60
ax_sprite sHypnoGfx38_2, 0x20
ax_sprite 0, 0x60
ax_sprite sHypnoGfx38_3, 0x20
ax_sprite_terminator
sHypnoGfx39:
.incbin "baserom.gba", 0x92664C, 0x40
sHypnoGfx39_1:
.incbin "baserom.gba", 0x92668C, 0x40
sHypnoGfx39_2:
.incbin "baserom.gba", 0x9266CC, 0x60
sHypnoGfx39_3:
.incbin "baserom.gba", 0x92672C, 0x60
sHypnoSprites39:
ax_sprite 0, 0x20
ax_sprite sHypnoGfx39, 0x40
ax_sprite 0, 0x40
ax_sprite sHypnoGfx39_1, 0x40
ax_sprite 0, 0x20
ax_sprite sHypnoGfx39_2, 0x60
ax_sprite 0, 0x20
ax_sprite sHypnoGfx39_3, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sHypnoGfx40:
.incbin "baserom.gba", 0x9267DC, 0x40
sHypnoGfx40_1:
.incbin "baserom.gba", 0x92681C, 0x60
sHypnoGfx40_2:
.incbin "baserom.gba", 0x92687C, 0x60
sHypnoGfx40_3:
.incbin "baserom.gba", 0x9268DC, 0x60
sHypnoSprites40:
ax_sprite 0, 0x20
ax_sprite sHypnoGfx40, 0x40
ax_sprite 0, 0x40
ax_sprite sHypnoGfx40_1, 0x60
ax_sprite 0, 0x20
ax_sprite sHypnoGfx40_2, 0x60
ax_sprite 0, 0x20
ax_sprite sHypnoGfx40_3, 0x60
ax_sprite_terminator
sHypnoGfx41:
.incbin "baserom.gba", 0x926984, 0x40
sHypnoGfx41_1:
.incbin "baserom.gba", 0x9269C4, 0x60
sHypnoGfx41_2:
.incbin "baserom.gba", 0x926A24, 0x20
sHypnoSprites41:
ax_sprite sHypnoGfx41, 0x40
ax_sprite 0, 0x40
ax_sprite sHypnoGfx41_1, 0x60
ax_sprite 0, 0x60
ax_sprite sHypnoGfx41_2, 0x20
ax_sprite 0, 0xa0
ax_sprite_terminator
sHypnoGfx42:
.incbin "baserom.gba", 0x926A7C, 0x40
sHypnoGfx42_1:
.incbin "baserom.gba", 0x926ABC, 0x60
sHypnoGfx42_2:
.incbin "baserom.gba", 0x926B1C, 0x60
sHypnoGfx42_3:
.incbin "baserom.gba", 0x926B7C, 0x40
sHypnoSprites42:
ax_sprite sHypnoGfx42, 0x40
ax_sprite 0, 0x40
ax_sprite sHypnoGfx42_1, 0x60
ax_sprite 0, 0x20
ax_sprite sHypnoGfx42_2, 0x60
ax_sprite 0, 0x40
ax_sprite sHypnoGfx42_3, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sHypnoGfx43:
.incbin "baserom.gba", 0x926C04, 0x40
sHypnoGfx43_1:
.incbin "baserom.gba", 0x926C44, 0x100
sHypnoGfx43_2:
.incbin "baserom.gba", 0x926D44, 0x60
sHypnoSprites43:
ax_sprite 0, 0x20
ax_sprite sHypnoGfx43, 0x40
ax_sprite 0, 0x20
ax_sprite sHypnoGfx43_1, 0x100
ax_sprite 0, 0x20
ax_sprite sHypnoGfx43_2, 0x60
ax_sprite_terminator
sHypnoGfx44:
.incbin "baserom.gba", 0x926DDC, 0x20
sHypnoGfx44_1:
.incbin "baserom.gba", 0x926DFC, 0x20
sHypnoGfx44_2:
.incbin "baserom.gba", 0x926E1C, 0x80
sHypnoGfx44_3:
.incbin "baserom.gba", 0x926E9C, 0x40
sHypnoSprites44:
ax_sprite 0, 0x20
ax_sprite sHypnoGfx44, 0x20
ax_sprite 0, 0x40
ax_sprite sHypnoGfx44_1, 0x20
ax_sprite 0, 0x20
ax_sprite sHypnoGfx44_2, 0x80
ax_sprite 0, 0x40
ax_sprite sHypnoGfx44_3, 0x40
ax_sprite 0, 0x40
ax_sprite_terminator
sHypnoGfx45:
.incbin "baserom.gba", 0x926F2C, 0x40
sHypnoGfx45_1:
.incbin "baserom.gba", 0x926F6C, 0x180
sHypnoSprites45:
ax_sprite 0, 0x20
ax_sprite sHypnoGfx45, 0x40
ax_sprite 0, 0x20
ax_sprite sHypnoGfx45_1, 0x180
ax_sprite_terminator
sHypnoGfx46:
.incbin "baserom.gba", 0x927114, 0x20
sHypnoGfx46_1:
.incbin "baserom.gba", 0x927134, 0x60
sHypnoGfx46_2:
.incbin "baserom.gba", 0x927194, 0x60
sHypnoGfx46_3:
.incbin "baserom.gba", 0x9271F4, 0x60
sHypnoSprites46:
ax_sprite 0, 0x20
ax_sprite sHypnoGfx46, 0x20
ax_sprite 0, 0x40
ax_sprite sHypnoGfx46_1, 0x60
ax_sprite 0, 0x20
ax_sprite sHypnoGfx46_2, 0x60
ax_sprite 0, 0x20
ax_sprite sHypnoGfx46_3, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sHypnoGfx47:
.incbin "baserom.gba", 0x9272A4, 0x20
sHypnoGfx47_1:
.incbin "baserom.gba", 0x9272C4, 0x60
sHypnoGfx47_2:
.incbin "baserom.gba", 0x927324, 0x40
sHypnoGfx47_3:
.incbin "baserom.gba", 0x927364, 0x40
sHypnoSprites47:
ax_sprite 0, 0x40
ax_sprite sHypnoGfx47, 0x20
ax_sprite 0, 0x20
ax_sprite sHypnoGfx47_1, 0x60
ax_sprite 0, 0x20
ax_sprite sHypnoGfx47_2, 0x40
ax_sprite 0, 0x40
ax_sprite sHypnoGfx47_3, 0x40
ax_sprite 0, 0x40
ax_sprite_terminator
sHypnoGfx48:
.incbin "baserom.gba", 0x9273F4, 0x60
sHypnoGfx48_1:
.incbin "baserom.gba", 0x927454, 0xE0
sHypnoSprites48:
ax_sprite 0, 0x80
ax_sprite sHypnoGfx48, 0x60
ax_sprite 0, 0x20
ax_sprite sHypnoGfx48_1, 0xe0
ax_sprite 0, 0x20
ax_sprite_terminator
sHypnoGfx49:
.incbin "baserom.gba", 0x927564, 0x20
sHypnoSprites49:
ax_sprite sHypnoGfx49, 0x20
ax_sprite_terminator
sHypnoGfx50:
.incbin "baserom.gba", 0x927594, 0x80
sHypnoSprites50:
ax_sprite sHypnoGfx50, 0x80
ax_sprite_terminator
sHypnoGfx51:
.incbin "baserom.gba", 0x927624, 0x60
sHypnoGfx51_1:
.incbin "baserom.gba", 0x927684, 0x100
sHypnoSprites51:
ax_sprite sHypnoGfx51, 0x60
ax_sprite 0, 0x20
ax_sprite sHypnoGfx51_1, 0x100
ax_sprite 0, 0x80
ax_sprite_terminator
sHypnoGfx52:
.incbin "baserom.gba", 0x9277AC, 0x40
sHypnoGfx52_1:
.incbin "baserom.gba", 0x9277EC, 0x100
sHypnoSprites52:
ax_sprite 0, 0x20
ax_sprite sHypnoGfx52, 0x40
ax_sprite 0, 0x20
ax_sprite sHypnoGfx52_1, 0x100
ax_sprite 0, 0x80
ax_sprite_terminator
sHypnoGfx53:
.incbin "baserom.gba", 0x92791C, 0x60
sHypnoGfx53_1:
.incbin "baserom.gba", 0x92797C, 0xE0
sHypnoSprites53:
ax_sprite 0, 0xa0
ax_sprite sHypnoGfx53, 0x60
ax_sprite 0, 0x20
ax_sprite sHypnoGfx53_1, 0xe0
ax_sprite_terminator
sHypnoGfx54:
.incbin "baserom.gba", 0x927A84, 0x20
sHypnoGfx54_1:
.incbin "baserom.gba", 0x927AA4, 0x60
sHypnoGfx54_2:
.incbin "baserom.gba", 0x927B04, 0xE0
sHypnoSprites54:
ax_sprite 0, 0x40
ax_sprite sHypnoGfx54, 0x20
ax_sprite 0, 0x40
ax_sprite sHypnoGfx54_1, 0x60
ax_sprite 0, 0x20
ax_sprite sHypnoGfx54_2, 0xe0
ax_sprite_terminator
sHypnoGfx55:
.incbin "baserom.gba", 0x927C1C, 0x20
sHypnoGfx55_1:
.incbin "baserom.gba", 0x927C3C, 0x60
sHypnoGfx55_2:
.incbin "baserom.gba", 0x927C9C, 0x60
sHypnoGfx55_3:
.incbin "baserom.gba", 0x927CFC, 0x60
sHypnoSprites55:
ax_sprite 0, 0x40
ax_sprite sHypnoGfx55, 0x20
ax_sprite 0, 0x40
ax_sprite sHypnoGfx55_1, 0x60
ax_sprite 0, 0x20
ax_sprite sHypnoGfx55_2, 0x60
ax_sprite 0, 0x20
ax_sprite sHypnoGfx55_3, 0x60
ax_sprite_terminator
sHypnoGfx56:
.incbin "baserom.gba", 0x927DA4, 0x20
sHypnoGfx56_1:
.incbin "baserom.gba", 0x927DC4, 0x60
sHypnoGfx56_2:
.incbin "baserom.gba", 0x927E24, 0x60
sHypnoGfx56_3:
.incbin "baserom.gba", 0x927E84, 0x40
sHypnoSprites56:
ax_sprite 0, 0x40
ax_sprite sHypnoGfx56, 0x20
ax_sprite 0, 0x40
ax_sprite sHypnoGfx56_1, 0x60
ax_sprite 0, 0x20
ax_sprite sHypnoGfx56_2, 0x60
ax_sprite 0, 0x20
ax_sprite sHypnoGfx56_3, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sHypnoGfx57:
.incbin "baserom.gba", 0x927F14, 0x40
sHypnoGfx57_1:
.incbin "baserom.gba", 0x927F54, 0x140
sHypnoSprites57:
ax_sprite 0, 0x20
ax_sprite sHypnoGfx57, 0x40
ax_sprite 0, 0x40
ax_sprite sHypnoGfx57_1, 0x140
ax_sprite 0, 0x20
ax_sprite_terminator
sHypnoGfx58:
.incbin "baserom.gba", 0x9280C4, 0x40
sHypnoGfx58_1:
.incbin "baserom.gba", 0x928104, 0x160
sHypnoSprites58:
ax_sprite 0, 0x20
ax_sprite sHypnoGfx58, 0x40
ax_sprite 0, 0x20
ax_sprite sHypnoGfx58_1, 0x160
ax_sprite 0, 0x20
ax_sprite_terminator
sHypnoGfx59:
.incbin "baserom.gba", 0x928294, 0x40
sHypnoGfx59_1:
.incbin "baserom.gba", 0x9282D4, 0x180
sHypnoSprites59:
ax_sprite 0, 0x20
ax_sprite sHypnoGfx59, 0x40
ax_sprite 0, 0x20
ax_sprite sHypnoGfx59_1, 0x180
ax_sprite_terminator
sHypnoGfx60:
.incbin "baserom.gba", 0x92847C, 0x180
sHypnoSprites60:
ax_sprite 0, 0x80
ax_sprite sHypnoGfx60, 0x180
ax_sprite_terminator
sHypnoGfx61:
.incbin "baserom.gba", 0x928614, 0x40
sHypnoGfx61_1:
.incbin "baserom.gba", 0x928654, 0x100
sHypnoGfx61_2:
.incbin "baserom.gba", 0x928754, 0x60
sHypnoSprites61:
ax_sprite 0, 0x20
ax_sprite sHypnoGfx61, 0x40
ax_sprite 0, 0x20
ax_sprite sHypnoGfx61_1, 0x100
ax_sprite 0, 0x20
ax_sprite sHypnoGfx61_2, 0x60
ax_sprite_terminator
sHypnoGfx62:
.incbin "baserom.gba", 0x9287EC, 0x40
sHypnoGfx62_1:
.incbin "baserom.gba", 0x92882C, 0x60
sHypnoGfx62_2:
.incbin "baserom.gba", 0x92888C, 0x100
sHypnoSprites62:
ax_sprite 0, 0x20
ax_sprite sHypnoGfx62, 0x40
ax_sprite 0, 0x20
ax_sprite sHypnoGfx62_1, 0x60
ax_sprite 0, 0x20
ax_sprite sHypnoGfx62_2, 0x100
ax_sprite_terminator
sHypnoGfx63:
.incbin "baserom.gba", 0x9289C4, 0x20
sHypnoGfx63_1:
.incbin "baserom.gba", 0x9289E4, 0x60
sHypnoGfx63_2:
.incbin "baserom.gba", 0x928A44, 0x60
sHypnoGfx63_3:
.incbin "baserom.gba", 0x928AA4, 0x60
sHypnoSprites63:
ax_sprite 0, 0x20
ax_sprite sHypnoGfx63, 0x20
ax_sprite 0, 0x40
ax_sprite sHypnoGfx63_1, 0x60
ax_sprite 0, 0x20
ax_sprite sHypnoGfx63_2, 0x60
ax_sprite 0, 0x20
ax_sprite sHypnoGfx63_3, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sHypnoGfx64:
.incbin "baserom.gba", 0x928B54, 0x20
sHypnoGfx64_1:
.incbin "baserom.gba", 0x928B74, 0x60
sHypnoGfx64_2:
.incbin "baserom.gba", 0x928BD4, 0x60
sHypnoGfx64_3:
.incbin "baserom.gba", 0x928C34, 0x40
sHypnoSprites64:
ax_sprite 0, 0x20
ax_sprite sHypnoGfx64, 0x20
ax_sprite 0, 0x40
ax_sprite sHypnoGfx64_1, 0x60
ax_sprite 0, 0x20
ax_sprite sHypnoGfx64_2, 0x60
ax_sprite 0, 0x40
ax_sprite sHypnoGfx64_3, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sHypnoGfx65:
.incbin "baserom.gba", 0x928CC4, 0x20
sHypnoGfx65_1:
.incbin "baserom.gba", 0x928CE4, 0x60
sHypnoGfx65_2:
.incbin "baserom.gba", 0x928D44, 0x60
sHypnoGfx65_3:
.incbin "baserom.gba", 0x928DA4, 0x40
sHypnoSprites65:
ax_sprite 0, 0x20
ax_sprite sHypnoGfx65, 0x20
ax_sprite 0, 0x40
ax_sprite sHypnoGfx65_1, 0x60
ax_sprite 0, 0x20
ax_sprite sHypnoGfx65_2, 0x60
ax_sprite 0, 0x40
ax_sprite sHypnoGfx65_3, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sHypnoGfx66:
.incbin "baserom.gba", 0x928E34, 0x60
sHypnoGfx66_1:
.incbin "baserom.gba", 0x928E94, 0x80
sHypnoGfx66_2:
.incbin "baserom.gba", 0x928F14, 0x60
sHypnoSprites66:
ax_sprite 0, 0x80
ax_sprite sHypnoGfx66, 0x60
ax_sprite 0, 0x20
ax_sprite sHypnoGfx66_1, 0x80
ax_sprite 0, 0x20
ax_sprite sHypnoGfx66_2, 0x60
ax_sprite_terminator
sHypnoGfx67:
.incbin "baserom.gba", 0x928FAC, 0x200
sHypnoSprites67:
ax_sprite sHypnoGfx67, 0x200
ax_sprite_terminator
sHypnoGfx68:
.incbin "baserom.gba", 0x9291BC, 0x200
sHypnoSprites68:
ax_sprite sHypnoGfx68, 0x200
ax_sprite_terminator
sHypnoGfx69:
.incbin "baserom.gba", 0x9293CC, 0x200
sHypnoSprites69:
ax_sprite sHypnoGfx69, 0x200
ax_sprite_terminator
sHypnoGfx70:
.incbin "baserom.gba", 0x9295DC, 0x200
sHypnoSprites70:
ax_sprite sHypnoGfx70, 0x200
ax_sprite_terminator
sHypnoGfx71:
.incbin "baserom.gba", 0x9297EC, 0x200
sHypnoSprites71:
ax_sprite sHypnoGfx71, 0x200
ax_sprite_terminator
sHypnoGfx72:
.incbin "baserom.gba", 0x9299FC, 0x200
sHypnoSprites72:
ax_sprite sHypnoGfx72, 0x200
ax_sprite_terminator
sHypnoGfx73:
.incbin "baserom.gba", 0x929C0C, 0x200
sHypnoSprites73:
ax_sprite sHypnoGfx73, 0x200
ax_sprite_terminator
sAxPosesHypno:
.4byte sHypnoPose1
.4byte sHypnoPose2
.4byte sHypnoPose3
.4byte sHypnoPose4
.4byte sHypnoPose5
.4byte sHypnoPose6
.4byte sHypnoPose7
.4byte sHypnoPose8
.4byte sHypnoPose9
.4byte sHypnoPose10
.4byte sHypnoPose11
.4byte sHypnoPose12
.4byte sHypnoPose13
.4byte sHypnoPose14
.4byte sHypnoPose15
.4byte sHypnoPose16
.4byte sHypnoPose17
.4byte sHypnoPose18
.4byte sHypnoPose19
.4byte sHypnoPose20
.4byte sHypnoPose21
.4byte sHypnoPose22
.4byte sHypnoPose23
.4byte sHypnoPose24
.4byte sHypnoPose25
.4byte sHypnoPose26
.4byte sHypnoPose27
.4byte sHypnoPose28
.4byte sHypnoPose29
.4byte sHypnoPose30
.4byte sHypnoPose31
.4byte sHypnoPose32
.4byte sHypnoPose33
.4byte sHypnoPose34
.4byte sHypnoPose35
.4byte sHypnoPose36
.4byte sHypnoPose37
.4byte sHypnoPose38
.4byte sHypnoPose39
.4byte sHypnoPose40
.4byte sHypnoPose41
.4byte sHypnoPose42
.4byte sHypnoPose43
.4byte sHypnoPose44
.4byte sHypnoPose45
.4byte sHypnoPose46
.4byte sHypnoPose47
.4byte sHypnoPose48
.4byte sHypnoPose49
.4byte sHypnoPose50
.4byte sHypnoPose51
.4byte sHypnoPose52
.4byte sHypnoPose53
.4byte sHypnoPose54
.4byte sHypnoPose55
.4byte sHypnoPose56
.4byte sHypnoPose57
.4byte sHypnoPose58
.4byte sHypnoPose59
.4byte sHypnoPose60
.4byte sHypnoPose61
.4byte sHypnoPose62
.4byte sHypnoPose63
.4byte sHypnoPose64
.4byte sHypnoPose65
.4byte sHypnoPose66
.4byte sHypnoPose67
.4byte sHypnoPose68
.4byte sHypnoPose69
.4byte sHypnoPose70
.4byte sHypnoPose71
.4byte sHypnoPose72
.4byte sHypnoPose73
.4byte sHypnoPose74
.4byte sHypnoPose75
.4byte sHypnoPose76
.4byte sHypnoPose77
.4byte sHypnoPose78
.4byte sHypnoPose79
.4byte sHypnoPose80
.4byte sHypnoPose81
.4byte sHypnoPose82
.4byte sHypnoPose83
.4byte sHypnoPose84
.4byte sHypnoPose85
.4byte sHypnoPose86
.4byte sHypnoPose87
.4byte sHypnoPose88
.4byte sHypnoPose89
.4byte sHypnoPose90
.4byte sHypnoPose91
.4byte sHypnoPose92
.4byte sHypnoPose93
.4byte sHypnoPose94
.4byte sHypnoPose95
.4byte sHypnoPose96
.4byte sHypnoPose97
.4byte sHypnoPose98
.4byte sHypnoPose99
.4byte sHypnoPose100
.4byte sHypnoPose101
.4byte sHypnoPose102
.4byte sHypnoPose103
.4byte sHypnoPose104
.4byte sHypnoPose105
.4byte sHypnoPose106
.4byte sHypnoPose107
.4byte sHypnoPose108
.4byte sHypnoPose109
.4byte sHypnoPose110
.4byte sHypnoPose111
.4byte sHypnoPose112
.4byte sHypnoPose113
.4byte sHypnoPose114
.4byte sHypnoPose115
.4byte sHypnoPose116
.4byte sHypnoPose117
.4byte sHypnoPose118
.4byte sHypnoPose119
.4byte sHypnoPose120
.4byte sHypnoPose121
.4byte sHypnoPose122
.4byte sHypnoPose123
.4byte sHypnoPose124
.4byte sHypnoPose125
.4byte sHypnoPose126
.4byte sHypnoPose127
.4byte sHypnoPose128
.4byte sHypnoPose129
.4byte sHypnoPose130
.4byte sHypnoPose131
.4byte sHypnoPose132
.4byte sHypnoPose133
.4byte sHypnoPose134
.4byte sHypnoPose135
.4byte sHypnoPose136
.4byte sHypnoPose137
.4byte sHypnoPose138
.4byte sHypnoPose139
.4byte sHypnoPose140
.4byte sHypnoPose141
.4byte sHypnoPose142
.4byte sHypnoPose143
.4byte sHypnoPose144
.4byte sHypnoPose145
.4byte sHypnoPose146
.4byte sHypnoPose147
.4byte sHypnoPose148
.4byte sHypnoPose149
.4byte sHypnoPose150
.4byte sHypnoPose151
.4byte sHypnoPose152
.4byte sHypnoPose153
.4byte sHypnoPose154
.4byte sHypnoPose155
.4byte sHypnoPose156
.4byte sHypnoPose157
.4byte sHypnoPose158
.4byte sHypnoPose159
.4byte sHypnoPose160
.4byte sHypnoPose161
.4byte sHypnoPose162
.4byte sHypnoPose163
.4byte sHypnoPose164
.4byte sHypnoPose165
.4byte sHypnoPose166
.4byte sHypnoPose167
.4byte sHypnoPose168
.4byte sHypnoPose169
.4byte sHypnoPose170
.4byte sHypnoPose171
.4byte sHypnoPose172
.4byte sHypnoPose173
.4byte sHypnoPose174
.4byte sHypnoPose175
.4byte sHypnoPose176
.4byte sHypnoPose177
.4byte sHypnoPose178
.4byte sHypnoPose179
.4byte sHypnoPose180
.4byte sHypnoPose181
.4byte sHypnoPose182
.4byte sHypnoPose183
.4byte sHypnoPose184
.4byte sHypnoPose185
.4byte sHypnoPose186
.4byte sHypnoPose187
.4byte sHypnoPose188
.4byte sHypnoPose189
.4byte sHypnoPose190
.4byte sHypnoPose191
.4byte sHypnoPose192
.4byte sHypnoPose193
.4byte sHypnoPose194
.4byte sHypnoPose195
.4byte sHypnoPose196
.4byte sHypnoPose197
.4byte sHypnoPose198
.4byte sHypnoPose199
.4byte sHypnoPose200
.4byte sHypnoPose201
.4byte sHypnoPose202
.4byte sHypnoPose203
.4byte sHypnoPose204
.4byte sHypnoPose205
.4byte sHypnoPose206
.4byte sHypnoPose207
.4byte sHypnoPose208
.4byte sHypnoPose209
.4byte sHypnoPose210
.4byte sHypnoPose211
.4byte sHypnoPose212
.4byte sHypnoPose213
.4byte sHypnoPose214
.4byte sHypnoPose215
.4byte sHypnoPose216
.4byte sHypnoPose217
.4byte sHypnoPose218
.4byte sHypnoPose219
.4byte sHypnoPose220
.4byte sHypnoPose221
.4byte sHypnoPose222
.4byte sHypnoPose223
.4byte sHypnoPose224
.4byte sHypnoPose225
.4byte sHypnoPose226
.4byte sHypnoPose227
.4byte sHypnoPose228
.4byte sHypnoPose229
.4byte sHypnoPose230
.4byte sHypnoPose231
.4byte sHypnoPose232
.4byte sHypnoPose233
.4byte sHypnoPose234
.4byte sHypnoPose235
.4byte sHypnoPose236
.4byte sHypnoPose237
.4byte sHypnoPose238
.4byte sHypnoPose239
.4byte sHypnoPose240
.4byte sHypnoPose241
.4byte sHypnoPose242
.4byte sHypnoPose243
.4byte sHypnoPose244
.4byte sHypnoPose245
.4byte sHypnoPose246
.4byte sHypnoPose247
.4byte sHypnoPose248
.4byte sHypnoPose249
.4byte sHypnoPose250
.4byte sHypnoPose251
.4byte sHypnoPose252
.4byte sHypnoPose253
.4byte sHypnoPose254
.4byte sHypnoPose255
.4byte sHypnoPose256
.4byte sHypnoPose257
.4byte sHypnoPose258
.4byte sHypnoPose259
.4byte sHypnoPose260
.4byte sHypnoPose261
.4byte sHypnoPose262
.4byte sHypnoPose263
.4byte sHypnoPose264
.4byte sHypnoPose265
.4byte sHypnoPose266
.4byte sHypnoPose267
.4byte sHypnoPose268
.4byte sHypnoPose269
.4byte sHypnoPose270
.4byte sHypnoPose271
.4byte sHypnoPose272
.4byte sHypnoPose273
.4byte sHypnoPose274
.4byte sHypnoPose275
.4byte sHypnoPose276
.4byte sHypnoPose277
.4byte sHypnoPose278
.4byte sHypnoPose279
.4byte sHypnoPose280
.4byte sHypnoPose281
.4byte sHypnoPose282
.4byte sHypnoPose283
.4byte sHypnoPose284
.4byte sHypnoPose285
.4byte sHypnoPose286
.4byte sHypnoPose287
.4byte sHypnoPose288
.4byte sHypnoPose289
.4byte sHypnoPose290
.4byte sHypnoPose291
.4byte sHypnoPose292
.4byte sHypnoPose293
.4byte sHypnoPose294
.4byte sHypnoPose295
.4byte sHypnoPose296
.4byte sHypnoPose297
.4byte sHypnoPose298
.4byte sHypnoPose299
.4byte sHypnoPose300
sAxPositionsHypno:
.2byte   -1,   -9, 	  -9,   -8, 	   8,  -16, 	  -1,  -11
.2byte   -1,   -8, 	  -8,   -5, 	  10,  -15, 	  -1,  -11
.2byte   -1,   -8, 	 -11,   -9, 	   6,  -15, 	  -1,  -10
.2byte    3,  -11, 	  -5,   -7, 	   8,  -18, 	   0,   -9
.2byte    3,  -10, 	  -2,   -5, 	   9,  -18, 	  -1,   -9
.2byte    3,  -10, 	  -8,   -7, 	   7,  -16, 	  -2,   -9
.2byte    7,  -12, 	   0,   -6, 	   9,  -18, 	  -2,   -9
.2byte    7,  -12, 	   2,   -6, 	   8,  -19, 	   1,   -8
.2byte    7,  -12, 	  -4,   -6, 	  10,  -15, 	  -1,   -9
.2byte    6,  -14, 	   7,   -6, 	  -3,  -19, 	  -2,   -9
.2byte    6,  -13, 	   8,   -8, 	  -5,  -20, 	  -3,   -9
.2byte    6,  -13, 	   2,   -5, 	  -2,  -17, 	  -2,  -10
.2byte   -1,  -18, 	   8,   -9, 	 -10,  -17, 	  -1,  -10
.2byte   -1,  -17, 	   6,   -8, 	 -12,  -16, 	   0,  -10
.2byte   -1,  -17, 	   9,   -8, 	  -8,  -16, 	   0,   -9
.2byte   -6,  -14, 	   2,  -11, 	 -11,  -15, 	  -1,  -10
.2byte   -7,  -13, 	   2,  -11, 	 -14,  -13, 	  -1,  -10
.2byte   -7,  -13, 	   4,  -10, 	 -10,  -14, 	   0,  -10
.2byte   -8,  -12, 	  -7,  -10, 	  -5,  -13, 	  -1,  -10
.2byte   -8,  -11, 	  -9,   -7, 	  -2,  -12, 	  -2,   -9
.2byte   -8,  -11, 	  -2,  -11, 	  -6,  -12, 	  -2,  -10
.2byte   -5,  -10, 	  -8,   -8, 	   5,  -14, 	  -1,   -9
.2byte   -6,   -9, 	 -10,   -6, 	   7,  -12, 	  -1,   -9
.2byte   -6,   -9, 	  -2,  -11, 	   3,  -14, 	  -2,   -9
.2byte   -1,   -9, 	  -9,   -8, 	   8,  -16, 	  -1,  -11
.2byte   -1,   -8, 	  -8,   -5, 	  10,  -15, 	  -1,  -11
.2byte   -1,   -8, 	 -11,   -9, 	   6,  -15, 	  -1,  -10
.2byte    3,  -11, 	  -5,   -7, 	   8,  -18, 	   0,   -9
.2byte    3,  -10, 	  -2,   -5, 	   9,  -18, 	  -1,   -9
.2byte    3,  -10, 	  -8,   -7, 	   7,  -16, 	  -2,   -9
.2byte    7,  -12, 	   0,   -6, 	   9,  -18, 	  -2,   -9
.2byte    7,  -12, 	   2,   -6, 	   8,  -19, 	   1,   -8
.2byte    7,  -12, 	  -4,   -6, 	  10,  -15, 	  -1,   -9
.2byte    6,  -14, 	   7,   -6, 	  -3,  -19, 	  -2,   -9
.2byte    6,  -13, 	   8,   -8, 	  -5,  -20, 	  -3,   -9
.2byte    6,  -13, 	   2,   -5, 	  -2,  -17, 	  -2,  -10
.2byte   -1,  -18, 	   8,   -9, 	 -10,  -17, 	  -1,  -10
.2byte   -1,  -17, 	   6,   -8, 	 -12,  -16, 	   0,  -10
.2byte   -1,  -17, 	   9,   -8, 	  -8,  -16, 	   0,   -9
.2byte   -6,  -14, 	   2,  -11, 	 -11,  -15, 	  -1,  -10
.2byte   -7,  -13, 	   2,  -11, 	 -14,  -13, 	  -1,  -10
.2byte   -7,  -13, 	   4,  -10, 	 -10,  -14, 	   0,  -10
.2byte   -8,  -12, 	  -7,  -10, 	  -5,  -13, 	  -1,  -10
.2byte   -8,  -11, 	  -9,   -7, 	  -2,  -12, 	  -2,   -9
.2byte   -8,  -11, 	  -2,  -11, 	  -6,  -12, 	  -2,  -10
.2byte   -5,  -10, 	  -8,   -8, 	   5,  -14, 	  -1,   -9
.2byte   -6,   -9, 	 -10,   -6, 	   7,  -12, 	  -1,   -9
.2byte   -6,   -9, 	  -2,  -11, 	   3,  -14, 	  -2,   -9
.2byte   -1,   -9, 	  -9,   -8, 	   8,  -16, 	  -1,  -11
.2byte   -1,   -8, 	  -8,   -5, 	  10,  -15, 	  -1,  -11
.2byte   -1,   -8, 	 -11,   -9, 	   6,  -15, 	  -1,  -10
.2byte   -3,  -11, 	  -8,   -9, 	   0,  -10, 	   0,   -9
.2byte    2,   -7, 	  -2,   -1, 	   9,  -11, 	   2,   -8
.2byte    2,   -7, 	  -2,   -1, 	   9,  -11, 	   2,   -8
.2byte    3,  -11, 	  -5,   -7, 	   8,  -18, 	   0,   -9
.2byte    3,  -10, 	  -2,   -5, 	   9,  -18, 	  -1,   -9
.2byte    3,  -10, 	  -8,   -7, 	   7,  -16, 	  -2,   -9
.2byte    0,  -11, 	 -12,  -16, 	   5,   -7, 	  -1,  -10
.2byte    5,   -6, 	   8,    0, 	  -2,   -9, 	   0,   -7
.2byte    5,   -6, 	   8,    0, 	  -2,   -9, 	   0,   -7
.2byte    7,  -12, 	   0,   -6, 	   9,  -18, 	  -2,   -9
.2byte    7,  -12, 	   2,   -6, 	   8,  -19, 	   1,   -8
.2byte    7,  -12, 	  -4,   -6, 	  10,  -15, 	  -1,   -9
.2byte    3,  -12, 	 -11,   -8, 	  11,  -14, 	  -1,  -10
.2byte    5,  -11, 	  10,  -10, 	 -11,   -9, 	   0,   -9
.2byte    5,  -11, 	  10,  -10, 	 -11,   -9, 	   0,   -9
.2byte    6,  -14, 	   7,   -6, 	  -3,  -19, 	  -2,   -9
.2byte    6,  -13, 	   8,   -8, 	  -5,  -20, 	  -3,   -9
.2byte    6,  -13, 	   2,   -5, 	  -2,  -17, 	  -2,  -10
.2byte    3,  -12, 	  -5,   -4, 	   7,  -17, 	  -2,  -10
.2byte    2,  -19, 	   6,  -19, 	 -11,  -11, 	  -2,  -12
.2byte    2,  -19, 	   6,  -19, 	 -11,  -11, 	  -2,  -12
.2byte   -1,  -18, 	   8,   -9, 	 -10,  -17, 	  -1,  -10
.2byte   -1,  -17, 	   6,   -8, 	 -12,  -16, 	   0,  -10
.2byte   -1,  -17, 	   9,   -8, 	  -8,  -16, 	   0,   -9
.2byte    5,  -11, 	   6,   -3, 	  -5,  -19, 	  -2,   -9
.2byte   -1,  -17, 	   0,  -25, 	 -10,   -6, 	  -1,   -9
.2byte   -1,  -17, 	   0,  -25, 	 -10,   -6, 	  -1,   -9
.2byte   -6,  -14, 	   2,  -11, 	 -11,  -15, 	  -1,  -10
.2byte   -7,  -13, 	   2,  -11, 	 -14,  -13, 	  -1,  -10
.2byte   -7,  -13, 	   4,  -10, 	 -10,  -14, 	   0,  -10
.2byte   -1,  -14, 	  10,   -6, 	  -6,  -17, 	   1,   -8
.2byte   -7,  -15, 	  -8,  -23, 	  -1,   -4, 	  -1,  -12
.2byte   -7,  -15, 	  -8,  -23, 	  -1,   -4, 	  -1,  -12
.2byte   -8,  -12, 	  -7,  -10, 	  -5,  -13, 	  -1,  -10
.2byte   -8,  -11, 	  -9,   -7, 	  -2,  -12, 	  -2,   -9
.2byte   -8,  -11, 	  -2,  -11, 	  -6,  -12, 	  -2,  -10
.2byte   -4,  -13, 	   9,   -9, 	  -8,  -11, 	   1,   -9
.2byte   -7,  -11, 	 -13,   -9, 	   9,   -6, 	  -1,   -8
.2byte   -7,  -11, 	 -13,   -9, 	   9,   -6, 	  -1,   -8
.2byte   -5,  -10, 	  -8,   -8, 	   5,  -14, 	  -1,   -9
.2byte   -6,   -9, 	 -10,   -6, 	   7,  -12, 	  -1,   -9
.2byte   -6,   -9, 	  -2,  -11, 	   3,  -14, 	  -2,   -9
.2byte   -5,  -10, 	  -1,   -8, 	  -5,   -8, 	   0,   -8
.2byte   -6,   -2, 	 -12,    0, 	   7,   -5, 	  -2,   -5
.2byte   -6,   -2, 	 -12,    0, 	   7,   -5, 	  -2,   -5
.2byte   -1,   -9, 	  -9,   -8, 	   8,  -16, 	  -1,  -11
.2byte   -1,   -8, 	  -8,   -5, 	  10,  -15, 	  -1,  -11
.2byte   -1,   -8, 	 -11,   -9, 	   6,  -15, 	  -1,  -10
.2byte   -3,  -11, 	  -8,   -9, 	   0,  -10, 	   0,   -9
.2byte   -1,   -7, 	 -12,   -6, 	   9,   -9, 	  -1,  -10
.2byte   -1,   -5, 	  -7,   -6, 	   9,  -10, 	  -1,   -8
.2byte   -3,  -11, 	  -8,   -9, 	   0,  -10, 	   0,   -9
.2byte   -1,   -5, 	  -7,   -6, 	   9,  -10, 	  -1,   -8
.2byte   -1,   -5, 	  -7,   -6, 	   9,  -10, 	  -1,   -8
.2byte    3,  -11, 	  -5,   -7, 	   8,  -18, 	   0,   -9
.2byte    3,  -10, 	  -2,   -5, 	   9,  -18, 	  -1,   -9
.2byte    3,  -10, 	  -8,   -7, 	   7,  -16, 	  -2,   -9
.2byte    0,  -11, 	 -12,  -16, 	   5,   -7, 	  -1,  -10
.2byte    5,   -6, 	  -2,   -4, 	  11,   -9, 	   2,   -7
.2byte    4,   -8, 	   1,   -5, 	  11,  -11, 	   0,   -9
.2byte    0,  -11, 	 -12,  -16, 	   5,   -7, 	  -1,  -10
.2byte    4,   -8, 	   1,   -5, 	  11,  -11, 	   0,   -9
.2byte    4,   -8, 	   1,   -5, 	  11,  -11, 	   0,   -9
.2byte    7,  -12, 	   0,   -6, 	   9,  -18, 	  -2,   -9
.2byte    7,  -12, 	   2,   -6, 	   8,  -19, 	   1,   -8
.2byte    7,  -12, 	  -4,   -6, 	  10,  -15, 	  -1,   -9
.2byte    3,  -12, 	 -11,   -8, 	  11,  -14, 	  -1,  -10
.2byte    8,   -7, 	   6,   -7, 	  12,  -11, 	   1,   -8
.2byte    6,  -10, 	   8,   -9, 	  12,  -15, 	   1,  -10
.2byte    3,  -12, 	 -11,   -8, 	  11,  -14, 	  -1,  -10
.2byte    6,  -10, 	   8,   -9, 	  12,  -15, 	   1,  -10
.2byte    6,  -10, 	   8,   -9, 	  12,  -15, 	   1,  -10
.2byte    6,  -14, 	   7,   -6, 	  -3,  -19, 	  -2,   -9
.2byte    6,  -13, 	   8,   -8, 	  -5,  -20, 	  -3,   -9
.2byte    6,  -13, 	   2,   -5, 	  -2,  -17, 	  -2,  -10
.2byte    3,  -12, 	  -5,   -4, 	   7,  -17, 	  -2,  -10
.2byte    6,  -11, 	  13,  -11, 	   7,  -12, 	   0,   -9
.2byte    5,  -12, 	  12,  -12, 	   6,  -14, 	  -1,   -9
.2byte    3,  -12, 	  -5,   -4, 	   7,  -17, 	  -2,  -10
.2byte    5,  -12, 	  12,  -12, 	   6,  -14, 	  -1,   -9
.2byte    5,  -12, 	  12,  -12, 	   6,  -14, 	  -1,   -9
.2byte   -1,  -18, 	   8,   -9, 	 -10,  -17, 	  -1,  -10
.2byte   -1,  -17, 	   6,   -8, 	 -12,  -16, 	   0,  -10
.2byte   -1,  -17, 	   9,   -8, 	  -8,  -16, 	   0,   -9
.2byte    5,  -12, 	   6,   -4, 	  -5,  -20, 	  -2,  -10
.2byte   -1,  -15, 	   7,  -17, 	 -10,  -13, 	  -1,  -10
.2byte   -1,  -13, 	   5,  -14, 	 -11,  -12, 	  -1,  -10
.2byte    5,  -12, 	   6,   -4, 	  -5,  -20, 	  -2,  -10
.2byte   -1,  -13, 	   5,  -14, 	 -11,  -12, 	  -1,  -10
.2byte   -1,  -13, 	   5,  -14, 	 -11,  -12, 	  -1,  -10
.2byte   -6,  -14, 	   2,  -11, 	 -11,  -15, 	  -1,  -10
.2byte   -7,  -13, 	   2,  -11, 	 -14,  -13, 	  -1,  -10
.2byte   -7,  -13, 	   4,  -10, 	 -10,  -14, 	   0,  -10
.2byte    0,  -13, 	  11,   -5, 	  -5,  -16, 	   2,   -7
.2byte   -8,  -12, 	  -4,  -17, 	 -13,  -11, 	  -1,  -10
.2byte   -9,  -12, 	  -5,  -17, 	 -15,   -9, 	  -1,   -9
.2byte    0,  -13, 	  11,   -5, 	  -5,  -16, 	   2,   -7
.2byte   -9,  -12, 	  -5,  -17, 	 -15,   -9, 	  -1,   -9
.2byte   -9,  -12, 	  -5,  -17, 	 -15,   -9, 	  -1,   -9
.2byte   -8,  -12, 	  -7,  -10, 	  -5,  -13, 	  -1,  -10
.2byte   -8,  -11, 	  -9,   -7, 	  -2,  -12, 	  -2,   -9
.2byte   -8,  -11, 	  -2,  -11, 	  -6,  -12, 	  -2,  -10
.2byte   -4,  -13, 	   9,   -9, 	  -8,  -11, 	   1,   -9
.2byte  -10,  -10, 	 -14,  -14, 	  -8,   -9, 	  -3,   -9
.2byte  -10,   -8, 	 -15,   -8, 	  -7,   -7, 	  -3,   -8
.2byte   -4,  -13, 	   9,   -9, 	  -8,  -11, 	   1,   -9
.2byte  -10,   -8, 	 -15,   -8, 	  -7,   -7, 	  -3,   -8
.2byte  -10,   -8, 	 -15,   -8, 	  -7,   -7, 	  -3,   -8
.2byte   -5,  -10, 	  -8,   -8, 	   5,  -14, 	  -1,   -9
.2byte   -6,   -9, 	 -10,   -6, 	   7,  -12, 	  -1,   -9
.2byte   -6,   -9, 	  -2,  -11, 	   3,  -14, 	  -2,   -9
.2byte   -5,  -10, 	  -1,   -8, 	  -5,   -8, 	   0,   -8
.2byte   -7,   -8, 	 -15,   -9, 	   2,   -8, 	  -2,   -9
.2byte   -7,   -6, 	 -13,   -6, 	   3,   -8, 	  -3,   -8
.2byte   -5,  -10, 	  -1,   -8, 	  -5,   -8, 	   0,   -8
.2byte   -7,   -6, 	 -13,   -6, 	   3,   -8, 	  -3,   -8
.2byte   -7,   -6, 	 -13,   -6, 	   3,   -8, 	  -3,   -8
.2byte   -1,   -7, 	 -12,   -6, 	   9,   -9, 	  -1,  -10
.2byte   -1,   -7, 	 -12,   -6, 	   9,   -9, 	  -1,  -10
.2byte   -1,   -5, 	  -7,   -6, 	   9,  -10, 	  -1,   -8
.2byte   -1,   -5, 	  -7,   -6, 	   9,  -10, 	  -1,   -8
.2byte   -1,   -5, 	  -7,   -6, 	   9,  -10, 	  -1,   -8
.2byte    5,   -6, 	  -2,   -4, 	  11,   -9, 	   2,   -7
.2byte    5,   -6, 	  -2,   -4, 	  11,   -9, 	   2,   -7
.2byte    4,   -8, 	   1,   -5, 	  11,  -11, 	   0,   -9
.2byte    4,   -8, 	   1,   -5, 	  11,  -11, 	   0,   -9
.2byte    4,   -8, 	   1,   -5, 	  11,  -11, 	   0,   -9
.2byte    8,   -7, 	   6,   -7, 	  12,  -11, 	   1,   -8
.2byte    8,   -7, 	   6,   -7, 	  12,  -11, 	   1,   -8
.2byte    6,  -10, 	   8,   -9, 	  12,  -15, 	   1,  -10
.2byte    6,  -10, 	   8,   -9, 	  12,  -15, 	   1,  -10
.2byte    6,  -10, 	   8,   -9, 	  12,  -15, 	   1,  -10
.2byte    6,  -11, 	  13,  -11, 	   7,  -12, 	   0,   -9
.2byte    6,  -11, 	  13,  -11, 	   7,  -12, 	   0,   -9
.2byte    5,  -12, 	  12,  -12, 	   6,  -14, 	  -1,   -9
.2byte    5,  -12, 	  12,  -12, 	   6,  -14, 	  -1,   -9
.2byte    5,  -12, 	  12,  -12, 	   6,  -14, 	  -1,   -9
.2byte   -1,  -15, 	   7,  -17, 	 -10,  -13, 	  -1,  -10
.2byte   -1,  -15, 	   7,  -17, 	 -10,  -13, 	  -1,  -10
.2byte   -1,  -13, 	   5,  -14, 	 -11,  -12, 	  -1,  -10
.2byte   -1,  -13, 	   5,  -14, 	 -11,  -12, 	  -1,  -10
.2byte   -1,  -13, 	   5,  -14, 	 -11,  -12, 	  -1,  -10
.2byte   -8,  -12, 	  -4,  -17, 	 -13,  -11, 	  -1,  -10
.2byte   -8,  -12, 	  -4,  -17, 	 -13,  -11, 	  -1,  -10
.2byte   -9,  -12, 	  -5,  -17, 	 -15,   -9, 	  -1,   -9
.2byte   -9,  -12, 	  -5,  -17, 	 -15,   -9, 	  -1,   -9
.2byte   -9,  -12, 	  -5,  -17, 	 -15,   -9, 	  -1,   -9
.2byte  -10,  -10, 	 -14,  -14, 	  -8,   -9, 	  -3,   -9
.2byte  -10,  -10, 	 -14,  -14, 	  -8,   -9, 	  -3,   -9
.2byte  -10,   -8, 	 -15,   -8, 	  -7,   -7, 	  -3,   -8
.2byte  -10,   -8, 	 -15,   -8, 	  -7,   -7, 	  -3,   -8
.2byte  -10,   -8, 	 -15,   -8, 	  -7,   -7, 	  -3,   -8
.2byte   -7,   -8, 	 -15,   -9, 	   2,   -8, 	  -2,   -9
.2byte   -7,   -8, 	 -15,   -9, 	   2,   -8, 	  -2,   -9
.2byte   -7,   -6, 	 -13,   -6, 	   3,   -8, 	  -3,   -8
.2byte   -7,   -6, 	 -13,   -6, 	   3,   -8, 	  -3,   -8
.2byte   -7,   -6, 	 -13,   -6, 	   3,   -8, 	  -3,   -8
.2byte    3,   -6, 	  -5,   -3, 	  10,   -3, 	   3,   -5
.2byte    3,   -4, 	  -5,   -3, 	  11,   -3, 	   3,   -6
.2byte    3,  -18, 	 -11,  -22, 	  12,  -20, 	   0,  -13
.2byte   -2,  -18, 	   6,  -25, 	 -12,  -19, 	  -2,  -13
.2byte    0,  -19, 	   2,  -23, 	 -13,  -17, 	  -2,  -13
.2byte    2,  -16, 	 -11,  -20, 	   6,  -15, 	  -2,  -12
.2byte   -5,  -16, 	  11,  -18, 	 -12,  -18, 	   0,   -9
.2byte   -4,  -16, 	   9,  -20, 	  -8,  -15, 	   0,  -12
.2byte    0,  -19, 	  -2,  -23, 	  13,  -17, 	   2,  -13
.2byte    1,  -18, 	  -7,  -25, 	  11,  -19, 	   1,  -13
.2byte   -1,   -9, 	  -9,   -8, 	   8,  -16, 	  -1,  -11
.2byte   -1,   -8, 	  -8,   -5, 	  10,  -15, 	  -1,  -11
.2byte   -1,   -8, 	 -11,   -9, 	   6,  -15, 	  -1,  -10
.2byte    3,  -11, 	  -5,   -7, 	   8,  -18, 	   0,   -9
.2byte    3,  -10, 	  -2,   -5, 	   9,  -18, 	  -1,   -9
.2byte    3,  -10, 	  -8,   -7, 	   7,  -16, 	  -2,   -9
.2byte    7,  -12, 	   0,   -6, 	   9,  -18, 	  -2,   -9
.2byte    7,  -12, 	   2,   -6, 	   8,  -19, 	   1,   -8
.2byte    7,  -12, 	  -4,   -6, 	  10,  -15, 	  -1,   -9
.2byte    6,  -14, 	   7,   -6, 	  -3,  -19, 	  -2,   -9
.2byte    6,  -13, 	   8,   -8, 	  -5,  -20, 	  -3,   -9
.2byte    6,  -13, 	   2,   -5, 	  -2,  -17, 	  -2,  -10
.2byte   -1,  -18, 	   8,   -9, 	 -10,  -17, 	  -1,  -10
.2byte   -1,  -17, 	   6,   -8, 	 -12,  -16, 	   0,  -10
.2byte   -1,  -17, 	   9,   -8, 	  -8,  -16, 	   0,   -9
.2byte   -6,  -14, 	   2,  -11, 	 -11,  -15, 	  -1,  -10
.2byte   -7,  -13, 	   2,  -11, 	 -14,  -13, 	  -1,  -10
.2byte   -7,  -13, 	   4,  -10, 	 -10,  -14, 	   0,  -10
.2byte   -8,  -12, 	  -7,  -10, 	  -5,  -13, 	  -1,  -10
.2byte   -8,  -11, 	  -9,   -7, 	  -2,  -12, 	  -2,   -9
.2byte   -8,  -11, 	  -2,  -11, 	  -6,  -12, 	  -2,  -10
.2byte   -5,  -10, 	  -8,   -8, 	   5,  -14, 	  -1,   -9
.2byte   -6,   -9, 	 -10,   -6, 	   7,  -12, 	  -1,   -9
.2byte   -6,   -9, 	  -2,  -11, 	   3,  -14, 	  -2,   -9
.2byte   -1,   -7, 	 -12,   -6, 	   9,   -9, 	  -1,  -10
.2byte   -7,   -8, 	 -15,   -9, 	   2,   -8, 	  -2,   -9
.2byte  -10,  -10, 	 -14,  -14, 	  -8,   -9, 	  -3,   -9
.2byte   -8,  -12, 	  -4,  -17, 	 -13,  -11, 	  -1,  -10
.2byte   -1,  -15, 	   7,  -17, 	 -10,  -13, 	  -1,  -10
.2byte    6,  -11, 	  13,  -11, 	   7,  -12, 	   0,   -9
.2byte    8,   -7, 	   6,   -7, 	  12,  -11, 	   1,   -8
.2byte    5,   -6, 	  -2,   -4, 	  11,   -9, 	   2,   -7
.2byte   -1,   -7, 	 -12,   -6, 	   9,   -9, 	  -1,  -10
.2byte    5,   -6, 	  -2,   -4, 	  11,   -9, 	   2,   -7
.2byte    8,   -7, 	   6,   -7, 	  12,  -11, 	   1,   -8
.2byte    6,  -11, 	  13,  -11, 	   7,  -12, 	   0,   -9
.2byte   -1,  -15, 	   7,  -17, 	 -10,  -13, 	  -1,  -10
.2byte   -8,  -12, 	  -4,  -17, 	 -13,  -11, 	  -1,  -10
.2byte  -10,  -10, 	 -14,  -14, 	  -8,   -9, 	  -3,   -9
.2byte   -7,   -8, 	 -15,   -9, 	   2,   -8, 	  -2,   -9
.2byte   -1,   -7, 	 -12,   -6, 	   9,   -9, 	  -1,  -10
.2byte   -1,   -9, 	  -9,   -8, 	   8,  -16, 	  -1,  -11
.2byte   -3,  -11, 	  -8,   -9, 	   0,  -10, 	   0,   -9
.2byte   -1,   -5, 	  -7,   -6, 	   9,  -10, 	  -1,   -8
.2byte    3,  -11, 	  -5,   -7, 	   8,  -18, 	   0,   -9
.2byte    0,  -11, 	 -12,  -16, 	   5,   -7, 	  -1,  -10
.2byte    4,   -8, 	   1,   -5, 	  11,  -11, 	   0,   -9
.2byte    7,  -12, 	   0,   -6, 	   9,  -18, 	  -2,   -9
.2byte    3,  -12, 	 -11,   -8, 	  11,  -14, 	  -1,  -10
.2byte    5,  -10, 	   7,   -9, 	  11,  -15, 	   0,  -10
.2byte    6,  -14, 	   7,   -6, 	  -3,  -19, 	  -2,   -9
.2byte    3,  -12, 	  -5,   -4, 	   7,  -17, 	  -2,  -10
.2byte    4,  -12, 	  11,  -12, 	   5,  -14, 	  -2,   -9
.2byte   -1,  -18, 	   8,   -9, 	 -10,  -17, 	  -1,  -10
.2byte    5,  -10, 	   6,   -2, 	  -5,  -18, 	  -2,   -8
.2byte   -1,  -13, 	   5,  -14, 	 -11,  -12, 	  -1,  -10
.2byte   -6,  -14, 	   2,  -11, 	 -11,  -15, 	  -1,  -10
.2byte   -1,  -14, 	  10,   -6, 	  -6,  -17, 	   1,   -8
.2byte   -9,  -13, 	  -5,  -18, 	 -15,  -10, 	  -1,  -10
.2byte   -8,  -12, 	  -7,  -10, 	  -5,  -13, 	  -1,  -10
.2byte   -4,  -13, 	   9,   -9, 	  -8,  -11, 	   1,   -9
.2byte   -8,   -8, 	 -13,   -8, 	  -5,   -7, 	  -1,   -8
.2byte   -5,  -10, 	  -8,   -8, 	   5,  -14, 	  -1,   -9
.2byte   -5,  -10, 	  -1,   -8, 	  -5,   -8, 	   0,   -8
.2byte   -7,   -6, 	 -13,   -6, 	   3,   -8, 	  -3,   -8
.2byte   -1,   -7, 	 -12,   -6, 	   9,   -9, 	  -1,  -10
.2byte   -7,   -8, 	 -15,   -9, 	   2,   -8, 	  -2,   -9
.2byte  -10,  -10, 	 -14,  -14, 	  -8,   -9, 	  -3,   -9
.2byte   -8,  -12, 	  -4,  -17, 	 -13,  -11, 	  -1,  -10
.2byte   -1,  -15, 	   7,  -17, 	 -10,  -13, 	  -1,  -10
.2byte    6,  -11, 	  13,  -11, 	   7,  -12, 	   0,   -9
.2byte    8,   -7, 	   6,   -7, 	  12,  -11, 	   1,   -8
.2byte    5,   -6, 	  -2,   -4, 	  11,   -9, 	   2,   -7
.2byte   -1,   -7, 	 -12,   -6, 	   9,   -9, 	  -1,  -10
.2byte   -1,   -9, 	  -9,   -8, 	   8,  -16, 	  -1,  -11
.2byte   -5,  -10, 	  -8,   -8, 	   5,  -14, 	  -1,   -9
.2byte   -8,  -12, 	  -7,  -10, 	  -5,  -13, 	  -1,  -10
.2byte   -6,  -14, 	   2,  -11, 	 -11,  -15, 	  -1,  -10
.2byte   -1,  -18, 	   8,   -9, 	 -10,  -17, 	  -1,  -10
.2byte    6,  -14, 	   7,   -6, 	  -3,  -19, 	  -2,   -9
.2byte    7,  -12, 	   0,   -6, 	   9,  -18, 	  -2,   -9
.2byte    3,  -11, 	  -5,   -7, 	   8,  -18, 	   0,   -9
sHypnoAnimTable1:
.4byte sHypnoAnims_1_1
.4byte sHypnoAnims_1_2
.4byte sHypnoAnims_1_3
.4byte sHypnoAnims_1_4
.4byte sHypnoAnims_1_5
.4byte sHypnoAnims_1_6
.4byte sHypnoAnims_1_7
.4byte sHypnoAnims_1_8
sHypnoAnimTable2:
.4byte sHypnoAnims_2_1
.4byte sHypnoAnims_2_2
.4byte sHypnoAnims_2_3
.4byte sHypnoAnims_2_4
.4byte sHypnoAnims_2_5
.4byte sHypnoAnims_2_6
.4byte sHypnoAnims_2_7
.4byte sHypnoAnims_2_8
sHypnoAnimTable3:
.4byte sHypnoAnims_3_1
.4byte sHypnoAnims_3_2
.4byte sHypnoAnims_3_3
.4byte sHypnoAnims_3_4
.4byte sHypnoAnims_3_5
.4byte sHypnoAnims_3_6
.4byte sHypnoAnims_3_7
.4byte sHypnoAnims_3_8
sHypnoAnimTable4:
.4byte sHypnoAnims_4_1
.4byte sHypnoAnims_4_2
.4byte sHypnoAnims_4_3
.4byte sHypnoAnims_4_4
.4byte sHypnoAnims_4_5
.4byte sHypnoAnims_4_6
.4byte sHypnoAnims_4_7
.4byte sHypnoAnims_4_8
sHypnoAnimTable5:
.4byte sHypnoAnims_5_1
.4byte sHypnoAnims_5_2
.4byte sHypnoAnims_5_3
.4byte sHypnoAnims_5_4
.4byte sHypnoAnims_5_5
.4byte sHypnoAnims_5_6
.4byte sHypnoAnims_5_7
.4byte sHypnoAnims_5_8
sHypnoAnimTable6:
.4byte sHypnoAnims_6_1
.4byte sHypnoAnims_6_1
.4byte sHypnoAnims_6_1
.4byte sHypnoAnims_6_1
.4byte sHypnoAnims_6_1
.4byte sHypnoAnims_6_1
.4byte sHypnoAnims_6_1
.4byte sHypnoAnims_6_1
sHypnoAnimTable7:
.4byte sHypnoAnims_7_1
.4byte sHypnoAnims_7_2
.4byte sHypnoAnims_7_3
.4byte sHypnoAnims_7_4
.4byte sHypnoAnims_7_5
.4byte sHypnoAnims_7_6
.4byte sHypnoAnims_7_7
.4byte sHypnoAnims_7_8
sHypnoAnimTable8:
.4byte sHypnoAnims_8_1
.4byte sHypnoAnims_8_2
.4byte sHypnoAnims_8_3
.4byte sHypnoAnims_8_4
.4byte sHypnoAnims_8_5
.4byte sHypnoAnims_8_6
.4byte sHypnoAnims_8_7
.4byte sHypnoAnims_8_8
sHypnoAnimTable9:
.4byte sHypnoAnims_9_1
.4byte sHypnoAnims_9_2
.4byte sHypnoAnims_9_3
.4byte sHypnoAnims_9_4
.4byte sHypnoAnims_9_5
.4byte sHypnoAnims_9_6
.4byte sHypnoAnims_9_7
.4byte sHypnoAnims_9_8
sHypnoAnimTable10:
.4byte sHypnoAnims_10_1
.4byte sHypnoAnims_10_2
.4byte sHypnoAnims_10_3
.4byte sHypnoAnims_10_4
.4byte sHypnoAnims_10_5
.4byte sHypnoAnims_10_6
.4byte sHypnoAnims_10_7
.4byte sHypnoAnims_10_8
sHypnoAnimTable11:
.4byte sHypnoAnims_11_1
.4byte sHypnoAnims_11_2
.4byte sHypnoAnims_11_3
.4byte sHypnoAnims_11_4
.4byte sHypnoAnims_11_5
.4byte sHypnoAnims_11_6
.4byte sHypnoAnims_11_7
.4byte sHypnoAnims_11_8
sHypnoAnimTable12:
.4byte sHypnoAnims_12_1
.4byte sHypnoAnims_12_2
.4byte sHypnoAnims_12_3
.4byte sHypnoAnims_12_4
.4byte sHypnoAnims_12_5
.4byte sHypnoAnims_12_6
.4byte sHypnoAnims_12_7
.4byte sHypnoAnims_12_8
sHypnoAnimTable13:
.4byte sHypnoAnims_13_1
.4byte sHypnoAnims_13_2
.4byte sHypnoAnims_13_3
.4byte sHypnoAnims_13_4
.4byte sHypnoAnims_13_5
.4byte sHypnoAnims_13_6
.4byte sHypnoAnims_13_7
.4byte sHypnoAnims_13_8
sAxAnimationsHypno:
.4byte sHypnoAnimTable1
.4byte sHypnoAnimTable2
.4byte sHypnoAnimTable3
.4byte sHypnoAnimTable4
.4byte sHypnoAnimTable5
.4byte sHypnoAnimTable6
.4byte sHypnoAnimTable7
.4byte sHypnoAnimTable8
.4byte sHypnoAnimTable9
.4byte sHypnoAnimTable10
.4byte sHypnoAnimTable11
.4byte sHypnoAnimTable12
.4byte sHypnoAnimTable13
sAxSpritesHypno:
.4byte sHypnoSprites1
.4byte sHypnoSprites2
.4byte sHypnoSprites3
.4byte sHypnoSprites4
.4byte sHypnoSprites5
.4byte sHypnoSprites6
.4byte sHypnoSprites7
.4byte sHypnoSprites8
.4byte sHypnoSprites9
.4byte sHypnoSprites10
.4byte sHypnoSprites11
.4byte sHypnoSprites12
.4byte sHypnoSprites13
.4byte sHypnoSprites14
.4byte sHypnoSprites15
.4byte sHypnoSprites16
.4byte sHypnoSprites17
.4byte sHypnoSprites18
.4byte sHypnoSprites19
.4byte sHypnoSprites20
.4byte sHypnoSprites21
.4byte sHypnoSprites22
.4byte sHypnoSprites23
.4byte sHypnoSprites24
.4byte sHypnoSprites25
.4byte sHypnoSprites26
.4byte sHypnoSprites27
.4byte sHypnoSprites28
.4byte sHypnoSprites29
.4byte sHypnoSprites30
.4byte sHypnoSprites31
.4byte sHypnoSprites32
.4byte sHypnoSprites33
.4byte sHypnoSprites34
.4byte sHypnoSprites35
.4byte sHypnoSprites36
.4byte sHypnoSprites37
.4byte sHypnoSprites38
.4byte sHypnoSprites39
.4byte sHypnoSprites40
.4byte sHypnoSprites41
.4byte sHypnoSprites42
.4byte sHypnoSprites43
.4byte sHypnoSprites44
.4byte sHypnoSprites45
.4byte sHypnoSprites46
.4byte sHypnoSprites47
.4byte sHypnoSprites48
.4byte sHypnoSprites49
.4byte sHypnoSprites50
.4byte sHypnoSprites51
.4byte sHypnoSprites52
.4byte sHypnoSprites53
.4byte sHypnoSprites54
.4byte sHypnoSprites55
.4byte sHypnoSprites56
.4byte sHypnoSprites57
.4byte sHypnoSprites58
.4byte sHypnoSprites59
.4byte sHypnoSprites60
.4byte sHypnoSprites61
.4byte sHypnoSprites62
.4byte sHypnoSprites63
.4byte sHypnoSprites64
.4byte sHypnoSprites65
.4byte sHypnoSprites66
.4byte sHypnoSprites67
.4byte sHypnoSprites68
.4byte sHypnoSprites69
.4byte sHypnoSprites70
.4byte sHypnoSprites71
.4byte sHypnoSprites72
.4byte sHypnoSprites73
sAxMainHypno:
ax_main sAxPosesHypno, sAxAnimationsHypno, 13, sAxSpritesHypno, sAxPositionsHypno
