.global gAxIgglybuff
gAxIgglybuff:
ax_siro sAxMainIgglybuff
sIgglybuffPose1:
ax_pose 0, 0x01f2, 0x40f8, 0x1c00
ax_pose_terminator
sIgglybuffPose2:
ax_pose 1, 0x81ee, 0x80f8, 0x1c00
ax_pose_terminator
sIgglybuffPose3:
ax_pose 2, 0x01f4, 0x40f8, 0x1c00
ax_pose_terminator
sIgglybuffPose4:
ax_pose 3, 0x01f2, 0x50f7, 0x1c00
ax_pose_terminator
sIgglybuffPose5:
ax_pose 4, 0x81ee, 0x90f7, 0x1c00
ax_pose_terminator
sIgglybuffPose6:
ax_pose 5, 0x01f4, 0x50f7, 0x1c00
ax_pose_terminator
sIgglybuffPose7:
ax_pose 6, 0x01f2, 0x50f7, 0x1c00
ax_pose_terminator
sIgglybuffPose8:
ax_pose 7, 0x81ed, 0x90f7, 0x1c00
ax_pose_terminator
sIgglybuffPose9:
ax_pose 8, 0x01f3, 0x50f7, 0x1c00
ax_pose_terminator
sIgglybuffPose10:
ax_pose 9, 0x01f2, 0x50f7, 0x1c00
ax_pose_terminator
sIgglybuffPose11:
ax_pose 10, 0x81ef, 0x90f7, 0x1c00
ax_pose_terminator
sIgglybuffPose12:
ax_pose 11, 0x01f4, 0x50f7, 0x1c00
ax_pose_terminator
sIgglybuffPose13:
ax_pose 12, 0x01f2, 0x40f8, 0x1c00
ax_pose_terminator
sIgglybuffPose14:
ax_pose 13, 0x81ef, 0x80f8, 0x1c00
ax_pose_terminator
sIgglybuffPose15:
ax_pose 14, 0x01f4, 0x40f8, 0x1c00
ax_pose_terminator
sIgglybuffPose16:
ax_pose 9, 0x01f2, 0x40f8, 0x1c00
ax_pose_terminator
sIgglybuffPose17:
ax_pose 10, 0x81ef, 0x80f8, 0x1c00
ax_pose_terminator
sIgglybuffPose18:
ax_pose 11, 0x01f4, 0x40f8, 0x1c00
ax_pose_terminator
sIgglybuffPose19:
ax_pose 6, 0x01f2, 0x40f8, 0x1c00
ax_pose_terminator
sIgglybuffPose20:
ax_pose 7, 0x81ed, 0x80f8, 0x1c00
ax_pose_terminator
sIgglybuffPose21:
ax_pose 8, 0x01f3, 0x40f8, 0x1c00
ax_pose_terminator
sIgglybuffPose22:
ax_pose 3, 0x01f2, 0x40f8, 0x1c00
ax_pose_terminator
sIgglybuffPose23:
ax_pose 4, 0x81ee, 0x80f8, 0x1c00
ax_pose_terminator
sIgglybuffPose24:
ax_pose 5, 0x01f4, 0x40f8, 0x1c00
ax_pose_terminator
sIgglybuffPose25:
ax_pose 15, 0x01f2, 0x40f8, 0x1c00
ax_pose_terminator
sIgglybuffPose26:
ax_pose 1, 0x81ee, 0x80f8, 0x1c00
ax_pose_terminator
sIgglybuffPose27:
ax_pose 2, 0x01f4, 0x40f8, 0x1c00
ax_pose_terminator
sIgglybuffPose28:
ax_pose 16, 0x01f3, 0x50f7, 0x1c00
ax_pose_terminator
sIgglybuffPose29:
ax_pose 4, 0x81ee, 0x90f7, 0x1c00
ax_pose_terminator
sIgglybuffPose30:
ax_pose 5, 0x01f4, 0x50f7, 0x1c00
ax_pose_terminator
sIgglybuffPose31:
ax_pose 17, 0x01f3, 0x50f7, 0x1c00
ax_pose_terminator
sIgglybuffPose32:
ax_pose 7, 0x81ed, 0x90f7, 0x1c00
ax_pose_terminator
sIgglybuffPose33:
ax_pose 8, 0x01f3, 0x50f7, 0x1c00
ax_pose_terminator
sIgglybuffPose34:
ax_pose 18, 0x01f3, 0x50f7, 0x1c00
ax_pose_terminator
sIgglybuffPose35:
ax_pose 10, 0x81ef, 0x90f7, 0x1c00
ax_pose_terminator
sIgglybuffPose36:
ax_pose 11, 0x01f4, 0x50f7, 0x1c00
ax_pose_terminator
sIgglybuffPose37:
ax_pose 19, 0x01f3, 0x40f8, 0x1c00
ax_pose_terminator
sIgglybuffPose38:
ax_pose 13, 0x81ef, 0x80f8, 0x1c00
ax_pose_terminator
sIgglybuffPose39:
ax_pose 14, 0x01f4, 0x40f8, 0x1c00
ax_pose_terminator
sIgglybuffPose40:
ax_pose 18, 0x01f3, 0x40f8, 0x1c00
ax_pose_terminator
sIgglybuffPose41:
ax_pose 10, 0x81ef, 0x80f8, 0x1c00
ax_pose_terminator
sIgglybuffPose42:
ax_pose 11, 0x01f4, 0x40f8, 0x1c00
ax_pose_terminator
sIgglybuffPose43:
ax_pose 17, 0x01f3, 0x40f8, 0x1c00
ax_pose_terminator
sIgglybuffPose44:
ax_pose 7, 0x81ed, 0x80f8, 0x1c00
ax_pose_terminator
sIgglybuffPose45:
ax_pose 8, 0x01f3, 0x40f8, 0x1c00
ax_pose_terminator
sIgglybuffPose46:
ax_pose 16, 0x01f3, 0x40f8, 0x1c00
ax_pose_terminator
sIgglybuffPose47:
ax_pose 4, 0x81ee, 0x80f8, 0x1c00
ax_pose_terminator
sIgglybuffPose48:
ax_pose 5, 0x01f4, 0x40f8, 0x1c00
ax_pose_terminator
sIgglybuffPose49:
ax_pose 15, 0x01f2, 0x40f8, 0x1c00
ax_pose_terminator
sIgglybuffPose50:
ax_pose 1, 0x81ee, 0x80f8, 0x1c00
ax_pose_terminator
sIgglybuffPose51:
ax_pose 2, 0x01f4, 0x40f8, 0x1c00
ax_pose_terminator
sIgglybuffPose52:
ax_pose 16, 0x01f3, 0x50f7, 0x1c00
ax_pose_terminator
sIgglybuffPose53:
ax_pose 4, 0x81ee, 0x90f7, 0x1c00
ax_pose_terminator
sIgglybuffPose54:
ax_pose 5, 0x01f4, 0x50f7, 0x1c00
ax_pose_terminator
sIgglybuffPose55:
ax_pose 17, 0x01f3, 0x50f7, 0x1c00
ax_pose_terminator
sIgglybuffPose56:
ax_pose 7, 0x81ed, 0x90f7, 0x1c00
ax_pose_terminator
sIgglybuffPose57:
ax_pose 8, 0x01f3, 0x50f7, 0x1c00
ax_pose_terminator
sIgglybuffPose58:
ax_pose 18, 0x01f3, 0x50f7, 0x1c00
ax_pose_terminator
sIgglybuffPose59:
ax_pose 10, 0x81ef, 0x90f7, 0x1c00
ax_pose_terminator
sIgglybuffPose60:
ax_pose 11, 0x01f4, 0x50f7, 0x1c00
ax_pose_terminator
sIgglybuffPose61:
ax_pose 19, 0x01f3, 0x40f8, 0x1c00
ax_pose_terminator
sIgglybuffPose62:
ax_pose 13, 0x81ef, 0x80f8, 0x1c00
ax_pose_terminator
sIgglybuffPose63:
ax_pose 14, 0x01f4, 0x40f8, 0x1c00
ax_pose_terminator
sIgglybuffPose64:
ax_pose 18, 0x01f3, 0x40f8, 0x1c00
ax_pose_terminator
sIgglybuffPose65:
ax_pose 10, 0x81ef, 0x80f8, 0x1c00
ax_pose_terminator
sIgglybuffPose66:
ax_pose 11, 0x01f4, 0x40f8, 0x1c00
ax_pose_terminator
sIgglybuffPose67:
ax_pose 17, 0x01f3, 0x40f8, 0x1c00
ax_pose_terminator
sIgglybuffPose68:
ax_pose 7, 0x81ed, 0x80f8, 0x1c00
ax_pose_terminator
sIgglybuffPose69:
ax_pose 8, 0x01f3, 0x40f8, 0x1c00
ax_pose_terminator
sIgglybuffPose70:
ax_pose 16, 0x01f3, 0x40f8, 0x1c00
ax_pose_terminator
sIgglybuffPose71:
ax_pose 4, 0x81ee, 0x80f8, 0x1c00
ax_pose_terminator
sIgglybuffPose72:
ax_pose 5, 0x01f4, 0x40f8, 0x1c00
ax_pose_terminator
sIgglybuffPose73:
ax_pose 0, 0x01f2, 0x40f8, 0x1c00
ax_pose_terminator
sIgglybuffPose74:
ax_pose 20, 0x81f1, 0x80f8, 0x1c00
ax_pose_terminator
sIgglybuffPose75:
ax_pose 21, 0x01f3, 0x40f8, 0x1c00
ax_pose_terminator
sIgglybuffPose76:
ax_pose 3, 0x01f2, 0x50f7, 0x1c00
ax_pose_terminator
sIgglybuffPose77:
ax_pose 22, 0x81f0, 0x90f7, 0x1c00
ax_pose_terminator
sIgglybuffPose78:
ax_pose 23, 0x01f2, 0x50f7, 0x1c00
ax_pose_terminator
sIgglybuffPose79:
ax_pose 6, 0x01f2, 0x50f7, 0x1c00
ax_pose_terminator
sIgglybuffPose80:
ax_pose 24, 0x81f0, 0x90f7, 0x1c00
ax_pose_terminator
sIgglybuffPose81:
ax_pose 25, 0x01f2, 0x50f7, 0x1c00
ax_pose_terminator
sIgglybuffPose82:
ax_pose 9, 0x01f2, 0x50f7, 0x1c00
ax_pose_terminator
sIgglybuffPose83:
ax_pose 26, 0x81f0, 0x90f7, 0x1c00
ax_pose_terminator
sIgglybuffPose84:
ax_pose 27, 0x01f3, 0x50f7, 0x1c00
ax_pose_terminator
sIgglybuffPose85:
ax_pose 12, 0x01f2, 0x40f8, 0x1c00
ax_pose_terminator
sIgglybuffPose86:
ax_pose 28, 0x81f1, 0x80f8, 0x1c00
ax_pose_terminator
sIgglybuffPose87:
ax_pose 29, 0x01f3, 0x40f8, 0x1c00
ax_pose_terminator
sIgglybuffPose88:
ax_pose 9, 0x01f2, 0x40f8, 0x1c00
ax_pose_terminator
sIgglybuffPose89:
ax_pose 26, 0x81f0, 0x80f8, 0x1c00
ax_pose_terminator
sIgglybuffPose90:
ax_pose 27, 0x01f3, 0x40f8, 0x1c00
ax_pose_terminator
sIgglybuffPose91:
ax_pose 6, 0x01f2, 0x40f9, 0x1c00
ax_pose_terminator
sIgglybuffPose92:
ax_pose 24, 0x81f0, 0x80f9, 0x1c00
ax_pose_terminator
sIgglybuffPose93:
ax_pose 25, 0x01f2, 0x40f9, 0x1c00
ax_pose_terminator
sIgglybuffPose94:
ax_pose 3, 0x01f2, 0x40f8, 0x1c00
ax_pose_terminator
sIgglybuffPose95:
ax_pose 22, 0x81f0, 0x80f8, 0x1c00
ax_pose_terminator
sIgglybuffPose96:
ax_pose 23, 0x01f2, 0x40f8, 0x1c00
ax_pose_terminator
sIgglybuffPose97:
ax_pose 0, 0x01f2, 0x40f8, 0x1c00
ax_pose_terminator
sIgglybuffPose98:
ax_pose 15, 0x01f3, 0x40f8, 0x1c00
ax_pose_terminator
sIgglybuffPose99:
ax_pose 20, 0x81f1, 0x80f8, 0x1c00
ax_pose_terminator
sIgglybuffPose100:
ax_pose 3, 0x01f2, 0x50f7, 0x1c00
ax_pose_terminator
sIgglybuffPose101:
ax_pose 16, 0x01f3, 0x50f7, 0x1c00
ax_pose_terminator
sIgglybuffPose102:
ax_pose 22, 0x81f0, 0x90f7, 0x1c00
ax_pose_terminator
sIgglybuffPose103:
ax_pose 6, 0x01f2, 0x50f7, 0x1c00
ax_pose_terminator
sIgglybuffPose104:
ax_pose 17, 0x01f3, 0x50f7, 0x1c00
ax_pose_terminator
sIgglybuffPose105:
ax_pose 24, 0x81f0, 0x90f7, 0x1c00
ax_pose_terminator
sIgglybuffPose106:
ax_pose 9, 0x01f2, 0x50f7, 0x1c00
ax_pose_terminator
sIgglybuffPose107:
ax_pose 18, 0x01f3, 0x50f7, 0x1c00
ax_pose_terminator
sIgglybuffPose108:
ax_pose 26, 0x81f0, 0x90f7, 0x1c00
ax_pose_terminator
sIgglybuffPose109:
ax_pose 12, 0x01f2, 0x40f8, 0x1c00
ax_pose_terminator
sIgglybuffPose110:
ax_pose 19, 0x01f3, 0x40f8, 0x1c00
ax_pose_terminator
sIgglybuffPose111:
ax_pose 28, 0x81f1, 0x80f8, 0x1c00
ax_pose_terminator
sIgglybuffPose112:
ax_pose 9, 0x01f2, 0x40f8, 0x1c00
ax_pose_terminator
sIgglybuffPose113:
ax_pose 18, 0x01f3, 0x40f8, 0x1c00
ax_pose_terminator
sIgglybuffPose114:
ax_pose 26, 0x81f0, 0x80f8, 0x1c00
ax_pose_terminator
sIgglybuffPose115:
ax_pose 6, 0x01f2, 0x40f8, 0x1c00
ax_pose_terminator
sIgglybuffPose116:
ax_pose 17, 0x01f3, 0x40f8, 0x1c00
ax_pose_terminator
sIgglybuffPose117:
ax_pose 24, 0x81f0, 0x80f8, 0x1c00
ax_pose_terminator
sIgglybuffPose118:
ax_pose 3, 0x01f2, 0x40f8, 0x1c00
ax_pose_terminator
sIgglybuffPose119:
ax_pose 16, 0x01f3, 0x40f8, 0x1c00
ax_pose_terminator
sIgglybuffPose120:
ax_pose 22, 0x81f0, 0x80f8, 0x1c00
ax_pose_terminator
sIgglybuffPose121:
ax_pose 30, 0x01f3, 0x40f8, 0x1c00
ax_pose_terminator
sIgglybuffPose122:
ax_pose 31, 0x01f2, 0x40f8, 0x1c00
ax_pose_terminator
sIgglybuffPose123:
ax_pose 32, 0x01e8, 0x80f1, 0x1c00
ax_pose_terminator
sIgglybuffPose124:
ax_pose 33, 0x01e7, 0x90e9, 0x1c00
ax_pose_terminator
sIgglybuffPose125:
ax_pose 34, 0x01e7, 0x90e8, 0x1c00
ax_pose_terminator
sIgglybuffPose126:
ax_pose 35, 0x01e8, 0x90e9, 0x1c00
ax_pose_terminator
sIgglybuffPose127:
ax_pose 36, 0x01e8, 0x80f1, 0x1c00
ax_pose_terminator
sIgglybuffPose128:
ax_pose 35, 0x01e8, 0x80f8, 0x1c00
ax_pose_terminator
sIgglybuffPose129:
ax_pose 34, 0x01e7, 0x80f9, 0x1c00
ax_pose_terminator
sIgglybuffPose130:
ax_pose 33, 0x01e7, 0x80f8, 0x1c00
ax_pose_terminator
sIgglybuffPose131:
ax_pose 0, 0x01f2, 0x40f8, 0x1c00
ax_pose_terminator
sIgglybuffPose132:
ax_pose 1, 0x81ee, 0x80f8, 0x1c00
ax_pose_terminator
sIgglybuffPose133:
ax_pose 3, 0x01f2, 0x50f7, 0x1c00
ax_pose_terminator
sIgglybuffPose134:
ax_pose 4, 0x81ee, 0x90f7, 0x1c00
ax_pose_terminator
sIgglybuffPose135:
ax_pose 6, 0x01f2, 0x50f7, 0x1c00
ax_pose_terminator
sIgglybuffPose136:
ax_pose 7, 0x81ed, 0x90f7, 0x1c00
ax_pose_terminator
sIgglybuffPose137:
ax_pose 9, 0x01f2, 0x50f7, 0x1c00
ax_pose_terminator
sIgglybuffPose138:
ax_pose 10, 0x81ef, 0x90f7, 0x1c00
ax_pose_terminator
sIgglybuffPose139:
ax_pose 12, 0x01f2, 0x40f8, 0x1c00
ax_pose_terminator
sIgglybuffPose140:
ax_pose 13, 0x81ef, 0x80f8, 0x1c00
ax_pose_terminator
sIgglybuffPose141:
ax_pose 9, 0x01f2, 0x40f8, 0x1c00
ax_pose_terminator
sIgglybuffPose142:
ax_pose 10, 0x81ef, 0x80f8, 0x1c00
ax_pose_terminator
sIgglybuffPose143:
ax_pose 6, 0x01f2, 0x40f8, 0x1c00
ax_pose_terminator
sIgglybuffPose144:
ax_pose 7, 0x81ed, 0x80f8, 0x1c00
ax_pose_terminator
sIgglybuffPose145:
ax_pose 3, 0x01f2, 0x40f8, 0x1c00
ax_pose_terminator
sIgglybuffPose146:
ax_pose 4, 0x81ee, 0x80f8, 0x1c00
ax_pose_terminator
sIgglybuffPose147:
ax_pose 20, 0x81f1, 0x80f8, 0x1c00
ax_pose_terminator
sIgglybuffPose148:
ax_pose 22, 0x81f0, 0x80f8, 0x1c00
ax_pose_terminator
sIgglybuffPose149:
ax_pose 24, 0x81f0, 0x80f8, 0x1c00
ax_pose_terminator
sIgglybuffPose150:
ax_pose 26, 0x81f0, 0x80f8, 0x1c00
ax_pose_terminator
sIgglybuffPose151:
ax_pose 28, 0x81f1, 0x80f8, 0x1c00
ax_pose_terminator
sIgglybuffPose152:
ax_pose 26, 0x81f0, 0x90f7, 0x1c00
ax_pose_terminator
sIgglybuffPose153:
ax_pose 24, 0x81f0, 0x90f7, 0x1c00
ax_pose_terminator
sIgglybuffPose154:
ax_pose 22, 0x81f0, 0x90f7, 0x1c00
ax_pose_terminator
sIgglybuffPose155:
ax_pose 20, 0x81f1, 0x80f8, 0x1c00
ax_pose_terminator
sIgglybuffPose156:
ax_pose 22, 0x81f0, 0x90f7, 0x1c00
ax_pose_terminator
sIgglybuffPose157:
ax_pose 24, 0x81f0, 0x90f7, 0x1c00
ax_pose_terminator
sIgglybuffPose158:
ax_pose 26, 0x81f0, 0x90f7, 0x1c00
ax_pose_terminator
sIgglybuffPose159:
ax_pose 28, 0x81f1, 0x80f8, 0x1c00
ax_pose_terminator
sIgglybuffPose160:
ax_pose 26, 0x81f0, 0x80f8, 0x1c00
ax_pose_terminator
sIgglybuffPose161:
ax_pose 24, 0x81f0, 0x80f8, 0x1c00
ax_pose_terminator
sIgglybuffPose162:
ax_pose 22, 0x81f0, 0x80f8, 0x1c00
ax_pose_terminator
sIgglybuffPose163:
ax_pose 0, 0x01f2, 0x40f8, 0x1c00
ax_pose_terminator
sIgglybuffPose164:
ax_pose 1, 0x81f1, 0x80f8, 0x1c00
ax_pose_terminator
sIgglybuffPose165:
ax_pose 2, 0x01f3, 0x40f8, 0x1c00
ax_pose_terminator
sIgglybuffPose166:
ax_pose 3, 0x01f2, 0x50f7, 0x1c00
ax_pose_terminator
sIgglybuffPose167:
ax_pose 4, 0x81f1, 0x90f7, 0x1c00
ax_pose_terminator
sIgglybuffPose168:
ax_pose 5, 0x01f3, 0x50f7, 0x1c00
ax_pose_terminator
sIgglybuffPose169:
ax_pose 6, 0x01f2, 0x50f7, 0x1c00
ax_pose_terminator
sIgglybuffPose170:
ax_pose 7, 0x81f1, 0x90f7, 0x1c00
ax_pose_terminator
sIgglybuffPose171:
ax_pose 8, 0x01f3, 0x50f7, 0x1c00
ax_pose_terminator
sIgglybuffPose172:
ax_pose 9, 0x01f2, 0x50f7, 0x1c00
ax_pose_terminator
sIgglybuffPose173:
ax_pose 10, 0x81f1, 0x90f7, 0x1c00
ax_pose_terminator
sIgglybuffPose174:
ax_pose 11, 0x01f3, 0x50f7, 0x1c00
ax_pose_terminator
sIgglybuffPose175:
ax_pose 12, 0x01f2, 0x40f8, 0x1c00
ax_pose_terminator
sIgglybuffPose176:
ax_pose 13, 0x81f1, 0x80f8, 0x1c00
ax_pose_terminator
sIgglybuffPose177:
ax_pose 14, 0x01f3, 0x40f8, 0x1c00
ax_pose_terminator
sIgglybuffPose178:
ax_pose 9, 0x01f2, 0x40f8, 0x1c00
ax_pose_terminator
sIgglybuffPose179:
ax_pose 10, 0x81f1, 0x80f8, 0x1c00
ax_pose_terminator
sIgglybuffPose180:
ax_pose 11, 0x01f3, 0x40f8, 0x1c00
ax_pose_terminator
sIgglybuffPose181:
ax_pose 6, 0x01f2, 0x40f8, 0x1c00
ax_pose_terminator
sIgglybuffPose182:
ax_pose 7, 0x81f1, 0x80f8, 0x1c00
ax_pose_terminator
sIgglybuffPose183:
ax_pose 8, 0x01f3, 0x40f8, 0x1c00
ax_pose_terminator
sIgglybuffPose184:
ax_pose 3, 0x01f2, 0x40f8, 0x1c00
ax_pose_terminator
sIgglybuffPose185:
ax_pose 4, 0x81f1, 0x80f8, 0x1c00
ax_pose_terminator
sIgglybuffPose186:
ax_pose 5, 0x01f3, 0x40f8, 0x1c00
ax_pose_terminator
sIgglybuffPose187:
ax_pose 15, 0x01f3, 0x40f8, 0x1c00
ax_pose_terminator
sIgglybuffPose188:
ax_pose 16, 0x01f3, 0x40f8, 0x1c00
ax_pose_terminator
sIgglybuffPose189:
ax_pose 17, 0x01f3, 0x40f8, 0x1c00
ax_pose_terminator
sIgglybuffPose190:
ax_pose 18, 0x01f3, 0x40f8, 0x1c00
ax_pose_terminator
sIgglybuffPose191:
ax_pose 19, 0x01f3, 0x40f8, 0x1c00
ax_pose_terminator
sIgglybuffPose192:
ax_pose 18, 0x01f3, 0x50f7, 0x1c00
ax_pose_terminator
sIgglybuffPose193:
ax_pose 17, 0x01f3, 0x50f7, 0x1c00
ax_pose_terminator
sIgglybuffPose194:
ax_pose 16, 0x01f3, 0x50f7, 0x1c00
ax_pose_terminator
sIgglybuffPose195:
ax_pose 0, 0x01f2, 0x40f8, 0x1c00
ax_pose_terminator
sIgglybuffPose196:
ax_pose 3, 0x01f2, 0x40f8, 0x1c00
ax_pose_terminator
sIgglybuffPose197:
ax_pose 6, 0x01f2, 0x40f8, 0x1c00
ax_pose_terminator
sIgglybuffPose198:
ax_pose 9, 0x01f2, 0x40f8, 0x1c00
ax_pose_terminator
sIgglybuffPose199:
ax_pose 12, 0x01f2, 0x40f8, 0x1c00
ax_pose_terminator
sIgglybuffPose200:
ax_pose 9, 0x01f2, 0x50f7, 0x1c00
ax_pose_terminator
sIgglybuffPose201:
ax_pose 6, 0x01f2, 0x50f7, 0x1c00
ax_pose_terminator
sIgglybuffPose202:
ax_pose 3, 0x01f2, 0x50f7, 0x1c00
ax_pose_terminator
.align 2
sIgglybuffAnims_1_1:
ax_anim 8, 0, 0, 0, 0, 0, 0,
ax_anim 4, 0, 1, 0, 0, 0, 0,
ax_anim 4, 0, 1, 0, -1, 0, 0,
ax_anim 4, 0, 1, 0, 0, 0, 0,
ax_anim 8, 0, 2, 0, 0, 0, 0,
ax_anim_terminator
sIgglybuffAnims_1_2:
ax_anim 8, 0, 3, 0, 0, 0, 0,
ax_anim 4, 0, 4, 0, 0, 0, 0,
ax_anim 4, 0, 4, 0, -1, 0, 0,
ax_anim 4, 0, 4, 0, 0, 0, 0,
ax_anim 8, 0, 5, 0, 0, 0, 0,
ax_anim_terminator
sIgglybuffAnims_1_3:
ax_anim 8, 0, 6, 0, 0, 0, 0,
ax_anim 4, 0, 7, 0, 0, 0, 0,
ax_anim 4, 0, 7, 0, -1, 0, 0,
ax_anim 4, 0, 7, 0, 0, 0, 0,
ax_anim 8, 0, 8, 0, 0, 0, 0,
ax_anim_terminator
sIgglybuffAnims_1_4:
ax_anim 8, 0, 9, 0, 0, 0, 0,
ax_anim 4, 0, 10, 0, 0, 0, 0,
ax_anim 4, 0, 10, 0, -1, 0, 0,
ax_anim 4, 0, 10, 0, 0, 0, 0,
ax_anim 8, 0, 11, 0, 0, 0, 0,
ax_anim_terminator
sIgglybuffAnims_1_5:
ax_anim 8, 0, 12, 0, 0, 0, 0,
ax_anim 4, 0, 13, 0, 0, 0, 0,
ax_anim 4, 0, 13, 0, -1, 0, 0,
ax_anim 4, 0, 13, 0, 0, 0, 0,
ax_anim 8, 0, 14, 0, 0, 0, 0,
ax_anim_terminator
sIgglybuffAnims_1_6:
ax_anim 8, 0, 15, 0, 0, 0, 0,
ax_anim 4, 0, 16, 0, 0, 0, 0,
ax_anim 4, 0, 16, 0, -1, 0, 0,
ax_anim 4, 0, 16, 0, 0, 0, 0,
ax_anim 8, 0, 17, 0, 0, 0, 0,
ax_anim_terminator
sIgglybuffAnims_1_7:
ax_anim 8, 0, 18, 0, 0, 0, 0,
ax_anim 4, 0, 19, 0, 0, 0, 0,
ax_anim 4, 0, 19, 0, -1, 0, 0,
ax_anim 4, 0, 19, 0, 0, 0, 0,
ax_anim 8, 0, 20, 0, 0, 0, 0,
ax_anim_terminator
sIgglybuffAnims_1_8:
ax_anim 8, 0, 21, 0, 0, 0, 0,
ax_anim 4, 0, 22, 0, 0, 0, 0,
ax_anim 4, 0, 22, 0, -1, 0, 0,
ax_anim 4, 0, 22, 0, 0, 0, 0,
ax_anim 8, 0, 23, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sIgglybuffAnims_2_1:
ax_anim 2, 0, 25, 0, 0, 0, 0,
ax_anim 2, 0, 25, 0, -1, 0, -1,
ax_anim 4, 0, 25, 0, -2, 0, -2,
ax_anim 1, 0, 26, 0, 0, 0, 0,
ax_anim 2, 0, 26, 0, 4, 0, 4,
ax_anim 2, 2, 24, 0, 10, 0, 10,
ax_anim 2, 0, 24, 0, 18, 0, 18,
ax_anim 2, 1, 24, 1, 18, 1, 18,
ax_anim 2, 0, 24, 0, 18, 0, 18,
ax_anim 2, 0, 24, 1, 18, 1, 18,
ax_anim 2, 0, 25, 0, 6, 0, 6,
ax_anim_terminator
sIgglybuffAnims_2_2:
ax_anim 2, 0, 28, 0, 0, 0, 0,
ax_anim 2, 0, 28, -1, -1, -1, -1,
ax_anim 4, 0, 28, -2, -2, -2, -2,
ax_anim 1, 0, 29, 0, -1, 0, -1,
ax_anim 2, 0, 29, 6, 2, 6, 5,
ax_anim 2, 2, 27, 14, 10, 14, 13,
ax_anim 2, 0, 27, 22, 19, 22, 19,
ax_anim 2, 1, 27, 23, 18, 23, 18,
ax_anim 2, 0, 27, 22, 19, 22, 19,
ax_anim 2, 0, 27, 23, 18, 23, 18,
ax_anim 2, 0, 28, 8, 8, 8, 8,
ax_anim_terminator
sIgglybuffAnims_2_3:
ax_anim 2, 0, 31, 0, 0, 0, 0,
ax_anim 2, 0, 31, -1, 0, -1, 0,
ax_anim 4, 0, 31, -2, 0, -2, 0,
ax_anim 1, 0, 32, 0, 0, 0, 0,
ax_anim 2, 0, 32, 4, -1, 4, 0,
ax_anim 2, 2, 30, 14, -1, 14, 0,
ax_anim 2, 0, 30, 23, -1, 23, 0,
ax_anim 2, 1, 30, 23, 0, 23, 0,
ax_anim 2, 0, 30, 23, -1, 23, -1,
ax_anim 2, 0, 30, 23, 0, 23, 0,
ax_anim 2, 0, 31, 6, 0, 6, 0,
ax_anim_terminator
sIgglybuffAnims_2_4:
ax_anim 2, 0, 34, 0, 0, 0, 0,
ax_anim 2, 0, 34, -1, 1, -1, 1,
ax_anim 4, 0, 34, -2, 2, -2, 2,
ax_anim 1, 0, 35, 0, -1, 0, -1,
ax_anim 2, 0, 35, 3, -11, 3, -4,
ax_anim 2, 2, 33, 10, -18, 10, -12,
ax_anim 2, 0, 33, 22, -27, 22, -27,
ax_anim 2, 1, 33, 23, -26, 23, -26,
ax_anim 2, 0, 33, 22, -27, 22, -27,
ax_anim 2, 0, 33, 23, -26, 23, -26,
ax_anim 2, 0, 34, 6, -6, 6, -6,
ax_anim_terminator
sIgglybuffAnims_2_5:
ax_anim 2, 0, 37, 0, 0, 0, 0,
ax_anim 2, 0, 37, 0, 1, 0, 1,
ax_anim 4, 0, 37, 0, 2, 0, 2,
ax_anim 1, 0, 38, 0, 0, 0, 0,
ax_anim 2, 0, 38, 0, -4, 0, -4,
ax_anim 2, 2, 36, 0, -12, 0, -12,
ax_anim 2, 0, 36, 0, -26, 0, -26,
ax_anim 2, 1, 36, 1, -26, 1, -26,
ax_anim 2, 0, 36, 0, -26, 0, -26,
ax_anim 2, 0, 36, 1, -26, 1, -26,
ax_anim 2, 0, 37, 0, -6, 0, -6,
ax_anim_terminator
sIgglybuffAnims_2_6:
ax_anim 2, 0, 40, 0, 0, 0, 0,
ax_anim 2, 0, 40, 1, 1, 1, 1,
ax_anim 4, 0, 40, 2, 2, 2, 2,
ax_anim 1, 0, 41, 0, -1, 0, -1,
ax_anim 2, 0, 41, -3, -11, -3, -4,
ax_anim 2, 2, 39, -10, -18, -10, -12,
ax_anim 2, 0, 39, -22, -27, -22, -27,
ax_anim 2, 1, 39, -23, -26, -23, -26,
ax_anim 2, 0, 39, -22, -27, -22, -27,
ax_anim 2, 0, 39, -23, -26, -23, -26,
ax_anim 2, 0, 40, -6, -6, -6, -6,
ax_anim_terminator
sIgglybuffAnims_2_7:
ax_anim 2, 0, 43, 0, 0, 0, 0,
ax_anim 2, 0, 43, 1, 0, 1, 0,
ax_anim 4, 0, 43, 2, 0, 2, 0,
ax_anim 1, 0, 44, 0, 0, 0, 0,
ax_anim 2, 0, 44, -4, -1, -4, 0,
ax_anim 2, 2, 42, -14, -1, -14, 0,
ax_anim 2, 0, 42, -23, -1, -23, 0,
ax_anim 2, 1, 42, -23, 0, -23, 0,
ax_anim 2, 0, 42, -23, -1, -23, -1,
ax_anim 2, 0, 42, -23, 0, -23, 0,
ax_anim 2, 0, 43, -6, 0, -6, 0,
ax_anim_terminator
sIgglybuffAnims_2_8:
ax_anim 2, 0, 46, 0, 0, 0, 0,
ax_anim 2, 0, 46, 1, -1, 1, -1,
ax_anim 4, 0, 46, 2, -2, 2, -2,
ax_anim 1, 0, 47, 0, -1, 0, -1,
ax_anim 2, 0, 47, -6, 2, -6, 5,
ax_anim 2, 2, 45, -14, 10, -14, 13,
ax_anim 2, 0, 45, -22, 19, -22, 19,
ax_anim 2, 1, 45, -23, 18, -23, 18,
ax_anim 2, 0, 45, -22, 19, -22, 19,
ax_anim 2, 0, 45, -23, 18, -23, 18,
ax_anim 2, 0, 46, -8, 8, -8, 8,
ax_anim_terminator
.align 2
sIgglybuffAnims_3_1:
ax_anim 2, 0, 49, 0, 0, 0, 0,
ax_anim 2, 0, 49, 0, -1, 0, -1,
ax_anim 4, 0, 49, 0, -2, 0, -2,
ax_anim 1, 0, 50, 0, 0, 0, 0,
ax_anim 2, 0, 50, 0, 4, 0, 4,
ax_anim 2, 2, 48, 0, 10, 0, 10,
ax_anim 2, 0, 48, 0, 18, 0, 18,
ax_anim 2, 1, 48, 1, 18, 1, 18,
ax_anim 2, 0, 48, 0, 18, 0, 18,
ax_anim 2, 0, 48, 1, 18, 1, 18,
ax_anim 2, 0, 49, 0, 6, 0, 6,
ax_anim_terminator
sIgglybuffAnims_3_2:
ax_anim 2, 0, 52, 0, 0, 0, 0,
ax_anim 2, 0, 52, -1, -1, -1, -1,
ax_anim 4, 0, 52, -2, -2, -2, -2,
ax_anim 1, 0, 53, 0, -1, 0, -1,
ax_anim 2, 0, 53, 6, 2, 6, 5,
ax_anim 2, 2, 51, 14, 10, 14, 13,
ax_anim 2, 0, 51, 22, 19, 22, 19,
ax_anim 2, 1, 51, 23, 18, 23, 18,
ax_anim 2, 0, 51, 22, 19, 22, 19,
ax_anim 2, 0, 51, 23, 18, 23, 18,
ax_anim 2, 0, 52, 8, 8, 8, 8,
ax_anim_terminator
sIgglybuffAnims_3_3:
ax_anim 2, 0, 55, 0, 0, 0, 0,
ax_anim 2, 0, 55, -1, 0, -1, 0,
ax_anim 4, 0, 55, -2, 0, -2, 0,
ax_anim 1, 0, 56, 0, 0, 0, 0,
ax_anim 2, 0, 56, 4, -1, 4, 0,
ax_anim 2, 2, 54, 14, -1, 14, 0,
ax_anim 2, 0, 54, 23, -1, 23, 0,
ax_anim 2, 1, 54, 23, 0, 23, 0,
ax_anim 2, 0, 54, 23, -1, 23, -1,
ax_anim 2, 0, 54, 23, 0, 23, 0,
ax_anim 2, 0, 55, 6, 0, 6, 0,
ax_anim_terminator
sIgglybuffAnims_3_4:
ax_anim 2, 0, 58, 0, 0, 0, 0,
ax_anim 2, 0, 58, -1, 1, -1, 1,
ax_anim 4, 0, 58, -2, 2, -2, 2,
ax_anim 1, 0, 59, 0, -1, 0, -1,
ax_anim 2, 0, 59, 3, -11, 3, -4,
ax_anim 2, 2, 57, 10, -18, 10, -12,
ax_anim 2, 0, 57, 22, -27, 22, -27,
ax_anim 2, 1, 57, 23, -26, 23, -26,
ax_anim 2, 0, 57, 22, -27, 22, -27,
ax_anim 2, 0, 57, 23, -26, 23, -26,
ax_anim 2, 0, 58, 6, -6, 6, -6,
ax_anim_terminator
sIgglybuffAnims_3_5:
ax_anim 2, 0, 61, 0, 0, 0, 0,
ax_anim 2, 0, 61, 0, 1, 0, 1,
ax_anim 4, 0, 61, 0, 2, 0, 2,
ax_anim 1, 0, 62, 0, 0, 0, 0,
ax_anim 2, 0, 62, 0, -4, 0, -4,
ax_anim 2, 2, 60, 0, -12, 0, -12,
ax_anim 2, 0, 60, 0, -26, 0, -26,
ax_anim 2, 1, 60, 1, -26, 1, -26,
ax_anim 2, 0, 60, 0, -26, 0, -26,
ax_anim 2, 0, 60, 1, -26, 1, -26,
ax_anim 2, 0, 61, 0, -6, 0, -6,
ax_anim_terminator
sIgglybuffAnims_3_6:
ax_anim 2, 0, 64, 0, 0, 0, 0,
ax_anim 2, 0, 64, 1, 1, 1, 1,
ax_anim 4, 0, 64, 2, 2, 2, 2,
ax_anim 1, 0, 65, 0, -1, 0, -1,
ax_anim 2, 0, 65, -3, -11, -3, -4,
ax_anim 2, 2, 63, -10, -18, -10, -12,
ax_anim 2, 0, 63, -22, -27, -22, -27,
ax_anim 2, 1, 63, -23, -26, -23, -26,
ax_anim 2, 0, 63, -22, -27, -22, -27,
ax_anim 2, 0, 63, -23, -26, -23, -26,
ax_anim 2, 0, 64, -6, -6, -6, -6,
ax_anim_terminator
sIgglybuffAnims_3_7:
ax_anim 2, 0, 67, 0, 0, 0, 0,
ax_anim 2, 0, 67, 1, 0, 1, 0,
ax_anim 4, 0, 67, 2, 0, 2, 0,
ax_anim 1, 0, 68, 0, 0, 0, 0,
ax_anim 2, 0, 68, -4, -1, -4, 0,
ax_anim 2, 2, 66, -14, -1, -14, 0,
ax_anim 2, 0, 66, -23, -1, -23, 0,
ax_anim 2, 1, 66, -23, 0, -23, 0,
ax_anim 2, 0, 66, -23, -1, -23, -1,
ax_anim 2, 0, 66, -23, 0, -23, 0,
ax_anim 2, 0, 67, -6, 0, -6, 0,
ax_anim_terminator
sIgglybuffAnims_3_8:
ax_anim 2, 0, 70, 0, 0, 0, 0,
ax_anim 2, 0, 70, 1, -1, 1, -1,
ax_anim 4, 0, 70, 2, -2, 2, -2,
ax_anim 1, 0, 71, 0, -1, 0, -1,
ax_anim 2, 0, 71, -6, 2, -6, 5,
ax_anim 2, 2, 69, -14, 10, -14, 13,
ax_anim 2, 0, 69, -22, 19, -22, 19,
ax_anim 2, 1, 69, -23, 18, -23, 18,
ax_anim 2, 0, 69, -22, 19, -22, 19,
ax_anim 2, 0, 69, -23, 18, -23, 18,
ax_anim 2, 0, 70, -8, 8, -8, 8,
ax_anim_terminator
.align 2
sIgglybuffAnims_4_1:
ax_anim 2, 0, 73, 0, 0, 0, 0,
ax_anim 4, 0, 77, 0, 0, 0, 0,
ax_anim 4, 0, 76, 0, 0, 0, 0,
ax_anim 4, 2, 74, 0, 0, 0, 0,
ax_anim 4, 0, 73, 0, 0, 0, 0,
ax_anim 4, 0, 95, 0, 0, 0, 0,
ax_anim 4, 0, 94, 0, 0, 0, 0,
ax_anim 4, 1, 74, 0, 0, 0, 0,
ax_anim 2, 0, 73, 0, 0, 0, 0,
ax_anim_terminator
sIgglybuffAnims_4_2:
ax_anim 2, 0, 76, 0, 0, 0, 0,
ax_anim 4, 0, 80, 0, 0, 0, 0,
ax_anim 4, 0, 79, 0, 0, 0, 0,
ax_anim 4, 2, 77, 0, 0, 0, 0,
ax_anim 4, 0, 76, 0, 0, 0, 0,
ax_anim 4, 0, 74, 0, 0, 0, 0,
ax_anim 4, 0, 73, 0, 0, 0, 0,
ax_anim 4, 1, 77, 0, 0, 0, 0,
ax_anim 2, 0, 76, 0, 0, 0, 0,
ax_anim_terminator
sIgglybuffAnims_4_3:
ax_anim 2, 0, 79, 0, 0, 0, 0,
ax_anim 4, 0, 83, 0, 0, 0, 0,
ax_anim 4, 0, 82, 0, 0, 0, 0,
ax_anim 4, 2, 80, 0, 0, 0, 0,
ax_anim 4, 0, 79, 0, 0, 0, 0,
ax_anim 4, 0, 77, 0, 0, 0, 0,
ax_anim 4, 0, 76, 0, 0, 0, 0,
ax_anim 4, 1, 80, 0, 0, 0, 0,
ax_anim 2, 0, 79, 0, 0, 0, 0,
ax_anim_terminator
sIgglybuffAnims_4_4:
ax_anim 2, 0, 82, 0, 0, 0, 0,
ax_anim 4, 0, 86, 0, 0, 0, 0,
ax_anim 4, 0, 85, 0, 0, 0, 0,
ax_anim 4, 2, 83, 0, 0, 0, 0,
ax_anim 4, 0, 82, 0, 0, 0, 0,
ax_anim 4, 0, 80, 0, 0, 0, 0,
ax_anim 4, 0, 79, 0, 0, 0, 0,
ax_anim 4, 1, 83, 0, 0, 0, 0,
ax_anim 2, 0, 82, 0, 0, 0, 0,
ax_anim_terminator
sIgglybuffAnims_4_5:
ax_anim 2, 0, 85, 0, 0, 0, 0,
ax_anim 4, 0, 89, 0, 0, 0, 0,
ax_anim 4, 0, 88, 0, 0, 0, 0,
ax_anim 4, 2, 86, 0, 0, 0, 0,
ax_anim 4, 0, 85, 0, 0, 0, 0,
ax_anim 4, 0, 83, 0, 0, 0, 0,
ax_anim 4, 0, 82, 0, 0, 0, 0,
ax_anim 4, 1, 86, 0, 0, 0, 0,
ax_anim 2, 0, 85, 0, 0, 0, 0,
ax_anim_terminator
sIgglybuffAnims_4_6:
ax_anim 2, 0, 88, 0, 0, 0, 0,
ax_anim 4, 0, 92, 0, 0, 0, 0,
ax_anim 4, 0, 91, 0, 0, 0, 0,
ax_anim 4, 2, 89, 0, 0, 0, 0,
ax_anim 4, 0, 88, 0, 0, 0, 0,
ax_anim 4, 0, 86, 0, 0, 0, 0,
ax_anim 4, 0, 85, 0, 0, 0, 0,
ax_anim 4, 1, 89, 0, 0, 0, 0,
ax_anim 2, 0, 88, 0, 0, 0, 0,
ax_anim_terminator
sIgglybuffAnims_4_7:
ax_anim 2, 0, 91, 0, 0, 0, 0,
ax_anim 4, 0, 95, 0, 0, 0, 0,
ax_anim 4, 0, 94, 0, 0, 0, 0,
ax_anim 4, 2, 92, 0, 0, 0, 0,
ax_anim 4, 0, 91, 0, 0, 0, 0,
ax_anim 4, 0, 89, 0, 0, 0, 0,
ax_anim 4, 0, 88, 0, 0, 0, 0,
ax_anim 4, 1, 92, 0, 0, 0, 0,
ax_anim 2, 0, 91, 0, 0, 0, 0,
ax_anim_terminator
sIgglybuffAnims_4_8:
ax_anim 2, 0, 94, 0, 0, 0, 0,
ax_anim 4, 0, 74, 0, 0, 0, 0,
ax_anim 4, 0, 73, 0, 0, 0, 0,
ax_anim 4, 2, 95, 0, 0, 0, 0,
ax_anim 4, 0, 94, 0, 0, 0, 0,
ax_anim 4, 0, 92, 0, 0, 0, 0,
ax_anim 4, 0, 91, 0, 0, 0, 0,
ax_anim 4, 1, 95, 0, 0, 0, 0,
ax_anim 2, 0, 94, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sIgglybuffAnims_5_1:
ax_anim 1, 0, 98, 0, -2, 0, -2,
ax_anim 2, 0, 98, 0, -3, 0, -3,
ax_anim 4, 2, 98, 0, -4, 0, -4,
ax_anim 2, 0, 98, 0, -3, 0, -3,
ax_anim 1, 0, 96, 0, -2, 0, -2,
ax_anim 4, 0, 97, 0, 0, 0, 0,
ax_anim 2, 1, 97, 1, 0, 1, 0,
ax_anim 2, 0, 97, 0, 0, 0, 0,
ax_anim 2, 0, 97, 1, 0, 1, 0,
ax_anim 2, 0, 97, 0, 0, 0, 0,
ax_anim 2, 0, 97, 1, 0, 1, 0,
ax_anim_terminator
sIgglybuffAnims_5_2:
ax_anim 1, 0, 101, 0, -2, 0, -2,
ax_anim 2, 0, 101, 0, -3, 0, -3,
ax_anim 4, 2, 101, 0, -4, 0, -4,
ax_anim 2, 0, 101, 0, -3, 0, -3,
ax_anim 1, 0, 99, 0, -2, 0, -2,
ax_anim 4, 0, 100, 0, 0, 0, 0,
ax_anim 2, 1, 100, 1, -1, 1, -1,
ax_anim 2, 0, 100, 0, 0, 0, 0,
ax_anim 2, 0, 100, 1, -1, 1, -1,
ax_anim 2, 0, 100, 0, 0, 0, 0,
ax_anim 2, 0, 100, 1, -1, 1, -1,
ax_anim_terminator
sIgglybuffAnims_5_3:
ax_anim 1, 0, 104, 0, -2, 0, 0,
ax_anim 2, 0, 104, 0, -3, 0, 0,
ax_anim 4, 2, 104, 0, -4, 0, 0,
ax_anim 2, 0, 104, 0, -3, 0, 0,
ax_anim 1, 0, 102, 0, -2, 0, 0,
ax_anim 4, 0, 103, 0, 0, 0, 0,
ax_anim 2, 1, 103, 0, 1, 0, 1,
ax_anim 2, 0, 103, 0, 0, 0, 0,
ax_anim 2, 0, 103, 0, 1, 0, 1,
ax_anim 2, 0, 103, 0, 0, 0, 0,
ax_anim 2, 0, 103, 0, 1, 0, 1,
ax_anim_terminator
sIgglybuffAnims_5_4:
ax_anim 1, 0, 107, 0, -2, 0, -2,
ax_anim 2, 0, 107, 0, -3, 0, -3,
ax_anim 4, 2, 107, 0, -4, 0, -4,
ax_anim 2, 0, 107, 0, -3, 0, -3,
ax_anim 1, 0, 105, 0, -2, 0, -2,
ax_anim 4, 0, 106, 0, 0, 0, 0,
ax_anim 2, 1, 106, 1, 1, 1, 1,
ax_anim 2, 0, 106, 0, 0, 0, 0,
ax_anim 2, 0, 106, 1, 1, 1, 1,
ax_anim 2, 0, 106, 0, 0, 0, 0,
ax_anim 2, 0, 106, 1, 1, 1, 1,
ax_anim_terminator
sIgglybuffAnims_5_5:
ax_anim 1, 0, 110, 0, -2, 0, -2,
ax_anim 2, 0, 110, 0, -3, 0, -3,
ax_anim 4, 2, 110, 0, -4, 0, -4,
ax_anim 2, 0, 110, 0, -3, 0, -3,
ax_anim 1, 0, 108, 0, -1, 0, -2,
ax_anim 4, 0, 109, 0, 0, 0, 0,
ax_anim 2, 1, 109, 1, 0, 1, 0,
ax_anim 2, 0, 109, 0, 0, 0, 0,
ax_anim 2, 0, 109, 1, 0, 1, 0,
ax_anim 2, 0, 109, 0, 0, 0, 0,
ax_anim 2, 0, 109, 1, 0, 1, 0,
ax_anim_terminator
sIgglybuffAnims_5_6:
ax_anim 1, 0, 113, 0, -2, 0, -2,
ax_anim 2, 0, 113, 0, -3, 0, -3,
ax_anim 4, 2, 113, 0, -4, 0, -4,
ax_anim 2, 0, 113, 0, -3, 0, -3,
ax_anim 1, 0, 111, 0, -2, 0, -2,
ax_anim 4, 0, 112, 0, 0, 0, 0,
ax_anim 2, 1, 112, -1, 1, -1, 1,
ax_anim 2, 0, 112, 0, 0, 0, 0,
ax_anim 2, 0, 112, -1, 1, -1, 1,
ax_anim 2, 0, 112, 0, 0, 0, 0,
ax_anim 2, 0, 112, -1, 1, -1, 1,
ax_anim_terminator
sIgglybuffAnims_5_7:
ax_anim 1, 0, 116, 0, -2, 0, 0,
ax_anim 2, 0, 116, 0, -3, 0, 0,
ax_anim 4, 2, 116, 0, -4, 0, 0,
ax_anim 2, 0, 116, 0, -3, 0, 0,
ax_anim 1, 0, 114, 0, -2, 0, 0,
ax_anim 4, 0, 115, 0, 0, 0, 0,
ax_anim 2, 1, 115, 0, 1, 0, 1,
ax_anim 2, 0, 115, 0, 0, 0, 0,
ax_anim 2, 0, 115, 0, 1, 0, 1,
ax_anim 2, 0, 115, 0, 0, 0, 0,
ax_anim 2, 0, 115, 0, 1, 0, 1,
ax_anim_terminator
sIgglybuffAnims_5_8:
ax_anim 1, 0, 119, 0, -2, 0, -2,
ax_anim 2, 0, 119, 0, -3, 0, -3,
ax_anim 4, 2, 119, 0, -4, 0, -4,
ax_anim 2, 0, 119, 0, -3, 0, -3,
ax_anim 1, 0, 117, 0, -2, 0, -2,
ax_anim 4, 0, 118, 0, 0, 0, 0,
ax_anim 2, 1, 118, -1, -1, -1, -1,
ax_anim 2, 0, 118, 0, 0, 0, 0,
ax_anim 2, 0, 118, -1, -1, -1, -1,
ax_anim 2, 0, 118, 0, 0, 0, 0,
ax_anim 2, 0, 118, -1, -1, -1, -1,
ax_anim_terminator
.align 2
sIgglybuffAnims_6_1:
ax_anim 30, 0, 120, 0, 0, 0, 0,
ax_anim 35, 0, 121, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sIgglybuffAnims_7_1:
ax_anim 2, 0, 122, 0, -2, 0, -2,
ax_anim 8, 0, 122, 0, -3, 0, -3,
ax_anim_terminator
sIgglybuffAnims_7_2:
ax_anim 2, 0, 123, -2, -2, -2, -2,
ax_anim 8, 0, 123, -3, -3, -3, -3,
ax_anim_terminator
sIgglybuffAnims_7_3:
ax_anim 2, 0, 124, -2, 0, -2, 0,
ax_anim 8, 0, 124, -3, 0, -3, 0,
ax_anim_terminator
sIgglybuffAnims_7_4:
ax_anim 2, 0, 125, -2, 2, -2, 2,
ax_anim 8, 0, 125, -3, 3, -3, 3,
ax_anim_terminator
sIgglybuffAnims_7_5:
ax_anim 2, 0, 126, 0, 2, 0, 2,
ax_anim 8, 0, 126, 0, 3, 0, 3,
ax_anim_terminator
sIgglybuffAnims_7_6:
ax_anim 2, 0, 127, 2, 2, 2, 2,
ax_anim 8, 0, 127, 3, 3, 3, 3,
ax_anim_terminator
sIgglybuffAnims_7_7:
ax_anim 2, 0, 128, 2, 0, 2, 0,
ax_anim 8, 0, 128, 3, 0, 3, 0,
ax_anim_terminator
sIgglybuffAnims_7_8:
ax_anim 2, 0, 129, 2, -2, 2, -2,
ax_anim 8, 0, 129, 3, -3, 3, -3,
ax_anim_terminator
.align 2
sIgglybuffAnims_8_1:
ax_anim 16, 0, 130, 0, 0, 0, 0,
ax_anim 16, 0, 131, 0, 3, 0, 0,
ax_anim_terminator
sIgglybuffAnims_8_2:
ax_anim 16, 0, 132, 0, 0, 0, 0,
ax_anim 16, 0, 133, 0, 3, 0, 0,
ax_anim_terminator
sIgglybuffAnims_8_3:
ax_anim 16, 0, 134, 0, 0, 0, 0,
ax_anim 16, 0, 135, 0, 4, 0, 0,
ax_anim_terminator
sIgglybuffAnims_8_4:
ax_anim 16, 0, 136, 0, 0, 0, 0,
ax_anim 16, 0, 137, 1, 2, 0, 0,
ax_anim_terminator
sIgglybuffAnims_8_5:
ax_anim 16, 0, 138, 0, 0, 0, 0,
ax_anim 16, 0, 139, 0, 2, 0, 0,
ax_anim_terminator
sIgglybuffAnims_8_6:
ax_anim 16, 0, 140, 0, 0, 0, 0,
ax_anim 16, 0, 141, -1, 2, 0, 0,
ax_anim_terminator
sIgglybuffAnims_8_7:
ax_anim 16, 0, 142, 0, 0, 0, 0,
ax_anim 16, 0, 143, 0, 4, 0, 0,
ax_anim_terminator
sIgglybuffAnims_8_8:
ax_anim 16, 0, 144, 0, 0, 0, 0,
ax_anim 16, 0, 145, 0, 3, 0, 0,
ax_anim_terminator
.align 2
sIgglybuffAnims_9_1:
ax_anim 2, 0, 146, 0, 0, 0, 0,
ax_anim 1, 0, 147, 6, 3, 6, 3,
ax_anim 2, 0, 148, 8, 10, 8, 10,
ax_anim 2, 0, 149, 7, 17, 7, 17,
ax_anim 3, 0, 150, 0, 20, 0, 20,
ax_anim 2, 3, 151, -7, 17, -7, 17,
ax_anim 2, 0, 152, -8, 10, -8, 10,
ax_anim 1, 0, 153, -6, 3, -6, 3,
ax_anim 1, 0, 146, 0, 0, 0, 0,
ax_anim_terminator
sIgglybuffAnims_9_2:
ax_anim 2, 0, 153, 0, 0, 0, 0,
ax_anim 1, 0, 146, 8, 0, 8, 0,
ax_anim 2, 0, 147, 17, 3, 17, 3,
ax_anim 2, 0, 148, 23, 12, 23, 12,
ax_anim 3, 0, 149, 24, 20, 24, 20,
ax_anim 2, 3, 150, 16, 21, 16, 21,
ax_anim 2, 0, 151, 6, 17, 6, 17,
ax_anim 1, 0, 152, 0, 7, 0, 7,
ax_anim 1, 0, 153, 0, 0, 0, 0,
ax_anim_terminator
sIgglybuffAnims_9_3:
ax_anim 2, 0, 152, 0, 0, 0, 0,
ax_anim 1, 0, 153, 3, -4, 3, -4,
ax_anim 2, 0, 146, 13, -6, 13, -6,
ax_anim 2, 0, 147, 19, -5, 19, -5,
ax_anim 3, 0, 148, 24, -2, 24, -2,
ax_anim 2, 3, 149, 21, 4, 21, 4,
ax_anim 2, 0, 150, 14, 5, 14, 5,
ax_anim 1, 0, 151, 4, 5, 4, 5,
ax_anim 1, 0, 152, 0, 0, 0, 0,
ax_anim_terminator
sIgglybuffAnims_9_4:
ax_anim 2, 0, 151, 0, 0, 0, 0,
ax_anim 1, 0, 152, -1, -8, -1, -8,
ax_anim 2, 0, 153, 6, -21, 6, -21,
ax_anim 2, 0, 146, 14, -25, 14, -25,
ax_anim 3, 0, 147, 24, -24, 24, -24,
ax_anim 2, 3, 148, 25, -14, 25, -14,
ax_anim 2, 0, 149, 18, -5, 18, -5,
ax_anim 1, 0, 150, 7, -1, 7, -1,
ax_anim 1, 0, 151, 0, 0, 0, 0,
ax_anim_terminator
sIgglybuffAnims_9_5:
ax_anim 2, 0, 150, 0, 0, 0, 0,
ax_anim 1, 0, 151, -8, -5, -8, -5,
ax_anim 2, 0, 152, -9, -14, -9, -14,
ax_anim 2, 0, 153, -7, -21, -7, -21,
ax_anim 3, 0, 146, 0, -25, 0, -25,
ax_anim 2, 3, 147, 7, -21, 7, -21,
ax_anim 2, 0, 148, 9, -14, 9, -14,
ax_anim 1, 0, 149, 8, -5, 8, -5,
ax_anim 1, 0, 150, 0, 0, 0, 0,
ax_anim_terminator
sIgglybuffAnims_9_6:
ax_anim 2, 0, 149, 0, 0, 0, 0,
ax_anim 1, 0, 148, 1, -8, 1, -8,
ax_anim 2, 0, 147, -6, -21, -6, -21,
ax_anim 2, 0, 146, -14, -25, -14, -25,
ax_anim 3, 0, 153, -24, -24, -24, -24,
ax_anim 2, 3, 152, -25, -14, -25, -14,
ax_anim 2, 0, 151, -18, -5, -18, -5,
ax_anim 1, 0, 150, -7, -1, -7, -1,
ax_anim 1, 0, 149, 0, 0, 0, 0,
ax_anim_terminator
sIgglybuffAnims_9_7:
ax_anim 2, 0, 148, 0, 0, 0, 0,
ax_anim 1, 0, 147, -3, -4, -3, -4,
ax_anim 2, 0, 146, -13, -6, -13, -6,
ax_anim 2, 0, 153, -19, -5, -19, -5,
ax_anim 3, 0, 152, -24, -2, -24, -2,
ax_anim 2, 3, 151, -21, 4, -21, 4,
ax_anim 2, 0, 150, -14, 5, -14, 5,
ax_anim 1, 0, 149, -4, 5, -4, 5,
ax_anim 1, 0, 148, 0, 0, 0, 0,
ax_anim_terminator
sIgglybuffAnims_9_8:
ax_anim 2, 0, 147, 0, 0, 0, 0,
ax_anim 1, 0, 146, -8, 0, -8, 0,
ax_anim 2, 0, 153, -17, 3, -17, 3,
ax_anim 2, 0, 152, -23, 12, -23, 12,
ax_anim 3, 0, 151, -24, 20, -24, 20,
ax_anim 2, 3, 150, -16, 21, -16, 21,
ax_anim 2, 0, 149, -6, 17, -6, 17,
ax_anim 1, 0, 148, 0, 7, 0, 7,
ax_anim 1, 0, 147, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sIgglybuffAnims_10_1:
ax_anim 2, 0, 154, 0, 0, 0, 0,
ax_anim 2, 0, 154, 6, 0, 6, 0,
ax_anim 2, 0, 154, -6, 0, -6, 0,
ax_anim 2, 0, 154, 10, 0, 10, 0,
ax_anim 2, 0, 154, -10, 0, -10, 0,
ax_anim 2, 0, 154, 12, 0, 12, 0,
ax_anim 3, 0, 154, -12, 0, -12, 0,
ax_anim 3, 0, 154, 13, 0, 13, 0,
ax_anim 3, 0, 154, -13, 0, -13, 0,
ax_anim 2, 0, 154, 12, 0, 12, 0,
ax_anim 3, 0, 154, -12, 0, -12, 0,
ax_anim 2, 0, 154, 10, 0, 10, 0,
ax_anim 2, 0, 154, -10, 0, -10, 0,
ax_anim 2, 0, 154, 6, 0, 6, 0,
ax_anim 2, 0, 154, -6, 0, -6, 0,
ax_anim 2, 0, 154, 0, 0, 0, 0,
ax_anim_terminator
sIgglybuffAnims_10_2:
ax_anim 2, 0, 155, 0, 0, 0, 0,
ax_anim 2, 0, 155, 6, -6, 6, -6,
ax_anim 2, 0, 155, -6, 6, -6, 6,
ax_anim 2, 0, 155, 10, -10, 10, -10,
ax_anim 2, 0, 155, -10, 10, -10, 10,
ax_anim 2, 0, 155, 12, -12, 12, -12,
ax_anim 3, 0, 155, -12, 12, -12, 12,
ax_anim 3, 0, 155, 13, -13, 13, -13,
ax_anim 3, 0, 155, -13, 13, -13, 13,
ax_anim 2, 0, 155, 12, -12, 12, -12,
ax_anim 3, 0, 155, -12, 12, -12, 12,
ax_anim 2, 0, 155, 10, -10, 10, -10,
ax_anim 2, 0, 155, -10, 10, -10, 10,
ax_anim 2, 0, 155, 6, -6, 6, -6,
ax_anim 2, 0, 155, -6, 6, -6, 6,
ax_anim 2, 0, 155, 0, 0, 0, 0,
ax_anim_terminator
sIgglybuffAnims_10_3:
ax_anim 2, 0, 156, 0, 0, 0, 0,
ax_anim 2, 0, 156, 0, -6, 0, -6,
ax_anim 2, 0, 156, 0, 6, 0, 6,
ax_anim 2, 0, 156, 0, -10, 0, -10,
ax_anim 2, 0, 156, 0, 10, 0, 10,
ax_anim 2, 0, 156, 0, -12, 0, -12,
ax_anim 3, 0, 156, 0, 12, 0, 12,
ax_anim 3, 0, 156, 0, -13, 0, -13,
ax_anim 3, 0, 156, 0, 13, 0, 13,
ax_anim 2, 0, 156, 0, -12, 0, -12,
ax_anim 3, 0, 156, 0, 12, 0, 12,
ax_anim 2, 0, 156, 0, -10, 0, -10,
ax_anim 2, 0, 156, 0, 10, 0, 10,
ax_anim 2, 0, 156, 0, -6, 0, -6,
ax_anim 2, 0, 156, 0, 6, 0, 6,
ax_anim 2, 0, 156, 0, 0, 0, 0,
ax_anim_terminator
sIgglybuffAnims_10_4:
ax_anim 2, 0, 157, 0, 0, 0, 0,
ax_anim 2, 0, 157, -6, -6, -6, -6,
ax_anim 2, 0, 157, 6, 6, 6, 6,
ax_anim 2, 0, 157, -10, -10, -10, -10,
ax_anim 2, 0, 157, 10, 10, 10, 10,
ax_anim 2, 0, 157, -12, -12, -12, -12,
ax_anim 3, 0, 157, 12, 12, 12, 12,
ax_anim 3, 0, 157, -13, -13, -13, -13,
ax_anim 3, 0, 157, 13, 13, 13, 13,
ax_anim 2, 0, 157, -12, -12, -12, -12,
ax_anim 3, 0, 157, 12, 12, 12, 12,
ax_anim 2, 0, 157, -10, -10, -10, -10,
ax_anim 2, 0, 157, 10, 10, 10, 10,
ax_anim 2, 0, 157, -6, -6, -6, -6,
ax_anim 2, 0, 157, 6, 6, 6, 6,
ax_anim 2, 0, 157, 0, 0, 0, 0,
ax_anim_terminator
sIgglybuffAnims_10_5:
ax_anim 2, 0, 158, 0, 0, 0, 0,
ax_anim 2, 0, 158, 6, 0, 6, 0,
ax_anim 2, 0, 158, -6, 0, -6, 0,
ax_anim 2, 0, 158, 10, 0, 10, 0,
ax_anim 2, 0, 158, -10, 0, -10, 0,
ax_anim 2, 0, 158, 12, 0, 12, 0,
ax_anim 3, 0, 158, -12, 0, -12, 0,
ax_anim 3, 0, 158, 13, 0, 13, 0,
ax_anim 3, 0, 158, -13, 0, -13, 0,
ax_anim 2, 0, 158, 12, 0, 12, 0,
ax_anim 3, 0, 158, -12, 0, -12, 0,
ax_anim 2, 0, 158, 10, 0, 10, 0,
ax_anim 2, 0, 158, -10, 0, -10, 0,
ax_anim 2, 0, 158, 6, 0, 6, 0,
ax_anim 2, 0, 158, -6, 0, -6, 0,
ax_anim 2, 0, 158, 0, 0, 0, 0,
ax_anim_terminator
sIgglybuffAnims_10_6:
ax_anim 2, 0, 159, 0, 0, 0, 0,
ax_anim 2, 0, 159, 6, -6, 6, -6,
ax_anim 2, 0, 159, -6, 6, -6, 6,
ax_anim 2, 0, 159, 10, -10, 10, -10,
ax_anim 2, 0, 159, -10, 10, -10, 10,
ax_anim 2, 0, 159, 12, -12, 12, -12,
ax_anim 3, 0, 159, -12, 12, -12, 12,
ax_anim 3, 0, 159, 13, -13, 13, -13,
ax_anim 3, 0, 159, -13, 13, -13, 13,
ax_anim 2, 0, 159, 12, -12, 12, -12,
ax_anim 3, 0, 159, -12, 12, -12, 12,
ax_anim 2, 0, 159, 10, -10, 10, -10,
ax_anim 2, 0, 159, -10, 10, -10, 10,
ax_anim 2, 0, 159, 6, -6, 6, -6,
ax_anim 2, 0, 159, -6, 6, -6, 6,
ax_anim 2, 0, 159, 0, 0, 0, 0,
ax_anim_terminator
sIgglybuffAnims_10_7:
ax_anim 2, 0, 160, 0, 0, 0, 0,
ax_anim 2, 0, 160, 0, -6, 0, -6,
ax_anim 2, 0, 160, 0, 6, 0, 6,
ax_anim 2, 0, 160, 0, -10, 0, -10,
ax_anim 2, 0, 160, 0, 10, 0, 10,
ax_anim 2, 0, 160, 0, -12, 0, -12,
ax_anim 3, 0, 160, 0, 12, 0, 12,
ax_anim 3, 0, 160, 0, -13, 0, -13,
ax_anim 3, 0, 160, 0, 13, 0, 13,
ax_anim 2, 0, 160, 0, -12, 0, -12,
ax_anim 3, 0, 160, 0, 12, 0, 12,
ax_anim 2, 0, 160, 0, -10, 0, -10,
ax_anim 2, 0, 160, 0, 10, 0, 10,
ax_anim 2, 0, 160, 0, -6, 0, -6,
ax_anim 2, 0, 160, 0, 6, 0, 6,
ax_anim 2, 0, 160, 0, 0, 0, 0,
ax_anim_terminator
sIgglybuffAnims_10_8:
ax_anim 2, 0, 161, 0, 0, 0, 0,
ax_anim 2, 0, 161, -6, -6, -6, -6,
ax_anim 2, 0, 161, 6, 6, 6, 6,
ax_anim 2, 0, 161, -10, -10, -10, -10,
ax_anim 2, 0, 161, 10, 10, 10, 10,
ax_anim 2, 0, 161, -12, -12, -12, -12,
ax_anim 3, 0, 161, 12, 12, 12, 12,
ax_anim 3, 0, 161, -13, -13, -13, -13,
ax_anim 3, 0, 161, 13, 13, 13, 13,
ax_anim 2, 0, 161, -12, -12, -12, -12,
ax_anim 3, 0, 161, 12, 12, 12, 12,
ax_anim 2, 0, 161, -10, -10, -10, -10,
ax_anim 2, 0, 161, 10, 10, 10, 10,
ax_anim 2, 0, 161, -6, -6, -6, -6,
ax_anim 2, 0, 161, 6, 6, 6, 6,
ax_anim 2, 0, 161, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sIgglybuffAnims_11_1:
ax_anim 2, 0, 162, 0, 0, 0, 0,
ax_anim 1, 0, 163, 0, -10, 0, 0,
ax_anim 2, 0, 163, 0, -16, 0, 0,
ax_anim 3, 0, 163, 0, -20, 0, 0,
ax_anim 4, 0, 163, 0, -21, 0, 0,
ax_anim 4, 0, 162, 0, -23, 0, 0,
ax_anim 3, 0, 164, 0, -22, 0, 0,
ax_anim 2, 0, 164, 0, -18, 0, 0,
ax_anim 1, 0, 164, 0, -12, 0, 0,
ax_anim 2, 2, 162, 0, 0, 0, 0,
ax_anim_terminator
sIgglybuffAnims_11_2:
ax_anim 2, 0, 165, 0, 0, 0, 0,
ax_anim 1, 0, 166, 0, -10, 0, 0,
ax_anim 2, 0, 166, 0, -16, 0, 0,
ax_anim 3, 0, 166, 0, -20, 0, 0,
ax_anim 4, 0, 166, 0, -21, 0, 0,
ax_anim 4, 0, 165, 0, -23, 0, 0,
ax_anim 3, 0, 167, 0, -22, 0, 0,
ax_anim 2, 0, 167, 0, -18, 0, 0,
ax_anim 1, 0, 167, 0, -12, 0, 0,
ax_anim 2, 2, 165, 0, 0, 0, 0,
ax_anim_terminator
sIgglybuffAnims_11_3:
ax_anim 2, 0, 168, 0, 0, 0, 0,
ax_anim 1, 0, 169, 0, -10, 0, 0,
ax_anim 2, 0, 169, 0, -16, 0, 0,
ax_anim 3, 0, 169, 0, -20, 0, 0,
ax_anim 4, 0, 169, 0, -21, 0, 0,
ax_anim 4, 0, 168, 0, -23, 0, 0,
ax_anim 3, 0, 170, 0, -22, 0, 0,
ax_anim 2, 0, 170, 0, -18, 0, 0,
ax_anim 1, 0, 170, 0, -12, 0, 0,
ax_anim 2, 2, 168, 0, 0, 0, 0,
ax_anim_terminator
sIgglybuffAnims_11_4:
ax_anim 2, 0, 171, 0, 0, 0, 0,
ax_anim 1, 0, 172, 0, -10, 0, 0,
ax_anim 2, 0, 172, 0, -16, 0, 0,
ax_anim 3, 0, 172, 0, -20, 0, 0,
ax_anim 4, 0, 172, 0, -21, 0, 0,
ax_anim 4, 0, 171, 0, -23, 0, 0,
ax_anim 3, 0, 173, 0, -22, 0, 0,
ax_anim 2, 0, 173, 0, -17, 0, 0,
ax_anim 1, 0, 173, 0, -11, 0, 0,
ax_anim 2, 2, 171, 0, 0, 0, 0,
ax_anim_terminator
sIgglybuffAnims_11_5:
ax_anim 2, 0, 174, 0, 0, 0, 0,
ax_anim 1, 0, 175, 0, -10, 0, 0,
ax_anim 2, 0, 175, 0, -16, 0, 0,
ax_anim 3, 0, 175, 0, -20, 0, 0,
ax_anim 4, 0, 175, 0, -21, 0, 0,
ax_anim 4, 0, 174, 0, -23, 0, 0,
ax_anim 3, 0, 176, 0, -22, 0, 0,
ax_anim 2, 0, 176, 0, -18, 0, 0,
ax_anim 1, 0, 176, 0, -12, 0, 0,
ax_anim 2, 2, 174, 0, 0, 0, 0,
ax_anim_terminator
sIgglybuffAnims_11_6:
ax_anim 2, 0, 177, 0, 0, 0, 0,
ax_anim 1, 0, 178, 0, -10, 0, 0,
ax_anim 2, 0, 178, 0, -16, 0, 0,
ax_anim 3, 0, 178, 0, -20, 0, 0,
ax_anim 4, 0, 178, 0, -21, 0, 0,
ax_anim 4, 0, 177, 0, -23, 0, 0,
ax_anim 3, 0, 179, 0, -22, 0, 0,
ax_anim 2, 0, 179, 0, -17, 0, 0,
ax_anim 1, 0, 179, 0, -11, 0, 0,
ax_anim 2, 2, 177, 0, 0, 0, 0,
ax_anim_terminator
sIgglybuffAnims_11_7:
ax_anim 2, 0, 180, 0, 0, 0, 0,
ax_anim 1, 0, 181, 0, -10, 0, 0,
ax_anim 2, 0, 181, 0, -16, 0, 0,
ax_anim 3, 0, 181, 0, -20, 0, 0,
ax_anim 4, 0, 181, 0, -21, 0, 0,
ax_anim 4, 0, 180, 0, -23, 0, 0,
ax_anim 3, 0, 182, 0, -22, 0, 0,
ax_anim 2, 0, 182, 0, -18, 0, 0,
ax_anim 1, 0, 182, 0, -12, 0, 0,
ax_anim 2, 2, 180, 0, 0, 0, 0,
ax_anim_terminator
sIgglybuffAnims_11_8:
ax_anim 2, 0, 183, 0, 0, 0, 0,
ax_anim 1, 0, 184, 0, -10, 0, 0,
ax_anim 2, 0, 184, 0, -16, 0, 0,
ax_anim 3, 0, 184, 0, -20, 0, 0,
ax_anim 4, 0, 184, 0, -21, 0, 0,
ax_anim 4, 0, 183, 0, -23, 0, 0,
ax_anim 3, 0, 185, 0, -22, 0, 0,
ax_anim 2, 0, 185, 0, -18, 0, 0,
ax_anim 1, 0, 185, 0, -12, 0, 0,
ax_anim 2, 2, 183, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sIgglybuffAnims_12_1:
ax_anim 2, 0, 186, 1, 0, 1, 0,
ax_anim 2, 0, 186, 0, 0, 0, 0,
ax_anim 2, 0, 186, 1, 0, 1, 0,
ax_anim 2, 0, 186, 0, 0, 0, 0,
ax_anim 2, 0, 186, 1, 0, 1, 0,
ax_anim 2, 2, 186, 0, 0, 0, 0,
ax_anim 2, 0, 186, 1, 0, 1, 0,
ax_anim 2, 0, 186, 0, 0, 0, 0,
ax_anim 2, 0, 186, 1, 0, 1, 0,
ax_anim 2, 1, 186, 0, 0, 0, 0,
ax_anim_terminator
sIgglybuffAnims_12_2:
ax_anim 2, 0, 193, 1, -1, 1, -1,
ax_anim 2, 0, 193, 0, 0, 0, 0,
ax_anim 2, 0, 193, 1, -1, 1, -1,
ax_anim 2, 0, 193, 0, 0, 0, 0,
ax_anim 2, 0, 193, 1, -1, 1, -1,
ax_anim 2, 2, 193, 0, 0, 0, 0,
ax_anim 2, 0, 193, 1, -1, 1, -1,
ax_anim 2, 0, 193, 0, 0, 0, 0,
ax_anim 2, 0, 193, 1, -1, 1, -1,
ax_anim 2, 1, 193, 0, 0, 0, 0,
ax_anim_terminator
sIgglybuffAnims_12_3:
ax_anim 2, 0, 192, 0, -1, 0, -1,
ax_anim 2, 0, 192, 0, 0, 0, 0,
ax_anim 2, 0, 192, 0, -1, 0, -1,
ax_anim 2, 0, 192, 0, 0, 0, 0,
ax_anim 2, 0, 192, 0, -1, 0, -1,
ax_anim 2, 2, 192, 0, 0, 0, 0,
ax_anim 2, 0, 192, 0, -1, 0, -1,
ax_anim 2, 0, 192, 0, 0, 0, 0,
ax_anim 2, 0, 192, 0, -1, 0, -1,
ax_anim 2, 1, 192, 0, 0, 0, 0,
ax_anim_terminator
sIgglybuffAnims_12_4:
ax_anim 2, 0, 191, -1, -1, -1, -1,
ax_anim 2, 0, 191, 0, 0, 0, 0,
ax_anim 2, 0, 191, -1, -1, -1, -1,
ax_anim 2, 0, 191, 0, 0, 0, 0,
ax_anim 2, 0, 191, -1, -1, -1, -1,
ax_anim 2, 2, 191, 0, 0, 0, 0,
ax_anim 2, 0, 191, -1, -1, -1, -1,
ax_anim 2, 0, 191, 0, 0, 0, 0,
ax_anim 2, 0, 191, -1, -1, -1, -1,
ax_anim 2, 1, 191, 0, 0, 0, 0,
ax_anim_terminator
sIgglybuffAnims_12_5:
ax_anim 2, 0, 190, 1, 0, 1, 0,
ax_anim 2, 0, 190, 0, 0, 0, 0,
ax_anim 2, 0, 190, 1, 0, 1, 0,
ax_anim 2, 0, 190, 0, 0, 0, 0,
ax_anim 2, 0, 190, 1, 0, 1, 0,
ax_anim 2, 2, 190, 0, 0, 0, 0,
ax_anim 2, 0, 190, 1, 0, 1, 0,
ax_anim 2, 0, 190, 0, 0, 0, 0,
ax_anim 2, 0, 190, 1, 0, 1, 0,
ax_anim 2, 1, 190, 0, 0, 0, 0,
ax_anim_terminator
sIgglybuffAnims_12_6:
ax_anim 2, 0, 189, 1, -1, 1, -1,
ax_anim 2, 0, 189, 0, 0, 0, 0,
ax_anim 2, 0, 189, 1, -1, 1, -1,
ax_anim 2, 0, 189, 0, 0, 0, 0,
ax_anim 2, 0, 189, 1, -1, 1, -1,
ax_anim 2, 2, 189, 0, 0, 0, 0,
ax_anim 2, 0, 189, 1, -1, 1, -1,
ax_anim 2, 0, 189, 0, 0, 0, 0,
ax_anim 2, 0, 189, 1, -1, 1, -1,
ax_anim 2, 1, 189, 0, 0, 0, 0,
ax_anim_terminator
sIgglybuffAnims_12_7:
ax_anim 2, 0, 188, 0, -1, 0, -1,
ax_anim 2, 0, 188, 0, 0, 0, 0,
ax_anim 2, 0, 188, 0, -1, 0, -1,
ax_anim 2, 0, 188, 0, 0, 0, 0,
ax_anim 2, 0, 188, 0, -1, 0, -1,
ax_anim 2, 2, 188, 0, 0, 0, 0,
ax_anim 2, 0, 188, 0, -1, 0, -1,
ax_anim 2, 0, 188, 0, 0, 0, 0,
ax_anim 2, 0, 188, 0, -1, 0, -1,
ax_anim 2, 1, 188, 0, 0, 0, 0,
ax_anim_terminator
sIgglybuffAnims_12_8:
ax_anim 2, 0, 187, -1, -1, -1, -1,
ax_anim 2, 0, 187, 0, 0, 0, 0,
ax_anim 2, 0, 187, -1, -1, -1, -1,
ax_anim 2, 0, 187, 0, 0, 0, 0,
ax_anim 2, 0, 187, -1, -1, -1, -1,
ax_anim 2, 2, 187, 0, 0, 0, 0,
ax_anim 2, 0, 187, -1, -1, -1, -1,
ax_anim 2, 0, 187, 0, 0, 0, 0,
ax_anim 2, 0, 187, -1, -1, -1, -1,
ax_anim 2, 1, 187, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sIgglybuffAnims_13_1:
ax_anim 2, 0, 194, 0, 0, 0, 0,
ax_anim 2, 0, 195, 0, 0, 0, 0,
ax_anim 2, 0, 196, 0, 0, 0, 0,
ax_anim 2, 0, 197, 0, 0, 0, 0,
ax_anim 2, 0, 198, 0, 0, 0, 0,
ax_anim 2, 0, 199, 0, 0, 0, 0,
ax_anim 2, 0, 200, 0, 0, 0, 0,
ax_anim 2, 0, 201, 0, 0, 0, 0,
ax_anim 2, 2, 194, 0, 0, 0, 0,
ax_anim_terminator
sIgglybuffAnims_13_2:
ax_anim 2, 0, 201, 0, 0, 0, 0,
ax_anim 2, 0, 194, 0, 0, 0, 0,
ax_anim 2, 0, 195, 0, 0, 0, 0,
ax_anim 2, 0, 196, 0, 0, 0, 0,
ax_anim 2, 0, 197, 0, 0, 0, 0,
ax_anim 2, 0, 198, 0, 0, 0, 0,
ax_anim 2, 0, 199, 0, 0, 0, 0,
ax_anim 2, 0, 200, 0, 0, 0, 0,
ax_anim 2, 2, 201, 0, 0, 0, 0,
ax_anim_terminator
sIgglybuffAnims_13_3:
ax_anim 2, 0, 200, 0, 0, 0, 0,
ax_anim 2, 0, 201, 0, 0, 0, 0,
ax_anim 2, 0, 194, 0, 0, 0, 0,
ax_anim 2, 0, 195, 0, 0, 0, 0,
ax_anim 2, 0, 196, 0, 0, 0, 0,
ax_anim 2, 0, 197, 0, 0, 0, 0,
ax_anim 2, 0, 198, 0, 0, 0, 0,
ax_anim 2, 0, 199, 0, 0, 0, 0,
ax_anim 2, 2, 200, 0, 0, 0, 0,
ax_anim_terminator
sIgglybuffAnims_13_4:
ax_anim 2, 0, 199, 0, 0, 0, 0,
ax_anim 2, 0, 200, 0, 0, 0, 0,
ax_anim 2, 0, 201, 0, 0, 0, 0,
ax_anim 2, 0, 194, 0, 0, 0, 0,
ax_anim 2, 0, 195, 0, 0, 0, 0,
ax_anim 2, 0, 196, 0, 0, 0, 0,
ax_anim 2, 0, 197, 0, 0, 0, 0,
ax_anim 2, 0, 198, 0, 0, 0, 0,
ax_anim 2, 2, 199, 0, 0, 0, 0,
ax_anim_terminator
sIgglybuffAnims_13_5:
ax_anim 2, 0, 198, 0, 0, 0, 0,
ax_anim 2, 0, 199, 0, 0, 0, 0,
ax_anim 2, 0, 200, 0, 0, 0, 0,
ax_anim 2, 0, 201, 0, 0, 0, 0,
ax_anim 2, 0, 194, 0, 0, 0, 0,
ax_anim 2, 0, 195, 0, 0, 0, 0,
ax_anim 2, 0, 196, 0, 0, 0, 0,
ax_anim 2, 0, 197, 0, 0, 0, 0,
ax_anim 2, 2, 198, 0, 0, 0, 0,
ax_anim_terminator
sIgglybuffAnims_13_6:
ax_anim 2, 0, 197, 0, 0, 0, 0,
ax_anim 2, 0, 198, 0, 0, 0, 0,
ax_anim 2, 0, 199, 0, 0, 0, 0,
ax_anim 2, 0, 200, 0, 0, 0, 0,
ax_anim 2, 0, 201, 0, 0, 0, 0,
ax_anim 2, 0, 194, 0, 0, 0, 0,
ax_anim 2, 0, 195, 0, 0, 0, 0,
ax_anim 2, 0, 196, 0, 0, 0, 0,
ax_anim 2, 2, 197, 0, 0, 0, 0,
ax_anim_terminator
sIgglybuffAnims_13_7:
ax_anim 2, 0, 196, 0, 0, 0, 0,
ax_anim 2, 0, 197, 0, 0, 0, 0,
ax_anim 2, 0, 198, 0, 0, 0, 0,
ax_anim 2, 0, 199, 0, 0, 0, 0,
ax_anim 2, 0, 200, 0, 0, 0, 0,
ax_anim 2, 0, 201, 0, 0, 0, 0,
ax_anim 2, 0, 194, 0, 0, 0, 0,
ax_anim 2, 0, 195, 0, 0, 0, 0,
ax_anim 2, 2, 196, 0, 0, 0, 0,
ax_anim_terminator
sIgglybuffAnims_13_8:
ax_anim 2, 0, 195, 0, 0, 0, 0,
ax_anim 2, 0, 196, 0, 0, 0, 0,
ax_anim 2, 0, 197, 0, 0, 0, 0,
ax_anim 2, 0, 198, 0, 0, 0, 0,
ax_anim 2, 0, 199, 0, 0, 0, 0,
ax_anim 2, 0, 200, 0, 0, 0, 0,
ax_anim 2, 0, 201, 0, 0, 0, 0,
ax_anim 2, 0, 194, 0, 0, 0, 0,
ax_anim 2, 2, 195, 0, 0, 0, 0,
ax_anim_terminator
sIgglybuffGfx1:
.incbin "baserom.gba", 0xC96BB8, 0x80
sIgglybuffSprites1:
ax_sprite sIgglybuffGfx1, 0x80
ax_sprite_terminator
sIgglybuffGfx2:
.incbin "baserom.gba", 0xC96C48, 0x100
sIgglybuffSprites2:
ax_sprite sIgglybuffGfx2, 0x100
ax_sprite_terminator
sIgglybuffGfx3:
.incbin "baserom.gba", 0xC96D58, 0x80
sIgglybuffSprites3:
ax_sprite sIgglybuffGfx3, 0x80
ax_sprite_terminator
sIgglybuffGfx4:
.incbin "baserom.gba", 0xC96DE8, 0x80
sIgglybuffSprites4:
ax_sprite sIgglybuffGfx4, 0x80
ax_sprite_terminator
sIgglybuffGfx5:
.incbin "baserom.gba", 0xC96E78, 0x100
sIgglybuffSprites5:
ax_sprite sIgglybuffGfx5, 0x100
ax_sprite_terminator
sIgglybuffGfx6:
.incbin "baserom.gba", 0xC96F88, 0x80
sIgglybuffSprites6:
ax_sprite sIgglybuffGfx6, 0x80
ax_sprite_terminator
sIgglybuffGfx7:
.incbin "baserom.gba", 0xC97018, 0x80
sIgglybuffSprites7:
ax_sprite sIgglybuffGfx7, 0x80
ax_sprite_terminator
sIgglybuffGfx8:
.incbin "baserom.gba", 0xC970A8, 0x100
sIgglybuffSprites8:
ax_sprite sIgglybuffGfx8, 0x100
ax_sprite_terminator
sIgglybuffGfx9:
.incbin "baserom.gba", 0xC971B8, 0x80
sIgglybuffSprites9:
ax_sprite sIgglybuffGfx9, 0x80
ax_sprite_terminator
sIgglybuffGfx10:
.incbin "baserom.gba", 0xC97248, 0x80
sIgglybuffSprites10:
ax_sprite sIgglybuffGfx10, 0x80
ax_sprite_terminator
sIgglybuffGfx11:
.incbin "baserom.gba", 0xC972D8, 0x100
sIgglybuffSprites11:
ax_sprite sIgglybuffGfx11, 0x100
ax_sprite_terminator
sIgglybuffGfx12:
.incbin "baserom.gba", 0xC973E8, 0x80
sIgglybuffSprites12:
ax_sprite sIgglybuffGfx12, 0x80
ax_sprite_terminator
sIgglybuffGfx13:
.incbin "baserom.gba", 0xC97478, 0x80
sIgglybuffSprites13:
ax_sprite sIgglybuffGfx13, 0x80
ax_sprite_terminator
sIgglybuffGfx14:
.incbin "baserom.gba", 0xC97508, 0x100
sIgglybuffSprites14:
ax_sprite sIgglybuffGfx14, 0x100
ax_sprite_terminator
sIgglybuffGfx15:
.incbin "baserom.gba", 0xC97618, 0x80
sIgglybuffSprites15:
ax_sprite sIgglybuffGfx15, 0x80
ax_sprite_terminator
sIgglybuffGfx16:
.incbin "baserom.gba", 0xC976A8, 0x80
sIgglybuffSprites16:
ax_sprite sIgglybuffGfx16, 0x80
ax_sprite_terminator
sIgglybuffGfx17:
.incbin "baserom.gba", 0xC97738, 0x80
sIgglybuffSprites17:
ax_sprite sIgglybuffGfx17, 0x80
ax_sprite_terminator
sIgglybuffGfx18:
.incbin "baserom.gba", 0xC977C8, 0x80
sIgglybuffSprites18:
ax_sprite sIgglybuffGfx18, 0x80
ax_sprite_terminator
sIgglybuffGfx19:
.incbin "baserom.gba", 0xC97858, 0x80
sIgglybuffSprites19:
ax_sprite sIgglybuffGfx19, 0x80
ax_sprite_terminator
sIgglybuffGfx20:
.incbin "baserom.gba", 0xC978E8, 0x80
sIgglybuffSprites20:
ax_sprite sIgglybuffGfx20, 0x80
ax_sprite_terminator
sIgglybuffGfx21:
.incbin "baserom.gba", 0xC97978, 0xC0
sIgglybuffSprites21:
ax_sprite sIgglybuffGfx21, 0xc0
ax_sprite 0, 0x40
ax_sprite_terminator
sIgglybuffGfx22:
.incbin "baserom.gba", 0xC97A50, 0x80
sIgglybuffSprites22:
ax_sprite sIgglybuffGfx22, 0x80
ax_sprite_terminator
sIgglybuffGfx23:
.incbin "baserom.gba", 0xC97AE0, 0xC0
sIgglybuffSprites23:
ax_sprite sIgglybuffGfx23, 0xc0
ax_sprite 0, 0x40
ax_sprite_terminator
sIgglybuffGfx24:
.incbin "baserom.gba", 0xC97BB8, 0x80
sIgglybuffSprites24:
ax_sprite sIgglybuffGfx24, 0x80
ax_sprite_terminator
sIgglybuffGfx25:
.incbin "baserom.gba", 0xC97C48, 0xC0
sIgglybuffSprites25:
ax_sprite sIgglybuffGfx25, 0xc0
ax_sprite 0, 0x40
ax_sprite_terminator
sIgglybuffGfx26:
.incbin "baserom.gba", 0xC97D20, 0x80
sIgglybuffSprites26:
ax_sprite sIgglybuffGfx26, 0x80
ax_sprite_terminator
sIgglybuffGfx27:
.incbin "baserom.gba", 0xC97DB0, 0xC0
sIgglybuffSprites27:
ax_sprite sIgglybuffGfx27, 0xc0
ax_sprite 0, 0x40
ax_sprite_terminator
sIgglybuffGfx28:
.incbin "baserom.gba", 0xC97E88, 0x80
sIgglybuffSprites28:
ax_sprite sIgglybuffGfx28, 0x80
ax_sprite_terminator
sIgglybuffGfx29:
.incbin "baserom.gba", 0xC97F18, 0xC0
sIgglybuffSprites29:
ax_sprite sIgglybuffGfx29, 0xc0
ax_sprite 0, 0x40
ax_sprite_terminator
sIgglybuffGfx30:
.incbin "baserom.gba", 0xC97FF0, 0x80
sIgglybuffSprites30:
ax_sprite sIgglybuffGfx30, 0x80
ax_sprite_terminator
sIgglybuffGfx31:
.incbin "baserom.gba", 0xC98080, 0x80
sIgglybuffSprites31:
ax_sprite sIgglybuffGfx31, 0x80
ax_sprite_terminator
sIgglybuffGfx32:
.incbin "baserom.gba", 0xC98110, 0x80
sIgglybuffSprites32:
ax_sprite sIgglybuffGfx32, 0x80
ax_sprite_terminator
sIgglybuffGfx33:
.incbin "baserom.gba", 0xC981A0, 0x200
sIgglybuffSprites33:
ax_sprite sIgglybuffGfx33, 0x200
ax_sprite_terminator
sIgglybuffGfx34:
.incbin "baserom.gba", 0xC983B0, 0x200
sIgglybuffSprites34:
ax_sprite sIgglybuffGfx34, 0x200
ax_sprite_terminator
sIgglybuffGfx35:
.incbin "baserom.gba", 0xC985C0, 0x200
sIgglybuffSprites35:
ax_sprite sIgglybuffGfx35, 0x200
ax_sprite_terminator
sIgglybuffGfx36:
.incbin "baserom.gba", 0xC987D0, 0x200
sIgglybuffSprites36:
ax_sprite sIgglybuffGfx36, 0x200
ax_sprite_terminator
sIgglybuffGfx37:
.incbin "baserom.gba", 0xC989E0, 0x200
sIgglybuffSprites37:
ax_sprite sIgglybuffGfx37, 0x200
ax_sprite_terminator
sAxPosesIgglybuff:
.4byte sIgglybuffPose1
.4byte sIgglybuffPose2
.4byte sIgglybuffPose3
.4byte sIgglybuffPose4
.4byte sIgglybuffPose5
.4byte sIgglybuffPose6
.4byte sIgglybuffPose7
.4byte sIgglybuffPose8
.4byte sIgglybuffPose9
.4byte sIgglybuffPose10
.4byte sIgglybuffPose11
.4byte sIgglybuffPose12
.4byte sIgglybuffPose13
.4byte sIgglybuffPose14
.4byte sIgglybuffPose15
.4byte sIgglybuffPose16
.4byte sIgglybuffPose17
.4byte sIgglybuffPose18
.4byte sIgglybuffPose19
.4byte sIgglybuffPose20
.4byte sIgglybuffPose21
.4byte sIgglybuffPose22
.4byte sIgglybuffPose23
.4byte sIgglybuffPose24
.4byte sIgglybuffPose25
.4byte sIgglybuffPose26
.4byte sIgglybuffPose27
.4byte sIgglybuffPose28
.4byte sIgglybuffPose29
.4byte sIgglybuffPose30
.4byte sIgglybuffPose31
.4byte sIgglybuffPose32
.4byte sIgglybuffPose33
.4byte sIgglybuffPose34
.4byte sIgglybuffPose35
.4byte sIgglybuffPose36
.4byte sIgglybuffPose37
.4byte sIgglybuffPose38
.4byte sIgglybuffPose39
.4byte sIgglybuffPose40
.4byte sIgglybuffPose41
.4byte sIgglybuffPose42
.4byte sIgglybuffPose43
.4byte sIgglybuffPose44
.4byte sIgglybuffPose45
.4byte sIgglybuffPose46
.4byte sIgglybuffPose47
.4byte sIgglybuffPose48
.4byte sIgglybuffPose49
.4byte sIgglybuffPose50
.4byte sIgglybuffPose51
.4byte sIgglybuffPose52
.4byte sIgglybuffPose53
.4byte sIgglybuffPose54
.4byte sIgglybuffPose55
.4byte sIgglybuffPose56
.4byte sIgglybuffPose57
.4byte sIgglybuffPose58
.4byte sIgglybuffPose59
.4byte sIgglybuffPose60
.4byte sIgglybuffPose61
.4byte sIgglybuffPose62
.4byte sIgglybuffPose63
.4byte sIgglybuffPose64
.4byte sIgglybuffPose65
.4byte sIgglybuffPose66
.4byte sIgglybuffPose67
.4byte sIgglybuffPose68
.4byte sIgglybuffPose69
.4byte sIgglybuffPose70
.4byte sIgglybuffPose71
.4byte sIgglybuffPose72
.4byte sIgglybuffPose73
.4byte sIgglybuffPose74
.4byte sIgglybuffPose75
.4byte sIgglybuffPose76
.4byte sIgglybuffPose77
.4byte sIgglybuffPose78
.4byte sIgglybuffPose79
.4byte sIgglybuffPose80
.4byte sIgglybuffPose81
.4byte sIgglybuffPose82
.4byte sIgglybuffPose83
.4byte sIgglybuffPose84
.4byte sIgglybuffPose85
.4byte sIgglybuffPose86
.4byte sIgglybuffPose87
.4byte sIgglybuffPose88
.4byte sIgglybuffPose89
.4byte sIgglybuffPose90
.4byte sIgglybuffPose91
.4byte sIgglybuffPose92
.4byte sIgglybuffPose93
.4byte sIgglybuffPose94
.4byte sIgglybuffPose95
.4byte sIgglybuffPose96
.4byte sIgglybuffPose97
.4byte sIgglybuffPose98
.4byte sIgglybuffPose99
.4byte sIgglybuffPose100
.4byte sIgglybuffPose101
.4byte sIgglybuffPose102
.4byte sIgglybuffPose103
.4byte sIgglybuffPose104
.4byte sIgglybuffPose105
.4byte sIgglybuffPose106
.4byte sIgglybuffPose107
.4byte sIgglybuffPose108
.4byte sIgglybuffPose109
.4byte sIgglybuffPose110
.4byte sIgglybuffPose111
.4byte sIgglybuffPose112
.4byte sIgglybuffPose113
.4byte sIgglybuffPose114
.4byte sIgglybuffPose115
.4byte sIgglybuffPose116
.4byte sIgglybuffPose117
.4byte sIgglybuffPose118
.4byte sIgglybuffPose119
.4byte sIgglybuffPose120
.4byte sIgglybuffPose121
.4byte sIgglybuffPose122
.4byte sIgglybuffPose123
.4byte sIgglybuffPose124
.4byte sIgglybuffPose125
.4byte sIgglybuffPose126
.4byte sIgglybuffPose127
.4byte sIgglybuffPose128
.4byte sIgglybuffPose129
.4byte sIgglybuffPose130
.4byte sIgglybuffPose131
.4byte sIgglybuffPose132
.4byte sIgglybuffPose133
.4byte sIgglybuffPose134
.4byte sIgglybuffPose135
.4byte sIgglybuffPose136
.4byte sIgglybuffPose137
.4byte sIgglybuffPose138
.4byte sIgglybuffPose139
.4byte sIgglybuffPose140
.4byte sIgglybuffPose141
.4byte sIgglybuffPose142
.4byte sIgglybuffPose143
.4byte sIgglybuffPose144
.4byte sIgglybuffPose145
.4byte sIgglybuffPose146
.4byte sIgglybuffPose147
.4byte sIgglybuffPose148
.4byte sIgglybuffPose149
.4byte sIgglybuffPose150
.4byte sIgglybuffPose151
.4byte sIgglybuffPose152
.4byte sIgglybuffPose153
.4byte sIgglybuffPose154
.4byte sIgglybuffPose155
.4byte sIgglybuffPose156
.4byte sIgglybuffPose157
.4byte sIgglybuffPose158
.4byte sIgglybuffPose159
.4byte sIgglybuffPose160
.4byte sIgglybuffPose161
.4byte sIgglybuffPose162
.4byte sIgglybuffPose163
.4byte sIgglybuffPose164
.4byte sIgglybuffPose165
.4byte sIgglybuffPose166
.4byte sIgglybuffPose167
.4byte sIgglybuffPose168
.4byte sIgglybuffPose169
.4byte sIgglybuffPose170
.4byte sIgglybuffPose171
.4byte sIgglybuffPose172
.4byte sIgglybuffPose173
.4byte sIgglybuffPose174
.4byte sIgglybuffPose175
.4byte sIgglybuffPose176
.4byte sIgglybuffPose177
.4byte sIgglybuffPose178
.4byte sIgglybuffPose179
.4byte sIgglybuffPose180
.4byte sIgglybuffPose181
.4byte sIgglybuffPose182
.4byte sIgglybuffPose183
.4byte sIgglybuffPose184
.4byte sIgglybuffPose185
.4byte sIgglybuffPose186
.4byte sIgglybuffPose187
.4byte sIgglybuffPose188
.4byte sIgglybuffPose189
.4byte sIgglybuffPose190
.4byte sIgglybuffPose191
.4byte sIgglybuffPose192
.4byte sIgglybuffPose193
.4byte sIgglybuffPose194
.4byte sIgglybuffPose195
.4byte sIgglybuffPose196
.4byte sIgglybuffPose197
.4byte sIgglybuffPose198
.4byte sIgglybuffPose199
.4byte sIgglybuffPose200
.4byte sIgglybuffPose201
.4byte sIgglybuffPose202
sAxPositionsIgglybuff:
.2byte   -1,   -3, 	  -7,   -2, 	   5,   -2, 	  -1,   -4
.2byte   -1,   -9, 	  -6,   -6, 	   4,   -6, 	  -1,   -8
.2byte   -1,   -1, 	  -7,   -3, 	   5,   -3, 	  -1,   -3
.2byte    2,   -3, 	   4,   -5, 	  -6,   -2, 	   0,   -4
.2byte    2,   -7, 	   5,   -9, 	  -5,   -5, 	   0,   -8
.2byte    2,   -1, 	   5,   -6, 	  -7,   -2, 	  -1,   -3
.2byte    5,   -4, 	   0,   -7, 	  -2,   -1, 	  -1,   -5
.2byte    5,   -9, 	  -1,  -10, 	  -2,   -5, 	  -1,   -9
.2byte    5,   -3, 	  -1,   -6, 	  -2,   -2, 	  -1,   -4
.2byte    2,   -6, 	  -4,   -6, 	   4,   -2, 	  -1,   -5
.2byte    2,   -9, 	  -5,   -8, 	   4,   -4, 	  -1,   -8
.2byte    1,   -4, 	  -5,   -5, 	   5,   -2, 	  -2,   -4
.2byte   -1,   -6, 	   5,   -4, 	  -7,   -4, 	  -1,   -5
.2byte   -1,   -9, 	   4,   -7, 	  -6,   -7, 	  -1,   -8
.2byte   -1,   -5, 	   5,   -4, 	  -7,   -4, 	  -1,   -3
.2byte   -4,   -6, 	   2,   -6, 	  -6,   -2, 	  -1,   -5
.2byte   -4,   -9, 	   3,   -8, 	  -6,   -4, 	  -1,   -8
.2byte   -3,   -4, 	   3,   -5, 	  -7,   -2, 	   0,   -4
.2byte   -7,   -4, 	  -2,   -7, 	   0,   -1, 	  -1,   -5
.2byte   -7,   -9, 	  -1,  -10, 	   0,   -5, 	  -1,   -9
.2byte   -7,   -3, 	  -1,   -6, 	   0,   -2, 	  -1,   -4
.2byte   -4,   -3, 	  -6,   -5, 	   4,   -2, 	  -2,   -4
.2byte   -4,   -7, 	  -7,   -9, 	   3,   -5, 	  -2,   -8
.2byte   -4,   -1, 	  -7,   -6, 	   5,   -2, 	  -1,   -3
.2byte   -1,   -3, 	  -6,   -3, 	   4,   -3, 	  -1,   -6
.2byte   -1,   -9, 	  -6,   -6, 	   4,   -6, 	  -1,   -8
.2byte   -1,   -1, 	  -7,   -3, 	   5,   -3, 	  -1,   -3
.2byte    2,   -2, 	   4,   -8, 	  -6,   -2, 	  -1,   -5
.2byte    2,   -7, 	   5,   -9, 	  -5,   -5, 	   0,   -8
.2byte    2,   -1, 	   5,   -6, 	  -7,   -2, 	  -1,   -3
.2byte    2,   -1, 	   0,   -6, 	   0,   -2, 	  -1,   -5
.2byte    5,   -9, 	  -1,  -10, 	  -2,   -5, 	  -1,   -9
.2byte    5,   -3, 	  -1,   -6, 	  -2,   -2, 	  -1,   -4
.2byte    0,   -4, 	  -5,   -6, 	   5,   -3, 	  -2,   -5
.2byte    2,   -9, 	  -5,   -8, 	   4,   -4, 	  -1,   -8
.2byte    1,   -4, 	  -5,   -5, 	   5,   -2, 	  -2,   -4
.2byte   -1,   -5, 	   5,   -4, 	  -7,   -4, 	  -1,   -6
.2byte   -1,   -9, 	   4,   -7, 	  -6,   -7, 	  -1,   -8
.2byte   -1,   -5, 	   5,   -4, 	  -7,   -4, 	  -1,   -3
.2byte   -2,   -4, 	   3,   -6, 	  -7,   -3, 	   0,   -5
.2byte   -4,   -9, 	   3,   -8, 	  -6,   -4, 	  -1,   -8
.2byte   -3,   -4, 	   3,   -5, 	  -7,   -2, 	   0,   -4
.2byte   -4,   -1, 	  -2,   -6, 	  -2,   -2, 	  -1,   -5
.2byte   -7,   -9, 	  -1,  -10, 	   0,   -5, 	  -1,   -9
.2byte   -7,   -3, 	  -1,   -6, 	   0,   -2, 	  -1,   -4
.2byte   -4,   -2, 	  -6,   -8, 	   4,   -2, 	  -1,   -5
.2byte   -4,   -7, 	  -7,   -9, 	   3,   -5, 	  -2,   -8
.2byte   -4,   -1, 	  -7,   -6, 	   5,   -2, 	  -1,   -3
.2byte   -1,   -3, 	  -6,   -3, 	   4,   -3, 	  -1,   -6
.2byte   -1,   -9, 	  -6,   -6, 	   4,   -6, 	  -1,   -8
.2byte   -1,   -1, 	  -7,   -3, 	   5,   -3, 	  -1,   -3
.2byte    2,   -2, 	   4,   -8, 	  -6,   -2, 	  -1,   -5
.2byte    2,   -7, 	   5,   -9, 	  -5,   -5, 	   0,   -8
.2byte    2,   -1, 	   5,   -6, 	  -7,   -2, 	  -1,   -3
.2byte    2,   -1, 	   0,   -6, 	   0,   -2, 	  -1,   -5
.2byte    5,   -9, 	  -1,  -10, 	  -2,   -5, 	  -1,   -9
.2byte    5,   -3, 	  -1,   -6, 	  -2,   -2, 	  -1,   -4
.2byte    0,   -4, 	  -5,   -6, 	   5,   -3, 	  -2,   -5
.2byte    2,   -9, 	  -5,   -8, 	   4,   -4, 	  -1,   -8
.2byte    1,   -4, 	  -5,   -5, 	   5,   -2, 	  -2,   -4
.2byte   -1,   -5, 	   5,   -4, 	  -7,   -4, 	  -1,   -6
.2byte   -1,   -9, 	   4,   -7, 	  -6,   -7, 	  -1,   -8
.2byte   -1,   -5, 	   5,   -4, 	  -7,   -4, 	  -1,   -3
.2byte   -2,   -4, 	   3,   -6, 	  -7,   -3, 	   0,   -5
.2byte   -4,   -9, 	   3,   -8, 	  -6,   -4, 	  -1,   -8
.2byte   -3,   -4, 	   3,   -5, 	  -7,   -2, 	   0,   -4
.2byte   -4,   -1, 	  -2,   -6, 	  -2,   -2, 	  -1,   -5
.2byte   -7,   -9, 	  -1,  -10, 	   0,   -5, 	  -1,   -9
.2byte   -7,   -3, 	  -1,   -6, 	   0,   -2, 	  -1,   -4
.2byte   -4,   -2, 	  -6,   -8, 	   4,   -2, 	  -1,   -5
.2byte   -4,   -7, 	  -7,   -9, 	   3,   -5, 	  -2,   -8
.2byte   -4,   -1, 	  -7,   -6, 	   5,   -2, 	  -1,   -3
.2byte   -1,   -3, 	  -7,   -2, 	   5,   -2, 	  -1,   -4
.2byte   -1,   -5, 	  -6,   -3, 	   4,   -3, 	  -1,   -6
.2byte   -1,   -2, 	  -7,   -3, 	   5,   -3, 	  -1,   -4
.2byte    2,   -3, 	   4,   -5, 	  -6,   -2, 	   0,   -4
.2byte    2,   -5, 	   5,   -5, 	  -4,   -2, 	  -1,   -5
.2byte    2,   -2, 	   5,   -4, 	  -6,   -3, 	  -1,   -5
.2byte    5,   -4, 	   0,   -7, 	  -2,   -1, 	  -1,   -5
.2byte    5,   -5, 	   0,   -6, 	  -1,   -2, 	  -1,   -6
.2byte    5,   -3, 	  -1,   -5, 	  -2,   -2, 	  -1,   -4
.2byte    2,   -6, 	  -4,   -6, 	   4,   -2, 	  -1,   -5
.2byte    1,   -7, 	  -5,   -7, 	   5,   -4, 	  -2,   -6
.2byte    1,   -5, 	  -6,   -6, 	   5,   -3, 	  -2,   -5
.2byte   -1,   -6, 	   5,   -4, 	  -7,   -4, 	  -1,   -5
.2byte   -1,   -6, 	   3,   -5, 	  -5,   -5, 	  -1,   -5
.2byte   -1,   -5, 	   3,   -4, 	  -5,   -4, 	  -1,   -4
.2byte   -4,   -6, 	   2,   -6, 	  -6,   -2, 	  -1,   -5
.2byte   -3,   -7, 	   3,   -7, 	  -7,   -4, 	   0,   -6
.2byte   -3,   -5, 	   4,   -6, 	  -7,   -3, 	   0,   -5
.2byte   -6,   -4, 	  -1,   -7, 	   1,   -1, 	   0,   -5
.2byte   -6,   -5, 	  -1,   -6, 	   0,   -2, 	   0,   -6
.2byte   -6,   -3, 	   0,   -5, 	   1,   -2, 	   0,   -4
.2byte   -4,   -3, 	  -6,   -5, 	   4,   -2, 	  -2,   -4
.2byte   -4,   -5, 	  -7,   -5, 	   2,   -2, 	  -1,   -5
.2byte   -4,   -2, 	  -7,   -4, 	   4,   -3, 	  -1,   -5
.2byte   -1,   -3, 	  -7,   -2, 	   5,   -2, 	  -1,   -4
.2byte   -1,   -2, 	  -6,   -2, 	   4,   -2, 	  -1,   -5
.2byte   -1,   -5, 	  -6,   -3, 	   4,   -3, 	  -1,   -6
.2byte    2,   -3, 	   4,   -5, 	  -6,   -2, 	   0,   -4
.2byte    2,   -2, 	   4,   -8, 	  -6,   -2, 	  -1,   -5
.2byte    2,   -5, 	   5,   -5, 	  -4,   -2, 	  -1,   -5
.2byte    5,   -4, 	   0,   -7, 	  -2,   -1, 	  -1,   -5
.2byte    2,   -1, 	   0,   -6, 	   0,   -2, 	  -1,   -5
.2byte    5,   -5, 	   0,   -6, 	  -1,   -2, 	  -1,   -6
.2byte    2,   -6, 	  -4,   -6, 	   4,   -2, 	  -1,   -5
.2byte    0,   -4, 	  -5,   -6, 	   5,   -3, 	  -2,   -5
.2byte    1,   -7, 	  -5,   -7, 	   5,   -4, 	  -2,   -6
.2byte   -1,   -6, 	   5,   -4, 	  -7,   -4, 	  -1,   -5
.2byte   -1,   -5, 	   5,   -4, 	  -7,   -4, 	  -1,   -6
.2byte   -1,   -6, 	   3,   -5, 	  -5,   -5, 	  -1,   -5
.2byte   -4,   -6, 	   2,   -6, 	  -6,   -2, 	  -1,   -5
.2byte   -2,   -4, 	   3,   -6, 	  -7,   -3, 	   0,   -5
.2byte   -3,   -7, 	   3,   -7, 	  -7,   -4, 	   0,   -6
.2byte   -7,   -4, 	  -2,   -7, 	   0,   -1, 	  -1,   -5
.2byte   -4,   -1, 	  -2,   -6, 	  -2,   -2, 	  -1,   -5
.2byte   -7,   -5, 	  -2,   -6, 	  -1,   -2, 	  -1,   -6
.2byte   -4,   -3, 	  -6,   -5, 	   4,   -2, 	  -2,   -4
.2byte   -4,   -2, 	  -6,   -8, 	   4,   -2, 	  -1,   -5
.2byte   -4,   -5, 	  -7,   -5, 	   2,   -2, 	  -1,   -5
.2byte   -3,   -2, 	  -6,   -3, 	   5,    0, 	   0,   -4
.2byte   -2,   -1, 	  -6,   -3, 	   5,    0, 	   0,   -3
.2byte    0,   -8, 	  -7,  -10, 	   7,  -10, 	   0,   -7
.2byte    4,   -8, 	   3,  -13, 	  -3,   -6, 	   0,   -8
.2byte    6,   -7, 	  -2,   -9, 	   0,   -7, 	   0,   -8
.2byte    2,   -9, 	  -4,  -14, 	   6,   -8, 	  -1,   -8
.2byte    0,  -10, 	   7,  -11, 	  -7,  -11, 	   0,   -7
.2byte   -2,   -9, 	   4,  -14, 	  -6,   -8, 	   1,   -8
.2byte   -6,   -7, 	   2,   -9, 	   0,   -7, 	   0,   -8
.2byte   -4,   -8, 	  -3,  -13, 	   3,   -6, 	   0,   -8
.2byte   -1,   -3, 	  -7,   -2, 	   5,   -2, 	  -1,   -4
.2byte   -1,   -9, 	  -6,   -6, 	   4,   -6, 	  -1,   -8
.2byte    2,   -3, 	   4,   -5, 	  -6,   -2, 	   0,   -4
.2byte    2,   -7, 	   5,   -9, 	  -5,   -5, 	   0,   -8
.2byte    5,   -4, 	   0,   -7, 	  -2,   -1, 	  -1,   -5
.2byte    5,   -9, 	  -1,  -10, 	  -2,   -5, 	  -1,   -9
.2byte    2,   -6, 	  -4,   -6, 	   4,   -2, 	  -1,   -5
.2byte    2,   -9, 	  -5,   -8, 	   4,   -4, 	  -1,   -8
.2byte   -1,   -6, 	   5,   -4, 	  -7,   -4, 	  -1,   -5
.2byte   -1,   -9, 	   4,   -7, 	  -6,   -7, 	  -1,   -8
.2byte   -4,   -6, 	   2,   -6, 	  -6,   -2, 	  -1,   -5
.2byte   -4,   -9, 	   3,   -8, 	  -6,   -4, 	  -1,   -8
.2byte   -7,   -4, 	  -2,   -7, 	   0,   -1, 	  -1,   -5
.2byte   -7,   -9, 	  -1,  -10, 	   0,   -5, 	  -1,   -9
.2byte   -4,   -3, 	  -6,   -5, 	   4,   -2, 	  -2,   -4
.2byte   -4,   -7, 	  -7,   -9, 	   3,   -5, 	  -2,   -8
.2byte   -1,   -5, 	  -6,   -3, 	   4,   -3, 	  -1,   -6
.2byte   -4,   -5, 	  -7,   -5, 	   2,   -2, 	  -1,   -5
.2byte   -7,   -5, 	  -2,   -6, 	  -1,   -2, 	  -1,   -6
.2byte   -3,   -7, 	   3,   -7, 	  -7,   -4, 	   0,   -6
.2byte   -1,   -6, 	   3,   -5, 	  -5,   -5, 	  -1,   -5
.2byte    1,   -7, 	  -5,   -7, 	   5,   -4, 	  -2,   -6
.2byte    5,   -5, 	   0,   -6, 	  -1,   -2, 	  -1,   -6
.2byte    2,   -5, 	   5,   -5, 	  -4,   -2, 	  -1,   -5
.2byte   -1,   -5, 	  -6,   -3, 	   4,   -3, 	  -1,   -6
.2byte    2,   -5, 	   5,   -5, 	  -4,   -2, 	  -1,   -5
.2byte    5,   -5, 	   0,   -6, 	  -1,   -2, 	  -1,   -6
.2byte    1,   -7, 	  -5,   -7, 	   5,   -4, 	  -2,   -6
.2byte   -1,   -6, 	   3,   -5, 	  -5,   -5, 	  -1,   -5
.2byte   -3,   -7, 	   3,   -7, 	  -7,   -4, 	   0,   -6
.2byte   -7,   -5, 	  -2,   -6, 	  -1,   -2, 	  -1,   -6
.2byte   -4,   -5, 	  -7,   -5, 	   2,   -2, 	  -1,   -5
.2byte   -1,   -3, 	  -7,   -2, 	   5,   -2, 	  -1,   -4
.2byte   -1,   -6, 	  -6,   -3, 	   4,   -3, 	  -1,   -5
.2byte   -1,   -2, 	  -7,   -4, 	   5,   -4, 	  -1,   -4
.2byte    2,   -3, 	   4,   -5, 	  -6,   -2, 	   0,   -4
.2byte    2,   -4, 	   5,   -6, 	  -5,   -2, 	   0,   -5
.2byte    2,   -2, 	   5,   -7, 	  -7,   -3, 	  -1,   -4
.2byte    5,   -4, 	   0,   -7, 	  -2,   -1, 	  -1,   -5
.2byte    5,   -5, 	  -1,   -6, 	  -2,   -1, 	  -1,   -5
.2byte    5,   -3, 	  -1,   -6, 	  -2,   -2, 	  -1,   -4
.2byte    2,   -6, 	  -4,   -6, 	   4,   -2, 	  -1,   -5
.2byte    2,   -7, 	  -5,   -6, 	   4,   -2, 	  -1,   -6
.2byte    1,   -5, 	  -5,   -6, 	   5,   -3, 	  -2,   -5
.2byte   -1,   -6, 	   5,   -4, 	  -7,   -4, 	  -1,   -5
.2byte   -1,   -7, 	   4,   -5, 	  -6,   -5, 	  -1,   -6
.2byte   -1,   -6, 	   5,   -5, 	  -7,   -5, 	  -1,   -4
.2byte   -4,   -6, 	   2,   -6, 	  -6,   -2, 	  -1,   -5
.2byte   -4,   -7, 	   3,   -6, 	  -6,   -2, 	  -1,   -6
.2byte   -3,   -5, 	   3,   -6, 	  -7,   -3, 	   0,   -5
.2byte   -7,   -4, 	  -2,   -7, 	   0,   -1, 	  -1,   -5
.2byte   -7,   -5, 	  -1,   -6, 	   0,   -1, 	  -1,   -5
.2byte   -7,   -3, 	  -1,   -6, 	   0,   -2, 	  -1,   -4
.2byte   -4,   -3, 	  -6,   -5, 	   4,   -2, 	  -2,   -4
.2byte   -4,   -4, 	  -7,   -6, 	   3,   -2, 	  -2,   -5
.2byte   -4,   -2, 	  -7,   -7, 	   5,   -3, 	  -1,   -4
.2byte   -1,   -2, 	  -6,   -2, 	   4,   -2, 	  -1,   -5
.2byte   -4,   -2, 	  -6,   -8, 	   4,   -2, 	  -1,   -5
.2byte   -4,   -1, 	  -2,   -6, 	  -2,   -2, 	  -1,   -5
.2byte   -2,   -4, 	   3,   -6, 	  -7,   -3, 	   0,   -5
.2byte   -1,   -5, 	   5,   -4, 	  -7,   -4, 	  -1,   -6
.2byte    0,   -4, 	  -5,   -6, 	   5,   -3, 	  -2,   -5
.2byte    2,   -1, 	   0,   -6, 	   0,   -2, 	  -1,   -5
.2byte    2,   -2, 	   4,   -8, 	  -6,   -2, 	  -1,   -5
.2byte   -1,   -3, 	  -7,   -2, 	   5,   -2, 	  -1,   -4
.2byte   -4,   -3, 	  -6,   -5, 	   4,   -2, 	  -2,   -4
.2byte   -7,   -4, 	  -2,   -7, 	   0,   -1, 	  -1,   -5
.2byte   -4,   -6, 	   2,   -6, 	  -6,   -2, 	  -1,   -5
.2byte   -1,   -6, 	   5,   -4, 	  -7,   -4, 	  -1,   -5
.2byte    2,   -6, 	  -4,   -6, 	   4,   -2, 	  -1,   -5
.2byte    5,   -4, 	   0,   -7, 	  -2,   -1, 	  -1,   -5
.2byte    2,   -3, 	   4,   -5, 	  -6,   -2, 	   0,   -4
sIgglybuffAnimTable1:
.4byte sIgglybuffAnims_1_1
.4byte sIgglybuffAnims_1_2
.4byte sIgglybuffAnims_1_3
.4byte sIgglybuffAnims_1_4
.4byte sIgglybuffAnims_1_5
.4byte sIgglybuffAnims_1_6
.4byte sIgglybuffAnims_1_7
.4byte sIgglybuffAnims_1_8
sIgglybuffAnimTable2:
.4byte sIgglybuffAnims_2_1
.4byte sIgglybuffAnims_2_2
.4byte sIgglybuffAnims_2_3
.4byte sIgglybuffAnims_2_4
.4byte sIgglybuffAnims_2_5
.4byte sIgglybuffAnims_2_6
.4byte sIgglybuffAnims_2_7
.4byte sIgglybuffAnims_2_8
sIgglybuffAnimTable3:
.4byte sIgglybuffAnims_3_1
.4byte sIgglybuffAnims_3_2
.4byte sIgglybuffAnims_3_3
.4byte sIgglybuffAnims_3_4
.4byte sIgglybuffAnims_3_5
.4byte sIgglybuffAnims_3_6
.4byte sIgglybuffAnims_3_7
.4byte sIgglybuffAnims_3_8
sIgglybuffAnimTable4:
.4byte sIgglybuffAnims_4_1
.4byte sIgglybuffAnims_4_2
.4byte sIgglybuffAnims_4_3
.4byte sIgglybuffAnims_4_4
.4byte sIgglybuffAnims_4_5
.4byte sIgglybuffAnims_4_6
.4byte sIgglybuffAnims_4_7
.4byte sIgglybuffAnims_4_8
sIgglybuffAnimTable5:
.4byte sIgglybuffAnims_5_1
.4byte sIgglybuffAnims_5_2
.4byte sIgglybuffAnims_5_3
.4byte sIgglybuffAnims_5_4
.4byte sIgglybuffAnims_5_5
.4byte sIgglybuffAnims_5_6
.4byte sIgglybuffAnims_5_7
.4byte sIgglybuffAnims_5_8
sIgglybuffAnimTable6:
.4byte sIgglybuffAnims_6_1
.4byte sIgglybuffAnims_6_1
.4byte sIgglybuffAnims_6_1
.4byte sIgglybuffAnims_6_1
.4byte sIgglybuffAnims_6_1
.4byte sIgglybuffAnims_6_1
.4byte sIgglybuffAnims_6_1
.4byte sIgglybuffAnims_6_1
sIgglybuffAnimTable7:
.4byte sIgglybuffAnims_7_1
.4byte sIgglybuffAnims_7_2
.4byte sIgglybuffAnims_7_3
.4byte sIgglybuffAnims_7_4
.4byte sIgglybuffAnims_7_5
.4byte sIgglybuffAnims_7_6
.4byte sIgglybuffAnims_7_7
.4byte sIgglybuffAnims_7_8
sIgglybuffAnimTable8:
.4byte sIgglybuffAnims_8_1
.4byte sIgglybuffAnims_8_2
.4byte sIgglybuffAnims_8_3
.4byte sIgglybuffAnims_8_4
.4byte sIgglybuffAnims_8_5
.4byte sIgglybuffAnims_8_6
.4byte sIgglybuffAnims_8_7
.4byte sIgglybuffAnims_8_8
sIgglybuffAnimTable9:
.4byte sIgglybuffAnims_9_1
.4byte sIgglybuffAnims_9_2
.4byte sIgglybuffAnims_9_3
.4byte sIgglybuffAnims_9_4
.4byte sIgglybuffAnims_9_5
.4byte sIgglybuffAnims_9_6
.4byte sIgglybuffAnims_9_7
.4byte sIgglybuffAnims_9_8
sIgglybuffAnimTable10:
.4byte sIgglybuffAnims_10_1
.4byte sIgglybuffAnims_10_2
.4byte sIgglybuffAnims_10_3
.4byte sIgglybuffAnims_10_4
.4byte sIgglybuffAnims_10_5
.4byte sIgglybuffAnims_10_6
.4byte sIgglybuffAnims_10_7
.4byte sIgglybuffAnims_10_8
sIgglybuffAnimTable11:
.4byte sIgglybuffAnims_11_1
.4byte sIgglybuffAnims_11_2
.4byte sIgglybuffAnims_11_3
.4byte sIgglybuffAnims_11_4
.4byte sIgglybuffAnims_11_5
.4byte sIgglybuffAnims_11_6
.4byte sIgglybuffAnims_11_7
.4byte sIgglybuffAnims_11_8
sIgglybuffAnimTable12:
.4byte sIgglybuffAnims_12_1
.4byte sIgglybuffAnims_12_2
.4byte sIgglybuffAnims_12_3
.4byte sIgglybuffAnims_12_4
.4byte sIgglybuffAnims_12_5
.4byte sIgglybuffAnims_12_6
.4byte sIgglybuffAnims_12_7
.4byte sIgglybuffAnims_12_8
sIgglybuffAnimTable13:
.4byte sIgglybuffAnims_13_1
.4byte sIgglybuffAnims_13_2
.4byte sIgglybuffAnims_13_3
.4byte sIgglybuffAnims_13_4
.4byte sIgglybuffAnims_13_5
.4byte sIgglybuffAnims_13_6
.4byte sIgglybuffAnims_13_7
.4byte sIgglybuffAnims_13_8
sAxAnimationsIgglybuff:
.4byte sIgglybuffAnimTable1
.4byte sIgglybuffAnimTable2
.4byte sIgglybuffAnimTable3
.4byte sIgglybuffAnimTable4
.4byte sIgglybuffAnimTable5
.4byte sIgglybuffAnimTable6
.4byte sIgglybuffAnimTable7
.4byte sIgglybuffAnimTable8
.4byte sIgglybuffAnimTable9
.4byte sIgglybuffAnimTable10
.4byte sIgglybuffAnimTable11
.4byte sIgglybuffAnimTable12
.4byte sIgglybuffAnimTable13
sAxSpritesIgglybuff:
.4byte sIgglybuffSprites1
.4byte sIgglybuffSprites2
.4byte sIgglybuffSprites3
.4byte sIgglybuffSprites4
.4byte sIgglybuffSprites5
.4byte sIgglybuffSprites6
.4byte sIgglybuffSprites7
.4byte sIgglybuffSprites8
.4byte sIgglybuffSprites9
.4byte sIgglybuffSprites10
.4byte sIgglybuffSprites11
.4byte sIgglybuffSprites12
.4byte sIgglybuffSprites13
.4byte sIgglybuffSprites14
.4byte sIgglybuffSprites15
.4byte sIgglybuffSprites16
.4byte sIgglybuffSprites17
.4byte sIgglybuffSprites18
.4byte sIgglybuffSprites19
.4byte sIgglybuffSprites20
.4byte sIgglybuffSprites21
.4byte sIgglybuffSprites22
.4byte sIgglybuffSprites23
.4byte sIgglybuffSprites24
.4byte sIgglybuffSprites25
.4byte sIgglybuffSprites26
.4byte sIgglybuffSprites27
.4byte sIgglybuffSprites28
.4byte sIgglybuffSprites29
.4byte sIgglybuffSprites30
.4byte sIgglybuffSprites31
.4byte sIgglybuffSprites32
.4byte sIgglybuffSprites33
.4byte sIgglybuffSprites34
.4byte sIgglybuffSprites35
.4byte sIgglybuffSprites36
.4byte sIgglybuffSprites37
sAxMainIgglybuff:
ax_main sAxPosesIgglybuff, sAxAnimationsIgglybuff, 13, sAxSpritesIgglybuff, sAxPositionsIgglybuff
