.global gAxIllumise
gAxIllumise:
ax_siro sAxMainIllumise
sIllumisePose1:
ax_pose 0, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sIllumisePose2:
ax_pose 1, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sIllumisePose3:
ax_pose 2, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sIllumisePose4:
ax_pose 3, 0x01e9, 0x90ec, 0x7c00
ax_pose_terminator
sIllumisePose5:
ax_pose 4, 0x01e9, 0x90ec, 0x7c00
ax_pose_terminator
sIllumisePose6:
ax_pose 5, 0x01e9, 0x90ec, 0x7c00
ax_pose_terminator
sIllumisePose7:
ax_pose 6, 0x81e6, 0x90f7, 0x7c00
ax_pose_terminator
sIllumisePose8:
ax_pose 7, 0x81e6, 0x90f7, 0x7c00
ax_pose_terminator
sIllumisePose9:
ax_pose 8, 0x81e6, 0x90f7, 0x7c00
ax_pose_terminator
sIllumisePose10:
ax_pose 9, 0x01e6, 0x90ef, 0x7c00
ax_pose_terminator
sIllumisePose11:
ax_pose 10, 0x01e6, 0x90ef, 0x7c00
ax_pose_terminator
sIllumisePose12:
ax_pose 11, 0x01e6, 0x90ef, 0x7c00
ax_pose_terminator
sIllumisePose13:
ax_pose 12, 0x01e6, 0x80f3, 0x7c00
ax_pose_terminator
sIllumisePose14:
ax_pose 13, 0x01e6, 0x80f3, 0x7c00
ax_pose_terminator
sIllumisePose15:
ax_pose 14, 0x01e6, 0x80f3, 0x7c00
ax_pose_terminator
sIllumisePose16:
ax_pose 9, 0x01e6, 0x80f0, 0x7c00
ax_pose_terminator
sIllumisePose17:
ax_pose 10, 0x01e6, 0x80f0, 0x7c00
ax_pose_terminator
sIllumisePose18:
ax_pose 11, 0x01e6, 0x80f0, 0x7c00
ax_pose_terminator
sIllumisePose19:
ax_pose 6, 0x81e6, 0x80f8, 0x7c00
ax_pose_terminator
sIllumisePose20:
ax_pose 7, 0x81e6, 0x80f8, 0x7c00
ax_pose_terminator
sIllumisePose21:
ax_pose 8, 0x81e6, 0x80f8, 0x7c00
ax_pose_terminator
sIllumisePose22:
ax_pose 3, 0x01e9, 0x80f3, 0x7c00
ax_pose_terminator
sIllumisePose23:
ax_pose 4, 0x01e9, 0x80f3, 0x7c00
ax_pose_terminator
sIllumisePose24:
ax_pose 5, 0x01e9, 0x80f3, 0x7c00
ax_pose_terminator
sIllumisePose25:
ax_pose 0, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sIllumisePose26:
ax_pose 3, 0x01e9, 0x80f3, 0x7c00
ax_pose_terminator
sIllumisePose27:
ax_pose 6, 0x81e6, 0x80f8, 0x7c00
ax_pose_terminator
sIllumisePose28:
ax_pose 9, 0x01e6, 0x80f0, 0x7c00
ax_pose_terminator
sIllumisePose29:
ax_pose 12, 0x01e6, 0x80f3, 0x7c00
ax_pose_terminator
sIllumisePose30:
ax_pose 9, 0x01e6, 0x90ef, 0x7c00
ax_pose_terminator
sIllumisePose31:
ax_pose 6, 0x81e6, 0x90f7, 0x7c00
ax_pose_terminator
sIllumisePose32:
ax_pose 3, 0x01e9, 0x90ec, 0x7c00
ax_pose_terminator
sIllumisePose33:
ax_pose 0, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sIllumisePose34:
ax_pose 1, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sIllumisePose35:
ax_pose 2, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sIllumisePose36:
ax_pose 15, 0x01e6, 0x80f0, 0x7c00
ax_pose_terminator
sIllumisePose37:
ax_pose 16, 0x01e6, 0x80f0, 0x7c00
ax_pose_terminator
sIllumisePose38:
ax_pose 3, 0x01e9, 0x90ec, 0x7c00
ax_pose_terminator
sIllumisePose39:
ax_pose 4, 0x01e9, 0x90ec, 0x7c00
ax_pose_terminator
sIllumisePose40:
ax_pose 5, 0x01e9, 0x90ec, 0x7c00
ax_pose_terminator
sIllumisePose41:
ax_pose 17, 0x01e6, 0x90f1, 0x7c00
ax_pose_terminator
sIllumisePose42:
ax_pose 18, 0x01e6, 0x90f1, 0x7c00
ax_pose_terminator
sIllumisePose43:
ax_pose 6, 0x81e6, 0x90f7, 0x7c00
ax_pose_terminator
sIllumisePose44:
ax_pose 7, 0x81e6, 0x90f7, 0x7c00
ax_pose_terminator
sIllumisePose45:
ax_pose 8, 0x81e6, 0x90f7, 0x7c00
ax_pose_terminator
sIllumisePose46:
ax_pose 19, 0x01e5, 0x90f2, 0x7c00
ax_pose_terminator
sIllumisePose47:
ax_pose 20, 0x01e5, 0x90f2, 0x7c00
ax_pose_terminator
sIllumisePose48:
ax_pose 9, 0x01e6, 0x90ef, 0x7c00
ax_pose_terminator
sIllumisePose49:
ax_pose 10, 0x01e6, 0x90ef, 0x7c00
ax_pose_terminator
sIllumisePose50:
ax_pose 11, 0x01e6, 0x90ef, 0x7c00
ax_pose_terminator
sIllumisePose51:
ax_pose 21, 0x01e5, 0x90f2, 0x7c00
ax_pose_terminator
sIllumisePose52:
ax_pose 22, 0x01e5, 0x90f2, 0x7c00
ax_pose_terminator
sIllumisePose53:
ax_pose 12, 0x01e6, 0x80f3, 0x7c00
ax_pose_terminator
sIllumisePose54:
ax_pose 13, 0x01e6, 0x80f3, 0x7c00
ax_pose_terminator
sIllumisePose55:
ax_pose 14, 0x01e6, 0x80f3, 0x7c00
ax_pose_terminator
sIllumisePose56:
ax_pose 23, 0x01e5, 0x80f0, 0x7c00
ax_pose_terminator
sIllumisePose57:
ax_pose 24, 0x01e5, 0x80f0, 0x7c00
ax_pose_terminator
sIllumisePose58:
ax_pose 9, 0x01e6, 0x80f0, 0x7c00
ax_pose_terminator
sIllumisePose59:
ax_pose 10, 0x01e6, 0x80f0, 0x7c00
ax_pose_terminator
sIllumisePose60:
ax_pose 11, 0x01e6, 0x80f0, 0x7c00
ax_pose_terminator
sIllumisePose61:
ax_pose 21, 0x01e5, 0x80ed, 0x7c00
ax_pose_terminator
sIllumisePose62:
ax_pose 22, 0x01e5, 0x80ed, 0x7c00
ax_pose_terminator
sIllumisePose63:
ax_pose 6, 0x81e6, 0x80f8, 0x7c00
ax_pose_terminator
sIllumisePose64:
ax_pose 7, 0x81e6, 0x80f8, 0x7c00
ax_pose_terminator
sIllumisePose65:
ax_pose 8, 0x81e6, 0x80f8, 0x7c00
ax_pose_terminator
sIllumisePose66:
ax_pose 19, 0x01e5, 0x80ed, 0x7c00
ax_pose_terminator
sIllumisePose67:
ax_pose 20, 0x01e5, 0x80ed, 0x7c00
ax_pose_terminator
sIllumisePose68:
ax_pose 3, 0x01e9, 0x80f3, 0x7c00
ax_pose_terminator
sIllumisePose69:
ax_pose 4, 0x01e9, 0x80f3, 0x7c00
ax_pose_terminator
sIllumisePose70:
ax_pose 5, 0x01e9, 0x80f3, 0x7c00
ax_pose_terminator
sIllumisePose71:
ax_pose 17, 0x01e6, 0x80ee, 0x7c00
ax_pose_terminator
sIllumisePose72:
ax_pose 18, 0x01e6, 0x80ee, 0x7c00
ax_pose_terminator
sIllumisePose73:
ax_pose 0, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sIllumisePose74:
ax_pose 1, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sIllumisePose75:
ax_pose 2, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sIllumisePose76:
ax_pose 15, 0x01e6, 0x80f0, 0x7c00
ax_pose_terminator
sIllumisePose77:
ax_pose 16, 0x01e6, 0x80f0, 0x7c00
ax_pose_terminator
sIllumisePose78:
ax_pose 3, 0x01e9, 0x90ec, 0x7c00
ax_pose_terminator
sIllumisePose79:
ax_pose 4, 0x01e9, 0x90ec, 0x7c00
ax_pose_terminator
sIllumisePose80:
ax_pose 5, 0x01e9, 0x90ec, 0x7c00
ax_pose_terminator
sIllumisePose81:
ax_pose 17, 0x01e6, 0x90f1, 0x7c00
ax_pose_terminator
sIllumisePose82:
ax_pose 18, 0x01e6, 0x90f1, 0x7c00
ax_pose_terminator
sIllumisePose83:
ax_pose 6, 0x81e6, 0x90f7, 0x7c00
ax_pose_terminator
sIllumisePose84:
ax_pose 7, 0x81e6, 0x90f7, 0x7c00
ax_pose_terminator
sIllumisePose85:
ax_pose 8, 0x81e6, 0x90f7, 0x7c00
ax_pose_terminator
sIllumisePose86:
ax_pose 19, 0x01e5, 0x90f2, 0x7c00
ax_pose_terminator
sIllumisePose87:
ax_pose 20, 0x01e5, 0x90f2, 0x7c00
ax_pose_terminator
sIllumisePose88:
ax_pose 9, 0x01e6, 0x90ef, 0x7c00
ax_pose_terminator
sIllumisePose89:
ax_pose 10, 0x01e6, 0x90ef, 0x7c00
ax_pose_terminator
sIllumisePose90:
ax_pose 11, 0x01e6, 0x90ef, 0x7c00
ax_pose_terminator
sIllumisePose91:
ax_pose 21, 0x01e5, 0x90f2, 0x7c00
ax_pose_terminator
sIllumisePose92:
ax_pose 22, 0x01e5, 0x90f2, 0x7c00
ax_pose_terminator
sIllumisePose93:
ax_pose 12, 0x01e6, 0x80f3, 0x7c00
ax_pose_terminator
sIllumisePose94:
ax_pose 13, 0x01e6, 0x80f3, 0x7c00
ax_pose_terminator
sIllumisePose95:
ax_pose 14, 0x01e6, 0x80f3, 0x7c00
ax_pose_terminator
sIllumisePose96:
ax_pose 23, 0x01e5, 0x80f0, 0x7c00
ax_pose_terminator
sIllumisePose97:
ax_pose 24, 0x01e5, 0x80f0, 0x7c00
ax_pose_terminator
sIllumisePose98:
ax_pose 9, 0x01e6, 0x80f0, 0x7c00
ax_pose_terminator
sIllumisePose99:
ax_pose 10, 0x01e6, 0x80f0, 0x7c00
ax_pose_terminator
sIllumisePose100:
ax_pose 11, 0x01e6, 0x80f0, 0x7c00
ax_pose_terminator
sIllumisePose101:
ax_pose 21, 0x01e5, 0x80ed, 0x7c00
ax_pose_terminator
sIllumisePose102:
ax_pose 22, 0x01e5, 0x80ed, 0x7c00
ax_pose_terminator
sIllumisePose103:
ax_pose 6, 0x81e6, 0x80f8, 0x7c00
ax_pose_terminator
sIllumisePose104:
ax_pose 7, 0x81e6, 0x80f8, 0x7c00
ax_pose_terminator
sIllumisePose105:
ax_pose 8, 0x81e6, 0x80f8, 0x7c00
ax_pose_terminator
sIllumisePose106:
ax_pose 19, 0x01e5, 0x80ed, 0x7c00
ax_pose_terminator
sIllumisePose107:
ax_pose 20, 0x01e5, 0x80ed, 0x7c00
ax_pose_terminator
sIllumisePose108:
ax_pose 3, 0x01e9, 0x80f3, 0x7c00
ax_pose_terminator
sIllumisePose109:
ax_pose 4, 0x01e9, 0x80f3, 0x7c00
ax_pose_terminator
sIllumisePose110:
ax_pose 5, 0x01e9, 0x80f3, 0x7c00
ax_pose_terminator
sIllumisePose111:
ax_pose 17, 0x01e6, 0x80ee, 0x7c00
ax_pose_terminator
sIllumisePose112:
ax_pose 18, 0x01e6, 0x80ee, 0x7c00
ax_pose_terminator
sIllumisePose113:
ax_pose 0, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sIllumisePose114:
ax_pose 25, 0x01e4, 0x80f0, 0x7c00
ax_pose_terminator
sIllumisePose115:
ax_pose 26, 0x01e4, 0x80f0, 0x7c00
ax_pose_terminator
sIllumisePose116:
ax_pose 3, 0x01e9, 0x90ec, 0x7c00
ax_pose_terminator
sIllumisePose117:
ax_pose 27, 0x01e4, 0x90f0, 0x7c00
ax_pose_terminator
sIllumisePose118:
ax_pose 28, 0x01e4, 0x90ee, 0x7c00
ax_pose_terminator
sIllumisePose119:
ax_pose 6, 0x81e6, 0x90f7, 0x7c00
ax_pose_terminator
sIllumisePose120:
ax_pose 29, 0x01e4, 0x90f0, 0x7c00
ax_pose_terminator
sIllumisePose121:
ax_pose 30, 0x01e4, 0x90ee, 0x7c00
ax_pose_terminator
sIllumisePose122:
ax_pose 9, 0x01e6, 0x90ef, 0x7c00
ax_pose_terminator
sIllumisePose123:
ax_pose 31, 0x01e4, 0x90f0, 0x7c00
ax_pose_terminator
sIllumisePose124:
ax_pose 32, 0x01e4, 0x90ef, 0x7c00
ax_pose_terminator
sIllumisePose125:
ax_pose 12, 0x01e6, 0x80f3, 0x7c00
ax_pose_terminator
sIllumisePose126:
ax_pose 33, 0x01e4, 0x80f0, 0x7c00
ax_pose_terminator
sIllumisePose127:
ax_pose 34, 0x01e4, 0x80f0, 0x7c00
ax_pose_terminator
sIllumisePose128:
ax_pose 9, 0x01e6, 0x80f0, 0x7c00
ax_pose_terminator
sIllumisePose129:
ax_pose 31, 0x01e4, 0x80ef, 0x7c00
ax_pose_terminator
sIllumisePose130:
ax_pose 32, 0x01e4, 0x80f0, 0x7c00
ax_pose_terminator
sIllumisePose131:
ax_pose 6, 0x81e6, 0x80f8, 0x7c00
ax_pose_terminator
sIllumisePose132:
ax_pose 29, 0x01e4, 0x80ef, 0x7c00
ax_pose_terminator
sIllumisePose133:
ax_pose 30, 0x01e4, 0x80f1, 0x7c00
ax_pose_terminator
sIllumisePose134:
ax_pose 3, 0x01e9, 0x80f3, 0x7c00
ax_pose_terminator
sIllumisePose135:
ax_pose 27, 0x01e4, 0x80ef, 0x7c00
ax_pose_terminator
sIllumisePose136:
ax_pose 28, 0x01e4, 0x80f1, 0x7c00
ax_pose_terminator
sIllumisePose137:
ax_pose 0, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sIllumisePose138:
ax_pose 1, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sIllumisePose139:
ax_pose 2, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sIllumisePose140:
ax_pose 15, 0x01e6, 0x80f0, 0x7c00
ax_pose_terminator
sIllumisePose141:
ax_pose 16, 0x01e6, 0x80f0, 0x7c00
ax_pose_terminator
sIllumisePose142:
ax_pose 3, 0x01e9, 0x90ec, 0x7c00
ax_pose_terminator
sIllumisePose143:
ax_pose 4, 0x01e9, 0x90ec, 0x7c00
ax_pose_terminator
sIllumisePose144:
ax_pose 5, 0x01e9, 0x90ec, 0x7c00
ax_pose_terminator
sIllumisePose145:
ax_pose 17, 0x01e6, 0x90f1, 0x7c00
ax_pose_terminator
sIllumisePose146:
ax_pose 18, 0x01e6, 0x90f1, 0x7c00
ax_pose_terminator
sIllumisePose147:
ax_pose 6, 0x81e6, 0x90f7, 0x7c00
ax_pose_terminator
sIllumisePose148:
ax_pose 7, 0x81e6, 0x90f7, 0x7c00
ax_pose_terminator
sIllumisePose149:
ax_pose 8, 0x81e6, 0x90f7, 0x7c00
ax_pose_terminator
sIllumisePose150:
ax_pose 19, 0x01e5, 0x90f2, 0x7c00
ax_pose_terminator
sIllumisePose151:
ax_pose 20, 0x01e5, 0x90f2, 0x7c00
ax_pose_terminator
sIllumisePose152:
ax_pose 9, 0x01e6, 0x90ef, 0x7c00
ax_pose_terminator
sIllumisePose153:
ax_pose 10, 0x01e6, 0x90ef, 0x7c00
ax_pose_terminator
sIllumisePose154:
ax_pose 11, 0x01e6, 0x90ef, 0x7c00
ax_pose_terminator
sIllumisePose155:
ax_pose 21, 0x01e5, 0x90f2, 0x7c00
ax_pose_terminator
sIllumisePose156:
ax_pose 22, 0x01e5, 0x90f2, 0x7c00
ax_pose_terminator
sIllumisePose157:
ax_pose 12, 0x01e6, 0x80f3, 0x7c00
ax_pose_terminator
sIllumisePose158:
ax_pose 13, 0x01e6, 0x80f3, 0x7c00
ax_pose_terminator
sIllumisePose159:
ax_pose 14, 0x01e6, 0x80f3, 0x7c00
ax_pose_terminator
sIllumisePose160:
ax_pose 23, 0x01e5, 0x80f0, 0x7c00
ax_pose_terminator
sIllumisePose161:
ax_pose 24, 0x01e5, 0x80f0, 0x7c00
ax_pose_terminator
sIllumisePose162:
ax_pose 9, 0x01e6, 0x80f0, 0x7c00
ax_pose_terminator
sIllumisePose163:
ax_pose 10, 0x01e6, 0x80f0, 0x7c00
ax_pose_terminator
sIllumisePose164:
ax_pose 11, 0x01e6, 0x80f0, 0x7c00
ax_pose_terminator
sIllumisePose165:
ax_pose 21, 0x01e5, 0x80ed, 0x7c00
ax_pose_terminator
sIllumisePose166:
ax_pose 22, 0x01e5, 0x80ed, 0x7c00
ax_pose_terminator
sIllumisePose167:
ax_pose 6, 0x81e6, 0x80f8, 0x7c00
ax_pose_terminator
sIllumisePose168:
ax_pose 7, 0x81e6, 0x80f8, 0x7c00
ax_pose_terminator
sIllumisePose169:
ax_pose 8, 0x81e6, 0x80f8, 0x7c00
ax_pose_terminator
sIllumisePose170:
ax_pose 19, 0x01e5, 0x80ed, 0x7c00
ax_pose_terminator
sIllumisePose171:
ax_pose 20, 0x01e5, 0x80ed, 0x7c00
ax_pose_terminator
sIllumisePose172:
ax_pose 3, 0x01e9, 0x80f3, 0x7c00
ax_pose_terminator
sIllumisePose173:
ax_pose 4, 0x01e9, 0x80f3, 0x7c00
ax_pose_terminator
sIllumisePose174:
ax_pose 5, 0x01e9, 0x80f3, 0x7c00
ax_pose_terminator
sIllumisePose175:
ax_pose 17, 0x01e6, 0x80ee, 0x7c00
ax_pose_terminator
sIllumisePose176:
ax_pose 18, 0x01e6, 0x80ee, 0x7c00
ax_pose_terminator
sIllumisePose177:
ax_pose 35, 0x01ea, 0x80f3, 0x7c00
ax_pose_terminator
sIllumisePose178:
ax_pose 36, 0x01ea, 0x80f3, 0x7c00
ax_pose_terminator
sIllumisePose179:
ax_pose 37, 0x01e0, 0x80f1, 0x7c00
ax_pose_terminator
sIllumisePose180:
ax_pose 38, 0x01e4, 0x90ea, 0x7c00
ax_pose_terminator
sIllumisePose181:
ax_pose 39, 0x01e4, 0x90eb, 0x7c00
ax_pose_terminator
sIllumisePose182:
ax_pose 40, 0x01e7, 0x90ea, 0x7c00
ax_pose_terminator
sIllumisePose183:
ax_pose 41, 0x01e3, 0x80f1, 0x7c00
ax_pose_terminator
sIllumisePose184:
ax_pose 40, 0x01e8, 0x80f7, 0x7c00
ax_pose_terminator
sIllumisePose185:
ax_pose 39, 0x01e4, 0x80f5, 0x7c00
ax_pose_terminator
sIllumisePose186:
ax_pose 38, 0x01e4, 0x80f6, 0x7c00
ax_pose_terminator
sIllumisePose187:
ax_pose 0, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sIllumisePose188:
ax_pose 25, 0x01e4, 0x80f0, 0x7c00
ax_pose_terminator
sIllumisePose189:
ax_pose 3, 0x01e9, 0x90ec, 0x7c00
ax_pose_terminator
sIllumisePose190:
ax_pose 27, 0x01e4, 0x90f0, 0x7c00
ax_pose_terminator
sIllumisePose191:
ax_pose 6, 0x81e6, 0x90f7, 0x7c00
ax_pose_terminator
sIllumisePose192:
ax_pose 29, 0x01e4, 0x90f0, 0x7c00
ax_pose_terminator
sIllumisePose193:
ax_pose 9, 0x01e6, 0x90ef, 0x7c00
ax_pose_terminator
sIllumisePose194:
ax_pose 31, 0x01e4, 0x90f0, 0x7c00
ax_pose_terminator
sIllumisePose195:
ax_pose 12, 0x01e6, 0x80f3, 0x7c00
ax_pose_terminator
sIllumisePose196:
ax_pose 33, 0x01e4, 0x80f0, 0x7c00
ax_pose_terminator
sIllumisePose197:
ax_pose 9, 0x01e6, 0x80f0, 0x7c00
ax_pose_terminator
sIllumisePose198:
ax_pose 31, 0x01e4, 0x80ef, 0x7c00
ax_pose_terminator
sIllumisePose199:
ax_pose 6, 0x81e6, 0x80f8, 0x7c00
ax_pose_terminator
sIllumisePose200:
ax_pose 29, 0x01e4, 0x80ef, 0x7c00
ax_pose_terminator
sIllumisePose201:
ax_pose 3, 0x01e9, 0x80f3, 0x7c00
ax_pose_terminator
sIllumisePose202:
ax_pose 27, 0x01e4, 0x80ef, 0x7c00
ax_pose_terminator
sIllumisePose203:
ax_pose 15, 0x01e6, 0x80f0, 0x7c00
ax_pose_terminator
sIllumisePose204:
ax_pose 17, 0x01e6, 0x80ee, 0x7c00
ax_pose_terminator
sIllumisePose205:
ax_pose 19, 0x01e5, 0x80ed, 0x7c00
ax_pose_terminator
sIllumisePose206:
ax_pose 21, 0x01e5, 0x80ed, 0x7c00
ax_pose_terminator
sIllumisePose207:
ax_pose 23, 0x01e5, 0x80f0, 0x7c00
ax_pose_terminator
sIllumisePose208:
ax_pose 21, 0x01e5, 0x90f2, 0x7c00
ax_pose_terminator
sIllumisePose209:
ax_pose 19, 0x01e5, 0x90f2, 0x7c00
ax_pose_terminator
sIllumisePose210:
ax_pose 17, 0x01e6, 0x90f1, 0x7c00
ax_pose_terminator
sIllumisePose211:
ax_pose 26, 0x01e4, 0x80f0, 0x7c00
ax_pose_terminator
sIllumisePose212:
ax_pose 28, 0x01e4, 0x90ee, 0x7c00
ax_pose_terminator
sIllumisePose213:
ax_pose 30, 0x01e5, 0x90ee, 0x7c00
ax_pose_terminator
sIllumisePose214:
ax_pose 32, 0x01e5, 0x90ef, 0x7c00
ax_pose_terminator
sIllumisePose215:
ax_pose 34, 0x01e5, 0x80f0, 0x7c00
ax_pose_terminator
sIllumisePose216:
ax_pose 32, 0x01e5, 0x80f0, 0x7c00
ax_pose_terminator
sIllumisePose217:
ax_pose 30, 0x01e5, 0x80f1, 0x7c00
ax_pose_terminator
sIllumisePose218:
ax_pose 28, 0x01e4, 0x80f1, 0x7c00
ax_pose_terminator
sIllumisePose219:
ax_pose 0, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sIllumisePose220:
ax_pose 2, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sIllumisePose221:
ax_pose 1, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sIllumisePose222:
ax_pose 3, 0x01e9, 0x90ec, 0x7c00
ax_pose_terminator
sIllumisePose223:
ax_pose 5, 0x01e9, 0x90ec, 0x7c00
ax_pose_terminator
sIllumisePose224:
ax_pose 4, 0x01e9, 0x90ec, 0x7c00
ax_pose_terminator
sIllumisePose225:
ax_pose 6, 0x81e6, 0x90f7, 0x7c00
ax_pose_terminator
sIllumisePose226:
ax_pose 8, 0x81e6, 0x90f7, 0x7c00
ax_pose_terminator
sIllumisePose227:
ax_pose 7, 0x81e6, 0x90f7, 0x7c00
ax_pose_terminator
sIllumisePose228:
ax_pose 9, 0x01e6, 0x90ef, 0x7c00
ax_pose_terminator
sIllumisePose229:
ax_pose 11, 0x01e6, 0x90ef, 0x7c00
ax_pose_terminator
sIllumisePose230:
ax_pose 10, 0x01e6, 0x90ef, 0x7c00
ax_pose_terminator
sIllumisePose231:
ax_pose 12, 0x01e6, 0x80f3, 0x7c00
ax_pose_terminator
sIllumisePose232:
ax_pose 14, 0x01e6, 0x80f3, 0x7c00
ax_pose_terminator
sIllumisePose233:
ax_pose 13, 0x01e6, 0x80f3, 0x7c00
ax_pose_terminator
sIllumisePose234:
ax_pose 9, 0x01e6, 0x80f0, 0x7c00
ax_pose_terminator
sIllumisePose235:
ax_pose 11, 0x01e6, 0x80f0, 0x7c00
ax_pose_terminator
sIllumisePose236:
ax_pose 10, 0x01e6, 0x80f0, 0x7c00
ax_pose_terminator
sIllumisePose237:
ax_pose 6, 0x81e6, 0x80f8, 0x7c00
ax_pose_terminator
sIllumisePose238:
ax_pose 8, 0x81e6, 0x80f8, 0x7c00
ax_pose_terminator
sIllumisePose239:
ax_pose 7, 0x81e6, 0x80f8, 0x7c00
ax_pose_terminator
sIllumisePose240:
ax_pose 3, 0x01e9, 0x80f3, 0x7c00
ax_pose_terminator
sIllumisePose241:
ax_pose 5, 0x01e9, 0x80f3, 0x7c00
ax_pose_terminator
sIllumisePose242:
ax_pose 4, 0x01e9, 0x80f3, 0x7c00
ax_pose_terminator
sIllumisePose243:
ax_pose 25, 0x01e4, 0x80f0, 0x7c00
ax_pose_terminator
sIllumisePose244:
ax_pose 27, 0x01e4, 0x80ef, 0x7c00
ax_pose_terminator
sIllumisePose245:
ax_pose 29, 0x01e4, 0x80ef, 0x7c00
ax_pose_terminator
sIllumisePose246:
ax_pose 31, 0x01e4, 0x80ef, 0x7c00
ax_pose_terminator
sIllumisePose247:
ax_pose 33, 0x01e4, 0x80f0, 0x7c00
ax_pose_terminator
sIllumisePose248:
ax_pose 31, 0x01e4, 0x90f0, 0x7c00
ax_pose_terminator
sIllumisePose249:
ax_pose 29, 0x01e4, 0x90f0, 0x7c00
ax_pose_terminator
sIllumisePose250:
ax_pose 27, 0x01e4, 0x90f0, 0x7c00
ax_pose_terminator
sIllumisePose251:
ax_pose 0, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sIllumisePose252:
ax_pose 3, 0x01e9, 0x80f4, 0x7c00
ax_pose_terminator
sIllumisePose253:
ax_pose 42, 0x01e6, 0x80f8, 0x7c00
ax_pose_terminator
sIllumisePose254:
ax_pose 9, 0x01e6, 0x80f0, 0x7c00
ax_pose_terminator
sIllumisePose255:
ax_pose 12, 0x01e6, 0x80f3, 0x7c00
ax_pose_terminator
sIllumisePose256:
ax_pose 9, 0x01e6, 0x90ef, 0x7c00
ax_pose_terminator
sIllumisePose257:
ax_pose 42, 0x01e6, 0x90e8, 0x7c00
ax_pose_terminator
sIllumisePose258:
ax_pose 3, 0x01e9, 0x90ec, 0x7c00
ax_pose_terminator
.align 2
sIllumiseAnims_1_1:
ax_anim 4, 0, 0, 0, -2, 0, 0,
ax_anim 4, 0, 1, 0, 0, 0, 2,
ax_anim 4, 0, 0, 0, 1, 0, 3,
ax_anim 4, 0, 2, 0, 1, 0, 3,
ax_anim 4, 0, 0, 0, 0, 0, 2,
ax_anim 4, 0, 1, 0, -1, 0, 1,
ax_anim 4, 0, 0, 0, -2, 0, 0,
ax_anim 4, 0, 2, 0, -3, 0, -1,
ax_anim_terminator
sIllumiseAnims_1_2:
ax_anim 4, 0, 3, 0, -2, 0, 0,
ax_anim 4, 0, 4, 1, -2, 1, 1,
ax_anim 4, 0, 3, 2, -3, 2, 2,
ax_anim 4, 0, 5, 2, -4, 2, 2,
ax_anim 4, 0, 3, 1, -5, 1, 1,
ax_anim 4, 0, 4, 0, -4, 0, 0,
ax_anim 4, 0, 3, -1, -3, -1, -1,
ax_anim 4, 0, 5, -1, -2, -1, -1,
ax_anim_terminator
sIllumiseAnims_1_3:
ax_anim 4, 0, 6, 0, -2, 0, 0,
ax_anim 4, 0, 7, 1, -3, 1, 0,
ax_anim 4, 0, 6, 2, -4, 2, 0,
ax_anim 4, 0, 8, 2, -5, 2, 0,
ax_anim 4, 0, 6, 1, -5, 1, 0,
ax_anim 4, 0, 7, 0, -4, 0, 0,
ax_anim 4, 0, 6, -1, -3, -1, 0,
ax_anim 4, 0, 8, -1, -2, -1, 0,
ax_anim_terminator
sIllumiseAnims_1_4:
ax_anim 4, 0, 9, 0, -2, 0, 0,
ax_anim 4, 0, 10, 1, -3, 1, -1,
ax_anim 4, 0, 9, 2, -5, 2, -2,
ax_anim 4, 0, 11, 2, -6, 2, -2,
ax_anim 4, 0, 9, 1, -7, 1, -1,
ax_anim 4, 0, 10, 0, -6, 0, 0,
ax_anim 4, 0, 9, -1, -3, -1, 1,
ax_anim 4, 0, 11, -1, -2, -1, 1,
ax_anim_terminator
sIllumiseAnims_1_5:
ax_anim 4, 0, 12, 0, -2, 0, 0,
ax_anim 4, 0, 13, 0, -3, 0, -1,
ax_anim 4, 0, 12, 0, -5, 0, -2,
ax_anim 4, 0, 14, 0, -6, 0, -3,
ax_anim 4, 0, 12, 0, -6, 0, -3,
ax_anim 4, 0, 13, 0, -5, 0, -2,
ax_anim 4, 0, 12, 0, -3, 0, -1,
ax_anim 4, 0, 14, 0, -2, 0, 0,
ax_anim_terminator
sIllumiseAnims_1_6:
ax_anim 4, 0, 15, 0, -2, 0, 0,
ax_anim 4, 0, 16, -1, -3, -1, -1,
ax_anim 4, 0, 15, -2, -5, -2, -2,
ax_anim 4, 0, 17, -2, -6, -2, -2,
ax_anim 4, 0, 15, -1, -7, -1, -1,
ax_anim 4, 0, 16, 0, -6, 0, 0,
ax_anim 4, 0, 15, 1, -3, 1, 1,
ax_anim 4, 0, 17, 1, -2, 1, 1,
ax_anim_terminator
sIllumiseAnims_1_7:
ax_anim 4, 0, 18, 0, -2, 0, 0,
ax_anim 4, 0, 19, -1, -3, -1, 0,
ax_anim 4, 0, 18, -2, -4, -2, 0,
ax_anim 4, 0, 20, -2, -5, -2, 0,
ax_anim 4, 0, 18, -1, -5, -1, 0,
ax_anim 4, 0, 19, 0, -4, 0, 0,
ax_anim 4, 0, 18, 1, -3, 1, 0,
ax_anim 4, 0, 20, 1, -2, 1, 0,
ax_anim_terminator
sIllumiseAnims_1_8:
ax_anim 4, 0, 21, 0, -2, 0, 0,
ax_anim 4, 0, 22, -1, -2, -1, 1,
ax_anim 4, 0, 21, -2, -3, -2, 2,
ax_anim 4, 0, 23, -2, -4, -2, 2,
ax_anim 4, 0, 21, -1, -5, -1, 1,
ax_anim 4, 0, 22, 0, -4, 0, 0,
ax_anim 4, 0, 21, 1, -3, 1, -1,
ax_anim 4, 0, 23, 1, -2, 1, -1,
ax_anim_terminator
.align 2
sIllumiseAnims_2_1:
ax_anim 2, 0, 32, 0, -1, 0, 0,
ax_anim 2, 0, 32, 0, -3, 0, 0,
ax_anim 2, 0, 36, 0, -4, 0, 0,
ax_anim 2, 0, 35, 0, -4, 0, 0,
ax_anim 2, 0, 36, 0, -4, 0, 0,
ax_anim 2, 2, 35, 0, -4, 0, 0,
ax_anim 1, 0, 36, 0, 7, 0, 7,
ax_anim 1, 0, 35, 0, 14, 0, 14,
ax_anim 2, 1, 36, 0, 22, 0, 22,
ax_anim 2, 0, 35, 1, 22, 1, 22,
ax_anim 2, 0, 36, 0, 22, 0, 22,
ax_anim 2, 0, 35, 1, 22, 1, 22,
ax_anim 2, 0, 36, 0, 22, 0, 22,
ax_anim 2, 0, 33, 0, 10, 0, 10,
ax_anim 2, 0, 34, 0, 4, 0, 4,
ax_anim_terminator
sIllumiseAnims_2_2:
ax_anim 2, 0, 37, 0, -1, 0, 0,
ax_anim 2, 0, 37, 0, -2, 0, 0,
ax_anim 2, 0, 41, 0, -4, 0, 0,
ax_anim 2, 0, 40, 0, -4, 0, 0,
ax_anim 2, 0, 41, 0, -4, 0, 0,
ax_anim 2, 2, 40, 0, -4, 0, 0,
ax_anim 1, 0, 41, 7, 7, 7, 7,
ax_anim 1, 0, 40, 14, 14, 14, 14,
ax_anim 2, 1, 41, 21, 22, 21, 22,
ax_anim 2, 0, 40, 22, 21, 22, 21,
ax_anim 2, 0, 41, 21, 22, 21, 22,
ax_anim 2, 0, 40, 22, 21, 22, 21,
ax_anim 2, 0, 41, 21, 22, 21, 22,
ax_anim 2, 0, 38, 10, 10, 10, 10,
ax_anim 2, 0, 39, 4, 4, 4, 4,
ax_anim_terminator
sIllumiseAnims_2_3:
ax_anim 2, 0, 42, 0, -1, 0, 0,
ax_anim 2, 0, 42, 0, -2, 0, 0,
ax_anim 2, 0, 46, 0, -4, 0, 0,
ax_anim 2, 0, 45, 0, -4, 0, 0,
ax_anim 2, 0, 46, 0, -4, 0, 0,
ax_anim 2, 2, 45, 0, -4, 0, 0,
ax_anim 1, 0, 46, 7, -3, 7, 0,
ax_anim 1, 0, 45, 14, -2, 14, 0,
ax_anim 2, 1, 46, 19, 0, 19, 0,
ax_anim 2, 0, 45, 19, 1, 19, 1,
ax_anim 2, 0, 46, 19, 0, 19, 0,
ax_anim 2, 0, 45, 19, 1, 19, 1,
ax_anim 2, 0, 46, 19, 0, 19, 0,
ax_anim 2, 0, 43, 10, -2, 10, 0,
ax_anim 2, 0, 44, 4, -1, 4, 0,
ax_anim_terminator
sIllumiseAnims_2_4:
ax_anim 2, 0, 47, 0, -1, 0, 0,
ax_anim 2, 0, 47, 0, -2, 0, 0,
ax_anim 2, 0, 51, 0, -4, 0, 0,
ax_anim 2, 0, 50, 0, -4, 0, 0,
ax_anim 2, 0, 51, 0, -4, 0, 0,
ax_anim 2, 2, 50, 0, -4, 0, 0,
ax_anim 1, 0, 51, 7, -10, 7, -7,
ax_anim 1, 0, 50, 14, -15, 14, -14,
ax_anim 2, 1, 51, 20, -19, 20, -19,
ax_anim 2, 0, 50, 21, -18, 21, -18,
ax_anim 2, 0, 51, 20, -19, 20, -19,
ax_anim 2, 0, 50, 21, -18, 21, -18,
ax_anim 2, 0, 51, 20, -19, 20, -19,
ax_anim 2, 0, 48, 10, -10, 10, -10,
ax_anim 2, 0, 49, 4, -4, 4, -4,
ax_anim_terminator
sIllumiseAnims_2_5:
ax_anim 2, 0, 52, 0, -1, 0, 0,
ax_anim 2, 0, 52, 0, -3, 0, 0,
ax_anim 2, 0, 56, 0, -4, 0, 0,
ax_anim 2, 0, 55, 0, -4, 0, 0,
ax_anim 2, 0, 56, 0, -4, 0, 0,
ax_anim 2, 2, 55, 0, -4, 0, 0,
ax_anim 1, 0, 56, 0, -7, 0, -7,
ax_anim 1, 0, 55, 0, -13, 0, -13,
ax_anim 2, 1, 56, 0, -18, 0, -18,
ax_anim 2, 0, 55, 1, -18, 1, -18,
ax_anim 2, 0, 56, 0, -18, 0, -18,
ax_anim 2, 0, 55, 1, -18, 1, -18,
ax_anim 2, 0, 56, 0, -18, 0, -18,
ax_anim 2, 0, 53, 0, -10, 0, -10,
ax_anim 2, 0, 54, 0, -4, 0, -4,
ax_anim_terminator
sIllumiseAnims_2_6:
ax_anim 2, 0, 57, 0, -1, 0, 0,
ax_anim 2, 0, 57, 0, -2, 0, 0,
ax_anim 2, 0, 61, 0, -4, 0, 0,
ax_anim 2, 0, 60, 0, -4, 0, 0,
ax_anim 2, 0, 61, 0, -4, 0, 0,
ax_anim 2, 2, 60, 0, -4, 0, 0,
ax_anim 1, 0, 61, -7, -10, -7, -7,
ax_anim 1, 0, 60, -14, -15, -14, -14,
ax_anim 2, 1, 61, -20, -19, -20, -19,
ax_anim 2, 0, 60, -21, -18, -21, -18,
ax_anim 2, 0, 61, -20, -19, -20, -19,
ax_anim 2, 0, 60, -21, -18, -21, -18,
ax_anim 2, 0, 61, -20, -19, -20, -19,
ax_anim 2, 0, 58, -10, -10, -10, -10,
ax_anim 2, 0, 59, -4, -4, -4, -4,
ax_anim_terminator
sIllumiseAnims_2_7:
ax_anim 2, 0, 62, 0, -1, 0, 0,
ax_anim 2, 0, 62, 0, -2, 0, 0,
ax_anim 2, 0, 66, 0, -4, 0, 0,
ax_anim 2, 0, 65, 0, -4, 0, 0,
ax_anim 2, 0, 66, 0, -4, 0, 0,
ax_anim 2, 2, 65, 0, -4, 0, 0,
ax_anim 1, 0, 66, -7, -3, -7, 0,
ax_anim 1, 0, 65, -14, -2, -14, 0,
ax_anim 2, 1, 66, -19, 0, -19, 0,
ax_anim 2, 0, 65, -19, 1, -19, 1,
ax_anim 2, 0, 66, -19, 0, -19, 0,
ax_anim 2, 0, 65, -19, 1, -19, 1,
ax_anim 2, 0, 66, -19, 0, -19, 0,
ax_anim 2, 0, 63, -10, -2, -10, 0,
ax_anim 2, 0, 64, -4, -1, -4, 0,
ax_anim_terminator
sIllumiseAnims_2_8:
ax_anim 2, 0, 67, 0, -1, 0, 0,
ax_anim 2, 0, 67, 0, -2, 0, 0,
ax_anim 2, 0, 71, 0, -4, 0, 0,
ax_anim 2, 0, 70, 0, -4, 0, 0,
ax_anim 2, 0, 71, 0, -4, 0, 0,
ax_anim 2, 2, 70, 0, -4, 0, 0,
ax_anim 1, 0, 71, -7, 7, -7, 7,
ax_anim 1, 0, 70, -14, 14, -14, 14,
ax_anim 2, 1, 71, -21, 22, -21, 22,
ax_anim 2, 0, 70, -22, 21, -22, 21,
ax_anim 2, 0, 71, -21, 22, -21, 22,
ax_anim 2, 0, 70, -22, 21, -22, 21,
ax_anim 2, 0, 71, -21, 22, -21, 22,
ax_anim 2, 0, 68, -10, 10, -10, 10,
ax_anim 2, 0, 69, -4, 4, -4, 4,
ax_anim_terminator
.align 2
sIllumiseAnims_3_1:
ax_anim 2, 0, 72, 0, -1, 0, 0,
ax_anim 2, 0, 74, 0, -3, 0, 0,
ax_anim 2, 0, 76, 0, -4, 0, 0,
ax_anim 2, 0, 75, 0, -4, 0, 0,
ax_anim 2, 0, 76, 0, -4, 0, 0,
ax_anim 2, 2, 75, 0, -4, 0, 0,
ax_anim 1, 0, 76, 0, 10, 0, 10,
ax_anim 1, 0, 75, 0, 23, 0, 23,
ax_anim 2, 1, 76, 0, 46, 0, 46,
ax_anim 2, 0, 75, 1, 46, 1, 46,
ax_anim 2, 0, 76, 0, 46, 0, 46,
ax_anim 2, 0, 75, 1, 46, 1, 46,
ax_anim 2, 0, 76, 0, 46, 0, 46,
ax_anim 2, 0, 75, 0, 20, 0, 20,
ax_anim 2, 0, 76, 0, 8, 0, 8,
ax_anim_terminator
sIllumiseAnims_3_2:
ax_anim 2, 0, 77, 0, -1, 0, 0,
ax_anim 2, 0, 79, 0, -2, 0, 0,
ax_anim 2, 0, 81, 0, -4, 0, 0,
ax_anim 2, 0, 80, 0, -4, 0, 0,
ax_anim 2, 0, 81, 0, -4, 0, 0,
ax_anim 2, 2, 80, 0, -4, 0, 0,
ax_anim 1, 0, 81, 10, 10, 10, 10,
ax_anim 1, 0, 80, 23, 23, 23, 23,
ax_anim 2, 1, 81, 46, 47, 46, 47,
ax_anim 2, 0, 80, 47, 46, 47, 46,
ax_anim 2, 0, 81, 46, 47, 46, 47,
ax_anim 2, 0, 80, 47, 46, 47, 46,
ax_anim 2, 0, 81, 46, 47, 46, 47,
ax_anim 2, 0, 80, 20, 20, 20, 20,
ax_anim 2, 0, 81, 8, 8, 8, 8,
ax_anim_terminator
sIllumiseAnims_3_3:
ax_anim 2, 0, 82, 0, -1, 0, 0,
ax_anim 2, 0, 84, 0, -2, 0, 0,
ax_anim 2, 0, 86, 0, -4, 0, 0,
ax_anim 2, 0, 85, 0, -4, 0, 0,
ax_anim 2, 0, 86, 0, -4, 0, 0,
ax_anim 2, 2, 85, 0, -4, 0, 0,
ax_anim 1, 0, 86, 14, -3, 14, 0,
ax_anim 1, 0, 85, 21, -2, 21, 0,
ax_anim 2, 1, 86, 42, 0, 42, 0,
ax_anim 2, 0, 85, 42, 1, 42, 1,
ax_anim 2, 0, 86, 42, 0, 42, 0,
ax_anim 2, 0, 85, 42, 1, 42, 1,
ax_anim 2, 0, 86, 42, 0, 42, 0,
ax_anim 2, 0, 85, 22, -2, 22, 0,
ax_anim 2, 0, 86, 10, -1, 10, 0,
ax_anim_terminator
sIllumiseAnims_3_4:
ax_anim 2, 0, 87, 0, -1, 0, 0,
ax_anim 2, 0, 89, 0, -2, 0, 0,
ax_anim 2, 0, 91, 0, -4, 0, 0,
ax_anim 2, 0, 90, 0, -4, 0, 0,
ax_anim 2, 0, 91, 0, -4, 0, 0,
ax_anim 2, 2, 90, 0, -4, 0, 0,
ax_anim 1, 0, 91, 10, -10, 10, -10,
ax_anim 1, 0, 90, 21, -21, 21, -21,
ax_anim 2, 1, 91, 44, -41, 44, -41,
ax_anim 2, 0, 90, 45, -40, 45, -40,
ax_anim 2, 0, 91, 44, -41, 44, -41,
ax_anim 2, 0, 90, 45, -40, 45, -40,
ax_anim 2, 0, 91, 44, -41, 44, -41,
ax_anim 2, 0, 90, 19, -19, 19, -19,
ax_anim 2, 0, 91, 8, -8, 8, -8,
ax_anim_terminator
sIllumiseAnims_3_5:
ax_anim 2, 0, 92, 0, -1, 0, 0,
ax_anim 2, 0, 94, 0, -3, 0, 0,
ax_anim 2, 0, 96, 0, -4, 0, 0,
ax_anim 2, 0, 95, 0, -4, 0, 0,
ax_anim 2, 0, 96, 0, -4, 0, 0,
ax_anim 2, 2, 95, 0, -4, 0, 0,
ax_anim 1, 0, 96, 0, -11, 0, -11,
ax_anim 1, 0, 95, 0, -23, 0, -23,
ax_anim 2, 1, 96, 0, -42, 0, -42,
ax_anim 2, 0, 95, 1, -42, 1, -42,
ax_anim 2, 0, 96, 0, -42, 0, -42,
ax_anim 2, 0, 95, 1, -42, 1, -42,
ax_anim 2, 0, 96, 0, -42, 0, -42,
ax_anim 2, 0, 95, 0, -21, 0, -21,
ax_anim 2, 0, 96, 0, -8, 0, -8,
ax_anim_terminator
sIllumiseAnims_3_6:
ax_anim 2, 0, 97, 0, -1, 0, 0,
ax_anim 2, 0, 99, 0, -2, 0, 0,
ax_anim 2, 0, 101, 0, -4, 0, 0,
ax_anim 2, 0, 100, 0, -4, 0, 0,
ax_anim 2, 0, 101, 0, -4, 0, 0,
ax_anim 2, 2, 100, 0, -4, 0, 0,
ax_anim 1, 0, 101, -10, -10, -10, -10,
ax_anim 1, 0, 100, -21, -21, -21, -21,
ax_anim 2, 1, 101, -44, -41, -44, -41,
ax_anim 2, 0, 100, -45, -40, -45, -40,
ax_anim 2, 0, 101, -44, -41, -44, -41,
ax_anim 2, 0, 100, -45, -40, -45, -40,
ax_anim 2, 0, 101, -44, -41, -44, -41,
ax_anim 2, 0, 100, -19, -19, -19, -19,
ax_anim 2, 0, 101, -8, -8, -8, -8,
ax_anim_terminator
sIllumiseAnims_3_7:
ax_anim 2, 0, 102, 0, -1, 0, 0,
ax_anim 2, 0, 104, 0, -2, 0, 0,
ax_anim 2, 0, 106, 0, -4, 0, 0,
ax_anim 2, 0, 105, 0, -4, 0, 0,
ax_anim 2, 0, 106, 0, -4, 0, 0,
ax_anim 2, 2, 105, 0, -4, 0, 0,
ax_anim 1, 0, 106, -14, -3, -14, 0,
ax_anim 1, 0, 105, -21, -2, -21, 0,
ax_anim 2, 1, 106, -42, 0, -42, 0,
ax_anim 2, 0, 105, -42, 1, -42, 1,
ax_anim 2, 0, 106, -42, 0, -42, 0,
ax_anim 2, 0, 105, -42, 1, -42, 1,
ax_anim 2, 0, 106, -42, 0, -42, 0,
ax_anim 2, 0, 105, -22, -2, -22, 0,
ax_anim 2, 0, 106, -10, -1, -10, 0,
ax_anim_terminator
sIllumiseAnims_3_8:
ax_anim 2, 0, 107, 0, -1, 0, 0,
ax_anim 2, 0, 109, 0, -2, 0, 0,
ax_anim 2, 0, 111, 0, -4, 0, 0,
ax_anim 2, 0, 110, 0, -4, 0, 0,
ax_anim 2, 0, 111, 0, -4, 0, 0,
ax_anim 2, 2, 110, 0, -4, 0, 0,
ax_anim 1, 0, 111, -10, 10, -10, 10,
ax_anim 1, 0, 110, -23, 23, -23, 23,
ax_anim 2, 1, 111, -46, 47, -46, 47,
ax_anim 2, 0, 110, -47, 46, -47, 46,
ax_anim 2, 0, 111, -46, 47, -46, 47,
ax_anim 2, 0, 110, -47, 46, -47, 46,
ax_anim 2, 0, 111, -46, 47, -46, 47,
ax_anim 2, 0, 110, -20, 20, -20, 20,
ax_anim 2, 0, 111, -8, 8, -8, 8,
ax_anim_terminator
.align 2
sIllumiseAnims_4_1:
ax_anim 2, 0, 113, 0, -2, 0, -2,
ax_anim 6, 2, 113, 0, -3, 0, -3,
ax_anim 2, 0, 112, 0, -1, 0, -1,
ax_anim 2, 1, 114, 0, 3, 0, 2,
ax_anim 2, 0, 114, 1, 3, 1, 2,
ax_anim 2, 0, 114, 0, 3, 0, 2,
ax_anim 2, 0, 114, 1, 3, 1, 2,
ax_anim 2, 0, 114, 0, 3, 0, 2,
ax_anim 2, 0, 114, 1, 3, 1, 2,
ax_anim 2, 0, 114, 0, 3, 0, 2,
ax_anim 2, 0, 112, 0, 1, 0, 1,
ax_anim_terminator
sIllumiseAnims_4_2:
ax_anim 2, 0, 116, -2, -2, -2, -2,
ax_anim 6, 2, 116, -3, -3, -3, -3,
ax_anim 2, 0, 115, -1, -1, -1, -1,
ax_anim 2, 1, 117, 2, 2, 1, 1,
ax_anim 2, 0, 117, 3, 1, 2, 0,
ax_anim 2, 0, 117, 2, 2, 1, 1,
ax_anim 2, 0, 117, 3, 1, 2, 0,
ax_anim 2, 0, 117, 2, 2, 1, 1,
ax_anim 2, 0, 117, 3, 1, 2, 0,
ax_anim 2, 0, 117, 2, 2, 1, 1,
ax_anim 2, 0, 115, 1, 1, 1, 1,
ax_anim_terminator
sIllumiseAnims_4_3:
ax_anim 2, 0, 119, -2, 0, -2, 0,
ax_anim 6, 2, 119, -3, 0, -3, 0,
ax_anim 2, 0, 118, -1, 0, -1, 0,
ax_anim 2, 1, 120, 2, 0, 2, 0,
ax_anim 2, 0, 120, 2, 1, 2, 1,
ax_anim 2, 0, 120, 2, 0, 2, 0,
ax_anim 2, 0, 120, 2, 1, 2, 1,
ax_anim 2, 0, 120, 2, 0, 2, 0,
ax_anim 2, 0, 120, 2, 1, 2, 1,
ax_anim 2, 0, 120, 2, 0, 2, 0,
ax_anim 2, 0, 118, 1, 0, 1, 0,
ax_anim_terminator
sIllumiseAnims_4_4:
ax_anim 2, 0, 122, -2, 2, -2, 2,
ax_anim 6, 2, 122, -3, 3, -3, 3,
ax_anim 2, 0, 121, -1, 1, -1, 1,
ax_anim 2, 1, 123, 2, -2, 1, -1,
ax_anim 2, 0, 123, 3, -1, 2, 0,
ax_anim 2, 0, 123, 2, -2, 1, -1,
ax_anim 2, 0, 123, 3, -1, 2, 0,
ax_anim 2, 0, 123, 2, -2, 1, -1,
ax_anim 2, 0, 123, 3, -1, 2, 0,
ax_anim 2, 0, 123, 2, -2, 1, -1,
ax_anim 2, 0, 121, 1, -1, 1, -1,
ax_anim_terminator
sIllumiseAnims_4_5:
ax_anim 2, 0, 125, 0, 2, 0, 2,
ax_anim 6, 2, 125, 0, 3, 0, 3,
ax_anim 2, 0, 124, 0, 1, 0, 1,
ax_anim 2, 1, 126, 0, -3, 0, -2,
ax_anim 2, 0, 126, 1, -3, 1, -2,
ax_anim 2, 0, 126, 0, -3, 0, -2,
ax_anim 2, 0, 126, 1, -3, 1, -2,
ax_anim 2, 0, 126, 0, -3, 0, -2,
ax_anim 2, 0, 126, 1, -3, 1, -2,
ax_anim 2, 0, 126, 0, -3, 0, -2,
ax_anim 2, 0, 124, 0, -1, 0, -1,
ax_anim_terminator
sIllumiseAnims_4_6:
ax_anim 2, 0, 128, 2, 2, 2, 2,
ax_anim 6, 2, 128, 3, 3, 3, 3,
ax_anim 2, 0, 127, 1, 1, 1, 1,
ax_anim 2, 1, 129, -2, -2, -1, -1,
ax_anim 2, 0, 129, -3, -1, -2, 0,
ax_anim 2, 0, 129, -2, -2, -1, -1,
ax_anim 2, 0, 129, -3, -1, -2, 0,
ax_anim 2, 0, 129, -2, -2, -1, -1,
ax_anim 2, 0, 129, -3, -1, -2, 0,
ax_anim 2, 0, 129, -2, -2, -1, -1,
ax_anim 2, 0, 127, -1, -1, -1, -1,
ax_anim_terminator
sIllumiseAnims_4_7:
ax_anim 2, 0, 131, 2, 0, 2, 0,
ax_anim 6, 2, 131, 3, 0, 3, 0,
ax_anim 2, 0, 130, 1, 0, 1, 0,
ax_anim 2, 1, 132, -2, 0, -2, 0,
ax_anim 2, 0, 132, -2, 1, -2, 1,
ax_anim 2, 0, 132, -2, 0, -2, 0,
ax_anim 2, 0, 132, -2, 1, -2, 1,
ax_anim 2, 0, 132, -2, 0, -2, 0,
ax_anim 2, 0, 132, -2, 1, -2, 1,
ax_anim 2, 0, 132, -2, 0, -2, 0,
ax_anim 2, 0, 130, -1, 0, -1, 0,
ax_anim_terminator
sIllumiseAnims_4_8:
ax_anim 2, 0, 134, 2, -2, 2, -2,
ax_anim 6, 2, 134, 3, -3, 3, -3,
ax_anim 2, 0, 133, 1, -1, 1, -1,
ax_anim 2, 1, 135, -2, 2, -1, 1,
ax_anim 2, 0, 135, -3, 1, -2, 0,
ax_anim 2, 0, 135, -2, 2, -1, 1,
ax_anim 2, 0, 135, -3, 1, -2, 0,
ax_anim 2, 0, 135, -2, 2, -1, 1,
ax_anim 2, 0, 135, -3, 1, -2, 0,
ax_anim 2, 0, 135, -2, 2, -1, 1,
ax_anim 2, 0, 133, -1, 1, -1, 1,
ax_anim_terminator
.align 2
sIllumiseAnims_5_1:
ax_anim 2, 0, 136, 0, -2, 0, 0,
ax_anim 4, 0, 136, 0, -5, 0, 0,
ax_anim 2, 0, 139, 0, -5, 0, 0,
ax_anim 2, 0, 140, 1, -5, 1, 0,
ax_anim 2, 0, 140, 2, -6, 2, 0,
ax_anim 2, 0, 139, 2, -6, 2, 0,
ax_anim 2, 0, 139, 1, -5, 1, 0,
ax_anim 2, 2, 140, 0, -5, 0, 0,
ax_anim 2, 0, 140, -1, -5, -1, 0,
ax_anim 2, 0, 140, -2, -6, -2, 0,
ax_anim 2, 0, 139, -2, -6, -2, 0,
ax_anim 2, 0, 139, -1, -5, -1, 0,
ax_anim 2, 0, 136, 0, -5, 0, 0,
ax_anim 2, 0, 136, 0, -2, 0, 0,
ax_anim_terminator
sIllumiseAnims_5_2:
ax_anim 2, 0, 141, 0, -2, 0, 0,
ax_anim 4, 0, 141, 0, -5, 0, 0,
ax_anim 2, 0, 144, 0, -5, 0, 0,
ax_anim 2, 0, 145, 1, -6, 1, -1,
ax_anim 2, 0, 145, 2, -8, 2, -2,
ax_anim 2, 0, 144, 2, -8, 2, -2,
ax_anim 2, 0, 144, 1, -6, 1, -1,
ax_anim 2, 2, 145, 0, -5, 0, 0,
ax_anim 2, 0, 145, -1, -4, -1, 1,
ax_anim 2, 0, 145, -2, -5, -2, 1,
ax_anim 2, 0, 144, -2, -5, -2, 1,
ax_anim 2, 0, 144, -1, -4, -1, 1,
ax_anim 2, 0, 141, 0, -5, 0, 0,
ax_anim 2, 0, 141, 0, -2, 0, 0,
ax_anim_terminator
sIllumiseAnims_5_3:
ax_anim 2, 0, 146, 0, -2, 0, 0,
ax_anim 4, 0, 146, -1, -5, 0, 0,
ax_anim 2, 0, 149, 0, -5, 0, 0,
ax_anim 2, 0, 150, 0, -6, 0, -1,
ax_anim 2, 0, 150, 0, -7, 0, -2,
ax_anim 2, 0, 149, 0, -8, 0, -2,
ax_anim 2, 0, 149, 0, -6, 0, -1,
ax_anim 2, 2, 150, 0, -5, 0, 0,
ax_anim 2, 0, 150, 0, -4, 0, 1,
ax_anim 2, 0, 150, 0, -5, 0, 2,
ax_anim 2, 0, 149, 0, -5, 0, 2,
ax_anim 2, 0, 149, 0, -4, 0, 1,
ax_anim 2, 0, 146, -1, -5, 0, 0,
ax_anim 2, 0, 146, 0, -2, 0, 0,
ax_anim_terminator
sIllumiseAnims_5_4:
ax_anim 2, 0, 151, 0, -2, 0, 0,
ax_anim 4, 0, 151, 0, -5, 0, 0,
ax_anim 2, 0, 154, 0, -5, 0, 0,
ax_anim 2, 0, 155, -1, -6, -1, -1,
ax_anim 2, 0, 155, -2, -8, -2, -3,
ax_anim 2, 0, 154, -2, -8, -2, -3,
ax_anim 2, 0, 154, -1, -6, -1, -1,
ax_anim 2, 2, 155, 0, -5, 0, 0,
ax_anim 2, 0, 155, 1, -4, 1, 1,
ax_anim 2, 0, 155, 2, -5, 2, 1,
ax_anim 2, 0, 154, 2, -5, 2, 1,
ax_anim 2, 0, 154, 1, -4, 1, 1,
ax_anim 2, 0, 151, 0, -5, 0, 0,
ax_anim 2, 0, 151, 0, -2, 0, 0,
ax_anim_terminator
sIllumiseAnims_5_5:
ax_anim 2, 0, 156, 0, -2, 0, 0,
ax_anim 4, 0, 156, 0, -5, 0, 0,
ax_anim 2, 0, 159, 0, -5, 0, 0,
ax_anim 2, 0, 160, 1, -5, 1, 0,
ax_anim 2, 0, 160, 2, -6, 2, 0,
ax_anim 2, 0, 159, 2, -6, 2, 0,
ax_anim 2, 0, 159, 1, -5, 1, 0,
ax_anim 2, 2, 160, 0, -5, 0, 0,
ax_anim 2, 0, 160, -1, -5, -1, 0,
ax_anim 2, 0, 160, -2, -6, -2, 0,
ax_anim 2, 0, 159, -2, -6, -2, 0,
ax_anim 2, 0, 159, -1, -5, -1, 0,
ax_anim 2, 0, 156, 0, -5, 0, 0,
ax_anim 2, 0, 156, 0, -2, 0, 0,
ax_anim_terminator
sIllumiseAnims_5_6:
ax_anim 2, 0, 161, 0, -2, 0, 0,
ax_anim 4, 0, 161, 0, -5, 0, 0,
ax_anim 2, 0, 164, 0, -5, 0, 0,
ax_anim 2, 0, 165, 1, -6, 1, -1,
ax_anim 2, 0, 165, 2, -8, 2, -3,
ax_anim 2, 0, 164, 2, -8, 2, -3,
ax_anim 2, 0, 164, 1, -6, 1, -1,
ax_anim 2, 2, 165, 0, -5, 0, 0,
ax_anim 2, 0, 165, -1, -4, -1, 1,
ax_anim 2, 0, 165, -2, -5, -2, 1,
ax_anim 2, 0, 164, -2, -5, -2, 1,
ax_anim 2, 0, 164, -1, -4, -1, 1,
ax_anim 2, 0, 161, 0, -5, 0, 0,
ax_anim 2, 0, 161, 0, -2, 0, 0,
ax_anim_terminator
sIllumiseAnims_5_7:
ax_anim 2, 0, 166, 0, -2, 0, 0,
ax_anim 4, 0, 166, 1, -5, 0, 0,
ax_anim 2, 0, 169, 0, -5, 0, 0,
ax_anim 2, 0, 170, 0, -6, 0, -1,
ax_anim 2, 0, 170, 0, -7, 0, -2,
ax_anim 2, 0, 169, 0, -8, 0, -2,
ax_anim 2, 0, 169, 0, -6, 0, -1,
ax_anim 2, 2, 170, 0, -5, 0, 0,
ax_anim 2, 0, 170, 0, -4, 0, 1,
ax_anim 2, 0, 170, 0, -5, 0, 2,
ax_anim 2, 0, 169, 0, -5, 0, 2,
ax_anim 2, 0, 169, 0, -4, 0, 1,
ax_anim 2, 0, 166, 1, -5, 0, 0,
ax_anim 2, 0, 166, 0, -2, 0, 0,
ax_anim_terminator
sIllumiseAnims_5_8:
ax_anim 2, 0, 171, 0, -2, 0, 0,
ax_anim 4, 0, 171, 0, -5, 0, 0,
ax_anim 2, 0, 174, 0, -5, 0, 0,
ax_anim 2, 0, 175, -1, -6, -1, -1,
ax_anim 2, 0, 175, -2, -8, -2, -2,
ax_anim 2, 0, 174, -2, -8, -2, -2,
ax_anim 2, 0, 174, -1, -6, -1, -1,
ax_anim 2, 2, 175, 0, -5, 0, 0,
ax_anim 2, 0, 175, 1, -4, 1, 1,
ax_anim 2, 0, 175, 2, -5, 2, 1,
ax_anim 2, 0, 174, 2, -5, 2, 1,
ax_anim 2, 0, 174, 1, -4, 1, 1,
ax_anim 2, 0, 171, 0, -5, 0, 0,
ax_anim 2, 0, 171, 0, -2, 0, 0,
ax_anim_terminator
.align 2
sIllumiseAnims_6_1:
ax_anim 30, 0, 176, 0, 0, 0, 0,
ax_anim 35, 0, 177, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sIllumiseAnims_7_1:
ax_anim 2, 0, 178, 0, -4, 0, -4,
ax_anim 8, 0, 178, 0, -5, 0, -5,
ax_anim_terminator
sIllumiseAnims_7_2:
ax_anim 2, 0, 179, -4, -4, -4, -4,
ax_anim 8, 0, 179, -5, -5, -5, -5,
ax_anim_terminator
sIllumiseAnims_7_3:
ax_anim 2, 0, 180, -4, 0, -4, 0,
ax_anim 8, 0, 180, -5, 0, -5, 0,
ax_anim_terminator
sIllumiseAnims_7_4:
ax_anim 2, 0, 181, -4, 4, -4, 4,
ax_anim 8, 0, 181, -5, 5, -5, 5,
ax_anim_terminator
sIllumiseAnims_7_5:
ax_anim 2, 0, 182, 0, 4, 0, 4,
ax_anim 8, 0, 182, 0, 5, 0, 5,
ax_anim_terminator
sIllumiseAnims_7_6:
ax_anim 2, 0, 183, 4, 4, 4, 4,
ax_anim 8, 0, 183, 5, 5, 5, 5,
ax_anim_terminator
sIllumiseAnims_7_7:
ax_anim 2, 0, 184, 4, 0, 4, 0,
ax_anim 8, 0, 184, 5, 0, 5, 0,
ax_anim_terminator
sIllumiseAnims_7_8:
ax_anim 2, 0, 185, 4, -4, 4, -4,
ax_anim 8, 0, 185, 5, -5, 5, -5,
ax_anim_terminator
.align 2
sIllumiseAnims_8_1:
ax_anim 30, 0, 186, 0, 0, 0, 0,
ax_anim 20, 0, 187, 0, 0, 0, 0,
ax_anim_terminator
sIllumiseAnims_8_2:
ax_anim 30, 0, 188, 0, 0, 0, 0,
ax_anim 20, 0, 189, 0, 0, 0, 0,
ax_anim_terminator
sIllumiseAnims_8_3:
ax_anim 30, 0, 190, 0, 0, 0, 0,
ax_anim 20, 0, 191, 0, 0, 0, 0,
ax_anim_terminator
sIllumiseAnims_8_4:
ax_anim 30, 0, 192, 0, 0, 0, 0,
ax_anim 20, 0, 193, 0, 0, 0, 0,
ax_anim_terminator
sIllumiseAnims_8_5:
ax_anim 30, 0, 194, 0, 0, 0, 0,
ax_anim 20, 0, 195, 0, 0, 0, 0,
ax_anim_terminator
sIllumiseAnims_8_6:
ax_anim 30, 0, 196, 0, 0, 0, 0,
ax_anim 20, 0, 197, 0, 0, 0, 0,
ax_anim_terminator
sIllumiseAnims_8_7:
ax_anim 30, 0, 198, 0, 0, 0, 0,
ax_anim 20, 0, 199, 0, 0, 0, 0,
ax_anim_terminator
sIllumiseAnims_8_8:
ax_anim 30, 0, 200, 0, 0, 0, 0,
ax_anim 20, 0, 201, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sIllumiseAnims_9_1:
ax_anim 2, 0, 202, 0, 0, 0, 0,
ax_anim 1, 0, 203, 7, 5, 7, 5,
ax_anim 2, 0, 204, 10, 15, 10, 15,
ax_anim 2, 0, 205, 7, 21, 7, 21,
ax_anim 3, 0, 206, 0, 23, 0, 23,
ax_anim 2, 3, 207, -7, 21, -7, 21,
ax_anim 2, 0, 208, -10, 15, -10, 15,
ax_anim 1, 0, 209, -7, 5, -7, 5,
ax_anim 1, 0, 202, 0, 0, 0, 0,
ax_anim_terminator
sIllumiseAnims_9_2:
ax_anim 2, 0, 209, 0, 0, 0, 0,
ax_anim 1, 0, 202, 10, 3, 10, 3,
ax_anim 2, 0, 203, 21, 8, 21, 8,
ax_anim 2, 0, 204, 25, 18, 25, 18,
ax_anim 3, 0, 205, 21, 23, 21, 23,
ax_anim 2, 3, 206, 12, 22, 12, 22,
ax_anim 2, 0, 207, 4, 16, 4, 16,
ax_anim 1, 0, 208, 1, 8, 1, 8,
ax_anim 1, 0, 209, 0, 0, 0, 0,
ax_anim_terminator
sIllumiseAnims_9_3:
ax_anim 2, 0, 208, 0, 0, 0, 0,
ax_anim 1, 0, 209, 5, -4, 5, -4,
ax_anim 2, 0, 202, 13, -5, 13, -5,
ax_anim 2, 0, 203, 19, -2, 19, -2,
ax_anim 3, 0, 204, 22, 3, 22, 1,
ax_anim 2, 3, 205, 19, 8, 19, 7,
ax_anim 2, 0, 206, 12, 9, 12, 9,
ax_anim 1, 0, 207, 4, 5, 4, 5,
ax_anim 1, 0, 208, 0, 0, 0, 0,
ax_anim_terminator
sIllumiseAnims_9_4:
ax_anim 2, 0, 207, 0, 0, 0, 0,
ax_anim 1, 0, 208, 1, -5, 1, -5,
ax_anim 2, 0, 209, 4, -15, 4, -15,
ax_anim 2, 0, 202, 14, -21, 14, -21,
ax_anim 3, 0, 203, 23, -22, 23, -23,
ax_anim 2, 3, 204, 27, -13, 27, -14,
ax_anim 2, 0, 205, 20, -6, 20, -6,
ax_anim 1, 0, 206, 9, -2, 9, -2,
ax_anim 1, 0, 207, 0, 0, 0, 0,
ax_anim_terminator
sIllumiseAnims_9_5:
ax_anim 2, 0, 206, 0, 0, 0, 0,
ax_anim 1, 0, 207, -7, -4, -7, -4,
ax_anim 2, 0, 208, -11, -10, -11, -10,
ax_anim 2, 0, 209, -10, -21, -10, -21,
ax_anim 3, 0, 202, 0, -23, 0, -23,
ax_anim 2, 3, 203, 10, -21, 10, -21,
ax_anim 2, 0, 204, 11, -10, 11, -10,
ax_anim 1, 0, 205, 7, -4, 7, -4,
ax_anim 1, 0, 206, 0, 0, 0, 0,
ax_anim_terminator
sIllumiseAnims_9_6:
ax_anim 2, 0, 205, 0, 0, 0, 0,
ax_anim 1, 0, 204, -1, -5, -1, -5,
ax_anim 2, 0, 203, -4, -15, -4, -15,
ax_anim 2, 0, 202, -14, -21, -14, -21,
ax_anim 3, 0, 209, -23, -22, -23, -23,
ax_anim 2, 3, 208, -27, -13, -27, -14,
ax_anim 2, 0, 207, -20, -6, -20, -6,
ax_anim 1, 0, 206, -9, -2, -9, -2,
ax_anim 1, 0, 205, 0, 0, 0, 0,
ax_anim_terminator
sIllumiseAnims_9_7:
ax_anim 2, 0, 204, 0, 0, 0, 0,
ax_anim 1, 0, 203, -5, -4, -5, -4,
ax_anim 2, 0, 202, -13, -5, -13, -5,
ax_anim 2, 0, 209, -19, -2, -19, -2,
ax_anim 3, 0, 208, -22, 3, -22, 1,
ax_anim 2, 3, 207, -19, 8, -19, 7,
ax_anim 2, 0, 206, -12, 9, -12, 9,
ax_anim 1, 0, 205, -4, 5, -4, 5,
ax_anim 1, 0, 204, 0, 0, 0, 0,
ax_anim_terminator
sIllumiseAnims_9_8:
ax_anim 2, 0, 203, 0, 0, 0, 0,
ax_anim 1, 0, 202, -10, 3, -10, 3,
ax_anim 2, 0, 209, -21, 8, -21, 8,
ax_anim 2, 0, 208, -25, 18, -25, 18,
ax_anim 3, 0, 207, -21, 23, -21, 23,
ax_anim 2, 3, 206, -12, 22, -12, 22,
ax_anim 2, 0, 205, -4, 16, -4, 16,
ax_anim 1, 0, 204, -1, 8, -1, 8,
ax_anim 1, 0, 203, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sIllumiseAnims_10_1:
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 2, 0, 210, 6, 0, 6, 0,
ax_anim 2, 0, 210, -6, 0, -6, 0,
ax_anim 2, 0, 210, 10, 0, 10, 0,
ax_anim 2, 0, 210, -10, 0, -10, 0,
ax_anim 2, 0, 210, 12, 0, 12, 0,
ax_anim 3, 0, 210, -12, 0, -12, 0,
ax_anim 3, 0, 210, 13, 0, 13, 0,
ax_anim 3, 0, 210, -13, 0, -13, 0,
ax_anim 2, 0, 210, 12, 0, 12, 0,
ax_anim 3, 0, 210, -12, 0, -12, 0,
ax_anim 2, 0, 210, 10, 0, 10, 0,
ax_anim 2, 0, 210, -10, 0, -10, 0,
ax_anim 2, 0, 210, 6, 0, 6, 0,
ax_anim 2, 0, 210, -6, 0, -6, 0,
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim_terminator
sIllumiseAnims_10_2:
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 2, 0, 211, 6, -6, 6, -6,
ax_anim 2, 0, 211, -6, 6, -6, 6,
ax_anim 2, 0, 211, 10, -10, 10, -10,
ax_anim 2, 0, 211, -10, 10, -10, 10,
ax_anim 2, 0, 211, 12, -12, 12, -12,
ax_anim 3, 0, 211, -12, 12, -12, 12,
ax_anim 3, 0, 211, 13, -13, 13, -13,
ax_anim 3, 0, 211, -13, 13, -13, 13,
ax_anim 2, 0, 211, 12, -12, 12, -12,
ax_anim 3, 0, 211, -12, 12, -12, 12,
ax_anim 2, 0, 211, 10, -10, 10, -10,
ax_anim 2, 0, 211, -10, 10, -10, 10,
ax_anim 2, 0, 211, 6, -6, 6, -6,
ax_anim 2, 0, 211, -6, 6, -6, 6,
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim_terminator
sIllumiseAnims_10_3:
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 2, 0, 212, 0, -6, 0, -6,
ax_anim 2, 0, 212, 0, 6, 0, 6,
ax_anim 2, 0, 212, 0, -10, 0, -10,
ax_anim 2, 0, 212, 0, 10, 0, 10,
ax_anim 2, 0, 212, 0, -12, 0, -12,
ax_anim 3, 0, 212, 0, 12, 0, 12,
ax_anim 3, 0, 212, 0, -13, 0, -13,
ax_anim 3, 0, 212, 0, 13, 0, 13,
ax_anim 2, 0, 212, 0, -12, 0, -12,
ax_anim 3, 0, 212, 0, 12, 0, 12,
ax_anim 2, 0, 212, 0, -10, 0, -10,
ax_anim 2, 0, 212, 0, 10, 0, 10,
ax_anim 2, 0, 212, 0, -6, 0, -6,
ax_anim 2, 0, 212, 0, 6, 0, 6,
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim_terminator
sIllumiseAnims_10_4:
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 2, 0, 213, -6, -6, -6, -6,
ax_anim 2, 0, 213, 6, 6, 6, 6,
ax_anim 2, 0, 213, -10, -10, -10, -10,
ax_anim 2, 0, 213, 10, 10, 10, 10,
ax_anim 2, 0, 213, -12, -12, -12, -12,
ax_anim 3, 0, 213, 12, 12, 12, 12,
ax_anim 3, 0, 213, -13, -13, -13, -13,
ax_anim 3, 0, 213, 13, 13, 13, 13,
ax_anim 2, 0, 213, -12, -12, -12, -12,
ax_anim 3, 0, 213, 12, 12, 12, 12,
ax_anim 2, 0, 213, -10, -10, -10, -10,
ax_anim 2, 0, 213, 10, 10, 10, 10,
ax_anim 2, 0, 213, -6, -6, -6, -6,
ax_anim 2, 0, 213, 6, 6, 6, 6,
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim_terminator
sIllumiseAnims_10_5:
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 2, 0, 214, 6, 0, 6, 0,
ax_anim 2, 0, 214, -6, 0, -6, 0,
ax_anim 2, 0, 214, 10, 0, 10, 0,
ax_anim 2, 0, 214, -10, 0, -10, 0,
ax_anim 2, 0, 214, 12, 0, 12, 0,
ax_anim 3, 0, 214, -12, 0, -12, 0,
ax_anim 3, 0, 214, 13, 0, 13, 0,
ax_anim 3, 0, 214, -13, 0, -13, 0,
ax_anim 2, 0, 214, 12, 0, 12, 0,
ax_anim 3, 0, 214, -12, 0, -12, 0,
ax_anim 2, 0, 214, 10, 0, 10, 0,
ax_anim 2, 0, 214, -10, 0, -10, 0,
ax_anim 2, 0, 214, 6, 0, 6, 0,
ax_anim 2, 0, 214, -6, 0, -6, 0,
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim_terminator
sIllumiseAnims_10_6:
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 0, 215, 6, -6, 6, -6,
ax_anim 2, 0, 215, -6, 6, -6, 6,
ax_anim 2, 0, 215, 10, -10, 10, -10,
ax_anim 2, 0, 215, -10, 10, -10, 10,
ax_anim 2, 0, 215, 12, -12, 12, -12,
ax_anim 3, 0, 215, -12, 12, -12, 12,
ax_anim 3, 0, 215, 13, -13, 13, -13,
ax_anim 3, 0, 215, -13, 13, -13, 13,
ax_anim 2, 0, 215, 12, -12, 12, -12,
ax_anim 3, 0, 215, -12, 12, -12, 12,
ax_anim 2, 0, 215, 10, -10, 10, -10,
ax_anim 2, 0, 215, -10, 10, -10, 10,
ax_anim 2, 0, 215, 6, -6, 6, -6,
ax_anim 2, 0, 215, -6, 6, -6, 6,
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim_terminator
sIllumiseAnims_10_7:
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, -6, 0, -6,
ax_anim 2, 0, 216, 0, 6, 0, 6,
ax_anim 2, 0, 216, 0, -10, 0, -10,
ax_anim 2, 0, 216, 0, 10, 0, 10,
ax_anim 2, 0, 216, 0, -12, 0, -12,
ax_anim 3, 0, 216, 0, 12, 0, 12,
ax_anim 3, 0, 216, 0, -13, 0, -13,
ax_anim 3, 0, 216, 0, 13, 0, 13,
ax_anim 2, 0, 216, 0, -12, 0, -12,
ax_anim 3, 0, 216, 0, 12, 0, 12,
ax_anim 2, 0, 216, 0, -10, 0, -10,
ax_anim 2, 0, 216, 0, 10, 0, 10,
ax_anim 2, 0, 216, 0, -6, 0, -6,
ax_anim 2, 0, 216, 0, 6, 0, 6,
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim_terminator
sIllumiseAnims_10_8:
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 0, 217, -6, -6, -6, -6,
ax_anim 2, 0, 217, 6, 6, 6, 6,
ax_anim 2, 0, 217, -10, -10, -10, -10,
ax_anim 2, 0, 217, 10, 10, 10, 10,
ax_anim 2, 0, 217, -12, -12, -12, -12,
ax_anim 3, 0, 217, 12, 12, 12, 12,
ax_anim 3, 0, 217, -13, -13, -13, -13,
ax_anim 3, 0, 217, 13, 13, 13, 13,
ax_anim 2, 0, 217, -12, -12, -12, -12,
ax_anim 3, 0, 217, 12, 12, 12, 12,
ax_anim 2, 0, 217, -10, -10, -10, -10,
ax_anim 2, 0, 217, 10, 10, 10, 10,
ax_anim 2, 0, 217, -6, -6, -6, -6,
ax_anim 2, 0, 217, 6, 6, 6, 6,
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sIllumiseAnims_11_1:
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 1, 0, 219, 0, -10, 0, 0,
ax_anim 2, 0, 219, 0, -16, 0, 0,
ax_anim 3, 0, 219, 0, -20, 0, 0,
ax_anim 4, 0, 219, 0, -22, 0, 0,
ax_anim 4, 0, 218, 0, -23, 0, 0,
ax_anim 3, 0, 220, 0, -22, 0, 0,
ax_anim 2, 0, 220, 0, -18, 0, 0,
ax_anim 1, 0, 220, 0, -12, 0, 0,
ax_anim 2, 2, 218, 0, 0, 0, 0,
ax_anim_terminator
sIllumiseAnims_11_2:
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 1, 0, 222, 0, -10, 0, 0,
ax_anim 2, 0, 222, 0, -16, 0, 0,
ax_anim 3, 0, 222, 0, -20, 0, 0,
ax_anim 4, 0, 222, 0, -22, 0, 0,
ax_anim 4, 0, 221, 0, -23, 0, 0,
ax_anim 3, 0, 223, 0, -22, 0, 0,
ax_anim 2, 0, 223, 0, -18, 0, 0,
ax_anim 1, 0, 223, 0, -12, 0, 0,
ax_anim 2, 2, 221, 0, 0, 0, 0,
ax_anim_terminator
sIllumiseAnims_11_3:
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 1, 0, 225, 0, -10, 0, 0,
ax_anim 2, 0, 225, 0, -16, 0, 0,
ax_anim 3, 0, 225, 0, -20, 0, 0,
ax_anim 4, 0, 225, 0, -22, 0, 0,
ax_anim 4, 0, 224, 0, -23, 0, 0,
ax_anim 3, 0, 226, 0, -22, 0, 0,
ax_anim 2, 0, 226, 0, -18, 0, 0,
ax_anim 1, 0, 226, 0, -12, 0, 0,
ax_anim 2, 2, 224, 0, 0, 0, 0,
ax_anim_terminator
sIllumiseAnims_11_4:
ax_anim 2, 0, 227, 0, 0, 0, 0,
ax_anim 1, 0, 228, 0, -10, 0, 0,
ax_anim 2, 0, 228, 0, -16, 0, 0,
ax_anim 3, 0, 228, 0, -20, 0, 0,
ax_anim 4, 0, 228, 0, -22, 0, 0,
ax_anim 4, 0, 227, 0, -23, 0, 0,
ax_anim 3, 0, 229, 0, -21, 0, 0,
ax_anim 2, 0, 229, 0, -17, 0, 0,
ax_anim 1, 0, 229, 0, -11, 0, 0,
ax_anim 2, 2, 227, 0, 0, 0, 0,
ax_anim_terminator
sIllumiseAnims_11_5:
ax_anim 2, 0, 230, 0, 0, 0, 0,
ax_anim 1, 0, 231, 0, -10, 0, 0,
ax_anim 2, 0, 231, 0, -16, 0, 0,
ax_anim 3, 0, 231, 0, -20, 0, 0,
ax_anim 4, 0, 231, 0, -22, 0, 0,
ax_anim 4, 0, 230, 0, -23, 0, 0,
ax_anim 3, 0, 232, 0, -22, 0, 0,
ax_anim 2, 0, 232, 0, -18, 0, 0,
ax_anim 1, 0, 232, 0, -12, 0, 0,
ax_anim 2, 2, 230, 0, 0, 0, 0,
ax_anim_terminator
sIllumiseAnims_11_6:
ax_anim 2, 0, 233, 0, 0, 0, 0,
ax_anim 1, 0, 234, 0, -10, 0, 0,
ax_anim 2, 0, 234, 0, -16, 0, 0,
ax_anim 3, 0, 234, 0, -20, 0, 0,
ax_anim 4, 0, 234, 0, -22, 0, 0,
ax_anim 4, 0, 233, 0, -23, 0, 0,
ax_anim 3, 0, 235, 0, -21, 0, 0,
ax_anim 2, 0, 235, 0, -17, 0, 0,
ax_anim 1, 0, 235, 0, -11, 0, 0,
ax_anim 2, 2, 233, 0, 0, 0, 0,
ax_anim_terminator
sIllumiseAnims_11_7:
ax_anim 2, 0, 236, 0, 0, 0, 0,
ax_anim 1, 0, 237, 0, -10, 0, 0,
ax_anim 2, 0, 237, 0, -16, 0, 0,
ax_anim 3, 0, 237, 0, -20, 0, 0,
ax_anim 4, 0, 237, 0, -22, 0, 0,
ax_anim 4, 0, 236, 0, -23, 0, 0,
ax_anim 3, 0, 238, 0, -22, 0, 0,
ax_anim 2, 0, 238, 0, -18, 0, 0,
ax_anim 1, 0, 238, 0, -12, 0, 0,
ax_anim 2, 2, 236, 0, 0, 0, 0,
ax_anim_terminator
sIllumiseAnims_11_8:
ax_anim 2, 0, 239, 0, 0, 0, 0,
ax_anim 1, 0, 240, 0, -10, 0, 0,
ax_anim 2, 0, 240, 0, -16, 0, 0,
ax_anim 3, 0, 240, 0, -20, 0, 0,
ax_anim 4, 0, 240, 0, -22, 0, 0,
ax_anim 4, 0, 239, 0, -23, 0, 0,
ax_anim 3, 0, 241, 0, -22, 0, 0,
ax_anim 2, 0, 241, 0, -18, 0, 0,
ax_anim 1, 0, 241, 0, -12, 0, 0,
ax_anim 2, 2, 239, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sIllumiseAnims_12_1:
ax_anim 2, 0, 242, 1, 0, 1, 0,
ax_anim 2, 0, 242, 0, 0, 0, 0,
ax_anim 2, 0, 242, 1, 0, 1, 0,
ax_anim 2, 0, 242, 0, 0, 0, 0,
ax_anim 2, 0, 242, 1, 0, 1, 0,
ax_anim 2, 2, 242, 0, 0, 0, 0,
ax_anim 2, 0, 242, 1, 0, 1, 0,
ax_anim 2, 0, 242, 0, 0, 0, 0,
ax_anim 2, 0, 242, 1, 0, 1, 0,
ax_anim 2, 1, 242, 0, 0, 0, 0,
ax_anim_terminator
sIllumiseAnims_12_2:
ax_anim 2, 0, 249, 1, -1, 1, -1,
ax_anim 2, 0, 249, 0, 0, 0, 0,
ax_anim 2, 0, 249, 1, -1, 1, -1,
ax_anim 2, 0, 249, 0, 0, 0, 0,
ax_anim 2, 0, 249, 1, -1, 1, -1,
ax_anim 2, 2, 249, 0, 0, 0, 0,
ax_anim 2, 0, 249, 1, -1, 1, -1,
ax_anim 2, 0, 249, 0, 0, 0, 0,
ax_anim 2, 0, 249, 1, -1, 1, -1,
ax_anim 2, 1, 249, 0, 0, 0, 0,
ax_anim_terminator
sIllumiseAnims_12_3:
ax_anim 2, 0, 248, 0, -1, 0, -1,
ax_anim 2, 0, 248, 0, 0, 0, 0,
ax_anim 2, 0, 248, 0, -1, 0, -1,
ax_anim 2, 0, 248, 0, 0, 0, 0,
ax_anim 2, 0, 248, 0, -1, 0, -1,
ax_anim 2, 2, 248, 0, 0, 0, 0,
ax_anim 2, 0, 248, 0, -1, 0, -1,
ax_anim 2, 0, 248, 0, 0, 0, 0,
ax_anim 2, 0, 248, 0, -1, 0, -1,
ax_anim 2, 1, 248, 0, 0, 0, 0,
ax_anim_terminator
sIllumiseAnims_12_4:
ax_anim 2, 0, 247, -1, -1, -1, -1,
ax_anim 2, 0, 247, 0, 0, 0, 0,
ax_anim 2, 0, 247, -1, -1, -1, -1,
ax_anim 2, 0, 247, 0, 0, 0, 0,
ax_anim 2, 0, 247, -1, -1, -1, -1,
ax_anim 2, 2, 247, 0, 0, 0, 0,
ax_anim 2, 0, 247, -1, -1, -1, -1,
ax_anim 2, 0, 247, 0, 0, 0, 0,
ax_anim 2, 0, 247, -1, -1, -1, -1,
ax_anim 2, 1, 247, 0, 0, 0, 0,
ax_anim_terminator
sIllumiseAnims_12_5:
ax_anim 2, 0, 246, 1, 0, 1, 0,
ax_anim 2, 0, 246, 0, 0, 0, 0,
ax_anim 2, 0, 246, 1, 0, 1, 0,
ax_anim 2, 0, 246, 0, 0, 0, 0,
ax_anim 2, 0, 246, 1, 0, 1, 0,
ax_anim 2, 2, 246, 0, 0, 0, 0,
ax_anim 2, 0, 246, 1, 0, 1, 0,
ax_anim 2, 0, 246, 0, 0, 0, 0,
ax_anim 2, 0, 246, 1, 0, 1, 0,
ax_anim 2, 1, 246, 0, 0, 0, 0,
ax_anim_terminator
sIllumiseAnims_12_6:
ax_anim 2, 0, 245, 1, -1, 1, -1,
ax_anim 2, 0, 245, 0, 0, 0, 0,
ax_anim 2, 0, 245, 1, -1, 1, -1,
ax_anim 2, 0, 245, 0, 0, 0, 0,
ax_anim 2, 0, 245, 1, -1, 1, -1,
ax_anim 2, 2, 245, 0, 0, 0, 0,
ax_anim 2, 0, 245, 1, -1, 1, -1,
ax_anim 2, 0, 245, 0, 0, 0, 0,
ax_anim 2, 0, 245, 1, -1, 1, -1,
ax_anim 2, 1, 245, 0, 0, 0, 0,
ax_anim_terminator
sIllumiseAnims_12_7:
ax_anim 2, 0, 244, 0, -1, 0, -1,
ax_anim 2, 0, 244, 0, 0, 0, 0,
ax_anim 2, 0, 244, 0, -1, 0, -1,
ax_anim 2, 0, 244, 0, 0, 0, 0,
ax_anim 2, 0, 244, 0, -1, 0, -1,
ax_anim 2, 2, 244, 0, 0, 0, 0,
ax_anim 2, 0, 244, 0, -1, 0, -1,
ax_anim 2, 0, 244, 0, 0, 0, 0,
ax_anim 2, 0, 244, 0, -1, 0, -1,
ax_anim 2, 1, 244, 0, 0, 0, 0,
ax_anim_terminator
sIllumiseAnims_12_8:
ax_anim 2, 0, 243, -1, -1, -1, -1,
ax_anim 2, 0, 243, 0, 0, 0, 0,
ax_anim 2, 0, 243, -1, -1, -1, -1,
ax_anim 2, 0, 243, 0, 0, 0, 0,
ax_anim 2, 0, 243, -1, -1, -1, -1,
ax_anim 2, 2, 243, 0, 0, 0, 0,
ax_anim 2, 0, 243, -1, -1, -1, -1,
ax_anim 2, 0, 243, 0, 0, 0, 0,
ax_anim 2, 0, 243, -1, -1, -1, -1,
ax_anim 2, 1, 243, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sIllumiseAnims_13_1:
ax_anim 2, 0, 250, 0, 0, 0, 0,
ax_anim 2, 0, 251, 0, 0, 0, 0,
ax_anim 2, 0, 252, 0, 0, 0, 0,
ax_anim 2, 0, 253, 0, 0, 0, 0,
ax_anim 2, 0, 254, 0, 0, 0, 0,
ax_anim 2, 0, 255, 0, 0, 0, 0,
ax_anim 2, 0, 256, 0, 0, 0, 0,
ax_anim 2, 0, 257, 0, 0, 0, 0,
ax_anim 2, 2, 250, 0, 0, 0, 0,
ax_anim_terminator
sIllumiseAnims_13_2:
ax_anim 2, 0, 257, 0, 0, 0, 0,
ax_anim 2, 0, 250, 0, 0, 0, 0,
ax_anim 2, 0, 251, 0, 0, 0, 0,
ax_anim 2, 0, 252, 0, 0, 0, 0,
ax_anim 2, 0, 253, 0, 0, 0, 0,
ax_anim 2, 0, 254, 0, 0, 0, 0,
ax_anim 2, 0, 255, 0, 0, 0, 0,
ax_anim 2, 0, 256, 0, 0, 0, 0,
ax_anim 2, 2, 257, 0, 0, 0, 0,
ax_anim_terminator
sIllumiseAnims_13_3:
ax_anim 2, 0, 256, 0, 0, 0, 0,
ax_anim 2, 0, 257, 0, 0, 0, 0,
ax_anim 2, 0, 250, 0, 0, 0, 0,
ax_anim 2, 0, 251, 0, 0, 0, 0,
ax_anim 2, 0, 252, 0, 0, 0, 0,
ax_anim 2, 0, 253, 0, 0, 0, 0,
ax_anim 2, 0, 254, 0, 0, 0, 0,
ax_anim 2, 0, 255, 0, 0, 0, 0,
ax_anim 2, 2, 256, 0, 0, 0, 0,
ax_anim_terminator
sIllumiseAnims_13_4:
ax_anim 2, 0, 255, 0, 0, 0, 0,
ax_anim 2, 0, 256, 0, 0, 0, 0,
ax_anim 2, 0, 257, 0, 0, 0, 0,
ax_anim 2, 0, 250, 0, 0, 0, 0,
ax_anim 2, 0, 251, 0, 0, 0, 0,
ax_anim 2, 0, 252, 0, 0, 0, 0,
ax_anim 2, 0, 253, 0, 0, 0, 0,
ax_anim 2, 0, 254, 0, 0, 0, 0,
ax_anim 2, 2, 255, 0, 0, 0, 0,
ax_anim_terminator
sIllumiseAnims_13_5:
ax_anim 2, 0, 254, 0, 0, 0, 0,
ax_anim 2, 0, 255, 0, 0, 0, 0,
ax_anim 2, 0, 256, 0, 0, 0, 0,
ax_anim 2, 0, 257, 0, 0, 0, 0,
ax_anim 2, 0, 250, 0, 0, 0, 0,
ax_anim 2, 0, 251, 0, 0, 0, 0,
ax_anim 2, 0, 252, 0, 0, 0, 0,
ax_anim 2, 0, 253, 0, 0, 0, 0,
ax_anim 2, 2, 254, 0, 0, 0, 0,
ax_anim_terminator
sIllumiseAnims_13_6:
ax_anim 2, 0, 253, 0, 0, 0, 0,
ax_anim 2, 0, 254, 0, 0, 0, 0,
ax_anim 2, 0, 255, 0, 0, 0, 0,
ax_anim 2, 0, 256, 0, 0, 0, 0,
ax_anim 2, 0, 257, 0, 0, 0, 0,
ax_anim 2, 0, 250, 0, 0, 0, 0,
ax_anim 2, 0, 251, 0, 0, 0, 0,
ax_anim 2, 0, 252, 0, 0, 0, 0,
ax_anim 2, 2, 253, 0, 0, 0, 0,
ax_anim_terminator
sIllumiseAnims_13_7:
ax_anim 2, 0, 252, 0, 0, 0, 0,
ax_anim 2, 0, 253, 0, 0, 0, 0,
ax_anim 2, 0, 254, 0, 0, 0, 0,
ax_anim 2, 0, 255, 0, 0, 0, 0,
ax_anim 2, 0, 256, 0, 0, 0, 0,
ax_anim 2, 0, 257, 0, 0, 0, 0,
ax_anim 2, 0, 250, 0, 0, 0, 0,
ax_anim 2, 0, 251, 0, 0, 0, 0,
ax_anim 2, 2, 252, 0, 0, 0, 0,
ax_anim_terminator
sIllumiseAnims_13_8:
ax_anim 2, 0, 251, 0, 0, 0, 0,
ax_anim 2, 0, 252, 0, 0, 0, 0,
ax_anim 2, 0, 253, 0, 0, 0, 0,
ax_anim 2, 0, 254, 0, 0, 0, 0,
ax_anim 2, 0, 255, 0, 0, 0, 0,
ax_anim 2, 0, 256, 0, 0, 0, 0,
ax_anim 2, 0, 257, 0, 0, 0, 0,
ax_anim 2, 0, 250, 0, 0, 0, 0,
ax_anim 2, 2, 251, 0, 0, 0, 0,
ax_anim_terminator
sIllumiseGfx1:
.incbin "baserom.gba", 0x12CA698, 0x200
sIllumiseSprites1:
ax_sprite sIllumiseGfx1, 0x200
ax_sprite_terminator
sIllumiseGfx2:
.incbin "baserom.gba", 0x12CA8A8, 0x200
sIllumiseSprites2:
ax_sprite sIllumiseGfx2, 0x200
ax_sprite_terminator
sIllumiseGfx3:
.incbin "baserom.gba", 0x12CAAB8, 0x200
sIllumiseSprites3:
ax_sprite sIllumiseGfx3, 0x200
ax_sprite_terminator
sIllumiseGfx4:
.incbin "baserom.gba", 0x12CACC8, 0x200
sIllumiseSprites4:
ax_sprite sIllumiseGfx4, 0x200
ax_sprite_terminator
sIllumiseGfx5:
.incbin "baserom.gba", 0x12CAED8, 0x200
sIllumiseSprites5:
ax_sprite sIllumiseGfx5, 0x200
ax_sprite_terminator
sIllumiseGfx6:
.incbin "baserom.gba", 0x12CB0E8, 0x200
sIllumiseSprites6:
ax_sprite sIllumiseGfx6, 0x200
ax_sprite_terminator
sIllumiseGfx7:
.incbin "baserom.gba", 0x12CB2F8, 0x100
sIllumiseSprites7:
ax_sprite sIllumiseGfx7, 0x100
ax_sprite_terminator
sIllumiseGfx8:
.incbin "baserom.gba", 0x12CB408, 0x100
sIllumiseSprites8:
ax_sprite sIllumiseGfx8, 0x100
ax_sprite_terminator
sIllumiseGfx9:
.incbin "baserom.gba", 0x12CB518, 0x100
sIllumiseSprites9:
ax_sprite sIllumiseGfx9, 0x100
ax_sprite_terminator
sIllumiseGfx10:
.incbin "baserom.gba", 0x12CB628, 0x200
sIllumiseSprites10:
ax_sprite sIllumiseGfx10, 0x200
ax_sprite_terminator
sIllumiseGfx11:
.incbin "baserom.gba", 0x12CB838, 0x200
sIllumiseSprites11:
ax_sprite sIllumiseGfx11, 0x200
ax_sprite_terminator
sIllumiseGfx12:
.incbin "baserom.gba", 0x12CBA48, 0x200
sIllumiseSprites12:
ax_sprite sIllumiseGfx12, 0x200
ax_sprite_terminator
sIllumiseGfx13:
.incbin "baserom.gba", 0x12CBC58, 0x200
sIllumiseSprites13:
ax_sprite sIllumiseGfx13, 0x200
ax_sprite_terminator
sIllumiseGfx14:
.incbin "baserom.gba", 0x12CBE68, 0x200
sIllumiseSprites14:
ax_sprite sIllumiseGfx14, 0x200
ax_sprite_terminator
sIllumiseGfx15:
.incbin "baserom.gba", 0x12CC078, 0x200
sIllumiseSprites15:
ax_sprite sIllumiseGfx15, 0x200
ax_sprite_terminator
sIllumiseGfx16:
.incbin "baserom.gba", 0x12CC288, 0x100
sIllumiseGfx16_1:
.incbin "baserom.gba", 0x12CC388, 0x40
sIllumiseSprites16:
ax_sprite 0, 0x80
ax_sprite sIllumiseGfx16, 0x100
ax_sprite 0, 0x20
ax_sprite sIllumiseGfx16_1, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sIllumiseGfx17:
.incbin "baserom.gba", 0x12CC3F8, 0x100
sIllumiseGfx17_1:
.incbin "baserom.gba", 0x12CC4F8, 0x40
sIllumiseSprites17:
ax_sprite 0, 0x80
ax_sprite sIllumiseGfx17, 0x100
ax_sprite 0, 0x20
ax_sprite sIllumiseGfx17_1, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sIllumiseGfx18:
.incbin "baserom.gba", 0x12CC568, 0x100
sIllumiseGfx18_1:
.incbin "baserom.gba", 0x12CC668, 0x20
sIllumiseSprites18:
ax_sprite 0, 0x80
ax_sprite sIllumiseGfx18, 0x100
ax_sprite 0, 0x40
ax_sprite sIllumiseGfx18_1, 0x20
ax_sprite 0, 0x20
ax_sprite_terminator
sIllumiseGfx19:
.incbin "baserom.gba", 0x12CC6B8, 0x100
sIllumiseGfx19_1:
.incbin "baserom.gba", 0x12CC7B8, 0x20
sIllumiseSprites19:
ax_sprite 0, 0x80
ax_sprite sIllumiseGfx19, 0x100
ax_sprite 0, 0x40
ax_sprite sIllumiseGfx19_1, 0x20
ax_sprite 0, 0x20
ax_sprite_terminator
sIllumiseGfx20:
.incbin "baserom.gba", 0x12CC808, 0x100
sIllumiseGfx20_1:
.incbin "baserom.gba", 0x12CC908, 0x40
sIllumiseSprites20:
ax_sprite 0, 0x80
ax_sprite sIllumiseGfx20, 0x100
ax_sprite 0, 0x40
ax_sprite sIllumiseGfx20_1, 0x40
ax_sprite_terminator
sIllumiseGfx21:
.incbin "baserom.gba", 0x12CC970, 0x60
sIllumiseGfx21_1:
.incbin "baserom.gba", 0x12CC9D0, 0x80
sIllumiseGfx21_2:
.incbin "baserom.gba", 0x12CCA50, 0x40
sIllumiseSprites21:
ax_sprite 0, 0x80
ax_sprite sIllumiseGfx21, 0x60
ax_sprite 0, 0x20
ax_sprite sIllumiseGfx21_1, 0x80
ax_sprite 0, 0x40
ax_sprite sIllumiseGfx21_2, 0x40
ax_sprite_terminator
sIllumiseGfx22:
.incbin "baserom.gba", 0x12CCAC8, 0x80
sIllumiseGfx22_1:
.incbin "baserom.gba", 0x12CCB48, 0x60
sIllumiseGfx22_2:
.incbin "baserom.gba", 0x12CCBA8, 0x60
sIllumiseSprites22:
ax_sprite 0, 0x80
ax_sprite sIllumiseGfx22, 0x80
ax_sprite 0, 0x20
ax_sprite sIllumiseGfx22_1, 0x60
ax_sprite 0, 0x20
ax_sprite sIllumiseGfx22_2, 0x60
ax_sprite_terminator
sIllumiseGfx23:
.incbin "baserom.gba", 0x12CCC40, 0x60
sIllumiseGfx23_1:
.incbin "baserom.gba", 0x12CCCA0, 0x60
sIllumiseGfx23_2:
.incbin "baserom.gba", 0x12CCD00, 0x60
sIllumiseSprites23:
ax_sprite 0, 0x80
ax_sprite sIllumiseGfx23, 0x60
ax_sprite 0, 0x40
ax_sprite sIllumiseGfx23_1, 0x60
ax_sprite 0, 0x20
ax_sprite sIllumiseGfx23_2, 0x60
ax_sprite_terminator
sIllumiseGfx24:
.incbin "baserom.gba", 0x12CCD98, 0x40
sIllumiseGfx24_1:
.incbin "baserom.gba", 0x12CCDD8, 0x60
sIllumiseGfx24_2:
.incbin "baserom.gba", 0x12CCE38, 0x80
sIllumiseGfx24_3:
.incbin "baserom.gba", 0x12CCEB8, 0x40
sIllumiseSprites24:
ax_sprite 0, 0x20
ax_sprite sIllumiseGfx24, 0x40
ax_sprite 0, 0x20
ax_sprite sIllumiseGfx24_1, 0x60
ax_sprite 0, 0x20
ax_sprite sIllumiseGfx24_2, 0x80
ax_sprite 0, 0x20
ax_sprite sIllumiseGfx24_3, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sIllumiseGfx25:
.incbin "baserom.gba", 0x12CCF48, 0x40
sIllumiseGfx25_1:
.incbin "baserom.gba", 0x12CCF88, 0x60
sIllumiseGfx25_2:
.incbin "baserom.gba", 0x12CCFE8, 0x80
sIllumiseGfx25_3:
.incbin "baserom.gba", 0x12CD068, 0x40
sIllumiseSprites25:
ax_sprite 0, 0x20
ax_sprite sIllumiseGfx25, 0x40
ax_sprite 0, 0x20
ax_sprite sIllumiseGfx25_1, 0x60
ax_sprite 0, 0x20
ax_sprite sIllumiseGfx25_2, 0x80
ax_sprite 0, 0x20
ax_sprite sIllumiseGfx25_3, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sIllumiseGfx26:
.incbin "baserom.gba", 0x12CD0F8, 0x40
sIllumiseGfx26_1:
.incbin "baserom.gba", 0x12CD138, 0x100
sIllumiseGfx26_2:
.incbin "baserom.gba", 0x12CD238, 0x40
sIllumiseSprites26:
ax_sprite 0, 0x20
ax_sprite sIllumiseGfx26, 0x40
ax_sprite 0, 0x20
ax_sprite sIllumiseGfx26_1, 0x100
ax_sprite 0, 0x20
ax_sprite sIllumiseGfx26_2, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sIllumiseGfx27:
.incbin "baserom.gba", 0x12CD2B8, 0x60
sIllumiseGfx27_1:
.incbin "baserom.gba", 0x12CD318, 0x80
sIllumiseGfx27_2:
.incbin "baserom.gba", 0x12CD398, 0x40
sIllumiseSprites27:
ax_sprite 0, 0x80
ax_sprite sIllumiseGfx27, 0x60
ax_sprite 0, 0x20
ax_sprite sIllumiseGfx27_1, 0x80
ax_sprite 0, 0x20
ax_sprite sIllumiseGfx27_2, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sIllumiseGfx28:
.incbin "baserom.gba", 0x12CD418, 0x40
sIllumiseGfx28_1:
.incbin "baserom.gba", 0x12CD458, 0x60
sIllumiseGfx28_2:
.incbin "baserom.gba", 0x12CD4B8, 0x60
sIllumiseGfx28_3:
.incbin "baserom.gba", 0x12CD518, 0x60
sIllumiseSprites28:
ax_sprite 0, 0x20
ax_sprite sIllumiseGfx28, 0x40
ax_sprite 0, 0x40
ax_sprite sIllumiseGfx28_1, 0x60
ax_sprite 0, 0x20
ax_sprite sIllumiseGfx28_2, 0x60
ax_sprite 0, 0x20
ax_sprite sIllumiseGfx28_3, 0x60
ax_sprite_terminator
sIllumiseGfx29:
.incbin "baserom.gba", 0x12CD5C0, 0x60
sIllumiseGfx29_1:
.incbin "baserom.gba", 0x12CD620, 0x80
sIllumiseGfx29_2:
.incbin "baserom.gba", 0x12CD6A0, 0x40
sIllumiseSprites29:
ax_sprite 0, 0x80
ax_sprite sIllumiseGfx29, 0x60
ax_sprite 0, 0x20
ax_sprite sIllumiseGfx29_1, 0x80
ax_sprite 0, 0x20
ax_sprite sIllumiseGfx29_2, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sIllumiseGfx30:
.incbin "baserom.gba", 0x12CD720, 0x20
sIllumiseGfx30_1:
.incbin "baserom.gba", 0x12CD740, 0x60
sIllumiseGfx30_2:
.incbin "baserom.gba", 0x12CD7A0, 0x60
sIllumiseGfx30_3:
.incbin "baserom.gba", 0x12CD800, 0x40
sIllumiseSprites30:
ax_sprite 0, 0x40
ax_sprite sIllumiseGfx30, 0x20
ax_sprite 0, 0x40
ax_sprite sIllumiseGfx30_1, 0x60
ax_sprite 0, 0x20
ax_sprite sIllumiseGfx30_2, 0x60
ax_sprite 0, 0x20
ax_sprite sIllumiseGfx30_3, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sIllumiseGfx31:
.incbin "baserom.gba", 0x12CD890, 0x20
sIllumiseGfx31_1:
.incbin "baserom.gba", 0x12CD8B0, 0x60
sIllumiseGfx31_2:
.incbin "baserom.gba", 0x12CD910, 0x60
sIllumiseGfx31_3:
.incbin "baserom.gba", 0x12CD970, 0x40
sIllumiseSprites31:
ax_sprite 0, 0x20
ax_sprite sIllumiseGfx31, 0x20
ax_sprite 0, 0x40
ax_sprite sIllumiseGfx31_1, 0x60
ax_sprite 0, 0x20
ax_sprite sIllumiseGfx31_2, 0x60
ax_sprite 0, 0x40
ax_sprite sIllumiseGfx31_3, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sIllumiseGfx32:
.incbin "baserom.gba", 0x12CDA00, 0x40
sIllumiseGfx32_1:
.incbin "baserom.gba", 0x12CDA40, 0x60
sIllumiseGfx32_2:
.incbin "baserom.gba", 0x12CDAA0, 0x60
sIllumiseGfx32_3:
.incbin "baserom.gba", 0x12CDB00, 0x40
sIllumiseSprites32:
ax_sprite 0, 0x20
ax_sprite sIllumiseGfx32, 0x40
ax_sprite 0, 0x40
ax_sprite sIllumiseGfx32_1, 0x60
ax_sprite 0, 0x20
ax_sprite sIllumiseGfx32_2, 0x60
ax_sprite 0, 0x20
ax_sprite sIllumiseGfx32_3, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sIllumiseGfx33:
.incbin "baserom.gba", 0x12CDB90, 0x40
sIllumiseGfx33_1:
.incbin "baserom.gba", 0x12CDBD0, 0x60
sIllumiseGfx33_2:
.incbin "baserom.gba", 0x12CDC30, 0x60
sIllumiseGfx33_3:
.incbin "baserom.gba", 0x12CDC90, 0x40
sIllumiseSprites33:
ax_sprite 0, 0x20
ax_sprite sIllumiseGfx33, 0x40
ax_sprite 0, 0x20
ax_sprite sIllumiseGfx33_1, 0x60
ax_sprite 0, 0x20
ax_sprite sIllumiseGfx33_2, 0x60
ax_sprite 0, 0x40
ax_sprite sIllumiseGfx33_3, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sIllumiseGfx34:
.incbin "baserom.gba", 0x12CDD20, 0x40
sIllumiseGfx34_1:
.incbin "baserom.gba", 0x12CDD60, 0x60
sIllumiseGfx34_2:
.incbin "baserom.gba", 0x12CDDC0, 0x80
sIllumiseGfx34_3:
.incbin "baserom.gba", 0x12CDE40, 0x40
sIllumiseSprites34:
ax_sprite 0, 0x20
ax_sprite sIllumiseGfx34, 0x40
ax_sprite 0, 0x20
ax_sprite sIllumiseGfx34_1, 0x60
ax_sprite 0, 0x20
ax_sprite sIllumiseGfx34_2, 0x80
ax_sprite 0, 0x20
ax_sprite sIllumiseGfx34_3, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sIllumiseGfx35:
.incbin "baserom.gba", 0x12CDED0, 0x40
sIllumiseGfx35_1:
.incbin "baserom.gba", 0x12CDF10, 0x60
sIllumiseGfx35_2:
.incbin "baserom.gba", 0x12CDF70, 0x80
sIllumiseGfx35_3:
.incbin "baserom.gba", 0x12CDFF0, 0x40
sIllumiseSprites35:
ax_sprite 0, 0x20
ax_sprite sIllumiseGfx35, 0x40
ax_sprite 0, 0x20
ax_sprite sIllumiseGfx35_1, 0x60
ax_sprite 0, 0x20
ax_sprite sIllumiseGfx35_2, 0x80
ax_sprite 0, 0x20
ax_sprite sIllumiseGfx35_3, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sIllumiseGfx36:
.incbin "baserom.gba", 0x12CE080, 0x200
sIllumiseSprites36:
ax_sprite sIllumiseGfx36, 0x200
ax_sprite_terminator
sIllumiseGfx37:
.incbin "baserom.gba", 0x12CE290, 0x200
sIllumiseSprites37:
ax_sprite sIllumiseGfx37, 0x200
ax_sprite_terminator
sIllumiseGfx38:
.incbin "baserom.gba", 0x12CE4A0, 0x200
sIllumiseSprites38:
ax_sprite sIllumiseGfx38, 0x200
ax_sprite_terminator
sIllumiseGfx39:
.incbin "baserom.gba", 0x12CE6B0, 0x200
sIllumiseSprites39:
ax_sprite sIllumiseGfx39, 0x200
ax_sprite_terminator
sIllumiseGfx40:
.incbin "baserom.gba", 0x12CE8C0, 0x200
sIllumiseSprites40:
ax_sprite sIllumiseGfx40, 0x200
ax_sprite_terminator
sIllumiseGfx41:
.incbin "baserom.gba", 0x12CEAD0, 0x200
sIllumiseSprites41:
ax_sprite sIllumiseGfx41, 0x200
ax_sprite_terminator
sIllumiseGfx42:
.incbin "baserom.gba", 0x12CECE0, 0x200
sIllumiseSprites42:
ax_sprite sIllumiseGfx42, 0x200
ax_sprite_terminator
sIllumiseGfx43:
.incbin "baserom.gba", 0x12CEEF0, 0x200
sIllumiseSprites43:
ax_sprite sIllumiseGfx43, 0x200
ax_sprite_terminator
sAxPosesIllumise:
.4byte sIllumisePose1
.4byte sIllumisePose2
.4byte sIllumisePose3
.4byte sIllumisePose4
.4byte sIllumisePose5
.4byte sIllumisePose6
.4byte sIllumisePose7
.4byte sIllumisePose8
.4byte sIllumisePose9
.4byte sIllumisePose10
.4byte sIllumisePose11
.4byte sIllumisePose12
.4byte sIllumisePose13
.4byte sIllumisePose14
.4byte sIllumisePose15
.4byte sIllumisePose16
.4byte sIllumisePose17
.4byte sIllumisePose18
.4byte sIllumisePose19
.4byte sIllumisePose20
.4byte sIllumisePose21
.4byte sIllumisePose22
.4byte sIllumisePose23
.4byte sIllumisePose24
.4byte sIllumisePose25
.4byte sIllumisePose26
.4byte sIllumisePose27
.4byte sIllumisePose28
.4byte sIllumisePose29
.4byte sIllumisePose30
.4byte sIllumisePose31
.4byte sIllumisePose32
.4byte sIllumisePose33
.4byte sIllumisePose34
.4byte sIllumisePose35
.4byte sIllumisePose36
.4byte sIllumisePose37
.4byte sIllumisePose38
.4byte sIllumisePose39
.4byte sIllumisePose40
.4byte sIllumisePose41
.4byte sIllumisePose42
.4byte sIllumisePose43
.4byte sIllumisePose44
.4byte sIllumisePose45
.4byte sIllumisePose46
.4byte sIllumisePose47
.4byte sIllumisePose48
.4byte sIllumisePose49
.4byte sIllumisePose50
.4byte sIllumisePose51
.4byte sIllumisePose52
.4byte sIllumisePose53
.4byte sIllumisePose54
.4byte sIllumisePose55
.4byte sIllumisePose56
.4byte sIllumisePose57
.4byte sIllumisePose58
.4byte sIllumisePose59
.4byte sIllumisePose60
.4byte sIllumisePose61
.4byte sIllumisePose62
.4byte sIllumisePose63
.4byte sIllumisePose64
.4byte sIllumisePose65
.4byte sIllumisePose66
.4byte sIllumisePose67
.4byte sIllumisePose68
.4byte sIllumisePose69
.4byte sIllumisePose70
.4byte sIllumisePose71
.4byte sIllumisePose72
.4byte sIllumisePose73
.4byte sIllumisePose74
.4byte sIllumisePose75
.4byte sIllumisePose76
.4byte sIllumisePose77
.4byte sIllumisePose78
.4byte sIllumisePose79
.4byte sIllumisePose80
.4byte sIllumisePose81
.4byte sIllumisePose82
.4byte sIllumisePose83
.4byte sIllumisePose84
.4byte sIllumisePose85
.4byte sIllumisePose86
.4byte sIllumisePose87
.4byte sIllumisePose88
.4byte sIllumisePose89
.4byte sIllumisePose90
.4byte sIllumisePose91
.4byte sIllumisePose92
.4byte sIllumisePose93
.4byte sIllumisePose94
.4byte sIllumisePose95
.4byte sIllumisePose96
.4byte sIllumisePose97
.4byte sIllumisePose98
.4byte sIllumisePose99
.4byte sIllumisePose100
.4byte sIllumisePose101
.4byte sIllumisePose102
.4byte sIllumisePose103
.4byte sIllumisePose104
.4byte sIllumisePose105
.4byte sIllumisePose106
.4byte sIllumisePose107
.4byte sIllumisePose108
.4byte sIllumisePose109
.4byte sIllumisePose110
.4byte sIllumisePose111
.4byte sIllumisePose112
.4byte sIllumisePose113
.4byte sIllumisePose114
.4byte sIllumisePose115
.4byte sIllumisePose116
.4byte sIllumisePose117
.4byte sIllumisePose118
.4byte sIllumisePose119
.4byte sIllumisePose120
.4byte sIllumisePose121
.4byte sIllumisePose122
.4byte sIllumisePose123
.4byte sIllumisePose124
.4byte sIllumisePose125
.4byte sIllumisePose126
.4byte sIllumisePose127
.4byte sIllumisePose128
.4byte sIllumisePose129
.4byte sIllumisePose130
.4byte sIllumisePose131
.4byte sIllumisePose132
.4byte sIllumisePose133
.4byte sIllumisePose134
.4byte sIllumisePose135
.4byte sIllumisePose136
.4byte sIllumisePose137
.4byte sIllumisePose138
.4byte sIllumisePose139
.4byte sIllumisePose140
.4byte sIllumisePose141
.4byte sIllumisePose142
.4byte sIllumisePose143
.4byte sIllumisePose144
.4byte sIllumisePose145
.4byte sIllumisePose146
.4byte sIllumisePose147
.4byte sIllumisePose148
.4byte sIllumisePose149
.4byte sIllumisePose150
.4byte sIllumisePose151
.4byte sIllumisePose152
.4byte sIllumisePose153
.4byte sIllumisePose154
.4byte sIllumisePose155
.4byte sIllumisePose156
.4byte sIllumisePose157
.4byte sIllumisePose158
.4byte sIllumisePose159
.4byte sIllumisePose160
.4byte sIllumisePose161
.4byte sIllumisePose162
.4byte sIllumisePose163
.4byte sIllumisePose164
.4byte sIllumisePose165
.4byte sIllumisePose166
.4byte sIllumisePose167
.4byte sIllumisePose168
.4byte sIllumisePose169
.4byte sIllumisePose170
.4byte sIllumisePose171
.4byte sIllumisePose172
.4byte sIllumisePose173
.4byte sIllumisePose174
.4byte sIllumisePose175
.4byte sIllumisePose176
.4byte sIllumisePose177
.4byte sIllumisePose178
.4byte sIllumisePose179
.4byte sIllumisePose180
.4byte sIllumisePose181
.4byte sIllumisePose182
.4byte sIllumisePose183
.4byte sIllumisePose184
.4byte sIllumisePose185
.4byte sIllumisePose186
.4byte sIllumisePose187
.4byte sIllumisePose188
.4byte sIllumisePose189
.4byte sIllumisePose190
.4byte sIllumisePose191
.4byte sIllumisePose192
.4byte sIllumisePose193
.4byte sIllumisePose194
.4byte sIllumisePose195
.4byte sIllumisePose196
.4byte sIllumisePose197
.4byte sIllumisePose198
.4byte sIllumisePose199
.4byte sIllumisePose200
.4byte sIllumisePose201
.4byte sIllumisePose202
.4byte sIllumisePose203
.4byte sIllumisePose204
.4byte sIllumisePose205
.4byte sIllumisePose206
.4byte sIllumisePose207
.4byte sIllumisePose208
.4byte sIllumisePose209
.4byte sIllumisePose210
.4byte sIllumisePose211
.4byte sIllumisePose212
.4byte sIllumisePose213
.4byte sIllumisePose214
.4byte sIllumisePose215
.4byte sIllumisePose216
.4byte sIllumisePose217
.4byte sIllumisePose218
.4byte sIllumisePose219
.4byte sIllumisePose220
.4byte sIllumisePose221
.4byte sIllumisePose222
.4byte sIllumisePose223
.4byte sIllumisePose224
.4byte sIllumisePose225
.4byte sIllumisePose226
.4byte sIllumisePose227
.4byte sIllumisePose228
.4byte sIllumisePose229
.4byte sIllumisePose230
.4byte sIllumisePose231
.4byte sIllumisePose232
.4byte sIllumisePose233
.4byte sIllumisePose234
.4byte sIllumisePose235
.4byte sIllumisePose236
.4byte sIllumisePose237
.4byte sIllumisePose238
.4byte sIllumisePose239
.4byte sIllumisePose240
.4byte sIllumisePose241
.4byte sIllumisePose242
.4byte sIllumisePose243
.4byte sIllumisePose244
.4byte sIllumisePose245
.4byte sIllumisePose246
.4byte sIllumisePose247
.4byte sIllumisePose248
.4byte sIllumisePose249
.4byte sIllumisePose250
.4byte sIllumisePose251
.4byte sIllumisePose252
.4byte sIllumisePose253
.4byte sIllumisePose254
.4byte sIllumisePose255
.4byte sIllumisePose256
.4byte sIllumisePose257
.4byte sIllumisePose258
sAxPositionsIllumise:
.2byte   -1,   -9, 	  -8,   -6, 	   6,   -6, 	  -1,   -8
.2byte   -1,   -9, 	  -8,   -6, 	   6,   -6, 	  -1,   -8
.2byte   -1,   -9, 	  -8,   -6, 	   6,   -6, 	  -1,   -8
.2byte    2,  -10, 	   5,   -7, 	  -6,   -5, 	   0,   -7
.2byte    2,  -10, 	   5,   -7, 	  -6,   -5, 	   0,   -7
.2byte    2,  -10, 	   5,   -7, 	  -6,   -5, 	  -1,   -7
.2byte    4,  -10, 	   1,   -5, 	  -1,   -4, 	  -2,   -6
.2byte    4,  -10, 	   1,   -5, 	  -1,   -4, 	  -1,   -6
.2byte    4,  -10, 	   1,   -5, 	  -1,   -4, 	  -1,   -6
.2byte    4,  -11, 	  -5,   -6, 	   4,   -4, 	  -2,   -6
.2byte    3,  -12, 	  -5,   -6, 	   4,   -4, 	  -2,   -6
.2byte    4,  -12, 	  -5,   -7, 	   4,   -4, 	  -2,   -6
.2byte   -1,  -11, 	   7,   -5, 	  -9,   -5, 	  -1,   -7
.2byte   -1,  -11, 	   7,   -5, 	  -9,   -5, 	  -1,   -7
.2byte   -1,  -12, 	   7,   -5, 	  -9,   -5, 	  -1,   -6
.2byte   -6,  -11, 	   3,   -6, 	  -6,   -4, 	   0,   -6
.2byte   -5,  -12, 	   3,   -6, 	  -6,   -4, 	   0,   -6
.2byte   -6,  -12, 	   3,   -7, 	  -6,   -4, 	   0,   -6
.2byte   -6,  -10, 	  -3,   -5, 	  -1,   -4, 	   0,   -6
.2byte   -6,  -10, 	  -3,   -5, 	  -1,   -4, 	  -1,   -6
.2byte   -6,  -10, 	  -3,   -5, 	  -1,   -4, 	  -1,   -6
.2byte   -4,  -10, 	  -7,   -7, 	   4,   -5, 	  -2,   -7
.2byte   -4,  -10, 	  -7,   -7, 	   4,   -5, 	  -2,   -7
.2byte   -4,  -10, 	  -7,   -7, 	   4,   -5, 	  -1,   -7
.2byte   -1,   -9, 	  -8,   -6, 	   6,   -6, 	  -1,   -8
.2byte   -4,  -10, 	  -7,   -7, 	   4,   -5, 	  -2,   -7
.2byte   -6,  -10, 	  -3,   -5, 	  -1,   -4, 	   0,   -6
.2byte   -6,  -11, 	   3,   -6, 	  -6,   -4, 	   0,   -6
.2byte   -1,  -11, 	   7,   -5, 	  -9,   -5, 	  -1,   -7
.2byte    4,  -11, 	  -5,   -6, 	   4,   -4, 	  -2,   -6
.2byte    4,  -10, 	   1,   -5, 	  -1,   -4, 	  -2,   -6
.2byte    2,  -10, 	   5,   -7, 	  -6,   -5, 	   0,   -7
.2byte   -1,   -9, 	  -8,   -6, 	   6,   -6, 	  -1,   -8
.2byte   -1,   -9, 	  -8,   -6, 	   6,   -6, 	  -1,   -8
.2byte   -1,   -9, 	  -8,   -6, 	   6,   -6, 	  -1,   -8
.2byte   -1,   -6, 	  -9,   -6, 	   7,   -6, 	  -1,   -9
.2byte   -1,   -6, 	  -9,   -6, 	   7,   -6, 	  -1,   -9
.2byte    2,  -10, 	   5,   -7, 	  -6,   -5, 	   0,   -7
.2byte    2,  -10, 	   5,   -7, 	  -6,   -5, 	   0,   -7
.2byte    2,  -10, 	   5,   -7, 	  -6,   -5, 	  -1,   -7
.2byte    2,   -6, 	   7,   -9, 	  -8,   -5, 	  -1,   -7
.2byte    2,   -6, 	   7,   -9, 	  -8,   -5, 	  -1,   -7
.2byte    4,  -10, 	   1,   -5, 	  -1,   -4, 	  -2,   -6
.2byte    4,  -10, 	   1,   -5, 	  -1,   -4, 	  -1,   -6
.2byte    4,  -10, 	   1,   -5, 	  -1,   -4, 	  -1,   -6
.2byte    3,   -7, 	  -5,   -9, 	  -5,   -6, 	  -3,   -8
.2byte    3,   -7, 	  -5,   -9, 	  -5,   -6, 	  -3,   -8
.2byte    4,  -11, 	  -5,   -6, 	   4,   -4, 	  -2,   -6
.2byte    3,  -12, 	  -5,   -6, 	   4,   -4, 	  -2,   -6
.2byte    4,  -12, 	  -5,   -7, 	   4,   -4, 	  -2,   -6
.2byte    3,   -7, 	  -6,   -7, 	   1,   -3, 	  -3,   -7
.2byte    3,   -7, 	  -6,   -7, 	   1,   -3, 	  -3,   -7
.2byte   -1,  -11, 	   7,   -5, 	  -9,   -5, 	  -1,   -7
.2byte   -1,  -11, 	   7,   -5, 	  -9,   -5, 	  -1,   -7
.2byte   -1,  -12, 	   7,   -5, 	  -9,   -5, 	  -1,   -6
.2byte   -1,  -10, 	   7,   -5, 	  -9,   -5, 	  -1,   -7
.2byte   -1,  -10, 	   7,   -6, 	  -9,   -6, 	  -1,   -7
.2byte   -6,  -11, 	   3,   -6, 	  -6,   -4, 	   0,   -6
.2byte   -5,  -12, 	   3,   -6, 	  -6,   -4, 	   0,   -6
.2byte   -6,  -12, 	   3,   -7, 	  -6,   -4, 	   0,   -6
.2byte   -5,   -7, 	   4,   -7, 	  -3,   -3, 	   1,   -7
.2byte   -5,   -7, 	   4,   -7, 	  -3,   -3, 	   1,   -7
.2byte   -6,  -10, 	  -3,   -5, 	  -1,   -4, 	   0,   -6
.2byte   -6,  -10, 	  -3,   -5, 	  -1,   -4, 	  -1,   -6
.2byte   -6,  -10, 	  -3,   -5, 	  -1,   -4, 	  -1,   -6
.2byte   -5,   -7, 	   3,   -9, 	   3,   -6, 	   1,   -8
.2byte   -5,   -7, 	   3,   -9, 	   3,   -6, 	   1,   -8
.2byte   -4,  -10, 	  -7,   -7, 	   4,   -5, 	  -2,   -7
.2byte   -4,  -10, 	  -7,   -7, 	   4,   -5, 	  -2,   -7
.2byte   -4,  -10, 	  -7,   -7, 	   4,   -5, 	  -1,   -7
.2byte   -4,   -6, 	  -9,   -9, 	   6,   -5, 	  -1,   -7
.2byte   -4,   -6, 	  -9,   -9, 	   6,   -5, 	  -1,   -7
.2byte   -1,   -9, 	  -8,   -6, 	   6,   -6, 	  -1,   -8
.2byte   -1,   -9, 	  -8,   -6, 	   6,   -6, 	  -1,   -8
.2byte   -1,   -9, 	  -8,   -6, 	   6,   -6, 	  -1,   -8
.2byte   -1,   -6, 	  -9,   -6, 	   7,   -6, 	  -1,   -9
.2byte   -1,   -6, 	  -9,   -6, 	   7,   -6, 	  -1,   -9
.2byte    2,  -10, 	   5,   -7, 	  -6,   -5, 	   0,   -7
.2byte    2,  -10, 	   5,   -7, 	  -6,   -5, 	   0,   -7
.2byte    2,  -10, 	   5,   -7, 	  -6,   -5, 	  -1,   -7
.2byte    2,   -6, 	   7,   -9, 	  -8,   -5, 	  -1,   -7
.2byte    2,   -6, 	   7,   -9, 	  -8,   -5, 	  -1,   -7
.2byte    4,  -10, 	   1,   -5, 	  -1,   -4, 	  -2,   -6
.2byte    4,  -10, 	   1,   -5, 	  -1,   -4, 	  -1,   -6
.2byte    4,  -10, 	   1,   -5, 	  -1,   -4, 	  -1,   -6
.2byte    3,   -7, 	  -5,   -9, 	  -5,   -6, 	  -3,   -8
.2byte    3,   -7, 	  -5,   -9, 	  -5,   -6, 	  -3,   -8
.2byte    4,  -11, 	  -5,   -6, 	   4,   -4, 	  -2,   -6
.2byte    3,  -12, 	  -5,   -6, 	   4,   -4, 	  -2,   -6
.2byte    4,  -12, 	  -5,   -7, 	   4,   -4, 	  -2,   -6
.2byte    3,   -7, 	  -6,   -7, 	   1,   -3, 	  -3,   -7
.2byte    3,   -7, 	  -6,   -7, 	   1,   -3, 	  -3,   -7
.2byte   -1,  -11, 	   7,   -5, 	  -9,   -5, 	  -1,   -7
.2byte   -1,  -11, 	   7,   -5, 	  -9,   -5, 	  -1,   -7
.2byte   -1,  -12, 	   7,   -5, 	  -9,   -5, 	  -1,   -6
.2byte   -1,  -10, 	   7,   -5, 	  -9,   -5, 	  -1,   -7
.2byte   -1,  -10, 	   7,   -6, 	  -9,   -6, 	  -1,   -7
.2byte   -6,  -11, 	   3,   -6, 	  -6,   -4, 	   0,   -6
.2byte   -5,  -12, 	   3,   -6, 	  -6,   -4, 	   0,   -6
.2byte   -6,  -12, 	   3,   -7, 	  -6,   -4, 	   0,   -6
.2byte   -5,   -7, 	   4,   -7, 	  -3,   -3, 	   1,   -7
.2byte   -5,   -7, 	   4,   -7, 	  -3,   -3, 	   1,   -7
.2byte   -6,  -10, 	  -3,   -5, 	  -1,   -4, 	   0,   -6
.2byte   -6,  -10, 	  -3,   -5, 	  -1,   -4, 	  -1,   -6
.2byte   -6,  -10, 	  -3,   -5, 	  -1,   -4, 	  -1,   -6
.2byte   -5,   -7, 	   3,   -9, 	   3,   -6, 	   1,   -8
.2byte   -5,   -7, 	   3,   -9, 	   3,   -6, 	   1,   -8
.2byte   -4,  -10, 	  -7,   -7, 	   4,   -5, 	  -2,   -7
.2byte   -4,  -10, 	  -7,   -7, 	   4,   -5, 	  -2,   -7
.2byte   -4,  -10, 	  -7,   -7, 	   4,   -5, 	  -1,   -7
.2byte   -4,   -6, 	  -9,   -9, 	   6,   -5, 	  -1,   -7
.2byte   -4,   -6, 	  -9,   -9, 	   6,   -5, 	  -1,   -7
.2byte   -1,   -9, 	  -8,   -6, 	   6,   -6, 	  -1,   -8
.2byte   -1,  -12, 	  -9,   -9, 	   7,   -9, 	  -1,   -8
.2byte   -1,   -7, 	  -8,   -6, 	   6,   -6, 	  -1,   -6
.2byte    2,  -10, 	   5,   -7, 	  -6,   -5, 	   0,   -7
.2byte    1,  -12, 	   4,   -8, 	  -8,   -7, 	  -2,   -7
.2byte    2,   -9, 	   3,   -6, 	  -8,   -6, 	  -1,   -5
.2byte    4,  -10, 	   1,   -5, 	  -1,   -4, 	  -2,   -6
.2byte    3,  -12, 	  -1,   -6, 	  -2,   -5, 	  -2,   -7
.2byte    6,  -10, 	  -2,   -7, 	  -3,   -6, 	   0,   -7
.2byte    4,  -11, 	  -5,   -6, 	   4,   -4, 	  -2,   -6
.2byte    3,  -14, 	  -6,   -5, 	   4,   -5, 	  -2,   -7
.2byte    4,  -15, 	  -6,   -7, 	   2,   -4, 	  -2,   -7
.2byte   -1,  -11, 	   7,   -5, 	  -9,   -5, 	  -1,   -7
.2byte   -1,   -9, 	   8,   -7, 	 -10,   -7, 	  -1,   -6
.2byte   -1,  -14, 	   8,   -6, 	 -10,   -6, 	  -1,   -7
.2byte   -6,  -11, 	   3,   -6, 	  -6,   -4, 	   0,   -6
.2byte   -5,  -14, 	   4,   -5, 	  -6,   -5, 	   0,   -7
.2byte   -6,  -15, 	   4,   -7, 	  -4,   -4, 	   0,   -7
.2byte   -6,  -10, 	  -3,   -5, 	  -1,   -4, 	   0,   -6
.2byte   -5,  -12, 	  -1,   -6, 	   0,   -5, 	   0,   -7
.2byte   -8,  -10, 	   0,   -7, 	   1,   -6, 	  -2,   -7
.2byte   -4,  -10, 	  -7,   -7, 	   4,   -5, 	  -2,   -7
.2byte   -3,  -12, 	  -6,   -8, 	   6,   -7, 	   0,   -7
.2byte   -4,   -9, 	  -5,   -6, 	   6,   -6, 	  -1,   -5
.2byte   -1,   -9, 	  -8,   -6, 	   6,   -6, 	  -1,   -8
.2byte   -1,   -9, 	  -8,   -6, 	   6,   -6, 	  -1,   -8
.2byte   -1,   -9, 	  -8,   -6, 	   6,   -6, 	  -1,   -8
.2byte   -1,   -6, 	  -9,   -6, 	   7,   -6, 	  -1,   -9
.2byte   -1,   -6, 	  -9,   -6, 	   7,   -6, 	  -1,   -9
.2byte    2,  -10, 	   5,   -7, 	  -6,   -5, 	   0,   -7
.2byte    2,  -10, 	   5,   -7, 	  -6,   -5, 	   0,   -7
.2byte    2,  -10, 	   5,   -7, 	  -6,   -5, 	  -1,   -7
.2byte    2,   -6, 	   7,   -9, 	  -8,   -5, 	  -1,   -7
.2byte    2,   -6, 	   7,   -9, 	  -8,   -5, 	  -1,   -7
.2byte    4,  -10, 	   1,   -5, 	  -1,   -4, 	  -2,   -6
.2byte    4,  -10, 	   1,   -5, 	  -1,   -4, 	  -1,   -6
.2byte    4,  -10, 	   1,   -5, 	  -1,   -4, 	  -1,   -6
.2byte    3,   -7, 	  -5,   -9, 	  -5,   -6, 	  -3,   -8
.2byte    3,   -7, 	  -5,   -9, 	  -5,   -6, 	  -3,   -8
.2byte    4,  -11, 	  -5,   -6, 	   4,   -4, 	  -2,   -6
.2byte    3,  -12, 	  -5,   -6, 	   4,   -4, 	  -2,   -6
.2byte    4,  -12, 	  -5,   -7, 	   4,   -4, 	  -2,   -6
.2byte    3,   -7, 	  -6,   -7, 	   1,   -3, 	  -3,   -7
.2byte    3,   -7, 	  -6,   -7, 	   1,   -3, 	  -3,   -7
.2byte   -1,  -11, 	   7,   -5, 	  -9,   -5, 	  -1,   -7
.2byte   -1,  -11, 	   7,   -5, 	  -9,   -5, 	  -1,   -7
.2byte   -1,  -12, 	   7,   -5, 	  -9,   -5, 	  -1,   -6
.2byte   -1,  -10, 	   7,   -5, 	  -9,   -5, 	  -1,   -7
.2byte   -1,  -10, 	   7,   -6, 	  -9,   -6, 	  -1,   -7
.2byte   -6,  -11, 	   3,   -6, 	  -6,   -4, 	   0,   -6
.2byte   -5,  -12, 	   3,   -6, 	  -6,   -4, 	   0,   -6
.2byte   -6,  -12, 	   3,   -7, 	  -6,   -4, 	   0,   -6
.2byte   -5,   -7, 	   4,   -7, 	  -3,   -3, 	   1,   -7
.2byte   -5,   -7, 	   4,   -7, 	  -3,   -3, 	   1,   -7
.2byte   -6,  -10, 	  -3,   -5, 	  -1,   -4, 	   0,   -6
.2byte   -6,  -10, 	  -3,   -5, 	  -1,   -4, 	  -1,   -6
.2byte   -6,  -10, 	  -3,   -5, 	  -1,   -4, 	  -1,   -6
.2byte   -5,   -7, 	   3,   -9, 	   3,   -6, 	   1,   -8
.2byte   -5,   -7, 	   3,   -9, 	   3,   -6, 	   1,   -8
.2byte   -4,  -10, 	  -7,   -7, 	   4,   -5, 	  -2,   -7
.2byte   -4,  -10, 	  -7,   -7, 	   4,   -5, 	  -2,   -7
.2byte   -4,  -10, 	  -7,   -7, 	   4,   -5, 	  -1,   -7
.2byte   -4,   -6, 	  -9,   -9, 	   6,   -5, 	  -1,   -7
.2byte   -4,   -6, 	  -9,   -9, 	   6,   -5, 	  -1,   -7
.2byte   -3,   -9, 	  -6,   -5, 	   4,   -4, 	  -1,   -5
.2byte   -3,   -8, 	  -6,   -5, 	   4,   -4, 	  -1,   -5
.2byte    0,  -11, 	  -7,  -10, 	   7,  -10, 	   0,   -9
.2byte    1,   -9, 	   6,  -10, 	  -7,   -8, 	  -1,   -6
.2byte    4,  -11, 	   2,  -10, 	  -2,   -8, 	   0,   -5
.2byte    1,  -13, 	  -1,  -11, 	   7,   -9, 	   1,   -6
.2byte    0,  -13, 	   8,   -7, 	  -8,   -7, 	   0,   -5
.2byte   -1,  -12, 	   1,  -10, 	  -7,   -8, 	  -1,   -5
.2byte   -5,  -11, 	  -3,  -10, 	   1,   -8, 	  -1,   -5
.2byte   -2,   -9, 	  -7,  -10, 	   6,   -8, 	   0,   -6
.2byte   -1,   -9, 	  -8,   -6, 	   6,   -6, 	  -1,   -8
.2byte   -1,  -12, 	  -9,   -9, 	   7,   -9, 	  -1,   -8
.2byte    2,  -10, 	   5,   -7, 	  -6,   -5, 	   0,   -7
.2byte    1,  -12, 	   4,   -8, 	  -8,   -7, 	  -2,   -7
.2byte    4,  -10, 	   1,   -5, 	  -1,   -4, 	  -2,   -6
.2byte    3,  -12, 	  -1,   -6, 	  -2,   -5, 	  -2,   -7
.2byte    4,  -11, 	  -5,   -6, 	   4,   -4, 	  -2,   -6
.2byte    3,  -14, 	  -6,   -5, 	   4,   -5, 	  -2,   -7
.2byte   -1,  -11, 	   7,   -5, 	  -9,   -5, 	  -1,   -7
.2byte   -1,   -9, 	   8,   -7, 	 -10,   -7, 	  -1,   -6
.2byte   -6,  -11, 	   3,   -6, 	  -6,   -4, 	   0,   -6
.2byte   -5,  -14, 	   4,   -5, 	  -6,   -5, 	   0,   -7
.2byte   -6,  -10, 	  -3,   -5, 	  -1,   -4, 	   0,   -6
.2byte   -5,  -12, 	  -1,   -6, 	   0,   -5, 	   0,   -7
.2byte   -4,  -10, 	  -7,   -7, 	   4,   -5, 	  -2,   -7
.2byte   -3,  -12, 	  -6,   -8, 	   6,   -7, 	   0,   -7
.2byte   -1,   -6, 	  -9,   -6, 	   7,   -6, 	  -1,   -9
.2byte   -4,   -6, 	  -9,   -9, 	   6,   -5, 	  -1,   -7
.2byte   -5,   -7, 	   3,   -9, 	   3,   -6, 	   1,   -8
.2byte   -5,   -7, 	   4,   -7, 	  -3,   -3, 	   1,   -7
.2byte   -1,  -10, 	   7,   -5, 	  -9,   -5, 	  -1,   -7
.2byte    3,   -7, 	  -6,   -7, 	   1,   -3, 	  -3,   -7
.2byte    3,   -7, 	  -5,   -9, 	  -5,   -6, 	  -3,   -8
.2byte    2,   -6, 	   7,   -9, 	  -8,   -5, 	  -1,   -7
.2byte   -1,   -7, 	  -8,   -6, 	   6,   -6, 	  -1,   -6
.2byte    2,   -9, 	   3,   -6, 	  -8,   -6, 	  -1,   -5
.2byte    6,   -9, 	  -2,   -6, 	  -3,   -5, 	   0,   -6
.2byte    4,  -14, 	  -6,   -6, 	   2,   -3, 	  -2,   -6
.2byte   -1,  -13, 	   8,   -5, 	 -10,   -5, 	  -1,   -6
.2byte   -6,  -14, 	   4,   -6, 	  -4,   -3, 	   0,   -6
.2byte   -8,   -9, 	   0,   -6, 	   1,   -5, 	  -2,   -6
.2byte   -4,   -9, 	  -5,   -6, 	   6,   -6, 	  -1,   -5
.2byte   -1,   -9, 	  -8,   -6, 	   6,   -6, 	  -1,   -8
.2byte   -1,   -9, 	  -8,   -6, 	   6,   -6, 	  -1,   -8
.2byte   -1,   -9, 	  -8,   -6, 	   6,   -6, 	  -1,   -8
.2byte    2,  -10, 	   5,   -7, 	  -6,   -5, 	   0,   -7
.2byte    2,  -10, 	   5,   -7, 	  -6,   -5, 	  -1,   -7
.2byte    2,  -10, 	   5,   -7, 	  -6,   -5, 	   0,   -7
.2byte    4,  -10, 	   1,   -5, 	  -1,   -4, 	  -2,   -6
.2byte    4,  -10, 	   1,   -5, 	  -1,   -4, 	  -1,   -6
.2byte    4,  -10, 	   1,   -5, 	  -1,   -4, 	  -1,   -6
.2byte    4,  -11, 	  -5,   -6, 	   4,   -4, 	  -2,   -6
.2byte    4,  -12, 	  -5,   -7, 	   4,   -4, 	  -2,   -6
.2byte    3,  -12, 	  -5,   -6, 	   4,   -4, 	  -2,   -6
.2byte   -1,  -11, 	   7,   -5, 	  -9,   -5, 	  -1,   -7
.2byte   -1,  -12, 	   7,   -5, 	  -9,   -5, 	  -1,   -6
.2byte   -1,  -11, 	   7,   -5, 	  -9,   -5, 	  -1,   -7
.2byte   -6,  -11, 	   3,   -6, 	  -6,   -4, 	   0,   -6
.2byte   -6,  -12, 	   3,   -7, 	  -6,   -4, 	   0,   -6
.2byte   -5,  -12, 	   3,   -6, 	  -6,   -4, 	   0,   -6
.2byte   -6,  -10, 	  -3,   -5, 	  -1,   -4, 	   0,   -6
.2byte   -6,  -10, 	  -3,   -5, 	  -1,   -4, 	  -1,   -6
.2byte   -6,  -10, 	  -3,   -5, 	  -1,   -4, 	  -1,   -6
.2byte   -4,  -10, 	  -7,   -7, 	   4,   -5, 	  -2,   -7
.2byte   -4,  -10, 	  -7,   -7, 	   4,   -5, 	  -1,   -7
.2byte   -4,  -10, 	  -7,   -7, 	   4,   -5, 	  -2,   -7
.2byte   -1,  -12, 	  -9,   -9, 	   7,   -9, 	  -1,   -8
.2byte   -3,  -12, 	  -6,   -8, 	   6,   -7, 	   0,   -7
.2byte   -5,  -12, 	  -1,   -6, 	   0,   -5, 	   0,   -7
.2byte   -5,  -14, 	   4,   -5, 	  -6,   -5, 	   0,   -7
.2byte   -1,   -9, 	   8,   -7, 	 -10,   -7, 	  -1,   -6
.2byte    3,  -14, 	  -6,   -5, 	   4,   -5, 	  -2,   -7
.2byte    3,  -12, 	  -1,   -6, 	  -2,   -5, 	  -2,   -7
.2byte    1,  -12, 	   4,   -8, 	  -8,   -7, 	  -2,   -7
.2byte   -1,   -9, 	  -8,   -6, 	   6,   -6, 	  -1,   -8
.2byte   -3,  -10, 	  -6,   -7, 	   5,   -5, 	  -1,   -7
.2byte   -6,  -10, 	  -3,   -5, 	  -1,   -4, 	   0,   -6
.2byte   -6,  -11, 	   3,   -6, 	  -6,   -4, 	   0,   -6
.2byte   -1,  -11, 	   7,   -5, 	  -9,   -5, 	  -1,   -7
.2byte    4,  -11, 	  -5,   -6, 	   4,   -4, 	  -2,   -6
.2byte    5,  -10, 	   2,   -5, 	   0,   -4, 	  -1,   -6
.2byte    2,  -10, 	   5,   -7, 	  -6,   -5, 	   0,   -7
sIllumiseAnimTable1:
.4byte sIllumiseAnims_1_1
.4byte sIllumiseAnims_1_2
.4byte sIllumiseAnims_1_3
.4byte sIllumiseAnims_1_4
.4byte sIllumiseAnims_1_5
.4byte sIllumiseAnims_1_6
.4byte sIllumiseAnims_1_7
.4byte sIllumiseAnims_1_8
sIllumiseAnimTable2:
.4byte sIllumiseAnims_2_1
.4byte sIllumiseAnims_2_2
.4byte sIllumiseAnims_2_3
.4byte sIllumiseAnims_2_4
.4byte sIllumiseAnims_2_5
.4byte sIllumiseAnims_2_6
.4byte sIllumiseAnims_2_7
.4byte sIllumiseAnims_2_8
sIllumiseAnimTable3:
.4byte sIllumiseAnims_3_1
.4byte sIllumiseAnims_3_2
.4byte sIllumiseAnims_3_3
.4byte sIllumiseAnims_3_4
.4byte sIllumiseAnims_3_5
.4byte sIllumiseAnims_3_6
.4byte sIllumiseAnims_3_7
.4byte sIllumiseAnims_3_8
sIllumiseAnimTable4:
.4byte sIllumiseAnims_4_1
.4byte sIllumiseAnims_4_2
.4byte sIllumiseAnims_4_3
.4byte sIllumiseAnims_4_4
.4byte sIllumiseAnims_4_5
.4byte sIllumiseAnims_4_6
.4byte sIllumiseAnims_4_7
.4byte sIllumiseAnims_4_8
sIllumiseAnimTable5:
.4byte sIllumiseAnims_5_1
.4byte sIllumiseAnims_5_2
.4byte sIllumiseAnims_5_3
.4byte sIllumiseAnims_5_4
.4byte sIllumiseAnims_5_5
.4byte sIllumiseAnims_5_6
.4byte sIllumiseAnims_5_7
.4byte sIllumiseAnims_5_8
sIllumiseAnimTable6:
.4byte sIllumiseAnims_6_1
.4byte sIllumiseAnims_6_1
.4byte sIllumiseAnims_6_1
.4byte sIllumiseAnims_6_1
.4byte sIllumiseAnims_6_1
.4byte sIllumiseAnims_6_1
.4byte sIllumiseAnims_6_1
.4byte sIllumiseAnims_6_1
sIllumiseAnimTable7:
.4byte sIllumiseAnims_7_1
.4byte sIllumiseAnims_7_2
.4byte sIllumiseAnims_7_3
.4byte sIllumiseAnims_7_4
.4byte sIllumiseAnims_7_5
.4byte sIllumiseAnims_7_6
.4byte sIllumiseAnims_7_7
.4byte sIllumiseAnims_7_8
sIllumiseAnimTable8:
.4byte sIllumiseAnims_8_1
.4byte sIllumiseAnims_8_2
.4byte sIllumiseAnims_8_3
.4byte sIllumiseAnims_8_4
.4byte sIllumiseAnims_8_5
.4byte sIllumiseAnims_8_6
.4byte sIllumiseAnims_8_7
.4byte sIllumiseAnims_8_8
sIllumiseAnimTable9:
.4byte sIllumiseAnims_9_1
.4byte sIllumiseAnims_9_2
.4byte sIllumiseAnims_9_3
.4byte sIllumiseAnims_9_4
.4byte sIllumiseAnims_9_5
.4byte sIllumiseAnims_9_6
.4byte sIllumiseAnims_9_7
.4byte sIllumiseAnims_9_8
sIllumiseAnimTable10:
.4byte sIllumiseAnims_10_1
.4byte sIllumiseAnims_10_2
.4byte sIllumiseAnims_10_3
.4byte sIllumiseAnims_10_4
.4byte sIllumiseAnims_10_5
.4byte sIllumiseAnims_10_6
.4byte sIllumiseAnims_10_7
.4byte sIllumiseAnims_10_8
sIllumiseAnimTable11:
.4byte sIllumiseAnims_11_1
.4byte sIllumiseAnims_11_2
.4byte sIllumiseAnims_11_3
.4byte sIllumiseAnims_11_4
.4byte sIllumiseAnims_11_5
.4byte sIllumiseAnims_11_6
.4byte sIllumiseAnims_11_7
.4byte sIllumiseAnims_11_8
sIllumiseAnimTable12:
.4byte sIllumiseAnims_12_1
.4byte sIllumiseAnims_12_2
.4byte sIllumiseAnims_12_3
.4byte sIllumiseAnims_12_4
.4byte sIllumiseAnims_12_5
.4byte sIllumiseAnims_12_6
.4byte sIllumiseAnims_12_7
.4byte sIllumiseAnims_12_8
sIllumiseAnimTable13:
.4byte sIllumiseAnims_13_1
.4byte sIllumiseAnims_13_2
.4byte sIllumiseAnims_13_3
.4byte sIllumiseAnims_13_4
.4byte sIllumiseAnims_13_5
.4byte sIllumiseAnims_13_6
.4byte sIllumiseAnims_13_7
.4byte sIllumiseAnims_13_8
sAxAnimationsIllumise:
.4byte sIllumiseAnimTable1
.4byte sIllumiseAnimTable2
.4byte sIllumiseAnimTable3
.4byte sIllumiseAnimTable4
.4byte sIllumiseAnimTable5
.4byte sIllumiseAnimTable6
.4byte sIllumiseAnimTable7
.4byte sIllumiseAnimTable8
.4byte sIllumiseAnimTable9
.4byte sIllumiseAnimTable10
.4byte sIllumiseAnimTable11
.4byte sIllumiseAnimTable12
.4byte sIllumiseAnimTable13
sAxSpritesIllumise:
.4byte sIllumiseSprites1
.4byte sIllumiseSprites2
.4byte sIllumiseSprites3
.4byte sIllumiseSprites4
.4byte sIllumiseSprites5
.4byte sIllumiseSprites6
.4byte sIllumiseSprites7
.4byte sIllumiseSprites8
.4byte sIllumiseSprites9
.4byte sIllumiseSprites10
.4byte sIllumiseSprites11
.4byte sIllumiseSprites12
.4byte sIllumiseSprites13
.4byte sIllumiseSprites14
.4byte sIllumiseSprites15
.4byte sIllumiseSprites16
.4byte sIllumiseSprites17
.4byte sIllumiseSprites18
.4byte sIllumiseSprites19
.4byte sIllumiseSprites20
.4byte sIllumiseSprites21
.4byte sIllumiseSprites22
.4byte sIllumiseSprites23
.4byte sIllumiseSprites24
.4byte sIllumiseSprites25
.4byte sIllumiseSprites26
.4byte sIllumiseSprites27
.4byte sIllumiseSprites28
.4byte sIllumiseSprites29
.4byte sIllumiseSprites30
.4byte sIllumiseSprites31
.4byte sIllumiseSprites32
.4byte sIllumiseSprites33
.4byte sIllumiseSprites34
.4byte sIllumiseSprites35
.4byte sIllumiseSprites36
.4byte sIllumiseSprites37
.4byte sIllumiseSprites38
.4byte sIllumiseSprites39
.4byte sIllumiseSprites40
.4byte sIllumiseSprites41
.4byte sIllumiseSprites42
.4byte sIllumiseSprites43
sAxMainIllumise:
ax_main sAxPosesIllumise, sAxAnimationsIllumise, 13, sAxSpritesIllumise, sAxPositionsIllumise
