.global gAxKabutops
gAxKabutops:
ax_siro sAxMainKabutops
sKabutopsPose1:
ax_pose 0, 0x01e6, 0x80f0, 0x6c00
ax_pose_terminator
sKabutopsPose2:
ax_pose 1, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sKabutopsPose3:
ax_pose 2, 0x01e6, 0x80f1, 0x6c00
ax_pose_terminator
sKabutopsPose4:
ax_pose 3, 0x01e6, 0x90ee, 0x6c00
ax_pose_terminator
sKabutopsPose5:
ax_pose 4, 0x01e6, 0x90ee, 0x6c00
ax_pose_terminator
sKabutopsPose6:
ax_pose 5, 0x01e6, 0x90ee, 0x6c00
ax_pose_terminator
sKabutopsPose7:
ax_pose 6, 0x01e6, 0x90f1, 0x6c00
ax_pose_terminator
sKabutopsPose8:
ax_pose 7, 0x01e6, 0x90f1, 0x6c00
ax_pose_terminator
sKabutopsPose9:
ax_pose 8, 0x01e6, 0x90f1, 0x6c00
ax_pose_terminator
sKabutopsPose10:
ax_pose 9, 0x01e6, 0x90f1, 0x6c00
ax_pose_terminator
sKabutopsPose11:
ax_pose 10, 0x01e6, 0x90f2, 0x6c00
ax_pose_terminator
sKabutopsPose12:
ax_pose 11, 0x01e6, 0x90f1, 0x6c00
ax_pose_terminator
sKabutopsPose13:
ax_pose 12, 0x01e6, 0x80f0, 0x6c00
ax_pose_terminator
sKabutopsPose14:
ax_pose 13, 0x01e6, 0x80f0, 0x6c00
ax_pose_terminator
sKabutopsPose15:
ax_pose 14, 0x01e6, 0x80f0, 0x6c00
ax_pose_terminator
sKabutopsPose16:
ax_pose 9, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sKabutopsPose17:
ax_pose 10, 0x01e6, 0x80ee, 0x6c00
ax_pose_terminator
sKabutopsPose18:
ax_pose 11, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sKabutopsPose19:
ax_pose 6, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sKabutopsPose20:
ax_pose 7, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sKabutopsPose21:
ax_pose 8, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sKabutopsPose22:
ax_pose 3, 0x01e6, 0x80f2, 0x6c00
ax_pose_terminator
sKabutopsPose23:
ax_pose 4, 0x01e6, 0x80f2, 0x6c00
ax_pose_terminator
sKabutopsPose24:
ax_pose 5, 0x01e6, 0x80f2, 0x6c00
ax_pose_terminator
sKabutopsPose25:
ax_pose 0, 0x01e6, 0x80f0, 0x6c00
ax_pose_terminator
sKabutopsPose26:
ax_pose 1, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sKabutopsPose27:
ax_pose 2, 0x01e6, 0x80f1, 0x6c00
ax_pose_terminator
sKabutopsPose28:
ax_pose 3, 0x01e6, 0x90ee, 0x6c00
ax_pose_terminator
sKabutopsPose29:
ax_pose 4, 0x01e6, 0x90ee, 0x6c00
ax_pose_terminator
sKabutopsPose30:
ax_pose 5, 0x01e6, 0x90ee, 0x6c00
ax_pose_terminator
sKabutopsPose31:
ax_pose 6, 0x01e6, 0x90f1, 0x6c00
ax_pose_terminator
sKabutopsPose32:
ax_pose 7, 0x01e6, 0x90f1, 0x6c00
ax_pose_terminator
sKabutopsPose33:
ax_pose 8, 0x01e6, 0x90f1, 0x6c00
ax_pose_terminator
sKabutopsPose34:
ax_pose 9, 0x01e6, 0x90f1, 0x6c00
ax_pose_terminator
sKabutopsPose35:
ax_pose 10, 0x01e6, 0x90f2, 0x6c00
ax_pose_terminator
sKabutopsPose36:
ax_pose 11, 0x01e6, 0x90f1, 0x6c00
ax_pose_terminator
sKabutopsPose37:
ax_pose 12, 0x01e6, 0x80f0, 0x6c00
ax_pose_terminator
sKabutopsPose38:
ax_pose 13, 0x01e6, 0x80f0, 0x6c00
ax_pose_terminator
sKabutopsPose39:
ax_pose 14, 0x01e6, 0x80f0, 0x6c00
ax_pose_terminator
sKabutopsPose40:
ax_pose 9, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sKabutopsPose41:
ax_pose 10, 0x01e6, 0x80ee, 0x6c00
ax_pose_terminator
sKabutopsPose42:
ax_pose 11, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sKabutopsPose43:
ax_pose 6, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sKabutopsPose44:
ax_pose 7, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sKabutopsPose45:
ax_pose 8, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sKabutopsPose46:
ax_pose 3, 0x01e6, 0x80f2, 0x6c00
ax_pose_terminator
sKabutopsPose47:
ax_pose 4, 0x01e6, 0x80f2, 0x6c00
ax_pose_terminator
sKabutopsPose48:
ax_pose 5, 0x01e6, 0x80f2, 0x6c00
ax_pose_terminator
sKabutopsPose49:
ax_pose 0, 0x01e6, 0x80f0, 0x6c00
ax_pose_terminator
sKabutopsPose50:
ax_pose 15, 0x01e7, 0x80f0, 0x6c00
ax_pose_terminator
sKabutopsPose51:
ax_pose 16, 0x01e7, 0x80f0, 0x6c00
ax_pose 17, 0x01e7, 0x80f0, 0x6c10
ax_pose_terminator
sKabutopsPose52:
ax_pose 17, 0x01e7, 0x80f0, 0x6c00
ax_pose_terminator
sKabutopsPose53:
ax_pose 18, 0x01e7, 0x80f0, 0x6c00
ax_pose_terminator
sKabutopsPose54:
ax_pose 16, 0x01e7, 0x90f0, 0x6c00
ax_pose 19, 0x01e7, 0x80f0, 0x6c10
ax_pose_terminator
sKabutopsPose55:
ax_pose 19, 0x01e7, 0x80f0, 0x6c00
ax_pose_terminator
sKabutopsPose56:
ax_pose 3, 0x01e6, 0x90ee, 0x6c00
ax_pose_terminator
sKabutopsPose57:
ax_pose 20, 0x01e6, 0x90f2, 0x6c00
ax_pose_terminator
sKabutopsPose58:
ax_pose 21, 0x01ee, 0x90f2, 0x6c00
ax_pose 22, 0x01e6, 0x90f2, 0x6c10
ax_pose_terminator
sKabutopsPose59:
ax_pose 22, 0x01e6, 0x90f2, 0x6c00
ax_pose_terminator
sKabutopsPose60:
ax_pose 23, 0x01e6, 0x90f2, 0x6c00
ax_pose_terminator
sKabutopsPose61:
ax_pose 24, 0x01e6, 0x90f2, 0x6c00
ax_pose 25, 0x01e6, 0x90f2, 0x6c10
ax_pose_terminator
sKabutopsPose62:
ax_pose 25, 0x01e6, 0x90f2, 0x6c00
ax_pose_terminator
sKabutopsPose63:
ax_pose 6, 0x01e6, 0x90f1, 0x6c00
ax_pose_terminator
sKabutopsPose64:
ax_pose 26, 0x01e6, 0x90f1, 0x6c00
ax_pose_terminator
sKabutopsPose65:
ax_pose 27, 0x41f3, 0x90f1, 0x6c00
ax_pose 28, 0x01e6, 0x90f1, 0x6c08
ax_pose_terminator
sKabutopsPose66:
ax_pose 28, 0x01e6, 0x90f1, 0x6c00
ax_pose_terminator
sKabutopsPose67:
ax_pose 29, 0x01e6, 0x90f1, 0x6c00
ax_pose_terminator
sKabutopsPose68:
ax_pose 30, 0x01e6, 0x90f1, 0x6c00
ax_pose 31, 0x01e6, 0x90f1, 0x6c10
ax_pose_terminator
sKabutopsPose69:
ax_pose 31, 0x01e6, 0x90f1, 0x6c00
ax_pose_terminator
sKabutopsPose70:
ax_pose 9, 0x01e6, 0x90f1, 0x6c00
ax_pose_terminator
sKabutopsPose71:
ax_pose 32, 0x01e6, 0x90f1, 0x6c00
ax_pose_terminator
sKabutopsPose72:
ax_pose 33, 0x81e4, 0x90ff, 0x6c00
ax_pose 34, 0x01e6, 0x90f1, 0x6c08
ax_pose_terminator
sKabutopsPose73:
ax_pose 34, 0x01e6, 0x90f1, 0x6c00
ax_pose_terminator
sKabutopsPose74:
ax_pose 35, 0x01e6, 0x90f1, 0x6c00
ax_pose_terminator
sKabutopsPose75:
ax_pose 36, 0x01e6, 0x90f1, 0x6c00
ax_pose 37, 0x01e6, 0x90f1, 0x6c10
ax_pose_terminator
sKabutopsPose76:
ax_pose 36, 0x01e6, 0x90f1, 0x6c00
ax_pose_terminator
sKabutopsPose77:
ax_pose 12, 0x01e6, 0x80f0, 0x6c00
ax_pose_terminator
sKabutopsPose78:
ax_pose 38, 0x01e6, 0x80f0, 0x6c00
ax_pose_terminator
sKabutopsPose79:
ax_pose 39, 0x41ee, 0x80f0, 0x6c00
ax_pose 40, 0x01e6, 0x80f0, 0x6c08
ax_pose_terminator
sKabutopsPose80:
ax_pose 40, 0x01e6, 0x80f0, 0x6c00
ax_pose_terminator
sKabutopsPose81:
ax_pose 41, 0x01e6, 0x80f0, 0x6c00
ax_pose_terminator
sKabutopsPose82:
ax_pose 39, 0x41ee, 0x90f1, 0x6c00
ax_pose 42, 0x01e6, 0x80f0, 0x6c08
ax_pose_terminator
sKabutopsPose83:
ax_pose 42, 0x01e6, 0x80f0, 0x6c00
ax_pose_terminator
sKabutopsPose84:
ax_pose 9, 0x01e6, 0x80f0, 0x6c00
ax_pose_terminator
sKabutopsPose85:
ax_pose 32, 0x01e6, 0x80f0, 0x6c00
ax_pose_terminator
sKabutopsPose86:
ax_pose 33, 0x81e6, 0x80f4, 0x6c00
ax_pose 34, 0x01e6, 0x80f0, 0x6c08
ax_pose_terminator
sKabutopsPose87:
ax_pose 34, 0x01e6, 0x80f0, 0x6c00
ax_pose_terminator
sKabutopsPose88:
ax_pose 35, 0x01e6, 0x80f0, 0x6c00
ax_pose_terminator
sKabutopsPose89:
ax_pose 36, 0x01e6, 0x80f0, 0x6c00
ax_pose 37, 0x01e6, 0x80f0, 0x6c10
ax_pose_terminator
sKabutopsPose90:
ax_pose 36, 0x01e6, 0x80f0, 0x6c00
ax_pose_terminator
sKabutopsPose91:
ax_pose 6, 0x01e6, 0x80f0, 0x6c00
ax_pose_terminator
sKabutopsPose92:
ax_pose 26, 0x01e6, 0x80f0, 0x6c00
ax_pose_terminator
sKabutopsPose93:
ax_pose 27, 0x41f3, 0x80f0, 0x6c00
ax_pose 28, 0x01e6, 0x80f0, 0x6c08
ax_pose_terminator
sKabutopsPose94:
ax_pose 28, 0x01e6, 0x80f0, 0x6c00
ax_pose_terminator
sKabutopsPose95:
ax_pose 29, 0x01e6, 0x80f0, 0x6c00
ax_pose_terminator
sKabutopsPose96:
ax_pose 30, 0x01e6, 0x80f0, 0x6c00
ax_pose 31, 0x01e6, 0x80f0, 0x6c10
ax_pose_terminator
sKabutopsPose97:
ax_pose 31, 0x01e6, 0x80f0, 0x6c00
ax_pose_terminator
sKabutopsPose98:
ax_pose 3, 0x01e6, 0x80f3, 0x6c00
ax_pose_terminator
sKabutopsPose99:
ax_pose 20, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sKabutopsPose100:
ax_pose 21, 0x01ee, 0x80ef, 0x6c00
ax_pose 22, 0x01e6, 0x80ef, 0x6c10
ax_pose_terminator
sKabutopsPose101:
ax_pose 22, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sKabutopsPose102:
ax_pose 23, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sKabutopsPose103:
ax_pose 24, 0x01e6, 0x80ef, 0x6c00
ax_pose 25, 0x01e6, 0x80ef, 0x6c10
ax_pose_terminator
sKabutopsPose104:
ax_pose 25, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sKabutopsPose105:
ax_pose 0, 0x01e6, 0x80f0, 0x6c00
ax_pose_terminator
sKabutopsPose106:
ax_pose 43, 0x81ec, 0x40f7, 0x6c00
ax_pose 44, 0x81ec, 0x80ff, 0x6c04
ax_pose 45, 0x81ec, 0x00ef, 0x6c0c
ax_pose 46, 0x01ee, 0x010f, 0x6c0e
ax_pose_terminator
sKabutopsPose107:
ax_pose 47, 0x81ec, 0x40f7, 0x6c00
ax_pose 48, 0x81ec, 0x80ff, 0x6c04
ax_pose 49, 0x81ec, 0x00ef, 0x6c0c
ax_pose 50, 0x01ee, 0x010f, 0x6c0e
ax_pose_terminator
sKabutopsPose108:
ax_pose 3, 0x01e6, 0x90ee, 0x6c00
ax_pose_terminator
sKabutopsPose109:
ax_pose 51, 0x01e6, 0x90f0, 0x6c00
ax_pose_terminator
sKabutopsPose110:
ax_pose 52, 0x01e6, 0x90f0, 0x6c00
ax_pose_terminator
sKabutopsPose111:
ax_pose 6, 0x01e6, 0x90f1, 0x6c00
ax_pose_terminator
sKabutopsPose112:
ax_pose 53, 0x01e6, 0x90f2, 0x6c00
ax_pose_terminator
sKabutopsPose113:
ax_pose 54, 0x01e6, 0x90f2, 0x6c00
ax_pose_terminator
sKabutopsPose114:
ax_pose 9, 0x01e6, 0x90f1, 0x6c00
ax_pose_terminator
sKabutopsPose115:
ax_pose 55, 0x01e6, 0x90f1, 0x6c00
ax_pose_terminator
sKabutopsPose116:
ax_pose 56, 0x01e6, 0x90f1, 0x6c00
ax_pose_terminator
sKabutopsPose117:
ax_pose 12, 0x01e6, 0x80f0, 0x6c00
ax_pose_terminator
sKabutopsPose118:
ax_pose 57, 0x01e6, 0x80f1, 0x6c00
ax_pose_terminator
sKabutopsPose119:
ax_pose 58, 0x01e6, 0x80f1, 0x6c00
ax_pose_terminator
sKabutopsPose120:
ax_pose 9, 0x01e6, 0x80f0, 0x6c00
ax_pose_terminator
sKabutopsPose121:
ax_pose 55, 0x01e6, 0x80f0, 0x6c00
ax_pose_terminator
sKabutopsPose122:
ax_pose 56, 0x01e6, 0x80f0, 0x6c00
ax_pose_terminator
sKabutopsPose123:
ax_pose 6, 0x01e6, 0x80f0, 0x6c00
ax_pose_terminator
sKabutopsPose124:
ax_pose 53, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sKabutopsPose125:
ax_pose 54, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sKabutopsPose126:
ax_pose 3, 0x01e6, 0x80f3, 0x6c00
ax_pose_terminator
sKabutopsPose127:
ax_pose 51, 0x01e6, 0x80f1, 0x6c00
ax_pose_terminator
sKabutopsPose128:
ax_pose 52, 0x01e6, 0x80f1, 0x6c00
ax_pose_terminator
sKabutopsPose129:
ax_pose 0, 0x01e6, 0x80f0, 0x6c00
ax_pose_terminator
sKabutopsPose130:
ax_pose 3, 0x01e6, 0x80f3, 0x6c00
ax_pose_terminator
sKabutopsPose131:
ax_pose 6, 0x01e6, 0x80f0, 0x6c00
ax_pose_terminator
sKabutopsPose132:
ax_pose 9, 0x01e6, 0x80f0, 0x6c00
ax_pose_terminator
sKabutopsPose133:
ax_pose 12, 0x01e6, 0x80f0, 0x6c00
ax_pose_terminator
sKabutopsPose134:
ax_pose 9, 0x01e6, 0x90f1, 0x6c00
ax_pose_terminator
sKabutopsPose135:
ax_pose 6, 0x01e6, 0x90f1, 0x6c00
ax_pose_terminator
sKabutopsPose136:
ax_pose 3, 0x01e6, 0x90ee, 0x6c00
ax_pose_terminator
sKabutopsPose137:
ax_pose 59, 0x01eb, 0x80f4, 0x6c00
ax_pose_terminator
sKabutopsPose138:
ax_pose 60, 0x01eb, 0x80f4, 0x6c00
ax_pose_terminator
sKabutopsPose139:
ax_pose 61, 0x01e3, 0x80f0, 0x6c00
ax_pose_terminator
sKabutopsPose140:
ax_pose 62, 0x01e3, 0x90ef, 0x6c00
ax_pose_terminator
sKabutopsPose141:
ax_pose 63, 0x01e3, 0x90ee, 0x6c00
ax_pose_terminator
sKabutopsPose142:
ax_pose 64, 0x01e3, 0x90ef, 0x6c00
ax_pose_terminator
sKabutopsPose143:
ax_pose 65, 0x01e3, 0x80f0, 0x6c00
ax_pose_terminator
sKabutopsPose144:
ax_pose 64, 0x01e3, 0x80f1, 0x6c00
ax_pose_terminator
sKabutopsPose145:
ax_pose 63, 0x01e3, 0x80f2, 0x6c00
ax_pose_terminator
sKabutopsPose146:
ax_pose 62, 0x01e3, 0x80f1, 0x6c00
ax_pose_terminator
sKabutopsPose147:
ax_pose 0, 0x01e6, 0x80f0, 0x6c00
ax_pose_terminator
sKabutopsPose148:
ax_pose 1, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sKabutopsPose149:
ax_pose 2, 0x01e6, 0x80f1, 0x6c00
ax_pose_terminator
sKabutopsPose150:
ax_pose 3, 0x01e6, 0x90ee, 0x6c00
ax_pose_terminator
sKabutopsPose151:
ax_pose 4, 0x01e6, 0x90ee, 0x6c00
ax_pose_terminator
sKabutopsPose152:
ax_pose 5, 0x01e6, 0x90ee, 0x6c00
ax_pose_terminator
sKabutopsPose153:
ax_pose 6, 0x01e6, 0x90f1, 0x6c00
ax_pose_terminator
sKabutopsPose154:
ax_pose 7, 0x01e6, 0x90f1, 0x6c00
ax_pose_terminator
sKabutopsPose155:
ax_pose 8, 0x01e6, 0x90f1, 0x6c00
ax_pose_terminator
sKabutopsPose156:
ax_pose 9, 0x01e6, 0x90f1, 0x6c00
ax_pose_terminator
sKabutopsPose157:
ax_pose 10, 0x01e6, 0x90f2, 0x6c00
ax_pose_terminator
sKabutopsPose158:
ax_pose 11, 0x01e6, 0x90f1, 0x6c00
ax_pose_terminator
sKabutopsPose159:
ax_pose 12, 0x01e6, 0x80f0, 0x6c00
ax_pose_terminator
sKabutopsPose160:
ax_pose 13, 0x01e6, 0x80f0, 0x6c00
ax_pose_terminator
sKabutopsPose161:
ax_pose 14, 0x01e6, 0x80f0, 0x6c00
ax_pose_terminator
sKabutopsPose162:
ax_pose 9, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sKabutopsPose163:
ax_pose 10, 0x01e6, 0x80ee, 0x6c00
ax_pose_terminator
sKabutopsPose164:
ax_pose 11, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sKabutopsPose165:
ax_pose 6, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sKabutopsPose166:
ax_pose 7, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sKabutopsPose167:
ax_pose 8, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sKabutopsPose168:
ax_pose 3, 0x01e6, 0x80f2, 0x6c00
ax_pose_terminator
sKabutopsPose169:
ax_pose 4, 0x01e6, 0x80f2, 0x6c00
ax_pose_terminator
sKabutopsPose170:
ax_pose 5, 0x01e6, 0x80f2, 0x6c00
ax_pose_terminator
sKabutopsPose171:
ax_pose 0, 0x01e6, 0x80f0, 0x6c00
ax_pose_terminator
sKabutopsPose172:
ax_pose 3, 0x01e6, 0x80f3, 0x6c00
ax_pose_terminator
sKabutopsPose173:
ax_pose 6, 0x01e6, 0x80f0, 0x6c00
ax_pose_terminator
sKabutopsPose174:
ax_pose 9, 0x01e6, 0x80f0, 0x6c00
ax_pose_terminator
sKabutopsPose175:
ax_pose 12, 0x01e6, 0x80f0, 0x6c00
ax_pose_terminator
sKabutopsPose176:
ax_pose 9, 0x01e6, 0x90f1, 0x6c00
ax_pose_terminator
sKabutopsPose177:
ax_pose 6, 0x01e6, 0x90f1, 0x6c00
ax_pose_terminator
sKabutopsPose178:
ax_pose 3, 0x01e6, 0x90ee, 0x6c00
ax_pose_terminator
sKabutopsPose179:
ax_pose 0, 0x01e6, 0x80f0, 0x6c00
ax_pose_terminator
sKabutopsPose180:
ax_pose 3, 0x01e6, 0x90ee, 0x6c00
ax_pose_terminator
sKabutopsPose181:
ax_pose 6, 0x01e6, 0x90f1, 0x6c00
ax_pose_terminator
sKabutopsPose182:
ax_pose 9, 0x01e6, 0x90f1, 0x6c00
ax_pose_terminator
sKabutopsPose183:
ax_pose 12, 0x01e6, 0x80f0, 0x6c00
ax_pose_terminator
sKabutopsPose184:
ax_pose 9, 0x01e6, 0x80f0, 0x6c00
ax_pose_terminator
sKabutopsPose185:
ax_pose 6, 0x01e6, 0x80f0, 0x6c00
ax_pose_terminator
sKabutopsPose186:
ax_pose 3, 0x01e6, 0x80f3, 0x6c00
ax_pose_terminator
sKabutopsPose187:
ax_pose 0, 0x01e6, 0x80f0, 0x6c00
ax_pose_terminator
sKabutopsPose188:
ax_pose 43, 0x81ec, 0x40f7, 0x6c00
ax_pose 44, 0x81ec, 0x80ff, 0x6c04
ax_pose 45, 0x81ec, 0x00ef, 0x6c0c
ax_pose 46, 0x01ee, 0x010f, 0x6c0e
ax_pose_terminator
sKabutopsPose189:
ax_pose 47, 0x81ec, 0x40f7, 0x6c00
ax_pose 48, 0x81ec, 0x80ff, 0x6c04
ax_pose 49, 0x81ec, 0x00ef, 0x6c0c
ax_pose 50, 0x01ee, 0x010f, 0x6c0e
ax_pose_terminator
sKabutopsPose190:
ax_pose 3, 0x01e6, 0x90ee, 0x6c00
ax_pose_terminator
sKabutopsPose191:
ax_pose 51, 0x01e6, 0x90f0, 0x6c00
ax_pose_terminator
sKabutopsPose192:
ax_pose 52, 0x01e6, 0x90f0, 0x6c00
ax_pose_terminator
sKabutopsPose193:
ax_pose 6, 0x01e6, 0x90f1, 0x6c00
ax_pose_terminator
sKabutopsPose194:
ax_pose 53, 0x01e6, 0x90f2, 0x6c00
ax_pose_terminator
sKabutopsPose195:
ax_pose 54, 0x01e6, 0x90f2, 0x6c00
ax_pose_terminator
sKabutopsPose196:
ax_pose 9, 0x01e6, 0x90f1, 0x6c00
ax_pose_terminator
sKabutopsPose197:
ax_pose 55, 0x01e6, 0x90f1, 0x6c00
ax_pose_terminator
sKabutopsPose198:
ax_pose 56, 0x01e6, 0x90f1, 0x6c00
ax_pose_terminator
sKabutopsPose199:
ax_pose 12, 0x01e6, 0x80f0, 0x6c00
ax_pose_terminator
sKabutopsPose200:
ax_pose 57, 0x01e6, 0x80f1, 0x6c00
ax_pose_terminator
sKabutopsPose201:
ax_pose 58, 0x01e6, 0x80f1, 0x6c00
ax_pose_terminator
sKabutopsPose202:
ax_pose 9, 0x01e6, 0x80f0, 0x6c00
ax_pose_terminator
sKabutopsPose203:
ax_pose 55, 0x01e6, 0x80f0, 0x6c00
ax_pose_terminator
sKabutopsPose204:
ax_pose 56, 0x01e6, 0x80f0, 0x6c00
ax_pose_terminator
sKabutopsPose205:
ax_pose 6, 0x01e6, 0x80f0, 0x6c00
ax_pose_terminator
sKabutopsPose206:
ax_pose 53, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sKabutopsPose207:
ax_pose 54, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sKabutopsPose208:
ax_pose 3, 0x01e6, 0x80f3, 0x6c00
ax_pose_terminator
sKabutopsPose209:
ax_pose 51, 0x01e6, 0x80f1, 0x6c00
ax_pose_terminator
sKabutopsPose210:
ax_pose 52, 0x01e6, 0x80f1, 0x6c00
ax_pose_terminator
sKabutopsPose211:
ax_pose 47, 0x81ec, 0x40f7, 0x6c00
ax_pose 48, 0x81ec, 0x80ff, 0x6c04
ax_pose 49, 0x81ec, 0x00ef, 0x6c0c
ax_pose 50, 0x01ee, 0x010f, 0x6c0e
ax_pose_terminator
sKabutopsPose212:
ax_pose 52, 0x01e6, 0x80f1, 0x6c00
ax_pose_terminator
sKabutopsPose213:
ax_pose 54, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sKabutopsPose214:
ax_pose 56, 0x01e6, 0x80f0, 0x6c00
ax_pose_terminator
sKabutopsPose215:
ax_pose 58, 0x01e6, 0x80f1, 0x6c00
ax_pose_terminator
sKabutopsPose216:
ax_pose 56, 0x01e6, 0x90f1, 0x6c00
ax_pose_terminator
sKabutopsPose217:
ax_pose 54, 0x01e6, 0x90f2, 0x6c00
ax_pose_terminator
sKabutopsPose218:
ax_pose 52, 0x01e6, 0x90f0, 0x6c00
ax_pose_terminator
sKabutopsPose219:
ax_pose 0, 0x01e6, 0x80f0, 0x6c00
ax_pose_terminator
sKabutopsPose220:
ax_pose 3, 0x01e6, 0x80f3, 0x6c00
ax_pose_terminator
sKabutopsPose221:
ax_pose 6, 0x01e6, 0x80f0, 0x6c00
ax_pose_terminator
sKabutopsPose222:
ax_pose 9, 0x01e6, 0x80f0, 0x6c00
ax_pose_terminator
sKabutopsPose223:
ax_pose 12, 0x01e6, 0x80f0, 0x6c00
ax_pose_terminator
sKabutopsPose224:
ax_pose 9, 0x01e6, 0x90f1, 0x6c00
ax_pose_terminator
sKabutopsPose225:
ax_pose 6, 0x01e6, 0x90f1, 0x6c00
ax_pose_terminator
sKabutopsPose226:
ax_pose 3, 0x01e6, 0x90ee, 0x6c00
ax_pose_terminator
.align 2
sKabutopsAnims_1_1:
ax_anim 6, 0, 0, 0, 0, 0, 0,
ax_anim 4, 0, 1, 0, 1, 0, 1,
ax_anim 8, 0, 1, 1, 2, 1, 2,
ax_anim 4, 0, 1, 0, 1, 0, 1,
ax_anim 6, 0, 0, 0, 0, 0, 0,
ax_anim 4, 0, 2, 1, 1, 1, 1,
ax_anim 8, 0, 2, 0, 2, 0, 2,
ax_anim 4, 0, 2, 0, 1, 0, 1,
ax_anim_terminator
sKabutopsAnims_1_2:
ax_anim 6, 0, 3, 0, 0, 0, 0,
ax_anim 4, 0, 4, 2, 2, 2, 2,
ax_anim 8, 0, 4, 4, 3, 4, 3,
ax_anim 4, 0, 4, 2, 2, 2, 2,
ax_anim 6, 0, 3, 0, 0, 0, 0,
ax_anim 4, 0, 5, 2, 0, 2, 0,
ax_anim 8, 0, 5, 3, 1, 3, 1,
ax_anim 4, 0, 5, 2, 0, 2, 0,
ax_anim_terminator
sKabutopsAnims_1_3:
ax_anim 6, 0, 6, 0, 0, 0, 0,
ax_anim 4, 0, 7, 2, 0, 2, 0,
ax_anim 8, 0, 7, 3, 0, 3, 0,
ax_anim 4, 0, 7, 2, 0, 2, 0,
ax_anim 6, 0, 6, 0, 0, 0, 0,
ax_anim 4, 0, 8, 2, 0, 2, 0,
ax_anim 8, 0, 8, 3, 0, 3, 0,
ax_anim 4, 0, 8, 2, 0, 2, 0,
ax_anim_terminator
sKabutopsAnims_1_4:
ax_anim 6, 0, 9, 0, 0, 0, 0,
ax_anim 4, 0, 10, 4, -1, 4, -1,
ax_anim 8, 0, 10, 5, -2, 5, -2,
ax_anim 4, 0, 10, 4, -1, 4, -1,
ax_anim 6, 0, 9, 0, 0, 0, 0,
ax_anim 4, 0, 11, 1, -1, 1, -1,
ax_anim 8, 0, 11, 3, -3, 3, -3,
ax_anim 4, 0, 11, 1, -1, 1, -1,
ax_anim_terminator
sKabutopsAnims_1_5:
ax_anim 6, 0, 12, 0, 0, 0, 0,
ax_anim 4, 0, 13, 1, -2, 1, -2,
ax_anim 8, 0, 13, 0, -3, 0, -3,
ax_anim 4, 0, 13, 1, -2, 1, -2,
ax_anim 6, 0, 12, 0, 0, 0, 0,
ax_anim 4, 0, 14, -1, -2, -1, -2,
ax_anim 8, 0, 14, 0, -3, 0, -3,
ax_anim 4, 0, 14, -1, -2, -1, -2,
ax_anim_terminator
sKabutopsAnims_1_6:
ax_anim 6, 0, 15, 0, 0, 0, 0,
ax_anim 4, 0, 16, -4, -1, -4, -1,
ax_anim 8, 0, 16, -5, -2, -5, -2,
ax_anim 4, 0, 16, -4, -1, -4, -1,
ax_anim 6, 0, 15, 0, 0, 0, 0,
ax_anim 4, 0, 17, -1, -1, -1, -1,
ax_anim 8, 0, 17, -3, -3, -3, -3,
ax_anim 4, 0, 17, -1, -1, -1, -1,
ax_anim_terminator
sKabutopsAnims_1_7:
ax_anim 6, 0, 18, 0, 0, 0, 0,
ax_anim 4, 0, 19, -2, 0, -2, 0,
ax_anim 8, 0, 19, -3, 0, -3, 0,
ax_anim 4, 0, 19, -2, 0, -2, 0,
ax_anim 6, 0, 18, 0, 0, 0, 0,
ax_anim 4, 0, 20, -2, 0, -2, 0,
ax_anim 8, 0, 20, -3, 0, -3, 0,
ax_anim 4, 0, 20, -2, 0, -2, 0,
ax_anim_terminator
sKabutopsAnims_1_8:
ax_anim 6, 0, 21, 0, 0, 0, 0,
ax_anim 4, 0, 22, -2, 2, -2, 2,
ax_anim 8, 0, 22, -4, 3, -4, 3,
ax_anim 4, 0, 22, -2, 2, -2, 2,
ax_anim 6, 0, 21, 0, 0, 0, 0,
ax_anim 4, 0, 23, -2, 0, -2, 0,
ax_anim 8, 0, 23, -3, 1, -3, 1,
ax_anim 4, 0, 23, -2, 0, -2, 0,
ax_anim_terminator
.align 2
sKabutopsAnims_2_1:
ax_anim 4, 0, 24, 0, 0, 0, 0,
ax_anim 2, 0, 24, 0, -1, 0, -1,
ax_anim 4, 0, 24, 0, -2, 0, -2,
ax_anim 2, 0, 26, 0, 0, 0, 0,
ax_anim 2, 0, 25, 0, 4, 0, 4,
ax_anim 2, 2, 25, 0, 10, 0, 10,
ax_anim 2, 0, 25, 0, 18, 0, 18,
ax_anim 2, 1, 25, 1, 18, 1, 18,
ax_anim 2, 0, 25, 0, 18, 0, 18,
ax_anim 2, 0, 25, 1, 18, 1, 18,
ax_anim 4, 0, 24, 0, 6, 0, 6,
ax_anim_terminator
sKabutopsAnims_2_2:
ax_anim 4, 0, 27, 0, 0, 0, 0,
ax_anim 2, 0, 27, -1, -1, -1, -1,
ax_anim 4, 0, 27, -2, -2, -2, -2,
ax_anim 2, 0, 29, 0, -1, 0, 0,
ax_anim 2, 0, 28, 4, 4, 4, 4,
ax_anim 2, 2, 28, 9, 9, 9, 9,
ax_anim 2, 0, 28, 16, 16, 16, 16,
ax_anim 2, 1, 28, 17, 15, 17, 15,
ax_anim 2, 0, 28, 16, 16, 16, 16,
ax_anim 2, 0, 28, 17, 15, 17, 15,
ax_anim 4, 0, 27, 7, 7, 7, 7,
ax_anim_terminator
sKabutopsAnims_2_3:
ax_anim 4, 0, 30, 0, 0, 0, 0,
ax_anim 2, 0, 30, -1, 0, -1, 0,
ax_anim 4, 0, 30, -2, 0, -2, 0,
ax_anim 2, 0, 32, 0, 0, 0, 0,
ax_anim 2, 0, 31, 4, 0, 4, 0,
ax_anim 2, 2, 31, 8, 0, 8, 0,
ax_anim 2, 0, 31, 14, 0, 14, 0,
ax_anim 2, 1, 31, 14, 1, 14, 1,
ax_anim 2, 0, 31, 14, 0, 14, 0,
ax_anim 2, 0, 31, 14, 1, 14, 1,
ax_anim 4, 0, 30, 4, 0, 4, 0,
ax_anim_terminator
sKabutopsAnims_2_4:
ax_anim 4, 0, 33, 0, 0, 0, 0,
ax_anim 2, 0, 33, -1, 1, -1, 1,
ax_anim 4, 0, 33, -2, 2, -2, 2,
ax_anim 2, 0, 35, 0, 0, 0, -1,
ax_anim 2, 0, 34, 4, -4, 4, -4,
ax_anim 2, 2, 34, 8, -8, 8, -8,
ax_anim 2, 0, 34, 14, -14, 14, -14,
ax_anim 2, 1, 34, 15, -13, 15, -13,
ax_anim 2, 0, 34, 14, -14, 14, -14,
ax_anim 2, 0, 34, 15, -13, 15, -13,
ax_anim 4, 0, 33, 6, -6, 6, -6,
ax_anim_terminator
sKabutopsAnims_2_5:
ax_anim 4, 0, 36, 0, 0, 0, 0,
ax_anim 2, 0, 36, 0, 1, 0, 1,
ax_anim 4, 0, 36, 0, 2, 0, 2,
ax_anim 2, 0, 38, 0, 0, 0, 0,
ax_anim 2, 0, 37, 0, -4, 0, -4,
ax_anim 2, 2, 37, 0, -8, 0, -8,
ax_anim 2, 0, 37, 0, -14, 0, -14,
ax_anim 2, 1, 37, 1, -14, 1, -14,
ax_anim 2, 0, 37, 0, -14, 0, -14,
ax_anim 2, 0, 37, 1, -14, 1, -14,
ax_anim 4, 0, 36, 0, -4, 0, -4,
ax_anim_terminator
sKabutopsAnims_2_6:
ax_anim 4, 0, 39, 0, 0, 0, 0,
ax_anim 2, 0, 39, 1, 1, 1, 1,
ax_anim 4, 0, 39, 2, 2, 2, 2,
ax_anim 2, 0, 41, 0, 0, 0, -1,
ax_anim 2, 0, 40, -4, -4, -4, -4,
ax_anim 2, 2, 40, -8, -8, -8, -8,
ax_anim 2, 0, 40, -14, -14, -14, -14,
ax_anim 2, 1, 40, -15, -13, -15, -13,
ax_anim 2, 0, 40, -14, -14, -14, -14,
ax_anim 2, 0, 40, -15, -13, -15, -13,
ax_anim 4, 0, 39, -6, -6, -6, -6,
ax_anim_terminator
sKabutopsAnims_2_7:
ax_anim 4, 0, 42, 0, 0, 0, 0,
ax_anim 2, 0, 42, 1, 0, 1, 0,
ax_anim 4, 0, 42, 2, 0, 2, 0,
ax_anim 2, 0, 44, 0, 0, 0, 0,
ax_anim 2, 0, 43, -4, 0, -4, 0,
ax_anim 2, 2, 43, -8, 0, -8, 0,
ax_anim 2, 0, 43, -14, 0, -14, 0,
ax_anim 2, 1, 43, -14, 1, -14, 1,
ax_anim 2, 0, 43, -14, 0, -14, 0,
ax_anim 2, 0, 43, -14, 1, -14, 1,
ax_anim 4, 0, 42, -4, 0, -4, 0,
ax_anim_terminator
sKabutopsAnims_2_8:
ax_anim 4, 0, 45, 0, 0, 0, 0,
ax_anim 2, 0, 45, 1, -1, 1, -1,
ax_anim 4, 0, 45, 2, -2, 2, -2,
ax_anim 2, 0, 46, 0, 0, 0, 0,
ax_anim 2, 0, 47, -4, 4, -4, 4,
ax_anim 2, 2, 46, -9, 9, -9, 9,
ax_anim 2, 0, 46, -15, 17, -15, 17,
ax_anim 2, 1, 46, -16, 16, -16, 16,
ax_anim 2, 0, 46, -15, 17, -15, 17,
ax_anim 2, 0, 46, -15, 17, -15, 17,
ax_anim 4, 0, 45, -5, 5, -5, 5,
ax_anim_terminator
.align 2
sKabutopsAnims_3_1:
ax_anim 2, 0, 49, 0, -1, 0, -1,
ax_anim 6, 0, 49, 0, -3, 0, -3,
ax_anim 2, 0, 49, 0, 4, 0, 4,
ax_anim 4, 2, 50, 0, 12, 0, 12,
ax_anim 4, 1, 51, 0, 13, 0, 13,
ax_anim 2, 0, 52, 0, 13, 0, 13,
ax_anim 2, 0, 52, 0, 12, 0, 12,
ax_anim 4, 0, 52, 0, 11, 0, 11,
ax_anim 4, 0, 53, 0, 14, 0, 14,
ax_anim 4, 0, 54, 1, 15, 1, 15,
ax_anim 4, 0, 48, 0, 11, 0, 11,
ax_anim_terminator
sKabutopsAnims_3_2:
ax_anim 2, 0, 56, -1, -1, -1, -1,
ax_anim 6, 0, 56, -3, -3, -3, -3,
ax_anim 2, 0, 56, 4, 4, 4, 4,
ax_anim 4, 2, 57, 16, 16, 16, 16,
ax_anim 4, 1, 58, 17, 17, 17, 17,
ax_anim 2, 0, 59, 17, 17, 17, 17,
ax_anim 2, 0, 59, 16, 16, 16, 16,
ax_anim 4, 0, 59, 15, 15, 15, 15,
ax_anim 4, 0, 60, 18, 18, 18, 18,
ax_anim 4, 0, 61, 17, 19, 17, 19,
ax_anim 4, 0, 55, 10, 10, 10, 10,
ax_anim_terminator
sKabutopsAnims_3_3:
ax_anim 2, 0, 63, -1, 0, -1, 0,
ax_anim 6, 0, 63, -3, 0, -3, 0,
ax_anim 2, 0, 63, 4, 0, 4, 0,
ax_anim 4, 2, 64, 13, 0, 16, 0,
ax_anim 4, 1, 65, 14, 0, 17, 0,
ax_anim 2, 0, 66, 14, 0, 17, 0,
ax_anim 2, 0, 66, 13, 0, 16, 0,
ax_anim 4, 0, 66, 12, 0, 15, 0,
ax_anim 4, 0, 67, 15, 0, 18, 0,
ax_anim 4, 0, 68, 14, 0, 17, 0,
ax_anim 4, 0, 62, 7, 0, 10, 0,
ax_anim_terminator
sKabutopsAnims_3_4:
ax_anim 2, 0, 70, -1, 1, -1, 1,
ax_anim 6, 0, 70, -3, 3, -3, 3,
ax_anim 2, 0, 70, 4, -4, 4, -4,
ax_anim 4, 2, 71, 16, -16, 16, -16,
ax_anim 4, 1, 72, 16, -17, 16, -17,
ax_anim 2, 0, 73, 17, -17, 17, -17,
ax_anim 2, 0, 73, 16, -16, 16, -16,
ax_anim 4, 0, 73, 15, -15, 15, -15,
ax_anim 4, 0, 74, 18, -18, 18, -18,
ax_anim 4, 0, 75, 20, -19, 20, -19,
ax_anim 4, 0, 69, 10, -10, 10, -10,
ax_anim_terminator
sKabutopsAnims_3_5:
ax_anim 2, 0, 77, 0, 1, 0, 1,
ax_anim 6, 0, 77, 0, 3, 0, 3,
ax_anim 2, 0, 77, 0, -4, 0, -4,
ax_anim 4, 2, 78, 0, -16, 0, -14,
ax_anim 4, 1, 79, 0, -17, 0, -15,
ax_anim 2, 0, 80, 0, -17, 0, -15,
ax_anim 2, 0, 80, 0, -16, 0, -14,
ax_anim 4, 0, 80, 0, -15, 0, -13,
ax_anim 4, 0, 81, 0, -18, 0, -16,
ax_anim 4, 0, 82, 1, -19, 1, -17,
ax_anim 4, 0, 76, 0, -15, 0, -13,
ax_anim_terminator
sKabutopsAnims_3_6:
ax_anim 2, 0, 84, 1, 1, 1, 1,
ax_anim 6, 0, 84, 3, 3, 3, 3,
ax_anim 2, 0, 84, -4, -4, -4, -4,
ax_anim 4, 2, 85, -16, -16, -16, -16,
ax_anim 4, 1, 86, -15, -18, -15, -18,
ax_anim 2, 0, 87, -17, -17, -17, -17,
ax_anim 2, 0, 87, -16, -16, -16, -16,
ax_anim 4, 0, 87, -15, -15, -15, -15,
ax_anim 4, 0, 88, -18, -18, -18, -18,
ax_anim 4, 0, 89, -20, -19, -20, -19,
ax_anim 4, 0, 83, -10, -10, -10, -10,
ax_anim_terminator
sKabutopsAnims_3_7:
ax_anim 2, 0, 91, 1, 0, 1, 0,
ax_anim 6, 0, 91, 3, 0, 3, 0,
ax_anim 2, 0, 91, -4, 0, -4, 0,
ax_anim 4, 2, 92, -13, 0, -16, 0,
ax_anim 4, 1, 93, -14, 0, -17, 0,
ax_anim 2, 0, 94, -14, 0, -17, 0,
ax_anim 2, 0, 94, -13, 0, -16, 0,
ax_anim 4, 0, 94, -12, 0, -15, 0,
ax_anim 4, 0, 95, -15, 0, -18, 0,
ax_anim 4, 0, 96, -14, 0, -17, 0,
ax_anim 4, 0, 90, -7, 0, -10, 0,
ax_anim_terminator
sKabutopsAnims_3_8:
ax_anim 2, 0, 98, 1, -1, 1, -1,
ax_anim 6, 0, 98, 3, -3, 3, -3,
ax_anim 2, 0, 98, -4, 4, -4, 4,
ax_anim 4, 2, 99, -16, 16, -16, 16,
ax_anim 4, 1, 100, -17, 17, -17, 17,
ax_anim 2, 0, 101, -17, 17, -17, 17,
ax_anim 2, 0, 101, -16, 16, -16, 16,
ax_anim 4, 0, 101, -15, 15, -15, 15,
ax_anim 4, 0, 102, -18, 18, -18, 18,
ax_anim 4, 0, 103, -17, 19, -17, 19,
ax_anim 4, 0, 97, -18, 18, -18, 18,
ax_anim_terminator
.align 2
sKabutopsAnims_4_1:
ax_anim 4, 0, 104, 0, -1, 0, -1,
ax_anim 6, 0, 104, 0, -3, 0, -3,
ax_anim 2, 0, 105, 0, 0, 0, 1,
ax_anim 2, 2, 106, 0, 0, 0, 1,
ax_anim 2, 0, 105, 0, 0, 0, 1,
ax_anim 2, 0, 106, 0, 0, 0, 1,
ax_anim 2, 0, 105, 0, 0, 0, 1,
ax_anim 2, 1, 106, 0, 0, 0, 1,
ax_anim 4, 0, 104, 0, 1, 0, 0,
ax_anim_terminator
sKabutopsAnims_4_2:
ax_anim 4, 0, 107, -1, -1, -1, -1,
ax_anim 6, 0, 107, -3, -3, -3, -3,
ax_anim 2, 0, 108, 1, 1, 1, 1,
ax_anim 2, 2, 109, 1, 1, 1, 1,
ax_anim 2, 0, 108, 1, 1, 1, 1,
ax_anim 2, 0, 109, 1, 1, 1, 1,
ax_anim 2, 0, 108, 1, 1, 1, 1,
ax_anim 2, 1, 109, 1, 1, 1, 1,
ax_anim 4, 0, 107, 1, 1, 1, 1,
ax_anim_terminator
sKabutopsAnims_4_3:
ax_anim 4, 0, 110, -1, 0, -1, 0,
ax_anim 6, 0, 110, -3, 0, -3, 0,
ax_anim 2, 0, 111, 1, 0, 1, 0,
ax_anim 2, 2, 112, 1, 0, 1, 0,
ax_anim 2, 0, 111, 1, 0, 1, 0,
ax_anim 2, 0, 112, 1, 0, 1, 0,
ax_anim 2, 0, 111, 1, 0, 1, 0,
ax_anim 2, 1, 112, 1, 0, 1, 0,
ax_anim 4, 0, 110, 1, 0, 1, 0,
ax_anim_terminator
sKabutopsAnims_4_4:
ax_anim 4, 0, 113, -1, 1, -1, 1,
ax_anim 6, 0, 113, -3, 3, -3, 3,
ax_anim 2, 0, 114, 1, -1, 1, -1,
ax_anim 2, 2, 115, 1, -1, 1, -1,
ax_anim 2, 0, 114, 1, -1, 1, -1,
ax_anim 2, 0, 115, 1, -1, 1, -1,
ax_anim 2, 0, 114, 1, -1, 1, -1,
ax_anim 2, 1, 115, 1, -1, 1, -1,
ax_anim 4, 0, 113, 1, -1, 1, -1,
ax_anim_terminator
sKabutopsAnims_4_5:
ax_anim 4, 0, 116, 0, 1, 0, 1,
ax_anim 6, 0, 116, 0, 3, 0, 3,
ax_anim 2, 0, 117, 0, -1, 0, -1,
ax_anim 2, 2, 118, 0, -1, 0, -1,
ax_anim 2, 0, 117, 0, -1, 0, -1,
ax_anim 2, 0, 118, 0, -1, 0, -1,
ax_anim 2, 0, 117, 0, -1, 0, -1,
ax_anim 2, 1, 118, 0, -1, 0, -1,
ax_anim 4, 0, 116, 0, -1, 0, 0,
ax_anim_terminator
sKabutopsAnims_4_6:
ax_anim 4, 0, 119, 1, 1, 1, 1,
ax_anim 6, 0, 119, 3, 3, 3, 3,
ax_anim 2, 0, 120, -1, -1, -1, -1,
ax_anim 2, 2, 121, -1, -1, -1, -1,
ax_anim 2, 0, 120, -1, -1, -1, -1,
ax_anim 2, 0, 121, -1, -1, -1, -1,
ax_anim 2, 0, 120, -1, -1, -1, -1,
ax_anim 2, 1, 121, -1, -1, -1, -1,
ax_anim 4, 0, 119, -1, -1, -1, -1,
ax_anim_terminator
sKabutopsAnims_4_7:
ax_anim 4, 0, 122, 1, 0, 1, 0,
ax_anim 6, 0, 122, 3, 0, 3, 0,
ax_anim 2, 0, 123, -1, 0, -1, 0,
ax_anim 2, 2, 124, -1, 0, -1, 0,
ax_anim 2, 0, 123, -1, 0, -1, 0,
ax_anim 2, 0, 124, -1, 0, -1, 0,
ax_anim 2, 0, 123, -1, 0, -1, 0,
ax_anim 2, 1, 124, -1, 0, -1, 0,
ax_anim 4, 0, 122, -1, 0, -1, 0,
ax_anim_terminator
sKabutopsAnims_4_8:
ax_anim 4, 0, 125, 1, -1, 1, -1,
ax_anim 6, 0, 125, 3, -3, 3, -3,
ax_anim 2, 0, 126, -1, 1, -1, 1,
ax_anim 2, 2, 127, -1, 1, -1, 1,
ax_anim 2, 0, 126, -1, 1, -1, 1,
ax_anim 2, 0, 127, -1, 1, -1, 1,
ax_anim 2, 0, 126, -1, 1, -1, 1,
ax_anim 2, 1, 127, -1, 1, -1, 1,
ax_anim 4, 0, 125, -1, 1, -1, 1,
ax_anim_terminator
.align 2
sKabutopsAnims_5_1:
ax_anim 2, 0, 128, 0, 0, 0, 0,
ax_anim 2, 0, 129, 0, 0, 0, 0,
ax_anim 2, 0, 130, 0, 0, 0, 0,
ax_anim 2, 0, 131, 0, 0, 0, 0,
ax_anim 2, 0, 132, 0, 0, 0, 0,
ax_anim 2, 0, 133, 0, 0, 0, 0,
ax_anim 2, 0, 134, 0, 0, 0, 0,
ax_anim 2, 0, 135, 0, 0, 0, 0,
ax_anim 2, 2, 128, 0, 0, 0, 0,
ax_anim_terminator
sKabutopsAnims_5_2:
ax_anim 2, 0, 135, 0, 0, 0, 0,
ax_anim 2, 0, 128, 0, 0, 0, 0,
ax_anim 2, 0, 129, 0, 0, 0, 0,
ax_anim 2, 0, 130, 0, 0, 0, 0,
ax_anim 2, 0, 131, 0, 0, 0, 0,
ax_anim 2, 0, 132, 0, 0, 0, 0,
ax_anim 2, 0, 133, 0, 0, 0, 0,
ax_anim 2, 0, 134, 0, 0, 0, 0,
ax_anim 2, 2, 135, 0, 0, 0, 0,
ax_anim_terminator
sKabutopsAnims_5_3:
ax_anim 2, 0, 134, 0, 0, 0, 0,
ax_anim 2, 0, 135, 0, 0, 0, 0,
ax_anim 2, 0, 128, 0, 0, 0, 0,
ax_anim 2, 0, 129, 0, 0, 0, 0,
ax_anim 2, 0, 130, 0, 0, 0, 0,
ax_anim 2, 0, 131, 0, 0, 0, 0,
ax_anim 2, 0, 132, 0, 0, 0, 0,
ax_anim 2, 0, 133, 0, 0, 0, 0,
ax_anim 2, 2, 134, 0, 0, 0, 0,
ax_anim_terminator
sKabutopsAnims_5_4:
ax_anim 2, 0, 133, 0, 0, 0, 0,
ax_anim 2, 0, 134, 0, 0, 0, 0,
ax_anim 2, 0, 135, 0, 0, 0, 0,
ax_anim 2, 0, 128, 0, 0, 0, 0,
ax_anim 2, 0, 129, 0, 0, 0, 0,
ax_anim 2, 0, 130, 0, 0, 0, 0,
ax_anim 2, 0, 131, 0, 0, 0, 0,
ax_anim 2, 0, 132, 0, 0, 0, 0,
ax_anim 2, 2, 133, 0, 0, 0, 0,
ax_anim_terminator
sKabutopsAnims_5_5:
ax_anim 2, 0, 132, 0, 0, 0, 0,
ax_anim 2, 0, 133, 0, 0, 0, 0,
ax_anim 2, 0, 134, 0, 0, 0, 0,
ax_anim 2, 0, 135, 0, 0, 0, 0,
ax_anim 2, 0, 128, 0, 0, 0, 0,
ax_anim 2, 0, 129, 0, 0, 0, 0,
ax_anim 2, 0, 130, 0, 0, 0, 0,
ax_anim 2, 0, 131, 0, 0, 0, 0,
ax_anim 2, 2, 132, 0, 0, 0, 0,
ax_anim_terminator
sKabutopsAnims_5_6:
ax_anim 2, 0, 131, 0, 0, 0, 0,
ax_anim 2, 0, 132, 0, 0, 0, 0,
ax_anim 2, 0, 133, 0, 0, 0, 0,
ax_anim 2, 0, 134, 0, 0, 0, 0,
ax_anim 2, 0, 135, 0, 0, 0, 0,
ax_anim 2, 0, 128, 0, 0, 0, 0,
ax_anim 2, 0, 129, 0, 0, 0, 0,
ax_anim 2, 0, 130, 0, 0, 0, 0,
ax_anim 2, 2, 131, 0, 0, 0, 0,
ax_anim_terminator
sKabutopsAnims_5_7:
ax_anim 2, 0, 130, 0, 0, 0, 0,
ax_anim 2, 0, 131, 0, 0, 0, 0,
ax_anim 2, 0, 132, 0, 0, 0, 0,
ax_anim 2, 0, 133, 0, 0, 0, 0,
ax_anim 2, 0, 134, 0, 0, 0, 0,
ax_anim 2, 0, 135, 0, 0, 0, 0,
ax_anim 2, 0, 128, 0, 0, 0, 0,
ax_anim 2, 0, 129, 0, 0, 0, 0,
ax_anim 2, 2, 130, 0, 0, 0, 0,
ax_anim_terminator
sKabutopsAnims_5_8:
ax_anim 2, 0, 129, 0, 0, 0, 0,
ax_anim 2, 0, 130, 0, 0, 0, 0,
ax_anim 2, 0, 131, 0, 0, 0, 0,
ax_anim 2, 0, 132, 0, 0, 0, 0,
ax_anim 2, 0, 133, 0, 0, 0, 0,
ax_anim 2, 0, 134, 0, 0, 0, 0,
ax_anim 2, 0, 135, 0, 0, 0, 0,
ax_anim 2, 0, 128, 0, 0, 0, 0,
ax_anim 2, 2, 129, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sKabutopsAnims_6_1:
ax_anim 30, 0, 136, 0, 0, 0, 0,
ax_anim 35, 0, 137, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sKabutopsAnims_7_1:
ax_anim 2, 0, 138, 0, -4, 0, -4,
ax_anim 8, 0, 138, 0, -5, 0, -5,
ax_anim_terminator
sKabutopsAnims_7_2:
ax_anim 2, 0, 139, -4, -4, -4, -4,
ax_anim 8, 0, 139, -5, -5, -5, -5,
ax_anim_terminator
sKabutopsAnims_7_3:
ax_anim 2, 0, 140, -4, 0, -4, 0,
ax_anim 8, 0, 140, -5, 0, -5, 0,
ax_anim_terminator
sKabutopsAnims_7_4:
ax_anim 2, 0, 141, -4, 4, -4, 4,
ax_anim 8, 0, 141, -5, 5, -5, 5,
ax_anim_terminator
sKabutopsAnims_7_5:
ax_anim 2, 0, 142, 0, 4, 0, 4,
ax_anim 8, 0, 142, 0, 5, 0, 5,
ax_anim_terminator
sKabutopsAnims_7_6:
ax_anim 2, 0, 143, 4, 4, 4, 4,
ax_anim 8, 0, 143, 5, 5, 5, 5,
ax_anim_terminator
sKabutopsAnims_7_7:
ax_anim 2, 0, 144, 4, 0, 4, 0,
ax_anim 8, 0, 144, 5, 0, 5, 0,
ax_anim_terminator
sKabutopsAnims_7_8:
ax_anim 2, 0, 145, 4, -4, 4, -4,
ax_anim 8, 0, 145, 5, -5, 5, -5,
ax_anim_terminator
.align 2
sKabutopsAnims_8_1:
ax_anim 20, 0, 146, 0, 0, 0, 0,
ax_anim 10, 0, 147, -1, -2, -1, -2,
ax_anim 20, 0, 146, 0, 0, 0, 0,
ax_anim 10, 0, 148, 2, -2, 2, -2,
ax_anim_terminator
sKabutopsAnims_8_2:
ax_anim 20, 0, 149, 0, 0, 0, 0,
ax_anim 10, 0, 150, -2, -2, -2, -2,
ax_anim 20, 0, 149, 0, 0, 0, 0,
ax_anim 10, 0, 151, -3, -2, -3, -2,
ax_anim_terminator
sKabutopsAnims_8_3:
ax_anim 20, 0, 152, 0, 0, 0, 0,
ax_anim 10, 0, 153, -6, -2, -6, -2,
ax_anim 20, 0, 152, 0, 0, 0, 0,
ax_anim 10, 0, 154, -5, 0, -5, 0,
ax_anim_terminator
sKabutopsAnims_8_4:
ax_anim 20, 0, 155, 0, 0, 0, 0,
ax_anim 10, 0, 156, -4, 1, -4, 1,
ax_anim 20, 0, 155, 0, 0, 0, 0,
ax_anim 10, 0, 157, -3, 2, -3, 2,
ax_anim_terminator
sKabutopsAnims_8_5:
ax_anim 20, 0, 158, 0, 0, 0, 0,
ax_anim 10, 0, 159, 0, 4, 0, 4,
ax_anim 20, 0, 158, 0, 0, 0, 0,
ax_anim 10, 0, 160, 1, 4, 1, 4,
ax_anim_terminator
sKabutopsAnims_8_6:
ax_anim 20, 0, 161, 0, 0, 0, 0,
ax_anim 10, 0, 162, 4, 1, 4, 1,
ax_anim 20, 0, 161, 0, 0, 0, 0,
ax_anim 10, 0, 163, 3, 2, 3, 2,
ax_anim_terminator
sKabutopsAnims_8_7:
ax_anim 20, 0, 164, 0, 0, 0, 0,
ax_anim 10, 0, 165, 6, -2, 6, -2,
ax_anim 20, 0, 164, 0, 0, 0, 0,
ax_anim 10, 0, 166, 5, 0, 5, 0,
ax_anim_terminator
sKabutopsAnims_8_8:
ax_anim 20, 0, 167, 0, 0, 0, 0,
ax_anim 10, 0, 168, 2, -2, 2, -2,
ax_anim 20, 0, 167, 0, 0, 0, 0,
ax_anim 10, 0, 169, 4, -2, 4, -2,
ax_anim_terminator
.align 2
sKabutopsAnims_9_1:
ax_anim 2, 0, 170, 0, 0, 0, 0,
ax_anim 1, 0, 171, 6, 4, 6, 4,
ax_anim 2, 0, 172, 8, 9, 8, 9,
ax_anim 2, 0, 173, 7, 13, 7, 13,
ax_anim 3, 0, 174, 1, 16, 1, 16,
ax_anim 2, 3, 175, -4, 14, -4, 14,
ax_anim 2, 0, 176, -5, 8, -5, 8,
ax_anim 1, 0, 177, -4, 4, -4, 4,
ax_anim 1, 0, 170, 0, 0, 0, 0,
ax_anim_terminator
sKabutopsAnims_9_2:
ax_anim 2, 0, 177, 0, 0, 0, 0,
ax_anim 1, 0, 170, 6, 0, 6, 0,
ax_anim 2, 0, 171, 17, 3, 17, 3,
ax_anim 2, 0, 172, 24, 9, 24, 9,
ax_anim 3, 0, 173, 23, 16, 23, 16,
ax_anim 2, 3, 174, 11, 16, 11, 16,
ax_anim 2, 0, 175, 4, 12, 4, 12,
ax_anim 1, 0, 176, 3, 7, 3, 7,
ax_anim 1, 0, 177, 0, 0, 0, 0,
ax_anim_terminator
sKabutopsAnims_9_3:
ax_anim 2, 0, 176, 0, 0, 0, 0,
ax_anim 1, 0, 177, 3, -4, 3, -4,
ax_anim 2, 0, 170, 11, -6, 11, -6,
ax_anim 2, 0, 171, 17, -4, 17, -4,
ax_anim 3, 0, 172, 20, 1, 20, 1,
ax_anim 2, 3, 173, 17, 5, 17, 5,
ax_anim 2, 0, 174, 12, 7, 12, 7,
ax_anim 1, 0, 175, 4, 5, 4, 5,
ax_anim 1, 0, 176, 0, 0, 0, 0,
ax_anim_terminator
sKabutopsAnims_9_4:
ax_anim 2, 0, 175, 0, 0, 0, 0,
ax_anim 1, 0, 176, 1, -6, 1, -6,
ax_anim 2, 0, 177, 4, -16, 4, -16,
ax_anim 2, 0, 170, 11, -20, 11, -20,
ax_anim 3, 0, 171, 16, -20, 16, -20,
ax_anim 2, 3, 172, 16, -15, 16, -15,
ax_anim 2, 0, 173, 14, -6, 14, -6,
ax_anim 1, 0, 174, 7, -1, 7, -1,
ax_anim 1, 0, 175, 0, 0, 0, 0,
ax_anim_terminator
sKabutopsAnims_9_5:
ax_anim 2, 0, 174, 0, 0, 0, 0,
ax_anim 1, 0, 175, -6, -4, -6, -4,
ax_anim 2, 0, 176, -8, -9, -8, -9,
ax_anim 2, 0, 177, -7, -13, -7, -13,
ax_anim 3, 0, 170, -1, -16, -1, -16,
ax_anim 2, 3, 171, 4, -14, 4, -14,
ax_anim 2, 0, 172, 5, -8, 5, -8,
ax_anim 1, 0, 173, 4, -4, 4, -4,
ax_anim 1, 0, 174, 0, 0, 0, 0,
ax_anim_terminator
sKabutopsAnims_9_6:
ax_anim 2, 0, 173, 0, 0, 0, 0,
ax_anim 1, 0, 172, -1, -6, -1, -6,
ax_anim 2, 0, 171, -4, -16, -4, -16,
ax_anim 2, 0, 170, -11, -20, -11, -20,
ax_anim 3, 0, 177, -16, -20, -16, -20,
ax_anim 2, 3, 176, -16, -15, -16, -15,
ax_anim 2, 0, 175, -14, -6, -14, -6,
ax_anim 1, 0, 174, -7, -1, -7, -1,
ax_anim 1, 0, 173, 0, 0, 0, 0,
ax_anim_terminator
sKabutopsAnims_9_7:
ax_anim 2, 0, 172, 0, 0, 0, 0,
ax_anim 1, 0, 171, -3, -4, -3, -4,
ax_anim 2, 0, 170, -11, -6, -11, -6,
ax_anim 2, 0, 177, -17, -4, -17, -4,
ax_anim 3, 0, 176, -20, 1, -20, 1,
ax_anim 2, 3, 175, -17, 5, -17, 5,
ax_anim 2, 0, 174, -12, 7, -12, 7,
ax_anim 1, 0, 173, -4, 5, -4, 5,
ax_anim 1, 0, 172, 0, 0, 0, 0,
ax_anim_terminator
sKabutopsAnims_9_8:
ax_anim 2, 0, 171, 0, 0, 0, 0,
ax_anim 1, 0, 170, -6, 0, -6, 0,
ax_anim 2, 0, 177, -17, 3, -17, 3,
ax_anim 2, 0, 176, -24, 9, -24, 9,
ax_anim 3, 0, 175, -23, 16, -23, 16,
ax_anim 2, 3, 174, -11, 16, -11, 16,
ax_anim 2, 0, 173, -4, 12, -4, 12,
ax_anim 1, 0, 172, -3, 7, -3, 7,
ax_anim 1, 0, 171, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sKabutopsAnims_10_1:
ax_anim 2, 0, 178, 0, 0, 0, 0,
ax_anim 2, 0, 178, 6, 0, 6, 0,
ax_anim 2, 0, 178, -6, 0, -6, 0,
ax_anim 2, 0, 178, 10, 0, 10, 0,
ax_anim 2, 0, 178, -10, 0, -10, 0,
ax_anim 2, 0, 178, 12, 0, 12, 0,
ax_anim 3, 0, 178, -12, 0, -12, 0,
ax_anim 3, 0, 178, 13, 0, 13, 0,
ax_anim 3, 0, 178, -13, 0, -13, 0,
ax_anim 2, 0, 178, 12, 0, 12, 0,
ax_anim 3, 0, 178, -12, 0, -12, 0,
ax_anim 2, 0, 178, 10, 0, 10, 0,
ax_anim 2, 0, 178, -10, 0, -10, 0,
ax_anim 2, 0, 178, 6, 0, 6, 0,
ax_anim 2, 0, 178, -6, 0, -6, 0,
ax_anim 2, 0, 178, 0, 0, 0, 0,
ax_anim_terminator
sKabutopsAnims_10_2:
ax_anim 2, 0, 179, 0, 0, 0, 0,
ax_anim 2, 0, 179, 6, -6, 6, -6,
ax_anim 2, 0, 179, -6, 6, -6, 6,
ax_anim 2, 0, 179, 10, -10, 10, -10,
ax_anim 2, 0, 179, -10, 10, -10, 10,
ax_anim 2, 0, 179, 12, -12, 12, -12,
ax_anim 3, 0, 179, -12, 12, -12, 12,
ax_anim 3, 0, 179, 13, -13, 13, -13,
ax_anim 3, 0, 179, -13, 13, -13, 13,
ax_anim 2, 0, 179, 12, -12, 12, -12,
ax_anim 3, 0, 179, -12, 12, -12, 12,
ax_anim 2, 0, 179, 10, -10, 10, -10,
ax_anim 2, 0, 179, -10, 10, -10, 10,
ax_anim 2, 0, 179, 6, -6, 6, -6,
ax_anim 2, 0, 179, -6, 6, -6, 6,
ax_anim 2, 0, 179, 0, 0, 0, 0,
ax_anim_terminator
sKabutopsAnims_10_3:
ax_anim 2, 0, 180, 0, 0, 0, 0,
ax_anim 2, 0, 180, 0, -6, 0, -6,
ax_anim 2, 0, 180, 0, 6, 0, 6,
ax_anim 2, 0, 180, 0, -10, 0, -10,
ax_anim 2, 0, 180, 0, 10, 0, 10,
ax_anim 2, 0, 180, 0, -12, 0, -12,
ax_anim 3, 0, 180, 0, 12, 0, 12,
ax_anim 3, 0, 180, 0, -13, 0, -13,
ax_anim 3, 0, 180, 0, 13, 0, 13,
ax_anim 2, 0, 180, 0, -12, 0, -12,
ax_anim 3, 0, 180, 0, 12, 0, 12,
ax_anim 2, 0, 180, 0, -10, 0, -10,
ax_anim 2, 0, 180, 0, 10, 0, 10,
ax_anim 2, 0, 180, 0, -6, 0, -6,
ax_anim 2, 0, 180, 0, 6, 0, 6,
ax_anim 2, 0, 180, 0, 0, 0, 0,
ax_anim_terminator
sKabutopsAnims_10_4:
ax_anim 2, 0, 181, 0, 0, 0, 0,
ax_anim 2, 0, 181, -6, -6, -6, -6,
ax_anim 2, 0, 181, 6, 6, 6, 6,
ax_anim 2, 0, 181, -10, -10, -10, -10,
ax_anim 2, 0, 181, 10, 10, 10, 10,
ax_anim 2, 0, 181, -12, -12, -12, -12,
ax_anim 3, 0, 181, 12, 12, 12, 12,
ax_anim 3, 0, 181, -13, -13, -13, -13,
ax_anim 3, 0, 181, 13, 13, 13, 13,
ax_anim 2, 0, 181, -12, -12, -12, -12,
ax_anim 3, 0, 181, 12, 12, 12, 12,
ax_anim 2, 0, 181, -10, -10, -10, -10,
ax_anim 2, 0, 181, 10, 10, 10, 10,
ax_anim 2, 0, 181, -6, -6, -6, -6,
ax_anim 2, 0, 181, 6, 6, 6, 6,
ax_anim 2, 0, 181, 0, 0, 0, 0,
ax_anim_terminator
sKabutopsAnims_10_5:
ax_anim 2, 0, 182, 0, 0, 0, 0,
ax_anim 2, 0, 182, 6, 0, 6, 0,
ax_anim 2, 0, 182, -6, 0, -6, 0,
ax_anim 2, 0, 182, 10, 0, 10, 0,
ax_anim 2, 0, 182, -10, 0, -10, 0,
ax_anim 2, 0, 182, 12, 0, 12, 0,
ax_anim 3, 0, 182, -12, 0, -12, 0,
ax_anim 3, 0, 182, 13, 0, 13, 0,
ax_anim 3, 0, 182, -13, 0, -13, 0,
ax_anim 2, 0, 182, 12, 0, 12, 0,
ax_anim 3, 0, 182, -12, 0, -12, 0,
ax_anim 2, 0, 182, 10, 0, 10, 0,
ax_anim 2, 0, 182, -10, 0, -10, 0,
ax_anim 2, 0, 182, 6, 0, 6, 0,
ax_anim 2, 0, 182, -6, 0, -6, 0,
ax_anim 2, 0, 182, 0, 0, 0, 0,
ax_anim_terminator
sKabutopsAnims_10_6:
ax_anim 2, 0, 183, 0, 0, 0, 0,
ax_anim 2, 0, 183, 6, -6, 6, -6,
ax_anim 2, 0, 183, -6, 6, -6, 6,
ax_anim 2, 0, 183, 10, -10, 10, -10,
ax_anim 2, 0, 183, -10, 10, -10, 10,
ax_anim 2, 0, 183, 12, -12, 12, -12,
ax_anim 3, 0, 183, -12, 12, -12, 12,
ax_anim 3, 0, 183, 13, -13, 13, -13,
ax_anim 3, 0, 183, -13, 13, -13, 13,
ax_anim 2, 0, 183, 12, -12, 12, -12,
ax_anim 3, 0, 183, -12, 12, -12, 12,
ax_anim 2, 0, 183, 10, -10, 10, -10,
ax_anim 2, 0, 183, -10, 10, -10, 10,
ax_anim 2, 0, 183, 6, -6, 6, -6,
ax_anim 2, 0, 183, -6, 6, -6, 6,
ax_anim 2, 0, 183, 0, 0, 0, 0,
ax_anim_terminator
sKabutopsAnims_10_7:
ax_anim 2, 0, 184, 0, 0, 0, 0,
ax_anim 2, 0, 184, 0, -6, 0, -6,
ax_anim 2, 0, 184, 0, 6, 0, 6,
ax_anim 2, 0, 184, 0, -10, 0, -10,
ax_anim 2, 0, 184, 0, 10, 0, 10,
ax_anim 2, 0, 184, 0, -12, 0, -12,
ax_anim 3, 0, 184, 0, 12, 0, 12,
ax_anim 3, 0, 184, 0, -13, 0, -13,
ax_anim 3, 0, 184, 0, 13, 0, 13,
ax_anim 2, 0, 184, 0, -12, 0, -12,
ax_anim 3, 0, 184, 0, 12, 0, 12,
ax_anim 2, 0, 184, 0, -10, 0, -10,
ax_anim 2, 0, 184, 0, 10, 0, 10,
ax_anim 2, 0, 184, 0, -6, 0, -6,
ax_anim 2, 0, 184, 0, 6, 0, 6,
ax_anim 2, 0, 184, 0, 0, 0, 0,
ax_anim_terminator
sKabutopsAnims_10_8:
ax_anim 2, 0, 185, 0, 0, 0, 0,
ax_anim 2, 0, 185, -6, -6, -6, -6,
ax_anim 2, 0, 185, 6, 6, 6, 6,
ax_anim 2, 0, 185, -10, -10, -10, -10,
ax_anim 2, 0, 185, 10, 10, 10, 10,
ax_anim 2, 0, 185, -12, -12, -12, -12,
ax_anim 3, 0, 185, 12, 12, 12, 12,
ax_anim 3, 0, 185, -13, -13, -13, -13,
ax_anim 3, 0, 185, 13, 13, 13, 13,
ax_anim 2, 0, 185, -12, -12, -12, -12,
ax_anim 3, 0, 185, 12, 12, 12, 12,
ax_anim 2, 0, 185, -10, -10, -10, -10,
ax_anim 2, 0, 185, 10, 10, 10, 10,
ax_anim 2, 0, 185, -6, -6, -6, -6,
ax_anim 2, 0, 185, 6, 6, 6, 6,
ax_anim 2, 0, 185, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sKabutopsAnims_11_1:
ax_anim 2, 0, 186, 0, 0, 0, 0,
ax_anim 1, 0, 187, 0, -10, 0, 0,
ax_anim 2, 0, 187, 0, -16, 0, 0,
ax_anim 3, 0, 187, 0, -20, 0, 0,
ax_anim 4, 0, 187, 0, -21, 0, 0,
ax_anim 4, 0, 188, 0, -23, 0, 0,
ax_anim 3, 0, 188, 0, -22, 0, 0,
ax_anim 2, 0, 188, 0, -18, 0, 0,
ax_anim 1, 0, 188, 0, -12, 0, 0,
ax_anim 2, 2, 186, 0, 0, 0, 0,
ax_anim_terminator
sKabutopsAnims_11_2:
ax_anim 2, 0, 189, 0, 0, 0, 0,
ax_anim 1, 0, 190, 0, -10, 0, 0,
ax_anim 2, 0, 190, 0, -16, 0, 0,
ax_anim 3, 0, 190, 0, -20, 0, 0,
ax_anim 4, 0, 190, 0, -21, 0, 0,
ax_anim 4, 0, 191, 0, -23, 0, 0,
ax_anim 3, 0, 191, 0, -22, 0, 0,
ax_anim 2, 0, 191, 0, -18, 0, 0,
ax_anim 1, 0, 191, 0, -12, 0, 0,
ax_anim 2, 2, 189, 0, 0, 0, 0,
ax_anim_terminator
sKabutopsAnims_11_3:
ax_anim 2, 0, 192, 0, 0, 0, 0,
ax_anim 1, 0, 193, 0, -10, 0, 0,
ax_anim 2, 0, 193, 0, -16, 0, 0,
ax_anim 3, 0, 193, 0, -20, 0, 0,
ax_anim 4, 0, 193, 0, -21, 0, 0,
ax_anim 4, 0, 194, 0, -23, 0, 0,
ax_anim 3, 0, 194, 0, -22, 0, 0,
ax_anim 2, 0, 194, 0, -18, 0, 0,
ax_anim 1, 0, 194, 0, -12, 0, 0,
ax_anim 2, 2, 192, 0, 0, 0, 0,
ax_anim_terminator
sKabutopsAnims_11_4:
ax_anim 2, 0, 195, 0, 0, 0, 0,
ax_anim 1, 0, 196, 0, -10, 0, 0,
ax_anim 2, 0, 196, 0, -16, 0, 0,
ax_anim 3, 0, 196, 0, -20, 0, 0,
ax_anim 4, 0, 196, 0, -21, 0, 0,
ax_anim 4, 0, 197, 0, -22, 0, 0,
ax_anim 3, 0, 197, 0, -21, 0, 0,
ax_anim 2, 0, 197, 0, -17, 0, 0,
ax_anim 1, 0, 197, 0, -11, 0, 0,
ax_anim 2, 2, 195, 0, 0, 0, 0,
ax_anim_terminator
sKabutopsAnims_11_5:
ax_anim 2, 0, 198, 0, 0, 0, 0,
ax_anim 1, 0, 199, 0, -10, 0, 0,
ax_anim 2, 0, 199, 0, -16, 0, 0,
ax_anim 3, 0, 199, 0, -20, 0, 0,
ax_anim 4, 0, 199, 0, -21, 0, 0,
ax_anim 4, 0, 200, 0, -23, 0, 0,
ax_anim 3, 0, 200, 0, -22, 0, 0,
ax_anim 2, 0, 200, 0, -18, 0, 0,
ax_anim 1, 0, 200, 0, -12, 0, 0,
ax_anim 2, 2, 198, 0, 0, 0, 0,
ax_anim_terminator
sKabutopsAnims_11_6:
ax_anim 2, 0, 201, 0, 0, 0, 0,
ax_anim 1, 0, 202, 0, -10, 0, 0,
ax_anim 2, 0, 202, 0, -16, 0, 0,
ax_anim 3, 0, 202, 0, -20, 0, 0,
ax_anim 4, 0, 202, 0, -21, 0, 0,
ax_anim 4, 0, 203, 0, -22, 0, 0,
ax_anim 3, 0, 203, 0, -21, 0, 0,
ax_anim 2, 0, 203, 0, -17, 0, 0,
ax_anim 1, 0, 203, 0, -11, 0, 0,
ax_anim 2, 2, 201, 0, 0, 0, 0,
ax_anim_terminator
sKabutopsAnims_11_7:
ax_anim 2, 0, 204, 0, 0, 0, 0,
ax_anim 1, 0, 205, 0, -10, 0, 0,
ax_anim 2, 0, 205, 0, -16, 0, 0,
ax_anim 3, 0, 205, 0, -20, 0, 0,
ax_anim 4, 0, 205, 0, -21, 0, 0,
ax_anim 4, 0, 206, 0, -23, 0, 0,
ax_anim 3, 0, 206, 0, -22, 0, 0,
ax_anim 2, 0, 206, 0, -18, 0, 0,
ax_anim 1, 0, 206, 0, -12, 0, 0,
ax_anim 2, 2, 204, 0, 0, 0, 0,
ax_anim_terminator
sKabutopsAnims_11_8:
ax_anim 2, 0, 207, 0, 0, 0, 0,
ax_anim 1, 0, 208, 0, -10, 0, 0,
ax_anim 2, 0, 208, 0, -16, 0, 0,
ax_anim 3, 0, 208, 0, -20, 0, 0,
ax_anim 4, 0, 208, 0, -21, 0, 0,
ax_anim 4, 0, 209, 0, -23, 0, 0,
ax_anim 3, 0, 209, 0, -22, 0, 0,
ax_anim 2, 0, 209, 0, -18, 0, 0,
ax_anim 1, 0, 209, 0, -12, 0, 0,
ax_anim 2, 2, 207, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sKabutopsAnims_12_1:
ax_anim 2, 0, 210, 1, 0, 1, 0,
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 2, 0, 210, 1, 0, 1, 0,
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 2, 0, 210, 1, 0, 1, 0,
ax_anim 2, 2, 210, 0, 0, 0, 0,
ax_anim 2, 0, 210, 1, 0, 1, 0,
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 2, 0, 210, 1, 0, 1, 0,
ax_anim 2, 1, 210, 0, 0, 0, 0,
ax_anim_terminator
sKabutopsAnims_12_2:
ax_anim 2, 0, 217, 1, -1, 1, 0,
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 0, 217, 1, -1, 1, 0,
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 0, 217, 1, -1, 1, 0,
ax_anim 2, 2, 217, 0, 0, 0, 0,
ax_anim 2, 0, 217, 1, -1, 1, 0,
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 0, 217, 1, -1, 1, 0,
ax_anim 2, 1, 217, 0, 0, 0, 0,
ax_anim_terminator
sKabutopsAnims_12_3:
ax_anim 2, 0, 216, 0, -1, 0, -1,
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, -1, 0, -1,
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, -1, 0, -1,
ax_anim 2, 2, 216, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, -1, 0, -1,
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, -1, 0, -1,
ax_anim 2, 1, 216, 0, 0, 0, 0,
ax_anim_terminator
sKabutopsAnims_12_4:
ax_anim 2, 0, 215, -1, -1, -1, -1,
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 0, 215, -1, -1, -1, -1,
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 0, 215, -1, -1, -1, -1,
ax_anim 2, 2, 215, 0, 0, 0, 0,
ax_anim 2, 0, 215, -1, -1, -1, -1,
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 0, 215, -1, -1, -1, -1,
ax_anim 2, 1, 215, 0, 0, 0, 0,
ax_anim_terminator
sKabutopsAnims_12_5:
ax_anim 2, 0, 214, 1, 0, 1, 0,
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 2, 0, 214, 1, 0, 1, 0,
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 2, 0, 214, 1, 0, 1, 0,
ax_anim 2, 2, 214, 0, 0, 0, 0,
ax_anim 2, 0, 214, 1, 0, 1, 0,
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 2, 0, 214, 1, 0, 1, 0,
ax_anim 2, 1, 214, 0, 0, 0, 0,
ax_anim_terminator
sKabutopsAnims_12_6:
ax_anim 2, 0, 213, 1, -1, 1, -1,
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 2, 0, 213, 1, -1, 1, -1,
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 2, 0, 213, 1, -1, 1, -1,
ax_anim 2, 2, 213, 0, 0, 0, 0,
ax_anim 2, 0, 213, 1, -1, 1, -1,
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 2, 0, 213, 1, -1, 1, -1,
ax_anim 2, 1, 213, 0, 0, 0, 0,
ax_anim_terminator
sKabutopsAnims_12_7:
ax_anim 2, 0, 212, 0, -1, 0, -1,
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 2, 0, 212, 0, -1, 0, -1,
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 2, 0, 212, 0, -1, 0, -1,
ax_anim 2, 2, 212, 0, 0, 0, 0,
ax_anim 2, 0, 212, 0, -1, 0, -1,
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 2, 0, 212, 0, -1, 0, -1,
ax_anim 2, 1, 212, 0, 0, 0, 0,
ax_anim_terminator
sKabutopsAnims_12_8:
ax_anim 2, 0, 211, -1, -1, -1, -1,
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 2, 0, 211, -1, -1, -1, -1,
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 2, 0, 211, -1, -1, -1, -1,
ax_anim 2, 2, 211, 0, 0, 0, 0,
ax_anim 2, 0, 211, -1, -1, -1, -1,
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 2, 0, 211, -1, -1, -1, -1,
ax_anim 2, 1, 211, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sKabutopsAnims_13_1:
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 2, 2, 218, 0, 0, 0, 0,
ax_anim_terminator
sKabutopsAnims_13_2:
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 2, 2, 225, 0, 0, 0, 0,
ax_anim_terminator
sKabutopsAnims_13_3:
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 2, 2, 224, 0, 0, 0, 0,
ax_anim_terminator
sKabutopsAnims_13_4:
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 2, 223, 0, 0, 0, 0,
ax_anim_terminator
sKabutopsAnims_13_5:
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 2, 222, 0, 0, 0, 0,
ax_anim_terminator
sKabutopsAnims_13_6:
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 2, 221, 0, 0, 0, 0,
ax_anim_terminator
sKabutopsAnims_13_7:
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 2, 220, 0, 0, 0, 0,
ax_anim_terminator
sKabutopsAnims_13_8:
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 2, 219, 0, 0, 0, 0,
ax_anim_terminator
sKabutopsGfx1:
.incbin "baserom.gba", 0xB124C4, 0x200
sKabutopsSprites1:
ax_sprite sKabutopsGfx1, 0x200
ax_sprite_terminator
sKabutopsGfx2:
.incbin "baserom.gba", 0xB126D4, 0x200
sKabutopsSprites2:
ax_sprite sKabutopsGfx2, 0x200
ax_sprite_terminator
sKabutopsGfx3:
.incbin "baserom.gba", 0xB128E4, 0x200
sKabutopsSprites3:
ax_sprite sKabutopsGfx3, 0x200
ax_sprite_terminator
sKabutopsGfx4:
.incbin "baserom.gba", 0xB12AF4, 0x200
sKabutopsSprites4:
ax_sprite sKabutopsGfx4, 0x200
ax_sprite_terminator
sKabutopsGfx5:
.incbin "baserom.gba", 0xB12D04, 0x200
sKabutopsSprites5:
ax_sprite sKabutopsGfx5, 0x200
ax_sprite_terminator
sKabutopsGfx6:
.incbin "baserom.gba", 0xB12F14, 0x200
sKabutopsSprites6:
ax_sprite sKabutopsGfx6, 0x200
ax_sprite_terminator
sKabutopsGfx7:
.incbin "baserom.gba", 0xB13124, 0x200
sKabutopsSprites7:
ax_sprite sKabutopsGfx7, 0x200
ax_sprite_terminator
sKabutopsGfx8:
.incbin "baserom.gba", 0xB13334, 0x200
sKabutopsSprites8:
ax_sprite sKabutopsGfx8, 0x200
ax_sprite_terminator
sKabutopsGfx9:
.incbin "baserom.gba", 0xB13544, 0x200
sKabutopsSprites9:
ax_sprite sKabutopsGfx9, 0x200
ax_sprite_terminator
sKabutopsGfx10:
.incbin "baserom.gba", 0xB13754, 0x200
sKabutopsSprites10:
ax_sprite sKabutopsGfx10, 0x200
ax_sprite_terminator
sKabutopsGfx11:
.incbin "baserom.gba", 0xB13964, 0x200
sKabutopsSprites11:
ax_sprite sKabutopsGfx11, 0x200
ax_sprite_terminator
sKabutopsGfx12:
.incbin "baserom.gba", 0xB13B74, 0x200
sKabutopsSprites12:
ax_sprite sKabutopsGfx12, 0x200
ax_sprite_terminator
sKabutopsGfx13:
.incbin "baserom.gba", 0xB13D84, 0x200
sKabutopsSprites13:
ax_sprite sKabutopsGfx13, 0x200
ax_sprite_terminator
sKabutopsGfx14:
.incbin "baserom.gba", 0xB13F94, 0x200
sKabutopsSprites14:
ax_sprite sKabutopsGfx14, 0x200
ax_sprite_terminator
sKabutopsGfx15:
.incbin "baserom.gba", 0xB141A4, 0x200
sKabutopsSprites15:
ax_sprite sKabutopsGfx15, 0x200
ax_sprite_terminator
sKabutopsGfx16:
.incbin "baserom.gba", 0xB143B4, 0x1C0
sKabutopsSprites16:
ax_sprite 0, 0x20
ax_sprite sKabutopsGfx16, 0x1c0
ax_sprite 0, 0x20
ax_sprite_terminator
sKabutopsGfx17:
.incbin "baserom.gba", 0xB14594, 0x20
sKabutopsGfx17_1:
.incbin "baserom.gba", 0xB145B4, 0x20
sKabutopsGfx17_2:
.incbin "baserom.gba", 0xB145D4, 0xC0
sKabutopsSprites17:
ax_sprite 0, 0x60
ax_sprite sKabutopsGfx17, 0x20
ax_sprite 0, 0x60
ax_sprite sKabutopsGfx17_1, 0x20
ax_sprite 0, 0x20
ax_sprite sKabutopsGfx17_2, 0xc0
ax_sprite 0, 0x20
ax_sprite_terminator
sKabutopsGfx18:
.incbin "baserom.gba", 0xB146D4, 0x40
sKabutopsGfx18_1:
.incbin "baserom.gba", 0xB14714, 0xE0
sKabutopsGfx18_2:
.incbin "baserom.gba", 0xB147F4, 0x60
sKabutopsSprites18:
ax_sprite 0, 0x20
ax_sprite sKabutopsGfx18, 0x40
ax_sprite 0, 0x20
ax_sprite sKabutopsGfx18_1, 0xe0
ax_sprite 0, 0x20
ax_sprite sKabutopsGfx18_2, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sKabutopsGfx19:
.incbin "baserom.gba", 0xB14894, 0x60
sKabutopsGfx19_1:
.incbin "baserom.gba", 0xB148F4, 0x100
sKabutopsGfx19_2:
.incbin "baserom.gba", 0xB149F4, 0x60
sKabutopsSprites19:
ax_sprite sKabutopsGfx19, 0x60
ax_sprite 0, 0x20
ax_sprite sKabutopsGfx19_1, 0x100
ax_sprite 0, 0x20
ax_sprite sKabutopsGfx19_2, 0x60
ax_sprite_terminator
sKabutopsGfx20:
.incbin "baserom.gba", 0xB14A84, 0x40
sKabutopsGfx20_1:
.incbin "baserom.gba", 0xB14AC4, 0x80
sKabutopsGfx20_2:
.incbin "baserom.gba", 0xB14B44, 0x60
sKabutopsGfx20_3:
.incbin "baserom.gba", 0xB14BA4, 0x60
sKabutopsSprites20:
ax_sprite 0, 0x20
ax_sprite sKabutopsGfx20, 0x40
ax_sprite 0, 0x20
ax_sprite sKabutopsGfx20_1, 0x80
ax_sprite 0, 0x20
ax_sprite sKabutopsGfx20_2, 0x60
ax_sprite 0, 0x20
ax_sprite sKabutopsGfx20_3, 0x60
ax_sprite_terminator
sKabutopsGfx21:
.incbin "baserom.gba", 0xB14C4C, 0x160
sKabutopsGfx21_1:
.incbin "baserom.gba", 0xB14DAC, 0x60
sKabutopsSprites21:
ax_sprite sKabutopsGfx21, 0x160
ax_sprite 0, 0x20
ax_sprite sKabutopsGfx21_1, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sKabutopsGfx22:
.incbin "baserom.gba", 0xB14E34, 0x100
sKabutopsSprites22:
ax_sprite 0, 0x60
ax_sprite sKabutopsGfx22, 0x100
ax_sprite 0, 0xa0
ax_sprite_terminator
sKabutopsGfx23:
.incbin "baserom.gba", 0xB14F54, 0x60
sKabutopsGfx23_1:
.incbin "baserom.gba", 0xB14FB4, 0x160
sKabutopsSprites23:
ax_sprite sKabutopsGfx23, 0x60
ax_sprite 0, 0x20
ax_sprite sKabutopsGfx23_1, 0x160
ax_sprite 0, 0x20
ax_sprite_terminator
sKabutopsGfx24:
.incbin "baserom.gba", 0xB1513C, 0x40
sKabutopsGfx24_1:
.incbin "baserom.gba", 0xB1517C, 0x80
sKabutopsGfx24_2:
.incbin "baserom.gba", 0xB151FC, 0x60
sKabutopsGfx24_3:
.incbin "baserom.gba", 0xB1525C, 0x20
sKabutopsSprites24:
ax_sprite 0, 0x20
ax_sprite sKabutopsGfx24, 0x40
ax_sprite 0, 0x20
ax_sprite sKabutopsGfx24_1, 0x80
ax_sprite 0, 0x20
ax_sprite sKabutopsGfx24_2, 0x60
ax_sprite 0, 0x40
ax_sprite sKabutopsGfx24_3, 0x20
ax_sprite 0, 0x20
ax_sprite_terminator
sKabutopsGfx25:
.incbin "baserom.gba", 0xB152CC, 0x60
sKabutopsGfx25_1:
.incbin "baserom.gba", 0xB1532C, 0x20
sKabutopsGfx25_2:
.incbin "baserom.gba", 0xB1534C, 0x40
sKabutopsGfx25_3:
.incbin "baserom.gba", 0xB1538C, 0x40
sKabutopsSprites25:
ax_sprite sKabutopsGfx25, 0x60
ax_sprite 0, 0x20
ax_sprite sKabutopsGfx25_1, 0x20
ax_sprite 0, 0x60
ax_sprite sKabutopsGfx25_2, 0x40
ax_sprite 0, 0x40
ax_sprite sKabutopsGfx25_3, 0x40
ax_sprite 0, 0x40
ax_sprite_terminator
sKabutopsGfx26:
.incbin "baserom.gba", 0xB15414, 0x20
sKabutopsGfx26_1:
.incbin "baserom.gba", 0xB15434, 0x160
sKabutopsSprites26:
ax_sprite 0, 0x20
ax_sprite sKabutopsGfx26, 0x20
ax_sprite 0, 0x40
ax_sprite sKabutopsGfx26_1, 0x160
ax_sprite 0, 0x20
ax_sprite_terminator
sKabutopsGfx27:
.incbin "baserom.gba", 0xB155C4, 0x160
sKabutopsGfx27_1:
.incbin "baserom.gba", 0xB15724, 0x40
sKabutopsSprites27:
ax_sprite 0, 0x20
ax_sprite sKabutopsGfx27, 0x160
ax_sprite 0, 0x20
ax_sprite sKabutopsGfx27_1, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sKabutopsGfx28:
.incbin "baserom.gba", 0xB15794, 0x100
sKabutopsSprites28:
ax_sprite sKabutopsGfx28, 0x100
ax_sprite_terminator
sKabutopsGfx29:
.incbin "baserom.gba", 0xB158A4, 0x160
sKabutopsGfx29_1:
.incbin "baserom.gba", 0xB15A04, 0x20
sKabutopsGfx29_2:
.incbin "baserom.gba", 0xB15A24, 0x20
sKabutopsSprites29:
ax_sprite 0, 0x20
ax_sprite sKabutopsGfx29, 0x160
ax_sprite 0, 0x20
ax_sprite sKabutopsGfx29_1, 0x20
ax_sprite 0, 0x20
ax_sprite sKabutopsGfx29_2, 0x20
ax_sprite_terminator
sKabutopsGfx30:
.incbin "baserom.gba", 0xB15A7C, 0x1E0
sKabutopsSprites30:
ax_sprite 0, 0x20
ax_sprite sKabutopsGfx30, 0x1e0
ax_sprite_terminator
sKabutopsGfx31:
.incbin "baserom.gba", 0xB15C74, 0x60
sKabutopsGfx31_1:
.incbin "baserom.gba", 0xB15CD4, 0x40
sKabutopsGfx31_2:
.incbin "baserom.gba", 0xB15D14, 0x20
sKabutopsGfx31_3:
.incbin "baserom.gba", 0xB15D34, 0x40
sKabutopsSprites31:
ax_sprite sKabutopsGfx31, 0x60
ax_sprite 0, 0x20
ax_sprite sKabutopsGfx31_1, 0x40
ax_sprite 0, 0x40
ax_sprite sKabutopsGfx31_2, 0x20
ax_sprite 0, 0x60
ax_sprite sKabutopsGfx31_3, 0x40
ax_sprite 0, 0x40
ax_sprite_terminator
sKabutopsGfx32:
.incbin "baserom.gba", 0xB15DBC, 0x40
sKabutopsGfx32_1:
.incbin "baserom.gba", 0xB15DFC, 0x180
sKabutopsSprites32:
ax_sprite 0, 0x20
ax_sprite sKabutopsGfx32, 0x40
ax_sprite 0, 0x20
ax_sprite sKabutopsGfx32_1, 0x180
ax_sprite_terminator
sKabutopsGfx33:
.incbin "baserom.gba", 0xB15FA4, 0x40
sKabutopsGfx33_1:
.incbin "baserom.gba", 0xB15FE4, 0x80
sKabutopsGfx33_2:
.incbin "baserom.gba", 0xB16064, 0x60
sKabutopsGfx33_3:
.incbin "baserom.gba", 0xB160C4, 0x60
sKabutopsSprites33:
ax_sprite 0, 0x20
ax_sprite sKabutopsGfx33, 0x40
ax_sprite 0, 0x20
ax_sprite sKabutopsGfx33_1, 0x80
ax_sprite 0, 0x20
ax_sprite sKabutopsGfx33_2, 0x60
ax_sprite 0, 0x20
ax_sprite sKabutopsGfx33_3, 0x60
ax_sprite_terminator
sKabutopsGfx34:
.incbin "baserom.gba", 0xB1616C, 0x60
sKabutopsGfx34_1:
.incbin "baserom.gba", 0xB161CC, 0x40
sKabutopsSprites34:
ax_sprite sKabutopsGfx34, 0x60
ax_sprite 0, 0x20
ax_sprite sKabutopsGfx34_1, 0x40
ax_sprite 0, 0x40
ax_sprite_terminator
sKabutopsGfx35:
.incbin "baserom.gba", 0xB16234, 0xE0
sKabutopsGfx35_1:
.incbin "baserom.gba", 0xB16314, 0x60
sKabutopsGfx35_2:
.incbin "baserom.gba", 0xB16374, 0x60
sKabutopsSprites35:
ax_sprite 0, 0x20
ax_sprite sKabutopsGfx35, 0xe0
ax_sprite 0, 0x20
ax_sprite sKabutopsGfx35_1, 0x60
ax_sprite 0, 0x20
ax_sprite sKabutopsGfx35_2, 0x60
ax_sprite_terminator
sKabutopsGfx36:
.incbin "baserom.gba", 0xB1640C, 0x1E0
sKabutopsSprites36:
ax_sprite 0, 0x20
ax_sprite sKabutopsGfx36, 0x1e0
ax_sprite_terminator
sKabutopsGfx37:
.incbin "baserom.gba", 0xB16604, 0x40
sKabutopsGfx37_1:
.incbin "baserom.gba", 0xB16644, 0x100
sKabutopsGfx37_2:
.incbin "baserom.gba", 0xB16744, 0x60
sKabutopsSprites37:
ax_sprite 0, 0x20
ax_sprite sKabutopsGfx37, 0x40
ax_sprite 0, 0x20
ax_sprite sKabutopsGfx37_1, 0x100
ax_sprite 0, 0x20
ax_sprite sKabutopsGfx37_2, 0x60
ax_sprite_terminator
sKabutopsGfx38:
.incbin "baserom.gba", 0xB167DC, 0x60
sKabutopsGfx38_1:
.incbin "baserom.gba", 0xB1683C, 0x20
sKabutopsGfx38_2:
.incbin "baserom.gba", 0xB1685C, 0x40
sKabutopsSprites38:
ax_sprite sKabutopsGfx38, 0x60
ax_sprite 0, 0x20
ax_sprite sKabutopsGfx38_1, 0x20
ax_sprite 0, 0x60
ax_sprite sKabutopsGfx38_2, 0x40
ax_sprite 0, 0xc0
ax_sprite_terminator
sKabutopsGfx39:
.incbin "baserom.gba", 0xB168D4, 0x160
sKabutopsGfx39_1:
.incbin "baserom.gba", 0xB16A34, 0x40
sKabutopsSprites39:
ax_sprite 0, 0x20
ax_sprite sKabutopsGfx39, 0x160
ax_sprite 0, 0x20
ax_sprite sKabutopsGfx39_1, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sKabutopsGfx40:
.incbin "baserom.gba", 0xB16AA4, 0x20
sKabutopsGfx40_1:
.incbin "baserom.gba", 0xB16AC4, 0x60
sKabutopsSprites40:
ax_sprite 0, 0x60
ax_sprite sKabutopsGfx40, 0x20
ax_sprite 0, 0x20
ax_sprite sKabutopsGfx40_1, 0x60
ax_sprite_terminator
sKabutopsGfx41:
.incbin "baserom.gba", 0xB16B4C, 0x140
sKabutopsGfx41_1:
.incbin "baserom.gba", 0xB16C8C, 0x40
sKabutopsSprites41:
ax_sprite 0, 0x20
ax_sprite sKabutopsGfx41, 0x140
ax_sprite 0, 0x40
ax_sprite sKabutopsGfx41_1, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sKabutopsGfx42:
.incbin "baserom.gba", 0xB16CFC, 0x60
sKabutopsGfx42_1:
.incbin "baserom.gba", 0xB16D5C, 0x100
sKabutopsGfx42_2:
.incbin "baserom.gba", 0xB16E5C, 0x40
sKabutopsSprites42:
ax_sprite sKabutopsGfx42, 0x60
ax_sprite 0, 0x20
ax_sprite sKabutopsGfx42_1, 0x100
ax_sprite 0, 0x20
ax_sprite sKabutopsGfx42_2, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sKabutopsGfx43:
.incbin "baserom.gba", 0xB16ED4, 0x60
sKabutopsGfx43_1:
.incbin "baserom.gba", 0xB16F34, 0x80
sKabutopsGfx43_2:
.incbin "baserom.gba", 0xB16FB4, 0x60
sKabutopsGfx43_3:
.incbin "baserom.gba", 0xB17014, 0x40
sKabutopsSprites43:
ax_sprite sKabutopsGfx43, 0x60
ax_sprite 0, 0x20
ax_sprite sKabutopsGfx43_1, 0x80
ax_sprite 0, 0x20
ax_sprite sKabutopsGfx43_2, 0x60
ax_sprite 0, 0x20
ax_sprite sKabutopsGfx43_3, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sKabutopsGfx44:
.incbin "baserom.gba", 0xB1709C, 0x60
sKabutopsSprites44:
ax_sprite sKabutopsGfx44, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sKabutopsGfx45:
.incbin "baserom.gba", 0xB17114, 0xA0
sKabutopsSprites45:
ax_sprite sKabutopsGfx45, 0xa0
ax_sprite 0, 0x60
ax_sprite_terminator
sKabutopsGfx46:
.incbin "baserom.gba", 0xB171CC, 0x40
sKabutopsSprites46:
ax_sprite sKabutopsGfx46, 0x40
ax_sprite_terminator
sKabutopsGfx47:
.incbin "baserom.gba", 0xB1721C, 0x20
sKabutopsSprites47:
ax_sprite sKabutopsGfx47, 0x20
ax_sprite_terminator
sKabutopsGfx48:
.incbin "baserom.gba", 0xB1724C, 0x60
sKabutopsSprites48:
ax_sprite sKabutopsGfx48, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sKabutopsGfx49:
.incbin "baserom.gba", 0xB172C4, 0xA0
sKabutopsSprites49:
ax_sprite sKabutopsGfx49, 0xa0
ax_sprite 0, 0x60
ax_sprite_terminator
sKabutopsGfx50:
.incbin "baserom.gba", 0xB1737C, 0x40
sKabutopsSprites50:
ax_sprite sKabutopsGfx50, 0x40
ax_sprite_terminator
sKabutopsGfx51:
.incbin "baserom.gba", 0xB173CC, 0x20
sKabutopsSprites51:
ax_sprite sKabutopsGfx51, 0x20
ax_sprite_terminator
sKabutopsGfx52:
.incbin "baserom.gba", 0xB173FC, 0x60
sKabutopsGfx52_1:
.incbin "baserom.gba", 0xB1745C, 0x160
sKabutopsSprites52:
ax_sprite sKabutopsGfx52, 0x60
ax_sprite 0, 0x20
ax_sprite sKabutopsGfx52_1, 0x160
ax_sprite 0, 0x20
ax_sprite_terminator
sKabutopsGfx53:
.incbin "baserom.gba", 0xB175E4, 0x60
sKabutopsGfx53_1:
.incbin "baserom.gba", 0xB17644, 0x160
sKabutopsSprites53:
ax_sprite sKabutopsGfx53, 0x60
ax_sprite 0, 0x20
ax_sprite sKabutopsGfx53_1, 0x160
ax_sprite 0, 0x20
ax_sprite_terminator
sKabutopsGfx54:
.incbin "baserom.gba", 0xB177CC, 0xE0
sKabutopsGfx54_1:
.incbin "baserom.gba", 0xB178AC, 0x60
sKabutopsGfx54_2:
.incbin "baserom.gba", 0xB1790C, 0x60
sKabutopsSprites54:
ax_sprite 0, 0x20
ax_sprite sKabutopsGfx54, 0xe0
ax_sprite 0, 0x20
ax_sprite sKabutopsGfx54_1, 0x60
ax_sprite 0, 0x20
ax_sprite sKabutopsGfx54_2, 0x60
ax_sprite_terminator
sKabutopsGfx55:
.incbin "baserom.gba", 0xB179A4, 0x160
sKabutopsGfx55_1:
.incbin "baserom.gba", 0xB17B04, 0x60
sKabutopsSprites55:
ax_sprite 0, 0x20
ax_sprite sKabutopsGfx55, 0x160
ax_sprite 0, 0x20
ax_sprite sKabutopsGfx55_1, 0x60
ax_sprite_terminator
sKabutopsGfx56:
.incbin "baserom.gba", 0xB17B8C, 0x60
sKabutopsGfx56_1:
.incbin "baserom.gba", 0xB17BEC, 0x100
sKabutopsGfx56_2:
.incbin "baserom.gba", 0xB17CEC, 0x40
sKabutopsSprites56:
ax_sprite sKabutopsGfx56, 0x60
ax_sprite 0, 0x20
ax_sprite sKabutopsGfx56_1, 0x100
ax_sprite 0, 0x20
ax_sprite sKabutopsGfx56_2, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sKabutopsGfx57:
.incbin "baserom.gba", 0xB17D64, 0x40
sKabutopsGfx57_1:
.incbin "baserom.gba", 0xB17DA4, 0x100
sKabutopsGfx57_2:
.incbin "baserom.gba", 0xB17EA4, 0x40
sKabutopsSprites57:
ax_sprite 0, 0x20
ax_sprite sKabutopsGfx57, 0x40
ax_sprite 0, 0x20
ax_sprite sKabutopsGfx57_1, 0x100
ax_sprite 0, 0x20
ax_sprite sKabutopsGfx57_2, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sKabutopsGfx58:
.incbin "baserom.gba", 0xB17F24, 0x60
sKabutopsGfx58_1:
.incbin "baserom.gba", 0xB17F84, 0x100
sKabutopsGfx58_2:
.incbin "baserom.gba", 0xB18084, 0x40
sKabutopsSprites58:
ax_sprite sKabutopsGfx58, 0x60
ax_sprite 0, 0x20
ax_sprite sKabutopsGfx58_1, 0x100
ax_sprite 0, 0x20
ax_sprite sKabutopsGfx58_2, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sKabutopsGfx59:
.incbin "baserom.gba", 0xB180FC, 0x40
sKabutopsGfx59_1:
.incbin "baserom.gba", 0xB1813C, 0x180
sKabutopsSprites59:
ax_sprite 0, 0x20
ax_sprite sKabutopsGfx59, 0x40
ax_sprite 0, 0x20
ax_sprite sKabutopsGfx59_1, 0x180
ax_sprite_terminator
sKabutopsGfx60:
.incbin "baserom.gba", 0xB182E4, 0x200
sKabutopsSprites60:
ax_sprite sKabutopsGfx60, 0x200
ax_sprite_terminator
sKabutopsGfx61:
.incbin "baserom.gba", 0xB184F4, 0x200
sKabutopsSprites61:
ax_sprite sKabutopsGfx61, 0x200
ax_sprite_terminator
sKabutopsGfx62:
.incbin "baserom.gba", 0xB18704, 0x200
sKabutopsSprites62:
ax_sprite sKabutopsGfx62, 0x200
ax_sprite_terminator
sKabutopsGfx63:
.incbin "baserom.gba", 0xB18914, 0x200
sKabutopsSprites63:
ax_sprite sKabutopsGfx63, 0x200
ax_sprite_terminator
sKabutopsGfx64:
.incbin "baserom.gba", 0xB18B24, 0x200
sKabutopsSprites64:
ax_sprite sKabutopsGfx64, 0x200
ax_sprite_terminator
sKabutopsGfx65:
.incbin "baserom.gba", 0xB18D34, 0x200
sKabutopsSprites65:
ax_sprite sKabutopsGfx65, 0x200
ax_sprite_terminator
sKabutopsGfx66:
.incbin "baserom.gba", 0xB18F44, 0x200
sKabutopsSprites66:
ax_sprite sKabutopsGfx66, 0x200
ax_sprite_terminator
sAxPosesKabutops:
.4byte sKabutopsPose1
.4byte sKabutopsPose2
.4byte sKabutopsPose3
.4byte sKabutopsPose4
.4byte sKabutopsPose5
.4byte sKabutopsPose6
.4byte sKabutopsPose7
.4byte sKabutopsPose8
.4byte sKabutopsPose9
.4byte sKabutopsPose10
.4byte sKabutopsPose11
.4byte sKabutopsPose12
.4byte sKabutopsPose13
.4byte sKabutopsPose14
.4byte sKabutopsPose15
.4byte sKabutopsPose16
.4byte sKabutopsPose17
.4byte sKabutopsPose18
.4byte sKabutopsPose19
.4byte sKabutopsPose20
.4byte sKabutopsPose21
.4byte sKabutopsPose22
.4byte sKabutopsPose23
.4byte sKabutopsPose24
.4byte sKabutopsPose25
.4byte sKabutopsPose26
.4byte sKabutopsPose27
.4byte sKabutopsPose28
.4byte sKabutopsPose29
.4byte sKabutopsPose30
.4byte sKabutopsPose31
.4byte sKabutopsPose32
.4byte sKabutopsPose33
.4byte sKabutopsPose34
.4byte sKabutopsPose35
.4byte sKabutopsPose36
.4byte sKabutopsPose37
.4byte sKabutopsPose38
.4byte sKabutopsPose39
.4byte sKabutopsPose40
.4byte sKabutopsPose41
.4byte sKabutopsPose42
.4byte sKabutopsPose43
.4byte sKabutopsPose44
.4byte sKabutopsPose45
.4byte sKabutopsPose46
.4byte sKabutopsPose47
.4byte sKabutopsPose48
.4byte sKabutopsPose49
.4byte sKabutopsPose50
.4byte sKabutopsPose51
.4byte sKabutopsPose52
.4byte sKabutopsPose53
.4byte sKabutopsPose54
.4byte sKabutopsPose55
.4byte sKabutopsPose56
.4byte sKabutopsPose57
.4byte sKabutopsPose58
.4byte sKabutopsPose59
.4byte sKabutopsPose60
.4byte sKabutopsPose61
.4byte sKabutopsPose62
.4byte sKabutopsPose63
.4byte sKabutopsPose64
.4byte sKabutopsPose65
.4byte sKabutopsPose66
.4byte sKabutopsPose67
.4byte sKabutopsPose68
.4byte sKabutopsPose69
.4byte sKabutopsPose70
.4byte sKabutopsPose71
.4byte sKabutopsPose72
.4byte sKabutopsPose73
.4byte sKabutopsPose74
.4byte sKabutopsPose75
.4byte sKabutopsPose76
.4byte sKabutopsPose77
.4byte sKabutopsPose78
.4byte sKabutopsPose79
.4byte sKabutopsPose80
.4byte sKabutopsPose81
.4byte sKabutopsPose82
.4byte sKabutopsPose83
.4byte sKabutopsPose84
.4byte sKabutopsPose85
.4byte sKabutopsPose86
.4byte sKabutopsPose87
.4byte sKabutopsPose88
.4byte sKabutopsPose89
.4byte sKabutopsPose90
.4byte sKabutopsPose91
.4byte sKabutopsPose92
.4byte sKabutopsPose93
.4byte sKabutopsPose94
.4byte sKabutopsPose95
.4byte sKabutopsPose96
.4byte sKabutopsPose97
.4byte sKabutopsPose98
.4byte sKabutopsPose99
.4byte sKabutopsPose100
.4byte sKabutopsPose101
.4byte sKabutopsPose102
.4byte sKabutopsPose103
.4byte sKabutopsPose104
.4byte sKabutopsPose105
.4byte sKabutopsPose106
.4byte sKabutopsPose107
.4byte sKabutopsPose108
.4byte sKabutopsPose109
.4byte sKabutopsPose110
.4byte sKabutopsPose111
.4byte sKabutopsPose112
.4byte sKabutopsPose113
.4byte sKabutopsPose114
.4byte sKabutopsPose115
.4byte sKabutopsPose116
.4byte sKabutopsPose117
.4byte sKabutopsPose118
.4byte sKabutopsPose119
.4byte sKabutopsPose120
.4byte sKabutopsPose121
.4byte sKabutopsPose122
.4byte sKabutopsPose123
.4byte sKabutopsPose124
.4byte sKabutopsPose125
.4byte sKabutopsPose126
.4byte sKabutopsPose127
.4byte sKabutopsPose128
.4byte sKabutopsPose129
.4byte sKabutopsPose130
.4byte sKabutopsPose131
.4byte sKabutopsPose132
.4byte sKabutopsPose133
.4byte sKabutopsPose134
.4byte sKabutopsPose135
.4byte sKabutopsPose136
.4byte sKabutopsPose137
.4byte sKabutopsPose138
.4byte sKabutopsPose139
.4byte sKabutopsPose140
.4byte sKabutopsPose141
.4byte sKabutopsPose142
.4byte sKabutopsPose143
.4byte sKabutopsPose144
.4byte sKabutopsPose145
.4byte sKabutopsPose146
.4byte sKabutopsPose147
.4byte sKabutopsPose148
.4byte sKabutopsPose149
.4byte sKabutopsPose150
.4byte sKabutopsPose151
.4byte sKabutopsPose152
.4byte sKabutopsPose153
.4byte sKabutopsPose154
.4byte sKabutopsPose155
.4byte sKabutopsPose156
.4byte sKabutopsPose157
.4byte sKabutopsPose158
.4byte sKabutopsPose159
.4byte sKabutopsPose160
.4byte sKabutopsPose161
.4byte sKabutopsPose162
.4byte sKabutopsPose163
.4byte sKabutopsPose164
.4byte sKabutopsPose165
.4byte sKabutopsPose166
.4byte sKabutopsPose167
.4byte sKabutopsPose168
.4byte sKabutopsPose169
.4byte sKabutopsPose170
.4byte sKabutopsPose171
.4byte sKabutopsPose172
.4byte sKabutopsPose173
.4byte sKabutopsPose174
.4byte sKabutopsPose175
.4byte sKabutopsPose176
.4byte sKabutopsPose177
.4byte sKabutopsPose178
.4byte sKabutopsPose179
.4byte sKabutopsPose180
.4byte sKabutopsPose181
.4byte sKabutopsPose182
.4byte sKabutopsPose183
.4byte sKabutopsPose184
.4byte sKabutopsPose185
.4byte sKabutopsPose186
.4byte sKabutopsPose187
.4byte sKabutopsPose188
.4byte sKabutopsPose189
.4byte sKabutopsPose190
.4byte sKabutopsPose191
.4byte sKabutopsPose192
.4byte sKabutopsPose193
.4byte sKabutopsPose194
.4byte sKabutopsPose195
.4byte sKabutopsPose196
.4byte sKabutopsPose197
.4byte sKabutopsPose198
.4byte sKabutopsPose199
.4byte sKabutopsPose200
.4byte sKabutopsPose201
.4byte sKabutopsPose202
.4byte sKabutopsPose203
.4byte sKabutopsPose204
.4byte sKabutopsPose205
.4byte sKabutopsPose206
.4byte sKabutopsPose207
.4byte sKabutopsPose208
.4byte sKabutopsPose209
.4byte sKabutopsPose210
.4byte sKabutopsPose211
.4byte sKabutopsPose212
.4byte sKabutopsPose213
.4byte sKabutopsPose214
.4byte sKabutopsPose215
.4byte sKabutopsPose216
.4byte sKabutopsPose217
.4byte sKabutopsPose218
.4byte sKabutopsPose219
.4byte sKabutopsPose220
.4byte sKabutopsPose221
.4byte sKabutopsPose222
.4byte sKabutopsPose223
.4byte sKabutopsPose224
.4byte sKabutopsPose225
.4byte sKabutopsPose226
sAxPositionsKabutops:
.2byte    0,  -10, 	  -9,   -5, 	   9,   -5, 	   0,  -12
.2byte    1,   -9, 	  -8,    2, 	   8,   -7, 	   1,  -11
.2byte   -2,   -9, 	  -9,   -7, 	   7,    2, 	  -2,  -11
.2byte    7,  -11, 	  10,   -6, 	   1,   -1, 	   0,   -9
.2byte    4,  -11, 	  11,   -3, 	  -9,   -5, 	  -1,  -10
.2byte    7,  -14, 	  -2,   -9, 	   3,   -2, 	  -1,   -8
.2byte   10,  -14, 	   9,   -9, 	   6,   -1, 	  -3,  -10
.2byte    8,  -12, 	  12,   -7, 	   0,    1, 	  -1,  -10
.2byte   11,  -15, 	  -1,  -12, 	  12,    0, 	  -1,   -8
.2byte    9,  -18, 	  -2,   -8, 	   9,   -5, 	  -2,  -11
.2byte   11,  -14, 	   2,   -7, 	   4,    2, 	  -2,   -9
.2byte    3,  -18, 	  -9,   -7, 	  10,   -6, 	  -2,   -9
.2byte    0,  -16, 	   8,   -6, 	  -8,   -6, 	   0,  -10
.2byte    0,  -16, 	   8,   -2, 	 -12,  -12, 	  -1,   -9
.2byte   -1,  -16, 	  11,  -11, 	  -9,   -2, 	   0,   -9
.2byte  -10,  -18, 	   1,   -8, 	 -10,   -5, 	   1,  -11
.2byte  -12,  -14, 	  -3,   -7, 	  -5,    2, 	   1,   -9
.2byte   -4,  -18, 	   8,   -7, 	 -11,   -6, 	   1,   -9
.2byte  -11,  -14, 	 -10,   -9, 	  -7,   -1, 	   2,  -10
.2byte   -9,  -12, 	 -13,   -7, 	  -1,    1, 	   0,  -10
.2byte  -12,  -15, 	   0,  -12, 	 -13,    0, 	   0,   -8
.2byte   -8,  -11, 	 -11,   -6, 	  -2,   -1, 	  -1,   -9
.2byte   -5,  -11, 	 -12,   -3, 	   8,   -5, 	   0,  -10
.2byte   -8,  -14, 	   1,   -9, 	  -4,   -2, 	   0,   -8
.2byte    0,  -10, 	  -9,   -5, 	   9,   -5, 	   0,  -12
.2byte    1,   -9, 	  -8,    2, 	   8,   -7, 	   1,  -11
.2byte   -2,   -9, 	  -9,   -7, 	   7,    2, 	  -2,  -11
.2byte    7,  -11, 	  10,   -6, 	   1,   -1, 	   0,   -9
.2byte    4,  -11, 	  11,   -3, 	  -9,   -5, 	  -1,  -10
.2byte    7,  -14, 	  -2,   -9, 	   3,   -2, 	  -1,   -8
.2byte   10,  -14, 	   9,   -9, 	   6,   -1, 	  -3,  -10
.2byte    8,  -12, 	  12,   -7, 	   0,    1, 	  -1,  -10
.2byte   11,  -15, 	  -1,  -12, 	  12,    0, 	  -1,   -8
.2byte    9,  -18, 	  -2,   -8, 	   9,   -5, 	  -2,  -11
.2byte   11,  -14, 	   2,   -7, 	   4,    2, 	  -2,   -9
.2byte    3,  -18, 	  -9,   -7, 	  10,   -6, 	  -2,   -9
.2byte    0,  -16, 	   8,   -6, 	  -8,   -6, 	   0,  -10
.2byte    0,  -16, 	   8,   -2, 	 -12,  -12, 	  -1,   -9
.2byte   -1,  -16, 	  11,  -11, 	  -9,   -2, 	   0,   -9
.2byte  -10,  -18, 	   1,   -8, 	 -10,   -5, 	   1,  -11
.2byte  -12,  -14, 	  -3,   -7, 	  -5,    2, 	   1,   -9
.2byte   -4,  -18, 	   8,   -7, 	 -11,   -6, 	   1,   -9
.2byte  -11,  -14, 	 -10,   -9, 	  -7,   -1, 	   2,  -10
.2byte   -9,  -12, 	 -13,   -7, 	  -1,    1, 	   0,  -10
.2byte  -12,  -15, 	   0,  -12, 	 -13,    0, 	   0,   -8
.2byte   -8,  -11, 	 -11,   -6, 	  -2,   -1, 	  -1,   -9
.2byte   -5,  -11, 	 -12,   -3, 	   8,   -5, 	   0,  -10
.2byte   -8,  -14, 	   1,   -9, 	  -4,   -2, 	   0,   -8
.2byte    0,  -10, 	  -9,   -5, 	   9,   -5, 	   0,  -12
.2byte    1,   -8, 	 -10,   -1, 	   9,  -23, 	   0,   -9
.2byte    0,   -6, 	  -5,  -18, 	 -10,    0, 	   0,   -7
.2byte    0,   -6, 	  -5,  -18, 	 -10,    0, 	   0,   -7
.2byte   -2,   -8, 	 -10,  -23, 	   9,   -1, 	  -1,   -9
.2byte   -1,   -6, 	   9,    0, 	   4,  -18, 	  -1,   -7
.2byte   -1,   -6, 	   9,    0, 	   4,  -18, 	  -1,   -7
.2byte    7,  -11, 	  10,   -6, 	   1,   -1, 	   0,   -9
.2byte    6,   -9, 	  13,   -4, 	 -11,  -15, 	   0,  -10
.2byte    9,   -8, 	   3,  -20, 	  12,   -5, 	   1,   -8
.2byte    9,   -8, 	   3,  -20, 	  12,   -5, 	   1,   -8
.2byte    9,  -13, 	   7,  -22, 	  -1,   -1, 	  -2,   -9
.2byte    8,   -8, 	   0,    0, 	  -8,  -16, 	   0,   -8
.2byte    8,   -8, 	   0,    0, 	  -8,  -16, 	   0,   -8
.2byte   10,  -14, 	   9,   -9, 	   6,   -1, 	  -3,  -10
.2byte    8,  -11, 	  11,   -6, 	 -12,  -12, 	  -1,  -10
.2byte   11,  -13, 	  -5,  -21, 	   8,  -11, 	   0,   -9
.2byte   11,  -13, 	  -5,  -21, 	   8,  -11, 	   0,   -9
.2byte    8,  -17, 	  -4,  -24, 	   8,   -3, 	  -2,  -10
.2byte   11,  -13, 	   3,    2, 	 -11,   -8, 	  -1,   -9
.2byte   11,  -13, 	   3,    2, 	 -11,   -8, 	  -1,   -9
.2byte    9,  -18, 	  -2,   -8, 	   9,   -5, 	  -2,  -11
.2byte    4,  -13, 	   1,   -9, 	   6,  -20, 	  -3,  -10
.2byte    6,  -15, 	 -12,  -11, 	  -8,  -17, 	   0,  -10
.2byte    6,  -15, 	 -12,  -11, 	  -8,  -17, 	   0,  -10
.2byte    4,  -16, 	 -11,  -21, 	  10,   -4, 	  -3,  -11
.2byte    7,  -15, 	   9,   -5, 	  -5,   -7, 	   0,   -9
.2byte    7,  -15, 	   9,   -5, 	  -5,   -7, 	   0,   -9
.2byte    0,  -16, 	   8,   -6, 	  -8,   -6, 	   0,  -10
.2byte    2,  -16, 	  12,  -12, 	  -8,  -10, 	  -1,   -8
.2byte    0,  -15, 	 -11,   -8, 	  -8,   -8, 	   0,   -9
.2byte    0,  -15, 	 -11,   -8, 	  -8,   -8, 	   0,   -9
.2byte   -2,  -16, 	   9,   -9, 	 -12,  -13, 	   1,   -8
.2byte    0,  -17, 	   9,   -8, 	  12,   -7, 	   0,   -9
.2byte    0,  -17, 	   9,   -8, 	  12,   -7, 	   0,   -9
.2byte   -9,  -18, 	   2,   -8, 	  -9,   -5, 	   2,  -11
.2byte   -4,  -13, 	  -1,   -9, 	  -6,  -20, 	   3,  -10
.2byte   -6,  -15, 	  12,  -11, 	   8,  -17, 	   0,  -10
.2byte   -6,  -15, 	  12,  -11, 	   8,  -17, 	   0,  -10
.2byte   -4,  -16, 	  11,  -21, 	 -10,   -4, 	   3,  -11
.2byte   -7,  -15, 	  -9,   -5, 	   5,   -7, 	   0,   -9
.2byte   -7,  -15, 	  -9,   -5, 	   5,   -7, 	   0,   -9
.2byte  -10,  -14, 	  -9,   -9, 	  -6,   -1, 	   3,  -10
.2byte   -8,  -11, 	 -11,   -6, 	  12,  -12, 	   1,  -10
.2byte  -11,  -13, 	   5,  -21, 	  -8,  -11, 	   0,   -9
.2byte  -11,  -13, 	   5,  -21, 	  -8,  -11, 	   0,   -9
.2byte   -8,  -17, 	   4,  -24, 	  -8,   -3, 	   2,  -10
.2byte  -11,  -13, 	  -3,    2, 	  11,   -8, 	   1,   -9
.2byte  -11,  -13, 	  -3,    2, 	  11,   -8, 	   1,   -9
.2byte   -7,  -11, 	 -10,   -6, 	  -1,   -1, 	   0,   -9
.2byte   -6,   -9, 	 -13,   -4, 	  11,  -15, 	   0,  -10
.2byte   -9,   -8, 	  -3,  -20, 	 -12,   -5, 	  -1,   -8
.2byte   -9,   -8, 	  -3,  -20, 	 -12,   -5, 	  -1,   -8
.2byte   -9,  -13, 	  -7,  -22, 	   1,   -1, 	   2,   -9
.2byte   -8,   -8, 	   0,    0, 	   8,  -16, 	   0,   -8
.2byte   -8,   -8, 	   0,    0, 	   8,  -16, 	   0,   -8
.2byte    0,  -10, 	  -9,   -5, 	   9,   -5, 	   0,  -12
.2byte    0,   -8, 	 -15,  -17, 	  15,  -17, 	   0,   -7
.2byte    0,   -7, 	 -14,  -18, 	  14,  -18, 	   0,   -6
.2byte    7,  -11, 	  10,   -6, 	   1,   -1, 	   0,   -9
.2byte    7,  -10, 	   5,  -19, 	 -14,  -13, 	   0,   -9
.2byte    7,   -9, 	   2,  -19, 	 -13,  -13, 	   0,   -9
.2byte   10,  -14, 	   9,   -9, 	   6,   -1, 	  -3,  -10
.2byte   11,  -13, 	  -8,  -19, 	  -8,   -6, 	  -1,   -9
.2byte   11,  -12, 	 -11,  -17, 	  -9,   -6, 	  -1,   -9
.2byte    9,  -18, 	  -2,   -8, 	   9,   -5, 	  -2,  -11
.2byte   10,  -16, 	 -11,  -12, 	   3,   -4, 	   0,   -9
.2byte   11,  -15, 	 -12,  -10, 	   0,   -3, 	   0,   -8
.2byte    0,  -16, 	   8,   -6, 	  -8,   -6, 	   0,  -10
.2byte    0,  -16, 	  12,   -6, 	 -12,   -6, 	   0,   -8
.2byte    0,  -15, 	  11,   -4, 	 -11,   -4, 	   0,   -8
.2byte   -9,  -18, 	   2,   -8, 	  -9,   -5, 	   2,  -11
.2byte  -10,  -16, 	  11,  -12, 	  -3,   -4, 	   0,   -9
.2byte  -11,  -15, 	  12,  -10, 	   0,   -3, 	   0,   -8
.2byte  -10,  -14, 	  -9,   -9, 	  -6,   -1, 	   3,  -10
.2byte  -11,  -13, 	   8,  -19, 	   8,   -6, 	   1,   -9
.2byte  -11,  -12, 	  11,  -17, 	   9,   -6, 	   1,   -9
.2byte   -7,  -11, 	 -10,   -6, 	  -1,   -1, 	   0,   -9
.2byte   -7,  -10, 	  -5,  -19, 	  14,  -13, 	   0,   -9
.2byte   -7,   -9, 	  -2,  -19, 	  13,  -13, 	   0,   -9
.2byte    0,  -10, 	  -9,   -5, 	   9,   -5, 	   0,  -12
.2byte   -7,  -11, 	 -10,   -6, 	  -1,   -1, 	   0,   -9
.2byte  -10,  -14, 	  -9,   -9, 	  -6,   -1, 	   3,  -10
.2byte   -9,  -18, 	   2,   -8, 	  -9,   -5, 	   2,  -11
.2byte    0,  -16, 	   8,   -6, 	  -8,   -6, 	   0,  -10
.2byte    9,  -18, 	  -2,   -8, 	   9,   -5, 	  -2,  -11
.2byte   10,  -14, 	   9,   -9, 	   6,   -1, 	  -3,  -10
.2byte    7,  -11, 	  10,   -6, 	   1,   -1, 	   0,   -9
.2byte   -7,   -9, 	  -4,   -5, 	   7,   -1, 	  -1,   -8
.2byte   -7,   -7, 	  -3,   -4, 	   8,    0, 	  -1,   -7
.2byte    0,  -12, 	 -15,  -11, 	   7,   -6, 	   0,  -11
.2byte    7,  -15, 	  13,  -16, 	  -5,   -4, 	   1,  -11
.2byte    6,  -17, 	  10,  -21, 	   0,   -1, 	  -1,   -9
.2byte    3,  -18, 	 -10,  -11, 	  13,   -1, 	  -1,   -7
.2byte    0,  -18, 	  10,   -9, 	 -11,   -3, 	   0,   -8
.2byte   -4,  -18, 	   9,  -11, 	 -14,   -1, 	   0,   -7
.2byte   -7,  -17, 	 -11,  -21, 	  -1,   -1, 	   0,   -9
.2byte   -8,  -15, 	 -14,  -16, 	   4,   -4, 	  -2,  -11
.2byte    0,  -10, 	  -9,   -5, 	   9,   -5, 	   0,  -12
.2byte    1,   -9, 	  -8,    2, 	   8,   -7, 	   1,  -11
.2byte   -2,   -9, 	  -9,   -7, 	   7,    2, 	  -2,  -11
.2byte    7,  -11, 	  10,   -6, 	   1,   -1, 	   0,   -9
.2byte    4,  -11, 	  11,   -3, 	  -9,   -5, 	  -1,  -10
.2byte    7,  -14, 	  -2,   -9, 	   3,   -2, 	  -1,   -8
.2byte   10,  -14, 	   9,   -9, 	   6,   -1, 	  -3,  -10
.2byte    8,  -12, 	  12,   -7, 	   0,    1, 	  -1,  -10
.2byte   11,  -15, 	  -1,  -12, 	  12,    0, 	  -1,   -8
.2byte    9,  -18, 	  -2,   -8, 	   9,   -5, 	  -2,  -11
.2byte   11,  -14, 	   2,   -7, 	   4,    2, 	  -2,   -9
.2byte    3,  -18, 	  -9,   -7, 	  10,   -6, 	  -2,   -9
.2byte    0,  -16, 	   8,   -6, 	  -8,   -6, 	   0,  -10
.2byte    0,  -16, 	   8,   -2, 	 -12,  -12, 	  -1,   -9
.2byte   -1,  -16, 	  11,  -11, 	  -9,   -2, 	   0,   -9
.2byte  -10,  -18, 	   1,   -8, 	 -10,   -5, 	   1,  -11
.2byte  -12,  -14, 	  -3,   -7, 	  -5,    2, 	   1,   -9
.2byte   -4,  -18, 	   8,   -7, 	 -11,   -6, 	   1,   -9
.2byte  -11,  -14, 	 -10,   -9, 	  -7,   -1, 	   2,  -10
.2byte   -9,  -12, 	 -13,   -7, 	  -1,    1, 	   0,  -10
.2byte  -12,  -15, 	   0,  -12, 	 -13,    0, 	   0,   -8
.2byte   -8,  -11, 	 -11,   -6, 	  -2,   -1, 	  -1,   -9
.2byte   -5,  -11, 	 -12,   -3, 	   8,   -5, 	   0,  -10
.2byte   -8,  -14, 	   1,   -9, 	  -4,   -2, 	   0,   -8
.2byte    0,  -10, 	  -9,   -5, 	   9,   -5, 	   0,  -12
.2byte   -7,  -11, 	 -10,   -6, 	  -1,   -1, 	   0,   -9
.2byte  -10,  -14, 	  -9,   -9, 	  -6,   -1, 	   3,  -10
.2byte   -9,  -18, 	   2,   -8, 	  -9,   -5, 	   2,  -11
.2byte    0,  -16, 	   8,   -6, 	  -8,   -6, 	   0,  -10
.2byte    9,  -18, 	  -2,   -8, 	   9,   -5, 	  -2,  -11
.2byte   10,  -14, 	   9,   -9, 	   6,   -1, 	  -3,  -10
.2byte    7,  -11, 	  10,   -6, 	   1,   -1, 	   0,   -9
.2byte    0,  -10, 	  -9,   -5, 	   9,   -5, 	   0,  -12
.2byte    7,  -11, 	  10,   -6, 	   1,   -1, 	   0,   -9
.2byte   10,  -14, 	   9,   -9, 	   6,   -1, 	  -3,  -10
.2byte    9,  -18, 	  -2,   -8, 	   9,   -5, 	  -2,  -11
.2byte    0,  -16, 	   8,   -6, 	  -8,   -6, 	   0,  -10
.2byte   -9,  -18, 	   2,   -8, 	  -9,   -5, 	   2,  -11
.2byte  -10,  -14, 	  -9,   -9, 	  -6,   -1, 	   3,  -10
.2byte   -7,  -11, 	 -10,   -6, 	  -1,   -1, 	   0,   -9
.2byte    0,  -10, 	  -9,   -5, 	   9,   -5, 	   0,  -12
.2byte    0,   -8, 	 -15,  -17, 	  15,  -17, 	   0,   -7
.2byte    0,   -7, 	 -14,  -18, 	  14,  -18, 	   0,   -6
.2byte    7,  -11, 	  10,   -6, 	   1,   -1, 	   0,   -9
.2byte    7,  -10, 	   5,  -19, 	 -14,  -13, 	   0,   -9
.2byte    7,   -9, 	   2,  -19, 	 -13,  -13, 	   0,   -9
.2byte   10,  -14, 	   9,   -9, 	   6,   -1, 	  -3,  -10
.2byte   11,  -13, 	  -8,  -19, 	  -8,   -6, 	  -1,   -9
.2byte   11,  -12, 	 -11,  -17, 	  -9,   -6, 	  -1,   -9
.2byte    9,  -18, 	  -2,   -8, 	   9,   -5, 	  -2,  -11
.2byte   10,  -16, 	 -11,  -12, 	   3,   -4, 	   0,   -9
.2byte   11,  -15, 	 -12,  -10, 	   0,   -3, 	   0,   -8
.2byte    0,  -16, 	   8,   -6, 	  -8,   -6, 	   0,  -10
.2byte    0,  -16, 	  12,   -6, 	 -12,   -6, 	   0,   -8
.2byte    0,  -15, 	  11,   -4, 	 -11,   -4, 	   0,   -8
.2byte   -9,  -18, 	   2,   -8, 	  -9,   -5, 	   2,  -11
.2byte  -10,  -16, 	  11,  -12, 	  -3,   -4, 	   0,   -9
.2byte  -11,  -15, 	  12,  -10, 	   0,   -3, 	   0,   -8
.2byte  -10,  -14, 	  -9,   -9, 	  -6,   -1, 	   3,  -10
.2byte  -11,  -13, 	   8,  -19, 	   8,   -6, 	   1,   -9
.2byte  -11,  -12, 	  11,  -17, 	   9,   -6, 	   1,   -9
.2byte   -7,  -11, 	 -10,   -6, 	  -1,   -1, 	   0,   -9
.2byte   -7,  -10, 	  -5,  -19, 	  14,  -13, 	   0,   -9
.2byte   -7,   -9, 	  -2,  -19, 	  13,  -13, 	   0,   -9
.2byte    0,   -7, 	 -14,  -18, 	  14,  -18, 	   0,   -6
.2byte   -7,   -9, 	  -2,  -19, 	  13,  -13, 	   0,   -9
.2byte  -11,  -12, 	  11,  -17, 	   9,   -6, 	   1,   -9
.2byte  -11,  -15, 	  12,  -10, 	   0,   -3, 	   0,   -8
.2byte    0,  -15, 	  11,   -4, 	 -11,   -4, 	   0,   -8
.2byte   11,  -15, 	 -12,  -10, 	   0,   -3, 	   0,   -8
.2byte   11,  -12, 	 -11,  -17, 	  -9,   -6, 	  -1,   -9
.2byte    7,   -9, 	   2,  -19, 	 -13,  -13, 	   0,   -9
.2byte    0,  -10, 	  -9,   -5, 	   9,   -5, 	   0,  -12
.2byte   -7,  -11, 	 -10,   -6, 	  -1,   -1, 	   0,   -9
.2byte  -10,  -14, 	  -9,   -9, 	  -6,   -1, 	   3,  -10
.2byte   -9,  -18, 	   2,   -8, 	  -9,   -5, 	   2,  -11
.2byte    0,  -16, 	   8,   -6, 	  -8,   -6, 	   0,  -10
.2byte    9,  -18, 	  -2,   -8, 	   9,   -5, 	  -2,  -11
.2byte   10,  -14, 	   9,   -9, 	   6,   -1, 	  -3,  -10
.2byte    7,  -11, 	  10,   -6, 	   1,   -1, 	   0,   -9
sKabutopsAnimTable1:
.4byte sKabutopsAnims_1_1
.4byte sKabutopsAnims_1_2
.4byte sKabutopsAnims_1_3
.4byte sKabutopsAnims_1_4
.4byte sKabutopsAnims_1_5
.4byte sKabutopsAnims_1_6
.4byte sKabutopsAnims_1_7
.4byte sKabutopsAnims_1_8
sKabutopsAnimTable2:
.4byte sKabutopsAnims_2_1
.4byte sKabutopsAnims_2_2
.4byte sKabutopsAnims_2_3
.4byte sKabutopsAnims_2_4
.4byte sKabutopsAnims_2_5
.4byte sKabutopsAnims_2_6
.4byte sKabutopsAnims_2_7
.4byte sKabutopsAnims_2_8
sKabutopsAnimTable3:
.4byte sKabutopsAnims_3_1
.4byte sKabutopsAnims_3_2
.4byte sKabutopsAnims_3_3
.4byte sKabutopsAnims_3_4
.4byte sKabutopsAnims_3_5
.4byte sKabutopsAnims_3_6
.4byte sKabutopsAnims_3_7
.4byte sKabutopsAnims_3_8
sKabutopsAnimTable4:
.4byte sKabutopsAnims_4_1
.4byte sKabutopsAnims_4_2
.4byte sKabutopsAnims_4_3
.4byte sKabutopsAnims_4_4
.4byte sKabutopsAnims_4_5
.4byte sKabutopsAnims_4_6
.4byte sKabutopsAnims_4_7
.4byte sKabutopsAnims_4_8
sKabutopsAnimTable5:
.4byte sKabutopsAnims_5_1
.4byte sKabutopsAnims_5_2
.4byte sKabutopsAnims_5_3
.4byte sKabutopsAnims_5_4
.4byte sKabutopsAnims_5_5
.4byte sKabutopsAnims_5_6
.4byte sKabutopsAnims_5_7
.4byte sKabutopsAnims_5_8
sKabutopsAnimTable6:
.4byte sKabutopsAnims_6_1
.4byte sKabutopsAnims_6_1
.4byte sKabutopsAnims_6_1
.4byte sKabutopsAnims_6_1
.4byte sKabutopsAnims_6_1
.4byte sKabutopsAnims_6_1
.4byte sKabutopsAnims_6_1
.4byte sKabutopsAnims_6_1
sKabutopsAnimTable7:
.4byte sKabutopsAnims_7_1
.4byte sKabutopsAnims_7_2
.4byte sKabutopsAnims_7_3
.4byte sKabutopsAnims_7_4
.4byte sKabutopsAnims_7_5
.4byte sKabutopsAnims_7_6
.4byte sKabutopsAnims_7_7
.4byte sKabutopsAnims_7_8
sKabutopsAnimTable8:
.4byte sKabutopsAnims_8_1
.4byte sKabutopsAnims_8_2
.4byte sKabutopsAnims_8_3
.4byte sKabutopsAnims_8_4
.4byte sKabutopsAnims_8_5
.4byte sKabutopsAnims_8_6
.4byte sKabutopsAnims_8_7
.4byte sKabutopsAnims_8_8
sKabutopsAnimTable9:
.4byte sKabutopsAnims_9_1
.4byte sKabutopsAnims_9_2
.4byte sKabutopsAnims_9_3
.4byte sKabutopsAnims_9_4
.4byte sKabutopsAnims_9_5
.4byte sKabutopsAnims_9_6
.4byte sKabutopsAnims_9_7
.4byte sKabutopsAnims_9_8
sKabutopsAnimTable10:
.4byte sKabutopsAnims_10_1
.4byte sKabutopsAnims_10_2
.4byte sKabutopsAnims_10_3
.4byte sKabutopsAnims_10_4
.4byte sKabutopsAnims_10_5
.4byte sKabutopsAnims_10_6
.4byte sKabutopsAnims_10_7
.4byte sKabutopsAnims_10_8
sKabutopsAnimTable11:
.4byte sKabutopsAnims_11_1
.4byte sKabutopsAnims_11_2
.4byte sKabutopsAnims_11_3
.4byte sKabutopsAnims_11_4
.4byte sKabutopsAnims_11_5
.4byte sKabutopsAnims_11_6
.4byte sKabutopsAnims_11_7
.4byte sKabutopsAnims_11_8
sKabutopsAnimTable12:
.4byte sKabutopsAnims_12_1
.4byte sKabutopsAnims_12_2
.4byte sKabutopsAnims_12_3
.4byte sKabutopsAnims_12_4
.4byte sKabutopsAnims_12_5
.4byte sKabutopsAnims_12_6
.4byte sKabutopsAnims_12_7
.4byte sKabutopsAnims_12_8
sKabutopsAnimTable13:
.4byte sKabutopsAnims_13_1
.4byte sKabutopsAnims_13_2
.4byte sKabutopsAnims_13_3
.4byte sKabutopsAnims_13_4
.4byte sKabutopsAnims_13_5
.4byte sKabutopsAnims_13_6
.4byte sKabutopsAnims_13_7
.4byte sKabutopsAnims_13_8
sAxAnimationsKabutops:
.4byte sKabutopsAnimTable1
.4byte sKabutopsAnimTable2
.4byte sKabutopsAnimTable3
.4byte sKabutopsAnimTable4
.4byte sKabutopsAnimTable5
.4byte sKabutopsAnimTable6
.4byte sKabutopsAnimTable7
.4byte sKabutopsAnimTable8
.4byte sKabutopsAnimTable9
.4byte sKabutopsAnimTable10
.4byte sKabutopsAnimTable11
.4byte sKabutopsAnimTable12
.4byte sKabutopsAnimTable13
sAxSpritesKabutops:
.4byte sKabutopsSprites1
.4byte sKabutopsSprites2
.4byte sKabutopsSprites3
.4byte sKabutopsSprites4
.4byte sKabutopsSprites5
.4byte sKabutopsSprites6
.4byte sKabutopsSprites7
.4byte sKabutopsSprites8
.4byte sKabutopsSprites9
.4byte sKabutopsSprites10
.4byte sKabutopsSprites11
.4byte sKabutopsSprites12
.4byte sKabutopsSprites13
.4byte sKabutopsSprites14
.4byte sKabutopsSprites15
.4byte sKabutopsSprites16
.4byte sKabutopsSprites17
.4byte sKabutopsSprites18
.4byte sKabutopsSprites19
.4byte sKabutopsSprites20
.4byte sKabutopsSprites21
.4byte sKabutopsSprites22
.4byte sKabutopsSprites23
.4byte sKabutopsSprites24
.4byte sKabutopsSprites25
.4byte sKabutopsSprites26
.4byte sKabutopsSprites27
.4byte sKabutopsSprites28
.4byte sKabutopsSprites29
.4byte sKabutopsSprites30
.4byte sKabutopsSprites31
.4byte sKabutopsSprites32
.4byte sKabutopsSprites33
.4byte sKabutopsSprites34
.4byte sKabutopsSprites35
.4byte sKabutopsSprites36
.4byte sKabutopsSprites37
.4byte sKabutopsSprites38
.4byte sKabutopsSprites39
.4byte sKabutopsSprites40
.4byte sKabutopsSprites41
.4byte sKabutopsSprites42
.4byte sKabutopsSprites43
.4byte sKabutopsSprites44
.4byte sKabutopsSprites45
.4byte sKabutopsSprites46
.4byte sKabutopsSprites47
.4byte sKabutopsSprites48
.4byte sKabutopsSprites49
.4byte sKabutopsSprites50
.4byte sKabutopsSprites51
.4byte sKabutopsSprites52
.4byte sKabutopsSprites53
.4byte sKabutopsSprites54
.4byte sKabutopsSprites55
.4byte sKabutopsSprites56
.4byte sKabutopsSprites57
.4byte sKabutopsSprites58
.4byte sKabutopsSprites59
.4byte sKabutopsSprites60
.4byte sKabutopsSprites61
.4byte sKabutopsSprites62
.4byte sKabutopsSprites63
.4byte sKabutopsSprites64
.4byte sKabutopsSprites65
.4byte sKabutopsSprites66
sAxMainKabutops:
ax_main sAxPosesKabutops, sAxAnimationsKabutops, 13, sAxSpritesKabutops, sAxPositionsKabutops
