.global gAxLanturn
gAxLanturn:
ax_siro sAxMainLanturn
sLanturnPose1:
ax_pose 0, 0x01e6, 0x80f0, 0x0c00
ax_pose_terminator
sLanturnPose2:
ax_pose 1, 0x01e6, 0x80f3, 0x0c00
ax_pose_terminator
sLanturnPose3:
ax_pose 2, 0x01e6, 0x80f4, 0x0c00
ax_pose_terminator
sLanturnPose4:
ax_pose 3, 0x01e8, 0x90ef, 0x0c00
ax_pose_terminator
sLanturnPose5:
ax_pose 4, 0x01e8, 0x90ef, 0x0c00
ax_pose_terminator
sLanturnPose6:
ax_pose 5, 0x01e8, 0x90ed, 0x0c00
ax_pose_terminator
sLanturnPose7:
ax_pose 6, 0x01ee, 0x90ef, 0x0c00
ax_pose_terminator
sLanturnPose8:
ax_pose 7, 0x01ee, 0x90ef, 0x0c00
ax_pose_terminator
sLanturnPose9:
ax_pose 8, 0x01ef, 0x90ef, 0x0c00
ax_pose_terminator
sLanturnPose10:
ax_pose 9, 0x01e6, 0x90ec, 0x0c00
ax_pose_terminator
sLanturnPose11:
ax_pose 10, 0x01e6, 0x90ec, 0x0c00
ax_pose_terminator
sLanturnPose12:
ax_pose 11, 0x01e6, 0x90ec, 0x0c00
ax_pose_terminator
sLanturnPose13:
ax_pose 12, 0x01e6, 0x80f0, 0x0c00
ax_pose_terminator
sLanturnPose14:
ax_pose 13, 0x01e6, 0x80f4, 0x0c00
ax_pose_terminator
sLanturnPose15:
ax_pose 14, 0x01e6, 0x80f3, 0x0c00
ax_pose_terminator
sLanturnPose16:
ax_pose 9, 0x01e6, 0x80f3, 0x0c00
ax_pose_terminator
sLanturnPose17:
ax_pose 10, 0x01e6, 0x80f3, 0x0c00
ax_pose_terminator
sLanturnPose18:
ax_pose 11, 0x01e6, 0x80f3, 0x0c00
ax_pose_terminator
sLanturnPose19:
ax_pose 6, 0x01ee, 0x80f0, 0x0c00
ax_pose_terminator
sLanturnPose20:
ax_pose 7, 0x01ee, 0x80f0, 0x0c00
ax_pose_terminator
sLanturnPose21:
ax_pose 8, 0x01ef, 0x80f0, 0x0c00
ax_pose_terminator
sLanturnPose22:
ax_pose 3, 0x01e8, 0x80f0, 0x0c00
ax_pose_terminator
sLanturnPose23:
ax_pose 4, 0x01e8, 0x80f0, 0x0c00
ax_pose_terminator
sLanturnPose24:
ax_pose 5, 0x01e8, 0x80f2, 0x0c00
ax_pose_terminator
sLanturnPose25:
ax_pose 0, 0x01e6, 0x80f0, 0x0c00
ax_pose_terminator
sLanturnPose26:
ax_pose 1, 0x01e6, 0x80f3, 0x0c00
ax_pose_terminator
sLanturnPose27:
ax_pose 2, 0x01e6, 0x80f4, 0x0c00
ax_pose_terminator
sLanturnPose28:
ax_pose 15, 0x01eb, 0x80f0, 0x0c00
ax_pose_terminator
sLanturnPose29:
ax_pose 3, 0x01e8, 0x90ef, 0x0c00
ax_pose_terminator
sLanturnPose30:
ax_pose 4, 0x01e8, 0x90ef, 0x0c00
ax_pose_terminator
sLanturnPose31:
ax_pose 5, 0x01e8, 0x90ed, 0x0c00
ax_pose_terminator
sLanturnPose32:
ax_pose 16, 0x01ea, 0x90ee, 0x0c00
ax_pose_terminator
sLanturnPose33:
ax_pose 6, 0x01ee, 0x90ef, 0x0c00
ax_pose_terminator
sLanturnPose34:
ax_pose 7, 0x01ee, 0x90ef, 0x0c00
ax_pose_terminator
sLanturnPose35:
ax_pose 8, 0x01ef, 0x90ef, 0x0c00
ax_pose_terminator
sLanturnPose36:
ax_pose 17, 0x01e8, 0x90f0, 0x0c00
ax_pose_terminator
sLanturnPose37:
ax_pose 9, 0x01e6, 0x90ec, 0x0c00
ax_pose_terminator
sLanturnPose38:
ax_pose 10, 0x01e6, 0x90ec, 0x0c00
ax_pose_terminator
sLanturnPose39:
ax_pose 11, 0x01e6, 0x90ec, 0x0c00
ax_pose_terminator
sLanturnPose40:
ax_pose 18, 0x01e9, 0x90ee, 0x0c00
ax_pose_terminator
sLanturnPose41:
ax_pose 12, 0x01e6, 0x80f0, 0x0c00
ax_pose_terminator
sLanturnPose42:
ax_pose 13, 0x01e6, 0x80f4, 0x0c00
ax_pose_terminator
sLanturnPose43:
ax_pose 14, 0x01e6, 0x80f3, 0x0c00
ax_pose_terminator
sLanturnPose44:
ax_pose 19, 0x01e6, 0x80f0, 0x0c00
ax_pose_terminator
sLanturnPose45:
ax_pose 9, 0x01e6, 0x80f3, 0x0c00
ax_pose_terminator
sLanturnPose46:
ax_pose 10, 0x01e6, 0x80f3, 0x0c00
ax_pose_terminator
sLanturnPose47:
ax_pose 11, 0x01e6, 0x80f3, 0x0c00
ax_pose_terminator
sLanturnPose48:
ax_pose 18, 0x01e7, 0x80f2, 0x0c00
ax_pose_terminator
sLanturnPose49:
ax_pose 6, 0x01ee, 0x80f0, 0x0c00
ax_pose_terminator
sLanturnPose50:
ax_pose 7, 0x01ee, 0x80f0, 0x0c00
ax_pose_terminator
sLanturnPose51:
ax_pose 8, 0x01ef, 0x80f0, 0x0c00
ax_pose_terminator
sLanturnPose52:
ax_pose 17, 0x01e8, 0x80f0, 0x0c00
ax_pose_terminator
sLanturnPose53:
ax_pose 3, 0x01e8, 0x80f0, 0x0c00
ax_pose_terminator
sLanturnPose54:
ax_pose 4, 0x01e8, 0x80f0, 0x0c00
ax_pose_terminator
sLanturnPose55:
ax_pose 5, 0x01e8, 0x80f2, 0x0c00
ax_pose_terminator
sLanturnPose56:
ax_pose 16, 0x01ea, 0x80f1, 0x0c00
ax_pose_terminator
sLanturnPose57:
ax_pose 0, 0x01e6, 0x80f0, 0x0c00
ax_pose_terminator
sLanturnPose58:
ax_pose 1, 0x01e6, 0x80f3, 0x0c00
ax_pose_terminator
sLanturnPose59:
ax_pose 2, 0x01e6, 0x80f4, 0x0c00
ax_pose_terminator
sLanturnPose60:
ax_pose 15, 0x01eb, 0x80f0, 0x0c00
ax_pose_terminator
sLanturnPose61:
ax_pose 3, 0x01e8, 0x90ef, 0x0c00
ax_pose_terminator
sLanturnPose62:
ax_pose 4, 0x01e8, 0x90ef, 0x0c00
ax_pose_terminator
sLanturnPose63:
ax_pose 5, 0x01e8, 0x90ed, 0x0c00
ax_pose_terminator
sLanturnPose64:
ax_pose 16, 0x01ea, 0x90ee, 0x0c00
ax_pose_terminator
sLanturnPose65:
ax_pose 6, 0x01ee, 0x90ef, 0x0c00
ax_pose_terminator
sLanturnPose66:
ax_pose 7, 0x01ee, 0x90ef, 0x0c00
ax_pose_terminator
sLanturnPose67:
ax_pose 8, 0x01ef, 0x90ef, 0x0c00
ax_pose_terminator
sLanturnPose68:
ax_pose 17, 0x01e8, 0x90f0, 0x0c00
ax_pose_terminator
sLanturnPose69:
ax_pose 9, 0x01e6, 0x90ec, 0x0c00
ax_pose_terminator
sLanturnPose70:
ax_pose 10, 0x01e6, 0x90ec, 0x0c00
ax_pose_terminator
sLanturnPose71:
ax_pose 11, 0x01e6, 0x90ec, 0x0c00
ax_pose_terminator
sLanturnPose72:
ax_pose 18, 0x01e9, 0x90ee, 0x0c00
ax_pose_terminator
sLanturnPose73:
ax_pose 12, 0x01e6, 0x80f0, 0x0c00
ax_pose_terminator
sLanturnPose74:
ax_pose 13, 0x01e6, 0x80f4, 0x0c00
ax_pose_terminator
sLanturnPose75:
ax_pose 14, 0x01e6, 0x80f3, 0x0c00
ax_pose_terminator
sLanturnPose76:
ax_pose 19, 0x01e6, 0x80f0, 0x0c00
ax_pose_terminator
sLanturnPose77:
ax_pose 9, 0x01e6, 0x80f3, 0x0c00
ax_pose_terminator
sLanturnPose78:
ax_pose 10, 0x01e6, 0x80f3, 0x0c00
ax_pose_terminator
sLanturnPose79:
ax_pose 11, 0x01e6, 0x80f3, 0x0c00
ax_pose_terminator
sLanturnPose80:
ax_pose 18, 0x01e7, 0x80f2, 0x0c00
ax_pose_terminator
sLanturnPose81:
ax_pose 6, 0x01ee, 0x80f0, 0x0c00
ax_pose_terminator
sLanturnPose82:
ax_pose 7, 0x01ee, 0x80f0, 0x0c00
ax_pose_terminator
sLanturnPose83:
ax_pose 8, 0x01ef, 0x80f0, 0x0c00
ax_pose_terminator
sLanturnPose84:
ax_pose 17, 0x01e8, 0x80f0, 0x0c00
ax_pose_terminator
sLanturnPose85:
ax_pose 3, 0x01e8, 0x80f0, 0x0c00
ax_pose_terminator
sLanturnPose86:
ax_pose 4, 0x01e8, 0x80f0, 0x0c00
ax_pose_terminator
sLanturnPose87:
ax_pose 5, 0x01e8, 0x80f2, 0x0c00
ax_pose_terminator
sLanturnPose88:
ax_pose 16, 0x01ea, 0x80f1, 0x0c00
ax_pose_terminator
sLanturnPose89:
ax_pose 0, 0x01e6, 0x80f0, 0x0c00
ax_pose_terminator
sLanturnPose90:
ax_pose 1, 0x01e6, 0x80f3, 0x0c00
ax_pose_terminator
sLanturnPose91:
ax_pose 2, 0x01e6, 0x80f4, 0x0c00
ax_pose_terminator
sLanturnPose92:
ax_pose 20, 0x01e6, 0x80f0, 0x0c00
ax_pose_terminator
sLanturnPose93:
ax_pose 15, 0x01e8, 0x80f0, 0x0c00
ax_pose_terminator
sLanturnPose94:
ax_pose 3, 0x01e8, 0x90ef, 0x0c00
ax_pose_terminator
sLanturnPose95:
ax_pose 4, 0x01e8, 0x90ef, 0x0c00
ax_pose_terminator
sLanturnPose96:
ax_pose 5, 0x01e8, 0x90ed, 0x0c00
ax_pose_terminator
sLanturnPose97:
ax_pose 21, 0x01e8, 0x90ef, 0x0c00
ax_pose_terminator
sLanturnPose98:
ax_pose 16, 0x01ea, 0x90ef, 0x0c00
ax_pose_terminator
sLanturnPose99:
ax_pose 6, 0x01ee, 0x90ef, 0x0c00
ax_pose_terminator
sLanturnPose100:
ax_pose 7, 0x01ee, 0x90ef, 0x0c00
ax_pose_terminator
sLanturnPose101:
ax_pose 8, 0x01ef, 0x90ef, 0x0c00
ax_pose_terminator
sLanturnPose102:
ax_pose 22, 0x01e7, 0x90ee, 0x0c00
ax_pose_terminator
sLanturnPose103:
ax_pose 17, 0x01e9, 0x90ef, 0x0c00
ax_pose_terminator
sLanturnPose104:
ax_pose 9, 0x01e6, 0x90ec, 0x0c00
ax_pose_terminator
sLanturnPose105:
ax_pose 10, 0x01e6, 0x90ec, 0x0c00
ax_pose_terminator
sLanturnPose106:
ax_pose 11, 0x01e6, 0x90ec, 0x0c00
ax_pose_terminator
sLanturnPose107:
ax_pose 23, 0x01e7, 0x90ed, 0x0c00
ax_pose_terminator
sLanturnPose108:
ax_pose 18, 0x01e8, 0x90ef, 0x0c00
ax_pose_terminator
sLanturnPose109:
ax_pose 12, 0x01e6, 0x80f0, 0x0c00
ax_pose_terminator
sLanturnPose110:
ax_pose 13, 0x01e6, 0x80f4, 0x0c00
ax_pose_terminator
sLanturnPose111:
ax_pose 14, 0x01e6, 0x80f3, 0x0c00
ax_pose_terminator
sLanturnPose112:
ax_pose 24, 0x01e6, 0x80f0, 0x0c00
ax_pose_terminator
sLanturnPose113:
ax_pose 19, 0x01e7, 0x80f0, 0x0c00
ax_pose_terminator
sLanturnPose114:
ax_pose 9, 0x01e6, 0x80f3, 0x0c00
ax_pose_terminator
sLanturnPose115:
ax_pose 10, 0x01e6, 0x80f3, 0x0c00
ax_pose_terminator
sLanturnPose116:
ax_pose 11, 0x01e6, 0x80f3, 0x0c00
ax_pose_terminator
sLanturnPose117:
ax_pose 23, 0x01e7, 0x80f3, 0x0c00
ax_pose_terminator
sLanturnPose118:
ax_pose 18, 0x01e8, 0x80f1, 0x0c00
ax_pose_terminator
sLanturnPose119:
ax_pose 6, 0x01ee, 0x80f0, 0x0c00
ax_pose_terminator
sLanturnPose120:
ax_pose 7, 0x01ee, 0x80f0, 0x0c00
ax_pose_terminator
sLanturnPose121:
ax_pose 8, 0x01ef, 0x80f0, 0x0c00
ax_pose_terminator
sLanturnPose122:
ax_pose 22, 0x01e7, 0x80f1, 0x0c00
ax_pose_terminator
sLanturnPose123:
ax_pose 17, 0x01e9, 0x80f0, 0x0c00
ax_pose_terminator
sLanturnPose124:
ax_pose 3, 0x01e8, 0x80f0, 0x0c00
ax_pose_terminator
sLanturnPose125:
ax_pose 4, 0x01e8, 0x80f0, 0x0c00
ax_pose_terminator
sLanturnPose126:
ax_pose 5, 0x01e8, 0x80f2, 0x0c00
ax_pose_terminator
sLanturnPose127:
ax_pose 21, 0x01e8, 0x80f1, 0x0c00
ax_pose_terminator
sLanturnPose128:
ax_pose 16, 0x01ea, 0x80f1, 0x0c00
ax_pose_terminator
sLanturnPose129:
ax_pose 0, 0x01e6, 0x80f0, 0x0c00
ax_pose_terminator
sLanturnPose130:
ax_pose 3, 0x01e8, 0x80f0, 0x0c00
ax_pose_terminator
sLanturnPose131:
ax_pose 6, 0x01ee, 0x80f0, 0x0c00
ax_pose_terminator
sLanturnPose132:
ax_pose 9, 0x01e6, 0x80f3, 0x0c00
ax_pose_terminator
sLanturnPose133:
ax_pose 12, 0x01e6, 0x80f0, 0x0c00
ax_pose_terminator
sLanturnPose134:
ax_pose 9, 0x01e6, 0x90ec, 0x0c00
ax_pose_terminator
sLanturnPose135:
ax_pose 6, 0x01ee, 0x90ef, 0x0c00
ax_pose_terminator
sLanturnPose136:
ax_pose 3, 0x01e8, 0x90ef, 0x0c00
ax_pose_terminator
sLanturnPose137:
ax_pose 25, 0x01e9, 0x80f3, 0x0c00
ax_pose_terminator
sLanturnPose138:
ax_pose 26, 0x01e9, 0x80f3, 0x0c00
ax_pose_terminator
sLanturnPose139:
ax_pose 27, 0x01e2, 0x80f1, 0x0c00
ax_pose_terminator
sLanturnPose140:
ax_pose 28, 0x01e2, 0x90ee, 0x0c00
ax_pose_terminator
sLanturnPose141:
ax_pose 29, 0x01e3, 0x90ee, 0x0c00
ax_pose_terminator
sLanturnPose142:
ax_pose 30, 0x01e5, 0x90ee, 0x0c00
ax_pose_terminator
sLanturnPose143:
ax_pose 31, 0x01e3, 0x80f1, 0x0c00
ax_pose_terminator
sLanturnPose144:
ax_pose 30, 0x01e5, 0x80f2, 0x0c00
ax_pose_terminator
sLanturnPose145:
ax_pose 29, 0x01e3, 0x80f2, 0x0c00
ax_pose_terminator
sLanturnPose146:
ax_pose 28, 0x01e2, 0x80f2, 0x0c00
ax_pose_terminator
sLanturnPose147:
ax_pose 0, 0x01e6, 0x80f0, 0x0c00
ax_pose_terminator
sLanturnPose148:
ax_pose 1, 0x01e6, 0x80f3, 0x0c00
ax_pose_terminator
sLanturnPose149:
ax_pose 2, 0x01e6, 0x80f4, 0x0c00
ax_pose_terminator
sLanturnPose150:
ax_pose 3, 0x01e8, 0x90ef, 0x0c00
ax_pose_terminator
sLanturnPose151:
ax_pose 4, 0x01e8, 0x90ef, 0x0c00
ax_pose_terminator
sLanturnPose152:
ax_pose 5, 0x01e8, 0x90ed, 0x0c00
ax_pose_terminator
sLanturnPose153:
ax_pose 6, 0x01ee, 0x90ef, 0x0c00
ax_pose_terminator
sLanturnPose154:
ax_pose 7, 0x01ee, 0x90ef, 0x0c00
ax_pose_terminator
sLanturnPose155:
ax_pose 8, 0x01ef, 0x90ef, 0x0c00
ax_pose_terminator
sLanturnPose156:
ax_pose 9, 0x01e6, 0x90ec, 0x0c00
ax_pose_terminator
sLanturnPose157:
ax_pose 10, 0x01e6, 0x90ec, 0x0c00
ax_pose_terminator
sLanturnPose158:
ax_pose 11, 0x01e6, 0x90ec, 0x0c00
ax_pose_terminator
sLanturnPose159:
ax_pose 12, 0x01e6, 0x80f0, 0x0c00
ax_pose_terminator
sLanturnPose160:
ax_pose 13, 0x01e6, 0x80f4, 0x0c00
ax_pose_terminator
sLanturnPose161:
ax_pose 14, 0x01e6, 0x80f3, 0x0c00
ax_pose_terminator
sLanturnPose162:
ax_pose 9, 0x01e6, 0x80f3, 0x0c00
ax_pose_terminator
sLanturnPose163:
ax_pose 10, 0x01e6, 0x80f3, 0x0c00
ax_pose_terminator
sLanturnPose164:
ax_pose 11, 0x01e6, 0x80f3, 0x0c00
ax_pose_terminator
sLanturnPose165:
ax_pose 6, 0x01ee, 0x80f0, 0x0c00
ax_pose_terminator
sLanturnPose166:
ax_pose 7, 0x01ee, 0x80f0, 0x0c00
ax_pose_terminator
sLanturnPose167:
ax_pose 8, 0x01ef, 0x80f0, 0x0c00
ax_pose_terminator
sLanturnPose168:
ax_pose 3, 0x01e8, 0x80f0, 0x0c00
ax_pose_terminator
sLanturnPose169:
ax_pose 4, 0x01e8, 0x80f0, 0x0c00
ax_pose_terminator
sLanturnPose170:
ax_pose 5, 0x01e8, 0x80f2, 0x0c00
ax_pose_terminator
sLanturnPose171:
ax_pose 0, 0x01e6, 0x80f0, 0x0c00
ax_pose_terminator
sLanturnPose172:
ax_pose 3, 0x01e8, 0x80f0, 0x0c00
ax_pose_terminator
sLanturnPose173:
ax_pose 6, 0x01ee, 0x80f0, 0x0c00
ax_pose_terminator
sLanturnPose174:
ax_pose 9, 0x01e6, 0x80f3, 0x0c00
ax_pose_terminator
sLanturnPose175:
ax_pose 12, 0x01e6, 0x80f0, 0x0c00
ax_pose_terminator
sLanturnPose176:
ax_pose 9, 0x01e6, 0x90ec, 0x0c00
ax_pose_terminator
sLanturnPose177:
ax_pose 6, 0x01ee, 0x90ef, 0x0c00
ax_pose_terminator
sLanturnPose178:
ax_pose 3, 0x01e8, 0x90ef, 0x0c00
ax_pose_terminator
sLanturnPose179:
ax_pose 20, 0x01e7, 0x80f0, 0x0c00
ax_pose_terminator
sLanturnPose180:
ax_pose 21, 0x01e7, 0x90ef, 0x0c00
ax_pose_terminator
sLanturnPose181:
ax_pose 22, 0x01e7, 0x90ef, 0x0c00
ax_pose_terminator
sLanturnPose182:
ax_pose 23, 0x01e7, 0x90ed, 0x0c00
ax_pose_terminator
sLanturnPose183:
ax_pose 24, 0x01e7, 0x80f0, 0x0c00
ax_pose_terminator
sLanturnPose184:
ax_pose 23, 0x01e7, 0x80f3, 0x0c00
ax_pose_terminator
sLanturnPose185:
ax_pose 22, 0x01e7, 0x80f0, 0x0c00
ax_pose_terminator
sLanturnPose186:
ax_pose 21, 0x01e7, 0x80f1, 0x0c00
ax_pose_terminator
sLanturnPose187:
ax_pose 0, 0x01e6, 0x80f0, 0x0c00
ax_pose_terminator
sLanturnPose188:
ax_pose 20, 0x01e6, 0x80f0, 0x0c00
ax_pose_terminator
sLanturnPose189:
ax_pose 15, 0x01e8, 0x80f0, 0x0c00
ax_pose_terminator
sLanturnPose190:
ax_pose 3, 0x01e8, 0x90ef, 0x0c00
ax_pose_terminator
sLanturnPose191:
ax_pose 21, 0x01e8, 0x90ef, 0x0c00
ax_pose_terminator
sLanturnPose192:
ax_pose 16, 0x01ea, 0x90ef, 0x0c00
ax_pose_terminator
sLanturnPose193:
ax_pose 6, 0x01ee, 0x90ef, 0x0c00
ax_pose_terminator
sLanturnPose194:
ax_pose 22, 0x01e7, 0x90ee, 0x0c00
ax_pose_terminator
sLanturnPose195:
ax_pose 17, 0x01e9, 0x90ef, 0x0c00
ax_pose_terminator
sLanturnPose196:
ax_pose 9, 0x01e6, 0x90ec, 0x0c00
ax_pose_terminator
sLanturnPose197:
ax_pose 23, 0x01e7, 0x90ed, 0x0c00
ax_pose_terminator
sLanturnPose198:
ax_pose 18, 0x01e8, 0x90ef, 0x0c00
ax_pose_terminator
sLanturnPose199:
ax_pose 12, 0x01e6, 0x80f0, 0x0c00
ax_pose_terminator
sLanturnPose200:
ax_pose 24, 0x01e6, 0x80f0, 0x0c00
ax_pose_terminator
sLanturnPose201:
ax_pose 19, 0x01e7, 0x80f0, 0x0c00
ax_pose_terminator
sLanturnPose202:
ax_pose 9, 0x01e6, 0x80f3, 0x0c00
ax_pose_terminator
sLanturnPose203:
ax_pose 23, 0x01e7, 0x80f3, 0x0c00
ax_pose_terminator
sLanturnPose204:
ax_pose 18, 0x01e8, 0x80f1, 0x0c00
ax_pose_terminator
sLanturnPose205:
ax_pose 6, 0x01ee, 0x80f0, 0x0c00
ax_pose_terminator
sLanturnPose206:
ax_pose 22, 0x01e7, 0x80f1, 0x0c00
ax_pose_terminator
sLanturnPose207:
ax_pose 17, 0x01e9, 0x80f0, 0x0c00
ax_pose_terminator
sLanturnPose208:
ax_pose 3, 0x01e8, 0x80f0, 0x0c00
ax_pose_terminator
sLanturnPose209:
ax_pose 21, 0x01e8, 0x80f1, 0x0c00
ax_pose_terminator
sLanturnPose210:
ax_pose 16, 0x01ea, 0x80f1, 0x0c00
ax_pose_terminator
sLanturnPose211:
ax_pose 15, 0x01e8, 0x80f0, 0x0c00
ax_pose_terminator
sLanturnPose212:
ax_pose 16, 0x01e8, 0x80f2, 0x0c00
ax_pose_terminator
sLanturnPose213:
ax_pose 17, 0x01e8, 0x80f1, 0x0c00
ax_pose_terminator
sLanturnPose214:
ax_pose 18, 0x01e9, 0x80f2, 0x0c00
ax_pose_terminator
sLanturnPose215:
ax_pose 19, 0x01e9, 0x80f0, 0x0c00
ax_pose_terminator
sLanturnPose216:
ax_pose 18, 0x01e9, 0x90ee, 0x0c00
ax_pose_terminator
sLanturnPose217:
ax_pose 17, 0x01e8, 0x90ee, 0x0c00
ax_pose_terminator
sLanturnPose218:
ax_pose 16, 0x01e8, 0x90ee, 0x0c00
ax_pose_terminator
sLanturnPose219:
ax_pose 0, 0x01e6, 0x80f0, 0x0c00
ax_pose_terminator
sLanturnPose220:
ax_pose 3, 0x01e8, 0x80f0, 0x0c00
ax_pose_terminator
sLanturnPose221:
ax_pose 6, 0x01ee, 0x80f0, 0x0c00
ax_pose_terminator
sLanturnPose222:
ax_pose 9, 0x01e6, 0x80f3, 0x0c00
ax_pose_terminator
sLanturnPose223:
ax_pose 12, 0x01e6, 0x80f0, 0x0c00
ax_pose_terminator
sLanturnPose224:
ax_pose 9, 0x01e6, 0x90ec, 0x0c00
ax_pose_terminator
sLanturnPose225:
ax_pose 6, 0x01ee, 0x90ef, 0x0c00
ax_pose_terminator
sLanturnPose226:
ax_pose 3, 0x01e8, 0x90ef, 0x0c00
ax_pose_terminator
.align 2
sLanturnAnims_1_1:
ax_anim 8, 0, 0, 0, 0, 0, 0,
ax_anim 8, 0, 1, 0, 0, 0, 0,
ax_anim 8, 0, 0, 0, 0, 0, 0,
ax_anim 8, 0, 2, 0, 0, 0, 0,
ax_anim_terminator
sLanturnAnims_1_2:
ax_anim 8, 0, 3, 0, 0, 0, 0,
ax_anim 8, 0, 4, 0, 0, 0, 0,
ax_anim 8, 0, 3, 0, 0, 0, 0,
ax_anim 8, 0, 5, 0, 0, 0, 0,
ax_anim_terminator
sLanturnAnims_1_3:
ax_anim 8, 0, 6, 0, 0, 0, 0,
ax_anim 8, 0, 7, 0, 0, 0, 0,
ax_anim 8, 0, 6, 0, 0, 0, 0,
ax_anim 8, 0, 8, 0, 0, 0, 0,
ax_anim_terminator
sLanturnAnims_1_4:
ax_anim 8, 0, 9, 0, 0, 0, 0,
ax_anim 8, 0, 10, 0, 0, 0, 0,
ax_anim 8, 0, 9, 0, 0, 0, 0,
ax_anim 8, 0, 11, 0, 0, 0, 0,
ax_anim_terminator
sLanturnAnims_1_5:
ax_anim 8, 0, 12, 0, 0, 0, 0,
ax_anim 8, 0, 13, 0, 0, 0, 0,
ax_anim 8, 0, 12, 0, 0, 0, 0,
ax_anim 8, 0, 14, 0, 0, 0, 0,
ax_anim_terminator
sLanturnAnims_1_6:
ax_anim 8, 0, 15, 0, 0, 0, 0,
ax_anim 8, 0, 16, 0, 0, 0, 0,
ax_anim 8, 0, 15, 0, 0, 0, 0,
ax_anim 8, 0, 17, 0, 0, 0, 0,
ax_anim_terminator
sLanturnAnims_1_7:
ax_anim 8, 0, 18, 0, 0, 0, 0,
ax_anim 8, 0, 19, 0, 0, 0, 0,
ax_anim 8, 0, 18, 0, 0, 0, 0,
ax_anim 8, 0, 20, 0, 0, 0, 0,
ax_anim_terminator
sLanturnAnims_1_8:
ax_anim 8, 0, 21, 0, 0, 0, 0,
ax_anim 8, 0, 22, 0, 0, 0, 0,
ax_anim 8, 0, 21, 0, 0, 0, 0,
ax_anim 8, 0, 23, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sLanturnAnims_2_1:
ax_anim 2, 0, 24, 0, -1, 0, -1,
ax_anim 4, 0, 24, 0, -2, 0, -2,
ax_anim 1, 0, 26, 0, 0, 0, 0,
ax_anim 1, 2, 25, 0, 4, 0, 4,
ax_anim 1, 0, 26, 0, 10, 0, 10,
ax_anim 2, 0, 27, 0, 19, 0, 19,
ax_anim 2, 1, 27, 1, 19, 1, 19,
ax_anim 2, 0, 27, 0, 19, 0, 19,
ax_anim 2, 0, 27, 1, 19, 1, 19,
ax_anim 2, 0, 24, 0, 6, 0, 6,
ax_anim_terminator
sLanturnAnims_2_2:
ax_anim 2, 0, 28, -1, -1, -1, -1,
ax_anim 4, 0, 28, -2, -2, -2, -2,
ax_anim 1, 0, 30, 0, 0, 0, 0,
ax_anim 1, 2, 29, 4, 4, 4, 4,
ax_anim 1, 0, 30, 10, 10, 10, 10,
ax_anim 2, 0, 31, 21, 21, 21, 21,
ax_anim 2, 1, 31, 22, 20, 22, 20,
ax_anim 2, 0, 31, 21, 21, 21, 21,
ax_anim 2, 0, 31, 22, 20, 22, 20,
ax_anim 2, 0, 28, 6, 6, 6, 6,
ax_anim_terminator
sLanturnAnims_2_3:
ax_anim 2, 0, 32, -1, 0, -1, 0,
ax_anim 4, 0, 32, -2, 0, -2, 0,
ax_anim 1, 0, 34, 0, 0, 0, 0,
ax_anim 1, 2, 33, 4, 0, 4, 0,
ax_anim 1, 0, 34, 10, 0, 10, 0,
ax_anim 2, 0, 35, 18, 0, 18, 0,
ax_anim 2, 1, 35, 18, 1, 18, 1,
ax_anim 2, 0, 35, 18, 0, 18, 0,
ax_anim 2, 0, 35, 18, 1, 18, 1,
ax_anim 2, 0, 32, 6, 0, 6, 0,
ax_anim_terminator
sLanturnAnims_2_4:
ax_anim 2, 0, 36, -1, 1, -1, 1,
ax_anim 4, 0, 36, -2, 2, -2, 2,
ax_anim 1, 0, 38, 0, -1, 0, -1,
ax_anim 1, 2, 37, 4, -6, 4, -6,
ax_anim 1, 0, 38, 10, -13, 10, -13,
ax_anim 2, 0, 39, 20, -22, 20, -22,
ax_anim 2, 1, 39, 21, -21, 21, -21,
ax_anim 2, 0, 39, 20, -22, 20, -22,
ax_anim 2, 0, 39, 21, -21, 21, -21,
ax_anim 2, 0, 36, 6, -6, 6, -6,
ax_anim_terminator
sLanturnAnims_2_5:
ax_anim 2, 0, 40, 0, 1, 0, 1,
ax_anim 4, 0, 40, 0, 2, 0, 2,
ax_anim 1, 0, 42, 0, 0, 0, 0,
ax_anim 1, 2, 41, 0, -4, 0, -4,
ax_anim 1, 0, 42, 0, -11, 0, -11,
ax_anim 2, 0, 43, 0, -21, 0, -21,
ax_anim 2, 1, 43, 1, -21, 1, -21,
ax_anim 2, 0, 43, 0, -21, 0, -21,
ax_anim 2, 0, 43, 1, -21, 1, -21,
ax_anim 2, 0, 40, 0, -6, 0, -6,
ax_anim_terminator
sLanturnAnims_2_6:
ax_anim 2, 0, 44, 1, 1, 1, 1,
ax_anim 4, 0, 44, 2, 2, 2, 2,
ax_anim 1, 0, 46, 0, -1, 0, -1,
ax_anim 1, 2, 45, -4, -6, -4, -6,
ax_anim 1, 0, 46, -10, -13, -10, -13,
ax_anim 2, 0, 47, -20, -22, -20, -22,
ax_anim 2, 1, 47, -21, -21, -21, -21,
ax_anim 2, 0, 47, -20, -22, -20, -22,
ax_anim 2, 0, 47, -21, -21, -21, -21,
ax_anim 2, 0, 44, -6, -6, -6, -6,
ax_anim_terminator
sLanturnAnims_2_7:
ax_anim 2, 0, 48, 1, 0, 1, 0,
ax_anim 4, 0, 48, 2, 0, 2, 0,
ax_anim 1, 0, 50, 0, 0, 0, 0,
ax_anim 1, 2, 49, -4, 0, -4, 0,
ax_anim 1, 0, 50, -10, 0, -10, 0,
ax_anim 2, 0, 51, -18, 0, -18, 0,
ax_anim 2, 1, 51, -18, 1, -18, 1,
ax_anim 2, 0, 51, -18, 0, -18, 0,
ax_anim 2, 0, 51, -18, 1, -18, 1,
ax_anim 2, 0, 48, -6, 0, -6, 0,
ax_anim_terminator
sLanturnAnims_2_8:
ax_anim 2, 0, 52, 1, -1, 1, -1,
ax_anim 4, 0, 52, 2, -2, 2, -2,
ax_anim 1, 0, 54, 0, 0, 0, 0,
ax_anim 1, 2, 53, -4, 4, -4, 4,
ax_anim 1, 0, 54, -10, 10, -10, 10,
ax_anim 2, 0, 55, -21, 21, -21, 21,
ax_anim 2, 1, 55, -22, 20, -22, 20,
ax_anim 2, 0, 55, -21, 21, -21, 21,
ax_anim 2, 0, 55, -22, 20, -22, 20,
ax_anim 2, 0, 52, -6, 6, -6, 6,
ax_anim_terminator
.align 2
sLanturnAnims_3_1:
ax_anim 2, 0, 56, 0, -1, 0, -1,
ax_anim 4, 0, 56, 0, -2, 0, -2,
ax_anim 1, 0, 58, 0, 0, 0, 0,
ax_anim 1, 2, 57, 0, 4, 0, 4,
ax_anim 1, 0, 58, 0, 10, 0, 10,
ax_anim 2, 0, 59, 0, 19, 0, 19,
ax_anim 2, 1, 59, 1, 19, 1, 19,
ax_anim 2, 0, 59, 0, 19, 0, 19,
ax_anim 2, 0, 59, 1, 19, 1, 19,
ax_anim 2, 0, 56, 0, 6, 0, 6,
ax_anim_terminator
sLanturnAnims_3_2:
ax_anim 2, 0, 60, -1, -1, -1, -1,
ax_anim 4, 0, 60, -2, -2, -2, -2,
ax_anim 1, 0, 62, 0, 0, 0, 0,
ax_anim 1, 2, 61, 4, 4, 4, 4,
ax_anim 1, 0, 62, 10, 10, 10, 10,
ax_anim 2, 0, 63, 21, 21, 21, 21,
ax_anim 2, 1, 63, 22, 20, 22, 20,
ax_anim 2, 0, 63, 21, 21, 21, 21,
ax_anim 2, 0, 63, 22, 20, 22, 20,
ax_anim 2, 0, 60, 6, 6, 6, 6,
ax_anim_terminator
sLanturnAnims_3_3:
ax_anim 2, 0, 64, -1, 0, -1, 0,
ax_anim 4, 0, 64, -2, 0, -2, 0,
ax_anim 1, 0, 66, 0, 0, 0, 0,
ax_anim 1, 2, 65, 4, 0, 4, 0,
ax_anim 1, 0, 66, 10, 0, 10, 0,
ax_anim 2, 0, 67, 18, 0, 18, 0,
ax_anim 2, 1, 67, 18, 1, 18, 1,
ax_anim 2, 0, 67, 18, 0, 18, 0,
ax_anim 2, 0, 67, 18, 1, 18, 1,
ax_anim 2, 0, 64, 6, 0, 6, 0,
ax_anim_terminator
sLanturnAnims_3_4:
ax_anim 2, 0, 68, -1, 1, -1, 1,
ax_anim 4, 0, 68, -2, 2, -2, 2,
ax_anim 1, 0, 70, 0, -1, 0, -1,
ax_anim 1, 2, 69, 4, -6, 4, -6,
ax_anim 1, 0, 70, 10, -13, 10, -13,
ax_anim 2, 0, 71, 20, -22, 20, -22,
ax_anim 2, 1, 71, 21, -21, 21, -21,
ax_anim 2, 0, 71, 20, -22, 20, -22,
ax_anim 2, 0, 71, 21, -21, 21, -21,
ax_anim 2, 0, 68, 6, -6, 6, -6,
ax_anim_terminator
sLanturnAnims_3_5:
ax_anim 2, 0, 72, 0, 1, 0, 1,
ax_anim 4, 0, 72, 0, 2, 0, 2,
ax_anim 1, 0, 74, 0, 0, 0, 0,
ax_anim 1, 2, 73, 0, -4, 0, -4,
ax_anim 1, 0, 74, 0, -11, 0, -11,
ax_anim 2, 0, 75, 0, -21, 0, -21,
ax_anim 2, 1, 75, 1, -21, 1, -21,
ax_anim 2, 0, 75, 0, -21, 0, -21,
ax_anim 2, 0, 75, 1, -21, 1, -21,
ax_anim 2, 0, 72, 0, -6, 0, -6,
ax_anim_terminator
sLanturnAnims_3_6:
ax_anim 2, 0, 76, 1, 1, 1, 1,
ax_anim 4, 0, 76, 2, 2, 2, 2,
ax_anim 1, 0, 78, 0, -1, 0, -1,
ax_anim 1, 2, 77, -4, -6, -4, -6,
ax_anim 1, 0, 78, -10, -13, -10, -13,
ax_anim 2, 0, 79, -20, -22, -20, -22,
ax_anim 2, 1, 79, -21, -21, -21, -21,
ax_anim 2, 0, 79, -20, -22, -20, -22,
ax_anim 2, 0, 79, -21, -21, -21, -21,
ax_anim 2, 0, 76, -6, -6, -6, -6,
ax_anim_terminator
sLanturnAnims_3_7:
ax_anim 2, 0, 80, 1, 0, 1, 0,
ax_anim 4, 0, 80, 2, 0, 2, 0,
ax_anim 1, 0, 82, 0, 0, 0, 0,
ax_anim 1, 2, 81, -4, 0, -4, 0,
ax_anim 1, 0, 82, -10, 0, -10, 0,
ax_anim 2, 0, 83, -18, 0, -18, 0,
ax_anim 2, 1, 83, -18, 1, -18, 1,
ax_anim 2, 0, 83, -18, 0, -18, 0,
ax_anim 2, 0, 83, -18, 1, -18, 1,
ax_anim 2, 0, 80, -6, 0, -6, 0,
ax_anim_terminator
sLanturnAnims_3_8:
ax_anim 2, 0, 84, 1, -1, 1, -1,
ax_anim 4, 0, 84, 2, -2, 2, -2,
ax_anim 1, 0, 86, 0, 0, 0, 0,
ax_anim 1, 2, 85, -4, 4, -4, 4,
ax_anim 1, 0, 86, -10, 10, -10, 10,
ax_anim 2, 0, 87, -21, 21, -21, 21,
ax_anim 2, 1, 87, -22, 20, -22, 20,
ax_anim 2, 0, 87, -21, 21, -21, 21,
ax_anim 2, 0, 87, -22, 20, -22, 20,
ax_anim 2, 0, 84, -6, 6, -6, 6,
ax_anim_terminator
.align 2
sLanturnAnims_4_1:
ax_anim 2, 0, 88, 0, -1, 0, 0,
ax_anim 2, 0, 91, 0, -3, 0, 0,
ax_anim 4, 2, 91, 0, -4, 0, 0,
ax_anim 1, 0, 91, 0, -1, 0, 0,
ax_anim 1, 0, 92, 0, 4, 0, 0,
ax_anim 2, 0, 92, 0, 5, 0, 0,
ax_anim 2, 1, 92, 1, 5, 0, 0,
ax_anim 2, 0, 92, 0, 5, 0, 0,
ax_anim 2, 0, 92, 1, 5, 0, 0,
ax_anim 2, 0, 92, 0, 5, 0, 0,
ax_anim 2, 0, 92, 1, 5, 0, 0,
ax_anim 2, 0, 88, 0, 2, 0, 0,
ax_anim_terminator
sLanturnAnims_4_2:
ax_anim 2, 0, 93, -1, -1, -1, -1,
ax_anim 2, 0, 96, -3, -3, -3, -3,
ax_anim 4, 2, 96, -4, -4, -4, -4,
ax_anim 1, 0, 96, -1, -1, -1, -1,
ax_anim 1, 0, 97, 4, 4, 4, 4,
ax_anim 2, 0, 97, 5, 5, 5, 5,
ax_anim 2, 1, 97, 6, 4, 6, 4,
ax_anim 2, 0, 97, 5, 5, 5, 5,
ax_anim 2, 0, 97, 6, 4, 6, 4,
ax_anim 2, 0, 97, 5, 5, 5, 5,
ax_anim 2, 0, 97, 6, 4, 6, 4,
ax_anim 2, 0, 93, 2, 2, 2, 2,
ax_anim_terminator
sLanturnAnims_4_3:
ax_anim 2, 0, 98, -1, 0, -1, 0,
ax_anim 2, 0, 101, -3, 0, -3, 0,
ax_anim 4, 2, 101, -4, 0, -4, 0,
ax_anim 1, 0, 101, -1, 0, -1, 0,
ax_anim 1, 0, 102, 4, 0, 4, 0,
ax_anim 2, 0, 102, 5, -1, 5, -1,
ax_anim 2, 1, 102, 5, 0, 5, 0,
ax_anim 2, 0, 102, 5, -1, 5, -1,
ax_anim 2, 0, 102, 5, 0, 5, 0,
ax_anim 2, 0, 102, 5, -1, 5, -1,
ax_anim 2, 0, 102, 5, 0, 5, 0,
ax_anim 2, 0, 98, 2, 0, 2, 0,
ax_anim_terminator
sLanturnAnims_4_4:
ax_anim 2, 0, 103, -1, 1, -1, 1,
ax_anim 2, 0, 106, -3, 3, -3, 3,
ax_anim 4, 2, 106, -4, 4, -4, 4,
ax_anim 1, 0, 106, -1, 1, -1, 1,
ax_anim 1, 0, 107, 4, -4, 4, -4,
ax_anim 2, 0, 107, 5, -5, 5, -5,
ax_anim 2, 1, 107, 6, -4, 6, -4,
ax_anim 2, 0, 107, 5, -5, 5, -5,
ax_anim 2, 0, 107, 6, -4, 6, -4,
ax_anim 2, 0, 107, 5, -5, 5, -5,
ax_anim 2, 0, 107, 6, -4, 6, -4,
ax_anim 2, 0, 103, 2, -2, 2, -2,
ax_anim_terminator
sLanturnAnims_4_5:
ax_anim 2, 0, 108, 0, 1, 0, 0,
ax_anim 2, 0, 111, 0, 3, 0, 0,
ax_anim 4, 2, 111, 0, 4, 0, 0,
ax_anim 1, 0, 111, 0, 1, 0, 0,
ax_anim 1, 0, 112, 0, -4, 0, 0,
ax_anim 2, 0, 112, 0, -5, 0, 0,
ax_anim 2, 1, 112, 1, -5, 0, 0,
ax_anim 2, 0, 112, 0, -5, 0, 0,
ax_anim 2, 0, 112, 1, -5, 0, 0,
ax_anim 2, 0, 112, 0, -5, 0, 0,
ax_anim 2, 0, 112, 1, -5, 0, 0,
ax_anim 2, 0, 108, 0, -2, 0, 0,
ax_anim_terminator
sLanturnAnims_4_6:
ax_anim 2, 0, 113, 1, 1, 1, 1,
ax_anim 2, 0, 116, 3, 3, 3, 3,
ax_anim 4, 2, 116, 4, 4, 4, 4,
ax_anim 1, 0, 116, 1, 1, 1, 1,
ax_anim 1, 0, 117, -4, -4, -4, -4,
ax_anim 2, 0, 117, -5, -5, -5, -5,
ax_anim 2, 1, 117, -6, -4, -6, -4,
ax_anim 2, 0, 117, -5, -5, -5, -5,
ax_anim 2, 0, 117, -6, -4, -6, -4,
ax_anim 2, 0, 117, -5, -5, -5, -5,
ax_anim 2, 0, 117, -6, -4, -6, -4,
ax_anim 2, 0, 113, -2, -2, -2, -2,
ax_anim_terminator
sLanturnAnims_4_7:
ax_anim 2, 0, 118, 1, 0, 1, 0,
ax_anim 2, 0, 121, 3, 0, 3, 0,
ax_anim 4, 2, 121, 4, 0, 4, 0,
ax_anim 1, 0, 121, 1, 0, 1, 0,
ax_anim 1, 0, 122, -4, 0, -4, 0,
ax_anim 2, 0, 122, -5, -1, -5, -1,
ax_anim 2, 1, 122, -5, 0, -5, 0,
ax_anim 2, 0, 122, -5, -1, -5, -1,
ax_anim 2, 0, 122, -5, 0, -5, 0,
ax_anim 2, 0, 122, -5, -1, -5, -1,
ax_anim 2, 0, 122, -5, 0, -5, 0,
ax_anim 2, 0, 118, -2, 0, -2, 0,
ax_anim_terminator
sLanturnAnims_4_8:
ax_anim 2, 0, 123, 1, -1, 1, -1,
ax_anim 2, 0, 126, 3, -3, 3, -3,
ax_anim 4, 2, 126, 4, -4, 4, -4,
ax_anim 1, 0, 126, 1, -1, 1, -1,
ax_anim 1, 0, 127, -4, 4, -4, 4,
ax_anim 2, 0, 127, -5, 5, -5, 5,
ax_anim 2, 1, 127, -6, 4, -6, 4,
ax_anim 2, 0, 127, -5, 5, -5, 5,
ax_anim 2, 0, 127, -6, 4, -6, 4,
ax_anim 2, 0, 127, -5, 5, -5, 5,
ax_anim 2, 0, 127, -6, 4, -6, 4,
ax_anim 2, 0, 123, -2, 2, -2, 2,
ax_anim_terminator
.align 2
sLanturnAnims_5_1:
ax_anim 2, 0, 128, 0, 0, 0, 0,
ax_anim 2, 0, 129, 0, 0, 0, 0,
ax_anim 2, 0, 130, 0, 0, 0, 0,
ax_anim 2, 0, 131, 0, 0, 0, 0,
ax_anim 2, 0, 132, 0, 0, 0, 0,
ax_anim 2, 0, 133, 0, 0, 0, 0,
ax_anim 2, 0, 134, 0, 0, 0, 0,
ax_anim 2, 0, 135, 0, 0, 0, 0,
ax_anim 2, 2, 128, 0, 0, 0, 0,
ax_anim_terminator
sLanturnAnims_5_2:
ax_anim 2, 0, 135, 0, 0, 0, 0,
ax_anim 2, 0, 128, 0, 0, 0, 0,
ax_anim 2, 0, 129, 0, 0, 0, 0,
ax_anim 2, 0, 130, 0, 0, 0, 0,
ax_anim 2, 0, 131, 0, 0, 0, 0,
ax_anim 2, 0, 132, 0, 0, 0, 0,
ax_anim 2, 0, 133, 0, 0, 0, 0,
ax_anim 2, 0, 134, 0, 0, 0, 0,
ax_anim 2, 2, 135, 0, 0, 0, 0,
ax_anim_terminator
sLanturnAnims_5_3:
ax_anim 2, 0, 134, 0, 0, 0, 0,
ax_anim 2, 0, 135, 0, 0, 0, 0,
ax_anim 2, 0, 128, 0, 0, 0, 0,
ax_anim 2, 0, 129, 0, 0, 0, 0,
ax_anim 2, 0, 130, 0, 0, 0, 0,
ax_anim 2, 0, 131, 0, 0, 0, 0,
ax_anim 2, 0, 132, 0, 0, 0, 0,
ax_anim 2, 0, 133, 0, 0, 0, 0,
ax_anim 2, 2, 134, 0, 0, 0, 0,
ax_anim_terminator
sLanturnAnims_5_4:
ax_anim 2, 0, 133, 0, 0, 0, 0,
ax_anim 2, 0, 134, 0, 0, 0, 0,
ax_anim 2, 0, 135, 0, 0, 0, 0,
ax_anim 2, 0, 128, 0, 0, 0, 0,
ax_anim 2, 0, 129, 0, 0, 0, 0,
ax_anim 2, 0, 130, 0, 0, 0, 0,
ax_anim 2, 0, 131, 0, 0, 0, 0,
ax_anim 2, 0, 132, 0, 0, 0, 0,
ax_anim 2, 2, 133, 0, 0, 0, 0,
ax_anim_terminator
sLanturnAnims_5_5:
ax_anim 2, 0, 132, 0, 0, 0, 0,
ax_anim 2, 0, 133, 0, 0, 0, 0,
ax_anim 2, 0, 134, 0, 0, 0, 0,
ax_anim 2, 0, 135, 0, 0, 0, 0,
ax_anim 2, 0, 128, 0, 0, 0, 0,
ax_anim 2, 0, 129, 0, 0, 0, 0,
ax_anim 2, 0, 130, 0, 0, 0, 0,
ax_anim 2, 0, 131, 0, 0, 0, 0,
ax_anim 2, 2, 132, 0, 0, 0, 0,
ax_anim_terminator
sLanturnAnims_5_6:
ax_anim 2, 0, 131, 0, 0, 0, 0,
ax_anim 2, 0, 132, 0, 0, 0, 0,
ax_anim 2, 0, 133, 0, 0, 0, 0,
ax_anim 2, 0, 134, 0, 0, 0, 0,
ax_anim 2, 0, 135, 0, 0, 0, 0,
ax_anim 2, 0, 128, 0, 0, 0, 0,
ax_anim 2, 0, 129, 0, 0, 0, 0,
ax_anim 2, 0, 130, 0, 0, 0, 0,
ax_anim 2, 2, 131, 0, 0, 0, 0,
ax_anim_terminator
sLanturnAnims_5_7:
ax_anim 2, 0, 130, 0, 0, 0, 0,
ax_anim 2, 0, 131, 0, 0, 0, 0,
ax_anim 2, 0, 132, 0, 0, 0, 0,
ax_anim 2, 0, 133, 0, 0, 0, 0,
ax_anim 2, 0, 134, 0, 0, 0, 0,
ax_anim 2, 0, 135, 0, 0, 0, 0,
ax_anim 2, 0, 128, 0, 0, 0, 0,
ax_anim 2, 0, 129, 0, 0, 0, 0,
ax_anim 2, 2, 130, 0, 0, 0, 0,
ax_anim_terminator
sLanturnAnims_5_8:
ax_anim 2, 0, 129, 0, 0, 0, 0,
ax_anim 2, 0, 130, 0, 0, 0, 0,
ax_anim 2, 0, 131, 0, 0, 0, 0,
ax_anim 2, 0, 132, 0, 0, 0, 0,
ax_anim 2, 0, 133, 0, 0, 0, 0,
ax_anim 2, 0, 134, 0, 0, 0, 0,
ax_anim 2, 0, 135, 0, 0, 0, 0,
ax_anim 2, 0, 128, 0, 0, 0, 0,
ax_anim 2, 2, 129, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sLanturnAnims_6_1:
ax_anim 20, 0, 136, 0, 0, 0, 0,
ax_anim 14, 0, 137, 0, 0, 0, 0,
ax_anim 14, 0, 137, 0, 1, 0, 0,
ax_anim 20, 0, 137, 0, 2, 0, 0,
ax_anim 14, 0, 136, 0, 2, 0, 0,
ax_anim 14, 0, 136, 0, 1, 0, 0,
ax_anim_terminator
.align 2
sLanturnAnims_7_1:
ax_anim 2, 0, 138, 0, -2, 0, -2,
ax_anim 8, 0, 138, 0, -3, 0, -3,
ax_anim_terminator
sLanturnAnims_7_2:
ax_anim 2, 0, 139, -2, -2, -2, -2,
ax_anim 8, 0, 139, -3, -3, -3, -3,
ax_anim_terminator
sLanturnAnims_7_3:
ax_anim 2, 0, 140, -2, 0, -2, 0,
ax_anim 8, 0, 140, -3, 0, -3, 0,
ax_anim_terminator
sLanturnAnims_7_4:
ax_anim 2, 0, 141, -2, 2, -2, 2,
ax_anim 8, 0, 141, -3, 3, -3, 3,
ax_anim_terminator
sLanturnAnims_7_5:
ax_anim 2, 0, 142, 0, 2, 0, 2,
ax_anim 8, 0, 142, 0, 3, 0, 3,
ax_anim_terminator
sLanturnAnims_7_6:
ax_anim 2, 0, 143, 2, 2, 2, 2,
ax_anim 8, 0, 143, 3, 3, 3, 3,
ax_anim_terminator
sLanturnAnims_7_7:
ax_anim 2, 0, 144, 2, 0, 2, 0,
ax_anim 8, 0, 144, 3, 0, 3, 0,
ax_anim_terminator
sLanturnAnims_7_8:
ax_anim 2, 0, 145, 2, -2, 2, -2,
ax_anim 8, 0, 145, 3, -3, 3, -3,
ax_anim_terminator
.align 2
sLanturnAnims_8_1:
ax_anim 20, 0, 146, 0, 0, 0, 0,
ax_anim 6, 0, 147, 0, -1, 0, 0,
ax_anim 6, 0, 146, 0, -1, 0, 0,
ax_anim 6, 0, 148, 0, -1, 0, 0,
ax_anim 8, 0, 146, 0, -1, 0, 0,
ax_anim 8, 0, 146, 0, -2, 0, 0,
ax_anim 20, 0, 146, 0, -3, 0, 0,
ax_anim 8, 0, 146, 0, -2, 0, 0,
ax_anim 8, 0, 146, 0, -1, 0, 0,
ax_anim_terminator
sLanturnAnims_8_2:
ax_anim 20, 0, 149, 0, 0, 0, 0,
ax_anim 6, 0, 150, 0, -1, 0, 0,
ax_anim 6, 0, 149, 0, -1, 0, 0,
ax_anim 6, 0, 151, 0, -1, 0, 0,
ax_anim 8, 0, 149, 0, -1, 0, 0,
ax_anim 8, 0, 149, 0, -2, 0, 0,
ax_anim 20, 0, 149, 0, -3, 0, 0,
ax_anim 8, 0, 149, 0, -2, 0, 0,
ax_anim 8, 0, 149, 0, -1, 0, 0,
ax_anim_terminator
sLanturnAnims_8_3:
ax_anim 20, 0, 152, 0, 0, 0, 0,
ax_anim 6, 0, 153, 0, -1, 0, 0,
ax_anim 6, 0, 152, 0, -1, 0, 0,
ax_anim 6, 0, 154, 0, -1, 0, 0,
ax_anim 8, 0, 152, 0, -1, 0, 0,
ax_anim 8, 0, 152, 0, -2, 0, 0,
ax_anim 20, 0, 152, 0, -3, 0, 0,
ax_anim 8, 0, 152, 0, -2, 0, 0,
ax_anim 8, 0, 152, 0, -1, 0, 0,
ax_anim_terminator
sLanturnAnims_8_4:
ax_anim 20, 0, 155, 0, 0, 0, 0,
ax_anim 6, 0, 156, 0, -1, 0, 0,
ax_anim 6, 0, 155, 0, -1, 0, 0,
ax_anim 6, 0, 157, 0, -1, 0, 0,
ax_anim 8, 0, 155, 0, -1, 0, 0,
ax_anim 8, 0, 155, 0, -2, 0, 0,
ax_anim 20, 0, 155, 0, -3, 0, 0,
ax_anim 8, 0, 155, 0, -2, 0, 0,
ax_anim 8, 0, 155, 0, -1, 0, 0,
ax_anim_terminator
sLanturnAnims_8_5:
ax_anim 20, 0, 158, 0, 0, 0, 0,
ax_anim 6, 0, 159, 0, -1, 0, 0,
ax_anim 6, 0, 158, 0, -1, 0, 0,
ax_anim 6, 0, 160, 0, -1, 0, 0,
ax_anim 8, 0, 158, 0, -1, 0, 0,
ax_anim 8, 0, 158, 0, -2, 0, 0,
ax_anim 20, 0, 158, 0, -3, 0, 0,
ax_anim 8, 0, 158, 0, -2, 0, 0,
ax_anim 8, 0, 158, 0, -1, 0, 0,
ax_anim_terminator
sLanturnAnims_8_6:
ax_anim 20, 0, 161, 0, 0, 0, 0,
ax_anim 6, 0, 162, 0, -1, 0, 0,
ax_anim 6, 0, 161, 0, -1, 0, 0,
ax_anim 6, 0, 163, 0, -1, 0, 0,
ax_anim 8, 0, 161, 0, -1, 0, 0,
ax_anim 8, 0, 161, 0, -2, 0, 0,
ax_anim 20, 0, 161, 0, -3, 0, 0,
ax_anim 8, 0, 161, 0, -2, 0, 0,
ax_anim 8, 0, 161, 0, -1, 0, 0,
ax_anim_terminator
sLanturnAnims_8_7:
ax_anim 20, 0, 164, 0, 0, 0, 0,
ax_anim 6, 0, 165, 0, -1, 0, 0,
ax_anim 6, 0, 164, 0, -1, 0, 0,
ax_anim 6, 0, 166, 0, -1, 0, 0,
ax_anim 8, 0, 164, 0, -1, 0, 0,
ax_anim 8, 0, 164, 0, -2, 0, 0,
ax_anim 20, 0, 164, 0, -3, 0, 0,
ax_anim 8, 0, 164, 0, -2, 0, 0,
ax_anim 8, 0, 164, 0, -1, 0, 0,
ax_anim_terminator
sLanturnAnims_8_8:
ax_anim 20, 0, 167, 0, 0, 0, 0,
ax_anim 6, 0, 168, 0, -1, 0, 0,
ax_anim 6, 0, 167, 0, -1, 0, 0,
ax_anim 6, 0, 169, 0, -1, 0, 0,
ax_anim 8, 0, 167, 0, -1, 0, 0,
ax_anim 8, 0, 167, 0, -2, 0, 0,
ax_anim 20, 0, 167, 0, -3, 0, 0,
ax_anim 8, 0, 167, 0, -2, 0, 0,
ax_anim 8, 0, 167, 0, -1, 0, 0,
ax_anim_terminator
.align 2
sLanturnAnims_9_1:
ax_anim 2, 0, 170, 0, 0, 0, 0,
ax_anim 1, 0, 171, 7, 3, 7, 3,
ax_anim 2, 0, 172, 9, 10, 9, 10,
ax_anim 2, 0, 173, 7, 16, 7, 16,
ax_anim 3, 0, 174, 0, 19, 0, 19,
ax_anim 2, 3, 175, -7, 16, -7, 16,
ax_anim 2, 0, 176, -9, 10, -9, 10,
ax_anim 1, 0, 177, -7, 3, -7, 3,
ax_anim 1, 0, 170, 0, 0, 0, 0,
ax_anim_terminator
sLanturnAnims_9_2:
ax_anim 2, 0, 177, 0, 0, 0, 0,
ax_anim 1, 0, 170, 10, 3, 10, 3,
ax_anim 2, 0, 171, 20, 7, 20, 7,
ax_anim 2, 0, 172, 23, 12, 23, 12,
ax_anim 3, 0, 173, 18, 19, 18, 19,
ax_anim 2, 3, 174, 11, 18, 11, 18,
ax_anim 2, 0, 175, 3, 14, 3, 14,
ax_anim 1, 0, 176, 0, 7, 0, 7,
ax_anim 1, 0, 177, 0, 0, 0, 0,
ax_anim_terminator
sLanturnAnims_9_3:
ax_anim 2, 0, 176, 0, 0, 0, 0,
ax_anim 1, 0, 177, 2, -3, 2, -3,
ax_anim 2, 0, 170, 9, -3, 9, -3,
ax_anim 2, 0, 171, 16, -2, 16, -2,
ax_anim 3, 0, 172, 17, 2, 17, 0,
ax_anim 2, 3, 173, 15, 6, 15, 5,
ax_anim 2, 0, 174, 11, 7, 11, 7,
ax_anim 1, 0, 175, 4, 5, 4, 5,
ax_anim 1, 0, 176, 0, 0, 0, 0,
ax_anim_terminator
sLanturnAnims_9_4:
ax_anim 2, 0, 175, 0, 0, 0, 0,
ax_anim 1, 0, 176, -1, -7, -1, -7,
ax_anim 2, 0, 177, 3, -14, 3, -14,
ax_anim 2, 0, 170, 13, -18, 13, -20,
ax_anim 3, 0, 171, 21, -15, 21, -20,
ax_anim 2, 3, 172, 22, -10, 22, -10,
ax_anim 2, 0, 173, 17, -4, 17, -4,
ax_anim 1, 0, 174, 9, 0, 9, 0,
ax_anim 1, 0, 175, 0, 0, 0, 0,
ax_anim_terminator
sLanturnAnims_9_5:
ax_anim 2, 0, 174, 0, 0, 0, 0,
ax_anim 1, 0, 175, -8, -3, -8, -3,
ax_anim 2, 0, 176, -11, -8, -11, -8,
ax_anim 2, 0, 177, -7, -13, -7, -15,
ax_anim 3, 0, 170, 0, -14, 0, -19,
ax_anim 2, 3, 171, 7, -13, 7, -15,
ax_anim 2, 0, 172, 11, -8, 11, -8,
ax_anim 1, 0, 173, 8, -3, 8, -3,
ax_anim 1, 0, 174, 0, 0, 0, 0,
ax_anim_terminator
sLanturnAnims_9_6:
ax_anim 2, 0, 173, 0, 0, 0, 0,
ax_anim 1, 0, 172, 1, -7, 1, -7,
ax_anim 2, 0, 171, -3, -14, -3, -14,
ax_anim 2, 0, 170, -13, -18, -13, -20,
ax_anim 3, 0, 177, -21, -15, -21, -20,
ax_anim 2, 3, 176, -22, -10, -22, -10,
ax_anim 2, 0, 175, -17, -4, -17, -4,
ax_anim 1, 0, 174, -9, 0, -9, 0,
ax_anim 1, 0, 173, 0, 0, 0, 0,
ax_anim_terminator
sLanturnAnims_9_7:
ax_anim 2, 0, 172, 0, 0, 0, 0,
ax_anim 1, 0, 171, -2, -3, -2, -3,
ax_anim 2, 0, 170, -9, -3, -9, -3,
ax_anim 2, 0, 177, -16, -2, -16, -2,
ax_anim 3, 0, 176, -17, 2, -17, 0,
ax_anim 2, 3, 175, -15, 6, -15, 5,
ax_anim 2, 0, 174, -11, 7, -11, 7,
ax_anim 1, 0, 173, -4, 5, -4, 5,
ax_anim 1, 0, 172, 0, 0, 0, 0,
ax_anim_terminator
sLanturnAnims_9_8:
ax_anim 2, 0, 171, 0, 0, 0, 0,
ax_anim 1, 0, 170, -10, 3, -10, 3,
ax_anim 2, 0, 177, -20, 7, -20, 7,
ax_anim 2, 0, 176, -23, 12, -23, 12,
ax_anim 3, 0, 175, -18, 19, -18, 19,
ax_anim 2, 3, 174, -11, 18, -11, 18,
ax_anim 2, 0, 173, -3, 14, -3, 14,
ax_anim 1, 0, 172, 0, 7, 0, 7,
ax_anim 1, 0, 171, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sLanturnAnims_10_1:
ax_anim 2, 0, 178, 0, 0, 0, 0,
ax_anim 2, 0, 178, 6, 0, 6, 0,
ax_anim 2, 0, 178, -6, 0, -6, 0,
ax_anim 2, 0, 178, 10, 0, 10, 0,
ax_anim 2, 0, 178, -10, 0, -10, 0,
ax_anim 2, 0, 178, 12, 0, 12, 0,
ax_anim 3, 0, 178, -12, 0, -12, 0,
ax_anim 3, 0, 178, 13, 0, 13, 0,
ax_anim 3, 0, 178, -13, 0, -13, 0,
ax_anim 2, 0, 178, 12, 0, 12, 0,
ax_anim 3, 0, 178, -12, 0, -12, 0,
ax_anim 2, 0, 178, 10, 0, 10, 0,
ax_anim 2, 0, 178, -10, 0, -10, 0,
ax_anim 2, 0, 178, 6, 0, 6, 0,
ax_anim 2, 0, 178, -6, 0, -6, 0,
ax_anim 2, 0, 178, 0, 0, 0, 0,
ax_anim_terminator
sLanturnAnims_10_2:
ax_anim 2, 0, 179, 0, 0, 0, 0,
ax_anim 2, 0, 179, 6, -6, 6, -6,
ax_anim 2, 0, 179, -6, 6, -6, 6,
ax_anim 2, 0, 179, 10, -10, 10, -10,
ax_anim 2, 0, 179, -10, 10, -10, 10,
ax_anim 2, 0, 179, 12, -12, 12, -12,
ax_anim 3, 0, 179, -12, 12, -12, 12,
ax_anim 3, 0, 179, 13, -13, 13, -13,
ax_anim 3, 0, 179, -13, 13, -13, 13,
ax_anim 2, 0, 179, 12, -12, 12, -12,
ax_anim 3, 0, 179, -12, 12, -12, 12,
ax_anim 2, 0, 179, 10, -10, 10, -10,
ax_anim 2, 0, 179, -10, 10, -10, 10,
ax_anim 2, 0, 179, 6, -6, 6, -6,
ax_anim 2, 0, 179, -6, 6, -6, 6,
ax_anim 2, 0, 179, 0, 0, 0, 0,
ax_anim_terminator
sLanturnAnims_10_3:
ax_anim 2, 0, 180, 0, 0, 0, 0,
ax_anim 2, 0, 180, 0, -6, 0, -6,
ax_anim 2, 0, 180, 0, 6, 0, 6,
ax_anim 2, 0, 180, 0, -10, 0, -10,
ax_anim 2, 0, 180, 0, 10, 0, 10,
ax_anim 2, 0, 180, 0, -12, 0, -12,
ax_anim 3, 0, 180, 0, 12, 0, 12,
ax_anim 3, 0, 180, 0, -13, 0, -13,
ax_anim 3, 0, 180, 0, 13, 0, 13,
ax_anim 2, 0, 180, 0, -12, 0, -12,
ax_anim 3, 0, 180, 0, 12, 0, 12,
ax_anim 2, 0, 180, 0, -10, 0, -10,
ax_anim 2, 0, 180, 0, 10, 0, 10,
ax_anim 2, 0, 180, 0, -6, 0, -6,
ax_anim 2, 0, 180, 0, 6, 0, 6,
ax_anim 2, 0, 180, 0, 0, 0, 0,
ax_anim_terminator
sLanturnAnims_10_4:
ax_anim 2, 0, 181, 0, 0, 0, 0,
ax_anim 2, 0, 181, -6, -6, -6, -6,
ax_anim 2, 0, 181, 6, 6, 6, 6,
ax_anim 2, 0, 181, -10, -10, -10, -10,
ax_anim 2, 0, 181, 10, 10, 10, 10,
ax_anim 2, 0, 181, -12, -12, -12, -12,
ax_anim 3, 0, 181, 12, 12, 12, 12,
ax_anim 3, 0, 181, -13, -13, -13, -13,
ax_anim 3, 0, 181, 13, 13, 13, 13,
ax_anim 2, 0, 181, -12, -12, -12, -12,
ax_anim 3, 0, 181, 12, 12, 12, 12,
ax_anim 2, 0, 181, -10, -10, -10, -10,
ax_anim 2, 0, 181, 10, 10, 10, 10,
ax_anim 2, 0, 181, -6, -6, -6, -6,
ax_anim 2, 0, 181, 6, 6, 6, 6,
ax_anim 2, 0, 181, 0, 0, 0, 0,
ax_anim_terminator
sLanturnAnims_10_5:
ax_anim 2, 0, 182, 0, 0, 0, 0,
ax_anim 2, 0, 182, 6, 0, 6, 0,
ax_anim 2, 0, 182, -6, 0, -6, 0,
ax_anim 2, 0, 182, 10, 0, 10, 0,
ax_anim 2, 0, 182, -10, 0, -10, 0,
ax_anim 2, 0, 182, 12, 0, 12, 0,
ax_anim 3, 0, 182, -12, 0, -12, 0,
ax_anim 3, 0, 182, 13, 0, 13, 0,
ax_anim 3, 0, 182, -13, 0, -13, 0,
ax_anim 2, 0, 182, 12, 0, 12, 0,
ax_anim 3, 0, 182, -12, 0, -12, 0,
ax_anim 2, 0, 182, 10, 0, 10, 0,
ax_anim 2, 0, 182, -10, 0, -10, 0,
ax_anim 2, 0, 182, 6, 0, 6, 0,
ax_anim 2, 0, 182, -6, 0, -6, 0,
ax_anim 2, 0, 182, 0, 0, 0, 0,
ax_anim_terminator
sLanturnAnims_10_6:
ax_anim 2, 0, 183, 0, 0, 0, 0,
ax_anim 2, 0, 183, 6, -6, 6, -6,
ax_anim 2, 0, 183, -6, 6, -6, 6,
ax_anim 2, 0, 183, 10, -10, 10, -10,
ax_anim 2, 0, 183, -10, 10, -10, 10,
ax_anim 2, 0, 183, 12, -12, 12, -12,
ax_anim 3, 0, 183, -12, 12, -12, 12,
ax_anim 3, 0, 183, 13, -13, 13, -13,
ax_anim 3, 0, 183, -13, 13, -13, 13,
ax_anim 2, 0, 183, 12, -12, 12, -12,
ax_anim 3, 0, 183, -12, 12, -12, 12,
ax_anim 2, 0, 183, 10, -10, 10, -10,
ax_anim 2, 0, 183, -10, 10, -10, 10,
ax_anim 2, 0, 183, 6, -6, 6, -6,
ax_anim 2, 0, 183, -6, 6, -6, 6,
ax_anim 2, 0, 183, 0, 0, 0, 0,
ax_anim_terminator
sLanturnAnims_10_7:
ax_anim 2, 0, 184, 0, 0, 0, 0,
ax_anim 2, 0, 184, 0, -6, 0, -6,
ax_anim 2, 0, 184, 0, 6, 0, 6,
ax_anim 2, 0, 184, 0, -10, 0, -10,
ax_anim 2, 0, 184, 0, 10, 0, 10,
ax_anim 2, 0, 184, 0, -12, 0, -12,
ax_anim 3, 0, 184, 0, 12, 0, 12,
ax_anim 3, 0, 184, 0, -13, 0, -13,
ax_anim 3, 0, 184, 0, 13, 0, 13,
ax_anim 2, 0, 184, 0, -12, 0, -12,
ax_anim 3, 0, 184, 0, 12, 0, 12,
ax_anim 2, 0, 184, 0, -10, 0, -10,
ax_anim 2, 0, 184, 0, 10, 0, 10,
ax_anim 2, 0, 184, 0, -6, 0, -6,
ax_anim 2, 0, 184, 0, 6, 0, 6,
ax_anim 2, 0, 184, 0, 0, 0, 0,
ax_anim_terminator
sLanturnAnims_10_8:
ax_anim 2, 0, 185, 0, 0, 0, 0,
ax_anim 2, 0, 185, -6, -6, -6, -6,
ax_anim 2, 0, 185, 6, 6, 6, 6,
ax_anim 2, 0, 185, -10, -10, -10, -10,
ax_anim 2, 0, 185, 10, 10, 10, 10,
ax_anim 2, 0, 185, -12, -12, -12, -12,
ax_anim 3, 0, 185, 12, 12, 12, 12,
ax_anim 3, 0, 185, -13, -13, -13, -13,
ax_anim 3, 0, 185, 13, 13, 13, 13,
ax_anim 2, 0, 185, -12, -12, -12, -12,
ax_anim 3, 0, 185, 12, 12, 12, 12,
ax_anim 2, 0, 185, -10, -10, -10, -10,
ax_anim 2, 0, 185, 10, 10, 10, 10,
ax_anim 2, 0, 185, -6, -6, -6, -6,
ax_anim 2, 0, 185, 6, 6, 6, 6,
ax_anim 2, 0, 185, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sLanturnAnims_11_1:
ax_anim 2, 0, 186, 0, 0, 0, 0,
ax_anim 1, 0, 187, 0, -10, 0, 0,
ax_anim 2, 0, 187, 0, -16, 0, 0,
ax_anim 3, 0, 187, 0, -20, 0, 0,
ax_anim 4, 0, 187, 0, -21, 0, 0,
ax_anim 4, 0, 188, 0, -23, 0, 0,
ax_anim 3, 0, 188, 0, -22, 0, 0,
ax_anim 2, 0, 188, 0, -18, 0, 0,
ax_anim 1, 0, 188, 0, -10, 0, 0,
ax_anim 2, 2, 186, 0, 5, 0, 0,
ax_anim_terminator
sLanturnAnims_11_2:
ax_anim 2, 0, 189, 0, 0, 0, 0,
ax_anim 1, 0, 190, 0, -10, 0, 0,
ax_anim 2, 0, 190, 0, -16, 0, 0,
ax_anim 3, 0, 190, 0, -20, 0, 0,
ax_anim 4, 0, 190, 0, -21, 0, 0,
ax_anim 4, 0, 191, 0, -23, 0, 0,
ax_anim 3, 0, 191, 0, -22, 0, 0,
ax_anim 2, 0, 191, 0, -18, 0, 0,
ax_anim 1, 0, 191, 0, -10, 0, 0,
ax_anim 2, 2, 189, 0, 3, 0, 0,
ax_anim_terminator
sLanturnAnims_11_3:
ax_anim 2, 0, 192, 0, 0, 0, 0,
ax_anim 1, 0, 193, 0, -10, 0, 0,
ax_anim 2, 0, 193, 0, -16, 0, 0,
ax_anim 3, 0, 193, 0, -20, 0, 0,
ax_anim 4, 0, 193, 0, -21, 0, 0,
ax_anim 4, 0, 194, 0, -23, 0, 0,
ax_anim 3, 0, 194, 0, -22, 0, 0,
ax_anim 2, 0, 194, 0, -18, 0, 0,
ax_anim 1, 0, 194, 0, -10, 0, 0,
ax_anim 2, 2, 192, 0, 4, 0, 0,
ax_anim_terminator
sLanturnAnims_11_4:
ax_anim 2, 0, 195, 0, 0, 0, 0,
ax_anim 1, 0, 196, 0, -10, 0, 0,
ax_anim 2, 0, 196, 0, -16, 0, 0,
ax_anim 3, 0, 196, 0, -20, 0, 0,
ax_anim 4, 0, 196, 0, -21, 0, 0,
ax_anim 4, 0, 197, 0, -22, 0, 0,
ax_anim 3, 0, 197, 0, -21, 0, 0,
ax_anim 2, 0, 197, 0, -17, 0, 0,
ax_anim 1, 0, 197, 0, -10, 0, 0,
ax_anim 2, 2, 195, 0, 4, 0, 0,
ax_anim_terminator
sLanturnAnims_11_5:
ax_anim 2, 0, 198, 0, 0, 0, 0,
ax_anim 1, 0, 199, 0, -10, 0, 0,
ax_anim 2, 0, 199, 0, -16, 0, 0,
ax_anim 3, 0, 199, 0, -20, 0, 0,
ax_anim 4, 0, 199, 0, -21, 0, 0,
ax_anim 4, 0, 200, 0, -23, 0, 0,
ax_anim 3, 0, 200, 0, -22, 0, 0,
ax_anim 2, 0, 200, 0, -18, 0, 0,
ax_anim 1, 0, 200, 0, -10, 0, 0,
ax_anim 2, 2, 198, 0, 4, 0, 0,
ax_anim_terminator
sLanturnAnims_11_6:
ax_anim 2, 0, 201, 0, 0, 0, 0,
ax_anim 1, 0, 202, 0, -10, 0, 0,
ax_anim 2, 0, 202, 0, -16, 0, 0,
ax_anim 3, 0, 202, 0, -20, 0, 0,
ax_anim 4, 0, 202, 0, -21, 0, 0,
ax_anim 4, 0, 203, 0, -22, 0, 0,
ax_anim 3, 0, 203, 0, -21, 0, 0,
ax_anim 2, 0, 203, 0, -17, 0, 0,
ax_anim 1, 0, 203, 0, -10, 0, 0,
ax_anim 2, 2, 201, 0, 4, 0, 0,
ax_anim_terminator
sLanturnAnims_11_7:
ax_anim 2, 0, 204, 0, 0, 0, 0,
ax_anim 1, 0, 205, 0, -10, 0, 0,
ax_anim 2, 0, 205, 0, -16, 0, 0,
ax_anim 3, 0, 205, 0, -20, 0, 0,
ax_anim 4, 0, 205, 0, -21, 0, 0,
ax_anim 4, 0, 206, 0, -23, 0, 0,
ax_anim 3, 0, 206, 0, -22, 0, 0,
ax_anim 2, 0, 206, 0, -18, 0, 0,
ax_anim 1, 0, 206, 0, -10, 0, 0,
ax_anim 2, 2, 204, 0, 4, 0, 0,
ax_anim_terminator
sLanturnAnims_11_8:
ax_anim 2, 0, 207, 0, 0, 0, 0,
ax_anim 1, 0, 208, 0, -10, 0, 0,
ax_anim 2, 0, 208, 0, -16, 0, 0,
ax_anim 3, 0, 208, 0, -20, 0, 0,
ax_anim 4, 0, 208, 0, -21, 0, 0,
ax_anim 4, 0, 209, 0, -23, 0, 0,
ax_anim 3, 0, 209, 0, -22, 0, 0,
ax_anim 2, 0, 209, 0, -18, 0, 0,
ax_anim 1, 0, 209, 0, -10, 0, 0,
ax_anim 2, 2, 207, 0, 3, 0, 0,
ax_anim_terminator
.align 2
sLanturnAnims_12_1:
ax_anim 2, 0, 210, 1, 0, 1, 0,
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 2, 0, 210, 1, 0, 1, 0,
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 2, 0, 210, 1, 0, 1, 0,
ax_anim 2, 2, 210, 0, 0, 0, 0,
ax_anim 2, 0, 210, 1, 0, 1, 0,
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 2, 0, 210, 1, 0, 1, 0,
ax_anim 2, 1, 210, 0, 0, 0, 0,
ax_anim_terminator
sLanturnAnims_12_2:
ax_anim 2, 0, 217, 1, -1, 1, -1,
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 0, 217, 1, -1, 1, -1,
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 0, 217, 1, -1, 1, -1,
ax_anim 2, 2, 217, 0, 0, 0, 0,
ax_anim 2, 0, 217, 1, -1, 1, -1,
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 0, 217, 1, -1, 1, -1,
ax_anim 2, 1, 217, 0, 0, 0, 0,
ax_anim_terminator
sLanturnAnims_12_3:
ax_anim 2, 0, 216, 0, -1, 0, -1,
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, -1, 0, -1,
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, -1, 0, -1,
ax_anim 2, 2, 216, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, -1, 0, -1,
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, -1, 0, -1,
ax_anim 2, 1, 216, 0, 0, 0, 0,
ax_anim_terminator
sLanturnAnims_12_4:
ax_anim 2, 0, 215, -1, -1, -1, -1,
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 0, 215, -1, -1, -1, -1,
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 0, 215, -1, -1, -1, -1,
ax_anim 2, 2, 215, 0, 0, 0, 0,
ax_anim 2, 0, 215, -1, -1, -1, -1,
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 0, 215, -1, -1, -1, -1,
ax_anim 2, 1, 215, 0, 0, 0, 0,
ax_anim_terminator
sLanturnAnims_12_5:
ax_anim 2, 0, 214, 1, 0, 1, 0,
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 2, 0, 214, 1, 0, 1, 0,
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 2, 0, 214, 1, 0, 1, 0,
ax_anim 2, 2, 214, 0, 0, 0, 0,
ax_anim 2, 0, 214, 1, 0, 1, 0,
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 2, 0, 214, 1, 0, 1, 0,
ax_anim 2, 1, 214, 0, 0, 0, 0,
ax_anim_terminator
sLanturnAnims_12_6:
ax_anim 2, 0, 213, 1, -1, 1, -1,
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 2, 0, 213, 1, -1, 1, -1,
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 2, 0, 213, 1, -1, 1, -1,
ax_anim 2, 2, 213, 0, 0, 0, 0,
ax_anim 2, 0, 213, 1, -1, 1, -1,
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 2, 0, 213, 1, -1, 1, -1,
ax_anim 2, 1, 213, 0, 0, 0, 0,
ax_anim_terminator
sLanturnAnims_12_7:
ax_anim 2, 0, 212, 0, -1, 0, -1,
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 2, 0, 212, 0, -1, 0, -1,
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 2, 0, 212, 0, -1, 0, -1,
ax_anim 2, 2, 212, 0, 0, 0, 0,
ax_anim 2, 0, 212, 0, -1, 0, -1,
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 2, 0, 212, 0, -1, 0, -1,
ax_anim 2, 1, 212, 0, 0, 0, 0,
ax_anim_terminator
sLanturnAnims_12_8:
ax_anim 2, 0, 211, -1, -1, -1, -1,
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 2, 0, 211, -1, -1, -1, -1,
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 2, 0, 211, -1, -1, -1, -1,
ax_anim 2, 2, 211, 0, 0, 0, 0,
ax_anim 2, 0, 211, -1, -1, -1, -1,
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 2, 0, 211, -1, -1, -1, -1,
ax_anim 2, 1, 211, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sLanturnAnims_13_1:
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 2, 2, 218, 0, 0, 0, 0,
ax_anim_terminator
sLanturnAnims_13_2:
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 2, 2, 225, 0, 0, 0, 0,
ax_anim_terminator
sLanturnAnims_13_3:
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 2, 2, 224, 0, 0, 0, 0,
ax_anim_terminator
sLanturnAnims_13_4:
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 2, 223, 0, 0, 0, 0,
ax_anim_terminator
sLanturnAnims_13_5:
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 2, 222, 0, 0, 0, 0,
ax_anim_terminator
sLanturnAnims_13_6:
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 2, 221, 0, 0, 0, 0,
ax_anim_terminator
sLanturnAnims_13_7:
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 2, 220, 0, 0, 0, 0,
ax_anim_terminator
sLanturnAnims_13_8:
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 2, 219, 0, 0, 0, 0,
ax_anim_terminator
sLanturnGfx1:
.incbin "baserom.gba", 0xC7A7B4, 0x200
sLanturnSprites1:
ax_sprite sLanturnGfx1, 0x200
ax_sprite_terminator
sLanturnGfx2:
.incbin "baserom.gba", 0xC7A9C4, 0x200
sLanturnSprites2:
ax_sprite sLanturnGfx2, 0x200
ax_sprite_terminator
sLanturnGfx3:
.incbin "baserom.gba", 0xC7ABD4, 0x200
sLanturnSprites3:
ax_sprite sLanturnGfx3, 0x200
ax_sprite_terminator
sLanturnGfx4:
.incbin "baserom.gba", 0xC7ADE4, 0x200
sLanturnSprites4:
ax_sprite sLanturnGfx4, 0x200
ax_sprite_terminator
sLanturnGfx5:
.incbin "baserom.gba", 0xC7AFF4, 0x200
sLanturnSprites5:
ax_sprite sLanturnGfx5, 0x200
ax_sprite_terminator
sLanturnGfx6:
.incbin "baserom.gba", 0xC7B204, 0x200
sLanturnSprites6:
ax_sprite sLanturnGfx6, 0x200
ax_sprite_terminator
sLanturnGfx7:
.incbin "baserom.gba", 0xC7B414, 0x200
sLanturnSprites7:
ax_sprite sLanturnGfx7, 0x200
ax_sprite_terminator
sLanturnGfx8:
.incbin "baserom.gba", 0xC7B624, 0x200
sLanturnSprites8:
ax_sprite sLanturnGfx8, 0x200
ax_sprite_terminator
sLanturnGfx9:
.incbin "baserom.gba", 0xC7B834, 0x200
sLanturnSprites9:
ax_sprite sLanturnGfx9, 0x200
ax_sprite_terminator
sLanturnGfx10:
.incbin "baserom.gba", 0xC7BA44, 0x200
sLanturnSprites10:
ax_sprite sLanturnGfx10, 0x200
ax_sprite_terminator
sLanturnGfx11:
.incbin "baserom.gba", 0xC7BC54, 0x200
sLanturnSprites11:
ax_sprite sLanturnGfx11, 0x200
ax_sprite_terminator
sLanturnGfx12:
.incbin "baserom.gba", 0xC7BE64, 0x200
sLanturnSprites12:
ax_sprite sLanturnGfx12, 0x200
ax_sprite_terminator
sLanturnGfx13:
.incbin "baserom.gba", 0xC7C074, 0x200
sLanturnSprites13:
ax_sprite sLanturnGfx13, 0x200
ax_sprite_terminator
sLanturnGfx14:
.incbin "baserom.gba", 0xC7C284, 0x200
sLanturnSprites14:
ax_sprite sLanturnGfx14, 0x200
ax_sprite_terminator
sLanturnGfx15:
.incbin "baserom.gba", 0xC7C494, 0x200
sLanturnSprites15:
ax_sprite sLanturnGfx15, 0x200
ax_sprite_terminator
sLanturnGfx16:
.incbin "baserom.gba", 0xC7C6A4, 0x40
sLanturnGfx16_1:
.incbin "baserom.gba", 0xC7C6E4, 0x40
sLanturnGfx16_2:
.incbin "baserom.gba", 0xC7C724, 0x80
sLanturnSprites16:
ax_sprite 0, 0x20
ax_sprite sLanturnGfx16, 0x40
ax_sprite 0, 0x40
ax_sprite sLanturnGfx16_1, 0x40
ax_sprite 0, 0x20
ax_sprite sLanturnGfx16_2, 0x80
ax_sprite 0, 0x80
ax_sprite_terminator
sLanturnGfx17:
.incbin "baserom.gba", 0xC7C7E4, 0x100
sLanturnSprites17:
ax_sprite 0, 0x80
ax_sprite sLanturnGfx17, 0x100
ax_sprite 0, 0x80
ax_sprite_terminator
sLanturnGfx18:
.incbin "baserom.gba", 0xC7C904, 0x20
sLanturnGfx18_1:
.incbin "baserom.gba", 0xC7C924, 0x100
sLanturnGfx18_2:
.incbin "baserom.gba", 0xC7CA24, 0x20
sLanturnSprites18:
ax_sprite 0, 0x20
ax_sprite sLanturnGfx18, 0x20
ax_sprite 0, 0x40
ax_sprite sLanturnGfx18_1, 0x100
ax_sprite 0, 0x20
ax_sprite sLanturnGfx18_2, 0x20
ax_sprite 0, 0x40
ax_sprite_terminator
sLanturnGfx19:
.incbin "baserom.gba", 0xC7CA84, 0x40
sLanturnGfx19_1:
.incbin "baserom.gba", 0xC7CAC4, 0x100
sLanturnGfx19_2:
.incbin "baserom.gba", 0xC7CBC4, 0x20
sLanturnSprites19:
ax_sprite sLanturnGfx19, 0x40
ax_sprite 0, 0x40
ax_sprite sLanturnGfx19_1, 0x100
ax_sprite 0, 0x40
ax_sprite sLanturnGfx19_2, 0x20
ax_sprite 0, 0x20
ax_sprite_terminator
sLanturnGfx20:
.incbin "baserom.gba", 0xC7CC1C, 0x40
sLanturnGfx20_1:
.incbin "baserom.gba", 0xC7CC5C, 0x60
sLanturnGfx20_2:
.incbin "baserom.gba", 0xC7CCBC, 0x80
sLanturnGfx20_3:
.incbin "baserom.gba", 0xC7CD3C, 0x40
sLanturnSprites20:
ax_sprite 0, 0x20
ax_sprite sLanturnGfx20, 0x40
ax_sprite 0, 0x20
ax_sprite sLanturnGfx20_1, 0x60
ax_sprite 0, 0x20
ax_sprite sLanturnGfx20_2, 0x80
ax_sprite 0, 0x20
ax_sprite sLanturnGfx20_3, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sLanturnGfx21:
.incbin "baserom.gba", 0xC7CDCC, 0x40
sLanturnGfx21_1:
.incbin "baserom.gba", 0xC7CE0C, 0x40
sLanturnGfx21_2:
.incbin "baserom.gba", 0xC7CE4C, 0x80
sLanturnSprites21:
ax_sprite 0, 0x20
ax_sprite sLanturnGfx21, 0x40
ax_sprite 0, 0x40
ax_sprite sLanturnGfx21_1, 0x40
ax_sprite 0, 0x20
ax_sprite sLanturnGfx21_2, 0x80
ax_sprite 0, 0x80
ax_sprite_terminator
sLanturnGfx22:
.incbin "baserom.gba", 0xC7CF0C, 0x40
sLanturnGfx22_1:
.incbin "baserom.gba", 0xC7CF4C, 0x100
sLanturnSprites22:
ax_sprite 0, 0x20
ax_sprite sLanturnGfx22, 0x40
ax_sprite 0, 0x20
ax_sprite sLanturnGfx22_1, 0x100
ax_sprite 0, 0x80
ax_sprite_terminator
sLanturnGfx23:
.incbin "baserom.gba", 0xC7D07C, 0x40
sLanturnGfx23_1:
.incbin "baserom.gba", 0xC7D0BC, 0x100
sLanturnSprites23:
ax_sprite 0, 0x20
ax_sprite sLanturnGfx23, 0x40
ax_sprite 0, 0x20
ax_sprite sLanturnGfx23_1, 0x100
ax_sprite 0, 0x80
ax_sprite_terminator
sLanturnGfx24:
.incbin "baserom.gba", 0xC7D1EC, 0x60
sLanturnGfx24_1:
.incbin "baserom.gba", 0xC7D24C, 0x100
sLanturnSprites24:
ax_sprite sLanturnGfx24, 0x60
ax_sprite 0, 0x20
ax_sprite sLanturnGfx24_1, 0x100
ax_sprite 0, 0x80
ax_sprite_terminator
sLanturnGfx25:
.incbin "baserom.gba", 0xC7D374, 0x40
sLanturnGfx25_1:
.incbin "baserom.gba", 0xC7D3B4, 0x40
sLanturnGfx25_2:
.incbin "baserom.gba", 0xC7D3F4, 0x80
sLanturnSprites25:
ax_sprite 0, 0x20
ax_sprite sLanturnGfx25, 0x40
ax_sprite 0, 0x40
ax_sprite sLanturnGfx25_1, 0x40
ax_sprite 0, 0x20
ax_sprite sLanturnGfx25_2, 0x80
ax_sprite 0, 0x80
ax_sprite_terminator
sLanturnGfx26:
.incbin "baserom.gba", 0xC7D4B4, 0x200
sLanturnSprites26:
ax_sprite sLanturnGfx26, 0x200
ax_sprite_terminator
sLanturnGfx27:
.incbin "baserom.gba", 0xC7D6C4, 0x200
sLanturnSprites27:
ax_sprite sLanturnGfx27, 0x200
ax_sprite_terminator
sLanturnGfx28:
.incbin "baserom.gba", 0xC7D8D4, 0x200
sLanturnSprites28:
ax_sprite sLanturnGfx28, 0x200
ax_sprite_terminator
sLanturnGfx29:
.incbin "baserom.gba", 0xC7DAE4, 0x200
sLanturnSprites29:
ax_sprite sLanturnGfx29, 0x200
ax_sprite_terminator
sLanturnGfx30:
.incbin "baserom.gba", 0xC7DCF4, 0x200
sLanturnSprites30:
ax_sprite sLanturnGfx30, 0x200
ax_sprite_terminator
sLanturnGfx31:
.incbin "baserom.gba", 0xC7DF04, 0x200
sLanturnSprites31:
ax_sprite sLanturnGfx31, 0x200
ax_sprite_terminator
sLanturnGfx32:
.incbin "baserom.gba", 0xC7E114, 0x200
sLanturnSprites32:
ax_sprite sLanturnGfx32, 0x200
ax_sprite_terminator
sAxPosesLanturn:
.4byte sLanturnPose1
.4byte sLanturnPose2
.4byte sLanturnPose3
.4byte sLanturnPose4
.4byte sLanturnPose5
.4byte sLanturnPose6
.4byte sLanturnPose7
.4byte sLanturnPose8
.4byte sLanturnPose9
.4byte sLanturnPose10
.4byte sLanturnPose11
.4byte sLanturnPose12
.4byte sLanturnPose13
.4byte sLanturnPose14
.4byte sLanturnPose15
.4byte sLanturnPose16
.4byte sLanturnPose17
.4byte sLanturnPose18
.4byte sLanturnPose19
.4byte sLanturnPose20
.4byte sLanturnPose21
.4byte sLanturnPose22
.4byte sLanturnPose23
.4byte sLanturnPose24
.4byte sLanturnPose25
.4byte sLanturnPose26
.4byte sLanturnPose27
.4byte sLanturnPose28
.4byte sLanturnPose29
.4byte sLanturnPose30
.4byte sLanturnPose31
.4byte sLanturnPose32
.4byte sLanturnPose33
.4byte sLanturnPose34
.4byte sLanturnPose35
.4byte sLanturnPose36
.4byte sLanturnPose37
.4byte sLanturnPose38
.4byte sLanturnPose39
.4byte sLanturnPose40
.4byte sLanturnPose41
.4byte sLanturnPose42
.4byte sLanturnPose43
.4byte sLanturnPose44
.4byte sLanturnPose45
.4byte sLanturnPose46
.4byte sLanturnPose47
.4byte sLanturnPose48
.4byte sLanturnPose49
.4byte sLanturnPose50
.4byte sLanturnPose51
.4byte sLanturnPose52
.4byte sLanturnPose53
.4byte sLanturnPose54
.4byte sLanturnPose55
.4byte sLanturnPose56
.4byte sLanturnPose57
.4byte sLanturnPose58
.4byte sLanturnPose59
.4byte sLanturnPose60
.4byte sLanturnPose61
.4byte sLanturnPose62
.4byte sLanturnPose63
.4byte sLanturnPose64
.4byte sLanturnPose65
.4byte sLanturnPose66
.4byte sLanturnPose67
.4byte sLanturnPose68
.4byte sLanturnPose69
.4byte sLanturnPose70
.4byte sLanturnPose71
.4byte sLanturnPose72
.4byte sLanturnPose73
.4byte sLanturnPose74
.4byte sLanturnPose75
.4byte sLanturnPose76
.4byte sLanturnPose77
.4byte sLanturnPose78
.4byte sLanturnPose79
.4byte sLanturnPose80
.4byte sLanturnPose81
.4byte sLanturnPose82
.4byte sLanturnPose83
.4byte sLanturnPose84
.4byte sLanturnPose85
.4byte sLanturnPose86
.4byte sLanturnPose87
.4byte sLanturnPose88
.4byte sLanturnPose89
.4byte sLanturnPose90
.4byte sLanturnPose91
.4byte sLanturnPose92
.4byte sLanturnPose93
.4byte sLanturnPose94
.4byte sLanturnPose95
.4byte sLanturnPose96
.4byte sLanturnPose97
.4byte sLanturnPose98
.4byte sLanturnPose99
.4byte sLanturnPose100
.4byte sLanturnPose101
.4byte sLanturnPose102
.4byte sLanturnPose103
.4byte sLanturnPose104
.4byte sLanturnPose105
.4byte sLanturnPose106
.4byte sLanturnPose107
.4byte sLanturnPose108
.4byte sLanturnPose109
.4byte sLanturnPose110
.4byte sLanturnPose111
.4byte sLanturnPose112
.4byte sLanturnPose113
.4byte sLanturnPose114
.4byte sLanturnPose115
.4byte sLanturnPose116
.4byte sLanturnPose117
.4byte sLanturnPose118
.4byte sLanturnPose119
.4byte sLanturnPose120
.4byte sLanturnPose121
.4byte sLanturnPose122
.4byte sLanturnPose123
.4byte sLanturnPose124
.4byte sLanturnPose125
.4byte sLanturnPose126
.4byte sLanturnPose127
.4byte sLanturnPose128
.4byte sLanturnPose129
.4byte sLanturnPose130
.4byte sLanturnPose131
.4byte sLanturnPose132
.4byte sLanturnPose133
.4byte sLanturnPose134
.4byte sLanturnPose135
.4byte sLanturnPose136
.4byte sLanturnPose137
.4byte sLanturnPose138
.4byte sLanturnPose139
.4byte sLanturnPose140
.4byte sLanturnPose141
.4byte sLanturnPose142
.4byte sLanturnPose143
.4byte sLanturnPose144
.4byte sLanturnPose145
.4byte sLanturnPose146
.4byte sLanturnPose147
.4byte sLanturnPose148
.4byte sLanturnPose149
.4byte sLanturnPose150
.4byte sLanturnPose151
.4byte sLanturnPose152
.4byte sLanturnPose153
.4byte sLanturnPose154
.4byte sLanturnPose155
.4byte sLanturnPose156
.4byte sLanturnPose157
.4byte sLanturnPose158
.4byte sLanturnPose159
.4byte sLanturnPose160
.4byte sLanturnPose161
.4byte sLanturnPose162
.4byte sLanturnPose163
.4byte sLanturnPose164
.4byte sLanturnPose165
.4byte sLanturnPose166
.4byte sLanturnPose167
.4byte sLanturnPose168
.4byte sLanturnPose169
.4byte sLanturnPose170
.4byte sLanturnPose171
.4byte sLanturnPose172
.4byte sLanturnPose173
.4byte sLanturnPose174
.4byte sLanturnPose175
.4byte sLanturnPose176
.4byte sLanturnPose177
.4byte sLanturnPose178
.4byte sLanturnPose179
.4byte sLanturnPose180
.4byte sLanturnPose181
.4byte sLanturnPose182
.4byte sLanturnPose183
.4byte sLanturnPose184
.4byte sLanturnPose185
.4byte sLanturnPose186
.4byte sLanturnPose187
.4byte sLanturnPose188
.4byte sLanturnPose189
.4byte sLanturnPose190
.4byte sLanturnPose191
.4byte sLanturnPose192
.4byte sLanturnPose193
.4byte sLanturnPose194
.4byte sLanturnPose195
.4byte sLanturnPose196
.4byte sLanturnPose197
.4byte sLanturnPose198
.4byte sLanturnPose199
.4byte sLanturnPose200
.4byte sLanturnPose201
.4byte sLanturnPose202
.4byte sLanturnPose203
.4byte sLanturnPose204
.4byte sLanturnPose205
.4byte sLanturnPose206
.4byte sLanturnPose207
.4byte sLanturnPose208
.4byte sLanturnPose209
.4byte sLanturnPose210
.4byte sLanturnPose211
.4byte sLanturnPose212
.4byte sLanturnPose213
.4byte sLanturnPose214
.4byte sLanturnPose215
.4byte sLanturnPose216
.4byte sLanturnPose217
.4byte sLanturnPose218
.4byte sLanturnPose219
.4byte sLanturnPose220
.4byte sLanturnPose221
.4byte sLanturnPose222
.4byte sLanturnPose223
.4byte sLanturnPose224
.4byte sLanturnPose225
.4byte sLanturnPose226
sAxPositionsLanturn:
.2byte   -1,   -2, 	 -12,   -7, 	  10,   -7, 	  -1,  -10
.2byte   -2,   -2, 	 -11,   -8, 	   8,   -6, 	  -1,  -10
.2byte    0,   -2, 	 -10,   -6, 	   9,   -8, 	   0,  -10
.2byte    8,   -4, 	  10,  -12, 	  -7,   -2, 	   0,   -9
.2byte    9,   -4, 	   8,  -13, 	  -4,   -2, 	   1,   -9
.2byte    6,   -3, 	   9,   -9, 	  -7,   -3, 	   1,   -9
.2byte    8,   -7, 	   3,   -6, 	   1,   -1, 	   1,   -9
.2byte    9,   -7, 	   3,   -6, 	   3,   -2, 	   1,   -9
.2byte    8,   -7, 	   1,   -5, 	   0,   -1, 	   1,   -9
.2byte    5,  -15, 	  -9,  -13, 	   9,   -4, 	   0,  -10
.2byte    3,  -16, 	 -10,  -11, 	   8,   -6, 	  -1,  -11
.2byte    6,  -14, 	  -7,  -14, 	   7,   -4, 	   1,  -11
.2byte   -1,   -9, 	  10,   -8, 	 -12,   -8, 	  -1,  -10
.2byte   -1,  -10, 	   9,   -8, 	 -10,   -9, 	   0,  -11
.2byte    0,  -10, 	   8,   -9, 	 -11,   -8, 	  -1,  -11
.2byte   -7,  -15, 	   7,  -13, 	 -11,   -4, 	  -2,  -10
.2byte   -5,  -16, 	   8,  -11, 	 -10,   -6, 	  -1,  -11
.2byte   -8,  -14, 	   5,  -14, 	  -9,   -4, 	  -3,  -11
.2byte  -10,   -7, 	  -5,   -6, 	  -3,   -1, 	  -3,   -9
.2byte  -11,   -7, 	  -5,   -6, 	  -5,   -2, 	  -3,   -9
.2byte  -10,   -7, 	  -3,   -5, 	  -2,   -1, 	  -3,   -9
.2byte  -10,   -4, 	 -12,  -12, 	   5,   -2, 	  -2,   -9
.2byte  -11,   -4, 	 -10,  -13, 	   2,   -2, 	  -3,   -9
.2byte   -8,   -3, 	 -11,   -9, 	   5,   -3, 	  -3,   -9
.2byte   -1,   -2, 	 -12,   -7, 	  10,   -7, 	  -1,  -10
.2byte   -2,   -2, 	 -11,   -8, 	   8,   -6, 	  -1,  -10
.2byte    0,   -2, 	 -10,   -6, 	   9,   -8, 	   0,  -10
.2byte   -1,    1, 	 -11,   -1, 	   9,   -1, 	  -1,   -5
.2byte    8,   -4, 	  10,  -12, 	  -7,   -2, 	   0,   -9
.2byte    9,   -4, 	   8,  -13, 	  -4,   -2, 	   1,   -9
.2byte    6,   -3, 	   9,   -9, 	  -7,   -3, 	   1,   -9
.2byte    3,   -2, 	   7,   -6, 	  -6,    0, 	   0,   -7
.2byte    8,   -7, 	   3,   -6, 	   1,   -1, 	   1,   -9
.2byte    9,   -7, 	   3,   -6, 	   3,   -2, 	   1,   -9
.2byte    8,   -7, 	   1,   -5, 	   0,   -1, 	   1,   -9
.2byte    5,   -5, 	   4,   -8, 	   1,   -1, 	   1,   -9
.2byte    5,  -15, 	  -9,  -13, 	   9,   -4, 	   0,  -10
.2byte    3,  -16, 	 -10,  -11, 	   8,   -6, 	  -1,  -11
.2byte    6,  -14, 	  -7,  -14, 	   7,   -4, 	   1,  -11
.2byte    3,   -7, 	  -3,  -10, 	   3,   -2, 	  -1,   -9
.2byte   -1,   -9, 	  10,   -8, 	 -12,   -8, 	  -1,  -10
.2byte   -1,  -10, 	   9,   -8, 	 -10,   -9, 	   0,  -11
.2byte    0,  -10, 	   8,   -9, 	 -11,   -8, 	  -1,  -11
.2byte   -1,  -11, 	   9,   -7, 	 -11,   -7, 	  -1,  -13
.2byte   -7,  -15, 	   7,  -13, 	 -11,   -4, 	  -2,  -10
.2byte   -5,  -16, 	   8,  -11, 	 -10,   -6, 	  -1,  -11
.2byte   -8,  -14, 	   5,  -14, 	  -9,   -4, 	  -3,  -11
.2byte   -4,   -9, 	   2,  -12, 	  -4,   -4, 	   0,  -11
.2byte  -10,   -7, 	  -5,   -6, 	  -3,   -1, 	  -3,   -9
.2byte  -11,   -7, 	  -5,   -6, 	  -5,   -2, 	  -3,   -9
.2byte  -10,   -7, 	  -3,   -5, 	  -2,   -1, 	  -3,   -9
.2byte   -6,   -5, 	  -5,   -8, 	  -2,   -1, 	  -2,   -9
.2byte  -10,   -4, 	 -12,  -12, 	   5,   -2, 	  -2,   -9
.2byte  -11,   -4, 	 -10,  -13, 	   2,   -2, 	  -3,   -9
.2byte   -8,   -3, 	 -11,   -9, 	   5,   -3, 	  -3,   -9
.2byte   -5,   -2, 	  -9,   -6, 	   4,    0, 	  -2,   -7
.2byte   -1,   -2, 	 -12,   -7, 	  10,   -7, 	  -1,  -10
.2byte   -2,   -2, 	 -11,   -8, 	   8,   -6, 	  -1,  -10
.2byte    0,   -2, 	 -10,   -6, 	   9,   -8, 	   0,  -10
.2byte   -1,    1, 	 -11,   -1, 	   9,   -1, 	  -1,   -5
.2byte    8,   -4, 	  10,  -12, 	  -7,   -2, 	   0,   -9
.2byte    9,   -4, 	   8,  -13, 	  -4,   -2, 	   1,   -9
.2byte    6,   -3, 	   9,   -9, 	  -7,   -3, 	   1,   -9
.2byte    3,   -2, 	   7,   -6, 	  -6,    0, 	   0,   -7
.2byte    8,   -7, 	   3,   -6, 	   1,   -1, 	   1,   -9
.2byte    9,   -7, 	   3,   -6, 	   3,   -2, 	   1,   -9
.2byte    8,   -7, 	   1,   -5, 	   0,   -1, 	   1,   -9
.2byte    5,   -5, 	   4,   -8, 	   1,   -1, 	   1,   -9
.2byte    5,  -15, 	  -9,  -13, 	   9,   -4, 	   0,  -10
.2byte    3,  -16, 	 -10,  -11, 	   8,   -6, 	  -1,  -11
.2byte    6,  -14, 	  -7,  -14, 	   7,   -4, 	   1,  -11
.2byte    3,   -7, 	  -3,  -10, 	   3,   -2, 	  -1,   -9
.2byte   -1,   -9, 	  10,   -8, 	 -12,   -8, 	  -1,  -10
.2byte   -1,  -10, 	   9,   -8, 	 -10,   -9, 	   0,  -11
.2byte    0,  -10, 	   8,   -9, 	 -11,   -8, 	  -1,  -11
.2byte   -1,  -11, 	   9,   -7, 	 -11,   -7, 	  -1,  -13
.2byte   -7,  -15, 	   7,  -13, 	 -11,   -4, 	  -2,  -10
.2byte   -5,  -16, 	   8,  -11, 	 -10,   -6, 	  -1,  -11
.2byte   -8,  -14, 	   5,  -14, 	  -9,   -4, 	  -3,  -11
.2byte   -4,   -9, 	   2,  -12, 	  -4,   -4, 	   0,  -11
.2byte  -10,   -7, 	  -5,   -6, 	  -3,   -1, 	  -3,   -9
.2byte  -11,   -7, 	  -5,   -6, 	  -5,   -2, 	  -3,   -9
.2byte  -10,   -7, 	  -3,   -5, 	  -2,   -1, 	  -3,   -9
.2byte   -6,   -5, 	  -5,   -8, 	  -2,   -1, 	  -2,   -9
.2byte  -10,   -4, 	 -12,  -12, 	   5,   -2, 	  -2,   -9
.2byte  -11,   -4, 	 -10,  -13, 	   2,   -2, 	  -3,   -9
.2byte   -8,   -3, 	 -11,   -9, 	   5,   -3, 	  -3,   -9
.2byte   -5,   -2, 	  -9,   -6, 	   4,    0, 	  -2,   -7
.2byte   -1,   -2, 	 -12,   -7, 	  10,   -7, 	  -1,  -10
.2byte   -2,   -2, 	 -11,   -8, 	   8,   -6, 	  -1,  -10
.2byte    0,   -2, 	 -10,   -6, 	   9,   -8, 	   0,  -10
.2byte   -1,  -17, 	  -8,   -5, 	   6,   -5, 	  -1,  -10
.2byte   -1,   -2, 	 -11,   -4, 	   9,   -4, 	  -1,   -8
.2byte    8,   -4, 	  10,  -12, 	  -7,   -2, 	   0,   -9
.2byte    9,   -4, 	   8,  -13, 	  -4,   -2, 	   1,   -9
.2byte    6,   -3, 	   9,   -9, 	  -7,   -3, 	   1,   -9
.2byte    3,  -14, 	   8,   -5, 	   1,   -3, 	   0,   -8
.2byte    4,   -2, 	   8,   -6, 	  -5,    0, 	   1,   -7
.2byte    8,   -7, 	   3,   -6, 	   1,   -1, 	   1,   -9
.2byte    9,   -7, 	   3,   -6, 	   3,   -2, 	   1,   -9
.2byte    8,   -7, 	   1,   -5, 	   0,   -1, 	   1,   -9
.2byte    4,  -16, 	   4,  -11, 	   6,   -4, 	  -1,   -9
.2byte    4,   -4, 	   3,   -7, 	   0,    0, 	   0,   -8
.2byte    5,  -15, 	  -9,  -13, 	   9,   -4, 	   0,  -10
.2byte    3,  -16, 	 -10,  -11, 	   8,   -6, 	  -1,  -11
.2byte    6,  -14, 	  -7,  -14, 	   7,   -4, 	   1,  -11
.2byte    3,  -16, 	  -7,   -9, 	   6,   -4, 	   0,  -10
.2byte    4,   -8, 	  -2,  -11, 	   4,   -3, 	   0,  -10
.2byte   -1,   -9, 	  10,   -8, 	 -12,   -8, 	  -1,  -10
.2byte   -1,  -10, 	   9,   -8, 	 -10,   -9, 	   0,  -11
.2byte    0,  -10, 	   8,   -9, 	 -11,   -8, 	  -1,  -11
.2byte   -1,  -18, 	   7,   -5, 	  -9,   -5, 	  -1,  -11
.2byte   -1,  -10, 	   9,   -6, 	 -11,   -6, 	  -1,  -12
.2byte   -7,  -15, 	   7,  -13, 	 -11,   -4, 	  -2,  -10
.2byte   -5,  -16, 	   8,  -11, 	 -10,   -6, 	  -1,  -11
.2byte   -8,  -14, 	   5,  -14, 	  -9,   -4, 	  -3,  -11
.2byte   -4,  -16, 	   6,   -9, 	  -7,   -4, 	  -1,  -10
.2byte   -5,   -8, 	   1,  -11, 	  -5,   -3, 	  -1,  -10
.2byte  -10,   -7, 	  -5,   -6, 	  -3,   -1, 	  -3,   -9
.2byte  -11,   -7, 	  -5,   -6, 	  -5,   -2, 	  -3,   -9
.2byte  -10,   -7, 	  -3,   -5, 	  -2,   -1, 	  -3,   -9
.2byte   -6,  -16, 	  -6,  -11, 	  -8,   -4, 	  -1,   -9
.2byte   -6,   -4, 	  -5,   -7, 	  -2,    0, 	  -2,   -8
.2byte  -10,   -4, 	 -12,  -12, 	   5,   -2, 	  -2,   -9
.2byte  -11,   -4, 	 -10,  -13, 	   2,   -2, 	  -3,   -9
.2byte   -8,   -3, 	 -11,   -9, 	   5,   -3, 	  -3,   -9
.2byte   -4,  -14, 	  -9,   -5, 	  -2,   -3, 	  -1,   -8
.2byte   -5,   -2, 	  -9,   -6, 	   4,    0, 	  -2,   -7
.2byte   -1,   -2, 	 -12,   -7, 	  10,   -7, 	  -1,  -10
.2byte  -10,   -4, 	 -12,  -12, 	   5,   -2, 	  -2,   -9
.2byte  -10,   -7, 	  -5,   -6, 	  -3,   -1, 	  -3,   -9
.2byte   -7,  -15, 	   7,  -13, 	 -11,   -4, 	  -2,  -10
.2byte   -1,   -9, 	  10,   -8, 	 -12,   -8, 	  -1,  -10
.2byte    5,  -15, 	  -9,  -13, 	   9,   -4, 	   0,  -10
.2byte    8,   -7, 	   3,   -6, 	   1,   -1, 	   1,   -9
.2byte    8,   -4, 	  10,  -12, 	  -7,   -2, 	   0,   -9
.2byte   -6,   -3, 	  -4,  -12, 	   4,   -6, 	  -3,   -8
.2byte   -5,   -3, 	  -4,  -12, 	   4,   -6, 	  -3,   -8
.2byte    0,   -3, 	 -10,  -14, 	  10,  -14, 	   0,  -12
.2byte    4,   -3, 	   8,  -13, 	  -8,   -9, 	   0,  -10
.2byte    5,   -7, 	  -2,  -12, 	  -3,   -6, 	  -1,  -11
.2byte    4,  -12, 	  -7,  -12, 	   2,   -4, 	  -1,  -11
.2byte    0,   -9, 	  10,   -7, 	 -10,   -7, 	   0,  -10
.2byte   -5,  -12, 	   6,  -12, 	  -3,   -4, 	   0,  -11
.2byte   -6,   -7, 	   1,  -12, 	   2,   -6, 	   0,  -11
.2byte   -5,   -3, 	  -9,  -13, 	   7,   -9, 	  -1,  -10
.2byte   -1,   -2, 	 -12,   -7, 	  10,   -7, 	  -1,  -10
.2byte   -2,   -2, 	 -11,   -8, 	   8,   -6, 	  -1,  -10
.2byte    0,   -2, 	 -10,   -6, 	   9,   -8, 	   0,  -10
.2byte    8,   -4, 	  10,  -12, 	  -7,   -2, 	   0,   -9
.2byte    9,   -4, 	   8,  -13, 	  -4,   -2, 	   1,   -9
.2byte    6,   -3, 	   9,   -9, 	  -7,   -3, 	   1,   -9
.2byte    8,   -7, 	   3,   -6, 	   1,   -1, 	   1,   -9
.2byte    9,   -7, 	   3,   -6, 	   3,   -2, 	   1,   -9
.2byte    8,   -7, 	   1,   -5, 	   0,   -1, 	   1,   -9
.2byte    5,  -15, 	  -9,  -13, 	   9,   -4, 	   0,  -10
.2byte    3,  -16, 	 -10,  -11, 	   8,   -6, 	  -1,  -11
.2byte    6,  -14, 	  -7,  -14, 	   7,   -4, 	   1,  -11
.2byte   -1,   -9, 	  10,   -8, 	 -12,   -8, 	  -1,  -10
.2byte   -1,  -10, 	   9,   -8, 	 -10,   -9, 	   0,  -11
.2byte    0,  -10, 	   8,   -9, 	 -11,   -8, 	  -1,  -11
.2byte   -7,  -15, 	   7,  -13, 	 -11,   -4, 	  -2,  -10
.2byte   -5,  -16, 	   8,  -11, 	 -10,   -6, 	  -1,  -11
.2byte   -8,  -14, 	   5,  -14, 	  -9,   -4, 	  -3,  -11
.2byte  -10,   -7, 	  -5,   -6, 	  -3,   -1, 	  -3,   -9
.2byte  -11,   -7, 	  -5,   -6, 	  -5,   -2, 	  -3,   -9
.2byte  -10,   -7, 	  -3,   -5, 	  -2,   -1, 	  -3,   -9
.2byte  -10,   -4, 	 -12,  -12, 	   5,   -2, 	  -2,   -9
.2byte  -11,   -4, 	 -10,  -13, 	   2,   -2, 	  -3,   -9
.2byte   -8,   -3, 	 -11,   -9, 	   5,   -3, 	  -3,   -9
.2byte   -1,   -2, 	 -12,   -7, 	  10,   -7, 	  -1,  -10
.2byte  -10,   -4, 	 -12,  -12, 	   5,   -2, 	  -2,   -9
.2byte  -10,   -7, 	  -5,   -6, 	  -3,   -1, 	  -3,   -9
.2byte   -7,  -15, 	   7,  -13, 	 -11,   -4, 	  -2,  -10
.2byte   -1,   -9, 	  10,   -8, 	 -12,   -8, 	  -1,  -10
.2byte    5,  -15, 	  -9,  -13, 	   9,   -4, 	   0,  -10
.2byte    8,   -7, 	   3,   -6, 	   1,   -1, 	   1,   -9
.2byte    8,   -4, 	  10,  -12, 	  -7,   -2, 	   0,   -9
.2byte   -1,  -16, 	  -8,   -4, 	   6,   -4, 	  -1,   -9
.2byte    3,  -15, 	   8,   -6, 	   1,   -4, 	   0,   -9
.2byte    5,  -16, 	   5,  -11, 	   7,   -4, 	   0,   -9
.2byte    3,  -16, 	  -7,   -9, 	   6,   -4, 	   0,  -10
.2byte   -1,  -17, 	   7,   -4, 	  -9,   -4, 	  -1,  -10
.2byte   -4,  -16, 	   6,   -9, 	  -7,   -4, 	  -1,  -10
.2byte   -7,  -16, 	  -7,  -11, 	  -9,   -4, 	  -2,   -9
.2byte   -4,  -15, 	  -9,   -6, 	  -2,   -4, 	  -1,   -9
.2byte   -1,   -2, 	 -12,   -7, 	  10,   -7, 	  -1,  -10
.2byte   -1,  -17, 	  -8,   -5, 	   6,   -5, 	  -1,  -10
.2byte   -1,   -2, 	 -11,   -4, 	   9,   -4, 	  -1,   -8
.2byte    8,   -4, 	  10,  -12, 	  -7,   -2, 	   0,   -9
.2byte    3,  -14, 	   8,   -5, 	   1,   -3, 	   0,   -8
.2byte    4,   -2, 	   8,   -6, 	  -5,    0, 	   1,   -7
.2byte    8,   -7, 	   3,   -6, 	   1,   -1, 	   1,   -9
.2byte    4,  -16, 	   4,  -11, 	   6,   -4, 	  -1,   -9
.2byte    4,   -4, 	   3,   -7, 	   0,    0, 	   0,   -8
.2byte    5,  -15, 	  -9,  -13, 	   9,   -4, 	   0,  -10
.2byte    3,  -16, 	  -7,   -9, 	   6,   -4, 	   0,  -10
.2byte    4,   -8, 	  -2,  -11, 	   4,   -3, 	   0,  -10
.2byte   -1,   -9, 	  10,   -8, 	 -12,   -8, 	  -1,  -10
.2byte   -1,  -18, 	   7,   -5, 	  -9,   -5, 	  -1,  -11
.2byte   -1,  -10, 	   9,   -6, 	 -11,   -6, 	  -1,  -12
.2byte   -7,  -15, 	   7,  -13, 	 -11,   -4, 	  -2,  -10
.2byte   -4,  -16, 	   6,   -9, 	  -7,   -4, 	  -1,  -10
.2byte   -5,   -8, 	   1,  -11, 	  -5,   -3, 	  -1,  -10
.2byte  -10,   -7, 	  -5,   -6, 	  -3,   -1, 	  -3,   -9
.2byte   -6,  -16, 	  -6,  -11, 	  -8,   -4, 	  -1,   -9
.2byte   -6,   -4, 	  -5,   -7, 	  -2,    0, 	  -2,   -8
.2byte  -10,   -4, 	 -12,  -12, 	   5,   -2, 	  -2,   -9
.2byte   -4,  -14, 	  -9,   -5, 	  -2,   -3, 	  -1,   -8
.2byte   -5,   -2, 	  -9,   -6, 	   4,    0, 	  -2,   -7
.2byte   -1,   -2, 	 -11,   -4, 	   9,   -4, 	  -1,   -8
.2byte   -4,   -4, 	  -8,   -8, 	   5,   -2, 	  -1,   -9
.2byte   -5,   -5, 	  -4,   -8, 	  -1,   -1, 	  -1,   -9
.2byte   -4,   -7, 	   2,  -10, 	  -4,   -2, 	   0,   -9
.2byte   -1,   -8, 	   9,   -4, 	 -11,   -4, 	  -1,  -10
.2byte    3,   -7, 	  -3,  -10, 	   3,   -2, 	  -1,   -9
.2byte    3,   -5, 	   2,   -8, 	  -1,   -1, 	  -1,   -9
.2byte    3,   -4, 	   7,   -8, 	  -6,   -2, 	   0,   -9
.2byte   -1,   -2, 	 -12,   -7, 	  10,   -7, 	  -1,  -10
.2byte  -10,   -4, 	 -12,  -12, 	   5,   -2, 	  -2,   -9
.2byte  -10,   -7, 	  -5,   -6, 	  -3,   -1, 	  -3,   -9
.2byte   -7,  -15, 	   7,  -13, 	 -11,   -4, 	  -2,  -10
.2byte   -1,   -9, 	  10,   -8, 	 -12,   -8, 	  -1,  -10
.2byte    5,  -15, 	  -9,  -13, 	   9,   -4, 	   0,  -10
.2byte    8,   -7, 	   3,   -6, 	   1,   -1, 	   1,   -9
.2byte    8,   -4, 	  10,  -12, 	  -7,   -2, 	   0,   -9
sLanturnAnimTable1:
.4byte sLanturnAnims_1_1
.4byte sLanturnAnims_1_2
.4byte sLanturnAnims_1_3
.4byte sLanturnAnims_1_4
.4byte sLanturnAnims_1_5
.4byte sLanturnAnims_1_6
.4byte sLanturnAnims_1_7
.4byte sLanturnAnims_1_8
sLanturnAnimTable2:
.4byte sLanturnAnims_2_1
.4byte sLanturnAnims_2_2
.4byte sLanturnAnims_2_3
.4byte sLanturnAnims_2_4
.4byte sLanturnAnims_2_5
.4byte sLanturnAnims_2_6
.4byte sLanturnAnims_2_7
.4byte sLanturnAnims_2_8
sLanturnAnimTable3:
.4byte sLanturnAnims_3_1
.4byte sLanturnAnims_3_2
.4byte sLanturnAnims_3_3
.4byte sLanturnAnims_3_4
.4byte sLanturnAnims_3_5
.4byte sLanturnAnims_3_6
.4byte sLanturnAnims_3_7
.4byte sLanturnAnims_3_8
sLanturnAnimTable4:
.4byte sLanturnAnims_4_1
.4byte sLanturnAnims_4_2
.4byte sLanturnAnims_4_3
.4byte sLanturnAnims_4_4
.4byte sLanturnAnims_4_5
.4byte sLanturnAnims_4_6
.4byte sLanturnAnims_4_7
.4byte sLanturnAnims_4_8
sLanturnAnimTable5:
.4byte sLanturnAnims_5_1
.4byte sLanturnAnims_5_2
.4byte sLanturnAnims_5_3
.4byte sLanturnAnims_5_4
.4byte sLanturnAnims_5_5
.4byte sLanturnAnims_5_6
.4byte sLanturnAnims_5_7
.4byte sLanturnAnims_5_8
sLanturnAnimTable6:
.4byte sLanturnAnims_6_1
.4byte sLanturnAnims_6_1
.4byte sLanturnAnims_6_1
.4byte sLanturnAnims_6_1
.4byte sLanturnAnims_6_1
.4byte sLanturnAnims_6_1
.4byte sLanturnAnims_6_1
.4byte sLanturnAnims_6_1
sLanturnAnimTable7:
.4byte sLanturnAnims_7_1
.4byte sLanturnAnims_7_2
.4byte sLanturnAnims_7_3
.4byte sLanturnAnims_7_4
.4byte sLanturnAnims_7_5
.4byte sLanturnAnims_7_6
.4byte sLanturnAnims_7_7
.4byte sLanturnAnims_7_8
sLanturnAnimTable8:
.4byte sLanturnAnims_8_1
.4byte sLanturnAnims_8_2
.4byte sLanturnAnims_8_3
.4byte sLanturnAnims_8_4
.4byte sLanturnAnims_8_5
.4byte sLanturnAnims_8_6
.4byte sLanturnAnims_8_7
.4byte sLanturnAnims_8_8
sLanturnAnimTable9:
.4byte sLanturnAnims_9_1
.4byte sLanturnAnims_9_2
.4byte sLanturnAnims_9_3
.4byte sLanturnAnims_9_4
.4byte sLanturnAnims_9_5
.4byte sLanturnAnims_9_6
.4byte sLanturnAnims_9_7
.4byte sLanturnAnims_9_8
sLanturnAnimTable10:
.4byte sLanturnAnims_10_1
.4byte sLanturnAnims_10_2
.4byte sLanturnAnims_10_3
.4byte sLanturnAnims_10_4
.4byte sLanturnAnims_10_5
.4byte sLanturnAnims_10_6
.4byte sLanturnAnims_10_7
.4byte sLanturnAnims_10_8
sLanturnAnimTable11:
.4byte sLanturnAnims_11_1
.4byte sLanturnAnims_11_2
.4byte sLanturnAnims_11_3
.4byte sLanturnAnims_11_4
.4byte sLanturnAnims_11_5
.4byte sLanturnAnims_11_6
.4byte sLanturnAnims_11_7
.4byte sLanturnAnims_11_8
sLanturnAnimTable12:
.4byte sLanturnAnims_12_1
.4byte sLanturnAnims_12_2
.4byte sLanturnAnims_12_3
.4byte sLanturnAnims_12_4
.4byte sLanturnAnims_12_5
.4byte sLanturnAnims_12_6
.4byte sLanturnAnims_12_7
.4byte sLanturnAnims_12_8
sLanturnAnimTable13:
.4byte sLanturnAnims_13_1
.4byte sLanturnAnims_13_2
.4byte sLanturnAnims_13_3
.4byte sLanturnAnims_13_4
.4byte sLanturnAnims_13_5
.4byte sLanturnAnims_13_6
.4byte sLanturnAnims_13_7
.4byte sLanturnAnims_13_8
sAxAnimationsLanturn:
.4byte sLanturnAnimTable1
.4byte sLanturnAnimTable2
.4byte sLanturnAnimTable3
.4byte sLanturnAnimTable4
.4byte sLanturnAnimTable5
.4byte sLanturnAnimTable6
.4byte sLanturnAnimTable7
.4byte sLanturnAnimTable8
.4byte sLanturnAnimTable9
.4byte sLanturnAnimTable10
.4byte sLanturnAnimTable11
.4byte sLanturnAnimTable12
.4byte sLanturnAnimTable13
sAxSpritesLanturn:
.4byte sLanturnSprites1
.4byte sLanturnSprites2
.4byte sLanturnSprites3
.4byte sLanturnSprites4
.4byte sLanturnSprites5
.4byte sLanturnSprites6
.4byte sLanturnSprites7
.4byte sLanturnSprites8
.4byte sLanturnSprites9
.4byte sLanturnSprites10
.4byte sLanturnSprites11
.4byte sLanturnSprites12
.4byte sLanturnSprites13
.4byte sLanturnSprites14
.4byte sLanturnSprites15
.4byte sLanturnSprites16
.4byte sLanturnSprites17
.4byte sLanturnSprites18
.4byte sLanturnSprites19
.4byte sLanturnSprites20
.4byte sLanturnSprites21
.4byte sLanturnSprites22
.4byte sLanturnSprites23
.4byte sLanturnSprites24
.4byte sLanturnSprites25
.4byte sLanturnSprites26
.4byte sLanturnSprites27
.4byte sLanturnSprites28
.4byte sLanturnSprites29
.4byte sLanturnSprites30
.4byte sLanturnSprites31
.4byte sLanturnSprites32
sAxMainLanturn:
ax_main sAxPosesLanturn, sAxAnimationsLanturn, 13, sAxSpritesLanturn, sAxPositionsLanturn
