.global gAxLombre
gAxLombre:
ax_siro sAxMainLombre
sLombrePose1:
ax_pose 0, 0x01e6, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose2:
ax_pose 1, 0x01e6, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose3:
ax_pose 2, 0x01e6, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose4:
ax_pose 3, 0x01e6, 0x80ef, 0x3c00
ax_pose_terminator
sLombrePose5:
ax_pose 4, 0x01e6, 0x80ef, 0x3c00
ax_pose_terminator
sLombrePose6:
ax_pose 5, 0x01e6, 0x80ef, 0x3c00
ax_pose_terminator
sLombrePose7:
ax_pose 6, 0x01e6, 0x80ef, 0x3c00
ax_pose_terminator
sLombrePose8:
ax_pose 7, 0x01e6, 0x80ef, 0x3c00
ax_pose_terminator
sLombrePose9:
ax_pose 8, 0x01e6, 0x80ef, 0x3c00
ax_pose_terminator
sLombrePose10:
ax_pose 9, 0x01e6, 0x80ef, 0x3c00
ax_pose_terminator
sLombrePose11:
ax_pose 10, 0x01e6, 0x80ef, 0x3c00
ax_pose_terminator
sLombrePose12:
ax_pose 11, 0x01e6, 0x80ef, 0x3c00
ax_pose_terminator
sLombrePose13:
ax_pose 12, 0x01e6, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose14:
ax_pose 13, 0x01e6, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose15:
ax_pose 14, 0x01e6, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose16:
ax_pose 15, 0x01e6, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose17:
ax_pose 16, 0x01e6, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose18:
ax_pose 17, 0x01e6, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose19:
ax_pose 18, 0x01e6, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose20:
ax_pose 19, 0x01e6, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose21:
ax_pose 20, 0x01e6, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose22:
ax_pose 21, 0x01e6, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose23:
ax_pose 22, 0x01e6, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose24:
ax_pose 23, 0x01e6, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose25:
ax_pose 24, 0x01e5, 0x80ed, 0x3c00
ax_pose_terminator
sLombrePose26:
ax_pose 1, 0x01e6, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose27:
ax_pose 2, 0x01e6, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose28:
ax_pose 25, 0x01e5, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose29:
ax_pose 4, 0x01e5, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose30:
ax_pose 5, 0x01e6, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose31:
ax_pose 26, 0x01e6, 0x80ed, 0x3c00
ax_pose_terminator
sLombrePose32:
ax_pose 7, 0x01e6, 0x80ef, 0x3c00
ax_pose_terminator
sLombrePose33:
ax_pose 8, 0x01e6, 0x80ef, 0x3c00
ax_pose_terminator
sLombrePose34:
ax_pose 27, 0x01e6, 0x80ef, 0x3c00
ax_pose_terminator
sLombrePose35:
ax_pose 10, 0x01e6, 0x80ef, 0x3c00
ax_pose_terminator
sLombrePose36:
ax_pose 11, 0x01e6, 0x80ef, 0x3c00
ax_pose_terminator
sLombrePose37:
ax_pose 28, 0x01e9, 0x80f2, 0x3c00
ax_pose_terminator
sLombrePose38:
ax_pose 13, 0x01e6, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose39:
ax_pose 14, 0x01e6, 0x80f1, 0x3c00
ax_pose_terminator
sLombrePose40:
ax_pose 29, 0x01e6, 0x80f1, 0x3c00
ax_pose_terminator
sLombrePose41:
ax_pose 16, 0x01e6, 0x80f1, 0x3c00
ax_pose_terminator
sLombrePose42:
ax_pose 17, 0x01e6, 0x80f1, 0x3c00
ax_pose_terminator
sLombrePose43:
ax_pose 30, 0x01e6, 0x80f3, 0x3c00
ax_pose_terminator
sLombrePose44:
ax_pose 19, 0x01e6, 0x80f1, 0x3c00
ax_pose_terminator
sLombrePose45:
ax_pose 20, 0x01e6, 0x80f1, 0x3c00
ax_pose_terminator
sLombrePose46:
ax_pose 31, 0x01e5, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose47:
ax_pose 22, 0x01e5, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose48:
ax_pose 23, 0x01e6, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose49:
ax_pose 0, 0x01e6, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose50:
ax_pose 32, 0x41f6, 0x80f0, 0x3c00
ax_pose 24, 0x01e6, 0x80f0, 0x3c08
ax_pose_terminator
sLombrePose51:
ax_pose 24, 0x01e6, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose52:
ax_pose 33, 0x41f6, 0x80f0, 0x3c00
ax_pose 34, 0x01e6, 0x80f0, 0x3c08
ax_pose_terminator
sLombrePose53:
ax_pose 34, 0x01e6, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose54:
ax_pose 3, 0x01e6, 0x80ef, 0x3c00
ax_pose_terminator
sLombrePose55:
ax_pose 35, 0x41f6, 0x90ef, 0x3c00
ax_pose 25, 0x01e6, 0x80ef, 0x3c08
ax_pose_terminator
sLombrePose56:
ax_pose 25, 0x01e6, 0x80ef, 0x3c00
ax_pose_terminator
sLombrePose57:
ax_pose 36, 0x41f6, 0x90ef, 0x3c00
ax_pose 37, 0x01e6, 0x80ef, 0x3c08
ax_pose_terminator
sLombrePose58:
ax_pose 37, 0x01e6, 0x80ef, 0x3c00
ax_pose_terminator
sLombrePose59:
ax_pose 6, 0x01e6, 0x80ef, 0x3c00
ax_pose_terminator
sLombrePose60:
ax_pose 38, 0x41f6, 0x90f1, 0x3c00
ax_pose 26, 0x01e6, 0x80ef, 0x3c08
ax_pose_terminator
sLombrePose61:
ax_pose 26, 0x01e6, 0x80ef, 0x3c00
ax_pose_terminator
sLombrePose62:
ax_pose 39, 0x41f6, 0x90f1, 0x3c00
ax_pose 40, 0x01e6, 0x80ef, 0x3c08
ax_pose_terminator
sLombrePose63:
ax_pose 40, 0x01e6, 0x80ef, 0x3c00
ax_pose_terminator
sLombrePose64:
ax_pose 9, 0x01e6, 0x80ef, 0x3c00
ax_pose_terminator
sLombrePose65:
ax_pose 41, 0x41ee, 0x90ef, 0x3c00
ax_pose 27, 0x01e6, 0x80ef, 0x3c08
ax_pose_terminator
sLombrePose66:
ax_pose 27, 0x01e6, 0x80ef, 0x3c00
ax_pose_terminator
sLombrePose67:
ax_pose 42, 0x01ee, 0x50ff, 0x3c00
ax_pose 43, 0x01e6, 0x80ef, 0x3c04
ax_pose_terminator
sLombrePose68:
ax_pose 43, 0x01e6, 0x80ef, 0x3c00
ax_pose_terminator
sLombrePose69:
ax_pose 12, 0x01e6, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose70:
ax_pose 44, 0x41ee, 0x80f0, 0x3c00
ax_pose 28, 0x01e6, 0x80f0, 0x3c08
ax_pose_terminator
sLombrePose71:
ax_pose 28, 0x01e6, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose72:
ax_pose 45, 0x41ee, 0x80f0, 0x3c00
ax_pose 46, 0x01e6, 0x80f0, 0x3c08
ax_pose_terminator
sLombrePose73:
ax_pose 46, 0x01e6, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose74:
ax_pose 15, 0x01e6, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose75:
ax_pose 41, 0x41ee, 0x80f0, 0x3c00
ax_pose 29, 0x01e6, 0x80f0, 0x3c08
ax_pose_terminator
sLombrePose76:
ax_pose 29, 0x01e6, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose77:
ax_pose 42, 0x01ee, 0x40f0, 0x3c00
ax_pose 47, 0x01e6, 0x80f0, 0x3c04
ax_pose_terminator
sLombrePose78:
ax_pose 47, 0x01e6, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose79:
ax_pose 18, 0x01e6, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose80:
ax_pose 38, 0x41f6, 0x80ee, 0x3c00
ax_pose 30, 0x01e6, 0x80f0, 0x3c08
ax_pose_terminator
sLombrePose81:
ax_pose 30, 0x01e6, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose82:
ax_pose 39, 0x41f6, 0x80ee, 0x3c00
ax_pose 48, 0x01e6, 0x80f0, 0x3c08
ax_pose_terminator
sLombrePose83:
ax_pose 48, 0x01e6, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose84:
ax_pose 21, 0x01e6, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose85:
ax_pose 35, 0x41f6, 0x80f0, 0x3c00
ax_pose 31, 0x01e6, 0x80f0, 0x3c08
ax_pose_terminator
sLombrePose86:
ax_pose 31, 0x01e6, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose87:
ax_pose 36, 0x41f6, 0x80f0, 0x3c00
ax_pose 49, 0x01e6, 0x80f0, 0x3c08
ax_pose_terminator
sLombrePose88:
ax_pose 49, 0x01e6, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose89:
ax_pose 0, 0x01e6, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose90:
ax_pose 50, 0x01e6, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose91:
ax_pose 3, 0x01e6, 0x80ef, 0x3c00
ax_pose_terminator
sLombrePose92:
ax_pose 51, 0x01e4, 0x80ef, 0x3c00
ax_pose_terminator
sLombrePose93:
ax_pose 6, 0x01e6, 0x80ef, 0x3c00
ax_pose_terminator
sLombrePose94:
ax_pose 52, 0x01e6, 0x80ef, 0x3c00
ax_pose_terminator
sLombrePose95:
ax_pose 9, 0x01e6, 0x80ef, 0x3c00
ax_pose_terminator
sLombrePose96:
ax_pose 53, 0x01e6, 0x80ef, 0x3c00
ax_pose_terminator
sLombrePose97:
ax_pose 12, 0x01e6, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose98:
ax_pose 54, 0x01e6, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose99:
ax_pose 15, 0x01e6, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose100:
ax_pose 55, 0x01e6, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose101:
ax_pose 18, 0x01e6, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose102:
ax_pose 56, 0x01e6, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose103:
ax_pose 21, 0x01e6, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose104:
ax_pose 57, 0x01e4, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose105:
ax_pose 0, 0x01e6, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose106:
ax_pose 32, 0x41f6, 0x80f0, 0x3c00
ax_pose 24, 0x01e6, 0x80f0, 0x3c08
ax_pose_terminator
sLombrePose107:
ax_pose 24, 0x01e6, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose108:
ax_pose 33, 0x41f6, 0x80f0, 0x3c00
ax_pose 34, 0x01e6, 0x80f0, 0x3c08
ax_pose_terminator
sLombrePose109:
ax_pose 34, 0x01e6, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose110:
ax_pose 3, 0x01e6, 0x80ef, 0x3c00
ax_pose_terminator
sLombrePose111:
ax_pose 35, 0x41f6, 0x90ef, 0x3c00
ax_pose 25, 0x01e6, 0x80ef, 0x3c08
ax_pose_terminator
sLombrePose112:
ax_pose 25, 0x01e6, 0x80ef, 0x3c00
ax_pose_terminator
sLombrePose113:
ax_pose 36, 0x41f6, 0x90ef, 0x3c00
ax_pose 37, 0x01e6, 0x80ef, 0x3c08
ax_pose_terminator
sLombrePose114:
ax_pose 37, 0x01e6, 0x80ef, 0x3c00
ax_pose_terminator
sLombrePose115:
ax_pose 6, 0x01e6, 0x80ef, 0x3c00
ax_pose_terminator
sLombrePose116:
ax_pose 38, 0x41f6, 0x90f1, 0x3c00
ax_pose 26, 0x01e6, 0x80ef, 0x3c08
ax_pose_terminator
sLombrePose117:
ax_pose 26, 0x01e6, 0x80ef, 0x3c00
ax_pose_terminator
sLombrePose118:
ax_pose 39, 0x41f6, 0x90f1, 0x3c00
ax_pose 40, 0x01e6, 0x80ef, 0x3c08
ax_pose_terminator
sLombrePose119:
ax_pose 40, 0x01e6, 0x80ef, 0x3c00
ax_pose_terminator
sLombrePose120:
ax_pose 9, 0x01e6, 0x80ef, 0x3c00
ax_pose_terminator
sLombrePose121:
ax_pose 41, 0x41ee, 0x90ef, 0x3c00
ax_pose 27, 0x01e6, 0x80ef, 0x3c08
ax_pose_terminator
sLombrePose122:
ax_pose 27, 0x01e6, 0x80ef, 0x3c00
ax_pose_terminator
sLombrePose123:
ax_pose 42, 0x01ee, 0x50ff, 0x3c00
ax_pose 43, 0x01e6, 0x80ef, 0x3c04
ax_pose_terminator
sLombrePose124:
ax_pose 43, 0x01e6, 0x80ef, 0x3c00
ax_pose_terminator
sLombrePose125:
ax_pose 12, 0x01e6, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose126:
ax_pose 44, 0x41ee, 0x80f0, 0x3c00
ax_pose 28, 0x01e6, 0x80f0, 0x3c08
ax_pose_terminator
sLombrePose127:
ax_pose 28, 0x01e6, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose128:
ax_pose 45, 0x41ee, 0x80f0, 0x3c00
ax_pose 46, 0x01e6, 0x80f0, 0x3c08
ax_pose_terminator
sLombrePose129:
ax_pose 46, 0x01e6, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose130:
ax_pose 15, 0x01e6, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose131:
ax_pose 41, 0x41ee, 0x80f0, 0x3c00
ax_pose 29, 0x01e6, 0x80f0, 0x3c08
ax_pose_terminator
sLombrePose132:
ax_pose 29, 0x01e6, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose133:
ax_pose 42, 0x01ee, 0x40f0, 0x3c00
ax_pose 47, 0x01e6, 0x80f0, 0x3c04
ax_pose_terminator
sLombrePose134:
ax_pose 47, 0x01e6, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose135:
ax_pose 18, 0x01e6, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose136:
ax_pose 38, 0x41f6, 0x80ee, 0x3c00
ax_pose 30, 0x01e6, 0x80f0, 0x3c08
ax_pose_terminator
sLombrePose137:
ax_pose 30, 0x01e6, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose138:
ax_pose 39, 0x41f6, 0x80ee, 0x3c00
ax_pose 48, 0x01e6, 0x80f0, 0x3c08
ax_pose_terminator
sLombrePose139:
ax_pose 48, 0x01e6, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose140:
ax_pose 21, 0x01e6, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose141:
ax_pose 35, 0x41f6, 0x80f0, 0x3c00
ax_pose 31, 0x01e6, 0x80f0, 0x3c08
ax_pose_terminator
sLombrePose142:
ax_pose 31, 0x01e6, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose143:
ax_pose 36, 0x41f6, 0x80f0, 0x3c00
ax_pose 49, 0x01e6, 0x80f0, 0x3c08
ax_pose_terminator
sLombrePose144:
ax_pose 49, 0x01e6, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose145:
ax_pose 58, 0x01ea, 0x80f1, 0x3c00
ax_pose_terminator
sLombrePose146:
ax_pose 59, 0x01ea, 0x80f1, 0x3c00
ax_pose_terminator
sLombrePose147:
ax_pose 60, 0x01e0, 0x80f1, 0x3c00
ax_pose_terminator
sLombrePose148:
ax_pose 61, 0x01e4, 0x80ed, 0x3c00
ax_pose_terminator
sLombrePose149:
ax_pose 62, 0x01e3, 0x80ec, 0x3c00
ax_pose_terminator
sLombrePose150:
ax_pose 63, 0x01e3, 0x80eb, 0x3c00
ax_pose_terminator
sLombrePose151:
ax_pose 64, 0x01e0, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose152:
ax_pose 65, 0x01e3, 0x80f5, 0x3c00
ax_pose_terminator
sLombrePose153:
ax_pose 66, 0x01e3, 0x80f5, 0x3c00
ax_pose_terminator
sLombrePose154:
ax_pose 67, 0x01e4, 0x80f3, 0x3c00
ax_pose_terminator
sLombrePose155:
ax_pose 0, 0x01e6, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose156:
ax_pose 50, 0x01e6, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose157:
ax_pose 3, 0x01e6, 0x80ef, 0x3c00
ax_pose_terminator
sLombrePose158:
ax_pose 51, 0x01e4, 0x80ed, 0x3c00
ax_pose_terminator
sLombrePose159:
ax_pose 6, 0x01e6, 0x80ef, 0x3c00
ax_pose_terminator
sLombrePose160:
ax_pose 52, 0x01e6, 0x80ee, 0x3c00
ax_pose_terminator
sLombrePose161:
ax_pose 9, 0x01e6, 0x80ef, 0x3c00
ax_pose_terminator
sLombrePose162:
ax_pose 53, 0x01e6, 0x80ee, 0x3c00
ax_pose_terminator
sLombrePose163:
ax_pose 12, 0x01e6, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose164:
ax_pose 54, 0x01e6, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose165:
ax_pose 15, 0x01e6, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose166:
ax_pose 55, 0x01e6, 0x80f1, 0x3c00
ax_pose_terminator
sLombrePose167:
ax_pose 18, 0x01e6, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose168:
ax_pose 56, 0x01e6, 0x80f1, 0x3c00
ax_pose_terminator
sLombrePose169:
ax_pose 21, 0x01e6, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose170:
ax_pose 57, 0x01e4, 0x80f2, 0x3c00
ax_pose_terminator
sLombrePose171:
ax_pose 50, 0x01e5, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose172:
ax_pose 57, 0x01e4, 0x80f2, 0x3c00
ax_pose_terminator
sLombrePose173:
ax_pose 56, 0x01e5, 0x80f2, 0x3c00
ax_pose_terminator
sLombrePose174:
ax_pose 55, 0x01e7, 0x80f2, 0x3c00
ax_pose_terminator
sLombrePose175:
ax_pose 54, 0x01e8, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose176:
ax_pose 53, 0x01e7, 0x80ed, 0x3c00
ax_pose_terminator
sLombrePose177:
ax_pose 52, 0x01e5, 0x80ed, 0x3c00
ax_pose_terminator
sLombrePose178:
ax_pose 51, 0x01e4, 0x80ed, 0x3c00
ax_pose_terminator
sLombrePose179:
ax_pose 50, 0x01e5, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose180:
ax_pose 51, 0x01e4, 0x80ed, 0x3c00
ax_pose_terminator
sLombrePose181:
ax_pose 52, 0x01e5, 0x80ed, 0x3c00
ax_pose_terminator
sLombrePose182:
ax_pose 53, 0x01e7, 0x80ed, 0x3c00
ax_pose_terminator
sLombrePose183:
ax_pose 54, 0x01e8, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose184:
ax_pose 55, 0x01e7, 0x80f2, 0x3c00
ax_pose_terminator
sLombrePose185:
ax_pose 56, 0x01e5, 0x80f2, 0x3c00
ax_pose_terminator
sLombrePose186:
ax_pose 57, 0x01e4, 0x80f2, 0x3c00
ax_pose_terminator
sLombrePose187:
ax_pose 0, 0x01e6, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose188:
ax_pose 50, 0x01e7, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose189:
ax_pose 3, 0x01e6, 0x80ef, 0x3c00
ax_pose_terminator
sLombrePose190:
ax_pose 51, 0x01e4, 0x80ed, 0x3c00
ax_pose_terminator
sLombrePose191:
ax_pose 6, 0x01e6, 0x80ef, 0x3c00
ax_pose_terminator
sLombrePose192:
ax_pose 52, 0x01e6, 0x80ec, 0x3c00
ax_pose_terminator
sLombrePose193:
ax_pose 9, 0x01e6, 0x80ef, 0x3c00
ax_pose_terminator
sLombrePose194:
ax_pose 53, 0x01e6, 0x80ec, 0x3c00
ax_pose_terminator
sLombrePose195:
ax_pose 12, 0x01e6, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose196:
ax_pose 54, 0x01e7, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose197:
ax_pose 15, 0x01e6, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose198:
ax_pose 55, 0x01e6, 0x80f3, 0x3c00
ax_pose_terminator
sLombrePose199:
ax_pose 18, 0x01e6, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose200:
ax_pose 56, 0x01e6, 0x80f3, 0x3c00
ax_pose_terminator
sLombrePose201:
ax_pose 21, 0x01e6, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose202:
ax_pose 57, 0x01e4, 0x80f2, 0x3c00
ax_pose_terminator
sLombrePose203:
ax_pose 50, 0x01e5, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose204:
ax_pose 57, 0x01e4, 0x80f2, 0x3c00
ax_pose_terminator
sLombrePose205:
ax_pose 56, 0x01e5, 0x80f2, 0x3c00
ax_pose_terminator
sLombrePose206:
ax_pose 55, 0x01e7, 0x80f2, 0x3c00
ax_pose_terminator
sLombrePose207:
ax_pose 54, 0x01e8, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose208:
ax_pose 53, 0x01e7, 0x80ed, 0x3c00
ax_pose_terminator
sLombrePose209:
ax_pose 52, 0x01e5, 0x80ed, 0x3c00
ax_pose_terminator
sLombrePose210:
ax_pose 51, 0x01e4, 0x80ed, 0x3c00
ax_pose_terminator
sLombrePose211:
ax_pose 0, 0x01e6, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose212:
ax_pose 21, 0x01e6, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose213:
ax_pose 18, 0x01e6, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose214:
ax_pose 15, 0x01e6, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose215:
ax_pose 12, 0x01e6, 0x80f0, 0x3c00
ax_pose_terminator
sLombrePose216:
ax_pose 9, 0x01e6, 0x80ef, 0x3c00
ax_pose_terminator
sLombrePose217:
ax_pose 6, 0x01e6, 0x80ef, 0x3c00
ax_pose_terminator
sLombrePose218:
ax_pose 3, 0x01e6, 0x80ef, 0x3c00
ax_pose_terminator
sLombrePose219:
ax_pose 68, 0x41ea, 0x40f0, 0x3c00
ax_pose 69, 0x41f2, 0x80f0, 0x3c04
ax_pose 70, 0x01fe, 0x44f8, 0x5c0c
ax_pose_terminator
sLombrePose220:
ax_pose 71, 0x41ee, 0x40f0, 0x3c00
ax_pose 72, 0x41f6, 0x80f0, 0x3c04
ax_pose 70, 0x01fe, 0x44f8, 0x5c0c
ax_pose_terminator
sLombrePose221:
ax_pose 73, 0x41ed, 0x80f0, 0x3c00
ax_pose 74, 0x41fd, 0x40f0, 0x3c08
ax_pose 70, 0x01fe, 0x44f8, 0x5c0c
ax_pose_terminator
sLombrePose222:
ax_pose 75, 0x01fc, 0x44f8, 0x5c00
ax_pose 76, 0x41ee, 0x40f0, 0x3c04
ax_pose 77, 0x41f6, 0x80f0, 0x3c08
ax_pose_terminator
sLombrePose223:
ax_pose 78, 0x01f5, 0x44f8, 0x5c00
ax_pose 79, 0x41ea, 0x40f0, 0x3c04
ax_pose 80, 0x41f2, 0x80f0, 0x3c08
ax_pose_terminator
sLombrePose224:
ax_pose 68, 0x41ea, 0x40f0, 0x3c00
ax_pose 69, 0x41f2, 0x80f0, 0x3c04
ax_pose 70, 0x01fe, 0x44f8, 0x5c0c
ax_pose_terminator
sLombrePose225:
ax_pose 71, 0x41ee, 0x40f0, 0x3c00
ax_pose 72, 0x41f6, 0x80f0, 0x3c04
ax_pose 70, 0x01fe, 0x44f8, 0x5c0c
ax_pose_terminator
sLombrePose226:
ax_pose 73, 0x41ed, 0x80f0, 0x3c00
ax_pose 74, 0x41fd, 0x40f0, 0x3c08
ax_pose 70, 0x01fe, 0x44f8, 0x5c0c
ax_pose_terminator
sLombrePose227:
ax_pose 75, 0x01fc, 0x44f8, 0x5c00
ax_pose 76, 0x41ee, 0x40f0, 0x3c04
ax_pose 77, 0x41f6, 0x80f0, 0x3c08
ax_pose_terminator
sLombrePose228:
ax_pose 78, 0x01f5, 0x44f8, 0x5c00
ax_pose 79, 0x41ea, 0x40f0, 0x3c04
ax_pose 80, 0x41f2, 0x80f0, 0x3c08
ax_pose_terminator
.align 2
sLombreAnims_1_1:
ax_anim 6, 0, 0, 0, 0, 0, 0,
ax_anim 10, 0, 1, 0, 0, 0, 0,
ax_anim 6, 0, 0, 0, 0, 0, 0,
ax_anim 10, 0, 2, 0, 0, 0, 0,
ax_anim_terminator
sLombreAnims_1_2:
ax_anim 6, 0, 3, 0, 0, 0, 0,
ax_anim 10, 0, 4, 0, 0, 0, 0,
ax_anim 6, 0, 3, 0, 0, 0, 0,
ax_anim 10, 0, 5, 0, 0, 0, 0,
ax_anim_terminator
sLombreAnims_1_3:
ax_anim 6, 0, 6, 0, 0, 0, 0,
ax_anim 10, 0, 7, 0, 0, 0, 0,
ax_anim 6, 0, 6, 0, 0, 0, 0,
ax_anim 10, 0, 8, 0, 0, 0, 0,
ax_anim_terminator
sLombreAnims_1_4:
ax_anim 6, 0, 9, 0, 0, 0, 0,
ax_anim 10, 0, 10, 0, 0, 0, 0,
ax_anim 6, 0, 9, 0, 0, 0, 0,
ax_anim 10, 0, 11, 0, 0, 0, 0,
ax_anim_terminator
sLombreAnims_1_5:
ax_anim 6, 0, 12, 0, 0, 0, 0,
ax_anim 10, 0, 13, 0, 0, 0, 0,
ax_anim 6, 0, 12, 0, 0, 0, 0,
ax_anim 10, 0, 14, 0, 0, 0, 0,
ax_anim_terminator
sLombreAnims_1_6:
ax_anim 6, 0, 15, 0, 0, 0, 0,
ax_anim 10, 0, 16, 0, 0, 0, 0,
ax_anim 6, 0, 15, 0, 0, 0, 0,
ax_anim 10, 0, 17, 0, 0, 0, 0,
ax_anim_terminator
sLombreAnims_1_7:
ax_anim 6, 0, 18, 0, 0, 0, 0,
ax_anim 10, 0, 19, 0, 0, 0, 0,
ax_anim 6, 0, 18, 0, 0, 0, 0,
ax_anim 10, 0, 20, 0, 0, 0, 0,
ax_anim_terminator
sLombreAnims_1_8:
ax_anim 6, 0, 21, 0, 0, 0, 0,
ax_anim 10, 0, 22, 0, 0, 0, 0,
ax_anim 6, 0, 21, 0, 0, 0, 0,
ax_anim 10, 0, 23, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sLombreAnims_2_1:
ax_anim 2, 0, 25, 0, -1, 0, -1,
ax_anim 4, 0, 25, 0, -2, 0, -2,
ax_anim 1, 0, 26, 0, 0, 0, 0,
ax_anim 1, 2, 24, 0, 4, 0, 4,
ax_anim 1, 0, 24, 0, 10, 0, 10,
ax_anim 2, 0, 24, 0, 18, 0, 18,
ax_anim 2, 1, 24, 1, 18, 1, 18,
ax_anim 2, 0, 24, 0, 18, 0, 18,
ax_anim 2, 0, 24, 1, 18, 1, 18,
ax_anim 2, 0, 26, 0, 6, 0, 6,
ax_anim 2, 0, 25, 0, 3, 0, 3,
ax_anim_terminator
sLombreAnims_2_2:
ax_anim 2, 0, 29, -1, -1, -1, -1,
ax_anim 4, 0, 29, -2, -2, -2, -2,
ax_anim 1, 0, 28, 0, 0, 0, 0,
ax_anim 1, 2, 27, 4, 4, 4, 4,
ax_anim 1, 0, 27, 10, 10, 10, 10,
ax_anim 2, 0, 27, 19, 19, 19, 19,
ax_anim 2, 1, 27, 20, 18, 20, 18,
ax_anim 2, 0, 27, 19, 19, 19, 19,
ax_anim 2, 0, 27, 20, 18, 20, 18,
ax_anim 2, 0, 28, 8, 8, 8, 8,
ax_anim 2, 0, 29, 4, 4, 4, 4,
ax_anim_terminator
sLombreAnims_2_3:
ax_anim 2, 0, 31, -1, 0, -1, 0,
ax_anim 4, 0, 31, -2, 0, -2, 0,
ax_anim 1, 0, 32, 0, 0, 0, 0,
ax_anim 1, 2, 30, 4, 0, 4, 0,
ax_anim 1, 0, 30, 10, 0, 10, 0,
ax_anim 2, 0, 30, 18, 0, 18, 0,
ax_anim 2, 1, 30, 18, 1, 18, 1,
ax_anim 2, 0, 30, 18, 0, 18, 0,
ax_anim 2, 0, 30, 18, 1, 18, 1,
ax_anim 2, 0, 31, 6, 0, 6, 0,
ax_anim 2, 0, 32, 3, 0, 3, 0,
ax_anim_terminator
sLombreAnims_2_4:
ax_anim 2, 0, 35, -1, 1, -1, 1,
ax_anim 4, 0, 35, -2, 2, -2, 2,
ax_anim 1, 0, 34, 0, -1, 0, -1,
ax_anim 1, 2, 33, 4, -4, 4, -4,
ax_anim 1, 0, 33, 10, -12, 10, -12,
ax_anim 2, 0, 33, 18, -20, 18, -20,
ax_anim 2, 1, 33, 19, -19, 19, -19,
ax_anim 2, 0, 33, 18, -20, 18, -20,
ax_anim 2, 0, 33, 19, -19, 19, -19,
ax_anim 2, 0, 34, 6, -6, 6, -6,
ax_anim 2, 0, 35, 3, -3, 3, -3,
ax_anim_terminator
sLombreAnims_2_5:
ax_anim 2, 0, 37, 0, 1, 0, 1,
ax_anim 4, 0, 37, 0, 2, 0, 2,
ax_anim 1, 0, 38, 0, 0, 0, 0,
ax_anim 1, 2, 36, 0, -4, 0, -4,
ax_anim 1, 0, 36, 0, -11, 0, -11,
ax_anim 2, 0, 36, 0, -21, 0, -21,
ax_anim 2, 1, 36, 1, -21, 1, -21,
ax_anim 2, 0, 36, 0, -21, 0, -21,
ax_anim 2, 0, 36, 1, -21, 1, -21,
ax_anim 2, 0, 37, 0, -6, 0, -6,
ax_anim 2, 0, 38, 0, -3, 0, -3,
ax_anim_terminator
sLombreAnims_2_6:
ax_anim 2, 0, 41, 1, 1, 1, 1,
ax_anim 4, 0, 41, 2, 2, 2, 2,
ax_anim 1, 0, 40, 0, -1, 0, -1,
ax_anim 1, 2, 39, -4, -4, -4, -4,
ax_anim 1, 0, 39, -10, -12, -10, -12,
ax_anim 2, 0, 39, -18, -20, -18, -20,
ax_anim 2, 1, 39, -19, -19, -19, -19,
ax_anim 2, 0, 39, -18, -20, -18, -20,
ax_anim 2, 0, 39, -19, -19, -19, -19,
ax_anim 2, 0, 40, -6, -6, -6, -6,
ax_anim 2, 0, 41, -3, -3, -3, -3,
ax_anim_terminator
sLombreAnims_2_7:
ax_anim 2, 0, 43, 1, 0, 1, 0,
ax_anim 4, 0, 43, 2, 0, 2, 0,
ax_anim 1, 0, 44, 0, 0, 0, 0,
ax_anim 1, 2, 42, -4, 0, -4, 0,
ax_anim 1, 0, 42, -10, 0, -10, 0,
ax_anim 2, 0, 42, -18, 0, -18, 0,
ax_anim 2, 1, 42, -18, 1, -18, 1,
ax_anim 2, 0, 42, -18, 0, -18, 0,
ax_anim 2, 0, 42, -18, 1, -18, 1,
ax_anim 2, 0, 43, -6, 0, -6, 0,
ax_anim 2, 0, 44, -3, 0, -3, 0,
ax_anim_terminator
sLombreAnims_2_8:
ax_anim 2, 0, 47, 1, -1, 1, -1,
ax_anim 4, 0, 47, 2, -2, 2, -2,
ax_anim 1, 0, 46, 0, 0, 0, 0,
ax_anim 1, 2, 45, -4, 4, -4, 4,
ax_anim 1, 0, 45, -10, 10, -10, 10,
ax_anim 2, 0, 45, -19, 19, -19, 19,
ax_anim 2, 1, 45, -20, 18, -20, 18,
ax_anim 2, 0, 45, -19, 19, -19, 19,
ax_anim 2, 0, 45, -20, 18, -20, 18,
ax_anim 2, 0, 46, -8, 8, -8, 8,
ax_anim 2, 0, 47, -4, 4, -4, 4,
ax_anim_terminator
.align 2
sLombreAnims_3_1:
ax_anim 2, 0, 52, 0, -2, 0, -2,
ax_anim 4, 0, 52, 0, -3, 0, -3,
ax_anim 1, 0, 52, 0, 0, 0, 0,
ax_anim 2, 2, 52, 0, 5, 0, 5,
ax_anim 3, 0, 49, 0, 17, 0, 17,
ax_anim 4, 1, 50, 1, 17, 0, 17,
ax_anim 2, 0, 50, 1, 16, 0, 16,
ax_anim 3, 0, 51, 0, 17, 0, 17,
ax_anim 4, 0, 52, -1, 17, 0, 17,
ax_anim 2, 0, 48, 0, 10, 0, 10,
ax_anim 2, 0, 48, 0, 4, 0, 4,
ax_anim_terminator
sLombreAnims_3_2:
ax_anim 2, 0, 57, -2, -2, -2, -2,
ax_anim 4, 0, 57, -3, -3, -3, -3,
ax_anim 1, 0, 57, 0, 0, 0, 0,
ax_anim 2, 2, 57, 5, 5, 5, 5,
ax_anim 3, 0, 54, 18, 18, 18, 18,
ax_anim 4, 1, 55, 17, 19, 17, 19,
ax_anim 2, 0, 55, 16, 17, 16, 17,
ax_anim 3, 0, 56, 18, 18, 18, 18,
ax_anim 4, 0, 57, 19, 18, 19, 18,
ax_anim 2, 0, 53, 10, 10, 10, 10,
ax_anim 2, 0, 53, 4, 4, 4, 4,
ax_anim_terminator
sLombreAnims_3_3:
ax_anim 2, 0, 62, -2, 0, -2, 0,
ax_anim 4, 0, 62, -3, 0, -3, 0,
ax_anim 1, 0, 62, 0, 0, 0, 0,
ax_anim 2, 2, 62, 5, 0, 5, 0,
ax_anim 3, 0, 59, 12, 0, 12, 0,
ax_anim 4, 1, 60, 12, 1, 12, 1,
ax_anim 2, 0, 60, 11, 1, 11, 0,
ax_anim 3, 0, 61, 12, 0, 12, 0,
ax_anim 4, 0, 62, 13, -1, 13, -1,
ax_anim 2, 0, 58, 8, 0, 8, 0,
ax_anim 2, 0, 58, 4, 0, 4, 0,
ax_anim_terminator
sLombreAnims_3_4:
ax_anim 2, 0, 67, -2, 2, -2, 2,
ax_anim 4, 0, 67, -3, 3, -3, 3,
ax_anim 1, 0, 67, 0, 0, 0, 0,
ax_anim 2, 2, 67, 5, -7, 5, -7,
ax_anim 3, 0, 64, 16, -21, 16, -21,
ax_anim 4, 1, 65, 17, -21, 17, -21,
ax_anim 2, 0, 65, 15, -20, 15, -20,
ax_anim 3, 0, 66, 16, -21, 16, -21,
ax_anim 4, 0, 67, 15, -22, 15, -22,
ax_anim 2, 0, 63, 10, -13, 10, -13,
ax_anim 2, 0, 63, 4, -6, 4, -6,
ax_anim_terminator
sLombreAnims_3_5:
ax_anim 2, 0, 72, 0, 2, 0, 2,
ax_anim 4, 0, 72, 0, 3, 0, 3,
ax_anim 1, 0, 72, 0, 0, 0, 0,
ax_anim 2, 2, 72, 0, -7, 0, -7,
ax_anim 3, 0, 69, 0, -19, 0, -19,
ax_anim 4, 1, 70, -1, -19, -1, -19,
ax_anim 2, 0, 70, -1, -18, -1, -18,
ax_anim 3, 0, 71, 0, -19, 0, -19,
ax_anim 4, 0, 72, 1, -19, 1, -19,
ax_anim 2, 0, 68, 0, -13, 0, -13,
ax_anim 2, 0, 68, 0, -4, 0, -4,
ax_anim_terminator
sLombreAnims_3_6:
ax_anim 2, 0, 77, 2, 2, 2, 2,
ax_anim 4, 0, 77, 3, 3, 3, 3,
ax_anim 1, 0, 77, 0, 0, 0, 0,
ax_anim 2, 2, 77, -5, -7, -5, -7,
ax_anim 3, 0, 74, -16, -21, -16, -21,
ax_anim 4, 1, 75, -17, -21, -17, -21,
ax_anim 2, 0, 75, -16, -20, -16, -20,
ax_anim 3, 0, 76, -16, -21, -16, -21,
ax_anim 4, 0, 77, -15, -22, -15, -22,
ax_anim 2, 0, 73, -10, -13, -10, -13,
ax_anim 2, 0, 73, -4, -6, -4, -6,
ax_anim_terminator
sLombreAnims_3_7:
ax_anim 2, 0, 82, 2, 0, 2, 0,
ax_anim 4, 0, 82, 3, 0, 3, 0,
ax_anim 1, 0, 82, 0, 0, 0, 0,
ax_anim 2, 2, 82, -5, 0, -5, 0,
ax_anim 3, 0, 79, -12, 0, -12, 0,
ax_anim 4, 1, 80, -13, 1, -13, 1,
ax_anim 2, 0, 80, -11, 1, -11, 1,
ax_anim 3, 0, 81, -12, 0, -12, 0,
ax_anim 4, 0, 82, -13, -1, -13, -1,
ax_anim 2, 0, 78, -8, 0, -8, 0,
ax_anim 2, 0, 78, -4, 0, -4, 0,
ax_anim_terminator
sLombreAnims_3_8:
ax_anim 2, 0, 87, 2, -2, 2, -2,
ax_anim 4, 0, 87, 3, -3, 3, -3,
ax_anim 1, 0, 87, 0, 0, 0, 0,
ax_anim 2, 2, 87, -7, 5, -7, 5,
ax_anim 3, 0, 84, -18, 18, -18, 18,
ax_anim 4, 1, 85, -17, 19, -17, 19,
ax_anim 2, 0, 85, -15, 17, -15, 17,
ax_anim 3, 0, 86, -18, 18, -18, 18,
ax_anim 4, 0, 87, -19, 18, -19, 18,
ax_anim 2, 0, 83, -10, 10, -10, 10,
ax_anim 2, 0, 83, -4, 4, -4, 4,
ax_anim_terminator
.align 2
sLombreAnims_4_1:
ax_anim 2, 0, 88, 0, -2, 0, -2,
ax_anim 4, 0, 88, 0, -3, 0, -3,
ax_anim 2, 0, 88, 0, -2, 0, -2,
ax_anim 2, 0, 88, 0, 1, 0, 1,
ax_anim 2, 2, 89, 0, 4, 0, 4,
ax_anim 2, 0, 89, 1, 4, 1, 4,
ax_anim 2, 0, 89, 0, 4, 0, 4,
ax_anim 2, 0, 89, 1, 4, 1, 4,
ax_anim 2, 1, 89, 0, 4, 0, 4,
ax_anim 2, 0, 89, 1, 4, 1, 4,
ax_anim 2, 0, 89, 0, 4, 0, 4,
ax_anim 2, 0, 88, 0, 3, 0, 3,
ax_anim_terminator
sLombreAnims_4_2:
ax_anim 2, 0, 90, -2, -2, -2, -2,
ax_anim 4, 0, 90, -3, -3, -3, -3,
ax_anim 2, 0, 90, -2, -2, -2, -2,
ax_anim 2, 0, 90, 1, 1, 1, 1,
ax_anim 2, 2, 91, 4, 4, 4, 4,
ax_anim 2, 0, 91, 5, 3, 5, 3,
ax_anim 2, 0, 91, 4, 4, 4, 4,
ax_anim 2, 0, 91, 5, 3, 5, 3,
ax_anim 2, 1, 91, 4, 4, 4, 4,
ax_anim 2, 0, 91, 5, 3, 5, 3,
ax_anim 2, 0, 91, 4, 4, 4, 4,
ax_anim 2, 0, 90, 3, 3, 3, 3,
ax_anim_terminator
sLombreAnims_4_3:
ax_anim 2, 0, 92, -2, 0, -2, 0,
ax_anim 4, 0, 92, -3, 0, -3, 0,
ax_anim 2, 0, 92, -2, 0, -2, 0,
ax_anim 2, 0, 92, 1, 0, 1, 0,
ax_anim 2, 2, 93, 4, 0, 4, 0,
ax_anim 2, 0, 93, 4, -1, 4, -1,
ax_anim 2, 0, 93, 4, 0, 4, 0,
ax_anim 2, 0, 93, 4, -1, 4, -1,
ax_anim 2, 1, 93, 4, 0, 4, 0,
ax_anim 2, 0, 93, 4, -1, 4, -1,
ax_anim 2, 0, 93, 4, 0, 4, 0,
ax_anim 2, 0, 92, 3, 0, 3, 0,
ax_anim_terminator
sLombreAnims_4_4:
ax_anim 2, 0, 94, -2, 2, -2, 2,
ax_anim 4, 0, 94, -3, 3, -3, 3,
ax_anim 2, 0, 94, -2, 2, -2, 2,
ax_anim 2, 0, 94, 1, -1, 1, -1,
ax_anim 2, 2, 95, 4, -4, 4, -4,
ax_anim 2, 0, 95, 5, -3, 5, -3,
ax_anim 2, 0, 95, 4, -4, 4, -4,
ax_anim 2, 0, 95, 5, -3, 5, -3,
ax_anim 2, 1, 95, 4, -4, 4, -4,
ax_anim 2, 0, 95, 5, -3, 5, -3,
ax_anim 2, 0, 95, 4, -4, 4, -4,
ax_anim 2, 0, 94, 3, -3, 3, -3,
ax_anim_terminator
sLombreAnims_4_5:
ax_anim 2, 0, 96, 0, 2, 0, 2,
ax_anim 4, 0, 96, 0, 3, 0, 3,
ax_anim 2, 0, 96, 0, 2, 0, 2,
ax_anim 2, 0, 96, 0, -1, 0, -1,
ax_anim 2, 2, 97, 0, -4, 0, -4,
ax_anim 2, 0, 97, 1, -4, 1, -4,
ax_anim 2, 0, 97, 0, -4, 0, -4,
ax_anim 2, 0, 97, 1, -4, 1, -4,
ax_anim 2, 1, 97, 0, -4, 0, -4,
ax_anim 2, 0, 97, 1, -4, 1, -4,
ax_anim 2, 0, 97, 0, -4, 0, -4,
ax_anim 2, 0, 96, 0, -3, 0, -3,
ax_anim_terminator
sLombreAnims_4_6:
ax_anim 2, 0, 98, 2, 2, 2, 2,
ax_anim 4, 0, 98, 3, 3, 3, 3,
ax_anim 2, 0, 98, 2, 2, 2, 2,
ax_anim 2, 0, 98, -1, -1, -1, -1,
ax_anim 2, 2, 99, -4, -4, -4, -4,
ax_anim 2, 0, 99, -5, -3, -5, -3,
ax_anim 2, 0, 99, -4, -4, -4, -4,
ax_anim 2, 0, 99, -5, -3, -5, -3,
ax_anim 2, 1, 99, -4, -4, -4, -4,
ax_anim 2, 0, 99, -5, -3, -5, -3,
ax_anim 2, 0, 99, -4, -4, -4, -4,
ax_anim 2, 0, 98, -3, -3, -3, -3,
ax_anim_terminator
sLombreAnims_4_7:
ax_anim 2, 0, 100, 2, 0, 2, 0,
ax_anim 4, 0, 100, 3, 0, 3, 0,
ax_anim 2, 0, 100, 2, 0, 2, 0,
ax_anim 2, 0, 100, -1, 0, -1, 0,
ax_anim 2, 2, 101, -4, 0, -4, 0,
ax_anim 2, 0, 101, -4, -1, -4, -1,
ax_anim 2, 0, 101, -4, 0, -4, 0,
ax_anim 2, 0, 101, -4, -1, -4, -1,
ax_anim 2, 1, 101, -4, 0, -4, 0,
ax_anim 2, 0, 101, -4, -1, -4, -1,
ax_anim 2, 0, 101, -4, 0, -4, 0,
ax_anim 2, 0, 100, -3, 0, -3, 0,
ax_anim_terminator
sLombreAnims_4_8:
ax_anim 2, 0, 102, 2, -2, 2, -2,
ax_anim 4, 0, 102, 3, -3, 3, -3,
ax_anim 2, 0, 102, 2, -2, 2, -2,
ax_anim 2, 0, 102, -1, 1, -1, 1,
ax_anim 2, 2, 103, -4, 4, -4, 4,
ax_anim 2, 0, 103, -5, 3, -5, 3,
ax_anim 2, 0, 103, -4, 4, -4, 4,
ax_anim 2, 0, 103, -5, 3, -5, 3,
ax_anim 2, 1, 103, -4, 4, -4, 4,
ax_anim 2, 0, 103, -5, 3, -5, 3,
ax_anim 2, 0, 103, -4, 4, -4, 4,
ax_anim 2, 0, 102, -3, 3, -3, 3,
ax_anim_terminator
.align 2
sLombreAnims_5_1:
ax_anim 2, 0, 108, 0, -2, 0, -2,
ax_anim 4, 0, 108, 0, -3, 0, -3,
ax_anim 1, 0, 108, 0, 8, 0, 8,
ax_anim 2, 2, 108, 0, 21, 0, 21,
ax_anim 3, 0, 105, 0, 41, 0, 41,
ax_anim 4, 1, 106, 1, 41, 1, 41,
ax_anim 2, 0, 106, 1, 40, 1, 40,
ax_anim 3, 0, 107, 0, 41, 0, 41,
ax_anim 4, 0, 108, -1, 41, -1, 41,
ax_anim 2, 0, 104, 0, 10, 0, 10,
ax_anim 2, 0, 104, 0, 4, 0, 4,
ax_anim_terminator
sLombreAnims_5_2:
ax_anim 2, 0, 113, -2, -2, -2, -2,
ax_anim 4, 0, 113, -3, -3, -3, -3,
ax_anim 1, 0, 113, 8, 8, 8, 8,
ax_anim 2, 2, 113, 21, 21, 21, 21,
ax_anim 3, 0, 110, 42, 42, 42, 42,
ax_anim 4, 1, 111, 41, 43, 41, 43,
ax_anim 2, 0, 111, 40, 41, 40, 41,
ax_anim 3, 0, 112, 42, 42, 42, 42,
ax_anim 4, 0, 113, 43, 42, 43, 42,
ax_anim 2, 0, 109, 10, 10, 10, 10,
ax_anim 2, 0, 109, 4, 4, 4, 4,
ax_anim_terminator
sLombreAnims_5_3:
ax_anim 2, 0, 118, -2, 0, -2, 0,
ax_anim 4, 0, 118, -3, 0, -3, 0,
ax_anim 1, 0, 118, 8, 0, 8, 0,
ax_anim 2, 2, 118, 21, 0, 21, 0,
ax_anim 3, 0, 115, 36, 0, 36, 0,
ax_anim 4, 1, 116, 36, 1, 36, 1,
ax_anim 2, 0, 116, 35, 1, 35, 1,
ax_anim 3, 0, 117, 36, 0, 36, 0,
ax_anim 4, 0, 118, 37, -1, 37, -1,
ax_anim 2, 0, 114, 8, 0, 8, 0,
ax_anim 2, 0, 114, 4, 0, 4, 0,
ax_anim_terminator
sLombreAnims_5_4:
ax_anim 2, 0, 123, -2, 2, -2, 2,
ax_anim 4, 0, 123, -3, 3, -3, 3,
ax_anim 1, 0, 123, 8, -8, 8, -8,
ax_anim 2, 2, 123, 21, -23, 21, -23,
ax_anim 3, 0, 120, 40, -45, 40, -45,
ax_anim 4, 1, 121, 41, -45, 41, -45,
ax_anim 2, 0, 121, 39, -44, 39, -44,
ax_anim 3, 0, 122, 40, -45, 40, -45,
ax_anim 4, 0, 123, 39, -46, 39, -46,
ax_anim 2, 0, 119, 10, -13, 10, -13,
ax_anim 2, 0, 119, 4, -6, 4, -6,
ax_anim_terminator
sLombreAnims_5_5:
ax_anim 2, 0, 128, 0, 2, 0, 2,
ax_anim 4, 0, 128, 0, 3, 0, 3,
ax_anim 1, 0, 128, 0, -8, 0, -8,
ax_anim 2, 2, 128, 0, -23, 0, -23,
ax_anim 3, 0, 125, 0, -43, 0, -43,
ax_anim 4, 1, 126, -1, -43, -1, -43,
ax_anim 2, 0, 126, -1, -42, -1, -42,
ax_anim 3, 0, 127, 0, -43, 0, -43,
ax_anim 4, 0, 128, 1, -43, 1, -43,
ax_anim 2, 0, 124, 0, -13, 0, -13,
ax_anim 2, 0, 124, 0, -4, 0, -4,
ax_anim_terminator
sLombreAnims_5_6:
ax_anim 2, 0, 133, 2, 2, 2, 2,
ax_anim 4, 0, 133, 3, 3, 3, 3,
ax_anim 1, 0, 133, -8, -8, -8, -8,
ax_anim 2, 2, 133, -21, -23, -21, -23,
ax_anim 3, 0, 130, -40, -45, -40, -45,
ax_anim 4, 1, 131, -41, -45, -41, -45,
ax_anim 2, 0, 131, -40, -44, -40, -44,
ax_anim 3, 0, 132, -40, -45, -40, -45,
ax_anim 4, 0, 133, -39, -46, -39, -46,
ax_anim 2, 0, 129, -10, -13, -10, -13,
ax_anim 2, 0, 129, -4, -6, -4, -6,
ax_anim_terminator
sLombreAnims_5_7:
ax_anim 2, 0, 138, 2, 0, 2, 0,
ax_anim 4, 0, 138, 3, 0, 3, 0,
ax_anim 1, 0, 138, -8, 0, -8, 0,
ax_anim 2, 2, 138, -21, 0, -21, 0,
ax_anim 3, 0, 135, -36, 0, -36, 0,
ax_anim 4, 1, 136, -37, 1, -37, 1,
ax_anim 2, 0, 136, -35, 1, -35, 1,
ax_anim 3, 0, 137, -36, 0, -36, 0,
ax_anim 4, 0, 138, -37, -1, -37, -1,
ax_anim 2, 0, 134, -8, 0, -8, 0,
ax_anim 2, 0, 134, -4, 0, -4, 0,
ax_anim_terminator
sLombreAnims_5_8:
ax_anim 2, 0, 143, 2, -2, 2, -2,
ax_anim 4, 0, 143, 3, -3, 3, -3,
ax_anim 1, 0, 143, -8, 8, -8, 8,
ax_anim 2, 2, 143, -23, 21, -23, 21,
ax_anim 3, 0, 140, -42, 42, -42, 42,
ax_anim 4, 1, 141, -41, 43, -41, 43,
ax_anim 2, 0, 141, -39, 41, -39, 41,
ax_anim 3, 0, 142, -42, 42, -42, 42,
ax_anim 4, 0, 143, -43, 42, -43, 42,
ax_anim 2, 0, 139, -10, 10, -10, 10,
ax_anim 2, 0, 139, -4, 4, -4, 4,
ax_anim_terminator
.align 2
sLombreAnims_6_1:
ax_anim 30, 0, 144, 0, 0, 0, 0,
ax_anim 35, 0, 145, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sLombreAnims_7_1:
ax_anim 2, 0, 146, 0, -2, 0, -2,
ax_anim 8, 0, 146, 0, -3, 0, -3,
ax_anim_terminator
sLombreAnims_7_2:
ax_anim 2, 0, 147, -2, -2, -2, -2,
ax_anim 8, 0, 147, -3, -3, -3, -3,
ax_anim_terminator
sLombreAnims_7_3:
ax_anim 2, 0, 148, -2, 0, -2, 0,
ax_anim 8, 0, 148, -3, 0, -3, 0,
ax_anim_terminator
sLombreAnims_7_4:
ax_anim 2, 0, 149, -2, 2, -2, 2,
ax_anim 8, 0, 149, -3, 3, -3, 3,
ax_anim_terminator
sLombreAnims_7_5:
ax_anim 2, 0, 150, 0, 2, 0, 2,
ax_anim 8, 0, 150, 0, 3, 0, 3,
ax_anim_terminator
sLombreAnims_7_6:
ax_anim 2, 0, 151, 2, 2, 2, 2,
ax_anim 8, 0, 151, 3, 3, 3, 3,
ax_anim_terminator
sLombreAnims_7_7:
ax_anim 2, 0, 152, 2, 0, 2, 0,
ax_anim 8, 0, 152, 3, 0, 3, 0,
ax_anim_terminator
sLombreAnims_7_8:
ax_anim 2, 0, 153, 2, -2, 2, -2,
ax_anim 8, 0, 153, 3, -3, 3, -3,
ax_anim_terminator
.align 2
sLombreAnims_8_1:
ax_anim 40, 0, 154, 0, 0, 0, 0,
ax_anim 1, 0, 154, 0, -2, 0, 0,
ax_anim 2, 0, 154, 0, -4, 0, 0,
ax_anim 3, 0, 154, 0, -5, 0, 0,
ax_anim 4, 0, 155, 0, -6, 0, 0,
ax_anim 2, 0, 155, 0, -4, 0, 0,
ax_anim 1, 0, 155, 0, -2, 0, 0,
ax_anim 10, 0, 155, 0, 0, 0, 0,
ax_anim_terminator
sLombreAnims_8_2:
ax_anim 40, 0, 156, 0, 0, 0, 0,
ax_anim 1, 0, 156, 0, -2, 0, 0,
ax_anim 2, 0, 156, 0, -4, 0, 0,
ax_anim 3, 0, 156, 0, -5, 0, 0,
ax_anim 4, 0, 157, 1, -7, 0, 0,
ax_anim 2, 0, 157, 1, -5, 0, 0,
ax_anim 1, 0, 157, 1, -3, 0, 0,
ax_anim 10, 0, 157, 1, 0, 0, 0,
ax_anim_terminator
sLombreAnims_8_3:
ax_anim 40, 0, 158, 0, 0, 0, 0,
ax_anim 1, 0, 158, 0, -2, 0, 0,
ax_anim 2, 0, 158, 0, -4, 0, 0,
ax_anim 3, 0, 158, 0, -5, 0, 0,
ax_anim 4, 0, 159, -1, -7, 0, 0,
ax_anim 2, 0, 159, 0, -5, 0, 0,
ax_anim 1, 0, 159, 0, -3, 0, 0,
ax_anim 10, 0, 159, 0, 0, 0, 0,
ax_anim_terminator
sLombreAnims_8_4:
ax_anim 40, 0, 160, 0, 0, 0, 0,
ax_anim 1, 0, 160, 0, -2, 0, 0,
ax_anim 2, 0, 160, 0, -4, 0, 0,
ax_anim 3, 0, 160, 0, -5, 0, 0,
ax_anim 4, 0, 161, -1, -5, 0, 0,
ax_anim 2, 0, 161, 0, -4, 0, 0,
ax_anim 1, 0, 161, 0, -2, 0, 0,
ax_anim 10, 0, 161, 0, 0, 0, 0,
ax_anim_terminator
sLombreAnims_8_5:
ax_anim 40, 0, 162, 0, 0, 0, 0,
ax_anim 1, 0, 162, 0, -2, 0, 0,
ax_anim 2, 0, 162, 0, -4, 0, 0,
ax_anim 3, 0, 162, 0, -5, 0, 0,
ax_anim 4, 0, 163, 0, -6, 0, 0,
ax_anim 2, 0, 163, 0, -4, 0, 0,
ax_anim 1, 0, 163, 0, -2, 0, 0,
ax_anim 10, 0, 163, 0, 0, 0, 0,
ax_anim_terminator
sLombreAnims_8_6:
ax_anim 40, 0, 164, 0, 0, 0, 0,
ax_anim 1, 0, 164, 0, -2, 0, 0,
ax_anim 2, 0, 164, 0, -4, 0, 0,
ax_anim 3, 0, 164, 0, -5, 0, 0,
ax_anim 4, 0, 165, 1, -5, 0, 0,
ax_anim 2, 0, 165, 0, -4, 0, 0,
ax_anim 1, 0, 165, 0, -2, 0, 0,
ax_anim 10, 0, 165, 0, 0, 0, 0,
ax_anim_terminator
sLombreAnims_8_7:
ax_anim 40, 0, 166, 0, 0, 0, 0,
ax_anim 1, 0, 166, 0, -2, 0, 0,
ax_anim 2, 0, 166, 0, -4, 0, 0,
ax_anim 3, 0, 166, 0, -5, 0, 0,
ax_anim 4, 0, 167, 1, -7, 0, 0,
ax_anim 2, 0, 167, 0, -5, 0, 0,
ax_anim 1, 0, 167, 0, -3, 0, 0,
ax_anim 10, 0, 167, 0, 0, 0, 0,
ax_anim_terminator
sLombreAnims_8_8:
ax_anim 40, 0, 168, 0, 0, 0, 0,
ax_anim 1, 0, 168, 0, -2, 0, 0,
ax_anim 2, 0, 168, 0, -4, 0, 0,
ax_anim 3, 0, 168, 0, -5, 0, 0,
ax_anim 4, 0, 169, -1, -7, 0, 0,
ax_anim 2, 0, 169, -1, -5, 0, 0,
ax_anim 1, 0, 169, -1, -3, 0, 0,
ax_anim 10, 0, 169, -1, 0, 0, 0,
ax_anim_terminator
.align 2
sLombreAnims_9_1:
ax_anim 2, 0, 170, 0, 0, 0, 0,
ax_anim 1, 0, 171, 6, 4, 6, 4,
ax_anim 2, 0, 172, 8, 9, 8, 9,
ax_anim 2, 0, 173, 7, 18, 7, 18,
ax_anim 3, 0, 174, 0, 22, 0, 22,
ax_anim 2, 3, 175, -7, 18, -7, 18,
ax_anim 2, 0, 176, -8, 9, -8, 9,
ax_anim 1, 0, 177, -6, 4, -6, 4,
ax_anim 1, 0, 170, 0, 0, 0, 0,
ax_anim_terminator
sLombreAnims_9_2:
ax_anim 2, 0, 177, 0, 0, 0, 0,
ax_anim 1, 0, 170, 6, 0, 6, 0,
ax_anim 2, 0, 171, 17, 3, 17, 3,
ax_anim 2, 0, 172, 24, 9, 24, 9,
ax_anim 3, 0, 173, 23, 19, 23, 19,
ax_anim 2, 3, 174, 11, 21, 11, 21,
ax_anim 2, 0, 175, 2, 14, 2, 14,
ax_anim 1, 0, 176, 0, 7, 0, 7,
ax_anim 1, 0, 177, 0, 0, 0, 0,
ax_anim_terminator
sLombreAnims_9_3:
ax_anim 2, 0, 176, 0, 0, 0, 0,
ax_anim 1, 0, 177, 3, -4, 3, -4,
ax_anim 2, 0, 170, 11, -6, 11, -6,
ax_anim 2, 0, 171, 17, -4, 17, -4,
ax_anim 3, 0, 172, 22, 1, 22, 1,
ax_anim 2, 3, 173, 17, 5, 17, 5,
ax_anim 2, 0, 174, 12, 7, 12, 7,
ax_anim 1, 0, 175, 4, 5, 4, 5,
ax_anim 1, 0, 176, 0, 0, 0, 0,
ax_anim_terminator
sLombreAnims_9_4:
ax_anim 2, 0, 175, 0, 0, 0, 0,
ax_anim 1, 0, 176, -1, -6, -1, -6,
ax_anim 2, 0, 177, 4, -16, 4, -16,
ax_anim 2, 0, 170, 11, -23, 11, -23,
ax_anim 3, 0, 171, 20, -25, 20, -25,
ax_anim 2, 3, 172, 22, -14, 22, -14,
ax_anim 2, 0, 173, 18, -6, 18, -6,
ax_anim 1, 0, 174, 8, 0, 8, 0,
ax_anim 1, 0, 175, 0, 0, 0, 0,
ax_anim_terminator
sLombreAnims_9_5:
ax_anim 2, 0, 174, 0, 0, 0, 0,
ax_anim 1, 0, 175, -6, -4, -6, -4,
ax_anim 2, 0, 176, -8, -10, -8, -10,
ax_anim 2, 0, 177, -7, -20, -7, -20,
ax_anim 3, 0, 170, 0, -25, 0, -25,
ax_anim 2, 3, 171, 7, -20, 7, -20,
ax_anim 2, 0, 172, 8, -8, 8, -8,
ax_anim 1, 0, 173, 6, -4, 6, -4,
ax_anim 1, 0, 174, 0, 0, 0, 0,
ax_anim_terminator
sLombreAnims_9_6:
ax_anim 2, 0, 173, 0, 0, 0, 0,
ax_anim 1, 0, 172, 1, -6, 1, -6,
ax_anim 2, 0, 171, -4, -16, -4, -16,
ax_anim 2, 0, 170, -11, -23, -11, -23,
ax_anim 3, 0, 177, -20, -25, -20, -25,
ax_anim 2, 3, 176, -22, -14, -22, -14,
ax_anim 2, 0, 175, -18, -6, -18, -6,
ax_anim 1, 0, 174, -8, 0, -8, 0,
ax_anim 1, 0, 173, 0, 0, 0, 0,
ax_anim_terminator
sLombreAnims_9_7:
ax_anim 2, 0, 172, 0, 0, 0, 0,
ax_anim 1, 0, 171, -3, -4, -3, -4,
ax_anim 2, 0, 170, -11, -6, -11, -6,
ax_anim 2, 0, 177, -17, -4, -17, -4,
ax_anim 3, 0, 176, -22, 1, -22, 1,
ax_anim 2, 3, 175, -17, 5, -17, 5,
ax_anim 2, 0, 174, -12, 7, -12, 7,
ax_anim 1, 0, 173, -4, 5, -4, 5,
ax_anim 1, 0, 172, 0, 0, 0, 0,
ax_anim_terminator
sLombreAnims_9_8:
ax_anim 2, 0, 171, 0, 0, 0, 0,
ax_anim 1, 0, 170, -6, 0, -6, 0,
ax_anim 2, 0, 177, -17, 3, -17, 3,
ax_anim 2, 0, 176, -24, 9, -24, 9,
ax_anim 3, 0, 175, -23, 19, -23, 19,
ax_anim 2, 3, 174, -11, 21, -11, 21,
ax_anim 2, 0, 173, -2, 14, -2, 14,
ax_anim 1, 0, 172, 0, 7, 0, 7,
ax_anim 1, 0, 171, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sLombreAnims_10_1:
ax_anim 2, 0, 178, 0, 0, 0, 0,
ax_anim 2, 0, 178, 6, 0, 6, 0,
ax_anim 2, 0, 178, -6, 0, -6, 0,
ax_anim 2, 0, 178, 10, 0, 10, 0,
ax_anim 2, 0, 178, -10, 0, -10, 0,
ax_anim 2, 0, 178, 12, 0, 12, 0,
ax_anim 3, 0, 178, -12, 0, -12, 0,
ax_anim 3, 0, 178, 13, 0, 13, 0,
ax_anim 3, 0, 178, -13, 0, -13, 0,
ax_anim 2, 0, 178, 12, 0, 12, 0,
ax_anim 3, 0, 178, -12, 0, -12, 0,
ax_anim 2, 0, 178, 10, 0, 10, 0,
ax_anim 2, 0, 178, -10, 0, -10, 0,
ax_anim 2, 0, 178, 6, 0, 6, 0,
ax_anim 2, 0, 178, -6, 0, -6, 0,
ax_anim 2, 0, 178, 0, 0, 0, 0,
ax_anim_terminator
sLombreAnims_10_2:
ax_anim 2, 0, 179, 0, 0, 0, 0,
ax_anim 2, 0, 179, 6, -6, 6, -6,
ax_anim 2, 0, 179, -6, 6, -6, 6,
ax_anim 2, 0, 179, 10, -10, 10, -10,
ax_anim 2, 0, 179, -10, 10, -10, 10,
ax_anim 2, 0, 179, 12, -12, 12, -12,
ax_anim 3, 0, 179, -12, 12, -12, 12,
ax_anim 3, 0, 179, 13, -13, 13, -13,
ax_anim 3, 0, 179, -13, 13, -13, 13,
ax_anim 2, 0, 179, 12, -12, 12, -12,
ax_anim 3, 0, 179, -12, 12, -12, 12,
ax_anim 2, 0, 179, 10, -10, 10, -10,
ax_anim 2, 0, 179, -10, 10, -10, 10,
ax_anim 2, 0, 179, 6, -6, 6, -6,
ax_anim 2, 0, 179, -6, 6, -6, 6,
ax_anim 2, 0, 179, 0, 0, 0, 0,
ax_anim_terminator
sLombreAnims_10_3:
ax_anim 2, 0, 180, 0, 0, 0, 0,
ax_anim 2, 0, 180, 0, -6, 0, -6,
ax_anim 2, 0, 180, 0, 6, 0, 6,
ax_anim 2, 0, 180, 0, -10, 0, -10,
ax_anim 2, 0, 180, 0, 10, 0, 10,
ax_anim 2, 0, 180, 0, -12, 0, -12,
ax_anim 3, 0, 180, 0, 12, 0, 12,
ax_anim 3, 0, 180, 0, -13, 0, -13,
ax_anim 3, 0, 180, 0, 13, 0, 13,
ax_anim 2, 0, 180, 0, -12, 0, -12,
ax_anim 3, 0, 180, 0, 12, 0, 12,
ax_anim 2, 0, 180, 0, -10, 0, -10,
ax_anim 2, 0, 180, 0, 10, 0, 10,
ax_anim 2, 0, 180, 0, -6, 0, -6,
ax_anim 2, 0, 180, 0, 6, 0, 6,
ax_anim 2, 0, 180, 0, 0, 0, 0,
ax_anim_terminator
sLombreAnims_10_4:
ax_anim 2, 0, 181, 0, 0, 0, 0,
ax_anim 2, 0, 181, -6, -6, -6, -6,
ax_anim 2, 0, 181, 6, 6, 6, 6,
ax_anim 2, 0, 181, -10, -10, -10, -10,
ax_anim 2, 0, 181, 10, 10, 10, 10,
ax_anim 2, 0, 181, -12, -12, -12, -12,
ax_anim 3, 0, 181, 12, 12, 12, 12,
ax_anim 3, 0, 181, -13, -13, -13, -13,
ax_anim 3, 0, 181, 13, 13, 13, 13,
ax_anim 2, 0, 181, -12, -12, -12, -12,
ax_anim 3, 0, 181, 12, 12, 12, 12,
ax_anim 2, 0, 181, -10, -10, -10, -10,
ax_anim 2, 0, 181, 10, 10, 10, 10,
ax_anim 2, 0, 181, -6, -6, -6, -6,
ax_anim 2, 0, 181, 6, 6, 6, 6,
ax_anim 2, 0, 181, 0, 0, 0, 0,
ax_anim_terminator
sLombreAnims_10_5:
ax_anim 2, 0, 182, 0, 0, 0, 0,
ax_anim 2, 0, 182, 6, 0, 6, 0,
ax_anim 2, 0, 182, -6, 0, -6, 0,
ax_anim 2, 0, 182, 10, 0, 10, 0,
ax_anim 2, 0, 182, -10, 0, -10, 0,
ax_anim 2, 0, 182, 12, 0, 12, 0,
ax_anim 3, 0, 182, -12, 0, -12, 0,
ax_anim 3, 0, 182, 13, 0, 13, 0,
ax_anim 3, 0, 182, -13, 0, -13, 0,
ax_anim 2, 0, 182, 12, 0, 12, 0,
ax_anim 3, 0, 182, -12, 0, -12, 0,
ax_anim 2, 0, 182, 10, 0, 10, 0,
ax_anim 2, 0, 182, -10, 0, -10, 0,
ax_anim 2, 0, 182, 6, 0, 6, 0,
ax_anim 2, 0, 182, -6, 0, -6, 0,
ax_anim 2, 0, 182, 0, 0, 0, 0,
ax_anim_terminator
sLombreAnims_10_6:
ax_anim 2, 0, 183, 0, 0, 0, 0,
ax_anim 2, 0, 183, 6, -6, 6, -6,
ax_anim 2, 0, 183, -6, 6, -6, 6,
ax_anim 2, 0, 183, 10, -10, 10, -10,
ax_anim 2, 0, 183, -10, 10, -10, 10,
ax_anim 2, 0, 183, 12, -12, 12, -12,
ax_anim 3, 0, 183, -12, 12, -12, 12,
ax_anim 3, 0, 183, 13, -13, 13, -13,
ax_anim 3, 0, 183, -13, 13, -13, 13,
ax_anim 2, 0, 183, 12, -12, 12, -12,
ax_anim 3, 0, 183, -12, 12, -12, 12,
ax_anim 2, 0, 183, 10, -10, 10, -10,
ax_anim 2, 0, 183, -10, 10, -10, 10,
ax_anim 2, 0, 183, 6, -6, 6, -6,
ax_anim 2, 0, 183, -6, 6, -6, 6,
ax_anim 2, 0, 183, 0, 0, 0, 0,
ax_anim_terminator
sLombreAnims_10_7:
ax_anim 2, 0, 184, 0, 0, 0, 0,
ax_anim 2, 0, 184, 0, -6, 0, -6,
ax_anim 2, 0, 184, 0, 6, 0, 6,
ax_anim 2, 0, 184, 0, -10, 0, -10,
ax_anim 2, 0, 184, 0, 10, 0, 10,
ax_anim 2, 0, 184, 0, -12, 0, -12,
ax_anim 3, 0, 184, 0, 12, 0, 12,
ax_anim 3, 0, 184, 0, -13, 0, -13,
ax_anim 3, 0, 184, 0, 13, 0, 13,
ax_anim 2, 0, 184, 0, -12, 0, -12,
ax_anim 3, 0, 184, 0, 12, 0, 12,
ax_anim 2, 0, 184, 0, -10, 0, -10,
ax_anim 2, 0, 184, 0, 10, 0, 10,
ax_anim 2, 0, 184, 0, -6, 0, -6,
ax_anim 2, 0, 184, 0, 6, 0, 6,
ax_anim 2, 0, 184, 0, 0, 0, 0,
ax_anim_terminator
sLombreAnims_10_8:
ax_anim 2, 0, 185, 0, 0, 0, 0,
ax_anim 2, 0, 185, -6, -6, -6, -6,
ax_anim 2, 0, 185, 6, 6, 6, 6,
ax_anim 2, 0, 185, -10, -10, -10, -10,
ax_anim 2, 0, 185, 10, 10, 10, 10,
ax_anim 2, 0, 185, -12, -12, -12, -12,
ax_anim 3, 0, 185, 12, 12, 12, 12,
ax_anim 3, 0, 185, -13, -13, -13, -13,
ax_anim 3, 0, 185, 13, 13, 13, 13,
ax_anim 2, 0, 185, -12, -12, -12, -12,
ax_anim 3, 0, 185, 12, 12, 12, 12,
ax_anim 2, 0, 185, -10, -10, -10, -10,
ax_anim 2, 0, 185, 10, 10, 10, 10,
ax_anim 2, 0, 185, -6, -6, -6, -6,
ax_anim 2, 0, 185, 6, 6, 6, 6,
ax_anim 2, 0, 185, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sLombreAnims_11_1:
ax_anim 2, 0, 186, 0, 0, 0, 0,
ax_anim 1, 0, 186, 0, -10, 0, 0,
ax_anim 2, 0, 186, 0, -16, 0, 0,
ax_anim 3, 0, 186, 0, -20, 0, 0,
ax_anim 4, 0, 186, 0, -21, 0, 0,
ax_anim 4, 0, 187, 0, -23, 0, 0,
ax_anim 3, 0, 187, 0, -22, 0, 0,
ax_anim 2, 0, 187, 0, -18, 0, 0,
ax_anim 1, 0, 187, 0, -12, 0, 0,
ax_anim 2, 2, 187, 0, 0, 0, 0,
ax_anim_terminator
sLombreAnims_11_2:
ax_anim 2, 0, 188, 0, 0, 0, 0,
ax_anim 1, 0, 188, 0, -10, 0, 0,
ax_anim 2, 0, 188, 0, -16, 0, 0,
ax_anim 3, 0, 188, 0, -20, 0, 0,
ax_anim 4, 0, 188, 0, -21, 0, 0,
ax_anim 4, 0, 189, 0, -23, 0, 0,
ax_anim 3, 0, 189, 0, -22, 0, 0,
ax_anim 2, 0, 189, 0, -18, 0, 0,
ax_anim 1, 0, 189, 0, -12, 0, 0,
ax_anim 2, 2, 189, 0, 0, 0, 0,
ax_anim_terminator
sLombreAnims_11_3:
ax_anim 2, 0, 190, 0, 0, 0, 0,
ax_anim 1, 0, 190, 0, -10, 0, 0,
ax_anim 2, 0, 190, 0, -16, 0, 0,
ax_anim 3, 0, 190, 0, -20, 0, 0,
ax_anim 4, 0, 190, 0, -21, 0, 0,
ax_anim 4, 0, 191, 0, -23, 0, 0,
ax_anim 3, 0, 191, 0, -22, 0, 0,
ax_anim 2, 0, 191, 0, -18, 0, 0,
ax_anim 1, 0, 191, 0, -12, 0, 0,
ax_anim 2, 2, 191, 0, 0, 0, 0,
ax_anim_terminator
sLombreAnims_11_4:
ax_anim 2, 0, 192, 0, 0, 0, 0,
ax_anim 1, 0, 192, 0, -10, 0, 0,
ax_anim 2, 0, 192, 0, -16, 0, 0,
ax_anim 3, 0, 192, 0, -20, 0, 0,
ax_anim 4, 0, 192, 0, -21, 0, 0,
ax_anim 4, 0, 193, 0, -22, 0, 0,
ax_anim 3, 0, 193, 0, -21, 0, 0,
ax_anim 2, 0, 193, 0, -17, 0, 0,
ax_anim 1, 0, 193, 0, -11, 0, 0,
ax_anim 2, 2, 193, 0, 0, 0, 0,
ax_anim_terminator
sLombreAnims_11_5:
ax_anim 2, 0, 194, 0, 0, 0, 0,
ax_anim 1, 0, 194, 0, -10, 0, 0,
ax_anim 2, 0, 194, 0, -16, 0, 0,
ax_anim 3, 0, 194, 0, -20, 0, 0,
ax_anim 4, 0, 194, 0, -21, 0, 0,
ax_anim 4, 0, 195, 0, -23, 0, 0,
ax_anim 3, 0, 195, 0, -22, 0, 0,
ax_anim 2, 0, 195, 0, -18, 0, 0,
ax_anim 1, 0, 195, 0, -12, 0, 0,
ax_anim 2, 2, 195, 0, 0, 0, 0,
ax_anim_terminator
sLombreAnims_11_6:
ax_anim 2, 0, 196, 0, 0, 0, 0,
ax_anim 1, 0, 196, 0, -10, 0, 0,
ax_anim 2, 0, 196, 0, -16, 0, 0,
ax_anim 3, 0, 196, 0, -20, 0, 0,
ax_anim 4, 0, 196, 0, -21, 0, 0,
ax_anim 4, 0, 197, 0, -22, 0, 0,
ax_anim 3, 0, 197, 0, -21, 0, 0,
ax_anim 2, 0, 197, 0, -17, 0, 0,
ax_anim 1, 0, 197, 0, -11, 0, 0,
ax_anim 2, 2, 197, 0, 0, 0, 0,
ax_anim_terminator
sLombreAnims_11_7:
ax_anim 2, 0, 198, 0, 0, 0, 0,
ax_anim 1, 0, 198, 0, -10, 0, 0,
ax_anim 2, 0, 198, 0, -16, 0, 0,
ax_anim 3, 0, 198, 0, -20, 0, 0,
ax_anim 4, 0, 198, 0, -21, 0, 0,
ax_anim 4, 0, 199, 0, -23, 0, 0,
ax_anim 3, 0, 199, 0, -22, 0, 0,
ax_anim 2, 0, 199, 0, -18, 0, 0,
ax_anim 1, 0, 199, 0, -12, 0, 0,
ax_anim 2, 2, 199, 0, 0, 0, 0,
ax_anim_terminator
sLombreAnims_11_8:
ax_anim 2, 0, 200, 0, 0, 0, 0,
ax_anim 1, 0, 200, 0, -10, 0, 0,
ax_anim 2, 0, 200, 0, -16, 0, 0,
ax_anim 3, 0, 200, 0, -20, 0, 0,
ax_anim 4, 0, 200, 0, -21, 0, 0,
ax_anim 4, 0, 201, 0, -23, 0, 0,
ax_anim 3, 0, 201, 0, -22, 0, 0,
ax_anim 2, 0, 201, 0, -18, 0, 0,
ax_anim 1, 0, 201, 0, -12, 0, 0,
ax_anim 2, 2, 201, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sLombreAnims_12_1:
ax_anim 2, 0, 202, 1, 0, 1, 0,
ax_anim 2, 0, 202, 0, 0, 0, 0,
ax_anim 2, 0, 202, 1, 0, 1, 0,
ax_anim 2, 0, 202, 0, 0, 0, 0,
ax_anim 2, 0, 202, 1, 0, 1, 0,
ax_anim 2, 2, 202, 0, 0, 0, 0,
ax_anim 2, 0, 202, 1, 0, 1, 0,
ax_anim 2, 0, 202, 0, 0, 0, 0,
ax_anim 2, 0, 202, 1, 0, 1, 0,
ax_anim 2, 1, 202, 0, 0, 0, 0,
ax_anim_terminator
sLombreAnims_12_2:
ax_anim 2, 0, 209, 1, -1, 1, 0,
ax_anim 2, 0, 209, 0, 0, 0, 0,
ax_anim 2, 0, 209, 1, -1, 1, 0,
ax_anim 2, 0, 209, 0, 0, 0, 0,
ax_anim 2, 0, 209, 1, -1, 1, 0,
ax_anim 2, 2, 209, 0, 0, 0, 0,
ax_anim 2, 0, 209, 1, -1, 1, 0,
ax_anim 2, 0, 209, 0, 0, 0, 0,
ax_anim 2, 0, 209, 1, -1, 1, 0,
ax_anim 2, 1, 209, 0, 0, 0, 0,
ax_anim_terminator
sLombreAnims_12_3:
ax_anim 2, 0, 208, 0, -1, 0, -1,
ax_anim 2, 0, 208, 0, 0, 0, 0,
ax_anim 2, 0, 208, 0, -1, 0, -1,
ax_anim 2, 0, 208, 0, 0, 0, 0,
ax_anim 2, 0, 208, 0, -1, 0, -1,
ax_anim 2, 2, 208, 0, 0, 0, 0,
ax_anim 2, 0, 208, 0, -1, 0, -1,
ax_anim 2, 0, 208, 0, 0, 0, 0,
ax_anim 2, 0, 208, 0, -1, 0, -1,
ax_anim 2, 1, 208, 0, 0, 0, 0,
ax_anim_terminator
sLombreAnims_12_4:
ax_anim 2, 0, 207, -1, -1, -1, -1,
ax_anim 2, 0, 207, 0, 0, 0, 0,
ax_anim 2, 0, 207, -1, -1, -1, -1,
ax_anim 2, 0, 207, 0, 0, 0, 0,
ax_anim 2, 0, 207, -1, -1, -1, -1,
ax_anim 2, 2, 207, 0, 0, 0, 0,
ax_anim 2, 0, 207, -1, -1, -1, -1,
ax_anim 2, 0, 207, 0, 0, 0, 0,
ax_anim 2, 0, 207, -1, -1, -1, -1,
ax_anim 2, 1, 207, 0, 0, 0, 0,
ax_anim_terminator
sLombreAnims_12_5:
ax_anim 2, 0, 206, 1, 0, 1, 0,
ax_anim 2, 0, 206, 0, 0, 0, 0,
ax_anim 2, 0, 206, 1, 0, 1, 0,
ax_anim 2, 0, 206, 0, 0, 0, 0,
ax_anim 2, 0, 206, 1, 0, 1, 0,
ax_anim 2, 2, 206, 0, 0, 0, 0,
ax_anim 2, 0, 206, 1, 0, 1, 0,
ax_anim 2, 0, 206, 0, 0, 0, 0,
ax_anim 2, 0, 206, 1, 0, 1, 0,
ax_anim 2, 1, 206, 0, 0, 0, 0,
ax_anim_terminator
sLombreAnims_12_6:
ax_anim 2, 0, 205, 1, -1, 1, -1,
ax_anim 2, 0, 205, 0, 0, 0, 0,
ax_anim 2, 0, 205, 1, -1, 1, -1,
ax_anim 2, 0, 205, 0, 0, 0, 0,
ax_anim 2, 0, 205, 1, -1, 1, -1,
ax_anim 2, 2, 205, 0, 0, 0, 0,
ax_anim 2, 0, 205, 1, -1, 1, -1,
ax_anim 2, 0, 205, 0, 0, 0, 0,
ax_anim 2, 0, 205, 1, -1, 1, -1,
ax_anim 2, 1, 205, 0, 0, 0, 0,
ax_anim_terminator
sLombreAnims_12_7:
ax_anim 2, 0, 204, 0, -1, 0, -1,
ax_anim 2, 0, 204, 0, 0, 0, 0,
ax_anim 2, 0, 204, 0, -1, 0, -1,
ax_anim 2, 0, 204, 0, 0, 0, 0,
ax_anim 2, 0, 204, 0, -1, 0, -1,
ax_anim 2, 2, 204, 0, 0, 0, 0,
ax_anim 2, 0, 204, 0, -1, 0, -1,
ax_anim 2, 0, 204, 0, 0, 0, 0,
ax_anim 2, 0, 204, 0, -1, 0, -1,
ax_anim 2, 1, 204, 0, 0, 0, 0,
ax_anim_terminator
sLombreAnims_12_8:
ax_anim 2, 0, 203, -1, -1, -1, -1,
ax_anim 2, 0, 203, 0, 0, 0, 0,
ax_anim 2, 0, 203, -1, -1, -1, -1,
ax_anim 2, 0, 203, 0, 0, 0, 0,
ax_anim 2, 0, 203, -1, -1, -1, -1,
ax_anim 2, 2, 203, 0, 0, 0, 0,
ax_anim 2, 0, 203, -1, -1, -1, -1,
ax_anim 2, 0, 203, 0, 0, 0, 0,
ax_anim 2, 0, 203, -1, -1, -1, -1,
ax_anim 2, 1, 203, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sLombreAnims_13_1:
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 2, 210, 0, 0, 0, 0,
ax_anim_terminator
sLombreAnims_13_2:
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 2, 217, 0, 0, 0, 0,
ax_anim_terminator
sLombreAnims_13_3:
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 2, 216, 0, 0, 0, 0,
ax_anim_terminator
sLombreAnims_13_4:
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 2, 2, 215, 0, 0, 0, 0,
ax_anim_terminator
sLombreAnims_13_5:
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 2, 2, 214, 0, 0, 0, 0,
ax_anim_terminator
sLombreAnims_13_6:
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 2, 2, 213, 0, 0, 0, 0,
ax_anim_terminator
sLombreAnims_13_7:
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 2, 2, 212, 0, 0, 0, 0,
ax_anim_terminator
sLombreAnims_13_8:
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 2, 2, 211, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sLombreAnims_14_1:
ax_anim 10, 0, 218, 0, 0, 0, 0,
ax_anim 4, 0, 219, 0, 0, 0, 0,
ax_anim 18, 0, 220, 0, 0, 0, 0,
ax_anim 4, 0, 221, 0, 0, 0, 0,
ax_anim 10, 0, 222, 0, 0, 0, 0,
ax_anim_terminator
sLombreAnims_14_2:
ax_anim 10, 0, 218, 0, 0, 0, 0,
ax_anim 4, 0, 219, 0, 0, 0, 0,
ax_anim 18, 0, 220, 0, 0, 0, 0,
ax_anim 4, 0, 221, 0, 0, 0, 0,
ax_anim 10, 0, 222, 0, 0, 0, 0,
ax_anim_terminator
sLombreAnims_14_3:
ax_anim 10, 0, 218, 0, 0, 0, 0,
ax_anim 4, 0, 219, 0, 0, 0, 0,
ax_anim 18, 0, 220, 0, 0, 0, 0,
ax_anim 4, 0, 221, 0, 0, 0, 0,
ax_anim 10, 0, 222, 0, 0, 0, 0,
ax_anim_terminator
sLombreAnims_14_4:
ax_anim 10, 0, 218, 0, 0, 0, 0,
ax_anim 4, 0, 219, 0, 0, 0, 0,
ax_anim 18, 0, 220, 0, 0, 0, 0,
ax_anim 4, 0, 221, 0, 0, 0, 0,
ax_anim 10, 0, 222, 0, 0, 0, 0,
ax_anim_terminator
sLombreAnims_14_5:
ax_anim 10, 0, 218, 0, 0, 0, 0,
ax_anim 4, 0, 219, 0, 0, 0, 0,
ax_anim 18, 0, 220, 0, 0, 0, 0,
ax_anim 4, 0, 221, 0, 0, 0, 0,
ax_anim 10, 0, 222, 0, 0, 0, 0,
ax_anim_terminator
sLombreAnims_14_6:
ax_anim 10, 0, 218, 0, 0, 0, 0,
ax_anim 4, 0, 219, 0, 0, 0, 0,
ax_anim 18, 0, 220, 0, 0, 0, 0,
ax_anim 4, 0, 221, 0, 0, 0, 0,
ax_anim 10, 0, 222, 0, 0, 0, 0,
ax_anim_terminator
sLombreAnims_14_7:
ax_anim 10, 0, 218, 0, 0, 0, 0,
ax_anim 4, 0, 219, 0, 0, 0, 0,
ax_anim 18, 0, 220, 0, 0, 0, 0,
ax_anim 4, 0, 221, 0, 0, 0, 0,
ax_anim 10, 0, 222, 0, 0, 0, 0,
ax_anim_terminator
sLombreAnims_14_8:
ax_anim 10, 0, 218, 0, 0, 0, 0,
ax_anim 4, 0, 219, 0, 0, 0, 0,
ax_anim 18, 0, 220, 0, 0, 0, 0,
ax_anim 4, 0, 221, 0, 0, 0, 0,
ax_anim 10, 0, 222, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sLombreAnims_15_1:
ax_anim 10, 0, 223, 0, 0, 0, 0,
ax_anim_terminator
sLombreAnims_15_2:
ax_anim 10, 0, 223, 0, 0, 0, 0,
ax_anim_terminator
sLombreAnims_15_3:
ax_anim 10, 0, 223, 0, 0, 0, 0,
ax_anim_terminator
sLombreAnims_15_4:
ax_anim 10, 0, 223, 0, 0, 0, 0,
ax_anim_terminator
sLombreAnims_15_5:
ax_anim 10, 0, 223, 0, 0, 0, 0,
ax_anim_terminator
sLombreAnims_15_6:
ax_anim 10, 0, 223, 0, 0, 0, 0,
ax_anim_terminator
sLombreAnims_15_7:
ax_anim 10, 0, 223, 0, 0, 0, 0,
ax_anim_terminator
sLombreAnims_15_8:
ax_anim 10, 0, 223, 0, 0, 0, 0,
ax_anim_terminator
sLombreGfx1:
.incbin "baserom.gba", 0x1113774, 0x200
sLombreSprites1:
ax_sprite sLombreGfx1, 0x200
ax_sprite_terminator
sLombreGfx2:
.incbin "baserom.gba", 0x1113984, 0x200
sLombreSprites2:
ax_sprite sLombreGfx2, 0x200
ax_sprite_terminator
sLombreGfx3:
.incbin "baserom.gba", 0x1113B94, 0x200
sLombreSprites3:
ax_sprite sLombreGfx3, 0x200
ax_sprite_terminator
sLombreGfx4:
.incbin "baserom.gba", 0x1113DA4, 0x200
sLombreSprites4:
ax_sprite sLombreGfx4, 0x200
ax_sprite_terminator
sLombreGfx5:
.incbin "baserom.gba", 0x1113FB4, 0x200
sLombreSprites5:
ax_sprite sLombreGfx5, 0x200
ax_sprite_terminator
sLombreGfx6:
.incbin "baserom.gba", 0x11141C4, 0x200
sLombreSprites6:
ax_sprite sLombreGfx6, 0x200
ax_sprite_terminator
sLombreGfx7:
.incbin "baserom.gba", 0x11143D4, 0x200
sLombreSprites7:
ax_sprite sLombreGfx7, 0x200
ax_sprite_terminator
sLombreGfx8:
.incbin "baserom.gba", 0x11145E4, 0x200
sLombreSprites8:
ax_sprite sLombreGfx8, 0x200
ax_sprite_terminator
sLombreGfx9:
.incbin "baserom.gba", 0x11147F4, 0x200
sLombreSprites9:
ax_sprite sLombreGfx9, 0x200
ax_sprite_terminator
sLombreGfx10:
.incbin "baserom.gba", 0x1114A04, 0x200
sLombreSprites10:
ax_sprite sLombreGfx10, 0x200
ax_sprite_terminator
sLombreGfx11:
.incbin "baserom.gba", 0x1114C14, 0x200
sLombreSprites11:
ax_sprite sLombreGfx11, 0x200
ax_sprite_terminator
sLombreGfx12:
.incbin "baserom.gba", 0x1114E24, 0x200
sLombreSprites12:
ax_sprite sLombreGfx12, 0x200
ax_sprite_terminator
sLombreGfx13:
.incbin "baserom.gba", 0x1115034, 0x200
sLombreSprites13:
ax_sprite sLombreGfx13, 0x200
ax_sprite_terminator
sLombreGfx14:
.incbin "baserom.gba", 0x1115244, 0x200
sLombreSprites14:
ax_sprite sLombreGfx14, 0x200
ax_sprite_terminator
sLombreGfx15:
.incbin "baserom.gba", 0x1115454, 0x200
sLombreSprites15:
ax_sprite sLombreGfx15, 0x200
ax_sprite_terminator
sLombreGfx16:
.incbin "baserom.gba", 0x1115664, 0x200
sLombreSprites16:
ax_sprite sLombreGfx16, 0x200
ax_sprite_terminator
sLombreGfx17:
.incbin "baserom.gba", 0x1115874, 0x200
sLombreSprites17:
ax_sprite sLombreGfx17, 0x200
ax_sprite_terminator
sLombreGfx18:
.incbin "baserom.gba", 0x1115A84, 0x200
sLombreSprites18:
ax_sprite sLombreGfx18, 0x200
ax_sprite_terminator
sLombreGfx19:
.incbin "baserom.gba", 0x1115C94, 0x200
sLombreSprites19:
ax_sprite sLombreGfx19, 0x200
ax_sprite_terminator
sLombreGfx20:
.incbin "baserom.gba", 0x1115EA4, 0x200
sLombreSprites20:
ax_sprite sLombreGfx20, 0x200
ax_sprite_terminator
sLombreGfx21:
.incbin "baserom.gba", 0x11160B4, 0x200
sLombreSprites21:
ax_sprite sLombreGfx21, 0x200
ax_sprite_terminator
sLombreGfx22:
.incbin "baserom.gba", 0x11162C4, 0x200
sLombreSprites22:
ax_sprite sLombreGfx22, 0x200
ax_sprite_terminator
sLombreGfx23:
.incbin "baserom.gba", 0x11164D4, 0x200
sLombreSprites23:
ax_sprite sLombreGfx23, 0x200
ax_sprite_terminator
sLombreGfx24:
.incbin "baserom.gba", 0x11166E4, 0x200
sLombreSprites24:
ax_sprite sLombreGfx24, 0x200
ax_sprite_terminator
sLombreGfx25:
.incbin "baserom.gba", 0x11168F4, 0x60
sLombreGfx25_1:
.incbin "baserom.gba", 0x1116954, 0x60
sLombreGfx25_2:
.incbin "baserom.gba", 0x11169B4, 0x60
sLombreGfx25_3:
.incbin "baserom.gba", 0x1116A14, 0x60
sLombreSprites25:
ax_sprite 0, 0x20
ax_sprite sLombreGfx25, 0x60
ax_sprite 0, 0x20
ax_sprite sLombreGfx25_1, 0x60
ax_sprite 0, 0x20
ax_sprite sLombreGfx25_2, 0x60
ax_sprite 0, 0x20
ax_sprite sLombreGfx25_3, 0x60
ax_sprite_terminator
sLombreGfx26:
.incbin "baserom.gba", 0x1116ABC, 0x40
sLombreGfx26_1:
.incbin "baserom.gba", 0x1116AFC, 0x100
sLombreGfx26_2:
.incbin "baserom.gba", 0x1116BFC, 0x40
sLombreSprites26:
ax_sprite 0, 0x20
ax_sprite sLombreGfx26, 0x40
ax_sprite 0, 0x20
ax_sprite sLombreGfx26_1, 0x100
ax_sprite 0, 0x20
ax_sprite sLombreGfx26_2, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sLombreGfx27:
.incbin "baserom.gba", 0x1116C7C, 0x60
sLombreGfx27_1:
.incbin "baserom.gba", 0x1116CDC, 0x60
sLombreGfx27_2:
.incbin "baserom.gba", 0x1116D3C, 0x60
sLombreGfx27_3:
.incbin "baserom.gba", 0x1116D9C, 0x60
sLombreSprites27:
ax_sprite 0, 0x20
ax_sprite sLombreGfx27, 0x60
ax_sprite 0, 0x20
ax_sprite sLombreGfx27_1, 0x60
ax_sprite 0, 0x20
ax_sprite sLombreGfx27_2, 0x60
ax_sprite 0, 0x20
ax_sprite sLombreGfx27_3, 0x60
ax_sprite_terminator
sLombreGfx28:
.incbin "baserom.gba", 0x1116E44, 0x60
sLombreGfx28_1:
.incbin "baserom.gba", 0x1116EA4, 0x60
sLombreGfx28_2:
.incbin "baserom.gba", 0x1116F04, 0x60
sLombreGfx28_3:
.incbin "baserom.gba", 0x1116F64, 0x40
sLombreSprites28:
ax_sprite 0, 0x20
ax_sprite sLombreGfx28, 0x60
ax_sprite 0, 0x20
ax_sprite sLombreGfx28_1, 0x60
ax_sprite 0, 0x20
ax_sprite sLombreGfx28_2, 0x60
ax_sprite 0, 0x20
ax_sprite sLombreGfx28_3, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sLombreGfx29:
.incbin "baserom.gba", 0x1116FF4, 0x160
sLombreGfx29_1:
.incbin "baserom.gba", 0x1117154, 0x20
sLombreSprites29:
ax_sprite sLombreGfx29, 0x160
ax_sprite 0, 0x60
ax_sprite sLombreGfx29_1, 0x20
ax_sprite 0, 0x20
ax_sprite_terminator
sLombreGfx30:
.incbin "baserom.gba", 0x111719C, 0x60
sLombreGfx30_1:
.incbin "baserom.gba", 0x11171FC, 0x60
sLombreGfx30_2:
.incbin "baserom.gba", 0x111725C, 0x60
sLombreGfx30_3:
.incbin "baserom.gba", 0x11172BC, 0x40
sLombreSprites30:
ax_sprite sLombreGfx30, 0x60
ax_sprite 0, 0x20
ax_sprite sLombreGfx30_1, 0x60
ax_sprite 0, 0x20
ax_sprite sLombreGfx30_2, 0x60
ax_sprite 0, 0x40
ax_sprite sLombreGfx30_3, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sLombreGfx31:
.incbin "baserom.gba", 0x1117344, 0x60
sLombreGfx31_1:
.incbin "baserom.gba", 0x11173A4, 0x60
sLombreGfx31_2:
.incbin "baserom.gba", 0x1117404, 0x60
sLombreGfx31_3:
.incbin "baserom.gba", 0x1117464, 0x60
sLombreSprites31:
ax_sprite sLombreGfx31, 0x60
ax_sprite 0, 0x20
ax_sprite sLombreGfx31_1, 0x60
ax_sprite 0, 0x20
ax_sprite sLombreGfx31_2, 0x60
ax_sprite 0, 0x20
ax_sprite sLombreGfx31_3, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sLombreGfx32:
.incbin "baserom.gba", 0x111750C, 0x40
sLombreGfx32_1:
.incbin "baserom.gba", 0x111754C, 0x100
sLombreGfx32_2:
.incbin "baserom.gba", 0x111764C, 0x40
sLombreSprites32:
ax_sprite 0, 0x20
ax_sprite sLombreGfx32, 0x40
ax_sprite 0, 0x20
ax_sprite sLombreGfx32_1, 0x100
ax_sprite 0, 0x20
ax_sprite sLombreGfx32_2, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sLombreGfx33:
.incbin "baserom.gba", 0x11176CC, 0x100
sLombreSprites33:
ax_sprite sLombreGfx33, 0x100
ax_sprite_terminator
sLombreGfx34:
.incbin "baserom.gba", 0x11177DC, 0x100
sLombreSprites34:
ax_sprite sLombreGfx34, 0x100
ax_sprite_terminator
sLombreGfx35:
.incbin "baserom.gba", 0x11178EC, 0x60
sLombreGfx35_1:
.incbin "baserom.gba", 0x111794C, 0x60
sLombreGfx35_2:
.incbin "baserom.gba", 0x11179AC, 0x60
sLombreGfx35_3:
.incbin "baserom.gba", 0x1117A0C, 0x60
sLombreSprites35:
ax_sprite sLombreGfx35, 0x60
ax_sprite 0, 0x20
ax_sprite sLombreGfx35_1, 0x60
ax_sprite 0, 0x20
ax_sprite sLombreGfx35_2, 0x60
ax_sprite 0, 0x20
ax_sprite sLombreGfx35_3, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sLombreGfx36:
.incbin "baserom.gba", 0x1117AB4, 0x60
sLombreGfx36_1:
.incbin "baserom.gba", 0x1117B14, 0x60
sLombreSprites36:
ax_sprite sLombreGfx36, 0x60
ax_sprite 0, 0x20
ax_sprite sLombreGfx36_1, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sLombreGfx37:
.incbin "baserom.gba", 0x1117B9C, 0xE0
sLombreSprites37:
ax_sprite sLombreGfx37, 0xe0
ax_sprite 0, 0x20
ax_sprite_terminator
sLombreGfx38:
.incbin "baserom.gba", 0x1117C94, 0x20
sLombreGfx38_1:
.incbin "baserom.gba", 0x1117CB4, 0x60
sLombreGfx38_2:
.incbin "baserom.gba", 0x1117D14, 0xC0
sLombreSprites38:
ax_sprite 0, 0x20
ax_sprite sLombreGfx38, 0x20
ax_sprite 0, 0x60
ax_sprite sLombreGfx38_1, 0x60
ax_sprite 0, 0x20
ax_sprite sLombreGfx38_2, 0xc0
ax_sprite 0, 0x20
ax_sprite_terminator
sLombreGfx39:
.incbin "baserom.gba", 0x1117E14, 0x20
sLombreGfx39_1:
.incbin "baserom.gba", 0x1117E34, 0x60
sLombreSprites39:
ax_sprite sLombreGfx39, 0x20
ax_sprite 0, 0x20
ax_sprite sLombreGfx39_1, 0x60
ax_sprite 0, 0x60
ax_sprite_terminator
sLombreGfx40:
.incbin "baserom.gba", 0x1117EBC, 0x60
sLombreGfx40_1:
.incbin "baserom.gba", 0x1117F1C, 0x60
sLombreSprites40:
ax_sprite sLombreGfx40, 0x60
ax_sprite 0, 0x20
ax_sprite sLombreGfx40_1, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sLombreGfx41:
.incbin "baserom.gba", 0x1117FA4, 0x20
sLombreGfx41_1:
.incbin "baserom.gba", 0x1117FC4, 0x60
sLombreGfx41_2:
.incbin "baserom.gba", 0x1118024, 0x60
sLombreGfx41_3:
.incbin "baserom.gba", 0x1118084, 0x60
sLombreSprites41:
ax_sprite 0, 0x40
ax_sprite sLombreGfx41, 0x20
ax_sprite 0, 0x40
ax_sprite sLombreGfx41_1, 0x60
ax_sprite 0, 0x20
ax_sprite sLombreGfx41_2, 0x60
ax_sprite 0, 0x20
ax_sprite sLombreGfx41_3, 0x60
ax_sprite_terminator
sLombreGfx42:
.incbin "baserom.gba", 0x111812C, 0x20
sLombreGfx42_1:
.incbin "baserom.gba", 0x111814C, 0x20
sLombreGfx42_2:
.incbin "baserom.gba", 0x111816C, 0x40
sLombreSprites42:
ax_sprite 0, 0x40
ax_sprite sLombreGfx42, 0x20
ax_sprite 0, 0x20
ax_sprite sLombreGfx42_1, 0x20
ax_sprite 0, 0x20
ax_sprite sLombreGfx42_2, 0x40
ax_sprite_terminator
sLombreGfx43:
.incbin "baserom.gba", 0x11181E4, 0x20
sLombreGfx43_1:
.incbin "baserom.gba", 0x1118204, 0x40
sLombreSprites43:
ax_sprite sLombreGfx43, 0x20
ax_sprite 0, 0x20
ax_sprite sLombreGfx43_1, 0x40
ax_sprite_terminator
sLombreGfx44:
.incbin "baserom.gba", 0x1118264, 0x140
sLombreGfx44_1:
.incbin "baserom.gba", 0x11183A4, 0x20
sLombreSprites44:
ax_sprite 0, 0x20
ax_sprite sLombreGfx44, 0x140
ax_sprite 0, 0x60
ax_sprite sLombreGfx44_1, 0x20
ax_sprite 0, 0x20
ax_sprite_terminator
sLombreGfx45:
.incbin "baserom.gba", 0x11183F4, 0x20
sLombreGfx45_1:
.incbin "baserom.gba", 0x1118414, 0x60
sLombreGfx45_2:
.incbin "baserom.gba", 0x1118474, 0x40
sLombreSprites45:
ax_sprite sLombreGfx45, 0x20
ax_sprite 0, 0x20
ax_sprite sLombreGfx45_1, 0x60
ax_sprite 0, 0x20
ax_sprite sLombreGfx45_2, 0x40
ax_sprite_terminator
sLombreGfx46:
.incbin "baserom.gba", 0x11184E4, 0x40
sLombreGfx46_1:
.incbin "baserom.gba", 0x1118524, 0x60
sLombreGfx46_2:
.incbin "baserom.gba", 0x1118584, 0x20
sLombreSprites46:
ax_sprite sLombreGfx46, 0x40
ax_sprite 0, 0x20
ax_sprite sLombreGfx46_1, 0x60
ax_sprite 0, 0x20
ax_sprite sLombreGfx46_2, 0x20
ax_sprite_terminator
sLombreGfx47:
.incbin "baserom.gba", 0x11185D4, 0x100
sLombreGfx47_1:
.incbin "baserom.gba", 0x11186D4, 0x60
sLombreGfx47_2:
.incbin "baserom.gba", 0x1118734, 0x20
sLombreSprites47:
ax_sprite sLombreGfx47, 0x100
ax_sprite 0, 0x20
ax_sprite sLombreGfx47_1, 0x60
ax_sprite 0, 0x20
ax_sprite sLombreGfx47_2, 0x20
ax_sprite 0, 0x40
ax_sprite_terminator
sLombreGfx48:
.incbin "baserom.gba", 0x111878C, 0x60
sLombreGfx48_1:
.incbin "baserom.gba", 0x11187EC, 0x80
sLombreGfx48_2:
.incbin "baserom.gba", 0x111886C, 0x60
sLombreGfx48_3:
.incbin "baserom.gba", 0x11188CC, 0x20
sLombreSprites48:
ax_sprite sLombreGfx48, 0x60
ax_sprite 0, 0x20
ax_sprite sLombreGfx48_1, 0x80
ax_sprite 0, 0x20
ax_sprite sLombreGfx48_2, 0x60
ax_sprite 0, 0x20
ax_sprite sLombreGfx48_3, 0x20
ax_sprite 0, 0x40
ax_sprite_terminator
sLombreGfx49:
.incbin "baserom.gba", 0x1118934, 0x20
sLombreGfx49_1:
.incbin "baserom.gba", 0x1118954, 0x60
sLombreGfx49_2:
.incbin "baserom.gba", 0x11189B4, 0x60
sLombreGfx49_3:
.incbin "baserom.gba", 0x1118A14, 0x60
sLombreSprites49:
ax_sprite 0, 0x20
ax_sprite sLombreGfx49, 0x20
ax_sprite 0, 0x40
ax_sprite sLombreGfx49_1, 0x60
ax_sprite 0, 0x20
ax_sprite sLombreGfx49_2, 0x60
ax_sprite 0, 0x20
ax_sprite sLombreGfx49_3, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sLombreGfx50:
.incbin "baserom.gba", 0x1118AC4, 0x20
sLombreGfx50_1:
.incbin "baserom.gba", 0x1118AE4, 0x60
sLombreGfx50_2:
.incbin "baserom.gba", 0x1118B44, 0x60
sLombreGfx50_3:
.incbin "baserom.gba", 0x1118BA4, 0x60
sLombreSprites50:
ax_sprite 0, 0x40
ax_sprite sLombreGfx50, 0x20
ax_sprite 0, 0x20
ax_sprite sLombreGfx50_1, 0x60
ax_sprite 0, 0x20
ax_sprite sLombreGfx50_2, 0x60
ax_sprite 0, 0x40
ax_sprite sLombreGfx50_3, 0x60
ax_sprite_terminator
sLombreGfx51:
.incbin "baserom.gba", 0x1118C4C, 0x40
sLombreGfx51_1:
.incbin "baserom.gba", 0x1118C8C, 0xE0
sLombreGfx51_2:
.incbin "baserom.gba", 0x1118D6C, 0x80
sLombreSprites51:
ax_sprite 0, 0x20
ax_sprite sLombreGfx51, 0x40
ax_sprite 0, 0x20
ax_sprite sLombreGfx51_1, 0xe0
ax_sprite 0, 0x20
ax_sprite sLombreGfx51_2, 0x80
ax_sprite_terminator
sLombreGfx52:
.incbin "baserom.gba", 0x1118E24, 0x60
sLombreGfx52_1:
.incbin "baserom.gba", 0x1118E84, 0x60
sLombreGfx52_2:
.incbin "baserom.gba", 0x1118EE4, 0x60
sLombreSprites52:
ax_sprite 0, 0xa0
ax_sprite sLombreGfx52, 0x60
ax_sprite 0, 0x20
ax_sprite sLombreGfx52_1, 0x60
ax_sprite 0, 0x20
ax_sprite sLombreGfx52_2, 0x60
ax_sprite_terminator
sLombreGfx53:
.incbin "baserom.gba", 0x1118F7C, 0x20
sLombreGfx53_1:
.incbin "baserom.gba", 0x1118F9C, 0x60
sLombreGfx53_2:
.incbin "baserom.gba", 0x1118FFC, 0x60
sLombreGfx53_3:
.incbin "baserom.gba", 0x111905C, 0x60
sLombreSprites53:
ax_sprite 0, 0x40
ax_sprite sLombreGfx53, 0x20
ax_sprite 0, 0x40
ax_sprite sLombreGfx53_1, 0x60
ax_sprite 0, 0x20
ax_sprite sLombreGfx53_2, 0x60
ax_sprite 0, 0x20
ax_sprite sLombreGfx53_3, 0x60
ax_sprite_terminator
sLombreGfx54:
.incbin "baserom.gba", 0x1119104, 0x60
sLombreGfx54_1:
.incbin "baserom.gba", 0x1119164, 0x60
sLombreGfx54_2:
.incbin "baserom.gba", 0x11191C4, 0x60
sLombreGfx54_3:
.incbin "baserom.gba", 0x1119224, 0x60
sLombreSprites54:
ax_sprite 0, 0x20
ax_sprite sLombreGfx54, 0x60
ax_sprite 0, 0x20
ax_sprite sLombreGfx54_1, 0x60
ax_sprite 0, 0x20
ax_sprite sLombreGfx54_2, 0x60
ax_sprite 0, 0x20
ax_sprite sLombreGfx54_3, 0x60
ax_sprite_terminator
sLombreGfx55:
.incbin "baserom.gba", 0x11192CC, 0x180
sLombreGfx55_1:
.incbin "baserom.gba", 0x111944C, 0x40
sLombreSprites55:
ax_sprite sLombreGfx55, 0x180
ax_sprite 0, 0x20
ax_sprite sLombreGfx55_1, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sLombreGfx56:
.incbin "baserom.gba", 0x11194B4, 0x60
sLombreGfx56_1:
.incbin "baserom.gba", 0x1119514, 0x60
sLombreGfx56_2:
.incbin "baserom.gba", 0x1119574, 0x60
sLombreGfx56_3:
.incbin "baserom.gba", 0x11195D4, 0x60
sLombreSprites56:
ax_sprite sLombreGfx56, 0x60
ax_sprite 0, 0x20
ax_sprite sLombreGfx56_1, 0x60
ax_sprite 0, 0x20
ax_sprite sLombreGfx56_2, 0x60
ax_sprite 0, 0x20
ax_sprite sLombreGfx56_3, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sLombreGfx57:
.incbin "baserom.gba", 0x111967C, 0x20
sLombreGfx57_1:
.incbin "baserom.gba", 0x111969C, 0x60
sLombreGfx57_2:
.incbin "baserom.gba", 0x11196FC, 0x60
sLombreGfx57_3:
.incbin "baserom.gba", 0x111975C, 0x60
sLombreSprites57:
ax_sprite 0, 0x20
ax_sprite sLombreGfx57, 0x20
ax_sprite 0, 0x40
ax_sprite sLombreGfx57_1, 0x60
ax_sprite 0, 0x20
ax_sprite sLombreGfx57_2, 0x60
ax_sprite 0, 0x20
ax_sprite sLombreGfx57_3, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sLombreGfx58:
.incbin "baserom.gba", 0x111980C, 0x60
sLombreGfx58_1:
.incbin "baserom.gba", 0x111986C, 0x60
sLombreGfx58_2:
.incbin "baserom.gba", 0x11198CC, 0x60
sLombreSprites58:
ax_sprite 0, 0x80
ax_sprite sLombreGfx58, 0x60
ax_sprite 0, 0x20
ax_sprite sLombreGfx58_1, 0x60
ax_sprite 0, 0x20
ax_sprite sLombreGfx58_2, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sLombreGfx59:
.incbin "baserom.gba", 0x111996C, 0x200
sLombreSprites59:
ax_sprite sLombreGfx59, 0x200
ax_sprite_terminator
sLombreGfx60:
.incbin "baserom.gba", 0x1119B7C, 0x200
sLombreSprites60:
ax_sprite sLombreGfx60, 0x200
ax_sprite_terminator
sLombreGfx61:
.incbin "baserom.gba", 0x1119D8C, 0x200
sLombreSprites61:
ax_sprite sLombreGfx61, 0x200
ax_sprite_terminator
sLombreGfx62:
.incbin "baserom.gba", 0x1119F9C, 0x200
sLombreSprites62:
ax_sprite sLombreGfx62, 0x200
ax_sprite_terminator
sLombreGfx63:
.incbin "baserom.gba", 0x111A1AC, 0x200
sLombreSprites63:
ax_sprite sLombreGfx63, 0x200
ax_sprite_terminator
sLombreGfx64:
.incbin "baserom.gba", 0x111A3BC, 0x200
sLombreSprites64:
ax_sprite sLombreGfx64, 0x200
ax_sprite_terminator
sLombreGfx65:
.incbin "baserom.gba", 0x111A5CC, 0x200
sLombreSprites65:
ax_sprite sLombreGfx65, 0x200
ax_sprite_terminator
sLombreGfx66:
.incbin "baserom.gba", 0x111A7DC, 0x200
sLombreSprites66:
ax_sprite sLombreGfx66, 0x200
ax_sprite_terminator
sLombreGfx67:
.incbin "baserom.gba", 0x111A9EC, 0x200
sLombreSprites67:
ax_sprite sLombreGfx67, 0x200
ax_sprite_terminator
sLombreGfx68:
.incbin "baserom.gba", 0x111ABFC, 0x200
sLombreSprites68:
ax_sprite sLombreGfx68, 0x200
ax_sprite_terminator
sLombreGfx69:
.incbin "baserom.gba", 0x111AE0C, 0x80
sLombreSprites69:
ax_sprite sLombreGfx69, 0x80
ax_sprite_terminator
sLombreGfx70:
.incbin "baserom.gba", 0x111AE9C, 0x100
sLombreSprites70:
ax_sprite sLombreGfx70, 0x100
ax_sprite_terminator
sLombreGfx71:
.incbin "baserom.gba", 0x111AFAC, 0x80
sLombreSprites71:
ax_sprite sLombreGfx71, 0x80
ax_sprite_terminator
sLombreGfx72:
.incbin "baserom.gba", 0x111B03C, 0x80
sLombreSprites72:
ax_sprite sLombreGfx72, 0x80
ax_sprite_terminator
sLombreGfx73:
.incbin "baserom.gba", 0x111B0CC, 0x100
sLombreSprites73:
ax_sprite sLombreGfx73, 0x100
ax_sprite_terminator
sLombreGfx74:
.incbin "baserom.gba", 0x111B1DC, 0x100
sLombreSprites74:
ax_sprite sLombreGfx74, 0x100
ax_sprite_terminator
sLombreGfx75:
.incbin "baserom.gba", 0x111B2EC, 0x80
sLombreSprites75:
ax_sprite sLombreGfx75, 0x80
ax_sprite_terminator
sLombreGfx76:
.incbin "baserom.gba", 0x111B37C, 0x80
sLombreSprites76:
ax_sprite sLombreGfx76, 0x80
ax_sprite_terminator
sLombreGfx77:
.incbin "baserom.gba", 0x111B40C, 0x80
sLombreSprites77:
ax_sprite sLombreGfx77, 0x80
ax_sprite_terminator
sLombreGfx78:
.incbin "baserom.gba", 0x111B49C, 0x100
sLombreSprites78:
ax_sprite sLombreGfx78, 0x100
ax_sprite_terminator
sLombreGfx79:
.incbin "baserom.gba", 0x111B5AC, 0x80
sLombreSprites79:
ax_sprite sLombreGfx79, 0x80
ax_sprite_terminator
sLombreGfx80:
.incbin "baserom.gba", 0x111B63C, 0x80
sLombreSprites80:
ax_sprite sLombreGfx80, 0x80
ax_sprite_terminator
sLombreGfx81:
.incbin "baserom.gba", 0x111B6CC, 0x100
sLombreSprites81:
ax_sprite sLombreGfx81, 0x100
ax_sprite_terminator
sAxPosesLombre:
.4byte sLombrePose1
.4byte sLombrePose2
.4byte sLombrePose3
.4byte sLombrePose4
.4byte sLombrePose5
.4byte sLombrePose6
.4byte sLombrePose7
.4byte sLombrePose8
.4byte sLombrePose9
.4byte sLombrePose10
.4byte sLombrePose11
.4byte sLombrePose12
.4byte sLombrePose13
.4byte sLombrePose14
.4byte sLombrePose15
.4byte sLombrePose16
.4byte sLombrePose17
.4byte sLombrePose18
.4byte sLombrePose19
.4byte sLombrePose20
.4byte sLombrePose21
.4byte sLombrePose22
.4byte sLombrePose23
.4byte sLombrePose24
.4byte sLombrePose25
.4byte sLombrePose26
.4byte sLombrePose27
.4byte sLombrePose28
.4byte sLombrePose29
.4byte sLombrePose30
.4byte sLombrePose31
.4byte sLombrePose32
.4byte sLombrePose33
.4byte sLombrePose34
.4byte sLombrePose35
.4byte sLombrePose36
.4byte sLombrePose37
.4byte sLombrePose38
.4byte sLombrePose39
.4byte sLombrePose40
.4byte sLombrePose41
.4byte sLombrePose42
.4byte sLombrePose43
.4byte sLombrePose44
.4byte sLombrePose45
.4byte sLombrePose46
.4byte sLombrePose47
.4byte sLombrePose48
.4byte sLombrePose49
.4byte sLombrePose50
.4byte sLombrePose51
.4byte sLombrePose52
.4byte sLombrePose53
.4byte sLombrePose54
.4byte sLombrePose55
.4byte sLombrePose56
.4byte sLombrePose57
.4byte sLombrePose58
.4byte sLombrePose59
.4byte sLombrePose60
.4byte sLombrePose61
.4byte sLombrePose62
.4byte sLombrePose63
.4byte sLombrePose64
.4byte sLombrePose65
.4byte sLombrePose66
.4byte sLombrePose67
.4byte sLombrePose68
.4byte sLombrePose69
.4byte sLombrePose70
.4byte sLombrePose71
.4byte sLombrePose72
.4byte sLombrePose73
.4byte sLombrePose74
.4byte sLombrePose75
.4byte sLombrePose76
.4byte sLombrePose77
.4byte sLombrePose78
.4byte sLombrePose79
.4byte sLombrePose80
.4byte sLombrePose81
.4byte sLombrePose82
.4byte sLombrePose83
.4byte sLombrePose84
.4byte sLombrePose85
.4byte sLombrePose86
.4byte sLombrePose87
.4byte sLombrePose88
.4byte sLombrePose89
.4byte sLombrePose90
.4byte sLombrePose91
.4byte sLombrePose92
.4byte sLombrePose93
.4byte sLombrePose94
.4byte sLombrePose95
.4byte sLombrePose96
.4byte sLombrePose97
.4byte sLombrePose98
.4byte sLombrePose99
.4byte sLombrePose100
.4byte sLombrePose101
.4byte sLombrePose102
.4byte sLombrePose103
.4byte sLombrePose104
.4byte sLombrePose105
.4byte sLombrePose106
.4byte sLombrePose107
.4byte sLombrePose108
.4byte sLombrePose109
.4byte sLombrePose110
.4byte sLombrePose111
.4byte sLombrePose112
.4byte sLombrePose113
.4byte sLombrePose114
.4byte sLombrePose115
.4byte sLombrePose116
.4byte sLombrePose117
.4byte sLombrePose118
.4byte sLombrePose119
.4byte sLombrePose120
.4byte sLombrePose121
.4byte sLombrePose122
.4byte sLombrePose123
.4byte sLombrePose124
.4byte sLombrePose125
.4byte sLombrePose126
.4byte sLombrePose127
.4byte sLombrePose128
.4byte sLombrePose129
.4byte sLombrePose130
.4byte sLombrePose131
.4byte sLombrePose132
.4byte sLombrePose133
.4byte sLombrePose134
.4byte sLombrePose135
.4byte sLombrePose136
.4byte sLombrePose137
.4byte sLombrePose138
.4byte sLombrePose139
.4byte sLombrePose140
.4byte sLombrePose141
.4byte sLombrePose142
.4byte sLombrePose143
.4byte sLombrePose144
.4byte sLombrePose145
.4byte sLombrePose146
.4byte sLombrePose147
.4byte sLombrePose148
.4byte sLombrePose149
.4byte sLombrePose150
.4byte sLombrePose151
.4byte sLombrePose152
.4byte sLombrePose153
.4byte sLombrePose154
.4byte sLombrePose155
.4byte sLombrePose156
.4byte sLombrePose157
.4byte sLombrePose158
.4byte sLombrePose159
.4byte sLombrePose160
.4byte sLombrePose161
.4byte sLombrePose162
.4byte sLombrePose163
.4byte sLombrePose164
.4byte sLombrePose165
.4byte sLombrePose166
.4byte sLombrePose167
.4byte sLombrePose168
.4byte sLombrePose169
.4byte sLombrePose170
.4byte sLombrePose171
.4byte sLombrePose172
.4byte sLombrePose173
.4byte sLombrePose174
.4byte sLombrePose175
.4byte sLombrePose176
.4byte sLombrePose177
.4byte sLombrePose178
.4byte sLombrePose179
.4byte sLombrePose180
.4byte sLombrePose181
.4byte sLombrePose182
.4byte sLombrePose183
.4byte sLombrePose184
.4byte sLombrePose185
.4byte sLombrePose186
.4byte sLombrePose187
.4byte sLombrePose188
.4byte sLombrePose189
.4byte sLombrePose190
.4byte sLombrePose191
.4byte sLombrePose192
.4byte sLombrePose193
.4byte sLombrePose194
.4byte sLombrePose195
.4byte sLombrePose196
.4byte sLombrePose197
.4byte sLombrePose198
.4byte sLombrePose199
.4byte sLombrePose200
.4byte sLombrePose201
.4byte sLombrePose202
.4byte sLombrePose203
.4byte sLombrePose204
.4byte sLombrePose205
.4byte sLombrePose206
.4byte sLombrePose207
.4byte sLombrePose208
.4byte sLombrePose209
.4byte sLombrePose210
.4byte sLombrePose211
.4byte sLombrePose212
.4byte sLombrePose213
.4byte sLombrePose214
.4byte sLombrePose215
.4byte sLombrePose216
.4byte sLombrePose217
.4byte sLombrePose218
.4byte sLombrePose219
.4byte sLombrePose220
.4byte sLombrePose221
.4byte sLombrePose222
.4byte sLombrePose223
.4byte sLombrePose224
.4byte sLombrePose225
.4byte sLombrePose226
.4byte sLombrePose227
.4byte sLombrePose228
sAxPositionsLombre:
.2byte   -1,   -7, 	 -10,   -1, 	   9,   -1, 	  -1,   -9
.2byte   -2,   -6, 	 -11,   -1, 	   7,    0, 	  -2,   -8
.2byte    0,   -6, 	  -8,    0, 	  10,   -1, 	   0,   -8
.2byte    2,   -7, 	  -7,   -1, 	   7,   -4, 	  -1,   -7
.2byte    3,   -6, 	  -4,    0, 	   8,   -4, 	   0,   -6
.2byte    1,   -5, 	  -8,    0, 	   6,   -2, 	  -2,   -5
.2byte    4,   -7, 	   1,   -1, 	   3,   -4, 	  -2,   -7
.2byte    5,   -6, 	   2,   -1, 	  -3,   -3, 	  -1,   -6
.2byte    4,   -5, 	   0,    1, 	   4,   -2, 	  -2,   -5
.2byte    5,   -8, 	   6,   -2, 	  -6,   -4, 	  -1,   -7
.2byte    4,   -7, 	   5,   -2, 	  -7,   -4, 	  -2,   -6
.2byte    6,   -7, 	   6,   -1, 	  -2,   -4, 	   0,   -6
.2byte   -1,  -12, 	   8,   -4, 	 -10,   -4, 	  -1,   -8
.2byte    1,  -12, 	   9,   -3, 	  -9,   -4, 	  -1,   -7
.2byte   -3,  -12, 	   7,   -4, 	 -11,   -3, 	  -1,   -7
.2byte   -6,   -8, 	   5,   -4, 	  -8,   -2, 	   0,   -7
.2byte   -5,   -7, 	   6,   -4, 	  -7,   -2, 	   0,   -6
.2byte   -7,   -7, 	   1,   -5, 	  -8,   -1, 	  -1,   -6
.2byte   -6,   -7, 	  -5,   -4, 	  -3,   -1, 	  -1,   -7
.2byte   -7,   -6, 	   1,   -2, 	  -4,   -1, 	  -2,   -6
.2byte   -6,   -5, 	  -5,   -2, 	  -2,    1, 	  -1,   -5
.2byte   -4,   -7, 	  -9,   -4, 	   5,   -1, 	  -1,   -7
.2byte   -5,   -6, 	 -10,   -4, 	   2,    0, 	  -2,   -6
.2byte   -3,   -5, 	  -8,   -2, 	   6,    0, 	   0,   -5
.2byte    0,   -5, 	   4,   -4, 	   8,   -6, 	   0,   -7
.2byte   -2,   -6, 	 -11,   -1, 	   7,    0, 	  -2,   -8
.2byte    0,   -6, 	  -8,    0, 	  10,   -1, 	   0,   -8
.2byte    3,   -5, 	 -10,   -8, 	  -3,   -3, 	  -2,   -6
.2byte    4,   -7, 	  -3,   -1, 	   9,   -5, 	   1,   -7
.2byte    2,   -5, 	  -7,    0, 	   7,   -2, 	  -1,   -5
.2byte    5,   -5, 	  -8,   -5, 	   8,   -3, 	  -1,   -7
.2byte    5,   -6, 	   2,   -1, 	  -3,   -3, 	  -1,   -6
.2byte    4,   -5, 	   0,    1, 	   4,   -2, 	  -2,   -5
.2byte    6,  -10, 	   4,   -5, 	   8,   -6, 	   1,   -8
.2byte    4,   -7, 	   5,   -2, 	  -7,   -4, 	  -2,   -6
.2byte    6,   -7, 	   6,   -1, 	  -2,   -4, 	   0,   -6
.2byte   -3,   -9, 	  -6,   -7, 	  -7,   -3, 	   0,   -7
.2byte    1,  -12, 	   9,   -3, 	  -9,   -4, 	  -1,   -7
.2byte   -2,  -12, 	   8,   -4, 	 -10,   -3, 	   0,   -7
.2byte   -5,   -9, 	  -9,   -6, 	  -6,   -5, 	  -1,   -9
.2byte   -4,   -7, 	   7,   -4, 	  -6,   -2, 	   1,   -6
.2byte   -6,   -7, 	   2,   -5, 	  -7,   -1, 	   0,   -6
.2byte   -5,   -5, 	  -9,   -3, 	   6,   -6, 	   0,   -6
.2byte   -6,   -6, 	   2,   -2, 	  -3,   -1, 	  -1,   -6
.2byte   -5,   -5, 	  -4,   -2, 	  -1,    1, 	   0,   -5
.2byte   -4,   -5, 	   2,   -3, 	   9,   -8, 	   0,   -7
.2byte   -5,   -7, 	 -10,   -5, 	   2,   -1, 	  -2,   -7
.2byte   -3,   -5, 	  -8,   -2, 	   6,    0, 	   0,   -5
.2byte   -1,   -7, 	 -10,   -1, 	   9,   -1, 	  -1,   -9
.2byte    3,   -4, 	   7,   -3, 	  11,   -5, 	   3,   -6
.2byte    3,   -4, 	   7,   -3, 	  11,   -5, 	   3,   -6
.2byte   -4,   -4, 	 -12,   -5, 	  -9,   -3, 	  -4,   -6
.2byte   -4,   -4, 	 -12,   -5, 	  -9,   -3, 	  -4,   -6
.2byte    2,   -7, 	  -7,   -1, 	   7,   -4, 	  -1,   -7
.2byte    2,   -4, 	 -11,   -7, 	  -4,   -2, 	  -3,   -5
.2byte    2,   -4, 	 -11,   -7, 	  -4,   -2, 	  -3,   -5
.2byte    4,   -5, 	   8,   -5, 	   3,   -3, 	   0,   -6
.2byte    4,   -5, 	   8,   -5, 	   3,   -3, 	   0,   -6
.2byte    4,   -7, 	   1,   -1, 	   3,   -4, 	  -2,   -7
.2byte    7,   -5, 	  -6,   -5, 	  10,   -3, 	   1,   -7
.2byte    7,   -5, 	  -6,   -5, 	  10,   -3, 	   1,   -7
.2byte    7,   -7, 	  10,   -7, 	  -1,   -6, 	   2,   -7
.2byte    7,   -7, 	  10,   -7, 	  -1,   -6, 	   2,   -7
.2byte    5,   -8, 	   6,   -2, 	  -6,   -4, 	  -1,   -7
.2byte    6,  -10, 	   4,   -5, 	   8,   -6, 	   1,   -8
.2byte    6,  -10, 	   4,   -5, 	   8,   -6, 	   1,   -8
.2byte    3,  -13, 	  -9,  -10, 	  -4,   -6, 	   0,   -8
.2byte    3,  -13, 	  -9,  -10, 	  -4,   -6, 	   0,   -8
.2byte   -1,  -12, 	   8,   -4, 	 -10,   -4, 	  -1,   -8
.2byte   -5,  -12, 	  -8,  -10, 	  -9,   -6, 	  -2,  -10
.2byte   -5,  -12, 	  -8,  -10, 	  -9,   -6, 	  -2,  -10
.2byte    4,  -12, 	   8,   -6, 	   7,  -10, 	   1,  -10
.2byte    4,  -12, 	   8,   -6, 	   7,  -10, 	   1,  -10
.2byte   -6,   -8, 	   5,   -4, 	  -8,   -2, 	   0,   -7
.2byte   -6,   -9, 	 -10,   -6, 	  -7,   -5, 	  -2,   -9
.2byte   -6,   -9, 	 -10,   -6, 	  -7,   -5, 	  -2,   -9
.2byte    0,  -10, 	   2,   -8, 	   7,  -10, 	  -2,   -9
.2byte    0,  -10, 	   2,   -8, 	   7,  -10, 	  -2,   -9
.2byte   -6,   -7, 	  -5,   -4, 	  -3,   -1, 	  -1,   -7
.2byte   -8,   -5, 	 -12,   -3, 	   3,   -6, 	  -3,   -6
.2byte   -8,   -5, 	 -12,   -3, 	   3,   -6, 	  -3,   -6
.2byte   -9,   -7, 	  -2,   -8, 	 -13,   -6, 	  -4,   -7
.2byte   -9,   -7, 	  -2,   -8, 	 -13,   -6, 	  -4,   -7
.2byte   -4,   -7, 	  -9,   -4, 	   5,   -1, 	  -1,   -7
.2byte   -4,   -4, 	   2,   -2, 	   9,   -7, 	   0,   -6
.2byte   -4,   -4, 	   2,   -2, 	   9,   -7, 	   0,   -6
.2byte   -6,   -5, 	  -6,   -6, 	 -10,   -5, 	  -2,   -6
.2byte   -6,   -5, 	  -6,   -6, 	 -10,   -5, 	  -2,   -6
.2byte   -1,   -7, 	 -10,   -1, 	   9,   -1, 	  -1,   -9
.2byte   -1,   -3, 	  -9,    1, 	   7,    1, 	  -1,   -6
.2byte    2,   -7, 	  -7,   -1, 	   7,   -4, 	  -1,   -7
.2byte    3,   -3, 	  -3,    1, 	   9,   -1, 	  -1,   -4
.2byte    4,   -7, 	   1,   -1, 	   3,   -4, 	  -2,   -7
.2byte    8,   -5, 	   5,    1, 	   8,   -1, 	   1,   -5
.2byte    5,   -8, 	   6,   -2, 	  -6,   -4, 	  -1,   -7
.2byte    7,   -9, 	   8,   -2, 	   1,   -4, 	   0,   -7
.2byte   -1,  -12, 	   8,   -4, 	 -10,   -4, 	  -1,   -8
.2byte   -1,  -13, 	   7,   -7, 	  -9,   -7, 	  -1,   -9
.2byte   -6,   -8, 	   5,   -4, 	  -8,   -2, 	   0,   -7
.2byte   -9,   -9, 	  -2,   -6, 	 -10,   -2, 	  -3,   -8
.2byte   -6,   -7, 	  -5,   -4, 	  -3,   -1, 	  -1,   -7
.2byte  -10,   -5, 	 -10,   -1, 	  -7,    2, 	  -3,   -5
.2byte   -4,   -7, 	  -9,   -4, 	   5,   -1, 	  -1,   -7
.2byte   -5,   -3, 	 -11,   -1, 	   1,    2, 	  -1,   -5
.2byte   -1,   -7, 	 -10,   -1, 	   9,   -1, 	  -1,   -9
.2byte    3,   -4, 	   7,   -3, 	  11,   -5, 	   3,   -6
.2byte    3,   -4, 	   7,   -3, 	  11,   -5, 	   3,   -6
.2byte   -4,   -4, 	 -12,   -5, 	  -9,   -3, 	  -4,   -6
.2byte   -4,   -4, 	 -12,   -5, 	  -9,   -3, 	  -4,   -6
.2byte    2,   -7, 	  -7,   -1, 	   7,   -4, 	  -1,   -7
.2byte    2,   -4, 	 -11,   -7, 	  -4,   -2, 	  -3,   -5
.2byte    2,   -4, 	 -11,   -7, 	  -4,   -2, 	  -3,   -5
.2byte    4,   -5, 	   8,   -5, 	   3,   -3, 	   0,   -6
.2byte    4,   -5, 	   8,   -5, 	   3,   -3, 	   0,   -6
.2byte    4,   -7, 	   1,   -1, 	   3,   -4, 	  -2,   -7
.2byte    7,   -5, 	  -6,   -5, 	  10,   -3, 	   1,   -7
.2byte    7,   -5, 	  -6,   -5, 	  10,   -3, 	   1,   -7
.2byte    7,   -7, 	  10,   -7, 	  -1,   -6, 	   2,   -7
.2byte    7,   -7, 	  10,   -7, 	  -1,   -6, 	   2,   -7
.2byte    5,   -8, 	   6,   -2, 	  -6,   -4, 	  -1,   -7
.2byte    6,  -10, 	   4,   -5, 	   8,   -6, 	   1,   -8
.2byte    6,  -10, 	   4,   -5, 	   8,   -6, 	   1,   -8
.2byte    3,  -13, 	  -9,  -10, 	  -4,   -6, 	   0,   -8
.2byte    3,  -13, 	  -9,  -10, 	  -4,   -6, 	   0,   -8
.2byte   -1,  -12, 	   8,   -4, 	 -10,   -4, 	  -1,   -8
.2byte   -5,  -12, 	  -8,  -10, 	  -9,   -6, 	  -2,  -10
.2byte   -5,  -12, 	  -8,  -10, 	  -9,   -6, 	  -2,  -10
.2byte    4,  -12, 	   8,   -6, 	   7,  -10, 	   1,  -10
.2byte    4,  -12, 	   8,   -6, 	   7,  -10, 	   1,  -10
.2byte   -6,   -8, 	   5,   -4, 	  -8,   -2, 	   0,   -7
.2byte   -6,   -9, 	 -10,   -6, 	  -7,   -5, 	  -2,   -9
.2byte   -6,   -9, 	 -10,   -6, 	  -7,   -5, 	  -2,   -9
.2byte    0,  -10, 	   2,   -8, 	   7,  -10, 	  -2,   -9
.2byte    0,  -10, 	   2,   -8, 	   7,  -10, 	  -2,   -9
.2byte   -6,   -7, 	  -5,   -4, 	  -3,   -1, 	  -1,   -7
.2byte   -8,   -5, 	 -12,   -3, 	   3,   -6, 	  -3,   -6
.2byte   -8,   -5, 	 -12,   -3, 	   3,   -6, 	  -3,   -6
.2byte   -9,   -7, 	  -2,   -8, 	 -13,   -6, 	  -4,   -7
.2byte   -9,   -7, 	  -2,   -8, 	 -13,   -6, 	  -4,   -7
.2byte   -4,   -7, 	  -9,   -4, 	   5,   -1, 	  -1,   -7
.2byte   -4,   -4, 	   2,   -2, 	   9,   -7, 	   0,   -6
.2byte   -4,   -4, 	   2,   -2, 	   9,   -7, 	   0,   -6
.2byte   -6,   -5, 	  -6,   -6, 	 -10,   -5, 	  -2,   -6
.2byte   -6,   -5, 	  -6,   -6, 	 -10,   -5, 	  -2,   -6
.2byte   -1,   -8, 	  -6,   -8, 	  10,    1, 	  -1,   -4
.2byte    0,   -9, 	  -6,   -8, 	  10,    1, 	  -1,   -5
.2byte    0,  -10, 	 -12,  -11, 	  12,  -11, 	   0,  -12
.2byte    3,  -10, 	  -7,    1, 	  10,  -18, 	   1,   -8
.2byte    5,  -10, 	  -5,   -2, 	  -5,   -8, 	   1,   -7
.2byte    1,  -13, 	   8,   -4, 	  -9,  -12, 	  -3,  -11
.2byte   -1,  -14, 	  11,  -10, 	 -13,  -10, 	  -1,  -10
.2byte   -3,  -14, 	   8,  -10, 	  -9,   -4, 	   1,  -12
.2byte   -6,   -9, 	   4,   -8, 	   4,   -2, 	  -2,   -7
.2byte   -4,  -10, 	 -11,  -18, 	   6,    1, 	  -2,   -8
.2byte   -1,   -7, 	 -10,   -1, 	   9,   -1, 	  -1,   -9
.2byte   -1,   -3, 	  -9,    1, 	   7,    1, 	  -1,   -6
.2byte    2,   -7, 	  -7,   -1, 	   7,   -4, 	  -1,   -7
.2byte    1,   -3, 	  -5,    1, 	   7,   -1, 	  -3,   -4
.2byte    4,   -7, 	   1,   -1, 	   3,   -4, 	  -2,   -7
.2byte    7,   -5, 	   4,    1, 	   7,   -1, 	   0,   -5
.2byte    5,   -8, 	   6,   -2, 	  -6,   -4, 	  -1,   -7
.2byte    6,   -9, 	   7,   -2, 	   0,   -4, 	  -1,   -7
.2byte   -1,  -12, 	   8,   -4, 	 -10,   -4, 	  -1,   -8
.2byte   -1,  -13, 	   7,   -7, 	  -9,   -7, 	  -1,   -9
.2byte   -6,   -8, 	   5,   -4, 	  -8,   -2, 	   0,   -7
.2byte   -8,   -9, 	  -1,   -6, 	  -9,   -2, 	  -2,   -8
.2byte   -6,   -7, 	  -5,   -4, 	  -3,   -1, 	  -1,   -7
.2byte   -9,   -5, 	  -9,   -1, 	  -6,    2, 	  -2,   -5
.2byte   -4,   -7, 	  -9,   -4, 	   5,   -1, 	  -1,   -7
.2byte   -3,   -3, 	  -9,   -1, 	   3,    2, 	   1,   -5
.2byte   -1,   -4, 	  -9,    0, 	   7,    0, 	  -1,   -7
.2byte   -3,   -3, 	  -9,   -1, 	   3,    2, 	   1,   -5
.2byte   -8,   -6, 	  -8,   -2, 	  -5,    1, 	  -1,   -6
.2byte   -7,   -8, 	   0,   -5, 	  -8,   -1, 	  -1,   -7
.2byte   -1,  -11, 	   7,   -5, 	  -9,   -5, 	  -1,   -7
.2byte    5,   -8, 	   6,   -1, 	  -1,   -3, 	  -2,   -6
.2byte    6,   -6, 	   3,    0, 	   6,   -2, 	  -1,   -6
.2byte    1,   -3, 	  -5,    1, 	   7,   -1, 	  -3,   -4
.2byte   -1,   -4, 	  -9,    0, 	   7,    0, 	  -1,   -7
.2byte    1,   -3, 	  -5,    1, 	   7,   -1, 	  -3,   -4
.2byte    6,   -6, 	   3,    0, 	   6,   -2, 	  -1,   -6
.2byte    5,   -8, 	   6,   -1, 	  -1,   -3, 	  -2,   -6
.2byte   -1,  -11, 	   7,   -5, 	  -9,   -5, 	  -1,   -7
.2byte   -7,   -8, 	   0,   -5, 	  -8,   -1, 	  -1,   -7
.2byte   -8,   -6, 	  -8,   -2, 	  -5,    1, 	  -1,   -6
.2byte   -3,   -3, 	  -9,   -1, 	   3,    2, 	   1,   -5
.2byte   -1,   -7, 	 -10,   -1, 	   9,   -1, 	  -1,   -9
.2byte   -1,   -2, 	  -9,    2, 	   7,    2, 	  -1,   -5
.2byte    2,   -7, 	  -7,   -1, 	   7,   -4, 	  -1,   -7
.2byte    1,   -3, 	  -5,    1, 	   7,   -1, 	  -3,   -4
.2byte    4,   -7, 	   1,   -1, 	   3,   -4, 	  -2,   -7
.2byte    5,   -5, 	   2,    1, 	   5,   -1, 	  -2,   -5
.2byte    5,   -8, 	   6,   -2, 	  -6,   -4, 	  -1,   -7
.2byte    4,   -9, 	   5,   -2, 	  -2,   -4, 	  -3,   -7
.2byte   -1,  -12, 	   8,   -4, 	 -10,   -4, 	  -1,   -8
.2byte   -1,  -12, 	   7,   -6, 	  -9,   -6, 	  -1,   -8
.2byte   -6,   -8, 	   5,   -4, 	  -8,   -2, 	   0,   -7
.2byte   -6,   -9, 	   1,   -6, 	  -7,   -2, 	   0,   -8
.2byte   -6,   -7, 	  -5,   -4, 	  -3,   -1, 	  -1,   -7
.2byte   -7,   -5, 	  -7,   -1, 	  -4,    2, 	   0,   -5
.2byte   -4,   -7, 	  -9,   -4, 	   5,   -1, 	  -1,   -7
.2byte   -3,   -3, 	  -9,   -1, 	   3,    2, 	   1,   -5
.2byte   -1,   -4, 	  -9,    0, 	   7,    0, 	  -1,   -7
.2byte   -3,   -3, 	  -9,   -1, 	   3,    2, 	   1,   -5
.2byte   -8,   -6, 	  -8,   -2, 	  -5,    1, 	  -1,   -6
.2byte   -7,   -8, 	   0,   -5, 	  -8,   -1, 	  -1,   -7
.2byte   -1,  -11, 	   7,   -5, 	  -9,   -5, 	  -1,   -7
.2byte    5,   -8, 	   6,   -1, 	  -1,   -3, 	  -2,   -6
.2byte    6,   -6, 	   3,    0, 	   6,   -2, 	  -1,   -6
.2byte    1,   -3, 	  -5,    1, 	   7,   -1, 	  -3,   -4
.2byte   -1,   -7, 	 -10,   -1, 	   9,   -1, 	  -1,   -9
.2byte   -4,   -7, 	  -9,   -4, 	   5,   -1, 	  -1,   -7
.2byte   -6,   -7, 	  -5,   -4, 	  -3,   -1, 	  -1,   -7
.2byte   -6,   -8, 	   5,   -4, 	  -8,   -2, 	   0,   -7
.2byte   -1,  -12, 	   8,   -4, 	 -10,   -4, 	  -1,   -8
.2byte    5,   -8, 	   6,   -2, 	  -6,   -4, 	  -1,   -7
.2byte    4,   -7, 	   1,   -1, 	   3,   -4, 	  -2,   -7
.2byte    2,   -7, 	  -7,   -1, 	   7,   -4, 	  -1,   -7
.2byte   -1,   -7, 	 -10,   -1, 	   9,   -1, 	  -1,   -9
.2byte   -1,   -6, 	  -9,    0, 	  11,   -3, 	  -1,   -8
.2byte   -1,   -5, 	  -8,    1, 	  12,   -5, 	  -1,   -9
.2byte   -1,   -6, 	  -7,   -1, 	  10,   -3, 	  -1,   -8
.2byte   -1,   -3, 	  -5,   -1, 	   0,    0, 	  -1,   -5
.2byte   -1,   -7, 	 -10,   -1, 	   9,   -1, 	  -1,   -9
.2byte   -1,   -6, 	  -9,    0, 	  11,   -3, 	  -1,   -8
.2byte   -1,   -5, 	  -8,    1, 	  12,   -5, 	  -1,   -9
.2byte   -1,   -6, 	  -7,   -1, 	  10,   -3, 	  -1,   -8
.2byte   -1,   -3, 	  -5,   -1, 	   0,    0, 	  -1,   -5
sLombreAnimTable1:
.4byte sLombreAnims_1_1
.4byte sLombreAnims_1_2
.4byte sLombreAnims_1_3
.4byte sLombreAnims_1_4
.4byte sLombreAnims_1_5
.4byte sLombreAnims_1_6
.4byte sLombreAnims_1_7
.4byte sLombreAnims_1_8
sLombreAnimTable2:
.4byte sLombreAnims_2_1
.4byte sLombreAnims_2_2
.4byte sLombreAnims_2_3
.4byte sLombreAnims_2_4
.4byte sLombreAnims_2_5
.4byte sLombreAnims_2_6
.4byte sLombreAnims_2_7
.4byte sLombreAnims_2_8
sLombreAnimTable3:
.4byte sLombreAnims_3_1
.4byte sLombreAnims_3_2
.4byte sLombreAnims_3_3
.4byte sLombreAnims_3_4
.4byte sLombreAnims_3_5
.4byte sLombreAnims_3_6
.4byte sLombreAnims_3_7
.4byte sLombreAnims_3_8
sLombreAnimTable4:
.4byte sLombreAnims_4_1
.4byte sLombreAnims_4_2
.4byte sLombreAnims_4_3
.4byte sLombreAnims_4_4
.4byte sLombreAnims_4_5
.4byte sLombreAnims_4_6
.4byte sLombreAnims_4_7
.4byte sLombreAnims_4_8
sLombreAnimTable5:
.4byte sLombreAnims_5_1
.4byte sLombreAnims_5_2
.4byte sLombreAnims_5_3
.4byte sLombreAnims_5_4
.4byte sLombreAnims_5_5
.4byte sLombreAnims_5_6
.4byte sLombreAnims_5_7
.4byte sLombreAnims_5_8
sLombreAnimTable6:
.4byte sLombreAnims_6_1
.4byte sLombreAnims_6_1
.4byte sLombreAnims_6_1
.4byte sLombreAnims_6_1
.4byte sLombreAnims_6_1
.4byte sLombreAnims_6_1
.4byte sLombreAnims_6_1
.4byte sLombreAnims_6_1
sLombreAnimTable7:
.4byte sLombreAnims_7_1
.4byte sLombreAnims_7_2
.4byte sLombreAnims_7_3
.4byte sLombreAnims_7_4
.4byte sLombreAnims_7_5
.4byte sLombreAnims_7_6
.4byte sLombreAnims_7_7
.4byte sLombreAnims_7_8
sLombreAnimTable8:
.4byte sLombreAnims_8_1
.4byte sLombreAnims_8_2
.4byte sLombreAnims_8_3
.4byte sLombreAnims_8_4
.4byte sLombreAnims_8_5
.4byte sLombreAnims_8_6
.4byte sLombreAnims_8_7
.4byte sLombreAnims_8_8
sLombreAnimTable9:
.4byte sLombreAnims_9_1
.4byte sLombreAnims_9_2
.4byte sLombreAnims_9_3
.4byte sLombreAnims_9_4
.4byte sLombreAnims_9_5
.4byte sLombreAnims_9_6
.4byte sLombreAnims_9_7
.4byte sLombreAnims_9_8
sLombreAnimTable10:
.4byte sLombreAnims_10_1
.4byte sLombreAnims_10_2
.4byte sLombreAnims_10_3
.4byte sLombreAnims_10_4
.4byte sLombreAnims_10_5
.4byte sLombreAnims_10_6
.4byte sLombreAnims_10_7
.4byte sLombreAnims_10_8
sLombreAnimTable11:
.4byte sLombreAnims_11_1
.4byte sLombreAnims_11_2
.4byte sLombreAnims_11_3
.4byte sLombreAnims_11_4
.4byte sLombreAnims_11_5
.4byte sLombreAnims_11_6
.4byte sLombreAnims_11_7
.4byte sLombreAnims_11_8
sLombreAnimTable12:
.4byte sLombreAnims_12_1
.4byte sLombreAnims_12_2
.4byte sLombreAnims_12_3
.4byte sLombreAnims_12_4
.4byte sLombreAnims_12_5
.4byte sLombreAnims_12_6
.4byte sLombreAnims_12_7
.4byte sLombreAnims_12_8
sLombreAnimTable13:
.4byte sLombreAnims_13_1
.4byte sLombreAnims_13_2
.4byte sLombreAnims_13_3
.4byte sLombreAnims_13_4
.4byte sLombreAnims_13_5
.4byte sLombreAnims_13_6
.4byte sLombreAnims_13_7
.4byte sLombreAnims_13_8
sLombreAnimTable14:
.4byte sLombreAnims_14_1
.4byte sLombreAnims_14_2
.4byte sLombreAnims_14_3
.4byte sLombreAnims_14_4
.4byte sLombreAnims_14_5
.4byte sLombreAnims_14_6
.4byte sLombreAnims_14_7
.4byte sLombreAnims_14_8
sLombreAnimTable15:
.4byte sLombreAnims_15_1
.4byte sLombreAnims_15_2
.4byte sLombreAnims_15_3
.4byte sLombreAnims_15_4
.4byte sLombreAnims_15_5
.4byte sLombreAnims_15_6
.4byte sLombreAnims_15_7
.4byte sLombreAnims_15_8
sAxAnimationsLombre:
.4byte sLombreAnimTable1
.4byte sLombreAnimTable2
.4byte sLombreAnimTable3
.4byte sLombreAnimTable4
.4byte sLombreAnimTable5
.4byte sLombreAnimTable6
.4byte sLombreAnimTable7
.4byte sLombreAnimTable8
.4byte sLombreAnimTable9
.4byte sLombreAnimTable10
.4byte sLombreAnimTable11
.4byte sLombreAnimTable12
.4byte sLombreAnimTable13
.4byte sLombreAnimTable14
.4byte sLombreAnimTable15
sAxSpritesLombre:
.4byte sLombreSprites1
.4byte sLombreSprites2
.4byte sLombreSprites3
.4byte sLombreSprites4
.4byte sLombreSprites5
.4byte sLombreSprites6
.4byte sLombreSprites7
.4byte sLombreSprites8
.4byte sLombreSprites9
.4byte sLombreSprites10
.4byte sLombreSprites11
.4byte sLombreSprites12
.4byte sLombreSprites13
.4byte sLombreSprites14
.4byte sLombreSprites15
.4byte sLombreSprites16
.4byte sLombreSprites17
.4byte sLombreSprites18
.4byte sLombreSprites19
.4byte sLombreSprites20
.4byte sLombreSprites21
.4byte sLombreSprites22
.4byte sLombreSprites23
.4byte sLombreSprites24
.4byte sLombreSprites25
.4byte sLombreSprites26
.4byte sLombreSprites27
.4byte sLombreSprites28
.4byte sLombreSprites29
.4byte sLombreSprites30
.4byte sLombreSprites31
.4byte sLombreSprites32
.4byte sLombreSprites33
.4byte sLombreSprites34
.4byte sLombreSprites35
.4byte sLombreSprites36
.4byte sLombreSprites37
.4byte sLombreSprites38
.4byte sLombreSprites39
.4byte sLombreSprites40
.4byte sLombreSprites41
.4byte sLombreSprites42
.4byte sLombreSprites43
.4byte sLombreSprites44
.4byte sLombreSprites45
.4byte sLombreSprites46
.4byte sLombreSprites47
.4byte sLombreSprites48
.4byte sLombreSprites49
.4byte sLombreSprites50
.4byte sLombreSprites51
.4byte sLombreSprites52
.4byte sLombreSprites53
.4byte sLombreSprites54
.4byte sLombreSprites55
.4byte sLombreSprites56
.4byte sLombreSprites57
.4byte sLombreSprites58
.4byte sLombreSprites59
.4byte sLombreSprites60
.4byte sLombreSprites61
.4byte sLombreSprites62
.4byte sLombreSprites63
.4byte sLombreSprites64
.4byte sLombreSprites65
.4byte sLombreSprites66
.4byte sLombreSprites67
.4byte sLombreSprites68
.4byte sLombreSprites69
.4byte sLombreSprites70
.4byte sLombreSprites71
.4byte sLombreSprites72
.4byte sLombreSprites73
.4byte sLombreSprites74
.4byte sLombreSprites75
.4byte sLombreSprites76
.4byte sLombreSprites77
.4byte sLombreSprites78
.4byte sLombreSprites79
.4byte sLombreSprites80
.4byte sLombreSprites81
sAxMainLombre:
ax_main sAxPosesLombre, sAxAnimationsLombre, 15, sAxSpritesLombre, sAxPositionsLombre
