.global gAxLoudred
gAxLoudred:
ax_siro sAxMainLoudred
sLoudredPose1:
ax_pose 0, 0x01e9, 0x80f4, 0x3c00
ax_pose_terminator
sLoudredPose2:
ax_pose 1, 0x01e5, 0x80f0, 0x3c00
ax_pose_terminator
sLoudredPose3:
ax_pose 2, 0x01e5, 0x80f0, 0x3c00
ax_pose_terminator
sLoudredPose4:
ax_pose 3, 0x01e5, 0x90ec, 0x3c00
ax_pose_terminator
sLoudredPose5:
ax_pose 4, 0x01e5, 0x90ec, 0x3c00
ax_pose_terminator
sLoudredPose6:
ax_pose 5, 0x01e6, 0x90ec, 0x3c00
ax_pose_terminator
sLoudredPose7:
ax_pose 6, 0x01e5, 0x90ec, 0x3c00
ax_pose_terminator
sLoudredPose8:
ax_pose 7, 0x01e5, 0x90ec, 0x3c00
ax_pose_terminator
sLoudredPose9:
ax_pose 8, 0x01e5, 0x90ec, 0x3c00
ax_pose_terminator
sLoudredPose10:
ax_pose 9, 0x01e4, 0x90ed, 0x3c00
ax_pose_terminator
sLoudredPose11:
ax_pose 10, 0x01e5, 0x90ed, 0x3c00
ax_pose_terminator
sLoudredPose12:
ax_pose 11, 0x01e5, 0x90ed, 0x3c00
ax_pose_terminator
sLoudredPose13:
ax_pose 12, 0x01e9, 0x80f0, 0x3c00
ax_pose_terminator
sLoudredPose14:
ax_pose 13, 0x01ea, 0x80f0, 0x3c00
ax_pose_terminator
sLoudredPose15:
ax_pose 14, 0x01ea, 0x80f0, 0x3c00
ax_pose_terminator
sLoudredPose16:
ax_pose 9, 0x01e4, 0x80f3, 0x3c00
ax_pose_terminator
sLoudredPose17:
ax_pose 10, 0x01e5, 0x80f3, 0x3c00
ax_pose_terminator
sLoudredPose18:
ax_pose 11, 0x01e5, 0x80f3, 0x3c00
ax_pose_terminator
sLoudredPose19:
ax_pose 6, 0x01e5, 0x80f4, 0x3c00
ax_pose_terminator
sLoudredPose20:
ax_pose 7, 0x01e5, 0x80f4, 0x3c00
ax_pose_terminator
sLoudredPose21:
ax_pose 8, 0x01e5, 0x80f4, 0x3c00
ax_pose_terminator
sLoudredPose22:
ax_pose 3, 0x01e5, 0x80f4, 0x3c00
ax_pose_terminator
sLoudredPose23:
ax_pose 4, 0x01e5, 0x80f4, 0x3c00
ax_pose_terminator
sLoudredPose24:
ax_pose 5, 0x01e6, 0x80f4, 0x3c00
ax_pose_terminator
sLoudredPose25:
ax_pose 0, 0x01ea, 0x80f4, 0x3c00
ax_pose_terminator
sLoudredPose26:
ax_pose 1, 0x01e5, 0x80f0, 0x3c00
ax_pose_terminator
sLoudredPose27:
ax_pose 2, 0x01e5, 0x80f0, 0x3c00
ax_pose_terminator
sLoudredPose28:
ax_pose 15, 0x81e6, 0x80f3, 0x3c00
ax_pose 16, 0x81e6, 0x4103, 0x3c08
ax_pose 17, 0x01f6, 0x010b, 0x3c0c
ax_pose_terminator
sLoudredPose29:
ax_pose 3, 0x01e5, 0x90ec, 0x3c00
ax_pose_terminator
sLoudredPose30:
ax_pose 4, 0x01e5, 0x90ec, 0x3c00
ax_pose_terminator
sLoudredPose31:
ax_pose 5, 0x01e6, 0x90ec, 0x3c00
ax_pose_terminator
sLoudredPose32:
ax_pose 18, 0x81e5, 0x90fa, 0x3c00
ax_pose 19, 0x81e5, 0x50f2, 0x3c08
ax_pose_terminator
sLoudredPose33:
ax_pose 6, 0x01e5, 0x90ec, 0x3c00
ax_pose_terminator
sLoudredPose34:
ax_pose 7, 0x01e5, 0x90ec, 0x3c00
ax_pose_terminator
sLoudredPose35:
ax_pose 8, 0x01e5, 0x90ec, 0x3c00
ax_pose_terminator
sLoudredPose36:
ax_pose 20, 0x81e5, 0x90f7, 0x3c00
ax_pose 21, 0x01f5, 0x1107, 0x3c08
ax_pose_terminator
sLoudredPose37:
ax_pose 9, 0x01e5, 0x90ed, 0x3c00
ax_pose_terminator
sLoudredPose38:
ax_pose 10, 0x01e5, 0x90ed, 0x3c00
ax_pose_terminator
sLoudredPose39:
ax_pose 11, 0x01e5, 0x90ed, 0x3c00
ax_pose_terminator
sLoudredPose40:
ax_pose 22, 0x81e5, 0x90fd, 0x3c00
ax_pose 23, 0x81e5, 0x50f5, 0x3c08
ax_pose_terminator
sLoudredPose41:
ax_pose 12, 0x01ea, 0x80f0, 0x3c00
ax_pose_terminator
sLoudredPose42:
ax_pose 13, 0x01ea, 0x80f0, 0x3c00
ax_pose_terminator
sLoudredPose43:
ax_pose 14, 0x01ea, 0x80f0, 0x3c00
ax_pose_terminator
sLoudredPose44:
ax_pose 24, 0x41ea, 0x80f0, 0x3c00
ax_pose 25, 0x41fa, 0x40f0, 0x3c08
ax_pose_terminator
sLoudredPose45:
ax_pose 9, 0x01e5, 0x80f3, 0x3c00
ax_pose_terminator
sLoudredPose46:
ax_pose 10, 0x01e5, 0x80f3, 0x3c00
ax_pose_terminator
sLoudredPose47:
ax_pose 11, 0x01e5, 0x80f3, 0x3c00
ax_pose_terminator
sLoudredPose48:
ax_pose 22, 0x81e5, 0x80f3, 0x3c00
ax_pose 23, 0x81e5, 0x4103, 0x3c08
ax_pose_terminator
sLoudredPose49:
ax_pose 6, 0x01e5, 0x80f4, 0x3c00
ax_pose_terminator
sLoudredPose50:
ax_pose 7, 0x01e5, 0x80f4, 0x3c00
ax_pose_terminator
sLoudredPose51:
ax_pose 8, 0x01e5, 0x80f4, 0x3c00
ax_pose_terminator
sLoudredPose52:
ax_pose 20, 0x81e5, 0x80f9, 0x3c00
ax_pose 21, 0x01f5, 0x00f1, 0x3c08
ax_pose_terminator
sLoudredPose53:
ax_pose 3, 0x01e5, 0x80f4, 0x3c00
ax_pose_terminator
sLoudredPose54:
ax_pose 4, 0x01e5, 0x80f4, 0x3c00
ax_pose_terminator
sLoudredPose55:
ax_pose 5, 0x01e6, 0x80f4, 0x3c00
ax_pose_terminator
sLoudredPose56:
ax_pose 18, 0x81e5, 0x80f6, 0x3c00
ax_pose 19, 0x81e5, 0x4106, 0x3c08
ax_pose_terminator
sLoudredPose57:
ax_pose 0, 0x01ea, 0x80f4, 0x3c00
ax_pose_terminator
sLoudredPose58:
ax_pose 1, 0x01e5, 0x80f0, 0x3c00
ax_pose_terminator
sLoudredPose59:
ax_pose 2, 0x01e5, 0x80f0, 0x3c00
ax_pose_terminator
sLoudredPose60:
ax_pose 15, 0x81e6, 0x80f3, 0x3c00
ax_pose 16, 0x81e6, 0x4103, 0x3c08
ax_pose 17, 0x01f6, 0x010b, 0x3c0c
ax_pose_terminator
sLoudredPose61:
ax_pose 3, 0x01e5, 0x90ec, 0x3c00
ax_pose_terminator
sLoudredPose62:
ax_pose 4, 0x01e5, 0x90ec, 0x3c00
ax_pose_terminator
sLoudredPose63:
ax_pose 5, 0x01e6, 0x90ec, 0x3c00
ax_pose_terminator
sLoudredPose64:
ax_pose 18, 0x81e5, 0x90fa, 0x3c00
ax_pose 19, 0x81e5, 0x50f2, 0x3c08
ax_pose_terminator
sLoudredPose65:
ax_pose 6, 0x01e5, 0x90ec, 0x3c00
ax_pose_terminator
sLoudredPose66:
ax_pose 7, 0x01e5, 0x90ec, 0x3c00
ax_pose_terminator
sLoudredPose67:
ax_pose 8, 0x01e5, 0x90ec, 0x3c00
ax_pose_terminator
sLoudredPose68:
ax_pose 20, 0x81e5, 0x90f7, 0x3c00
ax_pose 21, 0x01f5, 0x1107, 0x3c08
ax_pose_terminator
sLoudredPose69:
ax_pose 9, 0x01e5, 0x90ed, 0x3c00
ax_pose_terminator
sLoudredPose70:
ax_pose 10, 0x01e5, 0x90ed, 0x3c00
ax_pose_terminator
sLoudredPose71:
ax_pose 11, 0x01e5, 0x90ed, 0x3c00
ax_pose_terminator
sLoudredPose72:
ax_pose 22, 0x81e5, 0x90fd, 0x3c00
ax_pose 23, 0x81e5, 0x50f5, 0x3c08
ax_pose_terminator
sLoudredPose73:
ax_pose 12, 0x01ea, 0x80f0, 0x3c00
ax_pose_terminator
sLoudredPose74:
ax_pose 13, 0x01ea, 0x80f0, 0x3c00
ax_pose_terminator
sLoudredPose75:
ax_pose 14, 0x01ea, 0x80f0, 0x3c00
ax_pose_terminator
sLoudredPose76:
ax_pose 24, 0x41ea, 0x80f0, 0x3c00
ax_pose 25, 0x41fa, 0x40f0, 0x3c08
ax_pose_terminator
sLoudredPose77:
ax_pose 9, 0x01e5, 0x80f3, 0x3c00
ax_pose_terminator
sLoudredPose78:
ax_pose 10, 0x01e5, 0x80f3, 0x3c00
ax_pose_terminator
sLoudredPose79:
ax_pose 11, 0x01e5, 0x80f3, 0x3c00
ax_pose_terminator
sLoudredPose80:
ax_pose 22, 0x81e5, 0x80f3, 0x3c00
ax_pose 23, 0x81e5, 0x4103, 0x3c08
ax_pose_terminator
sLoudredPose81:
ax_pose 6, 0x01e5, 0x80f4, 0x3c00
ax_pose_terminator
sLoudredPose82:
ax_pose 7, 0x01e5, 0x80f4, 0x3c00
ax_pose_terminator
sLoudredPose83:
ax_pose 8, 0x01e5, 0x80f4, 0x3c00
ax_pose_terminator
sLoudredPose84:
ax_pose 20, 0x81e5, 0x80f9, 0x3c00
ax_pose 21, 0x01f5, 0x00f1, 0x3c08
ax_pose_terminator
sLoudredPose85:
ax_pose 3, 0x01e5, 0x80f4, 0x3c00
ax_pose_terminator
sLoudredPose86:
ax_pose 4, 0x01e5, 0x80f4, 0x3c00
ax_pose_terminator
sLoudredPose87:
ax_pose 5, 0x01e6, 0x80f4, 0x3c00
ax_pose_terminator
sLoudredPose88:
ax_pose 18, 0x81e5, 0x80f6, 0x3c00
ax_pose 19, 0x81e5, 0x4106, 0x3c08
ax_pose_terminator
sLoudredPose89:
ax_pose 0, 0x01ea, 0x80f4, 0x3c00
ax_pose_terminator
sLoudredPose90:
ax_pose 1, 0x01e5, 0x80f0, 0x3c00
ax_pose_terminator
sLoudredPose91:
ax_pose 2, 0x01e5, 0x80f0, 0x3c00
ax_pose_terminator
sLoudredPose92:
ax_pose 15, 0x81e6, 0x80f3, 0x3c00
ax_pose 16, 0x81e6, 0x4103, 0x3c08
ax_pose 17, 0x01f6, 0x010b, 0x3c0c
ax_pose_terminator
sLoudredPose93:
ax_pose 3, 0x01e5, 0x90ec, 0x3c00
ax_pose_terminator
sLoudredPose94:
ax_pose 4, 0x01e5, 0x90ec, 0x3c00
ax_pose_terminator
sLoudredPose95:
ax_pose 5, 0x01e6, 0x90ec, 0x3c00
ax_pose_terminator
sLoudredPose96:
ax_pose 18, 0x81e5, 0x90fb, 0x3c00
ax_pose 19, 0x81e5, 0x50f3, 0x3c08
ax_pose_terminator
sLoudredPose97:
ax_pose 6, 0x01e5, 0x90ec, 0x3c00
ax_pose_terminator
sLoudredPose98:
ax_pose 7, 0x01e5, 0x90ec, 0x3c00
ax_pose_terminator
sLoudredPose99:
ax_pose 8, 0x01e5, 0x90ec, 0x3c00
ax_pose_terminator
sLoudredPose100:
ax_pose 20, 0x81e5, 0x90f7, 0x3c00
ax_pose 21, 0x01f5, 0x1107, 0x3c08
ax_pose_terminator
sLoudredPose101:
ax_pose 9, 0x01e5, 0x90ed, 0x3c00
ax_pose_terminator
sLoudredPose102:
ax_pose 10, 0x01e5, 0x90ed, 0x3c00
ax_pose_terminator
sLoudredPose103:
ax_pose 11, 0x01e5, 0x90ed, 0x3c00
ax_pose_terminator
sLoudredPose104:
ax_pose 22, 0x81e5, 0x90fd, 0x3c00
ax_pose 23, 0x81e5, 0x50f5, 0x3c08
ax_pose_terminator
sLoudredPose105:
ax_pose 12, 0x01ea, 0x80f0, 0x3c00
ax_pose_terminator
sLoudredPose106:
ax_pose 13, 0x01ea, 0x80f0, 0x3c00
ax_pose_terminator
sLoudredPose107:
ax_pose 14, 0x01ea, 0x80f0, 0x3c00
ax_pose_terminator
sLoudredPose108:
ax_pose 24, 0x41ea, 0x80f0, 0x3c00
ax_pose 25, 0x41fa, 0x40f0, 0x3c08
ax_pose_terminator
sLoudredPose109:
ax_pose 9, 0x01e5, 0x80f3, 0x3c00
ax_pose_terminator
sLoudredPose110:
ax_pose 10, 0x01e5, 0x80f3, 0x3c00
ax_pose_terminator
sLoudredPose111:
ax_pose 11, 0x01e5, 0x80f3, 0x3c00
ax_pose_terminator
sLoudredPose112:
ax_pose 22, 0x81e5, 0x80f3, 0x3c00
ax_pose 23, 0x81e5, 0x4103, 0x3c08
ax_pose_terminator
sLoudredPose113:
ax_pose 6, 0x01e5, 0x80f4, 0x3c00
ax_pose_terminator
sLoudredPose114:
ax_pose 7, 0x01e5, 0x80f4, 0x3c00
ax_pose_terminator
sLoudredPose115:
ax_pose 8, 0x01e5, 0x80f4, 0x3c00
ax_pose_terminator
sLoudredPose116:
ax_pose 20, 0x81e5, 0x80f9, 0x3c00
ax_pose 21, 0x01f5, 0x00f1, 0x3c08
ax_pose_terminator
sLoudredPose117:
ax_pose 3, 0x01e5, 0x80f4, 0x3c00
ax_pose_terminator
sLoudredPose118:
ax_pose 4, 0x01e5, 0x80f4, 0x3c00
ax_pose_terminator
sLoudredPose119:
ax_pose 5, 0x01e6, 0x80f4, 0x3c00
ax_pose_terminator
sLoudredPose120:
ax_pose 18, 0x81e5, 0x80f5, 0x3c00
ax_pose 19, 0x81e5, 0x4105, 0x3c08
ax_pose_terminator
sLoudredPose121:
ax_pose 0, 0x01e9, 0x80f4, 0x3c00
ax_pose_terminator
sLoudredPose122:
ax_pose 1, 0x01e3, 0x80f0, 0x3c00
ax_pose_terminator
sLoudredPose123:
ax_pose 2, 0x01e3, 0x80f0, 0x3c00
ax_pose_terminator
sLoudredPose124:
ax_pose 3, 0x01e5, 0x90ec, 0x3c00
ax_pose_terminator
sLoudredPose125:
ax_pose 4, 0x01e4, 0x90ec, 0x3c00
ax_pose_terminator
sLoudredPose126:
ax_pose 5, 0x01e4, 0x90ec, 0x3c00
ax_pose_terminator
sLoudredPose127:
ax_pose 6, 0x01e5, 0x90ec, 0x3c00
ax_pose_terminator
sLoudredPose128:
ax_pose 7, 0x01e4, 0x90ec, 0x3c00
ax_pose_terminator
sLoudredPose129:
ax_pose 8, 0x01e4, 0x90ec, 0x3c00
ax_pose_terminator
sLoudredPose130:
ax_pose 9, 0x01e4, 0x90ed, 0x3c00
ax_pose_terminator
sLoudredPose131:
ax_pose 10, 0x01e4, 0x90ed, 0x3c00
ax_pose_terminator
sLoudredPose132:
ax_pose 11, 0x01e4, 0x90ed, 0x3c00
ax_pose_terminator
sLoudredPose133:
ax_pose 12, 0x01e9, 0x80f0, 0x3c00
ax_pose_terminator
sLoudredPose134:
ax_pose 13, 0x01e9, 0x80f0, 0x3c00
ax_pose_terminator
sLoudredPose135:
ax_pose 14, 0x01e9, 0x80f0, 0x3c00
ax_pose_terminator
sLoudredPose136:
ax_pose 9, 0x01e4, 0x80f3, 0x3c00
ax_pose_terminator
sLoudredPose137:
ax_pose 10, 0x01e4, 0x80f3, 0x3c00
ax_pose_terminator
sLoudredPose138:
ax_pose 11, 0x01e4, 0x80f3, 0x3c00
ax_pose_terminator
sLoudredPose139:
ax_pose 6, 0x01e5, 0x80f4, 0x3c00
ax_pose_terminator
sLoudredPose140:
ax_pose 7, 0x01e4, 0x80f4, 0x3c00
ax_pose_terminator
sLoudredPose141:
ax_pose 8, 0x01e4, 0x80f4, 0x3c00
ax_pose_terminator
sLoudredPose142:
ax_pose 3, 0x01e5, 0x80f4, 0x3c00
ax_pose_terminator
sLoudredPose143:
ax_pose 4, 0x01e4, 0x80f4, 0x3c00
ax_pose_terminator
sLoudredPose144:
ax_pose 5, 0x01e4, 0x80f4, 0x3c00
ax_pose_terminator
sLoudredPose145:
ax_pose 26, 0x01e6, 0x80f4, 0x3c00
ax_pose_terminator
sLoudredPose146:
ax_pose 27, 0x01e6, 0x80f4, 0x3c00
ax_pose_terminator
sLoudredPose147:
ax_pose 28, 0x01e2, 0x80f0, 0x3c00
ax_pose_terminator
sLoudredPose148:
ax_pose 29, 0x01e4, 0x90ea, 0x3c00
ax_pose_terminator
sLoudredPose149:
ax_pose 30, 0x01e7, 0x90e6, 0x3c00
ax_pose_terminator
sLoudredPose150:
ax_pose 31, 0x01e8, 0x90e9, 0x3c00
ax_pose_terminator
sLoudredPose151:
ax_pose 32, 0x01e7, 0x80f0, 0x3c00
ax_pose_terminator
sLoudredPose152:
ax_pose 31, 0x01e8, 0x80f7, 0x3c00
ax_pose_terminator
sLoudredPose153:
ax_pose 30, 0x01e7, 0x80fa, 0x3c00
ax_pose_terminator
sLoudredPose154:
ax_pose 29, 0x01e4, 0x80f6, 0x3c00
ax_pose_terminator
sLoudredPose155:
ax_pose 0, 0x01ea, 0x80f4, 0x3c00
ax_pose_terminator
sLoudredPose156:
ax_pose 15, 0x81e6, 0x80f3, 0x3c00
ax_pose 16, 0x81e6, 0x4103, 0x3c08
ax_pose 17, 0x01f6, 0x010b, 0x3c0c
ax_pose_terminator
sLoudredPose157:
ax_pose 3, 0x01e5, 0x90ec, 0x3c00
ax_pose_terminator
sLoudredPose158:
ax_pose 18, 0x81e5, 0x90fa, 0x3c00
ax_pose 19, 0x81e5, 0x50f2, 0x3c08
ax_pose_terminator
sLoudredPose159:
ax_pose 6, 0x01e5, 0x90ec, 0x3c00
ax_pose_terminator
sLoudredPose160:
ax_pose 20, 0x81e5, 0x90f7, 0x3c00
ax_pose 21, 0x01f5, 0x1107, 0x3c08
ax_pose_terminator
sLoudredPose161:
ax_pose 9, 0x01e5, 0x90ed, 0x3c00
ax_pose_terminator
sLoudredPose162:
ax_pose 22, 0x81e4, 0x90fc, 0x3c00
ax_pose 23, 0x81e4, 0x50f4, 0x3c08
ax_pose_terminator
sLoudredPose163:
ax_pose 12, 0x01ea, 0x80f0, 0x3c00
ax_pose_terminator
sLoudredPose164:
ax_pose 24, 0x41ea, 0x80f0, 0x3c00
ax_pose 25, 0x41fa, 0x40f0, 0x3c08
ax_pose_terminator
sLoudredPose165:
ax_pose 9, 0x01e5, 0x80f3, 0x3c00
ax_pose_terminator
sLoudredPose166:
ax_pose 22, 0x81e4, 0x80f4, 0x3c00
ax_pose 23, 0x81e4, 0x4104, 0x3c08
ax_pose_terminator
sLoudredPose167:
ax_pose 6, 0x01e5, 0x80f4, 0x3c00
ax_pose_terminator
sLoudredPose168:
ax_pose 20, 0x81e5, 0x80f9, 0x3c00
ax_pose 21, 0x01f5, 0x00f1, 0x3c08
ax_pose_terminator
sLoudredPose169:
ax_pose 3, 0x01e5, 0x80f4, 0x3c00
ax_pose_terminator
sLoudredPose170:
ax_pose 18, 0x81e5, 0x80f6, 0x3c00
ax_pose 19, 0x81e5, 0x4106, 0x3c08
ax_pose_terminator
sLoudredPose171:
ax_pose 15, 0x81e6, 0x80f3, 0x3c00
ax_pose 16, 0x81e6, 0x4103, 0x3c08
ax_pose 17, 0x01f6, 0x010b, 0x3c0c
ax_pose_terminator
sLoudredPose172:
ax_pose 18, 0x81e5, 0x80f5, 0x3c00
ax_pose 19, 0x81e5, 0x4105, 0x3c08
ax_pose_terminator
sLoudredPose173:
ax_pose 20, 0x81e5, 0x80f9, 0x3c00
ax_pose 21, 0x01f5, 0x00f1, 0x3c08
ax_pose_terminator
sLoudredPose174:
ax_pose 22, 0x81e5, 0x80f3, 0x3c00
ax_pose 23, 0x81e5, 0x4103, 0x3c08
ax_pose_terminator
sLoudredPose175:
ax_pose 24, 0x41ea, 0x80f0, 0x3c00
ax_pose 25, 0x41fa, 0x40f0, 0x3c08
ax_pose_terminator
sLoudredPose176:
ax_pose 22, 0x81e5, 0x90fd, 0x3c00
ax_pose 23, 0x81e5, 0x50f5, 0x3c08
ax_pose_terminator
sLoudredPose177:
ax_pose 20, 0x81e5, 0x90f7, 0x3c00
ax_pose 21, 0x01f5, 0x1107, 0x3c08
ax_pose_terminator
sLoudredPose178:
ax_pose 18, 0x81e5, 0x90fb, 0x3c00
ax_pose 19, 0x81e5, 0x50f3, 0x3c08
ax_pose_terminator
sLoudredPose179:
ax_pose 18, 0x81e5, 0x90fb, 0x3c00
ax_pose 19, 0x81e5, 0x50f3, 0x3c08
ax_pose_terminator
sLoudredPose180:
ax_pose 20, 0x81e5, 0x90f7, 0x3c00
ax_pose 21, 0x01f5, 0x1107, 0x3c08
ax_pose_terminator
sLoudredPose181:
ax_pose 18, 0x81e5, 0x90fb, 0x3c00
ax_pose 19, 0x81e5, 0x50f3, 0x3c08
ax_pose_terminator
sLoudredPose182:
ax_pose 22, 0x81e5, 0x90fd, 0x3c00
ax_pose 23, 0x81e5, 0x50f5, 0x3c08
ax_pose_terminator
sLoudredPose183:
ax_pose 20, 0x81e5, 0x90f7, 0x3c00
ax_pose 21, 0x01f5, 0x1107, 0x3c08
ax_pose_terminator
sLoudredPose184:
ax_pose 18, 0x81e5, 0x90fb, 0x3c00
ax_pose 19, 0x81e5, 0x50f3, 0x3c08
ax_pose_terminator
sLoudredPose185:
ax_pose 24, 0x41ea, 0x80f0, 0x3c00
ax_pose 25, 0x41fa, 0x40f0, 0x3c08
ax_pose_terminator
sLoudredPose186:
ax_pose 22, 0x81e5, 0x90fd, 0x3c00
ax_pose 23, 0x81e5, 0x50f5, 0x3c08
ax_pose_terminator
sLoudredPose187:
ax_pose 20, 0x81e5, 0x90f7, 0x3c00
ax_pose 21, 0x01f5, 0x1107, 0x3c08
ax_pose_terminator
sLoudredPose188:
ax_pose 18, 0x81e5, 0x90fb, 0x3c00
ax_pose 19, 0x81e5, 0x50f3, 0x3c08
ax_pose_terminator
sLoudredPose189:
ax_pose 22, 0x81e5, 0x80f3, 0x3c00
ax_pose 23, 0x81e5, 0x4103, 0x3c08
ax_pose_terminator
sLoudredPose190:
ax_pose 24, 0x41ea, 0x80f0, 0x3c00
ax_pose 25, 0x41fa, 0x40f0, 0x3c08
ax_pose_terminator
sLoudredPose191:
ax_pose 22, 0x81e5, 0x90fd, 0x3c00
ax_pose 23, 0x81e5, 0x50f5, 0x3c08
ax_pose_terminator
sLoudredPose192:
ax_pose 20, 0x81e5, 0x90f7, 0x3c00
ax_pose 21, 0x01f5, 0x1107, 0x3c08
ax_pose_terminator
sLoudredPose193:
ax_pose 18, 0x81e5, 0x90fb, 0x3c00
ax_pose 19, 0x81e5, 0x50f3, 0x3c08
ax_pose_terminator
sLoudredPose194:
ax_pose 20, 0x81e5, 0x80f9, 0x3c00
ax_pose 21, 0x01f5, 0x00f1, 0x3c08
ax_pose_terminator
sLoudredPose195:
ax_pose 22, 0x81e5, 0x80f3, 0x3c00
ax_pose 23, 0x81e5, 0x4103, 0x3c08
ax_pose_terminator
sLoudredPose196:
ax_pose 24, 0x41ea, 0x80f0, 0x3c00
ax_pose 25, 0x41fa, 0x40f0, 0x3c08
ax_pose_terminator
sLoudredPose197:
ax_pose 22, 0x81e5, 0x90fd, 0x3c00
ax_pose 23, 0x81e5, 0x50f5, 0x3c08
ax_pose_terminator
sLoudredPose198:
ax_pose 20, 0x81e5, 0x90f7, 0x3c00
ax_pose 21, 0x01f5, 0x1107, 0x3c08
ax_pose_terminator
sLoudredPose199:
ax_pose 18, 0x81e5, 0x90fb, 0x3c00
ax_pose 19, 0x81e5, 0x50f3, 0x3c08
ax_pose_terminator
sLoudredPose200:
ax_pose 18, 0x81e5, 0x80f5, 0x3c00
ax_pose 19, 0x81e5, 0x4105, 0x3c08
ax_pose_terminator
sLoudredPose201:
ax_pose 20, 0x81e5, 0x80f9, 0x3c00
ax_pose 21, 0x01f5, 0x00f1, 0x3c08
ax_pose_terminator
sLoudredPose202:
ax_pose 22, 0x81e5, 0x80f3, 0x3c00
ax_pose 23, 0x81e5, 0x4103, 0x3c08
ax_pose_terminator
sLoudredPose203:
ax_pose 24, 0x41ea, 0x80f0, 0x3c00
ax_pose 25, 0x41fa, 0x40f0, 0x3c08
ax_pose_terminator
sLoudredPose204:
ax_pose 22, 0x81e5, 0x90fd, 0x3c00
ax_pose 23, 0x81e5, 0x50f5, 0x3c08
ax_pose_terminator
sLoudredPose205:
ax_pose 20, 0x81e5, 0x90f7, 0x3c00
ax_pose 21, 0x01f5, 0x1107, 0x3c08
ax_pose_terminator
sLoudredPose206:
ax_pose 18, 0x81e5, 0x90fb, 0x3c00
ax_pose 19, 0x81e5, 0x50f3, 0x3c08
ax_pose_terminator
sLoudredPose207:
ax_pose 1, 0x01e5, 0x80f0, 0x3c00
ax_pose_terminator
sLoudredPose208:
ax_pose 5, 0x01e6, 0x90ec, 0x3c00
ax_pose_terminator
sLoudredPose209:
ax_pose 7, 0x01e5, 0x90ec, 0x3c00
ax_pose_terminator
sLoudredPose210:
ax_pose 10, 0x01e5, 0x90ed, 0x3c00
ax_pose_terminator
sLoudredPose211:
ax_pose 13, 0x01ea, 0x80f0, 0x3c00
ax_pose_terminator
sLoudredPose212:
ax_pose 10, 0x01e5, 0x80f3, 0x3c00
ax_pose_terminator
sLoudredPose213:
ax_pose 7, 0x01e5, 0x80f4, 0x3c00
ax_pose_terminator
sLoudredPose214:
ax_pose 4, 0x01e5, 0x80f4, 0x3c00
ax_pose_terminator
sLoudredPose215:
ax_pose 0, 0x01e9, 0x80f4, 0x3c00
ax_pose_terminator
sLoudredPose216:
ax_pose 1, 0x01e5, 0x80f1, 0x3c00
ax_pose_terminator
sLoudredPose217:
ax_pose 2, 0x01e5, 0x80ef, 0x3c00
ax_pose_terminator
sLoudredPose218:
ax_pose 3, 0x01e5, 0x90ec, 0x3c00
ax_pose_terminator
sLoudredPose219:
ax_pose 4, 0x01e5, 0x90eb, 0x3c00
ax_pose_terminator
sLoudredPose220:
ax_pose 5, 0x01e6, 0x90ed, 0x3c00
ax_pose_terminator
sLoudredPose221:
ax_pose 6, 0x01e5, 0x90ec, 0x3c00
ax_pose_terminator
sLoudredPose222:
ax_pose 7, 0x01e5, 0x90ec, 0x3c00
ax_pose_terminator
sLoudredPose223:
ax_pose 8, 0x01e5, 0x90eb, 0x3c00
ax_pose_terminator
sLoudredPose224:
ax_pose 9, 0x01e4, 0x90ed, 0x3c00
ax_pose_terminator
sLoudredPose225:
ax_pose 10, 0x01e5, 0x90ed, 0x3c00
ax_pose_terminator
sLoudredPose226:
ax_pose 11, 0x01e5, 0x90ed, 0x3c00
ax_pose_terminator
sLoudredPose227:
ax_pose 12, 0x01e9, 0x80f0, 0x3c00
ax_pose_terminator
sLoudredPose228:
ax_pose 13, 0x01ea, 0x80ef, 0x3c00
ax_pose_terminator
sLoudredPose229:
ax_pose 14, 0x01ea, 0x80f1, 0x3c00
ax_pose_terminator
sLoudredPose230:
ax_pose 9, 0x01e4, 0x80f3, 0x3c00
ax_pose_terminator
sLoudredPose231:
ax_pose 10, 0x01e5, 0x80f3, 0x3c00
ax_pose_terminator
sLoudredPose232:
ax_pose 11, 0x01e5, 0x80f3, 0x3c00
ax_pose_terminator
sLoudredPose233:
ax_pose 6, 0x01e5, 0x80f4, 0x3c00
ax_pose_terminator
sLoudredPose234:
ax_pose 7, 0x01e5, 0x80f4, 0x3c00
ax_pose_terminator
sLoudredPose235:
ax_pose 8, 0x01e5, 0x80f5, 0x3c00
ax_pose_terminator
sLoudredPose236:
ax_pose 3, 0x01e5, 0x80f4, 0x3c00
ax_pose_terminator
sLoudredPose237:
ax_pose 4, 0x01e5, 0x80f5, 0x3c00
ax_pose_terminator
sLoudredPose238:
ax_pose 5, 0x01e6, 0x80f3, 0x3c00
ax_pose_terminator
sLoudredPose239:
ax_pose 0, 0x01e9, 0x80f4, 0x3c00
ax_pose_terminator
sLoudredPose240:
ax_pose 3, 0x01e5, 0x80f4, 0x3c00
ax_pose_terminator
sLoudredPose241:
ax_pose 6, 0x01e5, 0x80f4, 0x3c00
ax_pose_terminator
sLoudredPose242:
ax_pose 9, 0x01e4, 0x80f3, 0x3c00
ax_pose_terminator
sLoudredPose243:
ax_pose 12, 0x01e9, 0x80f0, 0x3c00
ax_pose_terminator
sLoudredPose244:
ax_pose 9, 0x01e4, 0x90ed, 0x3c00
ax_pose_terminator
sLoudredPose245:
ax_pose 6, 0x01e5, 0x90ec, 0x3c00
ax_pose_terminator
sLoudredPose246:
ax_pose 3, 0x01e5, 0x90ec, 0x3c00
ax_pose_terminator
sLoudredPose247:
ax_pose 3, 0x01e5, 0x90ec, 0x3c00
ax_pose_terminator
sLoudredPose248:
ax_pose 6, 0x01e5, 0x90ec, 0x3c00
ax_pose_terminator
sLoudredPose249:
ax_pose 3, 0x01e5, 0x90ec, 0x3c00
ax_pose_terminator
sLoudredPose250:
ax_pose 9, 0x01e4, 0x90ed, 0x3c00
ax_pose_terminator
sLoudredPose251:
ax_pose 6, 0x01e5, 0x90ec, 0x3c00
ax_pose_terminator
sLoudredPose252:
ax_pose 3, 0x01e5, 0x90ec, 0x3c00
ax_pose_terminator
sLoudredPose253:
ax_pose 12, 0x01e9, 0x80f0, 0x3c00
ax_pose_terminator
sLoudredPose254:
ax_pose 9, 0x01e4, 0x90ed, 0x3c00
ax_pose_terminator
sLoudredPose255:
ax_pose 6, 0x01e5, 0x90ec, 0x3c00
ax_pose_terminator
sLoudredPose256:
ax_pose 3, 0x01e5, 0x90ec, 0x3c00
ax_pose_terminator
sLoudredPose257:
ax_pose 9, 0x01e4, 0x80f3, 0x3c00
ax_pose_terminator
sLoudredPose258:
ax_pose 12, 0x01e9, 0x80f0, 0x3c00
ax_pose_terminator
sLoudredPose259:
ax_pose 9, 0x01e4, 0x90ed, 0x3c00
ax_pose_terminator
sLoudredPose260:
ax_pose 6, 0x01e5, 0x90ec, 0x3c00
ax_pose_terminator
sLoudredPose261:
ax_pose 3, 0x01e5, 0x90ec, 0x3c00
ax_pose_terminator
sLoudredPose262:
ax_pose 6, 0x01e5, 0x80f4, 0x3c00
ax_pose_terminator
sLoudredPose263:
ax_pose 9, 0x01e4, 0x80f3, 0x3c00
ax_pose_terminator
sLoudredPose264:
ax_pose 12, 0x01e9, 0x80f0, 0x3c00
ax_pose_terminator
sLoudredPose265:
ax_pose 9, 0x01e4, 0x90ed, 0x3c00
ax_pose_terminator
sLoudredPose266:
ax_pose 6, 0x01e5, 0x90ec, 0x3c00
ax_pose_terminator
sLoudredPose267:
ax_pose 3, 0x01e5, 0x90ec, 0x3c00
ax_pose_terminator
sLoudredPose268:
ax_pose 3, 0x01e5, 0x80f4, 0x3c00
ax_pose_terminator
sLoudredPose269:
ax_pose 6, 0x01e5, 0x80f4, 0x3c00
ax_pose_terminator
sLoudredPose270:
ax_pose 9, 0x01e4, 0x80f3, 0x3c00
ax_pose_terminator
sLoudredPose271:
ax_pose 12, 0x01e9, 0x80f0, 0x3c00
ax_pose_terminator
sLoudredPose272:
ax_pose 9, 0x01e4, 0x90ed, 0x3c00
ax_pose_terminator
sLoudredPose273:
ax_pose 6, 0x01e5, 0x90ec, 0x3c00
ax_pose_terminator
sLoudredPose274:
ax_pose 3, 0x01e5, 0x90ec, 0x3c00
ax_pose_terminator
sLoudredPose275:
ax_pose 0, 0x01ea, 0x80f4, 0x3c00
ax_pose_terminator
sLoudredPose276:
ax_pose 3, 0x01e5, 0x80f4, 0x3c00
ax_pose_terminator
sLoudredPose277:
ax_pose 6, 0x01e5, 0x80f4, 0x3c00
ax_pose_terminator
sLoudredPose278:
ax_pose 9, 0x01e5, 0x80f3, 0x3c00
ax_pose_terminator
sLoudredPose279:
ax_pose 12, 0x01ea, 0x80f0, 0x3c00
ax_pose_terminator
sLoudredPose280:
ax_pose 9, 0x01e5, 0x90ed, 0x3c00
ax_pose_terminator
sLoudredPose281:
ax_pose 6, 0x01e5, 0x90ec, 0x3c00
ax_pose_terminator
sLoudredPose282:
ax_pose 3, 0x01e5, 0x90ec, 0x3c00
ax_pose_terminator
.align 2
sLoudredAnims_1_1:
ax_anim 6, 0, 0, 0, 0, 0, 0,
ax_anim 10, 0, 1, 0, 0, 0, 0,
ax_anim 6, 0, 0, 0, 0, 0, 0,
ax_anim 10, 0, 2, 0, 0, 0, 0,
ax_anim_terminator
sLoudredAnims_1_2:
ax_anim 6, 0, 3, 0, 0, 0, 0,
ax_anim 10, 0, 4, 0, 0, 0, 0,
ax_anim 6, 0, 3, 0, 0, 0, 0,
ax_anim 10, 0, 5, 0, 0, 0, 0,
ax_anim_terminator
sLoudredAnims_1_3:
ax_anim 6, 0, 6, 0, 0, 0, 0,
ax_anim 10, 0, 7, 0, 0, 0, 0,
ax_anim 6, 0, 6, 0, 0, 0, 0,
ax_anim 10, 0, 8, 0, 0, 0, 0,
ax_anim_terminator
sLoudredAnims_1_4:
ax_anim 6, 0, 9, 0, 0, 0, 0,
ax_anim 10, 0, 10, 0, 0, 0, 0,
ax_anim 6, 0, 9, 0, 0, 0, 0,
ax_anim 10, 0, 11, 0, 0, 0, 0,
ax_anim_terminator
sLoudredAnims_1_5:
ax_anim 6, 0, 12, 0, 0, 0, 0,
ax_anim 10, 0, 13, 0, 0, 0, 0,
ax_anim 6, 0, 12, 0, 0, 0, 0,
ax_anim 10, 0, 14, 0, 0, 0, 0,
ax_anim_terminator
sLoudredAnims_1_6:
ax_anim 6, 0, 15, 0, 0, 0, 0,
ax_anim 10, 0, 16, 0, 0, 0, 0,
ax_anim 6, 0, 15, 0, 0, 0, 0,
ax_anim 10, 0, 17, 0, 0, 0, 0,
ax_anim_terminator
sLoudredAnims_1_7:
ax_anim 6, 0, 18, 0, 0, 0, 0,
ax_anim 10, 0, 19, 0, 0, 0, 0,
ax_anim 6, 0, 18, 0, 0, 0, 0,
ax_anim 10, 0, 20, 0, 0, 0, 0,
ax_anim_terminator
sLoudredAnims_1_8:
ax_anim 6, 0, 21, 0, 0, 0, 0,
ax_anim 10, 0, 22, 0, 0, 0, 0,
ax_anim 6, 0, 21, 0, 0, 0, 0,
ax_anim 10, 0, 23, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sLoudredAnims_2_1:
ax_anim 2, 0, 24, 0, -1, 0, -1,
ax_anim 4, 0, 24, 0, -2, 0, -2,
ax_anim 1, 0, 26, 0, 0, 0, 0,
ax_anim 1, 2, 25, 0, 4, 0, 4,
ax_anim 1, 0, 26, 0, 10, 0, 10,
ax_anim 2, 0, 27, 0, 20, 0, 20,
ax_anim 2, 1, 27, 1, 20, 1, 20,
ax_anim 2, 0, 27, 0, 20, 0, 20,
ax_anim 2, 0, 27, 1, 20, 1, 20,
ax_anim 2, 0, 24, 0, 6, 0, 6,
ax_anim_terminator
sLoudredAnims_2_2:
ax_anim 2, 0, 28, -1, -1, -1, -1,
ax_anim 4, 0, 28, -2, -2, -2, -2,
ax_anim 1, 0, 30, 0, 0, 0, 0,
ax_anim 1, 2, 29, 4, 4, 4, 4,
ax_anim 1, 0, 30, 10, 10, 10, 10,
ax_anim 2, 0, 31, 20, 20, 20, 20,
ax_anim 2, 1, 31, 21, 19, 21, 19,
ax_anim 2, 0, 31, 20, 20, 20, 20,
ax_anim 2, 0, 31, 21, 19, 21, 19,
ax_anim 2, 0, 28, 6, 6, 6, 6,
ax_anim_terminator
sLoudredAnims_2_3:
ax_anim 2, 0, 32, -1, 0, -1, 0,
ax_anim 4, 0, 32, -2, 0, -2, 0,
ax_anim 1, 0, 34, 0, 0, 0, 0,
ax_anim 1, 2, 33, 4, 0, 4, 0,
ax_anim 1, 0, 34, 10, 0, 10, 0,
ax_anim 2, 0, 35, 21, 0, 21, 0,
ax_anim 2, 1, 35, 21, 1, 21, 1,
ax_anim 2, 0, 35, 21, 0, 21, 0,
ax_anim 2, 0, 35, 21, 1, 21, 1,
ax_anim 2, 0, 32, 6, 0, 6, 0,
ax_anim_terminator
sLoudredAnims_2_4:
ax_anim 2, 0, 36, -1, 1, -1, 1,
ax_anim 4, 0, 36, -2, 2, -2, 2,
ax_anim 1, 0, 38, 0, -1, 0, -1,
ax_anim 1, 2, 37, 5, -6, 5, -6,
ax_anim 1, 0, 38, 12, -13, 12, -13,
ax_anim 2, 0, 39, 19, -19, 19, -19,
ax_anim 2, 1, 39, 20, -18, 20, -18,
ax_anim 2, 0, 39, 19, -19, 19, -19,
ax_anim 2, 0, 39, 20, -18, 20, -18,
ax_anim 2, 0, 36, 6, -6, 6, -6,
ax_anim_terminator
sLoudredAnims_2_5:
ax_anim 2, 0, 40, 0, 1, 0, 1,
ax_anim 4, 0, 40, 0, 2, 0, 2,
ax_anim 1, 0, 42, 0, 0, 0, 0,
ax_anim 1, 2, 41, 0, -4, 0, -4,
ax_anim 1, 0, 42, 0, -11, 0, -11,
ax_anim 2, 0, 43, 0, -19, 0, -19,
ax_anim 2, 1, 43, 1, -19, 1, -19,
ax_anim 2, 0, 43, 0, -19, 0, -19,
ax_anim 2, 0, 43, 1, -19, 1, -19,
ax_anim 2, 0, 40, 0, -6, 0, -6,
ax_anim_terminator
sLoudredAnims_2_6:
ax_anim 2, 0, 44, 1, 1, 1, 1,
ax_anim 4, 0, 44, 2, 2, 2, 2,
ax_anim 1, 0, 46, 0, -1, 0, -1,
ax_anim 1, 2, 45, -5, -6, -5, -6,
ax_anim 1, 0, 46, -12, -13, -12, -13,
ax_anim 2, 0, 47, -19, -19, -19, -19,
ax_anim 2, 1, 47, -20, -18, -20, -18,
ax_anim 2, 0, 47, -19, -19, -19, -19,
ax_anim 2, 0, 47, -20, -18, -20, -18,
ax_anim 2, 0, 44, -6, -6, -6, -6,
ax_anim_terminator
sLoudredAnims_2_7:
ax_anim 2, 0, 48, 1, 0, 1, 0,
ax_anim 4, 0, 48, 2, 0, 2, 0,
ax_anim 1, 0, 50, 0, 0, 0, 0,
ax_anim 1, 2, 49, -4, 0, -4, 0,
ax_anim 1, 0, 50, -10, 0, -10, 0,
ax_anim 2, 0, 51, -21, 0, -21, 0,
ax_anim 2, 1, 51, -21, 1, -21, 1,
ax_anim 2, 0, 51, -21, 0, -21, 0,
ax_anim 2, 0, 51, -21, 1, -21, 1,
ax_anim 2, 0, 48, -6, 0, -6, 0,
ax_anim_terminator
sLoudredAnims_2_8:
ax_anim 2, 0, 52, 1, -1, 1, -1,
ax_anim 4, 0, 52, 2, -2, 2, -2,
ax_anim 1, 0, 54, 0, 0, 0, 0,
ax_anim 1, 2, 53, -4, 4, -4, 4,
ax_anim 1, 0, 54, -10, 10, -10, 10,
ax_anim 2, 0, 55, -20, 20, -20, 20,
ax_anim 2, 1, 55, -21, 19, -21, 19,
ax_anim 2, 0, 55, -20, 20, -20, 20,
ax_anim 2, 0, 55, -21, 19, -21, 19,
ax_anim 2, 0, 52, -6, 6, -6, 6,
ax_anim_terminator
.align 2
sLoudredAnims_3_1:
ax_anim 2, 0, 56, 0, -1, 0, -1,
ax_anim 4, 0, 56, 0, -2, 0, -2,
ax_anim 1, 0, 58, 0, 0, 0, 0,
ax_anim 1, 2, 57, 0, 4, 0, 4,
ax_anim 1, 0, 58, 0, 10, 0, 10,
ax_anim 2, 0, 59, 0, 20, 0, 20,
ax_anim 2, 1, 59, 1, 20, 1, 20,
ax_anim 2, 0, 59, 0, 20, 0, 20,
ax_anim 2, 0, 59, 1, 20, 1, 20,
ax_anim 2, 0, 56, 0, 6, 0, 6,
ax_anim_terminator
sLoudredAnims_3_2:
ax_anim 2, 0, 60, -1, -1, -1, -1,
ax_anim 4, 0, 60, -2, -2, -2, -2,
ax_anim 1, 0, 62, 0, 0, 0, 0,
ax_anim 1, 2, 61, 4, 4, 4, 4,
ax_anim 1, 0, 62, 10, 10, 10, 10,
ax_anim 2, 0, 63, 20, 20, 20, 20,
ax_anim 2, 1, 63, 21, 19, 21, 19,
ax_anim 2, 0, 63, 20, 20, 20, 20,
ax_anim 2, 0, 63, 21, 19, 21, 19,
ax_anim 2, 0, 60, 6, 6, 6, 6,
ax_anim_terminator
sLoudredAnims_3_3:
ax_anim 2, 0, 64, -1, 0, -1, 0,
ax_anim 4, 0, 64, -2, 0, -2, 0,
ax_anim 1, 0, 66, 0, 0, 0, 0,
ax_anim 1, 2, 65, 4, 0, 4, 0,
ax_anim 1, 0, 66, 10, 0, 10, 0,
ax_anim 2, 0, 67, 21, 0, 21, 0,
ax_anim 2, 1, 67, 21, 1, 21, 1,
ax_anim 2, 0, 67, 21, 0, 21, 0,
ax_anim 2, 0, 67, 21, 1, 21, 1,
ax_anim 2, 0, 64, 6, 0, 6, 0,
ax_anim_terminator
sLoudredAnims_3_4:
ax_anim 2, 0, 68, -1, 1, -1, 1,
ax_anim 4, 0, 68, -2, 2, -2, 2,
ax_anim 1, 0, 70, 0, -1, 0, -1,
ax_anim 1, 2, 69, 5, -6, 5, -6,
ax_anim 1, 0, 70, 12, -13, 12, -13,
ax_anim 2, 0, 71, 19, -19, 19, -19,
ax_anim 2, 1, 71, 20, -18, 20, -18,
ax_anim 2, 0, 71, 19, -19, 19, -19,
ax_anim 2, 0, 71, 20, -18, 20, -18,
ax_anim 2, 0, 68, 6, -6, 6, -6,
ax_anim_terminator
sLoudredAnims_3_5:
ax_anim 2, 0, 72, 0, 1, 0, 1,
ax_anim 4, 0, 72, 0, 2, 0, 2,
ax_anim 1, 0, 74, 0, 0, 0, 0,
ax_anim 1, 2, 73, 0, -4, 0, -4,
ax_anim 1, 0, 74, 0, -11, 0, -11,
ax_anim 2, 0, 75, 0, -19, 0, -19,
ax_anim 2, 1, 75, 1, -19, 1, -19,
ax_anim 2, 0, 75, 0, -19, 0, -19,
ax_anim 2, 0, 75, 1, -19, 1, -19,
ax_anim 2, 0, 72, 0, -6, 0, -6,
ax_anim_terminator
sLoudredAnims_3_6:
ax_anim 2, 0, 76, 1, 1, 1, 1,
ax_anim 4, 0, 76, 2, 2, 2, 2,
ax_anim 1, 0, 78, 0, -1, 0, -1,
ax_anim 1, 2, 77, -5, -6, -5, -6,
ax_anim 1, 0, 78, -12, -13, -12, -13,
ax_anim 2, 0, 79, -19, -19, -19, -19,
ax_anim 2, 1, 79, -20, -18, -20, -18,
ax_anim 2, 0, 79, -19, -19, -19, -19,
ax_anim 2, 0, 79, -20, -18, -20, -18,
ax_anim 2, 0, 76, -6, -6, -6, -6,
ax_anim_terminator
sLoudredAnims_3_7:
ax_anim 2, 0, 80, 1, 0, 1, 0,
ax_anim 4, 0, 80, 2, 0, 2, 0,
ax_anim 1, 0, 82, 0, 0, 0, 0,
ax_anim 1, 2, 81, -4, 0, -4, 0,
ax_anim 1, 0, 82, -10, 0, -10, 0,
ax_anim 2, 0, 83, -21, 0, -21, 0,
ax_anim 2, 1, 83, -21, 1, -21, 1,
ax_anim 2, 0, 83, -21, 0, -21, 0,
ax_anim 2, 0, 83, -21, 1, -21, 1,
ax_anim 2, 0, 80, -6, 0, -6, 0,
ax_anim_terminator
sLoudredAnims_3_8:
ax_anim 2, 0, 84, 1, -1, 1, -1,
ax_anim 4, 0, 84, 2, -2, 2, -2,
ax_anim 1, 0, 86, 0, 0, 0, 0,
ax_anim 1, 2, 85, -4, 4, -4, 4,
ax_anim 1, 0, 86, -10, 10, -10, 10,
ax_anim 2, 0, 87, -20, 20, -20, 20,
ax_anim 2, 1, 87, -21, 19, -21, 19,
ax_anim 2, 0, 87, -20, 20, -20, 20,
ax_anim 2, 0, 87, -21, 19, -21, 19,
ax_anim 2, 0, 84, -6, 6, -6, 6,
ax_anim_terminator
.align 2
sLoudredAnims_4_1:
ax_anim 3, 0, 89, 0, 0, 0, 0,
ax_anim 3, 0, 90, 0, 0, 0, 0,
ax_anim 3, 0, 89, 0, 0, 0, 0,
ax_anim 3, 0, 90, 0, 0, 0, 0,
ax_anim 3, 0, 89, 0, 0, 0, 0,
ax_anim 3, 0, 90, 0, 0, 0, 0,
ax_anim 1, 0, 91, 0, -2, 0, 0,
ax_anim 1, 2, 91, 0, -4, 0, 0,
ax_anim 4, 0, 91, 0, -5, 0, 0,
ax_anim 3, 0, 91, 0, -4, 0, 0,
ax_anim 2, 1, 91, 0, -2, 0, 0,
ax_anim 1, 0, 91, 0, 0, 0, 0,
ax_anim_terminator
sLoudredAnims_4_2:
ax_anim 3, 0, 93, 0, 0, 0, 0,
ax_anim 3, 0, 94, 0, 0, 0, 0,
ax_anim 3, 0, 93, 0, 0, 0, 0,
ax_anim 3, 0, 94, 0, 0, 0, 0,
ax_anim 3, 0, 93, 0, 0, 0, 0,
ax_anim 3, 0, 94, 0, 0, 0, 0,
ax_anim 1, 0, 95, 0, -2, 0, 0,
ax_anim 1, 2, 95, 0, -4, 0, 0,
ax_anim 4, 0, 95, 0, -5, 0, 0,
ax_anim 3, 0, 95, 0, -4, 0, 0,
ax_anim 2, 1, 95, 0, -2, 0, 0,
ax_anim 1, 0, 95, 0, 0, 0, 0,
ax_anim_terminator
sLoudredAnims_4_3:
ax_anim 3, 0, 97, 0, 0, 0, 0,
ax_anim 3, 0, 98, 0, 0, 0, 0,
ax_anim 3, 0, 97, 0, 0, 0, 0,
ax_anim 3, 0, 98, 0, 0, 0, 0,
ax_anim 3, 0, 97, 0, 0, 0, 0,
ax_anim 3, 0, 98, 0, 0, 0, 0,
ax_anim 1, 0, 99, 0, -2, 0, 0,
ax_anim 1, 2, 99, 0, -4, 0, 0,
ax_anim 4, 0, 99, 0, -5, 0, 0,
ax_anim 3, 0, 99, 0, -4, 0, 0,
ax_anim 2, 1, 99, 0, -2, 0, 0,
ax_anim 1, 0, 99, 0, 0, 0, 0,
ax_anim_terminator
sLoudredAnims_4_4:
ax_anim 3, 0, 101, 0, 0, 0, 0,
ax_anim 3, 0, 102, 0, 0, 0, 0,
ax_anim 3, 0, 101, 0, 0, 0, 0,
ax_anim 3, 0, 102, 0, 0, 0, 0,
ax_anim 3, 0, 101, 0, 0, 0, 0,
ax_anim 3, 0, 102, 0, 0, 0, 0,
ax_anim 1, 0, 103, 0, -2, 0, 0,
ax_anim 1, 2, 103, 0, -4, 0, 0,
ax_anim 4, 0, 103, 0, -5, 0, 0,
ax_anim 3, 0, 103, 0, -4, 0, 0,
ax_anim 2, 1, 103, 0, -2, 0, 0,
ax_anim 1, 0, 103, 0, 0, 0, 0,
ax_anim_terminator
sLoudredAnims_4_5:
ax_anim 3, 0, 105, 0, 0, 0, 0,
ax_anim 3, 0, 106, 0, 0, 0, 0,
ax_anim 3, 0, 105, 0, 0, 0, 0,
ax_anim 3, 0, 106, 0, 0, 0, 0,
ax_anim 3, 0, 105, 0, 0, 0, 0,
ax_anim 3, 0, 106, 0, 0, 0, 0,
ax_anim 1, 0, 107, 0, -2, 0, 0,
ax_anim 1, 2, 107, 0, -4, 0, 0,
ax_anim 4, 0, 107, 0, -5, 0, 0,
ax_anim 3, 0, 107, 0, -4, 0, 0,
ax_anim 2, 1, 107, 0, -2, 0, 0,
ax_anim 1, 0, 107, 0, 0, 0, 0,
ax_anim_terminator
sLoudredAnims_4_6:
ax_anim 3, 0, 109, 0, 0, 0, 0,
ax_anim 3, 0, 110, 0, 0, 0, 0,
ax_anim 3, 0, 109, 0, 0, 0, 0,
ax_anim 3, 0, 110, 0, 0, 0, 0,
ax_anim 3, 0, 109, 0, 0, 0, 0,
ax_anim 3, 0, 110, 0, 0, 0, 0,
ax_anim 1, 0, 111, 0, -2, 0, 0,
ax_anim 1, 2, 111, 0, -4, 0, 0,
ax_anim 4, 0, 111, 0, -5, 0, 0,
ax_anim 3, 0, 111, 0, -4, 0, 0,
ax_anim 2, 1, 111, 0, -2, 0, 0,
ax_anim 1, 0, 111, 0, 0, 0, 0,
ax_anim_terminator
sLoudredAnims_4_7:
ax_anim 3, 0, 113, 0, 0, 0, 0,
ax_anim 3, 0, 114, 0, 0, 0, 0,
ax_anim 3, 0, 113, 0, 0, 0, 0,
ax_anim 3, 0, 114, 0, 0, 0, 0,
ax_anim 3, 0, 113, 0, 0, 0, 0,
ax_anim 3, 0, 114, 0, 0, 0, 0,
ax_anim 1, 0, 115, 0, -2, 0, 0,
ax_anim 1, 2, 115, 0, -4, 0, 0,
ax_anim 4, 0, 115, 0, -5, 0, 0,
ax_anim 3, 0, 115, 0, -4, 0, 0,
ax_anim 2, 1, 115, 0, -2, 0, 0,
ax_anim 1, 0, 115, 0, 0, 0, 0,
ax_anim_terminator
sLoudredAnims_4_8:
ax_anim 3, 0, 117, 0, 0, 0, 0,
ax_anim 3, 0, 118, 0, 0, 0, 0,
ax_anim 3, 0, 117, 0, 0, 0, 0,
ax_anim 3, 0, 118, 0, 0, 0, 0,
ax_anim 3, 0, 117, 0, 0, 0, 0,
ax_anim 3, 0, 118, 0, 0, 0, 0,
ax_anim 1, 0, 119, 0, -2, 0, 0,
ax_anim 1, 2, 119, 0, -4, 0, 0,
ax_anim 4, 0, 119, 0, -5, 0, 0,
ax_anim 3, 0, 119, 0, -4, 0, 0,
ax_anim 2, 1, 119, 0, -2, 0, 0,
ax_anim 1, 0, 119, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sLoudredAnims_5_1:
ax_anim 2, 0, 124, 0, 0, 0, 0,
ax_anim 1, 0, 128, 0, -3, 0, 0,
ax_anim 2, 0, 130, 0, -5, 0, 0,
ax_anim 2, 0, 134, 0, -5, 0, 0,
ax_anim 1, 0, 136, 0, -3, 0, 0,
ax_anim 2, 0, 140, 0, 0, 0, 0,
ax_anim 1, 0, 142, 0, -3, 0, 0,
ax_anim 2, 2, 122, 0, -5, 0, 0,
ax_anim 2, 0, 124, 0, -5, 0, 0,
ax_anim 1, 0, 128, 0, -3, 0, 0,
ax_anim 2, 0, 130, 0, 0, 0, 0,
ax_anim 1, 0, 134, 0, -3, 0, 0,
ax_anim 2, 0, 136, 0, -5, 0, 0,
ax_anim 2, 0, 140, 0, -5, 0, 0,
ax_anim 1, 0, 142, 0, -3, 0, 0,
ax_anim 2, 1, 120, 0, 0, 0, 0,
ax_anim_terminator
sLoudredAnims_5_2:
ax_anim 2, 0, 127, 0, 0, 0, 0,
ax_anim 1, 0, 131, 0, -3, 0, 0,
ax_anim 2, 0, 133, 0, -5, 0, 0,
ax_anim 2, 0, 137, 0, -5, 0, 0,
ax_anim 1, 0, 139, 0, -3, 0, 0,
ax_anim 2, 0, 143, 0, 0, 0, 0,
ax_anim 1, 0, 121, 0, -3, 0, 0,
ax_anim 2, 2, 125, 0, -5, 0, 0,
ax_anim 2, 0, 127, 0, -5, 0, 0,
ax_anim 1, 0, 131, 0, -3, 0, 0,
ax_anim 2, 0, 133, 0, 0, 0, 0,
ax_anim 1, 0, 137, 0, -3, 0, 0,
ax_anim 2, 0, 139, 0, -5, 0, 0,
ax_anim 2, 0, 143, 0, -5, 0, 0,
ax_anim 1, 0, 121, 0, -3, 0, 0,
ax_anim 2, 1, 123, 0, 0, 0, 0,
ax_anim_terminator
sLoudredAnims_5_3:
ax_anim 2, 0, 130, 0, 0, 0, 0,
ax_anim 1, 0, 134, 0, -3, 0, 0,
ax_anim 2, 0, 136, 0, -5, 0, 0,
ax_anim 2, 0, 140, 0, -5, 0, 0,
ax_anim 1, 0, 142, 0, -3, 0, 0,
ax_anim 2, 0, 122, 0, 0, 0, 0,
ax_anim 1, 0, 124, 0, -3, 0, 0,
ax_anim 2, 2, 128, 0, -5, 0, 0,
ax_anim 2, 0, 130, 0, -5, 0, 0,
ax_anim 1, 0, 134, 0, -3, 0, 0,
ax_anim 2, 0, 136, 0, 0, 0, 0,
ax_anim 1, 0, 140, 0, -3, 0, 0,
ax_anim 2, 0, 142, 0, -5, 0, 0,
ax_anim 2, 0, 122, 0, -5, 0, 0,
ax_anim 1, 0, 124, 0, -3, 0, 0,
ax_anim 2, 1, 126, 0, 0, 0, 0,
ax_anim_terminator
sLoudredAnims_5_4:
ax_anim 2, 0, 133, 0, 0, 0, 0,
ax_anim 1, 0, 137, 0, -3, 0, 0,
ax_anim 2, 0, 139, 0, -5, 0, 0,
ax_anim 2, 0, 143, 0, -5, 0, 0,
ax_anim 1, 0, 121, 0, -3, 0, 0,
ax_anim 2, 0, 125, 0, 0, 0, 0,
ax_anim 1, 0, 127, 0, -3, 0, 0,
ax_anim 2, 2, 131, 0, -5, 0, 0,
ax_anim 2, 0, 133, 0, -5, 0, 0,
ax_anim 1, 0, 137, 0, -3, 0, 0,
ax_anim 2, 0, 139, 0, 0, 0, 0,
ax_anim 1, 0, 143, 0, -3, 0, 0,
ax_anim 2, 0, 121, 0, -5, 0, 0,
ax_anim 2, 0, 125, 0, -5, 0, 0,
ax_anim 1, 0, 127, 0, -3, 0, 0,
ax_anim 2, 1, 129, 0, 0, 0, 0,
ax_anim_terminator
sLoudredAnims_5_5:
ax_anim 2, 0, 136, 0, 0, 0, 0,
ax_anim 1, 0, 140, 0, -3, 0, 0,
ax_anim 2, 0, 142, 0, -5, 0, 0,
ax_anim 2, 0, 122, 0, -5, 0, 0,
ax_anim 1, 0, 124, 0, -3, 0, 0,
ax_anim 2, 0, 128, 0, 0, 0, 0,
ax_anim 1, 0, 130, 0, -3, 0, 0,
ax_anim 2, 2, 134, 0, -5, 0, 0,
ax_anim 2, 0, 136, 0, -5, 0, 0,
ax_anim 1, 0, 140, 0, -3, 0, 0,
ax_anim 2, 0, 142, 0, 0, 0, 0,
ax_anim 1, 0, 122, 0, -3, 0, 0,
ax_anim 2, 0, 124, 0, -5, 0, 0,
ax_anim 2, 0, 128, 0, -5, 0, 0,
ax_anim 1, 0, 130, 0, -3, 0, 0,
ax_anim 2, 1, 132, 0, 0, 0, 0,
ax_anim_terminator
sLoudredAnims_5_6:
ax_anim 2, 0, 139, 0, 0, 0, 0,
ax_anim 1, 0, 143, 0, -3, 0, 0,
ax_anim 2, 0, 121, 0, -5, 0, 0,
ax_anim 2, 0, 125, 0, -5, 0, 0,
ax_anim 1, 0, 127, 0, -3, 0, 0,
ax_anim 2, 0, 131, 0, 0, 0, 0,
ax_anim 1, 0, 133, 0, -3, 0, 0,
ax_anim 2, 2, 137, 0, -5, 0, 0,
ax_anim 2, 0, 139, 0, -5, 0, 0,
ax_anim 1, 0, 143, 0, -3, 0, 0,
ax_anim 2, 0, 121, 0, 0, 0, 0,
ax_anim 1, 0, 125, 0, -3, 0, 0,
ax_anim 2, 0, 127, 0, -5, 0, 0,
ax_anim 2, 0, 131, 0, -5, 0, 0,
ax_anim 1, 0, 133, 0, -3, 0, 0,
ax_anim 2, 1, 135, 0, 0, 0, 0,
ax_anim_terminator
sLoudredAnims_5_7:
ax_anim 2, 0, 142, 0, 0, 0, 0,
ax_anim 1, 0, 122, 0, -3, 0, 0,
ax_anim 2, 0, 124, 0, -5, 0, 0,
ax_anim 2, 0, 128, 0, -5, 0, 0,
ax_anim 1, 0, 130, 0, -3, 0, 0,
ax_anim 2, 0, 134, 0, 0, 0, 0,
ax_anim 1, 0, 136, 0, -3, 0, 0,
ax_anim 2, 2, 140, 0, -5, 0, 0,
ax_anim 2, 0, 142, 0, -5, 0, 0,
ax_anim 1, 0, 122, 0, -3, 0, 0,
ax_anim 2, 0, 124, 0, 0, 0, 0,
ax_anim 1, 0, 128, 0, -3, 0, 0,
ax_anim 2, 0, 130, 0, -5, 0, 0,
ax_anim 2, 0, 134, 0, -5, 0, 0,
ax_anim 1, 0, 136, 0, -3, 0, 0,
ax_anim 2, 1, 138, 0, 0, 0, 0,
ax_anim_terminator
sLoudredAnims_5_8:
ax_anim 2, 0, 121, 0, 0, 0, 0,
ax_anim 1, 0, 125, 0, -3, 0, 0,
ax_anim 2, 0, 127, 0, -5, 0, 0,
ax_anim 2, 0, 131, 0, -5, 0, 0,
ax_anim 1, 0, 133, 0, -3, 0, 0,
ax_anim 2, 0, 137, 0, 0, 0, 0,
ax_anim 1, 0, 139, 0, -3, 0, 0,
ax_anim 2, 2, 143, 0, -5, 0, 0,
ax_anim 2, 0, 121, 0, -5, 0, 0,
ax_anim 1, 0, 125, 0, -3, 0, 0,
ax_anim 2, 0, 127, 0, 0, 0, 0,
ax_anim 1, 0, 131, 0, -3, 0, 0,
ax_anim 2, 0, 133, 0, -5, 0, 0,
ax_anim 2, 0, 137, 0, -5, 0, 0,
ax_anim 1, 0, 139, 0, -3, 0, 0,
ax_anim 2, 1, 141, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sLoudredAnims_6_1:
ax_anim 30, 0, 144, 0, 0, 0, 0,
ax_anim 35, 0, 145, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sLoudredAnims_7_1:
ax_anim 2, 0, 146, 0, -2, 0, -2,
ax_anim 8, 0, 146, 0, -3, 0, -3,
ax_anim_terminator
sLoudredAnims_7_2:
ax_anim 2, 0, 147, -2, -2, -2, -2,
ax_anim 8, 0, 147, -3, -3, -3, -3,
ax_anim_terminator
sLoudredAnims_7_3:
ax_anim 2, 0, 148, -2, 0, -2, 0,
ax_anim 8, 0, 148, -3, 0, -3, 0,
ax_anim_terminator
sLoudredAnims_7_4:
ax_anim 2, 0, 149, -2, 2, -2, 2,
ax_anim 8, 0, 149, -3, 3, -3, 3,
ax_anim_terminator
sLoudredAnims_7_5:
ax_anim 2, 0, 150, 0, 2, 0, 2,
ax_anim 8, 0, 150, 0, 3, 0, 3,
ax_anim_terminator
sLoudredAnims_7_6:
ax_anim 2, 0, 151, 2, 2, 2, 2,
ax_anim 8, 0, 151, 3, 3, 3, 3,
ax_anim_terminator
sLoudredAnims_7_7:
ax_anim 2, 0, 152, 2, 0, 2, 0,
ax_anim 8, 0, 152, 3, 0, 3, 0,
ax_anim_terminator
sLoudredAnims_7_8:
ax_anim 2, 0, 153, 2, -2, 2, -2,
ax_anim 8, 0, 153, 3, -3, 3, -3,
ax_anim_terminator
.align 2
sLoudredAnims_8_1:
ax_anim 40, 0, 154, 0, 0, 0, 0,
ax_anim 1, 0, 155, 0, -3, 0, 0,
ax_anim 1, 0, 155, 0, -5, 0, 0,
ax_anim 4, 0, 155, 0, -6, 0, 0,
ax_anim 4, 0, 155, 0, -5, 0, 0,
ax_anim 2, 0, 155, 0, -2, 0, 0,
ax_anim 1, 0, 154, 0, 0, 0, 0,
ax_anim_terminator
sLoudredAnims_8_2:
ax_anim 40, 0, 156, 0, 0, 0, 0,
ax_anim 1, 0, 157, 0, -3, 0, 0,
ax_anim 1, 0, 157, 0, -5, 0, 0,
ax_anim 4, 0, 157, 0, -6, 0, 0,
ax_anim 4, 0, 157, 0, -5, 0, 0,
ax_anim 2, 0, 157, 0, -2, 0, 0,
ax_anim 1, 0, 156, 0, 0, 0, 0,
ax_anim_terminator
sLoudredAnims_8_3:
ax_anim 40, 0, 158, 0, 0, 0, 0,
ax_anim 1, 0, 159, 0, -3, 0, 0,
ax_anim 1, 0, 159, 0, -5, 0, 0,
ax_anim 4, 0, 159, 0, -6, 0, 0,
ax_anim 4, 0, 159, 0, -5, 0, 0,
ax_anim 2, 0, 159, 0, -2, 0, 0,
ax_anim 1, 0, 158, 0, 0, 0, 0,
ax_anim_terminator
sLoudredAnims_8_4:
ax_anim 40, 0, 160, 0, 0, 0, 0,
ax_anim 1, 0, 161, 0, -3, 0, 0,
ax_anim 1, 0, 161, 0, -5, 0, 0,
ax_anim 4, 0, 161, 0, -6, 0, 0,
ax_anim 4, 0, 161, 0, -5, 0, 0,
ax_anim 2, 0, 161, 0, -2, 0, 0,
ax_anim 1, 0, 160, 0, 0, 0, 0,
ax_anim_terminator
sLoudredAnims_8_5:
ax_anim 40, 0, 162, 0, 0, 0, 0,
ax_anim 1, 0, 163, 0, -3, 0, 0,
ax_anim 1, 0, 163, 0, -5, 0, 0,
ax_anim 4, 0, 163, 0, -6, 0, 0,
ax_anim 4, 0, 163, 0, -5, 0, 0,
ax_anim 2, 0, 163, 0, -2, 0, 0,
ax_anim 1, 0, 162, 0, 0, 0, 0,
ax_anim_terminator
sLoudredAnims_8_6:
ax_anim 40, 0, 164, 0, 0, 0, 0,
ax_anim 1, 0, 165, 0, -3, 0, 0,
ax_anim 1, 0, 165, 0, -5, 0, 0,
ax_anim 4, 0, 165, 0, -6, 0, 0,
ax_anim 4, 0, 165, 0, -5, 0, 0,
ax_anim 2, 0, 165, 0, -2, 0, 0,
ax_anim 1, 0, 164, 0, 0, 0, 0,
ax_anim_terminator
sLoudredAnims_8_7:
ax_anim 40, 0, 166, 0, 0, 0, 0,
ax_anim 1, 0, 167, 0, -3, 0, 0,
ax_anim 1, 0, 167, 0, -5, 0, 0,
ax_anim 4, 0, 167, 0, -6, 0, 0,
ax_anim 4, 0, 167, 0, -5, 0, 0,
ax_anim 2, 0, 167, 0, -2, 0, 0,
ax_anim 1, 0, 166, 0, 0, 0, 0,
ax_anim_terminator
sLoudredAnims_8_8:
ax_anim 40, 0, 168, 0, 0, 0, 0,
ax_anim 1, 0, 169, 0, -3, 0, 0,
ax_anim 1, 0, 169, 0, -5, 0, 0,
ax_anim 4, 0, 169, 0, -6, 0, 0,
ax_anim 4, 0, 169, 0, -5, 0, 0,
ax_anim 2, 0, 169, 0, -2, 0, 0,
ax_anim 1, 0, 168, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sLoudredAnims_9_1:
ax_anim 2, 0, 170, 0, 0, 0, 0,
ax_anim 1, 0, 171, 6, 3, 6, 3,
ax_anim 2, 0, 172, 9, 9, 9, 9,
ax_anim 2, 0, 173, 9, 18, 9, 18,
ax_anim 3, 0, 174, 0, 20, 0, 21,
ax_anim 2, 3, 175, -9, 18, -9, 18,
ax_anim 2, 0, 176, -9, 9, -9, 9,
ax_anim 1, 0, 177, -6, 3, -6, 3,
ax_anim 1, 0, 170, 0, 0, 0, 0,
ax_anim_terminator
sLoudredAnims_9_2:
ax_anim 2, 0, 177, 0, 0, 0, 0,
ax_anim 1, 0, 170, 8, 0, 8, 0,
ax_anim 2, 0, 171, 19, 4, 19, 4,
ax_anim 2, 0, 172, 23, 15, 23, 15,
ax_anim 3, 0, 173, 21, 20, 21, 20,
ax_anim 2, 3, 174, 11, 22, 11, 22,
ax_anim 2, 0, 175, 4, 15, 4, 15,
ax_anim 1, 0, 176, 0, 7, 0, 7,
ax_anim 1, 0, 177, 0, 0, 0, 0,
ax_anim_terminator
sLoudredAnims_9_3:
ax_anim 2, 0, 176, 0, 0, 0, 0,
ax_anim 1, 0, 177, 3, -5, 3, -5,
ax_anim 2, 0, 170, 11, -6, 11, -6,
ax_anim 2, 0, 171, 17, -7, 17, -7,
ax_anim 3, 0, 172, 21, 0, 21, 0,
ax_anim 2, 3, 173, 18, 4, 18, 4,
ax_anim 2, 0, 174, 12, 5, 12, 5,
ax_anim 1, 0, 175, 4, 5, 4, 5,
ax_anim 1, 0, 176, 0, 0, 0, 0,
ax_anim_terminator
sLoudredAnims_9_4:
ax_anim 2, 0, 175, 0, 0, 0, 0,
ax_anim 1, 0, 176, 0, -7, 0, -7,
ax_anim 2, 0, 177, 5, -16, 5, -16,
ax_anim 2, 0, 170, 11, -19, 11, -19,
ax_anim 3, 0, 171, 21, -20, 21, -20,
ax_anim 2, 3, 172, 24, -14, 24, -14,
ax_anim 2, 0, 173, 20, -5, 20, -5,
ax_anim 1, 0, 174, 7, -1, 7, -1,
ax_anim 1, 0, 175, 0, 0, 0, 0,
ax_anim_terminator
sLoudredAnims_9_5:
ax_anim 2, 0, 174, 0, 0, 0, 0,
ax_anim 1, 0, 175, -7, -4, -7, -4,
ax_anim 2, 0, 176, -10, -12, -10, -12,
ax_anim 2, 0, 177, -8, -18, -8, -18,
ax_anim 3, 0, 170, 0, -18, 0, -18,
ax_anim 2, 3, 171, 8, -18, 8, -18,
ax_anim 2, 0, 172, 10, -10, 10, -10,
ax_anim 1, 0, 173, 7, -4, 7, -4,
ax_anim 1, 0, 174, 0, 0, 0, 0,
ax_anim_terminator
sLoudredAnims_9_6:
ax_anim 2, 0, 173, 0, 0, 0, 0,
ax_anim 1, 0, 172, 0, -7, 0, -7,
ax_anim 2, 0, 171, -5, -16, -5, -16,
ax_anim 2, 0, 170, -11, -19, -11, -19,
ax_anim 3, 0, 177, -21, -20, -21, -20,
ax_anim 2, 3, 176, -24, -14, -24, -14,
ax_anim 2, 0, 175, -20, -5, -20, -5,
ax_anim 1, 0, 174, -7, -1, -7, -1,
ax_anim 1, 0, 173, 0, 0, 0, 0,
ax_anim_terminator
sLoudredAnims_9_7:
ax_anim 2, 0, 172, 0, 0, 0, 0,
ax_anim 1, 0, 171, -3, -5, -3, -5,
ax_anim 2, 0, 170, -11, -6, -11, -6,
ax_anim 2, 0, 177, -17, -7, -17, -7,
ax_anim 3, 0, 176, -21, 0, -21, 0,
ax_anim 2, 3, 175, -18, 4, -18, 4,
ax_anim 2, 0, 174, -12, 5, -12, 5,
ax_anim 1, 0, 173, -4, 5, -4, 5,
ax_anim 1, 0, 172, 0, 0, 0, 0,
ax_anim_terminator
sLoudredAnims_9_8:
ax_anim 2, 0, 171, 0, 0, 0, 0,
ax_anim 1, 0, 170, -8, 0, -8, 0,
ax_anim 2, 0, 177, -19, 4, -19, 4,
ax_anim 2, 0, 176, -23, 15, -23, 15,
ax_anim 3, 0, 175, -21, 20, -21, 20,
ax_anim 2, 3, 174, -11, 22, -11, 22,
ax_anim 2, 0, 173, -4, 15, -4, 15,
ax_anim 1, 0, 172, 0, 7, 0, 7,
ax_anim 1, 0, 171, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sLoudredAnims_10_1:
ax_anim 2, 0, 206, 0, 0, 0, 0,
ax_anim 2, 0, 206, 6, 0, 6, 0,
ax_anim 2, 0, 206, -6, 0, -6, 0,
ax_anim 2, 0, 206, 10, 0, 10, 0,
ax_anim 2, 0, 206, -10, 0, -10, 0,
ax_anim 2, 0, 206, 12, 0, 12, 0,
ax_anim 3, 0, 206, -12, 0, -12, 0,
ax_anim 3, 0, 206, 13, 0, 13, 0,
ax_anim 3, 0, 206, -13, 0, -13, 0,
ax_anim 2, 0, 206, 12, 0, 12, 0,
ax_anim 3, 0, 206, -12, 0, -12, 0,
ax_anim 2, 0, 206, 10, 0, 10, 0,
ax_anim 2, 0, 206, -10, 0, -10, 0,
ax_anim 2, 0, 206, 6, 0, 6, 0,
ax_anim 2, 0, 206, -6, 0, -6, 0,
ax_anim 2, 0, 206, 0, 0, 0, 0,
ax_anim_terminator
sLoudredAnims_10_2:
ax_anim 2, 0, 207, 0, 0, 0, 0,
ax_anim 2, 0, 207, 6, -6, 6, -6,
ax_anim 2, 0, 207, -6, 6, -6, 6,
ax_anim 2, 0, 207, 10, -10, 10, -10,
ax_anim 2, 0, 207, -10, 10, -10, 10,
ax_anim 2, 0, 207, 12, -12, 12, -12,
ax_anim 3, 0, 207, -12, 12, -12, 12,
ax_anim 3, 0, 207, 13, -13, 13, -13,
ax_anim 3, 0, 207, -13, 13, -13, 13,
ax_anim 2, 0, 207, 12, -12, 12, -12,
ax_anim 3, 0, 207, -12, 12, -12, 12,
ax_anim 2, 0, 207, 10, -10, 10, -10,
ax_anim 2, 0, 207, -10, 10, -10, 10,
ax_anim 2, 0, 207, 6, -6, 6, -6,
ax_anim 2, 0, 207, -6, 6, -6, 6,
ax_anim 2, 0, 207, 0, 0, 0, 0,
ax_anim_terminator
sLoudredAnims_10_3:
ax_anim 2, 0, 208, 0, 0, 0, 0,
ax_anim 2, 0, 208, 0, -6, 0, -6,
ax_anim 2, 0, 208, 0, 6, 0, 6,
ax_anim 2, 0, 208, 0, -10, 0, -10,
ax_anim 2, 0, 208, 0, 10, 0, 10,
ax_anim 2, 0, 208, 0, -12, 0, -12,
ax_anim 3, 0, 208, 0, 12, 0, 12,
ax_anim 3, 0, 208, 0, -13, 0, -13,
ax_anim 3, 0, 208, 0, 13, 0, 13,
ax_anim 2, 0, 208, 0, -12, 0, -12,
ax_anim 3, 0, 208, 0, 12, 0, 12,
ax_anim 2, 0, 208, 0, -10, 0, -10,
ax_anim 2, 0, 208, 0, 10, 0, 10,
ax_anim 2, 0, 208, 0, -6, 0, -6,
ax_anim 2, 0, 208, 0, 6, 0, 6,
ax_anim 2, 0, 208, 0, 0, 0, 0,
ax_anim_terminator
sLoudredAnims_10_4:
ax_anim 2, 0, 209, 0, 0, 0, 0,
ax_anim 2, 0, 209, -6, -6, -6, -6,
ax_anim 2, 0, 209, 6, 6, 6, 6,
ax_anim 2, 0, 209, -10, -10, -10, -10,
ax_anim 2, 0, 209, 10, 10, 10, 10,
ax_anim 2, 0, 209, -12, -12, -12, -12,
ax_anim 3, 0, 209, 12, 12, 12, 12,
ax_anim 3, 0, 209, -13, -13, -13, -13,
ax_anim 3, 0, 209, 13, 13, 13, 13,
ax_anim 2, 0, 209, -12, -12, -12, -12,
ax_anim 3, 0, 209, 12, 12, 12, 12,
ax_anim 2, 0, 209, -10, -10, -10, -10,
ax_anim 2, 0, 209, 10, 10, 10, 10,
ax_anim 2, 0, 209, -6, -6, -6, -6,
ax_anim 2, 0, 209, 6, 6, 6, 6,
ax_anim 2, 0, 209, 0, 0, 0, 0,
ax_anim_terminator
sLoudredAnims_10_5:
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 2, 0, 210, 6, 0, 6, 0,
ax_anim 2, 0, 210, -6, 0, -6, 0,
ax_anim 2, 0, 210, 10, 0, 10, 0,
ax_anim 2, 0, 210, -10, 0, -10, 0,
ax_anim 2, 0, 210, 12, 0, 12, 0,
ax_anim 3, 0, 210, -12, 0, -12, 0,
ax_anim 3, 0, 210, 13, 0, 13, 0,
ax_anim 3, 0, 210, -13, 0, -13, 0,
ax_anim 2, 0, 210, 12, 0, 12, 0,
ax_anim 3, 0, 210, -12, 0, -12, 0,
ax_anim 2, 0, 210, 10, 0, 10, 0,
ax_anim 2, 0, 210, -10, 0, -10, 0,
ax_anim 2, 0, 210, 6, 0, 6, 0,
ax_anim 2, 0, 210, -6, 0, -6, 0,
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim_terminator
sLoudredAnims_10_6:
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 2, 0, 211, 6, -6, 6, -6,
ax_anim 2, 0, 211, -6, 6, -6, 6,
ax_anim 2, 0, 211, 10, -10, 10, -10,
ax_anim 2, 0, 211, -10, 10, -10, 10,
ax_anim 2, 0, 211, 12, -12, 12, -12,
ax_anim 3, 0, 211, -12, 12, -12, 12,
ax_anim 3, 0, 211, 13, -13, 13, -13,
ax_anim 3, 0, 211, -13, 13, -13, 13,
ax_anim 2, 0, 211, 12, -12, 12, -12,
ax_anim 3, 0, 211, -12, 12, -12, 12,
ax_anim 2, 0, 211, 10, -10, 10, -10,
ax_anim 2, 0, 211, -10, 10, -10, 10,
ax_anim 2, 0, 211, 6, -6, 6, -6,
ax_anim 2, 0, 211, -6, 6, -6, 6,
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim_terminator
sLoudredAnims_10_7:
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 2, 0, 212, 0, -6, 0, -6,
ax_anim 2, 0, 212, 0, 6, 0, 6,
ax_anim 2, 0, 212, 0, -10, 0, -10,
ax_anim 2, 0, 212, 0, 10, 0, 10,
ax_anim 2, 0, 212, 0, -12, 0, -12,
ax_anim 3, 0, 212, 0, 12, 0, 12,
ax_anim 3, 0, 212, 0, -13, 0, -13,
ax_anim 3, 0, 212, 0, 13, 0, 13,
ax_anim 2, 0, 212, 0, -12, 0, -12,
ax_anim 3, 0, 212, 0, 12, 0, 12,
ax_anim 2, 0, 212, 0, -10, 0, -10,
ax_anim 2, 0, 212, 0, 10, 0, 10,
ax_anim 2, 0, 212, 0, -6, 0, -6,
ax_anim 2, 0, 212, 0, 6, 0, 6,
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim_terminator
sLoudredAnims_10_8:
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 2, 0, 213, -6, -6, -6, -6,
ax_anim 2, 0, 213, 6, 6, 6, 6,
ax_anim 2, 0, 213, -10, -10, -10, -10,
ax_anim 2, 0, 213, 10, 10, 10, 10,
ax_anim 2, 0, 213, -12, -12, -12, -12,
ax_anim 3, 0, 213, 12, 12, 12, 12,
ax_anim 3, 0, 213, -13, -13, -13, -13,
ax_anim 3, 0, 213, 13, 13, 13, 13,
ax_anim 2, 0, 213, -12, -12, -12, -12,
ax_anim 3, 0, 213, 12, 12, 12, 12,
ax_anim 2, 0, 213, -10, -10, -10, -10,
ax_anim 2, 0, 213, 10, 10, 10, 10,
ax_anim 2, 0, 213, -6, -6, -6, -6,
ax_anim 2, 0, 213, 6, 6, 6, 6,
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sLoudredAnims_11_1:
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 1, 0, 215, 0, -10, 0, 0,
ax_anim 2, 0, 215, 0, -16, 0, 0,
ax_anim 3, 0, 215, 0, -20, 0, 0,
ax_anim 4, 0, 215, 0, -21, 0, 0,
ax_anim 4, 0, 214, 0, -20, 0, 0,
ax_anim 3, 0, 216, 0, -21, 0, 0,
ax_anim 2, 0, 216, 0, -18, 0, 0,
ax_anim 1, 0, 216, 0, -12, 0, 0,
ax_anim 2, 2, 214, 0, 0, 0, 0,
ax_anim_terminator
sLoudredAnims_11_2:
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 1, 0, 218, 0, -10, 0, 0,
ax_anim 2, 0, 218, 0, -16, 0, 0,
ax_anim 3, 0, 218, 0, -20, 0, 0,
ax_anim 4, 0, 218, 0, -21, 0, 0,
ax_anim 4, 0, 217, 0, -21, 0, 0,
ax_anim 3, 0, 219, 0, -22, 0, 0,
ax_anim 2, 0, 219, 0, -18, 0, 0,
ax_anim 1, 0, 219, 0, -12, 0, 0,
ax_anim 2, 2, 217, 0, 0, 0, 0,
ax_anim_terminator
sLoudredAnims_11_3:
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 1, 0, 221, 0, -10, 0, 0,
ax_anim 2, 0, 221, 0, -16, 0, 0,
ax_anim 3, 0, 221, 0, -20, 0, 0,
ax_anim 4, 0, 221, 0, -21, 0, 0,
ax_anim 4, 0, 220, 0, -20, 0, 0,
ax_anim 3, 0, 222, 0, -21, 0, 0,
ax_anim 2, 0, 222, 0, -18, 0, 0,
ax_anim 1, 0, 222, 0, -12, 0, 0,
ax_anim 2, 2, 220, 0, 0, 0, 0,
ax_anim_terminator
sLoudredAnims_11_4:
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 1, 0, 224, 0, -10, 0, 0,
ax_anim 2, 0, 224, 0, -16, 0, 0,
ax_anim 3, 0, 224, 0, -20, 0, 0,
ax_anim 4, 0, 224, 0, -21, 0, 0,
ax_anim 4, 0, 223, 0, -20, 0, 0,
ax_anim 3, 0, 225, 0, -21, 0, 0,
ax_anim 2, 0, 225, 0, -17, 0, 0,
ax_anim 1, 0, 225, 0, -11, 0, 0,
ax_anim 2, 2, 223, 0, 0, 0, 0,
ax_anim_terminator
sLoudredAnims_11_5:
ax_anim 2, 0, 226, 0, 0, 0, 0,
ax_anim 1, 0, 227, 0, -10, 0, 0,
ax_anim 2, 0, 227, 0, -16, 0, 0,
ax_anim 3, 0, 227, 0, -20, 0, 0,
ax_anim 4, 0, 227, 0, -21, 0, 0,
ax_anim 4, 0, 226, 0, -21, 0, 0,
ax_anim 3, 0, 228, 0, -21, 0, 0,
ax_anim 2, 0, 228, 0, -18, 0, 0,
ax_anim 1, 0, 228, 0, -12, 0, 0,
ax_anim 2, 2, 226, 0, 0, 0, 0,
ax_anim_terminator
sLoudredAnims_11_6:
ax_anim 2, 0, 229, 0, 0, 0, 0,
ax_anim 1, 0, 230, 0, -10, 0, 0,
ax_anim 2, 0, 230, 0, -16, 0, 0,
ax_anim 3, 0, 230, 0, -20, 0, 0,
ax_anim 4, 0, 230, 0, -21, 0, 0,
ax_anim 4, 0, 229, 0, -20, 0, 0,
ax_anim 3, 0, 231, 0, -21, 0, 0,
ax_anim 2, 0, 231, 0, -17, 0, 0,
ax_anim 1, 0, 231, 0, -11, 0, 0,
ax_anim 2, 2, 229, 0, 0, 0, 0,
ax_anim_terminator
sLoudredAnims_11_7:
ax_anim 2, 0, 232, 0, 0, 0, 0,
ax_anim 1, 0, 233, 0, -10, 0, 0,
ax_anim 2, 0, 233, 0, -16, 0, 0,
ax_anim 3, 0, 233, 0, -20, 0, 0,
ax_anim 4, 0, 233, 0, -21, 0, 0,
ax_anim 4, 0, 232, 0, -20, 0, 0,
ax_anim 3, 0, 234, 0, -21, 0, 0,
ax_anim 2, 0, 234, 0, -18, 0, 0,
ax_anim 1, 0, 234, 0, -12, 0, 0,
ax_anim 2, 2, 232, 0, 0, 0, 0,
ax_anim_terminator
sLoudredAnims_11_8:
ax_anim 2, 0, 235, 0, 0, 0, 0,
ax_anim 1, 0, 236, 0, -10, 0, 0,
ax_anim 2, 0, 236, 0, -16, 0, 0,
ax_anim 3, 0, 236, 0, -20, 0, 0,
ax_anim 4, 0, 236, 0, -21, 0, 0,
ax_anim 4, 0, 235, 0, -21, 0, 0,
ax_anim 3, 0, 237, 0, -22, 0, 0,
ax_anim 2, 0, 237, 0, -18, 0, 0,
ax_anim 1, 0, 237, 0, -12, 0, 0,
ax_anim 2, 2, 235, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sLoudredAnims_12_1:
ax_anim 2, 0, 238, 1, 0, 1, 0,
ax_anim 2, 0, 238, 0, 0, 0, 0,
ax_anim 2, 0, 238, 1, 0, 1, 0,
ax_anim 2, 0, 238, 0, 0, 0, 0,
ax_anim 2, 0, 238, 1, 0, 1, 0,
ax_anim 2, 2, 238, 0, 0, 0, 0,
ax_anim 2, 0, 238, 1, 0, 1, 0,
ax_anim 2, 0, 238, 0, 0, 0, 0,
ax_anim 2, 0, 238, 1, 0, 1, 0,
ax_anim 2, 1, 238, 0, 0, 0, 0,
ax_anim_terminator
sLoudredAnims_12_2:
ax_anim 2, 0, 245, 1, -1, 1, -1,
ax_anim 2, 0, 245, 0, 0, 0, 0,
ax_anim 2, 0, 245, 1, -1, 1, -1,
ax_anim 2, 0, 245, 0, 0, 0, 0,
ax_anim 2, 0, 245, 1, -1, 1, -1,
ax_anim 2, 2, 245, 0, 0, 0, 0,
ax_anim 2, 0, 245, 1, -1, 1, -1,
ax_anim 2, 0, 245, 0, 0, 0, 0,
ax_anim 2, 0, 245, 1, -1, 1, -1,
ax_anim 2, 1, 245, 0, 0, 0, 0,
ax_anim_terminator
sLoudredAnims_12_3:
ax_anim 2, 0, 244, 0, -1, 0, -1,
ax_anim 2, 0, 244, 0, 0, 0, 0,
ax_anim 2, 0, 244, 0, -1, 0, -1,
ax_anim 2, 0, 244, 0, 0, 0, 0,
ax_anim 2, 0, 244, 0, -1, 0, -1,
ax_anim 2, 2, 244, 0, 0, 0, 0,
ax_anim 2, 0, 244, 0, -1, 0, -1,
ax_anim 2, 0, 244, 0, 0, 0, 0,
ax_anim 2, 0, 244, 0, -1, 0, -1,
ax_anim 2, 1, 244, 0, 0, 0, 0,
ax_anim_terminator
sLoudredAnims_12_4:
ax_anim 2, 0, 243, -1, -1, -1, -1,
ax_anim 2, 0, 243, 0, 0, 0, 0,
ax_anim 2, 0, 243, -1, -1, -1, -1,
ax_anim 2, 0, 243, 0, 0, 0, 0,
ax_anim 2, 0, 243, -1, -1, -1, -1,
ax_anim 2, 2, 243, 0, 0, 0, 0,
ax_anim 2, 0, 243, -1, -1, -1, -1,
ax_anim 2, 0, 243, 0, 0, 0, 0,
ax_anim 2, 0, 243, -1, -1, -1, -1,
ax_anim 2, 1, 243, 0, 0, 0, 0,
ax_anim_terminator
sLoudredAnims_12_5:
ax_anim 2, 0, 242, 1, 0, 1, 0,
ax_anim 2, 0, 242, 0, 0, 0, 0,
ax_anim 2, 0, 242, 1, 0, 1, 0,
ax_anim 2, 0, 242, 0, 0, 0, 0,
ax_anim 2, 0, 242, 1, 0, 1, 0,
ax_anim 2, 2, 242, 0, 0, 0, 0,
ax_anim 2, 0, 242, 1, 0, 1, 0,
ax_anim 2, 0, 242, 0, 0, 0, 0,
ax_anim 2, 0, 242, 1, 0, 1, 0,
ax_anim 2, 1, 242, 0, 0, 0, 0,
ax_anim_terminator
sLoudredAnims_12_6:
ax_anim 2, 0, 241, 1, -1, 1, -1,
ax_anim 2, 0, 241, 0, 0, 0, 0,
ax_anim 2, 0, 241, 1, -1, 1, -1,
ax_anim 2, 0, 241, 0, 0, 0, 0,
ax_anim 2, 0, 241, 1, -1, 1, -1,
ax_anim 2, 2, 241, 0, 0, 0, 0,
ax_anim 2, 0, 241, 1, -1, 1, -1,
ax_anim 2, 0, 241, 0, 0, 0, 0,
ax_anim 2, 0, 241, 1, -1, 1, -1,
ax_anim 2, 1, 241, 0, 0, 0, 0,
ax_anim_terminator
sLoudredAnims_12_7:
ax_anim 2, 0, 240, 0, -1, 0, -1,
ax_anim 2, 0, 240, 0, 0, 0, 0,
ax_anim 2, 0, 240, 0, -1, 0, -1,
ax_anim 2, 0, 240, 0, 0, 0, 0,
ax_anim 2, 0, 240, 0, -1, 0, -1,
ax_anim 2, 2, 240, 0, 0, 0, 0,
ax_anim 2, 0, 240, 0, -1, 0, -1,
ax_anim 2, 0, 240, 0, 0, 0, 0,
ax_anim 2, 0, 240, 0, -1, 0, -1,
ax_anim 2, 1, 240, 0, 0, 0, 0,
ax_anim_terminator
sLoudredAnims_12_8:
ax_anim 2, 0, 239, -1, -1, -1, -1,
ax_anim 2, 0, 239, 0, 0, 0, 0,
ax_anim 2, 0, 239, -1, -1, -1, -1,
ax_anim 2, 0, 239, 0, 0, 0, 0,
ax_anim 2, 0, 239, -1, -1, -1, -1,
ax_anim 2, 2, 239, 0, 0, 0, 0,
ax_anim 2, 0, 239, -1, -1, -1, -1,
ax_anim 2, 0, 239, 0, 0, 0, 0,
ax_anim 2, 0, 239, -1, -1, -1, -1,
ax_anim 2, 1, 239, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sLoudredAnims_13_1:
ax_anim 2, 0, 274, 0, 0, 0, 0,
ax_anim 2, 0, 275, 0, 0, 0, 0,
ax_anim 2, 0, 276, 0, 0, 0, 0,
ax_anim 2, 0, 277, 0, 0, 0, 0,
ax_anim 2, 0, 278, 0, 0, 0, 0,
ax_anim 2, 0, 279, 0, 0, 0, 0,
ax_anim 2, 0, 280, 0, 0, 0, 0,
ax_anim 2, 0, 281, 0, 0, 0, 0,
ax_anim 2, 2, 274, 0, 0, 0, 0,
ax_anim_terminator
sLoudredAnims_13_2:
ax_anim 2, 0, 281, 0, 0, 0, 0,
ax_anim 2, 0, 274, 0, 0, 0, 0,
ax_anim 2, 0, 275, 0, 0, 0, 0,
ax_anim 2, 0, 276, 0, 0, 0, 0,
ax_anim 2, 0, 277, 0, 0, 0, 0,
ax_anim 2, 0, 278, 0, 0, 0, 0,
ax_anim 2, 0, 279, 0, 0, 0, 0,
ax_anim 2, 0, 280, 0, 0, 0, 0,
ax_anim 2, 2, 281, 0, 0, 0, 0,
ax_anim_terminator
sLoudredAnims_13_3:
ax_anim 2, 0, 280, 0, 0, 0, 0,
ax_anim 2, 0, 281, 0, 0, 0, 0,
ax_anim 2, 0, 274, 0, 0, 0, 0,
ax_anim 2, 0, 275, 0, 0, 0, 0,
ax_anim 2, 0, 276, 0, 0, 0, 0,
ax_anim 2, 0, 277, 0, 0, 0, 0,
ax_anim 2, 0, 278, 0, 0, 0, 0,
ax_anim 2, 0, 279, 0, 0, 0, 0,
ax_anim 2, 2, 280, 0, 0, 0, 0,
ax_anim_terminator
sLoudredAnims_13_4:
ax_anim 2, 0, 279, 0, 0, 0, 0,
ax_anim 2, 0, 280, 0, 0, 0, 0,
ax_anim 2, 0, 281, 0, 0, 0, 0,
ax_anim 2, 0, 274, 0, 0, 0, 0,
ax_anim 2, 0, 275, 0, 0, 0, 0,
ax_anim 2, 0, 276, 0, 0, 0, 0,
ax_anim 2, 0, 277, 0, 0, 0, 0,
ax_anim 2, 0, 278, 0, 0, 0, 0,
ax_anim 2, 2, 279, 0, 0, 0, 0,
ax_anim_terminator
sLoudredAnims_13_5:
ax_anim 2, 0, 278, 0, 0, 0, 0,
ax_anim 2, 0, 279, 0, 0, 0, 0,
ax_anim 2, 0, 280, 0, 0, 0, 0,
ax_anim 2, 0, 281, 0, 0, 0, 0,
ax_anim 2, 0, 274, 0, 0, 0, 0,
ax_anim 2, 0, 275, 0, 0, 0, 0,
ax_anim 2, 0, 276, 0, 0, 0, 0,
ax_anim 2, 0, 277, 0, 0, 0, 0,
ax_anim 2, 2, 278, 0, 0, 0, 0,
ax_anim_terminator
sLoudredAnims_13_6:
ax_anim 2, 0, 277, 0, 0, 0, 0,
ax_anim 2, 0, 278, 0, 0, 0, 0,
ax_anim 2, 0, 279, 0, 0, 0, 0,
ax_anim 2, 0, 280, 0, 0, 0, 0,
ax_anim 2, 0, 281, 0, 0, 0, 0,
ax_anim 2, 0, 274, 0, 0, 0, 0,
ax_anim 2, 0, 275, 0, 0, 0, 0,
ax_anim 2, 0, 276, 0, 0, 0, 0,
ax_anim 2, 2, 277, 0, 0, 0, 0,
ax_anim_terminator
sLoudredAnims_13_7:
ax_anim 2, 0, 276, 0, 0, 0, 0,
ax_anim 2, 0, 277, 0, 0, 0, 0,
ax_anim 2, 0, 278, 0, 0, 0, 0,
ax_anim 2, 0, 279, 0, 0, 0, 0,
ax_anim 2, 0, 280, 0, 0, 0, 0,
ax_anim 2, 0, 281, 0, 0, 0, 0,
ax_anim 2, 0, 274, 0, 0, 0, 0,
ax_anim 2, 0, 275, 0, 0, 0, 0,
ax_anim 2, 2, 276, 0, 0, 0, 0,
ax_anim_terminator
sLoudredAnims_13_8:
ax_anim 2, 0, 275, 0, 0, 0, 0,
ax_anim 2, 0, 276, 0, 0, 0, 0,
ax_anim 2, 0, 277, 0, 0, 0, 0,
ax_anim 2, 0, 278, 0, 0, 0, 0,
ax_anim 2, 0, 279, 0, 0, 0, 0,
ax_anim 2, 0, 280, 0, 0, 0, 0,
ax_anim 2, 0, 281, 0, 0, 0, 0,
ax_anim 2, 0, 274, 0, 0, 0, 0,
ax_anim 2, 2, 275, 0, 0, 0, 0,
ax_anim_terminator
sLoudredGfx1:
.incbin "baserom.gba", 0x11F6FA8, 0x200
sLoudredSprites1:
ax_sprite sLoudredGfx1, 0x200
ax_sprite_terminator
sLoudredGfx2:
.incbin "baserom.gba", 0x11F71B8, 0x200
sLoudredSprites2:
ax_sprite sLoudredGfx2, 0x200
ax_sprite_terminator
sLoudredGfx3:
.incbin "baserom.gba", 0x11F73C8, 0x200
sLoudredSprites3:
ax_sprite sLoudredGfx3, 0x200
ax_sprite_terminator
sLoudredGfx4:
.incbin "baserom.gba", 0x11F75D8, 0x200
sLoudredSprites4:
ax_sprite sLoudredGfx4, 0x200
ax_sprite_terminator
sLoudredGfx5:
.incbin "baserom.gba", 0x11F77E8, 0x200
sLoudredSprites5:
ax_sprite sLoudredGfx5, 0x200
ax_sprite_terminator
sLoudredGfx6:
.incbin "baserom.gba", 0x11F79F8, 0x200
sLoudredSprites6:
ax_sprite sLoudredGfx6, 0x200
ax_sprite_terminator
sLoudredGfx7:
.incbin "baserom.gba", 0x11F7C08, 0x200
sLoudredSprites7:
ax_sprite sLoudredGfx7, 0x200
ax_sprite_terminator
sLoudredGfx8:
.incbin "baserom.gba", 0x11F7E18, 0x200
sLoudredSprites8:
ax_sprite sLoudredGfx8, 0x200
ax_sprite_terminator
sLoudredGfx9:
.incbin "baserom.gba", 0x11F8028, 0x200
sLoudredSprites9:
ax_sprite sLoudredGfx9, 0x200
ax_sprite_terminator
sLoudredGfx10:
.incbin "baserom.gba", 0x11F8238, 0x200
sLoudredSprites10:
ax_sprite sLoudredGfx10, 0x200
ax_sprite_terminator
sLoudredGfx11:
.incbin "baserom.gba", 0x11F8448, 0x200
sLoudredSprites11:
ax_sprite sLoudredGfx11, 0x200
ax_sprite_terminator
sLoudredGfx12:
.incbin "baserom.gba", 0x11F8658, 0x200
sLoudredSprites12:
ax_sprite sLoudredGfx12, 0x200
ax_sprite_terminator
sLoudredGfx13:
.incbin "baserom.gba", 0x11F8868, 0x200
sLoudredSprites13:
ax_sprite sLoudredGfx13, 0x200
ax_sprite_terminator
sLoudredGfx14:
.incbin "baserom.gba", 0x11F8A78, 0x200
sLoudredSprites14:
ax_sprite sLoudredGfx14, 0x200
ax_sprite_terminator
sLoudredGfx15:
.incbin "baserom.gba", 0x11F8C88, 0x200
sLoudredSprites15:
ax_sprite sLoudredGfx15, 0x200
ax_sprite_terminator
sLoudredGfx16:
.incbin "baserom.gba", 0x11F8E98, 0x100
sLoudredSprites16:
ax_sprite sLoudredGfx16, 0x100
ax_sprite_terminator
sLoudredGfx17:
.incbin "baserom.gba", 0x11F8FA8, 0x80
sLoudredSprites17:
ax_sprite sLoudredGfx17, 0x80
ax_sprite_terminator
sLoudredGfx18:
.incbin "baserom.gba", 0x11F9038, 0x20
sLoudredSprites18:
ax_sprite sLoudredGfx18, 0x20
ax_sprite_terminator
sLoudredGfx19:
.incbin "baserom.gba", 0x11F9068, 0x100
sLoudredSprites19:
ax_sprite sLoudredGfx19, 0x100
ax_sprite_terminator
sLoudredGfx20:
.incbin "baserom.gba", 0x11F9178, 0x80
sLoudredSprites20:
ax_sprite sLoudredGfx20, 0x80
ax_sprite_terminator
sLoudredGfx21:
.incbin "baserom.gba", 0x11F9208, 0x100
sLoudredSprites21:
ax_sprite sLoudredGfx21, 0x100
ax_sprite_terminator
sLoudredGfx22:
.incbin "baserom.gba", 0x11F9318, 0x20
sLoudredSprites22:
ax_sprite sLoudredGfx22, 0x20
ax_sprite_terminator
sLoudredGfx23:
.incbin "baserom.gba", 0x11F9348, 0xC0
sLoudredSprites23:
ax_sprite 0, 0x40
ax_sprite sLoudredGfx23, 0xc0
ax_sprite_terminator
sLoudredGfx24:
.incbin "baserom.gba", 0x11F9420, 0x80
sLoudredSprites24:
ax_sprite sLoudredGfx24, 0x80
ax_sprite_terminator
sLoudredGfx25:
.incbin "baserom.gba", 0x11F94B0, 0x100
sLoudredSprites25:
ax_sprite sLoudredGfx25, 0x100
ax_sprite_terminator
sLoudredGfx26:
.incbin "baserom.gba", 0x11F95C0, 0x80
sLoudredSprites26:
ax_sprite sLoudredGfx26, 0x80
ax_sprite_terminator
sLoudredGfx27:
.incbin "baserom.gba", 0x11F9650, 0x200
sLoudredSprites27:
ax_sprite sLoudredGfx27, 0x200
ax_sprite_terminator
sLoudredGfx28:
.incbin "baserom.gba", 0x11F9860, 0x200
sLoudredSprites28:
ax_sprite sLoudredGfx28, 0x200
ax_sprite_terminator
sLoudredGfx29:
.incbin "baserom.gba", 0x11F9A70, 0x200
sLoudredSprites29:
ax_sprite sLoudredGfx29, 0x200
ax_sprite_terminator
sLoudredGfx30:
.incbin "baserom.gba", 0x11F9C80, 0x200
sLoudredSprites30:
ax_sprite sLoudredGfx30, 0x200
ax_sprite_terminator
sLoudredGfx31:
.incbin "baserom.gba", 0x11F9E90, 0x200
sLoudredSprites31:
ax_sprite sLoudredGfx31, 0x200
ax_sprite_terminator
sLoudredGfx32:
.incbin "baserom.gba", 0x11FA0A0, 0x200
sLoudredSprites32:
ax_sprite sLoudredGfx32, 0x200
ax_sprite_terminator
sLoudredGfx33:
.incbin "baserom.gba", 0x11FA2B0, 0x200
sLoudredSprites33:
ax_sprite sLoudredGfx33, 0x200
ax_sprite_terminator
sAxPosesLoudred:
.4byte sLoudredPose1
.4byte sLoudredPose2
.4byte sLoudredPose3
.4byte sLoudredPose4
.4byte sLoudredPose5
.4byte sLoudredPose6
.4byte sLoudredPose7
.4byte sLoudredPose8
.4byte sLoudredPose9
.4byte sLoudredPose10
.4byte sLoudredPose11
.4byte sLoudredPose12
.4byte sLoudredPose13
.4byte sLoudredPose14
.4byte sLoudredPose15
.4byte sLoudredPose16
.4byte sLoudredPose17
.4byte sLoudredPose18
.4byte sLoudredPose19
.4byte sLoudredPose20
.4byte sLoudredPose21
.4byte sLoudredPose22
.4byte sLoudredPose23
.4byte sLoudredPose24
.4byte sLoudredPose25
.4byte sLoudredPose26
.4byte sLoudredPose27
.4byte sLoudredPose28
.4byte sLoudredPose29
.4byte sLoudredPose30
.4byte sLoudredPose31
.4byte sLoudredPose32
.4byte sLoudredPose33
.4byte sLoudredPose34
.4byte sLoudredPose35
.4byte sLoudredPose36
.4byte sLoudredPose37
.4byte sLoudredPose38
.4byte sLoudredPose39
.4byte sLoudredPose40
.4byte sLoudredPose41
.4byte sLoudredPose42
.4byte sLoudredPose43
.4byte sLoudredPose44
.4byte sLoudredPose45
.4byte sLoudredPose46
.4byte sLoudredPose47
.4byte sLoudredPose48
.4byte sLoudredPose49
.4byte sLoudredPose50
.4byte sLoudredPose51
.4byte sLoudredPose52
.4byte sLoudredPose53
.4byte sLoudredPose54
.4byte sLoudredPose55
.4byte sLoudredPose56
.4byte sLoudredPose57
.4byte sLoudredPose58
.4byte sLoudredPose59
.4byte sLoudredPose60
.4byte sLoudredPose61
.4byte sLoudredPose62
.4byte sLoudredPose63
.4byte sLoudredPose64
.4byte sLoudredPose65
.4byte sLoudredPose66
.4byte sLoudredPose67
.4byte sLoudredPose68
.4byte sLoudredPose69
.4byte sLoudredPose70
.4byte sLoudredPose71
.4byte sLoudredPose72
.4byte sLoudredPose73
.4byte sLoudredPose74
.4byte sLoudredPose75
.4byte sLoudredPose76
.4byte sLoudredPose77
.4byte sLoudredPose78
.4byte sLoudredPose79
.4byte sLoudredPose80
.4byte sLoudredPose81
.4byte sLoudredPose82
.4byte sLoudredPose83
.4byte sLoudredPose84
.4byte sLoudredPose85
.4byte sLoudredPose86
.4byte sLoudredPose87
.4byte sLoudredPose88
.4byte sLoudredPose89
.4byte sLoudredPose90
.4byte sLoudredPose91
.4byte sLoudredPose92
.4byte sLoudredPose93
.4byte sLoudredPose94
.4byte sLoudredPose95
.4byte sLoudredPose96
.4byte sLoudredPose97
.4byte sLoudredPose98
.4byte sLoudredPose99
.4byte sLoudredPose100
.4byte sLoudredPose101
.4byte sLoudredPose102
.4byte sLoudredPose103
.4byte sLoudredPose104
.4byte sLoudredPose105
.4byte sLoudredPose106
.4byte sLoudredPose107
.4byte sLoudredPose108
.4byte sLoudredPose109
.4byte sLoudredPose110
.4byte sLoudredPose111
.4byte sLoudredPose112
.4byte sLoudredPose113
.4byte sLoudredPose114
.4byte sLoudredPose115
.4byte sLoudredPose116
.4byte sLoudredPose117
.4byte sLoudredPose118
.4byte sLoudredPose119
.4byte sLoudredPose120
.4byte sLoudredPose121
.4byte sLoudredPose122
.4byte sLoudredPose123
.4byte sLoudredPose124
.4byte sLoudredPose125
.4byte sLoudredPose126
.4byte sLoudredPose127
.4byte sLoudredPose128
.4byte sLoudredPose129
.4byte sLoudredPose130
.4byte sLoudredPose131
.4byte sLoudredPose132
.4byte sLoudredPose133
.4byte sLoudredPose134
.4byte sLoudredPose135
.4byte sLoudredPose136
.4byte sLoudredPose137
.4byte sLoudredPose138
.4byte sLoudredPose139
.4byte sLoudredPose140
.4byte sLoudredPose141
.4byte sLoudredPose142
.4byte sLoudredPose143
.4byte sLoudredPose144
.4byte sLoudredPose145
.4byte sLoudredPose146
.4byte sLoudredPose147
.4byte sLoudredPose148
.4byte sLoudredPose149
.4byte sLoudredPose150
.4byte sLoudredPose151
.4byte sLoudredPose152
.4byte sLoudredPose153
.4byte sLoudredPose154
.4byte sLoudredPose155
.4byte sLoudredPose156
.4byte sLoudredPose157
.4byte sLoudredPose158
.4byte sLoudredPose159
.4byte sLoudredPose160
.4byte sLoudredPose161
.4byte sLoudredPose162
.4byte sLoudredPose163
.4byte sLoudredPose164
.4byte sLoudredPose165
.4byte sLoudredPose166
.4byte sLoudredPose167
.4byte sLoudredPose168
.4byte sLoudredPose169
.4byte sLoudredPose170
.4byte sLoudredPose171
.4byte sLoudredPose172
.4byte sLoudredPose173
.4byte sLoudredPose174
.4byte sLoudredPose175
.4byte sLoudredPose176
.4byte sLoudredPose177
.4byte sLoudredPose178
.4byte sLoudredPose179
.4byte sLoudredPose180
.4byte sLoudredPose181
.4byte sLoudredPose182
.4byte sLoudredPose183
.4byte sLoudredPose184
.4byte sLoudredPose185
.4byte sLoudredPose186
.4byte sLoudredPose187
.4byte sLoudredPose188
.4byte sLoudredPose189
.4byte sLoudredPose190
.4byte sLoudredPose191
.4byte sLoudredPose192
.4byte sLoudredPose193
.4byte sLoudredPose194
.4byte sLoudredPose195
.4byte sLoudredPose196
.4byte sLoudredPose197
.4byte sLoudredPose198
.4byte sLoudredPose199
.4byte sLoudredPose200
.4byte sLoudredPose201
.4byte sLoudredPose202
.4byte sLoudredPose203
.4byte sLoudredPose204
.4byte sLoudredPose205
.4byte sLoudredPose206
.4byte sLoudredPose207
.4byte sLoudredPose208
.4byte sLoudredPose209
.4byte sLoudredPose210
.4byte sLoudredPose211
.4byte sLoudredPose212
.4byte sLoudredPose213
.4byte sLoudredPose214
.4byte sLoudredPose215
.4byte sLoudredPose216
.4byte sLoudredPose217
.4byte sLoudredPose218
.4byte sLoudredPose219
.4byte sLoudredPose220
.4byte sLoudredPose221
.4byte sLoudredPose222
.4byte sLoudredPose223
.4byte sLoudredPose224
.4byte sLoudredPose225
.4byte sLoudredPose226
.4byte sLoudredPose227
.4byte sLoudredPose228
.4byte sLoudredPose229
.4byte sLoudredPose230
.4byte sLoudredPose231
.4byte sLoudredPose232
.4byte sLoudredPose233
.4byte sLoudredPose234
.4byte sLoudredPose235
.4byte sLoudredPose236
.4byte sLoudredPose237
.4byte sLoudredPose238
.4byte sLoudredPose239
.4byte sLoudredPose240
.4byte sLoudredPose241
.4byte sLoudredPose242
.4byte sLoudredPose243
.4byte sLoudredPose244
.4byte sLoudredPose245
.4byte sLoudredPose246
.4byte sLoudredPose247
.4byte sLoudredPose248
.4byte sLoudredPose249
.4byte sLoudredPose250
.4byte sLoudredPose251
.4byte sLoudredPose252
.4byte sLoudredPose253
.4byte sLoudredPose254
.4byte sLoudredPose255
.4byte sLoudredPose256
.4byte sLoudredPose257
.4byte sLoudredPose258
.4byte sLoudredPose259
.4byte sLoudredPose260
.4byte sLoudredPose261
.4byte sLoudredPose262
.4byte sLoudredPose263
.4byte sLoudredPose264
.4byte sLoudredPose265
.4byte sLoudredPose266
.4byte sLoudredPose267
.4byte sLoudredPose268
.4byte sLoudredPose269
.4byte sLoudredPose270
.4byte sLoudredPose271
.4byte sLoudredPose272
.4byte sLoudredPose273
.4byte sLoudredPose274
.4byte sLoudredPose275
.4byte sLoudredPose276
.4byte sLoudredPose277
.4byte sLoudredPose278
.4byte sLoudredPose279
.4byte sLoudredPose280
.4byte sLoudredPose281
.4byte sLoudredPose282
sAxPositionsLoudred:
.2byte   -1,   -8, 	  -9,  -13, 	   9,  -13, 	  -1,  -11
.2byte   -2,   -6, 	 -12,   -9, 	   9,  -13, 	  -2,   -9
.2byte    1,   -6, 	  -9,  -13, 	  12,   -9, 	   1,   -9
.2byte    2,   -7, 	   6,  -14, 	  -7,  -10, 	   2,  -10
.2byte    3,   -5, 	   7,  -10, 	  -8,  -11, 	   3,   -8
.2byte    1,   -5, 	   7,  -14, 	  -9,   -6, 	   1,   -8
.2byte    4,   -7, 	  -1,  -13, 	  -1,   -9, 	   1,   -8
.2byte    5,   -7, 	  -1,   -9, 	  -1,  -11, 	   2,   -8
.2byte    5,   -5, 	   0,  -15, 	   0,   -5, 	   2,   -7
.2byte    2,  -10, 	  -7,  -15, 	   7,  -11, 	  -1,  -10
.2byte   -2,  -10, 	  -8,   -9, 	   8,  -11, 	  -2,   -8
.2byte    1,   -8, 	  -7,  -15, 	   8,   -7, 	  -1,   -8
.2byte   -2,  -11, 	   8,  -13, 	  -9,  -13, 	  -1,  -11
.2byte    2,  -10, 	  11,   -9, 	  -9,  -14, 	   1,  -10
.2byte   -3,  -10, 	   8,  -14, 	 -11,   -9, 	  -2,  -10
.2byte   -3,  -10, 	   6,  -15, 	  -8,  -11, 	   0,  -10
.2byte    1,  -10, 	   7,   -9, 	  -9,  -11, 	   1,   -8
.2byte   -2,   -8, 	   6,  -15, 	  -9,   -7, 	   0,   -8
.2byte   -5,   -7, 	   0,  -13, 	   0,   -9, 	  -2,   -8
.2byte   -6,   -7, 	   0,   -9, 	   0,  -11, 	  -3,   -8
.2byte   -6,   -5, 	  -1,  -15, 	  -1,   -5, 	  -3,   -7
.2byte   -3,   -7, 	  -7,  -14, 	   6,  -10, 	  -3,  -10
.2byte   -4,   -5, 	  -8,  -10, 	   7,  -11, 	  -4,   -8
.2byte   -2,   -5, 	  -8,  -14, 	   8,   -6, 	  -2,   -8
.2byte   -1,   -7, 	  -9,  -12, 	   9,  -12, 	  -1,  -10
.2byte   -2,   -6, 	 -12,   -9, 	   9,  -13, 	  -2,   -9
.2byte    1,   -6, 	  -9,  -13, 	  12,   -9, 	   1,   -9
.2byte   -1,  -10, 	 -10,   -5, 	   9,   -5, 	  -1,  -11
.2byte    2,   -7, 	   6,  -14, 	  -7,  -10, 	   2,  -10
.2byte    3,   -5, 	   7,  -10, 	  -8,  -11, 	   3,   -8
.2byte    1,   -5, 	   7,  -14, 	  -9,   -6, 	   1,   -8
.2byte    1,   -8, 	   6,   -6, 	 -10,   -1, 	  -1,   -9
.2byte    4,   -7, 	  -1,  -13, 	  -1,   -9, 	   1,   -8
.2byte    5,   -7, 	  -1,   -9, 	  -1,  -11, 	   2,   -8
.2byte    5,   -5, 	   0,  -15, 	   0,   -5, 	   2,   -7
.2byte    3,  -10, 	  -3,   -7, 	  -3,   -4, 	  -1,  -11
.2byte    2,   -9, 	  -7,  -14, 	   7,  -10, 	  -1,   -9
.2byte   -2,  -10, 	  -8,   -9, 	   8,  -11, 	  -2,   -8
.2byte    1,   -8, 	  -7,  -15, 	   8,   -7, 	  -1,   -8
.2byte    0,   -8, 	  -7,   -4, 	   8,   -3, 	  -2,   -8
.2byte   -2,  -10, 	   8,  -12, 	  -9,  -12, 	  -1,  -10
.2byte    2,  -10, 	  11,   -9, 	  -9,  -14, 	   1,  -10
.2byte   -3,  -10, 	   8,  -14, 	 -11,   -9, 	  -2,  -10
.2byte   -1,   -8, 	   8,   -4, 	  -9,   -4, 	  -1,   -7
.2byte   -3,   -9, 	   6,  -14, 	  -8,  -10, 	   0,   -9
.2byte    1,  -10, 	   7,   -9, 	  -9,  -11, 	   1,   -8
.2byte   -2,   -8, 	   6,  -15, 	  -9,   -7, 	   0,   -8
.2byte   -1,   -8, 	   6,   -4, 	  -9,   -3, 	   1,   -8
.2byte   -5,   -7, 	   0,  -13, 	   0,   -9, 	  -2,   -8
.2byte   -6,   -7, 	   0,   -9, 	   0,  -11, 	  -3,   -8
.2byte   -6,   -5, 	  -1,  -15, 	  -1,   -5, 	  -3,   -7
.2byte   -4,  -10, 	   2,   -7, 	   2,   -4, 	   0,  -11
.2byte   -3,   -7, 	  -7,  -14, 	   6,  -10, 	  -3,  -10
.2byte   -4,   -5, 	  -8,  -10, 	   7,  -11, 	  -4,   -8
.2byte   -2,   -5, 	  -8,  -14, 	   8,   -6, 	  -2,   -8
.2byte   -2,   -8, 	  -7,   -6, 	   9,   -1, 	   0,   -9
.2byte   -1,   -7, 	  -9,  -12, 	   9,  -12, 	  -1,  -10
.2byte   -2,   -6, 	 -12,   -9, 	   9,  -13, 	  -2,   -9
.2byte    1,   -6, 	  -9,  -13, 	  12,   -9, 	   1,   -9
.2byte   -1,  -10, 	 -10,   -5, 	   9,   -5, 	  -1,  -11
.2byte    2,   -7, 	   6,  -14, 	  -7,  -10, 	   2,  -10
.2byte    3,   -5, 	   7,  -10, 	  -8,  -11, 	   3,   -8
.2byte    1,   -5, 	   7,  -14, 	  -9,   -6, 	   1,   -8
.2byte    1,   -8, 	   6,   -6, 	 -10,   -1, 	  -1,   -9
.2byte    4,   -7, 	  -1,  -13, 	  -1,   -9, 	   1,   -8
.2byte    5,   -7, 	  -1,   -9, 	  -1,  -11, 	   2,   -8
.2byte    5,   -5, 	   0,  -15, 	   0,   -5, 	   2,   -7
.2byte    3,  -10, 	  -3,   -7, 	  -3,   -4, 	  -1,  -11
.2byte    2,   -9, 	  -7,  -14, 	   7,  -10, 	  -1,   -9
.2byte   -2,  -10, 	  -8,   -9, 	   8,  -11, 	  -2,   -8
.2byte    1,   -8, 	  -7,  -15, 	   8,   -7, 	  -1,   -8
.2byte    0,   -8, 	  -7,   -4, 	   8,   -3, 	  -2,   -8
.2byte   -2,  -10, 	   8,  -12, 	  -9,  -12, 	  -1,  -10
.2byte    2,  -10, 	  11,   -9, 	  -9,  -14, 	   1,  -10
.2byte   -3,  -10, 	   8,  -14, 	 -11,   -9, 	  -2,  -10
.2byte   -1,   -8, 	   8,   -4, 	  -9,   -4, 	  -1,   -7
.2byte   -3,   -9, 	   6,  -14, 	  -8,  -10, 	   0,   -9
.2byte    1,  -10, 	   7,   -9, 	  -9,  -11, 	   1,   -8
.2byte   -2,   -8, 	   6,  -15, 	  -9,   -7, 	   0,   -8
.2byte   -1,   -8, 	   6,   -4, 	  -9,   -3, 	   1,   -8
.2byte   -5,   -7, 	   0,  -13, 	   0,   -9, 	  -2,   -8
.2byte   -6,   -7, 	   0,   -9, 	   0,  -11, 	  -3,   -8
.2byte   -6,   -5, 	  -1,  -15, 	  -1,   -5, 	  -3,   -7
.2byte   -4,  -10, 	   2,   -7, 	   2,   -4, 	   0,  -11
.2byte   -3,   -7, 	  -7,  -14, 	   6,  -10, 	  -3,  -10
.2byte   -4,   -5, 	  -8,  -10, 	   7,  -11, 	  -4,   -8
.2byte   -2,   -5, 	  -8,  -14, 	   8,   -6, 	  -2,   -8
.2byte   -2,   -8, 	  -7,   -6, 	   9,   -1, 	   0,   -9
.2byte   -1,   -7, 	  -9,  -12, 	   9,  -12, 	  -1,  -10
.2byte   -2,   -6, 	 -12,   -9, 	   9,  -13, 	  -2,   -9
.2byte    1,   -6, 	  -9,  -13, 	  12,   -9, 	   1,   -9
.2byte   -1,  -10, 	 -10,   -5, 	   9,   -5, 	  -1,  -11
.2byte    2,   -7, 	   6,  -14, 	  -7,  -10, 	   2,  -10
.2byte    3,   -5, 	   7,  -10, 	  -8,  -11, 	   3,   -8
.2byte    1,   -5, 	   7,  -14, 	  -9,   -6, 	   1,   -8
.2byte    2,   -8, 	   7,   -6, 	  -9,   -1, 	   0,   -9
.2byte    4,   -7, 	  -1,  -13, 	  -1,   -9, 	   1,   -8
.2byte    5,   -7, 	  -1,   -9, 	  -1,  -11, 	   2,   -8
.2byte    5,   -5, 	   0,  -15, 	   0,   -5, 	   2,   -7
.2byte    3,  -10, 	  -3,   -7, 	  -3,   -4, 	  -1,  -11
.2byte    2,   -9, 	  -7,  -14, 	   7,  -10, 	  -1,   -9
.2byte   -2,  -10, 	  -8,   -9, 	   8,  -11, 	  -2,   -8
.2byte    1,   -8, 	  -7,  -15, 	   8,   -7, 	  -1,   -8
.2byte    0,   -8, 	  -7,   -4, 	   8,   -3, 	  -2,   -8
.2byte   -2,  -10, 	   8,  -12, 	  -9,  -12, 	  -1,  -10
.2byte    2,  -10, 	  11,   -9, 	  -9,  -14, 	   1,  -10
.2byte   -3,  -10, 	   8,  -14, 	 -11,   -9, 	  -2,  -10
.2byte   -1,   -8, 	   8,   -4, 	  -9,   -4, 	  -1,   -7
.2byte   -3,   -9, 	   6,  -14, 	  -8,  -10, 	   0,   -9
.2byte    1,  -10, 	   7,   -9, 	  -9,  -11, 	   1,   -8
.2byte   -2,   -8, 	   6,  -15, 	  -9,   -7, 	   0,   -8
.2byte   -1,   -8, 	   6,   -4, 	  -9,   -3, 	   1,   -8
.2byte   -5,   -7, 	   0,  -13, 	   0,   -9, 	  -2,   -8
.2byte   -6,   -7, 	   0,   -9, 	   0,  -11, 	  -3,   -8
.2byte   -6,   -5, 	  -1,  -15, 	  -1,   -5, 	  -3,   -7
.2byte   -4,  -10, 	   2,   -7, 	   2,   -4, 	   0,  -11
.2byte   -3,   -7, 	  -7,  -14, 	   6,  -10, 	  -3,  -10
.2byte   -4,   -5, 	  -8,  -10, 	   7,  -11, 	  -4,   -8
.2byte   -2,   -5, 	  -8,  -14, 	   8,   -6, 	  -2,   -8
.2byte   -3,   -8, 	  -8,   -6, 	   8,   -1, 	  -1,   -9
.2byte   -1,   -8, 	  -9,  -13, 	   9,  -13, 	  -1,  -11
.2byte   -2,   -8, 	 -12,  -11, 	   9,  -15, 	  -2,  -11
.2byte    1,   -8, 	  -9,  -15, 	  12,  -11, 	   1,  -11
.2byte    2,   -7, 	   6,  -14, 	  -7,  -10, 	   2,  -10
.2byte    3,   -6, 	   7,  -11, 	  -8,  -12, 	   3,   -9
.2byte    1,   -7, 	   7,  -16, 	  -9,   -8, 	   1,  -10
.2byte    4,   -7, 	  -1,  -13, 	  -1,   -9, 	   1,   -8
.2byte    5,   -8, 	  -1,  -10, 	  -1,  -12, 	   2,   -9
.2byte    5,   -6, 	   0,  -16, 	   0,   -6, 	   2,   -8
.2byte    2,  -10, 	  -7,  -15, 	   7,  -11, 	  -1,  -10
.2byte   -2,  -11, 	  -8,  -10, 	   8,  -12, 	  -2,   -9
.2byte    1,   -9, 	  -7,  -16, 	   8,   -8, 	  -1,   -9
.2byte   -2,  -11, 	   8,  -13, 	  -9,  -13, 	  -1,  -11
.2byte    2,  -11, 	  11,  -10, 	  -9,  -15, 	   1,  -11
.2byte   -3,  -11, 	   8,  -15, 	 -11,  -10, 	  -2,  -11
.2byte   -3,  -10, 	   6,  -15, 	  -8,  -11, 	   0,  -10
.2byte    1,  -11, 	   7,  -10, 	  -9,  -12, 	   1,   -9
.2byte   -2,   -9, 	   6,  -16, 	  -9,   -8, 	   0,   -9
.2byte   -5,   -7, 	   0,  -13, 	   0,   -9, 	  -2,   -8
.2byte   -6,   -8, 	   0,  -10, 	   0,  -12, 	  -3,   -9
.2byte   -6,   -6, 	  -1,  -16, 	  -1,   -6, 	  -3,   -8
.2byte   -3,   -7, 	  -7,  -14, 	   6,  -10, 	  -3,  -10
.2byte   -4,   -6, 	  -8,  -11, 	   7,  -12, 	  -4,   -9
.2byte   -2,   -7, 	  -8,  -16, 	   8,   -8, 	  -2,  -10
.2byte   -4,   -4, 	  -8,   -4, 	   8,    0, 	  -2,   -7
.2byte   -4,   -5, 	  -8,   -4, 	   8,    0, 	  -2,   -8
.2byte   -1,  -12, 	 -13,  -13, 	  11,  -13, 	  -1,  -14
.2byte   -2,  -10, 	   5,  -19, 	 -13,  -12, 	  -2,  -12
.2byte   -1,   -8, 	  -7,  -16, 	 -12,   -3, 	  -5,   -8
.2byte    2,   -5, 	  -7,  -14, 	   3,   -5, 	  -4,   -6
.2byte   -1,   -8, 	  10,   -7, 	 -11,   -7, 	  -1,   -6
.2byte   -3,   -5, 	   6,  -14, 	  -4,   -5, 	   3,   -6
.2byte    0,   -8, 	   6,  -16, 	  11,   -3, 	   4,   -8
.2byte    1,  -10, 	  -6,  -19, 	  12,  -12, 	   1,  -12
.2byte   -1,   -7, 	  -9,  -12, 	   9,  -12, 	  -1,  -10
.2byte   -1,  -10, 	 -10,   -5, 	   9,   -5, 	  -1,  -11
.2byte    2,   -7, 	   6,  -14, 	  -7,  -10, 	   2,  -10
.2byte    1,   -8, 	   6,   -6, 	 -10,   -1, 	  -1,   -9
.2byte    4,   -7, 	  -1,  -13, 	  -1,   -9, 	   1,   -8
.2byte    3,  -10, 	  -3,   -7, 	  -3,   -4, 	  -1,  -11
.2byte    2,   -9, 	  -7,  -14, 	   7,  -10, 	  -1,   -9
.2byte   -1,   -9, 	  -8,   -5, 	   7,   -4, 	  -3,   -9
.2byte   -2,  -10, 	   8,  -12, 	  -9,  -12, 	  -1,  -10
.2byte   -1,   -8, 	   8,   -4, 	  -9,   -4, 	  -1,   -7
.2byte   -3,   -9, 	   6,  -14, 	  -8,  -10, 	   0,   -9
.2byte    0,   -9, 	   7,   -5, 	  -8,   -4, 	   2,   -9
.2byte   -5,   -7, 	   0,  -13, 	   0,   -9, 	  -2,   -8
.2byte   -4,  -10, 	   2,   -7, 	   2,   -4, 	   0,  -11
.2byte   -3,   -7, 	  -7,  -14, 	   6,  -10, 	  -3,  -10
.2byte   -2,   -8, 	  -7,   -6, 	   9,   -1, 	   0,   -9
.2byte   -1,  -10, 	 -10,   -5, 	   9,   -5, 	  -1,  -11
.2byte   -3,   -8, 	  -8,   -6, 	   8,   -1, 	  -1,   -9
.2byte   -4,  -10, 	   2,   -7, 	   2,   -4, 	   0,  -11
.2byte   -1,   -8, 	   6,   -4, 	  -9,   -3, 	   1,   -8
.2byte   -1,   -8, 	   8,   -4, 	  -9,   -4, 	  -1,   -7
.2byte    0,   -8, 	  -7,   -4, 	   8,   -3, 	  -2,   -8
.2byte    3,  -10, 	  -3,   -7, 	  -3,   -4, 	  -1,  -11
.2byte    2,   -8, 	   7,   -6, 	  -9,   -1, 	   0,   -9
.2byte    2,   -8, 	   7,   -6, 	  -9,   -1, 	   0,   -9
.2byte    3,  -10, 	  -3,   -7, 	  -3,   -4, 	  -1,  -11
.2byte    2,   -8, 	   7,   -6, 	  -9,   -1, 	   0,   -9
.2byte    0,   -8, 	  -7,   -4, 	   8,   -3, 	  -2,   -8
.2byte    3,  -10, 	  -3,   -7, 	  -3,   -4, 	  -1,  -11
.2byte    2,   -8, 	   7,   -6, 	  -9,   -1, 	   0,   -9
.2byte   -1,   -8, 	   8,   -4, 	  -9,   -4, 	  -1,   -7
.2byte    0,   -8, 	  -7,   -4, 	   8,   -3, 	  -2,   -8
.2byte    3,  -10, 	  -3,   -7, 	  -3,   -4, 	  -1,  -11
.2byte    2,   -8, 	   7,   -6, 	  -9,   -1, 	   0,   -9
.2byte   -1,   -8, 	   6,   -4, 	  -9,   -3, 	   1,   -8
.2byte   -1,   -8, 	   8,   -4, 	  -9,   -4, 	  -1,   -7
.2byte    0,   -8, 	  -7,   -4, 	   8,   -3, 	  -2,   -8
.2byte    3,  -10, 	  -3,   -7, 	  -3,   -4, 	  -1,  -11
.2byte    2,   -8, 	   7,   -6, 	  -9,   -1, 	   0,   -9
.2byte   -4,  -10, 	   2,   -7, 	   2,   -4, 	   0,  -11
.2byte   -1,   -8, 	   6,   -4, 	  -9,   -3, 	   1,   -8
.2byte   -1,   -8, 	   8,   -4, 	  -9,   -4, 	  -1,   -7
.2byte    0,   -8, 	  -7,   -4, 	   8,   -3, 	  -2,   -8
.2byte    3,  -10, 	  -3,   -7, 	  -3,   -4, 	  -1,  -11
.2byte    2,   -8, 	   7,   -6, 	  -9,   -1, 	   0,   -9
.2byte   -3,   -8, 	  -8,   -6, 	   8,   -1, 	  -1,   -9
.2byte   -4,  -10, 	   2,   -7, 	   2,   -4, 	   0,  -11
.2byte   -1,   -8, 	   6,   -4, 	  -9,   -3, 	   1,   -8
.2byte   -1,   -8, 	   8,   -4, 	  -9,   -4, 	  -1,   -7
.2byte    0,   -8, 	  -7,   -4, 	   8,   -3, 	  -2,   -8
.2byte    3,  -10, 	  -3,   -7, 	  -3,   -4, 	  -1,  -11
.2byte    2,   -8, 	   7,   -6, 	  -9,   -1, 	   0,   -9
.2byte   -2,   -6, 	 -12,   -9, 	   9,  -13, 	  -2,   -9
.2byte    1,   -5, 	   7,  -14, 	  -9,   -6, 	   1,   -8
.2byte    5,   -7, 	  -1,   -9, 	  -1,  -11, 	   2,   -8
.2byte   -2,  -10, 	  -8,   -9, 	   8,  -11, 	  -2,   -8
.2byte    2,  -10, 	  11,   -9, 	  -9,  -14, 	   1,  -10
.2byte    1,  -10, 	   7,   -9, 	  -9,  -11, 	   1,   -8
.2byte   -6,   -7, 	   0,   -9, 	   0,  -11, 	  -3,   -8
.2byte   -4,   -5, 	  -8,  -10, 	   7,  -11, 	  -4,   -8
.2byte   -1,   -8, 	  -9,  -13, 	   9,  -13, 	  -1,  -11
.2byte   -1,   -6, 	 -11,   -9, 	  10,  -13, 	  -1,   -9
.2byte    0,   -6, 	 -10,  -13, 	  11,   -9, 	   0,   -9
.2byte    2,   -7, 	   6,  -14, 	  -7,  -10, 	   2,  -10
.2byte    2,   -5, 	   6,  -10, 	  -9,  -11, 	   2,   -8
.2byte    2,   -5, 	   8,  -14, 	  -8,   -6, 	   2,   -8
.2byte    4,   -7, 	  -1,  -13, 	  -1,   -9, 	   1,   -8
.2byte    5,   -7, 	  -1,   -9, 	  -1,  -11, 	   2,   -8
.2byte    4,   -5, 	  -1,  -15, 	  -1,   -5, 	   1,   -7
.2byte    2,  -10, 	  -7,  -15, 	   7,  -11, 	  -1,  -10
.2byte   -2,  -10, 	  -8,   -9, 	   8,  -11, 	  -2,   -8
.2byte    1,   -8, 	  -7,  -15, 	   8,   -7, 	  -1,   -8
.2byte   -2,  -11, 	   8,  -13, 	  -9,  -13, 	  -1,  -11
.2byte    1,  -10, 	  10,   -9, 	 -10,  -14, 	   0,  -10
.2byte   -2,  -10, 	   9,  -14, 	 -10,   -9, 	  -1,  -10
.2byte   -3,  -10, 	   6,  -15, 	  -8,  -11, 	   0,  -10
.2byte    1,  -10, 	   7,   -9, 	  -9,  -11, 	   1,   -8
.2byte   -2,   -8, 	   6,  -15, 	  -9,   -7, 	   0,   -8
.2byte   -5,   -7, 	   0,  -13, 	   0,   -9, 	  -2,   -8
.2byte   -6,   -7, 	   0,   -9, 	   0,  -11, 	  -3,   -8
.2byte   -5,   -5, 	   0,  -15, 	   0,   -5, 	  -2,   -7
.2byte   -3,   -7, 	  -7,  -14, 	   6,  -10, 	  -3,  -10
.2byte   -3,   -5, 	  -7,  -10, 	   8,  -11, 	  -3,   -8
.2byte   -3,   -5, 	  -9,  -14, 	   7,   -6, 	  -3,   -8
.2byte   -1,   -8, 	  -9,  -13, 	   9,  -13, 	  -1,  -11
.2byte   -3,   -7, 	  -7,  -14, 	   6,  -10, 	  -3,  -10
.2byte   -5,   -7, 	   0,  -13, 	   0,   -9, 	  -2,   -8
.2byte   -3,  -10, 	   6,  -15, 	  -8,  -11, 	   0,  -10
.2byte   -2,  -11, 	   8,  -13, 	  -9,  -13, 	  -1,  -11
.2byte    2,  -10, 	  -7,  -15, 	   7,  -11, 	  -1,  -10
.2byte    4,   -7, 	  -1,  -13, 	  -1,   -9, 	   1,   -8
.2byte    2,   -7, 	   6,  -14, 	  -7,  -10, 	   2,  -10
.2byte    2,   -7, 	   6,  -14, 	  -7,  -10, 	   2,  -10
.2byte    4,   -7, 	  -1,  -13, 	  -1,   -9, 	   1,   -8
.2byte    2,   -7, 	   6,  -14, 	  -7,  -10, 	   2,  -10
.2byte    2,  -10, 	  -7,  -15, 	   7,  -11, 	  -1,  -10
.2byte    4,   -7, 	  -1,  -13, 	  -1,   -9, 	   1,   -8
.2byte    2,   -7, 	   6,  -14, 	  -7,  -10, 	   2,  -10
.2byte   -2,  -11, 	   8,  -13, 	  -9,  -13, 	  -1,  -11
.2byte    2,  -10, 	  -7,  -15, 	   7,  -11, 	  -1,  -10
.2byte    4,   -7, 	  -1,  -13, 	  -1,   -9, 	   1,   -8
.2byte    2,   -7, 	   6,  -14, 	  -7,  -10, 	   2,  -10
.2byte   -3,  -10, 	   6,  -15, 	  -8,  -11, 	   0,  -10
.2byte   -2,  -11, 	   8,  -13, 	  -9,  -13, 	  -1,  -11
.2byte    2,  -10, 	  -7,  -15, 	   7,  -11, 	  -1,  -10
.2byte    4,   -7, 	  -1,  -13, 	  -1,   -9, 	   1,   -8
.2byte    2,   -7, 	   6,  -14, 	  -7,  -10, 	   2,  -10
.2byte   -5,   -7, 	   0,  -13, 	   0,   -9, 	  -2,   -8
.2byte   -3,  -10, 	   6,  -15, 	  -8,  -11, 	   0,  -10
.2byte   -2,  -11, 	   8,  -13, 	  -9,  -13, 	  -1,  -11
.2byte    2,  -10, 	  -7,  -15, 	   7,  -11, 	  -1,  -10
.2byte    4,   -7, 	  -1,  -13, 	  -1,   -9, 	   1,   -8
.2byte    2,   -7, 	   6,  -14, 	  -7,  -10, 	   2,  -10
.2byte   -3,   -7, 	  -7,  -14, 	   6,  -10, 	  -3,  -10
.2byte   -5,   -7, 	   0,  -13, 	   0,   -9, 	  -2,   -8
.2byte   -3,  -10, 	   6,  -15, 	  -8,  -11, 	   0,  -10
.2byte   -2,  -11, 	   8,  -13, 	  -9,  -13, 	  -1,  -11
.2byte    2,  -10, 	  -7,  -15, 	   7,  -11, 	  -1,  -10
.2byte    4,   -7, 	  -1,  -13, 	  -1,   -9, 	   1,   -8
.2byte    2,   -7, 	   6,  -14, 	  -7,  -10, 	   2,  -10
.2byte   -1,   -7, 	  -9,  -12, 	   9,  -12, 	  -1,  -10
.2byte   -3,   -7, 	  -7,  -14, 	   6,  -10, 	  -3,  -10
.2byte   -5,   -7, 	   0,  -13, 	   0,   -9, 	  -2,   -8
.2byte   -3,   -9, 	   6,  -14, 	  -8,  -10, 	   0,   -9
.2byte   -2,  -10, 	   8,  -12, 	  -9,  -12, 	  -1,  -10
.2byte    2,   -9, 	  -7,  -14, 	   7,  -10, 	  -1,   -9
.2byte    4,   -7, 	  -1,  -13, 	  -1,   -9, 	   1,   -8
.2byte    2,   -7, 	   6,  -14, 	  -7,  -10, 	   2,  -10
sLoudredAnimTable1:
.4byte sLoudredAnims_1_1
.4byte sLoudredAnims_1_2
.4byte sLoudredAnims_1_3
.4byte sLoudredAnims_1_4
.4byte sLoudredAnims_1_5
.4byte sLoudredAnims_1_6
.4byte sLoudredAnims_1_7
.4byte sLoudredAnims_1_8
sLoudredAnimTable2:
.4byte sLoudredAnims_2_1
.4byte sLoudredAnims_2_2
.4byte sLoudredAnims_2_3
.4byte sLoudredAnims_2_4
.4byte sLoudredAnims_2_5
.4byte sLoudredAnims_2_6
.4byte sLoudredAnims_2_7
.4byte sLoudredAnims_2_8
sLoudredAnimTable3:
.4byte sLoudredAnims_3_1
.4byte sLoudredAnims_3_2
.4byte sLoudredAnims_3_3
.4byte sLoudredAnims_3_4
.4byte sLoudredAnims_3_5
.4byte sLoudredAnims_3_6
.4byte sLoudredAnims_3_7
.4byte sLoudredAnims_3_8
sLoudredAnimTable4:
.4byte sLoudredAnims_4_1
.4byte sLoudredAnims_4_2
.4byte sLoudredAnims_4_3
.4byte sLoudredAnims_4_4
.4byte sLoudredAnims_4_5
.4byte sLoudredAnims_4_6
.4byte sLoudredAnims_4_7
.4byte sLoudredAnims_4_8
sLoudredAnimTable5:
.4byte sLoudredAnims_5_1
.4byte sLoudredAnims_5_2
.4byte sLoudredAnims_5_3
.4byte sLoudredAnims_5_4
.4byte sLoudredAnims_5_5
.4byte sLoudredAnims_5_6
.4byte sLoudredAnims_5_7
.4byte sLoudredAnims_5_8
sLoudredAnimTable6:
.4byte sLoudredAnims_6_1
.4byte sLoudredAnims_6_1
.4byte sLoudredAnims_6_1
.4byte sLoudredAnims_6_1
.4byte sLoudredAnims_6_1
.4byte sLoudredAnims_6_1
.4byte sLoudredAnims_6_1
.4byte sLoudredAnims_6_1
sLoudredAnimTable7:
.4byte sLoudredAnims_7_1
.4byte sLoudredAnims_7_2
.4byte sLoudredAnims_7_3
.4byte sLoudredAnims_7_4
.4byte sLoudredAnims_7_5
.4byte sLoudredAnims_7_6
.4byte sLoudredAnims_7_7
.4byte sLoudredAnims_7_8
sLoudredAnimTable8:
.4byte sLoudredAnims_8_1
.4byte sLoudredAnims_8_2
.4byte sLoudredAnims_8_3
.4byte sLoudredAnims_8_4
.4byte sLoudredAnims_8_5
.4byte sLoudredAnims_8_6
.4byte sLoudredAnims_8_7
.4byte sLoudredAnims_8_8
sLoudredAnimTable9:
.4byte sLoudredAnims_9_1
.4byte sLoudredAnims_9_2
.4byte sLoudredAnims_9_3
.4byte sLoudredAnims_9_4
.4byte sLoudredAnims_9_5
.4byte sLoudredAnims_9_6
.4byte sLoudredAnims_9_7
.4byte sLoudredAnims_9_8
sLoudredAnimTable10:
.4byte sLoudredAnims_10_1
.4byte sLoudredAnims_10_2
.4byte sLoudredAnims_10_3
.4byte sLoudredAnims_10_4
.4byte sLoudredAnims_10_5
.4byte sLoudredAnims_10_6
.4byte sLoudredAnims_10_7
.4byte sLoudredAnims_10_8
sLoudredAnimTable11:
.4byte sLoudredAnims_11_1
.4byte sLoudredAnims_11_2
.4byte sLoudredAnims_11_3
.4byte sLoudredAnims_11_4
.4byte sLoudredAnims_11_5
.4byte sLoudredAnims_11_6
.4byte sLoudredAnims_11_7
.4byte sLoudredAnims_11_8
sLoudredAnimTable12:
.4byte sLoudredAnims_12_1
.4byte sLoudredAnims_12_2
.4byte sLoudredAnims_12_3
.4byte sLoudredAnims_12_4
.4byte sLoudredAnims_12_5
.4byte sLoudredAnims_12_6
.4byte sLoudredAnims_12_7
.4byte sLoudredAnims_12_8
sLoudredAnimTable13:
.4byte sLoudredAnims_13_1
.4byte sLoudredAnims_13_2
.4byte sLoudredAnims_13_3
.4byte sLoudredAnims_13_4
.4byte sLoudredAnims_13_5
.4byte sLoudredAnims_13_6
.4byte sLoudredAnims_13_7
.4byte sLoudredAnims_13_8
sAxAnimationsLoudred:
.4byte sLoudredAnimTable1
.4byte sLoudredAnimTable2
.4byte sLoudredAnimTable3
.4byte sLoudredAnimTable4
.4byte sLoudredAnimTable5
.4byte sLoudredAnimTable6
.4byte sLoudredAnimTable7
.4byte sLoudredAnimTable8
.4byte sLoudredAnimTable9
.4byte sLoudredAnimTable10
.4byte sLoudredAnimTable11
.4byte sLoudredAnimTable12
.4byte sLoudredAnimTable13
sAxSpritesLoudred:
.4byte sLoudredSprites1
.4byte sLoudredSprites2
.4byte sLoudredSprites3
.4byte sLoudredSprites4
.4byte sLoudredSprites5
.4byte sLoudredSprites6
.4byte sLoudredSprites7
.4byte sLoudredSprites8
.4byte sLoudredSprites9
.4byte sLoudredSprites10
.4byte sLoudredSprites11
.4byte sLoudredSprites12
.4byte sLoudredSprites13
.4byte sLoudredSprites14
.4byte sLoudredSprites15
.4byte sLoudredSprites16
.4byte sLoudredSprites17
.4byte sLoudredSprites18
.4byte sLoudredSprites19
.4byte sLoudredSprites20
.4byte sLoudredSprites21
.4byte sLoudredSprites22
.4byte sLoudredSprites23
.4byte sLoudredSprites24
.4byte sLoudredSprites25
.4byte sLoudredSprites26
.4byte sLoudredSprites27
.4byte sLoudredSprites28
.4byte sLoudredSprites29
.4byte sLoudredSprites30
.4byte sLoudredSprites31
.4byte sLoudredSprites32
.4byte sLoudredSprites33
sAxMainLoudred:
ax_main sAxPosesLoudred, sAxAnimationsLoudred, 13, sAxSpritesLoudred, sAxPositionsLoudred
