.global gAxLuvdisc
gAxLuvdisc:
ax_siro sAxMainLuvdisc
sLuvdiscPose1:
ax_pose 0, 0x81e7, 0x80f8, 0xac00
ax_pose_terminator
sLuvdiscPose2:
ax_pose 1, 0x81e7, 0x80f8, 0xac00
ax_pose_terminator
sLuvdiscPose3:
ax_pose 2, 0x81e7, 0x80f8, 0xac00
ax_pose_terminator
sLuvdiscPose4:
ax_pose 3, 0x81e7, 0x90f8, 0xac00
ax_pose_terminator
sLuvdiscPose5:
ax_pose 4, 0x81e7, 0x90f8, 0xac00
ax_pose_terminator
sLuvdiscPose6:
ax_pose 5, 0x81e7, 0x90f9, 0xac00
ax_pose_terminator
sLuvdiscPose7:
ax_pose 6, 0x01e7, 0x90f0, 0xac00
ax_pose_terminator
sLuvdiscPose8:
ax_pose 7, 0x01e7, 0x90f1, 0xac00
ax_pose_terminator
sLuvdiscPose9:
ax_pose 8, 0x01e7, 0x90f0, 0xac00
ax_pose_terminator
sLuvdiscPose10:
ax_pose 9, 0x81e7, 0x90f8, 0xac00
ax_pose_terminator
sLuvdiscPose11:
ax_pose 10, 0x81e7, 0x90f8, 0xac00
ax_pose_terminator
sLuvdiscPose12:
ax_pose 11, 0x81e7, 0x90f8, 0xac00
ax_pose_terminator
sLuvdiscPose13:
ax_pose 12, 0x81e7, 0x80f8, 0xac00
ax_pose_terminator
sLuvdiscPose14:
ax_pose 13, 0x81e7, 0x80f8, 0xac00
ax_pose_terminator
sLuvdiscPose15:
ax_pose 14, 0x81e7, 0x80f8, 0xac00
ax_pose_terminator
sLuvdiscPose16:
ax_pose 9, 0x81e7, 0x80f8, 0xac00
ax_pose_terminator
sLuvdiscPose17:
ax_pose 10, 0x81e7, 0x80f8, 0xac00
ax_pose_terminator
sLuvdiscPose18:
ax_pose 11, 0x81e7, 0x80f8, 0xac00
ax_pose_terminator
sLuvdiscPose19:
ax_pose 6, 0x01e7, 0x80f0, 0xac00
ax_pose_terminator
sLuvdiscPose20:
ax_pose 7, 0x01e7, 0x80ef, 0xac00
ax_pose_terminator
sLuvdiscPose21:
ax_pose 8, 0x01e7, 0x80f0, 0xac00
ax_pose_terminator
sLuvdiscPose22:
ax_pose 3, 0x81e7, 0x80f8, 0xac00
ax_pose_terminator
sLuvdiscPose23:
ax_pose 4, 0x81e7, 0x80f8, 0xac00
ax_pose_terminator
sLuvdiscPose24:
ax_pose 5, 0x81e7, 0x80f7, 0xac00
ax_pose_terminator
sLuvdiscPose25:
ax_pose 0, 0x81e7, 0x80f8, 0xac00
ax_pose_terminator
sLuvdiscPose26:
ax_pose 1, 0x81e7, 0x80f8, 0xac00
ax_pose_terminator
sLuvdiscPose27:
ax_pose 2, 0x81e7, 0x80f8, 0xac00
ax_pose_terminator
sLuvdiscPose28:
ax_pose 3, 0x81e7, 0x90f8, 0xac00
ax_pose_terminator
sLuvdiscPose29:
ax_pose 4, 0x81e7, 0x90f8, 0xac00
ax_pose_terminator
sLuvdiscPose30:
ax_pose 5, 0x81e7, 0x90f9, 0xac00
ax_pose_terminator
sLuvdiscPose31:
ax_pose 6, 0x01e7, 0x90f0, 0xac00
ax_pose_terminator
sLuvdiscPose32:
ax_pose 7, 0x01e7, 0x90f1, 0xac00
ax_pose_terminator
sLuvdiscPose33:
ax_pose 8, 0x01e7, 0x90f0, 0xac00
ax_pose_terminator
sLuvdiscPose34:
ax_pose 9, 0x81e7, 0x90f8, 0xac00
ax_pose_terminator
sLuvdiscPose35:
ax_pose 10, 0x81e7, 0x90f8, 0xac00
ax_pose_terminator
sLuvdiscPose36:
ax_pose 11, 0x81e7, 0x90f8, 0xac00
ax_pose_terminator
sLuvdiscPose37:
ax_pose 12, 0x81e7, 0x80f8, 0xac00
ax_pose_terminator
sLuvdiscPose38:
ax_pose 13, 0x81e7, 0x80f8, 0xac00
ax_pose_terminator
sLuvdiscPose39:
ax_pose 14, 0x81e7, 0x80f8, 0xac00
ax_pose_terminator
sLuvdiscPose40:
ax_pose 9, 0x81e7, 0x80f8, 0xac00
ax_pose_terminator
sLuvdiscPose41:
ax_pose 10, 0x81e7, 0x80f8, 0xac00
ax_pose_terminator
sLuvdiscPose42:
ax_pose 11, 0x81e7, 0x80f8, 0xac00
ax_pose_terminator
sLuvdiscPose43:
ax_pose 6, 0x01e7, 0x80f0, 0xac00
ax_pose_terminator
sLuvdiscPose44:
ax_pose 7, 0x01e7, 0x80ef, 0xac00
ax_pose_terminator
sLuvdiscPose45:
ax_pose 8, 0x01e7, 0x80f0, 0xac00
ax_pose_terminator
sLuvdiscPose46:
ax_pose 3, 0x81e7, 0x80f8, 0xac00
ax_pose_terminator
sLuvdiscPose47:
ax_pose 4, 0x81e7, 0x80f8, 0xac00
ax_pose_terminator
sLuvdiscPose48:
ax_pose 5, 0x81e7, 0x80f7, 0xac00
ax_pose_terminator
sLuvdiscPose49:
ax_pose 0, 0x81e7, 0x80f8, 0xac00
ax_pose_terminator
sLuvdiscPose50:
ax_pose 1, 0x81e7, 0x80f8, 0xac00
ax_pose_terminator
sLuvdiscPose51:
ax_pose 2, 0x81e7, 0x80f8, 0xac00
ax_pose_terminator
sLuvdiscPose52:
ax_pose 3, 0x81e7, 0x90f8, 0xac00
ax_pose_terminator
sLuvdiscPose53:
ax_pose 4, 0x81e7, 0x90f8, 0xac00
ax_pose_terminator
sLuvdiscPose54:
ax_pose 5, 0x81e7, 0x90f9, 0xac00
ax_pose_terminator
sLuvdiscPose55:
ax_pose 6, 0x01e7, 0x90f0, 0xac00
ax_pose_terminator
sLuvdiscPose56:
ax_pose 7, 0x01e7, 0x90f1, 0xac00
ax_pose_terminator
sLuvdiscPose57:
ax_pose 8, 0x01e7, 0x90f0, 0xac00
ax_pose_terminator
sLuvdiscPose58:
ax_pose 9, 0x81e7, 0x90f8, 0xac00
ax_pose_terminator
sLuvdiscPose59:
ax_pose 10, 0x81e7, 0x90f8, 0xac00
ax_pose_terminator
sLuvdiscPose60:
ax_pose 11, 0x81e7, 0x90f8, 0xac00
ax_pose_terminator
sLuvdiscPose61:
ax_pose 12, 0x81e7, 0x80f8, 0xac00
ax_pose_terminator
sLuvdiscPose62:
ax_pose 13, 0x81e7, 0x80f8, 0xac00
ax_pose_terminator
sLuvdiscPose63:
ax_pose 14, 0x81e7, 0x80f8, 0xac00
ax_pose_terminator
sLuvdiscPose64:
ax_pose 9, 0x81e7, 0x80f8, 0xac00
ax_pose_terminator
sLuvdiscPose65:
ax_pose 10, 0x81e7, 0x80f8, 0xac00
ax_pose_terminator
sLuvdiscPose66:
ax_pose 11, 0x81e7, 0x80f8, 0xac00
ax_pose_terminator
sLuvdiscPose67:
ax_pose 6, 0x01e7, 0x80f0, 0xac00
ax_pose_terminator
sLuvdiscPose68:
ax_pose 7, 0x01e7, 0x80ef, 0xac00
ax_pose_terminator
sLuvdiscPose69:
ax_pose 8, 0x01e7, 0x80f0, 0xac00
ax_pose_terminator
sLuvdiscPose70:
ax_pose 3, 0x81e7, 0x80f8, 0xac00
ax_pose_terminator
sLuvdiscPose71:
ax_pose 4, 0x81e7, 0x80f8, 0xac00
ax_pose_terminator
sLuvdiscPose72:
ax_pose 5, 0x81e7, 0x80f7, 0xac00
ax_pose_terminator
sLuvdiscPose73:
ax_pose 0, 0x81e7, 0x80f8, 0xac00
ax_pose_terminator
sLuvdiscPose74:
ax_pose 15, 0x81e7, 0x80f8, 0xac00
ax_pose_terminator
sLuvdiscPose75:
ax_pose 16, 0x81e7, 0x80f8, 0xac00
ax_pose_terminator
sLuvdiscPose76:
ax_pose 3, 0x81e7, 0x90f8, 0xac00
ax_pose_terminator
sLuvdiscPose77:
ax_pose 17, 0x81e7, 0x90f8, 0xac00
ax_pose_terminator
sLuvdiscPose78:
ax_pose 18, 0x01ed, 0x50f9, 0xac00
ax_pose 19, 0x01e5, 0x10f9, 0xac04
ax_pose_terminator
sLuvdiscPose79:
ax_pose 6, 0x01e7, 0x90f0, 0xac00
ax_pose_terminator
sLuvdiscPose80:
ax_pose 20, 0x81e7, 0x90f7, 0xac00
ax_pose 21, 0x01ef, 0x10ef, 0xac08
ax_pose_terminator
sLuvdiscPose81:
ax_pose 22, 0x81e8, 0x90f8, 0xac00
ax_pose 23, 0x01f0, 0x1108, 0xac08
ax_pose_terminator
sLuvdiscPose82:
ax_pose 9, 0x81e7, 0x90f8, 0xac00
ax_pose_terminator
sLuvdiscPose83:
ax_pose 24, 0x81e9, 0x90f8, 0xac00
ax_pose_terminator
sLuvdiscPose84:
ax_pose 25, 0x01eb, 0x50f9, 0xac00
ax_pose 26, 0x01fb, 0x10f9, 0xac04
ax_pose_terminator
sLuvdiscPose85:
ax_pose 12, 0x81e7, 0x80f8, 0xac00
ax_pose_terminator
sLuvdiscPose86:
ax_pose 27, 0x81e8, 0x80f8, 0xac00
ax_pose_terminator
sLuvdiscPose87:
ax_pose 28, 0x81e7, 0x80f8, 0xac00
ax_pose_terminator
sLuvdiscPose88:
ax_pose 9, 0x81e7, 0x80f8, 0xac00
ax_pose_terminator
sLuvdiscPose89:
ax_pose 24, 0x81e9, 0x80f8, 0xac00
ax_pose_terminator
sLuvdiscPose90:
ax_pose 25, 0x01eb, 0x40f7, 0xac00
ax_pose 26, 0x01fb, 0x00ff, 0xac04
ax_pose_terminator
sLuvdiscPose91:
ax_pose 6, 0x01e7, 0x80f0, 0xac00
ax_pose_terminator
sLuvdiscPose92:
ax_pose 20, 0x81e7, 0x80f9, 0xac00
ax_pose 21, 0x01ef, 0x0109, 0xac08
ax_pose_terminator
sLuvdiscPose93:
ax_pose 22, 0x81e8, 0x80f8, 0xac00
ax_pose 23, 0x01f0, 0x00f0, 0xac08
ax_pose_terminator
sLuvdiscPose94:
ax_pose 3, 0x81e7, 0x80f8, 0xac00
ax_pose_terminator
sLuvdiscPose95:
ax_pose 17, 0x81e7, 0x80f8, 0xac00
ax_pose_terminator
sLuvdiscPose96:
ax_pose 18, 0x01ed, 0x40f7, 0xac00
ax_pose 19, 0x01e5, 0x00ff, 0xac04
ax_pose_terminator
sLuvdiscPose97:
ax_pose 0, 0x81e7, 0x80f8, 0xac00
ax_pose_terminator
sLuvdiscPose98:
ax_pose 3, 0x81e7, 0x80f8, 0xac00
ax_pose_terminator
sLuvdiscPose99:
ax_pose 6, 0x01e7, 0x80f0, 0xac00
ax_pose_terminator
sLuvdiscPose100:
ax_pose 9, 0x81e7, 0x80f8, 0xac00
ax_pose_terminator
sLuvdiscPose101:
ax_pose 12, 0x81e7, 0x80f8, 0xac00
ax_pose_terminator
sLuvdiscPose102:
ax_pose 9, 0x81e7, 0x90f8, 0xac00
ax_pose_terminator
sLuvdiscPose103:
ax_pose 6, 0x01e7, 0x90f0, 0xac00
ax_pose_terminator
sLuvdiscPose104:
ax_pose 3, 0x81e7, 0x90f8, 0xac00
ax_pose_terminator
sLuvdiscPose105:
ax_pose 29, 0x41ef, 0x80f1, 0xac00
ax_pose_terminator
sLuvdiscPose106:
ax_pose 30, 0x41ee, 0x80f1, 0xac00
ax_pose_terminator
sLuvdiscPose107:
ax_pose 31, 0x01e0, 0x80ef, 0xac00
ax_pose_terminator
sLuvdiscPose108:
ax_pose 32, 0x01e4, 0x90ea, 0xac00
ax_pose_terminator
sLuvdiscPose109:
ax_pose 33, 0x01e2, 0x90ee, 0xac00
ax_pose_terminator
sLuvdiscPose110:
ax_pose 34, 0x01e3, 0x90ef, 0xac00
ax_pose_terminator
sLuvdiscPose111:
ax_pose 35, 0x01e3, 0x80f5, 0xac00
ax_pose_terminator
sLuvdiscPose112:
ax_pose 34, 0x01e3, 0x80f1, 0xac00
ax_pose_terminator
sLuvdiscPose113:
ax_pose 33, 0x01e2, 0x80f2, 0xac00
ax_pose_terminator
sLuvdiscPose114:
ax_pose 32, 0x01e4, 0x80f6, 0xac00
ax_pose_terminator
sLuvdiscPose115:
ax_pose 0, 0x81e7, 0x80f8, 0xac00
ax_pose_terminator
sLuvdiscPose116:
ax_pose 1, 0x81e7, 0x80f8, 0xac00
ax_pose_terminator
sLuvdiscPose117:
ax_pose 2, 0x81e7, 0x80f8, 0xac00
ax_pose_terminator
sLuvdiscPose118:
ax_pose 3, 0x81e7, 0x90f8, 0xac00
ax_pose_terminator
sLuvdiscPose119:
ax_pose 4, 0x81e7, 0x90f8, 0xac00
ax_pose_terminator
sLuvdiscPose120:
ax_pose 5, 0x81e7, 0x90f9, 0xac00
ax_pose_terminator
sLuvdiscPose121:
ax_pose 6, 0x01e7, 0x90f0, 0xac00
ax_pose_terminator
sLuvdiscPose122:
ax_pose 7, 0x01e7, 0x90f1, 0xac00
ax_pose_terminator
sLuvdiscPose123:
ax_pose 8, 0x01e7, 0x90f0, 0xac00
ax_pose_terminator
sLuvdiscPose124:
ax_pose 9, 0x81e7, 0x90f8, 0xac00
ax_pose_terminator
sLuvdiscPose125:
ax_pose 10, 0x81e7, 0x90f8, 0xac00
ax_pose_terminator
sLuvdiscPose126:
ax_pose 11, 0x81e7, 0x90f8, 0xac00
ax_pose_terminator
sLuvdiscPose127:
ax_pose 12, 0x81e7, 0x80f8, 0xac00
ax_pose_terminator
sLuvdiscPose128:
ax_pose 13, 0x81e7, 0x80f8, 0xac00
ax_pose_terminator
sLuvdiscPose129:
ax_pose 14, 0x81e7, 0x80f8, 0xac00
ax_pose_terminator
sLuvdiscPose130:
ax_pose 9, 0x81e7, 0x80f8, 0xac00
ax_pose_terminator
sLuvdiscPose131:
ax_pose 10, 0x81e7, 0x80f8, 0xac00
ax_pose_terminator
sLuvdiscPose132:
ax_pose 11, 0x81e7, 0x80f8, 0xac00
ax_pose_terminator
sLuvdiscPose133:
ax_pose 6, 0x01e7, 0x80f0, 0xac00
ax_pose_terminator
sLuvdiscPose134:
ax_pose 7, 0x01e7, 0x80ef, 0xac00
ax_pose_terminator
sLuvdiscPose135:
ax_pose 8, 0x01e7, 0x80f0, 0xac00
ax_pose_terminator
sLuvdiscPose136:
ax_pose 3, 0x81e7, 0x80f8, 0xac00
ax_pose_terminator
sLuvdiscPose137:
ax_pose 4, 0x81e7, 0x80f8, 0xac00
ax_pose_terminator
sLuvdiscPose138:
ax_pose 5, 0x81e7, 0x80f7, 0xac00
ax_pose_terminator
sLuvdiscPose139:
ax_pose 16, 0x81e7, 0x80f8, 0xac00
ax_pose_terminator
sLuvdiscPose140:
ax_pose 18, 0x01ec, 0x40f7, 0xac00
ax_pose 19, 0x01e4, 0x00ff, 0xac04
ax_pose_terminator
sLuvdiscPose141:
ax_pose 22, 0x81e8, 0x80f8, 0xac00
ax_pose 23, 0x01f0, 0x00f0, 0xac08
ax_pose_terminator
sLuvdiscPose142:
ax_pose 25, 0x01eb, 0x40f7, 0xac00
ax_pose 26, 0x01fb, 0x00ff, 0xac04
ax_pose_terminator
sLuvdiscPose143:
ax_pose 28, 0x81e8, 0x80f8, 0xac00
ax_pose_terminator
sLuvdiscPose144:
ax_pose 25, 0x01eb, 0x50f9, 0xac00
ax_pose 26, 0x01fb, 0x10f9, 0xac04
ax_pose_terminator
sLuvdiscPose145:
ax_pose 22, 0x81e8, 0x90f8, 0xac00
ax_pose 23, 0x01f0, 0x1108, 0xac08
ax_pose_terminator
sLuvdiscPose146:
ax_pose 18, 0x01ec, 0x50f9, 0xac00
ax_pose 19, 0x01e4, 0x10f9, 0xac04
ax_pose_terminator
sLuvdiscPose147:
ax_pose 15, 0x81e7, 0x80f8, 0xac00
ax_pose_terminator
sLuvdiscPose148:
ax_pose 17, 0x81e7, 0x90f9, 0xac00
ax_pose_terminator
sLuvdiscPose149:
ax_pose 20, 0x81e7, 0x90f8, 0xac00
ax_pose 21, 0x01ef, 0x10f0, 0xac08
ax_pose_terminator
sLuvdiscPose150:
ax_pose 24, 0x81e8, 0x90f9, 0xac00
ax_pose_terminator
sLuvdiscPose151:
ax_pose 27, 0x81e9, 0x80f8, 0xac00
ax_pose_terminator
sLuvdiscPose152:
ax_pose 24, 0x81e8, 0x80f7, 0xac00
ax_pose_terminator
sLuvdiscPose153:
ax_pose 20, 0x81e7, 0x80f8, 0xac00
ax_pose 21, 0x01ef, 0x0108, 0xac08
ax_pose_terminator
sLuvdiscPose154:
ax_pose 17, 0x81e7, 0x80f7, 0xac00
ax_pose_terminator
sLuvdiscPose155:
ax_pose 0, 0x81e7, 0x80f8, 0xac00
ax_pose_terminator
sLuvdiscPose156:
ax_pose 15, 0x81e7, 0x80f8, 0xac00
ax_pose_terminator
sLuvdiscPose157:
ax_pose 16, 0x81e7, 0x80f8, 0xac00
ax_pose_terminator
sLuvdiscPose158:
ax_pose 3, 0x81e7, 0x90f8, 0xac00
ax_pose_terminator
sLuvdiscPose159:
ax_pose 17, 0x81e9, 0x90f9, 0xac00
ax_pose_terminator
sLuvdiscPose160:
ax_pose 18, 0x01ed, 0x50f9, 0xac00
ax_pose 19, 0x01e5, 0x10f9, 0xac04
ax_pose_terminator
sLuvdiscPose161:
ax_pose 6, 0x01e7, 0x90f0, 0xac00
ax_pose_terminator
sLuvdiscPose162:
ax_pose 20, 0x81e7, 0x90f8, 0xac00
ax_pose 21, 0x01ef, 0x10f0, 0xac08
ax_pose_terminator
sLuvdiscPose163:
ax_pose 22, 0x81e8, 0x90f8, 0xac00
ax_pose 23, 0x01f0, 0x1108, 0xac08
ax_pose_terminator
sLuvdiscPose164:
ax_pose 9, 0x81e7, 0x90f8, 0xac00
ax_pose_terminator
sLuvdiscPose165:
ax_pose 24, 0x81e9, 0x90f8, 0xac00
ax_pose_terminator
sLuvdiscPose166:
ax_pose 25, 0x01eb, 0x50fa, 0xac00
ax_pose 26, 0x01fb, 0x10fa, 0xac04
ax_pose_terminator
sLuvdiscPose167:
ax_pose 12, 0x81e7, 0x80f8, 0xac00
ax_pose_terminator
sLuvdiscPose168:
ax_pose 27, 0x81e8, 0x80f8, 0xac00
ax_pose_terminator
sLuvdiscPose169:
ax_pose 28, 0x81e7, 0x80f8, 0xac00
ax_pose_terminator
sLuvdiscPose170:
ax_pose 9, 0x81e7, 0x80f8, 0xac00
ax_pose_terminator
sLuvdiscPose171:
ax_pose 24, 0x81e9, 0x80f8, 0xac00
ax_pose_terminator
sLuvdiscPose172:
ax_pose 25, 0x01eb, 0x40f6, 0xac00
ax_pose 26, 0x01fb, 0x00fe, 0xac04
ax_pose_terminator
sLuvdiscPose173:
ax_pose 6, 0x01e7, 0x80f0, 0xac00
ax_pose_terminator
sLuvdiscPose174:
ax_pose 20, 0x81e7, 0x80f8, 0xac00
ax_pose 21, 0x01ef, 0x0108, 0xac08
ax_pose_terminator
sLuvdiscPose175:
ax_pose 22, 0x81e8, 0x80f8, 0xac00
ax_pose 23, 0x01f0, 0x00f0, 0xac08
ax_pose_terminator
sLuvdiscPose176:
ax_pose 3, 0x81e7, 0x80f8, 0xac00
ax_pose_terminator
sLuvdiscPose177:
ax_pose 17, 0x81e9, 0x80f7, 0xac00
ax_pose_terminator
sLuvdiscPose178:
ax_pose 18, 0x01ed, 0x40f7, 0xac00
ax_pose 19, 0x01e5, 0x00ff, 0xac04
ax_pose_terminator
sLuvdiscPose179:
ax_pose 16, 0x81e7, 0x80f8, 0xac00
ax_pose_terminator
sLuvdiscPose180:
ax_pose 18, 0x01ec, 0x40f7, 0xac00
ax_pose 19, 0x01e4, 0x00ff, 0xac04
ax_pose_terminator
sLuvdiscPose181:
ax_pose 22, 0x81e8, 0x80f8, 0xac00
ax_pose 23, 0x01f0, 0x00f0, 0xac08
ax_pose_terminator
sLuvdiscPose182:
ax_pose 25, 0x01eb, 0x40f7, 0xac00
ax_pose 26, 0x01fb, 0x00ff, 0xac04
ax_pose_terminator
sLuvdiscPose183:
ax_pose 28, 0x81e8, 0x80f8, 0xac00
ax_pose_terminator
sLuvdiscPose184:
ax_pose 25, 0x01eb, 0x50f9, 0xac00
ax_pose 26, 0x01fb, 0x10f9, 0xac04
ax_pose_terminator
sLuvdiscPose185:
ax_pose 22, 0x81e8, 0x90f8, 0xac00
ax_pose 23, 0x01f0, 0x1108, 0xac08
ax_pose_terminator
sLuvdiscPose186:
ax_pose 18, 0x01ec, 0x50f9, 0xac00
ax_pose 19, 0x01e4, 0x10f9, 0xac04
ax_pose_terminator
sLuvdiscPose187:
ax_pose 0, 0x81e7, 0x80f8, 0xac00
ax_pose_terminator
sLuvdiscPose188:
ax_pose 3, 0x81e7, 0x80f8, 0xac00
ax_pose_terminator
sLuvdiscPose189:
ax_pose 6, 0x01e7, 0x80f0, 0xac00
ax_pose_terminator
sLuvdiscPose190:
ax_pose 9, 0x81e7, 0x80f8, 0xac00
ax_pose_terminator
sLuvdiscPose191:
ax_pose 12, 0x81e7, 0x80f8, 0xac00
ax_pose_terminator
sLuvdiscPose192:
ax_pose 9, 0x81e7, 0x90f8, 0xac00
ax_pose_terminator
sLuvdiscPose193:
ax_pose 6, 0x01e7, 0x90f0, 0xac00
ax_pose_terminator
sLuvdiscPose194:
ax_pose 3, 0x81e7, 0x90f8, 0xac00
ax_pose_terminator
.align 2
sLuvdiscAnims_1_1:
ax_anim 8, 0, 0, 0, 0, 0, 0,
ax_anim 8, 0, 1, 0, 0, 0, 0,
ax_anim 8, 0, 0, 0, -1, 0, 0,
ax_anim 8, 0, 2, 0, -1, 0, 0,
ax_anim 8, 0, 0, 0, -2, 0, 0,
ax_anim 8, 0, 1, 0, -2, 0, 0,
ax_anim 8, 0, 0, 0, -2, 0, 0,
ax_anim 8, 0, 2, 0, -2, 0, 0,
ax_anim 8, 0, 0, 0, -2, 0, 0,
ax_anim 8, 0, 1, 0, -1, 0, 0,
ax_anim 8, 0, 0, 0, -1, 0, 0,
ax_anim 8, 0, 2, 0, 0, 0, 0,
ax_anim_terminator
sLuvdiscAnims_1_2:
ax_anim 8, 0, 3, 0, 0, 0, 0,
ax_anim 8, 0, 4, 0, 0, 0, 0,
ax_anim 8, 0, 3, 0, -1, 0, 0,
ax_anim 8, 0, 5, 0, -1, 0, 0,
ax_anim 8, 0, 3, 0, -2, 0, 0,
ax_anim 8, 0, 4, 0, -2, 0, 0,
ax_anim 8, 0, 3, 0, -2, 0, 0,
ax_anim 8, 0, 5, 0, -2, 0, 0,
ax_anim 8, 0, 3, 0, -2, 0, 0,
ax_anim 8, 0, 4, 0, -1, 0, 0,
ax_anim 8, 0, 3, 0, -1, 0, 0,
ax_anim 8, 0, 5, 0, 0, 0, 0,
ax_anim_terminator
sLuvdiscAnims_1_3:
ax_anim 8, 0, 6, 0, 0, 0, 0,
ax_anim 8, 0, 7, 0, 0, 0, 0,
ax_anim 8, 0, 6, 0, -1, 0, 0,
ax_anim 8, 0, 8, 0, -1, 0, 0,
ax_anim 8, 0, 6, 0, -2, 0, 0,
ax_anim 8, 0, 7, 0, -2, 0, 0,
ax_anim 8, 0, 6, 0, -2, 0, 0,
ax_anim 8, 0, 8, 0, -2, 0, 0,
ax_anim 8, 0, 6, 0, -2, 0, 0,
ax_anim 8, 0, 7, 0, -1, 0, 0,
ax_anim 8, 0, 6, 0, -1, 0, 0,
ax_anim 8, 0, 8, 0, 0, 0, 0,
ax_anim_terminator
sLuvdiscAnims_1_4:
ax_anim 8, 0, 9, 0, 0, 0, 0,
ax_anim 8, 0, 10, 0, 0, 0, 0,
ax_anim 8, 0, 9, 0, -1, 0, 0,
ax_anim 8, 0, 11, 0, -1, 0, 0,
ax_anim 8, 0, 9, 0, -2, 0, 0,
ax_anim 8, 0, 10, 0, -2, 0, 0,
ax_anim 8, 0, 9, 0, -2, 0, 0,
ax_anim 8, 0, 11, 0, -2, 0, 0,
ax_anim 8, 0, 9, 0, -2, 0, 0,
ax_anim 8, 0, 10, 0, -1, 0, 0,
ax_anim 8, 0, 9, 0, -1, 0, 0,
ax_anim 8, 0, 11, 0, 0, 0, 0,
ax_anim_terminator
sLuvdiscAnims_1_5:
ax_anim 8, 0, 12, 0, 0, 0, 0,
ax_anim 8, 0, 13, 0, 0, 0, 0,
ax_anim 8, 0, 12, 0, -1, 0, 0,
ax_anim 8, 0, 14, 0, -1, 0, 0,
ax_anim 8, 0, 12, 0, -2, 0, 0,
ax_anim 8, 0, 13, 0, -2, 0, 0,
ax_anim 8, 0, 12, 0, -2, 0, 0,
ax_anim 8, 0, 14, 0, -2, 0, 0,
ax_anim 8, 0, 12, 0, -2, 0, 0,
ax_anim 8, 0, 13, 0, -1, 0, 0,
ax_anim 8, 0, 12, 0, -1, 0, 0,
ax_anim 8, 0, 14, 0, 0, 0, 0,
ax_anim_terminator
sLuvdiscAnims_1_6:
ax_anim 8, 0, 15, 0, 0, 0, 0,
ax_anim 8, 0, 16, 0, 0, 0, 0,
ax_anim 8, 0, 15, 0, -1, 0, 0,
ax_anim 8, 0, 17, 0, -1, 0, 0,
ax_anim 8, 0, 15, 0, -2, 0, 0,
ax_anim 8, 0, 16, 0, -2, 0, 0,
ax_anim 8, 0, 15, 0, -2, 0, 0,
ax_anim 8, 0, 17, 0, -2, 0, 0,
ax_anim 8, 0, 15, 0, -2, 0, 0,
ax_anim 8, 0, 16, 0, -1, 0, 0,
ax_anim 8, 0, 15, 0, -1, 0, 0,
ax_anim 8, 0, 17, 0, 0, 0, 0,
ax_anim_terminator
sLuvdiscAnims_1_7:
ax_anim 8, 0, 18, 0, 0, 0, 0,
ax_anim 8, 0, 19, 0, 0, 0, 0,
ax_anim 8, 0, 18, 0, -1, 0, 0,
ax_anim 8, 0, 20, 0, -1, 0, 0,
ax_anim 8, 0, 18, 0, -2, 0, 0,
ax_anim 8, 0, 19, 0, -2, 0, 0,
ax_anim 8, 0, 18, 0, -2, 0, 0,
ax_anim 8, 0, 20, 0, -2, 0, 0,
ax_anim 8, 0, 18, 0, -2, 0, 0,
ax_anim 8, 0, 19, 0, -1, 0, 0,
ax_anim 8, 0, 18, 0, -1, 0, 0,
ax_anim 8, 0, 20, 0, 0, 0, 0,
ax_anim_terminator
sLuvdiscAnims_1_8:
ax_anim 8, 0, 21, 0, 0, 0, 0,
ax_anim 8, 0, 22, 0, 0, 0, 0,
ax_anim 8, 0, 21, 0, 0, 0, 0,
ax_anim 8, 0, 23, 0, -1, 0, 0,
ax_anim 8, 0, 21, 0, -2, 0, 0,
ax_anim 8, 0, 22, 0, -2, 0, 0,
ax_anim 8, 0, 21, 0, -2, 0, 0,
ax_anim 8, 0, 23, 0, -2, 0, 0,
ax_anim 8, 0, 21, 0, -2, 0, 0,
ax_anim 8, 0, 22, 0, -1, 0, 0,
ax_anim 8, 0, 21, 0, 0, 0, 0,
ax_anim 8, 0, 23, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sLuvdiscAnims_2_1:
ax_anim 2, 0, 24, 0, -1, 0, -1,
ax_anim 2, 0, 24, 0, -2, 0, -2,
ax_anim 6, 0, 24, 0, -3, 0, -3,
ax_anim 1, 0, 26, 0, 0, 0, 0,
ax_anim 1, 2, 25, 0, 4, 0, 4,
ax_anim 2, 0, 26, 0, 10, 0, 10,
ax_anim 2, 0, 24, 0, 24, 0, 22,
ax_anim 2, 1, 24, 1, 24, 1, 22,
ax_anim 2, 0, 24, 0, 24, 0, 22,
ax_anim 2, 0, 24, 1, 24, 1, 22,
ax_anim 2, 0, 24, 0, 6, 0, 6,
ax_anim_terminator
sLuvdiscAnims_2_2:
ax_anim 2, 0, 27, -1, -1, -1, -1,
ax_anim 2, 0, 27, -2, -2, -2, -2,
ax_anim 6, 0, 27, -3, -3, -3, -3,
ax_anim 1, 0, 29, 0, 0, 0, 0,
ax_anim 1, 2, 28, 4, 4, 4, 4,
ax_anim 2, 0, 29, 10, 11, 10, 10,
ax_anim 2, 0, 27, 22, 25, 22, 22,
ax_anim 2, 1, 27, 23, 24, 23, 21,
ax_anim 2, 0, 27, 22, 25, 22, 22,
ax_anim 2, 0, 27, 23, 24, 23, 21,
ax_anim 2, 0, 27, 6, 6, 6, 6,
ax_anim_terminator
sLuvdiscAnims_2_3:
ax_anim 2, 0, 30, -1, 0, -1, 0,
ax_anim 2, 0, 30, -2, 0, -2, 0,
ax_anim 6, 0, 30, -3, 0, -3, 0,
ax_anim 1, 0, 32, 0, 0, 0, 0,
ax_anim 1, 2, 31, 4, 0, 4, 0,
ax_anim 2, 0, 32, 10, 1, 10, 0,
ax_anim 2, 0, 30, 22, 3, 22, 0,
ax_anim 2, 1, 30, 22, 4, 22, 1,
ax_anim 2, 0, 30, 22, 3, 22, 0,
ax_anim 2, 0, 30, 22, 4, 22, 1,
ax_anim 2, 0, 30, 6, 1, 6, 0,
ax_anim_terminator
sLuvdiscAnims_2_4:
ax_anim 2, 0, 33, -1, 1, -1, 1,
ax_anim 2, 0, 33, -2, 2, -2, 2,
ax_anim 6, 0, 33, -3, 3, -3, 3,
ax_anim 1, 0, 35, 0, -1, 0, -1,
ax_anim 1, 2, 34, 5, -5, 5, -5,
ax_anim 2, 0, 35, 12, -11, 12, -12,
ax_anim 2, 0, 33, 23, -19, 23, -22,
ax_anim 2, 1, 33, 24, -18, 24, -21,
ax_anim 2, 0, 33, 23, -19, 23, -22,
ax_anim 2, 0, 33, 24, -18, 24, -21,
ax_anim 2, 0, 33, 6, -6, 6, -6,
ax_anim_terminator
sLuvdiscAnims_2_5:
ax_anim 2, 0, 36, 0, 1, 0, 1,
ax_anim 2, 0, 36, 0, 2, 0, 2,
ax_anim 6, 0, 36, 0, 3, 0, 3,
ax_anim 1, 0, 38, 0, 0, 0, 0,
ax_anim 1, 2, 37, 0, -4, 0, -4,
ax_anim 2, 0, 38, 0, -11, 0, -12,
ax_anim 2, 0, 36, 0, -19, 0, -24,
ax_anim 2, 1, 36, 1, -19, 1, -24,
ax_anim 2, 0, 36, 0, -19, 0, -24,
ax_anim 2, 0, 36, 1, -19, 1, -24,
ax_anim 2, 0, 36, 0, -6, 0, -6,
ax_anim_terminator
sLuvdiscAnims_2_6:
ax_anim 2, 0, 39, 1, 1, 1, 1,
ax_anim 2, 0, 39, 2, 2, 2, 2,
ax_anim 6, 0, 39, 3, 3, 3, 3,
ax_anim 1, 0, 41, 0, -1, 0, -1,
ax_anim 1, 2, 40, -5, -5, -5, -5,
ax_anim 2, 0, 41, -12, -11, -12, -12,
ax_anim 2, 0, 39, -23, -19, -23, -22,
ax_anim 2, 1, 39, -24, -18, -24, -21,
ax_anim 2, 0, 39, -23, -19, -23, -22,
ax_anim 2, 0, 39, -24, -18, -24, -21,
ax_anim 2, 0, 39, -6, -6, -6, -6,
ax_anim_terminator
sLuvdiscAnims_2_7:
ax_anim 2, 0, 42, 1, 0, 1, 0,
ax_anim 2, 0, 42, 2, 0, 2, 0,
ax_anim 6, 0, 42, 3, 0, 3, 0,
ax_anim 1, 0, 44, 0, 0, 0, 0,
ax_anim 1, 2, 43, -4, 0, -4, 0,
ax_anim 2, 0, 44, -10, 1, -10, 0,
ax_anim 2, 0, 42, -22, 3, -22, 0,
ax_anim 2, 1, 42, -22, 4, -22, 1,
ax_anim 2, 0, 42, -22, 3, -22, 0,
ax_anim 2, 0, 42, -22, 4, -22, 1,
ax_anim 2, 0, 42, -6, 1, -6, 0,
ax_anim_terminator
sLuvdiscAnims_2_8:
ax_anim 2, 0, 45, 1, -1, 1, -1,
ax_anim 2, 0, 45, 2, -2, 2, -2,
ax_anim 6, 0, 45, 3, -3, 3, -3,
ax_anim 1, 0, 47, 0, 0, 0, 0,
ax_anim 1, 2, 46, -4, 4, -4, 4,
ax_anim 2, 0, 47, -10, 11, -10, 10,
ax_anim 2, 0, 45, -22, 25, -22, 22,
ax_anim 2, 1, 45, -23, 24, -23, 21,
ax_anim 2, 0, 45, -22, 25, -22, 22,
ax_anim 2, 0, 45, -23, 24, -23, 21,
ax_anim 2, 0, 45, -6, 6, -6, 6,
ax_anim_terminator
.align 2
sLuvdiscAnims_3_1:
ax_anim 2, 0, 49, 0, -1, 0, -1,
ax_anim 2, 0, 50, 0, -2, 0, -2,
ax_anim 6, 0, 48, 0, -3, 0, -3,
ax_anim 1, 0, 50, 0, 0, 0, 0,
ax_anim 1, 2, 49, 0, 8, 0, 8,
ax_anim 2, 0, 50, 0, 24, 0, 24,
ax_anim 2, 0, 48, 0, 48, 0, 45,
ax_anim 2, 1, 48, 1, 48, 1, 45,
ax_anim 2, 0, 48, 0, 48, 0, 45,
ax_anim 2, 0, 48, 1, 48, 1, 45,
ax_anim 2, 0, 48, 0, 20, 0, 20,
ax_anim 2, 0, 48, 0, 6, 0, 6,
ax_anim_terminator
sLuvdiscAnims_3_2:
ax_anim 2, 0, 51, -1, -1, -1, -1,
ax_anim 2, 0, 51, -2, -2, -2, -2,
ax_anim 6, 0, 51, -3, -3, -3, -3,
ax_anim 1, 0, 53, 0, 0, 0, 0,
ax_anim 1, 2, 52, 8, 8, 8, 8,
ax_anim 2, 0, 53, 24, 24, 24, 24,
ax_anim 2, 0, 51, 46, 49, 46, 46,
ax_anim 2, 1, 51, 47, 48, 47, 45,
ax_anim 2, 0, 51, 46, 49, 46, 46,
ax_anim 2, 0, 51, 47, 48, 47, 45,
ax_anim 2, 0, 51, 20, 20, 20, 20,
ax_anim 2, 0, 51, 6, 6, 6, 6,
ax_anim_terminator
sLuvdiscAnims_3_3:
ax_anim 2, 0, 54, -1, 0, -1, 0,
ax_anim 2, 0, 54, -2, 0, -2, 0,
ax_anim 6, 0, 54, -3, 0, -3, 0,
ax_anim 1, 0, 56, 0, 0, 0, 0,
ax_anim 1, 2, 55, 8, 0, 8, 0,
ax_anim 2, 0, 56, 24, 1, 24, 0,
ax_anim 2, 0, 54, 46, 3, 46, 0,
ax_anim 2, 1, 54, 46, 4, 46, 1,
ax_anim 2, 0, 54, 46, 3, 46, 0,
ax_anim 2, 0, 54, 46, 4, 46, 1,
ax_anim 2, 0, 54, 20, 1, 20, 0,
ax_anim 2, 0, 54, 6, 0, 6, 0,
ax_anim_terminator
sLuvdiscAnims_3_4:
ax_anim 2, 0, 57, -1, 1, -1, 1,
ax_anim 2, 0, 57, -2, 2, -2, 2,
ax_anim 6, 0, 57, -3, 3, -3, 3,
ax_anim 1, 0, 59, 0, -1, 0, -1,
ax_anim 1, 2, 58, 10, -10, 10, -10,
ax_anim 2, 0, 59, 25, -23, 25, -25,
ax_anim 2, 0, 57, 47, -43, 47, -46,
ax_anim 2, 1, 57, 48, -42, 48, -45,
ax_anim 2, 0, 57, 47, -43, 47, -46,
ax_anim 2, 0, 57, 48, -42, 48, -45,
ax_anim 2, 0, 57, 21, -19, 21, -21,
ax_anim 2, 0, 57, 6, -6, 6, -6,
ax_anim_terminator
sLuvdiscAnims_3_5:
ax_anim 2, 0, 60, 0, 1, 0, 1,
ax_anim 2, 0, 60, 0, 2, 0, 2,
ax_anim 6, 0, 60, 0, 3, 0, 3,
ax_anim 1, 0, 62, 0, 0, 0, 0,
ax_anim 1, 2, 61, 0, -8, 0, -8,
ax_anim 2, 0, 62, 0, -22, 0, -23,
ax_anim 2, 0, 60, 0, -43, 0, -48,
ax_anim 2, 1, 60, 1, -43, 1, -48,
ax_anim 2, 0, 60, 0, -43, 0, -48,
ax_anim 2, 0, 60, 1, -43, 1, -48,
ax_anim 2, 0, 60, 0, -16, 0, -16,
ax_anim 2, 0, 60, 0, -6, 0, -6,
ax_anim_terminator
sLuvdiscAnims_3_6:
ax_anim 2, 0, 63, 1, 1, 1, 1,
ax_anim 2, 0, 63, 2, 2, 2, 2,
ax_anim 6, 0, 63, 3, 3, 3, 3,
ax_anim 1, 0, 65, 0, -1, 0, -1,
ax_anim 1, 2, 64, -10, -10, -10, -10,
ax_anim 2, 0, 65, -25, -23, -25, -25,
ax_anim 2, 0, 63, -47, -43, -47, -46,
ax_anim 2, 1, 63, -48, -42, -48, -45,
ax_anim 2, 0, 63, -47, -43, -47, -46,
ax_anim 2, 0, 63, -48, -42, -48, -45,
ax_anim 2, 0, 63, -21, -19, -21, -21,
ax_anim 2, 0, 63, -6, -6, -6, -6,
ax_anim_terminator
sLuvdiscAnims_3_7:
ax_anim 2, 0, 66, 1, 0, 1, 0,
ax_anim 2, 0, 66, 2, 0, 2, 0,
ax_anim 6, 0, 66, 3, 0, 3, 0,
ax_anim 1, 0, 68, 0, 0, 0, 0,
ax_anim 1, 2, 67, -8, 0, -8, 0,
ax_anim 2, 0, 68, -24, 1, -24, 0,
ax_anim 2, 0, 66, -46, 3, -46, 0,
ax_anim 2, 1, 66, -46, 4, -46, 1,
ax_anim 2, 0, 66, -46, 3, -46, 0,
ax_anim 2, 0, 66, -46, 4, -46, 1,
ax_anim 2, 0, 66, -20, 1, -20, 0,
ax_anim 2, 0, 66, -6, 0, -6, 0,
ax_anim_terminator
sLuvdiscAnims_3_8:
ax_anim 2, 0, 69, 1, -1, 1, -1,
ax_anim 2, 0, 69, 2, -2, 2, -2,
ax_anim 6, 0, 69, 3, -3, 3, -3,
ax_anim 1, 0, 71, 0, 0, 0, 0,
ax_anim 1, 2, 70, -8, 8, -8, 8,
ax_anim 2, 0, 71, -24, 24, -24, 24,
ax_anim 2, 0, 69, -46, 49, -46, 46,
ax_anim 2, 1, 69, -47, 48, -47, 45,
ax_anim 2, 0, 69, -46, 49, -46, 46,
ax_anim 2, 0, 69, -47, 48, -47, 45,
ax_anim 2, 0, 69, -20, 20, -20, 20,
ax_anim 2, 0, 69, -6, 6, -6, 6,
ax_anim_terminator
.align 2
sLuvdiscAnims_4_1:
ax_anim 2, 0, 73, 0, -2, 0, -2,
ax_anim 6, 2, 73, 0, -3, 0, -3,
ax_anim 2, 0, 72, 0, -1, 0, -1,
ax_anim 2, 1, 74, 0, 3, 0, 3,
ax_anim 2, 0, 74, 1, 3, 1, 3,
ax_anim 2, 0, 74, 0, 3, 0, 3,
ax_anim 2, 0, 74, 1, 3, 1, 3,
ax_anim 2, 0, 74, 0, 3, 0, 3,
ax_anim 2, 0, 74, 1, 3, 1, 3,
ax_anim 2, 0, 74, 0, 3, 0, 3,
ax_anim 2, 0, 72, 0, 1, 0, 1,
ax_anim_terminator
sLuvdiscAnims_4_2:
ax_anim 2, 0, 76, -2, -2, -2, -2,
ax_anim 6, 2, 76, -3, -3, -3, -3,
ax_anim 2, 0, 75, -1, -1, -1, -1,
ax_anim 2, 1, 77, 2, 2, 2, 2,
ax_anim 2, 0, 77, 3, 1, 3, 1,
ax_anim 2, 0, 77, 2, 2, 2, 2,
ax_anim 2, 0, 77, 3, 1, 3, 1,
ax_anim 2, 0, 77, 2, 2, 2, 2,
ax_anim 2, 0, 77, 3, 1, 3, 1,
ax_anim 2, 0, 77, 2, 2, 2, 2,
ax_anim 2, 0, 75, 1, 1, 1, 1,
ax_anim_terminator
sLuvdiscAnims_4_3:
ax_anim 2, 0, 79, -2, 0, -2, 0,
ax_anim 6, 2, 79, -3, 0, -3, 0,
ax_anim 2, 0, 78, -1, 0, -1, 0,
ax_anim 2, 1, 80, 3, 0, 3, 0,
ax_anim 2, 0, 80, 3, 1, 3, 1,
ax_anim 2, 0, 80, 3, 0, 3, 0,
ax_anim 2, 0, 80, 3, 1, 3, 1,
ax_anim 2, 0, 80, 3, 0, 3, 0,
ax_anim 2, 0, 80, 3, 1, 3, 1,
ax_anim 2, 0, 80, 3, 0, 3, 0,
ax_anim 2, 0, 78, 1, 0, 1, 0,
ax_anim_terminator
sLuvdiscAnims_4_4:
ax_anim 2, 0, 82, -2, 2, -2, 2,
ax_anim 6, 2, 82, -3, 3, -3, 3,
ax_anim 2, 0, 81, -1, 1, -1, 1,
ax_anim 2, 1, 83, 2, -2, 2, -2,
ax_anim 2, 0, 83, 3, -1, 3, -1,
ax_anim 2, 0, 83, 2, -2, 2, -2,
ax_anim 2, 0, 83, 3, -1, 3, -1,
ax_anim 2, 0, 83, 2, -2, 2, -2,
ax_anim 2, 0, 83, 3, -1, 3, -1,
ax_anim 2, 0, 83, 2, -2, 2, -2,
ax_anim 2, 0, 81, 1, -1, 1, -1,
ax_anim_terminator
sLuvdiscAnims_4_5:
ax_anim 2, 0, 85, 0, 2, 0, 2,
ax_anim 6, 2, 85, 0, 3, 0, 3,
ax_anim 2, 0, 84, 0, 1, 0, 1,
ax_anim 2, 1, 86, 0, -3, 0, -3,
ax_anim 2, 0, 86, 1, -3, 1, -3,
ax_anim 2, 0, 86, 0, -3, 0, -3,
ax_anim 2, 0, 86, 1, -3, 1, -3,
ax_anim 2, 0, 86, 0, -3, 0, -3,
ax_anim 2, 0, 86, 1, -3, 1, -3,
ax_anim 2, 0, 86, 0, -3, 0, -3,
ax_anim 2, 0, 84, 0, -1, 0, -1,
ax_anim_terminator
sLuvdiscAnims_4_6:
ax_anim 2, 0, 88, 2, 2, 2, 2,
ax_anim 6, 2, 88, 3, 3, 3, 3,
ax_anim 2, 0, 87, 1, 1, 1, 1,
ax_anim 2, 1, 89, -2, -2, -2, -2,
ax_anim 2, 0, 89, -3, -1, -3, -1,
ax_anim 2, 0, 89, -2, -2, -2, -2,
ax_anim 2, 0, 89, -3, -1, -3, -1,
ax_anim 2, 0, 89, -2, -2, -2, -2,
ax_anim 2, 0, 89, -3, -1, -3, -1,
ax_anim 2, 0, 89, -2, -2, -2, -2,
ax_anim 2, 0, 87, -1, -1, -1, -1,
ax_anim_terminator
sLuvdiscAnims_4_7:
ax_anim 2, 0, 91, 2, 0, 2, 0,
ax_anim 6, 2, 91, 3, 0, 3, 0,
ax_anim 2, 0, 90, 1, 0, 1, 0,
ax_anim 2, 1, 92, -3, 0, -3, 0,
ax_anim 2, 0, 92, -3, 1, -3, 1,
ax_anim 2, 0, 92, -3, 0, -3, 0,
ax_anim 2, 0, 92, -3, 1, -3, 1,
ax_anim 2, 0, 92, -3, 0, -3, 0,
ax_anim 2, 0, 92, -3, 1, -3, 1,
ax_anim 2, 0, 92, -3, 0, -3, 0,
ax_anim 2, 0, 90, -1, 0, -1, 0,
ax_anim_terminator
sLuvdiscAnims_4_8:
ax_anim 2, 0, 94, 2, -2, 2, -2,
ax_anim 6, 2, 94, 3, -3, 3, -3,
ax_anim 2, 0, 93, 1, -1, 1, -1,
ax_anim 2, 1, 95, -2, 2, -2, 2,
ax_anim 2, 0, 95, -3, 1, -3, 1,
ax_anim 2, 0, 95, -2, 2, -2, 2,
ax_anim 2, 0, 95, -3, 1, -3, 1,
ax_anim 2, 0, 95, -2, 2, -2, 2,
ax_anim 2, 0, 95, -3, 1, -3, 1,
ax_anim 2, 0, 95, -2, 2, -2, 2,
ax_anim 2, 0, 93, -1, 1, -1, 1,
ax_anim_terminator
.align 2
sLuvdiscAnims_5_1:
ax_anim 1, 0, 97, 0, 0, 0, 0,
ax_anim 1, 0, 98, 0, -1, 0, 0,
ax_anim 2, 0, 99, 0, -2, 0, 0,
ax_anim 2, 0, 100, 0, -3, 0, 0,
ax_anim 2, 0, 101, 0, -4, 0, 0,
ax_anim 2, 0, 102, 0, -5, 0, 0,
ax_anim 2, 0, 103, 0, -5, 0, 0,
ax_anim 6, 2, 96, 0, -5, 0, 0,
ax_anim 2, 0, 96, 1, -5, 1, 0,
ax_anim 2, 1, 96, 0, -5, 0, 0,
ax_anim 2, 0, 96, 1, -5, 1, 0,
ax_anim 2, 0, 96, 0, -5, 0, 0,
ax_anim 2, 0, 96, 0, -3, 0, 0,
ax_anim 2, 0, 96, 0, -1, 0, 0,
ax_anim_terminator
sLuvdiscAnims_5_2:
ax_anim 1, 0, 96, 0, 0, 0, 0,
ax_anim 1, 0, 97, 0, -1, 0, 0,
ax_anim 2, 0, 98, 0, -2, 0, 0,
ax_anim 2, 0, 99, 0, -3, 0, 0,
ax_anim 2, 0, 100, 0, -4, 0, 0,
ax_anim 2, 0, 101, 0, -5, 0, 0,
ax_anim 2, 0, 102, 0, -5, 0, 0,
ax_anim 6, 2, 103, 0, -5, 0, 0,
ax_anim 2, 0, 103, -1, -4, -1, 1,
ax_anim 2, 1, 103, 0, -5, 0, 0,
ax_anim 2, 0, 103, -1, -4, -1, 1,
ax_anim 2, 0, 103, 0, -5, 0, 0,
ax_anim 2, 0, 103, 0, -3, 0, 0,
ax_anim 2, 0, 103, 0, -1, 0, 0,
ax_anim_terminator
sLuvdiscAnims_5_3:
ax_anim 1, 0, 103, 0, 0, 0, 0,
ax_anim 1, 0, 96, 0, -1, 0, 0,
ax_anim 2, 0, 97, 0, -2, 0, 0,
ax_anim 2, 0, 98, 0, -3, 0, 0,
ax_anim 2, 0, 99, 0, -4, 0, 0,
ax_anim 2, 0, 100, 0, -5, 0, 0,
ax_anim 2, 0, 101, 0, -5, 0, 0,
ax_anim 6, 2, 102, 0, -5, 0, 0,
ax_anim 2, 0, 102, 0, -6, 0, -1,
ax_anim 2, 1, 102, 0, -5, 0, 0,
ax_anim 2, 0, 102, 0, -6, 0, -1,
ax_anim 2, 0, 102, 0, -5, 0, 0,
ax_anim 2, 0, 102, 0, -3, 0, 0,
ax_anim 2, 0, 102, 0, -1, 0, 0,
ax_anim_terminator
sLuvdiscAnims_5_4:
ax_anim 1, 0, 102, 0, 0, 0, 0,
ax_anim 1, 0, 103, 0, -1, 0, 0,
ax_anim 2, 0, 96, 0, -2, 0, 0,
ax_anim 2, 0, 97, 0, -3, 0, 0,
ax_anim 2, 0, 98, 0, -4, 0, 0,
ax_anim 2, 0, 99, 0, -5, 0, 0,
ax_anim 2, 0, 100, 0, -5, 0, 0,
ax_anim 6, 2, 101, 0, -5, 0, 0,
ax_anim 2, 0, 101, -1, -6, -1, -1,
ax_anim 2, 1, 101, 0, -5, 0, 0,
ax_anim 2, 0, 101, -1, -6, -1, -1,
ax_anim 2, 0, 101, 0, -5, 0, 0,
ax_anim 2, 0, 101, 0, -3, 0, 0,
ax_anim 2, 0, 101, 0, -1, 0, 0,
ax_anim_terminator
sLuvdiscAnims_5_5:
ax_anim 1, 0, 101, 0, 0, 0, 0,
ax_anim 1, 0, 102, 0, -1, 0, 0,
ax_anim 2, 0, 103, 0, -2, 0, 0,
ax_anim 2, 0, 96, 0, -3, 0, 0,
ax_anim 2, 0, 97, 0, -4, 0, 0,
ax_anim 2, 0, 98, 0, -5, 0, 0,
ax_anim 2, 0, 99, 0, -5, 0, 0,
ax_anim 6, 2, 100, 0, -5, 0, 0,
ax_anim 2, 0, 100, 1, -5, 1, 0,
ax_anim 2, 1, 100, 0, -5, 0, 0,
ax_anim 2, 0, 100, 1, -5, 1, 0,
ax_anim 2, 0, 100, 0, -5, 0, 0,
ax_anim 2, 0, 100, 0, -3, 0, 0,
ax_anim 2, 0, 100, 0, -1, 0, 0,
ax_anim_terminator
sLuvdiscAnims_5_6:
ax_anim 1, 0, 100, 0, 0, 0, 0,
ax_anim 1, 0, 101, 0, -1, 0, 0,
ax_anim 2, 0, 102, 0, -2, 0, 0,
ax_anim 2, 0, 103, 0, -3, 0, 0,
ax_anim 2, 0, 96, 0, -4, 0, 0,
ax_anim 2, 0, 97, 0, -5, 0, 0,
ax_anim 2, 0, 98, 0, -5, 0, 0,
ax_anim 6, 2, 99, 0, -5, 0, 0,
ax_anim 2, 0, 99, 1, -6, 1, -1,
ax_anim 2, 1, 99, 0, -5, 0, 0,
ax_anim 2, 0, 99, 1, -6, 1, -1,
ax_anim 2, 0, 99, 0, -5, 0, 0,
ax_anim 2, 0, 99, 0, -3, 0, 0,
ax_anim 2, 0, 99, 0, -1, 0, 0,
ax_anim_terminator
sLuvdiscAnims_5_7:
ax_anim 1, 0, 99, 0, 0, 0, 0,
ax_anim 1, 0, 100, 0, -1, 0, 0,
ax_anim 2, 0, 101, 0, -2, 0, 0,
ax_anim 2, 0, 102, 0, -3, 0, 0,
ax_anim 2, 0, 103, 0, -4, 0, 0,
ax_anim 2, 0, 96, 0, -5, 0, 0,
ax_anim 2, 0, 97, 0, -5, 0, 0,
ax_anim 6, 2, 98, 0, -5, 0, 0,
ax_anim 2, 0, 98, 0, -6, 0, -1,
ax_anim 2, 1, 98, 0, -5, 0, 0,
ax_anim 2, 0, 98, 0, -6, 0, -1,
ax_anim 2, 0, 98, 0, -5, 0, 0,
ax_anim 2, 0, 98, 0, -3, 0, 0,
ax_anim 2, 0, 98, 0, -1, 0, 0,
ax_anim_terminator
sLuvdiscAnims_5_8:
ax_anim 1, 0, 98, 0, 0, 0, 0,
ax_anim 1, 0, 99, 0, -1, 0, 0,
ax_anim 2, 0, 100, 0, -2, 0, 0,
ax_anim 2, 0, 101, 0, -3, 0, 0,
ax_anim 2, 0, 102, 0, -4, 0, 0,
ax_anim 2, 0, 103, 0, -5, 0, 0,
ax_anim 2, 0, 96, 0, -5, 0, 0,
ax_anim 6, 2, 97, 0, -5, 0, 0,
ax_anim 2, 0, 97, 1, -4, 1, 1,
ax_anim 2, 1, 97, 0, -5, 0, 0,
ax_anim 2, 0, 97, 1, -4, 1, 1,
ax_anim 2, 0, 97, 0, -5, 0, 0,
ax_anim 2, 0, 97, 0, -3, 0, 0,
ax_anim 2, 0, 97, 0, -1, 0, 0,
ax_anim_terminator
.align 2
sLuvdiscAnims_6_1:
ax_anim 16, 0, 104, 0, 0, 0, 0,
ax_anim 12, 0, 104, 0, -1, 0, 0,
ax_anim 16, 0, 104, 0, -2, 0, 0,
ax_anim 16, 0, 105, 0, -1, 0, 0,
ax_anim 12, 0, 105, 0, 0, 0, 0,
ax_anim 16, 0, 105, 0, 1, 0, 0,
ax_anim_terminator
.align 2
sLuvdiscAnims_7_1:
ax_anim 2, 0, 106, 0, -2, 0, -2,
ax_anim 8, 0, 106, 0, -3, 0, -3,
ax_anim_terminator
sLuvdiscAnims_7_2:
ax_anim 2, 0, 107, -2, -2, -2, -2,
ax_anim 8, 0, 107, -3, -3, -3, -3,
ax_anim_terminator
sLuvdiscAnims_7_3:
ax_anim 2, 0, 108, -2, 0, -2, 0,
ax_anim 8, 0, 108, -3, 0, -3, 0,
ax_anim_terminator
sLuvdiscAnims_7_4:
ax_anim 2, 0, 109, -2, 2, -2, 2,
ax_anim 8, 0, 109, -3, 3, -3, 3,
ax_anim_terminator
sLuvdiscAnims_7_5:
ax_anim 2, 0, 110, 0, 2, 0, 2,
ax_anim 8, 0, 110, 0, 3, 0, 3,
ax_anim_terminator
sLuvdiscAnims_7_6:
ax_anim 2, 0, 111, 2, 2, 2, 2,
ax_anim 8, 0, 111, 3, 3, 3, 3,
ax_anim_terminator
sLuvdiscAnims_7_7:
ax_anim 2, 0, 112, 2, 0, 2, 0,
ax_anim 8, 0, 112, 3, 0, 3, 0,
ax_anim_terminator
sLuvdiscAnims_7_8:
ax_anim 2, 0, 113, 2, -2, 2, -2,
ax_anim 8, 0, 113, 3, -3, 3, -3,
ax_anim_terminator
.align 2
sLuvdiscAnims_8_1:
ax_anim 34, 0, 114, 0, 0, 0, 0,
ax_anim 8, 0, 115, 0, -1, 0, 0,
ax_anim 8, 0, 114, 0, -1, 0, 0,
ax_anim 8, 0, 116, 0, -2, 0, 0,
ax_anim 8, 0, 114, 0, -2, 0, 0,
ax_anim 8, 0, 115, 0, -2, 0, 0,
ax_anim 8, 0, 114, 0, -1, 0, 0,
ax_anim 8, 0, 116, 0, -1, 0, 0,
ax_anim_terminator
sLuvdiscAnims_8_2:
ax_anim 34, 0, 117, 0, 0, 0, 0,
ax_anim 8, 0, 118, 1, -1, 0, 0,
ax_anim 8, 0, 117, 1, -1, 0, 0,
ax_anim 8, 0, 119, 0, -2, 0, 0,
ax_anim 8, 0, 117, 0, -2, 0, 0,
ax_anim 8, 0, 118, 0, -2, 0, 0,
ax_anim 8, 0, 117, 0, -1, 0, 0,
ax_anim 8, 0, 119, 0, -1, 0, 0,
ax_anim_terminator
sLuvdiscAnims_8_3:
ax_anim 34, 0, 120, 0, 0, 0, 0,
ax_anim 8, 0, 121, 0, -1, 0, 0,
ax_anim 8, 0, 120, 0, -1, 0, 0,
ax_anim 8, 0, 122, 0, -2, 0, 0,
ax_anim 8, 0, 120, 0, -2, 0, 0,
ax_anim 8, 0, 121, 0, -2, 0, 0,
ax_anim 8, 0, 120, 0, -1, 0, 0,
ax_anim 8, 0, 122, 0, -1, 0, 0,
ax_anim_terminator
sLuvdiscAnims_8_4:
ax_anim 34, 0, 123, 0, 0, 0, 0,
ax_anim 8, 0, 124, 1, -1, 0, 0,
ax_anim 8, 0, 123, 1, -1, 0, 0,
ax_anim 8, 0, 125, 0, -2, 0, 0,
ax_anim 8, 0, 123, 0, -2, 0, 0,
ax_anim 8, 0, 124, 0, -2, 0, 0,
ax_anim 8, 0, 123, 0, -1, 0, 0,
ax_anim 8, 0, 125, 0, -1, 0, 0,
ax_anim_terminator
sLuvdiscAnims_8_5:
ax_anim 34, 0, 126, 0, 0, 0, 0,
ax_anim 8, 0, 127, 0, -1, 0, 0,
ax_anim 8, 0, 126, 0, -1, 0, 0,
ax_anim 8, 0, 128, 0, -2, 0, 0,
ax_anim 8, 0, 126, 0, -2, 0, 0,
ax_anim 8, 0, 127, 0, -2, 0, 0,
ax_anim 8, 0, 126, 0, -1, 0, 0,
ax_anim 8, 0, 128, 0, -1, 0, 0,
ax_anim_terminator
sLuvdiscAnims_8_6:
ax_anim 34, 0, 129, 0, 0, 0, 0,
ax_anim 8, 0, 130, -1, -1, 0, 0,
ax_anim 8, 0, 129, -1, -1, 0, 0,
ax_anim 8, 0, 131, 0, -2, 0, 0,
ax_anim 8, 0, 129, 0, -2, 0, 0,
ax_anim 8, 0, 130, 0, -2, 0, 0,
ax_anim 8, 0, 129, 0, -1, 0, 0,
ax_anim 8, 0, 131, 0, -1, 0, 0,
ax_anim_terminator
sLuvdiscAnims_8_7:
ax_anim 34, 0, 132, 0, 0, 0, 0,
ax_anim 8, 0, 133, 0, -1, 0, 0,
ax_anim 8, 0, 132, 0, -1, 0, 0,
ax_anim 8, 0, 134, 0, -2, 0, 0,
ax_anim 8, 0, 132, 0, -2, 0, 0,
ax_anim 8, 0, 133, 0, -2, 0, 0,
ax_anim 8, 0, 132, 0, -1, 0, 0,
ax_anim 8, 0, 134, 0, -1, 0, 0,
ax_anim_terminator
sLuvdiscAnims_8_8:
ax_anim 34, 0, 135, 0, 0, 0, 0,
ax_anim 8, 0, 136, -1, -1, 0, 0,
ax_anim 8, 0, 135, -1, -1, 0, 0,
ax_anim 8, 0, 137, 0, -2, 0, 0,
ax_anim 8, 0, 135, 0, -2, 0, 0,
ax_anim 8, 0, 136, 0, -2, 0, 0,
ax_anim 8, 0, 135, 0, -1, 0, 0,
ax_anim 8, 0, 137, 0, -1, 0, 0,
ax_anim_terminator
.align 2
sLuvdiscAnims_9_1:
ax_anim 2, 0, 138, 0, 0, 0, 0,
ax_anim 1, 0, 139, 8, 4, 8, 4,
ax_anim 2, 0, 140, 11, 12, 11, 12,
ax_anim 2, 0, 141, 8, 19, 8, 19,
ax_anim 3, 0, 142, 0, 23, 0, 23,
ax_anim 2, 3, 143, -8, 19, -8, 19,
ax_anim 2, 0, 144, -11, 12, -11, 12,
ax_anim 1, 0, 145, -8, 4, -8, 4,
ax_anim 1, 0, 138, 0, 0, 0, 0,
ax_anim_terminator
sLuvdiscAnims_9_2:
ax_anim 2, 0, 145, 0, 0, 0, 0,
ax_anim 1, 0, 138, 10, 1, 10, 1,
ax_anim 2, 0, 139, 19, 6, 19, 6,
ax_anim 2, 0, 140, 23, 16, 23, 15,
ax_anim 3, 0, 141, 23, 24, 23, 22,
ax_anim 2, 3, 142, 13, 25, 13, 25,
ax_anim 2, 0, 143, 5, 17, 5, 17,
ax_anim 1, 0, 144, 1, 8, 1, 8,
ax_anim 1, 0, 145, 0, 0, 0, 0,
ax_anim_terminator
sLuvdiscAnims_9_3:
ax_anim 2, 0, 144, 0, 0, 0, 0,
ax_anim 1, 0, 145, 5, -4, 5, -4,
ax_anim 2, 0, 138, 12, -4, 12, -4,
ax_anim 2, 0, 139, 20, -2, 20, -3,
ax_anim 3, 0, 140, 24, 3, 24, 1,
ax_anim 2, 3, 141, 17, 8, 17, 7,
ax_anim 2, 0, 142, 11, 8, 11, 8,
ax_anim 1, 0, 143, 4, 6, 4, 6,
ax_anim 1, 0, 144, 0, 0, 0, 0,
ax_anim_terminator
sLuvdiscAnims_9_4:
ax_anim 2, 0, 143, 0, 0, 0, 0,
ax_anim 1, 0, 144, 1, -8, 1, -8,
ax_anim 2, 0, 145, 6, -15, 6, -15,
ax_anim 2, 0, 138, 14, -19, 14, -21,
ax_anim 3, 0, 139, 22, -19, 22, -22,
ax_anim 2, 3, 140, 22, -12, 22, -14,
ax_anim 2, 0, 141, 18, -7, 18, -7,
ax_anim 1, 0, 142, 12, -1, 12, -1,
ax_anim 1, 0, 143, 0, 0, 0, 0,
ax_anim_terminator
sLuvdiscAnims_9_5:
ax_anim 2, 0, 142, 0, 0, 0, 0,
ax_anim 1, 0, 143, -9, -4, -9, -4,
ax_anim 2, 0, 144, -10, -11, -10, -11,
ax_anim 2, 0, 145, -6, -17, -6, -19,
ax_anim 3, 0, 138, 0, -20, 0, -22,
ax_anim 2, 3, 139, 6, -17, 6, -19,
ax_anim 2, 0, 140, 10, -11, 10, -11,
ax_anim 1, 0, 141, 9, -4, 9, -4,
ax_anim 1, 0, 142, 0, 0, 0, 0,
ax_anim_terminator
sLuvdiscAnims_9_6:
ax_anim 2, 0, 141, 0, 0, 0, 0,
ax_anim 1, 0, 140, -1, -8, -1, -8,
ax_anim 2, 0, 139, -6, -15, -6, -15,
ax_anim 2, 0, 138, -14, -19, -14, -21,
ax_anim 3, 0, 145, -22, -19, -22, -22,
ax_anim 2, 3, 144, -22, -12, -22, -14,
ax_anim 2, 0, 143, -18, -7, -18, -7,
ax_anim 1, 0, 142, -12, -1, -12, -1,
ax_anim 1, 0, 141, 0, 0, 0, 0,
ax_anim_terminator
sLuvdiscAnims_9_7:
ax_anim 2, 0, 140, 0, 0, 0, 0,
ax_anim 1, 0, 139, -5, -4, -5, -4,
ax_anim 2, 0, 138, -12, -4, -12, -4,
ax_anim 2, 0, 145, -20, -2, -20, -3,
ax_anim 3, 0, 144, -24, 3, -24, 1,
ax_anim 2, 3, 143, -17, 8, -17, 7,
ax_anim 2, 0, 142, -11, 8, -11, 8,
ax_anim 1, 0, 141, -4, 6, -4, 6,
ax_anim 1, 0, 140, 0, 0, 0, 0,
ax_anim_terminator
sLuvdiscAnims_9_8:
ax_anim 2, 0, 139, 0, 0, 0, 0,
ax_anim 1, 0, 138, -10, 1, -10, 1,
ax_anim 2, 0, 145, -19, 6, -19, 6,
ax_anim 2, 0, 144, -23, 16, -23, 15,
ax_anim 3, 0, 143, -23, 24, -23, 22,
ax_anim 2, 3, 142, -13, 25, -13, 25,
ax_anim 2, 0, 141, -5, 17, -5, 17,
ax_anim 1, 0, 140, -1, 8, -1, 8,
ax_anim 1, 0, 139, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sLuvdiscAnims_10_1:
ax_anim 2, 0, 146, 0, 0, 0, 0,
ax_anim 2, 0, 146, 6, 0, 6, 0,
ax_anim 2, 0, 146, -6, 0, -6, 0,
ax_anim 2, 0, 146, 10, 0, 10, 0,
ax_anim 2, 0, 146, -10, 0, -10, 0,
ax_anim 2, 0, 146, 12, 0, 12, 0,
ax_anim 3, 0, 146, -12, 0, -12, 0,
ax_anim 3, 0, 146, 13, 0, 13, 0,
ax_anim 3, 0, 146, -13, 0, -13, 0,
ax_anim 2, 0, 146, 12, 0, 12, 0,
ax_anim 3, 0, 146, -12, 0, -12, 0,
ax_anim 2, 0, 146, 10, 0, 10, 0,
ax_anim 2, 0, 146, -10, 0, -10, 0,
ax_anim 2, 0, 146, 6, 0, 6, 0,
ax_anim 2, 0, 146, -6, 0, -6, 0,
ax_anim 2, 0, 146, 0, 0, 0, 0,
ax_anim_terminator
sLuvdiscAnims_10_2:
ax_anim 2, 0, 147, 0, 0, 0, 0,
ax_anim 2, 0, 147, 6, -6, 6, -6,
ax_anim 2, 0, 147, -6, 6, -6, 6,
ax_anim 2, 0, 147, 10, -10, 10, -10,
ax_anim 2, 0, 147, -10, 10, -10, 10,
ax_anim 2, 0, 147, 12, -12, 12, -12,
ax_anim 3, 0, 147, -12, 12, -12, 12,
ax_anim 3, 0, 147, 13, -13, 13, -13,
ax_anim 3, 0, 147, -13, 13, -13, 13,
ax_anim 2, 0, 147, 12, -12, 12, -12,
ax_anim 3, 0, 147, -12, 12, -12, 12,
ax_anim 2, 0, 147, 10, -10, 10, -10,
ax_anim 2, 0, 147, -10, 10, -10, 10,
ax_anim 2, 0, 147, 6, -6, 6, -6,
ax_anim 2, 0, 147, -6, 6, -6, 6,
ax_anim 2, 0, 147, 0, 0, 0, 0,
ax_anim_terminator
sLuvdiscAnims_10_3:
ax_anim 2, 0, 148, 0, 0, 0, 0,
ax_anim 2, 0, 148, 0, -6, 0, -6,
ax_anim 2, 0, 148, 0, 6, 0, 6,
ax_anim 2, 0, 148, 0, -10, 0, -10,
ax_anim 2, 0, 148, 0, 10, 0, 10,
ax_anim 2, 0, 148, 0, -12, 0, -12,
ax_anim 3, 0, 148, 0, 12, 0, 12,
ax_anim 3, 0, 148, 0, -13, 0, -13,
ax_anim 3, 0, 148, 0, 13, 0, 13,
ax_anim 2, 0, 148, 0, -12, 0, -12,
ax_anim 3, 0, 148, 0, 12, 0, 12,
ax_anim 2, 0, 148, 0, -10, 0, -10,
ax_anim 2, 0, 148, 0, 10, 0, 10,
ax_anim 2, 0, 148, 0, -6, 0, -6,
ax_anim 2, 0, 148, 0, 6, 0, 6,
ax_anim 2, 0, 148, 0, 0, 0, 0,
ax_anim_terminator
sLuvdiscAnims_10_4:
ax_anim 2, 0, 149, 0, 0, 0, 0,
ax_anim 2, 0, 149, -6, -6, -6, -6,
ax_anim 2, 0, 149, 6, 6, 6, 6,
ax_anim 2, 0, 149, -10, -10, -10, -10,
ax_anim 2, 0, 149, 10, 10, 10, 10,
ax_anim 2, 0, 149, -12, -12, -12, -12,
ax_anim 3, 0, 149, 12, 12, 12, 12,
ax_anim 3, 0, 149, -13, -13, -13, -13,
ax_anim 3, 0, 149, 13, 13, 13, 13,
ax_anim 2, 0, 149, -12, -12, -12, -12,
ax_anim 3, 0, 149, 12, 12, 12, 12,
ax_anim 2, 0, 149, -10, -10, -10, -10,
ax_anim 2, 0, 149, 10, 10, 10, 10,
ax_anim 2, 0, 149, -6, -6, -6, -6,
ax_anim 2, 0, 149, 6, 6, 6, 6,
ax_anim 2, 0, 149, 0, 0, 0, 0,
ax_anim_terminator
sLuvdiscAnims_10_5:
ax_anim 2, 0, 150, 0, 0, 0, 0,
ax_anim 2, 0, 150, 6, 0, 6, 0,
ax_anim 2, 0, 150, -6, 0, -6, 0,
ax_anim 2, 0, 150, 10, 0, 10, 0,
ax_anim 2, 0, 150, -10, 0, -10, 0,
ax_anim 2, 0, 150, 12, 0, 12, 0,
ax_anim 3, 0, 150, -12, 0, -12, 0,
ax_anim 3, 0, 150, 13, 0, 13, 0,
ax_anim 3, 0, 150, -13, 0, -13, 0,
ax_anim 2, 0, 150, 12, 0, 12, 0,
ax_anim 3, 0, 150, -12, 0, -12, 0,
ax_anim 2, 0, 150, 10, 0, 10, 0,
ax_anim 2, 0, 150, -10, 0, -10, 0,
ax_anim 2, 0, 150, 6, 0, 6, 0,
ax_anim 2, 0, 150, -6, 0, -6, 0,
ax_anim 2, 0, 150, 0, 0, 0, 0,
ax_anim_terminator
sLuvdiscAnims_10_6:
ax_anim 2, 0, 151, 0, 0, 0, 0,
ax_anim 2, 0, 151, 6, -6, 6, -6,
ax_anim 2, 0, 151, -6, 6, -6, 6,
ax_anim 2, 0, 151, 10, -10, 10, -10,
ax_anim 2, 0, 151, -10, 10, -10, 10,
ax_anim 2, 0, 151, 12, -12, 12, -12,
ax_anim 3, 0, 151, -12, 12, -12, 12,
ax_anim 3, 0, 151, 13, -13, 13, -13,
ax_anim 3, 0, 151, -13, 13, -13, 13,
ax_anim 2, 0, 151, 12, -12, 12, -12,
ax_anim 3, 0, 151, -12, 12, -12, 12,
ax_anim 2, 0, 151, 10, -10, 10, -10,
ax_anim 2, 0, 151, -10, 10, -10, 10,
ax_anim 2, 0, 151, 6, -6, 6, -6,
ax_anim 2, 0, 151, -6, 6, -6, 6,
ax_anim 2, 0, 151, 0, 0, 0, 0,
ax_anim_terminator
sLuvdiscAnims_10_7:
ax_anim 2, 0, 152, 0, 0, 0, 0,
ax_anim 2, 0, 152, 0, -6, 0, -6,
ax_anim 2, 0, 152, 0, 6, 0, 6,
ax_anim 2, 0, 152, 0, -10, 0, -10,
ax_anim 2, 0, 152, 0, 10, 0, 10,
ax_anim 2, 0, 152, 0, -12, 0, -12,
ax_anim 3, 0, 152, 0, 12, 0, 12,
ax_anim 3, 0, 152, 0, -13, 0, -13,
ax_anim 3, 0, 152, 0, 13, 0, 13,
ax_anim 2, 0, 152, 0, -12, 0, -12,
ax_anim 3, 0, 152, 0, 12, 0, 12,
ax_anim 2, 0, 152, 0, -10, 0, -10,
ax_anim 2, 0, 152, 0, 10, 0, 10,
ax_anim 2, 0, 152, 0, -6, 0, -6,
ax_anim 2, 0, 152, 0, 6, 0, 6,
ax_anim 2, 0, 152, 0, 0, 0, 0,
ax_anim_terminator
sLuvdiscAnims_10_8:
ax_anim 2, 0, 153, 0, 0, 0, 0,
ax_anim 2, 0, 153, -6, -6, -6, -6,
ax_anim 2, 0, 153, 6, 6, 6, 6,
ax_anim 2, 0, 153, -10, -10, -10, -10,
ax_anim 2, 0, 153, 10, 10, 10, 10,
ax_anim 2, 0, 153, -12, -12, -12, -12,
ax_anim 3, 0, 153, 12, 12, 12, 12,
ax_anim 3, 0, 153, -13, -13, -13, -13,
ax_anim 3, 0, 153, 13, 13, 13, 13,
ax_anim 2, 0, 153, -12, -12, -12, -12,
ax_anim 3, 0, 153, 12, 12, 12, 12,
ax_anim 2, 0, 153, -10, -10, -10, -10,
ax_anim 2, 0, 153, 10, 10, 10, 10,
ax_anim 2, 0, 153, -6, -6, -6, -6,
ax_anim 2, 0, 153, 6, 6, 6, 6,
ax_anim 2, 0, 153, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sLuvdiscAnims_11_1:
ax_anim 2, 0, 154, 0, 0, 0, 0,
ax_anim 1, 0, 155, 0, -10, 0, 0,
ax_anim 2, 0, 155, 0, -16, 0, 0,
ax_anim 3, 0, 155, 0, -20, 0, 0,
ax_anim 4, 0, 155, 0, -21, 0, 0,
ax_anim 4, 0, 154, 0, -22, 0, 0,
ax_anim 3, 0, 156, 0, -21, 0, 0,
ax_anim 2, 0, 156, 0, -15, 0, 0,
ax_anim 1, 0, 156, 0, -10, 0, 0,
ax_anim 2, 2, 156, 0, 3, 0, 0,
ax_anim_terminator
sLuvdiscAnims_11_2:
ax_anim 2, 0, 157, 0, 0, 0, 0,
ax_anim 1, 0, 158, 0, -10, 0, 0,
ax_anim 2, 0, 158, 0, -16, 0, 0,
ax_anim 3, 0, 158, 0, -20, 0, 0,
ax_anim 4, 0, 158, 0, -21, 0, 0,
ax_anim 4, 0, 157, 0, -23, 0, 0,
ax_anim 3, 0, 159, 0, -23, 0, 0,
ax_anim 2, 0, 159, 0, -15, 0, 0,
ax_anim 1, 0, 159, 0, -9, 0, 0,
ax_anim 2, 2, 159, 0, 4, 0, 0,
ax_anim_terminator
sLuvdiscAnims_11_3:
ax_anim 2, 0, 160, 0, 0, 0, 0,
ax_anim 1, 0, 161, 0, -10, 0, 0,
ax_anim 2, 0, 161, 0, -16, 0, 0,
ax_anim 3, 0, 161, 0, -20, 0, 0,
ax_anim 4, 0, 161, 0, -21, 0, 0,
ax_anim 4, 0, 160, 0, -23, 0, 0,
ax_anim 3, 0, 162, 0, -22, 0, 0,
ax_anim 2, 0, 162, 0, -16, 0, 0,
ax_anim 1, 0, 162, 0, -10, 0, 0,
ax_anim 2, 2, 162, 0, 4, 0, 0,
ax_anim_terminator
sLuvdiscAnims_11_4:
ax_anim 2, 0, 163, 0, 0, 0, 0,
ax_anim 1, 0, 164, 0, -10, 0, 0,
ax_anim 2, 0, 164, 0, -16, 0, 0,
ax_anim 3, 0, 164, 0, -20, 0, 0,
ax_anim 4, 0, 164, 0, -21, 0, 0,
ax_anim 4, 0, 163, 0, -22, 0, 0,
ax_anim 3, 0, 165, 0, -21, 0, 0,
ax_anim 2, 0, 165, 0, -15, 0, 0,
ax_anim 1, 0, 165, 0, -9, 0, 0,
ax_anim 2, 2, 165, 0, 3, 0, 0,
ax_anim_terminator
sLuvdiscAnims_11_5:
ax_anim 2, 0, 166, 0, 0, 0, 0,
ax_anim 1, 0, 167, 0, -10, 0, 0,
ax_anim 2, 0, 167, 0, -16, 0, 0,
ax_anim 3, 0, 167, 0, -20, 0, 0,
ax_anim 4, 0, 167, 0, -21, 0, 0,
ax_anim 4, 0, 166, 0, -23, 0, 0,
ax_anim 3, 0, 168, 0, -22, 0, 0,
ax_anim 2, 0, 168, 0, -15, 0, 0,
ax_anim 1, 0, 168, 0, -9, 0, 0,
ax_anim 2, 2, 168, 0, 3, 0, 0,
ax_anim_terminator
sLuvdiscAnims_11_6:
ax_anim 2, 0, 169, 0, 0, 0, 0,
ax_anim 1, 0, 170, 0, -10, 0, 0,
ax_anim 2, 0, 170, 0, -16, 0, 0,
ax_anim 3, 0, 170, 0, -20, 0, 0,
ax_anim 4, 0, 170, 0, -21, 0, 0,
ax_anim 4, 0, 169, 0, -22, 0, 0,
ax_anim 3, 0, 171, 0, -21, 0, 0,
ax_anim 2, 0, 171, 0, -17, 0, 0,
ax_anim 1, 0, 171, 0, -9, 0, 0,
ax_anim 2, 2, 171, 0, 3, 0, 0,
ax_anim_terminator
sLuvdiscAnims_11_7:
ax_anim 2, 0, 172, 0, 0, 0, 0,
ax_anim 1, 0, 173, 0, -10, 0, 0,
ax_anim 2, 0, 173, 0, -16, 0, 0,
ax_anim 3, 0, 173, 0, -20, 0, 0,
ax_anim 4, 0, 173, 0, -21, 0, 0,
ax_anim 4, 0, 172, 0, -23, 0, 0,
ax_anim 3, 0, 174, 0, -22, 0, 0,
ax_anim 2, 0, 174, 0, -16, 0, 0,
ax_anim 1, 0, 174, 0, -10, 0, 0,
ax_anim 2, 2, 174, 0, 4, 0, 0,
ax_anim_terminator
sLuvdiscAnims_11_8:
ax_anim 2, 0, 175, 0, 0, 0, 0,
ax_anim 1, 0, 176, 0, -10, 0, 0,
ax_anim 2, 0, 176, 0, -16, 0, 0,
ax_anim 3, 0, 176, 0, -20, 0, 0,
ax_anim 4, 0, 176, 0, -21, 0, 0,
ax_anim 4, 0, 175, 0, -23, 0, 0,
ax_anim 3, 0, 177, 0, -23, 0, 0,
ax_anim 2, 0, 177, 0, -15, 0, 0,
ax_anim 1, 0, 177, 0, -9, 0, 0,
ax_anim 2, 2, 177, 0, 4, 0, 0,
ax_anim_terminator
.align 2
sLuvdiscAnims_12_1:
ax_anim 2, 0, 178, 1, 0, 1, 0,
ax_anim 2, 0, 178, 0, 0, 0, 0,
ax_anim 2, 0, 178, 1, 0, 1, 0,
ax_anim 2, 0, 178, 0, 0, 0, 0,
ax_anim 2, 0, 178, 1, 0, 1, 0,
ax_anim 2, 2, 178, 0, 0, 0, 0,
ax_anim 2, 0, 178, 1, 0, 1, 0,
ax_anim 2, 0, 178, 0, 0, 0, 0,
ax_anim 2, 0, 178, 1, 0, 1, 0,
ax_anim 2, 1, 178, 0, 0, 0, 0,
ax_anim_terminator
sLuvdiscAnims_12_2:
ax_anim 2, 0, 185, 1, -1, 1, -1,
ax_anim 2, 0, 185, 0, 0, 0, 0,
ax_anim 2, 0, 185, 1, -1, 1, -1,
ax_anim 2, 0, 185, 0, 0, 0, 0,
ax_anim 2, 0, 185, 1, -1, 1, -1,
ax_anim 2, 2, 185, 0, 0, 0, 0,
ax_anim 2, 0, 185, 1, -1, 1, -1,
ax_anim 2, 0, 185, 0, 0, 0, 0,
ax_anim 2, 0, 185, 1, -1, 1, -1,
ax_anim 2, 1, 185, 0, 0, 0, 0,
ax_anim_terminator
sLuvdiscAnims_12_3:
ax_anim 2, 0, 184, 0, -1, 0, -1,
ax_anim 2, 0, 184, 0, 0, 0, 0,
ax_anim 2, 0, 184, 0, -1, 0, -1,
ax_anim 2, 0, 184, 0, 0, 0, 0,
ax_anim 2, 0, 184, 0, -1, 0, -1,
ax_anim 2, 2, 184, 0, 0, 0, 0,
ax_anim 2, 0, 184, 0, -1, 0, -1,
ax_anim 2, 0, 184, 0, 0, 0, 0,
ax_anim 2, 0, 184, 0, -1, 0, -1,
ax_anim 2, 1, 184, 0, 0, 0, 0,
ax_anim_terminator
sLuvdiscAnims_12_4:
ax_anim 2, 0, 183, -1, -1, -1, -1,
ax_anim 2, 0, 183, 0, 0, 0, 0,
ax_anim 2, 0, 183, -1, -1, -1, -1,
ax_anim 2, 0, 183, 0, 0, 0, 0,
ax_anim 2, 0, 183, -1, -1, -1, -1,
ax_anim 2, 2, 183, 0, 0, 0, 0,
ax_anim 2, 0, 183, -1, -1, -1, -1,
ax_anim 2, 0, 183, 0, 0, 0, 0,
ax_anim 2, 0, 183, -1, -1, -1, -1,
ax_anim 2, 1, 183, 0, 0, 0, 0,
ax_anim_terminator
sLuvdiscAnims_12_5:
ax_anim 2, 0, 182, 1, 0, 1, 0,
ax_anim 2, 0, 182, 0, 0, 0, 0,
ax_anim 2, 0, 182, 1, 0, 1, 0,
ax_anim 2, 0, 182, 0, 0, 0, 0,
ax_anim 2, 0, 182, 1, 0, 1, 0,
ax_anim 2, 2, 182, 0, 0, 0, 0,
ax_anim 2, 0, 182, 1, 0, 1, 0,
ax_anim 2, 0, 182, 0, 0, 0, 0,
ax_anim 2, 0, 182, 1, 0, 1, 0,
ax_anim 2, 1, 182, 0, 0, 0, 0,
ax_anim_terminator
sLuvdiscAnims_12_6:
ax_anim 2, 0, 181, 1, -1, 1, -1,
ax_anim 2, 0, 181, 0, 0, 0, 0,
ax_anim 2, 0, 181, 1, -1, 1, -1,
ax_anim 2, 0, 181, 0, 0, 0, 0,
ax_anim 2, 0, 181, 1, -1, 1, -1,
ax_anim 2, 2, 181, 0, 0, 0, 0,
ax_anim 2, 0, 181, 1, -1, 1, -1,
ax_anim 2, 0, 181, 0, 0, 0, 0,
ax_anim 2, 0, 181, 1, -1, 1, -1,
ax_anim 2, 1, 181, 0, 0, 0, 0,
ax_anim_terminator
sLuvdiscAnims_12_7:
ax_anim 2, 0, 180, 0, -1, 0, -1,
ax_anim 2, 0, 180, 0, 0, 0, 0,
ax_anim 2, 0, 180, 0, -1, 0, -1,
ax_anim 2, 0, 180, 0, 0, 0, 0,
ax_anim 2, 0, 180, 0, -1, 0, -1,
ax_anim 2, 2, 180, 0, 0, 0, 0,
ax_anim 2, 0, 180, 0, -1, 0, -1,
ax_anim 2, 0, 180, 0, 0, 0, 0,
ax_anim 2, 0, 180, 0, -1, 0, -1,
ax_anim 2, 1, 180, 0, 0, 0, 0,
ax_anim_terminator
sLuvdiscAnims_12_8:
ax_anim 2, 0, 179, -1, -1, -1, -1,
ax_anim 2, 0, 179, 0, 0, 0, 0,
ax_anim 2, 0, 179, -1, -1, -1, -1,
ax_anim 2, 0, 179, 0, 0, 0, 0,
ax_anim 2, 0, 179, -1, -1, -1, -1,
ax_anim 2, 2, 179, 0, 0, 0, 0,
ax_anim 2, 0, 179, -1, -1, -1, -1,
ax_anim 2, 0, 179, 0, 0, 0, 0,
ax_anim 2, 0, 179, -1, -1, -1, -1,
ax_anim 2, 1, 179, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sLuvdiscAnims_13_1:
ax_anim 2, 0, 186, 0, 0, 0, 0,
ax_anim 2, 0, 187, 0, 0, 0, 0,
ax_anim 2, 0, 188, 0, 0, 0, 0,
ax_anim 2, 0, 189, 0, 0, 0, 0,
ax_anim 2, 0, 190, 0, 0, 0, 0,
ax_anim 2, 0, 191, 0, 0, 0, 0,
ax_anim 2, 0, 192, 0, 0, 0, 0,
ax_anim 2, 0, 193, 0, 0, 0, 0,
ax_anim 2, 2, 186, 0, 0, 0, 0,
ax_anim_terminator
sLuvdiscAnims_13_2:
ax_anim 2, 0, 193, 0, 0, 0, 0,
ax_anim 2, 0, 186, 0, 0, 0, 0,
ax_anim 2, 0, 187, 0, 0, 0, 0,
ax_anim 2, 0, 188, 0, 0, 0, 0,
ax_anim 2, 0, 189, 0, 0, 0, 0,
ax_anim 2, 0, 190, 0, 0, 0, 0,
ax_anim 2, 0, 191, 0, 0, 0, 0,
ax_anim 2, 0, 192, 0, 0, 0, 0,
ax_anim 2, 2, 193, 0, 0, 0, 0,
ax_anim_terminator
sLuvdiscAnims_13_3:
ax_anim 2, 0, 192, 0, 0, 0, 0,
ax_anim 2, 0, 193, 0, 0, 0, 0,
ax_anim 2, 0, 186, 0, 0, 0, 0,
ax_anim 2, 0, 187, 0, 0, 0, 0,
ax_anim 2, 0, 188, 0, 0, 0, 0,
ax_anim 2, 0, 189, 0, 0, 0, 0,
ax_anim 2, 0, 190, 0, 0, 0, 0,
ax_anim 2, 0, 191, 0, 0, 0, 0,
ax_anim 2, 2, 192, 0, 0, 0, 0,
ax_anim_terminator
sLuvdiscAnims_13_4:
ax_anim 2, 0, 191, 0, 0, 0, 0,
ax_anim 2, 0, 192, 0, 0, 0, 0,
ax_anim 2, 0, 193, 0, 0, 0, 0,
ax_anim 2, 0, 186, 0, 0, 0, 0,
ax_anim 2, 0, 187, 0, 0, 0, 0,
ax_anim 2, 0, 188, 0, 0, 0, 0,
ax_anim 2, 0, 189, 0, 0, 0, 0,
ax_anim 2, 0, 190, 0, 0, 0, 0,
ax_anim 2, 2, 191, 0, 0, 0, 0,
ax_anim_terminator
sLuvdiscAnims_13_5:
ax_anim 2, 0, 190, 0, 0, 0, 0,
ax_anim 2, 0, 191, 0, 0, 0, 0,
ax_anim 2, 0, 192, 0, 0, 0, 0,
ax_anim 2, 0, 193, 0, 0, 0, 0,
ax_anim 2, 0, 186, 0, 0, 0, 0,
ax_anim 2, 0, 187, 0, 0, 0, 0,
ax_anim 2, 0, 188, 0, 0, 0, 0,
ax_anim 2, 0, 189, 0, 0, 0, 0,
ax_anim 2, 2, 190, 0, 0, 0, 0,
ax_anim_terminator
sLuvdiscAnims_13_6:
ax_anim 2, 0, 189, 0, 0, 0, 0,
ax_anim 2, 0, 190, 0, 0, 0, 0,
ax_anim 2, 0, 191, 0, 0, 0, 0,
ax_anim 2, 0, 192, 0, 0, 0, 0,
ax_anim 2, 0, 193, 0, 0, 0, 0,
ax_anim 2, 0, 186, 0, 0, 0, 0,
ax_anim 2, 0, 187, 0, 0, 0, 0,
ax_anim 2, 0, 188, 0, 0, 0, 0,
ax_anim 2, 2, 189, 0, 0, 0, 0,
ax_anim_terminator
sLuvdiscAnims_13_7:
ax_anim 2, 0, 188, 0, 0, 0, 0,
ax_anim 2, 0, 189, 0, 0, 0, 0,
ax_anim 2, 0, 190, 0, 0, 0, 0,
ax_anim 2, 0, 191, 0, 0, 0, 0,
ax_anim 2, 0, 192, 0, 0, 0, 0,
ax_anim 2, 0, 193, 0, 0, 0, 0,
ax_anim 2, 0, 186, 0, 0, 0, 0,
ax_anim 2, 0, 187, 0, 0, 0, 0,
ax_anim 2, 2, 188, 0, 0, 0, 0,
ax_anim_terminator
sLuvdiscAnims_13_8:
ax_anim 2, 0, 187, 0, 0, 0, 0,
ax_anim 2, 0, 188, 0, 0, 0, 0,
ax_anim 2, 0, 189, 0, 0, 0, 0,
ax_anim 2, 0, 190, 0, 0, 0, 0,
ax_anim 2, 0, 191, 0, 0, 0, 0,
ax_anim 2, 0, 192, 0, 0, 0, 0,
ax_anim 2, 0, 193, 0, 0, 0, 0,
ax_anim 2, 0, 186, 0, 0, 0, 0,
ax_anim 2, 2, 187, 0, 0, 0, 0,
ax_anim_terminator
sLuvdiscGfx1:
.incbin "baserom.gba", 0x15405F8, 0x100
sLuvdiscSprites1:
ax_sprite sLuvdiscGfx1, 0x100
ax_sprite_terminator
sLuvdiscGfx2:
.incbin "baserom.gba", 0x1540708, 0x100
sLuvdiscSprites2:
ax_sprite sLuvdiscGfx2, 0x100
ax_sprite_terminator
sLuvdiscGfx3:
.incbin "baserom.gba", 0x1540818, 0x100
sLuvdiscSprites3:
ax_sprite sLuvdiscGfx3, 0x100
ax_sprite_terminator
sLuvdiscGfx4:
.incbin "baserom.gba", 0x1540928, 0x100
sLuvdiscSprites4:
ax_sprite sLuvdiscGfx4, 0x100
ax_sprite_terminator
sLuvdiscGfx5:
.incbin "baserom.gba", 0x1540A38, 0x100
sLuvdiscSprites5:
ax_sprite sLuvdiscGfx5, 0x100
ax_sprite_terminator
sLuvdiscGfx6:
.incbin "baserom.gba", 0x1540B48, 0x100
sLuvdiscSprites6:
ax_sprite sLuvdiscGfx6, 0x100
ax_sprite_terminator
sLuvdiscGfx7:
.incbin "baserom.gba", 0x1540C58, 0x200
sLuvdiscSprites7:
ax_sprite sLuvdiscGfx7, 0x200
ax_sprite_terminator
sLuvdiscGfx8:
.incbin "baserom.gba", 0x1540E68, 0x200
sLuvdiscSprites8:
ax_sprite sLuvdiscGfx8, 0x200
ax_sprite_terminator
sLuvdiscGfx9:
.incbin "baserom.gba", 0x1541078, 0x200
sLuvdiscSprites9:
ax_sprite sLuvdiscGfx9, 0x200
ax_sprite_terminator
sLuvdiscGfx10:
.incbin "baserom.gba", 0x1541288, 0x100
sLuvdiscSprites10:
ax_sprite sLuvdiscGfx10, 0x100
ax_sprite_terminator
sLuvdiscGfx11:
.incbin "baserom.gba", 0x1541398, 0x100
sLuvdiscSprites11:
ax_sprite sLuvdiscGfx11, 0x100
ax_sprite_terminator
sLuvdiscGfx12:
.incbin "baserom.gba", 0x15414A8, 0x100
sLuvdiscSprites12:
ax_sprite sLuvdiscGfx12, 0x100
ax_sprite_terminator
sLuvdiscGfx13:
.incbin "baserom.gba", 0x15415B8, 0x100
sLuvdiscSprites13:
ax_sprite sLuvdiscGfx13, 0x100
ax_sprite_terminator
sLuvdiscGfx14:
.incbin "baserom.gba", 0x15416C8, 0x100
sLuvdiscSprites14:
ax_sprite sLuvdiscGfx14, 0x100
ax_sprite_terminator
sLuvdiscGfx15:
.incbin "baserom.gba", 0x15417D8, 0x100
sLuvdiscSprites15:
ax_sprite sLuvdiscGfx15, 0x100
ax_sprite_terminator
sLuvdiscGfx16:
.incbin "baserom.gba", 0x15418E8, 0xC0
sLuvdiscSprites16:
ax_sprite sLuvdiscGfx16, 0xc0
ax_sprite 0, 0x40
ax_sprite_terminator
sLuvdiscGfx17:
.incbin "baserom.gba", 0x15419C0, 0xC0
sLuvdiscSprites17:
ax_sprite sLuvdiscGfx17, 0xc0
ax_sprite 0, 0x40
ax_sprite_terminator
sLuvdiscGfx18:
.incbin "baserom.gba", 0x1541A98, 0xC0
sLuvdiscSprites18:
ax_sprite sLuvdiscGfx18, 0xc0
ax_sprite 0, 0x40
ax_sprite_terminator
sLuvdiscGfx19:
.incbin "baserom.gba", 0x1541B70, 0x80
sLuvdiscSprites19:
ax_sprite sLuvdiscGfx19, 0x80
ax_sprite_terminator
sLuvdiscGfx20:
.incbin "baserom.gba", 0x1541C00, 0x20
sLuvdiscSprites20:
ax_sprite sLuvdiscGfx20, 0x20
ax_sprite_terminator
sLuvdiscGfx21:
.incbin "baserom.gba", 0x1541C30, 0xC0
sLuvdiscSprites21:
ax_sprite sLuvdiscGfx21, 0xc0
ax_sprite 0, 0x40
ax_sprite_terminator
sLuvdiscGfx22:
.incbin "baserom.gba", 0x1541D08, 0x20
sLuvdiscSprites22:
ax_sprite sLuvdiscGfx22, 0x20
ax_sprite_terminator
sLuvdiscGfx23:
.incbin "baserom.gba", 0x1541D38, 0xC0
sLuvdiscSprites23:
ax_sprite sLuvdiscGfx23, 0xc0
ax_sprite 0, 0x40
ax_sprite_terminator
sLuvdiscGfx24:
.incbin "baserom.gba", 0x1541E10, 0x20
sLuvdiscSprites24:
ax_sprite sLuvdiscGfx24, 0x20
ax_sprite_terminator
sLuvdiscGfx25:
.incbin "baserom.gba", 0x1541E40, 0xC0
sLuvdiscSprites25:
ax_sprite sLuvdiscGfx25, 0xc0
ax_sprite 0, 0x40
ax_sprite_terminator
sLuvdiscGfx26:
.incbin "baserom.gba", 0x1541F18, 0x80
sLuvdiscSprites26:
ax_sprite sLuvdiscGfx26, 0x80
ax_sprite_terminator
sLuvdiscGfx27:
.incbin "baserom.gba", 0x1541FA8, 0x20
sLuvdiscSprites27:
ax_sprite sLuvdiscGfx27, 0x20
ax_sprite_terminator
sLuvdiscGfx28:
.incbin "baserom.gba", 0x1541FD8, 0xC0
sLuvdiscSprites28:
ax_sprite sLuvdiscGfx28, 0xc0
ax_sprite 0, 0x40
ax_sprite_terminator
sLuvdiscGfx29:
.incbin "baserom.gba", 0x15420B0, 0xC0
sLuvdiscSprites29:
ax_sprite sLuvdiscGfx29, 0xc0
ax_sprite 0, 0x40
ax_sprite_terminator
sLuvdiscGfx30:
.incbin "baserom.gba", 0x1542188, 0x100
sLuvdiscSprites30:
ax_sprite sLuvdiscGfx30, 0x100
ax_sprite_terminator
sLuvdiscGfx31:
.incbin "baserom.gba", 0x1542298, 0x100
sLuvdiscSprites31:
ax_sprite sLuvdiscGfx31, 0x100
ax_sprite_terminator
sLuvdiscGfx32:
.incbin "baserom.gba", 0x15423A8, 0x200
sLuvdiscSprites32:
ax_sprite sLuvdiscGfx32, 0x200
ax_sprite_terminator
sLuvdiscGfx33:
.incbin "baserom.gba", 0x15425B8, 0x200
sLuvdiscSprites33:
ax_sprite sLuvdiscGfx33, 0x200
ax_sprite_terminator
sLuvdiscGfx34:
.incbin "baserom.gba", 0x15427C8, 0x200
sLuvdiscSprites34:
ax_sprite sLuvdiscGfx34, 0x200
ax_sprite_terminator
sLuvdiscGfx35:
.incbin "baserom.gba", 0x15429D8, 0x200
sLuvdiscSprites35:
ax_sprite sLuvdiscGfx35, 0x200
ax_sprite_terminator
sLuvdiscGfx36:
.incbin "baserom.gba", 0x1542BE8, 0x200
sLuvdiscSprites36:
ax_sprite sLuvdiscGfx36, 0x200
ax_sprite_terminator
sAxPosesLuvdisc:
.4byte sLuvdiscPose1
.4byte sLuvdiscPose2
.4byte sLuvdiscPose3
.4byte sLuvdiscPose4
.4byte sLuvdiscPose5
.4byte sLuvdiscPose6
.4byte sLuvdiscPose7
.4byte sLuvdiscPose8
.4byte sLuvdiscPose9
.4byte sLuvdiscPose10
.4byte sLuvdiscPose11
.4byte sLuvdiscPose12
.4byte sLuvdiscPose13
.4byte sLuvdiscPose14
.4byte sLuvdiscPose15
.4byte sLuvdiscPose16
.4byte sLuvdiscPose17
.4byte sLuvdiscPose18
.4byte sLuvdiscPose19
.4byte sLuvdiscPose20
.4byte sLuvdiscPose21
.4byte sLuvdiscPose22
.4byte sLuvdiscPose23
.4byte sLuvdiscPose24
.4byte sLuvdiscPose25
.4byte sLuvdiscPose26
.4byte sLuvdiscPose27
.4byte sLuvdiscPose28
.4byte sLuvdiscPose29
.4byte sLuvdiscPose30
.4byte sLuvdiscPose31
.4byte sLuvdiscPose32
.4byte sLuvdiscPose33
.4byte sLuvdiscPose34
.4byte sLuvdiscPose35
.4byte sLuvdiscPose36
.4byte sLuvdiscPose37
.4byte sLuvdiscPose38
.4byte sLuvdiscPose39
.4byte sLuvdiscPose40
.4byte sLuvdiscPose41
.4byte sLuvdiscPose42
.4byte sLuvdiscPose43
.4byte sLuvdiscPose44
.4byte sLuvdiscPose45
.4byte sLuvdiscPose46
.4byte sLuvdiscPose47
.4byte sLuvdiscPose48
.4byte sLuvdiscPose49
.4byte sLuvdiscPose50
.4byte sLuvdiscPose51
.4byte sLuvdiscPose52
.4byte sLuvdiscPose53
.4byte sLuvdiscPose54
.4byte sLuvdiscPose55
.4byte sLuvdiscPose56
.4byte sLuvdiscPose57
.4byte sLuvdiscPose58
.4byte sLuvdiscPose59
.4byte sLuvdiscPose60
.4byte sLuvdiscPose61
.4byte sLuvdiscPose62
.4byte sLuvdiscPose63
.4byte sLuvdiscPose64
.4byte sLuvdiscPose65
.4byte sLuvdiscPose66
.4byte sLuvdiscPose67
.4byte sLuvdiscPose68
.4byte sLuvdiscPose69
.4byte sLuvdiscPose70
.4byte sLuvdiscPose71
.4byte sLuvdiscPose72
.4byte sLuvdiscPose73
.4byte sLuvdiscPose74
.4byte sLuvdiscPose75
.4byte sLuvdiscPose76
.4byte sLuvdiscPose77
.4byte sLuvdiscPose78
.4byte sLuvdiscPose79
.4byte sLuvdiscPose80
.4byte sLuvdiscPose81
.4byte sLuvdiscPose82
.4byte sLuvdiscPose83
.4byte sLuvdiscPose84
.4byte sLuvdiscPose85
.4byte sLuvdiscPose86
.4byte sLuvdiscPose87
.4byte sLuvdiscPose88
.4byte sLuvdiscPose89
.4byte sLuvdiscPose90
.4byte sLuvdiscPose91
.4byte sLuvdiscPose92
.4byte sLuvdiscPose93
.4byte sLuvdiscPose94
.4byte sLuvdiscPose95
.4byte sLuvdiscPose96
.4byte sLuvdiscPose97
.4byte sLuvdiscPose98
.4byte sLuvdiscPose99
.4byte sLuvdiscPose100
.4byte sLuvdiscPose101
.4byte sLuvdiscPose102
.4byte sLuvdiscPose103
.4byte sLuvdiscPose104
.4byte sLuvdiscPose105
.4byte sLuvdiscPose106
.4byte sLuvdiscPose107
.4byte sLuvdiscPose108
.4byte sLuvdiscPose109
.4byte sLuvdiscPose110
.4byte sLuvdiscPose111
.4byte sLuvdiscPose112
.4byte sLuvdiscPose113
.4byte sLuvdiscPose114
.4byte sLuvdiscPose115
.4byte sLuvdiscPose116
.4byte sLuvdiscPose117
.4byte sLuvdiscPose118
.4byte sLuvdiscPose119
.4byte sLuvdiscPose120
.4byte sLuvdiscPose121
.4byte sLuvdiscPose122
.4byte sLuvdiscPose123
.4byte sLuvdiscPose124
.4byte sLuvdiscPose125
.4byte sLuvdiscPose126
.4byte sLuvdiscPose127
.4byte sLuvdiscPose128
.4byte sLuvdiscPose129
.4byte sLuvdiscPose130
.4byte sLuvdiscPose131
.4byte sLuvdiscPose132
.4byte sLuvdiscPose133
.4byte sLuvdiscPose134
.4byte sLuvdiscPose135
.4byte sLuvdiscPose136
.4byte sLuvdiscPose137
.4byte sLuvdiscPose138
.4byte sLuvdiscPose139
.4byte sLuvdiscPose140
.4byte sLuvdiscPose141
.4byte sLuvdiscPose142
.4byte sLuvdiscPose143
.4byte sLuvdiscPose144
.4byte sLuvdiscPose145
.4byte sLuvdiscPose146
.4byte sLuvdiscPose147
.4byte sLuvdiscPose148
.4byte sLuvdiscPose149
.4byte sLuvdiscPose150
.4byte sLuvdiscPose151
.4byte sLuvdiscPose152
.4byte sLuvdiscPose153
.4byte sLuvdiscPose154
.4byte sLuvdiscPose155
.4byte sLuvdiscPose156
.4byte sLuvdiscPose157
.4byte sLuvdiscPose158
.4byte sLuvdiscPose159
.4byte sLuvdiscPose160
.4byte sLuvdiscPose161
.4byte sLuvdiscPose162
.4byte sLuvdiscPose163
.4byte sLuvdiscPose164
.4byte sLuvdiscPose165
.4byte sLuvdiscPose166
.4byte sLuvdiscPose167
.4byte sLuvdiscPose168
.4byte sLuvdiscPose169
.4byte sLuvdiscPose170
.4byte sLuvdiscPose171
.4byte sLuvdiscPose172
.4byte sLuvdiscPose173
.4byte sLuvdiscPose174
.4byte sLuvdiscPose175
.4byte sLuvdiscPose176
.4byte sLuvdiscPose177
.4byte sLuvdiscPose178
.4byte sLuvdiscPose179
.4byte sLuvdiscPose180
.4byte sLuvdiscPose181
.4byte sLuvdiscPose182
.4byte sLuvdiscPose183
.4byte sLuvdiscPose184
.4byte sLuvdiscPose185
.4byte sLuvdiscPose186
.4byte sLuvdiscPose187
.4byte sLuvdiscPose188
.4byte sLuvdiscPose189
.4byte sLuvdiscPose190
.4byte sLuvdiscPose191
.4byte sLuvdiscPose192
.4byte sLuvdiscPose193
.4byte sLuvdiscPose194
sAxPositionsLuvdisc:
.2byte    0,   -8, 	  -4,  -13, 	   3,  -13, 	  -1,  -13
.2byte    1,   -8, 	  -3,  -13, 	   2,  -15, 	  -1,  -13
.2byte   -2,   -8, 	  -3,  -14, 	   3,  -13, 	   0,  -13
.2byte    6,  -10, 	   3,  -15, 	   0,  -13, 	   0,  -12
.2byte    5,  -10, 	   2,  -16, 	  -1,  -13, 	  -1,  -12
.2byte    7,  -10, 	   3,  -17, 	   2,  -14, 	   1,  -12
.2byte    8,  -11, 	   2,  -15, 	   0,  -14, 	   0,  -12
.2byte    8,  -11, 	   3,  -16, 	   1,  -14, 	   0,  -12
.2byte    8,  -11, 	   1,  -16, 	   2,  -14, 	   1,  -12
.2byte    4,  -14, 	  -2,  -15, 	   1,  -14, 	   0,  -12
.2byte    4,  -14, 	  -1,  -16, 	   1,  -15, 	   0,  -12
.2byte    4,  -14, 	  -1,  -16, 	   2,  -16, 	   1,  -12
.2byte   -1,  -13, 	   3,  -15, 	  -4,  -15, 	   0,  -12
.2byte    0,  -13, 	   4,  -15, 	  -3,  -15, 	   0,  -12
.2byte   -1,  -13, 	   2,  -15, 	  -5,  -16, 	  -1,  -12
.2byte   -5,  -14, 	   1,  -15, 	  -2,  -14, 	  -1,  -12
.2byte   -5,  -14, 	   0,  -16, 	  -2,  -15, 	  -1,  -12
.2byte   -5,  -14, 	   0,  -16, 	  -3,  -16, 	  -2,  -12
.2byte   -9,  -11, 	  -3,  -15, 	  -1,  -14, 	  -1,  -12
.2byte   -9,  -11, 	  -4,  -16, 	  -2,  -14, 	  -1,  -12
.2byte   -9,  -11, 	  -2,  -16, 	  -3,  -14, 	  -2,  -12
.2byte   -7,  -10, 	  -4,  -15, 	  -1,  -13, 	  -1,  -12
.2byte   -6,  -10, 	  -3,  -16, 	   0,  -13, 	   0,  -12
.2byte   -8,  -10, 	  -4,  -17, 	  -3,  -14, 	  -2,  -12
.2byte    0,   -8, 	  -4,  -13, 	   3,  -13, 	  -1,  -13
.2byte    1,   -8, 	  -3,  -13, 	   2,  -15, 	  -1,  -13
.2byte   -2,   -8, 	  -3,  -14, 	   3,  -13, 	   0,  -13
.2byte    6,  -10, 	   3,  -15, 	   0,  -13, 	   0,  -12
.2byte    5,  -10, 	   2,  -16, 	  -1,  -13, 	  -1,  -12
.2byte    7,  -10, 	   3,  -17, 	   2,  -14, 	   1,  -12
.2byte    8,  -11, 	   2,  -15, 	   0,  -14, 	   0,  -12
.2byte    8,  -11, 	   3,  -16, 	   1,  -14, 	   0,  -12
.2byte    8,  -11, 	   1,  -16, 	   2,  -14, 	   1,  -12
.2byte    4,  -14, 	  -2,  -15, 	   1,  -14, 	   0,  -12
.2byte    4,  -14, 	  -1,  -16, 	   1,  -15, 	   0,  -12
.2byte    4,  -14, 	  -1,  -16, 	   2,  -16, 	   1,  -12
.2byte   -1,  -13, 	   3,  -15, 	  -4,  -15, 	   0,  -12
.2byte    0,  -13, 	   4,  -15, 	  -3,  -15, 	   0,  -12
.2byte   -1,  -13, 	   2,  -15, 	  -5,  -16, 	  -1,  -12
.2byte   -5,  -14, 	   1,  -15, 	  -2,  -14, 	  -1,  -12
.2byte   -5,  -14, 	   0,  -16, 	  -2,  -15, 	  -1,  -12
.2byte   -5,  -14, 	   0,  -16, 	  -3,  -16, 	  -2,  -12
.2byte   -9,  -11, 	  -3,  -15, 	  -1,  -14, 	  -1,  -12
.2byte   -9,  -11, 	  -4,  -16, 	  -2,  -14, 	  -1,  -12
.2byte   -9,  -11, 	  -2,  -16, 	  -3,  -14, 	  -2,  -12
.2byte   -7,  -10, 	  -4,  -15, 	  -1,  -13, 	  -1,  -12
.2byte   -6,  -10, 	  -3,  -16, 	   0,  -13, 	   0,  -12
.2byte   -8,  -10, 	  -4,  -17, 	  -3,  -14, 	  -2,  -12
.2byte    0,   -8, 	  -4,  -13, 	   3,  -13, 	  -1,  -13
.2byte    1,   -8, 	  -3,  -13, 	   2,  -15, 	  -1,  -13
.2byte   -2,   -8, 	  -3,  -14, 	   3,  -13, 	   0,  -13
.2byte    6,  -10, 	   3,  -15, 	   0,  -13, 	   0,  -12
.2byte    5,  -10, 	   2,  -16, 	  -1,  -13, 	  -1,  -12
.2byte    7,  -10, 	   3,  -17, 	   2,  -14, 	   1,  -12
.2byte    8,  -11, 	   2,  -15, 	   0,  -14, 	   0,  -12
.2byte    8,  -11, 	   3,  -16, 	   1,  -14, 	   0,  -12
.2byte    8,  -11, 	   1,  -16, 	   2,  -14, 	   1,  -12
.2byte    4,  -14, 	  -2,  -15, 	   1,  -14, 	   0,  -12
.2byte    4,  -14, 	  -1,  -16, 	   1,  -15, 	   0,  -12
.2byte    4,  -14, 	  -1,  -16, 	   2,  -16, 	   1,  -12
.2byte   -1,  -13, 	   3,  -15, 	  -4,  -15, 	   0,  -12
.2byte    0,  -13, 	   4,  -15, 	  -3,  -15, 	   0,  -12
.2byte   -1,  -13, 	   2,  -15, 	  -5,  -16, 	  -1,  -12
.2byte   -5,  -14, 	   1,  -15, 	  -2,  -14, 	  -1,  -12
.2byte   -5,  -14, 	   0,  -16, 	  -2,  -15, 	  -1,  -12
.2byte   -5,  -14, 	   0,  -16, 	  -3,  -16, 	  -2,  -12
.2byte   -9,  -11, 	  -3,  -15, 	  -1,  -14, 	  -1,  -12
.2byte   -9,  -11, 	  -4,  -16, 	  -2,  -14, 	  -1,  -12
.2byte   -9,  -11, 	  -2,  -16, 	  -3,  -14, 	  -2,  -12
.2byte   -7,  -10, 	  -4,  -15, 	  -1,  -13, 	  -1,  -12
.2byte   -6,  -10, 	  -3,  -16, 	   0,  -13, 	   0,  -12
.2byte   -8,  -10, 	  -4,  -17, 	  -3,  -14, 	  -2,  -12
.2byte    0,   -8, 	  -4,  -13, 	   3,  -13, 	  -1,  -13
.2byte   -1,  -16, 	  -4,  -16, 	   3,  -16, 	  -1,  -12
.2byte   -1,   -5, 	  -4,  -12, 	   3,  -12, 	  -1,  -12
.2byte    6,  -10, 	   3,  -15, 	   0,  -13, 	   0,  -12
.2byte    3,  -17, 	   1,  -19, 	  -2,  -16, 	   0,  -12
.2byte    7,   -9, 	   4,  -13, 	   2,  -11, 	   0,  -10
.2byte    8,  -11, 	   2,  -15, 	   0,  -14, 	   0,  -12
.2byte    4,  -19, 	  -2,  -18, 	  -2,  -16, 	   0,  -13
.2byte    9,  -11, 	   2,  -16, 	   1,  -14, 	   0,  -11
.2byte    4,  -14, 	  -2,  -15, 	   1,  -14, 	   0,  -12
.2byte    3,  -17, 	  -3,  -16, 	   0,  -15, 	   0,  -11
.2byte    6,  -14, 	   1,  -16, 	   3,  -14, 	   0,  -11
.2byte   -1,  -13, 	   3,  -15, 	  -4,  -15, 	   0,  -12
.2byte    0,  -22, 	   3,  -16, 	  -4,  -16, 	  -1,  -14
.2byte   -1,  -17, 	   3,  -16, 	  -4,  -16, 	  -1,  -12
.2byte   -5,  -14, 	   1,  -15, 	  -2,  -14, 	  -1,  -12
.2byte   -4,  -17, 	   2,  -16, 	  -1,  -15, 	  -1,  -11
.2byte   -7,  -14, 	  -2,  -16, 	  -4,  -14, 	  -1,  -11
.2byte   -9,  -11, 	  -3,  -15, 	  -1,  -14, 	  -1,  -12
.2byte   -5,  -19, 	   1,  -18, 	   1,  -16, 	  -1,  -13
.2byte  -10,  -11, 	  -3,  -16, 	  -2,  -14, 	  -1,  -11
.2byte   -7,  -10, 	  -4,  -15, 	  -1,  -13, 	  -1,  -12
.2byte   -4,  -17, 	  -2,  -19, 	   1,  -16, 	  -1,  -12
.2byte   -8,   -9, 	  -5,  -13, 	  -3,  -11, 	  -1,  -10
.2byte    0,   -8, 	  -4,  -13, 	   3,  -13, 	  -1,  -13
.2byte   -7,  -10, 	  -4,  -15, 	  -1,  -13, 	  -1,  -12
.2byte   -9,  -11, 	  -3,  -15, 	  -1,  -14, 	  -1,  -12
.2byte   -5,  -14, 	   1,  -15, 	  -2,  -14, 	  -1,  -12
.2byte   -1,  -13, 	   3,  -15, 	  -4,  -15, 	   0,  -12
.2byte    4,  -14, 	  -2,  -15, 	   1,  -14, 	   0,  -12
.2byte    8,  -11, 	   2,  -15, 	   0,  -14, 	   0,  -12
.2byte    6,  -10, 	   3,  -15, 	   0,  -13, 	   0,  -12
.2byte   -9,   -7, 	  -4,   -8, 	  -4,  -12, 	   0,  -10
.2byte   -9,   -8, 	  -4,   -9, 	  -4,  -13, 	   0,  -12
.2byte   -8,  -14, 	  -4,  -17, 	  -2,  -15, 	  -1,  -14
.2byte    6,  -14, 	  -1,  -17, 	   2,  -17, 	   1,  -13
.2byte    1,  -16, 	  -3,  -16, 	   3,  -16, 	   0,  -12
.2byte   -6,  -14, 	  -1,  -15, 	   2,  -16, 	  -1,  -13
.2byte    8,  -16, 	   0,  -15, 	  -1,  -17, 	  -1,  -12
.2byte    5,  -14, 	   0,  -15, 	  -3,  -16, 	   0,  -13
.2byte   -2,  -16, 	   2,  -16, 	  -4,  -16, 	  -1,  -12
.2byte   -7,  -14, 	   0,  -17, 	  -3,  -17, 	  -2,  -13
.2byte    0,   -8, 	  -4,  -13, 	   3,  -13, 	  -1,  -13
.2byte    1,   -8, 	  -3,  -13, 	   2,  -15, 	  -1,  -13
.2byte   -2,   -8, 	  -3,  -14, 	   3,  -13, 	   0,  -13
.2byte    6,  -10, 	   3,  -15, 	   0,  -13, 	   0,  -12
.2byte    5,  -10, 	   2,  -16, 	  -1,  -13, 	  -1,  -12
.2byte    7,  -10, 	   3,  -17, 	   2,  -14, 	   1,  -12
.2byte    8,  -11, 	   2,  -15, 	   0,  -14, 	   0,  -12
.2byte    8,  -11, 	   3,  -16, 	   1,  -14, 	   0,  -12
.2byte    8,  -11, 	   1,  -16, 	   2,  -14, 	   1,  -12
.2byte    4,  -14, 	  -2,  -15, 	   1,  -14, 	   0,  -12
.2byte    4,  -14, 	  -1,  -16, 	   1,  -15, 	   0,  -12
.2byte    4,  -14, 	  -1,  -16, 	   2,  -16, 	   1,  -12
.2byte   -1,  -13, 	   3,  -15, 	  -4,  -15, 	   0,  -12
.2byte    0,  -13, 	   4,  -15, 	  -3,  -15, 	   0,  -12
.2byte   -1,  -13, 	   2,  -15, 	  -5,  -16, 	  -1,  -12
.2byte   -5,  -14, 	   1,  -15, 	  -2,  -14, 	  -1,  -12
.2byte   -5,  -14, 	   0,  -16, 	  -2,  -15, 	  -1,  -12
.2byte   -5,  -14, 	   0,  -16, 	  -3,  -16, 	  -2,  -12
.2byte   -9,  -11, 	  -3,  -15, 	  -1,  -14, 	  -1,  -12
.2byte   -9,  -11, 	  -4,  -16, 	  -2,  -14, 	  -1,  -12
.2byte   -9,  -11, 	  -2,  -16, 	  -3,  -14, 	  -2,  -12
.2byte   -7,  -10, 	  -4,  -15, 	  -1,  -13, 	  -1,  -12
.2byte   -6,  -10, 	  -3,  -16, 	   0,  -13, 	   0,  -12
.2byte   -8,  -10, 	  -4,  -17, 	  -3,  -14, 	  -2,  -12
.2byte   -1,   -5, 	  -4,  -12, 	   3,  -12, 	  -1,  -12
.2byte   -8,  -10, 	  -5,  -14, 	  -3,  -12, 	  -1,  -11
.2byte  -10,  -11, 	  -3,  -16, 	  -2,  -14, 	  -1,  -11
.2byte   -7,  -14, 	  -2,  -16, 	  -4,  -14, 	  -1,  -11
.2byte   -1,  -16, 	   3,  -15, 	  -4,  -15, 	  -1,  -11
.2byte    6,  -14, 	   1,  -16, 	   3,  -14, 	   0,  -11
.2byte    9,  -11, 	   2,  -16, 	   1,  -14, 	   0,  -11
.2byte    7,  -10, 	   4,  -14, 	   2,  -12, 	   0,  -11
.2byte   -1,  -16, 	  -4,  -16, 	   3,  -16, 	  -1,  -12
.2byte    4,  -17, 	   2,  -19, 	  -1,  -16, 	   1,  -12
.2byte    5,  -19, 	  -1,  -18, 	  -1,  -16, 	   1,  -13
.2byte    4,  -18, 	  -2,  -17, 	   1,  -16, 	   1,  -12
.2byte    0,  -21, 	   3,  -15, 	  -4,  -15, 	  -1,  -13
.2byte   -5,  -18, 	   1,  -17, 	  -2,  -16, 	  -2,  -12
.2byte   -6,  -19, 	   0,  -18, 	   0,  -16, 	  -2,  -13
.2byte   -5,  -17, 	  -3,  -19, 	   0,  -16, 	  -2,  -12
.2byte    0,   -8, 	  -4,  -13, 	   3,  -13, 	  -1,  -13
.2byte   -1,  -16, 	  -4,  -16, 	   3,  -16, 	  -1,  -12
.2byte   -1,   -5, 	  -4,  -12, 	   3,  -12, 	  -1,  -12
.2byte    6,  -10, 	   3,  -15, 	   0,  -13, 	   0,  -12
.2byte    4,  -15, 	   2,  -17, 	  -1,  -14, 	   1,  -10
.2byte    7,   -9, 	   4,  -13, 	   2,  -11, 	   0,  -10
.2byte    8,  -11, 	   2,  -15, 	   0,  -14, 	   0,  -12
.2byte    5,  -19, 	  -1,  -18, 	  -1,  -16, 	   1,  -13
.2byte    9,  -11, 	   2,  -16, 	   1,  -14, 	   0,  -11
.2byte    4,  -14, 	  -2,  -15, 	   1,  -14, 	   0,  -12
.2byte    3,  -17, 	  -3,  -16, 	   0,  -15, 	   0,  -11
.2byte    7,  -14, 	   2,  -16, 	   4,  -14, 	   1,  -11
.2byte   -1,  -13, 	   3,  -15, 	  -4,  -15, 	   0,  -12
.2byte    0,  -22, 	   3,  -16, 	  -4,  -16, 	  -1,  -14
.2byte   -1,  -17, 	   3,  -16, 	  -4,  -16, 	  -1,  -12
.2byte   -5,  -14, 	   1,  -15, 	  -2,  -14, 	  -1,  -12
.2byte   -4,  -17, 	   2,  -16, 	  -1,  -15, 	  -1,  -11
.2byte   -8,  -14, 	  -3,  -16, 	  -5,  -14, 	  -2,  -11
.2byte   -9,  -11, 	  -3,  -15, 	  -1,  -14, 	  -1,  -12
.2byte   -6,  -19, 	   0,  -18, 	   0,  -16, 	  -2,  -13
.2byte  -10,  -11, 	  -3,  -16, 	  -2,  -14, 	  -1,  -11
.2byte   -7,  -10, 	  -4,  -15, 	  -1,  -13, 	  -1,  -12
.2byte   -5,  -15, 	  -3,  -17, 	   0,  -14, 	  -2,  -10
.2byte   -8,   -9, 	  -5,  -13, 	  -3,  -11, 	  -1,  -10
.2byte   -1,   -5, 	  -4,  -12, 	   3,  -12, 	  -1,  -12
.2byte   -8,  -10, 	  -5,  -14, 	  -3,  -12, 	  -1,  -11
.2byte  -10,  -11, 	  -3,  -16, 	  -2,  -14, 	  -1,  -11
.2byte   -7,  -14, 	  -2,  -16, 	  -4,  -14, 	  -1,  -11
.2byte   -1,  -16, 	   3,  -15, 	  -4,  -15, 	  -1,  -11
.2byte    6,  -14, 	   1,  -16, 	   3,  -14, 	   0,  -11
.2byte    9,  -11, 	   2,  -16, 	   1,  -14, 	   0,  -11
.2byte    7,  -10, 	   4,  -14, 	   2,  -12, 	   0,  -11
.2byte    0,   -8, 	  -4,  -13, 	   3,  -13, 	  -1,  -13
.2byte   -7,  -10, 	  -4,  -15, 	  -1,  -13, 	  -1,  -12
.2byte   -9,  -11, 	  -3,  -15, 	  -1,  -14, 	  -1,  -12
.2byte   -5,  -14, 	   1,  -15, 	  -2,  -14, 	  -1,  -12
.2byte   -1,  -13, 	   3,  -15, 	  -4,  -15, 	   0,  -12
.2byte    4,  -14, 	  -2,  -15, 	   1,  -14, 	   0,  -12
.2byte    8,  -11, 	   2,  -15, 	   0,  -14, 	   0,  -12
.2byte    6,  -10, 	   3,  -15, 	   0,  -13, 	   0,  -12
sLuvdiscAnimTable1:
.4byte sLuvdiscAnims_1_1
.4byte sLuvdiscAnims_1_2
.4byte sLuvdiscAnims_1_3
.4byte sLuvdiscAnims_1_4
.4byte sLuvdiscAnims_1_5
.4byte sLuvdiscAnims_1_6
.4byte sLuvdiscAnims_1_7
.4byte sLuvdiscAnims_1_8
sLuvdiscAnimTable2:
.4byte sLuvdiscAnims_2_1
.4byte sLuvdiscAnims_2_2
.4byte sLuvdiscAnims_2_3
.4byte sLuvdiscAnims_2_4
.4byte sLuvdiscAnims_2_5
.4byte sLuvdiscAnims_2_6
.4byte sLuvdiscAnims_2_7
.4byte sLuvdiscAnims_2_8
sLuvdiscAnimTable3:
.4byte sLuvdiscAnims_3_1
.4byte sLuvdiscAnims_3_2
.4byte sLuvdiscAnims_3_3
.4byte sLuvdiscAnims_3_4
.4byte sLuvdiscAnims_3_5
.4byte sLuvdiscAnims_3_6
.4byte sLuvdiscAnims_3_7
.4byte sLuvdiscAnims_3_8
sLuvdiscAnimTable4:
.4byte sLuvdiscAnims_4_1
.4byte sLuvdiscAnims_4_2
.4byte sLuvdiscAnims_4_3
.4byte sLuvdiscAnims_4_4
.4byte sLuvdiscAnims_4_5
.4byte sLuvdiscAnims_4_6
.4byte sLuvdiscAnims_4_7
.4byte sLuvdiscAnims_4_8
sLuvdiscAnimTable5:
.4byte sLuvdiscAnims_5_1
.4byte sLuvdiscAnims_5_2
.4byte sLuvdiscAnims_5_3
.4byte sLuvdiscAnims_5_4
.4byte sLuvdiscAnims_5_5
.4byte sLuvdiscAnims_5_6
.4byte sLuvdiscAnims_5_7
.4byte sLuvdiscAnims_5_8
sLuvdiscAnimTable6:
.4byte sLuvdiscAnims_6_1
.4byte sLuvdiscAnims_6_1
.4byte sLuvdiscAnims_6_1
.4byte sLuvdiscAnims_6_1
.4byte sLuvdiscAnims_6_1
.4byte sLuvdiscAnims_6_1
.4byte sLuvdiscAnims_6_1
.4byte sLuvdiscAnims_6_1
sLuvdiscAnimTable7:
.4byte sLuvdiscAnims_7_1
.4byte sLuvdiscAnims_7_2
.4byte sLuvdiscAnims_7_3
.4byte sLuvdiscAnims_7_4
.4byte sLuvdiscAnims_7_5
.4byte sLuvdiscAnims_7_6
.4byte sLuvdiscAnims_7_7
.4byte sLuvdiscAnims_7_8
sLuvdiscAnimTable8:
.4byte sLuvdiscAnims_8_1
.4byte sLuvdiscAnims_8_2
.4byte sLuvdiscAnims_8_3
.4byte sLuvdiscAnims_8_4
.4byte sLuvdiscAnims_8_5
.4byte sLuvdiscAnims_8_6
.4byte sLuvdiscAnims_8_7
.4byte sLuvdiscAnims_8_8
sLuvdiscAnimTable9:
.4byte sLuvdiscAnims_9_1
.4byte sLuvdiscAnims_9_2
.4byte sLuvdiscAnims_9_3
.4byte sLuvdiscAnims_9_4
.4byte sLuvdiscAnims_9_5
.4byte sLuvdiscAnims_9_6
.4byte sLuvdiscAnims_9_7
.4byte sLuvdiscAnims_9_8
sLuvdiscAnimTable10:
.4byte sLuvdiscAnims_10_1
.4byte sLuvdiscAnims_10_2
.4byte sLuvdiscAnims_10_3
.4byte sLuvdiscAnims_10_4
.4byte sLuvdiscAnims_10_5
.4byte sLuvdiscAnims_10_6
.4byte sLuvdiscAnims_10_7
.4byte sLuvdiscAnims_10_8
sLuvdiscAnimTable11:
.4byte sLuvdiscAnims_11_1
.4byte sLuvdiscAnims_11_2
.4byte sLuvdiscAnims_11_3
.4byte sLuvdiscAnims_11_4
.4byte sLuvdiscAnims_11_5
.4byte sLuvdiscAnims_11_6
.4byte sLuvdiscAnims_11_7
.4byte sLuvdiscAnims_11_8
sLuvdiscAnimTable12:
.4byte sLuvdiscAnims_12_1
.4byte sLuvdiscAnims_12_2
.4byte sLuvdiscAnims_12_3
.4byte sLuvdiscAnims_12_4
.4byte sLuvdiscAnims_12_5
.4byte sLuvdiscAnims_12_6
.4byte sLuvdiscAnims_12_7
.4byte sLuvdiscAnims_12_8
sLuvdiscAnimTable13:
.4byte sLuvdiscAnims_13_1
.4byte sLuvdiscAnims_13_2
.4byte sLuvdiscAnims_13_3
.4byte sLuvdiscAnims_13_4
.4byte sLuvdiscAnims_13_5
.4byte sLuvdiscAnims_13_6
.4byte sLuvdiscAnims_13_7
.4byte sLuvdiscAnims_13_8
sAxAnimationsLuvdisc:
.4byte sLuvdiscAnimTable1
.4byte sLuvdiscAnimTable2
.4byte sLuvdiscAnimTable3
.4byte sLuvdiscAnimTable4
.4byte sLuvdiscAnimTable5
.4byte sLuvdiscAnimTable6
.4byte sLuvdiscAnimTable7
.4byte sLuvdiscAnimTable8
.4byte sLuvdiscAnimTable9
.4byte sLuvdiscAnimTable10
.4byte sLuvdiscAnimTable11
.4byte sLuvdiscAnimTable12
.4byte sLuvdiscAnimTable13
sAxSpritesLuvdisc:
.4byte sLuvdiscSprites1
.4byte sLuvdiscSprites2
.4byte sLuvdiscSprites3
.4byte sLuvdiscSprites4
.4byte sLuvdiscSprites5
.4byte sLuvdiscSprites6
.4byte sLuvdiscSprites7
.4byte sLuvdiscSprites8
.4byte sLuvdiscSprites9
.4byte sLuvdiscSprites10
.4byte sLuvdiscSprites11
.4byte sLuvdiscSprites12
.4byte sLuvdiscSprites13
.4byte sLuvdiscSprites14
.4byte sLuvdiscSprites15
.4byte sLuvdiscSprites16
.4byte sLuvdiscSprites17
.4byte sLuvdiscSprites18
.4byte sLuvdiscSprites19
.4byte sLuvdiscSprites20
.4byte sLuvdiscSprites21
.4byte sLuvdiscSprites22
.4byte sLuvdiscSprites23
.4byte sLuvdiscSprites24
.4byte sLuvdiscSprites25
.4byte sLuvdiscSprites26
.4byte sLuvdiscSprites27
.4byte sLuvdiscSprites28
.4byte sLuvdiscSprites29
.4byte sLuvdiscSprites30
.4byte sLuvdiscSprites31
.4byte sLuvdiscSprites32
.4byte sLuvdiscSprites33
.4byte sLuvdiscSprites34
.4byte sLuvdiscSprites35
.4byte sLuvdiscSprites36
sAxMainLuvdisc:
ax_main sAxPosesLuvdisc, sAxAnimationsLuvdisc, 13, sAxSpritesLuvdisc, sAxPositionsLuvdisc
