.global gAxMedicham
gAxMedicham:
ax_siro sAxMainMedicham
sMedichamPose1:
ax_pose 0, 0x01e4, 0x80f4, 0x5c00
ax_pose_terminator
sMedichamPose2:
ax_pose 1, 0x01e4, 0x80f4, 0x5c00
ax_pose_terminator
sMedichamPose3:
ax_pose 2, 0x01e4, 0x80f4, 0x5c00
ax_pose_terminator
sMedichamPose4:
ax_pose 3, 0x01e4, 0x90ee, 0x5c00
ax_pose_terminator
sMedichamPose5:
ax_pose 4, 0x01e4, 0x90ee, 0x5c00
ax_pose_terminator
sMedichamPose6:
ax_pose 5, 0x01e4, 0x90ee, 0x5c00
ax_pose_terminator
sMedichamPose7:
ax_pose 6, 0x01e4, 0x90ed, 0x5c00
ax_pose_terminator
sMedichamPose8:
ax_pose 7, 0x01e4, 0x90ed, 0x5c00
ax_pose_terminator
sMedichamPose9:
ax_pose 8, 0x01e4, 0x90ed, 0x5c00
ax_pose_terminator
sMedichamPose10:
ax_pose 9, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sMedichamPose11:
ax_pose 10, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sMedichamPose12:
ax_pose 11, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sMedichamPose13:
ax_pose 12, 0x01e4, 0x80f4, 0x5c00
ax_pose_terminator
sMedichamPose14:
ax_pose 13, 0x01e4, 0x80f4, 0x5c00
ax_pose_terminator
sMedichamPose15:
ax_pose 14, 0x01e4, 0x80f4, 0x5c00
ax_pose_terminator
sMedichamPose16:
ax_pose 9, 0x01e4, 0x80f2, 0x5c00
ax_pose_terminator
sMedichamPose17:
ax_pose 10, 0x01e4, 0x80f2, 0x5c00
ax_pose_terminator
sMedichamPose18:
ax_pose 11, 0x01e4, 0x80f2, 0x5c00
ax_pose_terminator
sMedichamPose19:
ax_pose 6, 0x01e4, 0x80f4, 0x5c00
ax_pose_terminator
sMedichamPose20:
ax_pose 7, 0x01e4, 0x80f4, 0x5c00
ax_pose_terminator
sMedichamPose21:
ax_pose 8, 0x01e4, 0x80f4, 0x5c00
ax_pose_terminator
sMedichamPose22:
ax_pose 3, 0x01e4, 0x80f3, 0x5c00
ax_pose_terminator
sMedichamPose23:
ax_pose 4, 0x01e4, 0x80f3, 0x5c00
ax_pose_terminator
sMedichamPose24:
ax_pose 5, 0x01e4, 0x80f3, 0x5c00
ax_pose_terminator
sMedichamPose25:
ax_pose 0, 0x01e4, 0x80f4, 0x5c00
ax_pose_terminator
sMedichamPose26:
ax_pose 1, 0x01e4, 0x80f4, 0x5c00
ax_pose_terminator
sMedichamPose27:
ax_pose 2, 0x01e4, 0x80f4, 0x5c00
ax_pose_terminator
sMedichamPose28:
ax_pose 3, 0x01e4, 0x90ee, 0x5c00
ax_pose_terminator
sMedichamPose29:
ax_pose 4, 0x01e4, 0x90ee, 0x5c00
ax_pose_terminator
sMedichamPose30:
ax_pose 5, 0x01e4, 0x90ee, 0x5c00
ax_pose_terminator
sMedichamPose31:
ax_pose 6, 0x01e4, 0x90ed, 0x5c00
ax_pose_terminator
sMedichamPose32:
ax_pose 7, 0x01e4, 0x90ed, 0x5c00
ax_pose_terminator
sMedichamPose33:
ax_pose 8, 0x01e4, 0x90ed, 0x5c00
ax_pose_terminator
sMedichamPose34:
ax_pose 9, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sMedichamPose35:
ax_pose 10, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sMedichamPose36:
ax_pose 11, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sMedichamPose37:
ax_pose 12, 0x01e4, 0x80f4, 0x5c00
ax_pose_terminator
sMedichamPose38:
ax_pose 13, 0x01e4, 0x80f4, 0x5c00
ax_pose_terminator
sMedichamPose39:
ax_pose 14, 0x01e4, 0x80f4, 0x5c00
ax_pose_terminator
sMedichamPose40:
ax_pose 9, 0x01e4, 0x80f2, 0x5c00
ax_pose_terminator
sMedichamPose41:
ax_pose 10, 0x01e4, 0x80f2, 0x5c00
ax_pose_terminator
sMedichamPose42:
ax_pose 11, 0x01e4, 0x80f2, 0x5c00
ax_pose_terminator
sMedichamPose43:
ax_pose 6, 0x01e4, 0x80f4, 0x5c00
ax_pose_terminator
sMedichamPose44:
ax_pose 7, 0x01e4, 0x80f4, 0x5c00
ax_pose_terminator
sMedichamPose45:
ax_pose 8, 0x01e4, 0x80f4, 0x5c00
ax_pose_terminator
sMedichamPose46:
ax_pose 3, 0x01e4, 0x80f3, 0x5c00
ax_pose_terminator
sMedichamPose47:
ax_pose 4, 0x01e4, 0x80f3, 0x5c00
ax_pose_terminator
sMedichamPose48:
ax_pose 5, 0x01e4, 0x80f3, 0x5c00
ax_pose_terminator
sMedichamPose49:
ax_pose 0, 0x01e4, 0x80f4, 0x5c00
ax_pose_terminator
sMedichamPose50:
ax_pose 1, 0x01e4, 0x80f4, 0x5c00
ax_pose_terminator
sMedichamPose51:
ax_pose 2, 0x01e4, 0x80f4, 0x5c00
ax_pose_terminator
sMedichamPose52:
ax_pose 15, 0x01e3, 0x80f5, 0x5c00
ax_pose_terminator
sMedichamPose53:
ax_pose 16, 0x01ea, 0x80f4, 0x5c00
ax_pose 17, 0x01ea, 0x80f4, 0x5c10
ax_pose_terminator
sMedichamPose54:
ax_pose 17, 0x01ea, 0x80f4, 0x5c00
ax_pose_terminator
sMedichamPose55:
ax_pose 3, 0x01e4, 0x90ee, 0x5c00
ax_pose_terminator
sMedichamPose56:
ax_pose 4, 0x01e4, 0x90ee, 0x5c00
ax_pose_terminator
sMedichamPose57:
ax_pose 5, 0x01e4, 0x90ee, 0x5c00
ax_pose_terminator
sMedichamPose58:
ax_pose 18, 0x01e3, 0x90ec, 0x5c00
ax_pose_terminator
sMedichamPose59:
ax_pose 19, 0x01e9, 0x90f2, 0x5c00
ax_pose 20, 0x01e9, 0x90f2, 0x5c10
ax_pose_terminator
sMedichamPose60:
ax_pose 20, 0x01e9, 0x90f2, 0x5c00
ax_pose_terminator
sMedichamPose61:
ax_pose 6, 0x01e4, 0x90ed, 0x5c00
ax_pose_terminator
sMedichamPose62:
ax_pose 7, 0x01e4, 0x90ed, 0x5c00
ax_pose_terminator
sMedichamPose63:
ax_pose 8, 0x01e4, 0x90ed, 0x5c00
ax_pose_terminator
sMedichamPose64:
ax_pose 21, 0x01e4, 0x90eb, 0x5c00
ax_pose_terminator
sMedichamPose65:
ax_pose 22, 0x01e4, 0x90f3, 0x5c00
ax_pose 23, 0x01e4, 0x90f3, 0x5c10
ax_pose_terminator
sMedichamPose66:
ax_pose 23, 0x01e4, 0x90f3, 0x5c00
ax_pose_terminator
sMedichamPose67:
ax_pose 9, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sMedichamPose68:
ax_pose 10, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sMedichamPose69:
ax_pose 11, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sMedichamPose70:
ax_pose 24, 0x01e3, 0x90f5, 0x5c00
ax_pose_terminator
sMedichamPose71:
ax_pose 25, 0x01e8, 0x90ee, 0x5c00
ax_pose 26, 0x01e8, 0x90ee, 0x5c10
ax_pose_terminator
sMedichamPose72:
ax_pose 26, 0x01e8, 0x90ee, 0x5c00
ax_pose_terminator
sMedichamPose73:
ax_pose 12, 0x01e4, 0x80f4, 0x5c00
ax_pose_terminator
sMedichamPose74:
ax_pose 13, 0x01e4, 0x80f4, 0x5c00
ax_pose_terminator
sMedichamPose75:
ax_pose 14, 0x01e4, 0x80f4, 0x5c00
ax_pose_terminator
sMedichamPose76:
ax_pose 27, 0x01e5, 0x80f4, 0x5c00
ax_pose_terminator
sMedichamPose77:
ax_pose 28, 0x01e7, 0x80f3, 0x5c00
ax_pose 29, 0x01e7, 0x80f3, 0x5c10
ax_pose_terminator
sMedichamPose78:
ax_pose 29, 0x01e7, 0x80f3, 0x5c00
ax_pose_terminator
sMedichamPose79:
ax_pose 9, 0x01e4, 0x80f2, 0x5c00
ax_pose_terminator
sMedichamPose80:
ax_pose 10, 0x01e4, 0x80f2, 0x5c00
ax_pose_terminator
sMedichamPose81:
ax_pose 11, 0x01e4, 0x80f2, 0x5c00
ax_pose_terminator
sMedichamPose82:
ax_pose 24, 0x01e3, 0x80ec, 0x5c00
ax_pose_terminator
sMedichamPose83:
ax_pose 25, 0x01e8, 0x80f3, 0x5c00
ax_pose 26, 0x01e8, 0x80f3, 0x5c10
ax_pose_terminator
sMedichamPose84:
ax_pose 26, 0x01e8, 0x80f3, 0x5c00
ax_pose_terminator
sMedichamPose85:
ax_pose 6, 0x01e4, 0x80f4, 0x5c00
ax_pose_terminator
sMedichamPose86:
ax_pose 7, 0x01e4, 0x80f4, 0x5c00
ax_pose_terminator
sMedichamPose87:
ax_pose 8, 0x01e4, 0x80f4, 0x5c00
ax_pose_terminator
sMedichamPose88:
ax_pose 21, 0x01e4, 0x80f6, 0x5c00
ax_pose_terminator
sMedichamPose89:
ax_pose 22, 0x01e4, 0x80ee, 0x5c00
ax_pose 23, 0x01e4, 0x80ee, 0x5c10
ax_pose_terminator
sMedichamPose90:
ax_pose 23, 0x01e4, 0x80ee, 0x5c00
ax_pose_terminator
sMedichamPose91:
ax_pose 3, 0x01e4, 0x80f3, 0x5c00
ax_pose_terminator
sMedichamPose92:
ax_pose 4, 0x01e4, 0x80f3, 0x5c00
ax_pose_terminator
sMedichamPose93:
ax_pose 5, 0x01e4, 0x80f3, 0x5c00
ax_pose_terminator
sMedichamPose94:
ax_pose 18, 0x01e3, 0x80f5, 0x5c00
ax_pose_terminator
sMedichamPose95:
ax_pose 19, 0x01e9, 0x80ef, 0x5c00
ax_pose 20, 0x01e9, 0x80ef, 0x5c10
ax_pose_terminator
sMedichamPose96:
ax_pose 20, 0x01e9, 0x80ef, 0x5c00
ax_pose_terminator
sMedichamPose97:
ax_pose 15, 0x01e4, 0x80f5, 0x5c00
ax_pose_terminator
sMedichamPose98:
ax_pose 18, 0x01e3, 0x80f5, 0x5c00
ax_pose_terminator
sMedichamPose99:
ax_pose 21, 0x01e4, 0x80f6, 0x5c00
ax_pose_terminator
sMedichamPose100:
ax_pose 24, 0x01e3, 0x80ec, 0x5c00
ax_pose_terminator
sMedichamPose101:
ax_pose 27, 0x01e4, 0x80f4, 0x5c00
ax_pose_terminator
sMedichamPose102:
ax_pose 24, 0x01e3, 0x90f5, 0x5c00
ax_pose_terminator
sMedichamPose103:
ax_pose 21, 0x01e4, 0x90eb, 0x5c00
ax_pose_terminator
sMedichamPose104:
ax_pose 18, 0x01e3, 0x90ec, 0x5c00
ax_pose_terminator
sMedichamPose105:
ax_pose 0, 0x01e4, 0x80f4, 0x5c00
ax_pose_terminator
sMedichamPose106:
ax_pose 30, 0x01ef, 0x00ff, 0x5c00
ax_pose -1, 0x01ef, 0x00fb, 0x5c00
ax_pose 0, 0x01e4, 0x80f4, 0x5c01
ax_pose_terminator
sMedichamPose107:
ax_pose 31, 0x01ef, 0x00ff, 0x5c00
ax_pose -1, 0x01ef, 0x00fb, 0x5c00
ax_pose 0, 0x01e4, 0x80f4, 0x5c01
ax_pose_terminator
sMedichamPose108:
ax_pose 32, 0x01eb, 0x40f6, 0x5c00
ax_pose -1, 0x01eb, 0x40fa, 0x5c00
ax_pose 0, 0x01e4, 0x80f4, 0x5c04
ax_pose_terminator
sMedichamPose109:
ax_pose 33, 0x01eb, 0x40f6, 0x5c00
ax_pose -1, 0x01eb, 0x40fa, 0x5c00
ax_pose 0, 0x01e4, 0x80f4, 0x5c04
ax_pose_terminator
sMedichamPose110:
ax_pose 3, 0x01e4, 0x90ee, 0x5c00
ax_pose_terminator
sMedichamPose111:
ax_pose 30, 0x01ee, 0x1100, 0x5c00
ax_pose -1, 0x01ef, 0x10fd, 0x5c00
ax_pose 3, 0x01e4, 0x90ee, 0x5c01
ax_pose_terminator
sMedichamPose112:
ax_pose 31, 0x01ee, 0x1100, 0x5c00
ax_pose -1, 0x01ef, 0x10fd, 0x5c00
ax_pose 3, 0x01e4, 0x90ee, 0x5c01
ax_pose_terminator
sMedichamPose113:
ax_pose 32, 0x01ea, 0x50fd, 0x5c00
ax_pose -1, 0x01eb, 0x50fa, 0x5c00
ax_pose 3, 0x01e4, 0x90ee, 0x5c04
ax_pose_terminator
sMedichamPose114:
ax_pose 33, 0x01ea, 0x50fd, 0x5c00
ax_pose -1, 0x01eb, 0x50f9, 0x5c00
ax_pose 3, 0x01e4, 0x90ee, 0x5c04
ax_pose_terminator
sMedichamPose115:
ax_pose 6, 0x01e4, 0x90ed, 0x5c00
ax_pose_terminator
sMedichamPose116:
ax_pose 30, 0x01ee, 0x1100, 0x5c00
ax_pose 6, 0x01e4, 0x90ed, 0x5c01
ax_pose -1, 0x01ec, 0x1101, 0x5c00
ax_pose_terminator
sMedichamPose117:
ax_pose 31, 0x01ee, 0x1100, 0x5c00
ax_pose 6, 0x01e4, 0x90ed, 0x5c01
ax_pose -1, 0x01ec, 0x1101, 0x5c00
ax_pose_terminator
sMedichamPose118:
ax_pose 32, 0x01ea, 0x50fd, 0x5c00
ax_pose 6, 0x01e4, 0x90ed, 0x5c04
ax_pose -1, 0x01e8, 0x50fe, 0x5c00
ax_pose_terminator
sMedichamPose119:
ax_pose 33, 0x01ea, 0x50fd, 0x5c00
ax_pose 6, 0x01e4, 0x90ed, 0x5c04
ax_pose -1, 0x01e8, 0x50fe, 0x5c00
ax_pose_terminator
sMedichamPose120:
ax_pose 9, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sMedichamPose121:
ax_pose 9, 0x01e4, 0x90ef, 0x5c00
ax_pose 30, 0x01ed, 0x1102, 0x5c10
ax_pose_terminator
sMedichamPose122:
ax_pose 9, 0x01e4, 0x90ef, 0x5c00
ax_pose 31, 0x01ed, 0x1102, 0x5c10
ax_pose_terminator
sMedichamPose123:
ax_pose 9, 0x01e4, 0x90ef, 0x5c00
ax_pose 32, 0x01e9, 0x50ff, 0x5c10
ax_pose -1, 0x01e8, 0x50f9, 0x5c10
ax_pose_terminator
sMedichamPose124:
ax_pose 9, 0x01e4, 0x90ef, 0x5c00
ax_pose 33, 0x01e8, 0x50fa, 0x5c10
ax_pose -1, 0x01e9, 0x50fe, 0x5c10
ax_pose_terminator
sMedichamPose125:
ax_pose 12, 0x01e4, 0x80f4, 0x5c00
ax_pose_terminator
sMedichamPose126:
ax_pose 12, 0x01e4, 0x80f4, 0x5c00
ax_pose 30, 0x01ea, 0x00f8, 0x5c10
ax_pose -1, 0x01ea, 0x0102, 0x5c10
ax_pose_terminator
sMedichamPose127:
ax_pose 12, 0x01e4, 0x80f4, 0x5c00
ax_pose 31, 0x01ea, 0x00f8, 0x5c10
ax_pose -1, 0x01ea, 0x0102, 0x5c10
ax_pose_terminator
sMedichamPose128:
ax_pose 12, 0x01e4, 0x80f4, 0x5c00
ax_pose 32, 0x01e6, 0x40f9, 0x5c10
ax_pose -1, 0x01e6, 0x40f7, 0x5c10
ax_pose_terminator
sMedichamPose129:
ax_pose 12, 0x01e4, 0x80f4, 0x5c00
ax_pose 33, 0x01e6, 0x40f9, 0x5c10
ax_pose -1, 0x01e6, 0x40f7, 0x5c10
ax_pose_terminator
sMedichamPose130:
ax_pose 9, 0x01e4, 0x80f2, 0x5c00
ax_pose_terminator
sMedichamPose131:
ax_pose 9, 0x01e4, 0x80f2, 0x5c00
ax_pose 30, 0x01ed, 0x00f7, 0x5c10
ax_pose_terminator
sMedichamPose132:
ax_pose 9, 0x01e4, 0x80f2, 0x5c00
ax_pose 31, 0x01ed, 0x00f7, 0x5c10
ax_pose_terminator
sMedichamPose133:
ax_pose 9, 0x01e4, 0x80f2, 0x5c00
ax_pose 32, 0x01e9, 0x40f2, 0x5c10
ax_pose -1, 0x01e8, 0x40f8, 0x5c10
ax_pose_terminator
sMedichamPose134:
ax_pose 9, 0x01e4, 0x80f2, 0x5c00
ax_pose 33, 0x01e9, 0x40f2, 0x5c10
ax_pose -1, 0x01e8, 0x40f8, 0x5c10
ax_pose_terminator
sMedichamPose135:
ax_pose 6, 0x01e4, 0x80f4, 0x5c00
ax_pose_terminator
sMedichamPose136:
ax_pose 30, 0x01ee, 0x00f9, 0x5c00
ax_pose 6, 0x01e4, 0x80f4, 0x5c01
ax_pose -1, 0x01ec, 0x00f8, 0x5c00
ax_pose_terminator
sMedichamPose137:
ax_pose 31, 0x01ee, 0x00f9, 0x5c00
ax_pose 6, 0x01e4, 0x80f4, 0x5c01
ax_pose -1, 0x01ec, 0x00f8, 0x5c00
ax_pose_terminator
sMedichamPose138:
ax_pose 32, 0x01ea, 0x40f4, 0x5c00
ax_pose 6, 0x01e4, 0x80f4, 0x5c04
ax_pose -1, 0x01e8, 0x40f3, 0x5c00
ax_pose_terminator
sMedichamPose139:
ax_pose 33, 0x01ea, 0x40f4, 0x5c00
ax_pose 6, 0x01e4, 0x80f4, 0x5c04
ax_pose -1, 0x01e8, 0x40f3, 0x5c00
ax_pose_terminator
sMedichamPose140:
ax_pose 3, 0x01e4, 0x80f3, 0x5c00
ax_pose_terminator
sMedichamPose141:
ax_pose 30, 0x01ef, 0x00fd, 0x5c00
ax_pose -1, 0x01ee, 0x00fa, 0x5c00
ax_pose 3, 0x01e4, 0x80f3, 0x5c01
ax_pose_terminator
sMedichamPose142:
ax_pose 31, 0x01ef, 0x00fd, 0x5c00
ax_pose -1, 0x01ee, 0x00fa, 0x5c00
ax_pose 3, 0x01e4, 0x80f3, 0x5c01
ax_pose_terminator
sMedichamPose143:
ax_pose 32, 0x01eb, 0x40f8, 0x5c00
ax_pose -1, 0x01ea, 0x40f5, 0x5c00
ax_pose 3, 0x01e4, 0x80f3, 0x5c04
ax_pose_terminator
sMedichamPose144:
ax_pose 33, 0x01eb, 0x40f8, 0x5c00
ax_pose -1, 0x01ea, 0x40f5, 0x5c00
ax_pose 3, 0x01e4, 0x80f3, 0x5c04
ax_pose_terminator
sMedichamPose145:
ax_pose 34, 0x01ec, 0x80f4, 0x5c00
ax_pose_terminator
sMedichamPose146:
ax_pose 35, 0x01ec, 0x80f4, 0x5c00
ax_pose_terminator
sMedichamPose147:
ax_pose 36, 0x81df, 0x4105, 0x5c00
ax_pose 37, 0x01d7, 0x00f9, 0x5c04
ax_pose 38, 0x81df, 0x80f5, 0x5c05
ax_pose_terminator
sMedichamPose148:
ax_pose 39, 0x01e2, 0x90ea, 0x5c00
ax_pose_terminator
sMedichamPose149:
ax_pose 40, 0x01e2, 0x90e9, 0x5c00
ax_pose_terminator
sMedichamPose150:
ax_pose 41, 0x01e6, 0x90ea, 0x5c00
ax_pose_terminator
sMedichamPose151:
ax_pose 42, 0x01e2, 0x80f1, 0x5c00
ax_pose_terminator
sMedichamPose152:
ax_pose 41, 0x01e6, 0x80f6, 0x5c00
ax_pose_terminator
sMedichamPose153:
ax_pose 40, 0x01e2, 0x80f7, 0x5c00
ax_pose_terminator
sMedichamPose154:
ax_pose 39, 0x01e2, 0x80f6, 0x5c00
ax_pose_terminator
sMedichamPose155:
ax_pose 0, 0x01e4, 0x80f4, 0x5c00
ax_pose_terminator
sMedichamPose156:
ax_pose 1, 0x01e4, 0x80f4, 0x5c00
ax_pose_terminator
sMedichamPose157:
ax_pose 2, 0x01e4, 0x80f4, 0x5c00
ax_pose_terminator
sMedichamPose158:
ax_pose 3, 0x01e4, 0x90ee, 0x5c00
ax_pose_terminator
sMedichamPose159:
ax_pose 4, 0x01e4, 0x90ee, 0x5c00
ax_pose_terminator
sMedichamPose160:
ax_pose 5, 0x01e4, 0x90ee, 0x5c00
ax_pose_terminator
sMedichamPose161:
ax_pose 6, 0x01e4, 0x90ed, 0x5c00
ax_pose_terminator
sMedichamPose162:
ax_pose 7, 0x01e4, 0x90ed, 0x5c00
ax_pose_terminator
sMedichamPose163:
ax_pose 8, 0x01e4, 0x90ed, 0x5c00
ax_pose_terminator
sMedichamPose164:
ax_pose 9, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sMedichamPose165:
ax_pose 10, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sMedichamPose166:
ax_pose 11, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sMedichamPose167:
ax_pose 12, 0x01e4, 0x80f4, 0x5c00
ax_pose_terminator
sMedichamPose168:
ax_pose 13, 0x01e4, 0x80f4, 0x5c00
ax_pose_terminator
sMedichamPose169:
ax_pose 14, 0x01e4, 0x80f4, 0x5c00
ax_pose_terminator
sMedichamPose170:
ax_pose 9, 0x01e4, 0x80f2, 0x5c00
ax_pose_terminator
sMedichamPose171:
ax_pose 10, 0x01e4, 0x80f2, 0x5c00
ax_pose_terminator
sMedichamPose172:
ax_pose 11, 0x01e4, 0x80f2, 0x5c00
ax_pose_terminator
sMedichamPose173:
ax_pose 6, 0x01e4, 0x80f4, 0x5c00
ax_pose_terminator
sMedichamPose174:
ax_pose 7, 0x01e4, 0x80f4, 0x5c00
ax_pose_terminator
sMedichamPose175:
ax_pose 8, 0x01e4, 0x80f4, 0x5c00
ax_pose_terminator
sMedichamPose176:
ax_pose 3, 0x01e4, 0x80f3, 0x5c00
ax_pose_terminator
sMedichamPose177:
ax_pose 4, 0x01e4, 0x80f3, 0x5c00
ax_pose_terminator
sMedichamPose178:
ax_pose 5, 0x01e4, 0x80f3, 0x5c00
ax_pose_terminator
sMedichamPose179:
ax_pose 0, 0x01e4, 0x80f4, 0x5c00
ax_pose_terminator
sMedichamPose180:
ax_pose 3, 0x01e4, 0x80f3, 0x5c00
ax_pose_terminator
sMedichamPose181:
ax_pose 6, 0x01e4, 0x80f4, 0x5c00
ax_pose_terminator
sMedichamPose182:
ax_pose 9, 0x01e4, 0x80f2, 0x5c00
ax_pose_terminator
sMedichamPose183:
ax_pose 12, 0x01e4, 0x80f4, 0x5c00
ax_pose_terminator
sMedichamPose184:
ax_pose 9, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sMedichamPose185:
ax_pose 6, 0x01e4, 0x90ed, 0x5c00
ax_pose_terminator
sMedichamPose186:
ax_pose 3, 0x01e4, 0x90ee, 0x5c00
ax_pose_terminator
sMedichamPose187:
ax_pose 1, 0x01e4, 0x80f4, 0x5c00
ax_pose_terminator
sMedichamPose188:
ax_pose 4, 0x01e4, 0x90ee, 0x5c00
ax_pose_terminator
sMedichamPose189:
ax_pose 7, 0x01e4, 0x90ed, 0x5c00
ax_pose_terminator
sMedichamPose190:
ax_pose 10, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sMedichamPose191:
ax_pose 13, 0x01e4, 0x80f4, 0x5c00
ax_pose_terminator
sMedichamPose192:
ax_pose 10, 0x01e4, 0x80f2, 0x5c00
ax_pose_terminator
sMedichamPose193:
ax_pose 7, 0x01e4, 0x80f4, 0x5c00
ax_pose_terminator
sMedichamPose194:
ax_pose 4, 0x01e4, 0x80f3, 0x5c00
ax_pose_terminator
sMedichamPose195:
ax_pose 0, 0x01e4, 0x80f4, 0x5c00
ax_pose_terminator
sMedichamPose196:
ax_pose 2, 0x01e4, 0x80f4, 0x5c00
ax_pose_terminator
sMedichamPose197:
ax_pose 15, 0x01e3, 0x80f5, 0x5c00
ax_pose_terminator
sMedichamPose198:
ax_pose 3, 0x01e4, 0x90ee, 0x5c00
ax_pose_terminator
sMedichamPose199:
ax_pose 5, 0x01e4, 0x90ee, 0x5c00
ax_pose_terminator
sMedichamPose200:
ax_pose 18, 0x01e3, 0x90ec, 0x5c00
ax_pose_terminator
sMedichamPose201:
ax_pose 6, 0x01e4, 0x90ed, 0x5c00
ax_pose_terminator
sMedichamPose202:
ax_pose 8, 0x01e4, 0x90ed, 0x5c00
ax_pose_terminator
sMedichamPose203:
ax_pose 21, 0x01e4, 0x90eb, 0x5c00
ax_pose_terminator
sMedichamPose204:
ax_pose 9, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sMedichamPose205:
ax_pose 11, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sMedichamPose206:
ax_pose 24, 0x01e3, 0x90f6, 0x5c00
ax_pose_terminator
sMedichamPose207:
ax_pose 12, 0x01e4, 0x80f4, 0x5c00
ax_pose_terminator
sMedichamPose208:
ax_pose 14, 0x01e4, 0x80f4, 0x5c00
ax_pose_terminator
sMedichamPose209:
ax_pose 27, 0x01e5, 0x80f4, 0x5c00
ax_pose_terminator
sMedichamPose210:
ax_pose 9, 0x01e4, 0x80f2, 0x5c00
ax_pose_terminator
sMedichamPose211:
ax_pose 11, 0x01e4, 0x80f2, 0x5c00
ax_pose_terminator
sMedichamPose212:
ax_pose 24, 0x01e3, 0x80eb, 0x5c00
ax_pose_terminator
sMedichamPose213:
ax_pose 6, 0x01e4, 0x80f4, 0x5c00
ax_pose_terminator
sMedichamPose214:
ax_pose 8, 0x01e4, 0x80f4, 0x5c00
ax_pose_terminator
sMedichamPose215:
ax_pose 21, 0x01e4, 0x80f6, 0x5c00
ax_pose_terminator
sMedichamPose216:
ax_pose 3, 0x01e4, 0x80f3, 0x5c00
ax_pose_terminator
sMedichamPose217:
ax_pose 5, 0x01e4, 0x80f3, 0x5c00
ax_pose_terminator
sMedichamPose218:
ax_pose 18, 0x01e3, 0x80f5, 0x5c00
ax_pose_terminator
sMedichamPose219:
ax_pose 15, 0x01e4, 0x80f5, 0x5c00
ax_pose_terminator
sMedichamPose220:
ax_pose 18, 0x01e3, 0x80f5, 0x5c00
ax_pose_terminator
sMedichamPose221:
ax_pose 21, 0x01e4, 0x80f6, 0x5c00
ax_pose_terminator
sMedichamPose222:
ax_pose 24, 0x01e3, 0x80ec, 0x5c00
ax_pose_terminator
sMedichamPose223:
ax_pose 27, 0x01e4, 0x80f4, 0x5c00
ax_pose_terminator
sMedichamPose224:
ax_pose 24, 0x01e3, 0x90f5, 0x5c00
ax_pose_terminator
sMedichamPose225:
ax_pose 21, 0x01e4, 0x90eb, 0x5c00
ax_pose_terminator
sMedichamPose226:
ax_pose 18, 0x01e3, 0x90ec, 0x5c00
ax_pose_terminator
sMedichamPose227:
ax_pose 0, 0x01e4, 0x80f4, 0x5c00
ax_pose_terminator
sMedichamPose228:
ax_pose 3, 0x01e4, 0x80f3, 0x5c00
ax_pose_terminator
sMedichamPose229:
ax_pose 6, 0x01e4, 0x80f4, 0x5c00
ax_pose_terminator
sMedichamPose230:
ax_pose 9, 0x01e4, 0x80f2, 0x5c00
ax_pose_terminator
sMedichamPose231:
ax_pose 12, 0x01e4, 0x80f4, 0x5c00
ax_pose_terminator
sMedichamPose232:
ax_pose 9, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sMedichamPose233:
ax_pose 6, 0x01e4, 0x90ed, 0x5c00
ax_pose_terminator
sMedichamPose234:
ax_pose 3, 0x01e4, 0x90ee, 0x5c00
ax_pose_terminator
.align 2
sMedichamAnims_1_1:
ax_anim 10, 0, 0, 0, 0, 0, 0,
ax_anim 6, 0, 1, 0, -1, 0, 0,
ax_anim 6, 0, 1, 0, -2, 0, 0,
ax_anim 6, 0, 1, 0, -1, 0, 0,
ax_anim 10, 0, 0, 0, 0, 0, 0,
ax_anim 6, 0, 2, 0, -1, 0, 0,
ax_anim 6, 0, 2, 0, -2, 0, 0,
ax_anim 6, 0, 2, 0, -1, 0, 0,
ax_anim_terminator
sMedichamAnims_1_2:
ax_anim 10, 0, 3, 0, 0, 0, 0,
ax_anim 6, 0, 4, 0, -1, 0, 0,
ax_anim 6, 0, 4, 0, -2, 0, 0,
ax_anim 6, 0, 4, 0, -1, 0, 0,
ax_anim 10, 0, 3, 0, 0, 0, 0,
ax_anim 6, 0, 5, 0, -1, 0, 0,
ax_anim 6, 0, 5, 0, -2, 0, 0,
ax_anim 6, 0, 5, 0, -1, 0, 0,
ax_anim_terminator
sMedichamAnims_1_3:
ax_anim 10, 0, 6, 0, 0, 0, 0,
ax_anim 6, 0, 7, 0, -1, 0, 0,
ax_anim 6, 0, 7, 0, -2, 0, 0,
ax_anim 6, 0, 7, 0, -1, 0, 0,
ax_anim 10, 0, 6, 0, 0, 0, 0,
ax_anim 6, 0, 8, 0, -1, 0, 0,
ax_anim 6, 0, 8, 0, -2, 0, 0,
ax_anim 6, 0, 8, 0, -1, 0, 0,
ax_anim_terminator
sMedichamAnims_1_4:
ax_anim 10, 0, 9, 0, 0, 0, 0,
ax_anim 6, 0, 10, 0, -1, 0, 0,
ax_anim 6, 0, 10, 0, -2, 0, 0,
ax_anim 6, 0, 10, 0, -1, 0, 0,
ax_anim 10, 0, 9, 0, 0, 0, 0,
ax_anim 6, 0, 11, 0, -1, 0, 0,
ax_anim 6, 0, 11, 0, -2, 0, 0,
ax_anim 6, 0, 11, 0, -1, 0, 0,
ax_anim_terminator
sMedichamAnims_1_5:
ax_anim 10, 0, 12, 0, 0, 0, 0,
ax_anim 6, 0, 13, 0, -1, 0, 0,
ax_anim 6, 0, 13, 0, -2, 0, 0,
ax_anim 6, 0, 13, 0, -1, 0, 0,
ax_anim 10, 0, 12, 0, 0, 0, 0,
ax_anim 6, 0, 14, 0, -1, 0, 0,
ax_anim 6, 0, 14, 0, -2, 0, 0,
ax_anim 6, 0, 14, 0, -1, 0, 0,
ax_anim_terminator
sMedichamAnims_1_6:
ax_anim 10, 0, 15, 0, 0, 0, 0,
ax_anim 6, 0, 16, 0, -1, 0, 0,
ax_anim 6, 0, 16, 0, -2, 0, 0,
ax_anim 6, 0, 16, 0, -1, 0, 0,
ax_anim 10, 0, 15, 0, 0, 0, 0,
ax_anim 6, 0, 17, 0, -1, 0, 0,
ax_anim 6, 0, 17, 0, -2, 0, 0,
ax_anim 6, 0, 17, 0, -1, 0, 0,
ax_anim_terminator
sMedichamAnims_1_7:
ax_anim 10, 0, 18, 0, 0, 0, 0,
ax_anim 6, 0, 19, 0, -1, 0, 0,
ax_anim 6, 0, 19, 0, -2, 0, 0,
ax_anim 6, 0, 19, 0, -1, 0, 0,
ax_anim 10, 0, 18, 0, 0, 0, 0,
ax_anim 6, 0, 20, 0, -1, 0, 0,
ax_anim 6, 0, 20, 0, -2, 0, 0,
ax_anim 6, 0, 20, 0, -1, 0, 0,
ax_anim_terminator
sMedichamAnims_1_8:
ax_anim 10, 0, 21, 0, 0, 0, 0,
ax_anim 6, 0, 22, 0, -1, 0, 0,
ax_anim 6, 0, 22, 0, -2, 0, 0,
ax_anim 6, 0, 22, 0, -1, 0, 0,
ax_anim 10, 0, 21, 0, 0, 0, 0,
ax_anim 6, 0, 23, 0, -1, 0, 0,
ax_anim 6, 0, 23, 0, -2, 0, 0,
ax_anim 6, 0, 23, 0, -1, 0, 0,
ax_anim_terminator
.align 2
sMedichamAnims_2_1:
ax_anim 2, 0, 24, 0, 0, 0, 0,
ax_anim 2, 0, 24, 0, -1, 0, -1,
ax_anim 4, 0, 24, 0, -2, 0, -2,
ax_anim 2, 0, 26, 0, -6, 0, -6,
ax_anim 2, 0, 26, 0, 0, 0, 0,
ax_anim 2, 2, 26, 0, 10, 0, 10,
ax_anim 2, 0, 26, 0, 21, 0, 21,
ax_anim 2, 1, 26, 1, 21, 1, 21,
ax_anim 2, 0, 26, 0, 21, 0, 21,
ax_anim 2, 0, 26, 1, 21, 1, 21,
ax_anim 2, 0, 24, 0, 6, 0, 6,
ax_anim_terminator
sMedichamAnims_2_2:
ax_anim 2, 0, 27, 0, 0, 0, 0,
ax_anim 2, 0, 27, -1, -1, -1, -1,
ax_anim 4, 0, 27, -2, -2, -2, -2,
ax_anim 2, 0, 29, 3, -1, 3, 3,
ax_anim 2, 0, 29, 9, 4, 9, 9,
ax_anim 2, 2, 29, 16, 14, 16, 16,
ax_anim 2, 0, 29, 21, 20, 21, 20,
ax_anim 2, 1, 29, 22, 19, 22, 19,
ax_anim 2, 0, 29, 21, 20, 21, 20,
ax_anim 2, 0, 29, 22, 19, 22, 19,
ax_anim 2, 0, 27, 8, 8, 8, 8,
ax_anim_terminator
sMedichamAnims_2_3:
ax_anim 2, 0, 30, 0, 0, 0, 0,
ax_anim 2, 0, 30, -1, 0, -1, 0,
ax_anim 4, 0, 30, -2, 0, -2, 0,
ax_anim 2, 0, 31, 4, -3, 4, 0,
ax_anim 2, 0, 31, 9, -5, 9, 0,
ax_anim 2, 2, 31, 15, -4, 15, 0,
ax_anim 2, 0, 31, 21, 0, 21, 0,
ax_anim 2, 1, 31, 21, 1, 21, 1,
ax_anim 2, 0, 31, 21, 0, 21, 0,
ax_anim 2, 0, 31, 21, 1, 21, 1,
ax_anim 2, 0, 30, 6, 0, 6, -1,
ax_anim_terminator
sMedichamAnims_2_4:
ax_anim 2, 0, 33, 0, 0, 0, 0,
ax_anim 2, 0, 33, -1, 1, -1, 1,
ax_anim 4, 0, 33, -2, 2, -2, 2,
ax_anim 2, 0, 35, 3, -9, 3, -3,
ax_anim 2, 0, 35, 8, -17, 8, -7,
ax_anim 2, 2, 35, 16, -20, 16, -14,
ax_anim 2, 0, 35, 21, -18, 21, -18,
ax_anim 2, 1, 35, 22, -17, 22, -17,
ax_anim 2, 0, 35, 21, -18, 21, -18,
ax_anim 2, 0, 35, 22, -17, 22, -17,
ax_anim 2, 0, 33, 6, -6, 6, -6,
ax_anim_terminator
sMedichamAnims_2_5:
ax_anim 2, 0, 36, 0, 0, 0, 0,
ax_anim 2, 0, 36, 0, 1, 0, 1,
ax_anim 4, 0, 36, 0, 2, 0, 2,
ax_anim 2, 0, 38, 0, -5, 0, -1,
ax_anim 2, 0, 38, 0, -11, 0, -6,
ax_anim 2, 2, 38, 0, -18, 0, -16,
ax_anim 2, 0, 38, 0, -19, 0, -19,
ax_anim 2, 1, 38, 1, -19, 1, -19,
ax_anim 2, 0, 38, 0, -19, 0, -19,
ax_anim 2, 0, 38, 1, -19, 1, -19,
ax_anim 2, 0, 36, 0, -6, 0, -6,
ax_anim_terminator
sMedichamAnims_2_6:
ax_anim 2, 0, 39, 0, 0, 0, 0,
ax_anim 2, 0, 39, 1, 1, 1, 1,
ax_anim 4, 0, 39, 2, 2, 2, 2,
ax_anim 2, 0, 41, -3, -9, -3, -3,
ax_anim 2, 0, 41, -8, -17, -8, -7,
ax_anim 2, 2, 41, -16, -20, -16, -14,
ax_anim 2, 0, 41, -21, -18, -21, -18,
ax_anim 2, 1, 41, -22, -17, -22, -17,
ax_anim 2, 0, 41, -21, -18, -21, -18,
ax_anim 2, 0, 41, -22, -17, -22, -17,
ax_anim 2, 0, 39, -6, -6, -6, -6,
ax_anim_terminator
sMedichamAnims_2_7:
ax_anim 2, 0, 42, 0, 0, 0, 0,
ax_anim 2, 0, 42, 1, 0, 1, 0,
ax_anim 4, 0, 42, 2, 0, 2, 0,
ax_anim 2, 0, 43, -4, -3, -4, 0,
ax_anim 2, 0, 43, -9, -5, -9, 0,
ax_anim 2, 2, 43, -15, -4, -15, 0,
ax_anim 2, 0, 43, -21, 0, -21, 0,
ax_anim 2, 1, 43, -21, 1, -21, 1,
ax_anim 2, 0, 43, -21, 0, -21, 0,
ax_anim 2, 0, 43, -21, 1, -21, 1,
ax_anim 2, 0, 42, -6, 0, -6, -1,
ax_anim_terminator
sMedichamAnims_2_8:
ax_anim 2, 0, 45, 0, 0, 0, 0,
ax_anim 2, 0, 45, 1, -1, 1, -1,
ax_anim 4, 0, 45, 2, -2, 2, -2,
ax_anim 2, 0, 47, -3, -1, -3, 3,
ax_anim 2, 0, 47, -9, 4, -9, 9,
ax_anim 2, 2, 47, -16, 14, -16, 16,
ax_anim 2, 0, 47, -21, 20, -21, 20,
ax_anim 2, 1, 47, -22, 19, -22, 19,
ax_anim 2, 0, 47, -21, 20, -21, 20,
ax_anim 2, 0, 47, -22, 19, -22, 19,
ax_anim 2, 0, 45, -8, 8, -8, 8,
ax_anim_terminator
.align 2
sMedichamAnims_3_1:
ax_anim 2, 0, 48, 0, -2, 0, -2,
ax_anim 2, 0, 51, 0, -4, 0, -4,
ax_anim 8, 2, 51, 0, -5, 0, -5,
ax_anim 1, 0, 51, 0, -1, 0, -1,
ax_anim 1, 0, 51, 0, 4, 0, 4,
ax_anim 2, 1, 52, 0, 13, 0, 13,
ax_anim 2, 0, 53, -1, 13, -1, 13,
ax_anim 2, 0, 53, 0, 13, 0, 13,
ax_anim 2, 0, 53, -1, 13, -1, 13,
ax_anim 2, 0, 53, 0, 13, 0, 13,
ax_anim 2, 0, 53, -1, 13, -1, 13,
ax_anim 2, 0, 48, 0, 6, 0, 6,
ax_anim 2, 0, 48, 0, 3, 0, 3,
ax_anim_terminator
sMedichamAnims_3_2:
ax_anim 2, 0, 54, -2, -2, -2, -2,
ax_anim 2, 0, 57, -4, -4, -4, -4,
ax_anim 8, 2, 57, -5, -5, -5, -5,
ax_anim 1, 0, 57, -1, -1, -1, -1,
ax_anim 1, 0, 57, 4, 4, 4, 4,
ax_anim 2, 1, 58, 13, 13, 13, 13,
ax_anim 2, 0, 59, 12, 14, 12, 14,
ax_anim 2, 0, 59, 13, 13, 13, 13,
ax_anim 2, 0, 59, 12, 14, 12, 14,
ax_anim 2, 0, 59, 13, 13, 13, 13,
ax_anim 2, 0, 59, 12, 14, 12, 14,
ax_anim 2, 0, 54, 6, 6, 6, 6,
ax_anim 2, 0, 54, 3, 3, 3, 3,
ax_anim_terminator
sMedichamAnims_3_3:
ax_anim 2, 0, 60, -2, 0, -2, 0,
ax_anim 2, 0, 63, -4, 0, -4, 0,
ax_anim 8, 2, 63, -5, 0, -5, 0,
ax_anim 1, 0, 63, -1, 0, -1, 0,
ax_anim 1, 0, 63, 4, 0, 4, 0,
ax_anim 2, 1, 64, 13, 0, 13, 0,
ax_anim 2, 0, 65, 13, 1, 13, 1,
ax_anim 2, 0, 65, 13, 0, 13, 0,
ax_anim 2, 0, 65, 13, 1, 13, 1,
ax_anim 2, 0, 65, 13, 0, 13, 0,
ax_anim 2, 0, 65, 13, 1, 13, 1,
ax_anim 2, 0, 60, 6, 0, 6, 0,
ax_anim 2, 0, 60, 3, 0, 3, 0,
ax_anim_terminator
sMedichamAnims_3_4:
ax_anim 2, 0, 66, -2, 2, -2, 2,
ax_anim 2, 0, 69, -4, 4, -4, 4,
ax_anim 8, 2, 69, -5, 5, -5, 5,
ax_anim 1, 0, 69, -1, 1, -1, 1,
ax_anim 1, 0, 69, 4, -4, 4, -4,
ax_anim 2, 1, 70, 15, -14, 15, -14,
ax_anim 2, 0, 71, 14, -15, 14, -15,
ax_anim 2, 0, 71, 15, -14, 15, -14,
ax_anim 2, 0, 71, 14, -15, 14, -15,
ax_anim 2, 0, 71, 15, -14, 15, -14,
ax_anim 2, 0, 71, 14, -15, 14, -15,
ax_anim 2, 0, 66, 6, -6, 6, -6,
ax_anim 2, 0, 66, 3, -3, 3, -3,
ax_anim_terminator
sMedichamAnims_3_5:
ax_anim 2, 0, 72, 0, 2, 0, 2,
ax_anim 2, 0, 75, 0, 4, 0, 4,
ax_anim 8, 2, 75, 0, 5, 0, 5,
ax_anim 1, 0, 75, 0, 1, 0, 1,
ax_anim 1, 0, 75, 0, -4, 0, -4,
ax_anim 2, 1, 76, 0, -13, 0, -13,
ax_anim 2, 0, 77, -1, -13, -1, -13,
ax_anim 2, 0, 77, 0, -13, 0, -13,
ax_anim 2, 0, 77, -1, -13, -1, -13,
ax_anim 2, 0, 77, 0, -13, 0, -13,
ax_anim 2, 0, 77, -1, -13, -1, -13,
ax_anim 2, 0, 72, 0, -6, 0, -6,
ax_anim 2, 0, 72, 0, -3, 0, -3,
ax_anim_terminator
sMedichamAnims_3_6:
ax_anim 2, 0, 78, 2, 2, 2, 2,
ax_anim 2, 0, 81, 4, 4, 4, 4,
ax_anim 8, 2, 81, 5, 5, 5, 5,
ax_anim 1, 0, 81, 1, 1, 1, 1,
ax_anim 1, 0, 81, -4, -4, -4, -4,
ax_anim 2, 1, 82, -15, -14, -15, -14,
ax_anim 2, 0, 83, -14, -15, -14, -15,
ax_anim 2, 0, 83, -15, -14, -15, -14,
ax_anim 2, 0, 83, -14, -15, -14, -15,
ax_anim 2, 0, 83, -15, -14, -15, -14,
ax_anim 2, 0, 83, -14, -15, -14, -15,
ax_anim 2, 0, 78, -6, -6, -6, -6,
ax_anim 2, 0, 78, -3, -3, -3, -3,
ax_anim_terminator
sMedichamAnims_3_7:
ax_anim 2, 0, 84, 2, 0, 2, 0,
ax_anim 2, 0, 87, 4, 0, 4, 0,
ax_anim 8, 2, 87, 5, 0, 5, 0,
ax_anim 1, 0, 87, 1, 0, 1, 0,
ax_anim 1, 0, 87, -4, 0, -4, 0,
ax_anim 2, 1, 88, -13, 0, -13, 0,
ax_anim 2, 0, 89, -13, 1, -13, 1,
ax_anim 2, 0, 89, -13, 0, -13, 0,
ax_anim 2, 0, 89, -13, 1, -13, 1,
ax_anim 2, 0, 89, -13, 0, -13, 0,
ax_anim 2, 0, 89, -13, 1, -13, 1,
ax_anim 2, 0, 84, -6, 0, -6, 0,
ax_anim 2, 0, 84, -3, 0, -3, 0,
ax_anim_terminator
sMedichamAnims_3_8:
ax_anim 2, 0, 90, 2, -2, 2, -2,
ax_anim 2, 0, 93, 4, -4, 4, -4,
ax_anim 8, 2, 93, 5, -5, 5, -5,
ax_anim 1, 0, 93, 1, -1, 1, -1,
ax_anim 1, 0, 93, -4, 4, -4, 4,
ax_anim 2, 1, 94, -13, 13, -13, 13,
ax_anim 2, 0, 95, -12, 14, -12, 14,
ax_anim 2, 0, 95, -13, 13, -13, 13,
ax_anim 2, 0, 95, -12, 14, -12, 14,
ax_anim 2, 0, 95, -13, 13, -13, 13,
ax_anim 2, 0, 95, -12, 14, -12, 14,
ax_anim 2, 0, 90, -6, 6, -6, 6,
ax_anim 2, 0, 90, -3, 3, -3, 3,
ax_anim_terminator
.align 2
sMedichamAnims_4_1:
ax_anim 2, 0, 96, 1, 0, 1, 0,
ax_anim 2, 0, 96, 0, 0, 0, 0,
ax_anim 2, 0, 96, 1, 0, 1, 0,
ax_anim 2, 0, 96, 0, 0, 0, 0,
ax_anim 2, 0, 96, 1, 0, 1, 0,
ax_anim 2, 2, 96, 0, 0, 0, 0,
ax_anim 2, 0, 96, 1, 0, 1, 0,
ax_anim 2, 0, 96, 0, 0, 0, 0,
ax_anim 2, 0, 96, 1, 0, 1, 0,
ax_anim 2, 1, 96, 0, 0, 0, 0,
ax_anim_terminator
sMedichamAnims_4_2:
ax_anim 2, 0, 103, 1, -1, 1, -1,
ax_anim 2, 0, 103, 0, 0, 0, 0,
ax_anim 2, 0, 103, 1, -1, 1, -1,
ax_anim 2, 0, 103, 0, 0, 0, 0,
ax_anim 2, 0, 103, 1, -1, 1, -1,
ax_anim 2, 2, 103, 0, 0, 0, 0,
ax_anim 2, 0, 103, 1, -1, 1, -1,
ax_anim 2, 0, 103, 0, 0, 0, 0,
ax_anim 2, 0, 103, 1, -1, 1, -1,
ax_anim 2, 1, 103, 0, 0, 0, 0,
ax_anim_terminator
sMedichamAnims_4_3:
ax_anim 2, 0, 102, 0, -1, 0, -1,
ax_anim 2, 0, 102, 0, 0, 0, 0,
ax_anim 2, 0, 102, 0, -1, 0, -1,
ax_anim 2, 0, 102, 0, 0, 0, 0,
ax_anim 2, 0, 102, 0, -1, 0, -1,
ax_anim 2, 2, 102, 0, 0, 0, 0,
ax_anim 2, 0, 102, 0, -1, 0, -1,
ax_anim 2, 0, 102, 0, 0, 0, 0,
ax_anim 2, 0, 102, 0, -1, 0, -1,
ax_anim 2, 1, 102, 0, 0, 0, 0,
ax_anim_terminator
sMedichamAnims_4_4:
ax_anim 2, 0, 101, -1, -1, -1, -1,
ax_anim 2, 0, 101, 0, 0, 0, 0,
ax_anim 2, 0, 101, -1, -1, -1, -1,
ax_anim 2, 0, 101, 0, 0, 0, 0,
ax_anim 2, 0, 101, -1, -1, -1, -1,
ax_anim 2, 2, 101, 0, 0, 0, 0,
ax_anim 2, 0, 101, -1, -1, -1, -1,
ax_anim 2, 0, 101, 0, 0, 0, 0,
ax_anim 2, 0, 101, -1, -1, -1, -1,
ax_anim 2, 1, 101, 0, 0, 0, 0,
ax_anim_terminator
sMedichamAnims_4_5:
ax_anim 2, 0, 100, 1, 0, 1, 0,
ax_anim 2, 0, 100, 0, 0, 0, 0,
ax_anim 2, 0, 100, 1, 0, 1, 0,
ax_anim 2, 0, 100, 0, 0, 0, 0,
ax_anim 2, 0, 100, 1, 0, 1, 0,
ax_anim 2, 2, 100, 0, 0, 0, 0,
ax_anim 2, 0, 100, 1, 0, 1, 0,
ax_anim 2, 0, 100, 0, 0, 0, 0,
ax_anim 2, 0, 100, 1, 0, 1, 0,
ax_anim 2, 1, 100, 0, 0, 0, 0,
ax_anim_terminator
sMedichamAnims_4_6:
ax_anim 2, 0, 99, 1, -1, 1, -1,
ax_anim 2, 0, 99, 0, 0, 0, 0,
ax_anim 2, 0, 99, 1, -1, 1, -1,
ax_anim 2, 0, 99, 0, 0, 0, 0,
ax_anim 2, 0, 99, 1, -1, 1, -1,
ax_anim 2, 2, 99, 0, 0, 0, 0,
ax_anim 2, 0, 99, 1, -1, 1, -1,
ax_anim 2, 0, 99, 0, 0, 0, 0,
ax_anim 2, 0, 99, 1, -1, 1, -1,
ax_anim 2, 1, 99, 0, 0, 0, 0,
ax_anim_terminator
sMedichamAnims_4_7:
ax_anim 2, 0, 98, 0, -1, 0, -1,
ax_anim 2, 0, 98, 0, 0, 0, 0,
ax_anim 2, 0, 98, 0, -1, 0, -1,
ax_anim 2, 0, 98, 0, 0, 0, 0,
ax_anim 2, 0, 98, 0, -1, 0, -1,
ax_anim 2, 2, 98, 0, 0, 0, 0,
ax_anim 2, 0, 98, 0, -1, 0, -1,
ax_anim 2, 0, 98, 0, 0, 0, 0,
ax_anim 2, 0, 98, 0, -1, 0, -1,
ax_anim 2, 1, 98, 0, 0, 0, 0,
ax_anim_terminator
sMedichamAnims_4_8:
ax_anim 2, 0, 97, -1, -1, -1, -1,
ax_anim 2, 0, 97, 0, 0, 0, 0,
ax_anim 2, 0, 97, -1, -1, -1, -1,
ax_anim 2, 0, 97, 0, 0, 0, 0,
ax_anim 2, 0, 97, -1, -1, -1, -1,
ax_anim 2, 2, 97, 0, 0, 0, 0,
ax_anim 2, 0, 97, -1, -1, -1, -1,
ax_anim 2, 0, 97, 0, 0, 0, 0,
ax_anim 2, 0, 97, -1, -1, -1, -1,
ax_anim 2, 1, 97, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sMedichamAnims_5_1:
ax_anim 2, 0, 109, 0, -2, 0, 0,
ax_anim 2, 0, 114, 0, -4, 0, 0,
ax_anim 1, 0, 119, 0, -5, 0, 0,
ax_anim 1, 0, 124, 0, -5, 0, 0,
ax_anim 1, 0, 129, 0, -5, 0, 0,
ax_anim 2, 0, 134, 0, -4, 0, 0,
ax_anim 2, 0, 139, 0, -2, 0, 0,
ax_anim 6, 0, 104, 0, 0, 0, 0,
ax_anim 1, 2, 105, 0, 0, 0, 0,
ax_anim 1, 0, 106, 0, 0, 0, 0,
ax_anim 2, 0, 107, 0, 0, 0, 0,
ax_anim 2, 0, 108, 0, 0, 0, 0,
ax_anim 2, 0, 107, 0, 0, 0, 0,
ax_anim 2, 0, 106, 0, 0, 0, 0,
ax_anim 1, 1, 105, 0, 0, 0, 0,
ax_anim 1, 0, 104, 0, 0, 0, 0,
ax_anim_terminator
sMedichamAnims_5_2:
ax_anim 2, 0, 114, 0, -2, 0, 0,
ax_anim 2, 0, 119, 0, -4, 0, 0,
ax_anim 1, 0, 124, 0, -5, 0, 0,
ax_anim 1, 0, 129, 0, -5, 0, 0,
ax_anim 1, 0, 134, 0, -5, 0, 0,
ax_anim 2, 0, 139, 0, -4, 0, 0,
ax_anim 2, 0, 104, 0, -2, 0, 0,
ax_anim 6, 0, 109, 0, 0, 0, 0,
ax_anim 1, 2, 110, 0, 0, 0, 0,
ax_anim 1, 0, 111, 0, 0, 0, 0,
ax_anim 2, 0, 112, 0, 0, 0, 0,
ax_anim 2, 0, 113, 0, 0, 0, 0,
ax_anim 2, 0, 112, 0, 0, 0, 0,
ax_anim 2, 0, 111, 0, 0, 0, 0,
ax_anim 1, 1, 110, 0, 0, 0, 0,
ax_anim 1, 0, 109, 0, 0, 0, 0,
ax_anim_terminator
sMedichamAnims_5_3:
ax_anim 2, 0, 119, 0, -2, 0, 0,
ax_anim 2, 0, 124, 0, -4, 0, 0,
ax_anim 1, 0, 129, 0, -5, 0, 0,
ax_anim 1, 0, 134, 0, -5, 0, 0,
ax_anim 1, 0, 139, 0, -5, 0, 0,
ax_anim 2, 0, 104, 0, -4, 0, 0,
ax_anim 2, 0, 109, 0, -2, 0, 0,
ax_anim 6, 0, 114, 0, 0, 0, 0,
ax_anim 1, 2, 115, 0, 0, 0, 0,
ax_anim 1, 0, 116, 0, 0, 0, 0,
ax_anim 2, 0, 117, 0, 0, 0, 0,
ax_anim 2, 0, 118, 0, 0, 0, 0,
ax_anim 2, 0, 117, 0, 0, 0, 0,
ax_anim 2, 0, 116, 0, 0, 0, 0,
ax_anim 1, 1, 115, 0, 0, 0, 0,
ax_anim 1, 0, 114, 0, 0, 0, 0,
ax_anim_terminator
sMedichamAnims_5_4:
ax_anim 2, 0, 124, 0, -2, 0, 0,
ax_anim 2, 0, 129, 0, -4, 0, 0,
ax_anim 1, 0, 134, 0, -5, 0, 0,
ax_anim 1, 0, 139, 0, -5, 0, 0,
ax_anim 1, 0, 104, 0, -5, 0, 0,
ax_anim 2, 0, 109, 0, -4, 0, 0,
ax_anim 2, 0, 114, 0, -2, 0, 0,
ax_anim 6, 0, 119, 0, 0, 0, 0,
ax_anim 1, 2, 120, 0, 0, 0, 0,
ax_anim 1, 0, 121, 0, 0, 0, 0,
ax_anim 2, 0, 122, 0, 0, 0, 0,
ax_anim 2, 0, 123, 0, 0, 0, 0,
ax_anim 2, 0, 122, 0, 0, 0, 0,
ax_anim 2, 0, 121, 0, 0, 0, 0,
ax_anim 1, 1, 120, 0, 0, 0, 0,
ax_anim 1, 0, 119, 0, 0, 0, 0,
ax_anim_terminator
sMedichamAnims_5_5:
ax_anim 2, 0, 129, 0, -2, 0, 0,
ax_anim 2, 0, 134, 0, -4, 0, 0,
ax_anim 1, 0, 139, 0, -5, 0, 0,
ax_anim 1, 0, 104, 0, -5, 0, 0,
ax_anim 1, 0, 109, 0, -5, 0, 0,
ax_anim 2, 0, 114, 0, -4, 0, 0,
ax_anim 2, 0, 119, 0, -2, 0, 0,
ax_anim 6, 0, 124, 0, 0, 0, 0,
ax_anim 1, 2, 125, 0, 0, 0, 0,
ax_anim 1, 0, 126, 0, 0, 0, 0,
ax_anim 2, 0, 127, 0, 0, 0, 0,
ax_anim 2, 0, 128, 0, 0, 0, 0,
ax_anim 2, 0, 127, 0, 0, 0, 0,
ax_anim 2, 0, 126, 0, 0, 0, 0,
ax_anim 1, 1, 125, 0, 0, 0, 0,
ax_anim 1, 0, 124, 0, 0, 0, 0,
ax_anim_terminator
sMedichamAnims_5_6:
ax_anim 2, 0, 134, 0, -2, 0, 0,
ax_anim 2, 0, 139, 0, -4, 0, 0,
ax_anim 1, 0, 104, 0, -5, 0, 0,
ax_anim 1, 0, 109, 0, -5, 0, 0,
ax_anim 1, 0, 114, 0, -5, 0, 0,
ax_anim 2, 0, 119, 0, -4, 0, 0,
ax_anim 2, 0, 124, 0, -2, 0, 0,
ax_anim 6, 0, 129, 0, 0, 0, 0,
ax_anim 1, 2, 130, 0, 0, 0, 0,
ax_anim 1, 0, 131, 0, 0, 0, 0,
ax_anim 2, 0, 132, 0, 0, 0, 0,
ax_anim 2, 0, 133, 0, 0, 0, 0,
ax_anim 2, 0, 132, 0, 0, 0, 0,
ax_anim 2, 0, 131, 0, 0, 0, 0,
ax_anim 1, 1, 130, 0, 0, 0, 0,
ax_anim 1, 0, 129, 0, 0, 0, 0,
ax_anim_terminator
sMedichamAnims_5_7:
ax_anim 2, 0, 139, 0, -2, 0, 0,
ax_anim 2, 0, 104, 0, -4, 0, 0,
ax_anim 1, 0, 109, 0, -5, 0, 0,
ax_anim 1, 0, 114, 0, -5, 0, 0,
ax_anim 1, 0, 119, 0, -5, 0, 0,
ax_anim 2, 0, 124, 0, -4, 0, 0,
ax_anim 2, 0, 129, 0, -2, 0, 0,
ax_anim 6, 0, 134, 0, 0, 0, 0,
ax_anim 1, 2, 135, 0, 0, 0, 0,
ax_anim 1, 0, 136, 0, 0, 0, 0,
ax_anim 2, 0, 137, 0, 0, 0, 0,
ax_anim 2, 0, 138, 0, 0, 0, 0,
ax_anim 2, 0, 137, 0, 0, 0, 0,
ax_anim 2, 0, 136, 0, 0, 0, 0,
ax_anim 1, 1, 135, 0, 0, 0, 0,
ax_anim 1, 0, 134, 0, 0, 0, 0,
ax_anim_terminator
sMedichamAnims_5_8:
ax_anim 2, 0, 104, 0, -2, 0, 0,
ax_anim 2, 0, 109, 0, -4, 0, 0,
ax_anim 1, 0, 114, 0, -5, 0, 0,
ax_anim 1, 0, 119, 0, -5, 0, 0,
ax_anim 1, 0, 124, 0, -5, 0, 0,
ax_anim 2, 0, 129, 0, -4, 0, 0,
ax_anim 2, 0, 134, 0, -2, 0, 0,
ax_anim 6, 0, 139, 0, 0, 0, 0,
ax_anim 1, 2, 140, 0, 0, 0, 0,
ax_anim 1, 0, 141, 0, 0, 0, 0,
ax_anim 2, 0, 142, 0, 0, 0, 0,
ax_anim 2, 0, 143, 0, 0, 0, 0,
ax_anim 2, 0, 142, 0, 0, 0, 0,
ax_anim 2, 0, 141, 0, 0, 0, 0,
ax_anim 1, 1, 140, 0, 0, 0, 0,
ax_anim 1, 0, 139, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sMedichamAnims_6_1:
ax_anim 30, 0, 144, 0, 0, 0, 0,
ax_anim 35, 0, 145, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sMedichamAnims_7_1:
ax_anim 2, 0, 146, 0, -4, 0, -4,
ax_anim 8, 0, 146, 0, -5, 0, -5,
ax_anim_terminator
sMedichamAnims_7_2:
ax_anim 2, 0, 147, -4, -4, -4, -4,
ax_anim 8, 0, 147, -5, -5, -5, -5,
ax_anim_terminator
sMedichamAnims_7_3:
ax_anim 2, 0, 148, -4, 0, -4, 0,
ax_anim 8, 0, 148, -5, 0, -5, 0,
ax_anim_terminator
sMedichamAnims_7_4:
ax_anim 2, 0, 149, -4, 4, -4, 4,
ax_anim 8, 0, 149, -5, 5, -5, 5,
ax_anim_terminator
sMedichamAnims_7_5:
ax_anim 2, 0, 150, 0, 4, 0, 4,
ax_anim 8, 0, 150, 0, 5, 0, 5,
ax_anim_terminator
sMedichamAnims_7_6:
ax_anim 2, 0, 151, 4, 4, 4, 4,
ax_anim 8, 0, 151, 5, 5, 5, 5,
ax_anim_terminator
sMedichamAnims_7_7:
ax_anim 2, 0, 152, 4, 0, 4, 0,
ax_anim 8, 0, 152, 5, 0, 5, 0,
ax_anim_terminator
sMedichamAnims_7_8:
ax_anim 2, 0, 153, 4, -4, 4, -4,
ax_anim 8, 0, 153, 5, -5, 5, -5,
ax_anim_terminator
.align 2
sMedichamAnims_8_1:
ax_anim 40, 0, 154, 0, 0, 0, 0,
ax_anim 2, 0, 155, 0, 0, 0, 0,
ax_anim 2, 0, 155, 0, -2, 0, 0,
ax_anim 3, 0, 155, 0, -3, 0, 0,
ax_anim 4, 0, 154, 0, -6, 0, 0,
ax_anim 3, 0, 156, 0, -3, 0, 0,
ax_anim 2, 0, 156, 0, -2, 0, 0,
ax_anim 2, 0, 156, 0, 0, 0, 0,
ax_anim_terminator
sMedichamAnims_8_2:
ax_anim 40, 0, 157, 0, 0, 0, 0,
ax_anim 2, 0, 158, 0, 0, 0, 0,
ax_anim 2, 0, 158, 0, -2, 0, 0,
ax_anim 3, 0, 158, 0, -3, 0, 0,
ax_anim 4, 0, 157, 0, -6, 0, 0,
ax_anim 3, 0, 159, 0, -3, 0, 0,
ax_anim 2, 0, 159, 0, -2, 0, 0,
ax_anim 2, 0, 159, 0, 0, 0, 0,
ax_anim_terminator
sMedichamAnims_8_3:
ax_anim 40, 0, 160, 0, 0, 0, 0,
ax_anim 2, 0, 161, 0, 0, 0, 0,
ax_anim 2, 0, 161, 0, -2, 0, 0,
ax_anim 3, 0, 161, 0, -3, 0, 0,
ax_anim 4, 0, 160, 0, -6, 0, 0,
ax_anim 3, 0, 162, 0, -3, 0, 0,
ax_anim 2, 0, 162, 0, -2, 0, 0,
ax_anim 2, 0, 162, 0, 0, 0, 0,
ax_anim_terminator
sMedichamAnims_8_4:
ax_anim 40, 0, 163, 0, 0, 0, 0,
ax_anim 2, 0, 164, 0, 0, 0, 0,
ax_anim 2, 0, 164, 0, -2, 0, 0,
ax_anim 3, 0, 164, 0, -3, 0, 0,
ax_anim 4, 0, 163, 0, -6, 0, 0,
ax_anim 3, 0, 165, 0, -3, 0, 0,
ax_anim 2, 0, 165, 0, -2, 0, 0,
ax_anim 2, 0, 165, 0, 0, 0, 0,
ax_anim_terminator
sMedichamAnims_8_5:
ax_anim 40, 0, 166, 0, 0, 0, 0,
ax_anim 2, 0, 167, 0, 0, 0, 0,
ax_anim 2, 0, 167, 0, -2, 0, 0,
ax_anim 3, 0, 167, 0, -3, 0, 0,
ax_anim 4, 0, 166, 0, -6, 0, 0,
ax_anim 3, 0, 168, 0, -3, 0, 0,
ax_anim 2, 0, 168, 0, -2, 0, 0,
ax_anim 2, 0, 168, 0, 0, 0, 0,
ax_anim_terminator
sMedichamAnims_8_6:
ax_anim 40, 0, 169, 0, 0, 0, 0,
ax_anim 2, 0, 170, 0, 0, 0, 0,
ax_anim 2, 0, 170, 0, -2, 0, 0,
ax_anim 3, 0, 170, 0, -3, 0, 0,
ax_anim 4, 0, 169, 0, -6, 0, 0,
ax_anim 3, 0, 171, 0, -3, 0, 0,
ax_anim 2, 0, 171, 0, -2, 0, 0,
ax_anim 2, 0, 171, 0, 0, 0, 0,
ax_anim_terminator
sMedichamAnims_8_7:
ax_anim 40, 0, 172, 0, 0, 0, 0,
ax_anim 2, 0, 173, 0, 0, 0, 0,
ax_anim 2, 0, 173, 0, -2, 0, 0,
ax_anim 3, 0, 173, 0, -3, 0, 0,
ax_anim 4, 0, 172, 0, -6, 0, 0,
ax_anim 3, 0, 174, 0, -3, 0, 0,
ax_anim 2, 0, 174, 0, -2, 0, 0,
ax_anim 2, 0, 174, 0, 0, 0, 0,
ax_anim_terminator
sMedichamAnims_8_8:
ax_anim 40, 0, 175, 0, 0, 0, 0,
ax_anim 2, 0, 176, 0, 0, 0, 0,
ax_anim 2, 0, 176, 0, -2, 0, 0,
ax_anim 3, 0, 176, 0, -3, 0, 0,
ax_anim 4, 0, 175, 0, -6, 0, 0,
ax_anim 3, 0, 177, 0, -3, 0, 0,
ax_anim 2, 0, 177, 0, -2, 0, 0,
ax_anim 2, 0, 177, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sMedichamAnims_9_1:
ax_anim 2, 0, 178, 0, 0, 0, 0,
ax_anim 1, 0, 179, 6, 3, 6, 3,
ax_anim 2, 0, 180, 10, 12, 10, 12,
ax_anim 2, 0, 181, 7, 19, 7, 19,
ax_anim 3, 0, 182, 0, 22, 0, 22,
ax_anim 2, 3, 183, -7, 19, -7, 19,
ax_anim 2, 0, 184, -10, 12, -10, 12,
ax_anim 1, 0, 185, -6, 3, -6, 3,
ax_anim 1, 0, 178, 0, 0, 0, 0,
ax_anim_terminator
sMedichamAnims_9_2:
ax_anim 2, 0, 185, 0, 0, 0, 0,
ax_anim 1, 0, 178, 9, 0, 9, 0,
ax_anim 2, 0, 179, 19, 5, 19, 5,
ax_anim 2, 0, 180, 26, 13, 26, 13,
ax_anim 3, 0, 181, 24, 21, 24, 21,
ax_anim 2, 3, 182, 12, 21, 12, 21,
ax_anim 2, 0, 183, 3, 15, 3, 15,
ax_anim 1, 0, 184, 0, 7, 0, 7,
ax_anim 1, 0, 185, 0, 0, 0, 0,
ax_anim_terminator
sMedichamAnims_9_3:
ax_anim 2, 0, 184, 0, 0, 0, 0,
ax_anim 1, 0, 185, 5, -5, 5, -5,
ax_anim 2, 0, 178, 12, -6, 12, -6,
ax_anim 2, 0, 179, 19, -5, 19, -5,
ax_anim 3, 0, 180, 23, -2, 23, -2,
ax_anim 2, 3, 181, 19, 4, 19, 4,
ax_anim 2, 0, 182, 12, 5, 12, 5,
ax_anim 1, 0, 183, 4, 4, 4, 4,
ax_anim 1, 0, 184, 0, 0, 0, 0,
ax_anim_terminator
sMedichamAnims_9_4:
ax_anim 2, 0, 183, 0, 0, 0, 0,
ax_anim 1, 0, 184, -1, -8, -1, -8,
ax_anim 2, 0, 185, 4, -16, 4, -16,
ax_anim 2, 0, 178, 12, -19, 12, -19,
ax_anim 3, 0, 179, 21, -19, 21, -19,
ax_anim 2, 3, 180, 24, -13, 24, -13,
ax_anim 2, 0, 181, 18, -5, 18, -5,
ax_anim 1, 0, 182, 9, 0, 9, 0,
ax_anim 1, 0, 183, 0, 0, 0, 0,
ax_anim_terminator
sMedichamAnims_9_5:
ax_anim 2, 0, 182, 0, 0, 0, 0,
ax_anim 1, 0, 183, -8, -4, -8, -4,
ax_anim 2, 0, 184, -10, -12, -10, -12,
ax_anim 2, 0, 185, -7, -18, -7, -18,
ax_anim 3, 0, 178, 0, -20, 0, -20,
ax_anim 2, 3, 179, 7, -18, 7, -18,
ax_anim 2, 0, 180, 10, -12, 10, -12,
ax_anim 1, 0, 181, 8, -4, 8, -4,
ax_anim 1, 0, 182, 0, 0, 0, 0,
ax_anim_terminator
sMedichamAnims_9_6:
ax_anim 2, 0, 181, 0, 0, 0, 0,
ax_anim 1, 0, 180, 1, -8, 1, -8,
ax_anim 2, 0, 179, -4, -16, -4, -16,
ax_anim 2, 0, 178, -12, -19, -12, -19,
ax_anim 3, 0, 185, -21, -19, -21, -19,
ax_anim 2, 3, 184, -24, -13, -24, -13,
ax_anim 2, 0, 183, -18, -5, -18, -5,
ax_anim 1, 0, 182, -9, 0, -9, 0,
ax_anim 1, 0, 181, 0, 0, 0, 0,
ax_anim_terminator
sMedichamAnims_9_7:
ax_anim 2, 0, 180, 0, 0, 0, 0,
ax_anim 1, 0, 179, -5, -5, -5, -5,
ax_anim 2, 0, 178, -12, -6, -12, -6,
ax_anim 2, 0, 185, -19, -5, -19, -5,
ax_anim 3, 0, 184, -23, -2, -23, -2,
ax_anim 2, 3, 183, -19, 4, -19, 4,
ax_anim 2, 0, 182, -12, 5, -12, 5,
ax_anim 1, 0, 181, -4, 4, -4, 4,
ax_anim 1, 0, 180, 0, 0, 0, 0,
ax_anim_terminator
sMedichamAnims_9_8:
ax_anim 2, 0, 179, 0, 0, 0, 0,
ax_anim 1, 0, 178, -9, 0, -9, 0,
ax_anim 2, 0, 185, -19, 5, -19, 5,
ax_anim 2, 0, 184, -26, 13, -26, 13,
ax_anim 3, 0, 183, -24, 21, -24, 21,
ax_anim 2, 3, 182, -12, 21, -12, 21,
ax_anim 2, 0, 181, -3, 15, -3, 15,
ax_anim 1, 0, 180, 0, 7, 0, 7,
ax_anim 1, 0, 179, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sMedichamAnims_10_1:
ax_anim 2, 0, 186, 0, 0, 0, 0,
ax_anim 2, 0, 186, 6, 0, 6, 0,
ax_anim 2, 0, 186, -6, 0, -6, 0,
ax_anim 2, 0, 186, 10, 0, 10, 0,
ax_anim 2, 0, 186, -10, 0, -10, 0,
ax_anim 2, 0, 186, 12, 0, 12, 0,
ax_anim 3, 0, 186, -12, 0, -12, 0,
ax_anim 3, 0, 186, 13, 0, 13, 0,
ax_anim 3, 0, 186, -13, 0, -13, 0,
ax_anim 2, 0, 186, 12, 0, 12, 0,
ax_anim 3, 0, 186, -12, 0, -12, 0,
ax_anim 2, 0, 186, 10, 0, 10, 0,
ax_anim 2, 0, 186, -10, 0, -10, 0,
ax_anim 2, 0, 186, 6, 0, 6, 0,
ax_anim 2, 0, 186, -6, 0, -6, 0,
ax_anim 2, 0, 186, 0, 0, 0, 0,
ax_anim_terminator
sMedichamAnims_10_2:
ax_anim 2, 0, 187, 0, 0, 0, 0,
ax_anim 2, 0, 187, 6, -6, 6, -6,
ax_anim 2, 0, 187, -6, 6, -6, 6,
ax_anim 2, 0, 187, 10, -10, 10, -10,
ax_anim 2, 0, 187, -10, 10, -10, 10,
ax_anim 2, 0, 187, 12, -12, 12, -12,
ax_anim 3, 0, 187, -12, 12, -12, 12,
ax_anim 3, 0, 187, 13, -13, 13, -13,
ax_anim 3, 0, 187, -13, 13, -13, 13,
ax_anim 2, 0, 187, 12, -12, 12, -12,
ax_anim 3, 0, 187, -12, 12, -12, 12,
ax_anim 2, 0, 187, 10, -10, 10, -10,
ax_anim 2, 0, 187, -10, 10, -10, 10,
ax_anim 2, 0, 187, 6, -6, 6, -6,
ax_anim 2, 0, 187, -6, 6, -6, 6,
ax_anim 2, 0, 187, 0, 0, 0, 0,
ax_anim_terminator
sMedichamAnims_10_3:
ax_anim 2, 0, 188, 0, 0, 0, 0,
ax_anim 2, 0, 188, 0, -6, 0, -6,
ax_anim 2, 0, 188, 0, 6, 0, 6,
ax_anim 2, 0, 188, 0, -10, 0, -10,
ax_anim 2, 0, 188, 0, 10, 0, 10,
ax_anim 2, 0, 188, 0, -12, 0, -12,
ax_anim 3, 0, 188, 0, 12, 0, 12,
ax_anim 3, 0, 188, 0, -13, 0, -13,
ax_anim 3, 0, 188, 0, 13, 0, 13,
ax_anim 2, 0, 188, 0, -12, 0, -12,
ax_anim 3, 0, 188, 0, 12, 0, 12,
ax_anim 2, 0, 188, 0, -10, 0, -10,
ax_anim 2, 0, 188, 0, 10, 0, 10,
ax_anim 2, 0, 188, 0, -6, 0, -6,
ax_anim 2, 0, 188, 0, 6, 0, 6,
ax_anim 2, 0, 188, 0, 0, 0, 0,
ax_anim_terminator
sMedichamAnims_10_4:
ax_anim 2, 0, 189, 0, 0, 0, 0,
ax_anim 2, 0, 189, -6, -6, -6, -6,
ax_anim 2, 0, 189, 6, 6, 6, 6,
ax_anim 2, 0, 189, -10, -10, -10, -10,
ax_anim 2, 0, 189, 10, 10, 10, 10,
ax_anim 2, 0, 189, -12, -12, -12, -12,
ax_anim 3, 0, 189, 12, 12, 12, 12,
ax_anim 3, 0, 189, -13, -13, -13, -13,
ax_anim 3, 0, 189, 13, 13, 13, 13,
ax_anim 2, 0, 189, -12, -12, -12, -12,
ax_anim 3, 0, 189, 12, 12, 12, 12,
ax_anim 2, 0, 189, -10, -10, -10, -10,
ax_anim 2, 0, 189, 10, 10, 10, 10,
ax_anim 2, 0, 189, -6, -6, -6, -6,
ax_anim 2, 0, 189, 6, 6, 6, 6,
ax_anim 2, 0, 189, 0, 0, 0, 0,
ax_anim_terminator
sMedichamAnims_10_5:
ax_anim 2, 0, 190, 0, 0, 0, 0,
ax_anim 2, 0, 190, 6, 0, 6, 0,
ax_anim 2, 0, 190, -6, 0, -6, 0,
ax_anim 2, 0, 190, 10, 0, 10, 0,
ax_anim 2, 0, 190, -10, 0, -10, 0,
ax_anim 2, 0, 190, 12, 0, 12, 0,
ax_anim 3, 0, 190, -12, 0, -12, 0,
ax_anim 3, 0, 190, 13, 0, 13, 0,
ax_anim 3, 0, 190, -13, 0, -13, 0,
ax_anim 2, 0, 190, 12, 0, 12, 0,
ax_anim 3, 0, 190, -12, 0, -12, 0,
ax_anim 2, 0, 190, 10, 0, 10, 0,
ax_anim 2, 0, 190, -10, 0, -10, 0,
ax_anim 2, 0, 190, 6, 0, 6, 0,
ax_anim 2, 0, 190, -6, 0, -6, 0,
ax_anim 2, 0, 190, 0, 0, 0, 0,
ax_anim_terminator
sMedichamAnims_10_6:
ax_anim 2, 0, 191, 0, 0, 0, 0,
ax_anim 2, 0, 191, 6, -6, 6, -6,
ax_anim 2, 0, 191, -6, 6, -6, 6,
ax_anim 2, 0, 191, 10, -10, 10, -10,
ax_anim 2, 0, 191, -10, 10, -10, 10,
ax_anim 2, 0, 191, 12, -12, 12, -12,
ax_anim 3, 0, 191, -12, 12, -12, 12,
ax_anim 3, 0, 191, 13, -13, 13, -13,
ax_anim 3, 0, 191, -13, 13, -13, 13,
ax_anim 2, 0, 191, 12, -12, 12, -12,
ax_anim 3, 0, 191, -12, 12, -12, 12,
ax_anim 2, 0, 191, 10, -10, 10, -10,
ax_anim 2, 0, 191, -10, 10, -10, 10,
ax_anim 2, 0, 191, 6, -6, 6, -6,
ax_anim 2, 0, 191, -6, 6, -6, 6,
ax_anim 2, 0, 191, 0, 0, 0, 0,
ax_anim_terminator
sMedichamAnims_10_7:
ax_anim 2, 0, 192, 0, 0, 0, 0,
ax_anim 2, 0, 192, 0, -6, 0, -6,
ax_anim 2, 0, 192, 0, 6, 0, 6,
ax_anim 2, 0, 192, 0, -10, 0, -10,
ax_anim 2, 0, 192, 0, 10, 0, 10,
ax_anim 2, 0, 192, 0, -12, 0, -12,
ax_anim 3, 0, 192, 0, 12, 0, 12,
ax_anim 3, 0, 192, 0, -13, 0, -13,
ax_anim 3, 0, 192, 0, 13, 0, 13,
ax_anim 2, 0, 192, 0, -12, 0, -12,
ax_anim 3, 0, 192, 0, 12, 0, 12,
ax_anim 2, 0, 192, 0, -10, 0, -10,
ax_anim 2, 0, 192, 0, 10, 0, 10,
ax_anim 2, 0, 192, 0, -6, 0, -6,
ax_anim 2, 0, 192, 0, 6, 0, 6,
ax_anim 2, 0, 192, 0, 0, 0, 0,
ax_anim_terminator
sMedichamAnims_10_8:
ax_anim 2, 0, 193, 0, 0, 0, 0,
ax_anim 2, 0, 193, -6, -6, -6, -6,
ax_anim 2, 0, 193, 6, 6, 6, 6,
ax_anim 2, 0, 193, -10, -10, -10, -10,
ax_anim 2, 0, 193, 10, 10, 10, 10,
ax_anim 2, 0, 193, -12, -12, -12, -12,
ax_anim 3, 0, 193, 12, 12, 12, 12,
ax_anim 3, 0, 193, -13, -13, -13, -13,
ax_anim 3, 0, 193, 13, 13, 13, 13,
ax_anim 2, 0, 193, -12, -12, -12, -12,
ax_anim 3, 0, 193, 12, 12, 12, 12,
ax_anim 2, 0, 193, -10, -10, -10, -10,
ax_anim 2, 0, 193, 10, 10, 10, 10,
ax_anim 2, 0, 193, -6, -6, -6, -6,
ax_anim 2, 0, 193, 6, 6, 6, 6,
ax_anim 2, 0, 193, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sMedichamAnims_11_1:
ax_anim 2, 0, 194, 0, 0, 0, 0,
ax_anim 1, 0, 196, 0, -10, 0, 0,
ax_anim 2, 0, 196, 0, -16, 0, 0,
ax_anim 3, 0, 196, 0, -20, 0, 0,
ax_anim 4, 0, 196, 0, -21, 0, 0,
ax_anim 4, 0, 194, 0, -22, 0, 0,
ax_anim 3, 0, 195, 0, -19, 0, 0,
ax_anim 2, 0, 195, 0, -17, 0, 0,
ax_anim 1, 0, 195, 0, -12, 0, 0,
ax_anim 2, 2, 194, 0, 0, 0, 0,
ax_anim_terminator
sMedichamAnims_11_2:
ax_anim 2, 0, 197, 0, 0, 0, 0,
ax_anim 1, 0, 199, 0, -10, 0, 0,
ax_anim 2, 0, 199, 0, -16, 0, 0,
ax_anim 3, 0, 199, 0, -20, 0, 0,
ax_anim 4, 0, 199, 0, -21, 0, 0,
ax_anim 4, 0, 197, 0, -21, 0, 0,
ax_anim 3, 0, 198, 0, -18, 0, 0,
ax_anim 2, 0, 198, 0, -16, 0, 0,
ax_anim 1, 0, 198, 0, -12, 0, 0,
ax_anim 2, 2, 197, 0, 0, 0, 0,
ax_anim_terminator
sMedichamAnims_11_3:
ax_anim 2, 0, 200, 0, 0, 0, 0,
ax_anim 1, 0, 202, 0, -10, 0, 0,
ax_anim 2, 0, 202, 0, -16, 0, 0,
ax_anim 3, 0, 202, 0, -20, 0, 0,
ax_anim 4, 0, 202, 0, -21, 0, 0,
ax_anim 4, 0, 200, 0, -23, 0, 0,
ax_anim 3, 0, 201, 0, -20, 0, 0,
ax_anim 2, 0, 201, 0, -18, 0, 0,
ax_anim 1, 0, 201, 0, -12, 0, 0,
ax_anim 2, 2, 200, 0, 0, 0, 0,
ax_anim_terminator
sMedichamAnims_11_4:
ax_anim 2, 0, 203, 0, 0, 0, 0,
ax_anim 1, 0, 205, 0, -10, 0, 0,
ax_anim 2, 0, 205, 0, -16, 0, 0,
ax_anim 3, 0, 205, 0, -20, 0, 0,
ax_anim 4, 0, 205, 0, -21, 0, 0,
ax_anim 4, 0, 204, 0, -21, 0, 0,
ax_anim 3, 0, 204, 0, -20, 0, 0,
ax_anim 2, 0, 204, 0, -17, 0, 0,
ax_anim 1, 0, 204, 0, -11, 0, 0,
ax_anim 2, 2, 203, 0, 0, 0, 0,
ax_anim_terminator
sMedichamAnims_11_5:
ax_anim 2, 0, 206, 0, 0, 0, 0,
ax_anim 1, 0, 208, 0, -10, 0, 0,
ax_anim 2, 0, 208, 0, -16, 0, 0,
ax_anim 3, 0, 208, 0, -20, 0, 0,
ax_anim 4, 0, 208, 0, -22, 0, 0,
ax_anim 4, 0, 207, 0, -21, 0, 0,
ax_anim 3, 0, 207, 0, -20, 0, 0,
ax_anim 2, 0, 207, 0, -18, 0, 0,
ax_anim 1, 0, 207, 0, -12, 0, 0,
ax_anim 2, 2, 206, 0, 0, 0, 0,
ax_anim_terminator
sMedichamAnims_11_6:
ax_anim 2, 0, 209, 0, 0, 0, 0,
ax_anim 1, 0, 211, 0, -10, 0, 0,
ax_anim 2, 0, 211, 0, -16, 0, 0,
ax_anim 3, 0, 211, 0, -20, 0, 0,
ax_anim 4, 0, 211, 0, -21, 0, 0,
ax_anim 4, 0, 210, 0, -21, 0, 0,
ax_anim 3, 0, 210, 0, -20, 0, 0,
ax_anim 2, 0, 210, 0, -17, 0, 0,
ax_anim 1, 0, 210, 0, -11, 0, 0,
ax_anim 2, 2, 209, 0, 0, 0, 0,
ax_anim_terminator
sMedichamAnims_11_7:
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 1, 0, 214, 0, -10, 0, 0,
ax_anim 2, 0, 214, 0, -16, 0, 0,
ax_anim 3, 0, 214, 0, -20, 0, 0,
ax_anim 4, 0, 214, 0, -21, 0, 0,
ax_anim 4, 0, 212, 0, -23, 0, 0,
ax_anim 3, 0, 213, 0, -20, 0, 0,
ax_anim 2, 0, 213, 0, -18, 0, 0,
ax_anim 1, 0, 213, 0, -12, 0, 0,
ax_anim 2, 2, 212, 0, 0, 0, 0,
ax_anim_terminator
sMedichamAnims_11_8:
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 1, 0, 217, 0, -10, 0, 0,
ax_anim 2, 0, 217, 0, -16, 0, 0,
ax_anim 3, 0, 217, 0, -20, 0, 0,
ax_anim 4, 0, 217, 0, -21, 0, 0,
ax_anim 4, 0, 215, 0, -21, 0, 0,
ax_anim 3, 0, 216, 0, -18, 0, 0,
ax_anim 2, 0, 216, 0, -16, 0, 0,
ax_anim 1, 0, 216, 0, -12, 0, 0,
ax_anim 2, 2, 215, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sMedichamAnims_12_1:
ax_anim 2, 0, 218, 1, 0, 1, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 218, 1, 0, 1, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 218, 1, 0, 1, 0,
ax_anim 2, 2, 218, 0, 0, 0, 0,
ax_anim 2, 0, 218, 1, 0, 1, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 218, 1, 0, 1, 0,
ax_anim 2, 1, 218, 0, 0, 0, 0,
ax_anim_terminator
sMedichamAnims_12_2:
ax_anim 2, 0, 225, 1, -1, 1, -1,
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 2, 0, 225, 1, -1, 1, -1,
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 2, 0, 225, 1, -1, 1, -1,
ax_anim 2, 2, 225, 0, 0, 0, 0,
ax_anim 2, 0, 225, 1, -1, 1, -1,
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 2, 0, 225, 1, -1, 1, -1,
ax_anim 2, 1, 225, 0, 0, 0, 0,
ax_anim_terminator
sMedichamAnims_12_3:
ax_anim 2, 0, 224, 0, -1, 0, -1,
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 2, 0, 224, 0, -1, 0, -1,
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 2, 0, 224, 0, -1, 0, -1,
ax_anim 2, 2, 224, 0, 0, 0, 0,
ax_anim 2, 0, 224, 0, -1, 0, -1,
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 2, 0, 224, 0, -1, 0, -1,
ax_anim 2, 1, 224, 0, 0, 0, 0,
ax_anim_terminator
sMedichamAnims_12_4:
ax_anim 2, 0, 223, -1, -1, -1, -1,
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 2, 0, 223, -1, -1, -1, -1,
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 2, 0, 223, -1, -1, -1, -1,
ax_anim 2, 2, 223, 0, 0, 0, 0,
ax_anim 2, 0, 223, -1, -1, -1, -1,
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 2, 0, 223, -1, -1, -1, -1,
ax_anim 2, 1, 223, 0, 0, 0, 0,
ax_anim_terminator
sMedichamAnims_12_5:
ax_anim 2, 0, 222, 1, 0, 1, 0,
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 0, 222, 1, 0, 1, 0,
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 0, 222, 1, 0, 1, 0,
ax_anim 2, 2, 222, 0, 0, 0, 0,
ax_anim 2, 0, 222, 1, 0, 1, 0,
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 0, 222, 1, 0, 1, 0,
ax_anim 2, 1, 222, 0, 0, 0, 0,
ax_anim_terminator
sMedichamAnims_12_6:
ax_anim 2, 0, 221, 1, -1, 1, -1,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 221, 1, -1, 1, -1,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 221, 1, -1, 1, -1,
ax_anim 2, 2, 221, 0, 0, 0, 0,
ax_anim 2, 0, 221, 1, -1, 1, -1,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 221, 1, -1, 1, -1,
ax_anim 2, 1, 221, 0, 0, 0, 0,
ax_anim_terminator
sMedichamAnims_12_7:
ax_anim 2, 0, 220, 0, -1, 0, -1,
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, -1, 0, -1,
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, -1, 0, -1,
ax_anim 2, 2, 220, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, -1, 0, -1,
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, -1, 0, -1,
ax_anim 2, 1, 220, 0, 0, 0, 0,
ax_anim_terminator
sMedichamAnims_12_8:
ax_anim 2, 0, 219, -1, -1, -1, -1,
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 0, 219, -1, -1, -1, -1,
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 0, 219, -1, -1, -1, -1,
ax_anim 2, 2, 219, 0, 0, 0, 0,
ax_anim 2, 0, 219, -1, -1, -1, -1,
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 0, 219, -1, -1, -1, -1,
ax_anim 2, 1, 219, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sMedichamAnims_13_1:
ax_anim 2, 0, 226, 0, 0, 0, 0,
ax_anim 2, 0, 227, 0, 0, 0, 0,
ax_anim 2, 0, 228, 0, 0, 0, 0,
ax_anim 2, 0, 229, 0, 0, 0, 0,
ax_anim 2, 0, 230, 0, 0, 0, 0,
ax_anim 2, 0, 231, 0, 0, 0, 0,
ax_anim 2, 0, 232, 0, 0, 0, 0,
ax_anim 2, 0, 233, 0, 0, 0, 0,
ax_anim 2, 2, 226, 0, 0, 0, 0,
ax_anim_terminator
sMedichamAnims_13_2:
ax_anim 2, 0, 233, 0, 0, 0, 0,
ax_anim 2, 0, 226, 0, 0, 0, 0,
ax_anim 2, 0, 227, 0, 0, 0, 0,
ax_anim 2, 0, 228, 0, 0, 0, 0,
ax_anim 2, 0, 229, 0, 0, 0, 0,
ax_anim 2, 0, 230, 0, 0, 0, 0,
ax_anim 2, 0, 231, 0, 0, 0, 0,
ax_anim 2, 0, 232, 0, 0, 0, 0,
ax_anim 2, 2, 233, 0, 0, 0, 0,
ax_anim_terminator
sMedichamAnims_13_3:
ax_anim 2, 0, 232, 0, 0, 0, 0,
ax_anim 2, 0, 233, 0, 0, 0, 0,
ax_anim 2, 0, 226, 0, 0, 0, 0,
ax_anim 2, 0, 227, 0, 0, 0, 0,
ax_anim 2, 0, 228, 0, 0, 0, 0,
ax_anim 2, 0, 229, 0, 0, 0, 0,
ax_anim 2, 0, 230, 0, 0, 0, 0,
ax_anim 2, 0, 231, 0, 0, 0, 0,
ax_anim 2, 2, 232, 0, 0, 0, 0,
ax_anim_terminator
sMedichamAnims_13_4:
ax_anim 2, 0, 231, 0, 0, 0, 0,
ax_anim 2, 0, 232, 0, 0, 0, 0,
ax_anim 2, 0, 233, 0, 0, 0, 0,
ax_anim 2, 0, 226, 0, 0, 0, 0,
ax_anim 2, 0, 227, 0, 0, 0, 0,
ax_anim 2, 0, 228, 0, 0, 0, 0,
ax_anim 2, 0, 229, 0, 0, 0, 0,
ax_anim 2, 0, 230, 0, 0, 0, 0,
ax_anim 2, 2, 231, 0, 0, 0, 0,
ax_anim_terminator
sMedichamAnims_13_5:
ax_anim 2, 0, 230, 0, 0, 0, 0,
ax_anim 2, 0, 231, 0, 0, 0, 0,
ax_anim 2, 0, 232, 0, 0, 0, 0,
ax_anim 2, 0, 233, 0, 0, 0, 0,
ax_anim 2, 0, 226, 0, 0, 0, 0,
ax_anim 2, 0, 227, 0, 0, 0, 0,
ax_anim 2, 0, 228, 0, 0, 0, 0,
ax_anim 2, 0, 229, 0, 0, 0, 0,
ax_anim 2, 2, 230, 0, 0, 0, 0,
ax_anim_terminator
sMedichamAnims_13_6:
ax_anim 2, 0, 229, 0, 0, 0, 0,
ax_anim 2, 0, 230, 0, 0, 0, 0,
ax_anim 2, 0, 231, 0, 0, 0, 0,
ax_anim 2, 0, 232, 0, 0, 0, 0,
ax_anim 2, 0, 233, 0, 0, 0, 0,
ax_anim 2, 0, 226, 0, 0, 0, 0,
ax_anim 2, 0, 227, 0, 0, 0, 0,
ax_anim 2, 0, 228, 0, 0, 0, 0,
ax_anim 2, 2, 229, 0, 0, 0, 0,
ax_anim_terminator
sMedichamAnims_13_7:
ax_anim 2, 0, 228, 0, 0, 0, 0,
ax_anim 2, 0, 229, 0, 0, 0, 0,
ax_anim 2, 0, 230, 0, 0, 0, 0,
ax_anim 2, 0, 231, 0, 0, 0, 0,
ax_anim 2, 0, 232, 0, 0, 0, 0,
ax_anim 2, 0, 233, 0, 0, 0, 0,
ax_anim 2, 0, 226, 0, 0, 0, 0,
ax_anim 2, 0, 227, 0, 0, 0, 0,
ax_anim 2, 2, 228, 0, 0, 0, 0,
ax_anim_terminator
sMedichamAnims_13_8:
ax_anim 2, 0, 227, 0, 0, 0, 0,
ax_anim 2, 0, 228, 0, 0, 0, 0,
ax_anim 2, 0, 229, 0, 0, 0, 0,
ax_anim 2, 0, 230, 0, 0, 0, 0,
ax_anim 2, 0, 231, 0, 0, 0, 0,
ax_anim 2, 0, 232, 0, 0, 0, 0,
ax_anim 2, 0, 233, 0, 0, 0, 0,
ax_anim 2, 0, 226, 0, 0, 0, 0,
ax_anim 2, 2, 227, 0, 0, 0, 0,
ax_anim_terminator
sMedichamGfx1:
.incbin "baserom.gba", 0x1287828, 0x200
sMedichamSprites1:
ax_sprite sMedichamGfx1, 0x200
ax_sprite_terminator
sMedichamGfx2:
.incbin "baserom.gba", 0x1287A38, 0x200
sMedichamSprites2:
ax_sprite sMedichamGfx2, 0x200
ax_sprite_terminator
sMedichamGfx3:
.incbin "baserom.gba", 0x1287C48, 0x200
sMedichamSprites3:
ax_sprite sMedichamGfx3, 0x200
ax_sprite_terminator
sMedichamGfx4:
.incbin "baserom.gba", 0x1287E58, 0x200
sMedichamSprites4:
ax_sprite sMedichamGfx4, 0x200
ax_sprite_terminator
sMedichamGfx5:
.incbin "baserom.gba", 0x1288068, 0x200
sMedichamSprites5:
ax_sprite sMedichamGfx5, 0x200
ax_sprite_terminator
sMedichamGfx6:
.incbin "baserom.gba", 0x1288278, 0x200
sMedichamSprites6:
ax_sprite sMedichamGfx6, 0x200
ax_sprite_terminator
sMedichamGfx7:
.incbin "baserom.gba", 0x1288488, 0x200
sMedichamSprites7:
ax_sprite sMedichamGfx7, 0x200
ax_sprite_terminator
sMedichamGfx8:
.incbin "baserom.gba", 0x1288698, 0x200
sMedichamSprites8:
ax_sprite sMedichamGfx8, 0x200
ax_sprite_terminator
sMedichamGfx9:
.incbin "baserom.gba", 0x12888A8, 0x200
sMedichamSprites9:
ax_sprite sMedichamGfx9, 0x200
ax_sprite_terminator
sMedichamGfx10:
.incbin "baserom.gba", 0x1288AB8, 0x200
sMedichamSprites10:
ax_sprite sMedichamGfx10, 0x200
ax_sprite_terminator
sMedichamGfx11:
.incbin "baserom.gba", 0x1288CC8, 0x200
sMedichamSprites11:
ax_sprite sMedichamGfx11, 0x200
ax_sprite_terminator
sMedichamGfx12:
.incbin "baserom.gba", 0x1288ED8, 0x200
sMedichamSprites12:
ax_sprite sMedichamGfx12, 0x200
ax_sprite_terminator
sMedichamGfx13:
.incbin "baserom.gba", 0x12890E8, 0x200
sMedichamSprites13:
ax_sprite sMedichamGfx13, 0x200
ax_sprite_terminator
sMedichamGfx14:
.incbin "baserom.gba", 0x12892F8, 0x200
sMedichamSprites14:
ax_sprite sMedichamGfx14, 0x200
ax_sprite_terminator
sMedichamGfx15:
.incbin "baserom.gba", 0x1289508, 0x200
sMedichamSprites15:
ax_sprite sMedichamGfx15, 0x200
ax_sprite_terminator
sMedichamGfx16:
.incbin "baserom.gba", 0x1289718, 0x20
sMedichamGfx16_1:
.incbin "baserom.gba", 0x1289738, 0x60
sMedichamGfx16_2:
.incbin "baserom.gba", 0x1289798, 0x60
sMedichamGfx16_3:
.incbin "baserom.gba", 0x12897F8, 0x60
sMedichamSprites16:
ax_sprite 0, 0x20
ax_sprite sMedichamGfx16, 0x20
ax_sprite 0, 0x40
ax_sprite sMedichamGfx16_1, 0x60
ax_sprite 0, 0x20
ax_sprite sMedichamGfx16_2, 0x60
ax_sprite 0, 0x20
ax_sprite sMedichamGfx16_3, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sMedichamGfx17:
.incbin "baserom.gba", 0x12898A8, 0x20
sMedichamGfx17_1:
.incbin "baserom.gba", 0x12898C8, 0x20
sMedichamGfx17_2:
.incbin "baserom.gba", 0x12898E8, 0x40
sMedichamGfx17_3:
.incbin "baserom.gba", 0x1289928, 0x40
sMedichamSprites17:
ax_sprite 0, 0x40
ax_sprite sMedichamGfx17, 0x20
ax_sprite 0, 0x60
ax_sprite sMedichamGfx17_1, 0x20
ax_sprite 0, 0x40
ax_sprite sMedichamGfx17_2, 0x40
ax_sprite 0, 0x40
ax_sprite sMedichamGfx17_3, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sMedichamGfx18:
.incbin "baserom.gba", 0x12899B8, 0x40
sMedichamGfx18_1:
.incbin "baserom.gba", 0x12899F8, 0x60
sMedichamGfx18_2:
.incbin "baserom.gba", 0x1289A58, 0x60
sMedichamGfx18_3:
.incbin "baserom.gba", 0x1289AB8, 0x40
sMedichamSprites18:
ax_sprite sMedichamGfx18, 0x40
ax_sprite 0, 0x40
ax_sprite sMedichamGfx18_1, 0x60
ax_sprite 0, 0x20
ax_sprite sMedichamGfx18_2, 0x60
ax_sprite 0, 0x40
ax_sprite sMedichamGfx18_3, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sMedichamGfx19:
.incbin "baserom.gba", 0x1289B40, 0x40
sMedichamGfx19_1:
.incbin "baserom.gba", 0x1289B80, 0x60
sMedichamGfx19_2:
.incbin "baserom.gba", 0x1289BE0, 0x60
sMedichamGfx19_3:
.incbin "baserom.gba", 0x1289C40, 0x60
sMedichamSprites19:
ax_sprite 0, 0x20
ax_sprite sMedichamGfx19, 0x40
ax_sprite 0, 0x20
ax_sprite sMedichamGfx19_1, 0x60
ax_sprite 0, 0x20
ax_sprite sMedichamGfx19_2, 0x60
ax_sprite 0, 0x20
ax_sprite sMedichamGfx19_3, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sMedichamGfx20:
.incbin "baserom.gba", 0x1289CF0, 0xA0
sMedichamGfx20_1:
.incbin "baserom.gba", 0x1289D90, 0x40
sMedichamSprites20:
ax_sprite 0, 0xc0
ax_sprite sMedichamGfx20, 0xa0
ax_sprite 0, 0x20
ax_sprite sMedichamGfx20_1, 0x40
ax_sprite 0, 0x40
ax_sprite_terminator
sMedichamGfx21:
.incbin "baserom.gba", 0x1289E00, 0x40
sMedichamGfx21_1:
.incbin "baserom.gba", 0x1289E40, 0x40
sMedichamGfx21_2:
.incbin "baserom.gba", 0x1289E80, 0x60
sMedichamGfx21_3:
.incbin "baserom.gba", 0x1289EE0, 0x60
sMedichamSprites21:
ax_sprite 0, 0x20
ax_sprite sMedichamGfx21, 0x40
ax_sprite 0, 0x40
ax_sprite sMedichamGfx21_1, 0x40
ax_sprite 0, 0x20
ax_sprite sMedichamGfx21_2, 0x60
ax_sprite 0, 0x20
ax_sprite sMedichamGfx21_3, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sMedichamGfx22:
.incbin "baserom.gba", 0x1289F90, 0x40
sMedichamGfx22_1:
.incbin "baserom.gba", 0x1289FD0, 0x60
sMedichamGfx22_2:
.incbin "baserom.gba", 0x128A030, 0x60
sMedichamGfx22_3:
.incbin "baserom.gba", 0x128A090, 0x40
sMedichamSprites22:
ax_sprite 0, 0x20
ax_sprite sMedichamGfx22, 0x40
ax_sprite 0, 0x20
ax_sprite sMedichamGfx22_1, 0x60
ax_sprite 0, 0x20
ax_sprite sMedichamGfx22_2, 0x60
ax_sprite 0, 0x20
ax_sprite sMedichamGfx22_3, 0x40
ax_sprite 0, 0x40
ax_sprite_terminator
sMedichamGfx23:
.incbin "baserom.gba", 0x128A120, 0x40
sMedichamGfx23_1:
.incbin "baserom.gba", 0x128A160, 0xC0
sMedichamSprites23:
ax_sprite 0, 0x80
ax_sprite sMedichamGfx23, 0x40
ax_sprite 0, 0x40
ax_sprite sMedichamGfx23_1, 0xc0
ax_sprite 0, 0x40
ax_sprite_terminator
sMedichamGfx24:
.incbin "baserom.gba", 0x128A250, 0x40
sMedichamGfx24_1:
.incbin "baserom.gba", 0x128A290, 0x40
sMedichamGfx24_2:
.incbin "baserom.gba", 0x128A2D0, 0x60
sMedichamGfx24_3:
.incbin "baserom.gba", 0x128A330, 0x80
sMedichamSprites24:
ax_sprite 0, 0x20
ax_sprite sMedichamGfx24, 0x40
ax_sprite 0, 0x40
ax_sprite sMedichamGfx24_1, 0x40
ax_sprite 0, 0x20
ax_sprite sMedichamGfx24_2, 0x60
ax_sprite 0, 0x20
ax_sprite sMedichamGfx24_3, 0x80
ax_sprite_terminator
sMedichamGfx25:
.incbin "baserom.gba", 0x128A3F8, 0x40
sMedichamGfx25_1:
.incbin "baserom.gba", 0x128A438, 0x60
sMedichamGfx25_2:
.incbin "baserom.gba", 0x128A498, 0x60
sMedichamGfx25_3:
.incbin "baserom.gba", 0x128A4F8, 0x60
sMedichamSprites25:
ax_sprite 0, 0x40
ax_sprite sMedichamGfx25, 0x40
ax_sprite 0, 0x20
ax_sprite sMedichamGfx25_1, 0x60
ax_sprite 0, 0x20
ax_sprite sMedichamGfx25_2, 0x60
ax_sprite 0, 0x20
ax_sprite sMedichamGfx25_3, 0x60
ax_sprite_terminator
sMedichamGfx26:
.incbin "baserom.gba", 0x128A5A0, 0x40
sMedichamGfx26_1:
.incbin "baserom.gba", 0x128A5E0, 0x40
sMedichamGfx26_2:
.incbin "baserom.gba", 0x128A620, 0x40
sMedichamSprites26:
ax_sprite sMedichamGfx26, 0x40
ax_sprite 0, 0x40
ax_sprite sMedichamGfx26_1, 0x40
ax_sprite 0, 0x60
ax_sprite sMedichamGfx26_2, 0x40
ax_sprite 0, 0xa0
ax_sprite_terminator
sMedichamGfx27:
.incbin "baserom.gba", 0x128A698, 0x60
sMedichamGfx27_1:
.incbin "baserom.gba", 0x128A6F8, 0x60
sMedichamGfx27_2:
.incbin "baserom.gba", 0x128A758, 0x60
sMedichamGfx27_3:
.incbin "baserom.gba", 0x128A7B8, 0x40
sMedichamSprites27:
ax_sprite sMedichamGfx27, 0x60
ax_sprite 0, 0x20
ax_sprite sMedichamGfx27_1, 0x60
ax_sprite 0, 0x20
ax_sprite sMedichamGfx27_2, 0x60
ax_sprite 0, 0x40
ax_sprite sMedichamGfx27_3, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sMedichamGfx28:
.incbin "baserom.gba", 0x128A840, 0x20
sMedichamGfx28_1:
.incbin "baserom.gba", 0x128A860, 0x60
sMedichamGfx28_2:
.incbin "baserom.gba", 0x128A8C0, 0x60
sMedichamGfx28_3:
.incbin "baserom.gba", 0x128A920, 0x60
sMedichamSprites28:
ax_sprite 0, 0x20
ax_sprite sMedichamGfx28, 0x20
ax_sprite 0, 0x40
ax_sprite sMedichamGfx28_1, 0x60
ax_sprite 0, 0x20
ax_sprite sMedichamGfx28_2, 0x60
ax_sprite 0, 0x20
ax_sprite sMedichamGfx28_3, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sMedichamGfx29:
.incbin "baserom.gba", 0x128A9D0, 0x40
sMedichamGfx29_1:
.incbin "baserom.gba", 0x128AA10, 0x40
sMedichamGfx29_2:
.incbin "baserom.gba", 0x128AA50, 0x20
sMedichamGfx29_3:
.incbin "baserom.gba", 0x128AA70, 0x20
sMedichamSprites29:
ax_sprite sMedichamGfx29, 0x40
ax_sprite 0, 0x40
ax_sprite sMedichamGfx29_1, 0x40
ax_sprite 0, 0x60
ax_sprite sMedichamGfx29_2, 0x20
ax_sprite 0, 0x60
ax_sprite sMedichamGfx29_3, 0x20
ax_sprite 0, 0x40
ax_sprite_terminator
sMedichamGfx30:
.incbin "baserom.gba", 0x128AAD8, 0x40
sMedichamGfx30_1:
.incbin "baserom.gba", 0x128AB18, 0x40
sMedichamGfx30_2:
.incbin "baserom.gba", 0x128AB58, 0x60
sMedichamGfx30_3:
.incbin "baserom.gba", 0x128ABB8, 0x40
sMedichamSprites30:
ax_sprite 0, 0x20
ax_sprite sMedichamGfx30, 0x40
ax_sprite 0, 0x40
ax_sprite sMedichamGfx30_1, 0x40
ax_sprite 0, 0x20
ax_sprite sMedichamGfx30_2, 0x60
ax_sprite 0, 0x40
ax_sprite sMedichamGfx30_3, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sMedichamGfx31:
.incbin "baserom.gba", 0x128AC48, 0x20
sMedichamSprites31:
ax_sprite sMedichamGfx31, 0x20
ax_sprite_terminator
sMedichamGfx32:
.incbin "baserom.gba", 0x128AC78, 0x20
sMedichamSprites32:
ax_sprite sMedichamGfx32, 0x20
ax_sprite_terminator
sMedichamGfx33:
.incbin "baserom.gba", 0x128ACA8, 0x80
sMedichamSprites33:
ax_sprite sMedichamGfx33, 0x80
ax_sprite_terminator
sMedichamGfx34:
.incbin "baserom.gba", 0x128AD38, 0x80
sMedichamSprites34:
ax_sprite sMedichamGfx34, 0x80
ax_sprite_terminator
sMedichamGfx35:
.incbin "baserom.gba", 0x128ADC8, 0x200
sMedichamSprites35:
ax_sprite sMedichamGfx35, 0x200
ax_sprite_terminator
sMedichamGfx36:
.incbin "baserom.gba", 0x128AFD8, 0x200
sMedichamSprites36:
ax_sprite sMedichamGfx36, 0x200
ax_sprite_terminator
sMedichamGfx37:
.incbin "baserom.gba", 0x128B1E8, 0x80
sMedichamSprites37:
ax_sprite sMedichamGfx37, 0x80
ax_sprite_terminator
sMedichamGfx38:
.incbin "baserom.gba", 0x128B278, 0x20
sMedichamSprites38:
ax_sprite sMedichamGfx38, 0x20
ax_sprite_terminator
sMedichamGfx39:
.incbin "baserom.gba", 0x128B2A8, 0x100
sMedichamSprites39:
ax_sprite sMedichamGfx39, 0x100
ax_sprite_terminator
sMedichamGfx40:
.incbin "baserom.gba", 0x128B3B8, 0x200
sMedichamSprites40:
ax_sprite sMedichamGfx40, 0x200
ax_sprite_terminator
sMedichamGfx41:
.incbin "baserom.gba", 0x128B5C8, 0x200
sMedichamSprites41:
ax_sprite sMedichamGfx41, 0x200
ax_sprite_terminator
sMedichamGfx42:
.incbin "baserom.gba", 0x128B7D8, 0x200
sMedichamSprites42:
ax_sprite sMedichamGfx42, 0x200
ax_sprite_terminator
sMedichamGfx43:
.incbin "baserom.gba", 0x128B9E8, 0x200
sMedichamSprites43:
ax_sprite sMedichamGfx43, 0x200
ax_sprite_terminator
sAxPosesMedicham:
.4byte sMedichamPose1
.4byte sMedichamPose2
.4byte sMedichamPose3
.4byte sMedichamPose4
.4byte sMedichamPose5
.4byte sMedichamPose6
.4byte sMedichamPose7
.4byte sMedichamPose8
.4byte sMedichamPose9
.4byte sMedichamPose10
.4byte sMedichamPose11
.4byte sMedichamPose12
.4byte sMedichamPose13
.4byte sMedichamPose14
.4byte sMedichamPose15
.4byte sMedichamPose16
.4byte sMedichamPose17
.4byte sMedichamPose18
.4byte sMedichamPose19
.4byte sMedichamPose20
.4byte sMedichamPose21
.4byte sMedichamPose22
.4byte sMedichamPose23
.4byte sMedichamPose24
.4byte sMedichamPose25
.4byte sMedichamPose26
.4byte sMedichamPose27
.4byte sMedichamPose28
.4byte sMedichamPose29
.4byte sMedichamPose30
.4byte sMedichamPose31
.4byte sMedichamPose32
.4byte sMedichamPose33
.4byte sMedichamPose34
.4byte sMedichamPose35
.4byte sMedichamPose36
.4byte sMedichamPose37
.4byte sMedichamPose38
.4byte sMedichamPose39
.4byte sMedichamPose40
.4byte sMedichamPose41
.4byte sMedichamPose42
.4byte sMedichamPose43
.4byte sMedichamPose44
.4byte sMedichamPose45
.4byte sMedichamPose46
.4byte sMedichamPose47
.4byte sMedichamPose48
.4byte sMedichamPose49
.4byte sMedichamPose50
.4byte sMedichamPose51
.4byte sMedichamPose52
.4byte sMedichamPose53
.4byte sMedichamPose54
.4byte sMedichamPose55
.4byte sMedichamPose56
.4byte sMedichamPose57
.4byte sMedichamPose58
.4byte sMedichamPose59
.4byte sMedichamPose60
.4byte sMedichamPose61
.4byte sMedichamPose62
.4byte sMedichamPose63
.4byte sMedichamPose64
.4byte sMedichamPose65
.4byte sMedichamPose66
.4byte sMedichamPose67
.4byte sMedichamPose68
.4byte sMedichamPose69
.4byte sMedichamPose70
.4byte sMedichamPose71
.4byte sMedichamPose72
.4byte sMedichamPose73
.4byte sMedichamPose74
.4byte sMedichamPose75
.4byte sMedichamPose76
.4byte sMedichamPose77
.4byte sMedichamPose78
.4byte sMedichamPose79
.4byte sMedichamPose80
.4byte sMedichamPose81
.4byte sMedichamPose82
.4byte sMedichamPose83
.4byte sMedichamPose84
.4byte sMedichamPose85
.4byte sMedichamPose86
.4byte sMedichamPose87
.4byte sMedichamPose88
.4byte sMedichamPose89
.4byte sMedichamPose90
.4byte sMedichamPose91
.4byte sMedichamPose92
.4byte sMedichamPose93
.4byte sMedichamPose94
.4byte sMedichamPose95
.4byte sMedichamPose96
.4byte sMedichamPose97
.4byte sMedichamPose98
.4byte sMedichamPose99
.4byte sMedichamPose100
.4byte sMedichamPose101
.4byte sMedichamPose102
.4byte sMedichamPose103
.4byte sMedichamPose104
.4byte sMedichamPose105
.4byte sMedichamPose106
.4byte sMedichamPose107
.4byte sMedichamPose108
.4byte sMedichamPose109
.4byte sMedichamPose110
.4byte sMedichamPose111
.4byte sMedichamPose112
.4byte sMedichamPose113
.4byte sMedichamPose114
.4byte sMedichamPose115
.4byte sMedichamPose116
.4byte sMedichamPose117
.4byte sMedichamPose118
.4byte sMedichamPose119
.4byte sMedichamPose120
.4byte sMedichamPose121
.4byte sMedichamPose122
.4byte sMedichamPose123
.4byte sMedichamPose124
.4byte sMedichamPose125
.4byte sMedichamPose126
.4byte sMedichamPose127
.4byte sMedichamPose128
.4byte sMedichamPose129
.4byte sMedichamPose130
.4byte sMedichamPose131
.4byte sMedichamPose132
.4byte sMedichamPose133
.4byte sMedichamPose134
.4byte sMedichamPose135
.4byte sMedichamPose136
.4byte sMedichamPose137
.4byte sMedichamPose138
.4byte sMedichamPose139
.4byte sMedichamPose140
.4byte sMedichamPose141
.4byte sMedichamPose142
.4byte sMedichamPose143
.4byte sMedichamPose144
.4byte sMedichamPose145
.4byte sMedichamPose146
.4byte sMedichamPose147
.4byte sMedichamPose148
.4byte sMedichamPose149
.4byte sMedichamPose150
.4byte sMedichamPose151
.4byte sMedichamPose152
.4byte sMedichamPose153
.4byte sMedichamPose154
.4byte sMedichamPose155
.4byte sMedichamPose156
.4byte sMedichamPose157
.4byte sMedichamPose158
.4byte sMedichamPose159
.4byte sMedichamPose160
.4byte sMedichamPose161
.4byte sMedichamPose162
.4byte sMedichamPose163
.4byte sMedichamPose164
.4byte sMedichamPose165
.4byte sMedichamPose166
.4byte sMedichamPose167
.4byte sMedichamPose168
.4byte sMedichamPose169
.4byte sMedichamPose170
.4byte sMedichamPose171
.4byte sMedichamPose172
.4byte sMedichamPose173
.4byte sMedichamPose174
.4byte sMedichamPose175
.4byte sMedichamPose176
.4byte sMedichamPose177
.4byte sMedichamPose178
.4byte sMedichamPose179
.4byte sMedichamPose180
.4byte sMedichamPose181
.4byte sMedichamPose182
.4byte sMedichamPose183
.4byte sMedichamPose184
.4byte sMedichamPose185
.4byte sMedichamPose186
.4byte sMedichamPose187
.4byte sMedichamPose188
.4byte sMedichamPose189
.4byte sMedichamPose190
.4byte sMedichamPose191
.4byte sMedichamPose192
.4byte sMedichamPose193
.4byte sMedichamPose194
.4byte sMedichamPose195
.4byte sMedichamPose196
.4byte sMedichamPose197
.4byte sMedichamPose198
.4byte sMedichamPose199
.4byte sMedichamPose200
.4byte sMedichamPose201
.4byte sMedichamPose202
.4byte sMedichamPose203
.4byte sMedichamPose204
.4byte sMedichamPose205
.4byte sMedichamPose206
.4byte sMedichamPose207
.4byte sMedichamPose208
.4byte sMedichamPose209
.4byte sMedichamPose210
.4byte sMedichamPose211
.4byte sMedichamPose212
.4byte sMedichamPose213
.4byte sMedichamPose214
.4byte sMedichamPose215
.4byte sMedichamPose216
.4byte sMedichamPose217
.4byte sMedichamPose218
.4byte sMedichamPose219
.4byte sMedichamPose220
.4byte sMedichamPose221
.4byte sMedichamPose222
.4byte sMedichamPose223
.4byte sMedichamPose224
.4byte sMedichamPose225
.4byte sMedichamPose226
.4byte sMedichamPose227
.4byte sMedichamPose228
.4byte sMedichamPose229
.4byte sMedichamPose230
.4byte sMedichamPose231
.4byte sMedichamPose232
.4byte sMedichamPose233
.4byte sMedichamPose234
sAxPositionsMedicham:
.2byte    0,  -11, 	  -9,   -9, 	   9,   -9, 	   0,   -9
.2byte    0,  -13, 	  -6,  -11, 	   9,  -16, 	   0,  -11
.2byte    0,  -13, 	  -9,  -16, 	   6,  -11, 	   0,  -11
.2byte    3,  -11, 	   7,  -11, 	  -5,   -8, 	   1,  -10
.2byte    3,  -13, 	   5,  -12, 	  -6,  -15, 	   1,  -12
.2byte    3,  -13, 	   8,  -16, 	  -3,  -10, 	   1,  -12
.2byte    4,  -12, 	   3,  -10, 	   2,   -7, 	   1,  -10
.2byte    4,  -14, 	   3,   -9, 	   3,  -12, 	   1,  -12
.2byte    4,  -14, 	   6,  -15, 	   4,   -8, 	   0,  -12
.2byte    3,  -12, 	  -1,  -11, 	   7,   -8, 	   0,  -11
.2byte    4,  -15, 	  -1,  -11, 	   9,  -14, 	   0,  -13
.2byte    3,  -14, 	  -1,  -16, 	   6,  -10, 	   0,  -13
.2byte    0,  -12, 	   8,  -10, 	  -8,  -10, 	   0,  -11
.2byte    0,  -14, 	   6,  -12, 	  -8,  -14, 	   0,  -13
.2byte    0,  -14, 	   8,  -14, 	  -6,  -12, 	   0,  -13
.2byte   -3,  -12, 	   1,  -11, 	  -7,   -8, 	   0,  -11
.2byte   -4,  -15, 	   1,  -11, 	  -9,  -14, 	   0,  -13
.2byte   -3,  -14, 	   1,  -16, 	  -6,  -10, 	   0,  -13
.2byte   -4,  -12, 	  -3,  -10, 	  -2,   -7, 	  -1,  -10
.2byte   -4,  -14, 	  -3,   -9, 	  -3,  -12, 	  -1,  -12
.2byte   -4,  -14, 	  -6,  -15, 	  -4,   -8, 	   0,  -12
.2byte   -3,  -11, 	  -7,  -11, 	   5,   -8, 	  -1,  -10
.2byte   -3,  -13, 	  -5,  -12, 	   6,  -15, 	  -1,  -12
.2byte   -3,  -13, 	  -8,  -16, 	   3,  -10, 	  -1,  -12
.2byte    0,  -11, 	  -9,   -9, 	   9,   -9, 	   0,   -9
.2byte    0,  -13, 	  -6,  -11, 	   9,  -16, 	   0,  -11
.2byte    0,  -13, 	  -9,  -16, 	   6,  -11, 	   0,  -11
.2byte    3,  -11, 	   7,  -11, 	  -5,   -8, 	   1,  -10
.2byte    3,  -13, 	   5,  -12, 	  -6,  -15, 	   1,  -12
.2byte    3,  -13, 	   8,  -16, 	  -3,  -10, 	   1,  -12
.2byte    4,  -12, 	   3,  -10, 	   2,   -7, 	   1,  -10
.2byte    4,  -14, 	   3,   -9, 	   3,  -12, 	   1,  -12
.2byte    4,  -14, 	   6,  -15, 	   4,   -8, 	   0,  -12
.2byte    3,  -12, 	  -1,  -11, 	   7,   -8, 	   0,  -11
.2byte    4,  -15, 	  -1,  -11, 	   9,  -14, 	   0,  -13
.2byte    3,  -14, 	  -1,  -16, 	   6,  -10, 	   0,  -13
.2byte    0,  -12, 	   8,  -10, 	  -8,  -10, 	   0,  -11
.2byte    0,  -14, 	   6,  -12, 	  -8,  -14, 	   0,  -13
.2byte    0,  -14, 	   8,  -14, 	  -6,  -12, 	   0,  -13
.2byte   -3,  -12, 	   1,  -11, 	  -7,   -8, 	   0,  -11
.2byte   -4,  -15, 	   1,  -11, 	  -9,  -14, 	   0,  -13
.2byte   -3,  -14, 	   1,  -16, 	  -6,  -10, 	   0,  -13
.2byte   -4,  -12, 	  -3,  -10, 	  -2,   -7, 	  -1,  -10
.2byte   -4,  -14, 	  -3,   -9, 	  -3,  -12, 	  -1,  -12
.2byte   -4,  -14, 	  -6,  -15, 	  -4,   -8, 	   0,  -12
.2byte   -3,  -11, 	  -7,  -11, 	   5,   -8, 	  -1,  -10
.2byte   -3,  -13, 	  -5,  -12, 	   6,  -15, 	  -1,  -12
.2byte   -3,  -13, 	  -8,  -16, 	   3,  -10, 	  -1,  -12
.2byte    0,  -11, 	  -9,   -9, 	   9,   -9, 	   0,   -9
.2byte    0,  -13, 	  -6,  -11, 	   9,  -16, 	   0,  -11
.2byte    0,  -13, 	  -9,  -16, 	   6,  -11, 	   0,  -11
.2byte    0,  -10, 	  -3,   -5, 	   6,  -10, 	   0,   -9
.2byte   -5,   -7, 	  -3,  -16, 	   0,    4, 	   0,   -8
.2byte   -5,   -7, 	  -3,  -16, 	   0,    4, 	   0,   -8
.2byte    3,  -11, 	   7,  -11, 	  -5,   -8, 	   1,  -10
.2byte    3,  -13, 	   5,  -12, 	  -6,  -15, 	   1,  -12
.2byte    3,  -13, 	   8,  -16, 	  -3,  -10, 	   1,  -12
.2byte    3,   -9, 	   9,   -9, 	  -3,   -9, 	   1,   -8
.2byte    6,   -6, 	  -2,  -11, 	  12,    3, 	   0,   -7
.2byte    6,   -6, 	  -2,  -11, 	  12,    3, 	   0,   -7
.2byte    4,  -12, 	   3,  -10, 	   2,   -7, 	   1,  -10
.2byte    4,  -14, 	   3,   -9, 	   3,  -12, 	   1,  -12
.2byte    4,  -14, 	   6,  -15, 	   4,   -8, 	   0,  -12
.2byte    3,  -11, 	   8,  -13, 	  -2,  -10, 	   0,  -10
.2byte    7,   -9, 	  -3,  -13, 	  14,   -8, 	   1,  -10
.2byte    7,   -9, 	  -3,  -13, 	  14,   -8, 	   1,  -10
.2byte    3,  -12, 	  -1,  -11, 	   7,   -8, 	   0,  -11
.2byte    4,  -15, 	  -1,  -11, 	   9,  -14, 	   0,  -13
.2byte    3,  -14, 	  -1,  -16, 	   6,  -10, 	   0,  -13
.2byte    3,  -11, 	   5,  -16, 	   4,  -10, 	  -1,  -12
.2byte   -2,  -11, 	  -8,  -10, 	   9,  -19, 	  -1,  -11
.2byte   -2,  -11, 	  -8,  -10, 	   9,  -19, 	  -1,  -11
.2byte    0,  -12, 	   8,  -10, 	  -8,  -10, 	   0,  -11
.2byte    0,  -14, 	   6,  -12, 	  -8,  -14, 	   0,  -13
.2byte    0,  -14, 	   8,  -14, 	  -6,  -12, 	   0,  -13
.2byte    0,  -11, 	   4,  -16, 	  -5,  -11, 	   0,  -10
.2byte    4,   -8, 	   6,   -5, 	  -2,  -23, 	   0,  -10
.2byte    4,   -8, 	   6,   -5, 	  -2,  -23, 	   0,  -10
.2byte   -3,  -12, 	   1,  -11, 	  -7,   -8, 	   0,  -11
.2byte   -4,  -15, 	   1,  -11, 	  -9,  -14, 	   0,  -13
.2byte   -3,  -14, 	   1,  -16, 	  -6,  -10, 	   0,  -13
.2byte   -3,  -11, 	  -5,  -16, 	  -4,  -10, 	   1,  -12
.2byte    2,  -11, 	   8,  -10, 	  -9,  -19, 	   1,  -11
.2byte    2,  -11, 	   8,  -10, 	  -9,  -19, 	   1,  -11
.2byte   -4,  -12, 	  -3,  -10, 	  -2,   -7, 	  -1,  -10
.2byte   -4,  -14, 	  -3,   -9, 	  -3,  -12, 	  -1,  -12
.2byte   -4,  -14, 	  -6,  -15, 	  -4,   -8, 	   0,  -12
.2byte   -3,  -11, 	  -8,  -13, 	   2,  -10, 	   0,  -10
.2byte   -7,   -9, 	   3,  -13, 	 -14,   -8, 	  -1,  -10
.2byte   -7,   -9, 	   3,  -13, 	 -14,   -8, 	  -1,  -10
.2byte   -3,  -11, 	  -7,  -11, 	   5,   -8, 	  -1,  -10
.2byte   -3,  -13, 	  -5,  -12, 	   6,  -15, 	  -1,  -12
.2byte   -3,  -13, 	  -8,  -16, 	   3,  -10, 	  -1,  -12
.2byte   -3,   -9, 	  -9,   -9, 	   3,   -9, 	  -1,   -8
.2byte   -6,   -6, 	   2,  -11, 	 -12,    3, 	   0,   -7
.2byte   -6,   -6, 	   2,  -11, 	 -12,    3, 	   0,   -7
.2byte    0,   -9, 	  -3,   -4, 	   6,   -9, 	   0,   -8
.2byte   -3,   -9, 	  -9,   -9, 	   3,   -9, 	  -1,   -8
.2byte   -3,  -11, 	  -8,  -13, 	   2,  -10, 	   0,  -10
.2byte   -3,  -11, 	  -5,  -16, 	  -4,  -10, 	   1,  -12
.2byte    0,  -12, 	   4,  -17, 	  -5,  -12, 	   0,  -11
.2byte    3,  -11, 	   5,  -16, 	   4,  -10, 	  -1,  -12
.2byte    3,  -11, 	   8,  -13, 	  -2,  -10, 	   0,  -10
.2byte    3,   -9, 	   9,   -9, 	  -3,   -9, 	   1,   -8
.2byte    0,  -11, 	  -9,   -9, 	   9,   -9, 	   0,   -9
.2byte    0,  -11, 	  -9,   -9, 	   9,   -9, 	   0,   -9
.2byte    0,  -11, 	  -9,   -9, 	   9,   -9, 	   0,   -9
.2byte    0,  -11, 	  -9,   -9, 	   9,   -9, 	   0,   -9
.2byte    0,  -11, 	  -9,   -9, 	   9,   -9, 	   0,   -9
.2byte    3,  -11, 	   7,  -11, 	  -5,   -8, 	   1,  -10
.2byte    3,  -11, 	   7,  -11, 	  -5,   -8, 	   1,  -10
.2byte    3,  -11, 	   7,  -11, 	  -5,   -8, 	   1,  -10
.2byte    3,  -11, 	   7,  -11, 	  -5,   -8, 	   1,  -10
.2byte    3,  -11, 	   7,  -11, 	  -5,   -8, 	   1,  -10
.2byte    4,  -12, 	   3,  -10, 	   2,   -7, 	   1,  -10
.2byte    4,  -12, 	   3,  -10, 	   2,   -7, 	   1,  -10
.2byte    4,  -12, 	   3,  -10, 	   2,   -7, 	   1,  -10
.2byte    4,  -12, 	   3,  -10, 	   2,   -7, 	   1,  -10
.2byte    4,  -12, 	   3,  -10, 	   2,   -7, 	   1,  -10
.2byte    3,  -12, 	  -1,  -11, 	   7,   -8, 	   0,  -11
.2byte    3,  -12, 	  -1,  -11, 	   7,   -8, 	   0,  -11
.2byte    3,  -12, 	  -1,  -11, 	   7,   -8, 	   0,  -11
.2byte    3,  -12, 	  -1,  -11, 	   7,   -8, 	   0,  -11
.2byte    3,  -12, 	  -1,  -11, 	   7,   -8, 	   0,  -11
.2byte    0,  -12, 	   8,  -10, 	  -8,  -10, 	   0,  -11
.2byte    0,  -12, 	   8,  -10, 	  -8,  -10, 	   0,  -11
.2byte    0,  -12, 	   8,  -10, 	  -8,  -10, 	   0,  -11
.2byte    0,  -12, 	   8,  -10, 	  -8,  -10, 	   0,  -11
.2byte    0,  -12, 	   8,  -10, 	  -8,  -10, 	   0,  -11
.2byte   -3,  -12, 	   1,  -11, 	  -7,   -8, 	   0,  -11
.2byte   -3,  -12, 	   1,  -11, 	  -7,   -8, 	   0,  -11
.2byte   -3,  -12, 	   1,  -11, 	  -7,   -8, 	   0,  -11
.2byte   -3,  -12, 	   1,  -11, 	  -7,   -8, 	   0,  -11
.2byte   -3,  -12, 	   1,  -11, 	  -7,   -8, 	   0,  -11
.2byte   -4,  -12, 	  -3,  -10, 	  -2,   -7, 	  -1,  -10
.2byte   -4,  -12, 	  -3,  -10, 	  -2,   -7, 	  -1,  -10
.2byte   -4,  -12, 	  -3,  -10, 	  -2,   -7, 	  -1,  -10
.2byte   -4,  -12, 	  -3,  -10, 	  -2,   -7, 	  -1,  -10
.2byte   -4,  -12, 	  -3,  -10, 	  -2,   -7, 	  -1,  -10
.2byte   -3,  -11, 	  -7,  -11, 	   5,   -8, 	  -1,  -10
.2byte   -3,  -11, 	  -7,  -11, 	   5,   -8, 	  -1,  -10
.2byte   -3,  -11, 	  -7,  -11, 	   5,   -8, 	  -1,  -10
.2byte   -3,  -11, 	  -7,  -11, 	   5,   -8, 	  -1,  -10
.2byte   -3,  -11, 	  -7,  -11, 	   5,   -8, 	  -1,  -10
.2byte   -3,   -6, 	  -7,   -2, 	   7,    0, 	   0,   -6
.2byte   -3,   -7, 	  -7,   -2, 	   7,    0, 	   0,   -6
.2byte    0,  -16, 	  -8,  -18, 	   8,  -18, 	   0,  -14
.2byte   -4,  -17, 	  -1,  -22, 	 -12,   -9, 	  -2,  -14
.2byte    1,  -15, 	  -2,  -20, 	  -9,  -12, 	  -1,  -11
.2byte    0,  -16, 	  -8,  -17, 	   6,  -13, 	   0,   -9
.2byte    0,  -13, 	   9,  -12, 	  -9,  -12, 	   0,   -8
.2byte   -1,  -16, 	   7,  -17, 	  -7,  -13, 	  -1,   -9
.2byte   -2,  -15, 	   1,  -20, 	   8,  -12, 	   0,  -11
.2byte    3,  -17, 	   0,  -22, 	  11,   -9, 	   1,  -14
.2byte    0,  -11, 	  -9,   -9, 	   9,   -9, 	   0,   -9
.2byte    0,  -13, 	  -6,  -11, 	   9,  -16, 	   0,  -11
.2byte    0,  -13, 	  -9,  -16, 	   6,  -11, 	   0,  -11
.2byte    3,  -11, 	   7,  -11, 	  -5,   -8, 	   1,  -10
.2byte    3,  -13, 	   5,  -12, 	  -6,  -15, 	   1,  -12
.2byte    3,  -13, 	   8,  -16, 	  -3,  -10, 	   1,  -12
.2byte    4,  -12, 	   3,  -10, 	   2,   -7, 	   1,  -10
.2byte    4,  -14, 	   3,   -9, 	   3,  -12, 	   1,  -12
.2byte    4,  -14, 	   6,  -15, 	   4,   -8, 	   0,  -12
.2byte    3,  -12, 	  -1,  -11, 	   7,   -8, 	   0,  -11
.2byte    4,  -15, 	  -1,  -11, 	   9,  -14, 	   0,  -13
.2byte    3,  -14, 	  -1,  -16, 	   6,  -10, 	   0,  -13
.2byte    0,  -12, 	   8,  -10, 	  -8,  -10, 	   0,  -11
.2byte    0,  -14, 	   6,  -12, 	  -8,  -14, 	   0,  -13
.2byte    0,  -14, 	   8,  -14, 	  -6,  -12, 	   0,  -13
.2byte   -3,  -12, 	   1,  -11, 	  -7,   -8, 	   0,  -11
.2byte   -4,  -15, 	   1,  -11, 	  -9,  -14, 	   0,  -13
.2byte   -3,  -14, 	   1,  -16, 	  -6,  -10, 	   0,  -13
.2byte   -4,  -12, 	  -3,  -10, 	  -2,   -7, 	  -1,  -10
.2byte   -4,  -14, 	  -3,   -9, 	  -3,  -12, 	  -1,  -12
.2byte   -4,  -14, 	  -6,  -15, 	  -4,   -8, 	   0,  -12
.2byte   -3,  -11, 	  -7,  -11, 	   5,   -8, 	  -1,  -10
.2byte   -3,  -13, 	  -5,  -12, 	   6,  -15, 	  -1,  -12
.2byte   -3,  -13, 	  -8,  -16, 	   3,  -10, 	  -1,  -12
.2byte    0,  -11, 	  -9,   -9, 	   9,   -9, 	   0,   -9
.2byte   -3,  -11, 	  -7,  -11, 	   5,   -8, 	  -1,  -10
.2byte   -4,  -12, 	  -3,  -10, 	  -2,   -7, 	  -1,  -10
.2byte   -3,  -12, 	   1,  -11, 	  -7,   -8, 	   0,  -11
.2byte    0,  -12, 	   8,  -10, 	  -8,  -10, 	   0,  -11
.2byte    3,  -12, 	  -1,  -11, 	   7,   -8, 	   0,  -11
.2byte    4,  -12, 	   3,  -10, 	   2,   -7, 	   1,  -10
.2byte    3,  -11, 	   7,  -11, 	  -5,   -8, 	   1,  -10
.2byte    0,  -13, 	  -6,  -11, 	   9,  -16, 	   0,  -11
.2byte    3,  -13, 	   5,  -12, 	  -6,  -15, 	   1,  -12
.2byte    4,  -14, 	   3,   -9, 	   3,  -12, 	   1,  -12
.2byte    4,  -15, 	  -1,  -11, 	   9,  -14, 	   0,  -13
.2byte    0,  -14, 	   6,  -12, 	  -8,  -14, 	   0,  -13
.2byte   -4,  -15, 	   1,  -11, 	  -9,  -14, 	   0,  -13
.2byte   -4,  -14, 	  -3,   -9, 	  -3,  -12, 	  -1,  -12
.2byte   -3,  -13, 	  -5,  -12, 	   6,  -15, 	  -1,  -12
.2byte    0,  -11, 	  -9,   -9, 	   9,   -9, 	   0,   -9
.2byte    0,  -13, 	  -9,  -16, 	   6,  -11, 	   0,  -11
.2byte    0,  -10, 	  -3,   -5, 	   6,  -10, 	   0,   -9
.2byte    3,  -11, 	   7,  -11, 	  -5,   -8, 	   1,  -10
.2byte    3,  -13, 	   8,  -16, 	  -3,  -10, 	   1,  -12
.2byte    3,   -9, 	   9,   -9, 	  -3,   -9, 	   1,   -8
.2byte    4,  -12, 	   3,  -10, 	   2,   -7, 	   1,  -10
.2byte    4,  -14, 	   6,  -15, 	   4,   -8, 	   0,  -12
.2byte    3,  -11, 	   8,  -13, 	  -2,  -10, 	   0,  -10
.2byte    3,  -12, 	  -1,  -11, 	   7,   -8, 	   0,  -11
.2byte    3,  -14, 	  -1,  -16, 	   6,  -10, 	   0,  -13
.2byte    4,  -11, 	   6,  -16, 	   5,  -10, 	   0,  -12
.2byte    0,  -12, 	   8,  -10, 	  -8,  -10, 	   0,  -11
.2byte    0,  -14, 	   8,  -14, 	  -6,  -12, 	   0,  -13
.2byte    0,  -11, 	   4,  -16, 	  -5,  -11, 	   0,  -10
.2byte   -3,  -12, 	   1,  -11, 	  -7,   -8, 	   0,  -11
.2byte   -3,  -14, 	   1,  -16, 	  -6,  -10, 	   0,  -13
.2byte   -4,  -11, 	  -6,  -16, 	  -5,  -10, 	   0,  -12
.2byte   -4,  -12, 	  -3,  -10, 	  -2,   -7, 	  -1,  -10
.2byte   -4,  -14, 	  -6,  -15, 	  -4,   -8, 	   0,  -12
.2byte   -3,  -11, 	  -8,  -13, 	   2,  -10, 	   0,  -10
.2byte   -3,  -11, 	  -7,  -11, 	   5,   -8, 	  -1,  -10
.2byte   -3,  -13, 	  -8,  -16, 	   3,  -10, 	  -1,  -12
.2byte   -3,   -9, 	  -9,   -9, 	   3,   -9, 	  -1,   -8
.2byte    0,   -9, 	  -3,   -4, 	   6,   -9, 	   0,   -8
.2byte   -3,   -9, 	  -9,   -9, 	   3,   -9, 	  -1,   -8
.2byte   -3,  -11, 	  -8,  -13, 	   2,  -10, 	   0,  -10
.2byte   -3,  -11, 	  -5,  -16, 	  -4,  -10, 	   1,  -12
.2byte    0,  -12, 	   4,  -17, 	  -5,  -12, 	   0,  -11
.2byte    3,  -11, 	   5,  -16, 	   4,  -10, 	  -1,  -12
.2byte    3,  -11, 	   8,  -13, 	  -2,  -10, 	   0,  -10
.2byte    3,   -9, 	   9,   -9, 	  -3,   -9, 	   1,   -8
.2byte    0,  -11, 	  -9,   -9, 	   9,   -9, 	   0,   -9
.2byte   -3,  -11, 	  -7,  -11, 	   5,   -8, 	  -1,  -10
.2byte   -4,  -12, 	  -3,  -10, 	  -2,   -7, 	  -1,  -10
.2byte   -3,  -12, 	   1,  -11, 	  -7,   -8, 	   0,  -11
.2byte    0,  -12, 	   8,  -10, 	  -8,  -10, 	   0,  -11
.2byte    3,  -12, 	  -1,  -11, 	   7,   -8, 	   0,  -11
.2byte    4,  -12, 	   3,  -10, 	   2,   -7, 	   1,  -10
.2byte    3,  -11, 	   7,  -11, 	  -5,   -8, 	   1,  -10
sMedichamAnimTable1:
.4byte sMedichamAnims_1_1
.4byte sMedichamAnims_1_2
.4byte sMedichamAnims_1_3
.4byte sMedichamAnims_1_4
.4byte sMedichamAnims_1_5
.4byte sMedichamAnims_1_6
.4byte sMedichamAnims_1_7
.4byte sMedichamAnims_1_8
sMedichamAnimTable2:
.4byte sMedichamAnims_2_1
.4byte sMedichamAnims_2_2
.4byte sMedichamAnims_2_3
.4byte sMedichamAnims_2_4
.4byte sMedichamAnims_2_5
.4byte sMedichamAnims_2_6
.4byte sMedichamAnims_2_7
.4byte sMedichamAnims_2_8
sMedichamAnimTable3:
.4byte sMedichamAnims_3_1
.4byte sMedichamAnims_3_2
.4byte sMedichamAnims_3_3
.4byte sMedichamAnims_3_4
.4byte sMedichamAnims_3_5
.4byte sMedichamAnims_3_6
.4byte sMedichamAnims_3_7
.4byte sMedichamAnims_3_8
sMedichamAnimTable4:
.4byte sMedichamAnims_4_1
.4byte sMedichamAnims_4_2
.4byte sMedichamAnims_4_3
.4byte sMedichamAnims_4_4
.4byte sMedichamAnims_4_5
.4byte sMedichamAnims_4_6
.4byte sMedichamAnims_4_7
.4byte sMedichamAnims_4_8
sMedichamAnimTable5:
.4byte sMedichamAnims_5_1
.4byte sMedichamAnims_5_2
.4byte sMedichamAnims_5_3
.4byte sMedichamAnims_5_4
.4byte sMedichamAnims_5_5
.4byte sMedichamAnims_5_6
.4byte sMedichamAnims_5_7
.4byte sMedichamAnims_5_8
sMedichamAnimTable6:
.4byte sMedichamAnims_6_1
.4byte sMedichamAnims_6_1
.4byte sMedichamAnims_6_1
.4byte sMedichamAnims_6_1
.4byte sMedichamAnims_6_1
.4byte sMedichamAnims_6_1
.4byte sMedichamAnims_6_1
.4byte sMedichamAnims_6_1
sMedichamAnimTable7:
.4byte sMedichamAnims_7_1
.4byte sMedichamAnims_7_2
.4byte sMedichamAnims_7_3
.4byte sMedichamAnims_7_4
.4byte sMedichamAnims_7_5
.4byte sMedichamAnims_7_6
.4byte sMedichamAnims_7_7
.4byte sMedichamAnims_7_8
sMedichamAnimTable8:
.4byte sMedichamAnims_8_1
.4byte sMedichamAnims_8_2
.4byte sMedichamAnims_8_3
.4byte sMedichamAnims_8_4
.4byte sMedichamAnims_8_5
.4byte sMedichamAnims_8_6
.4byte sMedichamAnims_8_7
.4byte sMedichamAnims_8_8
sMedichamAnimTable9:
.4byte sMedichamAnims_9_1
.4byte sMedichamAnims_9_2
.4byte sMedichamAnims_9_3
.4byte sMedichamAnims_9_4
.4byte sMedichamAnims_9_5
.4byte sMedichamAnims_9_6
.4byte sMedichamAnims_9_7
.4byte sMedichamAnims_9_8
sMedichamAnimTable10:
.4byte sMedichamAnims_10_1
.4byte sMedichamAnims_10_2
.4byte sMedichamAnims_10_3
.4byte sMedichamAnims_10_4
.4byte sMedichamAnims_10_5
.4byte sMedichamAnims_10_6
.4byte sMedichamAnims_10_7
.4byte sMedichamAnims_10_8
sMedichamAnimTable11:
.4byte sMedichamAnims_11_1
.4byte sMedichamAnims_11_2
.4byte sMedichamAnims_11_3
.4byte sMedichamAnims_11_4
.4byte sMedichamAnims_11_5
.4byte sMedichamAnims_11_6
.4byte sMedichamAnims_11_7
.4byte sMedichamAnims_11_8
sMedichamAnimTable12:
.4byte sMedichamAnims_12_1
.4byte sMedichamAnims_12_2
.4byte sMedichamAnims_12_3
.4byte sMedichamAnims_12_4
.4byte sMedichamAnims_12_5
.4byte sMedichamAnims_12_6
.4byte sMedichamAnims_12_7
.4byte sMedichamAnims_12_8
sMedichamAnimTable13:
.4byte sMedichamAnims_13_1
.4byte sMedichamAnims_13_2
.4byte sMedichamAnims_13_3
.4byte sMedichamAnims_13_4
.4byte sMedichamAnims_13_5
.4byte sMedichamAnims_13_6
.4byte sMedichamAnims_13_7
.4byte sMedichamAnims_13_8
sAxAnimationsMedicham:
.4byte sMedichamAnimTable1
.4byte sMedichamAnimTable2
.4byte sMedichamAnimTable3
.4byte sMedichamAnimTable4
.4byte sMedichamAnimTable5
.4byte sMedichamAnimTable6
.4byte sMedichamAnimTable7
.4byte sMedichamAnimTable8
.4byte sMedichamAnimTable9
.4byte sMedichamAnimTable10
.4byte sMedichamAnimTable11
.4byte sMedichamAnimTable12
.4byte sMedichamAnimTable13
sAxSpritesMedicham:
.4byte sMedichamSprites1
.4byte sMedichamSprites2
.4byte sMedichamSprites3
.4byte sMedichamSprites4
.4byte sMedichamSprites5
.4byte sMedichamSprites6
.4byte sMedichamSprites7
.4byte sMedichamSprites8
.4byte sMedichamSprites9
.4byte sMedichamSprites10
.4byte sMedichamSprites11
.4byte sMedichamSprites12
.4byte sMedichamSprites13
.4byte sMedichamSprites14
.4byte sMedichamSprites15
.4byte sMedichamSprites16
.4byte sMedichamSprites17
.4byte sMedichamSprites18
.4byte sMedichamSprites19
.4byte sMedichamSprites20
.4byte sMedichamSprites21
.4byte sMedichamSprites22
.4byte sMedichamSprites23
.4byte sMedichamSprites24
.4byte sMedichamSprites25
.4byte sMedichamSprites26
.4byte sMedichamSprites27
.4byte sMedichamSprites28
.4byte sMedichamSprites29
.4byte sMedichamSprites30
.4byte sMedichamSprites31
.4byte sMedichamSprites32
.4byte sMedichamSprites33
.4byte sMedichamSprites34
.4byte sMedichamSprites35
.4byte sMedichamSprites36
.4byte sMedichamSprites37
.4byte sMedichamSprites38
.4byte sMedichamSprites39
.4byte sMedichamSprites40
.4byte sMedichamSprites41
.4byte sMedichamSprites42
.4byte sMedichamSprites43
sAxMainMedicham:
ax_main sAxPosesMedicham, sAxAnimationsMedicham, 13, sAxSpritesMedicham, sAxPositionsMedicham
