.global gAxMetang
gAxMetang:
ax_siro sAxMainMetang
sMetangPose1:
ax_pose 0, 0x01e4, 0x80f0, 0xbc00
ax_pose_terminator
sMetangPose2:
ax_pose 1, 0x01e4, 0x80f0, 0xbc00
ax_pose_terminator
sMetangPose3:
ax_pose 2, 0x01e4, 0x80f0, 0xbc00
ax_pose_terminator
sMetangPose4:
ax_pose 3, 0x01e4, 0x90f3, 0xbc00
ax_pose_terminator
sMetangPose5:
ax_pose 4, 0x01e4, 0x90f3, 0xbc00
ax_pose_terminator
sMetangPose6:
ax_pose 5, 0x01e6, 0x90f3, 0xbc00
ax_pose_terminator
sMetangPose7:
ax_pose 6, 0x01e4, 0x90ef, 0xbc00
ax_pose_terminator
sMetangPose8:
ax_pose 7, 0x01e4, 0x90ef, 0xbc00
ax_pose_terminator
sMetangPose9:
ax_pose 8, 0x01e4, 0x90ef, 0xbc00
ax_pose_terminator
sMetangPose10:
ax_pose 9, 0x01e7, 0x90f3, 0xbc00
ax_pose_terminator
sMetangPose11:
ax_pose 10, 0x01e6, 0x90f3, 0xbc00
ax_pose_terminator
sMetangPose12:
ax_pose 11, 0x01e6, 0x90f3, 0xbc00
ax_pose_terminator
sMetangPose13:
ax_pose 12, 0x01e4, 0x80f0, 0xbc00
ax_pose_terminator
sMetangPose14:
ax_pose 13, 0x01e4, 0x80f0, 0xbc00
ax_pose_terminator
sMetangPose15:
ax_pose 14, 0x01e4, 0x80f0, 0xbc00
ax_pose_terminator
sMetangPose16:
ax_pose 9, 0x01e7, 0x80ec, 0xbc00
ax_pose_terminator
sMetangPose17:
ax_pose 10, 0x01e6, 0x80ec, 0xbc00
ax_pose_terminator
sMetangPose18:
ax_pose 11, 0x01e6, 0x80ec, 0xbc00
ax_pose_terminator
sMetangPose19:
ax_pose 6, 0x01e4, 0x80f0, 0xbc00
ax_pose_terminator
sMetangPose20:
ax_pose 7, 0x01e4, 0x80f0, 0xbc00
ax_pose_terminator
sMetangPose21:
ax_pose 8, 0x01e4, 0x80f0, 0xbc00
ax_pose_terminator
sMetangPose22:
ax_pose 3, 0x01e4, 0x80ec, 0xbc00
ax_pose_terminator
sMetangPose23:
ax_pose 4, 0x01e4, 0x80ec, 0xbc00
ax_pose_terminator
sMetangPose24:
ax_pose 5, 0x01e6, 0x80ec, 0xbc00
ax_pose_terminator
sMetangPose25:
ax_pose 0, 0x01e4, 0x80f0, 0xbc00
ax_pose_terminator
sMetangPose26:
ax_pose 1, 0x01e4, 0x80f0, 0xbc00
ax_pose_terminator
sMetangPose27:
ax_pose 15, 0x01e4, 0x80f0, 0xbc00
ax_pose_terminator
sMetangPose28:
ax_pose 3, 0x01e4, 0x90f3, 0xbc00
ax_pose_terminator
sMetangPose29:
ax_pose 4, 0x01e4, 0x90f3, 0xbc00
ax_pose_terminator
sMetangPose30:
ax_pose 16, 0x01e4, 0x90ee, 0xbc00
ax_pose_terminator
sMetangPose31:
ax_pose 6, 0x01e4, 0x90ef, 0xbc00
ax_pose_terminator
sMetangPose32:
ax_pose 7, 0x01e4, 0x90ef, 0xbc00
ax_pose_terminator
sMetangPose33:
ax_pose 17, 0x01e4, 0x90ef, 0xbc00
ax_pose_terminator
sMetangPose34:
ax_pose 9, 0x01e7, 0x90f3, 0xbc00
ax_pose_terminator
sMetangPose35:
ax_pose 10, 0x01e6, 0x90f3, 0xbc00
ax_pose_terminator
sMetangPose36:
ax_pose 18, 0x01e7, 0x90ee, 0xbc00
ax_pose_terminator
sMetangPose37:
ax_pose 12, 0x01e4, 0x80f0, 0xbc00
ax_pose_terminator
sMetangPose38:
ax_pose 13, 0x01e4, 0x80f0, 0xbc00
ax_pose_terminator
sMetangPose39:
ax_pose 19, 0x01e4, 0x80f0, 0xbc00
ax_pose_terminator
sMetangPose40:
ax_pose 9, 0x01e7, 0x80ec, 0xbc00
ax_pose_terminator
sMetangPose41:
ax_pose 10, 0x01e6, 0x80ec, 0xbc00
ax_pose_terminator
sMetangPose42:
ax_pose 18, 0x01e7, 0x80f1, 0xbc00
ax_pose_terminator
sMetangPose43:
ax_pose 6, 0x01e4, 0x80f0, 0xbc00
ax_pose_terminator
sMetangPose44:
ax_pose 7, 0x01e4, 0x80f0, 0xbc00
ax_pose_terminator
sMetangPose45:
ax_pose 17, 0x01e4, 0x80f0, 0xbc00
ax_pose_terminator
sMetangPose46:
ax_pose 3, 0x01e4, 0x80ec, 0xbc00
ax_pose_terminator
sMetangPose47:
ax_pose 4, 0x01e4, 0x80ec, 0xbc00
ax_pose_terminator
sMetangPose48:
ax_pose 16, 0x01e4, 0x80f1, 0xbc00
ax_pose_terminator
sMetangPose49:
ax_pose 0, 0x01e4, 0x80f0, 0xbc00
ax_pose_terminator
sMetangPose50:
ax_pose 20, 0x01e4, 0x80f0, 0xbc00
ax_pose 21, 0x01e4, 0x80f0, 0xbc10
ax_pose_terminator
sMetangPose51:
ax_pose 21, 0x01e4, 0x80f0, 0xbc00
ax_pose_terminator
sMetangPose52:
ax_pose 20, 0x01e4, 0x90f0, 0xbc00
ax_pose 22, 0x01e4, 0x80f0, 0xbc10
ax_pose_terminator
sMetangPose53:
ax_pose 22, 0x01e4, 0x80f0, 0xbc00
ax_pose_terminator
sMetangPose54:
ax_pose 3, 0x01e4, 0x90f3, 0xbc00
ax_pose_terminator
sMetangPose55:
ax_pose 23, 0x81e5, 0x9103, 0xbc00
ax_pose 24, 0x01e5, 0x90ef, 0xbc08
ax_pose_terminator
sMetangPose56:
ax_pose 24, 0x01e5, 0x90ef, 0xbc00
ax_pose_terminator
sMetangPose57:
ax_pose 25, 0x41f4, 0x90f4, 0xbc00
ax_pose 26, 0x01e4, 0x90f4, 0xbc08
ax_pose_terminator
sMetangPose58:
ax_pose 26, 0x01e4, 0x90f4, 0xbc00
ax_pose_terminator
sMetangPose59:
ax_pose 6, 0x01e4, 0x90ef, 0xbc00
ax_pose_terminator
sMetangPose60:
ax_pose 27, 0x01e3, 0x90f5, 0xbc00
ax_pose 28, 0x41e6, 0x90f1, 0xbc10
ax_pose 29, 0x41f6, 0x50f1, 0xbc18
ax_pose 30, 0x01f6, 0x1111, 0xbc1c
ax_pose 31, 0x01ee, 0x1111, 0xbc1d
ax_pose_terminator
sMetangPose61:
ax_pose 28, 0x41e6, 0x90f1, 0xbc00
ax_pose 29, 0x41f6, 0x50f1, 0xbc08
ax_pose 30, 0x01f6, 0x1111, 0xbc0c
ax_pose 31, 0x01ee, 0x1111, 0xbc0d
ax_pose_terminator
sMetangPose62:
ax_pose 32, 0x01e4, 0x90f6, 0xbc00
ax_pose 33, 0x41e4, 0x90f2, 0xbc10
ax_pose 34, 0x41f4, 0x50f2, 0xbc18
ax_pose 35, 0x01ec, 0x1112, 0xbc1c
ax_pose 36, 0x01e4, 0x1112, 0xbc1d
ax_pose_terminator
sMetangPose63:
ax_pose 33, 0x41e4, 0x90f2, 0xbc00
ax_pose 34, 0x41f4, 0x50f2, 0xbc08
ax_pose 35, 0x01ec, 0x1112, 0xbc0c
ax_pose 36, 0x01e4, 0x1112, 0xbc0d
ax_pose_terminator
sMetangPose64:
ax_pose 9, 0x01e7, 0x90f3, 0xbc00
ax_pose_terminator
sMetangPose65:
ax_pose 37, 0x41e5, 0x90f4, 0xbc00
ax_pose 38, 0x01e7, 0x90f3, 0xbc08
ax_pose_terminator
sMetangPose66:
ax_pose 38, 0x01e7, 0x90f3, 0xbc00
ax_pose_terminator
sMetangPose67:
ax_pose 39, 0x81e3, 0x9104, 0xbc00
ax_pose 40, 0x01e4, 0x90ed, 0xbc08
ax_pose_terminator
sMetangPose68:
ax_pose 40, 0x01e4, 0x90ed, 0xbc00
ax_pose_terminator
sMetangPose69:
ax_pose 12, 0x01e4, 0x90f0, 0xbc00
ax_pose_terminator
sMetangPose70:
ax_pose 41, 0x01e4, 0x80f0, 0xbc00
ax_pose 42, 0x01e4, 0x80f0, 0xbc10
ax_pose_terminator
sMetangPose71:
ax_pose 42, 0x01e4, 0x80f0, 0xbc00
ax_pose_terminator
sMetangPose72:
ax_pose 41, 0x01e4, 0x90f0, 0xbc00
ax_pose 43, 0x01e4, 0x80f0, 0xbc10
ax_pose_terminator
sMetangPose73:
ax_pose 43, 0x01e4, 0x80f0, 0xbc00
ax_pose_terminator
sMetangPose74:
ax_pose 9, 0x01e7, 0x80ec, 0xbc00
ax_pose_terminator
sMetangPose75:
ax_pose 37, 0x41e5, 0x80e9, 0xbc00
ax_pose 38, 0x01e7, 0x80eb, 0xbc08
ax_pose_terminator
sMetangPose76:
ax_pose 38, 0x01e7, 0x80eb, 0xbc00
ax_pose_terminator
sMetangPose77:
ax_pose 39, 0x81e4, 0x80ea, 0xbc00
ax_pose 40, 0x01e4, 0x80f1, 0xbc08
ax_pose_terminator
sMetangPose78:
ax_pose 40, 0x01e4, 0x80f1, 0xbc00
ax_pose_terminator
sMetangPose79:
ax_pose 6, 0x01e4, 0x80f0, 0xbc00
ax_pose_terminator
sMetangPose80:
ax_pose 27, 0x01e3, 0x80eb, 0xbc00
ax_pose 28, 0x41e6, 0x80ef, 0xbc10
ax_pose 29, 0x41f6, 0x40ef, 0xbc18
ax_pose 30, 0x01f6, 0x00e7, 0xbc1c
ax_pose 31, 0x01ee, 0x00e7, 0xbc1d
ax_pose_terminator
sMetangPose81:
ax_pose 28, 0x41e6, 0x80ef, 0xbc00
ax_pose 29, 0x41f6, 0x40ef, 0xbc08
ax_pose 30, 0x01f6, 0x00e7, 0xbc0c
ax_pose 31, 0x01ee, 0x00e7, 0xbc0d
ax_pose_terminator
sMetangPose82:
ax_pose 32, 0x01e4, 0x80ea, 0xbc00
ax_pose 33, 0x41e4, 0x80ee, 0xbc10
ax_pose 34, 0x41f4, 0x40ee, 0xbc18
ax_pose 35, 0x01ec, 0x00e6, 0xbc1c
ax_pose 36, 0x01e4, 0x00e6, 0xbc1d
ax_pose_terminator
sMetangPose83:
ax_pose 33, 0x41e4, 0x80ee, 0xbc00
ax_pose 34, 0x41f4, 0x40ee, 0xbc08
ax_pose 35, 0x01ec, 0x00e6, 0xbc0c
ax_pose 36, 0x01e4, 0x00e6, 0xbc0d
ax_pose_terminator
sMetangPose84:
ax_pose 3, 0x01e4, 0x80ec, 0xbc00
ax_pose_terminator
sMetangPose85:
ax_pose 23, 0x81e5, 0x80ec, 0xbc00
ax_pose 24, 0x01e5, 0x80f0, 0xbc08
ax_pose_terminator
sMetangPose86:
ax_pose 24, 0x01e5, 0x80f0, 0xbc00
ax_pose_terminator
sMetangPose87:
ax_pose 25, 0x41f4, 0x80ee, 0xbc00
ax_pose 26, 0x01e4, 0x80ee, 0xbc08
ax_pose_terminator
sMetangPose88:
ax_pose 26, 0x01e4, 0x80ee, 0xbc00
ax_pose_terminator
sMetangPose89:
ax_pose 0, 0x01e4, 0x80f0, 0xbc00
ax_pose_terminator
sMetangPose90:
ax_pose 44, 0x01e4, 0x80f0, 0xbc00
ax_pose_terminator
sMetangPose91:
ax_pose 15, 0x01e4, 0x80f0, 0xbc00
ax_pose_terminator
sMetangPose92:
ax_pose 1, 0x01e4, 0x80f0, 0xbc00
ax_pose_terminator
sMetangPose93:
ax_pose 3, 0x01e4, 0x90f3, 0xbc00
ax_pose_terminator
sMetangPose94:
ax_pose 45, 0x01e4, 0x90f1, 0xbc00
ax_pose_terminator
sMetangPose95:
ax_pose 16, 0x01e4, 0x90ee, 0xbc00
ax_pose_terminator
sMetangPose96:
ax_pose 4, 0x01e4, 0x90f3, 0xbc00
ax_pose_terminator
sMetangPose97:
ax_pose 6, 0x01e4, 0x90ef, 0xbc00
ax_pose_terminator
sMetangPose98:
ax_pose 46, 0x01e4, 0x90ef, 0xbc00
ax_pose_terminator
sMetangPose99:
ax_pose 17, 0x01e4, 0x90f1, 0xbc00
ax_pose_terminator
sMetangPose100:
ax_pose 7, 0x01e4, 0x90ef, 0xbc00
ax_pose_terminator
sMetangPose101:
ax_pose 9, 0x01e7, 0x90f3, 0xbc00
ax_pose_terminator
sMetangPose102:
ax_pose 47, 0x01e3, 0x90f2, 0xbc00
ax_pose_terminator
sMetangPose103:
ax_pose 18, 0x01e7, 0x90ee, 0xbc00
ax_pose_terminator
sMetangPose104:
ax_pose 10, 0x01e7, 0x90f3, 0xbc00
ax_pose_terminator
sMetangPose105:
ax_pose 12, 0x01e4, 0x80f0, 0xbc00
ax_pose_terminator
sMetangPose106:
ax_pose 48, 0x01e4, 0x80f0, 0xbc00
ax_pose_terminator
sMetangPose107:
ax_pose 19, 0x01e4, 0x80f0, 0xbc00
ax_pose_terminator
sMetangPose108:
ax_pose 13, 0x01e4, 0x80f0, 0xbc00
ax_pose_terminator
sMetangPose109:
ax_pose 9, 0x01e7, 0x80ec, 0xbc00
ax_pose_terminator
sMetangPose110:
ax_pose 47, 0x01e3, 0x80ec, 0xbc00
ax_pose_terminator
sMetangPose111:
ax_pose 18, 0x01e7, 0x80f1, 0xbc00
ax_pose_terminator
sMetangPose112:
ax_pose 10, 0x01e7, 0x80ec, 0xbc00
ax_pose_terminator
sMetangPose113:
ax_pose 6, 0x01e4, 0x80f0, 0xbc00
ax_pose_terminator
sMetangPose114:
ax_pose 46, 0x01e4, 0x80f0, 0xbc00
ax_pose_terminator
sMetangPose115:
ax_pose 17, 0x01e4, 0x80ee, 0xbc00
ax_pose_terminator
sMetangPose116:
ax_pose 7, 0x01e4, 0x80f0, 0xbc00
ax_pose_terminator
sMetangPose117:
ax_pose 3, 0x01e4, 0x80ec, 0xbc00
ax_pose_terminator
sMetangPose118:
ax_pose 45, 0x01e4, 0x80ec, 0xbc00
ax_pose_terminator
sMetangPose119:
ax_pose 16, 0x01e4, 0x80f1, 0xbc00
ax_pose_terminator
sMetangPose120:
ax_pose 4, 0x01e4, 0x80ec, 0xbc00
ax_pose_terminator
sMetangPose121:
ax_pose 0, 0x01e4, 0x80f0, 0xbc00
ax_pose_terminator
sMetangPose122:
ax_pose 3, 0x01e4, 0x80ec, 0xbc00
ax_pose_terminator
sMetangPose123:
ax_pose 6, 0x01e4, 0x80f0, 0xbc00
ax_pose_terminator
sMetangPose124:
ax_pose 9, 0x01e7, 0x80ec, 0xbc00
ax_pose_terminator
sMetangPose125:
ax_pose 12, 0x01e4, 0x80f0, 0xbc00
ax_pose_terminator
sMetangPose126:
ax_pose 9, 0x01e7, 0x90f3, 0xbc00
ax_pose_terminator
sMetangPose127:
ax_pose 6, 0x01e4, 0x90ef, 0xbc00
ax_pose_terminator
sMetangPose128:
ax_pose 3, 0x01e4, 0x90f3, 0xbc00
ax_pose_terminator
sMetangPose129:
ax_pose 49, 0x01e8, 0x80ef, 0xbc00
ax_pose_terminator
sMetangPose130:
ax_pose 50, 0x01e9, 0x80ef, 0xbc00
ax_pose_terminator
sMetangPose131:
ax_pose 51, 0x01db, 0x80f1, 0xbc00
ax_pose_terminator
sMetangPose132:
ax_pose 52, 0x01de, 0x90ef, 0xbc00
ax_pose_terminator
sMetangPose133:
ax_pose 53, 0x01de, 0x90ec, 0xbc00
ax_pose_terminator
sMetangPose134:
ax_pose 54, 0x81df, 0x90f2, 0xbc00
ax_pose 55, 0x81eb, 0x110a, 0xbc08
ax_pose 56, 0x01e3, 0x110a, 0xbc0a
ax_pose 57, 0x01e7, 0x1102, 0xbc0b
ax_pose 58, 0x01d7, 0x10fa, 0xbc0c
ax_pose 59, 0x01d7, 0x10f2, 0xbc0d
ax_pose 60, 0x81ef, 0x1102, 0xbc0e
ax_pose_terminator
sMetangPose135:
ax_pose 61, 0x01df, 0x80f1, 0xbc00
ax_pose_terminator
sMetangPose136:
ax_pose 54, 0x81df, 0x80ff, 0xbc00
ax_pose 55, 0x81eb, 0x00ef, 0xbc08
ax_pose 56, 0x01e3, 0x00ef, 0xbc0a
ax_pose 57, 0x01e7, 0x00f7, 0xbc0b
ax_pose 58, 0x01d7, 0x00ff, 0xbc0c
ax_pose 59, 0x01d7, 0x0107, 0xbc0d
ax_pose 60, 0x81ef, 0x00f7, 0xbc0e
ax_pose_terminator
sMetangPose137:
ax_pose 53, 0x01de, 0x80f4, 0xbc00
ax_pose_terminator
sMetangPose138:
ax_pose 52, 0x01dd, 0x80f2, 0xbc00
ax_pose_terminator
sMetangPose139:
ax_pose 0, 0x01e4, 0x80f0, 0xbc00
ax_pose_terminator
sMetangPose140:
ax_pose 1, 0x01e4, 0x80f0, 0xbc00
ax_pose_terminator
sMetangPose141:
ax_pose 2, 0x01e4, 0x80f0, 0xbc00
ax_pose_terminator
sMetangPose142:
ax_pose 3, 0x01e4, 0x90f3, 0xbc00
ax_pose_terminator
sMetangPose143:
ax_pose 4, 0x01e4, 0x90f3, 0xbc00
ax_pose_terminator
sMetangPose144:
ax_pose 5, 0x01e6, 0x90f3, 0xbc00
ax_pose_terminator
sMetangPose145:
ax_pose 6, 0x01e4, 0x90ef, 0xbc00
ax_pose_terminator
sMetangPose146:
ax_pose 7, 0x01e4, 0x90ef, 0xbc00
ax_pose_terminator
sMetangPose147:
ax_pose 8, 0x01e4, 0x90ef, 0xbc00
ax_pose_terminator
sMetangPose148:
ax_pose 9, 0x01e7, 0x90f3, 0xbc00
ax_pose_terminator
sMetangPose149:
ax_pose 10, 0x01e6, 0x90f3, 0xbc00
ax_pose_terminator
sMetangPose150:
ax_pose 11, 0x01e6, 0x90f3, 0xbc00
ax_pose_terminator
sMetangPose151:
ax_pose 12, 0x01e4, 0x80f0, 0xbc00
ax_pose_terminator
sMetangPose152:
ax_pose 13, 0x01e4, 0x80f0, 0xbc00
ax_pose_terminator
sMetangPose153:
ax_pose 14, 0x01e4, 0x80f0, 0xbc00
ax_pose_terminator
sMetangPose154:
ax_pose 9, 0x01e7, 0x80ec, 0xbc00
ax_pose_terminator
sMetangPose155:
ax_pose 10, 0x01e6, 0x80ec, 0xbc00
ax_pose_terminator
sMetangPose156:
ax_pose 11, 0x01e6, 0x80ec, 0xbc00
ax_pose_terminator
sMetangPose157:
ax_pose 6, 0x01e4, 0x80f0, 0xbc00
ax_pose_terminator
sMetangPose158:
ax_pose 7, 0x01e4, 0x80f0, 0xbc00
ax_pose_terminator
sMetangPose159:
ax_pose 8, 0x01e4, 0x80f0, 0xbc00
ax_pose_terminator
sMetangPose160:
ax_pose 3, 0x01e4, 0x80ec, 0xbc00
ax_pose_terminator
sMetangPose161:
ax_pose 4, 0x01e4, 0x80ec, 0xbc00
ax_pose_terminator
sMetangPose162:
ax_pose 5, 0x01e6, 0x80ec, 0xbc00
ax_pose_terminator
sMetangPose163:
ax_pose 15, 0x01e4, 0x80f0, 0xbc00
ax_pose_terminator
sMetangPose164:
ax_pose 16, 0x01e4, 0x80f1, 0xbc00
ax_pose_terminator
sMetangPose165:
ax_pose 17, 0x01e4, 0x80f0, 0xbc00
ax_pose_terminator
sMetangPose166:
ax_pose 18, 0x01e7, 0x80f1, 0xbc00
ax_pose_terminator
sMetangPose167:
ax_pose 19, 0x01e4, 0x80f0, 0xbc00
ax_pose_terminator
sMetangPose168:
ax_pose 18, 0x01e7, 0x90ee, 0xbc00
ax_pose_terminator
sMetangPose169:
ax_pose 17, 0x01e4, 0x90ef, 0xbc00
ax_pose_terminator
sMetangPose170:
ax_pose 16, 0x01e4, 0x90ee, 0xbc00
ax_pose_terminator
sMetangPose171:
ax_pose 44, 0x01e5, 0x80f0, 0xbc00
ax_pose_terminator
sMetangPose172:
ax_pose 45, 0x01e4, 0x90f3, 0xbc00
ax_pose_terminator
sMetangPose173:
ax_pose 46, 0x01e4, 0x90f0, 0xbc00
ax_pose_terminator
sMetangPose174:
ax_pose 47, 0x01e3, 0x90f3, 0xbc00
ax_pose_terminator
sMetangPose175:
ax_pose 48, 0x01e4, 0x80f0, 0xbc00
ax_pose_terminator
sMetangPose176:
ax_pose 47, 0x01e3, 0x80ed, 0xbc00
ax_pose_terminator
sMetangPose177:
ax_pose 46, 0x01e4, 0x80f0, 0xbc00
ax_pose_terminator
sMetangPose178:
ax_pose 45, 0x01e4, 0x80ed, 0xbc00
ax_pose_terminator
sMetangPose179:
ax_pose 0, 0x01e4, 0x80f0, 0xbc00
ax_pose_terminator
sMetangPose180:
ax_pose 2, 0x01e4, 0x80f0, 0xbc00
ax_pose_terminator
sMetangPose181:
ax_pose 44, 0x01e4, 0x80f0, 0xbc00
ax_pose_terminator
sMetangPose182:
ax_pose 3, 0x01e4, 0x90f3, 0xbc00
ax_pose_terminator
sMetangPose183:
ax_pose 5, 0x01e6, 0x90f3, 0xbc00
ax_pose_terminator
sMetangPose184:
ax_pose 45, 0x01e4, 0x90f1, 0xbc00
ax_pose_terminator
sMetangPose185:
ax_pose 6, 0x01e4, 0x90ef, 0xbc00
ax_pose_terminator
sMetangPose186:
ax_pose 8, 0x01e4, 0x90ef, 0xbc00
ax_pose_terminator
sMetangPose187:
ax_pose 46, 0x01e4, 0x90ef, 0xbc00
ax_pose_terminator
sMetangPose188:
ax_pose 9, 0x01e7, 0x90f3, 0xbc00
ax_pose_terminator
sMetangPose189:
ax_pose 11, 0x01e6, 0x90f3, 0xbc00
ax_pose_terminator
sMetangPose190:
ax_pose 47, 0x01e3, 0x90f2, 0xbc00
ax_pose_terminator
sMetangPose191:
ax_pose 12, 0x01e4, 0x80f0, 0xbc00
ax_pose_terminator
sMetangPose192:
ax_pose 14, 0x01e4, 0x80f0, 0xbc00
ax_pose_terminator
sMetangPose193:
ax_pose 48, 0x01e4, 0x80f0, 0xbc00
ax_pose_terminator
sMetangPose194:
ax_pose 9, 0x01e7, 0x80ec, 0xbc00
ax_pose_terminator
sMetangPose195:
ax_pose 11, 0x01e6, 0x80ec, 0xbc00
ax_pose_terminator
sMetangPose196:
ax_pose 47, 0x01e3, 0x80ec, 0xbc00
ax_pose_terminator
sMetangPose197:
ax_pose 6, 0x01e4, 0x80f0, 0xbc00
ax_pose_terminator
sMetangPose198:
ax_pose 8, 0x01e4, 0x80f0, 0xbc00
ax_pose_terminator
sMetangPose199:
ax_pose 46, 0x01e4, 0x80f0, 0xbc00
ax_pose_terminator
sMetangPose200:
ax_pose 3, 0x01e4, 0x80ec, 0xbc00
ax_pose_terminator
sMetangPose201:
ax_pose 5, 0x01e6, 0x80ec, 0xbc00
ax_pose_terminator
sMetangPose202:
ax_pose 45, 0x01e4, 0x80ec, 0xbc00
ax_pose_terminator
sMetangPose203:
ax_pose 1, 0x01e4, 0x80f0, 0xbc00
ax_pose_terminator
sMetangPose204:
ax_pose 4, 0x01e4, 0x80ed, 0xbc00
ax_pose_terminator
sMetangPose205:
ax_pose 7, 0x01e4, 0x80f0, 0xbc00
ax_pose_terminator
sMetangPose206:
ax_pose 10, 0x01e6, 0x80ec, 0xbc00
ax_pose_terminator
sMetangPose207:
ax_pose 13, 0x01e4, 0x80f0, 0xbc00
ax_pose_terminator
sMetangPose208:
ax_pose 10, 0x01e6, 0x90f4, 0xbc00
ax_pose_terminator
sMetangPose209:
ax_pose 7, 0x01e4, 0x90f0, 0xbc00
ax_pose_terminator
sMetangPose210:
ax_pose 4, 0x01e4, 0x90f3, 0xbc00
ax_pose_terminator
sMetangPose211:
ax_pose 0, 0x01e4, 0x80f0, 0xbc00
ax_pose_terminator
sMetangPose212:
ax_pose 3, 0x01e4, 0x80ec, 0xbc00
ax_pose_terminator
sMetangPose213:
ax_pose 6, 0x01e4, 0x80f0, 0xbc00
ax_pose_terminator
sMetangPose214:
ax_pose 9, 0x01e7, 0x80ec, 0xbc00
ax_pose_terminator
sMetangPose215:
ax_pose 12, 0x01e4, 0x80f0, 0xbc00
ax_pose_terminator
sMetangPose216:
ax_pose 9, 0x01e7, 0x90f3, 0xbc00
ax_pose_terminator
sMetangPose217:
ax_pose 6, 0x01e4, 0x90ef, 0xbc00
ax_pose_terminator
sMetangPose218:
ax_pose 3, 0x01e4, 0x90f3, 0xbc00
ax_pose_terminator
.align 2
sMetangAnims_1_1:
ax_anim 8, 0, 0, 0, 0, 0, 0,
ax_anim 8, 0, 2, 0, -1, 0, 0,
ax_anim 8, 0, 2, 0, -2, 0, 0,
ax_anim 8, 0, 2, 0, -3, 0, 0,
ax_anim 8, 0, 0, 0, -3, 0, 0,
ax_anim 8, 0, 1, 0, -2, 0, 0,
ax_anim 8, 0, 1, 0, -1, 0, 0,
ax_anim 8, 0, 1, 0, 0, 0, 0,
ax_anim_terminator
sMetangAnims_1_2:
ax_anim 8, 0, 3, 0, 0, 0, 0,
ax_anim 8, 0, 5, 0, -1, 0, 0,
ax_anim 8, 0, 5, 0, -2, 0, 0,
ax_anim 8, 0, 5, 0, -3, 0, 0,
ax_anim 8, 0, 3, 0, -3, 0, 0,
ax_anim 8, 0, 4, 0, -2, 0, 0,
ax_anim 8, 0, 4, 0, -1, 0, 0,
ax_anim 8, 0, 4, 0, 0, 0, 0,
ax_anim_terminator
sMetangAnims_1_3:
ax_anim 8, 0, 6, 0, 0, 0, 0,
ax_anim 8, 0, 8, 0, -1, 0, 0,
ax_anim 8, 0, 8, 0, -2, 0, 0,
ax_anim 8, 0, 8, 0, -3, 0, 0,
ax_anim 8, 0, 6, 0, -3, 0, 0,
ax_anim 8, 0, 7, 0, -2, 0, 0,
ax_anim 8, 0, 7, 0, -1, 0, 0,
ax_anim 8, 0, 7, 0, 0, 0, 0,
ax_anim_terminator
sMetangAnims_1_4:
ax_anim 8, 0, 9, 0, 0, 0, 0,
ax_anim 8, 0, 11, 0, -1, 0, 0,
ax_anim 8, 0, 11, 0, -2, 0, 0,
ax_anim 8, 0, 11, 0, -3, 0, 0,
ax_anim 8, 0, 9, 0, -3, 0, 0,
ax_anim 8, 0, 10, 0, -2, 0, 0,
ax_anim 8, 0, 10, 0, -1, 0, 0,
ax_anim 8, 0, 10, 0, 0, 0, 0,
ax_anim_terminator
sMetangAnims_1_5:
ax_anim 8, 0, 12, 0, 0, 0, 0,
ax_anim 8, 0, 14, 0, -1, 0, 0,
ax_anim 8, 0, 14, 0, -2, 0, 0,
ax_anim 8, 0, 14, 0, -3, 0, 0,
ax_anim 8, 0, 12, 0, -3, 0, 0,
ax_anim 8, 0, 13, 0, -2, 0, 0,
ax_anim 8, 0, 13, 0, -1, 0, 0,
ax_anim 8, 0, 13, 0, 0, 0, 0,
ax_anim_terminator
sMetangAnims_1_6:
ax_anim 8, 0, 15, 0, 0, 0, 0,
ax_anim 8, 0, 17, 0, -1, 0, 0,
ax_anim 8, 0, 17, 0, -2, 0, 0,
ax_anim 8, 0, 17, 0, -3, 0, 0,
ax_anim 8, 0, 15, 0, -3, 0, 0,
ax_anim 8, 0, 16, 0, -2, 0, 0,
ax_anim 8, 0, 16, 0, -1, 0, 0,
ax_anim 8, 0, 16, 0, 0, 0, 0,
ax_anim_terminator
sMetangAnims_1_7:
ax_anim 8, 0, 18, 0, 0, 0, 0,
ax_anim 8, 0, 20, 0, -1, 0, 0,
ax_anim 8, 0, 20, 0, -2, 0, 0,
ax_anim 8, 0, 20, 0, -3, 0, 0,
ax_anim 8, 0, 18, 0, -3, 0, 0,
ax_anim 8, 0, 19, 0, -2, 0, 0,
ax_anim 8, 0, 19, 0, -1, 0, 0,
ax_anim 8, 0, 19, 0, 0, 0, 0,
ax_anim_terminator
sMetangAnims_1_8:
ax_anim 8, 0, 21, 0, 0, 0, 0,
ax_anim 8, 0, 23, 0, -1, 0, 0,
ax_anim 8, 0, 23, 0, -2, 0, 0,
ax_anim 8, 0, 23, 0, -3, 0, 0,
ax_anim 8, 0, 21, 0, -3, 0, 0,
ax_anim 8, 0, 22, 0, -2, 0, 0,
ax_anim 8, 0, 22, 0, -1, 0, 0,
ax_anim 8, 0, 22, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sMetangAnims_2_1:
ax_anim 2, 0, 24, 0, -1, 0, -1,
ax_anim 2, 0, 25, 0, -2, 0, -2,
ax_anim 6, 0, 26, 0, -2, 0, -2,
ax_anim 1, 0, 26, 0, 3, 0, 3,
ax_anim 1, 2, 26, 0, 7, 0, 7,
ax_anim 1, 0, 26, 0, 13, 0, 11,
ax_anim 2, 0, 26, 0, 28, 0, 21,
ax_anim 2, 1, 26, 1, 28, 1, 21,
ax_anim 2, 0, 26, 0, 28, 0, 21,
ax_anim 2, 0, 26, 1, 28, 1, 21,
ax_anim 2, 0, 26, 0, 28, 0, 21,
ax_anim 2, 0, 26, 1, 28, 1, 21,
ax_anim 2, 0, 24, 0, 14, 0, 14,
ax_anim 2, 0, 24, 0, 6, 0, 6,
ax_anim_terminator
sMetangAnims_2_2:
ax_anim 2, 0, 27, -1, -1, -1, -1,
ax_anim 2, 0, 28, -2, -2, -2, -2,
ax_anim 6, 0, 29, -2, -2, -2, -2,
ax_anim 1, 0, 29, 5, 5, 5, 5,
ax_anim 1, 2, 29, 7, 9, 7, 8,
ax_anim 1, 0, 29, 11, 15, 11, 13,
ax_anim 2, 0, 29, 19, 27, 19, 22,
ax_anim 2, 1, 29, 20, 26, 20, 21,
ax_anim 2, 0, 29, 19, 27, 19, 22,
ax_anim 2, 0, 29, 20, 26, 20, 21,
ax_anim 2, 0, 29, 19, 27, 19, 22,
ax_anim 2, 0, 29, 20, 26, 20, 21,
ax_anim 2, 0, 27, 12, 14, 12, 12,
ax_anim 2, 0, 27, 4, 6, 4, 4,
ax_anim_terminator
sMetangAnims_2_3:
ax_anim 2, 0, 30, -1, 0, -1, 0,
ax_anim 2, 0, 31, -2, 0, -2, 0,
ax_anim 6, 0, 32, -2, 0, -2, 0,
ax_anim 1, 0, 32, 5, 0, 5, 0,
ax_anim 1, 2, 32, 7, 2, 7, 0,
ax_anim 1, 0, 32, 12, 3, 12, 0,
ax_anim 2, 0, 32, 23, 5, 23, 0,
ax_anim 2, 1, 32, 23, 6, 23, 1,
ax_anim 2, 0, 32, 23, 5, 23, 0,
ax_anim 2, 0, 32, 23, 6, 23, 1,
ax_anim 2, 0, 32, 23, 5, 23, 0,
ax_anim 2, 0, 32, 23, 6, 23, 1,
ax_anim 2, 0, 30, 12, 4, 12, 0,
ax_anim 2, 0, 30, 5, 2, 5, 0,
ax_anim_terminator
sMetangAnims_2_4:
ax_anim 2, 0, 33, -1, 1, -1, 1,
ax_anim 2, 0, 34, -2, 2, -2, 2,
ax_anim 6, 0, 35, -2, 2, -2, 2,
ax_anim 1, 0, 35, 4, -5, 4, -5,
ax_anim 1, 2, 35, 6, -7, 6, -7,
ax_anim 1, 0, 35, 12, -11, 11, -12,
ax_anim 2, 0, 35, 20, -16, 19, -22,
ax_anim 2, 1, 35, 21, -15, 20, -21,
ax_anim 2, 0, 35, 20, -16, 19, -22,
ax_anim 2, 0, 35, 21, -15, 20, -21,
ax_anim 2, 0, 35, 20, -16, 19, -22,
ax_anim 2, 0, 35, 21, -15, 20, -21,
ax_anim 2, 0, 33, 12, -10, 12, -12,
ax_anim 2, 0, 33, 6, -6, 6, -6,
ax_anim_terminator
sMetangAnims_2_5:
ax_anim 2, 0, 36, 0, 1, 0, 1,
ax_anim 2, 0, 37, 0, 2, 0, 2,
ax_anim 6, 0, 38, 0, 2, 0, 2,
ax_anim 1, 0, 38, 0, -3, 0, -3,
ax_anim 1, 2, 38, 0, -7, 0, -7,
ax_anim 1, 0, 38, 0, -13, 0, -15,
ax_anim 2, 0, 38, 0, -17, 0, -22,
ax_anim 2, 1, 38, 1, -17, 1, -22,
ax_anim 2, 0, 38, 0, -17, 0, -22,
ax_anim 2, 0, 38, 1, -17, 1, -22,
ax_anim 2, 0, 38, 0, -17, 0, -22,
ax_anim 2, 0, 38, 1, -17, 1, -22,
ax_anim 2, 0, 36, 0, -11, 0, -14,
ax_anim 2, 0, 36, 0, -6, 0, -6,
ax_anim_terminator
sMetangAnims_2_6:
ax_anim 2, 0, 39, 1, 1, 1, 1,
ax_anim 2, 0, 40, 2, 2, 2, 2,
ax_anim 6, 0, 41, 2, 2, 2, 2,
ax_anim 1, 0, 41, -4, -5, -4, -5,
ax_anim 1, 2, 41, -6, -7, -6, -7,
ax_anim 1, 0, 41, -12, -11, -11, -12,
ax_anim 2, 0, 41, -20, -16, -19, -22,
ax_anim 2, 1, 41, -21, -15, -20, -21,
ax_anim 2, 0, 41, -20, -16, -19, -22,
ax_anim 2, 0, 41, -21, -15, -20, -21,
ax_anim 2, 0, 41, -20, -16, -19, -22,
ax_anim 2, 0, 41, -21, -15, -20, -21,
ax_anim 2, 0, 39, -12, -10, -12, -12,
ax_anim 2, 0, 39, -6, -6, -6, -6,
ax_anim_terminator
sMetangAnims_2_7:
ax_anim 2, 0, 42, 1, 0, 1, 0,
ax_anim 2, 0, 43, 2, 0, 2, 0,
ax_anim 6, 0, 44, 2, 0, 2, 0,
ax_anim 1, 0, 44, -5, 0, -5, 0,
ax_anim 1, 2, 44, -7, 2, -7, 0,
ax_anim 1, 0, 44, -12, 3, -12, 0,
ax_anim 2, 0, 44, -23, 5, -23, 0,
ax_anim 2, 1, 44, -23, 6, -23, 1,
ax_anim 2, 0, 44, -23, 5, -23, 0,
ax_anim 2, 0, 44, -23, 6, -23, 1,
ax_anim 2, 0, 44, -23, 5, -23, 0,
ax_anim 2, 0, 44, -23, 6, -23, 1,
ax_anim 2, 0, 42, -12, 4, -12, 0,
ax_anim 2, 0, 42, -5, 2, -5, 0,
ax_anim_terminator
sMetangAnims_2_8:
ax_anim 2, 0, 45, 1, -1, 1, -1,
ax_anim 2, 0, 46, 2, -2, 2, -2,
ax_anim 6, 0, 47, 2, -2, 2, -2,
ax_anim 1, 0, 47, -5, 5, -5, 5,
ax_anim 1, 2, 47, -7, 9, -7, 8,
ax_anim 1, 0, 47, -11, 15, -11, 13,
ax_anim 2, 0, 47, -19, 27, -19, 22,
ax_anim 2, 1, 47, -20, 26, -20, 21,
ax_anim 2, 0, 47, -19, 27, -19, 22,
ax_anim 2, 0, 47, -20, 26, -20, 21,
ax_anim 2, 0, 47, -19, 27, -19, 22,
ax_anim 2, 0, 47, -20, 26, -20, 21,
ax_anim 2, 0, 45, -12, 14, -12, 12,
ax_anim 2, 0, 45, -4, 6, -4, 5,
ax_anim_terminator
.align 2
sMetangAnims_3_1:
ax_anim 2, 0, 52, 0, -2, 0, -2,
ax_anim 6, 0, 87, 0, -3, 0, -3,
ax_anim 2, 0, 87, 0, -1, 0, -1,
ax_anim 2, 2, 52, 0, 7, 0, 7,
ax_anim 2, 0, 49, 0, 15, 0, 15,
ax_anim 4, 1, 57, -1, 16, -1, 16,
ax_anim 2, 0, 50, 2, 16, 2, 16,
ax_anim 2, 0, 51, -1, 18, -1, 18,
ax_anim 4, 0, 87, -2, 20, -2, 20,
ax_anim 2, 0, 52, -1, 16, -1, 16,
ax_anim 1, 0, 48, 0, 9, 0, 9,
ax_anim 1, 0, 48, 0, 3, 0, 3,
ax_anim_terminator
sMetangAnims_3_2:
ax_anim 2, 0, 55, -2, -2, -2, -2,
ax_anim 6, 0, 52, -2, -4, -2, -4,
ax_anim 2, 0, 52, 0, -2, 0, -2,
ax_anim 2, 2, 55, 6, 8, 6, 8,
ax_anim 2, 0, 56, 11, 16, 11, 16,
ax_anim 4, 1, 62, 15, 18, 15, 18,
ax_anim 2, 0, 57, 11, 14, 11, 14,
ax_anim 2, 0, 54, 13, 17, 13, 17,
ax_anim 4, 0, 52, 13, 18, 13, 18,
ax_anim 2, 0, 55, 11, 15, 11, 15,
ax_anim 1, 0, 53, 7, 7, 7, 7,
ax_anim 1, 0, 53, 3, 3, 3, 3,
ax_anim_terminator
sMetangAnims_3_3:
ax_anim 2, 0, 60, -4, 0, -4, 0,
ax_anim 6, 0, 55, -5, 0, -5, 0,
ax_anim 2, 0, 55, -3, 0, -3, 0,
ax_anim 2, 2, 60, 2, 2, 2, 0,
ax_anim 2, 0, 61, 8, 5, 8, 0,
ax_anim 4, 1, 67, 10, 3, 10, 0,
ax_anim 2, 0, 62, 9, 3, 9, 0,
ax_anim 2, 0, 59, 13, 3, 13, 0,
ax_anim 4, 0, 55, 13, 4, 13, 0,
ax_anim 2, 0, 60, 10, 4, 10, 0,
ax_anim 1, 0, 58, 5, 1, 5, 0,
ax_anim 1, 0, 58, 3, 0, 3, 0,
ax_anim_terminator
sMetangAnims_3_4:
ax_anim 2, 0, 65, -2, 2, -2, 2,
ax_anim 6, 0, 60, -4, 4, -4, 4,
ax_anim 2, 0, 60, 0, 0, 0, 0,
ax_anim 2, 2, 65, 6, -6, 6, -6,
ax_anim 2, 0, 66, 9, -10, 9, -9,
ax_anim 4, 1, 70, 12, -12, 12, -12,
ax_anim 2, 0, 67, 14, -12, 14, -13,
ax_anim 2, 0, 64, 15, -14, 15, -14,
ax_anim 4, 0, 60, 17, -14, 17, -14,
ax_anim 2, 0, 65, 11, -11, 11, -11,
ax_anim 1, 0, 63, 6, -5, 6, -6,
ax_anim 1, 0, 63, 3, -3, 3, -3,
ax_anim_terminator
sMetangAnims_3_5:
ax_anim 2, 0, 72, 0, 4, 0, 4,
ax_anim 6, 0, 65, 0, 6, 0, 6,
ax_anim 2, 0, 65, 0, 1, 0, 1,
ax_anim 2, 2, 72, 0, -3, 0, -3,
ax_anim 2, 0, 69, 0, -8, 0, -8,
ax_anim 4, 1, 75, 0, -12, 0, -12,
ax_anim 2, 0, 70, -1, -13, -1, -13,
ax_anim 2, 0, 71, 0, -15, 0, -15,
ax_anim 4, 0, 65, 1, -18, 1, -18,
ax_anim 2, 0, 77, 1, -10, 1, -10,
ax_anim 1, 0, 68, 0, -5, 0, -5,
ax_anim 1, 0, 68, 0, -1, 0, -1,
ax_anim_terminator
sMetangAnims_3_6:
ax_anim 2, 0, 77, 2, 2, 2, 2,
ax_anim 6, 0, 72, 4, 4, 4, 4,
ax_anim 2, 0, 72, 2, 2, 2, 2,
ax_anim 2, 2, 77, -2, -3, -2, -2,
ax_anim 2, 0, 74, -11, -10, -10, -10,
ax_anim 4, 1, 80, -15, -9, -15, -13,
ax_anim 2, 0, 75, -13, -12, -13, -13,
ax_anim 2, 0, 76, -15, -14, -16, -15,
ax_anim 4, 0, 72, -17, -16, -17, -17,
ax_anim 2, 0, 77, -12, -10, -12, -12,
ax_anim 1, 0, 73, -8, -7, -8, -7,
ax_anim 1, 0, 73, -3, -3, -3, -3,
ax_anim_terminator
sMetangAnims_3_7:
ax_anim 2, 0, 82, 4, 0, 4, 0,
ax_anim 6, 0, 77, 6, 0, 6, 0,
ax_anim 2, 0, 77, 4, 0, 4, 0,
ax_anim 2, 2, 82, -2, 2, -2, 0,
ax_anim 2, 0, 79, -8, 2, -8, 0,
ax_anim 4, 1, 85, -9, 3, -9, 0,
ax_anim 2, 0, 80, -11, 3, -11, 0,
ax_anim 2, 0, 81, -10, 5, -10, 0,
ax_anim 4, 0, 77, -12, 4, -12, 0,
ax_anim 2, 0, 82, -9, 5, -9, 0,
ax_anim 1, 0, 78, -6, 4, -6, 0,
ax_anim 1, 0, 78, -3, 0, -3, 0,
ax_anim_terminator
sMetangAnims_3_8:
ax_anim 2, 0, 85, 3, 0, 3, 0,
ax_anim 6, 0, 50, 4, -4, 4, -4,
ax_anim 2, 0, 50, 2, -2, 2, -2,
ax_anim 2, 2, 85, -6, 6, -6, 6,
ax_anim 2, 0, 86, -12, 12, -12, 12,
ax_anim 4, 1, 82, -13, 16, -13, 16,
ax_anim 2, 0, 87, -14, 17, -14, 17,
ax_anim 2, 0, 84, -13, 20, -13, 20,
ax_anim 4, 0, 50, -14, 20, -14, 20,
ax_anim 2, 0, 85, -11, 15, -11, 15,
ax_anim 1, 0, 83, -7, 9, -7, 9,
ax_anim 1, 0, 83, -3, 3, -3, 3,
ax_anim_terminator
.align 2
sMetangAnims_4_1:
ax_anim 2, 0, 89, 0, -2, 0, -2,
ax_anim 6, 2, 89, 0, -5, 0, -3,
ax_anim 1, 0, 91, 0, -1, 0, -1,
ax_anim 1, 0, 88, 0, -1, 0, -1,
ax_anim 2, 1, 90, 0, 3, 0, 3,
ax_anim 2, 0, 90, 1, 3, 1, 3,
ax_anim 2, 0, 90, 0, 3, 0, 3,
ax_anim 2, 0, 90, 1, 3, 1, 3,
ax_anim 2, 0, 90, 0, 3, 0, 3,
ax_anim 2, 0, 90, 1, 3, 1, 3,
ax_anim 2, 0, 90, 0, 3, 0, 3,
ax_anim 2, 0, 88, 0, 1, 0, 1,
ax_anim_terminator
sMetangAnims_4_2:
ax_anim 2, 0, 93, -2, -2, -2, -2,
ax_anim 6, 2, 93, -3, -3, -3, -3,
ax_anim 1, 0, 92, -1, -1, -1, -1,
ax_anim 1, 0, 94, 2, 2, 2, 2,
ax_anim 2, 1, 94, 3, 1, 3, 1,
ax_anim 2, 0, 94, 2, 2, 2, 2,
ax_anim 2, 0, 94, 3, 1, 3, 1,
ax_anim 2, 0, 94, 2, 2, 2, 2,
ax_anim 2, 0, 94, 3, 1, 3, 1,
ax_anim 2, 0, 94, 2, 2, 2, 2,
ax_anim 2, 0, 94, 3, 1, 3, 1,
ax_anim 2, 0, 92, 1, 1, 1, 1,
ax_anim_terminator
sMetangAnims_4_3:
ax_anim 2, 0, 97, -2, 0, -2, 0,
ax_anim 6, 2, 97, -3, 0, -3, 0,
ax_anim 1, 0, 96, -1, 0, -1, 0,
ax_anim 1, 0, 98, 2, 0, 2, 0,
ax_anim 2, 1, 98, 2, 1, 2, 1,
ax_anim 2, 0, 98, 2, 0, 2, 0,
ax_anim 2, 0, 98, 2, 1, 2, 1,
ax_anim 2, 0, 98, 2, 0, 2, 0,
ax_anim 2, 0, 98, 2, 1, 2, 1,
ax_anim 2, 0, 98, 2, 0, 2, 0,
ax_anim 2, 0, 98, 2, 1, 2, 1,
ax_anim 2, 0, 96, 1, 0, 1, 0,
ax_anim_terminator
sMetangAnims_4_4:
ax_anim 2, 0, 101, -2, 2, -2, 2,
ax_anim 6, 2, 101, -3, 3, -3, 3,
ax_anim 1, 0, 100, -1, 1, -1, 1,
ax_anim 1, 0, 102, 2, -2, 2, -2,
ax_anim 2, 1, 102, 3, -1, 3, -1,
ax_anim 2, 0, 102, 2, -2, 2, -2,
ax_anim 2, 0, 102, 3, -1, 3, -1,
ax_anim 2, 0, 102, 2, -2, 2, -2,
ax_anim 2, 0, 102, 3, -1, 3, -1,
ax_anim 2, 0, 102, 2, -2, 2, -2,
ax_anim 2, 0, 102, 3, -1, 3, -1,
ax_anim 2, 0, 100, 1, -1, 1, -1,
ax_anim_terminator
sMetangAnims_4_5:
ax_anim 2, 0, 105, 0, 2, 0, 2,
ax_anim 6, 2, 105, 0, 3, 0, 3,
ax_anim 1, 0, 104, 0, 1, 0, 1,
ax_anim 1, 0, 106, 0, -3, 0, -3,
ax_anim 2, 1, 106, 1, -3, 1, -3,
ax_anim 2, 0, 106, 0, -3, 0, -3,
ax_anim 2, 0, 106, 1, -3, 1, -3,
ax_anim 2, 0, 106, 0, -3, 0, -3,
ax_anim 2, 0, 106, 1, -3, 1, -3,
ax_anim 2, 0, 106, 0, -3, 0, -3,
ax_anim 2, 0, 106, 1, -3, 1, -3,
ax_anim 2, 0, 104, 0, -1, 0, -1,
ax_anim_terminator
sMetangAnims_4_6:
ax_anim 2, 0, 109, 2, 2, 2, 2,
ax_anim 6, 2, 109, 3, 3, 3, 3,
ax_anim 1, 0, 108, 1, 1, 1, 1,
ax_anim 1, 0, 110, -2, -2, -2, -2,
ax_anim 2, 1, 110, -3, -1, -3, -1,
ax_anim 2, 0, 110, -2, -2, -2, -2,
ax_anim 2, 0, 110, -3, -1, -3, -1,
ax_anim 2, 0, 110, -2, -2, -2, -2,
ax_anim 2, 0, 110, -3, -1, -3, -1,
ax_anim 2, 0, 110, -2, -2, -2, -2,
ax_anim 2, 0, 110, -3, -1, -3, -1,
ax_anim 2, 0, 108, -1, -1, -1, -1,
ax_anim_terminator
sMetangAnims_4_7:
ax_anim 2, 0, 113, 2, 0, 2, 0,
ax_anim 6, 2, 113, 3, 0, 3, 0,
ax_anim 1, 0, 112, 1, 0, 1, 0,
ax_anim 1, 0, 114, -2, 0, -2, 0,
ax_anim 2, 1, 114, -2, 1, -2, 1,
ax_anim 2, 0, 114, -2, 0, -2, 0,
ax_anim 2, 0, 114, -2, 1, -2, 1,
ax_anim 2, 0, 114, -2, 0, -2, 0,
ax_anim 2, 0, 114, -2, 1, -2, 1,
ax_anim 2, 0, 114, -2, 0, -2, 0,
ax_anim 2, 0, 114, -2, 1, -2, 1,
ax_anim 2, 0, 112, -1, 0, -1, 0,
ax_anim_terminator
sMetangAnims_4_8:
ax_anim 2, 0, 117, 2, -2, 2, -2,
ax_anim 6, 2, 117, 3, -3, 3, -3,
ax_anim 1, 0, 116, 1, -1, 1, -1,
ax_anim 1, 0, 118, -2, 2, -2, 2,
ax_anim 2, 1, 118, -3, 1, -3, 1,
ax_anim 2, 0, 118, -2, 2, -2, 2,
ax_anim 2, 0, 118, -3, 1, -3, 1,
ax_anim 2, 0, 118, -2, 2, -2, 2,
ax_anim 2, 0, 118, -3, 1, -3, 1,
ax_anim 2, 0, 118, -2, 2, -2, 2,
ax_anim 2, 0, 118, -3, 1, -3, 1,
ax_anim 2, 0, 116, -1, 1, -1, 1,
ax_anim_terminator
.align 2
sMetangAnims_5_1:
ax_anim 2, 0, 120, 0, 0, 0, 0,
ax_anim 2, 0, 121, 0, 0, 0, 0,
ax_anim 2, 0, 122, 0, 0, 0, 0,
ax_anim 2, 0, 123, 0, 0, 0, 0,
ax_anim 2, 0, 124, 0, 0, 0, 0,
ax_anim 2, 0, 125, 0, 0, 0, 0,
ax_anim 2, 0, 126, 0, 0, 0, 0,
ax_anim 2, 0, 127, 0, 0, 0, 0,
ax_anim 2, 2, 120, 0, 0, 0, 0,
ax_anim_terminator
sMetangAnims_5_2:
ax_anim 2, 0, 127, 0, 0, 0, 0,
ax_anim 2, 0, 120, 0, 0, 0, 0,
ax_anim 2, 0, 121, 0, 0, 0, 0,
ax_anim 2, 0, 122, 0, 0, 0, 0,
ax_anim 2, 0, 123, 0, 0, 0, 0,
ax_anim 2, 0, 124, 0, 0, 0, 0,
ax_anim 2, 0, 125, 0, 0, 0, 0,
ax_anim 2, 0, 126, 0, 0, 0, 0,
ax_anim 2, 2, 127, 0, 0, 0, 0,
ax_anim_terminator
sMetangAnims_5_3:
ax_anim 2, 0, 126, 0, 0, 0, 0,
ax_anim 2, 0, 127, 0, 0, 0, 0,
ax_anim 2, 0, 120, 0, 0, 0, 0,
ax_anim 2, 0, 121, 0, 0, 0, 0,
ax_anim 2, 0, 122, 0, 0, 0, 0,
ax_anim 2, 0, 123, 0, 0, 0, 0,
ax_anim 2, 0, 124, 0, 0, 0, 0,
ax_anim 2, 0, 125, 0, 0, 0, 0,
ax_anim 2, 2, 126, 0, 0, 0, 0,
ax_anim_terminator
sMetangAnims_5_4:
ax_anim 2, 0, 125, 0, 0, 0, 0,
ax_anim 2, 0, 126, 0, 0, 0, 0,
ax_anim 2, 0, 127, 0, 0, 0, 0,
ax_anim 2, 0, 120, 0, 0, 0, 0,
ax_anim 2, 0, 121, 0, 0, 0, 0,
ax_anim 2, 0, 122, 0, 0, 0, 0,
ax_anim 2, 0, 123, 0, 0, 0, 0,
ax_anim 2, 0, 124, 0, 0, 0, 0,
ax_anim 2, 2, 125, 0, 0, 0, 0,
ax_anim_terminator
sMetangAnims_5_5:
ax_anim 2, 0, 124, 0, 0, 0, 0,
ax_anim 2, 0, 125, 0, 0, 0, 0,
ax_anim 2, 0, 126, 0, 0, 0, 0,
ax_anim 2, 0, 127, 0, 0, 0, 0,
ax_anim 2, 0, 120, 0, 0, 0, 0,
ax_anim 2, 0, 121, 0, 0, 0, 0,
ax_anim 2, 0, 122, 0, 0, 0, 0,
ax_anim 2, 0, 123, 0, 0, 0, 0,
ax_anim 2, 2, 124, 0, 0, 0, 0,
ax_anim_terminator
sMetangAnims_5_6:
ax_anim 2, 0, 123, 0, 0, 0, 0,
ax_anim 2, 0, 124, 0, 0, 0, 0,
ax_anim 2, 0, 125, 0, 0, 0, 0,
ax_anim 2, 0, 126, 0, 0, 0, 0,
ax_anim 2, 0, 127, 0, 0, 0, 0,
ax_anim 2, 0, 120, 0, 0, 0, 0,
ax_anim 2, 0, 121, 0, 0, 0, 0,
ax_anim 2, 0, 122, 0, 0, 0, 0,
ax_anim 2, 2, 123, 0, 0, 0, 0,
ax_anim_terminator
sMetangAnims_5_7:
ax_anim 2, 0, 122, 0, 0, 0, 0,
ax_anim 2, 0, 123, 0, 0, 0, 0,
ax_anim 2, 0, 124, 0, 0, 0, 0,
ax_anim 2, 0, 125, 0, 0, 0, 0,
ax_anim 2, 0, 126, 0, 0, 0, 0,
ax_anim 2, 0, 127, 0, 0, 0, 0,
ax_anim 2, 0, 120, 0, 0, 0, 0,
ax_anim 2, 0, 121, 0, 0, 0, 0,
ax_anim 2, 2, 122, 0, 0, 0, 0,
ax_anim_terminator
sMetangAnims_5_8:
ax_anim 2, 0, 121, 0, 0, 0, 0,
ax_anim 2, 0, 122, 0, 0, 0, 0,
ax_anim 2, 0, 123, 0, 0, 0, 0,
ax_anim 2, 0, 124, 0, 0, 0, 0,
ax_anim 2, 0, 125, 0, 0, 0, 0,
ax_anim 2, 0, 126, 0, 0, 0, 0,
ax_anim 2, 0, 127, 0, 0, 0, 0,
ax_anim 2, 0, 120, 0, 0, 0, 0,
ax_anim 2, 2, 121, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sMetangAnims_6_1:
ax_anim 16, 0, 128, 0, 0, 0, 0,
ax_anim 12, 0, 128, 0, -1, 0, 0,
ax_anim 16, 0, 128, 0, -2, 0, 0,
ax_anim 16, 0, 129, 0, -2, 0, 0,
ax_anim 12, 0, 129, 0, -1, 0, 0,
ax_anim 16, 0, 129, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sMetangAnims_7_1:
ax_anim 2, 0, 130, 0, -3, 0, -3,
ax_anim 8, 0, 130, 0, -4, 0, -4,
ax_anim_terminator
sMetangAnims_7_2:
ax_anim 2, 0, 131, -3, -3, -3, -3,
ax_anim 8, 0, 131, -4, -4, -4, -4,
ax_anim_terminator
sMetangAnims_7_3:
ax_anim 2, 0, 132, -3, 0, -3, 0,
ax_anim 8, 0, 132, -4, 0, -4, 0,
ax_anim_terminator
sMetangAnims_7_4:
ax_anim 2, 0, 133, -3, 3, -3, 3,
ax_anim 8, 0, 133, -4, 4, -4, 4,
ax_anim_terminator
sMetangAnims_7_5:
ax_anim 2, 0, 134, 0, 3, 0, 3,
ax_anim 8, 0, 134, 0, 4, 0, 4,
ax_anim_terminator
sMetangAnims_7_6:
ax_anim 2, 0, 135, 3, 3, 3, 3,
ax_anim 8, 0, 135, 4, 4, 4, 4,
ax_anim_terminator
sMetangAnims_7_7:
ax_anim 2, 0, 136, 3, 0, 3, 0,
ax_anim 8, 0, 136, 4, 0, 4, 0,
ax_anim_terminator
sMetangAnims_7_8:
ax_anim 2, 0, 137, 3, -3, 3, -3,
ax_anim 8, 0, 137, 4, -4, 4, -4,
ax_anim_terminator
.align 2
sMetangAnims_8_1:
ax_anim 12, 0, 138, 0, 0, 0, 0,
ax_anim 12, 0, 140, 0, -1, 0, 0,
ax_anim 12, 0, 140, 0, -2, 0, 0,
ax_anim 12, 0, 140, 0, -3, 0, 0,
ax_anim 12, 0, 138, 0, -3, 0, 0,
ax_anim 12, 0, 139, 0, -2, 0, 0,
ax_anim 12, 0, 139, 0, -1, 0, 0,
ax_anim 12, 0, 139, 0, 0, 0, 0,
ax_anim_terminator
sMetangAnims_8_2:
ax_anim 12, 0, 141, 0, 0, 0, 0,
ax_anim 12, 0, 143, 0, -1, 0, 0,
ax_anim 12, 0, 143, 0, -2, 0, 0,
ax_anim 12, 0, 143, 0, -3, 0, 0,
ax_anim 12, 0, 141, 0, -3, 0, 0,
ax_anim 12, 0, 142, 0, -2, 0, 0,
ax_anim 12, 0, 142, 0, -1, 0, 0,
ax_anim 12, 0, 142, 0, 0, 0, 0,
ax_anim_terminator
sMetangAnims_8_3:
ax_anim 12, 0, 144, 0, 0, 0, 0,
ax_anim 12, 0, 146, 0, -1, 0, 0,
ax_anim 12, 0, 146, 0, -2, 0, 0,
ax_anim 12, 0, 146, 0, -3, 0, 0,
ax_anim 12, 0, 144, 0, -3, 0, 0,
ax_anim 12, 0, 145, 0, -2, 0, 0,
ax_anim 12, 0, 145, 0, -1, 0, 0,
ax_anim 12, 0, 145, 0, 0, 0, 0,
ax_anim_terminator
sMetangAnims_8_4:
ax_anim 12, 0, 147, 0, 0, 0, 0,
ax_anim 12, 0, 149, 0, -1, 0, 0,
ax_anim 12, 0, 149, 0, -2, 0, 0,
ax_anim 12, 0, 149, 0, -3, 0, 0,
ax_anim 12, 0, 147, 0, -3, 0, 0,
ax_anim 12, 0, 148, 0, -2, 0, 0,
ax_anim 12, 0, 148, 0, -1, 0, 0,
ax_anim 12, 0, 148, 0, 0, 0, 0,
ax_anim_terminator
sMetangAnims_8_5:
ax_anim 12, 0, 150, 0, 0, 0, 0,
ax_anim 12, 0, 152, 0, -1, 0, 0,
ax_anim 12, 0, 152, 0, -2, 0, 0,
ax_anim 12, 0, 152, 0, -3, 0, 0,
ax_anim 12, 0, 150, 0, -3, 0, 0,
ax_anim 12, 0, 151, 0, -2, 0, 0,
ax_anim 12, 0, 151, 0, -1, 0, 0,
ax_anim 12, 0, 151, 0, 0, 0, 0,
ax_anim_terminator
sMetangAnims_8_6:
ax_anim 12, 0, 153, 0, 0, 0, 0,
ax_anim 12, 0, 155, 0, -1, 0, 0,
ax_anim 12, 0, 155, 0, -2, 0, 0,
ax_anim 12, 0, 155, 0, -3, 0, 0,
ax_anim 12, 0, 153, 0, -3, 0, 0,
ax_anim 12, 0, 154, 0, -2, 0, 0,
ax_anim 12, 0, 154, 0, -1, 0, 0,
ax_anim 12, 0, 154, 0, 0, 0, 0,
ax_anim_terminator
sMetangAnims_8_7:
ax_anim 12, 0, 156, 0, 0, 0, 0,
ax_anim 12, 0, 158, 0, -1, 0, 0,
ax_anim 12, 0, 158, 0, -2, 0, 0,
ax_anim 12, 0, 158, 0, -3, 0, 0,
ax_anim 12, 0, 156, 0, -3, 0, 0,
ax_anim 12, 0, 157, 0, -2, 0, 0,
ax_anim 12, 0, 157, 0, -1, 0, 0,
ax_anim 12, 0, 157, 0, 0, 0, 0,
ax_anim_terminator
sMetangAnims_8_8:
ax_anim 12, 0, 159, 0, 0, 0, 0,
ax_anim 12, 0, 161, 0, -1, 0, 0,
ax_anim 12, 0, 161, 0, -2, 0, 0,
ax_anim 12, 0, 161, 0, -3, 0, 0,
ax_anim 12, 0, 159, 0, -3, 0, 0,
ax_anim 12, 0, 160, 0, -2, 0, 0,
ax_anim 12, 0, 160, 0, -1, 0, 0,
ax_anim 12, 0, 160, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sMetangAnims_9_1:
ax_anim 2, 0, 162, 0, 0, 0, 0,
ax_anim 1, 0, 163, 6, 4, 6, 3,
ax_anim 2, 0, 164, 8, 13, 8, 9,
ax_anim 2, 0, 165, 6, 18, 7, 15,
ax_anim 3, 0, 166, 0, 22, 0, 18,
ax_anim 2, 3, 167, -6, 18, -7, 15,
ax_anim 2, 0, 168, -8, 13, -8, 9,
ax_anim 1, 0, 169, -6, 4, -6, 3,
ax_anim 1, 0, 162, 0, 0, 0, 0,
ax_anim_terminator
sMetangAnims_9_2:
ax_anim 2, 0, 169, 0, 0, 0, 0,
ax_anim 1, 0, 162, 8, 0, 8, 0,
ax_anim 2, 0, 163, 19, 4, 19, 4,
ax_anim 2, 0, 164, 23, 14, 23, 14,
ax_anim 3, 0, 165, 21, 22, 21, 16,
ax_anim 2, 3, 166, 11, 22, 11, 18,
ax_anim 2, 0, 167, 3, 15, 3, 15,
ax_anim 1, 0, 168, 0, 7, 0, 7,
ax_anim 1, 0, 169, 0, 0, 0, 0,
ax_anim_terminator
sMetangAnims_9_3:
ax_anim 2, 0, 168, 0, 0, 0, 0,
ax_anim 1, 0, 169, 3, -3, 3, -3,
ax_anim 2, 0, 162, 12, -4, 12, -4,
ax_anim 2, 0, 163, 18, 0, 18, -3,
ax_anim 3, 0, 164, 19, 4, 19, 0,
ax_anim 2, 3, 165, 15, 9, 15, 7,
ax_anim 2, 0, 166, 10, 9, 10, 9,
ax_anim 1, 0, 167, 3, 7, 3, 7,
ax_anim 1, 0, 168, 0, 0, 0, 0,
ax_anim_terminator
sMetangAnims_9_4:
ax_anim 2, 0, 167, 0, 0, 0, 0,
ax_anim 1, 0, 168, 0, -5, 0, -5,
ax_anim 2, 0, 169, 2, -11, 2, -13,
ax_anim 2, 0, 162, 10, -15, 10, -19,
ax_anim 3, 0, 163, 18, -17, 18, -22,
ax_anim 2, 3, 164, 20, -8, 20, -12,
ax_anim 2, 0, 165, 17, -2, 17, -2,
ax_anim 1, 0, 166, 10, 0, 10, 0,
ax_anim 1, 0, 167, 0, 0, 0, 0,
ax_anim_terminator
sMetangAnims_9_5:
ax_anim 2, 0, 166, 0, 0, 0, 0,
ax_anim 1, 0, 167, -4, -1, -4, -1,
ax_anim 2, 0, 168, -8, -6, -8, -6,
ax_anim 2, 0, 169, -6, -14, -6, -18,
ax_anim 3, 0, 162, 0, -17, 0, -22,
ax_anim 2, 3, 163, 6, -14, 6, -18,
ax_anim 2, 0, 164, 8, -6, 8, -6,
ax_anim 1, 0, 165, 5, -1, 5, -1,
ax_anim 1, 0, 166, 0, 0, 0, 0,
ax_anim_terminator
sMetangAnims_9_6:
ax_anim 2, 0, 165, 0, 0, 0, 0,
ax_anim 1, 0, 164, 0, -5, 0, -5,
ax_anim 2, 0, 163, -2, -11, -2, -13,
ax_anim 2, 0, 162, -10, -15, -10, -19,
ax_anim 3, 0, 169, -18, -17, -18, -22,
ax_anim 2, 3, 168, -20, -8, -20, -12,
ax_anim 2, 0, 167, -17, -2, -17, -2,
ax_anim 1, 0, 166, -10, 0, -10, 0,
ax_anim 1, 0, 165, 0, 0, 0, 0,
ax_anim_terminator
sMetangAnims_9_7:
ax_anim 2, 0, 164, 0, 0, 0, 0,
ax_anim 1, 0, 163, -3, -3, -3, -3,
ax_anim 2, 0, 162, -12, -4, -12, -4,
ax_anim 2, 0, 169, -18, 0, -18, -3,
ax_anim 3, 0, 168, -19, 4, -19, 0,
ax_anim 2, 3, 167, -15, 9, -15, 7,
ax_anim 2, 0, 166, -10, 9, -10, 9,
ax_anim 1, 0, 165, -3, 7, -3, 7,
ax_anim 1, 0, 164, 0, 0, 0, 0,
ax_anim_terminator
sMetangAnims_9_8:
ax_anim 2, 0, 163, 0, 0, 0, 0,
ax_anim 1, 0, 162, -8, 0, -8, 0,
ax_anim 2, 0, 169, -19, 4, -19, 4,
ax_anim 2, 0, 168, -23, 14, -23, 14,
ax_anim 3, 0, 167, -21, 22, -21, 16,
ax_anim 2, 3, 166, -11, 22, -11, 18,
ax_anim 2, 0, 165, -3, 15, -3, 15,
ax_anim 1, 0, 164, 0, 7, 0, 7,
ax_anim 1, 0, 163, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sMetangAnims_10_1:
ax_anim 2, 0, 170, 0, 0, 0, 0,
ax_anim 2, 0, 170, 6, 0, 6, 0,
ax_anim 2, 0, 170, -6, 0, -6, 0,
ax_anim 2, 0, 170, 10, 0, 10, 0,
ax_anim 2, 0, 170, -10, 0, -10, 0,
ax_anim 2, 0, 170, 12, 0, 12, 0,
ax_anim 3, 0, 170, -12, 0, -12, 0,
ax_anim 3, 0, 170, 13, 0, 13, 0,
ax_anim 3, 0, 170, -13, 0, -13, 0,
ax_anim 2, 0, 170, 12, 0, 12, 0,
ax_anim 3, 0, 170, -12, 0, -12, 0,
ax_anim 2, 0, 170, 10, 0, 10, 0,
ax_anim 2, 0, 170, -10, 0, -10, 0,
ax_anim 2, 0, 170, 6, 0, 6, 0,
ax_anim 2, 0, 170, -6, 0, -6, 0,
ax_anim 2, 0, 170, 0, 0, 0, 0,
ax_anim_terminator
sMetangAnims_10_2:
ax_anim 2, 0, 171, 0, 0, 0, 0,
ax_anim 2, 0, 171, 6, -6, 6, -6,
ax_anim 2, 0, 171, -6, 6, -6, 6,
ax_anim 2, 0, 171, 10, -10, 10, -10,
ax_anim 2, 0, 171, -10, 10, -10, 10,
ax_anim 2, 0, 171, 12, -12, 12, -12,
ax_anim 3, 0, 171, -12, 12, -12, 12,
ax_anim 3, 0, 171, 13, -13, 13, -13,
ax_anim 3, 0, 171, -13, 13, -13, 13,
ax_anim 2, 0, 171, 12, -12, 12, -12,
ax_anim 3, 0, 171, -12, 12, -12, 12,
ax_anim 2, 0, 171, 10, -10, 10, -10,
ax_anim 2, 0, 171, -10, 10, -10, 10,
ax_anim 2, 0, 171, 6, -6, 6, -6,
ax_anim 2, 0, 171, -6, 6, -6, 6,
ax_anim 2, 0, 171, 0, 0, 0, 0,
ax_anim_terminator
sMetangAnims_10_3:
ax_anim 2, 0, 172, 0, 0, 0, 0,
ax_anim 2, 0, 172, 0, -6, 0, -6,
ax_anim 2, 0, 172, 0, 6, 0, 6,
ax_anim 2, 0, 172, 0, -10, 0, -10,
ax_anim 2, 0, 172, 0, 10, 0, 10,
ax_anim 2, 0, 172, 0, -12, 0, -12,
ax_anim 3, 0, 172, 0, 12, 0, 12,
ax_anim 3, 0, 172, 0, -13, 0, -13,
ax_anim 3, 0, 172, 0, 13, 0, 13,
ax_anim 2, 0, 172, 0, -12, 0, -12,
ax_anim 3, 0, 172, 0, 12, 0, 12,
ax_anim 2, 0, 172, 0, -10, 0, -10,
ax_anim 2, 0, 172, 0, 10, 0, 10,
ax_anim 2, 0, 172, 0, -6, 0, -6,
ax_anim 2, 0, 172, 0, 6, 0, 6,
ax_anim 2, 0, 172, 0, 0, 0, 0,
ax_anim_terminator
sMetangAnims_10_4:
ax_anim 2, 0, 173, 0, 0, 0, 0,
ax_anim 2, 0, 173, -6, -6, -6, -6,
ax_anim 2, 0, 173, 6, 6, 6, 6,
ax_anim 2, 0, 173, -10, -10, -10, -10,
ax_anim 2, 0, 173, 10, 10, 10, 10,
ax_anim 2, 0, 173, -12, -12, -12, -12,
ax_anim 3, 0, 173, 12, 12, 12, 12,
ax_anim 3, 0, 173, -13, -13, -13, -13,
ax_anim 3, 0, 173, 13, 13, 13, 13,
ax_anim 2, 0, 173, -12, -12, -12, -12,
ax_anim 3, 0, 173, 12, 12, 12, 12,
ax_anim 2, 0, 173, -10, -10, -10, -10,
ax_anim 2, 0, 173, 10, 10, 10, 10,
ax_anim 2, 0, 173, -6, -6, -6, -6,
ax_anim 2, 0, 173, 6, 6, 6, 6,
ax_anim 2, 0, 173, 0, 0, 0, 0,
ax_anim_terminator
sMetangAnims_10_5:
ax_anim 2, 0, 174, 0, 0, 0, 0,
ax_anim 2, 0, 174, 6, 0, 6, 0,
ax_anim 2, 0, 174, -6, 0, -6, 0,
ax_anim 2, 0, 174, 10, 0, 10, 0,
ax_anim 2, 0, 174, -10, 0, -10, 0,
ax_anim 2, 0, 174, 12, 0, 12, 0,
ax_anim 3, 0, 174, -12, 0, -12, 0,
ax_anim 3, 0, 174, 13, 0, 13, 0,
ax_anim 3, 0, 174, -13, 0, -13, 0,
ax_anim 2, 0, 174, 12, 0, 12, 0,
ax_anim 3, 0, 174, -12, 0, -12, 0,
ax_anim 2, 0, 174, 10, 0, 10, 0,
ax_anim 2, 0, 174, -10, 0, -10, 0,
ax_anim 2, 0, 174, 6, 0, 6, 0,
ax_anim 2, 0, 174, -6, 0, -6, 0,
ax_anim 2, 0, 174, 0, 0, 0, 0,
ax_anim_terminator
sMetangAnims_10_6:
ax_anim 2, 0, 175, 0, 0, 0, 0,
ax_anim 2, 0, 175, 6, -6, 6, -6,
ax_anim 2, 0, 175, -6, 6, -6, 6,
ax_anim 2, 0, 175, 10, -10, 10, -10,
ax_anim 2, 0, 175, -10, 10, -10, 10,
ax_anim 2, 0, 175, 12, -12, 12, -12,
ax_anim 3, 0, 175, -12, 12, -12, 12,
ax_anim 3, 0, 175, 13, -13, 13, -13,
ax_anim 3, 0, 175, -13, 13, -13, 13,
ax_anim 2, 0, 175, 12, -12, 12, -12,
ax_anim 3, 0, 175, -12, 12, -12, 12,
ax_anim 2, 0, 175, 10, -10, 10, -10,
ax_anim 2, 0, 175, -10, 10, -10, 10,
ax_anim 2, 0, 175, 6, -6, 6, -6,
ax_anim 2, 0, 175, -6, 6, -6, 6,
ax_anim 2, 0, 175, 0, 0, 0, 0,
ax_anim_terminator
sMetangAnims_10_7:
ax_anim 2, 0, 176, 0, 0, 0, 0,
ax_anim 2, 0, 176, 0, -6, 0, -6,
ax_anim 2, 0, 176, 0, 6, 0, 6,
ax_anim 2, 0, 176, 0, -10, 0, -10,
ax_anim 2, 0, 176, 0, 10, 0, 10,
ax_anim 2, 0, 176, 0, -12, 0, -12,
ax_anim 3, 0, 176, 0, 12, 0, 12,
ax_anim 3, 0, 176, 0, -13, 0, -13,
ax_anim 3, 0, 176, 0, 13, 0, 13,
ax_anim 2, 0, 176, 0, -12, 0, -12,
ax_anim 3, 0, 176, 0, 12, 0, 12,
ax_anim 2, 0, 176, 0, -10, 0, -10,
ax_anim 2, 0, 176, 0, 10, 0, 10,
ax_anim 2, 0, 176, 0, -6, 0, -6,
ax_anim 2, 0, 176, 0, 6, 0, 6,
ax_anim 2, 0, 176, 0, 0, 0, 0,
ax_anim_terminator
sMetangAnims_10_8:
ax_anim 2, 0, 177, 0, 0, 0, 0,
ax_anim 2, 0, 177, -6, -6, -6, -6,
ax_anim 2, 0, 177, 6, 6, 6, 6,
ax_anim 2, 0, 177, -10, -10, -10, -10,
ax_anim 2, 0, 177, 10, 10, 10, 10,
ax_anim 2, 0, 177, -12, -12, -12, -12,
ax_anim 3, 0, 177, 12, 12, 12, 12,
ax_anim 3, 0, 177, -13, -13, -13, -13,
ax_anim 3, 0, 177, 13, 13, 13, 13,
ax_anim 2, 0, 177, -12, -12, -12, -12,
ax_anim 3, 0, 177, 12, 12, 12, 12,
ax_anim 2, 0, 177, -10, -10, -10, -10,
ax_anim 2, 0, 177, 10, 10, 10, 10,
ax_anim 2, 0, 177, -6, -6, -6, -6,
ax_anim 2, 0, 177, 6, 6, 6, 6,
ax_anim 2, 0, 177, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sMetangAnims_11_1:
ax_anim 2, 0, 178, 0, 0, 0, 0,
ax_anim 1, 0, 179, 0, -10, 0, 0,
ax_anim 2, 0, 179, 0, -16, 0, 0,
ax_anim 3, 0, 179, 0, -20, 0, 0,
ax_anim 4, 0, 179, 0, -21, 0, 0,
ax_anim 4, 0, 178, 0, -22, 0, 0,
ax_anim 3, 0, 180, 0, -22, 0, 0,
ax_anim 2, 0, 180, 0, -18, 0, 0,
ax_anim 1, 0, 180, 0, -8, 0, 0,
ax_anim 2, 2, 180, 0, 10, 0, 0,
ax_anim_terminator
sMetangAnims_11_2:
ax_anim 2, 0, 181, 0, 0, 0, 0,
ax_anim 1, 0, 182, 0, -10, 0, 0,
ax_anim 2, 0, 182, 0, -16, 0, 0,
ax_anim 3, 0, 182, 0, -20, 0, 0,
ax_anim 4, 0, 182, 0, -21, 0, 0,
ax_anim 4, 0, 181, 0, -22, 0, 0,
ax_anim 3, 0, 183, 0, -22, 0, 0,
ax_anim 2, 0, 183, 0, -18, 0, 0,
ax_anim 1, 0, 183, 0, -8, 0, 0,
ax_anim 2, 2, 183, 0, 9, 0, 0,
ax_anim_terminator
sMetangAnims_11_3:
ax_anim 2, 0, 184, 0, 0, 0, 0,
ax_anim 1, 0, 185, 0, -10, 0, 0,
ax_anim 2, 0, 185, 0, -16, 0, 0,
ax_anim 3, 0, 185, 0, -20, 0, 0,
ax_anim 4, 0, 185, 0, -21, 0, 0,
ax_anim 4, 0, 184, 0, -22, 0, 0,
ax_anim 3, 0, 186, 0, -22, 0, 0,
ax_anim 2, 0, 186, 0, -18, 0, 0,
ax_anim 1, 0, 186, 0, -8, 0, 0,
ax_anim 2, 2, 186, 0, 9, 0, 0,
ax_anim_terminator
sMetangAnims_11_4:
ax_anim 2, 0, 187, 0, 0, 0, 0,
ax_anim 1, 0, 188, 0, -10, 0, 0,
ax_anim 2, 0, 188, 0, -16, 0, 0,
ax_anim 3, 0, 188, 0, -20, 0, 0,
ax_anim 4, 0, 188, 0, -21, 0, 0,
ax_anim 4, 0, 187, 0, -22, 0, 0,
ax_anim 3, 0, 189, 0, -21, 0, 0,
ax_anim 2, 0, 189, 0, -17, 0, 0,
ax_anim 1, 0, 189, 0, -8, 0, 0,
ax_anim 2, 2, 189, 0, 10, 0, 0,
ax_anim_terminator
sMetangAnims_11_5:
ax_anim 2, 0, 190, 0, 0, 0, 0,
ax_anim 1, 0, 191, 0, -10, 0, 0,
ax_anim 2, 0, 191, 0, -16, 0, 0,
ax_anim 3, 0, 191, 0, -20, 0, 0,
ax_anim 4, 0, 191, 0, -21, 0, 0,
ax_anim 4, 0, 190, 0, -23, 0, 0,
ax_anim 3, 0, 192, 0, -22, 0, 0,
ax_anim 2, 0, 192, 0, -18, 0, 0,
ax_anim 1, 0, 192, 0, -8, 0, 0,
ax_anim 2, 2, 192, 0, 9, 0, 0,
ax_anim_terminator
sMetangAnims_11_6:
ax_anim 2, 0, 193, 0, 0, 0, 0,
ax_anim 1, 0, 194, 0, -10, 0, 0,
ax_anim 2, 0, 194, 0, -16, 0, 0,
ax_anim 3, 0, 194, 0, -20, 0, 0,
ax_anim 4, 0, 194, 0, -21, 0, 0,
ax_anim 4, 0, 193, 0, -22, 0, 0,
ax_anim 3, 0, 195, 0, -21, 0, 0,
ax_anim 2, 0, 195, 0, -17, 0, 0,
ax_anim 1, 0, 195, 0, -8, 0, 0,
ax_anim 2, 2, 195, 0, 10, 0, 0,
ax_anim_terminator
sMetangAnims_11_7:
ax_anim 2, 0, 196, 0, 0, 0, 0,
ax_anim 1, 0, 197, 0, -10, 0, 0,
ax_anim 2, 0, 197, 0, -16, 0, 0,
ax_anim 3, 0, 197, 0, -20, 0, 0,
ax_anim 4, 0, 197, 0, -21, 0, 0,
ax_anim 4, 0, 196, 0, -22, 0, 0,
ax_anim 3, 0, 198, 0, -22, 0, 0,
ax_anim 2, 0, 198, 0, -18, 0, 0,
ax_anim 1, 0, 198, 0, -8, 0, 0,
ax_anim 2, 2, 198, 0, 9, 0, 0,
ax_anim_terminator
sMetangAnims_11_8:
ax_anim 2, 0, 199, 0, 0, 0, 0,
ax_anim 1, 0, 200, 0, -10, 0, 0,
ax_anim 2, 0, 200, 0, -16, 0, 0,
ax_anim 3, 0, 200, 0, -20, 0, 0,
ax_anim 4, 0, 200, 0, -21, 0, 0,
ax_anim 4, 0, 199, 0, -22, 0, 0,
ax_anim 3, 0, 201, 0, -22, 0, 0,
ax_anim 2, 0, 201, 0, -18, 0, 0,
ax_anim 1, 0, 201, 0, -8, 0, 0,
ax_anim 2, 2, 201, 0, 9, 0, 0,
ax_anim_terminator
.align 2
sMetangAnims_12_1:
ax_anim 2, 0, 202, 1, 0, 1, 0,
ax_anim 2, 0, 202, 0, 0, 0, 0,
ax_anim 2, 0, 202, 1, 0, 1, 0,
ax_anim 2, 0, 202, 0, 0, 0, 0,
ax_anim 2, 0, 202, 1, 0, 1, 0,
ax_anim 2, 2, 202, 0, 0, 0, 0,
ax_anim 2, 0, 202, 1, 0, 1, 0,
ax_anim 2, 0, 202, 0, 0, 0, 0,
ax_anim 2, 0, 202, 1, 0, 1, 0,
ax_anim 2, 1, 202, 0, 0, 0, 0,
ax_anim_terminator
sMetangAnims_12_2:
ax_anim 2, 0, 209, 1, -1, 1, -1,
ax_anim 2, 0, 209, 0, 0, 0, 0,
ax_anim 2, 0, 209, 1, -1, 1, -1,
ax_anim 2, 0, 209, 0, 0, 0, 0,
ax_anim 2, 0, 209, 1, -1, 1, -1,
ax_anim 2, 2, 209, 0, 0, 0, 0,
ax_anim 2, 0, 209, 1, -1, 1, -1,
ax_anim 2, 0, 209, 0, 0, 0, 0,
ax_anim 2, 0, 209, 1, -1, 1, -1,
ax_anim 2, 1, 209, 0, 0, 0, 0,
ax_anim_terminator
sMetangAnims_12_3:
ax_anim 2, 0, 208, 0, -1, 0, -1,
ax_anim 2, 0, 208, 0, 0, 0, 0,
ax_anim 2, 0, 208, 0, -1, 0, -1,
ax_anim 2, 0, 208, 0, 0, 0, 0,
ax_anim 2, 0, 208, 0, -1, 0, -1,
ax_anim 2, 2, 208, 0, 0, 0, 0,
ax_anim 2, 0, 208, 0, -1, 0, -1,
ax_anim 2, 0, 208, 0, 0, 0, 0,
ax_anim 2, 0, 208, 0, -1, 0, -1,
ax_anim 2, 1, 208, 0, 0, 0, 0,
ax_anim_terminator
sMetangAnims_12_4:
ax_anim 2, 0, 207, -1, -1, -1, -1,
ax_anim 2, 0, 207, 0, 0, 0, 0,
ax_anim 2, 0, 207, -1, -1, -1, -1,
ax_anim 2, 0, 207, 0, 0, 0, 0,
ax_anim 2, 0, 207, -1, -1, -1, -1,
ax_anim 2, 2, 207, 0, 0, 0, 0,
ax_anim 2, 0, 207, -1, -1, -1, -1,
ax_anim 2, 0, 207, 0, 0, 0, 0,
ax_anim 2, 0, 207, -1, -1, -1, -1,
ax_anim 2, 1, 207, 0, 0, 0, 0,
ax_anim_terminator
sMetangAnims_12_5:
ax_anim 2, 0, 206, 1, 0, 1, 0,
ax_anim 2, 0, 206, 0, 0, 0, 0,
ax_anim 2, 0, 206, 1, 0, 1, 0,
ax_anim 2, 0, 206, 0, 0, 0, 0,
ax_anim 2, 0, 206, 1, 0, 1, 0,
ax_anim 2, 2, 206, 0, 0, 0, 0,
ax_anim 2, 0, 206, 1, 0, 1, 0,
ax_anim 2, 0, 206, 0, 0, 0, 0,
ax_anim 2, 0, 206, 1, 0, 1, 0,
ax_anim 2, 1, 206, 0, 0, 0, 0,
ax_anim_terminator
sMetangAnims_12_6:
ax_anim 2, 0, 205, 1, -1, 1, -1,
ax_anim 2, 0, 205, 0, 0, 0, 0,
ax_anim 2, 0, 205, 1, -1, 1, -1,
ax_anim 2, 0, 205, 0, 0, 0, 0,
ax_anim 2, 0, 205, 1, -1, 1, -1,
ax_anim 2, 2, 205, 0, 0, 0, 0,
ax_anim 2, 0, 205, 1, -1, 1, -1,
ax_anim 2, 0, 205, 0, 0, 0, 0,
ax_anim 2, 0, 205, 1, -1, 1, -1,
ax_anim 2, 1, 205, 0, 0, 0, 0,
ax_anim_terminator
sMetangAnims_12_7:
ax_anim 2, 0, 204, 0, -1, 0, -1,
ax_anim 2, 0, 204, 0, 0, 0, 0,
ax_anim 2, 0, 204, 0, -1, 0, -1,
ax_anim 2, 0, 204, 0, 0, 0, 0,
ax_anim 2, 0, 204, 0, -1, 0, -1,
ax_anim 2, 2, 204, 0, 0, 0, 0,
ax_anim 2, 0, 204, 0, -1, 0, -1,
ax_anim 2, 0, 204, 0, 0, 0, 0,
ax_anim 2, 0, 204, 0, -1, 0, -1,
ax_anim 2, 1, 204, 0, 0, 0, 0,
ax_anim_terminator
sMetangAnims_12_8:
ax_anim 2, 0, 203, -1, -1, -1, -1,
ax_anim 2, 0, 203, 0, 0, 0, 0,
ax_anim 2, 0, 203, -1, -1, -1, -1,
ax_anim 2, 0, 203, 0, 0, 0, 0,
ax_anim 2, 0, 203, -1, -1, -1, -1,
ax_anim 2, 2, 203, 0, 0, 0, 0,
ax_anim 2, 0, 203, -1, -1, -1, -1,
ax_anim 2, 0, 203, 0, 0, 0, 0,
ax_anim 2, 0, 203, -1, -1, -1, -1,
ax_anim 2, 1, 203, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sMetangAnims_13_1:
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 2, 210, 0, 0, 0, 0,
ax_anim_terminator
sMetangAnims_13_2:
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 2, 217, 0, 0, 0, 0,
ax_anim_terminator
sMetangAnims_13_3:
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 2, 216, 0, 0, 0, 0,
ax_anim_terminator
sMetangAnims_13_4:
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 2, 2, 215, 0, 0, 0, 0,
ax_anim_terminator
sMetangAnims_13_5:
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 2, 2, 214, 0, 0, 0, 0,
ax_anim_terminator
sMetangAnims_13_6:
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 2, 2, 213, 0, 0, 0, 0,
ax_anim_terminator
sMetangAnims_13_7:
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 2, 2, 212, 0, 0, 0, 0,
ax_anim_terminator
sMetangAnims_13_8:
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 2, 2, 211, 0, 0, 0, 0,
ax_anim_terminator
sMetangGfx1:
.incbin "baserom.gba", 0x1572E74, 0x200
sMetangSprites1:
ax_sprite sMetangGfx1, 0x200
ax_sprite_terminator
sMetangGfx2:
.incbin "baserom.gba", 0x1573084, 0x200
sMetangSprites2:
ax_sprite sMetangGfx2, 0x200
ax_sprite_terminator
sMetangGfx3:
.incbin "baserom.gba", 0x1573294, 0x200
sMetangSprites3:
ax_sprite sMetangGfx3, 0x200
ax_sprite_terminator
sMetangGfx4:
.incbin "baserom.gba", 0x15734A4, 0x200
sMetangSprites4:
ax_sprite sMetangGfx4, 0x200
ax_sprite_terminator
sMetangGfx5:
.incbin "baserom.gba", 0x15736B4, 0x200
sMetangSprites5:
ax_sprite sMetangGfx5, 0x200
ax_sprite_terminator
sMetangGfx6:
.incbin "baserom.gba", 0x15738C4, 0x200
sMetangSprites6:
ax_sprite sMetangGfx6, 0x200
ax_sprite_terminator
sMetangGfx7:
.incbin "baserom.gba", 0x1573AD4, 0x200
sMetangSprites7:
ax_sprite sMetangGfx7, 0x200
ax_sprite_terminator
sMetangGfx8:
.incbin "baserom.gba", 0x1573CE4, 0x200
sMetangSprites8:
ax_sprite sMetangGfx8, 0x200
ax_sprite_terminator
sMetangGfx9:
.incbin "baserom.gba", 0x1573EF4, 0x200
sMetangSprites9:
ax_sprite sMetangGfx9, 0x200
ax_sprite_terminator
sMetangGfx10:
.incbin "baserom.gba", 0x1574104, 0x200
sMetangSprites10:
ax_sprite sMetangGfx10, 0x200
ax_sprite_terminator
sMetangGfx11:
.incbin "baserom.gba", 0x1574314, 0x200
sMetangSprites11:
ax_sprite sMetangGfx11, 0x200
ax_sprite_terminator
sMetangGfx12:
.incbin "baserom.gba", 0x1574524, 0x200
sMetangSprites12:
ax_sprite sMetangGfx12, 0x200
ax_sprite_terminator
sMetangGfx13:
.incbin "baserom.gba", 0x1574734, 0x200
sMetangSprites13:
ax_sprite sMetangGfx13, 0x200
ax_sprite_terminator
sMetangGfx14:
.incbin "baserom.gba", 0x1574944, 0x200
sMetangSprites14:
ax_sprite sMetangGfx14, 0x200
ax_sprite_terminator
sMetangGfx15:
.incbin "baserom.gba", 0x1574B54, 0x200
sMetangSprites15:
ax_sprite sMetangGfx15, 0x200
ax_sprite_terminator
sMetangGfx16:
.incbin "baserom.gba", 0x1574D64, 0x180
sMetangSprites16:
ax_sprite sMetangGfx16, 0x180
ax_sprite 0, 0x80
ax_sprite_terminator
sMetangGfx17:
.incbin "baserom.gba", 0x1574EFC, 0x60
sMetangGfx17_1:
.incbin "baserom.gba", 0x1574F5C, 0x100
sMetangGfx17_2:
.incbin "baserom.gba", 0x157505C, 0x20
sMetangSprites17:
ax_sprite sMetangGfx17, 0x60
ax_sprite 0, 0x20
ax_sprite sMetangGfx17_1, 0x100
ax_sprite 0, 0x40
ax_sprite sMetangGfx17_2, 0x20
ax_sprite 0, 0x20
ax_sprite_terminator
sMetangGfx18:
.incbin "baserom.gba", 0x15750B4, 0x40
sMetangGfx18_1:
.incbin "baserom.gba", 0x15750F4, 0x100
sMetangGfx18_2:
.incbin "baserom.gba", 0x15751F4, 0x60
sMetangSprites18:
ax_sprite 0, 0x20
ax_sprite sMetangGfx18, 0x40
ax_sprite 0, 0x20
ax_sprite sMetangGfx18_1, 0x100
ax_sprite 0, 0x20
ax_sprite sMetangGfx18_2, 0x60
ax_sprite_terminator
sMetangGfx19:
.incbin "baserom.gba", 0x157528C, 0x1C0
sMetangSprites19:
ax_sprite sMetangGfx19, 0x1c0
ax_sprite 0, 0x40
ax_sprite_terminator
sMetangGfx20:
.incbin "baserom.gba", 0x1575464, 0x40
sMetangGfx20_1:
.incbin "baserom.gba", 0x15754A4, 0x180
sMetangSprites20:
ax_sprite 0, 0x20
ax_sprite sMetangGfx20, 0x40
ax_sprite 0, 0x20
ax_sprite sMetangGfx20_1, 0x180
ax_sprite_terminator
sMetangGfx21:
.incbin "baserom.gba", 0x157564C, 0x20
sMetangGfx21_1:
.incbin "baserom.gba", 0x157566C, 0x100
sMetangSprites21:
ax_sprite 0, 0x80
ax_sprite sMetangGfx21, 0x20
ax_sprite 0, 0x60
ax_sprite sMetangGfx21_1, 0x100
ax_sprite_terminator
sMetangGfx22:
.incbin "baserom.gba", 0x1575794, 0x40
sMetangGfx22_1:
.incbin "baserom.gba", 0x15757D4, 0x100
sMetangGfx22_2:
.incbin "baserom.gba", 0x15758D4, 0x60
sMetangSprites22:
ax_sprite 0, 0x20
ax_sprite sMetangGfx22, 0x40
ax_sprite 0, 0x20
ax_sprite sMetangGfx22_1, 0x100
ax_sprite 0, 0x20
ax_sprite sMetangGfx22_2, 0x60
ax_sprite_terminator
sMetangGfx23:
.incbin "baserom.gba", 0x157596C, 0x40
sMetangGfx23_1:
.incbin "baserom.gba", 0x15759AC, 0x160
sMetangSprites23:
ax_sprite 0, 0x20
ax_sprite sMetangGfx23, 0x40
ax_sprite 0, 0x20
ax_sprite sMetangGfx23_1, 0x160
ax_sprite 0, 0x20
ax_sprite_terminator
sMetangGfx24:
.incbin "baserom.gba", 0x1575B3C, 0x20
sMetangGfx24_1:
.incbin "baserom.gba", 0x1575B5C, 0x20
sMetangGfx24_2:
.incbin "baserom.gba", 0x1575B7C, 0x80
sMetangSprites24:
ax_sprite sMetangGfx24, 0x20
ax_sprite 0, 0x20
ax_sprite sMetangGfx24_1, 0x20
ax_sprite 0, 0x20
ax_sprite sMetangGfx24_2, 0x80
ax_sprite_terminator
sMetangGfx25:
.incbin "baserom.gba", 0x1575C2C, 0x60
sMetangGfx25_1:
.incbin "baserom.gba", 0x1575C8C, 0x140
sMetangSprites25:
ax_sprite sMetangGfx25, 0x60
ax_sprite 0, 0x20
ax_sprite sMetangGfx25_1, 0x140
ax_sprite 0, 0x40
ax_sprite_terminator
sMetangGfx26:
.incbin "baserom.gba", 0x1575DF4, 0x40
sMetangGfx26_1:
.incbin "baserom.gba", 0x1575E34, 0xA0
sMetangSprites26:
ax_sprite sMetangGfx26, 0x40
ax_sprite 0, 0x20
ax_sprite sMetangGfx26_1, 0xa0
ax_sprite_terminator
sMetangGfx27:
.incbin "baserom.gba", 0x1575EF4, 0x1C0
sMetangSprites27:
ax_sprite 0, 0x20
ax_sprite sMetangGfx27, 0x1c0
ax_sprite 0, 0x20
ax_sprite_terminator
sMetangGfx28:
.incbin "baserom.gba", 0x15760D4, 0x60
sMetangGfx28_1:
.incbin "baserom.gba", 0x1576134, 0x40
sMetangGfx28_2:
.incbin "baserom.gba", 0x1576174, 0x40
sMetangGfx28_3:
.incbin "baserom.gba", 0x15761B4, 0x40
sMetangSprites28:
ax_sprite sMetangGfx28, 0x60
ax_sprite 0, 0x20
ax_sprite sMetangGfx28_1, 0x40
ax_sprite 0, 0x40
ax_sprite sMetangGfx28_2, 0x40
ax_sprite 0, 0x40
ax_sprite sMetangGfx28_3, 0x40
ax_sprite 0, 0x40
ax_sprite_terminator
sMetangGfx29:
.incbin "baserom.gba", 0x157623C, 0xE0
sMetangSprites29:
ax_sprite 0, 0x20
ax_sprite sMetangGfx29, 0xe0
ax_sprite_terminator
sMetangGfx30:
.incbin "baserom.gba", 0x1576334, 0x80
sMetangSprites30:
ax_sprite sMetangGfx30, 0x80
ax_sprite_terminator
sMetangGfx31:
.incbin "baserom.gba", 0x15763C4, 0x20
sMetangSprites31:
ax_sprite sMetangGfx31, 0x20
ax_sprite_terminator
sMetangGfx32:
.incbin "baserom.gba", 0x15763F4, 0x20
sMetangSprites32:
ax_sprite sMetangGfx32, 0x20
ax_sprite_terminator
sMetangGfx33:
.incbin "baserom.gba", 0x1576424, 0x40
sMetangGfx33_1:
.incbin "baserom.gba", 0x1576464, 0x40
sMetangGfx33_2:
.incbin "baserom.gba", 0x15764A4, 0x60
sMetangSprites33:
ax_sprite sMetangGfx33, 0x40
ax_sprite 0, 0x40
ax_sprite sMetangGfx33_1, 0x40
ax_sprite 0, 0x40
ax_sprite sMetangGfx33_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sMetangGfx34:
.incbin "baserom.gba", 0x157653C, 0x100
sMetangSprites34:
ax_sprite sMetangGfx34, 0x100
ax_sprite_terminator
sMetangGfx35:
.incbin "baserom.gba", 0x157664C, 0x80
sMetangSprites35:
ax_sprite sMetangGfx35, 0x80
ax_sprite_terminator
sMetangGfx36:
.incbin "baserom.gba", 0x15766DC, 0x20
sMetangSprites36:
ax_sprite sMetangGfx36, 0x20
ax_sprite_terminator
sMetangGfx37:
.incbin "baserom.gba", 0x157670C, 0x20
sMetangSprites37:
ax_sprite sMetangGfx37, 0x20
ax_sprite_terminator
sMetangGfx38:
.incbin "baserom.gba", 0x157673C, 0xC0
sMetangSprites38:
ax_sprite sMetangGfx38, 0xc0
ax_sprite 0, 0x40
ax_sprite_terminator
sMetangGfx39:
.incbin "baserom.gba", 0x1576814, 0x100
sMetangGfx39_1:
.incbin "baserom.gba", 0x1576914, 0x60
sMetangGfx39_2:
.incbin "baserom.gba", 0x1576974, 0x40
sMetangSprites39:
ax_sprite sMetangGfx39, 0x100
ax_sprite 0, 0x20
ax_sprite sMetangGfx39_1, 0x60
ax_sprite 0, 0x40
ax_sprite sMetangGfx39_2, 0x40
ax_sprite_terminator
sMetangGfx40:
.incbin "baserom.gba", 0x15769E4, 0xC0
sMetangGfx40_1:
.incbin "baserom.gba", 0x1576AA4, 0x20
sMetangSprites40:
ax_sprite sMetangGfx40, 0xc0
ax_sprite 0, 0x20
ax_sprite sMetangGfx40_1, 0x20
ax_sprite_terminator
sMetangGfx41:
.incbin "baserom.gba", 0x1576AE4, 0x60
sMetangGfx41_1:
.incbin "baserom.gba", 0x1576B44, 0x100
sMetangGfx41_2:
.incbin "baserom.gba", 0x1576C44, 0x20
sMetangSprites41:
ax_sprite sMetangGfx41, 0x60
ax_sprite 0, 0x20
ax_sprite sMetangGfx41_1, 0x100
ax_sprite 0, 0x40
ax_sprite sMetangGfx41_2, 0x20
ax_sprite 0, 0x20
ax_sprite_terminator
sMetangGfx42:
.incbin "baserom.gba", 0x1576C9C, 0x60
sMetangGfx42_1:
.incbin "baserom.gba", 0x1576CFC, 0x80
sMetangGfx42_2:
.incbin "baserom.gba", 0x1576D7C, 0x20
sMetangSprites42:
ax_sprite sMetangGfx42, 0x60
ax_sprite 0, 0x20
ax_sprite sMetangGfx42_1, 0x80
ax_sprite 0, 0x60
ax_sprite sMetangGfx42_2, 0x20
ax_sprite 0, 0x80
ax_sprite_terminator
sMetangGfx43:
.incbin "baserom.gba", 0x1576DD4, 0x60
sMetangGfx43_1:
.incbin "baserom.gba", 0x1576E34, 0x160
sMetangSprites43:
ax_sprite sMetangGfx43, 0x60
ax_sprite 0, 0x20
ax_sprite sMetangGfx43_1, 0x160
ax_sprite 0, 0x20
ax_sprite_terminator
sMetangGfx44:
.incbin "baserom.gba", 0x1576FBC, 0x160
sMetangGfx44_1:
.incbin "baserom.gba", 0x157711C, 0x60
sMetangSprites44:
ax_sprite 0, 0x20
ax_sprite sMetangGfx44, 0x160
ax_sprite 0, 0x20
ax_sprite sMetangGfx44_1, 0x60
ax_sprite_terminator
sMetangGfx45:
.incbin "baserom.gba", 0x15771A4, 0x180
sMetangSprites45:
ax_sprite sMetangGfx45, 0x180
ax_sprite 0, 0x80
ax_sprite_terminator
sMetangGfx46:
.incbin "baserom.gba", 0x157733C, 0x60
sMetangGfx46_1:
.incbin "baserom.gba", 0x157739C, 0x100
sMetangGfx46_2:
.incbin "baserom.gba", 0x157749C, 0x20
sMetangSprites46:
ax_sprite sMetangGfx46, 0x60
ax_sprite 0, 0x20
ax_sprite sMetangGfx46_1, 0x100
ax_sprite 0, 0x40
ax_sprite sMetangGfx46_2, 0x20
ax_sprite 0, 0x20
ax_sprite_terminator
sMetangGfx47:
.incbin "baserom.gba", 0x15774F4, 0x60
sMetangGfx47_1:
.incbin "baserom.gba", 0x1577554, 0x120
sMetangSprites47:
ax_sprite sMetangGfx47, 0x60
ax_sprite 0, 0x20
ax_sprite sMetangGfx47_1, 0x120
ax_sprite 0, 0x60
ax_sprite_terminator
sMetangGfx48:
.incbin "baserom.gba", 0x157769C, 0x180
sMetangGfx48_1:
.incbin "baserom.gba", 0x157781C, 0x40
sMetangSprites48:
ax_sprite sMetangGfx48, 0x180
ax_sprite 0, 0x20
ax_sprite sMetangGfx48_1, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sMetangGfx49:
.incbin "baserom.gba", 0x1577884, 0x180
sMetangSprites49:
ax_sprite sMetangGfx49, 0x180
ax_sprite 0, 0x80
ax_sprite_terminator
sMetangGfx50:
.incbin "baserom.gba", 0x1577A1C, 0x200
sMetangSprites50:
ax_sprite sMetangGfx50, 0x200
ax_sprite_terminator
sMetangGfx51:
.incbin "baserom.gba", 0x1577C2C, 0x200
sMetangSprites51:
ax_sprite sMetangGfx51, 0x200
ax_sprite_terminator
sMetangGfx52:
.incbin "baserom.gba", 0x1577E3C, 0x200
sMetangSprites52:
ax_sprite sMetangGfx52, 0x200
ax_sprite_terminator
sMetangGfx53:
.incbin "baserom.gba", 0x157804C, 0x200
sMetangSprites53:
ax_sprite sMetangGfx53, 0x200
ax_sprite_terminator
sMetangGfx54:
.incbin "baserom.gba", 0x157825C, 0x200
sMetangSprites54:
ax_sprite sMetangGfx54, 0x200
ax_sprite_terminator
sMetangGfx55:
.incbin "baserom.gba", 0x157846C, 0x100
sMetangSprites55:
ax_sprite sMetangGfx55, 0x100
ax_sprite_terminator
sMetangGfx56:
.incbin "baserom.gba", 0x157857C, 0x40
sMetangSprites56:
ax_sprite sMetangGfx56, 0x40
ax_sprite_terminator
sMetangGfx57:
.incbin "baserom.gba", 0x15785CC, 0x20
sMetangSprites57:
ax_sprite sMetangGfx57, 0x20
ax_sprite_terminator
sMetangGfx58:
.incbin "baserom.gba", 0x15785FC, 0x20
sMetangSprites58:
ax_sprite sMetangGfx58, 0x20
ax_sprite_terminator
sMetangGfx59:
.incbin "baserom.gba", 0x157862C, 0x20
sMetangSprites59:
ax_sprite sMetangGfx59, 0x20
ax_sprite_terminator
sMetangGfx60:
.incbin "baserom.gba", 0x157865C, 0x20
sMetangSprites60:
ax_sprite sMetangGfx60, 0x20
ax_sprite_terminator
sMetangGfx61:
.incbin "baserom.gba", 0x157868C, 0x40
sMetangSprites61:
ax_sprite sMetangGfx61, 0x40
ax_sprite_terminator
sMetangGfx62:
.incbin "baserom.gba", 0x15786DC, 0x200
sMetangSprites62:
ax_sprite sMetangGfx62, 0x200
ax_sprite_terminator
sAxPosesMetang:
.4byte sMetangPose1
.4byte sMetangPose2
.4byte sMetangPose3
.4byte sMetangPose4
.4byte sMetangPose5
.4byte sMetangPose6
.4byte sMetangPose7
.4byte sMetangPose8
.4byte sMetangPose9
.4byte sMetangPose10
.4byte sMetangPose11
.4byte sMetangPose12
.4byte sMetangPose13
.4byte sMetangPose14
.4byte sMetangPose15
.4byte sMetangPose16
.4byte sMetangPose17
.4byte sMetangPose18
.4byte sMetangPose19
.4byte sMetangPose20
.4byte sMetangPose21
.4byte sMetangPose22
.4byte sMetangPose23
.4byte sMetangPose24
.4byte sMetangPose25
.4byte sMetangPose26
.4byte sMetangPose27
.4byte sMetangPose28
.4byte sMetangPose29
.4byte sMetangPose30
.4byte sMetangPose31
.4byte sMetangPose32
.4byte sMetangPose33
.4byte sMetangPose34
.4byte sMetangPose35
.4byte sMetangPose36
.4byte sMetangPose37
.4byte sMetangPose38
.4byte sMetangPose39
.4byte sMetangPose40
.4byte sMetangPose41
.4byte sMetangPose42
.4byte sMetangPose43
.4byte sMetangPose44
.4byte sMetangPose45
.4byte sMetangPose46
.4byte sMetangPose47
.4byte sMetangPose48
.4byte sMetangPose49
.4byte sMetangPose50
.4byte sMetangPose51
.4byte sMetangPose52
.4byte sMetangPose53
.4byte sMetangPose54
.4byte sMetangPose55
.4byte sMetangPose56
.4byte sMetangPose57
.4byte sMetangPose58
.4byte sMetangPose59
.4byte sMetangPose60
.4byte sMetangPose61
.4byte sMetangPose62
.4byte sMetangPose63
.4byte sMetangPose64
.4byte sMetangPose65
.4byte sMetangPose66
.4byte sMetangPose67
.4byte sMetangPose68
.4byte sMetangPose69
.4byte sMetangPose70
.4byte sMetangPose71
.4byte sMetangPose72
.4byte sMetangPose73
.4byte sMetangPose74
.4byte sMetangPose75
.4byte sMetangPose76
.4byte sMetangPose77
.4byte sMetangPose78
.4byte sMetangPose79
.4byte sMetangPose80
.4byte sMetangPose81
.4byte sMetangPose82
.4byte sMetangPose83
.4byte sMetangPose84
.4byte sMetangPose85
.4byte sMetangPose86
.4byte sMetangPose87
.4byte sMetangPose88
.4byte sMetangPose89
.4byte sMetangPose90
.4byte sMetangPose91
.4byte sMetangPose92
.4byte sMetangPose93
.4byte sMetangPose94
.4byte sMetangPose95
.4byte sMetangPose96
.4byte sMetangPose97
.4byte sMetangPose98
.4byte sMetangPose99
.4byte sMetangPose100
.4byte sMetangPose101
.4byte sMetangPose102
.4byte sMetangPose103
.4byte sMetangPose104
.4byte sMetangPose105
.4byte sMetangPose106
.4byte sMetangPose107
.4byte sMetangPose108
.4byte sMetangPose109
.4byte sMetangPose110
.4byte sMetangPose111
.4byte sMetangPose112
.4byte sMetangPose113
.4byte sMetangPose114
.4byte sMetangPose115
.4byte sMetangPose116
.4byte sMetangPose117
.4byte sMetangPose118
.4byte sMetangPose119
.4byte sMetangPose120
.4byte sMetangPose121
.4byte sMetangPose122
.4byte sMetangPose123
.4byte sMetangPose124
.4byte sMetangPose125
.4byte sMetangPose126
.4byte sMetangPose127
.4byte sMetangPose128
.4byte sMetangPose129
.4byte sMetangPose130
.4byte sMetangPose131
.4byte sMetangPose132
.4byte sMetangPose133
.4byte sMetangPose134
.4byte sMetangPose135
.4byte sMetangPose136
.4byte sMetangPose137
.4byte sMetangPose138
.4byte sMetangPose139
.4byte sMetangPose140
.4byte sMetangPose141
.4byte sMetangPose142
.4byte sMetangPose143
.4byte sMetangPose144
.4byte sMetangPose145
.4byte sMetangPose146
.4byte sMetangPose147
.4byte sMetangPose148
.4byte sMetangPose149
.4byte sMetangPose150
.4byte sMetangPose151
.4byte sMetangPose152
.4byte sMetangPose153
.4byte sMetangPose154
.4byte sMetangPose155
.4byte sMetangPose156
.4byte sMetangPose157
.4byte sMetangPose158
.4byte sMetangPose159
.4byte sMetangPose160
.4byte sMetangPose161
.4byte sMetangPose162
.4byte sMetangPose163
.4byte sMetangPose164
.4byte sMetangPose165
.4byte sMetangPose166
.4byte sMetangPose167
.4byte sMetangPose168
.4byte sMetangPose169
.4byte sMetangPose170
.4byte sMetangPose171
.4byte sMetangPose172
.4byte sMetangPose173
.4byte sMetangPose174
.4byte sMetangPose175
.4byte sMetangPose176
.4byte sMetangPose177
.4byte sMetangPose178
.4byte sMetangPose179
.4byte sMetangPose180
.4byte sMetangPose181
.4byte sMetangPose182
.4byte sMetangPose183
.4byte sMetangPose184
.4byte sMetangPose185
.4byte sMetangPose186
.4byte sMetangPose187
.4byte sMetangPose188
.4byte sMetangPose189
.4byte sMetangPose190
.4byte sMetangPose191
.4byte sMetangPose192
.4byte sMetangPose193
.4byte sMetangPose194
.4byte sMetangPose195
.4byte sMetangPose196
.4byte sMetangPose197
.4byte sMetangPose198
.4byte sMetangPose199
.4byte sMetangPose200
.4byte sMetangPose201
.4byte sMetangPose202
.4byte sMetangPose203
.4byte sMetangPose204
.4byte sMetangPose205
.4byte sMetangPose206
.4byte sMetangPose207
.4byte sMetangPose208
.4byte sMetangPose209
.4byte sMetangPose210
.4byte sMetangPose211
.4byte sMetangPose212
.4byte sMetangPose213
.4byte sMetangPose214
.4byte sMetangPose215
.4byte sMetangPose216
.4byte sMetangPose217
.4byte sMetangPose218
sAxPositionsMetang:
.2byte   -1,  -11, 	 -11,   -2, 	   9,   -2, 	  -1,  -16
.2byte   -1,  -11, 	 -12,   -4, 	   9,   -4, 	  -1,  -16
.2byte   -1,  -11, 	 -11,    0, 	   9,    0, 	  -1,  -16
.2byte    5,  -11, 	  15,  -10, 	  -3,   -1, 	   0,  -15
.2byte    5,  -11, 	  14,  -13, 	  -1,   -4, 	  -1,  -16
.2byte    5,  -11, 	  13,   -6, 	  -5,    2, 	   0,  -15
.2byte    8,  -16, 	   9,  -19, 	   9,   -4, 	  -1,  -16
.2byte    8,  -16, 	   8,  -22, 	   9,   -9, 	  -1,  -16
.2byte    8,  -16, 	   9,  -14, 	   6,   -1, 	  -2,  -16
.2byte    4,  -20, 	  -4,  -22, 	  14,  -12, 	  -1,  -17
.2byte    4,  -20, 	  -5,  -23, 	  15,  -16, 	  -1,  -17
.2byte    4,  -20, 	  -5,  -17, 	  13,   -8, 	  -1,  -16
.2byte   -1,  -20, 	  10,  -20, 	 -12,  -20, 	  -1,  -17
.2byte   -1,  -20, 	  11,  -21, 	 -12,  -21, 	  -1,  -17
.2byte   -1,  -20, 	  11,  -14, 	 -13,  -14, 	  -1,  -17
.2byte   -6,  -20, 	   2,  -22, 	 -16,  -12, 	  -1,  -17
.2byte   -6,  -20, 	   3,  -23, 	 -17,  -16, 	  -1,  -17
.2byte   -6,  -20, 	   3,  -17, 	 -15,   -8, 	  -1,  -16
.2byte  -10,  -16, 	 -11,  -19, 	 -11,   -4, 	  -1,  -16
.2byte  -10,  -16, 	 -10,  -22, 	 -11,   -9, 	  -1,  -16
.2byte  -10,  -16, 	 -11,  -14, 	  -8,   -1, 	   0,  -16
.2byte   -7,  -11, 	 -17,  -10, 	   1,   -1, 	  -2,  -15
.2byte   -7,  -11, 	 -16,  -13, 	  -1,   -4, 	  -1,  -16
.2byte   -7,  -11, 	 -15,   -6, 	   3,    2, 	  -2,  -15
.2byte   -1,  -11, 	 -11,   -2, 	   9,   -2, 	  -1,  -16
.2byte   -1,  -11, 	 -12,   -4, 	   9,   -4, 	  -1,  -16
.2byte   -1,  -11, 	 -12,  -19, 	  10,  -19, 	  -1,  -15
.2byte    5,  -11, 	  15,  -10, 	  -3,   -1, 	   0,  -15
.2byte    5,  -11, 	  14,  -13, 	  -1,   -4, 	  -1,  -16
.2byte    5,  -11, 	   6,  -20, 	 -16,  -14, 	  -1,  -17
.2byte    8,  -16, 	   9,  -19, 	   9,   -4, 	  -1,  -16
.2byte    8,  -16, 	   8,  -22, 	   9,   -9, 	  -1,  -16
.2byte    7,  -16, 	 -11,  -18, 	 -12,   -3, 	  -3,  -17
.2byte    4,  -20, 	  -4,  -22, 	  14,  -12, 	  -1,  -17
.2byte    4,  -20, 	  -5,  -23, 	  15,  -16, 	  -1,  -17
.2byte    4,  -20, 	 -15,  -12, 	   2,    1, 	  -1,  -17
.2byte   -1,  -20, 	  10,  -20, 	 -12,  -20, 	  -1,  -17
.2byte   -1,  -20, 	  11,  -21, 	 -12,  -21, 	  -1,  -17
.2byte   -1,  -20, 	  10,   -4, 	 -11,   -4, 	  -1,  -16
.2byte   -6,  -20, 	   2,  -22, 	 -16,  -12, 	  -1,  -17
.2byte   -6,  -20, 	   3,  -23, 	 -17,  -16, 	  -1,  -17
.2byte   -6,  -20, 	  13,  -12, 	  -4,    1, 	  -1,  -17
.2byte  -10,  -16, 	 -11,  -19, 	 -11,   -4, 	  -1,  -16
.2byte  -10,  -16, 	 -10,  -22, 	 -11,   -9, 	  -1,  -16
.2byte   -9,  -16, 	   9,  -18, 	  10,   -3, 	   1,  -17
.2byte   -7,  -11, 	 -17,  -10, 	   1,   -1, 	  -2,  -15
.2byte   -7,  -11, 	 -16,  -13, 	  -1,   -4, 	  -1,  -16
.2byte   -7,  -11, 	  -8,  -20, 	  14,  -14, 	  -1,  -17
.2byte   -1,  -11, 	 -11,   -2, 	   9,   -2, 	  -1,  -16
.2byte    5,  -11, 	   8,   -1, 	  12,  -17, 	   0,  -17
.2byte    5,  -11, 	   8,   -1, 	  12,  -17, 	   0,  -17
.2byte   -6,  -11, 	 -12,  -16, 	  -8,   -1, 	   0,  -17
.2byte   -6,  -11, 	 -12,  -16, 	  -8,   -1, 	   0,  -17
.2byte    5,  -11, 	  15,  -10, 	  -3,   -1, 	   0,  -15
.2byte    1,  -10, 	   8,    1, 	 -14,  -13, 	   1,  -16
.2byte    1,  -10, 	   8,    1, 	 -14,  -13, 	   1,  -16
.2byte   11,  -15, 	   7,  -22, 	  16,   -7, 	   1,  -16
.2byte   11,  -15, 	   7,  -22, 	  16,   -7, 	   1,  -16
.2byte    8,  -16, 	   9,  -19, 	   9,   -4, 	  -1,  -16
.2byte    7,  -12, 	  15,   -7, 	 -10,   -6, 	  -1,  -17
.2byte    7,  -12, 	  15,   -7, 	 -10,   -6, 	  -1,  -17
.2byte    7,  -19, 	 -10,  -22, 	  15,  -19, 	   0,  -17
.2byte    7,  -19, 	 -10,  -22, 	  15,  -19, 	   0,  -17
.2byte    4,  -20, 	  -4,  -22, 	  14,  -12, 	  -1,  -17
.2byte    7,  -15, 	  15,  -17, 	  -3,   -3, 	  -2,  -17
.2byte    7,  -15, 	  15,  -17, 	  -3,   -3, 	  -2,  -17
.2byte   -1,  -20, 	 -14,  -14, 	   8,  -26, 	  -1,  -16
.2byte   -1,  -20, 	 -14,  -14, 	   8,  -26, 	  -1,  -16
.2byte    0,  -20, 	 -11,  -20, 	  11,  -20, 	   0,  -17
.2byte   -8,  -16, 	 -12,  -22, 	  -8,   -6, 	   0,  -16
.2byte   -8,  -16, 	 -12,  -22, 	  -8,   -6, 	   0,  -16
.2byte    7,  -16, 	   8,   -5, 	  11,  -22, 	  -2,  -16
.2byte    7,  -16, 	   8,   -5, 	  11,  -22, 	  -2,  -16
.2byte   -6,  -20, 	   2,  -22, 	 -16,  -12, 	  -1,  -17
.2byte  -10,  -15, 	 -18,  -17, 	   0,   -3, 	  -1,  -17
.2byte  -10,  -15, 	 -18,  -17, 	   0,   -3, 	  -1,  -17
.2byte   -2,  -20, 	  11,  -14, 	 -11,  -26, 	  -2,  -16
.2byte   -2,  -20, 	  11,  -14, 	 -11,  -26, 	  -2,  -16
.2byte  -10,  -16, 	 -11,  -19, 	 -11,   -4, 	  -1,  -16
.2byte   -8,  -12, 	 -16,   -7, 	   9,   -6, 	   0,  -17
.2byte   -8,  -12, 	 -16,   -7, 	   9,   -6, 	   0,  -17
.2byte   -8,  -19, 	   9,  -22, 	 -16,  -19, 	  -1,  -17
.2byte   -8,  -19, 	   9,  -22, 	 -16,  -19, 	  -1,  -17
.2byte   -7,  -11, 	 -17,  -10, 	   1,   -1, 	  -2,  -15
.2byte   -3,  -10, 	 -10,    1, 	  12,  -13, 	  -3,  -16
.2byte   -3,  -10, 	 -10,    1, 	  12,  -13, 	  -3,  -16
.2byte  -10,  -15, 	  -6,  -22, 	 -15,   -7, 	   0,  -16
.2byte  -10,  -15, 	  -6,  -22, 	 -15,   -7, 	   0,  -16
.2byte   -1,  -11, 	 -11,   -2, 	   9,   -2, 	  -1,  -16
.2byte   -1,  -17, 	 -10,  -19, 	   8,  -19, 	  -1,  -15
.2byte   -1,  -11, 	 -12,  -19, 	  10,  -19, 	  -1,  -15
.2byte   -1,  -11, 	 -12,   -4, 	   9,   -4, 	  -1,  -16
.2byte    5,  -11, 	  15,  -10, 	  -3,   -1, 	   0,  -15
.2byte    3,  -19, 	   9,  -22, 	   0,  -16, 	  -3,  -14
.2byte    5,  -11, 	   6,  -20, 	 -16,  -14, 	  -1,  -17
.2byte    5,  -11, 	  14,  -13, 	  -1,   -4, 	  -1,  -16
.2byte    8,  -16, 	   9,  -19, 	   9,   -4, 	  -1,  -16
.2byte    5,  -18, 	   7,  -25, 	   8,  -18, 	  -2,  -17
.2byte    9,  -16, 	  -9,  -18, 	 -10,   -3, 	  -1,  -17
.2byte    8,  -16, 	   8,  -22, 	   9,   -9, 	  -1,  -16
.2byte    4,  -20, 	  -4,  -22, 	  14,  -12, 	  -1,  -17
.2byte    2,  -21, 	  -1,  -26, 	  10,  -23, 	  -2,  -17
.2byte    4,  -20, 	 -15,  -12, 	   2,    1, 	  -1,  -17
.2byte    4,  -19, 	  -5,  -22, 	  15,  -15, 	  -1,  -16
.2byte   -1,  -20, 	  10,  -20, 	 -12,  -20, 	  -1,  -17
.2byte   -1,  -21, 	   8,  -23, 	  -9,  -23, 	  -1,  -17
.2byte   -1,  -20, 	  10,   -4, 	 -11,   -4, 	  -1,  -16
.2byte   -1,  -20, 	  11,  -21, 	 -12,  -21, 	  -1,  -17
.2byte   -6,  -20, 	   2,  -22, 	 -16,  -12, 	  -1,  -17
.2byte   -5,  -21, 	  -2,  -26, 	 -13,  -23, 	  -1,  -17
.2byte   -6,  -20, 	  13,  -12, 	  -4,    1, 	  -1,  -17
.2byte   -6,  -19, 	   3,  -22, 	 -17,  -15, 	  -1,  -16
.2byte  -10,  -16, 	 -11,  -19, 	 -11,   -4, 	  -1,  -16
.2byte   -7,  -18, 	  -9,  -25, 	 -10,  -18, 	   0,  -17
.2byte  -11,  -16, 	   7,  -18, 	   8,   -3, 	  -1,  -17
.2byte  -10,  -16, 	 -10,  -22, 	 -11,   -9, 	  -1,  -16
.2byte   -7,  -11, 	 -17,  -10, 	   1,   -1, 	  -2,  -15
.2byte   -7,  -19, 	 -13,  -22, 	  -4,  -16, 	  -1,  -14
.2byte   -7,  -11, 	  -8,  -20, 	  14,  -14, 	  -1,  -17
.2byte   -7,  -11, 	 -16,  -13, 	  -1,   -4, 	  -1,  -16
.2byte   -1,  -11, 	 -11,   -2, 	   9,   -2, 	  -1,  -16
.2byte   -7,  -11, 	 -17,  -10, 	   1,   -1, 	  -2,  -15
.2byte  -10,  -16, 	 -11,  -19, 	 -11,   -4, 	  -1,  -16
.2byte   -6,  -20, 	   2,  -22, 	 -16,  -12, 	  -1,  -17
.2byte   -1,  -20, 	  10,  -20, 	 -12,  -20, 	  -1,  -17
.2byte    4,  -20, 	  -4,  -22, 	  14,  -12, 	  -1,  -17
.2byte    8,  -16, 	   9,  -19, 	   9,   -4, 	  -1,  -16
.2byte    5,  -11, 	  15,  -10, 	  -3,   -1, 	   0,  -15
.2byte   -4,   -9, 	 -14,   -6, 	   4,    3, 	   2,  -15
.2byte   -4,   -9, 	 -13,   -8, 	   4,    2, 	   1,  -16
.2byte    0,  -17, 	 -10,  -27, 	  10,  -27, 	   0,  -13
.2byte    6,  -15, 	   4,  -29, 	 -10,  -19, 	   0,  -14
.2byte    8,  -18, 	  -7,  -27, 	 -11,  -22, 	   0,  -15
.2byte    2,  -19, 	 -10,  -27, 	  13,  -22, 	  -2,  -13
.2byte    0,  -20, 	  10,  -27, 	 -10,  -26, 	   0,  -14
.2byte   -2,  -19, 	  10,  -27, 	 -13,  -22, 	   2,  -13
.2byte   -9,  -18, 	   6,  -27, 	  10,  -22, 	  -1,  -15
.2byte   -6,  -16, 	  -4,  -30, 	  10,  -20, 	   0,  -15
.2byte   -1,  -11, 	 -11,   -2, 	   9,   -2, 	  -1,  -16
.2byte   -1,  -11, 	 -12,   -4, 	   9,   -4, 	  -1,  -16
.2byte   -1,  -11, 	 -11,    0, 	   9,    0, 	  -1,  -16
.2byte    5,  -11, 	  15,  -10, 	  -3,   -1, 	   0,  -15
.2byte    5,  -11, 	  14,  -13, 	  -1,   -4, 	  -1,  -16
.2byte    5,  -11, 	  13,   -6, 	  -5,    2, 	   0,  -15
.2byte    8,  -16, 	   9,  -19, 	   9,   -4, 	  -1,  -16
.2byte    8,  -16, 	   8,  -22, 	   9,   -9, 	  -1,  -16
.2byte    8,  -16, 	   9,  -14, 	   6,   -1, 	  -2,  -16
.2byte    4,  -20, 	  -4,  -22, 	  14,  -12, 	  -1,  -17
.2byte    4,  -20, 	  -5,  -23, 	  15,  -16, 	  -1,  -17
.2byte    4,  -20, 	  -5,  -17, 	  13,   -8, 	  -1,  -16
.2byte   -1,  -20, 	  10,  -20, 	 -12,  -20, 	  -1,  -17
.2byte   -1,  -20, 	  11,  -21, 	 -12,  -21, 	  -1,  -17
.2byte   -1,  -20, 	  11,  -14, 	 -13,  -14, 	  -1,  -17
.2byte   -6,  -20, 	   2,  -22, 	 -16,  -12, 	  -1,  -17
.2byte   -6,  -20, 	   3,  -23, 	 -17,  -16, 	  -1,  -17
.2byte   -6,  -20, 	   3,  -17, 	 -15,   -8, 	  -1,  -16
.2byte  -10,  -16, 	 -11,  -19, 	 -11,   -4, 	  -1,  -16
.2byte  -10,  -16, 	 -10,  -22, 	 -11,   -9, 	  -1,  -16
.2byte  -10,  -16, 	 -11,  -14, 	  -8,   -1, 	   0,  -16
.2byte   -7,  -11, 	 -17,  -10, 	   1,   -1, 	  -2,  -15
.2byte   -7,  -11, 	 -16,  -13, 	  -1,   -4, 	  -1,  -16
.2byte   -7,  -11, 	 -15,   -6, 	   3,    2, 	  -2,  -15
.2byte   -1,  -11, 	 -12,  -19, 	  10,  -19, 	  -1,  -15
.2byte   -7,  -11, 	  -8,  -20, 	  14,  -14, 	  -1,  -17
.2byte   -9,  -16, 	   9,  -18, 	  10,   -3, 	   1,  -17
.2byte   -6,  -20, 	  13,  -12, 	  -4,    1, 	  -1,  -17
.2byte   -1,  -20, 	  10,   -4, 	 -11,   -4, 	  -1,  -16
.2byte    4,  -20, 	 -15,  -12, 	   2,    1, 	  -1,  -17
.2byte    7,  -16, 	 -11,  -18, 	 -12,   -3, 	  -3,  -17
.2byte    5,  -11, 	   6,  -20, 	 -16,  -14, 	  -1,  -17
.2byte   -1,  -16, 	 -10,  -18, 	   8,  -18, 	  -1,  -14
.2byte    5,  -19, 	  11,  -22, 	   2,  -16, 	  -1,  -14
.2byte    6,  -18, 	   8,  -25, 	   9,  -18, 	  -1,  -17
.2byte    3,  -21, 	   0,  -26, 	  11,  -23, 	  -1,  -17
.2byte   -1,  -21, 	   8,  -23, 	  -9,  -23, 	  -1,  -17
.2byte   -4,  -21, 	  -1,  -26, 	 -12,  -23, 	   0,  -17
.2byte   -7,  -18, 	  -9,  -25, 	 -10,  -18, 	   0,  -17
.2byte   -6,  -19, 	 -12,  -22, 	  -3,  -16, 	   0,  -14
.2byte   -1,  -11, 	 -11,   -2, 	   9,   -2, 	  -1,  -16
.2byte   -1,  -11, 	 -11,    0, 	   9,    0, 	  -1,  -16
.2byte   -1,  -17, 	 -10,  -19, 	   8,  -19, 	  -1,  -15
.2byte    5,  -11, 	  15,  -10, 	  -3,   -1, 	   0,  -15
.2byte    5,  -11, 	  13,   -6, 	  -5,    2, 	   0,  -15
.2byte    3,  -19, 	   9,  -22, 	   0,  -16, 	  -3,  -14
.2byte    8,  -16, 	   9,  -19, 	   9,   -4, 	  -1,  -16
.2byte    8,  -16, 	   9,  -14, 	   6,   -1, 	  -2,  -16
.2byte    5,  -18, 	   7,  -25, 	   8,  -18, 	  -2,  -17
.2byte    4,  -20, 	  -4,  -22, 	  14,  -12, 	  -1,  -17
.2byte    4,  -20, 	  -5,  -17, 	  13,   -8, 	  -1,  -16
.2byte    2,  -21, 	  -1,  -26, 	  10,  -23, 	  -2,  -17
.2byte   -1,  -20, 	  10,  -20, 	 -12,  -20, 	  -1,  -17
.2byte   -1,  -20, 	  11,  -14, 	 -13,  -14, 	  -1,  -17
.2byte   -1,  -21, 	   8,  -23, 	  -9,  -23, 	  -1,  -17
.2byte   -6,  -20, 	   2,  -22, 	 -16,  -12, 	  -1,  -17
.2byte   -6,  -20, 	   3,  -17, 	 -15,   -8, 	  -1,  -16
.2byte   -5,  -21, 	  -2,  -26, 	 -13,  -23, 	  -1,  -17
.2byte  -10,  -16, 	 -11,  -19, 	 -11,   -4, 	  -1,  -16
.2byte  -10,  -16, 	 -11,  -14, 	  -8,   -1, 	   0,  -16
.2byte   -7,  -18, 	  -9,  -25, 	 -10,  -18, 	   0,  -17
.2byte   -7,  -11, 	 -17,  -10, 	   1,   -1, 	  -2,  -15
.2byte   -7,  -11, 	 -15,   -6, 	   3,    2, 	  -2,  -15
.2byte   -7,  -19, 	 -13,  -22, 	  -4,  -16, 	  -1,  -14
.2byte   -1,  -11, 	 -12,   -4, 	   9,   -4, 	  -1,  -16
.2byte   -6,  -11, 	 -15,  -13, 	   0,   -4, 	   0,  -16
.2byte  -10,  -16, 	 -10,  -22, 	 -11,   -9, 	  -1,  -16
.2byte   -6,  -20, 	   3,  -23, 	 -17,  -16, 	  -1,  -17
.2byte   -1,  -20, 	  11,  -21, 	 -12,  -21, 	  -1,  -17
.2byte    5,  -20, 	  -4,  -23, 	  16,  -16, 	   0,  -17
.2byte    9,  -16, 	   9,  -22, 	  10,   -9, 	   0,  -16
.2byte    5,  -11, 	  14,  -13, 	  -1,   -4, 	  -1,  -16
.2byte   -1,  -11, 	 -11,   -2, 	   9,   -2, 	  -1,  -16
.2byte   -7,  -11, 	 -17,  -10, 	   1,   -1, 	  -2,  -15
.2byte  -10,  -16, 	 -11,  -19, 	 -11,   -4, 	  -1,  -16
.2byte   -6,  -20, 	   2,  -22, 	 -16,  -12, 	  -1,  -17
.2byte   -1,  -20, 	  10,  -20, 	 -12,  -20, 	  -1,  -17
.2byte    4,  -20, 	  -4,  -22, 	  14,  -12, 	  -1,  -17
.2byte    8,  -16, 	   9,  -19, 	   9,   -4, 	  -1,  -16
.2byte    5,  -11, 	  15,  -10, 	  -3,   -1, 	   0,  -15
sMetangAnimTable1:
.4byte sMetangAnims_1_1
.4byte sMetangAnims_1_2
.4byte sMetangAnims_1_3
.4byte sMetangAnims_1_4
.4byte sMetangAnims_1_5
.4byte sMetangAnims_1_6
.4byte sMetangAnims_1_7
.4byte sMetangAnims_1_8
sMetangAnimTable2:
.4byte sMetangAnims_2_1
.4byte sMetangAnims_2_2
.4byte sMetangAnims_2_3
.4byte sMetangAnims_2_4
.4byte sMetangAnims_2_5
.4byte sMetangAnims_2_6
.4byte sMetangAnims_2_7
.4byte sMetangAnims_2_8
sMetangAnimTable3:
.4byte sMetangAnims_3_1
.4byte sMetangAnims_3_2
.4byte sMetangAnims_3_3
.4byte sMetangAnims_3_4
.4byte sMetangAnims_3_5
.4byte sMetangAnims_3_6
.4byte sMetangAnims_3_7
.4byte sMetangAnims_3_8
sMetangAnimTable4:
.4byte sMetangAnims_4_1
.4byte sMetangAnims_4_2
.4byte sMetangAnims_4_3
.4byte sMetangAnims_4_4
.4byte sMetangAnims_4_5
.4byte sMetangAnims_4_6
.4byte sMetangAnims_4_7
.4byte sMetangAnims_4_8
sMetangAnimTable5:
.4byte sMetangAnims_5_1
.4byte sMetangAnims_5_2
.4byte sMetangAnims_5_3
.4byte sMetangAnims_5_4
.4byte sMetangAnims_5_5
.4byte sMetangAnims_5_6
.4byte sMetangAnims_5_7
.4byte sMetangAnims_5_8
sMetangAnimTable6:
.4byte sMetangAnims_6_1
.4byte sMetangAnims_6_1
.4byte sMetangAnims_6_1
.4byte sMetangAnims_6_1
.4byte sMetangAnims_6_1
.4byte sMetangAnims_6_1
.4byte sMetangAnims_6_1
.4byte sMetangAnims_6_1
sMetangAnimTable7:
.4byte sMetangAnims_7_1
.4byte sMetangAnims_7_2
.4byte sMetangAnims_7_3
.4byte sMetangAnims_7_4
.4byte sMetangAnims_7_5
.4byte sMetangAnims_7_6
.4byte sMetangAnims_7_7
.4byte sMetangAnims_7_8
sMetangAnimTable8:
.4byte sMetangAnims_8_1
.4byte sMetangAnims_8_2
.4byte sMetangAnims_8_3
.4byte sMetangAnims_8_4
.4byte sMetangAnims_8_5
.4byte sMetangAnims_8_6
.4byte sMetangAnims_8_7
.4byte sMetangAnims_8_8
sMetangAnimTable9:
.4byte sMetangAnims_9_1
.4byte sMetangAnims_9_2
.4byte sMetangAnims_9_3
.4byte sMetangAnims_9_4
.4byte sMetangAnims_9_5
.4byte sMetangAnims_9_6
.4byte sMetangAnims_9_7
.4byte sMetangAnims_9_8
sMetangAnimTable10:
.4byte sMetangAnims_10_1
.4byte sMetangAnims_10_2
.4byte sMetangAnims_10_3
.4byte sMetangAnims_10_4
.4byte sMetangAnims_10_5
.4byte sMetangAnims_10_6
.4byte sMetangAnims_10_7
.4byte sMetangAnims_10_8
sMetangAnimTable11:
.4byte sMetangAnims_11_1
.4byte sMetangAnims_11_2
.4byte sMetangAnims_11_3
.4byte sMetangAnims_11_4
.4byte sMetangAnims_11_5
.4byte sMetangAnims_11_6
.4byte sMetangAnims_11_7
.4byte sMetangAnims_11_8
sMetangAnimTable12:
.4byte sMetangAnims_12_1
.4byte sMetangAnims_12_2
.4byte sMetangAnims_12_3
.4byte sMetangAnims_12_4
.4byte sMetangAnims_12_5
.4byte sMetangAnims_12_6
.4byte sMetangAnims_12_7
.4byte sMetangAnims_12_8
sMetangAnimTable13:
.4byte sMetangAnims_13_1
.4byte sMetangAnims_13_2
.4byte sMetangAnims_13_3
.4byte sMetangAnims_13_4
.4byte sMetangAnims_13_5
.4byte sMetangAnims_13_6
.4byte sMetangAnims_13_7
.4byte sMetangAnims_13_8
sAxAnimationsMetang:
.4byte sMetangAnimTable1
.4byte sMetangAnimTable2
.4byte sMetangAnimTable3
.4byte sMetangAnimTable4
.4byte sMetangAnimTable5
.4byte sMetangAnimTable6
.4byte sMetangAnimTable7
.4byte sMetangAnimTable8
.4byte sMetangAnimTable9
.4byte sMetangAnimTable10
.4byte sMetangAnimTable11
.4byte sMetangAnimTable12
.4byte sMetangAnimTable13
sAxSpritesMetang:
.4byte sMetangSprites1
.4byte sMetangSprites2
.4byte sMetangSprites3
.4byte sMetangSprites4
.4byte sMetangSprites5
.4byte sMetangSprites6
.4byte sMetangSprites7
.4byte sMetangSprites8
.4byte sMetangSprites9
.4byte sMetangSprites10
.4byte sMetangSprites11
.4byte sMetangSprites12
.4byte sMetangSprites13
.4byte sMetangSprites14
.4byte sMetangSprites15
.4byte sMetangSprites16
.4byte sMetangSprites17
.4byte sMetangSprites18
.4byte sMetangSprites19
.4byte sMetangSprites20
.4byte sMetangSprites21
.4byte sMetangSprites22
.4byte sMetangSprites23
.4byte sMetangSprites24
.4byte sMetangSprites25
.4byte sMetangSprites26
.4byte sMetangSprites27
.4byte sMetangSprites28
.4byte sMetangSprites29
.4byte sMetangSprites30
.4byte sMetangSprites31
.4byte sMetangSprites32
.4byte sMetangSprites33
.4byte sMetangSprites34
.4byte sMetangSprites35
.4byte sMetangSprites36
.4byte sMetangSprites37
.4byte sMetangSprites38
.4byte sMetangSprites39
.4byte sMetangSprites40
.4byte sMetangSprites41
.4byte sMetangSprites42
.4byte sMetangSprites43
.4byte sMetangSprites44
.4byte sMetangSprites45
.4byte sMetangSprites46
.4byte sMetangSprites47
.4byte sMetangSprites48
.4byte sMetangSprites49
.4byte sMetangSprites50
.4byte sMetangSprites51
.4byte sMetangSprites52
.4byte sMetangSprites53
.4byte sMetangSprites54
.4byte sMetangSprites55
.4byte sMetangSprites56
.4byte sMetangSprites57
.4byte sMetangSprites58
.4byte sMetangSprites59
.4byte sMetangSprites60
.4byte sMetangSprites61
.4byte sMetangSprites62
sAxMainMetang:
ax_main sAxPosesMetang, sAxAnimationsMetang, 13, sAxSpritesMetang, sAxPositionsMetang
