.global gAxMightyena
gAxMightyena:
ax_siro sAxMainMightyena
sMightyenaPose1:
ax_pose 0, 0x81e8, 0x80f8, 0xbc00
ax_pose_terminator
sMightyenaPose2:
ax_pose 1, 0x81e8, 0x80f8, 0xbc00
ax_pose_terminator
sMightyenaPose3:
ax_pose 2, 0x81e8, 0x80f8, 0xbc00
ax_pose_terminator
sMightyenaPose4:
ax_pose 3, 0x01e8, 0x90ed, 0xbc00
ax_pose_terminator
sMightyenaPose5:
ax_pose 4, 0x01e8, 0x90ed, 0xbc00
ax_pose_terminator
sMightyenaPose6:
ax_pose 5, 0x01e8, 0x90ed, 0xbc00
ax_pose_terminator
sMightyenaPose7:
ax_pose 6, 0x01e8, 0x90f0, 0xbc00
ax_pose_terminator
sMightyenaPose8:
ax_pose 7, 0x01e8, 0x90f0, 0xbc00
ax_pose_terminator
sMightyenaPose9:
ax_pose 8, 0x01e8, 0x90f0, 0xbc00
ax_pose_terminator
sMightyenaPose10:
ax_pose 9, 0x01e8, 0x90ec, 0xbc00
ax_pose_terminator
sMightyenaPose11:
ax_pose 10, 0x01e8, 0x90ec, 0xbc00
ax_pose_terminator
sMightyenaPose12:
ax_pose 11, 0x01e8, 0x90ec, 0xbc00
ax_pose_terminator
sMightyenaPose13:
ax_pose 12, 0x81e8, 0x80f8, 0xbc00
ax_pose_terminator
sMightyenaPose14:
ax_pose 13, 0x81e8, 0x80f8, 0xbc00
ax_pose_terminator
sMightyenaPose15:
ax_pose 14, 0x81e8, 0x80f8, 0xbc00
ax_pose_terminator
sMightyenaPose16:
ax_pose 9, 0x01e8, 0x80f4, 0xbc00
ax_pose_terminator
sMightyenaPose17:
ax_pose 10, 0x01e8, 0x80f4, 0xbc00
ax_pose_terminator
sMightyenaPose18:
ax_pose 11, 0x01e8, 0x80f4, 0xbc00
ax_pose_terminator
sMightyenaPose19:
ax_pose 6, 0x01e8, 0x80f0, 0xbc00
ax_pose_terminator
sMightyenaPose20:
ax_pose 7, 0x01e8, 0x80f0, 0xbc00
ax_pose_terminator
sMightyenaPose21:
ax_pose 8, 0x01e8, 0x80f0, 0xbc00
ax_pose_terminator
sMightyenaPose22:
ax_pose 3, 0x01e8, 0x80f3, 0xbc00
ax_pose_terminator
sMightyenaPose23:
ax_pose 4, 0x01e8, 0x80f3, 0xbc00
ax_pose_terminator
sMightyenaPose24:
ax_pose 5, 0x01e8, 0x80f3, 0xbc00
ax_pose_terminator
sMightyenaPose25:
ax_pose 0, 0x81e8, 0x80f8, 0xbc00
ax_pose_terminator
sMightyenaPose26:
ax_pose 15, 0x81e8, 0x80f8, 0xbc00
ax_pose_terminator
sMightyenaPose27:
ax_pose 16, 0x81e8, 0x80f8, 0xbc00
ax_pose_terminator
sMightyenaPose28:
ax_pose 17, 0x81e8, 0x80f8, 0xbc00
ax_pose_terminator
sMightyenaPose29:
ax_pose 3, 0x01e8, 0x90ed, 0xbc00
ax_pose_terminator
sMightyenaPose30:
ax_pose 18, 0x01e8, 0x90ed, 0xbc00
ax_pose_terminator
sMightyenaPose31:
ax_pose 19, 0x01e8, 0x90f0, 0xbc00
ax_pose_terminator
sMightyenaPose32:
ax_pose 20, 0x01ea, 0x90ef, 0xbc00
ax_pose_terminator
sMightyenaPose33:
ax_pose 6, 0x01e8, 0x90f0, 0xbc00
ax_pose_terminator
sMightyenaPose34:
ax_pose 21, 0x01e8, 0x90f0, 0xbc00
ax_pose_terminator
sMightyenaPose35:
ax_pose 22, 0x01e8, 0x90f3, 0xbc00
ax_pose_terminator
sMightyenaPose36:
ax_pose 23, 0x01e6, 0x90f0, 0xbc00
ax_pose_terminator
sMightyenaPose37:
ax_pose 9, 0x01e8, 0x90ec, 0xbc00
ax_pose_terminator
sMightyenaPose38:
ax_pose 24, 0x01e8, 0x90ec, 0xbc00
ax_pose_terminator
sMightyenaPose39:
ax_pose 25, 0x01e8, 0x90ed, 0xbc00
ax_pose_terminator
sMightyenaPose40:
ax_pose 26, 0x01e5, 0x90ec, 0xbc00
ax_pose_terminator
sMightyenaPose41:
ax_pose 12, 0x81e8, 0x80f8, 0xbc00
ax_pose_terminator
sMightyenaPose42:
ax_pose 27, 0x81e8, 0x80f8, 0xbc00
ax_pose_terminator
sMightyenaPose43:
ax_pose 28, 0x81e8, 0x80f8, 0xbc00
ax_pose_terminator
sMightyenaPose44:
ax_pose 29, 0x81e6, 0x80f8, 0xbc00
ax_pose_terminator
sMightyenaPose45:
ax_pose 9, 0x01e8, 0x80f4, 0xbc00
ax_pose_terminator
sMightyenaPose46:
ax_pose 24, 0x01e8, 0x80f4, 0xbc00
ax_pose_terminator
sMightyenaPose47:
ax_pose 25, 0x01e8, 0x80f3, 0xbc00
ax_pose_terminator
sMightyenaPose48:
ax_pose 26, 0x01e5, 0x80f4, 0xbc00
ax_pose_terminator
sMightyenaPose49:
ax_pose 6, 0x01e8, 0x80f0, 0xbc00
ax_pose_terminator
sMightyenaPose50:
ax_pose 21, 0x01e8, 0x80f0, 0xbc00
ax_pose_terminator
sMightyenaPose51:
ax_pose 22, 0x01e8, 0x80ed, 0xbc00
ax_pose_terminator
sMightyenaPose52:
ax_pose 23, 0x01e6, 0x80f0, 0xbc00
ax_pose_terminator
sMightyenaPose53:
ax_pose 3, 0x01e8, 0x80f3, 0xbc00
ax_pose_terminator
sMightyenaPose54:
ax_pose 18, 0x01e8, 0x80f3, 0xbc00
ax_pose_terminator
sMightyenaPose55:
ax_pose 19, 0x01e8, 0x80f0, 0xbc00
ax_pose_terminator
sMightyenaPose56:
ax_pose 20, 0x01ea, 0x80f1, 0xbc00
ax_pose_terminator
sMightyenaPose57:
ax_pose 0, 0x81e8, 0x80f8, 0xbc00
ax_pose_terminator
sMightyenaPose58:
ax_pose 15, 0x81e8, 0x80f8, 0xbc00
ax_pose_terminator
sMightyenaPose59:
ax_pose 16, 0x81e8, 0x80f8, 0xbc00
ax_pose_terminator
sMightyenaPose60:
ax_pose 17, 0x81e8, 0x80f8, 0xbc00
ax_pose_terminator
sMightyenaPose61:
ax_pose 3, 0x01e8, 0x90ed, 0xbc00
ax_pose_terminator
sMightyenaPose62:
ax_pose 18, 0x01e8, 0x90ed, 0xbc00
ax_pose_terminator
sMightyenaPose63:
ax_pose 19, 0x01e8, 0x90f0, 0xbc00
ax_pose_terminator
sMightyenaPose64:
ax_pose 20, 0x01ea, 0x90ef, 0xbc00
ax_pose_terminator
sMightyenaPose65:
ax_pose 6, 0x01e8, 0x90f0, 0xbc00
ax_pose_terminator
sMightyenaPose66:
ax_pose 21, 0x01e8, 0x90f0, 0xbc00
ax_pose_terminator
sMightyenaPose67:
ax_pose 22, 0x01e8, 0x90f3, 0xbc00
ax_pose_terminator
sMightyenaPose68:
ax_pose 23, 0x01e6, 0x90f0, 0xbc00
ax_pose_terminator
sMightyenaPose69:
ax_pose 9, 0x01e8, 0x90ec, 0xbc00
ax_pose_terminator
sMightyenaPose70:
ax_pose 24, 0x01e8, 0x90ec, 0xbc00
ax_pose_terminator
sMightyenaPose71:
ax_pose 25, 0x01e8, 0x90ed, 0xbc00
ax_pose_terminator
sMightyenaPose72:
ax_pose 26, 0x01e5, 0x90ec, 0xbc00
ax_pose_terminator
sMightyenaPose73:
ax_pose 12, 0x81e8, 0x80f8, 0xbc00
ax_pose_terminator
sMightyenaPose74:
ax_pose 27, 0x81e8, 0x80f8, 0xbc00
ax_pose_terminator
sMightyenaPose75:
ax_pose 28, 0x81e8, 0x80f8, 0xbc00
ax_pose_terminator
sMightyenaPose76:
ax_pose 29, 0x81e6, 0x80f8, 0xbc00
ax_pose_terminator
sMightyenaPose77:
ax_pose 9, 0x01e8, 0x80f4, 0xbc00
ax_pose_terminator
sMightyenaPose78:
ax_pose 24, 0x01e8, 0x80f4, 0xbc00
ax_pose_terminator
sMightyenaPose79:
ax_pose 25, 0x01e8, 0x80f3, 0xbc00
ax_pose_terminator
sMightyenaPose80:
ax_pose 26, 0x01e5, 0x80f4, 0xbc00
ax_pose_terminator
sMightyenaPose81:
ax_pose 6, 0x01e8, 0x80f0, 0xbc00
ax_pose_terminator
sMightyenaPose82:
ax_pose 21, 0x01e8, 0x80f0, 0xbc00
ax_pose_terminator
sMightyenaPose83:
ax_pose 22, 0x01e8, 0x80ed, 0xbc00
ax_pose_terminator
sMightyenaPose84:
ax_pose 23, 0x01e6, 0x80f0, 0xbc00
ax_pose_terminator
sMightyenaPose85:
ax_pose 3, 0x01e8, 0x80f3, 0xbc00
ax_pose_terminator
sMightyenaPose86:
ax_pose 18, 0x01e8, 0x80f3, 0xbc00
ax_pose_terminator
sMightyenaPose87:
ax_pose 19, 0x01e8, 0x80f0, 0xbc00
ax_pose_terminator
sMightyenaPose88:
ax_pose 20, 0x01ea, 0x80f1, 0xbc00
ax_pose_terminator
sMightyenaPose89:
ax_pose 0, 0x81e8, 0x80f8, 0xbc00
ax_pose_terminator
sMightyenaPose90:
ax_pose 15, 0x81e8, 0x80f8, 0xbc00
ax_pose_terminator
sMightyenaPose91:
ax_pose 16, 0x81e8, 0x80f8, 0xbc00
ax_pose_terminator
sMightyenaPose92:
ax_pose 30, 0x81e8, 0x80f8, 0xbc00
ax_pose_terminator
sMightyenaPose93:
ax_pose 3, 0x01e8, 0x90ed, 0xbc00
ax_pose_terminator
sMightyenaPose94:
ax_pose 18, 0x01e8, 0x90ed, 0xbc00
ax_pose_terminator
sMightyenaPose95:
ax_pose 19, 0x01e8, 0x90f0, 0xbc00
ax_pose_terminator
sMightyenaPose96:
ax_pose 31, 0x01e8, 0x90ed, 0xbc00
ax_pose_terminator
sMightyenaPose97:
ax_pose 6, 0x01e8, 0x90f0, 0xbc00
ax_pose_terminator
sMightyenaPose98:
ax_pose 21, 0x01e8, 0x90f0, 0xbc00
ax_pose_terminator
sMightyenaPose99:
ax_pose 22, 0x01e8, 0x90f3, 0xbc00
ax_pose_terminator
sMightyenaPose100:
ax_pose 32, 0x01e6, 0x90f0, 0xbc00
ax_pose_terminator
sMightyenaPose101:
ax_pose 9, 0x01e8, 0x90ec, 0xbc00
ax_pose_terminator
sMightyenaPose102:
ax_pose 24, 0x01e8, 0x90ec, 0xbc00
ax_pose_terminator
sMightyenaPose103:
ax_pose 25, 0x01e8, 0x90ed, 0xbc00
ax_pose_terminator
sMightyenaPose104:
ax_pose 33, 0x01e6, 0x90ec, 0xbc00
ax_pose_terminator
sMightyenaPose105:
ax_pose 12, 0x81e8, 0x80f8, 0xbc00
ax_pose_terminator
sMightyenaPose106:
ax_pose 27, 0x81e8, 0x80f8, 0xbc00
ax_pose_terminator
sMightyenaPose107:
ax_pose 28, 0x81e8, 0x80f8, 0xbc00
ax_pose_terminator
sMightyenaPose108:
ax_pose 34, 0x81e7, 0x80f8, 0xbc00
ax_pose_terminator
sMightyenaPose109:
ax_pose 9, 0x01e8, 0x80f4, 0xbc00
ax_pose_terminator
sMightyenaPose110:
ax_pose 24, 0x01e8, 0x80f4, 0xbc00
ax_pose_terminator
sMightyenaPose111:
ax_pose 25, 0x01e8, 0x80f3, 0xbc00
ax_pose_terminator
sMightyenaPose112:
ax_pose 33, 0x01e6, 0x80f4, 0xbc00
ax_pose_terminator
sMightyenaPose113:
ax_pose 6, 0x01e8, 0x80f0, 0xbc00
ax_pose_terminator
sMightyenaPose114:
ax_pose 21, 0x01e8, 0x80f0, 0xbc00
ax_pose_terminator
sMightyenaPose115:
ax_pose 22, 0x01e8, 0x80ed, 0xbc00
ax_pose_terminator
sMightyenaPose116:
ax_pose 32, 0x01e6, 0x80f0, 0xbc00
ax_pose_terminator
sMightyenaPose117:
ax_pose 3, 0x01e8, 0x80f3, 0xbc00
ax_pose_terminator
sMightyenaPose118:
ax_pose 18, 0x01e8, 0x80f3, 0xbc00
ax_pose_terminator
sMightyenaPose119:
ax_pose 19, 0x01e8, 0x80f0, 0xbc00
ax_pose_terminator
sMightyenaPose120:
ax_pose 31, 0x01e8, 0x80f3, 0xbc00
ax_pose_terminator
sMightyenaPose121:
ax_pose 30, 0x81e8, 0x80f8, 0xbc00
ax_pose_terminator
sMightyenaPose122:
ax_pose 15, 0x81e8, 0x80f8, 0xbc00
ax_pose_terminator
sMightyenaPose123:
ax_pose 31, 0x01e8, 0x90ed, 0xbc00
ax_pose_terminator
sMightyenaPose124:
ax_pose 18, 0x01e8, 0x90ed, 0xbc00
ax_pose_terminator
sMightyenaPose125:
ax_pose 32, 0x01e6, 0x90f0, 0xbc00
ax_pose_terminator
sMightyenaPose126:
ax_pose 21, 0x01e8, 0x90f0, 0xbc00
ax_pose_terminator
sMightyenaPose127:
ax_pose 33, 0x01e6, 0x90ec, 0xbc00
ax_pose_terminator
sMightyenaPose128:
ax_pose 24, 0x01e8, 0x90ec, 0xbc00
ax_pose_terminator
sMightyenaPose129:
ax_pose 34, 0x81e7, 0x80f8, 0xbc00
ax_pose_terminator
sMightyenaPose130:
ax_pose 27, 0x81e8, 0x80f8, 0xbc00
ax_pose_terminator
sMightyenaPose131:
ax_pose 33, 0x01e6, 0x80f4, 0xbc00
ax_pose_terminator
sMightyenaPose132:
ax_pose 24, 0x01e8, 0x80f4, 0xbc00
ax_pose_terminator
sMightyenaPose133:
ax_pose 32, 0x01e6, 0x80f0, 0xbc00
ax_pose_terminator
sMightyenaPose134:
ax_pose 21, 0x01e8, 0x80f0, 0xbc00
ax_pose_terminator
sMightyenaPose135:
ax_pose 31, 0x01e8, 0x80f3, 0xbc00
ax_pose_terminator
sMightyenaPose136:
ax_pose 18, 0x01e8, 0x80f3, 0xbc00
ax_pose_terminator
sMightyenaPose137:
ax_pose 35, 0x01ea, 0x80f4, 0xbc00
ax_pose_terminator
sMightyenaPose138:
ax_pose 36, 0x01ea, 0x80f4, 0xbc00
ax_pose_terminator
sMightyenaPose139:
ax_pose 37, 0x01e2, 0x80f1, 0xbc00
ax_pose_terminator
sMightyenaPose140:
ax_pose 38, 0x01e5, 0x90ef, 0xbc00
ax_pose_terminator
sMightyenaPose141:
ax_pose 39, 0x01e3, 0x90ec, 0xbc00
ax_pose_terminator
sMightyenaPose142:
ax_pose 40, 0x01e5, 0x90ec, 0xbc00
ax_pose_terminator
sMightyenaPose143:
ax_pose 41, 0x01e4, 0x80f0, 0xbc00
ax_pose_terminator
sMightyenaPose144:
ax_pose 40, 0x01e4, 0x80f4, 0xbc00
ax_pose_terminator
sMightyenaPose145:
ax_pose 39, 0x01e3, 0x80f4, 0xbc00
ax_pose_terminator
sMightyenaPose146:
ax_pose 38, 0x01e5, 0x80f1, 0xbc00
ax_pose_terminator
sMightyenaPose147:
ax_pose 0, 0x81e8, 0x80f8, 0xbc00
ax_pose_terminator
sMightyenaPose148:
ax_pose 15, 0x81e8, 0x80f8, 0xbc00
ax_pose_terminator
sMightyenaPose149:
ax_pose 16, 0x81e8, 0x80f8, 0xbc00
ax_pose_terminator
sMightyenaPose150:
ax_pose 30, 0x81e8, 0x80f8, 0xbc00
ax_pose_terminator
sMightyenaPose151:
ax_pose 3, 0x01e8, 0x90ed, 0xbc00
ax_pose_terminator
sMightyenaPose152:
ax_pose 18, 0x01e8, 0x90ed, 0xbc00
ax_pose_terminator
sMightyenaPose153:
ax_pose 19, 0x01e8, 0x90f0, 0xbc00
ax_pose_terminator
sMightyenaPose154:
ax_pose 31, 0x01e8, 0x90ed, 0xbc00
ax_pose_terminator
sMightyenaPose155:
ax_pose 6, 0x01e8, 0x90f0, 0xbc00
ax_pose_terminator
sMightyenaPose156:
ax_pose 21, 0x01e8, 0x90f0, 0xbc00
ax_pose_terminator
sMightyenaPose157:
ax_pose 22, 0x01e8, 0x90f3, 0xbc00
ax_pose_terminator
sMightyenaPose158:
ax_pose 32, 0x01e6, 0x90f0, 0xbc00
ax_pose_terminator
sMightyenaPose159:
ax_pose 9, 0x01e8, 0x90ec, 0xbc00
ax_pose_terminator
sMightyenaPose160:
ax_pose 24, 0x01e8, 0x90ec, 0xbc00
ax_pose_terminator
sMightyenaPose161:
ax_pose 25, 0x01e8, 0x90ed, 0xbc00
ax_pose_terminator
sMightyenaPose162:
ax_pose 33, 0x01e6, 0x90ec, 0xbc00
ax_pose_terminator
sMightyenaPose163:
ax_pose 12, 0x81e8, 0x80f8, 0xbc00
ax_pose_terminator
sMightyenaPose164:
ax_pose 27, 0x81e8, 0x80f8, 0xbc00
ax_pose_terminator
sMightyenaPose165:
ax_pose 28, 0x81e8, 0x80f8, 0xbc00
ax_pose_terminator
sMightyenaPose166:
ax_pose 34, 0x81e7, 0x80f8, 0xbc00
ax_pose_terminator
sMightyenaPose167:
ax_pose 9, 0x01e8, 0x80f4, 0xbc00
ax_pose_terminator
sMightyenaPose168:
ax_pose 24, 0x01e8, 0x80f4, 0xbc00
ax_pose_terminator
sMightyenaPose169:
ax_pose 25, 0x01e8, 0x80f3, 0xbc00
ax_pose_terminator
sMightyenaPose170:
ax_pose 33, 0x01e6, 0x80f4, 0xbc00
ax_pose_terminator
sMightyenaPose171:
ax_pose 6, 0x01e8, 0x80f0, 0xbc00
ax_pose_terminator
sMightyenaPose172:
ax_pose 21, 0x01e8, 0x80f0, 0xbc00
ax_pose_terminator
sMightyenaPose173:
ax_pose 22, 0x01e8, 0x80ed, 0xbc00
ax_pose_terminator
sMightyenaPose174:
ax_pose 32, 0x01e6, 0x80f0, 0xbc00
ax_pose_terminator
sMightyenaPose175:
ax_pose 3, 0x01e8, 0x80f3, 0xbc00
ax_pose_terminator
sMightyenaPose176:
ax_pose 18, 0x01e8, 0x80f3, 0xbc00
ax_pose_terminator
sMightyenaPose177:
ax_pose 19, 0x01e8, 0x80f0, 0xbc00
ax_pose_terminator
sMightyenaPose178:
ax_pose 31, 0x01e8, 0x80f3, 0xbc00
ax_pose_terminator
sMightyenaPose179:
ax_pose 17, 0x81eb, 0x80f8, 0xbc00
ax_pose_terminator
sMightyenaPose180:
ax_pose 20, 0x01ec, 0x80f1, 0xbc00
ax_pose_terminator
sMightyenaPose181:
ax_pose 23, 0x01e8, 0x80f0, 0xbc00
ax_pose_terminator
sMightyenaPose182:
ax_pose 26, 0x01e7, 0x80f4, 0xbc00
ax_pose_terminator
sMightyenaPose183:
ax_pose 29, 0x81e8, 0x80f8, 0xbc00
ax_pose_terminator
sMightyenaPose184:
ax_pose 26, 0x01e7, 0x90ec, 0xbc00
ax_pose_terminator
sMightyenaPose185:
ax_pose 23, 0x01e8, 0x90f0, 0xbc00
ax_pose_terminator
sMightyenaPose186:
ax_pose 20, 0x01ec, 0x90ef, 0xbc00
ax_pose_terminator
sMightyenaPose187:
ax_pose 15, 0x81e8, 0x80f8, 0xbc00
ax_pose_terminator
sMightyenaPose188:
ax_pose 18, 0x01e9, 0x90ee, 0xbc00
ax_pose_terminator
sMightyenaPose189:
ax_pose 21, 0x01e8, 0x90f0, 0xbc00
ax_pose_terminator
sMightyenaPose190:
ax_pose 24, 0x01e8, 0x90ec, 0xbc00
ax_pose_terminator
sMightyenaPose191:
ax_pose 27, 0x81e7, 0x80f8, 0xbc00
ax_pose_terminator
sMightyenaPose192:
ax_pose 24, 0x01e8, 0x80f4, 0xbc00
ax_pose_terminator
sMightyenaPose193:
ax_pose 21, 0x01e8, 0x80f0, 0xbc00
ax_pose_terminator
sMightyenaPose194:
ax_pose 18, 0x01e9, 0x80f2, 0xbc00
ax_pose_terminator
sMightyenaPose195:
ax_pose 0, 0x81e8, 0x80f8, 0xbc00
ax_pose_terminator
sMightyenaPose196:
ax_pose 16, 0x81e8, 0x80f8, 0xbc00
ax_pose_terminator
sMightyenaPose197:
ax_pose 17, 0x81e8, 0x80f8, 0xbc00
ax_pose_terminator
sMightyenaPose198:
ax_pose 3, 0x01e8, 0x90ed, 0xbc00
ax_pose_terminator
sMightyenaPose199:
ax_pose 19, 0x01e8, 0x90ef, 0xbc00
ax_pose_terminator
sMightyenaPose200:
ax_pose 20, 0x01ea, 0x90ef, 0xbc00
ax_pose_terminator
sMightyenaPose201:
ax_pose 6, 0x01e8, 0x90f0, 0xbc00
ax_pose_terminator
sMightyenaPose202:
ax_pose 22, 0x01e8, 0x90f2, 0xbc00
ax_pose_terminator
sMightyenaPose203:
ax_pose 23, 0x01e6, 0x90f0, 0xbc00
ax_pose_terminator
sMightyenaPose204:
ax_pose 9, 0x01e8, 0x90ec, 0xbc00
ax_pose_terminator
sMightyenaPose205:
ax_pose 25, 0x01e8, 0x90ec, 0xbc00
ax_pose_terminator
sMightyenaPose206:
ax_pose 26, 0x01e5, 0x90ec, 0xbc00
ax_pose_terminator
sMightyenaPose207:
ax_pose 12, 0x81e8, 0x80f8, 0xbc00
ax_pose_terminator
sMightyenaPose208:
ax_pose 28, 0x81e8, 0x80f8, 0xbc00
ax_pose_terminator
sMightyenaPose209:
ax_pose 29, 0x81e6, 0x80f8, 0xbc00
ax_pose_terminator
sMightyenaPose210:
ax_pose 9, 0x01e8, 0x80f4, 0xbc00
ax_pose_terminator
sMightyenaPose211:
ax_pose 25, 0x01e8, 0x80f4, 0xbc00
ax_pose_terminator
sMightyenaPose212:
ax_pose 26, 0x01e5, 0x80f3, 0xbc00
ax_pose_terminator
sMightyenaPose213:
ax_pose 6, 0x01e8, 0x80f0, 0xbc00
ax_pose_terminator
sMightyenaPose214:
ax_pose 22, 0x01e8, 0x80ee, 0xbc00
ax_pose_terminator
sMightyenaPose215:
ax_pose 23, 0x01e6, 0x80f0, 0xbc00
ax_pose_terminator
sMightyenaPose216:
ax_pose 3, 0x01e8, 0x80f3, 0xbc00
ax_pose_terminator
sMightyenaPose217:
ax_pose 19, 0x01e8, 0x80f1, 0xbc00
ax_pose_terminator
sMightyenaPose218:
ax_pose 20, 0x01ea, 0x80f1, 0xbc00
ax_pose_terminator
sMightyenaPose219:
ax_pose 16, 0x81e8, 0x80f8, 0xbc00
ax_pose_terminator
sMightyenaPose220:
ax_pose 19, 0x01e8, 0x80f2, 0xbc00
ax_pose_terminator
sMightyenaPose221:
ax_pose 22, 0x01e8, 0x80ef, 0xbc00
ax_pose_terminator
sMightyenaPose222:
ax_pose 25, 0x01e8, 0x80f4, 0xbc00
ax_pose_terminator
sMightyenaPose223:
ax_pose 28, 0x81e8, 0x80f8, 0xbc00
ax_pose_terminator
sMightyenaPose224:
ax_pose 25, 0x01e8, 0x90ec, 0xbc00
ax_pose_terminator
sMightyenaPose225:
ax_pose 22, 0x01e8, 0x90f1, 0xbc00
ax_pose_terminator
sMightyenaPose226:
ax_pose 19, 0x01e8, 0x90ee, 0xbc00
ax_pose_terminator
sMightyenaPose227:
ax_pose 0, 0x81e8, 0x80f8, 0xbc00
ax_pose_terminator
sMightyenaPose228:
ax_pose 3, 0x01e8, 0x80f3, 0xbc00
ax_pose_terminator
sMightyenaPose229:
ax_pose 6, 0x01e8, 0x80f0, 0xbc00
ax_pose_terminator
sMightyenaPose230:
ax_pose 9, 0x01e8, 0x80f4, 0xbc00
ax_pose_terminator
sMightyenaPose231:
ax_pose 12, 0x81e8, 0x80f8, 0xbc00
ax_pose_terminator
sMightyenaPose232:
ax_pose 9, 0x01e8, 0x90ec, 0xbc00
ax_pose_terminator
sMightyenaPose233:
ax_pose 6, 0x01e8, 0x90f0, 0xbc00
ax_pose_terminator
sMightyenaPose234:
ax_pose 3, 0x01e8, 0x90ed, 0xbc00
ax_pose_terminator
.align 2
sMightyenaAnims_1_1:
ax_anim 10, 0, 0, 0, 0, 0, 0,
ax_anim 10, 0, 1, 0, 0, 0, 0,
ax_anim 10, 0, 0, 0, 0, 0, 0,
ax_anim 10, 0, 2, 0, 0, 0, 0,
ax_anim_terminator
sMightyenaAnims_1_2:
ax_anim 10, 0, 3, 0, 0, 0, 0,
ax_anim 10, 0, 4, 0, 0, 0, 0,
ax_anim 10, 0, 3, 0, 0, 0, 0,
ax_anim 10, 0, 5, 0, 0, 0, 0,
ax_anim_terminator
sMightyenaAnims_1_3:
ax_anim 10, 0, 6, 0, 0, 0, 0,
ax_anim 10, 0, 7, 0, 0, 0, 0,
ax_anim 10, 0, 6, 0, 0, 0, 0,
ax_anim 10, 0, 8, 0, 0, 0, 0,
ax_anim_terminator
sMightyenaAnims_1_4:
ax_anim 10, 0, 9, 0, 0, 0, 0,
ax_anim 10, 0, 10, 0, 0, 0, 0,
ax_anim 10, 0, 9, 0, 0, 0, 0,
ax_anim 10, 0, 11, 0, 0, 0, 0,
ax_anim_terminator
sMightyenaAnims_1_5:
ax_anim 10, 0, 12, 0, 0, 0, 0,
ax_anim 10, 0, 13, 0, 0, 0, 0,
ax_anim 10, 0, 12, 0, 0, 0, 0,
ax_anim 10, 0, 14, 0, 0, 0, 0,
ax_anim_terminator
sMightyenaAnims_1_6:
ax_anim 10, 0, 15, 0, 0, 0, 0,
ax_anim 10, 0, 16, 0, 0, 0, 0,
ax_anim 10, 0, 15, 0, 0, 0, 0,
ax_anim 10, 0, 17, 0, 0, 0, 0,
ax_anim_terminator
sMightyenaAnims_1_7:
ax_anim 10, 0, 18, 0, 0, 0, 0,
ax_anim 10, 0, 19, 0, 0, 0, 0,
ax_anim 10, 0, 18, 0, 0, 0, 0,
ax_anim 10, 0, 20, 0, 0, 0, 0,
ax_anim_terminator
sMightyenaAnims_1_8:
ax_anim 10, 0, 21, 0, 0, 0, 0,
ax_anim 10, 0, 22, 0, 0, 0, 0,
ax_anim 10, 0, 21, 0, 0, 0, 0,
ax_anim 10, 0, 23, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sMightyenaAnims_2_1:
ax_anim 2, 0, 24, 0, -2, 0, -2,
ax_anim 2, 2, 24, 0, -4, 0, -4,
ax_anim 4, 2, 24, 0, -5, 0, -5,
ax_anim 2, 0, 27, 0, -5, 0, -5,
ax_anim 2, 0, 27, 0, 4, 0, 4,
ax_anim 2, 0, 26, 0, 18, 0, 18,
ax_anim 2, 1, 24, 1, 18, 1, 18,
ax_anim 2, 0, 26, 0, 18, 0, 18,
ax_anim 2, 0, 24, 1, 18, 1, 18,
ax_anim 2, 0, 24, 0, 10, 0, 10,
ax_anim 2, 0, 24, 0, 4, 0, 4,
ax_anim_terminator
sMightyenaAnims_2_2:
ax_anim 2, 0, 28, -2, -2, -2, -2,
ax_anim 2, 0, 28, -4, -4, -4, -4,
ax_anim 4, 2, 28, -5, -5, -5, -5,
ax_anim 2, 0, 31, 1, -3, 1, 1,
ax_anim 2, 0, 31, 8, 3, 8, 8,
ax_anim 2, 0, 30, 16, 17, 16, 17,
ax_anim 2, 1, 28, 17, 16, 17, 16,
ax_anim 2, 0, 30, 16, 17, 16, 17,
ax_anim 2, 0, 28, 17, 16, 17, 16,
ax_anim 2, 0, 28, 10, 10, 10, 10,
ax_anim 2, 0, 28, 4, 4, 4, 4,
ax_anim_terminator
sMightyenaAnims_2_3:
ax_anim 2, 0, 32, -2, 0, -2, 0,
ax_anim 2, 0, 32, -4, 0, -4, 0,
ax_anim 4, 2, 32, -5, 0, -5, 0,
ax_anim 2, 0, 35, 1, -1, 1, 0,
ax_anim 2, 0, 35, 8, -3, 8, 0,
ax_anim 2, 0, 34, 13, 0, 13, 0,
ax_anim 2, 1, 32, 13, 1, 13, 1,
ax_anim 2, 0, 34, 13, 0, 13, 0,
ax_anim 2, 0, 32, 13, 1, 13, 1,
ax_anim 2, 0, 32, 10, 0, 10, 0,
ax_anim 2, 0, 32, 4, 0, 4, 0,
ax_anim_terminator
sMightyenaAnims_2_4:
ax_anim 2, 0, 36, -2, 2, -2, 2,
ax_anim 2, 0, 36, -4, 4, -4, 4,
ax_anim 4, 2, 36, -5, 5, -5, 5,
ax_anim 2, 0, 39, 1, -7, 1, -1,
ax_anim 2, 0, 39, 8, -13, 8, -8,
ax_anim 2, 0, 38, 17, -16, 17, -16,
ax_anim 2, 1, 36, 18, -15, 18, -15,
ax_anim 2, 0, 38, 17, -16, 17, -16,
ax_anim 2, 0, 36, 18, -15, 18, -15,
ax_anim 2, 0, 36, 10, -10, 10, -10,
ax_anim 2, 0, 36, 4, -4, 4, -4,
ax_anim_terminator
sMightyenaAnims_2_5:
ax_anim 2, 0, 40, 0, 2, 0, 2,
ax_anim 2, 0, 40, 0, 4, 0, 4,
ax_anim 4, 2, 40, 0, 5, 0, 5,
ax_anim 2, 0, 43, 0, -6, 0, -2,
ax_anim 2, 0, 43, 0, -12, 0, -8,
ax_anim 2, 0, 42, 0, -16, 0, -16,
ax_anim 2, 1, 40, 1, -16, 1, -16,
ax_anim 2, 0, 42, 0, -16, 0, -16,
ax_anim 2, 0, 40, 1, -16, 1, -16,
ax_anim 2, 0, 40, 0, -10, 0, -10,
ax_anim 2, 0, 40, 0, -4, 0, -4,
ax_anim_terminator
sMightyenaAnims_2_6:
ax_anim 2, 0, 44, 2, 2, 2, 2,
ax_anim 2, 0, 44, 4, 4, 4, 4,
ax_anim 4, 2, 44, 5, 5, 5, 5,
ax_anim 2, 0, 47, -1, -7, -1, -1,
ax_anim 2, 0, 47, -8, -13, -8, -8,
ax_anim 2, 0, 46, -17, -16, -17, -16,
ax_anim 2, 1, 44, -18, -15, -18, -15,
ax_anim 2, 0, 46, -17, -16, -17, -16,
ax_anim 2, 0, 44, -18, -15, -18, -15,
ax_anim 2, 0, 44, -10, -10, -10, -10,
ax_anim 2, 0, 44, -4, -4, -4, -4,
ax_anim_terminator
sMightyenaAnims_2_7:
ax_anim 2, 0, 48, 2, 0, 2, 0,
ax_anim 2, 0, 48, 4, 0, 4, 0,
ax_anim 4, 2, 48, 5, 0, 5, 0,
ax_anim 2, 0, 51, -1, -1, -1, 0,
ax_anim 2, 0, 51, -8, -3, -8, 0,
ax_anim 2, 0, 50, -13, 0, -13, 0,
ax_anim 2, 1, 48, -13, 1, -13, 1,
ax_anim 2, 0, 50, -13, 1, -13, 0,
ax_anim 2, 0, 48, -13, 1, -13, 1,
ax_anim 2, 0, 48, -10, 0, -10, 0,
ax_anim 2, 0, 48, -4, 0, -4, 0,
ax_anim_terminator
sMightyenaAnims_2_8:
ax_anim 2, 0, 52, 2, -2, 2, -2,
ax_anim 2, 0, 52, 4, -4, 4, -4,
ax_anim 4, 2, 52, 5, -5, 5, -5,
ax_anim 2, 0, 55, -1, -3, -1, 1,
ax_anim 2, 0, 55, -8, 3, -8, 8,
ax_anim 2, 0, 54, -16, 17, -16, 17,
ax_anim 2, 1, 52, -17, 16, -17, 16,
ax_anim 2, 0, 54, -16, 17, -16, 17,
ax_anim 2, 0, 52, -17, 16, -17, 16,
ax_anim 2, 0, 52, -10, 10, -10, 10,
ax_anim 2, 0, 52, -4, 4, -4, 4,
ax_anim_terminator
.align 2
sMightyenaAnims_3_1:
ax_anim 2, 0, 56, 0, -2, 0, -2,
ax_anim 2, 2, 56, 0, -4, 0, -4,
ax_anim 4, 2, 56, 0, -5, 0, -5,
ax_anim 2, 0, 59, 0, -5, 0, -5,
ax_anim 2, 0, 59, 0, 4, 0, 4,
ax_anim 2, 0, 58, 0, 18, 0, 18,
ax_anim 2, 1, 56, 1, 18, 1, 18,
ax_anim 2, 0, 58, 0, 18, 0, 18,
ax_anim 2, 0, 56, 1, 18, 1, 18,
ax_anim 2, 0, 56, 0, 10, 0, 10,
ax_anim 2, 0, 56, 0, 4, 0, 4,
ax_anim_terminator
sMightyenaAnims_3_2:
ax_anim 2, 0, 60, -2, -2, -2, -2,
ax_anim 2, 0, 60, -4, -4, -4, -4,
ax_anim 4, 2, 60, -5, -5, -5, -5,
ax_anim 2, 0, 63, 1, -3, 1, 1,
ax_anim 2, 0, 63, 8, 3, 8, 8,
ax_anim 2, 0, 62, 16, 17, 16, 17,
ax_anim 2, 1, 60, 17, 16, 17, 16,
ax_anim 2, 0, 62, 16, 17, 16, 17,
ax_anim 2, 0, 60, 17, 16, 17, 16,
ax_anim 2, 0, 60, 10, 10, 10, 10,
ax_anim 2, 0, 60, 4, 4, 4, 4,
ax_anim_terminator
sMightyenaAnims_3_3:
ax_anim 2, 0, 64, -2, 0, -2, 0,
ax_anim 2, 0, 64, -4, 0, -4, 0,
ax_anim 4, 2, 64, -5, 0, -5, 0,
ax_anim 2, 0, 67, 1, -1, 1, 0,
ax_anim 2, 0, 67, 8, -3, 8, 0,
ax_anim 2, 0, 66, 13, 0, 13, 0,
ax_anim 2, 1, 64, 13, 1, 13, 1,
ax_anim 2, 0, 66, 13, 0, 13, 0,
ax_anim 2, 0, 64, 13, 1, 13, 1,
ax_anim 2, 0, 64, 10, 0, 10, 0,
ax_anim 2, 0, 64, 4, 0, 4, 0,
ax_anim_terminator
sMightyenaAnims_3_4:
ax_anim 2, 0, 68, -2, 2, -2, 2,
ax_anim 2, 0, 68, -4, 4, -4, 4,
ax_anim 4, 2, 68, -5, 5, -5, 5,
ax_anim 2, 0, 71, 1, -7, 1, -1,
ax_anim 2, 0, 71, 8, -13, 8, -8,
ax_anim 2, 0, 70, 17, -16, 17, -16,
ax_anim 2, 1, 68, 18, -15, 18, -15,
ax_anim 2, 0, 70, 17, -16, 17, -16,
ax_anim 2, 0, 68, 18, -15, 18, -15,
ax_anim 2, 0, 68, 10, -10, 10, -10,
ax_anim 2, 0, 68, 4, -4, 4, -4,
ax_anim_terminator
sMightyenaAnims_3_5:
ax_anim 2, 0, 72, 0, 2, 0, 2,
ax_anim 2, 0, 72, 0, 4, 0, 4,
ax_anim 4, 2, 72, 0, 5, 0, 5,
ax_anim 2, 0, 75, 0, -6, 0, -2,
ax_anim 2, 0, 75, 0, -12, 0, -8,
ax_anim 2, 0, 74, 0, -16, 0, -16,
ax_anim 2, 1, 72, 1, -16, 1, -16,
ax_anim 2, 0, 74, 0, -16, 0, -16,
ax_anim 2, 0, 72, 1, -16, 1, -16,
ax_anim 2, 0, 72, 0, -10, 0, -10,
ax_anim 2, 0, 72, 0, -4, 0, -4,
ax_anim_terminator
sMightyenaAnims_3_6:
ax_anim 2, 0, 76, 2, 2, 2, 2,
ax_anim 2, 0, 76, 4, 4, 4, 4,
ax_anim 4, 2, 76, 5, 5, 5, 5,
ax_anim 2, 0, 79, -1, -7, -1, -1,
ax_anim 2, 0, 79, -8, -13, -8, -8,
ax_anim 2, 0, 78, -17, -16, -17, -16,
ax_anim 2, 1, 76, -18, -15, -18, -15,
ax_anim 2, 0, 78, -17, -16, -17, -16,
ax_anim 2, 0, 76, -18, -15, -18, -15,
ax_anim 2, 0, 76, -10, -10, -10, -10,
ax_anim 2, 0, 76, -4, -4, -4, -4,
ax_anim_terminator
sMightyenaAnims_3_7:
ax_anim 2, 0, 80, 2, 0, 2, 0,
ax_anim 2, 0, 80, 4, 0, 4, 0,
ax_anim 4, 2, 80, 5, 0, 5, 0,
ax_anim 2, 0, 83, -1, -1, -1, 0,
ax_anim 2, 0, 83, -8, -3, -8, 0,
ax_anim 2, 0, 82, -13, 0, -13, 0,
ax_anim 2, 1, 80, -13, 1, -13, 1,
ax_anim 2, 0, 82, -13, 1, -13, 0,
ax_anim 2, 0, 80, -13, 1, -13, 1,
ax_anim 2, 0, 80, -10, 0, -10, 0,
ax_anim 2, 0, 80, -4, 0, -4, 0,
ax_anim_terminator
sMightyenaAnims_3_8:
ax_anim 2, 0, 84, 2, -2, 2, -2,
ax_anim 2, 0, 84, 4, -4, 4, -4,
ax_anim 4, 2, 84, 5, -5, 5, -5,
ax_anim 2, 0, 87, -1, -3, -1, 1,
ax_anim 2, 0, 87, -8, 3, -8, 8,
ax_anim 2, 0, 86, -16, 17, -16, 17,
ax_anim 2, 1, 84, -17, 16, -17, 16,
ax_anim 2, 0, 86, -16, 17, -16, 17,
ax_anim 2, 0, 84, -17, 16, -17, 16,
ax_anim 2, 0, 84, -10, 10, -10, 10,
ax_anim 2, 0, 84, -4, 4, -4, 4,
ax_anim_terminator
.align 2
sMightyenaAnims_4_1:
ax_anim 6, 0, 91, 0, 0, 0, 0,
ax_anim 2, 0, 89, 0, -2, 0, -2,
ax_anim 2, 2, 89, 0, -3, 0, -3,
ax_anim 4, 0, 89, 0, -4, 0, -4,
ax_anim 1, 0, 90, 0, -1, 0, -1,
ax_anim 1, 0, 90, 0, 4, 0, 4,
ax_anim 2, 1, 90, 0, 5, 0, 5,
ax_anim 2, 0, 90, 1, 5, 1, 5,
ax_anim 2, 0, 90, 0, 5, 0, 5,
ax_anim 2, 0, 90, 1, 5, 1, 5,
ax_anim 2, 0, 90, 0, 5, 0, 5,
ax_anim 2, 0, 90, 1, 5, 1, 5,
ax_anim 2, 0, 88, 0, 2, 0, 2,
ax_anim_terminator
sMightyenaAnims_4_2:
ax_anim 6, 0, 95, 0, 0, 0, 0,
ax_anim 2, 0, 93, -2, -2, -1, -1,
ax_anim 2, 2, 93, -3, -3, -3, -3,
ax_anim 4, 0, 93, -4, -4, -4, -4,
ax_anim 1, 0, 94, -1, -1, -1, -1,
ax_anim 1, 0, 94, 4, 4, 4, 4,
ax_anim 2, 1, 94, 6, 6, 6, 6,
ax_anim 2, 0, 94, 7, 5, 7, 5,
ax_anim 2, 0, 94, 6, 6, 6, 6,
ax_anim 2, 0, 94, 7, 5, 7, 5,
ax_anim 2, 0, 94, 6, 6, 6, 6,
ax_anim 2, 0, 94, 7, 5, 7, 5,
ax_anim 2, 0, 92, 2, 2, 2, 2,
ax_anim_terminator
sMightyenaAnims_4_3:
ax_anim 6, 0, 99, 0, 0, 0, 0,
ax_anim 2, 0, 97, -2, 0, -2, 0,
ax_anim 2, 2, 97, -3, 0, -3, 0,
ax_anim 4, 0, 97, -4, 0, -4, 0,
ax_anim 1, 0, 98, -1, 0, -1, 0,
ax_anim 1, 0, 98, 4, 0, 4, 0,
ax_anim 2, 1, 98, 6, 0, 6, 0,
ax_anim 2, 0, 98, 6, 1, 6, 1,
ax_anim 2, 0, 98, 6, 0, 6, 0,
ax_anim 2, 0, 98, 6, 1, 6, 1,
ax_anim 2, 0, 98, 6, 0, 6, 0,
ax_anim 2, 0, 98, 6, 1, 6, 1,
ax_anim 2, 0, 96, 2, 0, 2, 0,
ax_anim_terminator
sMightyenaAnims_4_4:
ax_anim 6, 0, 103, 0, 0, 0, 0,
ax_anim 2, 0, 101, -1, 1, -1, 1,
ax_anim 2, 2, 101, -3, 3, -3, 3,
ax_anim 4, 0, 101, -4, 4, -4, 4,
ax_anim 1, 0, 102, -1, 1, -1, 1,
ax_anim 1, 0, 102, 4, -4, 4, -4,
ax_anim 2, 1, 102, 6, -6, 6, -6,
ax_anim 2, 0, 102, 7, -5, 7, -5,
ax_anim 2, 0, 102, 6, -6, 6, -6,
ax_anim 2, 0, 102, 7, -5, 7, -5,
ax_anim 2, 0, 102, 6, -6, 6, -6,
ax_anim 2, 0, 102, 7, -5, 7, -5,
ax_anim 2, 0, 100, 2, -2, 2, -2,
ax_anim_terminator
sMightyenaAnims_4_5:
ax_anim 6, 0, 107, 0, 0, 0, 0,
ax_anim 2, 0, 105, 0, 1, 0, 1,
ax_anim 2, 2, 105, 0, 3, 0, 3,
ax_anim 4, 0, 105, 0, 4, 0, 4,
ax_anim 1, 0, 106, 0, 1, 0, 1,
ax_anim 1, 0, 106, 0, -4, 0, -4,
ax_anim 2, 1, 106, 0, -6, 0, -5,
ax_anim 2, 0, 106, 1, -6, 1, -5,
ax_anim 2, 0, 106, 0, -6, 0, -5,
ax_anim 2, 0, 106, 1, -6, 1, -5,
ax_anim 2, 0, 106, 0, -6, 0, -5,
ax_anim 2, 0, 106, 1, -6, 1, -5,
ax_anim 2, 0, 104, 0, -2, 0, -2,
ax_anim_terminator
sMightyenaAnims_4_6:
ax_anim 6, 0, 111, 0, 0, 0, 0,
ax_anim 2, 0, 109, 1, 1, 1, 1,
ax_anim 2, 2, 109, 3, 3, 3, 3,
ax_anim 4, 0, 109, 4, 4, 4, 4,
ax_anim 1, 0, 110, 1, 1, 1, 1,
ax_anim 1, 0, 110, -4, -4, -4, -4,
ax_anim 2, 1, 110, -6, -6, -6, -6,
ax_anim 2, 0, 110, -7, -5, -7, -5,
ax_anim 2, 0, 110, -6, -6, -6, -6,
ax_anim 2, 0, 110, -7, -5, -7, -5,
ax_anim 2, 0, 110, -6, -6, -6, -6,
ax_anim 2, 0, 110, -7, -5, -7, -5,
ax_anim 2, 0, 108, -2, -2, -2, -2,
ax_anim_terminator
sMightyenaAnims_4_7:
ax_anim 6, 0, 115, 0, 0, 0, 0,
ax_anim 2, 0, 113, 2, 0, 2, 0,
ax_anim 2, 2, 113, 3, 0, 3, 0,
ax_anim 4, 0, 113, 4, 0, 4, 0,
ax_anim 1, 0, 114, 1, 0, 1, 0,
ax_anim 1, 0, 114, -4, 0, -4, 0,
ax_anim 2, 1, 114, -6, 0, -6, 0,
ax_anim 2, 0, 114, -6, 1, -6, 1,
ax_anim 2, 0, 114, -6, 0, -6, 0,
ax_anim 2, 0, 114, -6, 1, -6, 1,
ax_anim 2, 0, 114, -6, 0, -6, 0,
ax_anim 2, 0, 114, -6, 1, -6, 1,
ax_anim 2, 0, 112, -2, 0, -2, 0,
ax_anim_terminator
sMightyenaAnims_4_8:
ax_anim 6, 0, 119, 0, 0, 0, 0,
ax_anim 2, 0, 117, 2, -2, 2, -2,
ax_anim 2, 2, 117, 3, -3, 3, -3,
ax_anim 4, 0, 117, 4, -4, 4, -4,
ax_anim 1, 0, 118, 1, -1, 1, -1,
ax_anim 1, 0, 118, -4, 4, -4, 4,
ax_anim 2, 1, 118, -6, 6, -6, 6,
ax_anim 2, 0, 118, -7, 5, -7, 5,
ax_anim 2, 0, 118, -6, 6, -6, 6,
ax_anim 2, 0, 118, -7, 5, -7, 5,
ax_anim 2, 0, 118, -6, 6, -6, 6,
ax_anim 2, 0, 118, -7, 5, -7, 5,
ax_anim 2, 0, 116, -2, 2, -2, 2,
ax_anim_terminator
.align 2
sMightyenaAnims_5_1:
ax_anim 10, 0, 120, 0, 0, 0, 0,
ax_anim 6, 2, 121, 0, 1, 1, 0,
ax_anim 2, 0, 121, -1, 1, 0, 0,
ax_anim 2, 0, 121, 0, 1, 1, 0,
ax_anim 2, 0, 121, -1, 1, 0, 0,
ax_anim 2, 0, 121, 0, 1, 1, 0,
ax_anim 2, 0, 121, -1, 1, 0, 0,
ax_anim 2, 0, 121, 0, 1, 1, 0,
ax_anim_terminator
sMightyenaAnims_5_2:
ax_anim 10, 0, 122, 0, 0, 0, 0,
ax_anim 6, 2, 123, 2, 1, 1, -1,
ax_anim 2, 0, 123, 1, 2, 0, 0,
ax_anim 2, 0, 123, 2, 1, 1, -1,
ax_anim 2, 0, 123, 1, 2, 0, 0,
ax_anim 2, 0, 123, 2, 1, 1, -1,
ax_anim 2, 0, 123, 1, 2, 0, 0,
ax_anim 2, 0, 123, 2, 1, 1, -1,
ax_anim_terminator
sMightyenaAnims_5_3:
ax_anim 10, 0, 124, 0, 0, 0, 0,
ax_anim 6, 2, 125, 3, 0, 0, 1,
ax_anim 2, 0, 125, 3, -1, 0, 0,
ax_anim 2, 0, 125, 3, 0, 0, 1,
ax_anim 2, 0, 125, 3, -1, 0, 0,
ax_anim 2, 0, 125, 3, 0, 0, 1,
ax_anim 2, 0, 125, 3, -1, 0, 0,
ax_anim 2, 0, 125, 3, 0, 0, 1,
ax_anim_terminator
sMightyenaAnims_5_4:
ax_anim 10, 0, 126, 0, 0, 0, 0,
ax_anim 6, 2, 127, 0, -1, 1, 1,
ax_anim 2, 0, 127, -1, -2, 0, 0,
ax_anim 2, 0, 127, 0, -1, 1, 1,
ax_anim 2, 0, 127, -1, -2, 0, 0,
ax_anim 2, 0, 127, 0, -1, 1, 1,
ax_anim 2, 0, 127, -1, -2, 0, 0,
ax_anim 2, 0, 127, 0, -1, 1, 1,
ax_anim_terminator
sMightyenaAnims_5_5:
ax_anim 10, 0, 128, 0, 0, 0, 0,
ax_anim 6, 2, 129, 0, -1, 1, 0,
ax_anim 2, 0, 129, -1, -1, 0, 0,
ax_anim 2, 0, 129, 0, -1, 1, 0,
ax_anim 2, 0, 129, -1, -1, 0, 0,
ax_anim 2, 0, 129, 0, -1, 1, 0,
ax_anim 2, 0, 129, -1, -1, 0, 0,
ax_anim 2, 0, 129, 0, -1, 1, 0,
ax_anim_terminator
sMightyenaAnims_5_6:
ax_anim 10, 0, 130, 0, 0, 0, 0,
ax_anim 6, 2, 131, 0, -1, -1, 1,
ax_anim 2, 0, 131, 1, -2, 0, 0,
ax_anim 2, 0, 131, 0, -1, -1, 1,
ax_anim 2, 0, 131, 1, -2, 0, 0,
ax_anim 2, 0, 131, 0, -1, -1, 1,
ax_anim 2, 0, 131, 1, -2, 0, 0,
ax_anim 2, 0, 131, 0, -1, -1, 1,
ax_anim_terminator
sMightyenaAnims_5_7:
ax_anim 10, 0, 132, 0, 0, 0, 0,
ax_anim 6, 2, 133, -2, 0, 0, 1,
ax_anim 2, 0, 133, -2, -1, 0, 0,
ax_anim 2, 0, 133, -2, 0, 0, 1,
ax_anim 2, 0, 133, -2, -1, 0, 0,
ax_anim 2, 0, 133, -2, 0, 0, 1,
ax_anim 2, 0, 133, -2, -1, 0, 0,
ax_anim 2, 0, 133, -2, 0, 0, 1,
ax_anim_terminator
sMightyenaAnims_5_8:
ax_anim 10, 0, 134, 0, 0, 0, 0,
ax_anim 6, 2, 135, -2, 1, -1, -1,
ax_anim 2, 0, 135, -1, 2, 0, 0,
ax_anim 2, 0, 135, -2, 1, -1, -1,
ax_anim 2, 0, 135, -1, 2, 0, 0,
ax_anim 2, 0, 135, -2, 1, -1, -1,
ax_anim 2, 0, 135, -1, 2, 0, 0,
ax_anim 2, 0, 135, -2, 1, -1, -1,
ax_anim_terminator
.align 2
sMightyenaAnims_6_1:
ax_anim 30, 0, 136, 0, 0, 0, 0,
ax_anim 35, 0, 137, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sMightyenaAnims_7_1:
ax_anim 2, 0, 138, 0, -4, 0, -4,
ax_anim 8, 0, 138, 0, -5, 0, -5,
ax_anim_terminator
sMightyenaAnims_7_2:
ax_anim 2, 0, 139, -4, -4, -4, -4,
ax_anim 8, 0, 139, -5, -5, -5, -5,
ax_anim_terminator
sMightyenaAnims_7_3:
ax_anim 2, 0, 140, -4, 0, -4, 0,
ax_anim 8, 0, 140, -5, 0, -5, 0,
ax_anim_terminator
sMightyenaAnims_7_4:
ax_anim 2, 0, 141, -4, 4, -4, 4,
ax_anim 8, 0, 141, -5, 5, -5, 5,
ax_anim_terminator
sMightyenaAnims_7_5:
ax_anim 2, 0, 142, 0, 4, 0, 4,
ax_anim 8, 0, 142, 0, 5, 0, 5,
ax_anim_terminator
sMightyenaAnims_7_6:
ax_anim 2, 0, 143, 4, 4, 4, 4,
ax_anim 8, 0, 143, 5, 5, 5, 5,
ax_anim_terminator
sMightyenaAnims_7_7:
ax_anim 2, 0, 144, 4, 0, 4, 0,
ax_anim 8, 0, 144, 5, 0, 5, 0,
ax_anim_terminator
sMightyenaAnims_7_8:
ax_anim 2, 0, 145, 4, -4, 4, -4,
ax_anim 8, 0, 145, 5, -5, 5, -5,
ax_anim_terminator
.align 2
sMightyenaAnims_8_1:
ax_anim 40, 0, 149, 0, 0, 0, 0,
ax_anim 8, 0, 148, 0, 2, 0, 2,
ax_anim 5, 0, 146, 0, 2, 0, 2,
ax_anim 8, 0, 148, 0, 2, 0, 2,
ax_anim 5, 0, 146, 0, 2, 0, 2,
ax_anim 8, 0, 148, 0, 2, 0, 2,
ax_anim_terminator
sMightyenaAnims_8_2:
ax_anim 40, 0, 153, 0, 0, 0, 0,
ax_anim 8, 0, 152, 1, 1, 1, 1,
ax_anim 5, 0, 150, 1, 1, 1, 1,
ax_anim 8, 0, 152, 1, 1, 1, 1,
ax_anim 5, 0, 150, 1, 1, 1, 1,
ax_anim 8, 0, 152, 1, 1, 1, 1,
ax_anim_terminator
sMightyenaAnims_8_3:
ax_anim 40, 0, 157, 0, 0, 0, 0,
ax_anim 8, 0, 156, 3, 0, 3, 0,
ax_anim 5, 0, 154, 3, 0, 3, 0,
ax_anim 8, 0, 156, 3, 0, 3, 0,
ax_anim 5, 0, 154, 3, 0, 3, 0,
ax_anim 8, 0, 156, 3, 0, 3, 0,
ax_anim_terminator
sMightyenaAnims_8_4:
ax_anim 40, 0, 161, 0, 0, 0, 0,
ax_anim 8, 0, 160, 1, -1, 1, -1,
ax_anim 5, 0, 158, 1, -1, 1, -1,
ax_anim 8, 0, 160, 1, -1, 1, -1,
ax_anim 5, 0, 158, 1, -1, 1, -1,
ax_anim 8, 0, 160, 1, -1, 1, -1,
ax_anim_terminator
sMightyenaAnims_8_5:
ax_anim 40, 0, 165, 0, 0, 0, 0,
ax_anim 8, 0, 164, 0, -1, 0, -1,
ax_anim 5, 0, 162, 0, -1, 0, -1,
ax_anim 8, 0, 164, 0, -1, 0, -1,
ax_anim 5, 0, 162, 0, -1, 0, -1,
ax_anim 8, 0, 164, 0, -1, 0, -1,
ax_anim_terminator
sMightyenaAnims_8_6:
ax_anim 40, 0, 169, 0, 0, 0, 0,
ax_anim 8, 0, 168, -1, -1, -1, -1,
ax_anim 5, 0, 166, -1, -1, -1, -1,
ax_anim 8, 0, 168, -1, -1, -1, -1,
ax_anim 5, 0, 166, -1, -1, -1, -1,
ax_anim 8, 0, 168, -1, -1, -1, -1,
ax_anim_terminator
sMightyenaAnims_8_7:
ax_anim 40, 0, 173, 0, 0, 0, 0,
ax_anim 8, 0, 172, -3, 0, -3, 0,
ax_anim 5, 0, 170, -3, 0, -3, 0,
ax_anim 8, 0, 172, -3, 0, -3, 0,
ax_anim 5, 0, 170, -3, 0, -3, 0,
ax_anim 8, 0, 172, -3, 0, -3, 0,
ax_anim_terminator
sMightyenaAnims_8_8:
ax_anim 40, 0, 177, 0, 0, 0, 0,
ax_anim 8, 0, 176, -1, 1, -1, 1,
ax_anim 5, 0, 174, -1, 1, -1, 1,
ax_anim 8, 0, 176, -1, 1, -1, 1,
ax_anim 5, 0, 174, -1, 1, -1, 1,
ax_anim 8, 0, 176, -1, 1, -1, 1,
ax_anim_terminator
.align 2
sMightyenaAnims_9_1:
ax_anim 2, 0, 178, 0, 0, 0, 0,
ax_anim 1, 0, 179, 10, 1, 10, 1,
ax_anim 2, 0, 180, 15, 8, 15, 8,
ax_anim 2, 0, 181, 9, 15, 9, 15,
ax_anim 3, 0, 182, 0, 17, 0, 17,
ax_anim 2, 3, 183, -9, 15, -9, 15,
ax_anim 2, 0, 184, -15, 8, -15, 8,
ax_anim 1, 0, 185, -10, 1, -10, 1,
ax_anim 1, 0, 178, 0, 0, 0, 0,
ax_anim_terminator
sMightyenaAnims_9_2:
ax_anim 2, 0, 185, 0, 0, 0, 0,
ax_anim 1, 0, 178, 11, 1, 11, 1,
ax_anim 2, 0, 179, 19, 2, 19, 2,
ax_anim 2, 0, 180, 23, 9, 23, 9,
ax_anim 3, 0, 181, 19, 17, 19, 17,
ax_anim 2, 3, 182, 11, 17, 11, 17,
ax_anim 2, 0, 183, 4, 15, 4, 15,
ax_anim 1, 0, 184, -3, 8, -3, 8,
ax_anim 1, 0, 185, 0, 0, 0, 0,
ax_anim_terminator
sMightyenaAnims_9_3:
ax_anim 2, 0, 184, 0, 0, 0, 0,
ax_anim 1, 0, 185, 2, -4, 2, -4,
ax_anim 2, 0, 178, 11, -5, 11, -5,
ax_anim 2, 0, 179, 17, -4, 17, -4,
ax_anim 3, 0, 180, 19, 1, 19, 1,
ax_anim 2, 3, 181, 14, 8, 14, 8,
ax_anim 2, 0, 182, 11, 8, 11, 8,
ax_anim 1, 0, 183, 4, 7, 4, 7,
ax_anim 1, 0, 184, 0, 0, 0, 0,
ax_anim_terminator
sMightyenaAnims_9_4:
ax_anim 2, 0, 183, 0, 0, 0, 0,
ax_anim 1, 0, 184, -4, -8, -4, -8,
ax_anim 2, 0, 185, 0, -16, 0, -16,
ax_anim 2, 0, 178, 10, -19, 10, -19,
ax_anim 3, 0, 179, 20, -21, 20, -21,
ax_anim 2, 3, 180, 24, -11, 24, -11,
ax_anim 2, 0, 181, 17, -2, 17, -2,
ax_anim 1, 0, 182, 11, -1, 11, -1,
ax_anim 1, 0, 183, 0, 0, 0, 0,
ax_anim_terminator
sMightyenaAnims_9_5:
ax_anim 2, 0, 182, 0, 0, 0, 0,
ax_anim 1, 0, 183, -10, -4, -10, -4,
ax_anim 2, 0, 184, -15, -11, -15, -11,
ax_anim 2, 0, 185, -11, -18, -11, -18,
ax_anim 3, 0, 178, 0, -21, 0, -21,
ax_anim 2, 3, 179, 11, -18, 11, -18,
ax_anim 2, 0, 180, 15, -11, 15, -11,
ax_anim 1, 0, 181, 10, -4, 10, -4,
ax_anim 1, 0, 182, 0, 0, 0, 0,
ax_anim_terminator
sMightyenaAnims_9_6:
ax_anim 2, 0, 181, 0, 0, 0, 0,
ax_anim 1, 0, 180, 4, -8, 4, -8,
ax_anim 2, 0, 179, 0, -16, 0, -16,
ax_anim 2, 0, 178, -10, -19, -10, -19,
ax_anim 3, 0, 185, -20, -21, -20, -21,
ax_anim 2, 3, 184, -24, -11, -24, -11,
ax_anim 2, 0, 183, -17, -2, -17, -2,
ax_anim 1, 0, 182, -11, -1, -11, -1,
ax_anim 1, 0, 181, 0, 0, 0, 0,
ax_anim_terminator
sMightyenaAnims_9_7:
ax_anim 2, 0, 180, 0, 0, 0, 0,
ax_anim 1, 0, 179, -2, -4, -2, -4,
ax_anim 2, 0, 178, -11, -5, -11, -5,
ax_anim 2, 0, 185, -17, -4, -17, -4,
ax_anim 3, 0, 184, -19, 1, -19, 1,
ax_anim 2, 3, 183, -14, 8, -14, 8,
ax_anim 2, 0, 182, -11, 8, -11, 8,
ax_anim 1, 0, 181, -4, 7, -4, 7,
ax_anim 1, 0, 180, 0, 0, 0, 0,
ax_anim_terminator
sMightyenaAnims_9_8:
ax_anim 2, 0, 179, 0, 0, 0, 0,
ax_anim 1, 0, 178, -11, -1, -11, -1,
ax_anim 2, 0, 185, -19, 2, -19, 2,
ax_anim 2, 0, 184, -23, 9, -23, 9,
ax_anim 3, 0, 183, -19, 17, -19, 17,
ax_anim 2, 3, 182, -11, 17, -11, 17,
ax_anim 2, 0, 181, -4, 15, -4, 15,
ax_anim 1, 0, 180, 3, 8, 3, 8,
ax_anim 1, 0, 179, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sMightyenaAnims_10_1:
ax_anim 2, 0, 186, 0, 0, 0, 0,
ax_anim 2, 0, 186, 6, 0, 6, 0,
ax_anim 2, 0, 186, -6, 0, -6, 0,
ax_anim 2, 0, 186, 10, 0, 10, 0,
ax_anim 2, 0, 186, -10, 0, -10, 0,
ax_anim 2, 0, 186, 12, 0, 12, 0,
ax_anim 3, 0, 186, -12, 0, -12, 0,
ax_anim 3, 0, 186, 13, 0, 13, 0,
ax_anim 3, 0, 186, -13, 0, -13, 0,
ax_anim 2, 0, 186, 12, 0, 12, 0,
ax_anim 3, 0, 186, -12, 0, -12, 0,
ax_anim 2, 0, 186, 10, 0, 10, 0,
ax_anim 2, 0, 186, -10, 0, -10, 0,
ax_anim 2, 0, 186, 6, 0, 6, 0,
ax_anim 2, 0, 186, -6, 0, -6, 0,
ax_anim 2, 0, 186, 0, 0, 0, 0,
ax_anim_terminator
sMightyenaAnims_10_2:
ax_anim 2, 0, 187, 0, 0, 0, 0,
ax_anim 2, 0, 187, 6, -6, 6, -6,
ax_anim 2, 0, 187, -6, 6, -6, 6,
ax_anim 2, 0, 187, 10, -10, 10, -10,
ax_anim 2, 0, 187, -10, 10, -10, 10,
ax_anim 2, 0, 187, 12, -12, 12, -12,
ax_anim 3, 0, 187, -12, 12, -12, 12,
ax_anim 3, 0, 187, 13, -13, 13, -13,
ax_anim 3, 0, 187, -13, 13, -13, 13,
ax_anim 2, 0, 187, 12, -12, 12, -12,
ax_anim 3, 0, 187, -12, 12, -12, 12,
ax_anim 2, 0, 187, 10, -10, 10, -10,
ax_anim 2, 0, 187, -10, 10, -10, 10,
ax_anim 2, 0, 187, 6, -6, 6, -6,
ax_anim 2, 0, 187, -6, 6, -6, 6,
ax_anim 2, 0, 187, 0, 0, 0, 0,
ax_anim_terminator
sMightyenaAnims_10_3:
ax_anim 2, 0, 188, 0, 0, 0, 0,
ax_anim 2, 0, 188, 0, -6, 0, -6,
ax_anim 2, 0, 188, 0, 6, 0, 6,
ax_anim 2, 0, 188, 0, -10, 0, -10,
ax_anim 2, 0, 188, 0, 10, 0, 10,
ax_anim 2, 0, 188, 0, -12, 0, -12,
ax_anim 3, 0, 188, 0, 12, 0, 12,
ax_anim 3, 0, 188, 0, -13, 0, -13,
ax_anim 3, 0, 188, 0, 13, 0, 13,
ax_anim 2, 0, 188, 0, -12, 0, -12,
ax_anim 3, 0, 188, 0, 12, 0, 12,
ax_anim 2, 0, 188, 0, -10, 0, -10,
ax_anim 2, 0, 188, 0, 10, 0, 10,
ax_anim 2, 0, 188, 0, -6, 0, -6,
ax_anim 2, 0, 188, 0, 6, 0, 6,
ax_anim 2, 0, 188, 0, 0, 0, 0,
ax_anim_terminator
sMightyenaAnims_10_4:
ax_anim 2, 0, 189, 0, 0, 0, 0,
ax_anim 2, 0, 189, -6, -6, -6, -6,
ax_anim 2, 0, 189, 6, 6, 6, 6,
ax_anim 2, 0, 189, -10, -10, -10, -10,
ax_anim 2, 0, 189, 10, 10, 10, 10,
ax_anim 2, 0, 189, -12, -12, -12, -12,
ax_anim 3, 0, 189, 12, 12, 12, 12,
ax_anim 3, 0, 189, -13, -13, -13, -13,
ax_anim 3, 0, 189, 13, 13, 13, 13,
ax_anim 2, 0, 189, -12, -12, -12, -12,
ax_anim 3, 0, 189, 12, 12, 12, 12,
ax_anim 2, 0, 189, -10, -10, -10, -10,
ax_anim 2, 0, 189, 10, 10, 10, 10,
ax_anim 2, 0, 189, -6, -6, -6, -6,
ax_anim 2, 0, 189, 6, 6, 6, 6,
ax_anim 2, 0, 189, 0, 0, 0, 0,
ax_anim_terminator
sMightyenaAnims_10_5:
ax_anim 2, 0, 190, 0, 0, 0, 0,
ax_anim 2, 0, 190, 6, 0, 6, 0,
ax_anim 2, 0, 190, -6, 0, -6, 0,
ax_anim 2, 0, 190, 10, 0, 10, 0,
ax_anim 2, 0, 190, -10, 0, -10, 0,
ax_anim 2, 0, 190, 12, 0, 12, 0,
ax_anim 3, 0, 190, -12, 0, -12, 0,
ax_anim 3, 0, 190, 13, 0, 13, 0,
ax_anim 3, 0, 190, -13, 0, -13, 0,
ax_anim 2, 0, 190, 12, 0, 12, 0,
ax_anim 3, 0, 190, -12, 0, -12, 0,
ax_anim 2, 0, 190, 10, 0, 10, 0,
ax_anim 2, 0, 190, -10, 0, -10, 0,
ax_anim 2, 0, 190, 6, 0, 6, 0,
ax_anim 2, 0, 190, -6, 0, -6, 0,
ax_anim 2, 0, 190, 0, 0, 0, 0,
ax_anim_terminator
sMightyenaAnims_10_6:
ax_anim 2, 0, 191, 0, 0, 0, 0,
ax_anim 2, 0, 191, 6, -6, 6, -6,
ax_anim 2, 0, 191, -6, 6, -6, 6,
ax_anim 2, 0, 191, 10, -10, 10, -10,
ax_anim 2, 0, 191, -10, 10, -10, 10,
ax_anim 2, 0, 191, 12, -12, 12, -12,
ax_anim 3, 0, 191, -12, 12, -12, 12,
ax_anim 3, 0, 191, 13, -13, 13, -13,
ax_anim 3, 0, 191, -13, 13, -13, 13,
ax_anim 2, 0, 191, 12, -12, 12, -12,
ax_anim 3, 0, 191, -12, 12, -12, 12,
ax_anim 2, 0, 191, 10, -10, 10, -10,
ax_anim 2, 0, 191, -10, 10, -10, 10,
ax_anim 2, 0, 191, 6, -6, 6, -6,
ax_anim 2, 0, 191, -6, 6, -6, 6,
ax_anim 2, 0, 191, 0, 0, 0, 0,
ax_anim_terminator
sMightyenaAnims_10_7:
ax_anim 2, 0, 192, 0, 0, 0, 0,
ax_anim 2, 0, 192, 0, -6, 0, -6,
ax_anim 2, 0, 192, 0, 6, 0, 6,
ax_anim 2, 0, 192, 0, -10, 0, -10,
ax_anim 2, 0, 192, 0, 10, 0, 10,
ax_anim 2, 0, 192, 0, -12, 0, -12,
ax_anim 3, 0, 192, 0, 12, 0, 12,
ax_anim 3, 0, 192, 0, -13, 0, -13,
ax_anim 3, 0, 192, 0, 13, 0, 13,
ax_anim 2, 0, 192, 0, -12, 0, -12,
ax_anim 3, 0, 192, 0, 12, 0, 12,
ax_anim 2, 0, 192, 0, -10, 0, -10,
ax_anim 2, 0, 192, 0, 10, 0, 10,
ax_anim 2, 0, 192, 0, -6, 0, -6,
ax_anim 2, 0, 192, 0, 6, 0, 6,
ax_anim 2, 0, 192, 0, 0, 0, 0,
ax_anim_terminator
sMightyenaAnims_10_8:
ax_anim 2, 0, 193, 0, 0, 0, 0,
ax_anim 2, 0, 193, -6, -6, -6, -6,
ax_anim 2, 0, 193, 6, 6, 6, 6,
ax_anim 2, 0, 193, -10, -10, -10, -10,
ax_anim 2, 0, 193, 10, 10, 10, 10,
ax_anim 2, 0, 193, -12, -12, -12, -12,
ax_anim 3, 0, 193, 12, 12, 12, 12,
ax_anim 3, 0, 193, -13, -13, -13, -13,
ax_anim 3, 0, 193, 13, 13, 13, 13,
ax_anim 2, 0, 193, -12, -12, -12, -12,
ax_anim 3, 0, 193, 12, 12, 12, 12,
ax_anim 2, 0, 193, -10, -10, -10, -10,
ax_anim 2, 0, 193, 10, 10, 10, 10,
ax_anim 2, 0, 193, -6, -6, -6, -6,
ax_anim 2, 0, 193, 6, 6, 6, 6,
ax_anim 2, 0, 193, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sMightyenaAnims_11_1:
ax_anim 2, 0, 194, 0, 0, 0, 0,
ax_anim 1, 0, 196, 0, -10, 0, 0,
ax_anim 2, 0, 196, 0, -16, 0, 0,
ax_anim 3, 0, 196, 0, -20, 0, 0,
ax_anim 4, 0, 196, 0, -21, 0, 0,
ax_anim 4, 0, 194, 0, -24, 0, 0,
ax_anim 3, 0, 195, 0, -24, 0, 0,
ax_anim 2, 0, 195, 0, -19, 0, 0,
ax_anim 1, 0, 195, 0, -12, 0, 0,
ax_anim 2, 2, 195, 0, 0, 0, 0,
ax_anim_terminator
sMightyenaAnims_11_2:
ax_anim 2, 0, 197, 0, 0, 0, 0,
ax_anim 1, 0, 199, 0, -10, 0, 0,
ax_anim 2, 0, 199, 0, -16, 0, 0,
ax_anim 3, 0, 199, 0, -20, 0, 0,
ax_anim 4, 0, 199, 0, -21, 0, 0,
ax_anim 4, 0, 197, 0, -23, 0, 0,
ax_anim 3, 0, 198, 0, -23, 0, 0,
ax_anim 2, 0, 198, 0, -18, 0, 0,
ax_anim 1, 0, 198, 0, -12, 0, 0,
ax_anim 2, 2, 198, 0, 0, 0, 0,
ax_anim_terminator
sMightyenaAnims_11_3:
ax_anim 2, 0, 200, 0, 0, 0, 0,
ax_anim 1, 0, 202, 0, -10, 0, 0,
ax_anim 2, 0, 202, 0, -16, 0, 0,
ax_anim 3, 0, 202, 0, -20, 0, 0,
ax_anim 4, 0, 202, 0, -21, 0, 0,
ax_anim 4, 0, 200, 0, -23, 0, 0,
ax_anim 3, 0, 201, 0, -22, 0, 0,
ax_anim 2, 0, 201, 0, -18, 0, 0,
ax_anim 1, 0, 201, 0, -12, 0, 0,
ax_anim 2, 2, 201, 0, 0, 0, 0,
ax_anim_terminator
sMightyenaAnims_11_4:
ax_anim 2, 0, 203, 0, 0, 0, 0,
ax_anim 1, 0, 205, 0, -10, 0, 0,
ax_anim 2, 0, 205, 0, -16, 0, 0,
ax_anim 3, 0, 205, 0, -20, 0, 0,
ax_anim 4, 0, 205, 0, -21, 0, 0,
ax_anim 4, 0, 203, 0, -23, 0, 0,
ax_anim 3, 0, 204, 0, -19, 0, 0,
ax_anim 2, 0, 204, 0, -17, 0, 0,
ax_anim 1, 0, 204, 0, -11, 0, 0,
ax_anim 2, 2, 204, 0, 0, 0, 0,
ax_anim_terminator
sMightyenaAnims_11_5:
ax_anim 2, 0, 206, 0, 0, 0, 0,
ax_anim 1, 0, 208, 0, -10, 0, 0,
ax_anim 2, 0, 208, 0, -16, 0, 0,
ax_anim 3, 0, 208, 0, -20, 0, 0,
ax_anim 4, 0, 208, 0, -21, 0, 0,
ax_anim 4, 0, 206, 0, -23, 0, 0,
ax_anim 3, 0, 207, 0, -21, 0, 0,
ax_anim 2, 0, 207, 0, -17, 0, 0,
ax_anim 1, 0, 207, 0, -12, 0, 0,
ax_anim 2, 2, 207, 0, 0, 0, 0,
ax_anim_terminator
sMightyenaAnims_11_6:
ax_anim 2, 0, 209, 0, 0, 0, 0,
ax_anim 1, 0, 211, 0, -10, 0, 0,
ax_anim 2, 0, 211, 0, -16, 0, 0,
ax_anim 3, 0, 211, 0, -20, 0, 0,
ax_anim 4, 0, 211, 0, -21, 0, 0,
ax_anim 4, 0, 209, 0, -23, 0, 0,
ax_anim 3, 0, 210, 0, -19, 0, 0,
ax_anim 2, 0, 210, 0, -17, 0, 0,
ax_anim 1, 0, 210, 0, -11, 0, 0,
ax_anim 2, 2, 210, 0, 0, 0, 0,
ax_anim_terminator
sMightyenaAnims_11_7:
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 1, 0, 214, 0, -10, 0, 0,
ax_anim 2, 0, 214, 0, -16, 0, 0,
ax_anim 3, 0, 214, 0, -20, 0, 0,
ax_anim 4, 0, 214, 0, -21, 0, 0,
ax_anim 4, 0, 212, 0, -23, 0, 0,
ax_anim 3, 0, 213, 0, -22, 0, 0,
ax_anim 2, 0, 213, 0, -18, 0, 0,
ax_anim 1, 0, 213, 0, -12, 0, 0,
ax_anim 2, 2, 213, 0, 0, 0, 0,
ax_anim_terminator
sMightyenaAnims_11_8:
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 1, 0, 217, 0, -10, 0, 0,
ax_anim 2, 0, 217, 0, -16, 0, 0,
ax_anim 3, 0, 217, 0, -20, 0, 0,
ax_anim 4, 0, 217, 0, -21, 0, 0,
ax_anim 4, 0, 215, 0, -23, 0, 0,
ax_anim 3, 0, 216, 0, -23, 0, 0,
ax_anim 2, 0, 216, 0, -18, 0, 0,
ax_anim 1, 0, 216, 0, -12, 0, 0,
ax_anim 2, 2, 216, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sMightyenaAnims_12_1:
ax_anim 2, 0, 218, 1, 0, 1, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 218, 1, 0, 1, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 218, 1, 0, 1, 0,
ax_anim 2, 2, 218, 0, 0, 0, 0,
ax_anim 2, 0, 218, 1, 0, 1, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 218, 1, 0, 1, 0,
ax_anim 2, 1, 218, 0, 0, 0, 0,
ax_anim_terminator
sMightyenaAnims_12_2:
ax_anim 2, 0, 225, 1, -1, 1, -1,
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 2, 0, 225, 1, -1, 1, -1,
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 2, 0, 225, 1, -1, 1, -1,
ax_anim 2, 2, 225, 0, 0, 0, 0,
ax_anim 2, 0, 225, 1, -1, 1, -1,
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 2, 0, 225, 1, -1, 1, -1,
ax_anim 2, 1, 225, 0, 0, 0, 0,
ax_anim_terminator
sMightyenaAnims_12_3:
ax_anim 2, 0, 224, 0, -1, 0, -1,
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 2, 0, 224, 0, -1, 0, -1,
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 2, 0, 224, 0, -1, 0, -1,
ax_anim 2, 2, 224, 0, 0, 0, 0,
ax_anim 2, 0, 224, 0, -1, 0, -1,
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 2, 0, 224, 0, -1, 0, -1,
ax_anim 2, 1, 224, 0, 0, 0, 0,
ax_anim_terminator
sMightyenaAnims_12_4:
ax_anim 2, 0, 223, -1, -1, -1, -1,
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 2, 0, 223, -1, -1, -1, -1,
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 2, 0, 223, -1, -1, -1, -1,
ax_anim 2, 2, 223, 0, 0, 0, 0,
ax_anim 2, 0, 223, -1, -1, -1, -1,
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 2, 0, 223, -1, -1, -1, -1,
ax_anim 2, 1, 223, 0, 0, 0, 0,
ax_anim_terminator
sMightyenaAnims_12_5:
ax_anim 2, 0, 222, 1, 0, 1, 0,
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 0, 222, 1, 0, 1, 0,
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 0, 222, 1, 0, 1, 0,
ax_anim 2, 2, 222, 0, 0, 0, 0,
ax_anim 2, 0, 222, 1, 0, 1, 0,
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 0, 222, 1, 0, 1, 0,
ax_anim 2, 1, 222, 0, 0, 0, 0,
ax_anim_terminator
sMightyenaAnims_12_6:
ax_anim 2, 0, 221, 1, -1, 1, -1,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 221, 1, -1, 1, -1,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 221, 1, -1, 1, -1,
ax_anim 2, 2, 221, 0, 0, 0, 0,
ax_anim 2, 0, 221, 1, -1, 1, -1,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 221, 1, -1, 1, -1,
ax_anim 2, 1, 221, 0, 0, 0, 0,
ax_anim_terminator
sMightyenaAnims_12_7:
ax_anim 2, 0, 220, 0, -1, 0, -1,
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, -1, 0, -1,
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, -1, 0, -1,
ax_anim 2, 2, 220, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, -1, 0, -1,
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, -1, 0, -1,
ax_anim 2, 1, 220, 0, 0, 0, 0,
ax_anim_terminator
sMightyenaAnims_12_8:
ax_anim 2, 0, 219, -1, -1, -1, -1,
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 0, 219, -1, -1, -1, -1,
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 0, 219, -1, -1, -1, -1,
ax_anim 2, 2, 219, 0, 0, 0, 0,
ax_anim 2, 0, 219, -1, -1, -1, -1,
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 0, 219, -1, -1, -1, -1,
ax_anim 2, 1, 219, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sMightyenaAnims_13_1:
ax_anim 2, 0, 226, 0, 0, 0, 0,
ax_anim 2, 0, 227, 0, 0, 0, 0,
ax_anim 2, 0, 228, 0, 0, 0, 0,
ax_anim 2, 0, 229, 0, 0, 0, 0,
ax_anim 2, 0, 230, 0, 0, 0, 0,
ax_anim 2, 0, 231, 0, 0, 0, 0,
ax_anim 2, 0, 232, 0, 0, 0, 0,
ax_anim 2, 0, 233, 0, 0, 0, 0,
ax_anim 2, 2, 226, 0, 0, 0, 0,
ax_anim_terminator
sMightyenaAnims_13_2:
ax_anim 2, 0, 233, 0, 0, 0, 0,
ax_anim 2, 0, 226, 0, 0, 0, 0,
ax_anim 2, 0, 227, 0, 0, 0, 0,
ax_anim 2, 0, 228, 0, 0, 0, 0,
ax_anim 2, 0, 229, 0, 0, 0, 0,
ax_anim 2, 0, 230, 0, 0, 0, 0,
ax_anim 2, 0, 231, 0, 0, 0, 0,
ax_anim 2, 0, 232, 0, 0, 0, 0,
ax_anim 2, 2, 233, 0, 0, 0, 0,
ax_anim_terminator
sMightyenaAnims_13_3:
ax_anim 2, 0, 232, 0, 0, 0, 0,
ax_anim 2, 0, 233, 0, 0, 0, 0,
ax_anim 2, 0, 226, 0, 0, 0, 0,
ax_anim 2, 0, 227, 0, 0, 0, 0,
ax_anim 2, 0, 228, 0, 0, 0, 0,
ax_anim 2, 0, 229, 0, 0, 0, 0,
ax_anim 2, 0, 230, 0, 0, 0, 0,
ax_anim 2, 0, 231, 0, 0, 0, 0,
ax_anim 2, 2, 232, 0, 0, 0, 0,
ax_anim_terminator
sMightyenaAnims_13_4:
ax_anim 2, 0, 231, 0, 0, 0, 0,
ax_anim 2, 0, 232, 0, 0, 0, 0,
ax_anim 2, 0, 233, 0, 0, 0, 0,
ax_anim 2, 0, 226, 0, 0, 0, 0,
ax_anim 2, 0, 227, 0, 0, 0, 0,
ax_anim 2, 0, 228, 0, 0, 0, 0,
ax_anim 2, 0, 229, 0, 0, 0, 0,
ax_anim 2, 0, 230, 0, 0, 0, 0,
ax_anim 2, 2, 231, 0, 0, 0, 0,
ax_anim_terminator
sMightyenaAnims_13_5:
ax_anim 2, 0, 230, 0, 0, 0, 0,
ax_anim 2, 0, 231, 0, 0, 0, 0,
ax_anim 2, 0, 232, 0, 0, 0, 0,
ax_anim 2, 0, 233, 0, 0, 0, 0,
ax_anim 2, 0, 226, 0, 0, 0, 0,
ax_anim 2, 0, 227, 0, 0, 0, 0,
ax_anim 2, 0, 228, 0, 0, 0, 0,
ax_anim 2, 0, 229, 0, 0, 0, 0,
ax_anim 2, 2, 230, 0, 0, 0, 0,
ax_anim_terminator
sMightyenaAnims_13_6:
ax_anim 2, 0, 229, 0, 0, 0, 0,
ax_anim 2, 0, 230, 0, 0, 0, 0,
ax_anim 2, 0, 231, 0, 0, 0, 0,
ax_anim 2, 0, 232, 0, 0, 0, 0,
ax_anim 2, 0, 233, 0, 0, 0, 0,
ax_anim 2, 0, 226, 0, 0, 0, 0,
ax_anim 2, 0, 227, 0, 0, 0, 0,
ax_anim 2, 0, 228, 0, 0, 0, 0,
ax_anim 2, 2, 229, 0, 0, 0, 0,
ax_anim_terminator
sMightyenaAnims_13_7:
ax_anim 2, 0, 228, 0, 0, 0, 0,
ax_anim 2, 0, 229, 0, 0, 0, 0,
ax_anim 2, 0, 230, 0, 0, 0, 0,
ax_anim 2, 0, 231, 0, 0, 0, 0,
ax_anim 2, 0, 232, 0, 0, 0, 0,
ax_anim 2, 0, 233, 0, 0, 0, 0,
ax_anim 2, 0, 226, 0, 0, 0, 0,
ax_anim 2, 0, 227, 0, 0, 0, 0,
ax_anim 2, 2, 228, 0, 0, 0, 0,
ax_anim_terminator
sMightyenaAnims_13_8:
ax_anim 2, 0, 227, 0, 0, 0, 0,
ax_anim 2, 0, 228, 0, 0, 0, 0,
ax_anim 2, 0, 229, 0, 0, 0, 0,
ax_anim 2, 0, 230, 0, 0, 0, 0,
ax_anim 2, 0, 231, 0, 0, 0, 0,
ax_anim 2, 0, 232, 0, 0, 0, 0,
ax_anim 2, 0, 233, 0, 0, 0, 0,
ax_anim 2, 0, 226, 0, 0, 0, 0,
ax_anim 2, 2, 227, 0, 0, 0, 0,
ax_anim_terminator
sMightyenaGfx1:
.incbin "baserom.gba", 0x10C4FC8, 0x100
sMightyenaSprites1:
ax_sprite sMightyenaGfx1, 0x100
ax_sprite_terminator
sMightyenaGfx2:
.incbin "baserom.gba", 0x10C50D8, 0x100
sMightyenaSprites2:
ax_sprite sMightyenaGfx2, 0x100
ax_sprite_terminator
sMightyenaGfx3:
.incbin "baserom.gba", 0x10C51E8, 0x100
sMightyenaSprites3:
ax_sprite sMightyenaGfx3, 0x100
ax_sprite_terminator
sMightyenaGfx4:
.incbin "baserom.gba", 0x10C52F8, 0x200
sMightyenaSprites4:
ax_sprite sMightyenaGfx4, 0x200
ax_sprite_terminator
sMightyenaGfx5:
.incbin "baserom.gba", 0x10C5508, 0x200
sMightyenaSprites5:
ax_sprite sMightyenaGfx5, 0x200
ax_sprite_terminator
sMightyenaGfx6:
.incbin "baserom.gba", 0x10C5718, 0x200
sMightyenaSprites6:
ax_sprite sMightyenaGfx6, 0x200
ax_sprite_terminator
sMightyenaGfx7:
.incbin "baserom.gba", 0x10C5928, 0x200
sMightyenaSprites7:
ax_sprite sMightyenaGfx7, 0x200
ax_sprite_terminator
sMightyenaGfx8:
.incbin "baserom.gba", 0x10C5B38, 0x200
sMightyenaSprites8:
ax_sprite sMightyenaGfx8, 0x200
ax_sprite_terminator
sMightyenaGfx9:
.incbin "baserom.gba", 0x10C5D48, 0x200
sMightyenaSprites9:
ax_sprite sMightyenaGfx9, 0x200
ax_sprite_terminator
sMightyenaGfx10:
.incbin "baserom.gba", 0x10C5F58, 0x200
sMightyenaSprites10:
ax_sprite sMightyenaGfx10, 0x200
ax_sprite_terminator
sMightyenaGfx11:
.incbin "baserom.gba", 0x10C6168, 0x200
sMightyenaSprites11:
ax_sprite sMightyenaGfx11, 0x200
ax_sprite_terminator
sMightyenaGfx12:
.incbin "baserom.gba", 0x10C6378, 0x200
sMightyenaSprites12:
ax_sprite sMightyenaGfx12, 0x200
ax_sprite_terminator
sMightyenaGfx13:
.incbin "baserom.gba", 0x10C6588, 0x100
sMightyenaSprites13:
ax_sprite sMightyenaGfx13, 0x100
ax_sprite_terminator
sMightyenaGfx14:
.incbin "baserom.gba", 0x10C6698, 0x100
sMightyenaSprites14:
ax_sprite sMightyenaGfx14, 0x100
ax_sprite_terminator
sMightyenaGfx15:
.incbin "baserom.gba", 0x10C67A8, 0x100
sMightyenaSprites15:
ax_sprite sMightyenaGfx15, 0x100
ax_sprite_terminator
sMightyenaGfx16:
.incbin "baserom.gba", 0x10C68B8, 0x100
sMightyenaSprites16:
ax_sprite sMightyenaGfx16, 0x100
ax_sprite_terminator
sMightyenaGfx17:
.incbin "baserom.gba", 0x10C69C8, 0x100
sMightyenaSprites17:
ax_sprite sMightyenaGfx17, 0x100
ax_sprite_terminator
sMightyenaGfx18:
.incbin "baserom.gba", 0x10C6AD8, 0xC0
sMightyenaSprites18:
ax_sprite sMightyenaGfx18, 0xc0
ax_sprite 0, 0x40
ax_sprite_terminator
sMightyenaGfx19:
.incbin "baserom.gba", 0x10C6BB0, 0xE0
sMightyenaGfx19_1:
.incbin "baserom.gba", 0x10C6C90, 0x60
sMightyenaGfx19_2:
.incbin "baserom.gba", 0x10C6CF0, 0x40
sMightyenaSprites19:
ax_sprite sMightyenaGfx19, 0xe0
ax_sprite 0, 0x20
ax_sprite sMightyenaGfx19_1, 0x60
ax_sprite 0, 0x20
ax_sprite sMightyenaGfx19_2, 0x40
ax_sprite 0, 0x40
ax_sprite_terminator
sMightyenaGfx20:
.incbin "baserom.gba", 0x10C6D68, 0x20
sMightyenaGfx20_1:
.incbin "baserom.gba", 0x10C6D88, 0x20
sMightyenaGfx20_2:
.incbin "baserom.gba", 0x10C6DA8, 0x160
sMightyenaSprites20:
ax_sprite sMightyenaGfx20, 0x20
ax_sprite 0, 0x20
ax_sprite sMightyenaGfx20_1, 0x20
ax_sprite 0, 0x20
ax_sprite sMightyenaGfx20_2, 0x160
ax_sprite 0, 0x20
ax_sprite_terminator
sMightyenaGfx21:
.incbin "baserom.gba", 0x10C6F40, 0x180
sMightyenaSprites21:
ax_sprite sMightyenaGfx21, 0x180
ax_sprite 0, 0x80
ax_sprite_terminator
sMightyenaGfx22:
.incbin "baserom.gba", 0x10C70D8, 0x60
sMightyenaGfx22_1:
.incbin "baserom.gba", 0x10C7138, 0x100
sMightyenaGfx22_2:
.incbin "baserom.gba", 0x10C7238, 0x60
sMightyenaSprites22:
ax_sprite sMightyenaGfx22, 0x60
ax_sprite 0, 0x20
ax_sprite sMightyenaGfx22_1, 0x100
ax_sprite 0, 0x20
ax_sprite sMightyenaGfx22_2, 0x60
ax_sprite_terminator
sMightyenaGfx23:
.incbin "baserom.gba", 0x10C72C8, 0x160
sMightyenaGfx23_1:
.incbin "baserom.gba", 0x10C7428, 0x20
sMightyenaGfx23_2:
.incbin "baserom.gba", 0x10C7448, 0x20
sMightyenaSprites23:
ax_sprite 0, 0x20
ax_sprite sMightyenaGfx23, 0x160
ax_sprite 0, 0x20
ax_sprite sMightyenaGfx23_1, 0x20
ax_sprite 0, 0x20
ax_sprite sMightyenaGfx23_2, 0x20
ax_sprite_terminator
sMightyenaGfx24:
.incbin "baserom.gba", 0x10C74A0, 0x40
sMightyenaGfx24_1:
.incbin "baserom.gba", 0x10C74E0, 0x100
sMightyenaGfx24_2:
.incbin "baserom.gba", 0x10C75E0, 0x20
sMightyenaSprites24:
ax_sprite sMightyenaGfx24, 0x40
ax_sprite 0, 0x40
ax_sprite sMightyenaGfx24_1, 0x100
ax_sprite 0, 0x60
ax_sprite sMightyenaGfx24_2, 0x20
ax_sprite_terminator
sMightyenaGfx25:
.incbin "baserom.gba", 0x10C7630, 0x60
sMightyenaGfx25_1:
.incbin "baserom.gba", 0x10C7690, 0x60
sMightyenaGfx25_2:
.incbin "baserom.gba", 0x10C76F0, 0x60
sMightyenaGfx25_3:
.incbin "baserom.gba", 0x10C7750, 0x40
sMightyenaSprites25:
ax_sprite sMightyenaGfx25, 0x60
ax_sprite 0, 0x20
ax_sprite sMightyenaGfx25_1, 0x60
ax_sprite 0, 0x20
ax_sprite sMightyenaGfx25_2, 0x60
ax_sprite 0, 0x40
ax_sprite sMightyenaGfx25_3, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sMightyenaGfx26:
.incbin "baserom.gba", 0x10C77D8, 0x60
sMightyenaGfx26_1:
.incbin "baserom.gba", 0x10C7838, 0x60
sMightyenaGfx26_2:
.incbin "baserom.gba", 0x10C7898, 0x60
sMightyenaGfx26_3:
.incbin "baserom.gba", 0x10C78F8, 0x40
sMightyenaSprites26:
ax_sprite sMightyenaGfx26, 0x60
ax_sprite 0, 0x20
ax_sprite sMightyenaGfx26_1, 0x60
ax_sprite 0, 0x20
ax_sprite sMightyenaGfx26_2, 0x60
ax_sprite 0, 0x40
ax_sprite sMightyenaGfx26_3, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sMightyenaGfx27:
.incbin "baserom.gba", 0x10C7980, 0x40
sMightyenaGfx27_1:
.incbin "baserom.gba", 0x10C79C0, 0x60
sMightyenaGfx27_2:
.incbin "baserom.gba", 0x10C7A20, 0x80
sMightyenaGfx27_3:
.incbin "baserom.gba", 0x10C7AA0, 0x40
sMightyenaSprites27:
ax_sprite sMightyenaGfx27, 0x40
ax_sprite 0, 0x40
ax_sprite sMightyenaGfx27_1, 0x60
ax_sprite 0, 0x20
ax_sprite sMightyenaGfx27_2, 0x80
ax_sprite 0, 0x20
ax_sprite sMightyenaGfx27_3, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sMightyenaGfx28:
.incbin "baserom.gba", 0x10C7B28, 0x100
sMightyenaSprites28:
ax_sprite sMightyenaGfx28, 0x100
ax_sprite_terminator
sMightyenaGfx29:
.incbin "baserom.gba", 0x10C7C38, 0x100
sMightyenaSprites29:
ax_sprite sMightyenaGfx29, 0x100
ax_sprite_terminator
sMightyenaGfx30:
.incbin "baserom.gba", 0x10C7D48, 0x100
sMightyenaSprites30:
ax_sprite sMightyenaGfx30, 0x100
ax_sprite_terminator
sMightyenaGfx31:
.incbin "baserom.gba", 0x10C7E58, 0x100
sMightyenaSprites31:
ax_sprite sMightyenaGfx31, 0x100
ax_sprite_terminator
sMightyenaGfx32:
.incbin "baserom.gba", 0x10C7F68, 0x160
sMightyenaGfx32_1:
.incbin "baserom.gba", 0x10C80C8, 0x40
sMightyenaSprites32:
ax_sprite sMightyenaGfx32, 0x160
ax_sprite 0, 0x20
ax_sprite sMightyenaGfx32_1, 0x40
ax_sprite 0, 0x40
ax_sprite_terminator
sMightyenaGfx33:
.incbin "baserom.gba", 0x10C8130, 0x40
sMightyenaGfx33_1:
.incbin "baserom.gba", 0x10C8170, 0x60
sMightyenaGfx33_2:
.incbin "baserom.gba", 0x10C81D0, 0x80
sMightyenaGfx33_3:
.incbin "baserom.gba", 0x10C8250, 0x60
sMightyenaSprites33:
ax_sprite sMightyenaGfx33, 0x40
ax_sprite 0, 0x40
ax_sprite sMightyenaGfx33_1, 0x60
ax_sprite 0, 0x20
ax_sprite sMightyenaGfx33_2, 0x80
ax_sprite 0, 0x20
ax_sprite sMightyenaGfx33_3, 0x60
ax_sprite_terminator
sMightyenaGfx34:
.incbin "baserom.gba", 0x10C82F0, 0x60
sMightyenaGfx34_1:
.incbin "baserom.gba", 0x10C8350, 0x60
sMightyenaGfx34_2:
.incbin "baserom.gba", 0x10C83B0, 0x60
sMightyenaGfx34_3:
.incbin "baserom.gba", 0x10C8410, 0x60
sMightyenaSprites34:
ax_sprite sMightyenaGfx34, 0x60
ax_sprite 0, 0x20
ax_sprite sMightyenaGfx34_1, 0x60
ax_sprite 0, 0x20
ax_sprite sMightyenaGfx34_2, 0x60
ax_sprite 0, 0x20
ax_sprite sMightyenaGfx34_3, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sMightyenaGfx35:
.incbin "baserom.gba", 0x10C84B8, 0x100
sMightyenaSprites35:
ax_sprite sMightyenaGfx35, 0x100
ax_sprite_terminator
sMightyenaGfx36:
.incbin "baserom.gba", 0x10C85C8, 0x200
sMightyenaSprites36:
ax_sprite sMightyenaGfx36, 0x200
ax_sprite_terminator
sMightyenaGfx37:
.incbin "baserom.gba", 0x10C87D8, 0x200
sMightyenaSprites37:
ax_sprite sMightyenaGfx37, 0x200
ax_sprite_terminator
sMightyenaGfx38:
.incbin "baserom.gba", 0x10C89E8, 0x200
sMightyenaSprites38:
ax_sprite sMightyenaGfx38, 0x200
ax_sprite_terminator
sMightyenaGfx39:
.incbin "baserom.gba", 0x10C8BF8, 0x200
sMightyenaSprites39:
ax_sprite sMightyenaGfx39, 0x200
ax_sprite_terminator
sMightyenaGfx40:
.incbin "baserom.gba", 0x10C8E08, 0x200
sMightyenaSprites40:
ax_sprite sMightyenaGfx40, 0x200
ax_sprite_terminator
sMightyenaGfx41:
.incbin "baserom.gba", 0x10C9018, 0x200
sMightyenaSprites41:
ax_sprite sMightyenaGfx41, 0x200
ax_sprite_terminator
sMightyenaGfx42:
.incbin "baserom.gba", 0x10C9228, 0x200
sMightyenaSprites42:
ax_sprite sMightyenaGfx42, 0x200
ax_sprite_terminator
sAxPosesMightyena:
.4byte sMightyenaPose1
.4byte sMightyenaPose2
.4byte sMightyenaPose3
.4byte sMightyenaPose4
.4byte sMightyenaPose5
.4byte sMightyenaPose6
.4byte sMightyenaPose7
.4byte sMightyenaPose8
.4byte sMightyenaPose9
.4byte sMightyenaPose10
.4byte sMightyenaPose11
.4byte sMightyenaPose12
.4byte sMightyenaPose13
.4byte sMightyenaPose14
.4byte sMightyenaPose15
.4byte sMightyenaPose16
.4byte sMightyenaPose17
.4byte sMightyenaPose18
.4byte sMightyenaPose19
.4byte sMightyenaPose20
.4byte sMightyenaPose21
.4byte sMightyenaPose22
.4byte sMightyenaPose23
.4byte sMightyenaPose24
.4byte sMightyenaPose25
.4byte sMightyenaPose26
.4byte sMightyenaPose27
.4byte sMightyenaPose28
.4byte sMightyenaPose29
.4byte sMightyenaPose30
.4byte sMightyenaPose31
.4byte sMightyenaPose32
.4byte sMightyenaPose33
.4byte sMightyenaPose34
.4byte sMightyenaPose35
.4byte sMightyenaPose36
.4byte sMightyenaPose37
.4byte sMightyenaPose38
.4byte sMightyenaPose39
.4byte sMightyenaPose40
.4byte sMightyenaPose41
.4byte sMightyenaPose42
.4byte sMightyenaPose43
.4byte sMightyenaPose44
.4byte sMightyenaPose45
.4byte sMightyenaPose46
.4byte sMightyenaPose47
.4byte sMightyenaPose48
.4byte sMightyenaPose49
.4byte sMightyenaPose50
.4byte sMightyenaPose51
.4byte sMightyenaPose52
.4byte sMightyenaPose53
.4byte sMightyenaPose54
.4byte sMightyenaPose55
.4byte sMightyenaPose56
.4byte sMightyenaPose57
.4byte sMightyenaPose58
.4byte sMightyenaPose59
.4byte sMightyenaPose60
.4byte sMightyenaPose61
.4byte sMightyenaPose62
.4byte sMightyenaPose63
.4byte sMightyenaPose64
.4byte sMightyenaPose65
.4byte sMightyenaPose66
.4byte sMightyenaPose67
.4byte sMightyenaPose68
.4byte sMightyenaPose69
.4byte sMightyenaPose70
.4byte sMightyenaPose71
.4byte sMightyenaPose72
.4byte sMightyenaPose73
.4byte sMightyenaPose74
.4byte sMightyenaPose75
.4byte sMightyenaPose76
.4byte sMightyenaPose77
.4byte sMightyenaPose78
.4byte sMightyenaPose79
.4byte sMightyenaPose80
.4byte sMightyenaPose81
.4byte sMightyenaPose82
.4byte sMightyenaPose83
.4byte sMightyenaPose84
.4byte sMightyenaPose85
.4byte sMightyenaPose86
.4byte sMightyenaPose87
.4byte sMightyenaPose88
.4byte sMightyenaPose89
.4byte sMightyenaPose90
.4byte sMightyenaPose91
.4byte sMightyenaPose92
.4byte sMightyenaPose93
.4byte sMightyenaPose94
.4byte sMightyenaPose95
.4byte sMightyenaPose96
.4byte sMightyenaPose97
.4byte sMightyenaPose98
.4byte sMightyenaPose99
.4byte sMightyenaPose100
.4byte sMightyenaPose101
.4byte sMightyenaPose102
.4byte sMightyenaPose103
.4byte sMightyenaPose104
.4byte sMightyenaPose105
.4byte sMightyenaPose106
.4byte sMightyenaPose107
.4byte sMightyenaPose108
.4byte sMightyenaPose109
.4byte sMightyenaPose110
.4byte sMightyenaPose111
.4byte sMightyenaPose112
.4byte sMightyenaPose113
.4byte sMightyenaPose114
.4byte sMightyenaPose115
.4byte sMightyenaPose116
.4byte sMightyenaPose117
.4byte sMightyenaPose118
.4byte sMightyenaPose119
.4byte sMightyenaPose120
.4byte sMightyenaPose121
.4byte sMightyenaPose122
.4byte sMightyenaPose123
.4byte sMightyenaPose124
.4byte sMightyenaPose125
.4byte sMightyenaPose126
.4byte sMightyenaPose127
.4byte sMightyenaPose128
.4byte sMightyenaPose129
.4byte sMightyenaPose130
.4byte sMightyenaPose131
.4byte sMightyenaPose132
.4byte sMightyenaPose133
.4byte sMightyenaPose134
.4byte sMightyenaPose135
.4byte sMightyenaPose136
.4byte sMightyenaPose137
.4byte sMightyenaPose138
.4byte sMightyenaPose139
.4byte sMightyenaPose140
.4byte sMightyenaPose141
.4byte sMightyenaPose142
.4byte sMightyenaPose143
.4byte sMightyenaPose144
.4byte sMightyenaPose145
.4byte sMightyenaPose146
.4byte sMightyenaPose147
.4byte sMightyenaPose148
.4byte sMightyenaPose149
.4byte sMightyenaPose150
.4byte sMightyenaPose151
.4byte sMightyenaPose152
.4byte sMightyenaPose153
.4byte sMightyenaPose154
.4byte sMightyenaPose155
.4byte sMightyenaPose156
.4byte sMightyenaPose157
.4byte sMightyenaPose158
.4byte sMightyenaPose159
.4byte sMightyenaPose160
.4byte sMightyenaPose161
.4byte sMightyenaPose162
.4byte sMightyenaPose163
.4byte sMightyenaPose164
.4byte sMightyenaPose165
.4byte sMightyenaPose166
.4byte sMightyenaPose167
.4byte sMightyenaPose168
.4byte sMightyenaPose169
.4byte sMightyenaPose170
.4byte sMightyenaPose171
.4byte sMightyenaPose172
.4byte sMightyenaPose173
.4byte sMightyenaPose174
.4byte sMightyenaPose175
.4byte sMightyenaPose176
.4byte sMightyenaPose177
.4byte sMightyenaPose178
.4byte sMightyenaPose179
.4byte sMightyenaPose180
.4byte sMightyenaPose181
.4byte sMightyenaPose182
.4byte sMightyenaPose183
.4byte sMightyenaPose184
.4byte sMightyenaPose185
.4byte sMightyenaPose186
.4byte sMightyenaPose187
.4byte sMightyenaPose188
.4byte sMightyenaPose189
.4byte sMightyenaPose190
.4byte sMightyenaPose191
.4byte sMightyenaPose192
.4byte sMightyenaPose193
.4byte sMightyenaPose194
.4byte sMightyenaPose195
.4byte sMightyenaPose196
.4byte sMightyenaPose197
.4byte sMightyenaPose198
.4byte sMightyenaPose199
.4byte sMightyenaPose200
.4byte sMightyenaPose201
.4byte sMightyenaPose202
.4byte sMightyenaPose203
.4byte sMightyenaPose204
.4byte sMightyenaPose205
.4byte sMightyenaPose206
.4byte sMightyenaPose207
.4byte sMightyenaPose208
.4byte sMightyenaPose209
.4byte sMightyenaPose210
.4byte sMightyenaPose211
.4byte sMightyenaPose212
.4byte sMightyenaPose213
.4byte sMightyenaPose214
.4byte sMightyenaPose215
.4byte sMightyenaPose216
.4byte sMightyenaPose217
.4byte sMightyenaPose218
.4byte sMightyenaPose219
.4byte sMightyenaPose220
.4byte sMightyenaPose221
.4byte sMightyenaPose222
.4byte sMightyenaPose223
.4byte sMightyenaPose224
.4byte sMightyenaPose225
.4byte sMightyenaPose226
.4byte sMightyenaPose227
.4byte sMightyenaPose228
.4byte sMightyenaPose229
.4byte sMightyenaPose230
.4byte sMightyenaPose231
.4byte sMightyenaPose232
.4byte sMightyenaPose233
.4byte sMightyenaPose234
sAxPositionsMightyena:
.2byte   -1,   -2, 	  -5,    2, 	   4,    2, 	  -1,   -7
.2byte   -1,   -1, 	  -4,    4, 	   2,    1, 	  -1,   -6
.2byte   -1,   -1, 	  -3,    1, 	   3,    4, 	  -1,   -6
.2byte    7,   -5, 	   7,    0, 	   1,    3, 	  -1,   -7
.2byte    7,   -4, 	   9,    3, 	  -1,   -1, 	  -2,   -8
.2byte    7,   -4, 	   2,    0, 	   3,    5, 	  -2,   -7
.2byte   12,   -9, 	   8,   -4, 	   6,    1, 	  -1,   -7
.2byte   12,   -8, 	  11,   -1, 	   3,    1, 	  -2,   -6
.2byte   12,   -8, 	   1,   -1, 	  10,    1, 	  -2,   -6
.2byte    8,  -14, 	   1,   -7, 	   7,   -3, 	   1,   -8
.2byte    8,  -13, 	   3,   -9, 	   4,   -1, 	   1,   -8
.2byte    8,  -13, 	  -1,   -6, 	   9,   -4, 	   0,   -7
.2byte   -1,  -16, 	   4,   -5, 	  -5,   -5, 	  -1,   -9
.2byte   -1,  -14, 	   4,   -1, 	  -5,   -5, 	  -1,   -8
.2byte   -1,  -14, 	   4,   -5, 	  -5,   -1, 	  -1,   -8
.2byte   -9,  -14, 	  -2,   -7, 	  -8,   -3, 	  -2,   -8
.2byte   -9,  -13, 	  -4,   -9, 	  -5,   -1, 	  -2,   -8
.2byte   -9,  -13, 	   0,   -6, 	 -10,   -4, 	  -1,   -7
.2byte  -13,   -9, 	  -9,   -4, 	  -7,    1, 	   0,   -7
.2byte  -13,   -8, 	 -12,   -1, 	  -4,    1, 	   1,   -6
.2byte  -13,   -8, 	  -2,   -1, 	 -11,    1, 	   1,   -6
.2byte   -8,   -5, 	  -8,    0, 	  -2,    3, 	   0,   -7
.2byte   -8,   -4, 	 -10,    3, 	   0,   -1, 	   1,   -8
.2byte   -8,   -4, 	  -3,    0, 	  -4,    5, 	   1,   -7
.2byte   -1,   -2, 	  -5,    2, 	   4,    2, 	  -1,   -7
.2byte   -1,   -9, 	  -5,    2, 	   4,    2, 	  -1,   -7
.2byte   -1,   -1, 	  -6,    2, 	   5,    2, 	  -1,   -8
.2byte   -1,   -6, 	  -5,   -5, 	   5,   -5, 	  -1,  -11
.2byte    7,   -5, 	   7,    0, 	   1,    3, 	  -1,   -7
.2byte    7,  -12, 	   7,    0, 	   1,    3, 	  -2,   -8
.2byte    9,   -2, 	   7,    0, 	   1,    3, 	   0,   -9
.2byte    8,   -8, 	  12,   -5, 	   5,   -2, 	  -2,  -11
.2byte   12,   -9, 	   8,   -4, 	   6,    1, 	  -1,   -7
.2byte    8,  -13, 	   8,   -5, 	   6,    1, 	  -2,   -7
.2byte   12,   -5, 	   8,   -4, 	   6,    1, 	   1,   -7
.2byte   12,  -13, 	  12,  -14, 	  12,   -9, 	  -1,  -10
.2byte    8,  -14, 	   1,   -7, 	   7,   -3, 	   1,   -8
.2byte    6,  -18, 	  -2,   -9, 	   7,   -3, 	  -1,   -8
.2byte   10,  -15, 	   0,   -7, 	   7,   -3, 	   2,  -10
.2byte    7,  -17, 	   0,  -19, 	   9,  -15, 	  -1,  -10
.2byte   -1,  -16, 	   4,   -5, 	  -5,   -5, 	  -1,   -9
.2byte   -1,  -20, 	   4,   -2, 	  -5,   -2, 	  -1,  -11
.2byte   -1,  -13, 	   4,   -5, 	  -5,   -5, 	  -1,  -10
.2byte   -1,  -16, 	   5,  -18, 	  -6,  -18, 	  -1,  -13
.2byte   -9,  -14, 	  -2,   -7, 	  -8,   -3, 	  -2,   -8
.2byte   -7,  -18, 	   1,   -9, 	  -8,   -3, 	   0,   -8
.2byte  -11,  -15, 	  -1,   -7, 	  -8,   -3, 	  -3,  -10
.2byte   -8,  -17, 	  -1,  -19, 	 -10,  -15, 	   0,  -10
.2byte  -13,   -9, 	  -9,   -4, 	  -7,    1, 	   0,   -7
.2byte   -9,  -13, 	  -9,   -5, 	  -7,    1, 	   1,   -7
.2byte  -13,   -5, 	  -9,   -4, 	  -7,    1, 	  -2,   -7
.2byte  -13,  -13, 	 -13,  -14, 	 -13,   -9, 	   0,  -10
.2byte   -8,   -5, 	  -8,    0, 	  -2,    3, 	   0,   -7
.2byte   -8,  -12, 	  -8,    0, 	  -2,    3, 	   1,   -8
.2byte  -10,   -2, 	  -8,    0, 	  -2,    3, 	  -1,   -9
.2byte   -9,   -8, 	 -13,   -5, 	  -6,   -2, 	   1,  -11
.2byte   -1,   -2, 	  -5,    2, 	   4,    2, 	  -1,   -7
.2byte   -1,   -9, 	  -5,    2, 	   4,    2, 	  -1,   -7
.2byte   -1,   -1, 	  -6,    2, 	   5,    2, 	  -1,   -8
.2byte   -1,   -6, 	  -5,   -5, 	   5,   -5, 	  -1,  -11
.2byte    7,   -5, 	   7,    0, 	   1,    3, 	  -1,   -7
.2byte    7,  -12, 	   7,    0, 	   1,    3, 	  -2,   -8
.2byte    9,   -2, 	   7,    0, 	   1,    3, 	   0,   -9
.2byte    8,   -8, 	  12,   -5, 	   5,   -2, 	  -2,  -11
.2byte   12,   -9, 	   8,   -4, 	   6,    1, 	  -1,   -7
.2byte    8,  -13, 	   8,   -5, 	   6,    1, 	  -2,   -7
.2byte   12,   -5, 	   8,   -4, 	   6,    1, 	   1,   -7
.2byte   12,  -13, 	  12,  -14, 	  12,   -9, 	  -1,  -10
.2byte    8,  -14, 	   1,   -7, 	   7,   -3, 	   1,   -8
.2byte    6,  -18, 	  -2,   -9, 	   7,   -3, 	  -1,   -8
.2byte   10,  -15, 	   0,   -7, 	   7,   -3, 	   2,  -10
.2byte    7,  -17, 	   0,  -19, 	   9,  -15, 	  -1,  -10
.2byte   -1,  -16, 	   4,   -5, 	  -5,   -5, 	  -1,   -9
.2byte   -1,  -20, 	   4,   -2, 	  -5,   -2, 	  -1,  -11
.2byte   -1,  -13, 	   4,   -5, 	  -5,   -5, 	  -1,  -10
.2byte   -1,  -16, 	   5,  -18, 	  -6,  -18, 	  -1,  -13
.2byte   -9,  -14, 	  -2,   -7, 	  -8,   -3, 	  -2,   -8
.2byte   -7,  -18, 	   1,   -9, 	  -8,   -3, 	   0,   -8
.2byte  -11,  -15, 	  -1,   -7, 	  -8,   -3, 	  -3,  -10
.2byte   -8,  -17, 	  -1,  -19, 	 -10,  -15, 	   0,  -10
.2byte  -13,   -9, 	  -9,   -4, 	  -7,    1, 	   0,   -7
.2byte   -9,  -13, 	  -9,   -5, 	  -7,    1, 	   1,   -7
.2byte  -13,   -5, 	  -9,   -4, 	  -7,    1, 	  -2,   -7
.2byte  -13,  -13, 	 -13,  -14, 	 -13,   -9, 	   0,  -10
.2byte   -8,   -5, 	  -8,    0, 	  -2,    3, 	   0,   -7
.2byte   -8,  -12, 	  -8,    0, 	  -2,    3, 	   1,   -8
.2byte  -10,   -2, 	  -8,    0, 	  -2,    3, 	  -1,   -9
.2byte   -9,   -8, 	 -13,   -5, 	  -6,   -2, 	   1,  -11
.2byte   -1,   -2, 	  -5,    2, 	   4,    2, 	  -1,   -7
.2byte   -1,   -9, 	  -5,    2, 	   4,    2, 	  -1,   -7
.2byte   -1,   -1, 	  -6,    2, 	   5,    2, 	  -1,   -8
.2byte   -1,   -7, 	  -5,    1, 	   4,    1, 	  -1,   -9
.2byte    7,   -5, 	   7,    0, 	   1,    3, 	  -1,   -7
.2byte    7,  -12, 	   7,    0, 	   1,    3, 	  -2,   -8
.2byte    9,   -2, 	   7,    0, 	   1,    3, 	   0,   -9
.2byte    4,   -9, 	   5,   -1, 	   0,    2, 	  -4,   -8
.2byte   12,   -9, 	   8,   -4, 	   6,    1, 	  -1,   -7
.2byte    8,  -13, 	   8,   -5, 	   6,    1, 	  -2,   -7
.2byte   12,   -5, 	   8,   -4, 	   6,    1, 	   1,   -7
.2byte    9,  -13, 	   6,   -5, 	   3,    1, 	  -2,   -8
.2byte    8,  -14, 	   1,   -7, 	   7,   -3, 	   1,   -8
.2byte    6,  -18, 	  -2,   -9, 	   7,   -3, 	  -1,   -8
.2byte   10,  -15, 	   0,   -7, 	   7,   -3, 	   2,  -10
.2byte    5,  -16, 	  -3,   -5, 	   5,   -2, 	  -1,   -9
.2byte   -1,  -16, 	   4,   -5, 	  -5,   -5, 	  -1,   -9
.2byte   -1,  -20, 	   4,   -2, 	  -5,   -2, 	  -1,  -11
.2byte   -1,  -13, 	   4,   -5, 	  -5,   -5, 	  -1,  -10
.2byte   -1,  -14, 	   4,   -3, 	  -5,   -3, 	  -1,  -10
.2byte   -9,  -14, 	  -2,   -7, 	  -8,   -3, 	  -2,   -8
.2byte   -7,  -18, 	   1,   -9, 	  -8,   -3, 	   0,   -8
.2byte  -11,  -15, 	  -1,   -7, 	  -8,   -3, 	  -3,  -10
.2byte   -6,  -16, 	   2,   -5, 	  -6,   -2, 	   0,   -9
.2byte  -13,   -9, 	  -9,   -4, 	  -7,    1, 	   0,   -7
.2byte   -9,  -13, 	  -9,   -5, 	  -7,    1, 	   1,   -7
.2byte  -13,   -5, 	  -9,   -4, 	  -7,    1, 	  -2,   -7
.2byte  -10,  -13, 	  -7,   -5, 	  -4,    1, 	   1,   -8
.2byte   -8,   -5, 	  -8,    0, 	  -2,    3, 	   0,   -7
.2byte   -8,  -12, 	  -8,    0, 	  -2,    3, 	   1,   -8
.2byte  -10,   -2, 	  -8,    0, 	  -2,    3, 	  -1,   -9
.2byte   -5,   -9, 	  -6,   -1, 	  -1,    2, 	   3,   -8
.2byte   -1,   -7, 	  -5,    1, 	   4,    1, 	  -1,   -9
.2byte   -1,   -9, 	  -5,    2, 	   4,    2, 	  -1,   -7
.2byte    4,   -9, 	   5,   -1, 	   0,    2, 	  -4,   -8
.2byte    7,  -12, 	   7,    0, 	   1,    3, 	  -2,   -8
.2byte    9,  -13, 	   6,   -5, 	   3,    1, 	  -2,   -8
.2byte    8,  -13, 	   8,   -5, 	   6,    1, 	  -2,   -7
.2byte    5,  -16, 	  -3,   -5, 	   5,   -2, 	  -1,   -9
.2byte    6,  -18, 	  -2,   -9, 	   7,   -3, 	  -1,   -8
.2byte   -1,  -14, 	   4,   -3, 	  -5,   -3, 	  -1,  -10
.2byte   -1,  -20, 	   4,   -2, 	  -5,   -2, 	  -1,  -11
.2byte   -6,  -16, 	   2,   -5, 	  -6,   -2, 	   0,   -9
.2byte   -7,  -18, 	   1,   -9, 	  -8,   -3, 	   0,   -8
.2byte  -10,  -13, 	  -7,   -5, 	  -4,    1, 	   1,   -8
.2byte   -9,  -13, 	  -9,   -5, 	  -7,    1, 	   1,   -7
.2byte   -5,   -9, 	  -6,   -1, 	  -1,    2, 	   3,   -8
.2byte   -8,  -12, 	  -8,    0, 	  -2,    3, 	   1,   -8
.2byte   -1,    1, 	  -4,    3, 	   1,    3, 	   0,   -5
.2byte   -1,    2, 	  -4,    3, 	   1,    3, 	   0,   -4
.2byte    0,  -10, 	  -7,  -10, 	   7,   -7, 	   0,  -11
.2byte    2,  -14, 	   8,  -17, 	  -1,  -14, 	  -3,  -10
.2byte    3,  -15, 	   8,  -18, 	   2,  -11, 	  -2,   -9
.2byte    4,  -15, 	  -2,  -16, 	   8,  -12, 	  -2,   -8
.2byte   -1,  -15, 	   5,  -13, 	  -6,  -13, 	  -1,  -10
.2byte   -5,  -16, 	   1,  -17, 	  -9,  -13, 	   1,   -9
.2byte   -4,  -15, 	  -9,  -18, 	  -3,  -11, 	   1,   -9
.2byte   -3,  -14, 	  -9,  -17, 	   0,  -14, 	   2,  -10
.2byte   -1,   -2, 	  -5,    2, 	   4,    2, 	  -1,   -7
.2byte   -1,   -9, 	  -5,    2, 	   4,    2, 	  -1,   -7
.2byte   -1,   -1, 	  -6,    2, 	   5,    2, 	  -1,   -8
.2byte   -1,   -7, 	  -5,    1, 	   4,    1, 	  -1,   -9
.2byte    7,   -5, 	   7,    0, 	   1,    3, 	  -1,   -7
.2byte    7,  -12, 	   7,    0, 	   1,    3, 	  -2,   -8
.2byte    9,   -2, 	   7,    0, 	   1,    3, 	   0,   -9
.2byte    4,   -9, 	   5,   -1, 	   0,    2, 	  -4,   -8
.2byte   12,   -9, 	   8,   -4, 	   6,    1, 	  -1,   -7
.2byte    8,  -13, 	   8,   -5, 	   6,    1, 	  -2,   -7
.2byte   12,   -5, 	   8,   -4, 	   6,    1, 	   1,   -7
.2byte    9,  -13, 	   6,   -5, 	   3,    1, 	  -2,   -8
.2byte    8,  -14, 	   1,   -7, 	   7,   -3, 	   1,   -8
.2byte    6,  -18, 	  -2,   -9, 	   7,   -3, 	  -1,   -8
.2byte   10,  -15, 	   0,   -7, 	   7,   -3, 	   2,  -10
.2byte    5,  -16, 	  -3,   -5, 	   5,   -2, 	  -1,   -9
.2byte   -1,  -16, 	   4,   -5, 	  -5,   -5, 	  -1,   -9
.2byte   -1,  -20, 	   4,   -2, 	  -5,   -2, 	  -1,  -11
.2byte   -1,  -13, 	   4,   -5, 	  -5,   -5, 	  -1,  -10
.2byte   -1,  -14, 	   4,   -3, 	  -5,   -3, 	  -1,  -10
.2byte   -9,  -14, 	  -2,   -7, 	  -8,   -3, 	  -2,   -8
.2byte   -7,  -18, 	   1,   -9, 	  -8,   -3, 	   0,   -8
.2byte  -11,  -15, 	  -1,   -7, 	  -8,   -3, 	  -3,  -10
.2byte   -6,  -16, 	   2,   -5, 	  -6,   -2, 	   0,   -9
.2byte  -13,   -9, 	  -9,   -4, 	  -7,    1, 	   0,   -7
.2byte   -9,  -13, 	  -9,   -5, 	  -7,    1, 	   1,   -7
.2byte  -13,   -5, 	  -9,   -4, 	  -7,    1, 	  -2,   -7
.2byte  -10,  -13, 	  -7,   -5, 	  -4,    1, 	   1,   -8
.2byte   -8,   -5, 	  -8,    0, 	  -2,    3, 	   0,   -7
.2byte   -8,  -12, 	  -8,    0, 	  -2,    3, 	   1,   -8
.2byte  -10,   -2, 	  -8,    0, 	  -2,    3, 	  -1,   -9
.2byte   -5,   -9, 	  -6,   -1, 	  -1,    2, 	   3,   -8
.2byte   -1,   -3, 	  -5,   -2, 	   5,   -2, 	  -1,   -8
.2byte   -9,   -6, 	 -13,   -3, 	  -6,    0, 	   1,   -9
.2byte  -13,  -11, 	 -13,  -12, 	 -13,   -7, 	   0,   -8
.2byte   -8,  -15, 	  -1,  -17, 	 -10,  -13, 	   0,   -8
.2byte   -1,  -14, 	   5,  -16, 	  -6,  -16, 	  -1,  -11
.2byte    7,  -15, 	   0,  -17, 	   9,  -13, 	  -1,   -8
.2byte   12,  -11, 	  12,  -12, 	  12,   -7, 	  -1,   -8
.2byte    8,   -6, 	  12,   -3, 	   5,    0, 	  -2,   -9
.2byte   -1,   -9, 	  -5,    2, 	   4,    2, 	  -1,   -7
.2byte    8,  -11, 	   8,    1, 	   2,    4, 	  -1,   -7
.2byte    8,  -13, 	   8,   -5, 	   6,    1, 	  -2,   -7
.2byte    6,  -18, 	  -2,   -9, 	   7,   -3, 	  -1,   -8
.2byte   -1,  -21, 	   4,   -3, 	  -5,   -3, 	  -1,  -12
.2byte   -7,  -18, 	   1,   -9, 	  -8,   -3, 	   0,   -8
.2byte   -9,  -13, 	  -9,   -5, 	  -7,    1, 	   1,   -7
.2byte   -9,  -11, 	  -9,    1, 	  -3,    4, 	   0,   -7
.2byte   -1,   -2, 	  -5,    2, 	   4,    2, 	  -1,   -7
.2byte   -1,   -1, 	  -6,    2, 	   5,    2, 	  -1,   -8
.2byte   -1,   -6, 	  -5,   -5, 	   5,   -5, 	  -1,  -11
.2byte    7,   -5, 	   7,    0, 	   1,    3, 	  -1,   -7
.2byte    8,   -2, 	   6,    0, 	   0,    3, 	  -1,   -9
.2byte    8,   -8, 	  12,   -5, 	   5,   -2, 	  -2,  -11
.2byte   12,   -9, 	   8,   -4, 	   6,    1, 	  -1,   -7
.2byte   11,   -5, 	   7,   -4, 	   5,    1, 	   0,   -7
.2byte   12,  -13, 	  12,  -14, 	  12,   -9, 	  -1,  -10
.2byte    8,  -14, 	   1,   -7, 	   7,   -3, 	   1,   -8
.2byte    9,  -15, 	  -1,   -7, 	   6,   -3, 	   1,  -10
.2byte    7,  -17, 	   0,  -19, 	   9,  -15, 	  -1,  -10
.2byte   -1,  -16, 	   4,   -5, 	  -5,   -5, 	  -1,   -9
.2byte   -1,  -13, 	   4,   -5, 	  -5,   -5, 	  -1,  -10
.2byte   -1,  -16, 	   5,  -18, 	  -6,  -18, 	  -1,  -13
.2byte   -9,  -14, 	  -2,   -7, 	  -8,   -3, 	  -2,   -8
.2byte  -10,  -15, 	   0,   -7, 	  -7,   -3, 	  -2,  -10
.2byte   -9,  -17, 	  -2,  -19, 	 -11,  -15, 	  -1,  -10
.2byte  -13,   -9, 	  -9,   -4, 	  -7,    1, 	   0,   -7
.2byte  -12,   -5, 	  -8,   -4, 	  -6,    1, 	  -1,   -7
.2byte  -13,  -13, 	 -13,  -14, 	 -13,   -9, 	   0,  -10
.2byte   -8,   -5, 	  -8,    0, 	  -2,    3, 	   0,   -7
.2byte   -9,   -2, 	  -7,    0, 	  -1,    3, 	   0,   -9
.2byte   -9,   -8, 	 -13,   -5, 	  -6,   -2, 	   1,  -11
.2byte   -1,   -1, 	  -6,    2, 	   5,    2, 	  -1,   -8
.2byte   -8,   -2, 	  -6,    0, 	   0,    3, 	   1,   -9
.2byte  -11,   -5, 	  -7,   -4, 	  -5,    1, 	   0,   -7
.2byte  -10,  -15, 	   0,   -7, 	  -7,   -3, 	  -2,  -10
.2byte   -1,  -13, 	   4,   -5, 	  -5,   -5, 	  -1,  -10
.2byte    9,  -15, 	  -1,   -7, 	   6,   -3, 	   1,  -10
.2byte   10,   -5, 	   6,   -4, 	   4,    1, 	  -1,   -7
.2byte    7,   -2, 	   5,    0, 	  -1,    3, 	  -2,   -9
.2byte   -1,   -2, 	  -5,    2, 	   4,    2, 	  -1,   -7
.2byte   -8,   -5, 	  -8,    0, 	  -2,    3, 	   0,   -7
.2byte  -13,   -9, 	  -9,   -4, 	  -7,    1, 	   0,   -7
.2byte   -9,  -14, 	  -2,   -7, 	  -8,   -3, 	  -2,   -8
.2byte   -1,  -16, 	   4,   -5, 	  -5,   -5, 	  -1,   -9
.2byte    8,  -14, 	   1,   -7, 	   7,   -3, 	   1,   -8
.2byte   12,   -9, 	   8,   -4, 	   6,    1, 	  -1,   -7
.2byte    7,   -5, 	   7,    0, 	   1,    3, 	  -1,   -7
sMightyenaAnimTable1:
.4byte sMightyenaAnims_1_1
.4byte sMightyenaAnims_1_2
.4byte sMightyenaAnims_1_3
.4byte sMightyenaAnims_1_4
.4byte sMightyenaAnims_1_5
.4byte sMightyenaAnims_1_6
.4byte sMightyenaAnims_1_7
.4byte sMightyenaAnims_1_8
sMightyenaAnimTable2:
.4byte sMightyenaAnims_2_1
.4byte sMightyenaAnims_2_2
.4byte sMightyenaAnims_2_3
.4byte sMightyenaAnims_2_4
.4byte sMightyenaAnims_2_5
.4byte sMightyenaAnims_2_6
.4byte sMightyenaAnims_2_7
.4byte sMightyenaAnims_2_8
sMightyenaAnimTable3:
.4byte sMightyenaAnims_3_1
.4byte sMightyenaAnims_3_2
.4byte sMightyenaAnims_3_3
.4byte sMightyenaAnims_3_4
.4byte sMightyenaAnims_3_5
.4byte sMightyenaAnims_3_6
.4byte sMightyenaAnims_3_7
.4byte sMightyenaAnims_3_8
sMightyenaAnimTable4:
.4byte sMightyenaAnims_4_1
.4byte sMightyenaAnims_4_2
.4byte sMightyenaAnims_4_3
.4byte sMightyenaAnims_4_4
.4byte sMightyenaAnims_4_5
.4byte sMightyenaAnims_4_6
.4byte sMightyenaAnims_4_7
.4byte sMightyenaAnims_4_8
sMightyenaAnimTable5:
.4byte sMightyenaAnims_5_1
.4byte sMightyenaAnims_5_2
.4byte sMightyenaAnims_5_3
.4byte sMightyenaAnims_5_4
.4byte sMightyenaAnims_5_5
.4byte sMightyenaAnims_5_6
.4byte sMightyenaAnims_5_7
.4byte sMightyenaAnims_5_8
sMightyenaAnimTable6:
.4byte sMightyenaAnims_6_1
.4byte sMightyenaAnims_6_1
.4byte sMightyenaAnims_6_1
.4byte sMightyenaAnims_6_1
.4byte sMightyenaAnims_6_1
.4byte sMightyenaAnims_6_1
.4byte sMightyenaAnims_6_1
.4byte sMightyenaAnims_6_1
sMightyenaAnimTable7:
.4byte sMightyenaAnims_7_1
.4byte sMightyenaAnims_7_2
.4byte sMightyenaAnims_7_3
.4byte sMightyenaAnims_7_4
.4byte sMightyenaAnims_7_5
.4byte sMightyenaAnims_7_6
.4byte sMightyenaAnims_7_7
.4byte sMightyenaAnims_7_8
sMightyenaAnimTable8:
.4byte sMightyenaAnims_8_1
.4byte sMightyenaAnims_8_2
.4byte sMightyenaAnims_8_3
.4byte sMightyenaAnims_8_4
.4byte sMightyenaAnims_8_5
.4byte sMightyenaAnims_8_6
.4byte sMightyenaAnims_8_7
.4byte sMightyenaAnims_8_8
sMightyenaAnimTable9:
.4byte sMightyenaAnims_9_1
.4byte sMightyenaAnims_9_2
.4byte sMightyenaAnims_9_3
.4byte sMightyenaAnims_9_4
.4byte sMightyenaAnims_9_5
.4byte sMightyenaAnims_9_6
.4byte sMightyenaAnims_9_7
.4byte sMightyenaAnims_9_8
sMightyenaAnimTable10:
.4byte sMightyenaAnims_10_1
.4byte sMightyenaAnims_10_2
.4byte sMightyenaAnims_10_3
.4byte sMightyenaAnims_10_4
.4byte sMightyenaAnims_10_5
.4byte sMightyenaAnims_10_6
.4byte sMightyenaAnims_10_7
.4byte sMightyenaAnims_10_8
sMightyenaAnimTable11:
.4byte sMightyenaAnims_11_1
.4byte sMightyenaAnims_11_2
.4byte sMightyenaAnims_11_3
.4byte sMightyenaAnims_11_4
.4byte sMightyenaAnims_11_5
.4byte sMightyenaAnims_11_6
.4byte sMightyenaAnims_11_7
.4byte sMightyenaAnims_11_8
sMightyenaAnimTable12:
.4byte sMightyenaAnims_12_1
.4byte sMightyenaAnims_12_2
.4byte sMightyenaAnims_12_3
.4byte sMightyenaAnims_12_4
.4byte sMightyenaAnims_12_5
.4byte sMightyenaAnims_12_6
.4byte sMightyenaAnims_12_7
.4byte sMightyenaAnims_12_8
sMightyenaAnimTable13:
.4byte sMightyenaAnims_13_1
.4byte sMightyenaAnims_13_2
.4byte sMightyenaAnims_13_3
.4byte sMightyenaAnims_13_4
.4byte sMightyenaAnims_13_5
.4byte sMightyenaAnims_13_6
.4byte sMightyenaAnims_13_7
.4byte sMightyenaAnims_13_8
sAxAnimationsMightyena:
.4byte sMightyenaAnimTable1
.4byte sMightyenaAnimTable2
.4byte sMightyenaAnimTable3
.4byte sMightyenaAnimTable4
.4byte sMightyenaAnimTable5
.4byte sMightyenaAnimTable6
.4byte sMightyenaAnimTable7
.4byte sMightyenaAnimTable8
.4byte sMightyenaAnimTable9
.4byte sMightyenaAnimTable10
.4byte sMightyenaAnimTable11
.4byte sMightyenaAnimTable12
.4byte sMightyenaAnimTable13
sAxSpritesMightyena:
.4byte sMightyenaSprites1
.4byte sMightyenaSprites2
.4byte sMightyenaSprites3
.4byte sMightyenaSprites4
.4byte sMightyenaSprites5
.4byte sMightyenaSprites6
.4byte sMightyenaSprites7
.4byte sMightyenaSprites8
.4byte sMightyenaSprites9
.4byte sMightyenaSprites10
.4byte sMightyenaSprites11
.4byte sMightyenaSprites12
.4byte sMightyenaSprites13
.4byte sMightyenaSprites14
.4byte sMightyenaSprites15
.4byte sMightyenaSprites16
.4byte sMightyenaSprites17
.4byte sMightyenaSprites18
.4byte sMightyenaSprites19
.4byte sMightyenaSprites20
.4byte sMightyenaSprites21
.4byte sMightyenaSprites22
.4byte sMightyenaSprites23
.4byte sMightyenaSprites24
.4byte sMightyenaSprites25
.4byte sMightyenaSprites26
.4byte sMightyenaSprites27
.4byte sMightyenaSprites28
.4byte sMightyenaSprites29
.4byte sMightyenaSprites30
.4byte sMightyenaSprites31
.4byte sMightyenaSprites32
.4byte sMightyenaSprites33
.4byte sMightyenaSprites34
.4byte sMightyenaSprites35
.4byte sMightyenaSprites36
.4byte sMightyenaSprites37
.4byte sMightyenaSprites38
.4byte sMightyenaSprites39
.4byte sMightyenaSprites40
.4byte sMightyenaSprites41
.4byte sMightyenaSprites42
sAxMainMightyena:
ax_main sAxPosesMightyena, sAxAnimationsMightyena, 13, sAxSpritesMightyena, sAxPositionsMightyena
