.global gAxMrMime
gAxMrMime:
ax_siro sAxMainMrMime
sMrMimePose1:
ax_pose 0, 0x01ea, 0x80f0, 0xbc00
ax_pose_terminator
sMrMimePose2:
ax_pose 1, 0x01ec, 0x80f5, 0xbc00
ax_pose_terminator
sMrMimePose3:
ax_pose 2, 0x01ec, 0x80f5, 0xbc00
ax_pose_terminator
sMrMimePose4:
ax_pose 3, 0x01e4, 0x90ec, 0xbc00
ax_pose_terminator
sMrMimePose5:
ax_pose 4, 0x01e4, 0x90ec, 0xbc00
ax_pose_terminator
sMrMimePose6:
ax_pose 5, 0x01e4, 0x90ec, 0xbc00
ax_pose_terminator
sMrMimePose7:
ax_pose 6, 0x81e4, 0x90f8, 0xbc00
ax_pose_terminator
sMrMimePose8:
ax_pose 7, 0x01e4, 0x90ec, 0xbc00
ax_pose_terminator
sMrMimePose9:
ax_pose 8, 0x01e4, 0x90ec, 0xbc00
ax_pose_terminator
sMrMimePose10:
ax_pose 9, 0x01e4, 0x90ee, 0xbc00
ax_pose_terminator
sMrMimePose11:
ax_pose 10, 0x01e4, 0x90f0, 0xbc00
ax_pose_terminator
sMrMimePose12:
ax_pose 11, 0x01e4, 0x90ee, 0xbc00
ax_pose_terminator
sMrMimePose13:
ax_pose 12, 0x01ea, 0x80f0, 0xbc00
ax_pose_terminator
sMrMimePose14:
ax_pose 13, 0x01ec, 0x80f4, 0xbc00
ax_pose_terminator
sMrMimePose15:
ax_pose 14, 0x01ec, 0x80f4, 0xbc00
ax_pose_terminator
sMrMimePose16:
ax_pose 9, 0x01e4, 0x80f2, 0xbc00
ax_pose_terminator
sMrMimePose17:
ax_pose 10, 0x01e4, 0x80f0, 0xbc00
ax_pose_terminator
sMrMimePose18:
ax_pose 11, 0x01e4, 0x80f2, 0xbc00
ax_pose_terminator
sMrMimePose19:
ax_pose 6, 0x81e4, 0x80f8, 0xbc00
ax_pose_terminator
sMrMimePose20:
ax_pose 7, 0x01e4, 0x80f4, 0xbc00
ax_pose_terminator
sMrMimePose21:
ax_pose 8, 0x01e4, 0x80f4, 0xbc00
ax_pose_terminator
sMrMimePose22:
ax_pose 3, 0x01e4, 0x80f5, 0xbc00
ax_pose_terminator
sMrMimePose23:
ax_pose 4, 0x01e4, 0x80f5, 0xbc00
ax_pose_terminator
sMrMimePose24:
ax_pose 5, 0x01e4, 0x80f5, 0xbc00
ax_pose_terminator
sMrMimePose25:
ax_pose 0, 0x01ea, 0x80f0, 0xbc00
ax_pose_terminator
sMrMimePose26:
ax_pose 1, 0x01ec, 0x80f5, 0xbc00
ax_pose_terminator
sMrMimePose27:
ax_pose 2, 0x01ec, 0x80f5, 0xbc00
ax_pose_terminator
sMrMimePose28:
ax_pose 3, 0x01e4, 0x90ec, 0xbc00
ax_pose_terminator
sMrMimePose29:
ax_pose 4, 0x01e4, 0x90ec, 0xbc00
ax_pose_terminator
sMrMimePose30:
ax_pose 5, 0x01e4, 0x90ec, 0xbc00
ax_pose_terminator
sMrMimePose31:
ax_pose 6, 0x81e4, 0x90f8, 0xbc00
ax_pose_terminator
sMrMimePose32:
ax_pose 7, 0x01e4, 0x90ec, 0xbc00
ax_pose_terminator
sMrMimePose33:
ax_pose 8, 0x01e4, 0x90ec, 0xbc00
ax_pose_terminator
sMrMimePose34:
ax_pose 9, 0x01e4, 0x90ee, 0xbc00
ax_pose_terminator
sMrMimePose35:
ax_pose 10, 0x01e4, 0x90f0, 0xbc00
ax_pose_terminator
sMrMimePose36:
ax_pose 11, 0x01e4, 0x90ee, 0xbc00
ax_pose_terminator
sMrMimePose37:
ax_pose 12, 0x01ea, 0x80f0, 0xbc00
ax_pose_terminator
sMrMimePose38:
ax_pose 13, 0x01ec, 0x80f4, 0xbc00
ax_pose_terminator
sMrMimePose39:
ax_pose 14, 0x01ec, 0x80f4, 0xbc00
ax_pose_terminator
sMrMimePose40:
ax_pose 9, 0x01e4, 0x80f2, 0xbc00
ax_pose_terminator
sMrMimePose41:
ax_pose 10, 0x01e4, 0x80f0, 0xbc00
ax_pose_terminator
sMrMimePose42:
ax_pose 11, 0x01e4, 0x80f2, 0xbc00
ax_pose_terminator
sMrMimePose43:
ax_pose 6, 0x81e4, 0x80f8, 0xbc00
ax_pose_terminator
sMrMimePose44:
ax_pose 7, 0x01e4, 0x80f4, 0xbc00
ax_pose_terminator
sMrMimePose45:
ax_pose 8, 0x01e4, 0x80f4, 0xbc00
ax_pose_terminator
sMrMimePose46:
ax_pose 3, 0x01e4, 0x80f5, 0xbc00
ax_pose_terminator
sMrMimePose47:
ax_pose 4, 0x01e4, 0x80f5, 0xbc00
ax_pose_terminator
sMrMimePose48:
ax_pose 5, 0x01e4, 0x80f5, 0xbc00
ax_pose_terminator
sMrMimePose49:
ax_pose 0, 0x01ea, 0x80f0, 0xbc00
ax_pose_terminator
sMrMimePose50:
ax_pose 1, 0x01ec, 0x80f5, 0xbc00
ax_pose_terminator
sMrMimePose51:
ax_pose 2, 0x01ec, 0x80f5, 0xbc00
ax_pose_terminator
sMrMimePose52:
ax_pose 3, 0x01e4, 0x90ec, 0xbc00
ax_pose_terminator
sMrMimePose53:
ax_pose 4, 0x01e4, 0x90ec, 0xbc00
ax_pose_terminator
sMrMimePose54:
ax_pose 5, 0x01e4, 0x90ec, 0xbc00
ax_pose_terminator
sMrMimePose55:
ax_pose 6, 0x81e4, 0x90f8, 0xbc00
ax_pose_terminator
sMrMimePose56:
ax_pose 7, 0x01e4, 0x90ec, 0xbc00
ax_pose_terminator
sMrMimePose57:
ax_pose 8, 0x01e4, 0x90ec, 0xbc00
ax_pose_terminator
sMrMimePose58:
ax_pose 9, 0x01e4, 0x90ee, 0xbc00
ax_pose_terminator
sMrMimePose59:
ax_pose 10, 0x01e4, 0x90f0, 0xbc00
ax_pose_terminator
sMrMimePose60:
ax_pose 11, 0x01e4, 0x90ee, 0xbc00
ax_pose_terminator
sMrMimePose61:
ax_pose 12, 0x01ea, 0x80f0, 0xbc00
ax_pose_terminator
sMrMimePose62:
ax_pose 13, 0x01ec, 0x80f4, 0xbc00
ax_pose_terminator
sMrMimePose63:
ax_pose 14, 0x01ec, 0x80f4, 0xbc00
ax_pose_terminator
sMrMimePose64:
ax_pose 9, 0x01e4, 0x80f2, 0xbc00
ax_pose_terminator
sMrMimePose65:
ax_pose 10, 0x01e4, 0x80f0, 0xbc00
ax_pose_terminator
sMrMimePose66:
ax_pose 11, 0x01e4, 0x80f2, 0xbc00
ax_pose_terminator
sMrMimePose67:
ax_pose 6, 0x81e4, 0x80f8, 0xbc00
ax_pose_terminator
sMrMimePose68:
ax_pose 7, 0x01e4, 0x80f4, 0xbc00
ax_pose_terminator
sMrMimePose69:
ax_pose 8, 0x01e4, 0x80f4, 0xbc00
ax_pose_terminator
sMrMimePose70:
ax_pose 3, 0x01e4, 0x80f5, 0xbc00
ax_pose_terminator
sMrMimePose71:
ax_pose 4, 0x01e4, 0x80f5, 0xbc00
ax_pose_terminator
sMrMimePose72:
ax_pose 5, 0x01e4, 0x80f5, 0xbc00
ax_pose_terminator
sMrMimePose73:
ax_pose 15, 0x01e7, 0x80f0, 0xbc00
ax_pose_terminator
sMrMimePose74:
ax_pose 16, 0x01e7, 0x80f0, 0xbc00
ax_pose_terminator
sMrMimePose75:
ax_pose 17, 0x01e7, 0x80f0, 0xbc00
ax_pose_terminator
sMrMimePose76:
ax_pose 18, 0x01e7, 0x80f0, 0xbc00
ax_pose_terminator
sMrMimePose77:
ax_pose 0, 0x01ea, 0x80f0, 0xbc00
ax_pose_terminator
sMrMimePose78:
ax_pose 19, 0x01e7, 0x90f0, 0xbc00
ax_pose_terminator
sMrMimePose79:
ax_pose 20, 0x01e7, 0x90f0, 0xbc00
ax_pose_terminator
sMrMimePose80:
ax_pose 21, 0x01e7, 0x90f0, 0xbc00
ax_pose_terminator
sMrMimePose81:
ax_pose 22, 0x01e7, 0x90f0, 0xbc00
ax_pose_terminator
sMrMimePose82:
ax_pose 3, 0x01e4, 0x90ec, 0xbc00
ax_pose_terminator
sMrMimePose83:
ax_pose 23, 0x01e4, 0x90f5, 0xbc00
ax_pose_terminator
sMrMimePose84:
ax_pose 24, 0x01e4, 0x90f5, 0xbc00
ax_pose_terminator
sMrMimePose85:
ax_pose 25, 0x01e4, 0x90f5, 0xbc00
ax_pose_terminator
sMrMimePose86:
ax_pose 26, 0x01e4, 0x90f5, 0xbc00
ax_pose_terminator
sMrMimePose87:
ax_pose 6, 0x81e4, 0x90f8, 0xbc00
ax_pose_terminator
sMrMimePose88:
ax_pose 27, 0x01e6, 0x90f6, 0xbc00
ax_pose_terminator
sMrMimePose89:
ax_pose 28, 0x01e6, 0x90f6, 0xbc00
ax_pose_terminator
sMrMimePose90:
ax_pose 29, 0x01e6, 0x90f6, 0xbc00
ax_pose_terminator
sMrMimePose91:
ax_pose 30, 0x01e6, 0x90f6, 0xbc00
ax_pose_terminator
sMrMimePose92:
ax_pose 9, 0x01e4, 0x90ee, 0xbc00
ax_pose_terminator
sMrMimePose93:
ax_pose 31, 0x01e6, 0x80f0, 0xbc00
ax_pose_terminator
sMrMimePose94:
ax_pose 32, 0x01e6, 0x80f0, 0xbc00
ax_pose_terminator
sMrMimePose95:
ax_pose 33, 0x01e6, 0x80f0, 0xbc00
ax_pose_terminator
sMrMimePose96:
ax_pose 34, 0x01e6, 0x80f0, 0xbc00
ax_pose_terminator
sMrMimePose97:
ax_pose 12, 0x01ea, 0x80f0, 0xbc00
ax_pose_terminator
sMrMimePose98:
ax_pose 27, 0x01e6, 0x80ea, 0xbc00
ax_pose_terminator
sMrMimePose99:
ax_pose 28, 0x01e6, 0x80ea, 0xbc00
ax_pose_terminator
sMrMimePose100:
ax_pose 29, 0x01e6, 0x80ea, 0xbc00
ax_pose_terminator
sMrMimePose101:
ax_pose 30, 0x01e6, 0x80ea, 0xbc00
ax_pose_terminator
sMrMimePose102:
ax_pose 9, 0x01e4, 0x80f2, 0xbc00
ax_pose_terminator
sMrMimePose103:
ax_pose 23, 0x01e4, 0x80eb, 0xbc00
ax_pose_terminator
sMrMimePose104:
ax_pose 24, 0x01e4, 0x80eb, 0xbc00
ax_pose_terminator
sMrMimePose105:
ax_pose 25, 0x01e4, 0x80eb, 0xbc00
ax_pose_terminator
sMrMimePose106:
ax_pose 26, 0x01e4, 0x80eb, 0xbc00
ax_pose_terminator
sMrMimePose107:
ax_pose 6, 0x81e4, 0x80f8, 0xbc00
ax_pose_terminator
sMrMimePose108:
ax_pose 19, 0x01e7, 0x80f0, 0xbc00
ax_pose_terminator
sMrMimePose109:
ax_pose 20, 0x01e7, 0x80f0, 0xbc00
ax_pose_terminator
sMrMimePose110:
ax_pose 21, 0x01e7, 0x80f0, 0xbc00
ax_pose_terminator
sMrMimePose111:
ax_pose 22, 0x01e7, 0x80f0, 0xbc00
ax_pose_terminator
sMrMimePose112:
ax_pose 3, 0x01e4, 0x80f5, 0xbc00
ax_pose_terminator
sMrMimePose113:
ax_pose 35, 0x01e4, 0x80f4, 0xbc00
ax_pose_terminator
sMrMimePose114:
ax_pose 36, 0x01e4, 0x80f3, 0xbc00
ax_pose_terminator
sMrMimePose115:
ax_pose 37, 0x01e4, 0x80f0, 0xbc00
ax_pose_terminator
sMrMimePose116:
ax_pose 38, 0x01e4, 0x80f2, 0xbc00
ax_pose_terminator
sMrMimePose117:
ax_pose 39, 0x01e4, 0x80f4, 0xbc00
ax_pose_terminator
sMrMimePose118:
ax_pose 40, 0x01e4, 0x80f4, 0xbc00
ax_pose_terminator
sMrMimePose119:
ax_pose 41, 0x01e4, 0x80f4, 0xbc00
ax_pose_terminator
sMrMimePose120:
ax_pose 42, 0x01e4, 0x80f6, 0xbc00
ax_pose_terminator
sMrMimePose121:
ax_pose 43, 0x01e9, 0x80f1, 0xbc00
ax_pose_terminator
sMrMimePose122:
ax_pose 44, 0x01e9, 0x80f1, 0xbc00
ax_pose_terminator
sMrMimePose123:
ax_pose 45, 0x01e2, 0x80f0, 0xbc00
ax_pose_terminator
sMrMimePose124:
ax_pose 46, 0x01e3, 0x90ec, 0xbc00
ax_pose_terminator
sMrMimePose125:
ax_pose 47, 0x01e3, 0x90ea, 0xbc00
ax_pose_terminator
sMrMimePose126:
ax_pose 48, 0x01e3, 0x90f0, 0xbc00
ax_pose_terminator
sMrMimePose127:
ax_pose 49, 0x01e2, 0x80f1, 0xbc00
ax_pose_terminator
sMrMimePose128:
ax_pose 48, 0x01e3, 0x80f0, 0xbc00
ax_pose_terminator
sMrMimePose129:
ax_pose 47, 0x01e3, 0x80f6, 0xbc00
ax_pose_terminator
sMrMimePose130:
ax_pose 46, 0x01e3, 0x80f4, 0xbc00
ax_pose_terminator
sMrMimePose131:
ax_pose 35, 0x01e4, 0x80f4, 0xbc00
ax_pose_terminator
sMrMimePose132:
ax_pose 36, 0x01e4, 0x80f3, 0xbc00
ax_pose_terminator
sMrMimePose133:
ax_pose 37, 0x01e4, 0x80f0, 0xbc00
ax_pose_terminator
sMrMimePose134:
ax_pose 38, 0x01e4, 0x80f2, 0xbc00
ax_pose_terminator
sMrMimePose135:
ax_pose 39, 0x01e4, 0x80f4, 0xbc00
ax_pose_terminator
sMrMimePose136:
ax_pose 40, 0x01e4, 0x80f4, 0xbc00
ax_pose_terminator
sMrMimePose137:
ax_pose 41, 0x01e4, 0x80f4, 0xbc00
ax_pose_terminator
sMrMimePose138:
ax_pose 42, 0x01e4, 0x80f6, 0xbc00
ax_pose_terminator
sMrMimePose139:
ax_pose 50, 0x01e4, 0x80f4, 0xbc00
ax_pose_terminator
sMrMimePose140:
ax_pose 51, 0x01e4, 0x80f3, 0xbc00
ax_pose_terminator
sMrMimePose141:
ax_pose 52, 0x01e4, 0x80f0, 0xbc00
ax_pose_terminator
sMrMimePose142:
ax_pose 53, 0x01e4, 0x80f2, 0xbc00
ax_pose_terminator
sMrMimePose143:
ax_pose 54, 0x01e4, 0x80f4, 0xbc00
ax_pose_terminator
sMrMimePose144:
ax_pose 55, 0x01e4, 0x80f4, 0xbc00
ax_pose_terminator
sMrMimePose145:
ax_pose 56, 0x01e4, 0x80f4, 0xbc00
ax_pose_terminator
sMrMimePose146:
ax_pose 57, 0x01e4, 0x80f6, 0xbc00
ax_pose_terminator
sMrMimePose147:
ax_pose 18, 0x01e5, 0x80f0, 0xbc00
ax_pose_terminator
sMrMimePose148:
ax_pose 22, 0x01e6, 0x80f0, 0xbc00
ax_pose_terminator
sMrMimePose149:
ax_pose 26, 0x01e5, 0x80f0, 0xbc00
ax_pose_terminator
sMrMimePose150:
ax_pose 30, 0x01e9, 0x80f0, 0xbc00
ax_pose_terminator
sMrMimePose151:
ax_pose 34, 0x01eb, 0x80f0, 0xbc00
ax_pose_terminator
sMrMimePose152:
ax_pose 30, 0x01e9, 0x90f0, 0xbc00
ax_pose_terminator
sMrMimePose153:
ax_pose 26, 0x01e5, 0x90f0, 0xbc00
ax_pose_terminator
sMrMimePose154:
ax_pose 22, 0x01e6, 0x90f0, 0xbc00
ax_pose_terminator
sMrMimePose155:
ax_pose 35, 0x01e4, 0x80f4, 0xbc00
ax_pose_terminator
sMrMimePose156:
ax_pose 42, 0x01e4, 0x80f6, 0xbc00
ax_pose_terminator
sMrMimePose157:
ax_pose 41, 0x01e4, 0x80f4, 0xbc00
ax_pose_terminator
sMrMimePose158:
ax_pose 40, 0x01e4, 0x80f4, 0xbc00
ax_pose_terminator
sMrMimePose159:
ax_pose 39, 0x01e4, 0x80f4, 0xbc00
ax_pose_terminator
sMrMimePose160:
ax_pose 38, 0x01e4, 0x80f2, 0xbc00
ax_pose_terminator
sMrMimePose161:
ax_pose 37, 0x01e4, 0x80f0, 0xbc00
ax_pose_terminator
sMrMimePose162:
ax_pose 36, 0x01e4, 0x80f3, 0xbc00
ax_pose_terminator
sMrMimePose163:
ax_pose 0, 0x01ea, 0x80f0, 0xbc00
ax_pose_terminator
sMrMimePose164:
ax_pose 1, 0x01ec, 0x80f5, 0xbc00
ax_pose_terminator
sMrMimePose165:
ax_pose 2, 0x01ec, 0x80f5, 0xbc00
ax_pose_terminator
sMrMimePose166:
ax_pose 3, 0x01e4, 0x90ec, 0xbc00
ax_pose_terminator
sMrMimePose167:
ax_pose 4, 0x01e4, 0x90ec, 0xbc00
ax_pose_terminator
sMrMimePose168:
ax_pose 5, 0x01e4, 0x90ec, 0xbc00
ax_pose_terminator
sMrMimePose169:
ax_pose 6, 0x81e4, 0x90f8, 0xbc00
ax_pose_terminator
sMrMimePose170:
ax_pose 7, 0x01e4, 0x90ec, 0xbc00
ax_pose_terminator
sMrMimePose171:
ax_pose 8, 0x01e4, 0x90ec, 0xbc00
ax_pose_terminator
sMrMimePose172:
ax_pose 9, 0x01e4, 0x90ee, 0xbc00
ax_pose_terminator
sMrMimePose173:
ax_pose 10, 0x01e4, 0x90f0, 0xbc00
ax_pose_terminator
sMrMimePose174:
ax_pose 11, 0x01e4, 0x90ee, 0xbc00
ax_pose_terminator
sMrMimePose175:
ax_pose 12, 0x01ea, 0x80f0, 0xbc00
ax_pose_terminator
sMrMimePose176:
ax_pose 13, 0x01ec, 0x80f4, 0xbc00
ax_pose_terminator
sMrMimePose177:
ax_pose 14, 0x01ec, 0x80f4, 0xbc00
ax_pose_terminator
sMrMimePose178:
ax_pose 9, 0x01e4, 0x80f2, 0xbc00
ax_pose_terminator
sMrMimePose179:
ax_pose 10, 0x01e4, 0x80f0, 0xbc00
ax_pose_terminator
sMrMimePose180:
ax_pose 11, 0x01e4, 0x80f2, 0xbc00
ax_pose_terminator
sMrMimePose181:
ax_pose 6, 0x81e4, 0x80f8, 0xbc00
ax_pose_terminator
sMrMimePose182:
ax_pose 7, 0x01e4, 0x80f4, 0xbc00
ax_pose_terminator
sMrMimePose183:
ax_pose 8, 0x01e4, 0x80f4, 0xbc00
ax_pose_terminator
sMrMimePose184:
ax_pose 3, 0x01e4, 0x80f5, 0xbc00
ax_pose_terminator
sMrMimePose185:
ax_pose 4, 0x01e4, 0x80f5, 0xbc00
ax_pose_terminator
sMrMimePose186:
ax_pose 5, 0x01e4, 0x80f5, 0xbc00
ax_pose_terminator
sMrMimePose187:
ax_pose 18, 0x01e5, 0x80f0, 0xbc00
ax_pose_terminator
sMrMimePose188:
ax_pose 22, 0x01e6, 0x80f0, 0xbc00
ax_pose_terminator
sMrMimePose189:
ax_pose 26, 0x01e5, 0x80f0, 0xbc00
ax_pose_terminator
sMrMimePose190:
ax_pose 30, 0x01e9, 0x80f0, 0xbc00
ax_pose_terminator
sMrMimePose191:
ax_pose 34, 0x01eb, 0x80f0, 0xbc00
ax_pose_terminator
sMrMimePose192:
ax_pose 30, 0x01e9, 0x90f0, 0xbc00
ax_pose_terminator
sMrMimePose193:
ax_pose 26, 0x01e5, 0x90f0, 0xbc00
ax_pose_terminator
sMrMimePose194:
ax_pose 22, 0x01e6, 0x90f0, 0xbc00
ax_pose_terminator
sMrMimePose195:
ax_pose 35, 0x01e4, 0x80f4, 0xbc00
ax_pose_terminator
sMrMimePose196:
ax_pose 36, 0x01e4, 0x80f3, 0xbc00
ax_pose_terminator
sMrMimePose197:
ax_pose 37, 0x01e4, 0x80f0, 0xbc00
ax_pose_terminator
sMrMimePose198:
ax_pose 38, 0x01e4, 0x80f2, 0xbc00
ax_pose_terminator
sMrMimePose199:
ax_pose 39, 0x01e4, 0x80f4, 0xbc00
ax_pose_terminator
sMrMimePose200:
ax_pose 40, 0x01e4, 0x80f4, 0xbc00
ax_pose_terminator
sMrMimePose201:
ax_pose 41, 0x01e4, 0x80f4, 0xbc00
ax_pose_terminator
sMrMimePose202:
ax_pose 42, 0x01e4, 0x80f6, 0xbc00
ax_pose_terminator
.align 2
sMrMimeAnims_1_1:
ax_anim 8, 0, 0, 0, 0, 0, 0,
ax_anim 12, 0, 1, 0, 0, 0, 0,
ax_anim 8, 0, 0, 0, 0, 0, 0,
ax_anim 12, 0, 2, 0, 0, 0, 0,
ax_anim_terminator
sMrMimeAnims_1_2:
ax_anim 8, 0, 3, 0, 0, 0, 0,
ax_anim 12, 0, 4, 0, 0, 0, 0,
ax_anim 8, 0, 3, 0, 0, 0, 0,
ax_anim 12, 0, 5, 0, 0, 0, 0,
ax_anim_terminator
sMrMimeAnims_1_3:
ax_anim 8, 0, 6, 0, 0, 0, 0,
ax_anim 12, 0, 7, 0, 0, 0, 0,
ax_anim 8, 0, 6, 0, 0, 0, 0,
ax_anim 12, 0, 8, 0, 0, 0, 0,
ax_anim_terminator
sMrMimeAnims_1_4:
ax_anim 8, 0, 9, 0, 0, 0, 0,
ax_anim 12, 0, 10, 0, 0, 0, 0,
ax_anim 8, 0, 9, 0, 0, 0, 0,
ax_anim 12, 0, 11, 0, 0, 0, 0,
ax_anim_terminator
sMrMimeAnims_1_5:
ax_anim 8, 0, 12, 0, 0, 0, 0,
ax_anim 12, 0, 13, 0, 0, 0, 0,
ax_anim 8, 0, 12, 0, 0, 0, 0,
ax_anim 12, 0, 14, 0, 0, 0, 0,
ax_anim_terminator
sMrMimeAnims_1_6:
ax_anim 8, 0, 15, 0, 0, 0, 0,
ax_anim 12, 0, 16, 0, 0, 0, 0,
ax_anim 8, 0, 15, 0, 0, 0, 0,
ax_anim 12, 0, 17, 0, 0, 0, 0,
ax_anim_terminator
sMrMimeAnims_1_7:
ax_anim 8, 0, 18, 0, 0, 0, 0,
ax_anim 12, 0, 19, 0, 0, 0, 0,
ax_anim 8, 0, 18, 0, 0, 0, 0,
ax_anim 12, 0, 20, 0, 0, 0, 0,
ax_anim_terminator
sMrMimeAnims_1_8:
ax_anim 8, 0, 21, 0, 0, 0, 0,
ax_anim 12, 0, 22, 0, 0, 0, 0,
ax_anim 8, 0, 21, 0, 0, 0, 0,
ax_anim 12, 0, 23, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sMrMimeAnims_2_1:
ax_anim 2, 0, 24, 0, -1, 0, -1,
ax_anim 6, 0, 24, 0, -2, 0, -2,
ax_anim 1, 0, 26, 0, 0, 0, 0,
ax_anim 1, 2, 25, 0, 4, 0, 4,
ax_anim 1, 0, 26, 0, 10, 0, 10,
ax_anim 2, 0, 25, 0, 18, 0, 18,
ax_anim 2, 1, 25, 1, 18, 1, 18,
ax_anim 2, 0, 25, 0, 18, 0, 18,
ax_anim 2, 0, 25, 1, 18, 1, 18,
ax_anim 2, 0, 24, 0, 6, 0, 6,
ax_anim 2, 0, 24, 0, 3, 0, 3,
ax_anim_terminator
sMrMimeAnims_2_2:
ax_anim 2, 0, 27, -1, -1, -1, -1,
ax_anim 6, 0, 27, -2, -2, -2, -2,
ax_anim 1, 0, 29, 0, 0, 0, 0,
ax_anim 1, 2, 28, 4, 4, 4, 4,
ax_anim 1, 0, 29, 10, 10, 10, 10,
ax_anim 2, 0, 28, 18, 18, 18, 18,
ax_anim 2, 1, 28, 19, 17, 19, 17,
ax_anim 2, 0, 28, 18, 18, 18, 18,
ax_anim 2, 0, 28, 19, 17, 19, 17,
ax_anim 2, 0, 27, 6, 6, 6, 6,
ax_anim 2, 0, 27, 3, 3, 3, 3,
ax_anim_terminator
sMrMimeAnims_2_3:
ax_anim 2, 0, 30, -1, 0, -1, 0,
ax_anim 6, 0, 30, -2, 0, -2, 0,
ax_anim 1, 0, 32, 0, 0, 0, 0,
ax_anim 1, 2, 31, 4, 0, 4, 0,
ax_anim 1, 0, 32, 10, 0, 10, 0,
ax_anim 2, 0, 31, 18, 0, 18, 0,
ax_anim 2, 1, 31, 18, 1, 18, 1,
ax_anim 2, 0, 31, 18, 0, 18, 0,
ax_anim 2, 0, 31, 18, 1, 18, 1,
ax_anim 2, 0, 30, 6, 0, 6, 0,
ax_anim 2, 0, 30, 3, 0, 3, 0,
ax_anim_terminator
sMrMimeAnims_2_4:
ax_anim 2, 0, 33, -1, 1, -1, 1,
ax_anim 6, 0, 33, -2, 2, -2, 2,
ax_anim 1, 0, 35, 0, -1, 0, -1,
ax_anim 1, 2, 34, 4, -6, 4, -6,
ax_anim 1, 0, 35, 10, -13, 10, -13,
ax_anim 2, 0, 34, 18, -23, 18, -23,
ax_anim 2, 1, 34, 19, -22, 19, -22,
ax_anim 2, 0, 34, 18, -23, 18, -23,
ax_anim 2, 0, 34, 19, -22, 19, -22,
ax_anim 2, 0, 33, 6, -6, 6, -6,
ax_anim 2, 0, 33, 3, -3, 3, -3,
ax_anim_terminator
sMrMimeAnims_2_5:
ax_anim 2, 0, 36, 0, 1, 0, 1,
ax_anim 6, 0, 36, 0, 2, 0, 2,
ax_anim 1, 0, 38, 0, 0, 0, 0,
ax_anim 1, 2, 37, 0, -4, 0, -4,
ax_anim 1, 0, 38, 0, -11, 0, -11,
ax_anim 2, 0, 37, 0, -21, 0, -21,
ax_anim 2, 1, 37, 1, -21, 1, -21,
ax_anim 2, 0, 37, 0, -21, 0, -21,
ax_anim 2, 0, 37, 1, -21, 1, -21,
ax_anim 2, 0, 36, 0, -6, 0, -6,
ax_anim 2, 0, 36, 0, -3, 0, -3,
ax_anim_terminator
sMrMimeAnims_2_6:
ax_anim 2, 0, 39, 1, 1, 1, 1,
ax_anim 6, 0, 39, 2, 2, 2, 2,
ax_anim 1, 0, 41, 0, -1, 0, -1,
ax_anim 1, 2, 40, -4, -6, -4, -6,
ax_anim 1, 0, 41, -10, -13, -10, -13,
ax_anim 2, 0, 40, -18, -23, -18, -23,
ax_anim 2, 1, 40, -19, -22, -19, -22,
ax_anim 2, 0, 40, -18, -23, -18, -23,
ax_anim 2, 0, 40, -19, -22, -19, -22,
ax_anim 2, 0, 39, -6, -6, -6, -6,
ax_anim 2, 0, 39, -3, -3, -3, -3,
ax_anim_terminator
sMrMimeAnims_2_7:
ax_anim 2, 0, 42, 1, 0, 1, 0,
ax_anim 6, 0, 42, 2, 0, 2, 0,
ax_anim 1, 0, 44, 0, 0, 0, 0,
ax_anim 1, 2, 43, -4, 0, -4, 0,
ax_anim 1, 0, 44, -10, 0, -10, 0,
ax_anim 2, 0, 43, -18, 0, -18, 0,
ax_anim 2, 1, 43, -18, 1, -18, 1,
ax_anim 2, 0, 43, -18, 0, -18, 0,
ax_anim 2, 0, 43, -18, 1, -18, 1,
ax_anim 2, 0, 42, -6, 0, -6, 0,
ax_anim 2, 0, 42, -3, 0, -3, 0,
ax_anim_terminator
sMrMimeAnims_2_8:
ax_anim 2, 0, 45, 1, -1, 1, -1,
ax_anim 6, 0, 45, 2, -2, 2, -2,
ax_anim 1, 0, 47, 0, 0, 0, 0,
ax_anim 1, 2, 46, -4, 4, -4, 4,
ax_anim 1, 0, 47, -10, 10, -10, 10,
ax_anim 2, 0, 46, -17, 19, -17, 19,
ax_anim 2, 1, 46, -18, 18, -18, 18,
ax_anim 2, 0, 46, -17, 19, -17, 19,
ax_anim 2, 0, 46, -18, 18, -18, 18,
ax_anim 2, 0, 45, -6, 6, -6, 6,
ax_anim 2, 0, 45, -3, 3, -3, 3,
ax_anim_terminator
.align 2
sMrMimeAnims_3_1:
ax_anim 2, 0, 48, 0, -1, 0, -1,
ax_anim 6, 0, 48, 0, -2, 0, -2,
ax_anim 1, 0, 50, 0, 0, 0, 0,
ax_anim 1, 2, 49, 0, 4, 0, 4,
ax_anim 1, 0, 50, 0, 10, 0, 10,
ax_anim 2, 0, 49, 0, 18, 0, 18,
ax_anim 2, 1, 49, 1, 18, 1, 18,
ax_anim 2, 0, 49, 0, 18, 0, 18,
ax_anim 2, 0, 49, 1, 18, 1, 18,
ax_anim 2, 0, 48, 0, 6, 0, 6,
ax_anim 2, 0, 48, 0, 3, 0, 3,
ax_anim_terminator
sMrMimeAnims_3_2:
ax_anim 2, 0, 51, -1, -1, -1, -1,
ax_anim 6, 0, 51, -2, -2, -2, -2,
ax_anim 1, 0, 53, 0, 0, 0, 0,
ax_anim 1, 2, 52, 4, 4, 4, 4,
ax_anim 1, 0, 53, 10, 10, 10, 10,
ax_anim 2, 0, 52, 18, 18, 18, 18,
ax_anim 2, 1, 52, 19, 17, 19, 17,
ax_anim 2, 0, 52, 18, 18, 18, 18,
ax_anim 2, 0, 52, 19, 17, 19, 17,
ax_anim 2, 0, 51, 6, 6, 6, 6,
ax_anim 2, 0, 51, 3, 3, 3, 3,
ax_anim_terminator
sMrMimeAnims_3_3:
ax_anim 2, 0, 54, -1, 0, -1, 0,
ax_anim 6, 0, 54, -2, 0, -2, 0,
ax_anim 1, 0, 56, 0, 0, 0, 0,
ax_anim 1, 2, 55, 4, 0, 4, 0,
ax_anim 1, 0, 56, 10, 0, 10, 0,
ax_anim 2, 0, 55, 18, 0, 18, 0,
ax_anim 2, 1, 55, 18, 1, 18, 1,
ax_anim 2, 0, 55, 18, 0, 18, 0,
ax_anim 2, 0, 55, 18, 1, 18, 1,
ax_anim 2, 0, 54, 6, 0, 6, 0,
ax_anim 2, 0, 54, 3, 0, 3, 0,
ax_anim_terminator
sMrMimeAnims_3_4:
ax_anim 2, 0, 57, -1, 1, -1, 1,
ax_anim 6, 0, 57, -2, 2, -2, 2,
ax_anim 1, 0, 59, 0, -1, 0, -1,
ax_anim 1, 2, 58, 4, -6, 4, -6,
ax_anim 1, 0, 59, 10, -13, 10, -13,
ax_anim 2, 0, 58, 18, -23, 18, -23,
ax_anim 2, 1, 58, 19, -22, 19, -22,
ax_anim 2, 0, 58, 18, -23, 18, -23,
ax_anim 2, 0, 58, 19, -22, 19, -22,
ax_anim 2, 0, 57, 6, -6, 6, -6,
ax_anim 2, 0, 57, 3, -3, 3, -3,
ax_anim_terminator
sMrMimeAnims_3_5:
ax_anim 2, 0, 60, 0, 1, 0, 1,
ax_anim 6, 0, 60, 0, 2, 0, 2,
ax_anim 1, 0, 62, 0, 0, 0, 0,
ax_anim 1, 2, 61, 0, -4, 0, -4,
ax_anim 1, 0, 62, 0, -11, 0, -11,
ax_anim 2, 0, 61, 0, -21, 0, -21,
ax_anim 2, 1, 61, 1, -21, 1, -21,
ax_anim 2, 0, 61, 0, -21, 0, -21,
ax_anim 2, 0, 61, 1, -21, 1, -21,
ax_anim 2, 0, 60, 0, -6, 0, -6,
ax_anim 2, 0, 60, 0, -3, 0, -3,
ax_anim_terminator
sMrMimeAnims_3_6:
ax_anim 2, 0, 63, 1, 1, 1, 1,
ax_anim 6, 0, 63, 2, 2, 2, 2,
ax_anim 1, 0, 65, 0, -1, 0, -1,
ax_anim 1, 2, 64, -4, -6, -4, -6,
ax_anim 1, 0, 65, -10, -13, -10, -13,
ax_anim 2, 0, 64, -18, -23, -18, -23,
ax_anim 2, 1, 64, -19, -22, -19, -22,
ax_anim 2, 0, 64, -18, -23, -18, -23,
ax_anim 2, 0, 64, -19, -22, -19, -22,
ax_anim 2, 0, 63, -6, -6, -6, -6,
ax_anim 2, 0, 63, -3, -3, -3, -3,
ax_anim_terminator
sMrMimeAnims_3_7:
ax_anim 2, 0, 66, 1, 0, 1, 0,
ax_anim 6, 0, 66, 2, 0, 2, 0,
ax_anim 1, 0, 68, 0, 0, 0, 0,
ax_anim 1, 2, 67, -4, 0, -4, 0,
ax_anim 1, 0, 68, -10, 0, -10, 0,
ax_anim 2, 0, 67, -18, 0, -18, 0,
ax_anim 2, 1, 67, -18, 1, -18, 1,
ax_anim 2, 0, 67, -18, 0, -18, 0,
ax_anim 2, 0, 67, -18, 1, -18, 1,
ax_anim 2, 0, 66, -6, 0, -6, 0,
ax_anim 2, 0, 66, -3, 0, -3, 0,
ax_anim_terminator
sMrMimeAnims_3_8:
ax_anim 2, 0, 69, 1, -1, 1, -1,
ax_anim 6, 0, 69, 2, -2, 2, -2,
ax_anim 1, 0, 71, 0, 0, 0, 0,
ax_anim 1, 2, 70, -4, 4, -4, 4,
ax_anim 1, 0, 71, -10, 10, -10, 10,
ax_anim 2, 0, 70, -17, 19, -17, 19,
ax_anim 2, 1, 70, -18, 18, -18, 18,
ax_anim 2, 0, 70, -17, 19, -17, 19,
ax_anim 2, 0, 70, -18, 18, -18, 18,
ax_anim 2, 0, 69, -6, 6, -6, 6,
ax_anim 2, 0, 69, -3, 3, -3, 3,
ax_anim_terminator
.align 2
sMrMimeAnims_4_1:
ax_anim 4, 0, 72, 0, 0, 0, 0,
ax_anim 4, 0, 73, 0, 0, 0, 0,
ax_anim 4, 0, 74, 0, 0, 0, 0,
ax_anim 4, 0, 73, 0, 0, 0, 0,
ax_anim 4, 0, 72, 0, 0, 0, 0,
ax_anim 2, 2, 73, 0, 0, 0, 0,
ax_anim 2, 0, 74, 0, 0, 0, 0,
ax_anim 2, 0, 72, 0, 0, 0, 0,
ax_anim 1, 0, 75, 0, 0, 0, 0,
ax_anim 1, 0, 75, 0, 3, 0, 3,
ax_anim 2, 1, 75, 0, 5, 0, 5,
ax_anim 2, 0, 75, 1, 5, 1, 5,
ax_anim 2, 0, 75, 0, 5, 0, 5,
ax_anim 2, 0, 75, 1, 5, 1, 5,
ax_anim 2, 0, 76, 0, 2, 0, 2,
ax_anim_terminator
sMrMimeAnims_4_2:
ax_anim 4, 0, 77, 0, 0, 0, 0,
ax_anim 4, 0, 78, 0, 0, 0, 0,
ax_anim 4, 0, 79, 0, 0, 0, 0,
ax_anim 4, 0, 78, 0, 0, 0, 0,
ax_anim 4, 0, 77, 0, 0, 0, 0,
ax_anim 2, 2, 78, 0, 0, 0, 0,
ax_anim 2, 0, 79, 0, 0, 0, 0,
ax_anim 2, 0, 77, 0, 0, 0, 0,
ax_anim 1, 0, 80, 0, 0, 0, 0,
ax_anim 1, 0, 80, 3, 3, 3, 3,
ax_anim 2, 1, 80, 5, 5, 5, 5,
ax_anim 2, 0, 80, 6, 4, 6, 4,
ax_anim 2, 0, 80, 5, 5, 5, 5,
ax_anim 2, 0, 80, 6, 4, 6, 4,
ax_anim 2, 0, 81, 2, 2, 2, 2,
ax_anim_terminator
sMrMimeAnims_4_3:
ax_anim 4, 0, 82, 0, 0, 0, 0,
ax_anim 4, 0, 83, 0, 0, 0, 0,
ax_anim 4, 0, 84, 0, 0, 0, 0,
ax_anim 4, 0, 83, 0, 0, 0, 0,
ax_anim 4, 0, 82, 0, 0, 0, 0,
ax_anim 2, 2, 83, 0, 0, 0, 0,
ax_anim 2, 0, 84, 0, 0, 0, 0,
ax_anim 2, 0, 82, 0, 0, 0, 0,
ax_anim 1, 0, 85, 0, 0, 0, 0,
ax_anim 1, 0, 85, 3, 0, 3, 0,
ax_anim 2, 1, 85, 5, 0, 5, 0,
ax_anim 2, 0, 85, 5, -1, 5, -1,
ax_anim 2, 0, 85, 5, 0, 5, 0,
ax_anim 2, 0, 85, 5, -1, 5, -1,
ax_anim 2, 0, 86, 2, 0, 2, 0,
ax_anim_terminator
sMrMimeAnims_4_4:
ax_anim 4, 0, 87, 0, 0, 0, 0,
ax_anim 4, 0, 88, 0, 0, 0, 0,
ax_anim 4, 0, 89, 0, 0, 0, 0,
ax_anim 4, 0, 88, 0, 0, 0, 0,
ax_anim 4, 0, 87, 0, 0, 0, 0,
ax_anim 2, 2, 88, 0, 0, 0, 0,
ax_anim 2, 0, 89, 0, 0, 0, 0,
ax_anim 2, 0, 87, 0, 0, 0, 0,
ax_anim 1, 0, 90, 0, 0, 0, 0,
ax_anim 1, 0, 90, 3, -3, 3, -3,
ax_anim 2, 1, 90, 5, -5, 5, -5,
ax_anim 2, 0, 90, 6, -4, 6, -4,
ax_anim 2, 0, 90, 5, -5, 5, -5,
ax_anim 2, 0, 90, 6, -4, 6, -4,
ax_anim 2, 0, 91, 2, -2, 2, -2,
ax_anim_terminator
sMrMimeAnims_4_5:
ax_anim 4, 0, 92, 0, 0, 0, 0,
ax_anim 4, 0, 93, 0, 0, 0, 0,
ax_anim 4, 0, 94, 0, 0, 0, 0,
ax_anim 4, 0, 93, 0, 0, 0, 0,
ax_anim 4, 0, 92, 0, 0, 0, 0,
ax_anim 2, 2, 93, 0, 0, 0, 0,
ax_anim 2, 0, 94, 0, 0, 0, 0,
ax_anim 2, 0, 92, 0, 0, 0, 0,
ax_anim 1, 0, 95, 0, 0, 0, 0,
ax_anim 1, 0, 95, 0, -3, 0, -3,
ax_anim 2, 1, 95, 0, -5, 0, -5,
ax_anim 2, 0, 95, 1, -5, 1, -5,
ax_anim 2, 0, 95, 0, -5, 0, -5,
ax_anim 2, 0, 95, 1, -5, 1, -5,
ax_anim 2, 0, 96, 0, -2, 0, -2,
ax_anim_terminator
sMrMimeAnims_4_6:
ax_anim 4, 0, 97, 0, 0, 0, 0,
ax_anim 4, 0, 98, 0, 0, 0, 0,
ax_anim 4, 0, 99, 0, 0, 0, 0,
ax_anim 4, 0, 98, 0, 0, 0, 0,
ax_anim 4, 0, 97, 0, 0, 0, 0,
ax_anim 2, 2, 98, 0, 0, 0, 0,
ax_anim 2, 0, 99, 0, 0, 0, 0,
ax_anim 2, 0, 97, 0, 0, 0, 0,
ax_anim 1, 0, 100, 0, 0, 0, 0,
ax_anim 1, 0, 100, -3, -3, -3, -3,
ax_anim 2, 1, 100, -5, -5, -5, -5,
ax_anim 2, 0, 100, -6, -4, -6, -4,
ax_anim 2, 0, 100, -5, -5, -5, -5,
ax_anim 2, 0, 100, -6, -4, -6, -4,
ax_anim 2, 0, 101, -2, -2, -2, -2,
ax_anim_terminator
sMrMimeAnims_4_7:
ax_anim 4, 0, 102, 0, 0, 0, 0,
ax_anim 4, 0, 103, 0, 0, 0, 0,
ax_anim 4, 0, 104, 0, 0, 0, 0,
ax_anim 4, 0, 103, 0, 0, 0, 0,
ax_anim 4, 0, 102, 0, 0, 0, 0,
ax_anim 2, 2, 103, 0, 0, 0, 0,
ax_anim 2, 0, 104, 0, 0, 0, 0,
ax_anim 2, 0, 102, 0, 0, 0, 0,
ax_anim 1, 0, 105, 0, 0, 0, 0,
ax_anim 1, 0, 105, -3, 0, -3, 0,
ax_anim 2, 1, 105, -5, 0, -5, 0,
ax_anim 2, 0, 105, -5, -1, -5, -1,
ax_anim 2, 0, 105, -5, 0, -5, 0,
ax_anim 2, 0, 105, -5, -1, -5, -1,
ax_anim 2, 0, 106, -2, 0, -2, 0,
ax_anim_terminator
sMrMimeAnims_4_8:
ax_anim 4, 0, 107, 0, 0, 0, 0,
ax_anim 4, 0, 108, 0, 0, 0, 0,
ax_anim 4, 0, 109, 0, 0, 0, 0,
ax_anim 4, 0, 108, 0, 0, 0, 0,
ax_anim 4, 0, 107, 0, 0, 0, 0,
ax_anim 2, 2, 108, 0, 0, 0, 0,
ax_anim 2, 0, 109, 0, 0, 0, 0,
ax_anim 2, 0, 107, 0, 0, 0, 0,
ax_anim 1, 0, 110, 0, 0, 0, 0,
ax_anim 1, 0, 110, -3, 3, -3, 3,
ax_anim 2, 1, 110, -5, 5, -5, 5,
ax_anim 2, 0, 110, -6, 4, -6, 4,
ax_anim 2, 0, 110, -5, 5, -5, 5,
ax_anim 2, 0, 110, -6, 4, -6, 4,
ax_anim 2, 0, 111, -2, 2, -2, 2,
ax_anim_terminator
.align 2
sMrMimeAnims_5_1:
ax_anim 2, 0, 112, 0, 0, 0, 0,
ax_anim 2, 0, 113, 0, 0, 0, 0,
ax_anim 2, 0, 114, 0, 0, 0, 0,
ax_anim 2, 0, 115, 0, 0, 0, 0,
ax_anim 2, 0, 116, 0, 0, 0, 0,
ax_anim 2, 0, 117, 0, 0, 0, 0,
ax_anim 2, 0, 118, 0, 0, 0, 0,
ax_anim 2, 0, 119, 0, 0, 0, 0,
ax_anim 2, 2, 112, 0, 0, 0, 0,
ax_anim_terminator
sMrMimeAnims_5_2:
ax_anim 2, 0, 119, 0, 0, 0, 0,
ax_anim 2, 0, 112, 0, 0, 0, 0,
ax_anim 2, 0, 113, 0, 0, 0, 0,
ax_anim 2, 0, 114, 0, 0, 0, 0,
ax_anim 2, 0, 115, 0, 0, 0, 0,
ax_anim 2, 0, 116, 0, 0, 0, 0,
ax_anim 2, 0, 117, 0, 0, 0, 0,
ax_anim 2, 0, 118, 0, 0, 0, 0,
ax_anim 2, 2, 119, 0, 0, 0, 0,
ax_anim_terminator
sMrMimeAnims_5_3:
ax_anim 2, 0, 118, 0, 0, 0, 0,
ax_anim 2, 0, 119, 0, 0, 0, 0,
ax_anim 2, 0, 112, 0, 0, 0, 0,
ax_anim 2, 0, 113, 0, 0, 0, 0,
ax_anim 2, 0, 114, 0, 0, 0, 0,
ax_anim 2, 0, 115, 0, 0, 0, 0,
ax_anim 2, 0, 116, 0, 0, 0, 0,
ax_anim 2, 0, 117, 0, 0, 0, 0,
ax_anim 2, 2, 118, 0, 0, 0, 0,
ax_anim_terminator
sMrMimeAnims_5_4:
ax_anim 2, 0, 117, 0, 0, 0, 0,
ax_anim 2, 0, 118, 0, 0, 0, 0,
ax_anim 2, 0, 119, 0, 0, 0, 0,
ax_anim 2, 0, 112, 0, 0, 0, 0,
ax_anim 2, 0, 113, 0, 0, 0, 0,
ax_anim 2, 0, 114, 0, 0, 0, 0,
ax_anim 2, 0, 115, 0, 0, 0, 0,
ax_anim 2, 0, 116, 0, 0, 0, 0,
ax_anim 2, 2, 117, 0, 0, 0, 0,
ax_anim_terminator
sMrMimeAnims_5_5:
ax_anim 2, 0, 116, 0, 0, 0, 0,
ax_anim 2, 0, 117, 0, 0, 0, 0,
ax_anim 2, 0, 118, 0, 0, 0, 0,
ax_anim 2, 0, 119, 0, 0, 0, 0,
ax_anim 2, 0, 112, 0, 0, 0, 0,
ax_anim 2, 0, 113, 0, 0, 0, 0,
ax_anim 2, 0, 114, 0, 0, 0, 0,
ax_anim 2, 0, 115, 0, 0, 0, 0,
ax_anim 2, 2, 116, 0, 0, 0, 0,
ax_anim_terminator
sMrMimeAnims_5_6:
ax_anim 2, 0, 115, 0, 0, 0, 0,
ax_anim 2, 0, 116, 0, 0, 0, 0,
ax_anim 2, 0, 117, 0, 0, 0, 0,
ax_anim 2, 0, 118, 0, 0, 0, 0,
ax_anim 2, 0, 119, 0, 0, 0, 0,
ax_anim 2, 0, 112, 0, 0, 0, 0,
ax_anim 2, 0, 113, 0, 0, 0, 0,
ax_anim 2, 0, 114, 0, 0, 0, 0,
ax_anim 2, 2, 115, 0, 0, 0, 0,
ax_anim_terminator
sMrMimeAnims_5_7:
ax_anim 2, 0, 114, 0, 0, 0, 0,
ax_anim 2, 0, 115, 0, 0, 0, 0,
ax_anim 2, 0, 116, 0, 0, 0, 0,
ax_anim 2, 0, 117, 0, 0, 0, 0,
ax_anim 2, 0, 118, 0, 0, 0, 0,
ax_anim 2, 0, 119, 0, 0, 0, 0,
ax_anim 2, 0, 112, 0, 0, 0, 0,
ax_anim 2, 0, 113, 0, 0, 0, 0,
ax_anim 2, 2, 114, 0, 0, 0, 0,
ax_anim_terminator
sMrMimeAnims_5_8:
ax_anim 2, 0, 113, 0, 0, 0, 0,
ax_anim 2, 0, 114, 0, 0, 0, 0,
ax_anim 2, 0, 115, 0, 0, 0, 0,
ax_anim 2, 0, 116, 0, 0, 0, 0,
ax_anim 2, 0, 117, 0, 0, 0, 0,
ax_anim 2, 0, 118, 0, 0, 0, 0,
ax_anim 2, 0, 119, 0, 0, 0, 0,
ax_anim 2, 0, 112, 0, 0, 0, 0,
ax_anim 2, 2, 113, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sMrMimeAnims_6_1:
ax_anim 30, 0, 120, 0, 0, 0, 0,
ax_anim 35, 0, 121, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sMrMimeAnims_7_1:
ax_anim 2, 0, 122, 0, -2, 0, -2,
ax_anim 8, 0, 122, 0, -3, 0, -3,
ax_anim_terminator
sMrMimeAnims_7_2:
ax_anim 2, 0, 123, -2, -2, -2, -2,
ax_anim 8, 0, 123, -3, -3, -3, -3,
ax_anim_terminator
sMrMimeAnims_7_3:
ax_anim 2, 0, 124, -2, 0, -2, 0,
ax_anim 8, 0, 124, -3, 0, -3, 0,
ax_anim_terminator
sMrMimeAnims_7_4:
ax_anim 2, 0, 125, -2, 2, -2, 2,
ax_anim 8, 0, 125, -3, 3, -3, 3,
ax_anim_terminator
sMrMimeAnims_7_5:
ax_anim 2, 0, 126, 0, 2, 0, 2,
ax_anim 8, 0, 126, 0, 3, 0, 3,
ax_anim_terminator
sMrMimeAnims_7_6:
ax_anim 2, 0, 127, 2, 2, 2, 2,
ax_anim 8, 0, 127, 3, 3, 3, 3,
ax_anim_terminator
sMrMimeAnims_7_7:
ax_anim 2, 0, 128, 2, 0, 2, 0,
ax_anim 8, 0, 128, 3, 0, 3, 0,
ax_anim_terminator
sMrMimeAnims_7_8:
ax_anim 2, 0, 129, 2, -2, 2, -2,
ax_anim 8, 0, 129, 3, -3, 3, -3,
ax_anim_terminator
.align 2
sMrMimeAnims_8_1:
ax_anim 20, 0, 130, 0, 0, 0, 0,
ax_anim 12, 0, 138, 0, 0, 0, 0,
ax_anim_terminator
sMrMimeAnims_8_2:
ax_anim 20, 0, 137, 0, 0, 0, 0,
ax_anim 12, 0, 145, 0, 0, 0, 0,
ax_anim_terminator
sMrMimeAnims_8_3:
ax_anim 20, 0, 136, 0, 0, 0, 0,
ax_anim 12, 0, 144, 0, 0, 0, 0,
ax_anim_terminator
sMrMimeAnims_8_4:
ax_anim 20, 0, 135, 0, 0, 0, 0,
ax_anim 12, 0, 143, 0, 0, 0, 0,
ax_anim_terminator
sMrMimeAnims_8_5:
ax_anim 20, 0, 134, 0, 0, 0, 0,
ax_anim 12, 0, 142, 0, 0, 0, 0,
ax_anim_terminator
sMrMimeAnims_8_6:
ax_anim 20, 0, 133, 0, 0, 0, 0,
ax_anim 12, 0, 141, 0, 0, 0, 0,
ax_anim_terminator
sMrMimeAnims_8_7:
ax_anim 20, 0, 132, 0, 0, 0, 0,
ax_anim 12, 0, 140, 0, 0, 0, 0,
ax_anim_terminator
sMrMimeAnims_8_8:
ax_anim 20, 0, 131, 0, 0, 0, 0,
ax_anim 12, 0, 139, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sMrMimeAnims_9_1:
ax_anim 2, 0, 146, 0, 0, 0, 0,
ax_anim 1, 0, 147, 6, 3, 6, 3,
ax_anim 2, 0, 148, 8, 9, 8, 9,
ax_anim 2, 0, 149, 7, 15, 7, 15,
ax_anim 3, 0, 150, 0, 18, 0, 18,
ax_anim 2, 3, 151, -7, 15, -7, 15,
ax_anim 2, 0, 152, -8, 9, -8, 9,
ax_anim 1, 0, 153, -6, 3, -6, 3,
ax_anim 1, 0, 146, 0, 0, 0, 0,
ax_anim_terminator
sMrMimeAnims_9_2:
ax_anim 2, 0, 153, 0, 0, 0, 0,
ax_anim 1, 0, 146, 8, 0, 8, 0,
ax_anim 2, 0, 147, 17, 3, 17, 3,
ax_anim 2, 0, 148, 19, 10, 19, 10,
ax_anim 3, 0, 149, 19, 19, 19, 19,
ax_anim 2, 3, 150, 11, 19, 11, 19,
ax_anim 2, 0, 151, 3, 15, 3, 15,
ax_anim 1, 0, 152, 0, 7, 0, 7,
ax_anim 1, 0, 153, 0, 0, 0, 0,
ax_anim_terminator
sMrMimeAnims_9_3:
ax_anim 2, 0, 152, 0, 0, 0, 0,
ax_anim 1, 0, 153, 3, -5, 3, -5,
ax_anim 2, 0, 146, 11, -6, 11, -6,
ax_anim 2, 0, 147, 18, -5, 18, -5,
ax_anim 3, 0, 148, 21, -2, 21, -2,
ax_anim 2, 3, 149, 18, 4, 18, 4,
ax_anim 2, 0, 150, 12, 4, 12, 4,
ax_anim 1, 0, 151, 4, 5, 4, 5,
ax_anim 1, 0, 152, 0, 0, 0, 0,
ax_anim_terminator
sMrMimeAnims_9_4:
ax_anim 2, 0, 151, 0, 0, 0, 0,
ax_anim 1, 0, 152, -1, -8, -1, -8,
ax_anim 2, 0, 153, 3, -17, 3, -17,
ax_anim 2, 0, 146, 12, -22, 12, -22,
ax_anim 3, 0, 147, 21, -22, 21, -22,
ax_anim 2, 3, 148, 21, -14, 21, -14,
ax_anim 2, 0, 149, 17, -4, 17, -4,
ax_anim 1, 0, 150, 7, -1, 7, -1,
ax_anim 1, 0, 151, 0, 0, 0, 0,
ax_anim_terminator
sMrMimeAnims_9_5:
ax_anim 2, 0, 150, 0, 0, 0, 0,
ax_anim 1, 0, 151, -8, -4, -8, -4,
ax_anim 2, 0, 152, -9, -12, -9, -12,
ax_anim 2, 0, 153, -7, -20, -7, -20,
ax_anim 3, 0, 146, 0, -24, 0, -24,
ax_anim 2, 3, 147, 7, -20, 7, -20,
ax_anim 2, 0, 148, 9, -10, 9, -10,
ax_anim 1, 0, 149, 8, -4, 8, -4,
ax_anim 1, 0, 150, 0, 0, 0, 0,
ax_anim_terminator
sMrMimeAnims_9_6:
ax_anim 2, 0, 149, 0, 0, 0, 0,
ax_anim 1, 0, 148, 1, -8, 1, -8,
ax_anim 2, 0, 147, -3, -17, -3, -17,
ax_anim 2, 0, 146, -12, -22, -12, -22,
ax_anim 3, 0, 153, -21, -22, -21, -22,
ax_anim 2, 3, 152, -21, -14, -21, -14,
ax_anim 2, 0, 151, -17, -4, -17, -4,
ax_anim 1, 0, 150, -7, -1, -7, -1,
ax_anim 1, 0, 149, 0, 0, 0, 0,
ax_anim_terminator
sMrMimeAnims_9_7:
ax_anim 2, 0, 148, 0, 0, 0, 0,
ax_anim 1, 0, 147, -3, -5, -3, -5,
ax_anim 2, 0, 146, -11, -6, -11, -6,
ax_anim 2, 0, 153, -18, -5, -18, -5,
ax_anim 3, 0, 152, -21, -2, -21, -2,
ax_anim 2, 3, 151, -18, 4, -18, 4,
ax_anim 2, 0, 150, -12, 4, -12, 4,
ax_anim 1, 0, 149, -4, 5, -4, 5,
ax_anim 1, 0, 148, 0, 0, 0, 0,
ax_anim_terminator
sMrMimeAnims_9_8:
ax_anim 2, 0, 147, 0, 0, 0, 0,
ax_anim 1, 0, 146, -8, 0, -8, 0,
ax_anim 2, 0, 153, -17, 3, -17, 3,
ax_anim 2, 0, 152, -19, 10, -19, 10,
ax_anim 3, 0, 151, -19, 19, -19, 19,
ax_anim 2, 3, 150, -11, 19, -11, 19,
ax_anim 2, 0, 149, -3, 15, -3, 15,
ax_anim 1, 0, 148, 0, 7, 0, 7,
ax_anim 1, 0, 147, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sMrMimeAnims_10_1:
ax_anim 2, 0, 154, 0, 0, 0, 0,
ax_anim 2, 0, 154, 6, 0, 6, 0,
ax_anim 2, 0, 154, -6, 0, -6, 0,
ax_anim 2, 0, 154, 10, 0, 10, 0,
ax_anim 2, 0, 154, -10, 0, -10, 0,
ax_anim 2, 0, 154, 12, 0, 12, 0,
ax_anim 3, 0, 154, -12, 0, -12, 0,
ax_anim 3, 0, 154, 13, 0, 13, 0,
ax_anim 3, 0, 154, -13, 0, -13, 0,
ax_anim 2, 0, 154, 12, 0, 12, 0,
ax_anim 3, 0, 154, -12, 0, -12, 0,
ax_anim 2, 0, 154, 10, 0, 10, 0,
ax_anim 2, 0, 154, -10, 0, -10, 0,
ax_anim 2, 0, 154, 6, 0, 6, 0,
ax_anim 2, 0, 154, -6, 0, -6, 0,
ax_anim 2, 0, 154, 0, 0, 0, 0,
ax_anim_terminator
sMrMimeAnims_10_2:
ax_anim 2, 0, 155, 0, 0, 0, 0,
ax_anim 2, 0, 155, 6, -6, 6, -6,
ax_anim 2, 0, 155, -6, 6, -6, 6,
ax_anim 2, 0, 155, 10, -10, 10, -10,
ax_anim 2, 0, 155, -10, 10, -10, 10,
ax_anim 2, 0, 155, 12, -12, 12, -12,
ax_anim 3, 0, 155, -12, 12, -12, 12,
ax_anim 3, 0, 155, 13, -13, 13, -13,
ax_anim 3, 0, 155, -13, 13, -13, 13,
ax_anim 2, 0, 155, 12, -12, 12, -12,
ax_anim 3, 0, 155, -12, 12, -12, 12,
ax_anim 2, 0, 155, 10, -10, 10, -10,
ax_anim 2, 0, 155, -10, 10, -10, 10,
ax_anim 2, 0, 155, 6, -6, 6, -6,
ax_anim 2, 0, 155, -6, 6, -6, 6,
ax_anim 2, 0, 155, 0, 0, 0, 0,
ax_anim_terminator
sMrMimeAnims_10_3:
ax_anim 2, 0, 156, 0, 0, 0, 0,
ax_anim 2, 0, 156, 0, -6, 0, -6,
ax_anim 2, 0, 156, 0, 6, 0, 6,
ax_anim 2, 0, 156, 0, -10, 0, -10,
ax_anim 2, 0, 156, 0, 10, 0, 10,
ax_anim 2, 0, 156, 0, -12, 0, -12,
ax_anim 3, 0, 156, 0, 12, 0, 12,
ax_anim 3, 0, 156, 0, -13, 0, -13,
ax_anim 3, 0, 156, 0, 13, 0, 13,
ax_anim 2, 0, 156, 0, -12, 0, -12,
ax_anim 3, 0, 156, 0, 12, 0, 12,
ax_anim 2, 0, 156, 0, -10, 0, -10,
ax_anim 2, 0, 156, 0, 10, 0, 10,
ax_anim 2, 0, 156, 0, -6, 0, -6,
ax_anim 2, 0, 156, 0, 6, 0, 6,
ax_anim 2, 0, 156, 0, 0, 0, 0,
ax_anim_terminator
sMrMimeAnims_10_4:
ax_anim 2, 0, 157, 0, 0, 0, 0,
ax_anim 2, 0, 157, -6, -6, -6, -6,
ax_anim 2, 0, 157, 6, 6, 6, 6,
ax_anim 2, 0, 157, -10, -10, -10, -10,
ax_anim 2, 0, 157, 10, 10, 10, 10,
ax_anim 2, 0, 157, -12, -12, -12, -12,
ax_anim 3, 0, 157, 12, 12, 12, 12,
ax_anim 3, 0, 157, -13, -13, -13, -13,
ax_anim 3, 0, 157, 13, 13, 13, 13,
ax_anim 2, 0, 157, -12, -12, -12, -12,
ax_anim 3, 0, 157, 12, 12, 12, 12,
ax_anim 2, 0, 157, -10, -10, -10, -10,
ax_anim 2, 0, 157, 10, 10, 10, 10,
ax_anim 2, 0, 157, -6, -6, -6, -6,
ax_anim 2, 0, 157, 6, 6, 6, 6,
ax_anim 2, 0, 157, 0, 0, 0, 0,
ax_anim_terminator
sMrMimeAnims_10_5:
ax_anim 2, 0, 158, 0, 0, 0, 0,
ax_anim 2, 0, 158, 6, 0, 6, 0,
ax_anim 2, 0, 158, -6, 0, -6, 0,
ax_anim 2, 0, 158, 10, 0, 10, 0,
ax_anim 2, 0, 158, -10, 0, -10, 0,
ax_anim 2, 0, 158, 12, 0, 12, 0,
ax_anim 3, 0, 158, -12, 0, -12, 0,
ax_anim 3, 0, 158, 13, 0, 13, 0,
ax_anim 3, 0, 158, -13, 0, -13, 0,
ax_anim 2, 0, 158, 12, 0, 12, 0,
ax_anim 3, 0, 158, -12, 0, -12, 0,
ax_anim 2, 0, 158, 10, 0, 10, 0,
ax_anim 2, 0, 158, -10, 0, -10, 0,
ax_anim 2, 0, 158, 6, 0, 6, 0,
ax_anim 2, 0, 158, -6, 0, -6, 0,
ax_anim 2, 0, 158, 0, 0, 0, 0,
ax_anim_terminator
sMrMimeAnims_10_6:
ax_anim 2, 0, 159, 0, 0, 0, 0,
ax_anim 2, 0, 159, 6, -6, 6, -6,
ax_anim 2, 0, 159, -6, 6, -6, 6,
ax_anim 2, 0, 159, 10, -10, 10, -10,
ax_anim 2, 0, 159, -10, 10, -10, 10,
ax_anim 2, 0, 159, 12, -12, 12, -12,
ax_anim 3, 0, 159, -12, 12, -12, 12,
ax_anim 3, 0, 159, 13, -13, 13, -13,
ax_anim 3, 0, 159, -13, 13, -13, 13,
ax_anim 2, 0, 159, 12, -12, 12, -12,
ax_anim 3, 0, 159, -12, 12, -12, 12,
ax_anim 2, 0, 159, 10, -10, 10, -10,
ax_anim 2, 0, 159, -10, 10, -10, 10,
ax_anim 2, 0, 159, 6, -6, 6, -6,
ax_anim 2, 0, 159, -6, 6, -6, 6,
ax_anim 2, 0, 159, 0, 0, 0, 0,
ax_anim_terminator
sMrMimeAnims_10_7:
ax_anim 2, 0, 160, 0, 0, 0, 0,
ax_anim 2, 0, 160, 0, -6, 0, -6,
ax_anim 2, 0, 160, 0, 6, 0, 6,
ax_anim 2, 0, 160, 0, -10, 0, -10,
ax_anim 2, 0, 160, 0, 10, 0, 10,
ax_anim 2, 0, 160, 0, -12, 0, -12,
ax_anim 3, 0, 160, 0, 12, 0, 12,
ax_anim 3, 0, 160, 0, -13, 0, -13,
ax_anim 3, 0, 160, 0, 13, 0, 13,
ax_anim 2, 0, 160, 0, -12, 0, -12,
ax_anim 3, 0, 160, 0, 12, 0, 12,
ax_anim 2, 0, 160, 0, -10, 0, -10,
ax_anim 2, 0, 160, 0, 10, 0, 10,
ax_anim 2, 0, 160, 0, -6, 0, -6,
ax_anim 2, 0, 160, 0, 6, 0, 6,
ax_anim 2, 0, 160, 0, 0, 0, 0,
ax_anim_terminator
sMrMimeAnims_10_8:
ax_anim 2, 0, 161, 0, 0, 0, 0,
ax_anim 2, 0, 161, -6, -6, -6, -6,
ax_anim 2, 0, 161, 6, 6, 6, 6,
ax_anim 2, 0, 161, -10, -10, -10, -10,
ax_anim 2, 0, 161, 10, 10, 10, 10,
ax_anim 2, 0, 161, -12, -12, -12, -12,
ax_anim 3, 0, 161, 12, 12, 12, 12,
ax_anim 3, 0, 161, -13, -13, -13, -13,
ax_anim 3, 0, 161, 13, 13, 13, 13,
ax_anim 2, 0, 161, -12, -12, -12, -12,
ax_anim 3, 0, 161, 12, 12, 12, 12,
ax_anim 2, 0, 161, -10, -10, -10, -10,
ax_anim 2, 0, 161, 10, 10, 10, 10,
ax_anim 2, 0, 161, -6, -6, -6, -6,
ax_anim 2, 0, 161, 6, 6, 6, 6,
ax_anim 2, 0, 161, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sMrMimeAnims_11_1:
ax_anim 2, 0, 162, 0, 0, 0, 0,
ax_anim 1, 0, 163, 0, -10, 0, 0,
ax_anim 2, 0, 163, 0, -16, 0, 0,
ax_anim 3, 0, 163, 0, -20, 0, 0,
ax_anim 4, 0, 163, 0, -21, 0, 0,
ax_anim 4, 0, 164, 0, -23, 0, 0,
ax_anim 3, 0, 164, 0, -22, 0, 0,
ax_anim 2, 0, 164, 0, -18, 0, 0,
ax_anim 1, 0, 164, 0, -12, 0, 0,
ax_anim 2, 2, 162, 0, 0, 0, 0,
ax_anim_terminator
sMrMimeAnims_11_2:
ax_anim 2, 0, 165, 0, 0, 0, 0,
ax_anim 1, 0, 166, 0, -10, 0, 0,
ax_anim 2, 0, 166, 0, -16, 0, 0,
ax_anim 3, 0, 166, 0, -20, 0, 0,
ax_anim 4, 0, 166, 0, -21, 0, 0,
ax_anim 4, 0, 167, 0, -23, 0, 0,
ax_anim 3, 0, 167, 0, -22, 0, 0,
ax_anim 2, 0, 167, 0, -18, 0, 0,
ax_anim 1, 0, 167, 0, -12, 0, 0,
ax_anim 2, 2, 165, 0, 0, 0, 0,
ax_anim_terminator
sMrMimeAnims_11_3:
ax_anim 2, 0, 168, 0, 0, 0, 0,
ax_anim 1, 0, 169, 0, -10, 0, 0,
ax_anim 2, 0, 169, 0, -16, 0, 0,
ax_anim 3, 0, 169, 0, -20, 0, 0,
ax_anim 4, 0, 169, 0, -21, 0, 0,
ax_anim 4, 0, 170, 0, -23, 0, 0,
ax_anim 3, 0, 170, 0, -22, 0, 0,
ax_anim 2, 0, 170, 0, -18, 0, 0,
ax_anim 1, 0, 170, 0, -12, 0, 0,
ax_anim 2, 2, 168, 0, 0, 0, 0,
ax_anim_terminator
sMrMimeAnims_11_4:
ax_anim 2, 0, 171, 0, 0, 0, 0,
ax_anim 1, 0, 172, 0, -10, 0, 0,
ax_anim 2, 0, 172, 0, -16, 0, 0,
ax_anim 3, 0, 172, 0, -20, 0, 0,
ax_anim 4, 0, 172, 0, -21, 0, 0,
ax_anim 4, 0, 173, 0, -22, 0, 0,
ax_anim 3, 0, 173, 0, -21, 0, 0,
ax_anim 2, 0, 173, 0, -17, 0, 0,
ax_anim 1, 0, 173, 0, -11, 0, 0,
ax_anim 2, 2, 171, 0, 0, 0, 0,
ax_anim_terminator
sMrMimeAnims_11_5:
ax_anim 2, 0, 174, 0, 0, 0, 0,
ax_anim 1, 0, 175, 0, -10, 0, 0,
ax_anim 2, 0, 175, 0, -16, 0, 0,
ax_anim 3, 0, 175, 0, -20, 0, 0,
ax_anim 4, 0, 175, 0, -21, 0, 0,
ax_anim 4, 0, 176, 0, -23, 0, 0,
ax_anim 3, 0, 176, 0, -22, 0, 0,
ax_anim 2, 0, 176, 0, -18, 0, 0,
ax_anim 1, 0, 176, 0, -12, 0, 0,
ax_anim 2, 2, 174, 0, 0, 0, 0,
ax_anim_terminator
sMrMimeAnims_11_6:
ax_anim 2, 0, 177, 0, 0, 0, 0,
ax_anim 1, 0, 178, 0, -10, 0, 0,
ax_anim 2, 0, 178, 0, -16, 0, 0,
ax_anim 3, 0, 178, 0, -20, 0, 0,
ax_anim 4, 0, 178, 0, -21, 0, 0,
ax_anim 4, 0, 179, 0, -22, 0, 0,
ax_anim 3, 0, 179, 0, -21, 0, 0,
ax_anim 2, 0, 179, 0, -17, 0, 0,
ax_anim 1, 0, 179, 0, -11, 0, 0,
ax_anim 2, 2, 177, 0, 0, 0, 0,
ax_anim_terminator
sMrMimeAnims_11_7:
ax_anim 2, 0, 180, 0, 0, 0, 0,
ax_anim 1, 0, 181, 0, -10, 0, 0,
ax_anim 2, 0, 181, 0, -16, 0, 0,
ax_anim 3, 0, 181, 0, -20, 0, 0,
ax_anim 4, 0, 181, 0, -21, 0, 0,
ax_anim 4, 0, 182, 0, -23, 0, 0,
ax_anim 3, 0, 182, 0, -22, 0, 0,
ax_anim 2, 0, 182, 0, -18, 0, 0,
ax_anim 1, 0, 182, 0, -12, 0, 0,
ax_anim 2, 2, 180, 0, 0, 0, 0,
ax_anim_terminator
sMrMimeAnims_11_8:
ax_anim 2, 0, 183, 0, 0, 0, 0,
ax_anim 1, 0, 184, 0, -10, 0, 0,
ax_anim 2, 0, 184, 0, -16, 0, 0,
ax_anim 3, 0, 184, 0, -20, 0, 0,
ax_anim 4, 0, 184, 0, -21, 0, 0,
ax_anim 4, 0, 185, 0, -23, 0, 0,
ax_anim 3, 0, 185, 0, -22, 0, 0,
ax_anim 2, 0, 185, 0, -18, 0, 0,
ax_anim 1, 0, 185, 0, -12, 0, 0,
ax_anim 2, 2, 183, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sMrMimeAnims_12_1:
ax_anim 2, 0, 186, 1, 0, 1, 0,
ax_anim 2, 0, 186, 0, 0, 0, 0,
ax_anim 2, 0, 186, 1, 0, 1, 0,
ax_anim 2, 0, 186, 0, 0, 0, 0,
ax_anim 2, 0, 186, 1, 0, 1, 0,
ax_anim 2, 2, 186, 0, 0, 0, 0,
ax_anim 2, 0, 186, 1, 0, 1, 0,
ax_anim 2, 0, 186, 0, 0, 0, 0,
ax_anim 2, 0, 186, 1, 0, 1, 0,
ax_anim 2, 1, 186, 0, 0, 0, 0,
ax_anim_terminator
sMrMimeAnims_12_2:
ax_anim 2, 0, 193, 1, -1, 1, -1,
ax_anim 2, 0, 193, 0, 0, 0, 0,
ax_anim 2, 0, 193, 1, -1, 1, -1,
ax_anim 2, 0, 193, 0, 0, 0, 0,
ax_anim 2, 0, 193, 1, -1, 1, -1,
ax_anim 2, 2, 193, 0, 0, 0, 0,
ax_anim 2, 0, 193, 1, -1, 1, -1,
ax_anim 2, 0, 193, 0, 0, 0, 0,
ax_anim 2, 0, 193, 1, -1, 1, -1,
ax_anim 2, 1, 193, 0, 0, 0, 0,
ax_anim_terminator
sMrMimeAnims_12_3:
ax_anim 2, 0, 192, 0, -1, 0, -1,
ax_anim 2, 0, 192, 0, 0, 0, 0,
ax_anim 2, 0, 192, 0, -1, 0, -1,
ax_anim 2, 0, 192, 0, 0, 0, 0,
ax_anim 2, 0, 192, 0, -1, 0, -1,
ax_anim 2, 2, 192, 0, 0, 0, 0,
ax_anim 2, 0, 192, 0, -1, 0, -1,
ax_anim 2, 0, 192, 0, 0, 0, 0,
ax_anim 2, 0, 192, 0, -1, 0, -1,
ax_anim 2, 1, 192, 0, 0, 0, 0,
ax_anim_terminator
sMrMimeAnims_12_4:
ax_anim 2, 0, 191, -1, -1, -1, -1,
ax_anim 2, 0, 191, 0, 0, 0, 0,
ax_anim 2, 0, 191, -1, -1, -1, -1,
ax_anim 2, 0, 191, 0, 0, 0, 0,
ax_anim 2, 0, 191, -1, -1, -1, -1,
ax_anim 2, 2, 191, 0, 0, 0, 0,
ax_anim 2, 0, 191, -1, -1, -1, -1,
ax_anim 2, 0, 191, 0, 0, 0, 0,
ax_anim 2, 0, 191, -1, -1, -1, -1,
ax_anim 2, 1, 191, 0, 0, 0, 0,
ax_anim_terminator
sMrMimeAnims_12_5:
ax_anim 2, 0, 190, 1, 0, 1, 0,
ax_anim 2, 0, 190, 0, 0, 0, 0,
ax_anim 2, 0, 190, 1, 0, 1, 0,
ax_anim 2, 0, 190, 0, 0, 0, 0,
ax_anim 2, 0, 190, 1, 0, 1, 0,
ax_anim 2, 2, 190, 0, 0, 0, 0,
ax_anim 2, 0, 190, 1, 0, 1, 0,
ax_anim 2, 0, 190, 0, 0, 0, 0,
ax_anim 2, 0, 190, 1, 0, 1, 0,
ax_anim 2, 1, 190, 0, 0, 0, 0,
ax_anim_terminator
sMrMimeAnims_12_6:
ax_anim 2, 0, 189, 1, -1, 1, -1,
ax_anim 2, 0, 189, 0, 0, 0, 0,
ax_anim 2, 0, 189, 1, -1, 1, -1,
ax_anim 2, 0, 189, 0, 0, 0, 0,
ax_anim 2, 0, 189, 1, -1, 1, -1,
ax_anim 2, 2, 189, 0, 0, 0, 0,
ax_anim 2, 0, 189, 1, -1, 1, -1,
ax_anim 2, 0, 189, 0, 0, 0, 0,
ax_anim 2, 0, 189, 1, -1, 1, -1,
ax_anim 2, 1, 189, 0, 0, 0, 0,
ax_anim_terminator
sMrMimeAnims_12_7:
ax_anim 2, 0, 188, 0, -1, 0, -1,
ax_anim 2, 0, 188, 0, 0, 0, 0,
ax_anim 2, 0, 188, 0, -1, 0, -1,
ax_anim 2, 0, 188, 0, 0, 0, 0,
ax_anim 2, 0, 188, 0, -1, 0, -1,
ax_anim 2, 2, 188, 0, 0, 0, 0,
ax_anim 2, 0, 188, 0, -1, 0, -1,
ax_anim 2, 0, 188, 0, 0, 0, 0,
ax_anim 2, 0, 188, 0, -1, 0, -1,
ax_anim 2, 1, 188, 0, 0, 0, 0,
ax_anim_terminator
sMrMimeAnims_12_8:
ax_anim 2, 0, 187, -1, -1, -1, -1,
ax_anim 2, 0, 187, 0, 0, 0, 0,
ax_anim 2, 0, 187, -1, -1, -1, -1,
ax_anim 2, 0, 187, 0, 0, 0, 0,
ax_anim 2, 0, 187, -1, -1, -1, -1,
ax_anim 2, 2, 187, 0, 0, 0, 0,
ax_anim 2, 0, 187, -1, -1, -1, -1,
ax_anim 2, 0, 187, 0, 0, 0, 0,
ax_anim 2, 0, 187, -1, -1, -1, -1,
ax_anim 2, 1, 187, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sMrMimeAnims_13_1:
ax_anim 2, 0, 194, 0, 0, 0, 0,
ax_anim 2, 0, 195, 0, 0, 0, 0,
ax_anim 2, 0, 196, 0, 0, 0, 0,
ax_anim 2, 0, 197, 0, 0, 0, 0,
ax_anim 2, 0, 198, 0, 0, 0, 0,
ax_anim 2, 0, 199, 0, 0, 0, 0,
ax_anim 2, 0, 200, 0, 0, 0, 0,
ax_anim 2, 0, 201, 0, 0, 0, 0,
ax_anim 2, 2, 194, 0, 0, 0, 0,
ax_anim_terminator
sMrMimeAnims_13_2:
ax_anim 2, 0, 201, 0, 0, 0, 0,
ax_anim 2, 0, 194, 0, 0, 0, 0,
ax_anim 2, 0, 195, 0, 0, 0, 0,
ax_anim 2, 0, 196, 0, 0, 0, 0,
ax_anim 2, 0, 197, 0, 0, 0, 0,
ax_anim 2, 0, 198, 0, 0, 0, 0,
ax_anim 2, 0, 199, 0, 0, 0, 0,
ax_anim 2, 0, 200, 0, 0, 0, 0,
ax_anim 2, 2, 201, 0, 0, 0, 0,
ax_anim_terminator
sMrMimeAnims_13_3:
ax_anim 2, 0, 200, 0, 0, 0, 0,
ax_anim 2, 0, 201, 0, 0, 0, 0,
ax_anim 2, 0, 194, 0, 0, 0, 0,
ax_anim 2, 0, 195, 0, 0, 0, 0,
ax_anim 2, 0, 196, 0, 0, 0, 0,
ax_anim 2, 0, 197, 0, 0, 0, 0,
ax_anim 2, 0, 198, 0, 0, 0, 0,
ax_anim 2, 0, 199, 0, 0, 0, 0,
ax_anim 2, 2, 200, 0, 0, 0, 0,
ax_anim_terminator
sMrMimeAnims_13_4:
ax_anim 2, 0, 199, 0, 0, 0, 0,
ax_anim 2, 0, 200, 0, 0, 0, 0,
ax_anim 2, 0, 201, 0, 0, 0, 0,
ax_anim 2, 0, 194, 0, 0, 0, 0,
ax_anim 2, 0, 195, 0, 0, 0, 0,
ax_anim 2, 0, 196, 0, 0, 0, 0,
ax_anim 2, 0, 197, 0, 0, 0, 0,
ax_anim 2, 0, 198, 0, 0, 0, 0,
ax_anim 2, 2, 199, 0, 0, 0, 0,
ax_anim_terminator
sMrMimeAnims_13_5:
ax_anim 2, 0, 198, 0, 0, 0, 0,
ax_anim 2, 0, 199, 0, 0, 0, 0,
ax_anim 2, 0, 200, 0, 0, 0, 0,
ax_anim 2, 0, 201, 0, 0, 0, 0,
ax_anim 2, 0, 194, 0, 0, 0, 0,
ax_anim 2, 0, 195, 0, 0, 0, 0,
ax_anim 2, 0, 196, 0, 0, 0, 0,
ax_anim 2, 0, 197, 0, 0, 0, 0,
ax_anim 2, 2, 198, 0, 0, 0, 0,
ax_anim_terminator
sMrMimeAnims_13_6:
ax_anim 2, 0, 197, 0, 0, 0, 0,
ax_anim 2, 0, 198, 0, 0, 0, 0,
ax_anim 2, 0, 199, 0, 0, 0, 0,
ax_anim 2, 0, 200, 0, 0, 0, 0,
ax_anim 2, 0, 201, 0, 0, 0, 0,
ax_anim 2, 0, 194, 0, 0, 0, 0,
ax_anim 2, 0, 195, 0, 0, 0, 0,
ax_anim 2, 0, 196, 0, 0, 0, 0,
ax_anim 2, 2, 197, 0, 0, 0, 0,
ax_anim_terminator
sMrMimeAnims_13_7:
ax_anim 2, 0, 196, 0, 0, 0, 0,
ax_anim 2, 0, 197, 0, 0, 0, 0,
ax_anim 2, 0, 198, 0, 0, 0, 0,
ax_anim 2, 0, 199, 0, 0, 0, 0,
ax_anim 2, 0, 200, 0, 0, 0, 0,
ax_anim 2, 0, 201, 0, 0, 0, 0,
ax_anim 2, 0, 194, 0, 0, 0, 0,
ax_anim 2, 0, 195, 0, 0, 0, 0,
ax_anim 2, 2, 196, 0, 0, 0, 0,
ax_anim_terminator
sMrMimeAnims_13_8:
ax_anim 2, 0, 195, 0, 0, 0, 0,
ax_anim 2, 0, 196, 0, 0, 0, 0,
ax_anim 2, 0, 197, 0, 0, 0, 0,
ax_anim 2, 0, 198, 0, 0, 0, 0,
ax_anim 2, 0, 199, 0, 0, 0, 0,
ax_anim 2, 0, 200, 0, 0, 0, 0,
ax_anim 2, 0, 201, 0, 0, 0, 0,
ax_anim 2, 0, 194, 0, 0, 0, 0,
ax_anim 2, 2, 195, 0, 0, 0, 0,
ax_anim_terminator
sMrMimeGfx1:
.incbin "baserom.gba", 0xA3C7B8, 0x200
sMrMimeSprites1:
ax_sprite sMrMimeGfx1, 0x200
ax_sprite_terminator
sMrMimeGfx2:
.incbin "baserom.gba", 0xA3C9C8, 0x200
sMrMimeSprites2:
ax_sprite sMrMimeGfx2, 0x200
ax_sprite_terminator
sMrMimeGfx3:
.incbin "baserom.gba", 0xA3CBD8, 0x200
sMrMimeSprites3:
ax_sprite sMrMimeGfx3, 0x200
ax_sprite_terminator
sMrMimeGfx4:
.incbin "baserom.gba", 0xA3CDE8, 0x200
sMrMimeSprites4:
ax_sprite sMrMimeGfx4, 0x200
ax_sprite_terminator
sMrMimeGfx5:
.incbin "baserom.gba", 0xA3CFF8, 0x200
sMrMimeSprites5:
ax_sprite sMrMimeGfx5, 0x200
ax_sprite_terminator
sMrMimeGfx6:
.incbin "baserom.gba", 0xA3D208, 0x200
sMrMimeSprites6:
ax_sprite sMrMimeGfx6, 0x200
ax_sprite_terminator
sMrMimeGfx7:
.incbin "baserom.gba", 0xA3D418, 0x100
sMrMimeSprites7:
ax_sprite sMrMimeGfx7, 0x100
ax_sprite_terminator
sMrMimeGfx8:
.incbin "baserom.gba", 0xA3D528, 0x200
sMrMimeSprites8:
ax_sprite sMrMimeGfx8, 0x200
ax_sprite_terminator
sMrMimeGfx9:
.incbin "baserom.gba", 0xA3D738, 0x200
sMrMimeSprites9:
ax_sprite sMrMimeGfx9, 0x200
ax_sprite_terminator
sMrMimeGfx10:
.incbin "baserom.gba", 0xA3D948, 0x200
sMrMimeSprites10:
ax_sprite sMrMimeGfx10, 0x200
ax_sprite_terminator
sMrMimeGfx11:
.incbin "baserom.gba", 0xA3DB58, 0x200
sMrMimeSprites11:
ax_sprite sMrMimeGfx11, 0x200
ax_sprite_terminator
sMrMimeGfx12:
.incbin "baserom.gba", 0xA3DD68, 0x200
sMrMimeSprites12:
ax_sprite sMrMimeGfx12, 0x200
ax_sprite_terminator
sMrMimeGfx13:
.incbin "baserom.gba", 0xA3DF78, 0x200
sMrMimeSprites13:
ax_sprite sMrMimeGfx13, 0x200
ax_sprite_terminator
sMrMimeGfx14:
.incbin "baserom.gba", 0xA3E188, 0x200
sMrMimeSprites14:
ax_sprite sMrMimeGfx14, 0x200
ax_sprite_terminator
sMrMimeGfx15:
.incbin "baserom.gba", 0xA3E398, 0x200
sMrMimeSprites15:
ax_sprite sMrMimeGfx15, 0x200
ax_sprite_terminator
sMrMimeGfx16:
.incbin "baserom.gba", 0xA3E5A8, 0x40
sMrMimeGfx16_1:
.incbin "baserom.gba", 0xA3E5E8, 0x60
sMrMimeGfx16_2:
.incbin "baserom.gba", 0xA3E648, 0x100
sMrMimeSprites16:
ax_sprite 0, 0x20
ax_sprite sMrMimeGfx16, 0x40
ax_sprite 0, 0x20
ax_sprite sMrMimeGfx16_1, 0x60
ax_sprite 0, 0x20
ax_sprite sMrMimeGfx16_2, 0x100
ax_sprite_terminator
sMrMimeGfx17:
.incbin "baserom.gba", 0xA3E780, 0x40
sMrMimeGfx17_1:
.incbin "baserom.gba", 0xA3E7C0, 0x180
sMrMimeSprites17:
ax_sprite 0, 0x20
ax_sprite sMrMimeGfx17, 0x40
ax_sprite 0, 0x20
ax_sprite sMrMimeGfx17_1, 0x180
ax_sprite_terminator
sMrMimeGfx18:
.incbin "baserom.gba", 0xA3E968, 0x100
sMrMimeGfx18_1:
.incbin "baserom.gba", 0xA3EA68, 0xE0
sMrMimeSprites18:
ax_sprite sMrMimeGfx18, 0x100
ax_sprite 0, 0x20
ax_sprite sMrMimeGfx18_1, 0xe0
ax_sprite_terminator
sMrMimeGfx19:
.incbin "baserom.gba", 0xA3EB68, 0x180
sMrMimeSprites19:
ax_sprite 0, 0x80
ax_sprite sMrMimeGfx19, 0x180
ax_sprite_terminator
sMrMimeGfx20:
.incbin "baserom.gba", 0xA3ED00, 0x40
sMrMimeGfx20_1:
.incbin "baserom.gba", 0xA3ED40, 0x60
sMrMimeGfx20_2:
.incbin "baserom.gba", 0xA3EDA0, 0x60
sMrMimeGfx20_3:
.incbin "baserom.gba", 0xA3EE00, 0x80
sMrMimeSprites20:
ax_sprite 0, 0x20
ax_sprite sMrMimeGfx20, 0x40
ax_sprite 0, 0x20
ax_sprite sMrMimeGfx20_1, 0x60
ax_sprite 0, 0x20
ax_sprite sMrMimeGfx20_2, 0x60
ax_sprite 0, 0x20
ax_sprite sMrMimeGfx20_3, 0x80
ax_sprite_terminator
sMrMimeGfx21:
.incbin "baserom.gba", 0xA3EEC8, 0x40
sMrMimeGfx21_1:
.incbin "baserom.gba", 0xA3EF08, 0x60
sMrMimeGfx21_2:
.incbin "baserom.gba", 0xA3EF68, 0x60
sMrMimeGfx21_3:
.incbin "baserom.gba", 0xA3EFC8, 0x80
sMrMimeSprites21:
ax_sprite 0, 0x20
ax_sprite sMrMimeGfx21, 0x40
ax_sprite 0, 0x20
ax_sprite sMrMimeGfx21_1, 0x60
ax_sprite 0, 0x20
ax_sprite sMrMimeGfx21_2, 0x60
ax_sprite 0, 0x20
ax_sprite sMrMimeGfx21_3, 0x80
ax_sprite_terminator
sMrMimeGfx22:
.incbin "baserom.gba", 0xA3F090, 0x40
sMrMimeGfx22_1:
.incbin "baserom.gba", 0xA3F0D0, 0x60
sMrMimeGfx22_2:
.incbin "baserom.gba", 0xA3F130, 0x60
sMrMimeGfx22_3:
.incbin "baserom.gba", 0xA3F190, 0x80
sMrMimeSprites22:
ax_sprite 0, 0x20
ax_sprite sMrMimeGfx22, 0x40
ax_sprite 0, 0x20
ax_sprite sMrMimeGfx22_1, 0x60
ax_sprite 0, 0x20
ax_sprite sMrMimeGfx22_2, 0x60
ax_sprite 0, 0x20
ax_sprite sMrMimeGfx22_3, 0x80
ax_sprite_terminator
sMrMimeGfx23:
.incbin "baserom.gba", 0xA3F258, 0xE0
sMrMimeGfx23_1:
.incbin "baserom.gba", 0xA3F338, 0x80
sMrMimeSprites23:
ax_sprite 0, 0x80
ax_sprite sMrMimeGfx23, 0xe0
ax_sprite 0, 0x20
ax_sprite sMrMimeGfx23_1, 0x80
ax_sprite_terminator
sMrMimeGfx24:
.incbin "baserom.gba", 0xA3F3E0, 0x60
sMrMimeGfx24_1:
.incbin "baserom.gba", 0xA3F440, 0x60
sMrMimeGfx24_2:
.incbin "baserom.gba", 0xA3F4A0, 0x60
sMrMimeSprites24:
ax_sprite 0, 0x80
ax_sprite sMrMimeGfx24, 0x60
ax_sprite 0, 0x20
ax_sprite sMrMimeGfx24_1, 0x60
ax_sprite 0, 0x40
ax_sprite sMrMimeGfx24_2, 0x60
ax_sprite_terminator
sMrMimeGfx25:
.incbin "baserom.gba", 0xA3F538, 0x20
sMrMimeGfx25_1:
.incbin "baserom.gba", 0xA3F558, 0x40
sMrMimeGfx25_2:
.incbin "baserom.gba", 0xA3F598, 0x60
sMrMimeGfx25_3:
.incbin "baserom.gba", 0xA3F5F8, 0x60
sMrMimeSprites25:
ax_sprite 0, 0x20
ax_sprite sMrMimeGfx25, 0x20
ax_sprite 0, 0x60
ax_sprite sMrMimeGfx25_1, 0x40
ax_sprite 0, 0x40
ax_sprite sMrMimeGfx25_2, 0x60
ax_sprite 0, 0x20
ax_sprite sMrMimeGfx25_3, 0x60
ax_sprite_terminator
sMrMimeGfx26:
.incbin "baserom.gba", 0xA3F6A0, 0x20
sMrMimeGfx26_1:
.incbin "baserom.gba", 0xA3F6C0, 0x60
sMrMimeGfx26_2:
.incbin "baserom.gba", 0xA3F720, 0x60
sMrMimeGfx26_3:
.incbin "baserom.gba", 0xA3F780, 0x60
sMrMimeSprites26:
ax_sprite 0, 0x20
ax_sprite sMrMimeGfx26, 0x20
ax_sprite 0, 0x60
ax_sprite sMrMimeGfx26_1, 0x60
ax_sprite 0, 0x20
ax_sprite sMrMimeGfx26_2, 0x60
ax_sprite 0, 0x20
ax_sprite sMrMimeGfx26_3, 0x60
ax_sprite_terminator
sMrMimeGfx27:
.incbin "baserom.gba", 0xA3F828, 0x60
sMrMimeGfx27_1:
.incbin "baserom.gba", 0xA3F888, 0x60
sMrMimeGfx27_2:
.incbin "baserom.gba", 0xA3F8E8, 0x80
sMrMimeSprites27:
ax_sprite 0, 0x80
ax_sprite sMrMimeGfx27, 0x60
ax_sprite 0, 0x20
ax_sprite sMrMimeGfx27_1, 0x60
ax_sprite 0, 0x20
ax_sprite sMrMimeGfx27_2, 0x80
ax_sprite_terminator
sMrMimeGfx28:
.incbin "baserom.gba", 0xA3F9A0, 0x60
sMrMimeGfx28_1:
.incbin "baserom.gba", 0xA3FA00, 0x60
sMrMimeGfx28_2:
.incbin "baserom.gba", 0xA3FA60, 0x60
sMrMimeGfx28_3:
.incbin "baserom.gba", 0xA3FAC0, 0x60
sMrMimeSprites28:
ax_sprite 0, 0x20
ax_sprite sMrMimeGfx28, 0x60
ax_sprite 0, 0x20
ax_sprite sMrMimeGfx28_1, 0x60
ax_sprite 0, 0x20
ax_sprite sMrMimeGfx28_2, 0x60
ax_sprite 0, 0x20
ax_sprite sMrMimeGfx28_3, 0x60
ax_sprite_terminator
sMrMimeGfx29:
.incbin "baserom.gba", 0xA3FB68, 0x60
sMrMimeGfx29_1:
.incbin "baserom.gba", 0xA3FBC8, 0x60
sMrMimeGfx29_2:
.incbin "baserom.gba", 0xA3FC28, 0x60
sMrMimeGfx29_3:
.incbin "baserom.gba", 0xA3FC88, 0x60
sMrMimeSprites29:
ax_sprite 0, 0x20
ax_sprite sMrMimeGfx29, 0x60
ax_sprite 0, 0x20
ax_sprite sMrMimeGfx29_1, 0x60
ax_sprite 0, 0x20
ax_sprite sMrMimeGfx29_2, 0x60
ax_sprite 0, 0x20
ax_sprite sMrMimeGfx29_3, 0x60
ax_sprite_terminator
sMrMimeGfx30:
.incbin "baserom.gba", 0xA3FD30, 0x60
sMrMimeGfx30_1:
.incbin "baserom.gba", 0xA3FD90, 0x60
sMrMimeGfx30_2:
.incbin "baserom.gba", 0xA3FDF0, 0x60
sMrMimeGfx30_3:
.incbin "baserom.gba", 0xA3FE50, 0x60
sMrMimeSprites30:
ax_sprite 0, 0x20
ax_sprite sMrMimeGfx30, 0x60
ax_sprite 0, 0x20
ax_sprite sMrMimeGfx30_1, 0x60
ax_sprite 0, 0x20
ax_sprite sMrMimeGfx30_2, 0x60
ax_sprite 0, 0x20
ax_sprite sMrMimeGfx30_3, 0x60
ax_sprite_terminator
sMrMimeGfx31:
.incbin "baserom.gba", 0xA3FEF8, 0x60
sMrMimeGfx31_1:
.incbin "baserom.gba", 0xA3FF58, 0x80
sMrMimeGfx31_2:
.incbin "baserom.gba", 0xA3FFD8, 0x60
sMrMimeGfx31_3:
.incbin "baserom.gba", 0xA40038, 0x40
sMrMimeSprites31:
ax_sprite sMrMimeGfx31, 0x60
ax_sprite 0, 0x20
ax_sprite sMrMimeGfx31_1, 0x80
ax_sprite 0, 0x20
ax_sprite sMrMimeGfx31_2, 0x60
ax_sprite 0, 0x20
ax_sprite sMrMimeGfx31_3, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sMrMimeGfx32:
.incbin "baserom.gba", 0xA400C0, 0x20
sMrMimeGfx32_1:
.incbin "baserom.gba", 0xA400E0, 0x160
sMrMimeSprites32:
ax_sprite 0, 0x20
ax_sprite sMrMimeGfx32, 0x20
ax_sprite 0, 0x40
ax_sprite sMrMimeGfx32_1, 0x160
ax_sprite 0, 0x20
ax_sprite_terminator
sMrMimeGfx33:
.incbin "baserom.gba", 0xA40270, 0x60
sMrMimeGfx33_1:
.incbin "baserom.gba", 0xA402D0, 0xE0
sMrMimeGfx33_2:
.incbin "baserom.gba", 0xA403B0, 0x60
sMrMimeSprites33:
ax_sprite sMrMimeGfx33, 0x60
ax_sprite 0, 0x20
ax_sprite sMrMimeGfx33_1, 0xe0
ax_sprite 0, 0x20
ax_sprite sMrMimeGfx33_2, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sMrMimeGfx34:
.incbin "baserom.gba", 0xA40448, 0x60
sMrMimeGfx34_1:
.incbin "baserom.gba", 0xA404A8, 0xE0
sMrMimeGfx34_2:
.incbin "baserom.gba", 0xA40588, 0x60
sMrMimeSprites34:
ax_sprite sMrMimeGfx34, 0x60
ax_sprite 0, 0x20
ax_sprite sMrMimeGfx34_1, 0xe0
ax_sprite 0, 0x20
ax_sprite sMrMimeGfx34_2, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sMrMimeGfx35:
.incbin "baserom.gba", 0xA40620, 0x100
sMrMimeGfx35_1:
.incbin "baserom.gba", 0xA40720, 0x40
sMrMimeGfx35_2:
.incbin "baserom.gba", 0xA40760, 0x20
sMrMimeSprites35:
ax_sprite sMrMimeGfx35, 0x100
ax_sprite 0, 0x20
ax_sprite sMrMimeGfx35_1, 0x40
ax_sprite 0, 0x40
ax_sprite sMrMimeGfx35_2, 0x20
ax_sprite 0, 0x40
ax_sprite_terminator
sMrMimeGfx36:
.incbin "baserom.gba", 0xA407B8, 0x60
sMrMimeGfx36_1:
.incbin "baserom.gba", 0xA40818, 0x60
sMrMimeGfx36_2:
.incbin "baserom.gba", 0xA40878, 0x60
sMrMimeGfx36_3:
.incbin "baserom.gba", 0xA408D8, 0x60
sMrMimeSprites36:
ax_sprite sMrMimeGfx36, 0x60
ax_sprite 0, 0x20
ax_sprite sMrMimeGfx36_1, 0x60
ax_sprite 0, 0x20
ax_sprite sMrMimeGfx36_2, 0x60
ax_sprite 0, 0x20
ax_sprite sMrMimeGfx36_3, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sMrMimeGfx37:
.incbin "baserom.gba", 0xA40980, 0x40
sMrMimeGfx37_1:
.incbin "baserom.gba", 0xA409C0, 0x60
sMrMimeGfx37_2:
.incbin "baserom.gba", 0xA40A20, 0x60
sMrMimeGfx37_3:
.incbin "baserom.gba", 0xA40A80, 0x60
sMrMimeSprites37:
ax_sprite sMrMimeGfx37, 0x40
ax_sprite 0, 0x40
ax_sprite sMrMimeGfx37_1, 0x60
ax_sprite 0, 0x20
ax_sprite sMrMimeGfx37_2, 0x60
ax_sprite 0, 0x20
ax_sprite sMrMimeGfx37_3, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sMrMimeGfx38:
.incbin "baserom.gba", 0xA40B28, 0x60
sMrMimeGfx38_1:
.incbin "baserom.gba", 0xA40B88, 0x60
sMrMimeGfx38_2:
.incbin "baserom.gba", 0xA40BE8, 0x60
sMrMimeGfx38_3:
.incbin "baserom.gba", 0xA40C48, 0x40
sMrMimeSprites38:
ax_sprite sMrMimeGfx38, 0x60
ax_sprite 0, 0x20
ax_sprite sMrMimeGfx38_1, 0x60
ax_sprite 0, 0x20
ax_sprite sMrMimeGfx38_2, 0x60
ax_sprite 0, 0x40
ax_sprite sMrMimeGfx38_3, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sMrMimeGfx39:
.incbin "baserom.gba", 0xA40CD0, 0x60
sMrMimeGfx39_1:
.incbin "baserom.gba", 0xA40D30, 0x60
sMrMimeGfx39_2:
.incbin "baserom.gba", 0xA40D90, 0x60
sMrMimeGfx39_3:
.incbin "baserom.gba", 0xA40DF0, 0x60
sMrMimeSprites39:
ax_sprite sMrMimeGfx39, 0x60
ax_sprite 0, 0x20
ax_sprite sMrMimeGfx39_1, 0x60
ax_sprite 0, 0x20
ax_sprite sMrMimeGfx39_2, 0x60
ax_sprite 0, 0x20
ax_sprite sMrMimeGfx39_3, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sMrMimeGfx40:
.incbin "baserom.gba", 0xA40E98, 0x60
sMrMimeGfx40_1:
.incbin "baserom.gba", 0xA40EF8, 0x60
sMrMimeGfx40_2:
.incbin "baserom.gba", 0xA40F58, 0x60
sMrMimeGfx40_3:
.incbin "baserom.gba", 0xA40FB8, 0x60
sMrMimeSprites40:
ax_sprite sMrMimeGfx40, 0x60
ax_sprite 0, 0x20
ax_sprite sMrMimeGfx40_1, 0x60
ax_sprite 0, 0x20
ax_sprite sMrMimeGfx40_2, 0x60
ax_sprite 0, 0x20
ax_sprite sMrMimeGfx40_3, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sMrMimeGfx41:
.incbin "baserom.gba", 0xA41060, 0x60
sMrMimeGfx41_1:
.incbin "baserom.gba", 0xA410C0, 0x60
sMrMimeGfx41_2:
.incbin "baserom.gba", 0xA41120, 0x60
sMrMimeGfx41_3:
.incbin "baserom.gba", 0xA41180, 0x60
sMrMimeSprites41:
ax_sprite sMrMimeGfx41, 0x60
ax_sprite 0, 0x20
ax_sprite sMrMimeGfx41_1, 0x60
ax_sprite 0, 0x20
ax_sprite sMrMimeGfx41_2, 0x60
ax_sprite 0, 0x20
ax_sprite sMrMimeGfx41_3, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sMrMimeGfx42:
.incbin "baserom.gba", 0xA41228, 0x40
sMrMimeGfx42_1:
.incbin "baserom.gba", 0xA41268, 0x60
sMrMimeGfx42_2:
.incbin "baserom.gba", 0xA412C8, 0x60
sMrMimeGfx42_3:
.incbin "baserom.gba", 0xA41328, 0x20
sMrMimeSprites42:
ax_sprite 0, 0x20
ax_sprite sMrMimeGfx42, 0x40
ax_sprite 0, 0x20
ax_sprite sMrMimeGfx42_1, 0x60
ax_sprite 0, 0x20
ax_sprite sMrMimeGfx42_2, 0x60
ax_sprite 0, 0x40
ax_sprite sMrMimeGfx42_3, 0x20
ax_sprite 0, 0x40
ax_sprite_terminator
sMrMimeGfx43:
.incbin "baserom.gba", 0xA41398, 0x40
sMrMimeGfx43_1:
.incbin "baserom.gba", 0xA413D8, 0x60
sMrMimeGfx43_2:
.incbin "baserom.gba", 0xA41438, 0x60
sMrMimeGfx43_3:
.incbin "baserom.gba", 0xA41498, 0x60
sMrMimeSprites43:
ax_sprite 0, 0x20
ax_sprite sMrMimeGfx43, 0x40
ax_sprite 0, 0x20
ax_sprite sMrMimeGfx43_1, 0x60
ax_sprite 0, 0x20
ax_sprite sMrMimeGfx43_2, 0x60
ax_sprite 0, 0x20
ax_sprite sMrMimeGfx43_3, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sMrMimeGfx44:
.incbin "baserom.gba", 0xA41548, 0x200
sMrMimeSprites44:
ax_sprite sMrMimeGfx44, 0x200
ax_sprite_terminator
sMrMimeGfx45:
.incbin "baserom.gba", 0xA41758, 0x200
sMrMimeSprites45:
ax_sprite sMrMimeGfx45, 0x200
ax_sprite_terminator
sMrMimeGfx46:
.incbin "baserom.gba", 0xA41968, 0x200
sMrMimeSprites46:
ax_sprite sMrMimeGfx46, 0x200
ax_sprite_terminator
sMrMimeGfx47:
.incbin "baserom.gba", 0xA41B78, 0x200
sMrMimeSprites47:
ax_sprite sMrMimeGfx47, 0x200
ax_sprite_terminator
sMrMimeGfx48:
.incbin "baserom.gba", 0xA41D88, 0x200
sMrMimeSprites48:
ax_sprite sMrMimeGfx48, 0x200
ax_sprite_terminator
sMrMimeGfx49:
.incbin "baserom.gba", 0xA41F98, 0x200
sMrMimeSprites49:
ax_sprite sMrMimeGfx49, 0x200
ax_sprite_terminator
sMrMimeGfx50:
.incbin "baserom.gba", 0xA421A8, 0x200
sMrMimeSprites50:
ax_sprite sMrMimeGfx50, 0x200
ax_sprite_terminator
sMrMimeGfx51:
.incbin "baserom.gba", 0xA423B8, 0x200
sMrMimeSprites51:
ax_sprite sMrMimeGfx51, 0x200
ax_sprite_terminator
sMrMimeGfx52:
.incbin "baserom.gba", 0xA425C8, 0x200
sMrMimeSprites52:
ax_sprite sMrMimeGfx52, 0x200
ax_sprite_terminator
sMrMimeGfx53:
.incbin "baserom.gba", 0xA427D8, 0x200
sMrMimeSprites53:
ax_sprite sMrMimeGfx53, 0x200
ax_sprite_terminator
sMrMimeGfx54:
.incbin "baserom.gba", 0xA429E8, 0x200
sMrMimeSprites54:
ax_sprite sMrMimeGfx54, 0x200
ax_sprite_terminator
sMrMimeGfx55:
.incbin "baserom.gba", 0xA42BF8, 0x200
sMrMimeSprites55:
ax_sprite sMrMimeGfx55, 0x200
ax_sprite_terminator
sMrMimeGfx56:
.incbin "baserom.gba", 0xA42E08, 0x200
sMrMimeSprites56:
ax_sprite sMrMimeGfx56, 0x200
ax_sprite_terminator
sMrMimeGfx57:
.incbin "baserom.gba", 0xA43018, 0x200
sMrMimeSprites57:
ax_sprite sMrMimeGfx57, 0x200
ax_sprite_terminator
sMrMimeGfx58:
.incbin "baserom.gba", 0xA43228, 0x200
sMrMimeSprites58:
ax_sprite sMrMimeGfx58, 0x200
ax_sprite_terminator
sAxPosesMrMime:
.4byte sMrMimePose1
.4byte sMrMimePose2
.4byte sMrMimePose3
.4byte sMrMimePose4
.4byte sMrMimePose5
.4byte sMrMimePose6
.4byte sMrMimePose7
.4byte sMrMimePose8
.4byte sMrMimePose9
.4byte sMrMimePose10
.4byte sMrMimePose11
.4byte sMrMimePose12
.4byte sMrMimePose13
.4byte sMrMimePose14
.4byte sMrMimePose15
.4byte sMrMimePose16
.4byte sMrMimePose17
.4byte sMrMimePose18
.4byte sMrMimePose19
.4byte sMrMimePose20
.4byte sMrMimePose21
.4byte sMrMimePose22
.4byte sMrMimePose23
.4byte sMrMimePose24
.4byte sMrMimePose25
.4byte sMrMimePose26
.4byte sMrMimePose27
.4byte sMrMimePose28
.4byte sMrMimePose29
.4byte sMrMimePose30
.4byte sMrMimePose31
.4byte sMrMimePose32
.4byte sMrMimePose33
.4byte sMrMimePose34
.4byte sMrMimePose35
.4byte sMrMimePose36
.4byte sMrMimePose37
.4byte sMrMimePose38
.4byte sMrMimePose39
.4byte sMrMimePose40
.4byte sMrMimePose41
.4byte sMrMimePose42
.4byte sMrMimePose43
.4byte sMrMimePose44
.4byte sMrMimePose45
.4byte sMrMimePose46
.4byte sMrMimePose47
.4byte sMrMimePose48
.4byte sMrMimePose49
.4byte sMrMimePose50
.4byte sMrMimePose51
.4byte sMrMimePose52
.4byte sMrMimePose53
.4byte sMrMimePose54
.4byte sMrMimePose55
.4byte sMrMimePose56
.4byte sMrMimePose57
.4byte sMrMimePose58
.4byte sMrMimePose59
.4byte sMrMimePose60
.4byte sMrMimePose61
.4byte sMrMimePose62
.4byte sMrMimePose63
.4byte sMrMimePose64
.4byte sMrMimePose65
.4byte sMrMimePose66
.4byte sMrMimePose67
.4byte sMrMimePose68
.4byte sMrMimePose69
.4byte sMrMimePose70
.4byte sMrMimePose71
.4byte sMrMimePose72
.4byte sMrMimePose73
.4byte sMrMimePose74
.4byte sMrMimePose75
.4byte sMrMimePose76
.4byte sMrMimePose77
.4byte sMrMimePose78
.4byte sMrMimePose79
.4byte sMrMimePose80
.4byte sMrMimePose81
.4byte sMrMimePose82
.4byte sMrMimePose83
.4byte sMrMimePose84
.4byte sMrMimePose85
.4byte sMrMimePose86
.4byte sMrMimePose87
.4byte sMrMimePose88
.4byte sMrMimePose89
.4byte sMrMimePose90
.4byte sMrMimePose91
.4byte sMrMimePose92
.4byte sMrMimePose93
.4byte sMrMimePose94
.4byte sMrMimePose95
.4byte sMrMimePose96
.4byte sMrMimePose97
.4byte sMrMimePose98
.4byte sMrMimePose99
.4byte sMrMimePose100
.4byte sMrMimePose101
.4byte sMrMimePose102
.4byte sMrMimePose103
.4byte sMrMimePose104
.4byte sMrMimePose105
.4byte sMrMimePose106
.4byte sMrMimePose107
.4byte sMrMimePose108
.4byte sMrMimePose109
.4byte sMrMimePose110
.4byte sMrMimePose111
.4byte sMrMimePose112
.4byte sMrMimePose113
.4byte sMrMimePose114
.4byte sMrMimePose115
.4byte sMrMimePose116
.4byte sMrMimePose117
.4byte sMrMimePose118
.4byte sMrMimePose119
.4byte sMrMimePose120
.4byte sMrMimePose121
.4byte sMrMimePose122
.4byte sMrMimePose123
.4byte sMrMimePose124
.4byte sMrMimePose125
.4byte sMrMimePose126
.4byte sMrMimePose127
.4byte sMrMimePose128
.4byte sMrMimePose129
.4byte sMrMimePose130
.4byte sMrMimePose131
.4byte sMrMimePose132
.4byte sMrMimePose133
.4byte sMrMimePose134
.4byte sMrMimePose135
.4byte sMrMimePose136
.4byte sMrMimePose137
.4byte sMrMimePose138
.4byte sMrMimePose139
.4byte sMrMimePose140
.4byte sMrMimePose141
.4byte sMrMimePose142
.4byte sMrMimePose143
.4byte sMrMimePose144
.4byte sMrMimePose145
.4byte sMrMimePose146
.4byte sMrMimePose147
.4byte sMrMimePose148
.4byte sMrMimePose149
.4byte sMrMimePose150
.4byte sMrMimePose151
.4byte sMrMimePose152
.4byte sMrMimePose153
.4byte sMrMimePose154
.4byte sMrMimePose155
.4byte sMrMimePose156
.4byte sMrMimePose157
.4byte sMrMimePose158
.4byte sMrMimePose159
.4byte sMrMimePose160
.4byte sMrMimePose161
.4byte sMrMimePose162
.4byte sMrMimePose163
.4byte sMrMimePose164
.4byte sMrMimePose165
.4byte sMrMimePose166
.4byte sMrMimePose167
.4byte sMrMimePose168
.4byte sMrMimePose169
.4byte sMrMimePose170
.4byte sMrMimePose171
.4byte sMrMimePose172
.4byte sMrMimePose173
.4byte sMrMimePose174
.4byte sMrMimePose175
.4byte sMrMimePose176
.4byte sMrMimePose177
.4byte sMrMimePose178
.4byte sMrMimePose179
.4byte sMrMimePose180
.4byte sMrMimePose181
.4byte sMrMimePose182
.4byte sMrMimePose183
.4byte sMrMimePose184
.4byte sMrMimePose185
.4byte sMrMimePose186
.4byte sMrMimePose187
.4byte sMrMimePose188
.4byte sMrMimePose189
.4byte sMrMimePose190
.4byte sMrMimePose191
.4byte sMrMimePose192
.4byte sMrMimePose193
.4byte sMrMimePose194
.4byte sMrMimePose195
.4byte sMrMimePose196
.4byte sMrMimePose197
.4byte sMrMimePose198
.4byte sMrMimePose199
.4byte sMrMimePose200
.4byte sMrMimePose201
.4byte sMrMimePose202
sAxPositionsMrMime:
.2byte    1,  -10, 	 -10,   -3, 	  11,   -3, 	   1,   -9
.2byte    1,   -9, 	  -9,   -4, 	   6,    0, 	   1,   -8
.2byte    1,   -9, 	  -4,   -1, 	  10,   -4, 	   1,   -8
.2byte    2,  -10, 	   9,   -4, 	  -8,    0, 	   0,   -9
.2byte    2,   -9, 	   6,   -6, 	   1,    1, 	   0,   -7
.2byte    2,   -9, 	   8,    0, 	 -10,   -3, 	   0,   -7
.2byte    5,  -13, 	   1,   -7, 	   1,    0, 	  -2,  -10
.2byte    5,  -12, 	  -7,   -6, 	   6,   -2, 	  -2,   -9
.2byte    5,  -12, 	   8,   -6, 	  -8,    0, 	  -2,   -9
.2byte    3,  -14, 	  -4,   -7, 	  10,   -1, 	  -2,  -11
.2byte    2,  -14, 	 -10,   -5, 	  11,   -7, 	  -2,  -10
.2byte    2,  -14, 	  -1,   -9, 	   3,    2, 	  -2,  -10
.2byte   -1,  -15, 	  10,   -5, 	 -11,   -5, 	  -1,  -12
.2byte    0,  -14, 	   8,   -1, 	  -7,   -7, 	   0,  -11
.2byte   -1,  -14, 	   6,   -7, 	  -9,   -1, 	  -1,  -11
.2byte   -4,  -14, 	   3,   -7, 	 -11,   -1, 	   1,  -11
.2byte   -3,  -14, 	   9,   -5, 	 -12,   -7, 	   1,  -10
.2byte   -3,  -14, 	   0,   -9, 	  -4,    2, 	   1,  -10
.2byte   -6,  -13, 	  -2,   -7, 	  -2,    0, 	   1,  -10
.2byte   -6,  -12, 	   6,   -6, 	  -7,   -2, 	   1,   -9
.2byte   -6,  -12, 	  -9,   -6, 	   7,    0, 	   1,   -9
.2byte   -2,  -10, 	  -9,   -4, 	   8,    0, 	   0,   -9
.2byte   -2,   -9, 	  -6,   -6, 	  -1,    1, 	   0,   -7
.2byte   -2,   -9, 	  -8,    0, 	  10,   -3, 	   0,   -7
.2byte    1,  -10, 	 -10,   -3, 	  11,   -3, 	   1,   -9
.2byte    1,   -9, 	  -9,   -4, 	   6,    0, 	   1,   -8
.2byte    1,   -9, 	  -4,   -1, 	  10,   -4, 	   1,   -8
.2byte    2,  -10, 	   9,   -4, 	  -8,    0, 	   0,   -9
.2byte    2,   -9, 	   6,   -6, 	   1,    1, 	   0,   -7
.2byte    2,   -9, 	   8,    0, 	 -10,   -3, 	   0,   -7
.2byte    5,  -13, 	   1,   -7, 	   1,    0, 	  -2,  -10
.2byte    5,  -12, 	  -7,   -6, 	   6,   -2, 	  -2,   -9
.2byte    5,  -12, 	   8,   -6, 	  -8,    0, 	  -2,   -9
.2byte    3,  -14, 	  -4,   -7, 	  10,   -1, 	  -2,  -11
.2byte    2,  -14, 	 -10,   -5, 	  11,   -7, 	  -2,  -10
.2byte    2,  -14, 	  -1,   -9, 	   3,    2, 	  -2,  -10
.2byte   -1,  -15, 	  10,   -5, 	 -11,   -5, 	  -1,  -12
.2byte    0,  -14, 	   8,   -1, 	  -7,   -7, 	   0,  -11
.2byte   -1,  -14, 	   6,   -7, 	  -9,   -1, 	  -1,  -11
.2byte   -4,  -14, 	   3,   -7, 	 -11,   -1, 	   1,  -11
.2byte   -3,  -14, 	   9,   -5, 	 -12,   -7, 	   1,  -10
.2byte   -3,  -14, 	   0,   -9, 	  -4,    2, 	   1,  -10
.2byte   -6,  -13, 	  -2,   -7, 	  -2,    0, 	   1,  -10
.2byte   -6,  -12, 	   6,   -6, 	  -7,   -2, 	   1,   -9
.2byte   -6,  -12, 	  -9,   -6, 	   7,    0, 	   1,   -9
.2byte   -2,  -10, 	  -9,   -4, 	   8,    0, 	   0,   -9
.2byte   -2,   -9, 	  -6,   -6, 	  -1,    1, 	   0,   -7
.2byte   -2,   -9, 	  -8,    0, 	  10,   -3, 	   0,   -7
.2byte    1,  -10, 	 -10,   -3, 	  11,   -3, 	   1,   -9
.2byte    1,   -9, 	  -9,   -4, 	   6,    0, 	   1,   -8
.2byte    1,   -9, 	  -4,   -1, 	  10,   -4, 	   1,   -8
.2byte    2,  -10, 	   9,   -4, 	  -8,    0, 	   0,   -9
.2byte    2,   -9, 	   6,   -6, 	   1,    1, 	   0,   -7
.2byte    2,   -9, 	   8,    0, 	 -10,   -3, 	   0,   -7
.2byte    5,  -13, 	   1,   -7, 	   1,    0, 	  -2,  -10
.2byte    5,  -12, 	  -7,   -6, 	   6,   -2, 	  -2,   -9
.2byte    5,  -12, 	   8,   -6, 	  -8,    0, 	  -2,   -9
.2byte    3,  -14, 	  -4,   -7, 	  10,   -1, 	  -2,  -11
.2byte    2,  -14, 	 -10,   -5, 	  11,   -7, 	  -2,  -10
.2byte    2,  -14, 	  -1,   -9, 	   3,    2, 	  -2,  -10
.2byte   -1,  -15, 	  10,   -5, 	 -11,   -5, 	  -1,  -12
.2byte    0,  -14, 	   8,   -1, 	  -7,   -7, 	   0,  -11
.2byte   -1,  -14, 	   6,   -7, 	  -9,   -1, 	  -1,  -11
.2byte   -4,  -14, 	   3,   -7, 	 -11,   -1, 	   1,  -11
.2byte   -3,  -14, 	   9,   -5, 	 -12,   -7, 	   1,  -10
.2byte   -3,  -14, 	   0,   -9, 	  -4,    2, 	   1,  -10
.2byte   -6,  -13, 	  -2,   -7, 	  -2,    0, 	   1,  -10
.2byte   -6,  -12, 	   6,   -6, 	  -7,   -2, 	   1,   -9
.2byte   -6,  -12, 	  -9,   -6, 	   7,    0, 	   1,   -9
.2byte   -2,  -10, 	  -9,   -4, 	   8,    0, 	   0,   -9
.2byte   -2,   -9, 	  -6,   -6, 	  -1,    1, 	   0,   -7
.2byte   -2,   -9, 	  -8,    0, 	  10,   -3, 	   0,   -7
.2byte   -2,  -10, 	   1,   -2, 	  -1,   -7, 	  -1,   -9
.2byte   -1,  -10, 	   1,   -8, 	   3,   -5, 	  -1,   -9
.2byte    0,  -10, 	   3,   -9, 	   5,   -4, 	   1,   -9
.2byte    0,   -4, 	  -7,    0, 	   6,    0, 	   0,   -6
.2byte    1,  -10, 	 -10,   -3, 	  11,   -3, 	   1,   -9
.2byte    4,   -7, 	   4,    0, 	   4,   -5, 	   3,   -9
.2byte    3,   -8, 	   1,   -6, 	   1,   -3, 	   2,  -10
.2byte    3,   -8, 	   1,   -7, 	  -2,   -1, 	   0,   -9
.2byte    2,   -5, 	  12,   -3, 	   2,    1, 	   0,   -6
.2byte    2,  -10, 	   9,   -4, 	  -8,    0, 	   0,   -9
.2byte    6,   -9, 	   8,   -2, 	  11,   -8, 	   2,  -10
.2byte    5,  -10, 	   5,   -7, 	  10,   -5, 	   2,  -11
.2byte    4,  -10, 	   9,   -8, 	   5,   -2, 	   1,  -11
.2byte    7,   -8, 	  17,  -13, 	  17,   -7, 	   3,  -11
.2byte    5,  -13, 	   1,   -7, 	   1,    0, 	  -2,  -10
.2byte    2,  -12, 	   4,   -6, 	   2,  -13, 	  -1,  -11
.2byte    2,  -13, 	   3,  -10, 	   5,   -8, 	  -1,  -12
.2byte    3,  -12, 	   4,  -11, 	   3,   -7, 	  -1,  -12
.2byte    6,  -11, 	   8,  -23, 	  18,  -19, 	   2,  -12
.2byte    3,  -14, 	  -4,   -7, 	  10,   -1, 	  -2,  -11
.2byte    1,  -14, 	   1,   -7, 	   0,  -12, 	   0,  -11
.2byte    0,  -15, 	  -1,  -10, 	  -2,  -11, 	  -1,  -13
.2byte   -1,  -15, 	  -1,  -11, 	  -3,   -9, 	  -2,  -12
.2byte    0,  -16, 	   5,  -22, 	  -6,  -22, 	   0,  -13
.2byte   -1,  -15, 	  10,   -5, 	 -11,   -5, 	  -1,  -12
.2byte   -3,  -12, 	  -5,   -6, 	  -3,  -13, 	   0,  -11
.2byte   -3,  -13, 	  -4,  -10, 	  -6,   -8, 	   0,  -12
.2byte   -4,  -12, 	  -5,  -11, 	  -4,   -7, 	   0,  -12
.2byte   -7,  -11, 	  -9,  -23, 	 -19,  -19, 	  -3,  -12
.2byte   -4,  -14, 	   3,   -7, 	 -11,   -1, 	   1,  -11
.2byte   -7,   -9, 	  -9,   -2, 	 -12,   -8, 	  -3,  -10
.2byte   -6,  -10, 	  -6,   -7, 	 -11,   -5, 	  -3,  -11
.2byte   -5,  -10, 	 -10,   -8, 	  -6,   -2, 	  -2,  -11
.2byte   -8,   -8, 	 -18,  -13, 	 -18,   -7, 	  -4,  -11
.2byte   -6,  -13, 	  -2,   -7, 	  -2,    0, 	   1,  -10
.2byte   -5,   -7, 	  -5,    0, 	  -5,   -5, 	  -4,   -9
.2byte   -4,   -8, 	  -2,   -6, 	  -2,   -3, 	  -3,  -10
.2byte   -4,   -8, 	  -2,   -7, 	   1,   -1, 	  -1,   -9
.2byte   -3,   -5, 	 -13,   -3, 	  -3,    1, 	  -1,   -6
.2byte   -2,  -10, 	  -9,   -4, 	   8,    0, 	   0,   -9
.2byte    0,  -10, 	  -3,   -3, 	   0,  -19, 	   1,   -9
.2byte   -3,  -11, 	  -9,   -5, 	  -3,  -19, 	  -1,  -10
.2byte   -4,  -12, 	  -3,   -7, 	  -8,  -19, 	   1,  -10
.2byte   -3,  -15, 	   0,   -8, 	  -7,  -23, 	   1,  -11
.2byte    0,  -15, 	   2,   -8, 	  -1,  -22, 	   0,  -12
.2byte    3,  -14, 	   2,   -9, 	   3,  -22, 	  -1,  -12
.2byte    4,  -11, 	   9,   -8, 	   8,  -20, 	  -1,  -12
.2byte    3,  -10, 	   2,   -4, 	   4,  -19, 	   0,  -10
.2byte   -2,   -7, 	  -9,   -6, 	  10,    2, 	   0,   -6
.2byte   -2,   -6, 	  -9,   -6, 	  10,    2, 	   0,   -6
.2byte    0,  -13, 	   2,  -23, 	  -3,  -24, 	   0,   -9
.2byte    0,  -13, 	  -5,  -23, 	  -1,  -24, 	  -2,  -10
.2byte    4,  -13, 	   0,  -22, 	   1,  -23, 	  -1,  -11
.2byte    2,  -15, 	   2,  -23, 	   1,  -22, 	  -1,  -10
.2byte    1,  -14, 	  -1,  -25, 	   2,  -23, 	   1,  -11
.2byte   -3,  -15, 	  -3,  -23, 	  -2,  -22, 	   0,  -10
.2byte   -5,  -13, 	  -1,  -22, 	  -2,  -23, 	   0,  -11
.2byte   -1,  -13, 	   4,  -23, 	   0,  -24, 	   1,  -10
.2byte    0,  -10, 	  -3,   -3, 	   0,  -19, 	   1,   -9
.2byte   -3,  -11, 	  -9,   -5, 	  -3,  -19, 	  -1,  -10
.2byte   -4,  -12, 	  -3,   -7, 	  -8,  -19, 	   1,  -10
.2byte   -3,  -15, 	   0,   -8, 	  -7,  -23, 	   1,  -11
.2byte    0,  -15, 	   2,   -8, 	  -1,  -22, 	   0,  -12
.2byte    3,  -14, 	   2,   -9, 	   3,  -22, 	  -1,  -12
.2byte    4,  -11, 	   9,   -8, 	   8,  -20, 	  -1,  -12
.2byte    3,  -10, 	   2,   -4, 	   4,  -19, 	   0,  -10
.2byte    0,   -9, 	  -2,   -2, 	  -1,  -18, 	   0,   -8
.2byte   -2,  -10, 	  -8,   -4, 	  -4,  -18, 	  -1,   -9
.2byte   -4,  -10, 	  -2,   -8, 	  -8,  -17, 	   1,   -9
.2byte   -3,  -14, 	  -4,   -8, 	  -7,  -20, 	   0,  -10
.2byte    0,  -14, 	  -2,   -8, 	   0,  -21, 	   0,  -11
.2byte    3,  -14, 	   2,  -10, 	   5,  -20, 	  -2,  -11
.2byte    4,  -10, 	   8,   -9, 	   9,  -18, 	  -1,  -11
.2byte    4,  -10, 	   4,   -4, 	   3,  -18, 	   0,   -9
.2byte    0,   -6, 	  -7,   -2, 	   6,   -2, 	   0,   -8
.2byte   -3,   -6, 	 -13,   -4, 	  -3,    0, 	  -1,   -7
.2byte   -3,   -7, 	 -13,  -12, 	 -13,   -6, 	   1,  -10
.2byte   -1,   -8, 	  -3,  -20, 	 -13,  -16, 	   3,   -9
.2byte    0,  -11, 	   5,  -17, 	  -6,  -17, 	   0,   -8
.2byte    0,   -8, 	   2,  -20, 	  12,  -16, 	  -4,   -9
.2byte    2,   -7, 	  12,  -12, 	  12,   -6, 	  -2,  -10
.2byte    2,   -6, 	  12,   -4, 	   2,    0, 	   0,   -7
.2byte    0,  -10, 	  -3,   -3, 	   0,  -19, 	   1,   -9
.2byte    3,  -10, 	   2,   -4, 	   4,  -19, 	   0,  -10
.2byte    4,  -11, 	   9,   -8, 	   8,  -20, 	  -1,  -12
.2byte    3,  -14, 	   2,   -9, 	   3,  -22, 	  -1,  -12
.2byte    0,  -15, 	   2,   -8, 	  -1,  -22, 	   0,  -12
.2byte   -3,  -15, 	   0,   -8, 	  -7,  -23, 	   1,  -11
.2byte   -4,  -12, 	  -3,   -7, 	  -8,  -19, 	   1,  -10
.2byte   -3,  -11, 	  -9,   -5, 	  -3,  -19, 	  -1,  -10
.2byte    1,  -10, 	 -10,   -3, 	  11,   -3, 	   1,   -9
.2byte    1,   -9, 	  -9,   -4, 	   6,    0, 	   1,   -8
.2byte    1,   -9, 	  -4,   -1, 	  10,   -4, 	   1,   -8
.2byte    2,  -10, 	   9,   -4, 	  -8,    0, 	   0,   -9
.2byte    2,   -9, 	   6,   -6, 	   1,    1, 	   0,   -7
.2byte    2,   -9, 	   8,    0, 	 -10,   -3, 	   0,   -7
.2byte    5,  -13, 	   1,   -7, 	   1,    0, 	  -2,  -10
.2byte    5,  -12, 	  -7,   -6, 	   6,   -2, 	  -2,   -9
.2byte    5,  -12, 	   8,   -6, 	  -8,    0, 	  -2,   -9
.2byte    3,  -14, 	  -4,   -7, 	  10,   -1, 	  -2,  -11
.2byte    2,  -14, 	 -10,   -5, 	  11,   -7, 	  -2,  -10
.2byte    2,  -14, 	  -1,   -9, 	   3,    2, 	  -2,  -10
.2byte   -1,  -15, 	  10,   -5, 	 -11,   -5, 	  -1,  -12
.2byte    0,  -14, 	   8,   -1, 	  -7,   -7, 	   0,  -11
.2byte   -1,  -14, 	   6,   -7, 	  -9,   -1, 	  -1,  -11
.2byte   -4,  -14, 	   3,   -7, 	 -11,   -1, 	   1,  -11
.2byte   -3,  -14, 	   9,   -5, 	 -12,   -7, 	   1,  -10
.2byte   -3,  -14, 	   0,   -9, 	  -4,    2, 	   1,  -10
.2byte   -6,  -13, 	  -2,   -7, 	  -2,    0, 	   1,  -10
.2byte   -6,  -12, 	   6,   -6, 	  -7,   -2, 	   1,   -9
.2byte   -6,  -12, 	  -9,   -6, 	   7,    0, 	   1,   -9
.2byte   -2,  -10, 	  -9,   -4, 	   8,    0, 	   0,   -9
.2byte   -2,   -9, 	  -6,   -6, 	  -1,    1, 	   0,   -7
.2byte   -2,   -9, 	  -8,    0, 	  10,   -3, 	   0,   -7
.2byte    0,   -6, 	  -7,   -2, 	   6,   -2, 	   0,   -8
.2byte   -3,   -6, 	 -13,   -4, 	  -3,    0, 	  -1,   -7
.2byte   -3,   -7, 	 -13,  -12, 	 -13,   -6, 	   1,  -10
.2byte   -1,   -8, 	  -3,  -20, 	 -13,  -16, 	   3,   -9
.2byte    0,  -11, 	   5,  -17, 	  -6,  -17, 	   0,   -8
.2byte    0,   -8, 	   2,  -20, 	  12,  -16, 	  -4,   -9
.2byte    2,   -7, 	  12,  -12, 	  12,   -6, 	  -2,  -10
.2byte    2,   -6, 	  12,   -4, 	   2,    0, 	   0,   -7
.2byte    0,  -10, 	  -3,   -3, 	   0,  -19, 	   1,   -9
.2byte   -3,  -11, 	  -9,   -5, 	  -3,  -19, 	  -1,  -10
.2byte   -4,  -12, 	  -3,   -7, 	  -8,  -19, 	   1,  -10
.2byte   -3,  -15, 	   0,   -8, 	  -7,  -23, 	   1,  -11
.2byte    0,  -15, 	   2,   -8, 	  -1,  -22, 	   0,  -12
.2byte    3,  -14, 	   2,   -9, 	   3,  -22, 	  -1,  -12
.2byte    4,  -11, 	   9,   -8, 	   8,  -20, 	  -1,  -12
.2byte    3,  -10, 	   2,   -4, 	   4,  -19, 	   0,  -10
sMrMimeAnimTable1:
.4byte sMrMimeAnims_1_1
.4byte sMrMimeAnims_1_2
.4byte sMrMimeAnims_1_3
.4byte sMrMimeAnims_1_4
.4byte sMrMimeAnims_1_5
.4byte sMrMimeAnims_1_6
.4byte sMrMimeAnims_1_7
.4byte sMrMimeAnims_1_8
sMrMimeAnimTable2:
.4byte sMrMimeAnims_2_1
.4byte sMrMimeAnims_2_2
.4byte sMrMimeAnims_2_3
.4byte sMrMimeAnims_2_4
.4byte sMrMimeAnims_2_5
.4byte sMrMimeAnims_2_6
.4byte sMrMimeAnims_2_7
.4byte sMrMimeAnims_2_8
sMrMimeAnimTable3:
.4byte sMrMimeAnims_3_1
.4byte sMrMimeAnims_3_2
.4byte sMrMimeAnims_3_3
.4byte sMrMimeAnims_3_4
.4byte sMrMimeAnims_3_5
.4byte sMrMimeAnims_3_6
.4byte sMrMimeAnims_3_7
.4byte sMrMimeAnims_3_8
sMrMimeAnimTable4:
.4byte sMrMimeAnims_4_1
.4byte sMrMimeAnims_4_2
.4byte sMrMimeAnims_4_3
.4byte sMrMimeAnims_4_4
.4byte sMrMimeAnims_4_5
.4byte sMrMimeAnims_4_6
.4byte sMrMimeAnims_4_7
.4byte sMrMimeAnims_4_8
sMrMimeAnimTable5:
.4byte sMrMimeAnims_5_1
.4byte sMrMimeAnims_5_2
.4byte sMrMimeAnims_5_3
.4byte sMrMimeAnims_5_4
.4byte sMrMimeAnims_5_5
.4byte sMrMimeAnims_5_6
.4byte sMrMimeAnims_5_7
.4byte sMrMimeAnims_5_8
sMrMimeAnimTable6:
.4byte sMrMimeAnims_6_1
.4byte sMrMimeAnims_6_1
.4byte sMrMimeAnims_6_1
.4byte sMrMimeAnims_6_1
.4byte sMrMimeAnims_6_1
.4byte sMrMimeAnims_6_1
.4byte sMrMimeAnims_6_1
.4byte sMrMimeAnims_6_1
sMrMimeAnimTable7:
.4byte sMrMimeAnims_7_1
.4byte sMrMimeAnims_7_2
.4byte sMrMimeAnims_7_3
.4byte sMrMimeAnims_7_4
.4byte sMrMimeAnims_7_5
.4byte sMrMimeAnims_7_6
.4byte sMrMimeAnims_7_7
.4byte sMrMimeAnims_7_8
sMrMimeAnimTable8:
.4byte sMrMimeAnims_8_1
.4byte sMrMimeAnims_8_2
.4byte sMrMimeAnims_8_3
.4byte sMrMimeAnims_8_4
.4byte sMrMimeAnims_8_5
.4byte sMrMimeAnims_8_6
.4byte sMrMimeAnims_8_7
.4byte sMrMimeAnims_8_8
sMrMimeAnimTable9:
.4byte sMrMimeAnims_9_1
.4byte sMrMimeAnims_9_2
.4byte sMrMimeAnims_9_3
.4byte sMrMimeAnims_9_4
.4byte sMrMimeAnims_9_5
.4byte sMrMimeAnims_9_6
.4byte sMrMimeAnims_9_7
.4byte sMrMimeAnims_9_8
sMrMimeAnimTable10:
.4byte sMrMimeAnims_10_1
.4byte sMrMimeAnims_10_2
.4byte sMrMimeAnims_10_3
.4byte sMrMimeAnims_10_4
.4byte sMrMimeAnims_10_5
.4byte sMrMimeAnims_10_6
.4byte sMrMimeAnims_10_7
.4byte sMrMimeAnims_10_8
sMrMimeAnimTable11:
.4byte sMrMimeAnims_11_1
.4byte sMrMimeAnims_11_2
.4byte sMrMimeAnims_11_3
.4byte sMrMimeAnims_11_4
.4byte sMrMimeAnims_11_5
.4byte sMrMimeAnims_11_6
.4byte sMrMimeAnims_11_7
.4byte sMrMimeAnims_11_8
sMrMimeAnimTable12:
.4byte sMrMimeAnims_12_1
.4byte sMrMimeAnims_12_2
.4byte sMrMimeAnims_12_3
.4byte sMrMimeAnims_12_4
.4byte sMrMimeAnims_12_5
.4byte sMrMimeAnims_12_6
.4byte sMrMimeAnims_12_7
.4byte sMrMimeAnims_12_8
sMrMimeAnimTable13:
.4byte sMrMimeAnims_13_1
.4byte sMrMimeAnims_13_2
.4byte sMrMimeAnims_13_3
.4byte sMrMimeAnims_13_4
.4byte sMrMimeAnims_13_5
.4byte sMrMimeAnims_13_6
.4byte sMrMimeAnims_13_7
.4byte sMrMimeAnims_13_8
sAxAnimationsMrMime:
.4byte sMrMimeAnimTable1
.4byte sMrMimeAnimTable2
.4byte sMrMimeAnimTable3
.4byte sMrMimeAnimTable4
.4byte sMrMimeAnimTable5
.4byte sMrMimeAnimTable6
.4byte sMrMimeAnimTable7
.4byte sMrMimeAnimTable8
.4byte sMrMimeAnimTable9
.4byte sMrMimeAnimTable10
.4byte sMrMimeAnimTable11
.4byte sMrMimeAnimTable12
.4byte sMrMimeAnimTable13
sAxSpritesMrMime:
.4byte sMrMimeSprites1
.4byte sMrMimeSprites2
.4byte sMrMimeSprites3
.4byte sMrMimeSprites4
.4byte sMrMimeSprites5
.4byte sMrMimeSprites6
.4byte sMrMimeSprites7
.4byte sMrMimeSprites8
.4byte sMrMimeSprites9
.4byte sMrMimeSprites10
.4byte sMrMimeSprites11
.4byte sMrMimeSprites12
.4byte sMrMimeSprites13
.4byte sMrMimeSprites14
.4byte sMrMimeSprites15
.4byte sMrMimeSprites16
.4byte sMrMimeSprites17
.4byte sMrMimeSprites18
.4byte sMrMimeSprites19
.4byte sMrMimeSprites20
.4byte sMrMimeSprites21
.4byte sMrMimeSprites22
.4byte sMrMimeSprites23
.4byte sMrMimeSprites24
.4byte sMrMimeSprites25
.4byte sMrMimeSprites26
.4byte sMrMimeSprites27
.4byte sMrMimeSprites28
.4byte sMrMimeSprites29
.4byte sMrMimeSprites30
.4byte sMrMimeSprites31
.4byte sMrMimeSprites32
.4byte sMrMimeSprites33
.4byte sMrMimeSprites34
.4byte sMrMimeSprites35
.4byte sMrMimeSprites36
.4byte sMrMimeSprites37
.4byte sMrMimeSprites38
.4byte sMrMimeSprites39
.4byte sMrMimeSprites40
.4byte sMrMimeSprites41
.4byte sMrMimeSprites42
.4byte sMrMimeSprites43
.4byte sMrMimeSprites44
.4byte sMrMimeSprites45
.4byte sMrMimeSprites46
.4byte sMrMimeSprites47
.4byte sMrMimeSprites48
.4byte sMrMimeSprites49
.4byte sMrMimeSprites50
.4byte sMrMimeSprites51
.4byte sMrMimeSprites52
.4byte sMrMimeSprites53
.4byte sMrMimeSprites54
.4byte sMrMimeSprites55
.4byte sMrMimeSprites56
.4byte sMrMimeSprites57
.4byte sMrMimeSprites58
sAxMainMrMime:
ax_main sAxPosesMrMime, sAxAnimationsMrMime, 13, sAxSpritesMrMime, sAxPositionsMrMime
