.global gAxNidorino
gAxNidorino:
ax_siro sAxMainNidorino
sNidorinoPose1:
ax_pose 0, 0x01ec, 0x80f4, 0x1c00
ax_pose_terminator
sNidorinoPose2:
ax_pose 1, 0x01e7, 0x80f4, 0x1c00
ax_pose_terminator
sNidorinoPose3:
ax_pose 2, 0x01e7, 0x80f4, 0x1c00
ax_pose_terminator
sNidorinoPose4:
ax_pose 3, 0x01e7, 0x90ef, 0x1c00
ax_pose_terminator
sNidorinoPose5:
ax_pose 4, 0x01e7, 0x90ef, 0x1c00
ax_pose_terminator
sNidorinoPose6:
ax_pose 5, 0x01e7, 0x90ef, 0x1c00
ax_pose_terminator
sNidorinoPose7:
ax_pose 6, 0x01e7, 0x90f1, 0x1c00
ax_pose_terminator
sNidorinoPose8:
ax_pose 7, 0x01e7, 0x90f1, 0x1c00
ax_pose_terminator
sNidorinoPose9:
ax_pose 8, 0x01e7, 0x90f1, 0x1c00
ax_pose_terminator
sNidorinoPose10:
ax_pose 9, 0x01e7, 0x90ef, 0x1c00
ax_pose_terminator
sNidorinoPose11:
ax_pose 10, 0x01e7, 0x90ef, 0x1c00
ax_pose_terminator
sNidorinoPose12:
ax_pose 11, 0x01e7, 0x90ef, 0x1c00
ax_pose_terminator
sNidorinoPose13:
ax_pose 12, 0x01e7, 0x80f0, 0x1c00
ax_pose_terminator
sNidorinoPose14:
ax_pose 13, 0x01e7, 0x80f0, 0x1c00
ax_pose_terminator
sNidorinoPose15:
ax_pose 14, 0x01e7, 0x80f0, 0x1c00
ax_pose_terminator
sNidorinoPose16:
ax_pose 9, 0x01e7, 0x80f0, 0x1c00
ax_pose_terminator
sNidorinoPose17:
ax_pose 10, 0x01e7, 0x80f0, 0x1c00
ax_pose_terminator
sNidorinoPose18:
ax_pose 11, 0x01e7, 0x80f0, 0x1c00
ax_pose_terminator
sNidorinoPose19:
ax_pose 6, 0x01e7, 0x80ee, 0x1c00
ax_pose_terminator
sNidorinoPose20:
ax_pose 7, 0x01e7, 0x80ee, 0x1c00
ax_pose_terminator
sNidorinoPose21:
ax_pose 8, 0x01e7, 0x80ee, 0x1c00
ax_pose_terminator
sNidorinoPose22:
ax_pose 3, 0x01e7, 0x80f0, 0x1c00
ax_pose_terminator
sNidorinoPose23:
ax_pose 4, 0x01e7, 0x80f0, 0x1c00
ax_pose_terminator
sNidorinoPose24:
ax_pose 5, 0x01e7, 0x80f0, 0x1c00
ax_pose_terminator
sNidorinoPose25:
ax_pose 0, 0x01ec, 0x80f4, 0x1c00
ax_pose_terminator
sNidorinoPose26:
ax_pose 1, 0x01e7, 0x80f4, 0x1c00
ax_pose_terminator
sNidorinoPose27:
ax_pose 2, 0x01e7, 0x80f4, 0x1c00
ax_pose_terminator
sNidorinoPose28:
ax_pose 15, 0x01e8, 0x80f3, 0x1c00
ax_pose_terminator
sNidorinoPose29:
ax_pose 3, 0x01e7, 0x90ef, 0x1c00
ax_pose_terminator
sNidorinoPose30:
ax_pose 4, 0x01e7, 0x90ef, 0x1c00
ax_pose_terminator
sNidorinoPose31:
ax_pose 5, 0x01e7, 0x90f0, 0x1c00
ax_pose_terminator
sNidorinoPose32:
ax_pose 16, 0x01e7, 0x90ef, 0x1c00
ax_pose_terminator
sNidorinoPose33:
ax_pose 6, 0x01e7, 0x90f1, 0x1c00
ax_pose_terminator
sNidorinoPose34:
ax_pose 7, 0x01e7, 0x90f1, 0x1c00
ax_pose_terminator
sNidorinoPose35:
ax_pose 8, 0x01e7, 0x90f1, 0x1c00
ax_pose_terminator
sNidorinoPose36:
ax_pose 17, 0x01e7, 0x90f2, 0x1c00
ax_pose_terminator
sNidorinoPose37:
ax_pose 9, 0x01e7, 0x90ef, 0x1c00
ax_pose_terminator
sNidorinoPose38:
ax_pose 10, 0x01e7, 0x90ef, 0x1c00
ax_pose_terminator
sNidorinoPose39:
ax_pose 11, 0x01e7, 0x90ef, 0x1c00
ax_pose_terminator
sNidorinoPose40:
ax_pose 18, 0x01e7, 0x90ef, 0x1c00
ax_pose_terminator
sNidorinoPose41:
ax_pose 12, 0x01e7, 0x80f0, 0x1c00
ax_pose_terminator
sNidorinoPose42:
ax_pose 13, 0x01e7, 0x80f0, 0x1c00
ax_pose_terminator
sNidorinoPose43:
ax_pose 14, 0x01e7, 0x80f0, 0x1c00
ax_pose_terminator
sNidorinoPose44:
ax_pose 19, 0x01e8, 0x80f0, 0x1c00
ax_pose_terminator
sNidorinoPose45:
ax_pose 9, 0x01e7, 0x80f1, 0x1c00
ax_pose_terminator
sNidorinoPose46:
ax_pose 10, 0x01e7, 0x80f1, 0x1c00
ax_pose_terminator
sNidorinoPose47:
ax_pose 11, 0x01e7, 0x80f1, 0x1c00
ax_pose_terminator
sNidorinoPose48:
ax_pose 18, 0x01e7, 0x80f1, 0x1c00
ax_pose_terminator
sNidorinoPose49:
ax_pose 6, 0x01e7, 0x80ef, 0x1c00
ax_pose_terminator
sNidorinoPose50:
ax_pose 7, 0x01e7, 0x80ef, 0x1c00
ax_pose_terminator
sNidorinoPose51:
ax_pose 8, 0x01e7, 0x80ef, 0x1c00
ax_pose_terminator
sNidorinoPose52:
ax_pose 17, 0x01e7, 0x80ee, 0x1c00
ax_pose_terminator
sNidorinoPose53:
ax_pose 3, 0x01e7, 0x80f1, 0x1c00
ax_pose_terminator
sNidorinoPose54:
ax_pose 4, 0x01e7, 0x80f1, 0x1c00
ax_pose_terminator
sNidorinoPose55:
ax_pose 5, 0x01e7, 0x80f0, 0x1c00
ax_pose_terminator
sNidorinoPose56:
ax_pose 16, 0x01e7, 0x80f1, 0x1c00
ax_pose_terminator
sNidorinoPose57:
ax_pose 0, 0x01ec, 0x80f4, 0x1c00
ax_pose_terminator
sNidorinoPose58:
ax_pose 1, 0x01e7, 0x80f4, 0x1c00
ax_pose_terminator
sNidorinoPose59:
ax_pose 2, 0x01e7, 0x80f4, 0x1c00
ax_pose_terminator
sNidorinoPose60:
ax_pose 15, 0x01e8, 0x80f3, 0x1c00
ax_pose_terminator
sNidorinoPose61:
ax_pose 3, 0x01e7, 0x90ef, 0x1c00
ax_pose_terminator
sNidorinoPose62:
ax_pose 4, 0x01e7, 0x90ef, 0x1c00
ax_pose_terminator
sNidorinoPose63:
ax_pose 5, 0x01e7, 0x90f0, 0x1c00
ax_pose_terminator
sNidorinoPose64:
ax_pose 16, 0x01e7, 0x90ef, 0x1c00
ax_pose_terminator
sNidorinoPose65:
ax_pose 6, 0x01e7, 0x90f1, 0x1c00
ax_pose_terminator
sNidorinoPose66:
ax_pose 7, 0x01e7, 0x90f1, 0x1c00
ax_pose_terminator
sNidorinoPose67:
ax_pose 8, 0x01e7, 0x90f1, 0x1c00
ax_pose_terminator
sNidorinoPose68:
ax_pose 17, 0x01e7, 0x90f2, 0x1c00
ax_pose_terminator
sNidorinoPose69:
ax_pose 9, 0x01e7, 0x90ef, 0x1c00
ax_pose_terminator
sNidorinoPose70:
ax_pose 10, 0x01e7, 0x90ef, 0x1c00
ax_pose_terminator
sNidorinoPose71:
ax_pose 11, 0x01e7, 0x90ef, 0x1c00
ax_pose_terminator
sNidorinoPose72:
ax_pose 18, 0x01e7, 0x90ef, 0x1c00
ax_pose_terminator
sNidorinoPose73:
ax_pose 12, 0x01e7, 0x80f0, 0x1c00
ax_pose_terminator
sNidorinoPose74:
ax_pose 13, 0x01e7, 0x80f0, 0x1c00
ax_pose_terminator
sNidorinoPose75:
ax_pose 14, 0x01e7, 0x80f0, 0x1c00
ax_pose_terminator
sNidorinoPose76:
ax_pose 19, 0x01e8, 0x80f0, 0x1c00
ax_pose_terminator
sNidorinoPose77:
ax_pose 9, 0x01e7, 0x80f1, 0x1c00
ax_pose_terminator
sNidorinoPose78:
ax_pose 10, 0x01e7, 0x80f1, 0x1c00
ax_pose_terminator
sNidorinoPose79:
ax_pose 11, 0x01e7, 0x80f1, 0x1c00
ax_pose_terminator
sNidorinoPose80:
ax_pose 18, 0x01e7, 0x80f1, 0x1c00
ax_pose_terminator
sNidorinoPose81:
ax_pose 6, 0x01e7, 0x80ef, 0x1c00
ax_pose_terminator
sNidorinoPose82:
ax_pose 7, 0x01e7, 0x80ef, 0x1c00
ax_pose_terminator
sNidorinoPose83:
ax_pose 8, 0x01e7, 0x80ef, 0x1c00
ax_pose_terminator
sNidorinoPose84:
ax_pose 17, 0x01e7, 0x80ee, 0x1c00
ax_pose_terminator
sNidorinoPose85:
ax_pose 3, 0x01e7, 0x80f1, 0x1c00
ax_pose_terminator
sNidorinoPose86:
ax_pose 4, 0x01e7, 0x80f1, 0x1c00
ax_pose_terminator
sNidorinoPose87:
ax_pose 5, 0x01e7, 0x80f0, 0x1c00
ax_pose_terminator
sNidorinoPose88:
ax_pose 16, 0x01e7, 0x80f1, 0x1c00
ax_pose_terminator
sNidorinoPose89:
ax_pose 0, 0x01ec, 0x80f4, 0x1c00
ax_pose_terminator
sNidorinoPose90:
ax_pose 20, 0x01e6, 0x80f3, 0x1c00
ax_pose_terminator
sNidorinoPose91:
ax_pose 15, 0x01e8, 0x80f3, 0x1c00
ax_pose_terminator
sNidorinoPose92:
ax_pose 3, 0x01e7, 0x90ef, 0x1c00
ax_pose_terminator
sNidorinoPose93:
ax_pose 21, 0x01e3, 0x90ef, 0x1c00
ax_pose_terminator
sNidorinoPose94:
ax_pose 16, 0x01e7, 0x90ef, 0x1c00
ax_pose_terminator
sNidorinoPose95:
ax_pose 6, 0x01e7, 0x90f1, 0x1c00
ax_pose_terminator
sNidorinoPose96:
ax_pose 22, 0x01e5, 0x90ef, 0x1c00
ax_pose_terminator
sNidorinoPose97:
ax_pose 17, 0x01e7, 0x90f3, 0x1c00
ax_pose_terminator
sNidorinoPose98:
ax_pose 9, 0x01e7, 0x90ef, 0x1c00
ax_pose_terminator
sNidorinoPose99:
ax_pose 23, 0x01e7, 0x90ef, 0x1c00
ax_pose_terminator
sNidorinoPose100:
ax_pose 18, 0x01e7, 0x90ef, 0x1c00
ax_pose_terminator
sNidorinoPose101:
ax_pose 12, 0x01e7, 0x80f0, 0x1c00
ax_pose_terminator
sNidorinoPose102:
ax_pose 24, 0x01e7, 0x80f0, 0x1c00
ax_pose_terminator
sNidorinoPose103:
ax_pose 19, 0x01e7, 0x80f0, 0x1c00
ax_pose_terminator
sNidorinoPose104:
ax_pose 9, 0x01e7, 0x80f0, 0x1c00
ax_pose_terminator
sNidorinoPose105:
ax_pose 23, 0x01e7, 0x80f0, 0x1c00
ax_pose_terminator
sNidorinoPose106:
ax_pose 18, 0x01e7, 0x80f0, 0x1c00
ax_pose_terminator
sNidorinoPose107:
ax_pose 6, 0x01e7, 0x80ee, 0x1c00
ax_pose_terminator
sNidorinoPose108:
ax_pose 22, 0x01e5, 0x80f0, 0x1c00
ax_pose_terminator
sNidorinoPose109:
ax_pose 17, 0x01e7, 0x80ec, 0x1c00
ax_pose_terminator
sNidorinoPose110:
ax_pose 3, 0x01e7, 0x80f0, 0x1c00
ax_pose_terminator
sNidorinoPose111:
ax_pose 21, 0x01e3, 0x80f0, 0x1c00
ax_pose_terminator
sNidorinoPose112:
ax_pose 16, 0x01e7, 0x80f0, 0x1c00
ax_pose_terminator
sNidorinoPose113:
ax_pose 0, 0x01ec, 0x80f4, 0x1c00
ax_pose_terminator
sNidorinoPose114:
ax_pose 25, 0x01eb, 0x80f2, 0x1c00
ax_pose_terminator
sNidorinoPose115:
ax_pose 26, 0x01eb, 0x80f2, 0x1c00
ax_pose_terminator
sNidorinoPose116:
ax_pose 3, 0x01e7, 0x90ef, 0x1c00
ax_pose_terminator
sNidorinoPose117:
ax_pose 27, 0x01e7, 0x90ef, 0x1c00
ax_pose_terminator
sNidorinoPose118:
ax_pose 28, 0x01e7, 0x90ef, 0x1c00
ax_pose_terminator
sNidorinoPose119:
ax_pose 6, 0x01e7, 0x90f1, 0x1c00
ax_pose_terminator
sNidorinoPose120:
ax_pose 29, 0x01e7, 0x90f2, 0x1c00
ax_pose_terminator
sNidorinoPose121:
ax_pose 30, 0x01e7, 0x90f2, 0x1c00
ax_pose_terminator
sNidorinoPose122:
ax_pose 9, 0x01e7, 0x90ef, 0x1c00
ax_pose_terminator
sNidorinoPose123:
ax_pose 31, 0x01e7, 0x90ef, 0x1c00
ax_pose_terminator
sNidorinoPose124:
ax_pose 32, 0x01e7, 0x90ef, 0x1c00
ax_pose_terminator
sNidorinoPose125:
ax_pose 12, 0x01e7, 0x80f0, 0x1c00
ax_pose_terminator
sNidorinoPose126:
ax_pose 33, 0x01e7, 0x80f0, 0x1c00
ax_pose_terminator
sNidorinoPose127:
ax_pose 34, 0x01e7, 0x80f0, 0x1c00
ax_pose_terminator
sNidorinoPose128:
ax_pose 9, 0x01e7, 0x80f0, 0x1c00
ax_pose_terminator
sNidorinoPose129:
ax_pose 31, 0x01e7, 0x80f0, 0x1c00
ax_pose_terminator
sNidorinoPose130:
ax_pose 32, 0x01e7, 0x80f0, 0x1c00
ax_pose_terminator
sNidorinoPose131:
ax_pose 6, 0x01e7, 0x80ee, 0x1c00
ax_pose_terminator
sNidorinoPose132:
ax_pose 29, 0x01e7, 0x80ed, 0x1c00
ax_pose_terminator
sNidorinoPose133:
ax_pose 30, 0x01e7, 0x80ed, 0x1c00
ax_pose_terminator
sNidorinoPose134:
ax_pose 3, 0x01e7, 0x80f0, 0x1c00
ax_pose_terminator
sNidorinoPose135:
ax_pose 27, 0x01e7, 0x80f0, 0x1c00
ax_pose_terminator
sNidorinoPose136:
ax_pose 28, 0x01e7, 0x80f0, 0x1c00
ax_pose_terminator
sNidorinoPose137:
ax_pose 35, 0x01e7, 0x80f0, 0x1c00
ax_pose_terminator
sNidorinoPose138:
ax_pose 36, 0x01e7, 0x80f0, 0x1c00
ax_pose_terminator
sNidorinoPose139:
ax_pose 37, 0x01e7, 0x80f0, 0x1c00
ax_pose_terminator
sNidorinoPose140:
ax_pose 38, 0x01e7, 0x90f2, 0x1c00
ax_pose_terminator
sNidorinoPose141:
ax_pose 39, 0x01e5, 0x90f2, 0x1c00
ax_pose_terminator
sNidorinoPose142:
ax_pose 40, 0x01e7, 0x90f1, 0x1c00
ax_pose_terminator
sNidorinoPose143:
ax_pose 41, 0x01e5, 0x80f1, 0x1c00
ax_pose_terminator
sNidorinoPose144:
ax_pose 40, 0x01e7, 0x80f1, 0x1c00
ax_pose_terminator
sNidorinoPose145:
ax_pose 39, 0x01e5, 0x80ee, 0x1c00
ax_pose_terminator
sNidorinoPose146:
ax_pose 38, 0x01e7, 0x80ee, 0x1c00
ax_pose_terminator
sNidorinoPose147:
ax_pose 0, 0x01ec, 0x80f4, 0x1c00
ax_pose_terminator
sNidorinoPose148:
ax_pose 1, 0x01e7, 0x80f4, 0x1c00
ax_pose_terminator
sNidorinoPose149:
ax_pose 2, 0x01e7, 0x80f4, 0x1c00
ax_pose_terminator
sNidorinoPose150:
ax_pose 3, 0x01e7, 0x90ef, 0x1c00
ax_pose_terminator
sNidorinoPose151:
ax_pose 4, 0x01e7, 0x90ef, 0x1c00
ax_pose_terminator
sNidorinoPose152:
ax_pose 5, 0x01e7, 0x90ef, 0x1c00
ax_pose_terminator
sNidorinoPose153:
ax_pose 6, 0x01e7, 0x90f1, 0x1c00
ax_pose_terminator
sNidorinoPose154:
ax_pose 7, 0x01e7, 0x90f1, 0x1c00
ax_pose_terminator
sNidorinoPose155:
ax_pose 8, 0x01e7, 0x90f1, 0x1c00
ax_pose_terminator
sNidorinoPose156:
ax_pose 9, 0x01e7, 0x90ef, 0x1c00
ax_pose_terminator
sNidorinoPose157:
ax_pose 10, 0x01e7, 0x90ef, 0x1c00
ax_pose_terminator
sNidorinoPose158:
ax_pose 11, 0x01e7, 0x90ef, 0x1c00
ax_pose_terminator
sNidorinoPose159:
ax_pose 12, 0x01e7, 0x80f0, 0x1c00
ax_pose_terminator
sNidorinoPose160:
ax_pose 13, 0x01e7, 0x80f0, 0x1c00
ax_pose_terminator
sNidorinoPose161:
ax_pose 14, 0x01e7, 0x80f0, 0x1c00
ax_pose_terminator
sNidorinoPose162:
ax_pose 9, 0x01e7, 0x80f0, 0x1c00
ax_pose_terminator
sNidorinoPose163:
ax_pose 10, 0x01e7, 0x80f0, 0x1c00
ax_pose_terminator
sNidorinoPose164:
ax_pose 11, 0x01e7, 0x80f0, 0x1c00
ax_pose_terminator
sNidorinoPose165:
ax_pose 6, 0x01e7, 0x80ee, 0x1c00
ax_pose_terminator
sNidorinoPose166:
ax_pose 7, 0x01e7, 0x80ee, 0x1c00
ax_pose_terminator
sNidorinoPose167:
ax_pose 8, 0x01e7, 0x80ee, 0x1c00
ax_pose_terminator
sNidorinoPose168:
ax_pose 3, 0x01e7, 0x80f0, 0x1c00
ax_pose_terminator
sNidorinoPose169:
ax_pose 4, 0x01e7, 0x80f0, 0x1c00
ax_pose_terminator
sNidorinoPose170:
ax_pose 5, 0x01e7, 0x80f0, 0x1c00
ax_pose_terminator
sNidorinoPose171:
ax_pose 15, 0x01e8, 0x80f3, 0x1c00
ax_pose_terminator
sNidorinoPose172:
ax_pose 16, 0x01e7, 0x80f1, 0x1c00
ax_pose_terminator
sNidorinoPose173:
ax_pose 17, 0x01e7, 0x80ee, 0x1c00
ax_pose_terminator
sNidorinoPose174:
ax_pose 18, 0x01e7, 0x80f1, 0x1c00
ax_pose_terminator
sNidorinoPose175:
ax_pose 19, 0x01e8, 0x80f0, 0x1c00
ax_pose_terminator
sNidorinoPose176:
ax_pose 18, 0x01e7, 0x90ef, 0x1c00
ax_pose_terminator
sNidorinoPose177:
ax_pose 17, 0x01e7, 0x90f2, 0x1c00
ax_pose_terminator
sNidorinoPose178:
ax_pose 16, 0x01e7, 0x90ef, 0x1c00
ax_pose_terminator
sNidorinoPose179:
ax_pose 15, 0x01e8, 0x80f3, 0x1c00
ax_pose_terminator
sNidorinoPose180:
ax_pose 16, 0x01e7, 0x80f1, 0x1c00
ax_pose_terminator
sNidorinoPose181:
ax_pose 17, 0x01e7, 0x80ee, 0x1c00
ax_pose_terminator
sNidorinoPose182:
ax_pose 18, 0x01ea, 0x80f1, 0x1c00
ax_pose_terminator
sNidorinoPose183:
ax_pose 19, 0x01ea, 0x80f0, 0x1c00
ax_pose_terminator
sNidorinoPose184:
ax_pose 18, 0x01ea, 0x90ef, 0x1c00
ax_pose_terminator
sNidorinoPose185:
ax_pose 17, 0x01e7, 0x90f2, 0x1c00
ax_pose_terminator
sNidorinoPose186:
ax_pose 16, 0x01e7, 0x90ef, 0x1c00
ax_pose_terminator
sNidorinoPose187:
ax_pose 0, 0x01ec, 0x80f4, 0x1c00
ax_pose_terminator
sNidorinoPose188:
ax_pose 20, 0x01e6, 0x80f3, 0x1c00
ax_pose_terminator
sNidorinoPose189:
ax_pose 15, 0x01e8, 0x80f3, 0x1c00
ax_pose_terminator
sNidorinoPose190:
ax_pose 3, 0x01e7, 0x90ef, 0x1c00
ax_pose_terminator
sNidorinoPose191:
ax_pose 21, 0x01e4, 0x90f4, 0x1c00
ax_pose_terminator
sNidorinoPose192:
ax_pose 16, 0x01e7, 0x90ef, 0x1c00
ax_pose_terminator
sNidorinoPose193:
ax_pose 6, 0x01e7, 0x90f1, 0x1c00
ax_pose_terminator
sNidorinoPose194:
ax_pose 22, 0x01e5, 0x90f2, 0x1c00
ax_pose_terminator
sNidorinoPose195:
ax_pose 17, 0x01e7, 0x90f2, 0x1c00
ax_pose_terminator
sNidorinoPose196:
ax_pose 9, 0x01e7, 0x90ef, 0x1c00
ax_pose_terminator
sNidorinoPose197:
ax_pose 23, 0x01e7, 0x90f2, 0x1c00
ax_pose_terminator
sNidorinoPose198:
ax_pose 18, 0x01e7, 0x90ef, 0x1c00
ax_pose_terminator
sNidorinoPose199:
ax_pose 12, 0x01e7, 0x80f0, 0x1c00
ax_pose_terminator
sNidorinoPose200:
ax_pose 24, 0x01e7, 0x80ef, 0x1c00
ax_pose_terminator
sNidorinoPose201:
ax_pose 19, 0x01e7, 0x80f0, 0x1c00
ax_pose_terminator
sNidorinoPose202:
ax_pose 9, 0x01e7, 0x80f0, 0x1c00
ax_pose_terminator
sNidorinoPose203:
ax_pose 23, 0x01e7, 0x80ed, 0x1c00
ax_pose_terminator
sNidorinoPose204:
ax_pose 18, 0x01e7, 0x80f0, 0x1c00
ax_pose_terminator
sNidorinoPose205:
ax_pose 6, 0x01e7, 0x80ee, 0x1c00
ax_pose_terminator
sNidorinoPose206:
ax_pose 22, 0x01e5, 0x80ed, 0x1c00
ax_pose_terminator
sNidorinoPose207:
ax_pose 17, 0x01e7, 0x80ed, 0x1c00
ax_pose_terminator
sNidorinoPose208:
ax_pose 3, 0x01e7, 0x80f0, 0x1c00
ax_pose_terminator
sNidorinoPose209:
ax_pose 21, 0x01e4, 0x80ed, 0x1c00
ax_pose_terminator
sNidorinoPose210:
ax_pose 16, 0x01e7, 0x80f0, 0x1c00
ax_pose_terminator
sNidorinoPose211:
ax_pose 15, 0x01e8, 0x80f3, 0x1c00
ax_pose_terminator
sNidorinoPose212:
ax_pose 16, 0x01e7, 0x80f1, 0x1c00
ax_pose_terminator
sNidorinoPose213:
ax_pose 17, 0x01e7, 0x80ee, 0x1c00
ax_pose_terminator
sNidorinoPose214:
ax_pose 18, 0x01ea, 0x80f1, 0x1c00
ax_pose_terminator
sNidorinoPose215:
ax_pose 19, 0x01ea, 0x80f0, 0x1c00
ax_pose_terminator
sNidorinoPose216:
ax_pose 18, 0x01ea, 0x90ef, 0x1c00
ax_pose_terminator
sNidorinoPose217:
ax_pose 17, 0x01e7, 0x90f2, 0x1c00
ax_pose_terminator
sNidorinoPose218:
ax_pose 16, 0x01e7, 0x90ef, 0x1c00
ax_pose_terminator
sNidorinoPose219:
ax_pose 0, 0x01ec, 0x80f4, 0x1c00
ax_pose_terminator
sNidorinoPose220:
ax_pose 3, 0x01e7, 0x80f0, 0x1c00
ax_pose_terminator
sNidorinoPose221:
ax_pose 6, 0x01e7, 0x80ee, 0x1c00
ax_pose_terminator
sNidorinoPose222:
ax_pose 9, 0x01e7, 0x80f0, 0x1c00
ax_pose_terminator
sNidorinoPose223:
ax_pose 12, 0x01e7, 0x80f0, 0x1c00
ax_pose_terminator
sNidorinoPose224:
ax_pose 9, 0x01e7, 0x90ef, 0x1c00
ax_pose_terminator
sNidorinoPose225:
ax_pose 6, 0x01e7, 0x90f1, 0x1c00
ax_pose_terminator
sNidorinoPose226:
ax_pose 3, 0x01e7, 0x90ef, 0x1c00
ax_pose_terminator
.align 2
sNidorinoAnims_1_1:
ax_anim 6, 0, 0, 0, 0, 0, 0,
ax_anim 12, 0, 1, 0, 0, 0, 0,
ax_anim 6, 0, 0, 0, 0, 0, 0,
ax_anim 12, 0, 2, 0, 0, 0, 0,
ax_anim_terminator
sNidorinoAnims_1_2:
ax_anim 6, 0, 3, 0, 0, 0, 0,
ax_anim 12, 0, 4, 0, 0, 0, 0,
ax_anim 6, 0, 3, 0, 0, 0, 0,
ax_anim 12, 0, 5, 0, 0, 0, 0,
ax_anim_terminator
sNidorinoAnims_1_3:
ax_anim 6, 0, 6, 0, 0, 0, 0,
ax_anim 12, 0, 7, 0, 0, 0, 0,
ax_anim 6, 0, 6, 0, 0, 0, 0,
ax_anim 12, 0, 8, 0, 0, 0, 0,
ax_anim_terminator
sNidorinoAnims_1_4:
ax_anim 6, 0, 9, 0, 0, 0, 0,
ax_anim 12, 0, 10, 0, 0, 0, 0,
ax_anim 6, 0, 9, 0, 0, 0, 0,
ax_anim 12, 0, 11, 0, 0, 0, 0,
ax_anim_terminator
sNidorinoAnims_1_5:
ax_anim 6, 0, 12, 0, 0, 0, 0,
ax_anim 12, 0, 13, 0, 0, 0, 0,
ax_anim 6, 0, 12, 0, 0, 0, 0,
ax_anim 12, 0, 14, 0, 0, 0, 0,
ax_anim_terminator
sNidorinoAnims_1_6:
ax_anim 6, 0, 15, 0, 0, 0, 0,
ax_anim 12, 0, 16, 0, 0, 0, 0,
ax_anim 6, 0, 15, 0, 0, 0, 0,
ax_anim 12, 0, 17, 0, 0, 0, 0,
ax_anim_terminator
sNidorinoAnims_1_7:
ax_anim 6, 0, 18, 0, 0, 0, 0,
ax_anim 12, 0, 19, 0, 0, 0, 0,
ax_anim 6, 0, 18, 0, 0, 0, 0,
ax_anim 12, 0, 20, 0, 0, 0, 0,
ax_anim_terminator
sNidorinoAnims_1_8:
ax_anim 6, 0, 21, 0, 0, 0, 0,
ax_anim 12, 0, 22, 0, 0, 0, 0,
ax_anim 6, 0, 21, 0, 0, 0, 0,
ax_anim 12, 0, 23, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sNidorinoAnims_2_1:
ax_anim 2, 0, 24, 0, -1, 0, -1,
ax_anim 6, 0, 26, -1, -4, -1, -4,
ax_anim 1, 0, 25, -1, 0, -1, 0,
ax_anim 1, 2, 27, 0, 4, 0, 4,
ax_anim 1, 0, 27, 0, 10, 0, 10,
ax_anim 2, 0, 27, 0, 18, 0, 18,
ax_anim 2, 1, 27, 1, 18, 1, 18,
ax_anim 2, 0, 27, 0, 18, 0, 18,
ax_anim 2, 0, 27, 1, 18, 1, 18,
ax_anim 2, 0, 24, 0, 6, 0, 6,
ax_anim 2, 0, 24, 0, 3, 0, 3,
ax_anim_terminator
sNidorinoAnims_2_2:
ax_anim 2, 0, 28, -1, -1, -1, -1,
ax_anim 6, 0, 29, -5, -4, -5, -4,
ax_anim 1, 0, 30, 1, -2, 1, -2,
ax_anim 1, 2, 31, 4, 4, 4, 4,
ax_anim 1, 0, 31, 10, 10, 10, 10,
ax_anim 2, 0, 31, 18, 18, 18, 18,
ax_anim 2, 1, 31, 19, 17, 19, 17,
ax_anim 2, 0, 31, 18, 18, 18, 18,
ax_anim 2, 0, 31, 19, 17, 19, 17,
ax_anim 2, 0, 28, 8, 8, 8, 8,
ax_anim 2, 0, 28, 4, 4, 4, 4,
ax_anim_terminator
sNidorinoAnims_2_3:
ax_anim 2, 0, 32, -1, 0, -1, 0,
ax_anim 6, 0, 33, -4, 1, -4, 1,
ax_anim 1, 0, 34, 2, 0, 0, 0,
ax_anim 1, 2, 35, 4, 0, 4, 0,
ax_anim 1, 0, 35, 10, 0, 10, 0,
ax_anim 2, 0, 35, 15, 0, 15, 0,
ax_anim 2, 1, 35, 15, 1, 15, 1,
ax_anim 2, 0, 35, 15, 0, 15, 0,
ax_anim 2, 0, 35, 15, 1, 15, 1,
ax_anim 2, 0, 32, 6, 0, 6, 0,
ax_anim 2, 0, 32, 3, 0, 3, 0,
ax_anim_terminator
sNidorinoAnims_2_4:
ax_anim 2, 0, 36, -1, 1, -1, 1,
ax_anim 6, 0, 37, -2, 2, -2, 2,
ax_anim 1, 0, 38, 2, 1, 2, 1,
ax_anim 1, 2, 39, 4, -2, 4, -2,
ax_anim 1, 0, 39, 11, -14, 11, -14,
ax_anim 2, 0, 39, 15, -20, 15, -20,
ax_anim 2, 1, 39, 16, -19, 16, -19,
ax_anim 2, 0, 39, 15, -20, 15, -20,
ax_anim 2, 0, 39, 16, -19, 16, -19,
ax_anim 2, 0, 36, 6, -6, 6, -6,
ax_anim 2, 0, 36, 3, -3, 3, -3,
ax_anim_terminator
sNidorinoAnims_2_5:
ax_anim 2, 0, 40, 0, 1, 0, 1,
ax_anim 6, 0, 41, 0, 2, 0, 2,
ax_anim 1, 0, 42, -1, 0, -1, 0,
ax_anim 1, 2, 43, 0, -4, 0, -4,
ax_anim 1, 0, 43, 0, -14, 0, -14,
ax_anim 2, 0, 43, 0, -20, 0, -20,
ax_anim 2, 1, 43, -1, -20, -1, -20,
ax_anim 2, 0, 43, 0, -20, 0, -20,
ax_anim 2, 0, 43, -1, -20, -1, -20,
ax_anim 2, 0, 40, 0, -6, 0, -6,
ax_anim 2, 0, 40, 0, -3, 0, -3,
ax_anim_terminator
sNidorinoAnims_2_6:
ax_anim 2, 0, 44, 1, 1, 1, 1,
ax_anim 6, 0, 45, 2, 2, 2, 2,
ax_anim 1, 0, 46, -2, 1, -2, 1,
ax_anim 1, 2, 47, -4, -2, -4, -2,
ax_anim 1, 0, 47, -11, -14, -11, -14,
ax_anim 2, 0, 47, -15, -20, -15, -20,
ax_anim 2, 1, 47, -16, -19, -16, -19,
ax_anim 2, 0, 47, -15, -20, -15, -20,
ax_anim 2, 0, 47, -16, -19, -16, -19,
ax_anim 2, 0, 44, -6, -6, -6, -6,
ax_anim 2, 0, 44, -3, -3, -3, -3,
ax_anim_terminator
sNidorinoAnims_2_7:
ax_anim 2, 0, 48, 1, 0, 1, 0,
ax_anim 6, 0, 49, 4, 1, 4, 1,
ax_anim 1, 0, 50, -2, 0, 0, 0,
ax_anim 1, 2, 51, -4, 0, -4, 0,
ax_anim 1, 0, 51, -10, 0, -10, 0,
ax_anim 2, 0, 51, -15, 0, -15, 0,
ax_anim 2, 1, 51, -15, 1, -15, 1,
ax_anim 2, 0, 51, -15, 0, -15, 0,
ax_anim 2, 0, 51, -15, 1, -15, 1,
ax_anim 2, 0, 48, -6, 0, -6, 0,
ax_anim 2, 0, 48, -3, 0, -3, 0,
ax_anim_terminator
sNidorinoAnims_2_8:
ax_anim 2, 0, 52, 1, -1, 1, -1,
ax_anim 6, 0, 53, 5, -4, 5, -4,
ax_anim 1, 0, 54, -1, -2, -1, -2,
ax_anim 1, 2, 55, -4, 4, -4, 4,
ax_anim 1, 0, 55, -10, 10, -10, 10,
ax_anim 2, 0, 55, -18, 18, -18, 18,
ax_anim 2, 1, 55, -19, 17, -19, 17,
ax_anim 2, 0, 55, -18, 18, -18, 18,
ax_anim 2, 0, 55, -19, 17, -19, 17,
ax_anim 2, 0, 52, -8, 8, -8, 8,
ax_anim 2, 0, 52, -4, 4, -4, 4,
ax_anim_terminator
.align 2
sNidorinoAnims_3_1:
ax_anim 2, 0, 56, 0, -1, 0, -1,
ax_anim 6, 0, 58, -1, -4, -1, -4,
ax_anim 1, 0, 57, -1, 0, -1, 0,
ax_anim 1, 2, 59, 0, 4, 0, 4,
ax_anim 1, 0, 59, 0, 10, 0, 10,
ax_anim 2, 0, 59, 0, 18, 0, 18,
ax_anim 2, 1, 59, 1, 18, 1, 18,
ax_anim 2, 0, 59, 0, 18, 0, 18,
ax_anim 2, 0, 59, 1, 18, 1, 18,
ax_anim 2, 0, 56, 0, 6, 0, 6,
ax_anim 2, 0, 56, 0, 3, 0, 3,
ax_anim_terminator
sNidorinoAnims_3_2:
ax_anim 2, 0, 60, -1, -1, -1, -1,
ax_anim 6, 0, 61, -5, -4, -5, -4,
ax_anim 1, 0, 62, 1, -2, 1, -2,
ax_anim 1, 2, 63, 4, 4, 4, 4,
ax_anim 1, 0, 63, 10, 10, 10, 10,
ax_anim 2, 0, 63, 18, 18, 18, 18,
ax_anim 2, 1, 63, 19, 17, 19, 17,
ax_anim 2, 0, 63, 18, 18, 18, 18,
ax_anim 2, 0, 63, 19, 17, 19, 17,
ax_anim 2, 0, 60, 8, 8, 8, 8,
ax_anim 2, 0, 60, 4, 4, 4, 4,
ax_anim_terminator
sNidorinoAnims_3_3:
ax_anim 2, 0, 64, -1, 0, -1, 0,
ax_anim 6, 0, 65, -4, 1, -4, 1,
ax_anim 1, 0, 66, 2, 0, 0, 0,
ax_anim 1, 2, 67, 4, 0, 4, 0,
ax_anim 1, 0, 67, 10, 0, 10, 0,
ax_anim 2, 0, 67, 15, 0, 15, 0,
ax_anim 2, 1, 67, 15, 1, 15, 1,
ax_anim 2, 0, 67, 15, 0, 15, 0,
ax_anim 2, 0, 67, 15, 1, 15, 1,
ax_anim 2, 0, 64, 6, 0, 6, 0,
ax_anim 2, 0, 64, 3, 0, 3, 0,
ax_anim_terminator
sNidorinoAnims_3_4:
ax_anim 2, 0, 68, -1, 1, -1, 1,
ax_anim 6, 0, 69, -2, 2, -2, 2,
ax_anim 1, 0, 70, 2, 1, 2, 1,
ax_anim 1, 2, 71, 4, -2, 4, -2,
ax_anim 1, 0, 71, 11, -14, 11, -14,
ax_anim 2, 0, 71, 15, -20, 15, -20,
ax_anim 2, 1, 71, 16, -19, 16, -19,
ax_anim 2, 0, 71, 15, -20, 15, -20,
ax_anim 2, 0, 71, 16, -19, 16, -19,
ax_anim 2, 0, 68, 6, -6, 6, -6,
ax_anim 2, 0, 68, 3, -3, 3, -3,
ax_anim_terminator
sNidorinoAnims_3_5:
ax_anim 2, 0, 72, 0, 1, 0, 1,
ax_anim 6, 0, 73, 0, 2, 0, 2,
ax_anim 1, 0, 74, -1, 0, -1, 0,
ax_anim 1, 2, 75, 0, -4, 0, -4,
ax_anim 1, 0, 75, 0, -14, 0, -14,
ax_anim 2, 0, 75, 0, -20, 0, -20,
ax_anim 2, 1, 75, -1, -20, -1, -20,
ax_anim 2, 0, 75, 0, -20, 0, -20,
ax_anim 2, 0, 75, -1, -20, -1, -20,
ax_anim 2, 0, 72, 0, -6, 0, -6,
ax_anim 2, 0, 72, 0, -3, 0, -3,
ax_anim_terminator
sNidorinoAnims_3_6:
ax_anim 2, 0, 76, 1, 1, 1, 1,
ax_anim 6, 0, 77, 2, 2, 2, 2,
ax_anim 1, 0, 78, -2, 1, -2, 1,
ax_anim 1, 2, 79, -4, -2, -4, -2,
ax_anim 1, 0, 79, -11, -14, -11, -14,
ax_anim 2, 0, 79, -15, -20, -15, -20,
ax_anim 2, 1, 79, -16, -19, -16, -19,
ax_anim 2, 0, 79, -15, -20, -15, -20,
ax_anim 2, 0, 79, -16, -19, -16, -19,
ax_anim 2, 0, 76, -6, -6, -6, -6,
ax_anim 2, 0, 76, -3, -3, -3, -3,
ax_anim_terminator
sNidorinoAnims_3_7:
ax_anim 2, 0, 80, 1, 0, 1, 0,
ax_anim 6, 0, 81, 4, 1, 4, 1,
ax_anim 1, 0, 82, -2, 0, 0, 0,
ax_anim 1, 2, 83, -4, 0, -4, 0,
ax_anim 1, 0, 83, -10, 0, -10, 0,
ax_anim 2, 0, 83, -15, 0, -15, 0,
ax_anim 2, 1, 83, -15, 1, -15, 1,
ax_anim 2, 0, 83, -15, 0, -15, 0,
ax_anim 2, 0, 83, -15, 1, -15, 1,
ax_anim 2, 0, 80, -6, 0, -6, 0,
ax_anim 2, 0, 80, -3, 0, -3, 0,
ax_anim_terminator
sNidorinoAnims_3_8:
ax_anim 2, 0, 84, 1, -1, 1, -1,
ax_anim 6, 0, 85, 5, -4, 5, -4,
ax_anim 1, 0, 86, -1, -2, -1, -2,
ax_anim 1, 2, 87, -4, 4, -4, 4,
ax_anim 1, 0, 87, -10, 10, -10, 10,
ax_anim 2, 0, 87, -18, 18, -18, 18,
ax_anim 2, 1, 87, -19, 17, -19, 17,
ax_anim 2, 0, 87, -18, 18, -18, 18,
ax_anim 2, 0, 87, -19, 17, -19, 17,
ax_anim 2, 0, 84, -8, 8, -8, 8,
ax_anim 2, 0, 84, -4, 4, -4, 4,
ax_anim_terminator
.align 2
sNidorinoAnims_4_1:
ax_anim 2, 0, 89, 0, -2, 0, -2,
ax_anim 2, 0, 89, 0, -3, 0, -3,
ax_anim 6, 2, 89, 0, -4, 0, -4,
ax_anim 1, 0, 90, 0, 0, 0, 0,
ax_anim 2, 0, 90, 0, 5, 0, 5,
ax_anim 2, 1, 90, 1, 5, 1, 5,
ax_anim 2, 0, 90, 0, 5, 0, 5,
ax_anim 2, 0, 90, 1, 5, 1, 5,
ax_anim 2, 0, 90, 0, 5, 0, 5,
ax_anim 2, 0, 90, 1, 5, 1, 5,
ax_anim 2, 0, 88, 0, 2, 0, 2,
ax_anim_terminator
sNidorinoAnims_4_2:
ax_anim 2, 0, 92, -2, -2, -2, -2,
ax_anim 2, 0, 92, -3, -3, -3, -3,
ax_anim 6, 2, 92, -4, -4, -4, -4,
ax_anim 1, 0, 93, 0, 0, 0, 0,
ax_anim 2, 0, 93, 5, 5, 5, 5,
ax_anim 2, 1, 93, 6, 4, 6, 4,
ax_anim 2, 0, 93, 5, 5, 5, 5,
ax_anim 2, 0, 93, 6, 4, 6, 4,
ax_anim 2, 0, 93, 5, 5, 5, 5,
ax_anim 2, 0, 93, 6, 4, 6, 4,
ax_anim 2, 0, 91, 2, 2, 2, 2,
ax_anim_terminator
sNidorinoAnims_4_3:
ax_anim 2, 0, 95, -2, 0, -2, 0,
ax_anim 2, 0, 95, -3, 0, -3, 0,
ax_anim 6, 2, 95, -4, 0, -4, 0,
ax_anim 1, 0, 96, 0, 0, 0, 0,
ax_anim 2, 0, 96, 5, 0, 5, 0,
ax_anim 2, 1, 96, 5, -1, 5, -1,
ax_anim 2, 0, 96, 5, 0, 5, 0,
ax_anim 2, 0, 96, 5, -1, 5, -1,
ax_anim 2, 0, 96, 5, 0, 5, 0,
ax_anim 2, 0, 96, 5, -1, 5, -1,
ax_anim 2, 0, 94, 2, 0, 2, 0,
ax_anim_terminator
sNidorinoAnims_4_4:
ax_anim 2, 0, 98, -2, 2, -2, 2,
ax_anim 2, 0, 98, -3, 3, -3, 3,
ax_anim 6, 2, 98, -4, 4, -4, 4,
ax_anim 1, 0, 99, 0, 0, 0, 0,
ax_anim 2, 0, 99, 5, -5, 5, -5,
ax_anim 2, 1, 99, 6, -4, 6, -4,
ax_anim 2, 0, 99, 5, -5, 5, -5,
ax_anim 2, 0, 99, 6, -4, 6, -4,
ax_anim 2, 0, 99, 5, -5, 5, -5,
ax_anim 2, 0, 99, 6, -4, 6, -4,
ax_anim 2, 0, 97, 2, -2, 2, -2,
ax_anim_terminator
sNidorinoAnims_4_5:
ax_anim 2, 0, 101, 0, 2, 0, 2,
ax_anim 2, 0, 101, 0, 3, 0, 3,
ax_anim 6, 2, 101, 0, 4, 0, 4,
ax_anim 1, 0, 102, 0, 0, 0, 0,
ax_anim 2, 0, 102, 0, -5, 0, -5,
ax_anim 2, 1, 102, 1, -5, 1, -5,
ax_anim 2, 0, 102, 0, -5, 0, -5,
ax_anim 2, 0, 102, 1, -5, 1, -5,
ax_anim 2, 0, 102, 0, -5, 0, -5,
ax_anim 2, 0, 102, 1, -5, 1, -5,
ax_anim 2, 0, 100, 0, -2, 0, -2,
ax_anim_terminator
sNidorinoAnims_4_6:
ax_anim 2, 0, 104, 2, 2, 2, 2,
ax_anim 2, 0, 104, 3, 3, 3, 3,
ax_anim 6, 2, 104, 4, 4, 4, 4,
ax_anim 1, 0, 105, 0, 0, 0, 0,
ax_anim 2, 0, 105, -5, -5, -5, -5,
ax_anim 2, 1, 105, -6, -4, -6, -4,
ax_anim 2, 0, 105, -5, -5, -5, -5,
ax_anim 2, 0, 105, -6, -4, -6, -4,
ax_anim 2, 0, 105, -5, -5, -5, -5,
ax_anim 2, 0, 105, -6, -4, -6, -4,
ax_anim 2, 0, 103, -2, -2, -2, -2,
ax_anim_terminator
sNidorinoAnims_4_7:
ax_anim 2, 0, 107, 2, 0, 2, 0,
ax_anim 2, 0, 107, 3, 0, 3, 0,
ax_anim 6, 2, 107, 4, 0, 4, 0,
ax_anim 1, 0, 108, 0, 0, 0, 0,
ax_anim 2, 0, 108, -5, 0, -5, 0,
ax_anim 2, 1, 108, -5, -1, -5, -1,
ax_anim 2, 0, 108, -5, 0, -5, 0,
ax_anim 2, 0, 108, -5, -1, -5, -1,
ax_anim 2, 0, 108, -5, 0, -5, 0,
ax_anim 2, 0, 108, -5, -1, -5, -1,
ax_anim 2, 0, 106, -2, 0, -2, 0,
ax_anim_terminator
sNidorinoAnims_4_8:
ax_anim 2, 0, 110, 2, -2, 2, -2,
ax_anim 2, 0, 110, 3, -3, 3, -3,
ax_anim 6, 2, 110, 4, -4, 4, -4,
ax_anim 1, 0, 111, 0, 0, 0, 0,
ax_anim 2, 0, 111, -5, 5, -5, 5,
ax_anim 2, 1, 111, -6, 4, -6, 4,
ax_anim 2, 0, 111, -5, 5, -5, 5,
ax_anim 2, 0, 111, -6, 4, -6, 4,
ax_anim 2, 0, 111, -5, 5, -5, 5,
ax_anim 2, 0, 111, -6, 4, -6, 4,
ax_anim 2, 0, 109, -2, 2, -2, 2,
ax_anim_terminator
.align 2
sNidorinoAnims_5_1:
ax_anim 1, 0, 112, 0, -2, 0, 0,
ax_anim 1, 0, 112, 0, -4, 0, 0,
ax_anim 3, 0, 112, 0, -5, 0, 0,
ax_anim 1, 0, 112, 0, -4, 0, 0,
ax_anim 1, 0, 112, 0, -2, 0, 0,
ax_anim 4, 0, 112, 0, 0, 0, 0,
ax_anim 3, 0, 113, 0, 0, 0, 0,
ax_anim 3, 0, 114, 0, 0, 0, 0,
ax_anim 2, 2, 113, 0, 0, 0, 0,
ax_anim 2, 0, 114, 0, 0, 0, 0,
ax_anim 3, 0, 113, 0, 0, 0, 0,
ax_anim 3, 0, 114, 0, 0, 0, 0,
ax_anim_terminator
sNidorinoAnims_5_2:
ax_anim 1, 0, 115, 0, -2, 0, 0,
ax_anim 1, 0, 115, 0, -4, 0, 0,
ax_anim 3, 0, 115, 0, -5, 0, 0,
ax_anim 1, 0, 115, 0, -4, 0, 0,
ax_anim 1, 0, 115, 0, -2, 0, 0,
ax_anim 4, 0, 115, 0, 0, 0, 0,
ax_anim 3, 0, 116, 0, 0, 0, 0,
ax_anim 3, 0, 117, 0, 0, 0, 0,
ax_anim 2, 2, 116, 0, 0, 0, 0,
ax_anim 2, 0, 117, 0, 0, 0, 0,
ax_anim 3, 0, 116, 0, 0, 0, 0,
ax_anim 3, 0, 117, 0, 0, 0, 0,
ax_anim_terminator
sNidorinoAnims_5_3:
ax_anim 1, 0, 118, 0, -2, 0, 0,
ax_anim 1, 0, 118, 0, -4, 0, 0,
ax_anim 3, 0, 118, 0, -5, 0, 0,
ax_anim 1, 0, 118, 0, -4, 0, 0,
ax_anim 1, 0, 118, 0, -2, 0, 0,
ax_anim 4, 0, 118, 0, 0, 0, 0,
ax_anim 3, 0, 119, 0, 0, 0, 0,
ax_anim 3, 0, 120, 0, 0, 0, 0,
ax_anim 2, 2, 119, 0, 0, 0, 0,
ax_anim 2, 0, 120, 0, 0, 0, 0,
ax_anim 3, 0, 119, 0, 0, 0, 0,
ax_anim 3, 0, 120, 0, 0, 0, 0,
ax_anim_terminator
sNidorinoAnims_5_4:
ax_anim 1, 0, 121, 0, -2, 0, 0,
ax_anim 1, 0, 121, 0, -4, 0, 0,
ax_anim 3, 0, 121, 0, -5, 0, 0,
ax_anim 1, 0, 121, 0, -4, 0, 0,
ax_anim 1, 0, 121, 0, -2, 0, 0,
ax_anim 4, 0, 121, 0, 0, 0, 0,
ax_anim 3, 0, 122, 0, 0, 0, 0,
ax_anim 3, 0, 123, 0, 0, 0, 0,
ax_anim 2, 2, 122, 0, 0, 0, 0,
ax_anim 2, 0, 123, 0, 0, 0, 0,
ax_anim 3, 0, 122, 0, 0, 0, 0,
ax_anim 3, 0, 123, 0, 0, 0, 0,
ax_anim_terminator
sNidorinoAnims_5_5:
ax_anim 1, 0, 124, 0, -2, 0, 0,
ax_anim 1, 0, 124, 0, -4, 0, 0,
ax_anim 3, 0, 124, 0, -5, 0, 0,
ax_anim 1, 0, 124, 0, -4, 0, 0,
ax_anim 1, 0, 124, 0, -2, 0, 0,
ax_anim 4, 0, 124, 0, 0, 0, 0,
ax_anim 3, 0, 125, 0, 0, 0, 0,
ax_anim 3, 0, 126, 0, 0, 0, 0,
ax_anim 2, 2, 125, 0, 0, 0, 0,
ax_anim 2, 0, 126, 0, 0, 0, 0,
ax_anim 3, 0, 125, 0, 0, 0, 0,
ax_anim 3, 0, 126, 0, 0, 0, 0,
ax_anim_terminator
sNidorinoAnims_5_6:
ax_anim 1, 0, 127, 0, -2, 0, 0,
ax_anim 1, 0, 127, 0, -4, 0, 0,
ax_anim 3, 0, 127, 0, -5, 0, 0,
ax_anim 1, 0, 127, 0, -4, 0, 0,
ax_anim 1, 0, 127, 0, -2, 0, 0,
ax_anim 4, 0, 127, 0, 0, 0, 0,
ax_anim 3, 0, 128, 0, 0, 0, 0,
ax_anim 3, 0, 129, 0, 0, 0, 0,
ax_anim 2, 2, 128, 0, 0, 0, 0,
ax_anim 2, 0, 129, 0, 0, 0, 0,
ax_anim 3, 0, 128, 0, 0, 0, 0,
ax_anim 3, 0, 129, 0, 0, 0, 0,
ax_anim_terminator
sNidorinoAnims_5_7:
ax_anim 1, 0, 130, 0, -2, 0, 0,
ax_anim 1, 0, 130, 0, -4, 0, 0,
ax_anim 3, 0, 130, 0, -5, 0, 0,
ax_anim 1, 0, 130, 0, -4, 0, 0,
ax_anim 1, 0, 130, 0, -2, 0, 0,
ax_anim 4, 0, 130, 0, 0, 0, 0,
ax_anim 3, 0, 131, 0, 0, 0, 0,
ax_anim 3, 0, 132, 0, 0, 0, 0,
ax_anim 2, 2, 131, 0, 0, 0, 0,
ax_anim 2, 0, 132, 0, 0, 0, 0,
ax_anim 3, 0, 131, 0, 0, 0, 0,
ax_anim 3, 0, 132, 0, 0, 0, 0,
ax_anim_terminator
sNidorinoAnims_5_8:
ax_anim 1, 0, 133, 0, -2, 0, 0,
ax_anim 1, 0, 133, 0, -4, 0, 0,
ax_anim 3, 0, 133, 0, -5, 0, 0,
ax_anim 1, 0, 133, 0, -4, 0, 0,
ax_anim 1, 0, 133, 0, -2, 0, 0,
ax_anim 4, 0, 133, 0, 0, 0, 0,
ax_anim 3, 0, 134, 0, 0, 0, 0,
ax_anim 3, 0, 135, 0, 0, 0, 0,
ax_anim 2, 2, 134, 0, 0, 0, 0,
ax_anim 2, 0, 135, 0, 0, 0, 0,
ax_anim 3, 0, 134, 0, 0, 0, 0,
ax_anim 3, 0, 135, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sNidorinoAnims_6_1:
ax_anim 30, 0, 136, 0, 0, 0, 0,
ax_anim 35, 0, 137, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sNidorinoAnims_7_1:
ax_anim 2, 0, 138, 0, -2, 0, -2,
ax_anim 8, 0, 138, 0, -3, 0, -3,
ax_anim_terminator
sNidorinoAnims_7_2:
ax_anim 2, 0, 139, -2, -2, -2, -2,
ax_anim 8, 0, 139, -3, -3, -3, -3,
ax_anim_terminator
sNidorinoAnims_7_3:
ax_anim 2, 0, 140, -2, 0, -2, 0,
ax_anim 8, 0, 140, -3, 0, -3, 0,
ax_anim_terminator
sNidorinoAnims_7_4:
ax_anim 2, 0, 141, -2, 2, -2, 2,
ax_anim 8, 0, 141, -3, 3, -3, 3,
ax_anim_terminator
sNidorinoAnims_7_5:
ax_anim 2, 0, 142, 0, 2, 0, 2,
ax_anim 8, 0, 142, 0, 3, 0, 3,
ax_anim_terminator
sNidorinoAnims_7_6:
ax_anim 2, 0, 143, 2, 2, 2, 2,
ax_anim 8, 0, 143, 3, 3, 3, 3,
ax_anim_terminator
sNidorinoAnims_7_7:
ax_anim 2, 0, 144, 2, 0, 2, 0,
ax_anim 8, 0, 144, 3, 0, 3, 0,
ax_anim_terminator
sNidorinoAnims_7_8:
ax_anim 2, 0, 145, 2, -2, 2, -2,
ax_anim 8, 0, 145, 3, -3, 3, -3,
ax_anim_terminator
.align 2
sNidorinoAnims_8_1:
ax_anim 40, 0, 146, 0, 0, 0, 0,
ax_anim 10, 0, 147, 1, -3, 1, -3,
ax_anim 2, 0, 147, 0, -3, 0, -3,
ax_anim 2, 0, 147, 1, -3, 1, -3,
ax_anim 2, 0, 147, 0, -3, 0, -3,
ax_anim 2, 0, 147, 1, -3, 1, -3,
ax_anim 2, 0, 147, 0, -3, 0, -3,
ax_anim 2, 0, 147, 1, -3, 1, -3,
ax_anim 2, 0, 147, 0, -3, 0, -3,
ax_anim 6, 0, 147, 1, -3, 1, -3,
ax_anim_terminator
sNidorinoAnims_8_2:
ax_anim 40, 0, 149, 0, 0, 0, 0,
ax_anim 10, 0, 150, -4, -2, -4, -2,
ax_anim 2, 0, 150, -5, -2, -5, -2,
ax_anim 2, 0, 150, -4, -2, -4, -2,
ax_anim 2, 0, 150, -5, -2, -5, -2,
ax_anim 2, 0, 150, -4, -2, -4, -2,
ax_anim 2, 0, 150, -5, -2, -5, -2,
ax_anim 2, 0, 150, -4, -2, -4, -2,
ax_anim 2, 0, 150, -5, -2, -5, -2,
ax_anim 6, 0, 150, -4, -2, -4, -2,
ax_anim_terminator
sNidorinoAnims_8_3:
ax_anim 40, 0, 152, 0, 0, 0, 0,
ax_anim 10, 0, 153, -3, 1, -3, 1,
ax_anim 2, 0, 153, -4, 1, -4, 1,
ax_anim 2, 0, 153, -3, 1, -3, 1,
ax_anim 2, 0, 153, -4, 1, -4, 1,
ax_anim 2, 0, 153, -3, 1, -3, 1,
ax_anim 2, 0, 153, -4, 1, -4, 1,
ax_anim 2, 0, 153, -3, 1, -3, 1,
ax_anim 2, 0, 153, -4, 1, -4, 1,
ax_anim 6, 0, 153, -3, 1, -3, 1,
ax_anim_terminator
sNidorinoAnims_8_4:
ax_anim 40, 0, 155, 0, 0, 0, 0,
ax_anim 10, 0, 156, -1, 0, -1, 0,
ax_anim 2, 0, 156, -2, 0, -2, 0,
ax_anim 2, 0, 156, -1, 0, -1, 0,
ax_anim 2, 0, 156, -2, 0, -2, 0,
ax_anim 2, 0, 156, -1, 0, -1, 0,
ax_anim 2, 0, 156, -2, 0, -2, 0,
ax_anim 2, 0, 156, -1, 0, -1, 0,
ax_anim 2, 0, 156, -2, 0, -2, 0,
ax_anim 6, 0, 156, -1, 0, -1, 0,
ax_anim_terminator
sNidorinoAnims_8_5:
ax_anim 40, 0, 158, 0, 0, 0, 0,
ax_anim 10, 0, 159, 0, 1, 0, 1,
ax_anim 2, 0, 159, -1, 1, -1, 1,
ax_anim 2, 0, 159, 0, 1, 0, 1,
ax_anim 2, 0, 159, -1, 1, -1, 1,
ax_anim 2, 0, 159, 0, 1, 0, 1,
ax_anim 2, 0, 159, -1, 1, -1, 1,
ax_anim 2, 0, 159, 0, 1, 0, 1,
ax_anim 2, 0, 159, -1, 1, -1, 1,
ax_anim 6, 0, 159, 0, 1, 0, 1,
ax_anim_terminator
sNidorinoAnims_8_6:
ax_anim 40, 0, 161, 0, 0, 0, 0,
ax_anim 10, 0, 162, 1, 0, 1, 0,
ax_anim 2, 0, 162, 0, 0, 0, 0,
ax_anim 2, 0, 162, 1, 0, 1, 0,
ax_anim 2, 0, 162, 0, 0, 0, 0,
ax_anim 2, 0, 162, 1, 0, 1, 0,
ax_anim 2, 0, 162, 0, 0, 0, 0,
ax_anim 2, 0, 162, 1, 0, 1, 0,
ax_anim 2, 0, 162, 0, 0, 0, 0,
ax_anim 6, 0, 162, 1, 0, 1, 0,
ax_anim_terminator
sNidorinoAnims_8_7:
ax_anim 40, 0, 164, 0, 0, 0, 0,
ax_anim 10, 0, 165, 3, 1, 3, 1,
ax_anim 2, 0, 165, 2, 1, 2, 1,
ax_anim 2, 0, 165, 3, 1, 3, 1,
ax_anim 2, 0, 165, 2, 1, 2, 1,
ax_anim 2, 0, 165, 3, 1, 3, 1,
ax_anim 2, 0, 165, 2, 1, 2, 1,
ax_anim 2, 0, 165, 3, 1, 3, 1,
ax_anim 2, 0, 165, 2, 1, 2, 1,
ax_anim 6, 0, 165, 3, 1, 3, 1,
ax_anim_terminator
sNidorinoAnims_8_8:
ax_anim 40, 0, 167, 0, 0, 0, 0,
ax_anim 10, 0, 168, 4, -2, 4, -2,
ax_anim 2, 0, 168, 3, -2, 3, -2,
ax_anim 2, 0, 168, 4, -2, 4, -2,
ax_anim 2, 0, 168, 3, -2, 3, -2,
ax_anim 2, 0, 168, 4, -2, 4, -2,
ax_anim 2, 0, 168, 3, -2, 3, -2,
ax_anim 2, 0, 168, 4, -2, 4, -2,
ax_anim 2, 0, 168, 3, -2, 3, -2,
ax_anim 6, 0, 168, 4, -2, 4, -2,
ax_anim_terminator
.align 2
sNidorinoAnims_9_1:
ax_anim 2, 0, 170, 0, 0, 0, 0,
ax_anim 1, 0, 171, 6, 3, 6, 3,
ax_anim 2, 0, 172, 8, 9, 8, 9,
ax_anim 2, 0, 173, 7, 15, 7, 15,
ax_anim 3, 0, 174, 0, 18, 0, 18,
ax_anim 2, 3, 175, -7, 15, -7, 15,
ax_anim 2, 0, 176, -8, 9, -8, 9,
ax_anim 1, 0, 177, -6, 3, -6, 3,
ax_anim 1, 0, 170, 0, 0, 0, 0,
ax_anim_terminator
sNidorinoAnims_9_2:
ax_anim 2, 0, 177, 0, 0, 0, 0,
ax_anim 1, 0, 170, 8, 0, 8, 0,
ax_anim 2, 0, 171, 17, 3, 18, 3,
ax_anim 2, 0, 172, 19, 10, 21, 10,
ax_anim 3, 0, 173, 17, 19, 19, 20,
ax_anim 2, 3, 174, 11, 19, 11, 19,
ax_anim 2, 0, 175, 3, 15, 3, 15,
ax_anim 1, 0, 176, 0, 7, 0, 7,
ax_anim 1, 0, 177, 0, 0, 0, 0,
ax_anim_terminator
sNidorinoAnims_9_3:
ax_anim 2, 0, 176, 0, 0, 0, 0,
ax_anim 1, 0, 177, 3, -5, 3, -5,
ax_anim 2, 0, 170, 11, -6, 11, -6,
ax_anim 2, 0, 171, 16, -5, 16, -5,
ax_anim 3, 0, 172, 18, -2, 18, -2,
ax_anim 2, 3, 173, 16, 4, 16, 4,
ax_anim 2, 0, 174, 12, 5, 12, 5,
ax_anim 1, 0, 175, 4, 5, 4, 5,
ax_anim 1, 0, 176, 0, 0, 0, 0,
ax_anim_terminator
sNidorinoAnims_9_4:
ax_anim 2, 0, 175, 0, 0, 0, 0,
ax_anim 1, 0, 176, -1, -8, -1, -8,
ax_anim 2, 0, 177, 4, -16, 4, -16,
ax_anim 2, 0, 170, 12, -22, 12, -22,
ax_anim 3, 0, 171, 18, -22, 18, -22,
ax_anim 2, 3, 172, 20, -15, 20, -15,
ax_anim 2, 0, 173, 17, -4, 17, -4,
ax_anim 1, 0, 174, 7, -1, 7, -1,
ax_anim 1, 0, 175, 0, 0, 0, 0,
ax_anim_terminator
sNidorinoAnims_9_5:
ax_anim 2, 0, 174, 0, 0, 0, 0,
ax_anim 1, 0, 175, -8, -4, -8, -4,
ax_anim 2, 0, 176, -9, -12, -9, -12,
ax_anim 2, 0, 177, -7, -18, -7, -18,
ax_anim 3, 0, 170, 0, -22, 0, -22,
ax_anim 2, 3, 171, 7, -18, 7, -18,
ax_anim 2, 0, 172, 9, -10, 9, -10,
ax_anim 1, 0, 173, 8, -4, 8, -4,
ax_anim 1, 0, 174, 0, 0, 0, 0,
ax_anim_terminator
sNidorinoAnims_9_6:
ax_anim 2, 0, 173, 0, 0, 0, 0,
ax_anim 1, 0, 172, 1, -6, 1, -6,
ax_anim 2, 0, 171, -4, -16, -4, -16,
ax_anim 2, 0, 170, -12, -22, -12, -22,
ax_anim 3, 0, 177, -18, -22, -18, -22,
ax_anim 2, 3, 176, -20, -15, -20, -15,
ax_anim 2, 0, 175, -17, -4, -17, -4,
ax_anim 1, 0, 174, -7, -1, -7, -1,
ax_anim 1, 0, 173, 0, 0, 0, 0,
ax_anim_terminator
sNidorinoAnims_9_7:
ax_anim 2, 0, 172, 0, 0, 0, 0,
ax_anim 1, 0, 171, -3, -5, -3, -5,
ax_anim 2, 0, 170, -11, -6, -11, -6,
ax_anim 2, 0, 177, -16, -5, -16, -5,
ax_anim 3, 0, 176, -18, -2, -18, -2,
ax_anim 2, 3, 175, -16, 4, -16, 4,
ax_anim 2, 0, 174, -12, 5, -12, 5,
ax_anim 1, 0, 173, -4, 5, -4, 5,
ax_anim 1, 0, 172, 0, 0, 0, 0,
ax_anim_terminator
sNidorinoAnims_9_8:
ax_anim 2, 0, 171, 0, 0, 0, 0,
ax_anim 1, 0, 170, -8, 0, -8, 0,
ax_anim 2, 0, 177, -17, 3, -17, 3,
ax_anim 2, 0, 176, -19, 10, -19, 10,
ax_anim 3, 0, 175, -17, 19, -17, 19,
ax_anim 2, 3, 174, -11, 19, -11, 19,
ax_anim 2, 0, 173, -3, 15, -3, 15,
ax_anim 1, 0, 172, 0, 7, 0, 7,
ax_anim 1, 0, 171, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sNidorinoAnims_10_1:
ax_anim 2, 0, 178, 0, 0, 0, 0,
ax_anim 2, 0, 178, 6, 0, 6, 0,
ax_anim 2, 0, 178, -6, 0, -6, 0,
ax_anim 2, 0, 178, 10, 0, 10, 0,
ax_anim 2, 0, 178, -10, 0, -10, 0,
ax_anim 2, 0, 178, 12, 0, 12, 0,
ax_anim 3, 0, 178, -12, 0, -12, 0,
ax_anim 3, 0, 178, 13, 0, 13, 0,
ax_anim 3, 0, 178, -13, 0, -13, 0,
ax_anim 2, 0, 178, 12, 0, 12, 0,
ax_anim 3, 0, 178, -12, 0, -12, 0,
ax_anim 2, 0, 178, 10, 0, 10, 0,
ax_anim 2, 0, 178, -10, 0, -10, 0,
ax_anim 2, 0, 178, 6, 0, 6, 0,
ax_anim 2, 0, 178, -6, 0, -6, 0,
ax_anim 2, 0, 178, 0, 0, 0, 0,
ax_anim_terminator
sNidorinoAnims_10_2:
ax_anim 2, 0, 185, 0, 0, 0, 0,
ax_anim 2, 0, 185, 6, -6, 6, -6,
ax_anim 2, 0, 185, -6, 6, -6, 6,
ax_anim 2, 0, 185, 10, -10, 10, -10,
ax_anim 2, 0, 185, -10, 10, -10, 10,
ax_anim 2, 0, 185, 12, -12, 12, -12,
ax_anim 3, 0, 185, -12, 12, -12, 12,
ax_anim 3, 0, 185, 13, -13, 13, -13,
ax_anim 3, 0, 185, -13, 13, -13, 13,
ax_anim 2, 0, 185, 12, -12, 12, -12,
ax_anim 3, 0, 185, -12, 12, -12, 12,
ax_anim 2, 0, 185, 10, -10, 10, -10,
ax_anim 2, 0, 185, -10, 10, -10, 10,
ax_anim 2, 0, 185, 6, -6, 6, -6,
ax_anim 2, 0, 185, -6, 6, -6, 6,
ax_anim 2, 0, 185, 0, 0, 0, 0,
ax_anim_terminator
sNidorinoAnims_10_3:
ax_anim 2, 0, 184, 0, 0, 0, 0,
ax_anim 2, 0, 184, 0, -6, 0, -6,
ax_anim 2, 0, 184, 0, 6, 0, 6,
ax_anim 2, 0, 184, 0, -10, 0, -10,
ax_anim 2, 0, 184, 0, 10, 0, 10,
ax_anim 2, 0, 184, 0, -12, 0, -12,
ax_anim 3, 0, 184, 0, 12, 0, 12,
ax_anim 3, 0, 184, 0, -13, 0, -13,
ax_anim 3, 0, 184, 0, 13, 0, 13,
ax_anim 2, 0, 184, 0, -12, 0, -12,
ax_anim 3, 0, 184, 0, 12, 0, 12,
ax_anim 2, 0, 184, 0, -10, 0, -10,
ax_anim 2, 0, 184, 0, 10, 0, 10,
ax_anim 2, 0, 184, 0, -6, 0, -6,
ax_anim 2, 0, 184, 0, 6, 0, 6,
ax_anim 2, 0, 184, 0, 0, 0, 0,
ax_anim_terminator
sNidorinoAnims_10_4:
ax_anim 2, 0, 183, 0, 0, 0, 0,
ax_anim 2, 0, 183, -6, -6, -6, -6,
ax_anim 2, 0, 183, 6, 6, 6, 6,
ax_anim 2, 0, 183, -10, -10, -10, -10,
ax_anim 2, 0, 183, 10, 10, 10, 10,
ax_anim 2, 0, 183, -12, -12, -12, -12,
ax_anim 3, 0, 183, 12, 12, 12, 12,
ax_anim 3, 0, 183, -13, -13, -13, -13,
ax_anim 3, 0, 183, 13, 13, 13, 13,
ax_anim 2, 0, 183, -12, -12, -12, -12,
ax_anim 3, 0, 183, 12, 12, 12, 12,
ax_anim 2, 0, 183, -10, -10, -10, -10,
ax_anim 2, 0, 183, 10, 10, 10, 10,
ax_anim 2, 0, 183, -6, -6, -6, -6,
ax_anim 2, 0, 183, 6, 6, 6, 6,
ax_anim 2, 0, 183, 0, 0, 0, 0,
ax_anim_terminator
sNidorinoAnims_10_5:
ax_anim 2, 0, 182, 0, 0, 0, 0,
ax_anim 2, 0, 182, 6, 0, 6, 0,
ax_anim 2, 0, 182, -6, 0, -6, 0,
ax_anim 2, 0, 182, 10, 0, 10, 0,
ax_anim 2, 0, 182, -10, 0, -10, 0,
ax_anim 2, 0, 182, 12, 0, 12, 0,
ax_anim 3, 0, 182, -12, 0, -12, 0,
ax_anim 3, 0, 182, 13, 0, 13, 0,
ax_anim 3, 0, 182, -13, 0, -13, 0,
ax_anim 2, 0, 182, 12, 0, 12, 0,
ax_anim 3, 0, 182, -12, 0, -12, 0,
ax_anim 2, 0, 182, 10, 0, 10, 0,
ax_anim 2, 0, 182, -10, 0, -10, 0,
ax_anim 2, 0, 182, 6, 0, 6, 0,
ax_anim 2, 0, 182, -6, 0, -6, 0,
ax_anim 2, 0, 182, 0, 0, 0, 0,
ax_anim_terminator
sNidorinoAnims_10_6:
ax_anim 2, 0, 181, 0, 0, 0, 0,
ax_anim 2, 0, 181, 6, -6, 6, -6,
ax_anim 2, 0, 181, -6, 6, -6, 6,
ax_anim 2, 0, 181, 10, -10, 10, -10,
ax_anim 2, 0, 181, -10, 10, -10, 10,
ax_anim 2, 0, 181, 12, -12, 12, -12,
ax_anim 3, 0, 181, -12, 12, -12, 12,
ax_anim 3, 0, 181, 13, -13, 13, -13,
ax_anim 3, 0, 181, -13, 13, -13, 13,
ax_anim 2, 0, 181, 12, -12, 12, -12,
ax_anim 3, 0, 181, -12, 12, -12, 12,
ax_anim 2, 0, 181, 10, -10, 10, -10,
ax_anim 2, 0, 181, -10, 10, -10, 10,
ax_anim 2, 0, 181, 6, -6, 6, -6,
ax_anim 2, 0, 181, -6, 6, -6, 6,
ax_anim 2, 0, 181, 0, 0, 0, 0,
ax_anim_terminator
sNidorinoAnims_10_7:
ax_anim 2, 0, 180, 0, 0, 0, 0,
ax_anim 2, 0, 180, 0, -6, 0, -6,
ax_anim 2, 0, 180, 0, 6, 0, 6,
ax_anim 2, 0, 180, 0, -10, 0, -10,
ax_anim 2, 0, 180, 0, 10, 0, 10,
ax_anim 2, 0, 180, 0, -12, 0, -12,
ax_anim 3, 0, 180, 0, 12, 0, 12,
ax_anim 3, 0, 180, 0, -13, 0, -13,
ax_anim 3, 0, 180, 0, 13, 0, 13,
ax_anim 2, 0, 180, 0, -12, 0, -12,
ax_anim 3, 0, 180, 0, 12, 0, 12,
ax_anim 2, 0, 180, 0, -10, 0, -10,
ax_anim 2, 0, 180, 0, 10, 0, 10,
ax_anim 2, 0, 180, 0, -6, 0, -6,
ax_anim 2, 0, 180, 0, 6, 0, 6,
ax_anim 2, 0, 180, 0, 0, 0, 0,
ax_anim_terminator
sNidorinoAnims_10_8:
ax_anim 2, 0, 179, 0, 0, 0, 0,
ax_anim 2, 0, 179, -6, -6, -6, -6,
ax_anim 2, 0, 179, 6, 6, 6, 6,
ax_anim 2, 0, 179, -10, -10, -10, -10,
ax_anim 2, 0, 179, 10, 10, 10, 10,
ax_anim 2, 0, 179, -12, -12, -12, -12,
ax_anim 3, 0, 179, 12, 12, 12, 12,
ax_anim 3, 0, 179, -13, -13, -13, -13,
ax_anim 3, 0, 179, 13, 13, 13, 13,
ax_anim 2, 0, 179, -12, -12, -12, -12,
ax_anim 3, 0, 179, 12, 12, 12, 12,
ax_anim 2, 0, 179, -10, -10, -10, -10,
ax_anim 2, 0, 179, 10, 10, 10, 10,
ax_anim 2, 0, 179, -6, -6, -6, -6,
ax_anim 2, 0, 179, 6, 6, 6, 6,
ax_anim 2, 0, 179, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sNidorinoAnims_11_1:
ax_anim 2, 0, 186, 0, 0, 0, 0,
ax_anim 1, 0, 187, 0, -10, 0, 0,
ax_anim 2, 0, 187, 0, -16, 0, 0,
ax_anim 3, 0, 187, 0, -20, 0, 0,
ax_anim 4, 0, 187, 0, -21, 0, 0,
ax_anim 4, 0, 188, 0, -25, 0, 0,
ax_anim 3, 0, 188, 0, -22, 0, 0,
ax_anim 2, 0, 188, 0, -18, 0, 0,
ax_anim 1, 0, 188, 0, -12, 0, 0,
ax_anim 2, 2, 186, 0, 0, 0, 0,
ax_anim_terminator
sNidorinoAnims_11_2:
ax_anim 2, 0, 189, 0, 0, 0, 0,
ax_anim 1, 0, 190, 0, -10, 0, 0,
ax_anim 2, 0, 190, 0, -16, 0, 0,
ax_anim 3, 0, 190, 0, -20, 0, 0,
ax_anim 4, 0, 190, 0, -21, 0, 0,
ax_anim 4, 0, 191, 0, -26, 0, 0,
ax_anim 3, 0, 191, 0, -22, 0, 0,
ax_anim 2, 0, 191, 0, -18, 0, 0,
ax_anim 1, 0, 191, 0, -12, 0, 0,
ax_anim 2, 2, 189, 0, 0, 0, 0,
ax_anim_terminator
sNidorinoAnims_11_3:
ax_anim 2, 0, 192, 0, 0, 0, 0,
ax_anim 1, 0, 193, 0, -10, 0, 0,
ax_anim 2, 0, 193, 0, -16, 0, 0,
ax_anim 3, 0, 193, 0, -20, 0, 0,
ax_anim 4, 0, 193, 0, -21, 0, 0,
ax_anim 4, 0, 194, 0, -26, 0, 0,
ax_anim 3, 0, 194, 0, -22, 0, 0,
ax_anim 2, 0, 194, 0, -18, 0, 0,
ax_anim 1, 0, 194, 0, -12, 0, 0,
ax_anim 2, 2, 192, 0, 0, 0, 0,
ax_anim_terminator
sNidorinoAnims_11_4:
ax_anim 2, 0, 195, 0, 0, 0, 0,
ax_anim 1, 0, 196, 0, -10, 0, 0,
ax_anim 2, 0, 196, 0, -16, 0, 0,
ax_anim 3, 0, 196, 0, -20, 0, 0,
ax_anim 4, 0, 196, 0, -21, 0, 0,
ax_anim 4, 0, 197, 0, -22, 0, 0,
ax_anim 3, 0, 197, 0, -21, 0, 0,
ax_anim 2, 0, 197, 0, -17, 0, 0,
ax_anim 1, 0, 197, 0, -11, 0, 0,
ax_anim 2, 2, 195, 0, 0, 0, 0,
ax_anim_terminator
sNidorinoAnims_11_5:
ax_anim 2, 0, 198, 0, 0, 0, 0,
ax_anim 1, 0, 199, 0, -10, 0, 0,
ax_anim 2, 0, 199, 0, -16, 0, 0,
ax_anim 3, 0, 199, 0, -20, 0, 0,
ax_anim 4, 0, 199, 0, -21, 0, 0,
ax_anim 4, 0, 200, 0, -23, 0, 0,
ax_anim 3, 0, 200, 0, -22, 0, 0,
ax_anim 2, 0, 200, 0, -18, 0, 0,
ax_anim 1, 0, 200, 0, -12, 0, 0,
ax_anim 2, 2, 198, 0, 0, 0, 0,
ax_anim_terminator
sNidorinoAnims_11_6:
ax_anim 2, 0, 201, 0, 0, 0, 0,
ax_anim 1, 0, 202, 0, -10, 0, 0,
ax_anim 2, 0, 202, 0, -16, 0, 0,
ax_anim 3, 0, 202, 0, -20, 0, 0,
ax_anim 4, 0, 202, 0, -21, 0, 0,
ax_anim 4, 0, 203, 0, -22, 0, 0,
ax_anim 3, 0, 203, 0, -21, 0, 0,
ax_anim 2, 0, 203, 0, -17, 0, 0,
ax_anim 1, 0, 203, 0, -11, 0, 0,
ax_anim 2, 2, 201, 0, 0, 0, 0,
ax_anim_terminator
sNidorinoAnims_11_7:
ax_anim 2, 0, 204, 0, 0, 0, 0,
ax_anim 1, 0, 205, 0, -10, 0, 0,
ax_anim 2, 0, 205, 0, -16, 0, 0,
ax_anim 3, 0, 205, 0, -20, 0, 0,
ax_anim 4, 0, 205, 0, -21, 0, 0,
ax_anim 4, 0, 206, 0, -26, 0, 0,
ax_anim 3, 0, 206, 0, -22, 0, 0,
ax_anim 2, 0, 206, 0, -18, 0, 0,
ax_anim 1, 0, 206, 0, -12, 0, 0,
ax_anim 2, 2, 204, 0, 0, 0, 0,
ax_anim_terminator
sNidorinoAnims_11_8:
ax_anim 2, 0, 207, 0, 0, 0, 0,
ax_anim 1, 0, 208, 0, -10, 0, 0,
ax_anim 2, 0, 208, 0, -16, 0, 0,
ax_anim 3, 0, 208, 0, -20, 0, 0,
ax_anim 4, 0, 208, 0, -21, 0, 0,
ax_anim 4, 0, 209, 0, -26, 0, 0,
ax_anim 3, 0, 209, 0, -22, 0, 0,
ax_anim 2, 0, 209, 0, -18, 0, 0,
ax_anim 1, 0, 209, 0, -12, 0, 0,
ax_anim 2, 2, 207, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sNidorinoAnims_12_1:
ax_anim 2, 0, 210, 1, 0, 1, 0,
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 2, 0, 210, 1, 0, 1, 0,
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 2, 0, 210, 1, 0, 1, 0,
ax_anim 2, 2, 210, 0, 0, 0, 0,
ax_anim 2, 0, 210, 1, 0, 1, 0,
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 2, 0, 210, 1, 0, 1, 0,
ax_anim 2, 1, 210, 0, 0, 0, 0,
ax_anim_terminator
sNidorinoAnims_12_2:
ax_anim 2, 0, 217, 1, -1, 1, 0,
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 0, 217, 1, -1, 1, 0,
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 0, 217, 1, -1, 1, 0,
ax_anim 2, 2, 217, 0, 0, 0, 0,
ax_anim 2, 0, 217, 1, -1, 1, 0,
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 0, 217, 1, -1, 1, 0,
ax_anim 2, 1, 217, 0, 0, 0, 0,
ax_anim_terminator
sNidorinoAnims_12_3:
ax_anim 2, 0, 216, 0, -1, 0, -1,
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, -1, 0, -1,
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, -1, 0, -1,
ax_anim 2, 2, 216, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, -1, 0, -1,
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, -1, 0, -1,
ax_anim 2, 1, 216, 0, 0, 0, 0,
ax_anim_terminator
sNidorinoAnims_12_4:
ax_anim 2, 0, 215, -1, -1, -1, -1,
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 0, 215, -1, -1, -1, -1,
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 0, 215, -1, -1, -1, -1,
ax_anim 2, 2, 215, 0, 0, 0, 0,
ax_anim 2, 0, 215, -1, -1, -1, -1,
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 0, 215, -1, -1, -1, -1,
ax_anim 2, 1, 215, 0, 0, 0, 0,
ax_anim_terminator
sNidorinoAnims_12_5:
ax_anim 2, 0, 214, 1, 0, 1, 0,
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 2, 0, 214, 1, 0, 1, 0,
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 2, 0, 214, 1, 0, 1, 0,
ax_anim 2, 2, 214, 0, 0, 0, 0,
ax_anim 2, 0, 214, 1, 0, 1, 0,
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 2, 0, 214, 1, 0, 1, 0,
ax_anim 2, 1, 214, 0, 0, 0, 0,
ax_anim_terminator
sNidorinoAnims_12_6:
ax_anim 2, 0, 213, 1, -1, 1, -1,
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 2, 0, 213, 1, -1, 1, -1,
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 2, 0, 213, 1, -1, 1, -1,
ax_anim 2, 2, 213, 0, 0, 0, 0,
ax_anim 2, 0, 213, 1, -1, 1, -1,
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 2, 0, 213, 1, -1, 1, -1,
ax_anim 2, 1, 213, 0, 0, 0, 0,
ax_anim_terminator
sNidorinoAnims_12_7:
ax_anim 2, 0, 212, 0, -1, 0, -1,
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 2, 0, 212, 0, -1, 0, -1,
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 2, 0, 212, 0, -1, 0, -1,
ax_anim 2, 2, 212, 0, 0, 0, 0,
ax_anim 2, 0, 212, 0, -1, 0, -1,
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 2, 0, 212, 0, -1, 0, -1,
ax_anim 2, 1, 212, 0, 0, 0, 0,
ax_anim_terminator
sNidorinoAnims_12_8:
ax_anim 2, 0, 211, -1, -1, -1, -1,
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 2, 0, 211, -1, -1, -1, -1,
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 2, 0, 211, -1, -1, -1, -1,
ax_anim 2, 2, 211, 0, 0, 0, 0,
ax_anim 2, 0, 211, -1, -1, -1, -1,
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 2, 0, 211, -1, -1, -1, -1,
ax_anim 2, 1, 211, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sNidorinoAnims_13_1:
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 2, 2, 218, 0, 0, 0, 0,
ax_anim_terminator
sNidorinoAnims_13_2:
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 2, 2, 225, 0, 0, 0, 0,
ax_anim_terminator
sNidorinoAnims_13_3:
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 2, 2, 224, 0, 0, 0, 0,
ax_anim_terminator
sNidorinoAnims_13_4:
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 2, 223, 0, 0, 0, 0,
ax_anim_terminator
sNidorinoAnims_13_5:
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 2, 222, 0, 0, 0, 0,
ax_anim_terminator
sNidorinoAnims_13_6:
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 2, 221, 0, 0, 0, 0,
ax_anim_terminator
sNidorinoAnims_13_7:
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 2, 220, 0, 0, 0, 0,
ax_anim_terminator
sNidorinoAnims_13_8:
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 2, 219, 0, 0, 0, 0,
ax_anim_terminator
sNidorinoGfx1:
.incbin "baserom.gba", 0x672684, 0x200
sNidorinoSprites1:
ax_sprite sNidorinoGfx1, 0x200
ax_sprite_terminator
sNidorinoGfx2:
.incbin "baserom.gba", 0x672894, 0x200
sNidorinoSprites2:
ax_sprite sNidorinoGfx2, 0x200
ax_sprite_terminator
sNidorinoGfx3:
.incbin "baserom.gba", 0x672AA4, 0x200
sNidorinoSprites3:
ax_sprite sNidorinoGfx3, 0x200
ax_sprite_terminator
sNidorinoGfx4:
.incbin "baserom.gba", 0x672CB4, 0x200
sNidorinoSprites4:
ax_sprite sNidorinoGfx4, 0x200
ax_sprite_terminator
sNidorinoGfx5:
.incbin "baserom.gba", 0x672EC4, 0x200
sNidorinoSprites5:
ax_sprite sNidorinoGfx5, 0x200
ax_sprite_terminator
sNidorinoGfx6:
.incbin "baserom.gba", 0x6730D4, 0x200
sNidorinoSprites6:
ax_sprite sNidorinoGfx6, 0x200
ax_sprite_terminator
sNidorinoGfx7:
.incbin "baserom.gba", 0x6732E4, 0x200
sNidorinoSprites7:
ax_sprite sNidorinoGfx7, 0x200
ax_sprite_terminator
sNidorinoGfx8:
.incbin "baserom.gba", 0x6734F4, 0x200
sNidorinoSprites8:
ax_sprite sNidorinoGfx8, 0x200
ax_sprite_terminator
sNidorinoGfx9:
.incbin "baserom.gba", 0x673704, 0x200
sNidorinoSprites9:
ax_sprite sNidorinoGfx9, 0x200
ax_sprite_terminator
sNidorinoGfx10:
.incbin "baserom.gba", 0x673914, 0x200
sNidorinoSprites10:
ax_sprite sNidorinoGfx10, 0x200
ax_sprite_terminator
sNidorinoGfx11:
.incbin "baserom.gba", 0x673B24, 0x200
sNidorinoSprites11:
ax_sprite sNidorinoGfx11, 0x200
ax_sprite_terminator
sNidorinoGfx12:
.incbin "baserom.gba", 0x673D34, 0x200
sNidorinoSprites12:
ax_sprite sNidorinoGfx12, 0x200
ax_sprite_terminator
sNidorinoGfx13:
.incbin "baserom.gba", 0x673F44, 0x200
sNidorinoSprites13:
ax_sprite sNidorinoGfx13, 0x200
ax_sprite_terminator
sNidorinoGfx14:
.incbin "baserom.gba", 0x674154, 0x200
sNidorinoSprites14:
ax_sprite sNidorinoGfx14, 0x200
ax_sprite_terminator
sNidorinoGfx15:
.incbin "baserom.gba", 0x674364, 0x200
sNidorinoSprites15:
ax_sprite sNidorinoGfx15, 0x200
ax_sprite_terminator
sNidorinoGfx16:
.incbin "baserom.gba", 0x674574, 0x20
sNidorinoGfx16_1:
.incbin "baserom.gba", 0x674594, 0x60
sNidorinoGfx16_2:
.incbin "baserom.gba", 0x6745F4, 0x60
sNidorinoGfx16_3:
.incbin "baserom.gba", 0x674654, 0x60
sNidorinoSprites16:
ax_sprite 0, 0x20
ax_sprite sNidorinoGfx16, 0x20
ax_sprite 0, 0x40
ax_sprite sNidorinoGfx16_1, 0x60
ax_sprite 0, 0x20
ax_sprite sNidorinoGfx16_2, 0x60
ax_sprite 0, 0x20
ax_sprite sNidorinoGfx16_3, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sNidorinoGfx17:
.incbin "baserom.gba", 0x674704, 0x60
sNidorinoGfx17_1:
.incbin "baserom.gba", 0x674764, 0x180
sNidorinoSprites17:
ax_sprite sNidorinoGfx17, 0x60
ax_sprite 0, 0x20
ax_sprite sNidorinoGfx17_1, 0x180
ax_sprite_terminator
sNidorinoGfx18:
.incbin "baserom.gba", 0x674904, 0x40
sNidorinoGfx18_1:
.incbin "baserom.gba", 0x674944, 0x180
sNidorinoSprites18:
ax_sprite 0, 0x20
ax_sprite sNidorinoGfx18, 0x40
ax_sprite 0, 0x20
ax_sprite sNidorinoGfx18_1, 0x180
ax_sprite_terminator
sNidorinoGfx19:
.incbin "baserom.gba", 0x674AEC, 0x60
sNidorinoGfx19_1:
.incbin "baserom.gba", 0x674B4C, 0x160
sNidorinoSprites19:
ax_sprite sNidorinoGfx19, 0x60
ax_sprite 0, 0x20
ax_sprite sNidorinoGfx19_1, 0x160
ax_sprite 0, 0x20
ax_sprite_terminator
sNidorinoGfx20:
.incbin "baserom.gba", 0x674CD4, 0x200
sNidorinoSprites20:
ax_sprite sNidorinoGfx20, 0x200
ax_sprite_terminator
sNidorinoGfx21:
.incbin "baserom.gba", 0x674EE4, 0x60
sNidorinoGfx21_1:
.incbin "baserom.gba", 0x674F44, 0xE0
sNidorinoGfx21_2:
.incbin "baserom.gba", 0x675024, 0x60
sNidorinoSprites21:
ax_sprite sNidorinoGfx21, 0x60
ax_sprite 0, 0x20
ax_sprite sNidorinoGfx21_1, 0xe0
ax_sprite 0, 0x20
ax_sprite sNidorinoGfx21_2, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sNidorinoGfx22:
.incbin "baserom.gba", 0x6750BC, 0x40
sNidorinoGfx22_1:
.incbin "baserom.gba", 0x6750FC, 0x100
sNidorinoGfx22_2:
.incbin "baserom.gba", 0x6751FC, 0x60
sNidorinoSprites22:
ax_sprite 0, 0x20
ax_sprite sNidorinoGfx22, 0x40
ax_sprite 0, 0x20
ax_sprite sNidorinoGfx22_1, 0x100
ax_sprite 0, 0x20
ax_sprite sNidorinoGfx22_2, 0x60
ax_sprite_terminator
sNidorinoGfx23:
.incbin "baserom.gba", 0x675294, 0x40
sNidorinoGfx23_1:
.incbin "baserom.gba", 0x6752D4, 0xE0
sNidorinoGfx23_2:
.incbin "baserom.gba", 0x6753B4, 0x40
sNidorinoSprites23:
ax_sprite 0, 0x20
ax_sprite sNidorinoGfx23, 0x40
ax_sprite 0, 0x40
ax_sprite sNidorinoGfx23_1, 0xe0
ax_sprite 0, 0x40
ax_sprite sNidorinoGfx23_2, 0x40
ax_sprite_terminator
sNidorinoGfx24:
.incbin "baserom.gba", 0x67542C, 0xE0
sNidorinoGfx24_1:
.incbin "baserom.gba", 0x67550C, 0x60
sNidorinoGfx24_2:
.incbin "baserom.gba", 0x67556C, 0x60
sNidorinoSprites24:
ax_sprite 0, 0x20
ax_sprite sNidorinoGfx24, 0xe0
ax_sprite 0, 0x20
ax_sprite sNidorinoGfx24_1, 0x60
ax_sprite 0, 0x20
ax_sprite sNidorinoGfx24_2, 0x60
ax_sprite_terminator
sNidorinoGfx25:
.incbin "baserom.gba", 0x675604, 0xE0
sNidorinoGfx25_1:
.incbin "baserom.gba", 0x6756E4, 0xE0
sNidorinoSprites25:
ax_sprite 0, 0x20
ax_sprite sNidorinoGfx25, 0xe0
ax_sprite 0, 0x20
ax_sprite sNidorinoGfx25_1, 0xe0
ax_sprite_terminator
sNidorinoGfx26:
.incbin "baserom.gba", 0x6757EC, 0x40
sNidorinoGfx26_1:
.incbin "baserom.gba", 0x67582C, 0x60
sNidorinoGfx26_2:
.incbin "baserom.gba", 0x67588C, 0xE0
sNidorinoSprites26:
ax_sprite 0, 0x20
ax_sprite sNidorinoGfx26, 0x40
ax_sprite 0, 0x20
ax_sprite sNidorinoGfx26_1, 0x60
ax_sprite 0, 0x20
ax_sprite sNidorinoGfx26_2, 0xe0
ax_sprite 0, 0x20
ax_sprite_terminator
sNidorinoGfx27:
.incbin "baserom.gba", 0x6759AC, 0x60
sNidorinoGfx27_1:
.incbin "baserom.gba", 0x675A0C, 0x160
sNidorinoSprites27:
ax_sprite sNidorinoGfx27, 0x60
ax_sprite 0, 0x20
ax_sprite sNidorinoGfx27_1, 0x160
ax_sprite 0, 0x20
ax_sprite_terminator
sNidorinoGfx28:
.incbin "baserom.gba", 0x675B94, 0x60
sNidorinoGfx28_1:
.incbin "baserom.gba", 0x675BF4, 0x180
sNidorinoSprites28:
ax_sprite sNidorinoGfx28, 0x60
ax_sprite 0, 0x20
ax_sprite sNidorinoGfx28_1, 0x180
ax_sprite_terminator
sNidorinoGfx29:
.incbin "baserom.gba", 0x675D94, 0x60
sNidorinoGfx29_1:
.incbin "baserom.gba", 0x675DF4, 0x180
sNidorinoSprites29:
ax_sprite sNidorinoGfx29, 0x60
ax_sprite 0, 0x20
ax_sprite sNidorinoGfx29_1, 0x180
ax_sprite_terminator
sNidorinoGfx30:
.incbin "baserom.gba", 0x675F94, 0x20
sNidorinoGfx30_1:
.incbin "baserom.gba", 0x675FB4, 0x180
sNidorinoSprites30:
ax_sprite 0, 0x20
ax_sprite sNidorinoGfx30, 0x20
ax_sprite 0, 0x40
ax_sprite sNidorinoGfx30_1, 0x180
ax_sprite_terminator
sNidorinoGfx31:
.incbin "baserom.gba", 0x67615C, 0x40
sNidorinoGfx31_1:
.incbin "baserom.gba", 0x67619C, 0x180
sNidorinoSprites31:
ax_sprite 0, 0x20
ax_sprite sNidorinoGfx31, 0x40
ax_sprite 0, 0x20
ax_sprite sNidorinoGfx31_1, 0x180
ax_sprite_terminator
sNidorinoGfx32:
.incbin "baserom.gba", 0x676344, 0x60
sNidorinoGfx32_1:
.incbin "baserom.gba", 0x6763A4, 0x160
sNidorinoSprites32:
ax_sprite sNidorinoGfx32, 0x60
ax_sprite 0, 0x20
ax_sprite sNidorinoGfx32_1, 0x160
ax_sprite 0, 0x20
ax_sprite_terminator
sNidorinoGfx33:
.incbin "baserom.gba", 0x67652C, 0x40
sNidorinoGfx33_1:
.incbin "baserom.gba", 0x67656C, 0x160
sNidorinoSprites33:
ax_sprite 0, 0x20
ax_sprite sNidorinoGfx33, 0x40
ax_sprite 0, 0x20
ax_sprite sNidorinoGfx33_1, 0x160
ax_sprite 0, 0x20
ax_sprite_terminator
sNidorinoGfx34:
.incbin "baserom.gba", 0x6766FC, 0x200
sNidorinoSprites34:
ax_sprite sNidorinoGfx34, 0x200
ax_sprite_terminator
sNidorinoGfx35:
.incbin "baserom.gba", 0x67690C, 0x200
sNidorinoSprites35:
ax_sprite sNidorinoGfx35, 0x200
ax_sprite_terminator
sNidorinoGfx36:
.incbin "baserom.gba", 0x676B1C, 0x200
sNidorinoSprites36:
ax_sprite sNidorinoGfx36, 0x200
ax_sprite_terminator
sNidorinoGfx37:
.incbin "baserom.gba", 0x676D2C, 0x200
sNidorinoSprites37:
ax_sprite sNidorinoGfx37, 0x200
ax_sprite_terminator
sNidorinoGfx38:
.incbin "baserom.gba", 0x676F3C, 0x200
sNidorinoSprites38:
ax_sprite sNidorinoGfx38, 0x200
ax_sprite_terminator
sNidorinoGfx39:
.incbin "baserom.gba", 0x67714C, 0x200
sNidorinoSprites39:
ax_sprite sNidorinoGfx39, 0x200
ax_sprite_terminator
sNidorinoGfx40:
.incbin "baserom.gba", 0x67735C, 0x200
sNidorinoSprites40:
ax_sprite sNidorinoGfx40, 0x200
ax_sprite_terminator
sNidorinoGfx41:
.incbin "baserom.gba", 0x67756C, 0x200
sNidorinoSprites41:
ax_sprite sNidorinoGfx41, 0x200
ax_sprite_terminator
sNidorinoGfx42:
.incbin "baserom.gba", 0x67777C, 0x200
sNidorinoSprites42:
ax_sprite sNidorinoGfx42, 0x200
ax_sprite_terminator
sAxPosesNidorino:
.4byte sNidorinoPose1
.4byte sNidorinoPose2
.4byte sNidorinoPose3
.4byte sNidorinoPose4
.4byte sNidorinoPose5
.4byte sNidorinoPose6
.4byte sNidorinoPose7
.4byte sNidorinoPose8
.4byte sNidorinoPose9
.4byte sNidorinoPose10
.4byte sNidorinoPose11
.4byte sNidorinoPose12
.4byte sNidorinoPose13
.4byte sNidorinoPose14
.4byte sNidorinoPose15
.4byte sNidorinoPose16
.4byte sNidorinoPose17
.4byte sNidorinoPose18
.4byte sNidorinoPose19
.4byte sNidorinoPose20
.4byte sNidorinoPose21
.4byte sNidorinoPose22
.4byte sNidorinoPose23
.4byte sNidorinoPose24
.4byte sNidorinoPose25
.4byte sNidorinoPose26
.4byte sNidorinoPose27
.4byte sNidorinoPose28
.4byte sNidorinoPose29
.4byte sNidorinoPose30
.4byte sNidorinoPose31
.4byte sNidorinoPose32
.4byte sNidorinoPose33
.4byte sNidorinoPose34
.4byte sNidorinoPose35
.4byte sNidorinoPose36
.4byte sNidorinoPose37
.4byte sNidorinoPose38
.4byte sNidorinoPose39
.4byte sNidorinoPose40
.4byte sNidorinoPose41
.4byte sNidorinoPose42
.4byte sNidorinoPose43
.4byte sNidorinoPose44
.4byte sNidorinoPose45
.4byte sNidorinoPose46
.4byte sNidorinoPose47
.4byte sNidorinoPose48
.4byte sNidorinoPose49
.4byte sNidorinoPose50
.4byte sNidorinoPose51
.4byte sNidorinoPose52
.4byte sNidorinoPose53
.4byte sNidorinoPose54
.4byte sNidorinoPose55
.4byte sNidorinoPose56
.4byte sNidorinoPose57
.4byte sNidorinoPose58
.4byte sNidorinoPose59
.4byte sNidorinoPose60
.4byte sNidorinoPose61
.4byte sNidorinoPose62
.4byte sNidorinoPose63
.4byte sNidorinoPose64
.4byte sNidorinoPose65
.4byte sNidorinoPose66
.4byte sNidorinoPose67
.4byte sNidorinoPose68
.4byte sNidorinoPose69
.4byte sNidorinoPose70
.4byte sNidorinoPose71
.4byte sNidorinoPose72
.4byte sNidorinoPose73
.4byte sNidorinoPose74
.4byte sNidorinoPose75
.4byte sNidorinoPose76
.4byte sNidorinoPose77
.4byte sNidorinoPose78
.4byte sNidorinoPose79
.4byte sNidorinoPose80
.4byte sNidorinoPose81
.4byte sNidorinoPose82
.4byte sNidorinoPose83
.4byte sNidorinoPose84
.4byte sNidorinoPose85
.4byte sNidorinoPose86
.4byte sNidorinoPose87
.4byte sNidorinoPose88
.4byte sNidorinoPose89
.4byte sNidorinoPose90
.4byte sNidorinoPose91
.4byte sNidorinoPose92
.4byte sNidorinoPose93
.4byte sNidorinoPose94
.4byte sNidorinoPose95
.4byte sNidorinoPose96
.4byte sNidorinoPose97
.4byte sNidorinoPose98
.4byte sNidorinoPose99
.4byte sNidorinoPose100
.4byte sNidorinoPose101
.4byte sNidorinoPose102
.4byte sNidorinoPose103
.4byte sNidorinoPose104
.4byte sNidorinoPose105
.4byte sNidorinoPose106
.4byte sNidorinoPose107
.4byte sNidorinoPose108
.4byte sNidorinoPose109
.4byte sNidorinoPose110
.4byte sNidorinoPose111
.4byte sNidorinoPose112
.4byte sNidorinoPose113
.4byte sNidorinoPose114
.4byte sNidorinoPose115
.4byte sNidorinoPose116
.4byte sNidorinoPose117
.4byte sNidorinoPose118
.4byte sNidorinoPose119
.4byte sNidorinoPose120
.4byte sNidorinoPose121
.4byte sNidorinoPose122
.4byte sNidorinoPose123
.4byte sNidorinoPose124
.4byte sNidorinoPose125
.4byte sNidorinoPose126
.4byte sNidorinoPose127
.4byte sNidorinoPose128
.4byte sNidorinoPose129
.4byte sNidorinoPose130
.4byte sNidorinoPose131
.4byte sNidorinoPose132
.4byte sNidorinoPose133
.4byte sNidorinoPose134
.4byte sNidorinoPose135
.4byte sNidorinoPose136
.4byte sNidorinoPose137
.4byte sNidorinoPose138
.4byte sNidorinoPose139
.4byte sNidorinoPose140
.4byte sNidorinoPose141
.4byte sNidorinoPose142
.4byte sNidorinoPose143
.4byte sNidorinoPose144
.4byte sNidorinoPose145
.4byte sNidorinoPose146
.4byte sNidorinoPose147
.4byte sNidorinoPose148
.4byte sNidorinoPose149
.4byte sNidorinoPose150
.4byte sNidorinoPose151
.4byte sNidorinoPose152
.4byte sNidorinoPose153
.4byte sNidorinoPose154
.4byte sNidorinoPose155
.4byte sNidorinoPose156
.4byte sNidorinoPose157
.4byte sNidorinoPose158
.4byte sNidorinoPose159
.4byte sNidorinoPose160
.4byte sNidorinoPose161
.4byte sNidorinoPose162
.4byte sNidorinoPose163
.4byte sNidorinoPose164
.4byte sNidorinoPose165
.4byte sNidorinoPose166
.4byte sNidorinoPose167
.4byte sNidorinoPose168
.4byte sNidorinoPose169
.4byte sNidorinoPose170
.4byte sNidorinoPose171
.4byte sNidorinoPose172
.4byte sNidorinoPose173
.4byte sNidorinoPose174
.4byte sNidorinoPose175
.4byte sNidorinoPose176
.4byte sNidorinoPose177
.4byte sNidorinoPose178
.4byte sNidorinoPose179
.4byte sNidorinoPose180
.4byte sNidorinoPose181
.4byte sNidorinoPose182
.4byte sNidorinoPose183
.4byte sNidorinoPose184
.4byte sNidorinoPose185
.4byte sNidorinoPose186
.4byte sNidorinoPose187
.4byte sNidorinoPose188
.4byte sNidorinoPose189
.4byte sNidorinoPose190
.4byte sNidorinoPose191
.4byte sNidorinoPose192
.4byte sNidorinoPose193
.4byte sNidorinoPose194
.4byte sNidorinoPose195
.4byte sNidorinoPose196
.4byte sNidorinoPose197
.4byte sNidorinoPose198
.4byte sNidorinoPose199
.4byte sNidorinoPose200
.4byte sNidorinoPose201
.4byte sNidorinoPose202
.4byte sNidorinoPose203
.4byte sNidorinoPose204
.4byte sNidorinoPose205
.4byte sNidorinoPose206
.4byte sNidorinoPose207
.4byte sNidorinoPose208
.4byte sNidorinoPose209
.4byte sNidorinoPose210
.4byte sNidorinoPose211
.4byte sNidorinoPose212
.4byte sNidorinoPose213
.4byte sNidorinoPose214
.4byte sNidorinoPose215
.4byte sNidorinoPose216
.4byte sNidorinoPose217
.4byte sNidorinoPose218
.4byte sNidorinoPose219
.4byte sNidorinoPose220
.4byte sNidorinoPose221
.4byte sNidorinoPose222
.4byte sNidorinoPose223
.4byte sNidorinoPose224
.4byte sNidorinoPose225
.4byte sNidorinoPose226
sAxPositionsNidorino:
.2byte   -1,    3, 	 -10,    1, 	   8,    1, 	  -1,   -9
.2byte   -2,    4, 	  -9,    0, 	   7,    4, 	  -2,   -7
.2byte    1,    4, 	  -9,    4, 	   8,    0, 	   1,   -8
.2byte    7,    0, 	   7,   -2, 	  -2,    2, 	  -1,  -10
.2byte    8,    1, 	   3,   -3, 	   2,    4, 	   0,  -10
.2byte    5,    1, 	   6,    1, 	  -4,    2, 	  -2,   -9
.2byte    8,   -4, 	   3,   -3, 	   2,    1, 	  -2,   -9
.2byte    8,   -5, 	  -2,   -3, 	   5,    0, 	  -3,   -9
.2byte    7,   -3, 	   6,   -2, 	  -1,    1, 	  -2,   -9
.2byte   10,  -10, 	  -3,   -8, 	   8,   -3, 	  -1,  -11
.2byte   11,   -9, 	  -5,   -5, 	   9,   -3, 	  -1,  -10
.2byte   10,  -10, 	   0,  -10, 	   5,   -2, 	  -2,  -10
.2byte   -1,  -13, 	   8,   -7, 	 -10,   -7, 	  -1,  -10
.2byte    1,  -12, 	   7,   -6, 	 -10,   -8, 	  -1,   -9
.2byte   -3,  -12, 	   8,   -8, 	  -8,   -8, 	  -1,   -9
.2byte  -12,  -10, 	   1,   -8, 	 -10,   -3, 	  -1,  -11
.2byte  -13,   -9, 	   3,   -5, 	 -11,   -3, 	  -1,  -10
.2byte  -12,  -10, 	  -2,  -10, 	  -7,   -2, 	   0,  -10
.2byte  -10,   -4, 	  -5,   -3, 	  -4,    1, 	   0,   -9
.2byte  -10,   -5, 	   0,   -3, 	  -7,    0, 	   1,   -9
.2byte   -9,   -3, 	  -8,   -2, 	  -1,    1, 	   0,   -9
.2byte   -9,    0, 	  -9,   -2, 	   0,    2, 	  -1,  -10
.2byte  -10,    1, 	  -5,   -3, 	  -4,    4, 	  -2,  -10
.2byte   -7,    1, 	  -8,    1, 	   2,    2, 	   0,   -9
.2byte   -1,    3, 	 -10,    1, 	   8,    1, 	  -1,   -9
.2byte   -2,    4, 	  -9,    0, 	   7,    4, 	  -2,   -7
.2byte    1,    4, 	  -9,    4, 	   8,    0, 	   1,   -8
.2byte   -1,    3, 	 -10,    1, 	   8,    1, 	  -1,   -6
.2byte    7,    0, 	   7,   -2, 	  -2,    2, 	  -1,  -10
.2byte    8,    1, 	   3,   -3, 	   2,    4, 	   0,  -10
.2byte    6,    1, 	   7,    1, 	  -3,    2, 	  -1,   -9
.2byte    6,    0, 	   8,   -1, 	  -3,    2, 	   0,   -8
.2byte    8,   -4, 	   3,   -3, 	   2,    1, 	  -2,   -9
.2byte    8,   -5, 	  -2,   -3, 	   5,    0, 	  -3,   -9
.2byte    7,   -3, 	   6,   -2, 	  -1,    1, 	  -2,   -9
.2byte    8,   -3, 	   4,   -2, 	   1,    1, 	  -2,   -8
.2byte   10,  -10, 	  -3,   -8, 	   8,   -3, 	  -1,  -11
.2byte   11,   -9, 	  -5,   -5, 	   9,   -3, 	  -1,  -10
.2byte   10,  -10, 	   0,  -10, 	   5,   -2, 	  -2,  -10
.2byte   11,  -12, 	  -2,   -7, 	   8,   -3, 	  -1,  -11
.2byte   -1,  -13, 	   8,   -7, 	 -10,   -7, 	  -1,  -10
.2byte    1,  -12, 	   7,   -6, 	 -10,   -8, 	  -1,   -9
.2byte   -3,  -12, 	   8,   -8, 	  -8,   -8, 	  -1,   -9
.2byte   -1,  -16, 	   8,   -6, 	 -10,   -6, 	  -1,  -10
.2byte  -11,  -10, 	   2,   -8, 	  -9,   -3, 	   0,  -11
.2byte  -12,   -9, 	   4,   -5, 	 -10,   -3, 	   0,  -10
.2byte  -11,  -10, 	  -1,  -10, 	  -6,   -2, 	   1,  -10
.2byte  -12,  -12, 	   1,   -7, 	  -9,   -3, 	   0,  -11
.2byte   -9,   -4, 	  -4,   -3, 	  -3,    1, 	   1,   -9
.2byte   -9,   -5, 	   1,   -3, 	  -6,    0, 	   2,   -9
.2byte   -8,   -3, 	  -7,   -2, 	   0,    1, 	   1,   -9
.2byte   -9,   -3, 	  -5,   -2, 	  -2,    1, 	   1,   -8
.2byte   -8,    0, 	  -8,   -2, 	   1,    2, 	   0,  -10
.2byte   -9,    1, 	  -4,   -3, 	  -3,    4, 	  -1,  -10
.2byte   -7,    1, 	  -8,    1, 	   2,    2, 	   0,   -9
.2byte   -7,    0, 	  -9,   -1, 	   2,    2, 	  -1,   -8
.2byte   -1,    3, 	 -10,    1, 	   8,    1, 	  -1,   -9
.2byte   -2,    4, 	  -9,    0, 	   7,    4, 	  -2,   -7
.2byte    1,    4, 	  -9,    4, 	   8,    0, 	   1,   -8
.2byte   -1,    3, 	 -10,    1, 	   8,    1, 	  -1,   -6
.2byte    7,    0, 	   7,   -2, 	  -2,    2, 	  -1,  -10
.2byte    8,    1, 	   3,   -3, 	   2,    4, 	   0,  -10
.2byte    6,    1, 	   7,    1, 	  -3,    2, 	  -1,   -9
.2byte    6,    0, 	   8,   -1, 	  -3,    2, 	   0,   -8
.2byte    8,   -4, 	   3,   -3, 	   2,    1, 	  -2,   -9
.2byte    8,   -5, 	  -2,   -3, 	   5,    0, 	  -3,   -9
.2byte    7,   -3, 	   6,   -2, 	  -1,    1, 	  -2,   -9
.2byte    8,   -3, 	   4,   -2, 	   1,    1, 	  -2,   -8
.2byte   10,  -10, 	  -3,   -8, 	   8,   -3, 	  -1,  -11
.2byte   11,   -9, 	  -5,   -5, 	   9,   -3, 	  -1,  -10
.2byte   10,  -10, 	   0,  -10, 	   5,   -2, 	  -2,  -10
.2byte   11,  -12, 	  -2,   -7, 	   8,   -3, 	  -1,  -11
.2byte   -1,  -13, 	   8,   -7, 	 -10,   -7, 	  -1,  -10
.2byte    1,  -12, 	   7,   -6, 	 -10,   -8, 	  -1,   -9
.2byte   -3,  -12, 	   8,   -8, 	  -8,   -8, 	  -1,   -9
.2byte   -1,  -16, 	   8,   -6, 	 -10,   -6, 	  -1,  -10
.2byte  -11,  -10, 	   2,   -8, 	  -9,   -3, 	   0,  -11
.2byte  -12,   -9, 	   4,   -5, 	 -10,   -3, 	   0,  -10
.2byte  -11,  -10, 	  -1,  -10, 	  -6,   -2, 	   1,  -10
.2byte  -12,  -12, 	   1,   -7, 	  -9,   -3, 	   0,  -11
.2byte   -9,   -4, 	  -4,   -3, 	  -3,    1, 	   1,   -9
.2byte   -9,   -5, 	   1,   -3, 	  -6,    0, 	   2,   -9
.2byte   -8,   -3, 	  -7,   -2, 	   0,    1, 	   1,   -9
.2byte   -9,   -3, 	  -5,   -2, 	  -2,    1, 	   1,   -8
.2byte   -8,    0, 	  -8,   -2, 	   1,    2, 	   0,  -10
.2byte   -9,    1, 	  -4,   -3, 	  -3,    4, 	  -1,  -10
.2byte   -7,    1, 	  -8,    1, 	   2,    2, 	   0,   -9
.2byte   -7,    0, 	  -9,   -1, 	   2,    2, 	  -1,   -8
.2byte   -1,    3, 	 -10,    1, 	   8,    1, 	  -1,   -9
.2byte   -6,  -21, 	 -11,   -9, 	   1,  -10, 	  -1,  -10
.2byte   -1,    3, 	 -10,    1, 	   8,    1, 	  -1,   -6
.2byte    7,    0, 	   7,   -2, 	  -2,    2, 	  -1,  -10
.2byte   -1,  -24, 	   6,  -14, 	  -1,   -8, 	  -6,  -12
.2byte    6,    0, 	   8,   -1, 	  -3,    2, 	   0,   -8
.2byte    8,   -4, 	   3,   -3, 	   2,    1, 	  -2,   -9
.2byte    2,  -20, 	  -6,  -14, 	   6,   -7, 	  -7,  -11
.2byte    9,   -3, 	   5,   -2, 	   2,    1, 	  -1,   -8
.2byte   10,  -10, 	  -3,   -8, 	   8,   -3, 	  -1,  -11
.2byte   -4,  -23, 	  -9,  -18, 	   5,  -15, 	  -6,  -10
.2byte   11,  -12, 	  -2,   -7, 	   8,   -3, 	  -1,  -11
.2byte   -1,  -13, 	   8,   -7, 	 -10,   -7, 	  -1,  -10
.2byte    8,  -19, 	  11,   -8, 	  -1,  -11, 	   0,   -8
.2byte   -1,  -17, 	   8,   -7, 	 -10,   -7, 	  -1,  -11
.2byte  -12,  -10, 	   1,   -8, 	 -10,   -3, 	  -1,  -11
.2byte    2,  -23, 	   7,  -18, 	  -7,  -15, 	   4,  -10
.2byte  -13,  -12, 	   0,   -7, 	 -10,   -3, 	  -1,  -11
.2byte  -10,   -4, 	  -5,   -3, 	  -4,    1, 	   0,   -9
.2byte   -4,  -20, 	   4,  -14, 	  -8,   -7, 	   5,  -11
.2byte  -11,   -3, 	  -7,   -2, 	  -4,    1, 	  -1,   -8
.2byte   -9,    0, 	  -9,   -2, 	   0,    2, 	  -1,  -10
.2byte   -1,  -24, 	  -8,  -14, 	  -1,   -8, 	   4,  -12
.2byte   -8,    0, 	 -10,   -1, 	   1,    2, 	  -2,   -8
.2byte   -1,    3, 	 -10,    1, 	   8,    1, 	  -1,   -9
.2byte   -1,    4, 	 -11,    1, 	   9,    1, 	  -2,   -7
.2byte   -2,    4, 	 -11,    1, 	   9,    1, 	  -1,   -7
.2byte    7,    0, 	   7,   -2, 	  -2,    2, 	  -1,  -10
.2byte    7,    2, 	   8,   -1, 	  -4,    2, 	  -2,  -10
.2byte    7,    1, 	   8,   -1, 	  -4,    2, 	  -1,   -9
.2byte    8,   -4, 	   3,   -3, 	   2,    1, 	  -2,   -9
.2byte    9,   -2, 	   4,   -2, 	   1,    2, 	  -2,   -8
.2byte    8,   -1, 	   4,   -1, 	   1,    2, 	  -2,   -8
.2byte   10,  -10, 	  -3,   -8, 	   8,   -3, 	  -1,  -11
.2byte   10,   -8, 	  -3,   -7, 	   9,   -2, 	  -1,  -10
.2byte    9,   -6, 	  -1,   -7, 	   9,   -2, 	  -1,  -10
.2byte   -1,  -13, 	   8,   -7, 	 -10,   -7, 	  -1,  -10
.2byte   -2,  -10, 	   9,   -7, 	 -11,   -7, 	  -1,   -9
.2byte    1,  -10, 	   9,   -7, 	 -11,   -7, 	   0,   -9
.2byte  -12,  -10, 	   1,   -8, 	 -10,   -3, 	  -1,  -11
.2byte  -12,   -8, 	   1,   -7, 	 -11,   -2, 	  -1,  -10
.2byte  -11,   -6, 	  -1,   -7, 	 -11,   -2, 	  -1,  -10
.2byte  -10,   -4, 	  -5,   -3, 	  -4,    1, 	   0,   -9
.2byte  -11,   -2, 	  -6,   -2, 	  -3,    2, 	   0,   -8
.2byte  -10,   -1, 	  -6,   -1, 	  -3,    2, 	   0,   -8
.2byte   -9,    0, 	  -9,   -2, 	   0,    2, 	  -1,  -10
.2byte   -9,    2, 	 -10,   -1, 	   2,    2, 	   0,  -10
.2byte   -9,    1, 	 -10,   -1, 	   2,    2, 	  -1,   -9
.2byte   -8,    1, 	 -11,    0, 	  -7,    2, 	  -1,   -7
.2byte   -8,    2, 	 -11,    0, 	  -7,    2, 	  -1,   -6
.2byte    0,    5, 	  -9,    2, 	   9,    2, 	   0,   -8
.2byte    3,    1, 	  11,   -1, 	   1,    3, 	   0,   -8
.2byte    6,    0, 	   3,   -1, 	   0,    1, 	  -2,   -8
.2byte   10,   -6, 	   1,   -6, 	  10,   -1, 	   1,   -8
.2byte    0,   -8, 	   7,   -9, 	  -7,   -9, 	   0,   -7
.2byte   -9,   -6, 	   0,   -6, 	  -9,   -1, 	   0,   -8
.2byte   -7,    0, 	  -4,   -1, 	  -1,    1, 	   1,   -8
.2byte   -4,    1, 	 -12,   -1, 	  -2,    3, 	  -1,   -8
.2byte   -1,    3, 	 -10,    1, 	   8,    1, 	  -1,   -9
.2byte   -2,    4, 	  -9,    0, 	   7,    4, 	  -2,   -7
.2byte    1,    4, 	  -9,    4, 	   8,    0, 	   1,   -8
.2byte    7,    0, 	   7,   -2, 	  -2,    2, 	  -1,  -10
.2byte    8,    1, 	   3,   -3, 	   2,    4, 	   0,  -10
.2byte    5,    1, 	   6,    1, 	  -4,    2, 	  -2,   -9
.2byte    8,   -4, 	   3,   -3, 	   2,    1, 	  -2,   -9
.2byte    8,   -5, 	  -2,   -3, 	   5,    0, 	  -3,   -9
.2byte    7,   -3, 	   6,   -2, 	  -1,    1, 	  -2,   -9
.2byte   10,  -10, 	  -3,   -8, 	   8,   -3, 	  -1,  -11
.2byte   11,   -9, 	  -5,   -5, 	   9,   -3, 	  -1,  -10
.2byte   10,  -10, 	   0,  -10, 	   5,   -2, 	  -2,  -10
.2byte   -1,  -13, 	   8,   -7, 	 -10,   -7, 	  -1,  -10
.2byte    1,  -12, 	   7,   -6, 	 -10,   -8, 	  -1,   -9
.2byte   -3,  -12, 	   8,   -8, 	  -8,   -8, 	  -1,   -9
.2byte  -12,  -10, 	   1,   -8, 	 -10,   -3, 	  -1,  -11
.2byte  -13,   -9, 	   3,   -5, 	 -11,   -3, 	  -1,  -10
.2byte  -12,  -10, 	  -2,  -10, 	  -7,   -2, 	   0,  -10
.2byte  -10,   -4, 	  -5,   -3, 	  -4,    1, 	   0,   -9
.2byte  -10,   -5, 	   0,   -3, 	  -7,    0, 	   1,   -9
.2byte   -9,   -3, 	  -8,   -2, 	  -1,    1, 	   0,   -9
.2byte   -9,    0, 	  -9,   -2, 	   0,    2, 	  -1,  -10
.2byte  -10,    1, 	  -5,   -3, 	  -4,    4, 	  -2,  -10
.2byte   -7,    1, 	  -8,    1, 	   2,    2, 	   0,   -9
.2byte   -1,    3, 	 -10,    1, 	   8,    1, 	  -1,   -6
.2byte   -7,    0, 	  -9,   -1, 	   2,    2, 	  -1,   -8
.2byte   -9,   -3, 	  -5,   -2, 	  -2,    1, 	   1,   -8
.2byte  -12,  -12, 	   1,   -7, 	  -9,   -3, 	   0,  -11
.2byte   -1,  -16, 	   8,   -6, 	 -10,   -6, 	  -1,  -10
.2byte   11,  -12, 	  -2,   -7, 	   8,   -3, 	  -1,  -11
.2byte    8,   -3, 	   4,   -2, 	   1,    1, 	  -2,   -8
.2byte    6,    0, 	   8,   -1, 	  -3,    2, 	   0,   -8
.2byte   -1,    3, 	 -10,    1, 	   8,    1, 	  -1,   -6
.2byte   -7,    0, 	  -9,   -1, 	   2,    2, 	  -1,   -8
.2byte   -9,   -3, 	  -5,   -2, 	  -2,    1, 	   1,   -8
.2byte  -12,   -9, 	   1,   -4, 	  -9,    0, 	   0,   -8
.2byte   -1,  -14, 	   8,   -4, 	 -10,   -4, 	  -1,   -8
.2byte   11,   -9, 	  -2,   -4, 	   8,    0, 	  -1,   -8
.2byte    8,   -3, 	   4,   -2, 	   1,    1, 	  -2,   -8
.2byte    6,    0, 	   8,   -1, 	  -3,    2, 	   0,   -8
.2byte   -1,    3, 	 -10,    1, 	   8,    1, 	  -1,   -9
.2byte   -6,  -21, 	 -11,   -9, 	   1,  -10, 	  -1,  -10
.2byte   -1,    3, 	 -10,    1, 	   8,    1, 	  -1,   -6
.2byte    7,    0, 	   7,   -2, 	  -2,    2, 	  -1,  -10
.2byte    4,  -23, 	  11,  -13, 	   4,   -7, 	  -1,  -11
.2byte    6,    0, 	   8,   -1, 	  -3,    2, 	   0,   -8
.2byte    8,   -4, 	   3,   -3, 	   2,    1, 	  -2,   -9
.2byte    5,  -20, 	  -3,  -14, 	   9,   -7, 	  -4,  -11
.2byte    8,   -3, 	   4,   -2, 	   1,    1, 	  -2,   -8
.2byte   10,  -10, 	  -3,   -8, 	   8,   -3, 	  -1,  -11
.2byte   -1,  -23, 	  -6,  -18, 	   8,  -15, 	  -3,  -10
.2byte   11,  -12, 	  -2,   -7, 	   8,   -3, 	  -1,  -11
.2byte   -1,  -13, 	   8,   -7, 	 -10,   -7, 	  -1,  -10
.2byte    7,  -19, 	  10,   -8, 	  -2,  -11, 	  -1,   -8
.2byte   -1,  -17, 	   8,   -7, 	 -10,   -7, 	  -1,  -11
.2byte  -12,  -10, 	   1,   -8, 	 -10,   -3, 	  -1,  -11
.2byte   -1,  -23, 	   4,  -18, 	 -10,  -15, 	   1,  -10
.2byte  -13,  -12, 	   0,   -7, 	 -10,   -3, 	  -1,  -11
.2byte  -10,   -4, 	  -5,   -3, 	  -4,    1, 	   0,   -9
.2byte   -7,  -20, 	   1,  -14, 	 -11,   -7, 	   2,  -11
.2byte  -10,   -3, 	  -6,   -2, 	  -3,    1, 	   0,   -8
.2byte   -9,    0, 	  -9,   -2, 	   0,    2, 	  -1,  -10
.2byte   -4,  -23, 	 -11,  -13, 	  -4,   -7, 	   1,  -11
.2byte   -8,    0, 	 -10,   -1, 	   1,    2, 	  -2,   -8
.2byte   -1,    3, 	 -10,    1, 	   8,    1, 	  -1,   -6
.2byte   -7,    0, 	  -9,   -1, 	   2,    2, 	  -1,   -8
.2byte   -9,   -3, 	  -5,   -2, 	  -2,    1, 	   1,   -8
.2byte  -12,   -9, 	   1,   -4, 	  -9,    0, 	   0,   -8
.2byte   -1,  -14, 	   8,   -4, 	 -10,   -4, 	  -1,   -8
.2byte   11,   -9, 	  -2,   -4, 	   8,    0, 	  -1,   -8
.2byte    8,   -3, 	   4,   -2, 	   1,    1, 	  -2,   -8
.2byte    6,    0, 	   8,   -1, 	  -3,    2, 	   0,   -8
.2byte   -1,    3, 	 -10,    1, 	   8,    1, 	  -1,   -9
.2byte   -9,    0, 	  -9,   -2, 	   0,    2, 	  -1,  -10
.2byte  -10,   -4, 	  -5,   -3, 	  -4,    1, 	   0,   -9
.2byte  -12,  -10, 	   1,   -8, 	 -10,   -3, 	  -1,  -11
.2byte   -1,  -13, 	   8,   -7, 	 -10,   -7, 	  -1,  -10
.2byte   10,  -10, 	  -3,   -8, 	   8,   -3, 	  -1,  -11
.2byte    8,   -4, 	   3,   -3, 	   2,    1, 	  -2,   -9
.2byte    7,    0, 	   7,   -2, 	  -2,    2, 	  -1,  -10
sNidorinoAnimTable1:
.4byte sNidorinoAnims_1_1
.4byte sNidorinoAnims_1_2
.4byte sNidorinoAnims_1_3
.4byte sNidorinoAnims_1_4
.4byte sNidorinoAnims_1_5
.4byte sNidorinoAnims_1_6
.4byte sNidorinoAnims_1_7
.4byte sNidorinoAnims_1_8
sNidorinoAnimTable2:
.4byte sNidorinoAnims_2_1
.4byte sNidorinoAnims_2_2
.4byte sNidorinoAnims_2_3
.4byte sNidorinoAnims_2_4
.4byte sNidorinoAnims_2_5
.4byte sNidorinoAnims_2_6
.4byte sNidorinoAnims_2_7
.4byte sNidorinoAnims_2_8
sNidorinoAnimTable3:
.4byte sNidorinoAnims_3_1
.4byte sNidorinoAnims_3_2
.4byte sNidorinoAnims_3_3
.4byte sNidorinoAnims_3_4
.4byte sNidorinoAnims_3_5
.4byte sNidorinoAnims_3_6
.4byte sNidorinoAnims_3_7
.4byte sNidorinoAnims_3_8
sNidorinoAnimTable4:
.4byte sNidorinoAnims_4_1
.4byte sNidorinoAnims_4_2
.4byte sNidorinoAnims_4_3
.4byte sNidorinoAnims_4_4
.4byte sNidorinoAnims_4_5
.4byte sNidorinoAnims_4_6
.4byte sNidorinoAnims_4_7
.4byte sNidorinoAnims_4_8
sNidorinoAnimTable5:
.4byte sNidorinoAnims_5_1
.4byte sNidorinoAnims_5_2
.4byte sNidorinoAnims_5_3
.4byte sNidorinoAnims_5_4
.4byte sNidorinoAnims_5_5
.4byte sNidorinoAnims_5_6
.4byte sNidorinoAnims_5_7
.4byte sNidorinoAnims_5_8
sNidorinoAnimTable6:
.4byte sNidorinoAnims_6_1
.4byte sNidorinoAnims_6_1
.4byte sNidorinoAnims_6_1
.4byte sNidorinoAnims_6_1
.4byte sNidorinoAnims_6_1
.4byte sNidorinoAnims_6_1
.4byte sNidorinoAnims_6_1
.4byte sNidorinoAnims_6_1
sNidorinoAnimTable7:
.4byte sNidorinoAnims_7_1
.4byte sNidorinoAnims_7_2
.4byte sNidorinoAnims_7_3
.4byte sNidorinoAnims_7_4
.4byte sNidorinoAnims_7_5
.4byte sNidorinoAnims_7_6
.4byte sNidorinoAnims_7_7
.4byte sNidorinoAnims_7_8
sNidorinoAnimTable8:
.4byte sNidorinoAnims_8_1
.4byte sNidorinoAnims_8_2
.4byte sNidorinoAnims_8_3
.4byte sNidorinoAnims_8_4
.4byte sNidorinoAnims_8_5
.4byte sNidorinoAnims_8_6
.4byte sNidorinoAnims_8_7
.4byte sNidorinoAnims_8_8
sNidorinoAnimTable9:
.4byte sNidorinoAnims_9_1
.4byte sNidorinoAnims_9_2
.4byte sNidorinoAnims_9_3
.4byte sNidorinoAnims_9_4
.4byte sNidorinoAnims_9_5
.4byte sNidorinoAnims_9_6
.4byte sNidorinoAnims_9_7
.4byte sNidorinoAnims_9_8
sNidorinoAnimTable10:
.4byte sNidorinoAnims_10_1
.4byte sNidorinoAnims_10_2
.4byte sNidorinoAnims_10_3
.4byte sNidorinoAnims_10_4
.4byte sNidorinoAnims_10_5
.4byte sNidorinoAnims_10_6
.4byte sNidorinoAnims_10_7
.4byte sNidorinoAnims_10_8
sNidorinoAnimTable11:
.4byte sNidorinoAnims_11_1
.4byte sNidorinoAnims_11_2
.4byte sNidorinoAnims_11_3
.4byte sNidorinoAnims_11_4
.4byte sNidorinoAnims_11_5
.4byte sNidorinoAnims_11_6
.4byte sNidorinoAnims_11_7
.4byte sNidorinoAnims_11_8
sNidorinoAnimTable12:
.4byte sNidorinoAnims_12_1
.4byte sNidorinoAnims_12_2
.4byte sNidorinoAnims_12_3
.4byte sNidorinoAnims_12_4
.4byte sNidorinoAnims_12_5
.4byte sNidorinoAnims_12_6
.4byte sNidorinoAnims_12_7
.4byte sNidorinoAnims_12_8
sNidorinoAnimTable13:
.4byte sNidorinoAnims_13_1
.4byte sNidorinoAnims_13_2
.4byte sNidorinoAnims_13_3
.4byte sNidorinoAnims_13_4
.4byte sNidorinoAnims_13_5
.4byte sNidorinoAnims_13_6
.4byte sNidorinoAnims_13_7
.4byte sNidorinoAnims_13_8
sAxAnimationsNidorino:
.4byte sNidorinoAnimTable1
.4byte sNidorinoAnimTable2
.4byte sNidorinoAnimTable3
.4byte sNidorinoAnimTable4
.4byte sNidorinoAnimTable5
.4byte sNidorinoAnimTable6
.4byte sNidorinoAnimTable7
.4byte sNidorinoAnimTable8
.4byte sNidorinoAnimTable9
.4byte sNidorinoAnimTable10
.4byte sNidorinoAnimTable11
.4byte sNidorinoAnimTable12
.4byte sNidorinoAnimTable13
sAxSpritesNidorino:
.4byte sNidorinoSprites1
.4byte sNidorinoSprites2
.4byte sNidorinoSprites3
.4byte sNidorinoSprites4
.4byte sNidorinoSprites5
.4byte sNidorinoSprites6
.4byte sNidorinoSprites7
.4byte sNidorinoSprites8
.4byte sNidorinoSprites9
.4byte sNidorinoSprites10
.4byte sNidorinoSprites11
.4byte sNidorinoSprites12
.4byte sNidorinoSprites13
.4byte sNidorinoSprites14
.4byte sNidorinoSprites15
.4byte sNidorinoSprites16
.4byte sNidorinoSprites17
.4byte sNidorinoSprites18
.4byte sNidorinoSprites19
.4byte sNidorinoSprites20
.4byte sNidorinoSprites21
.4byte sNidorinoSprites22
.4byte sNidorinoSprites23
.4byte sNidorinoSprites24
.4byte sNidorinoSprites25
.4byte sNidorinoSprites26
.4byte sNidorinoSprites27
.4byte sNidorinoSprites28
.4byte sNidorinoSprites29
.4byte sNidorinoSprites30
.4byte sNidorinoSprites31
.4byte sNidorinoSprites32
.4byte sNidorinoSprites33
.4byte sNidorinoSprites34
.4byte sNidorinoSprites35
.4byte sNidorinoSprites36
.4byte sNidorinoSprites37
.4byte sNidorinoSprites38
.4byte sNidorinoSprites39
.4byte sNidorinoSprites40
.4byte sNidorinoSprites41
.4byte sNidorinoSprites42
sAxMainNidorino:
ax_main sAxPosesNidorino, sAxAnimationsNidorino, 13, sAxSpritesNidorino, sAxPositionsNidorino
