.global gAxNidoqueen
gAxNidoqueen:
ax_siro sAxMainNidoqueen
sNidoqueenPose1:
ax_pose 0, 0x01eb, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose2:
ax_pose 1, 0x01eb, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose3:
ax_pose 2, 0x01eb, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose4:
ax_pose 3, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sNidoqueenPose5:
ax_pose 4, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sNidoqueenPose6:
ax_pose 5, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sNidoqueenPose7:
ax_pose 6, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sNidoqueenPose8:
ax_pose 7, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sNidoqueenPose9:
ax_pose 8, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sNidoqueenPose10:
ax_pose 9, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sNidoqueenPose11:
ax_pose 10, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sNidoqueenPose12:
ax_pose 11, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sNidoqueenPose13:
ax_pose 12, 0x01e4, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose14:
ax_pose 13, 0x01e4, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose15:
ax_pose 14, 0x01e4, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose16:
ax_pose 9, 0x01e4, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose17:
ax_pose 10, 0x01e4, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose18:
ax_pose 11, 0x01e4, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose19:
ax_pose 6, 0x01e4, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose20:
ax_pose 7, 0x01e4, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose21:
ax_pose 8, 0x01e4, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose22:
ax_pose 3, 0x01e4, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose23:
ax_pose 4, 0x01e4, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose24:
ax_pose 5, 0x01e4, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose25:
ax_pose 15, 0x01e6, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose26:
ax_pose 1, 0x01eb, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose27:
ax_pose 2, 0x01eb, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose28:
ax_pose 16, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sNidoqueenPose29:
ax_pose 4, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sNidoqueenPose30:
ax_pose 5, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sNidoqueenPose31:
ax_pose 17, 0x01e5, 0x90ef, 0x5c00
ax_pose_terminator
sNidoqueenPose32:
ax_pose 7, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sNidoqueenPose33:
ax_pose 8, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sNidoqueenPose34:
ax_pose 18, 0x01e6, 0x90ef, 0x5c00
ax_pose_terminator
sNidoqueenPose35:
ax_pose 10, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sNidoqueenPose36:
ax_pose 11, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sNidoqueenPose37:
ax_pose 19, 0x01e7, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose38:
ax_pose 13, 0x01e4, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose39:
ax_pose 14, 0x01e4, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose40:
ax_pose 18, 0x01e6, 0x80f1, 0x5c00
ax_pose_terminator
sNidoqueenPose41:
ax_pose 10, 0x01e4, 0x80f1, 0x5c00
ax_pose_terminator
sNidoqueenPose42:
ax_pose 11, 0x01e4, 0x80f1, 0x5c00
ax_pose_terminator
sNidoqueenPose43:
ax_pose 17, 0x01e5, 0x80f1, 0x5c00
ax_pose_terminator
sNidoqueenPose44:
ax_pose 7, 0x01e4, 0x80f1, 0x5c00
ax_pose_terminator
sNidoqueenPose45:
ax_pose 8, 0x01e4, 0x80f1, 0x5c00
ax_pose_terminator
sNidoqueenPose46:
ax_pose 16, 0x01e4, 0x80f1, 0x5c00
ax_pose_terminator
sNidoqueenPose47:
ax_pose 4, 0x01e4, 0x80f1, 0x5c00
ax_pose_terminator
sNidoqueenPose48:
ax_pose 5, 0x01e4, 0x80f1, 0x5c00
ax_pose_terminator
sNidoqueenPose49:
ax_pose 0, 0x01eb, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose50:
ax_pose 1, 0x01eb, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose51:
ax_pose 2, 0x01eb, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose52:
ax_pose 20, 0x01eb, 0x80ee, 0x5c00
ax_pose 21, 0x01eb, 0x80f0, 0x5c10
ax_pose_terminator
sNidoqueenPose53:
ax_pose 21, 0x01eb, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose54:
ax_pose 22, 0x01eb, 0x80f1, 0x5c00
ax_pose 23, 0x01eb, 0x80ef, 0x5c10
ax_pose_terminator
sNidoqueenPose55:
ax_pose 23, 0x01eb, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose56:
ax_pose 3, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sNidoqueenPose57:
ax_pose 4, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sNidoqueenPose58:
ax_pose 5, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sNidoqueenPose59:
ax_pose 24, 0x01e6, 0x90f4, 0x5c00
ax_pose 25, 0x01e4, 0x90ef, 0x5c10
ax_pose_terminator
sNidoqueenPose60:
ax_pose 25, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sNidoqueenPose61:
ax_pose 26, 0x81e6, 0x9100, 0x5c00
ax_pose 27, 0x01e4, 0x90ef, 0x5c08
ax_pose_terminator
sNidoqueenPose62:
ax_pose 27, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sNidoqueenPose63:
ax_pose 6, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sNidoqueenPose64:
ax_pose 7, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sNidoqueenPose65:
ax_pose 8, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sNidoqueenPose66:
ax_pose 28, 0x01e4, 0x90f1, 0x5c00
ax_pose 29, 0x01e4, 0x90ef, 0x5c10
ax_pose_terminator
sNidoqueenPose67:
ax_pose 29, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sNidoqueenPose68:
ax_pose 30, 0x01e4, 0x90f2, 0x5c00
ax_pose 31, 0x01e4, 0x90ef, 0x5c10
ax_pose_terminator
sNidoqueenPose69:
ax_pose 31, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sNidoqueenPose70:
ax_pose 9, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sNidoqueenPose71:
ax_pose 10, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sNidoqueenPose72:
ax_pose 11, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sNidoqueenPose73:
ax_pose 32, 0x81e3, 0x9104, 0x5c00
ax_pose 33, 0x01e4, 0x90ef, 0x5c08
ax_pose_terminator
sNidoqueenPose74:
ax_pose 33, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sNidoqueenPose75:
ax_pose 34, 0x01e4, 0x90ef, 0x5c00
ax_pose 35, 0x41e5, 0x90f1, 0x5c10
ax_pose 36, 0x41f5, 0x1101, 0x5c18
ax_pose_terminator
sNidoqueenPose76:
ax_pose 34, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sNidoqueenPose77:
ax_pose 12, 0x01e4, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose78:
ax_pose 13, 0x01e4, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose79:
ax_pose 14, 0x01e4, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose80:
ax_pose 37, 0x01e4, 0x80f0, 0x5c00
ax_pose 38, 0x01e4, 0x80f3, 0x5c10
ax_pose_terminator
sNidoqueenPose81:
ax_pose 37, 0x01e4, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose82:
ax_pose 39, 0x01e4, 0x80f0, 0x5c00
ax_pose 38, 0x01e4, 0x90ed, 0x5c10
ax_pose_terminator
sNidoqueenPose83:
ax_pose 39, 0x01e4, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose84:
ax_pose 9, 0x01e4, 0x80f1, 0x5c00
ax_pose_terminator
sNidoqueenPose85:
ax_pose 10, 0x01e4, 0x80f1, 0x5c00
ax_pose_terminator
sNidoqueenPose86:
ax_pose 11, 0x01e4, 0x80f1, 0x5c00
ax_pose_terminator
sNidoqueenPose87:
ax_pose 32, 0x81e3, 0x80ec, 0x5c00
ax_pose 33, 0x01e4, 0x80f1, 0x5c08
ax_pose_terminator
sNidoqueenPose88:
ax_pose 33, 0x01e4, 0x80f1, 0x5c00
ax_pose_terminator
sNidoqueenPose89:
ax_pose 34, 0x01e4, 0x80f1, 0x5c00
ax_pose 35, 0x41e5, 0x80ef, 0x5c10
ax_pose 36, 0x41f5, 0x00ef, 0x5c18
ax_pose_terminator
sNidoqueenPose90:
ax_pose 34, 0x01e4, 0x80f1, 0x5c00
ax_pose_terminator
sNidoqueenPose91:
ax_pose 6, 0x01e4, 0x80f1, 0x5c00
ax_pose_terminator
sNidoqueenPose92:
ax_pose 7, 0x01e4, 0x80f1, 0x5c00
ax_pose_terminator
sNidoqueenPose93:
ax_pose 8, 0x01e4, 0x80f1, 0x5c00
ax_pose_terminator
sNidoqueenPose94:
ax_pose 28, 0x01e4, 0x80ef, 0x5c00
ax_pose 29, 0x01e4, 0x80f1, 0x5c10
ax_pose_terminator
sNidoqueenPose95:
ax_pose 29, 0x01e4, 0x80f1, 0x5c00
ax_pose_terminator
sNidoqueenPose96:
ax_pose 30, 0x01e4, 0x80ee, 0x5c00
ax_pose 31, 0x01e4, 0x80f1, 0x5c10
ax_pose_terminator
sNidoqueenPose97:
ax_pose 31, 0x01e4, 0x80f1, 0x5c00
ax_pose_terminator
sNidoqueenPose98:
ax_pose 3, 0x01e4, 0x80f1, 0x5c00
ax_pose_terminator
sNidoqueenPose99:
ax_pose 4, 0x01e4, 0x80f1, 0x5c00
ax_pose_terminator
sNidoqueenPose100:
ax_pose 5, 0x01e4, 0x80f1, 0x5c00
ax_pose_terminator
sNidoqueenPose101:
ax_pose 24, 0x01e6, 0x80ec, 0x5c00
ax_pose 25, 0x01e4, 0x80f1, 0x5c10
ax_pose_terminator
sNidoqueenPose102:
ax_pose 25, 0x01e4, 0x80f1, 0x5c00
ax_pose_terminator
sNidoqueenPose103:
ax_pose 26, 0x81e6, 0x80f0, 0x5c00
ax_pose 27, 0x01e4, 0x80f1, 0x5c08
ax_pose_terminator
sNidoqueenPose104:
ax_pose 27, 0x01e4, 0x80f1, 0x5c00
ax_pose_terminator
sNidoqueenPose105:
ax_pose 0, 0x01eb, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose106:
ax_pose 40, 0x01e6, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose107:
ax_pose 15, 0x01e6, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose108:
ax_pose 3, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sNidoqueenPose109:
ax_pose 41, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sNidoqueenPose110:
ax_pose 16, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sNidoqueenPose111:
ax_pose 6, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sNidoqueenPose112:
ax_pose 42, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sNidoqueenPose113:
ax_pose 17, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sNidoqueenPose114:
ax_pose 9, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sNidoqueenPose115:
ax_pose 43, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sNidoqueenPose116:
ax_pose 18, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sNidoqueenPose117:
ax_pose 12, 0x01e4, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose118:
ax_pose 44, 0x01e5, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose119:
ax_pose 19, 0x01e5, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose120:
ax_pose 9, 0x01e4, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose121:
ax_pose 43, 0x01e4, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose122:
ax_pose 18, 0x01e4, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose123:
ax_pose 6, 0x01e4, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose124:
ax_pose 42, 0x01e4, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose125:
ax_pose 17, 0x01e4, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose126:
ax_pose 3, 0x01e4, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose127:
ax_pose 41, 0x01e4, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose128:
ax_pose 16, 0x01e4, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose129:
ax_pose 0, 0x01eb, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose130:
ax_pose 3, 0x01e4, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose131:
ax_pose 6, 0x01e4, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose132:
ax_pose 9, 0x01e4, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose133:
ax_pose 12, 0x01e4, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose134:
ax_pose 9, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sNidoqueenPose135:
ax_pose 6, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sNidoqueenPose136:
ax_pose 3, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sNidoqueenPose137:
ax_pose 45, 0x01e4, 0x80f2, 0x5c00
ax_pose_terminator
sNidoqueenPose138:
ax_pose 46, 0x01e4, 0x80f2, 0x5c00
ax_pose_terminator
sNidoqueenPose139:
ax_pose 47, 0x01e5, 0x80f1, 0x5c00
ax_pose_terminator
sNidoqueenPose140:
ax_pose 48, 0x01e4, 0x90ee, 0x5c00
ax_pose_terminator
sNidoqueenPose141:
ax_pose 49, 0x01e4, 0x90eb, 0x5c00
ax_pose_terminator
sNidoqueenPose142:
ax_pose 50, 0x01e3, 0x90ef, 0x5c00
ax_pose_terminator
sNidoqueenPose143:
ax_pose 51, 0x01e5, 0x80f1, 0x5c00
ax_pose_terminator
sNidoqueenPose144:
ax_pose 50, 0x01e3, 0x80f1, 0x5c00
ax_pose_terminator
sNidoqueenPose145:
ax_pose 49, 0x01e4, 0x80f5, 0x5c00
ax_pose_terminator
sNidoqueenPose146:
ax_pose 48, 0x01e4, 0x80f2, 0x5c00
ax_pose_terminator
sNidoqueenPose147:
ax_pose 0, 0x01eb, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose148:
ax_pose 1, 0x01eb, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose149:
ax_pose 2, 0x01eb, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose150:
ax_pose 3, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sNidoqueenPose151:
ax_pose 4, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sNidoqueenPose152:
ax_pose 5, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sNidoqueenPose153:
ax_pose 6, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sNidoqueenPose154:
ax_pose 7, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sNidoqueenPose155:
ax_pose 8, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sNidoqueenPose156:
ax_pose 9, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sNidoqueenPose157:
ax_pose 10, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sNidoqueenPose158:
ax_pose 11, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sNidoqueenPose159:
ax_pose 12, 0x01e4, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose160:
ax_pose 13, 0x01e4, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose161:
ax_pose 14, 0x01e4, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose162:
ax_pose 9, 0x01e4, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose163:
ax_pose 10, 0x01e4, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose164:
ax_pose 11, 0x01e4, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose165:
ax_pose 6, 0x01e4, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose166:
ax_pose 7, 0x01e4, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose167:
ax_pose 8, 0x01e4, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose168:
ax_pose 3, 0x01e4, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose169:
ax_pose 4, 0x01e4, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose170:
ax_pose 5, 0x01e4, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose171:
ax_pose 15, 0x01e6, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose172:
ax_pose 16, 0x01e4, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose173:
ax_pose 17, 0x01e4, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose174:
ax_pose 18, 0x01e4, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose175:
ax_pose 19, 0x01e5, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose176:
ax_pose 18, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sNidoqueenPose177:
ax_pose 17, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sNidoqueenPose178:
ax_pose 16, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sNidoqueenPose179:
ax_pose 15, 0x01e6, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose180:
ax_pose 16, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sNidoqueenPose181:
ax_pose 17, 0x01e4, 0x90ed, 0x5c00
ax_pose_terminator
sNidoqueenPose182:
ax_pose 18, 0x01e5, 0x90ef, 0x5c00
ax_pose_terminator
sNidoqueenPose183:
ax_pose 19, 0x01e5, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose184:
ax_pose 18, 0x01e5, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose185:
ax_pose 17, 0x01e4, 0x80f2, 0x5c00
ax_pose_terminator
sNidoqueenPose186:
ax_pose 16, 0x01e4, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose187:
ax_pose 0, 0x01eb, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose188:
ax_pose 40, 0x01e6, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose189:
ax_pose 15, 0x01e6, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose190:
ax_pose 3, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sNidoqueenPose191:
ax_pose 41, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sNidoqueenPose192:
ax_pose 16, 0x01e4, 0x90ee, 0x5c00
ax_pose_terminator
sNidoqueenPose193:
ax_pose 6, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sNidoqueenPose194:
ax_pose 42, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sNidoqueenPose195:
ax_pose 17, 0x01e4, 0x90ec, 0x5c00
ax_pose_terminator
sNidoqueenPose196:
ax_pose 9, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sNidoqueenPose197:
ax_pose 43, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sNidoqueenPose198:
ax_pose 18, 0x01e5, 0x90ed, 0x5c00
ax_pose_terminator
sNidoqueenPose199:
ax_pose 12, 0x01e4, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose200:
ax_pose 44, 0x01e5, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose201:
ax_pose 19, 0x01e5, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose202:
ax_pose 9, 0x01e4, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose203:
ax_pose 43, 0x01e4, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose204:
ax_pose 18, 0x01e5, 0x80f2, 0x5c00
ax_pose_terminator
sNidoqueenPose205:
ax_pose 6, 0x01e4, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose206:
ax_pose 42, 0x01e4, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose207:
ax_pose 17, 0x01e4, 0x80f3, 0x5c00
ax_pose_terminator
sNidoqueenPose208:
ax_pose 3, 0x01e4, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose209:
ax_pose 41, 0x01e4, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose210:
ax_pose 16, 0x01e4, 0x80f1, 0x5c00
ax_pose_terminator
sNidoqueenPose211:
ax_pose 15, 0x01e6, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose212:
ax_pose 16, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sNidoqueenPose213:
ax_pose 17, 0x01e4, 0x90ed, 0x5c00
ax_pose_terminator
sNidoqueenPose214:
ax_pose 18, 0x01e5, 0x90ef, 0x5c00
ax_pose_terminator
sNidoqueenPose215:
ax_pose 19, 0x01e5, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose216:
ax_pose 18, 0x01e5, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose217:
ax_pose 17, 0x01e4, 0x80f2, 0x5c00
ax_pose_terminator
sNidoqueenPose218:
ax_pose 16, 0x01e4, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose219:
ax_pose 0, 0x01eb, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose220:
ax_pose 3, 0x01e4, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose221:
ax_pose 6, 0x01e4, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose222:
ax_pose 9, 0x01e4, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose223:
ax_pose 12, 0x01e4, 0x80f0, 0x5c00
ax_pose_terminator
sNidoqueenPose224:
ax_pose 9, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sNidoqueenPose225:
ax_pose 6, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
sNidoqueenPose226:
ax_pose 3, 0x01e4, 0x90ef, 0x5c00
ax_pose_terminator
.align 2
sNidoqueenAnims_1_1:
ax_anim 8, 0, 0, 0, 0, 0, 0,
ax_anim 10, 0, 1, 0, 0, 0, 0,
ax_anim 8, 0, 0, 0, 0, 0, 0,
ax_anim 10, 0, 2, 0, 0, 0, 0,
ax_anim_terminator
sNidoqueenAnims_1_2:
ax_anim 8, 0, 3, 0, 0, 0, 0,
ax_anim 10, 0, 4, 0, 0, 0, 0,
ax_anim 8, 0, 3, 0, 0, 0, 0,
ax_anim 10, 0, 5, 0, 0, 0, 0,
ax_anim_terminator
sNidoqueenAnims_1_3:
ax_anim 8, 0, 6, 0, 0, 0, 0,
ax_anim 10, 0, 7, 0, 0, 0, 0,
ax_anim 8, 0, 6, 0, 0, 0, 0,
ax_anim 10, 0, 8, 0, 0, 0, 0,
ax_anim_terminator
sNidoqueenAnims_1_4:
ax_anim 8, 0, 9, 0, 0, 0, 0,
ax_anim 10, 0, 10, 0, 0, 0, 0,
ax_anim 8, 0, 9, 0, 0, 0, 0,
ax_anim 10, 0, 11, 0, 0, 0, 0,
ax_anim_terminator
sNidoqueenAnims_1_5:
ax_anim 8, 0, 12, 0, 0, 0, 0,
ax_anim 10, 0, 13, 0, 0, 0, 0,
ax_anim 8, 0, 12, 0, 0, 0, 0,
ax_anim 10, 0, 14, 0, 0, 0, 0,
ax_anim_terminator
sNidoqueenAnims_1_6:
ax_anim 8, 0, 15, 0, 0, 0, 0,
ax_anim 10, 0, 16, 0, 0, 0, 0,
ax_anim 8, 0, 15, 0, 0, 0, 0,
ax_anim 10, 0, 17, 0, 0, 0, 0,
ax_anim_terminator
sNidoqueenAnims_1_7:
ax_anim 8, 0, 18, 0, 0, 0, 0,
ax_anim 10, 0, 19, 0, 0, 0, 0,
ax_anim 8, 0, 18, 0, 0, 0, 0,
ax_anim 10, 0, 20, 0, 0, 0, 0,
ax_anim_terminator
sNidoqueenAnims_1_8:
ax_anim 8, 0, 21, 0, 0, 0, 0,
ax_anim 10, 0, 22, 0, 0, 0, 0,
ax_anim 8, 0, 21, 0, 0, 0, 0,
ax_anim 10, 0, 23, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sNidoqueenAnims_2_1:
ax_anim 2, 0, 25, 0, -1, 0, -1,
ax_anim 6, 0, 25, 0, -2, 0, -2,
ax_anim 1, 2, 24, 0, 4, 0, 4,
ax_anim 1, 0, 24, 0, 10, 0, 10,
ax_anim 2, 0, 24, 0, 20, 0, 20,
ax_anim 2, 1, 24, 1, 20, 1, 20,
ax_anim 2, 0, 24, 0, 20, 0, 20,
ax_anim 2, 0, 24, 1, 20, 1, 20,
ax_anim 2, 0, 25, 0, 6, 0, 6,
ax_anim_terminator
sNidoqueenAnims_2_2:
ax_anim 2, 0, 28, -1, -1, -1, -1,
ax_anim 6, 0, 28, -2, -2, -2, -2,
ax_anim 1, 2, 27, 4, 4, 4, 4,
ax_anim 1, 0, 27, 10, 11, 10, 11,
ax_anim 2, 0, 27, 18, 20, 18, 20,
ax_anim 2, 1, 27, 19, 19, 19, 19,
ax_anim 2, 0, 27, 18, 20, 18, 20,
ax_anim 2, 0, 27, 19, 19, 19, 19,
ax_anim 2, 0, 28, 8, 8, 8, 8,
ax_anim_terminator
sNidoqueenAnims_2_3:
ax_anim 2, 0, 31, -1, 0, -1, 0,
ax_anim 6, 0, 31, -2, 0, -2, 0,
ax_anim 1, 2, 30, 4, 0, 4, 0,
ax_anim 1, 0, 30, 10, 0, 10, 0,
ax_anim 2, 0, 30, 18, 0, 18, 0,
ax_anim 2, 1, 30, 18, 1, 18, 1,
ax_anim 2, 0, 30, 18, 0, 18, 0,
ax_anim 2, 0, 30, 18, 1, 18, 1,
ax_anim 2, 0, 31, 6, 0, 6, 0,
ax_anim_terminator
sNidoqueenAnims_2_4:
ax_anim 2, 0, 34, -1, 1, -1, 1,
ax_anim 6, 0, 34, -2, 2, -2, 2,
ax_anim 1, 2, 33, 4, -6, 4, -6,
ax_anim 1, 0, 33, 11, -12, 11, -12,
ax_anim 2, 0, 33, 19, -20, 19, -20,
ax_anim 2, 1, 33, 20, -19, 20, -19,
ax_anim 2, 0, 33, 19, -20, 19, -20,
ax_anim 2, 0, 33, 20, -19, 20, -19,
ax_anim 2, 0, 34, 6, -6, 6, -6,
ax_anim_terminator
sNidoqueenAnims_2_5:
ax_anim 2, 0, 37, 0, 1, 0, 1,
ax_anim 6, 0, 37, 0, 2, 0, 2,
ax_anim 1, 2, 36, 0, -4, 0, -4,
ax_anim 1, 0, 36, 0, -11, 0, -11,
ax_anim 2, 0, 36, 0, -20, 0, -20,
ax_anim 2, 1, 36, 1, -20, 1, -20,
ax_anim 2, 0, 36, 0, -20, 0, -20,
ax_anim 2, 0, 36, 1, -20, 1, -20,
ax_anim 2, 0, 37, 0, -6, 0, -6,
ax_anim_terminator
sNidoqueenAnims_2_6:
ax_anim 2, 0, 40, 1, 1, 1, 1,
ax_anim 6, 0, 40, 2, 2, 2, 2,
ax_anim 1, 2, 39, -4, -6, -4, -6,
ax_anim 1, 0, 39, -11, -12, -11, -12,
ax_anim 2, 0, 39, -18, -20, -18, -20,
ax_anim 2, 1, 39, -19, -19, -19, -19,
ax_anim 2, 0, 39, -18, -20, -18, -20,
ax_anim 2, 0, 39, -19, -19, -19, -19,
ax_anim 2, 0, 40, -6, -6, -6, -6,
ax_anim_terminator
sNidoqueenAnims_2_7:
ax_anim 2, 0, 43, 1, 0, 1, 0,
ax_anim 6, 0, 43, 2, 0, 2, 0,
ax_anim 1, 2, 42, -4, 0, -4, 0,
ax_anim 1, 0, 42, -10, 0, -10, 0,
ax_anim 2, 0, 42, -18, 0, -18, 0,
ax_anim 2, 1, 42, -18, 1, -18, 1,
ax_anim 2, 0, 42, -18, 0, -18, 0,
ax_anim 2, 0, 42, -18, 1, -18, 1,
ax_anim 2, 0, 43, -6, 0, -6, 0,
ax_anim_terminator
sNidoqueenAnims_2_8:
ax_anim 2, 0, 46, 1, -1, 1, -1,
ax_anim 6, 0, 46, 2, -2, 2, -2,
ax_anim 1, 2, 45, -4, 4, -4, 4,
ax_anim 1, 0, 45, -10, 11, -10, 11,
ax_anim 2, 0, 45, -18, 20, -18, 20,
ax_anim 2, 1, 45, -19, 19, -19, 19,
ax_anim 2, 0, 45, -18, 20, -18, 20,
ax_anim 2, 0, 45, -19, 19, -19, 19,
ax_anim 2, 0, 46, -8, 8, -8, 8,
ax_anim_terminator
.align 2
sNidoqueenAnims_3_1:
ax_anim 2, 0, 50, 0, -2, 0, -2,
ax_anim 4, 0, 54, 0, -4, 0, -4,
ax_anim 1, 0, 54, 0, -2, 0, -2,
ax_anim 2, 2, 54, 0, 5, 0, 5,
ax_anim 2, 0, 51, 0, 17, 0, 17,
ax_anim 2, 1, 52, -1, 18, -1, 18,
ax_anim 2, 0, 53, 0, 17, 0, 17,
ax_anim 2, 0, 54, 1, 18, 1, 18,
ax_anim 2, 0, 51, 0, 17, 0, 17,
ax_anim 2, 0, 52, -1, 18, -1, 18,
ax_anim 1, 0, 49, 0, 10, 0, 10,
ax_anim 1, 0, 50, 0, 4, 0, 4,
ax_anim_terminator
sNidoqueenAnims_3_2:
ax_anim 2, 0, 57, -2, -2, -2, -2,
ax_anim 4, 0, 61, -4, -4, -4, -4,
ax_anim 1, 0, 61, -2, -2, -2, -2,
ax_anim 2, 2, 61, 5, 5, 5, 5,
ax_anim 2, 0, 58, 17, 17, 17, 17,
ax_anim 2, 1, 59, 20, 17, 20, 17,
ax_anim 2, 0, 60, 17, 17, 17, 17,
ax_anim 2, 0, 61, 16, 18, 16, 18,
ax_anim 2, 0, 58, 17, 17, 17, 17,
ax_anim 2, 0, 59, 20, 17, 20, 17,
ax_anim 1, 0, 56, 10, 10, 10, 10,
ax_anim 1, 0, 57, 4, 4, 4, 4,
ax_anim_terminator
sNidoqueenAnims_3_3:
ax_anim 2, 0, 64, -2, 0, -2, 0,
ax_anim 4, 0, 68, -4, 0, -4, 0,
ax_anim 1, 0, 68, -2, 0, -2, 0,
ax_anim 2, 2, 68, 5, 0, 5, 0,
ax_anim 2, 0, 65, 14, 0, 14, 0,
ax_anim 2, 1, 66, 15, 0, 15, 0,
ax_anim 2, 0, 67, 14, 0, 14, 0,
ax_anim 2, 0, 68, 15, 1, 15, 1,
ax_anim 2, 0, 65, 14, 0, 14, 0,
ax_anim 2, 0, 66, 15, -1, 15, -1,
ax_anim 1, 0, 63, 10, 0, 10, 0,
ax_anim 1, 0, 64, 4, 0, 4, 0,
ax_anim_terminator
sNidoqueenAnims_3_4:
ax_anim 2, 0, 71, -2, 2, -2, 2,
ax_anim 4, 0, 75, -4, 4, -4, 4,
ax_anim 1, 0, 75, -2, 2, -2, 2,
ax_anim 2, 2, 75, 5, -5, 5, -5,
ax_anim 2, 0, 72, 15, -17, 15, -17,
ax_anim 2, 1, 73, 15, -19, 15, -19,
ax_anim 2, 0, 74, 15, -17, 15, -17,
ax_anim 2, 0, 75, 17, -17, 17, -17,
ax_anim 2, 0, 72, 15, -17, 15, -17,
ax_anim 2, 0, 73, 15, -19, 15, -19,
ax_anim 1, 0, 70, 10, -10, 10, -10,
ax_anim 1, 0, 71, 4, -4, 4, -4,
ax_anim_terminator
sNidoqueenAnims_3_5:
ax_anim 2, 0, 78, 0, 2, 0, 2,
ax_anim 4, 0, 82, 0, 4, 0, 4,
ax_anim 1, 0, 82, 0, 2, 0, 2,
ax_anim 2, 2, 82, 0, -5, 0, -5,
ax_anim 2, 0, 79, 0, -13, 0, -13,
ax_anim 2, 1, 80, 1, -14, 1, -14,
ax_anim 2, 0, 81, 0, -13, 0, -13,
ax_anim 2, 0, 82, -1, -14, -1, -14,
ax_anim 2, 0, 79, 0, -13, 0, -13,
ax_anim 2, 0, 80, 1, -14, 1, -14,
ax_anim 1, 0, 77, 0, -10, 0, -10,
ax_anim 1, 0, 78, 0, -4, 0, -4,
ax_anim_terminator
sNidoqueenAnims_3_6:
ax_anim 2, 0, 85, 2, 2, 2, 2,
ax_anim 4, 0, 89, 4, 4, 4, 4,
ax_anim 1, 0, 89, 2, 2, 2, 2,
ax_anim 2, 2, 89, -5, -5, -5, -5,
ax_anim 2, 0, 86, -15, -17, -15, -17,
ax_anim 2, 1, 87, -15, -19, -15, -19,
ax_anim 2, 0, 88, -15, -17, -15, -17,
ax_anim 2, 0, 89, -17, -17, -17, -17,
ax_anim 2, 0, 86, -15, -17, -15, -17,
ax_anim 2, 0, 87, -15, -19, -15, -19,
ax_anim 1, 0, 84, -10, -10, -10, -10,
ax_anim 1, 0, 85, -4, -4, -4, -4,
ax_anim_terminator
sNidoqueenAnims_3_7:
ax_anim 2, 0, 92, 2, 0, 2, 0,
ax_anim 4, 0, 96, 4, 0, 4, 0,
ax_anim 1, 0, 96, 2, 0, 2, 0,
ax_anim 2, 2, 96, -5, 0, -5, 0,
ax_anim 2, 0, 93, -14, 0, -14, 0,
ax_anim 2, 1, 94, -15, 0, -15, 0,
ax_anim 2, 0, 95, -14, 0, -14, 0,
ax_anim 2, 0, 96, -15, 1, -15, 1,
ax_anim 2, 0, 93, -14, 0, -14, 0,
ax_anim 2, 0, 94, -15, -1, -15, -1,
ax_anim 1, 0, 91, -10, 0, -10, 0,
ax_anim 1, 0, 92, -4, 0, -4, 0,
ax_anim_terminator
sNidoqueenAnims_3_8:
ax_anim 2, 0, 99, 2, -2, 2, -2,
ax_anim 4, 0, 103, 4, -4, 4, -4,
ax_anim 1, 0, 103, 2, -2, 2, -2,
ax_anim 2, 2, 103, -5, 5, -5, 5,
ax_anim 2, 0, 100, -17, 17, -17, 17,
ax_anim 2, 1, 101, -20, 17, -20, 17,
ax_anim 2, 0, 102, -17, 17, -17, 17,
ax_anim 2, 0, 103, -16, 18, -16, 18,
ax_anim 2, 0, 100, -17, 17, -17, 17,
ax_anim 2, 0, 101, -20, 17, -20, 17,
ax_anim 1, 0, 98, -10, 10, -10, 10,
ax_anim 1, 0, 99, -4, 4, -4, 4,
ax_anim_terminator
.align 2
sNidoqueenAnims_4_1:
ax_anim 2, 0, 105, 0, -1, 0, -1,
ax_anim 2, 0, 105, 0, -3, 0, -3,
ax_anim 4, 0, 105, 0, -4, 0, -4,
ax_anim 1, 0, 105, 0, -3, 0, -3,
ax_anim 1, 2, 106, 0, 2, 0, 2,
ax_anim 2, 0, 106, 0, 5, 0, 5,
ax_anim 2, 0, 106, 1, 5, 1, 5,
ax_anim 2, 0, 106, 0, 5, 0, 5,
ax_anim 2, 1, 106, 1, 5, 1, 5,
ax_anim 2, 0, 106, 0, 5, 0, 5,
ax_anim 2, 0, 106, 1, 5, 1, 5,
ax_anim 2, 0, 106, 0, 5, 0, 5,
ax_anim 2, 0, 106, 1, 5, 1, 5,
ax_anim 2, 0, 104, 0, 2, 0, 2,
ax_anim_terminator
sNidoqueenAnims_4_2:
ax_anim 2, 0, 108, -1, -1, -1, -1,
ax_anim 2, 0, 108, -3, -3, -3, -3,
ax_anim 4, 0, 108, -4, -4, -4, -4,
ax_anim 1, 0, 108, -3, -3, -3, -3,
ax_anim 1, 2, 109, 2, 2, 2, 2,
ax_anim 2, 0, 109, 5, 5, 5, 5,
ax_anim 2, 0, 109, 6, 4, 6, 4,
ax_anim 2, 0, 109, 5, 5, 5, 5,
ax_anim 2, 1, 109, 6, 4, 6, 4,
ax_anim 2, 0, 109, 5, 5, 5, 5,
ax_anim 2, 0, 109, 6, 4, 6, 4,
ax_anim 2, 0, 109, 5, 5, 5, 5,
ax_anim 2, 0, 109, 6, 4, 6, 4,
ax_anim 2, 0, 107, 2, 2, 2, 2,
ax_anim_terminator
sNidoqueenAnims_4_3:
ax_anim 2, 0, 111, -1, 0, -1, 0,
ax_anim 2, 0, 111, -3, 0, -3, 0,
ax_anim 4, 0, 111, -4, 0, -4, 0,
ax_anim 1, 0, 111, -3, 0, -3, 0,
ax_anim 1, 2, 112, 2, 0, 2, 0,
ax_anim 2, 0, 112, 5, 0, 5, 0,
ax_anim 2, 0, 112, 5, 1, 5, 1,
ax_anim 2, 0, 112, 5, 0, 5, 0,
ax_anim 2, 1, 112, 5, 1, 5, 1,
ax_anim 2, 0, 112, 5, 0, 5, 0,
ax_anim 2, 0, 112, 5, 1, 5, 1,
ax_anim 2, 0, 112, 5, 0, 5, 0,
ax_anim 2, 0, 112, 5, 1, 5, 1,
ax_anim 2, 0, 110, 2, 0, 2, 0,
ax_anim_terminator
sNidoqueenAnims_4_4:
ax_anim 2, 0, 114, -1, 1, -1, 1,
ax_anim 2, 0, 114, -3, 3, -3, 3,
ax_anim 4, 0, 114, -4, 4, -4, 4,
ax_anim 1, 0, 114, -3, 3, -3, 3,
ax_anim 1, 2, 115, 2, -2, 2, -2,
ax_anim 2, 0, 115, 5, -5, 5, -5,
ax_anim 2, 0, 115, 6, -4, 6, -4,
ax_anim 2, 0, 115, 5, -5, 5, -5,
ax_anim 2, 1, 115, 6, -4, 6, -4,
ax_anim 2, 0, 115, 5, -5, 5, -5,
ax_anim 2, 0, 115, 6, -4, 6, -4,
ax_anim 2, 0, 115, 5, -5, 5, -5,
ax_anim 2, 0, 115, 6, -4, 6, -4,
ax_anim 2, 0, 113, 2, -2, 2, -2,
ax_anim_terminator
sNidoqueenAnims_4_5:
ax_anim 2, 0, 117, 0, 1, 0, 1,
ax_anim 2, 0, 117, 0, 3, 0, 3,
ax_anim 4, 0, 117, 0, 4, 0, 4,
ax_anim 1, 0, 117, 0, 3, 0, 3,
ax_anim 1, 2, 118, 0, -2, 0, -2,
ax_anim 2, 0, 118, 0, -5, 0, -5,
ax_anim 2, 0, 118, 1, -5, 1, -5,
ax_anim 2, 0, 118, 0, -5, 0, -5,
ax_anim 2, 1, 118, 1, -5, 1, -5,
ax_anim 2, 0, 118, 0, -5, 0, -5,
ax_anim 2, 0, 118, 1, -5, 1, -5,
ax_anim 2, 0, 118, 0, -5, 0, -5,
ax_anim 2, 0, 118, 1, -5, 1, -5,
ax_anim 2, 0, 116, 0, -2, 0, -2,
ax_anim_terminator
sNidoqueenAnims_4_6:
ax_anim 2, 0, 120, 1, 1, 1, 1,
ax_anim 2, 0, 120, 3, 3, 3, 3,
ax_anim 4, 0, 120, 4, 4, 4, 4,
ax_anim 1, 0, 120, 3, 3, 3, 3,
ax_anim 1, 2, 121, -2, -2, -2, -2,
ax_anim 2, 0, 121, -5, -5, -5, -5,
ax_anim 2, 0, 121, -6, -4, -6, -4,
ax_anim 2, 0, 121, -5, -5, -5, -5,
ax_anim 2, 1, 121, -6, -4, -6, -4,
ax_anim 2, 0, 121, -5, -5, -5, -5,
ax_anim 2, 0, 121, -6, -4, -6, -4,
ax_anim 2, 0, 121, -5, -5, -5, -5,
ax_anim 2, 0, 121, -6, -4, -6, -4,
ax_anim 2, 0, 119, -2, -2, -2, -2,
ax_anim_terminator
sNidoqueenAnims_4_7:
ax_anim 2, 0, 123, 1, 0, 1, 0,
ax_anim 2, 0, 123, 3, 0, 3, 0,
ax_anim 4, 0, 123, 4, 0, 4, 0,
ax_anim 1, 0, 123, 3, 0, 3, 0,
ax_anim 1, 2, 124, -2, 0, -2, 0,
ax_anim 2, 0, 124, -5, 0, -5, 0,
ax_anim 2, 0, 124, -5, 1, -5, 1,
ax_anim 2, 0, 124, -5, 0, -5, 0,
ax_anim 2, 1, 124, -5, 1, -5, 1,
ax_anim 2, 0, 124, -5, 0, -5, 0,
ax_anim 2, 0, 124, -5, 1, -5, 1,
ax_anim 2, 0, 124, -5, 0, -5, 0,
ax_anim 2, 0, 124, -5, 1, -5, 1,
ax_anim 2, 0, 122, -2, 0, -2, 0,
ax_anim_terminator
sNidoqueenAnims_4_8:
ax_anim 2, 0, 126, 1, -1, 1, -1,
ax_anim 2, 0, 126, 3, -3, 3, -3,
ax_anim 4, 0, 126, 4, -4, 4, -4,
ax_anim 1, 0, 126, 3, -3, 3, -3,
ax_anim 1, 2, 127, -2, 2, -2, 2,
ax_anim 2, 0, 127, -5, 5, -5, 5,
ax_anim 2, 0, 127, -6, 4, -6, 4,
ax_anim 2, 0, 127, -5, 5, -5, 5,
ax_anim 2, 1, 127, -6, 4, -6, 4,
ax_anim 2, 0, 127, -5, 5, -5, 5,
ax_anim 2, 0, 127, -6, 4, -6, 4,
ax_anim 2, 0, 127, -5, 5, -5, 5,
ax_anim 2, 0, 127, -6, 4, -6, 4,
ax_anim 2, 0, 125, -2, 2, -2, 2,
ax_anim_terminator
.align 2
sNidoqueenAnims_5_1:
ax_anim 2, 0, 128, 0, 0, 0, 0,
ax_anim 2, 0, 129, 0, 0, 0, 0,
ax_anim 2, 0, 130, 0, 0, 0, 0,
ax_anim 2, 0, 131, 0, 0, 0, 0,
ax_anim 2, 0, 132, 0, 0, 0, 0,
ax_anim 2, 0, 133, 0, 0, 0, 0,
ax_anim 2, 0, 134, 0, 0, 0, 0,
ax_anim 2, 0, 135, 0, 0, 0, 0,
ax_anim 2, 2, 128, 0, 0, 0, 0,
ax_anim_terminator
sNidoqueenAnims_5_2:
ax_anim 2, 0, 135, 0, 0, 0, 0,
ax_anim 2, 0, 128, 0, 0, 0, 0,
ax_anim 2, 0, 129, 0, 0, 0, 0,
ax_anim 2, 0, 130, 0, 0, 0, 0,
ax_anim 2, 0, 131, 0, 0, 0, 0,
ax_anim 2, 0, 132, 0, 0, 0, 0,
ax_anim 2, 0, 133, 0, 0, 0, 0,
ax_anim 2, 0, 134, 0, 0, 0, 0,
ax_anim 2, 2, 135, 0, 0, 0, 0,
ax_anim_terminator
sNidoqueenAnims_5_3:
ax_anim 2, 0, 134, 0, 0, 0, 0,
ax_anim 2, 0, 135, 0, 0, 0, 0,
ax_anim 2, 0, 128, 0, 0, 0, 0,
ax_anim 2, 0, 129, 0, 0, 0, 0,
ax_anim 2, 0, 130, 0, 0, 0, 0,
ax_anim 2, 0, 131, 0, 0, 0, 0,
ax_anim 2, 0, 132, 0, 0, 0, 0,
ax_anim 2, 0, 133, 0, 0, 0, 0,
ax_anim 2, 2, 134, 0, 0, 0, 0,
ax_anim_terminator
sNidoqueenAnims_5_4:
ax_anim 2, 0, 133, 0, 0, 0, 0,
ax_anim 2, 0, 134, 0, 0, 0, 0,
ax_anim 2, 0, 135, 0, 0, 0, 0,
ax_anim 2, 0, 128, 0, 0, 0, 0,
ax_anim 2, 0, 129, 0, 0, 0, 0,
ax_anim 2, 0, 130, 0, 0, 0, 0,
ax_anim 2, 0, 131, 0, 0, 0, 0,
ax_anim 2, 0, 132, 0, 0, 0, 0,
ax_anim 2, 2, 133, 0, 0, 0, 0,
ax_anim_terminator
sNidoqueenAnims_5_5:
ax_anim 2, 0, 132, 0, 0, 0, 0,
ax_anim 2, 0, 133, 0, 0, 0, 0,
ax_anim 2, 0, 134, 0, 0, 0, 0,
ax_anim 2, 0, 135, 0, 0, 0, 0,
ax_anim 2, 0, 128, 0, 0, 0, 0,
ax_anim 2, 0, 129, 0, 0, 0, 0,
ax_anim 2, 0, 130, 0, 0, 0, 0,
ax_anim 2, 0, 131, 0, 0, 0, 0,
ax_anim 2, 2, 132, 0, 0, 0, 0,
ax_anim_terminator
sNidoqueenAnims_5_6:
ax_anim 2, 0, 131, 0, 0, 0, 0,
ax_anim 2, 0, 132, 0, 0, 0, 0,
ax_anim 2, 0, 133, 0, 0, 0, 0,
ax_anim 2, 0, 134, 0, 0, 0, 0,
ax_anim 2, 0, 135, 0, 0, 0, 0,
ax_anim 2, 0, 128, 0, 0, 0, 0,
ax_anim 2, 0, 129, 0, 0, 0, 0,
ax_anim 2, 0, 130, 0, 0, 0, 0,
ax_anim 2, 2, 131, 0, 0, 0, 0,
ax_anim_terminator
sNidoqueenAnims_5_7:
ax_anim 2, 0, 130, 0, 0, 0, 0,
ax_anim 2, 0, 131, 0, 0, 0, 0,
ax_anim 2, 0, 132, 0, 0, 0, 0,
ax_anim 2, 0, 133, 0, 0, 0, 0,
ax_anim 2, 0, 134, 0, 0, 0, 0,
ax_anim 2, 0, 135, 0, 0, 0, 0,
ax_anim 2, 0, 128, 0, 0, 0, 0,
ax_anim 2, 0, 129, 0, 0, 0, 0,
ax_anim 2, 2, 130, 0, 0, 0, 0,
ax_anim_terminator
sNidoqueenAnims_5_8:
ax_anim 2, 0, 129, 0, 0, 0, 0,
ax_anim 2, 0, 130, 0, 0, 0, 0,
ax_anim 2, 0, 131, 0, 0, 0, 0,
ax_anim 2, 0, 132, 0, 0, 0, 0,
ax_anim 2, 0, 133, 0, 0, 0, 0,
ax_anim 2, 0, 134, 0, 0, 0, 0,
ax_anim 2, 0, 135, 0, 0, 0, 0,
ax_anim 2, 0, 128, 0, 0, 0, 0,
ax_anim 2, 2, 129, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sNidoqueenAnims_6_1:
ax_anim 30, 0, 136, 0, 0, 0, 0,
ax_anim 35, 0, 137, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sNidoqueenAnims_7_1:
ax_anim 2, 0, 138, 0, -2, 0, -2,
ax_anim 8, 0, 138, 0, -3, 0, -3,
ax_anim_terminator
sNidoqueenAnims_7_2:
ax_anim 2, 0, 139, -2, -2, -2, -2,
ax_anim 8, 0, 139, -3, -3, -3, -3,
ax_anim_terminator
sNidoqueenAnims_7_3:
ax_anim 2, 0, 140, -2, 0, -2, 0,
ax_anim 8, 0, 140, -3, 0, -3, 0,
ax_anim_terminator
sNidoqueenAnims_7_4:
ax_anim 2, 0, 141, -2, 2, -2, 2,
ax_anim 8, 0, 141, -3, 3, -3, 3,
ax_anim_terminator
sNidoqueenAnims_7_5:
ax_anim 2, 0, 142, 0, 2, 0, 2,
ax_anim 8, 0, 142, 0, 3, 0, 3,
ax_anim_terminator
sNidoqueenAnims_7_6:
ax_anim 2, 0, 143, 2, 2, 2, 2,
ax_anim 8, 0, 143, 3, 3, 3, 3,
ax_anim_terminator
sNidoqueenAnims_7_7:
ax_anim 2, 0, 144, 2, 0, 2, 0,
ax_anim 8, 0, 144, 3, 0, 3, 0,
ax_anim_terminator
sNidoqueenAnims_7_8:
ax_anim 2, 0, 145, 2, -2, 2, -2,
ax_anim 8, 0, 145, 3, -3, 3, -3,
ax_anim_terminator
.align 2
sNidoqueenAnims_8_1:
ax_anim 20, 0, 146, 0, 0, 0, 0,
ax_anim 6, 0, 147, 0, -1, 0, 0,
ax_anim 6, 0, 147, 0, -2, 0, 0,
ax_anim 6, 0, 146, 0, -1, 0, 0,
ax_anim 12, 0, 146, 0, 0, 0, 0,
ax_anim_terminator
sNidoqueenAnims_8_2:
ax_anim 20, 0, 149, 0, 0, 0, 0,
ax_anim 6, 0, 151, 0, -1, 0, 0,
ax_anim 6, 0, 151, 0, -2, 0, 0,
ax_anim 6, 0, 149, 0, -1, 0, 0,
ax_anim 12, 0, 149, 0, 0, 0, 0,
ax_anim_terminator
sNidoqueenAnims_8_3:
ax_anim 20, 0, 152, 0, 0, 0, 0,
ax_anim 6, 0, 153, 0, -1, 0, 0,
ax_anim 6, 0, 153, 0, -2, 0, 0,
ax_anim 6, 0, 152, 0, -1, 0, 0,
ax_anim 12, 0, 152, 0, 0, 0, 0,
ax_anim_terminator
sNidoqueenAnims_8_4:
ax_anim 20, 0, 155, 0, 0, 0, 0,
ax_anim 6, 0, 156, 0, -1, 0, 0,
ax_anim 6, 0, 156, 0, -2, 0, 0,
ax_anim 6, 0, 156, 0, -1, 0, 0,
ax_anim 12, 0, 155, 0, 0, 0, 0,
ax_anim_terminator
sNidoqueenAnims_8_5:
ax_anim 20, 0, 158, 0, 0, 0, 0,
ax_anim 6, 0, 160, 0, -1, 0, 0,
ax_anim 6, 0, 160, 0, -2, 0, 0,
ax_anim 6, 0, 160, 0, -1, 0, 0,
ax_anim 12, 0, 158, 0, 0, 0, 0,
ax_anim_terminator
sNidoqueenAnims_8_6:
ax_anim 20, 0, 161, 0, 0, 0, 0,
ax_anim 6, 0, 162, 0, -1, 0, 0,
ax_anim 6, 0, 162, 0, -2, 0, 0,
ax_anim 6, 0, 162, 0, -1, 0, 0,
ax_anim 12, 0, 161, 0, 0, 0, 0,
ax_anim_terminator
sNidoqueenAnims_8_7:
ax_anim 20, 0, 164, 0, 0, 0, 0,
ax_anim 6, 0, 165, 0, -1, 0, 0,
ax_anim 6, 0, 165, 0, -2, 0, 0,
ax_anim 6, 0, 165, 0, -1, 0, 0,
ax_anim 12, 0, 164, 0, 0, 0, 0,
ax_anim_terminator
sNidoqueenAnims_8_8:
ax_anim 20, 0, 167, 0, 0, 0, 0,
ax_anim 6, 0, 168, 0, -1, 0, 0,
ax_anim 6, 0, 168, 0, -2, 0, 0,
ax_anim 6, 0, 168, 0, -1, 0, 0,
ax_anim 12, 0, 167, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sNidoqueenAnims_9_1:
ax_anim 2, 0, 170, 0, 0, 0, 0,
ax_anim 1, 0, 171, 6, 4, 6, 4,
ax_anim 2, 0, 172, 10, 11, 10, 11,
ax_anim 2, 0, 173, 7, 19, 7, 19,
ax_anim 3, 0, 174, 0, 21, 0, 21,
ax_anim 2, 3, 175, -7, 19, -7, 19,
ax_anim 2, 0, 176, -10, 11, -10, 11,
ax_anim 1, 0, 177, -6, 4, -6, 4,
ax_anim 1, 0, 170, 0, 0, 0, 0,
ax_anim_terminator
sNidoqueenAnims_9_2:
ax_anim 2, 0, 177, 0, 0, 0, 0,
ax_anim 1, 0, 170, 6, 0, 6, 0,
ax_anim 2, 0, 171, 17, 3, 17, 3,
ax_anim 2, 0, 172, 24, 9, 24, 9,
ax_anim 3, 0, 173, 23, 21, 23, 21,
ax_anim 2, 3, 174, 11, 21, 11, 21,
ax_anim 2, 0, 175, 0, 16, 0, 16,
ax_anim 1, 0, 176, -2, 9, -2, 9,
ax_anim 1, 0, 177, 0, 0, 0, 0,
ax_anim_terminator
sNidoqueenAnims_9_3:
ax_anim 2, 0, 176, 0, 0, 0, 0,
ax_anim 1, 0, 177, 4, -6, 4, -6,
ax_anim 2, 0, 170, 11, -6, 11, -6,
ax_anim 2, 0, 171, 19, -4, 19, -4,
ax_anim 3, 0, 172, 23, 1, 23, 1,
ax_anim 2, 3, 173, 19, 6, 19, 6,
ax_anim 2, 0, 174, 12, 7, 12, 7,
ax_anim 1, 0, 175, 4, 5, 4, 5,
ax_anim 1, 0, 176, 0, 0, 0, 0,
ax_anim_terminator
sNidoqueenAnims_9_4:
ax_anim 2, 0, 175, 0, 0, 0, 0,
ax_anim 1, 0, 176, -1, -8, -1, -8,
ax_anim 2, 0, 177, 5, -18, 5, -18,
ax_anim 2, 0, 170, 13, -20, 13, -20,
ax_anim 3, 0, 171, 21, -22, 21, -22,
ax_anim 2, 3, 172, 22, -11, 22, -11,
ax_anim 2, 0, 173, 17, -4, 17, -4,
ax_anim 1, 0, 174, 7, -1, 7, -1,
ax_anim 1, 0, 175, 0, 0, 0, 0,
ax_anim_terminator
sNidoqueenAnims_9_5:
ax_anim 2, 0, 174, 0, 0, 0, 0,
ax_anim 1, 0, 175, -7, -2, -7, -2,
ax_anim 2, 0, 176, -11, -10, -11, -10,
ax_anim 2, 0, 177, -7, -18, -7, -18,
ax_anim 3, 0, 170, 0, -19, 0, -19,
ax_anim 2, 3, 171, 7, -18, 7, -18,
ax_anim 2, 0, 172, 11, -10, 11, -10,
ax_anim 1, 0, 173, 7, -2, 7, -2,
ax_anim 1, 0, 174, 0, 0, 0, 0,
ax_anim_terminator
sNidoqueenAnims_9_6:
ax_anim 2, 0, 173, 0, 0, 0, 0,
ax_anim 1, 0, 172, 1, -8, 1, -8,
ax_anim 2, 0, 171, -5, -18, -5, -18,
ax_anim 2, 0, 170, -13, -20, -13, -20,
ax_anim 3, 0, 177, -21, -22, -21, -22,
ax_anim 2, 3, 176, -22, -11, -22, -11,
ax_anim 2, 0, 175, -17, -4, -17, -4,
ax_anim 1, 0, 174, -7, -1, -7, -1,
ax_anim 1, 0, 173, 0, 0, 0, 0,
ax_anim_terminator
sNidoqueenAnims_9_7:
ax_anim 2, 0, 172, 0, 0, 0, 0,
ax_anim 1, 0, 171, -4, -4, -3, -4,
ax_anim 2, 0, 170, -11, -6, -11, -6,
ax_anim 2, 0, 177, -19, -4, -17, -4,
ax_anim 3, 0, 176, -23, 1, -20, 1,
ax_anim 2, 3, 175, -19, 5, -17, 5,
ax_anim 2, 0, 174, -12, 7, -12, 7,
ax_anim 1, 0, 173, -4, 5, -4, 5,
ax_anim 1, 0, 172, 0, 0, 0, 0,
ax_anim_terminator
sNidoqueenAnims_9_8:
ax_anim 2, 0, 171, 0, 0, 0, 0,
ax_anim 1, 0, 170, -6, 0, -6, 0,
ax_anim 2, 0, 177, -17, 3, -17, 3,
ax_anim 2, 0, 176, -24, 9, -24, 9,
ax_anim 3, 0, 175, -23, 21, -23, 16,
ax_anim 2, 3, 174, -11, 21, -11, 16,
ax_anim 2, 0, 173, 0, 16, -4, 12,
ax_anim 1, 0, 172, 2, 9, -3, 7,
ax_anim 1, 0, 171, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sNidoqueenAnims_10_1:
ax_anim 2, 0, 178, 0, 0, 0, 0,
ax_anim 2, 0, 178, 6, 0, 6, 0,
ax_anim 2, 0, 178, -6, 0, -6, 0,
ax_anim 2, 0, 178, 10, 0, 10, 0,
ax_anim 2, 0, 178, -10, 0, -10, 0,
ax_anim 2, 0, 178, 12, 0, 12, 0,
ax_anim 3, 0, 178, -12, 0, -12, 0,
ax_anim 3, 0, 178, 13, 0, 13, 0,
ax_anim 3, 0, 178, -13, 0, -13, 0,
ax_anim 2, 0, 178, 12, 0, 12, 0,
ax_anim 3, 0, 178, -12, 0, -12, 0,
ax_anim 2, 0, 178, 10, 0, 10, 0,
ax_anim 2, 0, 178, -10, 0, -10, 0,
ax_anim 2, 0, 178, 6, 0, 6, 0,
ax_anim 2, 0, 178, -6, 0, -6, 0,
ax_anim 2, 0, 178, 0, 0, 0, 0,
ax_anim_terminator
sNidoqueenAnims_10_2:
ax_anim 2, 0, 179, 0, 0, 0, 0,
ax_anim 2, 0, 179, 6, -6, 6, -6,
ax_anim 2, 0, 179, -6, 6, -6, 6,
ax_anim 2, 0, 179, 10, -10, 10, -10,
ax_anim 2, 0, 179, -10, 10, -10, 10,
ax_anim 2, 0, 179, 12, -12, 12, -12,
ax_anim 3, 0, 179, -12, 12, -12, 12,
ax_anim 3, 0, 179, 13, -13, 13, -13,
ax_anim 3, 0, 179, -13, 13, -13, 13,
ax_anim 2, 0, 179, 12, -12, 12, -12,
ax_anim 3, 0, 179, -12, 12, -12, 12,
ax_anim 2, 0, 179, 10, -10, 10, -10,
ax_anim 2, 0, 179, -10, 10, -10, 10,
ax_anim 2, 0, 179, 6, -6, 6, -6,
ax_anim 2, 0, 179, -6, 6, -6, 6,
ax_anim 2, 0, 179, 0, 0, 0, 0,
ax_anim_terminator
sNidoqueenAnims_10_3:
ax_anim 2, 0, 180, 0, 0, 0, 0,
ax_anim 2, 0, 180, 0, -6, 0, -6,
ax_anim 2, 0, 180, 0, 6, 0, 6,
ax_anim 2, 0, 180, 0, -10, 0, -10,
ax_anim 2, 0, 180, 0, 10, 0, 10,
ax_anim 2, 0, 180, 0, -12, 0, -12,
ax_anim 3, 0, 180, 0, 12, 0, 12,
ax_anim 3, 0, 180, 0, -13, 0, -13,
ax_anim 3, 0, 180, 0, 13, 0, 13,
ax_anim 2, 0, 180, 0, -12, 0, -12,
ax_anim 3, 0, 180, 0, 12, 0, 12,
ax_anim 2, 0, 180, 0, -10, 0, -10,
ax_anim 2, 0, 180, 0, 10, 0, 10,
ax_anim 2, 0, 180, 0, -6, 0, -6,
ax_anim 2, 0, 180, 0, 6, 0, 6,
ax_anim 2, 0, 180, 0, 0, 0, 0,
ax_anim_terminator
sNidoqueenAnims_10_4:
ax_anim 2, 0, 181, 0, 0, 0, 0,
ax_anim 2, 0, 181, -6, -6, -6, -6,
ax_anim 2, 0, 181, 6, 6, 6, 6,
ax_anim 2, 0, 181, -10, -10, -10, -10,
ax_anim 2, 0, 181, 10, 10, 10, 10,
ax_anim 2, 0, 181, -12, -12, -12, -12,
ax_anim 3, 0, 181, 12, 12, 12, 12,
ax_anim 3, 0, 181, -13, -13, -13, -13,
ax_anim 3, 0, 181, 13, 13, 13, 13,
ax_anim 2, 0, 181, -12, -12, -12, -12,
ax_anim 3, 0, 181, 12, 12, 12, 12,
ax_anim 2, 0, 181, -10, -10, -10, -10,
ax_anim 2, 0, 181, 10, 10, 10, 10,
ax_anim 2, 0, 181, -6, -6, -6, -6,
ax_anim 2, 0, 181, 6, 6, 6, 6,
ax_anim 2, 0, 181, 0, 0, 0, 0,
ax_anim_terminator
sNidoqueenAnims_10_5:
ax_anim 2, 0, 182, 0, 0, 0, 0,
ax_anim 2, 0, 182, 6, 0, 6, 0,
ax_anim 2, 0, 182, -6, 0, -6, 0,
ax_anim 2, 0, 182, 10, 0, 10, 0,
ax_anim 2, 0, 182, -10, 0, -10, 0,
ax_anim 2, 0, 182, 12, 0, 12, 0,
ax_anim 3, 0, 182, -12, 0, -12, 0,
ax_anim 3, 0, 182, 13, 0, 13, 0,
ax_anim 3, 0, 182, -13, 0, -13, 0,
ax_anim 2, 0, 182, 12, 0, 12, 0,
ax_anim 3, 0, 182, -12, 0, -12, 0,
ax_anim 2, 0, 182, 10, 0, 10, 0,
ax_anim 2, 0, 182, -10, 0, -10, 0,
ax_anim 2, 0, 182, 6, 0, 6, 0,
ax_anim 2, 0, 182, -6, 0, -6, 0,
ax_anim 2, 0, 182, 0, 0, 0, 0,
ax_anim_terminator
sNidoqueenAnims_10_6:
ax_anim 2, 0, 183, 0, 0, 0, 0,
ax_anim 2, 0, 183, 6, -6, 6, -6,
ax_anim 2, 0, 183, -6, 6, -6, 6,
ax_anim 2, 0, 183, 10, -10, 10, -10,
ax_anim 2, 0, 183, -10, 10, -10, 10,
ax_anim 2, 0, 183, 12, -12, 12, -12,
ax_anim 3, 0, 183, -12, 12, -12, 12,
ax_anim 3, 0, 183, 13, -13, 13, -13,
ax_anim 3, 0, 183, -13, 13, -13, 13,
ax_anim 2, 0, 183, 12, -12, 12, -12,
ax_anim 3, 0, 183, -12, 12, -12, 12,
ax_anim 2, 0, 183, 10, -10, 10, -10,
ax_anim 2, 0, 183, -10, 10, -10, 10,
ax_anim 2, 0, 183, 6, -6, 6, -6,
ax_anim 2, 0, 183, -6, 6, -6, 6,
ax_anim 2, 0, 183, 0, 0, 0, 0,
ax_anim_terminator
sNidoqueenAnims_10_7:
ax_anim 2, 0, 184, 0, 0, 0, 0,
ax_anim 2, 0, 184, 0, -6, 0, -6,
ax_anim 2, 0, 184, 0, 6, 0, 6,
ax_anim 2, 0, 184, 0, -10, 0, -10,
ax_anim 2, 0, 184, 0, 10, 0, 10,
ax_anim 2, 0, 184, 0, -12, 0, -12,
ax_anim 3, 0, 184, 0, 12, 0, 12,
ax_anim 3, 0, 184, 0, -13, 0, -13,
ax_anim 3, 0, 184, 0, 13, 0, 13,
ax_anim 2, 0, 184, 0, -12, 0, -12,
ax_anim 3, 0, 184, 0, 12, 0, 12,
ax_anim 2, 0, 184, 0, -10, 0, -10,
ax_anim 2, 0, 184, 0, 10, 0, 10,
ax_anim 2, 0, 184, 0, -6, 0, -6,
ax_anim 2, 0, 184, 0, 6, 0, 6,
ax_anim 2, 0, 184, 0, 0, 0, 0,
ax_anim_terminator
sNidoqueenAnims_10_8:
ax_anim 2, 0, 185, 0, 0, 0, 0,
ax_anim 2, 0, 185, -6, -6, -6, -6,
ax_anim 2, 0, 185, 6, 6, 6, 6,
ax_anim 2, 0, 185, -10, -10, -10, -10,
ax_anim 2, 0, 185, 10, 10, 10, 10,
ax_anim 2, 0, 185, -12, -12, -12, -12,
ax_anim 3, 0, 185, 12, 12, 12, 12,
ax_anim 3, 0, 185, -13, -13, -13, -13,
ax_anim 3, 0, 185, 13, 13, 13, 13,
ax_anim 2, 0, 185, -12, -12, -12, -12,
ax_anim 3, 0, 185, 12, 12, 12, 12,
ax_anim 2, 0, 185, -10, -10, -10, -10,
ax_anim 2, 0, 185, 10, 10, 10, 10,
ax_anim 2, 0, 185, -6, -6, -6, -6,
ax_anim 2, 0, 185, 6, 6, 6, 6,
ax_anim 2, 0, 185, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sNidoqueenAnims_11_1:
ax_anim 2, 0, 186, 0, 0, 0, 0,
ax_anim 1, 0, 187, 0, -10, 0, 0,
ax_anim 2, 0, 187, 0, -16, 0, 0,
ax_anim 3, 0, 187, 0, -20, 0, 0,
ax_anim 4, 0, 187, 0, -21, 0, 0,
ax_anim 4, 0, 188, 0, -27, 0, 0,
ax_anim 3, 0, 188, 0, -25, 0, 0,
ax_anim 2, 0, 188, 0, -18, 0, 0,
ax_anim 1, 0, 188, 0, -12, 0, 0,
ax_anim 2, 2, 188, 0, 0, 0, 0,
ax_anim_terminator
sNidoqueenAnims_11_2:
ax_anim 2, 0, 189, 0, 0, 0, 0,
ax_anim 1, 0, 190, 0, -10, 0, 0,
ax_anim 2, 0, 190, 0, -16, 0, 0,
ax_anim 3, 0, 190, 0, -20, 0, 0,
ax_anim 4, 0, 190, 0, -21, 0, 0,
ax_anim 4, 0, 191, 0, -25, 0, 0,
ax_anim 3, 0, 191, 0, -22, 0, 0,
ax_anim 2, 0, 191, 0, -18, 0, 0,
ax_anim 1, 0, 191, 0, -12, 0, 0,
ax_anim 2, 2, 191, 0, 0, 0, 0,
ax_anim_terminator
sNidoqueenAnims_11_3:
ax_anim 2, 0, 192, 0, 0, 0, 0,
ax_anim 1, 0, 193, 0, -10, 0, 0,
ax_anim 2, 0, 193, 0, -16, 0, 0,
ax_anim 3, 0, 193, 0, -20, 0, 0,
ax_anim 4, 0, 193, 0, -21, 0, 0,
ax_anim 4, 0, 194, 0, -23, 0, 0,
ax_anim 3, 0, 194, 0, -22, 0, 0,
ax_anim 2, 0, 194, 0, -18, 0, 0,
ax_anim 1, 0, 194, 0, -12, 0, 0,
ax_anim 2, 2, 194, 0, 0, 0, 0,
ax_anim_terminator
sNidoqueenAnims_11_4:
ax_anim 2, 0, 195, 0, 0, 0, 0,
ax_anim 1, 0, 196, 0, -10, 0, 0,
ax_anim 2, 0, 196, 0, -16, 0, 0,
ax_anim 3, 0, 196, 0, -20, 0, 0,
ax_anim 4, 0, 196, 0, -21, 0, 0,
ax_anim 4, 0, 197, 0, -22, 0, 0,
ax_anim 3, 0, 197, 0, -21, 0, 0,
ax_anim 2, 0, 197, 0, -17, 0, 0,
ax_anim 1, 0, 197, 0, -11, 0, 0,
ax_anim 2, 2, 197, 0, 0, 0, 0,
ax_anim_terminator
sNidoqueenAnims_11_5:
ax_anim 2, 0, 198, 0, 0, 0, 0,
ax_anim 1, 0, 199, 0, -10, 0, 0,
ax_anim 2, 0, 199, 0, -16, 0, 0,
ax_anim 3, 0, 199, 0, -20, 0, 0,
ax_anim 4, 0, 199, 0, -22, 0, 0,
ax_anim 4, 0, 200, 0, -23, 0, 0,
ax_anim 3, 0, 200, 0, -22, 0, 0,
ax_anim 2, 0, 200, 0, -18, 0, 0,
ax_anim 1, 0, 200, 0, -12, 0, 0,
ax_anim 2, 2, 200, 0, 0, 0, 0,
ax_anim_terminator
sNidoqueenAnims_11_6:
ax_anim 2, 0, 201, 0, 0, 0, 0,
ax_anim 1, 0, 202, 0, -10, 0, 0,
ax_anim 2, 0, 202, 0, -16, 0, 0,
ax_anim 3, 0, 202, 0, -20, 0, 0,
ax_anim 4, 0, 202, 0, -21, 0, 0,
ax_anim 4, 0, 203, 0, -22, 0, 0,
ax_anim 3, 0, 203, 0, -21, 0, 0,
ax_anim 2, 0, 203, 0, -17, 0, 0,
ax_anim 1, 0, 203, 0, -11, 0, 0,
ax_anim 2, 2, 203, 0, 0, 0, 0,
ax_anim_terminator
sNidoqueenAnims_11_7:
ax_anim 2, 0, 204, 0, 0, 0, 0,
ax_anim 1, 0, 205, 0, -10, 0, 0,
ax_anim 2, 0, 205, 0, -16, 0, 0,
ax_anim 3, 0, 205, 0, -20, 0, 0,
ax_anim 4, 0, 205, 0, -21, 0, 0,
ax_anim 4, 0, 206, 0, -23, 0, 0,
ax_anim 3, 0, 206, 0, -22, 0, 0,
ax_anim 2, 0, 206, 0, -18, 0, 0,
ax_anim 1, 0, 206, 0, -12, 0, 0,
ax_anim 2, 2, 206, 0, 0, 0, 0,
ax_anim_terminator
sNidoqueenAnims_11_8:
ax_anim 2, 0, 207, 0, 0, 0, 0,
ax_anim 1, 0, 208, 0, -10, 0, 0,
ax_anim 2, 0, 208, 0, -16, 0, 0,
ax_anim 3, 0, 208, 0, -20, 0, 0,
ax_anim 4, 0, 208, 0, -21, 0, 0,
ax_anim 4, 0, 209, 0, -25, 0, 0,
ax_anim 3, 0, 209, 0, -22, 0, 0,
ax_anim 2, 0, 209, 0, -18, 0, 0,
ax_anim 1, 0, 209, 0, -12, 0, 0,
ax_anim 2, 2, 209, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sNidoqueenAnims_12_1:
ax_anim 2, 0, 210, 1, 0, 1, 0,
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 2, 0, 210, 1, 0, 1, 0,
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 2, 0, 210, 1, 0, 1, 0,
ax_anim 2, 2, 210, 0, 0, 0, 0,
ax_anim 2, 0, 210, 1, 0, 1, 0,
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 2, 0, 210, 1, 0, 1, 0,
ax_anim 2, 1, 210, 0, 0, 0, 0,
ax_anim_terminator
sNidoqueenAnims_12_2:
ax_anim 2, 0, 211, 1, -1, 1, 0,
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 2, 0, 211, 1, -1, 1, 0,
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 2, 0, 211, 1, -1, 1, 0,
ax_anim 2, 2, 211, 0, 0, 0, 0,
ax_anim 2, 0, 211, 1, -1, 1, 0,
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 2, 0, 211, 1, -1, 1, 0,
ax_anim 2, 1, 211, 0, 0, 0, 0,
ax_anim_terminator
sNidoqueenAnims_12_3:
ax_anim 2, 0, 212, 0, -1, 0, -1,
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 2, 0, 212, 0, -1, 0, -1,
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 2, 0, 212, 0, -1, 0, -1,
ax_anim 2, 2, 212, 0, 0, 0, 0,
ax_anim 2, 0, 212, 0, -1, 0, -1,
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 2, 0, 212, 0, -1, 0, -1,
ax_anim 2, 1, 212, 0, 0, 0, 0,
ax_anim_terminator
sNidoqueenAnims_12_4:
ax_anim 2, 0, 213, -1, -1, -1, -1,
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 2, 0, 213, -1, -1, -1, -1,
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 2, 0, 213, -1, -1, -1, -1,
ax_anim 2, 2, 213, 0, 0, 0, 0,
ax_anim 2, 0, 213, -1, -1, -1, -1,
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 2, 0, 213, -1, -1, -1, -1,
ax_anim 2, 1, 213, 0, 0, 0, 0,
ax_anim_terminator
sNidoqueenAnims_12_5:
ax_anim 2, 0, 214, 1, 0, 1, 0,
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 2, 0, 214, 1, 0, 1, 0,
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 2, 0, 214, 1, 0, 1, 0,
ax_anim 2, 2, 214, 0, 0, 0, 0,
ax_anim 2, 0, 214, 1, 0, 1, 0,
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 2, 0, 214, 1, 0, 1, 0,
ax_anim 2, 1, 214, 0, 0, 0, 0,
ax_anim_terminator
sNidoqueenAnims_12_6:
ax_anim 2, 0, 215, 1, -1, 1, -1,
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 0, 215, 1, -1, 1, -1,
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 0, 215, 1, -1, 1, -1,
ax_anim 2, 2, 215, 0, 0, 0, 0,
ax_anim 2, 0, 215, 1, -1, 1, -1,
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 0, 215, 1, -1, 1, -1,
ax_anim 2, 1, 215, 0, 0, 0, 0,
ax_anim_terminator
sNidoqueenAnims_12_7:
ax_anim 2, 0, 216, 0, -1, 0, -1,
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, -1, 0, -1,
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, -1, 0, -1,
ax_anim 2, 2, 216, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, -1, 0, -1,
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, -1, 0, -1,
ax_anim 2, 1, 216, 0, 0, 0, 0,
ax_anim_terminator
sNidoqueenAnims_12_8:
ax_anim 2, 0, 217, -1, -1, -1, -1,
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 0, 217, -1, -1, -1, -1,
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 0, 217, -1, -1, -1, -1,
ax_anim 2, 2, 217, 0, 0, 0, 0,
ax_anim 2, 0, 217, -1, -1, -1, -1,
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 0, 217, -1, -1, -1, -1,
ax_anim 2, 1, 217, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sNidoqueenAnims_13_1:
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 2, 2, 218, 0, 0, 0, 0,
ax_anim_terminator
sNidoqueenAnims_13_2:
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 2, 2, 225, 0, 0, 0, 0,
ax_anim_terminator
sNidoqueenAnims_13_3:
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 2, 2, 224, 0, 0, 0, 0,
ax_anim_terminator
sNidoqueenAnims_13_4:
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 2, 223, 0, 0, 0, 0,
ax_anim_terminator
sNidoqueenAnims_13_5:
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 2, 222, 0, 0, 0, 0,
ax_anim_terminator
sNidoqueenAnims_13_6:
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 2, 221, 0, 0, 0, 0,
ax_anim_terminator
sNidoqueenAnims_13_7:
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 2, 220, 0, 0, 0, 0,
ax_anim_terminator
sNidoqueenAnims_13_8:
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 2, 219, 0, 0, 0, 0,
ax_anim_terminator
sNidoqueenGfx1:
.incbin "baserom.gba", 0x65E208, 0x200
sNidoqueenSprites1:
ax_sprite sNidoqueenGfx1, 0x200
ax_sprite_terminator
sNidoqueenGfx2:
.incbin "baserom.gba", 0x65E418, 0x200
sNidoqueenSprites2:
ax_sprite sNidoqueenGfx2, 0x200
ax_sprite_terminator
sNidoqueenGfx3:
.incbin "baserom.gba", 0x65E628, 0x200
sNidoqueenSprites3:
ax_sprite sNidoqueenGfx3, 0x200
ax_sprite_terminator
sNidoqueenGfx4:
.incbin "baserom.gba", 0x65E838, 0x200
sNidoqueenSprites4:
ax_sprite sNidoqueenGfx4, 0x200
ax_sprite_terminator
sNidoqueenGfx5:
.incbin "baserom.gba", 0x65EA48, 0x200
sNidoqueenSprites5:
ax_sprite sNidoqueenGfx5, 0x200
ax_sprite_terminator
sNidoqueenGfx6:
.incbin "baserom.gba", 0x65EC58, 0x200
sNidoqueenSprites6:
ax_sprite sNidoqueenGfx6, 0x200
ax_sprite_terminator
sNidoqueenGfx7:
.incbin "baserom.gba", 0x65EE68, 0x200
sNidoqueenSprites7:
ax_sprite sNidoqueenGfx7, 0x200
ax_sprite_terminator
sNidoqueenGfx8:
.incbin "baserom.gba", 0x65F078, 0x200
sNidoqueenSprites8:
ax_sprite sNidoqueenGfx8, 0x200
ax_sprite_terminator
sNidoqueenGfx9:
.incbin "baserom.gba", 0x65F288, 0x200
sNidoqueenSprites9:
ax_sprite sNidoqueenGfx9, 0x200
ax_sprite_terminator
sNidoqueenGfx10:
.incbin "baserom.gba", 0x65F498, 0x200
sNidoqueenSprites10:
ax_sprite sNidoqueenGfx10, 0x200
ax_sprite_terminator
sNidoqueenGfx11:
.incbin "baserom.gba", 0x65F6A8, 0x200
sNidoqueenSprites11:
ax_sprite sNidoqueenGfx11, 0x200
ax_sprite_terminator
sNidoqueenGfx12:
.incbin "baserom.gba", 0x65F8B8, 0x200
sNidoqueenSprites12:
ax_sprite sNidoqueenGfx12, 0x200
ax_sprite_terminator
sNidoqueenGfx13:
.incbin "baserom.gba", 0x65FAC8, 0x200
sNidoqueenSprites13:
ax_sprite sNidoqueenGfx13, 0x200
ax_sprite_terminator
sNidoqueenGfx14:
.incbin "baserom.gba", 0x65FCD8, 0x200
sNidoqueenSprites14:
ax_sprite sNidoqueenGfx14, 0x200
ax_sprite_terminator
sNidoqueenGfx15:
.incbin "baserom.gba", 0x65FEE8, 0x200
sNidoqueenSprites15:
ax_sprite sNidoqueenGfx15, 0x200
ax_sprite_terminator
sNidoqueenGfx16:
.incbin "baserom.gba", 0x6600F8, 0x20
sNidoqueenGfx16_1:
.incbin "baserom.gba", 0x660118, 0x60
sNidoqueenGfx16_2:
.incbin "baserom.gba", 0x660178, 0x100
sNidoqueenSprites16:
ax_sprite 0, 0x20
ax_sprite sNidoqueenGfx16, 0x20
ax_sprite 0, 0x40
ax_sprite sNidoqueenGfx16_1, 0x60
ax_sprite 0, 0x20
ax_sprite sNidoqueenGfx16_2, 0x100
ax_sprite_terminator
sNidoqueenGfx17:
.incbin "baserom.gba", 0x6602B0, 0x60
sNidoqueenGfx17_1:
.incbin "baserom.gba", 0x660310, 0x100
sNidoqueenSprites17:
ax_sprite 0, 0x80
ax_sprite sNidoqueenGfx17, 0x60
ax_sprite 0, 0x20
ax_sprite sNidoqueenGfx17_1, 0x100
ax_sprite_terminator
sNidoqueenGfx18:
.incbin "baserom.gba", 0x660438, 0x20
sNidoqueenGfx18_1:
.incbin "baserom.gba", 0x660458, 0x60
sNidoqueenGfx18_2:
.incbin "baserom.gba", 0x6604B8, 0x80
sNidoqueenGfx18_3:
.incbin "baserom.gba", 0x660538, 0x40
sNidoqueenSprites18:
ax_sprite 0, 0x20
ax_sprite sNidoqueenGfx18, 0x20
ax_sprite 0, 0x40
ax_sprite sNidoqueenGfx18_1, 0x60
ax_sprite 0, 0x20
ax_sprite sNidoqueenGfx18_2, 0x80
ax_sprite 0, 0x20
ax_sprite sNidoqueenGfx18_3, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sNidoqueenGfx19:
.incbin "baserom.gba", 0x6605C8, 0x40
sNidoqueenGfx19_1:
.incbin "baserom.gba", 0x660608, 0x60
sNidoqueenGfx19_2:
.incbin "baserom.gba", 0x660668, 0x100
sNidoqueenSprites19:
ax_sprite sNidoqueenGfx19, 0x40
ax_sprite 0, 0x40
ax_sprite sNidoqueenGfx19_1, 0x60
ax_sprite 0, 0x20
ax_sprite sNidoqueenGfx19_2, 0x100
ax_sprite_terminator
sNidoqueenGfx20:
.incbin "baserom.gba", 0x660798, 0x200
sNidoqueenSprites20:
ax_sprite sNidoqueenGfx20, 0x200
ax_sprite_terminator
sNidoqueenGfx21:
.incbin "baserom.gba", 0x6609A8, 0x20
sNidoqueenGfx21_1:
.incbin "baserom.gba", 0x6609C8, 0x20
sNidoqueenGfx21_2:
.incbin "baserom.gba", 0x6609E8, 0x60
sNidoqueenGfx21_3:
.incbin "baserom.gba", 0x660A48, 0x60
sNidoqueenSprites21:
ax_sprite 0, 0x60
ax_sprite sNidoqueenGfx21, 0x20
ax_sprite 0, 0x60
ax_sprite sNidoqueenGfx21_1, 0x20
ax_sprite 0, 0x20
ax_sprite sNidoqueenGfx21_2, 0x60
ax_sprite 0, 0x20
ax_sprite sNidoqueenGfx21_3, 0x60
ax_sprite_terminator
sNidoqueenGfx22:
.incbin "baserom.gba", 0x660AF0, 0x180
sNidoqueenSprites22:
ax_sprite sNidoqueenGfx22, 0x180
ax_sprite 0, 0x80
ax_sprite_terminator
sNidoqueenGfx23:
.incbin "baserom.gba", 0x660C88, 0x40
sNidoqueenGfx23_1:
.incbin "baserom.gba", 0x660CC8, 0x40
sNidoqueenGfx23_2:
.incbin "baserom.gba", 0x660D08, 0x60
sNidoqueenGfx23_3:
.incbin "baserom.gba", 0x660D68, 0x60
sNidoqueenSprites23:
ax_sprite sNidoqueenGfx23, 0x40
ax_sprite 0, 0x40
ax_sprite sNidoqueenGfx23_1, 0x40
ax_sprite 0, 0x40
ax_sprite sNidoqueenGfx23_2, 0x60
ax_sprite 0, 0x20
ax_sprite sNidoqueenGfx23_3, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sNidoqueenGfx24:
.incbin "baserom.gba", 0x660E10, 0x140
sNidoqueenGfx24_1:
.incbin "baserom.gba", 0x660F50, 0x20
sNidoqueenSprites24:
ax_sprite 0, 0x20
ax_sprite sNidoqueenGfx24, 0x140
ax_sprite 0, 0x40
ax_sprite sNidoqueenGfx24_1, 0x20
ax_sprite 0, 0x40
ax_sprite_terminator
sNidoqueenGfx25:
.incbin "baserom.gba", 0x660FA0, 0x20
sNidoqueenGfx25_1:
.incbin "baserom.gba", 0x660FC0, 0x40
sNidoqueenGfx25_2:
.incbin "baserom.gba", 0x661000, 0x60
sNidoqueenSprites25:
ax_sprite 0, 0xe0
ax_sprite sNidoqueenGfx25, 0x20
ax_sprite 0, 0x40
ax_sprite sNidoqueenGfx25_1, 0x40
ax_sprite 0, 0x20
ax_sprite sNidoqueenGfx25_2, 0x60
ax_sprite_terminator
sNidoqueenGfx26:
.incbin "baserom.gba", 0x661098, 0x40
sNidoqueenGfx26_1:
.incbin "baserom.gba", 0x6610D8, 0x80
sNidoqueenGfx26_2:
.incbin "baserom.gba", 0x661158, 0x60
sNidoqueenSprites26:
ax_sprite 0, 0xa0
ax_sprite sNidoqueenGfx26, 0x40
ax_sprite 0, 0x20
ax_sprite sNidoqueenGfx26_1, 0x80
ax_sprite 0, 0x20
ax_sprite sNidoqueenGfx26_2, 0x60
ax_sprite_terminator
sNidoqueenGfx27:
.incbin "baserom.gba", 0x6611F0, 0x20
sNidoqueenGfx27_1:
.incbin "baserom.gba", 0x661210, 0x20
sNidoqueenGfx27_2:
.incbin "baserom.gba", 0x661230, 0x80
sNidoqueenSprites27:
ax_sprite sNidoqueenGfx27, 0x20
ax_sprite 0, 0x20
ax_sprite sNidoqueenGfx27_1, 0x20
ax_sprite 0, 0x20
ax_sprite sNidoqueenGfx27_2, 0x80
ax_sprite_terminator
sNidoqueenGfx28:
.incbin "baserom.gba", 0x6612E0, 0x60
sNidoqueenGfx28_1:
.incbin "baserom.gba", 0x661340, 0xE0
sNidoqueenSprites28:
ax_sprite 0, 0x80
ax_sprite sNidoqueenGfx28, 0x60
ax_sprite 0, 0x20
ax_sprite sNidoqueenGfx28_1, 0xe0
ax_sprite 0, 0x20
ax_sprite_terminator
sNidoqueenGfx29:
.incbin "baserom.gba", 0x661450, 0x60
sNidoqueenGfx29_1:
.incbin "baserom.gba", 0x6614B0, 0x60
sNidoqueenGfx29_2:
.incbin "baserom.gba", 0x661510, 0x40
sNidoqueenSprites29:
ax_sprite 0, 0x80
ax_sprite sNidoqueenGfx29, 0x60
ax_sprite 0, 0x20
ax_sprite sNidoqueenGfx29_1, 0x60
ax_sprite 0, 0x20
ax_sprite sNidoqueenGfx29_2, 0x40
ax_sprite 0, 0x40
ax_sprite_terminator
sNidoqueenGfx30:
.incbin "baserom.gba", 0x661590, 0x60
sNidoqueenGfx30_1:
.incbin "baserom.gba", 0x6615F0, 0x80
sNidoqueenGfx30_2:
.incbin "baserom.gba", 0x661670, 0x60
sNidoqueenSprites30:
ax_sprite 0, 0x80
ax_sprite sNidoqueenGfx30, 0x60
ax_sprite 0, 0x20
ax_sprite sNidoqueenGfx30_1, 0x80
ax_sprite 0, 0x20
ax_sprite sNidoqueenGfx30_2, 0x60
ax_sprite_terminator
sNidoqueenGfx31:
.incbin "baserom.gba", 0x661708, 0x40
sNidoqueenGfx31_1:
.incbin "baserom.gba", 0x661748, 0x60
sNidoqueenGfx31_2:
.incbin "baserom.gba", 0x6617A8, 0x40
sNidoqueenGfx31_3:
.incbin "baserom.gba", 0x6617E8, 0x40
sNidoqueenSprites31:
ax_sprite 0, 0x20
ax_sprite sNidoqueenGfx31, 0x40
ax_sprite 0, 0x20
ax_sprite sNidoqueenGfx31_1, 0x60
ax_sprite 0, 0x20
ax_sprite sNidoqueenGfx31_2, 0x40
ax_sprite 0, 0x40
ax_sprite sNidoqueenGfx31_3, 0x40
ax_sprite 0, 0x40
ax_sprite_terminator
sNidoqueenGfx32:
.incbin "baserom.gba", 0x661878, 0x60
sNidoqueenGfx32_1:
.incbin "baserom.gba", 0x6618D8, 0x80
sNidoqueenGfx32_2:
.incbin "baserom.gba", 0x661958, 0x40
sNidoqueenSprites32:
ax_sprite 0, 0x80
ax_sprite sNidoqueenGfx32, 0x60
ax_sprite 0, 0x20
ax_sprite sNidoqueenGfx32_1, 0x80
ax_sprite 0, 0x20
ax_sprite sNidoqueenGfx32_2, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sNidoqueenGfx33:
.incbin "baserom.gba", 0x6619D8, 0x20
sNidoqueenGfx33_1:
.incbin "baserom.gba", 0x6619F8, 0x80
sNidoqueenSprites33:
ax_sprite sNidoqueenGfx33, 0x20
ax_sprite 0, 0x20
ax_sprite sNidoqueenGfx33_1, 0x80
ax_sprite 0, 0x40
ax_sprite_terminator
sNidoqueenGfx34:
.incbin "baserom.gba", 0x661AA0, 0x60
sNidoqueenGfx34_1:
.incbin "baserom.gba", 0x661B00, 0x180
sNidoqueenSprites34:
ax_sprite sNidoqueenGfx34, 0x60
ax_sprite 0, 0x20
ax_sprite sNidoqueenGfx34_1, 0x180
ax_sprite_terminator
sNidoqueenGfx35:
.incbin "baserom.gba", 0x661CA0, 0x20
sNidoqueenGfx35_1:
.incbin "baserom.gba", 0x661CC0, 0x60
sNidoqueenGfx35_2:
.incbin "baserom.gba", 0x661D20, 0x80
sNidoqueenGfx35_3:
.incbin "baserom.gba", 0x661DA0, 0x60
sNidoqueenSprites35:
ax_sprite 0, 0x20
ax_sprite sNidoqueenGfx35, 0x20
ax_sprite 0, 0x40
ax_sprite sNidoqueenGfx35_1, 0x60
ax_sprite 0, 0x20
ax_sprite sNidoqueenGfx35_2, 0x80
ax_sprite 0, 0x20
ax_sprite sNidoqueenGfx35_3, 0x60
ax_sprite_terminator
sNidoqueenGfx36:
.incbin "baserom.gba", 0x661E48, 0x60
sNidoqueenGfx36_1:
.incbin "baserom.gba", 0x661EA8, 0x80
sNidoqueenSprites36:
ax_sprite sNidoqueenGfx36, 0x60
ax_sprite 0, 0x20
ax_sprite sNidoqueenGfx36_1, 0x80
ax_sprite_terminator
sNidoqueenGfx37:
.incbin "baserom.gba", 0x661F48, 0x40
sNidoqueenSprites37:
ax_sprite sNidoqueenGfx37, 0x40
ax_sprite_terminator
sNidoqueenGfx38:
.incbin "baserom.gba", 0x661F98, 0x40
sNidoqueenGfx38_1:
.incbin "baserom.gba", 0x661FD8, 0x60
sNidoqueenGfx38_2:
.incbin "baserom.gba", 0x662038, 0xE0
sNidoqueenSprites38:
ax_sprite 0, 0x20
ax_sprite sNidoqueenGfx38, 0x40
ax_sprite 0, 0x40
ax_sprite sNidoqueenGfx38_1, 0x60
ax_sprite 0, 0x20
ax_sprite sNidoqueenGfx38_2, 0xe0
ax_sprite_terminator
sNidoqueenGfx39:
.incbin "baserom.gba", 0x662150, 0x60
sNidoqueenGfx39_1:
.incbin "baserom.gba", 0x6621B0, 0x40
sNidoqueenGfx39_2:
.incbin "baserom.gba", 0x6621F0, 0x20
sNidoqueenSprites39:
ax_sprite sNidoqueenGfx39, 0x60
ax_sprite 0, 0x20
ax_sprite sNidoqueenGfx39_1, 0x40
ax_sprite 0, 0x40
ax_sprite sNidoqueenGfx39_2, 0x20
ax_sprite 0, 0xe0
ax_sprite_terminator
sNidoqueenGfx40:
.incbin "baserom.gba", 0x662248, 0x40
sNidoqueenGfx40_1:
.incbin "baserom.gba", 0x662288, 0x60
sNidoqueenGfx40_2:
.incbin "baserom.gba", 0x6622E8, 0x60
sNidoqueenGfx40_3:
.incbin "baserom.gba", 0x662348, 0x80
sNidoqueenSprites40:
ax_sprite 0, 0x20
ax_sprite sNidoqueenGfx40, 0x40
ax_sprite 0, 0x20
ax_sprite sNidoqueenGfx40_1, 0x60
ax_sprite 0, 0x20
ax_sprite sNidoqueenGfx40_2, 0x60
ax_sprite 0, 0x20
ax_sprite sNidoqueenGfx40_3, 0x80
ax_sprite_terminator
sNidoqueenGfx41:
.incbin "baserom.gba", 0x662410, 0x40
sNidoqueenGfx41_1:
.incbin "baserom.gba", 0x662450, 0x180
sNidoqueenSprites41:
ax_sprite 0, 0x20
ax_sprite sNidoqueenGfx41, 0x40
ax_sprite 0, 0x20
ax_sprite sNidoqueenGfx41_1, 0x180
ax_sprite_terminator
sNidoqueenGfx42:
.incbin "baserom.gba", 0x6625F8, 0x40
sNidoqueenGfx42_1:
.incbin "baserom.gba", 0x662638, 0x160
sNidoqueenSprites42:
ax_sprite 0, 0x20
ax_sprite sNidoqueenGfx42, 0x40
ax_sprite 0, 0x20
ax_sprite sNidoqueenGfx42_1, 0x160
ax_sprite 0, 0x20
ax_sprite_terminator
sNidoqueenGfx43:
.incbin "baserom.gba", 0x6627C8, 0x40
sNidoqueenGfx43_1:
.incbin "baserom.gba", 0x662808, 0x60
sNidoqueenGfx43_2:
.incbin "baserom.gba", 0x662868, 0x60
sNidoqueenGfx43_3:
.incbin "baserom.gba", 0x6628C8, 0x60
sNidoqueenSprites43:
ax_sprite 0, 0x20
ax_sprite sNidoqueenGfx43, 0x40
ax_sprite 0, 0x40
ax_sprite sNidoqueenGfx43_1, 0x60
ax_sprite 0, 0x20
ax_sprite sNidoqueenGfx43_2, 0x60
ax_sprite 0, 0x20
ax_sprite sNidoqueenGfx43_3, 0x60
ax_sprite_terminator
sNidoqueenGfx44:
.incbin "baserom.gba", 0x662970, 0x40
sNidoqueenGfx44_1:
.incbin "baserom.gba", 0x6629B0, 0xE0
sNidoqueenGfx44_2:
.incbin "baserom.gba", 0x662A90, 0x80
sNidoqueenSprites44:
ax_sprite 0, 0x20
ax_sprite sNidoqueenGfx44, 0x40
ax_sprite 0, 0x20
ax_sprite sNidoqueenGfx44_1, 0xe0
ax_sprite 0, 0x20
ax_sprite sNidoqueenGfx44_2, 0x80
ax_sprite_terminator
sNidoqueenGfx45:
.incbin "baserom.gba", 0x662B48, 0x40
sNidoqueenGfx45_1:
.incbin "baserom.gba", 0x662B88, 0x180
sNidoqueenSprites45:
ax_sprite 0, 0x20
ax_sprite sNidoqueenGfx45, 0x40
ax_sprite 0, 0x20
ax_sprite sNidoqueenGfx45_1, 0x180
ax_sprite_terminator
sNidoqueenGfx46:
.incbin "baserom.gba", 0x662D30, 0x200
sNidoqueenSprites46:
ax_sprite sNidoqueenGfx46, 0x200
ax_sprite_terminator
sNidoqueenGfx47:
.incbin "baserom.gba", 0x662F40, 0x200
sNidoqueenSprites47:
ax_sprite sNidoqueenGfx47, 0x200
ax_sprite_terminator
sNidoqueenGfx48:
.incbin "baserom.gba", 0x663150, 0x200
sNidoqueenSprites48:
ax_sprite sNidoqueenGfx48, 0x200
ax_sprite_terminator
sNidoqueenGfx49:
.incbin "baserom.gba", 0x663360, 0x200
sNidoqueenSprites49:
ax_sprite sNidoqueenGfx49, 0x200
ax_sprite_terminator
sNidoqueenGfx50:
.incbin "baserom.gba", 0x663570, 0x200
sNidoqueenSprites50:
ax_sprite sNidoqueenGfx50, 0x200
ax_sprite_terminator
sNidoqueenGfx51:
.incbin "baserom.gba", 0x663780, 0x200
sNidoqueenSprites51:
ax_sprite sNidoqueenGfx51, 0x200
ax_sprite_terminator
sNidoqueenGfx52:
.incbin "baserom.gba", 0x663990, 0x200
sNidoqueenSprites52:
ax_sprite sNidoqueenGfx52, 0x200
ax_sprite_terminator
sAxPosesNidoqueen:
.4byte sNidoqueenPose1
.4byte sNidoqueenPose2
.4byte sNidoqueenPose3
.4byte sNidoqueenPose4
.4byte sNidoqueenPose5
.4byte sNidoqueenPose6
.4byte sNidoqueenPose7
.4byte sNidoqueenPose8
.4byte sNidoqueenPose9
.4byte sNidoqueenPose10
.4byte sNidoqueenPose11
.4byte sNidoqueenPose12
.4byte sNidoqueenPose13
.4byte sNidoqueenPose14
.4byte sNidoqueenPose15
.4byte sNidoqueenPose16
.4byte sNidoqueenPose17
.4byte sNidoqueenPose18
.4byte sNidoqueenPose19
.4byte sNidoqueenPose20
.4byte sNidoqueenPose21
.4byte sNidoqueenPose22
.4byte sNidoqueenPose23
.4byte sNidoqueenPose24
.4byte sNidoqueenPose25
.4byte sNidoqueenPose26
.4byte sNidoqueenPose27
.4byte sNidoqueenPose28
.4byte sNidoqueenPose29
.4byte sNidoqueenPose30
.4byte sNidoqueenPose31
.4byte sNidoqueenPose32
.4byte sNidoqueenPose33
.4byte sNidoqueenPose34
.4byte sNidoqueenPose35
.4byte sNidoqueenPose36
.4byte sNidoqueenPose37
.4byte sNidoqueenPose38
.4byte sNidoqueenPose39
.4byte sNidoqueenPose40
.4byte sNidoqueenPose41
.4byte sNidoqueenPose42
.4byte sNidoqueenPose43
.4byte sNidoqueenPose44
.4byte sNidoqueenPose45
.4byte sNidoqueenPose46
.4byte sNidoqueenPose47
.4byte sNidoqueenPose48
.4byte sNidoqueenPose49
.4byte sNidoqueenPose50
.4byte sNidoqueenPose51
.4byte sNidoqueenPose52
.4byte sNidoqueenPose53
.4byte sNidoqueenPose54
.4byte sNidoqueenPose55
.4byte sNidoqueenPose56
.4byte sNidoqueenPose57
.4byte sNidoqueenPose58
.4byte sNidoqueenPose59
.4byte sNidoqueenPose60
.4byte sNidoqueenPose61
.4byte sNidoqueenPose62
.4byte sNidoqueenPose63
.4byte sNidoqueenPose64
.4byte sNidoqueenPose65
.4byte sNidoqueenPose66
.4byte sNidoqueenPose67
.4byte sNidoqueenPose68
.4byte sNidoqueenPose69
.4byte sNidoqueenPose70
.4byte sNidoqueenPose71
.4byte sNidoqueenPose72
.4byte sNidoqueenPose73
.4byte sNidoqueenPose74
.4byte sNidoqueenPose75
.4byte sNidoqueenPose76
.4byte sNidoqueenPose77
.4byte sNidoqueenPose78
.4byte sNidoqueenPose79
.4byte sNidoqueenPose80
.4byte sNidoqueenPose81
.4byte sNidoqueenPose82
.4byte sNidoqueenPose83
.4byte sNidoqueenPose84
.4byte sNidoqueenPose85
.4byte sNidoqueenPose86
.4byte sNidoqueenPose87
.4byte sNidoqueenPose88
.4byte sNidoqueenPose89
.4byte sNidoqueenPose90
.4byte sNidoqueenPose91
.4byte sNidoqueenPose92
.4byte sNidoqueenPose93
.4byte sNidoqueenPose94
.4byte sNidoqueenPose95
.4byte sNidoqueenPose96
.4byte sNidoqueenPose97
.4byte sNidoqueenPose98
.4byte sNidoqueenPose99
.4byte sNidoqueenPose100
.4byte sNidoqueenPose101
.4byte sNidoqueenPose102
.4byte sNidoqueenPose103
.4byte sNidoqueenPose104
.4byte sNidoqueenPose105
.4byte sNidoqueenPose106
.4byte sNidoqueenPose107
.4byte sNidoqueenPose108
.4byte sNidoqueenPose109
.4byte sNidoqueenPose110
.4byte sNidoqueenPose111
.4byte sNidoqueenPose112
.4byte sNidoqueenPose113
.4byte sNidoqueenPose114
.4byte sNidoqueenPose115
.4byte sNidoqueenPose116
.4byte sNidoqueenPose117
.4byte sNidoqueenPose118
.4byte sNidoqueenPose119
.4byte sNidoqueenPose120
.4byte sNidoqueenPose121
.4byte sNidoqueenPose122
.4byte sNidoqueenPose123
.4byte sNidoqueenPose124
.4byte sNidoqueenPose125
.4byte sNidoqueenPose126
.4byte sNidoqueenPose127
.4byte sNidoqueenPose128
.4byte sNidoqueenPose129
.4byte sNidoqueenPose130
.4byte sNidoqueenPose131
.4byte sNidoqueenPose132
.4byte sNidoqueenPose133
.4byte sNidoqueenPose134
.4byte sNidoqueenPose135
.4byte sNidoqueenPose136
.4byte sNidoqueenPose137
.4byte sNidoqueenPose138
.4byte sNidoqueenPose139
.4byte sNidoqueenPose140
.4byte sNidoqueenPose141
.4byte sNidoqueenPose142
.4byte sNidoqueenPose143
.4byte sNidoqueenPose144
.4byte sNidoqueenPose145
.4byte sNidoqueenPose146
.4byte sNidoqueenPose147
.4byte sNidoqueenPose148
.4byte sNidoqueenPose149
.4byte sNidoqueenPose150
.4byte sNidoqueenPose151
.4byte sNidoqueenPose152
.4byte sNidoqueenPose153
.4byte sNidoqueenPose154
.4byte sNidoqueenPose155
.4byte sNidoqueenPose156
.4byte sNidoqueenPose157
.4byte sNidoqueenPose158
.4byte sNidoqueenPose159
.4byte sNidoqueenPose160
.4byte sNidoqueenPose161
.4byte sNidoqueenPose162
.4byte sNidoqueenPose163
.4byte sNidoqueenPose164
.4byte sNidoqueenPose165
.4byte sNidoqueenPose166
.4byte sNidoqueenPose167
.4byte sNidoqueenPose168
.4byte sNidoqueenPose169
.4byte sNidoqueenPose170
.4byte sNidoqueenPose171
.4byte sNidoqueenPose172
.4byte sNidoqueenPose173
.4byte sNidoqueenPose174
.4byte sNidoqueenPose175
.4byte sNidoqueenPose176
.4byte sNidoqueenPose177
.4byte sNidoqueenPose178
.4byte sNidoqueenPose179
.4byte sNidoqueenPose180
.4byte sNidoqueenPose181
.4byte sNidoqueenPose182
.4byte sNidoqueenPose183
.4byte sNidoqueenPose184
.4byte sNidoqueenPose185
.4byte sNidoqueenPose186
.4byte sNidoqueenPose187
.4byte sNidoqueenPose188
.4byte sNidoqueenPose189
.4byte sNidoqueenPose190
.4byte sNidoqueenPose191
.4byte sNidoqueenPose192
.4byte sNidoqueenPose193
.4byte sNidoqueenPose194
.4byte sNidoqueenPose195
.4byte sNidoqueenPose196
.4byte sNidoqueenPose197
.4byte sNidoqueenPose198
.4byte sNidoqueenPose199
.4byte sNidoqueenPose200
.4byte sNidoqueenPose201
.4byte sNidoqueenPose202
.4byte sNidoqueenPose203
.4byte sNidoqueenPose204
.4byte sNidoqueenPose205
.4byte sNidoqueenPose206
.4byte sNidoqueenPose207
.4byte sNidoqueenPose208
.4byte sNidoqueenPose209
.4byte sNidoqueenPose210
.4byte sNidoqueenPose211
.4byte sNidoqueenPose212
.4byte sNidoqueenPose213
.4byte sNidoqueenPose214
.4byte sNidoqueenPose215
.4byte sNidoqueenPose216
.4byte sNidoqueenPose217
.4byte sNidoqueenPose218
.4byte sNidoqueenPose219
.4byte sNidoqueenPose220
.4byte sNidoqueenPose221
.4byte sNidoqueenPose222
.4byte sNidoqueenPose223
.4byte sNidoqueenPose224
.4byte sNidoqueenPose225
.4byte sNidoqueenPose226
sAxPositionsNidoqueen:
.2byte   -1,   -8, 	 -12,   -6, 	  10,   -6, 	  -1,  -10
.2byte   -2,   -6, 	 -11,   -5, 	   8,   -4, 	  -1,   -8
.2byte    0,   -6, 	 -10,   -4, 	   9,   -5, 	  -1,   -8
.2byte    3,   -9, 	   9,   -9, 	  -5,   -4, 	  -1,   -9
.2byte    2,   -7, 	   7,   -8, 	  -3,   -3, 	  -2,   -7
.2byte    4,   -8, 	  10,   -6, 	  -6,   -4, 	   0,   -8
.2byte    6,   -9, 	   5,   -8, 	   5,   -6, 	  -1,   -9
.2byte    6,   -7, 	   1,   -7, 	   6,   -5, 	  -2,   -8
.2byte    7,   -8, 	   6,   -7, 	   2,   -5, 	  -1,   -8
.2byte    3,  -15, 	  -4,  -14, 	   9,  -11, 	  -1,  -11
.2byte    4,  -12, 	  -6,  -11, 	  10,  -10, 	  -1,  -10
.2byte    2,  -14, 	  -1,  -13, 	   8,   -9, 	  -3,  -10
.2byte   -1,  -16, 	   8,  -13, 	 -10,  -13, 	  -1,  -12
.2byte   -2,  -14, 	   8,  -11, 	  -9,  -13, 	  -2,  -10
.2byte    0,  -14, 	   7,  -13, 	 -10,  -11, 	   0,  -10
.2byte   -5,  -15, 	   2,  -14, 	 -11,  -11, 	  -1,  -11
.2byte   -6,  -12, 	   4,  -11, 	 -12,  -10, 	  -1,  -10
.2byte   -4,  -14, 	  -1,  -13, 	 -10,   -9, 	   1,  -10
.2byte   -8,   -9, 	  -7,   -8, 	  -7,   -6, 	  -1,   -9
.2byte   -8,   -7, 	  -3,   -7, 	  -8,   -5, 	   0,   -8
.2byte   -9,   -8, 	  -8,   -7, 	  -4,   -5, 	  -1,   -8
.2byte   -5,   -9, 	 -11,   -9, 	   3,   -4, 	  -1,   -9
.2byte   -4,   -7, 	  -9,   -8, 	   1,   -3, 	   0,   -7
.2byte   -6,   -8, 	 -12,   -6, 	   4,   -4, 	  -2,   -8
.2byte   -1,   -4, 	 -11,   -8, 	   9,   -8, 	  -1,   -9
.2byte   -2,   -6, 	 -11,   -5, 	   8,   -4, 	  -1,   -8
.2byte    0,   -6, 	 -10,   -4, 	   9,   -5, 	  -1,   -8
.2byte    4,   -5, 	   2,   -9, 	 -10,   -5, 	  -1,   -8
.2byte    2,   -7, 	   7,   -8, 	  -3,   -3, 	  -2,   -7
.2byte    4,   -8, 	  10,   -6, 	  -6,   -4, 	   0,   -8
.2byte    8,   -7, 	  -2,   -9, 	  -4,   -3, 	   2,   -8
.2byte    6,   -7, 	   1,   -7, 	   6,   -5, 	  -2,   -8
.2byte    7,   -8, 	   6,   -7, 	   2,   -5, 	  -1,   -8
.2byte    6,  -13, 	  -7,   -8, 	   3,   -1, 	   1,  -10
.2byte    4,  -12, 	  -6,  -11, 	  10,  -10, 	  -1,  -10
.2byte    2,  -14, 	  -1,  -13, 	   8,   -9, 	  -3,  -10
.2byte   -1,  -16, 	   9,   -6, 	 -11,   -6, 	  -1,  -11
.2byte   -2,  -14, 	   8,  -11, 	  -9,  -13, 	  -2,  -10
.2byte    0,  -14, 	   7,  -13, 	 -10,  -11, 	   0,  -10
.2byte   -7,  -13, 	   6,   -8, 	  -4,   -1, 	  -2,  -10
.2byte   -5,  -12, 	   5,  -11, 	 -11,  -10, 	   0,  -10
.2byte   -3,  -14, 	   0,  -13, 	  -9,   -9, 	   2,  -10
.2byte   -9,   -7, 	   1,   -9, 	   3,   -3, 	  -3,   -8
.2byte   -7,   -7, 	  -2,   -7, 	  -7,   -5, 	   1,   -8
.2byte   -8,   -8, 	  -7,   -7, 	  -3,   -5, 	   0,   -8
.2byte   -5,   -5, 	  -3,   -9, 	   9,   -5, 	   0,   -8
.2byte   -3,   -7, 	  -8,   -8, 	   2,   -3, 	   1,   -7
.2byte   -5,   -8, 	 -11,   -6, 	   5,   -4, 	  -1,   -8
.2byte   -1,   -8, 	 -12,   -6, 	  10,   -6, 	  -1,  -10
.2byte   -2,   -6, 	 -11,   -5, 	   8,   -4, 	  -1,   -8
.2byte    0,   -6, 	 -10,   -4, 	   9,   -5, 	  -1,   -8
.2byte   -2,   -5, 	 -10,  -13, 	   0,    0, 	   0,   -8
.2byte   -2,   -5, 	 -10,  -13, 	   0,    0, 	   0,   -8
.2byte    1,   -5, 	   0,    0, 	   8,  -14, 	  -1,   -8
.2byte    2,   -5, 	   1,    0, 	   9,  -14, 	   0,   -8
.2byte    3,   -9, 	   9,   -9, 	  -5,   -4, 	  -1,   -9
.2byte    2,   -7, 	   7,   -8, 	  -3,   -3, 	  -2,   -7
.2byte    4,   -8, 	  10,   -6, 	  -6,   -4, 	   0,   -8
.2byte    4,   -6, 	   3,  -13, 	   2,    0, 	  -2,   -7
.2byte    4,   -6, 	   3,  -13, 	   2,    0, 	  -2,   -7
.2byte    1,   -4, 	   1,    0, 	  -9,  -12, 	   1,   -7
.2byte    1,   -4, 	   1,    0, 	  -9,  -12, 	   1,   -7
.2byte    6,   -9, 	   5,   -8, 	   5,   -6, 	  -1,   -9
.2byte    6,   -7, 	   1,   -7, 	   6,   -5, 	  -2,   -8
.2byte    7,   -8, 	   6,   -7, 	   2,   -5, 	  -1,   -8
.2byte    6,   -9, 	  -6,  -17, 	   4,   -4, 	  -2,   -9
.2byte    6,   -9, 	  -6,  -17, 	   4,   -4, 	  -2,   -9
.2byte    6,   -9, 	   2,   -2, 	  -5,  -12, 	   0,   -8
.2byte    6,   -9, 	   2,   -2, 	  -5,  -12, 	   0,   -8
.2byte    3,  -15, 	  -4,  -14, 	   9,  -11, 	  -1,  -11
.2byte    4,  -12, 	  -6,  -11, 	  10,  -10, 	  -1,  -10
.2byte    2,  -14, 	  -1,  -13, 	   8,   -9, 	  -3,  -10
.2byte    1,  -15, 	 -10,  -16, 	   5,  -10, 	  -1,  -12
.2byte    1,  -15, 	 -10,  -16, 	   5,  -10, 	  -1,  -12
.2byte    8,  -12, 	   9,   -8, 	   5,  -12, 	   0,  -11
.2byte    8,  -12, 	   9,   -8, 	   5,  -12, 	   0,  -11
.2byte   -1,  -16, 	   8,  -13, 	 -10,  -13, 	  -1,  -12
.2byte   -2,  -14, 	   8,  -11, 	  -9,  -13, 	  -2,  -10
.2byte    0,  -14, 	   7,  -13, 	 -10,  -11, 	   0,  -10
.2byte    5,  -14, 	  11,  -11, 	   4,  -10, 	   1,  -12
.2byte    5,  -14, 	  11,  -11, 	   4,  -10, 	   1,  -12
.2byte   -5,  -14, 	  -4,  -10, 	 -10,  -11, 	  -1,  -12
.2byte   -5,  -14, 	  -4,  -10, 	 -10,  -11, 	  -1,  -12
.2byte   -4,  -15, 	   3,  -14, 	 -10,  -11, 	   0,  -11
.2byte   -5,  -12, 	   5,  -11, 	 -11,  -10, 	   0,  -10
.2byte   -3,  -14, 	   0,  -13, 	  -9,   -9, 	   2,  -10
.2byte   -2,  -15, 	   9,  -16, 	  -6,  -10, 	   0,  -12
.2byte   -2,  -15, 	   9,  -16, 	  -6,  -10, 	   0,  -12
.2byte   -9,  -12, 	 -10,   -8, 	  -6,  -12, 	  -1,  -11
.2byte   -9,  -12, 	 -10,   -8, 	  -6,  -12, 	  -1,  -11
.2byte   -7,   -9, 	  -6,   -8, 	  -6,   -6, 	   0,   -9
.2byte   -7,   -7, 	  -2,   -7, 	  -7,   -5, 	   1,   -8
.2byte   -8,   -8, 	  -7,   -7, 	  -3,   -5, 	   0,   -8
.2byte   -7,   -9, 	   5,  -17, 	  -5,   -4, 	   1,   -9
.2byte   -7,   -9, 	   5,  -17, 	  -5,   -4, 	   1,   -9
.2byte   -7,   -9, 	  -3,   -2, 	   4,  -12, 	  -1,   -8
.2byte   -7,   -9, 	  -3,   -2, 	   4,  -12, 	  -1,   -8
.2byte   -4,   -9, 	 -10,   -9, 	   4,   -4, 	   0,   -9
.2byte   -3,   -7, 	  -8,   -8, 	   2,   -3, 	   1,   -7
.2byte   -5,   -8, 	 -11,   -6, 	   5,   -4, 	  -1,   -8
.2byte   -5,   -6, 	  -4,  -13, 	  -3,    0, 	   1,   -7
.2byte   -5,   -6, 	  -4,  -13, 	  -3,    0, 	   1,   -7
.2byte   -2,   -4, 	  -2,    0, 	   8,  -12, 	  -2,   -7
.2byte   -2,   -4, 	  -2,    0, 	   8,  -12, 	  -2,   -7
.2byte   -1,   -8, 	 -12,   -6, 	  10,   -6, 	  -1,  -10
.2byte   -1,  -19, 	  -7,  -12, 	   5,  -12, 	  -1,   -9
.2byte   -1,   -4, 	 -11,   -8, 	   9,   -8, 	  -1,   -9
.2byte    3,   -9, 	   9,   -9, 	  -5,   -4, 	  -1,   -9
.2byte    0,  -18, 	   5,  -14, 	  -2,  -12, 	  -1,   -8
.2byte    4,   -5, 	   2,   -9, 	 -10,   -5, 	  -1,   -8
.2byte    6,   -9, 	   5,   -8, 	   5,   -6, 	  -1,   -9
.2byte    0,  -17, 	   4,  -16, 	   2,  -11, 	  -3,   -9
.2byte    8,   -8, 	  -2,  -10, 	  -4,   -4, 	   2,   -9
.2byte    3,  -15, 	  -4,  -14, 	   9,  -11, 	  -1,  -11
.2byte    2,  -17, 	  -6,  -19, 	   5,  -16, 	  -4,  -10
.2byte    6,  -15, 	  -7,  -10, 	   3,   -3, 	   1,  -12
.2byte   -1,  -16, 	   8,  -13, 	 -10,  -13, 	  -1,  -12
.2byte   -1,  -21, 	   5,  -17, 	  -7,  -17, 	  -1,  -11
.2byte   -1,  -18, 	   9,   -8, 	 -11,   -8, 	  -1,  -13
.2byte   -5,  -15, 	   2,  -14, 	 -11,  -11, 	  -1,  -11
.2byte   -4,  -17, 	   4,  -19, 	  -7,  -16, 	   2,  -10
.2byte   -8,  -15, 	   5,  -10, 	  -5,   -3, 	  -3,  -12
.2byte   -8,   -9, 	  -7,   -8, 	  -7,   -6, 	  -1,   -9
.2byte   -2,  -17, 	  -6,  -16, 	  -4,  -11, 	   1,   -9
.2byte  -10,   -8, 	   0,  -10, 	   2,   -4, 	  -4,   -9
.2byte   -5,   -9, 	 -11,   -9, 	   3,   -4, 	  -1,   -9
.2byte   -2,  -18, 	  -7,  -14, 	   0,  -12, 	  -1,   -8
.2byte   -6,   -5, 	  -4,   -9, 	   8,   -5, 	  -1,   -8
.2byte   -1,   -8, 	 -12,   -6, 	  10,   -6, 	  -1,  -10
.2byte   -5,   -9, 	 -11,   -9, 	   3,   -4, 	  -1,   -9
.2byte   -8,   -9, 	  -7,   -8, 	  -7,   -6, 	  -1,   -9
.2byte   -5,  -15, 	   2,  -14, 	 -11,  -11, 	  -1,  -11
.2byte   -1,  -16, 	   8,  -13, 	 -10,  -13, 	  -1,  -12
.2byte    3,  -15, 	  -4,  -14, 	   9,  -11, 	  -1,  -11
.2byte    6,   -9, 	   5,   -8, 	   5,   -6, 	  -1,   -9
.2byte    3,   -9, 	   9,   -9, 	  -5,   -4, 	  -1,   -9
.2byte   -4,   -8, 	  -9,   -4, 	   4,   -1, 	  -1,   -8
.2byte   -4,   -7, 	  -9,   -3, 	   4,    0, 	  -1,   -7
.2byte    0,   -7, 	  -2,  -14, 	   2,  -14, 	   0,  -10
.2byte    0,   -7, 	   5,  -15, 	  -1,  -14, 	  -2,   -8
.2byte    3,   -8, 	   4,  -15, 	   3,  -14, 	  -2,   -8
.2byte    3,  -13, 	  -1,  -18, 	   6,  -16, 	  -1,   -9
.2byte    0,  -11, 	   5,  -16, 	  -5,  -16, 	   0,   -9
.2byte   -4,  -13, 	   0,  -18, 	  -7,  -16, 	   0,   -9
.2byte   -4,   -8, 	  -5,  -15, 	  -4,  -14, 	   1,   -8
.2byte   -1,   -7, 	  -6,  -15, 	   0,  -14, 	   1,   -8
.2byte   -1,   -8, 	 -12,   -6, 	  10,   -6, 	  -1,  -10
.2byte   -2,   -6, 	 -11,   -5, 	   8,   -4, 	  -1,   -8
.2byte    0,   -6, 	 -10,   -4, 	   9,   -5, 	  -1,   -8
.2byte    3,   -9, 	   9,   -9, 	  -5,   -4, 	  -1,   -9
.2byte    2,   -7, 	   7,   -8, 	  -3,   -3, 	  -2,   -7
.2byte    4,   -8, 	  10,   -6, 	  -6,   -4, 	   0,   -8
.2byte    6,   -9, 	   5,   -8, 	   5,   -6, 	  -1,   -9
.2byte    6,   -7, 	   1,   -7, 	   6,   -5, 	  -2,   -8
.2byte    7,   -8, 	   6,   -7, 	   2,   -5, 	  -1,   -8
.2byte    3,  -15, 	  -4,  -14, 	   9,  -11, 	  -1,  -11
.2byte    4,  -12, 	  -6,  -11, 	  10,  -10, 	  -1,  -10
.2byte    2,  -14, 	  -1,  -13, 	   8,   -9, 	  -3,  -10
.2byte   -1,  -16, 	   8,  -13, 	 -10,  -13, 	  -1,  -12
.2byte   -2,  -14, 	   8,  -11, 	  -9,  -13, 	  -2,  -10
.2byte    0,  -14, 	   7,  -13, 	 -10,  -11, 	   0,  -10
.2byte   -5,  -15, 	   2,  -14, 	 -11,  -11, 	  -1,  -11
.2byte   -6,  -12, 	   4,  -11, 	 -12,  -10, 	  -1,  -10
.2byte   -4,  -14, 	  -1,  -13, 	 -10,   -9, 	   1,  -10
.2byte   -8,   -9, 	  -7,   -8, 	  -7,   -6, 	  -1,   -9
.2byte   -8,   -7, 	  -3,   -7, 	  -8,   -5, 	   0,   -8
.2byte   -9,   -8, 	  -8,   -7, 	  -4,   -5, 	  -1,   -8
.2byte   -5,   -9, 	 -11,   -9, 	   3,   -4, 	  -1,   -9
.2byte   -4,   -7, 	  -9,   -8, 	   1,   -3, 	   0,   -7
.2byte   -6,   -8, 	 -12,   -6, 	   4,   -4, 	  -2,   -8
.2byte   -1,   -4, 	 -11,   -8, 	   9,   -8, 	  -1,   -9
.2byte   -6,   -5, 	  -4,   -9, 	   8,   -5, 	  -1,   -8
.2byte  -10,   -8, 	   0,  -10, 	   2,   -4, 	  -4,   -9
.2byte   -8,  -15, 	   5,  -10, 	  -5,   -3, 	  -3,  -12
.2byte   -1,  -18, 	   9,   -8, 	 -11,   -8, 	  -1,  -13
.2byte    6,  -15, 	  -7,  -10, 	   3,   -3, 	   1,  -12
.2byte    8,   -8, 	  -2,  -10, 	  -4,   -4, 	   2,   -9
.2byte    4,   -5, 	   2,   -9, 	 -10,   -5, 	  -1,   -8
.2byte   -1,   -4, 	 -11,   -8, 	   9,   -8, 	  -1,   -9
.2byte    4,   -5, 	   2,   -9, 	 -10,   -5, 	  -1,   -8
.2byte    6,   -8, 	  -4,  -10, 	  -6,   -4, 	   0,   -9
.2byte    6,  -14, 	  -7,   -9, 	   3,   -2, 	   1,  -11
.2byte   -1,  -18, 	   9,   -8, 	 -11,   -8, 	  -1,  -13
.2byte   -8,  -14, 	   5,   -9, 	  -5,   -2, 	  -3,  -11
.2byte   -8,   -8, 	   2,  -10, 	   4,   -4, 	  -2,   -9
.2byte   -6,   -5, 	  -4,   -9, 	   8,   -5, 	  -1,   -8
.2byte   -1,   -8, 	 -12,   -6, 	  10,   -6, 	  -1,  -10
.2byte   -1,  -19, 	  -7,  -12, 	   5,  -12, 	  -1,   -9
.2byte   -1,   -4, 	 -11,   -8, 	   9,   -8, 	  -1,   -9
.2byte    3,   -9, 	   9,   -9, 	  -5,   -4, 	  -1,   -9
.2byte    0,  -18, 	   5,  -14, 	  -2,  -12, 	  -1,   -8
.2byte    3,   -5, 	   1,   -9, 	 -11,   -5, 	  -2,   -8
.2byte    6,   -9, 	   5,   -8, 	   5,   -6, 	  -1,   -9
.2byte    0,  -17, 	   4,  -16, 	   2,  -11, 	  -3,   -9
.2byte    5,   -8, 	  -5,  -10, 	  -7,   -4, 	  -1,   -9
.2byte    3,  -15, 	  -4,  -14, 	   9,  -11, 	  -1,  -11
.2byte    2,  -17, 	  -6,  -19, 	   5,  -16, 	  -4,  -10
.2byte    4,  -14, 	  -9,   -9, 	   1,   -2, 	  -1,  -11
.2byte   -1,  -16, 	   8,  -13, 	 -10,  -13, 	  -1,  -12
.2byte   -1,  -21, 	   5,  -17, 	  -7,  -17, 	  -1,  -11
.2byte   -1,  -18, 	   9,   -8, 	 -11,   -8, 	  -1,  -13
.2byte   -5,  -15, 	   2,  -14, 	 -11,  -11, 	  -1,  -11
.2byte   -4,  -17, 	   4,  -19, 	  -7,  -16, 	   2,  -10
.2byte   -6,  -14, 	   7,   -9, 	  -3,   -2, 	  -1,  -11
.2byte   -8,   -9, 	  -7,   -8, 	  -7,   -6, 	  -1,   -9
.2byte   -2,  -17, 	  -6,  -16, 	  -4,  -11, 	   1,   -9
.2byte   -7,   -8, 	   3,  -10, 	   5,   -4, 	  -1,   -9
.2byte   -5,   -9, 	 -11,   -9, 	   3,   -4, 	  -1,   -9
.2byte   -2,  -18, 	  -7,  -14, 	   0,  -12, 	  -1,   -8
.2byte   -5,   -5, 	  -3,   -9, 	   9,   -5, 	   0,   -8
.2byte   -1,   -4, 	 -11,   -8, 	   9,   -8, 	  -1,   -9
.2byte    4,   -5, 	   2,   -9, 	 -10,   -5, 	  -1,   -8
.2byte    6,   -8, 	  -4,  -10, 	  -6,   -4, 	   0,   -9
.2byte    6,  -14, 	  -7,   -9, 	   3,   -2, 	   1,  -11
.2byte   -1,  -18, 	   9,   -8, 	 -11,   -8, 	  -1,  -13
.2byte   -8,  -14, 	   5,   -9, 	  -5,   -2, 	  -3,  -11
.2byte   -8,   -8, 	   2,  -10, 	   4,   -4, 	  -2,   -9
.2byte   -6,   -5, 	  -4,   -9, 	   8,   -5, 	  -1,   -8
.2byte   -1,   -8, 	 -12,   -6, 	  10,   -6, 	  -1,  -10
.2byte   -5,   -9, 	 -11,   -9, 	   3,   -4, 	  -1,   -9
.2byte   -8,   -9, 	  -7,   -8, 	  -7,   -6, 	  -1,   -9
.2byte   -5,  -15, 	   2,  -14, 	 -11,  -11, 	  -1,  -11
.2byte   -1,  -16, 	   8,  -13, 	 -10,  -13, 	  -1,  -12
.2byte    3,  -15, 	  -4,  -14, 	   9,  -11, 	  -1,  -11
.2byte    6,   -9, 	   5,   -8, 	   5,   -6, 	  -1,   -9
.2byte    3,   -9, 	   9,   -9, 	  -5,   -4, 	  -1,   -9
sNidoqueenAnimTable1:
.4byte sNidoqueenAnims_1_1
.4byte sNidoqueenAnims_1_2
.4byte sNidoqueenAnims_1_3
.4byte sNidoqueenAnims_1_4
.4byte sNidoqueenAnims_1_5
.4byte sNidoqueenAnims_1_6
.4byte sNidoqueenAnims_1_7
.4byte sNidoqueenAnims_1_8
sNidoqueenAnimTable2:
.4byte sNidoqueenAnims_2_1
.4byte sNidoqueenAnims_2_2
.4byte sNidoqueenAnims_2_3
.4byte sNidoqueenAnims_2_4
.4byte sNidoqueenAnims_2_5
.4byte sNidoqueenAnims_2_6
.4byte sNidoqueenAnims_2_7
.4byte sNidoqueenAnims_2_8
sNidoqueenAnimTable3:
.4byte sNidoqueenAnims_3_1
.4byte sNidoqueenAnims_3_2
.4byte sNidoqueenAnims_3_3
.4byte sNidoqueenAnims_3_4
.4byte sNidoqueenAnims_3_5
.4byte sNidoqueenAnims_3_6
.4byte sNidoqueenAnims_3_7
.4byte sNidoqueenAnims_3_8
sNidoqueenAnimTable4:
.4byte sNidoqueenAnims_4_1
.4byte sNidoqueenAnims_4_2
.4byte sNidoqueenAnims_4_3
.4byte sNidoqueenAnims_4_4
.4byte sNidoqueenAnims_4_5
.4byte sNidoqueenAnims_4_6
.4byte sNidoqueenAnims_4_7
.4byte sNidoqueenAnims_4_8
sNidoqueenAnimTable5:
.4byte sNidoqueenAnims_5_1
.4byte sNidoqueenAnims_5_2
.4byte sNidoqueenAnims_5_3
.4byte sNidoqueenAnims_5_4
.4byte sNidoqueenAnims_5_5
.4byte sNidoqueenAnims_5_6
.4byte sNidoqueenAnims_5_7
.4byte sNidoqueenAnims_5_8
sNidoqueenAnimTable6:
.4byte sNidoqueenAnims_6_1
.4byte sNidoqueenAnims_6_1
.4byte sNidoqueenAnims_6_1
.4byte sNidoqueenAnims_6_1
.4byte sNidoqueenAnims_6_1
.4byte sNidoqueenAnims_6_1
.4byte sNidoqueenAnims_6_1
.4byte sNidoqueenAnims_6_1
sNidoqueenAnimTable7:
.4byte sNidoqueenAnims_7_1
.4byte sNidoqueenAnims_7_2
.4byte sNidoqueenAnims_7_3
.4byte sNidoqueenAnims_7_4
.4byte sNidoqueenAnims_7_5
.4byte sNidoqueenAnims_7_6
.4byte sNidoqueenAnims_7_7
.4byte sNidoqueenAnims_7_8
sNidoqueenAnimTable8:
.4byte sNidoqueenAnims_8_1
.4byte sNidoqueenAnims_8_2
.4byte sNidoqueenAnims_8_3
.4byte sNidoqueenAnims_8_4
.4byte sNidoqueenAnims_8_5
.4byte sNidoqueenAnims_8_6
.4byte sNidoqueenAnims_8_7
.4byte sNidoqueenAnims_8_8
sNidoqueenAnimTable9:
.4byte sNidoqueenAnims_9_1
.4byte sNidoqueenAnims_9_2
.4byte sNidoqueenAnims_9_3
.4byte sNidoqueenAnims_9_4
.4byte sNidoqueenAnims_9_5
.4byte sNidoqueenAnims_9_6
.4byte sNidoqueenAnims_9_7
.4byte sNidoqueenAnims_9_8
sNidoqueenAnimTable10:
.4byte sNidoqueenAnims_10_1
.4byte sNidoqueenAnims_10_2
.4byte sNidoqueenAnims_10_3
.4byte sNidoqueenAnims_10_4
.4byte sNidoqueenAnims_10_5
.4byte sNidoqueenAnims_10_6
.4byte sNidoqueenAnims_10_7
.4byte sNidoqueenAnims_10_8
sNidoqueenAnimTable11:
.4byte sNidoqueenAnims_11_1
.4byte sNidoqueenAnims_11_2
.4byte sNidoqueenAnims_11_3
.4byte sNidoqueenAnims_11_4
.4byte sNidoqueenAnims_11_5
.4byte sNidoqueenAnims_11_6
.4byte sNidoqueenAnims_11_7
.4byte sNidoqueenAnims_11_8
sNidoqueenAnimTable12:
.4byte sNidoqueenAnims_12_1
.4byte sNidoqueenAnims_12_2
.4byte sNidoqueenAnims_12_3
.4byte sNidoqueenAnims_12_4
.4byte sNidoqueenAnims_12_5
.4byte sNidoqueenAnims_12_6
.4byte sNidoqueenAnims_12_7
.4byte sNidoqueenAnims_12_8
sNidoqueenAnimTable13:
.4byte sNidoqueenAnims_13_1
.4byte sNidoqueenAnims_13_2
.4byte sNidoqueenAnims_13_3
.4byte sNidoqueenAnims_13_4
.4byte sNidoqueenAnims_13_5
.4byte sNidoqueenAnims_13_6
.4byte sNidoqueenAnims_13_7
.4byte sNidoqueenAnims_13_8
sAxAnimationsNidoqueen:
.4byte sNidoqueenAnimTable1
.4byte sNidoqueenAnimTable2
.4byte sNidoqueenAnimTable3
.4byte sNidoqueenAnimTable4
.4byte sNidoqueenAnimTable5
.4byte sNidoqueenAnimTable6
.4byte sNidoqueenAnimTable7
.4byte sNidoqueenAnimTable8
.4byte sNidoqueenAnimTable9
.4byte sNidoqueenAnimTable10
.4byte sNidoqueenAnimTable11
.4byte sNidoqueenAnimTable12
.4byte sNidoqueenAnimTable13
sAxSpritesNidoqueen:
.4byte sNidoqueenSprites1
.4byte sNidoqueenSprites2
.4byte sNidoqueenSprites3
.4byte sNidoqueenSprites4
.4byte sNidoqueenSprites5
.4byte sNidoqueenSprites6
.4byte sNidoqueenSprites7
.4byte sNidoqueenSprites8
.4byte sNidoqueenSprites9
.4byte sNidoqueenSprites10
.4byte sNidoqueenSprites11
.4byte sNidoqueenSprites12
.4byte sNidoqueenSprites13
.4byte sNidoqueenSprites14
.4byte sNidoqueenSprites15
.4byte sNidoqueenSprites16
.4byte sNidoqueenSprites17
.4byte sNidoqueenSprites18
.4byte sNidoqueenSprites19
.4byte sNidoqueenSprites20
.4byte sNidoqueenSprites21
.4byte sNidoqueenSprites22
.4byte sNidoqueenSprites23
.4byte sNidoqueenSprites24
.4byte sNidoqueenSprites25
.4byte sNidoqueenSprites26
.4byte sNidoqueenSprites27
.4byte sNidoqueenSprites28
.4byte sNidoqueenSprites29
.4byte sNidoqueenSprites30
.4byte sNidoqueenSprites31
.4byte sNidoqueenSprites32
.4byte sNidoqueenSprites33
.4byte sNidoqueenSprites34
.4byte sNidoqueenSprites35
.4byte sNidoqueenSprites36
.4byte sNidoqueenSprites37
.4byte sNidoqueenSprites38
.4byte sNidoqueenSprites39
.4byte sNidoqueenSprites40
.4byte sNidoqueenSprites41
.4byte sNidoqueenSprites42
.4byte sNidoqueenSprites43
.4byte sNidoqueenSprites44
.4byte sNidoqueenSprites45
.4byte sNidoqueenSprites46
.4byte sNidoqueenSprites47
.4byte sNidoqueenSprites48
.4byte sNidoqueenSprites49
.4byte sNidoqueenSprites50
.4byte sNidoqueenSprites51
.4byte sNidoqueenSprites52
sAxMainNidoqueen:
ax_main sAxPosesNidoqueen, sAxAnimationsNidoqueen, 13, sAxSpritesNidoqueen, sAxPositionsNidoqueen
