.global gAxNumel
gAxNumel:
ax_siro sAxMainNumel
sNumelPose1:
ax_pose 0, 0x81ee, 0x80f8, 0x8c00
ax_pose_terminator
sNumelPose2:
ax_pose 1, 0x81ee, 0x80f8, 0x8c00
ax_pose_terminator
sNumelPose3:
ax_pose 2, 0x81ee, 0x80f8, 0x8c00
ax_pose_terminator
sNumelPose4:
ax_pose 3, 0x01ee, 0x90ee, 0x8c00
ax_pose_terminator
sNumelPose5:
ax_pose 4, 0x01ee, 0x90ee, 0x8c00
ax_pose_terminator
sNumelPose6:
ax_pose 5, 0x01ee, 0x90ee, 0x8c00
ax_pose_terminator
sNumelPose7:
ax_pose 6, 0x01ec, 0x90ef, 0x8c00
ax_pose_terminator
sNumelPose8:
ax_pose 7, 0x01ec, 0x90ef, 0x8c00
ax_pose_terminator
sNumelPose9:
ax_pose 8, 0x01ec, 0x90ee, 0x8c00
ax_pose_terminator
sNumelPose10:
ax_pose 9, 0x01ec, 0x90ed, 0x8c00
ax_pose_terminator
sNumelPose11:
ax_pose 10, 0x01ec, 0x90ed, 0x8c00
ax_pose_terminator
sNumelPose12:
ax_pose 11, 0x01ed, 0x90ed, 0x8c00
ax_pose_terminator
sNumelPose13:
ax_pose 12, 0x81ed, 0x80f8, 0x8c00
ax_pose_terminator
sNumelPose14:
ax_pose 13, 0x81ed, 0x80f8, 0x8c00
ax_pose_terminator
sNumelPose15:
ax_pose 14, 0x81ed, 0x80f8, 0x8c00
ax_pose_terminator
sNumelPose16:
ax_pose 9, 0x01ec, 0x80f2, 0x8c00
ax_pose_terminator
sNumelPose17:
ax_pose 10, 0x01ec, 0x80f2, 0x8c00
ax_pose_terminator
sNumelPose18:
ax_pose 11, 0x01ed, 0x80f2, 0x8c00
ax_pose_terminator
sNumelPose19:
ax_pose 6, 0x01ec, 0x80f0, 0x8c00
ax_pose_terminator
sNumelPose20:
ax_pose 7, 0x01ec, 0x80f0, 0x8c00
ax_pose_terminator
sNumelPose21:
ax_pose 8, 0x01ec, 0x80f1, 0x8c00
ax_pose_terminator
sNumelPose22:
ax_pose 3, 0x01ee, 0x80f2, 0x8c00
ax_pose_terminator
sNumelPose23:
ax_pose 4, 0x01ee, 0x80f2, 0x8c00
ax_pose_terminator
sNumelPose24:
ax_pose 5, 0x01ee, 0x80f2, 0x8c00
ax_pose_terminator
sNumelPose25:
ax_pose 0, 0x81ee, 0x80f8, 0x8c00
ax_pose_terminator
sNumelPose26:
ax_pose 15, 0x81ea, 0x80f7, 0x8c00
ax_pose_terminator
sNumelPose27:
ax_pose 16, 0x81ed, 0x80f7, 0x8c00
ax_pose_terminator
sNumelPose28:
ax_pose 3, 0x01ee, 0x90ee, 0x8c00
ax_pose_terminator
sNumelPose29:
ax_pose 17, 0x01e9, 0x90f1, 0x8c00
ax_pose_terminator
sNumelPose30:
ax_pose 18, 0x01ea, 0x90f1, 0x8c00
ax_pose_terminator
sNumelPose31:
ax_pose 6, 0x01ec, 0x90ef, 0x8c00
ax_pose_terminator
sNumelPose32:
ax_pose 19, 0x01e7, 0x90f1, 0x8c00
ax_pose_terminator
sNumelPose33:
ax_pose 20, 0x01e8, 0x90f1, 0x8c00
ax_pose_terminator
sNumelPose34:
ax_pose 9, 0x01ec, 0x90ed, 0x8c00
ax_pose_terminator
sNumelPose35:
ax_pose 21, 0x01e7, 0x90ef, 0x8c00
ax_pose_terminator
sNumelPose36:
ax_pose 22, 0x01e9, 0x90ef, 0x8c00
ax_pose_terminator
sNumelPose37:
ax_pose 12, 0x81ed, 0x80f8, 0x8c00
ax_pose_terminator
sNumelPose38:
ax_pose 23, 0x81e8, 0x80f7, 0x8c00
ax_pose_terminator
sNumelPose39:
ax_pose 24, 0x81e9, 0x80f7, 0x8c00
ax_pose_terminator
sNumelPose40:
ax_pose 9, 0x01ec, 0x80f2, 0x8c00
ax_pose_terminator
sNumelPose41:
ax_pose 21, 0x01e7, 0x80f0, 0x8c00
ax_pose_terminator
sNumelPose42:
ax_pose 22, 0x01e9, 0x80f0, 0x8c00
ax_pose_terminator
sNumelPose43:
ax_pose 6, 0x01ec, 0x80f0, 0x8c00
ax_pose_terminator
sNumelPose44:
ax_pose 19, 0x01e7, 0x80ee, 0x8c00
ax_pose_terminator
sNumelPose45:
ax_pose 20, 0x01e8, 0x80ee, 0x8c00
ax_pose_terminator
sNumelPose46:
ax_pose 3, 0x01ee, 0x80f2, 0x8c00
ax_pose_terminator
sNumelPose47:
ax_pose 17, 0x01e9, 0x80ef, 0x8c00
ax_pose_terminator
sNumelPose48:
ax_pose 18, 0x01ea, 0x80ef, 0x8c00
ax_pose_terminator
sNumelPose49:
ax_pose 0, 0x81ee, 0x80f8, 0x8c00
ax_pose_terminator
sNumelPose50:
ax_pose 15, 0x81ea, 0x80f7, 0x8c00
ax_pose_terminator
sNumelPose51:
ax_pose 16, 0x81ed, 0x80f7, 0x8c00
ax_pose_terminator
sNumelPose52:
ax_pose 3, 0x01ee, 0x90ee, 0x8c00
ax_pose_terminator
sNumelPose53:
ax_pose 17, 0x01e9, 0x90f1, 0x8c00
ax_pose_terminator
sNumelPose54:
ax_pose 18, 0x01ea, 0x90f1, 0x8c00
ax_pose_terminator
sNumelPose55:
ax_pose 6, 0x01ec, 0x90ef, 0x8c00
ax_pose_terminator
sNumelPose56:
ax_pose 19, 0x01e7, 0x90f1, 0x8c00
ax_pose_terminator
sNumelPose57:
ax_pose 20, 0x01e8, 0x90f1, 0x8c00
ax_pose_terminator
sNumelPose58:
ax_pose 9, 0x01ec, 0x90ed, 0x8c00
ax_pose_terminator
sNumelPose59:
ax_pose 21, 0x01e7, 0x90ef, 0x8c00
ax_pose_terminator
sNumelPose60:
ax_pose 22, 0x01e9, 0x90ef, 0x8c00
ax_pose_terminator
sNumelPose61:
ax_pose 12, 0x81ed, 0x80f8, 0x8c00
ax_pose_terminator
sNumelPose62:
ax_pose 23, 0x81e8, 0x80f7, 0x8c00
ax_pose_terminator
sNumelPose63:
ax_pose 24, 0x81e9, 0x80f7, 0x8c00
ax_pose_terminator
sNumelPose64:
ax_pose 9, 0x01ec, 0x80f2, 0x8c00
ax_pose_terminator
sNumelPose65:
ax_pose 21, 0x01e7, 0x80f0, 0x8c00
ax_pose_terminator
sNumelPose66:
ax_pose 22, 0x01e9, 0x80f0, 0x8c00
ax_pose_terminator
sNumelPose67:
ax_pose 6, 0x01ec, 0x80f0, 0x8c00
ax_pose_terminator
sNumelPose68:
ax_pose 19, 0x01e7, 0x80ee, 0x8c00
ax_pose_terminator
sNumelPose69:
ax_pose 20, 0x01e8, 0x80ee, 0x8c00
ax_pose_terminator
sNumelPose70:
ax_pose 3, 0x01ee, 0x80f2, 0x8c00
ax_pose_terminator
sNumelPose71:
ax_pose 17, 0x01e9, 0x80ef, 0x8c00
ax_pose_terminator
sNumelPose72:
ax_pose 18, 0x01ea, 0x80ef, 0x8c00
ax_pose_terminator
sNumelPose73:
ax_pose 0, 0x81ee, 0x80f8, 0x8c00
ax_pose_terminator
sNumelPose74:
ax_pose 25, 0x81ec, 0x80f7, 0x8c00
ax_pose_terminator
sNumelPose75:
ax_pose 16, 0x81ed, 0x80f7, 0x8c00
ax_pose_terminator
sNumelPose76:
ax_pose 3, 0x01ee, 0x90ee, 0x8c00
ax_pose_terminator
sNumelPose77:
ax_pose 26, 0x01ea, 0x90f0, 0x8c00
ax_pose_terminator
sNumelPose78:
ax_pose 18, 0x01ea, 0x90f1, 0x8c00
ax_pose_terminator
sNumelPose79:
ax_pose 6, 0x01ec, 0x90ef, 0x8c00
ax_pose_terminator
sNumelPose80:
ax_pose 27, 0x01e8, 0x90ea, 0x8c00
ax_pose_terminator
sNumelPose81:
ax_pose 20, 0x01e8, 0x90f1, 0x8c00
ax_pose_terminator
sNumelPose82:
ax_pose 9, 0x01ec, 0x90ed, 0x8c00
ax_pose_terminator
sNumelPose83:
ax_pose 28, 0x01e8, 0x90e9, 0x8c00
ax_pose_terminator
sNumelPose84:
ax_pose 22, 0x01e9, 0x90ef, 0x8c00
ax_pose_terminator
sNumelPose85:
ax_pose 12, 0x81ed, 0x80f8, 0x8c00
ax_pose_terminator
sNumelPose86:
ax_pose 29, 0x81e8, 0x80f7, 0x8c00
ax_pose_terminator
sNumelPose87:
ax_pose 24, 0x81e9, 0x80f7, 0x8c00
ax_pose_terminator
sNumelPose88:
ax_pose 9, 0x01ec, 0x80f2, 0x8c00
ax_pose_terminator
sNumelPose89:
ax_pose 28, 0x01e8, 0x80f6, 0x8c00
ax_pose_terminator
sNumelPose90:
ax_pose 22, 0x01e9, 0x80f0, 0x8c00
ax_pose_terminator
sNumelPose91:
ax_pose 6, 0x01ec, 0x80f0, 0x8c00
ax_pose_terminator
sNumelPose92:
ax_pose 27, 0x01e8, 0x80f5, 0x8c00
ax_pose_terminator
sNumelPose93:
ax_pose 20, 0x01e8, 0x80ee, 0x8c00
ax_pose_terminator
sNumelPose94:
ax_pose 3, 0x01ee, 0x80f2, 0x8c00
ax_pose_terminator
sNumelPose95:
ax_pose 26, 0x01ea, 0x80f0, 0x8c00
ax_pose_terminator
sNumelPose96:
ax_pose 18, 0x01ea, 0x80ef, 0x8c00
ax_pose_terminator
sNumelPose97:
ax_pose 0, 0x81ee, 0x80f8, 0x8c00
ax_pose_terminator
sNumelPose98:
ax_pose 25, 0x81ec, 0x80f7, 0x8c00
ax_pose_terminator
sNumelPose99:
ax_pose 30, 0x81ec, 0x80f7, 0x8c00
ax_pose_terminator
sNumelPose100:
ax_pose 3, 0x01ee, 0x90ee, 0x8c00
ax_pose_terminator
sNumelPose101:
ax_pose 26, 0x01ea, 0x90f0, 0x8c00
ax_pose_terminator
sNumelPose102:
ax_pose 31, 0x01ea, 0x90f0, 0x8c00
ax_pose_terminator
sNumelPose103:
ax_pose 6, 0x01ec, 0x90ef, 0x8c00
ax_pose_terminator
sNumelPose104:
ax_pose 27, 0x01e8, 0x90ea, 0x8c00
ax_pose_terminator
sNumelPose105:
ax_pose 32, 0x01e8, 0x90ea, 0x8c00
ax_pose_terminator
sNumelPose106:
ax_pose 9, 0x01ec, 0x90ed, 0x8c00
ax_pose_terminator
sNumelPose107:
ax_pose 28, 0x01e8, 0x90e9, 0x8c00
ax_pose_terminator
sNumelPose108:
ax_pose 33, 0x01e8, 0x90e9, 0x8c00
ax_pose_terminator
sNumelPose109:
ax_pose 12, 0x81ed, 0x80f8, 0x8c00
ax_pose_terminator
sNumelPose110:
ax_pose 29, 0x81e8, 0x80f7, 0x8c00
ax_pose_terminator
sNumelPose111:
ax_pose 34, 0x81e8, 0x80f7, 0x8c00
ax_pose_terminator
sNumelPose112:
ax_pose 9, 0x01ec, 0x80f2, 0x8c00
ax_pose_terminator
sNumelPose113:
ax_pose 28, 0x01e8, 0x80f6, 0x8c00
ax_pose_terminator
sNumelPose114:
ax_pose 33, 0x01e8, 0x80f6, 0x8c00
ax_pose_terminator
sNumelPose115:
ax_pose 6, 0x01ec, 0x80f0, 0x8c00
ax_pose_terminator
sNumelPose116:
ax_pose 27, 0x01e8, 0x80f5, 0x8c00
ax_pose_terminator
sNumelPose117:
ax_pose 32, 0x01e8, 0x80f5, 0x8c00
ax_pose_terminator
sNumelPose118:
ax_pose 3, 0x01ee, 0x80f2, 0x8c00
ax_pose_terminator
sNumelPose119:
ax_pose 26, 0x01ea, 0x80f0, 0x8c00
ax_pose_terminator
sNumelPose120:
ax_pose 31, 0x01ea, 0x80f0, 0x8c00
ax_pose_terminator
sNumelPose121:
ax_pose 35, 0x01f0, 0x80f3, 0x8c00
ax_pose_terminator
sNumelPose122:
ax_pose 36, 0x01f0, 0x80f3, 0x8c00
ax_pose_terminator
sNumelPose123:
ax_pose 37, 0x01e0, 0x80f1, 0x8c00
ax_pose_terminator
sNumelPose124:
ax_pose 38, 0x01e1, 0x90ed, 0x8c00
ax_pose_terminator
sNumelPose125:
ax_pose 39, 0x01e2, 0x90ea, 0x8c00
ax_pose_terminator
sNumelPose126:
ax_pose 40, 0x01e6, 0x90ec, 0x8c00
ax_pose_terminator
sNumelPose127:
ax_pose 41, 0x01e3, 0x80f1, 0x8c00
ax_pose_terminator
sNumelPose128:
ax_pose 40, 0x01e6, 0x80f4, 0x8c00
ax_pose_terminator
sNumelPose129:
ax_pose 39, 0x01e2, 0x80f6, 0x8c00
ax_pose_terminator
sNumelPose130:
ax_pose 38, 0x01e1, 0x80f3, 0x8c00
ax_pose_terminator
sNumelPose131:
ax_pose 0, 0x81ee, 0x80f8, 0x8c00
ax_pose_terminator
sNumelPose132:
ax_pose 16, 0x81ed, 0x80f7, 0x8c00
ax_pose_terminator
sNumelPose133:
ax_pose 3, 0x01ee, 0x90ee, 0x8c00
ax_pose_terminator
sNumelPose134:
ax_pose 18, 0x01ea, 0x90f1, 0x8c00
ax_pose_terminator
sNumelPose135:
ax_pose 6, 0x01ec, 0x90ef, 0x8c00
ax_pose_terminator
sNumelPose136:
ax_pose 20, 0x01e8, 0x90f2, 0x8c00
ax_pose_terminator
sNumelPose137:
ax_pose 9, 0x01ec, 0x90ed, 0x8c00
ax_pose_terminator
sNumelPose138:
ax_pose 22, 0x01e8, 0x90f0, 0x8c00
ax_pose_terminator
sNumelPose139:
ax_pose 12, 0x81ed, 0x80f8, 0x8c00
ax_pose_terminator
sNumelPose140:
ax_pose 24, 0x81e9, 0x80f7, 0x8c00
ax_pose_terminator
sNumelPose141:
ax_pose 9, 0x01ec, 0x80f2, 0x8c00
ax_pose_terminator
sNumelPose142:
ax_pose 22, 0x01e8, 0x80ef, 0x8c00
ax_pose_terminator
sNumelPose143:
ax_pose 6, 0x01ec, 0x80f0, 0x8c00
ax_pose_terminator
sNumelPose144:
ax_pose 20, 0x01e8, 0x80ed, 0x8c00
ax_pose_terminator
sNumelPose145:
ax_pose 3, 0x01ee, 0x80f2, 0x8c00
ax_pose_terminator
sNumelPose146:
ax_pose 18, 0x01ea, 0x80ef, 0x8c00
ax_pose_terminator
sNumelPose147:
ax_pose 16, 0x81ec, 0x80f8, 0x8c00
ax_pose_terminator
sNumelPose148:
ax_pose 18, 0x01ea, 0x80f1, 0x8c00
ax_pose_terminator
sNumelPose149:
ax_pose 20, 0x01e9, 0x80f0, 0x8c00
ax_pose_terminator
sNumelPose150:
ax_pose 22, 0x01ea, 0x80f3, 0x8c00
ax_pose_terminator
sNumelPose151:
ax_pose 24, 0x81eb, 0x80f8, 0x8c00
ax_pose_terminator
sNumelPose152:
ax_pose 22, 0x01ea, 0x90ed, 0x8c00
ax_pose_terminator
sNumelPose153:
ax_pose 20, 0x01e9, 0x90f0, 0x8c00
ax_pose_terminator
sNumelPose154:
ax_pose 18, 0x01ea, 0x90ef, 0x8c00
ax_pose_terminator
sNumelPose155:
ax_pose 16, 0x81ec, 0x80f8, 0x8c00
ax_pose_terminator
sNumelPose156:
ax_pose 18, 0x01ea, 0x90ef, 0x8c00
ax_pose_terminator
sNumelPose157:
ax_pose 20, 0x01e9, 0x90f0, 0x8c00
ax_pose_terminator
sNumelPose158:
ax_pose 22, 0x01ea, 0x90ee, 0x8c00
ax_pose_terminator
sNumelPose159:
ax_pose 24, 0x81eb, 0x80f8, 0x8c00
ax_pose_terminator
sNumelPose160:
ax_pose 22, 0x01ea, 0x80f2, 0x8c00
ax_pose_terminator
sNumelPose161:
ax_pose 20, 0x01e9, 0x80f0, 0x8c00
ax_pose_terminator
sNumelPose162:
ax_pose 18, 0x01ea, 0x80f1, 0x8c00
ax_pose_terminator
sNumelPose163:
ax_pose 0, 0x81ee, 0x80f8, 0x8c00
ax_pose_terminator
sNumelPose164:
ax_pose 25, 0x81ef, 0x80f7, 0x8c00
ax_pose_terminator
sNumelPose165:
ax_pose 16, 0x81eb, 0x80f7, 0x8c00
ax_pose_terminator
sNumelPose166:
ax_pose 3, 0x01ee, 0x90ee, 0x8c00
ax_pose_terminator
sNumelPose167:
ax_pose 26, 0x01ed, 0x90f1, 0x8c00
ax_pose_terminator
sNumelPose168:
ax_pose 18, 0x01ea, 0x90f0, 0x8c00
ax_pose_terminator
sNumelPose169:
ax_pose 6, 0x01ec, 0x90ef, 0x8c00
ax_pose_terminator
sNumelPose170:
ax_pose 27, 0x01ea, 0x90ec, 0x8c00
ax_pose_terminator
sNumelPose171:
ax_pose 20, 0x01e8, 0x90f1, 0x8c00
ax_pose_terminator
sNumelPose172:
ax_pose 9, 0x01ec, 0x90ed, 0x8c00
ax_pose_terminator
sNumelPose173:
ax_pose 28, 0x01e9, 0x90eb, 0x8c00
ax_pose_terminator
sNumelPose174:
ax_pose 22, 0x01e9, 0x90ef, 0x8c00
ax_pose_terminator
sNumelPose175:
ax_pose 12, 0x81ed, 0x80f8, 0x8c00
ax_pose_terminator
sNumelPose176:
ax_pose 29, 0x81ea, 0x80f7, 0x8c00
ax_pose_terminator
sNumelPose177:
ax_pose 24, 0x81ea, 0x80f7, 0x8c00
ax_pose_terminator
sNumelPose178:
ax_pose 9, 0x01ec, 0x80f3, 0x8c00
ax_pose_terminator
sNumelPose179:
ax_pose 28, 0x01e9, 0x80f5, 0x8c00
ax_pose_terminator
sNumelPose180:
ax_pose 22, 0x01e9, 0x80f1, 0x8c00
ax_pose_terminator
sNumelPose181:
ax_pose 6, 0x01ec, 0x80f1, 0x8c00
ax_pose_terminator
sNumelPose182:
ax_pose 27, 0x01ea, 0x80f4, 0x8c00
ax_pose_terminator
sNumelPose183:
ax_pose 20, 0x01e8, 0x80ef, 0x8c00
ax_pose_terminator
sNumelPose184:
ax_pose 3, 0x01ee, 0x80f2, 0x8c00
ax_pose_terminator
sNumelPose185:
ax_pose 26, 0x01ed, 0x80ef, 0x8c00
ax_pose_terminator
sNumelPose186:
ax_pose 18, 0x01ea, 0x80f0, 0x8c00
ax_pose_terminator
sNumelPose187:
ax_pose 15, 0x81ea, 0x80f7, 0x8c00
ax_pose_terminator
sNumelPose188:
ax_pose 17, 0x01e9, 0x80f0, 0x8c00
ax_pose_terminator
sNumelPose189:
ax_pose 19, 0x01e7, 0x80f0, 0x8c00
ax_pose_terminator
sNumelPose190:
ax_pose 21, 0x01e7, 0x80f1, 0x8c00
ax_pose_terminator
sNumelPose191:
ax_pose 23, 0x81e9, 0x80f7, 0x8c00
ax_pose_terminator
sNumelPose192:
ax_pose 21, 0x01e7, 0x90ef, 0x8c00
ax_pose_terminator
sNumelPose193:
ax_pose 19, 0x01e7, 0x90f0, 0x8c00
ax_pose_terminator
sNumelPose194:
ax_pose 17, 0x01e9, 0x90f0, 0x8c00
ax_pose_terminator
sNumelPose195:
ax_pose 0, 0x81ee, 0x80f8, 0x8c00
ax_pose_terminator
sNumelPose196:
ax_pose 3, 0x01ee, 0x80f2, 0x8c00
ax_pose_terminator
sNumelPose197:
ax_pose 6, 0x01ec, 0x80f0, 0x8c00
ax_pose_terminator
sNumelPose198:
ax_pose 9, 0x01ec, 0x80f2, 0x8c00
ax_pose_terminator
sNumelPose199:
ax_pose 12, 0x81ed, 0x80f8, 0x8c00
ax_pose_terminator
sNumelPose200:
ax_pose 9, 0x01ec, 0x90ed, 0x8c00
ax_pose_terminator
sNumelPose201:
ax_pose 6, 0x01ec, 0x90ef, 0x8c00
ax_pose_terminator
sNumelPose202:
ax_pose 3, 0x01ee, 0x90ee, 0x8c00
ax_pose_terminator
.align 2
sNumelAnims_1_1:
ax_anim 8, 0, 0, 0, 0, 0, 0,
ax_anim 10, 0, 1, 0, 0, 0, 0,
ax_anim 8, 0, 0, 0, 0, 0, 0,
ax_anim 10, 0, 2, 0, 0, 0, 0,
ax_anim_terminator
sNumelAnims_1_2:
ax_anim 8, 0, 3, 0, 0, 0, 0,
ax_anim 10, 0, 4, 0, 0, 0, 0,
ax_anim 8, 0, 3, 0, 0, 0, 0,
ax_anim 10, 0, 5, 0, 0, 0, 0,
ax_anim_terminator
sNumelAnims_1_3:
ax_anim 8, 0, 6, 0, 0, 0, 0,
ax_anim 10, 0, 7, 0, 0, 0, 0,
ax_anim 8, 0, 6, 0, 0, 0, 0,
ax_anim 10, 0, 8, 0, 0, 0, 0,
ax_anim_terminator
sNumelAnims_1_4:
ax_anim 8, 0, 9, 0, 0, 0, 0,
ax_anim 10, 0, 10, 0, 0, 0, 0,
ax_anim 8, 0, 9, 0, 0, 0, 0,
ax_anim 10, 0, 11, 0, 0, 0, 0,
ax_anim_terminator
sNumelAnims_1_5:
ax_anim 8, 0, 12, 0, 0, 0, 0,
ax_anim 10, 0, 13, 0, 0, 0, 0,
ax_anim 8, 0, 12, 0, 0, 0, 0,
ax_anim 10, 0, 14, 0, 0, 0, 0,
ax_anim_terminator
sNumelAnims_1_6:
ax_anim 8, 0, 15, 0, 0, 0, 0,
ax_anim 10, 0, 16, 0, 0, 0, 0,
ax_anim 8, 0, 15, 0, 0, 0, 0,
ax_anim 10, 0, 17, 0, 0, 0, 0,
ax_anim_terminator
sNumelAnims_1_7:
ax_anim 8, 0, 18, 0, 0, 0, 0,
ax_anim 10, 0, 19, 0, 0, 0, 0,
ax_anim 8, 0, 18, 0, 0, 0, 0,
ax_anim 10, 0, 20, 0, 0, 0, 0,
ax_anim_terminator
sNumelAnims_1_8:
ax_anim 8, 0, 21, 0, 0, 0, 0,
ax_anim 10, 0, 22, 0, 0, 0, 0,
ax_anim 8, 0, 21, 0, 0, 0, 0,
ax_anim 10, 0, 23, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sNumelAnims_2_1:
ax_anim 2, 0, 24, 0, 0, 0, 0,
ax_anim 2, 0, 24, 0, -1, 0, -1,
ax_anim 4, 0, 24, 0, -2, 0, -2,
ax_anim 2, 0, 25, 0, -3, 0, 1,
ax_anim 2, 0, 25, 0, 1, 0, 4,
ax_anim 2, 2, 25, 0, 10, 0, 12,
ax_anim 2, 0, 26, 0, 17, 0, 17,
ax_anim 2, 1, 26, 1, 17, 1, 17,
ax_anim 2, 0, 26, 0, 17, 0, 17,
ax_anim 2, 0, 26, 1, 17, 1, 17,
ax_anim 2, 0, 24, 0, 6, 0, 6,
ax_anim_terminator
sNumelAnims_2_2:
ax_anim 2, 0, 27, 0, 0, 0, 0,
ax_anim 2, 0, 27, -1, -1, -1, -1,
ax_anim 4, 0, 27, -2, -2, -2, -2,
ax_anim 2, 0, 28, 3, -1, 3, 3,
ax_anim 2, 0, 28, 9, 4, 9, 9,
ax_anim 2, 2, 28, 15, 14, 15, 16,
ax_anim 2, 0, 29, 17, 18, 17, 18,
ax_anim 2, 1, 29, 18, 17, 18, 17,
ax_anim 2, 0, 29, 17, 18, 17, 18,
ax_anim 2, 0, 29, 18, 17, 18, 17,
ax_anim 2, 0, 27, 8, 8, 8, 8,
ax_anim_terminator
sNumelAnims_2_3:
ax_anim 2, 0, 30, 0, 0, 0, 0,
ax_anim 2, 0, 30, -1, 0, -1, 0,
ax_anim 4, 0, 30, -2, 0, -2, 0,
ax_anim 2, 0, 31, 4, -3, 4, 0,
ax_anim 2, 0, 31, 9, -5, 9, 0,
ax_anim 2, 2, 31, 13, -4, 13, 0,
ax_anim 2, 0, 32, 18, 0, 18, 0,
ax_anim 2, 1, 32, 18, 1, 18, 1,
ax_anim 2, 0, 32, 18, 0, 18, 0,
ax_anim 2, 0, 32, 18, 1, 18, 1,
ax_anim 2, 0, 30, 6, 0, 6, -1,
ax_anim_terminator
sNumelAnims_2_4:
ax_anim 2, 0, 33, 0, 0, 0, 0,
ax_anim 2, 0, 33, -1, 1, -1, 1,
ax_anim 4, 0, 33, -2, 2, -2, 2,
ax_anim 2, 0, 34, 3, -9, 3, -3,
ax_anim 2, 0, 34, 8, -17, 8, -8,
ax_anim 2, 2, 34, 16, -20, 16, -16,
ax_anim 2, 0, 35, 19, -21, 19, -19,
ax_anim 2, 1, 35, 20, -20, 20, -18,
ax_anim 2, 0, 35, 19, -21, 19, -19,
ax_anim 2, 0, 35, 20, -20, 20, -18,
ax_anim 2, 0, 33, 6, -6, 6, -6,
ax_anim_terminator
sNumelAnims_2_5:
ax_anim 2, 0, 36, 0, 0, 0, 0,
ax_anim 2, 0, 36, 0, 1, 0, 1,
ax_anim 4, 0, 36, 0, 2, 0, 2,
ax_anim 2, 0, 37, 0, -5, 0, -1,
ax_anim 2, 0, 37, 0, -11, 0, -6,
ax_anim 2, 2, 37, 0, -16, 0, -13,
ax_anim 2, 0, 38, 0, -19, 0, -19,
ax_anim 2, 1, 38, 1, -19, 1, -19,
ax_anim 2, 0, 38, 0, -19, 0, -19,
ax_anim 2, 0, 38, 1, -19, 1, -19,
ax_anim 2, 0, 36, 0, -6, 0, -6,
ax_anim_terminator
sNumelAnims_2_6:
ax_anim 2, 0, 39, 0, 0, 0, 0,
ax_anim 2, 0, 39, 1, 1, 1, 1,
ax_anim 4, 0, 39, 2, 2, 2, 2,
ax_anim 2, 0, 40, -3, -9, -3, -3,
ax_anim 2, 0, 40, -8, -17, -8, -8,
ax_anim 2, 2, 40, -16, -20, -16, -16,
ax_anim 2, 0, 41, -19, -21, -19, -19,
ax_anim 2, 1, 41, -20, -20, -20, -18,
ax_anim 2, 0, 41, -19, -21, -19, -19,
ax_anim 2, 0, 41, -20, -20, -20, -18,
ax_anim 2, 0, 39, -6, -6, -6, -6,
ax_anim_terminator
sNumelAnims_2_7:
ax_anim 2, 0, 42, 0, 0, 0, 0,
ax_anim 2, 0, 42, 1, 0, 1, 0,
ax_anim 4, 0, 42, 2, 0, 2, 0,
ax_anim 2, 0, 43, -4, -3, -4, 0,
ax_anim 2, 0, 43, -9, -5, -9, 0,
ax_anim 2, 2, 43, -13, -4, -13, 0,
ax_anim 2, 0, 44, -18, 0, -18, 0,
ax_anim 2, 1, 44, -18, 1, -18, 1,
ax_anim 2, 0, 44, -18, 0, -18, 0,
ax_anim 2, 0, 44, -18, 1, -18, 1,
ax_anim 2, 0, 42, -6, 0, -6, -1,
ax_anim_terminator
sNumelAnims_2_8:
ax_anim 2, 0, 45, 0, 0, 0, 0,
ax_anim 2, 0, 45, 1, -1, 1, -1,
ax_anim 4, 0, 45, 2, -2, 2, -2,
ax_anim 2, 0, 46, -3, -1, -3, 3,
ax_anim 2, 0, 46, -9, 4, -9, 9,
ax_anim 2, 2, 46, -15, 14, -15, 16,
ax_anim 2, 0, 47, -17, 18, -17, 18,
ax_anim 2, 1, 47, -18, 17, -18, 17,
ax_anim 2, 0, 47, -17, 18, -17, 18,
ax_anim 2, 0, 47, -18, 17, -18, 17,
ax_anim 2, 0, 45, -8, 8, -8, 8,
ax_anim_terminator
.align 2
sNumelAnims_3_1:
ax_anim 2, 0, 48, 0, 0, 0, 0,
ax_anim 2, 0, 48, 0, -1, 0, -1,
ax_anim 4, 0, 48, 0, -2, 0, -2,
ax_anim 2, 0, 49, 0, -3, 0, 1,
ax_anim 2, 0, 49, 0, 1, 0, 4,
ax_anim 2, 2, 49, 0, 10, 0, 12,
ax_anim 2, 0, 50, 0, 17, 0, 17,
ax_anim 2, 1, 50, 1, 17, 1, 17,
ax_anim 2, 0, 50, 0, 17, 0, 17,
ax_anim 2, 0, 50, 1, 17, 1, 17,
ax_anim 2, 0, 48, 0, 6, 0, 6,
ax_anim_terminator
sNumelAnims_3_2:
ax_anim 2, 0, 51, 0, 0, 0, 0,
ax_anim 2, 0, 51, -1, -1, -1, -1,
ax_anim 4, 0, 51, -2, -2, -2, -2,
ax_anim 2, 0, 52, 3, -1, 3, 3,
ax_anim 2, 0, 52, 9, 4, 9, 9,
ax_anim 2, 2, 52, 15, 14, 15, 16,
ax_anim 2, 0, 53, 17, 18, 17, 18,
ax_anim 2, 1, 53, 18, 17, 18, 17,
ax_anim 2, 0, 53, 17, 18, 17, 18,
ax_anim 2, 0, 53, 18, 17, 18, 17,
ax_anim 2, 0, 51, 8, 8, 8, 8,
ax_anim_terminator
sNumelAnims_3_3:
ax_anim 2, 0, 54, 0, 0, 0, 0,
ax_anim 2, 0, 54, -1, 0, -1, 0,
ax_anim 4, 0, 54, -2, 0, -2, 0,
ax_anim 2, 0, 55, 4, -3, 4, 0,
ax_anim 2, 0, 55, 9, -5, 9, 0,
ax_anim 2, 2, 55, 13, -4, 13, 0,
ax_anim 2, 0, 56, 18, 0, 18, 0,
ax_anim 2, 1, 56, 18, 1, 18, 1,
ax_anim 2, 0, 56, 18, 0, 18, 0,
ax_anim 2, 0, 56, 18, 1, 18, 1,
ax_anim 2, 0, 54, 6, 0, 6, -1,
ax_anim_terminator
sNumelAnims_3_4:
ax_anim 2, 0, 57, 0, 0, 0, 0,
ax_anim 2, 0, 57, -1, 1, -1, 1,
ax_anim 4, 0, 57, -2, 2, -2, 2,
ax_anim 2, 0, 58, 3, -9, 3, -3,
ax_anim 2, 0, 58, 8, -17, 8, -8,
ax_anim 2, 2, 58, 16, -20, 16, -16,
ax_anim 2, 0, 59, 19, -21, 19, -19,
ax_anim 2, 1, 59, 20, -20, 20, -18,
ax_anim 2, 0, 59, 19, -21, 19, -19,
ax_anim 2, 0, 59, 20, -20, 20, -18,
ax_anim 2, 0, 57, 6, -6, 6, -6,
ax_anim_terminator
sNumelAnims_3_5:
ax_anim 2, 0, 60, 0, 0, 0, 0,
ax_anim 2, 0, 60, 0, 1, 0, 1,
ax_anim 4, 0, 60, 0, 2, 0, 2,
ax_anim 2, 0, 61, 0, -5, 0, -1,
ax_anim 2, 0, 61, 0, -11, 0, -6,
ax_anim 2, 2, 61, 0, -16, 0, -13,
ax_anim 2, 0, 62, 0, -19, 0, -19,
ax_anim 2, 1, 62, 1, -19, 1, -19,
ax_anim 2, 0, 62, 0, -19, 0, -19,
ax_anim 2, 0, 62, 1, -19, 1, -19,
ax_anim 2, 0, 60, 0, -6, 0, -6,
ax_anim_terminator
sNumelAnims_3_6:
ax_anim 2, 0, 63, 0, 0, 0, 0,
ax_anim 2, 0, 63, 1, 1, 1, 1,
ax_anim 4, 0, 63, 2, 2, 2, 2,
ax_anim 2, 0, 64, -3, -9, -3, -3,
ax_anim 2, 0, 64, -8, -17, -8, -8,
ax_anim 2, 2, 64, -16, -20, -16, -16,
ax_anim 2, 0, 65, -19, -21, -19, -19,
ax_anim 2, 1, 65, -20, -20, -20, -18,
ax_anim 2, 0, 65, -19, -21, -19, -19,
ax_anim 2, 0, 65, -20, -20, -20, -18,
ax_anim 2, 0, 63, -6, -6, -6, -6,
ax_anim_terminator
sNumelAnims_3_7:
ax_anim 2, 0, 66, 0, 0, 0, 0,
ax_anim 2, 0, 66, 1, 0, 1, 0,
ax_anim 4, 0, 66, 2, 0, 2, 0,
ax_anim 2, 0, 67, -4, -3, -4, 0,
ax_anim 2, 0, 67, -9, -5, -9, 0,
ax_anim 2, 2, 67, -13, -4, -13, 0,
ax_anim 2, 0, 68, -18, 0, -18, 0,
ax_anim 2, 1, 68, -18, 1, -18, 1,
ax_anim 2, 0, 68, -18, 0, -18, 0,
ax_anim 2, 0, 68, -18, 1, -18, 1,
ax_anim 2, 0, 66, -6, 0, -6, -1,
ax_anim_terminator
sNumelAnims_3_8:
ax_anim 2, 0, 69, 0, 0, 0, 0,
ax_anim 2, 0, 69, 1, -1, 1, -1,
ax_anim 4, 0, 69, 2, -2, 2, -2,
ax_anim 2, 0, 70, -3, -1, -3, 3,
ax_anim 2, 0, 70, -9, 4, -9, 9,
ax_anim 2, 2, 70, -15, 14, -15, 16,
ax_anim 2, 0, 71, -17, 18, -17, 18,
ax_anim 2, 1, 71, -18, 17, -18, 17,
ax_anim 2, 0, 71, -17, 18, -17, 18,
ax_anim 2, 0, 71, -18, 17, -18, 17,
ax_anim 2, 0, 69, -8, 8, -8, 8,
ax_anim_terminator
.align 2
sNumelAnims_4_1:
ax_anim 2, 0, 73, 0, -2, 0, -2,
ax_anim 6, 2, 73, 0, -3, 0, -3,
ax_anim 2, 0, 72, 0, -1, 0, -1,
ax_anim 2, 1, 74, 0, 3, 0, 3,
ax_anim 2, 0, 74, 1, 3, 1, 3,
ax_anim 2, 0, 74, 0, 3, 0, 3,
ax_anim 2, 0, 74, 1, 3, 1, 3,
ax_anim 2, 0, 74, 0, 3, 0, 3,
ax_anim 2, 0, 74, 1, 3, 1, 3,
ax_anim 2, 0, 74, 0, 3, 0, 3,
ax_anim 2, 0, 72, 0, 1, 0, 1,
ax_anim_terminator
sNumelAnims_4_2:
ax_anim 2, 0, 76, -2, -2, -2, -2,
ax_anim 6, 2, 76, -3, -3, -3, -3,
ax_anim 2, 0, 75, -1, -1, -1, -1,
ax_anim 2, 1, 77, 2, 2, 2, 2,
ax_anim 2, 0, 77, 3, 1, 3, 1,
ax_anim 2, 0, 77, 2, 2, 2, 2,
ax_anim 2, 0, 77, 3, 1, 3, 1,
ax_anim 2, 0, 77, 2, 2, 2, 2,
ax_anim 2, 0, 77, 3, 1, 3, 1,
ax_anim 2, 0, 77, 2, 2, 2, 2,
ax_anim 2, 0, 75, 1, 1, 1, 1,
ax_anim_terminator
sNumelAnims_4_3:
ax_anim 2, 0, 79, -2, 0, -2, 0,
ax_anim 6, 2, 79, -3, 0, -3, 0,
ax_anim 2, 0, 78, -1, 0, -1, 0,
ax_anim 2, 1, 80, 3, 0, 3, 0,
ax_anim 2, 0, 80, 3, 1, 3, 1,
ax_anim 2, 0, 80, 3, 0, 3, 0,
ax_anim 2, 0, 80, 3, 1, 3, 1,
ax_anim 2, 0, 80, 3, 0, 3, 0,
ax_anim 2, 0, 80, 3, 1, 3, 1,
ax_anim 2, 0, 80, 3, 0, 3, 0,
ax_anim 2, 0, 78, 1, 0, 1, 0,
ax_anim_terminator
sNumelAnims_4_4:
ax_anim 2, 0, 82, -2, 2, -2, 2,
ax_anim 6, 2, 82, -3, 3, -3, 3,
ax_anim 2, 0, 81, -1, 1, -1, 1,
ax_anim 2, 1, 83, 2, -2, 2, -2,
ax_anim 2, 0, 83, 3, -1, 3, -1,
ax_anim 2, 0, 83, 2, -2, 2, -2,
ax_anim 2, 0, 83, 3, -1, 3, -1,
ax_anim 2, 0, 83, 2, -2, 2, -2,
ax_anim 2, 0, 83, 3, -1, 3, -1,
ax_anim 2, 0, 83, 2, -2, 2, -2,
ax_anim 2, 0, 81, 1, -1, 1, -1,
ax_anim_terminator
sNumelAnims_4_5:
ax_anim 2, 0, 85, 0, 2, 0, 2,
ax_anim 6, 2, 85, 0, 3, 0, 3,
ax_anim 2, 0, 84, 0, 1, 0, 1,
ax_anim 2, 1, 86, 0, -3, 0, -3,
ax_anim 2, 0, 86, 1, -3, 1, -3,
ax_anim 2, 0, 86, 0, -3, 0, -3,
ax_anim 2, 0, 86, 1, -3, 1, -3,
ax_anim 2, 0, 86, 0, -3, 0, -3,
ax_anim 2, 0, 86, 1, -3, 1, -3,
ax_anim 2, 0, 86, 0, -3, 0, -3,
ax_anim 2, 0, 84, 0, -1, 0, -1,
ax_anim_terminator
sNumelAnims_4_6:
ax_anim 2, 0, 88, 2, 2, 2, 2,
ax_anim 6, 2, 88, 3, 3, 3, 3,
ax_anim 2, 0, 87, 1, 1, 1, 1,
ax_anim 2, 1, 89, -2, -2, -2, -2,
ax_anim 2, 0, 89, -3, -1, -3, -1,
ax_anim 2, 0, 89, -2, -2, -2, -2,
ax_anim 2, 0, 89, -3, -1, -3, -1,
ax_anim 2, 0, 89, -2, -2, -2, -2,
ax_anim 2, 0, 89, -3, -1, -3, -1,
ax_anim 2, 0, 89, -2, -2, -2, -2,
ax_anim 2, 0, 87, -1, -1, -1, -1,
ax_anim_terminator
sNumelAnims_4_7:
ax_anim 2, 0, 91, 2, 0, 2, 0,
ax_anim 6, 2, 91, 3, 0, 3, 0,
ax_anim 2, 0, 90, 1, 0, 1, 0,
ax_anim 2, 1, 92, -3, 0, -3, 0,
ax_anim 2, 0, 92, -3, 1, -3, 1,
ax_anim 2, 0, 92, -3, 0, -3, 0,
ax_anim 2, 0, 92, -3, 1, -3, 1,
ax_anim 2, 0, 92, -3, 0, -3, 0,
ax_anim 2, 0, 92, -3, 1, -3, 1,
ax_anim 2, 0, 92, -3, 0, -3, 0,
ax_anim 2, 0, 90, -1, 0, -1, 0,
ax_anim_terminator
sNumelAnims_4_8:
ax_anim 2, 0, 94, 2, -2, 2, -2,
ax_anim 6, 2, 94, 3, -3, 3, -3,
ax_anim 2, 0, 93, 1, -1, 1, -1,
ax_anim 2, 1, 95, -2, 2, -2, 2,
ax_anim 2, 0, 95, -3, 1, -3, 1,
ax_anim 2, 0, 95, -2, 2, -2, 2,
ax_anim 2, 0, 95, -3, 1, -3, 1,
ax_anim 2, 0, 95, -2, 2, -2, 2,
ax_anim 2, 0, 95, -3, 1, -3, 1,
ax_anim 2, 0, 95, -2, 2, -2, 2,
ax_anim 2, 0, 93, -1, 1, -1, 1,
ax_anim_terminator
.align 2
sNumelAnims_5_1:
ax_anim 6, 2, 97, 0, 0, 0, 0,
ax_anim 3, 0, 97, 0, 3, 0, 3,
ax_anim 3, 0, 98, 1, 3, 1, 3,
ax_anim 3, 0, 97, 0, 3, 0, 3,
ax_anim 3, 1, 98, 1, 3, 1, 3,
ax_anim 3, 0, 97, 0, 3, 0, 3,
ax_anim 3, 0, 98, 1, 3, 1, 3,
ax_anim 3, 0, 97, 0, 3, 0, 3,
ax_anim 2, 0, 96, 0, 1, 0, 1,
ax_anim_terminator
sNumelAnims_5_2:
ax_anim 6, 2, 100, 1, 1, 1, 1,
ax_anim 3, 0, 100, 3, 3, 3, 3,
ax_anim 3, 0, 101, 4, 2, 4, 2,
ax_anim 3, 0, 100, 3, 3, 3, 3,
ax_anim 3, 1, 101, 4, 2, 4, 2,
ax_anim 3, 0, 100, 3, 3, 3, 3,
ax_anim 3, 0, 101, 4, 2, 4, 2,
ax_anim 3, 0, 100, 3, 3, 3, 3,
ax_anim 2, 0, 99, 1, 1, 1, 1,
ax_anim_terminator
sNumelAnims_5_3:
ax_anim 6, 2, 103, -1, 0, -1, 0,
ax_anim 3, 0, 103, 3, 0, 3, 0,
ax_anim 3, 0, 104, 3, 1, 3, 1,
ax_anim 3, 0, 103, 3, 0, 3, 0,
ax_anim 3, 1, 104, 3, 1, 3, 1,
ax_anim 3, 0, 103, 3, 0, 3, 0,
ax_anim 3, 0, 104, 3, 1, 3, 1,
ax_anim 3, 0, 103, 3, 0, 3, 0,
ax_anim 2, 0, 102, 1, 0, 1, 0,
ax_anim_terminator
sNumelAnims_5_4:
ax_anim 6, 2, 106, 0, 0, 0, 0,
ax_anim 3, 0, 106, 3, -3, 3, -3,
ax_anim 3, 0, 107, 4, -2, 4, -2,
ax_anim 3, 0, 106, 3, -3, 3, -3,
ax_anim 3, 1, 107, 4, -2, 4, -2,
ax_anim 3, 0, 106, 3, -3, 3, -3,
ax_anim 3, 0, 107, 4, -2, 4, -2,
ax_anim 3, 0, 106, 3, -3, 3, -3,
ax_anim 2, 0, 105, 1, -1, 1, -1,
ax_anim_terminator
sNumelAnims_5_5:
ax_anim 6, 2, 109, 0, 0, 0, 0,
ax_anim 3, 0, 109, 0, -3, 0, -3,
ax_anim 3, 0, 110, 1, -3, 1, -3,
ax_anim 3, 0, 109, 0, -3, 0, -3,
ax_anim 3, 1, 110, 1, -3, 1, -3,
ax_anim 3, 0, 109, 0, -3, 0, -3,
ax_anim 3, 0, 110, 1, -3, 1, -3,
ax_anim 3, 0, 109, 0, -3, 0, -3,
ax_anim 2, 0, 108, 0, -1, 0, -1,
ax_anim_terminator
sNumelAnims_5_6:
ax_anim 6, 2, 112, 0, 0, 0, 0,
ax_anim 3, 0, 112, -3, -3, -3, -3,
ax_anim 3, 0, 113, -4, -2, -4, -2,
ax_anim 3, 0, 112, -3, -3, -3, -3,
ax_anim 3, 1, 113, -4, -2, -4, -2,
ax_anim 3, 0, 112, -3, -3, -3, -3,
ax_anim 3, 0, 113, -4, -2, -4, -2,
ax_anim 3, 0, 112, -3, -3, -3, -3,
ax_anim 2, 0, 111, -1, -1, -1, -1,
ax_anim_terminator
sNumelAnims_5_7:
ax_anim 6, 2, 115, 1, 0, 1, 0,
ax_anim 3, 0, 115, -3, 0, -3, 0,
ax_anim 3, 0, 116, -3, 1, -3, 1,
ax_anim 3, 0, 115, -3, 0, -3, 0,
ax_anim 3, 1, 116, -3, 1, -3, 1,
ax_anim 3, 0, 115, -3, 0, -3, 0,
ax_anim 3, 0, 116, -3, 1, -3, 1,
ax_anim 3, 0, 115, -3, 0, -3, 0,
ax_anim 2, 0, 114, -1, 0, -1, 0,
ax_anim_terminator
sNumelAnims_5_8:
ax_anim 6, 2, 118, -1, 1, -1, 1,
ax_anim 3, 0, 118, -3, 3, -3, 3,
ax_anim 3, 0, 119, -4, 2, -4, 2,
ax_anim 3, 0, 118, -3, 3, -3, 3,
ax_anim 3, 1, 119, -4, 2, -4, 2,
ax_anim 3, 0, 118, -3, 3, -3, 3,
ax_anim 3, 0, 119, -4, 2, -4, 2,
ax_anim 3, 0, 118, -3, 3, -3, 3,
ax_anim 2, 0, 117, -1, 1, -1, 1,
ax_anim_terminator
.align 2
sNumelAnims_6_1:
ax_anim 30, 0, 120, 0, 0, 0, 0,
ax_anim 35, 0, 121, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sNumelAnims_7_1:
ax_anim 2, 0, 122, 0, -2, 0, -2,
ax_anim 8, 0, 122, 0, -3, 0, -3,
ax_anim_terminator
sNumelAnims_7_2:
ax_anim 2, 0, 123, -2, -2, -2, -2,
ax_anim 8, 0, 123, -3, -3, -3, -3,
ax_anim_terminator
sNumelAnims_7_3:
ax_anim 2, 0, 124, -2, 0, -2, 0,
ax_anim 8, 0, 124, -3, 0, -3, 0,
ax_anim_terminator
sNumelAnims_7_4:
ax_anim 2, 0, 125, -2, 2, -2, 2,
ax_anim 8, 0, 125, -3, 3, -3, 3,
ax_anim_terminator
sNumelAnims_7_5:
ax_anim 2, 0, 126, 0, 2, 0, 2,
ax_anim 8, 0, 126, 0, 3, 0, 3,
ax_anim_terminator
sNumelAnims_7_6:
ax_anim 2, 0, 127, 2, 2, 2, 2,
ax_anim 8, 0, 127, 3, 3, 3, 3,
ax_anim_terminator
sNumelAnims_7_7:
ax_anim 2, 0, 128, 2, 0, 2, 0,
ax_anim 8, 0, 128, 3, 0, 3, 0,
ax_anim_terminator
sNumelAnims_7_8:
ax_anim 2, 0, 129, 2, -2, 2, -2,
ax_anim 8, 0, 129, 3, -3, 3, -3,
ax_anim_terminator
.align 2
sNumelAnims_8_1:
ax_anim 40, 0, 130, 0, 0, 0, 0,
ax_anim 8, 0, 131, 0, 0, 0, 0,
ax_anim 12, 0, 130, 0, 0, 0, 0,
ax_anim 8, 0, 131, 0, 0, 0, 0,
ax_anim_terminator
sNumelAnims_8_2:
ax_anim 40, 0, 132, 0, 0, 0, 0,
ax_anim 8, 0, 133, 0, 0, 0, 0,
ax_anim 12, 0, 132, 0, 0, 0, 0,
ax_anim 8, 0, 133, 0, 0, 0, 0,
ax_anim_terminator
sNumelAnims_8_3:
ax_anim 40, 0, 134, 0, 0, 0, 0,
ax_anim 8, 0, 135, 0, 0, 0, 0,
ax_anim 12, 0, 134, 0, 0, 0, 0,
ax_anim 8, 0, 135, 0, 0, 0, 0,
ax_anim_terminator
sNumelAnims_8_4:
ax_anim 40, 0, 136, 0, 0, 0, 0,
ax_anim 8, 0, 137, 0, 0, 0, 0,
ax_anim 12, 0, 136, 0, 0, 0, 0,
ax_anim 8, 0, 137, 0, 0, 0, 0,
ax_anim_terminator
sNumelAnims_8_5:
ax_anim 40, 0, 138, 0, 0, 0, 0,
ax_anim 8, 0, 139, 0, 0, 0, 0,
ax_anim 12, 0, 138, 0, 0, 0, 0,
ax_anim 8, 0, 139, 0, 0, 0, 0,
ax_anim_terminator
sNumelAnims_8_6:
ax_anim 40, 0, 140, 0, 0, 0, 0,
ax_anim 8, 0, 141, 0, 0, 0, 0,
ax_anim 12, 0, 140, 0, 0, 0, 0,
ax_anim 8, 0, 141, 0, 0, 0, 0,
ax_anim_terminator
sNumelAnims_8_7:
ax_anim 40, 0, 142, 0, 0, 0, 0,
ax_anim 8, 0, 143, 0, 0, 0, 0,
ax_anim 12, 0, 142, 0, 0, 0, 0,
ax_anim 8, 0, 143, 0, 0, 0, 0,
ax_anim_terminator
sNumelAnims_8_8:
ax_anim 40, 0, 144, 0, 0, 0, 0,
ax_anim 8, 0, 145, 0, 0, 0, 0,
ax_anim 12, 0, 144, 0, 0, 0, 0,
ax_anim 8, 0, 145, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sNumelAnims_9_1:
ax_anim 2, 0, 146, 0, 0, 0, 0,
ax_anim 1, 0, 147, 8, 3, 8, 3,
ax_anim 2, 0, 148, 11, 10, 11, 10,
ax_anim 2, 0, 149, 7, 16, 7, 16,
ax_anim 3, 0, 150, 0, 19, 0, 19,
ax_anim 2, 3, 151, -7, 16, -7, 16,
ax_anim 2, 0, 152, -11, 10, -11, 10,
ax_anim 1, 0, 153, -8, 3, -8, 3,
ax_anim 1, 0, 146, 0, 0, 0, 0,
ax_anim_terminator
sNumelAnims_9_2:
ax_anim 2, 0, 153, 0, 0, 0, 0,
ax_anim 1, 0, 146, 10, 0, 10, 0,
ax_anim 2, 0, 147, 17, 3, 17, 3,
ax_anim 2, 0, 148, 22, 10, 22, 10,
ax_anim 3, 0, 149, 20, 18, 20, 18,
ax_anim 2, 3, 150, 10, 19, 10, 19,
ax_anim 2, 0, 151, 3, 14, 3, 14,
ax_anim 1, 0, 152, -1, 7, -1, 7,
ax_anim 1, 0, 153, 0, 0, 0, 0,
ax_anim_terminator
sNumelAnims_9_3:
ax_anim 2, 0, 152, 0, 0, 0, 0,
ax_anim 1, 0, 153, 4, -5, 4, -5,
ax_anim 2, 0, 146, 12, -7, 12, -7,
ax_anim 2, 0, 147, 20, -5, 20, -5,
ax_anim 3, 0, 148, 22, -1, 22, -1,
ax_anim 2, 3, 149, 17, 4, 17, 4,
ax_anim 2, 0, 150, 11, 5, 11, 5,
ax_anim 1, 0, 151, 5, 4, 5, 4,
ax_anim 1, 0, 152, 0, 0, 0, 0,
ax_anim_terminator
sNumelAnims_9_4:
ax_anim 2, 0, 151, 0, 0, 0, 0,
ax_anim 1, 0, 152, -1, -9, -1, -9,
ax_anim 2, 0, 153, 2, -17, 2, -17,
ax_anim 2, 0, 146, 11, -22, 11, -22,
ax_anim 3, 0, 147, 21, -25, 21, -25,
ax_anim 2, 3, 148, 24, -16, 24, -16,
ax_anim 2, 0, 149, 17, -6, 17, -6,
ax_anim 1, 0, 150, 10, -1, 10, -1,
ax_anim 1, 0, 151, 0, 0, 0, 0,
ax_anim_terminator
sNumelAnims_9_5:
ax_anim 2, 0, 150, 0, 0, 0, 0,
ax_anim 1, 0, 151, -8, -3, -8, -3,
ax_anim 2, 0, 152, -11, -12, -11, -12,
ax_anim 2, 0, 153, -8, -22, -8, -22,
ax_anim 3, 0, 146, 0, -25, 0, -25,
ax_anim 2, 3, 147, 8, -22, 8, -22,
ax_anim 2, 0, 148, 11, -12, 11, -12,
ax_anim 1, 0, 149, 8, -3, 8, -3,
ax_anim 1, 0, 150, 0, 0, 0, 0,
ax_anim_terminator
sNumelAnims_9_6:
ax_anim 2, 0, 149, 0, 0, 0, 0,
ax_anim 1, 0, 148, 1, -8, 1, -8,
ax_anim 2, 0, 147, -2, -17, -2, -17,
ax_anim 2, 0, 146, -11, -22, -11, -22,
ax_anim 3, 0, 153, -21, -25, -21, -25,
ax_anim 2, 3, 152, -24, -16, -24, -16,
ax_anim 2, 0, 151, -17, -6, -17, -6,
ax_anim 1, 0, 150, -10, -1, -10, -1,
ax_anim 1, 0, 149, 0, 0, 0, 0,
ax_anim_terminator
sNumelAnims_9_7:
ax_anim 2, 0, 148, 0, 0, 0, 0,
ax_anim 1, 0, 147, -4, -5, -4, -5,
ax_anim 2, 0, 146, -12, -7, -12, -7,
ax_anim 2, 0, 153, -20, -5, -20, -5,
ax_anim 3, 0, 152, -22, -1, -22, -1,
ax_anim 2, 3, 151, -17, 4, -17, 4,
ax_anim 2, 0, 150, -11, 5, -11, 5,
ax_anim 1, 0, 149, -5, 4, -5, 4,
ax_anim 1, 0, 148, 0, 0, 0, 0,
ax_anim_terminator
sNumelAnims_9_8:
ax_anim 2, 0, 147, 0, 0, 0, 0,
ax_anim 1, 0, 146, -10, 0, -10, 0,
ax_anim 2, 0, 153, -17, 3, -17, 3,
ax_anim 2, 0, 152, -22, 10, -22, 10,
ax_anim 3, 0, 151, -20, 18, -20, 18,
ax_anim 2, 3, 150, -10, 19, -10, 19,
ax_anim 2, 0, 149, -3, 14, -3, 14,
ax_anim 1, 0, 148, 1, 7, 1, 7,
ax_anim 1, 0, 147, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sNumelAnims_10_1:
ax_anim 2, 0, 154, 0, 0, 0, 0,
ax_anim 2, 0, 154, 6, 0, 6, 0,
ax_anim 2, 0, 154, -6, 0, -6, 0,
ax_anim 2, 0, 154, 10, 0, 10, 0,
ax_anim 2, 0, 154, -10, 0, -10, 0,
ax_anim 2, 0, 154, 12, 0, 12, 0,
ax_anim 3, 0, 154, -12, 0, -12, 0,
ax_anim 3, 0, 154, 13, 0, 13, 0,
ax_anim 3, 0, 154, -13, 0, -13, 0,
ax_anim 2, 0, 154, 12, 0, 12, 0,
ax_anim 3, 0, 154, -12, 0, -12, 0,
ax_anim 2, 0, 154, 10, 0, 10, 0,
ax_anim 2, 0, 154, -10, 0, -10, 0,
ax_anim 2, 0, 154, 6, 0, 6, 0,
ax_anim 2, 0, 154, -6, 0, -6, 0,
ax_anim 2, 0, 154, 0, 0, 0, 0,
ax_anim_terminator
sNumelAnims_10_2:
ax_anim 2, 0, 155, 0, 0, 0, 0,
ax_anim 2, 0, 155, 6, -6, 6, -6,
ax_anim 2, 0, 155, -6, 6, -6, 6,
ax_anim 2, 0, 155, 10, -10, 10, -10,
ax_anim 2, 0, 155, -10, 10, -10, 10,
ax_anim 2, 0, 155, 12, -12, 12, -12,
ax_anim 3, 0, 155, -12, 12, -12, 12,
ax_anim 3, 0, 155, 13, -13, 13, -13,
ax_anim 3, 0, 155, -13, 13, -13, 13,
ax_anim 2, 0, 155, 12, -12, 12, -12,
ax_anim 3, 0, 155, -12, 12, -12, 12,
ax_anim 2, 0, 155, 10, -10, 10, -10,
ax_anim 2, 0, 155, -10, 10, -10, 10,
ax_anim 2, 0, 155, 6, -6, 6, -6,
ax_anim 2, 0, 155, -6, 6, -6, 6,
ax_anim 2, 0, 155, 0, 0, 0, 0,
ax_anim_terminator
sNumelAnims_10_3:
ax_anim 2, 0, 156, 0, 0, 0, 0,
ax_anim 2, 0, 156, 0, -6, 0, -6,
ax_anim 2, 0, 156, 0, 6, 0, 6,
ax_anim 2, 0, 156, 0, -10, 0, -10,
ax_anim 2, 0, 156, 0, 10, 0, 10,
ax_anim 2, 0, 156, 0, -12, 0, -12,
ax_anim 3, 0, 156, 0, 12, 0, 12,
ax_anim 3, 0, 156, 0, -13, 0, -13,
ax_anim 3, 0, 156, 0, 13, 0, 13,
ax_anim 2, 0, 156, 0, -12, 0, -12,
ax_anim 3, 0, 156, 0, 12, 0, 12,
ax_anim 2, 0, 156, 0, -10, 0, -10,
ax_anim 2, 0, 156, 0, 10, 0, 10,
ax_anim 2, 0, 156, 0, -6, 0, -6,
ax_anim 2, 0, 156, 0, 6, 0, 6,
ax_anim 2, 0, 156, 0, 0, 0, 0,
ax_anim_terminator
sNumelAnims_10_4:
ax_anim 2, 0, 157, 0, 0, 0, 0,
ax_anim 2, 0, 157, -6, -6, -6, -6,
ax_anim 2, 0, 157, 6, 6, 6, 6,
ax_anim 2, 0, 157, -10, -10, -10, -10,
ax_anim 2, 0, 157, 10, 10, 10, 10,
ax_anim 2, 0, 157, -12, -12, -12, -12,
ax_anim 3, 0, 157, 12, 12, 12, 12,
ax_anim 3, 0, 157, -13, -13, -13, -13,
ax_anim 3, 0, 157, 13, 13, 13, 13,
ax_anim 2, 0, 157, -12, -12, -12, -12,
ax_anim 3, 0, 157, 12, 12, 12, 12,
ax_anim 2, 0, 157, -10, -10, -10, -10,
ax_anim 2, 0, 157, 10, 10, 10, 10,
ax_anim 2, 0, 157, -6, -6, -6, -6,
ax_anim 2, 0, 157, 6, 6, 6, 6,
ax_anim 2, 0, 157, 0, 0, 0, 0,
ax_anim_terminator
sNumelAnims_10_5:
ax_anim 2, 0, 158, 0, 0, 0, 0,
ax_anim 2, 0, 158, 6, 0, 6, 0,
ax_anim 2, 0, 158, -6, 0, -6, 0,
ax_anim 2, 0, 158, 10, 0, 10, 0,
ax_anim 2, 0, 158, -10, 0, -10, 0,
ax_anim 2, 0, 158, 12, 0, 12, 0,
ax_anim 3, 0, 158, -12, 0, -12, 0,
ax_anim 3, 0, 158, 13, 0, 13, 0,
ax_anim 3, 0, 158, -13, 0, -13, 0,
ax_anim 2, 0, 158, 12, 0, 12, 0,
ax_anim 3, 0, 158, -12, 0, -12, 0,
ax_anim 2, 0, 158, 10, 0, 10, 0,
ax_anim 2, 0, 158, -10, 0, -10, 0,
ax_anim 2, 0, 158, 6, 0, 6, 0,
ax_anim 2, 0, 158, -6, 0, -6, 0,
ax_anim 2, 0, 158, 0, 0, 0, 0,
ax_anim_terminator
sNumelAnims_10_6:
ax_anim 2, 0, 159, 0, 0, 0, 0,
ax_anim 2, 0, 159, 6, -6, 6, -6,
ax_anim 2, 0, 159, -6, 6, -6, 6,
ax_anim 2, 0, 159, 10, -10, 10, -10,
ax_anim 2, 0, 159, -10, 10, -10, 10,
ax_anim 2, 0, 159, 12, -12, 12, -12,
ax_anim 3, 0, 159, -12, 12, -12, 12,
ax_anim 3, 0, 159, 13, -13, 13, -13,
ax_anim 3, 0, 159, -13, 13, -13, 13,
ax_anim 2, 0, 159, 12, -12, 12, -12,
ax_anim 3, 0, 159, -12, 12, -12, 12,
ax_anim 2, 0, 159, 10, -10, 10, -10,
ax_anim 2, 0, 159, -10, 10, -10, 10,
ax_anim 2, 0, 159, 6, -6, 6, -6,
ax_anim 2, 0, 159, -6, 6, -6, 6,
ax_anim 2, 0, 159, 0, 0, 0, 0,
ax_anim_terminator
sNumelAnims_10_7:
ax_anim 2, 0, 160, 0, 0, 0, 0,
ax_anim 2, 0, 160, 0, -6, 0, -6,
ax_anim 2, 0, 160, 0, 6, 0, 6,
ax_anim 2, 0, 160, 0, -10, 0, -10,
ax_anim 2, 0, 160, 0, 10, 0, 10,
ax_anim 2, 0, 160, 0, -12, 0, -12,
ax_anim 3, 0, 160, 0, 12, 0, 12,
ax_anim 3, 0, 160, 0, -13, 0, -13,
ax_anim 3, 0, 160, 0, 13, 0, 13,
ax_anim 2, 0, 160, 0, -12, 0, -12,
ax_anim 3, 0, 160, 0, 12, 0, 12,
ax_anim 2, 0, 160, 0, -10, 0, -10,
ax_anim 2, 0, 160, 0, 10, 0, 10,
ax_anim 2, 0, 160, 0, -6, 0, -6,
ax_anim 2, 0, 160, 0, 6, 0, 6,
ax_anim 2, 0, 160, 0, 0, 0, 0,
ax_anim_terminator
sNumelAnims_10_8:
ax_anim 2, 0, 161, 0, 0, 0, 0,
ax_anim 2, 0, 161, -6, -6, -6, -6,
ax_anim 2, 0, 161, 6, 6, 6, 6,
ax_anim 2, 0, 161, -10, -10, -10, -10,
ax_anim 2, 0, 161, 10, 10, 10, 10,
ax_anim 2, 0, 161, -12, -12, -12, -12,
ax_anim 3, 0, 161, 12, 12, 12, 12,
ax_anim 3, 0, 161, -13, -13, -13, -13,
ax_anim 3, 0, 161, 13, 13, 13, 13,
ax_anim 2, 0, 161, -12, -12, -12, -12,
ax_anim 3, 0, 161, 12, 12, 12, 12,
ax_anim 2, 0, 161, -10, -10, -10, -10,
ax_anim 2, 0, 161, 10, 10, 10, 10,
ax_anim 2, 0, 161, -6, -6, -6, -6,
ax_anim 2, 0, 161, 6, 6, 6, 6,
ax_anim 2, 0, 161, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sNumelAnims_11_1:
ax_anim 2, 0, 162, 0, 0, 0, 0,
ax_anim 1, 0, 163, 0, -10, 0, 0,
ax_anim 2, 0, 163, 0, -16, 0, 0,
ax_anim 3, 0, 163, 0, -20, 0, 0,
ax_anim 4, 0, 163, 0, -21, 0, 0,
ax_anim 4, 0, 162, 0, -22, 0, 0,
ax_anim 3, 0, 164, 0, -20, 0, 0,
ax_anim 2, 0, 164, 0, -17, 0, 0,
ax_anim 1, 0, 164, 0, -12, 0, 0,
ax_anim 2, 2, 164, 0, 0, 0, 0,
ax_anim_terminator
sNumelAnims_11_2:
ax_anim 2, 0, 165, 0, 0, 0, 0,
ax_anim 1, 0, 166, 0, -10, 0, 0,
ax_anim 2, 0, 166, 0, -16, 0, 0,
ax_anim 3, 0, 166, 0, -20, 0, 0,
ax_anim 4, 0, 166, 0, -21, 0, 0,
ax_anim 4, 0, 165, 0, -22, 0, 0,
ax_anim 3, 0, 167, 0, -21, 0, 0,
ax_anim 2, 0, 167, 0, -18, 0, 0,
ax_anim 1, 0, 167, 0, -12, 0, 0,
ax_anim 2, 2, 167, 0, 0, 0, 0,
ax_anim_terminator
sNumelAnims_11_3:
ax_anim 2, 0, 168, 0, 0, 0, 0,
ax_anim 1, 0, 169, 0, -10, 0, 0,
ax_anim 2, 0, 169, 0, -16, 0, 0,
ax_anim 3, 0, 169, 0, -20, 0, 0,
ax_anim 4, 0, 169, 0, -21, 0, 0,
ax_anim 4, 0, 168, 0, -22, 0, 0,
ax_anim 3, 0, 170, 0, -21, 0, 0,
ax_anim 2, 0, 170, 0, -18, 0, 0,
ax_anim 1, 0, 170, 0, -12, 0, 0,
ax_anim 2, 2, 170, 0, 0, 0, 0,
ax_anim_terminator
sNumelAnims_11_4:
ax_anim 2, 0, 171, 0, 0, 0, 0,
ax_anim 1, 0, 172, 0, -10, 0, 0,
ax_anim 2, 0, 172, 0, -16, 0, 0,
ax_anim 3, 0, 172, 0, -19, 0, 0,
ax_anim 4, 0, 172, 0, -20, 0, 0,
ax_anim 4, 0, 171, 0, -21, 0, 0,
ax_anim 3, 0, 173, 0, -19, 0, 0,
ax_anim 2, 0, 173, 0, -17, 0, 0,
ax_anim 1, 0, 173, 0, -12, 0, 0,
ax_anim 2, 2, 173, 0, 0, 0, 0,
ax_anim_terminator
sNumelAnims_11_5:
ax_anim 2, 0, 174, 0, 0, 0, 0,
ax_anim 1, 0, 175, 0, -10, 0, 0,
ax_anim 2, 0, 175, 0, -16, 0, 0,
ax_anim 3, 0, 175, 0, -19, 0, 0,
ax_anim 4, 0, 175, 0, -20, 0, 0,
ax_anim 4, 0, 176, 0, -22, 0, 0,
ax_anim 3, 0, 176, 0, -20, 0, 0,
ax_anim 2, 0, 176, 0, -18, 0, 0,
ax_anim 1, 0, 176, 0, -12, 0, 0,
ax_anim 2, 2, 176, 0, 0, 0, 0,
ax_anim_terminator
sNumelAnims_11_6:
ax_anim 2, 0, 177, 0, 0, 0, 0,
ax_anim 1, 0, 178, 0, -10, 0, 0,
ax_anim 2, 0, 178, 0, -16, 0, 0,
ax_anim 3, 0, 178, 0, -19, 0, 0,
ax_anim 4, 0, 178, 0, -20, 0, 0,
ax_anim 4, 0, 177, 0, -21, 0, 0,
ax_anim 3, 0, 179, 0, -19, 0, 0,
ax_anim 2, 0, 179, 0, -17, 0, 0,
ax_anim 1, 0, 179, 0, -12, 0, 0,
ax_anim 2, 2, 179, 0, 0, 0, 0,
ax_anim_terminator
sNumelAnims_11_7:
ax_anim 2, 0, 180, 0, 0, 0, 0,
ax_anim 1, 0, 181, 0, -10, 0, 0,
ax_anim 2, 0, 181, 0, -16, 0, 0,
ax_anim 3, 0, 181, 0, -20, 0, 0,
ax_anim 4, 0, 181, 0, -21, 0, 0,
ax_anim 4, 0, 180, 0, -22, 0, 0,
ax_anim 3, 0, 182, 0, -21, 0, 0,
ax_anim 2, 0, 182, 0, -18, 0, 0,
ax_anim 1, 0, 182, 0, -12, 0, 0,
ax_anim 2, 2, 182, 0, 0, 0, 0,
ax_anim_terminator
sNumelAnims_11_8:
ax_anim 2, 0, 183, 0, 0, 0, 0,
ax_anim 1, 0, 184, 0, -10, 0, 0,
ax_anim 2, 0, 184, 0, -16, 0, 0,
ax_anim 3, 0, 184, 0, -20, 0, 0,
ax_anim 4, 0, 184, 0, -21, 0, 0,
ax_anim 4, 0, 183, 0, -22, 0, 0,
ax_anim 3, 0, 185, 0, -21, 0, 0,
ax_anim 2, 0, 185, 0, -18, 0, 0,
ax_anim 1, 0, 185, 0, -12, 0, 0,
ax_anim 2, 2, 185, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sNumelAnims_12_1:
ax_anim 2, 0, 186, 1, 0, 1, 0,
ax_anim 2, 0, 186, 0, 0, 0, 0,
ax_anim 2, 0, 186, 1, 0, 1, 0,
ax_anim 2, 0, 186, 0, 0, 0, 0,
ax_anim 2, 0, 186, 1, 0, 1, 0,
ax_anim 2, 2, 186, 0, 0, 0, 0,
ax_anim 2, 0, 186, 1, 0, 1, 0,
ax_anim 2, 0, 186, 0, 0, 0, 0,
ax_anim 2, 0, 186, 1, 0, 1, 0,
ax_anim 2, 1, 186, 0, 0, 0, 0,
ax_anim_terminator
sNumelAnims_12_2:
ax_anim 2, 0, 193, 1, -1, 1, -1,
ax_anim 2, 0, 193, 0, 0, 0, 0,
ax_anim 2, 0, 193, 1, -1, 1, -1,
ax_anim 2, 0, 193, 0, 0, 0, 0,
ax_anim 2, 0, 193, 1, -1, 1, -1,
ax_anim 2, 2, 193, 0, 0, 0, 0,
ax_anim 2, 0, 193, 1, -1, 1, -1,
ax_anim 2, 0, 193, 0, 0, 0, 0,
ax_anim 2, 0, 193, 1, -1, 1, -1,
ax_anim 2, 1, 193, 0, 0, 0, 0,
ax_anim_terminator
sNumelAnims_12_3:
ax_anim 2, 0, 192, 0, -1, 0, -1,
ax_anim 2, 0, 192, 0, 0, 0, 0,
ax_anim 2, 0, 192, 0, -1, 0, -1,
ax_anim 2, 0, 192, 0, 0, 0, 0,
ax_anim 2, 0, 192, 0, -1, 0, -1,
ax_anim 2, 2, 192, 0, 0, 0, 0,
ax_anim 2, 0, 192, 0, -1, 0, -1,
ax_anim 2, 0, 192, 0, 0, 0, 0,
ax_anim 2, 0, 192, 0, -1, 0, -1,
ax_anim 2, 1, 192, 0, 0, 0, 0,
ax_anim_terminator
sNumelAnims_12_4:
ax_anim 2, 0, 191, -1, -1, -1, -1,
ax_anim 2, 0, 191, 0, 0, 0, 0,
ax_anim 2, 0, 191, -1, -1, -1, -1,
ax_anim 2, 0, 191, 0, 0, 0, 0,
ax_anim 2, 0, 191, -1, -1, -1, -1,
ax_anim 2, 2, 191, 0, 0, 0, 0,
ax_anim 2, 0, 191, -1, -1, -1, -1,
ax_anim 2, 0, 191, 0, 0, 0, 0,
ax_anim 2, 0, 191, -1, -1, -1, -1,
ax_anim 2, 1, 191, 0, 0, 0, 0,
ax_anim_terminator
sNumelAnims_12_5:
ax_anim 2, 0, 190, 1, 0, 1, 0,
ax_anim 2, 0, 190, 0, 0, 0, 0,
ax_anim 2, 0, 190, 1, 0, 1, 0,
ax_anim 2, 0, 190, 0, 0, 0, 0,
ax_anim 2, 0, 190, 1, 0, 1, 0,
ax_anim 2, 2, 190, 0, 0, 0, 0,
ax_anim 2, 0, 190, 1, 0, 1, 0,
ax_anim 2, 0, 190, 0, 0, 0, 0,
ax_anim 2, 0, 190, 1, 0, 1, 0,
ax_anim 2, 1, 190, 0, 0, 0, 0,
ax_anim_terminator
sNumelAnims_12_6:
ax_anim 2, 0, 189, 1, -1, 1, -1,
ax_anim 2, 0, 189, 0, 0, 0, 0,
ax_anim 2, 0, 189, 1, -1, 1, -1,
ax_anim 2, 0, 189, 0, 0, 0, 0,
ax_anim 2, 0, 189, 1, -1, 1, -1,
ax_anim 2, 2, 189, 0, 0, 0, 0,
ax_anim 2, 0, 189, 1, -1, 1, -1,
ax_anim 2, 0, 189, 0, 0, 0, 0,
ax_anim 2, 0, 189, 1, -1, 1, -1,
ax_anim 2, 1, 189, 0, 0, 0, 0,
ax_anim_terminator
sNumelAnims_12_7:
ax_anim 2, 0, 188, 0, -1, 0, -1,
ax_anim 2, 0, 188, 0, 0, 0, 0,
ax_anim 2, 0, 188, 0, -1, 0, -1,
ax_anim 2, 0, 188, 0, 0, 0, 0,
ax_anim 2, 0, 188, 0, -1, 0, -1,
ax_anim 2, 2, 188, 0, 0, 0, 0,
ax_anim 2, 0, 188, 0, -1, 0, -1,
ax_anim 2, 0, 188, 0, 0, 0, 0,
ax_anim 2, 0, 188, 0, -1, 0, -1,
ax_anim 2, 1, 188, 0, 0, 0, 0,
ax_anim_terminator
sNumelAnims_12_8:
ax_anim 2, 0, 187, -1, -1, -1, -1,
ax_anim 2, 0, 187, 0, 0, 0, 0,
ax_anim 2, 0, 187, -1, -1, -1, -1,
ax_anim 2, 0, 187, 0, 0, 0, 0,
ax_anim 2, 0, 187, -1, -1, -1, -1,
ax_anim 2, 2, 187, 0, 0, 0, 0,
ax_anim 2, 0, 187, -1, -1, -1, -1,
ax_anim 2, 0, 187, 0, 0, 0, 0,
ax_anim 2, 0, 187, -1, -1, -1, -1,
ax_anim 2, 1, 187, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sNumelAnims_13_1:
ax_anim 2, 0, 194, 0, 0, 0, 0,
ax_anim 2, 0, 195, 0, 0, 0, 0,
ax_anim 2, 0, 196, 0, 0, 0, 0,
ax_anim 2, 0, 197, 0, 0, 0, 0,
ax_anim 2, 0, 198, 0, 0, 0, 0,
ax_anim 2, 0, 199, 0, 0, 0, 0,
ax_anim 2, 0, 200, 0, 0, 0, 0,
ax_anim 2, 0, 201, 0, 0, 0, 0,
ax_anim 2, 2, 194, 0, 0, 0, 0,
ax_anim_terminator
sNumelAnims_13_2:
ax_anim 2, 0, 201, 0, 0, 0, 0,
ax_anim 2, 0, 194, 0, 0, 0, 0,
ax_anim 2, 0, 195, 0, 0, 0, 0,
ax_anim 2, 0, 196, 0, 0, 0, 0,
ax_anim 2, 0, 197, 0, 0, 0, 0,
ax_anim 2, 0, 198, 0, 0, 0, 0,
ax_anim 2, 0, 199, 0, 0, 0, 0,
ax_anim 2, 0, 200, 0, 0, 0, 0,
ax_anim 2, 2, 201, 0, 0, 0, 0,
ax_anim_terminator
sNumelAnims_13_3:
ax_anim 2, 0, 200, 0, 0, 0, 0,
ax_anim 2, 0, 201, 0, 0, 0, 0,
ax_anim 2, 0, 194, 0, 0, 0, 0,
ax_anim 2, 0, 195, 0, 0, 0, 0,
ax_anim 2, 0, 196, 0, 0, 0, 0,
ax_anim 2, 0, 197, 0, 0, 0, 0,
ax_anim 2, 0, 198, 0, 0, 0, 0,
ax_anim 2, 0, 199, 0, 0, 0, 0,
ax_anim 2, 2, 200, 0, 0, 0, 0,
ax_anim_terminator
sNumelAnims_13_4:
ax_anim 2, 0, 199, 0, 0, 0, 0,
ax_anim 2, 0, 200, 0, 0, 0, 0,
ax_anim 2, 0, 201, 0, 0, 0, 0,
ax_anim 2, 0, 194, 0, 0, 0, 0,
ax_anim 2, 0, 195, 0, 0, 0, 0,
ax_anim 2, 0, 196, 0, 0, 0, 0,
ax_anim 2, 0, 197, 0, 0, 0, 0,
ax_anim 2, 0, 198, 0, 0, 0, 0,
ax_anim 2, 2, 199, 0, 0, 0, 0,
ax_anim_terminator
sNumelAnims_13_5:
ax_anim 2, 0, 198, 0, 0, 0, 0,
ax_anim 2, 0, 199, 0, 0, 0, 0,
ax_anim 2, 0, 200, 0, 0, 0, 0,
ax_anim 2, 0, 201, 0, 0, 0, 0,
ax_anim 2, 0, 194, 0, 0, 0, 0,
ax_anim 2, 0, 195, 0, 0, 0, 0,
ax_anim 2, 0, 196, 0, 0, 0, 0,
ax_anim 2, 0, 197, 0, 0, 0, 0,
ax_anim 2, 2, 198, 0, 0, 0, 0,
ax_anim_terminator
sNumelAnims_13_6:
ax_anim 2, 0, 197, 0, 0, 0, 0,
ax_anim 2, 0, 198, 0, 0, 0, 0,
ax_anim 2, 0, 199, 0, 0, 0, 0,
ax_anim 2, 0, 200, 0, 0, 0, 0,
ax_anim 2, 0, 201, 0, 0, 0, 0,
ax_anim 2, 0, 194, 0, 0, 0, 0,
ax_anim 2, 0, 195, 0, 0, 0, 0,
ax_anim 2, 0, 196, 0, 0, 0, 0,
ax_anim 2, 2, 197, 0, 0, 0, 0,
ax_anim_terminator
sNumelAnims_13_7:
ax_anim 2, 0, 196, 0, 0, 0, 0,
ax_anim 2, 0, 197, 0, 0, 0, 0,
ax_anim 2, 0, 198, 0, 0, 0, 0,
ax_anim 2, 0, 199, 0, 0, 0, 0,
ax_anim 2, 0, 200, 0, 0, 0, 0,
ax_anim 2, 0, 201, 0, 0, 0, 0,
ax_anim 2, 0, 194, 0, 0, 0, 0,
ax_anim 2, 0, 195, 0, 0, 0, 0,
ax_anim 2, 2, 196, 0, 0, 0, 0,
ax_anim_terminator
sNumelAnims_13_8:
ax_anim 2, 0, 195, 0, 0, 0, 0,
ax_anim 2, 0, 196, 0, 0, 0, 0,
ax_anim 2, 0, 197, 0, 0, 0, 0,
ax_anim 2, 0, 198, 0, 0, 0, 0,
ax_anim 2, 0, 199, 0, 0, 0, 0,
ax_anim 2, 0, 200, 0, 0, 0, 0,
ax_anim 2, 0, 201, 0, 0, 0, 0,
ax_anim 2, 0, 194, 0, 0, 0, 0,
ax_anim 2, 2, 195, 0, 0, 0, 0,
ax_anim_terminator
sNumelGfx1:
.incbin "baserom.gba", 0x1325918, 0x100
sNumelSprites1:
ax_sprite sNumelGfx1, 0x100
ax_sprite_terminator
sNumelGfx2:
.incbin "baserom.gba", 0x1325A28, 0x100
sNumelSprites2:
ax_sprite sNumelGfx2, 0x100
ax_sprite_terminator
sNumelGfx3:
.incbin "baserom.gba", 0x1325B38, 0x100
sNumelSprites3:
ax_sprite sNumelGfx3, 0x100
ax_sprite_terminator
sNumelGfx4:
.incbin "baserom.gba", 0x1325C48, 0x200
sNumelSprites4:
ax_sprite sNumelGfx4, 0x200
ax_sprite_terminator
sNumelGfx5:
.incbin "baserom.gba", 0x1325E58, 0x200
sNumelSprites5:
ax_sprite sNumelGfx5, 0x200
ax_sprite_terminator
sNumelGfx6:
.incbin "baserom.gba", 0x1326068, 0x200
sNumelSprites6:
ax_sprite sNumelGfx6, 0x200
ax_sprite_terminator
sNumelGfx7:
.incbin "baserom.gba", 0x1326278, 0x200
sNumelSprites7:
ax_sprite sNumelGfx7, 0x200
ax_sprite_terminator
sNumelGfx8:
.incbin "baserom.gba", 0x1326488, 0x200
sNumelSprites8:
ax_sprite sNumelGfx8, 0x200
ax_sprite_terminator
sNumelGfx9:
.incbin "baserom.gba", 0x1326698, 0x200
sNumelSprites9:
ax_sprite sNumelGfx9, 0x200
ax_sprite_terminator
sNumelGfx10:
.incbin "baserom.gba", 0x13268A8, 0x200
sNumelSprites10:
ax_sprite sNumelGfx10, 0x200
ax_sprite_terminator
sNumelGfx11:
.incbin "baserom.gba", 0x1326AB8, 0x200
sNumelSprites11:
ax_sprite sNumelGfx11, 0x200
ax_sprite_terminator
sNumelGfx12:
.incbin "baserom.gba", 0x1326CC8, 0x200
sNumelSprites12:
ax_sprite sNumelGfx12, 0x200
ax_sprite_terminator
sNumelGfx13:
.incbin "baserom.gba", 0x1326ED8, 0x100
sNumelSprites13:
ax_sprite sNumelGfx13, 0x100
ax_sprite_terminator
sNumelGfx14:
.incbin "baserom.gba", 0x1326FE8, 0x100
sNumelSprites14:
ax_sprite sNumelGfx14, 0x100
ax_sprite_terminator
sNumelGfx15:
.incbin "baserom.gba", 0x13270F8, 0x100
sNumelSprites15:
ax_sprite sNumelGfx15, 0x100
ax_sprite_terminator
sNumelGfx16:
.incbin "baserom.gba", 0x1327208, 0xC0
sNumelSprites16:
ax_sprite sNumelGfx16, 0xc0
ax_sprite 0, 0x40
ax_sprite_terminator
sNumelGfx17:
.incbin "baserom.gba", 0x13272E0, 0xC0
sNumelSprites17:
ax_sprite sNumelGfx17, 0xc0
ax_sprite 0, 0x40
ax_sprite_terminator
sNumelGfx18:
.incbin "baserom.gba", 0x13273B8, 0x40
sNumelGfx18_1:
.incbin "baserom.gba", 0x13273F8, 0x100
sNumelGfx18_2:
.incbin "baserom.gba", 0x13274F8, 0x20
sNumelSprites18:
ax_sprite sNumelGfx18, 0x40
ax_sprite 0, 0x40
ax_sprite sNumelGfx18_1, 0x100
ax_sprite 0, 0x40
ax_sprite sNumelGfx18_2, 0x20
ax_sprite 0, 0x20
ax_sprite_terminator
sNumelGfx19:
.incbin "baserom.gba", 0x1327550, 0x60
sNumelGfx19_1:
.incbin "baserom.gba", 0x13275B0, 0x80
sNumelGfx19_2:
.incbin "baserom.gba", 0x1327630, 0x40
sNumelSprites19:
ax_sprite 0, 0x80
ax_sprite sNumelGfx19, 0x60
ax_sprite 0, 0x20
ax_sprite sNumelGfx19_1, 0x80
ax_sprite 0, 0x20
ax_sprite sNumelGfx19_2, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sNumelGfx20:
.incbin "baserom.gba", 0x13276B0, 0x40
sNumelGfx20_1:
.incbin "baserom.gba", 0x13276F0, 0x100
sNumelGfx20_2:
.incbin "baserom.gba", 0x13277F0, 0x60
sNumelSprites20:
ax_sprite sNumelGfx20, 0x40
ax_sprite 0, 0x40
ax_sprite sNumelGfx20_1, 0x100
ax_sprite 0, 0x20
ax_sprite sNumelGfx20_2, 0x60
ax_sprite_terminator
sNumelGfx21:
.incbin "baserom.gba", 0x1327880, 0x100
sNumelGfx21_1:
.incbin "baserom.gba", 0x1327980, 0x60
sNumelSprites21:
ax_sprite 0, 0x80
ax_sprite sNumelGfx21, 0x100
ax_sprite 0, 0x20
ax_sprite sNumelGfx21_1, 0x60
ax_sprite_terminator
sNumelGfx22:
.incbin "baserom.gba", 0x1327A08, 0x40
sNumelGfx22_1:
.incbin "baserom.gba", 0x1327A48, 0x60
sNumelGfx22_2:
.incbin "baserom.gba", 0x1327AA8, 0x80
sNumelGfx22_3:
.incbin "baserom.gba", 0x1327B28, 0x40
sNumelSprites22:
ax_sprite sNumelGfx22, 0x40
ax_sprite 0, 0x40
ax_sprite sNumelGfx22_1, 0x60
ax_sprite 0, 0x20
ax_sprite sNumelGfx22_2, 0x80
ax_sprite 0, 0x20
ax_sprite sNumelGfx22_3, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sNumelGfx23:
.incbin "baserom.gba", 0x1327BB0, 0x40
sNumelGfx23_1:
.incbin "baserom.gba", 0x1327BF0, 0x60
sNumelGfx23_2:
.incbin "baserom.gba", 0x1327C50, 0x60
sNumelGfx23_3:
.incbin "baserom.gba", 0x1327CB0, 0x40
sNumelSprites23:
ax_sprite sNumelGfx23, 0x40
ax_sprite 0, 0x40
ax_sprite sNumelGfx23_1, 0x60
ax_sprite 0, 0x40
ax_sprite sNumelGfx23_2, 0x60
ax_sprite 0, 0x20
ax_sprite sNumelGfx23_3, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sNumelGfx24:
.incbin "baserom.gba", 0x1327D38, 0x100
sNumelSprites24:
ax_sprite sNumelGfx24, 0x100
ax_sprite_terminator
sNumelGfx25:
.incbin "baserom.gba", 0x1327E48, 0x100
sNumelSprites25:
ax_sprite sNumelGfx25, 0x100
ax_sprite_terminator
sNumelGfx26:
.incbin "baserom.gba", 0x1327F58, 0xC0
sNumelSprites26:
ax_sprite sNumelGfx26, 0xc0
ax_sprite 0, 0x40
ax_sprite_terminator
sNumelGfx27:
.incbin "baserom.gba", 0x1328030, 0x60
sNumelGfx27_1:
.incbin "baserom.gba", 0x1328090, 0x80
sNumelGfx27_2:
.incbin "baserom.gba", 0x1328110, 0x60
sNumelSprites27:
ax_sprite sNumelGfx27, 0x60
ax_sprite 0, 0x20
ax_sprite sNumelGfx27_1, 0x80
ax_sprite 0, 0x20
ax_sprite sNumelGfx27_2, 0x60
ax_sprite 0, 0x80
ax_sprite_terminator
sNumelGfx28:
.incbin "baserom.gba", 0x13281A8, 0x40
sNumelGfx28_1:
.incbin "baserom.gba", 0x13281E8, 0x60
sNumelGfx28_2:
.incbin "baserom.gba", 0x1328248, 0x60
sNumelGfx28_3:
.incbin "baserom.gba", 0x13282A8, 0x20
sNumelSprites28:
ax_sprite sNumelGfx28, 0x40
ax_sprite 0, 0x40
ax_sprite sNumelGfx28_1, 0x60
ax_sprite 0, 0x20
ax_sprite sNumelGfx28_2, 0x60
ax_sprite 0, 0x40
ax_sprite sNumelGfx28_3, 0x20
ax_sprite 0, 0x40
ax_sprite_terminator
sNumelGfx29:
.incbin "baserom.gba", 0x1328310, 0x40
sNumelGfx29_1:
.incbin "baserom.gba", 0x1328350, 0x60
sNumelGfx29_2:
.incbin "baserom.gba", 0x13283B0, 0x60
sNumelGfx29_3:
.incbin "baserom.gba", 0x1328410, 0x60
sNumelSprites29:
ax_sprite sNumelGfx29, 0x40
ax_sprite 0, 0x40
ax_sprite sNumelGfx29_1, 0x60
ax_sprite 0, 0x20
ax_sprite sNumelGfx29_2, 0x60
ax_sprite 0, 0x20
ax_sprite sNumelGfx29_3, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sNumelGfx30:
.incbin "baserom.gba", 0x13284B8, 0x100
sNumelSprites30:
ax_sprite sNumelGfx30, 0x100
ax_sprite_terminator
sNumelGfx31:
.incbin "baserom.gba", 0x13285C8, 0xC0
sNumelSprites31:
ax_sprite sNumelGfx31, 0xc0
ax_sprite 0, 0x40
ax_sprite_terminator
sNumelGfx32:
.incbin "baserom.gba", 0x13286A0, 0x60
sNumelGfx32_1:
.incbin "baserom.gba", 0x1328700, 0x80
sNumelGfx32_2:
.incbin "baserom.gba", 0x1328780, 0x60
sNumelSprites32:
ax_sprite sNumelGfx32, 0x60
ax_sprite 0, 0x20
ax_sprite sNumelGfx32_1, 0x80
ax_sprite 0, 0x20
ax_sprite sNumelGfx32_2, 0x60
ax_sprite 0, 0x80
ax_sprite_terminator
sNumelGfx33:
.incbin "baserom.gba", 0x1328818, 0x40
sNumelGfx33_1:
.incbin "baserom.gba", 0x1328858, 0x60
sNumelGfx33_2:
.incbin "baserom.gba", 0x13288B8, 0x60
sNumelGfx33_3:
.incbin "baserom.gba", 0x1328918, 0x20
sNumelSprites33:
ax_sprite sNumelGfx33, 0x40
ax_sprite 0, 0x40
ax_sprite sNumelGfx33_1, 0x60
ax_sprite 0, 0x20
ax_sprite sNumelGfx33_2, 0x60
ax_sprite 0, 0x40
ax_sprite sNumelGfx33_3, 0x20
ax_sprite 0, 0x40
ax_sprite_terminator
sNumelGfx34:
.incbin "baserom.gba", 0x1328980, 0x40
sNumelGfx34_1:
.incbin "baserom.gba", 0x13289C0, 0x60
sNumelGfx34_2:
.incbin "baserom.gba", 0x1328A20, 0x60
sNumelGfx34_3:
.incbin "baserom.gba", 0x1328A80, 0x60
sNumelSprites34:
ax_sprite sNumelGfx34, 0x40
ax_sprite 0, 0x40
ax_sprite sNumelGfx34_1, 0x60
ax_sprite 0, 0x20
ax_sprite sNumelGfx34_2, 0x60
ax_sprite 0, 0x20
ax_sprite sNumelGfx34_3, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sNumelGfx35:
.incbin "baserom.gba", 0x1328B28, 0x100
sNumelSprites35:
ax_sprite sNumelGfx35, 0x100
ax_sprite_terminator
sNumelGfx36:
.incbin "baserom.gba", 0x1328C38, 0x200
sNumelSprites36:
ax_sprite sNumelGfx36, 0x200
ax_sprite_terminator
sNumelGfx37:
.incbin "baserom.gba", 0x1328E48, 0x200
sNumelSprites37:
ax_sprite sNumelGfx37, 0x200
ax_sprite_terminator
sNumelGfx38:
.incbin "baserom.gba", 0x1329058, 0x200
sNumelSprites38:
ax_sprite sNumelGfx38, 0x200
ax_sprite_terminator
sNumelGfx39:
.incbin "baserom.gba", 0x1329268, 0x200
sNumelSprites39:
ax_sprite sNumelGfx39, 0x200
ax_sprite_terminator
sNumelGfx40:
.incbin "baserom.gba", 0x1329478, 0x200
sNumelSprites40:
ax_sprite sNumelGfx40, 0x200
ax_sprite_terminator
sNumelGfx41:
.incbin "baserom.gba", 0x1329688, 0x200
sNumelSprites41:
ax_sprite sNumelGfx41, 0x200
ax_sprite_terminator
sNumelGfx42:
.incbin "baserom.gba", 0x1329898, 0x200
sNumelSprites42:
ax_sprite sNumelGfx42, 0x200
ax_sprite_terminator
sAxPosesNumel:
.4byte sNumelPose1
.4byte sNumelPose2
.4byte sNumelPose3
.4byte sNumelPose4
.4byte sNumelPose5
.4byte sNumelPose6
.4byte sNumelPose7
.4byte sNumelPose8
.4byte sNumelPose9
.4byte sNumelPose10
.4byte sNumelPose11
.4byte sNumelPose12
.4byte sNumelPose13
.4byte sNumelPose14
.4byte sNumelPose15
.4byte sNumelPose16
.4byte sNumelPose17
.4byte sNumelPose18
.4byte sNumelPose19
.4byte sNumelPose20
.4byte sNumelPose21
.4byte sNumelPose22
.4byte sNumelPose23
.4byte sNumelPose24
.4byte sNumelPose25
.4byte sNumelPose26
.4byte sNumelPose27
.4byte sNumelPose28
.4byte sNumelPose29
.4byte sNumelPose30
.4byte sNumelPose31
.4byte sNumelPose32
.4byte sNumelPose33
.4byte sNumelPose34
.4byte sNumelPose35
.4byte sNumelPose36
.4byte sNumelPose37
.4byte sNumelPose38
.4byte sNumelPose39
.4byte sNumelPose40
.4byte sNumelPose41
.4byte sNumelPose42
.4byte sNumelPose43
.4byte sNumelPose44
.4byte sNumelPose45
.4byte sNumelPose46
.4byte sNumelPose47
.4byte sNumelPose48
.4byte sNumelPose49
.4byte sNumelPose50
.4byte sNumelPose51
.4byte sNumelPose52
.4byte sNumelPose53
.4byte sNumelPose54
.4byte sNumelPose55
.4byte sNumelPose56
.4byte sNumelPose57
.4byte sNumelPose58
.4byte sNumelPose59
.4byte sNumelPose60
.4byte sNumelPose61
.4byte sNumelPose62
.4byte sNumelPose63
.4byte sNumelPose64
.4byte sNumelPose65
.4byte sNumelPose66
.4byte sNumelPose67
.4byte sNumelPose68
.4byte sNumelPose69
.4byte sNumelPose70
.4byte sNumelPose71
.4byte sNumelPose72
.4byte sNumelPose73
.4byte sNumelPose74
.4byte sNumelPose75
.4byte sNumelPose76
.4byte sNumelPose77
.4byte sNumelPose78
.4byte sNumelPose79
.4byte sNumelPose80
.4byte sNumelPose81
.4byte sNumelPose82
.4byte sNumelPose83
.4byte sNumelPose84
.4byte sNumelPose85
.4byte sNumelPose86
.4byte sNumelPose87
.4byte sNumelPose88
.4byte sNumelPose89
.4byte sNumelPose90
.4byte sNumelPose91
.4byte sNumelPose92
.4byte sNumelPose93
.4byte sNumelPose94
.4byte sNumelPose95
.4byte sNumelPose96
.4byte sNumelPose97
.4byte sNumelPose98
.4byte sNumelPose99
.4byte sNumelPose100
.4byte sNumelPose101
.4byte sNumelPose102
.4byte sNumelPose103
.4byte sNumelPose104
.4byte sNumelPose105
.4byte sNumelPose106
.4byte sNumelPose107
.4byte sNumelPose108
.4byte sNumelPose109
.4byte sNumelPose110
.4byte sNumelPose111
.4byte sNumelPose112
.4byte sNumelPose113
.4byte sNumelPose114
.4byte sNumelPose115
.4byte sNumelPose116
.4byte sNumelPose117
.4byte sNumelPose118
.4byte sNumelPose119
.4byte sNumelPose120
.4byte sNumelPose121
.4byte sNumelPose122
.4byte sNumelPose123
.4byte sNumelPose124
.4byte sNumelPose125
.4byte sNumelPose126
.4byte sNumelPose127
.4byte sNumelPose128
.4byte sNumelPose129
.4byte sNumelPose130
.4byte sNumelPose131
.4byte sNumelPose132
.4byte sNumelPose133
.4byte sNumelPose134
.4byte sNumelPose135
.4byte sNumelPose136
.4byte sNumelPose137
.4byte sNumelPose138
.4byte sNumelPose139
.4byte sNumelPose140
.4byte sNumelPose141
.4byte sNumelPose142
.4byte sNumelPose143
.4byte sNumelPose144
.4byte sNumelPose145
.4byte sNumelPose146
.4byte sNumelPose147
.4byte sNumelPose148
.4byte sNumelPose149
.4byte sNumelPose150
.4byte sNumelPose151
.4byte sNumelPose152
.4byte sNumelPose153
.4byte sNumelPose154
.4byte sNumelPose155
.4byte sNumelPose156
.4byte sNumelPose157
.4byte sNumelPose158
.4byte sNumelPose159
.4byte sNumelPose160
.4byte sNumelPose161
.4byte sNumelPose162
.4byte sNumelPose163
.4byte sNumelPose164
.4byte sNumelPose165
.4byte sNumelPose166
.4byte sNumelPose167
.4byte sNumelPose168
.4byte sNumelPose169
.4byte sNumelPose170
.4byte sNumelPose171
.4byte sNumelPose172
.4byte sNumelPose173
.4byte sNumelPose174
.4byte sNumelPose175
.4byte sNumelPose176
.4byte sNumelPose177
.4byte sNumelPose178
.4byte sNumelPose179
.4byte sNumelPose180
.4byte sNumelPose181
.4byte sNumelPose182
.4byte sNumelPose183
.4byte sNumelPose184
.4byte sNumelPose185
.4byte sNumelPose186
.4byte sNumelPose187
.4byte sNumelPose188
.4byte sNumelPose189
.4byte sNumelPose190
.4byte sNumelPose191
.4byte sNumelPose192
.4byte sNumelPose193
.4byte sNumelPose194
.4byte sNumelPose195
.4byte sNumelPose196
.4byte sNumelPose197
.4byte sNumelPose198
.4byte sNumelPose199
.4byte sNumelPose200
.4byte sNumelPose201
.4byte sNumelPose202
sAxPositionsNumel:
.2byte   -1,   -1, 	  -5,    2, 	   3,    2, 	  -1,   -5
.2byte    0,    0, 	  -5,    4, 	   4,    1, 	   0,   -5
.2byte   -2,    0, 	  -5,    1, 	   3,    4, 	  -1,   -5
.2byte   10,   -3, 	   4,    0, 	  -1,    2, 	   0,   -7
.2byte    9,   -2, 	   6,    1, 	  -3,    2, 	   0,   -6
.2byte   11,   -2, 	   1,   -3, 	   2,    3, 	  -1,   -6
.2byte   12,   -7, 	   4,   -2, 	   2,    0, 	  -2,   -7
.2byte   11,   -6, 	   6,   -1, 	   0,    1, 	  -2,   -6
.2byte   11,   -7, 	   0,   -2, 	   5,    1, 	  -2,   -6
.2byte    8,  -11, 	  -1,   -5, 	   5,   -2, 	  -2,   -7
.2byte    9,  -10, 	  -1,   -5, 	   3,   -1, 	  -2,   -7
.2byte    7,  -10, 	  -1,   -4, 	   6,   -3, 	  -2,   -7
.2byte   -1,  -13, 	   4,   -5, 	  -6,   -5, 	  -1,   -6
.2byte    0,  -12, 	   4,   -5, 	  -6,   -6, 	  -1,   -5
.2byte   -2,  -12, 	   3,   -5, 	  -5,   -4, 	  -1,   -5
.2byte  -10,  -11, 	  -1,   -5, 	  -7,   -2, 	   0,   -7
.2byte  -11,  -10, 	  -1,   -5, 	  -5,   -1, 	   0,   -7
.2byte   -9,  -10, 	  -1,   -4, 	  -8,   -3, 	   0,   -7
.2byte  -14,   -7, 	  -6,   -2, 	  -4,    0, 	   0,   -7
.2byte  -13,   -6, 	  -8,   -1, 	  -2,    1, 	   0,   -6
.2byte  -13,   -7, 	  -2,   -2, 	  -7,    1, 	   0,   -6
.2byte  -11,   -3, 	  -5,    0, 	   0,    2, 	  -1,   -7
.2byte  -10,   -2, 	  -7,    1, 	   2,    2, 	  -1,   -6
.2byte  -12,   -2, 	  -2,   -3, 	  -3,    3, 	   0,   -6
.2byte   -1,   -1, 	  -5,    2, 	   3,    2, 	  -1,   -5
.2byte   -1,   -6, 	  -5,   -1, 	   3,   -1, 	  -1,   -7
.2byte   -1,    3, 	  -6,    3, 	   4,    3, 	  -1,   -3
.2byte   10,   -3, 	   4,    0, 	  -1,    2, 	   0,   -7
.2byte   11,   -5, 	   5,   -3, 	   0,   -1, 	   0,   -7
.2byte   12,   -1, 	   5,    0, 	  -1,    3, 	   1,   -4
.2byte   12,   -7, 	   4,   -2, 	   2,    0, 	  -2,   -7
.2byte   12,   -9, 	   6,   -5, 	   2,   -3, 	  -1,   -7
.2byte   12,   -4, 	   4,   -2, 	   0,    1, 	  -2,   -5
.2byte    8,  -11, 	  -1,   -5, 	   5,   -2, 	  -2,   -7
.2byte    7,  -12, 	   0,   -9, 	   6,   -5, 	  -2,   -8
.2byte    9,  -10, 	   1,   -6, 	   4,   -1, 	  -2,   -6
.2byte   -1,  -13, 	   4,   -5, 	  -6,   -5, 	  -1,   -6
.2byte   -1,  -15, 	   3,   -9, 	  -5,   -9, 	  -1,   -9
.2byte   -1,  -15, 	   4,   -8, 	  -5,   -8, 	  -1,  -10
.2byte  -10,  -11, 	  -1,   -5, 	  -7,   -2, 	   0,   -7
.2byte   -9,  -12, 	  -2,   -9, 	  -8,   -5, 	   0,   -8
.2byte  -11,  -10, 	  -3,   -6, 	  -6,   -1, 	   0,   -6
.2byte  -14,   -7, 	  -6,   -2, 	  -4,    0, 	   0,   -7
.2byte  -14,   -9, 	  -8,   -5, 	  -4,   -3, 	  -1,   -7
.2byte  -14,   -4, 	  -6,   -2, 	  -2,    1, 	   0,   -5
.2byte  -11,   -3, 	  -5,    0, 	   0,    2, 	  -1,   -7
.2byte  -12,   -5, 	  -6,   -3, 	  -1,   -1, 	  -1,   -7
.2byte  -13,   -1, 	  -6,    0, 	   0,    3, 	  -2,   -4
.2byte   -1,   -1, 	  -5,    2, 	   3,    2, 	  -1,   -5
.2byte   -1,   -6, 	  -5,   -1, 	   3,   -1, 	  -1,   -7
.2byte   -1,    3, 	  -6,    3, 	   4,    3, 	  -1,   -3
.2byte   10,   -3, 	   4,    0, 	  -1,    2, 	   0,   -7
.2byte   11,   -5, 	   5,   -3, 	   0,   -1, 	   0,   -7
.2byte   12,   -1, 	   5,    0, 	  -1,    3, 	   1,   -4
.2byte   12,   -7, 	   4,   -2, 	   2,    0, 	  -2,   -7
.2byte   12,   -9, 	   6,   -5, 	   2,   -3, 	  -1,   -7
.2byte   12,   -4, 	   4,   -2, 	   0,    1, 	  -2,   -5
.2byte    8,  -11, 	  -1,   -5, 	   5,   -2, 	  -2,   -7
.2byte    7,  -12, 	   0,   -9, 	   6,   -5, 	  -2,   -8
.2byte    9,  -10, 	   1,   -6, 	   4,   -1, 	  -2,   -6
.2byte   -1,  -13, 	   4,   -5, 	  -6,   -5, 	  -1,   -6
.2byte   -1,  -15, 	   3,   -9, 	  -5,   -9, 	  -1,   -9
.2byte   -1,  -15, 	   4,   -8, 	  -5,   -8, 	  -1,  -10
.2byte  -10,  -11, 	  -1,   -5, 	  -7,   -2, 	   0,   -7
.2byte   -9,  -12, 	  -2,   -9, 	  -8,   -5, 	   0,   -8
.2byte  -11,  -10, 	  -3,   -6, 	  -6,   -1, 	   0,   -6
.2byte  -14,   -7, 	  -6,   -2, 	  -4,    0, 	   0,   -7
.2byte  -14,   -9, 	  -8,   -5, 	  -4,   -3, 	  -1,   -7
.2byte  -14,   -4, 	  -6,   -2, 	  -2,    1, 	   0,   -5
.2byte  -11,   -3, 	  -5,    0, 	   0,    2, 	  -1,   -7
.2byte  -12,   -5, 	  -6,   -3, 	  -1,   -1, 	  -1,   -7
.2byte  -13,   -1, 	  -6,    0, 	   0,    3, 	  -2,   -4
.2byte   -1,   -1, 	  -5,    2, 	   3,    2, 	  -1,   -5
.2byte   -1,   -6, 	  -6,   -5, 	   3,   -2, 	  -1,   -7
.2byte   -1,    3, 	  -6,    3, 	   4,    3, 	  -1,   -3
.2byte   10,   -3, 	   4,    0, 	  -1,    2, 	   0,   -7
.2byte    8,   -8, 	   4,   -6, 	   1,   -3, 	  -2,   -8
.2byte   12,   -1, 	   5,    0, 	  -1,    3, 	   1,   -4
.2byte   12,   -7, 	   4,   -2, 	   2,    0, 	  -2,   -7
.2byte    7,  -13, 	   4,  -11, 	   5,   -7, 	  -4,   -8
.2byte   12,   -4, 	   4,   -2, 	   0,    1, 	  -2,   -5
.2byte    8,  -11, 	  -1,   -5, 	   5,   -2, 	  -2,   -7
.2byte    4,  -14, 	  -2,   -9, 	   5,   -7, 	  -4,   -6
.2byte    9,  -10, 	   1,   -6, 	   4,   -1, 	  -2,   -6
.2byte   -1,  -13, 	   4,   -5, 	  -6,   -5, 	  -1,   -6
.2byte   -1,  -16, 	   5,  -14, 	  -7,  -12, 	  -1,   -7
.2byte   -1,  -15, 	   4,   -8, 	  -5,   -8, 	  -1,  -10
.2byte  -10,  -11, 	  -1,   -5, 	  -7,   -2, 	   0,   -7
.2byte   -6,  -14, 	   0,   -9, 	  -7,   -7, 	   2,   -6
.2byte  -11,  -10, 	  -3,   -6, 	  -6,   -1, 	   0,   -6
.2byte  -14,   -7, 	  -6,   -2, 	  -4,    0, 	   0,   -7
.2byte   -9,  -13, 	  -6,  -11, 	  -7,   -7, 	   2,   -8
.2byte  -14,   -4, 	  -6,   -2, 	  -2,    1, 	   0,   -5
.2byte  -11,   -3, 	  -5,    0, 	   0,    2, 	  -1,   -7
.2byte   -9,   -8, 	  -5,   -6, 	  -2,   -3, 	   1,   -8
.2byte  -13,   -1, 	  -6,    0, 	   0,    3, 	  -2,   -4
.2byte   -1,   -1, 	  -5,    2, 	   3,    2, 	  -1,   -5
.2byte   -1,   -6, 	  -6,   -5, 	   3,   -2, 	  -1,   -7
.2byte   -1,   -6, 	  -5,   -2, 	   4,   -6, 	  -1,   -8
.2byte   10,   -3, 	   4,    0, 	  -1,    2, 	   0,   -7
.2byte    8,   -8, 	   4,   -6, 	   1,   -3, 	  -2,   -8
.2byte    8,   -8, 	   5,   -4, 	   3,   -7, 	  -1,   -7
.2byte   12,   -7, 	   4,   -2, 	   2,    0, 	  -2,   -7
.2byte    7,  -13, 	   4,  -11, 	   5,   -7, 	  -4,   -8
.2byte    8,  -14, 	   5,   -5, 	   5,  -11, 	  -4,   -8
.2byte    8,  -11, 	  -1,   -5, 	   5,   -2, 	  -2,   -7
.2byte    4,  -14, 	  -2,   -9, 	   5,   -7, 	  -4,   -6
.2byte    4,  -14, 	  -3,  -11, 	   5,  -10, 	  -3,   -6
.2byte   -1,  -13, 	   4,   -5, 	  -6,   -5, 	  -1,   -6
.2byte   -1,  -16, 	   5,  -14, 	  -7,  -12, 	  -1,   -7
.2byte   -1,  -16, 	   5,  -12, 	  -7,  -14, 	  -1,   -7
.2byte  -10,  -11, 	  -1,   -5, 	  -7,   -2, 	   0,   -7
.2byte   -6,  -14, 	   0,   -9, 	  -7,   -7, 	   2,   -6
.2byte   -6,  -14, 	   1,  -11, 	  -7,  -10, 	   1,   -6
.2byte  -14,   -7, 	  -6,   -2, 	  -4,    0, 	   0,   -7
.2byte   -9,  -13, 	  -6,  -11, 	  -7,   -7, 	   2,   -8
.2byte  -10,  -14, 	  -7,   -5, 	  -7,  -11, 	   2,   -8
.2byte  -11,   -3, 	  -5,    0, 	   0,    2, 	  -1,   -7
.2byte   -9,   -8, 	  -5,   -6, 	  -2,   -3, 	   1,   -8
.2byte   -9,   -8, 	  -6,   -4, 	  -4,   -7, 	   0,   -7
.2byte  -10,    0, 	  -5,    0, 	  -1,    2, 	   1,   -5
.2byte  -10,    0, 	  -5,    0, 	  -1,    2, 	   1,   -4
.2byte    0,  -12, 	  -7,   -9, 	   7,   -8, 	   0,   -8
.2byte    8,  -16, 	   7,  -11, 	   0,   -7, 	  -2,   -9
.2byte    8,  -19, 	   2,  -10, 	   4,   -7, 	  -4,   -8
.2byte    7,  -20, 	   0,  -10, 	   7,   -9, 	  -2,   -7
.2byte    0,  -17, 	   8,  -11, 	  -8,  -11, 	   0,   -7
.2byte   -8,  -20, 	  -1,  -10, 	  -8,   -9, 	   1,   -7
.2byte   -9,  -19, 	  -3,  -10, 	  -5,   -7, 	   3,   -8
.2byte   -9,  -16, 	  -8,  -11, 	  -1,   -7, 	   1,   -9
.2byte   -1,   -1, 	  -5,    2, 	   3,    2, 	  -1,   -5
.2byte   -1,    3, 	  -6,    3, 	   4,    3, 	  -1,   -3
.2byte   10,   -3, 	   4,    0, 	  -1,    2, 	   0,   -7
.2byte   12,   -1, 	   5,    0, 	  -1,    3, 	   1,   -4
.2byte   12,   -7, 	   4,   -2, 	   2,    0, 	  -2,   -7
.2byte   13,   -4, 	   5,   -2, 	   1,    1, 	  -1,   -5
.2byte    8,  -11, 	  -1,   -5, 	   5,   -2, 	  -2,   -7
.2byte   10,  -11, 	   2,   -7, 	   5,   -2, 	  -1,   -7
.2byte   -1,  -13, 	   4,   -5, 	  -6,   -5, 	  -1,   -6
.2byte   -1,  -15, 	   4,   -8, 	  -5,   -8, 	  -1,  -10
.2byte  -10,  -11, 	  -1,   -5, 	  -7,   -2, 	   0,   -7
.2byte  -12,  -11, 	  -4,   -7, 	  -7,   -2, 	  -1,   -7
.2byte  -14,   -7, 	  -6,   -2, 	  -4,    0, 	   0,   -7
.2byte  -15,   -4, 	  -7,   -2, 	  -3,    1, 	  -1,   -5
.2byte  -11,   -3, 	  -5,    0, 	   0,    2, 	  -1,   -7
.2byte  -13,   -1, 	  -6,    0, 	   0,    3, 	  -2,   -4
.2byte    0,    2, 	  -5,    2, 	   5,    2, 	   0,   -4
.2byte  -11,   -1, 	  -4,    0, 	   2,    3, 	   0,   -4
.2byte  -12,   -3, 	  -4,   -1, 	   0,    2, 	   2,   -4
.2byte   -8,   -9, 	   0,   -5, 	  -3,    0, 	   3,   -5
.2byte    0,  -13, 	   5,   -6, 	  -4,   -6, 	   0,   -8
.2byte    7,   -9, 	  -1,   -5, 	   2,    0, 	  -4,   -5
.2byte   11,   -3, 	   3,   -1, 	  -1,    2, 	  -3,   -4
.2byte   10,   -1, 	   3,    0, 	  -3,    3, 	  -1,   -4
.2byte    0,    2, 	  -5,    2, 	   5,    2, 	   0,   -4
.2byte   10,   -1, 	   3,    0, 	  -3,    3, 	  -1,   -4
.2byte   11,   -3, 	   3,   -1, 	  -1,    2, 	  -3,   -4
.2byte    8,   -9, 	   0,   -5, 	   3,    0, 	  -3,   -5
.2byte    0,  -13, 	   5,   -6, 	  -4,   -6, 	   0,   -8
.2byte   -9,   -9, 	  -1,   -5, 	  -4,    0, 	   2,   -5
.2byte  -12,   -3, 	  -4,   -1, 	   0,    2, 	   2,   -4
.2byte  -11,   -1, 	  -4,    0, 	   2,    3, 	   0,   -4
.2byte   -1,   -1, 	  -5,    2, 	   3,    2, 	  -1,   -5
.2byte   -1,   -3, 	  -6,   -2, 	   3,    1, 	  -1,   -4
.2byte   -1,    1, 	  -6,    1, 	   4,    1, 	  -1,   -5
.2byte   10,   -3, 	   4,    0, 	  -1,    2, 	   0,   -7
.2byte    9,   -5, 	   5,   -3, 	   2,    0, 	  -1,   -5
.2byte   11,   -1, 	   4,    0, 	  -2,    3, 	   0,   -4
.2byte   12,   -7, 	   4,   -2, 	   2,    0, 	  -2,   -7
.2byte    9,  -11, 	   6,   -9, 	   7,   -5, 	  -2,   -6
.2byte   12,   -4, 	   4,   -2, 	   0,    1, 	  -2,   -5
.2byte    8,  -11, 	  -1,   -5, 	   5,   -2, 	  -2,   -7
.2byte    6,  -13, 	   0,   -8, 	   7,   -6, 	  -2,   -5
.2byte    9,  -10, 	   1,   -6, 	   4,   -1, 	  -2,   -6
.2byte   -1,  -13, 	   4,   -5, 	  -6,   -5, 	  -1,   -6
.2byte   -1,  -14, 	   5,  -12, 	  -7,  -10, 	  -1,   -5
.2byte   -1,  -14, 	   4,   -7, 	  -5,   -7, 	  -1,   -9
.2byte   -9,  -11, 	   0,   -5, 	  -6,   -2, 	   1,   -7
.2byte   -7,  -13, 	  -1,   -8, 	  -8,   -6, 	   1,   -5
.2byte  -10,  -10, 	  -2,   -6, 	  -5,   -1, 	   1,   -6
.2byte  -13,   -7, 	  -5,   -2, 	  -3,    0, 	   1,   -7
.2byte  -10,  -11, 	  -7,   -9, 	  -8,   -5, 	   1,   -6
.2byte  -13,   -4, 	  -5,   -2, 	  -1,    1, 	   1,   -5
.2byte  -11,   -3, 	  -5,    0, 	   0,    2, 	  -1,   -7
.2byte  -10,   -5, 	  -6,   -3, 	  -3,    0, 	   0,   -5
.2byte  -12,   -1, 	  -5,    0, 	   1,    3, 	  -1,   -4
.2byte   -1,   -6, 	  -5,   -1, 	   3,   -1, 	  -1,   -7
.2byte  -11,   -5, 	  -5,   -3, 	   0,   -1, 	   0,   -7
.2byte  -12,   -9, 	  -6,   -5, 	  -2,   -3, 	   1,   -7
.2byte   -8,  -12, 	  -1,   -9, 	  -7,   -5, 	   1,   -8
.2byte   -1,  -14, 	   3,   -8, 	  -5,   -8, 	  -1,   -8
.2byte    7,  -12, 	   0,   -9, 	   6,   -5, 	  -2,   -8
.2byte   11,   -9, 	   5,   -5, 	   1,   -3, 	  -2,   -7
.2byte   10,   -5, 	   4,   -3, 	  -1,   -1, 	  -1,   -7
.2byte   -1,   -1, 	  -5,    2, 	   3,    2, 	  -1,   -5
.2byte  -11,   -3, 	  -5,    0, 	   0,    2, 	  -1,   -7
.2byte  -14,   -7, 	  -6,   -2, 	  -4,    0, 	   0,   -7
.2byte  -10,  -11, 	  -1,   -5, 	  -7,   -2, 	   0,   -7
.2byte   -1,  -13, 	   4,   -5, 	  -6,   -5, 	  -1,   -6
.2byte    8,  -11, 	  -1,   -5, 	   5,   -2, 	  -2,   -7
.2byte   12,   -7, 	   4,   -2, 	   2,    0, 	  -2,   -7
.2byte   10,   -3, 	   4,    0, 	  -1,    2, 	   0,   -7
sNumelAnimTable1:
.4byte sNumelAnims_1_1
.4byte sNumelAnims_1_2
.4byte sNumelAnims_1_3
.4byte sNumelAnims_1_4
.4byte sNumelAnims_1_5
.4byte sNumelAnims_1_6
.4byte sNumelAnims_1_7
.4byte sNumelAnims_1_8
sNumelAnimTable2:
.4byte sNumelAnims_2_1
.4byte sNumelAnims_2_2
.4byte sNumelAnims_2_3
.4byte sNumelAnims_2_4
.4byte sNumelAnims_2_5
.4byte sNumelAnims_2_6
.4byte sNumelAnims_2_7
.4byte sNumelAnims_2_8
sNumelAnimTable3:
.4byte sNumelAnims_3_1
.4byte sNumelAnims_3_2
.4byte sNumelAnims_3_3
.4byte sNumelAnims_3_4
.4byte sNumelAnims_3_5
.4byte sNumelAnims_3_6
.4byte sNumelAnims_3_7
.4byte sNumelAnims_3_8
sNumelAnimTable4:
.4byte sNumelAnims_4_1
.4byte sNumelAnims_4_2
.4byte sNumelAnims_4_3
.4byte sNumelAnims_4_4
.4byte sNumelAnims_4_5
.4byte sNumelAnims_4_6
.4byte sNumelAnims_4_7
.4byte sNumelAnims_4_8
sNumelAnimTable5:
.4byte sNumelAnims_5_1
.4byte sNumelAnims_5_2
.4byte sNumelAnims_5_3
.4byte sNumelAnims_5_4
.4byte sNumelAnims_5_5
.4byte sNumelAnims_5_6
.4byte sNumelAnims_5_7
.4byte sNumelAnims_5_8
sNumelAnimTable6:
.4byte sNumelAnims_6_1
.4byte sNumelAnims_6_1
.4byte sNumelAnims_6_1
.4byte sNumelAnims_6_1
.4byte sNumelAnims_6_1
.4byte sNumelAnims_6_1
.4byte sNumelAnims_6_1
.4byte sNumelAnims_6_1
sNumelAnimTable7:
.4byte sNumelAnims_7_1
.4byte sNumelAnims_7_2
.4byte sNumelAnims_7_3
.4byte sNumelAnims_7_4
.4byte sNumelAnims_7_5
.4byte sNumelAnims_7_6
.4byte sNumelAnims_7_7
.4byte sNumelAnims_7_8
sNumelAnimTable8:
.4byte sNumelAnims_8_1
.4byte sNumelAnims_8_2
.4byte sNumelAnims_8_3
.4byte sNumelAnims_8_4
.4byte sNumelAnims_8_5
.4byte sNumelAnims_8_6
.4byte sNumelAnims_8_7
.4byte sNumelAnims_8_8
sNumelAnimTable9:
.4byte sNumelAnims_9_1
.4byte sNumelAnims_9_2
.4byte sNumelAnims_9_3
.4byte sNumelAnims_9_4
.4byte sNumelAnims_9_5
.4byte sNumelAnims_9_6
.4byte sNumelAnims_9_7
.4byte sNumelAnims_9_8
sNumelAnimTable10:
.4byte sNumelAnims_10_1
.4byte sNumelAnims_10_2
.4byte sNumelAnims_10_3
.4byte sNumelAnims_10_4
.4byte sNumelAnims_10_5
.4byte sNumelAnims_10_6
.4byte sNumelAnims_10_7
.4byte sNumelAnims_10_8
sNumelAnimTable11:
.4byte sNumelAnims_11_1
.4byte sNumelAnims_11_2
.4byte sNumelAnims_11_3
.4byte sNumelAnims_11_4
.4byte sNumelAnims_11_5
.4byte sNumelAnims_11_6
.4byte sNumelAnims_11_7
.4byte sNumelAnims_11_8
sNumelAnimTable12:
.4byte sNumelAnims_12_1
.4byte sNumelAnims_12_2
.4byte sNumelAnims_12_3
.4byte sNumelAnims_12_4
.4byte sNumelAnims_12_5
.4byte sNumelAnims_12_6
.4byte sNumelAnims_12_7
.4byte sNumelAnims_12_8
sNumelAnimTable13:
.4byte sNumelAnims_13_1
.4byte sNumelAnims_13_2
.4byte sNumelAnims_13_3
.4byte sNumelAnims_13_4
.4byte sNumelAnims_13_5
.4byte sNumelAnims_13_6
.4byte sNumelAnims_13_7
.4byte sNumelAnims_13_8
sAxAnimationsNumel:
.4byte sNumelAnimTable1
.4byte sNumelAnimTable2
.4byte sNumelAnimTable3
.4byte sNumelAnimTable4
.4byte sNumelAnimTable5
.4byte sNumelAnimTable6
.4byte sNumelAnimTable7
.4byte sNumelAnimTable8
.4byte sNumelAnimTable9
.4byte sNumelAnimTable10
.4byte sNumelAnimTable11
.4byte sNumelAnimTable12
.4byte sNumelAnimTable13
sAxSpritesNumel:
.4byte sNumelSprites1
.4byte sNumelSprites2
.4byte sNumelSprites3
.4byte sNumelSprites4
.4byte sNumelSprites5
.4byte sNumelSprites6
.4byte sNumelSprites7
.4byte sNumelSprites8
.4byte sNumelSprites9
.4byte sNumelSprites10
.4byte sNumelSprites11
.4byte sNumelSprites12
.4byte sNumelSprites13
.4byte sNumelSprites14
.4byte sNumelSprites15
.4byte sNumelSprites16
.4byte sNumelSprites17
.4byte sNumelSprites18
.4byte sNumelSprites19
.4byte sNumelSprites20
.4byte sNumelSprites21
.4byte sNumelSprites22
.4byte sNumelSprites23
.4byte sNumelSprites24
.4byte sNumelSprites25
.4byte sNumelSprites26
.4byte sNumelSprites27
.4byte sNumelSprites28
.4byte sNumelSprites29
.4byte sNumelSprites30
.4byte sNumelSprites31
.4byte sNumelSprites32
.4byte sNumelSprites33
.4byte sNumelSprites34
.4byte sNumelSprites35
.4byte sNumelSprites36
.4byte sNumelSprites37
.4byte sNumelSprites38
.4byte sNumelSprites39
.4byte sNumelSprites40
.4byte sNumelSprites41
.4byte sNumelSprites42
sAxMainNumel:
ax_main sAxPosesNumel, sAxAnimationsNumel, 13, sAxSpritesNumel, sAxPositionsNumel
