.global gAxOmanyte
gAxOmanyte:
ax_siro sAxMainOmanyte
sOmanytePose1:
ax_pose 0, 0x01fa, 0x0108, 0x0c00
ax_pose 1, 0x81ee, 0x80f8, 0x0c01
ax_pose_terminator
sOmanytePose2:
ax_pose 2, 0x81ee, 0x80f8, 0x0c00
ax_pose_terminator
sOmanytePose3:
ax_pose 3, 0x81ee, 0x80f8, 0x0c00
ax_pose_terminator
sOmanytePose4:
ax_pose 4, 0x01ee, 0x90ee, 0x0c00
ax_pose_terminator
sOmanytePose5:
ax_pose 5, 0x01ee, 0x90ee, 0x0c00
ax_pose_terminator
sOmanytePose6:
ax_pose 6, 0x01ee, 0x90ee, 0x0c00
ax_pose_terminator
sOmanytePose7:
ax_pose 7, 0x01ee, 0x90ee, 0x0c00
ax_pose_terminator
sOmanytePose8:
ax_pose 8, 0x01ee, 0x90ee, 0x0c00
ax_pose_terminator
sOmanytePose9:
ax_pose 9, 0x01ee, 0x90ec, 0x0c00
ax_pose_terminator
sOmanytePose10:
ax_pose 10, 0x01ee, 0x90ee, 0x0c00
ax_pose_terminator
sOmanytePose11:
ax_pose 11, 0x01ee, 0x90ee, 0x0c00
ax_pose_terminator
sOmanytePose12:
ax_pose 12, 0x01ee, 0x90ee, 0x0c00
ax_pose_terminator
sOmanytePose13:
ax_pose 13, 0x01ee, 0x80f2, 0x0c00
ax_pose_terminator
sOmanytePose14:
ax_pose 14, 0x81ee, 0x80f8, 0x0c00
ax_pose_terminator
sOmanytePose15:
ax_pose 15, 0x01ee, 0x80f2, 0x0c00
ax_pose_terminator
sOmanytePose16:
ax_pose 10, 0x01ee, 0x80f2, 0x0c00
ax_pose_terminator
sOmanytePose17:
ax_pose 11, 0x01ee, 0x80f2, 0x0c00
ax_pose_terminator
sOmanytePose18:
ax_pose 12, 0x01ee, 0x80f2, 0x0c00
ax_pose_terminator
sOmanytePose19:
ax_pose 7, 0x01ee, 0x80f2, 0x0c00
ax_pose_terminator
sOmanytePose20:
ax_pose 8, 0x01ee, 0x80f2, 0x0c00
ax_pose_terminator
sOmanytePose21:
ax_pose 9, 0x01ee, 0x80f4, 0x0c00
ax_pose_terminator
sOmanytePose22:
ax_pose 4, 0x01ee, 0x80f2, 0x0c00
ax_pose_terminator
sOmanytePose23:
ax_pose 5, 0x01ee, 0x80f2, 0x0c00
ax_pose_terminator
sOmanytePose24:
ax_pose 6, 0x01ee, 0x80f2, 0x0c00
ax_pose_terminator
sOmanytePose25:
ax_pose 0, 0x01fa, 0x0108, 0x0c00
ax_pose 1, 0x81ee, 0x80f8, 0x0c01
ax_pose_terminator
sOmanytePose26:
ax_pose 2, 0x81ee, 0x80f8, 0x0c00
ax_pose_terminator
sOmanytePose27:
ax_pose 3, 0x81ee, 0x80f8, 0x0c00
ax_pose_terminator
sOmanytePose28:
ax_pose 4, 0x01ee, 0x90ee, 0x0c00
ax_pose_terminator
sOmanytePose29:
ax_pose 5, 0x01ee, 0x90ee, 0x0c00
ax_pose_terminator
sOmanytePose30:
ax_pose 6, 0x01ee, 0x90ee, 0x0c00
ax_pose_terminator
sOmanytePose31:
ax_pose 7, 0x01ee, 0x90ee, 0x0c00
ax_pose_terminator
sOmanytePose32:
ax_pose 8, 0x01ee, 0x90ee, 0x0c00
ax_pose_terminator
sOmanytePose33:
ax_pose 9, 0x01ee, 0x90ec, 0x0c00
ax_pose_terminator
sOmanytePose34:
ax_pose 10, 0x01ee, 0x90ee, 0x0c00
ax_pose_terminator
sOmanytePose35:
ax_pose 11, 0x01ee, 0x90ee, 0x0c00
ax_pose_terminator
sOmanytePose36:
ax_pose 12, 0x01ee, 0x90ee, 0x0c00
ax_pose_terminator
sOmanytePose37:
ax_pose 13, 0x01ee, 0x80f2, 0x0c00
ax_pose_terminator
sOmanytePose38:
ax_pose 14, 0x81ee, 0x80f8, 0x0c00
ax_pose_terminator
sOmanytePose39:
ax_pose 15, 0x01ee, 0x80f2, 0x0c00
ax_pose_terminator
sOmanytePose40:
ax_pose 10, 0x01ee, 0x80f2, 0x0c00
ax_pose_terminator
sOmanytePose41:
ax_pose 11, 0x01ee, 0x80f2, 0x0c00
ax_pose_terminator
sOmanytePose42:
ax_pose 12, 0x01ee, 0x80f2, 0x0c00
ax_pose_terminator
sOmanytePose43:
ax_pose 7, 0x01ee, 0x80f2, 0x0c00
ax_pose_terminator
sOmanytePose44:
ax_pose 8, 0x01ee, 0x80f2, 0x0c00
ax_pose_terminator
sOmanytePose45:
ax_pose 9, 0x01ee, 0x80f4, 0x0c00
ax_pose_terminator
sOmanytePose46:
ax_pose 4, 0x01ee, 0x80f2, 0x0c00
ax_pose_terminator
sOmanytePose47:
ax_pose 5, 0x01ee, 0x80f2, 0x0c00
ax_pose_terminator
sOmanytePose48:
ax_pose 6, 0x01ee, 0x80f2, 0x0c00
ax_pose_terminator
sOmanytePose49:
ax_pose 0, 0x01fa, 0x0108, 0x0c00
ax_pose 1, 0x81ee, 0x80f8, 0x0c01
ax_pose_terminator
sOmanytePose50:
ax_pose 2, 0x81ee, 0x80f8, 0x0c00
ax_pose_terminator
sOmanytePose51:
ax_pose 3, 0x81ee, 0x80f8, 0x0c00
ax_pose_terminator
sOmanytePose52:
ax_pose 4, 0x01ee, 0x90ee, 0x0c00
ax_pose_terminator
sOmanytePose53:
ax_pose 5, 0x01ee, 0x90ee, 0x0c00
ax_pose_terminator
sOmanytePose54:
ax_pose 6, 0x01ee, 0x90ee, 0x0c00
ax_pose_terminator
sOmanytePose55:
ax_pose 7, 0x01ee, 0x90ee, 0x0c00
ax_pose_terminator
sOmanytePose56:
ax_pose 8, 0x01ee, 0x90ee, 0x0c00
ax_pose_terminator
sOmanytePose57:
ax_pose 9, 0x01ee, 0x90ec, 0x0c00
ax_pose_terminator
sOmanytePose58:
ax_pose 10, 0x01ee, 0x90ee, 0x0c00
ax_pose_terminator
sOmanytePose59:
ax_pose 11, 0x01ee, 0x90ee, 0x0c00
ax_pose_terminator
sOmanytePose60:
ax_pose 12, 0x01ee, 0x90ee, 0x0c00
ax_pose_terminator
sOmanytePose61:
ax_pose 13, 0x01ee, 0x80f2, 0x0c00
ax_pose_terminator
sOmanytePose62:
ax_pose 14, 0x81ee, 0x80f8, 0x0c00
ax_pose_terminator
sOmanytePose63:
ax_pose 15, 0x01ee, 0x80f2, 0x0c00
ax_pose_terminator
sOmanytePose64:
ax_pose 10, 0x01ee, 0x80f2, 0x0c00
ax_pose_terminator
sOmanytePose65:
ax_pose 11, 0x01ee, 0x80f2, 0x0c00
ax_pose_terminator
sOmanytePose66:
ax_pose 12, 0x01ee, 0x80f2, 0x0c00
ax_pose_terminator
sOmanytePose67:
ax_pose 7, 0x01ee, 0x80f2, 0x0c00
ax_pose_terminator
sOmanytePose68:
ax_pose 8, 0x01ee, 0x80f2, 0x0c00
ax_pose_terminator
sOmanytePose69:
ax_pose 9, 0x01ee, 0x80f4, 0x0c00
ax_pose_terminator
sOmanytePose70:
ax_pose 4, 0x01ee, 0x80f2, 0x0c00
ax_pose_terminator
sOmanytePose71:
ax_pose 5, 0x01ee, 0x80f2, 0x0c00
ax_pose_terminator
sOmanytePose72:
ax_pose 6, 0x01ee, 0x80f2, 0x0c00
ax_pose_terminator
sOmanytePose73:
ax_pose 0, 0x01fa, 0x0108, 0x0c00
ax_pose 1, 0x81ee, 0x80f8, 0x0c01
ax_pose_terminator
sOmanytePose74:
ax_pose 2, 0x81ee, 0x80f8, 0x0c00
ax_pose_terminator
sOmanytePose75:
ax_pose 3, 0x81ee, 0x80f8, 0x0c00
ax_pose_terminator
sOmanytePose76:
ax_pose 16, 0x81ef, 0x80f8, 0x0c00
ax_pose_terminator
sOmanytePose77:
ax_pose 4, 0x01ee, 0x90ee, 0x0c00
ax_pose_terminator
sOmanytePose78:
ax_pose 5, 0x01ee, 0x90ee, 0x0c00
ax_pose_terminator
sOmanytePose79:
ax_pose 6, 0x01ee, 0x90ee, 0x0c00
ax_pose_terminator
sOmanytePose80:
ax_pose 17, 0x01f1, 0x90ef, 0x0c00
ax_pose_terminator
sOmanytePose81:
ax_pose 7, 0x01ee, 0x90ee, 0x0c00
ax_pose_terminator
sOmanytePose82:
ax_pose 8, 0x01ee, 0x90ed, 0x0c00
ax_pose_terminator
sOmanytePose83:
ax_pose 9, 0x01ee, 0x90ed, 0x0c00
ax_pose_terminator
sOmanytePose84:
ax_pose 18, 0x01ef, 0x90ef, 0x0c00
ax_pose_terminator
sOmanytePose85:
ax_pose 10, 0x01ee, 0x90ee, 0x0c00
ax_pose_terminator
sOmanytePose86:
ax_pose 11, 0x01ee, 0x90ee, 0x0c00
ax_pose_terminator
sOmanytePose87:
ax_pose 12, 0x01ee, 0x90ee, 0x0c00
ax_pose_terminator
sOmanytePose88:
ax_pose 19, 0x01ef, 0x90ee, 0x0c00
ax_pose_terminator
sOmanytePose89:
ax_pose 13, 0x01ee, 0x80f2, 0x0c00
ax_pose_terminator
sOmanytePose90:
ax_pose 14, 0x81ee, 0x80f8, 0x0c00
ax_pose_terminator
sOmanytePose91:
ax_pose 15, 0x01ee, 0x80f2, 0x0c00
ax_pose_terminator
sOmanytePose92:
ax_pose 20, 0x01ee, 0x80f2, 0x0c00
ax_pose_terminator
sOmanytePose93:
ax_pose 10, 0x01ee, 0x80f2, 0x0c00
ax_pose_terminator
sOmanytePose94:
ax_pose 11, 0x01ee, 0x80f2, 0x0c00
ax_pose_terminator
sOmanytePose95:
ax_pose 12, 0x01ee, 0x80f2, 0x0c00
ax_pose_terminator
sOmanytePose96:
ax_pose 19, 0x01ef, 0x80f2, 0x0c00
ax_pose_terminator
sOmanytePose97:
ax_pose 7, 0x01ee, 0x80f2, 0x0c00
ax_pose_terminator
sOmanytePose98:
ax_pose 8, 0x01ee, 0x80f3, 0x0c00
ax_pose_terminator
sOmanytePose99:
ax_pose 9, 0x01ee, 0x80f3, 0x0c00
ax_pose_terminator
sOmanytePose100:
ax_pose 18, 0x01ef, 0x80f1, 0x0c00
ax_pose_terminator
sOmanytePose101:
ax_pose 4, 0x01ee, 0x80f2, 0x0c00
ax_pose_terminator
sOmanytePose102:
ax_pose 5, 0x01ee, 0x80f2, 0x0c00
ax_pose_terminator
sOmanytePose103:
ax_pose 6, 0x01ee, 0x80f2, 0x0c00
ax_pose_terminator
sOmanytePose104:
ax_pose 17, 0x01f1, 0x80f1, 0x0c00
ax_pose_terminator
sOmanytePose105:
ax_pose 0, 0x01fa, 0x0108, 0x0c00
ax_pose 1, 0x81ee, 0x80f8, 0x0c01
ax_pose_terminator
sOmanytePose106:
ax_pose 21, 0x81ea, 0x80f8, 0x0c00
ax_pose_terminator
sOmanytePose107:
ax_pose 22, 0x81ee, 0x80f8, 0x0c00
ax_pose_terminator
sOmanytePose108:
ax_pose 4, 0x01ee, 0x90ee, 0x0c00
ax_pose_terminator
sOmanytePose109:
ax_pose 23, 0x01ea, 0x90ee, 0x0c00
ax_pose_terminator
sOmanytePose110:
ax_pose 24, 0x01ee, 0x90ee, 0x0c00
ax_pose_terminator
sOmanytePose111:
ax_pose 7, 0x01ee, 0x90ee, 0x0c00
ax_pose_terminator
sOmanytePose112:
ax_pose 25, 0x01ea, 0x90ee, 0x0c00
ax_pose_terminator
sOmanytePose113:
ax_pose 26, 0x01ee, 0x90ee, 0x0c00
ax_pose_terminator
sOmanytePose114:
ax_pose 10, 0x01ee, 0x90ee, 0x0c00
ax_pose_terminator
sOmanytePose115:
ax_pose 27, 0x01ec, 0x90ee, 0x0c00
ax_pose_terminator
sOmanytePose116:
ax_pose 28, 0x01ee, 0x90ee, 0x0c00
ax_pose_terminator
sOmanytePose117:
ax_pose 13, 0x01ee, 0x80f2, 0x0c00
ax_pose_terminator
sOmanytePose118:
ax_pose 29, 0x01ee, 0x80f2, 0x0c00
ax_pose_terminator
sOmanytePose119:
ax_pose 30, 0x81ee, 0x80f8, 0x0c00
ax_pose_terminator
sOmanytePose120:
ax_pose 10, 0x01ee, 0x80f2, 0x0c00
ax_pose_terminator
sOmanytePose121:
ax_pose 27, 0x01ec, 0x80f2, 0x0c00
ax_pose_terminator
sOmanytePose122:
ax_pose 28, 0x01ee, 0x80f2, 0x0c00
ax_pose_terminator
sOmanytePose123:
ax_pose 7, 0x01ee, 0x80f2, 0x0c00
ax_pose_terminator
sOmanytePose124:
ax_pose 25, 0x01ea, 0x80f2, 0x0c00
ax_pose_terminator
sOmanytePose125:
ax_pose 26, 0x01ee, 0x80f2, 0x0c00
ax_pose_terminator
sOmanytePose126:
ax_pose 4, 0x01ee, 0x80f2, 0x0c00
ax_pose_terminator
sOmanytePose127:
ax_pose 23, 0x01ea, 0x80f2, 0x0c00
ax_pose_terminator
sOmanytePose128:
ax_pose 24, 0x01ee, 0x80f2, 0x0c00
ax_pose_terminator
sOmanytePose129:
ax_pose 31, 0x01f0, 0x80f4, 0x0c00
ax_pose_terminator
sOmanytePose130:
ax_pose 32, 0x01f0, 0x80f4, 0x0c00
ax_pose_terminator
sOmanytePose131:
ax_pose 33, 0x01e3, 0x80f0, 0x0c00
ax_pose_terminator
sOmanytePose132:
ax_pose 34, 0x01e5, 0x90ed, 0x0c00
ax_pose_terminator
sOmanytePose133:
ax_pose 35, 0x01e5, 0x90ed, 0x0c00
ax_pose_terminator
sOmanytePose134:
ax_pose 36, 0x01e3, 0x90ed, 0x0c00
ax_pose_terminator
sOmanytePose135:
ax_pose 37, 0x01e3, 0x80f1, 0x0c00
ax_pose_terminator
sOmanytePose136:
ax_pose 36, 0x01e3, 0x80f3, 0x0c00
ax_pose_terminator
sOmanytePose137:
ax_pose 35, 0x01e5, 0x80f3, 0x0c00
ax_pose_terminator
sOmanytePose138:
ax_pose 34, 0x01e5, 0x80f3, 0x0c00
ax_pose_terminator
sOmanytePose139:
ax_pose 0, 0x01fa, 0x0108, 0x0c00
ax_pose 1, 0x81ee, 0x80f8, 0x0c01
ax_pose_terminator
sOmanytePose140:
ax_pose 2, 0x81ee, 0x80f8, 0x0c00
ax_pose_terminator
sOmanytePose141:
ax_pose 3, 0x81ee, 0x80f8, 0x0c00
ax_pose_terminator
sOmanytePose142:
ax_pose 4, 0x01ee, 0x90ee, 0x0c00
ax_pose_terminator
sOmanytePose143:
ax_pose 5, 0x01ee, 0x90ee, 0x0c00
ax_pose_terminator
sOmanytePose144:
ax_pose 6, 0x01ee, 0x90ee, 0x0c00
ax_pose_terminator
sOmanytePose145:
ax_pose 7, 0x01ee, 0x90ee, 0x0c00
ax_pose_terminator
sOmanytePose146:
ax_pose 8, 0x01ee, 0x90ee, 0x0c00
ax_pose_terminator
sOmanytePose147:
ax_pose 9, 0x01ee, 0x90ec, 0x0c00
ax_pose_terminator
sOmanytePose148:
ax_pose 10, 0x01ee, 0x90ee, 0x0c00
ax_pose_terminator
sOmanytePose149:
ax_pose 11, 0x01ee, 0x90ee, 0x0c00
ax_pose_terminator
sOmanytePose150:
ax_pose 12, 0x01ee, 0x90ee, 0x0c00
ax_pose_terminator
sOmanytePose151:
ax_pose 13, 0x01ee, 0x80f2, 0x0c00
ax_pose_terminator
sOmanytePose152:
ax_pose 14, 0x81ee, 0x80f8, 0x0c00
ax_pose_terminator
sOmanytePose153:
ax_pose 15, 0x01ee, 0x80f2, 0x0c00
ax_pose_terminator
sOmanytePose154:
ax_pose 10, 0x01ee, 0x80f2, 0x0c00
ax_pose_terminator
sOmanytePose155:
ax_pose 11, 0x01ee, 0x80f2, 0x0c00
ax_pose_terminator
sOmanytePose156:
ax_pose 12, 0x01ee, 0x80f2, 0x0c00
ax_pose_terminator
sOmanytePose157:
ax_pose 7, 0x01ee, 0x80f2, 0x0c00
ax_pose_terminator
sOmanytePose158:
ax_pose 8, 0x01ee, 0x80f2, 0x0c00
ax_pose_terminator
sOmanytePose159:
ax_pose 9, 0x01ee, 0x80f4, 0x0c00
ax_pose_terminator
sOmanytePose160:
ax_pose 4, 0x01ee, 0x80f2, 0x0c00
ax_pose_terminator
sOmanytePose161:
ax_pose 5, 0x01ee, 0x80f2, 0x0c00
ax_pose_terminator
sOmanytePose162:
ax_pose 6, 0x01ee, 0x80f2, 0x0c00
ax_pose_terminator
sOmanytePose163:
ax_pose 0, 0x01fa, 0x0108, 0x0c00
ax_pose 1, 0x81ee, 0x80f8, 0x0c01
ax_pose_terminator
sOmanytePose164:
ax_pose 4, 0x01ee, 0x80f2, 0x0c00
ax_pose_terminator
sOmanytePose165:
ax_pose 7, 0x01ee, 0x80f2, 0x0c00
ax_pose_terminator
sOmanytePose166:
ax_pose 10, 0x01ee, 0x80f2, 0x0c00
ax_pose_terminator
sOmanytePose167:
ax_pose 13, 0x01ee, 0x80f2, 0x0c00
ax_pose_terminator
sOmanytePose168:
ax_pose 10, 0x01ee, 0x90ee, 0x0c00
ax_pose_terminator
sOmanytePose169:
ax_pose 7, 0x01ee, 0x90ee, 0x0c00
ax_pose_terminator
sOmanytePose170:
ax_pose 4, 0x01ee, 0x90ee, 0x0c00
ax_pose_terminator
sOmanytePose171:
ax_pose 16, 0x81ef, 0x80f8, 0x0c00
ax_pose_terminator
sOmanytePose172:
ax_pose 17, 0x01f1, 0x90ef, 0x0c00
ax_pose_terminator
sOmanytePose173:
ax_pose 18, 0x01ef, 0x90ef, 0x0c00
ax_pose_terminator
sOmanytePose174:
ax_pose 19, 0x01ef, 0x90ee, 0x0c00
ax_pose_terminator
sOmanytePose175:
ax_pose 20, 0x01ee, 0x80f2, 0x0c00
ax_pose_terminator
sOmanytePose176:
ax_pose 19, 0x01ef, 0x80f2, 0x0c00
ax_pose_terminator
sOmanytePose177:
ax_pose 18, 0x01ef, 0x80f1, 0x0c00
ax_pose_terminator
sOmanytePose178:
ax_pose 17, 0x01f1, 0x80f1, 0x0c00
ax_pose_terminator
sOmanytePose179:
ax_pose 0, 0x01fa, 0x0108, 0x0c00
ax_pose 1, 0x81ee, 0x80f8, 0x0c01
ax_pose_terminator
sOmanytePose180:
ax_pose 16, 0x81ef, 0x80f8, 0x0c00
ax_pose_terminator
sOmanytePose181:
ax_pose 2, 0x81ee, 0x80f8, 0x0c00
ax_pose_terminator
sOmanytePose182:
ax_pose 4, 0x01ee, 0x90ee, 0x0c00
ax_pose_terminator
sOmanytePose183:
ax_pose 17, 0x01f1, 0x90ef, 0x0c00
ax_pose_terminator
sOmanytePose184:
ax_pose 5, 0x01ee, 0x90ec, 0x0c00
ax_pose_terminator
sOmanytePose185:
ax_pose 7, 0x01ee, 0x90ee, 0x0c00
ax_pose_terminator
sOmanytePose186:
ax_pose 18, 0x01ef, 0x90ef, 0x0c00
ax_pose_terminator
sOmanytePose187:
ax_pose 8, 0x01ee, 0x90ed, 0x0c00
ax_pose_terminator
sOmanytePose188:
ax_pose 9, 0x01ee, 0x90ed, 0x0c00
ax_pose_terminator
sOmanytePose189:
ax_pose 10, 0x01ee, 0x90ee, 0x0c00
ax_pose_terminator
sOmanytePose190:
ax_pose 19, 0x01ef, 0x90ee, 0x0c00
ax_pose_terminator
sOmanytePose191:
ax_pose 11, 0x01ee, 0x90ed, 0x0c00
ax_pose_terminator
sOmanytePose192:
ax_pose 13, 0x01ee, 0x80f2, 0x0c00
ax_pose_terminator
sOmanytePose193:
ax_pose 20, 0x01ee, 0x80f2, 0x0c00
ax_pose_terminator
sOmanytePose194:
ax_pose 14, 0x81ee, 0x80f8, 0x0c00
ax_pose_terminator
sOmanytePose195:
ax_pose 10, 0x01ee, 0x80f2, 0x0c00
ax_pose_terminator
sOmanytePose196:
ax_pose 19, 0x01ef, 0x80f2, 0x0c00
ax_pose_terminator
sOmanytePose197:
ax_pose 11, 0x01ee, 0x80f3, 0x0c00
ax_pose_terminator
sOmanytePose198:
ax_pose 7, 0x01ee, 0x80f2, 0x0c00
ax_pose_terminator
sOmanytePose199:
ax_pose 18, 0x01ef, 0x80f1, 0x0c00
ax_pose_terminator
sOmanytePose200:
ax_pose 8, 0x01ee, 0x80f3, 0x0c00
ax_pose_terminator
sOmanytePose201:
ax_pose 4, 0x01ee, 0x80f2, 0x0c00
ax_pose_terminator
sOmanytePose202:
ax_pose 17, 0x01f1, 0x80f1, 0x0c00
ax_pose_terminator
sOmanytePose203:
ax_pose 5, 0x01ee, 0x80f4, 0x0c00
ax_pose_terminator
sOmanytePose204:
ax_pose 0, 0x01fa, 0x0108, 0x0c00
ax_pose 1, 0x81ee, 0x80f8, 0x0c01
ax_pose_terminator
sOmanytePose205:
ax_pose 4, 0x01ee, 0x80f2, 0x0c00
ax_pose_terminator
sOmanytePose206:
ax_pose 7, 0x01ee, 0x80f2, 0x0c00
ax_pose_terminator
sOmanytePose207:
ax_pose 10, 0x01ee, 0x80f2, 0x0c00
ax_pose_terminator
sOmanytePose208:
ax_pose 13, 0x01ee, 0x80f2, 0x0c00
ax_pose_terminator
sOmanytePose209:
ax_pose 10, 0x01ee, 0x90ee, 0x0c00
ax_pose_terminator
sOmanytePose210:
ax_pose 7, 0x01ee, 0x90ee, 0x0c00
ax_pose_terminator
sOmanytePose211:
ax_pose 4, 0x01ee, 0x90ee, 0x0c00
ax_pose_terminator
sOmanytePose212:
ax_pose 0, 0x01fa, 0x0108, 0x0c00
ax_pose 1, 0x81ee, 0x80f8, 0x0c01
ax_pose_terminator
sOmanytePose213:
ax_pose 4, 0x01ee, 0x80f2, 0x0c00
ax_pose_terminator
sOmanytePose214:
ax_pose 7, 0x01ee, 0x80f2, 0x0c00
ax_pose_terminator
sOmanytePose215:
ax_pose 10, 0x01ee, 0x80f2, 0x0c00
ax_pose_terminator
sOmanytePose216:
ax_pose 13, 0x01ee, 0x80f2, 0x0c00
ax_pose_terminator
sOmanytePose217:
ax_pose 10, 0x01ee, 0x90ee, 0x0c00
ax_pose_terminator
sOmanytePose218:
ax_pose 7, 0x01ee, 0x90ee, 0x0c00
ax_pose_terminator
sOmanytePose219:
ax_pose 4, 0x01ee, 0x90ee, 0x0c00
ax_pose_terminator
.align 2
sOmanyteAnims_1_1:
ax_anim 8, 0, 0, 0, 0, 0, 0,
ax_anim 8, 0, 1, 0, 0, 0, 0,
ax_anim 8, 0, 0, 0, 0, 0, 0,
ax_anim 8, 0, 2, 0, 0, 0, 0,
ax_anim_terminator
sOmanyteAnims_1_2:
ax_anim 8, 0, 3, 0, 0, 0, 0,
ax_anim 8, 0, 4, 0, 0, 0, 0,
ax_anim 8, 0, 3, 0, 0, 0, 0,
ax_anim 8, 0, 5, 0, 0, 0, 0,
ax_anim_terminator
sOmanyteAnims_1_3:
ax_anim 8, 0, 6, 0, 0, 0, 0,
ax_anim 8, 0, 7, 0, 0, 0, 0,
ax_anim 8, 0, 6, 0, 0, 0, 0,
ax_anim 8, 0, 8, 0, 0, 0, 0,
ax_anim_terminator
sOmanyteAnims_1_4:
ax_anim 8, 0, 9, 0, 0, 0, 0,
ax_anim 8, 0, 10, 0, 0, 0, 0,
ax_anim 8, 0, 9, 0, 0, 0, 0,
ax_anim 8, 0, 11, 0, 0, 0, 0,
ax_anim_terminator
sOmanyteAnims_1_5:
ax_anim 8, 0, 12, 0, 0, 0, 0,
ax_anim 8, 0, 13, 0, 0, 0, 0,
ax_anim 8, 0, 12, 0, 0, 0, 0,
ax_anim 8, 0, 14, 0, 0, 0, 0,
ax_anim_terminator
sOmanyteAnims_1_6:
ax_anim 8, 0, 15, 0, 0, 0, 0,
ax_anim 8, 0, 16, 0, 0, 0, 0,
ax_anim 8, 0, 15, 0, 0, 0, 0,
ax_anim 8, 0, 17, 0, 0, 0, 0,
ax_anim_terminator
sOmanyteAnims_1_7:
ax_anim 8, 0, 18, 0, 0, 0, 0,
ax_anim 8, 0, 19, 0, 0, 0, 0,
ax_anim 8, 0, 18, 0, 0, 0, 0,
ax_anim 8, 0, 20, 0, 0, 0, 0,
ax_anim_terminator
sOmanyteAnims_1_8:
ax_anim 8, 0, 21, 0, 0, 0, 0,
ax_anim 8, 0, 22, 0, 0, 0, 0,
ax_anim 8, 0, 21, 0, 0, 0, 0,
ax_anim 8, 0, 23, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sOmanyteAnims_2_1:
ax_anim 2, 0, 24, 0, -1, 0, -1,
ax_anim 4, 0, 24, 0, -2, 0, -2,
ax_anim 1, 0, 26, 0, 0, 0, 0,
ax_anim 1, 2, 25, 0, 4, 0, 4,
ax_anim 1, 0, 26, 0, 10, 0, 10,
ax_anim 2, 0, 25, 0, 21, 0, 21,
ax_anim 2, 1, 25, 1, 21, 1, 21,
ax_anim 2, 0, 25, 0, 21, 0, 21,
ax_anim 2, 0, 25, 1, 21, 1, 21,
ax_anim 2, 0, 24, 0, 6, 0, 6,
ax_anim_terminator
sOmanyteAnims_2_2:
ax_anim 2, 0, 27, -1, -1, -1, -1,
ax_anim 4, 0, 27, -2, -2, -2, -2,
ax_anim 1, 0, 29, 0, 0, 0, 0,
ax_anim 1, 2, 28, 4, 4, 4, 4,
ax_anim 1, 0, 29, 9, 11, 9, 11,
ax_anim 2, 0, 28, 19, 22, 19, 22,
ax_anim 2, 1, 28, 20, 21, 20, 21,
ax_anim 2, 0, 28, 19, 22, 19, 22,
ax_anim 2, 0, 28, 20, 21, 20, 21,
ax_anim 2, 0, 27, 6, 6, 6, 6,
ax_anim_terminator
sOmanyteAnims_2_3:
ax_anim 2, 0, 30, -1, 0, -1, 0,
ax_anim 4, 0, 30, -2, 0, -2, 0,
ax_anim 1, 0, 32, 0, 0, 0, 0,
ax_anim 1, 2, 31, 4, 0, 4, 0,
ax_anim 1, 0, 32, 10, 0, 10, 0,
ax_anim 2, 0, 31, 23, 0, 23, 0,
ax_anim 2, 1, 31, 23, 1, 23, 1,
ax_anim 2, 0, 31, 23, 0, 23, 0,
ax_anim 2, 0, 31, 23, 1, 23, 1,
ax_anim 2, 0, 30, 6, 0, 6, 0,
ax_anim_terminator
sOmanyteAnims_2_4:
ax_anim 2, 0, 33, -1, 1, -1, 1,
ax_anim 4, 0, 33, -2, 2, -2, 2,
ax_anim 1, 0, 35, 0, -1, 0, -1,
ax_anim 1, 2, 34, 5, -6, 5, -6,
ax_anim 1, 0, 35, 12, -12, 12, -12,
ax_anim 2, 0, 34, 21, -22, 21, -22,
ax_anim 2, 1, 34, 22, -21, 22, -21,
ax_anim 2, 0, 34, 21, -22, 21, -22,
ax_anim 2, 0, 34, 22, -21, 22, -21,
ax_anim 2, 0, 33, 6, -6, 6, -6,
ax_anim_terminator
sOmanyteAnims_2_5:
ax_anim 2, 0, 36, 0, 1, 0, 1,
ax_anim 4, 0, 36, 0, 2, 0, 2,
ax_anim 1, 0, 38, 0, 0, 0, 0,
ax_anim 1, 2, 37, 0, -4, 0, -4,
ax_anim 1, 0, 38, 0, -11, 0, -11,
ax_anim 2, 0, 37, 0, -22, 0, -22,
ax_anim 2, 1, 37, 1, -22, 1, -22,
ax_anim 2, 0, 37, 0, -22, 0, -22,
ax_anim 2, 0, 37, 1, -22, 1, -22,
ax_anim 2, 0, 36, 0, -6, 0, -6,
ax_anim_terminator
sOmanyteAnims_2_6:
ax_anim 2, 0, 39, 1, 1, 1, 1,
ax_anim 4, 0, 39, 2, 2, 2, 2,
ax_anim 1, 0, 41, 0, -1, 0, -1,
ax_anim 1, 2, 40, -5, -6, -5, -6,
ax_anim 1, 0, 41, -11, -13, -11, -13,
ax_anim 2, 0, 40, -18, -24, -18, -24,
ax_anim 2, 1, 40, -19, -23, -19, -23,
ax_anim 2, 0, 40, -18, -24, -18, -24,
ax_anim 2, 0, 40, -19, -23, -19, -23,
ax_anim 2, 0, 39, -6, -6, -6, -6,
ax_anim_terminator
sOmanyteAnims_2_7:
ax_anim 2, 0, 42, 1, 0, 1, 0,
ax_anim 4, 0, 42, 2, 0, 2, 0,
ax_anim 1, 0, 44, 0, 0, 0, 0,
ax_anim 1, 2, 43, -4, 0, -4, 0,
ax_anim 1, 0, 44, -10, 0, -10, 0,
ax_anim 2, 0, 43, -22, 0, -22, 0,
ax_anim 2, 1, 43, -22, 1, -22, 1,
ax_anim 2, 0, 43, -22, 0, -22, 0,
ax_anim 2, 0, 43, -22, 1, -22, 1,
ax_anim 2, 0, 42, -6, 0, -6, 0,
ax_anim_terminator
sOmanyteAnims_2_8:
ax_anim 2, 0, 45, 1, -1, 1, -1,
ax_anim 4, 0, 45, 2, -2, 2, -2,
ax_anim 1, 0, 47, 0, 0, 0, 0,
ax_anim 1, 2, 46, -4, 4, -4, 4,
ax_anim 1, 0, 47, -11, 10, -11, 10,
ax_anim 2, 0, 46, -24, 20, -24, 20,
ax_anim 2, 1, 46, -25, 19, -25, 19,
ax_anim 2, 0, 46, -24, 20, -24, 20,
ax_anim 2, 0, 46, -25, 19, -25, 19,
ax_anim 2, 0, 45, -6, 6, -6, 6,
ax_anim_terminator
.align 2
sOmanyteAnims_3_1:
ax_anim 2, 0, 48, 0, -1, 0, -1,
ax_anim 4, 0, 48, 0, -2, 0, -2,
ax_anim 1, 0, 50, 0, 0, 0, 0,
ax_anim 1, 2, 49, 0, 4, 0, 4,
ax_anim 1, 0, 50, 0, 10, 0, 10,
ax_anim 2, 0, 49, 0, 21, 0, 21,
ax_anim 2, 1, 49, 1, 21, 1, 21,
ax_anim 2, 0, 49, 0, 21, 0, 21,
ax_anim 2, 0, 49, 1, 21, 1, 21,
ax_anim 2, 0, 48, 0, 6, 0, 6,
ax_anim_terminator
sOmanyteAnims_3_2:
ax_anim 2, 0, 51, -1, -1, -1, -1,
ax_anim 4, 0, 51, -2, -2, -2, -2,
ax_anim 1, 0, 53, 0, 0, 0, 0,
ax_anim 1, 2, 52, 4, 4, 4, 4,
ax_anim 1, 0, 53, 9, 11, 9, 11,
ax_anim 2, 0, 52, 19, 22, 19, 22,
ax_anim 2, 1, 52, 20, 21, 20, 21,
ax_anim 2, 0, 52, 19, 22, 19, 22,
ax_anim 2, 0, 52, 20, 21, 20, 21,
ax_anim 2, 0, 51, 6, 6, 6, 6,
ax_anim_terminator
sOmanyteAnims_3_3:
ax_anim 2, 0, 54, -1, 0, -1, 0,
ax_anim 4, 0, 54, -2, 0, -2, 0,
ax_anim 1, 0, 56, 0, 0, 0, 0,
ax_anim 1, 2, 55, 4, 0, 4, 0,
ax_anim 1, 0, 56, 10, 0, 10, 0,
ax_anim 2, 0, 55, 23, 0, 23, 0,
ax_anim 2, 1, 55, 23, 1, 23, 1,
ax_anim 2, 0, 55, 23, 0, 23, 0,
ax_anim 2, 0, 55, 23, 1, 23, 1,
ax_anim 2, 0, 54, 6, 0, 6, 0,
ax_anim_terminator
sOmanyteAnims_3_4:
ax_anim 2, 0, 57, -1, 1, -1, 1,
ax_anim 4, 0, 57, -2, 2, -2, 2,
ax_anim 1, 0, 59, 0, -1, 0, -1,
ax_anim 1, 2, 58, 5, -6, 5, -6,
ax_anim 1, 0, 59, 12, -12, 12, -12,
ax_anim 2, 0, 58, 21, -22, 21, -22,
ax_anim 2, 1, 58, 22, -21, 22, -21,
ax_anim 2, 0, 58, 21, -22, 21, -22,
ax_anim 2, 0, 58, 22, -21, 22, -21,
ax_anim 2, 0, 57, 6, -6, 6, -6,
ax_anim_terminator
sOmanyteAnims_3_5:
ax_anim 2, 0, 60, 0, 1, 0, 1,
ax_anim 4, 0, 60, 0, 2, 0, 2,
ax_anim 1, 0, 62, 0, 0, 0, 0,
ax_anim 1, 2, 61, 0, -4, 0, -4,
ax_anim 1, 0, 62, 0, -11, 0, -11,
ax_anim 2, 0, 61, 0, -22, 0, -22,
ax_anim 2, 1, 61, 1, -22, 1, -22,
ax_anim 2, 0, 61, 0, -22, 0, -22,
ax_anim 2, 0, 61, 1, -22, 1, -22,
ax_anim 2, 0, 60, 0, -6, 0, -6,
ax_anim_terminator
sOmanyteAnims_3_6:
ax_anim 2, 0, 63, 1, 1, 1, 1,
ax_anim 4, 0, 63, 2, 2, 2, 2,
ax_anim 1, 0, 65, 0, -1, 0, -1,
ax_anim 1, 2, 64, -5, -6, -5, -6,
ax_anim 1, 0, 65, -11, -13, -11, -13,
ax_anim 2, 0, 64, -18, -24, -18, -24,
ax_anim 2, 1, 64, -19, -23, -19, -23,
ax_anim 2, 0, 64, -18, -24, -18, -24,
ax_anim 2, 0, 64, -19, -23, -19, -23,
ax_anim 2, 0, 63, -6, -6, -6, -6,
ax_anim_terminator
sOmanyteAnims_3_7:
ax_anim 2, 0, 66, 1, 0, 1, 0,
ax_anim 4, 0, 66, 2, 0, 2, 0,
ax_anim 1, 0, 68, 0, 0, 0, 0,
ax_anim 1, 2, 67, -4, 0, -4, 0,
ax_anim 1, 0, 68, -10, 0, -10, 0,
ax_anim 2, 0, 67, -22, 0, -22, 0,
ax_anim 2, 1, 67, -22, 1, -22, 1,
ax_anim 2, 0, 67, -22, 0, -22, 0,
ax_anim 2, 0, 67, -22, 1, -22, 1,
ax_anim 2, 0, 66, -6, 0, -6, 0,
ax_anim_terminator
sOmanyteAnims_3_8:
ax_anim 2, 0, 69, 1, -1, 1, -1,
ax_anim 4, 0, 69, 2, -2, 2, -2,
ax_anim 1, 0, 71, 0, 0, 0, 0,
ax_anim 1, 2, 70, -4, 4, -4, 4,
ax_anim 1, 0, 71, -11, 10, -11, 10,
ax_anim 2, 0, 70, -24, 20, -24, 20,
ax_anim 2, 1, 70, -25, 19, -25, 19,
ax_anim 2, 0, 70, -24, 20, -24, 20,
ax_anim 2, 0, 70, -25, 19, -25, 19,
ax_anim 2, 0, 69, -6, 6, -6, 6,
ax_anim_terminator
.align 2
sOmanyteAnims_4_1:
ax_anim 1, 0, 74, 0, -2, 0, 0,
ax_anim 2, 0, 74, 0, -4, 0, 0,
ax_anim 2, 0, 74, 0, -5, 0, 0,
ax_anim 2, 2, 72, 0, -5, 0, 0,
ax_anim 2, 0, 72, 0, -4, 0, 0,
ax_anim 1, 0, 72, 0, -2, 0, 0,
ax_anim 6, 0, 75, 0, 0, 0, 0,
ax_anim 2, 1, 75, -1, 0, 0, 0,
ax_anim 2, 0, 75, 0, 0, 0, 0,
ax_anim 2, 0, 75, -1, 0, 0, 0,
ax_anim 2, 0, 75, 0, 0, 0, 0,
ax_anim 2, 0, 75, -1, 0, 0, 0,
ax_anim 2, 0, 75, 0, 0, 0, 0,
ax_anim_terminator
sOmanyteAnims_4_2:
ax_anim 1, 0, 78, 0, -2, 0, 0,
ax_anim 2, 0, 78, 0, -4, 0, 0,
ax_anim 2, 0, 78, 0, -5, 0, 0,
ax_anim 2, 2, 76, 0, -5, 0, 0,
ax_anim 2, 0, 76, 0, -4, 0, 0,
ax_anim 1, 0, 76, 0, -2, 0, 0,
ax_anim 6, 0, 79, 0, 0, 0, 0,
ax_anim 2, 1, 79, -1, 1, -1, -1,
ax_anim 2, 0, 79, 0, 0, 0, 0,
ax_anim 2, 0, 79, -1, 1, -1, -1,
ax_anim 2, 0, 79, 0, 0, 0, 0,
ax_anim 2, 0, 79, -1, 1, -1, -1,
ax_anim 2, 0, 79, 0, 0, 0, 0,
ax_anim_terminator
sOmanyteAnims_4_3:
ax_anim 1, 0, 82, 0, -2, 0, 0,
ax_anim 2, 0, 82, 0, -4, 0, 0,
ax_anim 2, 0, 82, 0, -5, 0, 0,
ax_anim 2, 2, 80, 0, -5, 0, 0,
ax_anim 2, 0, 80, 0, -4, 0, 0,
ax_anim 1, 0, 80, 0, -2, 0, 0,
ax_anim 6, 0, 83, 0, 0, 0, 0,
ax_anim 2, 1, 83, 0, 1, 0, 1,
ax_anim 2, 0, 83, 0, 0, 0, 0,
ax_anim 2, 0, 83, 0, 1, 0, 1,
ax_anim 2, 0, 83, 0, 0, 0, 0,
ax_anim 2, 0, 83, 0, 1, 0, 1,
ax_anim 2, 0, 83, 0, 0, 0, 0,
ax_anim_terminator
sOmanyteAnims_4_4:
ax_anim 1, 0, 86, 0, -2, 0, 0,
ax_anim 2, 0, 86, 0, -4, 0, 0,
ax_anim 2, 0, 86, 0, -5, 0, 0,
ax_anim 2, 2, 84, 0, -5, 0, 0,
ax_anim 2, 0, 84, 0, -4, 0, 0,
ax_anim 1, 0, 84, 0, -2, 0, 0,
ax_anim 6, 0, 87, 0, 0, 0, 0,
ax_anim 2, 1, 87, -1, -1, -1, 1,
ax_anim 2, 0, 87, 0, 0, 0, 0,
ax_anim 2, 0, 87, -1, -1, -1, 1,
ax_anim 2, 0, 87, 0, 0, 0, 0,
ax_anim 2, 0, 87, -1, -1, -1, 1,
ax_anim 2, 0, 87, 0, 0, 0, 0,
ax_anim_terminator
sOmanyteAnims_4_5:
ax_anim 1, 0, 90, 0, -2, 0, 0,
ax_anim 2, 0, 90, 0, -4, 0, 0,
ax_anim 2, 0, 90, 0, -5, 0, 0,
ax_anim 2, 2, 88, 0, -5, 0, 0,
ax_anim 2, 0, 88, 0, -4, 0, 0,
ax_anim 1, 0, 88, 0, -2, 0, 0,
ax_anim 6, 0, 91, 0, 0, 0, 0,
ax_anim 2, 1, 91, -1, 0, 0, 0,
ax_anim 2, 0, 91, 0, 0, 0, 0,
ax_anim 2, 0, 91, -1, 0, 0, 0,
ax_anim 2, 0, 91, 0, 0, 0, 0,
ax_anim 2, 0, 91, -1, 0, 0, 0,
ax_anim 2, 0, 91, 0, 0, 0, 0,
ax_anim_terminator
sOmanyteAnims_4_6:
ax_anim 1, 0, 94, 0, -2, 0, 0,
ax_anim 2, 0, 94, 0, -4, 0, 0,
ax_anim 2, 0, 94, 0, -5, 0, 0,
ax_anim 2, 2, 92, 0, -5, 0, 0,
ax_anim 2, 0, 92, 0, -4, 0, 0,
ax_anim 1, 0, 92, 0, -2, 0, 0,
ax_anim 6, 0, 95, 0, 0, 0, 0,
ax_anim 2, 1, 95, 1, -1, 1, 1,
ax_anim 2, 0, 95, 0, 0, 0, 0,
ax_anim 2, 0, 95, 1, -1, 1, 1,
ax_anim 2, 0, 95, 0, 0, 0, 0,
ax_anim 2, 0, 95, 1, -1, 1, 1,
ax_anim 2, 0, 95, 0, 0, 0, 0,
ax_anim_terminator
sOmanyteAnims_4_7:
ax_anim 1, 0, 98, 0, -2, 0, 0,
ax_anim 2, 0, 98, 0, -4, 0, 0,
ax_anim 2, 0, 98, 0, -5, 0, 0,
ax_anim 2, 2, 96, 0, -5, 0, 0,
ax_anim 2, 0, 96, 0, -4, 0, 0,
ax_anim 1, 0, 96, 0, -2, 0, 0,
ax_anim 6, 0, 99, 0, 0, 0, 0,
ax_anim 2, 1, 99, 0, 1, 0, 1,
ax_anim 2, 0, 99, 0, 0, 0, 0,
ax_anim 2, 0, 99, 0, 1, 0, 1,
ax_anim 2, 0, 99, 0, 0, 0, 0,
ax_anim 2, 0, 99, 0, 1, 0, 1,
ax_anim 2, 0, 99, 0, 0, 0, 0,
ax_anim_terminator
sOmanyteAnims_4_8:
ax_anim 1, 0, 102, 0, -2, 0, 0,
ax_anim 2, 0, 102, 0, -4, 0, 0,
ax_anim 2, 0, 102, 0, -5, 0, 0,
ax_anim 2, 2, 100, 0, -5, 0, 0,
ax_anim 2, 0, 100, 0, -4, 0, 0,
ax_anim 1, 0, 100, 0, -2, 0, 0,
ax_anim 6, 0, 103, 0, 0, 0, 0,
ax_anim 2, 1, 103, 1, 1, 1, -1,
ax_anim 2, 0, 103, 0, 0, 0, 0,
ax_anim 2, 0, 103, 1, 1, 1, -1,
ax_anim 2, 0, 103, 0, 0, 0, 0,
ax_anim 2, 0, 103, 1, 1, 1, -1,
ax_anim 2, 0, 103, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sOmanyteAnims_5_1:
ax_anim 1, 0, 105, 0, 0, 0, 0,
ax_anim 2, 0, 105, 0, -3, 0, 0,
ax_anim 2, 0, 105, 0, -5, 0, 0,
ax_anim 2, 0, 105, 0, -6, 0, 0,
ax_anim 2, 0, 104, 0, -6, 0, 0,
ax_anim 2, 0, 104, 0, -5, 0, 0,
ax_anim 1, 0, 106, 0, -3, 0, 0,
ax_anim 6, 0, 106, 0, 0, 0, 0,
ax_anim 2, 0, 106, -1, 0, -1, 0,
ax_anim 2, 2, 106, 0, 0, 0, 0,
ax_anim 2, 0, 106, -1, 0, -1, 0,
ax_anim 2, 0, 106, 0, 0, 0, 0,
ax_anim 2, 0, 106, -1, 0, -1, 0,
ax_anim 2, 0, 106, 0, 0, 0, 0,
ax_anim_terminator
sOmanyteAnims_5_2:
ax_anim 1, 0, 108, 0, 0, 0, 0,
ax_anim 2, 0, 108, 0, -3, 0, 0,
ax_anim 2, 0, 108, 0, -5, 0, 0,
ax_anim 2, 0, 108, 0, -6, 0, 0,
ax_anim 2, 0, 107, 0, -6, 0, 0,
ax_anim 2, 0, 107, 0, -5, 0, 0,
ax_anim 1, 0, 109, 0, -3, 0, 0,
ax_anim 6, 0, 109, 0, 0, 0, 0,
ax_anim 2, 0, 109, -1, 1, -1, 1,
ax_anim 2, 2, 109, 0, 0, 0, 0,
ax_anim 2, 0, 109, -1, 1, -1, 1,
ax_anim 2, 0, 109, 0, 0, 0, 0,
ax_anim 2, 0, 109, -1, 1, -1, 1,
ax_anim 2, 0, 109, 0, 0, 0, 0,
ax_anim_terminator
sOmanyteAnims_5_3:
ax_anim 1, 0, 111, 0, 0, 0, 0,
ax_anim 2, 0, 111, 0, -3, 0, 0,
ax_anim 2, 0, 111, 0, -5, 0, 0,
ax_anim 2, 0, 111, 0, -6, 0, 0,
ax_anim 2, 0, 110, 0, -6, 0, 0,
ax_anim 2, 0, 110, 0, -5, 0, 0,
ax_anim 1, 0, 112, 0, -3, 0, 0,
ax_anim 6, 0, 112, 0, 0, 0, 0,
ax_anim 2, 0, 112, 0, 1, 0, 1,
ax_anim 2, 2, 112, 0, 0, 0, 0,
ax_anim 2, 0, 112, 0, 1, 0, 1,
ax_anim 2, 0, 112, 0, 0, 0, 0,
ax_anim 2, 0, 112, 0, 1, 0, 1,
ax_anim 2, 0, 112, 0, 0, 0, 0,
ax_anim_terminator
sOmanyteAnims_5_4:
ax_anim 1, 0, 114, 0, 0, 0, 0,
ax_anim 2, 0, 114, 0, -3, 0, 0,
ax_anim 2, 0, 114, 0, -5, 0, 0,
ax_anim 2, 0, 114, 0, -6, 0, 0,
ax_anim 2, 0, 113, 0, -6, 0, 0,
ax_anim 2, 0, 113, 0, -5, 0, 0,
ax_anim 1, 0, 115, 0, -3, 0, 0,
ax_anim 6, 0, 115, 0, 0, 0, 0,
ax_anim 2, 0, 115, -1, -1, -1, -1,
ax_anim 2, 2, 115, 0, 0, 0, 0,
ax_anim 2, 0, 115, -1, -1, -1, -1,
ax_anim 2, 0, 115, 0, 0, 0, 0,
ax_anim 2, 0, 115, -1, -1, -1, -1,
ax_anim 2, 0, 115, 0, 0, 0, 0,
ax_anim_terminator
sOmanyteAnims_5_5:
ax_anim 1, 0, 117, 0, 0, 0, 0,
ax_anim 2, 0, 117, 0, -3, 0, 0,
ax_anim 2, 0, 117, 0, -5, 0, 0,
ax_anim 2, 0, 117, 0, -6, 0, 0,
ax_anim 2, 0, 116, 0, -6, 0, 0,
ax_anim 2, 0, 116, 0, -5, 0, 0,
ax_anim 1, 0, 118, 0, -3, 0, 0,
ax_anim 6, 0, 118, 0, 0, 0, 0,
ax_anim 2, 0, 118, 1, 0, 1, 0,
ax_anim 2, 2, 118, 0, 0, 0, 0,
ax_anim 2, 0, 118, 1, 0, 1, 0,
ax_anim 2, 0, 118, 0, 0, 0, 0,
ax_anim 2, 0, 118, 1, 0, 1, 0,
ax_anim 2, 0, 118, 0, 0, 0, 0,
ax_anim_terminator
sOmanyteAnims_5_6:
ax_anim 1, 0, 120, 0, 0, 0, 0,
ax_anim 2, 0, 120, 0, -3, 0, 0,
ax_anim 2, 0, 120, 0, -5, 0, 0,
ax_anim 2, 0, 120, 0, -6, 0, 0,
ax_anim 2, 0, 119, 0, -6, 0, 0,
ax_anim 2, 0, 119, 0, -5, 0, 0,
ax_anim 1, 0, 121, 0, -3, 0, 0,
ax_anim 6, 0, 121, 0, 0, 0, 0,
ax_anim 2, 0, 121, 1, -1, 1, -1,
ax_anim 2, 2, 121, 0, 0, 0, 0,
ax_anim 2, 0, 121, 1, -1, 1, -1,
ax_anim 2, 0, 121, 0, 0, 0, 0,
ax_anim 2, 0, 121, 1, -1, 1, -1,
ax_anim 2, 0, 121, 0, 0, 0, 0,
ax_anim_terminator
sOmanyteAnims_5_7:
ax_anim 1, 0, 123, 0, 0, 0, 0,
ax_anim 2, 0, 123, 0, -3, 0, 0,
ax_anim 2, 0, 123, 0, -5, 0, 0,
ax_anim 2, 0, 123, 0, -6, 0, 0,
ax_anim 2, 0, 122, 0, -6, 0, 0,
ax_anim 2, 0, 122, 0, -5, 0, 0,
ax_anim 1, 0, 124, 0, -3, 0, 0,
ax_anim 6, 0, 124, 0, 0, 0, 0,
ax_anim 2, 0, 124, 0, 1, 0, 1,
ax_anim 2, 2, 124, 0, 0, 0, 0,
ax_anim 2, 0, 124, 0, 1, 0, 1,
ax_anim 2, 0, 124, 0, 0, 0, 0,
ax_anim 2, 0, 124, 0, 1, 0, 1,
ax_anim 2, 0, 124, 0, 0, 0, 0,
ax_anim_terminator
sOmanyteAnims_5_8:
ax_anim 1, 0, 126, 0, 0, 0, 0,
ax_anim 2, 0, 126, 0, -3, 0, 0,
ax_anim 2, 0, 126, 0, -5, 0, 0,
ax_anim 2, 0, 126, 0, -6, 0, 0,
ax_anim 2, 0, 125, 0, -6, 0, 0,
ax_anim 2, 0, 125, 0, -5, 0, 0,
ax_anim 1, 0, 127, 0, -3, 0, 0,
ax_anim 6, 0, 127, 0, 0, 0, 0,
ax_anim 2, 0, 127, 1, 1, 1, 1,
ax_anim 2, 2, 127, 0, 0, 0, 0,
ax_anim 2, 0, 127, 1, 1, 1, 1,
ax_anim 2, 0, 127, 0, 0, 0, 0,
ax_anim 2, 0, 127, 1, 1, 1, 1,
ax_anim 2, 0, 127, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sOmanyteAnims_6_1:
ax_anim 30, 0, 128, 0, 0, 0, 0,
ax_anim 35, 0, 129, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sOmanyteAnims_7_1:
ax_anim 2, 0, 130, 0, -2, 0, -2,
ax_anim 8, 0, 130, 0, -3, 0, -3,
ax_anim_terminator
sOmanyteAnims_7_2:
ax_anim 2, 0, 131, -2, -2, -2, -2,
ax_anim 8, 0, 131, -3, -3, -3, -3,
ax_anim_terminator
sOmanyteAnims_7_3:
ax_anim 2, 0, 132, -2, 0, -2, 0,
ax_anim 8, 0, 132, -3, 0, -3, 0,
ax_anim_terminator
sOmanyteAnims_7_4:
ax_anim 2, 0, 133, -2, 2, -2, 2,
ax_anim 8, 0, 133, -3, 3, -3, 3,
ax_anim_terminator
sOmanyteAnims_7_5:
ax_anim 2, 0, 134, 0, 2, 0, 2,
ax_anim 8, 0, 134, 0, 3, 0, 3,
ax_anim_terminator
sOmanyteAnims_7_6:
ax_anim 2, 0, 135, 2, 2, 2, 2,
ax_anim 8, 0, 135, 3, 3, 3, 3,
ax_anim_terminator
sOmanyteAnims_7_7:
ax_anim 2, 0, 136, 2, 0, 2, 0,
ax_anim 8, 0, 136, 3, 0, 3, 0,
ax_anim_terminator
sOmanyteAnims_7_8:
ax_anim 2, 0, 137, 2, -2, 2, -2,
ax_anim 8, 0, 137, 3, -3, 3, -3,
ax_anim_terminator
.align 2
sOmanyteAnims_8_1:
ax_anim 30, 0, 138, 0, 0, 0, 0,
ax_anim 12, 0, 140, 0, 0, 0, 0,
ax_anim_terminator
sOmanyteAnims_8_2:
ax_anim 30, 0, 141, 0, 0, 0, 0,
ax_anim 12, 0, 143, 0, 0, 0, 0,
ax_anim_terminator
sOmanyteAnims_8_3:
ax_anim 30, 0, 144, 0, 0, 0, 0,
ax_anim 12, 0, 145, 0, 0, 0, 0,
ax_anim_terminator
sOmanyteAnims_8_4:
ax_anim 30, 0, 147, 0, 0, 0, 0,
ax_anim 12, 0, 148, 0, 0, 0, 0,
ax_anim_terminator
sOmanyteAnims_8_5:
ax_anim 30, 0, 150, 0, 0, 0, 0,
ax_anim 12, 0, 151, 0, 0, 0, 0,
ax_anim_terminator
sOmanyteAnims_8_6:
ax_anim 30, 0, 153, 0, 0, 0, 0,
ax_anim 12, 0, 154, 0, 0, 0, 0,
ax_anim_terminator
sOmanyteAnims_8_7:
ax_anim 30, 0, 156, 0, 0, 0, 0,
ax_anim 12, 0, 157, 0, 0, 0, 0,
ax_anim_terminator
sOmanyteAnims_8_8:
ax_anim 30, 0, 159, 0, 0, 0, 0,
ax_anim 12, 0, 161, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sOmanyteAnims_9_1:
ax_anim 2, 0, 162, 0, 0, 0, 0,
ax_anim 2, 0, 163, 6, 3, 6, 3,
ax_anim 2, 0, 164, 8, 11, 8, 11,
ax_anim 2, 0, 165, 7, 19, 7, 19,
ax_anim 2, 0, 166, 0, 20, 0, 20,
ax_anim 2, 3, 167, -7, 19, -7, 19,
ax_anim 2, 0, 168, -8, 11, -8, 11,
ax_anim 2, 0, 169, -6, 3, -6, 3,
ax_anim 2, 0, 162, 0, 0, 0, 0,
ax_anim_terminator
sOmanyteAnims_9_2:
ax_anim 2, 0, 169, 0, 0, 0, 0,
ax_anim 2, 0, 162, 8, 0, 8, 0,
ax_anim 2, 0, 163, 17, 3, 17, 3,
ax_anim 2, 0, 164, 22, 12, 22, 12,
ax_anim 2, 0, 165, 22, 22, 22, 22,
ax_anim 2, 3, 166, 17, 23, 17, 23,
ax_anim 2, 0, 167, 6, 19, 6, 19,
ax_anim 2, 0, 168, 0, 7, 0, 7,
ax_anim 2, 0, 169, 0, 0, 0, 0,
ax_anim_terminator
sOmanyteAnims_9_3:
ax_anim 2, 0, 168, 0, 0, 0, 0,
ax_anim 2, 0, 169, 3, -5, 3, -5,
ax_anim 2, 0, 162, 11, -6, 11, -6,
ax_anim 2, 0, 163, 18, -5, 18, -5,
ax_anim 2, 0, 164, 22, 0, 22, 0,
ax_anim 2, 3, 165, 18, 6, 18, 6,
ax_anim 2, 0, 166, 12, 6, 12, 6,
ax_anim 2, 0, 167, 4, 5, 4, 5,
ax_anim 2, 0, 168, 0, 0, 0, 0,
ax_anim_terminator
sOmanyteAnims_9_4:
ax_anim 2, 0, 167, 0, 0, 0, 0,
ax_anim 2, 0, 168, 0, -8, 0, -8,
ax_anim 2, 0, 169, 4, -16, 4, -16,
ax_anim 2, 0, 162, 12, -22, 12, -22,
ax_anim 2, 0, 163, 23, -23, 23, -23,
ax_anim 2, 3, 164, 23, -14, 23, -14,
ax_anim 2, 0, 165, 18, -5, 18, -5,
ax_anim 2, 0, 166, 7, -1, 7, -1,
ax_anim 2, 0, 167, 0, 0, 0, 0,
ax_anim_terminator
sOmanyteAnims_9_5:
ax_anim 2, 0, 166, 0, 0, 0, 0,
ax_anim 2, 0, 167, -7, -3, -7, -3,
ax_anim 2, 0, 168, -9, -12, -9, -12,
ax_anim 2, 0, 169, -7, -18, -7, -18,
ax_anim 2, 0, 162, 0, -23, 0, -23,
ax_anim 2, 3, 163, 7, -18, 7, -18,
ax_anim 2, 0, 164, 9, -10, 9, -10,
ax_anim 2, 0, 165, 7, -3, 7, -3,
ax_anim 2, 0, 166, 0, 0, 0, 0,
ax_anim_terminator
sOmanyteAnims_9_6:
ax_anim 2, 0, 165, 0, 0, 0, 0,
ax_anim 2, 0, 164, 0, -8, 0, -8,
ax_anim 2, 0, 163, -4, -16, -4, -16,
ax_anim 2, 0, 162, -12, -22, -12, -22,
ax_anim 2, 0, 169, -23, -23, -23, -23,
ax_anim 2, 3, 168, -23, -14, -23, -14,
ax_anim 2, 0, 167, -18, -5, -18, -5,
ax_anim 2, 0, 166, -7, -1, -7, -1,
ax_anim 2, 0, 165, 0, 0, 0, 0,
ax_anim_terminator
sOmanyteAnims_9_7:
ax_anim 2, 0, 164, 0, 0, 0, 0,
ax_anim 2, 0, 163, -3, -5, -3, -5,
ax_anim 2, 0, 162, -11, -6, -11, -6,
ax_anim 2, 0, 169, -18, -5, -18, -5,
ax_anim 2, 0, 168, -22, 0, -22, 0,
ax_anim 2, 3, 167, -18, 6, -18, 6,
ax_anim 2, 0, 166, -12, 6, -12, 6,
ax_anim 2, 0, 165, -4, 5, -4, 5,
ax_anim 2, 0, 164, 0, 0, 0, 0,
ax_anim_terminator
sOmanyteAnims_9_8:
ax_anim 2, 0, 163, 0, 0, 0, 0,
ax_anim 2, 0, 162, -8, 0, -8, 0,
ax_anim 2, 0, 169, -17, 3, -17, 3,
ax_anim 2, 0, 168, -22, 12, -22, 12,
ax_anim 2, 0, 167, -22, 22, -22, 22,
ax_anim 2, 3, 166, -17, 23, -17, 23,
ax_anim 2, 0, 165, -6, 19, -6, 19,
ax_anim 2, 0, 164, 0, 7, 0, 7,
ax_anim 2, 0, 163, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sOmanyteAnims_10_1:
ax_anim 2, 0, 170, 0, 0, 0, 0,
ax_anim 2, 0, 170, 6, 0, 6, 0,
ax_anim 2, 0, 170, -6, 0, -6, 0,
ax_anim 2, 0, 170, 10, 0, 10, 0,
ax_anim 2, 0, 170, -10, 0, -10, 0,
ax_anim 2, 0, 170, 12, 0, 12, 0,
ax_anim 3, 0, 170, -12, 0, -12, 0,
ax_anim 3, 0, 170, 13, 0, 13, 0,
ax_anim 3, 0, 170, -13, 0, -13, 0,
ax_anim 2, 0, 170, 12, 0, 12, 0,
ax_anim 3, 0, 170, -12, 0, -12, 0,
ax_anim 2, 0, 170, 10, 0, 10, 0,
ax_anim 2, 0, 170, -10, 0, -10, 0,
ax_anim 2, 0, 170, 6, 0, 6, 0,
ax_anim 2, 0, 170, -6, 0, -6, 0,
ax_anim 2, 0, 170, 0, 0, 0, 0,
ax_anim_terminator
sOmanyteAnims_10_2:
ax_anim 2, 0, 171, 0, 0, 0, 0,
ax_anim 2, 0, 171, 6, -6, 6, -6,
ax_anim 2, 0, 171, -6, 6, -6, 6,
ax_anim 2, 0, 171, 10, -10, 10, -10,
ax_anim 2, 0, 171, -10, 10, -10, 10,
ax_anim 2, 0, 171, 12, -12, 12, -12,
ax_anim 3, 0, 171, -12, 12, -12, 12,
ax_anim 3, 0, 171, 13, -13, 13, -13,
ax_anim 3, 0, 171, -13, 13, -13, 13,
ax_anim 2, 0, 171, 12, -12, 12, -12,
ax_anim 3, 0, 171, -12, 12, -12, 12,
ax_anim 2, 0, 171, 10, -10, 10, -10,
ax_anim 2, 0, 171, -10, 10, -10, 10,
ax_anim 2, 0, 171, 6, -6, 6, -6,
ax_anim 2, 0, 171, -6, 6, -6, 6,
ax_anim 2, 0, 171, 0, 0, 0, 0,
ax_anim_terminator
sOmanyteAnims_10_3:
ax_anim 2, 0, 172, 0, 0, 0, 0,
ax_anim 2, 0, 172, 0, -6, 0, -6,
ax_anim 2, 0, 172, 0, 6, 0, 6,
ax_anim 2, 0, 172, 0, -10, 0, -10,
ax_anim 2, 0, 172, 0, 10, 0, 10,
ax_anim 2, 0, 172, 0, -12, 0, -12,
ax_anim 3, 0, 172, 0, 12, 0, 12,
ax_anim 3, 0, 172, 0, -13, 0, -13,
ax_anim 3, 0, 172, 0, 13, 0, 13,
ax_anim 2, 0, 172, 0, -12, 0, -12,
ax_anim 3, 0, 172, 0, 12, 0, 12,
ax_anim 2, 0, 172, 0, -10, 0, -10,
ax_anim 2, 0, 172, 0, 10, 0, 10,
ax_anim 2, 0, 172, 0, -6, 0, -6,
ax_anim 2, 0, 172, 0, 6, 0, 6,
ax_anim 2, 0, 172, 0, 0, 0, 0,
ax_anim_terminator
sOmanyteAnims_10_4:
ax_anim 2, 0, 173, 0, 0, 0, 0,
ax_anim 2, 0, 173, -6, -6, -6, -6,
ax_anim 2, 0, 173, 6, 6, 6, 6,
ax_anim 2, 0, 173, -10, -10, -10, -10,
ax_anim 2, 0, 173, 10, 10, 10, 10,
ax_anim 2, 0, 173, -12, -12, -12, -12,
ax_anim 3, 0, 173, 12, 12, 12, 12,
ax_anim 3, 0, 173, -13, -13, -13, -13,
ax_anim 3, 0, 173, 13, 13, 13, 13,
ax_anim 2, 0, 173, -12, -12, -12, -12,
ax_anim 3, 0, 173, 12, 12, 12, 12,
ax_anim 2, 0, 173, -10, -10, -10, -10,
ax_anim 2, 0, 173, 10, 10, 10, 10,
ax_anim 2, 0, 173, -6, -6, -6, -6,
ax_anim 2, 0, 173, 6, 6, 6, 6,
ax_anim 2, 0, 173, 0, 0, 0, 0,
ax_anim_terminator
sOmanyteAnims_10_5:
ax_anim 2, 0, 174, 0, 0, 0, 0,
ax_anim 2, 0, 174, 6, 0, 6, 0,
ax_anim 2, 0, 174, -6, 0, -6, 0,
ax_anim 2, 0, 174, 10, 0, 10, 0,
ax_anim 2, 0, 174, -10, 0, -10, 0,
ax_anim 2, 0, 174, 12, 0, 12, 0,
ax_anim 3, 0, 174, -12, 0, -12, 0,
ax_anim 3, 0, 174, 13, 0, 13, 0,
ax_anim 3, 0, 174, -13, 0, -13, 0,
ax_anim 2, 0, 174, 12, 0, 12, 0,
ax_anim 3, 0, 174, -12, 0, -12, 0,
ax_anim 2, 0, 174, 10, 0, 10, 0,
ax_anim 2, 0, 174, -10, 0, -10, 0,
ax_anim 2, 0, 174, 6, 0, 6, 0,
ax_anim 2, 0, 174, -6, 0, -6, 0,
ax_anim 2, 0, 174, 0, 0, 0, 0,
ax_anim_terminator
sOmanyteAnims_10_6:
ax_anim 2, 0, 175, 0, 0, 0, 0,
ax_anim 2, 0, 175, 6, -6, 6, -6,
ax_anim 2, 0, 175, -6, 6, -6, 6,
ax_anim 2, 0, 175, 10, -10, 10, -10,
ax_anim 2, 0, 175, -10, 10, -10, 10,
ax_anim 2, 0, 175, 12, -12, 12, -12,
ax_anim 3, 0, 175, -12, 12, -12, 12,
ax_anim 3, 0, 175, 13, -13, 13, -13,
ax_anim 3, 0, 175, -13, 13, -13, 13,
ax_anim 2, 0, 175, 12, -12, 12, -12,
ax_anim 3, 0, 175, -12, 12, -12, 12,
ax_anim 2, 0, 175, 10, -10, 10, -10,
ax_anim 2, 0, 175, -10, 10, -10, 10,
ax_anim 2, 0, 175, 6, -6, 6, -6,
ax_anim 2, 0, 175, -6, 6, -6, 6,
ax_anim 2, 0, 175, 0, 0, 0, 0,
ax_anim_terminator
sOmanyteAnims_10_7:
ax_anim 2, 0, 176, 0, 0, 0, 0,
ax_anim 2, 0, 176, 0, -6, 0, -6,
ax_anim 2, 0, 176, 0, 6, 0, 6,
ax_anim 2, 0, 176, 0, -10, 0, -10,
ax_anim 2, 0, 176, 0, 10, 0, 10,
ax_anim 2, 0, 176, 0, -12, 0, -12,
ax_anim 3, 0, 176, 0, 12, 0, 12,
ax_anim 3, 0, 176, 0, -13, 0, -13,
ax_anim 3, 0, 176, 0, 13, 0, 13,
ax_anim 2, 0, 176, 0, -12, 0, -12,
ax_anim 3, 0, 176, 0, 12, 0, 12,
ax_anim 2, 0, 176, 0, -10, 0, -10,
ax_anim 2, 0, 176, 0, 10, 0, 10,
ax_anim 2, 0, 176, 0, -6, 0, -6,
ax_anim 2, 0, 176, 0, 6, 0, 6,
ax_anim 2, 0, 176, 0, 0, 0, 0,
ax_anim_terminator
sOmanyteAnims_10_8:
ax_anim 2, 0, 177, 0, 0, 0, 0,
ax_anim 2, 0, 177, -6, -6, -6, -6,
ax_anim 2, 0, 177, 6, 6, 6, 6,
ax_anim 2, 0, 177, -10, -10, -10, -10,
ax_anim 2, 0, 177, 10, 10, 10, 10,
ax_anim 2, 0, 177, -12, -12, -12, -12,
ax_anim 3, 0, 177, 12, 12, 12, 12,
ax_anim 3, 0, 177, -13, -13, -13, -13,
ax_anim 3, 0, 177, 13, 13, 13, 13,
ax_anim 2, 0, 177, -12, -12, -12, -12,
ax_anim 3, 0, 177, 12, 12, 12, 12,
ax_anim 2, 0, 177, -10, -10, -10, -10,
ax_anim 2, 0, 177, 10, 10, 10, 10,
ax_anim 2, 0, 177, -6, -6, -6, -6,
ax_anim 2, 0, 177, 6, 6, 6, 6,
ax_anim 2, 0, 177, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sOmanyteAnims_11_1:
ax_anim 2, 0, 178, 0, 0, 0, 0,
ax_anim 1, 0, 179, 0, -10, 0, 0,
ax_anim 2, 0, 179, 0, -16, 0, 0,
ax_anim 3, 0, 179, 0, -20, 0, 0,
ax_anim 4, 0, 179, 0, -21, 0, 0,
ax_anim 4, 0, 178, 0, -23, 0, 0,
ax_anim 3, 0, 180, 0, -22, 0, 0,
ax_anim 2, 0, 180, 0, -18, 0, 0,
ax_anim 1, 0, 180, 0, -12, 0, 0,
ax_anim 2, 2, 178, 0, 0, 0, 0,
ax_anim_terminator
sOmanyteAnims_11_2:
ax_anim 2, 0, 181, 0, 0, 0, 0,
ax_anim 1, 0, 182, 0, -10, 0, 0,
ax_anim 2, 0, 182, 0, -16, 0, 0,
ax_anim 3, 0, 182, 0, -20, 0, 0,
ax_anim 4, 0, 182, 0, -21, 0, 0,
ax_anim 4, 0, 181, 0, -23, 0, 0,
ax_anim 3, 0, 183, 0, -22, 0, 0,
ax_anim 2, 0, 183, 0, -18, 0, 0,
ax_anim 1, 0, 183, 0, -12, 0, 0,
ax_anim 2, 2, 181, 0, 0, 0, 0,
ax_anim_terminator
sOmanyteAnims_11_3:
ax_anim 2, 0, 184, 0, 0, 0, 0,
ax_anim 1, 0, 185, 0, -10, 0, 0,
ax_anim 2, 0, 185, 0, -16, 0, 0,
ax_anim 3, 0, 185, 0, -20, 0, 0,
ax_anim 4, 0, 185, 0, -21, 0, 0,
ax_anim 4, 0, 184, 0, -23, 0, 0,
ax_anim 3, 0, 186, 0, -22, 0, 0,
ax_anim 2, 0, 186, 0, -18, 0, 0,
ax_anim 1, 0, 186, 0, -12, 0, 0,
ax_anim 2, 2, 184, 0, 0, 0, 0,
ax_anim_terminator
sOmanyteAnims_11_4:
ax_anim 2, 0, 188, 0, 0, 0, 0,
ax_anim 1, 0, 189, 0, -10, 0, 0,
ax_anim 2, 0, 189, 0, -16, 0, 0,
ax_anim 3, 0, 189, 0, -20, 0, 0,
ax_anim 4, 0, 189, 0, -21, 0, 0,
ax_anim 4, 0, 188, 0, -22, 0, 0,
ax_anim 3, 0, 190, 0, -21, 0, 0,
ax_anim 2, 0, 190, 0, -17, 0, 0,
ax_anim 1, 0, 190, 0, -11, 0, 0,
ax_anim 2, 2, 188, 0, 0, 0, 0,
ax_anim_terminator
sOmanyteAnims_11_5:
ax_anim 2, 0, 191, 0, 0, 0, 0,
ax_anim 1, 0, 192, 0, -10, 0, 0,
ax_anim 2, 0, 192, 0, -16, 0, 0,
ax_anim 3, 0, 192, 0, -20, 0, 0,
ax_anim 4, 0, 192, 0, -21, 0, 0,
ax_anim 4, 0, 191, 0, -23, 0, 0,
ax_anim 3, 0, 193, 0, -22, 0, 0,
ax_anim 2, 0, 193, 0, -18, 0, 0,
ax_anim 1, 0, 193, 0, -12, 0, 0,
ax_anim 2, 2, 191, 0, 0, 0, 0,
ax_anim_terminator
sOmanyteAnims_11_6:
ax_anim 2, 0, 194, 0, 0, 0, 0,
ax_anim 1, 0, 195, 0, -10, 0, 0,
ax_anim 2, 0, 195, 0, -16, 0, 0,
ax_anim 3, 0, 195, 0, -20, 0, 0,
ax_anim 4, 0, 195, 0, -21, 0, 0,
ax_anim 4, 0, 194, 0, -22, 0, 0,
ax_anim 3, 0, 196, 0, -21, 0, 0,
ax_anim 2, 0, 196, 0, -17, 0, 0,
ax_anim 1, 0, 196, 0, -11, 0, 0,
ax_anim 2, 2, 194, 0, 0, 0, 0,
ax_anim_terminator
sOmanyteAnims_11_7:
ax_anim 2, 0, 197, 0, 0, 0, 0,
ax_anim 1, 0, 198, 0, -10, 0, 0,
ax_anim 2, 0, 198, 0, -16, 0, 0,
ax_anim 3, 0, 198, 0, -20, 0, 0,
ax_anim 4, 0, 198, 0, -21, 0, 0,
ax_anim 4, 0, 197, 0, -23, 0, 0,
ax_anim 3, 0, 199, 0, -22, 0, 0,
ax_anim 2, 0, 199, 0, -18, 0, 0,
ax_anim 1, 0, 199, 0, -12, 0, 0,
ax_anim 2, 2, 197, 0, 0, 0, 0,
ax_anim_terminator
sOmanyteAnims_11_8:
ax_anim 2, 0, 200, 0, 0, 0, 0,
ax_anim 1, 0, 201, 0, -10, 0, 0,
ax_anim 2, 0, 201, 0, -16, 0, 0,
ax_anim 3, 0, 201, 0, -20, 0, 0,
ax_anim 4, 0, 201, 0, -21, 0, 0,
ax_anim 4, 0, 200, 0, -23, 0, 0,
ax_anim 3, 0, 202, 0, -22, 0, 0,
ax_anim 2, 0, 202, 0, -18, 0, 0,
ax_anim 1, 0, 202, 0, -12, 0, 0,
ax_anim 2, 2, 200, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sOmanyteAnims_12_1:
ax_anim 2, 0, 203, 1, 0, 1, 0,
ax_anim 2, 0, 203, 0, 0, 0, 0,
ax_anim 2, 0, 203, 1, 0, 1, 0,
ax_anim 2, 0, 203, 0, 0, 0, 0,
ax_anim 2, 0, 203, 1, 0, 1, 0,
ax_anim 2, 2, 203, 0, 0, 0, 0,
ax_anim 2, 0, 203, 1, 0, 1, 0,
ax_anim 2, 0, 203, 0, 0, 0, 0,
ax_anim 2, 0, 203, 1, 0, 1, 0,
ax_anim 2, 1, 203, 0, 0, 0, 0,
ax_anim_terminator
sOmanyteAnims_12_2:
ax_anim 2, 0, 210, 1, -1, 1, -1,
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 2, 0, 210, 1, -1, 1, -1,
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 2, 0, 210, 1, -1, 1, -1,
ax_anim 2, 2, 210, 0, 0, 0, 0,
ax_anim 2, 0, 210, 1, -1, 1, -1,
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 2, 0, 210, 1, -1, 1, -1,
ax_anim 2, 1, 210, 0, 0, 0, 0,
ax_anim_terminator
sOmanyteAnims_12_3:
ax_anim 2, 0, 209, 0, -1, 0, -1,
ax_anim 2, 0, 209, 0, 0, 0, 0,
ax_anim 2, 0, 209, 0, -1, 0, -1,
ax_anim 2, 0, 209, 0, 0, 0, 0,
ax_anim 2, 0, 209, 0, -1, 0, -1,
ax_anim 2, 2, 209, 0, 0, 0, 0,
ax_anim 2, 0, 209, 0, -1, 0, -1,
ax_anim 2, 0, 209, 0, 0, 0, 0,
ax_anim 2, 0, 209, 0, -1, 0, -1,
ax_anim 2, 1, 209, 0, 0, 0, 0,
ax_anim_terminator
sOmanyteAnims_12_4:
ax_anim 2, 0, 208, -1, -1, -1, -1,
ax_anim 2, 0, 208, 0, 0, 0, 0,
ax_anim 2, 0, 208, -1, -1, -1, -1,
ax_anim 2, 0, 208, 0, 0, 0, 0,
ax_anim 2, 0, 208, -1, -1, -1, -1,
ax_anim 2, 2, 208, 0, 0, 0, 0,
ax_anim 2, 0, 208, -1, -1, -1, -1,
ax_anim 2, 0, 208, 0, 0, 0, 0,
ax_anim 2, 0, 208, -1, -1, -1, -1,
ax_anim 2, 1, 208, 0, 0, 0, 0,
ax_anim_terminator
sOmanyteAnims_12_5:
ax_anim 2, 0, 207, 1, 0, 1, 0,
ax_anim 2, 0, 207, 0, 0, 0, 0,
ax_anim 2, 0, 207, 1, 0, 1, 0,
ax_anim 2, 0, 207, 0, 0, 0, 0,
ax_anim 2, 0, 207, 1, 0, 1, 0,
ax_anim 2, 2, 207, 0, 0, 0, 0,
ax_anim 2, 0, 207, 1, 0, 1, 0,
ax_anim 2, 0, 207, 0, 0, 0, 0,
ax_anim 2, 0, 207, 1, 0, 1, 0,
ax_anim 2, 1, 207, 0, 0, 0, 0,
ax_anim_terminator
sOmanyteAnims_12_6:
ax_anim 2, 0, 206, 1, -1, 1, -1,
ax_anim 2, 0, 206, 0, 0, 0, 0,
ax_anim 2, 0, 206, 1, -1, 1, -1,
ax_anim 2, 0, 206, 0, 0, 0, 0,
ax_anim 2, 0, 206, 1, -1, 1, -1,
ax_anim 2, 2, 206, 0, 0, 0, 0,
ax_anim 2, 0, 206, 1, -1, 1, -1,
ax_anim 2, 0, 206, 0, 0, 0, 0,
ax_anim 2, 0, 206, 1, -1, 1, -1,
ax_anim 2, 1, 206, 0, 0, 0, 0,
ax_anim_terminator
sOmanyteAnims_12_7:
ax_anim 2, 0, 205, 0, -1, 0, -1,
ax_anim 2, 0, 205, 0, 0, 0, 0,
ax_anim 2, 0, 205, 0, -1, 0, -1,
ax_anim 2, 0, 205, 0, 0, 0, 0,
ax_anim 2, 0, 205, 0, -1, 0, -1,
ax_anim 2, 2, 205, 0, 0, 0, 0,
ax_anim 2, 0, 205, 0, -1, 0, -1,
ax_anim 2, 0, 205, 0, 0, 0, 0,
ax_anim 2, 0, 205, 0, -1, 0, -1,
ax_anim 2, 1, 205, 0, 0, 0, 0,
ax_anim_terminator
sOmanyteAnims_12_8:
ax_anim 2, 0, 204, -1, -1, -1, -1,
ax_anim 2, 0, 204, 0, 0, 0, 0,
ax_anim 2, 0, 204, -1, -1, -1, -1,
ax_anim 2, 0, 204, 0, 0, 0, 0,
ax_anim 2, 0, 204, -1, -1, -1, -1,
ax_anim 2, 2, 204, 0, 0, 0, 0,
ax_anim 2, 0, 204, -1, -1, -1, -1,
ax_anim 2, 0, 204, 0, 0, 0, 0,
ax_anim 2, 0, 204, -1, -1, -1, -1,
ax_anim 2, 1, 204, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sOmanyteAnims_13_1:
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 2, 211, 0, 0, 0, 0,
ax_anim_terminator
sOmanyteAnims_13_2:
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 2, 218, 0, 0, 0, 0,
ax_anim_terminator
sOmanyteAnims_13_3:
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 2, 217, 0, 0, 0, 0,
ax_anim_terminator
sOmanyteAnims_13_4:
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 2, 216, 0, 0, 0, 0,
ax_anim_terminator
sOmanyteAnims_13_5:
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 2, 2, 215, 0, 0, 0, 0,
ax_anim_terminator
sOmanyteAnims_13_6:
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 2, 2, 214, 0, 0, 0, 0,
ax_anim_terminator
sOmanyteAnims_13_7:
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 2, 2, 213, 0, 0, 0, 0,
ax_anim_terminator
sOmanyteAnims_13_8:
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 2, 2, 212, 0, 0, 0, 0,
ax_anim_terminator
sOmanyteGfx1:
.incbin "baserom.gba", 0xAF7024, 0x20
sOmanyteSprites1:
ax_sprite sOmanyteGfx1, 0x20
ax_sprite_terminator
sOmanyteGfx2:
.incbin "baserom.gba", 0xAF7054, 0x100
sOmanyteSprites2:
ax_sprite sOmanyteGfx2, 0x100
ax_sprite_terminator
sOmanyteGfx3:
.incbin "baserom.gba", 0xAF7164, 0x100
sOmanyteSprites3:
ax_sprite sOmanyteGfx3, 0x100
ax_sprite_terminator
sOmanyteGfx4:
.incbin "baserom.gba", 0xAF7274, 0x100
sOmanyteSprites4:
ax_sprite sOmanyteGfx4, 0x100
ax_sprite_terminator
sOmanyteGfx5:
.incbin "baserom.gba", 0xAF7384, 0x200
sOmanyteSprites5:
ax_sprite sOmanyteGfx5, 0x200
ax_sprite_terminator
sOmanyteGfx6:
.incbin "baserom.gba", 0xAF7594, 0x200
sOmanyteSprites6:
ax_sprite sOmanyteGfx6, 0x200
ax_sprite_terminator
sOmanyteGfx7:
.incbin "baserom.gba", 0xAF77A4, 0x200
sOmanyteSprites7:
ax_sprite sOmanyteGfx7, 0x200
ax_sprite_terminator
sOmanyteGfx8:
.incbin "baserom.gba", 0xAF79B4, 0x200
sOmanyteSprites8:
ax_sprite sOmanyteGfx8, 0x200
ax_sprite_terminator
sOmanyteGfx9:
.incbin "baserom.gba", 0xAF7BC4, 0x200
sOmanyteSprites9:
ax_sprite sOmanyteGfx9, 0x200
ax_sprite_terminator
sOmanyteGfx10:
.incbin "baserom.gba", 0xAF7DD4, 0x200
sOmanyteSprites10:
ax_sprite sOmanyteGfx10, 0x200
ax_sprite_terminator
sOmanyteGfx11:
.incbin "baserom.gba", 0xAF7FE4, 0x200
sOmanyteSprites11:
ax_sprite sOmanyteGfx11, 0x200
ax_sprite_terminator
sOmanyteGfx12:
.incbin "baserom.gba", 0xAF81F4, 0x200
sOmanyteSprites12:
ax_sprite sOmanyteGfx12, 0x200
ax_sprite_terminator
sOmanyteGfx13:
.incbin "baserom.gba", 0xAF8404, 0x200
sOmanyteSprites13:
ax_sprite sOmanyteGfx13, 0x200
ax_sprite_terminator
sOmanyteGfx14:
.incbin "baserom.gba", 0xAF8614, 0x200
sOmanyteSprites14:
ax_sprite sOmanyteGfx14, 0x200
ax_sprite_terminator
sOmanyteGfx15:
.incbin "baserom.gba", 0xAF8824, 0x100
sOmanyteSprites15:
ax_sprite sOmanyteGfx15, 0x100
ax_sprite_terminator
sOmanyteGfx16:
.incbin "baserom.gba", 0xAF8934, 0x200
sOmanyteSprites16:
ax_sprite sOmanyteGfx16, 0x200
ax_sprite_terminator
sOmanyteGfx17:
.incbin "baserom.gba", 0xAF8B44, 0xC0
sOmanyteSprites17:
ax_sprite sOmanyteGfx17, 0xc0
ax_sprite 0, 0x40
ax_sprite_terminator
sOmanyteGfx18:
.incbin "baserom.gba", 0xAF8C1C, 0x60
sOmanyteGfx18_1:
.incbin "baserom.gba", 0xAF8C7C, 0x60
sOmanyteGfx18_2:
.incbin "baserom.gba", 0xAF8CDC, 0x40
sOmanyteSprites18:
ax_sprite sOmanyteGfx18, 0x60
ax_sprite 0, 0x20
ax_sprite sOmanyteGfx18_1, 0x60
ax_sprite 0, 0x40
ax_sprite sOmanyteGfx18_2, 0x40
ax_sprite 0, 0xa0
ax_sprite_terminator
sOmanyteGfx19:
.incbin "baserom.gba", 0xAF8D54, 0x100
sOmanyteGfx19_1:
.incbin "baserom.gba", 0xAF8E54, 0x40
sOmanyteSprites19:
ax_sprite sOmanyteGfx19, 0x100
ax_sprite 0, 0x20
ax_sprite sOmanyteGfx19_1, 0x40
ax_sprite 0, 0xa0
ax_sprite_terminator
sOmanyteGfx20:
.incbin "baserom.gba", 0xAF8EBC, 0x60
sOmanyteGfx20_1:
.incbin "baserom.gba", 0xAF8F1C, 0x60
sOmanyteGfx20_2:
.incbin "baserom.gba", 0xAF8F7C, 0x40
sOmanyteSprites20:
ax_sprite sOmanyteGfx20, 0x60
ax_sprite 0, 0x20
ax_sprite sOmanyteGfx20_1, 0x60
ax_sprite 0, 0x40
ax_sprite sOmanyteGfx20_2, 0x40
ax_sprite 0, 0xa0
ax_sprite_terminator
sOmanyteGfx21:
.incbin "baserom.gba", 0xAF8FF4, 0x60
sOmanyteGfx21_1:
.incbin "baserom.gba", 0xAF9054, 0x60
sOmanyteGfx21_2:
.incbin "baserom.gba", 0xAF90B4, 0x40
sOmanyteSprites21:
ax_sprite sOmanyteGfx21, 0x60
ax_sprite 0, 0x20
ax_sprite sOmanyteGfx21_1, 0x60
ax_sprite 0, 0x40
ax_sprite sOmanyteGfx21_2, 0x40
ax_sprite 0, 0xa0
ax_sprite_terminator
sOmanyteGfx22:
.incbin "baserom.gba", 0xAF912C, 0x100
sOmanyteSprites22:
ax_sprite sOmanyteGfx22, 0x100
ax_sprite_terminator
sOmanyteGfx23:
.incbin "baserom.gba", 0xAF923C, 0xC0
sOmanyteSprites23:
ax_sprite sOmanyteGfx23, 0xc0
ax_sprite 0, 0x40
ax_sprite_terminator
sOmanyteGfx24:
.incbin "baserom.gba", 0xAF9314, 0x60
sOmanyteGfx24_1:
.incbin "baserom.gba", 0xAF9374, 0x60
sOmanyteGfx24_2:
.incbin "baserom.gba", 0xAF93D4, 0x60
sOmanyteSprites24:
ax_sprite sOmanyteGfx24, 0x60
ax_sprite 0, 0x20
ax_sprite sOmanyteGfx24_1, 0x60
ax_sprite 0, 0x20
ax_sprite sOmanyteGfx24_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sOmanyteGfx25:
.incbin "baserom.gba", 0xAF946C, 0x40
sOmanyteGfx25_1:
.incbin "baserom.gba", 0xAF94AC, 0x60
sOmanyteGfx25_2:
.incbin "baserom.gba", 0xAF950C, 0x40
sOmanyteSprites25:
ax_sprite 0, 0x20
ax_sprite sOmanyteGfx25, 0x40
ax_sprite 0, 0x20
ax_sprite sOmanyteGfx25_1, 0x60
ax_sprite 0, 0x40
ax_sprite sOmanyteGfx25_2, 0x40
ax_sprite 0, 0xa0
ax_sprite_terminator
sOmanyteGfx26:
.incbin "baserom.gba", 0xAF958C, 0x60
sOmanyteGfx26_1:
.incbin "baserom.gba", 0xAF95EC, 0x60
sOmanyteGfx26_2:
.incbin "baserom.gba", 0xAF964C, 0x60
sOmanyteGfx26_3:
.incbin "baserom.gba", 0xAF96AC, 0x20
sOmanyteSprites26:
ax_sprite sOmanyteGfx26, 0x60
ax_sprite 0, 0x20
ax_sprite sOmanyteGfx26_1, 0x60
ax_sprite 0, 0x20
ax_sprite sOmanyteGfx26_2, 0x60
ax_sprite 0, 0x40
ax_sprite sOmanyteGfx26_3, 0x20
ax_sprite 0, 0x40
ax_sprite_terminator
sOmanyteGfx27:
.incbin "baserom.gba", 0xAF9714, 0x60
sOmanyteGfx27_1:
.incbin "baserom.gba", 0xAF9774, 0x60
sOmanyteGfx27_2:
.incbin "baserom.gba", 0xAF97D4, 0x40
sOmanyteSprites27:
ax_sprite sOmanyteGfx27, 0x60
ax_sprite 0, 0x20
ax_sprite sOmanyteGfx27_1, 0x60
ax_sprite 0, 0x40
ax_sprite sOmanyteGfx27_2, 0x40
ax_sprite 0, 0xa0
ax_sprite_terminator
sOmanyteGfx28:
.incbin "baserom.gba", 0xAF984C, 0x40
sOmanyteGfx28_1:
.incbin "baserom.gba", 0xAF988C, 0x60
sOmanyteGfx28_2:
.incbin "baserom.gba", 0xAF98EC, 0x60
sOmanyteSprites28:
ax_sprite 0, 0x20
ax_sprite sOmanyteGfx28, 0x40
ax_sprite 0, 0x20
ax_sprite sOmanyteGfx28_1, 0x60
ax_sprite 0, 0x20
ax_sprite sOmanyteGfx28_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sOmanyteGfx29:
.incbin "baserom.gba", 0xAF998C, 0x60
sOmanyteGfx29_1:
.incbin "baserom.gba", 0xAF99EC, 0x60
sOmanyteGfx29_2:
.incbin "baserom.gba", 0xAF9A4C, 0x40
sOmanyteSprites29:
ax_sprite sOmanyteGfx29, 0x60
ax_sprite 0, 0x20
ax_sprite sOmanyteGfx29_1, 0x60
ax_sprite 0, 0x40
ax_sprite sOmanyteGfx29_2, 0x40
ax_sprite 0, 0xa0
ax_sprite_terminator
sOmanyteGfx30:
.incbin "baserom.gba", 0xAF9AC4, 0x40
sOmanyteGfx30_1:
.incbin "baserom.gba", 0xAF9B04, 0x60
sOmanyteGfx30_2:
.incbin "baserom.gba", 0xAF9B64, 0x40
sOmanyteSprites30:
ax_sprite 0, 0x20
ax_sprite sOmanyteGfx30, 0x40
ax_sprite 0, 0x20
ax_sprite sOmanyteGfx30_1, 0x60
ax_sprite 0, 0x40
ax_sprite sOmanyteGfx30_2, 0x40
ax_sprite 0, 0xa0
ax_sprite_terminator
sOmanyteGfx31:
.incbin "baserom.gba", 0xAF9BE4, 0xC0
sOmanyteSprites31:
ax_sprite sOmanyteGfx31, 0xc0
ax_sprite 0, 0x40
ax_sprite_terminator
sOmanyteGfx32:
.incbin "baserom.gba", 0xAF9CBC, 0x200
sOmanyteSprites32:
ax_sprite sOmanyteGfx32, 0x200
ax_sprite_terminator
sOmanyteGfx33:
.incbin "baserom.gba", 0xAF9ECC, 0x200
sOmanyteSprites33:
ax_sprite sOmanyteGfx33, 0x200
ax_sprite_terminator
sOmanyteGfx34:
.incbin "baserom.gba", 0xAFA0DC, 0x200
sOmanyteSprites34:
ax_sprite sOmanyteGfx34, 0x200
ax_sprite_terminator
sOmanyteGfx35:
.incbin "baserom.gba", 0xAFA2EC, 0x200
sOmanyteSprites35:
ax_sprite sOmanyteGfx35, 0x200
ax_sprite_terminator
sOmanyteGfx36:
.incbin "baserom.gba", 0xAFA4FC, 0x200
sOmanyteSprites36:
ax_sprite sOmanyteGfx36, 0x200
ax_sprite_terminator
sOmanyteGfx37:
.incbin "baserom.gba", 0xAFA70C, 0x200
sOmanyteSprites37:
ax_sprite sOmanyteGfx37, 0x200
ax_sprite_terminator
sOmanyteGfx38:
.incbin "baserom.gba", 0xAFA91C, 0x200
sOmanyteSprites38:
ax_sprite sOmanyteGfx38, 0x200
ax_sprite_terminator
sAxPosesOmanyte:
.4byte sOmanytePose1
.4byte sOmanytePose2
.4byte sOmanytePose3
.4byte sOmanytePose4
.4byte sOmanytePose5
.4byte sOmanytePose6
.4byte sOmanytePose7
.4byte sOmanytePose8
.4byte sOmanytePose9
.4byte sOmanytePose10
.4byte sOmanytePose11
.4byte sOmanytePose12
.4byte sOmanytePose13
.4byte sOmanytePose14
.4byte sOmanytePose15
.4byte sOmanytePose16
.4byte sOmanytePose17
.4byte sOmanytePose18
.4byte sOmanytePose19
.4byte sOmanytePose20
.4byte sOmanytePose21
.4byte sOmanytePose22
.4byte sOmanytePose23
.4byte sOmanytePose24
.4byte sOmanytePose25
.4byte sOmanytePose26
.4byte sOmanytePose27
.4byte sOmanytePose28
.4byte sOmanytePose29
.4byte sOmanytePose30
.4byte sOmanytePose31
.4byte sOmanytePose32
.4byte sOmanytePose33
.4byte sOmanytePose34
.4byte sOmanytePose35
.4byte sOmanytePose36
.4byte sOmanytePose37
.4byte sOmanytePose38
.4byte sOmanytePose39
.4byte sOmanytePose40
.4byte sOmanytePose41
.4byte sOmanytePose42
.4byte sOmanytePose43
.4byte sOmanytePose44
.4byte sOmanytePose45
.4byte sOmanytePose46
.4byte sOmanytePose47
.4byte sOmanytePose48
.4byte sOmanytePose49
.4byte sOmanytePose50
.4byte sOmanytePose51
.4byte sOmanytePose52
.4byte sOmanytePose53
.4byte sOmanytePose54
.4byte sOmanytePose55
.4byte sOmanytePose56
.4byte sOmanytePose57
.4byte sOmanytePose58
.4byte sOmanytePose59
.4byte sOmanytePose60
.4byte sOmanytePose61
.4byte sOmanytePose62
.4byte sOmanytePose63
.4byte sOmanytePose64
.4byte sOmanytePose65
.4byte sOmanytePose66
.4byte sOmanytePose67
.4byte sOmanytePose68
.4byte sOmanytePose69
.4byte sOmanytePose70
.4byte sOmanytePose71
.4byte sOmanytePose72
.4byte sOmanytePose73
.4byte sOmanytePose74
.4byte sOmanytePose75
.4byte sOmanytePose76
.4byte sOmanytePose77
.4byte sOmanytePose78
.4byte sOmanytePose79
.4byte sOmanytePose80
.4byte sOmanytePose81
.4byte sOmanytePose82
.4byte sOmanytePose83
.4byte sOmanytePose84
.4byte sOmanytePose85
.4byte sOmanytePose86
.4byte sOmanytePose87
.4byte sOmanytePose88
.4byte sOmanytePose89
.4byte sOmanytePose90
.4byte sOmanytePose91
.4byte sOmanytePose92
.4byte sOmanytePose93
.4byte sOmanytePose94
.4byte sOmanytePose95
.4byte sOmanytePose96
.4byte sOmanytePose97
.4byte sOmanytePose98
.4byte sOmanytePose99
.4byte sOmanytePose100
.4byte sOmanytePose101
.4byte sOmanytePose102
.4byte sOmanytePose103
.4byte sOmanytePose104
.4byte sOmanytePose105
.4byte sOmanytePose106
.4byte sOmanytePose107
.4byte sOmanytePose108
.4byte sOmanytePose109
.4byte sOmanytePose110
.4byte sOmanytePose111
.4byte sOmanytePose112
.4byte sOmanytePose113
.4byte sOmanytePose114
.4byte sOmanytePose115
.4byte sOmanytePose116
.4byte sOmanytePose117
.4byte sOmanytePose118
.4byte sOmanytePose119
.4byte sOmanytePose120
.4byte sOmanytePose121
.4byte sOmanytePose122
.4byte sOmanytePose123
.4byte sOmanytePose124
.4byte sOmanytePose125
.4byte sOmanytePose126
.4byte sOmanytePose127
.4byte sOmanytePose128
.4byte sOmanytePose129
.4byte sOmanytePose130
.4byte sOmanytePose131
.4byte sOmanytePose132
.4byte sOmanytePose133
.4byte sOmanytePose134
.4byte sOmanytePose135
.4byte sOmanytePose136
.4byte sOmanytePose137
.4byte sOmanytePose138
.4byte sOmanytePose139
.4byte sOmanytePose140
.4byte sOmanytePose141
.4byte sOmanytePose142
.4byte sOmanytePose143
.4byte sOmanytePose144
.4byte sOmanytePose145
.4byte sOmanytePose146
.4byte sOmanytePose147
.4byte sOmanytePose148
.4byte sOmanytePose149
.4byte sOmanytePose150
.4byte sOmanytePose151
.4byte sOmanytePose152
.4byte sOmanytePose153
.4byte sOmanytePose154
.4byte sOmanytePose155
.4byte sOmanytePose156
.4byte sOmanytePose157
.4byte sOmanytePose158
.4byte sOmanytePose159
.4byte sOmanytePose160
.4byte sOmanytePose161
.4byte sOmanytePose162
.4byte sOmanytePose163
.4byte sOmanytePose164
.4byte sOmanytePose165
.4byte sOmanytePose166
.4byte sOmanytePose167
.4byte sOmanytePose168
.4byte sOmanytePose169
.4byte sOmanytePose170
.4byte sOmanytePose171
.4byte sOmanytePose172
.4byte sOmanytePose173
.4byte sOmanytePose174
.4byte sOmanytePose175
.4byte sOmanytePose176
.4byte sOmanytePose177
.4byte sOmanytePose178
.4byte sOmanytePose179
.4byte sOmanytePose180
.4byte sOmanytePose181
.4byte sOmanytePose182
.4byte sOmanytePose183
.4byte sOmanytePose184
.4byte sOmanytePose185
.4byte sOmanytePose186
.4byte sOmanytePose187
.4byte sOmanytePose188
.4byte sOmanytePose189
.4byte sOmanytePose190
.4byte sOmanytePose191
.4byte sOmanytePose192
.4byte sOmanytePose193
.4byte sOmanytePose194
.4byte sOmanytePose195
.4byte sOmanytePose196
.4byte sOmanytePose197
.4byte sOmanytePose198
.4byte sOmanytePose199
.4byte sOmanytePose200
.4byte sOmanytePose201
.4byte sOmanytePose202
.4byte sOmanytePose203
.4byte sOmanytePose204
.4byte sOmanytePose205
.4byte sOmanytePose206
.4byte sOmanytePose207
.4byte sOmanytePose208
.4byte sOmanytePose209
.4byte sOmanytePose210
.4byte sOmanytePose211
.4byte sOmanytePose212
.4byte sOmanytePose213
.4byte sOmanytePose214
.4byte sOmanytePose215
.4byte sOmanytePose216
.4byte sOmanytePose217
.4byte sOmanytePose218
.4byte sOmanytePose219
sAxPositionsOmanyte:
.2byte    0,    0, 	  -7,   -3, 	   7,   -3, 	   0,   -9
.2byte    0,    2, 	  -6,    3, 	   6,    3, 	   0,   -8
.2byte    0,   -1, 	  -6,   -4, 	   6,   -4, 	   0,  -10
.2byte    6,   -1, 	   9,   -6, 	  -2,   -2, 	  -1,   -8
.2byte    7,   -1, 	  12,   -2, 	   1,    2, 	   1,   -8
.2byte    5,   -3, 	   8,   -7, 	  -2,   -4, 	  -1,   -8
.2byte    8,   -3, 	   8,   -7, 	   4,   -4, 	  -1,   -7
.2byte    9,   -3, 	  12,   -4, 	   8,   -1, 	   0,   -7
.2byte    7,   -3, 	   6,   -8, 	   2,   -4, 	  -3,   -7
.2byte    5,   -6, 	   4,  -11, 	   9,   -9, 	   0,   -8
.2byte    6,   -7, 	   4,   -7, 	  11,   -6, 	   1,   -9
.2byte    4,   -7, 	   3,  -11, 	   8,   -9, 	  -1,   -8
.2byte   -1,   -8, 	   6,  -11, 	  -8,  -11, 	  -1,   -7
.2byte   -1,   -7, 	   5,  -10, 	  -7,  -10, 	  -1,   -8
.2byte   -1,   -7, 	   6,  -10, 	  -8,  -10, 	  -1,   -8
.2byte   -6,   -6, 	  -5,  -11, 	 -10,   -9, 	  -1,   -8
.2byte   -7,   -7, 	  -5,   -7, 	 -12,   -6, 	  -2,   -9
.2byte   -5,   -7, 	  -4,  -11, 	  -9,   -9, 	   0,   -8
.2byte   -9,   -3, 	  -9,   -7, 	  -5,   -4, 	   0,   -7
.2byte  -10,   -3, 	 -13,   -4, 	  -9,   -1, 	  -1,   -7
.2byte   -8,   -3, 	  -7,   -8, 	  -3,   -4, 	   2,   -7
.2byte   -7,   -1, 	 -10,   -6, 	   1,   -2, 	   0,   -8
.2byte   -8,   -1, 	 -13,   -2, 	  -2,    2, 	  -2,   -8
.2byte   -6,   -3, 	  -9,   -7, 	   1,   -4, 	   0,   -8
.2byte    0,    0, 	  -7,   -3, 	   7,   -3, 	   0,   -9
.2byte    0,    2, 	  -6,    3, 	   6,    3, 	   0,   -8
.2byte    0,   -1, 	  -6,   -4, 	   6,   -4, 	   0,  -10
.2byte    6,   -1, 	   9,   -6, 	  -2,   -2, 	  -1,   -8
.2byte    7,   -1, 	  12,   -2, 	   1,    2, 	   1,   -8
.2byte    5,   -3, 	   8,   -7, 	  -2,   -4, 	  -1,   -8
.2byte    8,   -3, 	   8,   -7, 	   4,   -4, 	  -1,   -7
.2byte    9,   -3, 	  12,   -4, 	   8,   -1, 	   0,   -7
.2byte    7,   -3, 	   6,   -8, 	   2,   -4, 	  -3,   -7
.2byte    5,   -6, 	   4,  -11, 	   9,   -9, 	   0,   -8
.2byte    6,   -7, 	   4,   -7, 	  11,   -6, 	   1,   -9
.2byte    4,   -7, 	   3,  -11, 	   8,   -9, 	  -1,   -8
.2byte   -1,   -8, 	   6,  -11, 	  -8,  -11, 	  -1,   -7
.2byte   -1,   -7, 	   5,  -10, 	  -7,  -10, 	  -1,   -8
.2byte   -1,   -7, 	   6,  -10, 	  -8,  -10, 	  -1,   -8
.2byte   -6,   -6, 	  -5,  -11, 	 -10,   -9, 	  -1,   -8
.2byte   -7,   -7, 	  -5,   -7, 	 -12,   -6, 	  -2,   -9
.2byte   -5,   -7, 	  -4,  -11, 	  -9,   -9, 	   0,   -8
.2byte   -9,   -3, 	  -9,   -7, 	  -5,   -4, 	   0,   -7
.2byte  -10,   -3, 	 -13,   -4, 	  -9,   -1, 	  -1,   -7
.2byte   -8,   -3, 	  -7,   -8, 	  -3,   -4, 	   2,   -7
.2byte   -7,   -1, 	 -10,   -6, 	   1,   -2, 	   0,   -8
.2byte   -8,   -1, 	 -13,   -2, 	  -2,    2, 	  -2,   -8
.2byte   -6,   -3, 	  -9,   -7, 	   1,   -4, 	   0,   -8
.2byte    0,    0, 	  -7,   -3, 	   7,   -3, 	   0,   -9
.2byte    0,    2, 	  -6,    3, 	   6,    3, 	   0,   -8
.2byte    0,   -1, 	  -6,   -4, 	   6,   -4, 	   0,  -10
.2byte    6,   -1, 	   9,   -6, 	  -2,   -2, 	  -1,   -8
.2byte    7,   -1, 	  12,   -2, 	   1,    2, 	   1,   -8
.2byte    5,   -3, 	   8,   -7, 	  -2,   -4, 	  -1,   -8
.2byte    8,   -3, 	   8,   -7, 	   4,   -4, 	  -1,   -7
.2byte    9,   -3, 	  12,   -4, 	   8,   -1, 	   0,   -7
.2byte    7,   -3, 	   6,   -8, 	   2,   -4, 	  -3,   -7
.2byte    5,   -6, 	   4,  -11, 	   9,   -9, 	   0,   -8
.2byte    6,   -7, 	   4,   -7, 	  11,   -6, 	   1,   -9
.2byte    4,   -7, 	   3,  -11, 	   8,   -9, 	  -1,   -8
.2byte   -1,   -8, 	   6,  -11, 	  -8,  -11, 	  -1,   -7
.2byte   -1,   -7, 	   5,  -10, 	  -7,  -10, 	  -1,   -8
.2byte   -1,   -7, 	   6,  -10, 	  -8,  -10, 	  -1,   -8
.2byte   -6,   -6, 	  -5,  -11, 	 -10,   -9, 	  -1,   -8
.2byte   -7,   -7, 	  -5,   -7, 	 -12,   -6, 	  -2,   -9
.2byte   -5,   -7, 	  -4,  -11, 	  -9,   -9, 	   0,   -8
.2byte   -9,   -3, 	  -9,   -7, 	  -5,   -4, 	   0,   -7
.2byte  -10,   -3, 	 -13,   -4, 	  -9,   -1, 	  -1,   -7
.2byte   -8,   -3, 	  -7,   -8, 	  -3,   -4, 	   2,   -7
.2byte   -7,   -1, 	 -10,   -6, 	   1,   -2, 	   0,   -8
.2byte   -8,   -1, 	 -13,   -2, 	  -2,    2, 	  -2,   -8
.2byte   -6,   -3, 	  -9,   -7, 	   1,   -4, 	   0,   -8
.2byte    0,    0, 	  -7,   -3, 	   7,   -3, 	   0,   -9
.2byte    0,    2, 	  -6,    3, 	   6,    3, 	   0,   -8
.2byte    0,   -1, 	  -6,   -4, 	   6,   -4, 	   0,  -10
.2byte    0,   -1, 	  -6,   -4, 	   6,   -4, 	   0,  -10
.2byte    6,   -1, 	   9,   -6, 	  -2,   -2, 	  -1,   -8
.2byte    7,   -1, 	  12,   -2, 	   1,    2, 	   1,   -8
.2byte    5,   -3, 	   8,   -7, 	  -2,   -4, 	  -1,   -8
.2byte    6,   -2, 	   8,   -7, 	  -2,   -3, 	  -2,   -8
.2byte    8,   -3, 	   8,   -7, 	   4,   -4, 	  -1,   -7
.2byte    8,   -3, 	  11,   -4, 	   7,   -1, 	  -1,   -7
.2byte    8,   -3, 	   7,   -8, 	   3,   -4, 	  -2,   -7
.2byte    8,   -6, 	   7,   -9, 	   2,   -6, 	  -3,   -6
.2byte    5,   -6, 	   4,  -11, 	   9,   -9, 	   0,   -8
.2byte    6,   -7, 	   4,   -7, 	  11,   -6, 	   1,   -9
.2byte    4,   -7, 	   3,  -11, 	   8,   -9, 	  -1,   -8
.2byte    5,   -9, 	   1,  -12, 	   6,  -11, 	  -1,   -7
.2byte   -1,   -8, 	   6,  -11, 	  -8,  -11, 	  -1,   -7
.2byte   -1,   -7, 	   5,  -10, 	  -7,  -10, 	  -1,   -8
.2byte   -1,   -7, 	   6,  -10, 	  -8,  -10, 	  -1,   -8
.2byte   -1,   -9, 	   6,  -12, 	  -8,  -12, 	  -1,   -8
.2byte   -6,   -6, 	  -5,  -11, 	 -10,   -9, 	  -1,   -8
.2byte   -7,   -7, 	  -5,   -7, 	 -12,   -6, 	  -2,   -9
.2byte   -5,   -7, 	  -4,  -11, 	  -9,   -9, 	   0,   -8
.2byte   -6,   -9, 	  -2,  -12, 	  -7,  -11, 	   0,   -7
.2byte   -9,   -3, 	  -9,   -7, 	  -5,   -4, 	   0,   -7
.2byte   -9,   -3, 	 -12,   -4, 	  -8,   -1, 	   0,   -7
.2byte   -9,   -3, 	  -8,   -8, 	  -4,   -4, 	   1,   -7
.2byte   -9,   -6, 	  -8,   -9, 	  -3,   -6, 	   2,   -6
.2byte   -7,   -1, 	 -10,   -6, 	   1,   -2, 	   0,   -8
.2byte   -8,   -1, 	 -13,   -2, 	  -2,    2, 	  -2,   -8
.2byte   -6,   -3, 	  -9,   -7, 	   1,   -4, 	   0,   -8
.2byte   -7,   -2, 	  -9,   -7, 	   1,   -3, 	   1,   -8
.2byte    0,    0, 	  -7,   -3, 	   7,   -3, 	   0,   -9
.2byte    0,    0, 	  -6,    0, 	   6,    0, 	   0,  -13
.2byte    0,   -2, 	  -4,   -2, 	   4,   -2, 	   0,  -10
.2byte    6,   -1, 	   9,   -6, 	  -2,   -2, 	  -1,   -8
.2byte    5,   -2, 	   8,   -2, 	  -2,   -3, 	  -1,  -12
.2byte    2,   -4, 	   5,   -4, 	  -1,   -3, 	  -1,   -9
.2byte    8,   -3, 	   8,   -7, 	   4,   -4, 	  -1,   -7
.2byte    7,   -2, 	   8,   -3, 	   4,    1, 	  -2,  -12
.2byte    4,   -4, 	   5,   -6, 	   4,   -3, 	  -2,   -8
.2byte    5,   -6, 	   4,  -11, 	   9,   -9, 	   0,   -8
.2byte    5,   -3, 	   3,   -2, 	   7,    0, 	   0,  -10
.2byte    3,   -6, 	   0,   -8, 	   4,   -5, 	  -1,   -8
.2byte   -1,   -8, 	   6,  -11, 	  -8,  -11, 	  -1,   -7
.2byte   -1,   -5, 	   6,   -4, 	  -8,   -4, 	  -1,  -10
.2byte   -1,   -6, 	   4,   -7, 	  -6,   -7, 	  -1,   -9
.2byte   -6,   -6, 	  -5,  -11, 	 -10,   -9, 	  -1,   -8
.2byte   -6,   -3, 	  -4,   -2, 	  -8,    0, 	  -1,  -10
.2byte   -4,   -6, 	  -1,   -8, 	  -5,   -5, 	   0,   -8
.2byte   -9,   -3, 	  -9,   -7, 	  -5,   -4, 	   0,   -7
.2byte   -8,   -2, 	  -9,   -3, 	  -5,    1, 	   1,  -12
.2byte   -5,   -4, 	  -6,   -6, 	  -5,   -3, 	   1,   -8
.2byte   -7,   -1, 	 -10,   -6, 	   1,   -2, 	   0,   -8
.2byte   -6,   -2, 	  -9,   -2, 	   1,   -3, 	   0,  -12
.2byte   -3,   -4, 	  -6,   -4, 	   0,   -3, 	   0,   -9
.2byte   -4,   -2, 	  -7,   -2, 	  -2,    0, 	   1,   -7
.2byte   -4,   -2, 	  -8,   -1, 	  -4,    1, 	   0,   -6
.2byte    0,   -4, 	  -6,   -9, 	   6,   -9, 	   0,  -11
.2byte    5,   -6, 	   8,  -12, 	  -2,   -8, 	  -3,   -9
.2byte    8,   -6, 	   7,  -10, 	   3,   -9, 	  -3,   -7
.2byte    4,   -9, 	   2,  -13, 	   7,  -11, 	  -1,   -8
.2byte    0,  -11, 	   5,  -14, 	  -6,  -14, 	   0,   -9
.2byte   -5,   -9, 	  -3,  -13, 	  -8,  -11, 	   0,   -8
.2byte   -9,   -6, 	  -8,  -10, 	  -4,   -9, 	   2,   -7
.2byte   -6,   -6, 	  -9,  -12, 	   1,   -8, 	   2,   -9
.2byte    0,    0, 	  -7,   -3, 	   7,   -3, 	   0,   -9
.2byte    0,    2, 	  -6,    3, 	   6,    3, 	   0,   -8
.2byte    0,   -1, 	  -6,   -4, 	   6,   -4, 	   0,  -10
.2byte    6,   -1, 	   9,   -6, 	  -2,   -2, 	  -1,   -8
.2byte    7,   -1, 	  12,   -2, 	   1,    2, 	   1,   -8
.2byte    5,   -3, 	   8,   -7, 	  -2,   -4, 	  -1,   -8
.2byte    8,   -3, 	   8,   -7, 	   4,   -4, 	  -1,   -7
.2byte    9,   -3, 	  12,   -4, 	   8,   -1, 	   0,   -7
.2byte    7,   -3, 	   6,   -8, 	   2,   -4, 	  -3,   -7
.2byte    5,   -6, 	   4,  -11, 	   9,   -9, 	   0,   -8
.2byte    6,   -7, 	   4,   -7, 	  11,   -6, 	   1,   -9
.2byte    4,   -7, 	   3,  -11, 	   8,   -9, 	  -1,   -8
.2byte   -1,   -8, 	   6,  -11, 	  -8,  -11, 	  -1,   -7
.2byte   -1,   -7, 	   5,  -10, 	  -7,  -10, 	  -1,   -8
.2byte   -1,   -7, 	   6,  -10, 	  -8,  -10, 	  -1,   -8
.2byte   -6,   -6, 	  -5,  -11, 	 -10,   -9, 	  -1,   -8
.2byte   -7,   -7, 	  -5,   -7, 	 -12,   -6, 	  -2,   -9
.2byte   -5,   -7, 	  -4,  -11, 	  -9,   -9, 	   0,   -8
.2byte   -9,   -3, 	  -9,   -7, 	  -5,   -4, 	   0,   -7
.2byte  -10,   -3, 	 -13,   -4, 	  -9,   -1, 	  -1,   -7
.2byte   -8,   -3, 	  -7,   -8, 	  -3,   -4, 	   2,   -7
.2byte   -7,   -1, 	 -10,   -6, 	   1,   -2, 	   0,   -8
.2byte   -8,   -1, 	 -13,   -2, 	  -2,    2, 	  -2,   -8
.2byte   -6,   -3, 	  -9,   -7, 	   1,   -4, 	   0,   -8
.2byte    0,    0, 	  -7,   -3, 	   7,   -3, 	   0,   -9
.2byte   -7,   -1, 	 -10,   -6, 	   1,   -2, 	   0,   -8
.2byte   -9,   -3, 	  -9,   -7, 	  -5,   -4, 	   0,   -7
.2byte   -6,   -6, 	  -5,  -11, 	 -10,   -9, 	  -1,   -8
.2byte   -1,   -8, 	   6,  -11, 	  -8,  -11, 	  -1,   -7
.2byte    5,   -6, 	   4,  -11, 	   9,   -9, 	   0,   -8
.2byte    8,   -3, 	   8,   -7, 	   4,   -4, 	  -1,   -7
.2byte    6,   -1, 	   9,   -6, 	  -2,   -2, 	  -1,   -8
.2byte    0,   -1, 	  -6,   -4, 	   6,   -4, 	   0,  -10
.2byte    6,   -2, 	   8,   -7, 	  -2,   -3, 	  -2,   -8
.2byte    8,   -6, 	   7,   -9, 	   2,   -6, 	  -3,   -6
.2byte    5,   -9, 	   1,  -12, 	   6,  -11, 	  -1,   -7
.2byte   -1,   -9, 	   6,  -12, 	  -8,  -12, 	  -1,   -8
.2byte   -6,   -9, 	  -2,  -12, 	  -7,  -11, 	   0,   -7
.2byte   -9,   -6, 	  -8,   -9, 	  -3,   -6, 	   2,   -6
.2byte   -7,   -2, 	  -9,   -7, 	   1,   -3, 	   1,   -8
.2byte    0,    0, 	  -7,   -3, 	   7,   -3, 	   0,   -9
.2byte    0,   -1, 	  -6,   -4, 	   6,   -4, 	   0,  -10
.2byte    0,    2, 	  -6,    3, 	   6,    3, 	   0,   -8
.2byte    6,   -1, 	   9,   -6, 	  -2,   -2, 	  -1,   -8
.2byte    6,   -2, 	   8,   -7, 	  -2,   -3, 	  -2,   -8
.2byte    5,   -1, 	  10,   -2, 	  -1,    2, 	  -1,   -8
.2byte    8,   -3, 	   8,   -7, 	   4,   -4, 	  -1,   -7
.2byte    8,   -6, 	   7,   -9, 	   2,   -6, 	  -3,   -6
.2byte    8,   -3, 	  11,   -4, 	   7,   -1, 	  -1,   -7
.2byte    8,   -3, 	   7,   -8, 	   3,   -4, 	  -2,   -7
.2byte    5,   -6, 	   4,  -11, 	   9,   -9, 	   0,   -8
.2byte    5,   -9, 	   1,  -12, 	   6,  -11, 	  -1,   -7
.2byte    5,   -7, 	   3,   -7, 	  10,   -6, 	   0,   -9
.2byte   -1,   -8, 	   6,  -11, 	  -8,  -11, 	  -1,   -7
.2byte   -1,   -9, 	   6,  -12, 	  -8,  -12, 	  -1,   -8
.2byte   -1,   -7, 	   5,  -10, 	  -7,  -10, 	  -1,   -8
.2byte   -6,   -6, 	  -5,  -11, 	 -10,   -9, 	  -1,   -8
.2byte   -6,   -9, 	  -2,  -12, 	  -7,  -11, 	   0,   -7
.2byte   -6,   -7, 	  -4,   -7, 	 -11,   -6, 	  -1,   -9
.2byte   -9,   -3, 	  -9,   -7, 	  -5,   -4, 	   0,   -7
.2byte   -9,   -6, 	  -8,   -9, 	  -3,   -6, 	   2,   -6
.2byte   -9,   -3, 	 -12,   -4, 	  -8,   -1, 	   0,   -7
.2byte   -7,   -1, 	 -10,   -6, 	   1,   -2, 	   0,   -8
.2byte   -7,   -2, 	  -9,   -7, 	   1,   -3, 	   1,   -8
.2byte   -6,   -1, 	 -11,   -2, 	   0,    2, 	   0,   -8
.2byte    0,    0, 	  -7,   -3, 	   7,   -3, 	   0,   -9
.2byte   -7,   -1, 	 -10,   -6, 	   1,   -2, 	   0,   -8
.2byte   -9,   -3, 	  -9,   -7, 	  -5,   -4, 	   0,   -7
.2byte   -6,   -6, 	  -5,  -11, 	 -10,   -9, 	  -1,   -8
.2byte   -1,   -8, 	   6,  -11, 	  -8,  -11, 	  -1,   -7
.2byte    5,   -6, 	   4,  -11, 	   9,   -9, 	   0,   -8
.2byte    8,   -3, 	   8,   -7, 	   4,   -4, 	  -1,   -7
.2byte    6,   -1, 	   9,   -6, 	  -2,   -2, 	  -1,   -8
.2byte    0,    0, 	  -7,   -3, 	   7,   -3, 	   0,   -9
.2byte   -7,   -1, 	 -10,   -6, 	   1,   -2, 	   0,   -8
.2byte   -9,   -3, 	  -9,   -7, 	  -5,   -4, 	   0,   -7
.2byte   -6,   -6, 	  -5,  -11, 	 -10,   -9, 	  -1,   -8
.2byte   -1,   -8, 	   6,  -11, 	  -8,  -11, 	  -1,   -7
.2byte    5,   -6, 	   4,  -11, 	   9,   -9, 	   0,   -8
.2byte    8,   -3, 	   8,   -7, 	   4,   -4, 	  -1,   -7
.2byte    6,   -1, 	   9,   -6, 	  -2,   -2, 	  -1,   -8
sOmanyteAnimTable1:
.4byte sOmanyteAnims_1_1
.4byte sOmanyteAnims_1_2
.4byte sOmanyteAnims_1_3
.4byte sOmanyteAnims_1_4
.4byte sOmanyteAnims_1_5
.4byte sOmanyteAnims_1_6
.4byte sOmanyteAnims_1_7
.4byte sOmanyteAnims_1_8
sOmanyteAnimTable2:
.4byte sOmanyteAnims_2_1
.4byte sOmanyteAnims_2_2
.4byte sOmanyteAnims_2_3
.4byte sOmanyteAnims_2_4
.4byte sOmanyteAnims_2_5
.4byte sOmanyteAnims_2_6
.4byte sOmanyteAnims_2_7
.4byte sOmanyteAnims_2_8
sOmanyteAnimTable3:
.4byte sOmanyteAnims_3_1
.4byte sOmanyteAnims_3_2
.4byte sOmanyteAnims_3_3
.4byte sOmanyteAnims_3_4
.4byte sOmanyteAnims_3_5
.4byte sOmanyteAnims_3_6
.4byte sOmanyteAnims_3_7
.4byte sOmanyteAnims_3_8
sOmanyteAnimTable4:
.4byte sOmanyteAnims_4_1
.4byte sOmanyteAnims_4_2
.4byte sOmanyteAnims_4_3
.4byte sOmanyteAnims_4_4
.4byte sOmanyteAnims_4_5
.4byte sOmanyteAnims_4_6
.4byte sOmanyteAnims_4_7
.4byte sOmanyteAnims_4_8
sOmanyteAnimTable5:
.4byte sOmanyteAnims_5_1
.4byte sOmanyteAnims_5_2
.4byte sOmanyteAnims_5_3
.4byte sOmanyteAnims_5_4
.4byte sOmanyteAnims_5_5
.4byte sOmanyteAnims_5_6
.4byte sOmanyteAnims_5_7
.4byte sOmanyteAnims_5_8
sOmanyteAnimTable6:
.4byte sOmanyteAnims_6_1
.4byte sOmanyteAnims_6_1
.4byte sOmanyteAnims_6_1
.4byte sOmanyteAnims_6_1
.4byte sOmanyteAnims_6_1
.4byte sOmanyteAnims_6_1
.4byte sOmanyteAnims_6_1
.4byte sOmanyteAnims_6_1
sOmanyteAnimTable7:
.4byte sOmanyteAnims_7_1
.4byte sOmanyteAnims_7_2
.4byte sOmanyteAnims_7_3
.4byte sOmanyteAnims_7_4
.4byte sOmanyteAnims_7_5
.4byte sOmanyteAnims_7_6
.4byte sOmanyteAnims_7_7
.4byte sOmanyteAnims_7_8
sOmanyteAnimTable8:
.4byte sOmanyteAnims_8_1
.4byte sOmanyteAnims_8_2
.4byte sOmanyteAnims_8_3
.4byte sOmanyteAnims_8_4
.4byte sOmanyteAnims_8_5
.4byte sOmanyteAnims_8_6
.4byte sOmanyteAnims_8_7
.4byte sOmanyteAnims_8_8
sOmanyteAnimTable9:
.4byte sOmanyteAnims_9_1
.4byte sOmanyteAnims_9_2
.4byte sOmanyteAnims_9_3
.4byte sOmanyteAnims_9_4
.4byte sOmanyteAnims_9_5
.4byte sOmanyteAnims_9_6
.4byte sOmanyteAnims_9_7
.4byte sOmanyteAnims_9_8
sOmanyteAnimTable10:
.4byte sOmanyteAnims_10_1
.4byte sOmanyteAnims_10_2
.4byte sOmanyteAnims_10_3
.4byte sOmanyteAnims_10_4
.4byte sOmanyteAnims_10_5
.4byte sOmanyteAnims_10_6
.4byte sOmanyteAnims_10_7
.4byte sOmanyteAnims_10_8
sOmanyteAnimTable11:
.4byte sOmanyteAnims_11_1
.4byte sOmanyteAnims_11_2
.4byte sOmanyteAnims_11_3
.4byte sOmanyteAnims_11_4
.4byte sOmanyteAnims_11_5
.4byte sOmanyteAnims_11_6
.4byte sOmanyteAnims_11_7
.4byte sOmanyteAnims_11_8
sOmanyteAnimTable12:
.4byte sOmanyteAnims_12_1
.4byte sOmanyteAnims_12_2
.4byte sOmanyteAnims_12_3
.4byte sOmanyteAnims_12_4
.4byte sOmanyteAnims_12_5
.4byte sOmanyteAnims_12_6
.4byte sOmanyteAnims_12_7
.4byte sOmanyteAnims_12_8
sOmanyteAnimTable13:
.4byte sOmanyteAnims_13_1
.4byte sOmanyteAnims_13_2
.4byte sOmanyteAnims_13_3
.4byte sOmanyteAnims_13_4
.4byte sOmanyteAnims_13_5
.4byte sOmanyteAnims_13_6
.4byte sOmanyteAnims_13_7
.4byte sOmanyteAnims_13_8
sAxAnimationsOmanyte:
.4byte sOmanyteAnimTable1
.4byte sOmanyteAnimTable2
.4byte sOmanyteAnimTable3
.4byte sOmanyteAnimTable4
.4byte sOmanyteAnimTable5
.4byte sOmanyteAnimTable6
.4byte sOmanyteAnimTable7
.4byte sOmanyteAnimTable8
.4byte sOmanyteAnimTable9
.4byte sOmanyteAnimTable10
.4byte sOmanyteAnimTable11
.4byte sOmanyteAnimTable12
.4byte sOmanyteAnimTable13
sAxSpritesOmanyte:
.4byte sOmanyteSprites1
.4byte sOmanyteSprites2
.4byte sOmanyteSprites3
.4byte sOmanyteSprites4
.4byte sOmanyteSprites5
.4byte sOmanyteSprites6
.4byte sOmanyteSprites7
.4byte sOmanyteSprites8
.4byte sOmanyteSprites9
.4byte sOmanyteSprites10
.4byte sOmanyteSprites11
.4byte sOmanyteSprites12
.4byte sOmanyteSprites13
.4byte sOmanyteSprites14
.4byte sOmanyteSprites15
.4byte sOmanyteSprites16
.4byte sOmanyteSprites17
.4byte sOmanyteSprites18
.4byte sOmanyteSprites19
.4byte sOmanyteSprites20
.4byte sOmanyteSprites21
.4byte sOmanyteSprites22
.4byte sOmanyteSprites23
.4byte sOmanyteSprites24
.4byte sOmanyteSprites25
.4byte sOmanyteSprites26
.4byte sOmanyteSprites27
.4byte sOmanyteSprites28
.4byte sOmanyteSprites29
.4byte sOmanyteSprites30
.4byte sOmanyteSprites31
.4byte sOmanyteSprites32
.4byte sOmanyteSprites33
.4byte sOmanyteSprites34
.4byte sOmanyteSprites35
.4byte sOmanyteSprites36
.4byte sOmanyteSprites37
.4byte sOmanyteSprites38
sAxMainOmanyte:
ax_main sAxPosesOmanyte, sAxAnimationsOmanyte, 13, sAxSpritesOmanyte, sAxPositionsOmanyte
