.global gAxPersian
gAxPersian:
ax_siro sAxMainPersian
sPersianPose1:
ax_pose 0, 0x01e7, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose2:
ax_pose 1, 0x01e7, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose3:
ax_pose 2, 0x01e7, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose4:
ax_pose 3, 0x01ed, 0x90f0, 0x4c00
ax_pose_terminator
sPersianPose5:
ax_pose 4, 0x01ed, 0x90f0, 0x4c00
ax_pose_terminator
sPersianPose6:
ax_pose 5, 0x01ed, 0x90f0, 0x4c00
ax_pose_terminator
sPersianPose7:
ax_pose 6, 0x01eb, 0x90f0, 0x4c00
ax_pose_terminator
sPersianPose8:
ax_pose 7, 0x01eb, 0x90f0, 0x4c00
ax_pose_terminator
sPersianPose9:
ax_pose 8, 0x01eb, 0x90f0, 0x4c00
ax_pose_terminator
sPersianPose10:
ax_pose 9, 0x01ed, 0x90f0, 0x4c00
ax_pose_terminator
sPersianPose11:
ax_pose 10, 0x01ed, 0x90f0, 0x4c00
ax_pose_terminator
sPersianPose12:
ax_pose 11, 0x01ed, 0x90f0, 0x4c00
ax_pose_terminator
sPersianPose13:
ax_pose 12, 0x01e7, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose14:
ax_pose 13, 0x01e7, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose15:
ax_pose 14, 0x01e7, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose16:
ax_pose 9, 0x01ed, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose17:
ax_pose 10, 0x01ed, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose18:
ax_pose 11, 0x01ed, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose19:
ax_pose 6, 0x01eb, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose20:
ax_pose 7, 0x01eb, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose21:
ax_pose 8, 0x01eb, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose22:
ax_pose 3, 0x01ed, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose23:
ax_pose 4, 0x01ed, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose24:
ax_pose 5, 0x01ed, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose25:
ax_pose 0, 0x01e7, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose26:
ax_pose 1, 0x01e7, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose27:
ax_pose 2, 0x01e7, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose28:
ax_pose 15, 0x01e7, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose29:
ax_pose 16, 0x01e7, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose30:
ax_pose 3, 0x01ed, 0x90f0, 0x4c00
ax_pose_terminator
sPersianPose31:
ax_pose 4, 0x01ed, 0x90f0, 0x4c00
ax_pose_terminator
sPersianPose32:
ax_pose 5, 0x01ed, 0x90f0, 0x4c00
ax_pose_terminator
sPersianPose33:
ax_pose 17, 0x01e7, 0x90f0, 0x4c00
ax_pose_terminator
sPersianPose34:
ax_pose 18, 0x01e7, 0x90f1, 0x4c00
ax_pose_terminator
sPersianPose35:
ax_pose 6, 0x01eb, 0x90f0, 0x4c00
ax_pose_terminator
sPersianPose36:
ax_pose 7, 0x01eb, 0x90f0, 0x4c00
ax_pose_terminator
sPersianPose37:
ax_pose 8, 0x01eb, 0x90f0, 0x4c00
ax_pose_terminator
sPersianPose38:
ax_pose 19, 0x01e2, 0x90f0, 0x4c00
ax_pose_terminator
sPersianPose39:
ax_pose 20, 0x41e4, 0x90ef, 0x4c00
ax_pose 21, 0x41f4, 0x50ef, 0x4c08
ax_pose 22, 0x01f1, 0x10e7, 0x4c0c
ax_pose_terminator
sPersianPose40:
ax_pose 9, 0x01ed, 0x90f0, 0x4c00
ax_pose_terminator
sPersianPose41:
ax_pose 10, 0x01ed, 0x90f0, 0x4c00
ax_pose_terminator
sPersianPose42:
ax_pose 11, 0x01ed, 0x90f0, 0x4c00
ax_pose_terminator
sPersianPose43:
ax_pose 23, 0x01e6, 0x90ef, 0x4c00
ax_pose_terminator
sPersianPose44:
ax_pose 24, 0x01e7, 0x90f0, 0x4c00
ax_pose_terminator
sPersianPose45:
ax_pose 12, 0x01e7, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose46:
ax_pose 13, 0x01e7, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose47:
ax_pose 14, 0x01e7, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose48:
ax_pose 25, 0x01e7, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose49:
ax_pose 26, 0x01e7, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose50:
ax_pose 9, 0x01ed, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose51:
ax_pose 10, 0x01ed, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose52:
ax_pose 11, 0x01ed, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose53:
ax_pose 23, 0x01e6, 0x80f1, 0x4c00
ax_pose_terminator
sPersianPose54:
ax_pose 24, 0x01e7, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose55:
ax_pose 6, 0x01eb, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose56:
ax_pose 7, 0x01eb, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose57:
ax_pose 8, 0x01eb, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose58:
ax_pose 19, 0x01e2, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose59:
ax_pose 20, 0x41e4, 0x80f1, 0x4c00
ax_pose 21, 0x41f4, 0x40f1, 0x4c08
ax_pose 22, 0x01f1, 0x0111, 0x4c0c
ax_pose_terminator
sPersianPose60:
ax_pose 3, 0x01ed, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose61:
ax_pose 4, 0x01ed, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose62:
ax_pose 5, 0x01ed, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose63:
ax_pose 17, 0x01e7, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose64:
ax_pose 18, 0x01e7, 0x80ef, 0x4c00
ax_pose_terminator
sPersianPose65:
ax_pose 0, 0x01e7, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose66:
ax_pose 1, 0x01e7, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose67:
ax_pose 2, 0x01e7, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose68:
ax_pose 27, 0x01e4, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose69:
ax_pose 28, 0x01e9, 0x80f3, 0x4c00
ax_pose 29, 0x01e7, 0x80f0, 0x4c10
ax_pose_terminator
sPersianPose70:
ax_pose 29, 0x01e7, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose71:
ax_pose 3, 0x01ed, 0x90f0, 0x4c00
ax_pose_terminator
sPersianPose72:
ax_pose 4, 0x01ed, 0x90f0, 0x4c00
ax_pose_terminator
sPersianPose73:
ax_pose 5, 0x01ed, 0x90f0, 0x4c00
ax_pose_terminator
sPersianPose74:
ax_pose 30, 0x01e7, 0x90f0, 0x4c00
ax_pose_terminator
sPersianPose75:
ax_pose 31, 0x81eb, 0x9104, 0x4c00
ax_pose 32, 0x01e7, 0x90f0, 0x4c08
ax_pose_terminator
sPersianPose76:
ax_pose 32, 0x01e7, 0x90f0, 0x4c00
ax_pose_terminator
sPersianPose77:
ax_pose 6, 0x01eb, 0x90f0, 0x4c00
ax_pose_terminator
sPersianPose78:
ax_pose 7, 0x01eb, 0x90f0, 0x4c00
ax_pose_terminator
sPersianPose79:
ax_pose 8, 0x01eb, 0x90f0, 0x4c00
ax_pose_terminator
sPersianPose80:
ax_pose 33, 0x01e7, 0x90f0, 0x4c00
ax_pose_terminator
sPersianPose81:
ax_pose 34, 0x81e9, 0x910a, 0x4c00
ax_pose 35, 0x01e9, 0x1102, 0x4c08
ax_pose 36, 0x01e7, 0x90f0, 0x4c09
ax_pose_terminator
sPersianPose82:
ax_pose 36, 0x01e7, 0x90f0, 0x4c00
ax_pose_terminator
sPersianPose83:
ax_pose 9, 0x01ed, 0x90f0, 0x4c00
ax_pose_terminator
sPersianPose84:
ax_pose 10, 0x01ed, 0x90f0, 0x4c00
ax_pose_terminator
sPersianPose85:
ax_pose 11, 0x01ed, 0x90f0, 0x4c00
ax_pose_terminator
sPersianPose86:
ax_pose 37, 0x01e7, 0x90f0, 0x4c00
ax_pose_terminator
sPersianPose87:
ax_pose 38, 0x01e7, 0x90f0, 0x4c00
ax_pose 39, 0x01e4, 0x90ef, 0x4c10
ax_pose_terminator
sPersianPose88:
ax_pose 38, 0x01e7, 0x90f0, 0x4c00
ax_pose_terminator
sPersianPose89:
ax_pose 12, 0x01e7, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose90:
ax_pose 13, 0x01e7, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose91:
ax_pose 14, 0x01e7, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose92:
ax_pose 40, 0x01e7, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose93:
ax_pose 41, 0x01e7, 0x80f0, 0x4c00
ax_pose 42, 0x01e4, 0x80f2, 0x4c10
ax_pose_terminator
sPersianPose94:
ax_pose 41, 0x01e7, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose95:
ax_pose 9, 0x01ed, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose96:
ax_pose 10, 0x01ed, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose97:
ax_pose 11, 0x01ed, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose98:
ax_pose 37, 0x01e7, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose99:
ax_pose 38, 0x01e7, 0x80f0, 0x4c00
ax_pose 39, 0x01e4, 0x80f3, 0x4c10
ax_pose_terminator
sPersianPose100:
ax_pose 38, 0x01e7, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose101:
ax_pose 6, 0x01eb, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose102:
ax_pose 7, 0x01eb, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose103:
ax_pose 8, 0x01eb, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose104:
ax_pose 33, 0x01e7, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose105:
ax_pose 34, 0x81e9, 0x80e6, 0x4c00
ax_pose 35, 0x01e9, 0x00f6, 0x4c08
ax_pose 36, 0x01e7, 0x80f0, 0x4c09
ax_pose_terminator
sPersianPose106:
ax_pose 36, 0x01e7, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose107:
ax_pose 3, 0x01ed, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose108:
ax_pose 4, 0x01ed, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose109:
ax_pose 5, 0x01ed, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose110:
ax_pose 30, 0x01e7, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose111:
ax_pose 31, 0x81ed, 0x80ed, 0x4c00
ax_pose 32, 0x01e7, 0x80f0, 0x4c08
ax_pose_terminator
sPersianPose112:
ax_pose 32, 0x01e7, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose113:
ax_pose 1, 0x01e7, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose114:
ax_pose 43, 0x01e7, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose115:
ax_pose 44, 0x01e7, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose116:
ax_pose 4, 0x01ed, 0x90f0, 0x4c00
ax_pose_terminator
sPersianPose117:
ax_pose 45, 0x01e6, 0x90f0, 0x4c00
ax_pose_terminator
sPersianPose118:
ax_pose 46, 0x01e6, 0x90f0, 0x4c00
ax_pose_terminator
sPersianPose119:
ax_pose 7, 0x01eb, 0x90f0, 0x4c00
ax_pose_terminator
sPersianPose120:
ax_pose 47, 0x01e7, 0x90f0, 0x4c00
ax_pose_terminator
sPersianPose121:
ax_pose 48, 0x41ef, 0x90f3, 0x4c00
ax_pose 49, 0x41ff, 0x50f3, 0x4c08
ax_pose 50, 0x01f5, 0x10eb, 0x4c0c
ax_pose_terminator
sPersianPose122:
ax_pose 10, 0x01ed, 0x90f0, 0x4c00
ax_pose_terminator
sPersianPose123:
ax_pose 51, 0x01e7, 0x90f0, 0x4c00
ax_pose_terminator
sPersianPose124:
ax_pose 52, 0x01e7, 0x90f0, 0x4c00
ax_pose_terminator
sPersianPose125:
ax_pose 13, 0x01e7, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose126:
ax_pose 53, 0x01e7, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose127:
ax_pose 54, 0x01e7, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose128:
ax_pose 10, 0x01ed, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose129:
ax_pose 51, 0x01e7, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose130:
ax_pose 52, 0x01e7, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose131:
ax_pose 7, 0x01eb, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose132:
ax_pose 47, 0x01e7, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose133:
ax_pose 48, 0x41ef, 0x80ed, 0x4c00
ax_pose 49, 0x41ff, 0x40ed, 0x4c08
ax_pose 50, 0x01f5, 0x010d, 0x4c0c
ax_pose_terminator
sPersianPose134:
ax_pose 4, 0x01ed, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose135:
ax_pose 45, 0x01e6, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose136:
ax_pose 46, 0x01e6, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose137:
ax_pose 55, 0x81e8, 0x80f8, 0x4c00
ax_pose 56, 0x01f0, 0x00f0, 0x4c08
ax_pose_terminator
sPersianPose138:
ax_pose 57, 0x01e9, 0x80ef, 0x4c00
ax_pose_terminator
sPersianPose139:
ax_pose 58, 0x01e7, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose140:
ax_pose 59, 0x01e8, 0x80ef, 0x4c00
ax_pose_terminator
sPersianPose141:
ax_pose 60, 0x81e7, 0x80f8, 0x4c00
ax_pose 61, 0x81e7, 0x00f0, 0x4c08
ax_pose_terminator
sPersianPose142:
ax_pose 59, 0x01e8, 0x90f1, 0x4c00
ax_pose_terminator
sPersianPose143:
ax_pose 58, 0x01e7, 0x90f0, 0x4c00
ax_pose_terminator
sPersianPose144:
ax_pose 57, 0x01e9, 0x90f1, 0x4c00
ax_pose_terminator
sPersianPose145:
ax_pose 62, 0x41f4, 0x80f2, 0x4c00
ax_pose_terminator
sPersianPose146:
ax_pose 63, 0x41f4, 0x80f2, 0x4c00
ax_pose_terminator
sPersianPose147:
ax_pose 64, 0x01e5, 0x80f1, 0x4c00
ax_pose_terminator
sPersianPose148:
ax_pose 65, 0x01e5, 0x90f1, 0x4c00
ax_pose_terminator
sPersianPose149:
ax_pose 66, 0x01e5, 0x90ef, 0x4c00
ax_pose_terminator
sPersianPose150:
ax_pose 67, 0x01e8, 0x90ef, 0x4c00
ax_pose_terminator
sPersianPose151:
ax_pose 68, 0x01e8, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose152:
ax_pose 67, 0x01e8, 0x80f1, 0x4c00
ax_pose_terminator
sPersianPose153:
ax_pose 66, 0x01e5, 0x80f1, 0x4c00
ax_pose_terminator
sPersianPose154:
ax_pose 65, 0x01e5, 0x80f1, 0x4c00
ax_pose_terminator
sPersianPose155:
ax_pose 1, 0x01e7, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose156:
ax_pose 55, 0x81e8, 0x80f8, 0x4c00
ax_pose 56, 0x01f0, 0x00f0, 0x4c08
ax_pose_terminator
sPersianPose157:
ax_pose 4, 0x01ed, 0x90f0, 0x4c00
ax_pose_terminator
sPersianPose158:
ax_pose 57, 0x01e8, 0x90f1, 0x4c00
ax_pose_terminator
sPersianPose159:
ax_pose 7, 0x01eb, 0x90f0, 0x4c00
ax_pose_terminator
sPersianPose160:
ax_pose 58, 0x01e7, 0x90ef, 0x4c00
ax_pose_terminator
sPersianPose161:
ax_pose 10, 0x01ed, 0x90f0, 0x4c00
ax_pose_terminator
sPersianPose162:
ax_pose 59, 0x01e8, 0x90f0, 0x4c00
ax_pose_terminator
sPersianPose163:
ax_pose 13, 0x01e7, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose164:
ax_pose 60, 0x81e7, 0x80f8, 0x4c00
ax_pose 61, 0x81e7, 0x00f0, 0x4c08
ax_pose_terminator
sPersianPose165:
ax_pose 10, 0x01ed, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose166:
ax_pose 59, 0x01e8, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose167:
ax_pose 7, 0x01eb, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose168:
ax_pose 58, 0x01e7, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose169:
ax_pose 4, 0x01ed, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose170:
ax_pose 57, 0x01e8, 0x80ef, 0x4c00
ax_pose_terminator
sPersianPose171:
ax_pose 15, 0x01e7, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose172:
ax_pose 17, 0x01e7, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose173:
ax_pose 19, 0x01e2, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose174:
ax_pose 23, 0x01e6, 0x80f1, 0x4c00
ax_pose_terminator
sPersianPose175:
ax_pose 25, 0x01e7, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose176:
ax_pose 23, 0x01e6, 0x90ef, 0x4c00
ax_pose_terminator
sPersianPose177:
ax_pose 19, 0x01e2, 0x90f0, 0x4c00
ax_pose_terminator
sPersianPose178:
ax_pose 17, 0x01e7, 0x90f0, 0x4c00
ax_pose_terminator
sPersianPose179:
ax_pose 15, 0x01e7, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose180:
ax_pose 17, 0x01e7, 0x90f0, 0x4c00
ax_pose_terminator
sPersianPose181:
ax_pose 19, 0x01e2, 0x90f0, 0x4c00
ax_pose_terminator
sPersianPose182:
ax_pose 23, 0x01e6, 0x90ef, 0x4c00
ax_pose_terminator
sPersianPose183:
ax_pose 25, 0x01e7, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose184:
ax_pose 23, 0x01e6, 0x80f1, 0x4c00
ax_pose_terminator
sPersianPose185:
ax_pose 19, 0x01e2, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose186:
ax_pose 17, 0x01e7, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose187:
ax_pose 1, 0x01e7, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose188:
ax_pose 43, 0x01e7, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose189:
ax_pose 44, 0x01e7, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose190:
ax_pose 4, 0x01ed, 0x90f0, 0x4c00
ax_pose_terminator
sPersianPose191:
ax_pose 45, 0x01e6, 0x90f0, 0x4c00
ax_pose_terminator
sPersianPose192:
ax_pose 46, 0x01e6, 0x90f0, 0x4c00
ax_pose_terminator
sPersianPose193:
ax_pose 7, 0x01eb, 0x90f0, 0x4c00
ax_pose_terminator
sPersianPose194:
ax_pose 47, 0x01e7, 0x90f0, 0x4c00
ax_pose_terminator
sPersianPose195:
ax_pose 48, 0x41ef, 0x90f3, 0x4c00
ax_pose 49, 0x41ff, 0x50f3, 0x4c08
ax_pose 50, 0x01f5, 0x10eb, 0x4c0c
ax_pose_terminator
sPersianPose196:
ax_pose 10, 0x01ed, 0x90f0, 0x4c00
ax_pose_terminator
sPersianPose197:
ax_pose 51, 0x01e7, 0x90f0, 0x4c00
ax_pose_terminator
sPersianPose198:
ax_pose 52, 0x01e7, 0x90f0, 0x4c00
ax_pose_terminator
sPersianPose199:
ax_pose 13, 0x01e7, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose200:
ax_pose 53, 0x01e7, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose201:
ax_pose 54, 0x01e7, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose202:
ax_pose 10, 0x01ed, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose203:
ax_pose 51, 0x01e7, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose204:
ax_pose 52, 0x01e7, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose205:
ax_pose 7, 0x01eb, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose206:
ax_pose 47, 0x01e7, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose207:
ax_pose 48, 0x41ef, 0x80ed, 0x4c00
ax_pose 49, 0x41ff, 0x40ed, 0x4c08
ax_pose 50, 0x01f5, 0x010d, 0x4c0c
ax_pose_terminator
sPersianPose208:
ax_pose 4, 0x01ed, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose209:
ax_pose 45, 0x01e6, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose210:
ax_pose 46, 0x01e6, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose211:
ax_pose 55, 0x81e8, 0x80f8, 0x4c00
ax_pose 56, 0x01f0, 0x00f0, 0x4c08
ax_pose_terminator
sPersianPose212:
ax_pose 57, 0x01e9, 0x80ef, 0x4c00
ax_pose_terminator
sPersianPose213:
ax_pose 58, 0x01e7, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose214:
ax_pose 59, 0x01e8, 0x80ef, 0x4c00
ax_pose_terminator
sPersianPose215:
ax_pose 60, 0x81e7, 0x80f8, 0x4c00
ax_pose 61, 0x81e7, 0x00f0, 0x4c08
ax_pose_terminator
sPersianPose216:
ax_pose 59, 0x01e8, 0x90f1, 0x4c00
ax_pose_terminator
sPersianPose217:
ax_pose 58, 0x01e7, 0x90f0, 0x4c00
ax_pose_terminator
sPersianPose218:
ax_pose 57, 0x01e9, 0x90f1, 0x4c00
ax_pose_terminator
sPersianPose219:
ax_pose 0, 0x01e7, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose220:
ax_pose 3, 0x01ed, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose221:
ax_pose 6, 0x01eb, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose222:
ax_pose 9, 0x01ed, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose223:
ax_pose 12, 0x01e7, 0x80f0, 0x4c00
ax_pose_terminator
sPersianPose224:
ax_pose 9, 0x01ed, 0x90f0, 0x4c00
ax_pose_terminator
sPersianPose225:
ax_pose 6, 0x01eb, 0x90f0, 0x4c00
ax_pose_terminator
sPersianPose226:
ax_pose 3, 0x01ed, 0x90f0, 0x4c00
ax_pose_terminator
.align 2
sPersianAnims_1_1:
ax_anim 8, 0, 1, 0, 0, 0, 0,
ax_anim 10, 0, 0, 0, 0, 0, 0,
ax_anim 8, 0, 1, 0, 0, 0, 0,
ax_anim 10, 0, 2, 0, 0, 0, 0,
ax_anim_terminator
sPersianAnims_1_2:
ax_anim 8, 0, 4, 0, 0, 0, 0,
ax_anim 10, 0, 3, 0, 0, 0, 0,
ax_anim 8, 0, 4, 0, 0, 0, 0,
ax_anim 10, 0, 5, 0, 0, 0, 0,
ax_anim_terminator
sPersianAnims_1_3:
ax_anim 8, 0, 7, 0, 0, 0, 0,
ax_anim 10, 0, 6, 0, 0, 0, 0,
ax_anim 8, 0, 7, 0, 0, 0, 0,
ax_anim 10, 0, 8, 0, 0, 0, 0,
ax_anim_terminator
sPersianAnims_1_4:
ax_anim 8, 0, 10, 0, 0, 0, 0,
ax_anim 10, 0, 9, 0, 0, 0, 0,
ax_anim 8, 0, 10, 0, 0, 0, 0,
ax_anim 10, 0, 11, 0, 0, 0, 0,
ax_anim_terminator
sPersianAnims_1_5:
ax_anim 8, 0, 13, 0, 0, 0, 0,
ax_anim 10, 0, 12, 0, 0, 0, 0,
ax_anim 8, 0, 13, 0, 0, 0, 0,
ax_anim 10, 0, 14, 0, 0, 0, 0,
ax_anim_terminator
sPersianAnims_1_6:
ax_anim 8, 0, 16, 0, 0, 0, 0,
ax_anim 10, 0, 15, 0, 0, 0, 0,
ax_anim 8, 0, 16, 0, 0, 0, 0,
ax_anim 10, 0, 17, 0, 0, 0, 0,
ax_anim_terminator
sPersianAnims_1_7:
ax_anim 8, 0, 19, 0, 0, 0, 0,
ax_anim 10, 0, 18, 0, 0, 0, 0,
ax_anim 8, 0, 19, 0, 0, 0, 0,
ax_anim 10, 0, 20, 0, 0, 0, 0,
ax_anim_terminator
sPersianAnims_1_8:
ax_anim 8, 0, 22, 0, 0, 0, 0,
ax_anim 10, 0, 21, 0, 0, 0, 0,
ax_anim 8, 0, 22, 0, 0, 0, 0,
ax_anim 10, 0, 23, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sPersianAnims_2_1:
ax_anim 2, 0, 25, 0, -2, 0, -2,
ax_anim 2, 0, 24, 0, -4, 0, -4,
ax_anim 6, 0, 27, 0, -6, 0, -6,
ax_anim 2, 0, 27, 1, -6, 1, -6,
ax_anim 2, 0, 27, 0, -6, 0, -6,
ax_anim 1, 2, 28, 0, -7, 0, -3,
ax_anim 2, 0, 28, 0, -2, 0, 2,
ax_anim 2, 0, 25, 0, 3, 0, 10,
ax_anim 1, 0, 27, 0, 12, 0, 15,
ax_anim 2, 0, 27, 0, 17, 0, 17,
ax_anim 2, 1, 27, 1, 17, 1, 17,
ax_anim 2, 0, 27, 0, 17, 0, 17,
ax_anim 2, 0, 27, 1, 17, 1, 17,
ax_anim 2, 0, 27, 0, 17, 0, 17,
ax_anim 2, 0, 25, 0, 9, 0, 9,
ax_anim 2, 0, 25, 0, 3, 0, 3,
ax_anim_terminator
sPersianAnims_2_2:
ax_anim 2, 0, 30, -2, -2, -2, -2,
ax_anim 2, 0, 29, -4, -4, -4, -4,
ax_anim 6, 0, 32, -6, -6, -6, -6,
ax_anim 2, 0, 32, -5, -7, -5, -7,
ax_anim 2, 0, 32, -6, -6, -6, -6,
ax_anim 1, 2, 33, 0, -5, -2, -2,
ax_anim 2, 0, 33, 5, -1, 4, 4,
ax_anim 2, 0, 31, 11, -2, 9, 9,
ax_anim 1, 0, 32, 15, 5, 13, 13,
ax_anim 2, 0, 32, 17, 17, 17, 17,
ax_anim 2, 1, 32, 18, 16, 18, 16,
ax_anim 2, 0, 32, 17, 17, 17, 17,
ax_anim 2, 0, 32, 18, 16, 18, 16,
ax_anim 2, 0, 32, 17, 17, 17, 17,
ax_anim 2, 0, 30, 9, 9, 9, 9,
ax_anim 2, 0, 30, 3, 3, 3, 3,
ax_anim_terminator
sPersianAnims_2_3:
ax_anim 2, 0, 35, -2, 0, -2, 0,
ax_anim 2, 0, 36, -4, 0, -4, 0,
ax_anim 6, 0, 37, -6, 0, -6, 0,
ax_anim 2, 0, 37, -6, -1, -6, -1,
ax_anim 2, 0, 37, -6, 0, -6, 0,
ax_anim 1, 2, 38, -1, 2, 0, 0,
ax_anim 2, 0, 38, 3, -1, 7, 0,
ax_anim 2, 0, 36, 4, -8, 7, 0,
ax_anim 1, 0, 37, 11, -5, 7, 0,
ax_anim 2, 0, 37, 15, 0, 15, 0,
ax_anim 2, 1, 37, 15, -1, 15, -1,
ax_anim 2, 0, 37, 15, 0, 15, 0,
ax_anim 2, 0, 37, 15, -1, 15, -1,
ax_anim 2, 0, 37, 15, 0, 15, 0,
ax_anim 2, 0, 34, 9, 0, 9, 0,
ax_anim 2, 0, 36, 3, 0, 3, 0,
ax_anim_terminator
sPersianAnims_2_4:
ax_anim 2, 0, 40, -2, 2, -2, 2,
ax_anim 2, 0, 41, -4, 4, -4, 4,
ax_anim 6, 0, 42, -6, 6, -6, 6,
ax_anim 2, 0, 42, -5, 7, -5, 7,
ax_anim 2, 0, 42, -6, 6, -6, 6,
ax_anim 1, 2, 43, -1, -3, 1, -1,
ax_anim 2, 0, 43, 2, -10, 6, -6,
ax_anim 2, 0, 41, 7, -19, 9, -9,
ax_anim 1, 0, 42, 13, -23, 16, -16,
ax_anim 2, 0, 42, 17, -23, 17, -23,
ax_anim 2, 1, 42, 18, -22, 18, -22,
ax_anim 2, 0, 42, 17, -23, 17, -23,
ax_anim 2, 0, 42, 18, -22, 18, -22,
ax_anim 2, 0, 42, 17, -23, 17, -23,
ax_anim 2, 0, 40, 8, -11, 8, -11,
ax_anim 2, 0, 40, 3, -4, 3, -4,
ax_anim_terminator
sPersianAnims_2_5:
ax_anim 2, 0, 45, 0, 2, 0, 2,
ax_anim 2, 0, 46, 0, 4, 0, 4,
ax_anim 6, 0, 47, 0, 6, 0, 6,
ax_anim 2, 0, 47, 0, 7, 0, 7,
ax_anim 2, 0, 47, 0, 6, 0, 6,
ax_anim 1, 2, 48, 0, -3, 0, -1,
ax_anim 2, 0, 48, 0, -10, 0, -6,
ax_anim 2, 0, 46, 0, -19, 0, -9,
ax_anim 1, 0, 47, 0, -23, 0, -16,
ax_anim 2, 0, 47, 0, -23, 0, -23,
ax_anim 2, 1, 47, 0, -22, 0, -22,
ax_anim 2, 0, 47, 0, -23, 0, -23,
ax_anim 2, 0, 47, 0, -22, 0, -22,
ax_anim 2, 0, 47, 0, -23, 0, -23,
ax_anim 2, 0, 45, 0, -11, 0, -11,
ax_anim 2, 0, 45, 0, -4, 0, -4,
ax_anim_terminator
sPersianAnims_2_6:
ax_anim 2, 0, 50, 2, 2, 2, 2,
ax_anim 2, 0, 51, 4, 4, 4, 4,
ax_anim 6, 0, 52, 6, 6, 6, 6,
ax_anim 2, 0, 52, 5, 7, 5, 7,
ax_anim 2, 0, 52, 6, 6, 6, 6,
ax_anim 1, 2, 53, 1, -3, -1, -1,
ax_anim 2, 0, 53, -2, -10, -6, -6,
ax_anim 2, 0, 51, -7, -19, -9, -9,
ax_anim 1, 0, 52, -13, -23, -16, -16,
ax_anim 2, 0, 52, -17, -23, -17, -23,
ax_anim 2, 1, 52, -18, -22, -18, -22,
ax_anim 2, 0, 52, -17, -23, -17, -23,
ax_anim 2, 0, 52, -18, -22, -18, -22,
ax_anim 2, 0, 52, -17, -23, -17, -23,
ax_anim 2, 0, 50, -8, -11, -8, -11,
ax_anim 2, 0, 50, -3, -4, -3, -4,
ax_anim_terminator
sPersianAnims_2_7:
ax_anim 2, 0, 55, 2, 0, 2, 0,
ax_anim 2, 0, 56, 4, 0, 4, 0,
ax_anim 6, 0, 57, 6, 0, 6, 0,
ax_anim 2, 0, 57, 6, -1, 6, -1,
ax_anim 2, 0, 57, 6, 0, 6, 0,
ax_anim 1, 2, 58, 1, 2, 0, 0,
ax_anim 2, 0, 58, -3, -1, -7, 0,
ax_anim 2, 0, 56, -4, -8, -7, 0,
ax_anim 1, 0, 57, -11, -5, -7, 0,
ax_anim 2, 0, 57, -15, 0, -15, 0,
ax_anim 2, 1, 57, -15, -1, -15, -1,
ax_anim 2, 0, 57, -15, 0, -15, 0,
ax_anim 2, 0, 57, -15, -1, -15, -1,
ax_anim 2, 0, 57, -15, 0, -15, 0,
ax_anim 2, 0, 54, -9, 0, -9, 0,
ax_anim 2, 0, 56, -3, 0, -3, 0,
ax_anim_terminator
sPersianAnims_2_8:
ax_anim 2, 0, 60, 2, -2, 2, -2,
ax_anim 2, 0, 59, 4, -4, 4, -4,
ax_anim 6, 0, 62, 6, -6, 6, -6,
ax_anim 2, 0, 62, 5, -7, 5, -7,
ax_anim 2, 0, 62, 6, -6, 6, -6,
ax_anim 1, 2, 63, 0, -5, 2, -2,
ax_anim 2, 0, 63, -5, -1, -4, 4,
ax_anim 2, 0, 61, -11, -2, -9, 9,
ax_anim 1, 0, 62, -15, 5, -13, 13,
ax_anim 2, 0, 62, -17, 17, -17, 17,
ax_anim 2, 1, 62, -18, 16, -18, 16,
ax_anim 2, 0, 62, -17, 17, -17, 17,
ax_anim 2, 0, 62, -18, 16, -18, 16,
ax_anim 2, 0, 62, -17, 17, -17, 17,
ax_anim 2, 0, 60, -9, 9, -9, 9,
ax_anim 2, 0, 60, -3, 3, -3, 3,
ax_anim_terminator
.align 2
sPersianAnims_3_1:
ax_anim 2, 0, 64, 0, -2, 0, -2,
ax_anim 2, 0, 66, 0, -4, 0, -4,
ax_anim 4, 0, 67, 0, -5, 0, -5,
ax_anim 1, 2, 67, 0, -2, 0, -2,
ax_anim 2, 0, 67, 0, 4, 0, 4,
ax_anim 2, 0, 68, 0, 13, 0, 13,
ax_anim 2, 1, 69, 0, 14, 0, 14,
ax_anim 2, 0, 69, 1, 14, 1, 14,
ax_anim 2, 0, 69, 0, 14, 0, 14,
ax_anim 2, 0, 69, 1, 14, 1, 14,
ax_anim 2, 0, 69, 0, 14, 0, 14,
ax_anim 2, 0, 65, 0, 8, 0, 8,
ax_anim 2, 0, 65, 0, 3, 0, 3,
ax_anim_terminator
sPersianAnims_3_2:
ax_anim 2, 0, 70, -2, -2, -2, -2,
ax_anim 2, 0, 72, -4, -4, -4, -4,
ax_anim 4, 0, 73, -5, -5, -5, -5,
ax_anim 1, 2, 73, -2, -2, -2, -2,
ax_anim 2, 0, 73, 4, 4, 4, 4,
ax_anim 2, 0, 74, 14, 16, 14, 16,
ax_anim 2, 1, 75, 15, 17, 15, 17,
ax_anim 2, 0, 75, 16, 16, 16, 16,
ax_anim 2, 0, 75, 15, 17, 15, 17,
ax_anim 2, 0, 75, 16, 16, 16, 16,
ax_anim 2, 0, 75, 15, 17, 15, 17,
ax_anim 2, 0, 71, 8, 8, 8, 8,
ax_anim 2, 0, 71, 3, 3, 3, 3,
ax_anim_terminator
sPersianAnims_3_3:
ax_anim 2, 0, 76, -2, 0, -2, 0,
ax_anim 2, 0, 78, -4, 0, -4, 0,
ax_anim 4, 0, 79, -5, 0, -5, 0,
ax_anim 1, 2, 79, -2, 0, -2, 0,
ax_anim 2, 0, 79, 4, 0, 4, 0,
ax_anim 2, 0, 80, 10, 0, 10, 0,
ax_anim 2, 1, 81, 11, 0, 11, 0,
ax_anim 2, 0, 81, 11, 1, 11, 1,
ax_anim 2, 0, 81, 11, 0, 11, 0,
ax_anim 2, 0, 81, 11, 1, 11, 1,
ax_anim 2, 0, 81, 11, 0, 11, 0,
ax_anim 2, 0, 77, 6, 0, 6, 0,
ax_anim 2, 0, 77, 2, 0, 2, 0,
ax_anim_terminator
sPersianAnims_3_4:
ax_anim 2, 0, 82, -2, 2, -2, 2,
ax_anim 2, 0, 84, -4, 4, -4, 4,
ax_anim 4, 0, 85, -5, 5, -5, 5,
ax_anim 1, 2, 85, -2, 2, -2, 2,
ax_anim 2, 0, 85, 4, -7, 4, -7,
ax_anim 2, 0, 86, 14, -21, 14, -21,
ax_anim 2, 1, 87, 15, -22, 15, -22,
ax_anim 2, 0, 87, 16, -21, 16, -21,
ax_anim 2, 0, 87, 15, -22, 15, -22,
ax_anim 2, 0, 87, 16, -21, 16, -21,
ax_anim 2, 0, 87, 15, -22, 15, -22,
ax_anim 2, 0, 83, 7, -10, 7, -10,
ax_anim 2, 0, 83, 3, -4, 3, -4,
ax_anim_terminator
sPersianAnims_3_5:
ax_anim 2, 0, 88, 0, 2, 0, 2,
ax_anim 2, 0, 90, 0, 4, 0, 4,
ax_anim 4, 0, 91, 0, 5, 0, 5,
ax_anim 1, 2, 91, 0, 2, 0, 2,
ax_anim 2, 0, 91, 0, -7, 0, -7,
ax_anim 2, 0, 92, 0, -19, 0, -19,
ax_anim 2, 1, 93, 0, -20, 0, -20,
ax_anim 2, 0, 93, 1, -20, 1, -20,
ax_anim 2, 0, 93, 0, -20, 0, -20,
ax_anim 2, 0, 93, 1, -20, 1, -20,
ax_anim 2, 0, 93, 0, -20, 0, -20,
ax_anim 2, 0, 89, 0, -10, 0, -10,
ax_anim 2, 0, 89, 0, -4, 0, -4,
ax_anim_terminator
sPersianAnims_3_6:
ax_anim 2, 0, 94, 2, 2, 2, 2,
ax_anim 2, 0, 96, 4, 4, 4, 4,
ax_anim 4, 0, 97, 5, 5, 5, 5,
ax_anim 1, 2, 97, 2, 2, 2, 2,
ax_anim 2, 0, 97, -4, -7, -4, -7,
ax_anim 2, 0, 98, -14, -21, -14, -21,
ax_anim 2, 1, 99, -15, -22, -15, -22,
ax_anim 2, 0, 99, -16, -21, -16, -21,
ax_anim 2, 0, 99, -15, -22, -15, -22,
ax_anim 2, 0, 99, -16, -21, -16, -21,
ax_anim 2, 0, 99, -15, -22, -15, -22,
ax_anim 2, 0, 95, -7, -10, -7, -10,
ax_anim 2, 0, 95, -3, -4, -3, -4,
ax_anim_terminator
sPersianAnims_3_7:
ax_anim 2, 0, 100, 2, 0, 2, 0,
ax_anim 2, 0, 102, 4, 0, 4, 0,
ax_anim 4, 0, 103, 5, 0, 5, 0,
ax_anim 1, 2, 103, 2, 0, 2, 0,
ax_anim 2, 0, 103, -4, 0, -4, 0,
ax_anim 2, 0, 104, -10, 0, -10, 0,
ax_anim 2, 1, 105, -11, 0, -11, 0,
ax_anim 2, 0, 105, -11, 1, -11, 1,
ax_anim 2, 0, 105, -11, 0, -11, 0,
ax_anim 2, 0, 105, -11, 1, -11, 1,
ax_anim 2, 0, 105, -11, 0, -11, 0,
ax_anim 2, 0, 101, -6, 0, -6, 0,
ax_anim 2, 0, 101, -2, 0, -2, 0,
ax_anim_terminator
sPersianAnims_3_8:
ax_anim 2, 0, 106, 2, -2, 2, -2,
ax_anim 2, 0, 108, 4, -4, 4, -4,
ax_anim 4, 0, 109, 5, -5, 5, -5,
ax_anim 1, 2, 109, 2, -2, 2, -2,
ax_anim 2, 0, 109, -4, 4, -4, 4,
ax_anim 2, 0, 110, -14, 16, -14, 16,
ax_anim 2, 1, 111, -15, 17, -15, 17,
ax_anim 2, 0, 111, -16, 16, -16, 16,
ax_anim 2, 0, 111, -15, 17, -15, 17,
ax_anim 2, 0, 111, -16, 16, -16, 16,
ax_anim 2, 0, 111, -15, 17, -15, 17,
ax_anim 2, 0, 107, -8, 8, -8, 8,
ax_anim 2, 0, 107, -3, 3, -3, 3,
ax_anim_terminator
.align 2
sPersianAnims_4_1:
ax_anim 2, 0, 112, 0, -2, 0, -2,
ax_anim 2, 0, 113, 0, -3, 0, -3,
ax_anim 4, 2, 113, 0, -4, 0, -4,
ax_anim 2, 0, 114, 0, 0, 0, 0,
ax_anim 2, 0, 114, 0, 4, 0, 4,
ax_anim 2, 1, 114, 1, 4, 1, 4,
ax_anim 2, 0, 114, 0, 4, 0, 4,
ax_anim 2, 0, 114, 1, 4, 1, 4,
ax_anim 2, 0, 114, 0, 4, 0, 4,
ax_anim 2, 0, 114, 1, 4, 1, 4,
ax_anim 2, 0, 112, 0, 2, 0, 2,
ax_anim_terminator
sPersianAnims_4_2:
ax_anim 2, 0, 115, -2, -2, -2, -2,
ax_anim 2, 0, 116, -3, -3, -3, -3,
ax_anim 4, 2, 116, -4, -4, -4, -4,
ax_anim 2, 0, 117, 0, 0, 0, 0,
ax_anim 2, 0, 117, 4, 4, 4, 4,
ax_anim 2, 1, 117, 5, 3, 5, 3,
ax_anim 2, 0, 117, 4, 4, 4, 4,
ax_anim 2, 0, 117, 5, 3, 5, 3,
ax_anim 2, 0, 117, 4, 4, 4, 4,
ax_anim 2, 0, 117, 5, 3, 5, 3,
ax_anim 2, 0, 115, 2, 2, 2, 2,
ax_anim_terminator
sPersianAnims_4_3:
ax_anim 2, 0, 118, -2, 0, -2, 0,
ax_anim 2, 0, 119, -3, 0, -3, 0,
ax_anim 4, 2, 119, -4, 0, -4, 0,
ax_anim 2, 0, 120, 0, 0, 0, 0,
ax_anim 2, 0, 120, 4, 0, 4, 0,
ax_anim 2, 1, 120, 4, 1, 4, 1,
ax_anim 2, 0, 120, 4, 0, 4, 0,
ax_anim 2, 0, 120, 4, 1, 4, 1,
ax_anim 2, 0, 120, 4, 0, 4, 0,
ax_anim 2, 0, 120, 4, 1, 4, 1,
ax_anim 2, 0, 118, 2, 0, 2, 0,
ax_anim_terminator
sPersianAnims_4_4:
ax_anim 2, 0, 121, -2, 2, -2, 2,
ax_anim 2, 0, 122, -3, 3, -3, 3,
ax_anim 4, 2, 122, -4, 4, -4, 4,
ax_anim 2, 0, 123, 0, 0, 0, 0,
ax_anim 2, 0, 123, 5, -5, 5, -5,
ax_anim 2, 1, 123, 6, -4, 6, -4,
ax_anim 2, 0, 123, 5, -5, 5, -5,
ax_anim 2, 0, 123, 6, -4, 6, -4,
ax_anim 2, 0, 123, 5, -5, 5, -5,
ax_anim 2, 0, 123, 6, -4, 6, -4,
ax_anim 2, 0, 121, 2, -2, 2, -2,
ax_anim_terminator
sPersianAnims_4_5:
ax_anim 2, 0, 124, 0, 2, 0, 2,
ax_anim 2, 0, 125, 0, 3, 0, 3,
ax_anim 4, 2, 125, 0, 4, 0, 4,
ax_anim 2, 0, 126, 0, 0, 0, 0,
ax_anim 2, 0, 126, 0, -5, 0, -5,
ax_anim 2, 1, 126, 1, -5, 1, -5,
ax_anim 2, 0, 126, 0, -5, 0, -5,
ax_anim 2, 0, 126, 1, -5, 1, -5,
ax_anim 2, 0, 126, 0, -5, 0, -5,
ax_anim 2, 0, 126, 1, -5, 1, -5,
ax_anim 2, 0, 124, 0, -2, 0, -2,
ax_anim_terminator
sPersianAnims_4_6:
ax_anim 2, 0, 127, 2, 2, 2, 2,
ax_anim 2, 0, 128, 3, 3, 3, 3,
ax_anim 4, 2, 128, 4, 4, 4, 4,
ax_anim 2, 0, 129, 0, 0, 0, 0,
ax_anim 2, 0, 129, -5, -5, -5, -5,
ax_anim 2, 1, 129, -6, -4, -6, -4,
ax_anim 2, 0, 129, -5, -5, -5, -5,
ax_anim 2, 0, 129, -6, -4, -6, -4,
ax_anim 2, 0, 129, -5, -5, -5, -5,
ax_anim 2, 0, 129, -6, -4, -6, -4,
ax_anim 2, 0, 127, -2, -2, -2, -2,
ax_anim_terminator
sPersianAnims_4_7:
ax_anim 2, 0, 130, 2, 0, 2, 0,
ax_anim 2, 0, 131, 3, 0, 3, 0,
ax_anim 4, 2, 131, 4, 0, 4, 0,
ax_anim 2, 0, 132, 0, 0, 0, 0,
ax_anim 2, 0, 132, -4, 0, -4, 0,
ax_anim 2, 1, 132, -4, 1, -4, 1,
ax_anim 2, 0, 132, -4, 0, -4, 0,
ax_anim 2, 0, 132, -4, 1, -4, 1,
ax_anim 2, 0, 132, -4, 0, -4, 0,
ax_anim 2, 0, 132, -4, 1, -4, 1,
ax_anim 2, 0, 130, -2, 0, -2, 0,
ax_anim_terminator
sPersianAnims_4_8:
ax_anim 2, 0, 133, 2, -2, 2, -2,
ax_anim 2, 0, 134, 3, -3, 3, -3,
ax_anim 4, 2, 134, 4, -4, 4, -4,
ax_anim 2, 0, 135, 0, 0, 0, 0,
ax_anim 2, 0, 135, -4, 4, -4, 4,
ax_anim 2, 1, 135, -5, 3, -5, 3,
ax_anim 2, 0, 135, -4, 4, -4, 4,
ax_anim 2, 0, 135, -5, 3, -5, 3,
ax_anim 2, 0, 135, -4, 4, -4, 4,
ax_anim 2, 0, 135, -5, 3, -5, 3,
ax_anim 2, 0, 133, -2, 2, -2, 2,
ax_anim_terminator
.align 2
sPersianAnims_5_1:
ax_anim 2, 0, 136, 1, 0, 1, 0,
ax_anim 2, 0, 136, 0, 0, 0, 0,
ax_anim 2, 0, 136, 1, 0, 1, 0,
ax_anim 2, 0, 136, 0, 0, 0, 0,
ax_anim 2, 0, 136, 1, 0, 1, 0,
ax_anim 2, 2, 136, 0, 0, 0, 0,
ax_anim 2, 0, 136, 1, 0, 1, 0,
ax_anim 2, 0, 136, 0, 0, 0, 0,
ax_anim 2, 0, 136, 1, 0, 1, 0,
ax_anim 2, 1, 136, 0, 0, 0, 0,
ax_anim_terminator
sPersianAnims_5_2:
ax_anim 2, 0, 143, 1, -1, 1, -1,
ax_anim 2, 0, 143, 0, 0, 0, 0,
ax_anim 2, 0, 143, 1, -1, 1, -1,
ax_anim 2, 0, 143, 0, 0, 0, 0,
ax_anim 2, 0, 143, 1, -1, 1, -1,
ax_anim 2, 2, 143, 0, 0, 0, 0,
ax_anim 2, 0, 143, 1, -1, 1, -1,
ax_anim 2, 0, 143, 0, 0, 0, 0,
ax_anim 2, 0, 143, 1, -1, 1, -1,
ax_anim 2, 1, 143, 0, 0, 0, 0,
ax_anim_terminator
sPersianAnims_5_3:
ax_anim 2, 0, 142, 0, -1, 0, -1,
ax_anim 2, 0, 142, 0, 0, 0, 0,
ax_anim 2, 0, 142, 0, -1, 0, -1,
ax_anim 2, 0, 142, 0, 0, 0, 0,
ax_anim 2, 0, 142, 0, -1, 0, -1,
ax_anim 2, 2, 142, 0, 0, 0, 0,
ax_anim 2, 0, 142, 0, -1, 0, -1,
ax_anim 2, 0, 142, 0, 0, 0, 0,
ax_anim 2, 0, 142, 0, -1, 0, -1,
ax_anim 2, 1, 142, 0, 0, 0, 0,
ax_anim_terminator
sPersianAnims_5_4:
ax_anim 2, 0, 141, -1, -1, -1, -1,
ax_anim 2, 0, 141, 0, 0, 0, 0,
ax_anim 2, 0, 141, -1, -1, -1, -1,
ax_anim 2, 0, 141, 0, 0, 0, 0,
ax_anim 2, 0, 141, -1, -1, -1, -1,
ax_anim 2, 2, 141, 0, 0, 0, 0,
ax_anim 2, 0, 141, -1, -1, -1, -1,
ax_anim 2, 0, 141, 0, 0, 0, 0,
ax_anim 2, 0, 141, -1, -1, -1, -1,
ax_anim 2, 1, 141, 0, 0, 0, 0,
ax_anim_terminator
sPersianAnims_5_5:
ax_anim 2, 0, 140, 1, 0, 1, 0,
ax_anim 2, 0, 140, 0, 0, 0, 0,
ax_anim 2, 0, 140, 1, 0, 1, 0,
ax_anim 2, 0, 140, 0, 0, 0, 0,
ax_anim 2, 0, 140, 1, 0, 1, 0,
ax_anim 2, 2, 140, 0, 0, 0, 0,
ax_anim 2, 0, 140, 1, 0, 1, 0,
ax_anim 2, 0, 140, 0, 0, 0, 0,
ax_anim 2, 0, 140, 1, 0, 1, 0,
ax_anim 2, 1, 140, 0, 0, 0, 0,
ax_anim_terminator
sPersianAnims_5_6:
ax_anim 2, 0, 139, 1, -1, 1, -1,
ax_anim 2, 0, 139, 0, 0, 0, 0,
ax_anim 2, 0, 139, 1, -1, 1, -1,
ax_anim 2, 0, 139, 0, 0, 0, 0,
ax_anim 2, 0, 139, 1, -1, 1, -1,
ax_anim 2, 2, 139, 0, 0, 0, 0,
ax_anim 2, 0, 139, 1, -1, 1, -1,
ax_anim 2, 0, 139, 0, 0, 0, 0,
ax_anim 2, 0, 139, 1, -1, 1, -1,
ax_anim 2, 1, 139, 0, 0, 0, 0,
ax_anim_terminator
sPersianAnims_5_7:
ax_anim 2, 0, 138, 0, -1, 0, -1,
ax_anim 2, 0, 138, 0, 0, 0, 0,
ax_anim 2, 0, 138, 0, -1, 0, -1,
ax_anim 2, 0, 138, 0, 0, 0, 0,
ax_anim 2, 0, 138, 0, -1, 0, -1,
ax_anim 2, 2, 138, 0, 0, 0, 0,
ax_anim 2, 0, 138, 0, -1, 0, -1,
ax_anim 2, 0, 138, 0, 0, 0, 0,
ax_anim 2, 0, 138, 0, -1, 0, -1,
ax_anim 2, 1, 138, 0, 0, 0, 0,
ax_anim_terminator
sPersianAnims_5_8:
ax_anim 2, 0, 137, -1, -1, -1, -1,
ax_anim 2, 0, 137, 0, 0, 0, 0,
ax_anim 2, 0, 137, -1, -1, -1, -1,
ax_anim 2, 0, 137, 0, 0, 0, 0,
ax_anim 2, 0, 137, -1, -1, -1, -1,
ax_anim 2, 2, 137, 0, 0, 0, 0,
ax_anim 2, 0, 137, -1, -1, -1, -1,
ax_anim 2, 0, 137, 0, 0, 0, 0,
ax_anim 2, 0, 137, -1, -1, -1, -1,
ax_anim 2, 1, 137, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sPersianAnims_6_1:
ax_anim 30, 0, 144, 0, 0, 0, 0,
ax_anim 35, 0, 145, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sPersianAnims_7_1:
ax_anim 2, 0, 146, 0, -2, 0, -2,
ax_anim 8, 0, 146, 0, -3, 0, -3,
ax_anim_terminator
sPersianAnims_7_2:
ax_anim 2, 0, 147, -2, -2, -2, -2,
ax_anim 8, 0, 147, -3, -3, -3, -3,
ax_anim_terminator
sPersianAnims_7_3:
ax_anim 2, 0, 148, -2, 0, -2, 0,
ax_anim 8, 0, 148, -3, 0, -3, 0,
ax_anim_terminator
sPersianAnims_7_4:
ax_anim 2, 0, 149, -2, 2, -2, 2,
ax_anim 8, 0, 149, -3, 3, -3, 3,
ax_anim_terminator
sPersianAnims_7_5:
ax_anim 2, 0, 150, 0, 2, 0, 2,
ax_anim 8, 0, 150, 0, 3, 0, 3,
ax_anim_terminator
sPersianAnims_7_6:
ax_anim 2, 0, 151, 2, 2, 2, 2,
ax_anim 8, 0, 151, 3, 3, 3, 3,
ax_anim_terminator
sPersianAnims_7_7:
ax_anim 2, 0, 152, 2, 0, 2, 0,
ax_anim 8, 0, 152, 3, 0, 3, 0,
ax_anim_terminator
sPersianAnims_7_8:
ax_anim 2, 0, 153, 2, -2, 2, -2,
ax_anim 8, 0, 153, 3, -3, 3, -3,
ax_anim_terminator
.align 2
sPersianAnims_8_1:
ax_anim 8, 0, 155, 0, 0, 0, 0,
ax_anim_terminator
sPersianAnims_8_2:
ax_anim 8, 0, 157, 0, 0, 0, 0,
ax_anim_terminator
sPersianAnims_8_3:
ax_anim 8, 0, 159, 0, 0, 0, 0,
ax_anim_terminator
sPersianAnims_8_4:
ax_anim 8, 0, 161, 0, 0, 0, 0,
ax_anim_terminator
sPersianAnims_8_5:
ax_anim 8, 0, 163, 0, 0, 0, 0,
ax_anim_terminator
sPersianAnims_8_6:
ax_anim 8, 0, 165, 0, 0, 0, 0,
ax_anim_terminator
sPersianAnims_8_7:
ax_anim 8, 0, 167, 0, 0, 0, 0,
ax_anim_terminator
sPersianAnims_8_8:
ax_anim 8, 0, 169, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sPersianAnims_9_1:
ax_anim 2, 0, 170, 0, 0, 0, 0,
ax_anim 1, 0, 171, 6, 3, 6, 3,
ax_anim 2, 0, 172, 8, 9, 8, 9,
ax_anim 2, 0, 173, 7, 14, 7, 14,
ax_anim 3, 0, 174, 0, 18, 0, 18,
ax_anim 2, 3, 175, -7, 14, -7, 14,
ax_anim 2, 0, 176, -8, 9, -8, 9,
ax_anim 1, 0, 177, -6, 3, -6, 3,
ax_anim 1, 0, 170, 0, 0, 0, 0,
ax_anim_terminator
sPersianAnims_9_2:
ax_anim 2, 0, 177, 0, 0, 0, 0,
ax_anim 1, 0, 170, 8, 0, 8, 0,
ax_anim 2, 0, 171, 16, 3, 16, 3,
ax_anim 2, 0, 172, 20, 12, 20, 12,
ax_anim 3, 0, 173, 18, 19, 18, 19,
ax_anim 2, 3, 174, 11, 21, 11, 21,
ax_anim 2, 0, 175, 3, 15, 3, 15,
ax_anim 1, 0, 176, -1, 9, -1, 9,
ax_anim 1, 0, 177, 0, 0, 0, 0,
ax_anim_terminator
sPersianAnims_9_3:
ax_anim 2, 0, 176, 0, 0, 0, 0,
ax_anim 1, 0, 177, 3, -5, 3, -5,
ax_anim 2, 0, 170, 11, -6, 11, -6,
ax_anim 2, 0, 171, 17, -7, 17, -7,
ax_anim 3, 0, 172, 19, -2, 19, -2,
ax_anim 2, 3, 173, 18, 4, 18, 4,
ax_anim 2, 0, 174, 12, 7, 12, 7,
ax_anim 1, 0, 175, 4, 5, 4, 5,
ax_anim 1, 0, 176, 0, 0, 0, 0,
ax_anim_terminator
sPersianAnims_9_4:
ax_anim 2, 0, 175, 0, 0, 0, 0,
ax_anim 1, 0, 176, -1, -6, -1, -6,
ax_anim 2, 0, 177, 4, -16, 4, -16,
ax_anim 2, 0, 170, 12, -20, 12, -20,
ax_anim 3, 0, 171, 19, -20, 19, -20,
ax_anim 2, 3, 172, 22, -12, 22, -12,
ax_anim 2, 0, 173, 17, -4, 17, -4,
ax_anim 1, 0, 174, 7, 1, 7, 1,
ax_anim 1, 0, 175, 0, 0, 0, 0,
ax_anim_terminator
sPersianAnims_9_5:
ax_anim 2, 0, 174, 0, 0, 0, 0,
ax_anim 1, 0, 175, -8, -4, -8, -4,
ax_anim 2, 0, 176, -9, -12, -9, -12,
ax_anim 2, 0, 177, -7, -18, -7, -18,
ax_anim 3, 0, 170, 0, -22, 0, -22,
ax_anim 2, 3, 171, 7, -18, 7, -18,
ax_anim 2, 0, 172, 9, -10, 9, -10,
ax_anim 1, 0, 173, 8, -4, 8, -4,
ax_anim 1, 0, 174, 0, 0, 0, 0,
ax_anim_terminator
sPersianAnims_9_6:
ax_anim 2, 0, 173, 0, 0, 0, 0,
ax_anim 1, 0, 172, 1, -6, 1, -6,
ax_anim 2, 0, 171, -4, -16, -4, -16,
ax_anim 2, 0, 170, -12, -20, -12, -20,
ax_anim 3, 0, 177, -19, -20, -19, -20,
ax_anim 2, 3, 176, -22, -12, -22, -12,
ax_anim 2, 0, 175, -17, -4, -17, -4,
ax_anim 1, 0, 174, -7, -1, -7, -1,
ax_anim 1, 0, 173, 0, 0, 0, 0,
ax_anim_terminator
sPersianAnims_9_7:
ax_anim 2, 0, 172, 0, 0, 0, 0,
ax_anim 1, 0, 171, -3, -5, -3, -5,
ax_anim 2, 0, 170, -11, -6, -11, -6,
ax_anim 2, 0, 177, -17, -7, -17, -7,
ax_anim 3, 0, 176, -19, -2, -19, -2,
ax_anim 2, 3, 175, -18, 4, -18, 4,
ax_anim 2, 0, 174, -12, 7, -12, 7,
ax_anim 1, 0, 173, -4, 5, -4, 5,
ax_anim 1, 0, 172, 0, 0, 0, 0,
ax_anim_terminator
sPersianAnims_9_8:
ax_anim 2, 0, 171, 0, 0, 0, 0,
ax_anim 1, 0, 170, -8, 0, -8, 0,
ax_anim 2, 0, 177, -16, 3, -16, 3,
ax_anim 2, 0, 176, -20, 12, -20, 12,
ax_anim 3, 0, 175, -18, 19, -18, 19,
ax_anim 2, 3, 174, -11, 21, -11, 21,
ax_anim 2, 0, 173, -3, 15, -3, 15,
ax_anim 1, 0, 172, 1, 9, 1, 9,
ax_anim 1, 0, 171, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sPersianAnims_10_1:
ax_anim 2, 0, 178, 0, 0, 0, 0,
ax_anim 2, 0, 178, 6, 0, 6, 0,
ax_anim 2, 0, 178, -6, 0, -6, 0,
ax_anim 2, 0, 178, 10, 0, 10, 0,
ax_anim 2, 0, 178, -10, 0, -10, 0,
ax_anim 2, 0, 178, 12, 0, 12, 0,
ax_anim 3, 0, 178, -12, 0, -12, 0,
ax_anim 3, 0, 178, 13, 0, 13, 0,
ax_anim 3, 0, 178, -13, 0, -13, 0,
ax_anim 2, 0, 178, 12, 0, 12, 0,
ax_anim 3, 0, 178, -12, 0, -12, 0,
ax_anim 2, 0, 178, 10, 0, 10, 0,
ax_anim 2, 0, 178, -10, 0, -10, 0,
ax_anim 2, 0, 178, 6, 0, 6, 0,
ax_anim 2, 0, 178, -6, 0, -6, 0,
ax_anim 2, 0, 178, 0, 0, 0, 0,
ax_anim_terminator
sPersianAnims_10_2:
ax_anim 2, 0, 179, 0, 0, 0, 0,
ax_anim 2, 0, 179, 6, -6, 6, -6,
ax_anim 2, 0, 179, -6, 6, -6, 6,
ax_anim 2, 0, 179, 10, -10, 10, -10,
ax_anim 2, 0, 179, -10, 10, -10, 10,
ax_anim 2, 0, 179, 12, -12, 12, -12,
ax_anim 3, 0, 179, -12, 12, -12, 12,
ax_anim 3, 0, 179, 13, -13, 13, -13,
ax_anim 3, 0, 179, -13, 13, -13, 13,
ax_anim 2, 0, 179, 12, -12, 12, -12,
ax_anim 3, 0, 179, -12, 12, -12, 12,
ax_anim 2, 0, 179, 10, -10, 10, -10,
ax_anim 2, 0, 179, -10, 10, -10, 10,
ax_anim 2, 0, 179, 6, -6, 6, -6,
ax_anim 2, 0, 179, -6, 6, -6, 6,
ax_anim 2, 0, 179, 0, 0, 0, 0,
ax_anim_terminator
sPersianAnims_10_3:
ax_anim 2, 0, 180, 0, 0, 0, 0,
ax_anim 2, 0, 180, 0, -6, 0, -6,
ax_anim 2, 0, 180, 0, 6, 0, 6,
ax_anim 2, 0, 180, 0, -10, 0, -10,
ax_anim 2, 0, 180, 0, 10, 0, 10,
ax_anim 2, 0, 180, 0, -12, 0, -12,
ax_anim 3, 0, 180, 0, 12, 0, 12,
ax_anim 3, 0, 180, 0, -13, 0, -13,
ax_anim 3, 0, 180, 0, 13, 0, 13,
ax_anim 2, 0, 180, 0, -12, 0, -12,
ax_anim 3, 0, 180, 0, 12, 0, 12,
ax_anim 2, 0, 180, 0, -10, 0, -10,
ax_anim 2, 0, 180, 0, 10, 0, 10,
ax_anim 2, 0, 180, 0, -6, 0, -6,
ax_anim 2, 0, 180, 0, 6, 0, 6,
ax_anim 2, 0, 180, 0, 0, 0, 0,
ax_anim_terminator
sPersianAnims_10_4:
ax_anim 2, 0, 181, 0, 0, 0, 0,
ax_anim 2, 0, 181, -6, -6, -6, -6,
ax_anim 2, 0, 181, 6, 6, 6, 6,
ax_anim 2, 0, 181, -10, -10, -10, -10,
ax_anim 2, 0, 181, 10, 10, 10, 10,
ax_anim 2, 0, 181, -12, -12, -12, -12,
ax_anim 3, 0, 181, 12, 12, 12, 12,
ax_anim 3, 0, 181, -13, -13, -13, -13,
ax_anim 3, 0, 181, 13, 13, 13, 13,
ax_anim 2, 0, 181, -12, -12, -12, -12,
ax_anim 3, 0, 181, 12, 12, 12, 12,
ax_anim 2, 0, 181, -10, -10, -10, -10,
ax_anim 2, 0, 181, 10, 10, 10, 10,
ax_anim 2, 0, 181, -6, -6, -6, -6,
ax_anim 2, 0, 181, 6, 6, 6, 6,
ax_anim 2, 0, 181, 0, 0, 0, 0,
ax_anim_terminator
sPersianAnims_10_5:
ax_anim 2, 0, 182, 0, 0, 0, 0,
ax_anim 2, 0, 182, 6, 0, 6, 0,
ax_anim 2, 0, 182, -6, 0, -6, 0,
ax_anim 2, 0, 182, 10, 0, 10, 0,
ax_anim 2, 0, 182, -10, 0, -10, 0,
ax_anim 2, 0, 182, 12, 0, 12, 0,
ax_anim 3, 0, 182, -12, 0, -12, 0,
ax_anim 3, 0, 182, 13, 0, 13, 0,
ax_anim 3, 0, 182, -13, 0, -13, 0,
ax_anim 2, 0, 182, 12, 0, 12, 0,
ax_anim 3, 0, 182, -12, 0, -12, 0,
ax_anim 2, 0, 182, 10, 0, 10, 0,
ax_anim 2, 0, 182, -10, 0, -10, 0,
ax_anim 2, 0, 182, 6, 0, 6, 0,
ax_anim 2, 0, 182, -6, 0, -6, 0,
ax_anim 2, 0, 182, 0, 0, 0, 0,
ax_anim_terminator
sPersianAnims_10_6:
ax_anim 2, 0, 183, 0, 0, 0, 0,
ax_anim 2, 0, 183, 6, -6, 6, -6,
ax_anim 2, 0, 183, -6, 6, -6, 6,
ax_anim 2, 0, 183, 10, -10, 10, -10,
ax_anim 2, 0, 183, -10, 10, -10, 10,
ax_anim 2, 0, 183, 12, -12, 12, -12,
ax_anim 3, 0, 183, -12, 12, -12, 12,
ax_anim 3, 0, 183, 13, -13, 13, -13,
ax_anim 3, 0, 183, -13, 13, -13, 13,
ax_anim 2, 0, 183, 12, -12, 12, -12,
ax_anim 3, 0, 183, -12, 12, -12, 12,
ax_anim 2, 0, 183, 10, -10, 10, -10,
ax_anim 2, 0, 183, -10, 10, -10, 10,
ax_anim 2, 0, 183, 6, -6, 6, -6,
ax_anim 2, 0, 183, -6, 6, -6, 6,
ax_anim 2, 0, 183, 0, 0, 0, 0,
ax_anim_terminator
sPersianAnims_10_7:
ax_anim 2, 0, 184, 0, 0, 0, 0,
ax_anim 2, 0, 184, 0, -6, 0, -6,
ax_anim 2, 0, 184, 0, 6, 0, 6,
ax_anim 2, 0, 184, 0, -10, 0, -10,
ax_anim 2, 0, 184, 0, 10, 0, 10,
ax_anim 2, 0, 184, 0, -12, 0, -12,
ax_anim 3, 0, 184, 0, 12, 0, 12,
ax_anim 3, 0, 184, 0, -13, 0, -13,
ax_anim 3, 0, 184, 0, 13, 0, 13,
ax_anim 2, 0, 184, 0, -12, 0, -12,
ax_anim 3, 0, 184, 0, 12, 0, 12,
ax_anim 2, 0, 184, 0, -10, 0, -10,
ax_anim 2, 0, 184, 0, 10, 0, 10,
ax_anim 2, 0, 184, 0, -6, 0, -6,
ax_anim 2, 0, 184, 0, 6, 0, 6,
ax_anim 2, 0, 184, 0, 0, 0, 0,
ax_anim_terminator
sPersianAnims_10_8:
ax_anim 2, 0, 185, 0, 0, 0, 0,
ax_anim 2, 0, 185, -6, -6, -6, -6,
ax_anim 2, 0, 185, 6, 6, 6, 6,
ax_anim 2, 0, 185, -10, -10, -10, -10,
ax_anim 2, 0, 185, 10, 10, 10, 10,
ax_anim 2, 0, 185, -12, -12, -12, -12,
ax_anim 3, 0, 185, 12, 12, 12, 12,
ax_anim 3, 0, 185, -13, -13, -13, -13,
ax_anim 3, 0, 185, 13, 13, 13, 13,
ax_anim 2, 0, 185, -12, -12, -12, -12,
ax_anim 3, 0, 185, 12, 12, 12, 12,
ax_anim 2, 0, 185, -10, -10, -10, -10,
ax_anim 2, 0, 185, 10, 10, 10, 10,
ax_anim 2, 0, 185, -6, -6, -6, -6,
ax_anim 2, 0, 185, 6, 6, 6, 6,
ax_anim 2, 0, 185, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sPersianAnims_11_1:
ax_anim 2, 0, 186, 0, 0, 0, 0,
ax_anim 1, 0, 187, 0, -10, 0, 0,
ax_anim 2, 0, 187, 0, -16, 0, 0,
ax_anim 3, 0, 187, 0, -20, 0, 0,
ax_anim 4, 0, 187, 0, -21, 0, 0,
ax_anim 4, 0, 188, 0, -23, 0, 0,
ax_anim 3, 0, 188, 0, -22, 0, 0,
ax_anim 2, 0, 188, 0, -18, 0, 0,
ax_anim 1, 0, 188, 0, -12, 0, 0,
ax_anim 2, 2, 188, 0, 0, 0, 0,
ax_anim_terminator
sPersianAnims_11_2:
ax_anim 2, 0, 189, 0, 0, 0, 0,
ax_anim 1, 0, 190, 0, -10, 0, 0,
ax_anim 2, 0, 190, 0, -16, 0, 0,
ax_anim 3, 0, 190, 0, -20, 0, 0,
ax_anim 4, 0, 190, 0, -21, 0, 0,
ax_anim 4, 0, 191, 0, -23, 0, 0,
ax_anim 3, 0, 191, 0, -22, 0, 0,
ax_anim 2, 0, 191, 0, -18, 0, 0,
ax_anim 1, 0, 191, 0, -12, 0, 0,
ax_anim 2, 2, 191, 0, 0, 0, 0,
ax_anim_terminator
sPersianAnims_11_3:
ax_anim 2, 0, 192, 0, 0, 0, 0,
ax_anim 1, 0, 193, 0, -10, 0, 0,
ax_anim 2, 0, 193, 0, -16, 0, 0,
ax_anim 3, 0, 193, 0, -20, 0, 0,
ax_anim 4, 0, 193, 0, -21, 0, 0,
ax_anim 4, 0, 194, 0, -23, 0, 0,
ax_anim 3, 0, 194, 0, -22, 0, 0,
ax_anim 2, 0, 194, 0, -18, 0, 0,
ax_anim 1, 0, 194, 0, -12, 0, 0,
ax_anim 2, 2, 194, 0, 0, 0, 0,
ax_anim_terminator
sPersianAnims_11_4:
ax_anim 2, 0, 195, 0, 0, 0, 0,
ax_anim 1, 0, 196, 0, -10, 0, 0,
ax_anim 2, 0, 196, 0, -16, 0, 0,
ax_anim 3, 0, 196, 0, -20, 0, 0,
ax_anim 4, 0, 196, 0, -21, 0, 0,
ax_anim 4, 0, 197, 0, -22, 0, 0,
ax_anim 3, 0, 197, 0, -21, 0, 0,
ax_anim 2, 0, 197, 0, -17, 0, 0,
ax_anim 1, 0, 197, 0, -11, 0, 0,
ax_anim 2, 2, 197, 0, 0, 0, 0,
ax_anim_terminator
sPersianAnims_11_5:
ax_anim 2, 0, 198, 0, 0, 0, 0,
ax_anim 1, 0, 199, 0, -10, 0, 0,
ax_anim 2, 0, 199, 0, -16, 0, 0,
ax_anim 3, 0, 199, 0, -20, 0, 0,
ax_anim 4, 0, 199, 0, -21, 0, 0,
ax_anim 4, 0, 200, 0, -23, 0, 0,
ax_anim 3, 0, 200, 0, -22, 0, 0,
ax_anim 2, 0, 200, 0, -18, 0, 0,
ax_anim 1, 0, 200, 0, -12, 0, 0,
ax_anim 2, 2, 200, 0, 0, 0, 0,
ax_anim_terminator
sPersianAnims_11_6:
ax_anim 2, 0, 201, 0, 0, 0, 0,
ax_anim 1, 0, 202, 0, -10, 0, 0,
ax_anim 2, 0, 202, 0, -16, 0, 0,
ax_anim 3, 0, 202, 0, -20, 0, 0,
ax_anim 4, 0, 202, 0, -21, 0, 0,
ax_anim 4, 0, 203, 0, -22, 0, 0,
ax_anim 3, 0, 203, 0, -21, 0, 0,
ax_anim 2, 0, 203, 0, -17, 0, 0,
ax_anim 1, 0, 203, 0, -11, 0, 0,
ax_anim 2, 2, 203, 0, 0, 0, 0,
ax_anim_terminator
sPersianAnims_11_7:
ax_anim 2, 0, 204, 0, 0, 0, 0,
ax_anim 1, 0, 205, 0, -10, 0, 0,
ax_anim 2, 0, 205, 0, -16, 0, 0,
ax_anim 3, 0, 205, 0, -20, 0, 0,
ax_anim 4, 0, 205, 0, -21, 0, 0,
ax_anim 4, 0, 206, 0, -23, 0, 0,
ax_anim 3, 0, 206, 0, -22, 0, 0,
ax_anim 2, 0, 206, 0, -18, 0, 0,
ax_anim 1, 0, 206, 0, -12, 0, 0,
ax_anim 2, 2, 206, 0, 0, 0, 0,
ax_anim_terminator
sPersianAnims_11_8:
ax_anim 2, 0, 207, 0, 0, 0, 0,
ax_anim 1, 0, 208, 0, -10, 0, 0,
ax_anim 2, 0, 208, 0, -16, 0, 0,
ax_anim 3, 0, 208, 0, -20, 0, 0,
ax_anim 4, 0, 208, 0, -21, 0, 0,
ax_anim 4, 0, 209, 0, -23, 0, 0,
ax_anim 3, 0, 209, 0, -22, 0, 0,
ax_anim 2, 0, 209, 0, -18, 0, 0,
ax_anim 1, 0, 209, 0, -12, 0, 0,
ax_anim 2, 2, 209, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sPersianAnims_12_1:
ax_anim 2, 0, 210, 1, 0, 1, 0,
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 2, 0, 210, 1, 0, 1, 0,
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 2, 0, 210, 1, 0, 1, 0,
ax_anim 2, 2, 210, 0, 0, 0, 0,
ax_anim 2, 0, 210, 1, 0, 1, 0,
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 2, 0, 210, 1, 0, 1, 0,
ax_anim 2, 1, 210, 0, 0, 0, 0,
ax_anim_terminator
sPersianAnims_12_2:
ax_anim 2, 0, 217, 1, -1, 1, -1,
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 0, 217, 1, -1, 1, -1,
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 0, 217, 1, -1, 1, -1,
ax_anim 2, 2, 217, 0, 0, 0, 0,
ax_anim 2, 0, 217, 1, -1, 1, -1,
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 0, 217, 1, -1, 1, -1,
ax_anim 2, 1, 217, 0, 0, 0, 0,
ax_anim_terminator
sPersianAnims_12_3:
ax_anim 2, 0, 216, 0, -1, 0, -1,
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, -1, 0, -1,
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, -1, 0, -1,
ax_anim 2, 2, 216, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, -1, 0, -1,
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, -1, 0, -1,
ax_anim 2, 1, 216, 0, 0, 0, 0,
ax_anim_terminator
sPersianAnims_12_4:
ax_anim 2, 0, 215, -1, -1, -1, -1,
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 0, 215, -1, -1, -1, -1,
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 0, 215, -1, -1, -1, -1,
ax_anim 2, 2, 215, 0, 0, 0, 0,
ax_anim 2, 0, 215, -1, -1, -1, -1,
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 0, 215, -1, -1, -1, -1,
ax_anim 2, 1, 215, 0, 0, 0, 0,
ax_anim_terminator
sPersianAnims_12_5:
ax_anim 2, 0, 214, 1, 0, 1, 0,
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 2, 0, 214, 1, 0, 1, 0,
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 2, 0, 214, 1, 0, 1, 0,
ax_anim 2, 2, 214, 0, 0, 0, 0,
ax_anim 2, 0, 214, 1, 0, 1, 0,
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 2, 0, 214, 1, 0, 1, 0,
ax_anim 2, 1, 214, 0, 0, 0, 0,
ax_anim_terminator
sPersianAnims_12_6:
ax_anim 2, 0, 213, 1, -1, 1, -1,
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 2, 0, 213, 1, -1, 1, -1,
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 2, 0, 213, 1, -1, 1, -1,
ax_anim 2, 2, 213, 0, 0, 0, 0,
ax_anim 2, 0, 213, 1, -1, 1, -1,
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 2, 0, 213, 1, -1, 1, -1,
ax_anim 2, 1, 213, 0, 0, 0, 0,
ax_anim_terminator
sPersianAnims_12_7:
ax_anim 2, 0, 212, 0, -1, 0, -1,
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 2, 0, 212, 0, -1, 0, -1,
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 2, 0, 212, 0, -1, 0, -1,
ax_anim 2, 2, 212, 0, 0, 0, 0,
ax_anim 2, 0, 212, 0, -1, 0, -1,
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 2, 0, 212, 0, -1, 0, -1,
ax_anim 2, 1, 212, 0, 0, 0, 0,
ax_anim_terminator
sPersianAnims_12_8:
ax_anim 2, 0, 211, -1, -1, -1, -1,
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 2, 0, 211, -1, -1, -1, -1,
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 2, 0, 211, -1, -1, -1, -1,
ax_anim 2, 2, 211, 0, 0, 0, 0,
ax_anim 2, 0, 211, -1, -1, -1, -1,
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 2, 0, 211, -1, -1, -1, -1,
ax_anim 2, 1, 211, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sPersianAnims_13_1:
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 2, 2, 218, 0, 0, 0, 0,
ax_anim_terminator
sPersianAnims_13_2:
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 2, 2, 225, 0, 0, 0, 0,
ax_anim_terminator
sPersianAnims_13_3:
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 2, 2, 224, 0, 0, 0, 0,
ax_anim_terminator
sPersianAnims_13_4:
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 2, 223, 0, 0, 0, 0,
ax_anim_terminator
sPersianAnims_13_5:
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 2, 222, 0, 0, 0, 0,
ax_anim_terminator
sPersianAnims_13_6:
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 2, 221, 0, 0, 0, 0,
ax_anim_terminator
sPersianAnims_13_7:
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 2, 220, 0, 0, 0, 0,
ax_anim_terminator
sPersianAnims_13_8:
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 2, 219, 0, 0, 0, 0,
ax_anim_terminator
sPersianGfx1:
.incbin "baserom.gba", 0x748C84, 0x200
sPersianSprites1:
ax_sprite sPersianGfx1, 0x200
ax_sprite_terminator
sPersianGfx2:
.incbin "baserom.gba", 0x748E94, 0x200
sPersianSprites2:
ax_sprite sPersianGfx2, 0x200
ax_sprite_terminator
sPersianGfx3:
.incbin "baserom.gba", 0x7490A4, 0x200
sPersianSprites3:
ax_sprite sPersianGfx3, 0x200
ax_sprite_terminator
sPersianGfx4:
.incbin "baserom.gba", 0x7492B4, 0x200
sPersianSprites4:
ax_sprite sPersianGfx4, 0x200
ax_sprite_terminator
sPersianGfx5:
.incbin "baserom.gba", 0x7494C4, 0x200
sPersianSprites5:
ax_sprite sPersianGfx5, 0x200
ax_sprite_terminator
sPersianGfx6:
.incbin "baserom.gba", 0x7496D4, 0x200
sPersianSprites6:
ax_sprite sPersianGfx6, 0x200
ax_sprite_terminator
sPersianGfx7:
.incbin "baserom.gba", 0x7498E4, 0x200
sPersianSprites7:
ax_sprite sPersianGfx7, 0x200
ax_sprite_terminator
sPersianGfx8:
.incbin "baserom.gba", 0x749AF4, 0x200
sPersianSprites8:
ax_sprite sPersianGfx8, 0x200
ax_sprite_terminator
sPersianGfx9:
.incbin "baserom.gba", 0x749D04, 0x200
sPersianSprites9:
ax_sprite sPersianGfx9, 0x200
ax_sprite_terminator
sPersianGfx10:
.incbin "baserom.gba", 0x749F14, 0x200
sPersianSprites10:
ax_sprite sPersianGfx10, 0x200
ax_sprite_terminator
sPersianGfx11:
.incbin "baserom.gba", 0x74A124, 0x200
sPersianSprites11:
ax_sprite sPersianGfx11, 0x200
ax_sprite_terminator
sPersianGfx12:
.incbin "baserom.gba", 0x74A334, 0x200
sPersianSprites12:
ax_sprite sPersianGfx12, 0x200
ax_sprite_terminator
sPersianGfx13:
.incbin "baserom.gba", 0x74A544, 0x200
sPersianSprites13:
ax_sprite sPersianGfx13, 0x200
ax_sprite_terminator
sPersianGfx14:
.incbin "baserom.gba", 0x74A754, 0x200
sPersianSprites14:
ax_sprite sPersianGfx14, 0x200
ax_sprite_terminator
sPersianGfx15:
.incbin "baserom.gba", 0x74A964, 0x200
sPersianSprites15:
ax_sprite sPersianGfx15, 0x200
ax_sprite_terminator
sPersianGfx16:
.incbin "baserom.gba", 0x74AB74, 0x40
sPersianGfx16_1:
.incbin "baserom.gba", 0x74ABB4, 0x40
sPersianGfx16_2:
.incbin "baserom.gba", 0x74ABF4, 0x60
sPersianGfx16_3:
.incbin "baserom.gba", 0x74AC54, 0x60
sPersianSprites16:
ax_sprite 0, 0x20
ax_sprite sPersianGfx16, 0x40
ax_sprite 0, 0x40
ax_sprite sPersianGfx16_1, 0x40
ax_sprite 0, 0x20
ax_sprite sPersianGfx16_2, 0x60
ax_sprite 0, 0x20
ax_sprite sPersianGfx16_3, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sPersianGfx17:
.incbin "baserom.gba", 0x74AD04, 0x40
sPersianGfx17_1:
.incbin "baserom.gba", 0x74AD44, 0x40
sPersianGfx17_2:
.incbin "baserom.gba", 0x74AD84, 0x60
sPersianSprites17:
ax_sprite 0, 0x20
ax_sprite sPersianGfx17, 0x40
ax_sprite 0, 0x40
ax_sprite sPersianGfx17_1, 0x40
ax_sprite 0, 0x20
ax_sprite sPersianGfx17_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sPersianGfx18:
.incbin "baserom.gba", 0x74AE24, 0x1C0
sPersianSprites18:
ax_sprite 0, 0x20
ax_sprite sPersianGfx18, 0x1c0
ax_sprite 0, 0x20
ax_sprite_terminator
sPersianGfx19:
.incbin "baserom.gba", 0x74B004, 0x40
sPersianGfx19_1:
.incbin "baserom.gba", 0x74B044, 0x100
sPersianSprites19:
ax_sprite sPersianGfx19, 0x40
ax_sprite 0, 0x40
ax_sprite sPersianGfx19_1, 0x100
ax_sprite 0, 0x80
ax_sprite_terminator
sPersianGfx20:
.incbin "baserom.gba", 0x74B16C, 0x40
sPersianGfx20_1:
.incbin "baserom.gba", 0x74B1AC, 0x140
sPersianSprites20:
ax_sprite 0, 0x40
ax_sprite sPersianGfx20, 0x40
ax_sprite 0, 0x40
ax_sprite sPersianGfx20_1, 0x140
ax_sprite_terminator
sPersianGfx21:
.incbin "baserom.gba", 0x74B314, 0x40
sPersianGfx21_1:
.incbin "baserom.gba", 0x74B354, 0x80
sPersianSprites21:
ax_sprite sPersianGfx21, 0x40
ax_sprite 0, 0x40
ax_sprite sPersianGfx21_1, 0x80
ax_sprite_terminator
sPersianGfx22:
.incbin "baserom.gba", 0x74B3F4, 0x80
sPersianSprites22:
ax_sprite sPersianGfx22, 0x80
ax_sprite_terminator
sPersianGfx23:
.incbin "baserom.gba", 0x74B484, 0x20
sPersianSprites23:
ax_sprite sPersianGfx23, 0x20
ax_sprite_terminator
sPersianGfx24:
.incbin "baserom.gba", 0x74B4B4, 0x1A0
sPersianSprites24:
ax_sprite 0, 0x60
ax_sprite sPersianGfx24, 0x1a0
ax_sprite_terminator
sPersianGfx25:
.incbin "baserom.gba", 0x74B66C, 0x60
sPersianGfx25_1:
.incbin "baserom.gba", 0x74B6CC, 0x80
sPersianGfx25_2:
.incbin "baserom.gba", 0x74B74C, 0x60
sPersianGfx25_3:
.incbin "baserom.gba", 0x74B7AC, 0x40
sPersianSprites25:
ax_sprite sPersianGfx25, 0x60
ax_sprite 0, 0x20
ax_sprite sPersianGfx25_1, 0x80
ax_sprite 0, 0x20
ax_sprite sPersianGfx25_2, 0x60
ax_sprite 0, 0x40
ax_sprite sPersianGfx25_3, 0x40
ax_sprite_terminator
sPersianGfx26:
.incbin "baserom.gba", 0x74B82C, 0x60
sPersianGfx26_1:
.incbin "baserom.gba", 0x74B88C, 0x40
sPersianGfx26_2:
.incbin "baserom.gba", 0x74B8CC, 0x40
sPersianSprites26:
ax_sprite 0, 0x80
ax_sprite sPersianGfx26, 0x60
ax_sprite 0, 0x40
ax_sprite sPersianGfx26_1, 0x40
ax_sprite 0, 0x40
ax_sprite sPersianGfx26_2, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sPersianGfx27:
.incbin "baserom.gba", 0x74B94C, 0x60
sPersianGfx27_1:
.incbin "baserom.gba", 0x74B9AC, 0x40
sPersianGfx27_2:
.incbin "baserom.gba", 0x74B9EC, 0x40
sPersianGfx27_3:
.incbin "baserom.gba", 0x74BA2C, 0x40
sPersianSprites27:
ax_sprite sPersianGfx27, 0x60
ax_sprite 0, 0x40
ax_sprite sPersianGfx27_1, 0x40
ax_sprite 0, 0x40
ax_sprite sPersianGfx27_2, 0x40
ax_sprite 0, 0x40
ax_sprite sPersianGfx27_3, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sPersianGfx28:
.incbin "baserom.gba", 0x74BAB4, 0x60
sPersianGfx28_1:
.incbin "baserom.gba", 0x74BB14, 0x60
sPersianGfx28_2:
.incbin "baserom.gba", 0x74BB74, 0x40
sPersianSprites28:
ax_sprite 0, 0x80
ax_sprite sPersianGfx28, 0x60
ax_sprite 0, 0x20
ax_sprite sPersianGfx28_1, 0x60
ax_sprite 0, 0x40
ax_sprite sPersianGfx28_2, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sPersianGfx29:
.incbin "baserom.gba", 0x74BBF4, 0x20
sPersianGfx29_1:
.incbin "baserom.gba", 0x74BC14, 0x20
sPersianGfx29_2:
.incbin "baserom.gba", 0x74BC34, 0x40
sPersianGfx29_3:
.incbin "baserom.gba", 0x74BC74, 0x60
sPersianSprites29:
ax_sprite sPersianGfx29, 0x20
ax_sprite 0, 0x60
ax_sprite sPersianGfx29_1, 0x20
ax_sprite 0, 0x60
ax_sprite sPersianGfx29_2, 0x40
ax_sprite 0, 0x40
ax_sprite sPersianGfx29_3, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sPersianGfx30:
.incbin "baserom.gba", 0x74BD1C, 0x40
sPersianGfx30_1:
.incbin "baserom.gba", 0x74BD5C, 0x40
sPersianGfx30_2:
.incbin "baserom.gba", 0x74BD9C, 0x40
sPersianGfx30_3:
.incbin "baserom.gba", 0x74BDDC, 0x40
sPersianSprites30:
ax_sprite 0, 0x20
ax_sprite sPersianGfx30, 0x40
ax_sprite 0, 0x40
ax_sprite sPersianGfx30_1, 0x40
ax_sprite 0, 0x40
ax_sprite sPersianGfx30_2, 0x40
ax_sprite 0, 0x40
ax_sprite sPersianGfx30_3, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sPersianGfx31:
.incbin "baserom.gba", 0x74BE6C, 0x40
sPersianGfx31_1:
.incbin "baserom.gba", 0x74BEAC, 0x100
sPersianGfx31_2:
.incbin "baserom.gba", 0x74BFAC, 0x20
sPersianSprites31:
ax_sprite sPersianGfx31, 0x40
ax_sprite 0, 0x40
ax_sprite sPersianGfx31_1, 0x100
ax_sprite 0, 0x20
ax_sprite sPersianGfx31_2, 0x20
ax_sprite 0, 0x40
ax_sprite_terminator
sPersianGfx32:
.incbin "baserom.gba", 0x74C004, 0x60
sPersianGfx32_1:
.incbin "baserom.gba", 0x74C064, 0x80
sPersianSprites32:
ax_sprite sPersianGfx32, 0x60
ax_sprite 0, 0x20
ax_sprite sPersianGfx32_1, 0x80
ax_sprite_terminator
sPersianGfx33:
.incbin "baserom.gba", 0x74C104, 0x160
sPersianSprites33:
ax_sprite 0, 0x80
ax_sprite sPersianGfx33, 0x160
ax_sprite 0, 0x20
ax_sprite_terminator
sPersianGfx34:
.incbin "baserom.gba", 0x74C284, 0x40
sPersianGfx34_1:
.incbin "baserom.gba", 0x74C2C4, 0x80
sPersianGfx34_2:
.incbin "baserom.gba", 0x74C344, 0x60
sPersianGfx34_3:
.incbin "baserom.gba", 0x74C3A4, 0x40
sPersianSprites34:
ax_sprite sPersianGfx34, 0x40
ax_sprite 0, 0x40
ax_sprite sPersianGfx34_1, 0x80
ax_sprite 0, 0x20
ax_sprite sPersianGfx34_2, 0x60
ax_sprite 0, 0x40
ax_sprite sPersianGfx34_3, 0x40
ax_sprite_terminator
sPersianGfx35:
.incbin "baserom.gba", 0x74C424, 0x100
sPersianSprites35:
ax_sprite sPersianGfx35, 0x100
ax_sprite_terminator
sPersianGfx36:
.incbin "baserom.gba", 0x74C534, 0x20
sPersianSprites36:
ax_sprite sPersianGfx36, 0x20
ax_sprite_terminator
sPersianGfx37:
.incbin "baserom.gba", 0x74C564, 0x180
sPersianSprites37:
ax_sprite 0, 0x80
ax_sprite sPersianGfx37, 0x180
ax_sprite_terminator
sPersianGfx38:
.incbin "baserom.gba", 0x74C6FC, 0x60
sPersianGfx38_1:
.incbin "baserom.gba", 0x74C75C, 0x40
sPersianGfx38_2:
.incbin "baserom.gba", 0x74C79C, 0x60
sPersianGfx38_3:
.incbin "baserom.gba", 0x74C7FC, 0x60
sPersianSprites38:
ax_sprite sPersianGfx38, 0x60
ax_sprite 0, 0x40
ax_sprite sPersianGfx38_1, 0x40
ax_sprite 0, 0x40
ax_sprite sPersianGfx38_2, 0x60
ax_sprite 0, 0x20
ax_sprite sPersianGfx38_3, 0x60
ax_sprite_terminator
sPersianGfx39:
.incbin "baserom.gba", 0x74C89C, 0x60
sPersianGfx39_1:
.incbin "baserom.gba", 0x74C8FC, 0x100
sPersianSprites39:
ax_sprite 0, 0x80
ax_sprite sPersianGfx39, 0x60
ax_sprite 0, 0x20
ax_sprite sPersianGfx39_1, 0x100
ax_sprite_terminator
sPersianGfx40:
.incbin "baserom.gba", 0x74CA24, 0x60
sPersianGfx40_1:
.incbin "baserom.gba", 0x74CA84, 0xA0
sPersianGfx40_2:
.incbin "baserom.gba", 0x74CB24, 0x20
sPersianSprites40:
ax_sprite sPersianGfx40, 0x60
ax_sprite 0, 0x20
ax_sprite sPersianGfx40_1, 0xa0
ax_sprite 0, 0x60
ax_sprite sPersianGfx40_2, 0x20
ax_sprite 0, 0x60
ax_sprite_terminator
sPersianGfx41:
.incbin "baserom.gba", 0x74CB7C, 0x40
sPersianGfx41_1:
.incbin "baserom.gba", 0x74CBBC, 0x60
sPersianGfx41_2:
.incbin "baserom.gba", 0x74CC1C, 0x60
sPersianGfx41_3:
.incbin "baserom.gba", 0x74CC7C, 0x40
sPersianSprites41:
ax_sprite 0, 0x20
ax_sprite sPersianGfx41, 0x40
ax_sprite 0, 0x40
ax_sprite sPersianGfx41_1, 0x60
ax_sprite 0, 0x20
ax_sprite sPersianGfx41_2, 0x60
ax_sprite 0, 0x20
ax_sprite sPersianGfx41_3, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sPersianGfx42:
.incbin "baserom.gba", 0x74CD0C, 0x60
sPersianGfx42_1:
.incbin "baserom.gba", 0x74CD6C, 0x60
sPersianGfx42_2:
.incbin "baserom.gba", 0x74CDCC, 0x40
sPersianSprites42:
ax_sprite 0, 0x80
ax_sprite sPersianGfx42, 0x60
ax_sprite 0, 0x20
ax_sprite sPersianGfx42_1, 0x60
ax_sprite 0, 0x40
ax_sprite sPersianGfx42_2, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sPersianGfx43:
.incbin "baserom.gba", 0x74CE4C, 0x120
sPersianGfx43_1:
.incbin "baserom.gba", 0x74CF6C, 0x40
sPersianSprites43:
ax_sprite 0, 0x20
ax_sprite sPersianGfx43, 0x120
ax_sprite 0, 0x20
ax_sprite sPersianGfx43_1, 0x40
ax_sprite 0, 0x60
ax_sprite_terminator
sPersianGfx44:
.incbin "baserom.gba", 0x74CFDC, 0x40
sPersianGfx44_1:
.incbin "baserom.gba", 0x74D01C, 0x60
sPersianGfx44_2:
.incbin "baserom.gba", 0x74D07C, 0x40
sPersianGfx44_3:
.incbin "baserom.gba", 0x74D0BC, 0x40
sPersianSprites44:
ax_sprite 0, 0x20
ax_sprite sPersianGfx44, 0x40
ax_sprite 0, 0x20
ax_sprite sPersianGfx44_1, 0x60
ax_sprite 0, 0x40
ax_sprite sPersianGfx44_2, 0x40
ax_sprite 0, 0x40
ax_sprite sPersianGfx44_3, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sPersianGfx45:
.incbin "baserom.gba", 0x74D14C, 0x40
sPersianGfx45_1:
.incbin "baserom.gba", 0x74D18C, 0x40
sPersianGfx45_2:
.incbin "baserom.gba", 0x74D1CC, 0x60
sPersianGfx45_3:
.incbin "baserom.gba", 0x74D22C, 0x60
sPersianSprites45:
ax_sprite 0, 0x20
ax_sprite sPersianGfx45, 0x40
ax_sprite 0, 0x40
ax_sprite sPersianGfx45_1, 0x40
ax_sprite 0, 0x20
ax_sprite sPersianGfx45_2, 0x60
ax_sprite 0, 0x20
ax_sprite sPersianGfx45_3, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sPersianGfx46:
.incbin "baserom.gba", 0x74D2DC, 0xE0
sPersianGfx46_1:
.incbin "baserom.gba", 0x74D3BC, 0x60
sPersianGfx46_2:
.incbin "baserom.gba", 0x74D41C, 0x40
sPersianSprites46:
ax_sprite 0, 0x20
ax_sprite sPersianGfx46, 0xe0
ax_sprite 0, 0x20
ax_sprite sPersianGfx46_1, 0x60
ax_sprite 0, 0x20
ax_sprite sPersianGfx46_2, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sPersianGfx47:
.incbin "baserom.gba", 0x74D49C, 0x140
sPersianSprites47:
ax_sprite 0, 0xa0
ax_sprite sPersianGfx47, 0x140
ax_sprite 0, 0x20
ax_sprite_terminator
sPersianGfx48:
.incbin "baserom.gba", 0x74D5FC, 0x100
sPersianGfx48_1:
.incbin "baserom.gba", 0x74D6FC, 0x60
sPersianGfx48_2:
.incbin "baserom.gba", 0x74D75C, 0x60
sPersianSprites48:
ax_sprite sPersianGfx48, 0x100
ax_sprite 0, 0x20
ax_sprite sPersianGfx48_1, 0x60
ax_sprite 0, 0x20
ax_sprite sPersianGfx48_2, 0x60
ax_sprite_terminator
sPersianGfx49:
.incbin "baserom.gba", 0x74D7EC, 0x100
sPersianSprites49:
ax_sprite sPersianGfx49, 0x100
ax_sprite_terminator
sPersianGfx50:
.incbin "baserom.gba", 0x74D8FC, 0x80
sPersianSprites50:
ax_sprite sPersianGfx50, 0x80
ax_sprite_terminator
sPersianGfx51:
.incbin "baserom.gba", 0x74D98C, 0x20
sPersianSprites51:
ax_sprite sPersianGfx51, 0x20
ax_sprite_terminator
sPersianGfx52:
.incbin "baserom.gba", 0x74D9BC, 0x40
sPersianGfx52_1:
.incbin "baserom.gba", 0x74D9FC, 0x80
sPersianGfx52_2:
.incbin "baserom.gba", 0x74DA7C, 0x60
sPersianGfx52_3:
.incbin "baserom.gba", 0x74DADC, 0x60
sPersianSprites52:
ax_sprite 0, 0x20
ax_sprite sPersianGfx52, 0x40
ax_sprite 0, 0x20
ax_sprite sPersianGfx52_1, 0x80
ax_sprite 0, 0x20
ax_sprite sPersianGfx52_2, 0x60
ax_sprite 0, 0x20
ax_sprite sPersianGfx52_3, 0x60
ax_sprite_terminator
sPersianGfx53:
.incbin "baserom.gba", 0x74DB84, 0x100
sPersianGfx53_1:
.incbin "baserom.gba", 0x74DC84, 0x60
sPersianSprites53:
ax_sprite 0, 0x80
ax_sprite sPersianGfx53, 0x100
ax_sprite 0, 0x20
ax_sprite sPersianGfx53_1, 0x60
ax_sprite_terminator
sPersianGfx54:
.incbin "baserom.gba", 0x74DD0C, 0x40
sPersianGfx54_1:
.incbin "baserom.gba", 0x74DD4C, 0x60
sPersianGfx54_2:
.incbin "baserom.gba", 0x74DDAC, 0x40
sPersianGfx54_3:
.incbin "baserom.gba", 0x74DDEC, 0x40
sPersianSprites54:
ax_sprite 0, 0x20
ax_sprite sPersianGfx54, 0x40
ax_sprite 0, 0x20
ax_sprite sPersianGfx54_1, 0x60
ax_sprite 0, 0x40
ax_sprite sPersianGfx54_2, 0x40
ax_sprite 0, 0x40
ax_sprite sPersianGfx54_3, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sPersianGfx55:
.incbin "baserom.gba", 0x74DE7C, 0x40
sPersianGfx55_1:
.incbin "baserom.gba", 0x74DEBC, 0x40
sPersianGfx55_2:
.incbin "baserom.gba", 0x74DEFC, 0x40
sPersianSprites55:
ax_sprite 0, 0xa0
ax_sprite sPersianGfx55, 0x40
ax_sprite 0, 0x40
ax_sprite sPersianGfx55_1, 0x40
ax_sprite 0, 0x40
ax_sprite sPersianGfx55_2, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sPersianGfx56:
.incbin "baserom.gba", 0x74DF7C, 0x100
sPersianSprites56:
ax_sprite sPersianGfx56, 0x100
ax_sprite_terminator
sPersianGfx57:
.incbin "baserom.gba", 0x74E08C, 0x20
sPersianSprites57:
ax_sprite sPersianGfx57, 0x20
ax_sprite_terminator
sPersianGfx58:
.incbin "baserom.gba", 0x74E0BC, 0x60
sPersianGfx58_1:
.incbin "baserom.gba", 0x74E11C, 0x60
sPersianGfx58_2:
.incbin "baserom.gba", 0x74E17C, 0x60
sPersianGfx58_3:
.incbin "baserom.gba", 0x74E1DC, 0x60
sPersianSprites58:
ax_sprite sPersianGfx58, 0x60
ax_sprite 0, 0x20
ax_sprite sPersianGfx58_1, 0x60
ax_sprite 0, 0x40
ax_sprite sPersianGfx58_2, 0x60
ax_sprite 0, 0x20
ax_sprite sPersianGfx58_3, 0x60
ax_sprite_terminator
sPersianGfx59:
.incbin "baserom.gba", 0x74E27C, 0x40
sPersianGfx59_1:
.incbin "baserom.gba", 0x74E2BC, 0x60
sPersianGfx59_2:
.incbin "baserom.gba", 0x74E31C, 0x60
sPersianGfx59_3:
.incbin "baserom.gba", 0x74E37C, 0x60
sPersianSprites59:
ax_sprite sPersianGfx59, 0x40
ax_sprite 0, 0x40
ax_sprite sPersianGfx59_1, 0x60
ax_sprite 0, 0x40
ax_sprite sPersianGfx59_2, 0x60
ax_sprite 0, 0x20
ax_sprite sPersianGfx59_3, 0x60
ax_sprite_terminator
sPersianGfx60:
.incbin "baserom.gba", 0x74E41C, 0x60
sPersianGfx60_1:
.incbin "baserom.gba", 0x74E47C, 0x60
sPersianGfx60_2:
.incbin "baserom.gba", 0x74E4DC, 0x60
sPersianGfx60_3:
.incbin "baserom.gba", 0x74E53C, 0x60
sPersianSprites60:
ax_sprite sPersianGfx60, 0x60
ax_sprite 0, 0x20
ax_sprite sPersianGfx60_1, 0x60
ax_sprite 0, 0x40
ax_sprite sPersianGfx60_2, 0x60
ax_sprite 0, 0x20
ax_sprite sPersianGfx60_3, 0x60
ax_sprite_terminator
sPersianGfx61:
.incbin "baserom.gba", 0x74E5DC, 0x100
sPersianSprites61:
ax_sprite sPersianGfx61, 0x100
ax_sprite_terminator
sPersianGfx62:
.incbin "baserom.gba", 0x74E6EC, 0x40
sPersianSprites62:
ax_sprite sPersianGfx62, 0x40
ax_sprite_terminator
sPersianGfx63:
.incbin "baserom.gba", 0x74E73C, 0x100
sPersianSprites63:
ax_sprite sPersianGfx63, 0x100
ax_sprite_terminator
sPersianGfx64:
.incbin "baserom.gba", 0x74E84C, 0x100
sPersianSprites64:
ax_sprite sPersianGfx64, 0x100
ax_sprite_terminator
sPersianGfx65:
.incbin "baserom.gba", 0x74E95C, 0x200
sPersianSprites65:
ax_sprite sPersianGfx65, 0x200
ax_sprite_terminator
sPersianGfx66:
.incbin "baserom.gba", 0x74EB6C, 0x200
sPersianSprites66:
ax_sprite sPersianGfx66, 0x200
ax_sprite_terminator
sPersianGfx67:
.incbin "baserom.gba", 0x74ED7C, 0x200
sPersianSprites67:
ax_sprite sPersianGfx67, 0x200
ax_sprite_terminator
sPersianGfx68:
.incbin "baserom.gba", 0x74EF8C, 0x200
sPersianSprites68:
ax_sprite sPersianGfx68, 0x200
ax_sprite_terminator
sPersianGfx69:
.incbin "baserom.gba", 0x74F19C, 0x200
sPersianSprites69:
ax_sprite sPersianGfx69, 0x200
ax_sprite_terminator
sAxPosesPersian:
.4byte sPersianPose1
.4byte sPersianPose2
.4byte sPersianPose3
.4byte sPersianPose4
.4byte sPersianPose5
.4byte sPersianPose6
.4byte sPersianPose7
.4byte sPersianPose8
.4byte sPersianPose9
.4byte sPersianPose10
.4byte sPersianPose11
.4byte sPersianPose12
.4byte sPersianPose13
.4byte sPersianPose14
.4byte sPersianPose15
.4byte sPersianPose16
.4byte sPersianPose17
.4byte sPersianPose18
.4byte sPersianPose19
.4byte sPersianPose20
.4byte sPersianPose21
.4byte sPersianPose22
.4byte sPersianPose23
.4byte sPersianPose24
.4byte sPersianPose25
.4byte sPersianPose26
.4byte sPersianPose27
.4byte sPersianPose28
.4byte sPersianPose29
.4byte sPersianPose30
.4byte sPersianPose31
.4byte sPersianPose32
.4byte sPersianPose33
.4byte sPersianPose34
.4byte sPersianPose35
.4byte sPersianPose36
.4byte sPersianPose37
.4byte sPersianPose38
.4byte sPersianPose39
.4byte sPersianPose40
.4byte sPersianPose41
.4byte sPersianPose42
.4byte sPersianPose43
.4byte sPersianPose44
.4byte sPersianPose45
.4byte sPersianPose46
.4byte sPersianPose47
.4byte sPersianPose48
.4byte sPersianPose49
.4byte sPersianPose50
.4byte sPersianPose51
.4byte sPersianPose52
.4byte sPersianPose53
.4byte sPersianPose54
.4byte sPersianPose55
.4byte sPersianPose56
.4byte sPersianPose57
.4byte sPersianPose58
.4byte sPersianPose59
.4byte sPersianPose60
.4byte sPersianPose61
.4byte sPersianPose62
.4byte sPersianPose63
.4byte sPersianPose64
.4byte sPersianPose65
.4byte sPersianPose66
.4byte sPersianPose67
.4byte sPersianPose68
.4byte sPersianPose69
.4byte sPersianPose70
.4byte sPersianPose71
.4byte sPersianPose72
.4byte sPersianPose73
.4byte sPersianPose74
.4byte sPersianPose75
.4byte sPersianPose76
.4byte sPersianPose77
.4byte sPersianPose78
.4byte sPersianPose79
.4byte sPersianPose80
.4byte sPersianPose81
.4byte sPersianPose82
.4byte sPersianPose83
.4byte sPersianPose84
.4byte sPersianPose85
.4byte sPersianPose86
.4byte sPersianPose87
.4byte sPersianPose88
.4byte sPersianPose89
.4byte sPersianPose90
.4byte sPersianPose91
.4byte sPersianPose92
.4byte sPersianPose93
.4byte sPersianPose94
.4byte sPersianPose95
.4byte sPersianPose96
.4byte sPersianPose97
.4byte sPersianPose98
.4byte sPersianPose99
.4byte sPersianPose100
.4byte sPersianPose101
.4byte sPersianPose102
.4byte sPersianPose103
.4byte sPersianPose104
.4byte sPersianPose105
.4byte sPersianPose106
.4byte sPersianPose107
.4byte sPersianPose108
.4byte sPersianPose109
.4byte sPersianPose110
.4byte sPersianPose111
.4byte sPersianPose112
.4byte sPersianPose113
.4byte sPersianPose114
.4byte sPersianPose115
.4byte sPersianPose116
.4byte sPersianPose117
.4byte sPersianPose118
.4byte sPersianPose119
.4byte sPersianPose120
.4byte sPersianPose121
.4byte sPersianPose122
.4byte sPersianPose123
.4byte sPersianPose124
.4byte sPersianPose125
.4byte sPersianPose126
.4byte sPersianPose127
.4byte sPersianPose128
.4byte sPersianPose129
.4byte sPersianPose130
.4byte sPersianPose131
.4byte sPersianPose132
.4byte sPersianPose133
.4byte sPersianPose134
.4byte sPersianPose135
.4byte sPersianPose136
.4byte sPersianPose137
.4byte sPersianPose138
.4byte sPersianPose139
.4byte sPersianPose140
.4byte sPersianPose141
.4byte sPersianPose142
.4byte sPersianPose143
.4byte sPersianPose144
.4byte sPersianPose145
.4byte sPersianPose146
.4byte sPersianPose147
.4byte sPersianPose148
.4byte sPersianPose149
.4byte sPersianPose150
.4byte sPersianPose151
.4byte sPersianPose152
.4byte sPersianPose153
.4byte sPersianPose154
.4byte sPersianPose155
.4byte sPersianPose156
.4byte sPersianPose157
.4byte sPersianPose158
.4byte sPersianPose159
.4byte sPersianPose160
.4byte sPersianPose161
.4byte sPersianPose162
.4byte sPersianPose163
.4byte sPersianPose164
.4byte sPersianPose165
.4byte sPersianPose166
.4byte sPersianPose167
.4byte sPersianPose168
.4byte sPersianPose169
.4byte sPersianPose170
.4byte sPersianPose171
.4byte sPersianPose172
.4byte sPersianPose173
.4byte sPersianPose174
.4byte sPersianPose175
.4byte sPersianPose176
.4byte sPersianPose177
.4byte sPersianPose178
.4byte sPersianPose179
.4byte sPersianPose180
.4byte sPersianPose181
.4byte sPersianPose182
.4byte sPersianPose183
.4byte sPersianPose184
.4byte sPersianPose185
.4byte sPersianPose186
.4byte sPersianPose187
.4byte sPersianPose188
.4byte sPersianPose189
.4byte sPersianPose190
.4byte sPersianPose191
.4byte sPersianPose192
.4byte sPersianPose193
.4byte sPersianPose194
.4byte sPersianPose195
.4byte sPersianPose196
.4byte sPersianPose197
.4byte sPersianPose198
.4byte sPersianPose199
.4byte sPersianPose200
.4byte sPersianPose201
.4byte sPersianPose202
.4byte sPersianPose203
.4byte sPersianPose204
.4byte sPersianPose205
.4byte sPersianPose206
.4byte sPersianPose207
.4byte sPersianPose208
.4byte sPersianPose209
.4byte sPersianPose210
.4byte sPersianPose211
.4byte sPersianPose212
.4byte sPersianPose213
.4byte sPersianPose214
.4byte sPersianPose215
.4byte sPersianPose216
.4byte sPersianPose217
.4byte sPersianPose218
.4byte sPersianPose219
.4byte sPersianPose220
.4byte sPersianPose221
.4byte sPersianPose222
.4byte sPersianPose223
.4byte sPersianPose224
.4byte sPersianPose225
.4byte sPersianPose226
sAxPositionsPersian:
.2byte    0,   -2, 	  -4,    3, 	   2,    0, 	   0,   -9
.2byte   -1,   -1, 	  -4,    2, 	   2,    2, 	  -1,   -8
.2byte   -2,   -2, 	  -4,    0, 	   2,    3, 	  -1,   -9
.2byte    7,   -3, 	   8,    3, 	  -1,    1, 	  -1,  -10
.2byte    8,   -2, 	   7,    2, 	   1,    2, 	  -1,  -10
.2byte    8,   -3, 	   2,   -1, 	   3,    3, 	  -1,  -10
.2byte   12,   -5, 	  10,   -1, 	   3,    0, 	  -1,   -9
.2byte   13,   -4, 	   6,   -2, 	   5,    0, 	  -1,  -10
.2byte   13,   -5, 	   2,   -2, 	   8,    0, 	  -1,   -9
.2byte    7,  -10, 	   5,   -7, 	   3,   -1, 	  -1,   -8
.2byte    7,   -9, 	   1,   -4, 	   6,   -2, 	  -1,   -8
.2byte    6,  -11, 	  -1,   -2, 	   8,   -3, 	  -1,   -8
.2byte   -2,  -14, 	   4,   -9, 	  -4,   -4, 	  -1,  -11
.2byte   -1,  -14, 	   4,   -7, 	  -6,   -7, 	  -1,  -11
.2byte    0,  -14, 	   2,   -4, 	  -6,   -9, 	  -1,  -11
.2byte   -8,  -10, 	  -6,   -7, 	  -4,   -1, 	   0,   -8
.2byte   -8,   -9, 	  -2,   -4, 	  -7,   -2, 	   0,   -8
.2byte   -7,  -11, 	   0,   -2, 	  -9,   -3, 	   0,   -8
.2byte  -13,   -5, 	 -11,   -1, 	  -4,    0, 	   0,   -9
.2byte  -14,   -4, 	  -7,   -2, 	  -6,    0, 	   0,  -10
.2byte  -14,   -5, 	  -3,   -2, 	  -9,    0, 	   0,   -9
.2byte   -8,   -3, 	  -9,    3, 	   0,    1, 	   0,  -10
.2byte   -9,   -2, 	  -8,    2, 	  -2,    2, 	   0,  -10
.2byte   -9,   -3, 	  -3,   -1, 	  -4,    3, 	   0,  -10
.2byte    0,   -2, 	  -4,    3, 	   2,    0, 	   0,   -9
.2byte   -1,   -1, 	  -4,    2, 	   2,    2, 	  -1,   -8
.2byte   -2,   -2, 	  -4,    0, 	   2,    3, 	  -1,   -9
.2byte   -1,    0, 	  -6,    3, 	   4,    3, 	  -1,  -10
.2byte   -1,   -6, 	  -7,   -5, 	   5,   -5, 	  -1,   -9
.2byte    7,   -3, 	   8,    3, 	  -1,    1, 	  -1,  -10
.2byte    8,   -2, 	   7,    2, 	   1,    2, 	  -1,  -10
.2byte    8,   -3, 	   2,   -1, 	   3,    3, 	  -1,  -10
.2byte    6,    1, 	  10,    3, 	   1,    5, 	   0,  -10
.2byte   10,  -10, 	  15,   -9, 	   8,   -5, 	  -1,  -12
.2byte   12,   -5, 	  10,   -1, 	   3,    0, 	  -1,   -9
.2byte   13,   -4, 	   6,   -2, 	   5,    0, 	  -1,  -10
.2byte   13,   -5, 	   2,   -2, 	   8,    0, 	  -1,   -9
.2byte   10,   -3, 	   9,   -2, 	   8,    0, 	  -1,   -9
.2byte   12,  -14, 	  13,  -16, 	  13,  -12, 	  -1,  -16
.2byte    7,  -10, 	   5,   -7, 	   3,   -1, 	  -1,   -8
.2byte    7,   -9, 	   1,   -4, 	   6,   -2, 	  -1,   -8
.2byte    6,  -11, 	  -1,   -2, 	   8,   -3, 	  -1,   -8
.2byte    6,   -7, 	   2,   -6, 	   8,   -3, 	  -1,  -10
.2byte    5,  -14, 	   3,  -18, 	  11,  -15, 	  -1,  -12
.2byte   -2,  -14, 	   4,   -9, 	  -4,   -4, 	  -1,  -11
.2byte   -1,  -14, 	   4,   -7, 	  -6,   -7, 	  -1,  -11
.2byte    0,  -14, 	   2,   -4, 	  -6,   -9, 	  -1,  -11
.2byte   -1,  -11, 	   5,   -8, 	  -7,   -8, 	  -1,   -7
.2byte   -1,  -19, 	   4,  -18, 	  -6,  -18, 	  -1,  -13
.2byte   -8,  -10, 	  -6,   -7, 	  -4,   -1, 	   0,   -8
.2byte   -8,   -9, 	  -2,   -4, 	  -7,   -2, 	   0,   -8
.2byte   -7,  -11, 	   0,   -2, 	  -9,   -3, 	   0,   -8
.2byte   -7,   -7, 	  -3,   -6, 	  -9,   -3, 	   0,  -10
.2byte   -6,  -14, 	  -4,  -18, 	 -12,  -15, 	   0,  -12
.2byte  -13,   -5, 	 -11,   -1, 	  -4,    0, 	   0,   -9
.2byte  -14,   -4, 	  -7,   -2, 	  -6,    0, 	   0,  -10
.2byte  -14,   -5, 	  -3,   -2, 	  -9,    0, 	   0,   -9
.2byte  -11,   -3, 	 -10,   -2, 	  -9,    0, 	   0,   -9
.2byte  -13,  -14, 	 -14,  -16, 	 -14,  -12, 	   0,  -16
.2byte   -8,   -3, 	  -9,    3, 	   0,    1, 	   0,  -10
.2byte   -9,   -2, 	  -8,    2, 	  -2,    2, 	   0,  -10
.2byte   -9,   -3, 	  -3,   -1, 	  -4,    3, 	   0,  -10
.2byte   -7,    1, 	 -11,    3, 	  -2,    5, 	  -1,  -10
.2byte  -11,  -10, 	 -16,   -9, 	  -9,   -5, 	   0,  -12
.2byte    0,   -2, 	  -4,    3, 	   2,    0, 	   0,   -9
.2byte   -1,   -1, 	  -4,    2, 	   2,    2, 	  -1,   -8
.2byte   -2,   -2, 	  -4,    0, 	   2,    3, 	  -1,   -9
.2byte   -3,   -8, 	 -12,  -10, 	   2,   -1, 	  -2,  -11
.2byte    0,    0, 	   3,    4, 	   1,    1, 	   0,   -7
.2byte    0,    0, 	   3,    4, 	   1,    1, 	   0,   -7
.2byte    7,   -3, 	   8,    3, 	  -1,    1, 	  -1,  -10
.2byte    8,   -2, 	   7,    2, 	   1,    2, 	  -1,  -10
.2byte    8,   -3, 	   2,   -1, 	   3,    3, 	  -1,  -10
.2byte    8,   -9, 	  11,   -9, 	   1,   -1, 	  -2,  -11
.2byte    9,   -1, 	   4,    5, 	   2,    2, 	   0,   -9
.2byte    9,   -1, 	   4,    5, 	   2,    2, 	   0,   -9
.2byte   12,   -5, 	  10,   -1, 	   3,    0, 	  -1,   -9
.2byte   13,   -4, 	   6,   -2, 	   5,    0, 	  -1,  -10
.2byte   13,   -5, 	   2,   -2, 	   8,    0, 	  -1,   -9
.2byte   10,  -13, 	   4,  -19, 	   4,   -4, 	  -2,  -12
.2byte   13,   -3, 	  11,    2, 	   4,    0, 	   0,  -10
.2byte   13,   -3, 	  11,    2, 	   4,    0, 	   0,  -10
.2byte    7,  -10, 	   5,   -7, 	   3,   -1, 	  -1,   -8
.2byte    7,   -9, 	   1,   -4, 	   6,   -2, 	  -1,   -8
.2byte    6,  -11, 	  -1,   -2, 	   8,   -3, 	  -1,   -8
.2byte    2,  -19, 	  -4,  -18, 	   6,   -5, 	  -1,   -9
.2byte    7,   -9, 	  10,   -3, 	   6,   -2, 	   0,   -8
.2byte    7,   -9, 	  10,   -3, 	   6,   -2, 	   0,   -8
.2byte   -2,  -14, 	   4,   -9, 	  -4,   -4, 	  -1,  -11
.2byte   -1,  -14, 	   4,   -7, 	  -6,   -7, 	  -1,  -11
.2byte    0,  -14, 	   2,   -4, 	  -6,   -9, 	  -1,  -11
.2byte    2,  -15, 	   9,  -14, 	  -2,  -10, 	  -1,  -10
.2byte   -2,   -9, 	  -7,   -7, 	  -4,   -5, 	  -2,   -8
.2byte   -2,   -9, 	  -7,   -7, 	  -4,   -5, 	  -2,   -8
.2byte   -8,  -10, 	  -6,   -7, 	  -4,   -1, 	   0,   -8
.2byte   -8,   -9, 	  -2,   -4, 	  -7,   -2, 	   0,   -8
.2byte   -7,  -11, 	   0,   -2, 	  -9,   -3, 	   0,   -8
.2byte   -3,  -19, 	   3,  -18, 	  -7,   -5, 	   0,   -9
.2byte   -8,   -9, 	 -11,   -3, 	  -7,   -2, 	  -1,   -8
.2byte   -8,   -9, 	 -11,   -3, 	  -7,   -2, 	  -1,   -8
.2byte  -13,   -5, 	 -11,   -1, 	  -4,    0, 	   0,   -9
.2byte  -14,   -4, 	  -7,   -2, 	  -6,    0, 	   0,  -10
.2byte  -14,   -5, 	  -3,   -2, 	  -9,    0, 	   0,   -9
.2byte  -11,  -13, 	  -5,  -19, 	  -5,   -4, 	   1,  -12
.2byte  -14,   -3, 	 -12,    2, 	  -5,    0, 	  -1,  -10
.2byte  -14,   -3, 	 -12,    2, 	  -5,    0, 	  -1,  -10
.2byte   -8,   -3, 	  -9,    3, 	   0,    1, 	   0,  -10
.2byte   -9,   -2, 	  -8,    2, 	  -2,    2, 	   0,  -10
.2byte   -9,   -3, 	  -3,   -1, 	  -4,    3, 	   0,  -10
.2byte   -9,   -9, 	 -12,   -9, 	  -2,   -1, 	   1,  -11
.2byte  -10,   -1, 	  -5,    5, 	  -3,    2, 	  -1,   -9
.2byte  -10,   -1, 	  -5,    5, 	  -3,    2, 	  -1,   -9
.2byte   -1,   -1, 	  -4,    2, 	   2,    2, 	  -1,   -8
.2byte   -1,  -14, 	  -4,    2, 	   2,    2, 	  -1,   -7
.2byte   -1,    1, 	  -5,    2, 	   3,    2, 	  -1,  -10
.2byte    8,   -2, 	   7,    2, 	   1,    2, 	  -1,  -10
.2byte    6,  -13, 	   6,    1, 	   1,    2, 	  -1,  -11
.2byte    8,    2, 	   7,    0, 	   1,    2, 	   2,   -9
.2byte   13,   -4, 	   6,   -2, 	   5,    0, 	  -1,  -10
.2byte    6,  -18, 	   5,   -3, 	   4,    0, 	  -2,  -10
.2byte   15,   -4, 	   6,   -2, 	   5,    0, 	   3,  -10
.2byte    7,   -9, 	   1,   -4, 	   6,   -2, 	  -1,   -8
.2byte    5,  -17, 	   1,   -3, 	   6,   -1, 	  -2,   -8
.2byte    8,   -7, 	   1,   -4, 	   6,   -1, 	   0,   -8
.2byte   -1,  -14, 	   4,   -7, 	  -6,   -7, 	  -1,  -11
.2byte   -1,  -20, 	  -4,    2, 	   2,    2, 	  -1,   -9
.2byte   -1,   -9, 	   5,   -6, 	  -7,   -6, 	  -1,   -7
.2byte   -8,   -9, 	  -2,   -4, 	  -7,   -2, 	   0,   -8
.2byte   -6,  -17, 	  -2,   -3, 	  -7,   -1, 	   1,   -8
.2byte   -9,   -7, 	  -2,   -4, 	  -7,   -1, 	  -1,   -8
.2byte  -14,   -4, 	  -7,   -2, 	  -6,    0, 	   0,  -10
.2byte   -7,  -18, 	  -6,   -3, 	  -5,    0, 	   1,  -10
.2byte  -16,   -4, 	  -7,   -2, 	  -6,    0, 	  -4,  -10
.2byte   -9,   -2, 	  -8,    2, 	  -2,    2, 	   0,  -10
.2byte   -7,  -13, 	  -7,    1, 	  -2,    2, 	   0,  -11
.2byte   -9,    2, 	  -8,    0, 	  -2,    2, 	  -3,   -9
.2byte   -1,  -10, 	  -3,    2, 	   1,    2, 	  -1,   -7
.2byte   -5,  -12, 	  -6,    2, 	  -3,    3, 	   0,   -7
.2byte   -9,  -14, 	  -7,   -2, 	  -6,    0, 	   1,  -10
.2byte   -5,  -16, 	  -3,   -4, 	  -7,   -3, 	   1,  -10
.2byte   -1,  -17, 	   4,   -5, 	  -6,   -5, 	  -1,   -9
.2byte    4,  -16, 	   2,   -4, 	   6,   -3, 	  -2,  -10
.2byte    8,  -14, 	   6,   -2, 	   5,    0, 	  -2,  -10
.2byte    4,  -12, 	   5,    2, 	   2,    3, 	  -1,   -7
.2byte   -6,   -1, 	 -11,    0, 	  -5,    2, 	   1,   -6
.2byte   -6,   -1, 	 -11,    0, 	  -5,    2, 	   1,   -6
.2byte    0,   -1, 	  -5,    3, 	   5,    3, 	   0,   -8
.2byte    6,   -2, 	  11,    0, 	   4,    2, 	  -1,  -10
.2byte    9,   -2, 	  13,   -2, 	  11,    1, 	  -2,   -7
.2byte    6,   -5, 	   7,   -8, 	  12,   -6, 	  -2,   -4
.2byte   -1,   -9, 	   5,  -10, 	  -7,  -10, 	  -1,   -4
.2byte   -7,   -5, 	  -8,   -8, 	 -13,   -6, 	   1,   -4
.2byte  -10,   -2, 	 -14,   -2, 	 -12,    1, 	   1,   -7
.2byte   -5,   -2, 	 -10,    0, 	  -3,    2, 	   2,  -10
.2byte   -1,   -1, 	  -4,    2, 	   2,    2, 	  -1,   -8
.2byte   -1,  -10, 	  -3,    2, 	   1,    2, 	  -1,   -7
.2byte    8,   -2, 	   7,    2, 	   1,    2, 	  -1,  -10
.2byte    4,  -13, 	   5,    1, 	   2,    2, 	  -1,   -8
.2byte   13,   -4, 	   6,   -2, 	   5,    0, 	  -1,  -10
.2byte    7,  -14, 	   5,   -2, 	   4,    0, 	  -3,  -10
.2byte    7,   -9, 	   1,   -4, 	   6,   -2, 	  -1,   -8
.2byte    3,  -16, 	   1,   -4, 	   5,   -3, 	  -3,  -10
.2byte   -1,  -14, 	   4,   -7, 	  -6,   -7, 	  -1,  -11
.2byte   -1,  -17, 	   4,   -5, 	  -6,   -5, 	  -1,   -9
.2byte   -8,   -9, 	  -2,   -4, 	  -7,   -2, 	   0,   -8
.2byte   -4,  -16, 	  -2,   -4, 	  -6,   -3, 	   2,  -10
.2byte  -14,   -4, 	  -7,   -2, 	  -6,    0, 	   0,  -10
.2byte   -9,  -14, 	  -7,   -2, 	  -6,    0, 	   1,  -10
.2byte   -9,   -2, 	  -8,    2, 	  -2,    2, 	   0,  -10
.2byte   -5,  -13, 	  -6,    1, 	  -3,    2, 	   0,   -8
.2byte   -1,    0, 	  -6,    3, 	   4,    3, 	  -1,  -10
.2byte   -7,    1, 	 -11,    3, 	  -2,    5, 	  -1,  -10
.2byte  -11,   -3, 	 -10,   -2, 	  -9,    0, 	   0,   -9
.2byte   -7,   -7, 	  -3,   -6, 	  -9,   -3, 	   0,  -10
.2byte   -1,  -11, 	   5,   -8, 	  -7,   -8, 	  -1,   -7
.2byte    6,   -7, 	   2,   -6, 	   8,   -3, 	  -1,  -10
.2byte   10,   -3, 	   9,   -2, 	   8,    0, 	  -1,   -9
.2byte    6,    1, 	  10,    3, 	   1,    5, 	   0,  -10
.2byte   -1,    0, 	  -6,    3, 	   4,    3, 	  -1,  -10
.2byte    6,    1, 	  10,    3, 	   1,    5, 	   0,  -10
.2byte   10,   -3, 	   9,   -2, 	   8,    0, 	  -1,   -9
.2byte    6,   -7, 	   2,   -6, 	   8,   -3, 	  -1,  -10
.2byte   -1,  -11, 	   5,   -8, 	  -7,   -8, 	  -1,   -7
.2byte   -7,   -7, 	  -3,   -6, 	  -9,   -3, 	   0,  -10
.2byte  -11,   -3, 	 -10,   -2, 	  -9,    0, 	   0,   -9
.2byte   -7,    1, 	 -11,    3, 	  -2,    5, 	  -1,  -10
.2byte   -1,   -1, 	  -4,    2, 	   2,    2, 	  -1,   -8
.2byte   -1,  -14, 	  -4,    2, 	   2,    2, 	  -1,   -7
.2byte   -1,    1, 	  -5,    2, 	   3,    2, 	  -1,  -10
.2byte    8,   -2, 	   7,    2, 	   1,    2, 	  -1,  -10
.2byte    6,  -13, 	   6,    1, 	   1,    2, 	  -1,  -11
.2byte    8,    2, 	   7,    0, 	   1,    2, 	   2,   -9
.2byte   13,   -4, 	   6,   -2, 	   5,    0, 	  -1,  -10
.2byte    6,  -18, 	   5,   -3, 	   4,    0, 	  -2,  -10
.2byte   15,   -4, 	   6,   -2, 	   5,    0, 	   3,  -10
.2byte    7,   -9, 	   1,   -4, 	   6,   -2, 	  -1,   -8
.2byte    5,  -17, 	   1,   -3, 	   6,   -1, 	  -2,   -8
.2byte    8,   -7, 	   1,   -4, 	   6,   -1, 	   0,   -8
.2byte   -1,  -14, 	   4,   -7, 	  -6,   -7, 	  -1,  -11
.2byte   -1,  -20, 	  -4,    2, 	   2,    2, 	  -1,   -9
.2byte   -1,   -9, 	   5,   -6, 	  -7,   -6, 	  -1,   -7
.2byte   -8,   -9, 	  -2,   -4, 	  -7,   -2, 	   0,   -8
.2byte   -6,  -17, 	  -2,   -3, 	  -7,   -1, 	   1,   -8
.2byte   -9,   -7, 	  -2,   -4, 	  -7,   -1, 	  -1,   -8
.2byte  -14,   -4, 	  -7,   -2, 	  -6,    0, 	   0,  -10
.2byte   -7,  -18, 	  -6,   -3, 	  -5,    0, 	   1,  -10
.2byte  -16,   -4, 	  -7,   -2, 	  -6,    0, 	  -4,  -10
.2byte   -9,   -2, 	  -8,    2, 	  -2,    2, 	   0,  -10
.2byte   -7,  -13, 	  -7,    1, 	  -2,    2, 	   0,  -11
.2byte   -9,    2, 	  -8,    0, 	  -2,    2, 	  -3,   -9
.2byte   -1,  -10, 	  -3,    2, 	   1,    2, 	  -1,   -7
.2byte   -5,  -12, 	  -6,    2, 	  -3,    3, 	   0,   -7
.2byte   -9,  -14, 	  -7,   -2, 	  -6,    0, 	   1,  -10
.2byte   -5,  -16, 	  -3,   -4, 	  -7,   -3, 	   1,  -10
.2byte   -1,  -17, 	   4,   -5, 	  -6,   -5, 	  -1,   -9
.2byte    4,  -16, 	   2,   -4, 	   6,   -3, 	  -2,  -10
.2byte    8,  -14, 	   6,   -2, 	   5,    0, 	  -2,  -10
.2byte    4,  -12, 	   5,    2, 	   2,    3, 	  -1,   -7
.2byte    0,   -2, 	  -4,    3, 	   2,    0, 	   0,   -9
.2byte   -8,   -3, 	  -9,    3, 	   0,    1, 	   0,  -10
.2byte  -13,   -5, 	 -11,   -1, 	  -4,    0, 	   0,   -9
.2byte   -8,  -10, 	  -6,   -7, 	  -4,   -1, 	   0,   -8
.2byte   -2,  -14, 	   4,   -9, 	  -4,   -4, 	  -1,  -11
.2byte    7,  -10, 	   5,   -7, 	   3,   -1, 	  -1,   -8
.2byte   12,   -5, 	  10,   -1, 	   3,    0, 	  -1,   -9
.2byte    7,   -3, 	   8,    3, 	  -1,    1, 	  -1,  -10
sPersianAnimTable1:
.4byte sPersianAnims_1_1
.4byte sPersianAnims_1_2
.4byte sPersianAnims_1_3
.4byte sPersianAnims_1_4
.4byte sPersianAnims_1_5
.4byte sPersianAnims_1_6
.4byte sPersianAnims_1_7
.4byte sPersianAnims_1_8
sPersianAnimTable2:
.4byte sPersianAnims_2_1
.4byte sPersianAnims_2_2
.4byte sPersianAnims_2_3
.4byte sPersianAnims_2_4
.4byte sPersianAnims_2_5
.4byte sPersianAnims_2_6
.4byte sPersianAnims_2_7
.4byte sPersianAnims_2_8
sPersianAnimTable3:
.4byte sPersianAnims_3_1
.4byte sPersianAnims_3_2
.4byte sPersianAnims_3_3
.4byte sPersianAnims_3_4
.4byte sPersianAnims_3_5
.4byte sPersianAnims_3_6
.4byte sPersianAnims_3_7
.4byte sPersianAnims_3_8
sPersianAnimTable4:
.4byte sPersianAnims_4_1
.4byte sPersianAnims_4_2
.4byte sPersianAnims_4_3
.4byte sPersianAnims_4_4
.4byte sPersianAnims_4_5
.4byte sPersianAnims_4_6
.4byte sPersianAnims_4_7
.4byte sPersianAnims_4_8
sPersianAnimTable5:
.4byte sPersianAnims_5_1
.4byte sPersianAnims_5_2
.4byte sPersianAnims_5_3
.4byte sPersianAnims_5_4
.4byte sPersianAnims_5_5
.4byte sPersianAnims_5_6
.4byte sPersianAnims_5_7
.4byte sPersianAnims_5_8
sPersianAnimTable6:
.4byte sPersianAnims_6_1
.4byte sPersianAnims_6_1
.4byte sPersianAnims_6_1
.4byte sPersianAnims_6_1
.4byte sPersianAnims_6_1
.4byte sPersianAnims_6_1
.4byte sPersianAnims_6_1
.4byte sPersianAnims_6_1
sPersianAnimTable7:
.4byte sPersianAnims_7_1
.4byte sPersianAnims_7_2
.4byte sPersianAnims_7_3
.4byte sPersianAnims_7_4
.4byte sPersianAnims_7_5
.4byte sPersianAnims_7_6
.4byte sPersianAnims_7_7
.4byte sPersianAnims_7_8
sPersianAnimTable8:
.4byte sPersianAnims_8_1
.4byte sPersianAnims_8_2
.4byte sPersianAnims_8_3
.4byte sPersianAnims_8_4
.4byte sPersianAnims_8_5
.4byte sPersianAnims_8_6
.4byte sPersianAnims_8_7
.4byte sPersianAnims_8_8
sPersianAnimTable9:
.4byte sPersianAnims_9_1
.4byte sPersianAnims_9_2
.4byte sPersianAnims_9_3
.4byte sPersianAnims_9_4
.4byte sPersianAnims_9_5
.4byte sPersianAnims_9_6
.4byte sPersianAnims_9_7
.4byte sPersianAnims_9_8
sPersianAnimTable10:
.4byte sPersianAnims_10_1
.4byte sPersianAnims_10_2
.4byte sPersianAnims_10_3
.4byte sPersianAnims_10_4
.4byte sPersianAnims_10_5
.4byte sPersianAnims_10_6
.4byte sPersianAnims_10_7
.4byte sPersianAnims_10_8
sPersianAnimTable11:
.4byte sPersianAnims_11_1
.4byte sPersianAnims_11_2
.4byte sPersianAnims_11_3
.4byte sPersianAnims_11_4
.4byte sPersianAnims_11_5
.4byte sPersianAnims_11_6
.4byte sPersianAnims_11_7
.4byte sPersianAnims_11_8
sPersianAnimTable12:
.4byte sPersianAnims_12_1
.4byte sPersianAnims_12_2
.4byte sPersianAnims_12_3
.4byte sPersianAnims_12_4
.4byte sPersianAnims_12_5
.4byte sPersianAnims_12_6
.4byte sPersianAnims_12_7
.4byte sPersianAnims_12_8
sPersianAnimTable13:
.4byte sPersianAnims_13_1
.4byte sPersianAnims_13_2
.4byte sPersianAnims_13_3
.4byte sPersianAnims_13_4
.4byte sPersianAnims_13_5
.4byte sPersianAnims_13_6
.4byte sPersianAnims_13_7
.4byte sPersianAnims_13_8
sAxAnimationsPersian:
.4byte sPersianAnimTable1
.4byte sPersianAnimTable2
.4byte sPersianAnimTable3
.4byte sPersianAnimTable4
.4byte sPersianAnimTable5
.4byte sPersianAnimTable6
.4byte sPersianAnimTable7
.4byte sPersianAnimTable8
.4byte sPersianAnimTable9
.4byte sPersianAnimTable10
.4byte sPersianAnimTable11
.4byte sPersianAnimTable12
.4byte sPersianAnimTable13
sAxSpritesPersian:
.4byte sPersianSprites1
.4byte sPersianSprites2
.4byte sPersianSprites3
.4byte sPersianSprites4
.4byte sPersianSprites5
.4byte sPersianSprites6
.4byte sPersianSprites7
.4byte sPersianSprites8
.4byte sPersianSprites9
.4byte sPersianSprites10
.4byte sPersianSprites11
.4byte sPersianSprites12
.4byte sPersianSprites13
.4byte sPersianSprites14
.4byte sPersianSprites15
.4byte sPersianSprites16
.4byte sPersianSprites17
.4byte sPersianSprites18
.4byte sPersianSprites19
.4byte sPersianSprites20
.4byte sPersianSprites21
.4byte sPersianSprites22
.4byte sPersianSprites23
.4byte sPersianSprites24
.4byte sPersianSprites25
.4byte sPersianSprites26
.4byte sPersianSprites27
.4byte sPersianSprites28
.4byte sPersianSprites29
.4byte sPersianSprites30
.4byte sPersianSprites31
.4byte sPersianSprites32
.4byte sPersianSprites33
.4byte sPersianSprites34
.4byte sPersianSprites35
.4byte sPersianSprites36
.4byte sPersianSprites37
.4byte sPersianSprites38
.4byte sPersianSprites39
.4byte sPersianSprites40
.4byte sPersianSprites41
.4byte sPersianSprites42
.4byte sPersianSprites43
.4byte sPersianSprites44
.4byte sPersianSprites45
.4byte sPersianSprites46
.4byte sPersianSprites47
.4byte sPersianSprites48
.4byte sPersianSprites49
.4byte sPersianSprites50
.4byte sPersianSprites51
.4byte sPersianSprites52
.4byte sPersianSprites53
.4byte sPersianSprites54
.4byte sPersianSprites55
.4byte sPersianSprites56
.4byte sPersianSprites57
.4byte sPersianSprites58
.4byte sPersianSprites59
.4byte sPersianSprites60
.4byte sPersianSprites61
.4byte sPersianSprites62
.4byte sPersianSprites63
.4byte sPersianSprites64
.4byte sPersianSprites65
.4byte sPersianSprites66
.4byte sPersianSprites67
.4byte sPersianSprites68
.4byte sPersianSprites69
sAxMainPersian:
ax_main sAxPosesPersian, sAxAnimationsPersian, 13, sAxSpritesPersian, sAxPositionsPersian
