.global gAxPidgey
gAxPidgey:
ax_siro sAxMainPidgey
sPidgeyPose1:
ax_pose 0, 0x81ed, 0x80f8, 0x4c00
ax_pose_terminator
sPidgeyPose2:
ax_pose 1, 0x81ed, 0x80f8, 0x4c00
ax_pose_terminator
sPidgeyPose3:
ax_pose 2, 0x81ed, 0x80f8, 0x4c00
ax_pose_terminator
sPidgeyPose4:
ax_pose 3, 0x81ee, 0x90f9, 0x4c00
ax_pose_terminator
sPidgeyPose5:
ax_pose 4, 0x81ee, 0x90f9, 0x4c00
ax_pose_terminator
sPidgeyPose6:
ax_pose 5, 0x81ee, 0x90f9, 0x4c00
ax_pose_terminator
sPidgeyPose7:
ax_pose 6, 0x01ed, 0x90ec, 0x4c00
ax_pose_terminator
sPidgeyPose8:
ax_pose 7, 0x01ed, 0x90ec, 0x4c00
ax_pose_terminator
sPidgeyPose9:
ax_pose 8, 0x01ed, 0x90ed, 0x4c00
ax_pose_terminator
sPidgeyPose10:
ax_pose 9, 0x01ed, 0x90ec, 0x4c00
ax_pose_terminator
sPidgeyPose11:
ax_pose 10, 0x01ed, 0x90ec, 0x4c00
ax_pose_terminator
sPidgeyPose12:
ax_pose 11, 0x01ed, 0x90ec, 0x4c00
ax_pose_terminator
sPidgeyPose13:
ax_pose 12, 0x81ea, 0x80f8, 0x4c00
ax_pose_terminator
sPidgeyPose14:
ax_pose 13, 0x81ea, 0x80f8, 0x4c00
ax_pose_terminator
sPidgeyPose15:
ax_pose 14, 0x81ea, 0x80f8, 0x4c00
ax_pose_terminator
sPidgeyPose16:
ax_pose 9, 0x01ed, 0x80f4, 0x4c00
ax_pose_terminator
sPidgeyPose17:
ax_pose 10, 0x01ed, 0x80f4, 0x4c00
ax_pose_terminator
sPidgeyPose18:
ax_pose 11, 0x01ed, 0x80f4, 0x4c00
ax_pose_terminator
sPidgeyPose19:
ax_pose 6, 0x01ed, 0x80f4, 0x4c00
ax_pose_terminator
sPidgeyPose20:
ax_pose 7, 0x01ed, 0x80f4, 0x4c00
ax_pose_terminator
sPidgeyPose21:
ax_pose 8, 0x01ed, 0x80f3, 0x4c00
ax_pose_terminator
sPidgeyPose22:
ax_pose 3, 0x81ee, 0x80f7, 0x4c00
ax_pose_terminator
sPidgeyPose23:
ax_pose 4, 0x81ee, 0x80f7, 0x4c00
ax_pose_terminator
sPidgeyPose24:
ax_pose 5, 0x81ee, 0x80f7, 0x4c00
ax_pose_terminator
sPidgeyPose25:
ax_pose 0, 0x81ed, 0x80f8, 0x4c00
ax_pose_terminator
sPidgeyPose26:
ax_pose 15, 0x01e7, 0x80f0, 0x4c00
ax_pose_terminator
sPidgeyPose27:
ax_pose 16, 0x01e7, 0x80f0, 0x4c00
ax_pose_terminator
sPidgeyPose28:
ax_pose 17, 0x01e7, 0x80f0, 0x4c00
ax_pose_terminator
sPidgeyPose29:
ax_pose 3, 0x81ee, 0x90f9, 0x4c00
ax_pose_terminator
sPidgeyPose30:
ax_pose 18, 0x01e7, 0x90ef, 0x4c00
ax_pose_terminator
sPidgeyPose31:
ax_pose 19, 0x01e8, 0x90ef, 0x4c00
ax_pose_terminator
sPidgeyPose32:
ax_pose 20, 0x01e8, 0x90ef, 0x4c00
ax_pose_terminator
sPidgeyPose33:
ax_pose 6, 0x01ed, 0x90ec, 0x4c00
ax_pose_terminator
sPidgeyPose34:
ax_pose 21, 0x01e7, 0x90ef, 0x4c00
ax_pose_terminator
sPidgeyPose35:
ax_pose 22, 0x01e8, 0x90ef, 0x4c00
ax_pose_terminator
sPidgeyPose36:
ax_pose 23, 0x01e8, 0x90ef, 0x4c00
ax_pose_terminator
sPidgeyPose37:
ax_pose 9, 0x01ed, 0x90ec, 0x4c00
ax_pose_terminator
sPidgeyPose38:
ax_pose 24, 0x01e7, 0x90ef, 0x4c00
ax_pose_terminator
sPidgeyPose39:
ax_pose 25, 0x01e9, 0x90ef, 0x4c00
ax_pose_terminator
sPidgeyPose40:
ax_pose 26, 0x01e9, 0x90ef, 0x4c00
ax_pose_terminator
sPidgeyPose41:
ax_pose 12, 0x81ea, 0x80f8, 0x4c00
ax_pose_terminator
sPidgeyPose42:
ax_pose 27, 0x01e8, 0x80f0, 0x4c00
ax_pose_terminator
sPidgeyPose43:
ax_pose 28, 0x01e9, 0x80f0, 0x4c00
ax_pose_terminator
sPidgeyPose44:
ax_pose 29, 0x01e9, 0x80f0, 0x4c00
ax_pose_terminator
sPidgeyPose45:
ax_pose 9, 0x01ed, 0x80f4, 0x4c00
ax_pose_terminator
sPidgeyPose46:
ax_pose 24, 0x01e7, 0x80f1, 0x4c00
ax_pose_terminator
sPidgeyPose47:
ax_pose 25, 0x01e9, 0x80f1, 0x4c00
ax_pose_terminator
sPidgeyPose48:
ax_pose 26, 0x01e9, 0x80f1, 0x4c00
ax_pose_terminator
sPidgeyPose49:
ax_pose 6, 0x01ed, 0x80f4, 0x4c00
ax_pose_terminator
sPidgeyPose50:
ax_pose 21, 0x01e7, 0x80f1, 0x4c00
ax_pose_terminator
sPidgeyPose51:
ax_pose 22, 0x01e8, 0x80f1, 0x4c00
ax_pose_terminator
sPidgeyPose52:
ax_pose 23, 0x01e8, 0x80f1, 0x4c00
ax_pose_terminator
sPidgeyPose53:
ax_pose 3, 0x81ee, 0x80f7, 0x4c00
ax_pose_terminator
sPidgeyPose54:
ax_pose 18, 0x01e7, 0x80f1, 0x4c00
ax_pose_terminator
sPidgeyPose55:
ax_pose 19, 0x01e8, 0x80f1, 0x4c00
ax_pose_terminator
sPidgeyPose56:
ax_pose 20, 0x01e8, 0x80f1, 0x4c00
ax_pose_terminator
sPidgeyPose57:
ax_pose 0, 0x81ed, 0x80f8, 0x4c00
ax_pose_terminator
sPidgeyPose58:
ax_pose 15, 0x01e7, 0x80f0, 0x4c00
ax_pose_terminator
sPidgeyPose59:
ax_pose 16, 0x01e7, 0x80f0, 0x4c00
ax_pose_terminator
sPidgeyPose60:
ax_pose 17, 0x01e7, 0x80f0, 0x4c00
ax_pose_terminator
sPidgeyPose61:
ax_pose 3, 0x81ee, 0x90f9, 0x4c00
ax_pose_terminator
sPidgeyPose62:
ax_pose 18, 0x01e7, 0x90ef, 0x4c00
ax_pose_terminator
sPidgeyPose63:
ax_pose 19, 0x01e8, 0x90ef, 0x4c00
ax_pose_terminator
sPidgeyPose64:
ax_pose 20, 0x01e8, 0x90ef, 0x4c00
ax_pose_terminator
sPidgeyPose65:
ax_pose 6, 0x01ed, 0x90ec, 0x4c00
ax_pose_terminator
sPidgeyPose66:
ax_pose 21, 0x01e7, 0x90ef, 0x4c00
ax_pose_terminator
sPidgeyPose67:
ax_pose 22, 0x01e8, 0x90ef, 0x4c00
ax_pose_terminator
sPidgeyPose68:
ax_pose 23, 0x01e8, 0x90ef, 0x4c00
ax_pose_terminator
sPidgeyPose69:
ax_pose 9, 0x01ed, 0x90ec, 0x4c00
ax_pose_terminator
sPidgeyPose70:
ax_pose 24, 0x01e7, 0x90ef, 0x4c00
ax_pose_terminator
sPidgeyPose71:
ax_pose 25, 0x01e9, 0x90ef, 0x4c00
ax_pose_terminator
sPidgeyPose72:
ax_pose 26, 0x01e9, 0x90ef, 0x4c00
ax_pose_terminator
sPidgeyPose73:
ax_pose 12, 0x81ea, 0x80f8, 0x4c00
ax_pose_terminator
sPidgeyPose74:
ax_pose 27, 0x01e8, 0x80f0, 0x4c00
ax_pose_terminator
sPidgeyPose75:
ax_pose 28, 0x01e9, 0x80f0, 0x4c00
ax_pose_terminator
sPidgeyPose76:
ax_pose 29, 0x01e9, 0x80f0, 0x4c00
ax_pose_terminator
sPidgeyPose77:
ax_pose 9, 0x01ed, 0x80f4, 0x4c00
ax_pose_terminator
sPidgeyPose78:
ax_pose 24, 0x01e7, 0x80f1, 0x4c00
ax_pose_terminator
sPidgeyPose79:
ax_pose 25, 0x01e9, 0x80f1, 0x4c00
ax_pose_terminator
sPidgeyPose80:
ax_pose 26, 0x01e9, 0x80f1, 0x4c00
ax_pose_terminator
sPidgeyPose81:
ax_pose 6, 0x01ed, 0x80f4, 0x4c00
ax_pose_terminator
sPidgeyPose82:
ax_pose 21, 0x01e7, 0x80f1, 0x4c00
ax_pose_terminator
sPidgeyPose83:
ax_pose 22, 0x01e8, 0x80f1, 0x4c00
ax_pose_terminator
sPidgeyPose84:
ax_pose 23, 0x01e8, 0x80f1, 0x4c00
ax_pose_terminator
sPidgeyPose85:
ax_pose 3, 0x81ee, 0x80f7, 0x4c00
ax_pose_terminator
sPidgeyPose86:
ax_pose 18, 0x01e7, 0x80f1, 0x4c00
ax_pose_terminator
sPidgeyPose87:
ax_pose 19, 0x01e8, 0x80f1, 0x4c00
ax_pose_terminator
sPidgeyPose88:
ax_pose 20, 0x01e8, 0x80f1, 0x4c00
ax_pose_terminator
sPidgeyPose89:
ax_pose 0, 0x81ed, 0x80f8, 0x4c00
ax_pose_terminator
sPidgeyPose90:
ax_pose 16, 0x01e7, 0x80f0, 0x4c00
ax_pose_terminator
sPidgeyPose91:
ax_pose 17, 0x01e7, 0x80f0, 0x4c00
ax_pose_terminator
sPidgeyPose92:
ax_pose 3, 0x81ee, 0x90f9, 0x4c00
ax_pose_terminator
sPidgeyPose93:
ax_pose 19, 0x01e8, 0x90ef, 0x4c00
ax_pose_terminator
sPidgeyPose94:
ax_pose 20, 0x01e8, 0x90ef, 0x4c00
ax_pose_terminator
sPidgeyPose95:
ax_pose 6, 0x01ed, 0x90ec, 0x4c00
ax_pose_terminator
sPidgeyPose96:
ax_pose 22, 0x01e8, 0x90ef, 0x4c00
ax_pose_terminator
sPidgeyPose97:
ax_pose 23, 0x01e8, 0x90ef, 0x4c00
ax_pose_terminator
sPidgeyPose98:
ax_pose 9, 0x01ed, 0x90ec, 0x4c00
ax_pose_terminator
sPidgeyPose99:
ax_pose 25, 0x01e9, 0x90ef, 0x4c00
ax_pose_terminator
sPidgeyPose100:
ax_pose 26, 0x01e9, 0x90ef, 0x4c00
ax_pose_terminator
sPidgeyPose101:
ax_pose 12, 0x81ea, 0x80f8, 0x4c00
ax_pose_terminator
sPidgeyPose102:
ax_pose 28, 0x01e9, 0x80f0, 0x4c00
ax_pose_terminator
sPidgeyPose103:
ax_pose 29, 0x01e9, 0x80f0, 0x4c00
ax_pose_terminator
sPidgeyPose104:
ax_pose 9, 0x01ed, 0x80f4, 0x4c00
ax_pose_terminator
sPidgeyPose105:
ax_pose 25, 0x01e9, 0x80f1, 0x4c00
ax_pose_terminator
sPidgeyPose106:
ax_pose 26, 0x01e9, 0x80f1, 0x4c00
ax_pose_terminator
sPidgeyPose107:
ax_pose 6, 0x01ed, 0x80f4, 0x4c00
ax_pose_terminator
sPidgeyPose108:
ax_pose 22, 0x01e8, 0x80f1, 0x4c00
ax_pose_terminator
sPidgeyPose109:
ax_pose 23, 0x01e8, 0x80f1, 0x4c00
ax_pose_terminator
sPidgeyPose110:
ax_pose 3, 0x81ee, 0x80f7, 0x4c00
ax_pose_terminator
sPidgeyPose111:
ax_pose 19, 0x01e8, 0x80f1, 0x4c00
ax_pose_terminator
sPidgeyPose112:
ax_pose 20, 0x01e8, 0x80f1, 0x4c00
ax_pose_terminator
sPidgeyPose113:
ax_pose 16, 0x01e7, 0x80f0, 0x4c00
ax_pose_terminator
sPidgeyPose114:
ax_pose 17, 0x01e7, 0x80f0, 0x4c00
ax_pose_terminator
sPidgeyPose115:
ax_pose 19, 0x01e8, 0x90ef, 0x4c00
ax_pose_terminator
sPidgeyPose116:
ax_pose 20, 0x01e8, 0x90ef, 0x4c00
ax_pose_terminator
sPidgeyPose117:
ax_pose 22, 0x01e8, 0x90ef, 0x4c00
ax_pose_terminator
sPidgeyPose118:
ax_pose 23, 0x01e8, 0x90ef, 0x4c00
ax_pose_terminator
sPidgeyPose119:
ax_pose 25, 0x01e9, 0x90f0, 0x4c00
ax_pose_terminator
sPidgeyPose120:
ax_pose 26, 0x01e9, 0x90f0, 0x4c00
ax_pose_terminator
sPidgeyPose121:
ax_pose 28, 0x01e9, 0x80f0, 0x4c00
ax_pose_terminator
sPidgeyPose122:
ax_pose 29, 0x01e9, 0x80f0, 0x4c00
ax_pose_terminator
sPidgeyPose123:
ax_pose 25, 0x01e9, 0x80f0, 0x4c00
ax_pose_terminator
sPidgeyPose124:
ax_pose 26, 0x01e9, 0x80f0, 0x4c00
ax_pose_terminator
sPidgeyPose125:
ax_pose 22, 0x01e8, 0x80f1, 0x4c00
ax_pose_terminator
sPidgeyPose126:
ax_pose 23, 0x01e8, 0x80f1, 0x4c00
ax_pose_terminator
sPidgeyPose127:
ax_pose 19, 0x01e8, 0x80f1, 0x4c00
ax_pose_terminator
sPidgeyPose128:
ax_pose 20, 0x01e8, 0x80f1, 0x4c00
ax_pose_terminator
sPidgeyPose129:
ax_pose 30, 0x01f3, 0x40f7, 0x4c00
ax_pose_terminator
sPidgeyPose130:
ax_pose 31, 0x01f3, 0x40f7, 0x4c00
ax_pose_terminator
sPidgeyPose131:
ax_pose 32, 0x01eb, 0x80f5, 0x4c00
ax_pose_terminator
sPidgeyPose132:
ax_pose 33, 0x01e7, 0x90ef, 0x4c00
ax_pose_terminator
sPidgeyPose133:
ax_pose 34, 0x01e9, 0x90eb, 0x4c00
ax_pose_terminator
sPidgeyPose134:
ax_pose 35, 0x01ed, 0x90eb, 0x4c00
ax_pose_terminator
sPidgeyPose135:
ax_pose 36, 0x01e9, 0x80f4, 0x4c00
ax_pose_terminator
sPidgeyPose136:
ax_pose 35, 0x01ed, 0x80f5, 0x4c00
ax_pose_terminator
sPidgeyPose137:
ax_pose 34, 0x01e9, 0x80f5, 0x4c00
ax_pose_terminator
sPidgeyPose138:
ax_pose 33, 0x01e7, 0x80f1, 0x4c00
ax_pose_terminator
sPidgeyPose139:
ax_pose 0, 0x81ed, 0x80f8, 0x4c00
ax_pose_terminator
sPidgeyPose140:
ax_pose 1, 0x81ed, 0x80f8, 0x4c00
ax_pose_terminator
sPidgeyPose141:
ax_pose 2, 0x81ed, 0x80f8, 0x4c00
ax_pose_terminator
sPidgeyPose142:
ax_pose 3, 0x81ee, 0x90f9, 0x4c00
ax_pose_terminator
sPidgeyPose143:
ax_pose 4, 0x81ee, 0x90f9, 0x4c00
ax_pose_terminator
sPidgeyPose144:
ax_pose 5, 0x81ee, 0x90f9, 0x4c00
ax_pose_terminator
sPidgeyPose145:
ax_pose 6, 0x01ed, 0x90ec, 0x4c00
ax_pose_terminator
sPidgeyPose146:
ax_pose 7, 0x01ed, 0x90ec, 0x4c00
ax_pose_terminator
sPidgeyPose147:
ax_pose 8, 0x01ed, 0x90ed, 0x4c00
ax_pose_terminator
sPidgeyPose148:
ax_pose 9, 0x01ed, 0x90ec, 0x4c00
ax_pose_terminator
sPidgeyPose149:
ax_pose 10, 0x01ed, 0x90ec, 0x4c00
ax_pose_terminator
sPidgeyPose150:
ax_pose 11, 0x01ed, 0x90ec, 0x4c00
ax_pose_terminator
sPidgeyPose151:
ax_pose 12, 0x81ea, 0x80f8, 0x4c00
ax_pose_terminator
sPidgeyPose152:
ax_pose 13, 0x81ea, 0x80f8, 0x4c00
ax_pose_terminator
sPidgeyPose153:
ax_pose 14, 0x81ea, 0x80f8, 0x4c00
ax_pose_terminator
sPidgeyPose154:
ax_pose 9, 0x01ed, 0x80f4, 0x4c00
ax_pose_terminator
sPidgeyPose155:
ax_pose 10, 0x01ed, 0x80f4, 0x4c00
ax_pose_terminator
sPidgeyPose156:
ax_pose 11, 0x01ed, 0x80f4, 0x4c00
ax_pose_terminator
sPidgeyPose157:
ax_pose 6, 0x01ed, 0x80f4, 0x4c00
ax_pose_terminator
sPidgeyPose158:
ax_pose 7, 0x01ed, 0x80f4, 0x4c00
ax_pose_terminator
sPidgeyPose159:
ax_pose 8, 0x01ed, 0x80f3, 0x4c00
ax_pose_terminator
sPidgeyPose160:
ax_pose 3, 0x81ee, 0x80f7, 0x4c00
ax_pose_terminator
sPidgeyPose161:
ax_pose 4, 0x81ee, 0x80f7, 0x4c00
ax_pose_terminator
sPidgeyPose162:
ax_pose 5, 0x81ee, 0x80f7, 0x4c00
ax_pose_terminator
sPidgeyPose163:
ax_pose 15, 0x01e7, 0x80f0, 0x4c00
ax_pose_terminator
sPidgeyPose164:
ax_pose 18, 0x01e7, 0x80f1, 0x4c00
ax_pose_terminator
sPidgeyPose165:
ax_pose 21, 0x01e7, 0x80f1, 0x4c00
ax_pose_terminator
sPidgeyPose166:
ax_pose 24, 0x01e7, 0x80f1, 0x4c00
ax_pose_terminator
sPidgeyPose167:
ax_pose 27, 0x01e8, 0x80f0, 0x4c00
ax_pose_terminator
sPidgeyPose168:
ax_pose 24, 0x01e7, 0x90ef, 0x4c00
ax_pose_terminator
sPidgeyPose169:
ax_pose 21, 0x01e7, 0x90ef, 0x4c00
ax_pose_terminator
sPidgeyPose170:
ax_pose 18, 0x01e7, 0x90ef, 0x4c00
ax_pose_terminator
sPidgeyPose171:
ax_pose 17, 0x01e7, 0x80f0, 0x4c00
ax_pose_terminator
sPidgeyPose172:
ax_pose 20, 0x01e8, 0x90ef, 0x4c00
ax_pose_terminator
sPidgeyPose173:
ax_pose 23, 0x01e8, 0x90ef, 0x4c00
ax_pose_terminator
sPidgeyPose174:
ax_pose 26, 0x01e9, 0x90ef, 0x4c00
ax_pose_terminator
sPidgeyPose175:
ax_pose 29, 0x01e9, 0x80f0, 0x4c00
ax_pose_terminator
sPidgeyPose176:
ax_pose 26, 0x01e9, 0x80f1, 0x4c00
ax_pose_terminator
sPidgeyPose177:
ax_pose 23, 0x01e8, 0x80f1, 0x4c00
ax_pose_terminator
sPidgeyPose178:
ax_pose 20, 0x01e8, 0x80f1, 0x4c00
ax_pose_terminator
sPidgeyPose179:
ax_pose 2, 0x81ed, 0x80f8, 0x4c00
ax_pose_terminator
sPidgeyPose180:
ax_pose 16, 0x01e7, 0x80f0, 0x4c00
ax_pose_terminator
sPidgeyPose181:
ax_pose 17, 0x01e7, 0x80f0, 0x4c00
ax_pose_terminator
sPidgeyPose182:
ax_pose 5, 0x81ed, 0x90f9, 0x4c00
ax_pose_terminator
sPidgeyPose183:
ax_pose 19, 0x01e8, 0x90ef, 0x4c00
ax_pose_terminator
sPidgeyPose184:
ax_pose 20, 0x01e8, 0x90ef, 0x4c00
ax_pose_terminator
sPidgeyPose185:
ax_pose 8, 0x01ed, 0x90eb, 0x4c00
ax_pose_terminator
sPidgeyPose186:
ax_pose 22, 0x01e8, 0x90ef, 0x4c00
ax_pose_terminator
sPidgeyPose187:
ax_pose 23, 0x01e8, 0x90ef, 0x4c00
ax_pose_terminator
sPidgeyPose188:
ax_pose 11, 0x01ed, 0x90eb, 0x4c00
ax_pose_terminator
sPidgeyPose189:
ax_pose 25, 0x01e9, 0x90ef, 0x4c00
ax_pose_terminator
sPidgeyPose190:
ax_pose 26, 0x01e9, 0x90ef, 0x4c00
ax_pose_terminator
sPidgeyPose191:
ax_pose 14, 0x81eb, 0x80f8, 0x4c00
ax_pose_terminator
sPidgeyPose192:
ax_pose 28, 0x01e9, 0x80f0, 0x4c00
ax_pose_terminator
sPidgeyPose193:
ax_pose 29, 0x01e9, 0x80f0, 0x4c00
ax_pose_terminator
sPidgeyPose194:
ax_pose 11, 0x01ed, 0x80f5, 0x4c00
ax_pose_terminator
sPidgeyPose195:
ax_pose 25, 0x01e9, 0x80f1, 0x4c00
ax_pose_terminator
sPidgeyPose196:
ax_pose 26, 0x01e9, 0x80f1, 0x4c00
ax_pose_terminator
sPidgeyPose197:
ax_pose 8, 0x01ed, 0x80f5, 0x4c00
ax_pose_terminator
sPidgeyPose198:
ax_pose 22, 0x01e8, 0x80f1, 0x4c00
ax_pose_terminator
sPidgeyPose199:
ax_pose 23, 0x01e8, 0x80f1, 0x4c00
ax_pose_terminator
sPidgeyPose200:
ax_pose 5, 0x81ed, 0x80f7, 0x4c00
ax_pose_terminator
sPidgeyPose201:
ax_pose 19, 0x01e8, 0x80f1, 0x4c00
ax_pose_terminator
sPidgeyPose202:
ax_pose 20, 0x01e8, 0x80f1, 0x4c00
ax_pose_terminator
sPidgeyPose203:
ax_pose 17, 0x01e7, 0x80f0, 0x4c00
ax_pose_terminator
sPidgeyPose204:
ax_pose 20, 0x01e8, 0x80f1, 0x4c00
ax_pose_terminator
sPidgeyPose205:
ax_pose 23, 0x01e8, 0x80f1, 0x4c00
ax_pose_terminator
sPidgeyPose206:
ax_pose 26, 0x01e9, 0x80f1, 0x4c00
ax_pose_terminator
sPidgeyPose207:
ax_pose 29, 0x01e9, 0x80f0, 0x4c00
ax_pose_terminator
sPidgeyPose208:
ax_pose 26, 0x01e9, 0x90ef, 0x4c00
ax_pose_terminator
sPidgeyPose209:
ax_pose 23, 0x01e8, 0x90ef, 0x4c00
ax_pose_terminator
sPidgeyPose210:
ax_pose 20, 0x01e8, 0x90ef, 0x4c00
ax_pose_terminator
sPidgeyPose211:
ax_pose 0, 0x81ed, 0x80f8, 0x4c00
ax_pose_terminator
sPidgeyPose212:
ax_pose 3, 0x81ee, 0x80f7, 0x4c00
ax_pose_terminator
sPidgeyPose213:
ax_pose 6, 0x01ed, 0x80f4, 0x4c00
ax_pose_terminator
sPidgeyPose214:
ax_pose 9, 0x01ed, 0x80f4, 0x4c00
ax_pose_terminator
sPidgeyPose215:
ax_pose 12, 0x81ea, 0x80f8, 0x4c00
ax_pose_terminator
sPidgeyPose216:
ax_pose 9, 0x01ed, 0x90ec, 0x4c00
ax_pose_terminator
sPidgeyPose217:
ax_pose 6, 0x01ed, 0x90ec, 0x4c00
ax_pose_terminator
sPidgeyPose218:
ax_pose 3, 0x81ee, 0x90f9, 0x4c00
ax_pose_terminator
.align 2
sPidgeyAnims_1_1:
ax_anim 6, 0, 0, 0, 0, 0, 0,
ax_anim 4, 0, 1, 0, 0, 0, 1,
ax_anim 4, 0, 1, 0, 1, 0, 2,
ax_anim 4, 0, 2, 0, 1, 0, 1,
ax_anim 4, 0, 2, 0, 0, 0, 0,
ax_anim_terminator
sPidgeyAnims_1_2:
ax_anim 6, 0, 3, 0, 0, 0, 0,
ax_anim 4, 0, 4, 1, 0, 1, 1,
ax_anim 4, 0, 4, 2, -1, 2, 2,
ax_anim 4, 0, 5, 1, 1, 2, 2,
ax_anim 4, 0, 5, 0, 0, 0, 0,
ax_anim_terminator
sPidgeyAnims_1_3:
ax_anim 6, 0, 6, 0, 0, 0, 0,
ax_anim 4, 0, 7, 0, 0, 0, 0,
ax_anim 4, 0, 7, 2, -2, 2, 0,
ax_anim 4, 0, 8, 1, -1, 1, 0,
ax_anim 4, 0, 8, 0, 0, 0, 0,
ax_anim_terminator
sPidgeyAnims_1_4:
ax_anim 6, 0, 9, 0, 0, 0, 0,
ax_anim 4, 0, 10, 0, 0, 0, -1,
ax_anim 4, 0, 10, 2, -2, 3, -3,
ax_anim 4, 0, 11, 1, -1, 2, -1,
ax_anim 4, 0, 11, 0, 0, 0, 0,
ax_anim_terminator
sPidgeyAnims_1_5:
ax_anim 6, 0, 12, 0, 0, 0, 0,
ax_anim 4, 0, 13, 0, 0, 0, -1,
ax_anim 4, 0, 13, 0, -1, 0, -3,
ax_anim 4, 0, 14, 0, -1, 0, -1,
ax_anim 4, 0, 14, 0, 0, 0, 0,
ax_anim_terminator
sPidgeyAnims_1_6:
ax_anim 6, 0, 15, 0, 0, 0, 0,
ax_anim 4, 0, 16, 0, 0, 0, -1,
ax_anim 4, 0, 16, -2, -2, -3, -3,
ax_anim 4, 0, 17, -1, -1, -2, -1,
ax_anim 4, 0, 17, 0, 0, 0, 0,
ax_anim_terminator
sPidgeyAnims_1_7:
ax_anim 6, 0, 18, 0, 0, 0, 0,
ax_anim 4, 0, 19, 0, 0, 0, 0,
ax_anim 4, 0, 19, -2, -2, -2, 0,
ax_anim 4, 0, 20, -1, -1, -1, 0,
ax_anim 4, 0, 20, 0, 0, 0, 0,
ax_anim_terminator
sPidgeyAnims_1_8:
ax_anim 6, 0, 21, 0, 0, 0, 0,
ax_anim 4, 0, 22, -1, 0, -1, 1,
ax_anim 4, 0, 22, -2, -1, -2, 2,
ax_anim 4, 0, 23, -1, 1, -2, 2,
ax_anim 4, 0, 23, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sPidgeyAnims_2_1:
ax_anim 2, 0, 26, 0, -2, 0, 0,
ax_anim 2, 0, 27, 0, -4, 0, 0,
ax_anim 2, 0, 26, 0, -5, 0, 0,
ax_anim 4, 0, 27, 0, -5, 0, 0,
ax_anim 1, 2, 25, 0, 2, 0, 2,
ax_anim 1, 0, 25, 0, 10, 0, 10,
ax_anim 2, 0, 25, 0, 20, 0, 20,
ax_anim 2, 1, 25, 1, 20, 1, 20,
ax_anim 2, 0, 25, 0, 20, 0, 20,
ax_anim 2, 0, 25, 1, 20, 1, 20,
ax_anim 2, 0, 25, 0, 20, 0, 20,
ax_anim 2, 0, 25, 1, 20, 1, 20,
ax_anim 2, 0, 27, 0, 10, 0, 10,
ax_anim 2, 0, 27, 0, 5, 0, 5,
ax_anim_terminator
sPidgeyAnims_2_2:
ax_anim 2, 0, 30, 0, -2, 0, 0,
ax_anim 2, 0, 31, 0, -4, 0, 0,
ax_anim 2, 0, 30, 0, -5, 0, 0,
ax_anim 4, 0, 31, 0, -5, 0, 0,
ax_anim 1, 2, 29, 2, -1, 2, 2,
ax_anim 1, 0, 29, 10, 10, 10, 12,
ax_anim 2, 0, 29, 19, 22, 19, 22,
ax_anim 2, 1, 29, 20, 21, 20, 21,
ax_anim 2, 0, 29, 19, 22, 19, 22,
ax_anim 2, 0, 29, 20, 21, 20, 21,
ax_anim 2, 0, 29, 19, 22, 19, 22,
ax_anim 2, 0, 29, 20, 21, 20, 21,
ax_anim 2, 0, 31, 12, 12, 12, 12,
ax_anim 2, 0, 31, 5, 5, 5, 5,
ax_anim_terminator
sPidgeyAnims_2_3:
ax_anim 2, 0, 34, 0, -2, 0, 0,
ax_anim 2, 0, 35, 0, -4, 0, 0,
ax_anim 2, 0, 34, 0, -5, 0, 0,
ax_anim 4, 0, 35, 0, -5, 0, 0,
ax_anim 1, 2, 33, 2, -5, 2, 2,
ax_anim 1, 0, 33, 10, -3, 10, 0,
ax_anim 2, 0, 33, 18, 0, 18, 0,
ax_anim 2, 1, 33, 18, -1, 18, -1,
ax_anim 2, 0, 33, 18, 0, 18, 0,
ax_anim 2, 0, 33, 18, -1, 18, -1,
ax_anim 2, 0, 33, 18, 0, 18, 0,
ax_anim 2, 0, 33, 18, -1, 18, -1,
ax_anim 2, 0, 35, 12, -2, 12, 0,
ax_anim 2, 0, 35, 5, -3, 5, 0,
ax_anim_terminator
sPidgeyAnims_2_4:
ax_anim 2, 0, 38, 0, -2, 0, 0,
ax_anim 2, 0, 39, 0, -4, 0, 0,
ax_anim 2, 0, 38, 0, -5, 0, 0,
ax_anim 4, 0, 39, 0, -5, 0, 0,
ax_anim 1, 2, 37, 2, -4, 2, -2,
ax_anim 1, 0, 37, 10, -11, 10, -10,
ax_anim 2, 0, 37, 19, -22, 19, -22,
ax_anim 2, 1, 37, 18, -23, 18, -23,
ax_anim 2, 0, 37, 19, -22, 19, -22,
ax_anim 2, 0, 37, 18, -23, 18, -23,
ax_anim 2, 0, 37, 19, -22, 19, -22,
ax_anim 2, 0, 37, 18, -23, 18, -23,
ax_anim 2, 0, 39, 12, -12, 12, -12,
ax_anim 2, 0, 39, 5, -5, 5, -5,
ax_anim_terminator
sPidgeyAnims_2_5:
ax_anim 2, 0, 42, 0, -2, 0, 0,
ax_anim 2, 0, 43, 0, -4, 0, 0,
ax_anim 2, 0, 42, 0, -5, 0, 0,
ax_anim 4, 0, 43, 0, -5, 0, 0,
ax_anim 1, 2, 41, 0, -8, 0, -2,
ax_anim 1, 0, 41, 0, -12, 0, -8,
ax_anim 2, 0, 41, 0, -19, 0, -19,
ax_anim 2, 1, 41, 1, -19, 1, -19,
ax_anim 2, 0, 41, 0, -19, 0, -19,
ax_anim 2, 0, 41, 1, -19, 1, -19,
ax_anim 2, 0, 41, 0, -19, 0, -19,
ax_anim 2, 0, 41, 1, -19, 1, -19,
ax_anim 2, 0, 43, 0, -12, 0, -12,
ax_anim 2, 0, 43, 0, -5, 0, -5,
ax_anim_terminator
sPidgeyAnims_2_6:
ax_anim 2, 0, 46, 0, -2, 0, 0,
ax_anim 2, 0, 47, 0, -4, 0, 0,
ax_anim 2, 0, 46, 0, -5, 0, 0,
ax_anim 4, 0, 47, 0, -5, 0, 0,
ax_anim 1, 2, 45, -2, -4, -2, -2,
ax_anim 1, 0, 45, -10, -11, -10, -10,
ax_anim 2, 0, 45, -19, -22, -19, -22,
ax_anim 2, 1, 45, -18, -23, -18, -23,
ax_anim 2, 0, 45, -19, -22, -19, -22,
ax_anim 2, 0, 45, -18, -23, -18, -23,
ax_anim 2, 0, 45, -19, -22, -19, -22,
ax_anim 2, 0, 45, -18, -23, -18, -23,
ax_anim 2, 0, 47, -12, -12, -12, -12,
ax_anim 2, 0, 47, -5, -5, -5, -5,
ax_anim_terminator
sPidgeyAnims_2_7:
ax_anim 2, 0, 50, 0, -2, 0, 0,
ax_anim 2, 0, 51, 0, -4, 0, 0,
ax_anim 2, 0, 50, 0, -5, 0, 0,
ax_anim 4, 0, 51, 0, -5, 0, 0,
ax_anim 1, 2, 49, -2, -5, -2, 2,
ax_anim 1, 0, 49, -10, -3, -10, 0,
ax_anim 2, 0, 49, -18, 0, -18, 0,
ax_anim 2, 1, 49, -18, -1, -18, -1,
ax_anim 2, 0, 49, -18, 0, -18, 0,
ax_anim 2, 0, 49, -18, -1, -18, -1,
ax_anim 2, 0, 49, -18, 0, -18, 0,
ax_anim 2, 0, 49, -18, -1, -18, -1,
ax_anim 2, 0, 51, -12, -2, -12, 0,
ax_anim 2, 0, 51, -5, -3, -5, 0,
ax_anim_terminator
sPidgeyAnims_2_8:
ax_anim 2, 0, 54, 0, -2, 0, 0,
ax_anim 2, 0, 55, 0, -4, 0, 0,
ax_anim 2, 0, 54, 0, -5, 0, 0,
ax_anim 4, 0, 55, 0, -5, 0, 0,
ax_anim 1, 2, 53, -2, -3, -2, 2,
ax_anim 1, 0, 53, -10, 9, -10, 12,
ax_anim 2, 0, 53, -19, 22, -19, 22,
ax_anim 2, 1, 53, -20, 21, -20, 21,
ax_anim 2, 0, 53, -19, 22, -19, 22,
ax_anim 2, 0, 53, -20, 21, -20, 21,
ax_anim 2, 0, 53, -19, 22, -19, 22,
ax_anim 2, 0, 53, -20, 21, -20, 21,
ax_anim 2, 0, 55, -12, 12, -12, 12,
ax_anim 2, 0, 55, -5, 5, -5, 5,
ax_anim_terminator
.align 2
sPidgeyAnims_3_1:
ax_anim 2, 0, 58, 0, -2, 0, 0,
ax_anim 2, 0, 59, 0, -4, 0, 0,
ax_anim 2, 0, 58, 0, -5, 0, 0,
ax_anim 4, 0, 59, 0, -5, 0, 0,
ax_anim 1, 2, 57, 0, 2, 0, 2,
ax_anim 1, 0, 57, 0, 10, 0, 10,
ax_anim 2, 0, 57, 0, 20, 0, 20,
ax_anim 2, 1, 57, 1, 20, 1, 20,
ax_anim 2, 0, 57, 0, 20, 0, 20,
ax_anim 2, 0, 57, 1, 20, 1, 20,
ax_anim 2, 0, 57, 0, 20, 0, 20,
ax_anim 2, 0, 57, 1, 20, 1, 20,
ax_anim 2, 0, 59, 0, 10, 0, 10,
ax_anim 2, 0, 59, 0, 5, 0, 5,
ax_anim_terminator
sPidgeyAnims_3_2:
ax_anim 2, 0, 62, 0, -2, 0, 0,
ax_anim 2, 0, 63, 0, -4, 0, 0,
ax_anim 2, 0, 62, 0, -5, 0, 0,
ax_anim 4, 0, 63, 0, -5, 0, 0,
ax_anim 1, 2, 61, 2, -1, 2, 2,
ax_anim 1, 0, 61, 10, 10, 10, 12,
ax_anim 2, 0, 61, 19, 22, 19, 22,
ax_anim 2, 1, 61, 20, 21, 20, 21,
ax_anim 2, 0, 61, 19, 22, 19, 22,
ax_anim 2, 0, 61, 20, 21, 20, 21,
ax_anim 2, 0, 61, 19, 22, 19, 22,
ax_anim 2, 0, 61, 20, 21, 20, 21,
ax_anim 2, 0, 63, 12, 12, 12, 12,
ax_anim 2, 0, 63, 5, 5, 5, 5,
ax_anim_terminator
sPidgeyAnims_3_3:
ax_anim 2, 0, 66, 0, -2, 0, 0,
ax_anim 2, 0, 67, 0, -4, 0, 0,
ax_anim 2, 0, 66, 0, -5, 0, 0,
ax_anim 4, 0, 67, 0, -5, 0, 0,
ax_anim 1, 2, 65, 2, -5, 2, 2,
ax_anim 1, 0, 65, 10, -3, 10, 0,
ax_anim 2, 0, 65, 18, 0, 18, 0,
ax_anim 2, 1, 65, 18, -1, 18, -1,
ax_anim 2, 0, 65, 18, 0, 18, 0,
ax_anim 2, 0, 65, 18, -1, 18, -1,
ax_anim 2, 0, 65, 18, 0, 18, 0,
ax_anim 2, 0, 65, 18, -1, 18, -1,
ax_anim 2, 0, 67, 12, -2, 12, 0,
ax_anim 2, 0, 67, 5, -3, 5, 0,
ax_anim_terminator
sPidgeyAnims_3_4:
ax_anim 2, 0, 70, 0, -2, 0, 0,
ax_anim 2, 0, 71, 0, -4, 0, 0,
ax_anim 2, 0, 70, 0, -5, 0, 0,
ax_anim 4, 0, 71, 0, -5, 0, 0,
ax_anim 1, 2, 69, 2, -4, 2, -2,
ax_anim 1, 0, 69, 10, -11, 10, -10,
ax_anim 2, 0, 69, 19, -22, 19, -22,
ax_anim 2, 1, 69, 18, -23, 18, -23,
ax_anim 2, 0, 69, 19, -22, 19, -22,
ax_anim 2, 0, 69, 18, -23, 18, -23,
ax_anim 2, 0, 69, 19, -22, 19, -22,
ax_anim 2, 0, 69, 18, -23, 18, -23,
ax_anim 2, 0, 71, 12, -12, 12, -12,
ax_anim 2, 0, 71, 5, -5, 5, -5,
ax_anim_terminator
sPidgeyAnims_3_5:
ax_anim 2, 0, 74, 0, -2, 0, 0,
ax_anim 2, 0, 75, 0, -4, 0, 0,
ax_anim 2, 0, 74, 0, -5, 0, 0,
ax_anim 4, 0, 75, 0, -5, 0, 0,
ax_anim 1, 2, 73, 0, -8, 0, -2,
ax_anim 1, 0, 73, 0, -12, 0, -8,
ax_anim 2, 0, 73, 0, -19, 0, -19,
ax_anim 2, 1, 73, 1, -19, 1, -19,
ax_anim 2, 0, 73, 0, -19, 0, -19,
ax_anim 2, 0, 73, 1, -19, 1, -19,
ax_anim 2, 0, 73, 0, -19, 0, -19,
ax_anim 2, 0, 73, 1, -19, 1, -19,
ax_anim 2, 0, 75, 0, -12, 0, -12,
ax_anim 2, 0, 75, 0, -5, 0, -5,
ax_anim_terminator
sPidgeyAnims_3_6:
ax_anim 2, 0, 78, 0, -2, 0, 0,
ax_anim 2, 0, 79, 0, -4, 0, 0,
ax_anim 2, 0, 78, 0, -5, 0, 0,
ax_anim 4, 0, 79, 0, -5, 0, 0,
ax_anim 1, 2, 77, -2, -4, -2, -2,
ax_anim 1, 0, 77, -10, -11, -10, -10,
ax_anim 2, 0, 77, -19, -22, -19, -22,
ax_anim 2, 1, 77, -18, -23, -18, -23,
ax_anim 2, 0, 77, -19, -22, -19, -22,
ax_anim 2, 0, 77, -18, -23, -18, -23,
ax_anim 2, 0, 77, -19, -22, -19, -22,
ax_anim 2, 0, 77, -18, -23, -18, -23,
ax_anim 2, 0, 79, -12, -12, -12, -12,
ax_anim 2, 0, 79, -5, -5, -5, -5,
ax_anim_terminator
sPidgeyAnims_3_7:
ax_anim 2, 0, 82, 0, -2, 0, 0,
ax_anim 2, 0, 83, 0, -4, 0, 0,
ax_anim 2, 0, 82, 0, -5, 0, 0,
ax_anim 4, 0, 83, 0, -5, 0, 0,
ax_anim 1, 2, 81, -2, -5, -2, 2,
ax_anim 1, 0, 81, -10, -3, -10, 0,
ax_anim 2, 0, 81, -18, 0, -18, 0,
ax_anim 2, 1, 81, -18, -1, -18, -1,
ax_anim 2, 0, 81, -18, 0, -18, 0,
ax_anim 2, 0, 81, -18, -1, -18, -1,
ax_anim 2, 0, 81, -18, 0, -18, 0,
ax_anim 2, 0, 81, -18, -1, -18, -1,
ax_anim 2, 0, 83, -12, -2, -12, 0,
ax_anim 2, 0, 83, -5, -3, -5, 0,
ax_anim_terminator
sPidgeyAnims_3_8:
ax_anim 2, 0, 86, 0, -2, 0, 0,
ax_anim 2, 0, 87, 0, -4, 0, 0,
ax_anim 2, 0, 86, 0, -5, 0, 0,
ax_anim 4, 0, 87, 0, -5, 0, 0,
ax_anim 1, 2, 85, -2, -3, -2, 2,
ax_anim 1, 0, 85, -10, 9, -10, 12,
ax_anim 2, 0, 85, -19, 22, -19, 22,
ax_anim 2, 1, 85, -20, 21, -20, 21,
ax_anim 2, 0, 85, -19, 22, -19, 22,
ax_anim 2, 0, 85, -20, 21, -20, 21,
ax_anim 2, 0, 85, -19, 22, -19, 22,
ax_anim 2, 0, 85, -20, 21, -20, 21,
ax_anim 2, 0, 87, -12, 12, -12, 12,
ax_anim 2, 0, 87, -5, 5, -5, 5,
ax_anim_terminator
.align 2
sPidgeyAnims_4_1:
ax_anim 3, 0, 89, 0, -2, 0, 0,
ax_anim 3, 0, 90, 0, -4, 0, 0,
ax_anim 3, 0, 89, 0, -5, 0, 0,
ax_anim 3, 2, 90, 0, -6, 0, 0,
ax_anim 3, 0, 89, 0, -7, 0, 0,
ax_anim 3, 0, 90, 0, -7, 0, 0,
ax_anim 3, 1, 89, 0, -7, 0, 0,
ax_anim 3, 0, 90, 0, -7, 0, 0,
ax_anim 3, 0, 89, 0, -7, 0, 0,
ax_anim 2, 0, 89, 0, -5, 0, 0,
ax_anim 1, 0, 89, 0, -3, 0, 0,
ax_anim_terminator
sPidgeyAnims_4_2:
ax_anim 3, 0, 92, 0, -2, 0, 0,
ax_anim 3, 0, 93, 0, -4, 0, 0,
ax_anim 3, 0, 92, 0, -5, 0, 0,
ax_anim 3, 2, 93, 0, -6, 0, 0,
ax_anim 3, 0, 92, 0, -7, 0, 0,
ax_anim 3, 0, 93, 0, -7, 0, 0,
ax_anim 3, 1, 92, 0, -7, 0, 0,
ax_anim 3, 0, 93, 0, -7, 0, 0,
ax_anim 3, 0, 92, 0, -7, 0, 0,
ax_anim 2, 0, 92, 0, -5, 0, 0,
ax_anim 1, 0, 92, 0, -3, 0, 0,
ax_anim_terminator
sPidgeyAnims_4_3:
ax_anim 3, 0, 95, 0, -2, 0, 0,
ax_anim 3, 0, 96, 0, -4, 0, 0,
ax_anim 3, 0, 95, 0, -5, 0, 0,
ax_anim 3, 2, 96, 0, -6, 0, 0,
ax_anim 3, 0, 95, 0, -7, 0, 0,
ax_anim 3, 0, 96, 0, -7, 0, 0,
ax_anim 3, 1, 95, 0, -7, 0, 0,
ax_anim 3, 0, 96, 0, -7, 0, 0,
ax_anim 3, 0, 95, 0, -7, 0, 0,
ax_anim 2, 0, 95, 0, -5, 0, 0,
ax_anim 1, 0, 95, 0, -3, 0, 0,
ax_anim_terminator
sPidgeyAnims_4_4:
ax_anim 3, 0, 98, 0, -2, 0, 0,
ax_anim 3, 0, 99, 0, -4, 0, 0,
ax_anim 3, 0, 98, 0, -5, 0, 0,
ax_anim 3, 2, 99, 0, -6, 0, 0,
ax_anim 3, 0, 98, 0, -7, 0, 0,
ax_anim 3, 0, 99, 0, -7, 0, 0,
ax_anim 3, 1, 98, 0, -7, 0, 0,
ax_anim 3, 0, 99, 0, -7, 0, 0,
ax_anim 3, 0, 98, 0, -7, 0, 0,
ax_anim 2, 0, 98, 0, -5, 0, 0,
ax_anim 1, 0, 98, 0, -3, 0, 0,
ax_anim_terminator
sPidgeyAnims_4_5:
ax_anim 3, 0, 101, 0, -2, 0, 0,
ax_anim 3, 0, 102, 0, -4, 0, 0,
ax_anim 3, 0, 101, 0, -5, 0, 0,
ax_anim 3, 2, 102, 0, -6, 0, 0,
ax_anim 3, 0, 101, 0, -7, 0, 0,
ax_anim 3, 0, 102, 0, -7, 0, 0,
ax_anim 3, 1, 101, 0, -7, 0, 0,
ax_anim 3, 0, 102, 0, -7, 0, 0,
ax_anim 3, 0, 101, 0, -7, 0, 0,
ax_anim 2, 0, 101, 0, -5, 0, 0,
ax_anim 1, 0, 101, 0, -3, 0, 0,
ax_anim_terminator
sPidgeyAnims_4_6:
ax_anim 3, 0, 104, 0, -2, 0, 0,
ax_anim 3, 0, 105, 0, -4, 0, 0,
ax_anim 3, 0, 104, 0, -5, 0, 0,
ax_anim 3, 2, 105, 0, -6, 0, 0,
ax_anim 3, 0, 104, 0, -7, 0, 0,
ax_anim 3, 0, 105, 0, -7, 0, 0,
ax_anim 3, 1, 104, 0, -7, 0, 0,
ax_anim 3, 0, 105, 0, -7, 0, 0,
ax_anim 3, 0, 104, 0, -7, 0, 0,
ax_anim 2, 0, 104, 0, -5, 0, 0,
ax_anim 1, 0, 104, 0, -3, 0, 0,
ax_anim_terminator
sPidgeyAnims_4_7:
ax_anim 3, 0, 107, 0, -2, 0, 0,
ax_anim 3, 0, 108, 0, -4, 0, 0,
ax_anim 3, 0, 107, 0, -5, 0, 0,
ax_anim 3, 2, 108, 0, -6, 0, 0,
ax_anim 3, 0, 107, 0, -7, 0, 0,
ax_anim 3, 0, 108, 0, -7, 0, 0,
ax_anim 3, 1, 107, 0, -7, 0, 0,
ax_anim 3, 0, 108, 0, -7, 0, 0,
ax_anim 3, 0, 107, 0, -7, 0, 0,
ax_anim 2, 0, 107, 0, -5, 0, 0,
ax_anim 1, 0, 107, 0, -3, 0, 0,
ax_anim_terminator
sPidgeyAnims_4_8:
ax_anim 3, 0, 110, 0, -2, 0, 0,
ax_anim 3, 0, 111, 0, -4, 0, 0,
ax_anim 3, 0, 110, 0, -5, 0, 0,
ax_anim 3, 2, 111, 0, -6, 0, 0,
ax_anim 3, 0, 110, 0, -7, 0, 0,
ax_anim 3, 0, 111, 0, -7, 0, 0,
ax_anim 3, 1, 110, 0, -7, 0, 0,
ax_anim 3, 0, 111, 0, -7, 0, 0,
ax_anim 3, 0, 110, 0, -7, 0, 0,
ax_anim 2, 0, 110, 0, -5, 0, 0,
ax_anim 1, 0, 110, 0, -3, 0, 0,
ax_anim_terminator
.align 2
sPidgeyAnims_5_1:
ax_anim 2, 0, 112, 0, -4, 0, 0,
ax_anim 2, 0, 113, 0, -3, 0, 0,
ax_anim 2, 0, 114, 0, -4, 0, 0,
ax_anim 2, 0, 115, 0, -3, 0, 0,
ax_anim 2, 2, 116, 0, -4, 0, 0,
ax_anim 2, 0, 117, 0, -3, 0, 0,
ax_anim 2, 0, 118, 0, -4, 0, 0,
ax_anim 2, 0, 119, 0, -3, 0, 0,
ax_anim 2, 0, 120, 0, -4, 0, 0,
ax_anim 2, 0, 121, 0, -3, 0, 0,
ax_anim 2, 0, 122, 0, -4, 0, 0,
ax_anim 2, 0, 123, 0, -3, 0, 0,
ax_anim 2, 0, 124, 0, -4, 0, 0,
ax_anim 2, 0, 125, 0, -3, 0, 0,
ax_anim 2, 0, 126, 0, -4, 0, 0,
ax_anim 2, 0, 127, 0, -3, 0, 0,
ax_anim 2, 0, 112, 0, -4, 0, 0,
ax_anim 2, 1, 113, 0, -3, 0, 0,
ax_anim_terminator
sPidgeyAnims_5_2:
ax_anim 2, 0, 114, 0, -4, 0, 0,
ax_anim 2, 0, 115, 0, -3, 0, 0,
ax_anim 2, 0, 116, 0, -4, 0, 0,
ax_anim 2, 0, 117, 0, -3, 0, 0,
ax_anim 2, 2, 118, 0, -4, 0, 0,
ax_anim 2, 0, 119, 0, -3, 0, 0,
ax_anim 2, 0, 120, 0, -4, 0, 0,
ax_anim 2, 0, 121, 0, -3, 0, 0,
ax_anim 2, 0, 122, 0, -4, 0, 0,
ax_anim 2, 0, 123, 0, -3, 0, 0,
ax_anim 2, 0, 124, 0, -4, 0, 0,
ax_anim 2, 0, 125, 0, -3, 0, 0,
ax_anim 2, 0, 126, 0, -4, 0, 0,
ax_anim 2, 0, 127, 0, -3, 0, 0,
ax_anim 2, 0, 112, 0, -4, 0, 0,
ax_anim 2, 0, 113, 0, -3, 0, 0,
ax_anim 2, 0, 114, 0, -4, 0, 0,
ax_anim 2, 1, 115, 0, -3, 0, 0,
ax_anim_terminator
sPidgeyAnims_5_3:
ax_anim 2, 0, 116, 0, -4, 0, 0,
ax_anim 2, 0, 117, 0, -3, 0, 0,
ax_anim 2, 0, 118, 0, -4, 0, 0,
ax_anim 2, 0, 119, 0, -3, 0, 0,
ax_anim 2, 2, 120, 0, -4, 0, 0,
ax_anim 2, 0, 121, 0, -3, 0, 0,
ax_anim 2, 0, 122, 0, -4, 0, 0,
ax_anim 2, 0, 123, 0, -3, 0, 0,
ax_anim 2, 0, 124, 0, -4, 0, 0,
ax_anim 2, 0, 125, 0, -3, 0, 0,
ax_anim 2, 0, 126, 0, -4, 0, 0,
ax_anim 2, 0, 127, 0, -3, 0, 0,
ax_anim 2, 0, 112, 0, -4, 0, 0,
ax_anim 2, 0, 113, 0, -3, 0, 0,
ax_anim 2, 0, 114, 0, -4, 0, 0,
ax_anim 2, 0, 115, 0, -3, 0, 0,
ax_anim 2, 0, 116, 0, -4, 0, 0,
ax_anim 2, 1, 117, 0, -3, 0, 0,
ax_anim_terminator
sPidgeyAnims_5_4:
ax_anim 2, 0, 118, 0, -4, 0, 0,
ax_anim 2, 0, 119, 0, -3, 0, 0,
ax_anim 2, 0, 120, 0, -4, 0, 0,
ax_anim 2, 0, 121, 0, -3, 0, 0,
ax_anim 2, 2, 122, 0, -4, 0, 0,
ax_anim 2, 0, 123, 0, -3, 0, 0,
ax_anim 2, 0, 124, 0, -4, 0, 0,
ax_anim 2, 0, 125, 0, -3, 0, 0,
ax_anim 2, 0, 126, 0, -4, 0, 0,
ax_anim 2, 0, 127, 0, -3, 0, 0,
ax_anim 2, 0, 112, 0, -4, 0, 0,
ax_anim 2, 0, 113, 0, -3, 0, 0,
ax_anim 2, 0, 114, 0, -4, 0, 0,
ax_anim 2, 0, 115, 0, -3, 0, 0,
ax_anim 2, 0, 116, 0, -4, 0, 0,
ax_anim 2, 0, 117, 0, -3, 0, 0,
ax_anim 2, 0, 118, 0, -4, 0, 0,
ax_anim 2, 1, 119, 0, -3, 0, 0,
ax_anim_terminator
sPidgeyAnims_5_5:
ax_anim 2, 0, 120, 0, -4, 0, 0,
ax_anim 2, 0, 121, 0, -3, 0, 0,
ax_anim 2, 0, 122, 0, -4, 0, 0,
ax_anim 2, 0, 123, 0, -3, 0, 0,
ax_anim 2, 2, 124, 0, -4, 0, 0,
ax_anim 2, 0, 125, 0, -3, 0, 0,
ax_anim 2, 0, 126, 0, -4, 0, 0,
ax_anim 2, 0, 127, 0, -3, 0, 0,
ax_anim 2, 0, 112, 0, -4, 0, 0,
ax_anim 2, 0, 113, 0, -3, 0, 0,
ax_anim 2, 0, 114, 0, -4, 0, 0,
ax_anim 2, 0, 115, 0, -3, 0, 0,
ax_anim 2, 0, 116, 0, -4, 0, 0,
ax_anim 2, 0, 117, 0, -3, 0, 0,
ax_anim 2, 0, 118, 0, -4, 0, 0,
ax_anim 2, 0, 119, 0, -3, 0, 0,
ax_anim 2, 0, 120, 0, -4, 0, 0,
ax_anim 2, 1, 121, 0, -3, 0, 0,
ax_anim_terminator
sPidgeyAnims_5_6:
ax_anim 2, 0, 122, 0, -4, 0, 0,
ax_anim 2, 0, 123, 0, -3, 0, 0,
ax_anim 2, 0, 124, 0, -4, 0, 0,
ax_anim 2, 0, 125, 0, -3, 0, 0,
ax_anim 2, 2, 126, 0, -4, 0, 0,
ax_anim 2, 0, 127, 0, -3, 0, 0,
ax_anim 2, 0, 112, 0, -4, 0, 0,
ax_anim 2, 0, 113, 0, -3, 0, 0,
ax_anim 2, 0, 114, 0, -4, 0, 0,
ax_anim 2, 0, 115, 0, -3, 0, 0,
ax_anim 2, 0, 116, 0, -4, 0, 0,
ax_anim 2, 0, 117, 0, -3, 0, 0,
ax_anim 2, 0, 118, 0, -4, 0, 0,
ax_anim 2, 0, 119, 0, -3, 0, 0,
ax_anim 2, 0, 120, 0, -4, 0, 0,
ax_anim 2, 0, 121, 0, -3, 0, 0,
ax_anim 2, 0, 122, 0, -4, 0, 0,
ax_anim 2, 1, 123, 0, -3, 0, 0,
ax_anim_terminator
sPidgeyAnims_5_7:
ax_anim 2, 0, 124, 0, -4, 0, 0,
ax_anim 2, 0, 125, 0, -3, 0, 0,
ax_anim 2, 0, 126, 0, -4, 0, 0,
ax_anim 2, 0, 127, 0, -3, 0, 0,
ax_anim 2, 2, 112, 0, -4, 0, 0,
ax_anim 2, 0, 113, 0, -3, 0, 0,
ax_anim 2, 0, 114, 0, -4, 0, 0,
ax_anim 2, 0, 115, 0, -3, 0, 0,
ax_anim 2, 0, 116, 0, -4, 0, 0,
ax_anim 2, 0, 117, 0, -3, 0, 0,
ax_anim 2, 0, 118, 0, -4, 0, 0,
ax_anim 2, 0, 119, 0, -3, 0, 0,
ax_anim 2, 0, 120, 0, -4, 0, 0,
ax_anim 2, 0, 121, 0, -3, 0, 0,
ax_anim 2, 0, 122, 0, -4, 0, 0,
ax_anim 2, 0, 123, 0, -3, 0, 0,
ax_anim 2, 0, 124, 0, -4, 0, 0,
ax_anim 2, 1, 125, 0, -3, 0, 0,
ax_anim_terminator
sPidgeyAnims_5_8:
ax_anim 2, 0, 126, 0, -4, 0, 0,
ax_anim 2, 0, 127, 0, -3, 0, 0,
ax_anim 2, 0, 112, 0, -4, 0, 0,
ax_anim 2, 0, 113, 0, -3, 0, 0,
ax_anim 2, 2, 114, 0, -4, 0, 0,
ax_anim 2, 0, 115, 0, -3, 0, 0,
ax_anim 2, 0, 116, 0, -4, 0, 0,
ax_anim 2, 0, 117, 0, -3, 0, 0,
ax_anim 2, 0, 118, 0, -4, 0, 0,
ax_anim 2, 0, 119, 0, -3, 0, 0,
ax_anim 2, 0, 120, 0, -4, 0, 0,
ax_anim 2, 0, 121, 0, -3, 0, 0,
ax_anim 2, 0, 122, 0, -4, 0, 0,
ax_anim 2, 0, 123, 0, -3, 0, 0,
ax_anim 2, 0, 124, 0, -4, 0, 0,
ax_anim 2, 0, 125, 0, -3, 0, 0,
ax_anim 2, 0, 126, 0, -4, 0, 0,
ax_anim 2, 1, 127, 0, -3, 0, 0,
ax_anim_terminator
.align 2
sPidgeyAnims_6_1:
ax_anim 35, 0, 128, 0, 0, 0, 0,
ax_anim 30, 0, 129, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sPidgeyAnims_7_1:
ax_anim 2, 0, 130, 0, -3, 0, -3,
ax_anim 8, 0, 130, 0, -4, 0, -4,
ax_anim_terminator
sPidgeyAnims_7_2:
ax_anim 2, 0, 131, -3, -3, -3, -3,
ax_anim 8, 0, 131, -4, -4, -4, -4,
ax_anim_terminator
sPidgeyAnims_7_3:
ax_anim 2, 0, 132, -3, 0, -3, 0,
ax_anim 8, 0, 132, -4, 0, -4, 0,
ax_anim_terminator
sPidgeyAnims_7_4:
ax_anim 2, 0, 133, -3, 3, -3, 3,
ax_anim 8, 0, 133, -4, 4, -4, 4,
ax_anim_terminator
sPidgeyAnims_7_5:
ax_anim 2, 0, 134, 0, 3, 0, 3,
ax_anim 8, 0, 134, 0, 4, 0, 4,
ax_anim_terminator
sPidgeyAnims_7_6:
ax_anim 2, 0, 135, 3, 3, 3, 3,
ax_anim 8, 0, 135, 4, 4, 4, 4,
ax_anim_terminator
sPidgeyAnims_7_7:
ax_anim 2, 0, 136, 3, 0, 3, 0,
ax_anim 8, 0, 136, 4, 0, 4, 0,
ax_anim_terminator
sPidgeyAnims_7_8:
ax_anim 2, 0, 137, 3, -3, 3, -3,
ax_anim 8, 0, 137, 4, -4, 4, -4,
ax_anim_terminator
.align 2
sPidgeyAnims_8_1:
ax_anim 30, 0, 138, 0, 0, 0, 0,
ax_anim 4, 0, 139, 0, -1, 0, 0,
ax_anim 4, 0, 139, 0, -2, 0, 0,
ax_anim 4, 0, 139, 0, -1, 0, 0,
ax_anim 4, 0, 138, 0, 0, 0, 0,
ax_anim_terminator
sPidgeyAnims_8_2:
ax_anim 30, 0, 141, 0, 0, 0, 0,
ax_anim 4, 0, 142, 0, -1, 0, 0,
ax_anim 4, 0, 142, 0, -2, 0, 0,
ax_anim 4, 0, 142, 0, -1, 0, 0,
ax_anim 4, 0, 141, 0, 0, 0, 0,
ax_anim_terminator
sPidgeyAnims_8_3:
ax_anim 30, 0, 144, 0, 0, 0, 0,
ax_anim 4, 0, 145, 0, -1, 0, 0,
ax_anim 4, 0, 145, 0, -2, 0, 0,
ax_anim 4, 0, 145, 0, -1, 0, 0,
ax_anim 4, 0, 144, 0, 0, 0, 0,
ax_anim_terminator
sPidgeyAnims_8_4:
ax_anim 30, 0, 147, 0, 0, 0, 0,
ax_anim 4, 0, 148, 0, -1, 0, 0,
ax_anim 4, 0, 148, 0, -2, 0, 0,
ax_anim 4, 0, 148, 0, -1, 0, 0,
ax_anim 4, 0, 147, 0, 0, 0, 0,
ax_anim_terminator
sPidgeyAnims_8_5:
ax_anim 30, 0, 150, 0, 0, 0, 0,
ax_anim 4, 0, 151, 0, -1, 0, 0,
ax_anim 4, 0, 151, 0, -2, 0, 0,
ax_anim 4, 0, 151, 0, -1, 0, 0,
ax_anim 4, 0, 150, 0, 0, 0, 0,
ax_anim_terminator
sPidgeyAnims_8_6:
ax_anim 30, 0, 153, 0, 0, 0, 0,
ax_anim 4, 0, 154, 0, -1, 0, 0,
ax_anim 4, 0, 154, 0, -2, 0, 0,
ax_anim 4, 0, 154, 0, -1, 0, 0,
ax_anim 4, 0, 153, 0, 0, 0, 0,
ax_anim_terminator
sPidgeyAnims_8_7:
ax_anim 30, 0, 156, 0, 0, 0, 0,
ax_anim 4, 0, 157, 0, -1, 0, 0,
ax_anim 4, 0, 157, 0, -2, 0, 0,
ax_anim 4, 0, 157, 0, -1, 0, 0,
ax_anim 4, 0, 156, 0, 0, 0, 0,
ax_anim_terminator
sPidgeyAnims_8_8:
ax_anim 30, 0, 159, 0, 0, 0, 0,
ax_anim 4, 0, 160, 0, -1, 0, 0,
ax_anim 4, 0, 160, 0, -2, 0, 0,
ax_anim 4, 0, 160, 0, -1, 0, 0,
ax_anim 4, 0, 159, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sPidgeyAnims_9_1:
ax_anim 2, 0, 162, 0, 0, 0, 0,
ax_anim 1, 0, 163, 6, 4, 6, 4,
ax_anim 2, 0, 164, 8, 9, 8, 9,
ax_anim 2, 0, 165, 7, 19, 7, 19,
ax_anim 3, 0, 166, 0, 22, 0, 22,
ax_anim 2, 3, 167, -7, 19, -7, 19,
ax_anim 2, 0, 168, -8, 9, -8, 9,
ax_anim 1, 0, 169, -6, 4, -6, 4,
ax_anim 1, 0, 162, 0, 0, 0, 0,
ax_anim_terminator
sPidgeyAnims_9_2:
ax_anim 2, 0, 169, 0, 0, 0, 0,
ax_anim 1, 0, 162, 8, 0, 8, 0,
ax_anim 2, 0, 163, 17, 3, 17, 3,
ax_anim 2, 0, 164, 22, 9, 22, 9,
ax_anim 3, 0, 165, 21, 21, 21, 21,
ax_anim 2, 3, 166, 11, 21, 11, 21,
ax_anim 2, 0, 167, 2, 12, 2, 12,
ax_anim 1, 0, 168, -1, 8, -1, 8,
ax_anim 1, 0, 169, 0, 0, 0, 0,
ax_anim_terminator
sPidgeyAnims_9_3:
ax_anim 2, 0, 168, 0, 0, 0, 0,
ax_anim 1, 0, 169, 4, -4, 4, -4,
ax_anim 2, 0, 162, 11, -6, 11, -6,
ax_anim 2, 0, 163, 17, -4, 17, -4,
ax_anim 3, 0, 164, 22, 1, 22, 1,
ax_anim 2, 3, 165, 18, 7, 18, 7,
ax_anim 2, 0, 166, 10, 7, 10, 7,
ax_anim 1, 0, 167, 4, 5, 4, 5,
ax_anim 1, 0, 168, 0, 0, 0, 0,
ax_anim_terminator
sPidgeyAnims_9_4:
ax_anim 2, 0, 167, 0, 0, 0, 0,
ax_anim 1, 0, 168, -1, -6, -1, -6,
ax_anim 2, 0, 169, 2, -16, 2, -16,
ax_anim 2, 0, 162, 11, -23, 11, -23,
ax_anim 3, 0, 163, 21, -23, 21, -23,
ax_anim 2, 3, 164, 21, -12, 21, -12,
ax_anim 2, 0, 165, 16, -4, 16, -4,
ax_anim 1, 0, 166, 7, -1, 7, -1,
ax_anim 1, 0, 167, 0, 0, 0, 0,
ax_anim_terminator
sPidgeyAnims_9_5:
ax_anim 2, 0, 166, 0, 0, 0, 0,
ax_anim 1, 0, 167, -6, -4, -6, -4,
ax_anim 2, 0, 168, -8, -10, -8, -10,
ax_anim 2, 0, 169, -7, -18, -7, -18,
ax_anim 3, 0, 162, 0, -24, 0, -22,
ax_anim 2, 3, 163, 7, -18, 7, -18,
ax_anim 2, 0, 164, 8, -8, 8, -8,
ax_anim 1, 0, 165, 6, -4, 6, -4,
ax_anim 1, 0, 166, 0, 0, 0, 0,
ax_anim_terminator
sPidgeyAnims_9_6:
ax_anim 2, 0, 165, 0, 0, 0, 0,
ax_anim 1, 0, 164, 1, -6, 1, -6,
ax_anim 2, 0, 163, -2, -16, -2, -16,
ax_anim 2, 0, 162, -11, -23, -11, -23,
ax_anim 3, 0, 169, -21, -23, -21, -23,
ax_anim 2, 3, 168, -21, -12, -21, -12,
ax_anim 2, 0, 167, -16, -4, -16, -4,
ax_anim 1, 0, 166, -7, -1, -7, -1,
ax_anim 1, 0, 165, 0, 0, 0, 0,
ax_anim_terminator
sPidgeyAnims_9_7:
ax_anim 2, 0, 164, 0, 0, 0, 0,
ax_anim 1, 0, 163, -4, -4, -4, -4,
ax_anim 2, 0, 162, -11, -6, -11, -6,
ax_anim 2, 0, 169, -17, -4, -17, -4,
ax_anim 3, 0, 168, -22, 1, -22, 1,
ax_anim 2, 3, 167, -18, 7, -18, 7,
ax_anim 2, 0, 166, -10, 7, -10, 7,
ax_anim 1, 0, 165, -4, 5, -4, 5,
ax_anim 1, 0, 164, 0, 0, 0, 0,
ax_anim_terminator
sPidgeyAnims_9_8:
ax_anim 2, 0, 163, 0, 0, 0, 0,
ax_anim 1, 0, 162, -8, 0, -6, 0,
ax_anim 2, 0, 169, -17, 3, -17, 3,
ax_anim 2, 0, 168, -22, 9, -24, 9,
ax_anim 3, 0, 167, -21, 21, -23, 16,
ax_anim 2, 3, 166, -11, 21, -11, 16,
ax_anim 2, 0, 165, -2, 12, -4, 12,
ax_anim 1, 0, 164, 1, 8, -3, 7,
ax_anim 1, 0, 163, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sPidgeyAnims_10_1:
ax_anim 2, 0, 170, 0, 0, 0, 0,
ax_anim 2, 0, 170, 6, 0, 6, 0,
ax_anim 2, 0, 170, -6, 0, -6, 0,
ax_anim 2, 0, 170, 10, 0, 10, 0,
ax_anim 2, 0, 170, -10, 0, -10, 0,
ax_anim 2, 0, 170, 12, 0, 12, 0,
ax_anim 3, 0, 170, -12, 0, -12, 0,
ax_anim 3, 0, 170, 13, 0, 13, 0,
ax_anim 3, 0, 170, -13, 0, -13, 0,
ax_anim 2, 0, 170, 12, 0, 12, 0,
ax_anim 3, 0, 170, -12, 0, -12, 0,
ax_anim 2, 0, 170, 10, 0, 10, 0,
ax_anim 2, 0, 170, -10, 0, -10, 0,
ax_anim 2, 0, 170, 6, 0, 6, 0,
ax_anim 2, 0, 170, -6, 0, -6, 0,
ax_anim 2, 0, 170, 0, 0, 0, 0,
ax_anim_terminator
sPidgeyAnims_10_2:
ax_anim 2, 0, 171, 0, 0, 0, 0,
ax_anim 2, 0, 171, 6, -6, 6, -6,
ax_anim 2, 0, 171, -6, 6, -6, 6,
ax_anim 2, 0, 171, 10, -10, 10, -10,
ax_anim 2, 0, 171, -10, 10, -10, 10,
ax_anim 2, 0, 171, 12, -12, 12, -12,
ax_anim 3, 0, 171, -12, 12, -12, 12,
ax_anim 3, 0, 171, 13, -13, 13, -13,
ax_anim 3, 0, 171, -13, 13, -13, 13,
ax_anim 2, 0, 171, 12, -12, 12, -12,
ax_anim 3, 0, 171, -12, 12, -12, 12,
ax_anim 2, 0, 171, 10, -10, 10, -10,
ax_anim 2, 0, 171, -10, 10, -10, 10,
ax_anim 2, 0, 171, 6, -6, 6, -6,
ax_anim 2, 0, 171, -6, 6, -6, 6,
ax_anim 2, 0, 171, 0, 0, 0, 0,
ax_anim_terminator
sPidgeyAnims_10_3:
ax_anim 2, 0, 172, 0, 0, 0, 0,
ax_anim 2, 0, 172, 0, -6, 0, -6,
ax_anim 2, 0, 172, 0, 6, 0, 6,
ax_anim 2, 0, 172, 0, -10, 0, -10,
ax_anim 2, 0, 172, 0, 10, 0, 10,
ax_anim 2, 0, 172, 0, -12, 0, -12,
ax_anim 3, 0, 172, 0, 12, 0, 12,
ax_anim 3, 0, 172, 0, -13, 0, -13,
ax_anim 3, 0, 172, 0, 13, 0, 13,
ax_anim 2, 0, 172, 0, -12, 0, -12,
ax_anim 3, 0, 172, 0, 12, 0, 12,
ax_anim 2, 0, 172, 0, -10, 0, -10,
ax_anim 2, 0, 172, 0, 10, 0, 10,
ax_anim 2, 0, 172, 0, -6, 0, -6,
ax_anim 2, 0, 172, 0, 6, 0, 6,
ax_anim 2, 0, 172, 0, 0, 0, 0,
ax_anim_terminator
sPidgeyAnims_10_4:
ax_anim 2, 0, 173, 0, 0, 0, 0,
ax_anim 2, 0, 173, -6, -6, -6, -6,
ax_anim 2, 0, 173, 6, 6, 6, 6,
ax_anim 2, 0, 173, -10, -10, -10, -10,
ax_anim 2, 0, 173, 10, 10, 10, 10,
ax_anim 2, 0, 173, -12, -12, -12, -12,
ax_anim 3, 0, 173, 12, 12, 12, 12,
ax_anim 3, 0, 173, -13, -13, -13, -13,
ax_anim 3, 0, 173, 13, 13, 13, 13,
ax_anim 2, 0, 173, -12, -12, -12, -12,
ax_anim 3, 0, 173, 12, 12, 12, 12,
ax_anim 2, 0, 173, -10, -10, -10, -10,
ax_anim 2, 0, 173, 10, 10, 10, 10,
ax_anim 2, 0, 173, -6, -6, -6, -6,
ax_anim 2, 0, 173, 6, 6, 6, 6,
ax_anim 2, 0, 173, 0, 0, 0, 0,
ax_anim_terminator
sPidgeyAnims_10_5:
ax_anim 2, 0, 174, 0, 0, 0, 0,
ax_anim 2, 0, 174, 6, 0, 6, 0,
ax_anim 2, 0, 174, -6, 0, -6, 0,
ax_anim 2, 0, 174, 10, 0, 10, 0,
ax_anim 2, 0, 174, -10, 0, -10, 0,
ax_anim 2, 0, 174, 12, 0, 12, 0,
ax_anim 3, 0, 174, -12, 0, -12, 0,
ax_anim 3, 0, 174, 13, 0, 13, 0,
ax_anim 3, 0, 174, -13, 0, -13, 0,
ax_anim 2, 0, 174, 12, 0, 12, 0,
ax_anim 3, 0, 174, -12, 0, -12, 0,
ax_anim 2, 0, 174, 10, 0, 10, 0,
ax_anim 2, 0, 174, -10, 0, -10, 0,
ax_anim 2, 0, 174, 6, 0, 6, 0,
ax_anim 2, 0, 174, -6, 0, -6, 0,
ax_anim 2, 0, 174, 0, 0, 0, 0,
ax_anim_terminator
sPidgeyAnims_10_6:
ax_anim 2, 0, 175, 0, 0, 0, 0,
ax_anim 2, 0, 175, 6, -6, 6, -6,
ax_anim 2, 0, 175, -6, 6, -6, 6,
ax_anim 2, 0, 175, 10, -10, 10, -10,
ax_anim 2, 0, 175, -10, 10, -10, 10,
ax_anim 2, 0, 175, 12, -12, 12, -12,
ax_anim 3, 0, 175, -12, 12, -12, 12,
ax_anim 3, 0, 175, 13, -13, 13, -13,
ax_anim 3, 0, 175, -13, 13, -13, 13,
ax_anim 2, 0, 175, 12, -12, 12, -12,
ax_anim 3, 0, 175, -12, 12, -12, 12,
ax_anim 2, 0, 175, 10, -10, 10, -10,
ax_anim 2, 0, 175, -10, 10, -10, 10,
ax_anim 2, 0, 175, 6, -6, 6, -6,
ax_anim 2, 0, 175, -6, 6, -6, 6,
ax_anim 2, 0, 175, 0, 0, 0, 0,
ax_anim_terminator
sPidgeyAnims_10_7:
ax_anim 2, 0, 176, 0, 0, 0, 0,
ax_anim 2, 0, 176, 0, -6, 0, -6,
ax_anim 2, 0, 176, 0, 6, 0, 6,
ax_anim 2, 0, 176, 0, -10, 0, -10,
ax_anim 2, 0, 176, 0, 10, 0, 10,
ax_anim 2, 0, 176, 0, -12, 0, -12,
ax_anim 3, 0, 176, 0, 12, 0, 12,
ax_anim 3, 0, 176, 0, -13, 0, -13,
ax_anim 3, 0, 176, 0, 13, 0, 13,
ax_anim 2, 0, 176, 0, -12, 0, -12,
ax_anim 3, 0, 176, 0, 12, 0, 12,
ax_anim 2, 0, 176, 0, -10, 0, -10,
ax_anim 2, 0, 176, 0, 10, 0, 10,
ax_anim 2, 0, 176, 0, -6, 0, -6,
ax_anim 2, 0, 176, 0, 6, 0, 6,
ax_anim 2, 0, 176, 0, 0, 0, 0,
ax_anim_terminator
sPidgeyAnims_10_8:
ax_anim 2, 0, 177, 0, 0, 0, 0,
ax_anim 2, 0, 177, -6, -6, -6, -6,
ax_anim 2, 0, 177, 6, 6, 6, 6,
ax_anim 2, 0, 177, -10, -10, -10, -10,
ax_anim 2, 0, 177, 10, 10, 10, 10,
ax_anim 2, 0, 177, -12, -12, -12, -12,
ax_anim 3, 0, 177, 12, 12, 12, 12,
ax_anim 3, 0, 177, -13, -13, -13, -13,
ax_anim 3, 0, 177, 13, 13, 13, 13,
ax_anim 2, 0, 177, -12, -12, -12, -12,
ax_anim 3, 0, 177, 12, 12, 12, 12,
ax_anim 2, 0, 177, -10, -10, -10, -10,
ax_anim 2, 0, 177, 10, 10, 10, 10,
ax_anim 2, 0, 177, -6, -6, -6, -6,
ax_anim 2, 0, 177, 6, 6, 6, 6,
ax_anim 2, 0, 177, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sPidgeyAnims_11_1:
ax_anim 2, 0, 178, 0, 0, 0, 0,
ax_anim 1, 0, 179, 0, -10, 0, 0,
ax_anim 2, 0, 179, 0, -16, 0, 0,
ax_anim 3, 0, 179, 0, -20, 0, 0,
ax_anim 4, 0, 179, 0, -21, 0, 0,
ax_anim 4, 0, 180, 0, -23, 0, 0,
ax_anim 3, 0, 180, 0, -22, 0, 0,
ax_anim 2, 0, 180, 0, -18, 0, 0,
ax_anim 1, 0, 180, 0, -12, 0, 0,
ax_anim 2, 2, 178, 0, 0, 0, 0,
ax_anim_terminator
sPidgeyAnims_11_2:
ax_anim 2, 0, 181, 0, 0, 0, 0,
ax_anim 1, 0, 182, 0, -10, 0, 0,
ax_anim 2, 0, 182, 0, -16, 0, 0,
ax_anim 3, 0, 182, 0, -20, 0, 0,
ax_anim 4, 0, 182, 0, -21, 0, 0,
ax_anim 4, 0, 183, 0, -23, 0, 0,
ax_anim 3, 0, 183, 0, -22, 0, 0,
ax_anim 2, 0, 183, 0, -18, 0, 0,
ax_anim 1, 0, 183, 0, -12, 0, 0,
ax_anim 2, 2, 181, 0, 0, 0, 0,
ax_anim_terminator
sPidgeyAnims_11_3:
ax_anim 2, 0, 184, 0, 0, 0, 0,
ax_anim 1, 0, 185, 0, -10, 0, 0,
ax_anim 2, 0, 185, 0, -16, 0, 0,
ax_anim 3, 0, 185, 0, -20, 0, 0,
ax_anim 4, 0, 185, 0, -21, 0, 0,
ax_anim 4, 0, 186, 0, -23, 0, 0,
ax_anim 3, 0, 186, 0, -22, 0, 0,
ax_anim 2, 0, 186, 0, -18, 0, 0,
ax_anim 1, 0, 186, 0, -12, 0, 0,
ax_anim 2, 2, 184, 0, 0, 0, 0,
ax_anim_terminator
sPidgeyAnims_11_4:
ax_anim 2, 0, 187, 0, 0, 0, 0,
ax_anim 1, 0, 188, 0, -10, 0, 0,
ax_anim 2, 0, 188, 0, -16, 0, 0,
ax_anim 3, 0, 188, 0, -20, 0, 0,
ax_anim 4, 0, 188, 0, -21, 0, 0,
ax_anim 4, 0, 189, 0, -22, 0, 0,
ax_anim 3, 0, 189, 0, -21, 0, 0,
ax_anim 2, 0, 189, 0, -17, 0, 0,
ax_anim 1, 0, 189, 0, -11, 0, 0,
ax_anim 2, 2, 187, 0, 0, 0, 0,
ax_anim_terminator
sPidgeyAnims_11_5:
ax_anim 2, 0, 190, 0, 0, 0, 0,
ax_anim 1, 0, 191, 0, -10, 0, 0,
ax_anim 2, 0, 191, 0, -16, 0, 0,
ax_anim 3, 0, 191, 0, -20, 0, 0,
ax_anim 4, 0, 191, 0, -21, 0, 0,
ax_anim 4, 0, 192, 0, -23, 0, 0,
ax_anim 3, 0, 192, 0, -22, 0, 0,
ax_anim 2, 0, 192, 0, -18, 0, 0,
ax_anim 1, 0, 192, 0, -12, 0, 0,
ax_anim 2, 2, 190, 0, 0, 0, 0,
ax_anim_terminator
sPidgeyAnims_11_6:
ax_anim 2, 0, 193, 0, 0, 0, 0,
ax_anim 1, 0, 194, 0, -10, 0, 0,
ax_anim 2, 0, 194, 0, -16, 0, 0,
ax_anim 3, 0, 194, 0, -20, 0, 0,
ax_anim 4, 0, 194, 0, -21, 0, 0,
ax_anim 4, 0, 195, 0, -22, 0, 0,
ax_anim 3, 0, 195, 0, -21, 0, 0,
ax_anim 2, 0, 195, 0, -17, 0, 0,
ax_anim 1, 0, 195, 0, -11, 0, 0,
ax_anim 2, 2, 193, 0, 0, 0, 0,
ax_anim_terminator
sPidgeyAnims_11_7:
ax_anim 2, 0, 196, 0, 0, 0, 0,
ax_anim 1, 0, 197, 0, -10, 0, 0,
ax_anim 2, 0, 197, 0, -16, 0, 0,
ax_anim 3, 0, 197, 0, -20, 0, 0,
ax_anim 4, 0, 197, 0, -21, 0, 0,
ax_anim 4, 0, 198, 0, -23, 0, 0,
ax_anim 3, 0, 198, 0, -22, 0, 0,
ax_anim 2, 0, 198, 0, -18, 0, 0,
ax_anim 1, 0, 198, 0, -12, 0, 0,
ax_anim 2, 2, 196, 0, 0, 0, 0,
ax_anim_terminator
sPidgeyAnims_11_8:
ax_anim 2, 0, 199, 0, 0, 0, 0,
ax_anim 1, 0, 200, 0, -10, 0, 0,
ax_anim 2, 0, 200, 0, -16, 0, 0,
ax_anim 3, 0, 200, 0, -20, 0, 0,
ax_anim 4, 0, 200, 0, -21, 0, 0,
ax_anim 4, 0, 201, 0, -23, 0, 0,
ax_anim 3, 0, 201, 0, -22, 0, 0,
ax_anim 2, 0, 201, 0, -18, 0, 0,
ax_anim 1, 0, 201, 0, -12, 0, 0,
ax_anim 2, 2, 199, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sPidgeyAnims_12_1:
ax_anim 2, 0, 202, 1, 0, 1, 0,
ax_anim 2, 0, 202, 0, 0, 0, 0,
ax_anim 2, 0, 202, 1, 0, 1, 0,
ax_anim 2, 0, 202, 0, 0, 0, 0,
ax_anim 2, 0, 202, 1, 0, 1, 0,
ax_anim 2, 2, 202, 0, 0, 0, 0,
ax_anim 2, 0, 202, 1, 0, 1, 0,
ax_anim 2, 0, 202, 0, 0, 0, 0,
ax_anim 2, 0, 202, 1, 0, 1, 0,
ax_anim 2, 1, 202, 0, 0, 0, 0,
ax_anim_terminator
sPidgeyAnims_12_2:
ax_anim 2, 0, 209, 1, -1, 1, 0,
ax_anim 2, 0, 209, 0, 0, 0, 0,
ax_anim 2, 0, 209, 1, -1, 1, 0,
ax_anim 2, 0, 209, 0, 0, 0, 0,
ax_anim 2, 0, 209, 1, -1, 1, 0,
ax_anim 2, 2, 209, 0, 0, 0, 0,
ax_anim 2, 0, 209, 1, -1, 1, 0,
ax_anim 2, 0, 209, 0, 0, 0, 0,
ax_anim 2, 0, 209, 1, -1, 1, 0,
ax_anim 2, 1, 209, 0, 0, 0, 0,
ax_anim_terminator
sPidgeyAnims_12_3:
ax_anim 2, 0, 208, 0, -1, 0, -1,
ax_anim 2, 0, 208, 0, 0, 0, 0,
ax_anim 2, 0, 208, 0, -1, 0, -1,
ax_anim 2, 0, 208, 0, 0, 0, 0,
ax_anim 2, 0, 208, 0, -1, 0, -1,
ax_anim 2, 2, 208, 0, 0, 0, 0,
ax_anim 2, 0, 208, 0, -1, 0, -1,
ax_anim 2, 0, 208, 0, 0, 0, 0,
ax_anim 2, 0, 208, 0, -1, 0, -1,
ax_anim 2, 1, 208, 0, 0, 0, 0,
ax_anim_terminator
sPidgeyAnims_12_4:
ax_anim 2, 0, 207, -1, -1, -1, -1,
ax_anim 2, 0, 207, 0, 0, 0, 0,
ax_anim 2, 0, 207, -1, -1, -1, -1,
ax_anim 2, 0, 207, 0, 0, 0, 0,
ax_anim 2, 0, 207, -1, -1, -1, -1,
ax_anim 2, 2, 207, 0, 0, 0, 0,
ax_anim 2, 0, 207, -1, -1, -1, -1,
ax_anim 2, 0, 207, 0, 0, 0, 0,
ax_anim 2, 0, 207, -1, -1, -1, -1,
ax_anim 2, 1, 207, 0, 0, 0, 0,
ax_anim_terminator
sPidgeyAnims_12_5:
ax_anim 2, 0, 206, 1, 0, 1, 0,
ax_anim 2, 0, 206, 0, 0, 0, 0,
ax_anim 2, 0, 206, 1, 0, 1, 0,
ax_anim 2, 0, 206, 0, 0, 0, 0,
ax_anim 2, 0, 206, 1, 0, 1, 0,
ax_anim 2, 2, 206, 0, 0, 0, 0,
ax_anim 2, 0, 206, 1, 0, 1, 0,
ax_anim 2, 0, 206, 0, 0, 0, 0,
ax_anim 2, 0, 206, 1, 0, 1, 0,
ax_anim 2, 1, 206, 0, 0, 0, 0,
ax_anim_terminator
sPidgeyAnims_12_6:
ax_anim 2, 0, 205, 1, -1, 1, -1,
ax_anim 2, 0, 205, 0, 0, 0, 0,
ax_anim 2, 0, 205, 1, -1, 1, -1,
ax_anim 2, 0, 205, 0, 0, 0, 0,
ax_anim 2, 0, 205, 1, -1, 1, -1,
ax_anim 2, 2, 205, 0, 0, 0, 0,
ax_anim 2, 0, 205, 1, -1, 1, -1,
ax_anim 2, 0, 205, 0, 0, 0, 0,
ax_anim 2, 0, 205, 1, -1, 1, -1,
ax_anim 2, 1, 205, 0, 0, 0, 0,
ax_anim_terminator
sPidgeyAnims_12_7:
ax_anim 2, 0, 204, 0, -1, 0, -1,
ax_anim 2, 0, 204, 0, 0, 0, 0,
ax_anim 2, 0, 204, 0, -1, 0, -1,
ax_anim 2, 0, 204, 0, 0, 0, 0,
ax_anim 2, 0, 204, 0, -1, 0, -1,
ax_anim 2, 2, 204, 0, 0, 0, 0,
ax_anim 2, 0, 204, 0, -1, 0, -1,
ax_anim 2, 0, 204, 0, 0, 0, 0,
ax_anim 2, 0, 204, 0, -1, 0, -1,
ax_anim 2, 1, 204, 0, 0, 0, 0,
ax_anim_terminator
sPidgeyAnims_12_8:
ax_anim 2, 0, 203, -1, -1, -1, -1,
ax_anim 2, 0, 203, 0, 0, 0, 0,
ax_anim 2, 0, 203, -1, -1, -1, -1,
ax_anim 2, 0, 203, 0, 0, 0, 0,
ax_anim 2, 0, 203, -1, -1, -1, -1,
ax_anim 2, 2, 203, 0, 0, 0, 0,
ax_anim 2, 0, 203, -1, -1, -1, -1,
ax_anim 2, 0, 203, 0, 0, 0, 0,
ax_anim 2, 0, 203, -1, -1, -1, -1,
ax_anim 2, 1, 203, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sPidgeyAnims_13_1:
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 2, 210, 0, 0, 0, 0,
ax_anim_terminator
sPidgeyAnims_13_2:
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 2, 217, 0, 0, 0, 0,
ax_anim_terminator
sPidgeyAnims_13_3:
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 2, 216, 0, 0, 0, 0,
ax_anim_terminator
sPidgeyAnims_13_4:
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 2, 2, 215, 0, 0, 0, 0,
ax_anim_terminator
sPidgeyAnims_13_5:
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 2, 2, 214, 0, 0, 0, 0,
ax_anim_terminator
sPidgeyAnims_13_6:
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 2, 2, 213, 0, 0, 0, 0,
ax_anim_terminator
sPidgeyAnims_13_7:
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 2, 2, 212, 0, 0, 0, 0,
ax_anim_terminator
sPidgeyAnims_13_8:
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 2, 2, 211, 0, 0, 0, 0,
ax_anim_terminator
sPidgeyGfx1:
.incbin "baserom.gba", 0x5BE45C, 0x100
sPidgeySprites1:
ax_sprite sPidgeyGfx1, 0x100
ax_sprite_terminator
sPidgeyGfx2:
.incbin "baserom.gba", 0x5BE56C, 0x100
sPidgeySprites2:
ax_sprite sPidgeyGfx2, 0x100
ax_sprite_terminator
sPidgeyGfx3:
.incbin "baserom.gba", 0x5BE67C, 0x100
sPidgeySprites3:
ax_sprite sPidgeyGfx3, 0x100
ax_sprite_terminator
sPidgeyGfx4:
.incbin "baserom.gba", 0x5BE78C, 0x100
sPidgeySprites4:
ax_sprite sPidgeyGfx4, 0x100
ax_sprite_terminator
sPidgeyGfx5:
.incbin "baserom.gba", 0x5BE89C, 0x100
sPidgeySprites5:
ax_sprite sPidgeyGfx5, 0x100
ax_sprite_terminator
sPidgeyGfx6:
.incbin "baserom.gba", 0x5BE9AC, 0x100
sPidgeySprites6:
ax_sprite sPidgeyGfx6, 0x100
ax_sprite_terminator
sPidgeyGfx7:
.incbin "baserom.gba", 0x5BEABC, 0x200
sPidgeySprites7:
ax_sprite sPidgeyGfx7, 0x200
ax_sprite_terminator
sPidgeyGfx8:
.incbin "baserom.gba", 0x5BECCC, 0x200
sPidgeySprites8:
ax_sprite sPidgeyGfx8, 0x200
ax_sprite_terminator
sPidgeyGfx9:
.incbin "baserom.gba", 0x5BEEDC, 0x200
sPidgeySprites9:
ax_sprite sPidgeyGfx9, 0x200
ax_sprite_terminator
sPidgeyGfx10:
.incbin "baserom.gba", 0x5BF0EC, 0x200
sPidgeySprites10:
ax_sprite sPidgeyGfx10, 0x200
ax_sprite_terminator
sPidgeyGfx11:
.incbin "baserom.gba", 0x5BF2FC, 0x200
sPidgeySprites11:
ax_sprite sPidgeyGfx11, 0x200
ax_sprite_terminator
sPidgeyGfx12:
.incbin "baserom.gba", 0x5BF50C, 0x200
sPidgeySprites12:
ax_sprite sPidgeyGfx12, 0x200
ax_sprite_terminator
sPidgeyGfx13:
.incbin "baserom.gba", 0x5BF71C, 0x100
sPidgeySprites13:
ax_sprite sPidgeyGfx13, 0x100
ax_sprite_terminator
sPidgeyGfx14:
.incbin "baserom.gba", 0x5BF82C, 0x100
sPidgeySprites14:
ax_sprite sPidgeyGfx14, 0x100
ax_sprite_terminator
sPidgeyGfx15:
.incbin "baserom.gba", 0x5BF93C, 0x100
sPidgeySprites15:
ax_sprite sPidgeyGfx15, 0x100
ax_sprite_terminator
sPidgeyGfx16:
.incbin "baserom.gba", 0x5BFA4C, 0x100
sPidgeyGfx16_1:
.incbin "baserom.gba", 0x5BFB4C, 0x40
sPidgeySprites16:
ax_sprite 0, 0x80
ax_sprite sPidgeyGfx16, 0x100
ax_sprite 0, 0x20
ax_sprite sPidgeyGfx16_1, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sPidgeyGfx17:
.incbin "baserom.gba", 0x5BFBBC, 0x40
sPidgeyGfx17_1:
.incbin "baserom.gba", 0x5BFBFC, 0x40
sPidgeyGfx17_2:
.incbin "baserom.gba", 0x5BFC3C, 0x60
sPidgeyGfx17_3:
.incbin "baserom.gba", 0x5BFC9C, 0x60
sPidgeySprites17:
ax_sprite 0, 0x20
ax_sprite sPidgeyGfx17, 0x40
ax_sprite 0, 0x40
ax_sprite sPidgeyGfx17_1, 0x40
ax_sprite 0, 0x20
ax_sprite sPidgeyGfx17_2, 0x60
ax_sprite 0, 0x20
ax_sprite sPidgeyGfx17_3, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sPidgeyGfx18:
.incbin "baserom.gba", 0x5BFD4C, 0x40
sPidgeyGfx18_1:
.incbin "baserom.gba", 0x5BFD8C, 0x100
sPidgeyGfx18_2:
.incbin "baserom.gba", 0x5BFE8C, 0x40
sPidgeySprites18:
ax_sprite 0, 0x20
ax_sprite sPidgeyGfx18, 0x40
ax_sprite 0, 0x20
ax_sprite sPidgeyGfx18_1, 0x100
ax_sprite 0, 0x20
ax_sprite sPidgeyGfx18_2, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sPidgeyGfx19:
.incbin "baserom.gba", 0x5BFF0C, 0x60
sPidgeyGfx19_1:
.incbin "baserom.gba", 0x5BFF6C, 0x80
sPidgeySprites19:
ax_sprite 0, 0x80
ax_sprite sPidgeyGfx19, 0x60
ax_sprite 0, 0x20
ax_sprite sPidgeyGfx19_1, 0x80
ax_sprite 0, 0x80
ax_sprite_terminator
sPidgeyGfx20:
.incbin "baserom.gba", 0x5C001C, 0x20
sPidgeyGfx20_1:
.incbin "baserom.gba", 0x5C003C, 0x40
sPidgeyGfx20_2:
.incbin "baserom.gba", 0x5C007C, 0x60
sPidgeyGfx20_3:
.incbin "baserom.gba", 0x5C00DC, 0x40
sPidgeySprites20:
ax_sprite 0, 0x20
ax_sprite sPidgeyGfx20, 0x20
ax_sprite 0, 0x60
ax_sprite sPidgeyGfx20_1, 0x40
ax_sprite 0, 0x20
ax_sprite sPidgeyGfx20_2, 0x60
ax_sprite 0, 0x40
ax_sprite sPidgeyGfx20_3, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sPidgeyGfx21:
.incbin "baserom.gba", 0x5C016C, 0x40
sPidgeyGfx21_1:
.incbin "baserom.gba", 0x5C01AC, 0x80
sPidgeyGfx21_2:
.incbin "baserom.gba", 0x5C022C, 0x60
sPidgeyGfx21_3:
.incbin "baserom.gba", 0x5C028C, 0x20
sPidgeySprites21:
ax_sprite sPidgeyGfx21, 0x40
ax_sprite 0, 0x40
ax_sprite sPidgeyGfx21_1, 0x80
ax_sprite 0, 0x20
ax_sprite sPidgeyGfx21_2, 0x60
ax_sprite 0, 0x20
ax_sprite sPidgeyGfx21_3, 0x20
ax_sprite 0, 0x40
ax_sprite_terminator
sPidgeyGfx22:
.incbin "baserom.gba", 0x5C02F4, 0x60
sPidgeyGfx22_1:
.incbin "baserom.gba", 0x5C0354, 0x60
sPidgeyGfx22_2:
.incbin "baserom.gba", 0x5C03B4, 0x40
sPidgeySprites22:
ax_sprite 0, 0x80
ax_sprite sPidgeyGfx22, 0x60
ax_sprite 0, 0x20
ax_sprite sPidgeyGfx22_1, 0x60
ax_sprite 0, 0x40
ax_sprite sPidgeyGfx22_2, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sPidgeyGfx23:
.incbin "baserom.gba", 0x5C0434, 0x20
sPidgeyGfx23_1:
.incbin "baserom.gba", 0x5C0454, 0x60
sPidgeyGfx23_2:
.incbin "baserom.gba", 0x5C04B4, 0x40
sPidgeySprites23:
ax_sprite 0, 0x20
ax_sprite sPidgeyGfx23, 0x20
ax_sprite 0, 0x40
ax_sprite sPidgeyGfx23_1, 0x60
ax_sprite 0, 0x40
ax_sprite sPidgeyGfx23_2, 0x40
ax_sprite 0, 0xa0
ax_sprite_terminator
sPidgeyGfx24:
.incbin "baserom.gba", 0x5C0534, 0x40
sPidgeyGfx24_1:
.incbin "baserom.gba", 0x5C0574, 0x60
sPidgeyGfx24_2:
.incbin "baserom.gba", 0x5C05D4, 0x40
sPidgeySprites24:
ax_sprite 0, 0x20
ax_sprite sPidgeyGfx24, 0x40
ax_sprite 0, 0x20
ax_sprite sPidgeyGfx24_1, 0x60
ax_sprite 0, 0x40
ax_sprite sPidgeyGfx24_2, 0x40
ax_sprite 0, 0xa0
ax_sprite_terminator
sPidgeyGfx25:
.incbin "baserom.gba", 0x5C0654, 0x160
sPidgeySprites25:
ax_sprite 0, 0x80
ax_sprite sPidgeyGfx25, 0x160
ax_sprite 0, 0x20
ax_sprite_terminator
sPidgeyGfx26:
.incbin "baserom.gba", 0x5C07D4, 0x40
sPidgeyGfx26_1:
.incbin "baserom.gba", 0x5C0814, 0x40
sPidgeyGfx26_2:
.incbin "baserom.gba", 0x5C0854, 0x60
sPidgeySprites26:
ax_sprite 0, 0x20
ax_sprite sPidgeyGfx26, 0x40
ax_sprite 0, 0x40
ax_sprite sPidgeyGfx26_1, 0x40
ax_sprite 0, 0x20
ax_sprite sPidgeyGfx26_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sPidgeyGfx27:
.incbin "baserom.gba", 0x5C08F4, 0x40
sPidgeyGfx27_1:
.incbin "baserom.gba", 0x5C0934, 0x60
sPidgeyGfx27_2:
.incbin "baserom.gba", 0x5C0994, 0x40
sPidgeySprites27:
ax_sprite 0, 0x20
ax_sprite sPidgeyGfx27, 0x40
ax_sprite 0, 0x40
ax_sprite sPidgeyGfx27_1, 0x60
ax_sprite 0, 0x20
ax_sprite sPidgeyGfx27_2, 0x40
ax_sprite 0, 0xa0
ax_sprite_terminator
sPidgeyGfx28:
.incbin "baserom.gba", 0x5C0A14, 0x100
sPidgeyGfx28_1:
.incbin "baserom.gba", 0x5C0B14, 0x40
sPidgeySprites28:
ax_sprite 0, 0x80
ax_sprite sPidgeyGfx28, 0x100
ax_sprite 0, 0x20
ax_sprite sPidgeyGfx28_1, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sPidgeyGfx29:
.incbin "baserom.gba", 0x5C0B84, 0x40
sPidgeyGfx29_1:
.incbin "baserom.gba", 0x5C0BC4, 0x40
sPidgeyGfx29_2:
.incbin "baserom.gba", 0x5C0C04, 0x60
sPidgeySprites29:
ax_sprite 0, 0x20
ax_sprite sPidgeyGfx29, 0x40
ax_sprite 0, 0x40
ax_sprite sPidgeyGfx29_1, 0x40
ax_sprite 0, 0x20
ax_sprite sPidgeyGfx29_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sPidgeyGfx30:
.incbin "baserom.gba", 0x5C0CA4, 0x40
sPidgeyGfx30_1:
.incbin "baserom.gba", 0x5C0CE4, 0x100
sPidgeySprites30:
ax_sprite 0, 0x20
ax_sprite sPidgeyGfx30, 0x40
ax_sprite 0, 0x20
ax_sprite sPidgeyGfx30_1, 0x100
ax_sprite 0, 0x80
ax_sprite_terminator
sPidgeyGfx31:
.incbin "baserom.gba", 0x5C0E14, 0x80
sPidgeySprites31:
ax_sprite sPidgeyGfx31, 0x80
ax_sprite_terminator
sPidgeyGfx32:
.incbin "baserom.gba", 0x5C0EA4, 0x80
sPidgeySprites32:
ax_sprite sPidgeyGfx32, 0x80
ax_sprite_terminator
sPidgeyGfx33:
.incbin "baserom.gba", 0x5C0F34, 0x200
sPidgeySprites33:
ax_sprite sPidgeyGfx33, 0x200
ax_sprite_terminator
sPidgeyGfx34:
.incbin "baserom.gba", 0x5C1144, 0x200
sPidgeySprites34:
ax_sprite sPidgeyGfx34, 0x200
ax_sprite_terminator
sPidgeyGfx35:
.incbin "baserom.gba", 0x5C1354, 0x200
sPidgeySprites35:
ax_sprite sPidgeyGfx35, 0x200
ax_sprite_terminator
sPidgeyGfx36:
.incbin "baserom.gba", 0x5C1564, 0x200
sPidgeySprites36:
ax_sprite sPidgeyGfx36, 0x200
ax_sprite_terminator
sPidgeyGfx37:
.incbin "baserom.gba", 0x5C1774, 0x200
sPidgeySprites37:
ax_sprite sPidgeyGfx37, 0x200
ax_sprite_terminator
sAxPosesPidgey:
.4byte sPidgeyPose1
.4byte sPidgeyPose2
.4byte sPidgeyPose3
.4byte sPidgeyPose4
.4byte sPidgeyPose5
.4byte sPidgeyPose6
.4byte sPidgeyPose7
.4byte sPidgeyPose8
.4byte sPidgeyPose9
.4byte sPidgeyPose10
.4byte sPidgeyPose11
.4byte sPidgeyPose12
.4byte sPidgeyPose13
.4byte sPidgeyPose14
.4byte sPidgeyPose15
.4byte sPidgeyPose16
.4byte sPidgeyPose17
.4byte sPidgeyPose18
.4byte sPidgeyPose19
.4byte sPidgeyPose20
.4byte sPidgeyPose21
.4byte sPidgeyPose22
.4byte sPidgeyPose23
.4byte sPidgeyPose24
.4byte sPidgeyPose25
.4byte sPidgeyPose26
.4byte sPidgeyPose27
.4byte sPidgeyPose28
.4byte sPidgeyPose29
.4byte sPidgeyPose30
.4byte sPidgeyPose31
.4byte sPidgeyPose32
.4byte sPidgeyPose33
.4byte sPidgeyPose34
.4byte sPidgeyPose35
.4byte sPidgeyPose36
.4byte sPidgeyPose37
.4byte sPidgeyPose38
.4byte sPidgeyPose39
.4byte sPidgeyPose40
.4byte sPidgeyPose41
.4byte sPidgeyPose42
.4byte sPidgeyPose43
.4byte sPidgeyPose44
.4byte sPidgeyPose45
.4byte sPidgeyPose46
.4byte sPidgeyPose47
.4byte sPidgeyPose48
.4byte sPidgeyPose49
.4byte sPidgeyPose50
.4byte sPidgeyPose51
.4byte sPidgeyPose52
.4byte sPidgeyPose53
.4byte sPidgeyPose54
.4byte sPidgeyPose55
.4byte sPidgeyPose56
.4byte sPidgeyPose57
.4byte sPidgeyPose58
.4byte sPidgeyPose59
.4byte sPidgeyPose60
.4byte sPidgeyPose61
.4byte sPidgeyPose62
.4byte sPidgeyPose63
.4byte sPidgeyPose64
.4byte sPidgeyPose65
.4byte sPidgeyPose66
.4byte sPidgeyPose67
.4byte sPidgeyPose68
.4byte sPidgeyPose69
.4byte sPidgeyPose70
.4byte sPidgeyPose71
.4byte sPidgeyPose72
.4byte sPidgeyPose73
.4byte sPidgeyPose74
.4byte sPidgeyPose75
.4byte sPidgeyPose76
.4byte sPidgeyPose77
.4byte sPidgeyPose78
.4byte sPidgeyPose79
.4byte sPidgeyPose80
.4byte sPidgeyPose81
.4byte sPidgeyPose82
.4byte sPidgeyPose83
.4byte sPidgeyPose84
.4byte sPidgeyPose85
.4byte sPidgeyPose86
.4byte sPidgeyPose87
.4byte sPidgeyPose88
.4byte sPidgeyPose89
.4byte sPidgeyPose90
.4byte sPidgeyPose91
.4byte sPidgeyPose92
.4byte sPidgeyPose93
.4byte sPidgeyPose94
.4byte sPidgeyPose95
.4byte sPidgeyPose96
.4byte sPidgeyPose97
.4byte sPidgeyPose98
.4byte sPidgeyPose99
.4byte sPidgeyPose100
.4byte sPidgeyPose101
.4byte sPidgeyPose102
.4byte sPidgeyPose103
.4byte sPidgeyPose104
.4byte sPidgeyPose105
.4byte sPidgeyPose106
.4byte sPidgeyPose107
.4byte sPidgeyPose108
.4byte sPidgeyPose109
.4byte sPidgeyPose110
.4byte sPidgeyPose111
.4byte sPidgeyPose112
.4byte sPidgeyPose113
.4byte sPidgeyPose114
.4byte sPidgeyPose115
.4byte sPidgeyPose116
.4byte sPidgeyPose117
.4byte sPidgeyPose118
.4byte sPidgeyPose119
.4byte sPidgeyPose120
.4byte sPidgeyPose121
.4byte sPidgeyPose122
.4byte sPidgeyPose123
.4byte sPidgeyPose124
.4byte sPidgeyPose125
.4byte sPidgeyPose126
.4byte sPidgeyPose127
.4byte sPidgeyPose128
.4byte sPidgeyPose129
.4byte sPidgeyPose130
.4byte sPidgeyPose131
.4byte sPidgeyPose132
.4byte sPidgeyPose133
.4byte sPidgeyPose134
.4byte sPidgeyPose135
.4byte sPidgeyPose136
.4byte sPidgeyPose137
.4byte sPidgeyPose138
.4byte sPidgeyPose139
.4byte sPidgeyPose140
.4byte sPidgeyPose141
.4byte sPidgeyPose142
.4byte sPidgeyPose143
.4byte sPidgeyPose144
.4byte sPidgeyPose145
.4byte sPidgeyPose146
.4byte sPidgeyPose147
.4byte sPidgeyPose148
.4byte sPidgeyPose149
.4byte sPidgeyPose150
.4byte sPidgeyPose151
.4byte sPidgeyPose152
.4byte sPidgeyPose153
.4byte sPidgeyPose154
.4byte sPidgeyPose155
.4byte sPidgeyPose156
.4byte sPidgeyPose157
.4byte sPidgeyPose158
.4byte sPidgeyPose159
.4byte sPidgeyPose160
.4byte sPidgeyPose161
.4byte sPidgeyPose162
.4byte sPidgeyPose163
.4byte sPidgeyPose164
.4byte sPidgeyPose165
.4byte sPidgeyPose166
.4byte sPidgeyPose167
.4byte sPidgeyPose168
.4byte sPidgeyPose169
.4byte sPidgeyPose170
.4byte sPidgeyPose171
.4byte sPidgeyPose172
.4byte sPidgeyPose173
.4byte sPidgeyPose174
.4byte sPidgeyPose175
.4byte sPidgeyPose176
.4byte sPidgeyPose177
.4byte sPidgeyPose178
.4byte sPidgeyPose179
.4byte sPidgeyPose180
.4byte sPidgeyPose181
.4byte sPidgeyPose182
.4byte sPidgeyPose183
.4byte sPidgeyPose184
.4byte sPidgeyPose185
.4byte sPidgeyPose186
.4byte sPidgeyPose187
.4byte sPidgeyPose188
.4byte sPidgeyPose189
.4byte sPidgeyPose190
.4byte sPidgeyPose191
.4byte sPidgeyPose192
.4byte sPidgeyPose193
.4byte sPidgeyPose194
.4byte sPidgeyPose195
.4byte sPidgeyPose196
.4byte sPidgeyPose197
.4byte sPidgeyPose198
.4byte sPidgeyPose199
.4byte sPidgeyPose200
.4byte sPidgeyPose201
.4byte sPidgeyPose202
.4byte sPidgeyPose203
.4byte sPidgeyPose204
.4byte sPidgeyPose205
.4byte sPidgeyPose206
.4byte sPidgeyPose207
.4byte sPidgeyPose208
.4byte sPidgeyPose209
.4byte sPidgeyPose210
.4byte sPidgeyPose211
.4byte sPidgeyPose212
.4byte sPidgeyPose213
.4byte sPidgeyPose214
.4byte sPidgeyPose215
.4byte sPidgeyPose216
.4byte sPidgeyPose217
.4byte sPidgeyPose218
sAxPositionsPidgey:
.2byte   -1,   -3, 	  -6,   -4, 	   4,   -4, 	  -1,   -5
.2byte   -1,   -6, 	  -6,   -7, 	   4,   -7, 	  -1,   -8
.2byte   -1,    0, 	  -6,   -2, 	   4,   -2, 	  -1,   -2
.2byte    6,   -5, 	   3,   -6, 	  -4,   -4, 	   1,   -6
.2byte    7,   -7, 	   3,  -10, 	  -6,   -8, 	   1,   -7
.2byte    7,   -3, 	   4,   -7, 	  -5,   -4, 	   1,   -4
.2byte    8,   -7, 	  -3,   -6, 	  -5,   -3, 	   1,   -6
.2byte    9,  -10, 	  -3,   -8, 	  -5,   -5, 	   1,   -8
.2byte   11,   -4, 	  -1,   -5, 	  -3,   -2, 	   2,   -4
.2byte    6,  -10, 	  -6,   -4, 	  -1,   -2, 	   0,   -7
.2byte    7,  -12, 	  -6,   -6, 	  -1,   -4, 	   0,   -8
.2byte    8,   -9, 	  -4,   -6, 	  -1,   -1, 	   1,   -6
.2byte   -1,   -9, 	   2,   -4, 	  -4,   -4, 	  -1,   -6
.2byte   -1,  -14, 	   2,   -6, 	  -4,   -6, 	  -1,   -8
.2byte   -1,   -8, 	   3,   -3, 	  -5,   -3, 	  -1,   -6
.2byte   -7,  -10, 	   5,   -4, 	   0,   -2, 	  -1,   -7
.2byte   -8,  -12, 	   5,   -6, 	   0,   -4, 	  -1,   -8
.2byte   -9,   -9, 	   3,   -6, 	   0,   -1, 	  -2,   -6
.2byte   -9,   -7, 	   2,   -6, 	   4,   -3, 	  -2,   -6
.2byte  -10,  -10, 	   2,   -8, 	   4,   -5, 	  -2,   -8
.2byte  -12,   -4, 	   0,   -5, 	   2,   -2, 	  -3,   -4
.2byte   -7,   -5, 	  -4,   -6, 	   3,   -4, 	  -2,   -6
.2byte   -8,   -7, 	  -4,  -10, 	   5,   -8, 	  -2,   -7
.2byte   -8,   -3, 	  -5,   -7, 	   4,   -4, 	  -2,   -4
.2byte   -1,   -3, 	  -6,   -4, 	   4,   -4, 	  -1,   -5
.2byte   -1,    0, 	 -11,   -7, 	   9,   -7, 	  -1,   -5
.2byte   -1,   -6, 	  -8,   -2, 	   6,   -2, 	  -1,   -7
.2byte   -1,   -6, 	  -9,  -15, 	   7,  -15, 	  -1,   -7
.2byte    6,   -5, 	   3,   -6, 	  -4,   -4, 	   1,   -6
.2byte    7,   -3, 	   9,  -12, 	  -7,   -3, 	   0,   -8
.2byte    4,   -7, 	   8,   -4, 	  -2,   -2, 	  -1,   -7
.2byte    4,   -7, 	   6,  -16, 	  -9,  -11, 	  -1,   -7
.2byte    8,   -7, 	  -3,   -6, 	  -5,   -3, 	   1,   -6
.2byte    9,   -6, 	   0,  -14, 	   0,   -1, 	   0,   -8
.2byte    5,   -9, 	   4,   -7, 	   4,   -4, 	   0,   -8
.2byte    7,  -10, 	  -4,  -17, 	  -6,  -10, 	  -2,   -9
.2byte    6,  -10, 	  -6,   -4, 	  -1,   -2, 	   0,   -7
.2byte    6,  -13, 	  -8,  -11, 	   7,   -4, 	  -1,   -9
.2byte    4,  -14, 	  -6,   -7, 	   6,   -5, 	  -1,   -9
.2byte    3,  -14, 	  -7,  -14, 	   5,  -11, 	  -2,   -8
.2byte   -1,   -9, 	   2,   -4, 	  -4,   -4, 	  -1,   -6
.2byte   -1,  -11, 	   7,   -8, 	 -10,   -8, 	  -1,   -8
.2byte   -1,  -13, 	   6,   -5, 	  -8,   -5, 	  -1,   -9
.2byte   -1,  -14, 	   7,  -12, 	  -9,  -12, 	  -1,   -8
.2byte   -7,  -10, 	   5,   -4, 	   0,   -2, 	  -1,   -7
.2byte   -7,  -13, 	   7,  -11, 	  -8,   -4, 	   0,   -9
.2byte   -5,  -14, 	   5,   -7, 	  -7,   -5, 	   0,   -9
.2byte   -4,  -14, 	   6,  -14, 	  -6,  -11, 	   1,   -8
.2byte   -9,   -7, 	   2,   -6, 	   4,   -3, 	  -2,   -6
.2byte  -10,   -6, 	  -1,  -14, 	  -1,   -1, 	  -1,   -8
.2byte   -6,   -9, 	  -5,   -7, 	  -5,   -4, 	  -1,   -8
.2byte   -8,  -10, 	   3,  -17, 	   5,  -10, 	   1,   -9
.2byte   -7,   -5, 	  -4,   -6, 	   3,   -4, 	  -2,   -6
.2byte   -8,   -3, 	 -10,  -12, 	   6,   -3, 	  -1,   -8
.2byte   -5,   -7, 	  -9,   -4, 	   1,   -2, 	   0,   -7
.2byte   -5,   -7, 	  -7,  -16, 	   8,  -11, 	   0,   -7
.2byte   -1,   -3, 	  -6,   -4, 	   4,   -4, 	  -1,   -5
.2byte   -1,    0, 	 -11,   -7, 	   9,   -7, 	  -1,   -5
.2byte   -1,   -6, 	  -8,   -2, 	   6,   -2, 	  -1,   -7
.2byte   -1,   -6, 	  -9,  -15, 	   7,  -15, 	  -1,   -7
.2byte    6,   -5, 	   3,   -6, 	  -4,   -4, 	   1,   -6
.2byte    7,   -3, 	   9,  -12, 	  -7,   -3, 	   0,   -8
.2byte    4,   -7, 	   8,   -4, 	  -2,   -2, 	  -1,   -7
.2byte    4,   -7, 	   6,  -16, 	  -9,  -11, 	  -1,   -7
.2byte    8,   -7, 	  -3,   -6, 	  -5,   -3, 	   1,   -6
.2byte    9,   -6, 	   0,  -14, 	   0,   -1, 	   0,   -8
.2byte    5,   -9, 	   4,   -7, 	   4,   -4, 	   0,   -8
.2byte    7,  -10, 	  -4,  -17, 	  -6,  -10, 	  -2,   -9
.2byte    6,  -10, 	  -6,   -4, 	  -1,   -2, 	   0,   -7
.2byte    6,  -13, 	  -8,  -11, 	   7,   -4, 	  -1,   -9
.2byte    4,  -14, 	  -6,   -7, 	   6,   -5, 	  -1,   -9
.2byte    3,  -14, 	  -7,  -14, 	   5,  -11, 	  -2,   -8
.2byte   -1,   -9, 	   2,   -4, 	  -4,   -4, 	  -1,   -6
.2byte   -1,  -11, 	   7,   -8, 	 -10,   -8, 	  -1,   -8
.2byte   -1,  -13, 	   6,   -5, 	  -8,   -5, 	  -1,   -9
.2byte   -1,  -14, 	   7,  -12, 	  -9,  -12, 	  -1,   -8
.2byte   -7,  -10, 	   5,   -4, 	   0,   -2, 	  -1,   -7
.2byte   -7,  -13, 	   7,  -11, 	  -8,   -4, 	   0,   -9
.2byte   -5,  -14, 	   5,   -7, 	  -7,   -5, 	   0,   -9
.2byte   -4,  -14, 	   6,  -14, 	  -6,  -11, 	   1,   -8
.2byte   -9,   -7, 	   2,   -6, 	   4,   -3, 	  -2,   -6
.2byte  -10,   -6, 	  -1,  -14, 	  -1,   -1, 	  -1,   -8
.2byte   -6,   -9, 	  -5,   -7, 	  -5,   -4, 	  -1,   -8
.2byte   -8,  -10, 	   3,  -17, 	   5,  -10, 	   1,   -9
.2byte   -7,   -5, 	  -4,   -6, 	   3,   -4, 	  -2,   -6
.2byte   -8,   -3, 	 -10,  -12, 	   6,   -3, 	  -1,   -8
.2byte   -5,   -7, 	  -9,   -4, 	   1,   -2, 	   0,   -7
.2byte   -5,   -7, 	  -7,  -16, 	   8,  -11, 	   0,   -7
.2byte   -1,   -3, 	  -6,   -4, 	   4,   -4, 	  -1,   -5
.2byte   -1,   -6, 	  -8,   -2, 	   6,   -2, 	  -1,   -7
.2byte   -1,   -6, 	  -9,  -15, 	   7,  -15, 	  -1,   -7
.2byte    6,   -5, 	   3,   -6, 	  -4,   -4, 	   1,   -6
.2byte    4,   -7, 	   8,   -4, 	  -2,   -2, 	  -1,   -7
.2byte    4,   -7, 	   6,  -16, 	  -9,  -11, 	  -1,   -7
.2byte    8,   -7, 	  -3,   -6, 	  -5,   -3, 	   1,   -6
.2byte    5,   -9, 	   4,   -7, 	   4,   -4, 	   0,   -8
.2byte    7,  -10, 	  -4,  -17, 	  -6,  -10, 	  -2,   -9
.2byte    6,  -10, 	  -6,   -4, 	  -1,   -2, 	   0,   -7
.2byte    4,  -14, 	  -6,   -7, 	   6,   -5, 	  -1,   -9
.2byte    3,  -14, 	  -7,  -14, 	   5,  -11, 	  -2,   -8
.2byte   -1,   -9, 	   2,   -4, 	  -4,   -4, 	  -1,   -6
.2byte   -1,  -13, 	   6,   -5, 	  -8,   -5, 	  -1,   -9
.2byte   -1,  -14, 	   7,  -12, 	  -9,  -12, 	  -1,   -8
.2byte   -7,  -10, 	   5,   -4, 	   0,   -2, 	  -1,   -7
.2byte   -5,  -14, 	   5,   -7, 	  -7,   -5, 	   0,   -9
.2byte   -4,  -14, 	   6,  -14, 	  -6,  -11, 	   1,   -8
.2byte   -9,   -7, 	   2,   -6, 	   4,   -3, 	  -2,   -6
.2byte   -6,   -9, 	  -5,   -7, 	  -5,   -4, 	  -1,   -8
.2byte   -8,  -10, 	   3,  -17, 	   5,  -10, 	   1,   -9
.2byte   -7,   -5, 	  -4,   -6, 	   3,   -4, 	  -2,   -6
.2byte   -5,   -7, 	  -9,   -4, 	   1,   -2, 	   0,   -7
.2byte   -5,   -7, 	  -7,  -16, 	   8,  -11, 	   0,   -7
.2byte   -1,   -6, 	  -8,   -2, 	   6,   -2, 	  -1,   -7
.2byte   -1,   -6, 	  -9,  -15, 	   7,  -15, 	  -1,   -7
.2byte    4,   -7, 	   8,   -4, 	  -2,   -2, 	  -1,   -7
.2byte    4,   -7, 	   6,  -16, 	  -9,  -11, 	  -1,   -7
.2byte    5,   -9, 	   4,   -7, 	   4,   -4, 	   0,   -8
.2byte    7,  -10, 	  -4,  -17, 	  -6,  -10, 	  -2,   -9
.2byte    5,  -14, 	  -5,   -7, 	   7,   -5, 	   0,   -9
.2byte    4,  -14, 	  -6,  -14, 	   6,  -11, 	  -1,   -8
.2byte   -1,  -13, 	   6,   -5, 	  -8,   -5, 	  -1,   -9
.2byte   -1,  -14, 	   7,  -12, 	  -9,  -12, 	  -1,   -8
.2byte   -6,  -14, 	   4,   -7, 	  -8,   -5, 	  -1,   -9
.2byte   -5,  -14, 	   5,  -14, 	  -7,  -11, 	   0,   -8
.2byte   -6,   -9, 	  -5,   -7, 	  -5,   -4, 	  -1,   -8
.2byte   -8,  -10, 	   3,  -17, 	   5,  -10, 	   1,   -9
.2byte   -5,   -7, 	  -9,   -4, 	   1,   -2, 	   0,   -7
.2byte   -5,   -7, 	  -7,  -16, 	   8,  -11, 	   0,   -7
.2byte   -8,   -3, 	  -3,   -6, 	   3,   -4, 	   0,   -5
.2byte   -8,   -1, 	  -3,   -5, 	   3,   -3, 	   0,   -4
.2byte    0,    2, 	  -7,   -9, 	   7,   -9, 	   0,   -5
.2byte    5,    1, 	   6,  -11, 	  -8,   -9, 	  -1,   -6
.2byte    8,   -3, 	  -3,  -11, 	  -6,   -9, 	  -1,   -6
.2byte    6,   -7, 	  -8,   -8, 	  -1,   -3, 	  -1,   -4
.2byte    0,   -4, 	   7,   -6, 	  -7,   -6, 	   0,   -5
.2byte   -7,   -7, 	   7,   -8, 	   0,   -3, 	   0,   -4
.2byte   -9,   -3, 	   2,  -11, 	   5,   -9, 	   0,   -6
.2byte   -6,    1, 	  -7,  -11, 	   7,   -9, 	   0,   -6
.2byte   -1,   -3, 	  -6,   -4, 	   4,   -4, 	  -1,   -5
.2byte   -1,   -6, 	  -6,   -7, 	   4,   -7, 	  -1,   -8
.2byte   -1,    0, 	  -6,   -2, 	   4,   -2, 	  -1,   -2
.2byte    6,   -5, 	   3,   -6, 	  -4,   -4, 	   1,   -6
.2byte    7,   -7, 	   3,  -10, 	  -6,   -8, 	   1,   -7
.2byte    7,   -3, 	   4,   -7, 	  -5,   -4, 	   1,   -4
.2byte    8,   -7, 	  -3,   -6, 	  -5,   -3, 	   1,   -6
.2byte    9,  -10, 	  -3,   -8, 	  -5,   -5, 	   1,   -8
.2byte   11,   -4, 	  -1,   -5, 	  -3,   -2, 	   2,   -4
.2byte    6,  -10, 	  -6,   -4, 	  -1,   -2, 	   0,   -7
.2byte    7,  -12, 	  -6,   -6, 	  -1,   -4, 	   0,   -8
.2byte    8,   -9, 	  -4,   -6, 	  -1,   -1, 	   1,   -6
.2byte   -1,   -9, 	   2,   -4, 	  -4,   -4, 	  -1,   -6
.2byte   -1,  -14, 	   2,   -6, 	  -4,   -6, 	  -1,   -8
.2byte   -1,   -8, 	   3,   -3, 	  -5,   -3, 	  -1,   -6
.2byte   -7,  -10, 	   5,   -4, 	   0,   -2, 	  -1,   -7
.2byte   -8,  -12, 	   5,   -6, 	   0,   -4, 	  -1,   -8
.2byte   -9,   -9, 	   3,   -6, 	   0,   -1, 	  -2,   -6
.2byte   -9,   -7, 	   2,   -6, 	   4,   -3, 	  -2,   -6
.2byte  -10,  -10, 	   2,   -8, 	   4,   -5, 	  -2,   -8
.2byte  -12,   -4, 	   0,   -5, 	   2,   -2, 	  -3,   -4
.2byte   -7,   -5, 	  -4,   -6, 	   3,   -4, 	  -2,   -6
.2byte   -8,   -7, 	  -4,  -10, 	   5,   -8, 	  -2,   -7
.2byte   -8,   -3, 	  -5,   -7, 	   4,   -4, 	  -2,   -4
.2byte   -1,    0, 	 -11,   -7, 	   9,   -7, 	  -1,   -5
.2byte   -8,   -3, 	 -10,  -12, 	   6,   -3, 	  -1,   -8
.2byte  -10,   -6, 	  -1,  -14, 	  -1,   -1, 	  -1,   -8
.2byte   -7,  -13, 	   7,  -11, 	  -8,   -4, 	   0,   -9
.2byte   -1,  -11, 	   7,   -8, 	 -10,   -8, 	  -1,   -8
.2byte    6,  -13, 	  -8,  -11, 	   7,   -4, 	  -1,   -9
.2byte    9,   -6, 	   0,  -14, 	   0,   -1, 	   0,   -8
.2byte    7,   -3, 	   9,  -12, 	  -7,   -3, 	   0,   -8
.2byte   -1,   -6, 	  -9,  -15, 	   7,  -15, 	  -1,   -7
.2byte    4,   -7, 	   6,  -16, 	  -9,  -11, 	  -1,   -7
.2byte    7,  -10, 	  -4,  -17, 	  -6,  -10, 	  -2,   -9
.2byte    3,  -14, 	  -7,  -14, 	   5,  -11, 	  -2,   -8
.2byte   -1,  -14, 	   7,  -12, 	  -9,  -12, 	  -1,   -8
.2byte   -4,  -14, 	   6,  -14, 	  -6,  -11, 	   1,   -8
.2byte   -8,  -10, 	   3,  -17, 	   5,  -10, 	   1,   -9
.2byte   -5,   -7, 	  -7,  -16, 	   8,  -11, 	   0,   -7
.2byte   -1,    0, 	  -6,   -2, 	   4,   -2, 	  -1,   -2
.2byte   -1,   -6, 	  -8,   -2, 	   6,   -2, 	  -1,   -7
.2byte   -1,   -6, 	  -9,  -15, 	   7,  -15, 	  -1,   -7
.2byte    7,   -4, 	   4,   -8, 	  -5,   -5, 	   1,   -5
.2byte    4,   -7, 	   8,   -4, 	  -2,   -2, 	  -1,   -7
.2byte    4,   -7, 	   6,  -16, 	  -9,  -11, 	  -1,   -7
.2byte    9,   -4, 	  -3,   -5, 	  -5,   -2, 	   0,   -4
.2byte    5,   -9, 	   4,   -7, 	   4,   -4, 	   0,   -8
.2byte    7,  -10, 	  -4,  -17, 	  -6,  -10, 	  -2,   -9
.2byte    7,   -9, 	  -5,   -6, 	  -2,   -1, 	   0,   -6
.2byte    4,  -14, 	  -6,   -7, 	   6,   -5, 	  -1,   -9
.2byte    3,  -14, 	  -7,  -14, 	   5,  -11, 	  -2,   -8
.2byte   -1,   -7, 	   3,   -2, 	  -5,   -2, 	  -1,   -5
.2byte   -1,  -13, 	   6,   -5, 	  -8,   -5, 	  -1,   -9
.2byte   -1,  -14, 	   7,  -12, 	  -9,  -12, 	  -1,   -8
.2byte   -8,   -9, 	   4,   -6, 	   1,   -1, 	  -1,   -6
.2byte   -5,  -14, 	   5,   -7, 	  -7,   -5, 	   0,   -9
.2byte   -4,  -14, 	   6,  -14, 	  -6,  -11, 	   1,   -8
.2byte  -10,   -4, 	   2,   -5, 	   4,   -2, 	  -1,   -4
.2byte   -6,   -9, 	  -5,   -7, 	  -5,   -4, 	  -1,   -8
.2byte   -8,  -10, 	   3,  -17, 	   5,  -10, 	   1,   -9
.2byte   -8,   -4, 	  -5,   -8, 	   4,   -5, 	  -2,   -5
.2byte   -5,   -7, 	  -9,   -4, 	   1,   -2, 	   0,   -7
.2byte   -5,   -7, 	  -7,  -16, 	   8,  -11, 	   0,   -7
.2byte   -1,   -6, 	  -9,  -15, 	   7,  -15, 	  -1,   -7
.2byte   -5,   -7, 	  -7,  -16, 	   8,  -11, 	   0,   -7
.2byte   -8,  -10, 	   3,  -17, 	   5,  -10, 	   1,   -9
.2byte   -4,  -14, 	   6,  -14, 	  -6,  -11, 	   1,   -8
.2byte   -1,  -14, 	   7,  -12, 	  -9,  -12, 	  -1,   -8
.2byte    3,  -14, 	  -7,  -14, 	   5,  -11, 	  -2,   -8
.2byte    7,  -10, 	  -4,  -17, 	  -6,  -10, 	  -2,   -9
.2byte    4,   -7, 	   6,  -16, 	  -9,  -11, 	  -1,   -7
.2byte   -1,   -3, 	  -6,   -4, 	   4,   -4, 	  -1,   -5
.2byte   -7,   -5, 	  -4,   -6, 	   3,   -4, 	  -2,   -6
.2byte   -9,   -7, 	   2,   -6, 	   4,   -3, 	  -2,   -6
.2byte   -7,  -10, 	   5,   -4, 	   0,   -2, 	  -1,   -7
.2byte   -1,   -9, 	   2,   -4, 	  -4,   -4, 	  -1,   -6
.2byte    6,  -10, 	  -6,   -4, 	  -1,   -2, 	   0,   -7
.2byte    8,   -7, 	  -3,   -6, 	  -5,   -3, 	   1,   -6
.2byte    6,   -5, 	   3,   -6, 	  -4,   -4, 	   1,   -6
sPidgeyAnimTable1:
.4byte sPidgeyAnims_1_1
.4byte sPidgeyAnims_1_2
.4byte sPidgeyAnims_1_3
.4byte sPidgeyAnims_1_4
.4byte sPidgeyAnims_1_5
.4byte sPidgeyAnims_1_6
.4byte sPidgeyAnims_1_7
.4byte sPidgeyAnims_1_8
sPidgeyAnimTable2:
.4byte sPidgeyAnims_2_1
.4byte sPidgeyAnims_2_2
.4byte sPidgeyAnims_2_3
.4byte sPidgeyAnims_2_4
.4byte sPidgeyAnims_2_5
.4byte sPidgeyAnims_2_6
.4byte sPidgeyAnims_2_7
.4byte sPidgeyAnims_2_8
sPidgeyAnimTable3:
.4byte sPidgeyAnims_3_1
.4byte sPidgeyAnims_3_2
.4byte sPidgeyAnims_3_3
.4byte sPidgeyAnims_3_4
.4byte sPidgeyAnims_3_5
.4byte sPidgeyAnims_3_6
.4byte sPidgeyAnims_3_7
.4byte sPidgeyAnims_3_8
sPidgeyAnimTable4:
.4byte sPidgeyAnims_4_1
.4byte sPidgeyAnims_4_2
.4byte sPidgeyAnims_4_3
.4byte sPidgeyAnims_4_4
.4byte sPidgeyAnims_4_5
.4byte sPidgeyAnims_4_6
.4byte sPidgeyAnims_4_7
.4byte sPidgeyAnims_4_8
sPidgeyAnimTable5:
.4byte sPidgeyAnims_5_1
.4byte sPidgeyAnims_5_2
.4byte sPidgeyAnims_5_3
.4byte sPidgeyAnims_5_4
.4byte sPidgeyAnims_5_5
.4byte sPidgeyAnims_5_6
.4byte sPidgeyAnims_5_7
.4byte sPidgeyAnims_5_8
sPidgeyAnimTable6:
.4byte sPidgeyAnims_6_1
.4byte sPidgeyAnims_6_1
.4byte sPidgeyAnims_6_1
.4byte sPidgeyAnims_6_1
.4byte sPidgeyAnims_6_1
.4byte sPidgeyAnims_6_1
.4byte sPidgeyAnims_6_1
.4byte sPidgeyAnims_6_1
sPidgeyAnimTable7:
.4byte sPidgeyAnims_7_1
.4byte sPidgeyAnims_7_2
.4byte sPidgeyAnims_7_3
.4byte sPidgeyAnims_7_4
.4byte sPidgeyAnims_7_5
.4byte sPidgeyAnims_7_6
.4byte sPidgeyAnims_7_7
.4byte sPidgeyAnims_7_8
sPidgeyAnimTable8:
.4byte sPidgeyAnims_8_1
.4byte sPidgeyAnims_8_2
.4byte sPidgeyAnims_8_3
.4byte sPidgeyAnims_8_4
.4byte sPidgeyAnims_8_5
.4byte sPidgeyAnims_8_6
.4byte sPidgeyAnims_8_7
.4byte sPidgeyAnims_8_8
sPidgeyAnimTable9:
.4byte sPidgeyAnims_9_1
.4byte sPidgeyAnims_9_2
.4byte sPidgeyAnims_9_3
.4byte sPidgeyAnims_9_4
.4byte sPidgeyAnims_9_5
.4byte sPidgeyAnims_9_6
.4byte sPidgeyAnims_9_7
.4byte sPidgeyAnims_9_8
sPidgeyAnimTable10:
.4byte sPidgeyAnims_10_1
.4byte sPidgeyAnims_10_2
.4byte sPidgeyAnims_10_3
.4byte sPidgeyAnims_10_4
.4byte sPidgeyAnims_10_5
.4byte sPidgeyAnims_10_6
.4byte sPidgeyAnims_10_7
.4byte sPidgeyAnims_10_8
sPidgeyAnimTable11:
.4byte sPidgeyAnims_11_1
.4byte sPidgeyAnims_11_2
.4byte sPidgeyAnims_11_3
.4byte sPidgeyAnims_11_4
.4byte sPidgeyAnims_11_5
.4byte sPidgeyAnims_11_6
.4byte sPidgeyAnims_11_7
.4byte sPidgeyAnims_11_8
sPidgeyAnimTable12:
.4byte sPidgeyAnims_12_1
.4byte sPidgeyAnims_12_2
.4byte sPidgeyAnims_12_3
.4byte sPidgeyAnims_12_4
.4byte sPidgeyAnims_12_5
.4byte sPidgeyAnims_12_6
.4byte sPidgeyAnims_12_7
.4byte sPidgeyAnims_12_8
sPidgeyAnimTable13:
.4byte sPidgeyAnims_13_1
.4byte sPidgeyAnims_13_2
.4byte sPidgeyAnims_13_3
.4byte sPidgeyAnims_13_4
.4byte sPidgeyAnims_13_5
.4byte sPidgeyAnims_13_6
.4byte sPidgeyAnims_13_7
.4byte sPidgeyAnims_13_8
sAxAnimationsPidgey:
.4byte sPidgeyAnimTable1
.4byte sPidgeyAnimTable2
.4byte sPidgeyAnimTable3
.4byte sPidgeyAnimTable4
.4byte sPidgeyAnimTable5
.4byte sPidgeyAnimTable6
.4byte sPidgeyAnimTable7
.4byte sPidgeyAnimTable8
.4byte sPidgeyAnimTable9
.4byte sPidgeyAnimTable10
.4byte sPidgeyAnimTable11
.4byte sPidgeyAnimTable12
.4byte sPidgeyAnimTable13
sAxSpritesPidgey:
.4byte sPidgeySprites1
.4byte sPidgeySprites2
.4byte sPidgeySprites3
.4byte sPidgeySprites4
.4byte sPidgeySprites5
.4byte sPidgeySprites6
.4byte sPidgeySprites7
.4byte sPidgeySprites8
.4byte sPidgeySprites9
.4byte sPidgeySprites10
.4byte sPidgeySprites11
.4byte sPidgeySprites12
.4byte sPidgeySprites13
.4byte sPidgeySprites14
.4byte sPidgeySprites15
.4byte sPidgeySprites16
.4byte sPidgeySprites17
.4byte sPidgeySprites18
.4byte sPidgeySprites19
.4byte sPidgeySprites20
.4byte sPidgeySprites21
.4byte sPidgeySprites22
.4byte sPidgeySprites23
.4byte sPidgeySprites24
.4byte sPidgeySprites25
.4byte sPidgeySprites26
.4byte sPidgeySprites27
.4byte sPidgeySprites28
.4byte sPidgeySprites29
.4byte sPidgeySprites30
.4byte sPidgeySprites31
.4byte sPidgeySprites32
.4byte sPidgeySprites33
.4byte sPidgeySprites34
.4byte sPidgeySprites35
.4byte sPidgeySprites36
.4byte sPidgeySprites37
sAxMainPidgey:
ax_main sAxPosesPidgey, sAxAnimationsPidgey, 13, sAxSpritesPidgey, sAxPositionsPidgey
