.global gAxPikachu
gAxPikachu:
ax_siro sAxMainPikachu
sPikachuPose1:
ax_pose 0, 0x01e5, 0x80f4, 0x0c00
ax_pose_terminator
sPikachuPose2:
ax_pose 1, 0x01ea, 0x80f4, 0x0c00
ax_pose_terminator
sPikachuPose3:
ax_pose 2, 0x01e5, 0x80f4, 0x0c00
ax_pose_terminator
sPikachuPose4:
ax_pose 3, 0x01e5, 0x90ea, 0x0c00
ax_pose_terminator
sPikachuPose5:
ax_pose 4, 0x01eb, 0x90ea, 0x0c00
ax_pose_terminator
sPikachuPose6:
ax_pose 5, 0x01e5, 0x90ea, 0x0c00
ax_pose_terminator
sPikachuPose7:
ax_pose 6, 0x01ea, 0x90ea, 0x0c00
ax_pose_terminator
sPikachuPose8:
ax_pose 7, 0x01ea, 0x90ea, 0x0c00
ax_pose_terminator
sPikachuPose9:
ax_pose 8, 0x01ea, 0x90ea, 0x0c00
ax_pose_terminator
sPikachuPose10:
ax_pose 9, 0x01ea, 0x90ea, 0x0c00
ax_pose_terminator
sPikachuPose11:
ax_pose 10, 0x01ea, 0x90ea, 0x0c00
ax_pose_terminator
sPikachuPose12:
ax_pose 11, 0x01e5, 0x90f0, 0x0c00
ax_pose_terminator
sPikachuPose13:
ax_pose 12, 0x01ea, 0x80f3, 0x0c00
ax_pose_terminator
sPikachuPose14:
ax_pose 13, 0x01e5, 0x80f3, 0x0c00
ax_pose_terminator
sPikachuPose15:
ax_pose 14, 0x01e5, 0x80f3, 0x0c00
ax_pose_terminator
sPikachuPose16:
ax_pose 9, 0x01ea, 0x80f6, 0x0c00
ax_pose_terminator
sPikachuPose17:
ax_pose 10, 0x01ea, 0x80f6, 0x0c00
ax_pose_terminator
sPikachuPose18:
ax_pose 11, 0x01e5, 0x80f0, 0x0c00
ax_pose_terminator
sPikachuPose19:
ax_pose 6, 0x01ea, 0x80f6, 0x0c00
ax_pose_terminator
sPikachuPose20:
ax_pose 7, 0x01ea, 0x80f6, 0x0c00
ax_pose_terminator
sPikachuPose21:
ax_pose 8, 0x01ea, 0x80f6, 0x0c00
ax_pose_terminator
sPikachuPose22:
ax_pose 3, 0x01e5, 0x80f6, 0x0c00
ax_pose_terminator
sPikachuPose23:
ax_pose 4, 0x01eb, 0x80f6, 0x0c00
ax_pose_terminator
sPikachuPose24:
ax_pose 5, 0x01e5, 0x80f6, 0x0c00
ax_pose_terminator
sPikachuPose25:
ax_pose 0, 0x01e5, 0x80f4, 0x0c00
ax_pose_terminator
sPikachuPose26:
ax_pose 1, 0x01e6, 0x80f4, 0x0c00
ax_pose_terminator
sPikachuPose27:
ax_pose 2, 0x01e5, 0x80f4, 0x0c00
ax_pose_terminator
sPikachuPose28:
ax_pose 15, 0x01e5, 0x80f4, 0x0c00
ax_pose_terminator
sPikachuPose29:
ax_pose 3, 0x01e5, 0x90ea, 0x0c00
ax_pose_terminator
sPikachuPose30:
ax_pose 4, 0x01eb, 0x90ea, 0x0c00
ax_pose_terminator
sPikachuPose31:
ax_pose 5, 0x01e5, 0x90ea, 0x0c00
ax_pose_terminator
sPikachuPose32:
ax_pose 16, 0x01e5, 0x90ed, 0x0c00
ax_pose_terminator
sPikachuPose33:
ax_pose 6, 0x01ea, 0x90ea, 0x0c00
ax_pose_terminator
sPikachuPose34:
ax_pose 7, 0x01ea, 0x90ea, 0x0c00
ax_pose_terminator
sPikachuPose35:
ax_pose 8, 0x01ea, 0x90ea, 0x0c00
ax_pose_terminator
sPikachuPose36:
ax_pose 17, 0x01ea, 0x90eb, 0x0c00
ax_pose_terminator
sPikachuPose37:
ax_pose 9, 0x01ea, 0x90ea, 0x0c00
ax_pose_terminator
sPikachuPose38:
ax_pose 10, 0x01ea, 0x90ea, 0x0c00
ax_pose_terminator
sPikachuPose39:
ax_pose 11, 0x01e5, 0x90f0, 0x0c00
ax_pose_terminator
sPikachuPose40:
ax_pose 18, 0x01e9, 0x90eb, 0x0c00
ax_pose_terminator
sPikachuPose41:
ax_pose 12, 0x01ea, 0x80f3, 0x0c00
ax_pose_terminator
sPikachuPose42:
ax_pose 13, 0x01e5, 0x80f3, 0x0c00
ax_pose_terminator
sPikachuPose43:
ax_pose 14, 0x01e5, 0x80f3, 0x0c00
ax_pose_terminator
sPikachuPose44:
ax_pose 19, 0x01e9, 0x80f3, 0x0c00
ax_pose_terminator
sPikachuPose45:
ax_pose 9, 0x01ea, 0x80f6, 0x0c00
ax_pose_terminator
sPikachuPose46:
ax_pose 10, 0x01ea, 0x80f6, 0x0c00
ax_pose_terminator
sPikachuPose47:
ax_pose 11, 0x01e5, 0x80f0, 0x0c00
ax_pose_terminator
sPikachuPose48:
ax_pose 18, 0x01e9, 0x80f5, 0x0c00
ax_pose_terminator
sPikachuPose49:
ax_pose 6, 0x01ea, 0x80f6, 0x0c00
ax_pose_terminator
sPikachuPose50:
ax_pose 7, 0x01ea, 0x80f6, 0x0c00
ax_pose_terminator
sPikachuPose51:
ax_pose 8, 0x01ea, 0x80f6, 0x0c00
ax_pose_terminator
sPikachuPose52:
ax_pose 17, 0x01ea, 0x80f5, 0x0c00
ax_pose_terminator
sPikachuPose53:
ax_pose 3, 0x01e5, 0x80f6, 0x0c00
ax_pose_terminator
sPikachuPose54:
ax_pose 4, 0x01eb, 0x80f6, 0x0c00
ax_pose_terminator
sPikachuPose55:
ax_pose 5, 0x01e5, 0x80f6, 0x0c00
ax_pose_terminator
sPikachuPose56:
ax_pose 16, 0x01e5, 0x80f3, 0x0c00
ax_pose_terminator
sPikachuPose57:
ax_pose 0, 0x01e5, 0x80f4, 0x0c00
ax_pose_terminator
sPikachuPose58:
ax_pose 1, 0x01e6, 0x80f4, 0x0c00
ax_pose_terminator
sPikachuPose59:
ax_pose 2, 0x01e5, 0x80f4, 0x0c00
ax_pose_terminator
sPikachuPose60:
ax_pose 15, 0x01e5, 0x80f4, 0x0c00
ax_pose_terminator
sPikachuPose61:
ax_pose 3, 0x01e5, 0x90ea, 0x0c00
ax_pose_terminator
sPikachuPose62:
ax_pose 4, 0x01eb, 0x90ea, 0x0c00
ax_pose_terminator
sPikachuPose63:
ax_pose 5, 0x01e5, 0x90ea, 0x0c00
ax_pose_terminator
sPikachuPose64:
ax_pose 16, 0x01e5, 0x90ed, 0x0c00
ax_pose_terminator
sPikachuPose65:
ax_pose 6, 0x01ea, 0x90ea, 0x0c00
ax_pose_terminator
sPikachuPose66:
ax_pose 7, 0x01ea, 0x90ea, 0x0c00
ax_pose_terminator
sPikachuPose67:
ax_pose 8, 0x01ea, 0x90ea, 0x0c00
ax_pose_terminator
sPikachuPose68:
ax_pose 17, 0x01ea, 0x90eb, 0x0c00
ax_pose_terminator
sPikachuPose69:
ax_pose 9, 0x01ea, 0x90ea, 0x0c00
ax_pose_terminator
sPikachuPose70:
ax_pose 10, 0x01ea, 0x90ea, 0x0c00
ax_pose_terminator
sPikachuPose71:
ax_pose 11, 0x01e5, 0x90f0, 0x0c00
ax_pose_terminator
sPikachuPose72:
ax_pose 18, 0x01e9, 0x90eb, 0x0c00
ax_pose_terminator
sPikachuPose73:
ax_pose 12, 0x01ea, 0x80f3, 0x0c00
ax_pose_terminator
sPikachuPose74:
ax_pose 13, 0x01e5, 0x80f3, 0x0c00
ax_pose_terminator
sPikachuPose75:
ax_pose 14, 0x01e5, 0x80f3, 0x0c00
ax_pose_terminator
sPikachuPose76:
ax_pose 19, 0x01e9, 0x80f3, 0x0c00
ax_pose_terminator
sPikachuPose77:
ax_pose 9, 0x01ea, 0x80f6, 0x0c00
ax_pose_terminator
sPikachuPose78:
ax_pose 10, 0x01ea, 0x80f6, 0x0c00
ax_pose_terminator
sPikachuPose79:
ax_pose 11, 0x01e5, 0x80f0, 0x0c00
ax_pose_terminator
sPikachuPose80:
ax_pose 18, 0x01e9, 0x80f5, 0x0c00
ax_pose_terminator
sPikachuPose81:
ax_pose 6, 0x01ea, 0x80f6, 0x0c00
ax_pose_terminator
sPikachuPose82:
ax_pose 7, 0x01ea, 0x80f6, 0x0c00
ax_pose_terminator
sPikachuPose83:
ax_pose 8, 0x01ea, 0x80f6, 0x0c00
ax_pose_terminator
sPikachuPose84:
ax_pose 17, 0x01ea, 0x80f5, 0x0c00
ax_pose_terminator
sPikachuPose85:
ax_pose 3, 0x01e5, 0x80f6, 0x0c00
ax_pose_terminator
sPikachuPose86:
ax_pose 4, 0x01eb, 0x80f6, 0x0c00
ax_pose_terminator
sPikachuPose87:
ax_pose 5, 0x01e5, 0x80f6, 0x0c00
ax_pose_terminator
sPikachuPose88:
ax_pose 16, 0x01e5, 0x80f3, 0x0c00
ax_pose_terminator
sPikachuPose89:
ax_pose 0, 0x01e5, 0x80f4, 0x0c00
ax_pose_terminator
sPikachuPose90:
ax_pose 20, 0x01e5, 0x80f4, 0x0c00
ax_pose_terminator
sPikachuPose91:
ax_pose 3, 0x01e5, 0x90ea, 0x0c00
ax_pose_terminator
sPikachuPose92:
ax_pose 21, 0x01e5, 0x90ea, 0x0c00
ax_pose_terminator
sPikachuPose93:
ax_pose 6, 0x01ea, 0x90ea, 0x0c00
ax_pose_terminator
sPikachuPose94:
ax_pose 22, 0x01ea, 0x90eb, 0x0c00
ax_pose_terminator
sPikachuPose95:
ax_pose 9, 0x01ea, 0x90ea, 0x0c00
ax_pose_terminator
sPikachuPose96:
ax_pose 23, 0x01ea, 0x90eb, 0x0c00
ax_pose_terminator
sPikachuPose97:
ax_pose 12, 0x01ea, 0x80f3, 0x0c00
ax_pose_terminator
sPikachuPose98:
ax_pose 24, 0x01ea, 0x80f3, 0x0c00
ax_pose_terminator
sPikachuPose99:
ax_pose 9, 0x01ea, 0x80f6, 0x0c00
ax_pose_terminator
sPikachuPose100:
ax_pose 23, 0x01ea, 0x80f5, 0x0c00
ax_pose_terminator
sPikachuPose101:
ax_pose 6, 0x01ea, 0x80f6, 0x0c00
ax_pose_terminator
sPikachuPose102:
ax_pose 22, 0x01ea, 0x80f5, 0x0c00
ax_pose_terminator
sPikachuPose103:
ax_pose 3, 0x01e5, 0x80f6, 0x0c00
ax_pose_terminator
sPikachuPose104:
ax_pose 21, 0x01e5, 0x80f6, 0x0c00
ax_pose_terminator
sPikachuPose105:
ax_pose 0, 0x01e5, 0x80f4, 0x0c00
ax_pose_terminator
sPikachuPose106:
ax_pose 20, 0x01e5, 0x80f4, 0x0c00
ax_pose_terminator
sPikachuPose107:
ax_pose 25, 0x01de, 0x80eb, 0x0c00
ax_pose 26, 0x81de, 0x410b, 0x0c10
ax_pose 27, 0x41fe, 0x40eb, 0x0c14
ax_pose 28, 0x01e5, 0x80f4, 0x0c18
ax_pose_terminator
sPikachuPose108:
ax_pose 29, 0x01de, 0x80eb, 0x0c00
ax_pose 30, 0x81de, 0x410b, 0x0c10
ax_pose 31, 0x41fe, 0x00eb, 0x0c14
ax_pose 32, 0x41fe, 0x0103, 0x0c16
ax_pose 33, 0x01e5, 0x80f4, 0x0c18
ax_pose_terminator
sPikachuPose109:
ax_pose 28, 0x01e5, 0x80f4, 0x0c00
ax_pose_terminator
sPikachuPose110:
ax_pose 33, 0x01e5, 0x80f4, 0x0c00
ax_pose_terminator
sPikachuPose111:
ax_pose 3, 0x01e5, 0x90ea, 0x0c00
ax_pose_terminator
sPikachuPose112:
ax_pose 21, 0x01e5, 0x90ea, 0x0c00
ax_pose_terminator
sPikachuPose113:
ax_pose 34, 0x01dd, 0x90f5, 0x0c00
ax_pose 35, 0x81dd, 0x50ed, 0x0c10
ax_pose 36, 0x41fd, 0x10ed, 0x0c14
ax_pose 37, 0x01e5, 0x90ea, 0x0c16
ax_pose_terminator
sPikachuPose114:
ax_pose 38, 0x01dd, 0x90f5, 0x0c00
ax_pose 39, 0x81dd, 0x50ed, 0x0c10
ax_pose 40, 0x41fd, 0x10ed, 0x0c14
ax_pose 41, 0x01e5, 0x90ea, 0x0c16
ax_pose_terminator
sPikachuPose115:
ax_pose 37, 0x01e5, 0x90ea, 0x0c00
ax_pose_terminator
sPikachuPose116:
ax_pose 41, 0x01e5, 0x90ea, 0x0c00
ax_pose_terminator
sPikachuPose117:
ax_pose 6, 0x01ea, 0x90ea, 0x0c00
ax_pose_terminator
sPikachuPose118:
ax_pose 22, 0x01ea, 0x90eb, 0x0c00
ax_pose_terminator
sPikachuPose119:
ax_pose 42, 0x01df, 0x90f3, 0x0c00
ax_pose 43, 0x81df, 0x50eb, 0x0c10
ax_pose 44, 0x01ff, 0x10f3, 0x0c14
ax_pose 45, 0x01e9, 0x90ea, 0x0c15
ax_pose_terminator
sPikachuPose120:
ax_pose 29, 0x01df, 0x90f3, 0x0c00
ax_pose 30, 0x81df, 0x50eb, 0x0c10
ax_pose 31, 0x41ff, 0x1103, 0x0c14
ax_pose 32, 0x41ff, 0x10eb, 0x0c16
ax_pose 46, 0x01e9, 0x90ea, 0x0c18
ax_pose_terminator
sPikachuPose121:
ax_pose 45, 0x01e9, 0x90ea, 0x0c00
ax_pose_terminator
sPikachuPose122:
ax_pose 46, 0x01e9, 0x90ea, 0x0c00
ax_pose_terminator
sPikachuPose123:
ax_pose 9, 0x01ea, 0x90ea, 0x0c00
ax_pose_terminator
sPikachuPose124:
ax_pose 23, 0x01ea, 0x90eb, 0x0c00
ax_pose_terminator
sPikachuPose125:
ax_pose 47, 0x01dc, 0x90f3, 0x0c00
ax_pose 48, 0x81dc, 0x50eb, 0x0c10
ax_pose 49, 0x41fc, 0x1103, 0x0c14
ax_pose 50, 0x01e7, 0x90eb, 0x0c16
ax_pose_terminator
sPikachuPose126:
ax_pose 38, 0x01dd, 0x80ea, 0x0c00
ax_pose 39, 0x81dd, 0x410a, 0x0c10
ax_pose 40, 0x41fd, 0x0102, 0x0c14
ax_pose 51, 0x01e7, 0x90eb, 0x0c16
ax_pose_terminator
sPikachuPose127:
ax_pose 50, 0x01e7, 0x90eb, 0x0c00
ax_pose_terminator
sPikachuPose128:
ax_pose 51, 0x01e7, 0x90eb, 0x0c00
ax_pose_terminator
sPikachuPose129:
ax_pose 12, 0x01ea, 0x80f3, 0x0c00
ax_pose_terminator
sPikachuPose130:
ax_pose 24, 0x01ea, 0x80f3, 0x0c00
ax_pose_terminator
sPikachuPose131:
ax_pose 52, 0x01e2, 0x80eb, 0x0c00
ax_pose 53, 0x81e2, 0x410b, 0x0c10
ax_pose 54, 0x01ea, 0x80f3, 0x0c14
ax_pose_terminator
sPikachuPose132:
ax_pose 29, 0x01df, 0x80eb, 0x0c00
ax_pose 32, 0x41ff, 0x0103, 0x0c10
ax_pose 31, 0x41ff, 0x00eb, 0x0c12
ax_pose 30, 0x81df, 0x410b, 0x0c14
ax_pose 55, 0x01ea, 0x80f3, 0x0c18
ax_pose_terminator
sPikachuPose133:
ax_pose 54, 0x01ea, 0x80f3, 0x0c00
ax_pose_terminator
sPikachuPose134:
ax_pose 55, 0x01ea, 0x80f3, 0x0c00
ax_pose_terminator
sPikachuPose135:
ax_pose 9, 0x01ea, 0x80f6, 0x0c00
ax_pose_terminator
sPikachuPose136:
ax_pose 23, 0x01ea, 0x80f5, 0x0c00
ax_pose_terminator
sPikachuPose137:
ax_pose 47, 0x01dc, 0x80ed, 0x0c00
ax_pose 48, 0x81dc, 0x410d, 0x0c10
ax_pose 49, 0x41fc, 0x00ed, 0x0c14
ax_pose 50, 0x01e7, 0x80f5, 0x0c16
ax_pose_terminator
sPikachuPose138:
ax_pose 38, 0x01dd, 0x90f5, 0x0c00
ax_pose 39, 0x81dd, 0x50ed, 0x0c10
ax_pose 40, 0x41fd, 0x10ed, 0x0c14
ax_pose 51, 0x01e7, 0x80f5, 0x0c16
ax_pose_terminator
sPikachuPose139:
ax_pose 50, 0x01e7, 0x80f5, 0x0c00
ax_pose_terminator
sPikachuPose140:
ax_pose 51, 0x01e7, 0x80f5, 0x0c00
ax_pose_terminator
sPikachuPose141:
ax_pose 6, 0x01ea, 0x80f6, 0x0c00
ax_pose_terminator
sPikachuPose142:
ax_pose 22, 0x01ea, 0x80f5, 0x0c00
ax_pose_terminator
sPikachuPose143:
ax_pose 42, 0x01df, 0x80ed, 0x0c00
ax_pose 43, 0x81df, 0x410d, 0x0c10
ax_pose 44, 0x01ff, 0x0105, 0x0c14
ax_pose 45, 0x01e9, 0x80f6, 0x0c15
ax_pose_terminator
sPikachuPose144:
ax_pose 29, 0x01df, 0x90f6, 0x0c00
ax_pose 30, 0x81df, 0x50ee, 0x0c10
ax_pose 31, 0x41ff, 0x1106, 0x0c14
ax_pose 32, 0x41ff, 0x10ee, 0x0c16
ax_pose 46, 0x01e9, 0x80f6, 0x0c18
ax_pose_terminator
sPikachuPose145:
ax_pose 45, 0x01e9, 0x80f6, 0x0c00
ax_pose_terminator
sPikachuPose146:
ax_pose 46, 0x01e9, 0x80f6, 0x0c00
ax_pose_terminator
sPikachuPose147:
ax_pose 3, 0x01e5, 0x80f6, 0x0c00
ax_pose_terminator
sPikachuPose148:
ax_pose 21, 0x01e5, 0x80f6, 0x0c00
ax_pose_terminator
sPikachuPose149:
ax_pose 34, 0x01dd, 0x80eb, 0x0c00
ax_pose 35, 0x81dd, 0x410b, 0x0c10
ax_pose 36, 0x41fd, 0x0103, 0x0c14
ax_pose 37, 0x01e5, 0x80f6, 0x0c16
ax_pose_terminator
sPikachuPose150:
ax_pose 38, 0x01dd, 0x80ec, 0x0c00
ax_pose 39, 0x81dd, 0x410c, 0x0c10
ax_pose 40, 0x41fd, 0x0104, 0x0c14
ax_pose 41, 0x01e5, 0x80f6, 0x0c16
ax_pose_terminator
sPikachuPose151:
ax_pose 37, 0x01e5, 0x80f6, 0x0c00
ax_pose_terminator
sPikachuPose152:
ax_pose 41, 0x01e5, 0x80f6, 0x0c00
ax_pose_terminator
sPikachuPose153:
ax_pose 56, 0x01eb, 0x80f8, 0x0c00
ax_pose_terminator
sPikachuPose154:
ax_pose 57, 0x01eb, 0x80f8, 0x0c00
ax_pose_terminator
sPikachuPose155:
ax_pose 58, 0x01e0, 0x80f0, 0x0c00
ax_pose_terminator
sPikachuPose156:
ax_pose 59, 0x01e3, 0x90ea, 0x0c00
ax_pose_terminator
sPikachuPose157:
ax_pose 60, 0x01e3, 0x90eb, 0x0c00
ax_pose_terminator
sPikachuPose158:
ax_pose 61, 0x01e3, 0x90f0, 0x0c00
ax_pose_terminator
sPikachuPose159:
ax_pose 62, 0x01e5, 0x80ef, 0x0c00
ax_pose_terminator
sPikachuPose160:
ax_pose 61, 0x01e3, 0x80f0, 0x0c00
ax_pose_terminator
sPikachuPose161:
ax_pose 60, 0x01e3, 0x80f5, 0x0c00
ax_pose_terminator
sPikachuPose162:
ax_pose 59, 0x01e3, 0x80f6, 0x0c00
ax_pose_terminator
sPikachuPose163:
ax_pose 0, 0x01e5, 0x80f4, 0x0c00
ax_pose_terminator
sPikachuPose164:
ax_pose 3, 0x01e5, 0x80f6, 0x0c00
ax_pose_terminator
sPikachuPose165:
ax_pose 6, 0x01ea, 0x80f6, 0x0c00
ax_pose_terminator
sPikachuPose166:
ax_pose 9, 0x01ea, 0x80f6, 0x0c00
ax_pose_terminator
sPikachuPose167:
ax_pose 12, 0x01ea, 0x80f3, 0x0c00
ax_pose_terminator
sPikachuPose168:
ax_pose 9, 0x01ea, 0x90ea, 0x0c00
ax_pose_terminator
sPikachuPose169:
ax_pose 6, 0x01ea, 0x90ea, 0x0c00
ax_pose_terminator
sPikachuPose170:
ax_pose 3, 0x01e5, 0x90ea, 0x0c00
ax_pose_terminator
sPikachuPose171:
ax_pose 15, 0x01e5, 0x80f4, 0x0c00
ax_pose_terminator
sPikachuPose172:
ax_pose 16, 0x01e5, 0x80f6, 0x0c00
ax_pose_terminator
sPikachuPose173:
ax_pose 17, 0x01ea, 0x80f6, 0x0c00
ax_pose_terminator
sPikachuPose174:
ax_pose 18, 0x01ea, 0x80f6, 0x0c00
ax_pose_terminator
sPikachuPose175:
ax_pose 19, 0x01ea, 0x80f3, 0x0c00
ax_pose_terminator
sPikachuPose176:
ax_pose 18, 0x01ea, 0x90ea, 0x0c00
ax_pose_terminator
sPikachuPose177:
ax_pose 17, 0x01ea, 0x90ea, 0x0c00
ax_pose_terminator
sPikachuPose178:
ax_pose 16, 0x01e5, 0x90ea, 0x0c00
ax_pose_terminator
sPikachuPose179:
ax_pose 28, 0x01e5, 0x80f4, 0x0c00
ax_pose_terminator
sPikachuPose180:
ax_pose 37, 0x01e5, 0x80f6, 0x0c00
ax_pose_terminator
sPikachuPose181:
ax_pose 45, 0x01e9, 0x80f6, 0x0c00
ax_pose_terminator
sPikachuPose182:
ax_pose 50, 0x01e7, 0x80f5, 0x0c00
ax_pose_terminator
sPikachuPose183:
ax_pose 54, 0x01ea, 0x80f3, 0x0c00
ax_pose_terminator
sPikachuPose184:
ax_pose 50, 0x01e7, 0x90eb, 0x0c00
ax_pose_terminator
sPikachuPose185:
ax_pose 45, 0x01e9, 0x90ea, 0x0c00
ax_pose_terminator
sPikachuPose186:
ax_pose 37, 0x01e5, 0x90ea, 0x0c00
ax_pose_terminator
sPikachuPose187:
ax_pose 20, 0x01e5, 0x80f4, 0x0c00
ax_pose_terminator
sPikachuPose188:
ax_pose 21, 0x01e5, 0x90ea, 0x0c00
ax_pose_terminator
sPikachuPose189:
ax_pose 22, 0x01ea, 0x90eb, 0x0c00
ax_pose_terminator
sPikachuPose190:
ax_pose 23, 0x01ea, 0x90eb, 0x0c00
ax_pose_terminator
sPikachuPose191:
ax_pose 24, 0x01ea, 0x80f3, 0x0c00
ax_pose_terminator
sPikachuPose192:
ax_pose 23, 0x01ea, 0x80f5, 0x0c00
ax_pose_terminator
sPikachuPose193:
ax_pose 22, 0x01ea, 0x80f5, 0x0c00
ax_pose_terminator
sPikachuPose194:
ax_pose 21, 0x01e5, 0x80f6, 0x0c00
ax_pose_terminator
sPikachuPose195:
ax_pose 0, 0x01e5, 0x80f4, 0x0c00
ax_pose_terminator
sPikachuPose196:
ax_pose 1, 0x01e6, 0x80f4, 0x0c00
ax_pose_terminator
sPikachuPose197:
ax_pose 2, 0x01e5, 0x80f4, 0x0c00
ax_pose_terminator
sPikachuPose198:
ax_pose 15, 0x01e5, 0x80f4, 0x0c00
ax_pose_terminator
sPikachuPose199:
ax_pose 3, 0x01e5, 0x90ea, 0x0c00
ax_pose_terminator
sPikachuPose200:
ax_pose 4, 0x01eb, 0x90ea, 0x0c00
ax_pose_terminator
sPikachuPose201:
ax_pose 5, 0x01e5, 0x90ea, 0x0c00
ax_pose_terminator
sPikachuPose202:
ax_pose 16, 0x01e5, 0x90ec, 0x0c00
ax_pose_terminator
sPikachuPose203:
ax_pose 6, 0x01ea, 0x90ea, 0x0c00
ax_pose_terminator
sPikachuPose204:
ax_pose 7, 0x01ea, 0x90ea, 0x0c00
ax_pose_terminator
sPikachuPose205:
ax_pose 8, 0x01ea, 0x90ea, 0x0c00
ax_pose_terminator
sPikachuPose206:
ax_pose 17, 0x01ea, 0x90ea, 0x0c00
ax_pose_terminator
sPikachuPose207:
ax_pose 9, 0x01ea, 0x90ea, 0x0c00
ax_pose_terminator
sPikachuPose208:
ax_pose 10, 0x01ea, 0x90ea, 0x0c00
ax_pose_terminator
sPikachuPose209:
ax_pose 11, 0x01e5, 0x90f0, 0x0c00
ax_pose_terminator
sPikachuPose210:
ax_pose 18, 0x01e9, 0x90eb, 0x0c00
ax_pose_terminator
sPikachuPose211:
ax_pose 12, 0x01ea, 0x80f3, 0x0c00
ax_pose_terminator
sPikachuPose212:
ax_pose 13, 0x01e5, 0x80f3, 0x0c00
ax_pose_terminator
sPikachuPose213:
ax_pose 14, 0x01e5, 0x80f3, 0x0c00
ax_pose_terminator
sPikachuPose214:
ax_pose 19, 0x01e9, 0x80f3, 0x0c00
ax_pose_terminator
sPikachuPose215:
ax_pose 9, 0x01ea, 0x80f6, 0x0c00
ax_pose_terminator
sPikachuPose216:
ax_pose 10, 0x01ea, 0x80f6, 0x0c00
ax_pose_terminator
sPikachuPose217:
ax_pose 11, 0x01e5, 0x80f0, 0x0c00
ax_pose_terminator
sPikachuPose218:
ax_pose 18, 0x01e9, 0x80f5, 0x0c00
ax_pose_terminator
sPikachuPose219:
ax_pose 6, 0x01ea, 0x80f6, 0x0c00
ax_pose_terminator
sPikachuPose220:
ax_pose 7, 0x01ea, 0x80f6, 0x0c00
ax_pose_terminator
sPikachuPose221:
ax_pose 8, 0x01ea, 0x80f6, 0x0c00
ax_pose_terminator
sPikachuPose222:
ax_pose 17, 0x01ea, 0x80f6, 0x0c00
ax_pose_terminator
sPikachuPose223:
ax_pose 3, 0x01e5, 0x80f6, 0x0c00
ax_pose_terminator
sPikachuPose224:
ax_pose 4, 0x01eb, 0x80f6, 0x0c00
ax_pose_terminator
sPikachuPose225:
ax_pose 5, 0x01e5, 0x80f6, 0x0c00
ax_pose_terminator
sPikachuPose226:
ax_pose 16, 0x01e5, 0x80f4, 0x0c00
ax_pose_terminator
sPikachuPose227:
ax_pose 20, 0x01e5, 0x80f4, 0x0c00
ax_pose_terminator
sPikachuPose228:
ax_pose 21, 0x01e5, 0x80f6, 0x0c00
ax_pose_terminator
sPikachuPose229:
ax_pose 22, 0x01ea, 0x80f5, 0x0c00
ax_pose_terminator
sPikachuPose230:
ax_pose 23, 0x01ea, 0x80f5, 0x0c00
ax_pose_terminator
sPikachuPose231:
ax_pose 24, 0x01ea, 0x80f3, 0x0c00
ax_pose_terminator
sPikachuPose232:
ax_pose 23, 0x01ea, 0x90eb, 0x0c00
ax_pose_terminator
sPikachuPose233:
ax_pose 22, 0x01ea, 0x90eb, 0x0c00
ax_pose_terminator
sPikachuPose234:
ax_pose 21, 0x01e5, 0x90ea, 0x0c00
ax_pose_terminator
sPikachuPose235:
ax_pose 0, 0x01e5, 0x80f4, 0x0c00
ax_pose_terminator
sPikachuPose236:
ax_pose 3, 0x01e5, 0x80f6, 0x0c00
ax_pose_terminator
sPikachuPose237:
ax_pose 6, 0x01ea, 0x80f6, 0x0c00
ax_pose_terminator
sPikachuPose238:
ax_pose 9, 0x01ea, 0x80f6, 0x0c00
ax_pose_terminator
sPikachuPose239:
ax_pose 12, 0x01ea, 0x80f3, 0x0c00
ax_pose_terminator
sPikachuPose240:
ax_pose 9, 0x01ea, 0x90ea, 0x0c00
ax_pose_terminator
sPikachuPose241:
ax_pose 6, 0x01ea, 0x90ea, 0x0c00
ax_pose_terminator
sPikachuPose242:
ax_pose 3, 0x01e5, 0x90ea, 0x0c00
ax_pose_terminator
sPikachuPose243:
ax_pose 63, 0x01f1, 0x80f0, 0x0c00
ax_pose_terminator
sPikachuPose244:
ax_pose 64, 0x01f1, 0x80f0, 0x0c00
ax_pose_terminator
sPikachuPose245:
ax_pose 63, 0x01f1, 0x90f0, 0x0c00
ax_pose_terminator
sPikachuPose246:
ax_pose 64, 0x01f1, 0x90f0, 0x0c00
ax_pose_terminator
sPikachuPose247:
ax_pose 63, 0x01f1, 0x80f0, 0x0c00
ax_pose_terminator
sPikachuPose248:
ax_pose 65, 0x01ea, 0x80ee, 0x0c00
ax_pose_terminator
sPikachuPose249:
ax_pose 66, 0x01ea, 0x80ee, 0x0c00
ax_pose_terminator
sPikachuPose250:
ax_pose 67, 0x01ea, 0x80ee, 0x0c00
ax_pose_terminator
sPikachuPose251:
ax_pose 6, 0x01ea, 0x90ea, 0x0c00
ax_pose_terminator
sPikachuPose252:
ax_pose 12, 0x01ea, 0x80f3, 0x0c00
ax_pose_terminator
sPikachuPose253:
ax_pose 68, 0x01e9, 0x80f3, 0x0c00
ax_pose_terminator
sPikachuPose254:
ax_pose 69, 0x01e9, 0x80f3, 0x0c00
ax_pose_terminator
sPikachuPose255:
ax_pose 28, 0x01e5, 0x80f4, 0x0c00
ax_pose_terminator
sPikachuPose256:
ax_pose 70, 0x01e5, 0x80f4, 0x0c00
ax_pose_terminator
sPikachuPose257:
ax_pose 71, 0x01e5, 0x80f4, 0x0c00
ax_pose_terminator
sPikachuPose258:
ax_pose 72, 0x01e5, 0x80f4, 0x0c00
ax_pose_terminator
sPikachuPose259:
ax_pose 73, 0x01e5, 0x80f4, 0x0c00
ax_pose_terminator
sPikachuPose260:
ax_pose 74, 0x01e6, 0x80f1, 0x0c00
ax_pose_terminator
sPikachuPose261:
ax_pose 75, 0x01e6, 0x80f2, 0x0c00
ax_pose_terminator
sPikachuPose262:
ax_pose 75, 0x01e6, 0x80f2, 0x0c00
ax_pose_terminator
sPikachuPose263:
ax_pose 76, 0x01e5, 0x80f3, 0x0c00
ax_pose_terminator
sPikachuPose264:
ax_pose 77, 0x01e5, 0x80f3, 0x0c00
ax_pose_terminator
sPikachuPose265:
ax_pose 78, 0x01e5, 0x80f3, 0x0c00
ax_pose_terminator
sPikachuPose266:
ax_pose 6, 0x01ea, 0x80f6, 0x0c00
ax_pose_terminator
sPikachuPose267:
ax_pose 79, 0x01e6, 0x80f5, 0x0c00
ax_pose_terminator
sPikachuPose268:
ax_pose 80, 0x01e6, 0x80f4, 0x0c00
ax_pose_terminator
sPikachuPose269:
ax_pose 12, 0x01ea, 0x80f3, 0x0c00
ax_pose_terminator
sPikachuPose270:
ax_pose 81, 0x01ee, 0x80f2, 0x0c00
ax_pose_terminator
sPikachuPose271:
ax_pose 82, 0x01ef, 0x80f2, 0x0c00
ax_pose_terminator
sPikachuPose272:
ax_pose 0, 0x01e5, 0x80f4, 0x0c00
ax_pose_terminator
sPikachuPose273:
ax_pose 70, 0x01e5, 0x80f4, 0x0c00
ax_pose_terminator
sPikachuPose274:
ax_pose 83, 0x01e5, 0x80f4, 0x0c00
ax_pose_terminator
sPikachuPose275:
ax_pose 6, 0x01ea, 0x80f6, 0x0c00
ax_pose_terminator
sPikachuPose276:
ax_pose 84, 0x01ea, 0x80f2, 0x0c00
ax_pose_terminator
sPikachuPose277:
ax_pose 6, 0x01ea, 0x90ea, 0x0c00
ax_pose_terminator
sPikachuPose278:
ax_pose 84, 0x01ea, 0x90ee, 0x0c00
ax_pose_terminator
sPikachuPose279:
ax_pose 12, 0x01ea, 0x80f3, 0x0c00
ax_pose_terminator
sPikachuPose280:
ax_pose 85, 0x01eb, 0x80f3, 0x0c00
ax_pose_terminator
sPikachuPose281:
ax_pose 86, 0x01e6, 0x80f4, 0x0c00
ax_pose_terminator
sPikachuPose282:
ax_pose 87, 0x01e6, 0x80f4, 0x0c00
ax_pose_terminator
sPikachuPose283:
ax_pose 88, 0x01e6, 0x80f4, 0x0c00
ax_pose_terminator
sPikachuPose284:
ax_pose 89, 0x01e6, 0x80f4, 0x0c00
ax_pose_terminator
sPikachuPose285:
ax_pose 90, 0x01e6, 0x80f4, 0x0c00
ax_pose_terminator
sPikachuPose286:
ax_pose 86, 0x01e6, 0x90ec, 0x0c00
ax_pose_terminator
sPikachuPose287:
ax_pose 87, 0x01e6, 0x90ec, 0x0c00
ax_pose_terminator
sPikachuPose288:
ax_pose 88, 0x01e6, 0x90ec, 0x0c00
ax_pose_terminator
sPikachuPose289:
ax_pose 89, 0x01e6, 0x90ec, 0x0c00
ax_pose_terminator
sPikachuPose290:
ax_pose 90, 0x01e6, 0x90ec, 0x0c00
ax_pose_terminator
sPikachuPose291:
ax_pose 91, 0x01ea, 0x90ea, 0x0c00
ax_pose_terminator
sPikachuPose292:
ax_pose 63, 0x01f1, 0x80f0, 0x0c00
ax_pose_terminator
sPikachuPose293:
ax_pose 64, 0x01f1, 0x80f0, 0x0c00
ax_pose_terminator
sPikachuPose294:
ax_pose 63, 0x01f1, 0x90f0, 0x0c00
ax_pose_terminator
sPikachuPose295:
ax_pose 64, 0x01f1, 0x90f0, 0x0c00
ax_pose_terminator
sPikachuPose296:
ax_pose 63, 0x01f1, 0x80f0, 0x0c00
ax_pose_terminator
sPikachuPose297:
ax_pose 64, 0x01f1, 0x80f0, 0x0c00
ax_pose_terminator
sPikachuPose298:
ax_pose 63, 0x01f1, 0x90f0, 0x0c00
ax_pose_terminator
sPikachuPose299:
ax_pose 64, 0x01f1, 0x90f0, 0x0c00
ax_pose_terminator
.align 2
sPikachuAnims_1_1:
ax_anim 8, 0, 0, 0, 0, 0, 0,
ax_anim 10, 0, 1, 0, 0, 0, 0,
ax_anim 8, 0, 0, 0, 0, 0, 0,
ax_anim 10, 0, 2, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_1_2:
ax_anim 8, 0, 3, 0, 0, 0, 0,
ax_anim 10, 0, 4, 0, 0, 0, 0,
ax_anim 8, 0, 3, 0, 0, 0, 0,
ax_anim 10, 0, 5, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_1_3:
ax_anim 8, 0, 6, 0, 0, 0, 0,
ax_anim 10, 0, 7, 0, 0, 0, 0,
ax_anim 8, 0, 6, 0, 0, 0, 0,
ax_anim 10, 0, 8, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_1_4:
ax_anim 8, 0, 9, 0, 0, 0, 0,
ax_anim 10, 0, 10, 0, 0, 0, 0,
ax_anim 8, 0, 9, 0, 0, 0, 0,
ax_anim 10, 0, 11, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_1_5:
ax_anim 8, 0, 12, 0, 0, 0, 0,
ax_anim 10, 0, 13, 0, 0, 0, 0,
ax_anim 8, 0, 12, 0, 0, 0, 0,
ax_anim 10, 0, 14, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_1_6:
ax_anim 8, 0, 15, 0, 0, 0, 0,
ax_anim 10, 0, 16, 0, 0, 0, 0,
ax_anim 8, 0, 15, 0, 0, 0, 0,
ax_anim 10, 0, 17, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_1_7:
ax_anim 8, 0, 18, 0, 0, 0, 0,
ax_anim 10, 0, 19, 0, 0, 0, 0,
ax_anim 8, 0, 18, 0, 0, 0, 0,
ax_anim 10, 0, 20, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_1_8:
ax_anim 8, 0, 21, 0, 0, 0, 0,
ax_anim 10, 0, 22, 0, 0, 0, 0,
ax_anim 8, 0, 21, 0, 0, 0, 0,
ax_anim 10, 0, 23, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sPikachuAnims_2_1:
ax_anim 2, 0, 24, 0, -1, 0, -1,
ax_anim 4, 0, 24, 0, -2, 0, -2,
ax_anim 1, 0, 25, 0, 2, 0, 2,
ax_anim 1, 2, 27, 0, 4, 0, 4,
ax_anim 1, 0, 27, 0, 10, 0, 11,
ax_anim 2, 0, 27, 0, 24, 0, 20,
ax_anim 2, 1, 27, 1, 24, 1, 20,
ax_anim 2, 0, 27, 0, 24, 0, 20,
ax_anim 2, 0, 27, 1, 24, 1, 20,
ax_anim 4, 0, 24, 0, 6, 0, 6,
ax_anim_terminator
sPikachuAnims_2_2:
ax_anim 2, 0, 28, -1, -1, -1, -1,
ax_anim 4, 0, 28, -2, -2, -2, -2,
ax_anim 1, 0, 29, 0, -1, 0, 0,
ax_anim 1, 2, 31, 4, 1, 4, 4,
ax_anim 1, 0, 31, 12, 7, 10, 8,
ax_anim 2, 0, 31, 23, 20, 23, 20,
ax_anim 2, 1, 31, 24, 19, 24, 19,
ax_anim 2, 0, 31, 23, 20, 23, 20,
ax_anim 2, 0, 31, 24, 19, 24, 19,
ax_anim 4, 0, 28, 8, 8, 6, 6,
ax_anim_terminator
sPikachuAnims_2_3:
ax_anim 2, 0, 32, -1, 0, -1, 0,
ax_anim 4, 0, 32, -2, 0, -2, 0,
ax_anim 1, 0, 33, 0, -1, 0, 0,
ax_anim 1, 2, 35, 4, -3, 4, 0,
ax_anim 1, 0, 35, 10, -5, 10, 0,
ax_anim 2, 0, 35, 18, 0, 18, 0,
ax_anim 2, 1, 35, 18, 1, 18, 1,
ax_anim 2, 0, 35, 18, 0, 18, 0,
ax_anim 2, 0, 35, 18, 1, 18, 1,
ax_anim 4, 0, 32, 6, 0, 6, 0,
ax_anim_terminator
sPikachuAnims_2_4:
ax_anim 2, 0, 36, -1, 1, -1, 1,
ax_anim 4, 0, 36, -2, 2, -2, 2,
ax_anim 1, 0, 37, 0, -3, 0, -1,
ax_anim 1, 2, 39, 5, -10, 5, -6,
ax_anim 1, 0, 39, 13, -20, 13, -15,
ax_anim 2, 0, 39, 18, -20, 18, -20,
ax_anim 2, 1, 39, 19, -19, 19, -19,
ax_anim 2, 0, 39, 18, -20, 18, -20,
ax_anim 2, 0, 39, 19, -19, 19, -19,
ax_anim 4, 0, 36, 6, -6, 6, -6,
ax_anim_terminator
sPikachuAnims_2_5:
ax_anim 2, 0, 40, 0, 1, 0, 1,
ax_anim 4, 0, 40, 0, 2, 0, 2,
ax_anim 1, 0, 41, 0, 0, 0, 0,
ax_anim 1, 2, 43, 0, -6, 0, -4,
ax_anim 1, 0, 43, 0, -15, 0, -11,
ax_anim 2, 0, 43, 0, -18, 0, -18,
ax_anim 2, 1, 43, 1, -18, 1, -18,
ax_anim 2, 0, 43, 0, -18, 0, -18,
ax_anim 2, 0, 43, 1, -18, 1, -18,
ax_anim 4, 0, 40, 0, -6, 0, -6,
ax_anim_terminator
sPikachuAnims_2_6:
ax_anim 2, 0, 44, 1, 1, 1, 1,
ax_anim 4, 0, 44, 2, 2, 2, 2,
ax_anim 1, 0, 45, 0, -3, 0, -1,
ax_anim 1, 2, 47, -5, -10, -5, -6,
ax_anim 1, 0, 47, -13, -20, -13, -15,
ax_anim 2, 0, 47, -18, -20, -18, -20,
ax_anim 2, 1, 47, -19, -19, -19, -19,
ax_anim 2, 0, 47, -18, -20, -18, -20,
ax_anim 2, 0, 47, -19, -19, -19, -19,
ax_anim 4, 0, 44, -6, -6, -6, -6,
ax_anim_terminator
sPikachuAnims_2_7:
ax_anim 2, 0, 48, 1, 0, 1, 0,
ax_anim 4, 0, 48, 2, 0, 2, 0,
ax_anim 1, 0, 49, 0, -1, 0, 0,
ax_anim 1, 2, 51, -4, -3, -4, 0,
ax_anim 1, 0, 51, -10, -5, -10, 0,
ax_anim 2, 0, 51, -18, 0, -18, 0,
ax_anim 2, 1, 51, -18, 1, -18, 1,
ax_anim 2, 0, 51, -18, 0, -18, 0,
ax_anim 2, 0, 51, -18, 1, -18, 1,
ax_anim 4, 0, 48, -6, 0, -6, 0,
ax_anim_terminator
sPikachuAnims_2_8:
ax_anim 2, 0, 52, 1, -1, 1, -1,
ax_anim 4, 0, 52, 2, -2, 2, -2,
ax_anim 1, 0, 53, 0, -1, 0, 0,
ax_anim 1, 2, 55, -4, 1, -4, 4,
ax_anim 1, 0, 55, -12, 7, -10, 8,
ax_anim 2, 0, 55, -23, 20, -23, 20,
ax_anim 2, 1, 55, -24, 19, -24, 19,
ax_anim 2, 0, 55, -23, 20, -23, 20,
ax_anim 2, 0, 55, -24, 19, -24, 19,
ax_anim 4, 0, 52, -8, 8, -6, 6,
ax_anim_terminator
.align 2
sPikachuAnims_3_1:
ax_anim 2, 0, 56, 0, -1, 0, -1,
ax_anim 4, 0, 56, 0, -2, 0, -2,
ax_anim 1, 0, 57, 0, 2, 0, 2,
ax_anim 1, 2, 59, 0, 4, 0, 4,
ax_anim 1, 0, 59, 0, 10, 0, 11,
ax_anim 2, 0, 59, 0, 24, 0, 20,
ax_anim 2, 1, 59, 1, 24, 1, 20,
ax_anim 2, 0, 59, 0, 24, 0, 20,
ax_anim 2, 0, 59, 1, 24, 1, 20,
ax_anim 4, 0, 56, 0, 6, 0, 6,
ax_anim_terminator
sPikachuAnims_3_2:
ax_anim 2, 0, 60, -1, -1, -1, -1,
ax_anim 4, 0, 60, -2, -2, -2, -2,
ax_anim 1, 0, 61, 0, -1, 0, 0,
ax_anim 1, 2, 63, 4, 1, 4, 4,
ax_anim 1, 0, 63, 12, 7, 10, 8,
ax_anim 2, 0, 63, 23, 20, 23, 20,
ax_anim 2, 1, 63, 24, 19, 24, 19,
ax_anim 2, 0, 63, 23, 20, 23, 20,
ax_anim 2, 0, 63, 24, 19, 24, 19,
ax_anim 4, 0, 60, 8, 8, 6, 6,
ax_anim_terminator
sPikachuAnims_3_3:
ax_anim 2, 0, 64, -1, 0, -1, 0,
ax_anim 4, 0, 64, -2, 0, -2, 0,
ax_anim 1, 0, 65, 0, -1, 0, 0,
ax_anim 1, 2, 67, 4, -3, 4, 0,
ax_anim 1, 0, 67, 10, -5, 10, 0,
ax_anim 2, 0, 67, 18, 0, 18, 0,
ax_anim 2, 1, 67, 18, 1, 18, 1,
ax_anim 2, 0, 67, 18, 0, 18, 0,
ax_anim 2, 0, 67, 18, 1, 18, 1,
ax_anim 4, 0, 64, 6, 0, 6, 0,
ax_anim_terminator
sPikachuAnims_3_4:
ax_anim 2, 0, 68, -1, 1, -1, 1,
ax_anim 4, 0, 68, -2, 2, -2, 2,
ax_anim 1, 0, 69, 0, -3, 0, -1,
ax_anim 1, 2, 71, 5, -10, 5, -6,
ax_anim 1, 0, 71, 13, -20, 13, -15,
ax_anim 2, 0, 71, 18, -20, 18, -20,
ax_anim 2, 1, 71, 19, -19, 19, -19,
ax_anim 2, 0, 71, 18, -20, 18, -20,
ax_anim 2, 0, 71, 19, -19, 19, -19,
ax_anim 4, 0, 68, 6, -6, 6, -6,
ax_anim_terminator
sPikachuAnims_3_5:
ax_anim 2, 0, 72, 0, 1, 0, 1,
ax_anim 4, 0, 72, 0, 2, 0, 2,
ax_anim 1, 0, 73, 0, 0, 0, 0,
ax_anim 1, 2, 75, 0, -6, 0, -4,
ax_anim 1, 0, 75, 0, -15, 0, -11,
ax_anim 2, 0, 75, 0, -18, 0, -18,
ax_anim 2, 1, 75, 1, -18, 1, -18,
ax_anim 2, 0, 75, 0, -18, 0, -18,
ax_anim 2, 0, 75, 1, -18, 1, -18,
ax_anim 4, 0, 72, 0, -6, 0, -6,
ax_anim_terminator
sPikachuAnims_3_6:
ax_anim 2, 0, 76, 1, 1, 1, 1,
ax_anim 4, 0, 76, 2, 2, 2, 2,
ax_anim 1, 0, 77, 0, -3, 0, -1,
ax_anim 1, 2, 79, -5, -10, -5, -6,
ax_anim 1, 0, 79, -13, -20, -13, -15,
ax_anim 2, 0, 79, -18, -20, -18, -20,
ax_anim 2, 1, 79, -19, -19, -19, -19,
ax_anim 2, 0, 79, -18, -20, -18, -20,
ax_anim 2, 0, 79, -19, -19, -19, -19,
ax_anim 4, 0, 76, -6, -6, -6, -6,
ax_anim_terminator
sPikachuAnims_3_7:
ax_anim 2, 0, 80, 1, 0, 1, 0,
ax_anim 4, 0, 80, 2, 0, 2, 0,
ax_anim 1, 0, 81, 0, -1, 0, 0,
ax_anim 1, 2, 83, -4, -3, -4, 0,
ax_anim 1, 0, 83, -10, -5, -10, 0,
ax_anim 2, 0, 83, -18, 0, -18, 0,
ax_anim 2, 1, 83, -18, 1, -18, 1,
ax_anim 2, 0, 83, -18, 0, -18, 0,
ax_anim 2, 0, 83, -18, 1, -18, 1,
ax_anim 4, 0, 80, -6, 0, -6, 0,
ax_anim_terminator
sPikachuAnims_3_8:
ax_anim 2, 0, 84, 1, -1, 1, -1,
ax_anim 4, 0, 84, 2, -2, 2, -2,
ax_anim 1, 0, 85, 0, -1, 0, 0,
ax_anim 1, 2, 87, -4, 1, -4, 4,
ax_anim 1, 0, 87, -12, 7, -10, 8,
ax_anim 2, 0, 87, -23, 20, -23, 20,
ax_anim 2, 1, 87, -24, 19, -24, 19,
ax_anim 2, 0, 87, -23, 20, -23, 20,
ax_anim 2, 0, 87, -24, 19, -24, 19,
ax_anim 4, 0, 84, -8, 8, -6, 6,
ax_anim_terminator
.align 2
sPikachuAnims_4_1:
ax_anim 1, 0, 88, 0, -2, 0, -1,
ax_anim 2, 0, 88, 0, -3, 0, -2,
ax_anim 6, 2, 88, 0, -4, 0, -4,
ax_anim 2, 0, 88, 0, -1, 0, -1,
ax_anim 2, 1, 89, 0, 3, 0, 3,
ax_anim 2, 0, 89, 1, 3, 1, 3,
ax_anim 2, 0, 89, 0, 3, 0, 3,
ax_anim 2, 0, 89, 1, 3, 1, 3,
ax_anim 2, 0, 89, 0, 3, 0, 3,
ax_anim 2, 0, 89, 1, 3, 1, 3,
ax_anim 2, 0, 89, 0, 3, 0, 3,
ax_anim_terminator
sPikachuAnims_4_2:
ax_anim 1, 0, 90, -2, -4, -2, -2,
ax_anim 2, 0, 90, -3, -5, -3, -3,
ax_anim 6, 2, 90, -4, -4, -4, -4,
ax_anim 2, 0, 90, -1, -1, -1, -1,
ax_anim 2, 1, 91, 3, 3, 3, 3,
ax_anim 2, 0, 91, 2, 4, 2, 4,
ax_anim 2, 0, 91, 3, 3, 3, 3,
ax_anim 2, 0, 91, 2, 4, 2, 4,
ax_anim 2, 0, 91, 3, 3, 3, 3,
ax_anim 2, 0, 91, 2, 4, 2, 4,
ax_anim 2, 0, 91, 3, 3, 3, 3,
ax_anim_terminator
sPikachuAnims_4_3:
ax_anim 1, 0, 92, -2, -1, -2, 0,
ax_anim 2, 0, 92, -3, -2, -3, 0,
ax_anim 6, 2, 92, -4, 0, -4, 0,
ax_anim 2, 0, 92, -1, 0, -1, 0,
ax_anim 2, 1, 93, 3, 0, 3, 0,
ax_anim 2, 0, 93, 3, 1, 3, 1,
ax_anim 2, 0, 93, 3, 0, 3, 0,
ax_anim 2, 0, 93, 3, 1, 3, 1,
ax_anim 2, 0, 93, 3, 0, 3, 0,
ax_anim 2, 0, 93, 3, 1, 3, 1,
ax_anim 2, 0, 93, 3, 0, 3, 0,
ax_anim_terminator
sPikachuAnims_4_4:
ax_anim 1, 0, 94, -2, 1, -2, 2,
ax_anim 2, 0, 94, -3, 2, -3, 3,
ax_anim 6, 2, 94, -4, 4, -4, 4,
ax_anim 2, 0, 94, -1, 1, -1, 1,
ax_anim 2, 1, 95, 3, -3, 3, -3,
ax_anim 2, 0, 95, 2, -4, 2, -4,
ax_anim 2, 0, 95, 3, -3, 3, -3,
ax_anim 2, 0, 95, 2, -4, 2, -4,
ax_anim 2, 0, 95, 3, -3, 3, -3,
ax_anim 2, 0, 95, 2, -4, 2, -4,
ax_anim 2, 0, 95, 3, -3, 3, -3,
ax_anim_terminator
sPikachuAnims_4_5:
ax_anim 1, 0, 96, 0, 2, 0, 2,
ax_anim 2, 0, 96, 0, 3, 0, 3,
ax_anim 6, 2, 96, 0, 4, 0, 4,
ax_anim 2, 0, 96, 0, 1, 0, 1,
ax_anim 2, 1, 97, 0, -3, 0, -3,
ax_anim 2, 0, 97, 1, -3, 1, -3,
ax_anim 2, 0, 97, 0, -3, 0, -3,
ax_anim 2, 0, 97, 1, -3, 1, -3,
ax_anim 2, 0, 97, 0, -3, 0, -3,
ax_anim 2, 0, 97, 1, -3, 1, -3,
ax_anim 2, 0, 97, 0, -3, 0, -3,
ax_anim_terminator
sPikachuAnims_4_6:
ax_anim 1, 0, 98, 2, 1, 2, 2,
ax_anim 2, 0, 98, 3, 2, 3, 3,
ax_anim 6, 2, 98, 4, 4, 4, 4,
ax_anim 2, 0, 98, 1, 1, 1, 1,
ax_anim 2, 1, 99, -3, -3, -3, -3,
ax_anim 2, 0, 99, -2, -4, -2, -4,
ax_anim 2, 0, 99, -3, -3, -3, -3,
ax_anim 2, 0, 99, -2, -4, -2, -4,
ax_anim 2, 0, 99, -3, -3, -3, -3,
ax_anim 2, 0, 99, -2, -4, -2, -4,
ax_anim 2, 0, 99, -3, -3, -3, -3,
ax_anim_terminator
sPikachuAnims_4_7:
ax_anim 1, 0, 100, 2, -1, 2, 0,
ax_anim 2, 0, 100, 3, -2, 3, 0,
ax_anim 6, 2, 100, 4, 0, 4, 0,
ax_anim 2, 0, 100, 1, 0, 1, 0,
ax_anim 2, 1, 101, -3, 0, -3, 0,
ax_anim 2, 0, 101, -3, 1, -3, 1,
ax_anim 2, 0, 101, -3, 0, -3, 0,
ax_anim 2, 0, 101, -3, 1, -3, 1,
ax_anim 2, 0, 101, -3, 0, -3, 0,
ax_anim 2, 0, 101, -3, 1, -3, 1,
ax_anim 2, 0, 101, -3, 0, -3, 0,
ax_anim_terminator
sPikachuAnims_4_8:
ax_anim 1, 0, 102, 2, -4, 2, -2,
ax_anim 2, 0, 102, 3, -5, 3, -3,
ax_anim 6, 2, 102, 4, -4, 4, -4,
ax_anim 2, 0, 102, 1, -1, 1, -1,
ax_anim 2, 1, 103, -3, 3, -3, 3,
ax_anim 2, 0, 103, -2, 4, -2, 4,
ax_anim 2, 0, 103, -3, 3, -3, 3,
ax_anim 2, 0, 103, -2, 4, -2, 4,
ax_anim 2, 0, 103, -3, 3, -3, 3,
ax_anim 2, 0, 103, -2, 4, -2, 4,
ax_anim 2, 0, 103, -3, 3, -3, 3,
ax_anim_terminator
.align 2
sPikachuAnims_5_1:
ax_anim 8, 0, 105, 0, 0, 0, 0,
ax_anim 1, 0, 106, 0, 0, 0, 0,
ax_anim 1, 0, 108, 0, 0, 0, 0,
ax_anim 1, 0, 107, 0, 0, 0, 0,
ax_anim 1, 0, 106, 0, 0, 0, 0,
ax_anim 1, 0, 108, 0, 0, 0, 0,
ax_anim 1, 2, 107, 0, 0, 0, 0,
ax_anim 1, 0, 106, 0, 0, 0, 0,
ax_anim 1, 0, 108, 0, 0, 0, 0,
ax_anim 1, 0, 107, 0, 0, 0, 0,
ax_anim 1, 1, 108, 0, 0, 0, 0,
ax_anim 1, 0, 109, 0, 0, 0, 0,
ax_anim 1, 0, 108, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_5_2:
ax_anim 8, 0, 111, 0, 0, 0, 0,
ax_anim 1, 0, 112, 0, 0, 0, 0,
ax_anim 1, 0, 114, 0, 0, 0, 0,
ax_anim 1, 0, 113, 0, 0, 0, 0,
ax_anim 1, 0, 112, 0, 0, 0, 0,
ax_anim 1, 0, 114, 0, 0, 0, 0,
ax_anim 1, 2, 113, 0, 0, 0, 0,
ax_anim 1, 0, 112, 0, 0, 0, 0,
ax_anim 1, 0, 114, 0, 0, 0, 0,
ax_anim 1, 0, 113, 0, 0, 0, 0,
ax_anim 1, 1, 114, 0, 0, 0, 0,
ax_anim 1, 0, 115, 0, 0, 0, 0,
ax_anim 1, 0, 114, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_5_3:
ax_anim 8, 0, 117, 0, 0, 0, 0,
ax_anim 1, 0, 118, 0, 0, 0, 0,
ax_anim 1, 0, 120, 0, 0, 0, 0,
ax_anim 1, 0, 119, 0, 0, 0, 0,
ax_anim 1, 0, 118, 0, 0, 0, 0,
ax_anim 1, 0, 120, 0, 0, 0, 0,
ax_anim 1, 2, 119, 0, 0, 0, 0,
ax_anim 1, 0, 118, 0, 0, 0, 0,
ax_anim 1, 0, 120, 0, 0, 0, 0,
ax_anim 1, 0, 119, 0, 0, 0, 0,
ax_anim 1, 1, 120, 0, 0, 0, 0,
ax_anim 1, 0, 121, 0, 0, 0, 0,
ax_anim 1, 0, 120, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_5_4:
ax_anim 8, 0, 123, 0, 0, 0, 0,
ax_anim 1, 0, 124, 0, 0, 0, 0,
ax_anim 1, 0, 126, 0, 0, 0, 0,
ax_anim 1, 0, 125, 0, 0, 0, 0,
ax_anim 1, 0, 124, 0, 0, 0, 0,
ax_anim 1, 0, 126, 0, 0, 0, 0,
ax_anim 1, 2, 125, 0, 0, 0, 0,
ax_anim 1, 0, 124, 0, 0, 0, 0,
ax_anim 1, 0, 126, 0, 0, 0, 0,
ax_anim 1, 0, 125, 0, 0, 0, 0,
ax_anim 1, 1, 126, 0, 0, 0, 0,
ax_anim 1, 0, 127, 0, 0, 0, 0,
ax_anim 1, 0, 126, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_5_5:
ax_anim 8, 0, 129, 0, 0, 0, 0,
ax_anim 1, 0, 130, 0, 0, 0, 0,
ax_anim 1, 0, 132, 0, 0, 0, 0,
ax_anim 1, 0, 131, 0, 0, 0, 0,
ax_anim 1, 0, 130, 0, 0, 0, 0,
ax_anim 1, 0, 132, 0, 0, 0, 0,
ax_anim 1, 2, 131, 0, 0, 0, 0,
ax_anim 1, 0, 130, 0, 0, 0, 0,
ax_anim 1, 0, 132, 0, 0, 0, 0,
ax_anim 1, 0, 131, 0, 0, 0, 0,
ax_anim 1, 1, 132, 0, 0, 0, 0,
ax_anim 1, 0, 133, 0, 0, 0, 0,
ax_anim 1, 0, 132, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_5_6:
ax_anim 8, 0, 135, 0, 0, 0, 0,
ax_anim 1, 0, 136, 0, 0, 0, 0,
ax_anim 1, 0, 138, 0, 0, 0, 0,
ax_anim 1, 0, 137, 0, 0, 0, 0,
ax_anim 1, 0, 136, 0, 0, 0, 0,
ax_anim 1, 0, 138, 0, 0, 0, 0,
ax_anim 1, 2, 137, 0, 0, 0, 0,
ax_anim 1, 0, 136, 0, 0, 0, 0,
ax_anim 1, 0, 138, 0, 0, 0, 0,
ax_anim 1, 0, 137, 0, 0, 0, 0,
ax_anim 1, 1, 138, 0, 0, 0, 0,
ax_anim 1, 0, 139, 0, 0, 0, 0,
ax_anim 1, 0, 138, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_5_7:
ax_anim 8, 0, 141, 0, 0, 0, 0,
ax_anim 1, 0, 142, 0, 0, 0, 0,
ax_anim 1, 0, 144, 0, 0, 0, 0,
ax_anim 1, 0, 143, 0, 0, 0, 0,
ax_anim 1, 0, 142, 0, 0, 0, 0,
ax_anim 1, 0, 144, 0, 0, 0, 0,
ax_anim 1, 2, 143, 0, 0, 0, 0,
ax_anim 1, 0, 142, 0, 0, 0, 0,
ax_anim 1, 0, 144, 0, 0, 0, 0,
ax_anim 1, 0, 143, 0, 0, 0, 0,
ax_anim 1, 1, 144, 0, 0, 0, 0,
ax_anim 1, 0, 145, 0, 0, 0, 0,
ax_anim 1, 0, 144, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_5_8:
ax_anim 8, 0, 147, 0, 0, 0, 0,
ax_anim 1, 0, 148, 0, 0, 0, 0,
ax_anim 1, 0, 150, 0, 0, 0, 0,
ax_anim 1, 0, 149, 0, 0, 0, 0,
ax_anim 1, 0, 148, 0, 0, 0, 0,
ax_anim 1, 0, 150, 0, 0, 0, 0,
ax_anim 1, 2, 149, 0, 0, 0, 0,
ax_anim 1, 0, 148, 0, 0, 0, 0,
ax_anim 1, 0, 150, 0, 0, 0, 0,
ax_anim 1, 0, 149, 0, 0, 0, 0,
ax_anim 1, 1, 150, 0, 0, 0, 0,
ax_anim 1, 0, 151, 0, 0, 0, 0,
ax_anim 1, 0, 150, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sPikachuAnims_6_1:
ax_anim 30, 0, 152, 0, 0, 0, 0,
ax_anim 35, 0, 153, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sPikachuAnims_7_1:
ax_anim 2, 0, 154, 0, -3, 0, -3,
ax_anim 8, 0, 154, 0, -4, 0, -4,
ax_anim_terminator
sPikachuAnims_7_2:
ax_anim 2, 0, 155, -3, -3, -3, -3,
ax_anim 8, 0, 155, -4, -4, -4, -4,
ax_anim_terminator
sPikachuAnims_7_3:
ax_anim 2, 0, 156, -3, 0, -3, 0,
ax_anim 8, 0, 156, -4, 0, -4, 0,
ax_anim_terminator
sPikachuAnims_7_4:
ax_anim 2, 0, 157, -3, 3, -3, 3,
ax_anim 8, 0, 157, -4, 4, -4, 4,
ax_anim_terminator
sPikachuAnims_7_5:
ax_anim 2, 0, 158, 0, 3, 0, 3,
ax_anim 8, 0, 158, 0, 4, 0, 4,
ax_anim_terminator
sPikachuAnims_7_6:
ax_anim 2, 0, 159, 3, 3, 3, 3,
ax_anim 8, 0, 159, 4, 4, 4, 4,
ax_anim_terminator
sPikachuAnims_7_7:
ax_anim 2, 0, 160, 3, 0, 3, 0,
ax_anim 8, 0, 160, 4, 0, 4, 0,
ax_anim_terminator
sPikachuAnims_7_8:
ax_anim 2, 0, 161, 3, -3, 3, -3,
ax_anim 8, 0, 161, 4, -4, 4, -4,
ax_anim_terminator
.align 2
sPikachuAnims_8_1:
ax_anim 40, 0, 162, 0, 0, 0, 0,
ax_anim 2, 0, 170, 0, -2, 0, 0,
ax_anim 3, 0, 170, 0, -3, 0, 0,
ax_anim 3, 0, 170, 0, -4, 0, 0,
ax_anim 3, 0, 170, 0, -3, 0, 0,
ax_anim 2, 0, 170, 0, -2, 0, 0,
ax_anim_terminator
sPikachuAnims_8_2:
ax_anim 40, 0, 169, 0, 0, 0, 0,
ax_anim 2, 0, 177, 2, -3, 0, 0,
ax_anim 3, 0, 177, 2, -4, 0, 0,
ax_anim 3, 0, 177, 2, -5, 0, 0,
ax_anim 3, 0, 177, 2, -4, 0, 0,
ax_anim 2, 0, 177, 2, -3, 0, 0,
ax_anim_terminator
sPikachuAnims_8_3:
ax_anim 40, 0, 168, 0, 0, 0, 0,
ax_anim 2, 0, 176, 0, -4, 0, 0,
ax_anim 3, 0, 176, 0, -5, 0, 0,
ax_anim 3, 0, 176, 0, -6, 0, 0,
ax_anim 3, 0, 176, 0, -5, 0, 0,
ax_anim 2, 0, 176, 0, -4, 0, 0,
ax_anim_terminator
sPikachuAnims_8_4:
ax_anim 40, 0, 167, 0, 0, 0, 0,
ax_anim 2, 0, 175, 0, -4, 0, 0,
ax_anim 3, 0, 175, 0, -5, 0, 0,
ax_anim 3, 0, 175, 0, -6, 0, 0,
ax_anim 3, 0, 175, 0, -5, 0, 0,
ax_anim 2, 0, 175, 0, -4, 0, 0,
ax_anim_terminator
sPikachuAnims_8_5:
ax_anim 40, 0, 166, 0, 0, 0, 0,
ax_anim 2, 0, 174, 0, -4, 0, 0,
ax_anim 3, 0, 174, 0, -5, 0, 0,
ax_anim 3, 0, 174, 0, -6, 0, 0,
ax_anim 3, 0, 174, 0, -5, 0, 0,
ax_anim 2, 0, 174, 0, -4, 0, 0,
ax_anim_terminator
sPikachuAnims_8_6:
ax_anim 40, 0, 165, 0, 0, 0, 0,
ax_anim 2, 0, 173, 0, -4, 0, 0,
ax_anim 3, 0, 173, 0, -5, 0, 0,
ax_anim 3, 0, 173, 0, -6, 0, 0,
ax_anim 3, 0, 173, 0, -5, 0, 0,
ax_anim 2, 0, 173, 0, -4, 0, 0,
ax_anim_terminator
sPikachuAnims_8_7:
ax_anim 40, 0, 164, 0, 0, 0, 0,
ax_anim 2, 0, 172, 0, -4, 0, 0,
ax_anim 3, 0, 172, 0, -5, 0, 0,
ax_anim 3, 0, 172, 0, -6, 0, 0,
ax_anim 3, 0, 172, 0, -5, 0, 0,
ax_anim 2, 0, 172, 0, -4, 0, 0,
ax_anim_terminator
sPikachuAnims_8_8:
ax_anim 40, 0, 163, 0, 0, 0, 0,
ax_anim 2, 0, 171, -2, -3, 0, 0,
ax_anim 3, 0, 171, -2, -4, 0, 0,
ax_anim 3, 0, 171, -2, -5, 0, 0,
ax_anim 3, 0, 171, -2, -4, 0, 0,
ax_anim 2, 0, 171, -2, -3, 0, 0,
ax_anim_terminator
.align 2
sPikachuAnims_9_1:
ax_anim 2, 0, 178, 0, 0, 0, 0,
ax_anim 1, 0, 179, 6, 4, 6, 4,
ax_anim 2, 0, 180, 8, 9, 8, 9,
ax_anim 2, 0, 181, 7, 18, 7, 18,
ax_anim 3, 0, 182, 0, 21, 0, 21,
ax_anim 2, 3, 183, -7, 18, -7, 18,
ax_anim 2, 0, 184, -8, 9, -8, 9,
ax_anim 1, 0, 185, -6, 4, -6, 4,
ax_anim 1, 0, 178, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_9_2:
ax_anim 2, 0, 185, 0, 0, 0, 0,
ax_anim 1, 0, 178, 6, 0, 6, 0,
ax_anim 2, 0, 179, 17, 3, 17, 3,
ax_anim 2, 0, 180, 24, 9, 24, 9,
ax_anim 3, 0, 181, 23, 21, 23, 21,
ax_anim 2, 3, 182, 11, 21, 11, 21,
ax_anim 2, 0, 183, 2, 12, 2, 12,
ax_anim 1, 0, 184, 0, 7, 0, 7,
ax_anim 1, 0, 185, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_9_3:
ax_anim 2, 0, 184, 0, 0, 0, 0,
ax_anim 1, 0, 185, 3, -4, 3, -4,
ax_anim 2, 0, 178, 11, -6, 11, -6,
ax_anim 2, 0, 179, 18, -4, 17, -4,
ax_anim 3, 0, 180, 22, 1, 22, 1,
ax_anim 2, 3, 181, 18, 5, 18, 5,
ax_anim 2, 0, 182, 12, 7, 12, 7,
ax_anim 1, 0, 183, 4, 5, 4, 5,
ax_anim 1, 0, 184, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_9_4:
ax_anim 2, 0, 183, 0, 0, 0, 0,
ax_anim 1, 0, 184, -1, -6, -1, -6,
ax_anim 2, 0, 185, 2, -16, 2, -16,
ax_anim 2, 0, 178, 11, -22, 11, -22,
ax_anim 3, 0, 179, 20, -22, 20, -22,
ax_anim 2, 3, 180, 21, -12, 21, -12,
ax_anim 2, 0, 181, 16, -6, 16, -6,
ax_anim 1, 0, 182, 7, -1, 7, -1,
ax_anim 1, 0, 183, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_9_5:
ax_anim 2, 0, 182, 0, 0, 0, 0,
ax_anim 1, 0, 183, -6, -4, -6, -4,
ax_anim 2, 0, 184, -8, -10, -8, -10,
ax_anim 2, 0, 185, -7, -19, -7, -19,
ax_anim 3, 0, 178, 0, -24, 0, -24,
ax_anim 2, 3, 179, 7, -19, 7, -19,
ax_anim 2, 0, 180, 8, -8, 8, -8,
ax_anim 1, 0, 181, 6, -4, 6, -4,
ax_anim 1, 0, 182, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_9_6:
ax_anim 2, 0, 181, 0, 0, 0, 0,
ax_anim 1, 0, 180, 1, -6, 1, -6,
ax_anim 2, 0, 179, -2, -16, -2, -16,
ax_anim 2, 0, 178, -11, -22, -11, -22,
ax_anim 3, 0, 185, -20, -22, -20, -22,
ax_anim 2, 3, 184, -21, -12, -21, -12,
ax_anim 2, 0, 183, -16, -6, -16, -6,
ax_anim 1, 0, 182, -7, -1, -7, -1,
ax_anim 1, 0, 181, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_9_7:
ax_anim 2, 0, 180, 0, 0, 0, 0,
ax_anim 1, 0, 179, -3, -4, -3, -4,
ax_anim 2, 0, 178, -11, -6, -11, -6,
ax_anim 2, 0, 185, -18, -4, -18, -4,
ax_anim 3, 0, 184, -22, 1, -22, 1,
ax_anim 2, 3, 183, -18, 5, -18, 5,
ax_anim 2, 0, 182, -12, 7, -12, 7,
ax_anim 1, 0, 181, -4, 5, -4, 5,
ax_anim 1, 0, 180, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_9_8:
ax_anim 2, 0, 179, 0, 0, 0, 0,
ax_anim 1, 0, 178, -6, 0, -6, 0,
ax_anim 2, 0, 185, -17, 3, -17, 3,
ax_anim 2, 0, 184, -24, 9, -24, 9,
ax_anim 3, 0, 183, -23, 21, -23, 16,
ax_anim 2, 3, 182, -11, 21, -11, 16,
ax_anim 2, 0, 181, -2, 12, -4, 12,
ax_anim 1, 0, 180, 0, 7, -3, 7,
ax_anim 1, 0, 179, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sPikachuAnims_10_1:
ax_anim 2, 0, 186, 0, 0, 0, 0,
ax_anim 2, 0, 186, 6, 0, 6, 0,
ax_anim 2, 0, 186, -6, 0, -6, 0,
ax_anim 2, 0, 186, 10, 0, 10, 0,
ax_anim 2, 0, 186, -10, 0, -10, 0,
ax_anim 2, 0, 186, 12, 0, 12, 0,
ax_anim 3, 0, 186, -12, 0, -12, 0,
ax_anim 3, 0, 186, 13, 0, 13, 0,
ax_anim 3, 0, 186, -13, 0, -13, 0,
ax_anim 2, 0, 186, 12, 0, 12, 0,
ax_anim 3, 0, 186, -12, 0, -12, 0,
ax_anim 2, 0, 186, 10, 0, 10, 0,
ax_anim 2, 0, 186, -10, 0, -10, 0,
ax_anim 2, 0, 186, 6, 0, 6, 0,
ax_anim 2, 0, 186, -6, 0, -6, 0,
ax_anim 2, 0, 186, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_10_2:
ax_anim 2, 0, 187, 0, 0, 0, 0,
ax_anim 2, 0, 187, 6, -6, 6, -6,
ax_anim 2, 0, 187, -6, 6, -6, 6,
ax_anim 2, 0, 187, 10, -10, 10, -10,
ax_anim 2, 0, 187, -10, 10, -10, 10,
ax_anim 2, 0, 187, 12, -12, 12, -12,
ax_anim 3, 0, 187, -12, 12, -12, 12,
ax_anim 3, 0, 187, 13, -13, 13, -13,
ax_anim 3, 0, 187, -13, 13, -13, 13,
ax_anim 2, 0, 187, 12, -12, 12, -12,
ax_anim 3, 0, 187, -12, 12, -12, 12,
ax_anim 2, 0, 187, 10, -10, 10, -10,
ax_anim 2, 0, 187, -10, 10, -10, 10,
ax_anim 2, 0, 187, 6, -6, 6, -6,
ax_anim 2, 0, 187, -6, 6, -6, 6,
ax_anim 2, 0, 187, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_10_3:
ax_anim 2, 0, 188, 0, 0, 0, 0,
ax_anim 2, 0, 188, 0, -6, 0, -6,
ax_anim 2, 0, 188, 0, 6, 0, 6,
ax_anim 2, 0, 188, 0, -10, 0, -10,
ax_anim 2, 0, 188, 0, 10, 0, 10,
ax_anim 2, 0, 188, 0, -12, 0, -12,
ax_anim 3, 0, 188, 0, 12, 0, 12,
ax_anim 3, 0, 188, 0, -13, 0, -13,
ax_anim 3, 0, 188, 0, 13, 0, 13,
ax_anim 2, 0, 188, 0, -12, 0, -12,
ax_anim 3, 0, 188, 0, 12, 0, 12,
ax_anim 2, 0, 188, 0, -10, 0, -10,
ax_anim 2, 0, 188, 0, 10, 0, 10,
ax_anim 2, 0, 188, 0, -6, 0, -6,
ax_anim 2, 0, 188, 0, 6, 0, 6,
ax_anim 2, 0, 188, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_10_4:
ax_anim 2, 0, 189, 0, 0, 0, 0,
ax_anim 2, 0, 189, -6, -6, -6, -6,
ax_anim 2, 0, 189, 6, 6, 6, 6,
ax_anim 2, 0, 189, -10, -10, -10, -10,
ax_anim 2, 0, 189, 10, 10, 10, 10,
ax_anim 2, 0, 189, -12, -12, -12, -12,
ax_anim 3, 0, 189, 12, 12, 12, 12,
ax_anim 3, 0, 189, -13, -13, -13, -13,
ax_anim 3, 0, 189, 13, 13, 13, 13,
ax_anim 2, 0, 189, -12, -12, -12, -12,
ax_anim 3, 0, 189, 12, 12, 12, 12,
ax_anim 2, 0, 189, -10, -10, -10, -10,
ax_anim 2, 0, 189, 10, 10, 10, 10,
ax_anim 2, 0, 189, -6, -6, -6, -6,
ax_anim 2, 0, 189, 6, 6, 6, 6,
ax_anim 2, 0, 189, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_10_5:
ax_anim 2, 0, 190, 0, 0, 0, 0,
ax_anim 2, 0, 190, 6, 0, 6, 0,
ax_anim 2, 0, 190, -6, 0, -6, 0,
ax_anim 2, 0, 190, 10, 0, 10, 0,
ax_anim 2, 0, 190, -10, 0, -10, 0,
ax_anim 2, 0, 190, 12, 0, 12, 0,
ax_anim 3, 0, 190, -12, 0, -12, 0,
ax_anim 3, 0, 190, 13, 0, 13, 0,
ax_anim 3, 0, 190, -13, 0, -13, 0,
ax_anim 2, 0, 190, 12, 0, 12, 0,
ax_anim 3, 0, 190, -12, 0, -12, 0,
ax_anim 2, 0, 190, 10, 0, 10, 0,
ax_anim 2, 0, 190, -10, 0, -10, 0,
ax_anim 2, 0, 190, 6, 0, 6, 0,
ax_anim 2, 0, 190, -6, 0, -6, 0,
ax_anim 2, 0, 190, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_10_6:
ax_anim 2, 0, 191, 0, 0, 0, 0,
ax_anim 2, 0, 191, 6, -6, 6, -6,
ax_anim 2, 0, 191, -6, 6, -6, 6,
ax_anim 2, 0, 191, 10, -10, 10, -10,
ax_anim 2, 0, 191, -10, 10, -10, 10,
ax_anim 2, 0, 191, 12, -12, 12, -12,
ax_anim 3, 0, 191, -12, 12, -12, 12,
ax_anim 3, 0, 191, 13, -13, 13, -13,
ax_anim 3, 0, 191, -13, 13, -13, 13,
ax_anim 2, 0, 191, 12, -12, 12, -12,
ax_anim 3, 0, 191, -12, 12, -12, 12,
ax_anim 2, 0, 191, 10, -10, 10, -10,
ax_anim 2, 0, 191, -10, 10, -10, 10,
ax_anim 2, 0, 191, 6, -6, 6, -6,
ax_anim 2, 0, 191, -6, 6, -6, 6,
ax_anim 2, 0, 191, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_10_7:
ax_anim 2, 0, 192, 0, 0, 0, 0,
ax_anim 2, 0, 192, 0, -6, 0, -6,
ax_anim 2, 0, 192, 0, 6, 0, 6,
ax_anim 2, 0, 192, 0, -10, 0, -10,
ax_anim 2, 0, 192, 0, 10, 0, 10,
ax_anim 2, 0, 192, 0, -12, 0, -12,
ax_anim 3, 0, 192, 0, 12, 0, 12,
ax_anim 3, 0, 192, 0, -13, 0, -13,
ax_anim 3, 0, 192, 0, 13, 0, 13,
ax_anim 2, 0, 192, 0, -12, 0, -12,
ax_anim 3, 0, 192, 0, 12, 0, 12,
ax_anim 2, 0, 192, 0, -10, 0, -10,
ax_anim 2, 0, 192, 0, 10, 0, 10,
ax_anim 2, 0, 192, 0, -6, 0, -6,
ax_anim 2, 0, 192, 0, 6, 0, 6,
ax_anim 2, 0, 192, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_10_8:
ax_anim 2, 0, 193, 0, 0, 0, 0,
ax_anim 2, 0, 193, -6, -6, -6, -6,
ax_anim 2, 0, 193, 6, 6, 6, 6,
ax_anim 2, 0, 193, -10, -10, -10, -10,
ax_anim 2, 0, 193, 10, 10, 10, 10,
ax_anim 2, 0, 193, -12, -12, -12, -12,
ax_anim 3, 0, 193, 12, 12, 12, 12,
ax_anim 3, 0, 193, -13, -13, -13, -13,
ax_anim 3, 0, 193, 13, 13, 13, 13,
ax_anim 2, 0, 193, -12, -12, -12, -12,
ax_anim 3, 0, 193, 12, 12, 12, 12,
ax_anim 2, 0, 193, -10, -10, -10, -10,
ax_anim 2, 0, 193, 10, 10, 10, 10,
ax_anim 2, 0, 193, -6, -6, -6, -6,
ax_anim 2, 0, 193, 6, 6, 6, 6,
ax_anim 2, 0, 193, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sPikachuAnims_11_1:
ax_anim 2, 0, 194, 0, 0, 0, 0,
ax_anim 1, 0, 195, 0, -10, 0, 0,
ax_anim 2, 0, 195, 0, -16, 0, 0,
ax_anim 3, 0, 197, 0, -20, 0, 0,
ax_anim 4, 0, 197, 0, -21, 0, 0,
ax_anim 4, 0, 197, 0, -23, 0, 0,
ax_anim 3, 0, 197, 0, -22, 0, 0,
ax_anim 2, 0, 197, 0, -18, 0, 0,
ax_anim 1, 0, 197, 0, -12, 0, 0,
ax_anim 2, 2, 194, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_11_2:
ax_anim 2, 0, 198, 0, 0, 0, 0,
ax_anim 1, 0, 199, 0, -10, 0, 0,
ax_anim 2, 0, 199, 0, -16, 0, 0,
ax_anim 3, 0, 201, 0, -20, 0, 0,
ax_anim 4, 0, 201, 0, -21, 0, 0,
ax_anim 4, 0, 201, 0, -23, 0, 0,
ax_anim 3, 0, 201, 0, -22, 0, 0,
ax_anim 2, 0, 201, 0, -18, 0, 0,
ax_anim 1, 0, 201, 0, -12, 0, 0,
ax_anim 2, 2, 198, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_11_3:
ax_anim 2, 0, 202, 0, 0, 0, 0,
ax_anim 1, 0, 203, 0, -10, 0, 0,
ax_anim 2, 0, 203, 0, -16, 0, 0,
ax_anim 3, 0, 205, 0, -20, 0, 0,
ax_anim 4, 0, 205, 0, -21, 0, 0,
ax_anim 4, 0, 205, 0, -23, 0, 0,
ax_anim 3, 0, 205, 0, -22, 0, 0,
ax_anim 2, 0, 205, 0, -18, 0, 0,
ax_anim 1, 0, 205, 0, -12, 0, 0,
ax_anim 2, 2, 202, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_11_4:
ax_anim 2, 0, 206, 0, 0, 0, 0,
ax_anim 1, 0, 207, 0, -10, 0, 0,
ax_anim 2, 0, 207, 0, -16, 0, 0,
ax_anim 3, 0, 209, 0, -20, 0, 0,
ax_anim 4, 0, 209, 0, -21, 0, 0,
ax_anim 4, 0, 209, 0, -22, 0, 0,
ax_anim 3, 0, 209, 0, -21, 0, 0,
ax_anim 2, 0, 209, 0, -17, 0, 0,
ax_anim 1, 0, 209, 0, -11, 0, 0,
ax_anim 2, 2, 206, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_11_5:
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 1, 0, 211, 0, -10, 0, 0,
ax_anim 2, 0, 211, 0, -16, 0, 0,
ax_anim 3, 0, 213, 0, -20, 0, 0,
ax_anim 4, 0, 213, 0, -21, 0, 0,
ax_anim 4, 0, 213, 0, -23, 0, 0,
ax_anim 3, 0, 213, 0, -22, 0, 0,
ax_anim 2, 0, 213, 0, -18, 0, 0,
ax_anim 1, 0, 213, 0, -12, 0, 0,
ax_anim 2, 2, 210, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_11_6:
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 1, 0, 215, 0, -10, 0, 0,
ax_anim 2, 0, 215, 0, -16, 0, 0,
ax_anim 3, 0, 217, 0, -20, 0, 0,
ax_anim 4, 0, 217, 0, -21, 0, 0,
ax_anim 4, 0, 217, 0, -22, 0, 0,
ax_anim 3, 0, 217, 0, -21, 0, 0,
ax_anim 2, 0, 217, 0, -17, 0, 0,
ax_anim 1, 0, 217, 0, -11, 0, 0,
ax_anim 2, 2, 214, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_11_7:
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 1, 0, 219, 0, -10, 0, 0,
ax_anim 2, 0, 219, 0, -16, 0, 0,
ax_anim 3, 0, 221, 0, -20, 0, 0,
ax_anim 4, 0, 221, 0, -21, 0, 0,
ax_anim 4, 0, 221, 0, -23, 0, 0,
ax_anim 3, 0, 221, 0, -22, 0, 0,
ax_anim 2, 0, 221, 0, -18, 0, 0,
ax_anim 1, 0, 221, 0, -12, 0, 0,
ax_anim 2, 2, 218, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_11_8:
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 1, 0, 223, 0, -10, 0, 0,
ax_anim 2, 0, 223, 0, -16, 0, 0,
ax_anim 3, 0, 225, 0, -20, 0, 0,
ax_anim 4, 0, 225, 0, -21, 0, 0,
ax_anim 4, 0, 225, 0, -23, 0, 0,
ax_anim 3, 0, 225, 0, -22, 0, 0,
ax_anim 2, 0, 225, 0, -18, 0, 0,
ax_anim 1, 0, 225, 0, -12, 0, 0,
ax_anim 2, 2, 222, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sPikachuAnims_12_1:
ax_anim 2, 0, 226, 1, 0, 1, 0,
ax_anim 2, 0, 226, 0, 0, 0, 0,
ax_anim 2, 0, 226, 1, 0, 1, 0,
ax_anim 2, 0, 226, 0, 0, 0, 0,
ax_anim 2, 0, 226, 1, 0, 1, 0,
ax_anim 2, 2, 226, 0, 0, 0, 0,
ax_anim 2, 0, 226, 1, 0, 1, 0,
ax_anim 2, 0, 226, 0, 0, 0, 0,
ax_anim 2, 0, 226, 1, 0, 1, 0,
ax_anim 2, 1, 226, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_12_2:
ax_anim 2, 0, 233, 1, -1, 1, 0,
ax_anim 2, 0, 233, 0, 0, 0, 0,
ax_anim 2, 0, 233, 1, -1, 1, 0,
ax_anim 2, 0, 233, 0, 0, 0, 0,
ax_anim 2, 0, 233, 1, -1, 1, 0,
ax_anim 2, 2, 233, 0, 0, 0, 0,
ax_anim 2, 0, 233, 1, -1, 1, 0,
ax_anim 2, 0, 233, 0, 0, 0, 0,
ax_anim 2, 0, 233, 1, -1, 1, 0,
ax_anim 2, 1, 233, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_12_3:
ax_anim 2, 0, 232, 0, -1, 0, -1,
ax_anim 2, 0, 232, 0, 0, 0, 0,
ax_anim 2, 0, 232, 0, -1, 0, -1,
ax_anim 2, 0, 232, 0, 0, 0, 0,
ax_anim 2, 0, 232, 0, -1, 0, -1,
ax_anim 2, 2, 232, 0, 0, 0, 0,
ax_anim 2, 0, 232, 0, -1, 0, -1,
ax_anim 2, 0, 232, 0, 0, 0, 0,
ax_anim 2, 0, 232, 0, -1, 0, -1,
ax_anim 2, 1, 232, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_12_4:
ax_anim 2, 0, 231, -1, -1, -1, -1,
ax_anim 2, 0, 231, 0, 0, 0, 0,
ax_anim 2, 0, 231, -1, -1, -1, -1,
ax_anim 2, 0, 231, 0, 0, 0, 0,
ax_anim 2, 0, 231, -1, -1, -1, -1,
ax_anim 2, 2, 231, 0, 0, 0, 0,
ax_anim 2, 0, 231, -1, -1, -1, -1,
ax_anim 2, 0, 231, 0, 0, 0, 0,
ax_anim 2, 0, 231, -1, -1, -1, -1,
ax_anim 2, 1, 231, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_12_5:
ax_anim 2, 0, 230, 1, 0, 1, 0,
ax_anim 2, 0, 230, 0, 0, 0, 0,
ax_anim 2, 0, 230, 1, 0, 1, 0,
ax_anim 2, 0, 230, 0, 0, 0, 0,
ax_anim 2, 0, 230, 1, 0, 1, 0,
ax_anim 2, 2, 230, 0, 0, 0, 0,
ax_anim 2, 0, 230, 1, 0, 1, 0,
ax_anim 2, 0, 230, 0, 0, 0, 0,
ax_anim 2, 0, 230, 1, 0, 1, 0,
ax_anim 2, 1, 230, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_12_6:
ax_anim 2, 0, 229, 1, -1, 1, -1,
ax_anim 2, 0, 229, 0, 0, 0, 0,
ax_anim 2, 0, 229, 1, -1, 1, -1,
ax_anim 2, 0, 229, 0, 0, 0, 0,
ax_anim 2, 0, 229, 1, -1, 1, -1,
ax_anim 2, 2, 229, 0, 0, 0, 0,
ax_anim 2, 0, 229, 1, -1, 1, -1,
ax_anim 2, 0, 229, 0, 0, 0, 0,
ax_anim 2, 0, 229, 1, -1, 1, -1,
ax_anim 2, 1, 229, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_12_7:
ax_anim 2, 0, 228, 0, -1, 0, -1,
ax_anim 2, 0, 228, 0, 0, 0, 0,
ax_anim 2, 0, 228, 0, -1, 0, -1,
ax_anim 2, 0, 228, 0, 0, 0, 0,
ax_anim 2, 0, 228, 0, -1, 0, -1,
ax_anim 2, 2, 228, 0, 0, 0, 0,
ax_anim 2, 0, 228, 0, -1, 0, -1,
ax_anim 2, 0, 228, 0, 0, 0, 0,
ax_anim 2, 0, 228, 0, -1, 0, -1,
ax_anim 2, 1, 228, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_12_8:
ax_anim 2, 0, 227, -1, -1, -1, -1,
ax_anim 2, 0, 227, 0, 0, 0, 0,
ax_anim 2, 0, 227, -1, -1, -1, -1,
ax_anim 2, 0, 227, 0, 0, 0, 0,
ax_anim 2, 0, 227, -1, -1, -1, -1,
ax_anim 2, 2, 227, 0, 0, 0, 0,
ax_anim 2, 0, 227, -1, -1, -1, -1,
ax_anim 2, 0, 227, 0, 0, 0, 0,
ax_anim 2, 0, 227, -1, -1, -1, -1,
ax_anim 2, 1, 227, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sPikachuAnims_13_1:
ax_anim 2, 0, 234, 0, 0, 0, 0,
ax_anim 2, 0, 235, 0, 0, 0, 0,
ax_anim 2, 0, 236, 0, 0, 0, 0,
ax_anim 2, 0, 237, 0, 0, 0, 0,
ax_anim 2, 0, 238, 0, 0, 0, 0,
ax_anim 2, 0, 239, 0, 0, 0, 0,
ax_anim 2, 0, 240, 0, 0, 0, 0,
ax_anim 2, 0, 241, 0, 0, 0, 0,
ax_anim 2, 2, 234, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_13_2:
ax_anim 2, 0, 241, 0, 0, 0, 0,
ax_anim 2, 0, 234, 0, 0, 0, 0,
ax_anim 2, 0, 235, 0, 0, 0, 0,
ax_anim 2, 0, 236, 0, 0, 0, 0,
ax_anim 2, 0, 237, 0, 0, 0, 0,
ax_anim 2, 0, 238, 0, 0, 0, 0,
ax_anim 2, 0, 239, 0, 0, 0, 0,
ax_anim 2, 0, 240, 0, 0, 0, 0,
ax_anim 2, 2, 241, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_13_3:
ax_anim 2, 0, 240, 0, 0, 0, 0,
ax_anim 2, 0, 241, 0, 0, 0, 0,
ax_anim 2, 0, 234, 0, 0, 0, 0,
ax_anim 2, 0, 235, 0, 0, 0, 0,
ax_anim 2, 0, 236, 0, 0, 0, 0,
ax_anim 2, 0, 237, 0, 0, 0, 0,
ax_anim 2, 0, 238, 0, 0, 0, 0,
ax_anim 2, 0, 239, 0, 0, 0, 0,
ax_anim 2, 2, 240, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_13_4:
ax_anim 2, 0, 239, 0, 0, 0, 0,
ax_anim 2, 0, 240, 0, 0, 0, 0,
ax_anim 2, 0, 241, 0, 0, 0, 0,
ax_anim 2, 0, 234, 0, 0, 0, 0,
ax_anim 2, 0, 235, 0, 0, 0, 0,
ax_anim 2, 0, 236, 0, 0, 0, 0,
ax_anim 2, 0, 237, 0, 0, 0, 0,
ax_anim 2, 0, 238, 0, 0, 0, 0,
ax_anim 2, 2, 239, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_13_5:
ax_anim 2, 0, 238, 0, 0, 0, 0,
ax_anim 2, 0, 239, 0, 0, 0, 0,
ax_anim 2, 0, 240, 0, 0, 0, 0,
ax_anim 2, 0, 241, 0, 0, 0, 0,
ax_anim 2, 0, 234, 0, 0, 0, 0,
ax_anim 2, 0, 235, 0, 0, 0, 0,
ax_anim 2, 0, 236, 0, 0, 0, 0,
ax_anim 2, 0, 237, 0, 0, 0, 0,
ax_anim 2, 2, 238, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_13_6:
ax_anim 2, 0, 237, 0, 0, 0, 0,
ax_anim 2, 0, 238, 0, 0, 0, 0,
ax_anim 2, 0, 239, 0, 0, 0, 0,
ax_anim 2, 0, 240, 0, 0, 0, 0,
ax_anim 2, 0, 241, 0, 0, 0, 0,
ax_anim 2, 0, 234, 0, 0, 0, 0,
ax_anim 2, 0, 235, 0, 0, 0, 0,
ax_anim 2, 0, 236, 0, 0, 0, 0,
ax_anim 2, 2, 237, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_13_7:
ax_anim 2, 0, 236, 0, 0, 0, 0,
ax_anim 2, 0, 237, 0, 0, 0, 0,
ax_anim 2, 0, 238, 0, 0, 0, 0,
ax_anim 2, 0, 239, 0, 0, 0, 0,
ax_anim 2, 0, 240, 0, 0, 0, 0,
ax_anim 2, 0, 241, 0, 0, 0, 0,
ax_anim 2, 0, 234, 0, 0, 0, 0,
ax_anim 2, 0, 235, 0, 0, 0, 0,
ax_anim 2, 2, 236, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_13_8:
ax_anim 2, 0, 235, 0, 0, 0, 0,
ax_anim 2, 0, 236, 0, 0, 0, 0,
ax_anim 2, 0, 237, 0, 0, 0, 0,
ax_anim 2, 0, 238, 0, 0, 0, 0,
ax_anim 2, 0, 239, 0, 0, 0, 0,
ax_anim 2, 0, 240, 0, 0, 0, 0,
ax_anim 2, 0, 241, 0, 0, 0, 0,
ax_anim 2, 0, 234, 0, 0, 0, 0,
ax_anim 2, 2, 235, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sPikachuAnims_14_1:
ax_anim 30, 0, 242, 0, 0, 0, 0,
ax_anim 35, 0, 243, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_14_2:
ax_anim 30, 0, 242, 0, 0, 0, 0,
ax_anim 35, 0, 243, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_14_3:
ax_anim 30, 0, 242, 0, 0, 0, 0,
ax_anim 35, 0, 243, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_14_4:
ax_anim 30, 0, 242, 0, 0, 0, 0,
ax_anim 35, 0, 243, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_14_5:
ax_anim 30, 0, 242, 0, 0, 0, 0,
ax_anim 35, 0, 243, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_14_6:
ax_anim 30, 0, 242, 0, 0, 0, 0,
ax_anim 35, 0, 243, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_14_7:
ax_anim 30, 0, 242, 0, 0, 0, 0,
ax_anim 35, 0, 243, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_14_8:
ax_anim 30, 0, 242, 0, 0, 0, 0,
ax_anim 35, 0, 243, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sPikachuAnims_15_1:
ax_anim 8, 0, 246, 0, 0, 0, 0,
ax_anim 6, 0, 247, 0, 0, 0, 0,
ax_anim 4, 0, 248, 0, 0, 0, 0,
ax_anim 14, 0, 249, 0, 0, 0, 0,
ax_anim 10, 0, 250, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_15_2:
ax_anim 8, 0, 246, 0, 0, 0, 0,
ax_anim 6, 0, 247, 0, 0, 0, 0,
ax_anim 4, 0, 248, 0, 0, 0, 0,
ax_anim 14, 0, 249, 0, 0, 0, 0,
ax_anim 10, 0, 250, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_15_3:
ax_anim 8, 0, 246, 0, 0, 0, 0,
ax_anim 6, 0, 247, 0, 0, 0, 0,
ax_anim 4, 0, 248, 0, 0, 0, 0,
ax_anim 14, 0, 249, 0, 0, 0, 0,
ax_anim 10, 0, 250, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_15_4:
ax_anim 8, 0, 246, 0, 0, 0, 0,
ax_anim 6, 0, 247, 0, 0, 0, 0,
ax_anim 4, 0, 248, 0, 0, 0, 0,
ax_anim 14, 0, 249, 0, 0, 0, 0,
ax_anim 10, 0, 250, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_15_5:
ax_anim 8, 0, 246, 0, 0, 0, 0,
ax_anim 6, 0, 247, 0, 0, 0, 0,
ax_anim 4, 0, 248, 0, 0, 0, 0,
ax_anim 14, 0, 249, 0, 0, 0, 0,
ax_anim 10, 0, 250, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_15_6:
ax_anim 8, 0, 246, 0, 0, 0, 0,
ax_anim 6, 0, 247, 0, 0, 0, 0,
ax_anim 4, 0, 248, 0, 0, 0, 0,
ax_anim 14, 0, 249, 0, 0, 0, 0,
ax_anim 10, 0, 250, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_15_7:
ax_anim 8, 0, 246, 0, 0, 0, 0,
ax_anim 6, 0, 247, 0, 0, 0, 0,
ax_anim 4, 0, 248, 0, 0, 0, 0,
ax_anim 14, 0, 249, 0, 0, 0, 0,
ax_anim 10, 0, 250, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_15_8:
ax_anim 8, 0, 246, 0, 0, 0, 0,
ax_anim 6, 0, 247, 0, 0, 0, 0,
ax_anim 4, 0, 248, 0, 0, 0, 0,
ax_anim 14, 0, 249, 0, 0, 0, 0,
ax_anim 10, 0, 250, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sPikachuAnims_16_1:
ax_anim 8, 0, 251, 0, 0, 0, 0,
ax_anim 3, 0, 252, 0, 0, 0, 0,
ax_anim 8, 0, 253, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_16_2:
ax_anim 8, 0, 251, 0, 0, 0, 0,
ax_anim 3, 0, 252, 0, 0, 0, 0,
ax_anim 8, 0, 253, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_16_3:
ax_anim 8, 0, 251, 0, 0, 0, 0,
ax_anim 3, 0, 252, 0, 0, 0, 0,
ax_anim 8, 0, 253, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_16_4:
ax_anim 8, 0, 251, 0, 0, 0, 0,
ax_anim 3, 0, 252, 0, 0, 0, 0,
ax_anim 8, 0, 253, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_16_5:
ax_anim 8, 0, 251, 0, 0, 0, 0,
ax_anim 3, 0, 252, 0, 0, 0, 0,
ax_anim 8, 0, 253, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_16_6:
ax_anim 8, 0, 251, 0, 0, 0, 0,
ax_anim 3, 0, 252, 0, 0, 0, 0,
ax_anim 8, 0, 253, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_16_7:
ax_anim 8, 0, 251, 0, 0, 0, 0,
ax_anim 3, 0, 252, 0, 0, 0, 0,
ax_anim 8, 0, 253, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_16_8:
ax_anim 8, 0, 251, 0, 0, 0, 0,
ax_anim 3, 0, 252, 0, 0, 0, 0,
ax_anim 8, 0, 253, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sPikachuAnims_17_1:
ax_anim 12, 0, 255, 0, 0, 0, 0,
ax_anim 2, 0, 254, 0, 0, 0, 0,
ax_anim 2, 0, 254, -1, 0, -1, 0,
ax_anim 2, 0, 254, 0, 0, 0, 0,
ax_anim 2, 0, 254, -1, 0, -1, 0,
ax_anim 2, 0, 254, 0, 0, 0, 0,
ax_anim 2, 0, 254, -1, 0, -1, 0,
ax_anim 2, 0, 254, 0, 0, 0, 0,
ax_anim 2, 0, 254, -1, 0, -1, 0,
ax_anim_terminator
sPikachuAnims_17_2:
ax_anim 12, 0, 255, 0, 0, 0, 0,
ax_anim 2, 0, 254, 0, 0, 0, 0,
ax_anim 2, 0, 254, -1, 0, -1, 0,
ax_anim 2, 0, 254, 0, 0, 0, 0,
ax_anim 2, 0, 254, -1, 0, -1, 0,
ax_anim 2, 0, 254, 0, 0, 0, 0,
ax_anim 2, 0, 254, -1, 0, -1, 0,
ax_anim 2, 0, 254, 0, 0, 0, 0,
ax_anim 2, 0, 254, -1, 0, -1, 0,
ax_anim_terminator
sPikachuAnims_17_3:
ax_anim 12, 0, 255, 0, 0, 0, 0,
ax_anim 2, 0, 254, 0, 0, 0, 0,
ax_anim 2, 0, 254, -1, 0, -1, 0,
ax_anim 2, 0, 254, 0, 0, 0, 0,
ax_anim 2, 0, 254, -1, 0, -1, 0,
ax_anim 2, 0, 254, 0, 0, 0, 0,
ax_anim 2, 0, 254, -1, 0, -1, 0,
ax_anim 2, 0, 254, 0, 0, 0, 0,
ax_anim 2, 0, 254, -1, 0, -1, 0,
ax_anim_terminator
sPikachuAnims_17_4:
ax_anim 12, 0, 255, 0, 0, 0, 0,
ax_anim 2, 0, 254, 0, 0, 0, 0,
ax_anim 2, 0, 254, -1, 0, -1, 0,
ax_anim 2, 0, 254, 0, 0, 0, 0,
ax_anim 2, 0, 254, -1, 0, -1, 0,
ax_anim 2, 0, 254, 0, 0, 0, 0,
ax_anim 2, 0, 254, -1, 0, -1, 0,
ax_anim 2, 0, 254, 0, 0, 0, 0,
ax_anim 2, 0, 254, -1, 0, -1, 0,
ax_anim_terminator
sPikachuAnims_17_5:
ax_anim 12, 0, 255, 0, 0, 0, 0,
ax_anim 2, 0, 254, 0, 0, 0, 0,
ax_anim 2, 0, 254, -1, 0, -1, 0,
ax_anim 2, 0, 254, 0, 0, 0, 0,
ax_anim 2, 0, 254, -1, 0, -1, 0,
ax_anim 2, 0, 254, 0, 0, 0, 0,
ax_anim 2, 0, 254, -1, 0, -1, 0,
ax_anim 2, 0, 254, 0, 0, 0, 0,
ax_anim 2, 0, 254, -1, 0, -1, 0,
ax_anim_terminator
sPikachuAnims_17_6:
ax_anim 12, 0, 255, 0, 0, 0, 0,
ax_anim 2, 0, 254, 0, 0, 0, 0,
ax_anim 2, 0, 254, -1, 0, -1, 0,
ax_anim 2, 0, 254, 0, 0, 0, 0,
ax_anim 2, 0, 254, -1, 0, -1, 0,
ax_anim 2, 0, 254, 0, 0, 0, 0,
ax_anim 2, 0, 254, -1, 0, -1, 0,
ax_anim 2, 0, 254, 0, 0, 0, 0,
ax_anim 2, 0, 254, -1, 0, -1, 0,
ax_anim_terminator
sPikachuAnims_17_7:
ax_anim 12, 0, 255, 0, 0, 0, 0,
ax_anim 2, 0, 254, 0, 0, 0, 0,
ax_anim 2, 0, 254, -1, 0, -1, 0,
ax_anim 2, 0, 254, 0, 0, 0, 0,
ax_anim 2, 0, 254, -1, 0, -1, 0,
ax_anim 2, 0, 254, 0, 0, 0, 0,
ax_anim 2, 0, 254, -1, 0, -1, 0,
ax_anim 2, 0, 254, 0, 0, 0, 0,
ax_anim 2, 0, 254, -1, 0, -1, 0,
ax_anim_terminator
sPikachuAnims_17_8:
ax_anim 12, 0, 255, 0, 0, 0, 0,
ax_anim 2, 0, 254, 0, 0, 0, 0,
ax_anim 2, 0, 254, -1, 0, -1, 0,
ax_anim 2, 0, 254, 0, 0, 0, 0,
ax_anim 2, 0, 254, -1, 0, -1, 0,
ax_anim 2, 0, 254, 0, 0, 0, 0,
ax_anim 2, 0, 254, -1, 0, -1, 0,
ax_anim 2, 0, 254, 0, 0, 0, 0,
ax_anim 2, 0, 254, -1, 0, -1, 0,
ax_anim_terminator
.align 2
sPikachuAnims_18_1:
ax_anim 12, 0, 256, 0, 0, 0, 0,
ax_anim 2, 0, 257, 0, 0, 0, 0,
ax_anim 8, 0, 258, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_18_2:
ax_anim 12, 0, 256, 0, 0, 0, 0,
ax_anim 2, 0, 257, 0, 0, 0, 0,
ax_anim 8, 0, 258, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_18_3:
ax_anim 12, 0, 256, 0, 0, 0, 0,
ax_anim 2, 0, 257, 0, 0, 0, 0,
ax_anim 8, 0, 258, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_18_4:
ax_anim 12, 0, 256, 0, 0, 0, 0,
ax_anim 2, 0, 257, 0, 0, 0, 0,
ax_anim 8, 0, 258, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_18_5:
ax_anim 12, 0, 259, 0, 0, 0, 0,
ax_anim 2, 0, 260, 0, 0, 0, 0,
ax_anim 8, 0, 261, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_18_6:
ax_anim 12, 0, 256, 0, 0, 0, 0,
ax_anim 2, 0, 257, 0, 0, 0, 0,
ax_anim 8, 0, 258, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_18_7:
ax_anim 12, 0, 256, 0, 0, 0, 0,
ax_anim 2, 0, 257, 0, 0, 0, 0,
ax_anim 8, 0, 258, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_18_8:
ax_anim 12, 0, 256, 0, 0, 0, 0,
ax_anim 2, 0, 257, 0, 0, 0, 0,
ax_anim 8, 0, 258, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sPikachuAnims_19_1:
ax_anim 8, 0, 262, 0, 0, 0, 0,
ax_anim 10, 0, 263, 0, 0, 0, 0,
ax_anim 8, 0, 262, 0, 0, 0, 0,
ax_anim 10, 0, 264, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_19_2:
ax_anim 8, 0, 262, 0, 0, 0, 0,
ax_anim 10, 0, 263, 0, 0, 0, 0,
ax_anim 8, 0, 262, 0, 0, 0, 0,
ax_anim 10, 0, 264, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_19_3:
ax_anim 8, 0, 262, 0, 0, 0, 0,
ax_anim 10, 0, 263, 0, 0, 0, 0,
ax_anim 8, 0, 262, 0, 0, 0, 0,
ax_anim 10, 0, 264, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_19_4:
ax_anim 8, 0, 262, 0, 0, 0, 0,
ax_anim 10, 0, 263, 0, 0, 0, 0,
ax_anim 8, 0, 262, 0, 0, 0, 0,
ax_anim 10, 0, 264, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_19_5:
ax_anim 8, 0, 262, 0, 0, 0, 0,
ax_anim 10, 0, 263, 0, 0, 0, 0,
ax_anim 8, 0, 262, 0, 0, 0, 0,
ax_anim 10, 0, 264, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_19_6:
ax_anim 8, 0, 262, 0, 0, 0, 0,
ax_anim 10, 0, 263, 0, 0, 0, 0,
ax_anim 8, 0, 262, 0, 0, 0, 0,
ax_anim 10, 0, 264, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_19_7:
ax_anim 8, 0, 262, 0, 0, 0, 0,
ax_anim 10, 0, 263, 0, 0, 0, 0,
ax_anim 8, 0, 262, 0, 0, 0, 0,
ax_anim 10, 0, 264, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_19_8:
ax_anim 8, 0, 262, 0, 0, 0, 0,
ax_anim 10, 0, 263, 0, 0, 0, 0,
ax_anim 8, 0, 262, 0, 0, 0, 0,
ax_anim 10, 0, 264, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sPikachuAnims_20_1:
ax_anim 4, 0, 265, 0, 0, 0, 0,
ax_anim 1, 0, 266, 0, 0, 0, 0,
ax_anim 1, 0, 266, 0, -2, 0, 0,
ax_anim 1, 0, 266, 0, -4, 0, 0,
ax_anim 2, 0, 267, 0, -4, 0, 0,
ax_anim 1, 0, 267, 0, -2, 0, 0,
ax_anim 4, 0, 267, 0, 1, 0, 0,
ax_anim 2, 0, 267, 1, 1, 1, 0,
ax_anim 2, 0, 267, 0, 1, 0, 0,
ax_anim 2, 0, 267, 1, 1, 1, 0,
ax_anim 2, 0, 267, 0, 1, 0, 0,
ax_anim 2, 0, 267, 1, 1, 1, 0,
ax_anim_terminator
sPikachuAnims_20_2:
ax_anim 4, 0, 265, 0, 0, 0, 0,
ax_anim 1, 0, 266, 0, 0, 0, 0,
ax_anim 1, 0, 266, 0, -2, 0, 0,
ax_anim 1, 0, 266, 0, -4, 0, 0,
ax_anim 2, 0, 267, 0, -4, 0, 0,
ax_anim 1, 0, 267, 0, -2, 0, 0,
ax_anim 4, 0, 267, 0, 0, 0, 0,
ax_anim 2, 0, 267, 1, 0, 1, 0,
ax_anim 2, 0, 267, 0, 0, 0, 0,
ax_anim 2, 0, 267, 1, 0, 1, 0,
ax_anim 2, 0, 267, 0, 0, 0, 0,
ax_anim 2, 0, 267, 1, 0, 1, 0,
ax_anim_terminator
sPikachuAnims_20_3:
ax_anim 4, 0, 265, 0, 0, 0, 0,
ax_anim 1, 0, 266, 0, 0, 0, 0,
ax_anim 1, 0, 266, 0, -2, 0, 0,
ax_anim 1, 0, 266, 0, -4, 0, 0,
ax_anim 2, 0, 267, 0, -4, 0, 0,
ax_anim 1, 0, 267, 0, -2, 0, 0,
ax_anim 4, 0, 267, 0, 0, 0, 0,
ax_anim 2, 0, 267, 1, 0, 1, 0,
ax_anim 2, 0, 267, 0, 0, 0, 0,
ax_anim 2, 0, 267, 1, 0, 1, 0,
ax_anim 2, 0, 267, 0, 0, 0, 0,
ax_anim 2, 0, 267, 1, 0, 1, 0,
ax_anim_terminator
sPikachuAnims_20_4:
ax_anim 4, 0, 265, 0, 0, 0, 0,
ax_anim 1, 0, 266, 0, 0, 0, 0,
ax_anim 1, 0, 266, 0, -2, 0, 0,
ax_anim 1, 0, 266, 0, -4, 0, 0,
ax_anim 2, 0, 267, 0, -4, 0, 0,
ax_anim 1, 0, 267, 0, -2, 0, 0,
ax_anim 4, 0, 267, 0, 0, 0, 0,
ax_anim 2, 0, 267, 1, 0, 1, 0,
ax_anim 2, 0, 267, 0, 0, 0, 0,
ax_anim 2, 0, 267, 1, 0, 1, 0,
ax_anim 2, 0, 267, 0, 0, 0, 0,
ax_anim 2, 0, 267, 1, 0, 1, 0,
ax_anim_terminator
sPikachuAnims_20_5:
ax_anim 4, 0, 265, 0, 0, 0, 0,
ax_anim 1, 0, 266, 0, 0, 0, 0,
ax_anim 1, 0, 266, 0, -2, 0, 0,
ax_anim 1, 0, 266, 0, -4, 0, 0,
ax_anim 2, 0, 267, 0, -4, 0, 0,
ax_anim 1, 0, 267, 0, -2, 0, 0,
ax_anim 4, 0, 267, 0, 0, 0, 0,
ax_anim 2, 0, 267, 1, 0, 1, 0,
ax_anim 2, 0, 267, 0, 0, 0, 0,
ax_anim 2, 0, 267, 1, 0, 1, 0,
ax_anim 2, 0, 267, 0, 0, 0, 0,
ax_anim 2, 0, 267, 1, 0, 1, 0,
ax_anim_terminator
sPikachuAnims_20_6:
ax_anim 4, 0, 265, 0, 0, 0, 0,
ax_anim 1, 0, 266, 0, 0, 0, 0,
ax_anim 1, 0, 266, 0, -2, 0, 0,
ax_anim 1, 0, 266, 0, -4, 0, 0,
ax_anim 2, 0, 267, 0, -4, 0, 0,
ax_anim 1, 0, 267, 0, -2, 0, 0,
ax_anim 4, 0, 267, 0, 0, 0, 0,
ax_anim 2, 0, 267, 1, 0, 1, 0,
ax_anim 2, 0, 267, 0, 0, 0, 0,
ax_anim 2, 0, 267, 1, 0, 1, 0,
ax_anim 2, 0, 267, 0, 0, 0, 0,
ax_anim 2, 0, 267, 1, 0, 1, 0,
ax_anim_terminator
sPikachuAnims_20_7:
ax_anim 4, 0, 265, 0, 0, 0, 0,
ax_anim 1, 0, 266, 0, 0, 0, 0,
ax_anim 1, 0, 266, 0, -2, 0, 0,
ax_anim 1, 0, 266, 0, -4, 0, 0,
ax_anim 2, 0, 267, 0, -4, 0, 0,
ax_anim 1, 0, 267, 0, -2, 0, 0,
ax_anim 4, 0, 267, 0, 0, 0, 0,
ax_anim 2, 0, 267, 1, 0, 1, 0,
ax_anim 2, 0, 267, 0, 0, 0, 0,
ax_anim 2, 0, 267, 1, 0, 1, 0,
ax_anim 2, 0, 267, 0, 0, 0, 0,
ax_anim 2, 0, 267, 1, 0, 1, 0,
ax_anim_terminator
sPikachuAnims_20_8:
ax_anim 4, 0, 265, 0, 0, 0, 0,
ax_anim 1, 0, 266, 0, 0, 0, 0,
ax_anim 1, 0, 266, 0, -2, 0, 0,
ax_anim 1, 0, 266, 0, -4, 0, 0,
ax_anim 2, 0, 267, 0, -4, 0, 0,
ax_anim 1, 0, 267, 0, -2, 0, 0,
ax_anim 4, 0, 267, 0, 0, 0, 0,
ax_anim 2, 0, 267, 1, 0, 1, 0,
ax_anim 2, 0, 267, 0, 0, 0, 0,
ax_anim 2, 0, 267, 1, 0, 1, 0,
ax_anim 2, 0, 267, 0, 0, 0, 0,
ax_anim 2, 0, 267, 1, 0, 1, 0,
ax_anim_terminator
.align 2
sPikachuAnims_21_1:
ax_anim 8, 0, 268, 0, 0, 0, 0,
ax_anim 8, 0, 269, 0, 0, 0, 0,
ax_anim 8, 0, 270, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_21_2:
ax_anim 8, 0, 268, 0, 0, 0, 0,
ax_anim 8, 0, 269, 0, 0, 0, 0,
ax_anim 8, 0, 270, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_21_3:
ax_anim 8, 0, 268, 0, 0, 0, 0,
ax_anim 8, 0, 269, 0, 0, 0, 0,
ax_anim 8, 0, 270, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_21_4:
ax_anim 8, 0, 268, 0, 0, 0, 0,
ax_anim 8, 0, 269, 0, 0, 0, 0,
ax_anim 8, 0, 270, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_21_5:
ax_anim 8, 0, 268, 0, 0, 0, 0,
ax_anim 8, 0, 269, 0, 0, 0, 0,
ax_anim 8, 0, 270, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_21_6:
ax_anim 8, 0, 268, 0, 0, 0, 0,
ax_anim 8, 0, 269, 0, 0, 0, 0,
ax_anim 8, 0, 270, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_21_7:
ax_anim 8, 0, 268, 0, 0, 0, 0,
ax_anim 8, 0, 269, 0, 0, 0, 0,
ax_anim 8, 0, 270, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_21_8:
ax_anim 8, 0, 268, 0, 0, 0, 0,
ax_anim 8, 0, 269, 0, 0, 0, 0,
ax_anim 8, 0, 270, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sPikachuAnims_22_1:
ax_anim 30, 0, 272, 0, 0, 0, 0,
ax_anim 34, 0, 273, 0, 0, 0, 0,
ax_anim 30, 0, 272, 0, 0, 0, 0,
ax_anim 34, 0, 273, 0, 0, 0, 0,
ax_anim 4, 0, 271, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_22_2:
ax_anim 30, 0, 272, 0, 0, 0, 0,
ax_anim 34, 0, 273, 0, 0, 0, 0,
ax_anim 30, 0, 272, 0, 0, 0, 0,
ax_anim 34, 0, 273, 0, 0, 0, 0,
ax_anim 4, 0, 271, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_22_3:
ax_anim 30, 0, 272, 0, 0, 0, 0,
ax_anim 34, 0, 273, 0, 0, 0, 0,
ax_anim 30, 0, 272, 0, 0, 0, 0,
ax_anim 34, 0, 273, 0, 0, 0, 0,
ax_anim 4, 0, 271, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_22_4:
ax_anim 30, 0, 272, 0, 0, 0, 0,
ax_anim 34, 0, 273, 0, 0, 0, 0,
ax_anim 30, 0, 272, 0, 0, 0, 0,
ax_anim 34, 0, 273, 0, 0, 0, 0,
ax_anim 4, 0, 271, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_22_5:
ax_anim 30, 0, 272, 0, 0, 0, 0,
ax_anim 34, 0, 273, 0, 0, 0, 0,
ax_anim 30, 0, 272, 0, 0, 0, 0,
ax_anim 34, 0, 273, 0, 0, 0, 0,
ax_anim 4, 0, 271, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_22_6:
ax_anim 30, 0, 272, 0, 0, 0, 0,
ax_anim 34, 0, 273, 0, 0, 0, 0,
ax_anim 30, 0, 272, 0, 0, 0, 0,
ax_anim 34, 0, 273, 0, 0, 0, 0,
ax_anim 4, 0, 271, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_22_7:
ax_anim 30, 0, 272, 0, 0, 0, 0,
ax_anim 34, 0, 273, 0, 0, 0, 0,
ax_anim 30, 0, 272, 0, 0, 0, 0,
ax_anim 34, 0, 273, 0, 0, 0, 0,
ax_anim 4, 0, 271, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_22_8:
ax_anim 30, 0, 272, 0, 0, 0, 0,
ax_anim 34, 0, 273, 0, 0, 0, 0,
ax_anim 30, 0, 272, 0, 0, 0, 0,
ax_anim 34, 0, 273, 0, 0, 0, 0,
ax_anim 4, 0, 271, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sPikachuAnims_23_1:
ax_anim 10, 0, 274, 0, 0, 0, 0,
ax_anim 8, 0, 275, 0, 0, 0, 0,
ax_anim 12, 0, 274, 0, 0, 0, 0,
ax_anim 8, 0, 275, 0, 0, 0, 0,
ax_anim 4, 0, 274, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_23_2:
ax_anim 10, 0, 274, 0, 0, 0, 0,
ax_anim 8, 0, 275, 0, 0, 0, 0,
ax_anim 12, 0, 274, 0, 0, 0, 0,
ax_anim 8, 0, 275, 0, 0, 0, 0,
ax_anim 4, 0, 274, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_23_3:
ax_anim 10, 0, 276, 0, 0, 0, 0,
ax_anim 8, 0, 277, 0, 0, 0, 0,
ax_anim 12, 0, 276, 0, 0, 0, 0,
ax_anim 8, 0, 277, 0, 0, 0, 0,
ax_anim 4, 0, 276, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_23_4:
ax_anim 10, 0, 274, 0, 0, 0, 0,
ax_anim 8, 0, 275, 0, 0, 0, 0,
ax_anim 12, 0, 274, 0, 0, 0, 0,
ax_anim 8, 0, 275, 0, 0, 0, 0,
ax_anim 4, 0, 274, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_23_5:
ax_anim 10, 0, 274, 0, 0, 0, 0,
ax_anim 8, 0, 275, 0, 0, 0, 0,
ax_anim 12, 0, 274, 0, 0, 0, 0,
ax_anim 8, 0, 275, 0, 0, 0, 0,
ax_anim 4, 0, 274, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_23_6:
ax_anim 10, 0, 274, 0, 0, 0, 0,
ax_anim 8, 0, 275, 0, 0, 0, 0,
ax_anim 12, 0, 274, 0, 0, 0, 0,
ax_anim 8, 0, 275, 0, 0, 0, 0,
ax_anim 4, 0, 274, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_23_7:
ax_anim 10, 0, 274, 0, 0, 0, 0,
ax_anim 8, 0, 275, 0, 0, 0, 0,
ax_anim 12, 0, 274, 0, 0, 0, 0,
ax_anim 8, 0, 275, 0, 0, 0, 0,
ax_anim 4, 0, 274, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_23_8:
ax_anim 10, 0, 274, 0, 0, 0, 0,
ax_anim 8, 0, 275, 0, 0, 0, 0,
ax_anim 12, 0, 274, 0, 0, 0, 0,
ax_anim 8, 0, 275, 0, 0, 0, 0,
ax_anim 4, 0, 274, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sPikachuAnims_24_1:
ax_anim 4, 0, 279, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_24_2:
ax_anim 4, 0, 279, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_24_3:
ax_anim 4, 0, 279, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_24_4:
ax_anim 4, 0, 279, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_24_5:
ax_anim 4, 0, 279, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_24_6:
ax_anim 4, 0, 279, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_24_7:
ax_anim 4, 0, 279, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_24_8:
ax_anim 4, 0, 279, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sPikachuAnims_25_1:
ax_anim 10, 0, 285, 0, 0, 0, 0,
ax_anim 8, 0, 286, 0, 0, 0, 0,
ax_anim 12, 0, 287, 0, 0, 0, 0,
ax_anim 10, 0, 285, 0, 0, 0, 0,
ax_anim 8, 0, 288, 0, 0, 0, 0,
ax_anim 12, 0, 289, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_25_2:
ax_anim 10, 0, 285, 0, 0, 0, 0,
ax_anim 8, 0, 286, 0, 0, 0, 0,
ax_anim 12, 0, 287, 0, 0, 0, 0,
ax_anim 10, 0, 285, 0, 0, 0, 0,
ax_anim 8, 0, 288, 0, 0, 0, 0,
ax_anim 12, 0, 289, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_25_3:
ax_anim 10, 0, 285, 0, 0, 0, 0,
ax_anim 8, 0, 286, 0, 0, 0, 0,
ax_anim 12, 0, 287, 0, 0, 0, 0,
ax_anim 10, 0, 285, 0, 0, 0, 0,
ax_anim 8, 0, 288, 0, 0, 0, 0,
ax_anim 12, 0, 289, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_25_4:
ax_anim 10, 0, 285, 0, 0, 0, 0,
ax_anim 8, 0, 286, 0, 0, 0, 0,
ax_anim 12, 0, 287, 0, 0, 0, 0,
ax_anim 10, 0, 285, 0, 0, 0, 0,
ax_anim 8, 0, 288, 0, 0, 0, 0,
ax_anim 12, 0, 289, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_25_5:
ax_anim 10, 0, 285, 0, 0, 0, 0,
ax_anim 8, 0, 286, 0, 0, 0, 0,
ax_anim 12, 0, 287, 0, 0, 0, 0,
ax_anim 10, 0, 285, 0, 0, 0, 0,
ax_anim 8, 0, 288, 0, 0, 0, 0,
ax_anim 12, 0, 289, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_25_6:
ax_anim 10, 0, 285, 0, 0, 0, 0,
ax_anim 8, 0, 286, 0, 0, 0, 0,
ax_anim 12, 0, 287, 0, 0, 0, 0,
ax_anim 10, 0, 285, 0, 0, 0, 0,
ax_anim 8, 0, 288, 0, 0, 0, 0,
ax_anim 12, 0, 289, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_25_7:
ax_anim 10, 0, 280, 0, 0, 0, 0,
ax_anim 8, 0, 281, 0, 0, 0, 0,
ax_anim 12, 0, 282, 0, 0, 0, 0,
ax_anim 10, 0, 280, 0, 0, 0, 0,
ax_anim 8, 0, 283, 0, 0, 0, 0,
ax_anim 12, 0, 284, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_25_8:
ax_anim 10, 0, 280, 0, 0, 0, 0,
ax_anim 8, 0, 281, 0, 0, 0, 0,
ax_anim 12, 0, 282, 0, 0, 0, 0,
ax_anim 10, 0, 280, 0, 0, 0, 0,
ax_anim 8, 0, 283, 0, 0, 0, 0,
ax_anim 12, 0, 284, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sPikachuAnims_26_1:
ax_anim 2, 0, 290, 0, 0, 0, 0,
ax_anim 2, 0, 290, 1, 1, 1, 1,
ax_anim_terminator
sPikachuAnims_26_2:
ax_anim 2, 0, 290, 0, 0, 0, 0,
ax_anim 2, 0, 290, 1, 1, 1, 1,
ax_anim_terminator
sPikachuAnims_26_3:
ax_anim 2, 0, 290, 0, 0, 0, 0,
ax_anim 2, 0, 290, 1, 1, 1, 1,
ax_anim_terminator
sPikachuAnims_26_4:
ax_anim 2, 0, 290, 0, 0, 0, 0,
ax_anim 2, 0, 290, 1, 1, 1, 1,
ax_anim_terminator
sPikachuAnims_26_5:
ax_anim 2, 0, 290, 0, 0, 0, 0,
ax_anim 2, 0, 290, 1, 1, 1, 1,
ax_anim_terminator
sPikachuAnims_26_6:
ax_anim 2, 0, 290, 0, 0, 0, 0,
ax_anim 2, 0, 290, 1, 1, 1, 1,
ax_anim_terminator
sPikachuAnims_26_7:
ax_anim 2, 0, 290, 0, 0, 0, 0,
ax_anim 2, 0, 290, 1, 1, 1, 1,
ax_anim_terminator
sPikachuAnims_26_8:
ax_anim 2, 0, 290, 0, 0, 0, 0,
ax_anim 2, 0, 290, 1, 1, 1, 1,
ax_anim_terminator
.align 2
sPikachuAnims_27_1:
ax_anim 12, 0, 291, 0, 0, 0, 0,
ax_anim 12, 0, 291, 0, 0, 0, 0,
ax_anim 16, 0, 291, -1, 0, 0, 0,
ax_anim 12, 0, 291, 0, 0, 0, 0,
ax_anim 12, 0, 291, 1, 0, 0, 0,
ax_anim 16, 0, 291, 2, 0, 0, 0,
ax_anim_terminator
.align 2
sPikachuAnims_28_1:
ax_anim 12, 0, 295, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_28_2:
ax_anim 12, 0, 295, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_28_3:
ax_anim 12, 0, 297, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_28_4:
ax_anim 12, 0, 295, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_28_5:
ax_anim 12, 0, 295, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_28_6:
ax_anim 12, 0, 295, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_28_7:
ax_anim 12, 0, 295, 0, 0, 0, 0,
ax_anim_terminator
sPikachuAnims_28_8:
ax_anim 12, 0, 295, 0, 0, 0, 0,
ax_anim_terminator
sPikachuGfx1:
.incbin "baserom.gba", 0x61BC70, 0x200
sPikachuSprites1:
ax_sprite sPikachuGfx1, 0x200
ax_sprite_terminator
sPikachuGfx2:
.incbin "baserom.gba", 0x61BE80, 0x200
sPikachuSprites2:
ax_sprite sPikachuGfx2, 0x200
ax_sprite_terminator
sPikachuGfx3:
.incbin "baserom.gba", 0x61C090, 0x200
sPikachuSprites3:
ax_sprite sPikachuGfx3, 0x200
ax_sprite_terminator
sPikachuGfx4:
.incbin "baserom.gba", 0x61C2A0, 0x200
sPikachuSprites4:
ax_sprite sPikachuGfx4, 0x200
ax_sprite_terminator
sPikachuGfx5:
.incbin "baserom.gba", 0x61C4B0, 0x200
sPikachuSprites5:
ax_sprite sPikachuGfx5, 0x200
ax_sprite_terminator
sPikachuGfx6:
.incbin "baserom.gba", 0x61C6C0, 0x200
sPikachuSprites6:
ax_sprite sPikachuGfx6, 0x200
ax_sprite_terminator
sPikachuGfx7:
.incbin "baserom.gba", 0x61C8D0, 0x200
sPikachuSprites7:
ax_sprite sPikachuGfx7, 0x200
ax_sprite_terminator
sPikachuGfx8:
.incbin "baserom.gba", 0x61CAE0, 0x200
sPikachuSprites8:
ax_sprite sPikachuGfx8, 0x200
ax_sprite_terminator
sPikachuGfx9:
.incbin "baserom.gba", 0x61CCF0, 0x200
sPikachuSprites9:
ax_sprite sPikachuGfx9, 0x200
ax_sprite_terminator
sPikachuGfx10:
.incbin "baserom.gba", 0x61CF00, 0x200
sPikachuSprites10:
ax_sprite sPikachuGfx10, 0x200
ax_sprite_terminator
sPikachuGfx11:
.incbin "baserom.gba", 0x61D110, 0x200
sPikachuSprites11:
ax_sprite sPikachuGfx11, 0x200
ax_sprite_terminator
sPikachuGfx12:
.incbin "baserom.gba", 0x61D320, 0x200
sPikachuSprites12:
ax_sprite sPikachuGfx12, 0x200
ax_sprite_terminator
sPikachuGfx13:
.incbin "baserom.gba", 0x61D530, 0x200
sPikachuSprites13:
ax_sprite sPikachuGfx13, 0x200
ax_sprite_terminator
sPikachuGfx14:
.incbin "baserom.gba", 0x61D740, 0x200
sPikachuSprites14:
ax_sprite sPikachuGfx14, 0x200
ax_sprite_terminator
sPikachuGfx15:
.incbin "baserom.gba", 0x61D950, 0x200
sPikachuSprites15:
ax_sprite sPikachuGfx15, 0x200
ax_sprite_terminator
sPikachuGfx16:
.incbin "baserom.gba", 0x61DB60, 0x60
sPikachuGfx16_1:
.incbin "baserom.gba", 0x61DBC0, 0x60
sPikachuGfx16_2:
.incbin "baserom.gba", 0x61DC20, 0x60
sPikachuSprites16:
ax_sprite sPikachuGfx16, 0x60
ax_sprite 0, 0x20
ax_sprite sPikachuGfx16_1, 0x60
ax_sprite 0, 0x20
ax_sprite sPikachuGfx16_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sPikachuGfx17:
.incbin "baserom.gba", 0x61DCB8, 0x40
sPikachuGfx17_1:
.incbin "baserom.gba", 0x61DCF8, 0x100
sPikachuGfx17_2:
.incbin "baserom.gba", 0x61DDF8, 0x40
sPikachuSprites17:
ax_sprite sPikachuGfx17, 0x40
ax_sprite 0, 0x40
ax_sprite sPikachuGfx17_1, 0x100
ax_sprite 0, 0x20
ax_sprite sPikachuGfx17_2, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sPikachuGfx18:
.incbin "baserom.gba", 0x61DE70, 0x160
sPikachuSprites18:
ax_sprite sPikachuGfx18, 0x160
ax_sprite 0, 0xa0
ax_sprite_terminator
sPikachuGfx19:
.incbin "baserom.gba", 0x61DFE8, 0x60
sPikachuGfx19_1:
.incbin "baserom.gba", 0x61E048, 0xE0
sPikachuSprites19:
ax_sprite sPikachuGfx19, 0x60
ax_sprite 0, 0x20
ax_sprite sPikachuGfx19_1, 0xe0
ax_sprite 0, 0xa0
ax_sprite_terminator
sPikachuGfx20:
.incbin "baserom.gba", 0x61E150, 0x60
sPikachuGfx20_1:
.incbin "baserom.gba", 0x61E1B0, 0x60
sPikachuGfx20_2:
.incbin "baserom.gba", 0x61E210, 0x60
sPikachuGfx20_3:
.incbin "baserom.gba", 0x61E270, 0x20
sPikachuSprites20:
ax_sprite sPikachuGfx20, 0x60
ax_sprite 0, 0x20
ax_sprite sPikachuGfx20_1, 0x60
ax_sprite 0, 0x20
ax_sprite sPikachuGfx20_2, 0x60
ax_sprite 0, 0x20
ax_sprite sPikachuGfx20_3, 0x20
ax_sprite 0, 0x60
ax_sprite_terminator
sPikachuGfx21:
.incbin "baserom.gba", 0x61E2D8, 0x60
sPikachuGfx21_1:
.incbin "baserom.gba", 0x61E338, 0x60
sPikachuGfx21_2:
.incbin "baserom.gba", 0x61E398, 0x60
sPikachuGfx21_3:
.incbin "baserom.gba", 0x61E3F8, 0x60
sPikachuSprites21:
ax_sprite sPikachuGfx21, 0x60
ax_sprite 0, 0x20
ax_sprite sPikachuGfx21_1, 0x60
ax_sprite 0, 0x20
ax_sprite sPikachuGfx21_2, 0x60
ax_sprite 0, 0x20
ax_sprite sPikachuGfx21_3, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sPikachuGfx22:
.incbin "baserom.gba", 0x61E4A0, 0x40
sPikachuGfx22_1:
.incbin "baserom.gba", 0x61E4E0, 0xE0
sPikachuGfx22_2:
.incbin "baserom.gba", 0x61E5C0, 0x40
sPikachuSprites22:
ax_sprite sPikachuGfx22, 0x40
ax_sprite 0, 0x40
ax_sprite sPikachuGfx22_1, 0xe0
ax_sprite 0, 0x20
ax_sprite sPikachuGfx22_2, 0x40
ax_sprite 0, 0x40
ax_sprite_terminator
sPikachuGfx23:
.incbin "baserom.gba", 0x61E638, 0x160
sPikachuSprites23:
ax_sprite sPikachuGfx23, 0x160
ax_sprite 0, 0xa0
ax_sprite_terminator
sPikachuGfx24:
.incbin "baserom.gba", 0x61E7B0, 0x60
sPikachuGfx24_1:
.incbin "baserom.gba", 0x61E810, 0x100
sPikachuSprites24:
ax_sprite sPikachuGfx24, 0x60
ax_sprite 0, 0x20
ax_sprite sPikachuGfx24_1, 0x100
ax_sprite 0, 0x80
ax_sprite_terminator
sPikachuGfx25:
.incbin "baserom.gba", 0x61E938, 0x60
sPikachuGfx25_1:
.incbin "baserom.gba", 0x61E998, 0x60
sPikachuGfx25_2:
.incbin "baserom.gba", 0x61E9F8, 0x60
sPikachuGfx25_3:
.incbin "baserom.gba", 0x61EA58, 0x20
sPikachuSprites25:
ax_sprite sPikachuGfx25, 0x60
ax_sprite 0, 0x20
ax_sprite sPikachuGfx25_1, 0x60
ax_sprite 0, 0x20
ax_sprite sPikachuGfx25_2, 0x60
ax_sprite 0, 0x40
ax_sprite sPikachuGfx25_3, 0x20
ax_sprite 0, 0x40
ax_sprite_terminator
sPikachuGfx26:
.incbin "baserom.gba", 0x61EAC0, 0x120
sPikachuGfx26_1:
.incbin "baserom.gba", 0x61EBE0, 0x60
sPikachuGfx26_2:
.incbin "baserom.gba", 0x61EC40, 0x20
sPikachuSprites26:
ax_sprite 0, 0x20
ax_sprite sPikachuGfx26, 0x120
ax_sprite 0, 0x20
ax_sprite sPikachuGfx26_1, 0x60
ax_sprite 0, 0x20
ax_sprite sPikachuGfx26_2, 0x20
ax_sprite_terminator
sPikachuGfx27:
.incbin "baserom.gba", 0x61EC98, 0x80
sPikachuSprites27:
ax_sprite sPikachuGfx27, 0x80
ax_sprite_terminator
sPikachuGfx28:
.incbin "baserom.gba", 0x61ED28, 0x20
sPikachuGfx28_1:
.incbin "baserom.gba", 0x61ED48, 0x20
sPikachuSprites28:
ax_sprite 0, 0x20
ax_sprite sPikachuGfx28, 0x20
ax_sprite 0, 0x20
ax_sprite sPikachuGfx28_1, 0x20
ax_sprite_terminator
sPikachuGfx29:
.incbin "baserom.gba", 0x61ED90, 0x60
sPikachuGfx29_1:
.incbin "baserom.gba", 0x61EDF0, 0x60
sPikachuGfx29_2:
.incbin "baserom.gba", 0x61EE50, 0x60
sPikachuGfx29_3:
.incbin "baserom.gba", 0x61EEB0, 0x60
sPikachuSprites29:
ax_sprite sPikachuGfx29, 0x60
ax_sprite 0, 0x20
ax_sprite sPikachuGfx29_1, 0x60
ax_sprite 0, 0x20
ax_sprite sPikachuGfx29_2, 0x60
ax_sprite 0, 0x20
ax_sprite sPikachuGfx29_3, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sPikachuGfx30:
.incbin "baserom.gba", 0x61EF58, 0x140
sPikachuGfx30_1:
.incbin "baserom.gba", 0x61F098, 0x40
sPikachuGfx30_2:
.incbin "baserom.gba", 0x61F0D8, 0x20
sPikachuSprites30:
ax_sprite sPikachuGfx30, 0x140
ax_sprite 0, 0x40
ax_sprite sPikachuGfx30_1, 0x40
ax_sprite 0, 0x20
ax_sprite sPikachuGfx30_2, 0x20
ax_sprite_terminator
sPikachuGfx31:
.incbin "baserom.gba", 0x61F128, 0x80
sPikachuSprites31:
ax_sprite sPikachuGfx31, 0x80
ax_sprite_terminator
sPikachuGfx32:
.incbin "baserom.gba", 0x61F1B8, 0x40
sPikachuSprites32:
ax_sprite sPikachuGfx32, 0x40
ax_sprite_terminator
sPikachuGfx33:
.incbin "baserom.gba", 0x61F208, 0x40
sPikachuSprites33:
ax_sprite sPikachuGfx33, 0x40
ax_sprite_terminator
sPikachuGfx34:
.incbin "baserom.gba", 0x61F258, 0x60
sPikachuGfx34_1:
.incbin "baserom.gba", 0x61F2B8, 0x60
sPikachuGfx34_2:
.incbin "baserom.gba", 0x61F318, 0x60
sPikachuGfx34_3:
.incbin "baserom.gba", 0x61F378, 0x60
sPikachuSprites34:
ax_sprite sPikachuGfx34, 0x60
ax_sprite 0, 0x20
ax_sprite sPikachuGfx34_1, 0x60
ax_sprite 0, 0x20
ax_sprite sPikachuGfx34_2, 0x60
ax_sprite 0, 0x20
ax_sprite sPikachuGfx34_3, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sPikachuGfx35:
.incbin "baserom.gba", 0x61F420, 0x40
sPikachuGfx35_1:
.incbin "baserom.gba", 0x61F460, 0xA0
sPikachuGfx35_2:
.incbin "baserom.gba", 0x61F500, 0x80
sPikachuSprites35:
ax_sprite 0, 0x20
ax_sprite sPikachuGfx35, 0x40
ax_sprite 0, 0x40
ax_sprite sPikachuGfx35_1, 0xa0
ax_sprite 0, 0x40
ax_sprite sPikachuGfx35_2, 0x80
ax_sprite_terminator
sPikachuGfx36:
.incbin "baserom.gba", 0x61F5B8, 0x80
sPikachuSprites36:
ax_sprite sPikachuGfx36, 0x80
ax_sprite_terminator
sPikachuGfx37:
.incbin "baserom.gba", 0x61F648, 0x40
sPikachuSprites37:
ax_sprite sPikachuGfx37, 0x40
ax_sprite_terminator
sPikachuGfx38:
.incbin "baserom.gba", 0x61F698, 0x20
sPikachuGfx38_1:
.incbin "baserom.gba", 0x61F6B8, 0x20
sPikachuGfx38_2:
.incbin "baserom.gba", 0x61F6D8, 0x60
sPikachuGfx38_3:
.incbin "baserom.gba", 0x61F738, 0x60
sPikachuGfx38_4:
.incbin "baserom.gba", 0x61F798, 0x40
sPikachuSprites38:
ax_sprite sPikachuGfx38, 0x20
ax_sprite 0, 0x20
ax_sprite sPikachuGfx38_1, 0x20
ax_sprite 0, 0x20
ax_sprite sPikachuGfx38_2, 0x60
ax_sprite 0, 0x20
ax_sprite sPikachuGfx38_3, 0x60
ax_sprite 0, 0x20
ax_sprite sPikachuGfx38_4, 0x40
ax_sprite 0, 0x40
ax_sprite_terminator
sPikachuGfx39:
.incbin "baserom.gba", 0x61F830, 0x140
sPikachuGfx39_1:
.incbin "baserom.gba", 0x61F970, 0x60
sPikachuGfx39_2:
.incbin "baserom.gba", 0x61F9D0, 0x20
sPikachuSprites39:
ax_sprite sPikachuGfx39, 0x140
ax_sprite 0, 0x20
ax_sprite sPikachuGfx39_1, 0x60
ax_sprite 0, 0x20
ax_sprite sPikachuGfx39_2, 0x20
ax_sprite_terminator
sPikachuGfx40:
.incbin "baserom.gba", 0x61FA20, 0x80
sPikachuSprites40:
ax_sprite sPikachuGfx40, 0x80
ax_sprite_terminator
sPikachuGfx41:
.incbin "baserom.gba", 0x61FAB0, 0x40
sPikachuSprites41:
ax_sprite sPikachuGfx41, 0x40
ax_sprite_terminator
sPikachuGfx42:
.incbin "baserom.gba", 0x61FB00, 0x20
sPikachuGfx42_1:
.incbin "baserom.gba", 0x61FB20, 0x20
sPikachuGfx42_2:
.incbin "baserom.gba", 0x61FB40, 0x60
sPikachuGfx42_3:
.incbin "baserom.gba", 0x61FBA0, 0x60
sPikachuGfx42_4:
.incbin "baserom.gba", 0x61FC00, 0x40
sPikachuSprites42:
ax_sprite sPikachuGfx42, 0x20
ax_sprite 0, 0x20
ax_sprite sPikachuGfx42_1, 0x20
ax_sprite 0, 0x20
ax_sprite sPikachuGfx42_2, 0x60
ax_sprite 0, 0x20
ax_sprite sPikachuGfx42_3, 0x60
ax_sprite 0, 0x20
ax_sprite sPikachuGfx42_4, 0x40
ax_sprite 0, 0x40
ax_sprite_terminator
sPikachuGfx43:
.incbin "baserom.gba", 0x61FC98, 0x100
sPikachuGfx43_1:
.incbin "baserom.gba", 0x61FD98, 0xC0
sPikachuSprites43:
ax_sprite 0, 0x20
ax_sprite sPikachuGfx43, 0x100
ax_sprite 0, 0x20
ax_sprite sPikachuGfx43_1, 0xc0
ax_sprite_terminator
sPikachuGfx44:
.incbin "baserom.gba", 0x61FE80, 0x60
sPikachuSprites44:
ax_sprite 0, 0x20
ax_sprite sPikachuGfx44, 0x60
ax_sprite_terminator
sPikachuGfx45:
.incbin "baserom.gba", 0x61FEF8, 0x20
sPikachuSprites45:
ax_sprite sPikachuGfx45, 0x20
ax_sprite_terminator
sPikachuGfx46:
.incbin "baserom.gba", 0x61FF28, 0x60
sPikachuGfx46_1:
.incbin "baserom.gba", 0x61FF88, 0x60
sPikachuGfx46_2:
.incbin "baserom.gba", 0x61FFE8, 0x60
sPikachuGfx46_3:
.incbin "baserom.gba", 0x620048, 0x40
sPikachuSprites46:
ax_sprite sPikachuGfx46, 0x60
ax_sprite 0, 0x20
ax_sprite sPikachuGfx46_1, 0x60
ax_sprite 0, 0x20
ax_sprite sPikachuGfx46_2, 0x60
ax_sprite 0, 0x20
ax_sprite sPikachuGfx46_3, 0x40
ax_sprite 0, 0x40
ax_sprite_terminator
sPikachuGfx47:
.incbin "baserom.gba", 0x6200D0, 0x60
sPikachuGfx47_1:
.incbin "baserom.gba", 0x620130, 0x60
sPikachuGfx47_2:
.incbin "baserom.gba", 0x620190, 0x60
sPikachuGfx47_3:
.incbin "baserom.gba", 0x6201F0, 0x40
sPikachuSprites47:
ax_sprite sPikachuGfx47, 0x60
ax_sprite 0, 0x20
ax_sprite sPikachuGfx47_1, 0x60
ax_sprite 0, 0x20
ax_sprite sPikachuGfx47_2, 0x60
ax_sprite 0, 0x20
ax_sprite sPikachuGfx47_3, 0x40
ax_sprite 0, 0x40
ax_sprite_terminator
sPikachuGfx48:
.incbin "baserom.gba", 0x620278, 0x1A0
sPikachuGfx48_1:
.incbin "baserom.gba", 0x620418, 0x20
sPikachuSprites48:
ax_sprite 0, 0x20
ax_sprite sPikachuGfx48, 0x1a0
ax_sprite 0, 0x20
ax_sprite sPikachuGfx48_1, 0x20
ax_sprite_terminator
sPikachuGfx49:
.incbin "baserom.gba", 0x620460, 0x60
sPikachuSprites49:
ax_sprite 0, 0x20
ax_sprite sPikachuGfx49, 0x60
ax_sprite_terminator
sPikachuGfx50:
.incbin "baserom.gba", 0x6204D8, 0x40
sPikachuSprites50:
ax_sprite sPikachuGfx50, 0x40
ax_sprite_terminator
sPikachuGfx51:
.incbin "baserom.gba", 0x620528, 0x60
sPikachuGfx51_1:
.incbin "baserom.gba", 0x620588, 0x60
sPikachuGfx51_2:
.incbin "baserom.gba", 0x6205E8, 0x60
sPikachuGfx51_3:
.incbin "baserom.gba", 0x620648, 0x40
sPikachuSprites51:
ax_sprite sPikachuGfx51, 0x60
ax_sprite 0, 0x20
ax_sprite sPikachuGfx51_1, 0x60
ax_sprite 0, 0x20
ax_sprite sPikachuGfx51_2, 0x60
ax_sprite 0, 0x20
ax_sprite sPikachuGfx51_3, 0x40
ax_sprite 0, 0x40
ax_sprite_terminator
sPikachuGfx52:
.incbin "baserom.gba", 0x6206D0, 0x60
sPikachuGfx52_1:
.incbin "baserom.gba", 0x620730, 0x60
sPikachuGfx52_2:
.incbin "baserom.gba", 0x620790, 0x60
sPikachuGfx52_3:
.incbin "baserom.gba", 0x6207F0, 0x40
sPikachuSprites52:
ax_sprite sPikachuGfx52, 0x60
ax_sprite 0, 0x20
ax_sprite sPikachuGfx52_1, 0x60
ax_sprite 0, 0x20
ax_sprite sPikachuGfx52_2, 0x60
ax_sprite 0, 0x20
ax_sprite sPikachuGfx52_3, 0x40
ax_sprite 0, 0x40
ax_sprite_terminator
sPikachuGfx53:
.incbin "baserom.gba", 0x620878, 0xC0
sPikachuGfx53_1:
.incbin "baserom.gba", 0x620938, 0x60
sPikachuGfx53_2:
.incbin "baserom.gba", 0x620998, 0x60
sPikachuGfx53_3:
.incbin "baserom.gba", 0x6209F8, 0x20
sPikachuSprites53:
ax_sprite sPikachuGfx53, 0xc0
ax_sprite 0, 0x20
ax_sprite sPikachuGfx53_1, 0x60
ax_sprite 0, 0x20
ax_sprite sPikachuGfx53_2, 0x60
ax_sprite 0, 0x20
ax_sprite sPikachuGfx53_3, 0x20
ax_sprite_terminator
sPikachuGfx54:
.incbin "baserom.gba", 0x620A58, 0x80
sPikachuSprites54:
ax_sprite sPikachuGfx54, 0x80
ax_sprite_terminator
sPikachuGfx55:
.incbin "baserom.gba", 0x620AE8, 0x60
sPikachuGfx55_1:
.incbin "baserom.gba", 0x620B48, 0x60
sPikachuGfx55_2:
.incbin "baserom.gba", 0x620BA8, 0x60
sPikachuSprites55:
ax_sprite sPikachuGfx55, 0x60
ax_sprite 0, 0x20
ax_sprite sPikachuGfx55_1, 0x60
ax_sprite 0, 0x20
ax_sprite sPikachuGfx55_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sPikachuGfx56:
.incbin "baserom.gba", 0x620C40, 0x60
sPikachuGfx56_1:
.incbin "baserom.gba", 0x620CA0, 0x60
sPikachuGfx56_2:
.incbin "baserom.gba", 0x620D00, 0x60
sPikachuSprites56:
ax_sprite sPikachuGfx56, 0x60
ax_sprite 0, 0x20
ax_sprite sPikachuGfx56_1, 0x60
ax_sprite 0, 0x20
ax_sprite sPikachuGfx56_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sPikachuGfx57:
.incbin "baserom.gba", 0x620D98, 0x200
sPikachuSprites57:
ax_sprite sPikachuGfx57, 0x200
ax_sprite_terminator
sPikachuGfx58:
.incbin "baserom.gba", 0x620FA8, 0x200
sPikachuSprites58:
ax_sprite sPikachuGfx58, 0x200
ax_sprite_terminator
sPikachuGfx59:
.incbin "baserom.gba", 0x6211B8, 0x200
sPikachuSprites59:
ax_sprite sPikachuGfx59, 0x200
ax_sprite_terminator
sPikachuGfx60:
.incbin "baserom.gba", 0x6213C8, 0x200
sPikachuSprites60:
ax_sprite sPikachuGfx60, 0x200
ax_sprite_terminator
sPikachuGfx61:
.incbin "baserom.gba", 0x6215D8, 0x200
sPikachuSprites61:
ax_sprite sPikachuGfx61, 0x200
ax_sprite_terminator
sPikachuGfx62:
.incbin "baserom.gba", 0x6217E8, 0x200
sPikachuSprites62:
ax_sprite sPikachuGfx62, 0x200
ax_sprite_terminator
sPikachuGfx63:
.incbin "baserom.gba", 0x6219F8, 0x200
sPikachuSprites63:
ax_sprite sPikachuGfx63, 0x200
ax_sprite_terminator
sPikachuGfx64:
.incbin "baserom.gba", 0x621C08, 0x200
sPikachuSprites64:
ax_sprite sPikachuGfx64, 0x200
ax_sprite_terminator
sPikachuGfx65:
.incbin "baserom.gba", 0x621E18, 0x200
sPikachuSprites65:
ax_sprite sPikachuGfx65, 0x200
ax_sprite_terminator
sPikachuGfx66:
.incbin "baserom.gba", 0x622028, 0x200
sPikachuSprites66:
ax_sprite sPikachuGfx66, 0x200
ax_sprite_terminator
sPikachuGfx67:
.incbin "baserom.gba", 0x622238, 0x200
sPikachuSprites67:
ax_sprite sPikachuGfx67, 0x200
ax_sprite_terminator
sPikachuGfx68:
.incbin "baserom.gba", 0x622448, 0x200
sPikachuSprites68:
ax_sprite sPikachuGfx68, 0x200
ax_sprite_terminator
sPikachuGfx69:
.incbin "baserom.gba", 0x622658, 0x200
sPikachuSprites69:
ax_sprite sPikachuGfx69, 0x200
ax_sprite_terminator
sPikachuGfx70:
.incbin "baserom.gba", 0x622868, 0x200
sPikachuSprites70:
ax_sprite sPikachuGfx70, 0x200
ax_sprite_terminator
sPikachuGfx71:
.incbin "baserom.gba", 0x622A78, 0x200
sPikachuSprites71:
ax_sprite sPikachuGfx71, 0x200
ax_sprite_terminator
sPikachuGfx72:
.incbin "baserom.gba", 0x622C88, 0x200
sPikachuSprites72:
ax_sprite sPikachuGfx72, 0x200
ax_sprite_terminator
sPikachuGfx73:
.incbin "baserom.gba", 0x622E98, 0x200
sPikachuSprites73:
ax_sprite sPikachuGfx73, 0x200
ax_sprite_terminator
sPikachuGfx74:
.incbin "baserom.gba", 0x6230A8, 0x200
sPikachuSprites74:
ax_sprite sPikachuGfx74, 0x200
ax_sprite_terminator
sPikachuGfx75:
.incbin "baserom.gba", 0x6232B8, 0x200
sPikachuSprites75:
ax_sprite sPikachuGfx75, 0x200
ax_sprite_terminator
sPikachuGfx76:
.incbin "baserom.gba", 0x6234C8, 0x200
sPikachuSprites76:
ax_sprite sPikachuGfx76, 0x200
ax_sprite_terminator
sPikachuGfx77:
.incbin "baserom.gba", 0x6236D8, 0x200
sPikachuSprites77:
ax_sprite sPikachuGfx77, 0x200
ax_sprite_terminator
sPikachuGfx78:
.incbin "baserom.gba", 0x6238E8, 0x200
sPikachuSprites78:
ax_sprite sPikachuGfx78, 0x200
ax_sprite_terminator
sPikachuGfx79:
.incbin "baserom.gba", 0x623AF8, 0x200
sPikachuSprites79:
ax_sprite sPikachuGfx79, 0x200
ax_sprite_terminator
sPikachuGfx80:
.incbin "baserom.gba", 0x623D08, 0x200
sPikachuSprites80:
ax_sprite sPikachuGfx80, 0x200
ax_sprite_terminator
sPikachuGfx81:
.incbin "baserom.gba", 0x623F18, 0x200
sPikachuSprites81:
ax_sprite sPikachuGfx81, 0x200
ax_sprite_terminator
sPikachuGfx82:
.incbin "baserom.gba", 0x624128, 0x200
sPikachuSprites82:
ax_sprite sPikachuGfx82, 0x200
ax_sprite_terminator
sPikachuGfx83:
.incbin "baserom.gba", 0x624338, 0x200
sPikachuSprites83:
ax_sprite sPikachuGfx83, 0x200
ax_sprite_terminator
sPikachuGfx84:
.incbin "baserom.gba", 0x624548, 0x200
sPikachuSprites84:
ax_sprite sPikachuGfx84, 0x200
ax_sprite_terminator
sPikachuGfx85:
.incbin "baserom.gba", 0x624758, 0x200
sPikachuSprites85:
ax_sprite sPikachuGfx85, 0x200
ax_sprite_terminator
sPikachuGfx86:
.incbin "baserom.gba", 0x624968, 0x200
sPikachuSprites86:
ax_sprite sPikachuGfx86, 0x200
ax_sprite_terminator
sPikachuGfx87:
.incbin "baserom.gba", 0x624B78, 0x200
sPikachuSprites87:
ax_sprite sPikachuGfx87, 0x200
ax_sprite_terminator
sPikachuGfx88:
.incbin "baserom.gba", 0x624D88, 0x200
sPikachuSprites88:
ax_sprite sPikachuGfx88, 0x200
ax_sprite_terminator
sPikachuGfx89:
.incbin "baserom.gba", 0x624F98, 0x200
sPikachuSprites89:
ax_sprite sPikachuGfx89, 0x200
ax_sprite_terminator
sPikachuGfx90:
.incbin "baserom.gba", 0x6251A8, 0x200
sPikachuSprites90:
ax_sprite sPikachuGfx90, 0x200
ax_sprite_terminator
sPikachuGfx91:
.incbin "baserom.gba", 0x6253B8, 0x200
sPikachuSprites91:
ax_sprite sPikachuGfx91, 0x200
ax_sprite_terminator
sPikachuGfx92:
.incbin "baserom.gba", 0x6255C8, 0x200
sPikachuSprites92:
ax_sprite sPikachuGfx92, 0x200
ax_sprite_terminator
sAxPosesPikachu:
.4byte sPikachuPose1
.4byte sPikachuPose2
.4byte sPikachuPose3
.4byte sPikachuPose4
.4byte sPikachuPose5
.4byte sPikachuPose6
.4byte sPikachuPose7
.4byte sPikachuPose8
.4byte sPikachuPose9
.4byte sPikachuPose10
.4byte sPikachuPose11
.4byte sPikachuPose12
.4byte sPikachuPose13
.4byte sPikachuPose14
.4byte sPikachuPose15
.4byte sPikachuPose16
.4byte sPikachuPose17
.4byte sPikachuPose18
.4byte sPikachuPose19
.4byte sPikachuPose20
.4byte sPikachuPose21
.4byte sPikachuPose22
.4byte sPikachuPose23
.4byte sPikachuPose24
.4byte sPikachuPose25
.4byte sPikachuPose26
.4byte sPikachuPose27
.4byte sPikachuPose28
.4byte sPikachuPose29
.4byte sPikachuPose30
.4byte sPikachuPose31
.4byte sPikachuPose32
.4byte sPikachuPose33
.4byte sPikachuPose34
.4byte sPikachuPose35
.4byte sPikachuPose36
.4byte sPikachuPose37
.4byte sPikachuPose38
.4byte sPikachuPose39
.4byte sPikachuPose40
.4byte sPikachuPose41
.4byte sPikachuPose42
.4byte sPikachuPose43
.4byte sPikachuPose44
.4byte sPikachuPose45
.4byte sPikachuPose46
.4byte sPikachuPose47
.4byte sPikachuPose48
.4byte sPikachuPose49
.4byte sPikachuPose50
.4byte sPikachuPose51
.4byte sPikachuPose52
.4byte sPikachuPose53
.4byte sPikachuPose54
.4byte sPikachuPose55
.4byte sPikachuPose56
.4byte sPikachuPose57
.4byte sPikachuPose58
.4byte sPikachuPose59
.4byte sPikachuPose60
.4byte sPikachuPose61
.4byte sPikachuPose62
.4byte sPikachuPose63
.4byte sPikachuPose64
.4byte sPikachuPose65
.4byte sPikachuPose66
.4byte sPikachuPose67
.4byte sPikachuPose68
.4byte sPikachuPose69
.4byte sPikachuPose70
.4byte sPikachuPose71
.4byte sPikachuPose72
.4byte sPikachuPose73
.4byte sPikachuPose74
.4byte sPikachuPose75
.4byte sPikachuPose76
.4byte sPikachuPose77
.4byte sPikachuPose78
.4byte sPikachuPose79
.4byte sPikachuPose80
.4byte sPikachuPose81
.4byte sPikachuPose82
.4byte sPikachuPose83
.4byte sPikachuPose84
.4byte sPikachuPose85
.4byte sPikachuPose86
.4byte sPikachuPose87
.4byte sPikachuPose88
.4byte sPikachuPose89
.4byte sPikachuPose90
.4byte sPikachuPose91
.4byte sPikachuPose92
.4byte sPikachuPose93
.4byte sPikachuPose94
.4byte sPikachuPose95
.4byte sPikachuPose96
.4byte sPikachuPose97
.4byte sPikachuPose98
.4byte sPikachuPose99
.4byte sPikachuPose100
.4byte sPikachuPose101
.4byte sPikachuPose102
.4byte sPikachuPose103
.4byte sPikachuPose104
.4byte sPikachuPose105
.4byte sPikachuPose106
.4byte sPikachuPose107
.4byte sPikachuPose108
.4byte sPikachuPose109
.4byte sPikachuPose110
.4byte sPikachuPose111
.4byte sPikachuPose112
.4byte sPikachuPose113
.4byte sPikachuPose114
.4byte sPikachuPose115
.4byte sPikachuPose116
.4byte sPikachuPose117
.4byte sPikachuPose118
.4byte sPikachuPose119
.4byte sPikachuPose120
.4byte sPikachuPose121
.4byte sPikachuPose122
.4byte sPikachuPose123
.4byte sPikachuPose124
.4byte sPikachuPose125
.4byte sPikachuPose126
.4byte sPikachuPose127
.4byte sPikachuPose128
.4byte sPikachuPose129
.4byte sPikachuPose130
.4byte sPikachuPose131
.4byte sPikachuPose132
.4byte sPikachuPose133
.4byte sPikachuPose134
.4byte sPikachuPose135
.4byte sPikachuPose136
.4byte sPikachuPose137
.4byte sPikachuPose138
.4byte sPikachuPose139
.4byte sPikachuPose140
.4byte sPikachuPose141
.4byte sPikachuPose142
.4byte sPikachuPose143
.4byte sPikachuPose144
.4byte sPikachuPose145
.4byte sPikachuPose146
.4byte sPikachuPose147
.4byte sPikachuPose148
.4byte sPikachuPose149
.4byte sPikachuPose150
.4byte sPikachuPose151
.4byte sPikachuPose152
.4byte sPikachuPose153
.4byte sPikachuPose154
.4byte sPikachuPose155
.4byte sPikachuPose156
.4byte sPikachuPose157
.4byte sPikachuPose158
.4byte sPikachuPose159
.4byte sPikachuPose160
.4byte sPikachuPose161
.4byte sPikachuPose162
.4byte sPikachuPose163
.4byte sPikachuPose164
.4byte sPikachuPose165
.4byte sPikachuPose166
.4byte sPikachuPose167
.4byte sPikachuPose168
.4byte sPikachuPose169
.4byte sPikachuPose170
.4byte sPikachuPose171
.4byte sPikachuPose172
.4byte sPikachuPose173
.4byte sPikachuPose174
.4byte sPikachuPose175
.4byte sPikachuPose176
.4byte sPikachuPose177
.4byte sPikachuPose178
.4byte sPikachuPose179
.4byte sPikachuPose180
.4byte sPikachuPose181
.4byte sPikachuPose182
.4byte sPikachuPose183
.4byte sPikachuPose184
.4byte sPikachuPose185
.4byte sPikachuPose186
.4byte sPikachuPose187
.4byte sPikachuPose188
.4byte sPikachuPose189
.4byte sPikachuPose190
.4byte sPikachuPose191
.4byte sPikachuPose192
.4byte sPikachuPose193
.4byte sPikachuPose194
.4byte sPikachuPose195
.4byte sPikachuPose196
.4byte sPikachuPose197
.4byte sPikachuPose198
.4byte sPikachuPose199
.4byte sPikachuPose200
.4byte sPikachuPose201
.4byte sPikachuPose202
.4byte sPikachuPose203
.4byte sPikachuPose204
.4byte sPikachuPose205
.4byte sPikachuPose206
.4byte sPikachuPose207
.4byte sPikachuPose208
.4byte sPikachuPose209
.4byte sPikachuPose210
.4byte sPikachuPose211
.4byte sPikachuPose212
.4byte sPikachuPose213
.4byte sPikachuPose214
.4byte sPikachuPose215
.4byte sPikachuPose216
.4byte sPikachuPose217
.4byte sPikachuPose218
.4byte sPikachuPose219
.4byte sPikachuPose220
.4byte sPikachuPose221
.4byte sPikachuPose222
.4byte sPikachuPose223
.4byte sPikachuPose224
.4byte sPikachuPose225
.4byte sPikachuPose226
.4byte sPikachuPose227
.4byte sPikachuPose228
.4byte sPikachuPose229
.4byte sPikachuPose230
.4byte sPikachuPose231
.4byte sPikachuPose232
.4byte sPikachuPose233
.4byte sPikachuPose234
.4byte sPikachuPose235
.4byte sPikachuPose236
.4byte sPikachuPose237
.4byte sPikachuPose238
.4byte sPikachuPose239
.4byte sPikachuPose240
.4byte sPikachuPose241
.4byte sPikachuPose242
.4byte sPikachuPose243
.4byte sPikachuPose244
.4byte sPikachuPose245
.4byte sPikachuPose246
.4byte sPikachuPose247
.4byte sPikachuPose248
.4byte sPikachuPose249
.4byte sPikachuPose250
.4byte sPikachuPose251
.4byte sPikachuPose252
.4byte sPikachuPose253
.4byte sPikachuPose254
.4byte sPikachuPose255
.4byte sPikachuPose256
.4byte sPikachuPose257
.4byte sPikachuPose258
.4byte sPikachuPose259
.4byte sPikachuPose260
.4byte sPikachuPose261
.4byte sPikachuPose262
.4byte sPikachuPose263
.4byte sPikachuPose264
.4byte sPikachuPose265
.4byte sPikachuPose266
.4byte sPikachuPose267
.4byte sPikachuPose268
.4byte sPikachuPose269
.4byte sPikachuPose270
.4byte sPikachuPose271
.4byte sPikachuPose272
.4byte sPikachuPose273
.4byte sPikachuPose274
.4byte sPikachuPose275
.4byte sPikachuPose276
.4byte sPikachuPose277
.4byte sPikachuPose278
.4byte sPikachuPose279
.4byte sPikachuPose280
.4byte sPikachuPose281
.4byte sPikachuPose282
.4byte sPikachuPose283
.4byte sPikachuPose284
.4byte sPikachuPose285
.4byte sPikachuPose286
.4byte sPikachuPose287
.4byte sPikachuPose288
.4byte sPikachuPose289
.4byte sPikachuPose290
.4byte sPikachuPose291
.4byte sPikachuPose292
.4byte sPikachuPose293
.4byte sPikachuPose294
.4byte sPikachuPose295
.4byte sPikachuPose296
.4byte sPikachuPose297
.4byte sPikachuPose298
.4byte sPikachuPose299
sAxPositionsPikachu:
.2byte   -1,  -10, 	  -7,   -4, 	   5,   -4, 	  -1,   -7
.2byte   -1,   -9, 	  -5,   -5, 	   7,   -6, 	  -1,   -6
.2byte   -1,   -9, 	  -9,   -7, 	   3,   -5, 	  -1,   -6
.2byte    3,  -10, 	   6,   -6, 	  -3,   -4, 	   0,   -6
.2byte    3,   -9, 	   5,   -6, 	  -7,   -4, 	  -1,   -5
.2byte    3,   -9, 	   7,   -8, 	  -1,   -4, 	  -1,   -7
.2byte    5,   -9, 	   2,   -6, 	   1,   -4, 	  -1,   -7
.2byte    5,   -8, 	   6,   -6, 	  -2,   -3, 	   0,   -6
.2byte    5,   -8, 	  -1,   -6, 	   5,   -3, 	  -1,   -8
.2byte    4,  -13, 	  -4,   -9, 	   6,   -4, 	  -1,   -6
.2byte    3,  -12, 	  -2,   -9, 	   4,   -2, 	   0,   -6
.2byte    3,  -13, 	  -7,  -10, 	   8,   -6, 	  -1,   -6
.2byte   -2,  -13, 	   4,   -6, 	  -7,   -7, 	  -2,   -7
.2byte   -1,  -12, 	   4,   -8, 	  -9,   -6, 	  -1,   -6
.2byte   -2,  -13, 	   8,   -6, 	  -8,   -9, 	  -1,   -6
.2byte   -5,  -13, 	   3,   -9, 	  -7,   -4, 	   0,   -6
.2byte   -4,  -12, 	   1,   -9, 	  -5,   -2, 	  -1,   -6
.2byte   -4,  -13, 	   6,  -10, 	  -9,   -6, 	   0,   -6
.2byte   -6,   -9, 	  -3,   -6, 	  -2,   -4, 	   0,   -7
.2byte   -6,   -8, 	  -7,   -6, 	   1,   -3, 	  -1,   -6
.2byte   -6,   -8, 	   0,   -6, 	  -6,   -3, 	   0,   -8
.2byte   -4,  -10, 	  -7,   -6, 	   2,   -4, 	  -1,   -6
.2byte   -4,   -9, 	  -6,   -6, 	   6,   -4, 	   0,   -5
.2byte   -4,   -9, 	  -8,   -8, 	   0,   -4, 	   0,   -7
.2byte   -1,  -10, 	  -7,   -4, 	   5,   -4, 	  -1,   -7
.2byte   -1,  -13, 	  -5,   -9, 	   7,  -10, 	  -1,  -10
.2byte   -1,   -9, 	  -9,   -7, 	   3,   -5, 	  -1,   -6
.2byte   -1,  -13, 	  -8,  -11, 	   6,  -11, 	  -1,  -11
.2byte    3,  -10, 	   6,   -6, 	  -3,   -4, 	   0,   -6
.2byte    3,   -9, 	   5,   -6, 	  -7,   -4, 	  -1,   -5
.2byte    3,   -9, 	   7,   -8, 	  -1,   -4, 	  -1,   -7
.2byte    6,  -10, 	  11,  -11, 	   0,   -7, 	  -1,   -9
.2byte    5,   -9, 	   2,   -6, 	   1,   -4, 	  -1,   -7
.2byte    5,   -8, 	   6,   -6, 	  -2,   -3, 	   0,   -6
.2byte    5,   -8, 	  -1,   -6, 	   5,   -3, 	  -1,   -8
.2byte    8,   -9, 	   5,  -11, 	   5,   -6, 	   0,   -9
.2byte    4,  -13, 	  -4,   -9, 	   6,   -4, 	  -1,   -6
.2byte    3,  -12, 	  -2,   -9, 	   4,   -2, 	   0,   -6
.2byte    3,  -13, 	  -7,  -10, 	   8,   -6, 	  -1,   -6
.2byte    7,  -15, 	   0,  -15, 	   8,  -11, 	  -1,  -10
.2byte   -2,  -13, 	   4,   -6, 	  -7,   -7, 	  -2,   -7
.2byte   -1,  -12, 	   4,   -8, 	  -9,   -6, 	  -1,   -6
.2byte   -2,  -13, 	   8,   -6, 	  -8,   -9, 	  -1,   -6
.2byte   -1,  -17, 	   7,  -14, 	  -9,  -14, 	  -1,  -11
.2byte   -5,  -13, 	   3,   -9, 	  -7,   -4, 	   0,   -6
.2byte   -4,  -12, 	   1,   -9, 	  -5,   -2, 	  -1,   -6
.2byte   -4,  -13, 	   6,  -10, 	  -9,   -6, 	   0,   -6
.2byte   -8,  -15, 	  -1,  -15, 	  -9,  -11, 	   0,  -10
.2byte   -6,   -9, 	  -3,   -6, 	  -2,   -4, 	   0,   -7
.2byte   -6,   -8, 	  -7,   -6, 	   1,   -3, 	  -1,   -6
.2byte   -6,   -8, 	   0,   -6, 	  -6,   -3, 	   0,   -8
.2byte   -9,   -9, 	  -6,  -11, 	  -6,   -6, 	  -1,   -9
.2byte   -4,  -10, 	  -7,   -6, 	   2,   -4, 	  -1,   -6
.2byte   -4,   -9, 	  -6,   -6, 	   6,   -4, 	   0,   -5
.2byte   -4,   -9, 	  -8,   -8, 	   0,   -4, 	   0,   -7
.2byte   -7,  -10, 	 -12,  -11, 	  -1,   -7, 	   0,   -9
.2byte   -1,  -10, 	  -7,   -4, 	   5,   -4, 	  -1,   -7
.2byte   -1,  -13, 	  -5,   -9, 	   7,  -10, 	  -1,  -10
.2byte   -1,   -9, 	  -9,   -7, 	   3,   -5, 	  -1,   -6
.2byte   -1,  -13, 	  -8,  -11, 	   6,  -11, 	  -1,  -11
.2byte    3,  -10, 	   6,   -6, 	  -3,   -4, 	   0,   -6
.2byte    3,   -9, 	   5,   -6, 	  -7,   -4, 	  -1,   -5
.2byte    3,   -9, 	   7,   -8, 	  -1,   -4, 	  -1,   -7
.2byte    6,  -10, 	  11,  -11, 	   0,   -7, 	  -1,   -9
.2byte    5,   -9, 	   2,   -6, 	   1,   -4, 	  -1,   -7
.2byte    5,   -8, 	   6,   -6, 	  -2,   -3, 	   0,   -6
.2byte    5,   -8, 	  -1,   -6, 	   5,   -3, 	  -1,   -8
.2byte    8,   -9, 	   5,  -11, 	   5,   -6, 	   0,   -9
.2byte    4,  -13, 	  -4,   -9, 	   6,   -4, 	  -1,   -6
.2byte    3,  -12, 	  -2,   -9, 	   4,   -2, 	   0,   -6
.2byte    3,  -13, 	  -7,  -10, 	   8,   -6, 	  -1,   -6
.2byte    7,  -15, 	   0,  -15, 	   8,  -11, 	  -1,  -10
.2byte   -2,  -13, 	   4,   -6, 	  -7,   -7, 	  -2,   -7
.2byte   -1,  -12, 	   4,   -8, 	  -9,   -6, 	  -1,   -6
.2byte   -2,  -13, 	   8,   -6, 	  -8,   -9, 	  -1,   -6
.2byte   -1,  -17, 	   7,  -14, 	  -9,  -14, 	  -1,  -11
.2byte   -5,  -13, 	   3,   -9, 	  -7,   -4, 	   0,   -6
.2byte   -4,  -12, 	   1,   -9, 	  -5,   -2, 	  -1,   -6
.2byte   -4,  -13, 	   6,  -10, 	  -9,   -6, 	   0,   -6
.2byte   -8,  -15, 	  -1,  -15, 	  -9,  -11, 	   0,  -10
.2byte   -6,   -9, 	  -3,   -6, 	  -2,   -4, 	   0,   -7
.2byte   -6,   -8, 	  -7,   -6, 	   1,   -3, 	  -1,   -6
.2byte   -6,   -8, 	   0,   -6, 	  -6,   -3, 	   0,   -8
.2byte   -9,   -9, 	  -6,  -11, 	  -6,   -6, 	  -1,   -9
.2byte   -4,  -10, 	  -7,   -6, 	   2,   -4, 	  -1,   -6
.2byte   -4,   -9, 	  -6,   -6, 	   6,   -4, 	   0,   -5
.2byte   -4,   -9, 	  -8,   -8, 	   0,   -4, 	   0,   -7
.2byte   -7,  -10, 	 -12,  -11, 	  -1,   -7, 	   0,   -9
.2byte   -1,  -10, 	  -7,   -4, 	   5,   -4, 	  -1,   -7
.2byte   -1,  -12, 	  -8,   -7, 	   6,   -7, 	  -1,   -8
.2byte    3,  -10, 	   6,   -6, 	  -3,   -4, 	   0,   -6
.2byte    4,  -11, 	   5,   -9, 	  -6,   -7, 	  -1,   -7
.2byte    5,   -9, 	   2,   -6, 	   1,   -4, 	  -1,   -7
.2byte    7,  -10, 	  -1,  -10, 	  -2,   -7, 	   1,   -8
.2byte    4,  -13, 	  -4,   -9, 	   6,   -4, 	  -1,   -6
.2byte    5,  -14, 	  -6,  -11, 	   4,   -5, 	   0,   -9
.2byte   -2,  -13, 	   4,   -6, 	  -7,   -7, 	  -2,   -7
.2byte   -2,  -15, 	   7,   -7, 	  -8,   -6, 	  -1,   -7
.2byte   -5,  -13, 	   3,   -9, 	  -7,   -4, 	   0,   -6
.2byte   -6,  -14, 	   5,  -11, 	  -5,   -5, 	  -1,   -9
.2byte   -6,   -9, 	  -3,   -6, 	  -2,   -4, 	   0,   -7
.2byte   -8,  -10, 	   0,  -10, 	   1,   -7, 	  -2,   -8
.2byte   -4,  -10, 	  -7,   -6, 	   2,   -4, 	  -1,   -6
.2byte   -5,  -11, 	  -6,   -9, 	   5,   -7, 	   0,   -7
.2byte   -1,  -10, 	  -7,   -4, 	   5,   -4, 	  -1,   -7
.2byte   -1,  -12, 	  -8,   -7, 	   6,   -7, 	  -1,   -8
.2byte   -1,   -8, 	  -4,   -6, 	   2,   -6, 	  -1,   -9
.2byte   -1,   -8, 	  -4,   -6, 	   2,   -6, 	  -1,   -9
.2byte   -1,   -8, 	  -4,   -6, 	   2,   -6, 	  -1,   -9
.2byte   -1,   -8, 	  -4,   -6, 	   2,   -6, 	  -1,   -9
.2byte    3,  -10, 	   6,   -6, 	  -3,   -4, 	   0,   -6
.2byte    4,  -11, 	   5,   -9, 	  -6,   -7, 	  -1,   -7
.2byte    4,   -9, 	   7,   -7, 	   0,   -6, 	   0,   -7
.2byte    4,   -9, 	   7,   -7, 	   0,   -6, 	   0,   -7
.2byte    4,   -9, 	   7,   -7, 	   0,   -6, 	   0,   -7
.2byte    4,   -9, 	   7,   -7, 	   0,   -6, 	   0,   -7
.2byte    5,   -9, 	   2,   -6, 	   1,   -4, 	  -1,   -7
.2byte    7,  -10, 	  -1,  -10, 	  -2,   -7, 	   1,   -8
.2byte    6,   -7, 	   3,   -8, 	   2,   -5, 	   0,   -7
.2byte    6,   -7, 	   3,   -8, 	   2,   -5, 	   0,   -7
.2byte    6,   -7, 	   3,   -8, 	   2,   -5, 	   0,   -7
.2byte    6,   -7, 	   3,   -8, 	   2,   -5, 	   0,   -7
.2byte    4,  -13, 	  -4,   -9, 	   6,   -4, 	  -1,   -6
.2byte    5,  -14, 	  -6,  -11, 	   4,   -5, 	   0,   -9
.2byte    3,  -12, 	   0,  -11, 	   6,   -7, 	  -1,   -7
.2byte    3,  -12, 	   0,  -11, 	   6,   -7, 	  -1,   -7
.2byte    3,  -12, 	   0,  -11, 	   6,   -7, 	  -1,   -7
.2byte    3,  -12, 	   0,  -11, 	   6,   -7, 	  -1,   -7
.2byte   -2,  -13, 	   4,   -6, 	  -7,   -7, 	  -2,   -7
.2byte   -2,  -15, 	   7,   -7, 	  -8,   -6, 	  -1,   -7
.2byte   -2,  -13, 	   2,   -9, 	  -5,   -9, 	  -1,   -7
.2byte   -2,  -13, 	   2,   -9, 	  -5,   -9, 	  -1,   -7
.2byte   -2,  -13, 	   2,   -9, 	  -5,   -9, 	  -1,   -7
.2byte   -2,  -13, 	   2,   -9, 	  -5,   -9, 	  -1,   -7
.2byte   -5,  -13, 	   3,   -9, 	  -7,   -4, 	   0,   -6
.2byte   -6,  -14, 	   5,  -11, 	  -5,   -5, 	  -1,   -9
.2byte   -4,  -12, 	  -1,  -11, 	  -7,   -7, 	   0,   -7
.2byte   -4,  -12, 	  -1,  -11, 	  -7,   -7, 	   0,   -7
.2byte   -4,  -12, 	  -1,  -11, 	  -7,   -7, 	   0,   -7
.2byte   -4,  -12, 	  -1,  -11, 	  -7,   -7, 	   0,   -7
.2byte   -6,   -9, 	  -3,   -6, 	  -2,   -4, 	   0,   -7
.2byte   -8,  -10, 	   0,  -10, 	   1,   -7, 	  -2,   -8
.2byte   -7,   -7, 	  -4,   -8, 	  -3,   -5, 	  -1,   -7
.2byte   -7,   -7, 	  -4,   -8, 	  -3,   -5, 	  -1,   -7
.2byte   -7,   -7, 	  -4,   -8, 	  -3,   -5, 	  -1,   -7
.2byte   -7,   -7, 	  -4,   -8, 	  -3,   -5, 	  -1,   -7
.2byte   -4,  -10, 	  -7,   -6, 	   2,   -4, 	  -1,   -6
.2byte   -5,  -11, 	  -6,   -9, 	   5,   -7, 	   0,   -7
.2byte   -5,   -9, 	  -8,   -7, 	  -1,   -6, 	  -1,   -7
.2byte   -5,   -9, 	  -8,   -7, 	  -1,   -6, 	  -1,   -7
.2byte   -5,   -9, 	  -8,   -7, 	  -1,   -6, 	  -1,   -7
.2byte   -5,   -9, 	  -8,   -7, 	  -1,   -6, 	  -1,   -7
.2byte   -3,   -7, 	  -5,   -5, 	   4,   -2, 	   1,   -6
.2byte   -2,   -8, 	  -5,   -5, 	   3,   -3, 	   3,   -6
.2byte   -1,  -11, 	  -9,  -10, 	   7,  -10, 	  -1,   -7
.2byte    2,  -12, 	   5,  -12, 	  -9,  -10, 	  -1,   -8
.2byte    4,  -10, 	  -3,  -12, 	  -4,   -9, 	  -1,   -7
.2byte    2,  -13, 	  -5,  -12, 	   6,   -8, 	  -2,   -6
.2byte   -2,  -13, 	   8,   -6, 	 -11,   -6, 	  -1,   -7
.2byte   -3,  -13, 	   4,  -12, 	  -7,   -8, 	   1,   -6
.2byte   -5,  -10, 	   2,  -12, 	   3,   -9, 	   0,   -7
.2byte   -3,  -12, 	  -6,  -12, 	   8,  -10, 	   0,   -8
.2byte   -1,  -10, 	  -7,   -4, 	   5,   -4, 	  -1,   -7
.2byte   -4,  -10, 	  -7,   -6, 	   2,   -4, 	  -1,   -6
.2byte   -6,   -9, 	  -3,   -6, 	  -2,   -4, 	   0,   -7
.2byte   -5,  -13, 	   3,   -9, 	  -7,   -4, 	   0,   -6
.2byte   -2,  -13, 	   4,   -6, 	  -7,   -7, 	  -2,   -7
.2byte    4,  -13, 	  -4,   -9, 	   6,   -4, 	  -1,   -6
.2byte    5,   -9, 	   2,   -6, 	   1,   -4, 	  -1,   -7
.2byte    3,  -10, 	   6,   -6, 	  -3,   -4, 	   0,   -6
.2byte   -1,  -13, 	  -8,  -11, 	   6,  -11, 	  -1,  -11
.2byte   -4,  -10, 	  -9,  -11, 	   2,   -7, 	   3,   -9
.2byte   -8,   -9, 	  -5,  -11, 	  -5,   -6, 	   0,   -9
.2byte   -7,  -14, 	   0,  -14, 	  -8,  -10, 	   1,   -9
.2byte   -1,  -16, 	   7,  -13, 	  -9,  -13, 	  -1,  -10
.2byte    6,  -14, 	  -1,  -14, 	   7,  -10, 	  -2,   -9
.2byte    7,   -9, 	   4,  -11, 	   4,   -6, 	  -1,   -9
.2byte    3,  -10, 	   8,  -11, 	  -3,   -7, 	  -4,   -9
.2byte   -1,   -8, 	  -4,   -6, 	   2,   -6, 	  -1,   -9
.2byte   -5,   -9, 	  -8,   -7, 	  -1,   -6, 	  -1,   -7
.2byte   -7,   -7, 	  -4,   -8, 	  -3,   -5, 	  -1,   -7
.2byte   -4,  -12, 	  -1,  -11, 	  -7,   -7, 	   0,   -7
.2byte   -2,  -13, 	   2,   -9, 	  -5,   -9, 	  -1,   -7
.2byte    3,  -12, 	   0,  -11, 	   6,   -7, 	  -1,   -7
.2byte    6,   -7, 	   3,   -8, 	   2,   -5, 	   0,   -7
.2byte    4,   -9, 	   7,   -7, 	   0,   -6, 	   0,   -7
.2byte   -1,  -12, 	  -8,   -7, 	   6,   -7, 	  -1,   -8
.2byte    4,  -11, 	   5,   -9, 	  -6,   -7, 	  -1,   -7
.2byte    7,  -10, 	  -1,  -10, 	  -2,   -7, 	   1,   -8
.2byte    5,  -14, 	  -6,  -11, 	   4,   -5, 	   0,   -9
.2byte   -2,  -15, 	   7,   -7, 	  -8,   -6, 	  -1,   -7
.2byte   -6,  -14, 	   5,  -11, 	  -5,   -5, 	  -1,   -9
.2byte   -8,  -10, 	   0,  -10, 	   1,   -7, 	  -2,   -8
.2byte   -5,  -11, 	  -6,   -9, 	   5,   -7, 	   0,   -7
.2byte   -1,  -10, 	  -7,   -4, 	   5,   -4, 	  -1,   -7
.2byte   -1,  -13, 	  -5,   -9, 	   7,  -10, 	  -1,  -10
.2byte   -1,   -9, 	  -9,   -7, 	   3,   -5, 	  -1,   -6
.2byte   -1,  -13, 	  -8,  -11, 	   6,  -11, 	  -1,  -11
.2byte    3,  -10, 	   6,   -6, 	  -3,   -4, 	   0,   -6
.2byte    3,   -9, 	   5,   -6, 	  -7,   -4, 	  -1,   -5
.2byte    3,   -9, 	   7,   -8, 	  -1,   -4, 	  -1,   -7
.2byte    5,  -10, 	  10,  -11, 	  -1,   -7, 	  -2,   -9
.2byte    5,   -9, 	   2,   -6, 	   1,   -4, 	  -1,   -7
.2byte    5,   -8, 	   6,   -6, 	  -2,   -3, 	   0,   -6
.2byte    5,   -8, 	  -1,   -6, 	   5,   -3, 	  -1,   -8
.2byte    7,   -9, 	   4,  -11, 	   4,   -6, 	  -1,   -9
.2byte    4,  -13, 	  -4,   -9, 	   6,   -4, 	  -1,   -6
.2byte    3,  -12, 	  -2,   -9, 	   4,   -2, 	   0,   -6
.2byte    3,  -13, 	  -7,  -10, 	   8,   -6, 	  -1,   -6
.2byte    7,  -15, 	   0,  -15, 	   8,  -11, 	  -1,  -10
.2byte   -2,  -13, 	   4,   -6, 	  -7,   -7, 	  -2,   -7
.2byte   -1,  -12, 	   4,   -8, 	  -9,   -6, 	  -1,   -6
.2byte   -2,  -13, 	   8,   -6, 	  -8,   -9, 	  -1,   -6
.2byte   -1,  -17, 	   7,  -14, 	  -9,  -14, 	  -1,  -11
.2byte   -5,  -13, 	   3,   -9, 	  -7,   -4, 	   0,   -6
.2byte   -4,  -12, 	   1,   -9, 	  -5,   -2, 	  -1,   -6
.2byte   -4,  -13, 	   6,  -10, 	  -9,   -6, 	   0,   -6
.2byte   -8,  -15, 	  -1,  -15, 	  -9,  -11, 	   0,  -10
.2byte   -6,   -9, 	  -3,   -6, 	  -2,   -4, 	   0,   -7
.2byte   -6,   -8, 	  -7,   -6, 	   1,   -3, 	  -1,   -6
.2byte   -6,   -8, 	   0,   -6, 	  -6,   -3, 	   0,   -8
.2byte   -8,   -9, 	  -5,  -11, 	  -5,   -6, 	   0,   -9
.2byte   -4,  -10, 	  -7,   -6, 	   2,   -4, 	  -1,   -6
.2byte   -4,   -9, 	  -6,   -6, 	   6,   -4, 	   0,   -5
.2byte   -4,   -9, 	  -8,   -8, 	   0,   -4, 	   0,   -7
.2byte   -6,  -10, 	 -11,  -11, 	   0,   -7, 	   1,   -9
.2byte   -1,  -12, 	  -8,   -7, 	   6,   -7, 	  -1,   -8
.2byte   -5,  -11, 	  -6,   -9, 	   5,   -7, 	   0,   -7
.2byte   -8,  -10, 	   0,  -10, 	   1,   -7, 	  -2,   -8
.2byte   -6,  -14, 	   5,  -11, 	  -5,   -5, 	  -1,   -9
.2byte   -2,  -15, 	   7,   -7, 	  -8,   -6, 	  -1,   -7
.2byte    5,  -14, 	  -6,  -11, 	   4,   -5, 	   0,   -9
.2byte    7,  -10, 	  -1,  -10, 	  -2,   -7, 	   1,   -8
.2byte    4,  -11, 	   5,   -9, 	  -6,   -7, 	  -1,   -7
.2byte   -1,  -10, 	  -7,   -4, 	   5,   -4, 	  -1,   -7
.2byte   -4,  -10, 	  -7,   -6, 	   2,   -4, 	  -1,   -6
.2byte   -6,   -9, 	  -3,   -6, 	  -2,   -4, 	   0,   -7
.2byte   -5,  -13, 	   3,   -9, 	  -7,   -4, 	   0,   -6
.2byte   -2,  -13, 	   4,   -6, 	  -7,   -7, 	  -2,   -7
.2byte    4,  -13, 	  -4,   -9, 	   6,   -4, 	  -1,   -6
.2byte    5,   -9, 	   2,   -6, 	   1,   -4, 	  -1,   -7
.2byte    3,  -10, 	   6,   -6, 	  -3,   -4, 	   0,   -6
.2byte   -1,   -9, 	  -3,    1, 	   0,   -7, 	  -1,   -3
.2byte   -2,   -9, 	  -3,    1, 	   0,   -7, 	  -1,   -3
.2byte    0,   -9, 	   2,    1, 	  -1,   -7, 	   0,   -3
.2byte    1,   -9, 	   2,    1, 	  -1,   -7, 	   0,   -3
.2byte   -1,   -9, 	  -3,    1, 	   0,   -7, 	  -1,   -3
.2byte    2,   -7, 	   1,   -5, 	   5,   -8, 	  -1,   -5
.2byte    7,   -6, 	   3,   -3, 	   5,   -4, 	   0,   -7
.2byte    8,   -7, 	   4,   -3, 	   4,   -4, 	   1,   -8
.2byte    5,   -9, 	   2,   -6, 	   1,   -4, 	  -1,   -7
.2byte   -2,  -13, 	   4,   -6, 	  -7,   -7, 	  -2,   -7
.2byte   -1,  -11, 	   7,   -7, 	  -9,   -7, 	  -1,  -10
.2byte   -1,   -9, 	   8,  -10, 	 -11,  -10, 	  -1,  -10
.2byte   -1,   -8, 	  -4,   -6, 	   2,   -6, 	  -1,   -9
.2byte   -1,  -14, 	  -9,  -11, 	   7,  -11, 	  -1,  -10
.2byte   -3,   -8, 	  -8,   -6, 	   3,   -5, 	  -1,   -7
.2byte    0,    0, 	   0,    0, 	   0,    0, 	   0,    0
.2byte    1,  -11, 	  -7,  -14, 	   8,   -6, 	   1,   -8
.2byte    2,  -11, 	   7,   -9, 	  -6,   -9, 	   0,   -7
.2byte   -2,  -13, 	   8,  -15, 	  -9,   -6, 	   1,   -9
.2byte   -2,  -13, 	   8,  -15, 	  -9,   -6, 	   1,   -9
.2byte   -1,   -9, 	  -8,   -6, 	   6,   -6, 	  -1,   -7
.2byte   -1,   -8, 	  -8,   -5, 	   6,   -5, 	  -1,   -6
.2byte   -1,   -8, 	  -8,   -5, 	   6,   -5, 	  -1,   -6
.2byte   -6,   -9, 	  -3,   -6, 	  -2,   -4, 	   0,   -7
.2byte   -4,  -12, 	  -7,  -11, 	  -2,   -7, 	   1,   -8
.2byte   -2,  -11, 	  -7,  -11, 	   6,   -6, 	   2,   -6
.2byte   -2,  -13, 	   4,   -6, 	  -7,   -7, 	  -2,   -7
.2byte   -3,  -10, 	   5,   -5, 	  -7,   -5, 	  -1,   -6
.2byte   -1,   -5, 	   4,   -3, 	  -6,   -3, 	  -1,   -4
.2byte   -1,  -10, 	  -7,   -4, 	   5,   -4, 	  -1,   -7
.2byte   -1,  -14, 	  -9,  -11, 	   7,  -11, 	  -1,  -10
.2byte   -1,   -8, 	  -4,   -4, 	   2,   -4, 	  -1,   -7
.2byte   -6,   -9, 	  -3,   -6, 	  -2,   -4, 	   0,   -7
.2byte   -6,   -4, 	   0,   -6, 	   1,   -5, 	  -2,   -8
.2byte    5,   -9, 	   2,   -6, 	   1,   -4, 	  -1,   -7
.2byte    5,   -4, 	  -1,   -6, 	  -2,   -5, 	   1,   -8
.2byte   -2,  -13, 	   4,   -6, 	  -7,   -7, 	  -2,   -7
.2byte   -1,   -8, 	   7,   -8, 	 -10,   -8, 	  -1,   -6
.2byte   -6,   -7, 	   3,   -5, 	   2,   -7, 	  -1,   -8
.2byte   -6,   -9, 	  -7,   -8, 	   3,   -6, 	   0,   -8
.2byte  -10,   -7, 	  -6,   -6, 	  -1,   -6, 	  -3,   -7
.2byte   -5,   -9, 	  -1,   -7, 	  -2,   -6, 	   0,   -9
.2byte   -8,   -6, 	  -1,   -6, 	  -2,   -5, 	  -3,   -7
.2byte    5,   -7, 	  -4,   -5, 	  -3,   -7, 	   0,   -8
.2byte    5,   -9, 	   6,   -8, 	  -4,   -6, 	  -1,   -8
.2byte    9,   -7, 	   5,   -6, 	   0,   -6, 	   2,   -7
.2byte    4,   -9, 	   0,   -7, 	   1,   -6, 	  -1,   -9
.2byte    7,   -6, 	   0,   -6, 	   1,   -5, 	   2,   -7
.2byte    1,   -9, 	  -1,   -8, 	   5,   -9, 	  -2,   -9
.2byte   -1,   -9, 	  -3,    1, 	   0,   -7, 	  -1,   -3
.2byte   -2,   -9, 	  -3,    1, 	   0,   -7, 	  -1,   -3
.2byte    0,   -9, 	   2,    1, 	  -1,   -7, 	   0,   -3
.2byte    1,   -9, 	   2,    1, 	  -1,   -7, 	   0,   -3
.2byte   -1,   -9, 	  -3,    1, 	   0,   -7, 	  -1,   -3
.2byte   -2,   -9, 	  -3,    1, 	   0,   -7, 	  -1,   -3
.2byte    0,   -9, 	   2,    1, 	  -1,   -7, 	   0,   -3
.2byte    1,   -9, 	   2,    1, 	  -1,   -7, 	   0,   -3
sPikachuAnimTable1:
.4byte sPikachuAnims_1_1
.4byte sPikachuAnims_1_2
.4byte sPikachuAnims_1_3
.4byte sPikachuAnims_1_4
.4byte sPikachuAnims_1_5
.4byte sPikachuAnims_1_6
.4byte sPikachuAnims_1_7
.4byte sPikachuAnims_1_8
sPikachuAnimTable2:
.4byte sPikachuAnims_2_1
.4byte sPikachuAnims_2_2
.4byte sPikachuAnims_2_3
.4byte sPikachuAnims_2_4
.4byte sPikachuAnims_2_5
.4byte sPikachuAnims_2_6
.4byte sPikachuAnims_2_7
.4byte sPikachuAnims_2_8
sPikachuAnimTable3:
.4byte sPikachuAnims_3_1
.4byte sPikachuAnims_3_2
.4byte sPikachuAnims_3_3
.4byte sPikachuAnims_3_4
.4byte sPikachuAnims_3_5
.4byte sPikachuAnims_3_6
.4byte sPikachuAnims_3_7
.4byte sPikachuAnims_3_8
sPikachuAnimTable4:
.4byte sPikachuAnims_4_1
.4byte sPikachuAnims_4_2
.4byte sPikachuAnims_4_3
.4byte sPikachuAnims_4_4
.4byte sPikachuAnims_4_5
.4byte sPikachuAnims_4_6
.4byte sPikachuAnims_4_7
.4byte sPikachuAnims_4_8
sPikachuAnimTable5:
.4byte sPikachuAnims_5_1
.4byte sPikachuAnims_5_2
.4byte sPikachuAnims_5_3
.4byte sPikachuAnims_5_4
.4byte sPikachuAnims_5_5
.4byte sPikachuAnims_5_6
.4byte sPikachuAnims_5_7
.4byte sPikachuAnims_5_8
sPikachuAnimTable6:
.4byte sPikachuAnims_6_1
.4byte sPikachuAnims_6_1
.4byte sPikachuAnims_6_1
.4byte sPikachuAnims_6_1
.4byte sPikachuAnims_6_1
.4byte sPikachuAnims_6_1
.4byte sPikachuAnims_6_1
.4byte sPikachuAnims_6_1
sPikachuAnimTable7:
.4byte sPikachuAnims_7_1
.4byte sPikachuAnims_7_2
.4byte sPikachuAnims_7_3
.4byte sPikachuAnims_7_4
.4byte sPikachuAnims_7_5
.4byte sPikachuAnims_7_6
.4byte sPikachuAnims_7_7
.4byte sPikachuAnims_7_8
sPikachuAnimTable8:
.4byte sPikachuAnims_8_1
.4byte sPikachuAnims_8_2
.4byte sPikachuAnims_8_3
.4byte sPikachuAnims_8_4
.4byte sPikachuAnims_8_5
.4byte sPikachuAnims_8_6
.4byte sPikachuAnims_8_7
.4byte sPikachuAnims_8_8
sPikachuAnimTable9:
.4byte sPikachuAnims_9_1
.4byte sPikachuAnims_9_2
.4byte sPikachuAnims_9_3
.4byte sPikachuAnims_9_4
.4byte sPikachuAnims_9_5
.4byte sPikachuAnims_9_6
.4byte sPikachuAnims_9_7
.4byte sPikachuAnims_9_8
sPikachuAnimTable10:
.4byte sPikachuAnims_10_1
.4byte sPikachuAnims_10_2
.4byte sPikachuAnims_10_3
.4byte sPikachuAnims_10_4
.4byte sPikachuAnims_10_5
.4byte sPikachuAnims_10_6
.4byte sPikachuAnims_10_7
.4byte sPikachuAnims_10_8
sPikachuAnimTable11:
.4byte sPikachuAnims_11_1
.4byte sPikachuAnims_11_2
.4byte sPikachuAnims_11_3
.4byte sPikachuAnims_11_4
.4byte sPikachuAnims_11_5
.4byte sPikachuAnims_11_6
.4byte sPikachuAnims_11_7
.4byte sPikachuAnims_11_8
sPikachuAnimTable12:
.4byte sPikachuAnims_12_1
.4byte sPikachuAnims_12_2
.4byte sPikachuAnims_12_3
.4byte sPikachuAnims_12_4
.4byte sPikachuAnims_12_5
.4byte sPikachuAnims_12_6
.4byte sPikachuAnims_12_7
.4byte sPikachuAnims_12_8
sPikachuAnimTable13:
.4byte sPikachuAnims_13_1
.4byte sPikachuAnims_13_2
.4byte sPikachuAnims_13_3
.4byte sPikachuAnims_13_4
.4byte sPikachuAnims_13_5
.4byte sPikachuAnims_13_6
.4byte sPikachuAnims_13_7
.4byte sPikachuAnims_13_8
sPikachuAnimTable14:
.4byte sPikachuAnims_14_1
.4byte sPikachuAnims_14_2
.4byte sPikachuAnims_14_3
.4byte sPikachuAnims_14_4
.4byte sPikachuAnims_14_5
.4byte sPikachuAnims_14_6
.4byte sPikachuAnims_14_7
.4byte sPikachuAnims_14_8
sPikachuAnimTable15:
.4byte sPikachuAnims_15_1
.4byte sPikachuAnims_15_2
.4byte sPikachuAnims_15_3
.4byte sPikachuAnims_15_4
.4byte sPikachuAnims_15_5
.4byte sPikachuAnims_15_6
.4byte sPikachuAnims_15_7
.4byte sPikachuAnims_15_8
sPikachuAnimTable16:
.4byte sPikachuAnims_16_1
.4byte sPikachuAnims_16_2
.4byte sPikachuAnims_16_3
.4byte sPikachuAnims_16_4
.4byte sPikachuAnims_16_5
.4byte sPikachuAnims_16_6
.4byte sPikachuAnims_16_7
.4byte sPikachuAnims_16_8
sPikachuAnimTable17:
.4byte sPikachuAnims_17_1
.4byte sPikachuAnims_17_2
.4byte sPikachuAnims_17_3
.4byte sPikachuAnims_17_4
.4byte sPikachuAnims_17_5
.4byte sPikachuAnims_17_6
.4byte sPikachuAnims_17_7
.4byte sPikachuAnims_17_8
sPikachuAnimTable18:
.4byte sPikachuAnims_18_1
.4byte sPikachuAnims_18_2
.4byte sPikachuAnims_18_3
.4byte sPikachuAnims_18_4
.4byte sPikachuAnims_18_5
.4byte sPikachuAnims_18_6
.4byte sPikachuAnims_18_7
.4byte sPikachuAnims_18_8
sPikachuAnimTable19:
.4byte sPikachuAnims_19_1
.4byte sPikachuAnims_19_2
.4byte sPikachuAnims_19_3
.4byte sPikachuAnims_19_4
.4byte sPikachuAnims_19_5
.4byte sPikachuAnims_19_6
.4byte sPikachuAnims_19_7
.4byte sPikachuAnims_19_8
sPikachuAnimTable20:
.4byte sPikachuAnims_20_1
.4byte sPikachuAnims_20_2
.4byte sPikachuAnims_20_3
.4byte sPikachuAnims_20_4
.4byte sPikachuAnims_20_5
.4byte sPikachuAnims_20_6
.4byte sPikachuAnims_20_7
.4byte sPikachuAnims_20_8
sPikachuAnimTable21:
.4byte sPikachuAnims_21_1
.4byte sPikachuAnims_21_2
.4byte sPikachuAnims_21_3
.4byte sPikachuAnims_21_4
.4byte sPikachuAnims_21_5
.4byte sPikachuAnims_21_6
.4byte sPikachuAnims_21_7
.4byte sPikachuAnims_21_8
sPikachuAnimTable22:
.4byte sPikachuAnims_22_1
.4byte sPikachuAnims_22_2
.4byte sPikachuAnims_22_3
.4byte sPikachuAnims_22_4
.4byte sPikachuAnims_22_5
.4byte sPikachuAnims_22_6
.4byte sPikachuAnims_22_7
.4byte sPikachuAnims_22_8
sPikachuAnimTable23:
.4byte sPikachuAnims_23_1
.4byte sPikachuAnims_23_2
.4byte sPikachuAnims_23_3
.4byte sPikachuAnims_23_4
.4byte sPikachuAnims_23_5
.4byte sPikachuAnims_23_6
.4byte sPikachuAnims_23_7
.4byte sPikachuAnims_23_8
sPikachuAnimTable24:
.4byte sPikachuAnims_24_1
.4byte sPikachuAnims_24_2
.4byte sPikachuAnims_24_3
.4byte sPikachuAnims_24_4
.4byte sPikachuAnims_24_5
.4byte sPikachuAnims_24_6
.4byte sPikachuAnims_24_7
.4byte sPikachuAnims_24_8
sPikachuAnimTable25:
.4byte sPikachuAnims_25_1
.4byte sPikachuAnims_25_2
.4byte sPikachuAnims_25_3
.4byte sPikachuAnims_25_4
.4byte sPikachuAnims_25_5
.4byte sPikachuAnims_25_6
.4byte sPikachuAnims_25_7
.4byte sPikachuAnims_25_8
sPikachuAnimTable26:
.4byte sPikachuAnims_26_1
.4byte sPikachuAnims_26_2
.4byte sPikachuAnims_26_3
.4byte sPikachuAnims_26_4
.4byte sPikachuAnims_26_5
.4byte sPikachuAnims_26_6
.4byte sPikachuAnims_26_7
.4byte sPikachuAnims_26_8
sPikachuAnimTable27:
.4byte sPikachuAnims_27_1
.4byte sPikachuAnims_27_1
.4byte sPikachuAnims_27_1
.4byte sPikachuAnims_27_1
.4byte sPikachuAnims_27_1
.4byte sPikachuAnims_27_1
.4byte sPikachuAnims_27_1
.4byte sPikachuAnims_27_1
sPikachuAnimTable28:
.4byte sPikachuAnims_28_1
.4byte sPikachuAnims_28_2
.4byte sPikachuAnims_28_3
.4byte sPikachuAnims_28_4
.4byte sPikachuAnims_28_5
.4byte sPikachuAnims_28_6
.4byte sPikachuAnims_28_7
.4byte sPikachuAnims_28_8
sAxAnimationsPikachu:
.4byte sPikachuAnimTable1
.4byte sPikachuAnimTable2
.4byte sPikachuAnimTable3
.4byte sPikachuAnimTable4
.4byte sPikachuAnimTable5
.4byte sPikachuAnimTable6
.4byte sPikachuAnimTable7
.4byte sPikachuAnimTable8
.4byte sPikachuAnimTable9
.4byte sPikachuAnimTable10
.4byte sPikachuAnimTable11
.4byte sPikachuAnimTable12
.4byte sPikachuAnimTable13
.4byte sPikachuAnimTable14
.4byte sPikachuAnimTable15
.4byte sPikachuAnimTable16
.4byte sPikachuAnimTable17
.4byte sPikachuAnimTable18
.4byte sPikachuAnimTable19
.4byte sPikachuAnimTable20
.4byte sPikachuAnimTable21
.4byte sPikachuAnimTable22
.4byte sPikachuAnimTable23
.4byte sPikachuAnimTable24
.4byte sPikachuAnimTable25
.4byte sPikachuAnimTable26
.4byte sPikachuAnimTable27
.4byte sPikachuAnimTable28
sAxSpritesPikachu:
.4byte sPikachuSprites1
.4byte sPikachuSprites2
.4byte sPikachuSprites3
.4byte sPikachuSprites4
.4byte sPikachuSprites5
.4byte sPikachuSprites6
.4byte sPikachuSprites7
.4byte sPikachuSprites8
.4byte sPikachuSprites9
.4byte sPikachuSprites10
.4byte sPikachuSprites11
.4byte sPikachuSprites12
.4byte sPikachuSprites13
.4byte sPikachuSprites14
.4byte sPikachuSprites15
.4byte sPikachuSprites16
.4byte sPikachuSprites17
.4byte sPikachuSprites18
.4byte sPikachuSprites19
.4byte sPikachuSprites20
.4byte sPikachuSprites21
.4byte sPikachuSprites22
.4byte sPikachuSprites23
.4byte sPikachuSprites24
.4byte sPikachuSprites25
.4byte sPikachuSprites26
.4byte sPikachuSprites27
.4byte sPikachuSprites28
.4byte sPikachuSprites29
.4byte sPikachuSprites30
.4byte sPikachuSprites31
.4byte sPikachuSprites32
.4byte sPikachuSprites33
.4byte sPikachuSprites34
.4byte sPikachuSprites35
.4byte sPikachuSprites36
.4byte sPikachuSprites37
.4byte sPikachuSprites38
.4byte sPikachuSprites39
.4byte sPikachuSprites40
.4byte sPikachuSprites41
.4byte sPikachuSprites42
.4byte sPikachuSprites43
.4byte sPikachuSprites44
.4byte sPikachuSprites45
.4byte sPikachuSprites46
.4byte sPikachuSprites47
.4byte sPikachuSprites48
.4byte sPikachuSprites49
.4byte sPikachuSprites50
.4byte sPikachuSprites51
.4byte sPikachuSprites52
.4byte sPikachuSprites53
.4byte sPikachuSprites54
.4byte sPikachuSprites55
.4byte sPikachuSprites56
.4byte sPikachuSprites57
.4byte sPikachuSprites58
.4byte sPikachuSprites59
.4byte sPikachuSprites60
.4byte sPikachuSprites61
.4byte sPikachuSprites62
.4byte sPikachuSprites63
.4byte sPikachuSprites64
.4byte sPikachuSprites65
.4byte sPikachuSprites66
.4byte sPikachuSprites67
.4byte sPikachuSprites68
.4byte sPikachuSprites69
.4byte sPikachuSprites70
.4byte sPikachuSprites71
.4byte sPikachuSprites72
.4byte sPikachuSprites73
.4byte sPikachuSprites74
.4byte sPikachuSprites75
.4byte sPikachuSprites76
.4byte sPikachuSprites77
.4byte sPikachuSprites78
.4byte sPikachuSprites79
.4byte sPikachuSprites80
.4byte sPikachuSprites81
.4byte sPikachuSprites82
.4byte sPikachuSprites83
.4byte sPikachuSprites84
.4byte sPikachuSprites85
.4byte sPikachuSprites86
.4byte sPikachuSprites87
.4byte sPikachuSprites88
.4byte sPikachuSprites89
.4byte sPikachuSprites90
.4byte sPikachuSprites91
.4byte sPikachuSprites92
sAxMainPikachu:
ax_main sAxPosesPikachu, sAxAnimationsPikachu, 28, sAxSpritesPikachu, sAxPositionsPikachu
