.global gAxQwilfish
gAxQwilfish:
ax_siro sAxMainQwilfish
sQwilfishPose1:
ax_pose 0, 0x81e8, 0x80f8, 0x2c00
ax_pose_terminator
sQwilfishPose2:
ax_pose 1, 0x81e8, 0x80f8, 0x2c00
ax_pose_terminator
sQwilfishPose3:
ax_pose 2, 0x81e8, 0x80f8, 0x2c00
ax_pose_terminator
sQwilfishPose4:
ax_pose 3, 0x01e8, 0x90e9, 0x2c00
ax_pose_terminator
sQwilfishPose5:
ax_pose 4, 0x01e8, 0x90e9, 0x2c00
ax_pose_terminator
sQwilfishPose6:
ax_pose 5, 0x01e8, 0x90e9, 0x2c00
ax_pose_terminator
sQwilfishPose7:
ax_pose 6, 0x01e8, 0x90e8, 0x2c00
ax_pose_terminator
sQwilfishPose8:
ax_pose 7, 0x01e8, 0x90e8, 0x2c00
ax_pose_terminator
sQwilfishPose9:
ax_pose 8, 0x01e8, 0x90e8, 0x2c00
ax_pose_terminator
sQwilfishPose10:
ax_pose 9, 0x01e8, 0x90e9, 0x2c00
ax_pose_terminator
sQwilfishPose11:
ax_pose 10, 0x01e8, 0x90e9, 0x2c00
ax_pose_terminator
sQwilfishPose12:
ax_pose 11, 0x01e8, 0x90e9, 0x2c00
ax_pose_terminator
sQwilfishPose13:
ax_pose 12, 0x81e8, 0x80f8, 0x2c00
ax_pose_terminator
sQwilfishPose14:
ax_pose 13, 0x81e8, 0x80f8, 0x2c00
ax_pose_terminator
sQwilfishPose15:
ax_pose 14, 0x81e8, 0x80f8, 0x2c00
ax_pose_terminator
sQwilfishPose16:
ax_pose 9, 0x01e8, 0x80f6, 0x2c00
ax_pose_terminator
sQwilfishPose17:
ax_pose 10, 0x01e8, 0x80f6, 0x2c00
ax_pose_terminator
sQwilfishPose18:
ax_pose 11, 0x01e8, 0x80f6, 0x2c00
ax_pose_terminator
sQwilfishPose19:
ax_pose 6, 0x01e8, 0x80f7, 0x2c00
ax_pose_terminator
sQwilfishPose20:
ax_pose 7, 0x01e8, 0x80f7, 0x2c00
ax_pose_terminator
sQwilfishPose21:
ax_pose 8, 0x01e8, 0x80f7, 0x2c00
ax_pose_terminator
sQwilfishPose22:
ax_pose 3, 0x01e8, 0x80f6, 0x2c00
ax_pose_terminator
sQwilfishPose23:
ax_pose 4, 0x01e8, 0x80f6, 0x2c00
ax_pose_terminator
sQwilfishPose24:
ax_pose 5, 0x01e8, 0x80f6, 0x2c00
ax_pose_terminator
sQwilfishPose25:
ax_pose 0, 0x81e8, 0x80f8, 0x2c00
ax_pose_terminator
sQwilfishPose26:
ax_pose 1, 0x81e8, 0x80f8, 0x2c00
ax_pose_terminator
sQwilfishPose27:
ax_pose 2, 0x81e8, 0x80f8, 0x2c00
ax_pose_terminator
sQwilfishPose28:
ax_pose 15, 0x81ec, 0x80f7, 0x2c00
ax_pose 16, 0x01f4, 0x0107, 0x2c08
ax_pose_terminator
sQwilfishPose29:
ax_pose 3, 0x01e8, 0x90e9, 0x2c00
ax_pose_terminator
sQwilfishPose30:
ax_pose 4, 0x01e8, 0x90e9, 0x2c00
ax_pose_terminator
sQwilfishPose31:
ax_pose 5, 0x01e8, 0x90e9, 0x2c00
ax_pose_terminator
sQwilfishPose32:
ax_pose 17, 0x81e5, 0x90f9, 0x2c00
ax_pose 18, 0x01ed, 0x10f1, 0x2c08
ax_pose_terminator
sQwilfishPose33:
ax_pose 6, 0x01e8, 0x90e8, 0x2c00
ax_pose_terminator
sQwilfishPose34:
ax_pose 7, 0x01e8, 0x90e8, 0x2c00
ax_pose_terminator
sQwilfishPose35:
ax_pose 8, 0x01e8, 0x90e8, 0x2c00
ax_pose_terminator
sQwilfishPose36:
ax_pose 19, 0x01e8, 0x90eb, 0x2c00
ax_pose_terminator
sQwilfishPose37:
ax_pose 9, 0x01e8, 0x90e9, 0x2c00
ax_pose_terminator
sQwilfishPose38:
ax_pose 10, 0x01e8, 0x90e9, 0x2c00
ax_pose_terminator
sQwilfishPose39:
ax_pose 11, 0x01e8, 0x90e9, 0x2c00
ax_pose_terminator
sQwilfishPose40:
ax_pose 20, 0x81ea, 0x90fc, 0x2c00
ax_pose 21, 0x81ea, 0x10f4, 0x2c08
ax_pose_terminator
sQwilfishPose41:
ax_pose 12, 0x81e8, 0x80f8, 0x2c00
ax_pose_terminator
sQwilfishPose42:
ax_pose 13, 0x81e8, 0x80f8, 0x2c00
ax_pose_terminator
sQwilfishPose43:
ax_pose 14, 0x81e8, 0x80f8, 0x2c00
ax_pose_terminator
sQwilfishPose44:
ax_pose 22, 0x01f0, 0x40f5, 0x2c00
ax_pose 23, 0x81f0, 0x0105, 0x2c04
ax_pose_terminator
sQwilfishPose45:
ax_pose 9, 0x01e8, 0x80f6, 0x2c00
ax_pose_terminator
sQwilfishPose46:
ax_pose 10, 0x01e8, 0x80f6, 0x2c00
ax_pose_terminator
sQwilfishPose47:
ax_pose 11, 0x01e8, 0x80f6, 0x2c00
ax_pose_terminator
sQwilfishPose48:
ax_pose 20, 0x81ea, 0x80f3, 0x2c00
ax_pose 21, 0x81ea, 0x0103, 0x2c08
ax_pose_terminator
sQwilfishPose49:
ax_pose 6, 0x01e8, 0x80f7, 0x2c00
ax_pose_terminator
sQwilfishPose50:
ax_pose 7, 0x01e8, 0x80f7, 0x2c00
ax_pose_terminator
sQwilfishPose51:
ax_pose 8, 0x01e8, 0x80f7, 0x2c00
ax_pose_terminator
sQwilfishPose52:
ax_pose 19, 0x01e8, 0x80f5, 0x2c00
ax_pose_terminator
sQwilfishPose53:
ax_pose 3, 0x01e8, 0x80f6, 0x2c00
ax_pose_terminator
sQwilfishPose54:
ax_pose 4, 0x01e8, 0x80f6, 0x2c00
ax_pose_terminator
sQwilfishPose55:
ax_pose 5, 0x01e8, 0x80f6, 0x2c00
ax_pose_terminator
sQwilfishPose56:
ax_pose 17, 0x81e5, 0x80f6, 0x2c00
ax_pose 18, 0x01ed, 0x0106, 0x2c08
ax_pose_terminator
sQwilfishPose57:
ax_pose 0, 0x81e8, 0x80f8, 0x2c00
ax_pose_terminator
sQwilfishPose58:
ax_pose 1, 0x81e8, 0x80f8, 0x2c00
ax_pose_terminator
sQwilfishPose59:
ax_pose 2, 0x81e8, 0x80f8, 0x2c00
ax_pose_terminator
sQwilfishPose60:
ax_pose 15, 0x81ec, 0x80f7, 0x2c00
ax_pose 16, 0x01f4, 0x0107, 0x2c08
ax_pose_terminator
sQwilfishPose61:
ax_pose 3, 0x01e8, 0x90e9, 0x2c00
ax_pose_terminator
sQwilfishPose62:
ax_pose 4, 0x01e8, 0x90e9, 0x2c00
ax_pose_terminator
sQwilfishPose63:
ax_pose 5, 0x01e8, 0x90e9, 0x2c00
ax_pose_terminator
sQwilfishPose64:
ax_pose 17, 0x81e5, 0x90f9, 0x2c00
ax_pose 18, 0x01ed, 0x10f1, 0x2c08
ax_pose_terminator
sQwilfishPose65:
ax_pose 6, 0x01e8, 0x90e8, 0x2c00
ax_pose_terminator
sQwilfishPose66:
ax_pose 7, 0x01e8, 0x90e8, 0x2c00
ax_pose_terminator
sQwilfishPose67:
ax_pose 8, 0x01e8, 0x90e8, 0x2c00
ax_pose_terminator
sQwilfishPose68:
ax_pose 19, 0x01e8, 0x90eb, 0x2c00
ax_pose_terminator
sQwilfishPose69:
ax_pose 9, 0x01e8, 0x90e9, 0x2c00
ax_pose_terminator
sQwilfishPose70:
ax_pose 10, 0x01e8, 0x90e9, 0x2c00
ax_pose_terminator
sQwilfishPose71:
ax_pose 11, 0x01e8, 0x90e9, 0x2c00
ax_pose_terminator
sQwilfishPose72:
ax_pose 20, 0x81ea, 0x90fc, 0x2c00
ax_pose 21, 0x81ea, 0x10f4, 0x2c08
ax_pose_terminator
sQwilfishPose73:
ax_pose 12, 0x81e8, 0x80f8, 0x2c00
ax_pose_terminator
sQwilfishPose74:
ax_pose 13, 0x81e8, 0x80f8, 0x2c00
ax_pose_terminator
sQwilfishPose75:
ax_pose 14, 0x81e8, 0x80f8, 0x2c00
ax_pose_terminator
sQwilfishPose76:
ax_pose 22, 0x01f0, 0x40f5, 0x2c00
ax_pose 23, 0x81f0, 0x0105, 0x2c04
ax_pose_terminator
sQwilfishPose77:
ax_pose 9, 0x01e8, 0x80f6, 0x2c00
ax_pose_terminator
sQwilfishPose78:
ax_pose 10, 0x01e8, 0x80f6, 0x2c00
ax_pose_terminator
sQwilfishPose79:
ax_pose 11, 0x01e8, 0x80f6, 0x2c00
ax_pose_terminator
sQwilfishPose80:
ax_pose 20, 0x81ea, 0x80f3, 0x2c00
ax_pose 21, 0x81ea, 0x0103, 0x2c08
ax_pose_terminator
sQwilfishPose81:
ax_pose 6, 0x01e8, 0x80f7, 0x2c00
ax_pose_terminator
sQwilfishPose82:
ax_pose 7, 0x01e8, 0x80f7, 0x2c00
ax_pose_terminator
sQwilfishPose83:
ax_pose 8, 0x01e8, 0x80f7, 0x2c00
ax_pose_terminator
sQwilfishPose84:
ax_pose 19, 0x01e8, 0x80f5, 0x2c00
ax_pose_terminator
sQwilfishPose85:
ax_pose 3, 0x01e8, 0x80f6, 0x2c00
ax_pose_terminator
sQwilfishPose86:
ax_pose 4, 0x01e8, 0x80f6, 0x2c00
ax_pose_terminator
sQwilfishPose87:
ax_pose 5, 0x01e8, 0x80f6, 0x2c00
ax_pose_terminator
sQwilfishPose88:
ax_pose 17, 0x81e5, 0x80f6, 0x2c00
ax_pose 18, 0x01ed, 0x0106, 0x2c08
ax_pose_terminator
sQwilfishPose89:
ax_pose 24, 0x01e8, 0x80f4, 0x2c00
ax_pose_terminator
sQwilfishPose90:
ax_pose 25, 0x01e8, 0x80f4, 0x2c00
ax_pose_terminator
sQwilfishPose91:
ax_pose 0, 0x81e8, 0x80f8, 0x2c00
ax_pose_terminator
sQwilfishPose92:
ax_pose 1, 0x81e8, 0x80f8, 0x2c00
ax_pose_terminator
sQwilfishPose93:
ax_pose 2, 0x81e8, 0x80f8, 0x2c00
ax_pose_terminator
sQwilfishPose94:
ax_pose 15, 0x81ec, 0x80f7, 0x2c00
ax_pose 16, 0x01f4, 0x0107, 0x2c08
ax_pose_terminator
sQwilfishPose95:
ax_pose 26, 0x01e8, 0x90ec, 0x2c00
ax_pose_terminator
sQwilfishPose96:
ax_pose 27, 0x01e8, 0x90ec, 0x2c00
ax_pose_terminator
sQwilfishPose97:
ax_pose 3, 0x01e8, 0x90e9, 0x2c00
ax_pose_terminator
sQwilfishPose98:
ax_pose 4, 0x01e8, 0x90e9, 0x2c00
ax_pose_terminator
sQwilfishPose99:
ax_pose 5, 0x01e8, 0x90e9, 0x2c00
ax_pose_terminator
sQwilfishPose100:
ax_pose 17, 0x81e5, 0x90f9, 0x2c00
ax_pose 18, 0x01ed, 0x10f1, 0x2c08
ax_pose_terminator
sQwilfishPose101:
ax_pose 28, 0x01e7, 0x90ea, 0x2c00
ax_pose_terminator
sQwilfishPose102:
ax_pose 29, 0x01e7, 0x90ea, 0x2c00
ax_pose_terminator
sQwilfishPose103:
ax_pose 6, 0x01e8, 0x90e8, 0x2c00
ax_pose_terminator
sQwilfishPose104:
ax_pose 7, 0x01e8, 0x90e8, 0x2c00
ax_pose_terminator
sQwilfishPose105:
ax_pose 8, 0x01e8, 0x90e8, 0x2c00
ax_pose_terminator
sQwilfishPose106:
ax_pose 19, 0x01e8, 0x90eb, 0x2c00
ax_pose_terminator
sQwilfishPose107:
ax_pose 30, 0x01e8, 0x90ec, 0x2c00
ax_pose_terminator
sQwilfishPose108:
ax_pose 31, 0x01e8, 0x90ec, 0x2c00
ax_pose_terminator
sQwilfishPose109:
ax_pose 9, 0x01e8, 0x90e9, 0x2c00
ax_pose_terminator
sQwilfishPose110:
ax_pose 10, 0x01e8, 0x90e9, 0x2c00
ax_pose_terminator
sQwilfishPose111:
ax_pose 11, 0x01e8, 0x90e9, 0x2c00
ax_pose_terminator
sQwilfishPose112:
ax_pose 20, 0x81ea, 0x90fc, 0x2c00
ax_pose 21, 0x81ea, 0x10f4, 0x2c08
ax_pose_terminator
sQwilfishPose113:
ax_pose 32, 0x01e8, 0x80f3, 0x2c00
ax_pose_terminator
sQwilfishPose114:
ax_pose 33, 0x01e8, 0x80f3, 0x2c00
ax_pose_terminator
sQwilfishPose115:
ax_pose 12, 0x81e8, 0x80f8, 0x2c00
ax_pose_terminator
sQwilfishPose116:
ax_pose 13, 0x81e8, 0x80f8, 0x2c00
ax_pose_terminator
sQwilfishPose117:
ax_pose 14, 0x81e8, 0x80f8, 0x2c00
ax_pose_terminator
sQwilfishPose118:
ax_pose 22, 0x01f0, 0x40f5, 0x2c00
ax_pose 23, 0x81f0, 0x0105, 0x2c04
ax_pose_terminator
sQwilfishPose119:
ax_pose 30, 0x01e8, 0x80f4, 0x2c00
ax_pose_terminator
sQwilfishPose120:
ax_pose 31, 0x01e8, 0x80f4, 0x2c00
ax_pose_terminator
sQwilfishPose121:
ax_pose 9, 0x01e8, 0x80f6, 0x2c00
ax_pose_terminator
sQwilfishPose122:
ax_pose 10, 0x01e8, 0x80f6, 0x2c00
ax_pose_terminator
sQwilfishPose123:
ax_pose 11, 0x01e8, 0x80f6, 0x2c00
ax_pose_terminator
sQwilfishPose124:
ax_pose 20, 0x81ea, 0x80f3, 0x2c00
ax_pose 21, 0x81ea, 0x0103, 0x2c08
ax_pose_terminator
sQwilfishPose125:
ax_pose 28, 0x01e7, 0x80f5, 0x2c00
ax_pose_terminator
sQwilfishPose126:
ax_pose 29, 0x01e7, 0x80f5, 0x2c00
ax_pose_terminator
sQwilfishPose127:
ax_pose 6, 0x01e8, 0x80f7, 0x2c00
ax_pose_terminator
sQwilfishPose128:
ax_pose 7, 0x01e8, 0x80f7, 0x2c00
ax_pose_terminator
sQwilfishPose129:
ax_pose 8, 0x01e8, 0x80f7, 0x2c00
ax_pose_terminator
sQwilfishPose130:
ax_pose 19, 0x01e8, 0x80f5, 0x2c00
ax_pose_terminator
sQwilfishPose131:
ax_pose 26, 0x01e8, 0x80f4, 0x2c00
ax_pose_terminator
sQwilfishPose132:
ax_pose 27, 0x01e8, 0x80f4, 0x2c00
ax_pose_terminator
sQwilfishPose133:
ax_pose 3, 0x01e8, 0x80f6, 0x2c00
ax_pose_terminator
sQwilfishPose134:
ax_pose 4, 0x01e8, 0x80f6, 0x2c00
ax_pose_terminator
sQwilfishPose135:
ax_pose 5, 0x01e8, 0x80f6, 0x2c00
ax_pose_terminator
sQwilfishPose136:
ax_pose 17, 0x81e5, 0x80f6, 0x2c00
ax_pose 18, 0x01ed, 0x0106, 0x2c08
ax_pose_terminator
sQwilfishPose137:
ax_pose 0, 0x81e8, 0x80f8, 0x2c00
ax_pose_terminator
sQwilfishPose138:
ax_pose 34, 0x01ef, 0x40f7, 0x2c00
ax_pose_terminator
sQwilfishPose139:
ax_pose 3, 0x01e8, 0x90e9, 0x2c00
ax_pose_terminator
sQwilfishPose140:
ax_pose 35, 0x01ed, 0x50f7, 0x2c00
ax_pose_terminator
sQwilfishPose141:
ax_pose 6, 0x01e8, 0x90e8, 0x2c00
ax_pose_terminator
sQwilfishPose142:
ax_pose 36, 0x01ee, 0x50f6, 0x2c00
ax_pose 37, 0x81ee, 0x10ee, 0x2c04
ax_pose_terminator
sQwilfishPose143:
ax_pose 9, 0x01e8, 0x90e9, 0x2c00
ax_pose_terminator
sQwilfishPose144:
ax_pose 38, 0x01f1, 0x50f8, 0x2c00
ax_pose_terminator
sQwilfishPose145:
ax_pose 12, 0x81e8, 0x80f8, 0x2c00
ax_pose_terminator
sQwilfishPose146:
ax_pose 39, 0x01f0, 0x40f6, 0x2c00
ax_pose_terminator
sQwilfishPose147:
ax_pose 9, 0x01e8, 0x80f6, 0x2c00
ax_pose_terminator
sQwilfishPose148:
ax_pose 38, 0x01f1, 0x40f8, 0x2c00
ax_pose_terminator
sQwilfishPose149:
ax_pose 6, 0x01e8, 0x80f7, 0x2c00
ax_pose_terminator
sQwilfishPose150:
ax_pose 36, 0x01ee, 0x40f9, 0x2c00
ax_pose 37, 0x81ee, 0x0109, 0x2c04
ax_pose_terminator
sQwilfishPose151:
ax_pose 3, 0x01e8, 0x80f6, 0x2c00
ax_pose_terminator
sQwilfishPose152:
ax_pose 35, 0x01ed, 0x40f9, 0x2c00
ax_pose_terminator
sQwilfishPose153:
ax_pose 40, 0x81ea, 0x80f8, 0x2c00
ax_pose_terminator
sQwilfishPose154:
ax_pose 41, 0x81ea, 0x80f8, 0x2c00
ax_pose_terminator
sQwilfishPose155:
ax_pose 42, 0x01e1, 0x80f3, 0x2c00
ax_pose_terminator
sQwilfishPose156:
ax_pose 43, 0x01e7, 0x90e8, 0x2c00
ax_pose_terminator
sQwilfishPose157:
ax_pose 44, 0x01e4, 0x90e9, 0x2c00
ax_pose_terminator
sQwilfishPose158:
ax_pose 45, 0x01e6, 0x90e9, 0x2c00
ax_pose_terminator
sQwilfishPose159:
ax_pose 46, 0x01e5, 0x80f2, 0x2c00
ax_pose_terminator
sQwilfishPose160:
ax_pose 45, 0x01e6, 0x80f7, 0x2c00
ax_pose_terminator
sQwilfishPose161:
ax_pose 44, 0x01e4, 0x80f7, 0x2c00
ax_pose_terminator
sQwilfishPose162:
ax_pose 43, 0x01e7, 0x80f8, 0x2c00
ax_pose_terminator
sQwilfishPose163:
ax_pose 0, 0x81e8, 0x80f8, 0x2c00
ax_pose_terminator
sQwilfishPose164:
ax_pose 1, 0x81e8, 0x80f8, 0x2c00
ax_pose_terminator
sQwilfishPose165:
ax_pose 2, 0x81e8, 0x80f8, 0x2c00
ax_pose_terminator
sQwilfishPose166:
ax_pose 15, 0x81ec, 0x80f7, 0x2c00
ax_pose 16, 0x01f4, 0x0107, 0x2c08
ax_pose_terminator
sQwilfishPose167:
ax_pose 3, 0x01e8, 0x90e9, 0x2c00
ax_pose_terminator
sQwilfishPose168:
ax_pose 4, 0x01e8, 0x90e9, 0x2c00
ax_pose_terminator
sQwilfishPose169:
ax_pose 5, 0x01e8, 0x90e9, 0x2c00
ax_pose_terminator
sQwilfishPose170:
ax_pose 17, 0x81e5, 0x90f9, 0x2c00
ax_pose 18, 0x01ed, 0x10f1, 0x2c08
ax_pose_terminator
sQwilfishPose171:
ax_pose 6, 0x01e8, 0x90e8, 0x2c00
ax_pose_terminator
sQwilfishPose172:
ax_pose 7, 0x01e8, 0x90e8, 0x2c00
ax_pose_terminator
sQwilfishPose173:
ax_pose 8, 0x01e8, 0x90e8, 0x2c00
ax_pose_terminator
sQwilfishPose174:
ax_pose 19, 0x01e8, 0x90eb, 0x2c00
ax_pose_terminator
sQwilfishPose175:
ax_pose 9, 0x01e8, 0x90e9, 0x2c00
ax_pose_terminator
sQwilfishPose176:
ax_pose 10, 0x01e8, 0x90e9, 0x2c00
ax_pose_terminator
sQwilfishPose177:
ax_pose 11, 0x01e8, 0x90e9, 0x2c00
ax_pose_terminator
sQwilfishPose178:
ax_pose 20, 0x81ea, 0x90fc, 0x2c00
ax_pose 21, 0x81ea, 0x10f4, 0x2c08
ax_pose_terminator
sQwilfishPose179:
ax_pose 12, 0x81e8, 0x80f8, 0x2c00
ax_pose_terminator
sQwilfishPose180:
ax_pose 13, 0x81e8, 0x80f8, 0x2c00
ax_pose_terminator
sQwilfishPose181:
ax_pose 14, 0x81e8, 0x80f8, 0x2c00
ax_pose_terminator
sQwilfishPose182:
ax_pose 22, 0x01f0, 0x40f5, 0x2c00
ax_pose 23, 0x81f0, 0x0105, 0x2c04
ax_pose_terminator
sQwilfishPose183:
ax_pose 9, 0x01e8, 0x80f6, 0x2c00
ax_pose_terminator
sQwilfishPose184:
ax_pose 10, 0x01e8, 0x80f6, 0x2c00
ax_pose_terminator
sQwilfishPose185:
ax_pose 11, 0x01e8, 0x80f6, 0x2c00
ax_pose_terminator
sQwilfishPose186:
ax_pose 20, 0x81ea, 0x80f3, 0x2c00
ax_pose 21, 0x81ea, 0x0103, 0x2c08
ax_pose_terminator
sQwilfishPose187:
ax_pose 6, 0x01e8, 0x80f7, 0x2c00
ax_pose_terminator
sQwilfishPose188:
ax_pose 7, 0x01e8, 0x80f7, 0x2c00
ax_pose_terminator
sQwilfishPose189:
ax_pose 8, 0x01e8, 0x80f7, 0x2c00
ax_pose_terminator
sQwilfishPose190:
ax_pose 19, 0x01e8, 0x80f5, 0x2c00
ax_pose_terminator
sQwilfishPose191:
ax_pose 3, 0x01e8, 0x80f6, 0x2c00
ax_pose_terminator
sQwilfishPose192:
ax_pose 4, 0x01e8, 0x80f6, 0x2c00
ax_pose_terminator
sQwilfishPose193:
ax_pose 5, 0x01e8, 0x80f6, 0x2c00
ax_pose_terminator
sQwilfishPose194:
ax_pose 17, 0x81e5, 0x80f6, 0x2c00
ax_pose 18, 0x01ed, 0x0106, 0x2c08
ax_pose_terminator
sQwilfishPose195:
ax_pose 15, 0x81ea, 0x80f7, 0x2c00
ax_pose 16, 0x01f2, 0x0107, 0x2c08
ax_pose_terminator
sQwilfishPose196:
ax_pose 17, 0x81e6, 0x80f7, 0x2c00
ax_pose 18, 0x01ee, 0x0107, 0x2c08
ax_pose_terminator
sQwilfishPose197:
ax_pose 19, 0x01e8, 0x80f6, 0x2c00
ax_pose_terminator
sQwilfishPose198:
ax_pose 20, 0x81ec, 0x80f6, 0x2c00
ax_pose 21, 0x81ec, 0x0106, 0x2c08
ax_pose_terminator
sQwilfishPose199:
ax_pose 22, 0x01f0, 0x40f5, 0x2c00
ax_pose 23, 0x81f0, 0x0105, 0x2c04
ax_pose_terminator
sQwilfishPose200:
ax_pose 20, 0x81ec, 0x90fa, 0x2c00
ax_pose 21, 0x81ec, 0x10f2, 0x2c08
ax_pose_terminator
sQwilfishPose201:
ax_pose 19, 0x01e8, 0x90eb, 0x2c00
ax_pose_terminator
sQwilfishPose202:
ax_pose 17, 0x81e6, 0x90f9, 0x2c00
ax_pose 18, 0x01ee, 0x10f1, 0x2c08
ax_pose_terminator
sQwilfishPose203:
ax_pose 15, 0x81ea, 0x80f7, 0x2c00
ax_pose 16, 0x01f2, 0x0107, 0x2c08
ax_pose_terminator
sQwilfishPose204:
ax_pose 17, 0x81e6, 0x90f9, 0x2c00
ax_pose 18, 0x01ee, 0x10f1, 0x2c08
ax_pose_terminator
sQwilfishPose205:
ax_pose 19, 0x01e8, 0x90eb, 0x2c00
ax_pose_terminator
sQwilfishPose206:
ax_pose 20, 0x81ec, 0x90fa, 0x2c00
ax_pose 21, 0x81ec, 0x10f2, 0x2c08
ax_pose_terminator
sQwilfishPose207:
ax_pose 22, 0x01f0, 0x40f5, 0x2c00
ax_pose 23, 0x81f0, 0x0105, 0x2c04
ax_pose_terminator
sQwilfishPose208:
ax_pose 20, 0x81ec, 0x80f6, 0x2c00
ax_pose 21, 0x81ec, 0x0106, 0x2c08
ax_pose_terminator
sQwilfishPose209:
ax_pose 19, 0x01e8, 0x80f6, 0x2c00
ax_pose_terminator
sQwilfishPose210:
ax_pose 17, 0x81e6, 0x80f7, 0x2c00
ax_pose 18, 0x01ee, 0x0107, 0x2c08
ax_pose_terminator
sQwilfishPose211:
ax_pose 0, 0x81e8, 0x80f8, 0x2c00
ax_pose_terminator
sQwilfishPose212:
ax_pose 1, 0x81e8, 0x80f8, 0x2c00
ax_pose_terminator
sQwilfishPose213:
ax_pose 2, 0x81e8, 0x80f8, 0x2c00
ax_pose_terminator
sQwilfishPose214:
ax_pose 3, 0x01e8, 0x90e9, 0x2c00
ax_pose_terminator
sQwilfishPose215:
ax_pose 4, 0x01e8, 0x90e9, 0x2c00
ax_pose_terminator
sQwilfishPose216:
ax_pose 5, 0x01e8, 0x90e9, 0x2c00
ax_pose_terminator
sQwilfishPose217:
ax_pose 6, 0x01e8, 0x90e8, 0x2c00
ax_pose_terminator
sQwilfishPose218:
ax_pose 7, 0x01e8, 0x90e8, 0x2c00
ax_pose_terminator
sQwilfishPose219:
ax_pose 8, 0x01e8, 0x90e8, 0x2c00
ax_pose_terminator
sQwilfishPose220:
ax_pose 9, 0x01e8, 0x90e9, 0x2c00
ax_pose_terminator
sQwilfishPose221:
ax_pose 10, 0x01e8, 0x90e9, 0x2c00
ax_pose_terminator
sQwilfishPose222:
ax_pose 11, 0x01e8, 0x90e9, 0x2c00
ax_pose_terminator
sQwilfishPose223:
ax_pose 12, 0x81e8, 0x80f8, 0x2c00
ax_pose_terminator
sQwilfishPose224:
ax_pose 13, 0x81e8, 0x80f8, 0x2c00
ax_pose_terminator
sQwilfishPose225:
ax_pose 14, 0x81e8, 0x80f8, 0x2c00
ax_pose_terminator
sQwilfishPose226:
ax_pose 9, 0x01e8, 0x80f6, 0x2c00
ax_pose_terminator
sQwilfishPose227:
ax_pose 10, 0x01e8, 0x80f6, 0x2c00
ax_pose_terminator
sQwilfishPose228:
ax_pose 11, 0x01e8, 0x80f6, 0x2c00
ax_pose_terminator
sQwilfishPose229:
ax_pose 6, 0x01e8, 0x80f7, 0x2c00
ax_pose_terminator
sQwilfishPose230:
ax_pose 7, 0x01e8, 0x80f7, 0x2c00
ax_pose_terminator
sQwilfishPose231:
ax_pose 8, 0x01e8, 0x80f7, 0x2c00
ax_pose_terminator
sQwilfishPose232:
ax_pose 3, 0x01e8, 0x80f6, 0x2c00
ax_pose_terminator
sQwilfishPose233:
ax_pose 4, 0x01e8, 0x80f6, 0x2c00
ax_pose_terminator
sQwilfishPose234:
ax_pose 5, 0x01e8, 0x80f6, 0x2c00
ax_pose_terminator
sQwilfishPose235:
ax_pose 15, 0x81ea, 0x80f7, 0x2c00
ax_pose 16, 0x01f2, 0x0107, 0x2c08
ax_pose_terminator
sQwilfishPose236:
ax_pose 17, 0x81e6, 0x90f9, 0x2c00
ax_pose 18, 0x01ee, 0x10f1, 0x2c08
ax_pose_terminator
sQwilfishPose237:
ax_pose 19, 0x01e8, 0x90eb, 0x2c00
ax_pose_terminator
sQwilfishPose238:
ax_pose 20, 0x81ec, 0x90fa, 0x2c00
ax_pose 21, 0x81ec, 0x10f2, 0x2c08
ax_pose_terminator
sQwilfishPose239:
ax_pose 22, 0x01f0, 0x40f5, 0x2c00
ax_pose 23, 0x81f0, 0x0105, 0x2c04
ax_pose_terminator
sQwilfishPose240:
ax_pose 20, 0x81ec, 0x80f6, 0x2c00
ax_pose 21, 0x81ec, 0x0106, 0x2c08
ax_pose_terminator
sQwilfishPose241:
ax_pose 19, 0x01e8, 0x80f6, 0x2c00
ax_pose_terminator
sQwilfishPose242:
ax_pose 17, 0x81e6, 0x80f7, 0x2c00
ax_pose 18, 0x01ee, 0x0107, 0x2c08
ax_pose_terminator
sQwilfishPose243:
ax_pose 0, 0x81e8, 0x80f8, 0x2c00
ax_pose_terminator
sQwilfishPose244:
ax_pose 3, 0x01e8, 0x80f6, 0x2c00
ax_pose_terminator
sQwilfishPose245:
ax_pose 6, 0x01e8, 0x80f7, 0x2c00
ax_pose_terminator
sQwilfishPose246:
ax_pose 9, 0x01e8, 0x80f6, 0x2c00
ax_pose_terminator
sQwilfishPose247:
ax_pose 12, 0x81e8, 0x80f8, 0x2c00
ax_pose_terminator
sQwilfishPose248:
ax_pose 9, 0x01e8, 0x90e9, 0x2c00
ax_pose_terminator
sQwilfishPose249:
ax_pose 6, 0x01e8, 0x90e8, 0x2c00
ax_pose_terminator
sQwilfishPose250:
ax_pose 3, 0x01e8, 0x90e9, 0x2c00
ax_pose_terminator
.align 2
sQwilfishAnims_1_1:
ax_anim 8, 0, 0, 0, 0, 0, 0,
ax_anim 8, 0, 1, 0, 0, 0, 0,
ax_anim 8, 0, 0, 0, 0, 0, 0,
ax_anim 8, 0, 2, 0, 0, 0, 0,
ax_anim_terminator
sQwilfishAnims_1_2:
ax_anim 8, 0, 3, 0, 0, 0, 0,
ax_anim 8, 0, 4, 0, 0, 0, 0,
ax_anim 8, 0, 3, 0, 0, 0, 0,
ax_anim 8, 0, 5, 0, 0, 0, 0,
ax_anim_terminator
sQwilfishAnims_1_3:
ax_anim 8, 0, 6, 0, 0, 0, 0,
ax_anim 8, 0, 7, 0, 0, 0, 0,
ax_anim 8, 0, 6, 0, 0, 0, 0,
ax_anim 8, 0, 8, 0, 0, 0, 0,
ax_anim_terminator
sQwilfishAnims_1_4:
ax_anim 8, 0, 9, 0, 0, 0, 0,
ax_anim 8, 0, 10, 0, 0, 0, 0,
ax_anim 8, 0, 9, 0, 0, 0, 0,
ax_anim 8, 0, 11, 0, 0, 0, 0,
ax_anim_terminator
sQwilfishAnims_1_5:
ax_anim 8, 0, 12, 0, 0, 0, 0,
ax_anim 8, 0, 13, 0, 0, 0, 0,
ax_anim 8, 0, 12, 0, 0, 0, 0,
ax_anim 8, 0, 14, 0, 0, 0, 0,
ax_anim_terminator
sQwilfishAnims_1_6:
ax_anim 8, 0, 15, 0, 0, 0, 0,
ax_anim 8, 0, 16, 0, 0, 0, 0,
ax_anim 8, 0, 15, 0, 0, 0, 0,
ax_anim 8, 0, 17, 0, 0, 0, 0,
ax_anim_terminator
sQwilfishAnims_1_7:
ax_anim 8, 0, 18, 0, 0, 0, 0,
ax_anim 8, 0, 19, 0, 0, 0, 0,
ax_anim 8, 0, 18, 0, 0, 0, 0,
ax_anim 8, 0, 20, 0, 0, 0, 0,
ax_anim_terminator
sQwilfishAnims_1_8:
ax_anim 8, 0, 21, 0, 0, 0, 0,
ax_anim 8, 0, 22, 0, 0, 0, 0,
ax_anim 8, 0, 21, 0, 0, 0, 0,
ax_anim 8, 0, 23, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sQwilfishAnims_2_1:
ax_anim 2, 0, 25, 0, -1, 0, -1,
ax_anim 2, 0, 26, 0, -2, 0, -2,
ax_anim 2, 0, 25, 0, -3, 0, -3,
ax_anim 6, 0, 26, 0, -3, 0, -3,
ax_anim 1, 0, 24, 0, 0, 0, 0,
ax_anim 1, 2, 27, 0, 4, 0, 4,
ax_anim 1, 0, 27, 0, 10, 0, 10,
ax_anim 2, 0, 27, 0, 20, 0, 20,
ax_anim 2, 1, 27, 1, 20, 1, 20,
ax_anim 2, 0, 27, 0, 20, 0, 20,
ax_anim 2, 0, 27, 1, 20, 1, 20,
ax_anim 2, 0, 24, 0, 6, 0, 6,
ax_anim_terminator
sQwilfishAnims_2_2:
ax_anim 2, 0, 29, -1, -1, -1, -1,
ax_anim 2, 0, 30, -2, -2, -2, -2,
ax_anim 2, 0, 29, -3, -3, -3, -3,
ax_anim 6, 0, 30, -3, -3, -3, -3,
ax_anim 1, 0, 28, 0, 0, 0, 0,
ax_anim 1, 2, 31, 4, 4, 4, 4,
ax_anim 1, 0, 31, 10, 10, 10, 10,
ax_anim 2, 0, 31, 22, 22, 22, 22,
ax_anim 2, 1, 31, 23, 21, 23, 21,
ax_anim 2, 0, 31, 22, 22, 22, 22,
ax_anim 2, 0, 31, 23, 21, 23, 21,
ax_anim 2, 0, 28, 6, 6, 6, 6,
ax_anim_terminator
sQwilfishAnims_2_3:
ax_anim 2, 0, 33, -1, 0, -1, 0,
ax_anim 2, 0, 34, -2, 0, -2, 0,
ax_anim 2, 0, 33, -3, 0, -3, 0,
ax_anim 6, 0, 34, -3, 0, -3, 0,
ax_anim 1, 0, 32, 0, 0, 0, 0,
ax_anim 1, 2, 35, 4, 0, 4, 0,
ax_anim 1, 0, 35, 10, 0, 10, 0,
ax_anim 2, 0, 35, 21, 0, 21, 0,
ax_anim 2, 1, 35, 21, 1, 21, 1,
ax_anim 2, 0, 35, 21, 0, 21, 0,
ax_anim 2, 0, 35, 21, 1, 21, 1,
ax_anim 2, 0, 32, 6, 0, 6, 0,
ax_anim_terminator
sQwilfishAnims_2_4:
ax_anim 2, 0, 37, -1, 1, -1, 1,
ax_anim 2, 0, 38, -2, 2, -2, 2,
ax_anim 2, 0, 37, -3, 3, -3, 3,
ax_anim 6, 0, 38, -3, 3, -3, 3,
ax_anim 1, 0, 36, 0, 0, 0, 0,
ax_anim 1, 2, 39, 4, -4, 4, -4,
ax_anim 1, 0, 39, 10, -10, 10, -10,
ax_anim 2, 0, 39, 19, -19, 19, -19,
ax_anim 2, 1, 39, 20, -18, 20, -18,
ax_anim 2, 0, 39, 19, -19, 19, -19,
ax_anim 2, 0, 39, 20, -18, 20, -18,
ax_anim 2, 0, 36, 6, -6, 6, -6,
ax_anim_terminator
sQwilfishAnims_2_5:
ax_anim 2, 0, 41, 0, 1, 0, 1,
ax_anim 2, 0, 42, 0, 2, 0, 2,
ax_anim 2, 0, 41, 0, 3, 0, 3,
ax_anim 6, 0, 42, 0, 3, 0, 3,
ax_anim 1, 0, 40, 0, 0, 0, 0,
ax_anim 1, 2, 43, 0, -4, 0, -4,
ax_anim 1, 0, 43, 0, -10, 0, -10,
ax_anim 2, 0, 43, 0, -22, 0, -22,
ax_anim 2, 1, 43, 1, -22, 1, -22,
ax_anim 2, 0, 43, 0, -22, 0, -22,
ax_anim 2, 0, 43, 1, -22, 1, -22,
ax_anim 2, 0, 40, 0, -6, 0, -6,
ax_anim_terminator
sQwilfishAnims_2_6:
ax_anim 2, 0, 45, 1, 1, 1, 1,
ax_anim 2, 0, 46, 2, 2, 2, 2,
ax_anim 2, 0, 45, 3, 3, 3, 3,
ax_anim 6, 0, 46, 3, 3, 3, 3,
ax_anim 1, 0, 44, 0, 0, 0, 0,
ax_anim 1, 2, 47, -4, -4, -4, -4,
ax_anim 1, 0, 47, -10, -10, -10, -10,
ax_anim 2, 0, 47, -19, -19, -19, -19,
ax_anim 2, 1, 47, -20, -18, -20, -18,
ax_anim 2, 0, 47, -19, -19, -19, -19,
ax_anim 2, 0, 47, -20, -18, -20, -18,
ax_anim 2, 0, 44, -6, -6, -6, -6,
ax_anim_terminator
sQwilfishAnims_2_7:
ax_anim 2, 0, 49, 1, 0, 1, 0,
ax_anim 2, 0, 50, 2, 0, 2, 0,
ax_anim 2, 0, 49, 3, 0, 3, 0,
ax_anim 6, 0, 50, 3, 0, 3, 0,
ax_anim 1, 0, 48, 0, 0, 0, 0,
ax_anim 1, 2, 51, -4, 0, -4, 0,
ax_anim 1, 0, 51, -10, 0, -10, 0,
ax_anim 2, 0, 51, -21, 0, -21, 0,
ax_anim 2, 1, 51, -21, 1, -21, 1,
ax_anim 2, 0, 51, -21, 0, -21, 0,
ax_anim 2, 0, 51, -21, 1, -21, 1,
ax_anim 2, 0, 48, -6, 0, -6, 0,
ax_anim_terminator
sQwilfishAnims_2_8:
ax_anim 2, 0, 53, 1, -1, 1, -1,
ax_anim 2, 0, 54, 2, -2, 2, -2,
ax_anim 2, 0, 53, 3, -3, 3, -3,
ax_anim 6, 0, 54, 3, -3, 3, -3,
ax_anim 1, 0, 52, 0, 0, 0, 0,
ax_anim 1, 2, 55, -4, 4, -4, 4,
ax_anim 1, 0, 55, -10, 10, -10, 10,
ax_anim 2, 0, 55, -22, 22, -22, 22,
ax_anim 2, 1, 55, -23, 21, -23, 21,
ax_anim 2, 0, 55, -22, 22, -22, 22,
ax_anim 2, 0, 55, -23, 21, -23, 21,
ax_anim 2, 0, 52, -6, 6, -6, 6,
ax_anim_terminator
.align 2
sQwilfishAnims_3_1:
ax_anim 2, 0, 57, 0, -1, 0, -1,
ax_anim 2, 0, 58, 0, -2, 0, -2,
ax_anim 2, 0, 57, 0, -3, 0, -3,
ax_anim 6, 0, 58, 0, -3, 0, -3,
ax_anim 1, 0, 56, 0, 0, 0, 0,
ax_anim 1, 2, 59, 0, 4, 0, 4,
ax_anim 1, 0, 59, 0, 10, 0, 10,
ax_anim 2, 0, 59, 0, 20, 0, 20,
ax_anim 2, 1, 59, 1, 20, 1, 20,
ax_anim 2, 0, 59, 0, 20, 0, 20,
ax_anim 2, 0, 59, 1, 20, 1, 20,
ax_anim 2, 0, 56, 0, 6, 0, 6,
ax_anim_terminator
sQwilfishAnims_3_2:
ax_anim 2, 0, 61, -1, -1, -1, -1,
ax_anim 2, 0, 62, -2, -2, -2, -2,
ax_anim 2, 0, 61, -3, -3, -3, -3,
ax_anim 6, 0, 62, -3, -3, -3, -3,
ax_anim 1, 0, 60, 0, 0, 0, 0,
ax_anim 1, 2, 63, 4, 4, 4, 4,
ax_anim 1, 0, 63, 10, 10, 10, 10,
ax_anim 2, 0, 63, 22, 22, 22, 22,
ax_anim 2, 1, 63, 23, 21, 23, 21,
ax_anim 2, 0, 63, 22, 22, 22, 22,
ax_anim 2, 0, 63, 23, 21, 23, 21,
ax_anim 2, 0, 60, 6, 6, 6, 6,
ax_anim_terminator
sQwilfishAnims_3_3:
ax_anim 2, 0, 65, -1, 0, -1, 0,
ax_anim 2, 0, 66, -2, 0, -2, 0,
ax_anim 2, 0, 65, -3, 0, -3, 0,
ax_anim 6, 0, 66, -3, 0, -3, 0,
ax_anim 1, 0, 64, 0, 0, 0, 0,
ax_anim 1, 2, 67, 4, 0, 4, 0,
ax_anim 1, 0, 67, 10, 0, 10, 0,
ax_anim 2, 0, 67, 21, 0, 21, 0,
ax_anim 2, 1, 67, 21, 1, 21, 1,
ax_anim 2, 0, 67, 21, 0, 21, 0,
ax_anim 2, 0, 67, 21, 1, 21, 1,
ax_anim 2, 0, 64, 6, 0, 6, 0,
ax_anim_terminator
sQwilfishAnims_3_4:
ax_anim 2, 0, 69, -1, 1, -1, 1,
ax_anim 2, 0, 70, -2, 2, -2, 2,
ax_anim 2, 0, 69, -3, 3, -3, 3,
ax_anim 6, 0, 70, -3, 3, -3, 3,
ax_anim 1, 0, 68, 0, 0, 0, 0,
ax_anim 1, 2, 71, 4, -4, 4, -4,
ax_anim 1, 0, 71, 10, -10, 10, -10,
ax_anim 2, 0, 71, 19, -19, 19, -19,
ax_anim 2, 1, 71, 20, -18, 20, -18,
ax_anim 2, 0, 71, 19, -19, 19, -19,
ax_anim 2, 0, 71, 20, -18, 20, -18,
ax_anim 2, 0, 68, 6, -6, 6, -6,
ax_anim_terminator
sQwilfishAnims_3_5:
ax_anim 2, 0, 73, 0, 1, 0, 1,
ax_anim 2, 0, 74, 0, 2, 0, 2,
ax_anim 2, 0, 73, 0, 3, 0, 3,
ax_anim 6, 0, 74, 0, 3, 0, 3,
ax_anim 1, 0, 72, 0, 0, 0, 0,
ax_anim 1, 2, 75, 0, -4, 0, -4,
ax_anim 1, 0, 75, 0, -10, 0, -10,
ax_anim 2, 0, 75, 0, -22, 0, -22,
ax_anim 2, 1, 75, 1, -22, 1, -22,
ax_anim 2, 0, 75, 0, -22, 0, -22,
ax_anim 2, 0, 75, 1, -22, 1, -22,
ax_anim 2, 0, 72, 0, -6, 0, -6,
ax_anim_terminator
sQwilfishAnims_3_6:
ax_anim 2, 0, 77, 1, 1, 1, 1,
ax_anim 2, 0, 78, 2, 2, 2, 2,
ax_anim 2, 0, 77, 3, 3, 3, 3,
ax_anim 6, 0, 78, 3, 3, 3, 3,
ax_anim 1, 0, 76, 0, 0, 0, 0,
ax_anim 1, 2, 79, -4, -4, -4, -4,
ax_anim 1, 0, 79, -10, -10, -10, -10,
ax_anim 2, 0, 79, -19, -19, -19, -19,
ax_anim 2, 1, 79, -20, -18, -20, -18,
ax_anim 2, 0, 79, -19, -19, -19, -19,
ax_anim 2, 0, 79, -20, -18, -20, -18,
ax_anim 2, 0, 76, -6, -6, -6, -6,
ax_anim_terminator
sQwilfishAnims_3_7:
ax_anim 2, 0, 81, 1, 0, 1, 0,
ax_anim 2, 0, 82, 2, 0, 2, 0,
ax_anim 2, 0, 81, 3, 0, 3, 0,
ax_anim 6, 0, 82, 3, 0, 3, 0,
ax_anim 1, 0, 80, 0, 0, 0, 0,
ax_anim 1, 2, 83, -4, 0, -4, 0,
ax_anim 1, 0, 83, -10, 0, -10, 0,
ax_anim 2, 0, 83, -21, 0, -21, 0,
ax_anim 2, 1, 83, -21, 1, -21, 1,
ax_anim 2, 0, 83, -21, 0, -21, 0,
ax_anim 2, 0, 83, -21, 1, -21, 1,
ax_anim 2, 0, 80, -6, 0, -6, 0,
ax_anim_terminator
sQwilfishAnims_3_8:
ax_anim 2, 0, 85, 1, -1, 1, -1,
ax_anim 2, 0, 86, 2, -2, 2, -2,
ax_anim 2, 0, 85, 3, -3, 3, -3,
ax_anim 6, 0, 86, 3, -3, 3, -3,
ax_anim 1, 0, 84, 0, 0, 0, 0,
ax_anim 1, 2, 87, -4, 4, -4, 4,
ax_anim 1, 0, 87, -10, 10, -10, 10,
ax_anim 2, 0, 87, -22, 22, -22, 22,
ax_anim 2, 1, 87, -23, 21, -23, 21,
ax_anim 2, 0, 87, -22, 22, -22, 22,
ax_anim 2, 0, 87, -23, 21, -23, 21,
ax_anim 2, 0, 84, -6, 6, -6, 6,
ax_anim_terminator
.align 2
sQwilfishAnims_4_1:
ax_anim 2, 0, 90, 0, 0, 0, 0,
ax_anim 2, 0, 90, 0, 2, 0, 2,
ax_anim 2, 2, 93, 0, 3, 0, 3,
ax_anim 2, 0, 89, 0, 6, 0, 6,
ax_anim 2, 0, 88, 0, 7, 0, 7,
ax_anim 2, 0, 89, -1, 7, -1, 7,
ax_anim 2, 1, 88, 0, 7, 0, 7,
ax_anim 2, 0, 89, -1, 7, -1, 7,
ax_anim 2, 0, 88, 0, 7, 0, 7,
ax_anim 2, 0, 89, -1, 7, -1, 7,
ax_anim 2, 0, 88, 0, 7, 0, 7,
ax_anim 2, 0, 89, -1, 7, -1, 7,
ax_anim 2, 0, 88, 0, 7, 0, 7,
ax_anim 2, 0, 93, 0, 5, 0, 5,
ax_anim_terminator
sQwilfishAnims_4_2:
ax_anim 2, 0, 96, 0, 0, 0, 0,
ax_anim 2, 0, 96, 2, 2, 2, 2,
ax_anim 2, 2, 99, 3, 3, 3, 3,
ax_anim 2, 0, 95, 6, 6, 6, 6,
ax_anim 2, 0, 94, 7, 7, 7, 7,
ax_anim 2, 0, 95, 8, 6, 8, 6,
ax_anim 2, 1, 94, 7, 7, 7, 7,
ax_anim 2, 0, 95, 8, 6, 8, 6,
ax_anim 2, 0, 94, 7, 7, 7, 7,
ax_anim 2, 0, 95, 8, 6, 8, 6,
ax_anim 2, 0, 94, 7, 7, 7, 7,
ax_anim 2, 0, 95, 8, 6, 8, 6,
ax_anim 2, 0, 94, 7, 7, 7, 7,
ax_anim 2, 0, 99, 5, 5, 5, 5,
ax_anim_terminator
sQwilfishAnims_4_3:
ax_anim 2, 0, 102, 0, 0, 0, 0,
ax_anim 2, 0, 102, 2, 0, 2, 0,
ax_anim 2, 2, 105, 3, -1, 3, 0,
ax_anim 2, 0, 101, 6, 0, 6, 0,
ax_anim 2, 0, 100, 7, 0, 7, 0,
ax_anim 2, 0, 101, 8, 0, 8, 0,
ax_anim 2, 1, 100, 8, -1, 8, -1,
ax_anim 2, 0, 101, 8, 0, 8, 0,
ax_anim 2, 0, 100, 8, -1, 8, -1,
ax_anim 2, 0, 101, 8, 0, 8, 0,
ax_anim 2, 0, 100, 8, -1, 8, -1,
ax_anim 2, 0, 101, 8, 0, 8, 0,
ax_anim 2, 0, 100, 8, -1, 8, -1,
ax_anim 2, 0, 105, 5, -1, 5, 0,
ax_anim_terminator
sQwilfishAnims_4_4:
ax_anim 2, 0, 108, 0, 0, 0, 0,
ax_anim 2, 0, 108, 2, -2, 2, -2,
ax_anim 2, 2, 111, 3, -3, 3, -3,
ax_anim 2, 0, 107, 6, -6, 6, -6,
ax_anim 2, 0, 106, 7, -7, 7, -7,
ax_anim 2, 0, 107, 8, -6, 8, -6,
ax_anim 2, 1, 106, 7, -7, 7, -7,
ax_anim 2, 0, 107, 8, -6, 8, -6,
ax_anim 2, 0, 106, 7, -7, 7, -7,
ax_anim 2, 0, 107, 8, -6, 8, -6,
ax_anim 2, 0, 106, 7, -7, 7, -7,
ax_anim 2, 0, 107, 8, -6, 8, -6,
ax_anim 2, 0, 106, 7, -7, 7, -7,
ax_anim 2, 0, 111, 5, -5, 5, -5,
ax_anim_terminator
sQwilfishAnims_4_5:
ax_anim 2, 0, 114, 0, 0, 0, 0,
ax_anim 2, 0, 114, 0, -2, 0, -2,
ax_anim 2, 2, 117, 0, -3, 0, -3,
ax_anim 2, 0, 113, 0, -6, 0, -6,
ax_anim 2, 0, 112, 0, -7, 0, -7,
ax_anim 2, 0, 113, -1, -7, -1, -7,
ax_anim 2, 1, 112, 0, -7, 0, -7,
ax_anim 2, 0, 113, -1, -7, -1, -7,
ax_anim 2, 0, 112, 0, -7, 0, -7,
ax_anim 2, 0, 113, -1, -7, -1, -7,
ax_anim 2, 0, 112, 0, -7, 0, -7,
ax_anim 2, 0, 113, -1, -7, -1, -7,
ax_anim 2, 0, 112, 0, -7, 0, -7,
ax_anim 2, 0, 117, 0, -5, 0, -5,
ax_anim_terminator
sQwilfishAnims_4_6:
ax_anim 2, 0, 120, 0, 0, 0, 0,
ax_anim 2, 0, 120, -2, -2, -2, -2,
ax_anim 2, 2, 123, -3, -3, -3, -3,
ax_anim 2, 0, 119, -6, -6, -6, -6,
ax_anim 2, 0, 118, -7, -7, -7, -7,
ax_anim 2, 0, 119, -8, -6, -8, -6,
ax_anim 2, 1, 118, -7, -7, -7, -7,
ax_anim 2, 0, 119, -8, -6, -8, -6,
ax_anim 2, 0, 118, -7, -7, -7, -7,
ax_anim 2, 0, 119, -8, -6, -8, -6,
ax_anim 2, 0, 118, -7, -7, -7, -7,
ax_anim 2, 0, 119, -8, -6, -8, -6,
ax_anim 2, 0, 118, -7, -7, -7, -7,
ax_anim 2, 0, 123, -5, -5, -5, -5,
ax_anim_terminator
sQwilfishAnims_4_7:
ax_anim 2, 0, 126, 0, 0, 0, 0,
ax_anim 2, 0, 126, -2, 0, -2, 0,
ax_anim 2, 2, 129, -3, -1, -3, 0,
ax_anim 2, 0, 125, -6, 0, -6, 0,
ax_anim 2, 0, 124, -7, 0, -7, 0,
ax_anim 2, 0, 125, -8, 0, -8, 0,
ax_anim 2, 1, 124, -8, -1, -8, -1,
ax_anim 2, 0, 125, -8, 0, -8, 0,
ax_anim 2, 0, 124, -8, -1, -8, -1,
ax_anim 2, 0, 125, -8, 0, -8, 0,
ax_anim 2, 0, 124, -8, -1, -8, -1,
ax_anim 2, 0, 125, -8, 0, -8, 0,
ax_anim 2, 0, 124, -8, -1, -8, -1,
ax_anim 2, 0, 129, -5, -1, -5, 0,
ax_anim_terminator
sQwilfishAnims_4_8:
ax_anim 2, 0, 132, 0, 0, 0, 0,
ax_anim 2, 0, 132, -2, 2, -2, 2,
ax_anim 2, 2, 135, -3, 3, -3, 3,
ax_anim 2, 0, 131, -6, 6, -6, 6,
ax_anim 2, 0, 130, -7, 7, -7, 7,
ax_anim 2, 0, 131, -8, 6, -8, 6,
ax_anim 2, 1, 130, -7, 7, -7, 7,
ax_anim 2, 0, 131, -8, 6, -8, 6,
ax_anim 2, 0, 130, -7, 7, -7, 7,
ax_anim 2, 0, 131, -8, 6, -8, 6,
ax_anim 2, 0, 130, -7, 7, -7, 7,
ax_anim 2, 0, 131, -8, 6, -8, 6,
ax_anim 2, 0, 130, -7, 7, -7, 7,
ax_anim 2, 0, 135, -5, 5, -5, 5,
ax_anim_terminator
.align 2
sQwilfishAnims_5_1:
ax_anim 2, 0, 136, 0, -2, 0, 0,
ax_anim 2, 0, 136, 0, -4, 0, 0,
ax_anim 6, 0, 136, 0, -5, 0, 0,
ax_anim 2, 0, 137, 0, -6, 0, 0,
ax_anim 2, 0, 137, -1, -6, -1, 0,
ax_anim 2, 0, 137, 0, -6, 0, 0,
ax_anim 2, 0, 137, -1, -6, -1, 0,
ax_anim 2, 2, 137, 0, -6, 0, 0,
ax_anim 2, 0, 137, -1, -6, -1, 0,
ax_anim 2, 0, 137, 0, -6, 0, 0,
ax_anim 2, 0, 136, 0, -2, 0, 0,
ax_anim_terminator
sQwilfishAnims_5_2:
ax_anim 2, 0, 138, 0, -2, 0, 0,
ax_anim 2, 0, 138, 0, -4, 0, 0,
ax_anim 6, 0, 138, 0, -5, 0, 0,
ax_anim 2, 0, 139, 0, -5, 0, 0,
ax_anim 2, 0, 139, -1, -4, -1, 1,
ax_anim 2, 0, 139, 0, -5, 0, 0,
ax_anim 2, 0, 139, -1, -4, -1, 1,
ax_anim 2, 2, 139, 0, -5, 0, 0,
ax_anim 2, 0, 139, -1, -4, -1, 1,
ax_anim 2, 0, 139, 0, -5, 0, 0,
ax_anim 2, 0, 138, 0, -2, 0, 0,
ax_anim_terminator
sQwilfishAnims_5_3:
ax_anim 2, 0, 140, 0, -2, 0, 0,
ax_anim 2, 0, 140, 0, -4, 0, 0,
ax_anim 6, 0, 140, 0, -5, 0, 0,
ax_anim 2, 0, 141, 0, -5, 0, 0,
ax_anim 2, 0, 141, 0, -6, 0, -1,
ax_anim 2, 0, 141, 0, -5, 0, 0,
ax_anim 2, 0, 141, 0, -6, 0, -1,
ax_anim 2, 2, 141, 0, -5, 0, 0,
ax_anim 2, 0, 141, 0, -6, 0, -1,
ax_anim 2, 0, 141, 0, -5, 0, 0,
ax_anim 2, 0, 140, 0, -2, 0, 0,
ax_anim_terminator
sQwilfishAnims_5_4:
ax_anim 2, 0, 142, 0, -2, 0, 0,
ax_anim 2, 0, 142, 0, -4, 0, 0,
ax_anim 6, 0, 142, 0, -5, 0, 0,
ax_anim 2, 0, 143, -1, -5, 0, 0,
ax_anim 2, 0, 143, 1, -4, 1, 1,
ax_anim 2, 0, 143, -1, -5, 0, 0,
ax_anim 2, 0, 143, 1, -4, 1, 1,
ax_anim 2, 2, 143, -1, -5, 0, 0,
ax_anim 2, 0, 143, 1, -4, 1, 1,
ax_anim 2, 0, 143, -1, -5, 0, 0,
ax_anim 2, 0, 142, 0, -2, 0, 0,
ax_anim_terminator
sQwilfishAnims_5_5:
ax_anim 2, 0, 144, 0, -2, 0, 0,
ax_anim 2, 0, 144, 0, -4, 0, 0,
ax_anim 6, 0, 144, 0, -5, 0, 0,
ax_anim 2, 0, 145, 0, -5, 0, 0,
ax_anim 2, 0, 145, 1, -5, 1, 0,
ax_anim 2, 0, 145, 0, -5, 0, 0,
ax_anim 2, 0, 145, 1, -5, 1, 0,
ax_anim 2, 2, 145, 0, -5, 0, 0,
ax_anim 2, 0, 145, 1, -5, 1, 0,
ax_anim 2, 0, 145, 0, -5, 0, 0,
ax_anim 2, 0, 144, 0, -2, 0, 0,
ax_anim_terminator
sQwilfishAnims_5_6:
ax_anim 2, 0, 146, 0, -2, 0, 0,
ax_anim 2, 0, 146, 0, -4, 0, 0,
ax_anim 6, 0, 146, 0, -5, 0, 0,
ax_anim 2, 0, 147, 1, -5, 0, 0,
ax_anim 2, 0, 147, -1, -4, -1, 1,
ax_anim 2, 0, 147, 1, -5, 0, 0,
ax_anim 2, 0, 147, -1, -4, -1, 1,
ax_anim 2, 2, 147, 1, -5, 0, 0,
ax_anim 2, 0, 147, -1, -4, -1, 1,
ax_anim 2, 0, 147, 1, -5, 0, 0,
ax_anim 2, 0, 146, 0, -2, 0, 0,
ax_anim_terminator
sQwilfishAnims_5_7:
ax_anim 2, 0, 148, 0, -2, 0, 0,
ax_anim 2, 0, 148, 0, -4, 0, 0,
ax_anim 6, 0, 148, 0, -5, 0, 0,
ax_anim 2, 0, 149, 0, -5, 0, 0,
ax_anim 2, 0, 149, 0, -6, 0, -1,
ax_anim 2, 0, 149, 0, -5, 0, 0,
ax_anim 2, 0, 149, 0, -6, 0, -1,
ax_anim 2, 2, 149, 0, -5, 0, 0,
ax_anim 2, 0, 149, 0, -6, 0, -1,
ax_anim 2, 0, 149, 0, -5, 0, 0,
ax_anim 2, 0, 148, 0, -2, 0, 0,
ax_anim_terminator
sQwilfishAnims_5_8:
ax_anim 2, 0, 150, 0, -2, 0, 0,
ax_anim 2, 0, 150, 0, -4, 0, 0,
ax_anim 6, 0, 150, 0, -5, 0, 0,
ax_anim 2, 0, 151, 0, -5, 0, 0,
ax_anim 2, 0, 151, 1, -4, 1, 1,
ax_anim 2, 0, 151, 0, -5, 0, 0,
ax_anim 2, 0, 151, 1, -4, 1, 1,
ax_anim 2, 2, 151, 0, -5, 0, 0,
ax_anim 2, 0, 151, 1, -4, 1, 1,
ax_anim 2, 0, 151, 0, -5, 0, 0,
ax_anim 2, 0, 150, 0, -2, 0, 0,
ax_anim_terminator
.align 2
sQwilfishAnims_6_1:
ax_anim 8, 0, 152, 0, 0, 0, 0,
ax_anim 8, 0, 152, 0, -1, 0, 0,
ax_anim 26, 0, 152, 0, -2, 0, 0,
ax_anim 8, 0, 153, 0, -2, 0, 0,
ax_anim 8, 0, 153, 0, -1, 0, 0,
ax_anim 26, 0, 153, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sQwilfishAnims_7_1:
ax_anim 2, 0, 154, 0, -2, 0, -2,
ax_anim 8, 0, 154, 0, -3, 0, -3,
ax_anim_terminator
sQwilfishAnims_7_2:
ax_anim 2, 0, 155, -2, -2, -2, -2,
ax_anim 8, 0, 155, -3, -3, -3, -3,
ax_anim_terminator
sQwilfishAnims_7_3:
ax_anim 2, 0, 156, -2, 0, -2, 0,
ax_anim 8, 0, 156, -3, 0, -3, 0,
ax_anim_terminator
sQwilfishAnims_7_4:
ax_anim 2, 0, 157, -2, 2, -2, 2,
ax_anim 8, 0, 157, -3, 3, -3, 3,
ax_anim_terminator
sQwilfishAnims_7_5:
ax_anim 2, 0, 158, 0, 2, 0, 2,
ax_anim 8, 0, 158, 0, 3, 0, 3,
ax_anim_terminator
sQwilfishAnims_7_6:
ax_anim 2, 0, 159, 2, 2, 2, 2,
ax_anim 8, 0, 159, 3, 3, 3, 3,
ax_anim_terminator
sQwilfishAnims_7_7:
ax_anim 2, 0, 160, 2, 0, 2, 0,
ax_anim 8, 0, 160, 3, 0, 3, 0,
ax_anim_terminator
sQwilfishAnims_7_8:
ax_anim 2, 0, 161, 2, -2, 2, -2,
ax_anim 8, 0, 161, 3, -3, 3, -3,
ax_anim_terminator
.align 2
sQwilfishAnims_8_1:
ax_anim 12, 0, 162, 0, 0, 0, 0,
ax_anim 10, 0, 164, 0, -1, 0, 0,
ax_anim 10, 0, 164, 0, -2, 0, 0,
ax_anim 10, 0, 164, 0, -3, 0, 0,
ax_anim 12, 0, 162, 0, -3, 0, 0,
ax_anim 10, 0, 163, 0, -2, 0, 0,
ax_anim 10, 0, 163, 0, -1, 0, 0,
ax_anim_terminator
sQwilfishAnims_8_2:
ax_anim 12, 0, 166, 0, 0, 0, 0,
ax_anim 10, 0, 167, 0, -1, 0, 0,
ax_anim 10, 0, 167, 0, -2, 0, 0,
ax_anim 10, 0, 167, 0, -3, 0, 0,
ax_anim 12, 0, 166, 0, -3, 0, 0,
ax_anim 10, 0, 168, 0, -2, 0, 0,
ax_anim 10, 0, 168, 0, -1, 0, 0,
ax_anim_terminator
sQwilfishAnims_8_3:
ax_anim 12, 0, 170, 0, 0, 0, 0,
ax_anim 10, 0, 172, 0, -1, 0, 0,
ax_anim 10, 0, 172, 0, -2, 0, 0,
ax_anim 10, 0, 172, 0, -3, 0, 0,
ax_anim 12, 0, 170, 0, -3, 0, 0,
ax_anim 10, 0, 171, 0, -2, 0, 0,
ax_anim 10, 0, 171, 0, -1, 0, 0,
ax_anim_terminator
sQwilfishAnims_8_4:
ax_anim 12, 0, 174, 0, 0, 0, 0,
ax_anim 10, 0, 175, 0, -1, 0, 0,
ax_anim 10, 0, 175, 0, -2, 0, 0,
ax_anim 10, 0, 175, 0, -3, 0, 0,
ax_anim 12, 0, 174, 0, -3, 0, 0,
ax_anim 10, 0, 176, 0, -2, 0, 0,
ax_anim 10, 0, 176, 0, -1, 0, 0,
ax_anim_terminator
sQwilfishAnims_8_5:
ax_anim 12, 0, 178, 0, 0, 0, 0,
ax_anim 10, 0, 179, 0, -1, 0, 0,
ax_anim 10, 0, 179, 0, -2, 0, 0,
ax_anim 10, 0, 179, 0, -3, 0, 0,
ax_anim 12, 0, 178, 0, -3, 0, 0,
ax_anim 10, 0, 180, 0, -2, 0, 0,
ax_anim 10, 0, 180, 0, -1, 0, 0,
ax_anim_terminator
sQwilfishAnims_8_6:
ax_anim 12, 0, 182, 0, 0, 0, 0,
ax_anim 10, 0, 183, 0, -1, 0, 0,
ax_anim 10, 0, 183, 0, -2, 0, 0,
ax_anim 10, 0, 183, 0, -3, 0, 0,
ax_anim 12, 0, 182, 0, -3, 0, 0,
ax_anim 10, 0, 184, 0, -2, 0, 0,
ax_anim 10, 0, 184, 0, -1, 0, 0,
ax_anim_terminator
sQwilfishAnims_8_7:
ax_anim 12, 0, 186, 0, 0, 0, 0,
ax_anim 10, 0, 188, 0, -1, 0, 0,
ax_anim 10, 0, 188, 0, -2, 0, 0,
ax_anim 10, 0, 188, 0, -3, 0, 0,
ax_anim 12, 0, 186, 0, -3, 0, 0,
ax_anim 10, 0, 187, 0, -2, 0, 0,
ax_anim 10, 0, 187, 0, -1, 0, 0,
ax_anim_terminator
sQwilfishAnims_8_8:
ax_anim 12, 0, 190, 0, 0, 0, 0,
ax_anim 10, 0, 191, 0, -1, 0, 0,
ax_anim 10, 0, 191, 0, -2, 0, 0,
ax_anim 10, 0, 191, 0, -3, 0, 0,
ax_anim 12, 0, 190, 0, -3, 0, 0,
ax_anim 10, 0, 192, 0, -2, 0, 0,
ax_anim 10, 0, 192, 0, -1, 0, 0,
ax_anim_terminator
.align 2
sQwilfishAnims_9_1:
ax_anim 2, 0, 194, 0, 0, 0, 0,
ax_anim 1, 0, 195, 6, 3, 6, 3,
ax_anim 2, 0, 196, 8, 11, 8, 11,
ax_anim 2, 0, 197, 7, 19, 7, 19,
ax_anim 3, 0, 198, 0, 22, 0, 22,
ax_anim 2, 3, 199, -7, 19, -7, 19,
ax_anim 2, 0, 200, -8, 11, -8, 11,
ax_anim 1, 0, 201, -6, 3, -6, 3,
ax_anim 1, 0, 194, 0, 0, 0, 0,
ax_anim_terminator
sQwilfishAnims_9_2:
ax_anim 2, 0, 201, 0, 0, 0, 0,
ax_anim 1, 0, 194, 8, 0, 8, 0,
ax_anim 2, 0, 195, 17, 3, 17, 3,
ax_anim 2, 0, 196, 20, 15, 20, 15,
ax_anim 3, 0, 197, 21, 22, 21, 22,
ax_anim 2, 3, 198, 13, 23, 13, 23,
ax_anim 2, 0, 199, 4, 16, 4, 16,
ax_anim 1, 0, 200, 0, 7, 0, 7,
ax_anim 1, 0, 201, 0, 0, 0, 0,
ax_anim_terminator
sQwilfishAnims_9_3:
ax_anim 2, 0, 200, 0, 0, 0, 0,
ax_anim 1, 0, 201, 3, -5, 3, -5,
ax_anim 2, 0, 194, 11, -6, 11, -6,
ax_anim 2, 0, 195, 16, -5, 16, -5,
ax_anim 3, 0, 196, 20, 0, 20, 0,
ax_anim 2, 3, 197, 17, 5, 17, 5,
ax_anim 2, 0, 198, 12, 6, 12, 6,
ax_anim 1, 0, 199, 4, 4, 4, 4,
ax_anim 1, 0, 200, 0, 0, 0, 0,
ax_anim_terminator
sQwilfishAnims_9_4:
ax_anim 2, 0, 199, 0, 0, 0, 0,
ax_anim 1, 0, 200, 0, -8, 0, -8,
ax_anim 2, 0, 201, 4, -16, 4, -16,
ax_anim 2, 0, 194, 14, -22, 14, -22,
ax_anim 3, 0, 195, 22, -21, 22, -21,
ax_anim 2, 3, 196, 22, -13, 22, -13,
ax_anim 2, 0, 197, 17, -4, 17, -4,
ax_anim 1, 0, 198, 7, -1, 7, -1,
ax_anim 1, 0, 199, 0, 0, 0, 0,
ax_anim_terminator
sQwilfishAnims_9_5:
ax_anim 2, 0, 198, 0, 0, 0, 0,
ax_anim 1, 0, 199, -8, -4, -8, -4,
ax_anim 2, 0, 200, -9, -12, -9, -12,
ax_anim 2, 0, 201, -7, -18, -7, -18,
ax_anim 3, 0, 194, 0, -22, 0, -22,
ax_anim 2, 3, 195, 7, -18, 7, -18,
ax_anim 2, 0, 196, 9, -12, 9, -12,
ax_anim 1, 0, 197, 8, -4, 8, -4,
ax_anim 1, 0, 198, 0, 0, 0, 0,
ax_anim_terminator
sQwilfishAnims_9_6:
ax_anim 2, 0, 197, 0, 0, 0, 0,
ax_anim 1, 0, 196, 0, -8, 0, -8,
ax_anim 2, 0, 195, -4, -16, -4, -16,
ax_anim 2, 0, 194, -14, -22, -14, -22,
ax_anim 3, 0, 201, -22, -21, -22, -21,
ax_anim 2, 3, 200, -22, -13, -22, -13,
ax_anim 2, 0, 199, -17, -4, -17, -4,
ax_anim 1, 0, 198, -7, -1, -7, -1,
ax_anim 1, 0, 197, 0, 0, 0, 0,
ax_anim_terminator
sQwilfishAnims_9_7:
ax_anim 2, 0, 196, 0, 0, 0, 0,
ax_anim 1, 0, 195, -3, -5, -3, -5,
ax_anim 2, 0, 194, -11, -6, -11, -6,
ax_anim 2, 0, 201, -16, -5, -16, -5,
ax_anim 3, 0, 200, -20, 0, -20, 0,
ax_anim 2, 3, 199, -17, 5, -17, 5,
ax_anim 2, 0, 198, -12, 6, -12, 6,
ax_anim 1, 0, 197, -4, 6, -4, 6,
ax_anim 1, 0, 196, 0, 0, 0, 0,
ax_anim_terminator
sQwilfishAnims_9_8:
ax_anim 2, 0, 195, 0, 0, 0, 0,
ax_anim 1, 0, 194, -8, 0, -8, 0,
ax_anim 2, 0, 201, -17, 3, -17, 3,
ax_anim 2, 0, 200, -20, 15, -20, 15,
ax_anim 3, 0, 199, -21, 22, -21, 22,
ax_anim 2, 3, 198, -13, 23, -13, 23,
ax_anim 2, 0, 197, -4, 16, -4, 16,
ax_anim 1, 0, 196, 0, 7, 0, 7,
ax_anim 1, 0, 195, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sQwilfishAnims_10_1:
ax_anim 2, 0, 202, 0, 0, 0, 0,
ax_anim 2, 0, 202, 6, 0, 6, 0,
ax_anim 2, 0, 202, -6, 0, -6, 0,
ax_anim 2, 0, 202, 10, 0, 10, 0,
ax_anim 2, 0, 202, -10, 0, -10, 0,
ax_anim 2, 0, 202, 12, 0, 12, 0,
ax_anim 3, 0, 202, -12, 0, -12, 0,
ax_anim 3, 0, 202, 13, 0, 13, 0,
ax_anim 3, 0, 202, -13, 0, -13, 0,
ax_anim 2, 0, 202, 12, 0, 12, 0,
ax_anim 3, 0, 202, -12, 0, -12, 0,
ax_anim 2, 0, 202, 10, 0, 10, 0,
ax_anim 2, 0, 202, -10, 0, -10, 0,
ax_anim 2, 0, 202, 6, 0, 6, 0,
ax_anim 2, 0, 202, -6, 0, -6, 0,
ax_anim 2, 0, 202, 0, 0, 0, 0,
ax_anim_terminator
sQwilfishAnims_10_2:
ax_anim 2, 0, 203, 0, 0, 0, 0,
ax_anim 2, 0, 203, 6, -6, 6, -6,
ax_anim 2, 0, 203, -6, 6, -6, 6,
ax_anim 2, 0, 203, 10, -10, 10, -10,
ax_anim 2, 0, 203, -10, 10, -10, 10,
ax_anim 2, 0, 203, 12, -12, 12, -12,
ax_anim 3, 0, 203, -12, 12, -12, 12,
ax_anim 3, 0, 203, 13, -13, 13, -13,
ax_anim 3, 0, 203, -13, 13, -13, 13,
ax_anim 2, 0, 203, 12, -12, 12, -12,
ax_anim 3, 0, 203, -12, 12, -12, 12,
ax_anim 2, 0, 203, 10, -10, 10, -10,
ax_anim 2, 0, 203, -10, 10, -10, 10,
ax_anim 2, 0, 203, 6, -6, 6, -6,
ax_anim 2, 0, 203, -6, 6, -6, 6,
ax_anim 2, 0, 203, 0, 0, 0, 0,
ax_anim_terminator
sQwilfishAnims_10_3:
ax_anim 2, 0, 204, 0, 0, 0, 0,
ax_anim 2, 0, 204, 0, -6, 0, -6,
ax_anim 2, 0, 204, 0, 6, 0, 6,
ax_anim 2, 0, 204, 0, -10, 0, -10,
ax_anim 2, 0, 204, 0, 10, 0, 10,
ax_anim 2, 0, 204, 0, -12, 0, -12,
ax_anim 3, 0, 204, 0, 12, 0, 12,
ax_anim 3, 0, 204, 0, -13, 0, -13,
ax_anim 3, 0, 204, 0, 13, 0, 13,
ax_anim 2, 0, 204, 0, -12, 0, -12,
ax_anim 3, 0, 204, 0, 12, 0, 12,
ax_anim 2, 0, 204, 0, -10, 0, -10,
ax_anim 2, 0, 204, 0, 10, 0, 10,
ax_anim 2, 0, 204, 0, -6, 0, -6,
ax_anim 2, 0, 204, 0, 6, 0, 6,
ax_anim 2, 0, 204, 0, 0, 0, 0,
ax_anim_terminator
sQwilfishAnims_10_4:
ax_anim 2, 0, 205, 0, 0, 0, 0,
ax_anim 2, 0, 205, -6, -6, -6, -6,
ax_anim 2, 0, 205, 6, 6, 6, 6,
ax_anim 2, 0, 205, -10, -10, -10, -10,
ax_anim 2, 0, 205, 10, 10, 10, 10,
ax_anim 2, 0, 205, -12, -12, -12, -12,
ax_anim 3, 0, 205, 12, 12, 12, 12,
ax_anim 3, 0, 205, -13, -13, -13, -13,
ax_anim 3, 0, 205, 13, 13, 13, 13,
ax_anim 2, 0, 205, -12, -12, -12, -12,
ax_anim 3, 0, 205, 12, 12, 12, 12,
ax_anim 2, 0, 205, -10, -10, -10, -10,
ax_anim 2, 0, 205, 10, 10, 10, 10,
ax_anim 2, 0, 205, -6, -6, -6, -6,
ax_anim 2, 0, 205, 6, 6, 6, 6,
ax_anim 2, 0, 205, 0, 0, 0, 0,
ax_anim_terminator
sQwilfishAnims_10_5:
ax_anim 2, 0, 206, 0, 0, 0, 0,
ax_anim 2, 0, 206, 6, 0, 6, 0,
ax_anim 2, 0, 206, -6, 0, -6, 0,
ax_anim 2, 0, 206, 10, 0, 10, 0,
ax_anim 2, 0, 206, -10, 0, -10, 0,
ax_anim 2, 0, 206, 12, 0, 12, 0,
ax_anim 3, 0, 206, -12, 0, -12, 0,
ax_anim 3, 0, 206, 13, 0, 13, 0,
ax_anim 3, 0, 206, -13, 0, -13, 0,
ax_anim 2, 0, 206, 12, 0, 12, 0,
ax_anim 3, 0, 206, -12, 0, -12, 0,
ax_anim 2, 0, 206, 10, 0, 10, 0,
ax_anim 2, 0, 206, -10, 0, -10, 0,
ax_anim 2, 0, 206, 6, 0, 6, 0,
ax_anim 2, 0, 206, -6, 0, -6, 0,
ax_anim 2, 0, 206, 0, 0, 0, 0,
ax_anim_terminator
sQwilfishAnims_10_6:
ax_anim 2, 0, 207, 0, 0, 0, 0,
ax_anim 2, 0, 207, 6, -6, 6, -6,
ax_anim 2, 0, 207, -6, 6, -6, 6,
ax_anim 2, 0, 207, 10, -10, 10, -10,
ax_anim 2, 0, 207, -10, 10, -10, 10,
ax_anim 2, 0, 207, 12, -12, 12, -12,
ax_anim 3, 0, 207, -12, 12, -12, 12,
ax_anim 3, 0, 207, 13, -13, 13, -13,
ax_anim 3, 0, 207, -13, 13, -13, 13,
ax_anim 2, 0, 207, 12, -12, 12, -12,
ax_anim 3, 0, 207, -12, 12, -12, 12,
ax_anim 2, 0, 207, 10, -10, 10, -10,
ax_anim 2, 0, 207, -10, 10, -10, 10,
ax_anim 2, 0, 207, 6, -6, 6, -6,
ax_anim 2, 0, 207, -6, 6, -6, 6,
ax_anim 2, 0, 207, 0, 0, 0, 0,
ax_anim_terminator
sQwilfishAnims_10_7:
ax_anim 2, 0, 208, 0, 0, 0, 0,
ax_anim 2, 0, 208, 0, -6, 0, -6,
ax_anim 2, 0, 208, 0, 6, 0, 6,
ax_anim 2, 0, 208, 0, -10, 0, -10,
ax_anim 2, 0, 208, 0, 10, 0, 10,
ax_anim 2, 0, 208, 0, -12, 0, -12,
ax_anim 3, 0, 208, 0, 12, 0, 12,
ax_anim 3, 0, 208, 0, -13, 0, -13,
ax_anim 3, 0, 208, 0, 13, 0, 13,
ax_anim 2, 0, 208, 0, -12, 0, -12,
ax_anim 3, 0, 208, 0, 12, 0, 12,
ax_anim 2, 0, 208, 0, -10, 0, -10,
ax_anim 2, 0, 208, 0, 10, 0, 10,
ax_anim 2, 0, 208, 0, -6, 0, -6,
ax_anim 2, 0, 208, 0, 6, 0, 6,
ax_anim 2, 0, 208, 0, 0, 0, 0,
ax_anim_terminator
sQwilfishAnims_10_8:
ax_anim 2, 0, 209, 0, 0, 0, 0,
ax_anim 2, 0, 209, -6, -6, -6, -6,
ax_anim 2, 0, 209, 6, 6, 6, 6,
ax_anim 2, 0, 209, -10, -10, -10, -10,
ax_anim 2, 0, 209, 10, 10, 10, 10,
ax_anim 2, 0, 209, -12, -12, -12, -12,
ax_anim 3, 0, 209, 12, 12, 12, 12,
ax_anim 3, 0, 209, -13, -13, -13, -13,
ax_anim 3, 0, 209, 13, 13, 13, 13,
ax_anim 2, 0, 209, -12, -12, -12, -12,
ax_anim 3, 0, 209, 12, 12, 12, 12,
ax_anim 2, 0, 209, -10, -10, -10, -10,
ax_anim 2, 0, 209, 10, 10, 10, 10,
ax_anim 2, 0, 209, -6, -6, -6, -6,
ax_anim 2, 0, 209, 6, 6, 6, 6,
ax_anim 2, 0, 209, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sQwilfishAnims_11_1:
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 1, 0, 211, 0, -10, 0, 0,
ax_anim 2, 0, 211, 0, -16, 0, 0,
ax_anim 3, 0, 211, 0, -20, 0, 0,
ax_anim 4, 0, 211, 0, -21, 0, 0,
ax_anim 4, 0, 210, 0, -22, 0, 0,
ax_anim 3, 0, 212, 0, -21, 0, 0,
ax_anim 2, 0, 212, 0, -18, 0, 0,
ax_anim 1, 0, 212, 0, -12, 0, 0,
ax_anim 2, 2, 210, 0, 2, 0, 0,
ax_anim_terminator
sQwilfishAnims_11_2:
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 1, 0, 214, 0, -10, 0, 0,
ax_anim 2, 0, 214, 0, -16, 0, 0,
ax_anim 3, 0, 214, 0, -20, 0, 0,
ax_anim 4, 0, 214, 0, -21, 0, 0,
ax_anim 4, 0, 213, 0, -22, 0, 0,
ax_anim 3, 0, 215, 0, -21, 0, 0,
ax_anim 2, 0, 215, 0, -18, 0, 0,
ax_anim 1, 0, 215, 0, -12, 0, 0,
ax_anim 2, 2, 213, 0, 3, 0, 0,
ax_anim_terminator
sQwilfishAnims_11_3:
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 1, 0, 217, 0, -10, 0, 0,
ax_anim 2, 0, 217, 0, -16, 0, 0,
ax_anim 3, 0, 217, 0, -20, 0, 0,
ax_anim 4, 0, 217, 0, -21, 0, 0,
ax_anim 4, 0, 216, 0, -22, 0, 0,
ax_anim 3, 0, 218, 0, -21, 0, 0,
ax_anim 2, 0, 218, 0, -18, 0, 0,
ax_anim 1, 0, 218, 0, -12, 0, 0,
ax_anim 2, 2, 216, 0, 2, 0, 0,
ax_anim_terminator
sQwilfishAnims_11_4:
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 1, 0, 220, 0, -10, 0, 0,
ax_anim 2, 0, 220, 0, -16, 0, 0,
ax_anim 3, 0, 220, 0, -20, 0, 0,
ax_anim 4, 0, 220, 0, -21, 0, 0,
ax_anim 4, 0, 219, 0, -22, 0, 0,
ax_anim 3, 0, 221, 0, -21, 0, 0,
ax_anim 2, 0, 221, 0, -17, 0, 0,
ax_anim 1, 0, 221, 0, -11, 0, 0,
ax_anim 2, 2, 219, 0, 2, 0, 0,
ax_anim_terminator
sQwilfishAnims_11_5:
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 1, 0, 223, 0, -10, 0, 0,
ax_anim 2, 0, 223, 0, -16, 0, 0,
ax_anim 3, 0, 223, 0, -20, 0, 0,
ax_anim 4, 0, 223, 0, -21, 0, 0,
ax_anim 4, 0, 222, 0, -22, 0, 0,
ax_anim 3, 0, 224, 0, -21, 0, 0,
ax_anim 2, 0, 224, 0, -18, 0, 0,
ax_anim 1, 0, 224, 0, -12, 0, 0,
ax_anim 2, 2, 222, 0, 3, 0, 0,
ax_anim_terminator
sQwilfishAnims_11_6:
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 1, 0, 226, 0, -10, 0, 0,
ax_anim 2, 0, 226, 0, -16, 0, 0,
ax_anim 3, 0, 226, 0, -20, 0, 0,
ax_anim 4, 0, 226, 0, -21, 0, 0,
ax_anim 4, 0, 225, 0, -22, 0, 0,
ax_anim 3, 0, 227, 0, -21, 0, 0,
ax_anim 2, 0, 227, 0, -17, 0, 0,
ax_anim 1, 0, 227, 0, -11, 0, 0,
ax_anim 2, 2, 225, 0, 2, 0, 0,
ax_anim_terminator
sQwilfishAnims_11_7:
ax_anim 2, 0, 228, 0, 0, 0, 0,
ax_anim 1, 0, 229, 0, -10, 0, 0,
ax_anim 2, 0, 229, 0, -16, 0, 0,
ax_anim 3, 0, 229, 0, -20, 0, 0,
ax_anim 4, 0, 229, 0, -21, 0, 0,
ax_anim 4, 0, 228, 0, -22, 0, 0,
ax_anim 3, 0, 230, 0, -21, 0, 0,
ax_anim 2, 0, 230, 0, -18, 0, 0,
ax_anim 1, 0, 230, 0, -12, 0, 0,
ax_anim 2, 2, 228, 0, 2, 0, 0,
ax_anim_terminator
sQwilfishAnims_11_8:
ax_anim 2, 0, 231, 0, 0, 0, 0,
ax_anim 1, 0, 232, 0, -10, 0, 0,
ax_anim 2, 0, 232, 0, -16, 0, 0,
ax_anim 3, 0, 232, 0, -20, 0, 0,
ax_anim 4, 0, 232, 0, -21, 0, 0,
ax_anim 4, 0, 231, 0, -22, 0, 0,
ax_anim 3, 0, 233, 0, -21, 0, 0,
ax_anim 2, 0, 233, 0, -18, 0, 0,
ax_anim 1, 0, 233, 0, -12, 0, 0,
ax_anim 2, 2, 231, 0, 3, 0, 0,
ax_anim_terminator
.align 2
sQwilfishAnims_12_1:
ax_anim 2, 0, 234, 1, 0, 1, 0,
ax_anim 2, 0, 234, 0, 0, 0, 0,
ax_anim 2, 0, 234, 1, 0, 1, 0,
ax_anim 2, 0, 234, 0, 0, 0, 0,
ax_anim 2, 0, 234, 1, 0, 1, 0,
ax_anim 2, 2, 234, 0, 0, 0, 0,
ax_anim 2, 0, 234, 1, 0, 1, 0,
ax_anim 2, 0, 234, 0, 0, 0, 0,
ax_anim 2, 0, 234, 1, 0, 1, 0,
ax_anim 2, 1, 234, 0, 0, 0, 0,
ax_anim_terminator
sQwilfishAnims_12_2:
ax_anim 2, 0, 235, 1, -1, 1, -1,
ax_anim 2, 0, 235, 0, 0, 0, 0,
ax_anim 2, 0, 235, 1, -1, 1, -1,
ax_anim 2, 0, 235, 0, 0, 0, 0,
ax_anim 2, 0, 235, 1, -1, 1, -1,
ax_anim 2, 2, 235, 0, 0, 0, 0,
ax_anim 2, 0, 235, 1, -1, 1, -1,
ax_anim 2, 0, 235, 0, 0, 0, 0,
ax_anim 2, 0, 235, 1, -1, 1, -1,
ax_anim 2, 1, 235, 0, 0, 0, 0,
ax_anim_terminator
sQwilfishAnims_12_3:
ax_anim 2, 0, 236, 0, -1, 0, -1,
ax_anim 2, 0, 236, 0, 0, 0, 0,
ax_anim 2, 0, 236, 0, -1, 0, -1,
ax_anim 2, 0, 236, 0, 0, 0, 0,
ax_anim 2, 0, 236, 0, -1, 0, -1,
ax_anim 2, 2, 236, 0, 0, 0, 0,
ax_anim 2, 0, 236, 0, -1, 0, -1,
ax_anim 2, 0, 236, 0, 0, 0, 0,
ax_anim 2, 0, 236, 0, -1, 0, -1,
ax_anim 2, 1, 236, 0, 0, 0, 0,
ax_anim_terminator
sQwilfishAnims_12_4:
ax_anim 2, 0, 237, -1, -1, -1, -1,
ax_anim 2, 0, 237, 0, 0, 0, 0,
ax_anim 2, 0, 237, -1, -1, -1, -1,
ax_anim 2, 0, 237, 0, 0, 0, 0,
ax_anim 2, 0, 237, -1, -1, -1, -1,
ax_anim 2, 2, 237, 0, 0, 0, 0,
ax_anim 2, 0, 237, -1, -1, -1, -1,
ax_anim 2, 0, 237, 0, 0, 0, 0,
ax_anim 2, 0, 237, -1, -1, -1, -1,
ax_anim 2, 1, 237, 0, 0, 0, 0,
ax_anim_terminator
sQwilfishAnims_12_5:
ax_anim 2, 0, 238, 1, 0, 1, 0,
ax_anim 2, 0, 238, 0, 0, 0, 0,
ax_anim 2, 0, 238, 1, 0, 1, 0,
ax_anim 2, 0, 238, 0, 0, 0, 0,
ax_anim 2, 0, 238, 1, 0, 1, 0,
ax_anim 2, 2, 238, 0, 0, 0, 0,
ax_anim 2, 0, 238, 1, 0, 1, 0,
ax_anim 2, 0, 238, 0, 0, 0, 0,
ax_anim 2, 0, 238, 1, 0, 1, 0,
ax_anim 2, 1, 238, 0, 0, 0, 0,
ax_anim_terminator
sQwilfishAnims_12_6:
ax_anim 2, 0, 239, 1, -1, 1, -1,
ax_anim 2, 0, 239, 0, 0, 0, 0,
ax_anim 2, 0, 239, 1, -1, 1, -1,
ax_anim 2, 0, 239, 0, 0, 0, 0,
ax_anim 2, 0, 239, 1, -1, 1, -1,
ax_anim 2, 2, 239, 0, 0, 0, 0,
ax_anim 2, 0, 239, 1, -1, 1, -1,
ax_anim 2, 0, 239, 0, 0, 0, 0,
ax_anim 2, 0, 239, 1, -1, 1, -1,
ax_anim 2, 1, 239, 0, 0, 0, 0,
ax_anim_terminator
sQwilfishAnims_12_7:
ax_anim 2, 0, 240, 0, -1, 0, -1,
ax_anim 2, 0, 240, 0, 0, 0, 0,
ax_anim 2, 0, 240, 0, -1, 0, -1,
ax_anim 2, 0, 240, 0, 0, 0, 0,
ax_anim 2, 0, 240, 0, -1, 0, -1,
ax_anim 2, 2, 240, 0, 0, 0, 0,
ax_anim 2, 0, 240, 0, -1, 0, -1,
ax_anim 2, 0, 240, 0, 0, 0, 0,
ax_anim 2, 0, 240, 0, -1, 0, -1,
ax_anim 2, 1, 240, 0, 0, 0, 0,
ax_anim_terminator
sQwilfishAnims_12_8:
ax_anim 2, 0, 241, -1, -1, -1, -1,
ax_anim 2, 0, 241, 0, 0, 0, 0,
ax_anim 2, 0, 241, -1, -1, -1, -1,
ax_anim 2, 0, 241, 0, 0, 0, 0,
ax_anim 2, 0, 241, -1, -1, -1, -1,
ax_anim 2, 2, 241, 0, 0, 0, 0,
ax_anim 2, 0, 241, -1, -1, -1, -1,
ax_anim 2, 0, 241, 0, 0, 0, 0,
ax_anim 2, 0, 241, -1, -1, -1, -1,
ax_anim 2, 1, 241, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sQwilfishAnims_13_1:
ax_anim 2, 0, 242, 0, 0, 0, 0,
ax_anim 2, 0, 243, 0, 0, 0, 0,
ax_anim 2, 0, 244, 0, 0, 0, 0,
ax_anim 2, 0, 245, 0, 0, 0, 0,
ax_anim 2, 0, 246, 0, 0, 0, 0,
ax_anim 2, 0, 247, 0, 0, 0, 0,
ax_anim 2, 0, 248, 0, 0, 0, 0,
ax_anim 2, 0, 249, 0, 0, 0, 0,
ax_anim 2, 2, 242, 0, 0, 0, 0,
ax_anim_terminator
sQwilfishAnims_13_2:
ax_anim 2, 0, 249, 0, 0, 0, 0,
ax_anim 2, 0, 242, 0, 0, 0, 0,
ax_anim 2, 0, 243, 0, 0, 0, 0,
ax_anim 2, 0, 244, 0, 0, 0, 0,
ax_anim 2, 0, 245, 0, 0, 0, 0,
ax_anim 2, 0, 246, 0, 0, 0, 0,
ax_anim 2, 0, 247, 0, 0, 0, 0,
ax_anim 2, 0, 248, 0, 0, 0, 0,
ax_anim 2, 2, 249, 0, 0, 0, 0,
ax_anim_terminator
sQwilfishAnims_13_3:
ax_anim 2, 0, 248, 0, 0, 0, 0,
ax_anim 2, 0, 249, 0, 0, 0, 0,
ax_anim 2, 0, 242, 0, 0, 0, 0,
ax_anim 2, 0, 243, 0, 0, 0, 0,
ax_anim 2, 0, 244, 0, 0, 0, 0,
ax_anim 2, 0, 245, 0, 0, 0, 0,
ax_anim 2, 0, 246, 0, 0, 0, 0,
ax_anim 2, 0, 247, 0, 0, 0, 0,
ax_anim 2, 2, 248, 0, 0, 0, 0,
ax_anim_terminator
sQwilfishAnims_13_4:
ax_anim 2, 0, 247, 0, 0, 0, 0,
ax_anim 2, 0, 248, 0, 0, 0, 0,
ax_anim 2, 0, 249, 0, 0, 0, 0,
ax_anim 2, 0, 242, 0, 0, 0, 0,
ax_anim 2, 0, 243, 0, 0, 0, 0,
ax_anim 2, 0, 244, 0, 0, 0, 0,
ax_anim 2, 0, 245, 0, 0, 0, 0,
ax_anim 2, 0, 246, 0, 0, 0, 0,
ax_anim 2, 2, 247, 0, 0, 0, 0,
ax_anim_terminator
sQwilfishAnims_13_5:
ax_anim 2, 0, 246, 0, 0, 0, 0,
ax_anim 2, 0, 247, 0, 0, 0, 0,
ax_anim 2, 0, 248, 0, 0, 0, 0,
ax_anim 2, 0, 249, 0, 0, 0, 0,
ax_anim 2, 0, 242, 0, 0, 0, 0,
ax_anim 2, 0, 243, 0, 0, 0, 0,
ax_anim 2, 0, 244, 0, 0, 0, 0,
ax_anim 2, 0, 245, 0, 0, 0, 0,
ax_anim 2, 2, 246, 0, 0, 0, 0,
ax_anim_terminator
sQwilfishAnims_13_6:
ax_anim 2, 0, 245, 0, 0, 0, 0,
ax_anim 2, 0, 246, 0, 0, 0, 0,
ax_anim 2, 0, 247, 0, 0, 0, 0,
ax_anim 2, 0, 248, 0, 0, 0, 0,
ax_anim 2, 0, 249, 0, 0, 0, 0,
ax_anim 2, 0, 242, 0, 0, 0, 0,
ax_anim 2, 0, 243, 0, 0, 0, 0,
ax_anim 2, 0, 244, 0, 0, 0, 0,
ax_anim 2, 2, 245, 0, 0, 0, 0,
ax_anim_terminator
sQwilfishAnims_13_7:
ax_anim 2, 0, 244, 0, 0, 0, 0,
ax_anim 2, 0, 245, 0, 0, 0, 0,
ax_anim 2, 0, 246, 0, 0, 0, 0,
ax_anim 2, 0, 247, 0, 0, 0, 0,
ax_anim 2, 0, 248, 0, 0, 0, 0,
ax_anim 2, 0, 249, 0, 0, 0, 0,
ax_anim 2, 0, 242, 0, 0, 0, 0,
ax_anim 2, 0, 243, 0, 0, 0, 0,
ax_anim 2, 2, 244, 0, 0, 0, 0,
ax_anim_terminator
sQwilfishAnims_13_8:
ax_anim 2, 0, 243, 0, 0, 0, 0,
ax_anim 2, 0, 244, 0, 0, 0, 0,
ax_anim 2, 0, 245, 0, 0, 0, 0,
ax_anim 2, 0, 246, 0, 0, 0, 0,
ax_anim 2, 0, 247, 0, 0, 0, 0,
ax_anim 2, 0, 248, 0, 0, 0, 0,
ax_anim 2, 0, 249, 0, 0, 0, 0,
ax_anim 2, 0, 242, 0, 0, 0, 0,
ax_anim 2, 2, 243, 0, 0, 0, 0,
ax_anim_terminator
sQwilfishGfx1:
.incbin "baserom.gba", 0xE87490, 0x100
sQwilfishSprites1:
ax_sprite sQwilfishGfx1, 0x100
ax_sprite_terminator
sQwilfishGfx2:
.incbin "baserom.gba", 0xE875A0, 0x100
sQwilfishSprites2:
ax_sprite sQwilfishGfx2, 0x100
ax_sprite_terminator
sQwilfishGfx3:
.incbin "baserom.gba", 0xE876B0, 0x100
sQwilfishSprites3:
ax_sprite sQwilfishGfx3, 0x100
ax_sprite_terminator
sQwilfishGfx4:
.incbin "baserom.gba", 0xE877C0, 0x200
sQwilfishSprites4:
ax_sprite sQwilfishGfx4, 0x200
ax_sprite_terminator
sQwilfishGfx5:
.incbin "baserom.gba", 0xE879D0, 0x200
sQwilfishSprites5:
ax_sprite sQwilfishGfx5, 0x200
ax_sprite_terminator
sQwilfishGfx6:
.incbin "baserom.gba", 0xE87BE0, 0x200
sQwilfishSprites6:
ax_sprite sQwilfishGfx6, 0x200
ax_sprite_terminator
sQwilfishGfx7:
.incbin "baserom.gba", 0xE87DF0, 0x200
sQwilfishSprites7:
ax_sprite sQwilfishGfx7, 0x200
ax_sprite_terminator
sQwilfishGfx8:
.incbin "baserom.gba", 0xE88000, 0x200
sQwilfishSprites8:
ax_sprite sQwilfishGfx8, 0x200
ax_sprite_terminator
sQwilfishGfx9:
.incbin "baserom.gba", 0xE88210, 0x200
sQwilfishSprites9:
ax_sprite sQwilfishGfx9, 0x200
ax_sprite_terminator
sQwilfishGfx10:
.incbin "baserom.gba", 0xE88420, 0x200
sQwilfishSprites10:
ax_sprite sQwilfishGfx10, 0x200
ax_sprite_terminator
sQwilfishGfx11:
.incbin "baserom.gba", 0xE88630, 0x200
sQwilfishSprites11:
ax_sprite sQwilfishGfx11, 0x200
ax_sprite_terminator
sQwilfishGfx12:
.incbin "baserom.gba", 0xE88840, 0x200
sQwilfishSprites12:
ax_sprite sQwilfishGfx12, 0x200
ax_sprite_terminator
sQwilfishGfx13:
.incbin "baserom.gba", 0xE88A50, 0x100
sQwilfishSprites13:
ax_sprite sQwilfishGfx13, 0x100
ax_sprite_terminator
sQwilfishGfx14:
.incbin "baserom.gba", 0xE88B60, 0x100
sQwilfishSprites14:
ax_sprite sQwilfishGfx14, 0x100
ax_sprite_terminator
sQwilfishGfx15:
.incbin "baserom.gba", 0xE88C70, 0x100
sQwilfishSprites15:
ax_sprite sQwilfishGfx15, 0x100
ax_sprite_terminator
sQwilfishGfx16:
.incbin "baserom.gba", 0xE88D80, 0xC0
sQwilfishSprites16:
ax_sprite sQwilfishGfx16, 0xc0
ax_sprite 0, 0x40
ax_sprite_terminator
sQwilfishGfx17:
.incbin "baserom.gba", 0xE88E58, 0x20
sQwilfishSprites17:
ax_sprite sQwilfishGfx17, 0x20
ax_sprite_terminator
sQwilfishGfx18:
.incbin "baserom.gba", 0xE88E88, 0xC0
sQwilfishSprites18:
ax_sprite 0, 0x40
ax_sprite sQwilfishGfx18, 0xc0
ax_sprite_terminator
sQwilfishGfx19:
.incbin "baserom.gba", 0xE88F60, 0x20
sQwilfishSprites19:
ax_sprite sQwilfishGfx19, 0x20
ax_sprite_terminator
sQwilfishGfx20:
.incbin "baserom.gba", 0xE88F90, 0x60
sQwilfishGfx20_1:
.incbin "baserom.gba", 0xE88FF0, 0xE0
sQwilfishGfx20_2:
.incbin "baserom.gba", 0xE890D0, 0x20
sQwilfishSprites20:
ax_sprite sQwilfishGfx20, 0x60
ax_sprite 0, 0x20
ax_sprite sQwilfishGfx20_1, 0xe0
ax_sprite 0, 0x20
ax_sprite sQwilfishGfx20_2, 0x20
ax_sprite 0, 0x60
ax_sprite_terminator
sQwilfishGfx21:
.incbin "baserom.gba", 0xE89128, 0xC0
sQwilfishSprites21:
ax_sprite sQwilfishGfx21, 0xc0
ax_sprite 0, 0x40
ax_sprite_terminator
sQwilfishGfx22:
.incbin "baserom.gba", 0xE89200, 0x40
sQwilfishSprites22:
ax_sprite sQwilfishGfx22, 0x40
ax_sprite_terminator
sQwilfishGfx23:
.incbin "baserom.gba", 0xE89250, 0x80
sQwilfishSprites23:
ax_sprite sQwilfishGfx23, 0x80
ax_sprite_terminator
sQwilfishGfx24:
.incbin "baserom.gba", 0xE892E0, 0x40
sQwilfishSprites24:
ax_sprite sQwilfishGfx24, 0x40
ax_sprite_terminator
sQwilfishGfx25:
.incbin "baserom.gba", 0xE89330, 0x40
sQwilfishGfx25_1:
.incbin "baserom.gba", 0xE89370, 0x60
sQwilfishGfx25_2:
.incbin "baserom.gba", 0xE893D0, 0x60
sQwilfishGfx25_3:
.incbin "baserom.gba", 0xE89430, 0x60
sQwilfishSprites25:
ax_sprite sQwilfishGfx25, 0x40
ax_sprite 0, 0x40
ax_sprite sQwilfishGfx25_1, 0x60
ax_sprite 0, 0x20
ax_sprite sQwilfishGfx25_2, 0x60
ax_sprite 0, 0x20
ax_sprite sQwilfishGfx25_3, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sQwilfishGfx26:
.incbin "baserom.gba", 0xE894D8, 0x40
sQwilfishGfx26_1:
.incbin "baserom.gba", 0xE89518, 0x60
sQwilfishGfx26_2:
.incbin "baserom.gba", 0xE89578, 0xE0
sQwilfishSprites26:
ax_sprite 0, 0x20
ax_sprite sQwilfishGfx26, 0x40
ax_sprite 0, 0x20
ax_sprite sQwilfishGfx26_1, 0x60
ax_sprite 0, 0x20
ax_sprite sQwilfishGfx26_2, 0xe0
ax_sprite 0, 0x20
ax_sprite_terminator
sQwilfishGfx27:
.incbin "baserom.gba", 0xE89698, 0x60
sQwilfishGfx27_1:
.incbin "baserom.gba", 0xE896F8, 0x60
sQwilfishGfx27_2:
.incbin "baserom.gba", 0xE89758, 0x60
sQwilfishGfx27_3:
.incbin "baserom.gba", 0xE897B8, 0x20
sQwilfishSprites27:
ax_sprite sQwilfishGfx27, 0x60
ax_sprite 0, 0x20
ax_sprite sQwilfishGfx27_1, 0x60
ax_sprite 0, 0x20
ax_sprite sQwilfishGfx27_2, 0x60
ax_sprite 0, 0x40
ax_sprite sQwilfishGfx27_3, 0x20
ax_sprite 0, 0x40
ax_sprite_terminator
sQwilfishGfx28:
.incbin "baserom.gba", 0xE89820, 0x160
sQwilfishGfx28_1:
.incbin "baserom.gba", 0xE89980, 0x20
sQwilfishSprites28:
ax_sprite sQwilfishGfx28, 0x160
ax_sprite 0, 0x40
ax_sprite sQwilfishGfx28_1, 0x20
ax_sprite 0, 0x40
ax_sprite_terminator
sQwilfishGfx29:
.incbin "baserom.gba", 0xE899C8, 0x60
sQwilfishGfx29_1:
.incbin "baserom.gba", 0xE89A28, 0xE0
sQwilfishGfx29_2:
.incbin "baserom.gba", 0xE89B08, 0x40
sQwilfishSprites29:
ax_sprite sQwilfishGfx29, 0x60
ax_sprite 0, 0x20
ax_sprite sQwilfishGfx29_1, 0xe0
ax_sprite 0, 0x20
ax_sprite sQwilfishGfx29_2, 0x40
ax_sprite 0, 0x40
ax_sprite_terminator
sQwilfishGfx30:
.incbin "baserom.gba", 0xE89B80, 0x40
sQwilfishGfx30_1:
.incbin "baserom.gba", 0xE89BC0, 0x60
sQwilfishGfx30_2:
.incbin "baserom.gba", 0xE89C20, 0xC0
sQwilfishSprites30:
ax_sprite sQwilfishGfx30, 0x40
ax_sprite 0, 0x40
ax_sprite sQwilfishGfx30_1, 0x60
ax_sprite 0, 0x20
ax_sprite sQwilfishGfx30_2, 0xc0
ax_sprite 0, 0x40
ax_sprite_terminator
sQwilfishGfx31:
.incbin "baserom.gba", 0xE89D18, 0x60
sQwilfishGfx31_1:
.incbin "baserom.gba", 0xE89D78, 0x140
sQwilfishSprites31:
ax_sprite sQwilfishGfx31, 0x60
ax_sprite 0, 0x20
ax_sprite sQwilfishGfx31_1, 0x140
ax_sprite 0, 0x40
ax_sprite_terminator
sQwilfishGfx32:
.incbin "baserom.gba", 0xE89EE0, 0x60
sQwilfishGfx32_1:
.incbin "baserom.gba", 0xE89F40, 0x60
sQwilfishGfx32_2:
.incbin "baserom.gba", 0xE89FA0, 0x60
sQwilfishGfx32_3:
.incbin "baserom.gba", 0xE8A000, 0x40
sQwilfishSprites32:
ax_sprite sQwilfishGfx32, 0x60
ax_sprite 0, 0x20
ax_sprite sQwilfishGfx32_1, 0x60
ax_sprite 0, 0x20
ax_sprite sQwilfishGfx32_2, 0x60
ax_sprite 0, 0x40
ax_sprite sQwilfishGfx32_3, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sQwilfishGfx33:
.incbin "baserom.gba", 0xE8A088, 0x60
sQwilfishGfx33_1:
.incbin "baserom.gba", 0xE8A0E8, 0x60
sQwilfishGfx33_2:
.incbin "baserom.gba", 0xE8A148, 0xE0
sQwilfishSprites33:
ax_sprite sQwilfishGfx33, 0x60
ax_sprite 0, 0x20
ax_sprite sQwilfishGfx33_1, 0x60
ax_sprite 0, 0x20
ax_sprite sQwilfishGfx33_2, 0xe0
ax_sprite 0, 0x20
ax_sprite_terminator
sQwilfishGfx34:
.incbin "baserom.gba", 0xE8A260, 0x60
sQwilfishGfx34_1:
.incbin "baserom.gba", 0xE8A2C0, 0x60
sQwilfishGfx34_2:
.incbin "baserom.gba", 0xE8A320, 0x60
sQwilfishGfx34_3:
.incbin "baserom.gba", 0xE8A380, 0x40
sQwilfishSprites34:
ax_sprite sQwilfishGfx34, 0x60
ax_sprite 0, 0x20
ax_sprite sQwilfishGfx34_1, 0x60
ax_sprite 0, 0x20
ax_sprite sQwilfishGfx34_2, 0x60
ax_sprite 0, 0x40
ax_sprite sQwilfishGfx34_3, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sQwilfishGfx35:
.incbin "baserom.gba", 0xE8A408, 0x80
sQwilfishSprites35:
ax_sprite sQwilfishGfx35, 0x80
ax_sprite_terminator
sQwilfishGfx36:
.incbin "baserom.gba", 0xE8A498, 0x80
sQwilfishSprites36:
ax_sprite sQwilfishGfx36, 0x80
ax_sprite_terminator
sQwilfishGfx37:
.incbin "baserom.gba", 0xE8A528, 0x80
sQwilfishSprites37:
ax_sprite sQwilfishGfx37, 0x80
ax_sprite_terminator
sQwilfishGfx38:
.incbin "baserom.gba", 0xE8A5B8, 0x40
sQwilfishSprites38:
ax_sprite sQwilfishGfx38, 0x40
ax_sprite_terminator
sQwilfishGfx39:
.incbin "baserom.gba", 0xE8A608, 0x80
sQwilfishSprites39:
ax_sprite sQwilfishGfx39, 0x80
ax_sprite_terminator
sQwilfishGfx40:
.incbin "baserom.gba", 0xE8A698, 0x80
sQwilfishSprites40:
ax_sprite sQwilfishGfx40, 0x80
ax_sprite_terminator
sQwilfishGfx41:
.incbin "baserom.gba", 0xE8A728, 0x100
sQwilfishSprites41:
ax_sprite sQwilfishGfx41, 0x100
ax_sprite_terminator
sQwilfishGfx42:
.incbin "baserom.gba", 0xE8A838, 0x100
sQwilfishSprites42:
ax_sprite sQwilfishGfx42, 0x100
ax_sprite_terminator
sQwilfishGfx43:
.incbin "baserom.gba", 0xE8A948, 0x200
sQwilfishSprites43:
ax_sprite sQwilfishGfx43, 0x200
ax_sprite_terminator
sQwilfishGfx44:
.incbin "baserom.gba", 0xE8AB58, 0x200
sQwilfishSprites44:
ax_sprite sQwilfishGfx44, 0x200
ax_sprite_terminator
sQwilfishGfx45:
.incbin "baserom.gba", 0xE8AD68, 0x200
sQwilfishSprites45:
ax_sprite sQwilfishGfx45, 0x200
ax_sprite_terminator
sQwilfishGfx46:
.incbin "baserom.gba", 0xE8AF78, 0x200
sQwilfishSprites46:
ax_sprite sQwilfishGfx46, 0x200
ax_sprite_terminator
sQwilfishGfx47:
.incbin "baserom.gba", 0xE8B188, 0x200
sQwilfishSprites47:
ax_sprite sQwilfishGfx47, 0x200
ax_sprite_terminator
sAxPosesQwilfish:
.4byte sQwilfishPose1
.4byte sQwilfishPose2
.4byte sQwilfishPose3
.4byte sQwilfishPose4
.4byte sQwilfishPose5
.4byte sQwilfishPose6
.4byte sQwilfishPose7
.4byte sQwilfishPose8
.4byte sQwilfishPose9
.4byte sQwilfishPose10
.4byte sQwilfishPose11
.4byte sQwilfishPose12
.4byte sQwilfishPose13
.4byte sQwilfishPose14
.4byte sQwilfishPose15
.4byte sQwilfishPose16
.4byte sQwilfishPose17
.4byte sQwilfishPose18
.4byte sQwilfishPose19
.4byte sQwilfishPose20
.4byte sQwilfishPose21
.4byte sQwilfishPose22
.4byte sQwilfishPose23
.4byte sQwilfishPose24
.4byte sQwilfishPose25
.4byte sQwilfishPose26
.4byte sQwilfishPose27
.4byte sQwilfishPose28
.4byte sQwilfishPose29
.4byte sQwilfishPose30
.4byte sQwilfishPose31
.4byte sQwilfishPose32
.4byte sQwilfishPose33
.4byte sQwilfishPose34
.4byte sQwilfishPose35
.4byte sQwilfishPose36
.4byte sQwilfishPose37
.4byte sQwilfishPose38
.4byte sQwilfishPose39
.4byte sQwilfishPose40
.4byte sQwilfishPose41
.4byte sQwilfishPose42
.4byte sQwilfishPose43
.4byte sQwilfishPose44
.4byte sQwilfishPose45
.4byte sQwilfishPose46
.4byte sQwilfishPose47
.4byte sQwilfishPose48
.4byte sQwilfishPose49
.4byte sQwilfishPose50
.4byte sQwilfishPose51
.4byte sQwilfishPose52
.4byte sQwilfishPose53
.4byte sQwilfishPose54
.4byte sQwilfishPose55
.4byte sQwilfishPose56
.4byte sQwilfishPose57
.4byte sQwilfishPose58
.4byte sQwilfishPose59
.4byte sQwilfishPose60
.4byte sQwilfishPose61
.4byte sQwilfishPose62
.4byte sQwilfishPose63
.4byte sQwilfishPose64
.4byte sQwilfishPose65
.4byte sQwilfishPose66
.4byte sQwilfishPose67
.4byte sQwilfishPose68
.4byte sQwilfishPose69
.4byte sQwilfishPose70
.4byte sQwilfishPose71
.4byte sQwilfishPose72
.4byte sQwilfishPose73
.4byte sQwilfishPose74
.4byte sQwilfishPose75
.4byte sQwilfishPose76
.4byte sQwilfishPose77
.4byte sQwilfishPose78
.4byte sQwilfishPose79
.4byte sQwilfishPose80
.4byte sQwilfishPose81
.4byte sQwilfishPose82
.4byte sQwilfishPose83
.4byte sQwilfishPose84
.4byte sQwilfishPose85
.4byte sQwilfishPose86
.4byte sQwilfishPose87
.4byte sQwilfishPose88
.4byte sQwilfishPose89
.4byte sQwilfishPose90
.4byte sQwilfishPose91
.4byte sQwilfishPose92
.4byte sQwilfishPose93
.4byte sQwilfishPose94
.4byte sQwilfishPose95
.4byte sQwilfishPose96
.4byte sQwilfishPose97
.4byte sQwilfishPose98
.4byte sQwilfishPose99
.4byte sQwilfishPose100
.4byte sQwilfishPose101
.4byte sQwilfishPose102
.4byte sQwilfishPose103
.4byte sQwilfishPose104
.4byte sQwilfishPose105
.4byte sQwilfishPose106
.4byte sQwilfishPose107
.4byte sQwilfishPose108
.4byte sQwilfishPose109
.4byte sQwilfishPose110
.4byte sQwilfishPose111
.4byte sQwilfishPose112
.4byte sQwilfishPose113
.4byte sQwilfishPose114
.4byte sQwilfishPose115
.4byte sQwilfishPose116
.4byte sQwilfishPose117
.4byte sQwilfishPose118
.4byte sQwilfishPose119
.4byte sQwilfishPose120
.4byte sQwilfishPose121
.4byte sQwilfishPose122
.4byte sQwilfishPose123
.4byte sQwilfishPose124
.4byte sQwilfishPose125
.4byte sQwilfishPose126
.4byte sQwilfishPose127
.4byte sQwilfishPose128
.4byte sQwilfishPose129
.4byte sQwilfishPose130
.4byte sQwilfishPose131
.4byte sQwilfishPose132
.4byte sQwilfishPose133
.4byte sQwilfishPose134
.4byte sQwilfishPose135
.4byte sQwilfishPose136
.4byte sQwilfishPose137
.4byte sQwilfishPose138
.4byte sQwilfishPose139
.4byte sQwilfishPose140
.4byte sQwilfishPose141
.4byte sQwilfishPose142
.4byte sQwilfishPose143
.4byte sQwilfishPose144
.4byte sQwilfishPose145
.4byte sQwilfishPose146
.4byte sQwilfishPose147
.4byte sQwilfishPose148
.4byte sQwilfishPose149
.4byte sQwilfishPose150
.4byte sQwilfishPose151
.4byte sQwilfishPose152
.4byte sQwilfishPose153
.4byte sQwilfishPose154
.4byte sQwilfishPose155
.4byte sQwilfishPose156
.4byte sQwilfishPose157
.4byte sQwilfishPose158
.4byte sQwilfishPose159
.4byte sQwilfishPose160
.4byte sQwilfishPose161
.4byte sQwilfishPose162
.4byte sQwilfishPose163
.4byte sQwilfishPose164
.4byte sQwilfishPose165
.4byte sQwilfishPose166
.4byte sQwilfishPose167
.4byte sQwilfishPose168
.4byte sQwilfishPose169
.4byte sQwilfishPose170
.4byte sQwilfishPose171
.4byte sQwilfishPose172
.4byte sQwilfishPose173
.4byte sQwilfishPose174
.4byte sQwilfishPose175
.4byte sQwilfishPose176
.4byte sQwilfishPose177
.4byte sQwilfishPose178
.4byte sQwilfishPose179
.4byte sQwilfishPose180
.4byte sQwilfishPose181
.4byte sQwilfishPose182
.4byte sQwilfishPose183
.4byte sQwilfishPose184
.4byte sQwilfishPose185
.4byte sQwilfishPose186
.4byte sQwilfishPose187
.4byte sQwilfishPose188
.4byte sQwilfishPose189
.4byte sQwilfishPose190
.4byte sQwilfishPose191
.4byte sQwilfishPose192
.4byte sQwilfishPose193
.4byte sQwilfishPose194
.4byte sQwilfishPose195
.4byte sQwilfishPose196
.4byte sQwilfishPose197
.4byte sQwilfishPose198
.4byte sQwilfishPose199
.4byte sQwilfishPose200
.4byte sQwilfishPose201
.4byte sQwilfishPose202
.4byte sQwilfishPose203
.4byte sQwilfishPose204
.4byte sQwilfishPose205
.4byte sQwilfishPose206
.4byte sQwilfishPose207
.4byte sQwilfishPose208
.4byte sQwilfishPose209
.4byte sQwilfishPose210
.4byte sQwilfishPose211
.4byte sQwilfishPose212
.4byte sQwilfishPose213
.4byte sQwilfishPose214
.4byte sQwilfishPose215
.4byte sQwilfishPose216
.4byte sQwilfishPose217
.4byte sQwilfishPose218
.4byte sQwilfishPose219
.4byte sQwilfishPose220
.4byte sQwilfishPose221
.4byte sQwilfishPose222
.4byte sQwilfishPose223
.4byte sQwilfishPose224
.4byte sQwilfishPose225
.4byte sQwilfishPose226
.4byte sQwilfishPose227
.4byte sQwilfishPose228
.4byte sQwilfishPose229
.4byte sQwilfishPose230
.4byte sQwilfishPose231
.4byte sQwilfishPose232
.4byte sQwilfishPose233
.4byte sQwilfishPose234
.4byte sQwilfishPose235
.4byte sQwilfishPose236
.4byte sQwilfishPose237
.4byte sQwilfishPose238
.4byte sQwilfishPose239
.4byte sQwilfishPose240
.4byte sQwilfishPose241
.4byte sQwilfishPose242
.4byte sQwilfishPose243
.4byte sQwilfishPose244
.4byte sQwilfishPose245
.4byte sQwilfishPose246
.4byte sQwilfishPose247
.4byte sQwilfishPose248
.4byte sQwilfishPose249
.4byte sQwilfishPose250
sAxPositionsQwilfish:
.2byte    0,   -5, 	  -6,   -8, 	   6,   -8, 	   0,   -8
.2byte   -1,   -5, 	  -5,   -9, 	   5,   -6, 	   0,   -8
.2byte    1,   -5, 	  -5,   -6, 	   5,   -9, 	   0,   -8
.2byte    4,   -7, 	   3,  -11, 	  -4,   -6, 	  -1,   -9
.2byte    4,   -6, 	   3,  -12, 	  -3,   -5, 	  -1,   -9
.2byte    2,   -5, 	   5,   -9, 	  -5,   -6, 	  -1,   -9
.2byte    5,   -8, 	   0,  -10, 	  -1,   -5, 	  -1,   -9
.2byte    5,   -9, 	  -3,  -10, 	   1,   -5, 	  -1,   -9
.2byte    4,   -7, 	   0,  -11, 	  -1,   -5, 	  -1,   -8
.2byte    1,  -11, 	  -3,  -10, 	   3,   -6, 	   0,   -9
.2byte    2,  -10, 	  -5,   -9, 	   4,   -8, 	  -1,   -9
.2byte    5,   -9, 	  -3,  -11, 	   3,   -6, 	  -1,   -9
.2byte   -1,  -10, 	   5,   -7, 	  -7,   -7, 	  -1,   -9
.2byte   -2,  -10, 	   3,  -10, 	  -7,   -9, 	  -1,  -10
.2byte    1,  -10, 	   5,   -9, 	  -4,  -10, 	   0,  -10
.2byte   -3,  -11, 	   1,  -10, 	  -5,   -6, 	  -2,   -9
.2byte   -4,  -10, 	   3,   -9, 	  -6,   -8, 	  -1,   -9
.2byte   -7,   -9, 	   1,  -11, 	  -5,   -6, 	  -1,   -9
.2byte   -7,   -8, 	  -2,  -10, 	  -1,   -5, 	  -1,   -9
.2byte   -7,   -9, 	   1,  -10, 	  -3,   -5, 	  -1,   -9
.2byte   -6,   -7, 	  -2,  -11, 	  -1,   -5, 	  -1,   -8
.2byte   -6,   -7, 	  -5,  -11, 	   2,   -6, 	  -1,   -9
.2byte   -6,   -6, 	  -5,  -12, 	   1,   -5, 	  -1,   -9
.2byte   -4,   -5, 	  -7,   -9, 	   3,   -6, 	  -1,   -9
.2byte    0,   -5, 	  -6,   -8, 	   6,   -8, 	   0,   -8
.2byte   -1,   -5, 	  -5,   -9, 	   5,   -6, 	   0,   -8
.2byte    1,   -5, 	  -5,   -6, 	   5,   -9, 	   0,   -8
.2byte    0,   -2, 	  -8,   -6, 	   8,   -6, 	   0,   -5
.2byte    4,   -7, 	   3,  -11, 	  -4,   -6, 	  -1,   -9
.2byte    4,   -6, 	   3,  -12, 	  -3,   -5, 	  -1,   -9
.2byte    2,   -5, 	   5,   -9, 	  -5,   -6, 	  -1,   -9
.2byte    4,   -5, 	   4,  -10, 	  -5,   -7, 	   0,   -8
.2byte    5,   -8, 	   0,  -10, 	  -1,   -5, 	  -1,   -9
.2byte    5,   -9, 	  -3,  -10, 	   1,   -5, 	  -1,   -9
.2byte    4,   -7, 	   0,  -11, 	  -1,   -5, 	  -1,   -8
.2byte    6,   -6, 	   0,  -10, 	  -2,   -7, 	   1,   -7
.2byte    1,  -11, 	  -3,  -10, 	   3,   -6, 	   0,   -9
.2byte    2,  -10, 	  -5,   -9, 	   4,   -8, 	  -1,   -9
.2byte    5,   -9, 	  -3,  -11, 	   3,   -6, 	  -1,   -9
.2byte    4,  -10, 	  -2,  -13, 	   9,   -8, 	   2,  -10
.2byte   -1,  -10, 	   5,   -7, 	  -7,   -7, 	  -1,   -9
.2byte   -2,  -10, 	   3,  -10, 	  -7,   -9, 	  -1,  -10
.2byte    1,  -10, 	   5,   -9, 	  -4,  -10, 	   0,  -10
.2byte   -1,   -9, 	   8,   -9, 	 -10,   -9, 	  -1,   -8
.2byte   -3,  -11, 	   1,  -10, 	  -5,   -6, 	  -2,   -9
.2byte   -4,  -10, 	   3,   -9, 	  -6,   -8, 	  -1,   -9
.2byte   -7,   -9, 	   1,  -11, 	  -5,   -6, 	  -1,   -9
.2byte   -6,  -10, 	   0,  -13, 	 -11,   -8, 	  -4,  -10
.2byte   -7,   -8, 	  -2,  -10, 	  -1,   -5, 	  -1,   -9
.2byte   -7,   -9, 	   1,  -10, 	  -3,   -5, 	  -1,   -9
.2byte   -6,   -7, 	  -2,  -11, 	  -1,   -5, 	  -1,   -8
.2byte   -7,   -6, 	  -1,  -10, 	   1,   -7, 	  -2,   -7
.2byte   -6,   -7, 	  -5,  -11, 	   2,   -6, 	  -1,   -9
.2byte   -6,   -6, 	  -5,  -12, 	   1,   -5, 	  -1,   -9
.2byte   -4,   -5, 	  -7,   -9, 	   3,   -6, 	  -1,   -9
.2byte   -6,   -5, 	  -6,  -10, 	   3,   -7, 	  -2,   -8
.2byte    0,   -5, 	  -6,   -8, 	   6,   -8, 	   0,   -8
.2byte   -1,   -5, 	  -5,   -9, 	   5,   -6, 	   0,   -8
.2byte    1,   -5, 	  -5,   -6, 	   5,   -9, 	   0,   -8
.2byte    0,   -2, 	  -8,   -6, 	   8,   -6, 	   0,   -5
.2byte    4,   -7, 	   3,  -11, 	  -4,   -6, 	  -1,   -9
.2byte    4,   -6, 	   3,  -12, 	  -3,   -5, 	  -1,   -9
.2byte    2,   -5, 	   5,   -9, 	  -5,   -6, 	  -1,   -9
.2byte    4,   -5, 	   4,  -10, 	  -5,   -7, 	   0,   -8
.2byte    5,   -8, 	   0,  -10, 	  -1,   -5, 	  -1,   -9
.2byte    5,   -9, 	  -3,  -10, 	   1,   -5, 	  -1,   -9
.2byte    4,   -7, 	   0,  -11, 	  -1,   -5, 	  -1,   -8
.2byte    6,   -6, 	   0,  -10, 	  -2,   -7, 	   1,   -7
.2byte    1,  -11, 	  -3,  -10, 	   3,   -6, 	   0,   -9
.2byte    2,  -10, 	  -5,   -9, 	   4,   -8, 	  -1,   -9
.2byte    5,   -9, 	  -3,  -11, 	   3,   -6, 	  -1,   -9
.2byte    4,  -10, 	  -2,  -13, 	   9,   -8, 	   2,  -10
.2byte   -1,  -10, 	   5,   -7, 	  -7,   -7, 	  -1,   -9
.2byte   -2,  -10, 	   3,  -10, 	  -7,   -9, 	  -1,  -10
.2byte    1,  -10, 	   5,   -9, 	  -4,  -10, 	   0,  -10
.2byte   -1,   -9, 	   8,   -9, 	 -10,   -9, 	  -1,   -8
.2byte   -3,  -11, 	   1,  -10, 	  -5,   -6, 	  -2,   -9
.2byte   -4,  -10, 	   3,   -9, 	  -6,   -8, 	  -1,   -9
.2byte   -7,   -9, 	   1,  -11, 	  -5,   -6, 	  -1,   -9
.2byte   -6,  -10, 	   0,  -13, 	 -11,   -8, 	  -4,  -10
.2byte   -7,   -8, 	  -2,  -10, 	  -1,   -5, 	  -1,   -9
.2byte   -7,   -9, 	   1,  -10, 	  -3,   -5, 	  -1,   -9
.2byte   -6,   -7, 	  -2,  -11, 	  -1,   -5, 	  -1,   -8
.2byte   -7,   -6, 	  -1,  -10, 	   1,   -7, 	  -2,   -7
.2byte   -6,   -7, 	  -5,  -11, 	   2,   -6, 	  -1,   -9
.2byte   -6,   -6, 	  -5,  -12, 	   1,   -5, 	  -1,   -9
.2byte   -4,   -5, 	  -7,   -9, 	   3,   -6, 	  -1,   -9
.2byte   -6,   -5, 	  -6,  -10, 	   3,   -7, 	  -2,   -8
.2byte    0,   -4, 	 -11,   -8, 	   9,   -8, 	   0,   -8
.2byte    0,   -4, 	  -9,   -8, 	  11,   -8, 	   0,   -7
.2byte    0,   -5, 	  -6,   -8, 	   6,   -8, 	   0,   -8
.2byte   -1,   -5, 	  -5,   -9, 	   5,   -6, 	   0,   -8
.2byte    1,   -5, 	  -5,   -6, 	   5,   -9, 	   0,   -8
.2byte    0,   -2, 	  -8,   -6, 	   8,   -6, 	   0,   -5
.2byte    5,   -6, 	  10,   -9, 	  -4,   -7, 	  -1,   -9
.2byte    5,   -6, 	   8,   -9, 	  -6,   -7, 	  -1,   -9
.2byte    4,   -7, 	   3,  -11, 	  -4,   -6, 	  -1,   -9
.2byte    4,   -6, 	   3,  -12, 	  -3,   -5, 	  -1,   -9
.2byte    2,   -5, 	   5,   -9, 	  -5,   -6, 	  -1,   -9
.2byte    4,   -5, 	   4,  -10, 	  -5,   -7, 	   0,   -8
.2byte    7,   -9, 	  -1,  -13, 	  -1,   -5, 	  -2,  -10
.2byte    7,   -9, 	  -3,  -13, 	  -4,   -7, 	  -1,   -9
.2byte    5,   -8, 	   0,  -10, 	  -1,   -5, 	  -1,   -9
.2byte    5,   -9, 	  -3,  -10, 	   1,   -5, 	  -1,   -9
.2byte    4,   -7, 	   0,  -11, 	  -1,   -5, 	  -1,   -8
.2byte    6,   -6, 	   0,  -10, 	  -2,   -7, 	   1,   -7
.2byte    3,   -9, 	  -4,  -13, 	   6,   -6, 	  -1,  -10
.2byte    5,  -10, 	  -7,  -13, 	   9,   -7, 	   0,  -10
.2byte    1,  -11, 	  -3,  -10, 	   3,   -6, 	   0,   -9
.2byte    2,  -10, 	  -5,   -9, 	   4,   -8, 	  -1,   -9
.2byte    5,   -9, 	  -3,  -11, 	   3,   -6, 	  -1,   -9
.2byte    4,  -10, 	  -2,  -13, 	   9,   -8, 	   2,  -10
.2byte   -2,  -10, 	   6,  -11, 	  -9,   -7, 	  -1,   -9
.2byte    0,  -10, 	   7,   -7, 	  -8,  -11, 	  -1,  -10
.2byte   -1,  -10, 	   5,   -7, 	  -7,   -7, 	  -1,   -9
.2byte   -2,  -10, 	   3,  -10, 	  -7,   -9, 	  -1,  -10
.2byte    1,  -10, 	   5,   -9, 	  -4,  -10, 	   0,  -10
.2byte   -1,   -9, 	   8,   -9, 	 -10,   -9, 	  -1,   -8
.2byte   -4,   -9, 	   3,  -13, 	  -7,   -6, 	   0,  -10
.2byte   -6,  -10, 	   6,  -13, 	 -10,   -7, 	  -1,  -10
.2byte   -3,  -11, 	   1,  -10, 	  -5,   -6, 	  -2,   -9
.2byte   -4,  -10, 	   3,   -9, 	  -6,   -8, 	  -1,   -9
.2byte   -7,   -9, 	   1,  -11, 	  -5,   -6, 	  -1,   -9
.2byte   -6,  -10, 	   0,  -13, 	 -11,   -8, 	  -4,  -10
.2byte   -9,   -9, 	  -1,  -13, 	  -1,   -5, 	   0,  -10
.2byte   -9,   -9, 	   1,  -13, 	   2,   -7, 	  -1,   -9
.2byte   -7,   -8, 	  -2,  -10, 	  -1,   -5, 	  -1,   -9
.2byte   -7,   -9, 	   1,  -10, 	  -3,   -5, 	  -1,   -9
.2byte   -6,   -7, 	  -2,  -11, 	  -1,   -5, 	  -1,   -8
.2byte   -7,   -6, 	  -1,  -10, 	   1,   -7, 	  -2,   -7
.2byte   -6,   -6, 	 -11,   -9, 	   3,   -7, 	   0,   -9
.2byte   -6,   -6, 	  -9,   -9, 	   5,   -7, 	   0,   -9
.2byte   -6,   -7, 	  -5,  -11, 	   2,   -6, 	  -1,   -9
.2byte   -6,   -6, 	  -5,  -12, 	   1,   -5, 	  -1,   -9
.2byte   -4,   -5, 	  -7,   -9, 	   3,   -6, 	  -1,   -9
.2byte   -6,   -5, 	  -6,  -10, 	   3,   -7, 	  -2,   -8
.2byte    0,   -5, 	  -6,   -8, 	   6,   -8, 	   0,   -8
.2byte    0,   -5, 	  -5,   -7, 	   5,   -7, 	   0,   -7
.2byte    4,   -7, 	   3,  -11, 	  -4,   -6, 	  -1,   -9
.2byte    4,   -8, 	   3,  -10, 	  -1,   -7, 	   0,   -9
.2byte    5,   -8, 	   0,  -10, 	  -1,   -5, 	  -1,   -9
.2byte    4,   -8, 	  -1,  -10, 	  -1,   -5, 	  -1,   -8
.2byte    1,  -11, 	  -3,  -10, 	   3,   -6, 	   0,   -9
.2byte    2,   -9, 	  -2,  -11, 	   2,   -7, 	   0,   -9
.2byte   -1,  -10, 	   5,   -7, 	  -7,   -7, 	  -1,   -9
.2byte   -1,   -9, 	   4,   -8, 	  -6,   -8, 	  -1,   -8
.2byte   -3,  -11, 	   1,  -10, 	  -5,   -6, 	  -2,   -9
.2byte   -3,   -9, 	   1,  -11, 	  -3,   -7, 	  -1,   -9
.2byte   -7,   -8, 	  -2,  -10, 	  -1,   -5, 	  -1,   -9
.2byte   -6,   -8, 	  -1,  -10, 	  -1,   -5, 	  -1,   -8
.2byte   -6,   -7, 	  -5,  -11, 	   2,   -6, 	  -1,   -9
.2byte   -5,   -8, 	  -4,  -10, 	   0,   -7, 	  -1,   -9
.2byte    0,   -6, 	  -6,   -9, 	   6,   -9, 	   0,   -8
.2byte    0,   -5, 	  -6,   -8, 	   6,   -8, 	   0,   -7
.2byte    0,  -12, 	  -6,   -9, 	   6,   -9, 	   0,  -11
.2byte    3,  -12, 	   5,  -11, 	  -3,   -7, 	   0,  -10
.2byte    5,  -11, 	  -1,  -12, 	   0,   -8, 	   0,  -11
.2byte    2,  -13, 	  -3,  -11, 	   5,   -8, 	  -1,  -10
.2byte    0,  -13, 	   6,   -8, 	  -6,   -8, 	   0,  -11
.2byte   -3,  -13, 	   2,  -11, 	  -6,   -8, 	   0,  -10
.2byte   -6,  -11, 	   0,  -12, 	  -1,   -8, 	  -1,  -11
.2byte   -4,  -12, 	  -6,  -11, 	   2,   -7, 	  -1,  -10
.2byte    0,   -5, 	  -6,   -8, 	   6,   -8, 	   0,   -8
.2byte   -1,   -5, 	  -5,   -9, 	   5,   -6, 	   0,   -8
.2byte    1,   -5, 	  -5,   -6, 	   5,   -9, 	   0,   -8
.2byte    0,   -2, 	  -8,   -6, 	   8,   -6, 	   0,   -5
.2byte    4,   -7, 	   3,  -11, 	  -4,   -6, 	  -1,   -9
.2byte    4,   -6, 	   3,  -12, 	  -3,   -5, 	  -1,   -9
.2byte    2,   -5, 	   5,   -9, 	  -5,   -6, 	  -1,   -9
.2byte    4,   -5, 	   4,  -10, 	  -5,   -7, 	   0,   -8
.2byte    5,   -8, 	   0,  -10, 	  -1,   -5, 	  -1,   -9
.2byte    5,   -9, 	  -3,  -10, 	   1,   -5, 	  -1,   -9
.2byte    4,   -7, 	   0,  -11, 	  -1,   -5, 	  -1,   -8
.2byte    6,   -6, 	   0,  -10, 	  -2,   -7, 	   1,   -7
.2byte    1,  -11, 	  -3,  -10, 	   3,   -6, 	   0,   -9
.2byte    2,  -10, 	  -5,   -9, 	   4,   -8, 	  -1,   -9
.2byte    5,   -9, 	  -3,  -11, 	   3,   -6, 	  -1,   -9
.2byte    4,  -10, 	  -2,  -13, 	   9,   -8, 	   2,  -10
.2byte   -1,  -10, 	   5,   -7, 	  -7,   -7, 	  -1,   -9
.2byte   -2,  -10, 	   3,  -10, 	  -7,   -9, 	  -1,  -10
.2byte    1,  -10, 	   5,   -9, 	  -4,  -10, 	   0,  -10
.2byte   -1,   -9, 	   8,   -9, 	 -10,   -9, 	  -1,   -8
.2byte   -3,  -11, 	   1,  -10, 	  -5,   -6, 	  -2,   -9
.2byte   -4,  -10, 	   3,   -9, 	  -6,   -8, 	  -1,   -9
.2byte   -7,   -9, 	   1,  -11, 	  -5,   -6, 	  -1,   -9
.2byte   -6,  -10, 	   0,  -13, 	 -11,   -8, 	  -4,  -10
.2byte   -7,   -8, 	  -2,  -10, 	  -1,   -5, 	  -1,   -9
.2byte   -7,   -9, 	   1,  -10, 	  -3,   -5, 	  -1,   -9
.2byte   -6,   -7, 	  -2,  -11, 	  -1,   -5, 	  -1,   -8
.2byte   -7,   -6, 	  -1,  -10, 	   1,   -7, 	  -2,   -7
.2byte   -6,   -7, 	  -5,  -11, 	   2,   -6, 	  -1,   -9
.2byte   -6,   -6, 	  -5,  -12, 	   1,   -5, 	  -1,   -9
.2byte   -4,   -5, 	  -7,   -9, 	   3,   -6, 	  -1,   -9
.2byte   -6,   -5, 	  -6,  -10, 	   3,   -7, 	  -2,   -8
.2byte    0,   -4, 	  -8,   -8, 	   8,   -8, 	   0,   -7
.2byte   -5,   -4, 	  -5,   -9, 	   4,   -6, 	  -1,   -7
.2byte   -6,   -6, 	   0,  -10, 	   2,   -7, 	  -1,   -7
.2byte   -3,   -8, 	   3,  -11, 	  -8,   -6, 	  -1,   -8
.2byte   -1,   -9, 	   8,   -9, 	 -10,   -9, 	  -1,   -8
.2byte    2,   -8, 	  -4,  -11, 	   7,   -6, 	   0,   -8
.2byte    6,   -6, 	   0,  -10, 	  -2,   -7, 	   1,   -7
.2byte    4,   -4, 	   4,   -9, 	  -5,   -6, 	   0,   -7
.2byte    0,   -4, 	  -8,   -8, 	   8,   -8, 	   0,   -7
.2byte    4,   -4, 	   4,   -9, 	  -5,   -6, 	   0,   -7
.2byte    6,   -6, 	   0,  -10, 	  -2,   -7, 	   1,   -7
.2byte    2,   -8, 	  -4,  -11, 	   7,   -6, 	   0,   -8
.2byte   -1,   -9, 	   8,   -9, 	 -10,   -9, 	  -1,   -8
.2byte   -3,   -8, 	   3,  -11, 	  -8,   -6, 	  -1,   -8
.2byte   -6,   -6, 	   0,  -10, 	   2,   -7, 	  -1,   -7
.2byte   -5,   -4, 	  -5,   -9, 	   4,   -6, 	  -1,   -7
.2byte    0,   -5, 	  -6,   -8, 	   6,   -8, 	   0,   -8
.2byte   -1,   -5, 	  -5,   -9, 	   5,   -6, 	   0,   -8
.2byte    1,   -5, 	  -5,   -6, 	   5,   -9, 	   0,   -8
.2byte    4,   -7, 	   3,  -11, 	  -4,   -6, 	  -1,   -9
.2byte    4,   -6, 	   3,  -12, 	  -3,   -5, 	  -1,   -9
.2byte    2,   -5, 	   5,   -9, 	  -5,   -6, 	  -1,   -9
.2byte    5,   -8, 	   0,  -10, 	  -1,   -5, 	  -1,   -9
.2byte    5,   -9, 	  -3,  -10, 	   1,   -5, 	  -1,   -9
.2byte    4,   -7, 	   0,  -11, 	  -1,   -5, 	  -1,   -8
.2byte    1,  -11, 	  -3,  -10, 	   3,   -6, 	   0,   -9
.2byte    2,  -10, 	  -5,   -9, 	   4,   -8, 	  -1,   -9
.2byte    5,   -9, 	  -3,  -11, 	   3,   -6, 	  -1,   -9
.2byte   -1,  -10, 	   5,   -7, 	  -7,   -7, 	  -1,   -9
.2byte   -2,  -10, 	   3,  -10, 	  -7,   -9, 	  -1,  -10
.2byte    1,  -10, 	   5,   -9, 	  -4,  -10, 	   0,  -10
.2byte   -3,  -11, 	   1,  -10, 	  -5,   -6, 	  -2,   -9
.2byte   -4,  -10, 	   3,   -9, 	  -6,   -8, 	  -1,   -9
.2byte   -7,   -9, 	   1,  -11, 	  -5,   -6, 	  -1,   -9
.2byte   -7,   -8, 	  -2,  -10, 	  -1,   -5, 	  -1,   -9
.2byte   -7,   -9, 	   1,  -10, 	  -3,   -5, 	  -1,   -9
.2byte   -6,   -7, 	  -2,  -11, 	  -1,   -5, 	  -1,   -8
.2byte   -6,   -7, 	  -5,  -11, 	   2,   -6, 	  -1,   -9
.2byte   -6,   -6, 	  -5,  -12, 	   1,   -5, 	  -1,   -9
.2byte   -4,   -5, 	  -7,   -9, 	   3,   -6, 	  -1,   -9
.2byte    0,   -4, 	  -8,   -8, 	   8,   -8, 	   0,   -7
.2byte    4,   -4, 	   4,   -9, 	  -5,   -6, 	   0,   -7
.2byte    6,   -6, 	   0,  -10, 	  -2,   -7, 	   1,   -7
.2byte    2,   -8, 	  -4,  -11, 	   7,   -6, 	   0,   -8
.2byte   -1,   -9, 	   8,   -9, 	 -10,   -9, 	  -1,   -8
.2byte   -3,   -8, 	   3,  -11, 	  -8,   -6, 	  -1,   -8
.2byte   -6,   -6, 	   0,  -10, 	   2,   -7, 	  -1,   -7
.2byte   -5,   -4, 	  -5,   -9, 	   4,   -6, 	  -1,   -7
.2byte    0,   -5, 	  -6,   -8, 	   6,   -8, 	   0,   -8
.2byte   -6,   -7, 	  -5,  -11, 	   2,   -6, 	  -1,   -9
.2byte   -7,   -8, 	  -2,  -10, 	  -1,   -5, 	  -1,   -9
.2byte   -3,  -11, 	   1,  -10, 	  -5,   -6, 	  -2,   -9
.2byte   -1,  -10, 	   5,   -7, 	  -7,   -7, 	  -1,   -9
.2byte    1,  -11, 	  -3,  -10, 	   3,   -6, 	   0,   -9
.2byte    5,   -8, 	   0,  -10, 	  -1,   -5, 	  -1,   -9
.2byte    4,   -7, 	   3,  -11, 	  -4,   -6, 	  -1,   -9
sQwilfishAnimTable1:
.4byte sQwilfishAnims_1_1
.4byte sQwilfishAnims_1_2
.4byte sQwilfishAnims_1_3
.4byte sQwilfishAnims_1_4
.4byte sQwilfishAnims_1_5
.4byte sQwilfishAnims_1_6
.4byte sQwilfishAnims_1_7
.4byte sQwilfishAnims_1_8
sQwilfishAnimTable2:
.4byte sQwilfishAnims_2_1
.4byte sQwilfishAnims_2_2
.4byte sQwilfishAnims_2_3
.4byte sQwilfishAnims_2_4
.4byte sQwilfishAnims_2_5
.4byte sQwilfishAnims_2_6
.4byte sQwilfishAnims_2_7
.4byte sQwilfishAnims_2_8
sQwilfishAnimTable3:
.4byte sQwilfishAnims_3_1
.4byte sQwilfishAnims_3_2
.4byte sQwilfishAnims_3_3
.4byte sQwilfishAnims_3_4
.4byte sQwilfishAnims_3_5
.4byte sQwilfishAnims_3_6
.4byte sQwilfishAnims_3_7
.4byte sQwilfishAnims_3_8
sQwilfishAnimTable4:
.4byte sQwilfishAnims_4_1
.4byte sQwilfishAnims_4_2
.4byte sQwilfishAnims_4_3
.4byte sQwilfishAnims_4_4
.4byte sQwilfishAnims_4_5
.4byte sQwilfishAnims_4_6
.4byte sQwilfishAnims_4_7
.4byte sQwilfishAnims_4_8
sQwilfishAnimTable5:
.4byte sQwilfishAnims_5_1
.4byte sQwilfishAnims_5_2
.4byte sQwilfishAnims_5_3
.4byte sQwilfishAnims_5_4
.4byte sQwilfishAnims_5_5
.4byte sQwilfishAnims_5_6
.4byte sQwilfishAnims_5_7
.4byte sQwilfishAnims_5_8
sQwilfishAnimTable6:
.4byte sQwilfishAnims_6_1
.4byte sQwilfishAnims_6_1
.4byte sQwilfishAnims_6_1
.4byte sQwilfishAnims_6_1
.4byte sQwilfishAnims_6_1
.4byte sQwilfishAnims_6_1
.4byte sQwilfishAnims_6_1
.4byte sQwilfishAnims_6_1
sQwilfishAnimTable7:
.4byte sQwilfishAnims_7_1
.4byte sQwilfishAnims_7_2
.4byte sQwilfishAnims_7_3
.4byte sQwilfishAnims_7_4
.4byte sQwilfishAnims_7_5
.4byte sQwilfishAnims_7_6
.4byte sQwilfishAnims_7_7
.4byte sQwilfishAnims_7_8
sQwilfishAnimTable8:
.4byte sQwilfishAnims_8_1
.4byte sQwilfishAnims_8_2
.4byte sQwilfishAnims_8_3
.4byte sQwilfishAnims_8_4
.4byte sQwilfishAnims_8_5
.4byte sQwilfishAnims_8_6
.4byte sQwilfishAnims_8_7
.4byte sQwilfishAnims_8_8
sQwilfishAnimTable9:
.4byte sQwilfishAnims_9_1
.4byte sQwilfishAnims_9_2
.4byte sQwilfishAnims_9_3
.4byte sQwilfishAnims_9_4
.4byte sQwilfishAnims_9_5
.4byte sQwilfishAnims_9_6
.4byte sQwilfishAnims_9_7
.4byte sQwilfishAnims_9_8
sQwilfishAnimTable10:
.4byte sQwilfishAnims_10_1
.4byte sQwilfishAnims_10_2
.4byte sQwilfishAnims_10_3
.4byte sQwilfishAnims_10_4
.4byte sQwilfishAnims_10_5
.4byte sQwilfishAnims_10_6
.4byte sQwilfishAnims_10_7
.4byte sQwilfishAnims_10_8
sQwilfishAnimTable11:
.4byte sQwilfishAnims_11_1
.4byte sQwilfishAnims_11_2
.4byte sQwilfishAnims_11_3
.4byte sQwilfishAnims_11_4
.4byte sQwilfishAnims_11_5
.4byte sQwilfishAnims_11_6
.4byte sQwilfishAnims_11_7
.4byte sQwilfishAnims_11_8
sQwilfishAnimTable12:
.4byte sQwilfishAnims_12_1
.4byte sQwilfishAnims_12_2
.4byte sQwilfishAnims_12_3
.4byte sQwilfishAnims_12_4
.4byte sQwilfishAnims_12_5
.4byte sQwilfishAnims_12_6
.4byte sQwilfishAnims_12_7
.4byte sQwilfishAnims_12_8
sQwilfishAnimTable13:
.4byte sQwilfishAnims_13_1
.4byte sQwilfishAnims_13_2
.4byte sQwilfishAnims_13_3
.4byte sQwilfishAnims_13_4
.4byte sQwilfishAnims_13_5
.4byte sQwilfishAnims_13_6
.4byte sQwilfishAnims_13_7
.4byte sQwilfishAnims_13_8
sAxAnimationsQwilfish:
.4byte sQwilfishAnimTable1
.4byte sQwilfishAnimTable2
.4byte sQwilfishAnimTable3
.4byte sQwilfishAnimTable4
.4byte sQwilfishAnimTable5
.4byte sQwilfishAnimTable6
.4byte sQwilfishAnimTable7
.4byte sQwilfishAnimTable8
.4byte sQwilfishAnimTable9
.4byte sQwilfishAnimTable10
.4byte sQwilfishAnimTable11
.4byte sQwilfishAnimTable12
.4byte sQwilfishAnimTable13
sAxSpritesQwilfish:
.4byte sQwilfishSprites1
.4byte sQwilfishSprites2
.4byte sQwilfishSprites3
.4byte sQwilfishSprites4
.4byte sQwilfishSprites5
.4byte sQwilfishSprites6
.4byte sQwilfishSprites7
.4byte sQwilfishSprites8
.4byte sQwilfishSprites9
.4byte sQwilfishSprites10
.4byte sQwilfishSprites11
.4byte sQwilfishSprites12
.4byte sQwilfishSprites13
.4byte sQwilfishSprites14
.4byte sQwilfishSprites15
.4byte sQwilfishSprites16
.4byte sQwilfishSprites17
.4byte sQwilfishSprites18
.4byte sQwilfishSprites19
.4byte sQwilfishSprites20
.4byte sQwilfishSprites21
.4byte sQwilfishSprites22
.4byte sQwilfishSprites23
.4byte sQwilfishSprites24
.4byte sQwilfishSprites25
.4byte sQwilfishSprites26
.4byte sQwilfishSprites27
.4byte sQwilfishSprites28
.4byte sQwilfishSprites29
.4byte sQwilfishSprites30
.4byte sQwilfishSprites31
.4byte sQwilfishSprites32
.4byte sQwilfishSprites33
.4byte sQwilfishSprites34
.4byte sQwilfishSprites35
.4byte sQwilfishSprites36
.4byte sQwilfishSprites37
.4byte sQwilfishSprites38
.4byte sQwilfishSprites39
.4byte sQwilfishSprites40
.4byte sQwilfishSprites41
.4byte sQwilfishSprites42
.4byte sQwilfishSprites43
.4byte sQwilfishSprites44
.4byte sQwilfishSprites45
.4byte sQwilfishSprites46
.4byte sQwilfishSprites47
sAxMainQwilfish:
ax_main sAxPosesQwilfish, sAxAnimationsQwilfish, 13, sAxSpritesQwilfish, sAxPositionsQwilfish
