.global gAxRalts
gAxRalts:
ax_siro sAxMainRalts
sRaltsPose1:
ax_pose 0, 0x81ec, 0x80f8, 0xac00
ax_pose_terminator
sRaltsPose2:
ax_pose 1, 0x81ec, 0x80f8, 0xac00
ax_pose_terminator
sRaltsPose3:
ax_pose 2, 0x81ec, 0x80f8, 0xac00
ax_pose_terminator
sRaltsPose4:
ax_pose 3, 0x81ec, 0x90f7, 0xac00
ax_pose_terminator
sRaltsPose5:
ax_pose 4, 0x81ec, 0x90f7, 0xac00
ax_pose_terminator
sRaltsPose6:
ax_pose 5, 0x81ec, 0x90f7, 0xac00
ax_pose_terminator
sRaltsPose7:
ax_pose 6, 0x01ec, 0x90eb, 0xac00
ax_pose_terminator
sRaltsPose8:
ax_pose 7, 0x01ec, 0x90eb, 0xac00
ax_pose_terminator
sRaltsPose9:
ax_pose 8, 0x01ec, 0x90eb, 0xac00
ax_pose_terminator
sRaltsPose10:
ax_pose 9, 0x81ec, 0x90f7, 0xac00
ax_pose_terminator
sRaltsPose11:
ax_pose 10, 0x81ec, 0x90f7, 0xac00
ax_pose_terminator
sRaltsPose12:
ax_pose 11, 0x81ec, 0x90f7, 0xac00
ax_pose_terminator
sRaltsPose13:
ax_pose 12, 0x81ec, 0x80f8, 0xac00
ax_pose_terminator
sRaltsPose14:
ax_pose 13, 0x81ec, 0x80f8, 0xac00
ax_pose_terminator
sRaltsPose15:
ax_pose 14, 0x81ec, 0x80f8, 0xac00
ax_pose_terminator
sRaltsPose16:
ax_pose 9, 0x81ec, 0x80f8, 0xac00
ax_pose_terminator
sRaltsPose17:
ax_pose 10, 0x81ec, 0x80f8, 0xac00
ax_pose_terminator
sRaltsPose18:
ax_pose 11, 0x81ec, 0x80f8, 0xac00
ax_pose_terminator
sRaltsPose19:
ax_pose 6, 0x01ec, 0x80f4, 0xac00
ax_pose_terminator
sRaltsPose20:
ax_pose 7, 0x01ec, 0x80f4, 0xac00
ax_pose_terminator
sRaltsPose21:
ax_pose 8, 0x01ec, 0x80f4, 0xac00
ax_pose_terminator
sRaltsPose22:
ax_pose 3, 0x81ec, 0x80f8, 0xac00
ax_pose_terminator
sRaltsPose23:
ax_pose 4, 0x81ec, 0x80f8, 0xac00
ax_pose_terminator
sRaltsPose24:
ax_pose 5, 0x81ec, 0x80f8, 0xac00
ax_pose_terminator
sRaltsPose25:
ax_pose 0, 0x81ec, 0x80f8, 0xac00
ax_pose_terminator
sRaltsPose26:
ax_pose 1, 0x81ec, 0x80f8, 0xac00
ax_pose_terminator
sRaltsPose27:
ax_pose 2, 0x81ec, 0x80f8, 0xac00
ax_pose_terminator
sRaltsPose28:
ax_pose 3, 0x81ec, 0x90f7, 0xac00
ax_pose_terminator
sRaltsPose29:
ax_pose 4, 0x81ec, 0x90f7, 0xac00
ax_pose_terminator
sRaltsPose30:
ax_pose 5, 0x81ec, 0x90f7, 0xac00
ax_pose_terminator
sRaltsPose31:
ax_pose 6, 0x01ec, 0x90eb, 0xac00
ax_pose_terminator
sRaltsPose32:
ax_pose 7, 0x01ec, 0x90eb, 0xac00
ax_pose_terminator
sRaltsPose33:
ax_pose 8, 0x01ec, 0x90eb, 0xac00
ax_pose_terminator
sRaltsPose34:
ax_pose 9, 0x81ec, 0x90f7, 0xac00
ax_pose_terminator
sRaltsPose35:
ax_pose 10, 0x81ec, 0x90f7, 0xac00
ax_pose_terminator
sRaltsPose36:
ax_pose 11, 0x81ec, 0x90f7, 0xac00
ax_pose_terminator
sRaltsPose37:
ax_pose 12, 0x81ec, 0x80f8, 0xac00
ax_pose_terminator
sRaltsPose38:
ax_pose 13, 0x81ec, 0x80f8, 0xac00
ax_pose_terminator
sRaltsPose39:
ax_pose 14, 0x81ec, 0x80f8, 0xac00
ax_pose_terminator
sRaltsPose40:
ax_pose 9, 0x81ec, 0x80f8, 0xac00
ax_pose_terminator
sRaltsPose41:
ax_pose 10, 0x81ec, 0x80f8, 0xac00
ax_pose_terminator
sRaltsPose42:
ax_pose 11, 0x81ec, 0x80f8, 0xac00
ax_pose_terminator
sRaltsPose43:
ax_pose 6, 0x01ec, 0x80f4, 0xac00
ax_pose_terminator
sRaltsPose44:
ax_pose 7, 0x01ec, 0x80f4, 0xac00
ax_pose_terminator
sRaltsPose45:
ax_pose 8, 0x01ec, 0x80f4, 0xac00
ax_pose_terminator
sRaltsPose46:
ax_pose 3, 0x81ec, 0x80f8, 0xac00
ax_pose_terminator
sRaltsPose47:
ax_pose 4, 0x81ec, 0x80f8, 0xac00
ax_pose_terminator
sRaltsPose48:
ax_pose 5, 0x81ec, 0x80f8, 0xac00
ax_pose_terminator
sRaltsPose49:
ax_pose 0, 0x81ec, 0x80f8, 0xac00
ax_pose_terminator
sRaltsPose50:
ax_pose 1, 0x81ec, 0x80f8, 0xac00
ax_pose_terminator
sRaltsPose51:
ax_pose 2, 0x81ec, 0x80f8, 0xac00
ax_pose_terminator
sRaltsPose52:
ax_pose 3, 0x81ec, 0x90f7, 0xac00
ax_pose_terminator
sRaltsPose53:
ax_pose 4, 0x81ec, 0x90f7, 0xac00
ax_pose_terminator
sRaltsPose54:
ax_pose 5, 0x81ec, 0x90f7, 0xac00
ax_pose_terminator
sRaltsPose55:
ax_pose 6, 0x01ec, 0x90eb, 0xac00
ax_pose_terminator
sRaltsPose56:
ax_pose 7, 0x01ec, 0x90eb, 0xac00
ax_pose_terminator
sRaltsPose57:
ax_pose 8, 0x01ec, 0x90eb, 0xac00
ax_pose_terminator
sRaltsPose58:
ax_pose 9, 0x81ec, 0x90f7, 0xac00
ax_pose_terminator
sRaltsPose59:
ax_pose 10, 0x81ec, 0x90f7, 0xac00
ax_pose_terminator
sRaltsPose60:
ax_pose 11, 0x81ec, 0x90f7, 0xac00
ax_pose_terminator
sRaltsPose61:
ax_pose 12, 0x81ec, 0x80f8, 0xac00
ax_pose_terminator
sRaltsPose62:
ax_pose 13, 0x81ec, 0x80f8, 0xac00
ax_pose_terminator
sRaltsPose63:
ax_pose 14, 0x81ec, 0x80f8, 0xac00
ax_pose_terminator
sRaltsPose64:
ax_pose 9, 0x81ec, 0x80f8, 0xac00
ax_pose_terminator
sRaltsPose65:
ax_pose 10, 0x81ec, 0x80f8, 0xac00
ax_pose_terminator
sRaltsPose66:
ax_pose 11, 0x81ec, 0x80f8, 0xac00
ax_pose_terminator
sRaltsPose67:
ax_pose 6, 0x01ec, 0x80f4, 0xac00
ax_pose_terminator
sRaltsPose68:
ax_pose 7, 0x01ec, 0x80f4, 0xac00
ax_pose_terminator
sRaltsPose69:
ax_pose 8, 0x01ec, 0x80f4, 0xac00
ax_pose_terminator
sRaltsPose70:
ax_pose 3, 0x81ec, 0x80f8, 0xac00
ax_pose_terminator
sRaltsPose71:
ax_pose 4, 0x81ec, 0x80f8, 0xac00
ax_pose_terminator
sRaltsPose72:
ax_pose 5, 0x81ec, 0x80f8, 0xac00
ax_pose_terminator
sRaltsPose73:
ax_pose 15, 0x01ec, 0x80f8, 0xac00
ax_pose_terminator
sRaltsPose74:
ax_pose 16, 0x01eb, 0x80f7, 0xac00
ax_pose_terminator
sRaltsPose75:
ax_pose 17, 0x01eb, 0x80f2, 0xac00
ax_pose_terminator
sRaltsPose76:
ax_pose 18, 0x01eb, 0x80f7, 0xac00
ax_pose_terminator
sRaltsPose77:
ax_pose 19, 0x01eb, 0x80f8, 0xac00
ax_pose_terminator
sRaltsPose78:
ax_pose 18, 0x01eb, 0x90e8, 0xac00
ax_pose_terminator
sRaltsPose79:
ax_pose 17, 0x01eb, 0x90ed, 0xac00
ax_pose_terminator
sRaltsPose80:
ax_pose 16, 0x01eb, 0x90e8, 0xac00
ax_pose_terminator
sRaltsPose81:
ax_pose 15, 0x01ec, 0x80f8, 0xac00
ax_pose_terminator
sRaltsPose82:
ax_pose 16, 0x01ec, 0x80f7, 0xac00
ax_pose_terminator
sRaltsPose83:
ax_pose 17, 0x01ec, 0x80f2, 0xac00
ax_pose_terminator
sRaltsPose84:
ax_pose 18, 0x01ec, 0x80f7, 0xac00
ax_pose_terminator
sRaltsPose85:
ax_pose 19, 0x01ec, 0x80f8, 0xac00
ax_pose_terminator
sRaltsPose86:
ax_pose 18, 0x01ec, 0x90e8, 0xac00
ax_pose_terminator
sRaltsPose87:
ax_pose 17, 0x01ec, 0x90ed, 0xac00
ax_pose_terminator
sRaltsPose88:
ax_pose 16, 0x01ec, 0x90e8, 0xac00
ax_pose_terminator
sRaltsPose89:
ax_pose 20, 0x81eb, 0x80f8, 0xac00
ax_pose_terminator
sRaltsPose90:
ax_pose 21, 0x81eb, 0x80f8, 0xac00
ax_pose_terminator
sRaltsPose91:
ax_pose 22, 0x01e3, 0x80f1, 0xac00
ax_pose_terminator
sRaltsPose92:
ax_pose 23, 0x01e6, 0x90e9, 0xac00
ax_pose_terminator
sRaltsPose93:
ax_pose 24, 0x01e4, 0x90ea, 0xac00
ax_pose_terminator
sRaltsPose94:
ax_pose 25, 0x01e6, 0x90eb, 0xac00
ax_pose_terminator
sRaltsPose95:
ax_pose 26, 0x01e2, 0x80f1, 0xac00
ax_pose_terminator
sRaltsPose96:
ax_pose 25, 0x01e6, 0x80f5, 0xac00
ax_pose_terminator
sRaltsPose97:
ax_pose 24, 0x01e6, 0x80f5, 0xac00
ax_pose_terminator
sRaltsPose98:
ax_pose 23, 0x01e6, 0x80f7, 0xac00
ax_pose_terminator
sRaltsPose99:
ax_pose 0, 0x81ec, 0x80f8, 0xac00
ax_pose_terminator
sRaltsPose100:
ax_pose 15, 0x01ec, 0x80f8, 0xac00
ax_pose_terminator
sRaltsPose101:
ax_pose 3, 0x81ec, 0x90f7, 0xac00
ax_pose_terminator
sRaltsPose102:
ax_pose 16, 0x01ec, 0x90e7, 0xac00
ax_pose_terminator
sRaltsPose103:
ax_pose 6, 0x01ec, 0x90eb, 0xac00
ax_pose_terminator
sRaltsPose104:
ax_pose 17, 0x01ec, 0x90eb, 0xac00
ax_pose_terminator
sRaltsPose105:
ax_pose 9, 0x81ec, 0x90f7, 0xac00
ax_pose_terminator
sRaltsPose106:
ax_pose 18, 0x01ec, 0x90e7, 0xac00
ax_pose_terminator
sRaltsPose107:
ax_pose 12, 0x81ec, 0x80f8, 0xac00
ax_pose_terminator
sRaltsPose108:
ax_pose 19, 0x01ec, 0x80f8, 0xac00
ax_pose_terminator
sRaltsPose109:
ax_pose 9, 0x81ec, 0x80f8, 0xac00
ax_pose_terminator
sRaltsPose110:
ax_pose 18, 0x01ec, 0x80f8, 0xac00
ax_pose_terminator
sRaltsPose111:
ax_pose 6, 0x01ec, 0x80f4, 0xac00
ax_pose_terminator
sRaltsPose112:
ax_pose 17, 0x01ec, 0x80f4, 0xac00
ax_pose_terminator
sRaltsPose113:
ax_pose 3, 0x81ec, 0x80f8, 0xac00
ax_pose_terminator
sRaltsPose114:
ax_pose 16, 0x01ec, 0x80f8, 0xac00
ax_pose_terminator
sRaltsPose115:
ax_pose 0, 0x81ec, 0x80f8, 0xac00
ax_pose_terminator
sRaltsPose116:
ax_pose 3, 0x81ec, 0x80f8, 0xac00
ax_pose_terminator
sRaltsPose117:
ax_pose 6, 0x01ec, 0x80f4, 0xac00
ax_pose_terminator
sRaltsPose118:
ax_pose 9, 0x81ec, 0x80f8, 0xac00
ax_pose_terminator
sRaltsPose119:
ax_pose 12, 0x81ec, 0x80f8, 0xac00
ax_pose_terminator
sRaltsPose120:
ax_pose 9, 0x81ec, 0x90f7, 0xac00
ax_pose_terminator
sRaltsPose121:
ax_pose 6, 0x01ec, 0x90eb, 0xac00
ax_pose_terminator
sRaltsPose122:
ax_pose 3, 0x81ec, 0x90f7, 0xac00
ax_pose_terminator
sRaltsPose123:
ax_pose 15, 0x01ec, 0x80f8, 0xac00
ax_pose_terminator
sRaltsPose124:
ax_pose 16, 0x01eb, 0x90e8, 0xac00
ax_pose_terminator
sRaltsPose125:
ax_pose 17, 0x01eb, 0x90ed, 0xac00
ax_pose_terminator
sRaltsPose126:
ax_pose 18, 0x01eb, 0x90e8, 0xac00
ax_pose_terminator
sRaltsPose127:
ax_pose 19, 0x01eb, 0x80f8, 0xac00
ax_pose_terminator
sRaltsPose128:
ax_pose 18, 0x01eb, 0x80f7, 0xac00
ax_pose_terminator
sRaltsPose129:
ax_pose 17, 0x01eb, 0x80f2, 0xac00
ax_pose_terminator
sRaltsPose130:
ax_pose 16, 0x01eb, 0x80f7, 0xac00
ax_pose_terminator
sRaltsPose131:
ax_pose 0, 0x81ec, 0x80f8, 0xac00
ax_pose_terminator
sRaltsPose132:
ax_pose 15, 0x01ec, 0x80f8, 0xac00
ax_pose_terminator
sRaltsPose133:
ax_pose 3, 0x81ec, 0x90f7, 0xac00
ax_pose_terminator
sRaltsPose134:
ax_pose 16, 0x01ec, 0x90e7, 0xac00
ax_pose_terminator
sRaltsPose135:
ax_pose 6, 0x01ec, 0x90eb, 0xac00
ax_pose_terminator
sRaltsPose136:
ax_pose 17, 0x01ec, 0x90ec, 0xac00
ax_pose_terminator
sRaltsPose137:
ax_pose 9, 0x81ec, 0x90f7, 0xac00
ax_pose_terminator
sRaltsPose138:
ax_pose 18, 0x01ec, 0x90e7, 0xac00
ax_pose_terminator
sRaltsPose139:
ax_pose 12, 0x81ec, 0x80f8, 0xac00
ax_pose_terminator
sRaltsPose140:
ax_pose 19, 0x01ec, 0x80f8, 0xac00
ax_pose_terminator
sRaltsPose141:
ax_pose 9, 0x81ec, 0x80f8, 0xac00
ax_pose_terminator
sRaltsPose142:
ax_pose 18, 0x01ec, 0x80f8, 0xac00
ax_pose_terminator
sRaltsPose143:
ax_pose 6, 0x01ec, 0x80f4, 0xac00
ax_pose_terminator
sRaltsPose144:
ax_pose 17, 0x01ec, 0x80f3, 0xac00
ax_pose_terminator
sRaltsPose145:
ax_pose 3, 0x81ec, 0x80f8, 0xac00
ax_pose_terminator
sRaltsPose146:
ax_pose 16, 0x01ec, 0x80f8, 0xac00
ax_pose_terminator
sRaltsPose147:
ax_pose 15, 0x01ec, 0x80f8, 0xac00
ax_pose_terminator
sRaltsPose148:
ax_pose 16, 0x01eb, 0x80f7, 0xac00
ax_pose_terminator
sRaltsPose149:
ax_pose 17, 0x01eb, 0x80f2, 0xac00
ax_pose_terminator
sRaltsPose150:
ax_pose 18, 0x01eb, 0x80f7, 0xac00
ax_pose_terminator
sRaltsPose151:
ax_pose 19, 0x01eb, 0x80f8, 0xac00
ax_pose_terminator
sRaltsPose152:
ax_pose 18, 0x01eb, 0x90e8, 0xac00
ax_pose_terminator
sRaltsPose153:
ax_pose 17, 0x01eb, 0x90ed, 0xac00
ax_pose_terminator
sRaltsPose154:
ax_pose 16, 0x01eb, 0x90e8, 0xac00
ax_pose_terminator
sRaltsPose155:
ax_pose 0, 0x81ec, 0x80f8, 0xac00
ax_pose_terminator
sRaltsPose156:
ax_pose 3, 0x81ec, 0x80f8, 0xac00
ax_pose_terminator
sRaltsPose157:
ax_pose 6, 0x01ec, 0x80f4, 0xac00
ax_pose_terminator
sRaltsPose158:
ax_pose 9, 0x81ec, 0x80f8, 0xac00
ax_pose_terminator
sRaltsPose159:
ax_pose 12, 0x81ec, 0x80f8, 0xac00
ax_pose_terminator
sRaltsPose160:
ax_pose 9, 0x81ec, 0x90f7, 0xac00
ax_pose_terminator
sRaltsPose161:
ax_pose 6, 0x01ec, 0x90eb, 0xac00
ax_pose_terminator
sRaltsPose162:
ax_pose 3, 0x81ec, 0x90f7, 0xac00
ax_pose_terminator
.align 2
sRaltsAnims_1_1:
ax_anim 10, 0, 0, 0, 0, 0, 0,
ax_anim 8, 0, 1, 0, 0, 0, 0,
ax_anim 10, 0, 0, 0, 0, 0, 0,
ax_anim 8, 0, 2, 0, 0, 0, 0,
ax_anim_terminator
sRaltsAnims_1_2:
ax_anim 10, 0, 3, 0, 0, 0, 0,
ax_anim 8, 0, 4, 0, 0, 0, 0,
ax_anim 10, 0, 3, 0, 0, 0, 0,
ax_anim 8, 0, 5, 0, 0, 0, 0,
ax_anim_terminator
sRaltsAnims_1_3:
ax_anim 10, 0, 6, 0, 0, 0, 0,
ax_anim 8, 0, 7, 0, 0, 0, 0,
ax_anim 10, 0, 6, 0, 0, 0, 0,
ax_anim 8, 0, 8, 0, 0, 0, 0,
ax_anim_terminator
sRaltsAnims_1_4:
ax_anim 10, 0, 9, 0, 0, 0, 0,
ax_anim 8, 0, 10, 0, 0, 0, 0,
ax_anim 10, 0, 9, 0, 0, 0, 0,
ax_anim 8, 0, 11, 0, 0, 0, 0,
ax_anim_terminator
sRaltsAnims_1_5:
ax_anim 10, 0, 12, 0, 0, 0, 0,
ax_anim 8, 0, 13, 0, 0, 0, 0,
ax_anim 10, 0, 12, 0, 0, 0, 0,
ax_anim 8, 0, 14, 0, 0, 0, 0,
ax_anim_terminator
sRaltsAnims_1_6:
ax_anim 10, 0, 15, 0, 0, 0, 0,
ax_anim 8, 0, 16, 0, 0, 0, 0,
ax_anim 10, 0, 15, 0, 0, 0, 0,
ax_anim 8, 0, 17, 0, 0, 0, 0,
ax_anim_terminator
sRaltsAnims_1_7:
ax_anim 10, 0, 18, 0, 0, 0, 0,
ax_anim 8, 0, 19, 0, 0, 0, 0,
ax_anim 10, 0, 18, 0, 0, 0, 0,
ax_anim 8, 0, 20, 0, 0, 0, 0,
ax_anim_terminator
sRaltsAnims_1_8:
ax_anim 10, 0, 21, 0, 0, 0, 0,
ax_anim 8, 0, 22, 0, 0, 0, 0,
ax_anim 10, 0, 21, 0, 0, 0, 0,
ax_anim 8, 0, 23, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sRaltsAnims_2_1:
ax_anim 2, 0, 24, 0, -1, 0, -1,
ax_anim 6, 0, 24, 0, -2, 0, -2,
ax_anim 1, 0, 26, 0, 0, 0, 0,
ax_anim 1, 2, 25, 0, 4, 0, 4,
ax_anim 1, 0, 26, 0, 10, 0, 10,
ax_anim 2, 0, 24, 0, 20, 0, 20,
ax_anim 2, 1, 24, 1, 20, 1, 20,
ax_anim 2, 0, 24, 0, 20, 0, 20,
ax_anim 2, 0, 24, 1, 20, 1, 20,
ax_anim 2, 0, 24, 0, 6, 0, 6,
ax_anim_terminator
sRaltsAnims_2_2:
ax_anim 2, 0, 27, -1, -1, -1, -1,
ax_anim 6, 0, 27, -2, -2, -2, -2,
ax_anim 1, 0, 29, 0, 0, 0, 0,
ax_anim 1, 2, 28, 4, 4, 4, 4,
ax_anim 1, 0, 29, 11, 11, 11, 11,
ax_anim 2, 0, 27, 23, 23, 23, 23,
ax_anim 2, 1, 27, 24, 22, 24, 22,
ax_anim 2, 0, 27, 23, 23, 23, 23,
ax_anim 2, 0, 27, 24, 22, 24, 22,
ax_anim 2, 0, 27, 6, 6, 6, 6,
ax_anim_terminator
sRaltsAnims_2_3:
ax_anim 2, 0, 30, -1, 0, -1, 0,
ax_anim 6, 0, 30, -2, 0, -2, 0,
ax_anim 1, 0, 32, 0, 0, 0, 0,
ax_anim 1, 2, 31, 4, 0, 4, 0,
ax_anim 1, 0, 32, 12, 0, 12, 0,
ax_anim 2, 0, 30, 23, 0, 23, 0,
ax_anim 2, 1, 30, 23, 1, 23, 1,
ax_anim 2, 0, 30, 23, 0, 23, 0,
ax_anim 2, 0, 30, 23, 1, 23, 1,
ax_anim 2, 0, 30, 6, 0, 6, 0,
ax_anim_terminator
sRaltsAnims_2_4:
ax_anim 2, 0, 33, -1, 1, -1, 1,
ax_anim 6, 0, 33, -2, 2, -2, 2,
ax_anim 1, 0, 35, 0, -1, 0, -1,
ax_anim 1, 2, 34, 5, -6, 5, -6,
ax_anim 1, 0, 35, 13, -13, 13, -13,
ax_anim 2, 0, 33, 22, -23, 22, -23,
ax_anim 2, 1, 33, 23, -22, 23, -22,
ax_anim 2, 0, 33, 22, -23, 22, -23,
ax_anim 2, 0, 33, 23, -22, 23, -22,
ax_anim 2, 0, 33, 6, -6, 6, -6,
ax_anim_terminator
sRaltsAnims_2_5:
ax_anim 2, 0, 36, 0, 1, 0, 1,
ax_anim 6, 0, 36, 0, 2, 0, 2,
ax_anim 1, 0, 38, 0, 0, 0, 0,
ax_anim 1, 2, 37, 0, -5, 0, -5,
ax_anim 1, 0, 38, 0, -12, 0, -12,
ax_anim 2, 0, 36, 0, -23, 0, -23,
ax_anim 2, 1, 36, 1, -23, 1, -23,
ax_anim 2, 0, 36, 0, -23, 0, -23,
ax_anim 2, 0, 36, 1, -23, 1, -23,
ax_anim 2, 0, 36, 0, -6, 0, -6,
ax_anim_terminator
sRaltsAnims_2_6:
ax_anim 2, 0, 39, 1, 1, 1, 1,
ax_anim 6, 0, 39, 2, 2, 2, 2,
ax_anim 1, 0, 41, 0, -1, 0, -1,
ax_anim 1, 2, 40, -5, -6, -5, -6,
ax_anim 1, 0, 41, -13, -13, -13, -13,
ax_anim 2, 0, 39, -22, -23, -22, -23,
ax_anim 2, 1, 39, -23, -22, -23, -22,
ax_anim 2, 0, 39, -22, -23, -22, -23,
ax_anim 2, 0, 39, -23, -22, -23, -22,
ax_anim 2, 0, 39, -6, -6, -6, -6,
ax_anim_terminator
sRaltsAnims_2_7:
ax_anim 2, 0, 42, 1, 0, 1, 0,
ax_anim 6, 0, 42, 2, 0, 2, 0,
ax_anim 1, 0, 44, 0, 0, 0, 0,
ax_anim 1, 2, 43, -4, 0, -4, 0,
ax_anim 1, 0, 44, -12, 0, -12, 0,
ax_anim 2, 0, 42, -23, 0, -23, 0,
ax_anim 2, 1, 42, -23, 1, -23, 1,
ax_anim 2, 0, 42, -23, 0, -23, 0,
ax_anim 2, 0, 42, -23, 1, -23, 1,
ax_anim 2, 0, 42, -6, 0, -6, 0,
ax_anim_terminator
sRaltsAnims_2_8:
ax_anim 2, 0, 45, 1, -1, 1, -1,
ax_anim 6, 0, 45, 2, -2, 2, -2,
ax_anim 1, 0, 47, 0, 0, 0, 0,
ax_anim 1, 2, 46, -4, 4, -4, 4,
ax_anim 1, 0, 47, -11, 11, -11, 11,
ax_anim 2, 0, 45, -23, 23, -23, 23,
ax_anim 2, 1, 45, -24, 22, -24, 22,
ax_anim 2, 0, 45, -23, 23, -23, 23,
ax_anim 2, 0, 45, -24, 22, -24, 22,
ax_anim 2, 0, 45, -6, 6, -6, 6,
ax_anim_terminator
.align 2
sRaltsAnims_3_1:
ax_anim 2, 0, 48, 0, -1, 0, -1,
ax_anim 6, 0, 48, 0, -2, 0, -2,
ax_anim 1, 0, 50, 0, 0, 0, 0,
ax_anim 1, 2, 49, 0, 4, 0, 4,
ax_anim 1, 0, 50, 0, 10, 0, 10,
ax_anim 2, 0, 48, 0, 20, 0, 20,
ax_anim 2, 1, 48, 1, 20, 1, 20,
ax_anim 2, 0, 48, 0, 20, 0, 20,
ax_anim 2, 0, 48, 1, 20, 1, 20,
ax_anim 2, 0, 48, 0, 6, 0, 6,
ax_anim_terminator
sRaltsAnims_3_2:
ax_anim 2, 0, 51, -1, -1, -1, -1,
ax_anim 6, 0, 51, -2, -2, -2, -2,
ax_anim 1, 0, 53, 0, 0, 0, 0,
ax_anim 1, 2, 52, 4, 4, 4, 4,
ax_anim 1, 0, 53, 11, 11, 11, 11,
ax_anim 2, 0, 51, 23, 23, 23, 23,
ax_anim 2, 1, 51, 24, 22, 24, 22,
ax_anim 2, 0, 51, 23, 23, 23, 23,
ax_anim 2, 0, 51, 24, 22, 24, 22,
ax_anim 2, 0, 51, 6, 6, 6, 6,
ax_anim_terminator
sRaltsAnims_3_3:
ax_anim 2, 0, 54, -1, 0, -1, 0,
ax_anim 6, 0, 54, -2, 0, -2, 0,
ax_anim 1, 0, 56, 0, 0, 0, 0,
ax_anim 1, 2, 55, 4, 0, 4, 0,
ax_anim 1, 0, 56, 12, 0, 12, 0,
ax_anim 2, 0, 54, 23, 0, 23, 0,
ax_anim 2, 1, 54, 23, 1, 23, 1,
ax_anim 2, 0, 54, 23, 0, 23, 0,
ax_anim 2, 0, 54, 23, 1, 23, 1,
ax_anim 2, 0, 54, 6, 0, 6, 0,
ax_anim_terminator
sRaltsAnims_3_4:
ax_anim 2, 0, 57, -1, 1, -1, 1,
ax_anim 6, 0, 57, -2, 2, -2, 2,
ax_anim 1, 0, 59, 0, -1, 0, -1,
ax_anim 1, 2, 58, 5, -6, 5, -6,
ax_anim 1, 0, 59, 13, -13, 13, -13,
ax_anim 2, 0, 57, 22, -23, 22, -23,
ax_anim 2, 1, 57, 23, -22, 23, -22,
ax_anim 2, 0, 57, 22, -23, 22, -23,
ax_anim 2, 0, 57, 23, -22, 23, -22,
ax_anim 2, 0, 57, 6, -6, 6, -6,
ax_anim_terminator
sRaltsAnims_3_5:
ax_anim 2, 0, 60, 0, 1, 0, 1,
ax_anim 6, 0, 60, 0, 2, 0, 2,
ax_anim 1, 0, 62, 0, 0, 0, 0,
ax_anim 1, 2, 61, 0, -5, 0, -5,
ax_anim 1, 0, 62, 0, -12, 0, -12,
ax_anim 2, 0, 60, 0, -23, 0, -23,
ax_anim 2, 1, 60, 1, -23, 1, -23,
ax_anim 2, 0, 60, 0, -23, 0, -23,
ax_anim 2, 0, 60, 1, -23, 1, -23,
ax_anim 2, 0, 60, 0, -6, 0, -6,
ax_anim_terminator
sRaltsAnims_3_6:
ax_anim 2, 0, 63, 1, 1, 1, 1,
ax_anim 6, 0, 63, 2, 2, 2, 2,
ax_anim 1, 0, 65, 0, -1, 0, -1,
ax_anim 1, 2, 64, -5, -6, -5, -6,
ax_anim 1, 0, 65, -13, -13, -13, -13,
ax_anim 2, 0, 63, -22, -23, -22, -23,
ax_anim 2, 1, 63, -23, -22, -23, -22,
ax_anim 2, 0, 63, -22, -23, -22, -23,
ax_anim 2, 0, 63, -23, -22, -23, -22,
ax_anim 2, 0, 63, -6, -6, -6, -6,
ax_anim_terminator
sRaltsAnims_3_7:
ax_anim 2, 0, 66, 1, 0, 1, 0,
ax_anim 6, 0, 66, 2, 0, 2, 0,
ax_anim 1, 0, 68, 0, 0, 0, 0,
ax_anim 1, 2, 67, -4, 0, -4, 0,
ax_anim 1, 0, 68, -12, 0, -12, 0,
ax_anim 2, 0, 66, -23, 0, -23, 0,
ax_anim 2, 1, 66, -23, 1, -23, 1,
ax_anim 2, 0, 66, -23, 0, -23, 0,
ax_anim 2, 0, 66, -23, 1, -23, 1,
ax_anim 2, 0, 66, -6, 0, -6, 0,
ax_anim_terminator
sRaltsAnims_3_8:
ax_anim 2, 0, 69, 1, -1, 1, -1,
ax_anim 6, 0, 69, 2, -2, 2, -2,
ax_anim 1, 0, 71, 0, 0, 0, 0,
ax_anim 1, 2, 70, -4, 4, -4, 4,
ax_anim 1, 0, 71, -11, 11, -11, 11,
ax_anim 2, 0, 69, -23, 23, -23, 23,
ax_anim 2, 1, 69, -24, 22, -24, 22,
ax_anim 2, 0, 69, -23, 23, -23, 23,
ax_anim 2, 0, 69, -24, 22, -24, 22,
ax_anim 2, 0, 69, -6, 6, -6, 6,
ax_anim_terminator
.align 2
sRaltsAnims_4_1:
ax_anim 2, 0, 72, 1, 0, 1, 0,
ax_anim 2, 0, 72, 0, 0, 0, 0,
ax_anim 2, 0, 72, 1, 0, 1, 0,
ax_anim 2, 0, 72, 0, 0, 0, 0,
ax_anim 2, 0, 72, 1, 0, 1, 0,
ax_anim 2, 2, 72, 0, 0, 0, 0,
ax_anim 2, 0, 72, 1, 0, 1, 0,
ax_anim 2, 0, 72, 0, 0, 0, 0,
ax_anim 2, 0, 72, 1, 0, 1, 0,
ax_anim 2, 1, 72, 0, 0, 0, 0,
ax_anim_terminator
sRaltsAnims_4_2:
ax_anim 2, 0, 79, 1, -1, 1, -1,
ax_anim 2, 0, 79, 0, 0, 0, 0,
ax_anim 2, 0, 79, 1, -1, 1, -1,
ax_anim 2, 0, 79, 0, 0, 0, 0,
ax_anim 2, 0, 79, 1, -1, 1, -1,
ax_anim 2, 2, 79, 0, 0, 0, 0,
ax_anim 2, 0, 79, 1, -1, 1, -1,
ax_anim 2, 0, 79, 0, 0, 0, 0,
ax_anim 2, 0, 79, 1, -1, 1, -1,
ax_anim 2, 1, 79, 0, 0, 0, 0,
ax_anim_terminator
sRaltsAnims_4_3:
ax_anim 2, 0, 78, 0, -1, 0, -1,
ax_anim 2, 0, 78, 0, 0, 0, 0,
ax_anim 2, 0, 78, 0, -1, 0, -1,
ax_anim 2, 0, 78, 0, 0, 0, 0,
ax_anim 2, 0, 78, 0, -1, 0, -1,
ax_anim 2, 2, 78, 0, 0, 0, 0,
ax_anim 2, 0, 78, 0, -1, 0, -1,
ax_anim 2, 0, 78, 0, 0, 0, 0,
ax_anim 2, 0, 78, 0, -1, 0, -1,
ax_anim 2, 1, 78, 0, 0, 0, 0,
ax_anim_terminator
sRaltsAnims_4_4:
ax_anim 2, 0, 77, -1, -1, -1, -1,
ax_anim 2, 0, 77, 0, 0, 0, 0,
ax_anim 2, 0, 77, -1, -1, -1, -1,
ax_anim 2, 0, 77, 0, 0, 0, 0,
ax_anim 2, 0, 77, -1, -1, -1, -1,
ax_anim 2, 2, 77, 0, 0, 0, 0,
ax_anim 2, 0, 77, -1, -1, -1, -1,
ax_anim 2, 0, 77, 0, 0, 0, 0,
ax_anim 2, 0, 77, -1, -1, -1, -1,
ax_anim 2, 1, 77, 0, 0, 0, 0,
ax_anim_terminator
sRaltsAnims_4_5:
ax_anim 2, 0, 76, 1, 0, 1, 0,
ax_anim 2, 0, 76, 0, 0, 0, 0,
ax_anim 2, 0, 76, 1, 0, 1, 0,
ax_anim 2, 0, 76, 0, 0, 0, 0,
ax_anim 2, 0, 76, 1, 0, 1, 0,
ax_anim 2, 2, 76, 0, 0, 0, 0,
ax_anim 2, 0, 76, 1, 0, 1, 0,
ax_anim 2, 0, 76, 0, 0, 0, 0,
ax_anim 2, 0, 76, 1, 0, 1, 0,
ax_anim 2, 1, 76, 0, 0, 0, 0,
ax_anim_terminator
sRaltsAnims_4_6:
ax_anim 2, 0, 75, 1, -1, 1, -1,
ax_anim 2, 0, 75, 0, 0, 0, 0,
ax_anim 2, 0, 75, 1, -1, 1, -1,
ax_anim 2, 0, 75, 0, 0, 0, 0,
ax_anim 2, 0, 75, 1, -1, 1, -1,
ax_anim 2, 2, 75, 0, 0, 0, 0,
ax_anim 2, 0, 75, 1, -1, 1, -1,
ax_anim 2, 0, 75, 0, 0, 0, 0,
ax_anim 2, 0, 75, 1, -1, 1, -1,
ax_anim 2, 1, 75, 0, 0, 0, 0,
ax_anim_terminator
sRaltsAnims_4_7:
ax_anim 2, 0, 74, 0, -1, 0, -1,
ax_anim 2, 0, 74, 0, 0, 0, 0,
ax_anim 2, 0, 74, 0, -1, 0, -1,
ax_anim 2, 0, 74, 0, 0, 0, 0,
ax_anim 2, 0, 74, 0, -1, 0, -1,
ax_anim 2, 2, 74, 0, 0, 0, 0,
ax_anim 2, 0, 74, 0, -1, 0, -1,
ax_anim 2, 0, 74, 0, 0, 0, 0,
ax_anim 2, 0, 74, 0, -1, 0, -1,
ax_anim 2, 1, 74, 0, 0, 0, 0,
ax_anim_terminator
sRaltsAnims_4_8:
ax_anim 2, 0, 73, -1, -1, -1, -1,
ax_anim 2, 0, 73, 0, 0, 0, 0,
ax_anim 2, 0, 73, -1, -1, -1, -1,
ax_anim 2, 0, 73, 0, 0, 0, 0,
ax_anim 2, 0, 73, -1, -1, -1, -1,
ax_anim 2, 2, 73, 0, 0, 0, 0,
ax_anim 2, 0, 73, -1, -1, -1, -1,
ax_anim 2, 0, 73, 0, 0, 0, 0,
ax_anim 2, 0, 73, -1, -1, -1, -1,
ax_anim 2, 1, 73, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sRaltsAnims_5_1:
ax_anim 3, 0, 81, 0, 0, 0, 0,
ax_anim 4, 0, 80, 0, 0, 0, 0,
ax_anim 3, 0, 87, 0, 0, 0, 0,
ax_anim 4, 2, 80, 0, 0, 0, 0,
ax_anim 3, 0, 81, 0, 0, 0, 0,
ax_anim 4, 0, 80, 0, 0, 0, 0,
ax_anim 3, 0, 87, 0, 0, 0, 0,
ax_anim 4, 0, 80, 0, 0, 0, 0,
ax_anim_terminator
sRaltsAnims_5_2:
ax_anim 3, 0, 80, 0, 0, 0, 0,
ax_anim 4, 0, 87, 0, 0, 0, 0,
ax_anim 3, 0, 86, 0, 0, 0, 0,
ax_anim 4, 2, 87, 0, 0, 0, 0,
ax_anim 3, 0, 80, 0, 0, 0, 0,
ax_anim 4, 0, 87, 0, 0, 0, 0,
ax_anim 3, 0, 86, 0, 0, 0, 0,
ax_anim 4, 0, 87, 0, 0, 0, 0,
ax_anim_terminator
sRaltsAnims_5_3:
ax_anim 3, 0, 87, 0, 0, 0, 0,
ax_anim 4, 0, 86, 0, 0, 0, 0,
ax_anim 3, 0, 85, 0, 0, 0, 0,
ax_anim 4, 2, 86, 0, 0, 0, 0,
ax_anim 3, 0, 87, 0, 0, 0, 0,
ax_anim 4, 0, 86, 0, 0, 0, 0,
ax_anim 3, 0, 85, 0, 0, 0, 0,
ax_anim 4, 0, 86, 0, 0, 0, 0,
ax_anim_terminator
sRaltsAnims_5_4:
ax_anim 3, 0, 86, 0, 0, 0, 0,
ax_anim 4, 0, 85, 0, 0, 0, 0,
ax_anim 3, 0, 84, 0, 0, 0, 0,
ax_anim 4, 2, 85, 0, 0, 0, 0,
ax_anim 3, 0, 86, 0, 0, 0, 0,
ax_anim 4, 0, 85, 0, 0, 0, 0,
ax_anim 3, 0, 84, 0, 0, 0, 0,
ax_anim 4, 0, 85, 0, 0, 0, 0,
ax_anim_terminator
sRaltsAnims_5_5:
ax_anim 3, 0, 85, 0, 0, 0, 0,
ax_anim 4, 0, 84, 0, 0, 0, 0,
ax_anim 3, 0, 83, 0, 0, 0, 0,
ax_anim 4, 2, 84, 0, 0, 0, 0,
ax_anim 3, 0, 85, 0, 0, 0, 0,
ax_anim 4, 0, 84, 0, 0, 0, 0,
ax_anim 3, 0, 83, 0, 0, 0, 0,
ax_anim 4, 0, 84, 0, 0, 0, 0,
ax_anim_terminator
sRaltsAnims_5_6:
ax_anim 3, 0, 84, 0, 0, 0, 0,
ax_anim 4, 0, 83, 0, 0, 0, 0,
ax_anim 3, 0, 82, 0, 0, 0, 0,
ax_anim 4, 2, 83, 0, 0, 0, 0,
ax_anim 3, 0, 84, 0, 0, 0, 0,
ax_anim 4, 0, 83, 0, 0, 0, 0,
ax_anim 3, 0, 82, 0, 0, 0, 0,
ax_anim 4, 0, 83, 0, 0, 0, 0,
ax_anim_terminator
sRaltsAnims_5_7:
ax_anim 3, 0, 83, 0, 0, 0, 0,
ax_anim 4, 0, 82, 0, 0, 0, 0,
ax_anim 3, 0, 81, 0, 0, 0, 0,
ax_anim 4, 2, 82, 0, 0, 0, 0,
ax_anim 3, 0, 83, 0, 0, 0, 0,
ax_anim 4, 0, 82, 0, 0, 0, 0,
ax_anim 3, 0, 81, 0, 0, 0, 0,
ax_anim 4, 0, 82, 0, 0, 0, 0,
ax_anim_terminator
sRaltsAnims_5_8:
ax_anim 3, 0, 82, 0, 0, 0, 0,
ax_anim 4, 0, 81, 0, 0, 0, 0,
ax_anim 3, 0, 80, 0, 0, 0, 0,
ax_anim 4, 2, 81, 0, 0, 0, 0,
ax_anim 3, 0, 82, 0, 0, 0, 0,
ax_anim 4, 0, 81, 0, 0, 0, 0,
ax_anim 3, 0, 80, 0, 0, 0, 0,
ax_anim 4, 0, 81, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sRaltsAnims_6_1:
ax_anim 30, 0, 88, 0, 0, 0, 0,
ax_anim 35, 0, 89, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sRaltsAnims_7_1:
ax_anim 2, 0, 90, 0, -2, 0, -2,
ax_anim 8, 0, 90, 0, -3, 0, -3,
ax_anim_terminator
sRaltsAnims_7_2:
ax_anim 2, 0, 91, -2, -2, -2, -2,
ax_anim 8, 0, 91, -3, -3, -3, -3,
ax_anim_terminator
sRaltsAnims_7_3:
ax_anim 2, 0, 92, -2, 0, -2, 0,
ax_anim 8, 0, 92, -3, 0, -3, 0,
ax_anim_terminator
sRaltsAnims_7_4:
ax_anim 2, 0, 93, -2, 2, -2, 2,
ax_anim 8, 0, 93, -3, 3, -3, 3,
ax_anim_terminator
sRaltsAnims_7_5:
ax_anim 2, 0, 94, 0, 2, 0, 2,
ax_anim 8, 0, 94, 0, 3, 0, 3,
ax_anim_terminator
sRaltsAnims_7_6:
ax_anim 2, 0, 95, 2, 2, 2, 2,
ax_anim 8, 0, 95, 3, 3, 3, 3,
ax_anim_terminator
sRaltsAnims_7_7:
ax_anim 2, 0, 96, 2, 0, 2, 0,
ax_anim 8, 0, 96, 3, 0, 3, 0,
ax_anim_terminator
sRaltsAnims_7_8:
ax_anim 2, 0, 97, 2, -2, 2, -2,
ax_anim 8, 0, 97, 3, -3, 3, -3,
ax_anim_terminator
.align 2
sRaltsAnims_8_1:
ax_anim 40, 0, 98, 0, 0, 0, 0,
ax_anim 25, 0, 99, 0, 0, 0, 0,
ax_anim_terminator
sRaltsAnims_8_2:
ax_anim 40, 0, 100, 0, 0, 0, 0,
ax_anim 25, 0, 101, 0, 0, 0, 0,
ax_anim_terminator
sRaltsAnims_8_3:
ax_anim 40, 0, 102, 0, 0, 0, 0,
ax_anim 25, 0, 103, 0, 0, 0, 0,
ax_anim_terminator
sRaltsAnims_8_4:
ax_anim 40, 0, 104, 0, 0, 0, 0,
ax_anim 25, 0, 105, 0, 0, 0, 0,
ax_anim_terminator
sRaltsAnims_8_5:
ax_anim 40, 0, 106, 0, 0, 0, 0,
ax_anim 25, 0, 107, 0, 0, 0, 0,
ax_anim_terminator
sRaltsAnims_8_6:
ax_anim 40, 0, 108, 0, 0, 0, 0,
ax_anim 25, 0, 109, 0, 0, 0, 0,
ax_anim_terminator
sRaltsAnims_8_7:
ax_anim 40, 0, 110, 0, 0, 0, 0,
ax_anim 25, 0, 111, 0, 0, 0, 0,
ax_anim_terminator
sRaltsAnims_8_8:
ax_anim 40, 0, 112, 0, 0, 0, 0,
ax_anim 25, 0, 113, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sRaltsAnims_9_1:
ax_anim 2, 0, 114, 0, 0, 0, 0,
ax_anim 1, 0, 115, 6, 3, 6, 3,
ax_anim 2, 0, 116, 8, 9, 8, 9,
ax_anim 2, 0, 117, 7, 17, 7, 17,
ax_anim 3, 0, 118, 0, 19, 0, 19,
ax_anim 2, 3, 119, -7, 17, -7, 17,
ax_anim 2, 0, 120, -8, 9, -8, 9,
ax_anim 1, 0, 121, -6, 3, -6, 3,
ax_anim 1, 0, 114, 0, 0, 0, 0,
ax_anim_terminator
sRaltsAnims_9_2:
ax_anim 2, 0, 121, 0, 0, 0, 0,
ax_anim 1, 0, 114, 10, 1, 10, 1,
ax_anim 2, 0, 115, 18, 4, 18, 4,
ax_anim 2, 0, 116, 23, 12, 23, 12,
ax_anim 3, 0, 117, 22, 19, 22, 19,
ax_anim 2, 3, 118, 11, 20, 11, 20,
ax_anim 2, 0, 119, 2, 16, 2, 16,
ax_anim 1, 0, 120, 0, 7, 0, 7,
ax_anim 1, 0, 121, 0, 0, 0, 0,
ax_anim_terminator
sRaltsAnims_9_3:
ax_anim 2, 0, 120, 0, 0, 0, 0,
ax_anim 1, 0, 121, 3, -4, 3, -4,
ax_anim 2, 0, 114, 11, -6, 11, -6,
ax_anim 2, 0, 115, 17, -5, 17, -5,
ax_anim 3, 0, 116, 21, 0, 21, 0,
ax_anim 2, 3, 117, 19, 4, 19, 4,
ax_anim 2, 0, 118, 12, 5, 12, 5,
ax_anim 1, 0, 119, 3, 3, 3, 3,
ax_anim 1, 0, 120, 0, 0, 0, 0,
ax_anim_terminator
sRaltsAnims_9_4:
ax_anim 2, 0, 119, 0, 0, 0, 0,
ax_anim 1, 0, 120, 0, -8, 0, -8,
ax_anim 2, 0, 121, 3, -18, 3, -18,
ax_anim 2, 0, 114, 11, -23, 11, -23,
ax_anim 3, 0, 115, 21, -23, 21, -23,
ax_anim 2, 3, 116, 25, -15, 25, -15,
ax_anim 2, 0, 117, 22, -6, 22, -6,
ax_anim 1, 0, 118, 13, -2, 13, -2,
ax_anim 1, 0, 119, 0, 0, 0, 0,
ax_anim_terminator
sRaltsAnims_9_5:
ax_anim 2, 0, 118, 0, 0, 0, 0,
ax_anim 1, 0, 119, -8, -4, -8, -4,
ax_anim 2, 0, 120, -9, -13, -9, -13,
ax_anim 2, 0, 121, -7, -20, -7, -20,
ax_anim 3, 0, 114, 0, -22, 0, -22,
ax_anim 2, 3, 115, 7, -20, 7, -20,
ax_anim 2, 0, 116, 9, -13, 9, -13,
ax_anim 1, 0, 117, 8, -4, 8, -4,
ax_anim 1, 0, 118, 0, 0, 0, 0,
ax_anim_terminator
sRaltsAnims_9_6:
ax_anim 2, 0, 117, 0, 0, 0, 0,
ax_anim 1, 0, 116, 0, -8, 0, -8,
ax_anim 2, 0, 115, -3, -18, -3, -18,
ax_anim 2, 0, 114, -11, -23, -11, -23,
ax_anim 3, 0, 121, -21, -23, -21, -23,
ax_anim 2, 3, 120, -25, -15, -25, -15,
ax_anim 2, 0, 119, -22, -6, -22, -6,
ax_anim 1, 0, 118, -13, -2, -13, -2,
ax_anim 1, 0, 117, 0, 0, 0, 0,
ax_anim_terminator
sRaltsAnims_9_7:
ax_anim 2, 0, 116, 0, 0, 0, 0,
ax_anim 1, 0, 115, -3, -4, -3, -4,
ax_anim 2, 0, 114, -11, -6, -11, -6,
ax_anim 2, 0, 121, -17, -5, -17, -5,
ax_anim 3, 0, 120, -21, 0, -21, 0,
ax_anim 2, 3, 119, -19, 4, -19, 4,
ax_anim 2, 0, 118, -12, 5, -12, 5,
ax_anim 1, 0, 117, -3, 3, -3, 3,
ax_anim 1, 0, 116, 0, 0, 0, 0,
ax_anim_terminator
sRaltsAnims_9_8:
ax_anim 2, 0, 115, 0, 0, 0, 0,
ax_anim 1, 0, 114, -10, 1, -10, 1,
ax_anim 2, 0, 121, -18, 4, -18, 4,
ax_anim 2, 0, 120, -23, 12, -23, 12,
ax_anim 3, 0, 119, -22, 19, -22, 19,
ax_anim 2, 3, 118, -11, 20, -11, 20,
ax_anim 2, 0, 117, -2, 16, -2, 16,
ax_anim 1, 0, 116, 0, 7, 0, 7,
ax_anim 1, 0, 115, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sRaltsAnims_10_1:
ax_anim 2, 0, 122, 0, 0, 0, 0,
ax_anim 2, 0, 122, 6, 0, 6, 0,
ax_anim 2, 0, 122, -6, 0, -6, 0,
ax_anim 2, 0, 122, 10, 0, 10, 0,
ax_anim 2, 0, 122, -10, 0, -10, 0,
ax_anim 2, 0, 122, 12, 0, 12, 0,
ax_anim 3, 0, 122, -12, 0, -12, 0,
ax_anim 3, 0, 122, 13, 0, 13, 0,
ax_anim 3, 0, 122, -13, 0, -13, 0,
ax_anim 2, 0, 122, 12, 0, 12, 0,
ax_anim 3, 0, 122, -12, 0, -12, 0,
ax_anim 2, 0, 122, 10, 0, 10, 0,
ax_anim 2, 0, 122, -10, 0, -10, 0,
ax_anim 2, 0, 122, 6, 0, 6, 0,
ax_anim 2, 0, 122, -6, 0, -6, 0,
ax_anim 2, 0, 122, 0, 0, 0, 0,
ax_anim_terminator
sRaltsAnims_10_2:
ax_anim 2, 0, 123, 0, 0, 0, 0,
ax_anim 2, 0, 123, 6, -6, 6, -6,
ax_anim 2, 0, 123, -6, 6, -6, 6,
ax_anim 2, 0, 123, 10, -10, 10, -10,
ax_anim 2, 0, 123, -10, 10, -10, 10,
ax_anim 2, 0, 123, 12, -12, 12, -12,
ax_anim 3, 0, 123, -12, 12, -12, 12,
ax_anim 3, 0, 123, 13, -13, 13, -13,
ax_anim 3, 0, 123, -13, 13, -13, 13,
ax_anim 2, 0, 123, 12, -12, 12, -12,
ax_anim 3, 0, 123, -12, 12, -12, 12,
ax_anim 2, 0, 123, 10, -10, 10, -10,
ax_anim 2, 0, 123, -10, 10, -10, 10,
ax_anim 2, 0, 123, 6, -6, 6, -6,
ax_anim 2, 0, 123, -6, 6, -6, 6,
ax_anim 2, 0, 123, 0, 0, 0, 0,
ax_anim_terminator
sRaltsAnims_10_3:
ax_anim 2, 0, 124, 0, 0, 0, 0,
ax_anim 2, 0, 124, 0, -6, 0, -6,
ax_anim 2, 0, 124, 0, 6, 0, 6,
ax_anim 2, 0, 124, 0, -10, 0, -10,
ax_anim 2, 0, 124, 0, 10, 0, 10,
ax_anim 2, 0, 124, 0, -12, 0, -12,
ax_anim 3, 0, 124, 0, 12, 0, 12,
ax_anim 3, 0, 124, 0, -13, 0, -13,
ax_anim 3, 0, 124, 0, 13, 0, 13,
ax_anim 2, 0, 124, 0, -12, 0, -12,
ax_anim 3, 0, 124, 0, 12, 0, 12,
ax_anim 2, 0, 124, 0, -10, 0, -10,
ax_anim 2, 0, 124, 0, 10, 0, 10,
ax_anim 2, 0, 124, 0, -6, 0, -6,
ax_anim 2, 0, 124, 0, 6, 0, 6,
ax_anim 2, 0, 124, 0, 0, 0, 0,
ax_anim_terminator
sRaltsAnims_10_4:
ax_anim 2, 0, 125, 0, 0, 0, 0,
ax_anim 2, 0, 125, -6, -6, -6, -6,
ax_anim 2, 0, 125, 6, 6, 6, 6,
ax_anim 2, 0, 125, -10, -10, -10, -10,
ax_anim 2, 0, 125, 10, 10, 10, 10,
ax_anim 2, 0, 125, -12, -12, -12, -12,
ax_anim 3, 0, 125, 12, 12, 12, 12,
ax_anim 3, 0, 125, -13, -13, -13, -13,
ax_anim 3, 0, 125, 13, 13, 13, 13,
ax_anim 2, 0, 125, -12, -12, -12, -12,
ax_anim 3, 0, 125, 12, 12, 12, 12,
ax_anim 2, 0, 125, -10, -10, -10, -10,
ax_anim 2, 0, 125, 10, 10, 10, 10,
ax_anim 2, 0, 125, -6, -6, -6, -6,
ax_anim 2, 0, 125, 6, 6, 6, 6,
ax_anim 2, 0, 125, 0, 0, 0, 0,
ax_anim_terminator
sRaltsAnims_10_5:
ax_anim 2, 0, 126, 0, 0, 0, 0,
ax_anim 2, 0, 126, 6, 0, 6, 0,
ax_anim 2, 0, 126, -6, 0, -6, 0,
ax_anim 2, 0, 126, 10, 0, 10, 0,
ax_anim 2, 0, 126, -10, 0, -10, 0,
ax_anim 2, 0, 126, 12, 0, 12, 0,
ax_anim 3, 0, 126, -12, 0, -12, 0,
ax_anim 3, 0, 126, 13, 0, 13, 0,
ax_anim 3, 0, 126, -13, 0, -13, 0,
ax_anim 2, 0, 126, 12, 0, 12, 0,
ax_anim 3, 0, 126, -12, 0, -12, 0,
ax_anim 2, 0, 126, 10, 0, 10, 0,
ax_anim 2, 0, 126, -10, 0, -10, 0,
ax_anim 2, 0, 126, 6, 0, 6, 0,
ax_anim 2, 0, 126, -6, 0, -6, 0,
ax_anim 2, 0, 126, 0, 0, 0, 0,
ax_anim_terminator
sRaltsAnims_10_6:
ax_anim 2, 0, 127, 0, 0, 0, 0,
ax_anim 2, 0, 127, 6, -6, 6, -6,
ax_anim 2, 0, 127, -6, 6, -6, 6,
ax_anim 2, 0, 127, 10, -10, 10, -10,
ax_anim 2, 0, 127, -10, 10, -10, 10,
ax_anim 2, 0, 127, 12, -12, 12, -12,
ax_anim 3, 0, 127, -12, 12, -12, 12,
ax_anim 3, 0, 127, 13, -13, 13, -13,
ax_anim 3, 0, 127, -13, 13, -13, 13,
ax_anim 2, 0, 127, 12, -12, 12, -12,
ax_anim 3, 0, 127, -12, 12, -12, 12,
ax_anim 2, 0, 127, 10, -10, 10, -10,
ax_anim 2, 0, 127, -10, 10, -10, 10,
ax_anim 2, 0, 127, 6, -6, 6, -6,
ax_anim 2, 0, 127, -6, 6, -6, 6,
ax_anim 2, 0, 127, 0, 0, 0, 0,
ax_anim_terminator
sRaltsAnims_10_7:
ax_anim 2, 0, 128, 0, 0, 0, 0,
ax_anim 2, 0, 128, 0, -6, 0, -6,
ax_anim 2, 0, 128, 0, 6, 0, 6,
ax_anim 2, 0, 128, 0, -10, 0, -10,
ax_anim 2, 0, 128, 0, 10, 0, 10,
ax_anim 2, 0, 128, 0, -12, 0, -12,
ax_anim 3, 0, 128, 0, 12, 0, 12,
ax_anim 3, 0, 128, 0, -13, 0, -13,
ax_anim 3, 0, 128, 0, 13, 0, 13,
ax_anim 2, 0, 128, 0, -12, 0, -12,
ax_anim 3, 0, 128, 0, 12, 0, 12,
ax_anim 2, 0, 128, 0, -10, 0, -10,
ax_anim 2, 0, 128, 0, 10, 0, 10,
ax_anim 2, 0, 128, 0, -6, 0, -6,
ax_anim 2, 0, 128, 0, 6, 0, 6,
ax_anim 2, 0, 128, 0, 0, 0, 0,
ax_anim_terminator
sRaltsAnims_10_8:
ax_anim 2, 0, 129, 0, 0, 0, 0,
ax_anim 2, 0, 129, -6, -6, -6, -6,
ax_anim 2, 0, 129, 6, 6, 6, 6,
ax_anim 2, 0, 129, -10, -10, -10, -10,
ax_anim 2, 0, 129, 10, 10, 10, 10,
ax_anim 2, 0, 129, -12, -12, -12, -12,
ax_anim 3, 0, 129, 12, 12, 12, 12,
ax_anim 3, 0, 129, -13, -13, -13, -13,
ax_anim 3, 0, 129, 13, 13, 13, 13,
ax_anim 2, 0, 129, -12, -12, -12, -12,
ax_anim 3, 0, 129, 12, 12, 12, 12,
ax_anim 2, 0, 129, -10, -10, -10, -10,
ax_anim 2, 0, 129, 10, 10, 10, 10,
ax_anim 2, 0, 129, -6, -6, -6, -6,
ax_anim 2, 0, 129, 6, 6, 6, 6,
ax_anim 2, 0, 129, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sRaltsAnims_11_1:
ax_anim 2, 0, 130, 0, 0, 0, 0,
ax_anim 1, 0, 131, 0, -10, 0, 0,
ax_anim 2, 0, 131, 0, -16, 0, 0,
ax_anim 3, 0, 131, 0, -20, 0, 0,
ax_anim 4, 0, 131, 0, -21, 0, 0,
ax_anim 4, 0, 130, 0, -22, 0, 0,
ax_anim 3, 0, 130, 0, -21, 0, 0,
ax_anim 2, 0, 130, 0, -18, 0, 0,
ax_anim 1, 0, 130, 0, -12, 0, 0,
ax_anim 2, 2, 130, 0, 0, 0, 0,
ax_anim_terminator
sRaltsAnims_11_2:
ax_anim 2, 0, 132, 0, 0, 0, 0,
ax_anim 1, 0, 133, 0, -10, 0, 0,
ax_anim 2, 0, 133, 0, -16, 0, 0,
ax_anim 3, 0, 133, 0, -20, 0, 0,
ax_anim 4, 0, 133, 0, -21, 0, 0,
ax_anim 4, 0, 132, 0, -22, 0, 0,
ax_anim 3, 0, 132, 0, -21, 0, 0,
ax_anim 2, 0, 132, 0, -18, 0, 0,
ax_anim 1, 0, 132, 0, -12, 0, 0,
ax_anim 2, 2, 132, 0, 0, 0, 0,
ax_anim_terminator
sRaltsAnims_11_3:
ax_anim 2, 0, 134, 0, 0, 0, 0,
ax_anim 1, 0, 135, 0, -10, 0, 0,
ax_anim 2, 0, 135, 0, -16, 0, 0,
ax_anim 3, 0, 135, 0, -20, 0, 0,
ax_anim 4, 0, 135, 0, -21, 0, 0,
ax_anim 4, 0, 134, 0, -22, 0, 0,
ax_anim 3, 0, 134, 0, -21, 0, 0,
ax_anim 2, 0, 134, 0, -18, 0, 0,
ax_anim 1, 0, 134, 0, -12, 0, 0,
ax_anim 2, 2, 134, 0, 0, 0, 0,
ax_anim_terminator
sRaltsAnims_11_4:
ax_anim 2, 0, 136, 0, 0, 0, 0,
ax_anim 1, 0, 137, 0, -10, 0, 0,
ax_anim 2, 0, 137, 0, -16, 0, 0,
ax_anim 3, 0, 137, 0, -20, 0, 0,
ax_anim 4, 0, 137, 0, -21, 0, 0,
ax_anim 4, 0, 136, 0, -22, 0, 0,
ax_anim 3, 0, 136, 0, -21, 0, 0,
ax_anim 2, 0, 136, 0, -17, 0, 0,
ax_anim 1, 0, 136, 0, -11, 0, 0,
ax_anim 2, 2, 136, 0, 0, 0, 0,
ax_anim_terminator
sRaltsAnims_11_5:
ax_anim 2, 0, 138, 0, 0, 0, 0,
ax_anim 1, 0, 139, 0, -10, 0, 0,
ax_anim 2, 0, 139, 0, -16, 0, 0,
ax_anim 3, 0, 139, 0, -20, 0, 0,
ax_anim 4, 0, 139, 0, -21, 0, 0,
ax_anim 4, 0, 138, 0, -22, 0, 0,
ax_anim 3, 0, 138, 0, -21, 0, 0,
ax_anim 2, 0, 138, 0, -18, 0, 0,
ax_anim 1, 0, 138, 0, -12, 0, 0,
ax_anim 2, 2, 138, 0, 0, 0, 0,
ax_anim_terminator
sRaltsAnims_11_6:
ax_anim 2, 0, 140, 0, 0, 0, 0,
ax_anim 1, 0, 141, 0, -10, 0, 0,
ax_anim 2, 0, 141, 0, -16, 0, 0,
ax_anim 3, 0, 141, 0, -20, 0, 0,
ax_anim 4, 0, 141, 0, -21, 0, 0,
ax_anim 4, 0, 140, 0, -22, 0, 0,
ax_anim 3, 0, 140, 0, -21, 0, 0,
ax_anim 2, 0, 140, 0, -17, 0, 0,
ax_anim 1, 0, 140, 0, -11, 0, 0,
ax_anim 2, 2, 140, 0, 0, 0, 0,
ax_anim_terminator
sRaltsAnims_11_7:
ax_anim 2, 0, 142, 0, 0, 0, 0,
ax_anim 1, 0, 143, 0, -10, 0, 0,
ax_anim 2, 0, 143, 0, -16, 0, 0,
ax_anim 3, 0, 143, 0, -20, 0, 0,
ax_anim 4, 0, 143, 0, -21, 0, 0,
ax_anim 4, 0, 142, 0, -22, 0, 0,
ax_anim 3, 0, 142, 0, -21, 0, 0,
ax_anim 2, 0, 142, 0, -18, 0, 0,
ax_anim 1, 0, 142, 0, -12, 0, 0,
ax_anim 2, 2, 142, 0, 0, 0, 0,
ax_anim_terminator
sRaltsAnims_11_8:
ax_anim 2, 0, 144, 0, 0, 0, 0,
ax_anim 1, 0, 145, 0, -10, 0, 0,
ax_anim 2, 0, 145, 0, -16, 0, 0,
ax_anim 3, 0, 145, 0, -20, 0, 0,
ax_anim 4, 0, 145, 0, -21, 0, 0,
ax_anim 4, 0, 144, 0, -22, 0, 0,
ax_anim 3, 0, 144, 0, -21, 0, 0,
ax_anim 2, 0, 144, 0, -18, 0, 0,
ax_anim 1, 0, 144, 0, -12, 0, 0,
ax_anim 2, 2, 144, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sRaltsAnims_12_1:
ax_anim 2, 0, 146, 1, 0, 1, 0,
ax_anim 2, 0, 146, 0, 0, 0, 0,
ax_anim 2, 0, 146, 1, 0, 1, 0,
ax_anim 2, 0, 146, 0, 0, 0, 0,
ax_anim 2, 0, 146, 1, 0, 1, 0,
ax_anim 2, 2, 146, 0, 0, 0, 0,
ax_anim 2, 0, 146, 1, 0, 1, 0,
ax_anim 2, 0, 146, 0, 0, 0, 0,
ax_anim 2, 0, 146, 1, 0, 1, 0,
ax_anim 2, 1, 146, 0, 0, 0, 0,
ax_anim_terminator
sRaltsAnims_12_2:
ax_anim 2, 0, 153, 1, -1, 1, -1,
ax_anim 2, 0, 153, 0, 0, 0, 0,
ax_anim 2, 0, 153, 1, -1, 1, -1,
ax_anim 2, 0, 153, 0, 0, 0, 0,
ax_anim 2, 0, 153, 1, -1, 1, -1,
ax_anim 2, 2, 153, 0, 0, 0, 0,
ax_anim 2, 0, 153, 1, -1, 1, -1,
ax_anim 2, 0, 153, 0, 0, 0, 0,
ax_anim 2, 0, 153, 1, -1, 1, -1,
ax_anim 2, 1, 153, 0, 0, 0, 0,
ax_anim_terminator
sRaltsAnims_12_3:
ax_anim 2, 0, 152, 0, -1, 0, -1,
ax_anim 2, 0, 152, 0, 0, 0, 0,
ax_anim 2, 0, 152, 0, -1, 0, -1,
ax_anim 2, 0, 152, 0, 0, 0, 0,
ax_anim 2, 0, 152, 0, -1, 0, -1,
ax_anim 2, 2, 152, 0, 0, 0, 0,
ax_anim 2, 0, 152, 0, -1, 0, -1,
ax_anim 2, 0, 152, 0, 0, 0, 0,
ax_anim 2, 0, 152, 0, -1, 0, -1,
ax_anim 2, 1, 152, 0, 0, 0, 0,
ax_anim_terminator
sRaltsAnims_12_4:
ax_anim 2, 0, 151, -1, -1, -1, -1,
ax_anim 2, 0, 151, 0, 0, 0, 0,
ax_anim 2, 0, 151, -1, -1, -1, -1,
ax_anim 2, 0, 151, 0, 0, 0, 0,
ax_anim 2, 0, 151, -1, -1, -1, -1,
ax_anim 2, 2, 151, 0, 0, 0, 0,
ax_anim 2, 0, 151, -1, -1, -1, -1,
ax_anim 2, 0, 151, 0, 0, 0, 0,
ax_anim 2, 0, 151, -1, -1, -1, -1,
ax_anim 2, 1, 151, 0, 0, 0, 0,
ax_anim_terminator
sRaltsAnims_12_5:
ax_anim 2, 0, 150, 1, 0, 1, 0,
ax_anim 2, 0, 150, 0, 0, 0, 0,
ax_anim 2, 0, 150, 1, 0, 1, 0,
ax_anim 2, 0, 150, 0, 0, 0, 0,
ax_anim 2, 0, 150, 1, 0, 1, 0,
ax_anim 2, 2, 150, 0, 0, 0, 0,
ax_anim 2, 0, 150, 1, 0, 1, 0,
ax_anim 2, 0, 150, 0, 0, 0, 0,
ax_anim 2, 0, 150, 1, 0, 1, 0,
ax_anim 2, 1, 150, 0, 0, 0, 0,
ax_anim_terminator
sRaltsAnims_12_6:
ax_anim 2, 0, 149, 1, -1, 1, -1,
ax_anim 2, 0, 149, 0, 0, 0, 0,
ax_anim 2, 0, 149, 1, -1, 1, -1,
ax_anim 2, 0, 149, 0, 0, 0, 0,
ax_anim 2, 0, 149, 1, -1, 1, -1,
ax_anim 2, 2, 149, 0, 0, 0, 0,
ax_anim 2, 0, 149, 1, -1, 1, -1,
ax_anim 2, 0, 149, 0, 0, 0, 0,
ax_anim 2, 0, 149, 1, -1, 1, -1,
ax_anim 2, 1, 149, 0, 0, 0, 0,
ax_anim_terminator
sRaltsAnims_12_7:
ax_anim 2, 0, 148, 0, -1, 0, -1,
ax_anim 2, 0, 148, 0, 0, 0, 0,
ax_anim 2, 0, 148, 0, -1, 0, -1,
ax_anim 2, 0, 148, 0, 0, 0, 0,
ax_anim 2, 0, 148, 0, -1, 0, -1,
ax_anim 2, 2, 148, 0, 0, 0, 0,
ax_anim 2, 0, 148, 0, -1, 0, -1,
ax_anim 2, 0, 148, 0, 0, 0, 0,
ax_anim 2, 0, 148, 0, -1, 0, -1,
ax_anim 2, 1, 148, 0, 0, 0, 0,
ax_anim_terminator
sRaltsAnims_12_8:
ax_anim 2, 0, 147, -1, -1, -1, -1,
ax_anim 2, 0, 147, 0, 0, 0, 0,
ax_anim 2, 0, 147, -1, -1, -1, -1,
ax_anim 2, 0, 147, 0, 0, 0, 0,
ax_anim 2, 0, 147, -1, -1, -1, -1,
ax_anim 2, 2, 147, 0, 0, 0, 0,
ax_anim 2, 0, 147, -1, -1, -1, -1,
ax_anim 2, 0, 147, 0, 0, 0, 0,
ax_anim 2, 0, 147, -1, -1, -1, -1,
ax_anim 2, 1, 147, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sRaltsAnims_13_1:
ax_anim 2, 0, 154, 0, 0, 0, 0,
ax_anim 2, 0, 155, 0, 0, 0, 0,
ax_anim 2, 0, 156, 0, 0, 0, 0,
ax_anim 2, 0, 157, 0, 0, 0, 0,
ax_anim 2, 0, 158, 0, 0, 0, 0,
ax_anim 2, 0, 159, 0, 0, 0, 0,
ax_anim 2, 0, 160, 0, 0, 0, 0,
ax_anim 2, 0, 161, 0, 0, 0, 0,
ax_anim 2, 2, 154, 0, 0, 0, 0,
ax_anim_terminator
sRaltsAnims_13_2:
ax_anim 2, 0, 161, 0, 0, 0, 0,
ax_anim 2, 0, 154, 0, 0, 0, 0,
ax_anim 2, 0, 155, 0, 0, 0, 0,
ax_anim 2, 0, 156, 0, 0, 0, 0,
ax_anim 2, 0, 157, 0, 0, 0, 0,
ax_anim 2, 0, 158, 0, 0, 0, 0,
ax_anim 2, 0, 159, 0, 0, 0, 0,
ax_anim 2, 0, 160, 0, 0, 0, 0,
ax_anim 2, 2, 161, 0, 0, 0, 0,
ax_anim_terminator
sRaltsAnims_13_3:
ax_anim 2, 0, 160, 0, 0, 0, 0,
ax_anim 2, 0, 161, 0, 0, 0, 0,
ax_anim 2, 0, 154, 0, 0, 0, 0,
ax_anim 2, 0, 155, 0, 0, 0, 0,
ax_anim 2, 0, 156, 0, 0, 0, 0,
ax_anim 2, 0, 157, 0, 0, 0, 0,
ax_anim 2, 0, 158, 0, 0, 0, 0,
ax_anim 2, 0, 159, 0, 0, 0, 0,
ax_anim 2, 2, 160, 0, 0, 0, 0,
ax_anim_terminator
sRaltsAnims_13_4:
ax_anim 2, 0, 159, 0, 0, 0, 0,
ax_anim 2, 0, 160, 0, 0, 0, 0,
ax_anim 2, 0, 161, 0, 0, 0, 0,
ax_anim 2, 0, 154, 0, 0, 0, 0,
ax_anim 2, 0, 155, 0, 0, 0, 0,
ax_anim 2, 0, 156, 0, 0, 0, 0,
ax_anim 2, 0, 157, 0, 0, 0, 0,
ax_anim 2, 0, 158, 0, 0, 0, 0,
ax_anim 2, 2, 159, 0, 0, 0, 0,
ax_anim_terminator
sRaltsAnims_13_5:
ax_anim 2, 0, 158, 0, 0, 0, 0,
ax_anim 2, 0, 159, 0, 0, 0, 0,
ax_anim 2, 0, 160, 0, 0, 0, 0,
ax_anim 2, 0, 161, 0, 0, 0, 0,
ax_anim 2, 0, 154, 0, 0, 0, 0,
ax_anim 2, 0, 155, 0, 0, 0, 0,
ax_anim 2, 0, 156, 0, 0, 0, 0,
ax_anim 2, 0, 157, 0, 0, 0, 0,
ax_anim 2, 2, 158, 0, 0, 0, 0,
ax_anim_terminator
sRaltsAnims_13_6:
ax_anim 2, 0, 157, 0, 0, 0, 0,
ax_anim 2, 0, 158, 0, 0, 0, 0,
ax_anim 2, 0, 159, 0, 0, 0, 0,
ax_anim 2, 0, 160, 0, 0, 0, 0,
ax_anim 2, 0, 161, 0, 0, 0, 0,
ax_anim 2, 0, 154, 0, 0, 0, 0,
ax_anim 2, 0, 155, 0, 0, 0, 0,
ax_anim 2, 0, 156, 0, 0, 0, 0,
ax_anim 2, 2, 157, 0, 0, 0, 0,
ax_anim_terminator
sRaltsAnims_13_7:
ax_anim 2, 0, 156, 0, 0, 0, 0,
ax_anim 2, 0, 157, 0, 0, 0, 0,
ax_anim 2, 0, 158, 0, 0, 0, 0,
ax_anim 2, 0, 159, 0, 0, 0, 0,
ax_anim 2, 0, 160, 0, 0, 0, 0,
ax_anim 2, 0, 161, 0, 0, 0, 0,
ax_anim 2, 0, 154, 0, 0, 0, 0,
ax_anim 2, 0, 155, 0, 0, 0, 0,
ax_anim 2, 2, 156, 0, 0, 0, 0,
ax_anim_terminator
sRaltsAnims_13_8:
ax_anim 2, 0, 155, 0, 0, 0, 0,
ax_anim 2, 0, 156, 0, 0, 0, 0,
ax_anim 2, 0, 157, 0, 0, 0, 0,
ax_anim 2, 0, 158, 0, 0, 0, 0,
ax_anim 2, 0, 159, 0, 0, 0, 0,
ax_anim 2, 0, 160, 0, 0, 0, 0,
ax_anim 2, 0, 161, 0, 0, 0, 0,
ax_anim 2, 0, 154, 0, 0, 0, 0,
ax_anim 2, 2, 155, 0, 0, 0, 0,
ax_anim_terminator
sRaltsGfx1:
.incbin "baserom.gba", 0x1172134, 0x100
sRaltsSprites1:
ax_sprite sRaltsGfx1, 0x100
ax_sprite_terminator
sRaltsGfx2:
.incbin "baserom.gba", 0x1172244, 0x100
sRaltsSprites2:
ax_sprite sRaltsGfx2, 0x100
ax_sprite_terminator
sRaltsGfx3:
.incbin "baserom.gba", 0x1172354, 0x100
sRaltsSprites3:
ax_sprite sRaltsGfx3, 0x100
ax_sprite_terminator
sRaltsGfx4:
.incbin "baserom.gba", 0x1172464, 0x100
sRaltsSprites4:
ax_sprite sRaltsGfx4, 0x100
ax_sprite_terminator
sRaltsGfx5:
.incbin "baserom.gba", 0x1172574, 0x100
sRaltsSprites5:
ax_sprite sRaltsGfx5, 0x100
ax_sprite_terminator
sRaltsGfx6:
.incbin "baserom.gba", 0x1172684, 0x100
sRaltsSprites6:
ax_sprite sRaltsGfx6, 0x100
ax_sprite_terminator
sRaltsGfx7:
.incbin "baserom.gba", 0x1172794, 0x200
sRaltsSprites7:
ax_sprite sRaltsGfx7, 0x200
ax_sprite_terminator
sRaltsGfx8:
.incbin "baserom.gba", 0x11729A4, 0x200
sRaltsSprites8:
ax_sprite sRaltsGfx8, 0x200
ax_sprite_terminator
sRaltsGfx9:
.incbin "baserom.gba", 0x1172BB4, 0x200
sRaltsSprites9:
ax_sprite sRaltsGfx9, 0x200
ax_sprite_terminator
sRaltsGfx10:
.incbin "baserom.gba", 0x1172DC4, 0x100
sRaltsSprites10:
ax_sprite sRaltsGfx10, 0x100
ax_sprite_terminator
sRaltsGfx11:
.incbin "baserom.gba", 0x1172ED4, 0x100
sRaltsSprites11:
ax_sprite sRaltsGfx11, 0x100
ax_sprite_terminator
sRaltsGfx12:
.incbin "baserom.gba", 0x1172FE4, 0x100
sRaltsSprites12:
ax_sprite sRaltsGfx12, 0x100
ax_sprite_terminator
sRaltsGfx13:
.incbin "baserom.gba", 0x11730F4, 0x100
sRaltsSprites13:
ax_sprite sRaltsGfx13, 0x100
ax_sprite_terminator
sRaltsGfx14:
.incbin "baserom.gba", 0x1173204, 0x100
sRaltsSprites14:
ax_sprite sRaltsGfx14, 0x100
ax_sprite_terminator
sRaltsGfx15:
.incbin "baserom.gba", 0x1173314, 0x100
sRaltsSprites15:
ax_sprite sRaltsGfx15, 0x100
ax_sprite_terminator
sRaltsGfx16:
.incbin "baserom.gba", 0x1173424, 0x40
sRaltsGfx16_1:
.incbin "baserom.gba", 0x1173464, 0x40
sRaltsGfx16_2:
.incbin "baserom.gba", 0x11734A4, 0x40
sRaltsSprites16:
ax_sprite sRaltsGfx16, 0x40
ax_sprite 0, 0x40
ax_sprite sRaltsGfx16_1, 0x40
ax_sprite 0, 0x40
ax_sprite sRaltsGfx16_2, 0x40
ax_sprite 0, 0xc0
ax_sprite_terminator
sRaltsGfx17:
.incbin "baserom.gba", 0x117351C, 0x40
sRaltsGfx17_1:
.incbin "baserom.gba", 0x117355C, 0x40
sRaltsGfx17_2:
.incbin "baserom.gba", 0x117359C, 0x40
sRaltsSprites17:
ax_sprite sRaltsGfx17, 0x40
ax_sprite 0, 0x40
ax_sprite sRaltsGfx17_1, 0x40
ax_sprite 0, 0x40
ax_sprite sRaltsGfx17_2, 0x40
ax_sprite 0, 0xc0
ax_sprite_terminator
sRaltsGfx18:
.incbin "baserom.gba", 0x1173614, 0x40
sRaltsGfx18_1:
.incbin "baserom.gba", 0x1173654, 0x60
sRaltsGfx18_2:
.incbin "baserom.gba", 0x11736B4, 0x40
sRaltsSprites18:
ax_sprite 0, 0x20
ax_sprite sRaltsGfx18, 0x40
ax_sprite 0, 0x40
ax_sprite sRaltsGfx18_1, 0x60
ax_sprite 0, 0x20
ax_sprite sRaltsGfx18_2, 0x40
ax_sprite 0, 0xa0
ax_sprite_terminator
sRaltsGfx19:
.incbin "baserom.gba", 0x1173734, 0x40
sRaltsGfx19_1:
.incbin "baserom.gba", 0x1173774, 0x60
sRaltsGfx19_2:
.incbin "baserom.gba", 0x11737D4, 0x40
sRaltsSprites19:
ax_sprite sRaltsGfx19, 0x40
ax_sprite 0, 0x40
ax_sprite sRaltsGfx19_1, 0x60
ax_sprite 0, 0x20
ax_sprite sRaltsGfx19_2, 0x40
ax_sprite 0, 0xc0
ax_sprite_terminator
sRaltsGfx20:
.incbin "baserom.gba", 0x117384C, 0x40
sRaltsGfx20_1:
.incbin "baserom.gba", 0x117388C, 0x40
sRaltsGfx20_2:
.incbin "baserom.gba", 0x11738CC, 0x40
sRaltsSprites20:
ax_sprite sRaltsGfx20, 0x40
ax_sprite 0, 0x40
ax_sprite sRaltsGfx20_1, 0x40
ax_sprite 0, 0x40
ax_sprite sRaltsGfx20_2, 0x40
ax_sprite 0, 0xc0
ax_sprite_terminator
sRaltsGfx21:
.incbin "baserom.gba", 0x1173944, 0x100
sRaltsSprites21:
ax_sprite sRaltsGfx21, 0x100
ax_sprite_terminator
sRaltsGfx22:
.incbin "baserom.gba", 0x1173A54, 0x100
sRaltsSprites22:
ax_sprite sRaltsGfx22, 0x100
ax_sprite_terminator
sRaltsGfx23:
.incbin "baserom.gba", 0x1173B64, 0x200
sRaltsSprites23:
ax_sprite sRaltsGfx23, 0x200
ax_sprite_terminator
sRaltsGfx24:
.incbin "baserom.gba", 0x1173D74, 0x200
sRaltsSprites24:
ax_sprite sRaltsGfx24, 0x200
ax_sprite_terminator
sRaltsGfx25:
.incbin "baserom.gba", 0x1173F84, 0x200
sRaltsSprites25:
ax_sprite sRaltsGfx25, 0x200
ax_sprite_terminator
sRaltsGfx26:
.incbin "baserom.gba", 0x1174194, 0x200
sRaltsSprites26:
ax_sprite sRaltsGfx26, 0x200
ax_sprite_terminator
sRaltsGfx27:
.incbin "baserom.gba", 0x11743A4, 0x200
sRaltsSprites27:
ax_sprite sRaltsGfx27, 0x200
ax_sprite_terminator
sAxPosesRalts:
.4byte sRaltsPose1
.4byte sRaltsPose2
.4byte sRaltsPose3
.4byte sRaltsPose4
.4byte sRaltsPose5
.4byte sRaltsPose6
.4byte sRaltsPose7
.4byte sRaltsPose8
.4byte sRaltsPose9
.4byte sRaltsPose10
.4byte sRaltsPose11
.4byte sRaltsPose12
.4byte sRaltsPose13
.4byte sRaltsPose14
.4byte sRaltsPose15
.4byte sRaltsPose16
.4byte sRaltsPose17
.4byte sRaltsPose18
.4byte sRaltsPose19
.4byte sRaltsPose20
.4byte sRaltsPose21
.4byte sRaltsPose22
.4byte sRaltsPose23
.4byte sRaltsPose24
.4byte sRaltsPose25
.4byte sRaltsPose26
.4byte sRaltsPose27
.4byte sRaltsPose28
.4byte sRaltsPose29
.4byte sRaltsPose30
.4byte sRaltsPose31
.4byte sRaltsPose32
.4byte sRaltsPose33
.4byte sRaltsPose34
.4byte sRaltsPose35
.4byte sRaltsPose36
.4byte sRaltsPose37
.4byte sRaltsPose38
.4byte sRaltsPose39
.4byte sRaltsPose40
.4byte sRaltsPose41
.4byte sRaltsPose42
.4byte sRaltsPose43
.4byte sRaltsPose44
.4byte sRaltsPose45
.4byte sRaltsPose46
.4byte sRaltsPose47
.4byte sRaltsPose48
.4byte sRaltsPose49
.4byte sRaltsPose50
.4byte sRaltsPose51
.4byte sRaltsPose52
.4byte sRaltsPose53
.4byte sRaltsPose54
.4byte sRaltsPose55
.4byte sRaltsPose56
.4byte sRaltsPose57
.4byte sRaltsPose58
.4byte sRaltsPose59
.4byte sRaltsPose60
.4byte sRaltsPose61
.4byte sRaltsPose62
.4byte sRaltsPose63
.4byte sRaltsPose64
.4byte sRaltsPose65
.4byte sRaltsPose66
.4byte sRaltsPose67
.4byte sRaltsPose68
.4byte sRaltsPose69
.4byte sRaltsPose70
.4byte sRaltsPose71
.4byte sRaltsPose72
.4byte sRaltsPose73
.4byte sRaltsPose74
.4byte sRaltsPose75
.4byte sRaltsPose76
.4byte sRaltsPose77
.4byte sRaltsPose78
.4byte sRaltsPose79
.4byte sRaltsPose80
.4byte sRaltsPose81
.4byte sRaltsPose82
.4byte sRaltsPose83
.4byte sRaltsPose84
.4byte sRaltsPose85
.4byte sRaltsPose86
.4byte sRaltsPose87
.4byte sRaltsPose88
.4byte sRaltsPose89
.4byte sRaltsPose90
.4byte sRaltsPose91
.4byte sRaltsPose92
.4byte sRaltsPose93
.4byte sRaltsPose94
.4byte sRaltsPose95
.4byte sRaltsPose96
.4byte sRaltsPose97
.4byte sRaltsPose98
.4byte sRaltsPose99
.4byte sRaltsPose100
.4byte sRaltsPose101
.4byte sRaltsPose102
.4byte sRaltsPose103
.4byte sRaltsPose104
.4byte sRaltsPose105
.4byte sRaltsPose106
.4byte sRaltsPose107
.4byte sRaltsPose108
.4byte sRaltsPose109
.4byte sRaltsPose110
.4byte sRaltsPose111
.4byte sRaltsPose112
.4byte sRaltsPose113
.4byte sRaltsPose114
.4byte sRaltsPose115
.4byte sRaltsPose116
.4byte sRaltsPose117
.4byte sRaltsPose118
.4byte sRaltsPose119
.4byte sRaltsPose120
.4byte sRaltsPose121
.4byte sRaltsPose122
.4byte sRaltsPose123
.4byte sRaltsPose124
.4byte sRaltsPose125
.4byte sRaltsPose126
.4byte sRaltsPose127
.4byte sRaltsPose128
.4byte sRaltsPose129
.4byte sRaltsPose130
.4byte sRaltsPose131
.4byte sRaltsPose132
.4byte sRaltsPose133
.4byte sRaltsPose134
.4byte sRaltsPose135
.4byte sRaltsPose136
.4byte sRaltsPose137
.4byte sRaltsPose138
.4byte sRaltsPose139
.4byte sRaltsPose140
.4byte sRaltsPose141
.4byte sRaltsPose142
.4byte sRaltsPose143
.4byte sRaltsPose144
.4byte sRaltsPose145
.4byte sRaltsPose146
.4byte sRaltsPose147
.4byte sRaltsPose148
.4byte sRaltsPose149
.4byte sRaltsPose150
.4byte sRaltsPose151
.4byte sRaltsPose152
.4byte sRaltsPose153
.4byte sRaltsPose154
.4byte sRaltsPose155
.4byte sRaltsPose156
.4byte sRaltsPose157
.4byte sRaltsPose158
.4byte sRaltsPose159
.4byte sRaltsPose160
.4byte sRaltsPose161
.4byte sRaltsPose162
sAxPositionsRalts:
.2byte   -1,   -6, 	  -4,   -3, 	   2,   -3, 	  -1,   -5
.2byte   -1,   -5, 	  -4,   -2, 	   2,   -2, 	  -1,   -4
.2byte   -1,   -5, 	  -4,   -2, 	   2,   -2, 	  -1,   -4
.2byte    2,   -6, 	   1,   -3, 	  -3,   -3, 	  -1,   -5
.2byte    1,   -5, 	  -1,   -2, 	  -3,   -2, 	  -1,   -4
.2byte    1,   -5, 	   1,   -2, 	  -3,   -2, 	  -1,   -4
.2byte    2,   -6, 	   0,   -4, 	   0,   -3, 	  -1,   -5
.2byte    1,   -5, 	  -3,   -2, 	   0,   -2, 	  -1,   -4
.2byte    2,   -5, 	   1,   -2, 	   0,   -2, 	  -1,   -4
.2byte    1,   -7, 	  -2,   -4, 	   1,   -3, 	  -1,   -5
.2byte    1,   -6, 	  -3,   -2, 	   1,   -2, 	  -1,   -4
.2byte    1,   -6, 	   0,   -3, 	   1,   -2, 	  -1,   -4
.2byte   -1,   -7, 	   1,   -3, 	  -3,   -3, 	  -1,   -5
.2byte   -2,   -7, 	   2,   -2, 	  -3,   -3, 	  -1,   -5
.2byte    0,   -7, 	   1,   -3, 	  -4,   -2, 	  -1,   -5
.2byte   -3,   -7, 	   0,   -4, 	  -3,   -3, 	  -1,   -5
.2byte   -3,   -6, 	   1,   -2, 	  -3,   -2, 	  -1,   -4
.2byte   -3,   -6, 	  -2,   -3, 	  -3,   -2, 	  -1,   -4
.2byte   -4,   -6, 	  -2,   -4, 	  -2,   -3, 	  -1,   -5
.2byte   -3,   -5, 	   1,   -2, 	  -2,   -2, 	  -1,   -4
.2byte   -4,   -5, 	  -3,   -2, 	  -2,   -2, 	  -1,   -4
.2byte   -4,   -6, 	  -3,   -3, 	   1,   -3, 	  -1,   -5
.2byte   -3,   -5, 	  -1,   -2, 	   1,   -2, 	  -1,   -4
.2byte   -3,   -5, 	  -3,   -2, 	   1,   -2, 	  -1,   -4
.2byte   -1,   -6, 	  -4,   -3, 	   2,   -3, 	  -1,   -5
.2byte   -1,   -5, 	  -4,   -2, 	   2,   -2, 	  -1,   -4
.2byte   -1,   -5, 	  -4,   -2, 	   2,   -2, 	  -1,   -4
.2byte    2,   -6, 	   1,   -3, 	  -3,   -3, 	  -1,   -5
.2byte    1,   -5, 	  -1,   -2, 	  -3,   -2, 	  -1,   -4
.2byte    1,   -5, 	   1,   -2, 	  -3,   -2, 	  -1,   -4
.2byte    2,   -6, 	   0,   -4, 	   0,   -3, 	  -1,   -5
.2byte    1,   -5, 	  -3,   -2, 	   0,   -2, 	  -1,   -4
.2byte    2,   -5, 	   1,   -2, 	   0,   -2, 	  -1,   -4
.2byte    1,   -7, 	  -2,   -4, 	   1,   -3, 	  -1,   -5
.2byte    1,   -6, 	  -3,   -2, 	   1,   -2, 	  -1,   -4
.2byte    1,   -6, 	   0,   -3, 	   1,   -2, 	  -1,   -4
.2byte   -1,   -7, 	   1,   -3, 	  -3,   -3, 	  -1,   -5
.2byte   -2,   -7, 	   2,   -2, 	  -3,   -3, 	  -1,   -5
.2byte    0,   -7, 	   1,   -3, 	  -4,   -2, 	  -1,   -5
.2byte   -3,   -7, 	   0,   -4, 	  -3,   -3, 	  -1,   -5
.2byte   -3,   -6, 	   1,   -2, 	  -3,   -2, 	  -1,   -4
.2byte   -3,   -6, 	  -2,   -3, 	  -3,   -2, 	  -1,   -4
.2byte   -4,   -6, 	  -2,   -4, 	  -2,   -3, 	  -1,   -5
.2byte   -3,   -5, 	   1,   -2, 	  -2,   -2, 	  -1,   -4
.2byte   -4,   -5, 	  -3,   -2, 	  -2,   -2, 	  -1,   -4
.2byte   -4,   -6, 	  -3,   -3, 	   1,   -3, 	  -1,   -5
.2byte   -3,   -5, 	  -1,   -2, 	   1,   -2, 	  -1,   -4
.2byte   -3,   -5, 	  -3,   -2, 	   1,   -2, 	  -1,   -4
.2byte   -1,   -6, 	  -4,   -3, 	   2,   -3, 	  -1,   -5
.2byte   -1,   -5, 	  -4,   -2, 	   2,   -2, 	  -1,   -4
.2byte   -1,   -5, 	  -4,   -2, 	   2,   -2, 	  -1,   -4
.2byte    2,   -6, 	   1,   -3, 	  -3,   -3, 	  -1,   -5
.2byte    1,   -5, 	  -1,   -2, 	  -3,   -2, 	  -1,   -4
.2byte    1,   -5, 	   1,   -2, 	  -3,   -2, 	  -1,   -4
.2byte    2,   -6, 	   0,   -4, 	   0,   -3, 	  -1,   -5
.2byte    1,   -5, 	  -3,   -2, 	   0,   -2, 	  -1,   -4
.2byte    2,   -5, 	   1,   -2, 	   0,   -2, 	  -1,   -4
.2byte    1,   -7, 	  -2,   -4, 	   1,   -3, 	  -1,   -5
.2byte    1,   -6, 	  -3,   -2, 	   1,   -2, 	  -1,   -4
.2byte    1,   -6, 	   0,   -3, 	   1,   -2, 	  -1,   -4
.2byte   -1,   -7, 	   1,   -3, 	  -3,   -3, 	  -1,   -5
.2byte   -2,   -7, 	   2,   -2, 	  -3,   -3, 	  -1,   -5
.2byte    0,   -7, 	   1,   -3, 	  -4,   -2, 	  -1,   -5
.2byte   -3,   -7, 	   0,   -4, 	  -3,   -3, 	  -1,   -5
.2byte   -3,   -6, 	   1,   -2, 	  -3,   -2, 	  -1,   -4
.2byte   -3,   -6, 	  -2,   -3, 	  -3,   -2, 	  -1,   -4
.2byte   -4,   -6, 	  -2,   -4, 	  -2,   -3, 	  -1,   -5
.2byte   -3,   -5, 	   1,   -2, 	  -2,   -2, 	  -1,   -4
.2byte   -4,   -5, 	  -3,   -2, 	  -2,   -2, 	  -1,   -4
.2byte   -4,   -6, 	  -3,   -3, 	   1,   -3, 	  -1,   -5
.2byte   -3,   -5, 	  -1,   -2, 	   1,   -2, 	  -1,   -4
.2byte   -3,   -5, 	  -3,   -2, 	   1,   -2, 	  -1,   -4
.2byte   -1,   -7, 	  -3,   -6, 	   1,   -6, 	  -1,   -5
.2byte   -4,   -8, 	  -5,   -7, 	  -2,   -7, 	  -1,   -7
.2byte   -4,   -8, 	  -5,   -9, 	  -5,   -7, 	  -2,   -6
.2byte   -3,   -9, 	   0,   -9, 	  -5,   -7, 	  -2,   -6
.2byte   -1,   -9, 	   1,   -8, 	  -3,   -8, 	  -1,   -5
.2byte    1,   -9, 	  -2,   -9, 	   3,   -7, 	   0,   -6
.2byte    2,   -8, 	   3,   -9, 	   3,   -7, 	   0,   -6
.2byte    2,   -8, 	   3,   -7, 	   0,   -7, 	  -1,   -7
.2byte   -1,   -7, 	  -3,   -6, 	   1,   -6, 	  -1,   -5
.2byte   -4,   -7, 	  -5,   -6, 	  -2,   -6, 	  -1,   -6
.2byte   -4,   -7, 	  -5,   -8, 	  -5,   -6, 	  -2,   -5
.2byte   -3,   -8, 	   0,   -8, 	  -5,   -6, 	  -2,   -5
.2byte   -1,   -8, 	   1,   -7, 	  -3,   -7, 	  -1,   -4
.2byte    1,   -8, 	  -2,   -8, 	   3,   -6, 	   0,   -5
.2byte    2,   -7, 	   3,   -8, 	   3,   -6, 	   0,   -5
.2byte    2,   -7, 	   3,   -6, 	   0,   -6, 	  -1,   -6
.2byte   -4,   -5, 	  -3,   -2, 	   1,   -2, 	  -1,   -4
.2byte   -5,   -4, 	  -3,   -2, 	   1,   -1, 	  -2,   -3
.2byte    0,   -9, 	  -3,   -9, 	   3,   -9, 	   0,   -7
.2byte    1,   -9, 	   2,   -9, 	  -2,   -8, 	   0,   -6
.2byte    2,   -8, 	   1,  -10, 	   1,   -7, 	   0,   -5
.2byte    1,  -10, 	  -2,  -10, 	   3,   -8, 	   0,   -6
.2byte    0,   -8, 	   3,   -8, 	  -3,   -8, 	   0,   -5
.2byte   -2,  -10, 	   1,  -10, 	  -4,   -8, 	  -1,   -6
.2byte   -4,   -6, 	  -3,   -8, 	  -3,   -5, 	  -2,   -3
.2byte   -2,   -9, 	  -3,   -9, 	   1,   -8, 	  -1,   -6
.2byte   -1,   -6, 	  -4,   -3, 	   2,   -3, 	  -1,   -5
.2byte   -1,   -7, 	  -3,   -6, 	   1,   -6, 	  -1,   -5
.2byte    2,   -6, 	   1,   -3, 	  -3,   -3, 	  -1,   -5
.2byte    1,   -7, 	   2,   -6, 	  -1,   -6, 	  -2,   -6
.2byte    2,   -6, 	   0,   -4, 	   0,   -3, 	  -1,   -5
.2byte    0,   -7, 	   1,   -8, 	   1,   -6, 	  -2,   -5
.2byte    1,   -7, 	  -2,   -4, 	   1,   -3, 	  -1,   -5
.2byte    0,   -8, 	  -3,   -8, 	   2,   -6, 	  -1,   -5
.2byte   -1,   -7, 	   1,   -3, 	  -3,   -3, 	  -1,   -5
.2byte   -1,   -8, 	   1,   -7, 	  -3,   -7, 	  -1,   -4
.2byte   -3,   -7, 	   0,   -4, 	  -3,   -3, 	  -1,   -5
.2byte   -2,   -8, 	   1,   -8, 	  -4,   -6, 	  -1,   -5
.2byte   -4,   -6, 	  -2,   -4, 	  -2,   -3, 	  -1,   -5
.2byte   -2,   -7, 	  -3,   -8, 	  -3,   -6, 	   0,   -5
.2byte   -4,   -6, 	  -3,   -3, 	   1,   -3, 	  -1,   -5
.2byte   -3,   -7, 	  -4,   -6, 	  -1,   -6, 	   0,   -6
.2byte   -1,   -6, 	  -4,   -3, 	   2,   -3, 	  -1,   -5
.2byte   -4,   -6, 	  -3,   -3, 	   1,   -3, 	  -1,   -5
.2byte   -4,   -6, 	  -2,   -4, 	  -2,   -3, 	  -1,   -5
.2byte   -3,   -7, 	   0,   -4, 	  -3,   -3, 	  -1,   -5
.2byte   -1,   -7, 	   1,   -3, 	  -3,   -3, 	  -1,   -5
.2byte    1,   -7, 	  -2,   -4, 	   1,   -3, 	  -1,   -5
.2byte    2,   -6, 	   0,   -4, 	   0,   -3, 	  -1,   -5
.2byte    2,   -6, 	   1,   -3, 	  -3,   -3, 	  -1,   -5
.2byte   -1,   -7, 	  -3,   -6, 	   1,   -6, 	  -1,   -5
.2byte    2,   -8, 	   3,   -7, 	   0,   -7, 	  -1,   -7
.2byte    2,   -8, 	   3,   -9, 	   3,   -7, 	   0,   -6
.2byte    1,   -9, 	  -2,   -9, 	   3,   -7, 	   0,   -6
.2byte   -1,   -9, 	   1,   -8, 	  -3,   -8, 	  -1,   -5
.2byte   -3,   -9, 	   0,   -9, 	  -5,   -7, 	  -2,   -6
.2byte   -4,   -8, 	  -5,   -9, 	  -5,   -7, 	  -2,   -6
.2byte   -4,   -8, 	  -5,   -7, 	  -2,   -7, 	  -1,   -7
.2byte   -1,   -6, 	  -4,   -3, 	   2,   -3, 	  -1,   -5
.2byte   -1,   -7, 	  -3,   -6, 	   1,   -6, 	  -1,   -5
.2byte    2,   -6, 	   1,   -3, 	  -3,   -3, 	  -1,   -5
.2byte    1,   -7, 	   2,   -6, 	  -1,   -6, 	  -2,   -6
.2byte    2,   -6, 	   0,   -4, 	   0,   -3, 	  -1,   -5
.2byte    1,   -7, 	   2,   -8, 	   2,   -6, 	  -1,   -5
.2byte    1,   -7, 	  -2,   -4, 	   1,   -3, 	  -1,   -5
.2byte    0,   -8, 	  -3,   -8, 	   2,   -6, 	  -1,   -5
.2byte   -1,   -7, 	   1,   -3, 	  -3,   -3, 	  -1,   -5
.2byte   -1,   -8, 	   1,   -7, 	  -3,   -7, 	  -1,   -4
.2byte   -3,   -7, 	   0,   -4, 	  -3,   -3, 	  -1,   -5
.2byte   -2,   -8, 	   1,   -8, 	  -4,   -6, 	  -1,   -5
.2byte   -4,   -6, 	  -2,   -4, 	  -2,   -3, 	  -1,   -5
.2byte   -3,   -7, 	  -4,   -8, 	  -4,   -6, 	  -1,   -5
.2byte   -4,   -6, 	  -3,   -3, 	   1,   -3, 	  -1,   -5
.2byte   -3,   -7, 	  -4,   -6, 	  -1,   -6, 	   0,   -6
.2byte   -1,   -7, 	  -3,   -6, 	   1,   -6, 	  -1,   -5
.2byte   -4,   -8, 	  -5,   -7, 	  -2,   -7, 	  -1,   -7
.2byte   -4,   -8, 	  -5,   -9, 	  -5,   -7, 	  -2,   -6
.2byte   -3,   -9, 	   0,   -9, 	  -5,   -7, 	  -2,   -6
.2byte   -1,   -9, 	   1,   -8, 	  -3,   -8, 	  -1,   -5
.2byte    1,   -9, 	  -2,   -9, 	   3,   -7, 	   0,   -6
.2byte    2,   -8, 	   3,   -9, 	   3,   -7, 	   0,   -6
.2byte    2,   -8, 	   3,   -7, 	   0,   -7, 	  -1,   -7
.2byte   -1,   -6, 	  -4,   -3, 	   2,   -3, 	  -1,   -5
.2byte   -4,   -6, 	  -3,   -3, 	   1,   -3, 	  -1,   -5
.2byte   -4,   -6, 	  -2,   -4, 	  -2,   -3, 	  -1,   -5
.2byte   -3,   -7, 	   0,   -4, 	  -3,   -3, 	  -1,   -5
.2byte   -1,   -7, 	   1,   -3, 	  -3,   -3, 	  -1,   -5
.2byte    1,   -7, 	  -2,   -4, 	   1,   -3, 	  -1,   -5
.2byte    2,   -6, 	   0,   -4, 	   0,   -3, 	  -1,   -5
.2byte    2,   -6, 	   1,   -3, 	  -3,   -3, 	  -1,   -5
sRaltsAnimTable1:
.4byte sRaltsAnims_1_1
.4byte sRaltsAnims_1_2
.4byte sRaltsAnims_1_3
.4byte sRaltsAnims_1_4
.4byte sRaltsAnims_1_5
.4byte sRaltsAnims_1_6
.4byte sRaltsAnims_1_7
.4byte sRaltsAnims_1_8
sRaltsAnimTable2:
.4byte sRaltsAnims_2_1
.4byte sRaltsAnims_2_2
.4byte sRaltsAnims_2_3
.4byte sRaltsAnims_2_4
.4byte sRaltsAnims_2_5
.4byte sRaltsAnims_2_6
.4byte sRaltsAnims_2_7
.4byte sRaltsAnims_2_8
sRaltsAnimTable3:
.4byte sRaltsAnims_3_1
.4byte sRaltsAnims_3_2
.4byte sRaltsAnims_3_3
.4byte sRaltsAnims_3_4
.4byte sRaltsAnims_3_5
.4byte sRaltsAnims_3_6
.4byte sRaltsAnims_3_7
.4byte sRaltsAnims_3_8
sRaltsAnimTable4:
.4byte sRaltsAnims_4_1
.4byte sRaltsAnims_4_2
.4byte sRaltsAnims_4_3
.4byte sRaltsAnims_4_4
.4byte sRaltsAnims_4_5
.4byte sRaltsAnims_4_6
.4byte sRaltsAnims_4_7
.4byte sRaltsAnims_4_8
sRaltsAnimTable5:
.4byte sRaltsAnims_5_1
.4byte sRaltsAnims_5_2
.4byte sRaltsAnims_5_3
.4byte sRaltsAnims_5_4
.4byte sRaltsAnims_5_5
.4byte sRaltsAnims_5_6
.4byte sRaltsAnims_5_7
.4byte sRaltsAnims_5_8
sRaltsAnimTable6:
.4byte sRaltsAnims_6_1
.4byte sRaltsAnims_6_1
.4byte sRaltsAnims_6_1
.4byte sRaltsAnims_6_1
.4byte sRaltsAnims_6_1
.4byte sRaltsAnims_6_1
.4byte sRaltsAnims_6_1
.4byte sRaltsAnims_6_1
sRaltsAnimTable7:
.4byte sRaltsAnims_7_1
.4byte sRaltsAnims_7_2
.4byte sRaltsAnims_7_3
.4byte sRaltsAnims_7_4
.4byte sRaltsAnims_7_5
.4byte sRaltsAnims_7_6
.4byte sRaltsAnims_7_7
.4byte sRaltsAnims_7_8
sRaltsAnimTable8:
.4byte sRaltsAnims_8_1
.4byte sRaltsAnims_8_2
.4byte sRaltsAnims_8_3
.4byte sRaltsAnims_8_4
.4byte sRaltsAnims_8_5
.4byte sRaltsAnims_8_6
.4byte sRaltsAnims_8_7
.4byte sRaltsAnims_8_8
sRaltsAnimTable9:
.4byte sRaltsAnims_9_1
.4byte sRaltsAnims_9_2
.4byte sRaltsAnims_9_3
.4byte sRaltsAnims_9_4
.4byte sRaltsAnims_9_5
.4byte sRaltsAnims_9_6
.4byte sRaltsAnims_9_7
.4byte sRaltsAnims_9_8
sRaltsAnimTable10:
.4byte sRaltsAnims_10_1
.4byte sRaltsAnims_10_2
.4byte sRaltsAnims_10_3
.4byte sRaltsAnims_10_4
.4byte sRaltsAnims_10_5
.4byte sRaltsAnims_10_6
.4byte sRaltsAnims_10_7
.4byte sRaltsAnims_10_8
sRaltsAnimTable11:
.4byte sRaltsAnims_11_1
.4byte sRaltsAnims_11_2
.4byte sRaltsAnims_11_3
.4byte sRaltsAnims_11_4
.4byte sRaltsAnims_11_5
.4byte sRaltsAnims_11_6
.4byte sRaltsAnims_11_7
.4byte sRaltsAnims_11_8
sRaltsAnimTable12:
.4byte sRaltsAnims_12_1
.4byte sRaltsAnims_12_2
.4byte sRaltsAnims_12_3
.4byte sRaltsAnims_12_4
.4byte sRaltsAnims_12_5
.4byte sRaltsAnims_12_6
.4byte sRaltsAnims_12_7
.4byte sRaltsAnims_12_8
sRaltsAnimTable13:
.4byte sRaltsAnims_13_1
.4byte sRaltsAnims_13_2
.4byte sRaltsAnims_13_3
.4byte sRaltsAnims_13_4
.4byte sRaltsAnims_13_5
.4byte sRaltsAnims_13_6
.4byte sRaltsAnims_13_7
.4byte sRaltsAnims_13_8
sAxAnimationsRalts:
.4byte sRaltsAnimTable1
.4byte sRaltsAnimTable2
.4byte sRaltsAnimTable3
.4byte sRaltsAnimTable4
.4byte sRaltsAnimTable5
.4byte sRaltsAnimTable6
.4byte sRaltsAnimTable7
.4byte sRaltsAnimTable8
.4byte sRaltsAnimTable9
.4byte sRaltsAnimTable10
.4byte sRaltsAnimTable11
.4byte sRaltsAnimTable12
.4byte sRaltsAnimTable13
sAxSpritesRalts:
.4byte sRaltsSprites1
.4byte sRaltsSprites2
.4byte sRaltsSprites3
.4byte sRaltsSprites4
.4byte sRaltsSprites5
.4byte sRaltsSprites6
.4byte sRaltsSprites7
.4byte sRaltsSprites8
.4byte sRaltsSprites9
.4byte sRaltsSprites10
.4byte sRaltsSprites11
.4byte sRaltsSprites12
.4byte sRaltsSprites13
.4byte sRaltsSprites14
.4byte sRaltsSprites15
.4byte sRaltsSprites16
.4byte sRaltsSprites17
.4byte sRaltsSprites18
.4byte sRaltsSprites19
.4byte sRaltsSprites20
.4byte sRaltsSprites21
.4byte sRaltsSprites22
.4byte sRaltsSprites23
.4byte sRaltsSprites24
.4byte sRaltsSprites25
.4byte sRaltsSprites26
.4byte sRaltsSprites27
sAxMainRalts:
ax_main sAxPosesRalts, sAxAnimationsRalts, 13, sAxSpritesRalts, sAxPositionsRalts
