.global gAxSentret
gAxSentret:
ax_siro sAxMainSentret
sSentretPose1:
ax_pose 0, 0x01ea, 0x80f4, 0x1c00
ax_pose_terminator
sSentretPose2:
ax_pose 1, 0x01ec, 0x80f3, 0x1c00
ax_pose_terminator
sSentretPose3:
ax_pose 2, 0x01ec, 0x80f5, 0x1c00
ax_pose_terminator
sSentretPose4:
ax_pose 3, 0x01eb, 0x90eb, 0x1c00
ax_pose_terminator
sSentretPose5:
ax_pose 4, 0x01ea, 0x90ec, 0x1c00
ax_pose_terminator
sSentretPose6:
ax_pose 5, 0x01eb, 0x90eb, 0x1c00
ax_pose_terminator
sSentretPose7:
ax_pose 6, 0x01eb, 0x90e8, 0x1c00
ax_pose_terminator
sSentretPose8:
ax_pose 7, 0x01eb, 0x90e9, 0x1c00
ax_pose_terminator
sSentretPose9:
ax_pose 8, 0x01eb, 0x90e8, 0x1c00
ax_pose_terminator
sSentretPose10:
ax_pose 9, 0x01eb, 0x90eb, 0x1c00
ax_pose_terminator
sSentretPose11:
ax_pose 10, 0x01ec, 0x90ea, 0x1c00
ax_pose_terminator
sSentretPose12:
ax_pose 11, 0x01ed, 0x90eb, 0x1c00
ax_pose_terminator
sSentretPose13:
ax_pose 12, 0x01ec, 0x80f4, 0x1c00
ax_pose_terminator
sSentretPose14:
ax_pose 13, 0x01ec, 0x80f4, 0x1c00
ax_pose_terminator
sSentretPose15:
ax_pose 14, 0x01ec, 0x80f4, 0x1c00
ax_pose_terminator
sSentretPose16:
ax_pose 9, 0x01eb, 0x80f4, 0x1c00
ax_pose_terminator
sSentretPose17:
ax_pose 10, 0x01ec, 0x80f5, 0x1c00
ax_pose_terminator
sSentretPose18:
ax_pose 11, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sSentretPose19:
ax_pose 6, 0x01eb, 0x80f7, 0x1c00
ax_pose_terminator
sSentretPose20:
ax_pose 7, 0x01eb, 0x80f6, 0x1c00
ax_pose_terminator
sSentretPose21:
ax_pose 8, 0x01eb, 0x80f7, 0x1c00
ax_pose_terminator
sSentretPose22:
ax_pose 3, 0x01eb, 0x80f5, 0x1c00
ax_pose_terminator
sSentretPose23:
ax_pose 4, 0x01ea, 0x80f4, 0x1c00
ax_pose_terminator
sSentretPose24:
ax_pose 5, 0x01eb, 0x80f5, 0x1c00
ax_pose_terminator
sSentretPose25:
ax_pose 0, 0x01ea, 0x80f4, 0x1c00
ax_pose_terminator
sSentretPose26:
ax_pose 15, 0x01e1, 0x80f4, 0x1c00
ax_pose_terminator
sSentretPose27:
ax_pose 16, 0x01ea, 0x80f4, 0x1c00
ax_pose_terminator
sSentretPose28:
ax_pose 17, 0x01e8, 0x80f4, 0x1c00
ax_pose_terminator
sSentretPose29:
ax_pose 18, 0x01e4, 0x80f4, 0x1c00
ax_pose_terminator
sSentretPose30:
ax_pose 3, 0x01eb, 0x90eb, 0x1c00
ax_pose_terminator
sSentretPose31:
ax_pose 19, 0x01e0, 0x90eb, 0x1c00
ax_pose_terminator
sSentretPose32:
ax_pose 20, 0x01e8, 0x90eb, 0x1c00
ax_pose_terminator
sSentretPose33:
ax_pose 21, 0x01e5, 0x90ed, 0x1c00
ax_pose_terminator
sSentretPose34:
ax_pose 22, 0x01e2, 0x90eb, 0x1c00
ax_pose_terminator
sSentretPose35:
ax_pose 6, 0x01eb, 0x90e8, 0x1c00
ax_pose_terminator
sSentretPose36:
ax_pose 23, 0x01e0, 0x90e8, 0x1c00
ax_pose_terminator
sSentretPose37:
ax_pose 24, 0x01eb, 0x90ea, 0x1c00
ax_pose_terminator
sSentretPose38:
ax_pose 25, 0x41e6, 0x90eb, 0x1c00
ax_pose_terminator
sSentretPose39:
ax_pose 26, 0x01e3, 0x90ea, 0x1c00
ax_pose_terminator
sSentretPose40:
ax_pose 9, 0x01eb, 0x90eb, 0x1c00
ax_pose_terminator
sSentretPose41:
ax_pose 27, 0x01e1, 0x90eb, 0x1c00
ax_pose_terminator
sSentretPose42:
ax_pose 28, 0x01eb, 0x90ea, 0x1c00
ax_pose_terminator
sSentretPose43:
ax_pose 29, 0x01e3, 0x90eb, 0x1c00
ax_pose_terminator
sSentretPose44:
ax_pose 30, 0x01e1, 0x90e9, 0x1c00
ax_pose_terminator
sSentretPose45:
ax_pose 12, 0x01ec, 0x80f4, 0x1c00
ax_pose_terminator
sSentretPose46:
ax_pose 31, 0x01e1, 0x80f4, 0x1c00
ax_pose_terminator
sSentretPose47:
ax_pose 32, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sSentretPose48:
ax_pose 33, 0x01e4, 0x80f4, 0x1c00
ax_pose_terminator
sSentretPose49:
ax_pose 34, 0x01e2, 0x80f4, 0x1c00
ax_pose_terminator
sSentretPose50:
ax_pose 9, 0x01eb, 0x80f4, 0x1c00
ax_pose_terminator
sSentretPose51:
ax_pose 27, 0x01e1, 0x80f4, 0x1c00
ax_pose_terminator
sSentretPose52:
ax_pose 28, 0x01eb, 0x80f5, 0x1c00
ax_pose_terminator
sSentretPose53:
ax_pose 29, 0x01e3, 0x80f4, 0x1c00
ax_pose_terminator
sSentretPose54:
ax_pose 30, 0x01e2, 0x80f6, 0x1c00
ax_pose_terminator
sSentretPose55:
ax_pose 6, 0x01eb, 0x80f7, 0x1c00
ax_pose_terminator
sSentretPose56:
ax_pose 23, 0x01e0, 0x80f7, 0x1c00
ax_pose_terminator
sSentretPose57:
ax_pose 24, 0x01eb, 0x80f5, 0x1c00
ax_pose_terminator
sSentretPose58:
ax_pose 25, 0x41e6, 0x80f4, 0x1c00
ax_pose_terminator
sSentretPose59:
ax_pose 26, 0x01e4, 0x80f5, 0x1c00
ax_pose_terminator
sSentretPose60:
ax_pose 3, 0x01eb, 0x80f5, 0x1c00
ax_pose_terminator
sSentretPose61:
ax_pose 19, 0x01e0, 0x80f5, 0x1c00
ax_pose_terminator
sSentretPose62:
ax_pose 20, 0x01e8, 0x80f5, 0x1c00
ax_pose_terminator
sSentretPose63:
ax_pose 21, 0x01e5, 0x80f3, 0x1c00
ax_pose_terminator
sSentretPose64:
ax_pose 22, 0x01e3, 0x80f5, 0x1c00
ax_pose_terminator
sSentretPose65:
ax_pose 0, 0x01ea, 0x80f4, 0x1c00
ax_pose_terminator
sSentretPose66:
ax_pose 1, 0x01ec, 0x80f3, 0x1c00
ax_pose_terminator
sSentretPose67:
ax_pose 2, 0x01ec, 0x80f5, 0x1c00
ax_pose_terminator
sSentretPose68:
ax_pose 35, 0x01ea, 0x80f5, 0x1c00
ax_pose_terminator
sSentretPose69:
ax_pose 36, 0x81ea, 0x80f3, 0x1c00
ax_pose 37, 0x01ea, 0x80f3, 0x1c08
ax_pose_terminator
sSentretPose70:
ax_pose 37, 0x01ea, 0x80f3, 0x1c00
ax_pose_terminator
sSentretPose71:
ax_pose 3, 0x01eb, 0x90eb, 0x1c00
ax_pose_terminator
sSentretPose72:
ax_pose 4, 0x01ea, 0x90ec, 0x1c00
ax_pose_terminator
sSentretPose73:
ax_pose 5, 0x01eb, 0x90eb, 0x1c00
ax_pose_terminator
sSentretPose74:
ax_pose 38, 0x01eb, 0x90ea, 0x1c00
ax_pose_terminator
sSentretPose75:
ax_pose 39, 0x81e5, 0x90fc, 0x1c00
ax_pose 40, 0x01eb, 0x90ea, 0x1c08
ax_pose_terminator
sSentretPose76:
ax_pose 40, 0x01eb, 0x90ea, 0x1c00
ax_pose_terminator
sSentretPose77:
ax_pose 6, 0x01eb, 0x90e8, 0x1c00
ax_pose_terminator
sSentretPose78:
ax_pose 7, 0x01eb, 0x90e9, 0x1c00
ax_pose_terminator
sSentretPose79:
ax_pose 8, 0x01eb, 0x90e8, 0x1c00
ax_pose_terminator
sSentretPose80:
ax_pose 41, 0x01eb, 0x90e8, 0x1c00
ax_pose_terminator
sSentretPose81:
ax_pose 42, 0x01eb, 0x90ef, 0x1c00
ax_pose 43, 0x01eb, 0x90e9, 0x1c10
ax_pose_terminator
sSentretPose82:
ax_pose 43, 0x01eb, 0x90e9, 0x1c00
ax_pose_terminator
sSentretPose83:
ax_pose 9, 0x01eb, 0x90eb, 0x1c00
ax_pose_terminator
sSentretPose84:
ax_pose 10, 0x01ec, 0x90ea, 0x1c00
ax_pose_terminator
sSentretPose85:
ax_pose 11, 0x01ed, 0x90eb, 0x1c00
ax_pose_terminator
sSentretPose86:
ax_pose 44, 0x01eb, 0x90eb, 0x1c00
ax_pose_terminator
sSentretPose87:
ax_pose 45, 0x01eb, 0x90eb, 0x1c00
ax_pose 46, 0x41ea, 0x90eb, 0x1c10
ax_pose_terminator
sSentretPose88:
ax_pose 45, 0x01eb, 0x90eb, 0x1c00
ax_pose_terminator
sSentretPose89:
ax_pose 12, 0x01ec, 0x80f4, 0x1c00
ax_pose_terminator
sSentretPose90:
ax_pose 13, 0x01ec, 0x80f4, 0x1c00
ax_pose_terminator
sSentretPose91:
ax_pose 14, 0x01ec, 0x80f4, 0x1c00
ax_pose_terminator
sSentretPose92:
ax_pose 47, 0x01ec, 0x80f4, 0x1c00
ax_pose_terminator
sSentretPose93:
ax_pose 48, 0x01ec, 0x80f4, 0x1c00
ax_pose 49, 0x01e9, 0x80f7, 0x1c10
ax_pose_terminator
sSentretPose94:
ax_pose 48, 0x01ec, 0x80f4, 0x1c00
ax_pose_terminator
sSentretPose95:
ax_pose 9, 0x01eb, 0x80f4, 0x1c00
ax_pose_terminator
sSentretPose96:
ax_pose 10, 0x01ec, 0x80f5, 0x1c00
ax_pose_terminator
sSentretPose97:
ax_pose 11, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sSentretPose98:
ax_pose 44, 0x01eb, 0x80f4, 0x1c00
ax_pose_terminator
sSentretPose99:
ax_pose 45, 0x01eb, 0x80f4, 0x1c00
ax_pose 46, 0x41ea, 0x80f4, 0x1c10
ax_pose_terminator
sSentretPose100:
ax_pose 45, 0x01eb, 0x80f4, 0x1c00
ax_pose_terminator
sSentretPose101:
ax_pose 6, 0x01eb, 0x80f7, 0x1c00
ax_pose_terminator
sSentretPose102:
ax_pose 7, 0x01eb, 0x80f6, 0x1c00
ax_pose_terminator
sSentretPose103:
ax_pose 8, 0x01eb, 0x80f7, 0x1c00
ax_pose_terminator
sSentretPose104:
ax_pose 41, 0x01eb, 0x80f7, 0x1c00
ax_pose_terminator
sSentretPose105:
ax_pose 42, 0x01eb, 0x80f0, 0x1c00
ax_pose 43, 0x01eb, 0x80f6, 0x1c10
ax_pose_terminator
sSentretPose106:
ax_pose 43, 0x01eb, 0x80f6, 0x1c00
ax_pose_terminator
sSentretPose107:
ax_pose 3, 0x01eb, 0x80f5, 0x1c00
ax_pose_terminator
sSentretPose108:
ax_pose 4, 0x01ea, 0x80f4, 0x1c00
ax_pose_terminator
sSentretPose109:
ax_pose 5, 0x01eb, 0x80f5, 0x1c00
ax_pose_terminator
sSentretPose110:
ax_pose 38, 0x01eb, 0x80f6, 0x1c00
ax_pose_terminator
sSentretPose111:
ax_pose 39, 0x81e5, 0x80f4, 0x1c00
ax_pose 40, 0x01eb, 0x80f6, 0x1c08
ax_pose_terminator
sSentretPose112:
ax_pose 40, 0x01eb, 0x80f6, 0x1c00
ax_pose_terminator
sSentretPose113:
ax_pose 0, 0x01ea, 0x80f4, 0x1c00
ax_pose_terminator
sSentretPose114:
ax_pose 18, 0x01e8, 0x80f4, 0x1c00
ax_pose_terminator
sSentretPose115:
ax_pose 3, 0x01eb, 0x90eb, 0x1c00
ax_pose_terminator
sSentretPose116:
ax_pose 22, 0x01eb, 0x90eb, 0x1c00
ax_pose_terminator
sSentretPose117:
ax_pose 6, 0x01eb, 0x90e8, 0x1c00
ax_pose_terminator
sSentretPose118:
ax_pose 26, 0x01eb, 0x90ea, 0x1c00
ax_pose_terminator
sSentretPose119:
ax_pose 9, 0x01eb, 0x90eb, 0x1c00
ax_pose_terminator
sSentretPose120:
ax_pose 30, 0x01ec, 0x90e9, 0x1c00
ax_pose_terminator
sSentretPose121:
ax_pose 12, 0x01ec, 0x80f4, 0x1c00
ax_pose_terminator
sSentretPose122:
ax_pose 34, 0x01ee, 0x80f4, 0x1c00
ax_pose_terminator
sSentretPose123:
ax_pose 9, 0x01eb, 0x80f4, 0x1c00
ax_pose_terminator
sSentretPose124:
ax_pose 30, 0x01ec, 0x80f6, 0x1c00
ax_pose_terminator
sSentretPose125:
ax_pose 6, 0x01eb, 0x80f7, 0x1c00
ax_pose_terminator
sSentretPose126:
ax_pose 26, 0x01eb, 0x80f5, 0x1c00
ax_pose_terminator
sSentretPose127:
ax_pose 3, 0x01eb, 0x80f5, 0x1c00
ax_pose_terminator
sSentretPose128:
ax_pose 22, 0x01eb, 0x80f5, 0x1c00
ax_pose_terminator
sSentretPose129:
ax_pose 0, 0x01ea, 0x80f4, 0x1c00
ax_pose_terminator
sSentretPose130:
ax_pose 15, 0x01e1, 0x80f4, 0x1c00
ax_pose_terminator
sSentretPose131:
ax_pose 3, 0x01eb, 0x90eb, 0x1c00
ax_pose_terminator
sSentretPose132:
ax_pose 19, 0x01e0, 0x90eb, 0x1c00
ax_pose_terminator
sSentretPose133:
ax_pose 6, 0x01eb, 0x90e8, 0x1c00
ax_pose_terminator
sSentretPose134:
ax_pose 23, 0x01e0, 0x90e8, 0x1c00
ax_pose_terminator
sSentretPose135:
ax_pose 9, 0x01eb, 0x90eb, 0x1c00
ax_pose_terminator
sSentretPose136:
ax_pose 27, 0x01e1, 0x90eb, 0x1c00
ax_pose_terminator
sSentretPose137:
ax_pose 12, 0x01ec, 0x80f4, 0x1c00
ax_pose_terminator
sSentretPose138:
ax_pose 31, 0x01e1, 0x80f4, 0x1c00
ax_pose_terminator
sSentretPose139:
ax_pose 9, 0x01eb, 0x80f4, 0x1c00
ax_pose_terminator
sSentretPose140:
ax_pose 27, 0x01e1, 0x80f4, 0x1c00
ax_pose_terminator
sSentretPose141:
ax_pose 6, 0x01eb, 0x80f7, 0x1c00
ax_pose_terminator
sSentretPose142:
ax_pose 23, 0x01e0, 0x80f7, 0x1c00
ax_pose_terminator
sSentretPose143:
ax_pose 3, 0x01eb, 0x80f5, 0x1c00
ax_pose_terminator
sSentretPose144:
ax_pose 19, 0x01e0, 0x80f5, 0x1c00
ax_pose_terminator
sSentretPose145:
ax_pose 50, 0x01ec, 0x80f6, 0x1c00
ax_pose_terminator
sSentretPose146:
ax_pose 51, 0x01ec, 0x80f6, 0x1c00
ax_pose_terminator
sSentretPose147:
ax_pose 52, 0x01e2, 0x80f2, 0x1c00
ax_pose_terminator
sSentretPose148:
ax_pose 53, 0x01e3, 0x90e7, 0x1c00
ax_pose_terminator
sSentretPose149:
ax_pose 54, 0x01e3, 0x90e7, 0x1c00
ax_pose_terminator
sSentretPose150:
ax_pose 55, 0x01e9, 0x90e8, 0x1c00
ax_pose_terminator
sSentretPose151:
ax_pose 56, 0x01ea, 0x80f2, 0x1c00
ax_pose_terminator
sSentretPose152:
ax_pose 55, 0x01e9, 0x80f9, 0x1c00
ax_pose_terminator
sSentretPose153:
ax_pose 54, 0x01e3, 0x80f9, 0x1c00
ax_pose_terminator
sSentretPose154:
ax_pose 53, 0x01e3, 0x80fa, 0x1c00
ax_pose_terminator
sSentretPose155:
ax_pose 0, 0x01ea, 0x80f4, 0x1c00
ax_pose_terminator
sSentretPose156:
ax_pose 15, 0x01e1, 0x80f4, 0x1c00
ax_pose_terminator
sSentretPose157:
ax_pose 16, 0x01ea, 0x80f4, 0x1c00
ax_pose_terminator
sSentretPose158:
ax_pose 17, 0x01e8, 0x80f4, 0x1c00
ax_pose_terminator
sSentretPose159:
ax_pose 18, 0x01e4, 0x80f4, 0x1c00
ax_pose_terminator
sSentretPose160:
ax_pose 3, 0x01eb, 0x90eb, 0x1c00
ax_pose_terminator
sSentretPose161:
ax_pose 19, 0x01e0, 0x90eb, 0x1c00
ax_pose_terminator
sSentretPose162:
ax_pose 20, 0x01e8, 0x90eb, 0x1c00
ax_pose_terminator
sSentretPose163:
ax_pose 21, 0x01e5, 0x90ed, 0x1c00
ax_pose_terminator
sSentretPose164:
ax_pose 22, 0x01e2, 0x90eb, 0x1c00
ax_pose_terminator
sSentretPose165:
ax_pose 6, 0x01eb, 0x90e8, 0x1c00
ax_pose_terminator
sSentretPose166:
ax_pose 23, 0x01e0, 0x90e8, 0x1c00
ax_pose_terminator
sSentretPose167:
ax_pose 24, 0x01eb, 0x90ea, 0x1c00
ax_pose_terminator
sSentretPose168:
ax_pose 25, 0x41e6, 0x90eb, 0x1c00
ax_pose_terminator
sSentretPose169:
ax_pose 26, 0x01e3, 0x90ea, 0x1c00
ax_pose_terminator
sSentretPose170:
ax_pose 9, 0x01eb, 0x90eb, 0x1c00
ax_pose_terminator
sSentretPose171:
ax_pose 27, 0x01e1, 0x90eb, 0x1c00
ax_pose_terminator
sSentretPose172:
ax_pose 28, 0x01eb, 0x90ea, 0x1c00
ax_pose_terminator
sSentretPose173:
ax_pose 29, 0x01e3, 0x90eb, 0x1c00
ax_pose_terminator
sSentretPose174:
ax_pose 30, 0x01e1, 0x90e9, 0x1c00
ax_pose_terminator
sSentretPose175:
ax_pose 12, 0x01ec, 0x80f4, 0x1c00
ax_pose_terminator
sSentretPose176:
ax_pose 31, 0x01e1, 0x80f4, 0x1c00
ax_pose_terminator
sSentretPose177:
ax_pose 32, 0x01ed, 0x80f4, 0x1c00
ax_pose_terminator
sSentretPose178:
ax_pose 33, 0x01e4, 0x80f4, 0x1c00
ax_pose_terminator
sSentretPose179:
ax_pose 34, 0x01e2, 0x80f4, 0x1c00
ax_pose_terminator
sSentretPose180:
ax_pose 9, 0x01eb, 0x80f4, 0x1c00
ax_pose_terminator
sSentretPose181:
ax_pose 27, 0x01e1, 0x80f4, 0x1c00
ax_pose_terminator
sSentretPose182:
ax_pose 28, 0x01eb, 0x80f5, 0x1c00
ax_pose_terminator
sSentretPose183:
ax_pose 29, 0x01e3, 0x80f4, 0x1c00
ax_pose_terminator
sSentretPose184:
ax_pose 30, 0x01e2, 0x80f6, 0x1c00
ax_pose_terminator
sSentretPose185:
ax_pose 6, 0x01eb, 0x80f7, 0x1c00
ax_pose_terminator
sSentretPose186:
ax_pose 23, 0x01e0, 0x80f7, 0x1c00
ax_pose_terminator
sSentretPose187:
ax_pose 24, 0x01eb, 0x80f5, 0x1c00
ax_pose_terminator
sSentretPose188:
ax_pose 25, 0x41e6, 0x80f4, 0x1c00
ax_pose_terminator
sSentretPose189:
ax_pose 26, 0x01e4, 0x80f5, 0x1c00
ax_pose_terminator
sSentretPose190:
ax_pose 3, 0x01eb, 0x80f5, 0x1c00
ax_pose_terminator
sSentretPose191:
ax_pose 19, 0x01e0, 0x80f5, 0x1c00
ax_pose_terminator
sSentretPose192:
ax_pose 20, 0x01e8, 0x80f5, 0x1c00
ax_pose_terminator
sSentretPose193:
ax_pose 21, 0x01e5, 0x80f3, 0x1c00
ax_pose_terminator
sSentretPose194:
ax_pose 22, 0x01e3, 0x80f5, 0x1c00
ax_pose_terminator
sSentretPose195:
ax_pose 0, 0x01ea, 0x80f4, 0x1c00
ax_pose_terminator
sSentretPose196:
ax_pose 3, 0x01eb, 0x80f5, 0x1c00
ax_pose_terminator
sSentretPose197:
ax_pose 6, 0x01eb, 0x80f8, 0x1c00
ax_pose_terminator
sSentretPose198:
ax_pose 9, 0x01eb, 0x80f6, 0x1c00
ax_pose_terminator
sSentretPose199:
ax_pose 12, 0x01ec, 0x80f4, 0x1c00
ax_pose_terminator
sSentretPose200:
ax_pose 9, 0x01eb, 0x90e9, 0x1c00
ax_pose_terminator
sSentretPose201:
ax_pose 6, 0x01eb, 0x90e7, 0x1c00
ax_pose_terminator
sSentretPose202:
ax_pose 3, 0x01eb, 0x90ea, 0x1c00
ax_pose_terminator
sSentretPose203:
ax_pose 15, 0x01e1, 0x80f4, 0x1c00
ax_pose_terminator
sSentretPose204:
ax_pose 19, 0x01e1, 0x90ec, 0x1c00
ax_pose_terminator
sSentretPose205:
ax_pose 23, 0x01e1, 0x90ea, 0x1c00
ax_pose_terminator
sSentretPose206:
ax_pose 27, 0x01e1, 0x90ec, 0x1c00
ax_pose_terminator
sSentretPose207:
ax_pose 31, 0x01e1, 0x80f4, 0x1c00
ax_pose_terminator
sSentretPose208:
ax_pose 27, 0x01e1, 0x80f4, 0x1c00
ax_pose_terminator
sSentretPose209:
ax_pose 23, 0x01e1, 0x80f6, 0x1c00
ax_pose_terminator
sSentretPose210:
ax_pose 19, 0x01e1, 0x80f4, 0x1c00
ax_pose_terminator
sSentretPose211:
ax_pose 0, 0x01ea, 0x80f4, 0x1c00
ax_pose_terminator
sSentretPose212:
ax_pose 15, 0x01e1, 0x80f4, 0x1c00
ax_pose_terminator
sSentretPose213:
ax_pose 18, 0x01e6, 0x80f4, 0x1c00
ax_pose_terminator
sSentretPose214:
ax_pose 3, 0x01eb, 0x90eb, 0x1c00
ax_pose_terminator
sSentretPose215:
ax_pose 19, 0x01e8, 0x90eb, 0x1c00
ax_pose_terminator
sSentretPose216:
ax_pose 22, 0x01e9, 0x90e9, 0x1c00
ax_pose_terminator
sSentretPose217:
ax_pose 6, 0x01eb, 0x90e8, 0x1c00
ax_pose_terminator
sSentretPose218:
ax_pose 23, 0x01e4, 0x90e8, 0x1c00
ax_pose_terminator
sSentretPose219:
ax_pose 26, 0x01e7, 0x90e7, 0x1c00
ax_pose_terminator
sSentretPose220:
ax_pose 9, 0x01eb, 0x90eb, 0x1c00
ax_pose_terminator
sSentretPose221:
ax_pose 27, 0x01e9, 0x90eb, 0x1c00
ax_pose_terminator
sSentretPose222:
ax_pose 30, 0x01e9, 0x90e9, 0x1c00
ax_pose_terminator
sSentretPose223:
ax_pose 12, 0x01ec, 0x80f4, 0x1c00
ax_pose_terminator
sSentretPose224:
ax_pose 31, 0x01ea, 0x80f4, 0x1c00
ax_pose_terminator
sSentretPose225:
ax_pose 34, 0x01eb, 0x80f4, 0x1c00
ax_pose_terminator
sSentretPose226:
ax_pose 9, 0x01eb, 0x80f5, 0x1c00
ax_pose_terminator
sSentretPose227:
ax_pose 27, 0x01e9, 0x80f5, 0x1c00
ax_pose_terminator
sSentretPose228:
ax_pose 30, 0x01e9, 0x80f7, 0x1c00
ax_pose_terminator
sSentretPose229:
ax_pose 6, 0x01eb, 0x80f8, 0x1c00
ax_pose_terminator
sSentretPose230:
ax_pose 23, 0x01e4, 0x80f8, 0x1c00
ax_pose_terminator
sSentretPose231:
ax_pose 26, 0x01e7, 0x80f9, 0x1c00
ax_pose_terminator
sSentretPose232:
ax_pose 3, 0x01eb, 0x80f5, 0x1c00
ax_pose_terminator
sSentretPose233:
ax_pose 19, 0x01e8, 0x80f5, 0x1c00
ax_pose_terminator
sSentretPose234:
ax_pose 22, 0x01e9, 0x80f7, 0x1c00
ax_pose_terminator
sSentretPose235:
ax_pose 37, 0x01ea, 0x80f3, 0x1c00
ax_pose_terminator
sSentretPose236:
ax_pose 40, 0x01eb, 0x80f5, 0x1c00
ax_pose_terminator
sSentretPose237:
ax_pose 43, 0x01eb, 0x80f6, 0x1c00
ax_pose_terminator
sSentretPose238:
ax_pose 45, 0x01eb, 0x80f4, 0x1c00
ax_pose_terminator
sSentretPose239:
ax_pose 48, 0x01ec, 0x80f4, 0x1c00
ax_pose_terminator
sSentretPose240:
ax_pose 45, 0x01eb, 0x90eb, 0x1c00
ax_pose_terminator
sSentretPose241:
ax_pose 43, 0x01eb, 0x90e9, 0x1c00
ax_pose_terminator
sSentretPose242:
ax_pose 40, 0x01eb, 0x90eb, 0x1c00
ax_pose_terminator
sSentretPose243:
ax_pose 0, 0x01ea, 0x80f4, 0x1c00
ax_pose_terminator
sSentretPose244:
ax_pose 3, 0x01eb, 0x80f4, 0x1c00
ax_pose_terminator
sSentretPose245:
ax_pose 6, 0x01eb, 0x80f7, 0x1c00
ax_pose_terminator
sSentretPose246:
ax_pose 9, 0x01eb, 0x80f4, 0x1c00
ax_pose_terminator
sSentretPose247:
ax_pose 12, 0x01ec, 0x80f4, 0x1c00
ax_pose_terminator
sSentretPose248:
ax_pose 9, 0x01eb, 0x90eb, 0x1c00
ax_pose_terminator
sSentretPose249:
ax_pose 6, 0x01eb, 0x90e8, 0x1c00
ax_pose_terminator
sSentretPose250:
ax_pose 3, 0x01eb, 0x90eb, 0x1c00
ax_pose_terminator
.align 2
sSentretAnims_1_1:
ax_anim 8, 0, 0, 0, 0, 0, 0,
ax_anim 10, 0, 1, 0, 0, 0, 0,
ax_anim 8, 0, 0, 0, 0, 0, 0,
ax_anim 10, 0, 2, 0, 0, 0, 0,
ax_anim_terminator
sSentretAnims_1_2:
ax_anim 8, 0, 3, 0, 0, 0, 0,
ax_anim 10, 0, 4, 0, 0, 0, 0,
ax_anim 8, 0, 3, 0, 0, 0, 0,
ax_anim 10, 0, 5, 0, 0, 0, 0,
ax_anim_terminator
sSentretAnims_1_3:
ax_anim 8, 0, 6, 0, 0, 0, 0,
ax_anim 10, 0, 7, 0, 0, 0, 0,
ax_anim 8, 0, 6, 0, 0, 0, 0,
ax_anim 10, 0, 8, 0, 0, 0, 0,
ax_anim_terminator
sSentretAnims_1_4:
ax_anim 8, 0, 9, 0, 0, 0, 0,
ax_anim 10, 0, 10, 0, 0, 0, 0,
ax_anim 8, 0, 9, 0, 0, 0, 0,
ax_anim 10, 0, 11, 0, 0, 0, 0,
ax_anim_terminator
sSentretAnims_1_5:
ax_anim 8, 0, 12, 0, 0, 0, 0,
ax_anim 10, 0, 13, 0, 0, 0, 0,
ax_anim 8, 0, 12, 0, 0, 0, 0,
ax_anim 10, 0, 14, 0, 0, 0, 0,
ax_anim_terminator
sSentretAnims_1_6:
ax_anim 8, 0, 15, 0, 0, 0, 0,
ax_anim 10, 0, 16, 0, 0, 0, 0,
ax_anim 8, 0, 15, 0, 0, 0, 0,
ax_anim 10, 0, 17, 0, 0, 0, 0,
ax_anim_terminator
sSentretAnims_1_7:
ax_anim 8, 0, 18, 0, 0, 0, 0,
ax_anim 10, 0, 19, 0, 0, 0, 0,
ax_anim 8, 0, 18, 0, 0, 0, 0,
ax_anim 10, 0, 20, 0, 0, 0, 0,
ax_anim_terminator
sSentretAnims_1_8:
ax_anim 8, 0, 21, 0, 0, 0, 0,
ax_anim 10, 0, 22, 0, 0, 0, 0,
ax_anim 8, 0, 21, 0, 0, 0, 0,
ax_anim 10, 0, 23, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sSentretAnims_2_1:
ax_anim 6, 0, 25, 0, 0, 0, 0,
ax_anim 4, 0, 26, 0, 0, 0, 0,
ax_anim 1, 0, 27, 0, 2, 0, 5,
ax_anim 1, 2, 27, 0, 6, 0, 11,
ax_anim 1, 0, 27, 0, 15, 0, 17,
ax_anim 2, 0, 28, 0, 28, 0, 22,
ax_anim 2, 1, 28, 1, 28, 1, 22,
ax_anim 2, 0, 28, 0, 28, 0, 22,
ax_anim 2, 0, 28, 1, 28, 1, 22,
ax_anim 2, 0, 28, 0, 28, 0, 22,
ax_anim 2, 0, 24, 0, 0, 0, 6,
ax_anim_terminator
sSentretAnims_2_2:
ax_anim 6, 0, 30, 0, 0, 0, 0,
ax_anim 4, 0, 31, 0, 0, 0, 0,
ax_anim 1, 0, 32, 5, 0, 5, 5,
ax_anim 1, 2, 32, 11, 9, 11, 11,
ax_anim 1, 0, 32, 15, 20, 17, 17,
ax_anim 2, 0, 33, 19, 30, 19, 21,
ax_anim 2, 1, 33, 20, 29, 20, 20,
ax_anim 2, 0, 33, 19, 30, 19, 21,
ax_anim 2, 0, 33, 20, 29, 20, 20,
ax_anim 2, 0, 33, 19, 30, 19, 21,
ax_anim 2, 0, 29, 6, 0, 6, 6,
ax_anim_terminator
sSentretAnims_2_3:
ax_anim 6, 0, 35, 0, 0, 0, 0,
ax_anim 4, 0, 36, 0, 0, 0, 0,
ax_anim 1, 0, 37, 6, 1, 8, 0,
ax_anim 1, 2, 37, 13, 3, 13, 0,
ax_anim 1, 0, 37, 15, 4, 15, 0,
ax_anim 2, 0, 38, 20, 9, 20, 0,
ax_anim 2, 1, 38, 20, 10, 20, 1,
ax_anim 2, 0, 38, 20, 9, 20, 0,
ax_anim 2, 0, 38, 20, 10, 20, 1,
ax_anim 2, 0, 38, 20, 9, 20, 0,
ax_anim 2, 0, 34, 6, -7, 6, 0,
ax_anim_terminator
sSentretAnims_2_4:
ax_anim 6, 0, 40, 0, 0, 0, 0,
ax_anim 4, 0, 41, 0, 0, 0, 0,
ax_anim 1, 0, 42, 3, -2, 3, -3,
ax_anim 1, 2, 42, 8, -9, 8, -8,
ax_anim 1, 0, 42, 15, -11, 15, -15,
ax_anim 2, 0, 43, 20, -10, 20, -20,
ax_anim 2, 1, 43, 21, -9, 21, -19,
ax_anim 2, 0, 43, 20, -10, 20, -20,
ax_anim 2, 0, 43, 21, -9, 21, -19,
ax_anim 2, 0, 43, 20, -10, 20, -20,
ax_anim 2, 0, 39, 6, -6, 6, -6,
ax_anim_terminator
sSentretAnims_2_5:
ax_anim 6, 0, 45, 0, 0, 0, 0,
ax_anim 4, 0, 46, 0, 0, 0, 0,
ax_anim 1, 0, 47, 0, -4, 0, -6,
ax_anim 1, 2, 47, 0, -6, 0, -12,
ax_anim 1, 0, 47, 0, -9, 0, -17,
ax_anim 2, 0, 48, 0, -11, 0, -23,
ax_anim 2, 1, 48, 1, -11, 1, -23,
ax_anim 2, 0, 48, 0, -11, 0, -23,
ax_anim 2, 0, 48, 1, -11, 1, -23,
ax_anim 2, 0, 48, 0, -11, 0, -23,
ax_anim 2, 0, 44, 0, -6, 0, -6,
ax_anim_terminator
sSentretAnims_2_6:
ax_anim 6, 0, 50, 0, 0, 0, 0,
ax_anim 4, 0, 51, 0, 0, 0, 0,
ax_anim 1, 0, 52, -3, -2, -3, -3,
ax_anim 1, 2, 52, -8, -9, -8, -8,
ax_anim 1, 0, 52, -15, -11, -15, -15,
ax_anim 2, 0, 53, -20, -10, -20, -20,
ax_anim 2, 1, 53, -21, -9, -21, -19,
ax_anim 2, 0, 53, -20, -10, -20, -20,
ax_anim 2, 0, 53, -21, -9, -21, -19,
ax_anim 2, 0, 53, -20, -10, -20, -20,
ax_anim 2, 0, 49, -6, -6, -6, -6,
ax_anim_terminator
sSentretAnims_2_7:
ax_anim 6, 0, 55, 0, 0, 0, 0,
ax_anim 4, 0, 56, 0, 0, 0, 0,
ax_anim 1, 0, 57, -8, 0, -8, 0,
ax_anim 1, 2, 57, -13, 3, -13, 0,
ax_anim 1, 0, 57, -15, 4, -15, 0,
ax_anim 2, 0, 58, -20, 9, -20, 0,
ax_anim 2, 1, 58, -20, 10, -20, 1,
ax_anim 2, 0, 58, -20, 9, -20, 0,
ax_anim 2, 0, 58, -20, 10, -20, 1,
ax_anim 2, 0, 58, -20, 9, -20, 0,
ax_anim 2, 0, 54, -6, -1, -6, 0,
ax_anim_terminator
sSentretAnims_2_8:
ax_anim 6, 0, 60, 0, 0, 0, 0,
ax_anim 4, 0, 61, 0, 0, 0, 0,
ax_anim 1, 0, 62, -5, 0, -5, 5,
ax_anim 1, 2, 62, -11, 9, -11, 11,
ax_anim 1, 0, 62, -15, 20, -17, 17,
ax_anim 2, 0, 63, -19, 30, -19, 21,
ax_anim 2, 1, 63, -20, 29, -20, 20,
ax_anim 2, 0, 63, -19, 30, -19, 21,
ax_anim 2, 0, 63, -20, 29, -20, 20,
ax_anim 2, 0, 63, -19, 30, -19, 21,
ax_anim 2, 0, 59, -6, 0, -6, 6,
ax_anim_terminator
.align 2
sSentretAnims_3_1:
ax_anim 2, 0, 66, 0, -2, 0, -2,
ax_anim 2, 0, 67, 0, -4, 0, -4,
ax_anim 6, 0, 67, 0, -5, 0, -5,
ax_anim 1, 2, 67, 0, -2, 0, -2,
ax_anim 1, 0, 67, 0, 7, 0, 7,
ax_anim 2, 0, 68, 0, 16, 0, 16,
ax_anim 2, 1, 69, 1, 16, 1, 16,
ax_anim 2, 0, 69, 0, 16, 0, 16,
ax_anim 2, 0, 69, 1, 16, 1, 16,
ax_anim 2, 0, 69, 0, 16, 0, 16,
ax_anim 2, 0, 69, 1, 16, 1, 16,
ax_anim 2, 0, 69, 0, 16, 0, 16,
ax_anim 2, 0, 64, 0, 10, 0, 10,
ax_anim 2, 0, 64, 0, 4, 0, 4,
ax_anim_terminator
sSentretAnims_3_2:
ax_anim 2, 0, 72, -2, -2, -2, -2,
ax_anim 2, 0, 73, -4, -4, -4, -4,
ax_anim 6, 0, 73, -5, -5, -5, -5,
ax_anim 1, 2, 73, -2, -2, -2, -2,
ax_anim 1, 0, 73, 7, 9, 7, 9,
ax_anim 2, 0, 74, 16, 19, 16, 19,
ax_anim 2, 1, 75, 17, 18, 17, 18,
ax_anim 2, 0, 75, 16, 19, 16, 19,
ax_anim 2, 0, 75, 17, 18, 17, 18,
ax_anim 2, 0, 75, 16, 19, 16, 19,
ax_anim 2, 0, 75, 17, 18, 17, 18,
ax_anim 2, 0, 75, 16, 19, 16, 19,
ax_anim 2, 0, 70, 10, 12, 10, 12,
ax_anim 2, 0, 70, 4, 5, 4, 5,
ax_anim_terminator
sSentretAnims_3_3:
ax_anim 2, 0, 78, -2, 0, -2, 0,
ax_anim 2, 0, 79, -4, 0, -4, 0,
ax_anim 6, 0, 79, -5, 0, -5, 0,
ax_anim 1, 2, 79, -2, 0, -2, 0,
ax_anim 1, 0, 79, 7, 0, 7, 0,
ax_anim 2, 0, 80, 15, 0, 15, 0,
ax_anim 2, 1, 81, 15, 1, 15, 1,
ax_anim 2, 0, 81, 15, 0, 15, 0,
ax_anim 2, 0, 81, 15, 1, 15, 1,
ax_anim 2, 0, 81, 15, 0, 15, 0,
ax_anim 2, 0, 81, 15, 1, 15, 1,
ax_anim 2, 0, 81, 15, 0, 15, 0,
ax_anim 2, 0, 76, 10, 0, 10, 0,
ax_anim 2, 0, 76, 4, 0, 4, 0,
ax_anim_terminator
sSentretAnims_3_4:
ax_anim 2, 0, 84, -2, 2, -2, 2,
ax_anim 2, 0, 85, -4, 4, -4, 4,
ax_anim 6, 0, 85, -5, 5, -5, 5,
ax_anim 1, 2, 85, -2, 2, -2, 2,
ax_anim 1, 0, 85, 8, -9, 8, -9,
ax_anim 2, 0, 86, 18, -19, 18, -19,
ax_anim 2, 1, 87, 19, -18, 19, -18,
ax_anim 2, 0, 87, 18, -19, 18, -19,
ax_anim 2, 0, 87, 19, -18, 19, -18,
ax_anim 2, 0, 87, 18, -19, 18, -19,
ax_anim 2, 0, 87, 19, -18, 19, -18,
ax_anim 2, 0, 87, 18, -19, 18, -19,
ax_anim 2, 0, 82, 11, -12, 11, -12,
ax_anim 2, 0, 82, 4, -5, 4, -5,
ax_anim_terminator
sSentretAnims_3_5:
ax_anim 2, 0, 90, 0, 2, 0, 2,
ax_anim 2, 0, 91, 0, 4, 0, 4,
ax_anim 6, 0, 91, 0, 5, 0, 5,
ax_anim 1, 2, 91, 0, 2, 0, 2,
ax_anim 1, 0, 91, 0, -7, 0, -7,
ax_anim 2, 0, 92, 0, -16, 0, -16,
ax_anim 2, 1, 93, 1, -16, 1, -16,
ax_anim 2, 0, 93, 0, -16, 0, -16,
ax_anim 2, 0, 93, 1, -16, 1, -16,
ax_anim 2, 0, 93, 0, -16, 0, -16,
ax_anim 2, 0, 93, 1, -16, 1, -16,
ax_anim 2, 0, 93, 0, -16, 0, -16,
ax_anim 2, 0, 88, 0, -10, 0, -10,
ax_anim 2, 0, 88, 0, -4, 0, -4,
ax_anim_terminator
sSentretAnims_3_6:
ax_anim 2, 0, 96, 2, 2, 2, 2,
ax_anim 2, 0, 97, 4, 4, 4, 4,
ax_anim 6, 0, 97, 5, 5, 5, 5,
ax_anim 1, 2, 97, 2, 2, 2, 2,
ax_anim 1, 0, 97, -8, -9, -8, -9,
ax_anim 2, 0, 98, -18, -19, -18, -19,
ax_anim 2, 1, 99, -19, -18, -19, -18,
ax_anim 2, 0, 99, -18, -19, -18, -19,
ax_anim 2, 0, 99, -19, -18, -19, -18,
ax_anim 2, 0, 99, -18, -19, -18, -19,
ax_anim 2, 0, 99, -19, -18, -19, -18,
ax_anim 2, 0, 99, -18, -19, -18, -19,
ax_anim 2, 0, 94, -11, -12, -11, -12,
ax_anim 2, 0, 94, -4, -5, -4, -5,
ax_anim_terminator
sSentretAnims_3_7:
ax_anim 2, 0, 102, 2, 0, 2, 0,
ax_anim 2, 0, 103, 4, 0, 4, 0,
ax_anim 6, 0, 103, 5, 0, 5, 0,
ax_anim 1, 2, 103, 2, 0, 2, 0,
ax_anim 1, 0, 103, -7, 0, -7, 0,
ax_anim 2, 0, 104, -15, 0, -15, 0,
ax_anim 2, 1, 105, -15, 1, -15, 1,
ax_anim 2, 0, 105, -15, 0, -15, 0,
ax_anim 2, 0, 105, -15, 1, -15, 1,
ax_anim 2, 0, 105, -15, 0, -15, 0,
ax_anim 2, 0, 105, -15, 1, -15, 1,
ax_anim 2, 0, 105, -15, 0, -15, 0,
ax_anim 2, 0, 100, -10, 0, -10, 0,
ax_anim 2, 0, 100, -4, 0, -4, 0,
ax_anim_terminator
sSentretAnims_3_8:
ax_anim 2, 0, 108, 2, -2, 2, -2,
ax_anim 2, 0, 109, 4, -4, 4, -4,
ax_anim 6, 0, 109, 5, -5, 5, -5,
ax_anim 1, 2, 109, 2, -2, 2, -2,
ax_anim 1, 0, 109, -7, 9, -7, 9,
ax_anim 2, 0, 110, -16, 19, -16, 19,
ax_anim 2, 1, 111, -17, 18, -17, 18,
ax_anim 2, 0, 111, -16, 19, -16, 19,
ax_anim 2, 0, 111, -17, 18, -17, 18,
ax_anim 2, 0, 111, -16, 19, -16, 19,
ax_anim 2, 0, 111, -17, 18, -17, 18,
ax_anim 2, 0, 111, -16, 19, -16, 19,
ax_anim 2, 0, 106, -10, 12, -10, 12,
ax_anim 2, 0, 106, -4, 5, -4, 5,
ax_anim_terminator
.align 2
sSentretAnims_4_1:
ax_anim 2, 0, 112, 0, -2, 0, -2,
ax_anim 6, 2, 112, 0, -3, 0, -3,
ax_anim 2, 0, 112, 0, -1, 0, -1,
ax_anim 2, 1, 113, 0, 3, 0, 2,
ax_anim 2, 0, 113, 1, 3, 1, 2,
ax_anim 2, 0, 113, 0, 3, 0, 2,
ax_anim 2, 0, 113, 1, 3, 1, 2,
ax_anim 2, 0, 113, 0, 3, 0, 2,
ax_anim 2, 0, 113, 1, 3, 1, 2,
ax_anim 2, 0, 113, 0, 3, 0, 2,
ax_anim 2, 0, 112, 0, 1, 0, 1,
ax_anim_terminator
sSentretAnims_4_2:
ax_anim 2, 0, 114, -2, -2, -2, -2,
ax_anim 6, 2, 114, -3, -3, -3, -3,
ax_anim 2, 0, 114, -1, -1, -1, -1,
ax_anim 2, 1, 115, 2, 2, 1, 1,
ax_anim 2, 0, 115, 3, 1, 2, 0,
ax_anim 2, 0, 115, 2, 2, 1, 1,
ax_anim 2, 0, 115, 3, 1, 2, 0,
ax_anim 2, 0, 115, 2, 2, 1, 1,
ax_anim 2, 0, 115, 3, 1, 2, 0,
ax_anim 2, 0, 115, 2, 2, 1, 1,
ax_anim 2, 0, 114, 1, 1, 1, 1,
ax_anim_terminator
sSentretAnims_4_3:
ax_anim 2, 0, 116, -2, 0, -2, 0,
ax_anim 6, 2, 116, -3, 0, -3, 0,
ax_anim 2, 0, 116, -1, 0, -1, 0,
ax_anim 2, 1, 117, 2, 0, 2, 0,
ax_anim 2, 0, 117, 2, 1, 2, 1,
ax_anim 2, 0, 117, 2, 0, 2, 0,
ax_anim 2, 0, 117, 2, 1, 2, 1,
ax_anim 2, 0, 117, 2, 0, 2, 0,
ax_anim 2, 0, 117, 2, 1, 2, 1,
ax_anim 2, 0, 117, 2, 0, 2, 0,
ax_anim 2, 0, 116, 1, 0, 1, 0,
ax_anim_terminator
sSentretAnims_4_4:
ax_anim 2, 0, 118, -2, 2, -2, 2,
ax_anim 6, 2, 118, -3, 3, -3, 3,
ax_anim 2, 0, 118, -1, 1, -1, 1,
ax_anim 2, 1, 119, 2, -2, 1, -1,
ax_anim 2, 0, 119, 3, -1, 2, 0,
ax_anim 2, 0, 119, 2, -2, 1, -1,
ax_anim 2, 0, 119, 3, -1, 2, 0,
ax_anim 2, 0, 119, 2, -2, 1, -1,
ax_anim 2, 0, 119, 3, -1, 2, 0,
ax_anim 2, 0, 119, 2, -2, 1, -1,
ax_anim 2, 0, 118, 1, -1, 1, -1,
ax_anim_terminator
sSentretAnims_4_5:
ax_anim 2, 0, 120, 0, 2, 0, 2,
ax_anim 6, 2, 120, 0, 3, 0, 3,
ax_anim 2, 0, 120, 0, 1, 0, 1,
ax_anim 2, 1, 121, 0, -3, 0, -2,
ax_anim 2, 0, 121, 1, -3, 1, -2,
ax_anim 2, 0, 121, 0, -3, 0, -2,
ax_anim 2, 0, 121, 1, -3, 1, -2,
ax_anim 2, 0, 121, 0, -3, 0, -2,
ax_anim 2, 0, 121, 1, -3, 1, -2,
ax_anim 2, 0, 121, 0, -3, 0, -2,
ax_anim 2, 0, 120, 0, -1, 0, -1,
ax_anim_terminator
sSentretAnims_4_6:
ax_anim 2, 0, 122, 2, 2, 2, 2,
ax_anim 6, 2, 122, 3, 3, 3, 3,
ax_anim 2, 0, 122, 1, 1, 1, 1,
ax_anim 2, 1, 123, -2, -2, -1, -1,
ax_anim 2, 0, 123, -3, -1, -2, 0,
ax_anim 2, 0, 123, -2, -2, -1, -1,
ax_anim 2, 0, 123, -3, -1, -2, 0,
ax_anim 2, 0, 123, -2, -2, -1, -1,
ax_anim 2, 0, 123, -3, -1, -2, 0,
ax_anim 2, 0, 123, -2, -2, -1, -1,
ax_anim 2, 0, 122, -1, -1, -1, -1,
ax_anim_terminator
sSentretAnims_4_7:
ax_anim 2, 0, 124, 2, 0, 2, 0,
ax_anim 6, 2, 124, 3, 0, 3, 0,
ax_anim 2, 0, 124, 1, 0, 1, 0,
ax_anim 2, 1, 125, -2, 0, -2, 0,
ax_anim 2, 0, 125, -2, 1, -2, 1,
ax_anim 2, 0, 125, -2, 0, -2, 0,
ax_anim 2, 0, 125, -2, 1, -2, 1,
ax_anim 2, 0, 125, -2, 0, -2, 0,
ax_anim 2, 0, 125, -2, 1, -2, 1,
ax_anim 2, 0, 125, -2, 0, -2, 0,
ax_anim 2, 0, 124, -1, 0, -1, 0,
ax_anim_terminator
sSentretAnims_4_8:
ax_anim 2, 0, 126, 2, -2, 2, -2,
ax_anim 6, 2, 126, 3, -3, 3, -3,
ax_anim 2, 0, 126, 1, -1, 1, -1,
ax_anim 2, 1, 127, -2, 2, -1, 1,
ax_anim 2, 0, 127, -3, 1, -2, 0,
ax_anim 2, 0, 127, -2, 2, -1, 1,
ax_anim 2, 0, 127, -3, 1, -2, 0,
ax_anim 2, 0, 127, -2, 2, -1, 1,
ax_anim 2, 0, 127, -3, 1, -2, 0,
ax_anim 2, 0, 127, -2, 2, -1, 1,
ax_anim 2, 0, 126, -1, 1, -1, 1,
ax_anim_terminator
.align 2
sSentretAnims_5_1:
ax_anim 1, 0, 128, 0, -2, 0, 0,
ax_anim 2, 0, 128, 0, -9, 0, 0,
ax_anim 6, 0, 129, 0, 0, 0, 0,
ax_anim 2, 0, 129, 1, 0, 1, 0,
ax_anim 2, 0, 129, 0, 0, 0, 0,
ax_anim 2, 2, 129, 1, 0, 1, 0,
ax_anim 2, 0, 129, 0, 0, 0, 0,
ax_anim 2, 0, 129, 1, 0, 1, 0,
ax_anim 2, 0, 129, 0, 0, 0, 0,
ax_anim 2, 0, 128, 0, -12, 0, 0,
ax_anim 2, 0, 128, 0, -8, 0, 0,
ax_anim 2, 0, 128, 0, -2, 0, 0,
ax_anim 2, 0, 128, 0, 0, 0, 0,
ax_anim_terminator
sSentretAnims_5_2:
ax_anim 1, 0, 130, 0, -2, 0, 0,
ax_anim 2, 0, 130, 0, -9, 0, 0,
ax_anim 6, 0, 131, 0, 0, 0, 0,
ax_anim 2, 0, 131, -1, 1, 1, 0,
ax_anim 2, 0, 131, 0, 0, 0, 0,
ax_anim 2, 2, 131, -1, 1, 1, 0,
ax_anim 2, 0, 131, 0, 0, 0, 0,
ax_anim 2, 0, 131, -1, 1, 1, 0,
ax_anim 2, 0, 131, 0, 0, 0, 0,
ax_anim 2, 0, 130, 0, -12, 0, 0,
ax_anim 2, 0, 130, 0, -8, 0, 0,
ax_anim 2, 0, 130, 0, -2, 0, 0,
ax_anim 2, 0, 130, 0, 0, 0, 0,
ax_anim_terminator
sSentretAnims_5_3:
ax_anim 1, 0, 132, 0, -2, 0, 0,
ax_anim 2, 0, 132, 0, -9, 0, 0,
ax_anim 6, 0, 133, 0, 0, 0, 0,
ax_anim 2, 0, 133, 0, 1, 0, 1,
ax_anim 2, 0, 133, 0, 0, 0, 0,
ax_anim 2, 2, 133, 0, 1, 0, 1,
ax_anim 2, 0, 133, 0, 0, 0, 0,
ax_anim 2, 0, 133, 0, 1, 0, 1,
ax_anim 2, 0, 133, 0, 0, 0, 0,
ax_anim 2, 0, 132, 0, -12, 0, 0,
ax_anim 2, 0, 132, 0, -8, 0, 0,
ax_anim 2, 0, 132, 0, -2, 0, 0,
ax_anim 2, 0, 132, 0, 0, 0, 0,
ax_anim_terminator
sSentretAnims_5_4:
ax_anim 1, 0, 134, 0, -2, 0, 0,
ax_anim 2, 0, 134, 0, -9, 0, 0,
ax_anim 6, 0, 135, 0, 0, 0, 0,
ax_anim 2, 0, 135, 1, 1, 1, 1,
ax_anim 2, 0, 135, 0, 0, 0, 0,
ax_anim 2, 2, 135, 1, 1, 1, 1,
ax_anim 2, 0, 135, 0, 0, 0, 0,
ax_anim 2, 0, 135, 1, 1, 1, 1,
ax_anim 2, 0, 135, 0, 0, 0, 0,
ax_anim 2, 0, 134, 0, -12, 0, 0,
ax_anim 2, 0, 134, 0, -8, 0, 0,
ax_anim 2, 0, 134, 0, -2, 0, 0,
ax_anim 2, 0, 134, 0, 0, 0, 0,
ax_anim_terminator
sSentretAnims_5_5:
ax_anim 1, 0, 136, 0, -2, 0, 0,
ax_anim 2, 0, 136, 0, -9, 0, 0,
ax_anim 6, 0, 137, 0, 0, 0, 0,
ax_anim 2, 0, 137, -1, 0, -1, 0,
ax_anim 2, 0, 137, 0, 0, 0, 0,
ax_anim 2, 2, 137, -1, 0, -1, 0,
ax_anim 2, 0, 137, 0, 0, 0, 0,
ax_anim 2, 0, 137, -1, 0, -1, 0,
ax_anim 2, 0, 137, 0, 0, 0, 0,
ax_anim 2, 0, 136, 0, -12, 0, 0,
ax_anim 2, 0, 136, 0, -8, 0, 0,
ax_anim 2, 0, 136, 0, -2, 0, 0,
ax_anim 2, 0, 136, 0, 0, 0, 0,
ax_anim_terminator
sSentretAnims_5_6:
ax_anim 1, 0, 138, 0, -2, 0, 0,
ax_anim 2, 0, 138, 0, -9, 0, 0,
ax_anim 6, 0, 139, 0, 0, 0, 0,
ax_anim 2, 0, 139, -1, 1, -1, 1,
ax_anim 2, 0, 139, 0, 0, 0, 0,
ax_anim 2, 2, 139, -1, 1, -1, 1,
ax_anim 2, 0, 139, 0, 0, 0, 0,
ax_anim 2, 0, 139, -1, 1, -1, 1,
ax_anim 2, 0, 139, 0, 0, 0, 0,
ax_anim 2, 0, 138, 0, -12, 0, 0,
ax_anim 2, 0, 138, 0, -8, 0, 0,
ax_anim 2, 0, 138, 0, -2, 0, 0,
ax_anim 2, 0, 138, 0, 0, 0, 0,
ax_anim_terminator
sSentretAnims_5_7:
ax_anim 1, 0, 140, 0, -2, 0, 0,
ax_anim 2, 0, 140, 0, -9, 0, 0,
ax_anim 6, 0, 141, 0, 0, 0, 0,
ax_anim 2, 0, 141, 0, 1, 0, 1,
ax_anim 2, 0, 141, 0, 0, 0, 0,
ax_anim 2, 2, 141, 0, 1, 0, 1,
ax_anim 2, 0, 141, 0, 0, 0, 0,
ax_anim 2, 0, 141, 0, 1, 0, 1,
ax_anim 2, 0, 141, 0, 0, 0, 0,
ax_anim 2, 0, 140, 0, -12, 0, 0,
ax_anim 2, 0, 140, 0, -8, 0, 0,
ax_anim 2, 0, 140, 0, -2, 0, 0,
ax_anim 2, 0, 140, 0, 0, 0, 0,
ax_anim_terminator
sSentretAnims_5_8:
ax_anim 1, 0, 142, 0, -2, 0, 0,
ax_anim 2, 0, 142, 0, -9, 0, 0,
ax_anim 6, 0, 143, 0, 0, 0, 0,
ax_anim 2, 0, 143, 1, 1, -1, 0,
ax_anim 2, 0, 143, 0, 0, 0, 0,
ax_anim 2, 2, 143, 1, 1, -1, 0,
ax_anim 2, 0, 143, 0, 0, 0, 0,
ax_anim 2, 0, 143, 1, 1, -1, 0,
ax_anim 2, 0, 143, 0, 0, 0, 0,
ax_anim 2, 0, 142, 0, -12, 0, 0,
ax_anim 2, 0, 142, 0, -8, 0, 0,
ax_anim 2, 0, 142, 0, -2, 0, 0,
ax_anim 2, 0, 142, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sSentretAnims_6_1:
ax_anim 30, 0, 144, 0, 0, 0, 0,
ax_anim 35, 0, 145, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sSentretAnims_7_1:
ax_anim 2, 0, 146, 0, -2, 0, -2,
ax_anim 8, 0, 146, 0, -3, 0, -3,
ax_anim_terminator
sSentretAnims_7_2:
ax_anim 2, 0, 147, -2, -2, -2, -2,
ax_anim 8, 0, 147, -3, -3, -3, -3,
ax_anim_terminator
sSentretAnims_7_3:
ax_anim 2, 0, 148, -2, 0, -2, 0,
ax_anim 8, 0, 148, -3, 0, -3, 0,
ax_anim_terminator
sSentretAnims_7_4:
ax_anim 2, 0, 149, -2, 2, -2, 2,
ax_anim 8, 0, 149, -3, 3, -3, 3,
ax_anim_terminator
sSentretAnims_7_5:
ax_anim 2, 0, 150, 0, 2, 0, 2,
ax_anim 8, 0, 150, 0, 3, 0, 3,
ax_anim_terminator
sSentretAnims_7_6:
ax_anim 2, 0, 151, 2, 2, 2, 2,
ax_anim 8, 0, 151, 3, 3, 3, 3,
ax_anim_terminator
sSentretAnims_7_7:
ax_anim 2, 0, 152, 2, 0, 2, 0,
ax_anim 8, 0, 152, 3, 0, 3, 0,
ax_anim_terminator
sSentretAnims_7_8:
ax_anim 2, 0, 153, 2, -2, 2, -2,
ax_anim 8, 0, 153, 3, -3, 3, -3,
ax_anim_terminator
.align 2
sSentretAnims_8_1:
ax_anim 30, 0, 155, 0, 0, 0, 0,
ax_anim 10, 0, 156, 0, 0, 0, 0,
ax_anim 2, 0, 155, 0, 0, 0, 0,
ax_anim 2, 0, 155, 0, -3, 0, 0,
ax_anim 3, 0, 155, 0, -5, 0, 0,
ax_anim 3, 0, 155, 0, -6, 0, 0,
ax_anim 3, 0, 155, 0, -5, 0, 0,
ax_anim 2, 0, 155, 0, -3, 0, 0,
ax_anim_terminator
sSentretAnims_8_2:
ax_anim 30, 0, 160, 0, 0, 0, 0,
ax_anim 10, 0, 161, 0, 0, 0, 0,
ax_anim 2, 0, 160, 0, 0, 0, 0,
ax_anim 2, 0, 160, 0, -3, 0, 0,
ax_anim 3, 0, 160, 0, -5, 0, 0,
ax_anim 3, 0, 160, 0, -6, 0, 0,
ax_anim 3, 0, 160, 0, -5, 0, 0,
ax_anim 2, 0, 160, 0, -3, 0, 0,
ax_anim_terminator
sSentretAnims_8_3:
ax_anim 30, 0, 165, 0, 0, 0, 0,
ax_anim 10, 0, 166, 0, 0, 0, 0,
ax_anim 2, 0, 165, 0, 0, 0, 0,
ax_anim 2, 0, 165, 0, -3, 0, 0,
ax_anim 3, 0, 165, 0, -5, 0, 0,
ax_anim 3, 0, 165, 0, -6, 0, 0,
ax_anim 3, 0, 165, 0, -5, 0, 0,
ax_anim 2, 0, 165, 0, -3, 0, 0,
ax_anim_terminator
sSentretAnims_8_4:
ax_anim 30, 0, 170, 0, 0, 0, 0,
ax_anim 10, 0, 171, 0, 0, 0, 0,
ax_anim 2, 0, 170, 0, 0, 0, 0,
ax_anim 2, 0, 170, 0, -3, 0, 0,
ax_anim 3, 0, 170, 0, -5, 0, 0,
ax_anim 3, 0, 170, 0, -6, 0, 0,
ax_anim 3, 0, 170, 0, -5, 0, 0,
ax_anim 2, 0, 170, 0, -3, 0, 0,
ax_anim_terminator
sSentretAnims_8_5:
ax_anim 30, 0, 175, 0, 0, 0, 0,
ax_anim 10, 0, 176, 0, 0, 0, 0,
ax_anim 2, 0, 175, 0, 0, 0, 0,
ax_anim 2, 0, 175, 0, -3, 0, 0,
ax_anim 3, 0, 175, 0, -5, 0, 0,
ax_anim 3, 0, 175, 0, -6, 0, 0,
ax_anim 3, 0, 175, 0, -5, 0, 0,
ax_anim 2, 0, 175, 0, -3, 0, 0,
ax_anim_terminator
sSentretAnims_8_6:
ax_anim 30, 0, 180, 0, 0, 0, 0,
ax_anim 10, 0, 181, 0, 0, 0, 0,
ax_anim 2, 0, 180, 0, 0, 0, 0,
ax_anim 2, 0, 180, 0, -3, 0, 0,
ax_anim 3, 0, 180, 0, -5, 0, 0,
ax_anim 3, 0, 180, 0, -6, 0, 0,
ax_anim 3, 0, 180, 0, -5, 0, 0,
ax_anim 2, 0, 180, 0, -3, 0, 0,
ax_anim_terminator
sSentretAnims_8_7:
ax_anim 30, 0, 185, 0, 0, 0, 0,
ax_anim 10, 0, 186, 0, 0, 0, 0,
ax_anim 2, 0, 185, 0, 0, 0, 0,
ax_anim 2, 0, 185, 0, -3, 0, 0,
ax_anim 3, 0, 185, 0, -5, 0, 0,
ax_anim 3, 0, 185, 0, -6, 0, 0,
ax_anim 3, 0, 185, 0, -5, 0, 0,
ax_anim 2, 0, 185, 0, -3, 0, 0,
ax_anim_terminator
sSentretAnims_8_8:
ax_anim 30, 0, 190, 0, 0, 0, 0,
ax_anim 10, 0, 191, 0, 0, 0, 0,
ax_anim 2, 0, 190, 0, 0, 0, 0,
ax_anim 2, 0, 190, 0, -3, 0, 0,
ax_anim 3, 0, 190, 0, -5, 0, 0,
ax_anim 3, 0, 190, 0, -6, 0, 0,
ax_anim 3, 0, 190, 0, -5, 0, 0,
ax_anim 2, 0, 190, 0, -3, 0, 0,
ax_anim_terminator
.align 2
sSentretAnims_9_1:
ax_anim 2, 0, 194, 0, 0, 0, 0,
ax_anim 1, 0, 195, 6, 3, 6, 3,
ax_anim 2, 0, 196, 8, 9, 8, 9,
ax_anim 2, 0, 197, 7, 17, 7, 17,
ax_anim 3, 0, 198, 0, 20, 0, 20,
ax_anim 2, 3, 199, -7, 17, -7, 17,
ax_anim 2, 0, 200, -8, 9, -8, 9,
ax_anim 1, 0, 201, -6, 3, -6, 3,
ax_anim 1, 0, 194, 0, 0, 0, 0,
ax_anim_terminator
sSentretAnims_9_2:
ax_anim 2, 0, 201, 0, 0, 0, 0,
ax_anim 1, 0, 194, 8, 0, 8, 0,
ax_anim 2, 0, 195, 17, 3, 17, 3,
ax_anim 2, 0, 196, 19, 10, 19, 10,
ax_anim 3, 0, 197, 17, 19, 17, 19,
ax_anim 2, 3, 198, 11, 21, 11, 21,
ax_anim 2, 0, 199, 3, 15, 3, 15,
ax_anim 1, 0, 200, 0, 7, 0, 7,
ax_anim 1, 0, 201, 0, 0, 0, 0,
ax_anim_terminator
sSentretAnims_9_3:
ax_anim 2, 0, 200, 0, 0, 0, 0,
ax_anim 1, 0, 201, 3, -5, 3, -5,
ax_anim 2, 0, 194, 11, -6, 11, -6,
ax_anim 2, 0, 195, 16, -5, 16, -5,
ax_anim 3, 0, 196, 19, -2, 19, -2,
ax_anim 2, 3, 197, 16, 4, 16, 4,
ax_anim 2, 0, 198, 12, 7, 12, 7,
ax_anim 1, 0, 199, 4, 5, 4, 5,
ax_anim 1, 0, 200, 0, 0, 0, 0,
ax_anim_terminator
sSentretAnims_9_4:
ax_anim 2, 0, 199, 0, 0, 0, 0,
ax_anim 1, 0, 200, -1, -8, -1, -8,
ax_anim 2, 0, 201, 4, -16, 4, -16,
ax_anim 2, 0, 194, 12, -22, 12, -22,
ax_anim 3, 0, 195, 19, -21, 19, -21,
ax_anim 2, 3, 196, 21, -14, 21, -14,
ax_anim 2, 0, 197, 16, -5, 16, -5,
ax_anim 1, 0, 198, 7, -1, 7, -1,
ax_anim 1, 0, 199, 0, 0, 0, 0,
ax_anim_terminator
sSentretAnims_9_5:
ax_anim 2, 0, 198, 0, 0, 0, 0,
ax_anim 1, 0, 199, -7, -4, -7, -4,
ax_anim 2, 0, 200, -9, -12, -9, -12,
ax_anim 2, 0, 201, -7, -19, -7, -19,
ax_anim 3, 0, 194, 0, -22, 0, -22,
ax_anim 2, 3, 195, 7, -19, 7, -19,
ax_anim 2, 0, 196, 9, -10, 9, -10,
ax_anim 1, 0, 197, 7, -4, 7, -4,
ax_anim 1, 0, 198, 0, 0, 0, 0,
ax_anim_terminator
sSentretAnims_9_6:
ax_anim 2, 0, 197, 0, 0, 0, 0,
ax_anim 1, 0, 196, 1, -8, 1, -6,
ax_anim 2, 0, 195, -4, -16, -4, -16,
ax_anim 2, 0, 194, -12, -22, -12, -22,
ax_anim 3, 0, 201, -19, -21, -18, -22,
ax_anim 2, 3, 200, -21, -14, -20, -15,
ax_anim 2, 0, 199, -16, -5, -17, -4,
ax_anim 1, 0, 198, -7, -1, -7, -1,
ax_anim 1, 0, 197, 0, 0, 0, 0,
ax_anim_terminator
sSentretAnims_9_7:
ax_anim 2, 0, 196, 0, 0, 0, 0,
ax_anim 1, 0, 195, -3, -5, -3, -5,
ax_anim 2, 0, 194, -11, -6, -11, -6,
ax_anim 2, 0, 201, -16, -5, -16, -5,
ax_anim 3, 0, 200, -19, -2, -18, -2,
ax_anim 2, 3, 199, -16, 4, -16, 4,
ax_anim 2, 0, 198, -12, 7, -12, 5,
ax_anim 1, 0, 197, -4, 5, -4, 5,
ax_anim 1, 0, 196, 0, 0, 0, 0,
ax_anim_terminator
sSentretAnims_9_8:
ax_anim 2, 0, 195, 0, 0, 0, 0,
ax_anim 1, 0, 194, -8, 0, -8, 0,
ax_anim 2, 0, 201, -17, 3, -17, 3,
ax_anim 2, 0, 200, -19, 10, -19, 10,
ax_anim 3, 0, 199, -17, 19, -17, 19,
ax_anim 2, 3, 198, -11, 21, -11, 19,
ax_anim 2, 0, 197, -3, 15, -3, 15,
ax_anim 1, 0, 196, 0, 7, 0, 7,
ax_anim 1, 0, 195, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sSentretAnims_10_1:
ax_anim 2, 0, 202, 0, 0, 0, 0,
ax_anim 2, 0, 202, 6, 0, 6, 0,
ax_anim 2, 0, 202, -6, 0, -6, 0,
ax_anim 2, 0, 202, 10, 0, 10, 0,
ax_anim 2, 0, 202, -10, 0, -10, 0,
ax_anim 2, 0, 202, 12, 0, 12, 0,
ax_anim 3, 0, 202, -12, 0, -12, 0,
ax_anim 3, 0, 202, 13, 0, 13, 0,
ax_anim 3, 0, 202, -13, 0, -13, 0,
ax_anim 2, 0, 202, 12, 0, 12, 0,
ax_anim 3, 0, 202, -12, 0, -12, 0,
ax_anim 2, 0, 202, 10, 0, 10, 0,
ax_anim 2, 0, 202, -10, 0, -10, 0,
ax_anim 2, 0, 202, 6, 0, 6, 0,
ax_anim 2, 0, 202, -6, 0, -6, 0,
ax_anim 2, 0, 202, 0, 0, 0, 0,
ax_anim_terminator
sSentretAnims_10_2:
ax_anim 2, 0, 203, 0, 0, 0, 0,
ax_anim 2, 0, 203, 6, -6, 6, -6,
ax_anim 2, 0, 203, -6, 6, -6, 6,
ax_anim 2, 0, 203, 10, -10, 10, -10,
ax_anim 2, 0, 203, -10, 10, -10, 10,
ax_anim 2, 0, 203, 12, -12, 12, -12,
ax_anim 3, 0, 203, -12, 12, -12, 12,
ax_anim 3, 0, 203, 13, -13, 13, -13,
ax_anim 3, 0, 203, -13, 13, -13, 13,
ax_anim 2, 0, 203, 12, -12, 12, -12,
ax_anim 3, 0, 203, -12, 12, -12, 12,
ax_anim 2, 0, 203, 10, -10, 10, -10,
ax_anim 2, 0, 203, -10, 10, -10, 10,
ax_anim 2, 0, 203, 6, -6, 6, -6,
ax_anim 2, 0, 203, -6, 6, -6, 6,
ax_anim 2, 0, 203, 0, 0, 0, 0,
ax_anim_terminator
sSentretAnims_10_3:
ax_anim 2, 0, 204, 0, 0, 0, 0,
ax_anim 2, 0, 204, 0, -6, 0, -6,
ax_anim 2, 0, 204, 0, 6, 0, 6,
ax_anim 2, 0, 204, 0, -10, 0, -10,
ax_anim 2, 0, 204, 0, 10, 0, 10,
ax_anim 2, 0, 204, 0, -12, 0, -12,
ax_anim 3, 0, 204, 0, 12, 0, 12,
ax_anim 3, 0, 204, 0, -13, 0, -13,
ax_anim 3, 0, 204, 0, 13, 0, 13,
ax_anim 2, 0, 204, 0, -12, 0, -12,
ax_anim 3, 0, 204, 0, 12, 0, 12,
ax_anim 2, 0, 204, 0, -10, 0, -10,
ax_anim 2, 0, 204, 0, 10, 0, 10,
ax_anim 2, 0, 204, 0, -6, 0, -6,
ax_anim 2, 0, 204, 0, 6, 0, 6,
ax_anim 2, 0, 204, 0, 0, 0, 0,
ax_anim_terminator
sSentretAnims_10_4:
ax_anim 2, 0, 205, 0, 0, 0, 0,
ax_anim 2, 0, 205, -6, -6, -6, -6,
ax_anim 2, 0, 205, 6, 6, 6, 6,
ax_anim 2, 0, 205, -10, -10, -10, -10,
ax_anim 2, 0, 205, 10, 10, 10, 10,
ax_anim 2, 0, 205, -12, -12, -12, -12,
ax_anim 3, 0, 205, 12, 12, 12, 12,
ax_anim 3, 0, 205, -13, -13, -13, -13,
ax_anim 3, 0, 205, 13, 13, 13, 13,
ax_anim 2, 0, 205, -12, -12, -12, -12,
ax_anim 3, 0, 205, 12, 12, 12, 12,
ax_anim 2, 0, 205, -10, -10, -10, -10,
ax_anim 2, 0, 205, 10, 10, 10, 10,
ax_anim 2, 0, 205, -6, -6, -6, -6,
ax_anim 2, 0, 205, 6, 6, 6, 6,
ax_anim 2, 0, 205, 0, 0, 0, 0,
ax_anim_terminator
sSentretAnims_10_5:
ax_anim 2, 0, 206, 0, 0, 0, 0,
ax_anim 2, 0, 206, 6, 0, 6, 0,
ax_anim 2, 0, 206, -6, 0, -6, 0,
ax_anim 2, 0, 206, 10, 0, 10, 0,
ax_anim 2, 0, 206, -10, 0, -10, 0,
ax_anim 2, 0, 206, 12, 0, 12, 0,
ax_anim 3, 0, 206, -12, 0, -12, 0,
ax_anim 3, 0, 206, 13, 0, 13, 0,
ax_anim 3, 0, 206, -13, 0, -13, 0,
ax_anim 2, 0, 206, 12, 0, 12, 0,
ax_anim 3, 0, 206, -12, 0, -12, 0,
ax_anim 2, 0, 206, 10, 0, 10, 0,
ax_anim 2, 0, 206, -10, 0, -10, 0,
ax_anim 2, 0, 206, 6, 0, 6, 0,
ax_anim 2, 0, 206, -6, 0, -6, 0,
ax_anim 2, 0, 206, 0, 0, 0, 0,
ax_anim_terminator
sSentretAnims_10_6:
ax_anim 2, 0, 207, 0, 0, 0, 0,
ax_anim 2, 0, 207, 6, -6, 6, -6,
ax_anim 2, 0, 207, -6, 6, -6, 6,
ax_anim 2, 0, 207, 10, -10, 10, -10,
ax_anim 2, 0, 207, -10, 10, -10, 10,
ax_anim 2, 0, 207, 12, -12, 12, -12,
ax_anim 3, 0, 207, -12, 12, -12, 12,
ax_anim 3, 0, 207, 13, -13, 13, -13,
ax_anim 3, 0, 207, -13, 13, -13, 13,
ax_anim 2, 0, 207, 12, -12, 12, -12,
ax_anim 3, 0, 207, -12, 12, -12, 12,
ax_anim 2, 0, 207, 10, -10, 10, -10,
ax_anim 2, 0, 207, -10, 10, -10, 10,
ax_anim 2, 0, 207, 6, -6, 6, -6,
ax_anim 2, 0, 207, -6, 6, -6, 6,
ax_anim 2, 0, 207, 0, 0, 0, 0,
ax_anim_terminator
sSentretAnims_10_7:
ax_anim 2, 0, 208, 0, 0, 0, 0,
ax_anim 2, 0, 208, 0, -6, 0, -6,
ax_anim 2, 0, 208, 0, 6, 0, 6,
ax_anim 2, 0, 208, 0, -10, 0, -10,
ax_anim 2, 0, 208, 0, 10, 0, 10,
ax_anim 2, 0, 208, 0, -12, 0, -12,
ax_anim 3, 0, 208, 0, 12, 0, 12,
ax_anim 3, 0, 208, 0, -13, 0, -13,
ax_anim 3, 0, 208, 0, 13, 0, 13,
ax_anim 2, 0, 208, 0, -12, 0, -12,
ax_anim 3, 0, 208, 0, 12, 0, 12,
ax_anim 2, 0, 208, 0, -10, 0, -10,
ax_anim 2, 0, 208, 0, 10, 0, 10,
ax_anim 2, 0, 208, 0, -6, 0, -6,
ax_anim 2, 0, 208, 0, 6, 0, 6,
ax_anim 2, 0, 208, 0, 0, 0, 0,
ax_anim_terminator
sSentretAnims_10_8:
ax_anim 2, 0, 209, 0, 0, 0, 0,
ax_anim 2, 0, 209, -6, -6, -6, -6,
ax_anim 2, 0, 209, 6, 6, 6, 6,
ax_anim 2, 0, 209, -10, -10, -10, -10,
ax_anim 2, 0, 209, 10, 10, 10, 10,
ax_anim 2, 0, 209, -12, -12, -12, -12,
ax_anim 3, 0, 209, 12, 12, 12, 12,
ax_anim 3, 0, 209, -13, -13, -13, -13,
ax_anim 3, 0, 209, 13, 13, 13, 13,
ax_anim 2, 0, 209, -12, -12, -12, -12,
ax_anim 3, 0, 209, 12, 12, 12, 12,
ax_anim 2, 0, 209, -10, -10, -10, -10,
ax_anim 2, 0, 209, 10, 10, 10, 10,
ax_anim 2, 0, 209, -6, -6, -6, -6,
ax_anim 2, 0, 209, 6, 6, 6, 6,
ax_anim 2, 0, 209, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sSentretAnims_11_1:
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 1, 0, 211, 0, -2, 0, 0,
ax_anim 2, 0, 211, 0, -8, 0, 0,
ax_anim 3, 0, 211, 0, -12, 0, 0,
ax_anim 4, 0, 211, 0, -13, 0, 0,
ax_anim 4, 0, 212, 0, -23, 0, 0,
ax_anim 3, 0, 212, 0, -22, 0, 0,
ax_anim 2, 0, 212, 0, -18, 0, 0,
ax_anim 1, 0, 212, 0, -12, 0, 0,
ax_anim 2, 2, 210, 0, 0, 0, 0,
ax_anim_terminator
sSentretAnims_11_2:
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 1, 0, 214, 0, -10, 0, 0,
ax_anim 2, 0, 214, 0, -16, 0, 0,
ax_anim 3, 0, 214, 0, -20, 0, 0,
ax_anim 4, 0, 214, 0, -21, 0, 0,
ax_anim 4, 0, 215, 0, -23, 0, 0,
ax_anim 3, 0, 215, 0, -22, 0, 0,
ax_anim 2, 0, 215, 0, -18, 0, 0,
ax_anim 1, 0, 215, 0, -12, 0, 0,
ax_anim 2, 2, 213, 0, 0, 0, 0,
ax_anim_terminator
sSentretAnims_11_3:
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 1, 0, 217, 0, -10, 0, 0,
ax_anim 2, 0, 217, 0, -16, 0, 0,
ax_anim 3, 0, 217, 0, -20, 0, 0,
ax_anim 4, 0, 217, 0, -21, 0, 0,
ax_anim 4, 0, 218, 0, -23, 0, 0,
ax_anim 3, 0, 218, 0, -22, 0, 0,
ax_anim 2, 0, 218, 0, -18, 0, 0,
ax_anim 1, 0, 218, 0, -12, 0, 0,
ax_anim 2, 2, 216, 0, 0, 0, 0,
ax_anim_terminator
sSentretAnims_11_4:
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 1, 0, 220, 0, -10, 0, 0,
ax_anim 2, 0, 220, 0, -16, 0, 0,
ax_anim 3, 0, 220, 0, -20, 0, 0,
ax_anim 4, 0, 220, 0, -21, 0, 0,
ax_anim 4, 0, 221, 0, -22, 0, 0,
ax_anim 3, 0, 221, 0, -21, 0, 0,
ax_anim 2, 0, 221, 0, -17, 0, 0,
ax_anim 1, 0, 221, 0, -11, 0, 0,
ax_anim 2, 2, 219, 0, 0, 0, 0,
ax_anim_terminator
sSentretAnims_11_5:
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 1, 0, 223, 0, -10, 0, 0,
ax_anim 2, 0, 223, 0, -16, 0, 0,
ax_anim 3, 0, 223, 0, -21, 0, 0,
ax_anim 4, 0, 223, 0, -22, 0, 0,
ax_anim 4, 0, 224, 0, -23, 0, 0,
ax_anim 3, 0, 224, 0, -22, 0, 0,
ax_anim 2, 0, 224, 0, -18, 0, 0,
ax_anim 1, 0, 224, 0, -12, 0, 0,
ax_anim 2, 2, 222, 0, 0, 0, 0,
ax_anim_terminator
sSentretAnims_11_6:
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 1, 0, 226, 0, -10, 0, 0,
ax_anim 2, 0, 226, 0, -16, 0, 0,
ax_anim 3, 0, 226, 0, -20, 0, 0,
ax_anim 4, 0, 226, 0, -21, 0, 0,
ax_anim 4, 0, 227, 0, -22, 0, 0,
ax_anim 3, 0, 227, 0, -21, 0, 0,
ax_anim 2, 0, 227, 0, -17, 0, 0,
ax_anim 1, 0, 227, 0, -11, 0, 0,
ax_anim 2, 2, 225, 0, 0, 0, 0,
ax_anim_terminator
sSentretAnims_11_7:
ax_anim 2, 0, 228, 0, 0, 0, 0,
ax_anim 1, 0, 229, 0, -10, 0, 0,
ax_anim 2, 0, 229, 0, -16, 0, 0,
ax_anim 3, 0, 229, 0, -20, 0, 0,
ax_anim 4, 0, 229, 0, -21, 0, 0,
ax_anim 4, 0, 230, 0, -23, 0, 0,
ax_anim 3, 0, 230, 0, -22, 0, 0,
ax_anim 2, 0, 230, 0, -18, 0, 0,
ax_anim 1, 0, 230, 0, -12, 0, 0,
ax_anim 2, 2, 228, 0, 0, 0, 0,
ax_anim_terminator
sSentretAnims_11_8:
ax_anim 2, 0, 231, 0, 0, 0, 0,
ax_anim 1, 0, 232, 0, -10, 0, 0,
ax_anim 2, 0, 232, 0, -16, 0, 0,
ax_anim 3, 0, 232, 0, -20, 0, 0,
ax_anim 4, 0, 232, 0, -21, 0, 0,
ax_anim 4, 0, 233, 0, -23, 0, 0,
ax_anim 3, 0, 233, 0, -22, 0, 0,
ax_anim 2, 0, 233, 0, -18, 0, 0,
ax_anim 1, 0, 233, 0, -12, 0, 0,
ax_anim 2, 2, 231, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sSentretAnims_12_1:
ax_anim 2, 0, 234, 1, 0, 1, 0,
ax_anim 2, 0, 234, 0, 0, 0, 0,
ax_anim 2, 0, 234, 1, 0, 1, 0,
ax_anim 2, 0, 234, 0, 0, 0, 0,
ax_anim 2, 0, 234, 1, 0, 1, 0,
ax_anim 2, 2, 234, 0, 0, 0, 0,
ax_anim 2, 0, 234, 1, 0, 1, 0,
ax_anim 2, 0, 234, 0, 0, 0, 0,
ax_anim 2, 0, 234, 1, 0, 1, 0,
ax_anim 2, 1, 234, 0, 0, 0, 0,
ax_anim_terminator
sSentretAnims_12_2:
ax_anim 2, 0, 241, 1, -1, 1, -1,
ax_anim 2, 0, 241, 0, 0, 0, 0,
ax_anim 2, 0, 241, 1, -1, 1, -1,
ax_anim 2, 0, 241, 0, 0, 0, 0,
ax_anim 2, 0, 241, 1, -1, 1, -1,
ax_anim 2, 2, 241, 0, 0, 0, 0,
ax_anim 2, 0, 241, 1, -1, 1, -1,
ax_anim 2, 0, 241, 0, 0, 0, 0,
ax_anim 2, 0, 241, 1, -1, 1, -1,
ax_anim 2, 1, 241, 0, 0, 0, 0,
ax_anim_terminator
sSentretAnims_12_3:
ax_anim 2, 0, 240, 0, -1, 0, -1,
ax_anim 2, 0, 240, 0, 0, 0, 0,
ax_anim 2, 0, 240, 0, -1, 0, -1,
ax_anim 2, 0, 240, 0, 0, 0, 0,
ax_anim 2, 0, 240, 0, -1, 0, -1,
ax_anim 2, 2, 240, 0, 0, 0, 0,
ax_anim 2, 0, 240, 0, -1, 0, -1,
ax_anim 2, 0, 240, 0, 0, 0, 0,
ax_anim 2, 0, 240, 0, -1, 0, -1,
ax_anim 2, 1, 240, 0, 0, 0, 0,
ax_anim_terminator
sSentretAnims_12_4:
ax_anim 2, 0, 239, -1, -1, -1, -1,
ax_anim 2, 0, 239, 0, 0, 0, 0,
ax_anim 2, 0, 239, -1, -1, -1, -1,
ax_anim 2, 0, 239, 0, 0, 0, 0,
ax_anim 2, 0, 239, -1, -1, -1, -1,
ax_anim 2, 2, 239, 0, 0, 0, 0,
ax_anim 2, 0, 239, -1, -1, -1, -1,
ax_anim 2, 0, 239, 0, 0, 0, 0,
ax_anim 2, 0, 239, -1, -1, -1, -1,
ax_anim 2, 1, 239, 0, 0, 0, 0,
ax_anim_terminator
sSentretAnims_12_5:
ax_anim 2, 0, 238, 1, 0, 1, 0,
ax_anim 2, 0, 238, 0, 0, 0, 0,
ax_anim 2, 0, 238, 1, 0, 1, 0,
ax_anim 2, 0, 238, 0, 0, 0, 0,
ax_anim 2, 0, 238, 1, 0, 1, 0,
ax_anim 2, 2, 238, 0, 0, 0, 0,
ax_anim 2, 0, 238, 1, 0, 1, 0,
ax_anim 2, 0, 238, 0, 0, 0, 0,
ax_anim 2, 0, 238, 1, 0, 1, 0,
ax_anim 2, 1, 238, 0, 0, 0, 0,
ax_anim_terminator
sSentretAnims_12_6:
ax_anim 2, 0, 237, 1, -1, 1, -1,
ax_anim 2, 0, 237, 0, 0, 0, 0,
ax_anim 2, 0, 237, 1, -1, 1, -1,
ax_anim 2, 0, 237, 0, 0, 0, 0,
ax_anim 2, 0, 237, 1, -1, 1, -1,
ax_anim 2, 2, 237, 0, 0, 0, 0,
ax_anim 2, 0, 237, 1, -1, 1, -1,
ax_anim 2, 0, 237, 0, 0, 0, 0,
ax_anim 2, 0, 237, 1, -1, 1, -1,
ax_anim 2, 1, 237, 0, 0, 0, 0,
ax_anim_terminator
sSentretAnims_12_7:
ax_anim 2, 0, 236, 0, -1, 0, -1,
ax_anim 2, 0, 236, 0, 0, 0, 0,
ax_anim 2, 0, 236, 0, -1, 0, -1,
ax_anim 2, 0, 236, 0, 0, 0, 0,
ax_anim 2, 0, 236, 0, -1, 0, -1,
ax_anim 2, 2, 236, 0, 0, 0, 0,
ax_anim 2, 0, 236, 0, -1, 0, -1,
ax_anim 2, 0, 236, 0, 0, 0, 0,
ax_anim 2, 0, 236, 0, -1, 0, -1,
ax_anim 2, 1, 236, 0, 0, 0, 0,
ax_anim_terminator
sSentretAnims_12_8:
ax_anim 2, 0, 235, -1, -1, -1, -1,
ax_anim 2, 0, 235, 0, 0, 0, 0,
ax_anim 2, 0, 235, -1, -1, -1, -1,
ax_anim 2, 0, 235, 0, 0, 0, 0,
ax_anim 2, 0, 235, -1, -1, -1, -1,
ax_anim 2, 2, 235, 0, 0, 0, 0,
ax_anim 2, 0, 235, -1, -1, -1, -1,
ax_anim 2, 0, 235, 0, 0, 0, 0,
ax_anim 2, 0, 235, -1, -1, -1, -1,
ax_anim 2, 1, 235, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sSentretAnims_13_1:
ax_anim 2, 0, 242, 0, 0, 0, 0,
ax_anim 2, 0, 243, 0, 0, 0, 0,
ax_anim 2, 0, 244, 0, 0, 0, 0,
ax_anim 2, 0, 245, 0, 0, 0, 0,
ax_anim 2, 0, 246, 0, 0, 0, 0,
ax_anim 2, 0, 247, 0, 0, 0, 0,
ax_anim 2, 0, 248, 0, 0, 0, 0,
ax_anim 2, 0, 249, 0, 0, 0, 0,
ax_anim 2, 2, 242, 0, 0, 0, 0,
ax_anim_terminator
sSentretAnims_13_2:
ax_anim 2, 0, 249, 0, 0, 0, 0,
ax_anim 2, 0, 242, 0, 0, 0, 0,
ax_anim 2, 0, 243, 0, 0, 0, 0,
ax_anim 2, 0, 244, 0, 0, 0, 0,
ax_anim 2, 0, 245, 0, 0, 0, 0,
ax_anim 2, 0, 246, 0, 0, 0, 0,
ax_anim 2, 0, 247, 0, 0, 0, 0,
ax_anim 2, 0, 248, 0, 0, 0, 0,
ax_anim 2, 2, 249, 0, 0, 0, 0,
ax_anim_terminator
sSentretAnims_13_3:
ax_anim 2, 0, 248, 0, 0, 0, 0,
ax_anim 2, 0, 249, 0, 0, 0, 0,
ax_anim 2, 0, 242, 0, 0, 0, 0,
ax_anim 2, 0, 243, 0, 0, 0, 0,
ax_anim 2, 0, 244, 0, 0, 0, 0,
ax_anim 2, 0, 245, 0, 0, 0, 0,
ax_anim 2, 0, 246, 0, 0, 0, 0,
ax_anim 2, 0, 247, 0, 0, 0, 0,
ax_anim 2, 2, 248, 0, 0, 0, 0,
ax_anim_terminator
sSentretAnims_13_4:
ax_anim 2, 0, 247, 0, 0, 0, 0,
ax_anim 2, 0, 248, 0, 0, 0, 0,
ax_anim 2, 0, 249, 0, 0, 0, 0,
ax_anim 2, 0, 242, 0, 0, 0, 0,
ax_anim 2, 0, 243, 0, 0, 0, 0,
ax_anim 2, 0, 244, 0, 0, 0, 0,
ax_anim 2, 0, 245, 0, 0, 0, 0,
ax_anim 2, 0, 246, 0, 0, 0, 0,
ax_anim 2, 2, 247, 0, 0, 0, 0,
ax_anim_terminator
sSentretAnims_13_5:
ax_anim 2, 0, 246, 0, 0, 0, 0,
ax_anim 2, 0, 247, 0, 0, 0, 0,
ax_anim 2, 0, 248, 0, 0, 0, 0,
ax_anim 2, 0, 249, 0, 0, 0, 0,
ax_anim 2, 0, 242, 0, 0, 0, 0,
ax_anim 2, 0, 243, 0, 0, 0, 0,
ax_anim 2, 0, 244, 0, 0, 0, 0,
ax_anim 2, 0, 245, 0, 0, 0, 0,
ax_anim 2, 2, 246, 0, 0, 0, 0,
ax_anim_terminator
sSentretAnims_13_6:
ax_anim 2, 0, 245, 0, 0, 0, 0,
ax_anim 2, 0, 246, 0, 0, 0, 0,
ax_anim 2, 0, 247, 0, 0, 0, 0,
ax_anim 2, 0, 248, 0, 0, 0, 0,
ax_anim 2, 0, 249, 0, 0, 0, 0,
ax_anim 2, 0, 242, 0, 0, 0, 0,
ax_anim 2, 0, 243, 0, 0, 0, 0,
ax_anim 2, 0, 244, 0, 0, 0, 0,
ax_anim 2, 2, 245, 0, 0, 0, 0,
ax_anim_terminator
sSentretAnims_13_7:
ax_anim 2, 0, 244, 0, 0, 0, 0,
ax_anim 2, 0, 245, 0, 0, 0, 0,
ax_anim 2, 0, 246, 0, 0, 0, 0,
ax_anim 2, 0, 247, 0, 0, 0, 0,
ax_anim 2, 0, 248, 0, 0, 0, 0,
ax_anim 2, 0, 249, 0, 0, 0, 0,
ax_anim 2, 0, 242, 0, 0, 0, 0,
ax_anim 2, 0, 243, 0, 0, 0, 0,
ax_anim 2, 2, 244, 0, 0, 0, 0,
ax_anim_terminator
sSentretAnims_13_8:
ax_anim 2, 0, 243, 0, 0, 0, 0,
ax_anim 2, 0, 244, 0, 0, 0, 0,
ax_anim 2, 0, 245, 0, 0, 0, 0,
ax_anim 2, 0, 246, 0, 0, 0, 0,
ax_anim 2, 0, 247, 0, 0, 0, 0,
ax_anim 2, 0, 248, 0, 0, 0, 0,
ax_anim 2, 0, 249, 0, 0, 0, 0,
ax_anim 2, 0, 242, 0, 0, 0, 0,
ax_anim 2, 2, 243, 0, 0, 0, 0,
ax_anim_terminator
sSentretGfx1:
.incbin "baserom.gba", 0xC15814, 0x200
sSentretSprites1:
ax_sprite sSentretGfx1, 0x200
ax_sprite_terminator
sSentretGfx2:
.incbin "baserom.gba", 0xC15A24, 0x200
sSentretSprites2:
ax_sprite sSentretGfx2, 0x200
ax_sprite_terminator
sSentretGfx3:
.incbin "baserom.gba", 0xC15C34, 0x200
sSentretSprites3:
ax_sprite sSentretGfx3, 0x200
ax_sprite_terminator
sSentretGfx4:
.incbin "baserom.gba", 0xC15E44, 0x200
sSentretSprites4:
ax_sprite sSentretGfx4, 0x200
ax_sprite_terminator
sSentretGfx5:
.incbin "baserom.gba", 0xC16054, 0x200
sSentretSprites5:
ax_sprite sSentretGfx5, 0x200
ax_sprite_terminator
sSentretGfx6:
.incbin "baserom.gba", 0xC16264, 0x200
sSentretSprites6:
ax_sprite sSentretGfx6, 0x200
ax_sprite_terminator
sSentretGfx7:
.incbin "baserom.gba", 0xC16474, 0x200
sSentretSprites7:
ax_sprite sSentretGfx7, 0x200
ax_sprite_terminator
sSentretGfx8:
.incbin "baserom.gba", 0xC16684, 0x200
sSentretSprites8:
ax_sprite sSentretGfx8, 0x200
ax_sprite_terminator
sSentretGfx9:
.incbin "baserom.gba", 0xC16894, 0x200
sSentretSprites9:
ax_sprite sSentretGfx9, 0x200
ax_sprite_terminator
sSentretGfx10:
.incbin "baserom.gba", 0xC16AA4, 0x200
sSentretSprites10:
ax_sprite sSentretGfx10, 0x200
ax_sprite_terminator
sSentretGfx11:
.incbin "baserom.gba", 0xC16CB4, 0x200
sSentretSprites11:
ax_sprite sSentretGfx11, 0x200
ax_sprite_terminator
sSentretGfx12:
.incbin "baserom.gba", 0xC16EC4, 0x200
sSentretSprites12:
ax_sprite sSentretGfx12, 0x200
ax_sprite_terminator
sSentretGfx13:
.incbin "baserom.gba", 0xC170D4, 0x200
sSentretSprites13:
ax_sprite sSentretGfx13, 0x200
ax_sprite_terminator
sSentretGfx14:
.incbin "baserom.gba", 0xC172E4, 0x200
sSentretSprites14:
ax_sprite sSentretGfx14, 0x200
ax_sprite_terminator
sSentretGfx15:
.incbin "baserom.gba", 0xC174F4, 0x200
sSentretSprites15:
ax_sprite sSentretGfx15, 0x200
ax_sprite_terminator
sSentretGfx16:
.incbin "baserom.gba", 0xC17704, 0x60
sSentretGfx16_1:
.incbin "baserom.gba", 0xC17764, 0x60
sSentretGfx16_2:
.incbin "baserom.gba", 0xC177C4, 0x60
sSentretGfx16_3:
.incbin "baserom.gba", 0xC17824, 0x40
sSentretSprites16:
ax_sprite sSentretGfx16, 0x60
ax_sprite 0, 0x20
ax_sprite sSentretGfx16_1, 0x60
ax_sprite 0, 0x20
ax_sprite sSentretGfx16_2, 0x60
ax_sprite 0, 0x20
ax_sprite sSentretGfx16_3, 0x40
ax_sprite 0, 0x40
ax_sprite_terminator
sSentretGfx17:
.incbin "baserom.gba", 0xC178AC, 0x60
sSentretGfx17_1:
.incbin "baserom.gba", 0xC1790C, 0x60
sSentretGfx17_2:
.incbin "baserom.gba", 0xC1796C, 0x60
sSentretSprites17:
ax_sprite sSentretGfx17, 0x60
ax_sprite 0, 0x20
ax_sprite sSentretGfx17_1, 0x60
ax_sprite 0, 0x20
ax_sprite sSentretGfx17_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sSentretGfx18:
.incbin "baserom.gba", 0xC17A04, 0x40
sSentretGfx18_1:
.incbin "baserom.gba", 0xC17A44, 0x60
sSentretGfx18_2:
.incbin "baserom.gba", 0xC17AA4, 0x60
sSentretSprites18:
ax_sprite sSentretGfx18, 0x40
ax_sprite 0, 0x40
ax_sprite sSentretGfx18_1, 0x60
ax_sprite 0, 0x20
ax_sprite sSentretGfx18_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sSentretGfx19:
.incbin "baserom.gba", 0xC17B3C, 0x20
sSentretGfx19_1:
.incbin "baserom.gba", 0xC17B5C, 0x60
sSentretGfx19_2:
.incbin "baserom.gba", 0xC17BBC, 0x60
sSentretGfx19_3:
.incbin "baserom.gba", 0xC17C1C, 0x40
sSentretSprites19:
ax_sprite 0, 0x20
ax_sprite sSentretGfx19, 0x20
ax_sprite 0, 0x40
ax_sprite sSentretGfx19_1, 0x60
ax_sprite 0, 0x20
ax_sprite sSentretGfx19_2, 0x60
ax_sprite 0, 0x20
ax_sprite sSentretGfx19_3, 0x40
ax_sprite 0, 0x40
ax_sprite_terminator
sSentretGfx20:
.incbin "baserom.gba", 0xC17CAC, 0x60
sSentretGfx20_1:
.incbin "baserom.gba", 0xC17D0C, 0x60
sSentretGfx20_2:
.incbin "baserom.gba", 0xC17D6C, 0x60
sSentretGfx20_3:
.incbin "baserom.gba", 0xC17DCC, 0x40
sSentretSprites20:
ax_sprite sSentretGfx20, 0x60
ax_sprite 0, 0x20
ax_sprite sSentretGfx20_1, 0x60
ax_sprite 0, 0x20
ax_sprite sSentretGfx20_2, 0x60
ax_sprite 0, 0x40
ax_sprite sSentretGfx20_3, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sSentretGfx21:
.incbin "baserom.gba", 0xC17E54, 0x60
sSentretGfx21_1:
.incbin "baserom.gba", 0xC17EB4, 0x60
sSentretGfx21_2:
.incbin "baserom.gba", 0xC17F14, 0x60
sSentretSprites21:
ax_sprite sSentretGfx21, 0x60
ax_sprite 0, 0x20
ax_sprite sSentretGfx21_1, 0x60
ax_sprite 0, 0x20
ax_sprite sSentretGfx21_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sSentretGfx22:
.incbin "baserom.gba", 0xC17FAC, 0x140
sSentretSprites22:
ax_sprite sSentretGfx22, 0x140
ax_sprite 0, 0xc0
ax_sprite_terminator
sSentretGfx23:
.incbin "baserom.gba", 0xC18104, 0x40
sSentretGfx23_1:
.incbin "baserom.gba", 0xC18144, 0xE0
sSentretSprites23:
ax_sprite sSentretGfx23, 0x40
ax_sprite 0, 0x40
ax_sprite sSentretGfx23_1, 0xe0
ax_sprite 0, 0xa0
ax_sprite_terminator
sSentretGfx24:
.incbin "baserom.gba", 0xC1824C, 0x40
sSentretGfx24_1:
.incbin "baserom.gba", 0xC1828C, 0x40
sSentretGfx24_2:
.incbin "baserom.gba", 0xC182CC, 0x60
sSentretGfx24_3:
.incbin "baserom.gba", 0xC1832C, 0x60
sSentretSprites24:
ax_sprite sSentretGfx24, 0x40
ax_sprite 0, 0x40
ax_sprite sSentretGfx24_1, 0x40
ax_sprite 0, 0x40
ax_sprite sSentretGfx24_2, 0x60
ax_sprite 0, 0x20
ax_sprite sSentretGfx24_3, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sSentretGfx25:
.incbin "baserom.gba", 0xC183D4, 0x60
sSentretGfx25_1:
.incbin "baserom.gba", 0xC18434, 0x60
sSentretGfx25_2:
.incbin "baserom.gba", 0xC18494, 0x60
sSentretSprites25:
ax_sprite sSentretGfx25, 0x60
ax_sprite 0, 0x20
ax_sprite sSentretGfx25_1, 0x60
ax_sprite 0, 0x20
ax_sprite sSentretGfx25_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sSentretGfx26:
.incbin "baserom.gba", 0xC1852C, 0x100
sSentretSprites26:
ax_sprite sSentretGfx26, 0x100
ax_sprite_terminator
sSentretGfx27:
.incbin "baserom.gba", 0xC1863C, 0x40
sSentretGfx27_1:
.incbin "baserom.gba", 0xC1867C, 0x100
sSentretSprites27:
ax_sprite sSentretGfx27, 0x40
ax_sprite 0, 0x40
ax_sprite sSentretGfx27_1, 0x100
ax_sprite 0, 0x80
ax_sprite_terminator
sSentretGfx28:
.incbin "baserom.gba", 0xC187A4, 0x60
sSentretGfx28_1:
.incbin "baserom.gba", 0xC18804, 0x60
sSentretGfx28_2:
.incbin "baserom.gba", 0xC18864, 0x60
sSentretGfx28_3:
.incbin "baserom.gba", 0xC188C4, 0x40
sSentretSprites28:
ax_sprite sSentretGfx28, 0x60
ax_sprite 0, 0x20
ax_sprite sSentretGfx28_1, 0x60
ax_sprite 0, 0x20
ax_sprite sSentretGfx28_2, 0x60
ax_sprite 0, 0x40
ax_sprite sSentretGfx28_3, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sSentretGfx29:
.incbin "baserom.gba", 0xC1894C, 0x60
sSentretGfx29_1:
.incbin "baserom.gba", 0xC189AC, 0x60
sSentretGfx29_2:
.incbin "baserom.gba", 0xC18A0C, 0x60
sSentretSprites29:
ax_sprite sSentretGfx29, 0x60
ax_sprite 0, 0x20
ax_sprite sSentretGfx29_1, 0x60
ax_sprite 0, 0x20
ax_sprite sSentretGfx29_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sSentretGfx30:
.incbin "baserom.gba", 0xC18AA4, 0x60
sSentretGfx30_1:
.incbin "baserom.gba", 0xC18B04, 0x100
sSentretSprites30:
ax_sprite sSentretGfx30, 0x60
ax_sprite 0, 0x20
ax_sprite sSentretGfx30_1, 0x100
ax_sprite 0, 0x80
ax_sprite_terminator
sSentretGfx31:
.incbin "baserom.gba", 0xC18C2C, 0x40
sSentretGfx31_1:
.incbin "baserom.gba", 0xC18C6C, 0x60
sSentretGfx31_2:
.incbin "baserom.gba", 0xC18CCC, 0x60
sSentretGfx31_3:
.incbin "baserom.gba", 0xC18D2C, 0x40
sSentretSprites31:
ax_sprite sSentretGfx31, 0x40
ax_sprite 0, 0x40
ax_sprite sSentretGfx31_1, 0x60
ax_sprite 0, 0x20
ax_sprite sSentretGfx31_2, 0x60
ax_sprite 0, 0x40
ax_sprite sSentretGfx31_3, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sSentretGfx32:
.incbin "baserom.gba", 0xC18DB4, 0x60
sSentretGfx32_1:
.incbin "baserom.gba", 0xC18E14, 0x60
sSentretGfx32_2:
.incbin "baserom.gba", 0xC18E74, 0x60
sSentretGfx32_3:
.incbin "baserom.gba", 0xC18ED4, 0x60
sSentretSprites32:
ax_sprite sSentretGfx32, 0x60
ax_sprite 0, 0x20
ax_sprite sSentretGfx32_1, 0x60
ax_sprite 0, 0x20
ax_sprite sSentretGfx32_2, 0x60
ax_sprite 0, 0x20
ax_sprite sSentretGfx32_3, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sSentretGfx33:
.incbin "baserom.gba", 0xC18F7C, 0x60
sSentretGfx33_1:
.incbin "baserom.gba", 0xC18FDC, 0x60
sSentretGfx33_2:
.incbin "baserom.gba", 0xC1903C, 0x40
sSentretSprites33:
ax_sprite sSentretGfx33, 0x60
ax_sprite 0, 0x20
ax_sprite sSentretGfx33_1, 0x60
ax_sprite 0, 0x20
ax_sprite sSentretGfx33_2, 0x40
ax_sprite 0, 0xc0
ax_sprite_terminator
sSentretGfx34:
.incbin "baserom.gba", 0xC190B4, 0x60
sSentretGfx34_1:
.incbin "baserom.gba", 0xC19114, 0x60
sSentretGfx34_2:
.incbin "baserom.gba", 0xC19174, 0x60
sSentretGfx34_3:
.incbin "baserom.gba", 0xC191D4, 0x20
sSentretSprites34:
ax_sprite sSentretGfx34, 0x60
ax_sprite 0, 0x20
ax_sprite sSentretGfx34_1, 0x60
ax_sprite 0, 0x20
ax_sprite sSentretGfx34_2, 0x60
ax_sprite 0, 0x40
ax_sprite sSentretGfx34_3, 0x20
ax_sprite 0, 0x40
ax_sprite_terminator
sSentretGfx35:
.incbin "baserom.gba", 0xC1923C, 0x60
sSentretGfx35_1:
.incbin "baserom.gba", 0xC1929C, 0x60
sSentretGfx35_2:
.incbin "baserom.gba", 0xC192FC, 0x60
sSentretGfx35_3:
.incbin "baserom.gba", 0xC1935C, 0x40
sSentretSprites35:
ax_sprite sSentretGfx35, 0x60
ax_sprite 0, 0x20
ax_sprite sSentretGfx35_1, 0x60
ax_sprite 0, 0x20
ax_sprite sSentretGfx35_2, 0x60
ax_sprite 0, 0x20
ax_sprite sSentretGfx35_3, 0x40
ax_sprite 0, 0x40
ax_sprite_terminator
sSentretGfx36:
.incbin "baserom.gba", 0xC193E4, 0x60
sSentretGfx36_1:
.incbin "baserom.gba", 0xC19444, 0x60
sSentretGfx36_2:
.incbin "baserom.gba", 0xC194A4, 0x60
sSentretSprites36:
ax_sprite sSentretGfx36, 0x60
ax_sprite 0, 0x20
ax_sprite sSentretGfx36_1, 0x60
ax_sprite 0, 0x20
ax_sprite sSentretGfx36_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sSentretGfx37:
.incbin "baserom.gba", 0xC1953C, 0x20
sSentretGfx37_1:
.incbin "baserom.gba", 0xC1955C, 0x20
sSentretGfx37_2:
.incbin "baserom.gba", 0xC1957C, 0x80
sSentretSprites37:
ax_sprite sSentretGfx37, 0x20
ax_sprite 0, 0x20
ax_sprite sSentretGfx37_1, 0x20
ax_sprite 0, 0x20
ax_sprite sSentretGfx37_2, 0x80
ax_sprite_terminator
sSentretGfx38:
.incbin "baserom.gba", 0xC1962C, 0x60
sSentretGfx38_1:
.incbin "baserom.gba", 0xC1968C, 0x60
sSentretGfx38_2:
.incbin "baserom.gba", 0xC196EC, 0x60
sSentretSprites38:
ax_sprite sSentretGfx38, 0x60
ax_sprite 0, 0x20
ax_sprite sSentretGfx38_1, 0x60
ax_sprite 0, 0x20
ax_sprite sSentretGfx38_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sSentretGfx39:
.incbin "baserom.gba", 0xC19784, 0x60
sSentretGfx39_1:
.incbin "baserom.gba", 0xC197E4, 0xE0
sSentretSprites39:
ax_sprite sSentretGfx39, 0x60
ax_sprite 0, 0x20
ax_sprite sSentretGfx39_1, 0xe0
ax_sprite 0, 0xa0
ax_sprite_terminator
sSentretGfx40:
.incbin "baserom.gba", 0xC198EC, 0x60
sSentretGfx40_1:
.incbin "baserom.gba", 0xC1994C, 0x80
sSentretSprites40:
ax_sprite sSentretGfx40, 0x60
ax_sprite 0, 0x20
ax_sprite sSentretGfx40_1, 0x80
ax_sprite_terminator
sSentretGfx41:
.incbin "baserom.gba", 0xC199EC, 0x40
sSentretGfx41_1:
.incbin "baserom.gba", 0xC19A2C, 0x60
sSentretGfx41_2:
.incbin "baserom.gba", 0xC19A8C, 0x60
sSentretSprites41:
ax_sprite sSentretGfx41, 0x40
ax_sprite 0, 0x40
ax_sprite sSentretGfx41_1, 0x60
ax_sprite 0, 0x20
ax_sprite sSentretGfx41_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sSentretGfx42:
.incbin "baserom.gba", 0xC19B24, 0x40
sSentretGfx42_1:
.incbin "baserom.gba", 0xC19B64, 0x60
sSentretGfx42_2:
.incbin "baserom.gba", 0xC19BC4, 0x60
sSentretSprites42:
ax_sprite sSentretGfx42, 0x40
ax_sprite 0, 0x40
ax_sprite sSentretGfx42_1, 0x60
ax_sprite 0, 0x20
ax_sprite sSentretGfx42_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sSentretGfx43:
.incbin "baserom.gba", 0xC19C5C, 0x60
sSentretGfx43_1:
.incbin "baserom.gba", 0xC19CBC, 0x40
sSentretGfx43_2:
.incbin "baserom.gba", 0xC19CFC, 0x40
sSentretSprites43:
ax_sprite sSentretGfx43, 0x60
ax_sprite 0, 0x20
ax_sprite sSentretGfx43_1, 0x40
ax_sprite 0, 0x40
ax_sprite sSentretGfx43_2, 0x40
ax_sprite 0, 0xc0
ax_sprite_terminator
sSentretGfx44:
.incbin "baserom.gba", 0xC19D74, 0x40
sSentretGfx44_1:
.incbin "baserom.gba", 0xC19DB4, 0xE0
sSentretSprites44:
ax_sprite sSentretGfx44, 0x40
ax_sprite 0, 0x40
ax_sprite sSentretGfx44_1, 0xe0
ax_sprite 0, 0xa0
ax_sprite_terminator
sSentretGfx45:
.incbin "baserom.gba", 0xC19EBC, 0x60
sSentretGfx45_1:
.incbin "baserom.gba", 0xC19F1C, 0x60
sSentretGfx45_2:
.incbin "baserom.gba", 0xC19F7C, 0x60
sSentretGfx45_3:
.incbin "baserom.gba", 0xC19FDC, 0x20
sSentretSprites45:
ax_sprite sSentretGfx45, 0x60
ax_sprite 0, 0x20
ax_sprite sSentretGfx45_1, 0x60
ax_sprite 0, 0x20
ax_sprite sSentretGfx45_2, 0x60
ax_sprite 0, 0x60
ax_sprite sSentretGfx45_3, 0x20
ax_sprite 0, 0x20
ax_sprite_terminator
sSentretGfx46:
.incbin "baserom.gba", 0xC1A044, 0x40
sSentretGfx46_1:
.incbin "baserom.gba", 0xC1A084, 0x100
sSentretSprites46:
ax_sprite sSentretGfx46, 0x40
ax_sprite 0, 0x40
ax_sprite sSentretGfx46_1, 0x100
ax_sprite 0, 0x80
ax_sprite_terminator
sSentretGfx47:
.incbin "baserom.gba", 0xC1A1AC, 0x60
sSentretGfx47_1:
.incbin "baserom.gba", 0xC1A20C, 0x80
sSentretSprites47:
ax_sprite sSentretGfx47, 0x60
ax_sprite 0, 0x20
ax_sprite sSentretGfx47_1, 0x80
ax_sprite_terminator
sSentretGfx48:
.incbin "baserom.gba", 0xC1A2AC, 0x60
sSentretGfx48_1:
.incbin "baserom.gba", 0xC1A30C, 0x60
sSentretGfx48_2:
.incbin "baserom.gba", 0xC1A36C, 0x60
sSentretSprites48:
ax_sprite sSentretGfx48, 0x60
ax_sprite 0, 0x20
ax_sprite sSentretGfx48_1, 0x60
ax_sprite 0, 0x20
ax_sprite sSentretGfx48_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sSentretGfx49:
.incbin "baserom.gba", 0xC1A404, 0x60
sSentretGfx49_1:
.incbin "baserom.gba", 0xC1A464, 0x60
sSentretGfx49_2:
.incbin "baserom.gba", 0xC1A4C4, 0x60
sSentretSprites49:
ax_sprite sSentretGfx49, 0x60
ax_sprite 0, 0x20
ax_sprite sSentretGfx49_1, 0x60
ax_sprite 0, 0x20
ax_sprite sSentretGfx49_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sSentretGfx50:
.incbin "baserom.gba", 0xC1A55C, 0x60
sSentretGfx50_1:
.incbin "baserom.gba", 0xC1A5BC, 0x60
sSentretGfx50_2:
.incbin "baserom.gba", 0xC1A61C, 0x20
sSentretGfx50_3:
.incbin "baserom.gba", 0xC1A63C, 0x20
sSentretSprites50:
ax_sprite sSentretGfx50, 0x60
ax_sprite 0, 0x20
ax_sprite sSentretGfx50_1, 0x60
ax_sprite 0, 0x60
ax_sprite sSentretGfx50_2, 0x20
ax_sprite 0, 0x60
ax_sprite sSentretGfx50_3, 0x20
ax_sprite 0, 0x20
ax_sprite_terminator
sSentretGfx51:
.incbin "baserom.gba", 0xC1A6A4, 0x200
sSentretSprites51:
ax_sprite sSentretGfx51, 0x200
ax_sprite_terminator
sSentretGfx52:
.incbin "baserom.gba", 0xC1A8B4, 0x200
sSentretSprites52:
ax_sprite sSentretGfx52, 0x200
ax_sprite_terminator
sSentretGfx53:
.incbin "baserom.gba", 0xC1AAC4, 0x200
sSentretSprites53:
ax_sprite sSentretGfx53, 0x200
ax_sprite_terminator
sSentretGfx54:
.incbin "baserom.gba", 0xC1ACD4, 0x200
sSentretSprites54:
ax_sprite sSentretGfx54, 0x200
ax_sprite_terminator
sSentretGfx55:
.incbin "baserom.gba", 0xC1AEE4, 0x200
sSentretSprites55:
ax_sprite sSentretGfx55, 0x200
ax_sprite_terminator
sSentretGfx56:
.incbin "baserom.gba", 0xC1B0F4, 0x200
sSentretSprites56:
ax_sprite sSentretGfx56, 0x200
ax_sprite_terminator
sSentretGfx57:
.incbin "baserom.gba", 0xC1B304, 0x200
sSentretSprites57:
ax_sprite sSentretGfx57, 0x200
ax_sprite_terminator
sAxPosesSentret:
.4byte sSentretPose1
.4byte sSentretPose2
.4byte sSentretPose3
.4byte sSentretPose4
.4byte sSentretPose5
.4byte sSentretPose6
.4byte sSentretPose7
.4byte sSentretPose8
.4byte sSentretPose9
.4byte sSentretPose10
.4byte sSentretPose11
.4byte sSentretPose12
.4byte sSentretPose13
.4byte sSentretPose14
.4byte sSentretPose15
.4byte sSentretPose16
.4byte sSentretPose17
.4byte sSentretPose18
.4byte sSentretPose19
.4byte sSentretPose20
.4byte sSentretPose21
.4byte sSentretPose22
.4byte sSentretPose23
.4byte sSentretPose24
.4byte sSentretPose25
.4byte sSentretPose26
.4byte sSentretPose27
.4byte sSentretPose28
.4byte sSentretPose29
.4byte sSentretPose30
.4byte sSentretPose31
.4byte sSentretPose32
.4byte sSentretPose33
.4byte sSentretPose34
.4byte sSentretPose35
.4byte sSentretPose36
.4byte sSentretPose37
.4byte sSentretPose38
.4byte sSentretPose39
.4byte sSentretPose40
.4byte sSentretPose41
.4byte sSentretPose42
.4byte sSentretPose43
.4byte sSentretPose44
.4byte sSentretPose45
.4byte sSentretPose46
.4byte sSentretPose47
.4byte sSentretPose48
.4byte sSentretPose49
.4byte sSentretPose50
.4byte sSentretPose51
.4byte sSentretPose52
.4byte sSentretPose53
.4byte sSentretPose54
.4byte sSentretPose55
.4byte sSentretPose56
.4byte sSentretPose57
.4byte sSentretPose58
.4byte sSentretPose59
.4byte sSentretPose60
.4byte sSentretPose61
.4byte sSentretPose62
.4byte sSentretPose63
.4byte sSentretPose64
.4byte sSentretPose65
.4byte sSentretPose66
.4byte sSentretPose67
.4byte sSentretPose68
.4byte sSentretPose69
.4byte sSentretPose70
.4byte sSentretPose71
.4byte sSentretPose72
.4byte sSentretPose73
.4byte sSentretPose74
.4byte sSentretPose75
.4byte sSentretPose76
.4byte sSentretPose77
.4byte sSentretPose78
.4byte sSentretPose79
.4byte sSentretPose80
.4byte sSentretPose81
.4byte sSentretPose82
.4byte sSentretPose83
.4byte sSentretPose84
.4byte sSentretPose85
.4byte sSentretPose86
.4byte sSentretPose87
.4byte sSentretPose88
.4byte sSentretPose89
.4byte sSentretPose90
.4byte sSentretPose91
.4byte sSentretPose92
.4byte sSentretPose93
.4byte sSentretPose94
.4byte sSentretPose95
.4byte sSentretPose96
.4byte sSentretPose97
.4byte sSentretPose98
.4byte sSentretPose99
.4byte sSentretPose100
.4byte sSentretPose101
.4byte sSentretPose102
.4byte sSentretPose103
.4byte sSentretPose104
.4byte sSentretPose105
.4byte sSentretPose106
.4byte sSentretPose107
.4byte sSentretPose108
.4byte sSentretPose109
.4byte sSentretPose110
.4byte sSentretPose111
.4byte sSentretPose112
.4byte sSentretPose113
.4byte sSentretPose114
.4byte sSentretPose115
.4byte sSentretPose116
.4byte sSentretPose117
.4byte sSentretPose118
.4byte sSentretPose119
.4byte sSentretPose120
.4byte sSentretPose121
.4byte sSentretPose122
.4byte sSentretPose123
.4byte sSentretPose124
.4byte sSentretPose125
.4byte sSentretPose126
.4byte sSentretPose127
.4byte sSentretPose128
.4byte sSentretPose129
.4byte sSentretPose130
.4byte sSentretPose131
.4byte sSentretPose132
.4byte sSentretPose133
.4byte sSentretPose134
.4byte sSentretPose135
.4byte sSentretPose136
.4byte sSentretPose137
.4byte sSentretPose138
.4byte sSentretPose139
.4byte sSentretPose140
.4byte sSentretPose141
.4byte sSentretPose142
.4byte sSentretPose143
.4byte sSentretPose144
.4byte sSentretPose145
.4byte sSentretPose146
.4byte sSentretPose147
.4byte sSentretPose148
.4byte sSentretPose149
.4byte sSentretPose150
.4byte sSentretPose151
.4byte sSentretPose152
.4byte sSentretPose153
.4byte sSentretPose154
.4byte sSentretPose155
.4byte sSentretPose156
.4byte sSentretPose157
.4byte sSentretPose158
.4byte sSentretPose159
.4byte sSentretPose160
.4byte sSentretPose161
.4byte sSentretPose162
.4byte sSentretPose163
.4byte sSentretPose164
.4byte sSentretPose165
.4byte sSentretPose166
.4byte sSentretPose167
.4byte sSentretPose168
.4byte sSentretPose169
.4byte sSentretPose170
.4byte sSentretPose171
.4byte sSentretPose172
.4byte sSentretPose173
.4byte sSentretPose174
.4byte sSentretPose175
.4byte sSentretPose176
.4byte sSentretPose177
.4byte sSentretPose178
.4byte sSentretPose179
.4byte sSentretPose180
.4byte sSentretPose181
.4byte sSentretPose182
.4byte sSentretPose183
.4byte sSentretPose184
.4byte sSentretPose185
.4byte sSentretPose186
.4byte sSentretPose187
.4byte sSentretPose188
.4byte sSentretPose189
.4byte sSentretPose190
.4byte sSentretPose191
.4byte sSentretPose192
.4byte sSentretPose193
.4byte sSentretPose194
.4byte sSentretPose195
.4byte sSentretPose196
.4byte sSentretPose197
.4byte sSentretPose198
.4byte sSentretPose199
.4byte sSentretPose200
.4byte sSentretPose201
.4byte sSentretPose202
.4byte sSentretPose203
.4byte sSentretPose204
.4byte sSentretPose205
.4byte sSentretPose206
.4byte sSentretPose207
.4byte sSentretPose208
.4byte sSentretPose209
.4byte sSentretPose210
.4byte sSentretPose211
.4byte sSentretPose212
.4byte sSentretPose213
.4byte sSentretPose214
.4byte sSentretPose215
.4byte sSentretPose216
.4byte sSentretPose217
.4byte sSentretPose218
.4byte sSentretPose219
.4byte sSentretPose220
.4byte sSentretPose221
.4byte sSentretPose222
.4byte sSentretPose223
.4byte sSentretPose224
.4byte sSentretPose225
.4byte sSentretPose226
.4byte sSentretPose227
.4byte sSentretPose228
.4byte sSentretPose229
.4byte sSentretPose230
.4byte sSentretPose231
.4byte sSentretPose232
.4byte sSentretPose233
.4byte sSentretPose234
.4byte sSentretPose235
.4byte sSentretPose236
.4byte sSentretPose237
.4byte sSentretPose238
.4byte sSentretPose239
.4byte sSentretPose240
.4byte sSentretPose241
.4byte sSentretPose242
.4byte sSentretPose243
.4byte sSentretPose244
.4byte sSentretPose245
.4byte sSentretPose246
.4byte sSentretPose247
.4byte sSentretPose248
.4byte sSentretPose249
.4byte sSentretPose250
sAxPositionsSentret:
.2byte   -1,   -9, 	  -9,   -4, 	   7,   -4, 	  -1,   -6
.2byte   -1,   -8, 	  -8,   -2, 	   6,   -5, 	  -1,   -5
.2byte   -1,   -8, 	  -8,   -5, 	   6,   -2, 	  -1,   -5
.2byte    1,   -9, 	   7,   -7, 	  -4,   -2, 	  -1,   -6
.2byte    1,   -8, 	   8,   -5, 	  -7,   -4, 	   0,   -5
.2byte    2,   -8, 	   6,   -8, 	  -2,   -3, 	  -1,   -5
.2byte    4,   -9, 	   6,   -9, 	   4,   -4, 	  -1,   -7
.2byte    4,   -8, 	   7,   -7, 	   1,   -2, 	  -1,   -7
.2byte    4,   -8, 	   4,  -10, 	   6,   -4, 	  -1,   -6
.2byte    1,  -11, 	  -4,  -11, 	   8,   -6, 	  -2,   -7
.2byte    1,   -9, 	  -5,   -8, 	   5,   -2, 	  -2,   -6
.2byte   -1,  -10, 	  -8,  -10, 	   8,   -8, 	  -1,   -6
.2byte   -1,  -10, 	   7,   -7, 	  -9,   -7, 	  -1,   -8
.2byte   -1,   -9, 	   7,  -10, 	  -9,   -4, 	  -1,   -7
.2byte   -1,   -9, 	   7,   -4, 	  -9,  -10, 	  -1,   -7
.2byte   -3,  -11, 	   2,  -11, 	 -10,   -6, 	   0,   -7
.2byte   -3,   -9, 	   3,   -8, 	  -7,   -2, 	   0,   -6
.2byte   -1,  -10, 	   6,  -10, 	 -10,   -8, 	  -1,   -6
.2byte   -6,   -9, 	  -8,   -9, 	  -6,   -4, 	  -1,   -7
.2byte   -6,   -8, 	  -9,   -7, 	  -3,   -2, 	  -1,   -7
.2byte   -6,   -8, 	  -6,  -10, 	  -8,   -4, 	  -1,   -6
.2byte   -2,   -9, 	  -8,   -7, 	   3,   -2, 	   0,   -6
.2byte   -2,   -8, 	  -9,   -5, 	   6,   -4, 	  -1,   -5
.2byte   -3,   -8, 	  -7,   -8, 	   1,   -3, 	   0,   -5
.2byte   -1,   -9, 	  -9,   -4, 	   7,   -4, 	  -1,   -6
.2byte   -1,  -20, 	 -11,  -21, 	   9,  -21, 	  -1,  -17
.2byte   -1,  -10, 	  -9,  -11, 	   7,  -11, 	  -1,  -11
.2byte   -1,   -8, 	 -10,  -11, 	   7,  -11, 	  -1,  -10
.2byte   -1,   -8, 	 -10,  -13, 	   8,  -13, 	  -1,  -10
.2byte    1,   -9, 	   7,   -7, 	  -4,   -2, 	  -1,   -6
.2byte    1,  -20, 	   7,  -20, 	 -10,  -19, 	  -1,  -17
.2byte    2,  -14, 	   5,  -16, 	  -3,  -15, 	  -2,  -16
.2byte    5,  -12, 	  11,  -21, 	  -3,  -14, 	   2,  -16
.2byte    5,  -16, 	   7,  -23, 	  -7,  -18, 	   2,  -15
.2byte    4,   -9, 	   6,   -9, 	   4,   -4, 	  -1,   -7
.2byte    4,  -20, 	  -1,  -22, 	  -1,  -17, 	  -1,  -18
.2byte    3,  -12, 	   3,  -17, 	   2,  -11, 	  -3,  -14
.2byte    8,  -15, 	   4,  -21, 	   3,  -16, 	   1,  -17
.2byte    8,  -17, 	  -1,  -21, 	  -3,  -18, 	   2,  -16
.2byte    1,  -11, 	  -4,  -11, 	   8,   -6, 	  -2,   -7
.2byte    0,  -21, 	  -7,  -23, 	   8,  -18, 	  -2,  -18
.2byte    0,  -14, 	  -5,  -18, 	   6,  -12, 	  -4,  -14
.2byte    4,  -19, 	  -6,  -23, 	   9,  -17, 	   0,  -19
.2byte    2,  -21, 	  -7,  -23, 	   7,  -13, 	  -1,  -19
.2byte   -1,  -10, 	   7,   -7, 	  -9,   -7, 	  -1,   -8
.2byte   -1,  -21, 	   8,  -20, 	 -10,  -20, 	  -1,  -17
.2byte   -1,  -13, 	   7,  -12, 	  -9,  -12, 	  -1,  -12
.2byte   -1,  -22, 	   8,  -21, 	 -10,  -21, 	  -1,  -21
.2byte   -1,  -21, 	   7,  -18, 	  -9,  -18, 	  -1,  -20
.2byte   -3,  -11, 	   2,  -11, 	 -10,   -6, 	   0,   -7
.2byte   -2,  -21, 	   5,  -23, 	 -10,  -18, 	   0,  -18
.2byte   -2,  -14, 	   3,  -18, 	  -8,  -12, 	   2,  -14
.2byte   -6,  -19, 	   4,  -23, 	 -11,  -17, 	  -2,  -19
.2byte   -4,  -20, 	   5,  -22, 	  -9,  -12, 	  -1,  -18
.2byte   -6,   -9, 	  -8,   -9, 	  -6,   -4, 	  -1,   -7
.2byte   -6,  -20, 	  -1,  -22, 	  -1,  -17, 	  -1,  -18
.2byte   -5,  -12, 	  -5,  -17, 	  -4,  -11, 	   1,  -14
.2byte  -10,  -15, 	  -6,  -21, 	  -5,  -16, 	  -3,  -17
.2byte  -10,  -16, 	  -1,  -20, 	   1,  -17, 	  -4,  -15
.2byte   -2,   -9, 	  -8,   -7, 	   3,   -2, 	   0,   -6
.2byte   -2,  -20, 	  -8,  -20, 	   9,  -19, 	   0,  -17
.2byte   -3,  -14, 	  -6,  -16, 	   2,  -15, 	   1,  -16
.2byte   -6,  -12, 	 -12,  -21, 	   2,  -14, 	  -3,  -16
.2byte   -6,  -15, 	  -8,  -22, 	   6,  -17, 	  -3,  -14
.2byte   -1,   -9, 	  -9,   -4, 	   7,   -4, 	  -1,   -6
.2byte   -1,   -8, 	  -8,   -2, 	   6,   -5, 	  -1,   -5
.2byte   -1,   -8, 	  -8,   -5, 	   6,   -2, 	  -1,   -5
.2byte   -1,   -9, 	  -9,  -13, 	   4,   -5, 	   0,   -7
.2byte    0,   -6, 	  -2,   -2, 	   8,   -9, 	   0,   -5
.2byte    0,   -6, 	  -2,   -2, 	   8,   -9, 	   0,   -5
.2byte    1,   -9, 	   7,   -7, 	  -4,   -2, 	  -1,   -6
.2byte    1,   -8, 	   8,   -5, 	  -7,   -4, 	   0,   -5
.2byte    2,   -8, 	   6,   -8, 	  -2,   -3, 	  -1,   -5
.2byte    1,   -9, 	   5,  -14, 	  -2,   -5, 	  -1,   -7
.2byte    1,   -7, 	   2,   -3, 	 -10,   -9, 	  -1,   -8
.2byte    1,   -7, 	   2,   -3, 	 -10,   -9, 	  -1,   -8
.2byte    4,   -9, 	   6,   -9, 	   4,   -4, 	  -1,   -7
.2byte    4,   -8, 	   7,   -7, 	   1,   -2, 	  -1,   -7
.2byte    4,   -8, 	   4,  -10, 	   6,   -4, 	  -1,   -6
.2byte    4,   -9, 	  -6,  -14, 	   6,   -7, 	  -1,   -7
.2byte    3,   -7, 	   7,   -6, 	  -6,   -7, 	  -2,   -6
.2byte    3,   -7, 	   7,   -6, 	  -6,   -7, 	  -2,   -6
.2byte    1,  -11, 	  -4,  -11, 	   8,   -6, 	  -2,   -7
.2byte    1,   -9, 	  -5,   -8, 	   5,   -2, 	  -2,   -6
.2byte   -1,  -10, 	  -8,  -10, 	   8,   -8, 	  -1,   -6
.2byte   -1,   -9, 	  -9,  -13, 	   7,  -10, 	  -1,   -7
.2byte    1,   -8, 	  -3,   -6, 	   4,   -6, 	  -2,   -6
.2byte    1,   -8, 	  -3,   -6, 	   4,   -6, 	  -2,   -6
.2byte   -1,  -10, 	   7,   -7, 	  -9,   -7, 	  -1,   -8
.2byte   -1,   -9, 	   7,  -10, 	  -9,   -4, 	  -1,   -7
.2byte   -1,   -9, 	   7,   -4, 	  -9,  -10, 	  -1,   -7
.2byte   -1,  -10, 	   8,  -12, 	  -6,   -9, 	  -1,   -8
.2byte   -1,   -8, 	   2,   -6, 	 -10,  -10, 	   0,   -7
.2byte   -1,   -8, 	   2,   -6, 	 -10,  -10, 	   0,   -7
.2byte   -3,  -11, 	   2,  -11, 	 -10,   -6, 	   0,   -7
.2byte   -3,   -9, 	   3,   -8, 	  -7,   -2, 	   0,   -6
.2byte   -1,  -10, 	   6,  -10, 	 -10,   -8, 	  -1,   -6
.2byte   -1,   -9, 	   7,  -13, 	  -9,  -10, 	  -1,   -7
.2byte   -3,   -8, 	   1,   -6, 	  -6,   -6, 	   0,   -6
.2byte   -3,   -8, 	   1,   -6, 	  -6,   -6, 	   0,   -6
.2byte   -6,   -9, 	  -8,   -9, 	  -6,   -4, 	  -1,   -7
.2byte   -6,   -8, 	  -9,   -7, 	  -3,   -2, 	  -1,   -7
.2byte   -6,   -8, 	  -6,  -10, 	  -8,   -4, 	  -1,   -6
.2byte   -6,   -9, 	   4,  -14, 	  -8,   -7, 	  -1,   -7
.2byte   -5,   -7, 	  -9,   -6, 	   4,   -7, 	   0,   -6
.2byte   -5,   -7, 	  -9,   -6, 	   4,   -7, 	   0,   -6
.2byte   -2,   -9, 	  -8,   -7, 	   3,   -2, 	   0,   -6
.2byte   -2,   -8, 	  -9,   -5, 	   6,   -4, 	  -1,   -5
.2byte   -3,   -8, 	  -7,   -8, 	   1,   -3, 	   0,   -5
.2byte   -2,   -9, 	  -6,  -14, 	   1,   -5, 	   0,   -7
.2byte   -2,   -7, 	  -3,   -3, 	   9,   -9, 	   0,   -8
.2byte   -2,   -7, 	  -3,   -3, 	   9,   -9, 	   0,   -8
.2byte   -1,   -9, 	  -9,   -4, 	   7,   -4, 	  -1,   -6
.2byte   -1,   -4, 	 -10,   -9, 	   8,   -9, 	  -1,   -6
.2byte    1,   -9, 	   7,   -7, 	  -4,   -2, 	  -1,   -6
.2byte    5,   -7, 	   7,  -14, 	  -7,   -9, 	   2,   -6
.2byte    4,   -9, 	   6,   -9, 	   4,   -4, 	  -1,   -7
.2byte    8,   -9, 	  -1,  -13, 	  -3,  -10, 	   2,   -8
.2byte    1,  -11, 	  -4,  -11, 	   8,   -6, 	  -2,   -7
.2byte    2,  -10, 	  -7,  -12, 	   7,   -2, 	  -1,   -8
.2byte   -1,  -10, 	   7,   -7, 	  -9,   -7, 	  -1,   -8
.2byte   -1,   -9, 	   7,   -6, 	  -9,   -6, 	  -1,   -8
.2byte   -3,  -11, 	   2,  -11, 	 -10,   -6, 	   0,   -7
.2byte   -4,  -10, 	   5,  -12, 	  -9,   -2, 	  -1,   -8
.2byte   -6,   -9, 	  -8,   -9, 	  -6,   -4, 	  -1,   -7
.2byte  -10,   -9, 	  -1,  -13, 	   1,  -10, 	  -4,   -8
.2byte   -2,   -9, 	  -8,   -7, 	   3,   -2, 	   0,   -6
.2byte   -6,   -7, 	  -8,  -14, 	   6,   -9, 	  -3,   -6
.2byte   -1,   -9, 	  -9,   -4, 	   7,   -4, 	  -1,   -6
.2byte   -1,  -20, 	 -11,  -21, 	   9,  -21, 	  -1,  -17
.2byte    1,   -9, 	   7,   -7, 	  -4,   -2, 	  -1,   -6
.2byte    1,  -20, 	   7,  -20, 	 -10,  -19, 	  -1,  -17
.2byte    4,   -9, 	   6,   -9, 	   4,   -4, 	  -1,   -7
.2byte    4,  -20, 	  -1,  -22, 	  -1,  -17, 	  -1,  -18
.2byte    1,  -11, 	  -4,  -11, 	   8,   -6, 	  -2,   -7
.2byte    0,  -21, 	  -7,  -23, 	   8,  -18, 	  -2,  -18
.2byte   -1,  -10, 	   7,   -7, 	  -9,   -7, 	  -1,   -8
.2byte   -1,  -21, 	   8,  -20, 	 -10,  -20, 	  -1,  -17
.2byte   -3,  -11, 	   2,  -11, 	 -10,   -6, 	   0,   -7
.2byte   -2,  -21, 	   5,  -23, 	 -10,  -18, 	   0,  -18
.2byte   -6,   -9, 	  -8,   -9, 	  -6,   -4, 	  -1,   -7
.2byte   -6,  -20, 	  -1,  -22, 	  -1,  -17, 	  -1,  -18
.2byte   -2,   -9, 	  -8,   -7, 	   3,   -2, 	   0,   -6
.2byte   -2,  -20, 	  -8,  -20, 	   9,  -19, 	   0,  -17
.2byte    2,   -5, 	  -1,   -5, 	   6,   -2, 	   1,   -5
.2byte    2,   -5, 	  -1,   -4, 	   6,   -2, 	   1,   -5
.2byte    0,  -10, 	 -10,  -11, 	  10,  -11, 	   0,   -8
.2byte   -2,  -10, 	   4,  -14, 	 -14,   -7, 	  -3,   -8
.2byte    0,  -11, 	 -10,  -13, 	 -10,   -8, 	  -4,   -8
.2byte   -2,   -9, 	 -11,   -6, 	   2,   -4, 	  -5,   -6
.2byte    0,   -6, 	   9,   -3, 	  -9,   -3, 	   0,   -4
.2byte    2,   -9, 	  11,   -6, 	  -2,   -4, 	   5,   -6
.2byte   -1,  -11, 	   9,  -13, 	   9,   -8, 	   3,   -8
.2byte    2,  -10, 	  -4,  -14, 	  14,   -7, 	   3,   -8
.2byte   -1,   -9, 	  -9,   -4, 	   7,   -4, 	  -1,   -6
.2byte   -1,  -20, 	 -11,  -21, 	   9,  -21, 	  -1,  -17
.2byte   -1,  -10, 	  -9,  -11, 	   7,  -11, 	  -1,  -11
.2byte   -1,   -8, 	 -10,  -11, 	   7,  -11, 	  -1,  -10
.2byte   -1,   -8, 	 -10,  -13, 	   8,  -13, 	  -1,  -10
.2byte    1,   -9, 	   7,   -7, 	  -4,   -2, 	  -1,   -6
.2byte    1,  -20, 	   7,  -20, 	 -10,  -19, 	  -1,  -17
.2byte    2,  -14, 	   5,  -16, 	  -3,  -15, 	  -2,  -16
.2byte    5,  -12, 	  11,  -21, 	  -3,  -14, 	   2,  -16
.2byte    5,  -16, 	   7,  -23, 	  -7,  -18, 	   2,  -15
.2byte    4,   -9, 	   6,   -9, 	   4,   -4, 	  -1,   -7
.2byte    4,  -20, 	  -1,  -22, 	  -1,  -17, 	  -1,  -18
.2byte    3,  -12, 	   3,  -17, 	   2,  -11, 	  -3,  -14
.2byte    8,  -15, 	   4,  -21, 	   3,  -16, 	   1,  -17
.2byte    8,  -17, 	  -1,  -21, 	  -3,  -18, 	   2,  -16
.2byte    1,  -11, 	  -4,  -11, 	   8,   -6, 	  -2,   -7
.2byte    0,  -21, 	  -7,  -23, 	   8,  -18, 	  -2,  -18
.2byte    0,  -14, 	  -5,  -18, 	   6,  -12, 	  -4,  -14
.2byte    4,  -19, 	  -6,  -23, 	   9,  -17, 	   0,  -19
.2byte    2,  -21, 	  -7,  -23, 	   7,  -13, 	  -1,  -19
.2byte   -1,  -10, 	   7,   -7, 	  -9,   -7, 	  -1,   -8
.2byte   -1,  -21, 	   8,  -20, 	 -10,  -20, 	  -1,  -17
.2byte   -1,  -13, 	   7,  -12, 	  -9,  -12, 	  -1,  -12
.2byte   -1,  -22, 	   8,  -21, 	 -10,  -21, 	  -1,  -21
.2byte   -1,  -21, 	   7,  -18, 	  -9,  -18, 	  -1,  -20
.2byte   -3,  -11, 	   2,  -11, 	 -10,   -6, 	   0,   -7
.2byte   -2,  -21, 	   5,  -23, 	 -10,  -18, 	   0,  -18
.2byte   -2,  -14, 	   3,  -18, 	  -8,  -12, 	   2,  -14
.2byte   -6,  -19, 	   4,  -23, 	 -11,  -17, 	  -2,  -19
.2byte   -4,  -20, 	   5,  -22, 	  -9,  -12, 	  -1,  -18
.2byte   -6,   -9, 	  -8,   -9, 	  -6,   -4, 	  -1,   -7
.2byte   -6,  -20, 	  -1,  -22, 	  -1,  -17, 	  -1,  -18
.2byte   -5,  -12, 	  -5,  -17, 	  -4,  -11, 	   1,  -14
.2byte  -10,  -15, 	  -6,  -21, 	  -5,  -16, 	  -3,  -17
.2byte  -10,  -16, 	  -1,  -20, 	   1,  -17, 	  -4,  -15
.2byte   -2,   -9, 	  -8,   -7, 	   3,   -2, 	   0,   -6
.2byte   -2,  -20, 	  -8,  -20, 	   9,  -19, 	   0,  -17
.2byte   -3,  -14, 	  -6,  -16, 	   2,  -15, 	   1,  -16
.2byte   -6,  -12, 	 -12,  -21, 	   2,  -14, 	  -3,  -16
.2byte   -6,  -15, 	  -8,  -22, 	   6,  -17, 	  -3,  -14
.2byte   -1,   -9, 	  -9,   -4, 	   7,   -4, 	  -1,   -6
.2byte   -2,   -9, 	  -8,   -7, 	   3,   -2, 	   0,   -6
.2byte   -5,   -9, 	  -7,   -9, 	  -5,   -4, 	   0,   -7
.2byte   -1,  -11, 	   4,  -11, 	  -8,   -6, 	   2,   -7
.2byte   -1,  -10, 	   7,   -7, 	  -9,   -7, 	  -1,   -8
.2byte   -1,  -11, 	  -6,  -11, 	   6,   -6, 	  -4,   -7
.2byte    3,   -9, 	   5,   -9, 	   3,   -4, 	  -2,   -7
.2byte    0,   -9, 	   6,   -7, 	  -5,   -2, 	  -2,   -6
.2byte   -1,  -20, 	 -11,  -21, 	   9,  -21, 	  -1,  -17
.2byte    2,  -19, 	   8,  -19, 	  -9,  -18, 	   0,  -16
.2byte    6,  -19, 	   1,  -21, 	   1,  -16, 	   1,  -17
.2byte    1,  -21, 	  -6,  -23, 	   9,  -18, 	  -1,  -18
.2byte   -1,  -21, 	   8,  -20, 	 -10,  -20, 	  -1,  -17
.2byte   -2,  -21, 	   5,  -23, 	 -10,  -18, 	   0,  -18
.2byte   -7,  -19, 	  -2,  -21, 	  -2,  -16, 	  -2,  -17
.2byte   -3,  -19, 	  -9,  -19, 	   8,  -18, 	  -1,  -16
.2byte   -1,   -9, 	  -9,   -4, 	   7,   -4, 	  -1,   -6
.2byte   -1,  -20, 	 -11,  -21, 	   9,  -21, 	  -1,  -17
.2byte   -1,   -6, 	 -10,  -11, 	   8,  -11, 	  -1,   -8
.2byte    1,   -9, 	   7,   -7, 	  -4,   -2, 	  -1,   -6
.2byte    1,  -12, 	   7,  -12, 	 -10,  -11, 	  -1,   -9
.2byte    3,   -9, 	   5,  -16, 	  -9,  -11, 	   0,   -8
.2byte    4,   -9, 	   6,   -9, 	   4,   -4, 	  -1,   -7
.2byte    4,  -16, 	  -1,  -18, 	  -1,  -13, 	  -1,  -14
.2byte    5,  -13, 	  -4,  -17, 	  -6,  -14, 	  -1,  -12
.2byte    1,  -11, 	  -4,  -11, 	   8,   -6, 	  -2,   -7
.2byte    0,  -13, 	  -7,  -15, 	   8,  -10, 	  -2,  -10
.2byte    2,  -13, 	  -7,  -15, 	   7,   -5, 	  -1,  -11
.2byte   -1,  -10, 	   7,   -7, 	  -9,   -7, 	  -1,   -8
.2byte   -1,  -12, 	   8,  -11, 	 -10,  -11, 	  -1,   -8
.2byte   -1,  -12, 	   7,   -9, 	  -9,   -9, 	  -1,  -11
.2byte   -2,  -11, 	   3,  -11, 	  -9,   -6, 	   1,   -7
.2byte   -1,  -13, 	   6,  -15, 	  -9,  -10, 	   1,  -10
.2byte   -3,  -13, 	   6,  -15, 	  -8,   -5, 	   0,  -11
.2byte   -5,   -9, 	  -7,   -9, 	  -5,   -4, 	   0,   -7
.2byte   -5,  -16, 	   0,  -18, 	   0,  -13, 	   0,  -14
.2byte   -6,  -13, 	   3,  -17, 	   5,  -14, 	   0,  -12
.2byte   -2,   -9, 	  -8,   -7, 	   3,   -2, 	   0,   -6
.2byte   -2,  -12, 	  -8,  -12, 	   9,  -11, 	   0,   -9
.2byte   -4,   -9, 	  -6,  -16, 	   8,  -11, 	  -1,   -8
.2byte    0,   -6, 	  -2,   -2, 	   8,   -9, 	   0,   -5
.2byte   -3,   -7, 	  -4,   -3, 	   8,   -9, 	  -1,   -8
.2byte   -5,   -7, 	  -9,   -6, 	   4,   -7, 	   0,   -6
.2byte   -3,   -8, 	   1,   -6, 	  -6,   -6, 	   0,   -6
.2byte   -1,   -8, 	   2,   -6, 	 -10,  -10, 	   0,   -7
.2byte    1,   -8, 	  -3,   -6, 	   4,   -6, 	  -2,   -6
.2byte    3,   -7, 	   7,   -6, 	  -6,   -7, 	  -2,   -6
.2byte    2,   -7, 	   3,   -3, 	  -9,   -9, 	   0,   -8
.2byte   -1,   -9, 	  -9,   -4, 	   7,   -4, 	  -1,   -6
.2byte   -3,   -9, 	  -9,   -7, 	   2,   -2, 	  -1,   -6
.2byte   -6,   -9, 	  -8,   -9, 	  -6,   -4, 	  -1,   -7
.2byte   -3,  -11, 	   2,  -11, 	 -10,   -6, 	   0,   -7
.2byte   -1,  -10, 	   7,   -7, 	  -9,   -7, 	  -1,   -8
.2byte    1,  -11, 	  -4,  -11, 	   8,   -6, 	  -2,   -7
.2byte    4,   -9, 	   6,   -9, 	   4,   -4, 	  -1,   -7
.2byte    1,   -9, 	   7,   -7, 	  -4,   -2, 	  -1,   -6
sSentretAnimTable1:
.4byte sSentretAnims_1_1
.4byte sSentretAnims_1_2
.4byte sSentretAnims_1_3
.4byte sSentretAnims_1_4
.4byte sSentretAnims_1_5
.4byte sSentretAnims_1_6
.4byte sSentretAnims_1_7
.4byte sSentretAnims_1_8
sSentretAnimTable2:
.4byte sSentretAnims_2_1
.4byte sSentretAnims_2_2
.4byte sSentretAnims_2_3
.4byte sSentretAnims_2_4
.4byte sSentretAnims_2_5
.4byte sSentretAnims_2_6
.4byte sSentretAnims_2_7
.4byte sSentretAnims_2_8
sSentretAnimTable3:
.4byte sSentretAnims_3_1
.4byte sSentretAnims_3_2
.4byte sSentretAnims_3_3
.4byte sSentretAnims_3_4
.4byte sSentretAnims_3_5
.4byte sSentretAnims_3_6
.4byte sSentretAnims_3_7
.4byte sSentretAnims_3_8
sSentretAnimTable4:
.4byte sSentretAnims_4_1
.4byte sSentretAnims_4_2
.4byte sSentretAnims_4_3
.4byte sSentretAnims_4_4
.4byte sSentretAnims_4_5
.4byte sSentretAnims_4_6
.4byte sSentretAnims_4_7
.4byte sSentretAnims_4_8
sSentretAnimTable5:
.4byte sSentretAnims_5_1
.4byte sSentretAnims_5_2
.4byte sSentretAnims_5_3
.4byte sSentretAnims_5_4
.4byte sSentretAnims_5_5
.4byte sSentretAnims_5_6
.4byte sSentretAnims_5_7
.4byte sSentretAnims_5_8
sSentretAnimTable6:
.4byte sSentretAnims_6_1
.4byte sSentretAnims_6_1
.4byte sSentretAnims_6_1
.4byte sSentretAnims_6_1
.4byte sSentretAnims_6_1
.4byte sSentretAnims_6_1
.4byte sSentretAnims_6_1
.4byte sSentretAnims_6_1
sSentretAnimTable7:
.4byte sSentretAnims_7_1
.4byte sSentretAnims_7_2
.4byte sSentretAnims_7_3
.4byte sSentretAnims_7_4
.4byte sSentretAnims_7_5
.4byte sSentretAnims_7_6
.4byte sSentretAnims_7_7
.4byte sSentretAnims_7_8
sSentretAnimTable8:
.4byte sSentretAnims_8_1
.4byte sSentretAnims_8_2
.4byte sSentretAnims_8_3
.4byte sSentretAnims_8_4
.4byte sSentretAnims_8_5
.4byte sSentretAnims_8_6
.4byte sSentretAnims_8_7
.4byte sSentretAnims_8_8
sSentretAnimTable9:
.4byte sSentretAnims_9_1
.4byte sSentretAnims_9_2
.4byte sSentretAnims_9_3
.4byte sSentretAnims_9_4
.4byte sSentretAnims_9_5
.4byte sSentretAnims_9_6
.4byte sSentretAnims_9_7
.4byte sSentretAnims_9_8
sSentretAnimTable10:
.4byte sSentretAnims_10_1
.4byte sSentretAnims_10_2
.4byte sSentretAnims_10_3
.4byte sSentretAnims_10_4
.4byte sSentretAnims_10_5
.4byte sSentretAnims_10_6
.4byte sSentretAnims_10_7
.4byte sSentretAnims_10_8
sSentretAnimTable11:
.4byte sSentretAnims_11_1
.4byte sSentretAnims_11_2
.4byte sSentretAnims_11_3
.4byte sSentretAnims_11_4
.4byte sSentretAnims_11_5
.4byte sSentretAnims_11_6
.4byte sSentretAnims_11_7
.4byte sSentretAnims_11_8
sSentretAnimTable12:
.4byte sSentretAnims_12_1
.4byte sSentretAnims_12_2
.4byte sSentretAnims_12_3
.4byte sSentretAnims_12_4
.4byte sSentretAnims_12_5
.4byte sSentretAnims_12_6
.4byte sSentretAnims_12_7
.4byte sSentretAnims_12_8
sSentretAnimTable13:
.4byte sSentretAnims_13_1
.4byte sSentretAnims_13_2
.4byte sSentretAnims_13_3
.4byte sSentretAnims_13_4
.4byte sSentretAnims_13_5
.4byte sSentretAnims_13_6
.4byte sSentretAnims_13_7
.4byte sSentretAnims_13_8
sAxAnimationsSentret:
.4byte sSentretAnimTable1
.4byte sSentretAnimTable2
.4byte sSentretAnimTable3
.4byte sSentretAnimTable4
.4byte sSentretAnimTable5
.4byte sSentretAnimTable6
.4byte sSentretAnimTable7
.4byte sSentretAnimTable8
.4byte sSentretAnimTable9
.4byte sSentretAnimTable10
.4byte sSentretAnimTable11
.4byte sSentretAnimTable12
.4byte sSentretAnimTable13
sAxSpritesSentret:
.4byte sSentretSprites1
.4byte sSentretSprites2
.4byte sSentretSprites3
.4byte sSentretSprites4
.4byte sSentretSprites5
.4byte sSentretSprites6
.4byte sSentretSprites7
.4byte sSentretSprites8
.4byte sSentretSprites9
.4byte sSentretSprites10
.4byte sSentretSprites11
.4byte sSentretSprites12
.4byte sSentretSprites13
.4byte sSentretSprites14
.4byte sSentretSprites15
.4byte sSentretSprites16
.4byte sSentretSprites17
.4byte sSentretSprites18
.4byte sSentretSprites19
.4byte sSentretSprites20
.4byte sSentretSprites21
.4byte sSentretSprites22
.4byte sSentretSprites23
.4byte sSentretSprites24
.4byte sSentretSprites25
.4byte sSentretSprites26
.4byte sSentretSprites27
.4byte sSentretSprites28
.4byte sSentretSprites29
.4byte sSentretSprites30
.4byte sSentretSprites31
.4byte sSentretSprites32
.4byte sSentretSprites33
.4byte sSentretSprites34
.4byte sSentretSprites35
.4byte sSentretSprites36
.4byte sSentretSprites37
.4byte sSentretSprites38
.4byte sSentretSprites39
.4byte sSentretSprites40
.4byte sSentretSprites41
.4byte sSentretSprites42
.4byte sSentretSprites43
.4byte sSentretSprites44
.4byte sSentretSprites45
.4byte sSentretSprites46
.4byte sSentretSprites47
.4byte sSentretSprites48
.4byte sSentretSprites49
.4byte sSentretSprites50
.4byte sSentretSprites51
.4byte sSentretSprites52
.4byte sSentretSprites53
.4byte sSentretSprites54
.4byte sSentretSprites55
.4byte sSentretSprites56
.4byte sSentretSprites57
sAxMainSentret:
ax_main sAxPosesSentret, sAxAnimationsSentret, 13, sAxSpritesSentret, sAxPositionsSentret
