.global gAxShuppet
gAxShuppet:
ax_siro sAxMainShuppet
sShuppetPose1:
ax_pose 0, 0x01e8, 0x80f4, 0x9c00
ax_pose_terminator
sShuppetPose2:
ax_pose 1, 0x01e8, 0x80f4, 0x9c00
ax_pose_terminator
sShuppetPose3:
ax_pose 2, 0x01e8, 0x80f4, 0x9c00
ax_pose_terminator
sShuppetPose4:
ax_pose 3, 0x01e8, 0x90ef, 0x9c00
ax_pose_terminator
sShuppetPose5:
ax_pose 4, 0x01e8, 0x90ef, 0x9c00
ax_pose_terminator
sShuppetPose6:
ax_pose 5, 0x01e8, 0x90ef, 0x9c00
ax_pose_terminator
sShuppetPose7:
ax_pose 6, 0x01e8, 0x90ef, 0x9c00
ax_pose_terminator
sShuppetPose8:
ax_pose 7, 0x01e8, 0x90ef, 0x9c00
ax_pose_terminator
sShuppetPose9:
ax_pose 8, 0x01e8, 0x90ef, 0x9c00
ax_pose_terminator
sShuppetPose10:
ax_pose 9, 0x01e6, 0x90eb, 0x9c00
ax_pose_terminator
sShuppetPose11:
ax_pose 10, 0x01e6, 0x90eb, 0x9c00
ax_pose_terminator
sShuppetPose12:
ax_pose 11, 0x01e6, 0x90eb, 0x9c00
ax_pose_terminator
sShuppetPose13:
ax_pose 12, 0x81e4, 0x80f8, 0x9c00
ax_pose_terminator
sShuppetPose14:
ax_pose 13, 0x81e4, 0x80f8, 0x9c00
ax_pose_terminator
sShuppetPose15:
ax_pose 14, 0x81e4, 0x80f8, 0x9c00
ax_pose_terminator
sShuppetPose16:
ax_pose 9, 0x01e6, 0x80f4, 0x9c00
ax_pose_terminator
sShuppetPose17:
ax_pose 10, 0x01e6, 0x80f4, 0x9c00
ax_pose_terminator
sShuppetPose18:
ax_pose 11, 0x01e6, 0x80f4, 0x9c00
ax_pose_terminator
sShuppetPose19:
ax_pose 6, 0x01e8, 0x80f0, 0x9c00
ax_pose_terminator
sShuppetPose20:
ax_pose 7, 0x01e8, 0x80f0, 0x9c00
ax_pose_terminator
sShuppetPose21:
ax_pose 8, 0x01e8, 0x80f0, 0x9c00
ax_pose_terminator
sShuppetPose22:
ax_pose 3, 0x01e8, 0x80f0, 0x9c00
ax_pose_terminator
sShuppetPose23:
ax_pose 4, 0x01e8, 0x80f0, 0x9c00
ax_pose_terminator
sShuppetPose24:
ax_pose 5, 0x01e8, 0x80f0, 0x9c00
ax_pose_terminator
sShuppetPose25:
ax_pose 0, 0x01e8, 0x80f4, 0x9c00
ax_pose_terminator
sShuppetPose26:
ax_pose 1, 0x01e8, 0x80f4, 0x9c00
ax_pose_terminator
sShuppetPose27:
ax_pose 2, 0x01e8, 0x80f4, 0x9c00
ax_pose_terminator
sShuppetPose28:
ax_pose 3, 0x01e8, 0x90ef, 0x9c00
ax_pose_terminator
sShuppetPose29:
ax_pose 4, 0x01e8, 0x90ef, 0x9c00
ax_pose_terminator
sShuppetPose30:
ax_pose 5, 0x01e8, 0x90ef, 0x9c00
ax_pose_terminator
sShuppetPose31:
ax_pose 6, 0x01e8, 0x90ef, 0x9c00
ax_pose_terminator
sShuppetPose32:
ax_pose 7, 0x01e8, 0x90ef, 0x9c00
ax_pose_terminator
sShuppetPose33:
ax_pose 8, 0x01e8, 0x90ef, 0x9c00
ax_pose_terminator
sShuppetPose34:
ax_pose 9, 0x01e6, 0x90eb, 0x9c00
ax_pose_terminator
sShuppetPose35:
ax_pose 10, 0x01e6, 0x90eb, 0x9c00
ax_pose_terminator
sShuppetPose36:
ax_pose 11, 0x01e6, 0x90eb, 0x9c00
ax_pose_terminator
sShuppetPose37:
ax_pose 12, 0x81e4, 0x80f8, 0x9c00
ax_pose_terminator
sShuppetPose38:
ax_pose 13, 0x81e4, 0x80f8, 0x9c00
ax_pose_terminator
sShuppetPose39:
ax_pose 14, 0x81e4, 0x80f8, 0x9c00
ax_pose_terminator
sShuppetPose40:
ax_pose 9, 0x01e6, 0x80f4, 0x9c00
ax_pose_terminator
sShuppetPose41:
ax_pose 10, 0x01e6, 0x80f4, 0x9c00
ax_pose_terminator
sShuppetPose42:
ax_pose 11, 0x01e6, 0x80f4, 0x9c00
ax_pose_terminator
sShuppetPose43:
ax_pose 6, 0x01e8, 0x80f0, 0x9c00
ax_pose_terminator
sShuppetPose44:
ax_pose 7, 0x01e8, 0x80f0, 0x9c00
ax_pose_terminator
sShuppetPose45:
ax_pose 8, 0x01e8, 0x80f0, 0x9c00
ax_pose_terminator
sShuppetPose46:
ax_pose 3, 0x01e8, 0x80f0, 0x9c00
ax_pose_terminator
sShuppetPose47:
ax_pose 4, 0x01e8, 0x80f0, 0x9c00
ax_pose_terminator
sShuppetPose48:
ax_pose 5, 0x01e8, 0x80f0, 0x9c00
ax_pose_terminator
sShuppetPose49:
ax_pose 0, 0x01e8, 0x80f4, 0x9c00
ax_pose_terminator
sShuppetPose50:
ax_pose 3, 0x01e9, 0x80f3, 0x9c00
ax_pose_terminator
sShuppetPose51:
ax_pose 6, 0x01e9, 0x80f2, 0x9c00
ax_pose_terminator
sShuppetPose52:
ax_pose 9, 0x01e8, 0x80f5, 0x9c00
ax_pose_terminator
sShuppetPose53:
ax_pose 12, 0x81e6, 0x80f9, 0x9c00
ax_pose_terminator
sShuppetPose54:
ax_pose 9, 0x01e8, 0x90ea, 0x9c00
ax_pose_terminator
sShuppetPose55:
ax_pose 6, 0x01e9, 0x90ed, 0x9c00
ax_pose_terminator
sShuppetPose56:
ax_pose 3, 0x01e9, 0x90ec, 0x9c00
ax_pose_terminator
sShuppetPose57:
ax_pose 0, 0x01e8, 0x80f4, 0x9c00
ax_pose_terminator
sShuppetPose58:
ax_pose 3, 0x01e8, 0x80f0, 0x9c00
ax_pose_terminator
sShuppetPose59:
ax_pose 6, 0x01e8, 0x80f0, 0x9c00
ax_pose_terminator
sShuppetPose60:
ax_pose 9, 0x01e6, 0x80f4, 0x9c00
ax_pose_terminator
sShuppetPose61:
ax_pose 15, 0x01e4, 0x80f8, 0x9c00
ax_pose_terminator
sShuppetPose62:
ax_pose 9, 0x01e6, 0x90eb, 0x9c00
ax_pose_terminator
sShuppetPose63:
ax_pose 6, 0x01e8, 0x90ef, 0x9c00
ax_pose_terminator
sShuppetPose64:
ax_pose 3, 0x01e8, 0x90ef, 0x9c00
ax_pose_terminator
sShuppetPose65:
ax_pose 0, 0x01e8, 0x80f4, 0x9c00
ax_pose_terminator
sShuppetPose66:
ax_pose 3, 0x01e9, 0x80f3, 0x9c00
ax_pose_terminator
sShuppetPose67:
ax_pose 6, 0x01e9, 0x80f2, 0x9c00
ax_pose_terminator
sShuppetPose68:
ax_pose 9, 0x01e8, 0x80f5, 0x9c00
ax_pose_terminator
sShuppetPose69:
ax_pose 12, 0x81e6, 0x80f9, 0x9c00
ax_pose_terminator
sShuppetPose70:
ax_pose 9, 0x01e8, 0x90ea, 0x9c00
ax_pose_terminator
sShuppetPose71:
ax_pose 6, 0x01e9, 0x90ed, 0x9c00
ax_pose_terminator
sShuppetPose72:
ax_pose 3, 0x01e9, 0x90ec, 0x9c00
ax_pose_terminator
sShuppetPose73:
ax_pose 0, 0x01e8, 0x80f4, 0x9c00
ax_pose_terminator
sShuppetPose74:
ax_pose 3, 0x01e8, 0x80f0, 0x9c00
ax_pose_terminator
sShuppetPose75:
ax_pose 6, 0x01e8, 0x80f0, 0x9c00
ax_pose_terminator
sShuppetPose76:
ax_pose 9, 0x01e6, 0x80f4, 0x9c00
ax_pose_terminator
sShuppetPose77:
ax_pose 15, 0x01e4, 0x80f8, 0x9c00
ax_pose_terminator
sShuppetPose78:
ax_pose 9, 0x01e6, 0x90eb, 0x9c00
ax_pose_terminator
sShuppetPose79:
ax_pose 6, 0x01e8, 0x90ef, 0x9c00
ax_pose_terminator
sShuppetPose80:
ax_pose 3, 0x01e8, 0x90ef, 0x9c00
ax_pose_terminator
sShuppetPose81:
ax_pose 0, 0x01e8, 0x80f4, 0x9c00
ax_pose_terminator
sShuppetPose82:
ax_pose 1, 0x01e8, 0x80f4, 0x9c00
ax_pose_terminator
sShuppetPose83:
ax_pose 2, 0x01e8, 0x80f4, 0x9c00
ax_pose_terminator
sShuppetPose84:
ax_pose 16, 0x01e8, 0x80ef, 0x9c00
ax_pose_terminator
sShuppetPose85:
ax_pose 17, 0x01f3, 0x00fe, 0x9c00
ax_pose -1, 0x01f3, 0x00f7, 0x9c00
ax_pose 16, 0x01e8, 0x80ef, 0x9c01
ax_pose_terminator
sShuppetPose86:
ax_pose 18, 0x01f3, 0x00fe, 0x9c00
ax_pose -1, 0x01f3, 0x00f7, 0x9c00
ax_pose 16, 0x01e8, 0x80ef, 0x9c01
ax_pose_terminator
sShuppetPose87:
ax_pose 19, 0x01ed, 0x40fa, 0x9c00
ax_pose -1, 0x01ed, 0x40f3, 0x9c00
ax_pose 16, 0x01e8, 0x80ef, 0x9c04
ax_pose_terminator
sShuppetPose88:
ax_pose 20, 0x01ed, 0x40fa, 0x9c00
ax_pose -1, 0x01ed, 0x40f3, 0x9c00
ax_pose 16, 0x01e8, 0x80ef, 0x9c04
ax_pose_terminator
sShuppetPose89:
ax_pose 19, 0x01ed, 0x40fa, 0x9c00
ax_pose -1, 0x01ed, 0x40f3, 0x9c00
ax_pose 16, 0x01e8, 0x80ef, 0x9c04
ax_pose_terminator
sShuppetPose90:
ax_pose 21, 0x01ed, 0x40fa, 0x9c00
ax_pose -1, 0x01ed, 0x40f3, 0x9c00
ax_pose 16, 0x01e8, 0x80ef, 0x9c04
ax_pose_terminator
sShuppetPose91:
ax_pose 22, 0x01f3, 0x00fe, 0x9c00
ax_pose -1, 0x01f3, 0x00f7, 0x9c00
ax_pose 16, 0x01e8, 0x80ef, 0x9c01
ax_pose_terminator
sShuppetPose92:
ax_pose 3, 0x01e8, 0x90ef, 0x9c00
ax_pose_terminator
sShuppetPose93:
ax_pose 4, 0x01e8, 0x90ef, 0x9c00
ax_pose_terminator
sShuppetPose94:
ax_pose 5, 0x01e8, 0x90ef, 0x9c00
ax_pose_terminator
sShuppetPose95:
ax_pose 23, 0x01e8, 0x90f0, 0x9c00
ax_pose_terminator
sShuppetPose96:
ax_pose 17, 0x01f2, 0x0104, 0x9c00
ax_pose -1, 0x01f3, 0x00fd, 0x9c00
ax_pose 23, 0x01e8, 0x90f0, 0x9c01
ax_pose_terminator
sShuppetPose97:
ax_pose 18, 0x01f2, 0x0105, 0x9c00
ax_pose -1, 0x01f3, 0x00fd, 0x9c00
ax_pose 23, 0x01e8, 0x90f0, 0x9c01
ax_pose_terminator
sShuppetPose98:
ax_pose 19, 0x01ec, 0x4101, 0x9c00
ax_pose -1, 0x01ed, 0x40f9, 0x9c00
ax_pose 23, 0x01e8, 0x90f0, 0x9c04
ax_pose_terminator
sShuppetPose99:
ax_pose 20, 0x01ec, 0x4101, 0x9c00
ax_pose -1, 0x01ed, 0x40f9, 0x9c00
ax_pose 23, 0x01e8, 0x90f0, 0x9c04
ax_pose_terminator
sShuppetPose100:
ax_pose 19, 0x01ec, 0x4101, 0x9c00
ax_pose -1, 0x01ed, 0x40f9, 0x9c00
ax_pose 23, 0x01e8, 0x90f0, 0x9c04
ax_pose_terminator
sShuppetPose101:
ax_pose 21, 0x01ec, 0x4101, 0x9c00
ax_pose -1, 0x01ed, 0x40f9, 0x9c00
ax_pose 23, 0x01e8, 0x90f0, 0x9c04
ax_pose_terminator
sShuppetPose102:
ax_pose 22, 0x01f2, 0x0105, 0x9c00
ax_pose -1, 0x01f3, 0x00fd, 0x9c00
ax_pose 23, 0x01e8, 0x90f0, 0x9c01
ax_pose_terminator
sShuppetPose103:
ax_pose 6, 0x01e8, 0x90ef, 0x9c00
ax_pose_terminator
sShuppetPose104:
ax_pose 7, 0x01e8, 0x90ef, 0x9c00
ax_pose_terminator
sShuppetPose105:
ax_pose 8, 0x01e8, 0x90ef, 0x9c00
ax_pose_terminator
sShuppetPose106:
ax_pose 24, 0x01e8, 0x90ef, 0x9c00
ax_pose_terminator
sShuppetPose107:
ax_pose 17, 0x01f3, 0x0102, 0x9c00
ax_pose 24, 0x01e8, 0x90ef, 0x9c01
ax_pose -1, 0x01f0, 0x0105, 0x9c00
ax_pose_terminator
sShuppetPose108:
ax_pose 18, 0x01f3, 0x0102, 0x9c00
ax_pose 24, 0x01e8, 0x90ef, 0x9c01
ax_pose -1, 0x01f0, 0x0106, 0x9c00
ax_pose_terminator
sShuppetPose109:
ax_pose 19, 0x01ed, 0x40fe, 0x9c00
ax_pose 24, 0x01e8, 0x90ef, 0x9c04
ax_pose -1, 0x01ea, 0x4102, 0x9c00
ax_pose_terminator
sShuppetPose110:
ax_pose 20, 0x01ed, 0x40fe, 0x9c00
ax_pose 24, 0x01e8, 0x90ef, 0x9c04
ax_pose -1, 0x01ea, 0x4102, 0x9c00
ax_pose_terminator
sShuppetPose111:
ax_pose 19, 0x01ed, 0x40fe, 0x9c00
ax_pose 24, 0x01e8, 0x90ef, 0x9c04
ax_pose -1, 0x01ea, 0x4102, 0x9c00
ax_pose_terminator
sShuppetPose112:
ax_pose 21, 0x01ed, 0x40fe, 0x9c00
ax_pose 24, 0x01e8, 0x90ef, 0x9c04
ax_pose -1, 0x01ea, 0x4102, 0x9c00
ax_pose_terminator
sShuppetPose113:
ax_pose 22, 0x01f3, 0x0102, 0x9c00
ax_pose 24, 0x01e8, 0x90ef, 0x9c01
ax_pose -1, 0x01f0, 0x0106, 0x9c00
ax_pose_terminator
sShuppetPose114:
ax_pose 9, 0x01e6, 0x90eb, 0x9c00
ax_pose_terminator
sShuppetPose115:
ax_pose 10, 0x01e6, 0x90eb, 0x9c00
ax_pose_terminator
sShuppetPose116:
ax_pose 11, 0x01e6, 0x90eb, 0x9c00
ax_pose_terminator
sShuppetPose117:
ax_pose 11, 0x01e6, 0x90eb, 0x9c00
ax_pose 17, 0x01ea, 0x00fb, 0x9c10
ax_pose -1, 0x01ee, 0x0103, 0x9c10
ax_pose_terminator
sShuppetPose118:
ax_pose 11, 0x01e6, 0x90eb, 0x9c00
ax_pose 18, 0x01ea, 0x00fb, 0x9c10
ax_pose -1, 0x01ee, 0x0104, 0x9c10
ax_pose_terminator
sShuppetPose119:
ax_pose 11, 0x01e6, 0x90eb, 0x9c00
ax_pose 19, 0x01e4, 0x40f7, 0x9c10
ax_pose -1, 0x01e8, 0x4100, 0x9c10
ax_pose_terminator
sShuppetPose120:
ax_pose 11, 0x01e6, 0x90eb, 0x9c00
ax_pose 20, 0x01e4, 0x40f7, 0x9c10
ax_pose -1, 0x01e8, 0x4100, 0x9c10
ax_pose_terminator
sShuppetPose121:
ax_pose 11, 0x01e6, 0x90eb, 0x9c00
ax_pose 19, 0x01e4, 0x40f7, 0x9c10
ax_pose -1, 0x01e8, 0x4100, 0x9c10
ax_pose_terminator
sShuppetPose122:
ax_pose 11, 0x01e6, 0x90eb, 0x9c00
ax_pose 21, 0x01e4, 0x40f7, 0x9c10
ax_pose -1, 0x01e8, 0x4100, 0x9c10
ax_pose_terminator
sShuppetPose123:
ax_pose 11, 0x01e6, 0x90eb, 0x9c00
ax_pose 22, 0x01ea, 0x00fb, 0x9c10
ax_pose -1, 0x01ee, 0x0104, 0x9c10
ax_pose_terminator
sShuppetPose124:
ax_pose 12, 0x81e4, 0x80f8, 0x9c00
ax_pose_terminator
sShuppetPose125:
ax_pose 13, 0x81e4, 0x80f8, 0x9c00
ax_pose_terminator
sShuppetPose126:
ax_pose 14, 0x81e4, 0x80f8, 0x9c00
ax_pose_terminator
sShuppetPose127:
ax_pose 14, 0x81e4, 0x80f8, 0x9c00
ax_pose 17, 0x01eb, 0x00f5, 0x9c08
ax_pose -1, 0x01eb, 0x0100, 0x9c08
ax_pose_terminator
sShuppetPose128:
ax_pose 14, 0x81e4, 0x80f8, 0x9c00
ax_pose 18, 0x01eb, 0x00f5, 0x9c08
ax_pose -1, 0x01eb, 0x0100, 0x9c08
ax_pose_terminator
sShuppetPose129:
ax_pose 14, 0x81e4, 0x80f8, 0x9c00
ax_pose 19, 0x01e7, 0x40f1, 0x9c08
ax_pose -1, 0x01e5, 0x40fc, 0x9c08
ax_pose_terminator
sShuppetPose130:
ax_pose 14, 0x81e4, 0x80f8, 0x9c00
ax_pose 20, 0x01e7, 0x40f1, 0x9c08
ax_pose -1, 0x01e5, 0x40fc, 0x9c08
ax_pose_terminator
sShuppetPose131:
ax_pose 14, 0x81e4, 0x80f8, 0x9c00
ax_pose 19, 0x01e7, 0x40f1, 0x9c08
ax_pose -1, 0x01e5, 0x40fc, 0x9c08
ax_pose_terminator
sShuppetPose132:
ax_pose 14, 0x81e4, 0x80f8, 0x9c00
ax_pose 21, 0x01e7, 0x40f1, 0x9c08
ax_pose -1, 0x01e5, 0x40fc, 0x9c08
ax_pose_terminator
sShuppetPose133:
ax_pose 14, 0x81e4, 0x80f8, 0x9c00
ax_pose 22, 0x01eb, 0x00f5, 0x9c08
ax_pose -1, 0x01eb, 0x0100, 0x9c08
ax_pose_terminator
sShuppetPose134:
ax_pose 9, 0x01e6, 0x80f4, 0x9c00
ax_pose_terminator
sShuppetPose135:
ax_pose 10, 0x01e6, 0x80f4, 0x9c00
ax_pose_terminator
sShuppetPose136:
ax_pose 11, 0x01e6, 0x80f4, 0x9c00
ax_pose_terminator
sShuppetPose137:
ax_pose 11, 0x01e6, 0x80f4, 0x9c00
ax_pose 17, 0x01ea, 0x10fc, 0x9c10
ax_pose -1, 0x01ee, 0x10f4, 0x9c10
ax_pose_terminator
sShuppetPose138:
ax_pose 11, 0x01e6, 0x80f4, 0x9c00
ax_pose 18, 0x01ea, 0x10fc, 0x9c10
ax_pose -1, 0x01ee, 0x10f3, 0x9c10
ax_pose_terminator
sShuppetPose139:
ax_pose 11, 0x01e6, 0x80f4, 0x9c00
ax_pose 19, 0x01e4, 0x50f8, 0x9c10
ax_pose -1, 0x01e8, 0x50ef, 0x9c10
ax_pose_terminator
sShuppetPose140:
ax_pose 11, 0x01e6, 0x80f4, 0x9c00
ax_pose 20, 0x01e4, 0x50f8, 0x9c10
ax_pose -1, 0x01e8, 0x50ef, 0x9c10
ax_pose_terminator
sShuppetPose141:
ax_pose 11, 0x01e6, 0x80f4, 0x9c00
ax_pose 19, 0x01e4, 0x50f8, 0x9c10
ax_pose -1, 0x01e8, 0x50ef, 0x9c10
ax_pose_terminator
sShuppetPose142:
ax_pose 11, 0x01e6, 0x80f4, 0x9c00
ax_pose 21, 0x01e4, 0x50f8, 0x9c10
ax_pose -1, 0x01e8, 0x50ef, 0x9c10
ax_pose_terminator
sShuppetPose143:
ax_pose 11, 0x01e6, 0x80f4, 0x9c00
ax_pose 22, 0x01ea, 0x10fc, 0x9c10
ax_pose -1, 0x01ee, 0x10f3, 0x9c10
ax_pose_terminator
sShuppetPose144:
ax_pose 6, 0x01e8, 0x80f0, 0x9c00
ax_pose_terminator
sShuppetPose145:
ax_pose 7, 0x01e8, 0x80f0, 0x9c00
ax_pose_terminator
sShuppetPose146:
ax_pose 8, 0x01e8, 0x80f0, 0x9c00
ax_pose_terminator
sShuppetPose147:
ax_pose 24, 0x01e8, 0x80f0, 0x9c00
ax_pose_terminator
sShuppetPose148:
ax_pose 17, 0x01f3, 0x10f5, 0x9c00
ax_pose 24, 0x01e8, 0x80f0, 0x9c01
ax_pose -1, 0x01f0, 0x10f2, 0x9c00
ax_pose_terminator
sShuppetPose149:
ax_pose 18, 0x01f3, 0x10f5, 0x9c00
ax_pose 24, 0x01e8, 0x80f0, 0x9c01
ax_pose -1, 0x01f0, 0x10f1, 0x9c00
ax_pose_terminator
sShuppetPose150:
ax_pose 19, 0x01ed, 0x50f1, 0x9c00
ax_pose 24, 0x01e8, 0x80f0, 0x9c04
ax_pose -1, 0x01ea, 0x50ed, 0x9c00
ax_pose_terminator
sShuppetPose151:
ax_pose 20, 0x01ed, 0x50f1, 0x9c00
ax_pose 24, 0x01e8, 0x80f0, 0x9c04
ax_pose -1, 0x01ea, 0x50ed, 0x9c00
ax_pose_terminator
sShuppetPose152:
ax_pose 19, 0x01ed, 0x50f1, 0x9c00
ax_pose 24, 0x01e8, 0x80f0, 0x9c04
ax_pose -1, 0x01ea, 0x50ed, 0x9c00
ax_pose_terminator
sShuppetPose153:
ax_pose 21, 0x01ed, 0x50f1, 0x9c00
ax_pose 24, 0x01e8, 0x80f0, 0x9c04
ax_pose -1, 0x01ea, 0x50ed, 0x9c00
ax_pose_terminator
sShuppetPose154:
ax_pose 22, 0x01f3, 0x10f5, 0x9c00
ax_pose 24, 0x01e8, 0x80f0, 0x9c01
ax_pose -1, 0x01f0, 0x10f1, 0x9c00
ax_pose_terminator
sShuppetPose155:
ax_pose 3, 0x01e8, 0x80f0, 0x9c00
ax_pose_terminator
sShuppetPose156:
ax_pose 4, 0x01e8, 0x80f0, 0x9c00
ax_pose_terminator
sShuppetPose157:
ax_pose 5, 0x01e8, 0x80f0, 0x9c00
ax_pose_terminator
sShuppetPose158:
ax_pose 23, 0x01e8, 0x80ef, 0x9c00
ax_pose_terminator
sShuppetPose159:
ax_pose 17, 0x01f2, 0x10f3, 0x9c00
ax_pose -1, 0x01f3, 0x10fa, 0x9c00
ax_pose 23, 0x01e8, 0x80ef, 0x9c01
ax_pose_terminator
sShuppetPose160:
ax_pose 18, 0x01f2, 0x10f2, 0x9c00
ax_pose -1, 0x01f3, 0x10fa, 0x9c00
ax_pose 23, 0x01e8, 0x80ef, 0x9c01
ax_pose_terminator
sShuppetPose161:
ax_pose 19, 0x01ec, 0x50ee, 0x9c00
ax_pose -1, 0x01ed, 0x50f6, 0x9c00
ax_pose 23, 0x01e8, 0x80ef, 0x9c04
ax_pose_terminator
sShuppetPose162:
ax_pose 20, 0x01ec, 0x50ee, 0x9c00
ax_pose -1, 0x01ed, 0x50f6, 0x9c00
ax_pose 23, 0x01e8, 0x80ef, 0x9c04
ax_pose_terminator
sShuppetPose163:
ax_pose 19, 0x01ec, 0x50ee, 0x9c00
ax_pose -1, 0x01ed, 0x50f6, 0x9c00
ax_pose 23, 0x01e8, 0x80ef, 0x9c04
ax_pose_terminator
sShuppetPose164:
ax_pose 21, 0x01ec, 0x50ee, 0x9c00
ax_pose -1, 0x01ed, 0x50f6, 0x9c00
ax_pose 23, 0x01e8, 0x80ef, 0x9c04
ax_pose_terminator
sShuppetPose165:
ax_pose 22, 0x01f2, 0x10f2, 0x9c00
ax_pose -1, 0x01f3, 0x10fa, 0x9c00
ax_pose 23, 0x01e8, 0x80ef, 0x9c01
ax_pose_terminator
sShuppetPose166:
ax_pose 25, 0x81e8, 0x80f8, 0x9c00
ax_pose_terminator
sShuppetPose167:
ax_pose 26, 0x81e8, 0x80f8, 0x9c00
ax_pose_terminator
sShuppetPose168:
ax_pose 27, 0x01e3, 0x80f2, 0x9c00
ax_pose_terminator
sShuppetPose169:
ax_pose 28, 0x01e2, 0x90ef, 0x9c00
ax_pose_terminator
sShuppetPose170:
ax_pose 29, 0x01e5, 0x90ef, 0x9c00
ax_pose_terminator
sShuppetPose171:
ax_pose 30, 0x01e2, 0x90ed, 0x9c00
ax_pose_terminator
sShuppetPose172:
ax_pose 31, 0x01e1, 0x80f2, 0x9c00
ax_pose_terminator
sShuppetPose173:
ax_pose 30, 0x01e2, 0x80f3, 0x9c00
ax_pose_terminator
sShuppetPose174:
ax_pose 29, 0x01e5, 0x80f1, 0x9c00
ax_pose_terminator
sShuppetPose175:
ax_pose 28, 0x01e2, 0x80f1, 0x9c00
ax_pose_terminator
sShuppetPose176:
ax_pose 0, 0x01e8, 0x80f4, 0x9c00
ax_pose_terminator
sShuppetPose177:
ax_pose 1, 0x01e8, 0x80f4, 0x9c00
ax_pose_terminator
sShuppetPose178:
ax_pose 2, 0x01e8, 0x80f4, 0x9c00
ax_pose_terminator
sShuppetPose179:
ax_pose 3, 0x01e8, 0x90ef, 0x9c00
ax_pose_terminator
sShuppetPose180:
ax_pose 4, 0x01e8, 0x90ef, 0x9c00
ax_pose_terminator
sShuppetPose181:
ax_pose 5, 0x01e8, 0x90ef, 0x9c00
ax_pose_terminator
sShuppetPose182:
ax_pose 6, 0x01e8, 0x90ef, 0x9c00
ax_pose_terminator
sShuppetPose183:
ax_pose 7, 0x01e8, 0x90ef, 0x9c00
ax_pose_terminator
sShuppetPose184:
ax_pose 8, 0x01e8, 0x90ef, 0x9c00
ax_pose_terminator
sShuppetPose185:
ax_pose 9, 0x01e6, 0x90eb, 0x9c00
ax_pose_terminator
sShuppetPose186:
ax_pose 10, 0x01e6, 0x90eb, 0x9c00
ax_pose_terminator
sShuppetPose187:
ax_pose 11, 0x01e6, 0x90eb, 0x9c00
ax_pose_terminator
sShuppetPose188:
ax_pose 12, 0x81e4, 0x80f8, 0x9c00
ax_pose_terminator
sShuppetPose189:
ax_pose 13, 0x81e4, 0x80f8, 0x9c00
ax_pose_terminator
sShuppetPose190:
ax_pose 14, 0x81e4, 0x80f8, 0x9c00
ax_pose_terminator
sShuppetPose191:
ax_pose 9, 0x01e6, 0x80f4, 0x9c00
ax_pose_terminator
sShuppetPose192:
ax_pose 10, 0x01e6, 0x80f4, 0x9c00
ax_pose_terminator
sShuppetPose193:
ax_pose 11, 0x01e6, 0x80f4, 0x9c00
ax_pose_terminator
sShuppetPose194:
ax_pose 6, 0x01e8, 0x80f0, 0x9c00
ax_pose_terminator
sShuppetPose195:
ax_pose 7, 0x01e8, 0x80f0, 0x9c00
ax_pose_terminator
sShuppetPose196:
ax_pose 8, 0x01e8, 0x80f0, 0x9c00
ax_pose_terminator
sShuppetPose197:
ax_pose 3, 0x01e8, 0x80f0, 0x9c00
ax_pose_terminator
sShuppetPose198:
ax_pose 4, 0x01e8, 0x80f0, 0x9c00
ax_pose_terminator
sShuppetPose199:
ax_pose 5, 0x01e8, 0x80f0, 0x9c00
ax_pose_terminator
sShuppetPose200:
ax_pose 0, 0x01e8, 0x80f4, 0x9c00
ax_pose_terminator
sShuppetPose201:
ax_pose 3, 0x01e9, 0x80f3, 0x9c00
ax_pose_terminator
sShuppetPose202:
ax_pose 6, 0x01e9, 0x80f2, 0x9c00
ax_pose_terminator
sShuppetPose203:
ax_pose 9, 0x01e8, 0x80f5, 0x9c00
ax_pose_terminator
sShuppetPose204:
ax_pose 12, 0x81e6, 0x80f9, 0x9c00
ax_pose_terminator
sShuppetPose205:
ax_pose 9, 0x01e8, 0x90ea, 0x9c00
ax_pose_terminator
sShuppetPose206:
ax_pose 6, 0x01e9, 0x90ed, 0x9c00
ax_pose_terminator
sShuppetPose207:
ax_pose 3, 0x01e9, 0x90ec, 0x9c00
ax_pose_terminator
sShuppetPose208:
ax_pose 0, 0x01e8, 0x80f4, 0x9c00
ax_pose_terminator
sShuppetPose209:
ax_pose 3, 0x01e8, 0x80f0, 0x9c00
ax_pose_terminator
sShuppetPose210:
ax_pose 6, 0x01e8, 0x80f0, 0x9c00
ax_pose_terminator
sShuppetPose211:
ax_pose 9, 0x01e6, 0x80f4, 0x9c00
ax_pose_terminator
sShuppetPose212:
ax_pose 15, 0x01e4, 0x80f8, 0x9c00
ax_pose_terminator
sShuppetPose213:
ax_pose 9, 0x01e6, 0x90eb, 0x9c00
ax_pose_terminator
sShuppetPose214:
ax_pose 6, 0x01e8, 0x90ef, 0x9c00
ax_pose_terminator
sShuppetPose215:
ax_pose 3, 0x01e8, 0x90ef, 0x9c00
ax_pose_terminator
sShuppetPose216:
ax_pose 0, 0x01e8, 0x80f4, 0x9c00
ax_pose_terminator
sShuppetPose217:
ax_pose 3, 0x01e9, 0x90ec, 0x9c00
ax_pose_terminator
sShuppetPose218:
ax_pose 6, 0x01e9, 0x90ed, 0x9c00
ax_pose_terminator
sShuppetPose219:
ax_pose 9, 0x01e8, 0x90ea, 0x9c00
ax_pose_terminator
sShuppetPose220:
ax_pose 12, 0x81e6, 0x80f9, 0x9c00
ax_pose_terminator
sShuppetPose221:
ax_pose 9, 0x01e8, 0x80f5, 0x9c00
ax_pose_terminator
sShuppetPose222:
ax_pose 6, 0x01e9, 0x80f2, 0x9c00
ax_pose_terminator
sShuppetPose223:
ax_pose 3, 0x01e9, 0x80f3, 0x9c00
ax_pose_terminator
sShuppetPose224:
ax_pose 0, 0x01e8, 0x80f4, 0x9c00
ax_pose_terminator
sShuppetPose225:
ax_pose 1, 0x01e8, 0x80f4, 0x9c00
ax_pose_terminator
sShuppetPose226:
ax_pose 2, 0x01e8, 0x80f4, 0x9c00
ax_pose_terminator
sShuppetPose227:
ax_pose 3, 0x01e8, 0x90ed, 0x9c00
ax_pose_terminator
sShuppetPose228:
ax_pose 4, 0x01e8, 0x90ed, 0x9c00
ax_pose_terminator
sShuppetPose229:
ax_pose 5, 0x01e8, 0x90ed, 0x9c00
ax_pose_terminator
sShuppetPose230:
ax_pose 6, 0x01e8, 0x90ed, 0x9c00
ax_pose_terminator
sShuppetPose231:
ax_pose 7, 0x01e8, 0x90ed, 0x9c00
ax_pose_terminator
sShuppetPose232:
ax_pose 8, 0x01e8, 0x90ed, 0x9c00
ax_pose_terminator
sShuppetPose233:
ax_pose 9, 0x01e6, 0x90ea, 0x9c00
ax_pose_terminator
sShuppetPose234:
ax_pose 10, 0x01e6, 0x90ea, 0x9c00
ax_pose_terminator
sShuppetPose235:
ax_pose 11, 0x01e6, 0x90ea, 0x9c00
ax_pose_terminator
sShuppetPose236:
ax_pose 12, 0x81e4, 0x80f8, 0x9c00
ax_pose_terminator
sShuppetPose237:
ax_pose 13, 0x81e4, 0x80f8, 0x9c00
ax_pose_terminator
sShuppetPose238:
ax_pose 14, 0x81e4, 0x80f8, 0x9c00
ax_pose_terminator
sShuppetPose239:
ax_pose 9, 0x01e6, 0x80f5, 0x9c00
ax_pose_terminator
sShuppetPose240:
ax_pose 10, 0x01e6, 0x80f5, 0x9c00
ax_pose_terminator
sShuppetPose241:
ax_pose 11, 0x01e6, 0x80f5, 0x9c00
ax_pose_terminator
sShuppetPose242:
ax_pose 6, 0x01e8, 0x80f2, 0x9c00
ax_pose_terminator
sShuppetPose243:
ax_pose 7, 0x01e8, 0x80f2, 0x9c00
ax_pose_terminator
sShuppetPose244:
ax_pose 8, 0x01e8, 0x80f2, 0x9c00
ax_pose_terminator
sShuppetPose245:
ax_pose 3, 0x01e8, 0x80f2, 0x9c00
ax_pose_terminator
sShuppetPose246:
ax_pose 4, 0x01e8, 0x80f2, 0x9c00
ax_pose_terminator
sShuppetPose247:
ax_pose 5, 0x01e8, 0x80f2, 0x9c00
ax_pose_terminator
sShuppetPose248:
ax_pose 0, 0x01e8, 0x80f4, 0x9c00
ax_pose_terminator
sShuppetPose249:
ax_pose 3, 0x01e9, 0x80f3, 0x9c00
ax_pose_terminator
sShuppetPose250:
ax_pose 6, 0x01e9, 0x80f2, 0x9c00
ax_pose_terminator
sShuppetPose251:
ax_pose 9, 0x01e8, 0x80f5, 0x9c00
ax_pose_terminator
sShuppetPose252:
ax_pose 12, 0x81e6, 0x80f9, 0x9c00
ax_pose_terminator
sShuppetPose253:
ax_pose 9, 0x01e8, 0x90ea, 0x9c00
ax_pose_terminator
sShuppetPose254:
ax_pose 6, 0x01e9, 0x90ed, 0x9c00
ax_pose_terminator
sShuppetPose255:
ax_pose 3, 0x01e9, 0x90ec, 0x9c00
ax_pose_terminator
sShuppetPose256:
ax_pose 0, 0x01e8, 0x80f4, 0x9c00
ax_pose_terminator
sShuppetPose257:
ax_pose 3, 0x01e8, 0x80f0, 0x9c00
ax_pose_terminator
sShuppetPose258:
ax_pose 6, 0x01e8, 0x80f0, 0x9c00
ax_pose_terminator
sShuppetPose259:
ax_pose 9, 0x01e6, 0x80f4, 0x9c00
ax_pose_terminator
sShuppetPose260:
ax_pose 15, 0x01e4, 0x80f8, 0x9c00
ax_pose_terminator
sShuppetPose261:
ax_pose 9, 0x01e6, 0x90eb, 0x9c00
ax_pose_terminator
sShuppetPose262:
ax_pose 6, 0x01e8, 0x90ef, 0x9c00
ax_pose_terminator
sShuppetPose263:
ax_pose 3, 0x01e8, 0x90ef, 0x9c00
ax_pose_terminator
sShuppetPose264:
ax_pose 0, 0x01e8, 0x80f4, 0x9c00
ax_pose_terminator
sShuppetPose265:
ax_pose 3, 0x01e8, 0x80f0, 0x9c00
ax_pose_terminator
sShuppetPose266:
ax_pose 6, 0x01e8, 0x80f0, 0x9c00
ax_pose_terminator
sShuppetPose267:
ax_pose 9, 0x01e6, 0x80f4, 0x9c00
ax_pose_terminator
sShuppetPose268:
ax_pose 12, 0x81e4, 0x80f8, 0x9c00
ax_pose_terminator
sShuppetPose269:
ax_pose 9, 0x01e6, 0x90eb, 0x9c00
ax_pose_terminator
sShuppetPose270:
ax_pose 6, 0x01e8, 0x90ef, 0x9c00
ax_pose_terminator
sShuppetPose271:
ax_pose 3, 0x01e8, 0x90ef, 0x9c00
ax_pose_terminator
sShuppetPose272:
ax_pose 0, 0x01e8, 0x80f4, 0x9c00
ax_pose_terminator
sShuppetPose273:
ax_pose 3, 0x01e8, 0x80f0, 0x9c00
ax_pose_terminator
sShuppetPose274:
ax_pose 6, 0x01e8, 0x80f0, 0x9c00
ax_pose_terminator
sShuppetPose275:
ax_pose 9, 0x01e6, 0x80f4, 0x9c00
ax_pose_terminator
sShuppetPose276:
ax_pose 15, 0x01e4, 0x80f8, 0x9c00
ax_pose_terminator
sShuppetPose277:
ax_pose 9, 0x01e6, 0x90eb, 0x9c00
ax_pose_terminator
sShuppetPose278:
ax_pose 6, 0x01e8, 0x90ef, 0x9c00
ax_pose_terminator
sShuppetPose279:
ax_pose 3, 0x01e8, 0x90ef, 0x9c00
ax_pose_terminator
.align 2
sShuppetAnims_1_1:
ax_anim 6, 0, 0, 0, 0, 0, 0,
ax_anim 6, 0, 1, 0, -1, 0, 0,
ax_anim 6, 0, 2, 0, -2, 0, 0,
ax_anim 6, 0, 0, 0, -3, 0, 0,
ax_anim 6, 0, 1, 0, -2, 0, 0,
ax_anim 6, 0, 2, 0, -1, 0, 0,
ax_anim_terminator
sShuppetAnims_1_2:
ax_anim 6, 0, 3, 0, 0, 0, 0,
ax_anim 6, 0, 4, 0, -1, 0, 0,
ax_anim 6, 0, 5, 0, -2, 0, 0,
ax_anim 6, 0, 3, 0, -3, 0, 0,
ax_anim 6, 0, 4, 0, -2, 0, 0,
ax_anim 6, 0, 5, 0, -1, 0, 0,
ax_anim_terminator
sShuppetAnims_1_3:
ax_anim 6, 0, 6, 0, 0, 0, 0,
ax_anim 6, 0, 7, 0, -1, 0, 0,
ax_anim 6, 0, 8, 0, -2, 0, 0,
ax_anim 6, 0, 6, 0, -3, 0, 0,
ax_anim 6, 0, 7, 0, -2, 0, 0,
ax_anim 6, 0, 8, 0, -1, 0, 0,
ax_anim_terminator
sShuppetAnims_1_4:
ax_anim 6, 0, 9, 0, 0, 0, 0,
ax_anim 6, 0, 10, 0, -1, 0, 0,
ax_anim 6, 0, 11, 0, -2, 0, 0,
ax_anim 6, 0, 9, 0, -3, 0, 0,
ax_anim 6, 0, 10, 0, -2, 0, 0,
ax_anim 6, 0, 11, 0, -1, 0, 0,
ax_anim_terminator
sShuppetAnims_1_5:
ax_anim 6, 0, 12, 0, 0, 0, 0,
ax_anim 6, 0, 13, 0, -1, 0, 0,
ax_anim 6, 0, 14, 0, -2, 0, 0,
ax_anim 6, 0, 12, 0, -3, 0, 0,
ax_anim 6, 0, 13, 0, -2, 0, 0,
ax_anim 6, 0, 14, 0, -1, 0, 0,
ax_anim_terminator
sShuppetAnims_1_6:
ax_anim 6, 0, 15, 0, 0, 0, 0,
ax_anim 6, 0, 16, 0, -1, 0, 0,
ax_anim 6, 0, 17, 0, -2, 0, 0,
ax_anim 6, 0, 15, 0, -3, 0, 0,
ax_anim 6, 0, 16, 0, -2, 0, 0,
ax_anim 6, 0, 17, 0, -1, 0, 0,
ax_anim_terminator
sShuppetAnims_1_7:
ax_anim 6, 0, 18, 0, 0, 0, 0,
ax_anim 6, 0, 19, 0, -1, 0, 0,
ax_anim 6, 0, 20, 0, -2, 0, 0,
ax_anim 6, 0, 18, 0, -3, 0, 0,
ax_anim 6, 0, 19, 0, -2, 0, 0,
ax_anim 6, 0, 20, 0, -1, 0, 0,
ax_anim_terminator
sShuppetAnims_1_8:
ax_anim 6, 0, 21, 0, 0, 0, 0,
ax_anim 6, 0, 22, 0, -1, 0, 0,
ax_anim 6, 0, 23, 0, -2, 0, 0,
ax_anim 6, 0, 21, 0, -3, 0, 0,
ax_anim 6, 0, 22, 0, -2, 0, 0,
ax_anim 6, 0, 23, 0, -1, 0, 0,
ax_anim_terminator
.align 2
sShuppetAnims_2_1:
ax_anim 3, 0, 24, 0, -1, 0, -1,
ax_anim 3, 0, 25, 0, -2, 0, -2,
ax_anim 3, 0, 26, 0, -2, 0, -2,
ax_anim 3, 0, 24, 0, -2, 0, -2,
ax_anim 3, 0, 25, 0, -2, 0, -2,
ax_anim 1, 0, 26, 0, 0, 0, 0,
ax_anim 1, 2, 24, 0, 4, 0, 4,
ax_anim 1, 0, 25, 0, 10, 0, 10,
ax_anim 2, 0, 26, 0, 22, 0, 20,
ax_anim 2, 1, 24, 1, 22, 1, 20,
ax_anim 2, 0, 25, 0, 22, 0, 20,
ax_anim 2, 0, 26, 1, 22, 1, 20,
ax_anim 2, 0, 24, 0, 6, 0, 6,
ax_anim_terminator
sShuppetAnims_2_2:
ax_anim 3, 0, 27, -1, -1, -1, -1,
ax_anim 3, 0, 28, -2, -2, -2, -2,
ax_anim 3, 0, 29, -2, -2, -2, -2,
ax_anim 3, 0, 27, -2, -2, -2, -2,
ax_anim 3, 0, 28, -2, -2, -2, -2,
ax_anim 1, 0, 29, 0, 0, 0, 0,
ax_anim 1, 2, 27, 4, 4, 4, 4,
ax_anim 1, 0, 28, 10, 10, 10, 10,
ax_anim 2, 0, 29, 20, 24, 21, 22,
ax_anim 2, 1, 27, 21, 23, 22, 21,
ax_anim 2, 0, 28, 20, 24, 21, 22,
ax_anim 2, 0, 29, 21, 23, 22, 21,
ax_anim 2, 0, 27, 6, 6, 6, 6,
ax_anim_terminator
sShuppetAnims_2_3:
ax_anim 3, 0, 30, -1, 0, -1, 0,
ax_anim 3, 0, 31, -2, 0, -2, 0,
ax_anim 3, 0, 32, -2, 0, -2, 0,
ax_anim 3, 0, 30, -2, 0, -2, 0,
ax_anim 3, 0, 31, -2, 0, -2, 0,
ax_anim 1, 0, 32, 0, 0, 0, 0,
ax_anim 1, 2, 30, 4, 1, 4, 0,
ax_anim 1, 0, 31, 10, 2, 10, 0,
ax_anim 2, 0, 32, 20, 2, 20, 0,
ax_anim 2, 1, 30, 20, 3, 20, 1,
ax_anim 2, 0, 31, 20, 2, 20, 0,
ax_anim 2, 0, 32, 20, 3, 20, 1,
ax_anim 2, 0, 30, 6, 1, 6, 0,
ax_anim_terminator
sShuppetAnims_2_4:
ax_anim 3, 0, 33, -1, 1, -1, 1,
ax_anim 3, 0, 34, -2, 2, -2, 2,
ax_anim 3, 0, 35, -2, 2, -2, 2,
ax_anim 3, 0, 33, -2, 2, -2, 2,
ax_anim 3, 0, 34, -2, 2, -2, 2,
ax_anim 1, 0, 35, 0, -1, 0, -1,
ax_anim 1, 2, 33, 5, -5, 5, -5,
ax_anim 1, 0, 34, 13, -11, 13, -12,
ax_anim 2, 0, 35, 21, -16, 21, -19,
ax_anim 2, 1, 33, 20, -17, 20, -20,
ax_anim 2, 0, 34, 21, -16, 21, -19,
ax_anim 2, 0, 35, 20, -17, 20, -20,
ax_anim 2, 0, 33, 6, -6, 6, -6,
ax_anim_terminator
sShuppetAnims_2_5:
ax_anim 3, 0, 36, 0, 1, 0, 1,
ax_anim 3, 0, 37, 0, 2, 0, 2,
ax_anim 3, 0, 38, 0, 2, 0, 2,
ax_anim 3, 0, 36, 0, 2, 0, 2,
ax_anim 3, 0, 37, 0, 2, 0, 2,
ax_anim 1, 0, 38, 0, 0, 0, 0,
ax_anim 1, 2, 36, 0, -4, 0, -5,
ax_anim 1, 0, 37, 0, -9, 0, -11,
ax_anim 2, 0, 38, 0, -17, 0, -21,
ax_anim 2, 1, 36, 1, -17, 1, -21,
ax_anim 2, 0, 37, 0, -17, 0, -21,
ax_anim 2, 0, 38, 1, -17, 1, -21,
ax_anim 2, 0, 36, 0, -6, 0, -6,
ax_anim_terminator
sShuppetAnims_2_6:
ax_anim 3, 0, 39, 1, 1, 1, 1,
ax_anim 3, 0, 40, 2, 2, 2, 2,
ax_anim 3, 0, 41, 2, 2, 2, 2,
ax_anim 3, 0, 39, 2, 2, 2, 2,
ax_anim 3, 0, 40, 2, 2, 2, 2,
ax_anim 1, 0, 41, 0, -1, 0, -1,
ax_anim 1, 2, 39, -5, -5, -5, -5,
ax_anim 1, 0, 40, -13, -11, -13, -12,
ax_anim 2, 0, 41, -21, -16, -21, -19,
ax_anim 2, 1, 39, -20, -17, -20, -20,
ax_anim 2, 0, 40, -21, -16, -21, -19,
ax_anim 2, 0, 41, -20, -17, -20, -20,
ax_anim 2, 0, 39, -6, -6, -6, -6,
ax_anim_terminator
sShuppetAnims_2_7:
ax_anim 3, 0, 42, 1, 0, 1, 0,
ax_anim 3, 0, 43, 2, 0, 2, 0,
ax_anim 3, 0, 44, 2, 0, 2, 0,
ax_anim 3, 0, 42, 2, 0, 2, 0,
ax_anim 3, 0, 43, 2, 0, 2, 0,
ax_anim 1, 0, 44, 0, 0, 0, 0,
ax_anim 1, 2, 42, -4, 1, -4, 0,
ax_anim 1, 0, 43, -10, 2, -10, 0,
ax_anim 2, 0, 44, -20, 2, -20, 0,
ax_anim 2, 1, 42, -20, 3, -20, 1,
ax_anim 2, 0, 43, -20, 2, -20, 0,
ax_anim 2, 0, 44, -20, 3, -20, 1,
ax_anim 2, 0, 42, -6, 1, -6, 0,
ax_anim_terminator
sShuppetAnims_2_8:
ax_anim 3, 0, 45, 1, -1, 1, -1,
ax_anim 3, 0, 46, 2, -2, 2, -2,
ax_anim 3, 0, 47, 2, -2, 2, -2,
ax_anim 3, 0, 45, 2, -2, 2, -2,
ax_anim 3, 0, 46, 2, -2, 2, -2,
ax_anim 1, 0, 47, 0, 0, 0, 0,
ax_anim 1, 2, 45, -4, 4, -4, 4,
ax_anim 1, 0, 46, -10, 10, -10, 10,
ax_anim 2, 0, 47, -20, 24, -21, 22,
ax_anim 2, 1, 45, -21, 23, -22, 21,
ax_anim 2, 0, 46, -20, 24, -21, 22,
ax_anim 2, 0, 47, -21, 23, -22, 21,
ax_anim 2, 0, 45, -6, 6, -6, 6,
ax_anim_terminator
.align 2
sShuppetAnims_3_1:
ax_anim 1, 0, 48, 0, -1, 0, -1,
ax_anim 1, 0, 48, 0, -2, 0, -2,
ax_anim 2, 0, 48, 0, -3, 0, -3,
ax_anim 2, 0, 49, 0, -3, 0, -3,
ax_anim 2, 0, 50, 0, -3, 0, -3,
ax_anim 2, 0, 51, 0, -3, 0, -3,
ax_anim 2, 2, 52, 0, -3, 0, -3,
ax_anim 1, 0, 53, 0, 0, 0, 0,
ax_anim 1, 0, 54, 0, 7, 0, 7,
ax_anim 2, 0, 55, 0, 13, 0, 13,
ax_anim 1, 1, 48, 0, 23, 0, 23,
ax_anim 1, 0, 49, 0, 23, 0, 23,
ax_anim 1, 0, 50, 1, 23, 1, 23,
ax_anim 1, 0, 51, 1, 23, 1, 23,
ax_anim 1, 0, 52, 0, 23, 0, 23,
ax_anim 1, 0, 53, 0, 23, 0, 23,
ax_anim 1, 0, 54, 1, 23, 1, 23,
ax_anim 1, 0, 55, 1, 23, 1, 23,
ax_anim 2, 0, 48, 0, 10, 0, 10,
ax_anim 2, 0, 48, 0, 4, 0, 4,
ax_anim_terminator
sShuppetAnims_3_2:
ax_anim 1, 0, 55, -1, -1, -1, -1,
ax_anim 1, 0, 55, -2, -2, -2, -2,
ax_anim 2, 0, 55, -3, -3, -3, -3,
ax_anim 2, 0, 48, -3, -3, -3, -3,
ax_anim 2, 0, 49, -3, -3, -3, -3,
ax_anim 2, 0, 50, -3, -3, -3, -3,
ax_anim 2, 2, 51, -3, -3, -3, -3,
ax_anim 1, 0, 52, 0, 0, 0, 0,
ax_anim 1, 0, 53, 7, 7, 7, 7,
ax_anim 2, 0, 54, 13, 13, 13, 13,
ax_anim 1, 1, 55, 21, 23, 21, 23,
ax_anim 1, 0, 48, 21, 23, 21, 23,
ax_anim 1, 0, 49, 20, 24, 20, 24,
ax_anim 1, 0, 50, 20, 24, 20, 24,
ax_anim 1, 0, 51, 21, 23, 21, 23,
ax_anim 1, 0, 52, 21, 23, 21, 23,
ax_anim 1, 0, 53, 20, 24, 20, 24,
ax_anim 1, 0, 48, 20, 24, 20, 24,
ax_anim 2, 0, 55, 10, 10, 10, 10,
ax_anim 2, 0, 55, 4, 4, 4, 4,
ax_anim_terminator
sShuppetAnims_3_3:
ax_anim 1, 0, 54, -1, 0, -1, 0,
ax_anim 1, 0, 54, -2, 0, -2, 0,
ax_anim 2, 0, 54, -3, 0, -3, 0,
ax_anim 2, 0, 55, -3, 0, -3, 0,
ax_anim 2, 0, 48, -3, 0, -3, 0,
ax_anim 2, 0, 49, -3, 0, -3, 0,
ax_anim 2, 2, 50, -3, 0, -3, 0,
ax_anim 1, 0, 51, 0, 0, 0, 0,
ax_anim 1, 0, 52, 7, 0, 7, 0,
ax_anim 2, 0, 53, 13, 0, 13, 0,
ax_anim 1, 1, 54, 20, 0, 20, 0,
ax_anim 1, 0, 55, 20, 0, 20, 0,
ax_anim 1, 0, 48, 20, 1, 20, 1,
ax_anim 1, 0, 49, 20, 1, 20, 1,
ax_anim 1, 0, 50, 20, 0, 20, 0,
ax_anim 1, 0, 51, 20, 0, 20, 0,
ax_anim 1, 0, 52, 20, 1, 20, 1,
ax_anim 1, 0, 53, 20, 1, 20, 1,
ax_anim 2, 0, 54, 10, 0, 10, 0,
ax_anim 2, 0, 54, 4, 0, 4, 0,
ax_anim_terminator
sShuppetAnims_3_4:
ax_anim 1, 0, 53, -1, 1, -1, 1,
ax_anim 1, 0, 53, -2, 2, -2, 2,
ax_anim 2, 0, 53, -3, 3, -3, 3,
ax_anim 2, 0, 54, -3, 3, -3, 3,
ax_anim 2, 0, 55, -3, 3, -3, 3,
ax_anim 2, 0, 48, -3, 3, -3, 3,
ax_anim 2, 2, 49, -3, 3, -3, 3,
ax_anim 1, 0, 50, 0, 0, 0, 0,
ax_anim 1, 0, 51, 8, -6, 8, -6,
ax_anim 2, 0, 52, 14, -11, 14, -11,
ax_anim 1, 1, 53, 21, -17, 21, -17,
ax_anim 1, 0, 54, 21, -17, 21, -17,
ax_anim 1, 0, 55, 20, -18, 20, -18,
ax_anim 1, 0, 48, 20, -18, 20, -18,
ax_anim 1, 0, 49, 21, -17, 21, -17,
ax_anim 1, 0, 50, 21, -17, 21, -17,
ax_anim 1, 0, 51, 20, -18, 20, -18,
ax_anim 1, 0, 52, 20, -18, 20, -18,
ax_anim 2, 0, 53, 11, -9, 11, -9,
ax_anim 2, 0, 53, 5, -3, 5, -3,
ax_anim_terminator
sShuppetAnims_3_5:
ax_anim 1, 0, 52, 0, 1, 0, 1,
ax_anim 1, 0, 52, 0, 2, 0, 2,
ax_anim 2, 0, 52, 0, 3, 0, 3,
ax_anim 2, 0, 53, 0, 3, 0, 3,
ax_anim 2, 0, 54, 0, 3, 0, 3,
ax_anim 2, 0, 55, 0, 3, 0, 3,
ax_anim 2, 2, 48, 0, 3, 0, 3,
ax_anim 1, 0, 49, 0, 0, 0, 0,
ax_anim 1, 0, 50, 0, -6, 0, -6,
ax_anim 2, 0, 51, 0, -11, 0, -11,
ax_anim 1, 1, 52, 0, -17, 0, -17,
ax_anim 1, 0, 53, 0, -17, 0, -17,
ax_anim 1, 0, 54, 1, -17, 1, -17,
ax_anim 1, 0, 55, 1, -17, 1, -17,
ax_anim 1, 0, 48, 0, -17, 0, -17,
ax_anim 1, 0, 49, 0, -17, 0, -17,
ax_anim 1, 0, 50, 1, -17, 1, -17,
ax_anim 1, 0, 51, 1, -17, 1, -17,
ax_anim 2, 0, 52, 0, -9, 0, -9,
ax_anim 2, 0, 52, 0, -3, 0, -3,
ax_anim_terminator
sShuppetAnims_3_6:
ax_anim 1, 0, 51, 1, 1, 1, 1,
ax_anim 1, 0, 51, 2, 2, 2, 2,
ax_anim 2, 0, 51, 3, 3, 3, 3,
ax_anim 2, 0, 52, 3, 3, 3, 3,
ax_anim 2, 0, 53, 3, 3, 3, 3,
ax_anim 2, 0, 54, 3, 3, 3, 3,
ax_anim 2, 2, 55, 3, 3, 3, 3,
ax_anim 1, 0, 48, 0, 0, 0, 0,
ax_anim 1, 0, 49, -8, -6, -8, -6,
ax_anim 2, 0, 50, -14, -11, -14, -11,
ax_anim 1, 1, 51, -21, -17, -21, -17,
ax_anim 1, 0, 52, -21, -17, -21, -17,
ax_anim 1, 0, 53, -20, -18, -20, -18,
ax_anim 1, 0, 54, -20, -18, -20, -18,
ax_anim 1, 0, 55, -21, -17, -21, -17,
ax_anim 1, 0, 48, -21, -17, -21, -17,
ax_anim 1, 0, 49, -20, -18, -20, -18,
ax_anim 1, 0, 50, -20, -18, -20, -18,
ax_anim 2, 0, 51, -11, -9, -11, -9,
ax_anim 2, 0, 51, -5, -3, -5, -3,
ax_anim_terminator
sShuppetAnims_3_7:
ax_anim 1, 0, 50, 1, 0, 1, 0,
ax_anim 1, 0, 50, 2, 0, 2, 0,
ax_anim 2, 0, 50, 3, 0, 3, 0,
ax_anim 2, 0, 51, 3, 0, 3, 0,
ax_anim 2, 0, 52, 3, 0, 3, 0,
ax_anim 2, 0, 53, 3, 0, 3, 0,
ax_anim 2, 2, 54, 3, 0, 3, 0,
ax_anim 1, 0, 55, 0, 0, 0, 0,
ax_anim 1, 0, 48, -7, 0, -7, 0,
ax_anim 2, 0, 49, -13, 0, -13, 0,
ax_anim 1, 1, 50, -20, 0, -20, 0,
ax_anim 1, 0, 51, -20, 0, -20, 0,
ax_anim 1, 0, 52, -20, 1, -20, 1,
ax_anim 1, 0, 53, -20, 1, -20, 1,
ax_anim 1, 0, 54, -20, 0, -20, 0,
ax_anim 1, 0, 55, -20, 0, -20, 0,
ax_anim 1, 0, 48, -20, 1, -20, 1,
ax_anim 1, 0, 49, -20, 1, -20, 1,
ax_anim 2, 0, 50, -10, 0, -10, 0,
ax_anim 2, 0, 50, -4, 0, -4, 0,
ax_anim_terminator
sShuppetAnims_3_8:
ax_anim 1, 0, 49, 1, -1, 1, -1,
ax_anim 1, 0, 49, 2, -2, 2, -2,
ax_anim 2, 0, 49, 3, -3, 3, -3,
ax_anim 2, 0, 50, 3, -3, 3, -3,
ax_anim 2, 0, 51, 3, -3, 3, -3,
ax_anim 2, 0, 52, 3, -3, 3, -3,
ax_anim 2, 2, 53, 3, -3, 3, -3,
ax_anim 1, 0, 54, 0, 0, 0, 0,
ax_anim 1, 0, 55, -7, 7, -7, 7,
ax_anim 2, 0, 48, -13, 13, -13, 13,
ax_anim 1, 1, 49, -21, 23, -21, 23,
ax_anim 1, 0, 50, -21, 23, -21, 23,
ax_anim 1, 0, 51, -20, 24, -20, 24,
ax_anim 1, 0, 52, -20, 24, -20, 24,
ax_anim 1, 0, 53, -21, 23, -21, 23,
ax_anim 1, 0, 54, -21, 23, -21, 23,
ax_anim 1, 0, 55, -20, 24, -20, 24,
ax_anim 1, 0, 48, -20, 24, -20, 24,
ax_anim 2, 0, 49, -10, 10, -10, 10,
ax_anim 2, 0, 49, -4, 4, -4, 4,
ax_anim_terminator
.align 2
sShuppetAnims_4_1:
ax_anim 2, 0, 64, 1, 0, 1, 0,
ax_anim 2, 2, 64, 0, 0, 0, 0,
ax_anim 2, 0, 64, 1, 0, 1, 0,
ax_anim 2, 0, 64, 0, 0, 0, 0,
ax_anim 2, 0, 64, 1, 0, 1, 0,
ax_anim 2, 1, 64, 0, 0, 0, 0,
ax_anim 2, 0, 64, 1, 0, 1, 0,
ax_anim 2, 0, 64, 0, 0, 0, 0,
ax_anim 2, 0, 64, 1, 0, 1, 0,
ax_anim 2, 0, 64, 0, 0, 0, 0,
ax_anim_terminator
sShuppetAnims_4_2:
ax_anim 2, 0, 71, 1, -1, 1, -1,
ax_anim 2, 2, 71, 0, 0, 0, 0,
ax_anim 2, 0, 71, 1, -1, 1, -1,
ax_anim 2, 0, 71, 0, 0, 0, 0,
ax_anim 2, 0, 71, 1, -1, 1, -1,
ax_anim 2, 1, 71, 0, 0, 0, 0,
ax_anim 2, 0, 71, 1, -1, 1, -1,
ax_anim 2, 0, 71, 0, 0, 0, 0,
ax_anim 2, 0, 71, 1, -1, 1, -1,
ax_anim 2, 0, 71, 0, 0, 0, 0,
ax_anim_terminator
sShuppetAnims_4_3:
ax_anim 2, 0, 70, 0, -1, 0, -1,
ax_anim 2, 2, 70, 0, 0, 0, 0,
ax_anim 2, 0, 70, 0, -1, 0, -1,
ax_anim 2, 0, 70, 0, 0, 0, 0,
ax_anim 2, 0, 70, 0, -1, 0, -1,
ax_anim 2, 1, 70, 0, 0, 0, 0,
ax_anim 2, 0, 70, 0, -1, 0, -1,
ax_anim 2, 0, 70, 0, 0, 0, 0,
ax_anim 2, 0, 70, 0, -1, 0, -1,
ax_anim 2, 0, 70, 0, 0, 0, 0,
ax_anim_terminator
sShuppetAnims_4_4:
ax_anim 2, 0, 69, -1, -1, -1, -1,
ax_anim 2, 2, 69, 0, 0, 0, 0,
ax_anim 2, 0, 69, -1, -1, -1, -1,
ax_anim 2, 0, 69, 0, 0, 0, 0,
ax_anim 2, 0, 69, -1, -1, -1, -1,
ax_anim 2, 1, 69, 0, 0, 0, 0,
ax_anim 2, 0, 69, -1, -1, -1, -1,
ax_anim 2, 0, 69, 0, 0, 0, 0,
ax_anim 2, 0, 69, -1, -1, -1, -1,
ax_anim 2, 0, 69, 0, 0, 0, 0,
ax_anim_terminator
sShuppetAnims_4_5:
ax_anim 2, 0, 68, 1, 0, 1, 0,
ax_anim 2, 2, 68, 0, 0, 0, 0,
ax_anim 2, 0, 68, 1, 0, 1, 0,
ax_anim 2, 0, 68, 0, 0, 0, 0,
ax_anim 2, 0, 68, 1, 0, 1, 0,
ax_anim 2, 1, 68, 0, 0, 0, 0,
ax_anim 2, 0, 68, 1, 0, 1, 0,
ax_anim 2, 0, 68, 0, 0, 0, 0,
ax_anim 2, 0, 68, 1, 0, 1, 0,
ax_anim 2, 0, 68, 0, 0, 0, 0,
ax_anim_terminator
sShuppetAnims_4_6:
ax_anim 2, 0, 67, 1, -1, 1, -1,
ax_anim 2, 2, 67, 0, 0, 0, 0,
ax_anim 2, 0, 67, 1, -1, 1, -1,
ax_anim 2, 0, 67, 0, 0, 0, 0,
ax_anim 2, 0, 67, 1, -1, 1, -1,
ax_anim 2, 1, 67, 0, 0, 0, 0,
ax_anim 2, 0, 67, 1, -1, 1, -1,
ax_anim 2, 0, 67, 0, 0, 0, 0,
ax_anim 2, 0, 67, 1, -1, 1, -1,
ax_anim 2, 0, 67, 0, 0, 0, 0,
ax_anim_terminator
sShuppetAnims_4_7:
ax_anim 2, 0, 66, 0, -1, 0, -1,
ax_anim 2, 2, 66, 0, 0, 0, 0,
ax_anim 2, 0, 66, 0, -1, 0, -1,
ax_anim 2, 0, 66, 0, 0, 0, 0,
ax_anim 2, 0, 66, 0, -1, 0, -1,
ax_anim 2, 1, 66, 0, 0, 0, 0,
ax_anim 2, 0, 66, 0, -1, 0, -1,
ax_anim 2, 0, 66, 0, 0, 0, 0,
ax_anim 2, 0, 66, 0, -1, 0, -1,
ax_anim 2, 0, 66, 0, 0, 0, 0,
ax_anim_terminator
sShuppetAnims_4_8:
ax_anim 2, 0, 65, -1, -1, -1, -1,
ax_anim 2, 2, 65, 0, 0, 0, 0,
ax_anim 2, 0, 65, -1, -1, -1, -1,
ax_anim 2, 0, 65, 0, 0, 0, 0,
ax_anim 2, 0, 65, -1, -1, -1, -1,
ax_anim 2, 1, 65, 0, 0, 0, 0,
ax_anim 2, 0, 65, -1, -1, -1, -1,
ax_anim 2, 0, 65, 0, 0, 0, 0,
ax_anim 2, 0, 65, -1, -1, -1, -1,
ax_anim 2, 0, 65, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sShuppetAnims_5_1:
ax_anim 2, 0, 91, 0, 0, 0, 0,
ax_anim 2, 0, 102, 0, 0, 0, 0,
ax_anim 2, 0, 113, 0, 0, 0, 0,
ax_anim 2, 0, 123, 0, 0, 0, 0,
ax_anim 2, 0, 133, 0, 0, 0, 0,
ax_anim 2, 2, 143, 0, 0, 0, 0,
ax_anim 2, 0, 154, 0, 0, 0, 0,
ax_anim 4, 0, 80, 0, 0, 0, 0,
ax_anim 1, 0, 83, 0, 0, 0, 0,
ax_anim 1, 0, 84, 0, 0, 0, 0,
ax_anim 1, 0, 85, 0, 0, 0, 0,
ax_anim 1, 0, 86, 0, 0, 0, 0,
ax_anim 1, 0, 87, 0, 0, 0, 0,
ax_anim 1, 0, 88, 0, 0, 0, 0,
ax_anim 1, 0, 89, 0, 0, 0, 0,
ax_anim 1, 0, 85, 0, 0, 0, 0,
ax_anim 1, 0, 90, 0, 0, 0, 0,
ax_anim 1, 0, 84, 0, 0, 0, 0,
ax_anim 1, 0, 83, 0, 0, 0, 0,
ax_anim_terminator
sShuppetAnims_5_2:
ax_anim 2, 0, 102, 0, 0, 0, 0,
ax_anim 2, 0, 113, 0, 0, 0, 0,
ax_anim 2, 0, 123, 0, 0, 0, 0,
ax_anim 2, 0, 133, 0, 0, 0, 0,
ax_anim 2, 0, 143, 0, 0, 0, 0,
ax_anim 2, 2, 154, 0, 0, 0, 0,
ax_anim 2, 0, 80, 0, 0, 0, 0,
ax_anim 4, 0, 91, 0, 0, 0, 0,
ax_anim 1, 0, 94, 0, 0, 0, 0,
ax_anim 1, 0, 95, 0, 0, 0, 0,
ax_anim 1, 0, 96, 0, 0, 0, 0,
ax_anim 1, 0, 97, 0, 0, 0, 0,
ax_anim 1, 0, 98, 0, 0, 0, 0,
ax_anim 1, 0, 99, 0, 0, 0, 0,
ax_anim 1, 0, 100, 0, 0, 0, 0,
ax_anim 1, 0, 96, 0, 0, 0, 0,
ax_anim 1, 0, 101, 0, 0, 0, 0,
ax_anim 1, 0, 95, 0, 0, 0, 0,
ax_anim 1, 0, 94, 0, 0, 0, 0,
ax_anim_terminator
sShuppetAnims_5_3:
ax_anim 2, 0, 113, 0, 0, 0, 0,
ax_anim 2, 0, 123, 0, 0, 0, 0,
ax_anim 2, 0, 133, 0, 0, 0, 0,
ax_anim 2, 0, 143, 0, 0, 0, 0,
ax_anim 2, 0, 154, 0, 0, 0, 0,
ax_anim 2, 2, 80, 0, 0, 0, 0,
ax_anim 2, 0, 91, 0, 0, 0, 0,
ax_anim 4, 0, 102, 0, 0, 0, 0,
ax_anim 1, 0, 105, 0, 0, 0, 0,
ax_anim 1, 0, 106, 0, 0, 0, 0,
ax_anim 1, 0, 107, 0, 0, 0, 0,
ax_anim 1, 0, 108, 0, 0, 0, 0,
ax_anim 1, 0, 109, 0, 0, 0, 0,
ax_anim 1, 0, 110, 0, 0, 0, 0,
ax_anim 1, 0, 111, 0, 0, 0, 0,
ax_anim 1, 0, 107, 0, 0, 0, 0,
ax_anim 1, 0, 112, 0, 0, 0, 0,
ax_anim 1, 0, 106, 0, 0, 0, 0,
ax_anim 1, 0, 105, 0, 0, 0, 0,
ax_anim_terminator
sShuppetAnims_5_4:
ax_anim 2, 0, 123, 0, 0, 0, 0,
ax_anim 2, 0, 133, 0, 0, 0, 0,
ax_anim 2, 0, 143, 0, 0, 0, 0,
ax_anim 2, 0, 154, 0, 0, 0, 0,
ax_anim 2, 0, 80, 0, 0, 0, 0,
ax_anim 2, 2, 91, 0, 0, 0, 0,
ax_anim 2, 0, 102, 0, 0, 0, 0,
ax_anim 4, 0, 113, 0, 0, 0, 0,
ax_anim 1, 0, 115, 0, 0, 0, 0,
ax_anim 1, 0, 116, 0, 0, 0, 0,
ax_anim 1, 0, 117, 0, 0, 0, 0,
ax_anim 1, 0, 118, 0, 0, 0, 0,
ax_anim 1, 0, 119, 0, 0, 0, 0,
ax_anim 1, 0, 120, 0, 0, 0, 0,
ax_anim 1, 0, 121, 0, 0, 0, 0,
ax_anim 1, 0, 117, 0, 0, 0, 0,
ax_anim 1, 0, 122, 0, 0, 0, 0,
ax_anim 1, 0, 116, 0, 0, 0, 0,
ax_anim 1, 0, 115, 0, 0, 0, 0,
ax_anim_terminator
sShuppetAnims_5_5:
ax_anim 2, 0, 133, 0, 0, 0, 0,
ax_anim 2, 0, 143, 0, 0, 0, 0,
ax_anim 2, 0, 154, 0, 0, 0, 0,
ax_anim 2, 0, 80, 0, 0, 0, 0,
ax_anim 2, 0, 91, 0, 0, 0, 0,
ax_anim 2, 2, 102, 0, 0, 0, 0,
ax_anim 2, 0, 113, 0, 0, 0, 0,
ax_anim 4, 0, 123, 0, 0, 0, 0,
ax_anim 1, 0, 125, 0, 0, 0, 0,
ax_anim 1, 0, 126, 0, 0, 0, 0,
ax_anim 1, 0, 127, 0, 0, 0, 0,
ax_anim 1, 0, 128, 0, 0, 0, 0,
ax_anim 1, 0, 129, 0, 0, 0, 0,
ax_anim 1, 0, 130, 0, 0, 0, 0,
ax_anim 1, 0, 131, 0, 0, 0, 0,
ax_anim 1, 0, 127, 0, 0, 0, 0,
ax_anim 1, 0, 132, 0, 0, 0, 0,
ax_anim 1, 0, 126, 0, 0, 0, 0,
ax_anim 1, 0, 125, 0, 0, 0, 0,
ax_anim_terminator
sShuppetAnims_5_6:
ax_anim 2, 0, 143, 0, 0, 0, 0,
ax_anim 2, 0, 154, 0, 0, 0, 0,
ax_anim 2, 0, 80, 0, 0, 0, 0,
ax_anim 2, 0, 91, 0, 0, 0, 0,
ax_anim 2, 0, 102, 0, 0, 0, 0,
ax_anim 2, 2, 113, 0, 0, 0, 0,
ax_anim 2, 0, 123, 0, 0, 0, 0,
ax_anim 4, 0, 133, 0, 0, 0, 0,
ax_anim 1, 0, 135, 0, 0, 0, 0,
ax_anim 1, 0, 136, 0, 0, 0, 0,
ax_anim 1, 0, 137, 0, 0, 0, 0,
ax_anim 1, 0, 138, 0, 0, 0, 0,
ax_anim 1, 0, 139, 0, 0, 0, 0,
ax_anim 1, 0, 140, 0, 0, 0, 0,
ax_anim 1, 0, 141, 0, 0, 0, 0,
ax_anim 1, 0, 137, 0, 0, 0, 0,
ax_anim 1, 0, 142, 0, 0, 0, 0,
ax_anim 1, 0, 136, 0, 0, 0, 0,
ax_anim 1, 0, 135, 0, 0, 0, 0,
ax_anim_terminator
sShuppetAnims_5_7:
ax_anim 2, 0, 154, 0, 0, 0, 0,
ax_anim 2, 0, 80, 0, 0, 0, 0,
ax_anim 2, 0, 91, 0, 0, 0, 0,
ax_anim 2, 0, 102, 0, 0, 0, 0,
ax_anim 2, 0, 113, 0, 0, 0, 0,
ax_anim 2, 2, 123, 0, 0, 0, 0,
ax_anim 2, 0, 133, 0, 0, 0, 0,
ax_anim 4, 0, 143, 0, 0, 0, 0,
ax_anim 1, 0, 146, 0, 0, 0, 0,
ax_anim 1, 0, 147, 0, 0, 0, 0,
ax_anim 1, 0, 148, 0, 0, 0, 0,
ax_anim 1, 0, 149, 0, 0, 0, 0,
ax_anim 1, 0, 150, 0, 0, 0, 0,
ax_anim 1, 0, 151, 0, 0, 0, 0,
ax_anim 1, 0, 152, 0, 0, 0, 0,
ax_anim 1, 0, 148, 0, 0, 0, 0,
ax_anim 1, 0, 153, 0, 0, 0, 0,
ax_anim 1, 0, 147, 0, 0, 0, 0,
ax_anim 1, 0, 146, 0, 0, 0, 0,
ax_anim_terminator
sShuppetAnims_5_8:
ax_anim 2, 0, 80, 0, 0, 0, 0,
ax_anim 2, 0, 91, 0, 0, 0, 0,
ax_anim 2, 0, 102, 0, 0, 0, 0,
ax_anim 2, 0, 113, 0, 0, 0, 0,
ax_anim 2, 0, 123, 0, 0, 0, 0,
ax_anim 2, 2, 133, 0, 0, 0, 0,
ax_anim 2, 0, 143, 0, 0, 0, 0,
ax_anim 4, 0, 154, 0, 0, 0, 0,
ax_anim 1, 0, 157, 0, 0, 0, 0,
ax_anim 1, 0, 158, 0, 0, 0, 0,
ax_anim 1, 0, 159, 0, 0, 0, 0,
ax_anim 1, 0, 160, 0, 0, 0, 0,
ax_anim 1, 0, 161, 0, 0, 0, 0,
ax_anim 1, 0, 162, 0, 0, 0, 0,
ax_anim 1, 0, 163, 0, 0, 0, 0,
ax_anim 1, 0, 159, 0, 0, 0, 0,
ax_anim 1, 0, 164, 0, 0, 0, 0,
ax_anim 1, 0, 158, 0, 0, 0, 0,
ax_anim 1, 0, 157, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sShuppetAnims_6_1:
ax_anim 10, 0, 165, 0, 0, 0, 0,
ax_anim 10, 0, 165, 0, -1, 0, 0,
ax_anim 18, 0, 165, 0, -2, 0, 0,
ax_anim 10, 0, 166, 0, -2, 0, 0,
ax_anim 10, 0, 166, 0, -1, 0, 0,
ax_anim 18, 0, 166, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sShuppetAnims_7_1:
ax_anim 2, 0, 167, 0, -2, 0, -2,
ax_anim 8, 0, 167, 0, -3, 0, -3,
ax_anim_terminator
sShuppetAnims_7_2:
ax_anim 2, 0, 168, -2, -2, -2, -2,
ax_anim 8, 0, 168, -3, -3, -3, -3,
ax_anim_terminator
sShuppetAnims_7_3:
ax_anim 2, 0, 169, -2, 0, -2, 0,
ax_anim 8, 0, 169, -3, 0, -3, 0,
ax_anim_terminator
sShuppetAnims_7_4:
ax_anim 2, 0, 170, -2, 2, -2, 2,
ax_anim 8, 0, 170, -3, 3, -3, 3,
ax_anim_terminator
sShuppetAnims_7_5:
ax_anim 2, 0, 171, 0, 2, 0, 2,
ax_anim 8, 0, 171, 0, 3, 0, 3,
ax_anim_terminator
sShuppetAnims_7_6:
ax_anim 2, 0, 172, 2, 2, 2, 2,
ax_anim 8, 0, 172, 3, 3, 3, 3,
ax_anim_terminator
sShuppetAnims_7_7:
ax_anim 2, 0, 173, 2, 0, 2, 0,
ax_anim 8, 0, 173, 3, 0, 3, 0,
ax_anim_terminator
sShuppetAnims_7_8:
ax_anim 2, 0, 174, 2, -2, 2, -2,
ax_anim 8, 0, 174, 3, -3, 3, -3,
ax_anim_terminator
.align 2
sShuppetAnims_8_1:
ax_anim 10, 0, 175, 0, 0, 0, 0,
ax_anim 10, 0, 176, 0, -1, 0, 0,
ax_anim 10, 0, 177, 0, -2, 0, 0,
ax_anim 10, 0, 175, 0, -3, 0, 0,
ax_anim 10, 0, 176, 0, -2, 0, 0,
ax_anim 10, 0, 177, 0, -1, 0, 0,
ax_anim_terminator
sShuppetAnims_8_2:
ax_anim 10, 0, 178, 0, 0, 0, 0,
ax_anim 10, 0, 179, 0, -1, 0, 0,
ax_anim 10, 0, 180, 0, -2, 0, 0,
ax_anim 10, 0, 178, 0, -3, 0, 0,
ax_anim 10, 0, 179, 0, -2, 0, 0,
ax_anim 10, 0, 180, 0, -1, 0, 0,
ax_anim_terminator
sShuppetAnims_8_3:
ax_anim 10, 0, 181, 0, 0, 0, 0,
ax_anim 10, 0, 182, 0, -1, 0, 0,
ax_anim 10, 0, 183, 0, -2, 0, 0,
ax_anim 10, 0, 181, 0, -3, 0, 0,
ax_anim 10, 0, 182, 0, -2, 0, 0,
ax_anim 10, 0, 183, 0, -1, 0, 0,
ax_anim_terminator
sShuppetAnims_8_4:
ax_anim 10, 0, 184, 0, 0, 0, 0,
ax_anim 10, 0, 185, 0, -1, 0, 0,
ax_anim 10, 0, 186, 0, -2, 0, 0,
ax_anim 10, 0, 184, 0, -3, 0, 0,
ax_anim 10, 0, 185, 0, -2, 0, 0,
ax_anim 10, 0, 186, 0, -1, 0, 0,
ax_anim_terminator
sShuppetAnims_8_5:
ax_anim 10, 0, 187, 0, 0, 0, 0,
ax_anim 10, 0, 188, 0, -1, 0, 0,
ax_anim 10, 0, 189, 0, -2, 0, 0,
ax_anim 10, 0, 187, 0, -3, 0, 0,
ax_anim 10, 0, 188, 0, -2, 0, 0,
ax_anim 10, 0, 189, 0, -1, 0, 0,
ax_anim_terminator
sShuppetAnims_8_6:
ax_anim 10, 0, 190, 0, 0, 0, 0,
ax_anim 10, 0, 191, 0, -1, 0, 0,
ax_anim 10, 0, 192, 0, -2, 0, 0,
ax_anim 10, 0, 190, 0, -3, 0, 0,
ax_anim 10, 0, 191, 0, -2, 0, 0,
ax_anim 10, 0, 192, 0, -1, 0, 0,
ax_anim_terminator
sShuppetAnims_8_7:
ax_anim 10, 0, 193, 0, 0, 0, 0,
ax_anim 10, 0, 194, 0, -1, 0, 0,
ax_anim 10, 0, 195, 0, -2, 0, 0,
ax_anim 10, 0, 193, 0, -3, 0, 0,
ax_anim 10, 0, 194, 0, -2, 0, 0,
ax_anim 10, 0, 195, 0, -1, 0, 0,
ax_anim_terminator
sShuppetAnims_8_8:
ax_anim 10, 0, 196, 0, 0, 0, 0,
ax_anim 10, 0, 197, 0, -1, 0, 0,
ax_anim 10, 0, 198, 0, -2, 0, 0,
ax_anim 10, 0, 196, 0, -3, 0, 0,
ax_anim 10, 0, 197, 0, -2, 0, 0,
ax_anim 10, 0, 198, 0, -1, 0, 0,
ax_anim_terminator
.align 2
sShuppetAnims_9_1:
ax_anim 2, 0, 199, 0, 0, 0, 0,
ax_anim 1, 0, 200, 6, 3, 6, 3,
ax_anim 2, 0, 201, 8, 11, 8, 11,
ax_anim 2, 0, 202, 7, 19, 7, 18,
ax_anim 3, 0, 203, 0, 24, 0, 22,
ax_anim 2, 3, 204, -7, 19, -7, 18,
ax_anim 2, 0, 205, -8, 11, -8, 11,
ax_anim 1, 0, 206, -6, 3, -6, 3,
ax_anim 1, 0, 199, 0, 0, 0, 0,
ax_anim_terminator
sShuppetAnims_9_2:
ax_anim 2, 0, 206, 0, 0, 0, 0,
ax_anim 1, 0, 199, 8, 0, 8, 0,
ax_anim 2, 0, 200, 19, 3, 19, 3,
ax_anim 2, 0, 201, 23, 12, 23, 11,
ax_anim 3, 0, 202, 21, 24, 21, 23,
ax_anim 2, 3, 203, 11, 25, 11, 24,
ax_anim 2, 0, 204, 3, 17, 3, 17,
ax_anim 1, 0, 205, 0, 7, 0, 7,
ax_anim 1, 0, 206, 0, 0, 0, 0,
ax_anim_terminator
sShuppetAnims_9_3:
ax_anim 2, 0, 205, 0, 0, 0, 0,
ax_anim 1, 0, 206, 3, -5, 3, -5,
ax_anim 2, 0, 199, 11, -6, 11, -6,
ax_anim 2, 0, 200, 18, -5, 18, -5,
ax_anim 3, 0, 201, 21, 2, 21, 0,
ax_anim 2, 3, 202, 20, 7, 20, 5,
ax_anim 2, 0, 203, 12, 7, 12, 5,
ax_anim 1, 0, 204, 4, 5, 4, 3,
ax_anim 1, 0, 205, 0, 0, 0, 0,
ax_anim_terminator
sShuppetAnims_9_4:
ax_anim 2, 0, 204, 0, 0, 0, 0,
ax_anim 1, 0, 205, -1, -6, -1, -6,
ax_anim 2, 0, 206, 4, -16, 4, -16,
ax_anim 2, 0, 199, 12, -22, 12, -22,
ax_anim 3, 0, 200, 21, -19, 21, -19,
ax_anim 2, 3, 201, 22, -13, 22, -13,
ax_anim 2, 0, 202, 17, -4, 17, -4,
ax_anim 1, 0, 203, 7, -1, 7, -1,
ax_anim 1, 0, 204, 0, 0, 0, 0,
ax_anim_terminator
sShuppetAnims_9_5:
ax_anim 2, 0, 203, 0, 0, 0, 0,
ax_anim 1, 0, 204, -8, -4, -8, -4,
ax_anim 2, 0, 205, -9, -10, -9, -10,
ax_anim 2, 0, 206, -7, -16, -7, -16,
ax_anim 3, 0, 199, 0, -19, 0, -19,
ax_anim 2, 3, 200, 7, -16, 7, -16,
ax_anim 2, 0, 201, 9, -8, 9, -8,
ax_anim 1, 0, 202, 8, -4, 8, -4,
ax_anim 1, 0, 203, 0, 0, 0, 0,
ax_anim_terminator
sShuppetAnims_9_6:
ax_anim 2, 0, 202, 0, 0, 0, 0,
ax_anim 1, 0, 201, 1, -6, 1, -6,
ax_anim 2, 0, 200, -4, -16, -4, -16,
ax_anim 2, 0, 199, -12, -22, -12, -22,
ax_anim 3, 0, 206, -21, -19, -21, -19,
ax_anim 2, 3, 205, -22, -13, -22, -13,
ax_anim 2, 0, 204, -17, -4, -17, -4,
ax_anim 1, 0, 203, -7, -1, -7, -1,
ax_anim 1, 0, 202, 0, 0, 0, 0,
ax_anim_terminator
sShuppetAnims_9_7:
ax_anim 2, 0, 201, 0, 0, 0, 0,
ax_anim 1, 0, 200, -3, -5, -3, -5,
ax_anim 2, 0, 199, -11, -6, -11, -6,
ax_anim 2, 0, 206, -18, -5, -18, -5,
ax_anim 3, 0, 205, -21, 2, -21, 0,
ax_anim 2, 3, 204, -20, 7, -20, 5,
ax_anim 2, 0, 203, -12, 7, -12, 5,
ax_anim 1, 0, 202, -4, 5, -4, 3,
ax_anim 1, 0, 201, 0, 0, 0, 0,
ax_anim_terminator
sShuppetAnims_9_8:
ax_anim 2, 0, 200, 0, 0, 0, 0,
ax_anim 1, 0, 199, -8, 0, -8, 0,
ax_anim 2, 0, 206, -19, 3, -19, 3,
ax_anim 2, 0, 205, -23, 12, -23, 11,
ax_anim 3, 0, 204, -21, 24, -21, 23,
ax_anim 2, 3, 203, -11, 25, -11, 24,
ax_anim 2, 0, 202, -3, 17, -3, 17,
ax_anim 1, 0, 201, 0, 7, 0, 7,
ax_anim 1, 0, 200, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sShuppetAnims_10_1:
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 0, 215, 6, 0, 6, 0,
ax_anim 2, 0, 215, -6, 0, -6, 0,
ax_anim 2, 0, 215, 10, 0, 10, 0,
ax_anim 2, 0, 215, -10, 0, -10, 0,
ax_anim 2, 0, 215, 12, 0, 12, 0,
ax_anim 3, 0, 215, -12, 0, -12, 0,
ax_anim 3, 0, 215, 13, 0, 13, 0,
ax_anim 3, 0, 215, -13, 0, -13, 0,
ax_anim 2, 0, 215, 12, 0, 12, 0,
ax_anim 3, 0, 215, -12, 0, -12, 0,
ax_anim 2, 0, 215, 10, 0, 10, 0,
ax_anim 2, 0, 215, -10, 0, -10, 0,
ax_anim 2, 0, 215, 6, 0, 6, 0,
ax_anim 2, 0, 215, -6, 0, -6, 0,
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim_terminator
sShuppetAnims_10_2:
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 0, 216, 6, -6, 6, -6,
ax_anim 2, 0, 216, -6, 6, -6, 6,
ax_anim 2, 0, 216, 10, -10, 10, -10,
ax_anim 2, 0, 216, -10, 10, -10, 10,
ax_anim 2, 0, 216, 12, -12, 12, -12,
ax_anim 3, 0, 216, -12, 12, -12, 12,
ax_anim 3, 0, 216, 13, -13, 13, -13,
ax_anim 3, 0, 216, -13, 13, -13, 13,
ax_anim 2, 0, 216, 12, -12, 12, -12,
ax_anim 3, 0, 216, -12, 12, -12, 12,
ax_anim 2, 0, 216, 10, -10, 10, -10,
ax_anim 2, 0, 216, -10, 10, -10, 10,
ax_anim 2, 0, 216, 6, -6, 6, -6,
ax_anim 2, 0, 216, -6, 6, -6, 6,
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim_terminator
sShuppetAnims_10_3:
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 0, 217, 0, -6, 0, -6,
ax_anim 2, 0, 217, 0, 6, 0, 6,
ax_anim 2, 0, 217, 0, -10, 0, -10,
ax_anim 2, 0, 217, 0, 10, 0, 10,
ax_anim 2, 0, 217, 0, -12, 0, -12,
ax_anim 3, 0, 217, 0, 12, 0, 12,
ax_anim 3, 0, 217, 0, -13, 0, -13,
ax_anim 3, 0, 217, 0, 13, 0, 13,
ax_anim 2, 0, 217, 0, -12, 0, -12,
ax_anim 3, 0, 217, 0, 12, 0, 12,
ax_anim 2, 0, 217, 0, -10, 0, -10,
ax_anim 2, 0, 217, 0, 10, 0, 10,
ax_anim 2, 0, 217, 0, -6, 0, -6,
ax_anim 2, 0, 217, 0, 6, 0, 6,
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim_terminator
sShuppetAnims_10_4:
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 218, -6, -6, -6, -6,
ax_anim 2, 0, 218, 6, 6, 6, 6,
ax_anim 2, 0, 218, -10, -10, -10, -10,
ax_anim 2, 0, 218, 10, 10, 10, 10,
ax_anim 2, 0, 218, -12, -12, -12, -12,
ax_anim 3, 0, 218, 12, 12, 12, 12,
ax_anim 3, 0, 218, -13, -13, -13, -13,
ax_anim 3, 0, 218, 13, 13, 13, 13,
ax_anim 2, 0, 218, -12, -12, -12, -12,
ax_anim 3, 0, 218, 12, 12, 12, 12,
ax_anim 2, 0, 218, -10, -10, -10, -10,
ax_anim 2, 0, 218, 10, 10, 10, 10,
ax_anim 2, 0, 218, -6, -6, -6, -6,
ax_anim 2, 0, 218, 6, 6, 6, 6,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim_terminator
sShuppetAnims_10_5:
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 0, 219, 6, 0, 6, 0,
ax_anim 2, 0, 219, -6, 0, -6, 0,
ax_anim 2, 0, 219, 10, 0, 10, 0,
ax_anim 2, 0, 219, -10, 0, -10, 0,
ax_anim 2, 0, 219, 12, 0, 12, 0,
ax_anim 3, 0, 219, -12, 0, -12, 0,
ax_anim 3, 0, 219, 13, 0, 13, 0,
ax_anim 3, 0, 219, -13, 0, -13, 0,
ax_anim 2, 0, 219, 12, 0, 12, 0,
ax_anim 3, 0, 219, -12, 0, -12, 0,
ax_anim 2, 0, 219, 10, 0, 10, 0,
ax_anim 2, 0, 219, -10, 0, -10, 0,
ax_anim 2, 0, 219, 6, 0, 6, 0,
ax_anim 2, 0, 219, -6, 0, -6, 0,
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim_terminator
sShuppetAnims_10_6:
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 0, 220, 6, -6, 6, -6,
ax_anim 2, 0, 220, -6, 6, -6, 6,
ax_anim 2, 0, 220, 10, -10, 10, -10,
ax_anim 2, 0, 220, -10, 10, -10, 10,
ax_anim 2, 0, 220, 12, -12, 12, -12,
ax_anim 3, 0, 220, -12, 12, -12, 12,
ax_anim 3, 0, 220, 13, -13, 13, -13,
ax_anim 3, 0, 220, -13, 13, -13, 13,
ax_anim 2, 0, 220, 12, -12, 12, -12,
ax_anim 3, 0, 220, -12, 12, -12, 12,
ax_anim 2, 0, 220, 10, -10, 10, -10,
ax_anim 2, 0, 220, -10, 10, -10, 10,
ax_anim 2, 0, 220, 6, -6, 6, -6,
ax_anim 2, 0, 220, -6, 6, -6, 6,
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim_terminator
sShuppetAnims_10_7:
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 221, 0, -6, 0, -6,
ax_anim 2, 0, 221, 0, 6, 0, 6,
ax_anim 2, 0, 221, 0, -10, 0, -10,
ax_anim 2, 0, 221, 0, 10, 0, 10,
ax_anim 2, 0, 221, 0, -12, 0, -12,
ax_anim 3, 0, 221, 0, 12, 0, 12,
ax_anim 3, 0, 221, 0, -13, 0, -13,
ax_anim 3, 0, 221, 0, 13, 0, 13,
ax_anim 2, 0, 221, 0, -12, 0, -12,
ax_anim 3, 0, 221, 0, 12, 0, 12,
ax_anim 2, 0, 221, 0, -10, 0, -10,
ax_anim 2, 0, 221, 0, 10, 0, 10,
ax_anim 2, 0, 221, 0, -6, 0, -6,
ax_anim 2, 0, 221, 0, 6, 0, 6,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim_terminator
sShuppetAnims_10_8:
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 0, 222, -6, -6, -6, -6,
ax_anim 2, 0, 222, 6, 6, 6, 6,
ax_anim 2, 0, 222, -10, -10, -10, -10,
ax_anim 2, 0, 222, 10, 10, 10, 10,
ax_anim 2, 0, 222, -12, -12, -12, -12,
ax_anim 3, 0, 222, 12, 12, 12, 12,
ax_anim 3, 0, 222, -13, -13, -13, -13,
ax_anim 3, 0, 222, 13, 13, 13, 13,
ax_anim 2, 0, 222, -12, -12, -12, -12,
ax_anim 3, 0, 222, 12, 12, 12, 12,
ax_anim 2, 0, 222, -10, -10, -10, -10,
ax_anim 2, 0, 222, 10, 10, 10, 10,
ax_anim 2, 0, 222, -6, -6, -6, -6,
ax_anim 2, 0, 222, 6, 6, 6, 6,
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sShuppetAnims_11_1:
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 1, 0, 224, 0, -10, 0, 0,
ax_anim 2, 0, 225, 0, -16, 0, 0,
ax_anim 3, 0, 223, 0, -20, 0, 0,
ax_anim 4, 0, 224, 0, -21, 0, 0,
ax_anim 4, 0, 225, 0, -23, 0, 0,
ax_anim 3, 0, 223, 0, -22, 0, 0,
ax_anim 2, 0, 224, 0, -18, 0, 0,
ax_anim 1, 0, 225, 0, -10, 0, 0,
ax_anim 2, 2, 223, 0, 4, 0, 0,
ax_anim_terminator
sShuppetAnims_11_2:
ax_anim 2, 0, 226, 0, 0, 0, 0,
ax_anim 1, 0, 227, 0, -10, 0, 0,
ax_anim 2, 0, 228, 0, -16, 0, 0,
ax_anim 3, 0, 226, 0, -20, 0, 0,
ax_anim 4, 0, 227, 0, -21, 0, 0,
ax_anim 4, 0, 228, 0, -23, 0, 0,
ax_anim 3, 0, 226, 0, -22, 0, 0,
ax_anim 2, 0, 227, 0, -18, 0, 0,
ax_anim 1, 0, 228, 0, -10, 0, 0,
ax_anim 2, 2, 226, 0, 4, 0, 0,
ax_anim_terminator
sShuppetAnims_11_3:
ax_anim 2, 0, 229, 0, 0, 0, 0,
ax_anim 1, 0, 230, 0, -10, 0, 0,
ax_anim 2, 0, 231, 0, -16, 0, 0,
ax_anim 3, 0, 229, 0, -20, 0, 0,
ax_anim 4, 0, 230, 0, -21, 0, 0,
ax_anim 4, 0, 231, 0, -23, 0, 0,
ax_anim 3, 0, 229, 0, -22, 0, 0,
ax_anim 2, 0, 230, 0, -18, 0, 0,
ax_anim 1, 0, 231, 0, -10, 0, 0,
ax_anim 2, 2, 229, 0, 4, 0, 0,
ax_anim_terminator
sShuppetAnims_11_4:
ax_anim 2, 0, 232, 0, 0, 0, 0,
ax_anim 1, 0, 233, 0, -10, 0, 0,
ax_anim 2, 0, 234, 0, -16, 0, 0,
ax_anim 3, 0, 232, 0, -20, 0, 0,
ax_anim 4, 0, 233, 0, -21, 0, 0,
ax_anim 4, 0, 234, 0, -22, 0, 0,
ax_anim 3, 0, 232, 0, -21, 0, 0,
ax_anim 2, 0, 233, 0, -17, 0, 0,
ax_anim 1, 0, 234, 0, -8, 0, 0,
ax_anim 2, 2, 232, 0, 5, 0, 0,
ax_anim_terminator
sShuppetAnims_11_5:
ax_anim 2, 0, 235, 0, 0, 0, 0,
ax_anim 1, 0, 236, 0, -10, 0, 0,
ax_anim 2, 0, 237, 0, -16, 0, 0,
ax_anim 3, 0, 235, 0, -20, 0, 0,
ax_anim 4, 0, 236, 0, -21, 0, 0,
ax_anim 4, 0, 237, 0, -23, 0, 0,
ax_anim 3, 0, 235, 0, -22, 0, 0,
ax_anim 2, 0, 236, 0, -18, 0, 0,
ax_anim 1, 0, 237, 0, -9, 0, 0,
ax_anim 2, 2, 235, 0, 5, 0, 0,
ax_anim_terminator
sShuppetAnims_11_6:
ax_anim 2, 0, 238, 0, 0, 0, 0,
ax_anim 1, 0, 239, 0, -10, 0, 0,
ax_anim 2, 0, 240, 0, -16, 0, 0,
ax_anim 3, 0, 238, 0, -20, 0, 0,
ax_anim 4, 0, 239, 0, -21, 0, 0,
ax_anim 4, 0, 240, 0, -22, 0, 0,
ax_anim 3, 0, 238, 0, -21, 0, 0,
ax_anim 2, 0, 239, 0, -17, 0, 0,
ax_anim 1, 0, 240, 0, -8, 0, 0,
ax_anim 2, 2, 238, 0, 5, 0, 0,
ax_anim_terminator
sShuppetAnims_11_7:
ax_anim 2, 0, 241, 0, 0, 0, 0,
ax_anim 1, 0, 242, 0, -10, 0, 0,
ax_anim 2, 0, 243, 0, -16, 0, 0,
ax_anim 3, 0, 241, 0, -20, 0, 0,
ax_anim 4, 0, 242, 0, -21, 0, 0,
ax_anim 4, 0, 243, 0, -23, 0, 0,
ax_anim 3, 0, 241, 0, -22, 0, 0,
ax_anim 2, 0, 242, 0, -18, 0, 0,
ax_anim 1, 0, 243, 0, -10, 0, 0,
ax_anim 2, 2, 241, 0, 4, 0, 0,
ax_anim_terminator
sShuppetAnims_11_8:
ax_anim 2, 0, 244, 0, 0, 0, 0,
ax_anim 1, 0, 245, 0, -10, 0, 0,
ax_anim 2, 0, 246, 0, -16, 0, 0,
ax_anim 3, 0, 244, 0, -20, 0, 0,
ax_anim 4, 0, 245, 0, -21, 0, 0,
ax_anim 4, 0, 246, 0, -23, 0, 0,
ax_anim 3, 0, 244, 0, -22, 0, 0,
ax_anim 2, 0, 245, 0, -18, 0, 0,
ax_anim 1, 0, 246, 0, -10, 0, 0,
ax_anim 2, 2, 244, 0, 4, 0, 0,
ax_anim_terminator
.align 2
sShuppetAnims_12_1:
ax_anim 2, 0, 247, 1, 0, 1, 0,
ax_anim 2, 0, 247, 0, 0, 0, 0,
ax_anim 2, 0, 247, 1, 0, 1, 0,
ax_anim 2, 0, 247, 0, 0, 0, 0,
ax_anim 2, 0, 247, 1, 0, 1, 0,
ax_anim 2, 2, 247, 0, 0, 0, 0,
ax_anim 2, 0, 247, 1, 0, 1, 0,
ax_anim 2, 0, 247, 0, 0, 0, 0,
ax_anim 2, 0, 247, 1, 0, 1, 0,
ax_anim 2, 1, 247, 0, 0, 0, 0,
ax_anim_terminator
sShuppetAnims_12_2:
ax_anim 2, 0, 254, 1, -1, 1, -1,
ax_anim 2, 0, 254, 0, 0, 0, 0,
ax_anim 2, 0, 254, 1, -1, 1, -1,
ax_anim 2, 0, 254, 0, 0, 0, 0,
ax_anim 2, 0, 254, 1, -1, 1, -1,
ax_anim 2, 2, 254, 0, 0, 0, 0,
ax_anim 2, 0, 254, 1, -1, 1, -1,
ax_anim 2, 0, 254, 0, 0, 0, 0,
ax_anim 2, 0, 254, 1, -1, 1, -1,
ax_anim 2, 1, 254, 0, 0, 0, 0,
ax_anim_terminator
sShuppetAnims_12_3:
ax_anim 2, 0, 253, 0, -1, 0, -1,
ax_anim 2, 0, 253, 0, 0, 0, 0,
ax_anim 2, 0, 253, 0, -1, 0, -1,
ax_anim 2, 0, 253, 0, 0, 0, 0,
ax_anim 2, 0, 253, 0, -1, 0, -1,
ax_anim 2, 2, 253, 0, 0, 0, 0,
ax_anim 2, 0, 253, 0, -1, 0, -1,
ax_anim 2, 0, 253, 0, 0, 0, 0,
ax_anim 2, 0, 253, 0, -1, 0, -1,
ax_anim 2, 1, 253, 0, 0, 0, 0,
ax_anim_terminator
sShuppetAnims_12_4:
ax_anim 2, 0, 252, -1, -1, -1, -1,
ax_anim 2, 0, 252, 0, 0, 0, 0,
ax_anim 2, 0, 252, -1, -1, -1, -1,
ax_anim 2, 0, 252, 0, 0, 0, 0,
ax_anim 2, 0, 252, -1, -1, -1, -1,
ax_anim 2, 2, 252, 0, 0, 0, 0,
ax_anim 2, 0, 252, -1, -1, -1, -1,
ax_anim 2, 0, 252, 0, 0, 0, 0,
ax_anim 2, 0, 252, -1, -1, -1, -1,
ax_anim 2, 1, 252, 0, 0, 0, 0,
ax_anim_terminator
sShuppetAnims_12_5:
ax_anim 2, 0, 251, 1, 0, 1, 0,
ax_anim 2, 0, 251, 0, 0, 0, 0,
ax_anim 2, 0, 251, 1, 0, 1, 0,
ax_anim 2, 0, 251, 0, 0, 0, 0,
ax_anim 2, 0, 251, 1, 0, 1, 0,
ax_anim 2, 2, 251, 0, 0, 0, 0,
ax_anim 2, 0, 251, 1, 0, 1, 0,
ax_anim 2, 0, 251, 0, 0, 0, 0,
ax_anim 2, 0, 251, 1, 0, 1, 0,
ax_anim 2, 1, 251, 0, 0, 0, 0,
ax_anim_terminator
sShuppetAnims_12_6:
ax_anim 2, 0, 250, 1, -1, 1, -1,
ax_anim 2, 0, 250, 0, 0, 0, 0,
ax_anim 2, 0, 250, 1, -1, 1, -1,
ax_anim 2, 0, 250, 0, 0, 0, 0,
ax_anim 2, 0, 250, 1, -1, 1, -1,
ax_anim 2, 2, 250, 0, 0, 0, 0,
ax_anim 2, 0, 250, 1, -1, 1, -1,
ax_anim 2, 0, 250, 0, 0, 0, 0,
ax_anim 2, 0, 250, 1, -1, 1, -1,
ax_anim 2, 1, 250, 0, 0, 0, 0,
ax_anim_terminator
sShuppetAnims_12_7:
ax_anim 2, 0, 249, 0, -1, 0, -1,
ax_anim 2, 0, 249, 0, 0, 0, 0,
ax_anim 2, 0, 249, 0, -1, 0, -1,
ax_anim 2, 0, 249, 0, 0, 0, 0,
ax_anim 2, 0, 249, 0, -1, 0, -1,
ax_anim 2, 2, 249, 0, 0, 0, 0,
ax_anim 2, 0, 249, 0, -1, 0, -1,
ax_anim 2, 0, 249, 0, 0, 0, 0,
ax_anim 2, 0, 249, 0, -1, 0, -1,
ax_anim 2, 1, 249, 0, 0, 0, 0,
ax_anim_terminator
sShuppetAnims_12_8:
ax_anim 2, 0, 248, -1, -1, -1, -1,
ax_anim 2, 0, 248, 0, 0, 0, 0,
ax_anim 2, 0, 248, -1, -1, -1, -1,
ax_anim 2, 0, 248, 0, 0, 0, 0,
ax_anim 2, 0, 248, -1, -1, -1, -1,
ax_anim 2, 2, 248, 0, 0, 0, 0,
ax_anim 2, 0, 248, -1, -1, -1, -1,
ax_anim 2, 0, 248, 0, 0, 0, 0,
ax_anim 2, 0, 248, -1, -1, -1, -1,
ax_anim 2, 1, 248, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sShuppetAnims_13_1:
ax_anim 2, 0, 263, 0, 0, 0, 0,
ax_anim 2, 0, 264, 0, 0, 0, 0,
ax_anim 2, 0, 265, 0, 0, 0, 0,
ax_anim 2, 0, 266, 0, 0, 0, 0,
ax_anim 2, 0, 267, 0, 0, 0, 0,
ax_anim 2, 0, 268, 0, 0, 0, 0,
ax_anim 2, 0, 269, 0, 0, 0, 0,
ax_anim 2, 0, 270, 0, 0, 0, 0,
ax_anim 2, 2, 263, 0, 0, 0, 0,
ax_anim_terminator
sShuppetAnims_13_2:
ax_anim 2, 0, 270, 0, 0, 0, 0,
ax_anim 2, 0, 263, 0, 0, 0, 0,
ax_anim 2, 0, 264, 0, 0, 0, 0,
ax_anim 2, 0, 265, 0, 0, 0, 0,
ax_anim 2, 0, 266, 0, 0, 0, 0,
ax_anim 2, 0, 267, 0, 0, 0, 0,
ax_anim 2, 0, 268, 0, 0, 0, 0,
ax_anim 2, 0, 269, 0, 0, 0, 0,
ax_anim 2, 2, 270, 0, 0, 0, 0,
ax_anim_terminator
sShuppetAnims_13_3:
ax_anim 2, 0, 269, 0, 0, 0, 0,
ax_anim 2, 0, 270, 0, 0, 0, 0,
ax_anim 2, 0, 263, 0, 0, 0, 0,
ax_anim 2, 0, 264, 0, 0, 0, 0,
ax_anim 2, 0, 265, 0, 0, 0, 0,
ax_anim 2, 0, 266, 0, 0, 0, 0,
ax_anim 2, 0, 267, 0, 0, 0, 0,
ax_anim 2, 0, 268, 0, 0, 0, 0,
ax_anim 2, 2, 269, 0, 0, 0, 0,
ax_anim_terminator
sShuppetAnims_13_4:
ax_anim 2, 0, 268, 0, 0, 0, 0,
ax_anim 2, 0, 269, 0, 0, 0, 0,
ax_anim 2, 0, 270, 0, 0, 0, 0,
ax_anim 2, 0, 263, 0, 0, 0, 0,
ax_anim 2, 0, 264, 0, 0, 0, 0,
ax_anim 2, 0, 265, 0, 0, 0, 0,
ax_anim 2, 0, 266, 0, 0, 0, 0,
ax_anim 2, 0, 267, 0, 0, 0, 0,
ax_anim 2, 2, 268, 0, 0, 0, 0,
ax_anim_terminator
sShuppetAnims_13_5:
ax_anim 2, 0, 267, 0, 0, 0, 0,
ax_anim 2, 0, 268, 0, 0, 0, 0,
ax_anim 2, 0, 269, 0, 0, 0, 0,
ax_anim 2, 0, 270, 0, 0, 0, 0,
ax_anim 2, 0, 263, 0, 0, 0, 0,
ax_anim 2, 0, 264, 0, 0, 0, 0,
ax_anim 2, 0, 265, 0, 0, 0, 0,
ax_anim 2, 0, 266, 0, 0, 0, 0,
ax_anim 2, 2, 267, 0, 0, 0, 0,
ax_anim_terminator
sShuppetAnims_13_6:
ax_anim 2, 0, 266, 0, 0, 0, 0,
ax_anim 2, 0, 267, 0, 0, 0, 0,
ax_anim 2, 0, 268, 0, 0, 0, 0,
ax_anim 2, 0, 269, 0, 0, 0, 0,
ax_anim 2, 0, 270, 0, 0, 0, 0,
ax_anim 2, 0, 263, 0, 0, 0, 0,
ax_anim 2, 0, 264, 0, 0, 0, 0,
ax_anim 2, 0, 265, 0, 0, 0, 0,
ax_anim 2, 2, 266, 0, 0, 0, 0,
ax_anim_terminator
sShuppetAnims_13_7:
ax_anim 2, 0, 265, 0, 0, 0, 0,
ax_anim 2, 0, 266, 0, 0, 0, 0,
ax_anim 2, 0, 267, 0, 0, 0, 0,
ax_anim 2, 0, 268, 0, 0, 0, 0,
ax_anim 2, 0, 269, 0, 0, 0, 0,
ax_anim 2, 0, 270, 0, 0, 0, 0,
ax_anim 2, 0, 263, 0, 0, 0, 0,
ax_anim 2, 0, 264, 0, 0, 0, 0,
ax_anim 2, 2, 265, 0, 0, 0, 0,
ax_anim_terminator
sShuppetAnims_13_8:
ax_anim 2, 0, 264, 0, 0, 0, 0,
ax_anim 2, 0, 265, 0, 0, 0, 0,
ax_anim 2, 0, 266, 0, 0, 0, 0,
ax_anim 2, 0, 267, 0, 0, 0, 0,
ax_anim 2, 0, 268, 0, 0, 0, 0,
ax_anim 2, 0, 269, 0, 0, 0, 0,
ax_anim 2, 0, 270, 0, 0, 0, 0,
ax_anim 2, 0, 263, 0, 0, 0, 0,
ax_anim 2, 2, 264, 0, 0, 0, 0,
ax_anim_terminator
sShuppetGfx1:
.incbin "baserom.gba", 0x1493010, 0x200
sShuppetSprites1:
ax_sprite sShuppetGfx1, 0x200
ax_sprite_terminator
sShuppetGfx2:
.incbin "baserom.gba", 0x1493220, 0x200
sShuppetSprites2:
ax_sprite sShuppetGfx2, 0x200
ax_sprite_terminator
sShuppetGfx3:
.incbin "baserom.gba", 0x1493430, 0x200
sShuppetSprites3:
ax_sprite sShuppetGfx3, 0x200
ax_sprite_terminator
sShuppetGfx4:
.incbin "baserom.gba", 0x1493640, 0x200
sShuppetSprites4:
ax_sprite sShuppetGfx4, 0x200
ax_sprite_terminator
sShuppetGfx5:
.incbin "baserom.gba", 0x1493850, 0x200
sShuppetSprites5:
ax_sprite sShuppetGfx5, 0x200
ax_sprite_terminator
sShuppetGfx6:
.incbin "baserom.gba", 0x1493A60, 0x200
sShuppetSprites6:
ax_sprite sShuppetGfx6, 0x200
ax_sprite_terminator
sShuppetGfx7:
.incbin "baserom.gba", 0x1493C70, 0x200
sShuppetSprites7:
ax_sprite sShuppetGfx7, 0x200
ax_sprite_terminator
sShuppetGfx8:
.incbin "baserom.gba", 0x1493E80, 0x200
sShuppetSprites8:
ax_sprite sShuppetGfx8, 0x200
ax_sprite_terminator
sShuppetGfx9:
.incbin "baserom.gba", 0x1494090, 0x200
sShuppetSprites9:
ax_sprite sShuppetGfx9, 0x200
ax_sprite_terminator
sShuppetGfx10:
.incbin "baserom.gba", 0x14942A0, 0x200
sShuppetSprites10:
ax_sprite sShuppetGfx10, 0x200
ax_sprite_terminator
sShuppetGfx11:
.incbin "baserom.gba", 0x14944B0, 0x200
sShuppetSprites11:
ax_sprite sShuppetGfx11, 0x200
ax_sprite_terminator
sShuppetGfx12:
.incbin "baserom.gba", 0x14946C0, 0x200
sShuppetSprites12:
ax_sprite sShuppetGfx12, 0x200
ax_sprite_terminator
sShuppetGfx13:
.incbin "baserom.gba", 0x14948D0, 0x100
sShuppetSprites13:
ax_sprite sShuppetGfx13, 0x100
ax_sprite_terminator
sShuppetGfx14:
.incbin "baserom.gba", 0x14949E0, 0x100
sShuppetSprites14:
ax_sprite sShuppetGfx14, 0x100
ax_sprite_terminator
sShuppetGfx15:
.incbin "baserom.gba", 0x1494AF0, 0x100
sShuppetSprites15:
ax_sprite sShuppetGfx15, 0x100
ax_sprite_terminator
sShuppetGfx16:
.incbin "baserom.gba", 0x1494C00, 0x40
sShuppetGfx16_1:
.incbin "baserom.gba", 0x1494C40, 0x40
sShuppetGfx16_2:
.incbin "baserom.gba", 0x1494C80, 0x40
sShuppetSprites16:
ax_sprite sShuppetGfx16, 0x40
ax_sprite 0, 0x40
ax_sprite sShuppetGfx16_1, 0x40
ax_sprite 0, 0x40
ax_sprite sShuppetGfx16_2, 0x40
ax_sprite 0, 0xc0
ax_sprite_terminator
sShuppetGfx17:
.incbin "baserom.gba", 0x1494CF8, 0x40
sShuppetGfx17_1:
.incbin "baserom.gba", 0x1494D38, 0x60
sShuppetGfx17_2:
.incbin "baserom.gba", 0x1494D98, 0x40
sShuppetSprites17:
ax_sprite 0, 0x20
ax_sprite sShuppetGfx17, 0x40
ax_sprite 0, 0x40
ax_sprite sShuppetGfx17_1, 0x60
ax_sprite 0, 0x20
ax_sprite sShuppetGfx17_2, 0x40
ax_sprite 0, 0xa0
ax_sprite_terminator
sShuppetGfx18:
.incbin "baserom.gba", 0x1494E18, 0x20
sShuppetSprites18:
ax_sprite sShuppetGfx18, 0x20
ax_sprite_terminator
sShuppetGfx19:
.incbin "baserom.gba", 0x1494E48, 0x20
sShuppetSprites19:
ax_sprite sShuppetGfx19, 0x20
ax_sprite_terminator
sShuppetGfx20:
.incbin "baserom.gba", 0x1494E78, 0x80
sShuppetSprites20:
ax_sprite sShuppetGfx20, 0x80
ax_sprite_terminator
sShuppetGfx21:
.incbin "baserom.gba", 0x1494F08, 0x60
sShuppetSprites21:
ax_sprite 0, 0x20
ax_sprite sShuppetGfx21, 0x60
ax_sprite_terminator
sShuppetGfx22:
.incbin "baserom.gba", 0x1494F80, 0x60
sShuppetSprites22:
ax_sprite 0, 0x20
ax_sprite sShuppetGfx22, 0x60
ax_sprite_terminator
sShuppetGfx23:
.incbin "baserom.gba", 0x1494FF8, 0x20
sShuppetSprites23:
ax_sprite sShuppetGfx23, 0x20
ax_sprite_terminator
sShuppetGfx24:
.incbin "baserom.gba", 0x1495028, 0x40
sShuppetGfx24_1:
.incbin "baserom.gba", 0x1495068, 0x60
sShuppetGfx24_2:
.incbin "baserom.gba", 0x14950C8, 0x60
sShuppetSprites24:
ax_sprite 0, 0x20
ax_sprite sShuppetGfx24, 0x40
ax_sprite 0, 0x20
ax_sprite sShuppetGfx24_1, 0x60
ax_sprite 0, 0x20
ax_sprite sShuppetGfx24_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sShuppetGfx25:
.incbin "baserom.gba", 0x1495168, 0x60
sShuppetGfx25_1:
.incbin "baserom.gba", 0x14951C8, 0x60
sShuppetGfx25_2:
.incbin "baserom.gba", 0x1495228, 0x40
sShuppetSprites25:
ax_sprite sShuppetGfx25, 0x60
ax_sprite 0, 0x20
ax_sprite sShuppetGfx25_1, 0x60
ax_sprite 0, 0x40
ax_sprite sShuppetGfx25_2, 0x40
ax_sprite 0, 0xa0
ax_sprite_terminator
sShuppetGfx26:
.incbin "baserom.gba", 0x14952A0, 0x100
sShuppetSprites26:
ax_sprite sShuppetGfx26, 0x100
ax_sprite_terminator
sShuppetGfx27:
.incbin "baserom.gba", 0x14953B0, 0x100
sShuppetSprites27:
ax_sprite sShuppetGfx27, 0x100
ax_sprite_terminator
sShuppetGfx28:
.incbin "baserom.gba", 0x14954C0, 0x200
sShuppetSprites28:
ax_sprite sShuppetGfx28, 0x200
ax_sprite_terminator
sShuppetGfx29:
.incbin "baserom.gba", 0x14956D0, 0x200
sShuppetSprites29:
ax_sprite sShuppetGfx29, 0x200
ax_sprite_terminator
sShuppetGfx30:
.incbin "baserom.gba", 0x14958E0, 0x200
sShuppetSprites30:
ax_sprite sShuppetGfx30, 0x200
ax_sprite_terminator
sShuppetGfx31:
.incbin "baserom.gba", 0x1495AF0, 0x200
sShuppetSprites31:
ax_sprite sShuppetGfx31, 0x200
ax_sprite_terminator
sShuppetGfx32:
.incbin "baserom.gba", 0x1495D00, 0x200
sShuppetSprites32:
ax_sprite sShuppetGfx32, 0x200
ax_sprite_terminator
sAxPosesShuppet:
.4byte sShuppetPose1
.4byte sShuppetPose2
.4byte sShuppetPose3
.4byte sShuppetPose4
.4byte sShuppetPose5
.4byte sShuppetPose6
.4byte sShuppetPose7
.4byte sShuppetPose8
.4byte sShuppetPose9
.4byte sShuppetPose10
.4byte sShuppetPose11
.4byte sShuppetPose12
.4byte sShuppetPose13
.4byte sShuppetPose14
.4byte sShuppetPose15
.4byte sShuppetPose16
.4byte sShuppetPose17
.4byte sShuppetPose18
.4byte sShuppetPose19
.4byte sShuppetPose20
.4byte sShuppetPose21
.4byte sShuppetPose22
.4byte sShuppetPose23
.4byte sShuppetPose24
.4byte sShuppetPose25
.4byte sShuppetPose26
.4byte sShuppetPose27
.4byte sShuppetPose28
.4byte sShuppetPose29
.4byte sShuppetPose30
.4byte sShuppetPose31
.4byte sShuppetPose32
.4byte sShuppetPose33
.4byte sShuppetPose34
.4byte sShuppetPose35
.4byte sShuppetPose36
.4byte sShuppetPose37
.4byte sShuppetPose38
.4byte sShuppetPose39
.4byte sShuppetPose40
.4byte sShuppetPose41
.4byte sShuppetPose42
.4byte sShuppetPose43
.4byte sShuppetPose44
.4byte sShuppetPose45
.4byte sShuppetPose46
.4byte sShuppetPose47
.4byte sShuppetPose48
.4byte sShuppetPose49
.4byte sShuppetPose50
.4byte sShuppetPose51
.4byte sShuppetPose52
.4byte sShuppetPose53
.4byte sShuppetPose54
.4byte sShuppetPose55
.4byte sShuppetPose56
.4byte sShuppetPose57
.4byte sShuppetPose58
.4byte sShuppetPose59
.4byte sShuppetPose60
.4byte sShuppetPose61
.4byte sShuppetPose62
.4byte sShuppetPose63
.4byte sShuppetPose64
.4byte sShuppetPose65
.4byte sShuppetPose66
.4byte sShuppetPose67
.4byte sShuppetPose68
.4byte sShuppetPose69
.4byte sShuppetPose70
.4byte sShuppetPose71
.4byte sShuppetPose72
.4byte sShuppetPose73
.4byte sShuppetPose74
.4byte sShuppetPose75
.4byte sShuppetPose76
.4byte sShuppetPose77
.4byte sShuppetPose78
.4byte sShuppetPose79
.4byte sShuppetPose80
.4byte sShuppetPose81
.4byte sShuppetPose82
.4byte sShuppetPose83
.4byte sShuppetPose84
.4byte sShuppetPose85
.4byte sShuppetPose86
.4byte sShuppetPose87
.4byte sShuppetPose88
.4byte sShuppetPose89
.4byte sShuppetPose90
.4byte sShuppetPose91
.4byte sShuppetPose92
.4byte sShuppetPose93
.4byte sShuppetPose94
.4byte sShuppetPose95
.4byte sShuppetPose96
.4byte sShuppetPose97
.4byte sShuppetPose98
.4byte sShuppetPose99
.4byte sShuppetPose100
.4byte sShuppetPose101
.4byte sShuppetPose102
.4byte sShuppetPose103
.4byte sShuppetPose104
.4byte sShuppetPose105
.4byte sShuppetPose106
.4byte sShuppetPose107
.4byte sShuppetPose108
.4byte sShuppetPose109
.4byte sShuppetPose110
.4byte sShuppetPose111
.4byte sShuppetPose112
.4byte sShuppetPose113
.4byte sShuppetPose114
.4byte sShuppetPose115
.4byte sShuppetPose116
.4byte sShuppetPose117
.4byte sShuppetPose118
.4byte sShuppetPose119
.4byte sShuppetPose120
.4byte sShuppetPose121
.4byte sShuppetPose122
.4byte sShuppetPose123
.4byte sShuppetPose124
.4byte sShuppetPose125
.4byte sShuppetPose126
.4byte sShuppetPose127
.4byte sShuppetPose128
.4byte sShuppetPose129
.4byte sShuppetPose130
.4byte sShuppetPose131
.4byte sShuppetPose132
.4byte sShuppetPose133
.4byte sShuppetPose134
.4byte sShuppetPose135
.4byte sShuppetPose136
.4byte sShuppetPose137
.4byte sShuppetPose138
.4byte sShuppetPose139
.4byte sShuppetPose140
.4byte sShuppetPose141
.4byte sShuppetPose142
.4byte sShuppetPose143
.4byte sShuppetPose144
.4byte sShuppetPose145
.4byte sShuppetPose146
.4byte sShuppetPose147
.4byte sShuppetPose148
.4byte sShuppetPose149
.4byte sShuppetPose150
.4byte sShuppetPose151
.4byte sShuppetPose152
.4byte sShuppetPose153
.4byte sShuppetPose154
.4byte sShuppetPose155
.4byte sShuppetPose156
.4byte sShuppetPose157
.4byte sShuppetPose158
.4byte sShuppetPose159
.4byte sShuppetPose160
.4byte sShuppetPose161
.4byte sShuppetPose162
.4byte sShuppetPose163
.4byte sShuppetPose164
.4byte sShuppetPose165
.4byte sShuppetPose166
.4byte sShuppetPose167
.4byte sShuppetPose168
.4byte sShuppetPose169
.4byte sShuppetPose170
.4byte sShuppetPose171
.4byte sShuppetPose172
.4byte sShuppetPose173
.4byte sShuppetPose174
.4byte sShuppetPose175
.4byte sShuppetPose176
.4byte sShuppetPose177
.4byte sShuppetPose178
.4byte sShuppetPose179
.4byte sShuppetPose180
.4byte sShuppetPose181
.4byte sShuppetPose182
.4byte sShuppetPose183
.4byte sShuppetPose184
.4byte sShuppetPose185
.4byte sShuppetPose186
.4byte sShuppetPose187
.4byte sShuppetPose188
.4byte sShuppetPose189
.4byte sShuppetPose190
.4byte sShuppetPose191
.4byte sShuppetPose192
.4byte sShuppetPose193
.4byte sShuppetPose194
.4byte sShuppetPose195
.4byte sShuppetPose196
.4byte sShuppetPose197
.4byte sShuppetPose198
.4byte sShuppetPose199
.4byte sShuppetPose200
.4byte sShuppetPose201
.4byte sShuppetPose202
.4byte sShuppetPose203
.4byte sShuppetPose204
.4byte sShuppetPose205
.4byte sShuppetPose206
.4byte sShuppetPose207
.4byte sShuppetPose208
.4byte sShuppetPose209
.4byte sShuppetPose210
.4byte sShuppetPose211
.4byte sShuppetPose212
.4byte sShuppetPose213
.4byte sShuppetPose214
.4byte sShuppetPose215
.4byte sShuppetPose216
.4byte sShuppetPose217
.4byte sShuppetPose218
.4byte sShuppetPose219
.4byte sShuppetPose220
.4byte sShuppetPose221
.4byte sShuppetPose222
.4byte sShuppetPose223
.4byte sShuppetPose224
.4byte sShuppetPose225
.4byte sShuppetPose226
.4byte sShuppetPose227
.4byte sShuppetPose228
.4byte sShuppetPose229
.4byte sShuppetPose230
.4byte sShuppetPose231
.4byte sShuppetPose232
.4byte sShuppetPose233
.4byte sShuppetPose234
.4byte sShuppetPose235
.4byte sShuppetPose236
.4byte sShuppetPose237
.4byte sShuppetPose238
.4byte sShuppetPose239
.4byte sShuppetPose240
.4byte sShuppetPose241
.4byte sShuppetPose242
.4byte sShuppetPose243
.4byte sShuppetPose244
.4byte sShuppetPose245
.4byte sShuppetPose246
.4byte sShuppetPose247
.4byte sShuppetPose248
.4byte sShuppetPose249
.4byte sShuppetPose250
.4byte sShuppetPose251
.4byte sShuppetPose252
.4byte sShuppetPose253
.4byte sShuppetPose254
.4byte sShuppetPose255
.4byte sShuppetPose256
.4byte sShuppetPose257
.4byte sShuppetPose258
.4byte sShuppetPose259
.4byte sShuppetPose260
.4byte sShuppetPose261
.4byte sShuppetPose262
.4byte sShuppetPose263
.4byte sShuppetPose264
.4byte sShuppetPose265
.4byte sShuppetPose266
.4byte sShuppetPose267
.4byte sShuppetPose268
.4byte sShuppetPose269
.4byte sShuppetPose270
.4byte sShuppetPose271
.4byte sShuppetPose272
.4byte sShuppetPose273
.4byte sShuppetPose274
.4byte sShuppetPose275
.4byte sShuppetPose276
.4byte sShuppetPose277
.4byte sShuppetPose278
.4byte sShuppetPose279
sAxPositionsShuppet:
.2byte   -1,   -8, 	  -5,   -8, 	   5,   -8, 	  -1,  -10
.2byte   -1,   -8, 	  -5,   -8, 	   5,   -8, 	  -1,  -10
.2byte   -1,   -8, 	  -5,   -7, 	   4,   -7, 	  -1,  -10
.2byte    5,   -8, 	   6,   -9, 	  -3,   -8, 	   2,  -10
.2byte    4,   -8, 	   6,   -9, 	  -4,   -7, 	   2,   -9
.2byte    5,   -8, 	   7,   -9, 	  -3,   -7, 	   2,   -9
.2byte    4,   -8, 	  -2,  -10, 	  -3,   -6, 	   0,  -11
.2byte    4,   -8, 	  -2,  -10, 	  -4,   -7, 	   0,  -11
.2byte    4,   -8, 	  -1,  -10, 	  -2,   -6, 	   0,  -11
.2byte    2,  -13, 	  -4,  -11, 	   1,   -6, 	   0,  -12
.2byte    2,  -14, 	  -5,  -11, 	   1,   -7, 	   0,  -11
.2byte    1,  -14, 	  -5,  -10, 	   1,   -7, 	   0,  -11
.2byte   -2,  -17, 	   2,   -9, 	  -5,   -9, 	  -1,  -12
.2byte   -2,  -17, 	   3,  -11, 	  -5,   -9, 	  -1,  -12
.2byte   -2,  -17, 	   3,  -10, 	  -4,   -9, 	  -1,  -12
.2byte   -4,  -13, 	   2,  -11, 	  -3,   -6, 	  -2,  -12
.2byte   -4,  -14, 	   3,  -11, 	  -3,   -7, 	  -2,  -11
.2byte   -3,  -14, 	   3,  -10, 	  -3,   -7, 	  -2,  -11
.2byte   -6,   -8, 	   0,  -10, 	   1,   -6, 	  -2,  -11
.2byte   -6,   -8, 	   0,  -10, 	   2,   -7, 	  -2,  -11
.2byte   -6,   -8, 	  -1,  -10, 	   0,   -6, 	  -2,  -11
.2byte   -7,   -8, 	  -8,   -9, 	   1,   -8, 	  -4,  -10
.2byte   -6,   -8, 	  -8,   -9, 	   2,   -7, 	  -4,   -9
.2byte   -7,   -8, 	  -9,   -9, 	   1,   -7, 	  -4,   -9
.2byte   -1,   -8, 	  -5,   -8, 	   5,   -8, 	  -1,  -10
.2byte   -1,   -8, 	  -5,   -8, 	   5,   -8, 	  -1,  -10
.2byte   -1,   -8, 	  -5,   -7, 	   4,   -7, 	  -1,  -10
.2byte    5,   -8, 	   6,   -9, 	  -3,   -8, 	   2,  -10
.2byte    4,   -8, 	   6,   -9, 	  -4,   -7, 	   2,   -9
.2byte    5,   -8, 	   7,   -9, 	  -3,   -7, 	   2,   -9
.2byte    4,   -8, 	  -2,  -10, 	  -3,   -6, 	   0,  -11
.2byte    4,   -8, 	  -2,  -10, 	  -4,   -7, 	   0,  -11
.2byte    4,   -8, 	  -1,  -10, 	  -2,   -6, 	   0,  -11
.2byte    2,  -13, 	  -4,  -11, 	   1,   -6, 	   0,  -12
.2byte    2,  -14, 	  -5,  -11, 	   1,   -7, 	   0,  -11
.2byte    1,  -14, 	  -5,  -10, 	   1,   -7, 	   0,  -11
.2byte   -2,  -17, 	   2,   -9, 	  -5,   -9, 	  -1,  -12
.2byte   -2,  -17, 	   3,  -11, 	  -5,   -9, 	  -1,  -12
.2byte   -2,  -17, 	   3,  -10, 	  -4,   -9, 	  -1,  -12
.2byte   -4,  -13, 	   2,  -11, 	  -3,   -6, 	  -2,  -12
.2byte   -4,  -14, 	   3,  -11, 	  -3,   -7, 	  -2,  -11
.2byte   -3,  -14, 	   3,  -10, 	  -3,   -7, 	  -2,  -11
.2byte   -6,   -8, 	   0,  -10, 	   1,   -6, 	  -2,  -11
.2byte   -6,   -8, 	   0,  -10, 	   2,   -7, 	  -2,  -11
.2byte   -6,   -8, 	  -1,  -10, 	   0,   -6, 	  -2,  -11
.2byte   -7,   -8, 	  -8,   -9, 	   1,   -8, 	  -4,  -10
.2byte   -6,   -8, 	  -8,   -9, 	   2,   -7, 	  -4,   -9
.2byte   -7,   -8, 	  -9,   -9, 	   1,   -7, 	  -4,   -9
.2byte   -1,   -8, 	  -5,   -8, 	   5,   -8, 	  -1,  -10
.2byte   -4,   -7, 	  -5,   -8, 	   4,   -7, 	  -1,   -9
.2byte   -4,   -7, 	   2,   -9, 	   3,   -5, 	   0,  -10
.2byte   -3,  -11, 	   3,   -9, 	  -2,   -4, 	  -1,  -10
.2byte   -1,  -15, 	   3,   -7, 	  -4,   -7, 	   0,  -10
.2byte    1,  -11, 	  -5,   -9, 	   0,   -4, 	  -1,  -10
.2byte    2,   -7, 	  -4,   -9, 	  -5,   -5, 	  -2,  -10
.2byte    2,   -7, 	   3,   -8, 	  -6,   -7, 	  -1,   -9
.2byte   -1,   -8, 	  -5,   -8, 	   5,   -8, 	  -1,  -10
.2byte   -7,   -8, 	  -8,   -9, 	   1,   -8, 	  -4,  -10
.2byte   -6,   -8, 	   0,  -10, 	   1,   -6, 	  -2,  -11
.2byte   -4,  -13, 	   2,  -11, 	  -3,   -6, 	  -2,  -12
.2byte   -2,  -17, 	   2,   -9, 	  -5,   -9, 	  -1,  -12
.2byte    2,  -13, 	  -4,  -11, 	   1,   -6, 	   0,  -12
.2byte    4,   -8, 	  -2,  -10, 	  -3,   -6, 	   0,  -11
.2byte    5,   -8, 	   6,   -9, 	  -3,   -8, 	   2,  -10
.2byte   -1,   -8, 	  -5,   -8, 	   5,   -8, 	  -1,  -10
.2byte   -4,   -7, 	  -5,   -8, 	   4,   -7, 	  -1,   -9
.2byte   -4,   -7, 	   2,   -9, 	   3,   -5, 	   0,  -10
.2byte   -3,  -11, 	   3,   -9, 	  -2,   -4, 	  -1,  -10
.2byte   -1,  -15, 	   3,   -7, 	  -4,   -7, 	   0,  -10
.2byte    1,  -11, 	  -5,   -9, 	   0,   -4, 	  -1,  -10
.2byte    2,   -7, 	  -4,   -9, 	  -5,   -5, 	  -2,  -10
.2byte    2,   -7, 	   3,   -8, 	  -6,   -7, 	  -1,   -9
.2byte   -1,   -8, 	  -5,   -8, 	   5,   -8, 	  -1,  -10
.2byte   -7,   -8, 	  -8,   -9, 	   1,   -8, 	  -4,  -10
.2byte   -6,   -8, 	   0,  -10, 	   1,   -6, 	  -2,  -11
.2byte   -4,  -13, 	   2,  -11, 	  -3,   -6, 	  -2,  -12
.2byte   -2,  -17, 	   2,   -9, 	  -5,   -9, 	  -1,  -12
.2byte    2,  -13, 	  -4,  -11, 	   1,   -6, 	   0,  -12
.2byte    4,   -8, 	  -2,  -10, 	  -3,   -6, 	   0,  -11
.2byte    5,   -8, 	   6,   -9, 	  -3,   -8, 	   2,  -10
.2byte   -1,   -8, 	  -5,   -8, 	   5,   -8, 	  -1,  -10
.2byte   -1,   -8, 	  -5,   -8, 	   5,   -8, 	  -1,  -10
.2byte   -1,   -8, 	  -5,   -7, 	   4,   -7, 	  -1,  -10
.2byte   -1,   -8, 	  -7,   -8, 	   5,   -8, 	  -1,  -10
.2byte   -1,   -8, 	  -7,   -8, 	   5,   -8, 	  -1,  -10
.2byte   -1,   -8, 	  -7,   -8, 	   5,   -8, 	  -1,  -10
.2byte   -1,   -8, 	  -7,   -8, 	   5,   -8, 	  -1,  -10
.2byte   -1,   -8, 	  -7,   -8, 	   5,   -8, 	  -1,  -10
.2byte   -1,   -8, 	  -7,   -8, 	   5,   -8, 	  -1,  -10
.2byte   -1,   -8, 	  -7,   -8, 	   5,   -8, 	  -1,  -10
.2byte   -1,   -8, 	  -7,   -8, 	   5,   -8, 	  -1,  -10
.2byte    5,   -8, 	   6,   -9, 	  -3,   -8, 	   2,  -10
.2byte    4,   -8, 	   6,   -9, 	  -4,   -7, 	   2,   -9
.2byte    5,   -8, 	   7,   -9, 	  -3,   -7, 	   2,   -9
.2byte    5,   -9, 	   7,  -10, 	  -3,   -7, 	   1,  -10
.2byte    5,   -9, 	   7,  -10, 	  -3,   -7, 	   1,  -10
.2byte    5,   -9, 	   7,  -10, 	  -3,   -7, 	   1,  -10
.2byte    5,   -9, 	   7,  -10, 	  -3,   -7, 	   1,  -10
.2byte    5,   -9, 	   7,  -10, 	  -3,   -7, 	   1,  -10
.2byte    5,   -9, 	   7,  -10, 	  -3,   -7, 	   1,  -10
.2byte    5,   -9, 	   7,  -10, 	  -3,   -7, 	   1,  -10
.2byte    5,   -9, 	   7,  -10, 	  -3,   -7, 	   1,  -10
.2byte    4,   -8, 	  -2,  -10, 	  -3,   -6, 	   0,  -11
.2byte    4,   -8, 	  -2,  -10, 	  -4,   -7, 	   0,  -11
.2byte    4,   -8, 	  -1,  -10, 	  -2,   -6, 	   0,  -11
.2byte    3,   -8, 	  -2,  -10, 	  -3,   -7, 	   0,  -10
.2byte    3,   -8, 	  -2,  -10, 	  -3,   -7, 	   0,  -10
.2byte    3,   -8, 	  -2,  -10, 	  -3,   -7, 	   0,  -10
.2byte    3,   -8, 	  -2,  -10, 	  -3,   -7, 	   0,  -10
.2byte    3,   -8, 	  -2,  -10, 	  -3,   -7, 	   0,  -10
.2byte    3,   -8, 	  -2,  -10, 	  -3,   -7, 	   0,  -10
.2byte    3,   -8, 	  -2,  -10, 	  -3,   -7, 	   0,  -10
.2byte    3,   -8, 	  -2,  -10, 	  -3,   -7, 	   0,  -10
.2byte    2,  -13, 	  -4,  -11, 	   1,   -6, 	   0,  -12
.2byte    2,  -14, 	  -5,  -11, 	   1,   -7, 	   0,  -11
.2byte    1,  -14, 	  -5,  -10, 	   1,   -7, 	   0,  -11
.2byte    1,  -14, 	  -5,  -10, 	   1,   -7, 	   0,  -11
.2byte    1,  -14, 	  -5,  -10, 	   1,   -7, 	   0,  -11
.2byte    1,  -14, 	  -5,  -10, 	   1,   -7, 	   0,  -11
.2byte    1,  -14, 	  -5,  -10, 	   1,   -7, 	   0,  -11
.2byte    1,  -14, 	  -5,  -10, 	   1,   -7, 	   0,  -11
.2byte    1,  -14, 	  -5,  -10, 	   1,   -7, 	   0,  -11
.2byte    1,  -14, 	  -5,  -10, 	   1,   -7, 	   0,  -11
.2byte   -2,  -17, 	   2,   -9, 	  -5,   -9, 	  -1,  -12
.2byte   -2,  -17, 	   3,  -11, 	  -5,   -9, 	  -1,  -12
.2byte   -2,  -17, 	   3,  -10, 	  -4,   -9, 	  -1,  -12
.2byte   -2,  -17, 	   3,  -10, 	  -4,   -9, 	  -1,  -12
.2byte   -2,  -17, 	   3,  -10, 	  -4,   -9, 	  -1,  -12
.2byte   -2,  -17, 	   3,  -10, 	  -4,   -9, 	  -1,  -12
.2byte   -2,  -17, 	   3,  -10, 	  -4,   -9, 	  -1,  -12
.2byte   -2,  -17, 	   3,  -10, 	  -4,   -9, 	  -1,  -12
.2byte   -2,  -17, 	   3,  -10, 	  -4,   -9, 	  -1,  -12
.2byte   -2,  -17, 	   3,  -10, 	  -4,   -9, 	  -1,  -12
.2byte   -4,  -13, 	   2,  -11, 	  -3,   -6, 	  -2,  -12
.2byte   -4,  -14, 	   3,  -11, 	  -3,   -7, 	  -2,  -11
.2byte   -3,  -14, 	   3,  -10, 	  -3,   -7, 	  -2,  -11
.2byte   -3,  -14, 	   3,  -10, 	  -3,   -7, 	  -2,  -11
.2byte   -3,  -14, 	   3,  -10, 	  -3,   -7, 	  -2,  -11
.2byte   -3,  -14, 	   3,  -10, 	  -3,   -7, 	  -2,  -11
.2byte   -3,  -14, 	   3,  -10, 	  -3,   -7, 	  -2,  -11
.2byte   -3,  -14, 	   3,  -10, 	  -3,   -7, 	  -2,  -11
.2byte   -3,  -14, 	   3,  -10, 	  -3,   -7, 	  -2,  -11
.2byte   -3,  -14, 	   3,  -10, 	  -3,   -7, 	  -2,  -11
.2byte   -6,   -8, 	   0,  -10, 	   1,   -6, 	  -2,  -11
.2byte   -6,   -8, 	   0,  -10, 	   2,   -7, 	  -2,  -11
.2byte   -6,   -8, 	  -1,  -10, 	   0,   -6, 	  -2,  -11
.2byte   -5,   -8, 	   0,  -10, 	   1,   -7, 	  -2,  -10
.2byte   -5,   -8, 	   0,  -10, 	   1,   -7, 	  -2,  -10
.2byte   -5,   -8, 	   0,  -10, 	   1,   -7, 	  -2,  -10
.2byte   -5,   -8, 	   0,  -10, 	   1,   -7, 	  -2,  -10
.2byte   -5,   -8, 	   0,  -10, 	   1,   -7, 	  -2,  -10
.2byte   -5,   -8, 	   0,  -10, 	   1,   -7, 	  -2,  -10
.2byte   -5,   -8, 	   0,  -10, 	   1,   -7, 	  -2,  -10
.2byte   -5,   -8, 	   0,  -10, 	   1,   -7, 	  -2,  -10
.2byte   -7,   -8, 	  -8,   -9, 	   1,   -8, 	  -4,  -10
.2byte   -6,   -8, 	  -8,   -9, 	   2,   -7, 	  -4,   -9
.2byte   -7,   -8, 	  -9,   -9, 	   1,   -7, 	  -4,   -9
.2byte   -7,   -9, 	  -9,  -10, 	   1,   -7, 	  -3,  -10
.2byte   -7,   -9, 	  -9,  -10, 	   1,   -7, 	  -3,  -10
.2byte   -7,   -9, 	  -9,  -10, 	   1,   -7, 	  -3,  -10
.2byte   -7,   -9, 	  -9,  -10, 	   1,   -7, 	  -3,  -10
.2byte   -7,   -9, 	  -9,  -10, 	   1,   -7, 	  -3,  -10
.2byte   -7,   -9, 	  -9,  -10, 	   1,   -7, 	  -3,  -10
.2byte   -7,   -9, 	  -9,  -10, 	   1,   -7, 	  -3,  -10
.2byte   -7,   -9, 	  -9,  -10, 	   1,   -7, 	  -3,  -10
.2byte    0,   -8, 	  -4,   -6, 	   3,   -6, 	  -1,  -10
.2byte    0,   -9, 	  -4,   -7, 	   3,   -6, 	  -1,  -11
.2byte    0,   -9, 	  -4,   -7, 	   4,   -7, 	   0,  -10
.2byte    2,  -10, 	   4,   -9, 	  -4,   -5, 	  -2,  -10
.2byte    3,  -11, 	   1,   -9, 	   1,   -4, 	  -1,   -8
.2byte    1,  -13, 	  -1,   -8, 	   5,   -7, 	   0,   -8
.2byte    0,  -13, 	   5,   -8, 	  -6,   -8, 	   0,   -8
.2byte   -2,  -13, 	   0,   -8, 	  -6,   -7, 	  -1,   -8
.2byte   -4,  -11, 	  -2,   -9, 	  -2,   -4, 	   0,   -8
.2byte   -3,  -10, 	  -5,   -9, 	   3,   -5, 	   1,  -10
.2byte   -1,   -8, 	  -5,   -8, 	   5,   -8, 	  -1,  -10
.2byte   -1,   -8, 	  -5,   -8, 	   5,   -8, 	  -1,  -10
.2byte   -1,   -8, 	  -5,   -7, 	   4,   -7, 	  -1,  -10
.2byte    5,   -8, 	   6,   -9, 	  -3,   -8, 	   2,  -10
.2byte    4,   -8, 	   6,   -9, 	  -4,   -7, 	   2,   -9
.2byte    5,   -8, 	   7,   -9, 	  -3,   -7, 	   2,   -9
.2byte    4,   -8, 	  -2,  -10, 	  -3,   -6, 	   0,  -11
.2byte    4,   -8, 	  -2,  -10, 	  -4,   -7, 	   0,  -11
.2byte    4,   -8, 	  -1,  -10, 	  -2,   -6, 	   0,  -11
.2byte    2,  -13, 	  -4,  -11, 	   1,   -6, 	   0,  -12
.2byte    2,  -14, 	  -5,  -11, 	   1,   -7, 	   0,  -11
.2byte    1,  -14, 	  -5,  -10, 	   1,   -7, 	   0,  -11
.2byte   -2,  -17, 	   2,   -9, 	  -5,   -9, 	  -1,  -12
.2byte   -2,  -17, 	   3,  -11, 	  -5,   -9, 	  -1,  -12
.2byte   -2,  -17, 	   3,  -10, 	  -4,   -9, 	  -1,  -12
.2byte   -4,  -13, 	   2,  -11, 	  -3,   -6, 	  -2,  -12
.2byte   -4,  -14, 	   3,  -11, 	  -3,   -7, 	  -2,  -11
.2byte   -3,  -14, 	   3,  -10, 	  -3,   -7, 	  -2,  -11
.2byte   -6,   -8, 	   0,  -10, 	   1,   -6, 	  -2,  -11
.2byte   -6,   -8, 	   0,  -10, 	   2,   -7, 	  -2,  -11
.2byte   -6,   -8, 	  -1,  -10, 	   0,   -6, 	  -2,  -11
.2byte   -7,   -8, 	  -8,   -9, 	   1,   -8, 	  -4,  -10
.2byte   -6,   -8, 	  -8,   -9, 	   2,   -7, 	  -4,   -9
.2byte   -7,   -8, 	  -9,   -9, 	   1,   -7, 	  -4,   -9
.2byte   -1,   -8, 	  -5,   -8, 	   5,   -8, 	  -1,  -10
.2byte   -4,   -7, 	  -5,   -8, 	   4,   -7, 	  -1,   -9
.2byte   -4,   -7, 	   2,   -9, 	   3,   -5, 	   0,  -10
.2byte   -3,  -11, 	   3,   -9, 	  -2,   -4, 	  -1,  -10
.2byte   -1,  -15, 	   3,   -7, 	  -4,   -7, 	   0,  -10
.2byte    1,  -11, 	  -5,   -9, 	   0,   -4, 	  -1,  -10
.2byte    2,   -7, 	  -4,   -9, 	  -5,   -5, 	  -2,  -10
.2byte    2,   -7, 	   3,   -8, 	  -6,   -7, 	  -1,   -9
.2byte   -1,   -8, 	  -5,   -8, 	   5,   -8, 	  -1,  -10
.2byte   -7,   -8, 	  -8,   -9, 	   1,   -8, 	  -4,  -10
.2byte   -6,   -8, 	   0,  -10, 	   1,   -6, 	  -2,  -11
.2byte   -4,  -13, 	   2,  -11, 	  -3,   -6, 	  -2,  -12
.2byte   -2,  -17, 	   2,   -9, 	  -5,   -9, 	  -1,  -12
.2byte    2,  -13, 	  -4,  -11, 	   1,   -6, 	   0,  -12
.2byte    4,   -8, 	  -2,  -10, 	  -3,   -6, 	   0,  -11
.2byte    5,   -8, 	   6,   -9, 	  -3,   -8, 	   2,  -10
.2byte   -1,   -8, 	  -5,   -8, 	   5,   -8, 	  -1,  -10
.2byte    2,   -7, 	   3,   -8, 	  -6,   -7, 	  -1,   -9
.2byte    2,   -7, 	  -4,   -9, 	  -5,   -5, 	  -2,  -10
.2byte    1,  -11, 	  -5,   -9, 	   0,   -4, 	  -1,  -10
.2byte   -1,  -15, 	   3,   -7, 	  -4,   -7, 	   0,  -10
.2byte   -3,  -11, 	   3,   -9, 	  -2,   -4, 	  -1,  -10
.2byte   -4,   -7, 	   2,   -9, 	   3,   -5, 	   0,  -10
.2byte   -4,   -7, 	  -5,   -8, 	   4,   -7, 	  -1,   -9
.2byte   -1,   -8, 	  -5,   -8, 	   5,   -8, 	  -1,  -10
.2byte   -1,   -8, 	  -5,   -8, 	   5,   -8, 	  -1,  -10
.2byte   -1,   -8, 	  -5,   -7, 	   4,   -7, 	  -1,  -10
.2byte    3,   -8, 	   4,   -9, 	  -5,   -8, 	   0,  -10
.2byte    2,   -8, 	   4,   -9, 	  -6,   -7, 	   0,   -9
.2byte    3,   -8, 	   5,   -9, 	  -5,   -7, 	   0,   -9
.2byte    2,   -8, 	  -4,  -10, 	  -5,   -6, 	  -2,  -11
.2byte    2,   -8, 	  -4,  -10, 	  -6,   -7, 	  -2,  -11
.2byte    2,   -8, 	  -3,  -10, 	  -4,   -6, 	  -2,  -11
.2byte    1,  -13, 	  -5,  -11, 	   0,   -6, 	  -1,  -12
.2byte    1,  -14, 	  -6,  -11, 	   0,   -7, 	  -1,  -11
.2byte    0,  -14, 	  -6,  -10, 	   0,   -7, 	  -1,  -11
.2byte   -2,  -17, 	   2,   -9, 	  -5,   -9, 	  -1,  -12
.2byte   -2,  -17, 	   3,  -11, 	  -5,   -9, 	  -1,  -12
.2byte   -2,  -17, 	   3,  -10, 	  -4,   -9, 	  -1,  -12
.2byte   -3,  -13, 	   3,  -11, 	  -2,   -6, 	  -1,  -12
.2byte   -3,  -14, 	   4,  -11, 	  -2,   -7, 	  -1,  -11
.2byte   -2,  -14, 	   4,  -10, 	  -2,   -7, 	  -1,  -11
.2byte   -4,   -8, 	   2,  -10, 	   3,   -6, 	   0,  -11
.2byte   -4,   -8, 	   2,  -10, 	   4,   -7, 	   0,  -11
.2byte   -4,   -8, 	   1,  -10, 	   2,   -6, 	   0,  -11
.2byte   -5,   -8, 	  -6,   -9, 	   3,   -8, 	  -2,  -10
.2byte   -4,   -8, 	  -6,   -9, 	   4,   -7, 	  -2,   -9
.2byte   -5,   -8, 	  -7,   -9, 	   3,   -7, 	  -2,   -9
.2byte   -1,   -8, 	  -5,   -8, 	   5,   -8, 	  -1,  -10
.2byte   -4,   -7, 	  -5,   -8, 	   4,   -7, 	  -1,   -9
.2byte   -4,   -7, 	   2,   -9, 	   3,   -5, 	   0,  -10
.2byte   -3,  -11, 	   3,   -9, 	  -2,   -4, 	  -1,  -10
.2byte   -1,  -15, 	   3,   -7, 	  -4,   -7, 	   0,  -10
.2byte    1,  -11, 	  -5,   -9, 	   0,   -4, 	  -1,  -10
.2byte    2,   -7, 	  -4,   -9, 	  -5,   -5, 	  -2,  -10
.2byte    2,   -7, 	   3,   -8, 	  -6,   -7, 	  -1,   -9
.2byte   -1,   -8, 	  -5,   -8, 	   5,   -8, 	  -1,  -10
.2byte   -7,   -8, 	  -8,   -9, 	   1,   -8, 	  -4,  -10
.2byte   -6,   -8, 	   0,  -10, 	   1,   -6, 	  -2,  -11
.2byte   -4,  -13, 	   2,  -11, 	  -3,   -6, 	  -2,  -12
.2byte   -2,  -17, 	   2,   -9, 	  -5,   -9, 	  -1,  -12
.2byte    2,  -13, 	  -4,  -11, 	   1,   -6, 	   0,  -12
.2byte    4,   -8, 	  -2,  -10, 	  -3,   -6, 	   0,  -11
.2byte    5,   -8, 	   6,   -9, 	  -3,   -8, 	   2,  -10
.2byte   -1,   -8, 	  -5,   -8, 	   5,   -8, 	  -1,  -10
.2byte   -7,   -8, 	  -8,   -9, 	   1,   -8, 	  -4,  -10
.2byte   -6,   -8, 	   0,  -10, 	   1,   -6, 	  -2,  -11
.2byte   -4,  -13, 	   2,  -11, 	  -3,   -6, 	  -2,  -12
.2byte   -2,  -17, 	   2,   -9, 	  -5,   -9, 	  -1,  -12
.2byte    2,  -13, 	  -4,  -11, 	   1,   -6, 	   0,  -12
.2byte    4,   -8, 	  -2,  -10, 	  -3,   -6, 	   0,  -11
.2byte    5,   -8, 	   6,   -9, 	  -3,   -8, 	   2,  -10
.2byte   -1,   -8, 	  -5,   -8, 	   5,   -8, 	  -1,  -10
.2byte   -7,   -8, 	  -8,   -9, 	   1,   -8, 	  -4,  -10
.2byte   -6,   -8, 	   0,  -10, 	   1,   -6, 	  -2,  -11
.2byte   -4,  -13, 	   2,  -11, 	  -3,   -6, 	  -2,  -12
.2byte   -2,  -17, 	   2,   -9, 	  -5,   -9, 	  -1,  -12
.2byte    2,  -13, 	  -4,  -11, 	   1,   -6, 	   0,  -12
.2byte    4,   -8, 	  -2,  -10, 	  -3,   -6, 	   0,  -11
.2byte    5,   -8, 	   6,   -9, 	  -3,   -8, 	   2,  -10
sShuppetAnimTable1:
.4byte sShuppetAnims_1_1
.4byte sShuppetAnims_1_2
.4byte sShuppetAnims_1_3
.4byte sShuppetAnims_1_4
.4byte sShuppetAnims_1_5
.4byte sShuppetAnims_1_6
.4byte sShuppetAnims_1_7
.4byte sShuppetAnims_1_8
sShuppetAnimTable2:
.4byte sShuppetAnims_2_1
.4byte sShuppetAnims_2_2
.4byte sShuppetAnims_2_3
.4byte sShuppetAnims_2_4
.4byte sShuppetAnims_2_5
.4byte sShuppetAnims_2_6
.4byte sShuppetAnims_2_7
.4byte sShuppetAnims_2_8
sShuppetAnimTable3:
.4byte sShuppetAnims_3_1
.4byte sShuppetAnims_3_2
.4byte sShuppetAnims_3_3
.4byte sShuppetAnims_3_4
.4byte sShuppetAnims_3_5
.4byte sShuppetAnims_3_6
.4byte sShuppetAnims_3_7
.4byte sShuppetAnims_3_8
sShuppetAnimTable4:
.4byte sShuppetAnims_4_1
.4byte sShuppetAnims_4_2
.4byte sShuppetAnims_4_3
.4byte sShuppetAnims_4_4
.4byte sShuppetAnims_4_5
.4byte sShuppetAnims_4_6
.4byte sShuppetAnims_4_7
.4byte sShuppetAnims_4_8
sShuppetAnimTable5:
.4byte sShuppetAnims_5_1
.4byte sShuppetAnims_5_2
.4byte sShuppetAnims_5_3
.4byte sShuppetAnims_5_4
.4byte sShuppetAnims_5_5
.4byte sShuppetAnims_5_6
.4byte sShuppetAnims_5_7
.4byte sShuppetAnims_5_8
sShuppetAnimTable6:
.4byte sShuppetAnims_6_1
.4byte sShuppetAnims_6_1
.4byte sShuppetAnims_6_1
.4byte sShuppetAnims_6_1
.4byte sShuppetAnims_6_1
.4byte sShuppetAnims_6_1
.4byte sShuppetAnims_6_1
.4byte sShuppetAnims_6_1
sShuppetAnimTable7:
.4byte sShuppetAnims_7_1
.4byte sShuppetAnims_7_2
.4byte sShuppetAnims_7_3
.4byte sShuppetAnims_7_4
.4byte sShuppetAnims_7_5
.4byte sShuppetAnims_7_6
.4byte sShuppetAnims_7_7
.4byte sShuppetAnims_7_8
sShuppetAnimTable8:
.4byte sShuppetAnims_8_1
.4byte sShuppetAnims_8_2
.4byte sShuppetAnims_8_3
.4byte sShuppetAnims_8_4
.4byte sShuppetAnims_8_5
.4byte sShuppetAnims_8_6
.4byte sShuppetAnims_8_7
.4byte sShuppetAnims_8_8
sShuppetAnimTable9:
.4byte sShuppetAnims_9_1
.4byte sShuppetAnims_9_2
.4byte sShuppetAnims_9_3
.4byte sShuppetAnims_9_4
.4byte sShuppetAnims_9_5
.4byte sShuppetAnims_9_6
.4byte sShuppetAnims_9_7
.4byte sShuppetAnims_9_8
sShuppetAnimTable10:
.4byte sShuppetAnims_10_1
.4byte sShuppetAnims_10_2
.4byte sShuppetAnims_10_3
.4byte sShuppetAnims_10_4
.4byte sShuppetAnims_10_5
.4byte sShuppetAnims_10_6
.4byte sShuppetAnims_10_7
.4byte sShuppetAnims_10_8
sShuppetAnimTable11:
.4byte sShuppetAnims_11_1
.4byte sShuppetAnims_11_2
.4byte sShuppetAnims_11_3
.4byte sShuppetAnims_11_4
.4byte sShuppetAnims_11_5
.4byte sShuppetAnims_11_6
.4byte sShuppetAnims_11_7
.4byte sShuppetAnims_11_8
sShuppetAnimTable12:
.4byte sShuppetAnims_12_1
.4byte sShuppetAnims_12_2
.4byte sShuppetAnims_12_3
.4byte sShuppetAnims_12_4
.4byte sShuppetAnims_12_5
.4byte sShuppetAnims_12_6
.4byte sShuppetAnims_12_7
.4byte sShuppetAnims_12_8
sShuppetAnimTable13:
.4byte sShuppetAnims_13_1
.4byte sShuppetAnims_13_2
.4byte sShuppetAnims_13_3
.4byte sShuppetAnims_13_4
.4byte sShuppetAnims_13_5
.4byte sShuppetAnims_13_6
.4byte sShuppetAnims_13_7
.4byte sShuppetAnims_13_8
sAxAnimationsShuppet:
.4byte sShuppetAnimTable1
.4byte sShuppetAnimTable2
.4byte sShuppetAnimTable3
.4byte sShuppetAnimTable4
.4byte sShuppetAnimTable5
.4byte sShuppetAnimTable6
.4byte sShuppetAnimTable7
.4byte sShuppetAnimTable8
.4byte sShuppetAnimTable9
.4byte sShuppetAnimTable10
.4byte sShuppetAnimTable11
.4byte sShuppetAnimTable12
.4byte sShuppetAnimTable13
sAxSpritesShuppet:
.4byte sShuppetSprites1
.4byte sShuppetSprites2
.4byte sShuppetSprites3
.4byte sShuppetSprites4
.4byte sShuppetSprites5
.4byte sShuppetSprites6
.4byte sShuppetSprites7
.4byte sShuppetSprites8
.4byte sShuppetSprites9
.4byte sShuppetSprites10
.4byte sShuppetSprites11
.4byte sShuppetSprites12
.4byte sShuppetSprites13
.4byte sShuppetSprites14
.4byte sShuppetSprites15
.4byte sShuppetSprites16
.4byte sShuppetSprites17
.4byte sShuppetSprites18
.4byte sShuppetSprites19
.4byte sShuppetSprites20
.4byte sShuppetSprites21
.4byte sShuppetSprites22
.4byte sShuppetSprites23
.4byte sShuppetSprites24
.4byte sShuppetSprites25
.4byte sShuppetSprites26
.4byte sShuppetSprites27
.4byte sShuppetSprites28
.4byte sShuppetSprites29
.4byte sShuppetSprites30
.4byte sShuppetSprites31
.4byte sShuppetSprites32
sAxMainShuppet:
ax_main sAxPosesShuppet, sAxAnimationsShuppet, 13, sAxSpritesShuppet, sAxPositionsShuppet
