.global gAxSpheal
gAxSpheal:
ax_siro sAxMainSpheal
sSphealPose1:
ax_pose 0, 0x41f1, 0x80f5, 0x5c00
ax_pose_terminator
sSphealPose2:
ax_pose 1, 0x41f1, 0xa0f5, 0x5c00
ax_pose_terminator
sSphealPose3:
ax_pose 1, 0x41f2, 0x80f5, 0x5c00
ax_pose_terminator
sSphealPose4:
ax_pose 0, 0x41f2, 0xa0f5, 0x5c00
ax_pose_terminator
sSphealPose5:
ax_pose 2, 0x41f0, 0x80f4, 0x5c00
ax_pose_terminator
sSphealPose6:
ax_pose 3, 0x41f3, 0xa0f4, 0x5c00
ax_pose_terminator
sSphealPose7:
ax_pose 4, 0x41f2, 0x80f4, 0x5c00
ax_pose_terminator
sSphealPose8:
ax_pose 5, 0x01e9, 0xa0f4, 0x5c00
ax_pose_terminator
sSphealPose9:
ax_pose 5, 0x01ea, 0x80f4, 0x5c00
ax_pose_terminator
sSphealPose10:
ax_pose 4, 0x41f1, 0xa0f4, 0x5c00
ax_pose_terminator
sSphealPose11:
ax_pose 6, 0x41f1, 0x80f4, 0x5c00
ax_pose_terminator
sSphealPose12:
ax_pose 7, 0x01ee, 0x80f4, 0x5c00
ax_pose_terminator
sSphealPose13:
ax_pose 8, 0x01f2, 0x40f8, 0x5c00
ax_pose_terminator
sSphealPose14:
ax_pose 9, 0x01e9, 0xa0f0, 0x5c00
ax_pose_terminator
sSphealPose15:
ax_pose 9, 0x01ea, 0x80f0, 0x5c00
ax_pose_terminator
sSphealPose16:
ax_pose 8, 0x01f1, 0x60f8, 0x5c00
ax_pose_terminator
sSphealPose17:
ax_pose 9, 0x01e9, 0x90f0, 0x5c00
ax_pose_terminator
sSphealPose18:
ax_pose 9, 0x01e9, 0xb0f0, 0x5c00
ax_pose_terminator
sSphealPose19:
ax_pose 4, 0x41f2, 0x90ec, 0x5c00
ax_pose_terminator
sSphealPose20:
ax_pose 5, 0x01e9, 0xb0ec, 0x5c00
ax_pose_terminator
sSphealPose21:
ax_pose 5, 0x01ea, 0x90ec, 0x5c00
ax_pose_terminator
sSphealPose22:
ax_pose 4, 0x41f1, 0xb0ec, 0x5c00
ax_pose_terminator
sSphealPose23:
ax_pose 6, 0x41f1, 0x90ec, 0x5c00
ax_pose_terminator
sSphealPose24:
ax_pose 7, 0x01ee, 0x90ec, 0x5c00
ax_pose_terminator
sSphealPose25:
ax_pose 0, 0x41f1, 0x90eb, 0x5c00
ax_pose_terminator
sSphealPose26:
ax_pose 1, 0x41f1, 0xb0eb, 0x5c00
ax_pose_terminator
sSphealPose27:
ax_pose 1, 0x41f2, 0x90eb, 0x5c00
ax_pose_terminator
sSphealPose28:
ax_pose 0, 0x41f2, 0xb0eb, 0x5c00
ax_pose_terminator
sSphealPose29:
ax_pose 2, 0x41f0, 0x90ec, 0x5c00
ax_pose_terminator
sSphealPose30:
ax_pose 3, 0x41f3, 0xb0ec, 0x5c00
ax_pose_terminator
sSphealPose31:
ax_pose 10, 0x41f2, 0x90ec, 0x5c00
ax_pose_terminator
sSphealPose32:
ax_pose 11, 0x41f2, 0x90eb, 0x5c00
ax_pose_terminator
sSphealPose33:
ax_pose 12, 0x41f2, 0x90ec, 0x5c00
ax_pose_terminator
sSphealPose34:
ax_pose 13, 0x01f1, 0x90eb, 0x5c00
ax_pose_terminator
sSphealPose35:
ax_pose 14, 0x81ec, 0x90f7, 0x5c00
ax_pose_terminator
sSphealPose36:
ax_pose 15, 0x01ed, 0x90e9, 0x5c00
ax_pose_terminator
sSphealPose37:
ax_pose 16, 0x01f2, 0x40f8, 0x5c00
ax_pose_terminator
sSphealPose38:
ax_pose 17, 0x01e8, 0xa0f0, 0x5c00
ax_pose_terminator
sSphealPose39:
ax_pose 17, 0x01e9, 0x80f0, 0x5c00
ax_pose_terminator
sSphealPose40:
ax_pose 16, 0x01f1, 0x60f8, 0x5c00
ax_pose_terminator
sSphealPose41:
ax_pose 17, 0x01e9, 0x90f0, 0x5c00
ax_pose_terminator
sSphealPose42:
ax_pose 17, 0x01e9, 0xb0f0, 0x5c00
ax_pose_terminator
sSphealPose43:
ax_pose 10, 0x41f2, 0x80f4, 0x5c00
ax_pose_terminator
sSphealPose44:
ax_pose 11, 0x41f2, 0x80f5, 0x5c00
ax_pose_terminator
sSphealPose45:
ax_pose 12, 0x41f2, 0x80f4, 0x5c00
ax_pose_terminator
sSphealPose46:
ax_pose 13, 0x01f1, 0x80f5, 0x5c00
ax_pose_terminator
sSphealPose47:
ax_pose 14, 0x81ec, 0x80f9, 0x5c00
ax_pose_terminator
sSphealPose48:
ax_pose 15, 0x01ed, 0x80f7, 0x5c00
ax_pose_terminator
sSphealPose49:
ax_pose 18, 0x41f2, 0x80f4, 0x5c00
ax_pose_terminator
sSphealPose50:
ax_pose 19, 0x81e9, 0x80f8, 0x5c00
ax_pose_terminator
sSphealPose51:
ax_pose 8, 0x01f2, 0x40f8, 0x5c00
ax_pose_terminator
sSphealPose52:
ax_pose 20, 0x41f2, 0x90ec, 0x5c00
ax_pose_terminator
sSphealPose53:
ax_pose 21, 0x01ea, 0x90f0, 0x5c00
ax_pose_terminator
sSphealPose54:
ax_pose 4, 0x41f2, 0x90ec, 0x5c00
ax_pose_terminator
sSphealPose55:
ax_pose 22, 0x01ec, 0x90ea, 0x5c00
ax_pose_terminator
sSphealPose56:
ax_pose 23, 0x01ea, 0x90f0, 0x5c00
ax_pose_terminator
sSphealPose57:
ax_pose 0, 0x41f1, 0x90eb, 0x5c00
ax_pose_terminator
sSphealPose58:
ax_pose 24, 0x41f2, 0x90ec, 0x5c00
ax_pose_terminator
sSphealPose59:
ax_pose 25, 0x01ea, 0x90f0, 0x5c00
ax_pose_terminator
sSphealPose60:
ax_pose 10, 0x41f2, 0x90ec, 0x5c00
ax_pose_terminator
sSphealPose61:
ax_pose 26, 0x41f2, 0x80f4, 0x5c00
ax_pose_terminator
sSphealPose62:
ax_pose 27, 0x81ea, 0x80f8, 0x5c00
ax_pose_terminator
sSphealPose63:
ax_pose 16, 0x01f2, 0x40f8, 0x5c00
ax_pose_terminator
sSphealPose64:
ax_pose 24, 0x41f2, 0x80f4, 0x5c00
ax_pose_terminator
sSphealPose65:
ax_pose 25, 0x01ea, 0x80f0, 0x5c00
ax_pose_terminator
sSphealPose66:
ax_pose 10, 0x41f2, 0x80f4, 0x5c00
ax_pose_terminator
sSphealPose67:
ax_pose 22, 0x01ec, 0x80f6, 0x5c00
ax_pose_terminator
sSphealPose68:
ax_pose 23, 0x01ea, 0x80f0, 0x5c00
ax_pose_terminator
sSphealPose69:
ax_pose 0, 0x41f1, 0x80f5, 0x5c00
ax_pose_terminator
sSphealPose70:
ax_pose 20, 0x41f2, 0x80f4, 0x5c00
ax_pose_terminator
sSphealPose71:
ax_pose 21, 0x01ea, 0x80f0, 0x5c00
ax_pose_terminator
sSphealPose72:
ax_pose 4, 0x41f2, 0x80f4, 0x5c00
ax_pose_terminator
sSphealPose73:
ax_pose 18, 0x41f2, 0x80f4, 0x5c00
ax_pose_terminator
sSphealPose74:
ax_pose 19, 0x81e9, 0x80f8, 0x5c00
ax_pose_terminator
sSphealPose75:
ax_pose 8, 0x01f2, 0x40f8, 0x5c00
ax_pose_terminator
sSphealPose76:
ax_pose 20, 0x41f2, 0x90ec, 0x5c00
ax_pose_terminator
sSphealPose77:
ax_pose 21, 0x01ea, 0x90f0, 0x5c00
ax_pose_terminator
sSphealPose78:
ax_pose 4, 0x41f2, 0x90ec, 0x5c00
ax_pose_terminator
sSphealPose79:
ax_pose 22, 0x01ec, 0x90ea, 0x5c00
ax_pose_terminator
sSphealPose80:
ax_pose 23, 0x01ea, 0x90f0, 0x5c00
ax_pose_terminator
sSphealPose81:
ax_pose 0, 0x41f1, 0x90eb, 0x5c00
ax_pose_terminator
sSphealPose82:
ax_pose 24, 0x41f2, 0x90ec, 0x5c00
ax_pose_terminator
sSphealPose83:
ax_pose 25, 0x01ea, 0x90f0, 0x5c00
ax_pose_terminator
sSphealPose84:
ax_pose 10, 0x41f2, 0x90ec, 0x5c00
ax_pose_terminator
sSphealPose85:
ax_pose 26, 0x41f2, 0x80f4, 0x5c00
ax_pose_terminator
sSphealPose86:
ax_pose 27, 0x81ea, 0x80f8, 0x5c00
ax_pose_terminator
sSphealPose87:
ax_pose 16, 0x01f2, 0x40f8, 0x5c00
ax_pose_terminator
sSphealPose88:
ax_pose 24, 0x41f2, 0x80f4, 0x5c00
ax_pose_terminator
sSphealPose89:
ax_pose 25, 0x01ea, 0x80f0, 0x5c00
ax_pose_terminator
sSphealPose90:
ax_pose 10, 0x41f2, 0x80f4, 0x5c00
ax_pose_terminator
sSphealPose91:
ax_pose 22, 0x01ec, 0x80f6, 0x5c00
ax_pose_terminator
sSphealPose92:
ax_pose 23, 0x01ea, 0x80f0, 0x5c00
ax_pose_terminator
sSphealPose93:
ax_pose 0, 0x41f1, 0x80f5, 0x5c00
ax_pose_terminator
sSphealPose94:
ax_pose 20, 0x41f2, 0x80f4, 0x5c00
ax_pose_terminator
sSphealPose95:
ax_pose 21, 0x01ea, 0x80f0, 0x5c00
ax_pose_terminator
sSphealPose96:
ax_pose 4, 0x41f2, 0x80f4, 0x5c00
ax_pose_terminator
sSphealPose97:
ax_pose 18, 0x41f2, 0x80f4, 0x5c00
ax_pose_terminator
sSphealPose98:
ax_pose 28, 0x01ea, 0x80f0, 0x5c00
ax_pose_terminator
sSphealPose99:
ax_pose 29, 0x41f3, 0x80f0, 0x5c00
ax_pose_terminator
sSphealPose100:
ax_pose 20, 0x41f2, 0x90ec, 0x5c00
ax_pose_terminator
sSphealPose101:
ax_pose 30, 0x01ea, 0x90f0, 0x5c00
ax_pose_terminator
sSphealPose102:
ax_pose 31, 0x41f3, 0x90f0, 0x5c00
ax_pose_terminator
sSphealPose103:
ax_pose 22, 0x01ec, 0x90ea, 0x5c00
ax_pose_terminator
sSphealPose104:
ax_pose 32, 0x01ea, 0x90f0, 0x5c00
ax_pose_terminator
sSphealPose105:
ax_pose 33, 0x41f2, 0x90ef, 0x5c00
ax_pose_terminator
sSphealPose106:
ax_pose 24, 0x41f2, 0x90ec, 0x5c00
ax_pose_terminator
sSphealPose107:
ax_pose 34, 0x01eb, 0x90f0, 0x5c00
ax_pose_terminator
sSphealPose108:
ax_pose 35, 0x41f2, 0x90ef, 0x5c00
ax_pose_terminator
sSphealPose109:
ax_pose 26, 0x41f2, 0x80f4, 0x5c00
ax_pose_terminator
sSphealPose110:
ax_pose 36, 0x01eb, 0x80f0, 0x5c00
ax_pose_terminator
sSphealPose111:
ax_pose 37, 0x41f1, 0x80f0, 0x5c00
ax_pose_terminator
sSphealPose112:
ax_pose 24, 0x41f2, 0x80f4, 0x5c00
ax_pose_terminator
sSphealPose113:
ax_pose 34, 0x01eb, 0x80f0, 0x5c00
ax_pose_terminator
sSphealPose114:
ax_pose 35, 0x41f2, 0x80f1, 0x5c00
ax_pose_terminator
sSphealPose115:
ax_pose 22, 0x01ec, 0x80f6, 0x5c00
ax_pose_terminator
sSphealPose116:
ax_pose 32, 0x01ea, 0x80f0, 0x5c00
ax_pose_terminator
sSphealPose117:
ax_pose 33, 0x41f2, 0x80f1, 0x5c00
ax_pose_terminator
sSphealPose118:
ax_pose 20, 0x41f2, 0x80f4, 0x5c00
ax_pose_terminator
sSphealPose119:
ax_pose 30, 0x01ea, 0x80f0, 0x5c00
ax_pose_terminator
sSphealPose120:
ax_pose 31, 0x41f3, 0x80f0, 0x5c00
ax_pose_terminator
sSphealPose121:
ax_pose 18, 0x41f2, 0x80f4, 0x5c00
ax_pose_terminator
sSphealPose122:
ax_pose 19, 0x81e9, 0x80f8, 0x5c00
ax_pose_terminator
sSphealPose123:
ax_pose 20, 0x41f2, 0x90ec, 0x5c00
ax_pose_terminator
sSphealPose124:
ax_pose 21, 0x01ea, 0x90f0, 0x5c00
ax_pose_terminator
sSphealPose125:
ax_pose 22, 0x01ec, 0x90ea, 0x5c00
ax_pose_terminator
sSphealPose126:
ax_pose 23, 0x01ea, 0x90f0, 0x5c00
ax_pose_terminator
sSphealPose127:
ax_pose 24, 0x41f2, 0x90ec, 0x5c00
ax_pose_terminator
sSphealPose128:
ax_pose 25, 0x01ea, 0x90f0, 0x5c00
ax_pose_terminator
sSphealPose129:
ax_pose 26, 0x41f2, 0x80f4, 0x5c00
ax_pose_terminator
sSphealPose130:
ax_pose 27, 0x81ea, 0x80f8, 0x5c00
ax_pose_terminator
sSphealPose131:
ax_pose 24, 0x41f2, 0x80f4, 0x5c00
ax_pose_terminator
sSphealPose132:
ax_pose 25, 0x01ea, 0x80f0, 0x5c00
ax_pose_terminator
sSphealPose133:
ax_pose 22, 0x01ec, 0x80f6, 0x5c00
ax_pose_terminator
sSphealPose134:
ax_pose 23, 0x01ea, 0x80f0, 0x5c00
ax_pose_terminator
sSphealPose135:
ax_pose 20, 0x41f2, 0x80f4, 0x5c00
ax_pose_terminator
sSphealPose136:
ax_pose 21, 0x01ea, 0x80f0, 0x5c00
ax_pose_terminator
sSphealPose137:
ax_pose 38, 0x01ee, 0x80f5, 0x5c00
ax_pose_terminator
sSphealPose138:
ax_pose 39, 0x01ee, 0x80f5, 0x5c00
ax_pose_terminator
sSphealPose139:
ax_pose 40, 0x01e9, 0x80f1, 0x5c00
ax_pose_terminator
sSphealPose140:
ax_pose 41, 0x01e9, 0x90f1, 0x5c00
ax_pose_terminator
sSphealPose141:
ax_pose 42, 0x01ea, 0x90ec, 0x5c00
ax_pose_terminator
sSphealPose142:
ax_pose 43, 0x01ea, 0x90ee, 0x5c00
ax_pose_terminator
sSphealPose143:
ax_pose 44, 0x01e9, 0x80f1, 0x5c00
ax_pose_terminator
sSphealPose144:
ax_pose 43, 0x01ea, 0x80f2, 0x5c00
ax_pose_terminator
sSphealPose145:
ax_pose 42, 0x01ea, 0x80f4, 0x5c00
ax_pose_terminator
sSphealPose146:
ax_pose 41, 0x01e9, 0x80ef, 0x5c00
ax_pose_terminator
sSphealPose147:
ax_pose 22, 0x01ec, 0x80f6, 0x5c00
ax_pose_terminator
sSphealPose148:
ax_pose 0, 0x41f1, 0x80f5, 0x5c00
ax_pose_terminator
sSphealPose149:
ax_pose 20, 0x41f2, 0x80f4, 0x5c00
ax_pose_terminator
sSphealPose150:
ax_pose 4, 0x41f2, 0x80f4, 0x5c00
ax_pose_terminator
sSphealPose151:
ax_pose 18, 0x41f2, 0x80f4, 0x5c00
ax_pose_terminator
sSphealPose152:
ax_pose 8, 0x01f2, 0x40f8, 0x5c00
ax_pose_terminator
sSphealPose153:
ax_pose 20, 0x41f2, 0x90ec, 0x5c00
ax_pose_terminator
sSphealPose154:
ax_pose 4, 0x41f2, 0x90ec, 0x5c00
ax_pose_terminator
sSphealPose155:
ax_pose 22, 0x01ec, 0x90ea, 0x5c00
ax_pose_terminator
sSphealPose156:
ax_pose 0, 0x41f1, 0x90eb, 0x5c00
ax_pose_terminator
sSphealPose157:
ax_pose 24, 0x41f2, 0x90ec, 0x5c00
ax_pose_terminator
sSphealPose158:
ax_pose 10, 0x41f2, 0x90ec, 0x5c00
ax_pose_terminator
sSphealPose159:
ax_pose 26, 0x41f2, 0x80f4, 0x5c00
ax_pose_terminator
sSphealPose160:
ax_pose 16, 0x01f2, 0x40f8, 0x5c00
ax_pose_terminator
sSphealPose161:
ax_pose 24, 0x41f2, 0x80f4, 0x5c00
ax_pose_terminator
sSphealPose162:
ax_pose 10, 0x41f2, 0x80f4, 0x5c00
ax_pose_terminator
sSphealPose163:
ax_pose 28, 0x01ea, 0x80f0, 0x5c00
ax_pose_terminator
sSphealPose164:
ax_pose 30, 0x01ea, 0x80f0, 0x5c00
ax_pose_terminator
sSphealPose165:
ax_pose 32, 0x01ea, 0x80f0, 0x5c00
ax_pose_terminator
sSphealPose166:
ax_pose 34, 0x01eb, 0x80f0, 0x5c00
ax_pose_terminator
sSphealPose167:
ax_pose 36, 0x01eb, 0x80f0, 0x5c00
ax_pose_terminator
sSphealPose168:
ax_pose 34, 0x01eb, 0x90f0, 0x5c00
ax_pose_terminator
sSphealPose169:
ax_pose 32, 0x01ea, 0x90f0, 0x5c00
ax_pose_terminator
sSphealPose170:
ax_pose 30, 0x01ea, 0x90f0, 0x5c00
ax_pose_terminator
sSphealPose171:
ax_pose 19, 0x81ea, 0x80f8, 0x5c00
ax_pose_terminator
sSphealPose172:
ax_pose 21, 0x01ea, 0x90f0, 0x5c00
ax_pose_terminator
sSphealPose173:
ax_pose 23, 0x01ea, 0x90f0, 0x5c00
ax_pose_terminator
sSphealPose174:
ax_pose 25, 0x01ea, 0x90f0, 0x5c00
ax_pose_terminator
sSphealPose175:
ax_pose 27, 0x81ea, 0x80f8, 0x5c00
ax_pose_terminator
sSphealPose176:
ax_pose 25, 0x01ea, 0x80f0, 0x5c00
ax_pose_terminator
sSphealPose177:
ax_pose 23, 0x01ea, 0x80f0, 0x5c00
ax_pose_terminator
sSphealPose178:
ax_pose 21, 0x01ea, 0x80f0, 0x5c00
ax_pose_terminator
sSphealPose179:
ax_pose 18, 0x41f2, 0x80f4, 0x5c00
ax_pose_terminator
sSphealPose180:
ax_pose 19, 0x81ea, 0x80f8, 0x5c00
ax_pose_terminator
sSphealPose181:
ax_pose 29, 0x41f3, 0x80f0, 0x5c00
ax_pose_terminator
sSphealPose182:
ax_pose 20, 0x41f2, 0x90ec, 0x5c00
ax_pose_terminator
sSphealPose183:
ax_pose 21, 0x01ea, 0x90f0, 0x5c00
ax_pose_terminator
sSphealPose184:
ax_pose 31, 0x41f3, 0x90ef, 0x5c00
ax_pose_terminator
sSphealPose185:
ax_pose 22, 0x01ec, 0x90ea, 0x5c00
ax_pose_terminator
sSphealPose186:
ax_pose 23, 0x01ea, 0x90f0, 0x5c00
ax_pose_terminator
sSphealPose187:
ax_pose 33, 0x41f2, 0x90ef, 0x5c00
ax_pose_terminator
sSphealPose188:
ax_pose 24, 0x41f2, 0x90ec, 0x5c00
ax_pose_terminator
sSphealPose189:
ax_pose 25, 0x01ea, 0x90f0, 0x5c00
ax_pose_terminator
sSphealPose190:
ax_pose 35, 0x41f2, 0x90ef, 0x5c00
ax_pose_terminator
sSphealPose191:
ax_pose 26, 0x41f2, 0x80f4, 0x5c00
ax_pose_terminator
sSphealPose192:
ax_pose 27, 0x81ea, 0x80f8, 0x5c00
ax_pose_terminator
sSphealPose193:
ax_pose 37, 0x41f1, 0x80f0, 0x5c00
ax_pose_terminator
sSphealPose194:
ax_pose 24, 0x41f2, 0x80f4, 0x5c00
ax_pose_terminator
sSphealPose195:
ax_pose 25, 0x01ea, 0x80f0, 0x5c00
ax_pose_terminator
sSphealPose196:
ax_pose 35, 0x41f2, 0x80f1, 0x5c00
ax_pose_terminator
sSphealPose197:
ax_pose 22, 0x01ec, 0x80f6, 0x5c00
ax_pose_terminator
sSphealPose198:
ax_pose 23, 0x01ea, 0x80f0, 0x5c00
ax_pose_terminator
sSphealPose199:
ax_pose 33, 0x41f2, 0x80f1, 0x5c00
ax_pose_terminator
sSphealPose200:
ax_pose 20, 0x41f2, 0x80f4, 0x5c00
ax_pose_terminator
sSphealPose201:
ax_pose 21, 0x01ea, 0x80f0, 0x5c00
ax_pose_terminator
sSphealPose202:
ax_pose 31, 0x41f3, 0x80f1, 0x5c00
ax_pose_terminator
sSphealPose203:
ax_pose 29, 0x41f3, 0x80f0, 0x5c00
ax_pose_terminator
sSphealPose204:
ax_pose 31, 0x41f3, 0x80f0, 0x5c00
ax_pose_terminator
sSphealPose205:
ax_pose 33, 0x41f3, 0x80f1, 0x5c00
ax_pose_terminator
sSphealPose206:
ax_pose 35, 0x41f3, 0x80f0, 0x5c00
ax_pose_terminator
sSphealPose207:
ax_pose 37, 0x41f3, 0x80f0, 0x5c00
ax_pose_terminator
sSphealPose208:
ax_pose 35, 0x41f3, 0x90f0, 0x5c00
ax_pose_terminator
sSphealPose209:
ax_pose 33, 0x41f3, 0x90ef, 0x5c00
ax_pose_terminator
sSphealPose210:
ax_pose 31, 0x41f3, 0x90f0, 0x5c00
ax_pose_terminator
sSphealPose211:
ax_pose 18, 0x41f2, 0x80f4, 0x5c00
ax_pose_terminator
sSphealPose212:
ax_pose 20, 0x41f2, 0x80f4, 0x5c00
ax_pose_terminator
sSphealPose213:
ax_pose 22, 0x01ec, 0x80f6, 0x5c00
ax_pose_terminator
sSphealPose214:
ax_pose 24, 0x41f2, 0x80f4, 0x5c00
ax_pose_terminator
sSphealPose215:
ax_pose 26, 0x41f2, 0x80f4, 0x5c00
ax_pose_terminator
sSphealPose216:
ax_pose 24, 0x41f2, 0x90ec, 0x5c00
ax_pose_terminator
sSphealPose217:
ax_pose 22, 0x01ec, 0x90ea, 0x5c00
ax_pose_terminator
sSphealPose218:
ax_pose 20, 0x41f2, 0x90ec, 0x5c00
ax_pose_terminator
.align 2
sSphealAnims_1_1:
ax_anim 6, 0, 0, 0, 0, 0, 0,
ax_anim 6, 0, 1, 0, -1, 0, 0,
ax_anim 6, 0, 2, 0, -2, 0, 0,
ax_anim 6, 0, 3, 0, -2, 0, 0,
ax_anim 6, 0, 4, 0, -1, 0, 0,
ax_anim 6, 0, 5, 0, 0, 0, 0,
ax_anim_terminator
sSphealAnims_1_2:
ax_anim 6, 0, 6, 0, 0, 0, 0,
ax_anim 6, 0, 7, 0, -1, 0, 0,
ax_anim 6, 0, 8, 0, -2, 0, 0,
ax_anim 6, 0, 9, 0, -2, 0, 0,
ax_anim 6, 0, 10, 0, -1, 0, 0,
ax_anim 6, 0, 11, 0, 0, 0, 0,
ax_anim_terminator
sSphealAnims_1_3:
ax_anim 6, 0, 12, 0, 0, 0, 0,
ax_anim 6, 0, 13, 0, -1, 0, 0,
ax_anim 6, 0, 14, 0, -2, 0, 0,
ax_anim 6, 0, 15, 0, -2, 0, 0,
ax_anim 6, 0, 16, 0, -1, 0, 0,
ax_anim 6, 0, 17, 0, 0, 0, 0,
ax_anim_terminator
sSphealAnims_1_4:
ax_anim 6, 0, 18, 0, 0, 0, 0,
ax_anim 6, 0, 23, 0, -1, 0, 0,
ax_anim 6, 0, 22, 0, -2, 0, 0,
ax_anim 6, 0, 21, 0, -2, 0, 0,
ax_anim 6, 0, 20, 0, -1, 0, 0,
ax_anim 6, 0, 19, 0, 0, 0, 0,
ax_anim_terminator
sSphealAnims_1_5:
ax_anim 6, 0, 24, 0, 0, 0, 0,
ax_anim 6, 0, 29, 0, -1, 0, 0,
ax_anim 6, 0, 28, 0, -2, 0, 0,
ax_anim 6, 0, 27, 0, -2, 0, 0,
ax_anim 6, 0, 26, 0, -1, 0, 0,
ax_anim 6, 0, 25, 0, 0, 0, 0,
ax_anim_terminator
sSphealAnims_1_6:
ax_anim 6, 0, 30, 0, 0, 0, 0,
ax_anim 6, 0, 31, 0, -1, 0, 0,
ax_anim 6, 0, 32, 0, -2, 0, 0,
ax_anim 6, 0, 33, 0, -2, 0, 0,
ax_anim 6, 0, 34, 0, -1, 0, 0,
ax_anim 6, 0, 35, 0, 0, 0, 0,
ax_anim_terminator
sSphealAnims_1_7:
ax_anim 6, 0, 36, 0, 0, 0, 0,
ax_anim 6, 0, 41, 0, -1, 0, 0,
ax_anim 6, 0, 40, 0, -2, 0, 0,
ax_anim 6, 0, 39, 0, -2, 0, 0,
ax_anim 6, 0, 38, 0, -1, 0, 0,
ax_anim 6, 0, 37, 0, 0, 0, 0,
ax_anim_terminator
sSphealAnims_1_8:
ax_anim 6, 0, 42, 0, 0, 0, 0,
ax_anim 6, 0, 47, 0, -1, 0, 0,
ax_anim 6, 0, 46, 0, -2, 0, 0,
ax_anim 6, 0, 45, 0, -2, 0, 0,
ax_anim 6, 0, 44, 0, -1, 0, 0,
ax_anim 6, 0, 43, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sSphealAnims_2_1:
ax_anim 2, 0, 48, 0, -1, 0, -1,
ax_anim 6, 0, 49, 0, -2, 0, -2,
ax_anim 1, 0, 49, 0, 0, 0, 0,
ax_anim 2, 0, 50, 0, 4, 0, 4,
ax_anim 2, 2, 50, 0, 10, 0, 10,
ax_anim 2, 0, 48, 0, 20, 0, 20,
ax_anim 2, 1, 48, 1, 20, 1, 20,
ax_anim 2, 0, 48, 0, 20, 0, 20,
ax_anim 2, 0, 48, 1, 20, 1, 20,
ax_anim 2, 0, 48, 0, 6, 0, 6,
ax_anim_terminator
sSphealAnims_2_2:
ax_anim 2, 0, 51, -1, -1, -1, -1,
ax_anim 6, 0, 52, -2, -2, -2, -2,
ax_anim 1, 0, 52, 0, 0, 0, 0,
ax_anim 2, 0, 53, 4, 4, 4, 4,
ax_anim 2, 2, 53, 10, 10, 10, 10,
ax_anim 2, 0, 51, 21, 20, 21, 20,
ax_anim 2, 1, 51, 22, 19, 22, 19,
ax_anim 2, 0, 51, 21, 20, 21, 20,
ax_anim 2, 0, 51, 22, 19, 22, 19,
ax_anim 2, 0, 51, 6, 6, 6, 6,
ax_anim_terminator
sSphealAnims_2_3:
ax_anim 2, 0, 54, -1, 0, -1, 0,
ax_anim 6, 0, 55, -4, 0, -4, 0,
ax_anim 1, 0, 55, 0, 0, 0, 0,
ax_anim 2, 0, 56, 4, 0, 4, 0,
ax_anim 2, 2, 56, 12, 0, 12, 0,
ax_anim 2, 0, 54, 22, 0, 22, 0,
ax_anim 2, 1, 54, 22, 1, 22, 1,
ax_anim 2, 0, 54, 22, 0, 22, 0,
ax_anim 2, 0, 54, 22, 1, 22, 1,
ax_anim 2, 0, 54, 8, 0, 8, 0,
ax_anim_terminator
sSphealAnims_2_4:
ax_anim 2, 0, 57, -1, 1, -1, 1,
ax_anim 6, 0, 58, -2, 2, -2, 2,
ax_anim 1, 0, 58, 0, -1, 0, -1,
ax_anim 2, 0, 59, 4, -6, 4, -6,
ax_anim 2, 2, 59, 13, -15, 13, -15,
ax_anim 2, 0, 57, 21, -23, 21, -23,
ax_anim 2, 1, 57, 22, -22, 22, -22,
ax_anim 2, 0, 57, 21, -23, 21, -23,
ax_anim 2, 0, 57, 22, -22, 22, -22,
ax_anim 2, 0, 57, 5, -6, 5, -6,
ax_anim_terminator
sSphealAnims_2_5:
ax_anim 2, 0, 60, 0, 1, 0, 1,
ax_anim 6, 0, 61, 0, 4, 0, 4,
ax_anim 1, 0, 61, 0, 0, 0, 0,
ax_anim 2, 0, 62, 0, -4, 0, -4,
ax_anim 2, 2, 62, 0, -11, 0, -11,
ax_anim 2, 0, 60, 0, -24, 0, -24,
ax_anim 2, 1, 60, 1, -24, 1, -24,
ax_anim 2, 0, 60, 0, -24, 0, -24,
ax_anim 2, 0, 60, 1, -24, 1, -24,
ax_anim 2, 0, 60, 0, -6, 0, -6,
ax_anim_terminator
sSphealAnims_2_6:
ax_anim 2, 0, 63, 1, 1, 1, 1,
ax_anim 6, 0, 64, 2, 2, 2, 2,
ax_anim 1, 0, 64, 0, -1, 0, -1,
ax_anim 2, 0, 65, -4, -6, -4, -6,
ax_anim 2, 2, 65, -13, -15, -13, -15,
ax_anim 2, 0, 63, -21, -23, -21, -23,
ax_anim 2, 1, 63, -22, -22, -22, -22,
ax_anim 2, 0, 63, -21, -23, -21, -23,
ax_anim 2, 0, 63, -22, -22, -22, -22,
ax_anim 2, 0, 63, -5, -6, -5, -6,
ax_anim_terminator
sSphealAnims_2_7:
ax_anim 2, 0, 66, 1, 0, 1, 0,
ax_anim 6, 0, 67, 4, 0, 4, 0,
ax_anim 1, 0, 67, 0, 0, 0, 0,
ax_anim 2, 0, 68, -4, 0, -4, 0,
ax_anim 2, 2, 68, -12, 0, -12, 0,
ax_anim 2, 0, 66, -22, 0, -22, 0,
ax_anim 2, 1, 66, -22, 1, -22, 1,
ax_anim 2, 0, 66, -22, 0, -22, 0,
ax_anim 2, 0, 66, -22, 1, -22, 1,
ax_anim 2, 0, 66, -8, 0, -8, 0,
ax_anim_terminator
sSphealAnims_2_8:
ax_anim 2, 0, 69, 1, -1, 1, -1,
ax_anim 6, 0, 70, 2, -2, 2, -2,
ax_anim 1, 0, 70, 0, 0, 0, 0,
ax_anim 2, 0, 71, -4, 4, -4, 4,
ax_anim 2, 2, 71, -10, 10, -10, 10,
ax_anim 2, 0, 69, -21, 20, -21, 20,
ax_anim 2, 1, 69, -22, 19, -22, 19,
ax_anim 2, 0, 69, -21, 20, -21, 20,
ax_anim 2, 0, 69, -22, 19, -22, 19,
ax_anim 2, 0, 69, -6, 6, -6, 6,
ax_anim_terminator
.align 2
sSphealAnims_3_1:
ax_anim 2, 0, 72, 0, -1, 0, -1,
ax_anim 6, 0, 73, 0, -2, 0, -2,
ax_anim 1, 0, 73, 0, 0, 0, 0,
ax_anim 2, 0, 74, 0, 4, 0, 4,
ax_anim 2, 2, 74, 0, 10, 0, 10,
ax_anim 2, 0, 72, 0, 20, 0, 20,
ax_anim 2, 1, 72, 1, 20, 1, 20,
ax_anim 2, 0, 72, 0, 20, 0, 20,
ax_anim 2, 0, 72, 1, 20, 1, 20,
ax_anim 2, 0, 72, 0, 6, 0, 6,
ax_anim_terminator
sSphealAnims_3_2:
ax_anim 2, 0, 75, -1, -1, -1, -1,
ax_anim 6, 0, 76, -2, -2, -2, -2,
ax_anim 1, 0, 76, 0, 0, 0, 0,
ax_anim 2, 0, 77, 4, 4, 4, 4,
ax_anim 2, 2, 77, 10, 10, 10, 10,
ax_anim 2, 0, 75, 21, 20, 21, 20,
ax_anim 2, 1, 75, 22, 19, 22, 19,
ax_anim 2, 0, 75, 21, 20, 21, 20,
ax_anim 2, 0, 75, 22, 19, 22, 19,
ax_anim 2, 0, 75, 6, 6, 6, 6,
ax_anim_terminator
sSphealAnims_3_3:
ax_anim 2, 0, 78, -1, 0, -1, 0,
ax_anim 6, 0, 79, -4, 0, -4, 0,
ax_anim 1, 0, 79, 0, 0, 0, 0,
ax_anim 2, 0, 80, 4, 0, 4, 0,
ax_anim 2, 2, 80, 12, 0, 12, 0,
ax_anim 2, 0, 78, 22, 0, 22, 0,
ax_anim 2, 1, 78, 22, 1, 22, 1,
ax_anim 2, 0, 78, 22, 0, 22, 0,
ax_anim 2, 0, 78, 22, 1, 22, 1,
ax_anim 2, 0, 78, 8, 0, 8, 0,
ax_anim_terminator
sSphealAnims_3_4:
ax_anim 2, 0, 81, -1, 1, -1, 1,
ax_anim 6, 0, 82, -2, 2, -2, 2,
ax_anim 1, 0, 82, 0, -1, 0, -1,
ax_anim 2, 0, 83, 4, -6, 4, -6,
ax_anim 2, 2, 83, 13, -15, 13, -15,
ax_anim 2, 0, 81, 21, -23, 21, -23,
ax_anim 2, 1, 81, 22, -22, 22, -22,
ax_anim 2, 0, 81, 21, -23, 21, -23,
ax_anim 2, 0, 81, 22, -22, 22, -22,
ax_anim 2, 0, 81, 5, -6, 5, -6,
ax_anim_terminator
sSphealAnims_3_5:
ax_anim 2, 0, 84, 0, 1, 0, 1,
ax_anim 6, 0, 85, 0, 4, 0, 4,
ax_anim 1, 0, 85, 0, 0, 0, 0,
ax_anim 2, 0, 86, 0, -4, 0, -4,
ax_anim 2, 2, 86, 0, -11, 0, -11,
ax_anim 2, 0, 84, 0, -24, 0, -24,
ax_anim 2, 1, 84, 1, -24, 1, -24,
ax_anim 2, 0, 84, 0, -24, 0, -24,
ax_anim 2, 0, 84, 1, -24, 1, -24,
ax_anim 2, 0, 84, 0, -6, 0, -6,
ax_anim_terminator
sSphealAnims_3_6:
ax_anim 2, 0, 87, 1, 1, 1, 1,
ax_anim 6, 0, 88, 2, 2, 2, 2,
ax_anim 1, 0, 88, 0, -1, 0, -1,
ax_anim 2, 0, 89, -4, -6, -4, -6,
ax_anim 2, 2, 89, -13, -15, -13, -15,
ax_anim 2, 0, 87, -21, -23, -21, -23,
ax_anim 2, 1, 87, -22, -22, -22, -22,
ax_anim 2, 0, 87, -21, -23, -21, -23,
ax_anim 2, 0, 87, -22, -22, -22, -22,
ax_anim 2, 0, 87, -5, -6, -5, -6,
ax_anim_terminator
sSphealAnims_3_7:
ax_anim 2, 0, 90, 1, 0, 1, 0,
ax_anim 6, 0, 91, 4, 0, 4, 0,
ax_anim 1, 0, 91, 0, 0, 0, 0,
ax_anim 2, 0, 92, -4, 0, -4, 0,
ax_anim 2, 2, 92, -12, 0, -12, 0,
ax_anim 2, 0, 90, -22, 0, -22, 0,
ax_anim 2, 1, 90, -22, 1, -22, 1,
ax_anim 2, 0, 90, -22, 0, -22, 0,
ax_anim 2, 0, 90, -22, 1, -22, 1,
ax_anim 2, 0, 90, -8, 0, -8, 0,
ax_anim_terminator
sSphealAnims_3_8:
ax_anim 2, 0, 93, 1, -1, 1, -1,
ax_anim 6, 0, 94, 2, -2, 2, -2,
ax_anim 1, 0, 94, 0, 0, 0, 0,
ax_anim 2, 0, 95, -4, 4, -4, 4,
ax_anim 2, 2, 95, -10, 10, -10, 10,
ax_anim 2, 0, 93, -21, 20, -21, 20,
ax_anim 2, 1, 93, -22, 19, -22, 19,
ax_anim 2, 0, 93, -21, 20, -21, 20,
ax_anim 2, 0, 93, -22, 19, -22, 19,
ax_anim 2, 0, 93, -6, 6, -6, 6,
ax_anim_terminator
.align 2
sSphealAnims_4_1:
ax_anim 2, 0, 97, 0, -2, 0, -2,
ax_anim 6, 2, 97, 0, -3, 0, -3,
ax_anim 2, 0, 96, 0, -1, 0, -1,
ax_anim 2, 1, 98, 0, 3, 0, 3,
ax_anim 2, 0, 98, 1, 3, 1, 3,
ax_anim 2, 0, 98, 0, 3, 0, 3,
ax_anim 2, 0, 98, 1, 3, 1, 3,
ax_anim 2, 0, 98, 0, 3, 0, 3,
ax_anim 2, 0, 98, 1, 3, 1, 3,
ax_anim 2, 0, 98, 0, 3, 0, 3,
ax_anim 2, 0, 96, 0, 1, 0, 1,
ax_anim_terminator
sSphealAnims_4_2:
ax_anim 2, 0, 100, -2, -2, -2, -2,
ax_anim 6, 2, 100, -3, -3, -3, -3,
ax_anim 2, 0, 99, -1, -1, -1, -1,
ax_anim 2, 1, 101, 2, 2, 2, 2,
ax_anim 2, 0, 101, 3, 1, 3, 1,
ax_anim 2, 0, 101, 2, 2, 2, 2,
ax_anim 2, 0, 101, 3, 1, 3, 1,
ax_anim 2, 0, 101, 2, 2, 2, 2,
ax_anim 2, 0, 101, 3, 1, 3, 1,
ax_anim 2, 0, 101, 2, 2, 2, 2,
ax_anim 2, 0, 99, 1, 1, 1, 1,
ax_anim_terminator
sSphealAnims_4_3:
ax_anim 2, 0, 103, -2, 0, -2, 0,
ax_anim 6, 2, 103, -3, 0, -3, 0,
ax_anim 2, 0, 102, -1, 0, -1, 0,
ax_anim 2, 1, 104, 2, 0, 2, 0,
ax_anim 2, 0, 104, 2, 1, 2, 1,
ax_anim 2, 0, 104, 2, 0, 2, 0,
ax_anim 2, 0, 104, 2, 1, 2, 1,
ax_anim 2, 0, 104, 2, 0, 2, 0,
ax_anim 2, 0, 104, 2, 1, 2, 1,
ax_anim 2, 0, 104, 2, 0, 2, 0,
ax_anim 2, 0, 102, 1, 0, 1, 0,
ax_anim_terminator
sSphealAnims_4_4:
ax_anim 2, 0, 106, -2, 2, -2, 2,
ax_anim 6, 2, 106, -3, 3, -3, 3,
ax_anim 2, 0, 105, -1, 1, -1, 1,
ax_anim 2, 1, 107, 2, -2, 2, -2,
ax_anim 2, 0, 107, 3, -1, 3, -1,
ax_anim 2, 0, 107, 2, -2, 2, -2,
ax_anim 2, 0, 107, 3, -1, 3, -1,
ax_anim 2, 0, 107, 2, -2, 2, -2,
ax_anim 2, 0, 107, 3, -1, 3, -1,
ax_anim 2, 0, 107, 2, -2, 2, -2,
ax_anim 2, 0, 105, 1, -1, 1, -1,
ax_anim_terminator
sSphealAnims_4_5:
ax_anim 2, 0, 109, 0, 2, 0, 2,
ax_anim 6, 2, 109, 0, 3, 0, 3,
ax_anim 2, 0, 108, 0, 1, 0, 1,
ax_anim 2, 1, 110, 0, -3, 0, -3,
ax_anim 2, 0, 110, 1, -3, 1, -3,
ax_anim 2, 0, 110, 0, -3, 0, -3,
ax_anim 2, 0, 110, 1, -3, 1, -3,
ax_anim 2, 0, 110, 0, -3, 0, -3,
ax_anim 2, 0, 110, 1, -3, 1, -3,
ax_anim 2, 0, 110, 0, -3, 0, -3,
ax_anim 2, 0, 108, 0, -1, 0, -1,
ax_anim_terminator
sSphealAnims_4_6:
ax_anim 2, 0, 112, 2, 2, 2, 2,
ax_anim 6, 2, 112, 3, 3, 3, 3,
ax_anim 2, 0, 111, 1, 1, 1, 1,
ax_anim 2, 1, 113, -2, -2, -2, -2,
ax_anim 2, 0, 113, -3, -1, -3, -1,
ax_anim 2, 0, 113, -2, -2, -2, -2,
ax_anim 2, 0, 113, -3, -1, -3, -1,
ax_anim 2, 0, 113, -2, -2, -2, -2,
ax_anim 2, 0, 113, -3, -1, -3, -1,
ax_anim 2, 0, 113, -2, -2, -2, -2,
ax_anim 2, 0, 111, -1, -1, -1, -1,
ax_anim_terminator
sSphealAnims_4_7:
ax_anim 2, 0, 115, 2, 0, 2, 0,
ax_anim 6, 2, 115, 3, 0, 3, 0,
ax_anim 2, 0, 114, 1, 0, 1, 0,
ax_anim 2, 1, 116, -2, 0, -2, 0,
ax_anim 2, 0, 116, -2, 1, -2, 1,
ax_anim 2, 0, 116, -2, 0, -2, 0,
ax_anim 2, 0, 116, -2, 1, -2, 1,
ax_anim 2, 0, 116, -2, 0, -2, 0,
ax_anim 2, 0, 116, -2, 1, -2, 1,
ax_anim 2, 0, 116, -2, 0, -2, 0,
ax_anim 2, 0, 114, -1, 0, -1, 0,
ax_anim_terminator
sSphealAnims_4_8:
ax_anim 2, 0, 118, 2, -2, 2, -2,
ax_anim 6, 2, 118, 3, -3, 3, -3,
ax_anim 2, 0, 117, 1, -1, 1, -1,
ax_anim 2, 1, 119, -2, 2, -2, 2,
ax_anim 2, 0, 119, -3, 1, -3, 1,
ax_anim 2, 0, 119, -2, 2, -2, 2,
ax_anim 2, 0, 119, -3, 1, -3, 1,
ax_anim 2, 0, 119, -2, 2, -2, 2,
ax_anim 2, 0, 119, -3, 1, -3, 1,
ax_anim 2, 0, 119, -2, 2, -2, 2,
ax_anim 2, 0, 117, -1, 1, -1, 1,
ax_anim_terminator
.align 2
sSphealAnims_5_1:
ax_anim 3, 0, 120, 0, 0, 0, 0,
ax_anim 8, 2, 121, 0, 0, 0, 0,
ax_anim 2, 0, 121, -1, 0, -1, 0,
ax_anim 2, 0, 121, 0, 0, 0, 0,
ax_anim 2, 0, 121, -1, 0, -1, 0,
ax_anim 2, 0, 121, 0, 0, 0, 0,
ax_anim 2, 0, 121, -1, 0, -1, 0,
ax_anim 2, 0, 121, 0, 0, 0, 0,
ax_anim 2, 0, 121, -1, 0, -1, 0,
ax_anim 2, 0, 120, 0, 0, 0, 0,
ax_anim_terminator
sSphealAnims_5_2:
ax_anim 3, 0, 122, 0, 0, 0, 0,
ax_anim 8, 2, 123, 0, 0, 0, 0,
ax_anim 2, 0, 123, 1, -1, 1, -1,
ax_anim 2, 0, 123, 0, 0, 0, 0,
ax_anim 2, 0, 123, 1, -1, 1, -1,
ax_anim 2, 0, 123, 0, 0, 0, 0,
ax_anim 2, 0, 123, 1, -1, 1, -1,
ax_anim 2, 0, 123, 0, 0, 0, 0,
ax_anim 2, 0, 123, 1, -1, 1, -1,
ax_anim 2, 0, 122, 0, 0, 0, 0,
ax_anim_terminator
sSphealAnims_5_3:
ax_anim 3, 0, 124, 0, 0, 0, 0,
ax_anim 8, 2, 125, 0, 0, 0, 0,
ax_anim 2, 0, 125, 0, -1, 0, -1,
ax_anim 2, 0, 125, 0, 0, 0, 0,
ax_anim 2, 0, 125, 0, -1, 0, -1,
ax_anim 2, 0, 125, 0, 0, 0, 0,
ax_anim 2, 0, 125, 0, -1, 0, -1,
ax_anim 2, 0, 125, 0, 0, 0, 0,
ax_anim 2, 0, 125, 0, -1, 0, -1,
ax_anim 2, 0, 124, 0, 0, 0, 0,
ax_anim_terminator
sSphealAnims_5_4:
ax_anim 3, 0, 126, 0, 0, 0, 0,
ax_anim 8, 2, 127, 0, 0, 0, 0,
ax_anim 2, 0, 127, -1, -1, -1, -1,
ax_anim 2, 0, 127, 0, 0, 0, 0,
ax_anim 2, 0, 127, -1, -1, -1, -1,
ax_anim 2, 0, 127, 0, 0, 0, 0,
ax_anim 2, 0, 127, -1, -1, -1, -1,
ax_anim 2, 0, 127, 0, 0, 0, 0,
ax_anim 2, 0, 127, -1, -1, -1, -1,
ax_anim 2, 0, 126, 0, 0, 0, 0,
ax_anim_terminator
sSphealAnims_5_5:
ax_anim 3, 0, 128, 0, 0, 0, 0,
ax_anim 8, 2, 129, 0, 0, 0, 0,
ax_anim 2, 0, 129, -1, 0, -1, 0,
ax_anim 2, 0, 129, 0, 0, 0, 0,
ax_anim 2, 0, 129, -1, 0, -1, 0,
ax_anim 2, 0, 129, 0, 0, 0, 0,
ax_anim 2, 0, 129, -1, 0, -1, 0,
ax_anim 2, 0, 129, 0, 0, 0, 0,
ax_anim 2, 0, 129, -1, 0, -1, 0,
ax_anim 2, 0, 128, 0, 0, 0, 0,
ax_anim_terminator
sSphealAnims_5_6:
ax_anim 3, 0, 130, 0, 0, 0, 0,
ax_anim 8, 2, 131, 0, 0, 0, 0,
ax_anim 2, 0, 131, 1, -1, 1, -1,
ax_anim 2, 0, 131, 0, 0, 0, 0,
ax_anim 2, 0, 131, 1, -1, 1, -1,
ax_anim 2, 0, 131, 0, 0, 0, 0,
ax_anim 2, 0, 131, 1, -1, 1, -1,
ax_anim 2, 0, 131, 0, 0, 0, 0,
ax_anim 2, 0, 131, 1, -1, 1, -1,
ax_anim 2, 0, 130, 0, 0, 0, 0,
ax_anim_terminator
sSphealAnims_5_7:
ax_anim 3, 0, 132, 0, 0, 0, 0,
ax_anim 8, 2, 133, 0, 0, 0, 0,
ax_anim 2, 0, 133, 0, -1, 0, -1,
ax_anim 2, 0, 133, 0, 0, 0, 0,
ax_anim 2, 0, 133, 0, -1, 0, -1,
ax_anim 2, 0, 133, 0, 0, 0, 0,
ax_anim 2, 0, 133, 0, -1, 0, -1,
ax_anim 2, 0, 133, 0, 0, 0, 0,
ax_anim 2, 0, 133, 0, -1, 0, -1,
ax_anim 2, 0, 132, 0, 0, 0, 0,
ax_anim_terminator
sSphealAnims_5_8:
ax_anim 3, 0, 134, 0, 0, 0, 0,
ax_anim 8, 2, 135, 0, 0, 0, 0,
ax_anim 2, 0, 135, -1, -1, -1, -1,
ax_anim 2, 0, 135, 0, 0, 0, 0,
ax_anim 2, 0, 135, -1, -1, -1, -1,
ax_anim 2, 0, 135, 0, 0, 0, 0,
ax_anim 2, 0, 135, -1, -1, -1, -1,
ax_anim 2, 0, 135, 0, 0, 0, 0,
ax_anim 2, 0, 135, -1, -1, -1, -1,
ax_anim 2, 0, 134, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sSphealAnims_6_1:
ax_anim 30, 0, 136, 0, 0, 0, 0,
ax_anim 35, 0, 137, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sSphealAnims_7_1:
ax_anim 2, 0, 138, 0, -2, 0, -2,
ax_anim 8, 0, 138, 0, -3, 0, -3,
ax_anim_terminator
sSphealAnims_7_2:
ax_anim 2, 0, 139, -2, -2, -2, -2,
ax_anim 8, 0, 139, -3, -3, -3, -3,
ax_anim_terminator
sSphealAnims_7_3:
ax_anim 2, 0, 140, -2, 0, -2, 0,
ax_anim 8, 0, 140, -3, 0, -3, 0,
ax_anim_terminator
sSphealAnims_7_4:
ax_anim 2, 0, 141, -2, 2, -2, 2,
ax_anim 8, 0, 141, -3, 3, -3, 3,
ax_anim_terminator
sSphealAnims_7_5:
ax_anim 2, 0, 142, 0, 2, 0, 2,
ax_anim 8, 0, 142, 0, 3, 0, 3,
ax_anim_terminator
sSphealAnims_7_6:
ax_anim 2, 0, 143, 2, 2, 2, 2,
ax_anim 8, 0, 143, 3, 3, 3, 3,
ax_anim_terminator
sSphealAnims_7_7:
ax_anim 2, 0, 144, 2, 0, 2, 0,
ax_anim 8, 0, 144, 3, 0, 3, 0,
ax_anim_terminator
sSphealAnims_7_8:
ax_anim 2, 0, 145, 2, -2, 2, -2,
ax_anim 8, 0, 145, 3, -3, 3, -3,
ax_anim_terminator
.align 2
sSphealAnims_8_1:
ax_anim 16, 0, 150, 0, 0, 0, 0,
ax_anim 6, 0, 151, 0, -2, 0, 0,
ax_anim 6, 0, 151, 0, -3, 0, 0,
ax_anim 6, 0, 151, 0, 0, 0, 0,
ax_anim 6, 0, 151, 0, -2, 0, 0,
ax_anim 6, 0, 151, 0, -3, 0, 0,
ax_anim_terminator
sSphealAnims_8_2:
ax_anim 16, 0, 152, 0, 0, 0, 0,
ax_anim 6, 0, 153, 0, -2, 0, 0,
ax_anim 6, 0, 153, 0, -3, 0, 0,
ax_anim 6, 0, 153, 0, 0, 0, 0,
ax_anim 6, 0, 153, 0, -2, 0, 0,
ax_anim 6, 0, 153, 0, -3, 0, 0,
ax_anim_terminator
sSphealAnims_8_3:
ax_anim 16, 0, 154, 0, 0, 0, 0,
ax_anim 6, 0, 155, 0, -2, 0, 0,
ax_anim 6, 0, 155, 0, -3, 0, 0,
ax_anim 6, 0, 155, 0, 0, 0, 0,
ax_anim 6, 0, 155, 0, -2, 0, 0,
ax_anim 6, 0, 155, 0, -3, 0, 0,
ax_anim_terminator
sSphealAnims_8_4:
ax_anim 16, 0, 156, 0, 0, 0, 0,
ax_anim 6, 0, 157, 0, -2, 0, 0,
ax_anim 6, 0, 157, 0, -3, 0, 0,
ax_anim 6, 0, 157, 0, 0, 0, 0,
ax_anim 6, 0, 157, 0, -2, 0, 0,
ax_anim 6, 0, 157, 0, -3, 0, 0,
ax_anim_terminator
sSphealAnims_8_5:
ax_anim 16, 0, 158, 0, 0, 0, 0,
ax_anim 6, 0, 159, 0, -2, 0, 0,
ax_anim 6, 0, 159, 0, -3, 0, 0,
ax_anim 6, 0, 159, 0, 0, 0, 0,
ax_anim 6, 0, 159, 0, -2, 0, 0,
ax_anim 6, 0, 159, 0, -3, 0, 0,
ax_anim_terminator
sSphealAnims_8_6:
ax_anim 16, 0, 160, 0, 0, 0, 0,
ax_anim 6, 0, 161, 0, -2, 0, 0,
ax_anim 6, 0, 161, 0, -3, 0, 0,
ax_anim 6, 0, 161, 0, 0, 0, 0,
ax_anim 6, 0, 161, 0, -2, 0, 0,
ax_anim 6, 0, 161, 0, -3, 0, 0,
ax_anim_terminator
sSphealAnims_8_7:
ax_anim 16, 0, 146, 0, 0, 0, 0,
ax_anim 6, 0, 147, 0, -2, 0, 0,
ax_anim 6, 0, 147, 0, -3, 0, 0,
ax_anim 6, 0, 147, 0, 0, 0, 0,
ax_anim 6, 0, 147, 0, -2, 0, 0,
ax_anim 6, 0, 147, 0, -3, 0, 0,
ax_anim_terminator
sSphealAnims_8_8:
ax_anim 16, 0, 148, 0, 0, 0, 0,
ax_anim 6, 0, 149, 0, -2, 0, 0,
ax_anim 6, 0, 149, 0, -3, 0, 0,
ax_anim 6, 0, 149, 0, 0, 0, 0,
ax_anim 6, 0, 149, 0, -2, 0, 0,
ax_anim 6, 0, 149, 0, -3, 0, 0,
ax_anim_terminator
.align 2
sSphealAnims_9_1:
ax_anim 2, 0, 162, 0, 0, 0, 0,
ax_anim 1, 0, 163, 6, 3, 6, 3,
ax_anim 2, 0, 164, 8, 9, 8, 9,
ax_anim 2, 0, 165, 7, 15, 7, 15,
ax_anim 3, 0, 166, 0, 19, 0, 19,
ax_anim 2, 3, 167, -7, 15, -7, 15,
ax_anim 2, 0, 168, -8, 9, -8, 9,
ax_anim 1, 0, 169, -6, 3, -6, 3,
ax_anim 1, 0, 162, 0, 0, 0, 0,
ax_anim_terminator
sSphealAnims_9_2:
ax_anim 2, 0, 169, 0, 0, 0, 0,
ax_anim 1, 0, 162, 8, 0, 8, 0,
ax_anim 2, 0, 163, 17, 3, 17, 3,
ax_anim 2, 0, 164, 19, 10, 19, 10,
ax_anim 3, 0, 165, 20, 19, 20, 19,
ax_anim 2, 3, 166, 11, 19, 11, 19,
ax_anim 2, 0, 167, 3, 15, 3, 15,
ax_anim 1, 0, 168, 0, 7, 0, 7,
ax_anim 1, 0, 169, 0, 0, 0, 0,
ax_anim_terminator
sSphealAnims_9_3:
ax_anim 2, 0, 168, 0, 0, 0, 0,
ax_anim 1, 0, 169, 3, -5, 3, -5,
ax_anim 2, 0, 162, 11, -6, 11, -6,
ax_anim 2, 0, 163, 16, -5, 16, -5,
ax_anim 3, 0, 164, 20, 0, 20, 0,
ax_anim 2, 3, 165, 16, 4, 16, 4,
ax_anim 2, 0, 166, 12, 5, 12, 5,
ax_anim 1, 0, 167, 4, 5, 4, 5,
ax_anim 1, 0, 168, 0, 0, 0, 0,
ax_anim_terminator
sSphealAnims_9_4:
ax_anim 2, 0, 167, 0, 0, 0, 0,
ax_anim 1, 0, 168, -1, -8, -1, -8,
ax_anim 2, 0, 169, 3, -16, 3, -16,
ax_anim 2, 0, 162, 12, -22, 12, -22,
ax_anim 3, 0, 163, 20, -22, 20, -22,
ax_anim 2, 3, 164, 21, -15, 21, -15,
ax_anim 2, 0, 165, 17, -4, 17, -4,
ax_anim 1, 0, 166, 10, 0, 10, 0,
ax_anim 1, 0, 167, 0, 0, 0, 0,
ax_anim_terminator
sSphealAnims_9_5:
ax_anim 2, 0, 166, 0, 0, 0, 0,
ax_anim 1, 0, 167, -8, -4, -8, -4,
ax_anim 2, 0, 168, -9, -12, -9, -12,
ax_anim 2, 0, 169, -8, -18, -8, -18,
ax_anim 3, 0, 162, 0, -22, 0, -22,
ax_anim 2, 3, 163, 8, -18, 8, -18,
ax_anim 2, 0, 164, 9, -12, 9, -12,
ax_anim 1, 0, 165, 8, -4, 8, -4,
ax_anim 1, 0, 166, 0, 0, 0, 0,
ax_anim_terminator
sSphealAnims_9_6:
ax_anim 2, 0, 165, 0, 0, 0, 0,
ax_anim 1, 0, 164, 1, -8, 1, -8,
ax_anim 2, 0, 163, -3, -16, -3, -16,
ax_anim 2, 0, 162, -12, -22, -12, -22,
ax_anim 3, 0, 169, -20, -22, -20, -22,
ax_anim 2, 3, 168, -21, -15, -21, -15,
ax_anim 2, 0, 167, -17, -4, -17, -4,
ax_anim 1, 0, 166, -10, 0, -10, 0,
ax_anim 1, 0, 165, 0, 0, 0, 0,
ax_anim_terminator
sSphealAnims_9_7:
ax_anim 2, 0, 164, 0, 0, 0, 0,
ax_anim 1, 0, 163, -3, -5, -3, -5,
ax_anim 2, 0, 162, -11, -6, -11, -6,
ax_anim 2, 0, 169, -16, -5, -16, -5,
ax_anim 3, 0, 168, -20, 0, -20, 0,
ax_anim 2, 3, 167, -16, 4, -16, 4,
ax_anim 2, 0, 166, -12, 5, -12, 5,
ax_anim 1, 0, 165, -4, 5, -4, 5,
ax_anim 1, 0, 164, 0, 0, 0, 0,
ax_anim_terminator
sSphealAnims_9_8:
ax_anim 2, 0, 163, 0, 0, 0, 0,
ax_anim 1, 0, 162, -8, 0, -8, 0,
ax_anim 2, 0, 169, -17, 3, -17, 3,
ax_anim 2, 0, 168, -19, 10, -19, 10,
ax_anim 3, 0, 167, -20, 19, -20, 19,
ax_anim 2, 3, 166, -11, 19, -11, 19,
ax_anim 2, 0, 165, -3, 15, -3, 15,
ax_anim 1, 0, 164, 0, 7, 0, 7,
ax_anim 1, 0, 163, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sSphealAnims_10_1:
ax_anim 2, 0, 170, 0, 0, 0, 0,
ax_anim 2, 0, 170, 6, 0, 6, 0,
ax_anim 2, 0, 170, -6, 0, -6, 0,
ax_anim 2, 0, 170, 10, 0, 10, 0,
ax_anim 2, 0, 170, -10, 0, -10, 0,
ax_anim 2, 0, 170, 12, 0, 12, 0,
ax_anim 3, 0, 170, -12, 0, -12, 0,
ax_anim 3, 0, 170, 13, 0, 13, 0,
ax_anim 3, 0, 170, -13, 0, -13, 0,
ax_anim 2, 0, 170, 12, 0, 12, 0,
ax_anim 3, 0, 170, -12, 0, -12, 0,
ax_anim 2, 0, 170, 10, 0, 10, 0,
ax_anim 2, 0, 170, -10, 0, -10, 0,
ax_anim 2, 0, 170, 6, 0, 6, 0,
ax_anim 2, 0, 170, -6, 0, -6, 0,
ax_anim 2, 0, 170, 0, 0, 0, 0,
ax_anim_terminator
sSphealAnims_10_2:
ax_anim 2, 0, 171, 0, 0, 0, 0,
ax_anim 2, 0, 171, 6, -6, 6, -6,
ax_anim 2, 0, 171, -6, 6, -6, 6,
ax_anim 2, 0, 171, 10, -10, 10, -10,
ax_anim 2, 0, 171, -10, 10, -10, 10,
ax_anim 2, 0, 171, 12, -12, 12, -12,
ax_anim 3, 0, 171, -12, 12, -12, 12,
ax_anim 3, 0, 171, 13, -13, 13, -13,
ax_anim 3, 0, 171, -13, 13, -13, 13,
ax_anim 2, 0, 171, 12, -12, 12, -12,
ax_anim 3, 0, 171, -12, 12, -12, 12,
ax_anim 2, 0, 171, 10, -10, 10, -10,
ax_anim 2, 0, 171, -10, 10, -10, 10,
ax_anim 2, 0, 171, 6, -6, 6, -6,
ax_anim 2, 0, 171, -6, 6, -6, 6,
ax_anim 2, 0, 171, 0, 0, 0, 0,
ax_anim_terminator
sSphealAnims_10_3:
ax_anim 2, 0, 172, 0, 0, 0, 0,
ax_anim 2, 0, 172, 0, -6, 0, -6,
ax_anim 2, 0, 172, 0, 6, 0, 6,
ax_anim 2, 0, 172, 0, -10, 0, -10,
ax_anim 2, 0, 172, 0, 10, 0, 10,
ax_anim 2, 0, 172, 0, -12, 0, -12,
ax_anim 3, 0, 172, 0, 12, 0, 12,
ax_anim 3, 0, 172, 0, -13, 0, -13,
ax_anim 3, 0, 172, 0, 13, 0, 13,
ax_anim 2, 0, 172, 0, -12, 0, -12,
ax_anim 3, 0, 172, 0, 12, 0, 12,
ax_anim 2, 0, 172, 0, -10, 0, -10,
ax_anim 2, 0, 172, 0, 10, 0, 10,
ax_anim 2, 0, 172, 0, -6, 0, -6,
ax_anim 2, 0, 172, 0, 6, 0, 6,
ax_anim 2, 0, 172, 0, 0, 0, 0,
ax_anim_terminator
sSphealAnims_10_4:
ax_anim 2, 0, 173, 0, 0, 0, 0,
ax_anim 2, 0, 173, -6, -6, -6, -6,
ax_anim 2, 0, 173, 6, 6, 6, 6,
ax_anim 2, 0, 173, -10, -10, -10, -10,
ax_anim 2, 0, 173, 10, 10, 10, 10,
ax_anim 2, 0, 173, -12, -12, -12, -12,
ax_anim 3, 0, 173, 12, 12, 12, 12,
ax_anim 3, 0, 173, -13, -13, -13, -13,
ax_anim 3, 0, 173, 13, 13, 13, 13,
ax_anim 2, 0, 173, -12, -12, -12, -12,
ax_anim 3, 0, 173, 12, 12, 12, 12,
ax_anim 2, 0, 173, -10, -10, -10, -10,
ax_anim 2, 0, 173, 10, 10, 10, 10,
ax_anim 2, 0, 173, -6, -6, -6, -6,
ax_anim 2, 0, 173, 6, 6, 6, 6,
ax_anim 2, 0, 173, 0, 0, 0, 0,
ax_anim_terminator
sSphealAnims_10_5:
ax_anim 2, 0, 174, 0, 0, 0, 0,
ax_anim 2, 0, 174, 6, 0, 6, 0,
ax_anim 2, 0, 174, -6, 0, -6, 0,
ax_anim 2, 0, 174, 10, 0, 10, 0,
ax_anim 2, 0, 174, -10, 0, -10, 0,
ax_anim 2, 0, 174, 12, 0, 12, 0,
ax_anim 3, 0, 174, -12, 0, -12, 0,
ax_anim 3, 0, 174, 13, 0, 13, 0,
ax_anim 3, 0, 174, -13, 0, -13, 0,
ax_anim 2, 0, 174, 12, 0, 12, 0,
ax_anim 3, 0, 174, -12, 0, -12, 0,
ax_anim 2, 0, 174, 10, 0, 10, 0,
ax_anim 2, 0, 174, -10, 0, -10, 0,
ax_anim 2, 0, 174, 6, 0, 6, 0,
ax_anim 2, 0, 174, -6, 0, -6, 0,
ax_anim 2, 0, 174, 0, 0, 0, 0,
ax_anim_terminator
sSphealAnims_10_6:
ax_anim 2, 0, 175, 0, 0, 0, 0,
ax_anim 2, 0, 175, 6, -6, 6, -6,
ax_anim 2, 0, 175, -6, 6, -6, 6,
ax_anim 2, 0, 175, 10, -10, 10, -10,
ax_anim 2, 0, 175, -10, 10, -10, 10,
ax_anim 2, 0, 175, 12, -12, 12, -12,
ax_anim 3, 0, 175, -12, 12, -12, 12,
ax_anim 3, 0, 175, 13, -13, 13, -13,
ax_anim 3, 0, 175, -13, 13, -13, 13,
ax_anim 2, 0, 175, 12, -12, 12, -12,
ax_anim 3, 0, 175, -12, 12, -12, 12,
ax_anim 2, 0, 175, 10, -10, 10, -10,
ax_anim 2, 0, 175, -10, 10, -10, 10,
ax_anim 2, 0, 175, 6, -6, 6, -6,
ax_anim 2, 0, 175, -6, 6, -6, 6,
ax_anim 2, 0, 175, 0, 0, 0, 0,
ax_anim_terminator
sSphealAnims_10_7:
ax_anim 2, 0, 176, 0, 0, 0, 0,
ax_anim 2, 0, 176, 0, -6, 0, -6,
ax_anim 2, 0, 176, 0, 6, 0, 6,
ax_anim 2, 0, 176, 0, -10, 0, -10,
ax_anim 2, 0, 176, 0, 10, 0, 10,
ax_anim 2, 0, 176, 0, -12, 0, -12,
ax_anim 3, 0, 176, 0, 12, 0, 12,
ax_anim 3, 0, 176, 0, -13, 0, -13,
ax_anim 3, 0, 176, 0, 13, 0, 13,
ax_anim 2, 0, 176, 0, -12, 0, -12,
ax_anim 3, 0, 176, 0, 12, 0, 12,
ax_anim 2, 0, 176, 0, -10, 0, -10,
ax_anim 2, 0, 176, 0, 10, 0, 10,
ax_anim 2, 0, 176, 0, -6, 0, -6,
ax_anim 2, 0, 176, 0, 6, 0, 6,
ax_anim 2, 0, 176, 0, 0, 0, 0,
ax_anim_terminator
sSphealAnims_10_8:
ax_anim 2, 0, 177, 0, 0, 0, 0,
ax_anim 2, 0, 177, -6, -6, -6, -6,
ax_anim 2, 0, 177, 6, 6, 6, 6,
ax_anim 2, 0, 177, -10, -10, -10, -10,
ax_anim 2, 0, 177, 10, 10, 10, 10,
ax_anim 2, 0, 177, -12, -12, -12, -12,
ax_anim 3, 0, 177, 12, 12, 12, 12,
ax_anim 3, 0, 177, -13, -13, -13, -13,
ax_anim 3, 0, 177, 13, 13, 13, 13,
ax_anim 2, 0, 177, -12, -12, -12, -12,
ax_anim 3, 0, 177, 12, 12, 12, 12,
ax_anim 2, 0, 177, -10, -10, -10, -10,
ax_anim 2, 0, 177, 10, 10, 10, 10,
ax_anim 2, 0, 177, -6, -6, -6, -6,
ax_anim 2, 0, 177, 6, 6, 6, 6,
ax_anim 2, 0, 177, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sSphealAnims_11_1:
ax_anim 2, 0, 178, 0, 0, 0, 0,
ax_anim 1, 0, 179, 0, -10, 0, 0,
ax_anim 2, 0, 179, 0, -16, 0, 0,
ax_anim 3, 0, 179, 0, -20, 0, 0,
ax_anim 4, 0, 179, 0, -21, 0, 0,
ax_anim 4, 0, 178, 0, -23, 0, 0,
ax_anim 3, 0, 180, 0, -21, 0, 0,
ax_anim 2, 0, 180, 0, -18, 0, 0,
ax_anim 1, 0, 180, 0, -12, 0, 0,
ax_anim 2, 2, 180, 0, 0, 0, 0,
ax_anim_terminator
sSphealAnims_11_2:
ax_anim 2, 0, 181, 0, 0, 0, 0,
ax_anim 1, 0, 182, 0, -10, 0, 0,
ax_anim 2, 0, 182, 0, -16, 0, 0,
ax_anim 3, 0, 182, 0, -20, 0, 0,
ax_anim 4, 0, 182, 0, -21, 0, 0,
ax_anim 4, 0, 181, 0, -22, 0, 0,
ax_anim 3, 0, 183, 0, -21, 0, 0,
ax_anim 2, 0, 183, 0, -18, 0, 0,
ax_anim 1, 0, 183, 0, -12, 0, 0,
ax_anim 2, 2, 183, 0, 0, 0, 0,
ax_anim_terminator
sSphealAnims_11_3:
ax_anim 2, 0, 184, 0, 0, 0, 0,
ax_anim 1, 0, 185, 0, -10, 0, 0,
ax_anim 2, 0, 185, 0, -16, 0, 0,
ax_anim 3, 0, 185, 0, -20, 0, 0,
ax_anim 4, 0, 185, 0, -21, 0, 0,
ax_anim 4, 0, 186, 0, -23, 0, 0,
ax_anim 3, 0, 186, 0, -21, 0, 0,
ax_anim 2, 0, 186, 0, -18, 0, 0,
ax_anim 1, 0, 186, 0, -12, 0, 0,
ax_anim 2, 2, 186, 0, 0, 0, 0,
ax_anim_terminator
sSphealAnims_11_4:
ax_anim 2, 0, 187, 0, 0, 0, 0,
ax_anim 1, 0, 188, 0, -10, 0, 0,
ax_anim 2, 0, 188, 0, -16, 0, 0,
ax_anim 3, 0, 188, 0, -20, 0, 0,
ax_anim 4, 0, 188, 0, -21, 0, 0,
ax_anim 4, 0, 189, 0, -23, 0, 0,
ax_anim 3, 0, 189, 0, -22, 0, 0,
ax_anim 2, 0, 189, 0, -17, 0, 0,
ax_anim 1, 0, 189, 0, -11, 0, 0,
ax_anim 2, 2, 189, 0, 0, 0, 0,
ax_anim_terminator
sSphealAnims_11_5:
ax_anim 2, 0, 190, 0, 0, 0, 0,
ax_anim 1, 0, 191, 0, -10, 0, 0,
ax_anim 2, 0, 191, 0, -16, 0, 0,
ax_anim 3, 0, 191, 0, -20, 0, 0,
ax_anim 4, 0, 191, 0, -21, 0, 0,
ax_anim 4, 0, 192, 0, -22, 0, 0,
ax_anim 3, 0, 192, 0, -21, 0, 0,
ax_anim 2, 0, 192, 0, -18, 0, 0,
ax_anim 1, 0, 192, 0, -12, 0, 0,
ax_anim 2, 2, 192, 0, 0, 0, 0,
ax_anim_terminator
sSphealAnims_11_6:
ax_anim 2, 0, 193, 0, 0, 0, 0,
ax_anim 1, 0, 194, 0, -10, 0, 0,
ax_anim 2, 0, 194, 0, -16, 0, 0,
ax_anim 3, 0, 194, 0, -20, 0, 0,
ax_anim 4, 0, 194, 0, -21, 0, 0,
ax_anim 4, 0, 195, 0, -23, 0, 0,
ax_anim 3, 0, 195, 0, -22, 0, 0,
ax_anim 2, 0, 195, 0, -17, 0, 0,
ax_anim 1, 0, 195, 0, -11, 0, 0,
ax_anim 2, 2, 195, 0, 0, 0, 0,
ax_anim_terminator
sSphealAnims_11_7:
ax_anim 2, 0, 196, 0, 0, 0, 0,
ax_anim 1, 0, 197, 0, -10, 0, 0,
ax_anim 2, 0, 197, 0, -16, 0, 0,
ax_anim 3, 0, 197, 0, -20, 0, 0,
ax_anim 4, 0, 197, 0, -21, 0, 0,
ax_anim 4, 0, 198, 0, -23, 0, 0,
ax_anim 3, 0, 198, 0, -21, 0, 0,
ax_anim 2, 0, 198, 0, -18, 0, 0,
ax_anim 1, 0, 198, 0, -12, 0, 0,
ax_anim 2, 2, 198, 0, 0, 0, 0,
ax_anim_terminator
sSphealAnims_11_8:
ax_anim 2, 0, 199, 0, 0, 0, 0,
ax_anim 1, 0, 200, 0, -10, 0, 0,
ax_anim 2, 0, 200, 0, -16, 0, 0,
ax_anim 3, 0, 200, 0, -20, 0, 0,
ax_anim 4, 0, 200, 0, -21, 0, 0,
ax_anim 4, 0, 199, 0, -22, 0, 0,
ax_anim 3, 0, 201, 0, -21, 0, 0,
ax_anim 2, 0, 201, 0, -18, 0, 0,
ax_anim 1, 0, 201, 0, -12, 0, 0,
ax_anim 2, 2, 201, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sSphealAnims_12_1:
ax_anim 2, 0, 202, 1, 0, 1, 0,
ax_anim 2, 0, 202, 0, 0, 0, 0,
ax_anim 2, 0, 202, 1, 0, 1, 0,
ax_anim 2, 0, 202, 0, 0, 0, 0,
ax_anim 2, 0, 202, 1, 0, 1, 0,
ax_anim 2, 2, 202, 0, 0, 0, 0,
ax_anim 2, 0, 202, 1, 0, 1, 0,
ax_anim 2, 0, 202, 0, 0, 0, 0,
ax_anim 2, 0, 202, 1, 0, 1, 0,
ax_anim 2, 1, 202, 0, 0, 0, 0,
ax_anim_terminator
sSphealAnims_12_2:
ax_anim 2, 0, 209, 1, -1, 1, -1,
ax_anim 2, 0, 209, 0, 0, 0, 0,
ax_anim 2, 0, 209, 1, -1, 1, -1,
ax_anim 2, 0, 209, 0, 0, 0, 0,
ax_anim 2, 0, 209, 1, -1, 1, -1,
ax_anim 2, 2, 209, 0, 0, 0, 0,
ax_anim 2, 0, 209, 1, -1, 1, -1,
ax_anim 2, 0, 209, 0, 0, 0, 0,
ax_anim 2, 0, 209, 1, -1, 1, -1,
ax_anim 2, 1, 209, 0, 0, 0, 0,
ax_anim_terminator
sSphealAnims_12_3:
ax_anim 2, 0, 208, 0, -1, 0, -1,
ax_anim 2, 0, 208, 0, 0, 0, 0,
ax_anim 2, 0, 208, 0, -1, 0, -1,
ax_anim 2, 0, 208, 0, 0, 0, 0,
ax_anim 2, 0, 208, 0, -1, 0, -1,
ax_anim 2, 2, 208, 0, 0, 0, 0,
ax_anim 2, 0, 208, 0, -1, 0, -1,
ax_anim 2, 0, 208, 0, 0, 0, 0,
ax_anim 2, 0, 208, 0, -1, 0, -1,
ax_anim 2, 1, 208, 0, 0, 0, 0,
ax_anim_terminator
sSphealAnims_12_4:
ax_anim 2, 0, 207, -1, -1, -1, -1,
ax_anim 2, 0, 207, 0, 0, 0, 0,
ax_anim 2, 0, 207, -1, -1, -1, -1,
ax_anim 2, 0, 207, 0, 0, 0, 0,
ax_anim 2, 0, 207, -1, -1, -1, -1,
ax_anim 2, 2, 207, 0, 0, 0, 0,
ax_anim 2, 0, 207, -1, -1, -1, -1,
ax_anim 2, 0, 207, 0, 0, 0, 0,
ax_anim 2, 0, 207, -1, -1, -1, -1,
ax_anim 2, 1, 207, 0, 0, 0, 0,
ax_anim_terminator
sSphealAnims_12_5:
ax_anim 2, 0, 206, 1, 0, 1, 0,
ax_anim 2, 0, 206, 0, 0, 0, 0,
ax_anim 2, 0, 206, 1, 0, 1, 0,
ax_anim 2, 0, 206, 0, 0, 0, 0,
ax_anim 2, 0, 206, 1, 0, 1, 0,
ax_anim 2, 2, 206, 0, 0, 0, 0,
ax_anim 2, 0, 206, 1, 0, 1, 0,
ax_anim 2, 0, 206, 0, 0, 0, 0,
ax_anim 2, 0, 206, 1, 0, 1, 0,
ax_anim 2, 1, 206, 0, 0, 0, 0,
ax_anim_terminator
sSphealAnims_12_6:
ax_anim 2, 0, 205, 1, -1, 1, -1,
ax_anim 2, 0, 205, 0, 0, 0, 0,
ax_anim 2, 0, 205, 1, -1, 1, -1,
ax_anim 2, 0, 205, 0, 0, 0, 0,
ax_anim 2, 0, 205, 1, -1, 1, -1,
ax_anim 2, 2, 205, 0, 0, 0, 0,
ax_anim 2, 0, 205, 1, -1, 1, -1,
ax_anim 2, 0, 205, 0, 0, 0, 0,
ax_anim 2, 0, 205, 1, -1, 1, -1,
ax_anim 2, 1, 205, 0, 0, 0, 0,
ax_anim_terminator
sSphealAnims_12_7:
ax_anim 2, 0, 204, 0, -1, 0, -1,
ax_anim 2, 0, 204, 0, 0, 0, 0,
ax_anim 2, 0, 204, 0, -1, 0, -1,
ax_anim 2, 0, 204, 0, 0, 0, 0,
ax_anim 2, 0, 204, 0, -1, 0, -1,
ax_anim 2, 2, 204, 0, 0, 0, 0,
ax_anim 2, 0, 204, 0, -1, 0, -1,
ax_anim 2, 0, 204, 0, 0, 0, 0,
ax_anim 2, 0, 204, 0, -1, 0, -1,
ax_anim 2, 1, 204, 0, 0, 0, 0,
ax_anim_terminator
sSphealAnims_12_8:
ax_anim 2, 0, 203, -1, -1, -1, -1,
ax_anim 2, 0, 203, 0, 0, 0, 0,
ax_anim 2, 0, 203, -1, -1, -1, -1,
ax_anim 2, 0, 203, 0, 0, 0, 0,
ax_anim 2, 0, 203, -1, -1, -1, -1,
ax_anim 2, 2, 203, 0, 0, 0, 0,
ax_anim 2, 0, 203, -1, -1, -1, -1,
ax_anim 2, 0, 203, 0, 0, 0, 0,
ax_anim 2, 0, 203, -1, -1, -1, -1,
ax_anim 2, 1, 203, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sSphealAnims_13_1:
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 2, 210, 0, 0, 0, 0,
ax_anim_terminator
sSphealAnims_13_2:
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 2, 217, 0, 0, 0, 0,
ax_anim_terminator
sSphealAnims_13_3:
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 2, 216, 0, 0, 0, 0,
ax_anim_terminator
sSphealAnims_13_4:
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 2, 2, 215, 0, 0, 0, 0,
ax_anim_terminator
sSphealAnims_13_5:
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 2, 2, 214, 0, 0, 0, 0,
ax_anim_terminator
sSphealAnims_13_6:
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 2, 2, 213, 0, 0, 0, 0,
ax_anim_terminator
sSphealAnims_13_7:
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 2, 2, 212, 0, 0, 0, 0,
ax_anim_terminator
sSphealAnims_13_8:
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 2, 2, 211, 0, 0, 0, 0,
ax_anim_terminator
sSphealGfx1:
.incbin "baserom.gba", 0x14FE058, 0x100
sSphealSprites1:
ax_sprite sSphealGfx1, 0x100
ax_sprite_terminator
sSphealGfx2:
.incbin "baserom.gba", 0x14FE168, 0x100
sSphealSprites2:
ax_sprite sSphealGfx2, 0x100
ax_sprite_terminator
sSphealGfx3:
.incbin "baserom.gba", 0x14FE278, 0x100
sSphealSprites3:
ax_sprite sSphealGfx3, 0x100
ax_sprite_terminator
sSphealGfx4:
.incbin "baserom.gba", 0x14FE388, 0x100
sSphealSprites4:
ax_sprite sSphealGfx4, 0x100
ax_sprite_terminator
sSphealGfx5:
.incbin "baserom.gba", 0x14FE498, 0x100
sSphealSprites5:
ax_sprite sSphealGfx5, 0x100
ax_sprite_terminator
sSphealGfx6:
.incbin "baserom.gba", 0x14FE5A8, 0x200
sSphealSprites6:
ax_sprite sSphealGfx6, 0x200
ax_sprite_terminator
sSphealGfx7:
.incbin "baserom.gba", 0x14FE7B8, 0x100
sSphealSprites7:
ax_sprite sSphealGfx7, 0x100
ax_sprite_terminator
sSphealGfx8:
.incbin "baserom.gba", 0x14FE8C8, 0x200
sSphealSprites8:
ax_sprite sSphealGfx8, 0x200
ax_sprite_terminator
sSphealGfx9:
.incbin "baserom.gba", 0x14FEAD8, 0x80
sSphealSprites9:
ax_sprite sSphealGfx9, 0x80
ax_sprite_terminator
sSphealGfx10:
.incbin "baserom.gba", 0x14FEB68, 0x200
sSphealSprites10:
ax_sprite sSphealGfx10, 0x200
ax_sprite_terminator
sSphealGfx11:
.incbin "baserom.gba", 0x14FED78, 0x100
sSphealSprites11:
ax_sprite sSphealGfx11, 0x100
ax_sprite_terminator
sSphealGfx12:
.incbin "baserom.gba", 0x14FEE88, 0x100
sSphealSprites12:
ax_sprite sSphealGfx12, 0x100
ax_sprite_terminator
sSphealGfx13:
.incbin "baserom.gba", 0x14FEF98, 0x100
sSphealSprites13:
ax_sprite sSphealGfx13, 0x100
ax_sprite_terminator
sSphealGfx14:
.incbin "baserom.gba", 0x14FF0A8, 0x200
sSphealSprites14:
ax_sprite sSphealGfx14, 0x200
ax_sprite_terminator
sSphealGfx15:
.incbin "baserom.gba", 0x14FF2B8, 0x100
sSphealSprites15:
ax_sprite sSphealGfx15, 0x100
ax_sprite_terminator
sSphealGfx16:
.incbin "baserom.gba", 0x14FF3C8, 0x200
sSphealSprites16:
ax_sprite sSphealGfx16, 0x200
ax_sprite_terminator
sSphealGfx17:
.incbin "baserom.gba", 0x14FF5D8, 0x80
sSphealSprites17:
ax_sprite sSphealGfx17, 0x80
ax_sprite_terminator
sSphealGfx18:
.incbin "baserom.gba", 0x14FF668, 0x200
sSphealSprites18:
ax_sprite sSphealGfx18, 0x200
ax_sprite_terminator
sSphealGfx19:
.incbin "baserom.gba", 0x14FF878, 0x60
sSphealGfx19_1:
.incbin "baserom.gba", 0x14FF8D8, 0x60
sSphealSprites19:
ax_sprite sSphealGfx19, 0x60
ax_sprite 0, 0x20
ax_sprite sSphealGfx19_1, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sSphealGfx20:
.incbin "baserom.gba", 0x14FF960, 0xC0
sSphealSprites20:
ax_sprite sSphealGfx20, 0xc0
ax_sprite 0, 0x40
ax_sprite_terminator
sSphealGfx21:
.incbin "baserom.gba", 0x14FFA38, 0x60
sSphealGfx21_1:
.incbin "baserom.gba", 0x14FFA98, 0x60
sSphealSprites21:
ax_sprite sSphealGfx21, 0x60
ax_sprite 0, 0x20
ax_sprite sSphealGfx21_1, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sSphealGfx22:
.incbin "baserom.gba", 0x14FFB20, 0x40
sSphealGfx22_1:
.incbin "baserom.gba", 0x14FFB60, 0x60
sSphealGfx22_2:
.incbin "baserom.gba", 0x14FFBC0, 0x60
sSphealSprites22:
ax_sprite 0, 0x20
ax_sprite sSphealGfx22, 0x40
ax_sprite 0, 0x40
ax_sprite sSphealGfx22_1, 0x60
ax_sprite 0, 0x20
ax_sprite sSphealGfx22_2, 0x60
ax_sprite 0, 0x80
ax_sprite_terminator
sSphealGfx23:
.incbin "baserom.gba", 0x14FFC60, 0x40
sSphealGfx23_1:
.incbin "baserom.gba", 0x14FFCA0, 0x60
sSphealGfx23_2:
.incbin "baserom.gba", 0x14FFD00, 0x60
sSphealSprites23:
ax_sprite sSphealGfx23, 0x40
ax_sprite 0, 0x40
ax_sprite sSphealGfx23_1, 0x60
ax_sprite 0, 0x20
ax_sprite sSphealGfx23_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sSphealGfx24:
.incbin "baserom.gba", 0x14FFD98, 0x40
sSphealGfx24_1:
.incbin "baserom.gba", 0x14FFDD8, 0x60
sSphealGfx24_2:
.incbin "baserom.gba", 0x14FFE38, 0x60
sSphealSprites24:
ax_sprite 0, 0x20
ax_sprite sSphealGfx24, 0x40
ax_sprite 0, 0x40
ax_sprite sSphealGfx24_1, 0x60
ax_sprite 0, 0x20
ax_sprite sSphealGfx24_2, 0x60
ax_sprite 0, 0x80
ax_sprite_terminator
sSphealGfx25:
.incbin "baserom.gba", 0x14FFED8, 0x60
sSphealGfx25_1:
.incbin "baserom.gba", 0x14FFF38, 0x60
sSphealSprites25:
ax_sprite sSphealGfx25, 0x60
ax_sprite 0, 0x20
ax_sprite sSphealGfx25_1, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sSphealGfx26:
.incbin "baserom.gba", 0x14FFFC0, 0x40
sSphealGfx26_1:
.incbin "baserom.gba", 0x1500000, 0x60
sSphealGfx26_2:
.incbin "baserom.gba", 0x1500060, 0x60
sSphealGfx26_3:
.incbin "baserom.gba", 0x15000C0, 0x20
sSphealSprites26:
ax_sprite 0, 0x20
ax_sprite sSphealGfx26, 0x40
ax_sprite 0, 0x40
ax_sprite sSphealGfx26_1, 0x60
ax_sprite 0, 0x20
ax_sprite sSphealGfx26_2, 0x60
ax_sprite 0, 0x40
ax_sprite sSphealGfx26_3, 0x20
ax_sprite 0, 0x20
ax_sprite_terminator
sSphealGfx27:
.incbin "baserom.gba", 0x1500130, 0x60
sSphealGfx27_1:
.incbin "baserom.gba", 0x1500190, 0x60
sSphealSprites27:
ax_sprite sSphealGfx27, 0x60
ax_sprite 0, 0x20
ax_sprite sSphealGfx27_1, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sSphealGfx28:
.incbin "baserom.gba", 0x1500218, 0x100
sSphealSprites28:
ax_sprite sSphealGfx28, 0x100
ax_sprite_terminator
sSphealGfx29:
.incbin "baserom.gba", 0x1500328, 0x40
sSphealGfx29_1:
.incbin "baserom.gba", 0x1500368, 0x40
sSphealGfx29_2:
.incbin "baserom.gba", 0x15003A8, 0x80
sSphealSprites29:
ax_sprite 0, 0x20
ax_sprite sSphealGfx29, 0x40
ax_sprite 0, 0x40
ax_sprite sSphealGfx29_1, 0x40
ax_sprite 0, 0x20
ax_sprite sSphealGfx29_2, 0x80
ax_sprite 0, 0x80
ax_sprite_terminator
sSphealGfx30:
.incbin "baserom.gba", 0x1500468, 0x40
sSphealGfx30_1:
.incbin "baserom.gba", 0x15004A8, 0x80
sSphealSprites30:
ax_sprite 0, 0x20
ax_sprite sSphealGfx30, 0x40
ax_sprite 0, 0x20
ax_sprite sSphealGfx30_1, 0x80
ax_sprite_terminator
sSphealGfx31:
.incbin "baserom.gba", 0x1500550, 0x40
sSphealGfx31_1:
.incbin "baserom.gba", 0x1500590, 0x60
sSphealGfx31_2:
.incbin "baserom.gba", 0x15005F0, 0x60
sSphealSprites31:
ax_sprite 0, 0x20
ax_sprite sSphealGfx31, 0x40
ax_sprite 0, 0x40
ax_sprite sSphealGfx31_1, 0x60
ax_sprite 0, 0x20
ax_sprite sSphealGfx31_2, 0x60
ax_sprite 0, 0x80
ax_sprite_terminator
sSphealGfx32:
.incbin "baserom.gba", 0x1500690, 0x100
sSphealSprites32:
ax_sprite sSphealGfx32, 0x100
ax_sprite_terminator
sSphealGfx33:
.incbin "baserom.gba", 0x15007A0, 0x40
sSphealGfx33_1:
.incbin "baserom.gba", 0x15007E0, 0x60
sSphealGfx33_2:
.incbin "baserom.gba", 0x1500840, 0x60
sSphealSprites33:
ax_sprite 0, 0x20
ax_sprite sSphealGfx33, 0x40
ax_sprite 0, 0x40
ax_sprite sSphealGfx33_1, 0x60
ax_sprite 0, 0x20
ax_sprite sSphealGfx33_2, 0x60
ax_sprite 0, 0x80
ax_sprite_terminator
sSphealGfx34:
.incbin "baserom.gba", 0x15008E0, 0x100
sSphealSprites34:
ax_sprite sSphealGfx34, 0x100
ax_sprite_terminator
sSphealGfx35:
.incbin "baserom.gba", 0x15009F0, 0x40
sSphealGfx35_1:
.incbin "baserom.gba", 0x1500A30, 0x60
sSphealGfx35_2:
.incbin "baserom.gba", 0x1500A90, 0x60
sSphealGfx35_3:
.incbin "baserom.gba", 0x1500AF0, 0x20
sSphealSprites35:
ax_sprite 0, 0x20
ax_sprite sSphealGfx35, 0x40
ax_sprite 0, 0x40
ax_sprite sSphealGfx35_1, 0x60
ax_sprite 0, 0x20
ax_sprite sSphealGfx35_2, 0x60
ax_sprite 0, 0x40
ax_sprite sSphealGfx35_3, 0x20
ax_sprite 0, 0x20
ax_sprite_terminator
sSphealGfx36:
.incbin "baserom.gba", 0x1500B60, 0x80
sSphealGfx36_1:
.incbin "baserom.gba", 0x1500BE0, 0x60
sSphealSprites36:
ax_sprite sSphealGfx36, 0x80
ax_sprite 0, 0x20
ax_sprite sSphealGfx36_1, 0x60
ax_sprite_terminator
sSphealGfx37:
.incbin "baserom.gba", 0x1500C60, 0x40
sSphealGfx37_1:
.incbin "baserom.gba", 0x1500CA0, 0x40
sSphealGfx37_2:
.incbin "baserom.gba", 0x1500CE0, 0x80
sSphealGfx37_3:
.incbin "baserom.gba", 0x1500D60, 0x40
sSphealSprites37:
ax_sprite 0, 0x20
ax_sprite sSphealGfx37, 0x40
ax_sprite 0, 0x40
ax_sprite sSphealGfx37_1, 0x40
ax_sprite 0, 0x20
ax_sprite sSphealGfx37_2, 0x80
ax_sprite 0, 0x20
ax_sprite sSphealGfx37_3, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sSphealGfx38:
.incbin "baserom.gba", 0x1500DF0, 0x40
sSphealGfx38_1:
.incbin "baserom.gba", 0x1500E30, 0x80
sSphealSprites38:
ax_sprite 0, 0x20
ax_sprite sSphealGfx38, 0x40
ax_sprite 0, 0x20
ax_sprite sSphealGfx38_1, 0x80
ax_sprite_terminator
sSphealGfx39:
.incbin "baserom.gba", 0x1500ED8, 0x200
sSphealSprites39:
ax_sprite sSphealGfx39, 0x200
ax_sprite_terminator
sSphealGfx40:
.incbin "baserom.gba", 0x15010E8, 0x200
sSphealSprites40:
ax_sprite sSphealGfx40, 0x200
ax_sprite_terminator
sSphealGfx41:
.incbin "baserom.gba", 0x15012F8, 0x200
sSphealSprites41:
ax_sprite sSphealGfx41, 0x200
ax_sprite_terminator
sSphealGfx42:
.incbin "baserom.gba", 0x1501508, 0x200
sSphealSprites42:
ax_sprite sSphealGfx42, 0x200
ax_sprite_terminator
sSphealGfx43:
.incbin "baserom.gba", 0x1501718, 0x200
sSphealSprites43:
ax_sprite sSphealGfx43, 0x200
ax_sprite_terminator
sSphealGfx44:
.incbin "baserom.gba", 0x1501928, 0x200
sSphealSprites44:
ax_sprite sSphealGfx44, 0x200
ax_sprite_terminator
sSphealGfx45:
.incbin "baserom.gba", 0x1501B38, 0x200
sSphealSprites45:
ax_sprite sSphealGfx45, 0x200
ax_sprite_terminator
sAxPosesSpheal:
.4byte sSphealPose1
.4byte sSphealPose2
.4byte sSphealPose3
.4byte sSphealPose4
.4byte sSphealPose5
.4byte sSphealPose6
.4byte sSphealPose7
.4byte sSphealPose8
.4byte sSphealPose9
.4byte sSphealPose10
.4byte sSphealPose11
.4byte sSphealPose12
.4byte sSphealPose13
.4byte sSphealPose14
.4byte sSphealPose15
.4byte sSphealPose16
.4byte sSphealPose17
.4byte sSphealPose18
.4byte sSphealPose19
.4byte sSphealPose20
.4byte sSphealPose21
.4byte sSphealPose22
.4byte sSphealPose23
.4byte sSphealPose24
.4byte sSphealPose25
.4byte sSphealPose26
.4byte sSphealPose27
.4byte sSphealPose28
.4byte sSphealPose29
.4byte sSphealPose30
.4byte sSphealPose31
.4byte sSphealPose32
.4byte sSphealPose33
.4byte sSphealPose34
.4byte sSphealPose35
.4byte sSphealPose36
.4byte sSphealPose37
.4byte sSphealPose38
.4byte sSphealPose39
.4byte sSphealPose40
.4byte sSphealPose41
.4byte sSphealPose42
.4byte sSphealPose43
.4byte sSphealPose44
.4byte sSphealPose45
.4byte sSphealPose46
.4byte sSphealPose47
.4byte sSphealPose48
.4byte sSphealPose49
.4byte sSphealPose50
.4byte sSphealPose51
.4byte sSphealPose52
.4byte sSphealPose53
.4byte sSphealPose54
.4byte sSphealPose55
.4byte sSphealPose56
.4byte sSphealPose57
.4byte sSphealPose58
.4byte sSphealPose59
.4byte sSphealPose60
.4byte sSphealPose61
.4byte sSphealPose62
.4byte sSphealPose63
.4byte sSphealPose64
.4byte sSphealPose65
.4byte sSphealPose66
.4byte sSphealPose67
.4byte sSphealPose68
.4byte sSphealPose69
.4byte sSphealPose70
.4byte sSphealPose71
.4byte sSphealPose72
.4byte sSphealPose73
.4byte sSphealPose74
.4byte sSphealPose75
.4byte sSphealPose76
.4byte sSphealPose77
.4byte sSphealPose78
.4byte sSphealPose79
.4byte sSphealPose80
.4byte sSphealPose81
.4byte sSphealPose82
.4byte sSphealPose83
.4byte sSphealPose84
.4byte sSphealPose85
.4byte sSphealPose86
.4byte sSphealPose87
.4byte sSphealPose88
.4byte sSphealPose89
.4byte sSphealPose90
.4byte sSphealPose91
.4byte sSphealPose92
.4byte sSphealPose93
.4byte sSphealPose94
.4byte sSphealPose95
.4byte sSphealPose96
.4byte sSphealPose97
.4byte sSphealPose98
.4byte sSphealPose99
.4byte sSphealPose100
.4byte sSphealPose101
.4byte sSphealPose102
.4byte sSphealPose103
.4byte sSphealPose104
.4byte sSphealPose105
.4byte sSphealPose106
.4byte sSphealPose107
.4byte sSphealPose108
.4byte sSphealPose109
.4byte sSphealPose110
.4byte sSphealPose111
.4byte sSphealPose112
.4byte sSphealPose113
.4byte sSphealPose114
.4byte sSphealPose115
.4byte sSphealPose116
.4byte sSphealPose117
.4byte sSphealPose118
.4byte sSphealPose119
.4byte sSphealPose120
.4byte sSphealPose121
.4byte sSphealPose122
.4byte sSphealPose123
.4byte sSphealPose124
.4byte sSphealPose125
.4byte sSphealPose126
.4byte sSphealPose127
.4byte sSphealPose128
.4byte sSphealPose129
.4byte sSphealPose130
.4byte sSphealPose131
.4byte sSphealPose132
.4byte sSphealPose133
.4byte sSphealPose134
.4byte sSphealPose135
.4byte sSphealPose136
.4byte sSphealPose137
.4byte sSphealPose138
.4byte sSphealPose139
.4byte sSphealPose140
.4byte sSphealPose141
.4byte sSphealPose142
.4byte sSphealPose143
.4byte sSphealPose144
.4byte sSphealPose145
.4byte sSphealPose146
.4byte sSphealPose147
.4byte sSphealPose148
.4byte sSphealPose149
.4byte sSphealPose150
.4byte sSphealPose151
.4byte sSphealPose152
.4byte sSphealPose153
.4byte sSphealPose154
.4byte sSphealPose155
.4byte sSphealPose156
.4byte sSphealPose157
.4byte sSphealPose158
.4byte sSphealPose159
.4byte sSphealPose160
.4byte sSphealPose161
.4byte sSphealPose162
.4byte sSphealPose163
.4byte sSphealPose164
.4byte sSphealPose165
.4byte sSphealPose166
.4byte sSphealPose167
.4byte sSphealPose168
.4byte sSphealPose169
.4byte sSphealPose170
.4byte sSphealPose171
.4byte sSphealPose172
.4byte sSphealPose173
.4byte sSphealPose174
.4byte sSphealPose175
.4byte sSphealPose176
.4byte sSphealPose177
.4byte sSphealPose178
.4byte sSphealPose179
.4byte sSphealPose180
.4byte sSphealPose181
.4byte sSphealPose182
.4byte sSphealPose183
.4byte sSphealPose184
.4byte sSphealPose185
.4byte sSphealPose186
.4byte sSphealPose187
.4byte sSphealPose188
.4byte sSphealPose189
.4byte sSphealPose190
.4byte sSphealPose191
.4byte sSphealPose192
.4byte sSphealPose193
.4byte sSphealPose194
.4byte sSphealPose195
.4byte sSphealPose196
.4byte sSphealPose197
.4byte sSphealPose198
.4byte sSphealPose199
.4byte sSphealPose200
.4byte sSphealPose201
.4byte sSphealPose202
.4byte sSphealPose203
.4byte sSphealPose204
.4byte sSphealPose205
.4byte sSphealPose206
.4byte sSphealPose207
.4byte sSphealPose208
.4byte sSphealPose209
.4byte sSphealPose210
.4byte sSphealPose211
.4byte sSphealPose212
.4byte sSphealPose213
.4byte sSphealPose214
.4byte sSphealPose215
.4byte sSphealPose216
.4byte sSphealPose217
.4byte sSphealPose218
sAxPositionsSpheal:
.2byte   -5,   -4, 	  -1,   -4, 	   0,   -1, 	   0,   -7
.2byte   -5,   -3, 	   1,   -2, 	   0,   -9, 	   0,   -8
.2byte   -5,  -11, 	   1,  -12, 	   0,   -5, 	   0,   -6
.2byte   -5,  -10, 	  -1,  -10, 	   0,  -13, 	   0,   -7
.2byte   -5,   -9, 	  -1,   -9, 	   0,  -15, 	   0,   -7
.2byte   -5,   -6, 	  -1,  -10, 	  -1,    1, 	   0,   -6
.2byte   -5,   -4, 	  -4,   -5, 	   3,   -1, 	   0,   -6
.2byte   -6,   -7, 	   1,   -2, 	  -4,  -10, 	  -1,   -8
.2byte   -6,   -7, 	   1,  -12, 	  -4,   -4, 	  -1,   -6
.2byte   -5,  -10, 	  -4,   -9, 	   3,  -13, 	   0,   -8
.2byte   -4,   -7, 	   1,   -2, 	   1,  -14, 	   1,   -7
.2byte   -3,   -4, 	  -5,   -1, 	   4,   -6, 	   0,   -5
.2byte   -1,   -2, 	  -5,   -1, 	   4,   -1, 	   0,   -5
.2byte   -4,   -6, 	  -2,    0, 	  -8,   -8, 	  -1,   -8
.2byte   -4,   -8, 	  -2,  -14, 	  -8,   -6, 	  -1,   -6
.2byte   -1,  -12, 	  -5,  -13, 	   4,  -13, 	   0,   -9
.2byte    3,   -9, 	   1,  -15, 	   7,   -7, 	   0,   -7
.2byte    3,   -6, 	   1,    0, 	   7,   -8, 	   0,   -8
.2byte    4,   -4, 	   3,   -5, 	  -4,   -1, 	  -1,   -6
.2byte    5,   -7, 	  -2,   -2, 	   3,  -10, 	   0,   -8
.2byte    5,   -7, 	  -2,  -12, 	   3,   -4, 	   0,   -6
.2byte    4,  -10, 	   3,   -9, 	  -4,  -13, 	  -1,   -8
.2byte    3,   -7, 	  -2,   -2, 	  -2,  -14, 	  -2,   -7
.2byte    2,   -4, 	   4,   -1, 	  -5,   -6, 	  -1,   -5
.2byte    4,   -4, 	   0,   -4, 	  -1,   -1, 	  -1,   -7
.2byte    4,   -3, 	  -2,   -2, 	  -1,   -9, 	  -1,   -8
.2byte    4,  -11, 	  -2,  -12, 	  -1,   -5, 	  -1,   -6
.2byte    4,  -10, 	   0,  -10, 	  -1,  -13, 	  -1,   -7
.2byte    4,   -9, 	   0,   -9, 	  -1,  -15, 	  -1,   -7
.2byte    4,   -6, 	   0,  -10, 	   0,    1, 	  -1,   -6
.2byte    2,   -7, 	  -5,   -8, 	   3,   -1, 	  -1,   -6
.2byte    3,   -7, 	  -5,   -7, 	   5,   -4, 	  -1,   -6
.2byte    3,  -10, 	   3,   -2, 	  -5,  -11, 	  -1,   -6
.2byte    3,  -11, 	   1,  -10, 	  -6,  -12, 	   0,   -7
.2byte    1,  -13, 	  -7,  -12, 	   0,   -5, 	  -2,   -8
.2byte    2,  -10, 	  -6,  -10, 	   2,   -4, 	   0,   -7
.2byte   -1,   -6, 	   6,   -6, 	  -7,   -6, 	   0,   -6
.2byte    3,  -11, 	  -7,  -11, 	   3,   -2, 	   0,   -8
.2byte    3,   -5, 	  -7,   -5, 	   3,  -14, 	   0,   -8
.2byte   -1,   -8, 	   6,   -8, 	  -7,   -8, 	   0,   -8
.2byte   -4,   -5, 	   6,   -5, 	  -4,  -14, 	  -1,   -8
.2byte   -4,  -10, 	   6,  -10, 	  -4,   -1, 	  -1,   -7
.2byte   -3,   -7, 	   4,   -8, 	  -4,   -1, 	   0,   -6
.2byte   -4,   -7, 	   4,   -7, 	  -6,   -4, 	   0,   -6
.2byte   -4,  -10, 	  -4,   -2, 	   4,  -11, 	   0,   -6
.2byte   -4,  -11, 	  -2,  -10, 	   5,  -12, 	  -1,   -7
.2byte   -2,  -13, 	   6,  -12, 	  -1,   -5, 	   1,   -8
.2byte   -3,  -10, 	   5,  -10, 	  -3,   -4, 	  -1,   -7
.2byte   -1,   -2, 	  -6,   -1, 	   5,   -1, 	   0,   -5
.2byte   -1,  -11, 	  -5,   -1, 	   4,   -1, 	   0,   -7
.2byte   -1,   -2, 	  -5,   -1, 	   4,   -1, 	   0,   -5
.2byte    3,   -3, 	   5,   -2, 	  -5,   -1, 	  -1,   -6
.2byte    3,   -9, 	   4,   -2, 	  -1,    0, 	   0,   -6
.2byte    4,   -4, 	   3,   -5, 	  -4,   -1, 	  -1,   -6
.2byte    4,   -4, 	   1,   -4, 	   0,    0, 	  -1,   -6
.2byte    4,   -9, 	   0,   -2, 	   3,    0, 	  -1,   -6
.2byte    4,   -4, 	   0,   -4, 	  -1,   -1, 	  -1,   -7
.2byte    2,   -7, 	  -3,   -6, 	   5,   -1, 	  -1,   -7
.2byte    4,  -10, 	  -2,   -3, 	   3,    0, 	  -1,   -7
.2byte    2,   -7, 	  -5,   -8, 	   3,   -1, 	  -1,   -6
.2byte   -1,  -10, 	   6,   -3, 	  -7,   -3, 	  -1,   -7
.2byte   -1,  -12, 	   6,   -3, 	  -7,   -3, 	   0,   -7
.2byte   -1,   -6, 	   6,   -6, 	  -7,   -6, 	   0,   -6
.2byte   -3,   -7, 	   2,   -6, 	  -6,   -1, 	   0,   -7
.2byte   -5,  -10, 	   1,   -3, 	  -4,    0, 	   0,   -7
.2byte   -3,   -7, 	   4,   -8, 	  -4,   -1, 	   0,   -6
.2byte   -5,   -4, 	  -2,   -4, 	  -1,    0, 	   0,   -6
.2byte   -5,   -9, 	  -1,   -2, 	  -4,    0, 	   0,   -6
.2byte   -5,   -4, 	  -1,   -4, 	   0,   -1, 	   0,   -7
.2byte   -4,   -3, 	  -6,   -2, 	   4,   -1, 	   0,   -6
.2byte   -4,   -9, 	  -5,   -2, 	   0,    0, 	  -1,   -6
.2byte   -5,   -4, 	  -4,   -5, 	   3,   -1, 	   0,   -6
.2byte   -1,   -2, 	  -6,   -1, 	   5,   -1, 	   0,   -5
.2byte   -1,  -11, 	  -5,   -1, 	   4,   -1, 	   0,   -7
.2byte   -1,   -2, 	  -5,   -1, 	   4,   -1, 	   0,   -5
.2byte    3,   -3, 	   5,   -2, 	  -5,   -1, 	  -1,   -6
.2byte    3,   -9, 	   4,   -2, 	  -1,    0, 	   0,   -6
.2byte    4,   -4, 	   3,   -5, 	  -4,   -1, 	  -1,   -6
.2byte    4,   -4, 	   1,   -4, 	   0,    0, 	  -1,   -6
.2byte    4,   -9, 	   0,   -2, 	   3,    0, 	  -1,   -6
.2byte    4,   -4, 	   0,   -4, 	  -1,   -1, 	  -1,   -7
.2byte    2,   -7, 	  -3,   -6, 	   5,   -1, 	  -1,   -7
.2byte    4,  -10, 	  -2,   -3, 	   3,    0, 	  -1,   -7
.2byte    2,   -7, 	  -5,   -8, 	   3,   -1, 	  -1,   -6
.2byte   -1,  -10, 	   6,   -3, 	  -7,   -3, 	  -1,   -7
.2byte   -1,  -12, 	   6,   -3, 	  -7,   -3, 	   0,   -7
.2byte   -1,   -6, 	   6,   -6, 	  -7,   -6, 	   0,   -6
.2byte   -3,   -7, 	   2,   -6, 	  -6,   -1, 	   0,   -7
.2byte   -5,  -10, 	   1,   -3, 	  -4,    0, 	   0,   -7
.2byte   -3,   -7, 	   4,   -8, 	  -4,   -1, 	   0,   -6
.2byte   -5,   -4, 	  -2,   -4, 	  -1,    0, 	   0,   -6
.2byte   -5,   -9, 	  -1,   -2, 	  -4,    0, 	   0,   -6
.2byte   -5,   -4, 	  -1,   -4, 	   0,   -1, 	   0,   -7
.2byte   -4,   -3, 	  -6,   -2, 	   4,   -1, 	   0,   -6
.2byte   -4,   -9, 	  -5,   -2, 	   0,    0, 	  -1,   -6
.2byte   -5,   -4, 	  -4,   -5, 	   3,   -1, 	   0,   -6
.2byte   -1,   -2, 	  -6,   -1, 	   5,   -1, 	   0,   -5
.2byte    0,  -12, 	  -7,   -1, 	   6,   -1, 	   0,   -7
.2byte    0,   -2, 	  -7,    0, 	   6,    0, 	   0,   -5
.2byte    3,   -3, 	   5,   -2, 	  -5,   -1, 	  -1,   -6
.2byte    0,  -13, 	   5,   -3, 	  -5,   -1, 	  -1,   -6
.2byte    4,   -3, 	   6,   -1, 	  -4,    0, 	   0,   -5
.2byte    4,   -4, 	   1,   -4, 	   0,    0, 	  -1,   -6
.2byte    1,  -12, 	   1,   -4, 	   0,   -1, 	  -1,   -7
.2byte    5,   -4, 	   1,   -2, 	  -1,    0, 	   0,   -6
.2byte    2,   -7, 	  -3,   -6, 	   5,   -1, 	  -1,   -7
.2byte    2,  -12, 	  -5,   -5, 	   5,   -1, 	  -1,   -6
.2byte    4,   -6, 	  -3,   -4, 	   3,   -1, 	  -1,   -6
.2byte   -1,  -10, 	   6,   -3, 	  -7,   -3, 	  -1,   -7
.2byte    0,  -13, 	   6,   -3, 	  -7,   -3, 	   0,   -7
.2byte    0,  -11, 	   6,   -3, 	  -7,   -3, 	   0,   -8
.2byte   -3,   -7, 	   2,   -6, 	  -6,   -1, 	   0,   -7
.2byte   -3,  -12, 	   4,   -5, 	  -6,   -1, 	   0,   -6
.2byte   -5,   -6, 	   2,   -4, 	  -4,   -1, 	   0,   -6
.2byte   -5,   -4, 	  -2,   -4, 	  -1,    0, 	   0,   -6
.2byte   -2,  -12, 	  -2,   -4, 	  -1,   -1, 	   0,   -7
.2byte   -6,   -4, 	  -2,   -2, 	   0,    0, 	  -1,   -6
.2byte   -4,   -3, 	  -6,   -2, 	   4,   -1, 	   0,   -6
.2byte   -1,  -13, 	  -6,   -3, 	   4,   -1, 	   0,   -6
.2byte   -5,   -3, 	  -7,   -1, 	   3,    0, 	  -1,   -5
.2byte   -1,   -2, 	  -6,   -1, 	   5,   -1, 	   0,   -5
.2byte   -1,  -11, 	  -5,   -1, 	   4,   -1, 	   0,   -7
.2byte    3,   -3, 	   5,   -2, 	  -5,   -1, 	  -1,   -6
.2byte    3,   -9, 	   4,   -2, 	  -1,    0, 	   0,   -6
.2byte    4,   -4, 	   1,   -4, 	   0,    0, 	  -1,   -6
.2byte    4,   -9, 	   0,   -2, 	   3,    0, 	  -1,   -6
.2byte    2,   -7, 	  -3,   -6, 	   5,   -1, 	  -1,   -7
.2byte    4,  -10, 	  -2,   -3, 	   3,    0, 	  -1,   -7
.2byte   -1,  -10, 	   6,   -3, 	  -7,   -3, 	  -1,   -7
.2byte   -1,  -12, 	   6,   -3, 	  -7,   -3, 	   0,   -7
.2byte   -3,   -7, 	   2,   -6, 	  -6,   -1, 	   0,   -7
.2byte   -5,  -10, 	   1,   -3, 	  -4,    0, 	   0,   -7
.2byte   -5,   -4, 	  -2,   -4, 	  -1,    0, 	   0,   -6
.2byte   -5,   -9, 	  -1,   -2, 	  -4,    0, 	   0,   -6
.2byte   -4,   -3, 	  -6,   -2, 	   4,   -1, 	   0,   -6
.2byte   -4,   -9, 	  -5,   -2, 	   0,    0, 	  -1,   -6
.2byte   -4,   -3, 	  -4,   -1, 	   1,    0, 	   0,   -6
.2byte   -4,   -2, 	  -5,   -1, 	   1,    0, 	   0,   -5
.2byte   -1,   -8, 	  -7,   -1, 	   6,   -1, 	   0,   -5
.2byte    3,   -6, 	   8,   -6, 	  -1,   -1, 	   0,   -6
.2byte    5,   -6, 	   5,   -5, 	   4,   -2, 	  -1,   -6
.2byte    3,  -11, 	  -3,   -9, 	   7,   -4, 	  -1,   -6
.2byte    0,  -11, 	   7,   -6, 	  -8,   -6, 	   0,   -5
.2byte   -4,  -11, 	   2,   -9, 	  -8,   -4, 	   0,   -6
.2byte   -6,   -6, 	  -6,   -5, 	  -5,   -2, 	   0,   -6
.2byte   -4,   -6, 	  -9,   -6, 	   0,   -1, 	  -1,   -6
.2byte   -5,   -4, 	  -2,   -4, 	  -1,    0, 	   0,   -6
.2byte   -5,   -4, 	  -1,   -4, 	   0,   -1, 	   0,   -7
.2byte   -4,   -3, 	  -6,   -2, 	   4,   -1, 	   0,   -6
.2byte   -5,   -4, 	  -4,   -5, 	   3,   -1, 	   0,   -6
.2byte   -1,   -2, 	  -6,   -1, 	   5,   -1, 	   0,   -5
.2byte   -1,   -2, 	  -5,   -1, 	   4,   -1, 	   0,   -5
.2byte    3,   -3, 	   5,   -2, 	  -5,   -1, 	  -1,   -6
.2byte    4,   -4, 	   3,   -5, 	  -4,   -1, 	  -1,   -6
.2byte    4,   -4, 	   1,   -4, 	   0,    0, 	  -1,   -6
.2byte    4,   -4, 	   0,   -4, 	  -1,   -1, 	  -1,   -7
.2byte    2,   -7, 	  -3,   -6, 	   5,   -1, 	  -1,   -7
.2byte    2,   -7, 	  -5,   -8, 	   3,   -1, 	  -1,   -6
.2byte   -1,  -10, 	   6,   -3, 	  -7,   -3, 	  -1,   -7
.2byte   -1,   -6, 	   6,   -6, 	  -7,   -6, 	   0,   -6
.2byte   -3,   -7, 	   2,   -6, 	  -6,   -1, 	   0,   -7
.2byte   -3,   -7, 	   4,   -8, 	  -4,   -1, 	   0,   -6
.2byte    0,  -12, 	  -7,   -1, 	   6,   -1, 	   0,   -7
.2byte   -1,  -13, 	  -6,   -3, 	   4,   -1, 	   0,   -6
.2byte   -2,  -12, 	  -2,   -4, 	  -1,   -1, 	   0,   -7
.2byte   -3,  -12, 	   4,   -5, 	  -6,   -1, 	   0,   -6
.2byte    0,  -13, 	   6,   -3, 	  -7,   -3, 	   0,   -7
.2byte    2,  -12, 	  -5,   -5, 	   5,   -1, 	  -1,   -6
.2byte    1,  -12, 	   1,   -4, 	   0,   -1, 	  -1,   -7
.2byte    0,  -13, 	   5,   -3, 	  -5,   -1, 	  -1,   -6
.2byte   -1,  -10, 	  -5,    0, 	   4,    0, 	   0,   -6
.2byte    3,   -9, 	   4,   -2, 	  -1,    0, 	   0,   -6
.2byte    4,   -9, 	   0,   -2, 	   3,    0, 	  -1,   -6
.2byte    4,  -10, 	  -2,   -3, 	   3,    0, 	  -1,   -7
.2byte   -1,  -12, 	   6,   -3, 	  -7,   -3, 	   0,   -7
.2byte   -5,  -10, 	   1,   -3, 	  -4,    0, 	   0,   -7
.2byte   -5,   -9, 	  -1,   -2, 	  -4,    0, 	   0,   -6
.2byte   -4,   -9, 	  -5,   -2, 	   0,    0, 	  -1,   -6
.2byte   -1,   -2, 	  -6,   -1, 	   5,   -1, 	   0,   -5
.2byte   -1,  -10, 	  -5,    0, 	   4,    0, 	   0,   -6
.2byte    0,   -2, 	  -7,    0, 	   6,    0, 	   0,   -5
.2byte    3,   -3, 	   5,   -2, 	  -5,   -1, 	  -1,   -6
.2byte    3,   -9, 	   4,   -2, 	  -1,    0, 	   0,   -6
.2byte    3,   -3, 	   5,   -1, 	  -5,    0, 	  -1,   -5
.2byte    4,   -4, 	   1,   -4, 	   0,    0, 	  -1,   -6
.2byte    4,   -9, 	   0,   -2, 	   3,    0, 	  -1,   -6
.2byte    5,   -4, 	   1,   -2, 	  -1,    0, 	   0,   -6
.2byte    2,   -7, 	  -3,   -6, 	   5,   -1, 	  -1,   -7
.2byte    4,  -10, 	  -2,   -3, 	   3,    0, 	  -1,   -7
.2byte    4,   -6, 	  -3,   -4, 	   3,   -1, 	  -1,   -6
.2byte   -1,  -10, 	   6,   -3, 	  -7,   -3, 	  -1,   -7
.2byte   -1,  -12, 	   6,   -3, 	  -7,   -3, 	   0,   -7
.2byte    0,  -11, 	   6,   -3, 	  -7,   -3, 	   0,   -8
.2byte   -3,   -7, 	   2,   -6, 	  -6,   -1, 	   0,   -7
.2byte   -5,  -10, 	   1,   -3, 	  -4,    0, 	   0,   -7
.2byte   -5,   -6, 	   2,   -4, 	  -4,   -1, 	   0,   -6
.2byte   -5,   -4, 	  -2,   -4, 	  -1,    0, 	   0,   -6
.2byte   -5,   -9, 	  -1,   -2, 	  -4,    0, 	   0,   -6
.2byte   -6,   -4, 	  -2,   -2, 	   0,    0, 	  -1,   -6
.2byte   -4,   -3, 	  -6,   -2, 	   4,   -1, 	   0,   -6
.2byte   -4,   -9, 	  -5,   -2, 	   0,    0, 	  -1,   -6
.2byte   -4,   -3, 	  -6,   -1, 	   4,    0, 	   0,   -5
.2byte    0,   -2, 	  -7,    0, 	   6,    0, 	   0,   -5
.2byte   -5,   -3, 	  -7,   -1, 	   3,    0, 	  -1,   -5
.2byte   -6,   -3, 	  -2,   -1, 	   0,    1, 	  -1,   -5
.2byte   -6,   -5, 	   1,   -3, 	  -5,    0, 	  -1,   -5
.2byte    0,   -9, 	   6,   -1, 	  -7,   -1, 	   0,   -6
.2byte    5,   -5, 	  -2,   -3, 	   4,    0, 	   0,   -5
.2byte    5,   -3, 	   1,   -1, 	  -1,    1, 	   0,   -5
.2byte    4,   -3, 	   6,   -1, 	  -4,    0, 	   0,   -5
.2byte   -1,   -2, 	  -6,   -1, 	   5,   -1, 	   0,   -5
.2byte   -4,   -3, 	  -6,   -2, 	   4,   -1, 	   0,   -6
.2byte   -5,   -4, 	  -2,   -4, 	  -1,    0, 	   0,   -6
.2byte   -3,   -7, 	   2,   -6, 	  -6,   -1, 	   0,   -7
.2byte   -1,  -10, 	   6,   -3, 	  -7,   -3, 	  -1,   -7
.2byte    2,   -7, 	  -3,   -6, 	   5,   -1, 	  -1,   -7
.2byte    4,   -4, 	   1,   -4, 	   0,    0, 	  -1,   -6
.2byte    3,   -3, 	   5,   -2, 	  -5,   -1, 	  -1,   -6
sSphealAnimTable1:
.4byte sSphealAnims_1_1
.4byte sSphealAnims_1_2
.4byte sSphealAnims_1_3
.4byte sSphealAnims_1_4
.4byte sSphealAnims_1_5
.4byte sSphealAnims_1_6
.4byte sSphealAnims_1_7
.4byte sSphealAnims_1_8
sSphealAnimTable2:
.4byte sSphealAnims_2_1
.4byte sSphealAnims_2_2
.4byte sSphealAnims_2_3
.4byte sSphealAnims_2_4
.4byte sSphealAnims_2_5
.4byte sSphealAnims_2_6
.4byte sSphealAnims_2_7
.4byte sSphealAnims_2_8
sSphealAnimTable3:
.4byte sSphealAnims_3_1
.4byte sSphealAnims_3_2
.4byte sSphealAnims_3_3
.4byte sSphealAnims_3_4
.4byte sSphealAnims_3_5
.4byte sSphealAnims_3_6
.4byte sSphealAnims_3_7
.4byte sSphealAnims_3_8
sSphealAnimTable4:
.4byte sSphealAnims_4_1
.4byte sSphealAnims_4_2
.4byte sSphealAnims_4_3
.4byte sSphealAnims_4_4
.4byte sSphealAnims_4_5
.4byte sSphealAnims_4_6
.4byte sSphealAnims_4_7
.4byte sSphealAnims_4_8
sSphealAnimTable5:
.4byte sSphealAnims_5_1
.4byte sSphealAnims_5_2
.4byte sSphealAnims_5_3
.4byte sSphealAnims_5_4
.4byte sSphealAnims_5_5
.4byte sSphealAnims_5_6
.4byte sSphealAnims_5_7
.4byte sSphealAnims_5_8
sSphealAnimTable6:
.4byte sSphealAnims_6_1
.4byte sSphealAnims_6_1
.4byte sSphealAnims_6_1
.4byte sSphealAnims_6_1
.4byte sSphealAnims_6_1
.4byte sSphealAnims_6_1
.4byte sSphealAnims_6_1
.4byte sSphealAnims_6_1
sSphealAnimTable7:
.4byte sSphealAnims_7_1
.4byte sSphealAnims_7_2
.4byte sSphealAnims_7_3
.4byte sSphealAnims_7_4
.4byte sSphealAnims_7_5
.4byte sSphealAnims_7_6
.4byte sSphealAnims_7_7
.4byte sSphealAnims_7_8
sSphealAnimTable8:
.4byte sSphealAnims_8_1
.4byte sSphealAnims_8_2
.4byte sSphealAnims_8_3
.4byte sSphealAnims_8_4
.4byte sSphealAnims_8_5
.4byte sSphealAnims_8_6
.4byte sSphealAnims_8_7
.4byte sSphealAnims_8_8
sSphealAnimTable9:
.4byte sSphealAnims_9_1
.4byte sSphealAnims_9_2
.4byte sSphealAnims_9_3
.4byte sSphealAnims_9_4
.4byte sSphealAnims_9_5
.4byte sSphealAnims_9_6
.4byte sSphealAnims_9_7
.4byte sSphealAnims_9_8
sSphealAnimTable10:
.4byte sSphealAnims_10_1
.4byte sSphealAnims_10_2
.4byte sSphealAnims_10_3
.4byte sSphealAnims_10_4
.4byte sSphealAnims_10_5
.4byte sSphealAnims_10_6
.4byte sSphealAnims_10_7
.4byte sSphealAnims_10_8
sSphealAnimTable11:
.4byte sSphealAnims_11_1
.4byte sSphealAnims_11_2
.4byte sSphealAnims_11_3
.4byte sSphealAnims_11_4
.4byte sSphealAnims_11_5
.4byte sSphealAnims_11_6
.4byte sSphealAnims_11_7
.4byte sSphealAnims_11_8
sSphealAnimTable12:
.4byte sSphealAnims_12_1
.4byte sSphealAnims_12_2
.4byte sSphealAnims_12_3
.4byte sSphealAnims_12_4
.4byte sSphealAnims_12_5
.4byte sSphealAnims_12_6
.4byte sSphealAnims_12_7
.4byte sSphealAnims_12_8
sSphealAnimTable13:
.4byte sSphealAnims_13_1
.4byte sSphealAnims_13_2
.4byte sSphealAnims_13_3
.4byte sSphealAnims_13_4
.4byte sSphealAnims_13_5
.4byte sSphealAnims_13_6
.4byte sSphealAnims_13_7
.4byte sSphealAnims_13_8
sAxAnimationsSpheal:
.4byte sSphealAnimTable1
.4byte sSphealAnimTable2
.4byte sSphealAnimTable3
.4byte sSphealAnimTable4
.4byte sSphealAnimTable5
.4byte sSphealAnimTable6
.4byte sSphealAnimTable7
.4byte sSphealAnimTable8
.4byte sSphealAnimTable9
.4byte sSphealAnimTable10
.4byte sSphealAnimTable11
.4byte sSphealAnimTable12
.4byte sSphealAnimTable13
sAxSpritesSpheal:
.4byte sSphealSprites1
.4byte sSphealSprites2
.4byte sSphealSprites3
.4byte sSphealSprites4
.4byte sSphealSprites5
.4byte sSphealSprites6
.4byte sSphealSprites7
.4byte sSphealSprites8
.4byte sSphealSprites9
.4byte sSphealSprites10
.4byte sSphealSprites11
.4byte sSphealSprites12
.4byte sSphealSprites13
.4byte sSphealSprites14
.4byte sSphealSprites15
.4byte sSphealSprites16
.4byte sSphealSprites17
.4byte sSphealSprites18
.4byte sSphealSprites19
.4byte sSphealSprites20
.4byte sSphealSprites21
.4byte sSphealSprites22
.4byte sSphealSprites23
.4byte sSphealSprites24
.4byte sSphealSprites25
.4byte sSphealSprites26
.4byte sSphealSprites27
.4byte sSphealSprites28
.4byte sSphealSprites29
.4byte sSphealSprites30
.4byte sSphealSprites31
.4byte sSphealSprites32
.4byte sSphealSprites33
.4byte sSphealSprites34
.4byte sSphealSprites35
.4byte sSphealSprites36
.4byte sSphealSprites37
.4byte sSphealSprites38
.4byte sSphealSprites39
.4byte sSphealSprites40
.4byte sSphealSprites41
.4byte sSphealSprites42
.4byte sSphealSprites43
.4byte sSphealSprites44
.4byte sSphealSprites45
sAxMainSpheal:
ax_main sAxPosesSpheal, sAxAnimationsSpheal, 13, sAxSpritesSpheal, sAxPositionsSpheal
