.global gAxStarmie
gAxStarmie:
ax_siro sAxMainStarmie
sStarmiePose1:
ax_pose 0, 0x01e9, 0x80f4, 0x2c00
ax_pose_terminator
sStarmiePose2:
ax_pose 1, 0x01e9, 0x80f4, 0x2c00
ax_pose_terminator
sStarmiePose3:
ax_pose 2, 0x01e9, 0x80f4, 0x2c00
ax_pose_terminator
sStarmiePose4:
ax_pose 3, 0x01eb, 0x90ed, 0x2c00
ax_pose_terminator
sStarmiePose5:
ax_pose 4, 0x01eb, 0x90ed, 0x2c00
ax_pose_terminator
sStarmiePose6:
ax_pose 5, 0x01eb, 0x90ed, 0x2c00
ax_pose_terminator
sStarmiePose7:
ax_pose 6, 0x81eb, 0x90f9, 0x2c00
ax_pose_terminator
sStarmiePose8:
ax_pose 7, 0x81eb, 0x90f8, 0x2c00
ax_pose_terminator
sStarmiePose9:
ax_pose 8, 0x81ec, 0x90f9, 0x2c00
ax_pose_terminator
sStarmiePose10:
ax_pose 9, 0x01eb, 0x90eb, 0x2c00
ax_pose_terminator
sStarmiePose11:
ax_pose 10, 0x01eb, 0x90ee, 0x2c00
ax_pose_terminator
sStarmiePose12:
ax_pose 11, 0x01eb, 0x90ed, 0x2c00
ax_pose_terminator
sStarmiePose13:
ax_pose 12, 0x01e9, 0x80f4, 0x2c00
ax_pose_terminator
sStarmiePose14:
ax_pose 13, 0x01e9, 0x80f4, 0x2c00
ax_pose_terminator
sStarmiePose15:
ax_pose 14, 0x01e9, 0x80f4, 0x2c00
ax_pose_terminator
sStarmiePose16:
ax_pose 9, 0x01eb, 0x80f4, 0x2c00
ax_pose_terminator
sStarmiePose17:
ax_pose 10, 0x01eb, 0x80f4, 0x2c00
ax_pose_terminator
sStarmiePose18:
ax_pose 11, 0x01eb, 0x80f4, 0x2c00
ax_pose_terminator
sStarmiePose19:
ax_pose 6, 0x81eb, 0x80f8, 0x2c00
ax_pose_terminator
sStarmiePose20:
ax_pose 7, 0x81eb, 0x80f9, 0x2c00
ax_pose_terminator
sStarmiePose21:
ax_pose 8, 0x81eb, 0x80f8, 0x2c00
ax_pose_terminator
sStarmiePose22:
ax_pose 3, 0x01eb, 0x80f4, 0x2c00
ax_pose_terminator
sStarmiePose23:
ax_pose 4, 0x01eb, 0x80f4, 0x2c00
ax_pose_terminator
sStarmiePose24:
ax_pose 5, 0x01eb, 0x80f4, 0x2c00
ax_pose_terminator
sStarmiePose25:
ax_pose 0, 0x01e9, 0x80f4, 0x2c00
ax_pose_terminator
sStarmiePose26:
ax_pose 15, 0x01e9, 0x80f4, 0x2c00
ax_pose_terminator
sStarmiePose27:
ax_pose 16, 0x01e9, 0x80f4, 0x2c00
ax_pose_terminator
sStarmiePose28:
ax_pose 17, 0x01e9, 0x80f4, 0x2c00
ax_pose_terminator
sStarmiePose29:
ax_pose 3, 0x01eb, 0x90ed, 0x2c00
ax_pose_terminator
sStarmiePose30:
ax_pose 18, 0x01eb, 0x90ef, 0x2c00
ax_pose_terminator
sStarmiePose31:
ax_pose 19, 0x01ea, 0x90f0, 0x2c00
ax_pose_terminator
sStarmiePose32:
ax_pose 6, 0x81eb, 0x90f9, 0x2c00
ax_pose_terminator
sStarmiePose33:
ax_pose 20, 0x01e9, 0x90ec, 0x2c00
ax_pose_terminator
sStarmiePose34:
ax_pose 9, 0x01eb, 0x90eb, 0x2c00
ax_pose_terminator
sStarmiePose35:
ax_pose 21, 0x01e9, 0x90ee, 0x2c00
ax_pose_terminator
sStarmiePose36:
ax_pose 12, 0x01e9, 0x80f4, 0x2c00
ax_pose_terminator
sStarmiePose37:
ax_pose 22, 0x41ef, 0x80f3, 0x2c00
ax_pose_terminator
sStarmiePose38:
ax_pose 9, 0x01eb, 0x80f4, 0x2c00
ax_pose_terminator
sStarmiePose39:
ax_pose 21, 0x01e9, 0x80f1, 0x2c00
ax_pose_terminator
sStarmiePose40:
ax_pose 6, 0x81eb, 0x80f8, 0x2c00
ax_pose_terminator
sStarmiePose41:
ax_pose 20, 0x01e9, 0x80f5, 0x2c00
ax_pose_terminator
sStarmiePose42:
ax_pose 3, 0x01eb, 0x80f4, 0x2c00
ax_pose_terminator
sStarmiePose43:
ax_pose 18, 0x01eb, 0x80f2, 0x2c00
ax_pose_terminator
sStarmiePose44:
ax_pose 0, 0x01e9, 0x80f4, 0x2c00
ax_pose_terminator
sStarmiePose45:
ax_pose 15, 0x01e9, 0x80f4, 0x2c00
ax_pose_terminator
sStarmiePose46:
ax_pose 16, 0x01e9, 0x80f4, 0x2c00
ax_pose_terminator
sStarmiePose47:
ax_pose 17, 0x01e9, 0x80f4, 0x2c00
ax_pose_terminator
sStarmiePose48:
ax_pose 3, 0x01eb, 0x90ed, 0x2c00
ax_pose_terminator
sStarmiePose49:
ax_pose 18, 0x01eb, 0x90ef, 0x2c00
ax_pose_terminator
sStarmiePose50:
ax_pose 19, 0x01ea, 0x90f0, 0x2c00
ax_pose_terminator
sStarmiePose51:
ax_pose 6, 0x81eb, 0x90f9, 0x2c00
ax_pose_terminator
sStarmiePose52:
ax_pose 20, 0x01e9, 0x90ec, 0x2c00
ax_pose_terminator
sStarmiePose53:
ax_pose 9, 0x01eb, 0x90eb, 0x2c00
ax_pose_terminator
sStarmiePose54:
ax_pose 21, 0x01e9, 0x90ee, 0x2c00
ax_pose_terminator
sStarmiePose55:
ax_pose 12, 0x01e9, 0x80f4, 0x2c00
ax_pose_terminator
sStarmiePose56:
ax_pose 22, 0x41ef, 0x80f3, 0x2c00
ax_pose_terminator
sStarmiePose57:
ax_pose 9, 0x01eb, 0x80f4, 0x2c00
ax_pose_terminator
sStarmiePose58:
ax_pose 21, 0x01e9, 0x80f1, 0x2c00
ax_pose_terminator
sStarmiePose59:
ax_pose 6, 0x81eb, 0x80f8, 0x2c00
ax_pose_terminator
sStarmiePose60:
ax_pose 20, 0x01e9, 0x80f5, 0x2c00
ax_pose_terminator
sStarmiePose61:
ax_pose 3, 0x01eb, 0x80f4, 0x2c00
ax_pose_terminator
sStarmiePose62:
ax_pose 18, 0x01eb, 0x80f2, 0x2c00
ax_pose_terminator
sStarmiePose63:
ax_pose 0, 0x01e9, 0x80f4, 0x2c00
ax_pose_terminator
sStarmiePose64:
ax_pose 1, 0x01e9, 0x80f4, 0x2c00
ax_pose_terminator
sStarmiePose65:
ax_pose 2, 0x01e9, 0x80f4, 0x2c00
ax_pose_terminator
sStarmiePose66:
ax_pose 23, 0x01e9, 0x80f4, 0x2c00
ax_pose_terminator
sStarmiePose67:
ax_pose 24, 0x01e9, 0x80f4, 0x2c00
ax_pose_terminator
sStarmiePose68:
ax_pose 3, 0x01eb, 0x90ed, 0x2c00
ax_pose_terminator
sStarmiePose69:
ax_pose 4, 0x01eb, 0x90ed, 0x2c00
ax_pose_terminator
sStarmiePose70:
ax_pose 5, 0x01eb, 0x90ed, 0x2c00
ax_pose_terminator
sStarmiePose71:
ax_pose 19, 0x01ea, 0x90f0, 0x2c00
ax_pose_terminator
sStarmiePose72:
ax_pose 25, 0x01ea, 0x90f0, 0x2c00
ax_pose_terminator
sStarmiePose73:
ax_pose 6, 0x81eb, 0x90f9, 0x2c00
ax_pose_terminator
sStarmiePose74:
ax_pose 7, 0x81eb, 0x90f8, 0x2c00
ax_pose_terminator
sStarmiePose75:
ax_pose 8, 0x81ec, 0x90f9, 0x2c00
ax_pose_terminator
sStarmiePose76:
ax_pose 26, 0x81e9, 0x90f9, 0x2c00
ax_pose_terminator
sStarmiePose77:
ax_pose 27, 0x81e9, 0x90f9, 0x2c00
ax_pose_terminator
sStarmiePose78:
ax_pose 9, 0x01eb, 0x90eb, 0x2c00
ax_pose_terminator
sStarmiePose79:
ax_pose 10, 0x01eb, 0x90ee, 0x2c00
ax_pose_terminator
sStarmiePose80:
ax_pose 11, 0x01eb, 0x90ed, 0x2c00
ax_pose_terminator
sStarmiePose81:
ax_pose 28, 0x01e9, 0x90ed, 0x2c00
ax_pose_terminator
sStarmiePose82:
ax_pose 29, 0x01e9, 0x90ed, 0x2c00
ax_pose_terminator
sStarmiePose83:
ax_pose 12, 0x01e9, 0x80f4, 0x2c00
ax_pose_terminator
sStarmiePose84:
ax_pose 13, 0x01e9, 0x80f4, 0x2c00
ax_pose_terminator
sStarmiePose85:
ax_pose 14, 0x01e9, 0x80f4, 0x2c00
ax_pose_terminator
sStarmiePose86:
ax_pose 30, 0x01e7, 0x80f2, 0x2c00
ax_pose_terminator
sStarmiePose87:
ax_pose 31, 0x01e7, 0x80f2, 0x2c00
ax_pose_terminator
sStarmiePose88:
ax_pose 9, 0x01eb, 0x80f4, 0x2c00
ax_pose_terminator
sStarmiePose89:
ax_pose 10, 0x01eb, 0x80f4, 0x2c00
ax_pose_terminator
sStarmiePose90:
ax_pose 11, 0x01eb, 0x80f4, 0x2c00
ax_pose_terminator
sStarmiePose91:
ax_pose 28, 0x01e9, 0x80f2, 0x2c00
ax_pose_terminator
sStarmiePose92:
ax_pose 29, 0x01e9, 0x80f2, 0x2c00
ax_pose_terminator
sStarmiePose93:
ax_pose 6, 0x81eb, 0x80f8, 0x2c00
ax_pose_terminator
sStarmiePose94:
ax_pose 7, 0x81eb, 0x80f9, 0x2c00
ax_pose_terminator
sStarmiePose95:
ax_pose 8, 0x81eb, 0x80f8, 0x2c00
ax_pose_terminator
sStarmiePose96:
ax_pose 26, 0x81e9, 0x80f8, 0x2c00
ax_pose_terminator
sStarmiePose97:
ax_pose 27, 0x81e9, 0x80f8, 0x2c00
ax_pose_terminator
sStarmiePose98:
ax_pose 3, 0x01eb, 0x80f4, 0x2c00
ax_pose_terminator
sStarmiePose99:
ax_pose 4, 0x01eb, 0x80f4, 0x2c00
ax_pose_terminator
sStarmiePose100:
ax_pose 5, 0x01eb, 0x80f4, 0x2c00
ax_pose_terminator
sStarmiePose101:
ax_pose 19, 0x01ea, 0x80f1, 0x2c00
ax_pose_terminator
sStarmiePose102:
ax_pose 25, 0x01ea, 0x80f1, 0x2c00
ax_pose_terminator
sStarmiePose103:
ax_pose 0, 0x01eb, 0x80f4, 0x2c00
ax_pose_terminator
sStarmiePose104:
ax_pose 3, 0x01ed, 0x80f4, 0x2c00
ax_pose_terminator
sStarmiePose105:
ax_pose 6, 0x81ed, 0x80f8, 0x2c00
ax_pose_terminator
sStarmiePose106:
ax_pose 9, 0x01ed, 0x80f4, 0x2c00
ax_pose_terminator
sStarmiePose107:
ax_pose 12, 0x01eb, 0x80f4, 0x2c00
ax_pose_terminator
sStarmiePose108:
ax_pose 9, 0x01ed, 0x90ed, 0x2c00
ax_pose_terminator
sStarmiePose109:
ax_pose 6, 0x81ed, 0x90f9, 0x2c00
ax_pose_terminator
sStarmiePose110:
ax_pose 3, 0x01ed, 0x90ed, 0x2c00
ax_pose_terminator
sStarmiePose111:
ax_pose 32, 0x01f1, 0x80f5, 0x2c00
ax_pose_terminator
sStarmiePose112:
ax_pose 33, 0x01f1, 0x80f5, 0x2c00
ax_pose_terminator
sStarmiePose113:
ax_pose 34, 0x01e4, 0x80f3, 0x2c00
ax_pose_terminator
sStarmiePose114:
ax_pose 35, 0x01e4, 0x90eb, 0x2c00
ax_pose_terminator
sStarmiePose115:
ax_pose 36, 0x01e8, 0x90ec, 0x2c00
ax_pose_terminator
sStarmiePose116:
ax_pose 37, 0x01e7, 0x90ed, 0x2c00
ax_pose_terminator
sStarmiePose117:
ax_pose 38, 0x01e9, 0x80f3, 0x2c00
ax_pose_terminator
sStarmiePose118:
ax_pose 37, 0x01e7, 0x80f3, 0x2c00
ax_pose_terminator
sStarmiePose119:
ax_pose 36, 0x01e8, 0x80f4, 0x2c00
ax_pose_terminator
sStarmiePose120:
ax_pose 35, 0x01e4, 0x80f5, 0x2c00
ax_pose_terminator
sStarmiePose121:
ax_pose 0, 0x01eb, 0x80f4, 0x2c00
ax_pose_terminator
sStarmiePose122:
ax_pose 3, 0x01ed, 0x80f4, 0x2c00
ax_pose_terminator
sStarmiePose123:
ax_pose 6, 0x81ed, 0x80f8, 0x2c00
ax_pose_terminator
sStarmiePose124:
ax_pose 9, 0x01ed, 0x80f4, 0x2c00
ax_pose_terminator
sStarmiePose125:
ax_pose 12, 0x01eb, 0x80f4, 0x2c00
ax_pose_terminator
sStarmiePose126:
ax_pose 9, 0x01ed, 0x90ed, 0x2c00
ax_pose_terminator
sStarmiePose127:
ax_pose 6, 0x81ed, 0x90f9, 0x2c00
ax_pose_terminator
sStarmiePose128:
ax_pose 3, 0x01ed, 0x90ed, 0x2c00
ax_pose_terminator
sStarmiePose129:
ax_pose 0, 0x01eb, 0x80f4, 0x2c00
ax_pose_terminator
sStarmiePose130:
ax_pose 3, 0x01ed, 0x80f4, 0x2c00
ax_pose_terminator
sStarmiePose131:
ax_pose 6, 0x81ed, 0x80f8, 0x2c00
ax_pose_terminator
sStarmiePose132:
ax_pose 9, 0x01ed, 0x80f4, 0x2c00
ax_pose_terminator
sStarmiePose133:
ax_pose 12, 0x01eb, 0x80f4, 0x2c00
ax_pose_terminator
sStarmiePose134:
ax_pose 9, 0x01ed, 0x90ed, 0x2c00
ax_pose_terminator
sStarmiePose135:
ax_pose 6, 0x81ed, 0x90f9, 0x2c00
ax_pose_terminator
sStarmiePose136:
ax_pose 3, 0x01ed, 0x90ed, 0x2c00
ax_pose_terminator
sStarmiePose137:
ax_pose 0, 0x01eb, 0x80f4, 0x2c00
ax_pose_terminator
sStarmiePose138:
ax_pose 3, 0x01ed, 0x90ed, 0x2c00
ax_pose_terminator
sStarmiePose139:
ax_pose 6, 0x81ed, 0x90f9, 0x2c00
ax_pose_terminator
sStarmiePose140:
ax_pose 9, 0x01ed, 0x90ed, 0x2c00
ax_pose_terminator
sStarmiePose141:
ax_pose 12, 0x01eb, 0x80f4, 0x2c00
ax_pose_terminator
sStarmiePose142:
ax_pose 9, 0x01ed, 0x80f4, 0x2c00
ax_pose_terminator
sStarmiePose143:
ax_pose 6, 0x81ed, 0x80f8, 0x2c00
ax_pose_terminator
sStarmiePose144:
ax_pose 3, 0x01ed, 0x80f4, 0x2c00
ax_pose_terminator
sStarmiePose145:
ax_pose 0, 0x01e9, 0x80f4, 0x2c00
ax_pose_terminator
sStarmiePose146:
ax_pose 15, 0x01e9, 0x80f4, 0x2c00
ax_pose_terminator
sStarmiePose147:
ax_pose 3, 0x01eb, 0x90ed, 0x2c00
ax_pose_terminator
sStarmiePose148:
ax_pose 18, 0x01eb, 0x90ed, 0x2c00
ax_pose_terminator
sStarmiePose149:
ax_pose 6, 0x81eb, 0x90f9, 0x2c00
ax_pose_terminator
sStarmiePose150:
ax_pose 20, 0x01e9, 0x90ec, 0x2c00
ax_pose_terminator
sStarmiePose151:
ax_pose 9, 0x01eb, 0x90eb, 0x2c00
ax_pose_terminator
sStarmiePose152:
ax_pose 21, 0x01e9, 0x90ee, 0x2c00
ax_pose_terminator
sStarmiePose153:
ax_pose 12, 0x01e9, 0x80f4, 0x2c00
ax_pose_terminator
sStarmiePose154:
ax_pose 22, 0x41ef, 0x80f3, 0x2c00
ax_pose_terminator
sStarmiePose155:
ax_pose 9, 0x01eb, 0x80f4, 0x2c00
ax_pose_terminator
sStarmiePose156:
ax_pose 21, 0x01e9, 0x80f1, 0x2c00
ax_pose_terminator
sStarmiePose157:
ax_pose 6, 0x81eb, 0x80f8, 0x2c00
ax_pose_terminator
sStarmiePose158:
ax_pose 20, 0x01e9, 0x80f5, 0x2c00
ax_pose_terminator
sStarmiePose159:
ax_pose 3, 0x01eb, 0x80f4, 0x2c00
ax_pose_terminator
sStarmiePose160:
ax_pose 18, 0x01eb, 0x80f4, 0x2c00
ax_pose_terminator
sStarmiePose161:
ax_pose 23, 0x01e9, 0x80f4, 0x2c00
ax_pose_terminator
sStarmiePose162:
ax_pose 19, 0x01e9, 0x80f2, 0x2c00
ax_pose_terminator
sStarmiePose163:
ax_pose 26, 0x81e9, 0x80f8, 0x2c00
ax_pose_terminator
sStarmiePose164:
ax_pose 28, 0x01e9, 0x80f2, 0x2c00
ax_pose_terminator
sStarmiePose165:
ax_pose 30, 0x01e7, 0x80f2, 0x2c00
ax_pose_terminator
sStarmiePose166:
ax_pose 28, 0x01e9, 0x90ef, 0x2c00
ax_pose_terminator
sStarmiePose167:
ax_pose 26, 0x81e9, 0x90f8, 0x2c00
ax_pose_terminator
sStarmiePose168:
ax_pose 19, 0x01e9, 0x90ee, 0x2c00
ax_pose_terminator
sStarmiePose169:
ax_pose 0, 0x01eb, 0x80f4, 0x2c00
ax_pose_terminator
sStarmiePose170:
ax_pose 3, 0x01ed, 0x80f4, 0x2c00
ax_pose_terminator
sStarmiePose171:
ax_pose 6, 0x81ed, 0x80f8, 0x2c00
ax_pose_terminator
sStarmiePose172:
ax_pose 9, 0x01ed, 0x80f4, 0x2c00
ax_pose_terminator
sStarmiePose173:
ax_pose 12, 0x01eb, 0x80f4, 0x2c00
ax_pose_terminator
sStarmiePose174:
ax_pose 9, 0x01ed, 0x90ed, 0x2c00
ax_pose_terminator
sStarmiePose175:
ax_pose 6, 0x81ed, 0x90f9, 0x2c00
ax_pose_terminator
sStarmiePose176:
ax_pose 3, 0x01ed, 0x90ed, 0x2c00
ax_pose_terminator
.align 2
sStarmieAnims_1_1:
ax_anim 8, 0, 0, 0, 0, 0, 0,
ax_anim 10, 0, 1, 0, 0, 0, 0,
ax_anim 8, 0, 0, 0, 0, 0, 0,
ax_anim 10, 0, 2, 0, 0, 0, 0,
ax_anim_terminator
sStarmieAnims_1_2:
ax_anim 8, 0, 3, 0, 0, 0, 0,
ax_anim 10, 0, 4, 0, 0, 0, 0,
ax_anim 8, 0, 3, 0, 0, 0, 0,
ax_anim 10, 0, 5, 0, 0, 0, 0,
ax_anim_terminator
sStarmieAnims_1_3:
ax_anim 8, 0, 6, 0, 0, 0, 0,
ax_anim 10, 0, 7, 0, 0, 0, 0,
ax_anim 8, 0, 6, 0, 0, 0, 0,
ax_anim 10, 0, 8, 0, 0, 0, 0,
ax_anim_terminator
sStarmieAnims_1_4:
ax_anim 8, 0, 9, 0, 0, 0, 0,
ax_anim 10, 0, 10, 0, 0, 0, 0,
ax_anim 8, 0, 9, 0, 0, 0, 0,
ax_anim 10, 0, 11, 0, 0, 0, 0,
ax_anim_terminator
sStarmieAnims_1_5:
ax_anim 8, 0, 12, 0, 0, 0, 0,
ax_anim 10, 0, 13, 0, 0, 0, 0,
ax_anim 8, 0, 12, 0, 0, 0, 0,
ax_anim 10, 0, 14, 0, 0, 0, 0,
ax_anim_terminator
sStarmieAnims_1_6:
ax_anim 8, 0, 15, 0, 0, 0, 0,
ax_anim 10, 0, 16, 0, 0, 0, 0,
ax_anim 8, 0, 15, 0, 0, 0, 0,
ax_anim 10, 0, 17, 0, 0, 0, 0,
ax_anim_terminator
sStarmieAnims_1_7:
ax_anim 8, 0, 18, 0, 0, 0, 0,
ax_anim 10, 0, 19, 0, 0, 0, 0,
ax_anim 8, 0, 18, 0, 0, 0, 0,
ax_anim 10, 0, 20, 0, 0, 0, 0,
ax_anim_terminator
sStarmieAnims_1_8:
ax_anim 8, 0, 21, 0, 0, 0, 0,
ax_anim 10, 0, 22, 0, 0, 0, 0,
ax_anim 8, 0, 21, 0, 0, 0, 0,
ax_anim 10, 0, 23, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sStarmieAnims_2_1:
ax_anim 2, 0, 25, 0, 0, 0, 0,
ax_anim 2, 0, 25, 0, -3, 0, -3,
ax_anim 4, 0, 26, 0, -5, 0, -5,
ax_anim 2, 0, 27, 0, -5, 0, -5,
ax_anim 2, 2, 26, 0, -5, 0, -5,
ax_anim 1, 0, 27, 0, 2, 0, 2,
ax_anim 1, 0, 26, 0, 10, 0, 10,
ax_anim 1, 0, 27, 0, 19, 0, 19,
ax_anim 2, 1, 26, 0, 19, 0, 19,
ax_anim 2, 0, 27, 0, 19, 0, 19,
ax_anim 2, 0, 26, 0, 19, 0, 19,
ax_anim 2, 0, 27, 0, 19, 0, 19,
ax_anim 2, 0, 26, 0, 19, 0, 19,
ax_anim 2, 0, 27, 0, 12, 0, 12,
ax_anim 2, 0, 24, 0, 4, 0, 4,
ax_anim_terminator
sStarmieAnims_2_2:
ax_anim 2, 0, 29, 0, 0, 0, 0,
ax_anim 2, 0, 29, -3, -3, -3, -3,
ax_anim 4, 0, 26, -5, -5, -5, -5,
ax_anim 2, 0, 27, -5, -5, -5, -5,
ax_anim 2, 2, 26, -5, -5, -5, -5,
ax_anim 1, 0, 27, 2, 2, 2, 2,
ax_anim 1, 0, 26, 10, 10, 10, 10,
ax_anim 1, 0, 27, 20, 19, 20, 19,
ax_anim 2, 1, 26, 20, 19, 20, 19,
ax_anim 2, 0, 27, 20, 19, 20, 19,
ax_anim 2, 0, 26, 20, 19, 20, 19,
ax_anim 2, 0, 27, 20, 19, 20, 19,
ax_anim 2, 0, 26, 20, 19, 20, 19,
ax_anim 2, 0, 27, 12, 12, 12, 12,
ax_anim 2, 0, 28, 4, 4, 4, 4,
ax_anim_terminator
sStarmieAnims_2_3:
ax_anim 2, 0, 32, 0, 0, 0, 0,
ax_anim 2, 0, 32, -3, 0, -3, 0,
ax_anim 4, 0, 26, -5, 0, -5, 0,
ax_anim 2, 0, 27, -5, 0, -5, 0,
ax_anim 2, 2, 26, -5, 0, -5, 0,
ax_anim 1, 0, 27, 2, 0, 2, 0,
ax_anim 1, 0, 26, 10, 0, 10, 0,
ax_anim 1, 0, 27, 20, 0, 20, 0,
ax_anim 2, 1, 26, 20, 0, 20, 0,
ax_anim 2, 0, 27, 20, 0, 20, 0,
ax_anim 2, 0, 26, 20, 0, 20, 0,
ax_anim 2, 0, 27, 20, 0, 20, 0,
ax_anim 2, 0, 26, 20, 0, 20, 0,
ax_anim 2, 0, 27, 12, 0, 12, 0,
ax_anim 2, 0, 31, 4, 0, 4, 0,
ax_anim_terminator
sStarmieAnims_2_4:
ax_anim 2, 0, 34, 0, 0, 0, 0,
ax_anim 2, 0, 34, -3, 3, -3, 3,
ax_anim 4, 0, 26, -5, 5, -5, 5,
ax_anim 2, 0, 27, -5, 5, -5, 5,
ax_anim 2, 2, 26, -5, 5, -5, 5,
ax_anim 1, 0, 27, 2, -2, 2, -2,
ax_anim 1, 0, 26, 10, -10, 10, -10,
ax_anim 1, 0, 27, 20, -19, 20, -19,
ax_anim 2, 1, 26, 20, -19, 20, -19,
ax_anim 2, 0, 27, 20, -19, 20, -19,
ax_anim 2, 0, 26, 20, -19, 20, -19,
ax_anim 2, 0, 27, 20, -19, 20, -19,
ax_anim 2, 0, 26, 20, -19, 20, -19,
ax_anim 2, 0, 27, 12, -12, 12, -12,
ax_anim 2, 0, 33, 4, -4, 4, -4,
ax_anim_terminator
sStarmieAnims_2_5:
ax_anim 2, 0, 36, 0, 0, 0, 0,
ax_anim 2, 0, 36, 0, 3, 0, 3,
ax_anim 4, 0, 26, 0, 5, 0, 5,
ax_anim 2, 0, 27, 0, 5, 0, 5,
ax_anim 2, 2, 26, 0, 5, 0, 5,
ax_anim 1, 0, 27, 0, -2, 0, -2,
ax_anim 1, 0, 26, 0, -10, 0, -10,
ax_anim 1, 0, 27, 0, -19, 0, -19,
ax_anim 2, 1, 26, 0, -19, 0, -19,
ax_anim 2, 0, 27, 0, -19, 0, -19,
ax_anim 2, 0, 26, 0, -19, 0, -19,
ax_anim 2, 0, 27, 0, -19, 0, -19,
ax_anim 2, 0, 26, 0, -19, 0, -19,
ax_anim 2, 0, 27, 0, -12, 0, -12,
ax_anim 2, 0, 35, 0, -4, 0, -4,
ax_anim_terminator
sStarmieAnims_2_6:
ax_anim 2, 0, 38, 0, 0, 0, 0,
ax_anim 2, 0, 38, 3, 3, 3, 3,
ax_anim 4, 0, 26, 5, 5, 5, 5,
ax_anim 2, 0, 27, 5, 5, 5, 5,
ax_anim 2, 2, 26, 5, 5, 5, 5,
ax_anim 1, 0, 27, -2, -2, -2, -2,
ax_anim 1, 0, 26, -10, -10, -10, -10,
ax_anim 1, 0, 27, -20, -19, -20, -19,
ax_anim 2, 1, 26, -20, -19, -20, -19,
ax_anim 2, 0, 27, -20, -19, -20, -19,
ax_anim 2, 0, 26, -20, -19, -20, -19,
ax_anim 2, 0, 27, -20, -19, -20, -19,
ax_anim 2, 0, 26, -20, -19, -20, -19,
ax_anim 2, 0, 27, -12, -12, -12, -12,
ax_anim 2, 0, 37, -4, -4, -4, -4,
ax_anim_terminator
sStarmieAnims_2_7:
ax_anim 2, 0, 40, 0, 0, 0, 0,
ax_anim 2, 0, 40, 3, 0, 3, 0,
ax_anim 4, 0, 26, 5, 0, 5, 0,
ax_anim 2, 0, 27, 5, 0, 5, 0,
ax_anim 2, 2, 26, 5, 0, 5, 0,
ax_anim 1, 0, 27, -2, 0, -2, 0,
ax_anim 1, 0, 26, -10, 0, -10, 0,
ax_anim 1, 0, 27, -20, 0, -20, 0,
ax_anim 2, 1, 26, -20, 0, -20, 0,
ax_anim 2, 0, 27, -20, 0, -20, 0,
ax_anim 2, 0, 26, -20, 0, -20, 0,
ax_anim 2, 0, 27, -20, 0, -20, 0,
ax_anim 2, 0, 26, -20, 0, -20, 0,
ax_anim 2, 0, 27, -12, 0, -12, 0,
ax_anim 2, 0, 39, -4, 0, -4, 0,
ax_anim_terminator
sStarmieAnims_2_8:
ax_anim 2, 0, 42, 0, 0, 0, 0,
ax_anim 2, 0, 42, 3, -3, 3, -3,
ax_anim 4, 0, 26, 5, -5, 5, -5,
ax_anim 2, 0, 27, 5, -5, 5, -5,
ax_anim 2, 2, 26, 5, -5, 5, -5,
ax_anim 1, 0, 27, -2, 2, -2, 2,
ax_anim 1, 0, 26, -10, 10, -10, 10,
ax_anim 1, 0, 27, -20, 19, -20, 19,
ax_anim 2, 1, 26, -20, 19, -20, 19,
ax_anim 2, 0, 27, -20, 19, -20, 19,
ax_anim 2, 0, 26, -20, 19, -20, 19,
ax_anim 2, 0, 27, -20, 19, -20, 19,
ax_anim 2, 0, 26, -20, 19, -20, 19,
ax_anim 2, 0, 27, -12, 12, -12, 12,
ax_anim 2, 0, 41, -4, 4, -4, 4,
ax_anim_terminator
.align 2
sStarmieAnims_3_1:
ax_anim 2, 0, 44, 0, 0, 0, 0,
ax_anim 2, 0, 44, 0, -3, 0, -3,
ax_anim 4, 0, 45, 0, -5, 0, -5,
ax_anim 2, 0, 46, 0, -5, 0, -5,
ax_anim 2, 2, 45, 0, -5, 0, -5,
ax_anim 1, 0, 46, 0, 2, 0, 2,
ax_anim 1, 0, 45, 0, 10, 0, 10,
ax_anim 1, 0, 46, 0, 19, 0, 19,
ax_anim 2, 1, 45, 0, 19, 0, 19,
ax_anim 2, 0, 46, 0, 19, 0, 19,
ax_anim 2, 0, 45, 0, 19, 0, 19,
ax_anim 2, 0, 46, 0, 19, 0, 19,
ax_anim 2, 0, 45, 0, 19, 0, 19,
ax_anim 2, 0, 46, 0, 12, 0, 12,
ax_anim 2, 0, 43, 0, 4, 0, 4,
ax_anim_terminator
sStarmieAnims_3_2:
ax_anim 2, 0, 48, 0, 0, 0, 0,
ax_anim 2, 0, 48, -3, -3, -3, -3,
ax_anim 4, 0, 45, -5, -5, -5, -5,
ax_anim 2, 0, 46, -5, -5, -5, -5,
ax_anim 2, 2, 45, -5, -5, -5, -5,
ax_anim 1, 0, 46, 2, 2, 2, 2,
ax_anim 1, 0, 45, 10, 10, 10, 10,
ax_anim 1, 0, 46, 20, 19, 20, 19,
ax_anim 2, 1, 45, 20, 19, 20, 19,
ax_anim 2, 0, 46, 20, 19, 20, 19,
ax_anim 2, 0, 45, 20, 19, 20, 19,
ax_anim 2, 0, 46, 20, 19, 20, 19,
ax_anim 2, 0, 45, 20, 19, 20, 19,
ax_anim 2, 0, 46, 12, 12, 12, 12,
ax_anim 2, 0, 47, 4, 4, 4, 4,
ax_anim_terminator
sStarmieAnims_3_3:
ax_anim 2, 0, 51, 0, 0, 0, 0,
ax_anim 2, 0, 51, -3, 0, -3, 0,
ax_anim 4, 0, 45, -5, 0, -5, 0,
ax_anim 2, 0, 46, -5, 0, -5, 0,
ax_anim 2, 2, 45, -5, 0, -5, 0,
ax_anim 1, 0, 46, 2, 0, 2, 0,
ax_anim 1, 0, 45, 10, 0, 10, 0,
ax_anim 1, 0, 46, 20, 0, 20, 0,
ax_anim 2, 1, 45, 20, 0, 20, 0,
ax_anim 2, 0, 46, 20, 0, 20, 0,
ax_anim 2, 0, 45, 20, 0, 20, 0,
ax_anim 2, 0, 46, 20, 0, 20, 0,
ax_anim 2, 0, 45, 20, 0, 20, 0,
ax_anim 2, 0, 46, 12, 0, 12, 0,
ax_anim 2, 0, 50, 4, 0, 4, 0,
ax_anim_terminator
sStarmieAnims_3_4:
ax_anim 2, 0, 53, 0, 0, 0, 0,
ax_anim 2, 0, 53, -3, 3, -3, 3,
ax_anim 4, 0, 45, -5, 5, -5, 5,
ax_anim 2, 0, 46, -5, 5, -5, 5,
ax_anim 2, 2, 45, -5, 5, -5, 5,
ax_anim 1, 0, 46, 2, -2, 2, -2,
ax_anim 1, 0, 45, 10, -10, 10, -10,
ax_anim 1, 0, 46, 20, -19, 20, -19,
ax_anim 2, 1, 45, 20, -19, 20, -19,
ax_anim 2, 0, 46, 20, -19, 20, -19,
ax_anim 2, 0, 45, 20, -19, 20, -19,
ax_anim 2, 0, 46, 20, -19, 20, -19,
ax_anim 2, 0, 45, 20, -19, 20, -19,
ax_anim 2, 0, 46, 12, -12, 12, -12,
ax_anim 2, 0, 52, 4, -4, 4, -4,
ax_anim_terminator
sStarmieAnims_3_5:
ax_anim 2, 0, 55, 0, 0, 0, 0,
ax_anim 2, 0, 55, 0, 3, 0, 3,
ax_anim 4, 0, 45, 0, 5, 0, 5,
ax_anim 2, 0, 46, 0, 5, 0, 5,
ax_anim 2, 2, 45, 0, 5, 0, 5,
ax_anim 1, 0, 46, 0, -2, 0, -2,
ax_anim 1, 0, 45, 0, -10, 0, -10,
ax_anim 1, 0, 46, 0, -19, 0, -19,
ax_anim 2, 1, 45, 0, -19, 0, -19,
ax_anim 2, 0, 46, 0, -19, 0, -19,
ax_anim 2, 0, 45, 0, -19, 0, -19,
ax_anim 2, 0, 46, 0, -19, 0, -19,
ax_anim 2, 0, 45, 0, -19, 0, -19,
ax_anim 2, 0, 46, 0, -12, 0, -12,
ax_anim 2, 0, 54, 0, -4, 0, -4,
ax_anim_terminator
sStarmieAnims_3_6:
ax_anim 2, 0, 57, 0, 0, 0, 0,
ax_anim 2, 0, 57, 3, 3, 3, 3,
ax_anim 4, 0, 45, 5, 5, 5, 5,
ax_anim 2, 0, 46, 5, 5, 5, 5,
ax_anim 2, 2, 45, 5, 5, 5, 5,
ax_anim 1, 0, 46, -2, -2, -2, -2,
ax_anim 1, 0, 45, -10, -10, -10, -10,
ax_anim 1, 0, 46, -20, -19, -20, -19,
ax_anim 2, 1, 45, -20, -19, -20, -19,
ax_anim 2, 0, 46, -20, -19, -20, -19,
ax_anim 2, 0, 45, -20, -19, -20, -19,
ax_anim 2, 0, 46, -20, -19, -20, -19,
ax_anim 2, 0, 45, -20, -19, -20, -19,
ax_anim 2, 0, 46, -12, -12, -12, -12,
ax_anim 2, 0, 56, -4, -4, -4, -4,
ax_anim_terminator
sStarmieAnims_3_7:
ax_anim 2, 0, 59, 0, 0, 0, 0,
ax_anim 2, 0, 59, 3, 0, 3, 0,
ax_anim 4, 0, 45, 5, 0, 5, 0,
ax_anim 2, 0, 46, 5, 0, 5, 0,
ax_anim 2, 2, 45, 5, 0, 5, 0,
ax_anim 1, 0, 46, -2, 0, -2, 0,
ax_anim 1, 0, 45, -10, 0, -10, 0,
ax_anim 1, 0, 46, -20, 0, -20, 0,
ax_anim 2, 1, 45, -20, 0, -20, 0,
ax_anim 2, 0, 46, -20, 0, -20, 0,
ax_anim 2, 0, 45, -20, 0, -20, 0,
ax_anim 2, 0, 46, -20, 0, -20, 0,
ax_anim 2, 0, 45, -20, 0, -20, 0,
ax_anim 2, 0, 46, -12, 0, -12, 0,
ax_anim 2, 0, 58, -4, 0, -4, 0,
ax_anim_terminator
sStarmieAnims_3_8:
ax_anim 2, 0, 61, 0, 0, 0, 0,
ax_anim 2, 0, 61, 3, -3, 3, -3,
ax_anim 4, 0, 45, 5, -5, 5, -5,
ax_anim 2, 0, 46, 5, -5, 5, -5,
ax_anim 2, 2, 45, 5, -5, 5, -5,
ax_anim 1, 0, 46, -2, 2, -2, 2,
ax_anim 1, 0, 45, -10, 10, -10, 10,
ax_anim 1, 0, 46, -20, 19, -20, 19,
ax_anim 2, 1, 45, -20, 19, -20, 19,
ax_anim 2, 0, 46, -20, 19, -20, 19,
ax_anim 2, 0, 45, -20, 19, -20, 19,
ax_anim 2, 0, 46, -20, 19, -20, 19,
ax_anim 2, 0, 45, -20, 19, -20, 19,
ax_anim 2, 0, 46, -12, 12, -12, 12,
ax_anim 2, 0, 60, -4, 4, -4, 4,
ax_anim_terminator
.align 2
sStarmieAnims_4_1:
ax_anim 2, 0, 63, 0, -2, 0, -2,
ax_anim 2, 0, 64, 0, -3, 0, -3,
ax_anim 6, 2, 62, 0, -3, 0, -3,
ax_anim 1, 0, 65, 0, -1, 0, -1,
ax_anim 2, 0, 65, 0, 3, 0, 3,
ax_anim 2, 1, 66, 0, 3, 0, 3,
ax_anim 2, 0, 65, 0, 3, 0, 3,
ax_anim 2, 0, 66, 0, 3, 0, 3,
ax_anim 2, 0, 65, 0, 3, 0, 3,
ax_anim 2, 0, 66, 0, 3, 0, 3,
ax_anim 2, 0, 65, 0, 3, 0, 3,
ax_anim 2, 0, 62, 0, 1, 0, 1,
ax_anim_terminator
sStarmieAnims_4_2:
ax_anim 2, 0, 68, -2, -2, -2, -2,
ax_anim 2, 0, 69, -3, -3, -3, -3,
ax_anim 6, 2, 67, -3, -3, -3, -3,
ax_anim 1, 0, 70, -1, -1, -1, -1,
ax_anim 2, 0, 70, 3, 3, 3, 3,
ax_anim 2, 1, 71, 3, 3, 3, 3,
ax_anim 2, 0, 70, 3, 3, 3, 3,
ax_anim 2, 0, 71, 3, 3, 3, 3,
ax_anim 2, 0, 70, 3, 3, 3, 3,
ax_anim 2, 0, 71, 3, 3, 3, 3,
ax_anim 2, 0, 70, 3, 3, 3, 3,
ax_anim 2, 0, 67, 1, 1, 1, 1,
ax_anim_terminator
sStarmieAnims_4_3:
ax_anim 2, 0, 73, -2, 0, -2, 0,
ax_anim 2, 0, 74, -4, 0, -4, 0,
ax_anim 6, 2, 72, -5, 0, -5, 0,
ax_anim 1, 0, 75, -1, 0, -1, 0,
ax_anim 2, 0, 75, 3, 0, 3, 0,
ax_anim 2, 1, 76, 3, 0, 3, 0,
ax_anim 2, 0, 75, 3, 0, 3, 0,
ax_anim 2, 0, 76, 3, 0, 3, 0,
ax_anim 2, 0, 75, 3, 0, 3, 0,
ax_anim 2, 0, 76, 3, 0, 3, 0,
ax_anim 2, 0, 75, 3, 0, 3, 0,
ax_anim 2, 0, 72, 1, 0, 1, 0,
ax_anim_terminator
sStarmieAnims_4_4:
ax_anim 2, 0, 78, -2, 2, -2, 2,
ax_anim 2, 0, 79, -3, 3, -3, 3,
ax_anim 6, 2, 77, -3, 3, -3, 3,
ax_anim 1, 0, 80, -1, 1, -1, 1,
ax_anim 2, 0, 80, 3, -3, 3, -3,
ax_anim 2, 1, 81, 3, -3, 3, -3,
ax_anim 2, 0, 80, 3, -3, 3, -3,
ax_anim 2, 0, 81, 3, -3, 3, -3,
ax_anim 2, 0, 80, 3, -3, 3, -3,
ax_anim 2, 0, 81, 3, -3, 3, -3,
ax_anim 2, 0, 80, 3, -3, 3, -3,
ax_anim 2, 0, 77, 1, -1, 1, -1,
ax_anim_terminator
sStarmieAnims_4_5:
ax_anim 2, 0, 83, 0, 2, 0, 2,
ax_anim 2, 0, 84, 0, 3, 0, 3,
ax_anim 6, 2, 82, 0, 3, 0, 3,
ax_anim 1, 0, 85, 0, 1, 0, 1,
ax_anim 2, 0, 85, 0, -3, 0, -3,
ax_anim 2, 1, 86, 0, -3, 0, -3,
ax_anim 2, 0, 85, 0, -3, 0, -3,
ax_anim 2, 0, 86, 0, -3, 0, -3,
ax_anim 2, 0, 85, 0, -3, 0, -3,
ax_anim 2, 0, 86, 0, -3, 0, -3,
ax_anim 2, 0, 85, 0, -3, 0, -3,
ax_anim 2, 0, 82, 0, -1, 0, -1,
ax_anim_terminator
sStarmieAnims_4_6:
ax_anim 2, 0, 88, 2, 2, 2, 2,
ax_anim 2, 0, 89, 3, 3, 3, 3,
ax_anim 6, 2, 87, 3, 3, 3, 3,
ax_anim 1, 0, 90, 1, 1, 1, 1,
ax_anim 2, 0, 90, -3, -3, -3, -3,
ax_anim 2, 1, 91, -3, -3, -3, -3,
ax_anim 2, 0, 90, -3, -3, -3, -3,
ax_anim 2, 0, 91, -3, -3, -3, -3,
ax_anim 2, 0, 90, -3, -3, -3, -3,
ax_anim 2, 0, 91, -3, -3, -3, -3,
ax_anim 2, 0, 90, -3, -3, -3, -3,
ax_anim 2, 0, 87, -1, -1, -1, -1,
ax_anim_terminator
sStarmieAnims_4_7:
ax_anim 2, 0, 93, 2, 0, 2, 0,
ax_anim 2, 0, 94, 4, 0, 4, 0,
ax_anim 6, 2, 92, 5, 0, 5, 0,
ax_anim 1, 0, 95, 1, 0, 1, 0,
ax_anim 2, 0, 95, -3, 0, -3, 0,
ax_anim 2, 1, 96, -3, 0, -3, 0,
ax_anim 2, 0, 95, -3, 0, -3, 0,
ax_anim 2, 0, 96, -3, 0, -3, 0,
ax_anim 2, 0, 95, -3, 0, -3, 0,
ax_anim 2, 0, 96, -3, 0, -3, 0,
ax_anim 2, 0, 95, -3, 0, -3, 0,
ax_anim 2, 0, 92, -1, 0, -1, 0,
ax_anim_terminator
sStarmieAnims_4_8:
ax_anim 2, 0, 98, 2, -2, 2, -2,
ax_anim 2, 0, 99, 3, -3, 3, -3,
ax_anim 6, 2, 97, 3, -3, 3, -3,
ax_anim 1, 0, 100, 1, -1, 1, -1,
ax_anim 2, 0, 100, -3, 3, -3, 3,
ax_anim 2, 1, 101, -3, 3, -3, 3,
ax_anim 2, 0, 100, -3, 3, -3, 3,
ax_anim 2, 0, 101, -3, 3, -3, 3,
ax_anim 2, 0, 100, -3, 3, -3, 3,
ax_anim 2, 0, 101, -3, 3, -3, 3,
ax_anim 2, 0, 100, -3, 3, -3, 3,
ax_anim 2, 0, 97, -1, 1, -1, 1,
ax_anim_terminator
.align 2
sStarmieAnims_5_1:
ax_anim 2, 0, 102, 0, 0, 0, 0,
ax_anim 2, 0, 103, 0, 0, 0, 0,
ax_anim 2, 0, 104, 0, 0, 0, 0,
ax_anim 2, 0, 105, 0, 0, 0, 0,
ax_anim 2, 0, 106, 0, 0, 0, 0,
ax_anim 2, 0, 107, 0, 0, 0, 0,
ax_anim 2, 0, 108, 0, 0, 0, 0,
ax_anim 2, 0, 109, 0, 0, 0, 0,
ax_anim 2, 2, 102, 0, 0, 0, 0,
ax_anim_terminator
sStarmieAnims_5_2:
ax_anim 2, 0, 109, 0, 0, 0, 0,
ax_anim 2, 0, 102, 0, 0, 0, 0,
ax_anim 2, 0, 103, 0, 0, 0, 0,
ax_anim 2, 0, 104, 0, 0, 0, 0,
ax_anim 2, 0, 105, 0, 0, 0, 0,
ax_anim 2, 0, 106, 0, 0, 0, 0,
ax_anim 2, 0, 107, 0, 0, 0, 0,
ax_anim 2, 0, 108, 0, 0, 0, 0,
ax_anim 2, 2, 109, 0, 0, 0, 0,
ax_anim_terminator
sStarmieAnims_5_3:
ax_anim 2, 0, 108, 0, 0, 0, 0,
ax_anim 2, 0, 109, 0, 0, 0, 0,
ax_anim 2, 0, 102, 0, 0, 0, 0,
ax_anim 2, 0, 103, 0, 0, 0, 0,
ax_anim 2, 0, 104, 0, 0, 0, 0,
ax_anim 2, 0, 105, 0, 0, 0, 0,
ax_anim 2, 0, 106, 0, 0, 0, 0,
ax_anim 2, 0, 107, 0, 0, 0, 0,
ax_anim 2, 2, 108, 0, 0, 0, 0,
ax_anim_terminator
sStarmieAnims_5_4:
ax_anim 2, 0, 107, 0, 0, 0, 0,
ax_anim 2, 0, 108, 0, 0, 0, 0,
ax_anim 2, 0, 109, 0, 0, 0, 0,
ax_anim 2, 0, 102, 0, 0, 0, 0,
ax_anim 2, 0, 103, 0, 0, 0, 0,
ax_anim 2, 0, 104, 0, 0, 0, 0,
ax_anim 2, 0, 105, 0, 0, 0, 0,
ax_anim 2, 0, 106, 0, 0, 0, 0,
ax_anim 2, 2, 107, 0, 0, 0, 0,
ax_anim_terminator
sStarmieAnims_5_5:
ax_anim 2, 0, 106, 0, 0, 0, 0,
ax_anim 2, 0, 107, 0, 0, 0, 0,
ax_anim 2, 0, 108, 0, 0, 0, 0,
ax_anim 2, 0, 109, 0, 0, 0, 0,
ax_anim 2, 0, 102, 0, 0, 0, 0,
ax_anim 2, 0, 103, 0, 0, 0, 0,
ax_anim 2, 0, 104, 0, 0, 0, 0,
ax_anim 2, 0, 105, 0, 0, 0, 0,
ax_anim 2, 2, 106, 0, 0, 0, 0,
ax_anim_terminator
sStarmieAnims_5_6:
ax_anim 2, 0, 105, 0, 0, 0, 0,
ax_anim 2, 0, 106, 0, 0, 0, 0,
ax_anim 2, 0, 107, 0, 0, 0, 0,
ax_anim 2, 0, 108, 0, 0, 0, 0,
ax_anim 2, 0, 109, 0, 0, 0, 0,
ax_anim 2, 0, 102, 0, 0, 0, 0,
ax_anim 2, 0, 103, 0, 0, 0, 0,
ax_anim 2, 0, 104, 0, 0, 0, 0,
ax_anim 2, 2, 105, 0, 0, 0, 0,
ax_anim_terminator
sStarmieAnims_5_7:
ax_anim 2, 0, 104, 0, 0, 0, 0,
ax_anim 2, 0, 105, 0, 0, 0, 0,
ax_anim 2, 0, 106, 0, 0, 0, 0,
ax_anim 2, 0, 107, 0, 0, 0, 0,
ax_anim 2, 0, 108, 0, 0, 0, 0,
ax_anim 2, 0, 109, 0, 0, 0, 0,
ax_anim 2, 0, 102, 0, 0, 0, 0,
ax_anim 2, 0, 103, 0, 0, 0, 0,
ax_anim 2, 2, 104, 0, 0, 0, 0,
ax_anim_terminator
sStarmieAnims_5_8:
ax_anim 2, 0, 103, 0, 0, 0, 0,
ax_anim 2, 0, 104, 0, 0, 0, 0,
ax_anim 2, 0, 105, 0, 0, 0, 0,
ax_anim 2, 0, 106, 0, 0, 0, 0,
ax_anim 2, 0, 107, 0, 0, 0, 0,
ax_anim 2, 0, 108, 0, 0, 0, 0,
ax_anim 2, 0, 109, 0, 0, 0, 0,
ax_anim 2, 0, 102, 0, 0, 0, 0,
ax_anim 2, 2, 103, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sStarmieAnims_6_1:
ax_anim 30, 0, 110, 0, 0, 0, 0,
ax_anim 35, 0, 111, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sStarmieAnims_7_1:
ax_anim 2, 0, 112, 0, -4, 0, -4,
ax_anim 8, 0, 112, 0, -5, 0, -5,
ax_anim_terminator
sStarmieAnims_7_2:
ax_anim 2, 0, 113, -4, -4, -4, -4,
ax_anim 8, 0, 113, -5, -5, -5, -5,
ax_anim_terminator
sStarmieAnims_7_3:
ax_anim 2, 0, 114, -4, 0, -4, 0,
ax_anim 8, 0, 114, -5, 0, -5, 0,
ax_anim_terminator
sStarmieAnims_7_4:
ax_anim 2, 0, 115, -4, 4, -4, 4,
ax_anim 8, 0, 115, -5, 5, -5, 5,
ax_anim_terminator
sStarmieAnims_7_5:
ax_anim 2, 0, 116, 0, 4, 0, 4,
ax_anim 8, 0, 116, 0, 5, 0, 5,
ax_anim_terminator
sStarmieAnims_7_6:
ax_anim 2, 0, 117, 4, 4, 4, 4,
ax_anim 8, 0, 117, 5, 5, 5, 5,
ax_anim_terminator
sStarmieAnims_7_7:
ax_anim 2, 0, 118, 4, 0, 4, 0,
ax_anim 8, 0, 118, 5, 0, 5, 0,
ax_anim_terminator
sStarmieAnims_7_8:
ax_anim 2, 0, 119, 4, -4, 4, -4,
ax_anim 8, 0, 119, 5, -5, 5, -5,
ax_anim_terminator
.align 2
sStarmieAnims_8_1:
ax_anim 60, 0, 120, 0, 0, 0, 0,
ax_anim 4, 0, 121, 0, 0, 0, 0,
ax_anim 4, 0, 122, 0, 0, 0, 0,
ax_anim 4, 0, 123, 0, 0, 0, 0,
ax_anim 4, 0, 124, 0, 0, 0, 0,
ax_anim 4, 0, 125, 0, 0, 0, 0,
ax_anim 4, 0, 126, 0, 0, 0, 0,
ax_anim 4, 0, 127, 0, 0, 0, 0,
ax_anim_terminator
sStarmieAnims_8_2:
ax_anim 60, 0, 127, 0, 0, 0, 0,
ax_anim 4, 0, 120, 0, 0, 0, 0,
ax_anim 4, 0, 121, 0, 0, 0, 0,
ax_anim 4, 0, 122, 0, 0, 0, 0,
ax_anim 4, 0, 123, 0, 0, 0, 0,
ax_anim 4, 0, 124, 0, 0, 0, 0,
ax_anim 4, 0, 125, 0, 0, 0, 0,
ax_anim 4, 0, 126, 0, 0, 0, 0,
ax_anim_terminator
sStarmieAnims_8_3:
ax_anim 60, 0, 126, 0, 0, 0, 0,
ax_anim 4, 0, 127, 0, 0, 0, 0,
ax_anim 4, 0, 120, 0, 0, 0, 0,
ax_anim 4, 0, 121, 0, 0, 0, 0,
ax_anim 4, 0, 122, 0, 0, 0, 0,
ax_anim 4, 0, 123, 0, 0, 0, 0,
ax_anim 4, 0, 124, 0, 0, 0, 0,
ax_anim 4, 0, 125, 0, 0, 0, 0,
ax_anim_terminator
sStarmieAnims_8_4:
ax_anim 60, 0, 125, 0, 0, 0, 0,
ax_anim 4, 0, 126, 0, 0, 0, 0,
ax_anim 4, 0, 127, 0, 0, 0, 0,
ax_anim 4, 0, 120, 0, 0, 0, 0,
ax_anim 4, 0, 121, 0, 0, 0, 0,
ax_anim 4, 0, 122, 0, 0, 0, 0,
ax_anim 4, 0, 123, 0, 0, 0, 0,
ax_anim 4, 0, 124, 0, 0, 0, 0,
ax_anim_terminator
sStarmieAnims_8_5:
ax_anim 60, 0, 124, 0, 0, 0, 0,
ax_anim 4, 0, 125, 0, 0, 0, 0,
ax_anim 4, 0, 126, 0, 0, 0, 0,
ax_anim 4, 0, 127, 0, 0, 0, 0,
ax_anim 4, 0, 120, 0, 0, 0, 0,
ax_anim 4, 0, 121, 0, 0, 0, 0,
ax_anim 4, 0, 122, 0, 0, 0, 0,
ax_anim 4, 0, 123, 0, 0, 0, 0,
ax_anim_terminator
sStarmieAnims_8_6:
ax_anim 60, 0, 123, 0, 0, 0, 0,
ax_anim 4, 0, 124, 0, 0, 0, 0,
ax_anim 4, 0, 125, 0, 0, 0, 0,
ax_anim 4, 0, 126, 0, 0, 0, 0,
ax_anim 4, 0, 127, 0, 0, 0, 0,
ax_anim 4, 0, 120, 0, 0, 0, 0,
ax_anim 4, 0, 121, 0, 0, 0, 0,
ax_anim 4, 0, 122, 0, 0, 0, 0,
ax_anim_terminator
sStarmieAnims_8_7:
ax_anim 60, 0, 122, 0, 0, 0, 0,
ax_anim 4, 0, 123, 0, 0, 0, 0,
ax_anim 4, 0, 124, 0, 0, 0, 0,
ax_anim 4, 0, 125, 0, 0, 0, 0,
ax_anim 4, 0, 126, 0, 0, 0, 0,
ax_anim 4, 0, 127, 0, 0, 0, 0,
ax_anim 4, 0, 120, 0, 0, 0, 0,
ax_anim 4, 0, 121, 0, 0, 0, 0,
ax_anim_terminator
sStarmieAnims_8_8:
ax_anim 60, 0, 121, 0, 0, 0, 0,
ax_anim 4, 0, 122, 0, 0, 0, 0,
ax_anim 4, 0, 123, 0, 0, 0, 0,
ax_anim 4, 0, 124, 0, 0, 0, 0,
ax_anim 4, 0, 125, 0, 0, 0, 0,
ax_anim 4, 0, 126, 0, 0, 0, 0,
ax_anim 4, 0, 127, 0, 0, 0, 0,
ax_anim 4, 0, 120, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sStarmieAnims_9_1:
ax_anim 2, 0, 128, 0, 0, 0, 0,
ax_anim 1, 0, 129, 6, 3, 6, 3,
ax_anim 2, 0, 130, 8, 9, 8, 9,
ax_anim 2, 0, 131, 7, 17, 7, 17,
ax_anim 3, 0, 132, 0, 20, 0, 20,
ax_anim 2, 3, 133, -7, 17, -7, 17,
ax_anim 2, 0, 134, -8, 9, -8, 9,
ax_anim 1, 0, 135, -6, 3, -6, 3,
ax_anim 1, 0, 128, 0, 0, 0, 0,
ax_anim_terminator
sStarmieAnims_9_2:
ax_anim 2, 0, 135, 0, 0, 0, 0,
ax_anim 1, 0, 128, 8, 0, 8, 0,
ax_anim 2, 0, 129, 17, 3, 17, 3,
ax_anim 2, 0, 130, 20, 11, 20, 11,
ax_anim 3, 0, 131, 21, 19, 21, 19,
ax_anim 2, 3, 132, 11, 21, 11, 21,
ax_anim 2, 0, 133, 3, 15, 3, 15,
ax_anim 1, 0, 134, 0, 7, 0, 7,
ax_anim 1, 0, 135, 0, 0, 0, 0,
ax_anim_terminator
sStarmieAnims_9_3:
ax_anim 2, 0, 134, 0, 0, 0, 0,
ax_anim 1, 0, 135, 3, -5, 3, -5,
ax_anim 2, 0, 128, 11, -6, 11, -6,
ax_anim 2, 0, 129, 19, -5, 19, -5,
ax_anim 3, 0, 130, 22, -2, 22, -2,
ax_anim 2, 3, 131, 20, 4, 20, 4,
ax_anim 2, 0, 132, 12, 7, 12, 7,
ax_anim 1, 0, 133, 4, 5, 4, 5,
ax_anim 1, 0, 134, 0, 0, 0, 0,
ax_anim_terminator
sStarmieAnims_9_4:
ax_anim 2, 0, 133, 0, 0, 0, 0,
ax_anim 1, 0, 134, -1, -8, -1, -8,
ax_anim 2, 0, 135, 4, -16, 4, -16,
ax_anim 2, 0, 128, 12, -21, 12, -21,
ax_anim 3, 0, 129, 20, -20, 20, -20,
ax_anim 2, 3, 130, 20, -13, 20, -13,
ax_anim 2, 0, 131, 17, -4, 17, -4,
ax_anim 1, 0, 132, 7, -1, 7, -1,
ax_anim 1, 0, 133, 0, 0, 0, 0,
ax_anim_terminator
sStarmieAnims_9_5:
ax_anim 2, 0, 132, 0, 0, 0, 0,
ax_anim 1, 0, 133, -8, -4, -8, -4,
ax_anim 2, 0, 134, -9, -12, -9, -12,
ax_anim 2, 0, 135, -7, -18, -7, -18,
ax_anim 3, 0, 128, 0, -21, 0, -21,
ax_anim 2, 3, 129, 7, -18, 7, -18,
ax_anim 2, 0, 130, 9, -10, 9, -10,
ax_anim 1, 0, 131, 8, -4, 8, -4,
ax_anim 1, 0, 132, 0, 0, 0, 0,
ax_anim_terminator
sStarmieAnims_9_6:
ax_anim 2, 0, 131, 0, 0, 0, 0,
ax_anim 1, 0, 130, 1, -8, 1, -8,
ax_anim 2, 0, 129, -4, -16, -4, -16,
ax_anim 2, 0, 128, -12, -21, -12, -21,
ax_anim 3, 0, 135, -20, -20, -20, -20,
ax_anim 2, 3, 134, -20, -13, -20, -13,
ax_anim 2, 0, 133, -17, -4, -17, -4,
ax_anim 1, 0, 132, -7, -1, -7, -1,
ax_anim 1, 0, 131, 0, 0, 0, 0,
ax_anim_terminator
sStarmieAnims_9_7:
ax_anim 2, 0, 130, 0, 0, 0, 0,
ax_anim 1, 0, 129, -3, -5, -3, -5,
ax_anim 2, 0, 128, -11, -6, -11, -6,
ax_anim 2, 0, 135, -19, -5, -19, -5,
ax_anim 3, 0, 134, -22, -2, -22, -2,
ax_anim 2, 3, 133, -20, 4, -20, 4,
ax_anim 2, 0, 132, -12, 7, -12, 7,
ax_anim 1, 0, 131, -4, 5, -4, 5,
ax_anim 1, 0, 130, 0, 0, 0, 0,
ax_anim_terminator
sStarmieAnims_9_8:
ax_anim 2, 0, 129, 0, 0, 0, 0,
ax_anim 1, 0, 128, -8, 0, -8, 0,
ax_anim 2, 0, 135, -17, 3, -17, 3,
ax_anim 2, 0, 134, -20, 11, -20, 11,
ax_anim 3, 0, 133, -21, 19, -21, 19,
ax_anim 2, 3, 132, -11, 21, -11, 21,
ax_anim 2, 0, 131, -3, 15, -3, 15,
ax_anim 1, 0, 130, 0, 7, 0, 7,
ax_anim 1, 0, 129, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sStarmieAnims_10_1:
ax_anim 2, 0, 136, 0, 0, 0, 0,
ax_anim 2, 0, 136, 6, 0, 6, 0,
ax_anim 2, 0, 136, -6, 0, -6, 0,
ax_anim 2, 0, 136, 10, 0, 10, 0,
ax_anim 2, 0, 136, -10, 0, -10, 0,
ax_anim 2, 0, 136, 12, 0, 12, 0,
ax_anim 3, 0, 136, -12, 0, -12, 0,
ax_anim 3, 0, 136, 13, 0, 13, 0,
ax_anim 3, 0, 136, -13, 0, -13, 0,
ax_anim 2, 0, 136, 12, 0, 12, 0,
ax_anim 3, 0, 136, -12, 0, -12, 0,
ax_anim 2, 0, 136, 10, 0, 10, 0,
ax_anim 2, 0, 136, -10, 0, -10, 0,
ax_anim 2, 0, 136, 6, 0, 6, 0,
ax_anim 2, 0, 136, -6, 0, -6, 0,
ax_anim 2, 0, 136, 0, 0, 0, 0,
ax_anim_terminator
sStarmieAnims_10_2:
ax_anim 2, 0, 137, 0, 0, 0, 0,
ax_anim 2, 0, 137, 6, -6, 6, -6,
ax_anim 2, 0, 137, -6, 6, -6, 6,
ax_anim 2, 0, 137, 10, -10, 10, -10,
ax_anim 2, 0, 137, -10, 10, -10, 10,
ax_anim 2, 0, 137, 12, -12, 12, -12,
ax_anim 3, 0, 137, -12, 12, -12, 12,
ax_anim 3, 0, 137, 13, -13, 13, -13,
ax_anim 3, 0, 137, -13, 13, -13, 13,
ax_anim 2, 0, 137, 12, -12, 12, -12,
ax_anim 3, 0, 137, -12, 12, -12, 12,
ax_anim 2, 0, 137, 10, -10, 10, -10,
ax_anim 2, 0, 137, -10, 10, -10, 10,
ax_anim 2, 0, 137, 6, -6, 6, -6,
ax_anim 2, 0, 137, -6, 6, -6, 6,
ax_anim 2, 0, 137, 0, 0, 0, 0,
ax_anim_terminator
sStarmieAnims_10_3:
ax_anim 2, 0, 138, 0, 0, 0, 0,
ax_anim 2, 0, 138, 0, -6, 0, -6,
ax_anim 2, 0, 138, 0, 6, 0, 6,
ax_anim 2, 0, 138, 0, -10, 0, -10,
ax_anim 2, 0, 138, 0, 10, 0, 10,
ax_anim 2, 0, 138, 0, -12, 0, -12,
ax_anim 3, 0, 138, 0, 12, 0, 12,
ax_anim 3, 0, 138, 0, -13, 0, -13,
ax_anim 3, 0, 138, 0, 13, 0, 13,
ax_anim 2, 0, 138, 0, -12, 0, -12,
ax_anim 3, 0, 138, 0, 12, 0, 12,
ax_anim 2, 0, 138, 0, -10, 0, -10,
ax_anim 2, 0, 138, 0, 10, 0, 10,
ax_anim 2, 0, 138, 0, -6, 0, -6,
ax_anim 2, 0, 138, 0, 6, 0, 6,
ax_anim 2, 0, 138, 0, 0, 0, 0,
ax_anim_terminator
sStarmieAnims_10_4:
ax_anim 2, 0, 139, 0, 0, 0, 0,
ax_anim 2, 0, 139, -6, -6, -6, -6,
ax_anim 2, 0, 139, 6, 6, 6, 6,
ax_anim 2, 0, 139, -10, -10, -10, -10,
ax_anim 2, 0, 139, 10, 10, 10, 10,
ax_anim 2, 0, 139, -12, -12, -12, -12,
ax_anim 3, 0, 139, 12, 12, 12, 12,
ax_anim 3, 0, 139, -13, -13, -13, -13,
ax_anim 3, 0, 139, 13, 13, 13, 13,
ax_anim 2, 0, 139, -12, -12, -12, -12,
ax_anim 3, 0, 139, 12, 12, 12, 12,
ax_anim 2, 0, 139, -10, -10, -10, -10,
ax_anim 2, 0, 139, 10, 10, 10, 10,
ax_anim 2, 0, 139, -6, -6, -6, -6,
ax_anim 2, 0, 139, 6, 6, 6, 6,
ax_anim 2, 0, 139, 0, 0, 0, 0,
ax_anim_terminator
sStarmieAnims_10_5:
ax_anim 2, 0, 140, 0, 0, 0, 0,
ax_anim 2, 0, 140, 6, 0, 6, 0,
ax_anim 2, 0, 140, -6, 0, -6, 0,
ax_anim 2, 0, 140, 10, 0, 10, 0,
ax_anim 2, 0, 140, -10, 0, -10, 0,
ax_anim 2, 0, 140, 12, 0, 12, 0,
ax_anim 3, 0, 140, -12, 0, -12, 0,
ax_anim 3, 0, 140, 13, 0, 13, 0,
ax_anim 3, 0, 140, -13, 0, -13, 0,
ax_anim 2, 0, 140, 12, 0, 12, 0,
ax_anim 3, 0, 140, -12, 0, -12, 0,
ax_anim 2, 0, 140, 10, 0, 10, 0,
ax_anim 2, 0, 140, -10, 0, -10, 0,
ax_anim 2, 0, 140, 6, 0, 6, 0,
ax_anim 2, 0, 140, -6, 0, -6, 0,
ax_anim 2, 0, 140, 0, 0, 0, 0,
ax_anim_terminator
sStarmieAnims_10_6:
ax_anim 2, 0, 141, 0, 0, 0, 0,
ax_anim 2, 0, 141, 6, -6, 6, -6,
ax_anim 2, 0, 141, -6, 6, -6, 6,
ax_anim 2, 0, 141, 10, -10, 10, -10,
ax_anim 2, 0, 141, -10, 10, -10, 10,
ax_anim 2, 0, 141, 12, -12, 12, -12,
ax_anim 3, 0, 141, -12, 12, -12, 12,
ax_anim 3, 0, 141, 13, -13, 13, -13,
ax_anim 3, 0, 141, -13, 13, -13, 13,
ax_anim 2, 0, 141, 12, -12, 12, -12,
ax_anim 3, 0, 141, -12, 12, -12, 12,
ax_anim 2, 0, 141, 10, -10, 10, -10,
ax_anim 2, 0, 141, -10, 10, -10, 10,
ax_anim 2, 0, 141, 6, -6, 6, -6,
ax_anim 2, 0, 141, -6, 6, -6, 6,
ax_anim 2, 0, 141, 0, 0, 0, 0,
ax_anim_terminator
sStarmieAnims_10_7:
ax_anim 2, 0, 142, 0, 0, 0, 0,
ax_anim 2, 0, 142, 0, -6, 0, -6,
ax_anim 2, 0, 142, 0, 6, 0, 6,
ax_anim 2, 0, 142, 0, -10, 0, -10,
ax_anim 2, 0, 142, 0, 10, 0, 10,
ax_anim 2, 0, 142, 0, -12, 0, -12,
ax_anim 3, 0, 142, 0, 12, 0, 12,
ax_anim 3, 0, 142, 0, -13, 0, -13,
ax_anim 3, 0, 142, 0, 13, 0, 13,
ax_anim 2, 0, 142, 0, -12, 0, -12,
ax_anim 3, 0, 142, 0, 12, 0, 12,
ax_anim 2, 0, 142, 0, -10, 0, -10,
ax_anim 2, 0, 142, 0, 10, 0, 10,
ax_anim 2, 0, 142, 0, -6, 0, -6,
ax_anim 2, 0, 142, 0, 6, 0, 6,
ax_anim 2, 0, 142, 0, 0, 0, 0,
ax_anim_terminator
sStarmieAnims_10_8:
ax_anim 2, 0, 143, 0, 0, 0, 0,
ax_anim 2, 0, 143, -6, -6, -6, -6,
ax_anim 2, 0, 143, 6, 6, 6, 6,
ax_anim 2, 0, 143, -10, -10, -10, -10,
ax_anim 2, 0, 143, 10, 10, 10, 10,
ax_anim 2, 0, 143, -12, -12, -12, -12,
ax_anim 3, 0, 143, 12, 12, 12, 12,
ax_anim 3, 0, 143, -13, -13, -13, -13,
ax_anim 3, 0, 143, 13, 13, 13, 13,
ax_anim 2, 0, 143, -12, -12, -12, -12,
ax_anim 3, 0, 143, 12, 12, 12, 12,
ax_anim 2, 0, 143, -10, -10, -10, -10,
ax_anim 2, 0, 143, 10, 10, 10, 10,
ax_anim 2, 0, 143, -6, -6, -6, -6,
ax_anim 2, 0, 143, 6, 6, 6, 6,
ax_anim 2, 0, 143, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sStarmieAnims_11_1:
ax_anim 2, 0, 145, 0, 0, 0, 0,
ax_anim 1, 0, 145, 0, -10, 0, 0,
ax_anim 2, 0, 145, 0, -16, 0, 0,
ax_anim 3, 0, 145, 0, -20, 0, 0,
ax_anim 4, 0, 145, 0, -21, 0, 0,
ax_anim 4, 0, 144, 0, -23, 0, 0,
ax_anim 3, 0, 144, 0, -22, 0, 0,
ax_anim 2, 0, 144, 0, -18, 0, 0,
ax_anim 1, 0, 144, 0, -12, 0, 0,
ax_anim 2, 2, 144, 0, 2, 0, 0,
ax_anim_terminator
sStarmieAnims_11_2:
ax_anim 2, 0, 147, 0, 0, 0, 0,
ax_anim 1, 0, 147, 0, -10, 0, 0,
ax_anim 2, 0, 147, 0, -16, 0, 0,
ax_anim 3, 0, 147, 0, -20, 0, 0,
ax_anim 4, 0, 147, 0, -21, 0, 0,
ax_anim 4, 0, 146, 0, -23, 0, 0,
ax_anim 3, 0, 146, 0, -22, 0, 0,
ax_anim 2, 0, 146, 0, -18, 0, 0,
ax_anim 1, 0, 146, 0, -12, 0, 0,
ax_anim 2, 2, 146, 0, 2, 0, 0,
ax_anim_terminator
sStarmieAnims_11_3:
ax_anim 2, 0, 149, 0, 0, 0, 0,
ax_anim 1, 0, 149, 0, -10, 0, 0,
ax_anim 2, 0, 149, 0, -16, 0, 0,
ax_anim 3, 0, 149, 0, -20, 0, 0,
ax_anim 4, 0, 149, 0, -21, 0, 0,
ax_anim 4, 0, 148, 0, -23, 0, 0,
ax_anim 3, 0, 148, 0, -22, 0, 0,
ax_anim 2, 0, 148, 0, -18, 0, 0,
ax_anim 1, 0, 148, 0, -12, 0, 0,
ax_anim 2, 2, 148, 0, 2, 0, 0,
ax_anim_terminator
sStarmieAnims_11_4:
ax_anim 2, 0, 151, 0, 0, 0, 0,
ax_anim 1, 0, 151, 0, -10, 0, 0,
ax_anim 2, 0, 151, 0, -16, 0, 0,
ax_anim 3, 0, 151, 0, -20, 0, 0,
ax_anim 4, 0, 151, 0, -21, 0, 0,
ax_anim 4, 0, 150, 0, -22, 0, 0,
ax_anim 3, 0, 150, 0, -21, 0, 0,
ax_anim 2, 0, 150, 0, -17, 0, 0,
ax_anim 1, 0, 150, 0, -11, 0, 0,
ax_anim 2, 2, 150, 0, 2, 0, 0,
ax_anim_terminator
sStarmieAnims_11_5:
ax_anim 2, 0, 153, 0, 0, 0, 0,
ax_anim 1, 0, 153, 0, -10, 0, 0,
ax_anim 2, 0, 153, 0, -16, 0, 0,
ax_anim 3, 0, 153, 0, -20, 0, 0,
ax_anim 4, 0, 153, 0, -21, 0, 0,
ax_anim 4, 0, 152, 0, -23, 0, 0,
ax_anim 3, 0, 152, 0, -22, 0, 0,
ax_anim 2, 0, 152, 0, -18, 0, 0,
ax_anim 1, 0, 152, 0, -12, 0, 0,
ax_anim 2, 2, 152, 0, 2, 0, 0,
ax_anim_terminator
sStarmieAnims_11_6:
ax_anim 2, 0, 155, 0, 0, 0, 0,
ax_anim 1, 0, 155, 0, -10, 0, 0,
ax_anim 2, 0, 155, 0, -16, 0, 0,
ax_anim 3, 0, 155, 0, -20, 0, 0,
ax_anim 4, 0, 155, 0, -21, 0, 0,
ax_anim 4, 0, 154, 0, -22, 0, 0,
ax_anim 3, 0, 154, 0, -21, 0, 0,
ax_anim 2, 0, 154, 0, -17, 0, 0,
ax_anim 1, 0, 154, 0, -11, 0, 0,
ax_anim 2, 2, 154, 0, 2, 0, 0,
ax_anim_terminator
sStarmieAnims_11_7:
ax_anim 2, 0, 157, 0, 0, 0, 0,
ax_anim 1, 0, 157, 0, -10, 0, 0,
ax_anim 2, 0, 157, 0, -16, 0, 0,
ax_anim 3, 0, 157, 0, -20, 0, 0,
ax_anim 4, 0, 157, 0, -21, 0, 0,
ax_anim 4, 0, 156, 0, -23, 0, 0,
ax_anim 3, 0, 156, 0, -22, 0, 0,
ax_anim 2, 0, 156, 0, -18, 0, 0,
ax_anim 1, 0, 156, 0, -12, 0, 0,
ax_anim 2, 2, 156, 0, 2, 0, 0,
ax_anim_terminator
sStarmieAnims_11_8:
ax_anim 2, 0, 159, 0, 0, 0, 0,
ax_anim 1, 0, 159, 0, -10, 0, 0,
ax_anim 2, 0, 159, 0, -16, 0, 0,
ax_anim 3, 0, 159, 0, -20, 0, 0,
ax_anim 4, 0, 159, 0, -21, 0, 0,
ax_anim 4, 0, 158, 0, -23, 0, 0,
ax_anim 3, 0, 158, 0, -22, 0, 0,
ax_anim 2, 0, 158, 0, -18, 0, 0,
ax_anim 1, 0, 158, 0, -12, 0, 0,
ax_anim 2, 2, 158, 0, 2, 0, 0,
ax_anim_terminator
.align 2
sStarmieAnims_12_1:
ax_anim 2, 0, 160, 1, 0, 1, 0,
ax_anim 2, 0, 160, 0, 0, 0, 0,
ax_anim 2, 0, 160, 1, 0, 1, 0,
ax_anim 2, 0, 160, 0, 0, 0, 0,
ax_anim 2, 0, 160, 1, 0, 1, 0,
ax_anim 2, 2, 160, 0, 0, 0, 0,
ax_anim 2, 0, 160, 1, 0, 1, 0,
ax_anim 2, 0, 160, 0, 0, 0, 0,
ax_anim 2, 0, 160, 1, 0, 1, 0,
ax_anim 2, 1, 160, 0, 0, 0, 0,
ax_anim_terminator
sStarmieAnims_12_2:
ax_anim 2, 0, 167, 1, -1, 1, -1,
ax_anim 2, 0, 167, 0, 0, 0, 0,
ax_anim 2, 0, 167, 1, -1, 1, -1,
ax_anim 2, 0, 167, 0, 0, 0, 0,
ax_anim 2, 0, 167, 1, -1, 1, -1,
ax_anim 2, 2, 167, 0, 0, 0, 0,
ax_anim 2, 0, 167, 1, -1, 1, -1,
ax_anim 2, 0, 167, 0, 0, 0, 0,
ax_anim 2, 0, 167, 1, -1, 1, -1,
ax_anim 2, 1, 167, 0, 0, 0, 0,
ax_anim_terminator
sStarmieAnims_12_3:
ax_anim 2, 0, 166, 0, -1, 0, -1,
ax_anim 2, 0, 166, 0, 0, 0, 0,
ax_anim 2, 0, 166, 0, -1, 0, -1,
ax_anim 2, 0, 166, 0, 0, 0, 0,
ax_anim 2, 0, 166, 0, -1, 0, -1,
ax_anim 2, 2, 166, 0, 0, 0, 0,
ax_anim 2, 0, 166, 0, -1, 0, -1,
ax_anim 2, 0, 166, 0, 0, 0, 0,
ax_anim 2, 0, 166, 0, -1, 0, -1,
ax_anim 2, 1, 166, 0, 0, 0, 0,
ax_anim_terminator
sStarmieAnims_12_4:
ax_anim 2, 0, 165, -1, -1, -1, -1,
ax_anim 2, 0, 165, 0, 0, 0, 0,
ax_anim 2, 0, 165, -1, -1, -1, -1,
ax_anim 2, 0, 165, 0, 0, 0, 0,
ax_anim 2, 0, 165, -1, -1, -1, -1,
ax_anim 2, 2, 165, 0, 0, 0, 0,
ax_anim 2, 0, 165, -1, -1, -1, -1,
ax_anim 2, 0, 165, 0, 0, 0, 0,
ax_anim 2, 0, 165, -1, -1, -1, -1,
ax_anim 2, 1, 165, 0, 0, 0, 0,
ax_anim_terminator
sStarmieAnims_12_5:
ax_anim 2, 0, 164, 1, 0, 1, 0,
ax_anim 2, 0, 164, 0, 0, 0, 0,
ax_anim 2, 0, 164, 1, 0, 1, 0,
ax_anim 2, 0, 164, 0, 0, 0, 0,
ax_anim 2, 0, 164, 1, 0, 1, 0,
ax_anim 2, 2, 164, 0, 0, 0, 0,
ax_anim 2, 0, 164, 1, 0, 1, 0,
ax_anim 2, 0, 164, 0, 0, 0, 0,
ax_anim 2, 0, 164, 1, 0, 1, 0,
ax_anim 2, 1, 164, 0, 0, 0, 0,
ax_anim_terminator
sStarmieAnims_12_6:
ax_anim 2, 0, 163, 1, -1, 1, -1,
ax_anim 2, 0, 163, 0, 0, 0, 0,
ax_anim 2, 0, 163, 1, -1, 1, -1,
ax_anim 2, 0, 163, 0, 0, 0, 0,
ax_anim 2, 0, 163, 1, -1, 1, -1,
ax_anim 2, 2, 163, 0, 0, 0, 0,
ax_anim 2, 0, 163, 1, -1, 1, -1,
ax_anim 2, 0, 163, 0, 0, 0, 0,
ax_anim 2, 0, 163, 1, -1, 1, -1,
ax_anim 2, 1, 163, 0, 0, 0, 0,
ax_anim_terminator
sStarmieAnims_12_7:
ax_anim 2, 0, 162, 0, -1, 0, -1,
ax_anim 2, 0, 162, 0, 0, 0, 0,
ax_anim 2, 0, 162, 0, -1, 0, -1,
ax_anim 2, 0, 162, 0, 0, 0, 0,
ax_anim 2, 0, 162, 0, -1, 0, -1,
ax_anim 2, 2, 162, 0, 0, 0, 0,
ax_anim 2, 0, 162, 0, -1, 0, -1,
ax_anim 2, 0, 162, 0, 0, 0, 0,
ax_anim 2, 0, 162, 0, -1, 0, -1,
ax_anim 2, 1, 162, 0, 0, 0, 0,
ax_anim_terminator
sStarmieAnims_12_8:
ax_anim 2, 0, 161, -1, -1, -1, -1,
ax_anim 2, 0, 161, 0, 0, 0, 0,
ax_anim 2, 0, 161, -1, -1, -1, -1,
ax_anim 2, 0, 161, 0, 0, 0, 0,
ax_anim 2, 0, 161, -1, -1, -1, -1,
ax_anim 2, 2, 161, 0, 0, 0, 0,
ax_anim 2, 0, 161, -1, -1, -1, -1,
ax_anim 2, 0, 161, 0, 0, 0, 0,
ax_anim 2, 0, 161, -1, -1, -1, -1,
ax_anim 2, 1, 161, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sStarmieAnims_13_1:
ax_anim 2, 0, 168, 0, 0, 0, 0,
ax_anim 2, 0, 169, 0, 0, 0, 0,
ax_anim 2, 0, 170, 0, 0, 0, 0,
ax_anim 2, 0, 171, 0, 0, 0, 0,
ax_anim 2, 0, 172, 0, 0, 0, 0,
ax_anim 2, 0, 173, 0, 0, 0, 0,
ax_anim 2, 0, 174, 0, 0, 0, 0,
ax_anim 2, 0, 175, 0, 0, 0, 0,
ax_anim 2, 2, 168, 0, 0, 0, 0,
ax_anim_terminator
sStarmieAnims_13_2:
ax_anim 2, 0, 175, 0, 0, 0, 0,
ax_anim 2, 0, 168, 0, 0, 0, 0,
ax_anim 2, 0, 169, 0, 0, 0, 0,
ax_anim 2, 0, 170, 0, 0, 0, 0,
ax_anim 2, 0, 171, 0, 0, 0, 0,
ax_anim 2, 0, 172, 0, 0, 0, 0,
ax_anim 2, 0, 173, 0, 0, 0, 0,
ax_anim 2, 0, 174, 0, 0, 0, 0,
ax_anim 2, 2, 175, 0, 0, 0, 0,
ax_anim_terminator
sStarmieAnims_13_3:
ax_anim 2, 0, 174, 0, 0, 0, 0,
ax_anim 2, 0, 175, 0, 0, 0, 0,
ax_anim 2, 0, 168, 0, 0, 0, 0,
ax_anim 2, 0, 169, 0, 0, 0, 0,
ax_anim 2, 0, 170, 0, 0, 0, 0,
ax_anim 2, 0, 171, 0, 0, 0, 0,
ax_anim 2, 0, 172, 0, 0, 0, 0,
ax_anim 2, 0, 173, 0, 0, 0, 0,
ax_anim 2, 2, 174, 0, 0, 0, 0,
ax_anim_terminator
sStarmieAnims_13_4:
ax_anim 2, 0, 173, 0, 0, 0, 0,
ax_anim 2, 0, 174, 0, 0, 0, 0,
ax_anim 2, 0, 175, 0, 0, 0, 0,
ax_anim 2, 0, 168, 0, 0, 0, 0,
ax_anim 2, 0, 169, 0, 0, 0, 0,
ax_anim 2, 0, 170, 0, 0, 0, 0,
ax_anim 2, 0, 171, 0, 0, 0, 0,
ax_anim 2, 0, 172, 0, 0, 0, 0,
ax_anim 2, 2, 173, 0, 0, 0, 0,
ax_anim_terminator
sStarmieAnims_13_5:
ax_anim 2, 0, 172, 0, 0, 0, 0,
ax_anim 2, 0, 173, 0, 0, 0, 0,
ax_anim 2, 0, 174, 0, 0, 0, 0,
ax_anim 2, 0, 175, 0, 0, 0, 0,
ax_anim 2, 0, 168, 0, 0, 0, 0,
ax_anim 2, 0, 169, 0, 0, 0, 0,
ax_anim 2, 0, 170, 0, 0, 0, 0,
ax_anim 2, 0, 171, 0, 0, 0, 0,
ax_anim 2, 2, 172, 0, 0, 0, 0,
ax_anim_terminator
sStarmieAnims_13_6:
ax_anim 2, 0, 171, 0, 0, 0, 0,
ax_anim 2, 0, 172, 0, 0, 0, 0,
ax_anim 2, 0, 173, 0, 0, 0, 0,
ax_anim 2, 0, 174, 0, 0, 0, 0,
ax_anim 2, 0, 175, 0, 0, 0, 0,
ax_anim 2, 0, 168, 0, 0, 0, 0,
ax_anim 2, 0, 169, 0, 0, 0, 0,
ax_anim 2, 0, 170, 0, 0, 0, 0,
ax_anim 2, 2, 171, 0, 0, 0, 0,
ax_anim_terminator
sStarmieAnims_13_7:
ax_anim 2, 0, 170, 0, 0, 0, 0,
ax_anim 2, 0, 171, 0, 0, 0, 0,
ax_anim 2, 0, 172, 0, 0, 0, 0,
ax_anim 2, 0, 173, 0, 0, 0, 0,
ax_anim 2, 0, 174, 0, 0, 0, 0,
ax_anim 2, 0, 175, 0, 0, 0, 0,
ax_anim 2, 0, 168, 0, 0, 0, 0,
ax_anim 2, 0, 169, 0, 0, 0, 0,
ax_anim 2, 2, 170, 0, 0, 0, 0,
ax_anim_terminator
sStarmieAnims_13_8:
ax_anim 2, 0, 169, 0, 0, 0, 0,
ax_anim 2, 0, 170, 0, 0, 0, 0,
ax_anim 2, 0, 171, 0, 0, 0, 0,
ax_anim 2, 0, 172, 0, 0, 0, 0,
ax_anim 2, 0, 173, 0, 0, 0, 0,
ax_anim 2, 0, 174, 0, 0, 0, 0,
ax_anim 2, 0, 175, 0, 0, 0, 0,
ax_anim 2, 0, 168, 0, 0, 0, 0,
ax_anim 2, 2, 169, 0, 0, 0, 0,
ax_anim_terminator
sStarmieGfx1:
.incbin "baserom.gba", 0xA33978, 0x200
sStarmieSprites1:
ax_sprite sStarmieGfx1, 0x200
ax_sprite_terminator
sStarmieGfx2:
.incbin "baserom.gba", 0xA33B88, 0x200
sStarmieSprites2:
ax_sprite sStarmieGfx2, 0x200
ax_sprite_terminator
sStarmieGfx3:
.incbin "baserom.gba", 0xA33D98, 0x200
sStarmieSprites3:
ax_sprite sStarmieGfx3, 0x200
ax_sprite_terminator
sStarmieGfx4:
.incbin "baserom.gba", 0xA33FA8, 0x200
sStarmieSprites4:
ax_sprite sStarmieGfx4, 0x200
ax_sprite_terminator
sStarmieGfx5:
.incbin "baserom.gba", 0xA341B8, 0x200
sStarmieSprites5:
ax_sprite sStarmieGfx5, 0x200
ax_sprite_terminator
sStarmieGfx6:
.incbin "baserom.gba", 0xA343C8, 0x200
sStarmieSprites6:
ax_sprite sStarmieGfx6, 0x200
ax_sprite_terminator
sStarmieGfx7:
.incbin "baserom.gba", 0xA345D8, 0x100
sStarmieSprites7:
ax_sprite sStarmieGfx7, 0x100
ax_sprite_terminator
sStarmieGfx8:
.incbin "baserom.gba", 0xA346E8, 0x100
sStarmieSprites8:
ax_sprite sStarmieGfx8, 0x100
ax_sprite_terminator
sStarmieGfx9:
.incbin "baserom.gba", 0xA347F8, 0x100
sStarmieSprites9:
ax_sprite sStarmieGfx9, 0x100
ax_sprite_terminator
sStarmieGfx10:
.incbin "baserom.gba", 0xA34908, 0x200
sStarmieSprites10:
ax_sprite sStarmieGfx10, 0x200
ax_sprite_terminator
sStarmieGfx11:
.incbin "baserom.gba", 0xA34B18, 0x200
sStarmieSprites11:
ax_sprite sStarmieGfx11, 0x200
ax_sprite_terminator
sStarmieGfx12:
.incbin "baserom.gba", 0xA34D28, 0x200
sStarmieSprites12:
ax_sprite sStarmieGfx12, 0x200
ax_sprite_terminator
sStarmieGfx13:
.incbin "baserom.gba", 0xA34F38, 0x200
sStarmieSprites13:
ax_sprite sStarmieGfx13, 0x200
ax_sprite_terminator
sStarmieGfx14:
.incbin "baserom.gba", 0xA35148, 0x200
sStarmieSprites14:
ax_sprite sStarmieGfx14, 0x200
ax_sprite_terminator
sStarmieGfx15:
.incbin "baserom.gba", 0xA35358, 0x200
sStarmieSprites15:
ax_sprite sStarmieGfx15, 0x200
ax_sprite_terminator
sStarmieGfx16:
.incbin "baserom.gba", 0xA35568, 0x60
sStarmieGfx16_1:
.incbin "baserom.gba", 0xA355C8, 0x60
sStarmieGfx16_2:
.incbin "baserom.gba", 0xA35628, 0x60
sStarmieSprites16:
ax_sprite sStarmieGfx16, 0x60
ax_sprite 0, 0x20
ax_sprite sStarmieGfx16_1, 0x60
ax_sprite 0, 0x20
ax_sprite sStarmieGfx16_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sStarmieGfx17:
.incbin "baserom.gba", 0xA356C0, 0x60
sStarmieGfx17_1:
.incbin "baserom.gba", 0xA35720, 0x60
sStarmieGfx17_2:
.incbin "baserom.gba", 0xA35780, 0x60
sStarmieSprites17:
ax_sprite sStarmieGfx17, 0x60
ax_sprite 0, 0x20
ax_sprite sStarmieGfx17_1, 0x60
ax_sprite 0, 0x20
ax_sprite sStarmieGfx17_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sStarmieGfx18:
.incbin "baserom.gba", 0xA35818, 0x60
sStarmieGfx18_1:
.incbin "baserom.gba", 0xA35878, 0x60
sStarmieGfx18_2:
.incbin "baserom.gba", 0xA358D8, 0x60
sStarmieGfx18_3:
.incbin "baserom.gba", 0xA35938, 0x20
sStarmieSprites18:
ax_sprite sStarmieGfx18, 0x60
ax_sprite 0, 0x20
ax_sprite sStarmieGfx18_1, 0x60
ax_sprite 0, 0x20
ax_sprite sStarmieGfx18_2, 0x60
ax_sprite 0, 0x40
ax_sprite sStarmieGfx18_3, 0x20
ax_sprite 0, 0x40
ax_sprite_terminator
sStarmieGfx19:
.incbin "baserom.gba", 0xA359A0, 0x40
sStarmieGfx19_1:
.incbin "baserom.gba", 0xA359E0, 0xE0
sStarmieSprites19:
ax_sprite 0, 0x20
ax_sprite sStarmieGfx19, 0x40
ax_sprite 0, 0x20
ax_sprite sStarmieGfx19_1, 0xe0
ax_sprite 0, 0xa0
ax_sprite_terminator
sStarmieGfx20:
.incbin "baserom.gba", 0xA35AF0, 0x60
sStarmieGfx20_1:
.incbin "baserom.gba", 0xA35B50, 0x100
sStarmieSprites20:
ax_sprite sStarmieGfx20, 0x60
ax_sprite 0, 0x20
ax_sprite sStarmieGfx20_1, 0x100
ax_sprite 0, 0x80
ax_sprite_terminator
sStarmieGfx21:
.incbin "baserom.gba", 0xA35C78, 0x40
sStarmieGfx21_1:
.incbin "baserom.gba", 0xA35CB8, 0x60
sStarmieGfx21_2:
.incbin "baserom.gba", 0xA35D18, 0x40
sStarmieGfx21_3:
.incbin "baserom.gba", 0xA35D58, 0x20
sStarmieSprites21:
ax_sprite 0, 0x20
ax_sprite sStarmieGfx21, 0x40
ax_sprite 0, 0x20
ax_sprite sStarmieGfx21_1, 0x60
ax_sprite 0, 0x20
ax_sprite sStarmieGfx21_2, 0x40
ax_sprite 0, 0x60
ax_sprite sStarmieGfx21_3, 0x20
ax_sprite 0, 0x40
ax_sprite_terminator
sStarmieGfx22:
.incbin "baserom.gba", 0xA35DC8, 0x40
sStarmieGfx22_1:
.incbin "baserom.gba", 0xA35E08, 0x60
sStarmieGfx22_2:
.incbin "baserom.gba", 0xA35E68, 0x60
sStarmieSprites22:
ax_sprite 0, 0x20
ax_sprite sStarmieGfx22, 0x40
ax_sprite 0, 0x20
ax_sprite sStarmieGfx22_1, 0x60
ax_sprite 0, 0x20
ax_sprite sStarmieGfx22_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sStarmieGfx23:
.incbin "baserom.gba", 0xA35F08, 0x60
sStarmieGfx23_1:
.incbin "baserom.gba", 0xA35F68, 0x60
sStarmieSprites23:
ax_sprite sStarmieGfx23, 0x60
ax_sprite 0, 0x20
ax_sprite sStarmieGfx23_1, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sStarmieGfx24:
.incbin "baserom.gba", 0xA35FF0, 0x60
sStarmieGfx24_1:
.incbin "baserom.gba", 0xA36050, 0x60
sStarmieGfx24_2:
.incbin "baserom.gba", 0xA360B0, 0x60
sStarmieSprites24:
ax_sprite sStarmieGfx24, 0x60
ax_sprite 0, 0x20
ax_sprite sStarmieGfx24_1, 0x60
ax_sprite 0, 0x20
ax_sprite sStarmieGfx24_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sStarmieGfx25:
.incbin "baserom.gba", 0xA36148, 0x60
sStarmieGfx25_1:
.incbin "baserom.gba", 0xA361A8, 0x60
sStarmieGfx25_2:
.incbin "baserom.gba", 0xA36208, 0x60
sStarmieSprites25:
ax_sprite sStarmieGfx25, 0x60
ax_sprite 0, 0x20
ax_sprite sStarmieGfx25_1, 0x60
ax_sprite 0, 0x20
ax_sprite sStarmieGfx25_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sStarmieGfx26:
.incbin "baserom.gba", 0xA362A0, 0x60
sStarmieGfx26_1:
.incbin "baserom.gba", 0xA36300, 0xE0
sStarmieSprites26:
ax_sprite sStarmieGfx26, 0x60
ax_sprite 0, 0x20
ax_sprite sStarmieGfx26_1, 0xe0
ax_sprite 0, 0xa0
ax_sprite_terminator
sStarmieGfx27:
.incbin "baserom.gba", 0xA36408, 0xC0
sStarmieGfx27_1:
.incbin "baserom.gba", 0xA364C8, 0x20
sStarmieSprites27:
ax_sprite sStarmieGfx27, 0xc0
ax_sprite 0, 0x20
ax_sprite sStarmieGfx27_1, 0x20
ax_sprite_terminator
sStarmieGfx28:
.incbin "baserom.gba", 0xA36508, 0xC0
sStarmieGfx28_1:
.incbin "baserom.gba", 0xA365C8, 0x20
sStarmieSprites28:
ax_sprite sStarmieGfx28, 0xc0
ax_sprite 0, 0x20
ax_sprite sStarmieGfx28_1, 0x20
ax_sprite_terminator
sStarmieGfx29:
.incbin "baserom.gba", 0xA36608, 0x40
sStarmieGfx29_1:
.incbin "baserom.gba", 0xA36648, 0x60
sStarmieGfx29_2:
.incbin "baserom.gba", 0xA366A8, 0x60
sStarmieGfx29_3:
.incbin "baserom.gba", 0xA36708, 0x20
sStarmieSprites29:
ax_sprite 0, 0x20
ax_sprite sStarmieGfx29, 0x40
ax_sprite 0, 0x20
ax_sprite sStarmieGfx29_1, 0x60
ax_sprite 0, 0x20
ax_sprite sStarmieGfx29_2, 0x60
ax_sprite 0, 0x40
ax_sprite sStarmieGfx29_3, 0x20
ax_sprite 0, 0x40
ax_sprite_terminator
sStarmieGfx30:
.incbin "baserom.gba", 0xA36778, 0x40
sStarmieGfx30_1:
.incbin "baserom.gba", 0xA367B8, 0x60
sStarmieGfx30_2:
.incbin "baserom.gba", 0xA36818, 0x60
sStarmieGfx30_3:
.incbin "baserom.gba", 0xA36878, 0x20
sStarmieSprites30:
ax_sprite 0, 0x20
ax_sprite sStarmieGfx30, 0x40
ax_sprite 0, 0x20
ax_sprite sStarmieGfx30_1, 0x60
ax_sprite 0, 0x20
ax_sprite sStarmieGfx30_2, 0x60
ax_sprite 0, 0x40
ax_sprite sStarmieGfx30_3, 0x20
ax_sprite 0, 0x40
ax_sprite_terminator
sStarmieGfx31:
.incbin "baserom.gba", 0xA368E8, 0x40
sStarmieGfx31_1:
.incbin "baserom.gba", 0xA36928, 0xE0
sStarmieGfx31_2:
.incbin "baserom.gba", 0xA36A08, 0x20
sStarmieSprites31:
ax_sprite 0, 0x20
ax_sprite sStarmieGfx31, 0x40
ax_sprite 0, 0x20
ax_sprite sStarmieGfx31_1, 0xe0
ax_sprite 0, 0x40
ax_sprite sStarmieGfx31_2, 0x20
ax_sprite 0, 0x40
ax_sprite_terminator
sStarmieGfx32:
.incbin "baserom.gba", 0xA36A68, 0x40
sStarmieGfx32_1:
.incbin "baserom.gba", 0xA36AA8, 0x100
sStarmieGfx32_2:
.incbin "baserom.gba", 0xA36BA8, 0x20
sStarmieSprites32:
ax_sprite 0, 0x20
ax_sprite sStarmieGfx32, 0x40
ax_sprite 0, 0x20
ax_sprite sStarmieGfx32_1, 0x100
ax_sprite 0, 0x40
ax_sprite sStarmieGfx32_2, 0x20
ax_sprite 0, 0x20
ax_sprite_terminator
sStarmieGfx33:
.incbin "baserom.gba", 0xA36C08, 0x200
sStarmieSprites33:
ax_sprite sStarmieGfx33, 0x200
ax_sprite_terminator
sStarmieGfx34:
.incbin "baserom.gba", 0xA36E18, 0x200
sStarmieSprites34:
ax_sprite sStarmieGfx34, 0x200
ax_sprite_terminator
sStarmieGfx35:
.incbin "baserom.gba", 0xA37028, 0x200
sStarmieSprites35:
ax_sprite sStarmieGfx35, 0x200
ax_sprite_terminator
sStarmieGfx36:
.incbin "baserom.gba", 0xA37238, 0x200
sStarmieSprites36:
ax_sprite sStarmieGfx36, 0x200
ax_sprite_terminator
sStarmieGfx37:
.incbin "baserom.gba", 0xA37448, 0x200
sStarmieSprites37:
ax_sprite sStarmieGfx37, 0x200
ax_sprite_terminator
sStarmieGfx38:
.incbin "baserom.gba", 0xA37658, 0x200
sStarmieSprites38:
ax_sprite sStarmieGfx38, 0x200
ax_sprite_terminator
sStarmieGfx39:
.incbin "baserom.gba", 0xA37868, 0x200
sStarmieSprites39:
ax_sprite sStarmieGfx39, 0x200
ax_sprite_terminator
sAxPosesStarmie:
.4byte sStarmiePose1
.4byte sStarmiePose2
.4byte sStarmiePose3
.4byte sStarmiePose4
.4byte sStarmiePose5
.4byte sStarmiePose6
.4byte sStarmiePose7
.4byte sStarmiePose8
.4byte sStarmiePose9
.4byte sStarmiePose10
.4byte sStarmiePose11
.4byte sStarmiePose12
.4byte sStarmiePose13
.4byte sStarmiePose14
.4byte sStarmiePose15
.4byte sStarmiePose16
.4byte sStarmiePose17
.4byte sStarmiePose18
.4byte sStarmiePose19
.4byte sStarmiePose20
.4byte sStarmiePose21
.4byte sStarmiePose22
.4byte sStarmiePose23
.4byte sStarmiePose24
.4byte sStarmiePose25
.4byte sStarmiePose26
.4byte sStarmiePose27
.4byte sStarmiePose28
.4byte sStarmiePose29
.4byte sStarmiePose30
.4byte sStarmiePose31
.4byte sStarmiePose32
.4byte sStarmiePose33
.4byte sStarmiePose34
.4byte sStarmiePose35
.4byte sStarmiePose36
.4byte sStarmiePose37
.4byte sStarmiePose38
.4byte sStarmiePose39
.4byte sStarmiePose40
.4byte sStarmiePose41
.4byte sStarmiePose42
.4byte sStarmiePose43
.4byte sStarmiePose44
.4byte sStarmiePose45
.4byte sStarmiePose46
.4byte sStarmiePose47
.4byte sStarmiePose48
.4byte sStarmiePose49
.4byte sStarmiePose50
.4byte sStarmiePose51
.4byte sStarmiePose52
.4byte sStarmiePose53
.4byte sStarmiePose54
.4byte sStarmiePose55
.4byte sStarmiePose56
.4byte sStarmiePose57
.4byte sStarmiePose58
.4byte sStarmiePose59
.4byte sStarmiePose60
.4byte sStarmiePose61
.4byte sStarmiePose62
.4byte sStarmiePose63
.4byte sStarmiePose64
.4byte sStarmiePose65
.4byte sStarmiePose66
.4byte sStarmiePose67
.4byte sStarmiePose68
.4byte sStarmiePose69
.4byte sStarmiePose70
.4byte sStarmiePose71
.4byte sStarmiePose72
.4byte sStarmiePose73
.4byte sStarmiePose74
.4byte sStarmiePose75
.4byte sStarmiePose76
.4byte sStarmiePose77
.4byte sStarmiePose78
.4byte sStarmiePose79
.4byte sStarmiePose80
.4byte sStarmiePose81
.4byte sStarmiePose82
.4byte sStarmiePose83
.4byte sStarmiePose84
.4byte sStarmiePose85
.4byte sStarmiePose86
.4byte sStarmiePose87
.4byte sStarmiePose88
.4byte sStarmiePose89
.4byte sStarmiePose90
.4byte sStarmiePose91
.4byte sStarmiePose92
.4byte sStarmiePose93
.4byte sStarmiePose94
.4byte sStarmiePose95
.4byte sStarmiePose96
.4byte sStarmiePose97
.4byte sStarmiePose98
.4byte sStarmiePose99
.4byte sStarmiePose100
.4byte sStarmiePose101
.4byte sStarmiePose102
.4byte sStarmiePose103
.4byte sStarmiePose104
.4byte sStarmiePose105
.4byte sStarmiePose106
.4byte sStarmiePose107
.4byte sStarmiePose108
.4byte sStarmiePose109
.4byte sStarmiePose110
.4byte sStarmiePose111
.4byte sStarmiePose112
.4byte sStarmiePose113
.4byte sStarmiePose114
.4byte sStarmiePose115
.4byte sStarmiePose116
.4byte sStarmiePose117
.4byte sStarmiePose118
.4byte sStarmiePose119
.4byte sStarmiePose120
.4byte sStarmiePose121
.4byte sStarmiePose122
.4byte sStarmiePose123
.4byte sStarmiePose124
.4byte sStarmiePose125
.4byte sStarmiePose126
.4byte sStarmiePose127
.4byte sStarmiePose128
.4byte sStarmiePose129
.4byte sStarmiePose130
.4byte sStarmiePose131
.4byte sStarmiePose132
.4byte sStarmiePose133
.4byte sStarmiePose134
.4byte sStarmiePose135
.4byte sStarmiePose136
.4byte sStarmiePose137
.4byte sStarmiePose138
.4byte sStarmiePose139
.4byte sStarmiePose140
.4byte sStarmiePose141
.4byte sStarmiePose142
.4byte sStarmiePose143
.4byte sStarmiePose144
.4byte sStarmiePose145
.4byte sStarmiePose146
.4byte sStarmiePose147
.4byte sStarmiePose148
.4byte sStarmiePose149
.4byte sStarmiePose150
.4byte sStarmiePose151
.4byte sStarmiePose152
.4byte sStarmiePose153
.4byte sStarmiePose154
.4byte sStarmiePose155
.4byte sStarmiePose156
.4byte sStarmiePose157
.4byte sStarmiePose158
.4byte sStarmiePose159
.4byte sStarmiePose160
.4byte sStarmiePose161
.4byte sStarmiePose162
.4byte sStarmiePose163
.4byte sStarmiePose164
.4byte sStarmiePose165
.4byte sStarmiePose166
.4byte sStarmiePose167
.4byte sStarmiePose168
.4byte sStarmiePose169
.4byte sStarmiePose170
.4byte sStarmiePose171
.4byte sStarmiePose172
.4byte sStarmiePose173
.4byte sStarmiePose174
.4byte sStarmiePose175
.4byte sStarmiePose176
sAxPositionsStarmie:
.2byte    0,   -7, 	  -8,  -13, 	   8,  -13, 	   0,  -10
.2byte    1,   -6, 	  -7,  -12, 	   7,  -10, 	   0,   -9
.2byte   -1,   -6, 	  -7,  -10, 	   6,  -12, 	   1,   -9
.2byte    3,   -8, 	   6,  -15, 	  -7,  -10, 	   0,  -10
.2byte    2,   -7, 	   7,  -13, 	  -7,   -9, 	   0,   -9
.2byte    4,   -7, 	   6,  -12, 	  -5,  -10, 	   0,   -9
.2byte    5,   -8, 	   2,  -15, 	  -2,   -9, 	   0,   -9
.2byte    5,   -7, 	   5,  -15, 	  -3,   -7, 	   0,   -8
.2byte    4,  -10, 	   2,  -12, 	   1,  -11, 	  -1,   -7
.2byte   -1,  -12, 	  -7,  -14, 	   5,  -10, 	  -3,  -10
.2byte    4,  -10, 	  -4,  -13, 	   7,   -7, 	   0,   -9
.2byte   -3,  -12, 	  -8,  -14, 	   7,   -9, 	  -2,   -9
.2byte    0,  -12, 	   8,  -13, 	  -8,  -13, 	   0,  -10
.2byte   -2,  -11, 	   5,  -14, 	  -8,  -10, 	   1,  -10
.2byte    2,  -11, 	   8,  -10, 	  -5,  -14, 	  -1,   -9
.2byte   -1,  -12, 	   5,  -14, 	  -7,  -10, 	   1,  -10
.2byte   -3,  -10, 	   5,  -13, 	  -6,   -7, 	   1,   -9
.2byte    3,  -12, 	   8,  -14, 	  -7,   -9, 	   2,   -9
.2byte   -5,   -8, 	  -2,  -15, 	   2,   -9, 	   0,   -9
.2byte   -5,   -7, 	  -5,  -15, 	   3,   -7, 	   0,   -8
.2byte   -4,  -11, 	  -2,  -13, 	  -1,  -12, 	   1,   -8
.2byte   -3,   -8, 	  -6,  -15, 	   7,  -10, 	   0,  -10
.2byte   -2,   -7, 	  -7,  -13, 	   7,   -9, 	   0,   -9
.2byte   -4,   -7, 	  -6,  -12, 	   5,  -10, 	   0,   -9
.2byte    0,   -7, 	  -8,  -13, 	   8,  -13, 	   0,  -10
.2byte    0,   -9, 	  -8,  -13, 	   8,  -13, 	   0,  -10
.2byte    0,  -10, 	  -8,  -12, 	   8,  -12, 	   0,   -9
.2byte    0,  -10, 	  -6,  -15, 	   8,   -6, 	   0,   -9
.2byte    3,   -8, 	   6,  -15, 	  -7,  -10, 	   0,  -10
.2byte    2,  -10, 	   5,  -15, 	  -7,   -7, 	   2,   -9
.2byte    4,   -7, 	   8,  -15, 	  -7,  -10, 	   2,   -9
.2byte    5,   -8, 	   2,  -15, 	  -2,   -9, 	   0,   -9
.2byte    4,  -13, 	   0,  -17, 	  -1,   -7, 	   1,  -11
.2byte   -1,  -12, 	  -7,  -14, 	   5,  -10, 	  -3,  -10
.2byte    4,  -13, 	  -6,  -15, 	   6,   -6, 	   0,  -10
.2byte    0,  -12, 	   8,  -13, 	  -8,  -13, 	   0,  -10
.2byte    0,  -16, 	   8,  -12, 	  -9,  -12, 	   0,  -12
.2byte   -1,  -12, 	   5,  -14, 	  -7,  -10, 	   1,  -10
.2byte   -6,  -13, 	   4,  -15, 	  -8,   -6, 	  -2,  -10
.2byte   -5,   -8, 	  -2,  -15, 	   2,   -9, 	   0,   -9
.2byte   -4,  -13, 	   0,  -17, 	   1,   -7, 	  -1,  -11
.2byte   -3,   -8, 	  -6,  -15, 	   7,  -10, 	   0,  -10
.2byte   -2,  -10, 	  -5,  -15, 	   7,   -7, 	  -2,   -9
.2byte    0,   -7, 	  -8,  -13, 	   8,  -13, 	   0,  -10
.2byte    0,   -9, 	  -8,  -13, 	   8,  -13, 	   0,  -10
.2byte    0,  -10, 	  -8,  -12, 	   8,  -12, 	   0,   -9
.2byte    0,  -10, 	  -6,  -15, 	   8,   -6, 	   0,   -9
.2byte    3,   -8, 	   6,  -15, 	  -7,  -10, 	   0,  -10
.2byte    2,  -10, 	   5,  -15, 	  -7,   -7, 	   2,   -9
.2byte    4,   -7, 	   8,  -15, 	  -7,  -10, 	   2,   -9
.2byte    5,   -8, 	   2,  -15, 	  -2,   -9, 	   0,   -9
.2byte    4,  -13, 	   0,  -17, 	  -1,   -7, 	   1,  -11
.2byte   -1,  -12, 	  -7,  -14, 	   5,  -10, 	  -3,  -10
.2byte    4,  -13, 	  -6,  -15, 	   6,   -6, 	   0,  -10
.2byte    0,  -12, 	   8,  -13, 	  -8,  -13, 	   0,  -10
.2byte    0,  -16, 	   8,  -12, 	  -9,  -12, 	   0,  -12
.2byte   -1,  -12, 	   5,  -14, 	  -7,  -10, 	   1,  -10
.2byte   -6,  -13, 	   4,  -15, 	  -8,   -6, 	  -2,  -10
.2byte   -5,   -8, 	  -2,  -15, 	   2,   -9, 	   0,   -9
.2byte   -4,  -13, 	   0,  -17, 	   1,   -7, 	  -1,  -11
.2byte   -3,   -8, 	  -6,  -15, 	   7,  -10, 	   0,  -10
.2byte   -2,  -10, 	  -5,  -15, 	   7,   -7, 	  -2,   -9
.2byte    0,   -7, 	  -8,  -13, 	   8,  -13, 	   0,  -10
.2byte    1,   -6, 	  -7,  -12, 	   7,  -10, 	   0,   -9
.2byte   -1,   -6, 	  -7,  -10, 	   6,  -12, 	   1,   -9
.2byte    0,   -7, 	  -9,  -14, 	   9,  -14, 	   0,   -9
.2byte    0,   -7, 	  -9,  -14, 	   9,  -14, 	   0,   -9
.2byte    3,   -8, 	   6,  -15, 	  -7,  -10, 	   0,  -10
.2byte    2,   -7, 	   7,  -13, 	  -7,   -9, 	   0,   -9
.2byte    4,   -7, 	   6,  -12, 	  -5,  -10, 	   0,   -9
.2byte    4,   -7, 	   8,  -15, 	  -7,  -10, 	   2,   -9
.2byte    4,   -7, 	   8,  -16, 	  -7,  -10, 	   1,   -8
.2byte    5,   -8, 	   2,  -15, 	  -2,   -9, 	   0,   -9
.2byte    5,   -7, 	   5,  -15, 	  -3,   -7, 	   0,   -8
.2byte    4,  -10, 	   2,  -12, 	   1,  -11, 	  -1,   -7
.2byte    6,   -8, 	  -3,  -16, 	  -2,   -8, 	   2,   -9
.2byte    6,   -8, 	  -2,  -18, 	  -2,   -8, 	   2,   -9
.2byte   -1,  -12, 	  -7,  -14, 	   5,  -10, 	  -3,  -10
.2byte    4,  -10, 	  -4,  -13, 	   7,   -7, 	   0,   -9
.2byte   -3,  -12, 	  -8,  -14, 	   7,   -9, 	  -2,   -9
.2byte   -1,   -9, 	  -8,  -14, 	   5,  -10, 	  -2,  -10
.2byte   -1,  -11, 	  -8,  -14, 	   5,   -9, 	  -2,  -10
.2byte    0,  -12, 	   8,  -13, 	  -8,  -13, 	   0,  -10
.2byte   -2,  -11, 	   5,  -14, 	  -8,  -10, 	   1,  -10
.2byte    2,  -11, 	   8,  -10, 	  -5,  -14, 	  -1,   -9
.2byte   -1,  -10, 	   8,  -12, 	  -8,  -12, 	   1,  -11
.2byte    3,  -10, 	   8,  -11, 	  -7,  -13, 	  -1,  -11
.2byte   -1,  -12, 	   5,  -14, 	  -7,  -10, 	   1,  -10
.2byte   -3,  -10, 	   5,  -13, 	  -6,   -7, 	   1,   -9
.2byte    3,  -12, 	   8,  -14, 	  -7,   -9, 	   2,   -9
.2byte   -1,   -9, 	   6,  -14, 	  -7,  -10, 	   0,  -10
.2byte   -1,  -11, 	   6,  -14, 	  -7,   -9, 	   0,  -10
.2byte   -5,   -8, 	  -2,  -15, 	   2,   -9, 	   0,   -9
.2byte   -5,   -7, 	  -5,  -15, 	   3,   -7, 	   0,   -8
.2byte   -4,  -11, 	  -2,  -13, 	  -1,  -12, 	   1,   -8
.2byte   -6,   -8, 	   3,  -16, 	   2,   -8, 	  -2,   -9
.2byte   -6,   -8, 	   2,  -18, 	   2,   -8, 	  -2,   -9
.2byte   -3,   -8, 	  -6,  -15, 	   7,  -10, 	   0,  -10
.2byte   -2,   -7, 	  -7,  -13, 	   7,   -9, 	   0,   -9
.2byte   -4,   -7, 	  -6,  -12, 	   5,  -10, 	   0,   -9
.2byte   -4,   -7, 	  -8,  -15, 	   7,  -10, 	  -2,   -9
.2byte   -4,   -7, 	  -8,  -16, 	   7,  -10, 	  -1,   -8
.2byte    0,   -5, 	  -8,  -11, 	   8,  -11, 	   0,   -8
.2byte   -3,   -6, 	  -6,  -13, 	   7,   -8, 	   0,   -8
.2byte   -5,   -6, 	  -2,  -13, 	   2,   -7, 	   0,   -7
.2byte   -1,  -10, 	   5,  -12, 	  -7,   -8, 	   1,   -8
.2byte    0,  -10, 	   8,  -11, 	  -8,  -11, 	   0,   -8
.2byte    1,  -10, 	  -5,  -12, 	   7,   -8, 	  -1,   -8
.2byte    5,   -6, 	   2,  -13, 	  -2,   -7, 	   0,   -7
.2byte    3,   -6, 	   6,  -13, 	  -7,   -8, 	   0,   -8
.2byte    0,   -6, 	  -7,   -9, 	   8,   -3, 	   0,   -4
.2byte    0,   -5, 	  -3,   -9, 	   9,   -2, 	   0,   -3
.2byte   -1,   -9, 	  -8,   -9, 	   7,   -8, 	  -1,  -10
.2byte    3,   -7, 	   5,  -14, 	  -6,   -8, 	  -1,   -9
.2byte    3,  -12, 	   0,  -17, 	  -4,   -7, 	  -1,  -10
.2byte    2,  -13, 	  -2,  -18, 	   4,   -6, 	  -1,   -9
.2byte    0,  -14, 	   7,  -10, 	  -8,  -10, 	   0,   -9
.2byte   -3,  -13, 	   1,  -18, 	  -5,   -6, 	   0,   -9
.2byte   -4,  -12, 	  -1,  -17, 	   3,   -7, 	   0,  -10
.2byte   -4,   -7, 	  -6,  -14, 	   5,   -8, 	   0,   -9
.2byte    0,   -5, 	  -8,  -11, 	   8,  -11, 	   0,   -8
.2byte   -3,   -6, 	  -6,  -13, 	   7,   -8, 	   0,   -8
.2byte   -5,   -6, 	  -2,  -13, 	   2,   -7, 	   0,   -7
.2byte   -1,  -10, 	   5,  -12, 	  -7,   -8, 	   1,   -8
.2byte    0,  -10, 	   8,  -11, 	  -8,  -11, 	   0,   -8
.2byte    1,  -10, 	  -5,  -12, 	   7,   -8, 	  -1,   -8
.2byte    5,   -6, 	   2,  -13, 	  -2,   -7, 	   0,   -7
.2byte    3,   -6, 	   6,  -13, 	  -7,   -8, 	   0,   -8
.2byte    0,   -5, 	  -8,  -11, 	   8,  -11, 	   0,   -8
.2byte   -3,   -6, 	  -6,  -13, 	   7,   -8, 	   0,   -8
.2byte   -5,   -6, 	  -2,  -13, 	   2,   -7, 	   0,   -7
.2byte   -1,  -10, 	   5,  -12, 	  -7,   -8, 	   1,   -8
.2byte    0,  -10, 	   8,  -11, 	  -8,  -11, 	   0,   -8
.2byte    1,  -10, 	  -5,  -12, 	   7,   -8, 	  -1,   -8
.2byte    5,   -6, 	   2,  -13, 	  -2,   -7, 	   0,   -7
.2byte    3,   -6, 	   6,  -13, 	  -7,   -8, 	   0,   -8
.2byte    0,   -5, 	  -8,  -11, 	   8,  -11, 	   0,   -8
.2byte    3,   -6, 	   6,  -13, 	  -7,   -8, 	   0,   -8
.2byte    5,   -6, 	   2,  -13, 	  -2,   -7, 	   0,   -7
.2byte    1,  -10, 	  -5,  -12, 	   7,   -8, 	  -1,   -8
.2byte    0,  -10, 	   8,  -11, 	  -8,  -11, 	   0,   -8
.2byte   -1,  -10, 	   5,  -12, 	  -7,   -8, 	   1,   -8
.2byte   -5,   -6, 	  -2,  -13, 	   2,   -7, 	   0,   -7
.2byte   -3,   -6, 	  -6,  -13, 	   7,   -8, 	   0,   -8
.2byte    0,   -7, 	  -8,  -13, 	   8,  -13, 	   0,  -10
.2byte    0,   -9, 	  -8,  -13, 	   8,  -13, 	   0,  -10
.2byte    3,   -8, 	   6,  -15, 	  -7,  -10, 	   0,  -10
.2byte    0,  -10, 	   3,  -15, 	  -9,   -7, 	   0,   -9
.2byte    5,   -8, 	   2,  -15, 	  -2,   -9, 	   0,   -9
.2byte    4,  -13, 	   0,  -17, 	  -1,   -7, 	   1,  -11
.2byte   -1,  -12, 	  -7,  -14, 	   5,  -10, 	  -3,  -10
.2byte    4,  -13, 	  -6,  -15, 	   6,   -6, 	   0,  -10
.2byte    0,  -12, 	   8,  -13, 	  -8,  -13, 	   0,  -10
.2byte    0,  -16, 	   8,  -12, 	  -9,  -12, 	   0,  -12
.2byte   -1,  -12, 	   5,  -14, 	  -7,  -10, 	   1,  -10
.2byte   -6,  -13, 	   4,  -15, 	  -8,   -6, 	  -2,  -10
.2byte   -5,   -8, 	  -2,  -15, 	   2,   -9, 	   0,   -9
.2byte   -4,  -13, 	   0,  -17, 	   1,   -7, 	  -1,  -11
.2byte   -3,   -8, 	  -6,  -15, 	   7,  -10, 	   0,  -10
.2byte    0,  -10, 	  -3,  -15, 	   9,   -7, 	   0,   -9
.2byte    0,   -7, 	  -9,  -14, 	   9,  -14, 	   0,   -9
.2byte   -3,   -8, 	  -7,  -16, 	   8,  -11, 	  -1,  -10
.2byte   -6,   -8, 	   3,  -16, 	   2,   -8, 	  -2,   -9
.2byte   -1,   -9, 	   6,  -14, 	  -7,  -10, 	   0,  -10
.2byte   -1,  -10, 	   8,  -12, 	  -8,  -12, 	   1,  -11
.2byte    1,   -9, 	  -6,  -14, 	   7,  -10, 	   0,  -10
.2byte    5,   -8, 	  -4,  -16, 	  -3,   -8, 	   1,   -9
.2byte    2,   -8, 	   6,  -16, 	  -9,  -11, 	   0,  -10
.2byte    0,   -5, 	  -8,  -11, 	   8,  -11, 	   0,   -8
.2byte   -3,   -6, 	  -6,  -13, 	   7,   -8, 	   0,   -8
.2byte   -5,   -6, 	  -2,  -13, 	   2,   -7, 	   0,   -7
.2byte   -1,  -10, 	   5,  -12, 	  -7,   -8, 	   1,   -8
.2byte    0,  -10, 	   8,  -11, 	  -8,  -11, 	   0,   -8
.2byte    1,  -10, 	  -5,  -12, 	   7,   -8, 	  -1,   -8
.2byte    5,   -6, 	   2,  -13, 	  -2,   -7, 	   0,   -7
.2byte    3,   -6, 	   6,  -13, 	  -7,   -8, 	   0,   -8
sStarmieAnimTable1:
.4byte sStarmieAnims_1_1
.4byte sStarmieAnims_1_2
.4byte sStarmieAnims_1_3
.4byte sStarmieAnims_1_4
.4byte sStarmieAnims_1_5
.4byte sStarmieAnims_1_6
.4byte sStarmieAnims_1_7
.4byte sStarmieAnims_1_8
sStarmieAnimTable2:
.4byte sStarmieAnims_2_1
.4byte sStarmieAnims_2_2
.4byte sStarmieAnims_2_3
.4byte sStarmieAnims_2_4
.4byte sStarmieAnims_2_5
.4byte sStarmieAnims_2_6
.4byte sStarmieAnims_2_7
.4byte sStarmieAnims_2_8
sStarmieAnimTable3:
.4byte sStarmieAnims_3_1
.4byte sStarmieAnims_3_2
.4byte sStarmieAnims_3_3
.4byte sStarmieAnims_3_4
.4byte sStarmieAnims_3_5
.4byte sStarmieAnims_3_6
.4byte sStarmieAnims_3_7
.4byte sStarmieAnims_3_8
sStarmieAnimTable4:
.4byte sStarmieAnims_4_1
.4byte sStarmieAnims_4_2
.4byte sStarmieAnims_4_3
.4byte sStarmieAnims_4_4
.4byte sStarmieAnims_4_5
.4byte sStarmieAnims_4_6
.4byte sStarmieAnims_4_7
.4byte sStarmieAnims_4_8
sStarmieAnimTable5:
.4byte sStarmieAnims_5_1
.4byte sStarmieAnims_5_2
.4byte sStarmieAnims_5_3
.4byte sStarmieAnims_5_4
.4byte sStarmieAnims_5_5
.4byte sStarmieAnims_5_6
.4byte sStarmieAnims_5_7
.4byte sStarmieAnims_5_8
sStarmieAnimTable6:
.4byte sStarmieAnims_6_1
.4byte sStarmieAnims_6_1
.4byte sStarmieAnims_6_1
.4byte sStarmieAnims_6_1
.4byte sStarmieAnims_6_1
.4byte sStarmieAnims_6_1
.4byte sStarmieAnims_6_1
.4byte sStarmieAnims_6_1
sStarmieAnimTable7:
.4byte sStarmieAnims_7_1
.4byte sStarmieAnims_7_2
.4byte sStarmieAnims_7_3
.4byte sStarmieAnims_7_4
.4byte sStarmieAnims_7_5
.4byte sStarmieAnims_7_6
.4byte sStarmieAnims_7_7
.4byte sStarmieAnims_7_8
sStarmieAnimTable8:
.4byte sStarmieAnims_8_1
.4byte sStarmieAnims_8_2
.4byte sStarmieAnims_8_3
.4byte sStarmieAnims_8_4
.4byte sStarmieAnims_8_5
.4byte sStarmieAnims_8_6
.4byte sStarmieAnims_8_7
.4byte sStarmieAnims_8_8
sStarmieAnimTable9:
.4byte sStarmieAnims_9_1
.4byte sStarmieAnims_9_2
.4byte sStarmieAnims_9_3
.4byte sStarmieAnims_9_4
.4byte sStarmieAnims_9_5
.4byte sStarmieAnims_9_6
.4byte sStarmieAnims_9_7
.4byte sStarmieAnims_9_8
sStarmieAnimTable10:
.4byte sStarmieAnims_10_1
.4byte sStarmieAnims_10_2
.4byte sStarmieAnims_10_3
.4byte sStarmieAnims_10_4
.4byte sStarmieAnims_10_5
.4byte sStarmieAnims_10_6
.4byte sStarmieAnims_10_7
.4byte sStarmieAnims_10_8
sStarmieAnimTable11:
.4byte sStarmieAnims_11_1
.4byte sStarmieAnims_11_2
.4byte sStarmieAnims_11_3
.4byte sStarmieAnims_11_4
.4byte sStarmieAnims_11_5
.4byte sStarmieAnims_11_6
.4byte sStarmieAnims_11_7
.4byte sStarmieAnims_11_8
sStarmieAnimTable12:
.4byte sStarmieAnims_12_1
.4byte sStarmieAnims_12_2
.4byte sStarmieAnims_12_3
.4byte sStarmieAnims_12_4
.4byte sStarmieAnims_12_5
.4byte sStarmieAnims_12_6
.4byte sStarmieAnims_12_7
.4byte sStarmieAnims_12_8
sStarmieAnimTable13:
.4byte sStarmieAnims_13_1
.4byte sStarmieAnims_13_2
.4byte sStarmieAnims_13_3
.4byte sStarmieAnims_13_4
.4byte sStarmieAnims_13_5
.4byte sStarmieAnims_13_6
.4byte sStarmieAnims_13_7
.4byte sStarmieAnims_13_8
sAxAnimationsStarmie:
.4byte sStarmieAnimTable1
.4byte sStarmieAnimTable2
.4byte sStarmieAnimTable3
.4byte sStarmieAnimTable4
.4byte sStarmieAnimTable5
.4byte sStarmieAnimTable6
.4byte sStarmieAnimTable7
.4byte sStarmieAnimTable8
.4byte sStarmieAnimTable9
.4byte sStarmieAnimTable10
.4byte sStarmieAnimTable11
.4byte sStarmieAnimTable12
.4byte sStarmieAnimTable13
sAxSpritesStarmie:
.4byte sStarmieSprites1
.4byte sStarmieSprites2
.4byte sStarmieSprites3
.4byte sStarmieSprites4
.4byte sStarmieSprites5
.4byte sStarmieSprites6
.4byte sStarmieSprites7
.4byte sStarmieSprites8
.4byte sStarmieSprites9
.4byte sStarmieSprites10
.4byte sStarmieSprites11
.4byte sStarmieSprites12
.4byte sStarmieSprites13
.4byte sStarmieSprites14
.4byte sStarmieSprites15
.4byte sStarmieSprites16
.4byte sStarmieSprites17
.4byte sStarmieSprites18
.4byte sStarmieSprites19
.4byte sStarmieSprites20
.4byte sStarmieSprites21
.4byte sStarmieSprites22
.4byte sStarmieSprites23
.4byte sStarmieSprites24
.4byte sStarmieSprites25
.4byte sStarmieSprites26
.4byte sStarmieSprites27
.4byte sStarmieSprites28
.4byte sStarmieSprites29
.4byte sStarmieSprites30
.4byte sStarmieSprites31
.4byte sStarmieSprites32
.4byte sStarmieSprites33
.4byte sStarmieSprites34
.4byte sStarmieSprites35
.4byte sStarmieSprites36
.4byte sStarmieSprites37
.4byte sStarmieSprites38
.4byte sStarmieSprites39
sAxMainStarmie:
ax_main sAxPosesStarmie, sAxAnimationsStarmie, 13, sAxSpritesStarmie, sAxPositionsStarmie
