.global gAxStaryu
gAxStaryu:
ax_siro sAxMainStaryu
sStaryuPose1:
ax_pose 0, 0x01eb, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose2:
ax_pose 1, 0x01ec, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose3:
ax_pose 2, 0x01ec, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose4:
ax_pose 3, 0x01ed, 0x90ed, 0x4c00
ax_pose_terminator
sStaryuPose5:
ax_pose 4, 0x01ee, 0x90ed, 0x4c00
ax_pose_terminator
sStaryuPose6:
ax_pose 5, 0x01ee, 0x90ed, 0x4c00
ax_pose_terminator
sStaryuPose7:
ax_pose 6, 0x81ed, 0x90f9, 0x4c00
ax_pose_terminator
sStaryuPose8:
ax_pose 7, 0x81ee, 0x90f9, 0x4c00
ax_pose_terminator
sStaryuPose9:
ax_pose 8, 0x81ee, 0x90f9, 0x4c00
ax_pose_terminator
sStaryuPose10:
ax_pose 9, 0x01ed, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose11:
ax_pose 10, 0x01ed, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose12:
ax_pose 11, 0x01ee, 0x80f5, 0x4c00
ax_pose_terminator
sStaryuPose13:
ax_pose 12, 0x01eb, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose14:
ax_pose 13, 0x01ec, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose15:
ax_pose 14, 0x01ec, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose16:
ax_pose 15, 0x01ed, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose17:
ax_pose 16, 0x01ee, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose18:
ax_pose 17, 0x01ed, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose19:
ax_pose 6, 0x81ed, 0x80f8, 0x4c00
ax_pose_terminator
sStaryuPose20:
ax_pose 7, 0x81ee, 0x80f8, 0x4c00
ax_pose_terminator
sStaryuPose21:
ax_pose 8, 0x81ee, 0x80f8, 0x4c00
ax_pose_terminator
sStaryuPose22:
ax_pose 3, 0x01ed, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose23:
ax_pose 4, 0x01ee, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose24:
ax_pose 5, 0x01ee, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose25:
ax_pose 0, 0x01eb, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose26:
ax_pose 18, 0x01eb, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose27:
ax_pose 19, 0x01ee, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose28:
ax_pose 20, 0x01ee, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose29:
ax_pose 3, 0x01ed, 0x90ed, 0x4c00
ax_pose_terminator
sStaryuPose30:
ax_pose 21, 0x01ed, 0x90ed, 0x4c00
ax_pose_terminator
sStaryuPose31:
ax_pose 6, 0x81ed, 0x90f9, 0x4c00
ax_pose_terminator
sStaryuPose32:
ax_pose 22, 0x01ed, 0x90eb, 0x4c00
ax_pose_terminator
sStaryuPose33:
ax_pose 9, 0x01ed, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose34:
ax_pose 23, 0x01f3, 0x40f7, 0x4c00
ax_pose_terminator
sStaryuPose35:
ax_pose 12, 0x01eb, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose36:
ax_pose 24, 0x41f3, 0x80f3, 0x4c00
ax_pose_terminator
sStaryuPose37:
ax_pose 15, 0x01ed, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose38:
ax_pose 25, 0x01f3, 0x40f9, 0x4c00
ax_pose_terminator
sStaryuPose39:
ax_pose 6, 0x81ed, 0x80f8, 0x4c00
ax_pose_terminator
sStaryuPose40:
ax_pose 22, 0x01ed, 0x80f6, 0x4c00
ax_pose_terminator
sStaryuPose41:
ax_pose 3, 0x01ed, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose42:
ax_pose 21, 0x01ed, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose43:
ax_pose 0, 0x01eb, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose44:
ax_pose 18, 0x01eb, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose45:
ax_pose 19, 0x01ee, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose46:
ax_pose 20, 0x01ee, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose47:
ax_pose 3, 0x01ed, 0x90ed, 0x4c00
ax_pose_terminator
sStaryuPose48:
ax_pose 21, 0x01ed, 0x90ed, 0x4c00
ax_pose_terminator
sStaryuPose49:
ax_pose 6, 0x81ed, 0x90f9, 0x4c00
ax_pose_terminator
sStaryuPose50:
ax_pose 22, 0x01ed, 0x90eb, 0x4c00
ax_pose_terminator
sStaryuPose51:
ax_pose 9, 0x01ed, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose52:
ax_pose 23, 0x01f3, 0x40f7, 0x4c00
ax_pose_terminator
sStaryuPose53:
ax_pose 12, 0x01eb, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose54:
ax_pose 24, 0x41f3, 0x80f3, 0x4c00
ax_pose_terminator
sStaryuPose55:
ax_pose 15, 0x01ed, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose56:
ax_pose 25, 0x01f3, 0x40f9, 0x4c00
ax_pose_terminator
sStaryuPose57:
ax_pose 6, 0x81ed, 0x80f8, 0x4c00
ax_pose_terminator
sStaryuPose58:
ax_pose 22, 0x01ed, 0x80f6, 0x4c00
ax_pose_terminator
sStaryuPose59:
ax_pose 3, 0x01ed, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose60:
ax_pose 21, 0x01ed, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose61:
ax_pose 0, 0x01eb, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose62:
ax_pose 1, 0x01ec, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose63:
ax_pose 2, 0x01ec, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose64:
ax_pose 26, 0x01eb, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose65:
ax_pose 3, 0x01ed, 0x90ed, 0x4c00
ax_pose_terminator
sStaryuPose66:
ax_pose 4, 0x01ee, 0x90ed, 0x4c00
ax_pose_terminator
sStaryuPose67:
ax_pose 5, 0x01ee, 0x90ed, 0x4c00
ax_pose_terminator
sStaryuPose68:
ax_pose 27, 0x01ed, 0x90ed, 0x4c00
ax_pose_terminator
sStaryuPose69:
ax_pose 6, 0x81ec, 0x90f9, 0x4c00
ax_pose_terminator
sStaryuPose70:
ax_pose 7, 0x81ec, 0x90f9, 0x4c00
ax_pose_terminator
sStaryuPose71:
ax_pose 8, 0x81ec, 0x90f9, 0x4c00
ax_pose_terminator
sStaryuPose72:
ax_pose 28, 0x81ec, 0x90f9, 0x4c00
ax_pose_terminator
sStaryuPose73:
ax_pose 9, 0x01ed, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose74:
ax_pose 10, 0x01ed, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose75:
ax_pose 11, 0x01ee, 0x80f5, 0x4c00
ax_pose_terminator
sStaryuPose76:
ax_pose 29, 0x81ed, 0x80f9, 0x4c00
ax_pose_terminator
sStaryuPose77:
ax_pose 12, 0x01eb, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose78:
ax_pose 13, 0x01ec, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose79:
ax_pose 14, 0x01ec, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose80:
ax_pose 30, 0x01eb, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose81:
ax_pose 15, 0x01ed, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose82:
ax_pose 16, 0x01ee, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose83:
ax_pose 17, 0x01ed, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose84:
ax_pose 31, 0x81ed, 0x80f8, 0x4c00
ax_pose_terminator
sStaryuPose85:
ax_pose 6, 0x81ec, 0x80f8, 0x4c00
ax_pose_terminator
sStaryuPose86:
ax_pose 7, 0x81ec, 0x80f8, 0x4c00
ax_pose_terminator
sStaryuPose87:
ax_pose 8, 0x81ec, 0x80f8, 0x4c00
ax_pose_terminator
sStaryuPose88:
ax_pose 28, 0x81ec, 0x80f8, 0x4c00
ax_pose_terminator
sStaryuPose89:
ax_pose 3, 0x01ed, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose90:
ax_pose 4, 0x01ee, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose91:
ax_pose 5, 0x01ee, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose92:
ax_pose 27, 0x01ed, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose93:
ax_pose 0, 0x01eb, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose94:
ax_pose 3, 0x01ed, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose95:
ax_pose 6, 0x81ed, 0x80f8, 0x4c00
ax_pose_terminator
sStaryuPose96:
ax_pose 15, 0x01ed, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose97:
ax_pose 12, 0x01eb, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose98:
ax_pose 9, 0x01ed, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose99:
ax_pose 6, 0x81ed, 0x90f9, 0x4c00
ax_pose_terminator
sStaryuPose100:
ax_pose 3, 0x01ed, 0x90ed, 0x4c00
ax_pose_terminator
sStaryuPose101:
ax_pose 32, 0x01f1, 0x80f5, 0x4c00
ax_pose_terminator
sStaryuPose102:
ax_pose 33, 0x01f1, 0x80f5, 0x4c00
ax_pose_terminator
sStaryuPose103:
ax_pose 34, 0x01e3, 0x80f0, 0x4c00
ax_pose_terminator
sStaryuPose104:
ax_pose 35, 0x01e4, 0x80ec, 0x4c00
ax_pose_terminator
sStaryuPose105:
ax_pose 36, 0x01e2, 0x90eb, 0x4c00
ax_pose_terminator
sStaryuPose106:
ax_pose 37, 0x01e6, 0x80f0, 0x4c00
ax_pose_terminator
sStaryuPose107:
ax_pose 38, 0x01e8, 0x80f0, 0x4c00
ax_pose_terminator
sStaryuPose108:
ax_pose 39, 0x01e6, 0x80f8, 0x4c00
ax_pose_terminator
sStaryuPose109:
ax_pose 36, 0x01e3, 0x80f5, 0x4c00
ax_pose_terminator
sStaryuPose110:
ax_pose 40, 0x01e4, 0x80f5, 0x4c00
ax_pose_terminator
sStaryuPose111:
ax_pose 0, 0x01eb, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose112:
ax_pose 26, 0x01eb, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose113:
ax_pose 3, 0x01ed, 0x90ed, 0x4c00
ax_pose_terminator
sStaryuPose114:
ax_pose 27, 0x01ed, 0x90ed, 0x4c00
ax_pose_terminator
sStaryuPose115:
ax_pose 6, 0x81ed, 0x90f9, 0x4c00
ax_pose_terminator
sStaryuPose116:
ax_pose 28, 0x81ed, 0x90f9, 0x4c00
ax_pose_terminator
sStaryuPose117:
ax_pose 9, 0x01ed, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose118:
ax_pose 29, 0x81ed, 0x80f9, 0x4c00
ax_pose_terminator
sStaryuPose119:
ax_pose 12, 0x01eb, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose120:
ax_pose 30, 0x01eb, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose121:
ax_pose 15, 0x01ed, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose122:
ax_pose 31, 0x81ed, 0x80f8, 0x4c00
ax_pose_terminator
sStaryuPose123:
ax_pose 6, 0x81ed, 0x80f8, 0x4c00
ax_pose_terminator
sStaryuPose124:
ax_pose 28, 0x81ed, 0x80f8, 0x4c00
ax_pose_terminator
sStaryuPose125:
ax_pose 3, 0x01ed, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose126:
ax_pose 27, 0x01ed, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose127:
ax_pose 26, 0x01eb, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose128:
ax_pose 27, 0x01ed, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose129:
ax_pose 28, 0x81ec, 0x80f8, 0x4c00
ax_pose_terminator
sStaryuPose130:
ax_pose 31, 0x81ed, 0x80f8, 0x4c00
ax_pose_terminator
sStaryuPose131:
ax_pose 30, 0x01eb, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose132:
ax_pose 29, 0x81ed, 0x80f8, 0x4c00
ax_pose_terminator
sStaryuPose133:
ax_pose 28, 0x81ec, 0x90f8, 0x4c00
ax_pose_terminator
sStaryuPose134:
ax_pose 27, 0x01ed, 0x90ec, 0x4c00
ax_pose_terminator
sStaryuPose135:
ax_pose 26, 0x01eb, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose136:
ax_pose 27, 0x01ed, 0x90ec, 0x4c00
ax_pose_terminator
sStaryuPose137:
ax_pose 28, 0x81ec, 0x90f8, 0x4c00
ax_pose_terminator
sStaryuPose138:
ax_pose 29, 0x81ed, 0x80f8, 0x4c00
ax_pose_terminator
sStaryuPose139:
ax_pose 30, 0x01eb, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose140:
ax_pose 31, 0x81ed, 0x80f8, 0x4c00
ax_pose_terminator
sStaryuPose141:
ax_pose 28, 0x81ec, 0x80f8, 0x4c00
ax_pose_terminator
sStaryuPose142:
ax_pose 27, 0x01ed, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose143:
ax_pose 0, 0x01eb, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose144:
ax_pose 18, 0x01eb, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose145:
ax_pose 26, 0x01eb, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose146:
ax_pose 3, 0x01ed, 0x90ed, 0x4c00
ax_pose_terminator
sStaryuPose147:
ax_pose 21, 0x01ea, 0x90ed, 0x4c00
ax_pose_terminator
sStaryuPose148:
ax_pose 27, 0x01ed, 0x90ed, 0x4c00
ax_pose_terminator
sStaryuPose149:
ax_pose 6, 0x81ed, 0x90f9, 0x4c00
ax_pose_terminator
sStaryuPose150:
ax_pose 22, 0x01ed, 0x90eb, 0x4c00
ax_pose_terminator
sStaryuPose151:
ax_pose 28, 0x81ed, 0x90f9, 0x4c00
ax_pose_terminator
sStaryuPose152:
ax_pose 9, 0x01ed, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose153:
ax_pose 23, 0x01f3, 0x40f7, 0x4c00
ax_pose_terminator
sStaryuPose154:
ax_pose 29, 0x81ee, 0x80f9, 0x4c00
ax_pose_terminator
sStaryuPose155:
ax_pose 12, 0x01eb, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose156:
ax_pose 24, 0x41f3, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose157:
ax_pose 30, 0x01eb, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose158:
ax_pose 15, 0x01ed, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose159:
ax_pose 25, 0x01f3, 0x40f9, 0x4c00
ax_pose_terminator
sStaryuPose160:
ax_pose 31, 0x81ee, 0x80f8, 0x4c00
ax_pose_terminator
sStaryuPose161:
ax_pose 6, 0x81ed, 0x80f8, 0x4c00
ax_pose_terminator
sStaryuPose162:
ax_pose 22, 0x01ed, 0x80f6, 0x4c00
ax_pose_terminator
sStaryuPose163:
ax_pose 28, 0x81ed, 0x80f8, 0x4c00
ax_pose_terminator
sStaryuPose164:
ax_pose 3, 0x01ed, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose165:
ax_pose 21, 0x01ea, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose166:
ax_pose 27, 0x01ed, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose167:
ax_pose 26, 0x01eb, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose168:
ax_pose 27, 0x01ed, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose169:
ax_pose 28, 0x81ec, 0x80f8, 0x4c00
ax_pose_terminator
sStaryuPose170:
ax_pose 31, 0x81ed, 0x80f8, 0x4c00
ax_pose_terminator
sStaryuPose171:
ax_pose 30, 0x01eb, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose172:
ax_pose 29, 0x81ed, 0x80f8, 0x4c00
ax_pose_terminator
sStaryuPose173:
ax_pose 28, 0x81ec, 0x90f8, 0x4c00
ax_pose_terminator
sStaryuPose174:
ax_pose 27, 0x01ed, 0x90ec, 0x4c00
ax_pose_terminator
sStaryuPose175:
ax_pose 0, 0x01eb, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose176:
ax_pose 3, 0x01ed, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose177:
ax_pose 6, 0x81ed, 0x80f8, 0x4c00
ax_pose_terminator
sStaryuPose178:
ax_pose 15, 0x01ed, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose179:
ax_pose 12, 0x01eb, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose180:
ax_pose 9, 0x01ed, 0x80f4, 0x4c00
ax_pose_terminator
sStaryuPose181:
ax_pose 6, 0x81ed, 0x90f9, 0x4c00
ax_pose_terminator
sStaryuPose182:
ax_pose 3, 0x01ed, 0x90ed, 0x4c00
ax_pose_terminator
.align 2
sStaryuAnims_1_1:
ax_anim 8, 0, 0, 0, 0, 0, 0,
ax_anim 10, 0, 1, 0, 0, 0, 0,
ax_anim 8, 0, 0, 0, 0, 0, 0,
ax_anim 10, 0, 2, 0, 0, 0, 0,
ax_anim_terminator
sStaryuAnims_1_2:
ax_anim 8, 0, 3, 0, 0, 0, 0,
ax_anim 10, 0, 4, 0, 0, 0, 0,
ax_anim 8, 0, 3, 0, 0, 0, 0,
ax_anim 10, 0, 5, 0, 0, 0, 0,
ax_anim_terminator
sStaryuAnims_1_3:
ax_anim 8, 0, 6, 0, 0, 0, 0,
ax_anim 10, 0, 7, 0, 0, 0, 0,
ax_anim 8, 0, 6, 0, 0, 0, 0,
ax_anim 10, 0, 8, 0, 0, 0, 0,
ax_anim_terminator
sStaryuAnims_1_4:
ax_anim 8, 0, 9, 0, 0, 0, 0,
ax_anim 10, 0, 10, 0, 0, 0, 0,
ax_anim 8, 0, 9, 0, 0, 0, 0,
ax_anim 10, 0, 11, 0, 0, 0, 0,
ax_anim_terminator
sStaryuAnims_1_5:
ax_anim 8, 0, 12, 0, 0, 0, 0,
ax_anim 10, 0, 13, 0, 0, 0, 0,
ax_anim 8, 0, 12, 0, 0, 0, 0,
ax_anim 10, 0, 14, 0, 0, 0, 0,
ax_anim_terminator
sStaryuAnims_1_6:
ax_anim 8, 0, 15, 0, 0, 0, 0,
ax_anim 10, 0, 16, 0, 0, 0, 0,
ax_anim 8, 0, 15, 0, 0, 0, 0,
ax_anim 10, 0, 17, 0, 0, 0, 0,
ax_anim_terminator
sStaryuAnims_1_7:
ax_anim 8, 0, 18, 0, 0, 0, 0,
ax_anim 10, 0, 19, 0, 0, 0, 0,
ax_anim 8, 0, 18, 0, 0, 0, 0,
ax_anim 10, 0, 20, 0, 0, 0, 0,
ax_anim_terminator
sStaryuAnims_1_8:
ax_anim 8, 0, 21, 0, 0, 0, 0,
ax_anim 10, 0, 22, 0, 0, 0, 0,
ax_anim 8, 0, 21, 0, 0, 0, 0,
ax_anim 10, 0, 23, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sStaryuAnims_2_1:
ax_anim 2, 0, 25, 0, 0, 0, 0,
ax_anim 2, 0, 25, 0, -3, 0, -3,
ax_anim 4, 0, 26, 0, -5, 0, -5,
ax_anim 2, 0, 27, 0, -5, 0, -5,
ax_anim 2, 2, 26, 0, -5, 0, -5,
ax_anim 1, 0, 27, 0, 2, 0, 2,
ax_anim 1, 0, 26, 0, 10, 0, 10,
ax_anim 1, 0, 27, 0, 19, 0, 19,
ax_anim 2, 1, 26, 0, 19, 0, 19,
ax_anim 2, 0, 27, 0, 19, 0, 19,
ax_anim 2, 0, 26, 0, 19, 0, 19,
ax_anim 2, 0, 27, 0, 19, 0, 19,
ax_anim 2, 0, 26, 0, 19, 0, 19,
ax_anim 2, 0, 27, 0, 12, 0, 12,
ax_anim 2, 0, 24, 0, 4, 0, 4,
ax_anim_terminator
sStaryuAnims_2_2:
ax_anim 2, 0, 29, 0, 0, 0, 0,
ax_anim 2, 0, 29, -3, -3, -3, -3,
ax_anim 4, 0, 26, -5, -5, -5, -5,
ax_anim 2, 0, 27, -5, -5, -5, -5,
ax_anim 2, 2, 26, -5, -5, -5, -5,
ax_anim 1, 0, 27, 2, 2, 2, 2,
ax_anim 1, 0, 26, 10, 10, 10, 10,
ax_anim 1, 0, 27, 20, 19, 20, 19,
ax_anim 2, 1, 26, 20, 19, 20, 19,
ax_anim 2, 0, 27, 20, 19, 20, 19,
ax_anim 2, 0, 26, 20, 19, 20, 19,
ax_anim 2, 0, 27, 20, 19, 20, 19,
ax_anim 2, 0, 26, 20, 19, 20, 19,
ax_anim 2, 0, 27, 12, 12, 12, 12,
ax_anim 2, 0, 28, 4, 4, 4, 4,
ax_anim_terminator
sStaryuAnims_2_3:
ax_anim 2, 0, 31, 0, 0, 0, 0,
ax_anim 2, 0, 31, -3, 0, -3, 0,
ax_anim 4, 0, 26, -5, 0, -5, 0,
ax_anim 2, 0, 27, -5, 0, -5, 0,
ax_anim 2, 2, 26, -5, 0, -5, 0,
ax_anim 1, 0, 27, 2, 0, 2, 0,
ax_anim 1, 0, 26, 10, 0, 10, 0,
ax_anim 1, 0, 27, 20, 0, 20, 0,
ax_anim 2, 1, 26, 20, 0, 20, 0,
ax_anim 2, 0, 27, 20, 0, 20, 0,
ax_anim 2, 0, 26, 20, 0, 20, 0,
ax_anim 2, 0, 27, 20, 0, 20, 0,
ax_anim 2, 0, 26, 20, 0, 20, 0,
ax_anim 2, 0, 27, 12, 0, 12, 0,
ax_anim 2, 0, 30, 4, 0, 4, 0,
ax_anim_terminator
sStaryuAnims_2_4:
ax_anim 2, 0, 33, 0, 0, 0, 0,
ax_anim 2, 0, 33, -3, 3, -3, 3,
ax_anim 4, 0, 26, -5, 5, -5, 5,
ax_anim 2, 0, 27, -5, 5, -5, 5,
ax_anim 2, 2, 26, -5, 5, -5, 5,
ax_anim 1, 0, 27, 2, -2, 2, -2,
ax_anim 1, 0, 26, 10, -10, 10, -10,
ax_anim 1, 0, 27, 20, -19, 20, -19,
ax_anim 2, 1, 26, 20, -19, 20, -19,
ax_anim 2, 0, 27, 20, -19, 20, -19,
ax_anim 2, 0, 26, 20, -19, 20, -19,
ax_anim 2, 0, 27, 20, -19, 20, -19,
ax_anim 2, 0, 26, 20, -19, 20, -19,
ax_anim 2, 0, 27, 12, -12, 12, -12,
ax_anim 2, 0, 32, 4, -4, 4, -4,
ax_anim_terminator
sStaryuAnims_2_5:
ax_anim 2, 0, 35, 0, 0, 0, 0,
ax_anim 2, 0, 35, 0, 3, 0, 3,
ax_anim 4, 0, 26, 0, 5, 0, 5,
ax_anim 2, 0, 27, 0, 5, 0, 5,
ax_anim 2, 2, 26, 0, 5, 0, 5,
ax_anim 1, 0, 27, 0, -2, 0, -2,
ax_anim 1, 0, 26, 0, -10, 0, -10,
ax_anim 1, 0, 27, 0, -19, 0, -19,
ax_anim 2, 1, 26, 0, -19, 0, -19,
ax_anim 2, 0, 27, 0, -19, 0, -19,
ax_anim 2, 0, 26, 0, -19, 0, -19,
ax_anim 2, 0, 27, 0, -19, 0, -19,
ax_anim 2, 0, 26, 0, -19, 0, -19,
ax_anim 2, 0, 27, 0, -12, 0, -12,
ax_anim 2, 0, 34, 0, -4, 0, -4,
ax_anim_terminator
sStaryuAnims_2_6:
ax_anim 2, 0, 37, 0, 0, 0, 0,
ax_anim 2, 0, 37, 3, 3, 3, 3,
ax_anim 4, 0, 26, 5, 5, 5, 5,
ax_anim 2, 0, 27, 5, 5, 5, 5,
ax_anim 2, 2, 26, 5, 5, 5, 5,
ax_anim 1, 0, 27, -2, -2, -2, -2,
ax_anim 1, 0, 26, -10, -10, -10, -10,
ax_anim 1, 0, 27, -20, -19, -20, -19,
ax_anim 2, 1, 26, -20, -19, -20, -19,
ax_anim 2, 0, 27, -20, -19, -20, -19,
ax_anim 2, 0, 26, -20, -19, -20, -19,
ax_anim 2, 0, 27, -20, -19, -20, -19,
ax_anim 2, 0, 26, -20, -19, -20, -19,
ax_anim 2, 0, 27, -12, -12, -12, -12,
ax_anim 2, 0, 36, -4, -4, -4, -4,
ax_anim_terminator
sStaryuAnims_2_7:
ax_anim 2, 0, 39, 0, 0, 0, 0,
ax_anim 2, 0, 39, 3, 0, 3, 0,
ax_anim 4, 0, 26, 5, 0, 5, 0,
ax_anim 2, 0, 27, 5, 0, 5, 0,
ax_anim 2, 2, 26, 5, 0, 5, 0,
ax_anim 1, 0, 27, -2, 0, -2, 0,
ax_anim 1, 0, 26, -10, 0, -10, 0,
ax_anim 1, 0, 27, -20, 0, -20, 0,
ax_anim 2, 1, 26, -20, 0, -20, 0,
ax_anim 2, 0, 27, -20, 0, -20, 0,
ax_anim 2, 0, 26, -20, 0, -20, 0,
ax_anim 2, 0, 27, -20, 0, -20, 0,
ax_anim 2, 0, 26, -20, 0, -20, 0,
ax_anim 2, 0, 27, -12, 0, -12, 0,
ax_anim 2, 0, 38, -4, 0, -4, 0,
ax_anim_terminator
sStaryuAnims_2_8:
ax_anim 2, 0, 41, 0, 0, 0, 0,
ax_anim 2, 0, 41, 3, -3, 3, -3,
ax_anim 4, 0, 26, 5, -5, 5, -5,
ax_anim 2, 0, 27, 5, -5, 5, -5,
ax_anim 2, 2, 26, 5, -5, 5, -5,
ax_anim 1, 0, 27, -2, 2, -2, 2,
ax_anim 1, 0, 26, -10, 10, -10, 10,
ax_anim 1, 0, 27, -20, 19, -20, 19,
ax_anim 2, 1, 26, -20, 19, -20, 19,
ax_anim 2, 0, 27, -20, 19, -20, 19,
ax_anim 2, 0, 26, -20, 19, -20, 19,
ax_anim 2, 0, 27, -20, 19, -20, 19,
ax_anim 2, 0, 26, -20, 19, -20, 19,
ax_anim 2, 0, 27, -12, 12, -12, 12,
ax_anim 2, 0, 40, -4, 4, -4, 4,
ax_anim_terminator
.align 2
sStaryuAnims_3_1:
ax_anim 2, 0, 43, 0, 0, 0, 0,
ax_anim 2, 0, 43, 0, -3, 0, -3,
ax_anim 4, 0, 44, 0, -5, 0, -5,
ax_anim 2, 0, 45, 0, -5, 0, -5,
ax_anim 2, 2, 44, 0, -5, 0, -5,
ax_anim 1, 0, 45, 0, 2, 0, 2,
ax_anim 1, 0, 44, 0, 10, 0, 10,
ax_anim 1, 0, 45, 0, 19, 0, 19,
ax_anim 2, 1, 44, 0, 19, 0, 19,
ax_anim 2, 0, 45, 0, 19, 0, 19,
ax_anim 2, 0, 44, 0, 19, 0, 19,
ax_anim 2, 0, 45, 0, 19, 0, 19,
ax_anim 2, 0, 44, 0, 19, 0, 19,
ax_anim 2, 0, 45, 0, 12, 0, 12,
ax_anim 2, 0, 42, 0, 4, 0, 4,
ax_anim_terminator
sStaryuAnims_3_2:
ax_anim 2, 0, 47, 0, 0, 0, 0,
ax_anim 2, 0, 47, -3, -3, -3, -3,
ax_anim 4, 0, 44, -5, -5, -5, -5,
ax_anim 2, 0, 45, -5, -5, -5, -5,
ax_anim 2, 2, 44, -5, -5, -5, -5,
ax_anim 1, 0, 45, 2, 2, 2, 2,
ax_anim 1, 0, 44, 10, 10, 10, 10,
ax_anim 1, 0, 45, 20, 19, 20, 19,
ax_anim 2, 1, 44, 20, 19, 20, 19,
ax_anim 2, 0, 45, 20, 19, 20, 19,
ax_anim 2, 0, 44, 20, 19, 20, 19,
ax_anim 2, 0, 45, 20, 19, 20, 19,
ax_anim 2, 0, 44, 20, 19, 20, 19,
ax_anim 2, 0, 45, 12, 12, 12, 12,
ax_anim 2, 0, 46, 4, 4, 4, 4,
ax_anim_terminator
sStaryuAnims_3_3:
ax_anim 2, 0, 49, 0, 0, 0, 0,
ax_anim 2, 0, 49, -3, 0, -3, 0,
ax_anim 4, 0, 44, -5, 0, -5, 0,
ax_anim 2, 0, 45, -5, 0, -5, 0,
ax_anim 2, 2, 44, -5, 0, -5, 0,
ax_anim 1, 0, 45, 2, 0, 2, 0,
ax_anim 1, 0, 44, 10, 0, 10, 0,
ax_anim 1, 0, 45, 20, 0, 20, 0,
ax_anim 2, 1, 44, 20, 0, 20, 0,
ax_anim 2, 0, 45, 20, 0, 20, 0,
ax_anim 2, 0, 44, 20, 0, 20, 0,
ax_anim 2, 0, 45, 20, 0, 20, 0,
ax_anim 2, 0, 44, 20, 0, 20, 0,
ax_anim 2, 0, 45, 12, 0, 12, 0,
ax_anim 2, 0, 48, 4, 0, 4, 0,
ax_anim_terminator
sStaryuAnims_3_4:
ax_anim 2, 0, 51, 0, 0, 0, 0,
ax_anim 2, 0, 51, -3, 3, -3, 3,
ax_anim 4, 0, 44, -5, 5, -5, 5,
ax_anim 2, 0, 45, -5, 5, -5, 5,
ax_anim 2, 2, 44, -5, 5, -5, 5,
ax_anim 1, 0, 45, 2, -2, 2, -2,
ax_anim 1, 0, 44, 10, -10, 10, -10,
ax_anim 1, 0, 45, 20, -19, 20, -19,
ax_anim 2, 1, 44, 20, -19, 20, -19,
ax_anim 2, 0, 45, 20, -19, 20, -19,
ax_anim 2, 0, 44, 20, -19, 20, -19,
ax_anim 2, 0, 45, 20, -19, 20, -19,
ax_anim 2, 0, 44, 20, -19, 20, -19,
ax_anim 2, 0, 45, 12, -12, 12, -12,
ax_anim 2, 0, 50, 4, -4, 4, -4,
ax_anim_terminator
sStaryuAnims_3_5:
ax_anim 2, 0, 53, 0, 0, 0, 0,
ax_anim 2, 0, 53, 0, 3, 0, 3,
ax_anim 4, 0, 44, 0, 5, 0, 5,
ax_anim 2, 0, 45, 0, 5, 0, 5,
ax_anim 2, 2, 44, 0, 5, 0, 5,
ax_anim 1, 0, 45, 0, -2, 0, -2,
ax_anim 1, 0, 44, 0, -10, 0, -10,
ax_anim 1, 0, 45, 0, -19, 0, -19,
ax_anim 2, 1, 44, 0, -19, 0, -19,
ax_anim 2, 0, 45, 0, -19, 0, -19,
ax_anim 2, 0, 44, 0, -19, 0, -19,
ax_anim 2, 0, 45, 0, -19, 0, -19,
ax_anim 2, 0, 44, 0, -19, 0, -19,
ax_anim 2, 0, 45, 0, -12, 0, -12,
ax_anim 2, 0, 52, 0, -4, 0, -4,
ax_anim_terminator
sStaryuAnims_3_6:
ax_anim 2, 0, 55, 0, 0, 0, 0,
ax_anim 2, 0, 55, 3, 3, 3, 3,
ax_anim 4, 0, 44, 5, 5, 5, 5,
ax_anim 2, 0, 45, 5, 5, 5, 5,
ax_anim 2, 2, 44, 5, 5, 5, 5,
ax_anim 1, 0, 45, -2, -2, -2, -2,
ax_anim 1, 0, 44, -10, -10, -10, -10,
ax_anim 1, 0, 45, -20, -19, -20, -19,
ax_anim 2, 1, 44, -20, -19, -20, -19,
ax_anim 2, 0, 45, -20, -19, -20, -19,
ax_anim 2, 0, 44, -20, -19, -20, -19,
ax_anim 2, 0, 45, -20, -19, -20, -19,
ax_anim 2, 0, 44, -20, -19, -20, -19,
ax_anim 2, 0, 45, -12, -12, -12, -12,
ax_anim 2, 0, 54, -4, -4, -4, -4,
ax_anim_terminator
sStaryuAnims_3_7:
ax_anim 2, 0, 57, 0, 0, 0, 0,
ax_anim 2, 0, 57, 3, 0, 3, 0,
ax_anim 4, 0, 44, 5, 0, 5, 0,
ax_anim 2, 0, 45, 5, 0, 5, 0,
ax_anim 2, 2, 44, 5, 0, 5, 0,
ax_anim 1, 0, 45, -2, 0, -2, 0,
ax_anim 1, 0, 44, -10, 0, -10, 0,
ax_anim 1, 0, 45, -20, 0, -20, 0,
ax_anim 2, 1, 44, -20, 0, -20, 0,
ax_anim 2, 0, 45, -20, 0, -20, 0,
ax_anim 2, 0, 44, -20, 0, -20, 0,
ax_anim 2, 0, 45, -20, 0, -20, 0,
ax_anim 2, 0, 44, -20, 0, -20, 0,
ax_anim 2, 0, 45, -12, 0, -12, 0,
ax_anim 2, 0, 56, -4, 0, -4, 0,
ax_anim_terminator
sStaryuAnims_3_8:
ax_anim 2, 0, 59, 0, 0, 0, 0,
ax_anim 2, 0, 59, 3, -3, 3, -3,
ax_anim 4, 0, 44, 5, -5, 5, -5,
ax_anim 2, 0, 45, 5, -5, 5, -5,
ax_anim 2, 2, 44, 5, -5, 5, -5,
ax_anim 1, 0, 45, -2, 2, -2, 2,
ax_anim 1, 0, 44, -10, 10, -10, 10,
ax_anim 1, 0, 45, -20, 19, -20, 19,
ax_anim 2, 1, 44, -20, 19, -20, 19,
ax_anim 2, 0, 45, -20, 19, -20, 19,
ax_anim 2, 0, 44, -20, 19, -20, 19,
ax_anim 2, 0, 45, -20, 19, -20, 19,
ax_anim 2, 0, 44, -20, 19, -20, 19,
ax_anim 2, 0, 45, -12, 12, -12, 12,
ax_anim 2, 0, 58, -4, 4, -4, 4,
ax_anim_terminator
.align 2
sStaryuAnims_4_1:
ax_anim 4, 0, 60, 0, 0, 0, 0,
ax_anim 8, 2, 63, 0, 0, 0, 0,
ax_anim 1, 1, 60, 0, -3, 0, -3,
ax_anim 1, 0, 60, 0, -5, 0, -5,
ax_anim 1, 0, 60, 0, -6, 0, -6,
ax_anim 4, 0, 60, 0, -7, 0, -7,
ax_anim 2, 0, 61, 0, -7, 0, -7,
ax_anim 2, 0, 60, 0, -4, 0, -4,
ax_anim 2, 0, 62, 0, -4, 0, -3,
ax_anim_terminator
sStaryuAnims_4_2:
ax_anim 4, 0, 64, 0, 0, 0, 0,
ax_anim 8, 2, 67, 0, 0, 0, 0,
ax_anim 1, 1, 64, -3, -3, -3, -3,
ax_anim 1, 0, 64, -5, -5, -5, -5,
ax_anim 1, 0, 64, -6, -6, -6, -6,
ax_anim 4, 0, 64, -7, -7, -7, -7,
ax_anim 2, 0, 65, -7, -6, -7, -6,
ax_anim 2, 0, 64, -4, -4, -4, -4,
ax_anim 2, 0, 66, -3, -3, -3, -3,
ax_anim_terminator
sStaryuAnims_4_3:
ax_anim 4, 0, 68, 0, 0, 0, 0,
ax_anim 8, 2, 71, 0, 0, 0, 0,
ax_anim 1, 1, 68, -3, 0, -3, 0,
ax_anim 1, 0, 68, -5, 0, -5, 0,
ax_anim 1, 0, 68, -6, 0, -6, 0,
ax_anim 4, 0, 68, -7, 0, -7, 0,
ax_anim 2, 0, 69, -4, 0, -4, 0,
ax_anim 2, 0, 68, -2, 0, -2, 0,
ax_anim 2, 0, 70, -1, 0, -1, 0,
ax_anim_terminator
sStaryuAnims_4_4:
ax_anim 4, 0, 72, 0, 0, 0, 0,
ax_anim 8, 2, 75, 0, 0, 0, 0,
ax_anim 1, 1, 72, -3, 3, -3, 3,
ax_anim 1, 0, 72, -5, 5, -5, 5,
ax_anim 1, 0, 72, -6, 6, -6, 6,
ax_anim 4, 0, 72, -7, 7, -7, 7,
ax_anim 2, 0, 73, -5, 5, -5, 5,
ax_anim 2, 0, 72, -4, 4, -4, 4,
ax_anim 2, 0, 74, -1, 1, -1, 1,
ax_anim_terminator
sStaryuAnims_4_5:
ax_anim 4, 0, 76, 0, 0, 0, 0,
ax_anim 8, 2, 79, 0, 0, 0, 0,
ax_anim 1, 1, 76, 0, 3, 0, 3,
ax_anim 1, 0, 76, 0, 5, 0, 5,
ax_anim 1, 0, 76, 0, 6, 0, 6,
ax_anim 4, 0, 76, 0, 7, 0, 7,
ax_anim 2, 0, 77, 0, 4, 0, 4,
ax_anim 2, 0, 76, 0, 3, 0, 3,
ax_anim 2, 0, 78, 0, 1, 0, 1,
ax_anim_terminator
sStaryuAnims_4_6:
ax_anim 4, 0, 80, 0, 0, 0, 0,
ax_anim 8, 2, 83, 0, 0, 0, 0,
ax_anim 1, 1, 80, 3, 3, 3, 3,
ax_anim 1, 0, 80, 5, 5, 5, 5,
ax_anim 1, 0, 80, 6, 6, 6, 6,
ax_anim 4, 0, 80, 7, 7, 7, 7,
ax_anim 2, 0, 81, 5, 5, 5, 5,
ax_anim 2, 0, 80, 4, 4, 4, 4,
ax_anim 2, 0, 82, 1, 1, 1, 1,
ax_anim_terminator
sStaryuAnims_4_7:
ax_anim 4, 0, 84, 0, 0, 0, 0,
ax_anim 8, 2, 87, 0, 0, 0, 0,
ax_anim 1, 1, 84, 3, 0, 3, 0,
ax_anim 1, 0, 84, 5, 0, 5, 0,
ax_anim 1, 0, 84, 6, 0, 6, 0,
ax_anim 4, 0, 84, 7, 0, 7, 0,
ax_anim 2, 0, 85, 4, 0, 4, 0,
ax_anim 2, 0, 84, 2, 0, 2, 0,
ax_anim 2, 0, 86, 1, 0, 1, 0,
ax_anim_terminator
sStaryuAnims_4_8:
ax_anim 4, 0, 88, 0, 0, 0, 0,
ax_anim 8, 2, 91, 0, 0, 0, 0,
ax_anim 1, 1, 88, 3, -3, 3, -3,
ax_anim 1, 0, 88, 5, -5, 5, -5,
ax_anim 1, 0, 88, 6, -6, 6, -6,
ax_anim 4, 0, 88, 7, -7, 7, -7,
ax_anim 2, 0, 89, 7, -6, 7, -6,
ax_anim 2, 0, 88, 4, -4, 4, -4,
ax_anim 2, 0, 90, 3, -3, 3, -3,
ax_anim_terminator
.align 2
sStaryuAnims_5_1:
ax_anim 2, 0, 92, 0, 0, 0, 0,
ax_anim 2, 0, 93, 0, 0, 0, 0,
ax_anim 2, 0, 94, 0, 0, 0, 0,
ax_anim 2, 0, 95, 0, 0, 0, 0,
ax_anim 2, 0, 96, 0, 0, 0, 0,
ax_anim 2, 0, 97, 0, 0, 0, 0,
ax_anim 2, 0, 98, 0, 0, 0, 0,
ax_anim 2, 0, 99, 0, 0, 0, 0,
ax_anim 2, 2, 92, 0, 0, 0, 0,
ax_anim_terminator
sStaryuAnims_5_2:
ax_anim 2, 0, 99, 0, 0, 0, 0,
ax_anim 2, 0, 92, 0, 0, 0, 0,
ax_anim 2, 0, 93, 0, 0, 0, 0,
ax_anim 2, 0, 94, 0, 0, 0, 0,
ax_anim 2, 0, 95, 0, 0, 0, 0,
ax_anim 2, 0, 96, 0, 0, 0, 0,
ax_anim 2, 0, 97, 0, 0, 0, 0,
ax_anim 2, 0, 98, 0, 0, 0, 0,
ax_anim 2, 2, 99, 0, 0, 0, 0,
ax_anim_terminator
sStaryuAnims_5_3:
ax_anim 2, 0, 98, 0, 0, 0, 0,
ax_anim 2, 0, 99, 0, 0, 0, 0,
ax_anim 2, 0, 92, 0, 0, 0, 0,
ax_anim 2, 0, 93, 0, 0, 0, 0,
ax_anim 2, 0, 94, 0, 0, 0, 0,
ax_anim 2, 0, 95, 0, 0, 0, 0,
ax_anim 2, 0, 96, 0, 0, 0, 0,
ax_anim 2, 0, 97, 0, 0, 0, 0,
ax_anim 2, 2, 98, 0, 0, 0, 0,
ax_anim_terminator
sStaryuAnims_5_4:
ax_anim 2, 0, 97, 0, 0, 0, 0,
ax_anim 2, 0, 98, 0, 0, 0, 0,
ax_anim 2, 0, 99, 0, 0, 0, 0,
ax_anim 2, 0, 92, 0, 0, 0, 0,
ax_anim 2, 0, 93, 0, 0, 0, 0,
ax_anim 2, 0, 94, 0, 0, 0, 0,
ax_anim 2, 0, 95, 0, 0, 0, 0,
ax_anim 2, 0, 96, 0, 0, 0, 0,
ax_anim 2, 2, 97, 0, 0, 0, 0,
ax_anim_terminator
sStaryuAnims_5_5:
ax_anim 2, 0, 96, 0, 0, 0, 0,
ax_anim 2, 0, 97, 0, 0, 0, 0,
ax_anim 2, 0, 98, 0, 0, 0, 0,
ax_anim 2, 0, 99, 0, 0, 0, 0,
ax_anim 2, 0, 92, 0, 0, 0, 0,
ax_anim 2, 0, 93, 0, 0, 0, 0,
ax_anim 2, 0, 94, 0, 0, 0, 0,
ax_anim 2, 0, 95, 0, 0, 0, 0,
ax_anim 2, 2, 96, 0, 0, 0, 0,
ax_anim_terminator
sStaryuAnims_5_6:
ax_anim 2, 0, 95, 0, 0, 0, 0,
ax_anim 2, 0, 96, 0, 0, 0, 0,
ax_anim 2, 0, 97, 0, 0, 0, 0,
ax_anim 2, 0, 98, 0, 0, 0, 0,
ax_anim 2, 0, 99, 0, 0, 0, 0,
ax_anim 2, 0, 92, 0, 0, 0, 0,
ax_anim 2, 0, 93, 0, 0, 0, 0,
ax_anim 2, 0, 94, 0, 0, 0, 0,
ax_anim 2, 2, 95, 0, 0, 0, 0,
ax_anim_terminator
sStaryuAnims_5_7:
ax_anim 2, 0, 94, 0, 0, 0, 0,
ax_anim 2, 0, 95, 0, 0, 0, 0,
ax_anim 2, 0, 96, 0, 0, 0, 0,
ax_anim 2, 0, 97, 0, 0, 0, 0,
ax_anim 2, 0, 98, 0, 0, 0, 0,
ax_anim 2, 0, 99, 0, 0, 0, 0,
ax_anim 2, 0, 92, 0, 0, 0, 0,
ax_anim 2, 0, 93, 0, 0, 0, 0,
ax_anim 2, 2, 94, 0, 0, 0, 0,
ax_anim_terminator
sStaryuAnims_5_8:
ax_anim 2, 0, 93, 0, 0, 0, 0,
ax_anim 2, 0, 94, 0, 0, 0, 0,
ax_anim 2, 0, 95, 0, 0, 0, 0,
ax_anim 2, 0, 96, 0, 0, 0, 0,
ax_anim 2, 0, 97, 0, 0, 0, 0,
ax_anim 2, 0, 98, 0, 0, 0, 0,
ax_anim 2, 0, 99, 0, 0, 0, 0,
ax_anim 2, 0, 92, 0, 0, 0, 0,
ax_anim 2, 2, 93, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sStaryuAnims_6_1:
ax_anim 30, 0, 100, 0, 0, 0, 0,
ax_anim 35, 0, 101, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sStaryuAnims_7_1:
ax_anim 2, 0, 102, 0, -2, 0, -2,
ax_anim 8, 0, 102, 0, -3, 0, -3,
ax_anim_terminator
sStaryuAnims_7_2:
ax_anim 2, 0, 103, -2, -2, -2, -2,
ax_anim 8, 0, 103, -3, -3, -3, -3,
ax_anim_terminator
sStaryuAnims_7_3:
ax_anim 2, 0, 104, -2, 0, -2, 0,
ax_anim 8, 0, 104, -3, 0, -3, 0,
ax_anim_terminator
sStaryuAnims_7_4:
ax_anim 2, 0, 105, -2, 2, -2, 2,
ax_anim 8, 0, 105, -3, 3, -3, 3,
ax_anim_terminator
sStaryuAnims_7_5:
ax_anim 2, 0, 106, 0, 2, 0, 2,
ax_anim 8, 0, 106, 0, 3, 0, 3,
ax_anim_terminator
sStaryuAnims_7_6:
ax_anim 2, 0, 107, 2, 2, 2, 2,
ax_anim 8, 0, 107, 3, 3, 3, 3,
ax_anim_terminator
sStaryuAnims_7_7:
ax_anim 2, 0, 108, 2, 0, 2, 0,
ax_anim 8, 0, 108, 3, 0, 3, 0,
ax_anim_terminator
sStaryuAnims_7_8:
ax_anim 2, 0, 109, 2, -2, 2, -2,
ax_anim 8, 0, 109, 3, -3, 3, -3,
ax_anim_terminator
.align 2
sStaryuAnims_8_1:
ax_anim 36, 0, 110, 0, 0, 0, 0,
ax_anim 10, 0, 111, 0, 0, 0, 0,
ax_anim 6, 0, 110, 0, 0, 0, 0,
ax_anim 10, 0, 111, 0, 0, 0, 0,
ax_anim_terminator
sStaryuAnims_8_2:
ax_anim 36, 0, 112, 0, 0, 0, 0,
ax_anim 10, 0, 113, 0, 0, 0, 0,
ax_anim 6, 0, 112, 0, 0, 0, 0,
ax_anim 10, 0, 113, 0, 0, 0, 0,
ax_anim_terminator
sStaryuAnims_8_3:
ax_anim 36, 0, 114, 0, 0, 0, 0,
ax_anim 10, 0, 115, 0, 0, 0, 0,
ax_anim 6, 0, 114, 0, 0, 0, 0,
ax_anim 10, 0, 115, 0, 0, 0, 0,
ax_anim_terminator
sStaryuAnims_8_4:
ax_anim 36, 0, 116, 0, 0, 0, 0,
ax_anim 10, 0, 117, 0, 0, 0, 0,
ax_anim 6, 0, 116, 0, 0, 0, 0,
ax_anim 10, 0, 117, 0, 0, 0, 0,
ax_anim_terminator
sStaryuAnims_8_5:
ax_anim 36, 0, 118, 0, 0, 0, 0,
ax_anim 10, 0, 119, 0, 0, 0, 0,
ax_anim 6, 0, 118, 0, 0, 0, 0,
ax_anim 10, 0, 119, 0, 0, 0, 0,
ax_anim_terminator
sStaryuAnims_8_6:
ax_anim 36, 0, 120, 0, 0, 0, 0,
ax_anim 10, 0, 121, 0, 0, 0, 0,
ax_anim 6, 0, 120, 0, 0, 0, 0,
ax_anim 10, 0, 121, 0, 0, 0, 0,
ax_anim_terminator
sStaryuAnims_8_7:
ax_anim 36, 0, 122, 0, 0, 0, 0,
ax_anim 10, 0, 123, 0, 0, 0, 0,
ax_anim 6, 0, 122, 0, 0, 0, 0,
ax_anim 10, 0, 123, 0, 0, 0, 0,
ax_anim_terminator
sStaryuAnims_8_8:
ax_anim 36, 0, 124, 0, 0, 0, 0,
ax_anim 10, 0, 125, 0, 0, 0, 0,
ax_anim 6, 0, 124, 0, 0, 0, 0,
ax_anim 10, 0, 125, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sStaryuAnims_9_1:
ax_anim 2, 0, 126, 0, 0, 0, 0,
ax_anim 1, 0, 127, 6, 3, 6, 3,
ax_anim 2, 0, 128, 8, 10, 8, 10,
ax_anim 2, 0, 129, 7, 18, 7, 18,
ax_anim 3, 0, 130, 0, 21, 0, 21,
ax_anim 2, 3, 131, -7, 18, -7, 18,
ax_anim 2, 0, 132, -8, 10, -8, 10,
ax_anim 1, 0, 133, -6, 3, -6, 3,
ax_anim 1, 0, 126, 0, 0, 0, 0,
ax_anim_terminator
sStaryuAnims_9_2:
ax_anim 2, 0, 133, 0, 0, 0, 0,
ax_anim 1, 0, 126, 8, 0, 8, 0,
ax_anim 2, 0, 127, 17, 3, 17, 3,
ax_anim 2, 0, 128, 21, 12, 21, 12,
ax_anim 3, 0, 129, 22, 20, 22, 20,
ax_anim 2, 3, 130, 12, 23, 12, 23,
ax_anim 2, 0, 131, 3, 15, 3, 15,
ax_anim 1, 0, 132, 0, 7, 0, 7,
ax_anim 1, 0, 133, 0, 0, 0, 0,
ax_anim_terminator
sStaryuAnims_9_3:
ax_anim 2, 0, 132, 0, 0, 0, 0,
ax_anim 1, 0, 133, 3, -5, 3, -5,
ax_anim 2, 0, 126, 11, -6, 11, -6,
ax_anim 2, 0, 127, 20, -5, 20, -5,
ax_anim 3, 0, 128, 24, -2, 24, -2,
ax_anim 2, 3, 129, 21, 5, 21, 5,
ax_anim 2, 0, 130, 12, 7, 12, 7,
ax_anim 1, 0, 131, 4, 4, 4, 4,
ax_anim 1, 0, 132, 0, 0, 0, 0,
ax_anim_terminator
sStaryuAnims_9_4:
ax_anim 2, 0, 131, 0, 0, 0, 0,
ax_anim 1, 0, 132, -1, -8, -1, -8,
ax_anim 2, 0, 133, 4, -16, 4, -16,
ax_anim 2, 0, 126, 14, -23, 14, -23,
ax_anim 3, 0, 127, 22, -22, 22, -22,
ax_anim 2, 3, 128, 23, -14, 23, -14,
ax_anim 2, 0, 129, 17, -4, 17, -4,
ax_anim 1, 0, 130, 7, -1, 7, -1,
ax_anim 1, 0, 131, 0, 0, 0, 0,
ax_anim_terminator
sStaryuAnims_9_5:
ax_anim 2, 0, 130, 0, 0, 0, 0,
ax_anim 1, 0, 131, -8, -4, -8, -4,
ax_anim 2, 0, 132, -9, -12, -9, -12,
ax_anim 2, 0, 133, -7, -20, -7, -20,
ax_anim 3, 0, 126, 0, -25, 0, -25,
ax_anim 2, 3, 127, 7, -20, 7, -20,
ax_anim 2, 0, 128, 9, -10, 9, -10,
ax_anim 1, 0, 129, 8, -4, 8, -4,
ax_anim 1, 0, 130, 0, 0, 0, 0,
ax_anim_terminator
sStaryuAnims_9_6:
ax_anim 2, 0, 129, 0, 0, 0, 0,
ax_anim 1, 0, 128, 1, -8, 1, -8,
ax_anim 2, 0, 127, -4, -16, -4, -16,
ax_anim 2, 0, 126, -14, -23, -14, -23,
ax_anim 3, 0, 133, -22, -22, -22, -22,
ax_anim 2, 3, 132, -23, -14, -23, -14,
ax_anim 2, 0, 131, -17, -4, -17, -4,
ax_anim 1, 0, 130, -7, -1, -7, -1,
ax_anim 1, 0, 129, 0, 0, 0, 0,
ax_anim_terminator
sStaryuAnims_9_7:
ax_anim 2, 0, 128, 0, 0, 0, 0,
ax_anim 1, 0, 127, -3, -5, -3, -5,
ax_anim 2, 0, 126, -11, -6, -11, -6,
ax_anim 2, 0, 133, -20, -5, -20, -5,
ax_anim 3, 0, 132, -24, -2, -24, -2,
ax_anim 2, 3, 131, -21, 5, -21, 5,
ax_anim 2, 0, 130, -12, 7, -12, 7,
ax_anim 1, 0, 129, -4, 4, -4, 4,
ax_anim 1, 0, 128, 0, 0, 0, 0,
ax_anim_terminator
sStaryuAnims_9_8:
ax_anim 2, 0, 127, 0, 0, 0, 0,
ax_anim 1, 0, 126, -8, 0, -8, 0,
ax_anim 2, 0, 133, -17, 3, -17, 3,
ax_anim 2, 0, 132, -21, 12, -21, 12,
ax_anim 3, 0, 131, -22, 20, -22, 20,
ax_anim 2, 3, 130, -12, 23, -12, 23,
ax_anim 2, 0, 129, -3, 15, -3, 15,
ax_anim 1, 0, 128, 0, 7, 0, 7,
ax_anim 1, 0, 127, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sStaryuAnims_10_1:
ax_anim 2, 0, 134, 0, 0, 0, 0,
ax_anim 2, 0, 134, 6, 0, 6, 0,
ax_anim 2, 0, 134, -6, 0, -6, 0,
ax_anim 2, 0, 134, 10, 0, 10, 0,
ax_anim 2, 0, 134, -10, 0, -10, 0,
ax_anim 2, 0, 134, 12, 0, 12, 0,
ax_anim 3, 0, 134, -12, 0, -12, 0,
ax_anim 3, 0, 134, 13, 0, 13, 0,
ax_anim 3, 0, 134, -13, 0, -13, 0,
ax_anim 2, 0, 134, 12, 0, 12, 0,
ax_anim 3, 0, 134, -12, 0, -12, 0,
ax_anim 2, 0, 134, 10, 0, 10, 0,
ax_anim 2, 0, 134, -10, 0, -10, 0,
ax_anim 2, 0, 134, 6, 0, 6, 0,
ax_anim 2, 0, 134, -6, 0, -6, 0,
ax_anim 2, 0, 134, 0, 0, 0, 0,
ax_anim_terminator
sStaryuAnims_10_2:
ax_anim 2, 0, 135, 0, 0, 0, 0,
ax_anim 2, 0, 135, 6, -6, 6, -6,
ax_anim 2, 0, 135, -6, 6, -6, 6,
ax_anim 2, 0, 135, 10, -10, 10, -10,
ax_anim 2, 0, 135, -10, 10, -10, 10,
ax_anim 2, 0, 135, 12, -12, 12, -12,
ax_anim 3, 0, 135, -12, 12, -12, 12,
ax_anim 3, 0, 135, 13, -13, 13, -13,
ax_anim 3, 0, 135, -13, 13, -13, 13,
ax_anim 2, 0, 135, 12, -12, 12, -12,
ax_anim 3, 0, 135, -12, 12, -12, 12,
ax_anim 2, 0, 135, 10, -10, 10, -10,
ax_anim 2, 0, 135, -10, 10, -10, 10,
ax_anim 2, 0, 135, 6, -6, 6, -6,
ax_anim 2, 0, 135, -6, 6, -6, 6,
ax_anim 2, 0, 135, 0, 0, 0, 0,
ax_anim_terminator
sStaryuAnims_10_3:
ax_anim 2, 0, 136, 0, 0, 0, 0,
ax_anim 2, 0, 136, 0, -6, 0, -6,
ax_anim 2, 0, 136, 0, 6, 0, 6,
ax_anim 2, 0, 136, 0, -10, 0, -10,
ax_anim 2, 0, 136, 0, 10, 0, 10,
ax_anim 2, 0, 136, 0, -12, 0, -12,
ax_anim 3, 0, 136, 0, 12, 0, 12,
ax_anim 3, 0, 136, 0, -13, 0, -13,
ax_anim 3, 0, 136, 0, 13, 0, 13,
ax_anim 2, 0, 136, 0, -12, 0, -12,
ax_anim 3, 0, 136, 0, 12, 0, 12,
ax_anim 2, 0, 136, 0, -10, 0, -10,
ax_anim 2, 0, 136, 0, 10, 0, 10,
ax_anim 2, 0, 136, 0, -6, 0, -6,
ax_anim 2, 0, 136, 0, 6, 0, 6,
ax_anim 2, 0, 136, 0, 0, 0, 0,
ax_anim_terminator
sStaryuAnims_10_4:
ax_anim 2, 0, 137, 0, 0, 0, 0,
ax_anim 2, 0, 137, -6, -6, -6, -6,
ax_anim 2, 0, 137, 6, 6, 6, 6,
ax_anim 2, 0, 137, -10, -10, -10, -10,
ax_anim 2, 0, 137, 10, 10, 10, 10,
ax_anim 2, 0, 137, -12, -12, -12, -12,
ax_anim 3, 0, 137, 12, 12, 12, 12,
ax_anim 3, 0, 137, -13, -13, -13, -13,
ax_anim 3, 0, 137, 13, 13, 13, 13,
ax_anim 2, 0, 137, -12, -12, -12, -12,
ax_anim 3, 0, 137, 12, 12, 12, 12,
ax_anim 2, 0, 137, -10, -10, -10, -10,
ax_anim 2, 0, 137, 10, 10, 10, 10,
ax_anim 2, 0, 137, -6, -6, -6, -6,
ax_anim 2, 0, 137, 6, 6, 6, 6,
ax_anim 2, 0, 137, 0, 0, 0, 0,
ax_anim_terminator
sStaryuAnims_10_5:
ax_anim 2, 0, 138, 0, 0, 0, 0,
ax_anim 2, 0, 138, 6, 0, 6, 0,
ax_anim 2, 0, 138, -6, 0, -6, 0,
ax_anim 2, 0, 138, 10, 0, 10, 0,
ax_anim 2, 0, 138, -10, 0, -10, 0,
ax_anim 2, 0, 138, 12, 0, 12, 0,
ax_anim 3, 0, 138, -12, 0, -12, 0,
ax_anim 3, 0, 138, 13, 0, 13, 0,
ax_anim 3, 0, 138, -13, 0, -13, 0,
ax_anim 2, 0, 138, 12, 0, 12, 0,
ax_anim 3, 0, 138, -12, 0, -12, 0,
ax_anim 2, 0, 138, 10, 0, 10, 0,
ax_anim 2, 0, 138, -10, 0, -10, 0,
ax_anim 2, 0, 138, 6, 0, 6, 0,
ax_anim 2, 0, 138, -6, 0, -6, 0,
ax_anim 2, 0, 138, 0, 0, 0, 0,
ax_anim_terminator
sStaryuAnims_10_6:
ax_anim 2, 0, 139, 0, 0, 0, 0,
ax_anim 2, 0, 139, 6, -6, 6, -6,
ax_anim 2, 0, 139, -6, 6, -6, 6,
ax_anim 2, 0, 139, 10, -10, 10, -10,
ax_anim 2, 0, 139, -10, 10, -10, 10,
ax_anim 2, 0, 139, 12, -12, 12, -12,
ax_anim 3, 0, 139, -12, 12, -12, 12,
ax_anim 3, 0, 139, 13, -13, 13, -13,
ax_anim 3, 0, 139, -13, 13, -13, 13,
ax_anim 2, 0, 139, 12, -12, 12, -12,
ax_anim 3, 0, 139, -12, 12, -12, 12,
ax_anim 2, 0, 139, 10, -10, 10, -10,
ax_anim 2, 0, 139, -10, 10, -10, 10,
ax_anim 2, 0, 139, 6, -6, 6, -6,
ax_anim 2, 0, 139, -6, 6, -6, 6,
ax_anim 2, 0, 139, 0, 0, 0, 0,
ax_anim_terminator
sStaryuAnims_10_7:
ax_anim 2, 0, 140, 0, 0, 0, 0,
ax_anim 2, 0, 140, 0, -6, 0, -6,
ax_anim 2, 0, 140, 0, 6, 0, 6,
ax_anim 2, 0, 140, 0, -10, 0, -10,
ax_anim 2, 0, 140, 0, 10, 0, 10,
ax_anim 2, 0, 140, 0, -12, 0, -12,
ax_anim 3, 0, 140, 0, 12, 0, 12,
ax_anim 3, 0, 140, 0, -13, 0, -13,
ax_anim 3, 0, 140, 0, 13, 0, 13,
ax_anim 2, 0, 140, 0, -12, 0, -12,
ax_anim 3, 0, 140, 0, 12, 0, 12,
ax_anim 2, 0, 140, 0, -10, 0, -10,
ax_anim 2, 0, 140, 0, 10, 0, 10,
ax_anim 2, 0, 140, 0, -6, 0, -6,
ax_anim 2, 0, 140, 0, 6, 0, 6,
ax_anim 2, 0, 140, 0, 0, 0, 0,
ax_anim_terminator
sStaryuAnims_10_8:
ax_anim 2, 0, 141, 0, 0, 0, 0,
ax_anim 2, 0, 141, -6, -6, -6, -6,
ax_anim 2, 0, 141, 6, 6, 6, 6,
ax_anim 2, 0, 141, -10, -10, -10, -10,
ax_anim 2, 0, 141, 10, 10, 10, 10,
ax_anim 2, 0, 141, -12, -12, -12, -12,
ax_anim 3, 0, 141, 12, 12, 12, 12,
ax_anim 3, 0, 141, -13, -13, -13, -13,
ax_anim 3, 0, 141, 13, 13, 13, 13,
ax_anim 2, 0, 141, -12, -12, -12, -12,
ax_anim 3, 0, 141, 12, 12, 12, 12,
ax_anim 2, 0, 141, -10, -10, -10, -10,
ax_anim 2, 0, 141, 10, 10, 10, 10,
ax_anim 2, 0, 141, -6, -6, -6, -6,
ax_anim 2, 0, 141, 6, 6, 6, 6,
ax_anim 2, 0, 141, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sStaryuAnims_11_1:
ax_anim 2, 0, 142, 0, 0, 0, 0,
ax_anim 1, 0, 143, 0, -10, 0, 0,
ax_anim 2, 0, 143, 0, -16, 0, 0,
ax_anim 3, 0, 143, 0, -20, 0, 0,
ax_anim 4, 0, 143, 0, -21, 0, 0,
ax_anim 4, 0, 142, 0, -23, 0, 0,
ax_anim 3, 0, 144, 0, -22, 0, 0,
ax_anim 2, 0, 144, 0, -18, 0, 0,
ax_anim 1, 0, 144, 0, -12, 0, 0,
ax_anim 2, 2, 142, 0, 0, 0, 0,
ax_anim_terminator
sStaryuAnims_11_2:
ax_anim 2, 0, 145, 0, 0, 0, 0,
ax_anim 1, 0, 146, 0, -10, 0, 0,
ax_anim 2, 0, 146, 0, -16, 0, 0,
ax_anim 3, 0, 146, 0, -20, 0, 0,
ax_anim 4, 0, 146, 0, -21, 0, 0,
ax_anim 4, 0, 145, 0, -23, 0, 0,
ax_anim 3, 0, 147, 0, -22, 0, 0,
ax_anim 2, 0, 147, 0, -18, 0, 0,
ax_anim 1, 0, 147, 0, -12, 0, 0,
ax_anim 2, 2, 145, 0, 0, 0, 0,
ax_anim_terminator
sStaryuAnims_11_3:
ax_anim 2, 0, 148, 0, 0, 0, 0,
ax_anim 1, 0, 149, 0, -10, 0, 0,
ax_anim 2, 0, 149, 0, -16, 0, 0,
ax_anim 3, 0, 149, 0, -20, 0, 0,
ax_anim 4, 0, 149, 0, -21, 0, 0,
ax_anim 4, 0, 148, 0, -23, 0, 0,
ax_anim 3, 0, 150, 0, -22, 0, 0,
ax_anim 2, 0, 150, 0, -18, 0, 0,
ax_anim 1, 0, 150, 0, -12, 0, 0,
ax_anim 2, 2, 148, 0, 0, 0, 0,
ax_anim_terminator
sStaryuAnims_11_4:
ax_anim 2, 0, 151, 0, 0, 0, 0,
ax_anim 1, 0, 152, 0, -10, 0, 0,
ax_anim 2, 0, 152, 0, -16, 0, 0,
ax_anim 3, 0, 152, 0, -20, 0, 0,
ax_anim 4, 0, 152, 0, -21, 0, 0,
ax_anim 4, 0, 151, 0, -22, 0, 0,
ax_anim 3, 0, 153, 0, -21, 0, 0,
ax_anim 2, 0, 153, 0, -17, 0, 0,
ax_anim 1, 0, 153, 0, -11, 0, 0,
ax_anim 2, 2, 151, 0, 0, 0, 0,
ax_anim_terminator
sStaryuAnims_11_5:
ax_anim 2, 0, 154, 0, 0, 0, 0,
ax_anim 1, 0, 155, 0, -10, 0, 0,
ax_anim 2, 0, 155, 0, -16, 0, 0,
ax_anim 3, 0, 155, 0, -20, 0, 0,
ax_anim 4, 0, 155, 0, -21, 0, 0,
ax_anim 4, 0, 156, 0, -23, 0, 0,
ax_anim 3, 0, 156, 0, -22, 0, 0,
ax_anim 2, 0, 156, 0, -18, 0, 0,
ax_anim 1, 0, 156, 0, -12, 0, 0,
ax_anim 2, 2, 154, 0, 0, 0, 0,
ax_anim_terminator
sStaryuAnims_11_6:
ax_anim 2, 0, 157, 0, 0, 0, 0,
ax_anim 1, 0, 158, 0, -10, 0, 0,
ax_anim 2, 0, 158, 0, -16, 0, 0,
ax_anim 3, 0, 158, 0, -20, 0, 0,
ax_anim 4, 0, 158, 0, -21, 0, 0,
ax_anim 4, 0, 157, 0, -22, 0, 0,
ax_anim 3, 0, 159, 0, -21, 0, 0,
ax_anim 2, 0, 159, 0, -17, 0, 0,
ax_anim 1, 0, 159, 0, -11, 0, 0,
ax_anim 2, 2, 157, 0, 0, 0, 0,
ax_anim_terminator
sStaryuAnims_11_7:
ax_anim 2, 0, 160, 0, 0, 0, 0,
ax_anim 1, 0, 161, 0, -10, 0, 0,
ax_anim 2, 0, 161, 0, -16, 0, 0,
ax_anim 3, 0, 161, 0, -20, 0, 0,
ax_anim 4, 0, 161, 0, -21, 0, 0,
ax_anim 4, 0, 160, 0, -23, 0, 0,
ax_anim 3, 0, 162, 0, -22, 0, 0,
ax_anim 2, 0, 162, 0, -18, 0, 0,
ax_anim 1, 0, 162, 0, -12, 0, 0,
ax_anim 2, 2, 160, 0, 0, 0, 0,
ax_anim_terminator
sStaryuAnims_11_8:
ax_anim 2, 0, 163, 0, 0, 0, 0,
ax_anim 1, 0, 164, 0, -10, 0, 0,
ax_anim 2, 0, 164, 0, -16, 0, 0,
ax_anim 3, 0, 164, 0, -20, 0, 0,
ax_anim 4, 0, 164, 0, -21, 0, 0,
ax_anim 4, 0, 163, 0, -23, 0, 0,
ax_anim 3, 0, 165, 0, -22, 0, 0,
ax_anim 2, 0, 165, 0, -18, 0, 0,
ax_anim 1, 0, 165, 0, -12, 0, 0,
ax_anim 2, 2, 163, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sStaryuAnims_12_1:
ax_anim 2, 0, 166, 1, 0, 1, 0,
ax_anim 2, 0, 166, 0, 0, 0, 0,
ax_anim 2, 0, 166, 1, 0, 1, 0,
ax_anim 2, 0, 166, 0, 0, 0, 0,
ax_anim 2, 0, 166, 1, 0, 1, 0,
ax_anim 2, 2, 166, 0, 0, 0, 0,
ax_anim 2, 0, 166, 1, 0, 1, 0,
ax_anim 2, 0, 166, 0, 0, 0, 0,
ax_anim 2, 0, 166, 1, 0, 1, 0,
ax_anim 2, 1, 166, 0, 0, 0, 0,
ax_anim_terminator
sStaryuAnims_12_2:
ax_anim 2, 0, 173, 1, -1, 1, -1,
ax_anim 2, 0, 173, 0, 0, 0, 0,
ax_anim 2, 0, 173, 1, -1, 1, -1,
ax_anim 2, 0, 173, 0, 0, 0, 0,
ax_anim 2, 0, 173, 1, -1, 1, -1,
ax_anim 2, 2, 173, 0, 0, 0, 0,
ax_anim 2, 0, 173, 1, -1, 1, -1,
ax_anim 2, 0, 173, 0, 0, 0, 0,
ax_anim 2, 0, 173, 1, -1, 1, -1,
ax_anim 2, 1, 173, 0, 0, 0, 0,
ax_anim_terminator
sStaryuAnims_12_3:
ax_anim 2, 0, 172, 0, -1, 0, -1,
ax_anim 2, 0, 172, 0, 0, 0, 0,
ax_anim 2, 0, 172, 0, -1, 0, -1,
ax_anim 2, 0, 172, 0, 0, 0, 0,
ax_anim 2, 0, 172, 0, -1, 0, -1,
ax_anim 2, 2, 172, 0, 0, 0, 0,
ax_anim 2, 0, 172, 0, -1, 0, -1,
ax_anim 2, 0, 172, 0, 0, 0, 0,
ax_anim 2, 0, 172, 0, -1, 0, -1,
ax_anim 2, 1, 172, 0, 0, 0, 0,
ax_anim_terminator
sStaryuAnims_12_4:
ax_anim 2, 0, 171, -1, -1, -1, -1,
ax_anim 2, 0, 171, 0, 0, 0, 0,
ax_anim 2, 0, 171, -1, -1, -1, -1,
ax_anim 2, 0, 171, 0, 0, 0, 0,
ax_anim 2, 0, 171, -1, -1, -1, -1,
ax_anim 2, 2, 171, 0, 0, 0, 0,
ax_anim 2, 0, 171, -1, -1, -1, -1,
ax_anim 2, 0, 171, 0, 0, 0, 0,
ax_anim 2, 0, 171, -1, -1, -1, -1,
ax_anim 2, 1, 171, 0, 0, 0, 0,
ax_anim_terminator
sStaryuAnims_12_5:
ax_anim 2, 0, 170, 1, 0, 1, 0,
ax_anim 2, 0, 170, 0, 0, 0, 0,
ax_anim 2, 0, 170, 1, 0, 1, 0,
ax_anim 2, 0, 170, 0, 0, 0, 0,
ax_anim 2, 0, 170, 1, 0, 1, 0,
ax_anim 2, 2, 170, 0, 0, 0, 0,
ax_anim 2, 0, 170, 1, 0, 1, 0,
ax_anim 2, 0, 170, 0, 0, 0, 0,
ax_anim 2, 0, 170, 1, 0, 1, 0,
ax_anim 2, 1, 170, 0, 0, 0, 0,
ax_anim_terminator
sStaryuAnims_12_6:
ax_anim 2, 0, 169, 1, -1, 1, -1,
ax_anim 2, 0, 169, 0, 0, 0, 0,
ax_anim 2, 0, 169, 1, -1, 1, -1,
ax_anim 2, 0, 169, 0, 0, 0, 0,
ax_anim 2, 0, 169, 1, -1, 1, -1,
ax_anim 2, 2, 169, 0, 0, 0, 0,
ax_anim 2, 0, 169, 1, -1, 1, -1,
ax_anim 2, 0, 169, 0, 0, 0, 0,
ax_anim 2, 0, 169, 1, -1, 1, -1,
ax_anim 2, 1, 169, 0, 0, 0, 0,
ax_anim_terminator
sStaryuAnims_12_7:
ax_anim 2, 0, 168, 0, -1, 0, -1,
ax_anim 2, 0, 168, 0, 0, 0, 0,
ax_anim 2, 0, 168, 0, -1, 0, -1,
ax_anim 2, 0, 168, 0, 0, 0, 0,
ax_anim 2, 0, 168, 0, -1, 0, -1,
ax_anim 2, 2, 168, 0, 0, 0, 0,
ax_anim 2, 0, 168, 0, -1, 0, -1,
ax_anim 2, 0, 168, 0, 0, 0, 0,
ax_anim 2, 0, 168, 0, -1, 0, -1,
ax_anim 2, 1, 168, 0, 0, 0, 0,
ax_anim_terminator
sStaryuAnims_12_8:
ax_anim 2, 0, 167, -1, -1, -1, -1,
ax_anim 2, 0, 167, 0, 0, 0, 0,
ax_anim 2, 0, 167, -1, -1, -1, -1,
ax_anim 2, 0, 167, 0, 0, 0, 0,
ax_anim 2, 0, 167, -1, -1, -1, -1,
ax_anim 2, 2, 167, 0, 0, 0, 0,
ax_anim 2, 0, 167, -1, -1, -1, -1,
ax_anim 2, 0, 167, 0, 0, 0, 0,
ax_anim 2, 0, 167, -1, -1, -1, -1,
ax_anim 2, 1, 167, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sStaryuAnims_13_1:
ax_anim 2, 0, 174, 0, 0, 0, 0,
ax_anim 2, 0, 175, 0, 0, 0, 0,
ax_anim 2, 0, 176, 0, 0, 0, 0,
ax_anim 2, 0, 177, 0, 0, 0, 0,
ax_anim 2, 0, 178, 0, 0, 0, 0,
ax_anim 2, 0, 179, 0, 0, 0, 0,
ax_anim 2, 0, 180, 0, 0, 0, 0,
ax_anim 2, 0, 181, 0, 0, 0, 0,
ax_anim 2, 2, 174, 0, 0, 0, 0,
ax_anim_terminator
sStaryuAnims_13_2:
ax_anim 2, 0, 181, 0, 0, 0, 0,
ax_anim 2, 0, 174, 0, 0, 0, 0,
ax_anim 2, 0, 175, 0, 0, 0, 0,
ax_anim 2, 0, 176, 0, 0, 0, 0,
ax_anim 2, 0, 177, 0, 0, 0, 0,
ax_anim 2, 0, 178, 0, 0, 0, 0,
ax_anim 2, 0, 179, 0, 0, 0, 0,
ax_anim 2, 0, 180, 0, 0, 0, 0,
ax_anim 2, 2, 181, 0, 0, 0, 0,
ax_anim_terminator
sStaryuAnims_13_3:
ax_anim 2, 0, 180, 0, 0, 0, 0,
ax_anim 2, 0, 181, 0, 0, 0, 0,
ax_anim 2, 0, 174, 0, 0, 0, 0,
ax_anim 2, 0, 175, 0, 0, 0, 0,
ax_anim 2, 0, 176, 0, 0, 0, 0,
ax_anim 2, 0, 177, 0, 0, 0, 0,
ax_anim 2, 0, 178, 0, 0, 0, 0,
ax_anim 2, 0, 179, 0, 0, 0, 0,
ax_anim 2, 2, 180, 0, 0, 0, 0,
ax_anim_terminator
sStaryuAnims_13_4:
ax_anim 2, 0, 179, 0, 0, 0, 0,
ax_anim 2, 0, 180, 0, 0, 0, 0,
ax_anim 2, 0, 181, 0, 0, 0, 0,
ax_anim 2, 0, 174, 0, 0, 0, 0,
ax_anim 2, 0, 175, 0, 0, 0, 0,
ax_anim 2, 0, 176, 0, 0, 0, 0,
ax_anim 2, 0, 177, 0, 0, 0, 0,
ax_anim 2, 0, 178, 0, 0, 0, 0,
ax_anim 2, 2, 179, 0, 0, 0, 0,
ax_anim_terminator
sStaryuAnims_13_5:
ax_anim 2, 0, 178, 0, 0, 0, 0,
ax_anim 2, 0, 179, 0, 0, 0, 0,
ax_anim 2, 0, 180, 0, 0, 0, 0,
ax_anim 2, 0, 181, 0, 0, 0, 0,
ax_anim 2, 0, 174, 0, 0, 0, 0,
ax_anim 2, 0, 175, 0, 0, 0, 0,
ax_anim 2, 0, 176, 0, 0, 0, 0,
ax_anim 2, 0, 177, 0, 0, 0, 0,
ax_anim 2, 2, 178, 0, 0, 0, 0,
ax_anim_terminator
sStaryuAnims_13_6:
ax_anim 2, 0, 177, 0, 0, 0, 0,
ax_anim 2, 0, 178, 0, 0, 0, 0,
ax_anim 2, 0, 179, 0, 0, 0, 0,
ax_anim 2, 0, 180, 0, 0, 0, 0,
ax_anim 2, 0, 181, 0, 0, 0, 0,
ax_anim 2, 0, 174, 0, 0, 0, 0,
ax_anim 2, 0, 175, 0, 0, 0, 0,
ax_anim 2, 0, 176, 0, 0, 0, 0,
ax_anim 2, 2, 177, 0, 0, 0, 0,
ax_anim_terminator
sStaryuAnims_13_7:
ax_anim 2, 0, 176, 0, 0, 0, 0,
ax_anim 2, 0, 177, 0, 0, 0, 0,
ax_anim 2, 0, 178, 0, 0, 0, 0,
ax_anim 2, 0, 179, 0, 0, 0, 0,
ax_anim 2, 0, 180, 0, 0, 0, 0,
ax_anim 2, 0, 181, 0, 0, 0, 0,
ax_anim 2, 0, 174, 0, 0, 0, 0,
ax_anim 2, 0, 175, 0, 0, 0, 0,
ax_anim 2, 2, 176, 0, 0, 0, 0,
ax_anim_terminator
sStaryuAnims_13_8:
ax_anim 2, 0, 175, 0, 0, 0, 0,
ax_anim 2, 0, 176, 0, 0, 0, 0,
ax_anim 2, 0, 177, 0, 0, 0, 0,
ax_anim 2, 0, 178, 0, 0, 0, 0,
ax_anim 2, 0, 179, 0, 0, 0, 0,
ax_anim 2, 0, 180, 0, 0, 0, 0,
ax_anim 2, 0, 181, 0, 0, 0, 0,
ax_anim 2, 0, 174, 0, 0, 0, 0,
ax_anim 2, 2, 175, 0, 0, 0, 0,
ax_anim_terminator
sStaryuGfx1:
.incbin "baserom.gba", 0xA2A6F0, 0x200
sStaryuSprites1:
ax_sprite sStaryuGfx1, 0x200
ax_sprite_terminator
sStaryuGfx2:
.incbin "baserom.gba", 0xA2A900, 0x200
sStaryuSprites2:
ax_sprite sStaryuGfx2, 0x200
ax_sprite_terminator
sStaryuGfx3:
.incbin "baserom.gba", 0xA2AB10, 0x200
sStaryuSprites3:
ax_sprite sStaryuGfx3, 0x200
ax_sprite_terminator
sStaryuGfx4:
.incbin "baserom.gba", 0xA2AD20, 0x200
sStaryuSprites4:
ax_sprite sStaryuGfx4, 0x200
ax_sprite_terminator
sStaryuGfx5:
.incbin "baserom.gba", 0xA2AF30, 0x200
sStaryuSprites5:
ax_sprite sStaryuGfx5, 0x200
ax_sprite_terminator
sStaryuGfx6:
.incbin "baserom.gba", 0xA2B140, 0x200
sStaryuSprites6:
ax_sprite sStaryuGfx6, 0x200
ax_sprite_terminator
sStaryuGfx7:
.incbin "baserom.gba", 0xA2B350, 0x100
sStaryuSprites7:
ax_sprite sStaryuGfx7, 0x100
ax_sprite_terminator
sStaryuGfx8:
.incbin "baserom.gba", 0xA2B460, 0x100
sStaryuSprites8:
ax_sprite sStaryuGfx8, 0x100
ax_sprite_terminator
sStaryuGfx9:
.incbin "baserom.gba", 0xA2B570, 0x100
sStaryuSprites9:
ax_sprite sStaryuGfx9, 0x100
ax_sprite_terminator
sStaryuGfx10:
.incbin "baserom.gba", 0xA2B680, 0x200
sStaryuSprites10:
ax_sprite sStaryuGfx10, 0x200
ax_sprite_terminator
sStaryuGfx11:
.incbin "baserom.gba", 0xA2B890, 0x200
sStaryuSprites11:
ax_sprite sStaryuGfx11, 0x200
ax_sprite_terminator
sStaryuGfx12:
.incbin "baserom.gba", 0xA2BAA0, 0x200
sStaryuSprites12:
ax_sprite sStaryuGfx12, 0x200
ax_sprite_terminator
sStaryuGfx13:
.incbin "baserom.gba", 0xA2BCB0, 0x200
sStaryuSprites13:
ax_sprite sStaryuGfx13, 0x200
ax_sprite_terminator
sStaryuGfx14:
.incbin "baserom.gba", 0xA2BEC0, 0x200
sStaryuSprites14:
ax_sprite sStaryuGfx14, 0x200
ax_sprite_terminator
sStaryuGfx15:
.incbin "baserom.gba", 0xA2C0D0, 0x200
sStaryuSprites15:
ax_sprite sStaryuGfx15, 0x200
ax_sprite_terminator
sStaryuGfx16:
.incbin "baserom.gba", 0xA2C2E0, 0x200
sStaryuSprites16:
ax_sprite sStaryuGfx16, 0x200
ax_sprite_terminator
sStaryuGfx17:
.incbin "baserom.gba", 0xA2C4F0, 0x200
sStaryuSprites17:
ax_sprite sStaryuGfx17, 0x200
ax_sprite_terminator
sStaryuGfx18:
.incbin "baserom.gba", 0xA2C700, 0x200
sStaryuSprites18:
ax_sprite sStaryuGfx18, 0x200
ax_sprite_terminator
sStaryuGfx19:
.incbin "baserom.gba", 0xA2C910, 0x20
sStaryuGfx19_1:
.incbin "baserom.gba", 0xA2C930, 0x60
sStaryuGfx19_2:
.incbin "baserom.gba", 0xA2C990, 0x60
sStaryuSprites19:
ax_sprite 0, 0x20
ax_sprite sStaryuGfx19, 0x20
ax_sprite 0, 0x40
ax_sprite sStaryuGfx19_1, 0x60
ax_sprite 0, 0x20
ax_sprite sStaryuGfx19_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sStaryuGfx20:
.incbin "baserom.gba", 0xA2CA30, 0x60
sStaryuGfx20_1:
.incbin "baserom.gba", 0xA2CA90, 0x60
sStaryuGfx20_2:
.incbin "baserom.gba", 0xA2CAF0, 0x60
sStaryuSprites20:
ax_sprite sStaryuGfx20, 0x60
ax_sprite 0, 0x20
ax_sprite sStaryuGfx20_1, 0x60
ax_sprite 0, 0x20
ax_sprite sStaryuGfx20_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sStaryuGfx21:
.incbin "baserom.gba", 0xA2CB88, 0x60
sStaryuGfx21_1:
.incbin "baserom.gba", 0xA2CBE8, 0x60
sStaryuGfx21_2:
.incbin "baserom.gba", 0xA2CC48, 0x20
sStaryuSprites21:
ax_sprite sStaryuGfx21, 0x60
ax_sprite 0, 0x20
ax_sprite sStaryuGfx21_1, 0x60
ax_sprite 0, 0x40
ax_sprite sStaryuGfx21_2, 0x20
ax_sprite 0, 0xc0
ax_sprite_terminator
sStaryuGfx22:
.incbin "baserom.gba", 0xA2CCA0, 0x40
sStaryuGfx22_1:
.incbin "baserom.gba", 0xA2CCE0, 0x60
sStaryuGfx22_2:
.incbin "baserom.gba", 0xA2CD40, 0x60
sStaryuSprites22:
ax_sprite 0, 0x20
ax_sprite sStaryuGfx22, 0x40
ax_sprite 0, 0x20
ax_sprite sStaryuGfx22_1, 0x60
ax_sprite 0, 0x20
ax_sprite sStaryuGfx22_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sStaryuGfx23:
.incbin "baserom.gba", 0xA2CDE0, 0x40
sStaryuGfx23_1:
.incbin "baserom.gba", 0xA2CE20, 0x60
sStaryuGfx23_2:
.incbin "baserom.gba", 0xA2CE80, 0x40
sStaryuSprites23:
ax_sprite 0, 0x20
ax_sprite sStaryuGfx23, 0x40
ax_sprite 0, 0x20
ax_sprite sStaryuGfx23_1, 0x60
ax_sprite 0, 0x20
ax_sprite sStaryuGfx23_2, 0x40
ax_sprite 0, 0xc0
ax_sprite_terminator
sStaryuGfx24:
.incbin "baserom.gba", 0xA2CF00, 0x80
sStaryuSprites24:
ax_sprite sStaryuGfx24, 0x80
ax_sprite_terminator
sStaryuGfx25:
.incbin "baserom.gba", 0xA2CF90, 0x60
sStaryuGfx25_1:
.incbin "baserom.gba", 0xA2CFF0, 0x60
sStaryuSprites25:
ax_sprite sStaryuGfx25, 0x60
ax_sprite 0, 0x20
ax_sprite sStaryuGfx25_1, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sStaryuGfx26:
.incbin "baserom.gba", 0xA2D078, 0x80
sStaryuSprites26:
ax_sprite sStaryuGfx26, 0x80
ax_sprite_terminator
sStaryuGfx27:
.incbin "baserom.gba", 0xA2D108, 0x20
sStaryuGfx27_1:
.incbin "baserom.gba", 0xA2D128, 0x60
sStaryuGfx27_2:
.incbin "baserom.gba", 0xA2D188, 0x60
sStaryuSprites27:
ax_sprite 0, 0x20
ax_sprite sStaryuGfx27, 0x20
ax_sprite 0, 0x40
ax_sprite sStaryuGfx27_1, 0x60
ax_sprite 0, 0x20
ax_sprite sStaryuGfx27_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sStaryuGfx28:
.incbin "baserom.gba", 0xA2D228, 0x40
sStaryuGfx28_1:
.incbin "baserom.gba", 0xA2D268, 0x60
sStaryuGfx28_2:
.incbin "baserom.gba", 0xA2D2C8, 0x60
sStaryuSprites28:
ax_sprite sStaryuGfx28, 0x40
ax_sprite 0, 0x40
ax_sprite sStaryuGfx28_1, 0x60
ax_sprite 0, 0x20
ax_sprite sStaryuGfx28_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sStaryuGfx29:
.incbin "baserom.gba", 0xA2D360, 0xC0
sStaryuSprites29:
ax_sprite sStaryuGfx29, 0xc0
ax_sprite 0, 0x40
ax_sprite_terminator
sStaryuGfx30:
.incbin "baserom.gba", 0xA2D438, 0xC0
sStaryuSprites30:
ax_sprite sStaryuGfx30, 0xc0
ax_sprite 0, 0x40
ax_sprite_terminator
sStaryuGfx31:
.incbin "baserom.gba", 0xA2D510, 0x20
sStaryuGfx31_1:
.incbin "baserom.gba", 0xA2D530, 0x60
sStaryuGfx31_2:
.incbin "baserom.gba", 0xA2D590, 0x60
sStaryuSprites31:
ax_sprite 0, 0x20
ax_sprite sStaryuGfx31, 0x20
ax_sprite 0, 0x40
ax_sprite sStaryuGfx31_1, 0x60
ax_sprite 0, 0x20
ax_sprite sStaryuGfx31_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sStaryuGfx32:
.incbin "baserom.gba", 0xA2D630, 0xC0
sStaryuSprites32:
ax_sprite sStaryuGfx32, 0xc0
ax_sprite 0, 0x40
ax_sprite_terminator
sStaryuGfx33:
.incbin "baserom.gba", 0xA2D708, 0x200
sStaryuSprites33:
ax_sprite sStaryuGfx33, 0x200
ax_sprite_terminator
sStaryuGfx34:
.incbin "baserom.gba", 0xA2D918, 0x200
sStaryuSprites34:
ax_sprite sStaryuGfx34, 0x200
ax_sprite_terminator
sStaryuGfx35:
.incbin "baserom.gba", 0xA2DB28, 0x200
sStaryuSprites35:
ax_sprite sStaryuGfx35, 0x200
ax_sprite_terminator
sStaryuGfx36:
.incbin "baserom.gba", 0xA2DD38, 0x200
sStaryuSprites36:
ax_sprite sStaryuGfx36, 0x200
ax_sprite_terminator
sStaryuGfx37:
.incbin "baserom.gba", 0xA2DF48, 0x200
sStaryuSprites37:
ax_sprite sStaryuGfx37, 0x200
ax_sprite_terminator
sStaryuGfx38:
.incbin "baserom.gba", 0xA2E158, 0x200
sStaryuSprites38:
ax_sprite sStaryuGfx38, 0x200
ax_sprite_terminator
sStaryuGfx39:
.incbin "baserom.gba", 0xA2E368, 0x200
sStaryuSprites39:
ax_sprite sStaryuGfx39, 0x200
ax_sprite_terminator
sStaryuGfx40:
.incbin "baserom.gba", 0xA2E578, 0x200
sStaryuSprites40:
ax_sprite sStaryuGfx40, 0x200
ax_sprite_terminator
sStaryuGfx41:
.incbin "baserom.gba", 0xA2E788, 0x200
sStaryuSprites41:
ax_sprite sStaryuGfx41, 0x200
ax_sprite_terminator
sAxPosesStaryu:
.4byte sStaryuPose1
.4byte sStaryuPose2
.4byte sStaryuPose3
.4byte sStaryuPose4
.4byte sStaryuPose5
.4byte sStaryuPose6
.4byte sStaryuPose7
.4byte sStaryuPose8
.4byte sStaryuPose9
.4byte sStaryuPose10
.4byte sStaryuPose11
.4byte sStaryuPose12
.4byte sStaryuPose13
.4byte sStaryuPose14
.4byte sStaryuPose15
.4byte sStaryuPose16
.4byte sStaryuPose17
.4byte sStaryuPose18
.4byte sStaryuPose19
.4byte sStaryuPose20
.4byte sStaryuPose21
.4byte sStaryuPose22
.4byte sStaryuPose23
.4byte sStaryuPose24
.4byte sStaryuPose25
.4byte sStaryuPose26
.4byte sStaryuPose27
.4byte sStaryuPose28
.4byte sStaryuPose29
.4byte sStaryuPose30
.4byte sStaryuPose31
.4byte sStaryuPose32
.4byte sStaryuPose33
.4byte sStaryuPose34
.4byte sStaryuPose35
.4byte sStaryuPose36
.4byte sStaryuPose37
.4byte sStaryuPose38
.4byte sStaryuPose39
.4byte sStaryuPose40
.4byte sStaryuPose41
.4byte sStaryuPose42
.4byte sStaryuPose43
.4byte sStaryuPose44
.4byte sStaryuPose45
.4byte sStaryuPose46
.4byte sStaryuPose47
.4byte sStaryuPose48
.4byte sStaryuPose49
.4byte sStaryuPose50
.4byte sStaryuPose51
.4byte sStaryuPose52
.4byte sStaryuPose53
.4byte sStaryuPose54
.4byte sStaryuPose55
.4byte sStaryuPose56
.4byte sStaryuPose57
.4byte sStaryuPose58
.4byte sStaryuPose59
.4byte sStaryuPose60
.4byte sStaryuPose61
.4byte sStaryuPose62
.4byte sStaryuPose63
.4byte sStaryuPose64
.4byte sStaryuPose65
.4byte sStaryuPose66
.4byte sStaryuPose67
.4byte sStaryuPose68
.4byte sStaryuPose69
.4byte sStaryuPose70
.4byte sStaryuPose71
.4byte sStaryuPose72
.4byte sStaryuPose73
.4byte sStaryuPose74
.4byte sStaryuPose75
.4byte sStaryuPose76
.4byte sStaryuPose77
.4byte sStaryuPose78
.4byte sStaryuPose79
.4byte sStaryuPose80
.4byte sStaryuPose81
.4byte sStaryuPose82
.4byte sStaryuPose83
.4byte sStaryuPose84
.4byte sStaryuPose85
.4byte sStaryuPose86
.4byte sStaryuPose87
.4byte sStaryuPose88
.4byte sStaryuPose89
.4byte sStaryuPose90
.4byte sStaryuPose91
.4byte sStaryuPose92
.4byte sStaryuPose93
.4byte sStaryuPose94
.4byte sStaryuPose95
.4byte sStaryuPose96
.4byte sStaryuPose97
.4byte sStaryuPose98
.4byte sStaryuPose99
.4byte sStaryuPose100
.4byte sStaryuPose101
.4byte sStaryuPose102
.4byte sStaryuPose103
.4byte sStaryuPose104
.4byte sStaryuPose105
.4byte sStaryuPose106
.4byte sStaryuPose107
.4byte sStaryuPose108
.4byte sStaryuPose109
.4byte sStaryuPose110
.4byte sStaryuPose111
.4byte sStaryuPose112
.4byte sStaryuPose113
.4byte sStaryuPose114
.4byte sStaryuPose115
.4byte sStaryuPose116
.4byte sStaryuPose117
.4byte sStaryuPose118
.4byte sStaryuPose119
.4byte sStaryuPose120
.4byte sStaryuPose121
.4byte sStaryuPose122
.4byte sStaryuPose123
.4byte sStaryuPose124
.4byte sStaryuPose125
.4byte sStaryuPose126
.4byte sStaryuPose127
.4byte sStaryuPose128
.4byte sStaryuPose129
.4byte sStaryuPose130
.4byte sStaryuPose131
.4byte sStaryuPose132
.4byte sStaryuPose133
.4byte sStaryuPose134
.4byte sStaryuPose135
.4byte sStaryuPose136
.4byte sStaryuPose137
.4byte sStaryuPose138
.4byte sStaryuPose139
.4byte sStaryuPose140
.4byte sStaryuPose141
.4byte sStaryuPose142
.4byte sStaryuPose143
.4byte sStaryuPose144
.4byte sStaryuPose145
.4byte sStaryuPose146
.4byte sStaryuPose147
.4byte sStaryuPose148
.4byte sStaryuPose149
.4byte sStaryuPose150
.4byte sStaryuPose151
.4byte sStaryuPose152
.4byte sStaryuPose153
.4byte sStaryuPose154
.4byte sStaryuPose155
.4byte sStaryuPose156
.4byte sStaryuPose157
.4byte sStaryuPose158
.4byte sStaryuPose159
.4byte sStaryuPose160
.4byte sStaryuPose161
.4byte sStaryuPose162
.4byte sStaryuPose163
.4byte sStaryuPose164
.4byte sStaryuPose165
.4byte sStaryuPose166
.4byte sStaryuPose167
.4byte sStaryuPose168
.4byte sStaryuPose169
.4byte sStaryuPose170
.4byte sStaryuPose171
.4byte sStaryuPose172
.4byte sStaryuPose173
.4byte sStaryuPose174
.4byte sStaryuPose175
.4byte sStaryuPose176
.4byte sStaryuPose177
.4byte sStaryuPose178
.4byte sStaryuPose179
.4byte sStaryuPose180
.4byte sStaryuPose181
.4byte sStaryuPose182
sAxPositionsStaryu:
.2byte    0,   -5, 	  -8,  -11, 	   8,  -11, 	   0,   -7
.2byte    1,   -4, 	  -8,  -10, 	   7,   -8, 	   0,   -6
.2byte   -1,   -4, 	  -7,   -8, 	   8,  -10, 	   1,   -6
.2byte    3,   -5, 	   6,  -13, 	  -7,   -8, 	   0,   -7
.2byte    2,   -4, 	   7,  -12, 	  -7,   -7, 	   1,   -6
.2byte    4,   -4, 	   6,  -10, 	  -6,   -8, 	   1,   -6
.2byte    5,   -6, 	   3,  -13, 	  -2,   -6, 	   0,   -7
.2byte    4,   -4, 	   5,  -13, 	  -4,   -5, 	   1,   -6
.2byte    4,   -6, 	   3,  -10, 	   0,   -8, 	   1,   -5
.2byte    2,  -10, 	   7,   -7, 	  -5,  -13, 	   0,   -8
.2byte    0,  -10, 	   7,  -10, 	  -6,   -9, 	   0,   -8
.2byte    4,   -7, 	   6,   -5, 	  -3,  -13, 	   1,   -6
.2byte    0,  -11, 	   8,  -11, 	  -7,  -11, 	   0,   -8
.2byte   -1,  -10, 	   6,  -12, 	  -8,   -7, 	   0,   -8
.2byte    1,  -10, 	   7,   -7, 	  -6,  -12, 	   0,   -7
.2byte   -1,   -8, 	   5,  -12, 	  -7,   -8, 	   0,   -9
.2byte   -2,   -6, 	   3,  -13, 	  -6,   -5, 	   0,   -8
.2byte    1,   -8, 	   7,   -9, 	  -6,   -9, 	   0,   -8
.2byte   -5,   -6, 	  -3,  -13, 	   2,   -6, 	   0,   -7
.2byte   -4,   -4, 	  -5,  -13, 	   4,   -5, 	  -1,   -6
.2byte   -4,   -6, 	  -3,  -10, 	   0,   -8, 	  -1,   -5
.2byte   -3,   -5, 	  -6,  -13, 	   7,   -8, 	   0,   -7
.2byte   -2,   -4, 	  -7,  -12, 	   7,   -7, 	  -1,   -6
.2byte   -4,   -4, 	  -6,  -10, 	   6,   -8, 	  -1,   -6
.2byte    0,   -5, 	  -8,  -11, 	   8,  -11, 	   0,   -7
.2byte    0,   -7, 	  -8,  -11, 	   8,  -11, 	   0,   -8
.2byte    0,   -9, 	  -8,  -11, 	   8,  -11, 	   0,   -8
.2byte    0,   -9, 	  -5,  -13, 	   8,   -6, 	   0,   -8
.2byte    3,   -5, 	   6,  -13, 	  -7,   -8, 	   0,   -7
.2byte    0,   -8, 	   3,  -13, 	  -9,   -4, 	  -1,   -7
.2byte    5,   -6, 	   3,  -13, 	  -2,   -6, 	   0,   -7
.2byte    3,   -9, 	  -1,  -13, 	  -2,   -3, 	   0,   -7
.2byte    2,  -10, 	   7,   -7, 	  -5,  -13, 	   0,   -8
.2byte    2,  -10, 	   4,   -1, 	  -6,  -11, 	   1,   -7
.2byte    0,  -11, 	   8,  -11, 	  -7,  -11, 	   0,   -8
.2byte   -1,  -12, 	   8,   -8, 	  -9,   -8, 	  -1,   -7
.2byte   -1,   -8, 	   5,  -12, 	  -7,   -8, 	   0,   -9
.2byte   -3,  -10, 	   5,  -11, 	  -5,   -2, 	  -1,   -7
.2byte   -5,   -6, 	  -3,  -13, 	   2,   -6, 	   0,   -7
.2byte   -3,   -9, 	   1,  -13, 	   2,   -3, 	   0,   -7
.2byte   -3,   -5, 	  -6,  -13, 	   7,   -8, 	   0,   -7
.2byte    0,   -8, 	  -3,  -13, 	   9,   -4, 	   1,   -7
.2byte    0,   -5, 	  -8,  -11, 	   8,  -11, 	   0,   -7
.2byte    0,   -7, 	  -8,  -11, 	   8,  -11, 	   0,   -8
.2byte    0,   -9, 	  -8,  -11, 	   8,  -11, 	   0,   -8
.2byte    0,   -9, 	  -5,  -13, 	   8,   -6, 	   0,   -8
.2byte    3,   -5, 	   6,  -13, 	  -7,   -8, 	   0,   -7
.2byte    0,   -8, 	   3,  -13, 	  -9,   -4, 	  -1,   -7
.2byte    5,   -6, 	   3,  -13, 	  -2,   -6, 	   0,   -7
.2byte    3,   -9, 	  -1,  -13, 	  -2,   -3, 	   0,   -7
.2byte    2,  -10, 	   7,   -7, 	  -5,  -13, 	   0,   -8
.2byte    2,  -10, 	   4,   -1, 	  -6,  -11, 	   1,   -7
.2byte    0,  -11, 	   8,  -11, 	  -7,  -11, 	   0,   -8
.2byte   -1,  -12, 	   8,   -8, 	  -9,   -8, 	  -1,   -7
.2byte   -1,   -8, 	   5,  -12, 	  -7,   -8, 	   0,   -9
.2byte   -3,  -10, 	   5,  -11, 	  -5,   -2, 	  -1,   -7
.2byte   -5,   -6, 	  -3,  -13, 	   2,   -6, 	   0,   -7
.2byte   -3,   -9, 	   1,  -13, 	   2,   -3, 	   0,   -7
.2byte   -3,   -5, 	  -6,  -13, 	   7,   -8, 	   0,   -7
.2byte    0,   -8, 	  -3,  -13, 	   9,   -4, 	   1,   -7
.2byte    0,   -5, 	  -8,  -11, 	   8,  -11, 	   0,   -7
.2byte    1,   -4, 	  -8,  -10, 	   7,   -8, 	   0,   -6
.2byte   -1,   -4, 	  -7,   -8, 	   8,  -10, 	   1,   -6
.2byte    0,   -3, 	  -8,   -9, 	   7,   -9, 	   0,   -5
.2byte    3,   -5, 	   6,  -13, 	  -7,   -8, 	   0,   -7
.2byte    2,   -4, 	   7,  -12, 	  -7,   -7, 	   1,   -6
.2byte    4,   -4, 	   6,  -10, 	  -6,   -8, 	   1,   -6
.2byte    4,   -4, 	   8,  -14, 	  -6,   -8, 	   2,   -5
.2byte    5,   -7, 	   3,  -14, 	  -2,   -7, 	   0,   -8
.2byte    4,   -6, 	   5,  -15, 	  -4,   -7, 	   1,   -8
.2byte    4,   -8, 	   3,  -12, 	   0,  -10, 	   1,   -7
.2byte    6,   -6, 	  -2,  -15, 	  -3,   -7, 	   1,   -8
.2byte    2,  -10, 	   7,   -7, 	  -5,  -13, 	   0,   -8
.2byte    0,  -10, 	   7,  -10, 	  -6,   -9, 	   0,   -8
.2byte    4,   -7, 	   6,   -5, 	  -3,  -13, 	   1,   -6
.2byte    4,  -10, 	   7,   -8, 	  -5,  -13, 	   2,   -9
.2byte    0,  -11, 	   8,  -11, 	  -7,  -11, 	   0,   -8
.2byte   -1,  -10, 	   6,  -12, 	  -8,   -7, 	   0,   -8
.2byte    1,  -10, 	   7,   -7, 	  -6,  -12, 	   0,   -7
.2byte    0,  -13, 	   8,   -9, 	  -8,   -8, 	   0,   -8
.2byte   -1,   -8, 	   5,  -12, 	  -7,   -8, 	   0,   -9
.2byte   -2,   -6, 	   3,  -13, 	  -6,   -5, 	   0,   -8
.2byte    1,   -8, 	   7,   -9, 	  -6,   -9, 	   0,   -8
.2byte   -2,  -10, 	   5,  -13, 	  -7,   -8, 	  -1,   -9
.2byte   -5,   -7, 	  -3,  -14, 	   2,   -7, 	   0,   -8
.2byte   -4,   -6, 	  -5,  -15, 	   4,   -7, 	  -1,   -8
.2byte   -4,   -8, 	  -3,  -12, 	   0,  -10, 	  -1,   -7
.2byte   -6,   -6, 	   2,  -15, 	   3,   -7, 	  -1,   -8
.2byte   -3,   -5, 	  -6,  -13, 	   7,   -8, 	   0,   -7
.2byte   -2,   -4, 	  -7,  -12, 	   7,   -7, 	  -1,   -6
.2byte   -4,   -4, 	  -6,  -10, 	   6,   -8, 	  -1,   -6
.2byte   -4,   -4, 	  -8,  -14, 	   6,   -8, 	  -2,   -5
.2byte    0,   -5, 	  -8,  -11, 	   8,  -11, 	   0,   -7
.2byte   -3,   -5, 	  -6,  -13, 	   7,   -8, 	   0,   -7
.2byte   -5,   -6, 	  -3,  -13, 	   2,   -6, 	   0,   -7
.2byte   -1,   -8, 	   5,  -12, 	  -7,   -8, 	   0,   -9
.2byte    0,  -11, 	   8,  -11, 	  -7,  -11, 	   0,   -8
.2byte    2,  -10, 	   7,   -7, 	  -5,  -13, 	   0,   -8
.2byte    5,   -6, 	   3,  -13, 	  -2,   -6, 	   0,   -7
.2byte    3,   -5, 	   6,  -13, 	  -7,   -8, 	   0,   -7
.2byte   -2,   -7, 	  -6,   -9, 	   8,   -3, 	   0,   -5
.2byte   -2,   -5, 	  -6,   -8, 	   9,   -3, 	   0,   -3
.2byte    0,   -9, 	  -7,  -16, 	   7,  -16, 	   0,  -11
.2byte    2,   -9, 	  -9,  -12, 	   2,  -18, 	  -1,  -10
.2byte    4,  -11, 	  -1,  -18, 	  -6,  -13, 	   0,  -12
.2byte    1,  -12, 	   4,  -14, 	  -3,  -16, 	  -1,  -10
.2byte    0,  -11, 	   7,  -13, 	  -7,  -13, 	   0,   -9
.2byte    0,  -10, 	   5,  -16, 	  -5,  -14, 	   1,  -11
.2byte   -5,  -10, 	   0,  -17, 	   5,  -12, 	  -1,  -11
.2byte   -2,   -9, 	  -2,  -17, 	  10,  -12, 	   1,  -10
.2byte    0,   -5, 	  -8,  -11, 	   8,  -11, 	   0,   -7
.2byte    0,   -3, 	  -8,   -9, 	   7,   -9, 	   0,   -5
.2byte    3,   -5, 	   6,  -13, 	  -7,   -8, 	   0,   -7
.2byte    4,   -4, 	   8,  -14, 	  -6,   -8, 	   2,   -5
.2byte    5,   -6, 	   3,  -13, 	  -2,   -6, 	   0,   -7
.2byte    6,   -5, 	  -2,  -14, 	  -3,   -6, 	   1,   -7
.2byte    2,  -10, 	   7,   -7, 	  -5,  -13, 	   0,   -8
.2byte    4,  -10, 	   7,   -8, 	  -5,  -13, 	   2,   -9
.2byte    0,  -11, 	   8,  -11, 	  -7,  -11, 	   0,   -8
.2byte    0,  -13, 	   8,   -9, 	  -8,   -8, 	   0,   -8
.2byte   -1,   -8, 	   5,  -12, 	  -7,   -8, 	   0,   -9
.2byte   -2,  -10, 	   5,  -13, 	  -7,   -8, 	  -1,   -9
.2byte   -5,   -6, 	  -3,  -13, 	   2,   -6, 	   0,   -7
.2byte   -6,   -5, 	   2,  -14, 	   3,   -6, 	  -1,   -7
.2byte   -3,   -5, 	  -6,  -13, 	   7,   -8, 	   0,   -7
.2byte   -4,   -4, 	  -8,  -14, 	   6,   -8, 	  -2,   -5
.2byte    0,   -3, 	  -8,   -9, 	   7,   -9, 	   0,   -5
.2byte   -4,   -4, 	  -8,  -14, 	   6,   -8, 	  -2,   -5
.2byte   -6,   -6, 	   2,  -15, 	   3,   -7, 	  -1,   -8
.2byte   -2,  -10, 	   5,  -13, 	  -7,   -8, 	  -1,   -9
.2byte    0,  -13, 	   8,   -9, 	  -8,   -8, 	   0,   -8
.2byte    3,  -10, 	   6,   -8, 	  -6,  -13, 	   1,   -9
.2byte    5,   -6, 	  -3,  -15, 	  -4,   -7, 	   0,   -8
.2byte    3,   -4, 	   7,  -14, 	  -7,   -8, 	   1,   -5
.2byte    0,   -3, 	  -8,   -9, 	   7,   -9, 	   0,   -5
.2byte    3,   -4, 	   7,  -14, 	  -7,   -8, 	   1,   -5
.2byte    5,   -6, 	  -3,  -15, 	  -4,   -7, 	   0,   -8
.2byte    3,  -10, 	   6,   -8, 	  -6,  -13, 	   1,   -9
.2byte    0,  -13, 	   8,   -9, 	  -8,   -8, 	   0,   -8
.2byte   -2,  -10, 	   5,  -13, 	  -7,   -8, 	  -1,   -9
.2byte   -6,   -6, 	   2,  -15, 	   3,   -7, 	  -1,   -8
.2byte   -4,   -4, 	  -8,  -14, 	   6,   -8, 	  -2,   -5
.2byte    0,   -5, 	  -8,  -11, 	   8,  -11, 	   0,   -7
.2byte    0,   -7, 	  -8,  -11, 	   8,  -11, 	   0,   -8
.2byte    0,   -3, 	  -8,   -9, 	   7,   -9, 	   0,   -5
.2byte    3,   -5, 	   6,  -13, 	  -7,   -8, 	   0,   -7
.2byte    0,  -11, 	   3,  -16, 	  -9,   -7, 	  -1,  -10
.2byte    4,   -4, 	   8,  -14, 	  -6,   -8, 	   2,   -5
.2byte    5,   -6, 	   3,  -13, 	  -2,   -6, 	   0,   -7
.2byte    3,   -9, 	  -1,  -13, 	  -2,   -3, 	   0,   -7
.2byte    6,   -5, 	  -2,  -14, 	  -3,   -6, 	   1,   -7
.2byte    2,  -10, 	   7,   -7, 	  -5,  -13, 	   0,   -8
.2byte    2,  -10, 	   4,   -1, 	  -6,  -11, 	   1,   -7
.2byte    4,   -9, 	   7,   -7, 	  -5,  -12, 	   2,   -8
.2byte    0,  -11, 	   8,  -11, 	  -7,  -11, 	   0,   -8
.2byte    0,  -12, 	   9,   -8, 	  -8,   -8, 	   0,   -7
.2byte    0,  -13, 	   8,   -9, 	  -8,   -8, 	   0,   -8
.2byte   -1,   -8, 	   5,  -12, 	  -7,   -8, 	   0,   -9
.2byte   -3,  -10, 	   5,  -11, 	  -5,   -2, 	  -1,   -7
.2byte   -2,   -9, 	   5,  -12, 	  -7,   -7, 	  -1,   -8
.2byte   -5,   -6, 	  -3,  -13, 	   2,   -6, 	   0,   -7
.2byte   -3,   -9, 	   1,  -13, 	   2,   -3, 	   0,   -7
.2byte   -6,   -5, 	   2,  -14, 	   3,   -6, 	  -1,   -7
.2byte   -3,   -5, 	  -6,  -13, 	   7,   -8, 	   0,   -7
.2byte    0,  -11, 	  -3,  -16, 	   9,   -7, 	   1,  -10
.2byte   -4,   -4, 	  -8,  -14, 	   6,   -8, 	  -2,   -5
.2byte    0,   -3, 	  -8,   -9, 	   7,   -9, 	   0,   -5
.2byte   -4,   -4, 	  -8,  -14, 	   6,   -8, 	  -2,   -5
.2byte   -6,   -6, 	   2,  -15, 	   3,   -7, 	  -1,   -8
.2byte   -2,  -10, 	   5,  -13, 	  -7,   -8, 	  -1,   -9
.2byte    0,  -13, 	   8,   -9, 	  -8,   -8, 	   0,   -8
.2byte    3,  -10, 	   6,   -8, 	  -6,  -13, 	   1,   -9
.2byte    5,   -6, 	  -3,  -15, 	  -4,   -7, 	   0,   -8
.2byte    3,   -4, 	   7,  -14, 	  -7,   -8, 	   1,   -5
.2byte    0,   -5, 	  -8,  -11, 	   8,  -11, 	   0,   -7
.2byte   -3,   -5, 	  -6,  -13, 	   7,   -8, 	   0,   -7
.2byte   -5,   -6, 	  -3,  -13, 	   2,   -6, 	   0,   -7
.2byte   -1,   -8, 	   5,  -12, 	  -7,   -8, 	   0,   -9
.2byte    0,  -11, 	   8,  -11, 	  -7,  -11, 	   0,   -8
.2byte    2,  -10, 	   7,   -7, 	  -5,  -13, 	   0,   -8
.2byte    5,   -6, 	   3,  -13, 	  -2,   -6, 	   0,   -7
.2byte    3,   -5, 	   6,  -13, 	  -7,   -8, 	   0,   -7
sStaryuAnimTable1:
.4byte sStaryuAnims_1_1
.4byte sStaryuAnims_1_2
.4byte sStaryuAnims_1_3
.4byte sStaryuAnims_1_4
.4byte sStaryuAnims_1_5
.4byte sStaryuAnims_1_6
.4byte sStaryuAnims_1_7
.4byte sStaryuAnims_1_8
sStaryuAnimTable2:
.4byte sStaryuAnims_2_1
.4byte sStaryuAnims_2_2
.4byte sStaryuAnims_2_3
.4byte sStaryuAnims_2_4
.4byte sStaryuAnims_2_5
.4byte sStaryuAnims_2_6
.4byte sStaryuAnims_2_7
.4byte sStaryuAnims_2_8
sStaryuAnimTable3:
.4byte sStaryuAnims_3_1
.4byte sStaryuAnims_3_2
.4byte sStaryuAnims_3_3
.4byte sStaryuAnims_3_4
.4byte sStaryuAnims_3_5
.4byte sStaryuAnims_3_6
.4byte sStaryuAnims_3_7
.4byte sStaryuAnims_3_8
sStaryuAnimTable4:
.4byte sStaryuAnims_4_1
.4byte sStaryuAnims_4_2
.4byte sStaryuAnims_4_3
.4byte sStaryuAnims_4_4
.4byte sStaryuAnims_4_5
.4byte sStaryuAnims_4_6
.4byte sStaryuAnims_4_7
.4byte sStaryuAnims_4_8
sStaryuAnimTable5:
.4byte sStaryuAnims_5_1
.4byte sStaryuAnims_5_2
.4byte sStaryuAnims_5_3
.4byte sStaryuAnims_5_4
.4byte sStaryuAnims_5_5
.4byte sStaryuAnims_5_6
.4byte sStaryuAnims_5_7
.4byte sStaryuAnims_5_8
sStaryuAnimTable6:
.4byte sStaryuAnims_6_1
.4byte sStaryuAnims_6_1
.4byte sStaryuAnims_6_1
.4byte sStaryuAnims_6_1
.4byte sStaryuAnims_6_1
.4byte sStaryuAnims_6_1
.4byte sStaryuAnims_6_1
.4byte sStaryuAnims_6_1
sStaryuAnimTable7:
.4byte sStaryuAnims_7_1
.4byte sStaryuAnims_7_2
.4byte sStaryuAnims_7_3
.4byte sStaryuAnims_7_4
.4byte sStaryuAnims_7_5
.4byte sStaryuAnims_7_6
.4byte sStaryuAnims_7_7
.4byte sStaryuAnims_7_8
sStaryuAnimTable8:
.4byte sStaryuAnims_8_1
.4byte sStaryuAnims_8_2
.4byte sStaryuAnims_8_3
.4byte sStaryuAnims_8_4
.4byte sStaryuAnims_8_5
.4byte sStaryuAnims_8_6
.4byte sStaryuAnims_8_7
.4byte sStaryuAnims_8_8
sStaryuAnimTable9:
.4byte sStaryuAnims_9_1
.4byte sStaryuAnims_9_2
.4byte sStaryuAnims_9_3
.4byte sStaryuAnims_9_4
.4byte sStaryuAnims_9_5
.4byte sStaryuAnims_9_6
.4byte sStaryuAnims_9_7
.4byte sStaryuAnims_9_8
sStaryuAnimTable10:
.4byte sStaryuAnims_10_1
.4byte sStaryuAnims_10_2
.4byte sStaryuAnims_10_3
.4byte sStaryuAnims_10_4
.4byte sStaryuAnims_10_5
.4byte sStaryuAnims_10_6
.4byte sStaryuAnims_10_7
.4byte sStaryuAnims_10_8
sStaryuAnimTable11:
.4byte sStaryuAnims_11_1
.4byte sStaryuAnims_11_2
.4byte sStaryuAnims_11_3
.4byte sStaryuAnims_11_4
.4byte sStaryuAnims_11_5
.4byte sStaryuAnims_11_6
.4byte sStaryuAnims_11_7
.4byte sStaryuAnims_11_8
sStaryuAnimTable12:
.4byte sStaryuAnims_12_1
.4byte sStaryuAnims_12_2
.4byte sStaryuAnims_12_3
.4byte sStaryuAnims_12_4
.4byte sStaryuAnims_12_5
.4byte sStaryuAnims_12_6
.4byte sStaryuAnims_12_7
.4byte sStaryuAnims_12_8
sStaryuAnimTable13:
.4byte sStaryuAnims_13_1
.4byte sStaryuAnims_13_2
.4byte sStaryuAnims_13_3
.4byte sStaryuAnims_13_4
.4byte sStaryuAnims_13_5
.4byte sStaryuAnims_13_6
.4byte sStaryuAnims_13_7
.4byte sStaryuAnims_13_8
sAxAnimationsStaryu:
.4byte sStaryuAnimTable1
.4byte sStaryuAnimTable2
.4byte sStaryuAnimTable3
.4byte sStaryuAnimTable4
.4byte sStaryuAnimTable5
.4byte sStaryuAnimTable6
.4byte sStaryuAnimTable7
.4byte sStaryuAnimTable8
.4byte sStaryuAnimTable9
.4byte sStaryuAnimTable10
.4byte sStaryuAnimTable11
.4byte sStaryuAnimTable12
.4byte sStaryuAnimTable13
sAxSpritesStaryu:
.4byte sStaryuSprites1
.4byte sStaryuSprites2
.4byte sStaryuSprites3
.4byte sStaryuSprites4
.4byte sStaryuSprites5
.4byte sStaryuSprites6
.4byte sStaryuSprites7
.4byte sStaryuSprites8
.4byte sStaryuSprites9
.4byte sStaryuSprites10
.4byte sStaryuSprites11
.4byte sStaryuSprites12
.4byte sStaryuSprites13
.4byte sStaryuSprites14
.4byte sStaryuSprites15
.4byte sStaryuSprites16
.4byte sStaryuSprites17
.4byte sStaryuSprites18
.4byte sStaryuSprites19
.4byte sStaryuSprites20
.4byte sStaryuSprites21
.4byte sStaryuSprites22
.4byte sStaryuSprites23
.4byte sStaryuSprites24
.4byte sStaryuSprites25
.4byte sStaryuSprites26
.4byte sStaryuSprites27
.4byte sStaryuSprites28
.4byte sStaryuSprites29
.4byte sStaryuSprites30
.4byte sStaryuSprites31
.4byte sStaryuSprites32
.4byte sStaryuSprites33
.4byte sStaryuSprites34
.4byte sStaryuSprites35
.4byte sStaryuSprites36
.4byte sStaryuSprites37
.4byte sStaryuSprites38
.4byte sStaryuSprites39
.4byte sStaryuSprites40
.4byte sStaryuSprites41
sAxMainStaryu:
ax_main sAxPosesStaryu, sAxAnimationsStaryu, 13, sAxSpritesStaryu, sAxPositionsStaryu
