.global gAxSunkern
gAxSunkern:
ax_siro sAxMainSunkern
sSunkernPose1:
ax_pose 0, 0x01ea, 0x80f4, 0x3c00
ax_pose_terminator
sSunkernPose2:
ax_pose 1, 0x01ea, 0x80f4, 0x3c00
ax_pose_terminator
sSunkernPose3:
ax_pose 2, 0x01ea, 0x80f4, 0x3c00
ax_pose_terminator
sSunkernPose4:
ax_pose 3, 0x81ea, 0x90f7, 0x3c00
ax_pose_terminator
sSunkernPose5:
ax_pose 4, 0x01ea, 0x90e7, 0x3c00
ax_pose_terminator
sSunkernPose6:
ax_pose 5, 0x81ea, 0x90f7, 0x3c00
ax_pose_terminator
sSunkernPose7:
ax_pose 6, 0x81ea, 0x90f7, 0x3c00
ax_pose_terminator
sSunkernPose8:
ax_pose 7, 0x81ea, 0x90f7, 0x3c00
ax_pose_terminator
sSunkernPose9:
ax_pose 8, 0x81ea, 0x90f7, 0x3c00
ax_pose_terminator
sSunkernPose10:
ax_pose 9, 0x81ea, 0x90f8, 0x3c00
ax_pose_terminator
sSunkernPose11:
ax_pose 10, 0x81ea, 0x90f8, 0x3c00
ax_pose_terminator
sSunkernPose12:
ax_pose 11, 0x81ea, 0x90f8, 0x3c00
ax_pose_terminator
sSunkernPose13:
ax_pose 12, 0x01ea, 0x80f4, 0x3c00
ax_pose_terminator
sSunkernPose14:
ax_pose 13, 0x01ea, 0x80f4, 0x3c00
ax_pose_terminator
sSunkernPose15:
ax_pose 14, 0x01ea, 0x80f4, 0x3c00
ax_pose_terminator
sSunkernPose16:
ax_pose 9, 0x81ea, 0x80f7, 0x3c00
ax_pose_terminator
sSunkernPose17:
ax_pose 10, 0x81ea, 0x80f7, 0x3c00
ax_pose_terminator
sSunkernPose18:
ax_pose 11, 0x81ea, 0x80f7, 0x3c00
ax_pose_terminator
sSunkernPose19:
ax_pose 6, 0x81ea, 0x80f8, 0x3c00
ax_pose_terminator
sSunkernPose20:
ax_pose 7, 0x81ea, 0x80f8, 0x3c00
ax_pose_terminator
sSunkernPose21:
ax_pose 8, 0x81ea, 0x80f8, 0x3c00
ax_pose_terminator
sSunkernPose22:
ax_pose 3, 0x81ea, 0x80f8, 0x3c00
ax_pose_terminator
sSunkernPose23:
ax_pose 4, 0x01ea, 0x80f8, 0x3c00
ax_pose_terminator
sSunkernPose24:
ax_pose 5, 0x81ea, 0x80f8, 0x3c00
ax_pose_terminator
sSunkernPose25:
ax_pose 0, 0x01ea, 0x80f4, 0x3c00
ax_pose_terminator
sSunkernPose26:
ax_pose 1, 0x01ea, 0x80f4, 0x3c00
ax_pose_terminator
sSunkernPose27:
ax_pose 2, 0x01ea, 0x80f4, 0x3c00
ax_pose_terminator
sSunkernPose28:
ax_pose 3, 0x81ea, 0x90f7, 0x3c00
ax_pose_terminator
sSunkernPose29:
ax_pose 4, 0x01ea, 0x90e7, 0x3c00
ax_pose_terminator
sSunkernPose30:
ax_pose 5, 0x81ea, 0x90f7, 0x3c00
ax_pose_terminator
sSunkernPose31:
ax_pose 6, 0x81ea, 0x90f7, 0x3c00
ax_pose_terminator
sSunkernPose32:
ax_pose 7, 0x81ea, 0x90f7, 0x3c00
ax_pose_terminator
sSunkernPose33:
ax_pose 8, 0x81ea, 0x90f7, 0x3c00
ax_pose_terminator
sSunkernPose34:
ax_pose 9, 0x81ea, 0x90f8, 0x3c00
ax_pose_terminator
sSunkernPose35:
ax_pose 10, 0x81ea, 0x90f8, 0x3c00
ax_pose_terminator
sSunkernPose36:
ax_pose 11, 0x81ea, 0x90f8, 0x3c00
ax_pose_terminator
sSunkernPose37:
ax_pose 12, 0x01ea, 0x80f4, 0x3c00
ax_pose_terminator
sSunkernPose38:
ax_pose 13, 0x01ea, 0x80f4, 0x3c00
ax_pose_terminator
sSunkernPose39:
ax_pose 14, 0x01ea, 0x80f4, 0x3c00
ax_pose_terminator
sSunkernPose40:
ax_pose 9, 0x81ea, 0x80f7, 0x3c00
ax_pose_terminator
sSunkernPose41:
ax_pose 10, 0x81ea, 0x80f7, 0x3c00
ax_pose_terminator
sSunkernPose42:
ax_pose 11, 0x81ea, 0x80f7, 0x3c00
ax_pose_terminator
sSunkernPose43:
ax_pose 6, 0x81ea, 0x80f8, 0x3c00
ax_pose_terminator
sSunkernPose44:
ax_pose 7, 0x81ea, 0x80f8, 0x3c00
ax_pose_terminator
sSunkernPose45:
ax_pose 8, 0x81ea, 0x80f8, 0x3c00
ax_pose_terminator
sSunkernPose46:
ax_pose 3, 0x81ea, 0x80f8, 0x3c00
ax_pose_terminator
sSunkernPose47:
ax_pose 4, 0x01ea, 0x80f8, 0x3c00
ax_pose_terminator
sSunkernPose48:
ax_pose 5, 0x81ea, 0x80f8, 0x3c00
ax_pose_terminator
sSunkernPose49:
ax_pose 0, 0x01ea, 0x80f4, 0x3c00
ax_pose_terminator
sSunkernPose50:
ax_pose 1, 0x01ea, 0x80f4, 0x3c00
ax_pose_terminator
sSunkernPose51:
ax_pose 2, 0x01ea, 0x80f4, 0x3c00
ax_pose_terminator
sSunkernPose52:
ax_pose 3, 0x81ea, 0x90f7, 0x3c00
ax_pose_terminator
sSunkernPose53:
ax_pose 4, 0x01ea, 0x90e7, 0x3c00
ax_pose_terminator
sSunkernPose54:
ax_pose 5, 0x81ea, 0x90f7, 0x3c00
ax_pose_terminator
sSunkernPose55:
ax_pose 6, 0x81ea, 0x90f7, 0x3c00
ax_pose_terminator
sSunkernPose56:
ax_pose 7, 0x81ea, 0x90f7, 0x3c00
ax_pose_terminator
sSunkernPose57:
ax_pose 8, 0x81ea, 0x90f7, 0x3c00
ax_pose_terminator
sSunkernPose58:
ax_pose 9, 0x81ea, 0x90f8, 0x3c00
ax_pose_terminator
sSunkernPose59:
ax_pose 10, 0x81ea, 0x90f8, 0x3c00
ax_pose_terminator
sSunkernPose60:
ax_pose 11, 0x81ea, 0x90f8, 0x3c00
ax_pose_terminator
sSunkernPose61:
ax_pose 12, 0x01ea, 0x80f4, 0x3c00
ax_pose_terminator
sSunkernPose62:
ax_pose 13, 0x01ea, 0x80f4, 0x3c00
ax_pose_terminator
sSunkernPose63:
ax_pose 14, 0x01ea, 0x80f4, 0x3c00
ax_pose_terminator
sSunkernPose64:
ax_pose 9, 0x81ea, 0x80f7, 0x3c00
ax_pose_terminator
sSunkernPose65:
ax_pose 10, 0x81ea, 0x80f7, 0x3c00
ax_pose_terminator
sSunkernPose66:
ax_pose 11, 0x81ea, 0x80f7, 0x3c00
ax_pose_terminator
sSunkernPose67:
ax_pose 6, 0x81ea, 0x80f8, 0x3c00
ax_pose_terminator
sSunkernPose68:
ax_pose 7, 0x81ea, 0x80f8, 0x3c00
ax_pose_terminator
sSunkernPose69:
ax_pose 8, 0x81ea, 0x80f8, 0x3c00
ax_pose_terminator
sSunkernPose70:
ax_pose 3, 0x81ea, 0x80f8, 0x3c00
ax_pose_terminator
sSunkernPose71:
ax_pose 4, 0x01ea, 0x80f8, 0x3c00
ax_pose_terminator
sSunkernPose72:
ax_pose 5, 0x81ea, 0x80f8, 0x3c00
ax_pose_terminator
sSunkernPose73:
ax_pose 0, 0x01ea, 0x80f4, 0x3c00
ax_pose_terminator
sSunkernPose74:
ax_pose 3, 0x81ea, 0x80f8, 0x3c00
ax_pose_terminator
sSunkernPose75:
ax_pose 6, 0x81ea, 0x80f8, 0x3c00
ax_pose_terminator
sSunkernPose76:
ax_pose 9, 0x81ea, 0x80f7, 0x3c00
ax_pose_terminator
sSunkernPose77:
ax_pose 12, 0x01ea, 0x80f4, 0x3c00
ax_pose_terminator
sSunkernPose78:
ax_pose 9, 0x81ea, 0x90f8, 0x3c00
ax_pose_terminator
sSunkernPose79:
ax_pose 6, 0x81ea, 0x90f7, 0x3c00
ax_pose_terminator
sSunkernPose80:
ax_pose 3, 0x81ea, 0x90f7, 0x3c00
ax_pose_terminator
sSunkernPose81:
ax_pose 15, 0x81e9, 0x80f8, 0x3c00
ax_pose_terminator
sSunkernPose82:
ax_pose 16, 0x81e9, 0x80f7, 0x3c00
ax_pose_terminator
sSunkernPose83:
ax_pose 17, 0x81e9, 0x80f8, 0x3c00
ax_pose_terminator
sSunkernPose84:
ax_pose 18, 0x81e9, 0x80f7, 0x3c00
ax_pose_terminator
sSunkernPose85:
ax_pose 19, 0x81e9, 0x80f8, 0x3c00
ax_pose_terminator
sSunkernPose86:
ax_pose 18, 0x81e9, 0x90f7, 0x3c00
ax_pose_terminator
sSunkernPose87:
ax_pose 17, 0x81e9, 0x90f7, 0x3c00
ax_pose_terminator
sSunkernPose88:
ax_pose 16, 0x81e9, 0x90f8, 0x3c00
ax_pose_terminator
sSunkernPose89:
ax_pose 0, 0x01ea, 0x80f4, 0x3c00
ax_pose_terminator
sSunkernPose90:
ax_pose 3, 0x81ea, 0x80f8, 0x3c00
ax_pose_terminator
sSunkernPose91:
ax_pose 6, 0x81ea, 0x80f8, 0x3c00
ax_pose_terminator
sSunkernPose92:
ax_pose 9, 0x81ea, 0x80f7, 0x3c00
ax_pose_terminator
sSunkernPose93:
ax_pose 12, 0x01ea, 0x80f4, 0x3c00
ax_pose_terminator
sSunkernPose94:
ax_pose 9, 0x81ea, 0x90f8, 0x3c00
ax_pose_terminator
sSunkernPose95:
ax_pose 6, 0x81ea, 0x90f7, 0x3c00
ax_pose_terminator
sSunkernPose96:
ax_pose 3, 0x81ea, 0x90f7, 0x3c00
ax_pose_terminator
sSunkernPose97:
ax_pose 20, 0x81ea, 0x80f8, 0x3c00
ax_pose_terminator
sSunkernPose98:
ax_pose 21, 0x81ea, 0x80f8, 0x3c00
ax_pose_terminator
sSunkernPose99:
ax_pose 22, 0x01de, 0x80f1, 0x3c00
ax_pose_terminator
sSunkernPose100:
ax_pose 23, 0x01e1, 0x90e7, 0x3c00
ax_pose_terminator
sSunkernPose101:
ax_pose 24, 0x01e1, 0x90e8, 0x3c00
ax_pose_terminator
sSunkernPose102:
ax_pose 25, 0x01e2, 0x90ea, 0x3c00
ax_pose_terminator
sSunkernPose103:
ax_pose 26, 0x01e0, 0x80f1, 0x3c00
ax_pose_terminator
sSunkernPose104:
ax_pose 25, 0x01e2, 0x80f6, 0x3c00
ax_pose_terminator
sSunkernPose105:
ax_pose 24, 0x01e1, 0x80f8, 0x3c00
ax_pose_terminator
sSunkernPose106:
ax_pose 23, 0x01e1, 0x80f9, 0x3c00
ax_pose_terminator
sSunkernPose107:
ax_pose 0, 0x01ea, 0x80f4, 0x3c00
ax_pose_terminator
sSunkernPose108:
ax_pose 1, 0x01ea, 0x80f4, 0x3c00
ax_pose_terminator
sSunkernPose109:
ax_pose 2, 0x01ea, 0x80f4, 0x3c00
ax_pose_terminator
sSunkernPose110:
ax_pose 3, 0x81ea, 0x90f7, 0x3c00
ax_pose_terminator
sSunkernPose111:
ax_pose 4, 0x01ea, 0x90e7, 0x3c00
ax_pose_terminator
sSunkernPose112:
ax_pose 5, 0x81ea, 0x90f7, 0x3c00
ax_pose_terminator
sSunkernPose113:
ax_pose 6, 0x81ea, 0x90f7, 0x3c00
ax_pose_terminator
sSunkernPose114:
ax_pose 7, 0x81ea, 0x90f7, 0x3c00
ax_pose_terminator
sSunkernPose115:
ax_pose 8, 0x81ea, 0x90f7, 0x3c00
ax_pose_terminator
sSunkernPose116:
ax_pose 9, 0x81ea, 0x90f8, 0x3c00
ax_pose_terminator
sSunkernPose117:
ax_pose 10, 0x81ea, 0x90f8, 0x3c00
ax_pose_terminator
sSunkernPose118:
ax_pose 11, 0x81ea, 0x90f8, 0x3c00
ax_pose_terminator
sSunkernPose119:
ax_pose 12, 0x01ea, 0x80f4, 0x3c00
ax_pose_terminator
sSunkernPose120:
ax_pose 13, 0x01ea, 0x80f4, 0x3c00
ax_pose_terminator
sSunkernPose121:
ax_pose 14, 0x01ea, 0x80f4, 0x3c00
ax_pose_terminator
sSunkernPose122:
ax_pose 9, 0x81ea, 0x80f7, 0x3c00
ax_pose_terminator
sSunkernPose123:
ax_pose 10, 0x81ea, 0x80f7, 0x3c00
ax_pose_terminator
sSunkernPose124:
ax_pose 11, 0x81ea, 0x80f7, 0x3c00
ax_pose_terminator
sSunkernPose125:
ax_pose 6, 0x81ea, 0x80f8, 0x3c00
ax_pose_terminator
sSunkernPose126:
ax_pose 7, 0x81ea, 0x80f8, 0x3c00
ax_pose_terminator
sSunkernPose127:
ax_pose 8, 0x81ea, 0x80f8, 0x3c00
ax_pose_terminator
sSunkernPose128:
ax_pose 3, 0x81ea, 0x80f8, 0x3c00
ax_pose_terminator
sSunkernPose129:
ax_pose 4, 0x01ea, 0x80f8, 0x3c00
ax_pose_terminator
sSunkernPose130:
ax_pose 5, 0x81ea, 0x80f8, 0x3c00
ax_pose_terminator
sSunkernPose131:
ax_pose 0, 0x01ea, 0x80f4, 0x3c00
ax_pose_terminator
sSunkernPose132:
ax_pose 3, 0x81ea, 0x80f8, 0x3c00
ax_pose_terminator
sSunkernPose133:
ax_pose 6, 0x81ea, 0x80f8, 0x3c00
ax_pose_terminator
sSunkernPose134:
ax_pose 9, 0x81ea, 0x80f7, 0x3c00
ax_pose_terminator
sSunkernPose135:
ax_pose 12, 0x01ea, 0x80f4, 0x3c00
ax_pose_terminator
sSunkernPose136:
ax_pose 9, 0x81ea, 0x90f8, 0x3c00
ax_pose_terminator
sSunkernPose137:
ax_pose 6, 0x81ea, 0x90f7, 0x3c00
ax_pose_terminator
sSunkernPose138:
ax_pose 3, 0x81ea, 0x90f7, 0x3c00
ax_pose_terminator
sSunkernPose139:
ax_pose 15, 0x81e9, 0x80f8, 0x3c00
ax_pose_terminator
sSunkernPose140:
ax_pose 16, 0x81e9, 0x90f8, 0x3c00
ax_pose_terminator
sSunkernPose141:
ax_pose 17, 0x81e9, 0x90f7, 0x3c00
ax_pose_terminator
sSunkernPose142:
ax_pose 18, 0x81e9, 0x90f7, 0x3c00
ax_pose_terminator
sSunkernPose143:
ax_pose 19, 0x81e9, 0x80f8, 0x3c00
ax_pose_terminator
sSunkernPose144:
ax_pose 18, 0x81e9, 0x80f7, 0x3c00
ax_pose_terminator
sSunkernPose145:
ax_pose 17, 0x81e9, 0x80f8, 0x3c00
ax_pose_terminator
sSunkernPose146:
ax_pose 16, 0x81e9, 0x80f7, 0x3c00
ax_pose_terminator
sSunkernPose147:
ax_pose 0, 0x01ea, 0x80f4, 0x3c00
ax_pose_terminator
sSunkernPose148:
ax_pose 1, 0x01ea, 0x80f4, 0x3c00
ax_pose_terminator
sSunkernPose149:
ax_pose 2, 0x01ea, 0x80f4, 0x3c00
ax_pose_terminator
sSunkernPose150:
ax_pose 15, 0x81e9, 0x80f8, 0x3c00
ax_pose_terminator
sSunkernPose151:
ax_pose 3, 0x81ea, 0x90f7, 0x3c00
ax_pose_terminator
sSunkernPose152:
ax_pose 4, 0x01ea, 0x90e7, 0x3c00
ax_pose_terminator
sSunkernPose153:
ax_pose 5, 0x81ea, 0x90f7, 0x3c00
ax_pose_terminator
sSunkernPose154:
ax_pose 16, 0x81e9, 0x90f8, 0x3c00
ax_pose_terminator
sSunkernPose155:
ax_pose 6, 0x81ea, 0x90f7, 0x3c00
ax_pose_terminator
sSunkernPose156:
ax_pose 7, 0x81ea, 0x90f7, 0x3c00
ax_pose_terminator
sSunkernPose157:
ax_pose 8, 0x81ea, 0x90f7, 0x3c00
ax_pose_terminator
sSunkernPose158:
ax_pose 17, 0x81e9, 0x90f6, 0x3c00
ax_pose_terminator
sSunkernPose159:
ax_pose 9, 0x81ea, 0x90f8, 0x3c00
ax_pose_terminator
sSunkernPose160:
ax_pose 10, 0x81ea, 0x90f8, 0x3c00
ax_pose_terminator
sSunkernPose161:
ax_pose 11, 0x81ea, 0x90f8, 0x3c00
ax_pose_terminator
sSunkernPose162:
ax_pose 18, 0x81e9, 0x90f7, 0x3c00
ax_pose_terminator
sSunkernPose163:
ax_pose 12, 0x01ea, 0x80f4, 0x3c00
ax_pose_terminator
sSunkernPose164:
ax_pose 13, 0x01ea, 0x80f4, 0x3c00
ax_pose_terminator
sSunkernPose165:
ax_pose 14, 0x01ea, 0x80f4, 0x3c00
ax_pose_terminator
sSunkernPose166:
ax_pose 19, 0x81e9, 0x80f8, 0x3c00
ax_pose_terminator
sSunkernPose167:
ax_pose 9, 0x81ea, 0x80f7, 0x3c00
ax_pose_terminator
sSunkernPose168:
ax_pose 10, 0x81ea, 0x80f7, 0x3c00
ax_pose_terminator
sSunkernPose169:
ax_pose 11, 0x81ea, 0x80f7, 0x3c00
ax_pose_terminator
sSunkernPose170:
ax_pose 18, 0x81e9, 0x80f8, 0x3c00
ax_pose_terminator
sSunkernPose171:
ax_pose 6, 0x81ea, 0x80f8, 0x3c00
ax_pose_terminator
sSunkernPose172:
ax_pose 7, 0x81ea, 0x80f8, 0x3c00
ax_pose_terminator
sSunkernPose173:
ax_pose 8, 0x81ea, 0x80f8, 0x3c00
ax_pose_terminator
sSunkernPose174:
ax_pose 17, 0x81e9, 0x80f9, 0x3c00
ax_pose_terminator
sSunkernPose175:
ax_pose 3, 0x81ea, 0x80f8, 0x3c00
ax_pose_terminator
sSunkernPose176:
ax_pose 4, 0x01ea, 0x80f8, 0x3c00
ax_pose_terminator
sSunkernPose177:
ax_pose 5, 0x81ea, 0x80f8, 0x3c00
ax_pose_terminator
sSunkernPose178:
ax_pose 16, 0x81e9, 0x80f7, 0x3c00
ax_pose_terminator
sSunkernPose179:
ax_pose 15, 0x81e9, 0x80f8, 0x3c00
ax_pose_terminator
sSunkernPose180:
ax_pose 16, 0x81e9, 0x80f7, 0x3c00
ax_pose_terminator
sSunkernPose181:
ax_pose 17, 0x81e9, 0x80f8, 0x3c00
ax_pose_terminator
sSunkernPose182:
ax_pose 18, 0x81e9, 0x80f7, 0x3c00
ax_pose_terminator
sSunkernPose183:
ax_pose 19, 0x81e9, 0x80f8, 0x3c00
ax_pose_terminator
sSunkernPose184:
ax_pose 18, 0x81e9, 0x90f7, 0x3c00
ax_pose_terminator
sSunkernPose185:
ax_pose 17, 0x81e9, 0x90f7, 0x3c00
ax_pose_terminator
sSunkernPose186:
ax_pose 16, 0x81e9, 0x90f8, 0x3c00
ax_pose_terminator
sSunkernPose187:
ax_pose 0, 0x01ea, 0x80f4, 0x3c00
ax_pose_terminator
sSunkernPose188:
ax_pose 3, 0x81ea, 0x80f8, 0x3c00
ax_pose_terminator
sSunkernPose189:
ax_pose 6, 0x81ea, 0x80f8, 0x3c00
ax_pose_terminator
sSunkernPose190:
ax_pose 9, 0x81ea, 0x80f7, 0x3c00
ax_pose_terminator
sSunkernPose191:
ax_pose 12, 0x01ea, 0x80f4, 0x3c00
ax_pose_terminator
sSunkernPose192:
ax_pose 9, 0x81ea, 0x90f8, 0x3c00
ax_pose_terminator
sSunkernPose193:
ax_pose 6, 0x81ea, 0x90f7, 0x3c00
ax_pose_terminator
sSunkernPose194:
ax_pose 3, 0x81ea, 0x90f7, 0x3c00
ax_pose_terminator
.align 2
sSunkernAnims_1_1:
ax_anim 4, 0, 0, 0, 0, 0, 0,
ax_anim 6, 0, 1, 0, 0, 0, 0,
ax_anim 6, 0, 0, 0, -2, 0, 0,
ax_anim 6, 0, 2, 0, -3, 0, 0,
ax_anim 6, 0, 0, 0, -4, 0, 0,
ax_anim 6, 0, 2, 0, -4, 0, 0,
ax_anim 6, 0, 0, 0, -3, 0, 0,
ax_anim 6, 0, 2, 0, -2, 0, 0,
ax_anim_terminator
sSunkernAnims_1_2:
ax_anim 4, 0, 3, 0, 0, 0, 0,
ax_anim 6, 0, 4, 0, 0, 0, 0,
ax_anim 6, 0, 3, 0, -2, 0, 0,
ax_anim 6, 0, 5, 0, -3, 0, 0,
ax_anim 6, 0, 3, 0, -4, 0, 0,
ax_anim 6, 0, 5, 0, -4, 0, 0,
ax_anim 6, 0, 3, 0, -3, 0, 0,
ax_anim 6, 0, 5, 0, -2, 0, 0,
ax_anim_terminator
sSunkernAnims_1_3:
ax_anim 4, 0, 6, 0, 0, 0, 0,
ax_anim 6, 0, 7, 0, 0, 0, 0,
ax_anim 6, 0, 6, 0, -2, 0, 0,
ax_anim 6, 0, 8, 0, -3, 0, 0,
ax_anim 6, 0, 6, 0, -4, 0, 0,
ax_anim 6, 0, 8, 0, -4, 0, 0,
ax_anim 6, 0, 6, 0, -3, 0, 0,
ax_anim 6, 0, 8, 0, -2, 0, 0,
ax_anim_terminator
sSunkernAnims_1_4:
ax_anim 4, 0, 9, 0, 0, 0, 0,
ax_anim 6, 0, 10, 0, 0, 0, 0,
ax_anim 6, 0, 9, 0, -2, 0, 0,
ax_anim 6, 0, 11, 0, -3, 0, 0,
ax_anim 6, 0, 9, 0, -4, 0, 0,
ax_anim 6, 0, 11, 0, -4, 0, 0,
ax_anim 6, 0, 9, 0, -3, 0, 0,
ax_anim 6, 0, 11, 0, -2, 0, 0,
ax_anim_terminator
sSunkernAnims_1_5:
ax_anim 4, 0, 12, 0, 0, 0, 0,
ax_anim 6, 0, 13, 0, 0, 0, 0,
ax_anim 6, 0, 12, 0, -2, 0, 0,
ax_anim 6, 0, 14, 0, -3, 0, 0,
ax_anim 6, 0, 12, 0, -4, 0, 0,
ax_anim 6, 0, 14, 0, -4, 0, 0,
ax_anim 6, 0, 12, 0, -3, 0, 0,
ax_anim 6, 0, 14, 0, -2, 0, 0,
ax_anim_terminator
sSunkernAnims_1_6:
ax_anim 4, 0, 15, 0, 0, 0, 0,
ax_anim 6, 0, 16, 0, 0, 0, 0,
ax_anim 6, 0, 15, 0, -2, 0, 0,
ax_anim 6, 0, 17, 0, -3, 0, 0,
ax_anim 6, 0, 15, 0, -4, 0, 0,
ax_anim 6, 0, 17, 0, -4, 0, 0,
ax_anim 6, 0, 15, 0, -3, 0, 0,
ax_anim 6, 0, 17, 0, -2, 0, 0,
ax_anim_terminator
sSunkernAnims_1_7:
ax_anim 4, 0, 18, 0, 0, 0, 0,
ax_anim 6, 0, 19, 0, 0, 0, 0,
ax_anim 6, 0, 18, 0, -2, 0, 0,
ax_anim 6, 0, 20, 0, -3, 0, 0,
ax_anim 6, 0, 18, 0, -4, 0, 0,
ax_anim 6, 0, 20, 0, -4, 0, 0,
ax_anim 6, 0, 18, 0, -3, 0, 0,
ax_anim 6, 0, 20, 0, -2, 0, 0,
ax_anim_terminator
sSunkernAnims_1_8:
ax_anim 4, 0, 21, 0, 0, 0, 0,
ax_anim 6, 0, 22, 0, 0, 0, 0,
ax_anim 6, 0, 21, 0, -2, 0, 0,
ax_anim 6, 0, 23, 0, -3, 0, 0,
ax_anim 6, 0, 21, 0, -4, 0, 0,
ax_anim 6, 0, 23, 0, -4, 0, 0,
ax_anim 6, 0, 21, 0, -3, 0, 0,
ax_anim 6, 0, 23, 0, -2, 0, 0,
ax_anim_terminator
.align 2
sSunkernAnims_2_1:
ax_anim 4, 0, 24, 0, 0, 0, 0,
ax_anim 2, 0, 24, 0, -3, 0, -3,
ax_anim 4, 0, 24, 0, -5, 0, -5,
ax_anim 2, 0, 25, 0, -1, 0, 1,
ax_anim 2, 0, 25, 0, 2, 0, 7,
ax_anim 2, 2, 25, 0, 10, 0, 16,
ax_anim 2, 0, 25, 0, 22, 0, 22,
ax_anim 2, 1, 25, 1, 22, 1, 22,
ax_anim 2, 0, 25, 0, 22, 0, 22,
ax_anim 2, 0, 25, 1, 22, 1, 22,
ax_anim 4, 0, 24, 0, 8, 0, 8,
ax_anim_terminator
sSunkernAnims_2_2:
ax_anim 4, 0, 27, 0, 0, 0, 0,
ax_anim 2, 0, 27, -3, -3, -3, -3,
ax_anim 4, 0, 27, -5, -5, -5, -5,
ax_anim 2, 0, 28, 1, -5, 1, 0,
ax_anim 2, 0, 28, 4, -4, 4, 3,
ax_anim 2, 2, 28, 13, 2, 13, 11,
ax_anim 2, 0, 28, 22, 19, 22, 19,
ax_anim 2, 1, 28, 23, 18, 23, 18,
ax_anim 2, 0, 28, 22, 19, 22, 19,
ax_anim 2, 0, 28, 23, 18, 23, 18,
ax_anim 4, 0, 27, 6, 6, 6, 6,
ax_anim_terminator
sSunkernAnims_2_3:
ax_anim 4, 0, 30, 0, 0, 0, 0,
ax_anim 2, 0, 30, -3, 0, -3, 0,
ax_anim 4, 0, 30, -5, 0, -5, 0,
ax_anim 2, 0, 31, 1, -3, 1, 0,
ax_anim 2, 0, 31, 3, -5, 3, 0,
ax_anim 2, 2, 31, 10, -6, 10, 0,
ax_anim 2, 0, 31, 22, 0, 22, 0,
ax_anim 2, 1, 31, 22, 1, 22, 1,
ax_anim 2, 0, 31, 22, 0, 22, 0,
ax_anim 2, 0, 31, 22, 1, 22, 1,
ax_anim 4, 0, 30, 6, 0, 6, 0,
ax_anim_terminator
sSunkernAnims_2_4:
ax_anim 4, 0, 33, 0, 0, 0, 0,
ax_anim 2, 0, 33, -3, 3, -3, 3,
ax_anim 4, 0, 33, -5, 5, -5, 5,
ax_anim 2, 0, 34, 1, -13, 1, -1,
ax_anim 2, 0, 34, 5, -18, 5, -6,
ax_anim 2, 2, 34, 10, -22, 10, -12,
ax_anim 2, 0, 34, 22, -25, 22, -25,
ax_anim 2, 1, 34, 23, -24, 23, -24,
ax_anim 2, 0, 34, 22, -25, 22, -25,
ax_anim 2, 0, 34, 23, -24, 23, -24,
ax_anim 4, 0, 33, 6, -6, 6, -6,
ax_anim_terminator
sSunkernAnims_2_5:
ax_anim 4, 0, 36, 0, 0, 0, 0,
ax_anim 2, 0, 36, 0, 3, 0, 3,
ax_anim 4, 0, 36, 0, 5, 0, 5,
ax_anim 2, 0, 37, 0, 1, 0, 4,
ax_anim 2, 0, 37, 0, -2, 0, 1,
ax_anim 2, 2, 37, 0, -10, 0, -4,
ax_anim 2, 0, 37, 0, -24, 0, -24,
ax_anim 2, 1, 37, 1, -24, 1, -24,
ax_anim 2, 0, 37, 0, -24, 0, -24,
ax_anim 2, 0, 37, 1, -24, 1, -24,
ax_anim 4, 0, 36, 0, -8, 0, -8,
ax_anim_terminator
sSunkernAnims_2_6:
ax_anim 4, 0, 39, 0, 0, 0, 0,
ax_anim 2, 0, 39, 3, 3, 3, 3,
ax_anim 4, 0, 39, 5, 5, 5, 5,
ax_anim 2, 0, 40, -1, -13, -1, -1,
ax_anim 2, 0, 40, -5, -18, -5, -6,
ax_anim 2, 2, 40, -10, -22, -10, -12,
ax_anim 2, 0, 40, -22, -25, -22, -25,
ax_anim 2, 1, 40, -23, -24, -23, -24,
ax_anim 2, 0, 40, -22, -25, -22, -25,
ax_anim 2, 0, 40, -23, -24, -23, -24,
ax_anim 4, 0, 39, -6, -6, -6, -6,
ax_anim_terminator
sSunkernAnims_2_7:
ax_anim 4, 0, 42, 0, 0, 0, 0,
ax_anim 2, 0, 42, 3, 0, 3, 0,
ax_anim 4, 0, 42, 5, 0, 5, 0,
ax_anim 2, 0, 43, -1, -3, -1, 0,
ax_anim 2, 0, 43, -3, -5, -3, 0,
ax_anim 2, 2, 43, -10, -6, -10, 0,
ax_anim 2, 0, 43, -22, 0, -22, 0,
ax_anim 2, 1, 43, -22, 1, -22, 1,
ax_anim 2, 0, 43, -22, 0, -22, 0,
ax_anim 2, 0, 43, -22, 1, -22, 1,
ax_anim 4, 0, 42, -6, 0, -6, 0,
ax_anim_terminator
sSunkernAnims_2_8:
ax_anim 4, 0, 45, 0, 0, 0, 0,
ax_anim 2, 0, 45, 3, -3, 3, -3,
ax_anim 4, 0, 45, 5, -5, 5, -5,
ax_anim 2, 0, 46, -1, -5, -1, 0,
ax_anim 2, 0, 46, -4, -4, -4, 3,
ax_anim 2, 2, 46, -13, 2, -13, 11,
ax_anim 2, 0, 46, -22, 19, -22, 19,
ax_anim 2, 1, 46, -23, 18, -23, 18,
ax_anim 2, 0, 46, -22, 19, -22, 19,
ax_anim 2, 0, 46, -23, 18, -23, 18,
ax_anim 4, 0, 45, -6, 6, -6, 6,
ax_anim_terminator
.align 2
sSunkernAnims_3_1:
ax_anim 4, 0, 48, 0, 0, 0, 0,
ax_anim 2, 0, 48, 0, -3, 0, -3,
ax_anim 4, 0, 48, 0, -5, 0, -5,
ax_anim 2, 0, 49, 0, -1, 0, 1,
ax_anim 2, 0, 49, 0, 2, 0, 7,
ax_anim 2, 2, 49, 0, 10, 0, 16,
ax_anim 2, 0, 49, 0, 22, 0, 22,
ax_anim 2, 1, 49, 1, 22, 1, 22,
ax_anim 2, 0, 49, 0, 22, 0, 22,
ax_anim 2, 0, 49, 1, 22, 1, 22,
ax_anim 4, 0, 48, 0, 8, 0, 8,
ax_anim_terminator
sSunkernAnims_3_2:
ax_anim 4, 0, 51, 0, 0, 0, 0,
ax_anim 2, 0, 51, -3, -3, -3, -3,
ax_anim 4, 0, 51, -5, -5, -5, -5,
ax_anim 2, 0, 52, 1, -5, 1, 0,
ax_anim 2, 0, 52, 4, -4, 4, 3,
ax_anim 2, 2, 52, 13, 2, 13, 11,
ax_anim 2, 0, 52, 22, 19, 22, 19,
ax_anim 2, 1, 52, 23, 18, 23, 18,
ax_anim 2, 0, 52, 22, 19, 22, 19,
ax_anim 2, 0, 52, 23, 18, 23, 18,
ax_anim 4, 0, 51, 6, 6, 6, 6,
ax_anim_terminator
sSunkernAnims_3_3:
ax_anim 4, 0, 54, 0, 0, 0, 0,
ax_anim 2, 0, 54, -3, 0, -3, 0,
ax_anim 4, 0, 54, -5, 0, -5, 0,
ax_anim 2, 0, 55, 1, -3, 1, 0,
ax_anim 2, 0, 55, 3, -5, 3, 0,
ax_anim 2, 2, 55, 10, -6, 10, 0,
ax_anim 2, 0, 55, 22, 0, 22, 0,
ax_anim 2, 1, 55, 22, 1, 22, 1,
ax_anim 2, 0, 55, 22, 0, 22, 0,
ax_anim 2, 0, 55, 22, 1, 22, 1,
ax_anim 4, 0, 54, 6, 0, 6, 0,
ax_anim_terminator
sSunkernAnims_3_4:
ax_anim 4, 0, 57, 0, 0, 0, 0,
ax_anim 2, 0, 57, -3, 3, -3, 3,
ax_anim 4, 0, 57, -5, 5, -5, 5,
ax_anim 2, 0, 58, 1, -13, 1, -1,
ax_anim 2, 0, 58, 5, -18, 5, -6,
ax_anim 2, 2, 58, 10, -22, 10, -12,
ax_anim 2, 0, 58, 22, -25, 22, -25,
ax_anim 2, 1, 58, 23, -24, 23, -24,
ax_anim 2, 0, 58, 22, -25, 22, -25,
ax_anim 2, 0, 58, 23, -24, 23, -24,
ax_anim 4, 0, 57, 6, -6, 6, -6,
ax_anim_terminator
sSunkernAnims_3_5:
ax_anim 4, 0, 60, 0, 0, 0, 0,
ax_anim 2, 0, 60, 0, 3, 0, 3,
ax_anim 4, 0, 60, 0, 5, 0, 5,
ax_anim 2, 0, 61, 0, 1, 0, 4,
ax_anim 2, 0, 61, 0, -2, 0, 1,
ax_anim 2, 2, 61, 0, -10, 0, -4,
ax_anim 2, 0, 61, 0, -24, 0, -24,
ax_anim 2, 1, 61, 1, -24, 1, -24,
ax_anim 2, 0, 61, 0, -24, 0, -24,
ax_anim 2, 0, 61, 1, -24, 1, -24,
ax_anim 4, 0, 60, 0, -8, 0, -8,
ax_anim_terminator
sSunkernAnims_3_6:
ax_anim 4, 0, 63, 0, 0, 0, 0,
ax_anim 2, 0, 63, 3, 3, 3, 3,
ax_anim 4, 0, 63, 5, 5, 5, 5,
ax_anim 2, 0, 64, -1, -13, -1, -1,
ax_anim 2, 0, 64, -5, -18, -5, -6,
ax_anim 2, 2, 64, -10, -22, -10, -12,
ax_anim 2, 0, 64, -22, -25, -22, -25,
ax_anim 2, 1, 64, -23, -24, -23, -24,
ax_anim 2, 0, 64, -22, -25, -22, -25,
ax_anim 2, 0, 64, -23, -24, -23, -24,
ax_anim 4, 0, 63, -6, -6, -6, -6,
ax_anim_terminator
sSunkernAnims_3_7:
ax_anim 4, 0, 66, 0, 0, 0, 0,
ax_anim 2, 0, 66, 3, 0, 3, 0,
ax_anim 4, 0, 66, 5, 0, 5, 0,
ax_anim 2, 0, 67, -1, -3, -1, 0,
ax_anim 2, 0, 67, -3, -5, -3, 0,
ax_anim 2, 2, 67, -10, -6, -10, 0,
ax_anim 2, 0, 67, -22, 0, -22, 0,
ax_anim 2, 1, 67, -22, 1, -22, 1,
ax_anim 2, 0, 67, -22, 0, -22, 0,
ax_anim 2, 0, 67, -22, 1, -22, 1,
ax_anim 4, 0, 66, -6, 0, -6, 0,
ax_anim_terminator
sSunkernAnims_3_8:
ax_anim 4, 0, 69, 0, 0, 0, 0,
ax_anim 2, 0, 69, 3, -3, 3, -3,
ax_anim 4, 0, 69, 5, -5, 5, -5,
ax_anim 2, 0, 70, -1, -5, -1, 0,
ax_anim 2, 0, 70, -4, -4, -4, 3,
ax_anim 2, 2, 70, -13, 2, -13, 11,
ax_anim 2, 0, 70, -22, 19, -22, 19,
ax_anim 2, 1, 70, -23, 18, -23, 18,
ax_anim 2, 0, 70, -22, 19, -22, 19,
ax_anim 2, 0, 70, -23, 18, -23, 18,
ax_anim 4, 0, 69, -6, 6, -6, 6,
ax_anim_terminator
.align 2
sSunkernAnims_4_1:
ax_anim 3, 0, 72, 0, 0, 0, 0,
ax_anim 2, 0, 73, 0, -1, 0, 0,
ax_anim 1, 0, 74, 0, -3, 0, 0,
ax_anim 1, 0, 75, 0, -5, 0, 0,
ax_anim 1, 0, 76, 0, -6, 0, 0,
ax_anim 1, 0, 77, 0, -6, 0, 0,
ax_anim 1, 0, 78, 0, -5, 0, 0,
ax_anim 2, 0, 79, 0, -3, 0, 0,
ax_anim 2, 0, 72, 0, -1, 0, 0,
ax_anim 4, 0, 73, 0, 0, 0, 0,
ax_anim 2, 2, 80, 0, 0, 0, 0,
ax_anim 2, 0, 80, 0, 1, 0, 1,
ax_anim 2, 0, 80, 1, 1, 1, 1,
ax_anim 2, 0, 80, 0, 1, 0, 1,
ax_anim 2, 1, 80, 1, 1, 1, 1,
ax_anim 2, 0, 80, 0, 1, 0, 1,
ax_anim_terminator
sSunkernAnims_4_2:
ax_anim 3, 0, 79, 0, 0, 0, 0,
ax_anim 2, 0, 72, 0, -1, 0, 0,
ax_anim 1, 0, 73, 0, -3, 0, 0,
ax_anim 1, 0, 74, 0, -5, 0, 0,
ax_anim 1, 0, 75, 0, -6, 0, 0,
ax_anim 1, 0, 76, 0, -6, 0, 0,
ax_anim 1, 0, 77, 0, -5, 0, 0,
ax_anim 2, 0, 78, 0, -3, 0, 0,
ax_anim 2, 0, 79, 0, -1, 0, 0,
ax_anim 4, 0, 72, 0, 0, 0, 0,
ax_anim 2, 2, 87, 0, 0, 0, 0,
ax_anim 2, 0, 87, 1, 1, 1, 1,
ax_anim 2, 0, 87, 0, 2, 0, 2,
ax_anim 2, 0, 87, 1, 1, 1, 1,
ax_anim 2, 1, 87, 0, 2, 0, 2,
ax_anim 2, 0, 87, 1, 1, 1, 1,
ax_anim_terminator
sSunkernAnims_4_3:
ax_anim 3, 0, 78, 0, 0, 0, 0,
ax_anim 2, 0, 79, 0, -1, 0, 0,
ax_anim 1, 0, 72, 0, -3, 0, 0,
ax_anim 1, 0, 73, 0, -5, 0, 0,
ax_anim 1, 0, 74, 0, -6, 0, 0,
ax_anim 1, 0, 75, 0, -6, 0, 0,
ax_anim 1, 0, 76, 0, -5, 0, 0,
ax_anim 2, 0, 77, 0, -3, 0, 0,
ax_anim 2, 0, 78, 0, -1, 0, 0,
ax_anim 4, 0, 79, 0, 0, 0, 0,
ax_anim 2, 2, 86, 0, 0, 0, 0,
ax_anim 2, 0, 86, 1, 0, 1, 0,
ax_anim 2, 0, 86, 1, -1, 1, -1,
ax_anim 2, 0, 86, 1, 0, 1, 0,
ax_anim 2, 1, 86, 1, -1, 1, -1,
ax_anim 2, 0, 86, 1, 0, 1, 0,
ax_anim_terminator
sSunkernAnims_4_4:
ax_anim 3, 0, 77, 0, 0, 0, 0,
ax_anim 2, 0, 78, 0, -1, 0, 0,
ax_anim 1, 0, 79, 0, -3, 0, 0,
ax_anim 1, 0, 72, 0, -5, 0, 0,
ax_anim 1, 0, 73, 0, -6, 0, 0,
ax_anim 1, 0, 74, 0, -6, 0, 0,
ax_anim 1, 0, 75, 0, -5, 0, 0,
ax_anim 2, 0, 76, 0, -3, 0, 0,
ax_anim 2, 0, 77, 0, -1, 0, 0,
ax_anim 4, 0, 78, 0, 0, 0, 0,
ax_anim 2, 2, 85, 0, 0, 0, 0,
ax_anim 2, 0, 85, 1, -1, 1, -1,
ax_anim 2, 0, 85, 2, 0, 2, 0,
ax_anim 2, 0, 85, 1, -1, 1, -1,
ax_anim 2, 1, 85, 2, 0, 2, 0,
ax_anim 2, 0, 85, 1, -1, 1, -1,
ax_anim_terminator
sSunkernAnims_4_5:
ax_anim 3, 0, 76, 0, 0, 0, 0,
ax_anim 2, 0, 77, 0, -1, 0, 0,
ax_anim 1, 0, 78, 0, -3, 0, 0,
ax_anim 1, 0, 79, 0, -5, 0, 0,
ax_anim 1, 0, 72, 0, -6, 0, 0,
ax_anim 1, 0, 73, 0, -6, 0, 0,
ax_anim 1, 0, 74, 0, -5, 0, 0,
ax_anim 2, 0, 75, 0, -3, 0, 0,
ax_anim 2, 0, 76, 0, -1, 0, 0,
ax_anim 4, 0, 77, 0, 0, 0, 0,
ax_anim 2, 2, 84, 0, 0, 0, 0,
ax_anim 2, 0, 84, 0, -1, 0, -1,
ax_anim 2, 0, 84, 1, -1, 1, -1,
ax_anim 2, 0, 84, 0, -1, 0, -1,
ax_anim 2, 1, 84, 1, -1, 1, -1,
ax_anim 2, 0, 84, 0, -1, 0, -1,
ax_anim_terminator
sSunkernAnims_4_6:
ax_anim 3, 0, 75, 0, 0, 0, 0,
ax_anim 2, 0, 76, 0, -1, 0, 0,
ax_anim 1, 0, 77, 0, -3, 0, 0,
ax_anim 1, 0, 78, 0, -5, 0, 0,
ax_anim 1, 0, 79, 0, -6, 0, 0,
ax_anim 1, 0, 72, 0, -6, 0, 0,
ax_anim 1, 0, 73, 0, -5, 0, 0,
ax_anim 2, 0, 74, 0, -3, 0, 0,
ax_anim 2, 0, 75, 0, -1, 0, 0,
ax_anim 4, 0, 76, 0, 0, 0, 0,
ax_anim 2, 2, 83, 0, 0, 0, 0,
ax_anim 2, 0, 83, -1, -1, -1, -1,
ax_anim 2, 0, 83, -2, 0, -2, 0,
ax_anim 2, 0, 83, -1, -1, -1, -1,
ax_anim 2, 1, 83, -2, 0, -2, 0,
ax_anim 2, 0, 83, -1, -1, -1, -1,
ax_anim_terminator
sSunkernAnims_4_7:
ax_anim 3, 0, 74, 0, 0, 0, 0,
ax_anim 2, 0, 75, 0, -1, 0, 0,
ax_anim 1, 0, 76, 0, -3, 0, 0,
ax_anim 1, 0, 77, 0, -5, 0, 0,
ax_anim 1, 0, 78, 0, -6, 0, 0,
ax_anim 1, 0, 79, 0, -6, 0, 0,
ax_anim 1, 0, 72, 0, -5, 0, 0,
ax_anim 2, 0, 73, 0, -3, 0, 0,
ax_anim 2, 0, 74, 0, -1, 0, 0,
ax_anim 4, 0, 75, 0, 0, 0, 0,
ax_anim 2, 2, 82, 0, 0, 0, 0,
ax_anim 2, 0, 82, -1, 0, -1, 0,
ax_anim 2, 0, 82, -1, -1, -1, -1,
ax_anim 2, 0, 82, -1, 0, -1, 0,
ax_anim 2, 1, 82, -1, -1, -1, -1,
ax_anim 2, 0, 82, -1, 0, -1, 0,
ax_anim_terminator
sSunkernAnims_4_8:
ax_anim 3, 0, 73, 0, 0, 0, 0,
ax_anim 2, 0, 74, 0, -1, 0, 0,
ax_anim 1, 0, 75, 0, -3, 0, 0,
ax_anim 1, 0, 76, 0, -5, 0, 0,
ax_anim 1, 0, 77, 0, -6, 0, 0,
ax_anim 1, 0, 78, 0, -6, 0, 0,
ax_anim 1, 0, 79, 0, -5, 0, 0,
ax_anim 2, 0, 72, 0, -3, 0, 0,
ax_anim 2, 0, 73, 0, -1, 0, 0,
ax_anim 4, 0, 74, 0, 0, 0, 0,
ax_anim 2, 2, 81, 0, 0, 0, 0,
ax_anim 2, 0, 81, -1, 1, -1, 1,
ax_anim 2, 0, 81, -2, 0, -2, 0,
ax_anim 2, 0, 81, -1, 1, -1, 1,
ax_anim 2, 1, 81, -2, 0, -2, 0,
ax_anim 2, 0, 81, -1, 1, -1, 1,
ax_anim_terminator
.align 2
sSunkernAnims_5_1:
ax_anim 2, 0, 88, 0, 0, 0, 0,
ax_anim 2, 0, 89, 0, 0, 0, 0,
ax_anim 2, 0, 90, 0, 0, 0, 0,
ax_anim 2, 0, 91, 0, 0, 0, 0,
ax_anim 2, 0, 92, 0, 0, 0, 0,
ax_anim 2, 0, 93, 0, 0, 0, 0,
ax_anim 2, 0, 94, 0, 0, 0, 0,
ax_anim 2, 0, 95, 0, 0, 0, 0,
ax_anim 2, 2, 88, 0, 0, 0, 0,
ax_anim_terminator
sSunkernAnims_5_2:
ax_anim 2, 0, 95, 0, 0, 0, 0,
ax_anim 2, 0, 88, 0, 0, 0, 0,
ax_anim 2, 0, 89, 0, 0, 0, 0,
ax_anim 2, 0, 90, 0, 0, 0, 0,
ax_anim 2, 0, 91, 0, 0, 0, 0,
ax_anim 2, 0, 92, 0, 0, 0, 0,
ax_anim 2, 0, 93, 0, 0, 0, 0,
ax_anim 2, 0, 94, 0, 0, 0, 0,
ax_anim 2, 2, 95, 0, 0, 0, 0,
ax_anim_terminator
sSunkernAnims_5_3:
ax_anim 2, 0, 94, 0, 0, 0, 0,
ax_anim 2, 0, 95, 0, 0, 0, 0,
ax_anim 2, 0, 88, 0, 0, 0, 0,
ax_anim 2, 0, 89, 0, 0, 0, 0,
ax_anim 2, 0, 90, 0, 0, 0, 0,
ax_anim 2, 0, 91, 0, 0, 0, 0,
ax_anim 2, 0, 92, 0, 0, 0, 0,
ax_anim 2, 0, 93, 0, 0, 0, 0,
ax_anim 2, 2, 94, 0, 0, 0, 0,
ax_anim_terminator
sSunkernAnims_5_4:
ax_anim 2, 0, 93, 0, 0, 0, 0,
ax_anim 2, 0, 94, 0, 0, 0, 0,
ax_anim 2, 0, 95, 0, 0, 0, 0,
ax_anim 2, 0, 88, 0, 0, 0, 0,
ax_anim 2, 0, 89, 0, 0, 0, 0,
ax_anim 2, 0, 90, 0, 0, 0, 0,
ax_anim 2, 0, 91, 0, 0, 0, 0,
ax_anim 2, 0, 92, 0, 0, 0, 0,
ax_anim 2, 2, 93, 0, 0, 0, 0,
ax_anim_terminator
sSunkernAnims_5_5:
ax_anim 2, 0, 92, 0, 0, 0, 0,
ax_anim 2, 0, 93, 0, 0, 0, 0,
ax_anim 2, 0, 94, 0, 0, 0, 0,
ax_anim 2, 0, 95, 0, 0, 0, 0,
ax_anim 2, 0, 88, 0, 0, 0, 0,
ax_anim 2, 0, 89, 0, 0, 0, 0,
ax_anim 2, 0, 90, 0, 0, 0, 0,
ax_anim 2, 0, 91, 0, 0, 0, 0,
ax_anim 2, 2, 92, 0, 0, 0, 0,
ax_anim_terminator
sSunkernAnims_5_6:
ax_anim 2, 0, 91, 0, 0, 0, 0,
ax_anim 2, 0, 92, 0, 0, 0, 0,
ax_anim 2, 0, 93, 0, 0, 0, 0,
ax_anim 2, 0, 94, 0, 0, 0, 0,
ax_anim 2, 0, 95, 0, 0, 0, 0,
ax_anim 2, 0, 88, 0, 0, 0, 0,
ax_anim 2, 0, 89, 0, 0, 0, 0,
ax_anim 2, 0, 90, 0, 0, 0, 0,
ax_anim 2, 2, 91, 0, 0, 0, 0,
ax_anim_terminator
sSunkernAnims_5_7:
ax_anim 2, 0, 90, 0, 0, 0, 0,
ax_anim 2, 0, 91, 0, 0, 0, 0,
ax_anim 2, 0, 92, 0, 0, 0, 0,
ax_anim 2, 0, 93, 0, 0, 0, 0,
ax_anim 2, 0, 94, 0, 0, 0, 0,
ax_anim 2, 0, 95, 0, 0, 0, 0,
ax_anim 2, 0, 88, 0, 0, 0, 0,
ax_anim 2, 0, 89, 0, 0, 0, 0,
ax_anim 2, 2, 90, 0, 0, 0, 0,
ax_anim_terminator
sSunkernAnims_5_8:
ax_anim 2, 0, 89, 0, 0, 0, 0,
ax_anim 2, 0, 90, 0, 0, 0, 0,
ax_anim 2, 0, 91, 0, 0, 0, 0,
ax_anim 2, 0, 92, 0, 0, 0, 0,
ax_anim 2, 0, 93, 0, 0, 0, 0,
ax_anim 2, 0, 94, 0, 0, 0, 0,
ax_anim 2, 0, 95, 0, 0, 0, 0,
ax_anim 2, 0, 88, 0, 0, 0, 0,
ax_anim 2, 2, 89, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sSunkernAnims_6_1:
ax_anim 30, 0, 96, 0, 0, 0, 0,
ax_anim 35, 0, 97, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sSunkernAnims_7_1:
ax_anim 2, 0, 98, 0, -4, 0, -4,
ax_anim 8, 0, 98, 0, -5, 0, -5,
ax_anim_terminator
sSunkernAnims_7_2:
ax_anim 2, 0, 99, -4, -4, -4, -4,
ax_anim 8, 0, 99, -5, -5, -5, -5,
ax_anim_terminator
sSunkernAnims_7_3:
ax_anim 2, 0, 100, -4, 0, -4, 0,
ax_anim 8, 0, 100, -5, 0, -5, 0,
ax_anim_terminator
sSunkernAnims_7_4:
ax_anim 2, 0, 101, -4, 4, -4, 4,
ax_anim 8, 0, 101, -5, 5, -5, 5,
ax_anim_terminator
sSunkernAnims_7_5:
ax_anim 2, 0, 102, 0, 4, 0, 4,
ax_anim 8, 0, 102, 0, 5, 0, 5,
ax_anim_terminator
sSunkernAnims_7_6:
ax_anim 2, 0, 103, 4, 4, 4, 4,
ax_anim 8, 0, 103, 5, 5, 5, 5,
ax_anim_terminator
sSunkernAnims_7_7:
ax_anim 2, 0, 104, 4, 0, 4, 0,
ax_anim 8, 0, 104, 5, 0, 5, 0,
ax_anim_terminator
sSunkernAnims_7_8:
ax_anim 2, 0, 105, 4, -4, 4, -4,
ax_anim 8, 0, 105, 5, -5, 5, -5,
ax_anim_terminator
.align 2
sSunkernAnims_8_1:
ax_anim 26, 0, 106, 0, 0, 0, 0,
ax_anim 18, 0, 108, 0, 0, 0, 0,
ax_anim_terminator
sSunkernAnims_8_2:
ax_anim 26, 0, 109, 0, 0, 0, 0,
ax_anim 18, 0, 111, 0, 0, 0, 0,
ax_anim_terminator
sSunkernAnims_8_3:
ax_anim 26, 0, 112, 0, 0, 0, 0,
ax_anim 18, 0, 114, 0, 0, 0, 0,
ax_anim_terminator
sSunkernAnims_8_4:
ax_anim 26, 0, 115, 0, 0, 0, 0,
ax_anim 18, 0, 117, 0, 0, 0, 0,
ax_anim_terminator
sSunkernAnims_8_5:
ax_anim 26, 0, 118, 0, 0, 0, 0,
ax_anim 18, 0, 120, 0, 0, 0, 0,
ax_anim_terminator
sSunkernAnims_8_6:
ax_anim 26, 0, 121, 0, 0, 0, 0,
ax_anim 18, 0, 123, 0, 0, 0, 0,
ax_anim_terminator
sSunkernAnims_8_7:
ax_anim 26, 0, 124, 0, 0, 0, 0,
ax_anim 18, 0, 126, 0, 0, 0, 0,
ax_anim_terminator
sSunkernAnims_8_8:
ax_anim 26, 0, 127, 0, 0, 0, 0,
ax_anim 18, 0, 129, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sSunkernAnims_9_1:
ax_anim 2, 0, 130, 0, 0, 0, 0,
ax_anim 1, 0, 131, 6, 4, 6, 4,
ax_anim 2, 0, 132, 8, 9, 8, 9,
ax_anim 2, 0, 133, 7, 19, 7, 19,
ax_anim 3, 0, 134, 1, 22, 1, 24,
ax_anim 2, 3, 135, -6, 19, -6, 19,
ax_anim 2, 0, 136, -8, 9, -8, 9,
ax_anim 1, 0, 137, -6, 4, -6, 4,
ax_anim 1, 0, 130, 0, 0, 0, 0,
ax_anim_terminator
sSunkernAnims_9_2:
ax_anim 2, 0, 137, 0, 0, 0, 0,
ax_anim 1, 0, 130, 6, 0, 6, 0,
ax_anim 2, 0, 131, 17, 3, 17, 3,
ax_anim 2, 0, 132, 24, 9, 24, 9,
ax_anim 3, 0, 133, 23, 21, 23, 21,
ax_anim 2, 3, 134, 11, 21, 11, 21,
ax_anim 2, 0, 135, 2, 12, 2, 12,
ax_anim 1, 0, 136, 0, 7, 0, 7,
ax_anim 1, 0, 137, 0, 0, 0, 0,
ax_anim_terminator
sSunkernAnims_9_3:
ax_anim 2, 0, 136, 0, 0, 0, 0,
ax_anim 1, 0, 137, 3, -4, 3, -4,
ax_anim 2, 0, 130, 11, -6, 11, -6,
ax_anim 2, 0, 131, 17, -4, 17, -4,
ax_anim 3, 0, 132, 22, 1, 22, 1,
ax_anim 2, 3, 133, 17, 5, 17, 5,
ax_anim 2, 0, 134, 12, 7, 12, 7,
ax_anim 1, 0, 135, 4, 5, 4, 5,
ax_anim 1, 0, 136, 0, 0, 0, 0,
ax_anim_terminator
sSunkernAnims_9_4:
ax_anim 2, 0, 135, 0, 0, 0, 0,
ax_anim 1, 0, 136, -1, -6, -1, -6,
ax_anim 2, 0, 137, 3, -18, 3, -18,
ax_anim 2, 0, 130, 11, -23, 11, -23,
ax_anim 3, 0, 131, 21, -24, 21, -24,
ax_anim 2, 3, 132, 21, -11, 21, -11,
ax_anim 2, 0, 133, 16, -6, 16, -6,
ax_anim 1, 0, 134, 7, -1, 7, -1,
ax_anim 1, 0, 135, 0, 0, 0, 0,
ax_anim_terminator
sSunkernAnims_9_5:
ax_anim 2, 0, 134, 0, 0, 0, 0,
ax_anim 1, 0, 135, -6, -4, -6, -4,
ax_anim 2, 0, 136, -8, -10, -8, -10,
ax_anim 2, 0, 137, -7, -18, -7, -18,
ax_anim 3, 0, 130, 0, -25, 0, -25,
ax_anim 2, 3, 131, 7, -20, 7, -20,
ax_anim 2, 0, 132, 8, -10, 8, -10,
ax_anim 1, 0, 133, 6, -4, 6, -4,
ax_anim 1, 0, 134, 0, 0, 0, 0,
ax_anim_terminator
sSunkernAnims_9_6:
ax_anim 2, 0, 133, 0, 0, 0, 0,
ax_anim 1, 0, 132, 1, -6, 1, -6,
ax_anim 2, 0, 131, -3, -18, -3, -18,
ax_anim 2, 0, 130, -11, -23, -11, -23,
ax_anim 3, 0, 137, -21, -24, -21, -24,
ax_anim 2, 3, 136, -21, -11, -21, -11,
ax_anim 2, 0, 135, -16, -6, -16, -6,
ax_anim 1, 0, 134, -7, -1, -7, -1,
ax_anim 1, 0, 133, 0, 0, 0, 0,
ax_anim_terminator
sSunkernAnims_9_7:
ax_anim 2, 0, 132, 0, 0, 0, 0,
ax_anim 1, 0, 131, -3, -4, -3, -4,
ax_anim 2, 0, 130, -11, -6, -11, -6,
ax_anim 2, 0, 137, -17, -4, -17, -4,
ax_anim 3, 0, 136, -22, 1, -22, 1,
ax_anim 2, 3, 135, -17, 5, -17, 5,
ax_anim 2, 0, 134, -12, 7, -12, 7,
ax_anim 1, 0, 133, -4, 5, -4, 5,
ax_anim 1, 0, 132, 0, 0, 0, 0,
ax_anim_terminator
sSunkernAnims_9_8:
ax_anim 2, 0, 131, 0, 0, 0, 0,
ax_anim 1, 0, 130, -6, 0, -6, 0,
ax_anim 2, 0, 137, -17, 3, -17, 3,
ax_anim 2, 0, 136, -24, 9, -24, 9,
ax_anim 3, 0, 135, -23, 21, -23, 16,
ax_anim 2, 3, 134, -11, 21, -11, 16,
ax_anim 2, 0, 133, -2, 12, -4, 12,
ax_anim 1, 0, 132, 0, 7, -3, 7,
ax_anim 1, 0, 131, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sSunkernAnims_10_1:
ax_anim 2, 0, 138, 0, 0, 0, 0,
ax_anim 2, 0, 138, 6, 0, 6, 0,
ax_anim 2, 0, 138, -6, 0, -6, 0,
ax_anim 2, 0, 138, 10, 0, 10, 0,
ax_anim 2, 0, 138, -10, 0, -10, 0,
ax_anim 2, 0, 138, 12, 0, 12, 0,
ax_anim 3, 0, 138, -12, 0, -12, 0,
ax_anim 3, 0, 138, 13, 0, 13, 0,
ax_anim 3, 0, 138, -13, 0, -13, 0,
ax_anim 2, 0, 138, 12, 0, 12, 0,
ax_anim 3, 0, 138, -12, 0, -12, 0,
ax_anim 2, 0, 138, 10, 0, 10, 0,
ax_anim 2, 0, 138, -10, 0, -10, 0,
ax_anim 2, 0, 138, 6, 0, 6, 0,
ax_anim 2, 0, 138, -6, 0, -6, 0,
ax_anim 2, 0, 138, 0, 0, 0, 0,
ax_anim_terminator
sSunkernAnims_10_2:
ax_anim 2, 0, 139, 0, 0, 0, 0,
ax_anim 2, 0, 139, 6, -6, 6, -6,
ax_anim 2, 0, 139, -6, 6, -6, 6,
ax_anim 2, 0, 139, 10, -10, 10, -10,
ax_anim 2, 0, 139, -10, 10, -10, 10,
ax_anim 2, 0, 139, 12, -12, 12, -12,
ax_anim 3, 0, 139, -12, 12, -12, 12,
ax_anim 3, 0, 139, 13, -13, 13, -13,
ax_anim 3, 0, 139, -13, 13, -13, 13,
ax_anim 2, 0, 139, 12, -12, 12, -12,
ax_anim 3, 0, 139, -12, 12, -12, 12,
ax_anim 2, 0, 139, 10, -10, 10, -10,
ax_anim 2, 0, 139, -10, 10, -10, 10,
ax_anim 2, 0, 139, 6, -6, 6, -6,
ax_anim 2, 0, 139, -6, 6, -6, 6,
ax_anim 2, 0, 139, 0, 0, 0, 0,
ax_anim_terminator
sSunkernAnims_10_3:
ax_anim 2, 0, 140, 0, 0, 0, 0,
ax_anim 2, 0, 140, 0, -6, 0, -6,
ax_anim 2, 0, 140, 0, 6, 0, 6,
ax_anim 2, 0, 140, 0, -10, 0, -10,
ax_anim 2, 0, 140, 0, 10, 0, 10,
ax_anim 2, 0, 140, 0, -12, 0, -12,
ax_anim 3, 0, 140, 0, 12, 0, 12,
ax_anim 3, 0, 140, 0, -13, 0, -13,
ax_anim 3, 0, 140, 0, 13, 0, 13,
ax_anim 2, 0, 140, 0, -12, 0, -12,
ax_anim 3, 0, 140, 0, 12, 0, 12,
ax_anim 2, 0, 140, 0, -10, 0, -10,
ax_anim 2, 0, 140, 0, 10, 0, 10,
ax_anim 2, 0, 140, 0, -6, 0, -6,
ax_anim 2, 0, 140, 0, 6, 0, 6,
ax_anim 2, 0, 140, 0, 0, 0, 0,
ax_anim_terminator
sSunkernAnims_10_4:
ax_anim 2, 0, 141, 0, 0, 0, 0,
ax_anim 2, 0, 141, -6, -6, -6, -6,
ax_anim 2, 0, 141, 6, 6, 6, 6,
ax_anim 2, 0, 141, -10, -10, -10, -10,
ax_anim 2, 0, 141, 10, 10, 10, 10,
ax_anim 2, 0, 141, -12, -12, -12, -12,
ax_anim 3, 0, 141, 12, 12, 12, 12,
ax_anim 3, 0, 141, -13, -13, -13, -13,
ax_anim 3, 0, 141, 13, 13, 13, 13,
ax_anim 2, 0, 141, -12, -12, -12, -12,
ax_anim 3, 0, 141, 12, 12, 12, 12,
ax_anim 2, 0, 141, -10, -10, -10, -10,
ax_anim 2, 0, 141, 10, 10, 10, 10,
ax_anim 2, 0, 141, -6, -6, -6, -6,
ax_anim 2, 0, 141, 6, 6, 6, 6,
ax_anim 2, 0, 141, 0, 0, 0, 0,
ax_anim_terminator
sSunkernAnims_10_5:
ax_anim 2, 0, 142, 0, 0, 0, 0,
ax_anim 2, 0, 142, 6, 0, 6, 0,
ax_anim 2, 0, 142, -6, 0, -6, 0,
ax_anim 2, 0, 142, 10, 0, 10, 0,
ax_anim 2, 0, 142, -10, 0, -10, 0,
ax_anim 2, 0, 142, 12, 0, 12, 0,
ax_anim 3, 0, 142, -12, 0, -12, 0,
ax_anim 3, 0, 142, 13, 0, 13, 0,
ax_anim 3, 0, 142, -13, 0, -13, 0,
ax_anim 2, 0, 142, 12, 0, 12, 0,
ax_anim 3, 0, 142, -12, 0, -12, 0,
ax_anim 2, 0, 142, 10, 0, 10, 0,
ax_anim 2, 0, 142, -10, 0, -10, 0,
ax_anim 2, 0, 142, 6, 0, 6, 0,
ax_anim 2, 0, 142, -6, 0, -6, 0,
ax_anim 2, 0, 142, 0, 0, 0, 0,
ax_anim_terminator
sSunkernAnims_10_6:
ax_anim 2, 0, 143, 0, 0, 0, 0,
ax_anim 2, 0, 143, 6, -6, 6, -6,
ax_anim 2, 0, 143, -6, 6, -6, 6,
ax_anim 2, 0, 143, 10, -10, 10, -10,
ax_anim 2, 0, 143, -10, 10, -10, 10,
ax_anim 2, 0, 143, 12, -12, 12, -12,
ax_anim 3, 0, 143, -12, 12, -12, 12,
ax_anim 3, 0, 143, 13, -13, 13, -13,
ax_anim 3, 0, 143, -13, 13, -13, 13,
ax_anim 2, 0, 143, 12, -12, 12, -12,
ax_anim 3, 0, 143, -12, 12, -12, 12,
ax_anim 2, 0, 143, 10, -10, 10, -10,
ax_anim 2, 0, 143, -10, 10, -10, 10,
ax_anim 2, 0, 143, 6, -6, 6, -6,
ax_anim 2, 0, 143, -6, 6, -6, 6,
ax_anim 2, 0, 143, 0, 0, 0, 0,
ax_anim_terminator
sSunkernAnims_10_7:
ax_anim 2, 0, 144, 0, 0, 0, 0,
ax_anim 2, 0, 144, 0, -6, 0, -6,
ax_anim 2, 0, 144, 0, 6, 0, 6,
ax_anim 2, 0, 144, 0, -10, 0, -10,
ax_anim 2, 0, 144, 0, 10, 0, 10,
ax_anim 2, 0, 144, 0, -12, 0, -12,
ax_anim 3, 0, 144, 0, 12, 0, 12,
ax_anim 3, 0, 144, 0, -13, 0, -13,
ax_anim 3, 0, 144, 0, 13, 0, 13,
ax_anim 2, 0, 144, 0, -12, 0, -12,
ax_anim 3, 0, 144, 0, 12, 0, 12,
ax_anim 2, 0, 144, 0, -10, 0, -10,
ax_anim 2, 0, 144, 0, 10, 0, 10,
ax_anim 2, 0, 144, 0, -6, 0, -6,
ax_anim 2, 0, 144, 0, 6, 0, 6,
ax_anim 2, 0, 144, 0, 0, 0, 0,
ax_anim_terminator
sSunkernAnims_10_8:
ax_anim 2, 0, 145, 0, 0, 0, 0,
ax_anim 2, 0, 145, -6, -6, -6, -6,
ax_anim 2, 0, 145, 6, 6, 6, 6,
ax_anim 2, 0, 145, -10, -10, -10, -10,
ax_anim 2, 0, 145, 10, 10, 10, 10,
ax_anim 2, 0, 145, -12, -12, -12, -12,
ax_anim 3, 0, 145, 12, 12, 12, 12,
ax_anim 3, 0, 145, -13, -13, -13, -13,
ax_anim 3, 0, 145, 13, 13, 13, 13,
ax_anim 2, 0, 145, -12, -12, -12, -12,
ax_anim 3, 0, 145, 12, 12, 12, 12,
ax_anim 2, 0, 145, -10, -10, -10, -10,
ax_anim 2, 0, 145, 10, 10, 10, 10,
ax_anim 2, 0, 145, -6, -6, -6, -6,
ax_anim 2, 0, 145, 6, 6, 6, 6,
ax_anim 2, 0, 145, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sSunkernAnims_11_1:
ax_anim 2, 0, 146, 0, 0, 0, 0,
ax_anim 1, 0, 148, 0, -10, 0, 0,
ax_anim 2, 0, 148, 0, -16, 0, 0,
ax_anim 3, 0, 148, 0, -20, 0, 0,
ax_anim 4, 0, 147, 0, -21, 0, 0,
ax_anim 4, 0, 149, 0, -23, 0, 0,
ax_anim 3, 0, 149, 0, -22, 0, 0,
ax_anim 2, 0, 149, 0, -18, 0, 0,
ax_anim 1, 0, 149, 0, -12, 0, 0,
ax_anim 2, 2, 149, 0, 0, 0, 0,
ax_anim_terminator
sSunkernAnims_11_2:
ax_anim 2, 0, 150, 0, 0, 0, 0,
ax_anim 1, 0, 152, 0, -10, 0, 0,
ax_anim 2, 0, 152, 0, -16, 0, 0,
ax_anim 3, 0, 152, 0, -20, 0, 0,
ax_anim 4, 0, 151, 0, -21, 0, 0,
ax_anim 4, 0, 153, 0, -23, 0, 0,
ax_anim 3, 0, 153, 0, -22, 0, 0,
ax_anim 2, 0, 153, 0, -18, 0, 0,
ax_anim 1, 0, 153, 0, -12, 0, 0,
ax_anim 2, 2, 153, 0, 0, 0, 0,
ax_anim_terminator
sSunkernAnims_11_3:
ax_anim 2, 0, 154, 0, 0, 0, 0,
ax_anim 1, 0, 156, 0, -10, 0, 0,
ax_anim 2, 0, 156, 0, -16, 0, 0,
ax_anim 3, 0, 156, 0, -20, 0, 0,
ax_anim 4, 0, 155, 0, -21, 0, 0,
ax_anim 4, 0, 157, 0, -23, 0, 0,
ax_anim 3, 0, 157, 0, -22, 0, 0,
ax_anim 2, 0, 157, 0, -18, 0, 0,
ax_anim 1, 0, 157, 0, -12, 0, 0,
ax_anim 2, 2, 157, 0, 0, 0, 0,
ax_anim_terminator
sSunkernAnims_11_4:
ax_anim 2, 0, 158, 0, 0, 0, 0,
ax_anim 1, 0, 160, 0, -10, 0, 0,
ax_anim 2, 0, 160, 0, -16, 0, 0,
ax_anim 3, 0, 160, 0, -20, 0, 0,
ax_anim 4, 0, 159, 0, -21, 0, 0,
ax_anim 4, 0, 161, 0, -22, 0, 0,
ax_anim 3, 0, 161, 0, -21, 0, 0,
ax_anim 2, 0, 161, 0, -17, 0, 0,
ax_anim 1, 0, 161, 0, -11, 0, 0,
ax_anim 2, 2, 161, 0, 0, 0, 0,
ax_anim_terminator
sSunkernAnims_11_5:
ax_anim 2, 0, 162, 0, 0, 0, 0,
ax_anim 1, 0, 164, 0, -10, 0, 0,
ax_anim 2, 0, 164, 0, -16, 0, 0,
ax_anim 3, 0, 164, 0, -20, 0, 0,
ax_anim 4, 0, 163, 0, -21, 0, 0,
ax_anim 4, 0, 165, 0, -23, 0, 0,
ax_anim 3, 0, 165, 0, -22, 0, 0,
ax_anim 2, 0, 165, 0, -18, 0, 0,
ax_anim 1, 0, 165, 0, -12, 0, 0,
ax_anim 2, 2, 165, 0, 0, 0, 0,
ax_anim_terminator
sSunkernAnims_11_6:
ax_anim 2, 0, 166, 0, 0, 0, 0,
ax_anim 1, 0, 168, 0, -10, 0, 0,
ax_anim 2, 0, 168, 0, -16, 0, 0,
ax_anim 3, 0, 168, 0, -20, 0, 0,
ax_anim 4, 0, 167, 0, -21, 0, 0,
ax_anim 4, 0, 169, 0, -22, 0, 0,
ax_anim 3, 0, 169, 0, -21, 0, 0,
ax_anim 2, 0, 169, 0, -17, 0, 0,
ax_anim 1, 0, 169, 0, -11, 0, 0,
ax_anim 2, 2, 169, 0, 0, 0, 0,
ax_anim_terminator
sSunkernAnims_11_7:
ax_anim 2, 0, 170, 0, 0, 0, 0,
ax_anim 1, 0, 172, 0, -10, 0, 0,
ax_anim 2, 0, 172, 0, -16, 0, 0,
ax_anim 3, 0, 172, 0, -20, 0, 0,
ax_anim 4, 0, 171, 0, -21, 0, 0,
ax_anim 4, 0, 173, 0, -23, 0, 0,
ax_anim 3, 0, 173, 0, -22, 0, 0,
ax_anim 2, 0, 173, 0, -18, 0, 0,
ax_anim 1, 0, 173, 0, -12, 0, 0,
ax_anim 2, 2, 173, 0, 0, 0, 0,
ax_anim_terminator
sSunkernAnims_11_8:
ax_anim 2, 0, 174, 0, 0, 0, 0,
ax_anim 1, 0, 176, 0, -10, 0, 0,
ax_anim 2, 0, 176, 0, -16, 0, 0,
ax_anim 3, 0, 176, 0, -20, 0, 0,
ax_anim 4, 0, 175, 0, -21, 0, 0,
ax_anim 4, 0, 177, 0, -23, 0, 0,
ax_anim 3, 0, 177, 0, -22, 0, 0,
ax_anim 2, 0, 177, 0, -18, 0, 0,
ax_anim 1, 0, 177, 0, -12, 0, 0,
ax_anim 2, 2, 177, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sSunkernAnims_12_1:
ax_anim 2, 0, 178, 1, 0, 1, 0,
ax_anim 2, 0, 178, 0, 0, 0, 0,
ax_anim 2, 0, 178, 1, 0, 1, 0,
ax_anim 2, 0, 178, 0, 0, 0, 0,
ax_anim 2, 0, 178, 1, 0, 1, 0,
ax_anim 2, 2, 178, 0, 0, 0, 0,
ax_anim 2, 0, 178, 1, 0, 1, 0,
ax_anim 2, 0, 178, 0, 0, 0, 0,
ax_anim 2, 0, 178, 1, 0, 1, 0,
ax_anim 2, 1, 178, 0, 0, 0, 0,
ax_anim_terminator
sSunkernAnims_12_2:
ax_anim 2, 0, 185, 1, -1, 1, 0,
ax_anim 2, 0, 185, 0, 0, 0, 0,
ax_anim 2, 0, 185, 1, -1, 1, 0,
ax_anim 2, 0, 185, 0, 0, 0, 0,
ax_anim 2, 0, 185, 1, -1, 1, 0,
ax_anim 2, 2, 185, 0, 0, 0, 0,
ax_anim 2, 0, 185, 1, -1, 1, 0,
ax_anim 2, 0, 185, 0, 0, 0, 0,
ax_anim 2, 0, 185, 1, -1, 1, 0,
ax_anim 2, 1, 185, 0, 0, 0, 0,
ax_anim_terminator
sSunkernAnims_12_3:
ax_anim 2, 0, 184, 0, -1, 0, -1,
ax_anim 2, 0, 184, 0, 0, 0, 0,
ax_anim 2, 0, 184, 0, -1, 0, -1,
ax_anim 2, 0, 184, 0, 0, 0, 0,
ax_anim 2, 0, 184, 0, -1, 0, -1,
ax_anim 2, 2, 184, 0, 0, 0, 0,
ax_anim 2, 0, 184, 0, -1, 0, -1,
ax_anim 2, 0, 184, 0, 0, 0, 0,
ax_anim 2, 0, 184, 0, -1, 0, -1,
ax_anim 2, 1, 184, 0, 0, 0, 0,
ax_anim_terminator
sSunkernAnims_12_4:
ax_anim 2, 0, 183, -1, -1, -1, -1,
ax_anim 2, 0, 183, 0, 0, 0, 0,
ax_anim 2, 0, 183, -1, -1, -1, -1,
ax_anim 2, 0, 183, 0, 0, 0, 0,
ax_anim 2, 0, 183, -1, -1, -1, -1,
ax_anim 2, 2, 183, 0, 0, 0, 0,
ax_anim 2, 0, 183, -1, -1, -1, -1,
ax_anim 2, 0, 183, 0, 0, 0, 0,
ax_anim 2, 0, 183, -1, -1, -1, -1,
ax_anim 2, 1, 183, 0, 0, 0, 0,
ax_anim_terminator
sSunkernAnims_12_5:
ax_anim 2, 0, 182, 1, 0, 1, 0,
ax_anim 2, 0, 182, 0, 0, 0, 0,
ax_anim 2, 0, 182, 1, 0, 1, 0,
ax_anim 2, 0, 182, 0, 0, 0, 0,
ax_anim 2, 0, 182, 1, 0, 1, 0,
ax_anim 2, 2, 182, 0, 0, 0, 0,
ax_anim 2, 0, 182, 1, 0, 1, 0,
ax_anim 2, 0, 182, 0, 0, 0, 0,
ax_anim 2, 0, 182, 1, 0, 1, 0,
ax_anim 2, 1, 182, 0, 0, 0, 0,
ax_anim_terminator
sSunkernAnims_12_6:
ax_anim 2, 0, 181, 1, -1, 1, -1,
ax_anim 2, 0, 181, 0, 0, 0, 0,
ax_anim 2, 0, 181, 1, -1, 1, -1,
ax_anim 2, 0, 181, 0, 0, 0, 0,
ax_anim 2, 0, 181, 1, -1, 1, -1,
ax_anim 2, 2, 181, 0, 0, 0, 0,
ax_anim 2, 0, 181, 1, -1, 1, -1,
ax_anim 2, 0, 181, 0, 0, 0, 0,
ax_anim 2, 0, 181, 1, -1, 1, -1,
ax_anim 2, 1, 181, 0, 0, 0, 0,
ax_anim_terminator
sSunkernAnims_12_7:
ax_anim 2, 0, 180, 0, -1, 0, -1,
ax_anim 2, 0, 180, 0, 0, 0, 0,
ax_anim 2, 0, 180, 0, -1, 0, -1,
ax_anim 2, 0, 180, 0, 0, 0, 0,
ax_anim 2, 0, 180, 0, -1, 0, -1,
ax_anim 2, 2, 180, 0, 0, 0, 0,
ax_anim 2, 0, 180, 0, -1, 0, -1,
ax_anim 2, 0, 180, 0, 0, 0, 0,
ax_anim 2, 0, 180, 0, -1, 0, -1,
ax_anim 2, 1, 180, 0, 0, 0, 0,
ax_anim_terminator
sSunkernAnims_12_8:
ax_anim 2, 0, 179, -1, -1, -1, -1,
ax_anim 2, 0, 179, 0, 0, 0, 0,
ax_anim 2, 0, 179, -1, -1, -1, -1,
ax_anim 2, 0, 179, 0, 0, 0, 0,
ax_anim 2, 0, 179, -1, -1, -1, -1,
ax_anim 2, 2, 179, 0, 0, 0, 0,
ax_anim 2, 0, 179, -1, -1, -1, -1,
ax_anim 2, 0, 179, 0, 0, 0, 0,
ax_anim 2, 0, 179, -1, -1, -1, -1,
ax_anim 2, 1, 179, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sSunkernAnims_13_1:
ax_anim 2, 0, 186, 0, 0, 0, 0,
ax_anim 2, 0, 187, 0, 0, 0, 0,
ax_anim 2, 0, 188, 0, 0, 0, 0,
ax_anim 2, 0, 189, 0, 0, 0, 0,
ax_anim 2, 0, 190, 0, 0, 0, 0,
ax_anim 2, 0, 191, 0, 0, 0, 0,
ax_anim 2, 0, 192, 0, 0, 0, 0,
ax_anim 2, 0, 193, 0, 0, 0, 0,
ax_anim 2, 2, 186, 0, 0, 0, 0,
ax_anim_terminator
sSunkernAnims_13_2:
ax_anim 2, 0, 193, 0, 0, 0, 0,
ax_anim 2, 0, 186, 0, 0, 0, 0,
ax_anim 2, 0, 187, 0, 0, 0, 0,
ax_anim 2, 0, 188, 0, 0, 0, 0,
ax_anim 2, 0, 189, 0, 0, 0, 0,
ax_anim 2, 0, 190, 0, 0, 0, 0,
ax_anim 2, 0, 191, 0, 0, 0, 0,
ax_anim 2, 0, 192, 0, 0, 0, 0,
ax_anim 2, 2, 193, 0, 0, 0, 0,
ax_anim_terminator
sSunkernAnims_13_3:
ax_anim 2, 0, 192, 0, 0, 0, 0,
ax_anim 2, 0, 193, 0, 0, 0, 0,
ax_anim 2, 0, 186, 0, 0, 0, 0,
ax_anim 2, 0, 187, 0, 0, 0, 0,
ax_anim 2, 0, 188, 0, 0, 0, 0,
ax_anim 2, 0, 189, 0, 0, 0, 0,
ax_anim 2, 0, 190, 0, 0, 0, 0,
ax_anim 2, 0, 191, 0, 0, 0, 0,
ax_anim 2, 2, 192, 0, 0, 0, 0,
ax_anim_terminator
sSunkernAnims_13_4:
ax_anim 2, 0, 191, 0, 0, 0, 0,
ax_anim 2, 0, 192, 0, 0, 0, 0,
ax_anim 2, 0, 193, 0, 0, 0, 0,
ax_anim 2, 0, 186, 0, 0, 0, 0,
ax_anim 2, 0, 187, 0, 0, 0, 0,
ax_anim 2, 0, 188, 0, 0, 0, 0,
ax_anim 2, 0, 189, 0, 0, 0, 0,
ax_anim 2, 0, 190, 0, 0, 0, 0,
ax_anim 2, 2, 191, 0, 0, 0, 0,
ax_anim_terminator
sSunkernAnims_13_5:
ax_anim 2, 0, 190, 0, 0, 0, 0,
ax_anim 2, 0, 191, 0, 0, 0, 0,
ax_anim 2, 0, 192, 0, 0, 0, 0,
ax_anim 2, 0, 193, 0, 0, 0, 0,
ax_anim 2, 0, 186, 0, 0, 0, 0,
ax_anim 2, 0, 187, 0, 0, 0, 0,
ax_anim 2, 0, 188, 0, 0, 0, 0,
ax_anim 2, 0, 189, 0, 0, 0, 0,
ax_anim 2, 2, 190, 0, 0, 0, 0,
ax_anim_terminator
sSunkernAnims_13_6:
ax_anim 2, 0, 189, 0, 0, 0, 0,
ax_anim 2, 0, 190, 0, 0, 0, 0,
ax_anim 2, 0, 191, 0, 0, 0, 0,
ax_anim 2, 0, 192, 0, 0, 0, 0,
ax_anim 2, 0, 193, 0, 0, 0, 0,
ax_anim 2, 0, 186, 0, 0, 0, 0,
ax_anim 2, 0, 187, 0, 0, 0, 0,
ax_anim 2, 0, 188, 0, 0, 0, 0,
ax_anim 2, 2, 189, 0, 0, 0, 0,
ax_anim_terminator
sSunkernAnims_13_7:
ax_anim 2, 0, 188, 0, 0, 0, 0,
ax_anim 2, 0, 189, 0, 0, 0, 0,
ax_anim 2, 0, 190, 0, 0, 0, 0,
ax_anim 2, 0, 191, 0, 0, 0, 0,
ax_anim 2, 0, 192, 0, 0, 0, 0,
ax_anim 2, 0, 193, 0, 0, 0, 0,
ax_anim 2, 0, 186, 0, 0, 0, 0,
ax_anim 2, 0, 187, 0, 0, 0, 0,
ax_anim 2, 2, 188, 0, 0, 0, 0,
ax_anim_terminator
sSunkernAnims_13_8:
ax_anim 2, 0, 187, 0, 0, 0, 0,
ax_anim 2, 0, 188, 0, 0, 0, 0,
ax_anim 2, 0, 189, 0, 0, 0, 0,
ax_anim 2, 0, 190, 0, 0, 0, 0,
ax_anim 2, 0, 191, 0, 0, 0, 0,
ax_anim 2, 0, 192, 0, 0, 0, 0,
ax_anim 2, 0, 193, 0, 0, 0, 0,
ax_anim 2, 0, 186, 0, 0, 0, 0,
ax_anim 2, 2, 187, 0, 0, 0, 0,
ax_anim_terminator
sSunkernGfx1:
.incbin "baserom.gba", 0xD39C58, 0x200
sSunkernSprites1:
ax_sprite sSunkernGfx1, 0x200
ax_sprite_terminator
sSunkernGfx2:
.incbin "baserom.gba", 0xD39E68, 0x200
sSunkernSprites2:
ax_sprite sSunkernGfx2, 0x200
ax_sprite_terminator
sSunkernGfx3:
.incbin "baserom.gba", 0xD3A078, 0x200
sSunkernSprites3:
ax_sprite sSunkernGfx3, 0x200
ax_sprite_terminator
sSunkernGfx4:
.incbin "baserom.gba", 0xD3A288, 0x100
sSunkernSprites4:
ax_sprite sSunkernGfx4, 0x100
ax_sprite_terminator
sSunkernGfx5:
.incbin "baserom.gba", 0xD3A398, 0x200
sSunkernSprites5:
ax_sprite sSunkernGfx5, 0x200
ax_sprite_terminator
sSunkernGfx6:
.incbin "baserom.gba", 0xD3A5A8, 0x100
sSunkernSprites6:
ax_sprite sSunkernGfx6, 0x100
ax_sprite_terminator
sSunkernGfx7:
.incbin "baserom.gba", 0xD3A6B8, 0x100
sSunkernSprites7:
ax_sprite sSunkernGfx7, 0x100
ax_sprite_terminator
sSunkernGfx8:
.incbin "baserom.gba", 0xD3A7C8, 0x100
sSunkernSprites8:
ax_sprite sSunkernGfx8, 0x100
ax_sprite_terminator
sSunkernGfx9:
.incbin "baserom.gba", 0xD3A8D8, 0x100
sSunkernSprites9:
ax_sprite sSunkernGfx9, 0x100
ax_sprite_terminator
sSunkernGfx10:
.incbin "baserom.gba", 0xD3A9E8, 0x100
sSunkernSprites10:
ax_sprite sSunkernGfx10, 0x100
ax_sprite_terminator
sSunkernGfx11:
.incbin "baserom.gba", 0xD3AAF8, 0x100
sSunkernSprites11:
ax_sprite sSunkernGfx11, 0x100
ax_sprite_terminator
sSunkernGfx12:
.incbin "baserom.gba", 0xD3AC08, 0x100
sSunkernSprites12:
ax_sprite sSunkernGfx12, 0x100
ax_sprite_terminator
sSunkernGfx13:
.incbin "baserom.gba", 0xD3AD18, 0x200
sSunkernSprites13:
ax_sprite sSunkernGfx13, 0x200
ax_sprite_terminator
sSunkernGfx14:
.incbin "baserom.gba", 0xD3AF28, 0x200
sSunkernSprites14:
ax_sprite sSunkernGfx14, 0x200
ax_sprite_terminator
sSunkernGfx15:
.incbin "baserom.gba", 0xD3B138, 0x200
sSunkernSprites15:
ax_sprite sSunkernGfx15, 0x200
ax_sprite_terminator
sSunkernGfx16:
.incbin "baserom.gba", 0xD3B348, 0xC0
sSunkernSprites16:
ax_sprite sSunkernGfx16, 0xc0
ax_sprite 0, 0x40
ax_sprite_terminator
sSunkernGfx17:
.incbin "baserom.gba", 0xD3B420, 0xC0
sSunkernSprites17:
ax_sprite sSunkernGfx17, 0xc0
ax_sprite 0, 0x40
ax_sprite_terminator
sSunkernGfx18:
.incbin "baserom.gba", 0xD3B4F8, 0x20
sSunkernGfx18_1:
.incbin "baserom.gba", 0xD3B518, 0x80
sSunkernSprites18:
ax_sprite sSunkernGfx18, 0x20
ax_sprite 0, 0x20
ax_sprite sSunkernGfx18_1, 0x80
ax_sprite 0, 0x40
ax_sprite_terminator
sSunkernGfx19:
.incbin "baserom.gba", 0xD3B5C0, 0xC0
sSunkernSprites19:
ax_sprite sSunkernGfx19, 0xc0
ax_sprite 0, 0x40
ax_sprite_terminator
sSunkernGfx20:
.incbin "baserom.gba", 0xD3B698, 0xC0
sSunkernSprites20:
ax_sprite sSunkernGfx20, 0xc0
ax_sprite 0, 0x40
ax_sprite_terminator
sSunkernGfx21:
.incbin "baserom.gba", 0xD3B770, 0x100
sSunkernSprites21:
ax_sprite sSunkernGfx21, 0x100
ax_sprite_terminator
sSunkernGfx22:
.incbin "baserom.gba", 0xD3B880, 0x100
sSunkernSprites22:
ax_sprite sSunkernGfx22, 0x100
ax_sprite_terminator
sSunkernGfx23:
.incbin "baserom.gba", 0xD3B990, 0x200
sSunkernSprites23:
ax_sprite sSunkernGfx23, 0x200
ax_sprite_terminator
sSunkernGfx24:
.incbin "baserom.gba", 0xD3BBA0, 0x200
sSunkernSprites24:
ax_sprite sSunkernGfx24, 0x200
ax_sprite_terminator
sSunkernGfx25:
.incbin "baserom.gba", 0xD3BDB0, 0x200
sSunkernSprites25:
ax_sprite sSunkernGfx25, 0x200
ax_sprite_terminator
sSunkernGfx26:
.incbin "baserom.gba", 0xD3BFC0, 0x200
sSunkernSprites26:
ax_sprite sSunkernGfx26, 0x200
ax_sprite_terminator
sSunkernGfx27:
.incbin "baserom.gba", 0xD3C1D0, 0x200
sSunkernSprites27:
ax_sprite sSunkernGfx27, 0x200
ax_sprite_terminator
sAxPosesSunkern:
.4byte sSunkernPose1
.4byte sSunkernPose2
.4byte sSunkernPose3
.4byte sSunkernPose4
.4byte sSunkernPose5
.4byte sSunkernPose6
.4byte sSunkernPose7
.4byte sSunkernPose8
.4byte sSunkernPose9
.4byte sSunkernPose10
.4byte sSunkernPose11
.4byte sSunkernPose12
.4byte sSunkernPose13
.4byte sSunkernPose14
.4byte sSunkernPose15
.4byte sSunkernPose16
.4byte sSunkernPose17
.4byte sSunkernPose18
.4byte sSunkernPose19
.4byte sSunkernPose20
.4byte sSunkernPose21
.4byte sSunkernPose22
.4byte sSunkernPose23
.4byte sSunkernPose24
.4byte sSunkernPose25
.4byte sSunkernPose26
.4byte sSunkernPose27
.4byte sSunkernPose28
.4byte sSunkernPose29
.4byte sSunkernPose30
.4byte sSunkernPose31
.4byte sSunkernPose32
.4byte sSunkernPose33
.4byte sSunkernPose34
.4byte sSunkernPose35
.4byte sSunkernPose36
.4byte sSunkernPose37
.4byte sSunkernPose38
.4byte sSunkernPose39
.4byte sSunkernPose40
.4byte sSunkernPose41
.4byte sSunkernPose42
.4byte sSunkernPose43
.4byte sSunkernPose44
.4byte sSunkernPose45
.4byte sSunkernPose46
.4byte sSunkernPose47
.4byte sSunkernPose48
.4byte sSunkernPose49
.4byte sSunkernPose50
.4byte sSunkernPose51
.4byte sSunkernPose52
.4byte sSunkernPose53
.4byte sSunkernPose54
.4byte sSunkernPose55
.4byte sSunkernPose56
.4byte sSunkernPose57
.4byte sSunkernPose58
.4byte sSunkernPose59
.4byte sSunkernPose60
.4byte sSunkernPose61
.4byte sSunkernPose62
.4byte sSunkernPose63
.4byte sSunkernPose64
.4byte sSunkernPose65
.4byte sSunkernPose66
.4byte sSunkernPose67
.4byte sSunkernPose68
.4byte sSunkernPose69
.4byte sSunkernPose70
.4byte sSunkernPose71
.4byte sSunkernPose72
.4byte sSunkernPose73
.4byte sSunkernPose74
.4byte sSunkernPose75
.4byte sSunkernPose76
.4byte sSunkernPose77
.4byte sSunkernPose78
.4byte sSunkernPose79
.4byte sSunkernPose80
.4byte sSunkernPose81
.4byte sSunkernPose82
.4byte sSunkernPose83
.4byte sSunkernPose84
.4byte sSunkernPose85
.4byte sSunkernPose86
.4byte sSunkernPose87
.4byte sSunkernPose88
.4byte sSunkernPose89
.4byte sSunkernPose90
.4byte sSunkernPose91
.4byte sSunkernPose92
.4byte sSunkernPose93
.4byte sSunkernPose94
.4byte sSunkernPose95
.4byte sSunkernPose96
.4byte sSunkernPose97
.4byte sSunkernPose98
.4byte sSunkernPose99
.4byte sSunkernPose100
.4byte sSunkernPose101
.4byte sSunkernPose102
.4byte sSunkernPose103
.4byte sSunkernPose104
.4byte sSunkernPose105
.4byte sSunkernPose106
.4byte sSunkernPose107
.4byte sSunkernPose108
.4byte sSunkernPose109
.4byte sSunkernPose110
.4byte sSunkernPose111
.4byte sSunkernPose112
.4byte sSunkernPose113
.4byte sSunkernPose114
.4byte sSunkernPose115
.4byte sSunkernPose116
.4byte sSunkernPose117
.4byte sSunkernPose118
.4byte sSunkernPose119
.4byte sSunkernPose120
.4byte sSunkernPose121
.4byte sSunkernPose122
.4byte sSunkernPose123
.4byte sSunkernPose124
.4byte sSunkernPose125
.4byte sSunkernPose126
.4byte sSunkernPose127
.4byte sSunkernPose128
.4byte sSunkernPose129
.4byte sSunkernPose130
.4byte sSunkernPose131
.4byte sSunkernPose132
.4byte sSunkernPose133
.4byte sSunkernPose134
.4byte sSunkernPose135
.4byte sSunkernPose136
.4byte sSunkernPose137
.4byte sSunkernPose138
.4byte sSunkernPose139
.4byte sSunkernPose140
.4byte sSunkernPose141
.4byte sSunkernPose142
.4byte sSunkernPose143
.4byte sSunkernPose144
.4byte sSunkernPose145
.4byte sSunkernPose146
.4byte sSunkernPose147
.4byte sSunkernPose148
.4byte sSunkernPose149
.4byte sSunkernPose150
.4byte sSunkernPose151
.4byte sSunkernPose152
.4byte sSunkernPose153
.4byte sSunkernPose154
.4byte sSunkernPose155
.4byte sSunkernPose156
.4byte sSunkernPose157
.4byte sSunkernPose158
.4byte sSunkernPose159
.4byte sSunkernPose160
.4byte sSunkernPose161
.4byte sSunkernPose162
.4byte sSunkernPose163
.4byte sSunkernPose164
.4byte sSunkernPose165
.4byte sSunkernPose166
.4byte sSunkernPose167
.4byte sSunkernPose168
.4byte sSunkernPose169
.4byte sSunkernPose170
.4byte sSunkernPose171
.4byte sSunkernPose172
.4byte sSunkernPose173
.4byte sSunkernPose174
.4byte sSunkernPose175
.4byte sSunkernPose176
.4byte sSunkernPose177
.4byte sSunkernPose178
.4byte sSunkernPose179
.4byte sSunkernPose180
.4byte sSunkernPose181
.4byte sSunkernPose182
.4byte sSunkernPose183
.4byte sSunkernPose184
.4byte sSunkernPose185
.4byte sSunkernPose186
.4byte sSunkernPose187
.4byte sSunkernPose188
.4byte sSunkernPose189
.4byte sSunkernPose190
.4byte sSunkernPose191
.4byte sSunkernPose192
.4byte sSunkernPose193
.4byte sSunkernPose194
sAxPositionsSunkern:
.2byte   -1,   -4, 	  -8,  -15, 	   6,  -15, 	  -1,   -5
.2byte   -1,   -4, 	  -7,  -19, 	   5,  -19, 	  -1,   -5
.2byte   -1,   -4, 	  -8,  -13, 	   6,  -13, 	  -1,   -5
.2byte    1,   -4, 	   3,  -17, 	  -6,  -13, 	  -1,   -6
.2byte    1,   -4, 	   4,  -20, 	  -7,  -17, 	  -1,   -6
.2byte    1,   -4, 	   3,  -15, 	  -6,  -12, 	   0,   -5
.2byte    2,   -4, 	  -1,  -18, 	  -1,  -11, 	  -1,   -6
.2byte    2,   -4, 	  -1,  -20, 	  -1,  -15, 	  -1,   -6
.2byte    2,   -4, 	  -1,  -17, 	  -1,  -10, 	  -1,   -6
.2byte   -1,   -6, 	  -4,  -17, 	   4,  -13, 	  -2,   -6
.2byte   -1,   -6, 	  -4,  -18, 	   4,  -17, 	  -2,   -6
.2byte   -1,   -6, 	  -5,  -16, 	   4,  -11, 	  -2,   -6
.2byte   -1,   -7, 	   6,  -15, 	  -8,  -15, 	  -1,   -6
.2byte   -1,   -7, 	   5,  -19, 	  -7,  -19, 	  -1,   -6
.2byte   -1,   -7, 	   6,  -13, 	  -7,  -13, 	  -1,   -6
.2byte   -1,   -6, 	   2,  -17, 	  -6,  -13, 	   0,   -6
.2byte   -1,   -6, 	   2,  -18, 	  -6,  -17, 	   0,   -6
.2byte   -1,   -6, 	   3,  -16, 	  -6,  -11, 	   0,   -6
.2byte   -4,   -4, 	  -1,  -18, 	  -1,  -11, 	  -1,   -6
.2byte   -4,   -4, 	  -1,  -20, 	  -1,  -15, 	  -1,   -6
.2byte   -4,   -4, 	  -1,  -17, 	  -1,  -10, 	  -1,   -6
.2byte   -3,   -4, 	  -5,  -17, 	   4,  -13, 	  -1,   -6
.2byte   -3,   -4, 	  -6,  -20, 	   5,  -17, 	  -1,   -6
.2byte   -3,   -4, 	  -5,  -15, 	   4,  -12, 	  -2,   -5
.2byte   -1,   -4, 	  -8,  -15, 	   6,  -15, 	  -1,   -5
.2byte   -1,   -4, 	  -7,  -19, 	   5,  -19, 	  -1,   -5
.2byte   -1,   -4, 	  -8,  -13, 	   6,  -13, 	  -1,   -5
.2byte    1,   -4, 	   3,  -17, 	  -6,  -13, 	  -1,   -6
.2byte    1,   -4, 	   4,  -20, 	  -7,  -17, 	  -1,   -6
.2byte    1,   -4, 	   3,  -15, 	  -6,  -12, 	   0,   -5
.2byte    2,   -4, 	  -1,  -18, 	  -1,  -11, 	  -1,   -6
.2byte    2,   -4, 	  -1,  -20, 	  -1,  -15, 	  -1,   -6
.2byte    2,   -4, 	  -1,  -17, 	  -1,  -10, 	  -1,   -6
.2byte   -1,   -6, 	  -4,  -17, 	   4,  -13, 	  -2,   -6
.2byte   -1,   -6, 	  -4,  -18, 	   4,  -17, 	  -2,   -6
.2byte   -1,   -6, 	  -5,  -16, 	   4,  -11, 	  -2,   -6
.2byte   -1,   -7, 	   6,  -15, 	  -8,  -15, 	  -1,   -6
.2byte   -1,   -7, 	   5,  -19, 	  -7,  -19, 	  -1,   -6
.2byte   -1,   -7, 	   6,  -13, 	  -7,  -13, 	  -1,   -6
.2byte   -1,   -6, 	   2,  -17, 	  -6,  -13, 	   0,   -6
.2byte   -1,   -6, 	   2,  -18, 	  -6,  -17, 	   0,   -6
.2byte   -1,   -6, 	   3,  -16, 	  -6,  -11, 	   0,   -6
.2byte   -4,   -4, 	  -1,  -18, 	  -1,  -11, 	  -1,   -6
.2byte   -4,   -4, 	  -1,  -20, 	  -1,  -15, 	  -1,   -6
.2byte   -4,   -4, 	  -1,  -17, 	  -1,  -10, 	  -1,   -6
.2byte   -3,   -4, 	  -5,  -17, 	   4,  -13, 	  -1,   -6
.2byte   -3,   -4, 	  -6,  -20, 	   5,  -17, 	  -1,   -6
.2byte   -3,   -4, 	  -5,  -15, 	   4,  -12, 	  -2,   -5
.2byte   -1,   -4, 	  -8,  -15, 	   6,  -15, 	  -1,   -5
.2byte   -1,   -4, 	  -7,  -19, 	   5,  -19, 	  -1,   -5
.2byte   -1,   -4, 	  -8,  -13, 	   6,  -13, 	  -1,   -5
.2byte    1,   -4, 	   3,  -17, 	  -6,  -13, 	  -1,   -6
.2byte    1,   -4, 	   4,  -20, 	  -7,  -17, 	  -1,   -6
.2byte    1,   -4, 	   3,  -15, 	  -6,  -12, 	   0,   -5
.2byte    2,   -4, 	  -1,  -18, 	  -1,  -11, 	  -1,   -6
.2byte    2,   -4, 	  -1,  -20, 	  -1,  -15, 	  -1,   -6
.2byte    2,   -4, 	  -1,  -17, 	  -1,  -10, 	  -1,   -6
.2byte   -1,   -6, 	  -4,  -17, 	   4,  -13, 	  -2,   -6
.2byte   -1,   -6, 	  -4,  -18, 	   4,  -17, 	  -2,   -6
.2byte   -1,   -6, 	  -5,  -16, 	   4,  -11, 	  -2,   -6
.2byte   -1,   -7, 	   6,  -15, 	  -8,  -15, 	  -1,   -6
.2byte   -1,   -7, 	   5,  -19, 	  -7,  -19, 	  -1,   -6
.2byte   -1,   -7, 	   6,  -13, 	  -7,  -13, 	  -1,   -6
.2byte   -1,   -6, 	   2,  -17, 	  -6,  -13, 	   0,   -6
.2byte   -1,   -6, 	   2,  -18, 	  -6,  -17, 	   0,   -6
.2byte   -1,   -6, 	   3,  -16, 	  -6,  -11, 	   0,   -6
.2byte   -4,   -4, 	  -1,  -18, 	  -1,  -11, 	  -1,   -6
.2byte   -4,   -4, 	  -1,  -20, 	  -1,  -15, 	  -1,   -6
.2byte   -4,   -4, 	  -1,  -17, 	  -1,  -10, 	  -1,   -6
.2byte   -3,   -4, 	  -5,  -17, 	   4,  -13, 	  -1,   -6
.2byte   -3,   -4, 	  -6,  -20, 	   5,  -17, 	  -1,   -6
.2byte   -3,   -4, 	  -5,  -15, 	   4,  -12, 	  -2,   -5
.2byte   -1,   -4, 	  -8,  -15, 	   6,  -15, 	  -1,   -5
.2byte   -3,   -4, 	  -5,  -17, 	   4,  -13, 	  -1,   -6
.2byte   -4,   -4, 	  -1,  -18, 	  -1,  -11, 	  -1,   -6
.2byte   -1,   -6, 	   2,  -17, 	  -6,  -13, 	   0,   -6
.2byte   -1,   -7, 	   6,  -15, 	  -8,  -15, 	  -1,   -6
.2byte   -1,   -6, 	  -4,  -17, 	   4,  -13, 	  -2,   -6
.2byte    2,   -4, 	  -1,  -18, 	  -1,  -11, 	  -1,   -6
.2byte    1,   -4, 	   3,  -17, 	  -6,  -13, 	  -1,   -6
.2byte   -1,   -6, 	  -4,  -19, 	   2,  -19, 	  -1,   -7
.2byte   -3,   -5, 	  -6,  -20, 	  -1,  -18, 	  -2,   -6
.2byte   -5,   -5, 	  -4,  -21, 	  -4,  -18, 	  -2,   -6
.2byte   -3,   -8, 	  -1,  -20, 	  -6,  -18, 	  -2,   -7
.2byte   -1,   -8, 	   3,  -21, 	  -5,  -21, 	  -1,   -7
.2byte    0,   -8, 	  -2,  -20, 	   3,  -18, 	  -1,   -7
.2byte    3,   -5, 	   2,  -21, 	   2,  -18, 	   0,   -6
.2byte    1,   -5, 	   4,  -20, 	  -1,  -18, 	   0,   -6
.2byte   -1,   -4, 	  -8,  -15, 	   6,  -15, 	  -1,   -5
.2byte   -3,   -4, 	  -5,  -17, 	   4,  -13, 	  -1,   -6
.2byte   -4,   -4, 	  -1,  -18, 	  -1,  -11, 	  -1,   -6
.2byte   -1,   -6, 	   2,  -17, 	  -6,  -13, 	   0,   -6
.2byte   -1,   -7, 	   6,  -15, 	  -8,  -15, 	  -1,   -6
.2byte   -1,   -6, 	  -4,  -17, 	   4,  -13, 	  -2,   -6
.2byte    2,   -4, 	  -1,  -18, 	  -1,  -11, 	  -1,   -6
.2byte    1,   -4, 	   3,  -17, 	  -6,  -13, 	  -1,   -6
.2byte   -3,   -4, 	  -5,  -15, 	   4,  -10, 	  -1,   -6
.2byte   -3,   -4, 	  -5,  -14, 	   4,  -10, 	  -1,   -6
.2byte    0,   -7, 	  -6,  -20, 	   7,  -20, 	   0,   -8
.2byte    2,   -8, 	  -7,  -22, 	 -13,  -12, 	   0,   -9
.2byte    2,   -8, 	 -11,  -18, 	  -8,  -15, 	  -2,   -8
.2byte    1,  -10, 	  -9,  -20, 	   1,  -17, 	  -1,   -8
.2byte    0,   -8, 	   7,  -19, 	  -7,  -19, 	   0,   -7
.2byte   -2,  -10, 	   8,  -20, 	  -2,  -17, 	   0,   -8
.2byte   -3,   -8, 	  10,  -18, 	   7,  -15, 	   1,   -8
.2byte   -3,   -8, 	   6,  -22, 	  12,  -12, 	  -1,   -9
.2byte   -1,   -4, 	  -8,  -15, 	   6,  -15, 	  -1,   -5
.2byte   -1,   -4, 	  -7,  -19, 	   5,  -19, 	  -1,   -5
.2byte   -1,   -4, 	  -8,  -13, 	   6,  -13, 	  -1,   -5
.2byte    1,   -4, 	   3,  -17, 	  -6,  -13, 	  -1,   -6
.2byte    1,   -4, 	   4,  -20, 	  -7,  -17, 	  -1,   -6
.2byte    1,   -4, 	   3,  -15, 	  -6,  -12, 	   0,   -5
.2byte    2,   -4, 	  -1,  -18, 	  -1,  -11, 	  -1,   -6
.2byte    2,   -4, 	  -1,  -20, 	  -1,  -15, 	  -1,   -6
.2byte    2,   -4, 	  -1,  -17, 	  -1,  -10, 	  -1,   -6
.2byte   -1,   -6, 	  -4,  -17, 	   4,  -13, 	  -2,   -6
.2byte   -1,   -6, 	  -4,  -18, 	   4,  -17, 	  -2,   -6
.2byte   -1,   -6, 	  -5,  -16, 	   4,  -11, 	  -2,   -6
.2byte   -1,   -7, 	   6,  -15, 	  -8,  -15, 	  -1,   -6
.2byte   -1,   -7, 	   5,  -19, 	  -7,  -19, 	  -1,   -6
.2byte   -1,   -7, 	   6,  -13, 	  -7,  -13, 	  -1,   -6
.2byte   -1,   -6, 	   2,  -17, 	  -6,  -13, 	   0,   -6
.2byte   -1,   -6, 	   2,  -18, 	  -6,  -17, 	   0,   -6
.2byte   -1,   -6, 	   3,  -16, 	  -6,  -11, 	   0,   -6
.2byte   -4,   -4, 	  -1,  -18, 	  -1,  -11, 	  -1,   -6
.2byte   -4,   -4, 	  -1,  -20, 	  -1,  -15, 	  -1,   -6
.2byte   -4,   -4, 	  -1,  -17, 	  -1,  -10, 	  -1,   -6
.2byte   -3,   -4, 	  -5,  -17, 	   4,  -13, 	  -1,   -6
.2byte   -3,   -4, 	  -6,  -20, 	   5,  -17, 	  -1,   -6
.2byte   -3,   -4, 	  -5,  -15, 	   4,  -12, 	  -2,   -5
.2byte   -1,   -4, 	  -8,  -15, 	   6,  -15, 	  -1,   -5
.2byte   -3,   -4, 	  -5,  -17, 	   4,  -13, 	  -1,   -6
.2byte   -4,   -4, 	  -1,  -18, 	  -1,  -11, 	  -1,   -6
.2byte   -1,   -6, 	   2,  -17, 	  -6,  -13, 	   0,   -6
.2byte   -1,   -7, 	   6,  -15, 	  -8,  -15, 	  -1,   -6
.2byte   -1,   -6, 	  -4,  -17, 	   4,  -13, 	  -2,   -6
.2byte    2,   -4, 	  -1,  -18, 	  -1,  -11, 	  -1,   -6
.2byte    1,   -4, 	   3,  -17, 	  -6,  -13, 	  -1,   -6
.2byte   -1,   -6, 	  -4,  -19, 	   2,  -19, 	  -1,   -7
.2byte    1,   -5, 	   4,  -20, 	  -1,  -18, 	   0,   -6
.2byte    3,   -5, 	   2,  -21, 	   2,  -18, 	   0,   -6
.2byte    0,   -8, 	  -2,  -20, 	   3,  -18, 	  -1,   -7
.2byte   -1,   -8, 	   3,  -21, 	  -5,  -21, 	  -1,   -7
.2byte   -3,   -8, 	  -1,  -20, 	  -6,  -18, 	  -2,   -7
.2byte   -5,   -5, 	  -4,  -21, 	  -4,  -18, 	  -2,   -6
.2byte   -3,   -5, 	  -6,  -20, 	  -1,  -18, 	  -2,   -6
.2byte   -1,   -4, 	  -8,  -15, 	   6,  -15, 	  -1,   -5
.2byte   -1,   -4, 	  -7,  -19, 	   5,  -19, 	  -1,   -5
.2byte   -1,   -4, 	  -8,  -13, 	   6,  -13, 	  -1,   -5
.2byte   -1,   -6, 	  -4,  -19, 	   2,  -19, 	  -1,   -7
.2byte    1,   -4, 	   3,  -17, 	  -6,  -13, 	  -1,   -6
.2byte    1,   -4, 	   4,  -20, 	  -7,  -17, 	  -1,   -6
.2byte    1,   -4, 	   3,  -15, 	  -6,  -12, 	   0,   -5
.2byte    1,   -5, 	   4,  -20, 	  -1,  -18, 	   0,   -6
.2byte    2,   -4, 	  -1,  -18, 	  -1,  -11, 	  -1,   -6
.2byte    2,   -4, 	  -1,  -20, 	  -1,  -15, 	  -1,   -6
.2byte    2,   -4, 	  -1,  -17, 	  -1,  -10, 	  -1,   -6
.2byte    2,   -5, 	   1,  -21, 	   1,  -18, 	  -1,   -6
.2byte   -1,   -6, 	  -4,  -17, 	   4,  -13, 	  -2,   -6
.2byte   -1,   -6, 	  -4,  -18, 	   4,  -17, 	  -2,   -6
.2byte   -1,   -6, 	  -5,  -16, 	   4,  -11, 	  -2,   -6
.2byte    0,   -8, 	  -2,  -20, 	   3,  -18, 	  -1,   -7
.2byte   -1,   -7, 	   6,  -15, 	  -8,  -15, 	  -1,   -6
.2byte   -1,   -7, 	   5,  -19, 	  -7,  -19, 	  -1,   -6
.2byte   -1,   -7, 	   6,  -13, 	  -7,  -13, 	  -1,   -6
.2byte   -1,   -8, 	   3,  -21, 	  -5,  -21, 	  -1,   -7
.2byte   -1,   -6, 	   2,  -17, 	  -6,  -13, 	   0,   -6
.2byte   -1,   -6, 	   2,  -18, 	  -6,  -17, 	   0,   -6
.2byte   -1,   -6, 	   3,  -16, 	  -6,  -11, 	   0,   -6
.2byte   -2,   -8, 	   0,  -20, 	  -5,  -18, 	  -1,   -7
.2byte   -4,   -4, 	  -1,  -18, 	  -1,  -11, 	  -1,   -6
.2byte   -4,   -4, 	  -1,  -20, 	  -1,  -15, 	  -1,   -6
.2byte   -4,   -4, 	  -1,  -17, 	  -1,  -10, 	  -1,   -6
.2byte   -4,   -5, 	  -3,  -21, 	  -3,  -18, 	  -1,   -6
.2byte   -3,   -4, 	  -5,  -17, 	   4,  -13, 	  -1,   -6
.2byte   -3,   -4, 	  -6,  -20, 	   5,  -17, 	  -1,   -6
.2byte   -3,   -4, 	  -5,  -15, 	   4,  -12, 	  -2,   -5
.2byte   -3,   -5, 	  -6,  -20, 	  -1,  -18, 	  -2,   -6
.2byte   -1,   -6, 	  -4,  -19, 	   2,  -19, 	  -1,   -7
.2byte   -3,   -5, 	  -6,  -20, 	  -1,  -18, 	  -2,   -6
.2byte   -5,   -5, 	  -4,  -21, 	  -4,  -18, 	  -2,   -6
.2byte   -3,   -8, 	  -1,  -20, 	  -6,  -18, 	  -2,   -7
.2byte   -1,   -8, 	   3,  -21, 	  -5,  -21, 	  -1,   -7
.2byte    0,   -8, 	  -2,  -20, 	   3,  -18, 	  -1,   -7
.2byte    3,   -5, 	   2,  -21, 	   2,  -18, 	   0,   -6
.2byte    1,   -5, 	   4,  -20, 	  -1,  -18, 	   0,   -6
.2byte   -1,   -4, 	  -8,  -15, 	   6,  -15, 	  -1,   -5
.2byte   -3,   -4, 	  -5,  -17, 	   4,  -13, 	  -1,   -6
.2byte   -4,   -4, 	  -1,  -18, 	  -1,  -11, 	  -1,   -6
.2byte   -1,   -6, 	   2,  -17, 	  -6,  -13, 	   0,   -6
.2byte   -1,   -7, 	   6,  -15, 	  -8,  -15, 	  -1,   -6
.2byte   -1,   -6, 	  -4,  -17, 	   4,  -13, 	  -2,   -6
.2byte    2,   -4, 	  -1,  -18, 	  -1,  -11, 	  -1,   -6
.2byte    1,   -4, 	   3,  -17, 	  -6,  -13, 	  -1,   -6
sSunkernAnimTable1:
.4byte sSunkernAnims_1_1
.4byte sSunkernAnims_1_2
.4byte sSunkernAnims_1_3
.4byte sSunkernAnims_1_4
.4byte sSunkernAnims_1_5
.4byte sSunkernAnims_1_6
.4byte sSunkernAnims_1_7
.4byte sSunkernAnims_1_8
sSunkernAnimTable2:
.4byte sSunkernAnims_2_1
.4byte sSunkernAnims_2_2
.4byte sSunkernAnims_2_3
.4byte sSunkernAnims_2_4
.4byte sSunkernAnims_2_5
.4byte sSunkernAnims_2_6
.4byte sSunkernAnims_2_7
.4byte sSunkernAnims_2_8
sSunkernAnimTable3:
.4byte sSunkernAnims_3_1
.4byte sSunkernAnims_3_2
.4byte sSunkernAnims_3_3
.4byte sSunkernAnims_3_4
.4byte sSunkernAnims_3_5
.4byte sSunkernAnims_3_6
.4byte sSunkernAnims_3_7
.4byte sSunkernAnims_3_8
sSunkernAnimTable4:
.4byte sSunkernAnims_4_1
.4byte sSunkernAnims_4_2
.4byte sSunkernAnims_4_3
.4byte sSunkernAnims_4_4
.4byte sSunkernAnims_4_5
.4byte sSunkernAnims_4_6
.4byte sSunkernAnims_4_7
.4byte sSunkernAnims_4_8
sSunkernAnimTable5:
.4byte sSunkernAnims_5_1
.4byte sSunkernAnims_5_2
.4byte sSunkernAnims_5_3
.4byte sSunkernAnims_5_4
.4byte sSunkernAnims_5_5
.4byte sSunkernAnims_5_6
.4byte sSunkernAnims_5_7
.4byte sSunkernAnims_5_8
sSunkernAnimTable6:
.4byte sSunkernAnims_6_1
.4byte sSunkernAnims_6_1
.4byte sSunkernAnims_6_1
.4byte sSunkernAnims_6_1
.4byte sSunkernAnims_6_1
.4byte sSunkernAnims_6_1
.4byte sSunkernAnims_6_1
.4byte sSunkernAnims_6_1
sSunkernAnimTable7:
.4byte sSunkernAnims_7_1
.4byte sSunkernAnims_7_2
.4byte sSunkernAnims_7_3
.4byte sSunkernAnims_7_4
.4byte sSunkernAnims_7_5
.4byte sSunkernAnims_7_6
.4byte sSunkernAnims_7_7
.4byte sSunkernAnims_7_8
sSunkernAnimTable8:
.4byte sSunkernAnims_8_1
.4byte sSunkernAnims_8_2
.4byte sSunkernAnims_8_3
.4byte sSunkernAnims_8_4
.4byte sSunkernAnims_8_5
.4byte sSunkernAnims_8_6
.4byte sSunkernAnims_8_7
.4byte sSunkernAnims_8_8
sSunkernAnimTable9:
.4byte sSunkernAnims_9_1
.4byte sSunkernAnims_9_2
.4byte sSunkernAnims_9_3
.4byte sSunkernAnims_9_4
.4byte sSunkernAnims_9_5
.4byte sSunkernAnims_9_6
.4byte sSunkernAnims_9_7
.4byte sSunkernAnims_9_8
sSunkernAnimTable10:
.4byte sSunkernAnims_10_1
.4byte sSunkernAnims_10_2
.4byte sSunkernAnims_10_3
.4byte sSunkernAnims_10_4
.4byte sSunkernAnims_10_5
.4byte sSunkernAnims_10_6
.4byte sSunkernAnims_10_7
.4byte sSunkernAnims_10_8
sSunkernAnimTable11:
.4byte sSunkernAnims_11_1
.4byte sSunkernAnims_11_2
.4byte sSunkernAnims_11_3
.4byte sSunkernAnims_11_4
.4byte sSunkernAnims_11_5
.4byte sSunkernAnims_11_6
.4byte sSunkernAnims_11_7
.4byte sSunkernAnims_11_8
sSunkernAnimTable12:
.4byte sSunkernAnims_12_1
.4byte sSunkernAnims_12_2
.4byte sSunkernAnims_12_3
.4byte sSunkernAnims_12_4
.4byte sSunkernAnims_12_5
.4byte sSunkernAnims_12_6
.4byte sSunkernAnims_12_7
.4byte sSunkernAnims_12_8
sSunkernAnimTable13:
.4byte sSunkernAnims_13_1
.4byte sSunkernAnims_13_2
.4byte sSunkernAnims_13_3
.4byte sSunkernAnims_13_4
.4byte sSunkernAnims_13_5
.4byte sSunkernAnims_13_6
.4byte sSunkernAnims_13_7
.4byte sSunkernAnims_13_8
sAxAnimationsSunkern:
.4byte sSunkernAnimTable1
.4byte sSunkernAnimTable2
.4byte sSunkernAnimTable3
.4byte sSunkernAnimTable4
.4byte sSunkernAnimTable5
.4byte sSunkernAnimTable6
.4byte sSunkernAnimTable7
.4byte sSunkernAnimTable8
.4byte sSunkernAnimTable9
.4byte sSunkernAnimTable10
.4byte sSunkernAnimTable11
.4byte sSunkernAnimTable12
.4byte sSunkernAnimTable13
sAxSpritesSunkern:
.4byte sSunkernSprites1
.4byte sSunkernSprites2
.4byte sSunkernSprites3
.4byte sSunkernSprites4
.4byte sSunkernSprites5
.4byte sSunkernSprites6
.4byte sSunkernSprites7
.4byte sSunkernSprites8
.4byte sSunkernSprites9
.4byte sSunkernSprites10
.4byte sSunkernSprites11
.4byte sSunkernSprites12
.4byte sSunkernSprites13
.4byte sSunkernSprites14
.4byte sSunkernSprites15
.4byte sSunkernSprites16
.4byte sSunkernSprites17
.4byte sSunkernSprites18
.4byte sSunkernSprites19
.4byte sSunkernSprites20
.4byte sSunkernSprites21
.4byte sSunkernSprites22
.4byte sSunkernSprites23
.4byte sSunkernSprites24
.4byte sSunkernSprites25
.4byte sSunkernSprites26
.4byte sSunkernSprites27
sAxMainSunkern:
ax_main sAxPosesSunkern, sAxAnimationsSunkern, 13, sAxSpritesSunkern, sAxPositionsSunkern
