.global gAxSwablu
gAxSwablu:
ax_siro sAxMainSwablu
sSwabluPose1:
ax_pose 0, 0x41ef, 0x80f0, 0x5c00
ax_pose_terminator
sSwabluPose2:
ax_pose 1, 0x01ee, 0x80f0, 0x5c00
ax_pose_terminator
sSwabluPose3:
ax_pose 2, 0x41ee, 0x80f0, 0x5c00
ax_pose_terminator
sSwabluPose4:
ax_pose 3, 0x01e7, 0x90e9, 0x5c00
ax_pose_terminator
sSwabluPose5:
ax_pose 4, 0x01eb, 0x90ec, 0x5c00
ax_pose_terminator
sSwabluPose6:
ax_pose 5, 0x01e7, 0x90e9, 0x5c00
ax_pose_terminator
sSwabluPose7:
ax_pose 6, 0x01eb, 0x90e9, 0x5c00
ax_pose_terminator
sSwabluPose8:
ax_pose 7, 0x81ef, 0x90f7, 0x5c00
ax_pose_terminator
sSwabluPose9:
ax_pose 8, 0x01e7, 0x90e9, 0x5c00
ax_pose_terminator
sSwabluPose10:
ax_pose 9, 0x01eb, 0x90eb, 0x5c00
ax_pose_terminator
sSwabluPose11:
ax_pose 10, 0x01eb, 0x90eb, 0x5c00
ax_pose_terminator
sSwabluPose12:
ax_pose 11, 0x01eb, 0x90eb, 0x5c00
ax_pose_terminator
sSwabluPose13:
ax_pose 12, 0x01eb, 0x80f0, 0x5c00
ax_pose_terminator
sSwabluPose14:
ax_pose 13, 0x01eb, 0x80f0, 0x5c00
ax_pose_terminator
sSwabluPose15:
ax_pose 14, 0x01eb, 0x80f0, 0x5c00
ax_pose_terminator
sSwabluPose16:
ax_pose 9, 0x01eb, 0x80f4, 0x5c00
ax_pose_terminator
sSwabluPose17:
ax_pose 10, 0x01eb, 0x80f4, 0x5c00
ax_pose_terminator
sSwabluPose18:
ax_pose 11, 0x01eb, 0x80f4, 0x5c00
ax_pose_terminator
sSwabluPose19:
ax_pose 6, 0x01eb, 0x80f6, 0x5c00
ax_pose_terminator
sSwabluPose20:
ax_pose 7, 0x81ef, 0x80f8, 0x5c00
ax_pose_terminator
sSwabluPose21:
ax_pose 8, 0x01e7, 0x80f6, 0x5c00
ax_pose_terminator
sSwabluPose22:
ax_pose 3, 0x01e7, 0x80f6, 0x5c00
ax_pose_terminator
sSwabluPose23:
ax_pose 4, 0x01eb, 0x80f3, 0x5c00
ax_pose_terminator
sSwabluPose24:
ax_pose 5, 0x01e7, 0x80f6, 0x5c00
ax_pose_terminator
sSwabluPose25:
ax_pose 0, 0x41ef, 0x80f0, 0x5c00
ax_pose_terminator
sSwabluPose26:
ax_pose 1, 0x01ee, 0x80f0, 0x5c00
ax_pose_terminator
sSwabluPose27:
ax_pose 2, 0x41ee, 0x80f0, 0x5c00
ax_pose_terminator
sSwabluPose28:
ax_pose 3, 0x01e7, 0x90e9, 0x5c00
ax_pose_terminator
sSwabluPose29:
ax_pose 4, 0x01eb, 0x90ec, 0x5c00
ax_pose_terminator
sSwabluPose30:
ax_pose 5, 0x01e7, 0x90e9, 0x5c00
ax_pose_terminator
sSwabluPose31:
ax_pose 6, 0x01eb, 0x90e9, 0x5c00
ax_pose_terminator
sSwabluPose32:
ax_pose 7, 0x81ef, 0x90f7, 0x5c00
ax_pose_terminator
sSwabluPose33:
ax_pose 8, 0x01e7, 0x90e9, 0x5c00
ax_pose_terminator
sSwabluPose34:
ax_pose 9, 0x01eb, 0x90eb, 0x5c00
ax_pose_terminator
sSwabluPose35:
ax_pose 10, 0x01eb, 0x90eb, 0x5c00
ax_pose_terminator
sSwabluPose36:
ax_pose 11, 0x01eb, 0x90eb, 0x5c00
ax_pose_terminator
sSwabluPose37:
ax_pose 12, 0x01eb, 0x80f0, 0x5c00
ax_pose_terminator
sSwabluPose38:
ax_pose 13, 0x01eb, 0x80f0, 0x5c00
ax_pose_terminator
sSwabluPose39:
ax_pose 14, 0x01eb, 0x80f0, 0x5c00
ax_pose_terminator
sSwabluPose40:
ax_pose 9, 0x01eb, 0x80f4, 0x5c00
ax_pose_terminator
sSwabluPose41:
ax_pose 10, 0x01eb, 0x80f4, 0x5c00
ax_pose_terminator
sSwabluPose42:
ax_pose 11, 0x01eb, 0x80f4, 0x5c00
ax_pose_terminator
sSwabluPose43:
ax_pose 6, 0x01eb, 0x80f6, 0x5c00
ax_pose_terminator
sSwabluPose44:
ax_pose 7, 0x81ef, 0x80f8, 0x5c00
ax_pose_terminator
sSwabluPose45:
ax_pose 8, 0x01e7, 0x80f6, 0x5c00
ax_pose_terminator
sSwabluPose46:
ax_pose 3, 0x01e7, 0x80f6, 0x5c00
ax_pose_terminator
sSwabluPose47:
ax_pose 4, 0x01eb, 0x80f3, 0x5c00
ax_pose_terminator
sSwabluPose48:
ax_pose 5, 0x01e7, 0x80f6, 0x5c00
ax_pose_terminator
sSwabluPose49:
ax_pose 0, 0x41ef, 0x80f0, 0x5c00
ax_pose_terminator
sSwabluPose50:
ax_pose 1, 0x01ee, 0x80f0, 0x5c00
ax_pose_terminator
sSwabluPose51:
ax_pose 2, 0x41ee, 0x80f0, 0x5c00
ax_pose_terminator
sSwabluPose52:
ax_pose 3, 0x01e7, 0x90e9, 0x5c00
ax_pose_terminator
sSwabluPose53:
ax_pose 4, 0x01eb, 0x90ec, 0x5c00
ax_pose_terminator
sSwabluPose54:
ax_pose 5, 0x01e7, 0x90e9, 0x5c00
ax_pose_terminator
sSwabluPose55:
ax_pose 6, 0x01eb, 0x90e9, 0x5c00
ax_pose_terminator
sSwabluPose56:
ax_pose 7, 0x81ef, 0x90f7, 0x5c00
ax_pose_terminator
sSwabluPose57:
ax_pose 8, 0x01e7, 0x90e9, 0x5c00
ax_pose_terminator
sSwabluPose58:
ax_pose 9, 0x01eb, 0x90eb, 0x5c00
ax_pose_terminator
sSwabluPose59:
ax_pose 10, 0x01eb, 0x90eb, 0x5c00
ax_pose_terminator
sSwabluPose60:
ax_pose 11, 0x01eb, 0x90eb, 0x5c00
ax_pose_terminator
sSwabluPose61:
ax_pose 12, 0x01eb, 0x80f0, 0x5c00
ax_pose_terminator
sSwabluPose62:
ax_pose 13, 0x01eb, 0x80f0, 0x5c00
ax_pose_terminator
sSwabluPose63:
ax_pose 14, 0x01eb, 0x80f0, 0x5c00
ax_pose_terminator
sSwabluPose64:
ax_pose 9, 0x01eb, 0x80f4, 0x5c00
ax_pose_terminator
sSwabluPose65:
ax_pose 10, 0x01eb, 0x80f4, 0x5c00
ax_pose_terminator
sSwabluPose66:
ax_pose 11, 0x01eb, 0x80f4, 0x5c00
ax_pose_terminator
sSwabluPose67:
ax_pose 6, 0x01eb, 0x80f6, 0x5c00
ax_pose_terminator
sSwabluPose68:
ax_pose 7, 0x81ef, 0x80f8, 0x5c00
ax_pose_terminator
sSwabluPose69:
ax_pose 8, 0x01e7, 0x80f6, 0x5c00
ax_pose_terminator
sSwabluPose70:
ax_pose 3, 0x01e7, 0x80f6, 0x5c00
ax_pose_terminator
sSwabluPose71:
ax_pose 4, 0x01eb, 0x80f3, 0x5c00
ax_pose_terminator
sSwabluPose72:
ax_pose 5, 0x01e7, 0x80f6, 0x5c00
ax_pose_terminator
sSwabluPose73:
ax_pose 0, 0x41ef, 0x80f0, 0x5c00
ax_pose_terminator
sSwabluPose74:
ax_pose 1, 0x01ee, 0x80f0, 0x5c00
ax_pose_terminator
sSwabluPose75:
ax_pose 2, 0x41ee, 0x80f0, 0x5c00
ax_pose_terminator
sSwabluPose76:
ax_pose 15, 0x41ef, 0x80f0, 0x5c00
ax_pose_terminator
sSwabluPose77:
ax_pose 16, 0x41ee, 0x80f0, 0x5c00
ax_pose 17, 0x41fe, 0x40f0, 0x5c08
ax_pose_terminator
sSwabluPose78:
ax_pose 18, 0x41ee, 0x80f0, 0x5c00
ax_pose 19, 0x01fe, 0x00f8, 0x5c08
ax_pose_terminator
sSwabluPose79:
ax_pose 3, 0x01e7, 0x90e9, 0x5c00
ax_pose_terminator
sSwabluPose80:
ax_pose 4, 0x01eb, 0x90ec, 0x5c00
ax_pose_terminator
sSwabluPose81:
ax_pose 5, 0x01e7, 0x90e9, 0x5c00
ax_pose_terminator
sSwabluPose82:
ax_pose 20, 0x41e7, 0x10f9, 0x5c00
ax_pose 21, 0x41ef, 0x90e9, 0x5c02
ax_pose_terminator
sSwabluPose83:
ax_pose 22, 0x41f3, 0x90ec, 0x5c00
ax_pose 23, 0x41eb, 0x50ec, 0x5c08
ax_pose_terminator
sSwabluPose84:
ax_pose 24, 0x41ef, 0x90e9, 0x5c00
ax_pose 25, 0x41e7, 0x10f9, 0x5c08
ax_pose_terminator
sSwabluPose85:
ax_pose 6, 0x01eb, 0x90e9, 0x5c00
ax_pose_terminator
sSwabluPose86:
ax_pose 7, 0x81ef, 0x90f7, 0x5c00
ax_pose_terminator
sSwabluPose87:
ax_pose 8, 0x01e7, 0x90e9, 0x5c00
ax_pose_terminator
sSwabluPose88:
ax_pose 26, 0x81ea, 0x90f7, 0x5c00
ax_pose 27, 0x01fa, 0x10ef, 0x5c08
ax_pose_terminator
sSwabluPose89:
ax_pose 28, 0x81ef, 0x90f7, 0x5c00
ax_pose_terminator
sSwabluPose90:
ax_pose 29, 0x81e7, 0x90f9, 0x5c00
ax_pose 30, 0x01f7, 0x10f1, 0x5c08
ax_pose_terminator
sSwabluPose91:
ax_pose 9, 0x01eb, 0x90eb, 0x5c00
ax_pose_terminator
sSwabluPose92:
ax_pose 10, 0x01eb, 0x90eb, 0x5c00
ax_pose_terminator
sSwabluPose93:
ax_pose 11, 0x01eb, 0x90eb, 0x5c00
ax_pose_terminator
sSwabluPose94:
ax_pose 31, 0x41f2, 0x90eb, 0x5c00
ax_pose 32, 0x41ea, 0x10f3, 0x5c08
ax_pose_terminator
sSwabluPose95:
ax_pose 33, 0x41f3, 0x90eb, 0x5c00
ax_pose 34, 0x41eb, 0x10f3, 0x5c08
ax_pose_terminator
sSwabluPose96:
ax_pose 35, 0x41f0, 0x90eb, 0x5c00
ax_pose 36, 0x41e8, 0x10f3, 0x5c08
ax_pose_terminator
sSwabluPose97:
ax_pose 12, 0x01eb, 0x80f0, 0x5c00
ax_pose_terminator
sSwabluPose98:
ax_pose 13, 0x01eb, 0x80f0, 0x5c00
ax_pose_terminator
sSwabluPose99:
ax_pose 14, 0x01eb, 0x80f0, 0x5c00
ax_pose_terminator
sSwabluPose100:
ax_pose 37, 0x41f3, 0x80f0, 0x5c00
ax_pose 38, 0x41eb, 0x00f8, 0x5c08
ax_pose_terminator
sSwabluPose101:
ax_pose 39, 0x41f3, 0x80f0, 0x5c00
ax_pose 40, 0x41eb, 0x00f8, 0x5c08
ax_pose_terminator
sSwabluPose102:
ax_pose 41, 0x41eb, 0x80f0, 0x5c00
ax_pose 42, 0x41fb, 0x00f8, 0x5c08
ax_pose_terminator
sSwabluPose103:
ax_pose 9, 0x01eb, 0x80f4, 0x5c00
ax_pose_terminator
sSwabluPose104:
ax_pose 10, 0x01eb, 0x80f4, 0x5c00
ax_pose_terminator
sSwabluPose105:
ax_pose 11, 0x01eb, 0x80f4, 0x5c00
ax_pose_terminator
sSwabluPose106:
ax_pose 31, 0x41f2, 0x80f4, 0x5c00
ax_pose 32, 0x41ea, 0x00fc, 0x5c08
ax_pose_terminator
sSwabluPose107:
ax_pose 33, 0x41f3, 0x80f4, 0x5c00
ax_pose 34, 0x41eb, 0x00fc, 0x5c08
ax_pose_terminator
sSwabluPose108:
ax_pose 35, 0x41f0, 0x80f4, 0x5c00
ax_pose 36, 0x41e8, 0x00fc, 0x5c08
ax_pose_terminator
sSwabluPose109:
ax_pose 6, 0x01eb, 0x80f6, 0x5c00
ax_pose_terminator
sSwabluPose110:
ax_pose 7, 0x81ef, 0x80f8, 0x5c00
ax_pose_terminator
sSwabluPose111:
ax_pose 8, 0x01e7, 0x80f6, 0x5c00
ax_pose_terminator
sSwabluPose112:
ax_pose 27, 0x01fa, 0x0108, 0x5c00
ax_pose 26, 0x81ea, 0x80f8, 0x5c01
ax_pose_terminator
sSwabluPose113:
ax_pose 28, 0x81ef, 0x80f8, 0x5c00
ax_pose_terminator
sSwabluPose114:
ax_pose 29, 0x81e7, 0x80f6, 0x5c00
ax_pose 30, 0x01f7, 0x0106, 0x5c08
ax_pose_terminator
sSwabluPose115:
ax_pose 3, 0x01e7, 0x80f6, 0x5c00
ax_pose_terminator
sSwabluPose116:
ax_pose 4, 0x01eb, 0x80f3, 0x5c00
ax_pose_terminator
sSwabluPose117:
ax_pose 5, 0x01e7, 0x80f6, 0x5c00
ax_pose_terminator
sSwabluPose118:
ax_pose 20, 0x41e7, 0x00f6, 0x5c00
ax_pose 21, 0x41ef, 0x80f6, 0x5c02
ax_pose_terminator
sSwabluPose119:
ax_pose 22, 0x41f3, 0x80f3, 0x5c00
ax_pose 23, 0x41eb, 0x40f3, 0x5c08
ax_pose_terminator
sSwabluPose120:
ax_pose 24, 0x41ef, 0x80f6, 0x5c00
ax_pose 25, 0x41e7, 0x00f6, 0x5c08
ax_pose_terminator
sSwabluPose121:
ax_pose 0, 0x41ef, 0x80f0, 0x5c00
ax_pose_terminator
sSwabluPose122:
ax_pose 1, 0x01ed, 0x80f0, 0x5c00
ax_pose_terminator
sSwabluPose123:
ax_pose 2, 0x41ee, 0x80f0, 0x5c00
ax_pose_terminator
sSwabluPose124:
ax_pose 3, 0x01e7, 0x90e9, 0x5c00
ax_pose_terminator
sSwabluPose125:
ax_pose 4, 0x01ea, 0x90ec, 0x5c00
ax_pose_terminator
sSwabluPose126:
ax_pose 5, 0x01e7, 0x90e9, 0x5c00
ax_pose_terminator
sSwabluPose127:
ax_pose 6, 0x01eb, 0x90e9, 0x5c00
ax_pose_terminator
sSwabluPose128:
ax_pose 7, 0x81ee, 0x90f7, 0x5c00
ax_pose_terminator
sSwabluPose129:
ax_pose 8, 0x01e7, 0x90e9, 0x5c00
ax_pose_terminator
sSwabluPose130:
ax_pose 9, 0x01eb, 0x90eb, 0x5c00
ax_pose_terminator
sSwabluPose131:
ax_pose 10, 0x01ea, 0x90eb, 0x5c00
ax_pose_terminator
sSwabluPose132:
ax_pose 11, 0x01eb, 0x90eb, 0x5c00
ax_pose_terminator
sSwabluPose133:
ax_pose 12, 0x01eb, 0x80f0, 0x5c00
ax_pose_terminator
sSwabluPose134:
ax_pose 13, 0x01ea, 0x80f0, 0x5c00
ax_pose_terminator
sSwabluPose135:
ax_pose 14, 0x01eb, 0x80f0, 0x5c00
ax_pose_terminator
sSwabluPose136:
ax_pose 9, 0x01eb, 0x80f4, 0x5c00
ax_pose_terminator
sSwabluPose137:
ax_pose 10, 0x01ea, 0x80f4, 0x5c00
ax_pose_terminator
sSwabluPose138:
ax_pose 11, 0x01eb, 0x80f4, 0x5c00
ax_pose_terminator
sSwabluPose139:
ax_pose 6, 0x01eb, 0x80f6, 0x5c00
ax_pose_terminator
sSwabluPose140:
ax_pose 7, 0x81ee, 0x80f8, 0x5c00
ax_pose_terminator
sSwabluPose141:
ax_pose 8, 0x01e7, 0x80f6, 0x5c00
ax_pose_terminator
sSwabluPose142:
ax_pose 3, 0x01e7, 0x80f6, 0x5c00
ax_pose_terminator
sSwabluPose143:
ax_pose 4, 0x01ea, 0x80f3, 0x5c00
ax_pose_terminator
sSwabluPose144:
ax_pose 5, 0x01e7, 0x80f6, 0x5c00
ax_pose_terminator
sSwabluPose145:
ax_pose 43, 0x01f3, 0x80f4, 0x5c00
ax_pose_terminator
sSwabluPose146:
ax_pose 44, 0x01f3, 0x80f4, 0x5c00
ax_pose_terminator
sSwabluPose147:
ax_pose 45, 0x01dd, 0x80f0, 0x5c00
ax_pose_terminator
sSwabluPose148:
ax_pose 46, 0x01e1, 0x90ed, 0x5c00
ax_pose_terminator
sSwabluPose149:
ax_pose 47, 0x01e2, 0x90eb, 0x5c00
ax_pose_terminator
sSwabluPose150:
ax_pose 48, 0x01e2, 0x90ec, 0x5c00
ax_pose_terminator
sSwabluPose151:
ax_pose 49, 0x01dc, 0x80f0, 0x5c00
ax_pose_terminator
sSwabluPose152:
ax_pose 48, 0x01e2, 0x80f3, 0x5c00
ax_pose_terminator
sSwabluPose153:
ax_pose 47, 0x01e2, 0x80f5, 0x5c00
ax_pose_terminator
sSwabluPose154:
ax_pose 46, 0x01e1, 0x80f3, 0x5c00
ax_pose_terminator
sSwabluPose155:
ax_pose 0, 0x41ef, 0x80f0, 0x5c00
ax_pose_terminator
sSwabluPose156:
ax_pose 1, 0x01ee, 0x80f0, 0x5c00
ax_pose_terminator
sSwabluPose157:
ax_pose 2, 0x41ee, 0x80f0, 0x5c00
ax_pose_terminator
sSwabluPose158:
ax_pose 3, 0x01e7, 0x90e9, 0x5c00
ax_pose_terminator
sSwabluPose159:
ax_pose 4, 0x01eb, 0x90ec, 0x5c00
ax_pose_terminator
sSwabluPose160:
ax_pose 5, 0x01e7, 0x90e9, 0x5c00
ax_pose_terminator
sSwabluPose161:
ax_pose 6, 0x01eb, 0x90e9, 0x5c00
ax_pose_terminator
sSwabluPose162:
ax_pose 7, 0x81ef, 0x90f7, 0x5c00
ax_pose_terminator
sSwabluPose163:
ax_pose 8, 0x01e7, 0x90e9, 0x5c00
ax_pose_terminator
sSwabluPose164:
ax_pose 9, 0x01eb, 0x90eb, 0x5c00
ax_pose_terminator
sSwabluPose165:
ax_pose 10, 0x01eb, 0x90eb, 0x5c00
ax_pose_terminator
sSwabluPose166:
ax_pose 11, 0x01eb, 0x90eb, 0x5c00
ax_pose_terminator
sSwabluPose167:
ax_pose 12, 0x01eb, 0x80f0, 0x5c00
ax_pose_terminator
sSwabluPose168:
ax_pose 13, 0x01eb, 0x80f0, 0x5c00
ax_pose_terminator
sSwabluPose169:
ax_pose 14, 0x01eb, 0x80f0, 0x5c00
ax_pose_terminator
sSwabluPose170:
ax_pose 9, 0x01eb, 0x80f4, 0x5c00
ax_pose_terminator
sSwabluPose171:
ax_pose 10, 0x01eb, 0x80f4, 0x5c00
ax_pose_terminator
sSwabluPose172:
ax_pose 11, 0x01eb, 0x80f4, 0x5c00
ax_pose_terminator
sSwabluPose173:
ax_pose 6, 0x01eb, 0x80f6, 0x5c00
ax_pose_terminator
sSwabluPose174:
ax_pose 7, 0x81ef, 0x80f8, 0x5c00
ax_pose_terminator
sSwabluPose175:
ax_pose 8, 0x01e7, 0x80f6, 0x5c00
ax_pose_terminator
sSwabluPose176:
ax_pose 3, 0x01e7, 0x80f6, 0x5c00
ax_pose_terminator
sSwabluPose177:
ax_pose 4, 0x01eb, 0x80f3, 0x5c00
ax_pose_terminator
sSwabluPose178:
ax_pose 5, 0x01e7, 0x80f6, 0x5c00
ax_pose_terminator
sSwabluPose179:
ax_pose 18, 0x41ee, 0x80f0, 0x5c00
ax_pose 19, 0x01fe, 0x00f8, 0x5c08
ax_pose_terminator
sSwabluPose180:
ax_pose 24, 0x41ef, 0x80f6, 0x5c00
ax_pose 25, 0x41e7, 0x00f6, 0x5c08
ax_pose_terminator
sSwabluPose181:
ax_pose 29, 0x81e7, 0x80f6, 0x5c00
ax_pose 30, 0x01f7, 0x0106, 0x5c08
ax_pose_terminator
sSwabluPose182:
ax_pose 35, 0x41f0, 0x80f4, 0x5c00
ax_pose 36, 0x41e8, 0x00fc, 0x5c08
ax_pose_terminator
sSwabluPose183:
ax_pose 41, 0x41ea, 0x80f0, 0x5c00
ax_pose 42, 0x41fa, 0x00f8, 0x5c08
ax_pose_terminator
sSwabluPose184:
ax_pose 35, 0x41f0, 0x90ec, 0x5c00
ax_pose 36, 0x41e8, 0x10f4, 0x5c08
ax_pose_terminator
sSwabluPose185:
ax_pose 29, 0x81e7, 0x90f9, 0x5c00
ax_pose 30, 0x01f7, 0x10f1, 0x5c08
ax_pose_terminator
sSwabluPose186:
ax_pose 24, 0x41ef, 0x90e9, 0x5c00
ax_pose 25, 0x41e7, 0x10f9, 0x5c08
ax_pose_terminator
sSwabluPose187:
ax_pose 15, 0x41ef, 0x80f0, 0x5c00
ax_pose_terminator
sSwabluPose188:
ax_pose 20, 0x41e7, 0x10f9, 0x5c00
ax_pose 21, 0x41ef, 0x90e9, 0x5c02
ax_pose_terminator
sSwabluPose189:
ax_pose 26, 0x81ea, 0x90f7, 0x5c00
ax_pose 27, 0x01fa, 0x10ef, 0x5c08
ax_pose_terminator
sSwabluPose190:
ax_pose 31, 0x41f2, 0x90eb, 0x5c00
ax_pose 32, 0x41ea, 0x10f3, 0x5c08
ax_pose_terminator
sSwabluPose191:
ax_pose 37, 0x41f3, 0x80f0, 0x5c00
ax_pose 38, 0x41eb, 0x00f8, 0x5c08
ax_pose_terminator
sSwabluPose192:
ax_pose 31, 0x41f2, 0x80f4, 0x5c00
ax_pose 32, 0x41ea, 0x00fc, 0x5c08
ax_pose_terminator
sSwabluPose193:
ax_pose 27, 0x01fa, 0x0108, 0x5c00
ax_pose 26, 0x81ea, 0x80f8, 0x5c01
ax_pose_terminator
sSwabluPose194:
ax_pose 20, 0x41e7, 0x00f6, 0x5c00
ax_pose 21, 0x41ef, 0x80f6, 0x5c02
ax_pose_terminator
sSwabluPose195:
ax_pose 15, 0x41ef, 0x80f0, 0x5c00
ax_pose_terminator
sSwabluPose196:
ax_pose 16, 0x41ee, 0x80f0, 0x5c00
ax_pose 17, 0x41fe, 0x40f0, 0x5c08
ax_pose_terminator
sSwabluPose197:
ax_pose 18, 0x41ee, 0x80f0, 0x5c00
ax_pose 19, 0x01fe, 0x00f8, 0x5c08
ax_pose_terminator
sSwabluPose198:
ax_pose 20, 0x41e7, 0x10f9, 0x5c00
ax_pose 21, 0x41ef, 0x90e9, 0x5c02
ax_pose_terminator
sSwabluPose199:
ax_pose 22, 0x41f3, 0x90ec, 0x5c00
ax_pose 23, 0x41eb, 0x50ec, 0x5c08
ax_pose_terminator
sSwabluPose200:
ax_pose 24, 0x41ef, 0x90e9, 0x5c00
ax_pose 25, 0x41e7, 0x10f9, 0x5c08
ax_pose_terminator
sSwabluPose201:
ax_pose 26, 0x81ea, 0x90f7, 0x5c00
ax_pose 27, 0x01fa, 0x10ef, 0x5c08
ax_pose_terminator
sSwabluPose202:
ax_pose 28, 0x81ef, 0x90f7, 0x5c00
ax_pose_terminator
sSwabluPose203:
ax_pose 29, 0x81e7, 0x90f9, 0x5c00
ax_pose 30, 0x01f7, 0x10f1, 0x5c08
ax_pose_terminator
sSwabluPose204:
ax_pose 31, 0x41f2, 0x90eb, 0x5c00
ax_pose 32, 0x41ea, 0x10f3, 0x5c08
ax_pose_terminator
sSwabluPose205:
ax_pose 33, 0x41f3, 0x90eb, 0x5c00
ax_pose 34, 0x41eb, 0x10f3, 0x5c08
ax_pose_terminator
sSwabluPose206:
ax_pose 35, 0x41f0, 0x90eb, 0x5c00
ax_pose 36, 0x41e8, 0x10f3, 0x5c08
ax_pose_terminator
sSwabluPose207:
ax_pose 37, 0x41f3, 0x80f0, 0x5c00
ax_pose 38, 0x41eb, 0x00f8, 0x5c08
ax_pose_terminator
sSwabluPose208:
ax_pose 39, 0x41f3, 0x80f0, 0x5c00
ax_pose 40, 0x41eb, 0x00f8, 0x5c08
ax_pose_terminator
sSwabluPose209:
ax_pose 41, 0x41eb, 0x80f0, 0x5c00
ax_pose 42, 0x41fb, 0x00f8, 0x5c08
ax_pose_terminator
sSwabluPose210:
ax_pose 31, 0x41f2, 0x80f4, 0x5c00
ax_pose 32, 0x41ea, 0x00fc, 0x5c08
ax_pose_terminator
sSwabluPose211:
ax_pose 33, 0x41f3, 0x80f4, 0x5c00
ax_pose 34, 0x41eb, 0x00fc, 0x5c08
ax_pose_terminator
sSwabluPose212:
ax_pose 35, 0x41f0, 0x80f4, 0x5c00
ax_pose 36, 0x41e8, 0x00fc, 0x5c08
ax_pose_terminator
sSwabluPose213:
ax_pose 27, 0x01fa, 0x0108, 0x5c00
ax_pose 26, 0x81ea, 0x80f8, 0x5c01
ax_pose_terminator
sSwabluPose214:
ax_pose 28, 0x81ef, 0x80f8, 0x5c00
ax_pose_terminator
sSwabluPose215:
ax_pose 29, 0x81e7, 0x80f6, 0x5c00
ax_pose 30, 0x01f7, 0x0106, 0x5c08
ax_pose_terminator
sSwabluPose216:
ax_pose 20, 0x41e7, 0x00f6, 0x5c00
ax_pose 21, 0x41ef, 0x80f6, 0x5c02
ax_pose_terminator
sSwabluPose217:
ax_pose 22, 0x41f3, 0x80f3, 0x5c00
ax_pose 23, 0x41eb, 0x40f3, 0x5c08
ax_pose_terminator
sSwabluPose218:
ax_pose 24, 0x41ef, 0x80f6, 0x5c00
ax_pose 25, 0x41e7, 0x00f6, 0x5c08
ax_pose_terminator
sSwabluPose219:
ax_pose 16, 0x41ee, 0x80f0, 0x5c00
ax_pose 17, 0x41fe, 0x40f0, 0x5c08
ax_pose_terminator
sSwabluPose220:
ax_pose 22, 0x41f3, 0x80f3, 0x5c00
ax_pose 23, 0x41eb, 0x40f3, 0x5c08
ax_pose_terminator
sSwabluPose221:
ax_pose 28, 0x81ef, 0x80f8, 0x5c00
ax_pose_terminator
sSwabluPose222:
ax_pose 33, 0x41f3, 0x80f3, 0x5c00
ax_pose 34, 0x41eb, 0x00fb, 0x5c08
ax_pose_terminator
sSwabluPose223:
ax_pose 39, 0x41f3, 0x80f0, 0x5c00
ax_pose 40, 0x41eb, 0x00f8, 0x5c08
ax_pose_terminator
sSwabluPose224:
ax_pose 33, 0x41f3, 0x90ec, 0x5c00
ax_pose 34, 0x41eb, 0x10f4, 0x5c08
ax_pose_terminator
sSwabluPose225:
ax_pose 28, 0x81ef, 0x90f8, 0x5c00
ax_pose_terminator
sSwabluPose226:
ax_pose 22, 0x41f3, 0x90ed, 0x5c00
ax_pose 23, 0x41eb, 0x50ed, 0x5c08
ax_pose_terminator
sSwabluPose227:
ax_pose 0, 0x41ef, 0x80f0, 0x5c00
ax_pose_terminator
sSwabluPose228:
ax_pose 3, 0x01e7, 0x80f6, 0x5c00
ax_pose_terminator
sSwabluPose229:
ax_pose 6, 0x01eb, 0x80f6, 0x5c00
ax_pose_terminator
sSwabluPose230:
ax_pose 9, 0x01eb, 0x80f4, 0x5c00
ax_pose_terminator
sSwabluPose231:
ax_pose 12, 0x01eb, 0x80f0, 0x5c00
ax_pose_terminator
sSwabluPose232:
ax_pose 9, 0x01eb, 0x90eb, 0x5c00
ax_pose_terminator
sSwabluPose233:
ax_pose 6, 0x01eb, 0x90e9, 0x5c00
ax_pose_terminator
sSwabluPose234:
ax_pose 3, 0x01e7, 0x90e9, 0x5c00
ax_pose_terminator
.align 2
sSwabluAnims_1_1:
ax_anim 8, 0, 0, 0, 0, 0, 0,
ax_anim 6, 0, 1, 0, -1, 0, 0,
ax_anim 6, 0, 1, 0, -2, 0, 0,
ax_anim 8, 0, 0, 0, -2, 0, 0,
ax_anim 6, 0, 2, 0, -1, 0, 0,
ax_anim 6, 0, 2, 0, 0, 0, 0,
ax_anim_terminator
sSwabluAnims_1_2:
ax_anim 8, 0, 3, 0, 0, 0, 0,
ax_anim 6, 0, 4, 0, -1, 0, 0,
ax_anim 6, 0, 4, 0, -2, 0, 0,
ax_anim 8, 0, 3, 0, -2, 0, 0,
ax_anim 6, 0, 5, 0, -1, 0, 0,
ax_anim 6, 0, 5, 0, 0, 0, 0,
ax_anim_terminator
sSwabluAnims_1_3:
ax_anim 8, 0, 6, 0, 0, 0, 0,
ax_anim 6, 0, 7, 0, -1, 0, 0,
ax_anim 6, 0, 7, 0, -2, 0, 0,
ax_anim 8, 0, 6, 0, -2, 0, 0,
ax_anim 6, 0, 8, 0, -1, 0, 0,
ax_anim 6, 0, 8, 0, 0, 0, 0,
ax_anim_terminator
sSwabluAnims_1_4:
ax_anim 8, 0, 9, 0, 0, 0, 0,
ax_anim 6, 0, 10, 0, -1, 0, 0,
ax_anim 6, 0, 10, 0, -2, 0, 0,
ax_anim 8, 0, 9, 0, -2, 0, 0,
ax_anim 6, 0, 11, 0, -1, 0, 0,
ax_anim 6, 0, 11, 0, 0, 0, 0,
ax_anim_terminator
sSwabluAnims_1_5:
ax_anim 8, 0, 12, 0, 0, 0, 0,
ax_anim 6, 0, 13, 0, -1, 0, 0,
ax_anim 6, 0, 13, 0, -2, 0, 0,
ax_anim 8, 0, 12, 0, -2, 0, 0,
ax_anim 6, 0, 14, 0, -1, 0, 0,
ax_anim 6, 0, 14, 0, 0, 0, 0,
ax_anim_terminator
sSwabluAnims_1_6:
ax_anim 8, 0, 15, 0, 0, 0, 0,
ax_anim 6, 0, 16, 0, -1, 0, 0,
ax_anim 6, 0, 16, 0, -2, 0, 0,
ax_anim 8, 0, 15, 0, -2, 0, 0,
ax_anim 6, 0, 17, 0, -1, 0, 0,
ax_anim 6, 0, 17, 0, 0, 0, 0,
ax_anim_terminator
sSwabluAnims_1_7:
ax_anim 8, 0, 18, 0, 0, 0, 0,
ax_anim 6, 0, 19, 0, -1, 0, 0,
ax_anim 6, 0, 19, 0, -2, 0, 0,
ax_anim 8, 0, 18, 0, -2, 0, 0,
ax_anim 6, 0, 20, 0, -1, 0, 0,
ax_anim 6, 0, 20, 0, 0, 0, 0,
ax_anim_terminator
sSwabluAnims_1_8:
ax_anim 8, 0, 21, 0, 0, 0, 0,
ax_anim 6, 0, 22, 0, -1, 0, 0,
ax_anim 6, 0, 22, 0, -2, 0, 0,
ax_anim 8, 0, 21, 0, -2, 0, 0,
ax_anim 6, 0, 23, 0, -1, 0, 0,
ax_anim 6, 0, 23, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sSwabluAnims_2_1:
ax_anim 2, 0, 25, 0, -1, 0, -1,
ax_anim 4, 0, 24, 0, -2, 0, -2,
ax_anim 1, 0, 26, 0, 0, 0, 0,
ax_anim 1, 2, 26, 0, 4, 0, 4,
ax_anim 1, 0, 26, 0, 10, 0, 9,
ax_anim 2, 0, 26, 0, 24, 0, 21,
ax_anim 2, 1, 26, 1, 24, 1, 21,
ax_anim 2, 0, 26, 0, 24, 0, 21,
ax_anim 2, 0, 26, 1, 24, 1, 21,
ax_anim 2, 0, 24, 0, 8, 0, 8,
ax_anim_terminator
sSwabluAnims_2_2:
ax_anim 2, 0, 28, -1, -1, -1, -1,
ax_anim 4, 0, 27, -2, -2, -2, -2,
ax_anim 1, 0, 29, 0, 0, 0, 0,
ax_anim 1, 2, 29, 4, 4, 4, 3,
ax_anim 1, 0, 29, 10, 10, 10, 8,
ax_anim 2, 0, 29, 23, 24, 23, 20,
ax_anim 2, 1, 29, 24, 23, 24, 19,
ax_anim 2, 0, 29, 23, 24, 23, 20,
ax_anim 2, 0, 29, 24, 23, 24, 19,
ax_anim 2, 0, 27, 8, 8, 8, 6,
ax_anim_terminator
sSwabluAnims_2_3:
ax_anim 2, 0, 31, -1, 0, -1, 0,
ax_anim 4, 0, 30, -2, 0, -2, 0,
ax_anim 1, 0, 32, 0, 0, 0, 0,
ax_anim 1, 2, 32, 4, 0, 4, 0,
ax_anim 1, 0, 32, 10, 1, 10, 0,
ax_anim 2, 0, 32, 23, 2, 23, 0,
ax_anim 2, 1, 32, 23, 3, 23, 1,
ax_anim 2, 0, 32, 23, 2, 23, 0,
ax_anim 2, 0, 32, 23, 3, 23, 1,
ax_anim 2, 0, 30, 8, 1, 8, 0,
ax_anim_terminator
sSwabluAnims_2_4:
ax_anim 2, 0, 34, -1, 1, -1, 1,
ax_anim 4, 0, 33, -2, 2, -2, 2,
ax_anim 1, 0, 35, 0, -1, 0, -1,
ax_anim 1, 2, 35, 5, -5, 5, -6,
ax_anim 1, 0, 35, 11, -11, 11, -13,
ax_anim 2, 0, 35, 22, -21, 21, -25,
ax_anim 2, 1, 35, 23, -20, 22, -24,
ax_anim 2, 0, 35, 22, -21, 21, -25,
ax_anim 2, 0, 35, 23, -20, 22, -24,
ax_anim 2, 0, 33, 8, -8, 8, -10,
ax_anim_terminator
sSwabluAnims_2_5:
ax_anim 2, 0, 37, 0, 1, 0, 1,
ax_anim 4, 0, 36, 0, 2, 0, 2,
ax_anim 1, 0, 38, 0, 0, 0, 0,
ax_anim 1, 2, 38, 0, -4, 0, -4,
ax_anim 1, 0, 38, 0, -11, 0, -13,
ax_anim 2, 0, 38, 0, -21, 0, -26,
ax_anim 2, 1, 38, 1, -21, 1, -26,
ax_anim 2, 0, 38, 0, -21, 0, -26,
ax_anim 2, 0, 38, 1, -21, 1, -26,
ax_anim 2, 0, 36, 0, -7, 0, -9,
ax_anim_terminator
sSwabluAnims_2_6:
ax_anim 2, 0, 40, 1, 1, 1, 1,
ax_anim 4, 0, 39, 2, 2, 2, 2,
ax_anim 1, 0, 41, 0, -1, 0, -1,
ax_anim 1, 2, 41, -5, -5, -5, -6,
ax_anim 1, 0, 41, -11, -11, -11, -13,
ax_anim 2, 0, 41, -22, -21, -21, -25,
ax_anim 2, 1, 41, -23, -20, -22, -24,
ax_anim 2, 0, 41, -22, -21, -21, -25,
ax_anim 2, 0, 41, -23, -20, -22, -24,
ax_anim 2, 0, 39, -8, -8, -8, -10,
ax_anim_terminator
sSwabluAnims_2_7:
ax_anim 2, 0, 43, 1, 0, 1, 0,
ax_anim 4, 0, 42, 2, 0, 2, 0,
ax_anim 1, 0, 44, 0, 0, 0, 0,
ax_anim 1, 2, 44, -4, 0, -4, 0,
ax_anim 1, 0, 44, -10, 1, -10, 0,
ax_anim 2, 0, 44, -23, 2, -23, 0,
ax_anim 2, 1, 44, -23, 3, -23, 1,
ax_anim 2, 0, 44, -23, 2, -23, 0,
ax_anim 2, 0, 44, -23, 3, -23, 1,
ax_anim 2, 0, 42, -8, 1, -8, 0,
ax_anim_terminator
sSwabluAnims_2_8:
ax_anim 2, 0, 46, 1, -1, 1, -1,
ax_anim 4, 0, 45, 2, -2, 2, -2,
ax_anim 1, 0, 47, 0, 0, 0, 0,
ax_anim 1, 2, 47, -4, 4, -4, 3,
ax_anim 1, 0, 47, -10, 10, -10, 8,
ax_anim 2, 0, 47, -23, 24, -23, 20,
ax_anim 2, 1, 47, -24, 23, -24, 19,
ax_anim 2, 0, 47, -23, 24, -23, 20,
ax_anim 2, 0, 47, -24, 23, -24, 19,
ax_anim 2, 0, 45, -8, 8, -8, 6,
ax_anim_terminator
.align 2
sSwabluAnims_3_1:
ax_anim 2, 0, 49, 0, -1, 0, -1,
ax_anim 4, 0, 48, 0, -2, 0, -2,
ax_anim 1, 0, 50, 0, 0, 0, 0,
ax_anim 1, 2, 50, 0, 4, 0, 4,
ax_anim 1, 0, 50, 0, 10, 0, 9,
ax_anim 2, 0, 50, 0, 24, 0, 21,
ax_anim 2, 1, 50, 1, 24, 1, 21,
ax_anim 2, 0, 50, 0, 24, 0, 21,
ax_anim 2, 0, 50, 1, 24, 1, 21,
ax_anim 2, 0, 48, 0, 8, 0, 8,
ax_anim_terminator
sSwabluAnims_3_2:
ax_anim 2, 0, 52, -1, -1, -1, -1,
ax_anim 4, 0, 51, -2, -2, -2, -2,
ax_anim 1, 0, 53, 0, 0, 0, 0,
ax_anim 1, 2, 53, 4, 4, 4, 3,
ax_anim 1, 0, 53, 10, 10, 10, 8,
ax_anim 2, 0, 53, 23, 24, 23, 20,
ax_anim 2, 1, 53, 24, 23, 24, 19,
ax_anim 2, 0, 53, 23, 24, 23, 20,
ax_anim 2, 0, 53, 24, 23, 24, 19,
ax_anim 2, 0, 51, 8, 8, 8, 6,
ax_anim_terminator
sSwabluAnims_3_3:
ax_anim 2, 0, 55, -1, 0, -1, 0,
ax_anim 4, 0, 54, -2, 0, -2, 0,
ax_anim 1, 0, 56, 0, 0, 0, 0,
ax_anim 1, 2, 56, 4, 0, 4, 0,
ax_anim 1, 0, 56, 10, 1, 10, 0,
ax_anim 2, 0, 56, 23, 2, 23, 0,
ax_anim 2, 1, 56, 23, 3, 23, 1,
ax_anim 2, 0, 56, 23, 2, 23, 0,
ax_anim 2, 0, 56, 23, 3, 23, 1,
ax_anim 2, 0, 54, 8, 1, 8, 0,
ax_anim_terminator
sSwabluAnims_3_4:
ax_anim 2, 0, 58, -1, 1, -1, 1,
ax_anim 4, 0, 57, -2, 2, -2, 2,
ax_anim 1, 0, 59, 0, -1, 0, -1,
ax_anim 1, 2, 59, 5, -5, 5, -6,
ax_anim 1, 0, 59, 11, -11, 11, -13,
ax_anim 2, 0, 59, 22, -21, 21, -25,
ax_anim 2, 1, 59, 23, -20, 22, -24,
ax_anim 2, 0, 59, 22, -21, 21, -25,
ax_anim 2, 0, 59, 23, -20, 22, -24,
ax_anim 2, 0, 57, 8, -8, 8, -10,
ax_anim_terminator
sSwabluAnims_3_5:
ax_anim 2, 0, 61, 0, 1, 0, 1,
ax_anim 4, 0, 60, 0, 2, 0, 2,
ax_anim 1, 0, 62, 0, 0, 0, 0,
ax_anim 1, 2, 62, 0, -4, 0, -4,
ax_anim 1, 0, 62, 0, -11, 0, -13,
ax_anim 2, 0, 62, 0, -21, 0, -26,
ax_anim 2, 1, 62, 1, -21, 1, -26,
ax_anim 2, 0, 62, 0, -21, 0, -26,
ax_anim 2, 0, 62, 1, -21, 1, -26,
ax_anim 2, 0, 60, 0, -7, 0, -9,
ax_anim_terminator
sSwabluAnims_3_6:
ax_anim 2, 0, 64, 1, 1, 1, 1,
ax_anim 4, 0, 63, 2, 2, 2, 2,
ax_anim 1, 0, 65, 0, -1, 0, -1,
ax_anim 1, 2, 65, -5, -5, -5, -6,
ax_anim 1, 0, 65, -11, -11, -11, -13,
ax_anim 2, 0, 65, -22, -21, -21, -25,
ax_anim 2, 1, 65, -23, -20, -22, -24,
ax_anim 2, 0, 65, -22, -21, -21, -25,
ax_anim 2, 0, 65, -23, -20, -22, -24,
ax_anim 2, 0, 63, -8, -8, -8, -10,
ax_anim_terminator
sSwabluAnims_3_7:
ax_anim 2, 0, 67, 1, 0, 1, 0,
ax_anim 4, 0, 66, 2, 0, 2, 0,
ax_anim 1, 0, 68, 0, 0, 0, 0,
ax_anim 1, 2, 68, -4, 0, -4, 0,
ax_anim 1, 0, 68, -10, 1, -10, 0,
ax_anim 2, 0, 68, -23, 2, -23, 0,
ax_anim 2, 1, 68, -23, 3, -23, 1,
ax_anim 2, 0, 68, -23, 2, -23, 0,
ax_anim 2, 0, 68, -23, 3, -23, 1,
ax_anim 2, 0, 66, -8, 1, -8, 0,
ax_anim_terminator
sSwabluAnims_3_8:
ax_anim 2, 0, 70, 1, -1, 1, -1,
ax_anim 4, 0, 69, 2, -2, 2, -2,
ax_anim 1, 0, 71, 0, 0, 0, 0,
ax_anim 1, 2, 71, -4, 4, -4, 3,
ax_anim 1, 0, 71, -10, 10, -10, 8,
ax_anim 2, 0, 71, -23, 24, -23, 20,
ax_anim 2, 1, 71, -24, 23, -24, 19,
ax_anim 2, 0, 71, -23, 24, -23, 20,
ax_anim 2, 0, 71, -24, 23, -24, 19,
ax_anim 2, 0, 69, -8, 8, -8, 6,
ax_anim_terminator
.align 2
sSwabluAnims_4_1:
ax_anim 2, 0, 73, 0, -2, 0, -2,
ax_anim 6, 2, 74, 0, -3, 0, -3,
ax_anim 2, 0, 73, 0, -1, 0, -1,
ax_anim 2, 1, 77, 0, 3, 0, 3,
ax_anim 2, 0, 76, 1, 3, 1, 3,
ax_anim 2, 0, 77, 0, 3, 0, 3,
ax_anim 2, 0, 76, 1, 3, 1, 3,
ax_anim 2, 0, 77, 0, 3, 0, 3,
ax_anim 2, 0, 76, 1, 3, 1, 3,
ax_anim 2, 0, 77, 0, 3, 0, 3,
ax_anim 2, 0, 72, 0, 1, 0, 1,
ax_anim_terminator
sSwabluAnims_4_2:
ax_anim 2, 0, 79, -2, -2, -2, -2,
ax_anim 6, 2, 80, -3, -3, -3, -3,
ax_anim 2, 0, 78, -1, -1, -1, -1,
ax_anim 2, 1, 83, 2, 2, 2, 2,
ax_anim 2, 0, 82, 3, 1, 3, 1,
ax_anim 2, 0, 83, 2, 2, 2, 2,
ax_anim 2, 0, 82, 3, 1, 3, 1,
ax_anim 2, 0, 83, 2, 2, 2, 2,
ax_anim 2, 0, 82, 3, 1, 3, 1,
ax_anim 2, 0, 83, 2, 2, 2, 2,
ax_anim 2, 0, 78, 1, 1, 1, 1,
ax_anim_terminator
sSwabluAnims_4_3:
ax_anim 2, 0, 85, -2, 0, -2, 0,
ax_anim 6, 2, 86, -3, 0, -3, 0,
ax_anim 2, 0, 84, -1, 0, -1, 0,
ax_anim 2, 1, 89, 3, 0, 3, 0,
ax_anim 2, 0, 88, 3, 1, 3, 1,
ax_anim 2, 0, 89, 3, 0, 3, 0,
ax_anim 2, 0, 88, 3, 1, 3, 1,
ax_anim 2, 0, 89, 3, 0, 3, 0,
ax_anim 2, 0, 88, 3, 1, 3, 1,
ax_anim 2, 0, 89, 3, 0, 3, 0,
ax_anim 2, 0, 84, 1, 0, 1, 0,
ax_anim_terminator
sSwabluAnims_4_4:
ax_anim 2, 0, 91, -2, 2, -2, 2,
ax_anim 6, 2, 92, -3, 3, -3, 3,
ax_anim 2, 0, 90, -1, 1, -1, 1,
ax_anim 2, 1, 95, 2, -2, 2, -2,
ax_anim 2, 0, 94, 2, -2, 1, -3,
ax_anim 2, 0, 95, 2, -2, 2, -2,
ax_anim 2, 0, 94, 2, -2, 1, -3,
ax_anim 2, 0, 95, 2, -2, 2, -2,
ax_anim 2, 0, 94, 2, -2, 1, -3,
ax_anim 2, 0, 95, 2, -2, 2, -2,
ax_anim 2, 0, 90, 1, -1, 1, -1,
ax_anim_terminator
sSwabluAnims_4_5:
ax_anim 2, 0, 97, 0, 2, 0, 2,
ax_anim 6, 2, 98, 0, 3, 0, 3,
ax_anim 2, 0, 96, 0, 1, 0, 1,
ax_anim 2, 1, 101, 0, -3, 0, -3,
ax_anim 2, 0, 100, 0, -4, 0, -4,
ax_anim 2, 0, 101, 0, -3, 0, -3,
ax_anim 2, 0, 100, 0, -4, 0, -4,
ax_anim 2, 0, 101, 0, -3, 0, -3,
ax_anim 2, 0, 100, 0, -4, 0, -4,
ax_anim 2, 0, 101, 0, -3, 0, -3,
ax_anim 2, 0, 96, 0, -1, 0, -1,
ax_anim_terminator
sSwabluAnims_4_6:
ax_anim 2, 0, 103, 2, 2, 2, 2,
ax_anim 6, 2, 104, 3, 3, 3, 3,
ax_anim 2, 0, 102, 1, 1, 1, 1,
ax_anim 2, 1, 107, -2, -2, -2, -2,
ax_anim 2, 0, 106, -2, -2, -1, -3,
ax_anim 2, 0, 107, -2, -2, -2, -2,
ax_anim 2, 0, 106, -2, -2, -1, -3,
ax_anim 2, 0, 107, -2, -2, -2, -2,
ax_anim 2, 0, 106, -2, -2, -1, -3,
ax_anim 2, 0, 107, -2, -2, -2, -2,
ax_anim 2, 0, 102, -1, -1, -1, -1,
ax_anim_terminator
sSwabluAnims_4_7:
ax_anim 2, 0, 109, 2, 0, 2, 0,
ax_anim 6, 2, 110, 3, 0, 3, 0,
ax_anim 2, 0, 108, 1, 0, 1, 0,
ax_anim 2, 1, 113, -3, 0, -3, 0,
ax_anim 2, 0, 112, -3, 1, -3, 1,
ax_anim 2, 0, 113, -3, 0, -3, 0,
ax_anim 2, 0, 112, -3, 1, -3, 1,
ax_anim 2, 0, 113, -3, 0, -3, 0,
ax_anim 2, 0, 112, -3, 1, -3, 1,
ax_anim 2, 0, 113, -3, 0, -3, 0,
ax_anim 2, 0, 108, -1, 0, -1, 0,
ax_anim_terminator
sSwabluAnims_4_8:
ax_anim 2, 0, 115, 2, -2, 2, -2,
ax_anim 6, 2, 116, 3, -3, 3, -3,
ax_anim 2, 0, 114, 1, -1, 1, -1,
ax_anim 2, 1, 119, -2, 2, -2, 2,
ax_anim 2, 0, 118, -3, 1, -3, 1,
ax_anim 2, 0, 119, -2, 2, -2, 2,
ax_anim 2, 0, 118, -3, 1, -3, 1,
ax_anim 2, 0, 119, -2, 2, -2, 2,
ax_anim 2, 0, 118, -3, 1, -3, 1,
ax_anim 2, 0, 119, -2, 2, -2, 2,
ax_anim 2, 0, 114, -1, 1, -1, 1,
ax_anim_terminator
.align 2
sSwabluAnims_5_1:
ax_anim 1, 0, 120, 0, 0, 0, 0,
ax_anim 2, 0, 121, 0, 0, 0, 0,
ax_anim 1, 0, 120, 0, 0, 0, 0,
ax_anim 2, 0, 122, 0, 0, 0, 0,
ax_anim 1, 2, 120, 0, 0, 0, 0,
ax_anim 2, 0, 121, 0, 0, 0, 0,
ax_anim 1, 0, 120, 0, 0, 0, 0,
ax_anim 2, 0, 122, 0, 0, 0, 0,
ax_anim 1, 0, 120, 0, 0, 0, 0,
ax_anim 2, 0, 121, 0, 0, 0, 0,
ax_anim 1, 0, 120, 0, 0, 0, 0,
ax_anim 2, 0, 122, 0, 0, 0, 0,
ax_anim 1, 0, 120, 0, 0, 0, 0,
ax_anim 2, 0, 121, 0, 0, 0, 0,
ax_anim 1, 0, 120, 0, 0, 0, 0,
ax_anim 2, 0, 122, 0, 0, 0, 0,
ax_anim_terminator
sSwabluAnims_5_2:
ax_anim 1, 0, 123, 0, 0, 0, 0,
ax_anim 2, 0, 124, 0, 0, 0, 0,
ax_anim 1, 0, 123, 0, 0, 0, 0,
ax_anim 2, 0, 125, 0, 0, 0, 0,
ax_anim 1, 2, 123, 0, 0, 0, 0,
ax_anim 2, 0, 124, 0, 0, 0, 0,
ax_anim 1, 0, 123, 0, 0, 0, 0,
ax_anim 2, 0, 125, 0, 0, 0, 0,
ax_anim 1, 0, 123, 0, 0, 0, 0,
ax_anim 2, 0, 124, 0, 0, 0, 0,
ax_anim 1, 0, 123, 0, 0, 0, 0,
ax_anim 2, 0, 125, 0, 0, 0, 0,
ax_anim 1, 0, 123, 0, 0, 0, 0,
ax_anim 2, 0, 124, 0, 0, 0, 0,
ax_anim 1, 0, 123, 0, 0, 0, 0,
ax_anim 2, 0, 125, 0, 0, 0, 0,
ax_anim_terminator
sSwabluAnims_5_3:
ax_anim 1, 0, 126, 0, 0, 0, 0,
ax_anim 2, 0, 127, 0, 0, 0, 0,
ax_anim 1, 0, 126, 0, 0, 0, 0,
ax_anim 2, 0, 128, 0, 0, 0, 0,
ax_anim 1, 2, 126, 0, 0, 0, 0,
ax_anim 2, 0, 127, 0, 0, 0, 0,
ax_anim 1, 0, 126, 0, 0, 0, 0,
ax_anim 2, 0, 128, 0, 0, 0, 0,
ax_anim 1, 0, 126, 0, 0, 0, 0,
ax_anim 2, 0, 127, 0, 0, 0, 0,
ax_anim 1, 0, 126, 0, 0, 0, 0,
ax_anim 2, 0, 128, 0, 0, 0, 0,
ax_anim 1, 0, 126, 0, 0, 0, 0,
ax_anim 2, 0, 127, 0, 0, 0, 0,
ax_anim 1, 0, 126, 0, 0, 0, 0,
ax_anim 2, 0, 128, 0, 0, 0, 0,
ax_anim_terminator
sSwabluAnims_5_4:
ax_anim 1, 0, 129, 0, 0, 0, 0,
ax_anim 2, 0, 130, 0, 0, 0, 0,
ax_anim 1, 0, 129, 0, 0, 0, 0,
ax_anim 2, 0, 131, 0, 0, 0, 0,
ax_anim 1, 2, 129, 0, 0, 0, 0,
ax_anim 2, 0, 130, 0, 0, 0, 0,
ax_anim 1, 0, 129, 0, 0, 0, 0,
ax_anim 2, 0, 131, 0, 0, 0, 0,
ax_anim 1, 0, 129, 0, 0, 0, 0,
ax_anim 2, 0, 130, 0, 0, 0, 0,
ax_anim 1, 0, 129, 0, 0, 0, 0,
ax_anim 2, 0, 131, 0, 0, 0, 0,
ax_anim 1, 0, 129, 0, 0, 0, 0,
ax_anim 2, 0, 130, 0, 0, 0, 0,
ax_anim 1, 0, 129, 0, 0, 0, 0,
ax_anim 2, 0, 131, 0, 0, 0, 0,
ax_anim_terminator
sSwabluAnims_5_5:
ax_anim 1, 0, 132, 0, 0, 0, 0,
ax_anim 2, 0, 133, 0, 0, 0, 0,
ax_anim 1, 0, 132, 0, 0, 0, 0,
ax_anim 2, 0, 134, 0, 0, 0, 0,
ax_anim 1, 2, 132, 0, 0, 0, 0,
ax_anim 2, 0, 133, 0, 0, 0, 0,
ax_anim 1, 0, 132, 0, 0, 0, 0,
ax_anim 2, 0, 134, 0, 0, 0, 0,
ax_anim 1, 0, 132, 0, 0, 0, 0,
ax_anim 2, 0, 133, 0, 0, 0, 0,
ax_anim 1, 0, 132, 0, 0, 0, 0,
ax_anim 2, 0, 134, 0, 0, 0, 0,
ax_anim 1, 0, 132, 0, 0, 0, 0,
ax_anim 2, 0, 133, 0, 0, 0, 0,
ax_anim 1, 0, 132, 0, 0, 0, 0,
ax_anim 2, 0, 134, 0, 0, 0, 0,
ax_anim_terminator
sSwabluAnims_5_6:
ax_anim 1, 0, 135, 0, 0, 0, 0,
ax_anim 2, 0, 136, 0, 0, 0, 0,
ax_anim 1, 0, 135, 0, 0, 0, 0,
ax_anim 2, 0, 137, 0, 0, 0, 0,
ax_anim 1, 2, 135, 0, 0, 0, 0,
ax_anim 2, 0, 136, 0, 0, 0, 0,
ax_anim 1, 0, 135, 0, 0, 0, 0,
ax_anim 2, 0, 137, 0, 0, 0, 0,
ax_anim 1, 0, 135, 0, 0, 0, 0,
ax_anim 2, 0, 136, 0, 0, 0, 0,
ax_anim 1, 0, 135, 0, 0, 0, 0,
ax_anim 2, 0, 137, 0, 0, 0, 0,
ax_anim 1, 0, 135, 0, 0, 0, 0,
ax_anim 2, 0, 136, 0, 0, 0, 0,
ax_anim 1, 0, 135, 0, 0, 0, 0,
ax_anim 2, 0, 137, 0, 0, 0, 0,
ax_anim_terminator
sSwabluAnims_5_7:
ax_anim 1, 0, 138, 0, 0, 0, 0,
ax_anim 2, 0, 139, 0, 0, 0, 0,
ax_anim 1, 0, 138, 0, 0, 0, 0,
ax_anim 2, 0, 140, 0, 0, 0, 0,
ax_anim 1, 2, 138, 0, 0, 0, 0,
ax_anim 2, 0, 139, 0, 0, 0, 0,
ax_anim 1, 0, 138, 0, 0, 0, 0,
ax_anim 2, 0, 140, 0, 0, 0, 0,
ax_anim 1, 0, 138, 0, 0, 0, 0,
ax_anim 2, 0, 139, 0, 0, 0, 0,
ax_anim 1, 0, 138, 0, 0, 0, 0,
ax_anim 2, 0, 140, 0, 0, 0, 0,
ax_anim 1, 0, 138, 0, 0, 0, 0,
ax_anim 2, 0, 139, 0, 0, 0, 0,
ax_anim 1, 0, 138, 0, 0, 0, 0,
ax_anim 2, 0, 140, 0, 0, 0, 0,
ax_anim_terminator
sSwabluAnims_5_8:
ax_anim 1, 0, 141, 0, 0, 0, 0,
ax_anim 2, 0, 142, 0, 0, 0, 0,
ax_anim 1, 0, 141, 0, 0, 0, 0,
ax_anim 2, 0, 143, 0, 0, 0, 0,
ax_anim 1, 2, 141, 0, 0, 0, 0,
ax_anim 2, 0, 142, 0, 0, 0, 0,
ax_anim 1, 0, 141, 0, 0, 0, 0,
ax_anim 2, 0, 143, 0, 0, 0, 0,
ax_anim 1, 0, 141, 0, 0, 0, 0,
ax_anim 2, 0, 142, 0, 0, 0, 0,
ax_anim 1, 0, 141, 0, 0, 0, 0,
ax_anim 2, 0, 143, 0, 0, 0, 0,
ax_anim 1, 0, 141, 0, 0, 0, 0,
ax_anim 2, 0, 142, 0, 0, 0, 0,
ax_anim 1, 0, 141, 0, 0, 0, 0,
ax_anim 2, 0, 143, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sSwabluAnims_6_1:
ax_anim 30, 0, 144, 0, 0, 0, 0,
ax_anim 35, 0, 145, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sSwabluAnims_7_1:
ax_anim 2, 0, 146, 0, -4, 0, -4,
ax_anim 8, 0, 146, 0, -5, 0, -5,
ax_anim_terminator
sSwabluAnims_7_2:
ax_anim 2, 0, 147, -4, -4, -4, -4,
ax_anim 8, 0, 147, -5, -5, -5, -5,
ax_anim_terminator
sSwabluAnims_7_3:
ax_anim 2, 0, 148, -4, 0, -4, 0,
ax_anim 8, 0, 148, -5, 0, -5, 0,
ax_anim_terminator
sSwabluAnims_7_4:
ax_anim 2, 0, 149, -4, 4, -4, 4,
ax_anim 8, 0, 149, -5, 5, -5, 5,
ax_anim_terminator
sSwabluAnims_7_5:
ax_anim 2, 0, 150, 0, 4, 0, 4,
ax_anim 8, 0, 150, 0, 5, 0, 5,
ax_anim_terminator
sSwabluAnims_7_6:
ax_anim 2, 0, 151, 4, 4, 4, 4,
ax_anim 8, 0, 151, 5, 5, 5, 5,
ax_anim_terminator
sSwabluAnims_7_7:
ax_anim 2, 0, 152, 4, 0, 4, 0,
ax_anim 8, 0, 152, 5, 0, 5, 0,
ax_anim_terminator
sSwabluAnims_7_8:
ax_anim 2, 0, 153, 4, -4, 4, -4,
ax_anim 8, 0, 153, 5, -5, 5, -5,
ax_anim_terminator
.align 2
sSwabluAnims_8_1:
ax_anim 4, 0, 154, 0, 0, 0, 0,
ax_anim 4, 0, 155, 0, -1, 0, 0,
ax_anim 4, 0, 154, 0, -2, 0, 0,
ax_anim 4, 0, 155, 0, -3, 0, 0,
ax_anim 6, 0, 154, 0, -4, 0, 0,
ax_anim 8, 0, 156, 0, -3, 0, 0,
ax_anim 8, 0, 156, 0, -2, 0, 0,
ax_anim 8, 0, 156, 0, -1, 0, 0,
ax_anim 8, 0, 156, 0, 0, 0, 0,
ax_anim_terminator
sSwabluAnims_8_2:
ax_anim 4, 0, 157, 0, 0, 0, 0,
ax_anim 4, 0, 158, 0, -1, 0, 0,
ax_anim 4, 0, 157, 0, -2, 0, 0,
ax_anim 4, 0, 158, 0, -3, 0, 0,
ax_anim 6, 0, 157, 0, -4, 0, 0,
ax_anim 8, 0, 159, 0, -3, 0, 0,
ax_anim 8, 0, 159, 0, -2, 0, 0,
ax_anim 8, 0, 159, 0, -1, 0, 0,
ax_anim 8, 0, 159, 0, 0, 0, 0,
ax_anim_terminator
sSwabluAnims_8_3:
ax_anim 4, 0, 160, 0, 0, 0, 0,
ax_anim 4, 0, 161, 0, -1, 0, 0,
ax_anim 4, 0, 160, 0, -2, 0, 0,
ax_anim 4, 0, 161, 0, -3, 0, 0,
ax_anim 6, 0, 160, 0, -4, 0, 0,
ax_anim 8, 0, 162, 0, -3, 0, 0,
ax_anim 8, 0, 162, 0, -2, 0, 0,
ax_anim 8, 0, 162, 0, -1, 0, 0,
ax_anim 8, 0, 162, 0, 0, 0, 0,
ax_anim_terminator
sSwabluAnims_8_4:
ax_anim 4, 0, 163, 0, 0, 0, 0,
ax_anim 4, 0, 164, 0, -1, 0, 0,
ax_anim 4, 0, 163, 0, -2, 0, 0,
ax_anim 4, 0, 164, 0, -3, 0, 0,
ax_anim 6, 0, 163, 0, -4, 0, 0,
ax_anim 8, 0, 165, 0, -3, 0, 0,
ax_anim 8, 0, 165, 0, -2, 0, 0,
ax_anim 8, 0, 165, 0, -1, 0, 0,
ax_anim 8, 0, 165, 0, 0, 0, 0,
ax_anim_terminator
sSwabluAnims_8_5:
ax_anim 4, 0, 166, 0, 0, 0, 0,
ax_anim 4, 0, 167, 0, -1, 0, 0,
ax_anim 4, 0, 166, 0, -2, 0, 0,
ax_anim 4, 0, 167, 0, -3, 0, 0,
ax_anim 6, 0, 166, 0, -4, 0, 0,
ax_anim 8, 0, 168, 0, -3, 0, 0,
ax_anim 8, 0, 168, 0, -2, 0, 0,
ax_anim 8, 0, 168, 0, -1, 0, 0,
ax_anim 8, 0, 168, 0, 0, 0, 0,
ax_anim_terminator
sSwabluAnims_8_6:
ax_anim 4, 0, 169, 0, 0, 0, 0,
ax_anim 4, 0, 170, 0, -1, 0, 0,
ax_anim 4, 0, 169, 0, -2, 0, 0,
ax_anim 4, 0, 170, 0, -3, 0, 0,
ax_anim 6, 0, 169, 0, -4, 0, 0,
ax_anim 8, 0, 171, 0, -3, 0, 0,
ax_anim 8, 0, 171, 0, -2, 0, 0,
ax_anim 8, 0, 171, 0, -1, 0, 0,
ax_anim 8, 0, 171, 0, 0, 0, 0,
ax_anim_terminator
sSwabluAnims_8_7:
ax_anim 4, 0, 172, 0, 0, 0, 0,
ax_anim 4, 0, 173, 0, -1, 0, 0,
ax_anim 4, 0, 172, 0, -2, 0, 0,
ax_anim 4, 0, 173, 0, -3, 0, 0,
ax_anim 6, 0, 172, 0, -4, 0, 0,
ax_anim 8, 0, 174, 0, -3, 0, 0,
ax_anim 8, 0, 174, 0, -2, 0, 0,
ax_anim 8, 0, 174, 0, -1, 0, 0,
ax_anim 8, 0, 174, 0, 0, 0, 0,
ax_anim_terminator
sSwabluAnims_8_8:
ax_anim 4, 0, 175, 0, 0, 0, 0,
ax_anim 4, 0, 176, 0, -1, 0, 0,
ax_anim 4, 0, 175, 0, -2, 0, 0,
ax_anim 4, 0, 176, 0, -3, 0, 0,
ax_anim 6, 0, 175, 0, -4, 0, 0,
ax_anim 8, 0, 177, 0, -3, 0, 0,
ax_anim 8, 0, 177, 0, -2, 0, 0,
ax_anim 8, 0, 177, 0, -1, 0, 0,
ax_anim 8, 0, 177, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sSwabluAnims_9_1:
ax_anim 2, 0, 178, 0, 0, 0, 0,
ax_anim 1, 0, 179, 5, 3, 6, 3,
ax_anim 2, 0, 180, 9, 12, 8, 9,
ax_anim 2, 0, 181, 6, 21, 7, 15,
ax_anim 3, 0, 182, 0, 24, 0, 18,
ax_anim 2, 3, 183, -6, 21, -7, 15,
ax_anim 2, 0, 184, -9, 12, -8, 9,
ax_anim 1, 0, 185, -5, 3, -6, 3,
ax_anim 1, 0, 178, 0, 0, 0, 0,
ax_anim_terminator
sSwabluAnims_9_2:
ax_anim 2, 0, 185, 0, 0, 0, 0,
ax_anim 1, 0, 178, 8, 0, 8, 0,
ax_anim 2, 0, 179, 19, 6, 19, 6,
ax_anim 2, 0, 180, 24, 14, 24, 13,
ax_anim 3, 0, 181, 22, 22, 22, 19,
ax_anim 2, 3, 182, 13, 25, 13, 23,
ax_anim 2, 0, 183, 3, 21, 3, 21,
ax_anim 1, 0, 184, 0, 9, 0, 9,
ax_anim 1, 0, 185, 0, 0, 0, 0,
ax_anim_terminator
sSwabluAnims_9_3:
ax_anim 2, 0, 184, 0, 0, 0, 0,
ax_anim 1, 0, 185, 4, -6, 4, -6,
ax_anim 2, 0, 178, 11, -8, 11, -8,
ax_anim 2, 0, 179, 19, -4, 19, -4,
ax_anim 3, 0, 180, 23, 3, 23, 0,
ax_anim 2, 3, 181, 20, 10, 20, 8,
ax_anim 2, 0, 182, 11, 14, 11, 14,
ax_anim 1, 0, 183, 2, 10, 2, 10,
ax_anim 1, 0, 184, 0, 0, 0, 0,
ax_anim_terminator
sSwabluAnims_9_4:
ax_anim 2, 0, 183, 0, 0, 0, 0,
ax_anim 1, 0, 184, 0, -7, 0, -7,
ax_anim 2, 0, 185, 3, -15, 3, -15,
ax_anim 2, 0, 178, 11, -21, 11, -21,
ax_anim 3, 0, 179, 20, -20, 20, -22,
ax_anim 2, 3, 180, 25, -12, 25, -12,
ax_anim 2, 0, 181, 20, -2, 20, -2,
ax_anim 1, 0, 182, 10, 2, 10, 2,
ax_anim 1, 0, 183, 0, 0, 0, 0,
ax_anim_terminator
sSwabluAnims_9_5:
ax_anim 2, 0, 182, 0, 0, 0, 0,
ax_anim 1, 0, 183, -5, -2, -5, -2,
ax_anim 2, 0, 184, -8, -9, -8, -9,
ax_anim 2, 0, 185, -7, -17, -7, -18,
ax_anim 3, 0, 178, 0, -21, 0, -23,
ax_anim 2, 3, 179, 7, -17, 7, -18,
ax_anim 2, 0, 180, 8, -9, 8, -9,
ax_anim 1, 0, 181, 5, -2, 5, -2,
ax_anim 1, 0, 182, 0, 0, 0, 0,
ax_anim_terminator
sSwabluAnims_9_6:
ax_anim 2, 0, 181, 0, 0, 0, 0,
ax_anim 1, 0, 180, 0, -7, 0, -7,
ax_anim 2, 0, 179, -3, -15, -3, -15,
ax_anim 2, 0, 178, -11, -21, -11, -21,
ax_anim 3, 0, 185, -20, -20, -20, -22,
ax_anim 2, 3, 184, -25, -12, -25, -12,
ax_anim 2, 0, 183, -20, -2, -20, -2,
ax_anim 1, 0, 182, -10, 2, -10, 2,
ax_anim 1, 0, 181, 0, 0, 0, 0,
ax_anim_terminator
sSwabluAnims_9_7:
ax_anim 2, 0, 180, 0, 0, 0, 0,
ax_anim 1, 0, 179, -4, -6, -4, -6,
ax_anim 2, 0, 178, -11, -8, -11, -8,
ax_anim 2, 0, 185, -19, -4, -19, -4,
ax_anim 3, 0, 184, -23, 3, -23, 0,
ax_anim 2, 3, 183, -20, 10, -20, 8,
ax_anim 2, 0, 182, -11, 14, -11, 14,
ax_anim 1, 0, 181, -2, 10, -2, 10,
ax_anim 1, 0, 180, 0, 0, 0, 0,
ax_anim_terminator
sSwabluAnims_9_8:
ax_anim 2, 0, 179, 0, 0, 0, 0,
ax_anim 1, 0, 178, -8, 0, -8, 0,
ax_anim 2, 0, 185, -19, 6, -19, 6,
ax_anim 2, 0, 184, -24, 14, -24, 13,
ax_anim 3, 0, 183, -22, 22, -22, 19,
ax_anim 2, 3, 182, -13, 25, -13, 23,
ax_anim 2, 0, 181, -3, 21, -3, 21,
ax_anim 1, 0, 180, 0, 9, 0, 9,
ax_anim 1, 0, 179, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sSwabluAnims_10_1:
ax_anim 2, 0, 186, 0, 0, 0, 0,
ax_anim 2, 0, 186, 6, 0, 6, 0,
ax_anim 2, 0, 186, -6, 0, -6, 0,
ax_anim 2, 0, 186, 10, 0, 10, 0,
ax_anim 2, 0, 186, -10, 0, -10, 0,
ax_anim 2, 0, 186, 12, 0, 12, 0,
ax_anim 3, 0, 186, -12, 0, -12, 0,
ax_anim 3, 0, 186, 13, 0, 13, 0,
ax_anim 3, 0, 186, -13, 0, -13, 0,
ax_anim 2, 0, 186, 12, 0, 12, 0,
ax_anim 3, 0, 186, -12, 0, -12, 0,
ax_anim 2, 0, 186, 10, 0, 10, 0,
ax_anim 2, 0, 186, -10, 0, -10, 0,
ax_anim 2, 0, 186, 6, 0, 6, 0,
ax_anim 2, 0, 186, -6, 0, -6, 0,
ax_anim 2, 0, 186, 0, 0, 0, 0,
ax_anim_terminator
sSwabluAnims_10_2:
ax_anim 2, 0, 187, 0, 0, 0, 0,
ax_anim 2, 0, 187, 6, -6, 6, -6,
ax_anim 2, 0, 187, -6, 6, -6, 6,
ax_anim 2, 0, 187, 10, -10, 10, -10,
ax_anim 2, 0, 187, -10, 10, -10, 10,
ax_anim 2, 0, 187, 12, -12, 12, -12,
ax_anim 3, 0, 187, -12, 12, -12, 12,
ax_anim 3, 0, 187, 13, -13, 13, -13,
ax_anim 3, 0, 187, -13, 13, -13, 13,
ax_anim 2, 0, 187, 12, -12, 12, -12,
ax_anim 3, 0, 187, -12, 12, -12, 12,
ax_anim 2, 0, 187, 10, -10, 10, -10,
ax_anim 2, 0, 187, -10, 10, -10, 10,
ax_anim 2, 0, 187, 6, -6, 6, -6,
ax_anim 2, 0, 187, -6, 6, -6, 6,
ax_anim 2, 0, 187, 0, 0, 0, 0,
ax_anim_terminator
sSwabluAnims_10_3:
ax_anim 2, 0, 188, 0, 0, 0, 0,
ax_anim 2, 0, 188, 0, -6, 0, -6,
ax_anim 2, 0, 188, 0, 6, 0, 6,
ax_anim 2, 0, 188, 0, -10, 0, -10,
ax_anim 2, 0, 188, 0, 10, 0, 10,
ax_anim 2, 0, 188, 0, -12, 0, -12,
ax_anim 3, 0, 188, 0, 12, 0, 12,
ax_anim 3, 0, 188, 0, -13, 0, -13,
ax_anim 3, 0, 188, 0, 13, 0, 13,
ax_anim 2, 0, 188, 0, -12, 0, -12,
ax_anim 3, 0, 188, 0, 12, 0, 12,
ax_anim 2, 0, 188, 0, -10, 0, -10,
ax_anim 2, 0, 188, 0, 10, 0, 10,
ax_anim 2, 0, 188, 0, -6, 0, -6,
ax_anim 2, 0, 188, 0, 6, 0, 6,
ax_anim 2, 0, 188, 0, 0, 0, 0,
ax_anim_terminator
sSwabluAnims_10_4:
ax_anim 2, 0, 189, 0, 0, 0, 0,
ax_anim 2, 0, 189, -6, -6, -6, -6,
ax_anim 2, 0, 189, 6, 6, 6, 6,
ax_anim 2, 0, 189, -10, -10, -10, -10,
ax_anim 2, 0, 189, 10, 10, 10, 10,
ax_anim 2, 0, 189, -12, -12, -12, -12,
ax_anim 3, 0, 189, 12, 12, 12, 12,
ax_anim 3, 0, 189, -13, -13, -13, -13,
ax_anim 3, 0, 189, 13, 13, 13, 13,
ax_anim 2, 0, 189, -12, -12, -12, -12,
ax_anim 3, 0, 189, 12, 12, 12, 12,
ax_anim 2, 0, 189, -10, -10, -10, -10,
ax_anim 2, 0, 189, 10, 10, 10, 10,
ax_anim 2, 0, 189, -6, -6, -6, -6,
ax_anim 2, 0, 189, 6, 6, 6, 6,
ax_anim 2, 0, 189, 0, 0, 0, 0,
ax_anim_terminator
sSwabluAnims_10_5:
ax_anim 2, 0, 190, 0, 0, 0, 0,
ax_anim 2, 0, 190, 6, 0, 6, 0,
ax_anim 2, 0, 190, -6, 0, -6, 0,
ax_anim 2, 0, 190, 10, 0, 10, 0,
ax_anim 2, 0, 190, -10, 0, -10, 0,
ax_anim 2, 0, 190, 12, 0, 12, 0,
ax_anim 3, 0, 190, -12, 0, -12, 0,
ax_anim 3, 0, 190, 13, 0, 13, 0,
ax_anim 3, 0, 190, -13, 0, -13, 0,
ax_anim 2, 0, 190, 12, 0, 12, 0,
ax_anim 3, 0, 190, -12, 0, -12, 0,
ax_anim 2, 0, 190, 10, 0, 10, 0,
ax_anim 2, 0, 190, -10, 0, -10, 0,
ax_anim 2, 0, 190, 6, 0, 6, 0,
ax_anim 2, 0, 190, -6, 0, -6, 0,
ax_anim 2, 0, 190, 0, 0, 0, 0,
ax_anim_terminator
sSwabluAnims_10_6:
ax_anim 2, 0, 191, 0, 0, 0, 0,
ax_anim 2, 0, 191, 6, -6, 6, -6,
ax_anim 2, 0, 191, -6, 6, -6, 6,
ax_anim 2, 0, 191, 10, -10, 10, -10,
ax_anim 2, 0, 191, -10, 10, -10, 10,
ax_anim 2, 0, 191, 12, -12, 12, -12,
ax_anim 3, 0, 191, -12, 12, -12, 12,
ax_anim 3, 0, 191, 13, -13, 13, -13,
ax_anim 3, 0, 191, -13, 13, -13, 13,
ax_anim 2, 0, 191, 12, -12, 12, -12,
ax_anim 3, 0, 191, -12, 12, -12, 12,
ax_anim 2, 0, 191, 10, -10, 10, -10,
ax_anim 2, 0, 191, -10, 10, -10, 10,
ax_anim 2, 0, 191, 6, -6, 6, -6,
ax_anim 2, 0, 191, -6, 6, -6, 6,
ax_anim 2, 0, 191, 0, 0, 0, 0,
ax_anim_terminator
sSwabluAnims_10_7:
ax_anim 2, 0, 192, 0, 0, 0, 0,
ax_anim 2, 0, 192, 0, -6, 0, -6,
ax_anim 2, 0, 192, 0, 6, 0, 6,
ax_anim 2, 0, 192, 0, -10, 0, -10,
ax_anim 2, 0, 192, 0, 10, 0, 10,
ax_anim 2, 0, 192, 0, -12, 0, -12,
ax_anim 3, 0, 192, 0, 12, 0, 12,
ax_anim 3, 0, 192, 0, -13, 0, -13,
ax_anim 3, 0, 192, 0, 13, 0, 13,
ax_anim 2, 0, 192, 0, -12, 0, -12,
ax_anim 3, 0, 192, 0, 12, 0, 12,
ax_anim 2, 0, 192, 0, -10, 0, -10,
ax_anim 2, 0, 192, 0, 10, 0, 10,
ax_anim 2, 0, 192, 0, -6, 0, -6,
ax_anim 2, 0, 192, 0, 6, 0, 6,
ax_anim 2, 0, 192, 0, 0, 0, 0,
ax_anim_terminator
sSwabluAnims_10_8:
ax_anim 2, 0, 193, 0, 0, 0, 0,
ax_anim 2, 0, 193, -6, -6, -6, -6,
ax_anim 2, 0, 193, 6, 6, 6, 6,
ax_anim 2, 0, 193, -10, -10, -10, -10,
ax_anim 2, 0, 193, 10, 10, 10, 10,
ax_anim 2, 0, 193, -12, -12, -12, -12,
ax_anim 3, 0, 193, 12, 12, 12, 12,
ax_anim 3, 0, 193, -13, -13, -13, -13,
ax_anim 3, 0, 193, 13, 13, 13, 13,
ax_anim 2, 0, 193, -12, -12, -12, -12,
ax_anim 3, 0, 193, 12, 12, 12, 12,
ax_anim 2, 0, 193, -10, -10, -10, -10,
ax_anim 2, 0, 193, 10, 10, 10, 10,
ax_anim 2, 0, 193, -6, -6, -6, -6,
ax_anim 2, 0, 193, 6, 6, 6, 6,
ax_anim 2, 0, 193, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sSwabluAnims_11_1:
ax_anim 2, 0, 194, 0, 0, 0, 0,
ax_anim 1, 0, 195, 0, -10, 0, 0,
ax_anim 2, 0, 195, 0, -16, 0, 0,
ax_anim 3, 0, 195, 0, -20, 0, 0,
ax_anim 4, 0, 195, 0, -21, 0, 0,
ax_anim 4, 0, 194, 0, -23, 0, 0,
ax_anim 3, 0, 196, 0, -22, 0, 0,
ax_anim 2, 0, 196, 0, -18, 0, 0,
ax_anim 1, 0, 196, 0, -12, 0, 0,
ax_anim 2, 2, 196, 0, 4, 0, 0,
ax_anim_terminator
sSwabluAnims_11_2:
ax_anim 2, 0, 197, 0, 0, 0, 0,
ax_anim 1, 0, 198, 0, -10, 0, 0,
ax_anim 2, 0, 198, 0, -16, 0, 0,
ax_anim 3, 0, 198, 0, -20, 0, 0,
ax_anim 4, 0, 198, 0, -21, 0, 0,
ax_anim 4, 0, 197, 0, -23, 0, 0,
ax_anim 3, 0, 199, 0, -22, 0, 0,
ax_anim 2, 0, 199, 0, -18, 0, 0,
ax_anim 1, 0, 199, 0, -12, 0, 0,
ax_anim 2, 2, 199, 0, 3, 0, 0,
ax_anim_terminator
sSwabluAnims_11_3:
ax_anim 2, 0, 200, 0, 0, 0, 0,
ax_anim 1, 0, 201, 0, -10, 0, 0,
ax_anim 2, 0, 201, 0, -16, 0, 0,
ax_anim 3, 0, 201, 0, -20, 0, 0,
ax_anim 4, 0, 201, 0, -21, 0, 0,
ax_anim 4, 0, 200, 0, -23, 0, 0,
ax_anim 3, 0, 202, 0, -22, 0, 0,
ax_anim 2, 0, 202, 0, -18, 0, 0,
ax_anim 1, 0, 202, 0, -12, 0, 0,
ax_anim 2, 2, 202, 0, 3, 0, 0,
ax_anim_terminator
sSwabluAnims_11_4:
ax_anim 2, 0, 203, 0, 0, 0, 0,
ax_anim 1, 0, 204, 0, -10, 0, 0,
ax_anim 2, 0, 204, 0, -16, 0, 0,
ax_anim 3, 0, 204, 0, -20, 0, 0,
ax_anim 4, 0, 204, 0, -21, 0, 0,
ax_anim 4, 0, 203, 0, -22, 0, 0,
ax_anim 3, 0, 205, 0, -21, 0, 0,
ax_anim 2, 0, 205, 0, -17, 0, 0,
ax_anim 1, 0, 205, 0, -11, 0, 0,
ax_anim 2, 2, 205, 0, 4, 0, 0,
ax_anim_terminator
sSwabluAnims_11_5:
ax_anim 2, 0, 206, 0, 0, 0, 0,
ax_anim 1, 0, 207, 0, -10, 0, 0,
ax_anim 2, 0, 207, 0, -16, 0, 0,
ax_anim 3, 0, 207, 0, -20, 0, 0,
ax_anim 4, 0, 207, 0, -21, 0, 0,
ax_anim 4, 0, 206, 0, -23, 0, 0,
ax_anim 3, 0, 208, 0, -22, 0, 0,
ax_anim 2, 0, 208, 0, -18, 0, 0,
ax_anim 1, 0, 208, 0, -12, 0, 0,
ax_anim 2, 2, 208, 0, 4, 0, 0,
ax_anim_terminator
sSwabluAnims_11_6:
ax_anim 2, 0, 209, 0, 0, 0, 0,
ax_anim 1, 0, 210, 0, -10, 0, 0,
ax_anim 2, 0, 210, 0, -16, 0, 0,
ax_anim 3, 0, 210, 0, -20, 0, 0,
ax_anim 4, 0, 210, 0, -21, 0, 0,
ax_anim 4, 0, 209, 0, -22, 0, 0,
ax_anim 3, 0, 211, 0, -21, 0, 0,
ax_anim 2, 0, 211, 0, -17, 0, 0,
ax_anim 1, 0, 211, 0, -11, 0, 0,
ax_anim 2, 2, 211, 0, 4, 0, 0,
ax_anim_terminator
sSwabluAnims_11_7:
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 1, 0, 213, 0, -10, 0, 0,
ax_anim 2, 0, 213, 0, -16, 0, 0,
ax_anim 3, 0, 213, 0, -20, 0, 0,
ax_anim 4, 0, 213, 0, -21, 0, 0,
ax_anim 4, 0, 212, 0, -23, 0, 0,
ax_anim 3, 0, 214, 0, -22, 0, 0,
ax_anim 2, 0, 214, 0, -18, 0, 0,
ax_anim 1, 0, 214, 0, -12, 0, 0,
ax_anim 2, 2, 214, 0, 3, 0, 0,
ax_anim_terminator
sSwabluAnims_11_8:
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 1, 0, 216, 0, -10, 0, 0,
ax_anim 2, 0, 216, 0, -16, 0, 0,
ax_anim 3, 0, 216, 0, -20, 0, 0,
ax_anim 4, 0, 216, 0, -21, 0, 0,
ax_anim 4, 0, 215, 0, -23, 0, 0,
ax_anim 3, 0, 217, 0, -22, 0, 0,
ax_anim 2, 0, 217, 0, -18, 0, 0,
ax_anim 1, 0, 217, 0, -12, 0, 0,
ax_anim 2, 2, 217, 0, 3, 0, 0,
ax_anim_terminator
.align 2
sSwabluAnims_12_1:
ax_anim 2, 0, 218, 1, 0, 1, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 218, 1, 0, 1, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 218, 1, 0, 1, 0,
ax_anim 2, 2, 218, 0, 0, 0, 0,
ax_anim 2, 0, 218, 1, 0, 1, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 218, 1, 0, 1, 0,
ax_anim 2, 1, 218, 0, 0, 0, 0,
ax_anim_terminator
sSwabluAnims_12_2:
ax_anim 2, 0, 225, 1, -1, 1, -1,
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 2, 0, 225, 1, -1, 1, -1,
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 2, 0, 225, 1, -1, 1, -1,
ax_anim 2, 2, 225, 0, 0, 0, 0,
ax_anim 2, 0, 225, 1, -1, 1, -1,
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 2, 0, 225, 1, -1, 1, -1,
ax_anim 2, 1, 225, 0, 0, 0, 0,
ax_anim_terminator
sSwabluAnims_12_3:
ax_anim 2, 0, 224, 0, -1, 0, -1,
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 2, 0, 224, 0, -1, 0, -1,
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 2, 0, 224, 0, -1, 0, -1,
ax_anim 2, 2, 224, 0, 0, 0, 0,
ax_anim 2, 0, 224, 0, -1, 0, -1,
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 2, 0, 224, 0, -1, 0, -1,
ax_anim 2, 1, 224, 0, 0, 0, 0,
ax_anim_terminator
sSwabluAnims_12_4:
ax_anim 2, 0, 223, -1, -1, -1, -1,
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 2, 0, 223, -1, -1, -1, -1,
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 2, 0, 223, -1, -1, -1, -1,
ax_anim 2, 2, 223, 0, 0, 0, 0,
ax_anim 2, 0, 223, -1, -1, -1, -1,
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 2, 0, 223, -1, -1, -1, -1,
ax_anim 2, 1, 223, 0, 0, 0, 0,
ax_anim_terminator
sSwabluAnims_12_5:
ax_anim 2, 0, 222, 1, 0, 1, 0,
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 0, 222, 1, 0, 1, 0,
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 0, 222, 1, 0, 1, 0,
ax_anim 2, 2, 222, 0, 0, 0, 0,
ax_anim 2, 0, 222, 1, 0, 1, 0,
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 0, 222, 1, 0, 1, 0,
ax_anim 2, 1, 222, 0, 0, 0, 0,
ax_anim_terminator
sSwabluAnims_12_6:
ax_anim 2, 0, 221, 1, -1, 1, -1,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 221, 1, -1, 1, -1,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 221, 1, -1, 1, -1,
ax_anim 2, 2, 221, 0, 0, 0, 0,
ax_anim 2, 0, 221, 1, -1, 1, -1,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 221, 1, -1, 1, -1,
ax_anim 2, 1, 221, 0, 0, 0, 0,
ax_anim_terminator
sSwabluAnims_12_7:
ax_anim 2, 0, 220, 0, -1, 0, -1,
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, -1, 0, -1,
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, -1, 0, -1,
ax_anim 2, 2, 220, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, -1, 0, -1,
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, -1, 0, -1,
ax_anim 2, 1, 220, 0, 0, 0, 0,
ax_anim_terminator
sSwabluAnims_12_8:
ax_anim 2, 0, 219, -1, -1, -1, -1,
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 0, 219, -1, -1, -1, -1,
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 0, 219, -1, -1, -1, -1,
ax_anim 2, 2, 219, 0, 0, 0, 0,
ax_anim 2, 0, 219, -1, -1, -1, -1,
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 0, 219, -1, -1, -1, -1,
ax_anim 2, 1, 219, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sSwabluAnims_13_1:
ax_anim 2, 0, 226, 0, 0, 0, 0,
ax_anim 2, 0, 227, 0, 0, 0, 0,
ax_anim 2, 0, 228, 0, 0, 0, 0,
ax_anim 2, 0, 229, 0, 0, 0, 0,
ax_anim 2, 0, 230, 0, 0, 0, 0,
ax_anim 2, 0, 231, 0, 0, 0, 0,
ax_anim 2, 0, 232, 0, 0, 0, 0,
ax_anim 2, 0, 233, 0, 0, 0, 0,
ax_anim 2, 2, 226, 0, 0, 0, 0,
ax_anim_terminator
sSwabluAnims_13_2:
ax_anim 2, 0, 233, 0, 0, 0, 0,
ax_anim 2, 0, 226, 0, 0, 0, 0,
ax_anim 2, 0, 227, 0, 0, 0, 0,
ax_anim 2, 0, 228, 0, 0, 0, 0,
ax_anim 2, 0, 229, 0, 0, 0, 0,
ax_anim 2, 0, 230, 0, 0, 0, 0,
ax_anim 2, 0, 231, 0, 0, 0, 0,
ax_anim 2, 0, 232, 0, 0, 0, 0,
ax_anim 2, 2, 233, 0, 0, 0, 0,
ax_anim_terminator
sSwabluAnims_13_3:
ax_anim 2, 0, 232, 0, 0, 0, 0,
ax_anim 2, 0, 233, 0, 0, 0, 0,
ax_anim 2, 0, 226, 0, 0, 0, 0,
ax_anim 2, 0, 227, 0, 0, 0, 0,
ax_anim 2, 0, 228, 0, 0, 0, 0,
ax_anim 2, 0, 229, 0, 0, 0, 0,
ax_anim 2, 0, 230, 0, 0, 0, 0,
ax_anim 2, 0, 231, 0, 0, 0, 0,
ax_anim 2, 2, 232, 0, 0, 0, 0,
ax_anim_terminator
sSwabluAnims_13_4:
ax_anim 2, 0, 231, 0, 0, 0, 0,
ax_anim 2, 0, 232, 0, 0, 0, 0,
ax_anim 2, 0, 233, 0, 0, 0, 0,
ax_anim 2, 0, 226, 0, 0, 0, 0,
ax_anim 2, 0, 227, 0, 0, 0, 0,
ax_anim 2, 0, 228, 0, 0, 0, 0,
ax_anim 2, 0, 229, 0, 0, 0, 0,
ax_anim 2, 0, 230, 0, 0, 0, 0,
ax_anim 2, 2, 231, 0, 0, 0, 0,
ax_anim_terminator
sSwabluAnims_13_5:
ax_anim 2, 0, 230, 0, 0, 0, 0,
ax_anim 2, 0, 231, 0, 0, 0, 0,
ax_anim 2, 0, 232, 0, 0, 0, 0,
ax_anim 2, 0, 233, 0, 0, 0, 0,
ax_anim 2, 0, 226, 0, 0, 0, 0,
ax_anim 2, 0, 227, 0, 0, 0, 0,
ax_anim 2, 0, 228, 0, 0, 0, 0,
ax_anim 2, 0, 229, 0, 0, 0, 0,
ax_anim 2, 2, 230, 0, 0, 0, 0,
ax_anim_terminator
sSwabluAnims_13_6:
ax_anim 2, 0, 229, 0, 0, 0, 0,
ax_anim 2, 0, 230, 0, 0, 0, 0,
ax_anim 2, 0, 231, 0, 0, 0, 0,
ax_anim 2, 0, 232, 0, 0, 0, 0,
ax_anim 2, 0, 233, 0, 0, 0, 0,
ax_anim 2, 0, 226, 0, 0, 0, 0,
ax_anim 2, 0, 227, 0, 0, 0, 0,
ax_anim 2, 0, 228, 0, 0, 0, 0,
ax_anim 2, 2, 229, 0, 0, 0, 0,
ax_anim_terminator
sSwabluAnims_13_7:
ax_anim 2, 0, 228, 0, 0, 0, 0,
ax_anim 2, 0, 229, 0, 0, 0, 0,
ax_anim 2, 0, 230, 0, 0, 0, 0,
ax_anim 2, 0, 231, 0, 0, 0, 0,
ax_anim 2, 0, 232, 0, 0, 0, 0,
ax_anim 2, 0, 233, 0, 0, 0, 0,
ax_anim 2, 0, 226, 0, 0, 0, 0,
ax_anim 2, 0, 227, 0, 0, 0, 0,
ax_anim 2, 2, 228, 0, 0, 0, 0,
ax_anim_terminator
sSwabluAnims_13_8:
ax_anim 2, 0, 227, 0, 0, 0, 0,
ax_anim 2, 0, 228, 0, 0, 0, 0,
ax_anim 2, 0, 229, 0, 0, 0, 0,
ax_anim 2, 0, 230, 0, 0, 0, 0,
ax_anim 2, 0, 231, 0, 0, 0, 0,
ax_anim 2, 0, 232, 0, 0, 0, 0,
ax_anim 2, 0, 233, 0, 0, 0, 0,
ax_anim 2, 0, 226, 0, 0, 0, 0,
ax_anim 2, 2, 227, 0, 0, 0, 0,
ax_anim_terminator
sSwabluGfx1:
.incbin "baserom.gba", 0x1398438, 0x100
sSwabluSprites1:
ax_sprite sSwabluGfx1, 0x100
ax_sprite_terminator
sSwabluGfx2:
.incbin "baserom.gba", 0x1398548, 0x200
sSwabluSprites2:
ax_sprite sSwabluGfx2, 0x200
ax_sprite_terminator
sSwabluGfx3:
.incbin "baserom.gba", 0x1398758, 0x100
sSwabluSprites3:
ax_sprite sSwabluGfx3, 0x100
ax_sprite_terminator
sSwabluGfx4:
.incbin "baserom.gba", 0x1398868, 0x200
sSwabluSprites4:
ax_sprite sSwabluGfx4, 0x200
ax_sprite_terminator
sSwabluGfx5:
.incbin "baserom.gba", 0x1398A78, 0x200
sSwabluSprites5:
ax_sprite sSwabluGfx5, 0x200
ax_sprite_terminator
sSwabluGfx6:
.incbin "baserom.gba", 0x1398C88, 0x200
sSwabluSprites6:
ax_sprite sSwabluGfx6, 0x200
ax_sprite_terminator
sSwabluGfx7:
.incbin "baserom.gba", 0x1398E98, 0x200
sSwabluSprites7:
ax_sprite sSwabluGfx7, 0x200
ax_sprite_terminator
sSwabluGfx8:
.incbin "baserom.gba", 0x13990A8, 0x100
sSwabluSprites8:
ax_sprite sSwabluGfx8, 0x100
ax_sprite_terminator
sSwabluGfx9:
.incbin "baserom.gba", 0x13991B8, 0x200
sSwabluSprites9:
ax_sprite sSwabluGfx9, 0x200
ax_sprite_terminator
sSwabluGfx10:
.incbin "baserom.gba", 0x13993C8, 0x200
sSwabluSprites10:
ax_sprite sSwabluGfx10, 0x200
ax_sprite_terminator
sSwabluGfx11:
.incbin "baserom.gba", 0x13995D8, 0x200
sSwabluSprites11:
ax_sprite sSwabluGfx11, 0x200
ax_sprite_terminator
sSwabluGfx12:
.incbin "baserom.gba", 0x13997E8, 0x200
sSwabluSprites12:
ax_sprite sSwabluGfx12, 0x200
ax_sprite_terminator
sSwabluGfx13:
.incbin "baserom.gba", 0x13999F8, 0x200
sSwabluSprites13:
ax_sprite sSwabluGfx13, 0x200
ax_sprite_terminator
sSwabluGfx14:
.incbin "baserom.gba", 0x1399C08, 0x200
sSwabluSprites14:
ax_sprite sSwabluGfx14, 0x200
ax_sprite_terminator
sSwabluGfx15:
.incbin "baserom.gba", 0x1399E18, 0x200
sSwabluSprites15:
ax_sprite sSwabluGfx15, 0x200
ax_sprite_terminator
sSwabluGfx16:
.incbin "baserom.gba", 0x139A028, 0x100
sSwabluSprites16:
ax_sprite sSwabluGfx16, 0x100
ax_sprite_terminator
sSwabluGfx17:
.incbin "baserom.gba", 0x139A138, 0x40
sSwabluGfx17_1:
.incbin "baserom.gba", 0x139A178, 0x80
sSwabluSprites17:
ax_sprite 0, 0x20
ax_sprite sSwabluGfx17, 0x40
ax_sprite 0, 0x20
ax_sprite sSwabluGfx17_1, 0x80
ax_sprite_terminator
sSwabluGfx18:
.incbin "baserom.gba", 0x139A220, 0x80
sSwabluSprites18:
ax_sprite sSwabluGfx18, 0x80
ax_sprite_terminator
sSwabluGfx19:
.incbin "baserom.gba", 0x139A2B0, 0x100
sSwabluSprites19:
ax_sprite sSwabluGfx19, 0x100
ax_sprite_terminator
sSwabluGfx20:
.incbin "baserom.gba", 0x139A3C0, 0x20
sSwabluSprites20:
ax_sprite sSwabluGfx20, 0x20
ax_sprite_terminator
sSwabluGfx21:
.incbin "baserom.gba", 0x139A3F0, 0x40
sSwabluSprites21:
ax_sprite sSwabluGfx21, 0x40
ax_sprite_terminator
sSwabluGfx22:
.incbin "baserom.gba", 0x139A440, 0x60
sSwabluGfx22_1:
.incbin "baserom.gba", 0x139A4A0, 0x60
sSwabluSprites22:
ax_sprite sSwabluGfx22, 0x60
ax_sprite 0, 0x20
ax_sprite sSwabluGfx22_1, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sSwabluGfx23:
.incbin "baserom.gba", 0x139A528, 0x60
sSwabluGfx23_1:
.incbin "baserom.gba", 0x139A588, 0x40
sSwabluSprites23:
ax_sprite sSwabluGfx23, 0x60
ax_sprite 0, 0x40
ax_sprite sSwabluGfx23_1, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sSwabluGfx24:
.incbin "baserom.gba", 0x139A5F0, 0x60
sSwabluSprites24:
ax_sprite sSwabluGfx24, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sSwabluGfx25:
.incbin "baserom.gba", 0x139A668, 0x60
sSwabluGfx25_1:
.incbin "baserom.gba", 0x139A6C8, 0x60
sSwabluSprites25:
ax_sprite sSwabluGfx25, 0x60
ax_sprite 0, 0x20
ax_sprite sSwabluGfx25_1, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sSwabluGfx26:
.incbin "baserom.gba", 0x139A750, 0x40
sSwabluSprites26:
ax_sprite sSwabluGfx26, 0x40
ax_sprite_terminator
sSwabluGfx27:
.incbin "baserom.gba", 0x139A7A0, 0xC0
sSwabluSprites27:
ax_sprite sSwabluGfx27, 0xc0
ax_sprite 0, 0x40
ax_sprite_terminator
sSwabluGfx28:
.incbin "baserom.gba", 0x139A878, 0x20
sSwabluSprites28:
ax_sprite sSwabluGfx28, 0x20
ax_sprite_terminator
sSwabluGfx29:
.incbin "baserom.gba", 0x139A8A8, 0xC0
sSwabluSprites29:
ax_sprite sSwabluGfx29, 0xc0
ax_sprite 0, 0x40
ax_sprite_terminator
sSwabluGfx30:
.incbin "baserom.gba", 0x139A980, 0xC0
sSwabluSprites30:
ax_sprite sSwabluGfx30, 0xc0
ax_sprite 0, 0x40
ax_sprite_terminator
sSwabluGfx31:
.incbin "baserom.gba", 0x139AA58, 0x20
sSwabluSprites31:
ax_sprite sSwabluGfx31, 0x20
ax_sprite_terminator
sSwabluGfx32:
.incbin "baserom.gba", 0x139AA88, 0x60
sSwabluGfx32_1:
.incbin "baserom.gba", 0x139AAE8, 0x60
sSwabluSprites32:
ax_sprite sSwabluGfx32, 0x60
ax_sprite 0, 0x20
ax_sprite sSwabluGfx32_1, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sSwabluGfx33:
.incbin "baserom.gba", 0x139AB70, 0x40
sSwabluSprites33:
ax_sprite sSwabluGfx33, 0x40
ax_sprite_terminator
sSwabluGfx34:
.incbin "baserom.gba", 0x139ABC0, 0x60
sSwabluGfx34_1:
.incbin "baserom.gba", 0x139AC20, 0x60
sSwabluSprites34:
ax_sprite sSwabluGfx34, 0x60
ax_sprite 0, 0x20
ax_sprite sSwabluGfx34_1, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sSwabluGfx35:
.incbin "baserom.gba", 0x139ACA8, 0x40
sSwabluSprites35:
ax_sprite sSwabluGfx35, 0x40
ax_sprite_terminator
sSwabluGfx36:
.incbin "baserom.gba", 0x139ACF8, 0x60
sSwabluGfx36_1:
.incbin "baserom.gba", 0x139AD58, 0x60
sSwabluSprites36:
ax_sprite sSwabluGfx36, 0x60
ax_sprite 0, 0x20
ax_sprite sSwabluGfx36_1, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sSwabluGfx37:
.incbin "baserom.gba", 0x139ADE0, 0x40
sSwabluSprites37:
ax_sprite sSwabluGfx37, 0x40
ax_sprite_terminator
sSwabluGfx38:
.incbin "baserom.gba", 0x139AE30, 0x100
sSwabluSprites38:
ax_sprite sSwabluGfx38, 0x100
ax_sprite_terminator
sSwabluGfx39:
.incbin "baserom.gba", 0x139AF40, 0x40
sSwabluSprites39:
ax_sprite sSwabluGfx39, 0x40
ax_sprite_terminator
sSwabluGfx40:
.incbin "baserom.gba", 0x139AF90, 0x100
sSwabluSprites40:
ax_sprite sSwabluGfx40, 0x100
ax_sprite_terminator
sSwabluGfx41:
.incbin "baserom.gba", 0x139B0A0, 0x40
sSwabluSprites41:
ax_sprite sSwabluGfx41, 0x40
ax_sprite_terminator
sSwabluGfx42:
.incbin "baserom.gba", 0x139B0F0, 0x100
sSwabluSprites42:
ax_sprite sSwabluGfx42, 0x100
ax_sprite_terminator
sSwabluGfx43:
.incbin "baserom.gba", 0x139B200, 0x40
sSwabluSprites43:
ax_sprite sSwabluGfx43, 0x40
ax_sprite_terminator
sSwabluGfx44:
.incbin "baserom.gba", 0x139B250, 0x200
sSwabluSprites44:
ax_sprite sSwabluGfx44, 0x200
ax_sprite_terminator
sSwabluGfx45:
.incbin "baserom.gba", 0x139B460, 0x200
sSwabluSprites45:
ax_sprite sSwabluGfx45, 0x200
ax_sprite_terminator
sSwabluGfx46:
.incbin "baserom.gba", 0x139B670, 0x200
sSwabluSprites46:
ax_sprite sSwabluGfx46, 0x200
ax_sprite_terminator
sSwabluGfx47:
.incbin "baserom.gba", 0x139B880, 0x200
sSwabluSprites47:
ax_sprite sSwabluGfx47, 0x200
ax_sprite_terminator
sSwabluGfx48:
.incbin "baserom.gba", 0x139BA90, 0x200
sSwabluSprites48:
ax_sprite sSwabluGfx48, 0x200
ax_sprite_terminator
sSwabluGfx49:
.incbin "baserom.gba", 0x139BCA0, 0x200
sSwabluSprites49:
ax_sprite sSwabluGfx49, 0x200
ax_sprite_terminator
sSwabluGfx50:
.incbin "baserom.gba", 0x139BEB0, 0x200
sSwabluSprites50:
ax_sprite sSwabluGfx50, 0x200
ax_sprite_terminator
sAxPosesSwablu:
.4byte sSwabluPose1
.4byte sSwabluPose2
.4byte sSwabluPose3
.4byte sSwabluPose4
.4byte sSwabluPose5
.4byte sSwabluPose6
.4byte sSwabluPose7
.4byte sSwabluPose8
.4byte sSwabluPose9
.4byte sSwabluPose10
.4byte sSwabluPose11
.4byte sSwabluPose12
.4byte sSwabluPose13
.4byte sSwabluPose14
.4byte sSwabluPose15
.4byte sSwabluPose16
.4byte sSwabluPose17
.4byte sSwabluPose18
.4byte sSwabluPose19
.4byte sSwabluPose20
.4byte sSwabluPose21
.4byte sSwabluPose22
.4byte sSwabluPose23
.4byte sSwabluPose24
.4byte sSwabluPose25
.4byte sSwabluPose26
.4byte sSwabluPose27
.4byte sSwabluPose28
.4byte sSwabluPose29
.4byte sSwabluPose30
.4byte sSwabluPose31
.4byte sSwabluPose32
.4byte sSwabluPose33
.4byte sSwabluPose34
.4byte sSwabluPose35
.4byte sSwabluPose36
.4byte sSwabluPose37
.4byte sSwabluPose38
.4byte sSwabluPose39
.4byte sSwabluPose40
.4byte sSwabluPose41
.4byte sSwabluPose42
.4byte sSwabluPose43
.4byte sSwabluPose44
.4byte sSwabluPose45
.4byte sSwabluPose46
.4byte sSwabluPose47
.4byte sSwabluPose48
.4byte sSwabluPose49
.4byte sSwabluPose50
.4byte sSwabluPose51
.4byte sSwabluPose52
.4byte sSwabluPose53
.4byte sSwabluPose54
.4byte sSwabluPose55
.4byte sSwabluPose56
.4byte sSwabluPose57
.4byte sSwabluPose58
.4byte sSwabluPose59
.4byte sSwabluPose60
.4byte sSwabluPose61
.4byte sSwabluPose62
.4byte sSwabluPose63
.4byte sSwabluPose64
.4byte sSwabluPose65
.4byte sSwabluPose66
.4byte sSwabluPose67
.4byte sSwabluPose68
.4byte sSwabluPose69
.4byte sSwabluPose70
.4byte sSwabluPose71
.4byte sSwabluPose72
.4byte sSwabluPose73
.4byte sSwabluPose74
.4byte sSwabluPose75
.4byte sSwabluPose76
.4byte sSwabluPose77
.4byte sSwabluPose78
.4byte sSwabluPose79
.4byte sSwabluPose80
.4byte sSwabluPose81
.4byte sSwabluPose82
.4byte sSwabluPose83
.4byte sSwabluPose84
.4byte sSwabluPose85
.4byte sSwabluPose86
.4byte sSwabluPose87
.4byte sSwabluPose88
.4byte sSwabluPose89
.4byte sSwabluPose90
.4byte sSwabluPose91
.4byte sSwabluPose92
.4byte sSwabluPose93
.4byte sSwabluPose94
.4byte sSwabluPose95
.4byte sSwabluPose96
.4byte sSwabluPose97
.4byte sSwabluPose98
.4byte sSwabluPose99
.4byte sSwabluPose100
.4byte sSwabluPose101
.4byte sSwabluPose102
.4byte sSwabluPose103
.4byte sSwabluPose104
.4byte sSwabluPose105
.4byte sSwabluPose106
.4byte sSwabluPose107
.4byte sSwabluPose108
.4byte sSwabluPose109
.4byte sSwabluPose110
.4byte sSwabluPose111
.4byte sSwabluPose112
.4byte sSwabluPose113
.4byte sSwabluPose114
.4byte sSwabluPose115
.4byte sSwabluPose116
.4byte sSwabluPose117
.4byte sSwabluPose118
.4byte sSwabluPose119
.4byte sSwabluPose120
.4byte sSwabluPose121
.4byte sSwabluPose122
.4byte sSwabluPose123
.4byte sSwabluPose124
.4byte sSwabluPose125
.4byte sSwabluPose126
.4byte sSwabluPose127
.4byte sSwabluPose128
.4byte sSwabluPose129
.4byte sSwabluPose130
.4byte sSwabluPose131
.4byte sSwabluPose132
.4byte sSwabluPose133
.4byte sSwabluPose134
.4byte sSwabluPose135
.4byte sSwabluPose136
.4byte sSwabluPose137
.4byte sSwabluPose138
.4byte sSwabluPose139
.4byte sSwabluPose140
.4byte sSwabluPose141
.4byte sSwabluPose142
.4byte sSwabluPose143
.4byte sSwabluPose144
.4byte sSwabluPose145
.4byte sSwabluPose146
.4byte sSwabluPose147
.4byte sSwabluPose148
.4byte sSwabluPose149
.4byte sSwabluPose150
.4byte sSwabluPose151
.4byte sSwabluPose152
.4byte sSwabluPose153
.4byte sSwabluPose154
.4byte sSwabluPose155
.4byte sSwabluPose156
.4byte sSwabluPose157
.4byte sSwabluPose158
.4byte sSwabluPose159
.4byte sSwabluPose160
.4byte sSwabluPose161
.4byte sSwabluPose162
.4byte sSwabluPose163
.4byte sSwabluPose164
.4byte sSwabluPose165
.4byte sSwabluPose166
.4byte sSwabluPose167
.4byte sSwabluPose168
.4byte sSwabluPose169
.4byte sSwabluPose170
.4byte sSwabluPose171
.4byte sSwabluPose172
.4byte sSwabluPose173
.4byte sSwabluPose174
.4byte sSwabluPose175
.4byte sSwabluPose176
.4byte sSwabluPose177
.4byte sSwabluPose178
.4byte sSwabluPose179
.4byte sSwabluPose180
.4byte sSwabluPose181
.4byte sSwabluPose182
.4byte sSwabluPose183
.4byte sSwabluPose184
.4byte sSwabluPose185
.4byte sSwabluPose186
.4byte sSwabluPose187
.4byte sSwabluPose188
.4byte sSwabluPose189
.4byte sSwabluPose190
.4byte sSwabluPose191
.4byte sSwabluPose192
.4byte sSwabluPose193
.4byte sSwabluPose194
.4byte sSwabluPose195
.4byte sSwabluPose196
.4byte sSwabluPose197
.4byte sSwabluPose198
.4byte sSwabluPose199
.4byte sSwabluPose200
.4byte sSwabluPose201
.4byte sSwabluPose202
.4byte sSwabluPose203
.4byte sSwabluPose204
.4byte sSwabluPose205
.4byte sSwabluPose206
.4byte sSwabluPose207
.4byte sSwabluPose208
.4byte sSwabluPose209
.4byte sSwabluPose210
.4byte sSwabluPose211
.4byte sSwabluPose212
.4byte sSwabluPose213
.4byte sSwabluPose214
.4byte sSwabluPose215
.4byte sSwabluPose216
.4byte sSwabluPose217
.4byte sSwabluPose218
.4byte sSwabluPose219
.4byte sSwabluPose220
.4byte sSwabluPose221
.4byte sSwabluPose222
.4byte sSwabluPose223
.4byte sSwabluPose224
.4byte sSwabluPose225
.4byte sSwabluPose226
.4byte sSwabluPose227
.4byte sSwabluPose228
.4byte sSwabluPose229
.4byte sSwabluPose230
.4byte sSwabluPose231
.4byte sSwabluPose232
.4byte sSwabluPose233
.4byte sSwabluPose234
sAxPositionsSwablu:
.2byte   -1,   -5, 	 -13,  -11, 	  11,  -11, 	  -1,   -9
.2byte   -1,   -5, 	 -12,   -2, 	  11,   -3, 	  -1,   -9
.2byte   -1,   -5, 	 -12,  -14, 	  10,  -14, 	  -1,   -9
.2byte    3,   -5, 	   5,  -17, 	 -13,   -6, 	   0,   -9
.2byte    3,   -5, 	   9,  -11, 	  -8,    0, 	   0,   -9
.2byte    3,   -5, 	   3,  -18, 	 -13,  -10, 	  -1,   -9
.2byte    5,   -7, 	  -2,  -17, 	  -8,   -2, 	  -1,   -9
.2byte    5,   -7, 	   0,  -14, 	  -4,    4, 	  -2,   -9
.2byte    5,   -7, 	  -1,  -18, 	  -6,   -5, 	  -1,   -9
.2byte    3,  -11, 	 -10,  -14, 	   7,   -2, 	  -2,   -9
.2byte    3,  -11, 	  -9,  -13, 	   5,   -1, 	  -2,   -9
.2byte    3,  -11, 	 -11,  -16, 	   7,   -6, 	  -2,   -9
.2byte   -1,  -10, 	  11,   -9, 	 -13,   -8, 	  -1,   -8
.2byte   -1,  -10, 	   9,   -6, 	 -11,   -6, 	  -1,   -8
.2byte   -1,  -11, 	  11,  -12, 	 -13,  -12, 	  -1,   -8
.2byte   -5,  -11, 	   8,  -14, 	  -9,   -2, 	   0,   -9
.2byte   -5,  -11, 	   7,  -13, 	  -7,   -1, 	   0,   -9
.2byte   -5,  -11, 	   9,  -16, 	  -9,   -6, 	   0,   -9
.2byte   -7,   -7, 	   0,  -17, 	   6,   -2, 	  -1,   -9
.2byte   -7,   -7, 	  -2,  -14, 	   2,    4, 	   0,   -9
.2byte   -7,   -7, 	  -1,  -18, 	   4,   -5, 	  -1,   -9
.2byte   -5,   -5, 	  -7,  -17, 	  11,   -6, 	  -2,   -9
.2byte   -5,   -5, 	 -11,  -11, 	   6,    0, 	  -2,   -9
.2byte   -5,   -5, 	  -5,  -18, 	  11,  -10, 	  -1,   -9
.2byte   -1,   -5, 	 -13,  -11, 	  11,  -11, 	  -1,   -9
.2byte   -1,   -5, 	 -12,   -2, 	  11,   -3, 	  -1,   -9
.2byte   -1,   -5, 	 -12,  -14, 	  10,  -14, 	  -1,   -9
.2byte    3,   -5, 	   5,  -17, 	 -13,   -6, 	   0,   -9
.2byte    3,   -5, 	   9,  -11, 	  -8,    0, 	   0,   -9
.2byte    3,   -5, 	   3,  -18, 	 -13,  -10, 	  -1,   -9
.2byte    5,   -7, 	  -2,  -17, 	  -8,   -2, 	  -1,   -9
.2byte    5,   -7, 	   0,  -14, 	  -4,    4, 	  -2,   -9
.2byte    5,   -7, 	  -1,  -18, 	  -6,   -5, 	  -1,   -9
.2byte    3,  -11, 	 -10,  -14, 	   7,   -2, 	  -2,   -9
.2byte    3,  -11, 	  -9,  -13, 	   5,   -1, 	  -2,   -9
.2byte    3,  -11, 	 -11,  -16, 	   7,   -6, 	  -2,   -9
.2byte   -1,  -10, 	  11,   -9, 	 -13,   -8, 	  -1,   -8
.2byte   -1,  -10, 	   9,   -6, 	 -11,   -6, 	  -1,   -8
.2byte   -1,  -11, 	  11,  -12, 	 -13,  -12, 	  -1,   -8
.2byte   -5,  -11, 	   8,  -14, 	  -9,   -2, 	   0,   -9
.2byte   -5,  -11, 	   7,  -13, 	  -7,   -1, 	   0,   -9
.2byte   -5,  -11, 	   9,  -16, 	  -9,   -6, 	   0,   -9
.2byte   -7,   -7, 	   0,  -17, 	   6,   -2, 	  -1,   -9
.2byte   -7,   -7, 	  -2,  -14, 	   2,    4, 	   0,   -9
.2byte   -7,   -7, 	  -1,  -18, 	   4,   -5, 	  -1,   -9
.2byte   -5,   -5, 	  -7,  -17, 	  11,   -6, 	  -2,   -9
.2byte   -5,   -5, 	 -11,  -11, 	   6,    0, 	  -2,   -9
.2byte   -5,   -5, 	  -5,  -18, 	  11,  -10, 	  -1,   -9
.2byte   -1,   -5, 	 -13,  -11, 	  11,  -11, 	  -1,   -9
.2byte   -1,   -5, 	 -12,   -2, 	  11,   -3, 	  -1,   -9
.2byte   -1,   -5, 	 -12,  -14, 	  10,  -14, 	  -1,   -9
.2byte    3,   -5, 	   5,  -17, 	 -13,   -6, 	   0,   -9
.2byte    3,   -5, 	   9,  -11, 	  -8,    0, 	   0,   -9
.2byte    3,   -5, 	   3,  -18, 	 -13,  -10, 	  -1,   -9
.2byte    5,   -7, 	  -2,  -17, 	  -8,   -2, 	  -1,   -9
.2byte    5,   -7, 	   0,  -14, 	  -4,    4, 	  -2,   -9
.2byte    5,   -7, 	  -1,  -18, 	  -6,   -5, 	  -1,   -9
.2byte    3,  -11, 	 -10,  -14, 	   7,   -2, 	  -2,   -9
.2byte    3,  -11, 	  -9,  -13, 	   5,   -1, 	  -2,   -9
.2byte    3,  -11, 	 -11,  -16, 	   7,   -6, 	  -2,   -9
.2byte   -1,  -10, 	  11,   -9, 	 -13,   -8, 	  -1,   -8
.2byte   -1,  -10, 	   9,   -6, 	 -11,   -6, 	  -1,   -8
.2byte   -1,  -11, 	  11,  -12, 	 -13,  -12, 	  -1,   -8
.2byte   -5,  -11, 	   8,  -14, 	  -9,   -2, 	   0,   -9
.2byte   -5,  -11, 	   7,  -13, 	  -7,   -1, 	   0,   -9
.2byte   -5,  -11, 	   9,  -16, 	  -9,   -6, 	   0,   -9
.2byte   -7,   -7, 	   0,  -17, 	   6,   -2, 	  -1,   -9
.2byte   -7,   -7, 	  -2,  -14, 	   2,    4, 	   0,   -9
.2byte   -7,   -7, 	  -1,  -18, 	   4,   -5, 	  -1,   -9
.2byte   -5,   -5, 	  -7,  -17, 	  11,   -6, 	  -2,   -9
.2byte   -5,   -5, 	 -11,  -11, 	   6,    0, 	  -2,   -9
.2byte   -5,   -5, 	  -5,  -18, 	  11,  -10, 	  -1,   -9
.2byte   -1,   -5, 	 -13,  -11, 	  11,  -11, 	  -1,   -9
.2byte   -1,   -5, 	 -12,   -2, 	  11,   -3, 	  -1,   -9
.2byte   -1,   -5, 	 -12,  -14, 	  10,  -14, 	  -1,   -9
.2byte   -1,   -5, 	 -13,  -12, 	  11,  -12, 	  -1,   -9
.2byte   -1,   -5, 	 -12,   -2, 	  10,   -2, 	  -1,   -9
.2byte   -1,   -5, 	 -12,  -14, 	  10,  -13, 	  -1,   -9
.2byte    3,   -5, 	   5,  -17, 	 -13,   -6, 	   0,   -9
.2byte    3,   -5, 	   9,  -11, 	  -8,    0, 	   0,   -9
.2byte    3,   -5, 	   3,  -18, 	 -13,  -10, 	  -1,   -9
.2byte    2,   -6, 	   5,  -17, 	 -13,   -6, 	  -1,   -9
.2byte    2,   -6, 	   9,  -11, 	  -8,    0, 	  -1,   -9
.2byte    2,   -6, 	   3,  -18, 	 -13,   -9, 	  -2,   -9
.2byte    5,   -7, 	  -2,  -17, 	  -8,   -2, 	  -1,   -9
.2byte    5,   -7, 	   0,  -14, 	  -4,    4, 	  -2,   -9
.2byte    5,   -7, 	  -1,  -18, 	  -6,   -5, 	  -1,   -9
.2byte    4,   -6, 	  -2,  -17, 	  -7,   -2, 	  -1,   -8
.2byte    4,   -6, 	   0,  -14, 	  -5,    4, 	  -1,   -8
.2byte    4,   -6, 	  -1,  -18, 	  -7,   -5, 	  -2,   -8
.2byte    3,  -11, 	 -10,  -14, 	   7,   -2, 	  -2,   -9
.2byte    3,  -11, 	  -9,  -13, 	   5,   -1, 	  -2,   -9
.2byte    3,  -11, 	 -11,  -16, 	   7,   -6, 	  -2,   -9
.2byte    4,  -11, 	 -10,  -14, 	   6,   -2, 	  -2,   -9
.2byte    4,  -11, 	  -9,  -13, 	   5,   -2, 	  -2,   -9
.2byte    4,  -11, 	 -11,  -16, 	   7,   -4, 	  -3,  -10
.2byte   -1,  -10, 	  11,   -9, 	 -13,   -8, 	  -1,   -8
.2byte   -1,  -10, 	   9,   -6, 	 -11,   -6, 	  -1,   -8
.2byte   -1,  -11, 	  11,  -12, 	 -13,  -12, 	  -1,   -8
.2byte   -1,  -15, 	  11,   -9, 	 -13,   -9, 	  -1,   -8
.2byte   -1,  -15, 	   9,   -6, 	 -11,   -6, 	  -1,   -7
.2byte   -1,  -15, 	  11,  -12, 	 -13,  -12, 	  -1,   -9
.2byte   -5,  -11, 	   8,  -14, 	  -9,   -2, 	   0,   -9
.2byte   -5,  -11, 	   7,  -13, 	  -7,   -1, 	   0,   -9
.2byte   -5,  -11, 	   9,  -16, 	  -9,   -6, 	   0,   -9
.2byte   -6,  -11, 	   8,  -14, 	  -8,   -2, 	   0,   -9
.2byte   -6,  -11, 	   7,  -13, 	  -7,   -2, 	   0,   -9
.2byte   -6,  -11, 	   9,  -16, 	  -9,   -4, 	   1,  -10
.2byte   -7,   -7, 	   0,  -17, 	   6,   -2, 	  -1,   -9
.2byte   -7,   -7, 	  -2,  -14, 	   2,    4, 	   0,   -9
.2byte   -7,   -7, 	  -1,  -18, 	   4,   -5, 	  -1,   -9
.2byte   -6,   -6, 	   0,  -17, 	   5,   -2, 	  -1,   -8
.2byte   -6,   -6, 	  -2,  -14, 	   3,    4, 	  -1,   -8
.2byte   -6,   -6, 	  -1,  -18, 	   5,   -5, 	   0,   -8
.2byte   -5,   -5, 	  -7,  -17, 	  11,   -6, 	  -2,   -9
.2byte   -5,   -5, 	 -11,  -11, 	   6,    0, 	  -2,   -9
.2byte   -5,   -5, 	  -5,  -18, 	  11,  -10, 	  -1,   -9
.2byte   -4,   -6, 	  -7,  -17, 	  11,   -6, 	  -1,   -9
.2byte   -4,   -6, 	 -11,  -11, 	   6,    0, 	  -1,   -9
.2byte   -4,   -6, 	  -5,  -18, 	  11,   -9, 	   0,   -9
.2byte   -1,   -5, 	 -13,  -11, 	  11,  -11, 	  -1,   -9
.2byte   -1,   -6, 	 -12,   -3, 	  11,   -4, 	  -1,  -10
.2byte   -1,   -5, 	 -12,  -14, 	  10,  -14, 	  -1,   -9
.2byte    3,   -5, 	   5,  -17, 	 -13,   -6, 	   0,   -9
.2byte    3,   -6, 	   9,  -12, 	  -8,   -1, 	   0,  -10
.2byte    3,   -5, 	   3,  -18, 	 -13,  -10, 	  -1,   -9
.2byte    5,   -7, 	  -2,  -17, 	  -8,   -2, 	  -1,   -9
.2byte    5,   -8, 	   0,  -15, 	  -4,    3, 	  -2,  -10
.2byte    5,   -7, 	  -1,  -18, 	  -6,   -5, 	  -1,   -9
.2byte    3,  -11, 	 -10,  -14, 	   7,   -2, 	  -2,   -9
.2byte    3,  -12, 	  -9,  -14, 	   5,   -2, 	  -2,  -10
.2byte    3,  -11, 	 -11,  -16, 	   7,   -6, 	  -2,   -9
.2byte   -1,  -10, 	  11,   -9, 	 -13,   -8, 	  -1,   -8
.2byte   -1,  -11, 	   9,   -7, 	 -11,   -7, 	  -1,   -9
.2byte   -1,  -11, 	  11,  -12, 	 -13,  -12, 	  -1,   -8
.2byte   -5,  -11, 	   8,  -14, 	  -9,   -2, 	   0,   -9
.2byte   -5,  -12, 	   7,  -14, 	  -7,   -2, 	   0,  -10
.2byte   -5,  -11, 	   9,  -16, 	  -9,   -6, 	   0,   -9
.2byte   -7,   -7, 	   0,  -17, 	   6,   -2, 	  -1,   -9
.2byte   -7,   -8, 	  -2,  -15, 	   2,    3, 	   0,  -10
.2byte   -7,   -7, 	  -1,  -18, 	   4,   -5, 	  -1,   -9
.2byte   -5,   -5, 	  -7,  -17, 	  11,   -6, 	  -2,   -9
.2byte   -5,   -6, 	 -11,  -12, 	   6,   -1, 	  -2,  -10
.2byte   -5,   -5, 	  -5,  -18, 	  11,  -10, 	  -1,   -9
.2byte   -1,   -2, 	  -7,   -7, 	   6,   -7, 	  -1,   -4
.2byte   -1,   -1, 	  -7,   -7, 	   6,   -7, 	  -1,   -4
.2byte   -1,  -15, 	 -10,   -8, 	   8,   -8, 	  -1,  -12
.2byte    1,  -15, 	   9,  -12, 	  -6,   -3, 	  -1,  -12
.2byte    2,  -18, 	   8,  -12, 	   4,   -7, 	  -1,  -12
.2byte    1,  -18, 	   1,  -21, 	   8,  -11, 	  -2,  -12
.2byte   -1,  -21, 	   9,  -18, 	 -11,  -18, 	  -1,  -14
.2byte   -3,  -18, 	  -3,  -21, 	 -10,  -11, 	   0,  -12
.2byte   -3,  -18, 	  -9,  -12, 	  -5,   -7, 	   0,  -12
.2byte   -2,  -15, 	 -10,  -12, 	   5,   -3, 	   0,  -12
.2byte   -1,   -5, 	 -13,  -11, 	  11,  -11, 	  -1,   -9
.2byte   -1,   -5, 	 -12,   -2, 	  11,   -3, 	  -1,   -9
.2byte   -1,   -5, 	 -12,  -14, 	  10,  -14, 	  -1,   -9
.2byte    3,   -5, 	   5,  -17, 	 -13,   -6, 	   0,   -9
.2byte    3,   -5, 	   9,  -11, 	  -8,    0, 	   0,   -9
.2byte    3,   -5, 	   3,  -18, 	 -13,  -10, 	  -1,   -9
.2byte    5,   -7, 	  -2,  -17, 	  -8,   -2, 	  -1,   -9
.2byte    5,   -7, 	   0,  -14, 	  -4,    4, 	  -2,   -9
.2byte    5,   -7, 	  -1,  -18, 	  -6,   -5, 	  -1,   -9
.2byte    3,  -11, 	 -10,  -14, 	   7,   -2, 	  -2,   -9
.2byte    3,  -11, 	  -9,  -13, 	   5,   -1, 	  -2,   -9
.2byte    3,  -11, 	 -11,  -16, 	   7,   -6, 	  -2,   -9
.2byte   -1,  -10, 	  11,   -9, 	 -13,   -8, 	  -1,   -8
.2byte   -1,  -10, 	   9,   -6, 	 -11,   -6, 	  -1,   -8
.2byte   -1,  -11, 	  11,  -12, 	 -13,  -12, 	  -1,   -8
.2byte   -5,  -11, 	   8,  -14, 	  -9,   -2, 	   0,   -9
.2byte   -5,  -11, 	   7,  -13, 	  -7,   -1, 	   0,   -9
.2byte   -5,  -11, 	   9,  -16, 	  -9,   -6, 	   0,   -9
.2byte   -7,   -7, 	   0,  -17, 	   6,   -2, 	  -1,   -9
.2byte   -7,   -7, 	  -2,  -14, 	   2,    4, 	   0,   -9
.2byte   -7,   -7, 	  -1,  -18, 	   4,   -5, 	  -1,   -9
.2byte   -5,   -5, 	  -7,  -17, 	  11,   -6, 	  -2,   -9
.2byte   -5,   -5, 	 -11,  -11, 	   6,    0, 	  -2,   -9
.2byte   -5,   -5, 	  -5,  -18, 	  11,  -10, 	  -1,   -9
.2byte   -1,   -5, 	 -12,  -14, 	  10,  -13, 	  -1,   -9
.2byte   -4,   -6, 	  -5,  -18, 	  11,   -9, 	   0,   -9
.2byte   -6,   -6, 	  -1,  -18, 	   5,   -5, 	   0,   -8
.2byte   -6,  -11, 	   9,  -16, 	  -9,   -4, 	   1,  -10
.2byte   -1,  -16, 	  11,  -13, 	 -13,  -13, 	  -1,  -10
.2byte    5,  -11, 	 -10,  -16, 	   8,   -4, 	  -2,  -10
.2byte    4,   -6, 	  -1,  -18, 	  -7,   -5, 	  -2,   -8
.2byte    2,   -6, 	   3,  -18, 	 -13,   -9, 	  -2,   -9
.2byte   -1,   -5, 	 -13,  -12, 	  11,  -12, 	  -1,   -9
.2byte    2,   -6, 	   5,  -17, 	 -13,   -6, 	  -1,   -9
.2byte    4,   -6, 	  -2,  -17, 	  -7,   -2, 	  -1,   -8
.2byte    4,  -11, 	 -10,  -14, 	   6,   -2, 	  -2,   -9
.2byte   -1,  -15, 	  11,   -9, 	 -13,   -9, 	  -1,   -8
.2byte   -6,  -11, 	   8,  -14, 	  -8,   -2, 	   0,   -9
.2byte   -6,   -6, 	   0,  -17, 	   5,   -2, 	  -1,   -8
.2byte   -4,   -6, 	  -7,  -17, 	  11,   -6, 	  -1,   -9
.2byte   -1,   -5, 	 -13,  -12, 	  11,  -12, 	  -1,   -9
.2byte   -1,   -5, 	 -12,   -2, 	  10,   -2, 	  -1,   -9
.2byte   -1,   -5, 	 -12,  -14, 	  10,  -13, 	  -1,   -9
.2byte    2,   -6, 	   5,  -17, 	 -13,   -6, 	  -1,   -9
.2byte    2,   -6, 	   9,  -11, 	  -8,    0, 	  -1,   -9
.2byte    2,   -6, 	   3,  -18, 	 -13,   -9, 	  -2,   -9
.2byte    4,   -6, 	  -2,  -17, 	  -7,   -2, 	  -1,   -8
.2byte    4,   -6, 	   0,  -14, 	  -5,    4, 	  -1,   -8
.2byte    4,   -6, 	  -1,  -18, 	  -7,   -5, 	  -2,   -8
.2byte    4,  -11, 	 -10,  -14, 	   6,   -2, 	  -2,   -9
.2byte    4,  -11, 	  -9,  -13, 	   5,   -2, 	  -2,   -9
.2byte    4,  -11, 	 -11,  -16, 	   7,   -4, 	  -3,  -10
.2byte   -1,  -15, 	  11,   -9, 	 -13,   -9, 	  -1,   -8
.2byte   -1,  -15, 	   9,   -6, 	 -11,   -6, 	  -1,   -7
.2byte   -1,  -15, 	  11,  -12, 	 -13,  -12, 	  -1,   -9
.2byte   -6,  -11, 	   8,  -14, 	  -8,   -2, 	   0,   -9
.2byte   -6,  -11, 	   7,  -13, 	  -7,   -2, 	   0,   -9
.2byte   -6,  -11, 	   9,  -16, 	  -9,   -4, 	   1,  -10
.2byte   -6,   -6, 	   0,  -17, 	   5,   -2, 	  -1,   -8
.2byte   -6,   -6, 	  -2,  -14, 	   3,    4, 	  -1,   -8
.2byte   -6,   -6, 	  -1,  -18, 	   5,   -5, 	   0,   -8
.2byte   -4,   -6, 	  -7,  -17, 	  11,   -6, 	  -1,   -9
.2byte   -4,   -6, 	 -11,  -11, 	   6,    0, 	  -1,   -9
.2byte   -4,   -6, 	  -5,  -18, 	  11,   -9, 	   0,   -9
.2byte   -1,   -5, 	 -12,   -2, 	  10,   -2, 	  -1,   -9
.2byte   -4,   -6, 	 -11,  -11, 	   6,    0, 	  -1,   -9
.2byte   -6,   -6, 	  -2,  -14, 	   3,    4, 	  -1,   -8
.2byte   -7,  -11, 	   6,  -13, 	  -8,   -2, 	  -1,   -9
.2byte   -1,  -15, 	   9,   -6, 	 -11,   -6, 	  -1,   -7
.2byte    5,  -11, 	  -8,  -13, 	   6,   -2, 	  -1,   -9
.2byte    5,   -6, 	   1,  -14, 	  -4,    4, 	   0,   -8
.2byte    3,   -6, 	  10,  -11, 	  -7,    0, 	   0,   -9
.2byte   -1,   -5, 	 -13,  -11, 	  11,  -11, 	  -1,   -9
.2byte   -5,   -5, 	  -7,  -17, 	  11,   -6, 	  -2,   -9
.2byte   -7,   -7, 	   0,  -17, 	   6,   -2, 	  -1,   -9
.2byte   -5,  -11, 	   8,  -14, 	  -9,   -2, 	   0,   -9
.2byte   -1,  -10, 	  11,   -9, 	 -13,   -8, 	  -1,   -8
.2byte    3,  -11, 	 -10,  -14, 	   7,   -2, 	  -2,   -9
.2byte    5,   -7, 	  -2,  -17, 	  -8,   -2, 	  -1,   -9
.2byte    3,   -5, 	   5,  -17, 	 -13,   -6, 	   0,   -9
sSwabluAnimTable1:
.4byte sSwabluAnims_1_1
.4byte sSwabluAnims_1_2
.4byte sSwabluAnims_1_3
.4byte sSwabluAnims_1_4
.4byte sSwabluAnims_1_5
.4byte sSwabluAnims_1_6
.4byte sSwabluAnims_1_7
.4byte sSwabluAnims_1_8
sSwabluAnimTable2:
.4byte sSwabluAnims_2_1
.4byte sSwabluAnims_2_2
.4byte sSwabluAnims_2_3
.4byte sSwabluAnims_2_4
.4byte sSwabluAnims_2_5
.4byte sSwabluAnims_2_6
.4byte sSwabluAnims_2_7
.4byte sSwabluAnims_2_8
sSwabluAnimTable3:
.4byte sSwabluAnims_3_1
.4byte sSwabluAnims_3_2
.4byte sSwabluAnims_3_3
.4byte sSwabluAnims_3_4
.4byte sSwabluAnims_3_5
.4byte sSwabluAnims_3_6
.4byte sSwabluAnims_3_7
.4byte sSwabluAnims_3_8
sSwabluAnimTable4:
.4byte sSwabluAnims_4_1
.4byte sSwabluAnims_4_2
.4byte sSwabluAnims_4_3
.4byte sSwabluAnims_4_4
.4byte sSwabluAnims_4_5
.4byte sSwabluAnims_4_6
.4byte sSwabluAnims_4_7
.4byte sSwabluAnims_4_8
sSwabluAnimTable5:
.4byte sSwabluAnims_5_1
.4byte sSwabluAnims_5_2
.4byte sSwabluAnims_5_3
.4byte sSwabluAnims_5_4
.4byte sSwabluAnims_5_5
.4byte sSwabluAnims_5_6
.4byte sSwabluAnims_5_7
.4byte sSwabluAnims_5_8
sSwabluAnimTable6:
.4byte sSwabluAnims_6_1
.4byte sSwabluAnims_6_1
.4byte sSwabluAnims_6_1
.4byte sSwabluAnims_6_1
.4byte sSwabluAnims_6_1
.4byte sSwabluAnims_6_1
.4byte sSwabluAnims_6_1
.4byte sSwabluAnims_6_1
sSwabluAnimTable7:
.4byte sSwabluAnims_7_1
.4byte sSwabluAnims_7_2
.4byte sSwabluAnims_7_3
.4byte sSwabluAnims_7_4
.4byte sSwabluAnims_7_5
.4byte sSwabluAnims_7_6
.4byte sSwabluAnims_7_7
.4byte sSwabluAnims_7_8
sSwabluAnimTable8:
.4byte sSwabluAnims_8_1
.4byte sSwabluAnims_8_2
.4byte sSwabluAnims_8_3
.4byte sSwabluAnims_8_4
.4byte sSwabluAnims_8_5
.4byte sSwabluAnims_8_6
.4byte sSwabluAnims_8_7
.4byte sSwabluAnims_8_8
sSwabluAnimTable9:
.4byte sSwabluAnims_9_1
.4byte sSwabluAnims_9_2
.4byte sSwabluAnims_9_3
.4byte sSwabluAnims_9_4
.4byte sSwabluAnims_9_5
.4byte sSwabluAnims_9_6
.4byte sSwabluAnims_9_7
.4byte sSwabluAnims_9_8
sSwabluAnimTable10:
.4byte sSwabluAnims_10_1
.4byte sSwabluAnims_10_2
.4byte sSwabluAnims_10_3
.4byte sSwabluAnims_10_4
.4byte sSwabluAnims_10_5
.4byte sSwabluAnims_10_6
.4byte sSwabluAnims_10_7
.4byte sSwabluAnims_10_8
sSwabluAnimTable11:
.4byte sSwabluAnims_11_1
.4byte sSwabluAnims_11_2
.4byte sSwabluAnims_11_3
.4byte sSwabluAnims_11_4
.4byte sSwabluAnims_11_5
.4byte sSwabluAnims_11_6
.4byte sSwabluAnims_11_7
.4byte sSwabluAnims_11_8
sSwabluAnimTable12:
.4byte sSwabluAnims_12_1
.4byte sSwabluAnims_12_2
.4byte sSwabluAnims_12_3
.4byte sSwabluAnims_12_4
.4byte sSwabluAnims_12_5
.4byte sSwabluAnims_12_6
.4byte sSwabluAnims_12_7
.4byte sSwabluAnims_12_8
sSwabluAnimTable13:
.4byte sSwabluAnims_13_1
.4byte sSwabluAnims_13_2
.4byte sSwabluAnims_13_3
.4byte sSwabluAnims_13_4
.4byte sSwabluAnims_13_5
.4byte sSwabluAnims_13_6
.4byte sSwabluAnims_13_7
.4byte sSwabluAnims_13_8
sAxAnimationsSwablu:
.4byte sSwabluAnimTable1
.4byte sSwabluAnimTable2
.4byte sSwabluAnimTable3
.4byte sSwabluAnimTable4
.4byte sSwabluAnimTable5
.4byte sSwabluAnimTable6
.4byte sSwabluAnimTable7
.4byte sSwabluAnimTable8
.4byte sSwabluAnimTable9
.4byte sSwabluAnimTable10
.4byte sSwabluAnimTable11
.4byte sSwabluAnimTable12
.4byte sSwabluAnimTable13
sAxSpritesSwablu:
.4byte sSwabluSprites1
.4byte sSwabluSprites2
.4byte sSwabluSprites3
.4byte sSwabluSprites4
.4byte sSwabluSprites5
.4byte sSwabluSprites6
.4byte sSwabluSprites7
.4byte sSwabluSprites8
.4byte sSwabluSprites9
.4byte sSwabluSprites10
.4byte sSwabluSprites11
.4byte sSwabluSprites12
.4byte sSwabluSprites13
.4byte sSwabluSprites14
.4byte sSwabluSprites15
.4byte sSwabluSprites16
.4byte sSwabluSprites17
.4byte sSwabluSprites18
.4byte sSwabluSprites19
.4byte sSwabluSprites20
.4byte sSwabluSprites21
.4byte sSwabluSprites22
.4byte sSwabluSprites23
.4byte sSwabluSprites24
.4byte sSwabluSprites25
.4byte sSwabluSprites26
.4byte sSwabluSprites27
.4byte sSwabluSprites28
.4byte sSwabluSprites29
.4byte sSwabluSprites30
.4byte sSwabluSprites31
.4byte sSwabluSprites32
.4byte sSwabluSprites33
.4byte sSwabluSprites34
.4byte sSwabluSprites35
.4byte sSwabluSprites36
.4byte sSwabluSprites37
.4byte sSwabluSprites38
.4byte sSwabluSprites39
.4byte sSwabluSprites40
.4byte sSwabluSprites41
.4byte sSwabluSprites42
.4byte sSwabluSprites43
.4byte sSwabluSprites44
.4byte sSwabluSprites45
.4byte sSwabluSprites46
.4byte sSwabluSprites47
.4byte sSwabluSprites48
.4byte sSwabluSprites49
.4byte sSwabluSprites50
sAxMainSwablu:
ax_main sAxPosesSwablu, sAxAnimationsSwablu, 13, sAxSpritesSwablu, sAxPositionsSwablu
