.global gAxUnownE
gAxUnownE:
ax_siro sAxMainUnownE
sUnownEPose1:
ax_pose 0, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sUnownEPose2:
ax_pose 1, 0x01e8, 0x80f5, 0x5c00
ax_pose_terminator
sUnownEPose3:
ax_pose 2, 0x01e8, 0x80f5, 0x5c00
ax_pose_terminator
sUnownEPose4:
ax_pose 3, 0x01e8, 0x80f5, 0x5c00
ax_pose_terminator
sUnownEPose5:
ax_pose 4, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sUnownEPose6:
ax_pose 5, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sUnownEPose7:
ax_pose 6, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sUnownEPose8:
ax_pose 7, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sUnownEPose9:
ax_pose 0, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sUnownEPose10:
ax_pose 1, 0x01e8, 0x80f5, 0x5c00
ax_pose_terminator
sUnownEPose11:
ax_pose 2, 0x01e8, 0x80f5, 0x5c00
ax_pose_terminator
sUnownEPose12:
ax_pose 3, 0x01e8, 0x80f5, 0x5c00
ax_pose_terminator
sUnownEPose13:
ax_pose 4, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sUnownEPose14:
ax_pose 5, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sUnownEPose15:
ax_pose 6, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sUnownEPose16:
ax_pose 7, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sUnownEPose17:
ax_pose 0, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sUnownEPose18:
ax_pose 1, 0x01e8, 0x80f5, 0x5c00
ax_pose_terminator
sUnownEPose19:
ax_pose 2, 0x01e8, 0x80f5, 0x5c00
ax_pose_terminator
sUnownEPose20:
ax_pose 3, 0x01e8, 0x80f5, 0x5c00
ax_pose_terminator
sUnownEPose21:
ax_pose 4, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sUnownEPose22:
ax_pose 5, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sUnownEPose23:
ax_pose 6, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sUnownEPose24:
ax_pose 7, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sUnownEPose25:
ax_pose 0, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sUnownEPose26:
ax_pose 1, 0x01e8, 0x80f5, 0x5c00
ax_pose_terminator
sUnownEPose27:
ax_pose 2, 0x01e8, 0x80f5, 0x5c00
ax_pose_terminator
sUnownEPose28:
ax_pose 3, 0x01e8, 0x80f5, 0x5c00
ax_pose_terminator
sUnownEPose29:
ax_pose 4, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sUnownEPose30:
ax_pose 5, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sUnownEPose31:
ax_pose 6, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sUnownEPose32:
ax_pose 7, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sUnownEPose33:
ax_pose 0, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sUnownEPose34:
ax_pose 1, 0x01e8, 0x80f5, 0x5c00
ax_pose_terminator
sUnownEPose35:
ax_pose 2, 0x01e8, 0x80f5, 0x5c00
ax_pose_terminator
sUnownEPose36:
ax_pose 3, 0x01e8, 0x80f5, 0x5c00
ax_pose_terminator
sUnownEPose37:
ax_pose 4, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sUnownEPose38:
ax_pose 5, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sUnownEPose39:
ax_pose 6, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sUnownEPose40:
ax_pose 7, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sUnownEPose41:
ax_pose 8, 0x01e8, 0x80f3, 0x5c00
ax_pose_terminator
sUnownEPose42:
ax_pose 9, 0x01e3, 0x80f4, 0x5c00
ax_pose_terminator
sUnownEPose43:
ax_pose 10, 0x01e4, 0x80ed, 0x5c00
ax_pose_terminator
sUnownEPose44:
ax_pose 11, 0x01e4, 0x80ed, 0x5c00
ax_pose_terminator
sUnownEPose45:
ax_pose 12, 0x01e4, 0x80ed, 0x5c00
ax_pose_terminator
sUnownEPose46:
ax_pose 13, 0x01e6, 0x80f4, 0x5c00
ax_pose_terminator
sUnownEPose47:
ax_pose 14, 0x01e4, 0x80f4, 0x5c00
ax_pose_terminator
sUnownEPose48:
ax_pose 15, 0x01e4, 0x80f4, 0x5c00
ax_pose_terminator
sUnownEPose49:
ax_pose 16, 0x01e4, 0x80f3, 0x5c00
ax_pose_terminator
sUnownEPose50:
ax_pose 0, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sUnownEPose51:
ax_pose 1, 0x01e8, 0x80f5, 0x5c00
ax_pose_terminator
sUnownEPose52:
ax_pose 2, 0x01e8, 0x80f5, 0x5c00
ax_pose_terminator
sUnownEPose53:
ax_pose 3, 0x01e8, 0x80f5, 0x5c00
ax_pose_terminator
sUnownEPose54:
ax_pose 4, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sUnownEPose55:
ax_pose 5, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sUnownEPose56:
ax_pose 6, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sUnownEPose57:
ax_pose 7, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sUnownEPose58:
ax_pose 0, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sUnownEPose59:
ax_pose 1, 0x01e8, 0x80f5, 0x5c00
ax_pose_terminator
sUnownEPose60:
ax_pose 2, 0x01e8, 0x80f5, 0x5c00
ax_pose_terminator
sUnownEPose61:
ax_pose 3, 0x01e8, 0x80f5, 0x5c00
ax_pose_terminator
sUnownEPose62:
ax_pose 4, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sUnownEPose63:
ax_pose 5, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sUnownEPose64:
ax_pose 6, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sUnownEPose65:
ax_pose 7, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sUnownEPose66:
ax_pose 0, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sUnownEPose67:
ax_pose 1, 0x01e8, 0x80f5, 0x5c00
ax_pose_terminator
sUnownEPose68:
ax_pose 2, 0x01e8, 0x80f5, 0x5c00
ax_pose_terminator
sUnownEPose69:
ax_pose 3, 0x01e8, 0x80f5, 0x5c00
ax_pose_terminator
sUnownEPose70:
ax_pose 4, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sUnownEPose71:
ax_pose 5, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sUnownEPose72:
ax_pose 6, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sUnownEPose73:
ax_pose 7, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sUnownEPose74:
ax_pose 0, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sUnownEPose75:
ax_pose 1, 0x01e8, 0x80f5, 0x5c00
ax_pose_terminator
sUnownEPose76:
ax_pose 2, 0x01e8, 0x80f5, 0x5c00
ax_pose_terminator
sUnownEPose77:
ax_pose 3, 0x01e8, 0x80f5, 0x5c00
ax_pose_terminator
sUnownEPose78:
ax_pose 4, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sUnownEPose79:
ax_pose 5, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sUnownEPose80:
ax_pose 6, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sUnownEPose81:
ax_pose 7, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sUnownEPose82:
ax_pose 0, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sUnownEPose83:
ax_pose 1, 0x01e8, 0x80f5, 0x5c00
ax_pose_terminator
sUnownEPose84:
ax_pose 2, 0x01e8, 0x80f5, 0x5c00
ax_pose_terminator
sUnownEPose85:
ax_pose 3, 0x01e8, 0x80f5, 0x5c00
ax_pose_terminator
sUnownEPose86:
ax_pose 4, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sUnownEPose87:
ax_pose 5, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sUnownEPose88:
ax_pose 6, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sUnownEPose89:
ax_pose 7, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sUnownEPose90:
ax_pose 0, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sUnownEPose91:
ax_pose 1, 0x01e8, 0x80f5, 0x5c00
ax_pose_terminator
sUnownEPose92:
ax_pose 2, 0x01e8, 0x80f5, 0x5c00
ax_pose_terminator
sUnownEPose93:
ax_pose 3, 0x01e8, 0x80f5, 0x5c00
ax_pose_terminator
sUnownEPose94:
ax_pose 4, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sUnownEPose95:
ax_pose 5, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sUnownEPose96:
ax_pose 6, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
sUnownEPose97:
ax_pose 7, 0x01e8, 0x80f4, 0x5c00
ax_pose_terminator
.align 2
sUnownEAnims_1_1:
ax_anim 6, 0, 0, 0, 0, 0, 0,
ax_anim 6, 0, 0, 2, -1, 2, 0,
ax_anim 5, 0, 0, 3, -2, 3, 0,
ax_anim 5, 0, 0, 3, -3, 3, 0,
ax_anim 6, 0, 0, 2, -4, 2, 0,
ax_anim 6, 0, 0, 0, -5, 0, 0,
ax_anim 6, 0, 0, -2, -4, -2, 0,
ax_anim 5, 0, 0, -3, -3, -3, 0,
ax_anim 5, 0, 0, -3, -2, -3, 0,
ax_anim 6, 0, 0, -2, -1, -2, 0,
ax_anim_terminator
sUnownEAnims_1_2:
ax_anim 6, 0, 1, 0, 0, 0, 0,
ax_anim 6, 0, 1, -2, 0, -1, 1,
ax_anim 5, 0, 1, -3, -1, -2, 2,
ax_anim 5, 0, 1, -3, -2, -2, 2,
ax_anim 6, 0, 1, -2, -3, -1, 1,
ax_anim 6, 0, 1, 0, -5, 0, 0,
ax_anim 6, 0, 1, 2, -5, 1, -1,
ax_anim 5, 0, 1, 3, -4, 2, -2,
ax_anim 5, 0, 1, 3, -3, 2, -2,
ax_anim 6, 0, 1, 2, -2, 1, -1,
ax_anim_terminator
sUnownEAnims_1_3:
ax_anim 6, 0, 2, 0, 0, 0, 0,
ax_anim 6, 0, 2, 1, -1, 1, 1,
ax_anim 5, 0, 2, 2, -2, 2, 1,
ax_anim 5, 0, 2, 2, -3, 2, 1,
ax_anim 6, 0, 2, 1, -4, 1, 1,
ax_anim 6, 0, 2, 0, -5, 0, 0,
ax_anim 6, 0, 2, -1, -4, -1, -1,
ax_anim 5, 0, 2, -2, -3, -2, -1,
ax_anim 5, 0, 2, -2, -2, -2, -1,
ax_anim 6, 0, 2, -1, -1, -1, -1,
ax_anim_terminator
sUnownEAnims_1_4:
ax_anim 6, 0, 3, 0, 0, 0, 0,
ax_anim 6, 0, 3, -1, -1, -1, -1,
ax_anim 5, 0, 3, -2, -2, -2, -2,
ax_anim 5, 0, 3, -3, -3, -2, -2,
ax_anim 6, 0, 3, -2, -4, -1, -1,
ax_anim 6, 0, 3, 0, -5, 0, 0,
ax_anim 6, 0, 3, 1, -4, 1, 1,
ax_anim 5, 0, 3, 2, -3, 2, 2,
ax_anim 5, 0, 3, 3, -2, 2, 2,
ax_anim 6, 0, 3, 2, -1, 1, 1,
ax_anim_terminator
sUnownEAnims_1_5:
ax_anim 6, 0, 4, 0, 0, 0, 0,
ax_anim 6, 0, 4, -2, -1, -2, 0,
ax_anim 5, 0, 4, -3, -2, -3, 0,
ax_anim 5, 0, 4, -3, -3, -3, 0,
ax_anim 6, 0, 4, -2, -4, -2, 0,
ax_anim 6, 0, 4, 0, -5, 0, 0,
ax_anim 6, 0, 4, 2, -4, 2, 0,
ax_anim 5, 0, 4, 3, -3, 3, 0,
ax_anim 5, 0, 4, 3, -2, 3, 0,
ax_anim 6, 0, 4, 2, -1, 2, 0,
ax_anim_terminator
sUnownEAnims_1_6:
ax_anim 6, 0, 5, 0, 0, 0, 0,
ax_anim 6, 0, 5, 1, -1, 1, -1,
ax_anim 5, 0, 5, 2, -2, 2, -2,
ax_anim 5, 0, 5, 3, -3, 2, -2,
ax_anim 6, 0, 5, 2, -4, 1, -1,
ax_anim 6, 0, 5, 0, -5, 0, 0,
ax_anim 6, 0, 5, -1, -4, -1, 1,
ax_anim 5, 0, 5, -2, -3, -2, 2,
ax_anim 5, 0, 5, -3, -2, -2, 2,
ax_anim 6, 0, 5, -2, -1, -1, 1,
ax_anim_terminator
sUnownEAnims_1_7:
ax_anim 6, 0, 6, 0, 0, 0, 0,
ax_anim 6, 0, 6, 1, -1, 1, 1,
ax_anim 5, 0, 6, 2, -2, 2, 1,
ax_anim 5, 0, 6, 2, -3, 2, 1,
ax_anim 6, 0, 6, 1, -4, 1, 1,
ax_anim 6, 0, 6, 0, -5, 0, 0,
ax_anim 6, 0, 6, -1, -4, -1, -1,
ax_anim 5, 0, 6, -2, -3, -2, -1,
ax_anim 5, 0, 6, -2, -2, -2, -1,
ax_anim 6, 0, 6, -1, -1, -1, -1,
ax_anim_terminator
sUnownEAnims_1_8:
ax_anim 6, 0, 7, 0, 0, 0, 0,
ax_anim 6, 0, 7, 2, 0, 1, 1,
ax_anim 5, 0, 7, 3, -1, 2, 2,
ax_anim 5, 0, 7, 3, -2, 2, 2,
ax_anim 6, 0, 7, 2, -3, 1, 1,
ax_anim 6, 0, 7, 0, -5, 0, 0,
ax_anim 6, 0, 7, -2, -5, -1, -1,
ax_anim 5, 0, 7, -3, -4, -2, -2,
ax_anim 5, 0, 7, -3, -3, -2, -2,
ax_anim 6, 0, 7, -2, -2, -1, -1,
ax_anim_terminator
.align 2
sUnownEAnims_2_1:
ax_anim 2, 0, 8, 0, -1, 0, -1,
ax_anim 4, 0, 8, 0, -2, 0, -2,
ax_anim 1, 0, 8, 0, 0, 0, 0,
ax_anim 1, 2, 8, 0, 4, 0, 4,
ax_anim 1, 0, 8, 0, 10, 0, 8,
ax_anim 2, 0, 8, 0, 24, 0, 21,
ax_anim 2, 1, 8, 1, 24, 1, 21,
ax_anim 2, 0, 8, 0, 24, 0, 21,
ax_anim 2, 0, 8, 1, 24, 1, 21,
ax_anim 2, 0, 8, 0, 6, 0, 6,
ax_anim_terminator
sUnownEAnims_2_2:
ax_anim 2, 0, 9, -1, -1, -1, -1,
ax_anim 4, 0, 9, -2, -2, -2, -2,
ax_anim 1, 0, 9, 0, 0, 0, 0,
ax_anim 1, 2, 9, 4, 4, 4, 4,
ax_anim 1, 0, 9, 10, 10, 10, 9,
ax_anim 2, 0, 9, 23, 24, 23, 21,
ax_anim 2, 1, 9, 24, 23, 24, 20,
ax_anim 2, 0, 9, 23, 24, 23, 21,
ax_anim 2, 0, 9, 24, 23, 24, 20,
ax_anim 2, 0, 9, 6, 6, 6, 6,
ax_anim_terminator
sUnownEAnims_2_3:
ax_anim 2, 0, 10, -1, 0, -1, 0,
ax_anim 4, 0, 10, -2, 0, -2, 0,
ax_anim 1, 0, 10, 0, 0, 0, 0,
ax_anim 1, 2, 10, 4, 0, 4, 0,
ax_anim 1, 0, 10, 10, 1, 10, 0,
ax_anim 2, 0, 10, 23, 2, 23, 0,
ax_anim 2, 1, 10, 23, 1, 23, -1,
ax_anim 2, 0, 10, 23, 2, 23, 0,
ax_anim 2, 0, 10, 23, 1, 23, -1,
ax_anim 2, 0, 10, 6, 0, 6, 0,
ax_anim_terminator
sUnownEAnims_2_4:
ax_anim 2, 0, 11, -1, 1, -1, 1,
ax_anim 4, 0, 11, -2, 2, -2, 2,
ax_anim 1, 0, 11, 0, 0, 0, 0,
ax_anim 1, 2, 11, 6, -5, 6, -5,
ax_anim 1, 0, 11, 14, -11, 14, -13,
ax_anim 2, 0, 11, 23, -17, 23, -20,
ax_anim 2, 1, 11, 22, -18, 22, -21,
ax_anim 2, 0, 11, 23, -17, 23, -20,
ax_anim 2, 0, 11, 22, -18, 22, -21,
ax_anim 2, 0, 11, 7, -5, 7, -6,
ax_anim_terminator
sUnownEAnims_2_5:
ax_anim 2, 0, 12, 0, 1, 0, 1,
ax_anim 4, 0, 12, 0, 2, 0, 2,
ax_anim 1, 0, 12, 0, 0, 0, 0,
ax_anim 1, 2, 12, 0, -4, 0, -4,
ax_anim 1, 0, 12, 0, -11, 0, -12,
ax_anim 2, 0, 12, 0, -17, 0, -20,
ax_anim 2, 1, 12, 1, -17, 1, -20,
ax_anim 2, 0, 12, 0, -17, 0, -20,
ax_anim 2, 0, 12, 1, -17, 1, -20,
ax_anim 2, 0, 12, 0, -6, 0, -6,
ax_anim_terminator
sUnownEAnims_2_6:
ax_anim 2, 0, 13, 1, 1, 1, 1,
ax_anim 4, 0, 13, 2, 2, 2, 2,
ax_anim 1, 0, 13, 0, 0, 0, 0,
ax_anim 1, 2, 13, -6, -5, -6, -5,
ax_anim 1, 0, 13, -14, -11, -14, -13,
ax_anim 2, 0, 13, -23, -17, -23, -20,
ax_anim 2, 1, 13, -24, -16, -24, -19,
ax_anim 2, 0, 13, -23, -17, -23, -20,
ax_anim 2, 0, 13, -24, -16, -24, -19,
ax_anim 2, 0, 13, -7, -5, -7, -6,
ax_anim_terminator
sUnownEAnims_2_7:
ax_anim 2, 0, 14, 1, 0, 1, 0,
ax_anim 4, 0, 14, 2, 0, 2, 0,
ax_anim 1, 0, 14, 0, 0, 0, 0,
ax_anim 1, 2, 14, -4, 0, -4, 0,
ax_anim 1, 0, 14, -10, 1, -10, 0,
ax_anim 2, 0, 14, -23, 2, -23, 0,
ax_anim 2, 1, 14, -23, 1, -23, -1,
ax_anim 2, 0, 14, -23, 2, -23, 0,
ax_anim 2, 0, 14, -23, 1, -23, -1,
ax_anim 2, 0, 14, -6, 0, -6, 0,
ax_anim_terminator
sUnownEAnims_2_8:
ax_anim 2, 0, 15, 1, -1, 1, -1,
ax_anim 4, 0, 15, 2, -2, 2, -2,
ax_anim 1, 0, 15, 0, 0, 0, 0,
ax_anim 1, 2, 15, -4, 4, -4, 4,
ax_anim 1, 0, 15, -10, 10, -10, 9,
ax_anim 2, 0, 15, -23, 24, -23, 21,
ax_anim 2, 1, 15, -24, 23, -24, 20,
ax_anim 2, 0, 15, -23, 24, -23, 21,
ax_anim 2, 0, 15, -24, 23, -24, 20,
ax_anim 2, 0, 15, -6, 6, -6, 6,
ax_anim_terminator
.align 2
sUnownEAnims_3_1:
ax_anim 2, 0, 16, 0, -1, 0, -1,
ax_anim 4, 0, 16, 0, -2, 0, -2,
ax_anim 1, 0, 16, 0, 0, 0, 0,
ax_anim 1, 2, 16, 0, 4, 0, 4,
ax_anim 1, 0, 16, 0, 10, 0, 8,
ax_anim 2, 0, 16, 0, 24, 0, 21,
ax_anim 2, 1, 16, 1, 24, 1, 21,
ax_anim 2, 0, 16, 0, 24, 0, 21,
ax_anim 2, 0, 16, 1, 24, 1, 21,
ax_anim 2, 0, 16, 0, 6, 0, 6,
ax_anim_terminator
sUnownEAnims_3_2:
ax_anim 2, 0, 17, -1, -1, -1, -1,
ax_anim 4, 0, 17, -2, -2, -2, -2,
ax_anim 1, 0, 17, 0, 0, 0, 0,
ax_anim 1, 2, 17, 4, 4, 4, 4,
ax_anim 1, 0, 17, 10, 10, 10, 9,
ax_anim 2, 0, 17, 23, 24, 23, 21,
ax_anim 2, 1, 17, 24, 23, 24, 20,
ax_anim 2, 0, 17, 23, 24, 23, 21,
ax_anim 2, 0, 17, 24, 23, 24, 20,
ax_anim 2, 0, 17, 6, 6, 6, 6,
ax_anim_terminator
sUnownEAnims_3_3:
ax_anim 2, 0, 18, -1, 0, -1, 0,
ax_anim 4, 0, 18, -2, 0, -2, 0,
ax_anim 1, 0, 18, 0, 0, 0, 0,
ax_anim 1, 2, 18, 4, 0, 4, 0,
ax_anim 1, 0, 18, 10, 1, 10, 0,
ax_anim 2, 0, 18, 23, 2, 23, 0,
ax_anim 2, 1, 18, 23, 1, 23, -1,
ax_anim 2, 0, 18, 23, 2, 23, 0,
ax_anim 2, 0, 18, 23, 1, 23, -1,
ax_anim 2, 0, 18, 6, 0, 6, 0,
ax_anim_terminator
sUnownEAnims_3_4:
ax_anim 2, 0, 19, -1, 1, -1, 1,
ax_anim 4, 0, 19, -2, 2, -2, 2,
ax_anim 1, 0, 19, 0, 0, 0, 0,
ax_anim 1, 2, 19, 6, -5, 6, -5,
ax_anim 1, 0, 19, 14, -11, 14, -13,
ax_anim 2, 0, 19, 23, -17, 23, -20,
ax_anim 2, 1, 19, 22, -18, 22, -21,
ax_anim 2, 0, 19, 23, -17, 23, -20,
ax_anim 2, 0, 19, 22, -18, 22, -21,
ax_anim 2, 0, 19, 7, -5, 7, -6,
ax_anim_terminator
sUnownEAnims_3_5:
ax_anim 2, 0, 20, 0, 1, 0, 1,
ax_anim 4, 0, 20, 0, 2, 0, 2,
ax_anim 1, 0, 20, 0, 0, 0, 0,
ax_anim 1, 2, 20, 0, -4, 0, -4,
ax_anim 1, 0, 20, 0, -11, 0, -12,
ax_anim 2, 0, 20, 0, -17, 0, -20,
ax_anim 2, 1, 20, 1, -17, 1, -20,
ax_anim 2, 0, 20, 0, -17, 0, -20,
ax_anim 2, 0, 20, 1, -17, 1, -20,
ax_anim 2, 0, 20, 0, -6, 0, -6,
ax_anim_terminator
sUnownEAnims_3_6:
ax_anim 2, 0, 21, 1, 1, 1, 1,
ax_anim 4, 0, 21, 2, 2, 2, 2,
ax_anim 1, 0, 21, 0, 0, 0, 0,
ax_anim 1, 2, 21, -6, -5, -6, -5,
ax_anim 1, 0, 21, -14, -11, -14, -13,
ax_anim 2, 0, 21, -23, -17, -23, -20,
ax_anim 2, 1, 21, -24, -16, -24, -19,
ax_anim 2, 0, 21, -23, -17, -23, -20,
ax_anim 2, 0, 21, -24, -16, -24, -19,
ax_anim 2, 0, 21, -7, -5, -7, -6,
ax_anim_terminator
sUnownEAnims_3_7:
ax_anim 2, 0, 22, 1, 0, 1, 0,
ax_anim 4, 0, 22, 2, 0, 2, 0,
ax_anim 1, 0, 22, 0, 0, 0, 0,
ax_anim 1, 2, 22, -4, 0, -4, 0,
ax_anim 1, 0, 22, -10, 1, -10, 0,
ax_anim 2, 0, 22, -23, 2, -23, 0,
ax_anim 2, 1, 22, -23, 1, -23, -1,
ax_anim 2, 0, 22, -23, 2, -23, 0,
ax_anim 2, 0, 22, -23, 1, -23, -1,
ax_anim 2, 0, 22, -6, 0, -6, 0,
ax_anim_terminator
sUnownEAnims_3_8:
ax_anim 2, 0, 23, 1, -1, 1, -1,
ax_anim 4, 0, 23, 2, -2, 2, -2,
ax_anim 1, 0, 23, 0, 0, 0, 0,
ax_anim 1, 2, 23, -4, 4, -4, 4,
ax_anim 1, 0, 23, -10, 10, -10, 9,
ax_anim 2, 0, 23, -23, 24, -23, 21,
ax_anim 2, 1, 23, -24, 23, -24, 20,
ax_anim 2, 0, 23, -23, 24, -23, 21,
ax_anim 2, 0, 23, -24, 23, -24, 20,
ax_anim 2, 0, 23, -6, 6, -6, 6,
ax_anim_terminator
.align 2
sUnownEAnims_4_1:
ax_anim 2, 0, 24, 1, 0, 1, 0,
ax_anim 2, 0, 24, 0, 0, 0, 0,
ax_anim 2, 0, 24, 1, 0, 1, 0,
ax_anim 2, 0, 24, 0, 0, 0, 0,
ax_anim 2, 0, 24, 1, 0, 1, 0,
ax_anim 2, 2, 24, 0, 0, 0, 0,
ax_anim 2, 0, 24, 1, 0, 1, 0,
ax_anim 2, 0, 24, 0, 0, 0, 0,
ax_anim 2, 0, 24, 1, 0, 1, 0,
ax_anim 2, 1, 24, 0, 0, 0, 0,
ax_anim_terminator
sUnownEAnims_4_2:
ax_anim 2, 0, 25, 1, -1, 1, -1,
ax_anim 2, 0, 25, 0, 0, 0, 0,
ax_anim 2, 0, 25, 1, -1, 1, -1,
ax_anim 2, 0, 25, 0, 0, 0, 0,
ax_anim 2, 0, 25, 1, -1, 1, -1,
ax_anim 2, 2, 25, 0, 0, 0, 0,
ax_anim 2, 0, 25, 1, -1, 1, -1,
ax_anim 2, 0, 25, 0, 0, 0, 0,
ax_anim 2, 0, 25, 1, -1, 1, -1,
ax_anim 2, 1, 25, 0, 0, 0, 0,
ax_anim_terminator
sUnownEAnims_4_3:
ax_anim 2, 0, 26, 0, -1, 0, -1,
ax_anim 2, 0, 26, 0, 0, 0, 0,
ax_anim 2, 0, 26, 0, -1, 0, -1,
ax_anim 2, 0, 26, 0, 0, 0, 0,
ax_anim 2, 0, 26, 0, -1, 0, -1,
ax_anim 2, 2, 26, 0, 0, 0, 0,
ax_anim 2, 0, 26, 0, -1, 0, -1,
ax_anim 2, 0, 26, 0, 0, 0, 0,
ax_anim 2, 0, 26, 0, -1, 0, -1,
ax_anim 2, 1, 26, 0, 0, 0, 0,
ax_anim_terminator
sUnownEAnims_4_4:
ax_anim 2, 0, 27, -1, -1, -1, -1,
ax_anim 2, 0, 27, 0, 0, 0, 0,
ax_anim 2, 0, 27, -1, -1, -1, -1,
ax_anim 2, 0, 27, 0, 0, 0, 0,
ax_anim 2, 0, 27, -1, -1, -1, -1,
ax_anim 2, 2, 27, 0, 0, 0, 0,
ax_anim 2, 0, 27, -1, -1, -1, -1,
ax_anim 2, 0, 27, 0, 0, 0, 0,
ax_anim 2, 0, 27, -1, -1, -1, -1,
ax_anim 2, 1, 27, 0, 0, 0, 0,
ax_anim_terminator
sUnownEAnims_4_5:
ax_anim 2, 0, 28, 1, 0, 1, 0,
ax_anim 2, 0, 28, 0, 0, 0, 0,
ax_anim 2, 0, 28, 1, 0, 1, 0,
ax_anim 2, 0, 28, 0, 0, 0, 0,
ax_anim 2, 0, 28, 1, 0, 1, 0,
ax_anim 2, 2, 28, 0, 0, 0, 0,
ax_anim 2, 0, 28, 1, 0, 1, 0,
ax_anim 2, 0, 28, 0, 0, 0, 0,
ax_anim 2, 0, 28, 1, 0, 1, 0,
ax_anim 2, 1, 28, 0, 0, 0, 0,
ax_anim_terminator
sUnownEAnims_4_6:
ax_anim 2, 0, 29, 1, -1, 1, -1,
ax_anim 2, 0, 29, 0, 0, 0, 0,
ax_anim 2, 0, 29, 1, -1, 1, -1,
ax_anim 2, 0, 29, 0, 0, 0, 0,
ax_anim 2, 0, 29, 1, -1, 1, -1,
ax_anim 2, 2, 29, 0, 0, 0, 0,
ax_anim 2, 0, 29, 1, -1, 1, -1,
ax_anim 2, 0, 29, 0, 0, 0, 0,
ax_anim 2, 0, 29, 1, -1, 1, -1,
ax_anim 2, 1, 29, 0, 0, 0, 0,
ax_anim_terminator
sUnownEAnims_4_7:
ax_anim 2, 0, 30, 0, -1, 0, -1,
ax_anim 2, 0, 30, 0, 0, 0, 0,
ax_anim 2, 0, 30, 0, -1, 0, -1,
ax_anim 2, 0, 30, 0, 0, 0, 0,
ax_anim 2, 0, 30, 0, -1, 0, -1,
ax_anim 2, 2, 30, 0, 0, 0, 0,
ax_anim 2, 0, 30, 0, -1, 0, -1,
ax_anim 2, 0, 30, 0, 0, 0, 0,
ax_anim 2, 0, 30, 0, -1, 0, -1,
ax_anim 2, 1, 30, 0, 0, 0, 0,
ax_anim_terminator
sUnownEAnims_4_8:
ax_anim 2, 0, 31, -1, -1, -1, -1,
ax_anim 2, 0, 31, 0, 0, 0, 0,
ax_anim 2, 0, 31, -1, -1, -1, -1,
ax_anim 2, 0, 31, 0, 0, 0, 0,
ax_anim 2, 0, 31, -1, -1, -1, -1,
ax_anim 2, 2, 31, 0, 0, 0, 0,
ax_anim 2, 0, 31, -1, -1, -1, -1,
ax_anim 2, 0, 31, 0, 0, 0, 0,
ax_anim 2, 0, 31, -1, -1, -1, -1,
ax_anim 2, 1, 31, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sUnownEAnims_5_1:
ax_anim 2, 0, 32, 0, 0, 0, 0,
ax_anim 2, 0, 33, 0, 0, 0, 0,
ax_anim 2, 0, 34, 0, 0, 0, 0,
ax_anim 2, 0, 35, 0, 0, 0, 0,
ax_anim 2, 0, 36, 0, 0, 0, 0,
ax_anim 2, 0, 37, 0, 0, 0, 0,
ax_anim 2, 0, 38, 0, 0, 0, 0,
ax_anim 2, 0, 39, 0, 0, 0, 0,
ax_anim 2, 2, 32, 0, 0, 0, 0,
ax_anim_terminator
sUnownEAnims_5_2:
ax_anim 2, 0, 33, 0, 0, 0, 0,
ax_anim 2, 0, 34, 0, 0, 0, 0,
ax_anim 2, 0, 35, 0, 0, 0, 0,
ax_anim 2, 0, 36, 0, 0, 0, 0,
ax_anim 2, 0, 37, 0, 0, 0, 0,
ax_anim 2, 0, 38, 0, 0, 0, 0,
ax_anim 2, 0, 39, 0, 0, 0, 0,
ax_anim 2, 0, 32, 0, 0, 0, 0,
ax_anim 2, 2, 33, 0, 0, 0, 0,
ax_anim_terminator
sUnownEAnims_5_3:
ax_anim 2, 0, 34, 0, 0, 0, 0,
ax_anim 2, 0, 35, 0, 0, 0, 0,
ax_anim 2, 0, 36, 0, 0, 0, 0,
ax_anim 2, 0, 37, 0, 0, 0, 0,
ax_anim 2, 0, 38, 0, 0, 0, 0,
ax_anim 2, 0, 39, 0, 0, 0, 0,
ax_anim 2, 0, 32, 0, 0, 0, 0,
ax_anim 2, 0, 33, 0, 0, 0, 0,
ax_anim 2, 2, 34, 0, 0, 0, 0,
ax_anim_terminator
sUnownEAnims_5_4:
ax_anim 2, 0, 35, 0, 0, 0, 0,
ax_anim 2, 0, 36, 0, 0, 0, 0,
ax_anim 2, 0, 37, 0, 0, 0, 0,
ax_anim 2, 0, 38, 0, 0, 0, 0,
ax_anim 2, 0, 39, 0, 0, 0, 0,
ax_anim 2, 0, 32, 0, 0, 0, 0,
ax_anim 2, 0, 33, 0, 0, 0, 0,
ax_anim 2, 0, 34, 0, 0, 0, 0,
ax_anim 2, 2, 35, 0, 0, 0, 0,
ax_anim_terminator
sUnownEAnims_5_5:
ax_anim 2, 0, 36, 0, 0, 0, 0,
ax_anim 2, 0, 37, 0, 0, 0, 0,
ax_anim 2, 0, 38, 0, 0, 0, 0,
ax_anim 2, 0, 39, 0, 0, 0, 0,
ax_anim 2, 0, 32, 0, 0, 0, 0,
ax_anim 2, 0, 33, 0, 0, 0, 0,
ax_anim 2, 0, 34, 0, 0, 0, 0,
ax_anim 2, 0, 35, 0, 0, 0, 0,
ax_anim 2, 2, 36, 0, 0, 0, 0,
ax_anim_terminator
sUnownEAnims_5_6:
ax_anim 2, 0, 37, 0, 0, 0, 0,
ax_anim 2, 0, 38, 0, 0, 0, 0,
ax_anim 2, 0, 39, 0, 0, 0, 0,
ax_anim 2, 0, 32, 0, 0, 0, 0,
ax_anim 2, 0, 33, 0, 0, 0, 0,
ax_anim 2, 0, 34, 0, 0, 0, 0,
ax_anim 2, 0, 35, 0, 0, 0, 0,
ax_anim 2, 0, 36, 0, 0, 0, 0,
ax_anim 2, 2, 37, 0, 0, 0, 0,
ax_anim_terminator
sUnownEAnims_5_7:
ax_anim 2, 0, 38, 0, 0, 0, 0,
ax_anim 2, 0, 39, 0, 0, 0, 0,
ax_anim 2, 0, 32, 0, 0, 0, 0,
ax_anim 2, 0, 33, 0, 0, 0, 0,
ax_anim 2, 0, 34, 0, 0, 0, 0,
ax_anim 2, 0, 35, 0, 0, 0, 0,
ax_anim 2, 0, 36, 0, 0, 0, 0,
ax_anim 2, 0, 37, 0, 0, 0, 0,
ax_anim 2, 2, 38, 0, 0, 0, 0,
ax_anim_terminator
sUnownEAnims_5_8:
ax_anim 2, 0, 39, 0, 0, 0, 0,
ax_anim 2, 0, 32, 0, 0, 0, 0,
ax_anim 2, 0, 33, 0, 0, 0, 0,
ax_anim 2, 0, 34, 0, 0, 0, 0,
ax_anim 2, 0, 35, 0, 0, 0, 0,
ax_anim 2, 0, 36, 0, 0, 0, 0,
ax_anim 2, 0, 37, 0, 0, 0, 0,
ax_anim 2, 0, 38, 0, 0, 0, 0,
ax_anim 2, 2, 39, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sUnownEAnims_6_1:
ax_anim 30, 0, 40, 0, 0, 0, 0,
ax_anim 4, 0, 40, 0, 1, 0, 0,
ax_anim 35, 0, 40, 0, 2, 0, 0,
ax_anim 4, 0, 40, 0, 1, 0, 0,
ax_anim_terminator
.align 2
sUnownEAnims_7_1:
ax_anim 2, 0, 41, 0, -2, 0, -2,
ax_anim 8, 0, 41, 0, -3, 0, -3,
ax_anim_terminator
sUnownEAnims_7_2:
ax_anim 2, 0, 42, -2, -2, -2, -2,
ax_anim 8, 0, 42, -3, -3, -3, -3,
ax_anim_terminator
sUnownEAnims_7_3:
ax_anim 2, 0, 43, -2, 0, -2, 0,
ax_anim 8, 0, 43, -3, 0, -3, 0,
ax_anim_terminator
sUnownEAnims_7_4:
ax_anim 2, 0, 44, -2, 2, -2, 2,
ax_anim 8, 0, 44, -3, 3, -3, 3,
ax_anim_terminator
sUnownEAnims_7_5:
ax_anim 2, 0, 45, 0, 2, 0, 2,
ax_anim 8, 0, 45, 0, 3, 0, 3,
ax_anim_terminator
sUnownEAnims_7_6:
ax_anim 2, 0, 46, 2, 2, 2, 2,
ax_anim 8, 0, 46, 3, 3, 3, 3,
ax_anim_terminator
sUnownEAnims_7_7:
ax_anim 2, 0, 47, 2, 0, 2, 0,
ax_anim 8, 0, 47, 3, 0, 3, 0,
ax_anim_terminator
sUnownEAnims_7_8:
ax_anim 2, 0, 48, 2, -2, 2, -2,
ax_anim 8, 0, 48, 3, -3, 3, -3,
ax_anim_terminator
.align 2
sUnownEAnims_8_1:
ax_anim 20, 0, 49, 0, 0, 0, 0,
ax_anim 8, 0, 49, 0, -1, 0, 0,
ax_anim 20, 0, 49, 0, -2, 0, 0,
ax_anim 8, 0, 49, 0, -1, 0, 0,
ax_anim_terminator
sUnownEAnims_8_2:
ax_anim 20, 0, 50, 0, 0, 0, 0,
ax_anim 8, 0, 50, 0, -1, 0, 0,
ax_anim 20, 0, 50, 0, -2, 0, 0,
ax_anim 8, 0, 50, 0, -1, 0, 0,
ax_anim_terminator
sUnownEAnims_8_3:
ax_anim 20, 0, 51, 0, 0, 0, 0,
ax_anim 8, 0, 51, 0, -1, 0, 0,
ax_anim 20, 0, 51, 0, -2, 0, 0,
ax_anim 8, 0, 51, 0, -1, 0, 0,
ax_anim_terminator
sUnownEAnims_8_4:
ax_anim 20, 0, 52, 0, 0, 0, 0,
ax_anim 8, 0, 52, 0, -1, 0, 0,
ax_anim 20, 0, 52, 0, -2, 0, 0,
ax_anim 8, 0, 52, 0, -1, 0, 0,
ax_anim_terminator
sUnownEAnims_8_5:
ax_anim 20, 0, 53, 0, 0, 0, 0,
ax_anim 8, 0, 53, 0, -1, 0, 0,
ax_anim 20, 0, 53, 0, -2, 0, 0,
ax_anim 8, 0, 53, 0, -1, 0, 0,
ax_anim_terminator
sUnownEAnims_8_6:
ax_anim 20, 0, 54, 0, 0, 0, 0,
ax_anim 8, 0, 54, 0, -1, 0, 0,
ax_anim 20, 0, 54, 0, -2, 0, 0,
ax_anim 8, 0, 54, 0, -1, 0, 0,
ax_anim_terminator
sUnownEAnims_8_7:
ax_anim 20, 0, 55, 0, 0, 0, 0,
ax_anim 8, 0, 55, 0, -1, 0, 0,
ax_anim 20, 0, 55, 0, -2, 0, 0,
ax_anim 8, 0, 55, 0, -1, 0, 0,
ax_anim_terminator
sUnownEAnims_8_8:
ax_anim 20, 0, 56, 0, 0, 0, 0,
ax_anim 8, 0, 56, 0, -1, 0, 0,
ax_anim 20, 0, 56, 0, -2, 0, 0,
ax_anim 8, 0, 56, 0, -1, 0, 0,
ax_anim_terminator
.align 2
sUnownEAnims_9_1:
ax_anim 2, 0, 57, 0, 0, 0, 0,
ax_anim 1, 0, 64, 6, 3, 6, 3,
ax_anim 2, 0, 63, 8, 9, 8, 9,
ax_anim 2, 0, 62, 7, 18, 7, 18,
ax_anim 3, 0, 61, 0, 22, 0, 22,
ax_anim 2, 3, 60, -7, 18, -7, 18,
ax_anim 2, 0, 59, -8, 9, -8, 9,
ax_anim 1, 0, 58, -6, 3, -6, 3,
ax_anim 1, 0, 57, 0, 0, 0, 0,
ax_anim_terminator
sUnownEAnims_9_2:
ax_anim 2, 0, 58, 0, 0, 0, 0,
ax_anim 1, 0, 57, 11, 0, 11, 0,
ax_anim 2, 0, 64, 21, 3, 21, 3,
ax_anim 2, 0, 63, 26, 10, 26, 10,
ax_anim 3, 0, 62, 20, 18, 20, 18,
ax_anim 2, 3, 61, 11, 19, 11, 19,
ax_anim 2, 0, 60, 3, 15, 3, 15,
ax_anim 1, 0, 59, 0, 7, 0, 7,
ax_anim 1, 0, 58, 0, 0, 0, 0,
ax_anim_terminator
sUnownEAnims_9_3:
ax_anim 2, 0, 59, 0, 0, 0, 0,
ax_anim 1, 0, 58, 5, -5, 5, -5,
ax_anim 2, 0, 57, 13, -6, 13, -6,
ax_anim 2, 0, 64, 20, -5, 20, -5,
ax_anim 3, 0, 63, 23, 0, 23, 0,
ax_anim 2, 3, 62, 20, 4, 20, 4,
ax_anim 2, 0, 61, 14, 7, 14, 7,
ax_anim 1, 0, 60, 6, 5, 6, 5,
ax_anim 1, 0, 59, 2, 0, 2, 0,
ax_anim_terminator
sUnownEAnims_9_4:
ax_anim 2, 0, 60, 0, 0, 0, 0,
ax_anim 1, 0, 59, -1, -6, -1, -6,
ax_anim 2, 0, 58, 4, -17, 4, -17,
ax_anim 2, 0, 57, 15, -22, 15, -22,
ax_anim 3, 0, 64, 21, -21, 21, -21,
ax_anim 2, 3, 63, 24, -13, 24, -13,
ax_anim 2, 0, 62, 19, -4, 19, -4,
ax_anim 1, 0, 61, 9, 0, 9, 0,
ax_anim 1, 0, 60, 0, 0, 0, 0,
ax_anim_terminator
sUnownEAnims_9_5:
ax_anim 2, 0, 61, 0, 0, 0, 0,
ax_anim 1, 0, 60, -8, -4, -8, -4,
ax_anim 2, 0, 59, -9, -12, -9, -12,
ax_anim 2, 0, 58, -7, -20, -7, -20,
ax_anim 3, 0, 57, 0, -22, 0, -22,
ax_anim 2, 3, 64, 7, -20, 7, -20,
ax_anim 2, 0, 63, 9, -10, 9, -10,
ax_anim 1, 0, 62, 8, -4, 8, -4,
ax_anim 1, 0, 61, 0, 0, 0, 0,
ax_anim_terminator
sUnownEAnims_9_6:
ax_anim 2, 0, 62, 0, 0, 0, 0,
ax_anim 1, 0, 63, 1, -6, 1, -6,
ax_anim 2, 0, 64, -4, -17, -4, -17,
ax_anim 2, 0, 57, -15, -22, -15, -22,
ax_anim 3, 0, 58, -21, -21, -21, -21,
ax_anim 2, 3, 59, -24, -13, -24, -13,
ax_anim 2, 0, 60, -19, -4, -19, -4,
ax_anim 1, 0, 61, -9, 0, -9, 0,
ax_anim 1, 0, 62, 0, 0, 0, 0,
ax_anim_terminator
sUnownEAnims_9_7:
ax_anim 2, 0, 63, 0, 0, 0, 0,
ax_anim 1, 0, 64, -5, -5, -5, -5,
ax_anim 2, 0, 57, -13, -6, -13, -6,
ax_anim 2, 0, 58, -20, -5, -20, -5,
ax_anim 3, 0, 59, -23, 0, -23, 0,
ax_anim 2, 3, 60, -20, 4, -20, 4,
ax_anim 2, 0, 61, -14, 7, -14, 7,
ax_anim 1, 0, 62, -6, 5, -6, 5,
ax_anim 1, 0, 63, -2, 0, -2, 0,
ax_anim_terminator
sUnownEAnims_9_8:
ax_anim 2, 0, 64, 0, 0, 0, 0,
ax_anim 1, 0, 57, -11, 0, -11, 0,
ax_anim 2, 0, 58, -21, 3, -21, 3,
ax_anim 2, 0, 59, -26, 10, -26, 10,
ax_anim 3, 0, 60, -20, 18, -20, 18,
ax_anim 2, 3, 61, -11, 19, -11, 19,
ax_anim 2, 0, 62, -3, 15, -3, 15,
ax_anim 1, 0, 63, 0, 7, 0, 7,
ax_anim 1, 0, 64, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sUnownEAnims_10_1:
ax_anim 2, 0, 65, 0, 0, 0, 0,
ax_anim 2, 0, 65, 6, 0, 6, 0,
ax_anim 2, 0, 65, -6, 0, -6, 0,
ax_anim 2, 0, 65, 10, 0, 10, 0,
ax_anim 2, 0, 65, -10, 0, -10, 0,
ax_anim 2, 0, 65, 12, 0, 12, 0,
ax_anim 3, 0, 65, -12, 0, -12, 0,
ax_anim 3, 0, 65, 13, 0, 13, 0,
ax_anim 3, 0, 65, -13, 0, -13, 0,
ax_anim 2, 0, 65, 12, 0, 12, 0,
ax_anim 3, 0, 65, -12, 0, -12, 0,
ax_anim 2, 0, 65, 10, 0, 10, 0,
ax_anim 2, 0, 65, -10, 0, -10, 0,
ax_anim 2, 0, 65, 6, 0, 6, 0,
ax_anim 2, 0, 65, -6, 0, -6, 0,
ax_anim 2, 0, 65, 0, 0, 0, 0,
ax_anim_terminator
sUnownEAnims_10_2:
ax_anim 2, 0, 66, 0, 0, 0, 0,
ax_anim 2, 0, 66, 6, -6, 6, -6,
ax_anim 2, 0, 66, -6, 6, -6, 6,
ax_anim 2, 0, 66, 10, -10, 10, -10,
ax_anim 2, 0, 66, -10, 10, -10, 10,
ax_anim 2, 0, 66, 12, -12, 12, -12,
ax_anim 3, 0, 66, -12, 12, -12, 12,
ax_anim 3, 0, 66, 13, -13, 13, -13,
ax_anim 3, 0, 66, -13, 13, -13, 13,
ax_anim 2, 0, 66, 12, -12, 12, -12,
ax_anim 3, 0, 66, -12, 12, -12, 12,
ax_anim 2, 0, 66, 10, -10, 10, -10,
ax_anim 2, 0, 66, -10, 10, -10, 10,
ax_anim 2, 0, 66, 6, -6, 6, -6,
ax_anim 2, 0, 66, -6, 6, -6, 6,
ax_anim 2, 0, 66, 0, 0, 0, 0,
ax_anim_terminator
sUnownEAnims_10_3:
ax_anim 2, 0, 67, 0, 0, 0, 0,
ax_anim 2, 0, 67, 0, -6, 0, -6,
ax_anim 2, 0, 67, 0, 6, 0, 6,
ax_anim 2, 0, 67, 0, -10, 0, -10,
ax_anim 2, 0, 67, 0, 10, 0, 10,
ax_anim 2, 0, 67, 0, -12, 0, -12,
ax_anim 3, 0, 67, 0, 12, 0, 12,
ax_anim 3, 0, 67, 0, -13, 0, -13,
ax_anim 3, 0, 67, 0, 13, 0, 13,
ax_anim 2, 0, 67, 0, -12, 0, -12,
ax_anim 3, 0, 67, 0, 12, 0, 12,
ax_anim 2, 0, 67, 0, -10, 0, -10,
ax_anim 2, 0, 67, 0, 10, 0, 10,
ax_anim 2, 0, 67, 0, -6, 0, -6,
ax_anim 2, 0, 67, 0, 6, 0, 6,
ax_anim 2, 0, 67, 0, 0, 0, 0,
ax_anim_terminator
sUnownEAnims_10_4:
ax_anim 2, 0, 68, 0, 0, 0, 0,
ax_anim 2, 0, 68, -6, -6, -6, -6,
ax_anim 2, 0, 68, 6, 6, 6, 6,
ax_anim 2, 0, 68, -10, -10, -10, -10,
ax_anim 2, 0, 68, 10, 10, 10, 10,
ax_anim 2, 0, 68, -12, -12, -12, -12,
ax_anim 3, 0, 68, 12, 12, 12, 12,
ax_anim 3, 0, 68, -13, -13, -13, -13,
ax_anim 3, 0, 68, 13, 13, 13, 13,
ax_anim 2, 0, 68, -12, -12, -12, -12,
ax_anim 3, 0, 68, 12, 12, 12, 12,
ax_anim 2, 0, 68, -10, -10, -10, -10,
ax_anim 2, 0, 68, 10, 10, 10, 10,
ax_anim 2, 0, 68, -6, -6, -6, -6,
ax_anim 2, 0, 68, 6, 6, 6, 6,
ax_anim 2, 0, 68, 0, 0, 0, 0,
ax_anim_terminator
sUnownEAnims_10_5:
ax_anim 2, 0, 69, 0, 0, 0, 0,
ax_anim 2, 0, 69, 6, 0, 6, 0,
ax_anim 2, 0, 69, -6, 0, -6, 0,
ax_anim 2, 0, 69, 10, 0, 10, 0,
ax_anim 2, 0, 69, -10, 0, -10, 0,
ax_anim 2, 0, 69, 12, 0, 12, 0,
ax_anim 3, 0, 69, -12, 0, -12, 0,
ax_anim 3, 0, 69, 13, 0, 13, 0,
ax_anim 3, 0, 69, -13, 0, -13, 0,
ax_anim 2, 0, 69, 12, 0, 12, 0,
ax_anim 3, 0, 69, -12, 0, -12, 0,
ax_anim 2, 0, 69, 10, 0, 10, 0,
ax_anim 2, 0, 69, -10, 0, -10, 0,
ax_anim 2, 0, 69, 6, 0, 6, 0,
ax_anim 2, 0, 69, -6, 0, -6, 0,
ax_anim 2, 0, 69, 0, 0, 0, 0,
ax_anim_terminator
sUnownEAnims_10_6:
ax_anim 2, 0, 70, 0, 0, 0, 0,
ax_anim 2, 0, 70, 6, -6, 6, -6,
ax_anim 2, 0, 70, -6, 6, -6, 6,
ax_anim 2, 0, 70, 10, -10, 10, -10,
ax_anim 2, 0, 70, -10, 10, -10, 10,
ax_anim 2, 0, 70, 12, -12, 12, -12,
ax_anim 3, 0, 70, -12, 12, -12, 12,
ax_anim 3, 0, 70, 13, -13, 13, -13,
ax_anim 3, 0, 70, -13, 13, -13, 13,
ax_anim 2, 0, 70, 12, -12, 12, -12,
ax_anim 3, 0, 70, -12, 12, -12, 12,
ax_anim 2, 0, 70, 10, -10, 10, -10,
ax_anim 2, 0, 70, -10, 10, -10, 10,
ax_anim 2, 0, 70, 6, -6, 6, -6,
ax_anim 2, 0, 70, -6, 6, -6, 6,
ax_anim 2, 0, 70, 0, 0, 0, 0,
ax_anim_terminator
sUnownEAnims_10_7:
ax_anim 2, 0, 71, 0, 0, 0, 0,
ax_anim 2, 0, 71, 0, -6, 0, -6,
ax_anim 2, 0, 71, 0, 6, 0, 6,
ax_anim 2, 0, 71, 0, -10, 0, -10,
ax_anim 2, 0, 71, 0, 10, 0, 10,
ax_anim 2, 0, 71, 0, -12, 0, -12,
ax_anim 3, 0, 71, 0, 12, 0, 12,
ax_anim 3, 0, 71, 0, -13, 0, -13,
ax_anim 3, 0, 71, 0, 13, 0, 13,
ax_anim 2, 0, 71, 0, -12, 0, -12,
ax_anim 3, 0, 71, 0, 12, 0, 12,
ax_anim 2, 0, 71, 0, -10, 0, -10,
ax_anim 2, 0, 71, 0, 10, 0, 10,
ax_anim 2, 0, 71, 0, -6, 0, -6,
ax_anim 2, 0, 71, 0, 6, 0, 6,
ax_anim 2, 0, 71, 0, 0, 0, 0,
ax_anim_terminator
sUnownEAnims_10_8:
ax_anim 2, 0, 72, 0, 0, 0, 0,
ax_anim 2, 0, 72, -6, -6, -6, -6,
ax_anim 2, 0, 72, 6, 6, 6, 6,
ax_anim 2, 0, 72, -10, -10, -10, -10,
ax_anim 2, 0, 72, 10, 10, 10, 10,
ax_anim 2, 0, 72, -12, -12, -12, -12,
ax_anim 3, 0, 72, 12, 12, 12, 12,
ax_anim 3, 0, 72, -13, -13, -13, -13,
ax_anim 3, 0, 72, 13, 13, 13, 13,
ax_anim 2, 0, 72, -12, -12, -12, -12,
ax_anim 3, 0, 72, 12, 12, 12, 12,
ax_anim 2, 0, 72, -10, -10, -10, -10,
ax_anim 2, 0, 72, 10, 10, 10, 10,
ax_anim 2, 0, 72, -6, -6, -6, -6,
ax_anim 2, 0, 72, 6, 6, 6, 6,
ax_anim 2, 0, 72, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sUnownEAnims_11_1:
ax_anim 2, 0, 73, 0, 0, 0, 0,
ax_anim 1, 0, 73, 0, -10, 0, 0,
ax_anim 2, 0, 73, 0, -16, 0, 0,
ax_anim 3, 0, 73, 0, -20, 0, 0,
ax_anim 4, 0, 73, 0, -21, 0, 0,
ax_anim 4, 0, 73, 0, -22, 0, 0,
ax_anim 3, 0, 73, 0, -21, 0, 0,
ax_anim 2, 0, 73, 0, -18, 0, 0,
ax_anim 1, 0, 73, 0, -12, 0, 0,
ax_anim 2, 2, 73, 0, 4, 0, 0,
ax_anim_terminator
sUnownEAnims_11_2:
ax_anim 2, 0, 74, 0, 0, 0, 0,
ax_anim 1, 0, 74, 0, -10, 0, 0,
ax_anim 2, 0, 74, 0, -16, 0, 0,
ax_anim 3, 0, 74, 0, -20, 0, 0,
ax_anim 4, 0, 74, 0, -21, 0, 0,
ax_anim 4, 0, 74, 0, -22, 0, 0,
ax_anim 3, 0, 74, 0, -21, 0, 0,
ax_anim 2, 0, 74, 0, -18, 0, 0,
ax_anim 1, 0, 74, 0, -12, 0, 0,
ax_anim 2, 2, 74, 0, 4, 0, 0,
ax_anim_terminator
sUnownEAnims_11_3:
ax_anim 2, 0, 75, 0, 0, 0, 0,
ax_anim 1, 0, 75, 0, -10, 0, 0,
ax_anim 2, 0, 75, 0, -16, 0, 0,
ax_anim 3, 0, 75, 0, -20, 0, 0,
ax_anim 4, 0, 75, 0, -21, 0, 0,
ax_anim 4, 0, 75, 0, -22, 0, 0,
ax_anim 3, 0, 75, 0, -21, 0, 0,
ax_anim 2, 0, 75, 0, -18, 0, 0,
ax_anim 1, 0, 75, 0, -12, 0, 0,
ax_anim 2, 2, 75, 0, 4, 0, 0,
ax_anim_terminator
sUnownEAnims_11_4:
ax_anim 2, 0, 76, 0, 0, 0, 0,
ax_anim 1, 0, 76, 0, -10, 0, 0,
ax_anim 2, 0, 76, 0, -16, 0, 0,
ax_anim 3, 0, 76, 0, -20, 0, 0,
ax_anim 4, 0, 76, 0, -21, 0, 0,
ax_anim 4, 0, 76, 0, -22, 0, 0,
ax_anim 3, 0, 76, 0, -21, 0, 0,
ax_anim 2, 0, 76, 0, -18, 0, 0,
ax_anim 1, 0, 76, 0, -12, 0, 0,
ax_anim 2, 2, 76, 0, 4, 0, 0,
ax_anim_terminator
sUnownEAnims_11_5:
ax_anim 2, 0, 77, 0, 0, 0, 0,
ax_anim 1, 0, 77, 0, -10, 0, 0,
ax_anim 2, 0, 77, 0, -16, 0, 0,
ax_anim 3, 0, 77, 0, -20, 0, 0,
ax_anim 4, 0, 77, 0, -21, 0, 0,
ax_anim 4, 0, 77, 0, -22, 0, 0,
ax_anim 3, 0, 77, 0, -21, 0, 0,
ax_anim 2, 0, 77, 0, -18, 0, 0,
ax_anim 1, 0, 77, 0, -12, 0, 0,
ax_anim 2, 2, 77, 0, 4, 0, 0,
ax_anim_terminator
sUnownEAnims_11_6:
ax_anim 2, 0, 78, 0, 0, 0, 0,
ax_anim 1, 0, 78, 0, -10, 0, 0,
ax_anim 2, 0, 78, 0, -16, 0, 0,
ax_anim 3, 0, 78, 0, -20, 0, 0,
ax_anim 4, 0, 78, 0, -21, 0, 0,
ax_anim 4, 0, 78, 0, -22, 0, 0,
ax_anim 3, 0, 78, 0, -21, 0, 0,
ax_anim 2, 0, 78, 0, -18, 0, 0,
ax_anim 1, 0, 78, 0, -12, 0, 0,
ax_anim 2, 2, 78, 0, 4, 0, 0,
ax_anim_terminator
sUnownEAnims_11_7:
ax_anim 2, 0, 79, 0, 0, 0, 0,
ax_anim 1, 0, 79, 0, -10, 0, 0,
ax_anim 2, 0, 79, 0, -16, 0, 0,
ax_anim 3, 0, 79, 0, -20, 0, 0,
ax_anim 4, 0, 79, 0, -21, 0, 0,
ax_anim 4, 0, 79, 0, -22, 0, 0,
ax_anim 3, 0, 79, 0, -21, 0, 0,
ax_anim 2, 0, 79, 0, -18, 0, 0,
ax_anim 1, 0, 79, 0, -12, 0, 0,
ax_anim 2, 2, 79, 0, 4, 0, 0,
ax_anim_terminator
sUnownEAnims_11_8:
ax_anim 2, 0, 80, 0, 0, 0, 0,
ax_anim 1, 0, 80, 0, -10, 0, 0,
ax_anim 2, 0, 80, 0, -16, 0, 0,
ax_anim 3, 0, 80, 0, -20, 0, 0,
ax_anim 4, 0, 80, 0, -21, 0, 0,
ax_anim 4, 0, 80, 0, -22, 0, 0,
ax_anim 3, 0, 80, 0, -21, 0, 0,
ax_anim 2, 0, 80, 0, -18, 0, 0,
ax_anim 1, 0, 80, 0, -12, 0, 0,
ax_anim 2, 2, 80, 0, 4, 0, 0,
ax_anim_terminator
.align 2
sUnownEAnims_12_1:
ax_anim 2, 0, 81, 1, 0, 1, 0,
ax_anim 2, 0, 81, 0, 0, 0, 0,
ax_anim 2, 0, 81, 1, 0, 1, 0,
ax_anim 2, 0, 81, 0, 0, 0, 0,
ax_anim 2, 0, 81, 1, 0, 1, 0,
ax_anim 2, 2, 81, 0, 0, 0, 0,
ax_anim 2, 0, 81, 1, 0, 1, 0,
ax_anim 2, 0, 81, 0, 0, 0, 0,
ax_anim 2, 0, 81, 1, 0, 1, 0,
ax_anim 2, 1, 81, 0, 0, 0, 0,
ax_anim_terminator
sUnownEAnims_12_2:
ax_anim 2, 0, 82, 1, -1, 1, -1,
ax_anim 2, 0, 82, 0, 0, 0, 0,
ax_anim 2, 0, 82, 1, -1, 1, -1,
ax_anim 2, 0, 82, 0, 0, 0, 0,
ax_anim 2, 0, 82, 1, -1, 1, -1,
ax_anim 2, 2, 82, 0, 0, 0, 0,
ax_anim 2, 0, 82, 1, -1, 1, -1,
ax_anim 2, 0, 82, 0, 0, 0, 0,
ax_anim 2, 0, 82, 1, -1, 1, -1,
ax_anim 2, 1, 82, 0, 0, 0, 0,
ax_anim_terminator
sUnownEAnims_12_3:
ax_anim 2, 0, 83, 0, -1, 0, -1,
ax_anim 2, 0, 83, 0, 0, 0, 0,
ax_anim 2, 0, 83, 0, -1, 0, -1,
ax_anim 2, 0, 83, 0, 0, 0, 0,
ax_anim 2, 0, 83, 0, -1, 0, -1,
ax_anim 2, 2, 83, 0, 0, 0, 0,
ax_anim 2, 0, 83, 0, -1, 0, -1,
ax_anim 2, 0, 83, 0, 0, 0, 0,
ax_anim 2, 0, 83, 0, -1, 0, -1,
ax_anim 2, 1, 83, 0, 0, 0, 0,
ax_anim_terminator
sUnownEAnims_12_4:
ax_anim 2, 0, 84, -1, -1, -1, -1,
ax_anim 2, 0, 84, 0, 0, 0, 0,
ax_anim 2, 0, 84, -1, -1, -1, -1,
ax_anim 2, 0, 84, 0, 0, 0, 0,
ax_anim 2, 0, 84, -1, -1, -1, -1,
ax_anim 2, 2, 84, 0, 0, 0, 0,
ax_anim 2, 0, 84, -1, -1, -1, -1,
ax_anim 2, 0, 84, 0, 0, 0, 0,
ax_anim 2, 0, 84, -1, -1, -1, -1,
ax_anim 2, 1, 84, 0, 0, 0, 0,
ax_anim_terminator
sUnownEAnims_12_5:
ax_anim 2, 0, 85, 1, 0, 1, 0,
ax_anim 2, 0, 85, 0, 0, 0, 0,
ax_anim 2, 0, 85, 1, 0, 1, 0,
ax_anim 2, 0, 85, 0, 0, 0, 0,
ax_anim 2, 0, 85, 1, 0, 1, 0,
ax_anim 2, 2, 85, 0, 0, 0, 0,
ax_anim 2, 0, 85, 1, 0, 1, 0,
ax_anim 2, 0, 85, 0, 0, 0, 0,
ax_anim 2, 0, 85, 1, 0, 1, 0,
ax_anim 2, 1, 85, 0, 0, 0, 0,
ax_anim_terminator
sUnownEAnims_12_6:
ax_anim 2, 0, 86, 1, -1, 1, -1,
ax_anim 2, 0, 86, 0, 0, 0, 0,
ax_anim 2, 0, 86, 1, -1, 1, -1,
ax_anim 2, 0, 86, 0, 0, 0, 0,
ax_anim 2, 0, 86, 1, -1, 1, -1,
ax_anim 2, 2, 86, 0, 0, 0, 0,
ax_anim 2, 0, 86, 1, -1, 1, -1,
ax_anim 2, 0, 86, 0, 0, 0, 0,
ax_anim 2, 0, 86, 1, -1, 1, -1,
ax_anim 2, 1, 86, 0, 0, 0, 0,
ax_anim_terminator
sUnownEAnims_12_7:
ax_anim 2, 0, 87, 0, -1, 0, -1,
ax_anim 2, 0, 87, 0, 0, 0, 0,
ax_anim 2, 0, 87, 0, -1, 0, -1,
ax_anim 2, 0, 87, 0, 0, 0, 0,
ax_anim 2, 0, 87, 0, -1, 0, -1,
ax_anim 2, 2, 87, 0, 0, 0, 0,
ax_anim 2, 0, 87, 0, -1, 0, -1,
ax_anim 2, 0, 87, 0, 0, 0, 0,
ax_anim 2, 0, 87, 0, -1, 0, -1,
ax_anim 2, 1, 87, 0, 0, 0, 0,
ax_anim_terminator
sUnownEAnims_12_8:
ax_anim 2, 0, 88, -1, -1, -1, -1,
ax_anim 2, 0, 88, 0, 0, 0, 0,
ax_anim 2, 0, 88, -1, -1, -1, -1,
ax_anim 2, 0, 88, 0, 0, 0, 0,
ax_anim 2, 0, 88, -1, -1, -1, -1,
ax_anim 2, 2, 88, 0, 0, 0, 0,
ax_anim 2, 0, 88, -1, -1, -1, -1,
ax_anim 2, 0, 88, 0, 0, 0, 0,
ax_anim 2, 0, 88, -1, -1, -1, -1,
ax_anim 2, 1, 88, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sUnownEAnims_13_1:
ax_anim 2, 0, 89, 0, 0, 0, 0,
ax_anim 2, 0, 90, 0, 0, 0, 0,
ax_anim 2, 0, 91, 0, 0, 0, 0,
ax_anim 2, 0, 92, 0, 0, 0, 0,
ax_anim 2, 0, 93, 0, 0, 0, 0,
ax_anim 2, 0, 94, 0, 0, 0, 0,
ax_anim 2, 0, 95, 0, 0, 0, 0,
ax_anim 2, 0, 96, 0, 0, 0, 0,
ax_anim 2, 2, 89, 0, 0, 0, 0,
ax_anim_terminator
sUnownEAnims_13_2:
ax_anim 2, 0, 90, 0, 0, 0, 0,
ax_anim 2, 0, 91, 0, 0, 0, 0,
ax_anim 2, 0, 92, 0, 0, 0, 0,
ax_anim 2, 0, 93, 0, 0, 0, 0,
ax_anim 2, 0, 94, 0, 0, 0, 0,
ax_anim 2, 0, 95, 0, 0, 0, 0,
ax_anim 2, 0, 96, 0, 0, 0, 0,
ax_anim 2, 0, 89, 0, 0, 0, 0,
ax_anim 2, 2, 90, 0, 0, 0, 0,
ax_anim_terminator
sUnownEAnims_13_3:
ax_anim 2, 0, 91, 0, 0, 0, 0,
ax_anim 2, 0, 92, 0, 0, 0, 0,
ax_anim 2, 0, 93, 0, 0, 0, 0,
ax_anim 2, 0, 94, 0, 0, 0, 0,
ax_anim 2, 0, 95, 0, 0, 0, 0,
ax_anim 2, 0, 96, 0, 0, 0, 0,
ax_anim 2, 0, 89, 0, 0, 0, 0,
ax_anim 2, 0, 90, 0, 0, 0, 0,
ax_anim 2, 2, 91, 0, 0, 0, 0,
ax_anim_terminator
sUnownEAnims_13_4:
ax_anim 2, 0, 92, 0, 0, 0, 0,
ax_anim 2, 0, 93, 0, 0, 0, 0,
ax_anim 2, 0, 94, 0, 0, 0, 0,
ax_anim 2, 0, 95, 0, 0, 0, 0,
ax_anim 2, 0, 96, 0, 0, 0, 0,
ax_anim 2, 0, 89, 0, 0, 0, 0,
ax_anim 2, 0, 90, 0, 0, 0, 0,
ax_anim 2, 0, 91, 0, 0, 0, 0,
ax_anim 2, 2, 92, 0, 0, 0, 0,
ax_anim_terminator
sUnownEAnims_13_5:
ax_anim 2, 0, 93, 0, 0, 0, 0,
ax_anim 2, 0, 94, 0, 0, 0, 0,
ax_anim 2, 0, 95, 0, 0, 0, 0,
ax_anim 2, 0, 96, 0, 0, 0, 0,
ax_anim 2, 0, 89, 0, 0, 0, 0,
ax_anim 2, 0, 90, 0, 0, 0, 0,
ax_anim 2, 0, 91, 0, 0, 0, 0,
ax_anim 2, 0, 92, 0, 0, 0, 0,
ax_anim 2, 2, 93, 0, 0, 0, 0,
ax_anim_terminator
sUnownEAnims_13_6:
ax_anim 2, 0, 94, 0, 0, 0, 0,
ax_anim 2, 0, 95, 0, 0, 0, 0,
ax_anim 2, 0, 96, 0, 0, 0, 0,
ax_anim 2, 0, 89, 0, 0, 0, 0,
ax_anim 2, 0, 90, 0, 0, 0, 0,
ax_anim 2, 0, 91, 0, 0, 0, 0,
ax_anim 2, 0, 92, 0, 0, 0, 0,
ax_anim 2, 0, 93, 0, 0, 0, 0,
ax_anim 2, 2, 94, 0, 0, 0, 0,
ax_anim_terminator
sUnownEAnims_13_7:
ax_anim 2, 0, 95, 0, 0, 0, 0,
ax_anim 2, 0, 96, 0, 0, 0, 0,
ax_anim 2, 0, 89, 0, 0, 0, 0,
ax_anim 2, 0, 90, 0, 0, 0, 0,
ax_anim 2, 0, 91, 0, 0, 0, 0,
ax_anim 2, 0, 92, 0, 0, 0, 0,
ax_anim 2, 0, 93, 0, 0, 0, 0,
ax_anim 2, 0, 94, 0, 0, 0, 0,
ax_anim 2, 2, 95, 0, 0, 0, 0,
ax_anim_terminator
sUnownEAnims_13_8:
ax_anim 2, 0, 96, 0, 0, 0, 0,
ax_anim 2, 0, 89, 0, 0, 0, 0,
ax_anim 2, 0, 90, 0, 0, 0, 0,
ax_anim 2, 0, 91, 0, 0, 0, 0,
ax_anim 2, 0, 92, 0, 0, 0, 0,
ax_anim 2, 0, 93, 0, 0, 0, 0,
ax_anim 2, 0, 94, 0, 0, 0, 0,
ax_anim 2, 0, 95, 0, 0, 0, 0,
ax_anim 2, 2, 96, 0, 0, 0, 0,
ax_anim_terminator
sUnownEGfx1:
.incbin "baserom.gba", 0xDAB438, 0x200
sUnownESprites1:
ax_sprite sUnownEGfx1, 0x200
ax_sprite_terminator
sUnownEGfx2:
.incbin "baserom.gba", 0xDAB648, 0x200
sUnownESprites2:
ax_sprite sUnownEGfx2, 0x200
ax_sprite_terminator
sUnownEGfx3:
.incbin "baserom.gba", 0xDAB858, 0x200
sUnownESprites3:
ax_sprite sUnownEGfx3, 0x200
ax_sprite_terminator
sUnownEGfx4:
.incbin "baserom.gba", 0xDABA68, 0x200
sUnownESprites4:
ax_sprite sUnownEGfx4, 0x200
ax_sprite_terminator
sUnownEGfx5:
.incbin "baserom.gba", 0xDABC78, 0x200
sUnownESprites5:
ax_sprite sUnownEGfx5, 0x200
ax_sprite_terminator
sUnownEGfx6:
.incbin "baserom.gba", 0xDABE88, 0x200
sUnownESprites6:
ax_sprite sUnownEGfx6, 0x200
ax_sprite_terminator
sUnownEGfx7:
.incbin "baserom.gba", 0xDAC098, 0x200
sUnownESprites7:
ax_sprite sUnownEGfx7, 0x200
ax_sprite_terminator
sUnownEGfx8:
.incbin "baserom.gba", 0xDAC2A8, 0x200
sUnownESprites8:
ax_sprite sUnownEGfx8, 0x200
ax_sprite_terminator
sUnownEGfx9:
.incbin "baserom.gba", 0xDAC4B8, 0x200
sUnownESprites9:
ax_sprite sUnownEGfx9, 0x200
ax_sprite_terminator
sUnownEGfx10:
.incbin "baserom.gba", 0xDAC6C8, 0x200
sUnownESprites10:
ax_sprite sUnownEGfx10, 0x200
ax_sprite_terminator
sUnownEGfx11:
.incbin "baserom.gba", 0xDAC8D8, 0x200
sUnownESprites11:
ax_sprite sUnownEGfx11, 0x200
ax_sprite_terminator
sUnownEGfx12:
.incbin "baserom.gba", 0xDACAE8, 0x200
sUnownESprites12:
ax_sprite sUnownEGfx12, 0x200
ax_sprite_terminator
sUnownEGfx13:
.incbin "baserom.gba", 0xDACCF8, 0x200
sUnownESprites13:
ax_sprite sUnownEGfx13, 0x200
ax_sprite_terminator
sUnownEGfx14:
.incbin "baserom.gba", 0xDACF08, 0x200
sUnownESprites14:
ax_sprite sUnownEGfx14, 0x200
ax_sprite_terminator
sUnownEGfx15:
.incbin "baserom.gba", 0xDAD118, 0x200
sUnownESprites15:
ax_sprite sUnownEGfx15, 0x200
ax_sprite_terminator
sUnownEGfx16:
.incbin "baserom.gba", 0xDAD328, 0x200
sUnownESprites16:
ax_sprite sUnownEGfx16, 0x200
ax_sprite_terminator
sUnownEGfx17:
.incbin "baserom.gba", 0xDAD538, 0x200
sUnownESprites17:
ax_sprite sUnownEGfx17, 0x200
ax_sprite_terminator
sAxPosesUnownE:
.4byte sUnownEPose1
.4byte sUnownEPose2
.4byte sUnownEPose3
.4byte sUnownEPose4
.4byte sUnownEPose5
.4byte sUnownEPose6
.4byte sUnownEPose7
.4byte sUnownEPose8
.4byte sUnownEPose9
.4byte sUnownEPose10
.4byte sUnownEPose11
.4byte sUnownEPose12
.4byte sUnownEPose13
.4byte sUnownEPose14
.4byte sUnownEPose15
.4byte sUnownEPose16
.4byte sUnownEPose17
.4byte sUnownEPose18
.4byte sUnownEPose19
.4byte sUnownEPose20
.4byte sUnownEPose21
.4byte sUnownEPose22
.4byte sUnownEPose23
.4byte sUnownEPose24
.4byte sUnownEPose25
.4byte sUnownEPose26
.4byte sUnownEPose27
.4byte sUnownEPose28
.4byte sUnownEPose29
.4byte sUnownEPose30
.4byte sUnownEPose31
.4byte sUnownEPose32
.4byte sUnownEPose33
.4byte sUnownEPose34
.4byte sUnownEPose35
.4byte sUnownEPose36
.4byte sUnownEPose37
.4byte sUnownEPose38
.4byte sUnownEPose39
.4byte sUnownEPose40
.4byte sUnownEPose41
.4byte sUnownEPose42
.4byte sUnownEPose43
.4byte sUnownEPose44
.4byte sUnownEPose45
.4byte sUnownEPose46
.4byte sUnownEPose47
.4byte sUnownEPose48
.4byte sUnownEPose49
.4byte sUnownEPose50
.4byte sUnownEPose51
.4byte sUnownEPose52
.4byte sUnownEPose53
.4byte sUnownEPose54
.4byte sUnownEPose55
.4byte sUnownEPose56
.4byte sUnownEPose57
.4byte sUnownEPose58
.4byte sUnownEPose59
.4byte sUnownEPose60
.4byte sUnownEPose61
.4byte sUnownEPose62
.4byte sUnownEPose63
.4byte sUnownEPose64
.4byte sUnownEPose65
.4byte sUnownEPose66
.4byte sUnownEPose67
.4byte sUnownEPose68
.4byte sUnownEPose69
.4byte sUnownEPose70
.4byte sUnownEPose71
.4byte sUnownEPose72
.4byte sUnownEPose73
.4byte sUnownEPose74
.4byte sUnownEPose75
.4byte sUnownEPose76
.4byte sUnownEPose77
.4byte sUnownEPose78
.4byte sUnownEPose79
.4byte sUnownEPose80
.4byte sUnownEPose81
.4byte sUnownEPose82
.4byte sUnownEPose83
.4byte sUnownEPose84
.4byte sUnownEPose85
.4byte sUnownEPose86
.4byte sUnownEPose87
.4byte sUnownEPose88
.4byte sUnownEPose89
.4byte sUnownEPose90
.4byte sUnownEPose91
.4byte sUnownEPose92
.4byte sUnownEPose93
.4byte sUnownEPose94
.4byte sUnownEPose95
.4byte sUnownEPose96
.4byte sUnownEPose97
sAxPositionsUnownE:
.2byte   -1,  -12, 	  -6,  -12, 	   4,  -12, 	  -1,  -11
.2byte    1,  -12, 	  -5,  -11, 	   3,  -13, 	  -1,  -11
.2byte    2,  -12, 	  -3,  -10, 	   1,  -13, 	  -1,  -12
.2byte    0,  -14, 	   3,  -11, 	  -5,  -13, 	  -1,  -12
.2byte   -1,  -15, 	   4,  -12, 	  -6,  -12, 	  -1,  -12
.2byte   -2,  -13, 	   2,  -13, 	  -5,  -11, 	  -1,  -11
.2byte   -4,  -12, 	  -3,  -13, 	   2,  -10, 	  -1,  -11
.2byte   -3,  -12, 	  -5,  -13, 	   3,  -11, 	  -1,  -11
.2byte   -1,  -12, 	  -6,  -12, 	   4,  -12, 	  -1,  -11
.2byte    1,  -12, 	  -5,  -11, 	   3,  -13, 	  -1,  -11
.2byte    2,  -12, 	  -3,  -10, 	   1,  -13, 	  -1,  -12
.2byte    0,  -14, 	   3,  -11, 	  -5,  -13, 	  -1,  -12
.2byte   -1,  -15, 	   4,  -12, 	  -6,  -12, 	  -1,  -12
.2byte   -2,  -13, 	   2,  -13, 	  -5,  -11, 	  -1,  -11
.2byte   -4,  -12, 	  -3,  -13, 	   2,  -10, 	  -1,  -11
.2byte   -3,  -12, 	  -5,  -13, 	   3,  -11, 	  -1,  -11
.2byte   -1,  -12, 	  -6,  -12, 	   4,  -12, 	  -1,  -11
.2byte    1,  -12, 	  -5,  -11, 	   3,  -13, 	  -1,  -11
.2byte    2,  -12, 	  -3,  -10, 	   1,  -13, 	  -1,  -12
.2byte    0,  -14, 	   3,  -11, 	  -5,  -13, 	  -1,  -12
.2byte   -1,  -15, 	   4,  -12, 	  -6,  -12, 	  -1,  -12
.2byte   -2,  -13, 	   2,  -13, 	  -5,  -11, 	  -1,  -11
.2byte   -4,  -12, 	  -3,  -13, 	   2,  -10, 	  -1,  -11
.2byte   -3,  -12, 	  -5,  -13, 	   3,  -11, 	  -1,  -11
.2byte   -1,  -12, 	  -6,  -12, 	   4,  -12, 	  -1,  -11
.2byte    1,  -12, 	  -5,  -11, 	   3,  -13, 	  -1,  -11
.2byte    2,  -12, 	  -3,  -10, 	   1,  -13, 	  -1,  -12
.2byte    0,  -14, 	   3,  -11, 	  -5,  -13, 	  -1,  -12
.2byte   -1,  -15, 	   4,  -12, 	  -6,  -12, 	  -1,  -12
.2byte   -2,  -13, 	   2,  -13, 	  -5,  -11, 	  -1,  -11
.2byte   -4,  -12, 	  -3,  -13, 	   2,  -10, 	  -1,  -11
.2byte   -3,  -12, 	  -5,  -13, 	   3,  -11, 	  -1,  -11
.2byte   -1,  -12, 	  -6,  -12, 	   4,  -12, 	  -1,  -11
.2byte    1,  -12, 	  -5,  -11, 	   3,  -13, 	  -1,  -11
.2byte    2,  -12, 	  -3,  -10, 	   1,  -13, 	  -1,  -12
.2byte    0,  -14, 	   3,  -11, 	  -5,  -13, 	  -1,  -12
.2byte   -1,  -15, 	   4,  -12, 	  -6,  -12, 	  -1,  -12
.2byte   -2,  -13, 	   2,  -13, 	  -5,  -11, 	  -1,  -11
.2byte   -4,  -12, 	  -3,  -13, 	   2,  -10, 	  -1,  -11
.2byte   -3,  -12, 	  -5,  -13, 	   3,  -11, 	  -1,  -11
.2byte   -2,  -12, 	  -7,  -12, 	   3,  -12, 	  -2,  -11
.2byte   -1,  -12, 	  -6,  -12, 	   4,  -12, 	  -1,  -11
.2byte    1,  -13, 	  -5,  -11, 	   3,  -13, 	  -1,  -11
.2byte    2,  -13, 	  -4,  -10, 	   1,  -11, 	  -1,  -12
.2byte    0,  -14, 	   3,  -11, 	  -5,  -13, 	  -1,  -12
.2byte   -1,  -14, 	   4,  -11, 	  -6,  -11, 	  -1,  -11
.2byte   -2,  -13, 	   3,  -13, 	  -5,  -11, 	   0,  -11
.2byte   -4,  -13, 	  -2,  -14, 	   1,  -10, 	  -1,  -11
.2byte   -3,  -13, 	  -5,  -13, 	   2,  -11, 	   0,  -12
.2byte   -1,  -12, 	  -6,  -12, 	   4,  -12, 	  -1,  -11
.2byte    1,  -12, 	  -5,  -11, 	   3,  -13, 	  -1,  -11
.2byte    2,  -12, 	  -3,  -10, 	   1,  -13, 	  -1,  -12
.2byte    0,  -14, 	   3,  -11, 	  -5,  -13, 	  -1,  -12
.2byte   -1,  -15, 	   4,  -12, 	  -6,  -12, 	  -1,  -12
.2byte   -2,  -13, 	   2,  -13, 	  -5,  -11, 	  -1,  -11
.2byte   -4,  -12, 	  -3,  -13, 	   2,  -10, 	  -1,  -11
.2byte   -3,  -12, 	  -5,  -13, 	   3,  -11, 	  -1,  -11
.2byte   -1,  -12, 	  -6,  -12, 	   4,  -12, 	  -1,  -11
.2byte    1,  -12, 	  -5,  -11, 	   3,  -13, 	  -1,  -11
.2byte    2,  -12, 	  -3,  -10, 	   1,  -13, 	  -1,  -12
.2byte    0,  -14, 	   3,  -11, 	  -5,  -13, 	  -1,  -12
.2byte   -1,  -15, 	   4,  -12, 	  -6,  -12, 	  -1,  -12
.2byte   -2,  -13, 	   2,  -13, 	  -5,  -11, 	  -1,  -11
.2byte   -4,  -12, 	  -3,  -13, 	   2,  -10, 	  -1,  -11
.2byte   -3,  -12, 	  -5,  -13, 	   3,  -11, 	  -1,  -11
.2byte   -1,  -12, 	  -6,  -12, 	   4,  -12, 	  -1,  -11
.2byte    1,  -12, 	  -5,  -11, 	   3,  -13, 	  -1,  -11
.2byte    2,  -12, 	  -3,  -10, 	   1,  -13, 	  -1,  -12
.2byte    0,  -14, 	   3,  -11, 	  -5,  -13, 	  -1,  -12
.2byte   -1,  -15, 	   4,  -12, 	  -6,  -12, 	  -1,  -12
.2byte   -2,  -13, 	   2,  -13, 	  -5,  -11, 	  -1,  -11
.2byte   -4,  -12, 	  -3,  -13, 	   2,  -10, 	  -1,  -11
.2byte   -3,  -12, 	  -5,  -13, 	   3,  -11, 	  -1,  -11
.2byte   -1,  -12, 	  -6,  -12, 	   4,  -12, 	  -1,  -11
.2byte    1,  -12, 	  -5,  -11, 	   3,  -13, 	  -1,  -11
.2byte    2,  -12, 	  -3,  -10, 	   1,  -13, 	  -1,  -12
.2byte    0,  -14, 	   3,  -11, 	  -5,  -13, 	  -1,  -12
.2byte   -1,  -15, 	   4,  -12, 	  -6,  -12, 	  -1,  -12
.2byte   -2,  -13, 	   2,  -13, 	  -5,  -11, 	  -1,  -11
.2byte   -4,  -12, 	  -3,  -13, 	   2,  -10, 	  -1,  -11
.2byte   -3,  -12, 	  -5,  -13, 	   3,  -11, 	  -1,  -11
.2byte   -1,  -12, 	  -6,  -12, 	   4,  -12, 	  -1,  -11
.2byte    1,  -12, 	  -5,  -11, 	   3,  -13, 	  -1,  -11
.2byte    2,  -12, 	  -3,  -10, 	   1,  -13, 	  -1,  -12
.2byte    0,  -14, 	   3,  -11, 	  -5,  -13, 	  -1,  -12
.2byte   -1,  -15, 	   4,  -12, 	  -6,  -12, 	  -1,  -12
.2byte   -2,  -13, 	   2,  -13, 	  -5,  -11, 	  -1,  -11
.2byte   -4,  -12, 	  -3,  -13, 	   2,  -10, 	  -1,  -11
.2byte   -3,  -12, 	  -5,  -13, 	   3,  -11, 	  -1,  -11
.2byte   -1,  -12, 	  -6,  -12, 	   4,  -12, 	  -1,  -11
.2byte    1,  -12, 	  -5,  -11, 	   3,  -13, 	  -1,  -11
.2byte    2,  -12, 	  -3,  -10, 	   1,  -13, 	  -1,  -12
.2byte    0,  -14, 	   3,  -11, 	  -5,  -13, 	  -1,  -12
.2byte   -1,  -15, 	   4,  -12, 	  -6,  -12, 	  -1,  -12
.2byte   -2,  -13, 	   2,  -13, 	  -5,  -11, 	  -1,  -11
.2byte   -4,  -12, 	  -3,  -13, 	   2,  -10, 	  -1,  -11
.2byte   -3,  -12, 	  -5,  -13, 	   3,  -11, 	  -1,  -11
sUnownEAnimTable1:
.4byte sUnownEAnims_1_1
.4byte sUnownEAnims_1_2
.4byte sUnownEAnims_1_3
.4byte sUnownEAnims_1_4
.4byte sUnownEAnims_1_5
.4byte sUnownEAnims_1_6
.4byte sUnownEAnims_1_7
.4byte sUnownEAnims_1_8
sUnownEAnimTable2:
.4byte sUnownEAnims_2_1
.4byte sUnownEAnims_2_2
.4byte sUnownEAnims_2_3
.4byte sUnownEAnims_2_4
.4byte sUnownEAnims_2_5
.4byte sUnownEAnims_2_6
.4byte sUnownEAnims_2_7
.4byte sUnownEAnims_2_8
sUnownEAnimTable3:
.4byte sUnownEAnims_3_1
.4byte sUnownEAnims_3_2
.4byte sUnownEAnims_3_3
.4byte sUnownEAnims_3_4
.4byte sUnownEAnims_3_5
.4byte sUnownEAnims_3_6
.4byte sUnownEAnims_3_7
.4byte sUnownEAnims_3_8
sUnownEAnimTable4:
.4byte sUnownEAnims_4_1
.4byte sUnownEAnims_4_2
.4byte sUnownEAnims_4_3
.4byte sUnownEAnims_4_4
.4byte sUnownEAnims_4_5
.4byte sUnownEAnims_4_6
.4byte sUnownEAnims_4_7
.4byte sUnownEAnims_4_8
sUnownEAnimTable5:
.4byte sUnownEAnims_5_1
.4byte sUnownEAnims_5_2
.4byte sUnownEAnims_5_3
.4byte sUnownEAnims_5_4
.4byte sUnownEAnims_5_5
.4byte sUnownEAnims_5_6
.4byte sUnownEAnims_5_7
.4byte sUnownEAnims_5_8
sUnownEAnimTable6:
.4byte sUnownEAnims_6_1
.4byte sUnownEAnims_6_1
.4byte sUnownEAnims_6_1
.4byte sUnownEAnims_6_1
.4byte sUnownEAnims_6_1
.4byte sUnownEAnims_6_1
.4byte sUnownEAnims_6_1
.4byte sUnownEAnims_6_1
sUnownEAnimTable7:
.4byte sUnownEAnims_7_1
.4byte sUnownEAnims_7_2
.4byte sUnownEAnims_7_3
.4byte sUnownEAnims_7_4
.4byte sUnownEAnims_7_5
.4byte sUnownEAnims_7_6
.4byte sUnownEAnims_7_7
.4byte sUnownEAnims_7_8
sUnownEAnimTable8:
.4byte sUnownEAnims_8_1
.4byte sUnownEAnims_8_2
.4byte sUnownEAnims_8_3
.4byte sUnownEAnims_8_4
.4byte sUnownEAnims_8_5
.4byte sUnownEAnims_8_6
.4byte sUnownEAnims_8_7
.4byte sUnownEAnims_8_8
sUnownEAnimTable9:
.4byte sUnownEAnims_9_1
.4byte sUnownEAnims_9_2
.4byte sUnownEAnims_9_3
.4byte sUnownEAnims_9_4
.4byte sUnownEAnims_9_5
.4byte sUnownEAnims_9_6
.4byte sUnownEAnims_9_7
.4byte sUnownEAnims_9_8
sUnownEAnimTable10:
.4byte sUnownEAnims_10_1
.4byte sUnownEAnims_10_2
.4byte sUnownEAnims_10_3
.4byte sUnownEAnims_10_4
.4byte sUnownEAnims_10_5
.4byte sUnownEAnims_10_6
.4byte sUnownEAnims_10_7
.4byte sUnownEAnims_10_8
sUnownEAnimTable11:
.4byte sUnownEAnims_11_1
.4byte sUnownEAnims_11_2
.4byte sUnownEAnims_11_3
.4byte sUnownEAnims_11_4
.4byte sUnownEAnims_11_5
.4byte sUnownEAnims_11_6
.4byte sUnownEAnims_11_7
.4byte sUnownEAnims_11_8
sUnownEAnimTable12:
.4byte sUnownEAnims_12_1
.4byte sUnownEAnims_12_2
.4byte sUnownEAnims_12_3
.4byte sUnownEAnims_12_4
.4byte sUnownEAnims_12_5
.4byte sUnownEAnims_12_6
.4byte sUnownEAnims_12_7
.4byte sUnownEAnims_12_8
sUnownEAnimTable13:
.4byte sUnownEAnims_13_1
.4byte sUnownEAnims_13_2
.4byte sUnownEAnims_13_3
.4byte sUnownEAnims_13_4
.4byte sUnownEAnims_13_5
.4byte sUnownEAnims_13_6
.4byte sUnownEAnims_13_7
.4byte sUnownEAnims_13_8
sAxAnimationsUnownE:
.4byte sUnownEAnimTable1
.4byte sUnownEAnimTable2
.4byte sUnownEAnimTable3
.4byte sUnownEAnimTable4
.4byte sUnownEAnimTable5
.4byte sUnownEAnimTable6
.4byte sUnownEAnimTable7
.4byte sUnownEAnimTable8
.4byte sUnownEAnimTable9
.4byte sUnownEAnimTable10
.4byte sUnownEAnimTable11
.4byte sUnownEAnimTable12
.4byte sUnownEAnimTable13
sAxSpritesUnownE:
.4byte sUnownESprites1
.4byte sUnownESprites2
.4byte sUnownESprites3
.4byte sUnownESprites4
.4byte sUnownESprites5
.4byte sUnownESprites6
.4byte sUnownESprites7
.4byte sUnownESprites8
.4byte sUnownESprites9
.4byte sUnownESprites10
.4byte sUnownESprites11
.4byte sUnownESprites12
.4byte sUnownESprites13
.4byte sUnownESprites14
.4byte sUnownESprites15
.4byte sUnownESprites16
.4byte sUnownESprites17
sAxMainUnownE:
ax_main sAxPosesUnownE, sAxAnimationsUnownE, 13, sAxSpritesUnownE, sAxPositionsUnownE
