.global gAxVibrava
gAxVibrava:
ax_siro sAxMainVibrava
sVibravaPose1:
ax_pose 0, 0x01ec, 0x80f3, 0xac00
ax_pose_terminator
sVibravaPose2:
ax_pose 1, 0x01ec, 0x80f0, 0xac00
ax_pose_terminator
sVibravaPose3:
ax_pose 2, 0x01ec, 0x80f3, 0xac00
ax_pose_terminator
sVibravaPose4:
ax_pose 3, 0x01ec, 0x90ef, 0xac00
ax_pose_terminator
sVibravaPose5:
ax_pose 4, 0x01ec, 0x90ef, 0xac00
ax_pose_terminator
sVibravaPose6:
ax_pose 5, 0x01e8, 0x90ef, 0xac00
ax_pose_terminator
sVibravaPose7:
ax_pose 6, 0x01ec, 0x90f2, 0xac00
ax_pose_terminator
sVibravaPose8:
ax_pose 7, 0x01ec, 0x90f2, 0xac00
ax_pose_terminator
sVibravaPose9:
ax_pose 8, 0x01e8, 0x90f2, 0xac00
ax_pose_terminator
sVibravaPose10:
ax_pose 9, 0x01e8, 0x90ef, 0xac00
ax_pose_terminator
sVibravaPose11:
ax_pose 10, 0x01e8, 0x90ef, 0xac00
ax_pose_terminator
sVibravaPose12:
ax_pose 11, 0x01ea, 0x90ef, 0xac00
ax_pose_terminator
sVibravaPose13:
ax_pose 12, 0x01ec, 0x80f0, 0xac00
ax_pose_terminator
sVibravaPose14:
ax_pose 13, 0x01e8, 0x80f0, 0xac00
ax_pose_terminator
sVibravaPose15:
ax_pose 14, 0x01e8, 0x80f0, 0xac00
ax_pose_terminator
sVibravaPose16:
ax_pose 9, 0x01e8, 0x80f0, 0xac00
ax_pose_terminator
sVibravaPose17:
ax_pose 10, 0x01e8, 0x80f0, 0xac00
ax_pose_terminator
sVibravaPose18:
ax_pose 11, 0x01ea, 0x80f0, 0xac00
ax_pose_terminator
sVibravaPose19:
ax_pose 6, 0x01ec, 0x80ed, 0xac00
ax_pose_terminator
sVibravaPose20:
ax_pose 7, 0x01ec, 0x80ed, 0xac00
ax_pose_terminator
sVibravaPose21:
ax_pose 8, 0x01e8, 0x80ed, 0xac00
ax_pose_terminator
sVibravaPose22:
ax_pose 3, 0x01ec, 0x80f0, 0xac00
ax_pose_terminator
sVibravaPose23:
ax_pose 4, 0x01ec, 0x80f0, 0xac00
ax_pose_terminator
sVibravaPose24:
ax_pose 5, 0x01e8, 0x80f0, 0xac00
ax_pose_terminator
sVibravaPose25:
ax_pose 0, 0x01ec, 0x80f3, 0xac00
ax_pose_terminator
sVibravaPose26:
ax_pose 3, 0x01ec, 0x80f0, 0xac00
ax_pose_terminator
sVibravaPose27:
ax_pose 6, 0x01ec, 0x80ed, 0xac00
ax_pose_terminator
sVibravaPose28:
ax_pose 9, 0x01e8, 0x80f0, 0xac00
ax_pose_terminator
sVibravaPose29:
ax_pose 12, 0x01ec, 0x80f0, 0xac00
ax_pose_terminator
sVibravaPose30:
ax_pose 9, 0x01e8, 0x90ef, 0xac00
ax_pose_terminator
sVibravaPose31:
ax_pose 6, 0x01ec, 0x90f2, 0xac00
ax_pose_terminator
sVibravaPose32:
ax_pose 3, 0x01ec, 0x90ef, 0xac00
ax_pose_terminator
sVibravaPose33:
ax_pose 0, 0x01ec, 0x80f3, 0xac00
ax_pose_terminator
sVibravaPose34:
ax_pose 1, 0x01ec, 0x80f0, 0xac00
ax_pose_terminator
sVibravaPose35:
ax_pose 2, 0x01ec, 0x80f3, 0xac00
ax_pose_terminator
sVibravaPose36:
ax_pose 3, 0x01ec, 0x90ef, 0xac00
ax_pose_terminator
sVibravaPose37:
ax_pose 4, 0x01ec, 0x90ef, 0xac00
ax_pose_terminator
sVibravaPose38:
ax_pose 5, 0x01e8, 0x90ef, 0xac00
ax_pose_terminator
sVibravaPose39:
ax_pose 6, 0x01ec, 0x90f2, 0xac00
ax_pose_terminator
sVibravaPose40:
ax_pose 7, 0x01ec, 0x90f2, 0xac00
ax_pose_terminator
sVibravaPose41:
ax_pose 8, 0x01e8, 0x90f2, 0xac00
ax_pose_terminator
sVibravaPose42:
ax_pose 9, 0x01e8, 0x90ef, 0xac00
ax_pose_terminator
sVibravaPose43:
ax_pose 10, 0x01e8, 0x90ef, 0xac00
ax_pose_terminator
sVibravaPose44:
ax_pose 11, 0x01ea, 0x90ef, 0xac00
ax_pose_terminator
sVibravaPose45:
ax_pose 12, 0x01ec, 0x80f0, 0xac00
ax_pose_terminator
sVibravaPose46:
ax_pose 13, 0x01e8, 0x80f0, 0xac00
ax_pose_terminator
sVibravaPose47:
ax_pose 14, 0x01e8, 0x80f0, 0xac00
ax_pose_terminator
sVibravaPose48:
ax_pose 9, 0x01e8, 0x80f0, 0xac00
ax_pose_terminator
sVibravaPose49:
ax_pose 10, 0x01e8, 0x80f0, 0xac00
ax_pose_terminator
sVibravaPose50:
ax_pose 11, 0x01ea, 0x80f0, 0xac00
ax_pose_terminator
sVibravaPose51:
ax_pose 6, 0x01ec, 0x80ed, 0xac00
ax_pose_terminator
sVibravaPose52:
ax_pose 7, 0x01ec, 0x80ed, 0xac00
ax_pose_terminator
sVibravaPose53:
ax_pose 8, 0x01e8, 0x80ed, 0xac00
ax_pose_terminator
sVibravaPose54:
ax_pose 3, 0x01ec, 0x80f0, 0xac00
ax_pose_terminator
sVibravaPose55:
ax_pose 4, 0x01ec, 0x80f0, 0xac00
ax_pose_terminator
sVibravaPose56:
ax_pose 5, 0x01e8, 0x80f0, 0xac00
ax_pose_terminator
sVibravaPose57:
ax_pose 0, 0x01ec, 0x80f3, 0xac00
ax_pose_terminator
sVibravaPose58:
ax_pose 3, 0x01ec, 0x80f0, 0xac00
ax_pose_terminator
sVibravaPose59:
ax_pose 6, 0x01ec, 0x80ed, 0xac00
ax_pose_terminator
sVibravaPose60:
ax_pose 9, 0x01e8, 0x80f0, 0xac00
ax_pose_terminator
sVibravaPose61:
ax_pose 12, 0x01ec, 0x80f0, 0xac00
ax_pose_terminator
sVibravaPose62:
ax_pose 9, 0x01e8, 0x90ef, 0xac00
ax_pose_terminator
sVibravaPose63:
ax_pose 6, 0x01ec, 0x90f2, 0xac00
ax_pose_terminator
sVibravaPose64:
ax_pose 3, 0x01ec, 0x90ef, 0xac00
ax_pose_terminator
sVibravaPose65:
ax_pose 0, 0x01ec, 0x80f3, 0xac00
ax_pose_terminator
sVibravaPose66:
ax_pose 1, 0x01ec, 0x80f0, 0xac00
ax_pose_terminator
sVibravaPose67:
ax_pose 2, 0x01ec, 0x80f3, 0xac00
ax_pose_terminator
sVibravaPose68:
ax_pose 3, 0x01ec, 0x90ef, 0xac00
ax_pose_terminator
sVibravaPose69:
ax_pose 4, 0x01ec, 0x90ef, 0xac00
ax_pose_terminator
sVibravaPose70:
ax_pose 5, 0x01e8, 0x90ef, 0xac00
ax_pose_terminator
sVibravaPose71:
ax_pose 6, 0x01ec, 0x90f2, 0xac00
ax_pose_terminator
sVibravaPose72:
ax_pose 7, 0x01ec, 0x90f2, 0xac00
ax_pose_terminator
sVibravaPose73:
ax_pose 8, 0x01e8, 0x90f2, 0xac00
ax_pose_terminator
sVibravaPose74:
ax_pose 9, 0x01e8, 0x90ef, 0xac00
ax_pose_terminator
sVibravaPose75:
ax_pose 10, 0x01e8, 0x90ef, 0xac00
ax_pose_terminator
sVibravaPose76:
ax_pose 11, 0x01ea, 0x90ef, 0xac00
ax_pose_terminator
sVibravaPose77:
ax_pose 12, 0x01ec, 0x80f0, 0xac00
ax_pose_terminator
sVibravaPose78:
ax_pose 13, 0x01e8, 0x80f0, 0xac00
ax_pose_terminator
sVibravaPose79:
ax_pose 14, 0x01e8, 0x80f0, 0xac00
ax_pose_terminator
sVibravaPose80:
ax_pose 9, 0x01e8, 0x80f0, 0xac00
ax_pose_terminator
sVibravaPose81:
ax_pose 10, 0x01e8, 0x80f0, 0xac00
ax_pose_terminator
sVibravaPose82:
ax_pose 11, 0x01ea, 0x80f0, 0xac00
ax_pose_terminator
sVibravaPose83:
ax_pose 6, 0x01ec, 0x80ed, 0xac00
ax_pose_terminator
sVibravaPose84:
ax_pose 7, 0x01ec, 0x80ed, 0xac00
ax_pose_terminator
sVibravaPose85:
ax_pose 8, 0x01e8, 0x80ed, 0xac00
ax_pose_terminator
sVibravaPose86:
ax_pose 3, 0x01ec, 0x80f0, 0xac00
ax_pose_terminator
sVibravaPose87:
ax_pose 4, 0x01ec, 0x80f0, 0xac00
ax_pose_terminator
sVibravaPose88:
ax_pose 5, 0x01e8, 0x80f0, 0xac00
ax_pose_terminator
sVibravaPose89:
ax_pose 0, 0x01ec, 0x80f3, 0xac00
ax_pose_terminator
sVibravaPose90:
ax_pose 3, 0x01ec, 0x80f0, 0xac00
ax_pose_terminator
sVibravaPose91:
ax_pose 6, 0x01ec, 0x80ed, 0xac00
ax_pose_terminator
sVibravaPose92:
ax_pose 9, 0x01e8, 0x80f0, 0xac00
ax_pose_terminator
sVibravaPose93:
ax_pose 12, 0x01ec, 0x80f0, 0xac00
ax_pose_terminator
sVibravaPose94:
ax_pose 9, 0x01e8, 0x90ef, 0xac00
ax_pose_terminator
sVibravaPose95:
ax_pose 6, 0x01ec, 0x90f2, 0xac00
ax_pose_terminator
sVibravaPose96:
ax_pose 3, 0x01ec, 0x90ef, 0xac00
ax_pose_terminator
sVibravaPose97:
ax_pose 0, 0x01ec, 0x80f3, 0xac00
ax_pose_terminator
sVibravaPose98:
ax_pose 15, 0x01ec, 0x80f2, 0xac00
ax_pose_terminator
sVibravaPose99:
ax_pose 3, 0x01ec, 0x90ef, 0xac00
ax_pose_terminator
sVibravaPose100:
ax_pose 16, 0x01eb, 0x90ee, 0xac00
ax_pose_terminator
sVibravaPose101:
ax_pose 6, 0x01ec, 0x90f2, 0xac00
ax_pose_terminator
sVibravaPose102:
ax_pose 17, 0x01eb, 0x90f0, 0xac00
ax_pose_terminator
sVibravaPose103:
ax_pose 9, 0x01e8, 0x90ef, 0xac00
ax_pose_terminator
sVibravaPose104:
ax_pose 18, 0x01e8, 0x90ef, 0xac00
ax_pose_terminator
sVibravaPose105:
ax_pose 12, 0x01ec, 0x80f0, 0xac00
ax_pose_terminator
sVibravaPose106:
ax_pose 19, 0x01ec, 0x80f0, 0xac00
ax_pose_terminator
sVibravaPose107:
ax_pose 9, 0x01e8, 0x80f0, 0xac00
ax_pose_terminator
sVibravaPose108:
ax_pose 18, 0x01e8, 0x80f0, 0xac00
ax_pose_terminator
sVibravaPose109:
ax_pose 6, 0x01ec, 0x80ed, 0xac00
ax_pose_terminator
sVibravaPose110:
ax_pose 17, 0x01eb, 0x80ef, 0xac00
ax_pose_terminator
sVibravaPose111:
ax_pose 3, 0x01ec, 0x80f0, 0xac00
ax_pose_terminator
sVibravaPose112:
ax_pose 16, 0x01eb, 0x80f1, 0xac00
ax_pose_terminator
sVibravaPose113:
ax_pose 0, 0x01ec, 0x80f3, 0xac00
ax_pose_terminator
sVibravaPose114:
ax_pose 3, 0x01ec, 0x80f0, 0xac00
ax_pose_terminator
sVibravaPose115:
ax_pose 6, 0x01ec, 0x80ed, 0xac00
ax_pose_terminator
sVibravaPose116:
ax_pose 9, 0x01e8, 0x80f0, 0xac00
ax_pose_terminator
sVibravaPose117:
ax_pose 12, 0x01ec, 0x80f0, 0xac00
ax_pose_terminator
sVibravaPose118:
ax_pose 9, 0x01e8, 0x90ef, 0xac00
ax_pose_terminator
sVibravaPose119:
ax_pose 6, 0x01ec, 0x90f2, 0xac00
ax_pose_terminator
sVibravaPose120:
ax_pose 3, 0x01ec, 0x90ef, 0xac00
ax_pose_terminator
sVibravaPose121:
ax_pose 20, 0x01ec, 0x80f3, 0xac00
ax_pose_terminator
sVibravaPose122:
ax_pose 21, 0x01ec, 0x80f3, 0xac00
ax_pose_terminator
sVibravaPose123:
ax_pose 22, 0x81e5, 0x4103, 0xac00
ax_pose 23, 0x01dd, 0x00f8, 0xac04
ax_pose 24, 0x01dd, 0x0103, 0xac05
ax_pose 25, 0x01e5, 0x010b, 0xac06
ax_pose 26, 0x81e5, 0x80f3, 0xac07
ax_pose_terminator
sVibravaPose124:
ax_pose 27, 0x01e5, 0x90f2, 0xac00
ax_pose_terminator
sVibravaPose125:
ax_pose 28, 0x01e6, 0x90ef, 0xac00
ax_pose_terminator
sVibravaPose126:
ax_pose 29, 0x01e7, 0x90ee, 0xac00
ax_pose_terminator
sVibravaPose127:
ax_pose 30, 0x01e8, 0x80f0, 0xac00
ax_pose_terminator
sVibravaPose128:
ax_pose 29, 0x01e7, 0x80f2, 0xac00
ax_pose_terminator
sVibravaPose129:
ax_pose 28, 0x01e6, 0x80f3, 0xac00
ax_pose_terminator
sVibravaPose130:
ax_pose 27, 0x01e5, 0x80f2, 0xac00
ax_pose_terminator
sVibravaPose131:
ax_pose 0, 0x01ec, 0x80f3, 0xac00
ax_pose_terminator
sVibravaPose132:
ax_pose 1, 0x01ec, 0x80f0, 0xac00
ax_pose_terminator
sVibravaPose133:
ax_pose 2, 0x01ec, 0x80f3, 0xac00
ax_pose_terminator
sVibravaPose134:
ax_pose 3, 0x01ec, 0x90ef, 0xac00
ax_pose_terminator
sVibravaPose135:
ax_pose 4, 0x01ec, 0x90ef, 0xac00
ax_pose_terminator
sVibravaPose136:
ax_pose 5, 0x01e8, 0x90ef, 0xac00
ax_pose_terminator
sVibravaPose137:
ax_pose 6, 0x01ec, 0x90f2, 0xac00
ax_pose_terminator
sVibravaPose138:
ax_pose 7, 0x01ec, 0x90f2, 0xac00
ax_pose_terminator
sVibravaPose139:
ax_pose 8, 0x01e8, 0x90f2, 0xac00
ax_pose_terminator
sVibravaPose140:
ax_pose 9, 0x01e8, 0x90ef, 0xac00
ax_pose_terminator
sVibravaPose141:
ax_pose 10, 0x01e8, 0x90ef, 0xac00
ax_pose_terminator
sVibravaPose142:
ax_pose 11, 0x01ea, 0x90ef, 0xac00
ax_pose_terminator
sVibravaPose143:
ax_pose 12, 0x01ec, 0x80f0, 0xac00
ax_pose_terminator
sVibravaPose144:
ax_pose 13, 0x01e8, 0x80f0, 0xac00
ax_pose_terminator
sVibravaPose145:
ax_pose 14, 0x01e8, 0x80f0, 0xac00
ax_pose_terminator
sVibravaPose146:
ax_pose 9, 0x01e8, 0x80f0, 0xac00
ax_pose_terminator
sVibravaPose147:
ax_pose 10, 0x01e8, 0x80f0, 0xac00
ax_pose_terminator
sVibravaPose148:
ax_pose 11, 0x01ea, 0x80f0, 0xac00
ax_pose_terminator
sVibravaPose149:
ax_pose 6, 0x01ec, 0x80ed, 0xac00
ax_pose_terminator
sVibravaPose150:
ax_pose 7, 0x01ec, 0x80ed, 0xac00
ax_pose_terminator
sVibravaPose151:
ax_pose 8, 0x01e8, 0x80ed, 0xac00
ax_pose_terminator
sVibravaPose152:
ax_pose 3, 0x01ec, 0x80f0, 0xac00
ax_pose_terminator
sVibravaPose153:
ax_pose 4, 0x01ec, 0x80f0, 0xac00
ax_pose_terminator
sVibravaPose154:
ax_pose 5, 0x01e8, 0x80f0, 0xac00
ax_pose_terminator
sVibravaPose155:
ax_pose 0, 0x01ec, 0x80f3, 0xac00
ax_pose_terminator
sVibravaPose156:
ax_pose 3, 0x01ec, 0x80f0, 0xac00
ax_pose_terminator
sVibravaPose157:
ax_pose 6, 0x01ec, 0x80ed, 0xac00
ax_pose_terminator
sVibravaPose158:
ax_pose 9, 0x01e8, 0x80f0, 0xac00
ax_pose_terminator
sVibravaPose159:
ax_pose 12, 0x01ec, 0x80f0, 0xac00
ax_pose_terminator
sVibravaPose160:
ax_pose 9, 0x01e8, 0x90ef, 0xac00
ax_pose_terminator
sVibravaPose161:
ax_pose 6, 0x01ec, 0x90f2, 0xac00
ax_pose_terminator
sVibravaPose162:
ax_pose 3, 0x01ec, 0x90ef, 0xac00
ax_pose_terminator
sVibravaPose163:
ax_pose 1, 0x01ec, 0x80f0, 0xac00
ax_pose_terminator
sVibravaPose164:
ax_pose 4, 0x01ed, 0x80f0, 0xac00
ax_pose_terminator
sVibravaPose165:
ax_pose 7, 0x01ed, 0x80ee, 0xac00
ax_pose_terminator
sVibravaPose166:
ax_pose 10, 0x01ea, 0x80f0, 0xac00
ax_pose_terminator
sVibravaPose167:
ax_pose 13, 0x01ea, 0x80f0, 0xac00
ax_pose_terminator
sVibravaPose168:
ax_pose 10, 0x01ea, 0x90ef, 0xac00
ax_pose_terminator
sVibravaPose169:
ax_pose 7, 0x01ed, 0x90f2, 0xac00
ax_pose_terminator
sVibravaPose170:
ax_pose 4, 0x01ed, 0x90ef, 0xac00
ax_pose_terminator
sVibravaPose171:
ax_pose 0, 0x01ec, 0x80f3, 0xac00
ax_pose_terminator
sVibravaPose172:
ax_pose 3, 0x01ec, 0x80f0, 0xac00
ax_pose_terminator
sVibravaPose173:
ax_pose 6, 0x01ec, 0x80ed, 0xac00
ax_pose_terminator
sVibravaPose174:
ax_pose 9, 0x01e8, 0x80f0, 0xac00
ax_pose_terminator
sVibravaPose175:
ax_pose 12, 0x01ec, 0x80f0, 0xac00
ax_pose_terminator
sVibravaPose176:
ax_pose 9, 0x01e8, 0x90ef, 0xac00
ax_pose_terminator
sVibravaPose177:
ax_pose 6, 0x01ec, 0x90f2, 0xac00
ax_pose_terminator
sVibravaPose178:
ax_pose 3, 0x01ec, 0x90ef, 0xac00
ax_pose_terminator
sVibravaPose179:
ax_pose 15, 0x01ec, 0x80f2, 0xac00
ax_pose_terminator
sVibravaPose180:
ax_pose 16, 0x01eb, 0x90ee, 0xac00
ax_pose_terminator
sVibravaPose181:
ax_pose 17, 0x01eb, 0x90f0, 0xac00
ax_pose_terminator
sVibravaPose182:
ax_pose 18, 0x01e9, 0x90ef, 0xac00
ax_pose_terminator
sVibravaPose183:
ax_pose 19, 0x01ea, 0x80f0, 0xac00
ax_pose_terminator
sVibravaPose184:
ax_pose 18, 0x01e9, 0x80f0, 0xac00
ax_pose_terminator
sVibravaPose185:
ax_pose 17, 0x01eb, 0x80ef, 0xac00
ax_pose_terminator
sVibravaPose186:
ax_pose 16, 0x01eb, 0x80f1, 0xac00
ax_pose_terminator
sVibravaPose187:
ax_pose 0, 0x01ec, 0x80f3, 0xac00
ax_pose_terminator
sVibravaPose188:
ax_pose 1, 0x01ec, 0x80f0, 0xac00
ax_pose_terminator
sVibravaPose189:
ax_pose 2, 0x01ec, 0x80f3, 0xac00
ax_pose_terminator
sVibravaPose190:
ax_pose 3, 0x01ec, 0x90ef, 0xac00
ax_pose_terminator
sVibravaPose191:
ax_pose 4, 0x01ec, 0x90ef, 0xac00
ax_pose_terminator
sVibravaPose192:
ax_pose 5, 0x01e8, 0x90ef, 0xac00
ax_pose_terminator
sVibravaPose193:
ax_pose 6, 0x01ec, 0x90f2, 0xac00
ax_pose_terminator
sVibravaPose194:
ax_pose 7, 0x01ec, 0x90f2, 0xac00
ax_pose_terminator
sVibravaPose195:
ax_pose 8, 0x01e8, 0x90f2, 0xac00
ax_pose_terminator
sVibravaPose196:
ax_pose 9, 0x01e8, 0x90ef, 0xac00
ax_pose_terminator
sVibravaPose197:
ax_pose 10, 0x01e8, 0x90ef, 0xac00
ax_pose_terminator
sVibravaPose198:
ax_pose 11, 0x01ea, 0x90ef, 0xac00
ax_pose_terminator
sVibravaPose199:
ax_pose 12, 0x01ec, 0x80f0, 0xac00
ax_pose_terminator
sVibravaPose200:
ax_pose 13, 0x01e8, 0x80f0, 0xac00
ax_pose_terminator
sVibravaPose201:
ax_pose 14, 0x01e8, 0x80f0, 0xac00
ax_pose_terminator
sVibravaPose202:
ax_pose 9, 0x01e8, 0x80f0, 0xac00
ax_pose_terminator
sVibravaPose203:
ax_pose 10, 0x01e8, 0x80f0, 0xac00
ax_pose_terminator
sVibravaPose204:
ax_pose 11, 0x01ea, 0x80f0, 0xac00
ax_pose_terminator
sVibravaPose205:
ax_pose 6, 0x01ec, 0x80ed, 0xac00
ax_pose_terminator
sVibravaPose206:
ax_pose 7, 0x01ec, 0x80ed, 0xac00
ax_pose_terminator
sVibravaPose207:
ax_pose 8, 0x01e8, 0x80ed, 0xac00
ax_pose_terminator
sVibravaPose208:
ax_pose 3, 0x01ec, 0x80f0, 0xac00
ax_pose_terminator
sVibravaPose209:
ax_pose 4, 0x01ec, 0x80f0, 0xac00
ax_pose_terminator
sVibravaPose210:
ax_pose 5, 0x01e8, 0x80f0, 0xac00
ax_pose_terminator
sVibravaPose211:
ax_pose 2, 0x01ec, 0x80f3, 0xac00
ax_pose_terminator
sVibravaPose212:
ax_pose 5, 0x01e8, 0x80f0, 0xac00
ax_pose_terminator
sVibravaPose213:
ax_pose 8, 0x01e9, 0x80ee, 0xac00
ax_pose_terminator
sVibravaPose214:
ax_pose 11, 0x01ec, 0x80f1, 0xac00
ax_pose_terminator
sVibravaPose215:
ax_pose 14, 0x01eb, 0x80f0, 0xac00
ax_pose_terminator
sVibravaPose216:
ax_pose 11, 0x01ec, 0x90ef, 0xac00
ax_pose_terminator
sVibravaPose217:
ax_pose 8, 0x01e9, 0x90f2, 0xac00
ax_pose_terminator
sVibravaPose218:
ax_pose 5, 0x01e8, 0x90ef, 0xac00
ax_pose_terminator
sVibravaPose219:
ax_pose 0, 0x01ec, 0x80f3, 0xac00
ax_pose_terminator
sVibravaPose220:
ax_pose 3, 0x01ec, 0x80f0, 0xac00
ax_pose_terminator
sVibravaPose221:
ax_pose 6, 0x01ec, 0x80ed, 0xac00
ax_pose_terminator
sVibravaPose222:
ax_pose 9, 0x01e8, 0x80f0, 0xac00
ax_pose_terminator
sVibravaPose223:
ax_pose 12, 0x01ec, 0x80f0, 0xac00
ax_pose_terminator
sVibravaPose224:
ax_pose 9, 0x01e8, 0x90ef, 0xac00
ax_pose_terminator
sVibravaPose225:
ax_pose 6, 0x01ec, 0x90f2, 0xac00
ax_pose_terminator
sVibravaPose226:
ax_pose 3, 0x01ec, 0x90ef, 0xac00
ax_pose_terminator
.align 2
sVibravaAnims_1_1:
ax_anim 4, 0, 0, 0, -4, 0, 0,
ax_anim 6, 0, 1, 0, -2, 0, 0,
ax_anim 6, 0, 1, 0, -3, 0, 0,
ax_anim 6, 0, 1, 0, -4, 0, 0,
ax_anim 4, 0, 0, 0, -6, 0, 0,
ax_anim 6, 0, 2, 0, -5, 0, 0,
ax_anim 6, 0, 2, 0, -4, 0, 0,
ax_anim 6, 0, 2, 0, -3, 0, 0,
ax_anim_terminator
sVibravaAnims_1_2:
ax_anim 4, 0, 3, 0, -4, 0, 0,
ax_anim 6, 0, 4, 0, -2, 0, 0,
ax_anim 6, 0, 4, 0, -3, 0, 0,
ax_anim 6, 0, 4, 0, -4, 0, 0,
ax_anim 4, 0, 3, 0, -6, 0, 0,
ax_anim 6, 0, 5, 0, -4, 0, 0,
ax_anim 6, 0, 5, 0, -3, 0, 0,
ax_anim 6, 0, 5, 0, -2, 0, 0,
ax_anim_terminator
sVibravaAnims_1_3:
ax_anim 4, 0, 6, 0, -4, 0, 0,
ax_anim 6, 0, 7, 0, -2, 0, 0,
ax_anim 6, 0, 7, 0, -3, 0, 0,
ax_anim 6, 0, 7, 0, -4, 0, 0,
ax_anim 4, 0, 6, 0, -6, 0, 0,
ax_anim 6, 0, 8, 0, -4, 0, 0,
ax_anim 6, 0, 8, 0, -3, 0, 0,
ax_anim 6, 0, 8, 0, -2, 0, 0,
ax_anim_terminator
sVibravaAnims_1_4:
ax_anim 4, 0, 9, 0, -4, 0, 0,
ax_anim 6, 0, 10, 0, -2, 0, 0,
ax_anim 6, 0, 10, 0, -3, 0, 0,
ax_anim 6, 0, 10, 0, -4, 0, 0,
ax_anim 4, 0, 9, 0, -6, 0, 0,
ax_anim 6, 0, 11, 0, -4, 0, 0,
ax_anim 6, 0, 11, 0, -3, 0, 0,
ax_anim 6, 0, 11, 0, -2, 0, 0,
ax_anim_terminator
sVibravaAnims_1_5:
ax_anim 4, 0, 12, 0, -4, 0, 0,
ax_anim 6, 0, 13, 0, -2, 0, 0,
ax_anim 6, 0, 13, 0, -3, 0, 0,
ax_anim 6, 0, 13, 0, -4, 0, 0,
ax_anim 4, 0, 12, 0, -7, 0, 0,
ax_anim 6, 0, 14, 0, -4, 0, 0,
ax_anim 6, 0, 14, 0, -3, 0, 0,
ax_anim 6, 0, 14, 0, -2, 0, 0,
ax_anim_terminator
sVibravaAnims_1_6:
ax_anim 4, 0, 15, 0, -4, 0, 0,
ax_anim 6, 0, 16, 0, -2, 0, 0,
ax_anim 6, 0, 16, 0, -3, 0, 0,
ax_anim 6, 0, 16, 0, -4, 0, 0,
ax_anim 4, 0, 15, 0, -6, 0, 0,
ax_anim 6, 0, 17, 0, -4, 0, 0,
ax_anim 6, 0, 17, 0, -3, 0, 0,
ax_anim 6, 0, 17, 0, -2, 0, 0,
ax_anim_terminator
sVibravaAnims_1_7:
ax_anim 4, 0, 18, 0, -4, 0, 0,
ax_anim 6, 0, 19, 0, -2, 0, 0,
ax_anim 6, 0, 19, 0, -3, 0, 0,
ax_anim 6, 0, 19, 0, -4, 0, 0,
ax_anim 4, 0, 18, 0, -6, 0, 0,
ax_anim 6, 0, 20, 0, -4, 0, 0,
ax_anim 6, 0, 20, 0, -3, 0, 0,
ax_anim 6, 0, 20, 0, -2, 0, 0,
ax_anim_terminator
sVibravaAnims_1_8:
ax_anim 4, 0, 21, 0, -4, 0, 0,
ax_anim 6, 0, 22, 0, -2, 0, 0,
ax_anim 6, 0, 22, 0, -3, 0, 0,
ax_anim 6, 0, 22, 0, -4, 0, 0,
ax_anim 4, 0, 21, 0, -6, 0, 0,
ax_anim 6, 0, 23, 0, -4, 0, 0,
ax_anim 6, 0, 23, 0, -3, 0, 0,
ax_anim 6, 0, 23, 0, -2, 0, 0,
ax_anim_terminator
.align 2
sVibravaAnims_2_1:
ax_anim 2, 0, 32, 0, 0, 0, 0,
ax_anim 2, 0, 32, 0, -1, 0, -1,
ax_anim 4, 0, 32, 0, -2, 0, -2,
ax_anim 2, 0, 33, 0, -6, 0, -6,
ax_anim 2, 2, 33, 0, 0, 0, 0,
ax_anim 2, 0, 34, 0, 10, 0, 10,
ax_anim 2, 0, 34, 0, 18, 0, 18,
ax_anim 2, 1, 34, 1, 18, 1, 18,
ax_anim 2, 0, 34, 0, 18, 0, 18,
ax_anim 2, 0, 34, 1, 18, 1, 18,
ax_anim 2, 0, 32, 0, 6, 0, 6,
ax_anim_terminator
sVibravaAnims_2_2:
ax_anim 2, 0, 35, 0, 0, 0, 0,
ax_anim 2, 0, 35, -1, -1, -1, -1,
ax_anim 4, 0, 35, -2, -2, -2, -2,
ax_anim 2, 0, 36, 3, -1, 3, 3,
ax_anim 2, 2, 36, 9, 4, 9, 9,
ax_anim 2, 0, 37, 16, 14, 16, 16,
ax_anim 2, 0, 37, 19, 19, 19, 19,
ax_anim 2, 1, 37, 20, 18, 20, 18,
ax_anim 2, 0, 37, 19, 19, 19, 19,
ax_anim 2, 0, 37, 20, 18, 20, 18,
ax_anim 2, 0, 35, 8, 8, 8, 8,
ax_anim_terminator
sVibravaAnims_2_3:
ax_anim 2, 0, 38, 0, 0, 0, 0,
ax_anim 2, 0, 38, -1, 0, -1, 0,
ax_anim 4, 0, 38, -2, 0, -2, 0,
ax_anim 2, 0, 39, 4, -3, 4, 0,
ax_anim 2, 2, 39, 9, -5, 9, 0,
ax_anim 2, 0, 40, 13, -4, 13, 0,
ax_anim 2, 0, 40, 17, 0, 17, 0,
ax_anim 2, 1, 40, 17, 1, 17, 1,
ax_anim 2, 0, 40, 17, 0, 17, 0,
ax_anim 2, 0, 40, 17, 1, 17, 1,
ax_anim 2, 0, 38, 6, 0, 6, -1,
ax_anim_terminator
sVibravaAnims_2_4:
ax_anim 2, 0, 41, 0, 0, 0, 0,
ax_anim 2, 0, 41, -1, 1, -1, 1,
ax_anim 4, 0, 41, -2, 2, -2, 2,
ax_anim 2, 0, 42, 3, -9, 3, -3,
ax_anim 2, 2, 42, 8, -17, 8, -9,
ax_anim 2, 0, 43, 16, -20, 16, -16,
ax_anim 2, 0, 43, 19, -19, 19, -19,
ax_anim 2, 1, 43, 20, -18, 20, -18,
ax_anim 2, 0, 43, 19, -19, 19, -19,
ax_anim 2, 0, 43, 20, -18, 20, -18,
ax_anim 2, 0, 41, 6, -6, 6, -6,
ax_anim_terminator
sVibravaAnims_2_5:
ax_anim 2, 0, 44, 0, 0, 0, 0,
ax_anim 2, 0, 44, 0, 1, 0, 1,
ax_anim 4, 0, 44, 0, 2, 0, 2,
ax_anim 2, 0, 45, 0, -5, 0, -1,
ax_anim 2, 2, 45, 0, -11, 0, -6,
ax_anim 2, 0, 46, 0, -16, 0, -15,
ax_anim 2, 0, 46, 0, -20, 0, -20,
ax_anim 2, 1, 46, 1, -20, 1, -20,
ax_anim 2, 0, 46, 0, -20, 0, -20,
ax_anim 2, 0, 46, 1, -20, 1, -20,
ax_anim 2, 0, 44, 0, -6, 0, -6,
ax_anim_terminator
sVibravaAnims_2_6:
ax_anim 2, 0, 47, 0, 0, 0, 0,
ax_anim 2, 0, 47, 1, 1, 1, 1,
ax_anim 4, 0, 47, 2, 2, 2, 2,
ax_anim 2, 0, 48, -3, -9, -3, -3,
ax_anim 2, 2, 48, -8, -17, -8, -9,
ax_anim 2, 0, 49, -16, -20, -16, -16,
ax_anim 2, 0, 49, -19, -19, -19, -19,
ax_anim 2, 1, 49, -20, -18, -20, -18,
ax_anim 2, 0, 49, -19, -19, -19, -19,
ax_anim 2, 0, 49, -20, -18, -20, -18,
ax_anim 2, 0, 47, -6, -6, -6, -6,
ax_anim_terminator
sVibravaAnims_2_7:
ax_anim 2, 0, 50, 0, 0, 0, 0,
ax_anim 2, 0, 50, 1, 0, 1, 0,
ax_anim 4, 0, 50, 2, 0, 2, 0,
ax_anim 2, 0, 51, -4, -3, -4, 0,
ax_anim 2, 2, 51, -9, -5, -9, 0,
ax_anim 2, 0, 52, -13, -4, -13, 0,
ax_anim 2, 0, 52, -17, 0, -17, 0,
ax_anim 2, 1, 52, -17, 1, -17, 1,
ax_anim 2, 0, 52, -17, 0, -17, 0,
ax_anim 2, 0, 52, -17, 1, -17, 1,
ax_anim 2, 0, 50, -6, 0, -6, -1,
ax_anim_terminator
sVibravaAnims_2_8:
ax_anim 2, 0, 53, 0, 0, 0, 0,
ax_anim 2, 0, 53, 1, -1, 1, -1,
ax_anim 4, 0, 53, 2, -2, 2, -2,
ax_anim 2, 0, 54, -3, -1, -3, 3,
ax_anim 2, 2, 54, -9, 4, -9, 9,
ax_anim 2, 0, 55, -16, 14, -16, 16,
ax_anim 2, 0, 55, -19, 19, -19, 19,
ax_anim 2, 1, 55, -20, 18, -20, 18,
ax_anim 2, 0, 55, -19, 19, -19, 19,
ax_anim 2, 0, 55, -20, 18, -20, 18,
ax_anim 2, 0, 53, -8, 8, -8, 8,
ax_anim_terminator
.align 2
sVibravaAnims_3_1:
ax_anim 2, 0, 64, 0, 0, 0, 0,
ax_anim 2, 0, 64, 0, -1, 0, -1,
ax_anim 4, 0, 64, 0, -2, 0, -2,
ax_anim 2, 0, 65, 0, -6, 0, -6,
ax_anim 2, 2, 65, 0, 0, 0, 0,
ax_anim 2, 0, 66, 0, 10, 0, 10,
ax_anim 2, 0, 66, 0, 18, 0, 18,
ax_anim 2, 1, 66, 1, 18, 1, 18,
ax_anim 2, 0, 66, 0, 18, 0, 18,
ax_anim 2, 0, 66, 1, 18, 1, 18,
ax_anim 2, 0, 64, 0, 6, 0, 6,
ax_anim_terminator
sVibravaAnims_3_2:
ax_anim 2, 0, 67, 0, 0, 0, 0,
ax_anim 2, 0, 67, -1, -1, -1, -1,
ax_anim 4, 0, 67, -2, -2, -2, -2,
ax_anim 2, 0, 68, 3, -1, 3, 3,
ax_anim 2, 2, 68, 9, 4, 9, 9,
ax_anim 2, 0, 69, 16, 14, 16, 16,
ax_anim 2, 0, 69, 19, 19, 19, 19,
ax_anim 2, 1, 69, 20, 18, 20, 18,
ax_anim 2, 0, 69, 19, 19, 19, 19,
ax_anim 2, 0, 69, 20, 18, 20, 18,
ax_anim 2, 0, 67, 8, 8, 8, 8,
ax_anim_terminator
sVibravaAnims_3_3:
ax_anim 2, 0, 70, 0, 0, 0, 0,
ax_anim 2, 0, 70, -1, 0, -1, 0,
ax_anim 4, 0, 70, -2, 0, -2, 0,
ax_anim 2, 0, 71, 4, -3, 4, 0,
ax_anim 2, 2, 71, 9, -5, 9, 0,
ax_anim 2, 0, 72, 13, -4, 13, 0,
ax_anim 2, 0, 72, 17, 0, 17, 0,
ax_anim 2, 1, 72, 17, 1, 17, 1,
ax_anim 2, 0, 72, 17, 0, 17, 0,
ax_anim 2, 0, 72, 17, 1, 17, 1,
ax_anim 2, 0, 70, 6, 0, 6, -1,
ax_anim_terminator
sVibravaAnims_3_4:
ax_anim 2, 0, 73, 0, 0, 0, 0,
ax_anim 2, 0, 73, -1, 1, -1, 1,
ax_anim 4, 0, 73, -2, 2, -2, 2,
ax_anim 2, 0, 74, 3, -9, 3, -3,
ax_anim 2, 2, 74, 8, -17, 8, -9,
ax_anim 2, 0, 75, 16, -20, 16, -16,
ax_anim 2, 0, 75, 19, -19, 19, -19,
ax_anim 2, 1, 75, 20, -18, 20, -18,
ax_anim 2, 0, 75, 19, -19, 19, -19,
ax_anim 2, 0, 75, 20, -18, 20, -18,
ax_anim 2, 0, 73, 6, -6, 6, -6,
ax_anim_terminator
sVibravaAnims_3_5:
ax_anim 2, 0, 76, 0, 0, 0, 0,
ax_anim 2, 0, 76, 0, 1, 0, 1,
ax_anim 4, 0, 76, 0, 2, 0, 2,
ax_anim 2, 0, 77, 0, -5, 0, -1,
ax_anim 2, 2, 77, 0, -11, 0, -6,
ax_anim 2, 0, 78, 0, -16, 0, -15,
ax_anim 2, 0, 78, 0, -20, 0, -20,
ax_anim 2, 1, 78, 1, -20, 1, -20,
ax_anim 2, 0, 78, 0, -20, 0, -20,
ax_anim 2, 0, 78, 1, -20, 1, -20,
ax_anim 2, 0, 76, 0, -6, 0, -6,
ax_anim_terminator
sVibravaAnims_3_6:
ax_anim 2, 0, 79, 0, 0, 0, 0,
ax_anim 2, 0, 79, 1, 1, 1, 1,
ax_anim 4, 0, 79, 2, 2, 2, 2,
ax_anim 2, 0, 80, -3, -9, -3, -3,
ax_anim 2, 2, 80, -8, -17, -8, -9,
ax_anim 2, 0, 81, -16, -20, -16, -16,
ax_anim 2, 0, 81, -19, -19, -19, -19,
ax_anim 2, 1, 81, -20, -18, -20, -18,
ax_anim 2, 0, 81, -19, -19, -19, -19,
ax_anim 2, 0, 81, -20, -18, -20, -18,
ax_anim 2, 0, 79, -6, -6, -6, -6,
ax_anim_terminator
sVibravaAnims_3_7:
ax_anim 2, 0, 82, 0, 0, 0, 0,
ax_anim 2, 0, 82, 1, 0, 1, 0,
ax_anim 4, 0, 82, 2, 0, 2, 0,
ax_anim 2, 0, 83, -4, -3, -4, 0,
ax_anim 2, 2, 83, -9, -5, -9, 0,
ax_anim 2, 0, 84, -13, -4, -13, 0,
ax_anim 2, 0, 84, -17, 0, -17, 0,
ax_anim 2, 1, 84, -17, 1, -17, 1,
ax_anim 2, 0, 84, -17, 0, -17, 0,
ax_anim 2, 0, 84, -17, 1, -17, 1,
ax_anim 2, 0, 82, -6, 0, -6, -1,
ax_anim_terminator
sVibravaAnims_3_8:
ax_anim 2, 0, 85, 0, 0, 0, 0,
ax_anim 2, 0, 85, 1, -1, 1, -1,
ax_anim 4, 0, 85, 2, -2, 2, -2,
ax_anim 2, 0, 86, -3, -1, -3, 3,
ax_anim 2, 2, 86, -9, 4, -9, 9,
ax_anim 2, 0, 87, -16, 14, -16, 16,
ax_anim 2, 0, 87, -19, 19, -19, 19,
ax_anim 2, 1, 87, -20, 18, -20, 18,
ax_anim 2, 0, 87, -19, 19, -19, 19,
ax_anim 2, 0, 87, -20, 18, -20, 18,
ax_anim 2, 0, 85, -8, 8, -8, 8,
ax_anim_terminator
.align 2
sVibravaAnims_4_1:
ax_anim 2, 0, 96, 0, -1, 0, -1,
ax_anim 2, 0, 96, 1, -1, 1, -1,
ax_anim 2, 0, 96, 0, -2, 0, -2,
ax_anim 2, 0, 96, 1, -2, 1, -2,
ax_anim 6, 2, 96, 0, -2, 0, -2,
ax_anim 1, 0, 97, 0, 1, 0, 1,
ax_anim 1, 0, 97, 0, 4, 0, 4,
ax_anim 2, 1, 97, 1, 4, 1, 4,
ax_anim 2, 0, 97, 0, 4, 0, 4,
ax_anim 2, 0, 97, 1, 4, 1, 4,
ax_anim 2, 0, 97, 0, 4, 0, 4,
ax_anim 2, 0, 97, 1, 4, 1, 4,
ax_anim 2, 0, 97, 0, 4, 0, 4,
ax_anim 2, 0, 96, 0, 2, 0, 2,
ax_anim_terminator
sVibravaAnims_4_2:
ax_anim 2, 0, 98, -1, -1, -1, -1,
ax_anim 2, 0, 98, 0, -2, 0, -2,
ax_anim 2, 0, 98, -2, -2, -2, -2,
ax_anim 2, 0, 98, -1, -3, -1, -3,
ax_anim 6, 2, 98, -2, -2, -2, -2,
ax_anim 1, 0, 99, 1, 1, 1, 1,
ax_anim 1, 0, 99, 4, 4, 4, 4,
ax_anim 2, 1, 99, 5, 3, 5, 3,
ax_anim 2, 0, 99, 4, 4, 4, 4,
ax_anim 2, 0, 99, 5, 3, 5, 3,
ax_anim 2, 0, 99, 4, 4, 4, 4,
ax_anim 2, 0, 99, 5, 3, 5, 3,
ax_anim 2, 0, 99, 4, 4, 4, 4,
ax_anim 2, 0, 98, 2, 2, 2, 2,
ax_anim_terminator
sVibravaAnims_4_3:
ax_anim 2, 0, 100, -1, 0, -1, 0,
ax_anim 2, 0, 100, -1, 1, -1, 1,
ax_anim 2, 0, 100, -2, 0, -2, 0,
ax_anim 2, 0, 100, -2, 1, -2, 1,
ax_anim 6, 2, 100, -2, 0, -2, 0,
ax_anim 1, 0, 101, 1, 0, 1, 0,
ax_anim 1, 0, 101, 5, 0, 5, 0,
ax_anim 2, 1, 101, 5, 1, 5, 1,
ax_anim 2, 0, 101, 5, 0, 5, 0,
ax_anim 2, 0, 101, 5, 1, 5, 1,
ax_anim 2, 0, 101, 5, 0, 5, 0,
ax_anim 2, 0, 101, 5, 1, 5, 1,
ax_anim 2, 0, 101, 5, 0, 5, 0,
ax_anim 2, 0, 100, 2, 0, 2, 0,
ax_anim_terminator
sVibravaAnims_4_4:
ax_anim 2, 0, 102, -1, 1, -1, 1,
ax_anim 2, 0, 102, 0, 2, 0, 2,
ax_anim 2, 0, 102, -2, 2, -2, 2,
ax_anim 2, 0, 102, -1, 3, -1, 3,
ax_anim 6, 2, 102, -2, 2, -2, 2,
ax_anim 1, 0, 103, 1, -1, 1, -1,
ax_anim 1, 0, 103, 4, -4, 4, -4,
ax_anim 2, 1, 103, 5, -3, 5, -3,
ax_anim 2, 0, 103, 4, -4, 4, -4,
ax_anim 2, 0, 103, 5, -3, 5, -3,
ax_anim 2, 0, 103, 4, -4, 4, -4,
ax_anim 2, 0, 103, 5, -3, 5, -3,
ax_anim 2, 0, 103, 4, -4, 4, -4,
ax_anim 2, 0, 102, 2, -2, 2, -2,
ax_anim_terminator
sVibravaAnims_4_5:
ax_anim 2, 0, 104, 0, 1, 0, 1,
ax_anim 2, 0, 104, 1, 1, 1, 1,
ax_anim 2, 0, 104, 0, 2, 0, 2,
ax_anim 2, 0, 104, 1, 2, 1, 2,
ax_anim 6, 2, 104, 0, 2, 0, 2,
ax_anim 1, 0, 105, 0, -1, 0, -1,
ax_anim 1, 0, 105, 0, -6, 0, -6,
ax_anim 2, 1, 105, 1, -6, 1, -6,
ax_anim 2, 0, 105, 0, -6, 0, -6,
ax_anim 2, 0, 105, 1, -6, 1, -6,
ax_anim 2, 0, 105, 0, -6, 0, -6,
ax_anim 2, 0, 105, 1, -6, 1, -6,
ax_anim 2, 0, 105, 0, -6, 0, -6,
ax_anim 2, 0, 104, 0, -2, 0, -2,
ax_anim_terminator
sVibravaAnims_4_6:
ax_anim 2, 0, 106, 1, 1, 1, 1,
ax_anim 2, 0, 106, 0, 2, 0, 2,
ax_anim 2, 0, 106, 2, 2, 2, 2,
ax_anim 2, 0, 106, 1, 3, 1, 3,
ax_anim 6, 2, 106, 2, 2, 2, 2,
ax_anim 1, 0, 107, -1, -1, -1, -1,
ax_anim 1, 0, 107, -4, -4, -4, -4,
ax_anim 2, 1, 107, -5, -3, -5, -3,
ax_anim 2, 0, 107, -4, -4, -4, -4,
ax_anim 2, 0, 107, -5, -3, -5, -3,
ax_anim 2, 0, 107, -4, -4, -4, -4,
ax_anim 2, 0, 107, -5, -3, -5, -3,
ax_anim 2, 0, 107, -4, -4, -4, -4,
ax_anim 2, 0, 106, -2, -2, -2, -2,
ax_anim_terminator
sVibravaAnims_4_7:
ax_anim 2, 0, 108, 1, 0, 1, 0,
ax_anim 2, 0, 108, 1, 1, 1, 1,
ax_anim 2, 0, 108, 2, 0, 2, 0,
ax_anim 2, 0, 108, 2, 1, 2, 1,
ax_anim 6, 2, 108, 2, 0, 2, 0,
ax_anim 1, 0, 109, -1, 0, -1, 0,
ax_anim 1, 0, 109, -5, 0, -5, 0,
ax_anim 2, 1, 109, -5, 1, -5, 1,
ax_anim 2, 0, 109, -5, 0, -5, 0,
ax_anim 2, 0, 109, -5, 1, -5, 1,
ax_anim 2, 0, 109, -5, 0, -5, 0,
ax_anim 2, 0, 109, -5, 1, -5, 1,
ax_anim 2, 0, 109, -5, 0, -5, 0,
ax_anim 2, 0, 108, -2, 0, -2, 0,
ax_anim_terminator
sVibravaAnims_4_8:
ax_anim 2, 0, 110, 1, -1, 1, -1,
ax_anim 2, 0, 110, 0, -2, 0, -2,
ax_anim 2, 0, 110, 2, -2, 2, -2,
ax_anim 2, 0, 110, 1, -3, 1, -3,
ax_anim 6, 2, 110, 2, -2, 2, -2,
ax_anim 1, 0, 111, -1, 1, -1, 1,
ax_anim 1, 0, 111, -4, 4, -4, 4,
ax_anim 2, 1, 111, -5, 3, -5, 3,
ax_anim 2, 0, 111, -4, 4, -4, 4,
ax_anim 2, 0, 111, -5, 3, -5, 3,
ax_anim 2, 0, 111, -4, 4, -4, 4,
ax_anim 2, 0, 111, -5, 3, -5, 3,
ax_anim 2, 0, 111, -4, 4, -4, 4,
ax_anim 2, 0, 110, -2, 2, -2, 2,
ax_anim_terminator
.align 2
sVibravaAnims_5_1:
ax_anim 2, 0, 112, 0, 0, 0, 0,
ax_anim 2, 0, 113, 0, 0, 0, 0,
ax_anim 2, 0, 114, 0, 0, 0, 0,
ax_anim 2, 0, 115, 0, 0, 0, 0,
ax_anim 2, 0, 116, 0, 0, 0, 0,
ax_anim 2, 0, 117, 0, 0, 0, 0,
ax_anim 2, 0, 118, 0, 0, 0, 0,
ax_anim 2, 0, 119, 0, 0, 0, 0,
ax_anim 2, 2, 112, 0, 0, 0, 0,
ax_anim_terminator
sVibravaAnims_5_2:
ax_anim 2, 0, 119, 0, 0, 0, 0,
ax_anim 2, 0, 112, 0, 0, 0, 0,
ax_anim 2, 0, 113, 0, 0, 0, 0,
ax_anim 2, 0, 114, 0, 0, 0, 0,
ax_anim 2, 0, 115, 0, 0, 0, 0,
ax_anim 2, 0, 116, 0, 0, 0, 0,
ax_anim 2, 0, 117, 0, 0, 0, 0,
ax_anim 2, 0, 118, 0, 0, 0, 0,
ax_anim 2, 2, 119, 0, 0, 0, 0,
ax_anim_terminator
sVibravaAnims_5_3:
ax_anim 2, 0, 118, 0, 0, 0, 0,
ax_anim 2, 0, 119, 0, 0, 0, 0,
ax_anim 2, 0, 112, 0, 0, 0, 0,
ax_anim 2, 0, 113, 0, 0, 0, 0,
ax_anim 2, 0, 114, 0, 0, 0, 0,
ax_anim 2, 0, 115, 0, 0, 0, 0,
ax_anim 2, 0, 116, 0, 0, 0, 0,
ax_anim 2, 0, 117, 0, 0, 0, 0,
ax_anim 2, 2, 118, 0, 0, 0, 0,
ax_anim_terminator
sVibravaAnims_5_4:
ax_anim 2, 0, 117, 0, 0, 0, 0,
ax_anim 2, 0, 118, 0, 0, 0, 0,
ax_anim 2, 0, 119, 0, 0, 0, 0,
ax_anim 2, 0, 112, 0, 0, 0, 0,
ax_anim 2, 0, 113, 0, 0, 0, 0,
ax_anim 2, 0, 114, 0, 0, 0, 0,
ax_anim 2, 0, 115, 0, 0, 0, 0,
ax_anim 2, 0, 116, 0, 0, 0, 0,
ax_anim 2, 2, 117, 0, 0, 0, 0,
ax_anim_terminator
sVibravaAnims_5_5:
ax_anim 2, 0, 116, 0, 0, 0, 0,
ax_anim 2, 0, 117, 0, 0, 0, 0,
ax_anim 2, 0, 118, 0, 0, 0, 0,
ax_anim 2, 0, 119, 0, 0, 0, 0,
ax_anim 2, 0, 112, 0, 0, 0, 0,
ax_anim 2, 0, 113, 0, 0, 0, 0,
ax_anim 2, 0, 114, 0, 0, 0, 0,
ax_anim 2, 0, 115, 0, 0, 0, 0,
ax_anim 2, 2, 116, 0, 0, 0, 0,
ax_anim_terminator
sVibravaAnims_5_6:
ax_anim 2, 0, 115, 0, 0, 0, 0,
ax_anim 2, 0, 116, 0, 0, 0, 0,
ax_anim 2, 0, 117, 0, 0, 0, 0,
ax_anim 2, 0, 118, 0, 0, 0, 0,
ax_anim 2, 0, 119, 0, 0, 0, 0,
ax_anim 2, 0, 112, 0, 0, 0, 0,
ax_anim 2, 0, 113, 0, 0, 0, 0,
ax_anim 2, 0, 114, 0, 0, 0, 0,
ax_anim 2, 2, 115, 0, 0, 0, 0,
ax_anim_terminator
sVibravaAnims_5_7:
ax_anim 2, 0, 114, 0, 0, 0, 0,
ax_anim 2, 0, 115, 0, 0, 0, 0,
ax_anim 2, 0, 116, 0, 0, 0, 0,
ax_anim 2, 0, 117, 0, 0, 0, 0,
ax_anim 2, 0, 118, 0, 0, 0, 0,
ax_anim 2, 0, 119, 0, 0, 0, 0,
ax_anim 2, 0, 112, 0, 0, 0, 0,
ax_anim 2, 0, 113, 0, 0, 0, 0,
ax_anim 2, 2, 114, 0, 0, 0, 0,
ax_anim_terminator
sVibravaAnims_5_8:
ax_anim 2, 0, 113, 0, 0, 0, 0,
ax_anim 2, 0, 114, 0, 0, 0, 0,
ax_anim 2, 0, 115, 0, 0, 0, 0,
ax_anim 2, 0, 116, 0, 0, 0, 0,
ax_anim 2, 0, 117, 0, 0, 0, 0,
ax_anim 2, 0, 118, 0, 0, 0, 0,
ax_anim 2, 0, 119, 0, 0, 0, 0,
ax_anim 2, 0, 112, 0, 0, 0, 0,
ax_anim 2, 2, 113, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sVibravaAnims_6_1:
ax_anim 30, 0, 120, 0, 0, 0, 0,
ax_anim 35, 0, 121, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sVibravaAnims_7_1:
ax_anim 2, 0, 122, 0, -2, 0, -2,
ax_anim 8, 0, 122, 0, -3, 0, -3,
ax_anim_terminator
sVibravaAnims_7_2:
ax_anim 2, 0, 123, -2, -2, -2, -2,
ax_anim 8, 0, 123, -3, -3, -3, -3,
ax_anim_terminator
sVibravaAnims_7_3:
ax_anim 2, 0, 124, -2, 0, -2, 0,
ax_anim 8, 0, 124, -3, 0, -3, 0,
ax_anim_terminator
sVibravaAnims_7_4:
ax_anim 2, 0, 125, -2, 2, -2, 2,
ax_anim 8, 0, 125, -3, 3, -3, 3,
ax_anim_terminator
sVibravaAnims_7_5:
ax_anim 2, 0, 126, 0, 2, 0, 2,
ax_anim 8, 0, 126, 0, 3, 0, 3,
ax_anim_terminator
sVibravaAnims_7_6:
ax_anim 2, 0, 127, 2, 2, 2, 2,
ax_anim 8, 0, 127, 3, 3, 3, 3,
ax_anim_terminator
sVibravaAnims_7_7:
ax_anim 2, 0, 128, 2, 0, 2, 0,
ax_anim 8, 0, 128, 3, 0, 3, 0,
ax_anim_terminator
sVibravaAnims_7_8:
ax_anim 2, 0, 129, 2, -2, 2, -2,
ax_anim 8, 0, 129, 3, -3, 3, -3,
ax_anim_terminator
.align 2
sVibravaAnims_8_1:
ax_anim 40, 0, 130, 0, 0, 0, 0,
ax_anim 4, 0, 132, 0, -1, 0, 0,
ax_anim 4, 0, 131, 0, 1, 0, 0,
ax_anim 4, 0, 131, 0, -4, 0, 0,
ax_anim 4, 0, 131, 0, -5, 0, 0,
ax_anim 4, 0, 131, 0, -4, 0, 0,
ax_anim 4, 0, 131, 0, -3, 0, 0,
ax_anim 4, 0, 131, 0, 0, 0, 0,
ax_anim 4, 0, 131, 0, 1, 0, 0,
ax_anim_terminator
sVibravaAnims_8_2:
ax_anim 40, 0, 133, 0, 0, 0, 0,
ax_anim 4, 0, 135, 0, 1, 0, 0,
ax_anim 4, 0, 134, 0, 1, 0, 0,
ax_anim 4, 0, 134, 0, -4, 0, 0,
ax_anim 4, 0, 134, 0, -5, 0, 0,
ax_anim 4, 0, 134, 0, -4, 0, 0,
ax_anim 4, 0, 134, 0, -3, 0, 0,
ax_anim 4, 0, 134, 0, 0, 0, 0,
ax_anim 4, 0, 134, 0, 2, 0, 0,
ax_anim_terminator
sVibravaAnims_8_3:
ax_anim 40, 0, 136, 0, 0, 0, 0,
ax_anim 4, 0, 138, 0, 1, 0, 0,
ax_anim 4, 0, 137, 0, 1, 0, 0,
ax_anim 4, 0, 137, 0, -4, 0, 0,
ax_anim 4, 0, 137, 0, -5, 0, 0,
ax_anim 4, 0, 137, 0, -4, 0, 0,
ax_anim 4, 0, 137, 0, -3, 0, 0,
ax_anim 4, 0, 137, 0, 0, 0, 0,
ax_anim 4, 0, 137, 0, 2, 0, 0,
ax_anim_terminator
sVibravaAnims_8_4:
ax_anim 40, 0, 139, 0, 0, 0, 0,
ax_anim 4, 0, 141, 0, 2, 0, 0,
ax_anim 4, 0, 140, 0, 1, 0, 0,
ax_anim 4, 0, 140, 0, -4, 0, 0,
ax_anim 4, 0, 140, 0, -5, 0, 0,
ax_anim 4, 0, 140, 0, -4, 0, 0,
ax_anim 4, 0, 140, 0, -3, 0, 0,
ax_anim 4, 0, 140, 0, 0, 0, 0,
ax_anim 4, 0, 140, 0, 2, 0, 0,
ax_anim_terminator
sVibravaAnims_8_5:
ax_anim 40, 0, 142, 0, 0, 0, 0,
ax_anim 4, 0, 144, 0, 2, 0, 0,
ax_anim 4, 0, 143, 0, -2, 0, 0,
ax_anim 4, 0, 143, 0, -4, 0, 0,
ax_anim 4, 0, 143, 0, -5, 0, 0,
ax_anim 4, 0, 143, 0, -4, 0, 0,
ax_anim 4, 0, 143, 0, -3, 0, 0,
ax_anim 4, 0, 143, 0, 0, 0, 0,
ax_anim 4, 0, 143, 0, 2, 0, 0,
ax_anim_terminator
sVibravaAnims_8_6:
ax_anim 40, 0, 145, 0, 0, 0, 0,
ax_anim 4, 0, 147, 0, 2, 0, 0,
ax_anim 4, 0, 146, 0, 1, 0, 0,
ax_anim 4, 0, 146, 0, -4, 0, 0,
ax_anim 4, 0, 146, 0, -5, 0, 0,
ax_anim 4, 0, 146, 0, -4, 0, 0,
ax_anim 4, 0, 146, 0, -3, 0, 0,
ax_anim 4, 0, 146, 0, 0, 0, 0,
ax_anim 4, 0, 146, 0, 2, 0, 0,
ax_anim_terminator
sVibravaAnims_8_7:
ax_anim 40, 0, 148, 0, 0, 0, 0,
ax_anim 4, 0, 150, 0, 1, 0, 0,
ax_anim 4, 0, 149, 0, 1, 0, 0,
ax_anim 4, 0, 149, 0, -4, 0, 0,
ax_anim 4, 0, 149, 0, -5, 0, 0,
ax_anim 4, 0, 149, 0, -4, 0, 0,
ax_anim 4, 0, 149, 0, -3, 0, 0,
ax_anim 4, 0, 149, 0, 0, 0, 0,
ax_anim 4, 0, 149, 0, 2, 0, 0,
ax_anim_terminator
sVibravaAnims_8_8:
ax_anim 40, 0, 151, 0, 0, 0, 0,
ax_anim 4, 0, 153, 0, 1, 0, 0,
ax_anim 4, 0, 152, 0, 1, 0, 0,
ax_anim 4, 0, 152, 0, -4, 0, 0,
ax_anim 4, 0, 152, 0, -5, 0, 0,
ax_anim 4, 0, 152, 0, -4, 0, 0,
ax_anim 4, 0, 152, 0, -3, 0, 0,
ax_anim 4, 0, 152, 0, 0, 0, 0,
ax_anim 4, 0, 152, 0, 2, 0, 0,
ax_anim_terminator
.align 2
sVibravaAnims_9_1:
ax_anim 2, 0, 162, 0, 0, 0, 0,
ax_anim 1, 0, 163, 7, 4, 7, 4,
ax_anim 2, 0, 164, 11, 10, 11, 10,
ax_anim 2, 0, 165, 8, 16, 8, 16,
ax_anim 3, 0, 166, 0, 18, 0, 18,
ax_anim 2, 3, 167, -8, 16, -8, 16,
ax_anim 2, 0, 168, -11, 10, -11, 10,
ax_anim 1, 0, 169, -7, 4, -7, 4,
ax_anim 1, 0, 162, 0, 0, 0, 0,
ax_anim_terminator
sVibravaAnims_9_2:
ax_anim 2, 0, 169, 0, 0, 0, 0,
ax_anim 1, 0, 162, 7, 0, 7, 0,
ax_anim 2, 0, 163, 17, 5, 17, 5,
ax_anim 2, 0, 164, 21, 13, 21, 13,
ax_anim 3, 0, 165, 19, 18, 19, 18,
ax_anim 2, 3, 166, 11, 21, 11, 21,
ax_anim 2, 0, 167, 1, 17, 1, 17,
ax_anim 1, 0, 168, -2, 8, -2, 8,
ax_anim 1, 0, 169, 0, 0, 0, 0,
ax_anim_terminator
sVibravaAnims_9_3:
ax_anim 2, 0, 168, 0, 0, 0, 0,
ax_anim 1, 0, 169, 3, -4, 3, -4,
ax_anim 2, 0, 162, 9, -6, 9, -6,
ax_anim 2, 0, 163, 17, -2, 17, -2,
ax_anim 3, 0, 164, 20, 3, 20, 3,
ax_anim 2, 3, 165, 19, 5, 19, 5,
ax_anim 2, 0, 166, 8, 7, 8, 7,
ax_anim 1, 0, 167, 3, 5, 3, 5,
ax_anim 1, 0, 168, 0, 0, 0, 0,
ax_anim_terminator
sVibravaAnims_9_4:
ax_anim 2, 0, 167, 0, 0, 0, 0,
ax_anim 1, 0, 168, -3, -10, -3, -10,
ax_anim 2, 0, 169, 2, -17, 2, -17,
ax_anim 2, 0, 162, 10, -24, 10, -24,
ax_anim 3, 0, 163, 18, -21, 18, -21,
ax_anim 2, 3, 164, 22, -15, 22, -15,
ax_anim 2, 0, 165, 18, -5, 18, -5,
ax_anim 1, 0, 166, 9, 0, 9, 0,
ax_anim 1, 0, 167, 0, 0, 0, 0,
ax_anim_terminator
sVibravaAnims_9_5:
ax_anim 2, 0, 166, 0, 0, 0, 0,
ax_anim 1, 0, 167, -8, -3, -8, -3,
ax_anim 2, 0, 168, -12, -12, -12, -12,
ax_anim 2, 0, 169, -8, -18, -8, -18,
ax_anim 3, 0, 162, 0, -22, 0, -22,
ax_anim 2, 3, 163, 8, -18, 8, -18,
ax_anim 2, 0, 164, 12, -12, 12, -12,
ax_anim 1, 0, 165, 8, -3, 8, -3,
ax_anim 1, 0, 166, 0, 0, 0, 0,
ax_anim_terminator
sVibravaAnims_9_6:
ax_anim 2, 0, 165, 0, 0, 0, 0,
ax_anim 1, 0, 164, 3, -10, 3, -10,
ax_anim 2, 0, 163, -2, -17, -2, -17,
ax_anim 2, 0, 162, -10, -24, -10, -24,
ax_anim 3, 0, 169, -18, -21, -18, -21,
ax_anim 2, 3, 168, -22, -15, -22, -15,
ax_anim 2, 0, 167, -18, -5, -18, -5,
ax_anim 1, 0, 166, -9, 0, -9, 0,
ax_anim 1, 0, 165, 0, 0, 0, 0,
ax_anim_terminator
sVibravaAnims_9_7:
ax_anim 2, 0, 164, 0, 0, 0, 0,
ax_anim 1, 0, 163, -3, -4, -3, -4,
ax_anim 2, 0, 162, -9, -6, -9, -6,
ax_anim 2, 0, 169, -17, -2, -17, -2,
ax_anim 3, 0, 168, -20, 3, -20, 3,
ax_anim 2, 3, 167, -19, 5, -19, 5,
ax_anim 2, 0, 166, -8, 7, -8, 7,
ax_anim 1, 0, 165, -3, 5, -3, 5,
ax_anim 1, 0, 164, 0, 0, 0, 0,
ax_anim_terminator
sVibravaAnims_9_8:
ax_anim 2, 0, 163, 0, 0, 0, 0,
ax_anim 1, 0, 162, -7, 0, -7, 0,
ax_anim 2, 0, 169, -17, 5, -17, 5,
ax_anim 2, 0, 168, -21, 13, -21, 13,
ax_anim 3, 0, 167, -19, 18, -19, 18,
ax_anim 2, 3, 166, -11, 21, -11, 21,
ax_anim 2, 0, 165, -1, 17, -1, 17,
ax_anim 1, 0, 164, 2, 8, 2, 8,
ax_anim 1, 0, 163, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sVibravaAnims_10_1:
ax_anim 2, 0, 178, 0, 0, 0, 0,
ax_anim 2, 0, 178, 6, 0, 6, 0,
ax_anim 2, 0, 178, -6, 0, -6, 0,
ax_anim 2, 0, 178, 10, 0, 10, 0,
ax_anim 2, 0, 178, -10, 0, -10, 0,
ax_anim 2, 0, 178, 12, 0, 12, 0,
ax_anim 3, 0, 178, -12, 0, -12, 0,
ax_anim 3, 0, 178, 13, 0, 13, 0,
ax_anim 3, 0, 178, -13, 0, -13, 0,
ax_anim 2, 0, 178, 12, 0, 12, 0,
ax_anim 3, 0, 178, -12, 0, -12, 0,
ax_anim 2, 0, 178, 10, 0, 10, 0,
ax_anim 2, 0, 178, -10, 0, -10, 0,
ax_anim 2, 0, 178, 6, 0, 6, 0,
ax_anim 2, 0, 178, -6, 0, -6, 0,
ax_anim 2, 0, 178, 0, 0, 0, 0,
ax_anim_terminator
sVibravaAnims_10_2:
ax_anim 2, 0, 179, 0, 0, 0, 0,
ax_anim 2, 0, 179, 6, -6, 6, -6,
ax_anim 2, 0, 179, -6, 6, -6, 6,
ax_anim 2, 0, 179, 10, -10, 10, -10,
ax_anim 2, 0, 179, -10, 10, -10, 10,
ax_anim 2, 0, 179, 12, -12, 12, -12,
ax_anim 3, 0, 179, -12, 12, -12, 12,
ax_anim 3, 0, 179, 13, -13, 13, -13,
ax_anim 3, 0, 179, -13, 13, -13, 13,
ax_anim 2, 0, 179, 12, -12, 12, -12,
ax_anim 3, 0, 179, -12, 12, -12, 12,
ax_anim 2, 0, 179, 10, -10, 10, -10,
ax_anim 2, 0, 179, -10, 10, -10, 10,
ax_anim 2, 0, 179, 6, -6, 6, -6,
ax_anim 2, 0, 179, -6, 6, -6, 6,
ax_anim 2, 0, 179, 0, 0, 0, 0,
ax_anim_terminator
sVibravaAnims_10_3:
ax_anim 2, 0, 180, 0, 0, 0, 0,
ax_anim 2, 0, 180, 0, -6, 0, -6,
ax_anim 2, 0, 180, 0, 6, 0, 6,
ax_anim 2, 0, 180, 0, -10, 0, -10,
ax_anim 2, 0, 180, 0, 10, 0, 10,
ax_anim 2, 0, 180, 0, -12, 0, -12,
ax_anim 3, 0, 180, 0, 12, 0, 12,
ax_anim 3, 0, 180, 0, -13, 0, -13,
ax_anim 3, 0, 180, 0, 13, 0, 13,
ax_anim 2, 0, 180, 0, -12, 0, -12,
ax_anim 3, 0, 180, 0, 12, 0, 12,
ax_anim 2, 0, 180, 0, -10, 0, -10,
ax_anim 2, 0, 180, 0, 10, 0, 10,
ax_anim 2, 0, 180, 0, -6, 0, -6,
ax_anim 2, 0, 180, 0, 6, 0, 6,
ax_anim 2, 0, 180, 0, 0, 0, 0,
ax_anim_terminator
sVibravaAnims_10_4:
ax_anim 2, 0, 181, 0, 0, 0, 0,
ax_anim 2, 0, 181, -6, -6, -6, -6,
ax_anim 2, 0, 181, 6, 6, 6, 6,
ax_anim 2, 0, 181, -10, -10, -10, -10,
ax_anim 2, 0, 181, 10, 10, 10, 10,
ax_anim 2, 0, 181, -12, -12, -12, -12,
ax_anim 3, 0, 181, 12, 12, 12, 12,
ax_anim 3, 0, 181, -13, -13, -13, -13,
ax_anim 3, 0, 181, 13, 13, 13, 13,
ax_anim 2, 0, 181, -12, -12, -12, -12,
ax_anim 3, 0, 181, 12, 12, 12, 12,
ax_anim 2, 0, 181, -10, -10, -10, -10,
ax_anim 2, 0, 181, 10, 10, 10, 10,
ax_anim 2, 0, 181, -6, -6, -6, -6,
ax_anim 2, 0, 181, 6, 6, 6, 6,
ax_anim 2, 0, 181, 0, 0, 0, 0,
ax_anim_terminator
sVibravaAnims_10_5:
ax_anim 2, 0, 182, 0, 0, 0, 0,
ax_anim 2, 0, 182, 6, 0, 6, 0,
ax_anim 2, 0, 182, -6, 0, -6, 0,
ax_anim 2, 0, 182, 10, 0, 10, 0,
ax_anim 2, 0, 182, -10, 0, -10, 0,
ax_anim 2, 0, 182, 12, 0, 12, 0,
ax_anim 3, 0, 182, -12, 0, -12, 0,
ax_anim 3, 0, 182, 13, 0, 13, 0,
ax_anim 3, 0, 182, -13, 0, -13, 0,
ax_anim 2, 0, 182, 12, 0, 12, 0,
ax_anim 3, 0, 182, -12, 0, -12, 0,
ax_anim 2, 0, 182, 10, 0, 10, 0,
ax_anim 2, 0, 182, -10, 0, -10, 0,
ax_anim 2, 0, 182, 6, 0, 6, 0,
ax_anim 2, 0, 182, -6, 0, -6, 0,
ax_anim 2, 0, 182, 0, 0, 0, 0,
ax_anim_terminator
sVibravaAnims_10_6:
ax_anim 2, 0, 183, 0, 0, 0, 0,
ax_anim 2, 0, 183, 6, -6, 6, -6,
ax_anim 2, 0, 183, -6, 6, -6, 6,
ax_anim 2, 0, 183, 10, -10, 10, -10,
ax_anim 2, 0, 183, -10, 10, -10, 10,
ax_anim 2, 0, 183, 12, -12, 12, -12,
ax_anim 3, 0, 183, -12, 12, -12, 12,
ax_anim 3, 0, 183, 13, -13, 13, -13,
ax_anim 3, 0, 183, -13, 13, -13, 13,
ax_anim 2, 0, 183, 12, -12, 12, -12,
ax_anim 3, 0, 183, -12, 12, -12, 12,
ax_anim 2, 0, 183, 10, -10, 10, -10,
ax_anim 2, 0, 183, -10, 10, -10, 10,
ax_anim 2, 0, 183, 6, -6, 6, -6,
ax_anim 2, 0, 183, -6, 6, -6, 6,
ax_anim 2, 0, 183, 0, 0, 0, 0,
ax_anim_terminator
sVibravaAnims_10_7:
ax_anim 2, 0, 184, 0, 0, 0, 0,
ax_anim 2, 0, 184, 0, -6, 0, -6,
ax_anim 2, 0, 184, 0, 6, 0, 6,
ax_anim 2, 0, 184, 0, -10, 0, -10,
ax_anim 2, 0, 184, 0, 10, 0, 10,
ax_anim 2, 0, 184, 0, -12, 0, -12,
ax_anim 3, 0, 184, 0, 12, 0, 12,
ax_anim 3, 0, 184, 0, -13, 0, -13,
ax_anim 3, 0, 184, 0, 13, 0, 13,
ax_anim 2, 0, 184, 0, -12, 0, -12,
ax_anim 3, 0, 184, 0, 12, 0, 12,
ax_anim 2, 0, 184, 0, -10, 0, -10,
ax_anim 2, 0, 184, 0, 10, 0, 10,
ax_anim 2, 0, 184, 0, -6, 0, -6,
ax_anim 2, 0, 184, 0, 6, 0, 6,
ax_anim 2, 0, 184, 0, 0, 0, 0,
ax_anim_terminator
sVibravaAnims_10_8:
ax_anim 2, 0, 185, 0, 0, 0, 0,
ax_anim 2, 0, 185, -6, -6, -6, -6,
ax_anim 2, 0, 185, 6, 6, 6, 6,
ax_anim 2, 0, 185, -10, -10, -10, -10,
ax_anim 2, 0, 185, 10, 10, 10, 10,
ax_anim 2, 0, 185, -12, -12, -12, -12,
ax_anim 3, 0, 185, 12, 12, 12, 12,
ax_anim 3, 0, 185, -13, -13, -13, -13,
ax_anim 3, 0, 185, 13, 13, 13, 13,
ax_anim 2, 0, 185, -12, -12, -12, -12,
ax_anim 3, 0, 185, 12, 12, 12, 12,
ax_anim 2, 0, 185, -10, -10, -10, -10,
ax_anim 2, 0, 185, 10, 10, 10, 10,
ax_anim 2, 0, 185, -6, -6, -6, -6,
ax_anim 2, 0, 185, 6, 6, 6, 6,
ax_anim 2, 0, 185, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sVibravaAnims_11_1:
ax_anim 2, 0, 186, 0, 0, 0, 0,
ax_anim 1, 0, 187, 0, -10, 0, 0,
ax_anim 2, 0, 187, 0, -16, 0, 0,
ax_anim 3, 0, 187, 0, -18, 0, 0,
ax_anim 4, 0, 187, 0, -19, 0, 0,
ax_anim 4, 0, 186, 0, -23, 0, 0,
ax_anim 3, 0, 188, 0, -22, 0, 0,
ax_anim 2, 0, 188, 0, -18, 0, 0,
ax_anim 1, 0, 188, 0, -12, 0, 0,
ax_anim 2, 2, 186, 0, 0, 0, 0,
ax_anim_terminator
sVibravaAnims_11_2:
ax_anim 2, 0, 189, 0, 0, 0, 0,
ax_anim 1, 0, 190, 0, -10, 0, 0,
ax_anim 2, 0, 190, 0, -16, 0, 0,
ax_anim 3, 0, 190, 0, -18, 0, 0,
ax_anim 4, 0, 190, 0, -19, 0, 0,
ax_anim 4, 0, 189, 0, -24, 0, 0,
ax_anim 3, 0, 191, 0, -22, 0, 0,
ax_anim 2, 0, 191, 0, -18, 0, 0,
ax_anim 1, 0, 191, 0, -12, 0, 0,
ax_anim 2, 2, 189, 0, 0, 0, 0,
ax_anim_terminator
sVibravaAnims_11_3:
ax_anim 2, 0, 192, 0, 0, 0, 0,
ax_anim 1, 0, 193, 0, -10, 0, 0,
ax_anim 2, 0, 193, 0, -16, 0, 0,
ax_anim 3, 0, 193, 0, -18, 0, 0,
ax_anim 4, 0, 193, 0, -19, 0, 0,
ax_anim 4, 0, 192, 0, -25, 0, 0,
ax_anim 3, 0, 194, 0, -22, 0, 0,
ax_anim 2, 0, 194, 0, -18, 0, 0,
ax_anim 1, 0, 194, 0, -12, 0, 0,
ax_anim 2, 2, 192, 0, 0, 0, 0,
ax_anim_terminator
sVibravaAnims_11_4:
ax_anim 2, 0, 195, 0, 0, 0, 0,
ax_anim 1, 0, 196, 0, -10, 0, 0,
ax_anim 2, 0, 196, 0, -16, 0, 0,
ax_anim 3, 0, 196, 0, -18, 0, 0,
ax_anim 4, 0, 196, 0, -19, 0, 0,
ax_anim 4, 0, 195, 0, -24, 0, 0,
ax_anim 3, 0, 197, 0, -21, 0, 0,
ax_anim 2, 0, 197, 0, -17, 0, 0,
ax_anim 1, 0, 197, 0, -11, 0, 0,
ax_anim 2, 2, 195, 0, 0, 0, 0,
ax_anim_terminator
sVibravaAnims_11_5:
ax_anim 2, 0, 198, 0, 0, 0, 0,
ax_anim 1, 0, 199, 0, -10, 0, 0,
ax_anim 2, 0, 199, 0, -16, 0, 0,
ax_anim 3, 0, 199, 0, -18, 0, 0,
ax_anim 4, 0, 199, 0, -19, 0, 0,
ax_anim 4, 0, 198, 0, -23, 0, 0,
ax_anim 3, 0, 200, 0, -20, 0, 0,
ax_anim 2, 0, 200, 0, -16, 0, 0,
ax_anim 1, 0, 200, 0, -10, 0, 0,
ax_anim 2, 2, 198, 0, 0, 0, 0,
ax_anim_terminator
sVibravaAnims_11_6:
ax_anim 2, 0, 201, 0, 0, 0, 0,
ax_anim 1, 0, 202, 0, -10, 0, 0,
ax_anim 2, 0, 202, 0, -16, 0, 0,
ax_anim 3, 0, 202, 0, -18, 0, 0,
ax_anim 4, 0, 202, 0, -19, 0, 0,
ax_anim 4, 0, 201, 0, -24, 0, 0,
ax_anim 3, 0, 203, 0, -21, 0, 0,
ax_anim 2, 0, 203, 0, -17, 0, 0,
ax_anim 1, 0, 203, 0, -11, 0, 0,
ax_anim 2, 2, 201, 0, 0, 0, 0,
ax_anim_terminator
sVibravaAnims_11_7:
ax_anim 2, 0, 204, 0, 0, 0, 0,
ax_anim 1, 0, 205, 0, -10, 0, 0,
ax_anim 2, 0, 205, 0, -16, 0, 0,
ax_anim 3, 0, 205, 0, -18, 0, 0,
ax_anim 4, 0, 205, 0, -19, 0, 0,
ax_anim 4, 0, 204, 0, -25, 0, 0,
ax_anim 3, 0, 206, 0, -22, 0, 0,
ax_anim 2, 0, 206, 0, -18, 0, 0,
ax_anim 1, 0, 206, 0, -12, 0, 0,
ax_anim 2, 2, 204, 0, 0, 0, 0,
ax_anim_terminator
sVibravaAnims_11_8:
ax_anim 2, 0, 207, 0, 0, 0, 0,
ax_anim 1, 0, 208, 0, -10, 0, 0,
ax_anim 2, 0, 208, 0, -16, 0, 0,
ax_anim 3, 0, 208, 0, -18, 0, 0,
ax_anim 4, 0, 208, 0, -19, 0, 0,
ax_anim 4, 0, 207, 0, -24, 0, 0,
ax_anim 3, 0, 209, 0, -22, 0, 0,
ax_anim 2, 0, 209, 0, -18, 0, 0,
ax_anim 1, 0, 209, 0, -12, 0, 0,
ax_anim 2, 2, 207, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sVibravaAnims_12_1:
ax_anim 2, 0, 210, 1, 0, 1, 0,
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 2, 0, 210, 1, 0, 1, 0,
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 2, 0, 210, 1, 0, 1, 0,
ax_anim 2, 2, 210, 0, 0, 0, 0,
ax_anim 2, 0, 210, 1, 0, 1, 0,
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 2, 0, 210, 1, 0, 1, 0,
ax_anim 2, 1, 210, 0, 0, 0, 0,
ax_anim_terminator
sVibravaAnims_12_2:
ax_anim 2, 0, 217, 1, -1, 1, -1,
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 0, 217, 1, -1, 1, -1,
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 0, 217, 1, -1, 1, -1,
ax_anim 2, 2, 217, 0, 0, 0, 0,
ax_anim 2, 0, 217, 1, -1, 1, -1,
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 0, 217, 1, -1, 1, -1,
ax_anim 2, 1, 217, 0, 0, 0, 0,
ax_anim_terminator
sVibravaAnims_12_3:
ax_anim 2, 0, 216, 0, -1, 0, -1,
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, -1, 0, -1,
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, -1, 0, -1,
ax_anim 2, 2, 216, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, -1, 0, -1,
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, -1, 0, -1,
ax_anim 2, 1, 216, 0, 0, 0, 0,
ax_anim_terminator
sVibravaAnims_12_4:
ax_anim 2, 0, 215, -1, -1, -1, -1,
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 0, 215, -1, -1, -1, -1,
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 0, 215, -1, -1, -1, -1,
ax_anim 2, 2, 215, 0, 0, 0, 0,
ax_anim 2, 0, 215, -1, -1, -1, -1,
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 0, 215, -1, -1, -1, -1,
ax_anim 2, 1, 215, 0, 0, 0, 0,
ax_anim_terminator
sVibravaAnims_12_5:
ax_anim 2, 0, 214, 1, 0, 1, 0,
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 2, 0, 214, 1, 0, 1, 0,
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 2, 0, 214, 1, 0, 1, 0,
ax_anim 2, 2, 214, 0, 0, 0, 0,
ax_anim 2, 0, 214, 1, 0, 1, 0,
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 2, 0, 214, 1, 0, 1, 0,
ax_anim 2, 1, 214, 0, 0, 0, 0,
ax_anim_terminator
sVibravaAnims_12_6:
ax_anim 2, 0, 213, 1, -1, 1, -1,
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 2, 0, 213, 1, -1, 1, -1,
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 2, 0, 213, 1, -1, 1, -1,
ax_anim 2, 2, 213, 0, 0, 0, 0,
ax_anim 2, 0, 213, 1, -1, 1, -1,
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 2, 0, 213, 1, -1, 1, -1,
ax_anim 2, 1, 213, 0, 0, 0, 0,
ax_anim_terminator
sVibravaAnims_12_7:
ax_anim 2, 0, 212, 0, -1, 0, -1,
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 2, 0, 212, 0, -1, 0, -1,
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 2, 0, 212, 0, -1, 0, -1,
ax_anim 2, 2, 212, 0, 0, 0, 0,
ax_anim 2, 0, 212, 0, -1, 0, -1,
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 2, 0, 212, 0, -1, 0, -1,
ax_anim 2, 1, 212, 0, 0, 0, 0,
ax_anim_terminator
sVibravaAnims_12_8:
ax_anim 2, 0, 211, -1, -1, -1, -1,
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 2, 0, 211, -1, -1, -1, -1,
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 2, 0, 211, -1, -1, -1, -1,
ax_anim 2, 2, 211, 0, 0, 0, 0,
ax_anim 2, 0, 211, -1, -1, -1, -1,
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 2, 0, 211, -1, -1, -1, -1,
ax_anim 2, 1, 211, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sVibravaAnims_13_1:
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 2, 2, 218, 0, 0, 0, 0,
ax_anim_terminator
sVibravaAnims_13_2:
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 2, 2, 225, 0, 0, 0, 0,
ax_anim_terminator
sVibravaAnims_13_3:
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 2, 2, 224, 0, 0, 0, 0,
ax_anim_terminator
sVibravaAnims_13_4:
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 2, 223, 0, 0, 0, 0,
ax_anim_terminator
sVibravaAnims_13_5:
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 2, 222, 0, 0, 0, 0,
ax_anim_terminator
sVibravaAnims_13_6:
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 2, 221, 0, 0, 0, 0,
ax_anim_terminator
sVibravaAnims_13_7:
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 2, 220, 0, 0, 0, 0,
ax_anim_terminator
sVibravaAnims_13_8:
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 2, 219, 0, 0, 0, 0,
ax_anim_terminator
sVibravaGfx1:
.incbin "baserom.gba", 0x136E148, 0x200
sVibravaSprites1:
ax_sprite sVibravaGfx1, 0x200
ax_sprite_terminator
sVibravaGfx2:
.incbin "baserom.gba", 0x136E358, 0x200
sVibravaSprites2:
ax_sprite sVibravaGfx2, 0x200
ax_sprite_terminator
sVibravaGfx3:
.incbin "baserom.gba", 0x136E568, 0x200
sVibravaSprites3:
ax_sprite sVibravaGfx3, 0x200
ax_sprite_terminator
sVibravaGfx4:
.incbin "baserom.gba", 0x136E778, 0x200
sVibravaSprites4:
ax_sprite sVibravaGfx4, 0x200
ax_sprite_terminator
sVibravaGfx5:
.incbin "baserom.gba", 0x136E988, 0x200
sVibravaSprites5:
ax_sprite sVibravaGfx5, 0x200
ax_sprite_terminator
sVibravaGfx6:
.incbin "baserom.gba", 0x136EB98, 0x200
sVibravaSprites6:
ax_sprite sVibravaGfx6, 0x200
ax_sprite_terminator
sVibravaGfx7:
.incbin "baserom.gba", 0x136EDA8, 0x200
sVibravaSprites7:
ax_sprite sVibravaGfx7, 0x200
ax_sprite_terminator
sVibravaGfx8:
.incbin "baserom.gba", 0x136EFB8, 0x200
sVibravaSprites8:
ax_sprite sVibravaGfx8, 0x200
ax_sprite_terminator
sVibravaGfx9:
.incbin "baserom.gba", 0x136F1C8, 0x200
sVibravaSprites9:
ax_sprite sVibravaGfx9, 0x200
ax_sprite_terminator
sVibravaGfx10:
.incbin "baserom.gba", 0x136F3D8, 0x200
sVibravaSprites10:
ax_sprite sVibravaGfx10, 0x200
ax_sprite_terminator
sVibravaGfx11:
.incbin "baserom.gba", 0x136F5E8, 0x200
sVibravaSprites11:
ax_sprite sVibravaGfx11, 0x200
ax_sprite_terminator
sVibravaGfx12:
.incbin "baserom.gba", 0x136F7F8, 0x200
sVibravaSprites12:
ax_sprite sVibravaGfx12, 0x200
ax_sprite_terminator
sVibravaGfx13:
.incbin "baserom.gba", 0x136FA08, 0x200
sVibravaSprites13:
ax_sprite sVibravaGfx13, 0x200
ax_sprite_terminator
sVibravaGfx14:
.incbin "baserom.gba", 0x136FC18, 0x200
sVibravaSprites14:
ax_sprite sVibravaGfx14, 0x200
ax_sprite_terminator
sVibravaGfx15:
.incbin "baserom.gba", 0x136FE28, 0x200
sVibravaSprites15:
ax_sprite sVibravaGfx15, 0x200
ax_sprite_terminator
sVibravaGfx16:
.incbin "baserom.gba", 0x1370038, 0x160
sVibravaSprites16:
ax_sprite sVibravaGfx16, 0x160
ax_sprite 0, 0xa0
ax_sprite_terminator
sVibravaGfx17:
.incbin "baserom.gba", 0x13701B0, 0x60
sVibravaGfx17_1:
.incbin "baserom.gba", 0x1370210, 0x100
sVibravaSprites17:
ax_sprite sVibravaGfx17, 0x60
ax_sprite 0, 0x20
ax_sprite sVibravaGfx17_1, 0x100
ax_sprite 0, 0x80
ax_sprite_terminator
sVibravaGfx18:
.incbin "baserom.gba", 0x1370338, 0x60
sVibravaGfx18_1:
.incbin "baserom.gba", 0x1370398, 0x80
sVibravaGfx18_2:
.incbin "baserom.gba", 0x1370418, 0x60
sVibravaGfx18_3:
.incbin "baserom.gba", 0x1370478, 0x40
sVibravaSprites18:
ax_sprite sVibravaGfx18, 0x60
ax_sprite 0, 0x20
ax_sprite sVibravaGfx18_1, 0x80
ax_sprite 0, 0x20
ax_sprite sVibravaGfx18_2, 0x60
ax_sprite 0, 0x20
ax_sprite sVibravaGfx18_3, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sVibravaGfx19:
.incbin "baserom.gba", 0x1370500, 0x20
sVibravaGfx19_1:
.incbin "baserom.gba", 0x1370520, 0x60
sVibravaGfx19_2:
.incbin "baserom.gba", 0x1370580, 0x60
sVibravaGfx19_3:
.incbin "baserom.gba", 0x13705E0, 0x60
sVibravaSprites19:
ax_sprite 0, 0x20
ax_sprite sVibravaGfx19, 0x20
ax_sprite 0, 0x60
ax_sprite sVibravaGfx19_1, 0x60
ax_sprite 0, 0x20
ax_sprite sVibravaGfx19_2, 0x60
ax_sprite 0, 0x20
ax_sprite sVibravaGfx19_3, 0x60
ax_sprite_terminator
sVibravaGfx20:
.incbin "baserom.gba", 0x1370688, 0x40
sVibravaGfx20_1:
.incbin "baserom.gba", 0x13706C8, 0x100
sVibravaGfx20_2:
.incbin "baserom.gba", 0x13707C8, 0x40
sVibravaSprites20:
ax_sprite 0, 0x20
ax_sprite sVibravaGfx20, 0x40
ax_sprite 0, 0x20
ax_sprite sVibravaGfx20_1, 0x100
ax_sprite 0, 0x20
ax_sprite sVibravaGfx20_2, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sVibravaGfx21:
.incbin "baserom.gba", 0x1370848, 0x200
sVibravaSprites21:
ax_sprite sVibravaGfx21, 0x200
ax_sprite_terminator
sVibravaGfx22:
.incbin "baserom.gba", 0x1370A58, 0x200
sVibravaSprites22:
ax_sprite sVibravaGfx22, 0x200
ax_sprite_terminator
sVibravaGfx23:
.incbin "baserom.gba", 0x1370C68, 0x80
sVibravaSprites23:
ax_sprite sVibravaGfx23, 0x80
ax_sprite_terminator
sVibravaGfx24:
.incbin "baserom.gba", 0x1370CF8, 0x20
sVibravaSprites24:
ax_sprite sVibravaGfx24, 0x20
ax_sprite_terminator
sVibravaGfx25:
.incbin "baserom.gba", 0x1370D28, 0x20
sVibravaSprites25:
ax_sprite sVibravaGfx25, 0x20
ax_sprite_terminator
sVibravaGfx26:
.incbin "baserom.gba", 0x1370D58, 0x20
sVibravaSprites26:
ax_sprite sVibravaGfx26, 0x20
ax_sprite_terminator
sVibravaGfx27:
.incbin "baserom.gba", 0x1370D88, 0x100
sVibravaSprites27:
ax_sprite sVibravaGfx27, 0x100
ax_sprite_terminator
sVibravaGfx28:
.incbin "baserom.gba", 0x1370E98, 0x200
sVibravaSprites28:
ax_sprite sVibravaGfx28, 0x200
ax_sprite_terminator
sVibravaGfx29:
.incbin "baserom.gba", 0x13710A8, 0x200
sVibravaSprites29:
ax_sprite sVibravaGfx29, 0x200
ax_sprite_terminator
sVibravaGfx30:
.incbin "baserom.gba", 0x13712B8, 0x200
sVibravaSprites30:
ax_sprite sVibravaGfx30, 0x200
ax_sprite_terminator
sVibravaGfx31:
.incbin "baserom.gba", 0x13714C8, 0x200
sVibravaSprites31:
ax_sprite sVibravaGfx31, 0x200
ax_sprite_terminator
sAxPosesVibrava:
.4byte sVibravaPose1
.4byte sVibravaPose2
.4byte sVibravaPose3
.4byte sVibravaPose4
.4byte sVibravaPose5
.4byte sVibravaPose6
.4byte sVibravaPose7
.4byte sVibravaPose8
.4byte sVibravaPose9
.4byte sVibravaPose10
.4byte sVibravaPose11
.4byte sVibravaPose12
.4byte sVibravaPose13
.4byte sVibravaPose14
.4byte sVibravaPose15
.4byte sVibravaPose16
.4byte sVibravaPose17
.4byte sVibravaPose18
.4byte sVibravaPose19
.4byte sVibravaPose20
.4byte sVibravaPose21
.4byte sVibravaPose22
.4byte sVibravaPose23
.4byte sVibravaPose24
.4byte sVibravaPose25
.4byte sVibravaPose26
.4byte sVibravaPose27
.4byte sVibravaPose28
.4byte sVibravaPose29
.4byte sVibravaPose30
.4byte sVibravaPose31
.4byte sVibravaPose32
.4byte sVibravaPose33
.4byte sVibravaPose34
.4byte sVibravaPose35
.4byte sVibravaPose36
.4byte sVibravaPose37
.4byte sVibravaPose38
.4byte sVibravaPose39
.4byte sVibravaPose40
.4byte sVibravaPose41
.4byte sVibravaPose42
.4byte sVibravaPose43
.4byte sVibravaPose44
.4byte sVibravaPose45
.4byte sVibravaPose46
.4byte sVibravaPose47
.4byte sVibravaPose48
.4byte sVibravaPose49
.4byte sVibravaPose50
.4byte sVibravaPose51
.4byte sVibravaPose52
.4byte sVibravaPose53
.4byte sVibravaPose54
.4byte sVibravaPose55
.4byte sVibravaPose56
.4byte sVibravaPose57
.4byte sVibravaPose58
.4byte sVibravaPose59
.4byte sVibravaPose60
.4byte sVibravaPose61
.4byte sVibravaPose62
.4byte sVibravaPose63
.4byte sVibravaPose64
.4byte sVibravaPose65
.4byte sVibravaPose66
.4byte sVibravaPose67
.4byte sVibravaPose68
.4byte sVibravaPose69
.4byte sVibravaPose70
.4byte sVibravaPose71
.4byte sVibravaPose72
.4byte sVibravaPose73
.4byte sVibravaPose74
.4byte sVibravaPose75
.4byte sVibravaPose76
.4byte sVibravaPose77
.4byte sVibravaPose78
.4byte sVibravaPose79
.4byte sVibravaPose80
.4byte sVibravaPose81
.4byte sVibravaPose82
.4byte sVibravaPose83
.4byte sVibravaPose84
.4byte sVibravaPose85
.4byte sVibravaPose86
.4byte sVibravaPose87
.4byte sVibravaPose88
.4byte sVibravaPose89
.4byte sVibravaPose90
.4byte sVibravaPose91
.4byte sVibravaPose92
.4byte sVibravaPose93
.4byte sVibravaPose94
.4byte sVibravaPose95
.4byte sVibravaPose96
.4byte sVibravaPose97
.4byte sVibravaPose98
.4byte sVibravaPose99
.4byte sVibravaPose100
.4byte sVibravaPose101
.4byte sVibravaPose102
.4byte sVibravaPose103
.4byte sVibravaPose104
.4byte sVibravaPose105
.4byte sVibravaPose106
.4byte sVibravaPose107
.4byte sVibravaPose108
.4byte sVibravaPose109
.4byte sVibravaPose110
.4byte sVibravaPose111
.4byte sVibravaPose112
.4byte sVibravaPose113
.4byte sVibravaPose114
.4byte sVibravaPose115
.4byte sVibravaPose116
.4byte sVibravaPose117
.4byte sVibravaPose118
.4byte sVibravaPose119
.4byte sVibravaPose120
.4byte sVibravaPose121
.4byte sVibravaPose122
.4byte sVibravaPose123
.4byte sVibravaPose124
.4byte sVibravaPose125
.4byte sVibravaPose126
.4byte sVibravaPose127
.4byte sVibravaPose128
.4byte sVibravaPose129
.4byte sVibravaPose130
.4byte sVibravaPose131
.4byte sVibravaPose132
.4byte sVibravaPose133
.4byte sVibravaPose134
.4byte sVibravaPose135
.4byte sVibravaPose136
.4byte sVibravaPose137
.4byte sVibravaPose138
.4byte sVibravaPose139
.4byte sVibravaPose140
.4byte sVibravaPose141
.4byte sVibravaPose142
.4byte sVibravaPose143
.4byte sVibravaPose144
.4byte sVibravaPose145
.4byte sVibravaPose146
.4byte sVibravaPose147
.4byte sVibravaPose148
.4byte sVibravaPose149
.4byte sVibravaPose150
.4byte sVibravaPose151
.4byte sVibravaPose152
.4byte sVibravaPose153
.4byte sVibravaPose154
.4byte sVibravaPose155
.4byte sVibravaPose156
.4byte sVibravaPose157
.4byte sVibravaPose158
.4byte sVibravaPose159
.4byte sVibravaPose160
.4byte sVibravaPose161
.4byte sVibravaPose162
.4byte sVibravaPose163
.4byte sVibravaPose164
.4byte sVibravaPose165
.4byte sVibravaPose166
.4byte sVibravaPose167
.4byte sVibravaPose168
.4byte sVibravaPose169
.4byte sVibravaPose170
.4byte sVibravaPose171
.4byte sVibravaPose172
.4byte sVibravaPose173
.4byte sVibravaPose174
.4byte sVibravaPose175
.4byte sVibravaPose176
.4byte sVibravaPose177
.4byte sVibravaPose178
.4byte sVibravaPose179
.4byte sVibravaPose180
.4byte sVibravaPose181
.4byte sVibravaPose182
.4byte sVibravaPose183
.4byte sVibravaPose184
.4byte sVibravaPose185
.4byte sVibravaPose186
.4byte sVibravaPose187
.4byte sVibravaPose188
.4byte sVibravaPose189
.4byte sVibravaPose190
.4byte sVibravaPose191
.4byte sVibravaPose192
.4byte sVibravaPose193
.4byte sVibravaPose194
.4byte sVibravaPose195
.4byte sVibravaPose196
.4byte sVibravaPose197
.4byte sVibravaPose198
.4byte sVibravaPose199
.4byte sVibravaPose200
.4byte sVibravaPose201
.4byte sVibravaPose202
.4byte sVibravaPose203
.4byte sVibravaPose204
.4byte sVibravaPose205
.4byte sVibravaPose206
.4byte sVibravaPose207
.4byte sVibravaPose208
.4byte sVibravaPose209
.4byte sVibravaPose210
.4byte sVibravaPose211
.4byte sVibravaPose212
.4byte sVibravaPose213
.4byte sVibravaPose214
.4byte sVibravaPose215
.4byte sVibravaPose216
.4byte sVibravaPose217
.4byte sVibravaPose218
.4byte sVibravaPose219
.4byte sVibravaPose220
.4byte sVibravaPose221
.4byte sVibravaPose222
.4byte sVibravaPose223
.4byte sVibravaPose224
.4byte sVibravaPose225
.4byte sVibravaPose226
sAxPositionsVibrava:
.2byte   -1,    2, 	  -8,    0, 	   6,    0, 	  -1,   -5
.2byte   -1,   -1, 	  -8,   -1, 	   6,   -1, 	  -1,   -7
.2byte   -1,    2, 	  -8,    1, 	   6,    1, 	  -1,   -5
.2byte    7,    0, 	   6,   -5, 	  -3,    0, 	  -1,   -6
.2byte    6,   -4, 	   1,   -8, 	  -4,   -2, 	  -2,   -9
.2byte    7,   -1, 	   6,   -6, 	  -1,    1, 	   0,   -7
.2byte    6,   -2, 	   2,   -4, 	   2,    1, 	   0,   -6
.2byte    5,   -6, 	   1,   -8, 	   1,   -1, 	  -1,   -9
.2byte    6,   -4, 	   3,   -7, 	   3,    0, 	   1,   -7
.2byte    5,   -7, 	  -3,   -9, 	   5,   -3, 	  -1,   -7
.2byte    4,  -11, 	  -5,  -11, 	   5,   -6, 	  -2,   -9
.2byte    5,   -9, 	  -2,  -11, 	   6,   -6, 	  -1,  -10
.2byte   -1,  -12, 	   3,   -7, 	  -5,   -7, 	  -1,   -8
.2byte   -1,  -15, 	   4,   -9, 	  -4,   -9, 	  -1,  -10
.2byte   -1,  -14, 	   3,  -10, 	  -4,  -10, 	  -1,  -10
.2byte   -7,   -7, 	   1,   -9, 	  -7,   -3, 	  -1,   -7
.2byte   -6,  -11, 	   3,  -11, 	  -7,   -6, 	   0,   -9
.2byte   -7,   -9, 	   0,  -11, 	  -8,   -6, 	  -1,  -10
.2byte   -8,   -2, 	  -4,   -4, 	  -4,    1, 	  -2,   -6
.2byte   -7,   -6, 	  -3,   -8, 	  -3,   -1, 	  -1,   -9
.2byte   -8,   -4, 	  -5,   -7, 	  -5,    0, 	  -3,   -7
.2byte   -9,    0, 	  -8,   -5, 	   1,    0, 	  -1,   -6
.2byte   -8,   -4, 	  -3,   -8, 	   2,   -2, 	   0,   -9
.2byte   -9,   -1, 	  -8,   -6, 	  -1,    1, 	  -2,   -7
.2byte   -1,    2, 	  -8,    0, 	   6,    0, 	  -1,   -5
.2byte   -9,    0, 	  -8,   -5, 	   1,    0, 	  -1,   -6
.2byte   -8,   -2, 	  -4,   -4, 	  -4,    1, 	  -2,   -6
.2byte   -7,   -7, 	   1,   -9, 	  -7,   -3, 	  -1,   -7
.2byte   -1,  -12, 	   3,   -7, 	  -5,   -7, 	  -1,   -8
.2byte    5,   -7, 	  -3,   -9, 	   5,   -3, 	  -1,   -7
.2byte    6,   -2, 	   2,   -4, 	   2,    1, 	   0,   -6
.2byte    7,    0, 	   6,   -5, 	  -3,    0, 	  -1,   -6
.2byte   -1,    2, 	  -8,    0, 	   6,    0, 	  -1,   -5
.2byte   -1,   -1, 	  -8,   -1, 	   6,   -1, 	  -1,   -7
.2byte   -1,    2, 	  -8,    1, 	   6,    1, 	  -1,   -5
.2byte    7,    0, 	   6,   -5, 	  -3,    0, 	  -1,   -6
.2byte    6,   -4, 	   1,   -8, 	  -4,   -2, 	  -2,   -9
.2byte    7,   -1, 	   6,   -6, 	  -1,    1, 	   0,   -7
.2byte    6,   -2, 	   2,   -4, 	   2,    1, 	   0,   -6
.2byte    5,   -6, 	   1,   -8, 	   1,   -1, 	  -1,   -9
.2byte    6,   -4, 	   3,   -7, 	   3,    0, 	   1,   -7
.2byte    5,   -7, 	  -3,   -9, 	   5,   -3, 	  -1,   -7
.2byte    4,  -11, 	  -5,  -11, 	   5,   -6, 	  -2,   -9
.2byte    5,   -9, 	  -2,  -11, 	   6,   -6, 	  -1,  -10
.2byte   -1,  -12, 	   3,   -7, 	  -5,   -7, 	  -1,   -8
.2byte   -1,  -15, 	   4,   -9, 	  -4,   -9, 	  -1,  -10
.2byte   -1,  -14, 	   3,  -10, 	  -4,  -10, 	  -1,  -10
.2byte   -7,   -7, 	   1,   -9, 	  -7,   -3, 	  -1,   -7
.2byte   -6,  -11, 	   3,  -11, 	  -7,   -6, 	   0,   -9
.2byte   -7,   -9, 	   0,  -11, 	  -8,   -6, 	  -1,  -10
.2byte   -8,   -2, 	  -4,   -4, 	  -4,    1, 	  -2,   -6
.2byte   -7,   -6, 	  -3,   -8, 	  -3,   -1, 	  -1,   -9
.2byte   -8,   -4, 	  -5,   -7, 	  -5,    0, 	  -3,   -7
.2byte   -9,    0, 	  -8,   -5, 	   1,    0, 	  -1,   -6
.2byte   -8,   -4, 	  -3,   -8, 	   2,   -2, 	   0,   -9
.2byte   -9,   -1, 	  -8,   -6, 	  -1,    1, 	  -2,   -7
.2byte   -1,    2, 	  -8,    0, 	   6,    0, 	  -1,   -5
.2byte   -9,    0, 	  -8,   -5, 	   1,    0, 	  -1,   -6
.2byte   -8,   -2, 	  -4,   -4, 	  -4,    1, 	  -2,   -6
.2byte   -7,   -7, 	   1,   -9, 	  -7,   -3, 	  -1,   -7
.2byte   -1,  -12, 	   3,   -7, 	  -5,   -7, 	  -1,   -8
.2byte    5,   -7, 	  -3,   -9, 	   5,   -3, 	  -1,   -7
.2byte    6,   -2, 	   2,   -4, 	   2,    1, 	   0,   -6
.2byte    7,    0, 	   6,   -5, 	  -3,    0, 	  -1,   -6
.2byte   -1,    2, 	  -8,    0, 	   6,    0, 	  -1,   -5
.2byte   -1,   -1, 	  -8,   -1, 	   6,   -1, 	  -1,   -7
.2byte   -1,    2, 	  -8,    1, 	   6,    1, 	  -1,   -5
.2byte    7,    0, 	   6,   -5, 	  -3,    0, 	  -1,   -6
.2byte    6,   -4, 	   1,   -8, 	  -4,   -2, 	  -2,   -9
.2byte    7,   -1, 	   6,   -6, 	  -1,    1, 	   0,   -7
.2byte    6,   -2, 	   2,   -4, 	   2,    1, 	   0,   -6
.2byte    5,   -6, 	   1,   -8, 	   1,   -1, 	  -1,   -9
.2byte    6,   -4, 	   3,   -7, 	   3,    0, 	   1,   -7
.2byte    5,   -7, 	  -3,   -9, 	   5,   -3, 	  -1,   -7
.2byte    4,  -11, 	  -5,  -11, 	   5,   -6, 	  -2,   -9
.2byte    5,   -9, 	  -2,  -11, 	   6,   -6, 	  -1,  -10
.2byte   -1,  -12, 	   3,   -7, 	  -5,   -7, 	  -1,   -8
.2byte   -1,  -15, 	   4,   -9, 	  -4,   -9, 	  -1,  -10
.2byte   -1,  -14, 	   3,  -10, 	  -4,  -10, 	  -1,  -10
.2byte   -7,   -7, 	   1,   -9, 	  -7,   -3, 	  -1,   -7
.2byte   -6,  -11, 	   3,  -11, 	  -7,   -6, 	   0,   -9
.2byte   -7,   -9, 	   0,  -11, 	  -8,   -6, 	  -1,  -10
.2byte   -8,   -2, 	  -4,   -4, 	  -4,    1, 	  -2,   -6
.2byte   -7,   -6, 	  -3,   -8, 	  -3,   -1, 	  -1,   -9
.2byte   -8,   -4, 	  -5,   -7, 	  -5,    0, 	  -3,   -7
.2byte   -9,    0, 	  -8,   -5, 	   1,    0, 	  -1,   -6
.2byte   -8,   -4, 	  -3,   -8, 	   2,   -2, 	   0,   -9
.2byte   -9,   -1, 	  -8,   -6, 	  -1,    1, 	  -2,   -7
.2byte   -1,    2, 	  -8,    0, 	   6,    0, 	  -1,   -5
.2byte   -9,    0, 	  -8,   -5, 	   1,    0, 	  -1,   -6
.2byte   -8,   -2, 	  -4,   -4, 	  -4,    1, 	  -2,   -6
.2byte   -7,   -7, 	   1,   -9, 	  -7,   -3, 	  -1,   -7
.2byte   -1,  -12, 	   3,   -7, 	  -5,   -7, 	  -1,   -8
.2byte    5,   -7, 	  -3,   -9, 	   5,   -3, 	  -1,   -7
.2byte    6,   -2, 	   2,   -4, 	   2,    1, 	   0,   -6
.2byte    7,    0, 	   6,   -5, 	  -3,    0, 	  -1,   -6
.2byte   -1,    2, 	  -8,    0, 	   6,    0, 	  -1,   -5
.2byte   -1,   -1, 	  -7,    0, 	   5,    0, 	  -1,   -7
.2byte    7,    0, 	   6,   -5, 	  -3,    0, 	  -1,   -6
.2byte    4,   -4, 	   4,   -2, 	  -3,    0, 	  -2,   -7
.2byte    6,   -2, 	   2,   -4, 	   2,    1, 	   0,   -6
.2byte    6,   -7, 	   1,   -6, 	   1,    0, 	  -2,   -7
.2byte    5,   -7, 	  -3,   -9, 	   5,   -3, 	  -1,   -7
.2byte    4,  -10, 	  -5,   -9, 	   1,   -4, 	  -2,   -8
.2byte   -1,  -12, 	   3,   -7, 	  -5,   -7, 	  -1,   -8
.2byte   -1,  -10, 	   4,   -5, 	  -5,   -5, 	  -1,   -5
.2byte   -7,   -7, 	   1,   -9, 	  -7,   -3, 	  -1,   -7
.2byte   -6,  -10, 	   3,   -9, 	  -3,   -4, 	   0,   -8
.2byte   -8,   -2, 	  -4,   -4, 	  -4,    1, 	  -2,   -6
.2byte   -8,   -7, 	  -3,   -6, 	  -3,    0, 	   0,   -7
.2byte   -9,    0, 	  -8,   -5, 	   1,    0, 	  -1,   -6
.2byte   -6,   -4, 	  -6,   -2, 	   1,    0, 	   0,   -7
.2byte   -1,    2, 	  -8,    0, 	   6,    0, 	  -1,   -5
.2byte   -9,    0, 	  -8,   -5, 	   1,    0, 	  -1,   -6
.2byte   -8,   -2, 	  -4,   -4, 	  -4,    1, 	  -2,   -6
.2byte   -7,   -7, 	   1,   -9, 	  -7,   -3, 	  -1,   -7
.2byte   -1,  -12, 	   3,   -7, 	  -5,   -7, 	  -1,   -8
.2byte    5,   -7, 	  -3,   -9, 	   5,   -3, 	  -1,   -7
.2byte    6,   -2, 	   2,   -4, 	   2,    1, 	   0,   -6
.2byte    7,    0, 	   6,   -5, 	  -3,    0, 	  -1,   -6
.2byte   -1,    3, 	  -8,    0, 	   6,    0, 	  -1,   -6
.2byte   -1,    2, 	  -8,    0, 	   6,    0, 	  -1,   -7
.2byte   -1,    2, 	  -9,   -3, 	   7,   -3, 	  -1,   -6
.2byte    8,    1, 	   7,   -5, 	   0,    0, 	   1,   -6
.2byte    4,   -1, 	   3,   -3, 	   2,    0, 	   0,   -5
.2byte    5,   -5, 	   0,  -10, 	   6,   -1, 	  -1,   -5
.2byte   -1,   -8, 	   5,   -6, 	  -7,   -6, 	  -1,   -5
.2byte   -6,   -5, 	  -1,  -10, 	  -7,   -1, 	   0,   -5
.2byte   -3,   -1, 	  -2,   -3, 	  -1,    0, 	   1,   -5
.2byte   -5,    1, 	  -4,   -5, 	   3,    0, 	   2,   -6
.2byte   -1,    2, 	  -8,    0, 	   6,    0, 	  -1,   -5
.2byte   -1,   -1, 	  -8,   -1, 	   6,   -1, 	  -1,   -7
.2byte   -1,    2, 	  -8,    1, 	   6,    1, 	  -1,   -5
.2byte    7,    0, 	   6,   -5, 	  -3,    0, 	  -1,   -6
.2byte    6,   -4, 	   1,   -8, 	  -4,   -2, 	  -2,   -9
.2byte    7,   -1, 	   6,   -6, 	  -1,    1, 	   0,   -7
.2byte    6,   -2, 	   2,   -4, 	   2,    1, 	   0,   -6
.2byte    5,   -6, 	   1,   -8, 	   1,   -1, 	  -1,   -9
.2byte    6,   -4, 	   3,   -7, 	   3,    0, 	   1,   -7
.2byte    5,   -7, 	  -3,   -9, 	   5,   -3, 	  -1,   -7
.2byte    4,  -11, 	  -5,  -11, 	   5,   -6, 	  -2,   -9
.2byte    5,   -9, 	  -2,  -11, 	   6,   -6, 	  -1,  -10
.2byte   -1,  -12, 	   3,   -7, 	  -5,   -7, 	  -1,   -8
.2byte   -1,  -15, 	   4,   -9, 	  -4,   -9, 	  -1,  -10
.2byte   -1,  -14, 	   3,  -10, 	  -4,  -10, 	  -1,  -10
.2byte   -7,   -7, 	   1,   -9, 	  -7,   -3, 	  -1,   -7
.2byte   -6,  -11, 	   3,  -11, 	  -7,   -6, 	   0,   -9
.2byte   -7,   -9, 	   0,  -11, 	  -8,   -6, 	  -1,  -10
.2byte   -8,   -2, 	  -4,   -4, 	  -4,    1, 	  -2,   -6
.2byte   -7,   -6, 	  -3,   -8, 	  -3,   -1, 	  -1,   -9
.2byte   -8,   -4, 	  -5,   -7, 	  -5,    0, 	  -3,   -7
.2byte   -9,    0, 	  -8,   -5, 	   1,    0, 	  -1,   -6
.2byte   -8,   -4, 	  -3,   -8, 	   2,   -2, 	   0,   -9
.2byte   -9,   -1, 	  -8,   -6, 	  -1,    1, 	  -2,   -7
.2byte   -1,    2, 	  -8,    0, 	   6,    0, 	  -1,   -5
.2byte   -9,    0, 	  -8,   -5, 	   1,    0, 	  -1,   -6
.2byte   -8,   -2, 	  -4,   -4, 	  -4,    1, 	  -2,   -6
.2byte   -7,   -7, 	   1,   -9, 	  -7,   -3, 	  -1,   -7
.2byte   -1,  -12, 	   3,   -7, 	  -5,   -7, 	  -1,   -8
.2byte    5,   -7, 	  -3,   -9, 	   5,   -3, 	  -1,   -7
.2byte    6,   -2, 	   2,   -4, 	   2,    1, 	   0,   -6
.2byte    7,    0, 	   6,   -5, 	  -3,    0, 	  -1,   -6
.2byte   -1,   -1, 	  -8,   -1, 	   6,   -1, 	  -1,   -7
.2byte   -8,   -3, 	  -3,   -7, 	   2,   -1, 	   0,   -8
.2byte   -6,   -5, 	  -2,   -7, 	  -2,    0, 	   0,   -8
.2byte   -6,   -9, 	   3,   -9, 	  -7,   -4, 	   0,   -7
.2byte   -1,  -13, 	   4,   -7, 	  -4,   -7, 	  -1,   -8
.2byte    4,   -9, 	  -5,   -9, 	   5,   -4, 	  -2,   -7
.2byte    5,   -5, 	   1,   -7, 	   1,    0, 	  -1,   -8
.2byte    6,   -3, 	   1,   -7, 	  -4,   -1, 	  -2,   -8
.2byte   -1,    2, 	  -8,    0, 	   6,    0, 	  -1,   -5
.2byte   -9,    0, 	  -8,   -5, 	   1,    0, 	  -1,   -6
.2byte   -8,   -2, 	  -4,   -4, 	  -4,    1, 	  -2,   -6
.2byte   -7,   -7, 	   1,   -9, 	  -7,   -3, 	  -1,   -7
.2byte   -1,  -12, 	   3,   -7, 	  -5,   -7, 	  -1,   -8
.2byte    5,   -7, 	  -3,   -9, 	   5,   -3, 	  -1,   -7
.2byte    6,   -2, 	   2,   -4, 	   2,    1, 	   0,   -6
.2byte    7,    0, 	   6,   -5, 	  -3,    0, 	  -1,   -6
.2byte   -1,   -1, 	  -7,    0, 	   5,    0, 	  -1,   -7
.2byte    4,   -4, 	   4,   -2, 	  -3,    0, 	  -2,   -7
.2byte    6,   -7, 	   1,   -6, 	   1,    0, 	  -2,   -7
.2byte    4,   -9, 	  -5,   -8, 	   1,   -3, 	  -2,   -7
.2byte   -1,  -12, 	   4,   -7, 	  -5,   -7, 	  -1,   -7
.2byte   -6,   -9, 	   3,   -8, 	  -3,   -3, 	   0,   -7
.2byte   -8,   -7, 	  -3,   -6, 	  -3,    0, 	   0,   -7
.2byte   -6,   -4, 	  -6,   -2, 	   1,    0, 	   0,   -7
.2byte   -1,    2, 	  -8,    0, 	   6,    0, 	  -1,   -5
.2byte   -1,   -1, 	  -8,   -1, 	   6,   -1, 	  -1,   -7
.2byte   -1,    2, 	  -8,    1, 	   6,    1, 	  -1,   -5
.2byte    7,    0, 	   6,   -5, 	  -3,    0, 	  -1,   -6
.2byte    6,   -4, 	   1,   -8, 	  -4,   -2, 	  -2,   -9
.2byte    7,   -1, 	   6,   -6, 	  -1,    1, 	   0,   -7
.2byte    6,   -2, 	   2,   -4, 	   2,    1, 	   0,   -6
.2byte    5,   -6, 	   1,   -8, 	   1,   -1, 	  -1,   -9
.2byte    6,   -4, 	   3,   -7, 	   3,    0, 	   1,   -7
.2byte    5,   -7, 	  -3,   -9, 	   5,   -3, 	  -1,   -7
.2byte    4,  -11, 	  -5,  -11, 	   5,   -6, 	  -2,   -9
.2byte    5,   -9, 	  -2,  -11, 	   6,   -6, 	  -1,  -10
.2byte   -1,  -12, 	   3,   -7, 	  -5,   -7, 	  -1,   -8
.2byte   -1,  -15, 	   4,   -9, 	  -4,   -9, 	  -1,  -10
.2byte   -1,  -14, 	   3,  -10, 	  -4,  -10, 	  -1,  -10
.2byte   -7,   -7, 	   1,   -9, 	  -7,   -3, 	  -1,   -7
.2byte   -6,  -11, 	   3,  -11, 	  -7,   -6, 	   0,   -9
.2byte   -7,   -9, 	   0,  -11, 	  -8,   -6, 	  -1,  -10
.2byte   -8,   -2, 	  -4,   -4, 	  -4,    1, 	  -2,   -6
.2byte   -7,   -6, 	  -3,   -8, 	  -3,   -1, 	  -1,   -9
.2byte   -8,   -4, 	  -5,   -7, 	  -5,    0, 	  -3,   -7
.2byte   -9,    0, 	  -8,   -5, 	   1,    0, 	  -1,   -6
.2byte   -8,   -4, 	  -3,   -8, 	   2,   -2, 	   0,   -9
.2byte   -9,   -1, 	  -8,   -6, 	  -1,    1, 	  -2,   -7
.2byte   -1,    2, 	  -8,    1, 	   6,    1, 	  -1,   -5
.2byte   -9,   -1, 	  -8,   -6, 	  -1,    1, 	  -2,   -7
.2byte   -7,   -3, 	  -4,   -6, 	  -4,    1, 	  -2,   -6
.2byte   -6,   -7, 	   1,   -9, 	  -7,   -4, 	   0,   -8
.2byte   -1,  -11, 	   3,   -7, 	  -4,   -7, 	  -1,   -7
.2byte    5,   -7, 	  -2,   -9, 	   6,   -4, 	  -1,   -8
.2byte    6,   -3, 	   3,   -6, 	   3,    1, 	   1,   -6
.2byte    7,   -1, 	   6,   -6, 	  -1,    1, 	   0,   -7
.2byte   -1,    2, 	  -8,    0, 	   6,    0, 	  -1,   -5
.2byte   -9,    0, 	  -8,   -5, 	   1,    0, 	  -1,   -6
.2byte   -8,   -2, 	  -4,   -4, 	  -4,    1, 	  -2,   -6
.2byte   -7,   -7, 	   1,   -9, 	  -7,   -3, 	  -1,   -7
.2byte   -1,  -12, 	   3,   -7, 	  -5,   -7, 	  -1,   -8
.2byte    5,   -7, 	  -3,   -9, 	   5,   -3, 	  -1,   -7
.2byte    6,   -2, 	   2,   -4, 	   2,    1, 	   0,   -6
.2byte    7,    0, 	   6,   -5, 	  -3,    0, 	  -1,   -6
sVibravaAnimTable1:
.4byte sVibravaAnims_1_1
.4byte sVibravaAnims_1_2
.4byte sVibravaAnims_1_3
.4byte sVibravaAnims_1_4
.4byte sVibravaAnims_1_5
.4byte sVibravaAnims_1_6
.4byte sVibravaAnims_1_7
.4byte sVibravaAnims_1_8
sVibravaAnimTable2:
.4byte sVibravaAnims_2_1
.4byte sVibravaAnims_2_2
.4byte sVibravaAnims_2_3
.4byte sVibravaAnims_2_4
.4byte sVibravaAnims_2_5
.4byte sVibravaAnims_2_6
.4byte sVibravaAnims_2_7
.4byte sVibravaAnims_2_8
sVibravaAnimTable3:
.4byte sVibravaAnims_3_1
.4byte sVibravaAnims_3_2
.4byte sVibravaAnims_3_3
.4byte sVibravaAnims_3_4
.4byte sVibravaAnims_3_5
.4byte sVibravaAnims_3_6
.4byte sVibravaAnims_3_7
.4byte sVibravaAnims_3_8
sVibravaAnimTable4:
.4byte sVibravaAnims_4_1
.4byte sVibravaAnims_4_2
.4byte sVibravaAnims_4_3
.4byte sVibravaAnims_4_4
.4byte sVibravaAnims_4_5
.4byte sVibravaAnims_4_6
.4byte sVibravaAnims_4_7
.4byte sVibravaAnims_4_8
sVibravaAnimTable5:
.4byte sVibravaAnims_5_1
.4byte sVibravaAnims_5_2
.4byte sVibravaAnims_5_3
.4byte sVibravaAnims_5_4
.4byte sVibravaAnims_5_5
.4byte sVibravaAnims_5_6
.4byte sVibravaAnims_5_7
.4byte sVibravaAnims_5_8
sVibravaAnimTable6:
.4byte sVibravaAnims_6_1
.4byte sVibravaAnims_6_1
.4byte sVibravaAnims_6_1
.4byte sVibravaAnims_6_1
.4byte sVibravaAnims_6_1
.4byte sVibravaAnims_6_1
.4byte sVibravaAnims_6_1
.4byte sVibravaAnims_6_1
sVibravaAnimTable7:
.4byte sVibravaAnims_7_1
.4byte sVibravaAnims_7_2
.4byte sVibravaAnims_7_3
.4byte sVibravaAnims_7_4
.4byte sVibravaAnims_7_5
.4byte sVibravaAnims_7_6
.4byte sVibravaAnims_7_7
.4byte sVibravaAnims_7_8
sVibravaAnimTable8:
.4byte sVibravaAnims_8_1
.4byte sVibravaAnims_8_2
.4byte sVibravaAnims_8_3
.4byte sVibravaAnims_8_4
.4byte sVibravaAnims_8_5
.4byte sVibravaAnims_8_6
.4byte sVibravaAnims_8_7
.4byte sVibravaAnims_8_8
sVibravaAnimTable9:
.4byte sVibravaAnims_9_1
.4byte sVibravaAnims_9_2
.4byte sVibravaAnims_9_3
.4byte sVibravaAnims_9_4
.4byte sVibravaAnims_9_5
.4byte sVibravaAnims_9_6
.4byte sVibravaAnims_9_7
.4byte sVibravaAnims_9_8
sVibravaAnimTable10:
.4byte sVibravaAnims_10_1
.4byte sVibravaAnims_10_2
.4byte sVibravaAnims_10_3
.4byte sVibravaAnims_10_4
.4byte sVibravaAnims_10_5
.4byte sVibravaAnims_10_6
.4byte sVibravaAnims_10_7
.4byte sVibravaAnims_10_8
sVibravaAnimTable11:
.4byte sVibravaAnims_11_1
.4byte sVibravaAnims_11_2
.4byte sVibravaAnims_11_3
.4byte sVibravaAnims_11_4
.4byte sVibravaAnims_11_5
.4byte sVibravaAnims_11_6
.4byte sVibravaAnims_11_7
.4byte sVibravaAnims_11_8
sVibravaAnimTable12:
.4byte sVibravaAnims_12_1
.4byte sVibravaAnims_12_2
.4byte sVibravaAnims_12_3
.4byte sVibravaAnims_12_4
.4byte sVibravaAnims_12_5
.4byte sVibravaAnims_12_6
.4byte sVibravaAnims_12_7
.4byte sVibravaAnims_12_8
sVibravaAnimTable13:
.4byte sVibravaAnims_13_1
.4byte sVibravaAnims_13_2
.4byte sVibravaAnims_13_3
.4byte sVibravaAnims_13_4
.4byte sVibravaAnims_13_5
.4byte sVibravaAnims_13_6
.4byte sVibravaAnims_13_7
.4byte sVibravaAnims_13_8
sAxAnimationsVibrava:
.4byte sVibravaAnimTable1
.4byte sVibravaAnimTable2
.4byte sVibravaAnimTable3
.4byte sVibravaAnimTable4
.4byte sVibravaAnimTable5
.4byte sVibravaAnimTable6
.4byte sVibravaAnimTable7
.4byte sVibravaAnimTable8
.4byte sVibravaAnimTable9
.4byte sVibravaAnimTable10
.4byte sVibravaAnimTable11
.4byte sVibravaAnimTable12
.4byte sVibravaAnimTable13
sAxSpritesVibrava:
.4byte sVibravaSprites1
.4byte sVibravaSprites2
.4byte sVibravaSprites3
.4byte sVibravaSprites4
.4byte sVibravaSprites5
.4byte sVibravaSprites6
.4byte sVibravaSprites7
.4byte sVibravaSprites8
.4byte sVibravaSprites9
.4byte sVibravaSprites10
.4byte sVibravaSprites11
.4byte sVibravaSprites12
.4byte sVibravaSprites13
.4byte sVibravaSprites14
.4byte sVibravaSprites15
.4byte sVibravaSprites16
.4byte sVibravaSprites17
.4byte sVibravaSprites18
.4byte sVibravaSprites19
.4byte sVibravaSprites20
.4byte sVibravaSprites21
.4byte sVibravaSprites22
.4byte sVibravaSprites23
.4byte sVibravaSprites24
.4byte sVibravaSprites25
.4byte sVibravaSprites26
.4byte sVibravaSprites27
.4byte sVibravaSprites28
.4byte sVibravaSprites29
.4byte sVibravaSprites30
.4byte sVibravaSprites31
sAxMainVibrava:
ax_main sAxPosesVibrava, sAxAnimationsVibrava, 13, sAxSpritesVibrava, sAxPositionsVibrava
