.global gAxVolbeat
gAxVolbeat:
ax_siro sAxMainVolbeat
sVolbeatPose1:
ax_pose 0, 0x01e6, 0x80f3, 0x6c00
ax_pose_terminator
sVolbeatPose2:
ax_pose 1, 0x01e6, 0x80f3, 0x6c00
ax_pose_terminator
sVolbeatPose3:
ax_pose 2, 0x01e6, 0x80f3, 0x6c00
ax_pose_terminator
sVolbeatPose4:
ax_pose 3, 0x01e6, 0x90eb, 0x6c00
ax_pose_terminator
sVolbeatPose5:
ax_pose 4, 0x01e6, 0x90eb, 0x6c00
ax_pose_terminator
sVolbeatPose6:
ax_pose 5, 0x01e6, 0x90eb, 0x6c00
ax_pose_terminator
sVolbeatPose7:
ax_pose 6, 0x01e6, 0x90eb, 0x6c00
ax_pose_terminator
sVolbeatPose8:
ax_pose 7, 0x01e6, 0x90eb, 0x6c00
ax_pose_terminator
sVolbeatPose9:
ax_pose 8, 0x01e6, 0x90eb, 0x6c00
ax_pose_terminator
sVolbeatPose10:
ax_pose 9, 0x01e6, 0x90ea, 0x6c00
ax_pose_terminator
sVolbeatPose11:
ax_pose 10, 0x01e6, 0x90ea, 0x6c00
ax_pose_terminator
sVolbeatPose12:
ax_pose 11, 0x01e6, 0x90ea, 0x6c00
ax_pose_terminator
sVolbeatPose13:
ax_pose 12, 0x01e6, 0x80f3, 0x6c00
ax_pose_terminator
sVolbeatPose14:
ax_pose 13, 0x01e6, 0x80f3, 0x6c00
ax_pose_terminator
sVolbeatPose15:
ax_pose 14, 0x01e6, 0x80f3, 0x6c00
ax_pose_terminator
sVolbeatPose16:
ax_pose 9, 0x01e6, 0x80f5, 0x6c00
ax_pose_terminator
sVolbeatPose17:
ax_pose 10, 0x01e6, 0x80f5, 0x6c00
ax_pose_terminator
sVolbeatPose18:
ax_pose 11, 0x01e6, 0x80f5, 0x6c00
ax_pose_terminator
sVolbeatPose19:
ax_pose 6, 0x01e6, 0x80f4, 0x6c00
ax_pose_terminator
sVolbeatPose20:
ax_pose 7, 0x01e6, 0x80f4, 0x6c00
ax_pose_terminator
sVolbeatPose21:
ax_pose 8, 0x01e6, 0x80f4, 0x6c00
ax_pose_terminator
sVolbeatPose22:
ax_pose 3, 0x01e6, 0x80f4, 0x6c00
ax_pose_terminator
sVolbeatPose23:
ax_pose 4, 0x01e6, 0x80f4, 0x6c00
ax_pose_terminator
sVolbeatPose24:
ax_pose 5, 0x01e6, 0x80f4, 0x6c00
ax_pose_terminator
sVolbeatPose25:
ax_pose 0, 0x01e6, 0x80f3, 0x6c00
ax_pose_terminator
sVolbeatPose26:
ax_pose 1, 0x01e6, 0x80f3, 0x6c00
ax_pose_terminator
sVolbeatPose27:
ax_pose 2, 0x01e6, 0x80f3, 0x6c00
ax_pose_terminator
sVolbeatPose28:
ax_pose 15, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sVolbeatPose29:
ax_pose 16, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sVolbeatPose30:
ax_pose 17, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sVolbeatPose31:
ax_pose 18, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sVolbeatPose32:
ax_pose 3, 0x01e6, 0x90eb, 0x6c00
ax_pose_terminator
sVolbeatPose33:
ax_pose 4, 0x01e6, 0x90eb, 0x6c00
ax_pose_terminator
sVolbeatPose34:
ax_pose 5, 0x01e6, 0x90eb, 0x6c00
ax_pose_terminator
sVolbeatPose35:
ax_pose 19, 0x01e6, 0x90f1, 0x6c00
ax_pose_terminator
sVolbeatPose36:
ax_pose 20, 0x01e6, 0x90f1, 0x6c00
ax_pose_terminator
sVolbeatPose37:
ax_pose 21, 0x01e6, 0x90f0, 0x6c00
ax_pose_terminator
sVolbeatPose38:
ax_pose 22, 0x01e6, 0x90f0, 0x6c00
ax_pose_terminator
sVolbeatPose39:
ax_pose 6, 0x01e6, 0x90eb, 0x6c00
ax_pose_terminator
sVolbeatPose40:
ax_pose 7, 0x01e6, 0x90eb, 0x6c00
ax_pose_terminator
sVolbeatPose41:
ax_pose 8, 0x01e6, 0x90eb, 0x6c00
ax_pose_terminator
sVolbeatPose42:
ax_pose 23, 0x01e6, 0x90f2, 0x6c00
ax_pose_terminator
sVolbeatPose43:
ax_pose 24, 0x01e6, 0x90f2, 0x6c00
ax_pose_terminator
sVolbeatPose44:
ax_pose 25, 0x01e6, 0x90f0, 0x6c00
ax_pose_terminator
sVolbeatPose45:
ax_pose 26, 0x01e6, 0x90f0, 0x6c00
ax_pose_terminator
sVolbeatPose46:
ax_pose 27, 0x01e6, 0x90f0, 0x6c00
ax_pose_terminator
sVolbeatPose47:
ax_pose 28, 0x01e6, 0x90f0, 0x6c00
ax_pose_terminator
sVolbeatPose48:
ax_pose 9, 0x01e6, 0x90ea, 0x6c00
ax_pose_terminator
sVolbeatPose49:
ax_pose 10, 0x01e6, 0x90ea, 0x6c00
ax_pose_terminator
sVolbeatPose50:
ax_pose 11, 0x01e6, 0x90ea, 0x6c00
ax_pose_terminator
sVolbeatPose51:
ax_pose 29, 0x01e6, 0x90f1, 0x6c00
ax_pose_terminator
sVolbeatPose52:
ax_pose 30, 0x01e6, 0x90f1, 0x6c00
ax_pose_terminator
sVolbeatPose53:
ax_pose 31, 0x01e6, 0x90f0, 0x6c00
ax_pose_terminator
sVolbeatPose54:
ax_pose 32, 0x01e6, 0x90f0, 0x6c00
ax_pose_terminator
sVolbeatPose55:
ax_pose 33, 0x01e6, 0x90f0, 0x6c00
ax_pose_terminator
sVolbeatPose56:
ax_pose 34, 0x01e6, 0x90f0, 0x6c00
ax_pose_terminator
sVolbeatPose57:
ax_pose 12, 0x01e6, 0x80f3, 0x6c00
ax_pose_terminator
sVolbeatPose58:
ax_pose 13, 0x01e6, 0x80f3, 0x6c00
ax_pose_terminator
sVolbeatPose59:
ax_pose 14, 0x01e6, 0x80f3, 0x6c00
ax_pose_terminator
sVolbeatPose60:
ax_pose 35, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sVolbeatPose61:
ax_pose 36, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sVolbeatPose62:
ax_pose 37, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sVolbeatPose63:
ax_pose 38, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sVolbeatPose64:
ax_pose 39, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sVolbeatPose65:
ax_pose 40, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sVolbeatPose66:
ax_pose 9, 0x01e6, 0x80f5, 0x6c00
ax_pose_terminator
sVolbeatPose67:
ax_pose 10, 0x01e6, 0x80f5, 0x6c00
ax_pose_terminator
sVolbeatPose68:
ax_pose 11, 0x01e6, 0x80f5, 0x6c00
ax_pose_terminator
sVolbeatPose69:
ax_pose 29, 0x01e6, 0x80ee, 0x6c00
ax_pose_terminator
sVolbeatPose70:
ax_pose 30, 0x01e6, 0x80ee, 0x6c00
ax_pose_terminator
sVolbeatPose71:
ax_pose 31, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sVolbeatPose72:
ax_pose 32, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sVolbeatPose73:
ax_pose 33, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sVolbeatPose74:
ax_pose 34, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sVolbeatPose75:
ax_pose 6, 0x01e6, 0x80f4, 0x6c00
ax_pose_terminator
sVolbeatPose76:
ax_pose 7, 0x01e6, 0x80f4, 0x6c00
ax_pose_terminator
sVolbeatPose77:
ax_pose 8, 0x01e6, 0x80f4, 0x6c00
ax_pose_terminator
sVolbeatPose78:
ax_pose 23, 0x01e6, 0x80ed, 0x6c00
ax_pose_terminator
sVolbeatPose79:
ax_pose 24, 0x01e6, 0x80ed, 0x6c00
ax_pose_terminator
sVolbeatPose80:
ax_pose 25, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sVolbeatPose81:
ax_pose 26, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sVolbeatPose82:
ax_pose 27, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sVolbeatPose83:
ax_pose 28, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sVolbeatPose84:
ax_pose 3, 0x01e6, 0x80f4, 0x6c00
ax_pose_terminator
sVolbeatPose85:
ax_pose 4, 0x01e6, 0x80f4, 0x6c00
ax_pose_terminator
sVolbeatPose86:
ax_pose 5, 0x01e6, 0x80f4, 0x6c00
ax_pose_terminator
sVolbeatPose87:
ax_pose 19, 0x01e6, 0x80ee, 0x6c00
ax_pose_terminator
sVolbeatPose88:
ax_pose 20, 0x01e6, 0x80ee, 0x6c00
ax_pose_terminator
sVolbeatPose89:
ax_pose 21, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sVolbeatPose90:
ax_pose 22, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sVolbeatPose91:
ax_pose 0, 0x01e6, 0x80f3, 0x6c00
ax_pose_terminator
sVolbeatPose92:
ax_pose 1, 0x01e6, 0x80f3, 0x6c00
ax_pose_terminator
sVolbeatPose93:
ax_pose 2, 0x01e6, 0x80f3, 0x6c00
ax_pose_terminator
sVolbeatPose94:
ax_pose 15, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sVolbeatPose95:
ax_pose 16, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sVolbeatPose96:
ax_pose 17, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sVolbeatPose97:
ax_pose 18, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sVolbeatPose98:
ax_pose 3, 0x01e6, 0x90eb, 0x6c00
ax_pose_terminator
sVolbeatPose99:
ax_pose 4, 0x01e6, 0x90eb, 0x6c00
ax_pose_terminator
sVolbeatPose100:
ax_pose 5, 0x01e6, 0x90eb, 0x6c00
ax_pose_terminator
sVolbeatPose101:
ax_pose 19, 0x01e6, 0x90f1, 0x6c00
ax_pose_terminator
sVolbeatPose102:
ax_pose 20, 0x01e6, 0x90f1, 0x6c00
ax_pose_terminator
sVolbeatPose103:
ax_pose 21, 0x01e6, 0x90f0, 0x6c00
ax_pose_terminator
sVolbeatPose104:
ax_pose 22, 0x01e6, 0x90f0, 0x6c00
ax_pose_terminator
sVolbeatPose105:
ax_pose 6, 0x01e6, 0x90eb, 0x6c00
ax_pose_terminator
sVolbeatPose106:
ax_pose 7, 0x01e6, 0x90eb, 0x6c00
ax_pose_terminator
sVolbeatPose107:
ax_pose 8, 0x01e6, 0x90eb, 0x6c00
ax_pose_terminator
sVolbeatPose108:
ax_pose 23, 0x01e6, 0x90f2, 0x6c00
ax_pose_terminator
sVolbeatPose109:
ax_pose 24, 0x01e6, 0x90f2, 0x6c00
ax_pose_terminator
sVolbeatPose110:
ax_pose 25, 0x01e6, 0x90f0, 0x6c00
ax_pose_terminator
sVolbeatPose111:
ax_pose 26, 0x01e6, 0x90f0, 0x6c00
ax_pose_terminator
sVolbeatPose112:
ax_pose 27, 0x01e6, 0x90f0, 0x6c00
ax_pose_terminator
sVolbeatPose113:
ax_pose 28, 0x01e6, 0x90f0, 0x6c00
ax_pose_terminator
sVolbeatPose114:
ax_pose 9, 0x01e6, 0x90ea, 0x6c00
ax_pose_terminator
sVolbeatPose115:
ax_pose 10, 0x01e6, 0x90ea, 0x6c00
ax_pose_terminator
sVolbeatPose116:
ax_pose 11, 0x01e6, 0x90ea, 0x6c00
ax_pose_terminator
sVolbeatPose117:
ax_pose 29, 0x01e6, 0x90f1, 0x6c00
ax_pose_terminator
sVolbeatPose118:
ax_pose 30, 0x01e6, 0x90f1, 0x6c00
ax_pose_terminator
sVolbeatPose119:
ax_pose 31, 0x01e6, 0x90f0, 0x6c00
ax_pose_terminator
sVolbeatPose120:
ax_pose 32, 0x01e6, 0x90f0, 0x6c00
ax_pose_terminator
sVolbeatPose121:
ax_pose 33, 0x01e6, 0x90f0, 0x6c00
ax_pose_terminator
sVolbeatPose122:
ax_pose 34, 0x01e6, 0x90f0, 0x6c00
ax_pose_terminator
sVolbeatPose123:
ax_pose 12, 0x01e6, 0x80f3, 0x6c00
ax_pose_terminator
sVolbeatPose124:
ax_pose 13, 0x01e6, 0x80f3, 0x6c00
ax_pose_terminator
sVolbeatPose125:
ax_pose 14, 0x01e6, 0x80f3, 0x6c00
ax_pose_terminator
sVolbeatPose126:
ax_pose 35, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sVolbeatPose127:
ax_pose 36, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sVolbeatPose128:
ax_pose 37, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sVolbeatPose129:
ax_pose 38, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sVolbeatPose130:
ax_pose 39, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sVolbeatPose131:
ax_pose 40, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sVolbeatPose132:
ax_pose 9, 0x01e6, 0x80f5, 0x6c00
ax_pose_terminator
sVolbeatPose133:
ax_pose 10, 0x01e6, 0x80f5, 0x6c00
ax_pose_terminator
sVolbeatPose134:
ax_pose 11, 0x01e6, 0x80f5, 0x6c00
ax_pose_terminator
sVolbeatPose135:
ax_pose 29, 0x01e6, 0x80ee, 0x6c00
ax_pose_terminator
sVolbeatPose136:
ax_pose 30, 0x01e6, 0x80ee, 0x6c00
ax_pose_terminator
sVolbeatPose137:
ax_pose 31, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sVolbeatPose138:
ax_pose 32, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sVolbeatPose139:
ax_pose 33, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sVolbeatPose140:
ax_pose 34, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sVolbeatPose141:
ax_pose 6, 0x01e6, 0x80f4, 0x6c00
ax_pose_terminator
sVolbeatPose142:
ax_pose 7, 0x01e6, 0x80f4, 0x6c00
ax_pose_terminator
sVolbeatPose143:
ax_pose 8, 0x01e6, 0x80f4, 0x6c00
ax_pose_terminator
sVolbeatPose144:
ax_pose 23, 0x01e6, 0x80ed, 0x6c00
ax_pose_terminator
sVolbeatPose145:
ax_pose 24, 0x01e6, 0x80ed, 0x6c00
ax_pose_terminator
sVolbeatPose146:
ax_pose 25, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sVolbeatPose147:
ax_pose 26, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sVolbeatPose148:
ax_pose 27, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sVolbeatPose149:
ax_pose 28, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sVolbeatPose150:
ax_pose 3, 0x01e6, 0x80f4, 0x6c00
ax_pose_terminator
sVolbeatPose151:
ax_pose 4, 0x01e6, 0x80f4, 0x6c00
ax_pose_terminator
sVolbeatPose152:
ax_pose 5, 0x01e6, 0x80f4, 0x6c00
ax_pose_terminator
sVolbeatPose153:
ax_pose 19, 0x01e6, 0x80ee, 0x6c00
ax_pose_terminator
sVolbeatPose154:
ax_pose 20, 0x01e6, 0x80ee, 0x6c00
ax_pose_terminator
sVolbeatPose155:
ax_pose 21, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sVolbeatPose156:
ax_pose 22, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sVolbeatPose157:
ax_pose 1, 0x01e6, 0x80f3, 0x6c00
ax_pose_terminator
sVolbeatPose158:
ax_pose 4, 0x01e6, 0x80f4, 0x6c00
ax_pose_terminator
sVolbeatPose159:
ax_pose 7, 0x01e6, 0x80f4, 0x6c00
ax_pose_terminator
sVolbeatPose160:
ax_pose 10, 0x01e6, 0x80f5, 0x6c00
ax_pose_terminator
sVolbeatPose161:
ax_pose 13, 0x01e6, 0x80f3, 0x6c00
ax_pose_terminator
sVolbeatPose162:
ax_pose 10, 0x01e6, 0x90ea, 0x6c00
ax_pose_terminator
sVolbeatPose163:
ax_pose 7, 0x01e6, 0x90eb, 0x6c00
ax_pose_terminator
sVolbeatPose164:
ax_pose 4, 0x01e6, 0x90eb, 0x6c00
ax_pose_terminator
sVolbeatPose165:
ax_pose 0, 0x01e6, 0x80f3, 0x6c00
ax_pose_terminator
sVolbeatPose166:
ax_pose 17, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sVolbeatPose167:
ax_pose 18, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sVolbeatPose168:
ax_pose 3, 0x01e6, 0x90eb, 0x6c00
ax_pose_terminator
sVolbeatPose169:
ax_pose 21, 0x01e6, 0x90f0, 0x6c00
ax_pose_terminator
sVolbeatPose170:
ax_pose 22, 0x01e6, 0x90f0, 0x6c00
ax_pose_terminator
sVolbeatPose171:
ax_pose 6, 0x01e6, 0x90eb, 0x6c00
ax_pose_terminator
sVolbeatPose172:
ax_pose 25, 0x01e6, 0x90f0, 0x6c00
ax_pose_terminator
sVolbeatPose173:
ax_pose 26, 0x01e6, 0x90f0, 0x6c00
ax_pose_terminator
sVolbeatPose174:
ax_pose 27, 0x01e6, 0x90f0, 0x6c00
ax_pose_terminator
sVolbeatPose175:
ax_pose 28, 0x01e6, 0x90f0, 0x6c00
ax_pose_terminator
sVolbeatPose176:
ax_pose 41, 0x01fb, 0x00f8, 0x3c00
ax_pose 26, 0x01e6, 0x90f0, 0x6c01
ax_pose_terminator
sVolbeatPose177:
ax_pose 28, 0x01e6, 0x90f0, 0x6c00
ax_pose 41, 0x01fa, 0x00f7, 0x3c10
ax_pose_terminator
sVolbeatPose178:
ax_pose 9, 0x01e6, 0x90ea, 0x6c00
ax_pose_terminator
sVolbeatPose179:
ax_pose 31, 0x01e6, 0x90f0, 0x6c00
ax_pose_terminator
sVolbeatPose180:
ax_pose 32, 0x01e6, 0x90f0, 0x6c00
ax_pose_terminator
sVolbeatPose181:
ax_pose 33, 0x01e6, 0x90f0, 0x6c00
ax_pose_terminator
sVolbeatPose182:
ax_pose 34, 0x01e6, 0x90f0, 0x6c00
ax_pose_terminator
sVolbeatPose183:
ax_pose 41, 0x01fc, 0x00f9, 0x3c00
ax_pose 32, 0x01e6, 0x90f0, 0x6c01
ax_pose_terminator
sVolbeatPose184:
ax_pose 41, 0x01fb, 0x00f7, 0x3c00
ax_pose 34, 0x01e6, 0x90f0, 0x6c01
ax_pose_terminator
sVolbeatPose185:
ax_pose 12, 0x01e6, 0x80f3, 0x6c00
ax_pose_terminator
sVolbeatPose186:
ax_pose 37, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sVolbeatPose187:
ax_pose 38, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sVolbeatPose188:
ax_pose 39, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sVolbeatPose189:
ax_pose 40, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sVolbeatPose190:
ax_pose 41, 0x01fd, 0x00fb, 0x3c00
ax_pose 38, 0x01e6, 0x80ef, 0x6c01
ax_pose_terminator
sVolbeatPose191:
ax_pose 41, 0x01fd, 0x00fd, 0x3c00
ax_pose 40, 0x01e6, 0x80ef, 0x6c01
ax_pose_terminator
sVolbeatPose192:
ax_pose 9, 0x01e6, 0x80f5, 0x6c00
ax_pose_terminator
sVolbeatPose193:
ax_pose 31, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sVolbeatPose194:
ax_pose 32, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sVolbeatPose195:
ax_pose 33, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sVolbeatPose196:
ax_pose 34, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sVolbeatPose197:
ax_pose 41, 0x01fc, 0x00fe, 0x3c00
ax_pose 32, 0x01e6, 0x80ef, 0x6c01
ax_pose_terminator
sVolbeatPose198:
ax_pose 41, 0x01fa, 0x0100, 0x3c00
ax_pose 34, 0x01e6, 0x80ef, 0x6c01
ax_pose_terminator
sVolbeatPose199:
ax_pose 6, 0x01e6, 0x80f4, 0x6c00
ax_pose_terminator
sVolbeatPose200:
ax_pose 25, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sVolbeatPose201:
ax_pose 26, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sVolbeatPose202:
ax_pose 27, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sVolbeatPose203:
ax_pose 28, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sVolbeatPose204:
ax_pose 41, 0x01fb, 0x0100, 0x3c00
ax_pose 26, 0x01e6, 0x80ef, 0x6c01
ax_pose_terminator
sVolbeatPose205:
ax_pose 28, 0x01e6, 0x80ef, 0x6c00
ax_pose 41, 0x01f9, 0x0100, 0x3c10
ax_pose_terminator
sVolbeatPose206:
ax_pose 3, 0x01e6, 0x80f4, 0x6c00
ax_pose_terminator
sVolbeatPose207:
ax_pose 21, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sVolbeatPose208:
ax_pose 22, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sVolbeatPose209:
ax_pose 42, 0x01e9, 0x80f4, 0x6c00
ax_pose_terminator
sVolbeatPose210:
ax_pose 43, 0x01e9, 0x80f4, 0x6c00
ax_pose_terminator
sVolbeatPose211:
ax_pose 44, 0x81e1, 0x40f5, 0x6c00
ax_pose 45, 0x01d9, 0x00fd, 0x6c04
ax_pose 46, 0x01e1, 0x00ed, 0x6c05
ax_pose 47, 0x81e1, 0x80fd, 0x6c06
ax_pose_terminator
sVolbeatPose212:
ax_pose 48, 0x01e4, 0x90ed, 0x6c00
ax_pose_terminator
sVolbeatPose213:
ax_pose 49, 0x01e3, 0x90ea, 0x6c00
ax_pose_terminator
sVolbeatPose214:
ax_pose 50, 0x01e4, 0x90eb, 0x6c00
ax_pose_terminator
sVolbeatPose215:
ax_pose 51, 0x81e4, 0x4102, 0x6c00
ax_pose 52, 0x01e4, 0x010a, 0x6c04
ax_pose 53, 0x01dc, 0x00fa, 0x6c05
ax_pose 54, 0x81e4, 0x80f2, 0x6c06
ax_pose_terminator
sVolbeatPose216:
ax_pose 50, 0x01e4, 0x80f5, 0x6c00
ax_pose_terminator
sVolbeatPose217:
ax_pose 49, 0x01e3, 0x80f6, 0x6c00
ax_pose_terminator
sVolbeatPose218:
ax_pose 48, 0x01e4, 0x80f3, 0x6c00
ax_pose_terminator
sVolbeatPose219:
ax_pose 0, 0x01e6, 0x80f3, 0x6c00
ax_pose_terminator
sVolbeatPose220:
ax_pose 17, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sVolbeatPose221:
ax_pose 18, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sVolbeatPose222:
ax_pose 3, 0x01e6, 0x90eb, 0x6c00
ax_pose_terminator
sVolbeatPose223:
ax_pose 21, 0x01e6, 0x90f0, 0x6c00
ax_pose_terminator
sVolbeatPose224:
ax_pose 22, 0x01e6, 0x90f0, 0x6c00
ax_pose_terminator
sVolbeatPose225:
ax_pose 6, 0x01e6, 0x90eb, 0x6c00
ax_pose_terminator
sVolbeatPose226:
ax_pose 26, 0x01e6, 0x90f0, 0x6c00
ax_pose_terminator
sVolbeatPose227:
ax_pose 28, 0x01e6, 0x90f0, 0x6c00
ax_pose_terminator
sVolbeatPose228:
ax_pose 9, 0x01e6, 0x90ea, 0x6c00
ax_pose_terminator
sVolbeatPose229:
ax_pose 32, 0x01e6, 0x90f0, 0x6c00
ax_pose_terminator
sVolbeatPose230:
ax_pose 34, 0x01e6, 0x90f0, 0x6c00
ax_pose_terminator
sVolbeatPose231:
ax_pose 12, 0x01e6, 0x80f3, 0x6c00
ax_pose_terminator
sVolbeatPose232:
ax_pose 38, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sVolbeatPose233:
ax_pose 40, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sVolbeatPose234:
ax_pose 9, 0x01e6, 0x80f5, 0x6c00
ax_pose_terminator
sVolbeatPose235:
ax_pose 32, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sVolbeatPose236:
ax_pose 34, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sVolbeatPose237:
ax_pose 6, 0x01e6, 0x80f4, 0x6c00
ax_pose_terminator
sVolbeatPose238:
ax_pose 26, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sVolbeatPose239:
ax_pose 28, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sVolbeatPose240:
ax_pose 3, 0x01e6, 0x80f4, 0x6c00
ax_pose_terminator
sVolbeatPose241:
ax_pose 21, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sVolbeatPose242:
ax_pose 22, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sVolbeatPose243:
ax_pose 15, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sVolbeatPose244:
ax_pose 19, 0x01e6, 0x80ee, 0x6c00
ax_pose_terminator
sVolbeatPose245:
ax_pose 23, 0x01e6, 0x80ed, 0x6c00
ax_pose_terminator
sVolbeatPose246:
ax_pose 29, 0x01e6, 0x80ee, 0x6c00
ax_pose_terminator
sVolbeatPose247:
ax_pose 35, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sVolbeatPose248:
ax_pose 29, 0x01e6, 0x90f1, 0x6c00
ax_pose_terminator
sVolbeatPose249:
ax_pose 23, 0x01e6, 0x90f2, 0x6c00
ax_pose_terminator
sVolbeatPose250:
ax_pose 19, 0x01e6, 0x90f1, 0x6c00
ax_pose_terminator
sVolbeatPose251:
ax_pose 15, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sVolbeatPose252:
ax_pose 19, 0x01e6, 0x90f1, 0x6c00
ax_pose_terminator
sVolbeatPose253:
ax_pose 23, 0x01e6, 0x90f2, 0x6c00
ax_pose_terminator
sVolbeatPose254:
ax_pose 29, 0x01e6, 0x90f1, 0x6c00
ax_pose_terminator
sVolbeatPose255:
ax_pose 35, 0x01e6, 0x80ef, 0x6c00
ax_pose_terminator
sVolbeatPose256:
ax_pose 29, 0x01e6, 0x80ee, 0x6c00
ax_pose_terminator
sVolbeatPose257:
ax_pose 23, 0x01e6, 0x80ed, 0x6c00
ax_pose_terminator
sVolbeatPose258:
ax_pose 19, 0x01e6, 0x80ee, 0x6c00
ax_pose_terminator
sVolbeatPose259:
ax_pose 0, 0x01e6, 0x80f3, 0x6c00
ax_pose_terminator
sVolbeatPose260:
ax_pose 2, 0x01e6, 0x80f3, 0x6c00
ax_pose_terminator
sVolbeatPose261:
ax_pose 1, 0x01e6, 0x80f3, 0x6c00
ax_pose_terminator
sVolbeatPose262:
ax_pose 3, 0x01e6, 0x90eb, 0x6c00
ax_pose_terminator
sVolbeatPose263:
ax_pose 5, 0x01e6, 0x90eb, 0x6c00
ax_pose_terminator
sVolbeatPose264:
ax_pose 4, 0x01e6, 0x90eb, 0x6c00
ax_pose_terminator
sVolbeatPose265:
ax_pose 6, 0x01e6, 0x90eb, 0x6c00
ax_pose_terminator
sVolbeatPose266:
ax_pose 8, 0x01e6, 0x90eb, 0x6c00
ax_pose_terminator
sVolbeatPose267:
ax_pose 7, 0x01e6, 0x90eb, 0x6c00
ax_pose_terminator
sVolbeatPose268:
ax_pose 9, 0x01e6, 0x90ea, 0x6c00
ax_pose_terminator
sVolbeatPose269:
ax_pose 11, 0x01e6, 0x90ea, 0x6c00
ax_pose_terminator
sVolbeatPose270:
ax_pose 10, 0x01e6, 0x90ea, 0x6c00
ax_pose_terminator
sVolbeatPose271:
ax_pose 12, 0x01e6, 0x80f3, 0x6c00
ax_pose_terminator
sVolbeatPose272:
ax_pose 14, 0x01e6, 0x80f3, 0x6c00
ax_pose_terminator
sVolbeatPose273:
ax_pose 13, 0x01e6, 0x80f3, 0x6c00
ax_pose_terminator
sVolbeatPose274:
ax_pose 9, 0x01e6, 0x80f5, 0x6c00
ax_pose_terminator
sVolbeatPose275:
ax_pose 11, 0x01e6, 0x80f5, 0x6c00
ax_pose_terminator
sVolbeatPose276:
ax_pose 10, 0x01e6, 0x80f5, 0x6c00
ax_pose_terminator
sVolbeatPose277:
ax_pose 6, 0x01e6, 0x80f4, 0x6c00
ax_pose_terminator
sVolbeatPose278:
ax_pose 8, 0x01e6, 0x80f4, 0x6c00
ax_pose_terminator
sVolbeatPose279:
ax_pose 7, 0x01e6, 0x80f4, 0x6c00
ax_pose_terminator
sVolbeatPose280:
ax_pose 3, 0x01e6, 0x80f4, 0x6c00
ax_pose_terminator
sVolbeatPose281:
ax_pose 5, 0x01e6, 0x80f4, 0x6c00
ax_pose_terminator
sVolbeatPose282:
ax_pose 4, 0x01e6, 0x80f4, 0x6c00
ax_pose_terminator
sVolbeatPose283:
ax_pose 1, 0x01e6, 0x80f3, 0x6c00
ax_pose_terminator
sVolbeatPose284:
ax_pose 4, 0x01e6, 0x80f4, 0x6c00
ax_pose_terminator
sVolbeatPose285:
ax_pose 7, 0x01e6, 0x80f4, 0x6c00
ax_pose_terminator
sVolbeatPose286:
ax_pose 10, 0x01e6, 0x80f5, 0x6c00
ax_pose_terminator
sVolbeatPose287:
ax_pose 13, 0x01e6, 0x80f3, 0x6c00
ax_pose_terminator
sVolbeatPose288:
ax_pose 10, 0x01e6, 0x90ea, 0x6c00
ax_pose_terminator
sVolbeatPose289:
ax_pose 7, 0x01e6, 0x90eb, 0x6c00
ax_pose_terminator
sVolbeatPose290:
ax_pose 4, 0x01e6, 0x90eb, 0x6c00
ax_pose_terminator
sVolbeatPose291:
ax_pose 0, 0x01e6, 0x80f3, 0x6c00
ax_pose_terminator
sVolbeatPose292:
ax_pose 3, 0x01e6, 0x80f4, 0x6c00
ax_pose_terminator
sVolbeatPose293:
ax_pose 6, 0x01e6, 0x80f4, 0x6c00
ax_pose_terminator
sVolbeatPose294:
ax_pose 9, 0x01e6, 0x80f5, 0x6c00
ax_pose_terminator
sVolbeatPose295:
ax_pose 12, 0x01e6, 0x80f3, 0x6c00
ax_pose_terminator
sVolbeatPose296:
ax_pose 9, 0x01e6, 0x90eb, 0x6c00
ax_pose_terminator
sVolbeatPose297:
ax_pose 6, 0x01e6, 0x90ec, 0x6c00
ax_pose_terminator
sVolbeatPose298:
ax_pose 3, 0x01e6, 0x90ec, 0x6c00
ax_pose_terminator
.align 2
sVolbeatAnims_1_1:
ax_anim 4, 0, 0, 0, -3, 0, 0,
ax_anim 4, 0, 1, 0, -1, 0, 2,
ax_anim 4, 0, 0, 0, 0, 0, 3,
ax_anim 4, 0, 2, 0, 0, 0, 3,
ax_anim 4, 0, 0, 0, -1, 0, 2,
ax_anim 4, 0, 1, 0, -2, 0, 1,
ax_anim 4, 0, 0, 0, -3, 0, 0,
ax_anim 4, 0, 2, 0, -4, 0, -1,
ax_anim_terminator
sVolbeatAnims_1_2:
ax_anim 4, 0, 3, 0, -3, 0, 0,
ax_anim 4, 0, 4, 1, -3, 1, 1,
ax_anim 4, 0, 3, 2, -4, 2, 2,
ax_anim 4, 0, 5, 2, -5, 2, 2,
ax_anim 4, 0, 3, 1, -6, 1, 1,
ax_anim 4, 0, 4, 0, -5, 0, 0,
ax_anim 4, 0, 3, -1, -4, -1, -1,
ax_anim 4, 0, 5, -1, -3, -1, -1,
ax_anim_terminator
sVolbeatAnims_1_3:
ax_anim 4, 0, 6, 0, -3, 0, 0,
ax_anim 4, 0, 7, 1, -4, 1, 0,
ax_anim 4, 0, 6, 2, -5, 2, 0,
ax_anim 4, 0, 8, 2, -6, 2, 0,
ax_anim 4, 0, 6, 1, -6, 1, 0,
ax_anim 4, 0, 7, 0, -5, 0, 0,
ax_anim 4, 0, 6, -1, -4, -1, 0,
ax_anim 4, 0, 8, -1, -3, -1, 0,
ax_anim_terminator
sVolbeatAnims_1_4:
ax_anim 4, 0, 9, 0, -3, 0, 0,
ax_anim 4, 0, 10, 1, -4, 1, -1,
ax_anim 4, 0, 9, 2, -6, 2, -2,
ax_anim 4, 0, 11, 2, -7, 2, -2,
ax_anim 4, 0, 9, 1, -8, 1, -1,
ax_anim 4, 0, 10, 0, -7, 0, 0,
ax_anim 4, 0, 9, -1, -4, -1, 1,
ax_anim 4, 0, 11, -1, -3, -1, 1,
ax_anim_terminator
sVolbeatAnims_1_5:
ax_anim 4, 0, 12, 0, -3, 0, 0,
ax_anim 4, 0, 13, 0, -4, 0, -1,
ax_anim 4, 0, 12, 0, -6, 0, -2,
ax_anim 4, 0, 14, 0, -7, 0, -3,
ax_anim 4, 0, 12, 0, -7, 0, -3,
ax_anim 4, 0, 13, 0, -6, 0, -2,
ax_anim 4, 0, 12, 0, -4, 0, -1,
ax_anim 4, 0, 14, 0, -3, 0, 0,
ax_anim_terminator
sVolbeatAnims_1_6:
ax_anim 4, 0, 15, 0, -3, 0, 0,
ax_anim 4, 0, 16, -1, -4, -1, -1,
ax_anim 4, 0, 15, -2, -6, -2, -2,
ax_anim 4, 0, 17, -2, -7, -2, -2,
ax_anim 4, 0, 15, -1, -8, -1, -1,
ax_anim 4, 0, 16, 0, -7, 0, 0,
ax_anim 4, 0, 15, 1, -4, 1, 1,
ax_anim 4, 0, 17, 1, -3, 1, 1,
ax_anim_terminator
sVolbeatAnims_1_7:
ax_anim 4, 0, 18, 0, -3, 0, 0,
ax_anim 4, 0, 19, -1, -4, -1, 0,
ax_anim 4, 0, 18, -2, -5, -2, 0,
ax_anim 4, 0, 20, -2, -6, -2, 0,
ax_anim 4, 0, 18, -1, -6, -1, 0,
ax_anim 4, 0, 19, 0, -5, 0, 0,
ax_anim 4, 0, 18, 1, -4, 1, 0,
ax_anim 4, 0, 20, 1, -3, 1, 0,
ax_anim_terminator
sVolbeatAnims_1_8:
ax_anim 4, 0, 21, 0, -3, 0, 0,
ax_anim 4, 0, 22, -1, -3, -1, 1,
ax_anim 4, 0, 21, -2, -4, -2, 2,
ax_anim 4, 0, 23, -2, -5, -2, 2,
ax_anim 4, 0, 21, -1, -6, -1, 1,
ax_anim 4, 0, 22, 0, -5, 0, 0,
ax_anim 4, 0, 21, 1, -4, 1, -1,
ax_anim 4, 0, 23, 1, -3, 1, -1,
ax_anim_terminator
.align 2
sVolbeatAnims_2_1:
ax_anim 2, 0, 24, 0, -1, 0, 0,
ax_anim 2, 0, 26, 0, -3, 0, 0,
ax_anim 2, 0, 28, 0, -4, 0, 0,
ax_anim 2, 0, 27, 0, -4, 0, 0,
ax_anim 2, 0, 28, 0, -4, 0, 0,
ax_anim 2, 2, 27, 0, -4, 0, 0,
ax_anim 1, 0, 28, 0, 7, 0, 7,
ax_anim 1, 0, 27, 0, 14, 0, 14,
ax_anim 2, 1, 28, 0, 20, 0, 20,
ax_anim 2, 0, 27, 1, 20, 1, 20,
ax_anim 2, 0, 28, 0, 20, 0, 20,
ax_anim 2, 0, 27, 1, 20, 1, 20,
ax_anim 2, 0, 28, 0, 20, 0, 20,
ax_anim 2, 0, 27, 0, 10, 0, 10,
ax_anim 2, 0, 28, 0, 4, 0, 4,
ax_anim_terminator
sVolbeatAnims_2_2:
ax_anim 2, 0, 31, 0, -1, 0, 0,
ax_anim 2, 0, 33, 0, -2, 0, 0,
ax_anim 2, 0, 35, 0, -4, 0, 0,
ax_anim 2, 0, 34, 0, -4, 0, 0,
ax_anim 2, 0, 35, 0, -4, 0, 0,
ax_anim 2, 2, 34, 0, -4, 0, 0,
ax_anim 1, 0, 35, 7, 7, 7, 7,
ax_anim 1, 0, 34, 14, 14, 14, 14,
ax_anim 2, 1, 35, 20, 21, 20, 21,
ax_anim 2, 0, 34, 21, 20, 21, 20,
ax_anim 2, 0, 35, 20, 21, 20, 21,
ax_anim 2, 0, 34, 21, 20, 21, 20,
ax_anim 2, 0, 35, 20, 21, 20, 21,
ax_anim 2, 0, 34, 10, 10, 10, 10,
ax_anim 2, 0, 35, 4, 4, 4, 4,
ax_anim_terminator
sVolbeatAnims_2_3:
ax_anim 2, 0, 38, 0, -1, 0, 0,
ax_anim 2, 0, 40, 0, -2, 0, 0,
ax_anim 2, 0, 42, 0, -4, 0, 0,
ax_anim 2, 0, 41, 0, -4, 0, 0,
ax_anim 2, 0, 42, 0, -4, 0, 0,
ax_anim 2, 2, 41, 0, -4, 0, 0,
ax_anim 1, 0, 42, 7, -3, 7, 0,
ax_anim 1, 0, 41, 14, -2, 14, 0,
ax_anim 2, 1, 42, 19, 0, 19, 0,
ax_anim 2, 0, 41, 19, 1, 19, 1,
ax_anim 2, 0, 42, 19, 0, 19, 0,
ax_anim 2, 0, 41, 19, 1, 19, 1,
ax_anim 2, 0, 42, 19, 0, 19, 0,
ax_anim 2, 0, 41, 10, -2, 10, 0,
ax_anim 2, 0, 42, 4, -1, 4, 0,
ax_anim_terminator
sVolbeatAnims_2_4:
ax_anim 2, 0, 47, 0, -1, 0, 0,
ax_anim 2, 0, 49, 0, -2, 0, 0,
ax_anim 2, 0, 51, 0, -4, 0, 0,
ax_anim 2, 0, 50, 0, -4, 0, 0,
ax_anim 2, 0, 51, 0, -4, 0, 0,
ax_anim 2, 2, 50, 0, -4, 0, 0,
ax_anim 1, 0, 51, 7, -7, 7, -7,
ax_anim 1, 0, 50, 14, -14, 14, -14,
ax_anim 2, 1, 51, 21, -17, 20, -21,
ax_anim 2, 0, 50, 22, -16, 21, -20,
ax_anim 2, 0, 51, 21, -17, 20, -21,
ax_anim 2, 0, 50, 22, -16, 21, -20,
ax_anim 2, 0, 51, 21, -17, 20, -21,
ax_anim 2, 0, 50, 10, -10, 10, -10,
ax_anim 2, 0, 51, 4, -4, 4, -4,
ax_anim_terminator
sVolbeatAnims_2_5:
ax_anim 2, 0, 56, 0, -1, 0, 0,
ax_anim 2, 0, 58, 0, -3, 0, 0,
ax_anim 2, 0, 60, 0, -4, 0, 0,
ax_anim 2, 0, 59, 0, -4, 0, 0,
ax_anim 2, 0, 60, 0, -4, 0, 0,
ax_anim 2, 2, 59, 0, -4, 0, 0,
ax_anim 1, 0, 60, 0, -7, 0, -7,
ax_anim 1, 0, 59, 0, -13, 0, -13,
ax_anim 2, 1, 60, 0, -18, 0, -18,
ax_anim 2, 0, 59, 1, -18, 1, -18,
ax_anim 2, 0, 60, 0, -18, 0, -18,
ax_anim 2, 0, 59, 1, -18, 1, -18,
ax_anim 2, 0, 60, 0, -18, 0, -18,
ax_anim 2, 0, 59, 0, -10, 0, -10,
ax_anim 2, 0, 60, 0, -4, 0, -4,
ax_anim_terminator
sVolbeatAnims_2_6:
ax_anim 2, 0, 65, 0, -1, 0, 0,
ax_anim 2, 0, 67, 0, -2, 0, 0,
ax_anim 2, 0, 69, 0, -4, 0, 0,
ax_anim 2, 0, 68, 0, -4, 0, 0,
ax_anim 2, 0, 69, 0, -4, 0, 0,
ax_anim 2, 2, 68, 0, -4, 0, 0,
ax_anim 1, 0, 69, -7, -7, -7, -7,
ax_anim 1, 0, 68, -14, -14, -14, -14,
ax_anim 2, 1, 69, -21, -17, -20, -21,
ax_anim 2, 0, 68, -22, -16, -21, -20,
ax_anim 2, 0, 69, -21, -17, -20, -21,
ax_anim 2, 0, 68, -22, -16, -21, -20,
ax_anim 2, 0, 69, -21, -17, -20, -21,
ax_anim 2, 0, 68, -10, -10, -10, -10,
ax_anim 2, 0, 69, -4, -4, -4, -4,
ax_anim_terminator
sVolbeatAnims_2_7:
ax_anim 2, 0, 74, 0, -1, 0, 0,
ax_anim 2, 0, 76, 0, -2, 0, 0,
ax_anim 2, 0, 78, 0, -4, 0, 0,
ax_anim 2, 0, 77, 0, -4, 0, 0,
ax_anim 2, 0, 78, 0, -4, 0, 0,
ax_anim 2, 2, 77, 0, -4, 0, 0,
ax_anim 1, 0, 78, -7, -3, -7, 0,
ax_anim 1, 0, 77, -14, -2, -14, 0,
ax_anim 2, 1, 78, -19, 0, -19, 0,
ax_anim 2, 0, 77, -19, 1, -19, 1,
ax_anim 2, 0, 78, -19, 0, -19, 0,
ax_anim 2, 0, 77, -19, 1, -19, 1,
ax_anim 2, 0, 78, -19, 0, -19, 0,
ax_anim 2, 0, 77, -10, -2, -10, 0,
ax_anim 2, 0, 78, -4, -1, -4, 0,
ax_anim_terminator
sVolbeatAnims_2_8:
ax_anim 2, 0, 83, 0, -1, 0, 0,
ax_anim 2, 0, 85, 0, -2, 0, 0,
ax_anim 2, 0, 87, 0, -4, 0, 0,
ax_anim 2, 0, 86, 0, -4, 0, 0,
ax_anim 2, 0, 87, 0, -4, 0, 0,
ax_anim 2, 2, 86, 0, -4, 0, 0,
ax_anim 1, 0, 87, -7, 7, -7, 7,
ax_anim 1, 0, 86, -14, 14, -14, 14,
ax_anim 2, 1, 87, -20, 21, -20, 21,
ax_anim 2, 0, 86, -21, 20, -21, 20,
ax_anim 2, 0, 87, -20, 21, -20, 21,
ax_anim 2, 0, 86, -21, 20, -21, 20,
ax_anim 2, 0, 87, -20, 21, -20, 21,
ax_anim 2, 0, 86, -10, 10, -10, 10,
ax_anim 2, 0, 87, -4, 4, -4, 4,
ax_anim_terminator
.align 2
sVolbeatAnims_3_1:
ax_anim 2, 0, 90, 0, -1, 0, 0,
ax_anim 2, 0, 92, 0, -3, 0, 0,
ax_anim 2, 0, 94, 0, -4, 0, 0,
ax_anim 2, 0, 93, 0, -4, 0, 0,
ax_anim 2, 0, 94, 0, -4, 0, 0,
ax_anim 2, 2, 93, 0, -4, 0, 0,
ax_anim 1, 0, 94, 0, 10, 0, 10,
ax_anim 1, 0, 93, 0, 23, 0, 23,
ax_anim 2, 1, 94, 0, 44, 0, 44,
ax_anim 2, 0, 93, 1, 44, 1, 44,
ax_anim 2, 0, 94, 0, 44, 0, 44,
ax_anim 2, 0, 93, 1, 44, 1, 44,
ax_anim 2, 0, 94, 0, 44, 0, 44,
ax_anim 2, 0, 93, 0, 20, 0, 20,
ax_anim 2, 0, 94, 0, 8, 0, 8,
ax_anim_terminator
sVolbeatAnims_3_2:
ax_anim 2, 0, 97, 0, -1, 0, 0,
ax_anim 2, 0, 99, 0, -2, 0, 0,
ax_anim 2, 0, 101, 0, -4, 0, 0,
ax_anim 2, 0, 100, 0, -4, 0, 0,
ax_anim 2, 0, 101, 0, -4, 0, 0,
ax_anim 2, 2, 100, 0, -4, 0, 0,
ax_anim 1, 0, 101, 10, 10, 10, 10,
ax_anim 1, 0, 100, 23, 23, 23, 23,
ax_anim 2, 1, 101, 45, 45, 45, 45,
ax_anim 2, 0, 100, 46, 44, 46, 44,
ax_anim 2, 0, 101, 45, 45, 45, 45,
ax_anim 2, 0, 100, 46, 44, 46, 44,
ax_anim 2, 0, 101, 45, 45, 45, 45,
ax_anim 2, 0, 100, 20, 20, 20, 20,
ax_anim 2, 0, 101, 8, 8, 8, 8,
ax_anim_terminator
sVolbeatAnims_3_3:
ax_anim 2, 0, 104, 0, -1, 0, 0,
ax_anim 2, 0, 106, 0, -2, 0, 0,
ax_anim 2, 0, 108, 0, -4, 0, 0,
ax_anim 2, 0, 107, 0, -4, 0, 0,
ax_anim 2, 0, 108, 0, -4, 0, 0,
ax_anim 2, 2, 107, 0, -4, 0, 0,
ax_anim 1, 0, 108, 14, -3, 14, 0,
ax_anim 1, 0, 107, 21, -2, 21, 0,
ax_anim 2, 1, 108, 43, 0, 43, 0,
ax_anim 2, 0, 107, 43, 1, 43, 1,
ax_anim 2, 0, 108, 43, 0, 43, 0,
ax_anim 2, 0, 107, 43, 1, 43, 1,
ax_anim 2, 0, 108, 43, 0, 43, 0,
ax_anim 2, 0, 107, 22, -2, 22, 0,
ax_anim 2, 0, 108, 10, -1, 10, 0,
ax_anim_terminator
sVolbeatAnims_3_4:
ax_anim 2, 0, 113, 0, -1, 0, 0,
ax_anim 2, 0, 115, 0, -2, 0, 0,
ax_anim 2, 0, 117, 0, -4, 0, 0,
ax_anim 2, 0, 116, 0, -4, 0, 0,
ax_anim 2, 0, 117, 0, -4, 0, 0,
ax_anim 2, 2, 116, 0, -4, 0, 0,
ax_anim 1, 0, 117, 10, -10, 10, -10,
ax_anim 1, 0, 116, 21, -21, 21, -21,
ax_anim 2, 1, 117, 44, -41, 44, -41,
ax_anim 2, 0, 116, 45, -40, 45, -40,
ax_anim 2, 0, 117, 44, -41, 44, -41,
ax_anim 2, 0, 116, 45, -40, 45, -40,
ax_anim 2, 0, 117, 44, -41, 44, -41,
ax_anim 2, 0, 116, 19, -19, 19, -19,
ax_anim 2, 0, 117, 8, -8, 8, -8,
ax_anim_terminator
sVolbeatAnims_3_5:
ax_anim 2, 0, 122, 0, -1, 0, 0,
ax_anim 2, 0, 124, 0, -3, 0, 0,
ax_anim 2, 0, 126, 0, -4, 0, 0,
ax_anim 2, 0, 125, 0, -4, 0, 0,
ax_anim 2, 0, 126, 0, -4, 0, 0,
ax_anim 2, 2, 125, 0, -4, 0, 0,
ax_anim 1, 0, 126, 0, -11, 0, -11,
ax_anim 1, 0, 125, 0, -23, 0, -23,
ax_anim 2, 1, 126, 0, -42, 0, -42,
ax_anim 2, 0, 125, 1, -42, 1, -42,
ax_anim 2, 0, 126, 0, -42, 0, -42,
ax_anim 2, 0, 125, 1, -42, 1, -42,
ax_anim 2, 0, 126, 0, -42, 0, -42,
ax_anim 2, 0, 125, 0, -21, 0, -21,
ax_anim 2, 0, 126, 0, -8, 0, -8,
ax_anim_terminator
sVolbeatAnims_3_6:
ax_anim 2, 0, 131, 0, -1, 0, 0,
ax_anim 2, 0, 133, 0, -2, 0, 0,
ax_anim 2, 0, 135, 0, -4, 0, 0,
ax_anim 2, 0, 134, 0, -4, 0, 0,
ax_anim 2, 0, 135, 0, -4, 0, 0,
ax_anim 2, 2, 134, 0, -4, 0, 0,
ax_anim 1, 0, 135, -10, -10, -10, -10,
ax_anim 1, 0, 134, -21, -21, -21, -21,
ax_anim 2, 1, 135, -44, -41, -44, -41,
ax_anim 2, 0, 134, -45, -40, -45, -40,
ax_anim 2, 0, 135, -44, -41, -44, -41,
ax_anim 2, 0, 134, -45, -40, -45, -40,
ax_anim 2, 0, 135, -44, -41, -44, -41,
ax_anim 2, 0, 134, -19, -19, -19, -19,
ax_anim 2, 0, 135, -8, -8, -8, -8,
ax_anim_terminator
sVolbeatAnims_3_7:
ax_anim 2, 0, 140, 0, -1, 0, 0,
ax_anim 2, 0, 142, 0, -2, 0, 0,
ax_anim 2, 0, 144, 0, -4, 0, 0,
ax_anim 2, 0, 143, 0, -4, 0, 0,
ax_anim 2, 0, 144, 0, -4, 0, 0,
ax_anim 2, 2, 143, 0, -4, 0, 0,
ax_anim 1, 0, 144, -14, -3, -14, 0,
ax_anim 1, 0, 143, -21, -2, -21, 0,
ax_anim 2, 1, 144, -43, 0, -43, 0,
ax_anim 2, 0, 143, -43, 1, -43, 1,
ax_anim 2, 0, 144, -43, 0, -43, 0,
ax_anim 2, 0, 143, -43, 1, -43, 1,
ax_anim 2, 0, 144, -43, 0, -43, 0,
ax_anim 2, 0, 143, -22, -2, -22, 0,
ax_anim 2, 0, 144, -10, -1, -10, 0,
ax_anim_terminator
sVolbeatAnims_3_8:
ax_anim 2, 0, 149, 0, -1, 0, 0,
ax_anim 2, 0, 151, 0, -2, 0, 0,
ax_anim 2, 0, 153, 0, -4, 0, 0,
ax_anim 2, 0, 152, 0, -4, 0, 0,
ax_anim 2, 0, 153, 0, -4, 0, 0,
ax_anim 2, 2, 152, 0, -4, 0, 0,
ax_anim 1, 0, 153, -10, 10, -10, 10,
ax_anim 1, 0, 152, -23, 23, -23, 23,
ax_anim 2, 1, 153, -45, 45, -45, 45,
ax_anim 2, 0, 152, -46, 44, -46, 44,
ax_anim 2, 0, 153, -45, 45, -45, 45,
ax_anim 2, 0, 152, -46, 44, -46, 44,
ax_anim 2, 0, 153, -45, 45, -45, 45,
ax_anim 2, 0, 152, -20, 20, -20, 20,
ax_anim 2, 0, 153, -8, 8, -8, 8,
ax_anim_terminator
.align 2
sVolbeatAnims_4_1:
ax_anim 2, 0, 156, 1, 0, 1, 0,
ax_anim 2, 0, 156, 0, 0, 0, 0,
ax_anim 2, 0, 156, 1, 0, 1, 0,
ax_anim 2, 0, 156, 0, 0, 0, 0,
ax_anim 2, 0, 156, 1, 0, 1, 0,
ax_anim 2, 2, 156, 0, 0, 0, 0,
ax_anim 2, 0, 156, 1, 0, 1, 0,
ax_anim 2, 0, 156, 0, 0, 0, 0,
ax_anim 2, 0, 156, 1, 0, 1, 0,
ax_anim 2, 1, 156, 0, 0, 0, 0,
ax_anim_terminator
sVolbeatAnims_4_2:
ax_anim 2, 0, 163, 1, -1, 1, -1,
ax_anim 2, 0, 163, 0, 0, 0, 0,
ax_anim 2, 0, 163, 1, -1, 1, -1,
ax_anim 2, 0, 163, 0, 0, 0, 0,
ax_anim 2, 0, 163, 1, -1, 1, -1,
ax_anim 2, 2, 163, 0, 0, 0, 0,
ax_anim 2, 0, 163, 1, -1, 1, -1,
ax_anim 2, 0, 163, 0, 0, 0, 0,
ax_anim 2, 0, 163, 1, -1, 1, -1,
ax_anim 2, 1, 163, 0, 0, 0, 0,
ax_anim_terminator
sVolbeatAnims_4_3:
ax_anim 2, 0, 162, 0, -1, 0, -1,
ax_anim 2, 0, 162, 0, 0, 0, 0,
ax_anim 2, 0, 162, 0, -1, 0, -1,
ax_anim 2, 0, 162, 0, 0, 0, 0,
ax_anim 2, 0, 162, 0, -1, 0, -1,
ax_anim 2, 2, 162, 0, 0, 0, 0,
ax_anim 2, 0, 162, 0, -1, 0, -1,
ax_anim 2, 0, 162, 0, 0, 0, 0,
ax_anim 2, 0, 162, 0, -1, 0, -1,
ax_anim 2, 1, 162, 0, 0, 0, 0,
ax_anim_terminator
sVolbeatAnims_4_4:
ax_anim 2, 0, 161, -1, -1, -1, -1,
ax_anim 2, 0, 161, 0, 0, 0, 0,
ax_anim 2, 0, 161, -1, -1, -1, -1,
ax_anim 2, 0, 161, 0, 0, 0, 0,
ax_anim 2, 0, 161, -1, -1, -1, -1,
ax_anim 2, 2, 161, 0, 0, 0, 0,
ax_anim 2, 0, 161, -1, -1, -1, -1,
ax_anim 2, 0, 161, 0, 0, 0, 0,
ax_anim 2, 0, 161, -1, -1, -1, -1,
ax_anim 2, 1, 161, 0, 0, 0, 0,
ax_anim_terminator
sVolbeatAnims_4_5:
ax_anim 2, 0, 160, 1, 0, 1, 0,
ax_anim 2, 0, 160, 0, 0, 0, 0,
ax_anim 2, 0, 160, 1, 0, 1, 0,
ax_anim 2, 0, 160, 0, 0, 0, 0,
ax_anim 2, 0, 160, 1, 0, 1, 0,
ax_anim 2, 2, 160, 0, 0, 0, 0,
ax_anim 2, 0, 160, 1, 0, 1, 0,
ax_anim 2, 0, 160, 0, 0, 0, 0,
ax_anim 2, 0, 160, 1, 0, 1, 0,
ax_anim 2, 1, 160, 0, 0, 0, 0,
ax_anim_terminator
sVolbeatAnims_4_6:
ax_anim 2, 0, 159, 1, -1, 1, -1,
ax_anim 2, 0, 159, 0, 0, 0, 0,
ax_anim 2, 0, 159, 1, -1, 1, -1,
ax_anim 2, 0, 159, 0, 0, 0, 0,
ax_anim 2, 0, 159, 1, -1, 1, -1,
ax_anim 2, 2, 159, 0, 0, 0, 0,
ax_anim 2, 0, 159, 1, -1, 1, -1,
ax_anim 2, 0, 159, 0, 0, 0, 0,
ax_anim 2, 0, 159, 1, -1, 1, -1,
ax_anim 2, 1, 159, 0, 0, 0, 0,
ax_anim_terminator
sVolbeatAnims_4_7:
ax_anim 2, 0, 158, 0, -1, 0, -1,
ax_anim 2, 0, 158, 0, 0, 0, 0,
ax_anim 2, 0, 158, 0, -1, 0, -1,
ax_anim 2, 0, 158, 0, 0, 0, 0,
ax_anim 2, 0, 158, 0, -1, 0, -1,
ax_anim 2, 2, 158, 0, 0, 0, 0,
ax_anim 2, 0, 158, 0, -1, 0, -1,
ax_anim 2, 0, 158, 0, 0, 0, 0,
ax_anim 2, 0, 158, 0, -1, 0, -1,
ax_anim 2, 1, 158, 0, 0, 0, 0,
ax_anim_terminator
sVolbeatAnims_4_8:
ax_anim 2, 0, 157, -1, -1, -1, -1,
ax_anim 2, 0, 157, 0, 0, 0, 0,
ax_anim 2, 0, 157, -1, -1, -1, -1,
ax_anim 2, 0, 157, 0, 0, 0, 0,
ax_anim 2, 0, 157, -1, -1, -1, -1,
ax_anim 2, 2, 157, 0, 0, 0, 0,
ax_anim 2, 0, 157, -1, -1, -1, -1,
ax_anim 2, 0, 157, 0, 0, 0, 0,
ax_anim 2, 0, 157, -1, -1, -1, -1,
ax_anim 2, 1, 157, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sVolbeatAnims_5_1:
ax_anim 1, 0, 167, 0, 0, 0, 0,
ax_anim 1, 0, 170, 0, 0, 0, 0,
ax_anim 1, 0, 177, 0, 0, 0, 0,
ax_anim 2, 0, 184, 0, 0, 0, 0,
ax_anim 2, 0, 185, 0, 0, 0, 0,
ax_anim 2, 2, 186, 0, 0, 0, 0,
ax_anim 1, 0, 189, 0, 0, 0, 0,
ax_anim 2, 0, 186, 0, 0, 0, 0,
ax_anim 2, 0, 185, 0, 0, 0, 0,
ax_anim 2, 0, 184, 0, 0, 0, 0,
ax_anim 2, 1, 187, 0, 0, 0, 0,
ax_anim 2, 0, 188, 0, 0, 0, 0,
ax_anim 1, 0, 190, 0, 0, 0, 0,
ax_anim 2, 0, 188, 0, 0, 0, 0,
ax_anim 2, 0, 187, 0, 0, 0, 0,
ax_anim 2, 0, 184, 0, 0, 0, 0,
ax_anim 1, 0, 191, 0, 0, 0, 0,
ax_anim 1, 0, 198, 0, 0, 0, 0,
ax_anim 1, 0, 205, 0, 0, 0, 0,
ax_anim_terminator
sVolbeatAnims_5_2:
ax_anim 1, 0, 170, 0, 0, 0, 0,
ax_anim 1, 0, 177, 0, 0, 0, 0,
ax_anim 1, 0, 184, 0, 0, 0, 0,
ax_anim 2, 0, 191, 0, 0, 0, 0,
ax_anim 2, 0, 192, 0, 0, 0, 0,
ax_anim 2, 2, 193, 0, 0, 0, 0,
ax_anim 1, 0, 196, 0, 0, 0, 0,
ax_anim 2, 0, 193, 0, 0, 0, 0,
ax_anim 2, 0, 192, 0, 0, 0, 0,
ax_anim 2, 0, 191, 0, 0, 0, 0,
ax_anim 2, 1, 194, 0, 0, 0, 0,
ax_anim 2, 0, 195, 0, 0, 0, 0,
ax_anim 1, 0, 197, 0, 0, 0, 0,
ax_anim 2, 0, 195, 0, 0, 0, 0,
ax_anim 2, 0, 194, 0, 0, 0, 0,
ax_anim 2, 0, 191, 0, 0, 0, 0,
ax_anim 1, 0, 198, 0, 0, 0, 0,
ax_anim 1, 0, 205, 0, 0, 0, 0,
ax_anim 1, 0, 164, 0, 0, 0, 0,
ax_anim_terminator
sVolbeatAnims_5_3:
ax_anim 1, 0, 177, 0, 0, 0, 0,
ax_anim 1, 0, 184, 0, 0, 0, 0,
ax_anim 1, 0, 191, 0, 0, 0, 0,
ax_anim 2, 0, 198, 0, 0, 0, 0,
ax_anim 2, 0, 199, 0, 0, 0, 0,
ax_anim 2, 2, 200, 0, 0, 0, 0,
ax_anim 1, 0, 203, 0, 0, 0, 0,
ax_anim 2, 0, 200, 0, 0, 0, 0,
ax_anim 2, 0, 199, 0, 0, 0, 0,
ax_anim 2, 0, 198, 0, 0, 0, 0,
ax_anim 2, 1, 201, 0, 0, 0, 0,
ax_anim 2, 0, 202, 0, 0, 0, 0,
ax_anim 1, 0, 204, 0, 0, 0, 0,
ax_anim 2, 0, 202, 0, 0, 0, 0,
ax_anim 2, 0, 201, 0, 0, 0, 0,
ax_anim 2, 0, 198, 0, 0, 0, 0,
ax_anim 1, 0, 205, 0, 0, 0, 0,
ax_anim 1, 0, 164, 0, 0, 0, 0,
ax_anim 1, 0, 167, 0, 0, 0, 0,
ax_anim_terminator
sVolbeatAnims_5_4:
ax_anim 1, 0, 184, 0, 0, 0, 0,
ax_anim 1, 0, 191, 0, 0, 0, 0,
ax_anim 1, 0, 198, 0, 0, 0, 0,
ax_anim 2, 0, 205, 0, 0, 0, 0,
ax_anim 2, 0, 206, 0, 0, 0, 0,
ax_anim 2, 2, 206, 0, 0, 0, 0,
ax_anim 1, 0, 206, 0, 0, 0, 0,
ax_anim 2, 0, 206, 0, 0, 0, 0,
ax_anim 2, 0, 206, 0, 0, 0, 0,
ax_anim 2, 0, 205, 0, 0, 0, 0,
ax_anim 2, 1, 207, 0, 0, 0, 0,
ax_anim 2, 0, 207, 0, 0, 0, 0,
ax_anim 1, 0, 207, 0, 0, 0, 0,
ax_anim 2, 0, 207, 0, 0, 0, 0,
ax_anim 2, 0, 207, 0, 0, 0, 0,
ax_anim 2, 0, 205, 0, 0, 0, 0,
ax_anim 1, 0, 164, 0, 0, 0, 0,
ax_anim 1, 0, 167, 0, 0, 0, 0,
ax_anim 1, 0, 170, 0, 0, 0, 0,
ax_anim_terminator
sVolbeatAnims_5_5:
ax_anim 1, 0, 191, 0, 0, 0, 0,
ax_anim 1, 0, 198, 0, 0, 0, 0,
ax_anim 1, 0, 205, 0, 0, 0, 0,
ax_anim 2, 0, 164, 0, 0, 0, 0,
ax_anim 2, 0, 165, 0, 0, 0, 0,
ax_anim 2, 2, 165, 0, 0, 0, 0,
ax_anim 1, 0, 165, 0, 0, 0, 0,
ax_anim 2, 0, 165, 0, 0, 0, 0,
ax_anim 2, 0, 165, 0, 0, 0, 0,
ax_anim 2, 0, 164, 0, 0, 0, 0,
ax_anim 2, 1, 166, 0, 0, 0, 0,
ax_anim 2, 0, 166, 0, 0, 0, 0,
ax_anim 1, 0, 166, 0, 0, 0, 0,
ax_anim 2, 0, 166, 0, 0, 0, 0,
ax_anim 2, 0, 166, 0, 0, 0, 0,
ax_anim 2, 0, 164, 0, 0, 0, 0,
ax_anim 1, 0, 167, 0, 0, 0, 0,
ax_anim 1, 0, 170, 0, 0, 0, 0,
ax_anim 1, 0, 177, 0, 0, 0, 0,
ax_anim_terminator
sVolbeatAnims_5_6:
ax_anim 1, 0, 198, 0, 0, 0, 0,
ax_anim 1, 0, 205, 0, 0, 0, 0,
ax_anim 1, 0, 164, 0, 0, 0, 0,
ax_anim 2, 0, 167, 0, 0, 0, 0,
ax_anim 2, 0, 168, 0, 0, 0, 0,
ax_anim 2, 2, 168, 0, 0, 0, 0,
ax_anim 1, 0, 168, 0, 0, 0, 0,
ax_anim 2, 0, 168, 0, 0, 0, 0,
ax_anim 2, 0, 168, 0, 0, 0, 0,
ax_anim 2, 0, 167, 0, 0, 0, 0,
ax_anim 2, 1, 169, 0, 0, 0, 0,
ax_anim 2, 0, 169, 0, 0, 0, 0,
ax_anim 1, 0, 169, 0, 0, 0, 0,
ax_anim 2, 0, 169, 0, 0, 0, 0,
ax_anim 2, 0, 169, 0, 0, 0, 0,
ax_anim 2, 0, 167, 0, 0, 0, 0,
ax_anim 1, 0, 170, 0, 0, 0, 0,
ax_anim 1, 0, 177, 0, 0, 0, 0,
ax_anim 1, 0, 184, 0, 0, 0, 0,
ax_anim_terminator
sVolbeatAnims_5_7:
ax_anim 1, 0, 205, 0, 0, 0, 0,
ax_anim 1, 0, 164, 0, 0, 0, 0,
ax_anim 1, 0, 167, 0, 0, 0, 0,
ax_anim 2, 0, 170, 0, 0, 0, 0,
ax_anim 2, 0, 171, 0, 0, 0, 0,
ax_anim 2, 2, 172, 0, 0, 0, 0,
ax_anim 1, 0, 175, 0, 0, 0, 0,
ax_anim 2, 0, 172, 0, 0, 0, 0,
ax_anim 2, 0, 171, 0, 0, 0, 0,
ax_anim 2, 0, 170, 0, 0, 0, 0,
ax_anim 2, 1, 173, 0, 0, 0, 0,
ax_anim 2, 0, 174, 0, 0, 0, 0,
ax_anim 1, 0, 176, 0, 0, 0, 0,
ax_anim 2, 0, 174, 0, 0, 0, 0,
ax_anim 2, 0, 173, 0, 0, 0, 0,
ax_anim 2, 0, 170, 0, 0, 0, 0,
ax_anim 1, 0, 177, 0, 0, 0, 0,
ax_anim 1, 0, 184, 0, 0, 0, 0,
ax_anim 1, 0, 191, 0, 0, 0, 0,
ax_anim_terminator
sVolbeatAnims_5_8:
ax_anim 1, 0, 164, 0, 0, 0, 0,
ax_anim 1, 0, 167, 0, 0, 0, 0,
ax_anim 1, 0, 170, 0, 0, 0, 0,
ax_anim 2, 0, 177, 0, 0, 0, 0,
ax_anim 2, 0, 178, 0, 0, 0, 0,
ax_anim 2, 2, 179, 0, 0, 0, 0,
ax_anim 1, 0, 182, 0, 0, 0, 0,
ax_anim 2, 0, 179, 0, 0, 0, 0,
ax_anim 2, 0, 178, 0, 0, 0, 0,
ax_anim 2, 0, 177, 0, 0, 0, 0,
ax_anim 2, 1, 180, 0, 0, 0, 0,
ax_anim 2, 0, 181, 0, 0, 0, 0,
ax_anim 1, 0, 183, 0, 0, 0, 0,
ax_anim 2, 0, 181, 0, 0, 0, 0,
ax_anim 2, 0, 180, 0, 0, 0, 0,
ax_anim 2, 0, 177, 0, 0, 0, 0,
ax_anim 1, 0, 184, 0, 0, 0, 0,
ax_anim 1, 0, 191, 0, 0, 0, 0,
ax_anim 1, 0, 198, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sVolbeatAnims_6_1:
ax_anim 30, 0, 208, 0, 0, 0, 0,
ax_anim 35, 0, 209, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sVolbeatAnims_7_1:
ax_anim 2, 0, 210, 0, -2, 0, -2,
ax_anim 8, 0, 210, 0, -3, 0, -3,
ax_anim_terminator
sVolbeatAnims_7_2:
ax_anim 2, 0, 211, -2, -2, -2, -2,
ax_anim 8, 0, 211, -3, -3, -3, -3,
ax_anim_terminator
sVolbeatAnims_7_3:
ax_anim 2, 0, 212, -2, 0, -2, 0,
ax_anim 8, 0, 212, -3, 0, -3, 0,
ax_anim_terminator
sVolbeatAnims_7_4:
ax_anim 2, 0, 213, -2, 2, -2, 2,
ax_anim 8, 0, 213, -3, 3, -3, 3,
ax_anim_terminator
sVolbeatAnims_7_5:
ax_anim 2, 0, 214, 0, 2, 0, 2,
ax_anim 8, 0, 214, 0, 3, 0, 3,
ax_anim_terminator
sVolbeatAnims_7_6:
ax_anim 2, 0, 215, 2, 2, 2, 2,
ax_anim 8, 0, 215, 3, 3, 3, 3,
ax_anim_terminator
sVolbeatAnims_7_7:
ax_anim 2, 0, 216, 2, 0, 2, 0,
ax_anim 8, 0, 216, 3, 0, 3, 0,
ax_anim_terminator
sVolbeatAnims_7_8:
ax_anim 2, 0, 217, 2, -2, 2, -2,
ax_anim 8, 0, 217, 3, -3, 3, -3,
ax_anim_terminator
.align 2
sVolbeatAnims_8_1:
ax_anim 30, 0, 218, 0, 0, 0, 0,
ax_anim 8, 0, 219, 0, 0, 0, 0,
ax_anim 4, 0, 218, 0, 0, 0, 0,
ax_anim 8, 0, 220, 0, 0, 0, 0,
ax_anim 4, 0, 218, 0, 0, 0, 0,
ax_anim 8, 0, 219, 0, 0, 0, 0,
ax_anim 4, 0, 218, 0, 0, 0, 0,
ax_anim 8, 0, 220, 0, 0, 0, 0,
ax_anim_terminator
sVolbeatAnims_8_2:
ax_anim 30, 0, 221, 0, 0, 0, 0,
ax_anim 8, 0, 222, 0, 0, 0, 0,
ax_anim 4, 0, 221, 0, 0, 0, 0,
ax_anim 8, 0, 223, 0, 0, 0, 0,
ax_anim 4, 0, 221, 0, 0, 0, 0,
ax_anim 8, 0, 222, 0, 0, 0, 0,
ax_anim 4, 0, 221, 0, 0, 0, 0,
ax_anim 8, 0, 223, 0, 0, 0, 0,
ax_anim_terminator
sVolbeatAnims_8_3:
ax_anim 30, 0, 224, 0, 0, 0, 0,
ax_anim 8, 0, 225, 0, 0, 0, 0,
ax_anim 4, 0, 224, 0, 0, 0, 0,
ax_anim 8, 0, 226, 0, 0, 0, 0,
ax_anim 4, 0, 224, 0, 0, 0, 0,
ax_anim 8, 0, 225, 0, 0, 0, 0,
ax_anim 4, 0, 224, 0, 0, 0, 0,
ax_anim 8, 0, 226, 0, 0, 0, 0,
ax_anim_terminator
sVolbeatAnims_8_4:
ax_anim 30, 0, 227, 0, 0, 0, 0,
ax_anim 8, 0, 228, 0, 0, 0, 0,
ax_anim 4, 0, 227, 0, 0, 0, 0,
ax_anim 8, 0, 229, 0, 0, 0, 0,
ax_anim 4, 0, 227, 0, 0, 0, 0,
ax_anim 8, 0, 228, 0, 0, 0, 0,
ax_anim 4, 0, 227, 0, 0, 0, 0,
ax_anim 8, 0, 229, 0, 0, 0, 0,
ax_anim_terminator
sVolbeatAnims_8_5:
ax_anim 30, 0, 230, 0, 0, 0, 0,
ax_anim 8, 0, 231, 0, 0, 0, 0,
ax_anim 4, 0, 230, 0, 0, 0, 0,
ax_anim 8, 0, 232, 0, 0, 0, 0,
ax_anim 4, 0, 230, 0, 0, 0, 0,
ax_anim 8, 0, 231, 0, 0, 0, 0,
ax_anim 4, 0, 230, 0, 0, 0, 0,
ax_anim 8, 0, 232, 0, 0, 0, 0,
ax_anim_terminator
sVolbeatAnims_8_6:
ax_anim 30, 0, 233, 0, 0, 0, 0,
ax_anim 8, 0, 234, 0, 0, 0, 0,
ax_anim 4, 0, 233, 0, 0, 0, 0,
ax_anim 8, 0, 235, 0, 0, 0, 0,
ax_anim 4, 0, 233, 0, 0, 0, 0,
ax_anim 8, 0, 234, 0, 0, 0, 0,
ax_anim 4, 0, 233, 0, 0, 0, 0,
ax_anim 8, 0, 235, 0, 0, 0, 0,
ax_anim_terminator
sVolbeatAnims_8_7:
ax_anim 30, 0, 236, 0, 0, 0, 0,
ax_anim 8, 0, 237, 0, 0, 0, 0,
ax_anim 4, 0, 236, 0, 0, 0, 0,
ax_anim 8, 0, 238, 0, 0, 0, 0,
ax_anim 4, 0, 236, 0, 0, 0, 0,
ax_anim 8, 0, 237, 0, 0, 0, 0,
ax_anim 4, 0, 236, 0, 0, 0, 0,
ax_anim 8, 0, 238, 0, 0, 0, 0,
ax_anim_terminator
sVolbeatAnims_8_8:
ax_anim 30, 0, 239, 0, 0, 0, 0,
ax_anim 8, 0, 240, 0, 0, 0, 0,
ax_anim 4, 0, 239, 0, 0, 0, 0,
ax_anim 8, 0, 241, 0, 0, 0, 0,
ax_anim 4, 0, 239, 0, 0, 0, 0,
ax_anim 8, 0, 240, 0, 0, 0, 0,
ax_anim 4, 0, 239, 0, 0, 0, 0,
ax_anim 8, 0, 241, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sVolbeatAnims_9_1:
ax_anim 2, 0, 242, 0, 0, 0, 0,
ax_anim 1, 0, 243, 7, 4, 7, 4,
ax_anim 2, 0, 244, 10, 13, 10, 13,
ax_anim 2, 0, 245, 7, 19, 7, 19,
ax_anim 3, 0, 246, 0, 20, 0, 20,
ax_anim 2, 3, 247, -7, 19, -7, 19,
ax_anim 2, 0, 248, -10, 13, -10, 13,
ax_anim 1, 0, 249, -7, 4, -7, 4,
ax_anim 1, 0, 242, 0, 0, 0, 0,
ax_anim_terminator
sVolbeatAnims_9_2:
ax_anim 2, 0, 249, 0, 0, 0, 0,
ax_anim 1, 0, 242, 12, 3, 12, 3,
ax_anim 2, 0, 243, 20, 8, 20, 8,
ax_anim 2, 0, 244, 23, 15, 23, 15,
ax_anim 3, 0, 245, 20, 20, 20, 20,
ax_anim 2, 3, 246, 14, 19, 14, 19,
ax_anim 2, 0, 247, 7, 15, 7, 15,
ax_anim 1, 0, 248, 3, 7, 3, 7,
ax_anim 1, 0, 249, 0, 0, 0, 0,
ax_anim_terminator
sVolbeatAnims_9_3:
ax_anim 2, 0, 248, 0, 0, 0, 0,
ax_anim 1, 0, 249, 4, -2, 4, -2,
ax_anim 2, 0, 242, 11, -4, 11, -4,
ax_anim 2, 0, 243, 18, -3, 18, -3,
ax_anim 3, 0, 244, 20, 0, 20, 0,
ax_anim 2, 3, 245, 17, 4, 17, 4,
ax_anim 2, 0, 246, 12, 5, 12, 5,
ax_anim 1, 0, 247, 5, 4, 5, 4,
ax_anim 1, 0, 248, 0, 0, 0, 0,
ax_anim_terminator
sVolbeatAnims_9_4:
ax_anim 2, 0, 247, 0, 0, 0, 0,
ax_anim 1, 0, 248, 0, -8, 0, -8,
ax_anim 2, 0, 249, 5, -16, 5, -16,
ax_anim 2, 0, 242, 13, -21, 13, -21,
ax_anim 3, 0, 243, 22, -20, 22, -20,
ax_anim 2, 3, 244, 24, -14, 24, -14,
ax_anim 2, 0, 245, 19, -5, 19, -5,
ax_anim 1, 0, 246, 9, -1, 9, -1,
ax_anim 1, 0, 247, 0, 0, 0, 0,
ax_anim_terminator
sVolbeatAnims_9_5:
ax_anim 2, 0, 246, 0, 0, 0, 0,
ax_anim 1, 0, 247, -8, -4, -8, -4,
ax_anim 2, 0, 248, -11, -10, -11, -10,
ax_anim 2, 0, 249, -8, -19, -8, -19,
ax_anim 3, 0, 242, 0, -21, 0, -21,
ax_anim 2, 3, 243, 8, -19, 8, -19,
ax_anim 2, 0, 244, 11, -10, 11, -10,
ax_anim 1, 0, 245, 8, -4, 8, -4,
ax_anim 1, 0, 246, 0, 0, 0, 0,
ax_anim_terminator
sVolbeatAnims_9_6:
ax_anim 2, 0, 245, 0, 0, 0, 0,
ax_anim 1, 0, 244, 0, -8, 0, -8,
ax_anim 2, 0, 243, -5, -16, -5, -16,
ax_anim 2, 0, 242, -13, -21, -13, -21,
ax_anim 3, 0, 249, -22, -20, -22, -20,
ax_anim 2, 3, 248, -24, -14, -24, -14,
ax_anim 2, 0, 247, -19, -5, -19, -5,
ax_anim 1, 0, 246, -9, -1, -9, -1,
ax_anim 1, 0, 245, 0, 0, 0, 0,
ax_anim_terminator
sVolbeatAnims_9_7:
ax_anim 2, 0, 244, 0, 0, 0, 0,
ax_anim 1, 0, 243, -4, -2, -4, -2,
ax_anim 2, 0, 242, -11, -4, -11, -4,
ax_anim 2, 0, 249, -18, -3, -18, -3,
ax_anim 3, 0, 248, -20, 0, -20, 0,
ax_anim 2, 3, 247, -17, 4, -17, 4,
ax_anim 2, 0, 246, -12, 5, -12, 5,
ax_anim 1, 0, 245, -5, 4, -5, 4,
ax_anim 1, 0, 244, 0, 0, 0, 0,
ax_anim_terminator
sVolbeatAnims_9_8:
ax_anim 2, 0, 243, 0, 0, 0, 0,
ax_anim 1, 0, 242, -12, 3, -12, 3,
ax_anim 2, 0, 249, -20, 8, -20, 8,
ax_anim 2, 0, 248, -23, 15, -23, 15,
ax_anim 3, 0, 247, -20, 20, -20, 20,
ax_anim 2, 3, 246, -14, 20, -14, 20,
ax_anim 2, 0, 245, -7, 15, -7, 15,
ax_anim 1, 0, 244, -3, 7, -3, 7,
ax_anim 1, 0, 243, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sVolbeatAnims_10_1:
ax_anim 2, 0, 250, 0, 0, 0, 0,
ax_anim 2, 0, 250, 6, 0, 6, 0,
ax_anim 2, 0, 250, -6, 0, -6, 0,
ax_anim 2, 0, 250, 10, 0, 10, 0,
ax_anim 2, 0, 250, -10, 0, -10, 0,
ax_anim 2, 0, 250, 12, 0, 12, 0,
ax_anim 3, 0, 250, -12, 0, -12, 0,
ax_anim 3, 0, 250, 13, 0, 13, 0,
ax_anim 3, 0, 250, -13, 0, -13, 0,
ax_anim 2, 0, 250, 12, 0, 12, 0,
ax_anim 3, 0, 250, -12, 0, -12, 0,
ax_anim 2, 0, 250, 10, 0, 10, 0,
ax_anim 2, 0, 250, -10, 0, -10, 0,
ax_anim 2, 0, 250, 6, 0, 6, 0,
ax_anim 2, 0, 250, -6, 0, -6, 0,
ax_anim 2, 0, 250, 0, 0, 0, 0,
ax_anim_terminator
sVolbeatAnims_10_2:
ax_anim 2, 0, 251, 0, 0, 0, 0,
ax_anim 2, 0, 251, 6, -6, 6, -6,
ax_anim 2, 0, 251, -6, 6, -6, 6,
ax_anim 2, 0, 251, 10, -10, 10, -10,
ax_anim 2, 0, 251, -10, 10, -10, 10,
ax_anim 2, 0, 251, 12, -12, 12, -12,
ax_anim 3, 0, 251, -12, 12, -12, 12,
ax_anim 3, 0, 251, 13, -13, 13, -13,
ax_anim 3, 0, 251, -13, 13, -13, 13,
ax_anim 2, 0, 251, 12, -12, 12, -12,
ax_anim 3, 0, 251, -12, 12, -12, 12,
ax_anim 2, 0, 251, 10, -10, 10, -10,
ax_anim 2, 0, 251, -10, 10, -10, 10,
ax_anim 2, 0, 251, 6, -6, 6, -6,
ax_anim 2, 0, 251, -6, 6, -6, 6,
ax_anim 2, 0, 251, 0, 0, 0, 0,
ax_anim_terminator
sVolbeatAnims_10_3:
ax_anim 2, 0, 252, 0, 0, 0, 0,
ax_anim 2, 0, 252, 0, -6, 0, -6,
ax_anim 2, 0, 252, 0, 6, 0, 6,
ax_anim 2, 0, 252, 0, -10, 0, -10,
ax_anim 2, 0, 252, 0, 10, 0, 10,
ax_anim 2, 0, 252, 0, -12, 0, -12,
ax_anim 3, 0, 252, 0, 12, 0, 12,
ax_anim 3, 0, 252, 0, -13, 0, -13,
ax_anim 3, 0, 252, 0, 13, 0, 13,
ax_anim 2, 0, 252, 0, -12, 0, -12,
ax_anim 3, 0, 252, 0, 12, 0, 12,
ax_anim 2, 0, 252, 0, -10, 0, -10,
ax_anim 2, 0, 252, 0, 10, 0, 10,
ax_anim 2, 0, 252, 0, -6, 0, -6,
ax_anim 2, 0, 252, 0, 6, 0, 6,
ax_anim 2, 0, 252, 0, 0, 0, 0,
ax_anim_terminator
sVolbeatAnims_10_4:
ax_anim 2, 0, 253, 0, 0, 0, 0,
ax_anim 2, 0, 253, -6, -6, -6, -6,
ax_anim 2, 0, 253, 6, 6, 6, 6,
ax_anim 2, 0, 253, -10, -10, -10, -10,
ax_anim 2, 0, 253, 10, 10, 10, 10,
ax_anim 2, 0, 253, -12, -12, -12, -12,
ax_anim 3, 0, 253, 12, 12, 12, 12,
ax_anim 3, 0, 253, -13, -13, -13, -13,
ax_anim 3, 0, 253, 13, 13, 13, 13,
ax_anim 2, 0, 253, -12, -12, -12, -12,
ax_anim 3, 0, 253, 12, 12, 12, 12,
ax_anim 2, 0, 253, -10, -10, -10, -10,
ax_anim 2, 0, 253, 10, 10, 10, 10,
ax_anim 2, 0, 253, -6, -6, -6, -6,
ax_anim 2, 0, 253, 6, 6, 6, 6,
ax_anim 2, 0, 253, 0, 0, 0, 0,
ax_anim_terminator
sVolbeatAnims_10_5:
ax_anim 2, 0, 254, 0, 0, 0, 0,
ax_anim 2, 0, 254, 6, 0, 6, 0,
ax_anim 2, 0, 254, -6, 0, -6, 0,
ax_anim 2, 0, 254, 10, 0, 10, 0,
ax_anim 2, 0, 254, -10, 0, -10, 0,
ax_anim 2, 0, 254, 12, 0, 12, 0,
ax_anim 3, 0, 254, -12, 0, -12, 0,
ax_anim 3, 0, 254, 13, 0, 13, 0,
ax_anim 3, 0, 254, -13, 0, -13, 0,
ax_anim 2, 0, 254, 12, 0, 12, 0,
ax_anim 3, 0, 254, -12, 0, -12, 0,
ax_anim 2, 0, 254, 10, 0, 10, 0,
ax_anim 2, 0, 254, -10, 0, -10, 0,
ax_anim 2, 0, 254, 6, 0, 6, 0,
ax_anim 2, 0, 254, -6, 0, -6, 0,
ax_anim 2, 0, 254, 0, 0, 0, 0,
ax_anim_terminator
sVolbeatAnims_10_6:
ax_anim 2, 0, 255, 0, 0, 0, 0,
ax_anim 2, 0, 255, 6, -6, 6, -6,
ax_anim 2, 0, 255, -6, 6, -6, 6,
ax_anim 2, 0, 255, 10, -10, 10, -10,
ax_anim 2, 0, 255, -10, 10, -10, 10,
ax_anim 2, 0, 255, 12, -12, 12, -12,
ax_anim 3, 0, 255, -12, 12, -12, 12,
ax_anim 3, 0, 255, 13, -13, 13, -13,
ax_anim 3, 0, 255, -13, 13, -13, 13,
ax_anim 2, 0, 255, 12, -12, 12, -12,
ax_anim 3, 0, 255, -12, 12, -12, 12,
ax_anim 2, 0, 255, 10, -10, 10, -10,
ax_anim 2, 0, 255, -10, 10, -10, 10,
ax_anim 2, 0, 255, 6, -6, 6, -6,
ax_anim 2, 0, 255, -6, 6, -6, 6,
ax_anim 2, 0, 255, 0, 0, 0, 0,
ax_anim_terminator
sVolbeatAnims_10_7:
ax_anim 2, 0, 256, 0, 0, 0, 0,
ax_anim 2, 0, 256, 0, -6, 0, -6,
ax_anim 2, 0, 256, 0, 6, 0, 6,
ax_anim 2, 0, 256, 0, -10, 0, -10,
ax_anim 2, 0, 256, 0, 10, 0, 10,
ax_anim 2, 0, 256, 0, -12, 0, -12,
ax_anim 3, 0, 256, 0, 12, 0, 12,
ax_anim 3, 0, 256, 0, -13, 0, -13,
ax_anim 3, 0, 256, 0, 13, 0, 13,
ax_anim 2, 0, 256, 0, -12, 0, -12,
ax_anim 3, 0, 256, 0, 12, 0, 12,
ax_anim 2, 0, 256, 0, -10, 0, -10,
ax_anim 2, 0, 256, 0, 10, 0, 10,
ax_anim 2, 0, 256, 0, -6, 0, -6,
ax_anim 2, 0, 256, 0, 6, 0, 6,
ax_anim 2, 0, 256, 0, 0, 0, 0,
ax_anim_terminator
sVolbeatAnims_10_8:
ax_anim 2, 0, 257, 0, 0, 0, 0,
ax_anim 2, 0, 257, -6, -6, -6, -6,
ax_anim 2, 0, 257, 6, 6, 6, 6,
ax_anim 2, 0, 257, -10, -10, -10, -10,
ax_anim 2, 0, 257, 10, 10, 10, 10,
ax_anim 2, 0, 257, -12, -12, -12, -12,
ax_anim 3, 0, 257, 12, 12, 12, 12,
ax_anim 3, 0, 257, -13, -13, -13, -13,
ax_anim 3, 0, 257, 13, 13, 13, 13,
ax_anim 2, 0, 257, -12, -12, -12, -12,
ax_anim 3, 0, 257, 12, 12, 12, 12,
ax_anim 2, 0, 257, -10, -10, -10, -10,
ax_anim 2, 0, 257, 10, 10, 10, 10,
ax_anim 2, 0, 257, -6, -6, -6, -6,
ax_anim 2, 0, 257, 6, 6, 6, 6,
ax_anim 2, 0, 257, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sVolbeatAnims_11_1:
ax_anim 2, 0, 258, 0, 0, 0, 0,
ax_anim 1, 0, 259, 0, -10, 0, 0,
ax_anim 2, 0, 259, 0, -16, 0, 0,
ax_anim 3, 0, 259, 0, -20, 0, 0,
ax_anim 4, 0, 259, 0, -22, 0, 0,
ax_anim 4, 0, 258, 0, -23, 0, 0,
ax_anim 3, 0, 260, 0, -22, 0, 0,
ax_anim 2, 0, 260, 0, -18, 0, 0,
ax_anim 1, 0, 260, 0, -12, 0, 0,
ax_anim 2, 2, 258, 0, 0, 0, 0,
ax_anim_terminator
sVolbeatAnims_11_2:
ax_anim 2, 0, 261, 0, 0, 0, 0,
ax_anim 1, 0, 262, 0, -10, 0, 0,
ax_anim 2, 0, 262, 0, -16, 0, 0,
ax_anim 3, 0, 262, 0, -20, 0, 0,
ax_anim 4, 0, 262, 0, -22, 0, 0,
ax_anim 4, 0, 261, 0, -24, 0, 0,
ax_anim 3, 0, 263, 0, -22, 0, 0,
ax_anim 2, 0, 263, 0, -18, 0, 0,
ax_anim 1, 0, 263, 0, -12, 0, 0,
ax_anim 2, 2, 261, 0, 0, 0, 0,
ax_anim_terminator
sVolbeatAnims_11_3:
ax_anim 2, 0, 264, 0, 0, 0, 0,
ax_anim 1, 0, 265, 0, -10, 0, 0,
ax_anim 2, 0, 265, 0, -16, 0, 0,
ax_anim 3, 0, 265, 0, -20, 0, 0,
ax_anim 4, 0, 265, 0, -22, 0, 0,
ax_anim 4, 0, 264, 0, -24, 0, 0,
ax_anim 3, 0, 266, 0, -22, 0, 0,
ax_anim 2, 0, 266, 0, -18, 0, 0,
ax_anim 1, 0, 266, 0, -12, 0, 0,
ax_anim 2, 2, 264, 0, 0, 0, 0,
ax_anim_terminator
sVolbeatAnims_11_4:
ax_anim 2, 0, 267, 0, 0, 0, 0,
ax_anim 1, 0, 268, 0, -10, 0, 0,
ax_anim 2, 0, 268, 0, -16, 0, 0,
ax_anim 3, 0, 268, 0, -20, 0, 0,
ax_anim 4, 0, 268, 0, -22, 0, 0,
ax_anim 4, 0, 267, 0, -23, 0, 0,
ax_anim 3, 0, 269, 0, -21, 0, 0,
ax_anim 2, 0, 269, 0, -17, 0, 0,
ax_anim 1, 0, 269, 0, -11, 0, 0,
ax_anim 2, 2, 267, 0, 0, 0, 0,
ax_anim_terminator
sVolbeatAnims_11_5:
ax_anim 2, 0, 270, 0, 0, 0, 0,
ax_anim 1, 0, 271, 0, -10, 0, 0,
ax_anim 2, 0, 271, 0, -16, 0, 0,
ax_anim 3, 0, 271, 0, -20, 0, 0,
ax_anim 4, 0, 271, 0, -22, 0, 0,
ax_anim 4, 0, 270, 0, -24, 0, 0,
ax_anim 3, 0, 272, 0, -22, 0, 0,
ax_anim 2, 0, 272, 0, -18, 0, 0,
ax_anim 1, 0, 272, 0, -12, 0, 0,
ax_anim 2, 2, 270, 0, 0, 0, 0,
ax_anim_terminator
sVolbeatAnims_11_6:
ax_anim 2, 0, 273, 0, 0, 0, 0,
ax_anim 1, 0, 274, 0, -10, 0, 0,
ax_anim 2, 0, 274, 0, -16, 0, 0,
ax_anim 3, 0, 274, 0, -20, 0, 0,
ax_anim 4, 0, 274, 0, -22, 0, 0,
ax_anim 4, 0, 273, 0, -23, 0, 0,
ax_anim 3, 0, 275, 0, -21, 0, 0,
ax_anim 2, 0, 275, 0, -17, 0, 0,
ax_anim 1, 0, 275, 0, -11, 0, 0,
ax_anim 2, 2, 273, 0, 0, 0, 0,
ax_anim_terminator
sVolbeatAnims_11_7:
ax_anim 2, 0, 276, 0, 0, 0, 0,
ax_anim 1, 0, 277, 0, -10, 0, 0,
ax_anim 2, 0, 277, 0, -16, 0, 0,
ax_anim 3, 0, 277, 0, -20, 0, 0,
ax_anim 4, 0, 277, 0, -22, 0, 0,
ax_anim 4, 0, 276, 0, -24, 0, 0,
ax_anim 3, 0, 278, 0, -22, 0, 0,
ax_anim 2, 0, 278, 0, -18, 0, 0,
ax_anim 1, 0, 278, 0, -12, 0, 0,
ax_anim 2, 2, 276, 0, 0, 0, 0,
ax_anim_terminator
sVolbeatAnims_11_8:
ax_anim 2, 0, 279, 0, 0, 0, 0,
ax_anim 1, 0, 280, 0, -10, 0, 0,
ax_anim 2, 0, 280, 0, -16, 0, 0,
ax_anim 3, 0, 280, 0, -20, 0, 0,
ax_anim 4, 0, 280, 0, -22, 0, 0,
ax_anim 4, 0, 279, 0, -24, 0, 0,
ax_anim 3, 0, 281, 0, -22, 0, 0,
ax_anim 2, 0, 281, 0, -18, 0, 0,
ax_anim 1, 0, 281, 0, -12, 0, 0,
ax_anim 2, 2, 279, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sVolbeatAnims_12_1:
ax_anim 2, 0, 282, 1, 0, 1, 0,
ax_anim 2, 0, 282, 0, 0, 0, 0,
ax_anim 2, 0, 282, 1, 0, 1, 0,
ax_anim 2, 0, 282, 0, 0, 0, 0,
ax_anim 2, 0, 282, 1, 0, 1, 0,
ax_anim 2, 2, 282, 0, 0, 0, 0,
ax_anim 2, 0, 282, 1, 0, 1, 0,
ax_anim 2, 0, 282, 0, 0, 0, 0,
ax_anim 2, 0, 282, 1, 0, 1, 0,
ax_anim 2, 1, 282, 0, 0, 0, 0,
ax_anim_terminator
sVolbeatAnims_12_2:
ax_anim 2, 0, 289, 1, -1, 1, -1,
ax_anim 2, 0, 289, 0, 0, 0, 0,
ax_anim 2, 0, 289, 1, -1, 1, -1,
ax_anim 2, 0, 289, 0, 0, 0, 0,
ax_anim 2, 0, 289, 1, -1, 1, -1,
ax_anim 2, 2, 289, 0, 0, 0, 0,
ax_anim 2, 0, 289, 1, -1, 1, -1,
ax_anim 2, 0, 289, 0, 0, 0, 0,
ax_anim 2, 0, 289, 1, -1, 1, -1,
ax_anim 2, 1, 289, 0, 0, 0, 0,
ax_anim_terminator
sVolbeatAnims_12_3:
ax_anim 2, 0, 288, 0, -1, 0, -1,
ax_anim 2, 0, 288, 0, 0, 0, 0,
ax_anim 2, 0, 288, 0, -1, 0, -1,
ax_anim 2, 0, 288, 0, 0, 0, 0,
ax_anim 2, 0, 288, 0, -1, 0, -1,
ax_anim 2, 2, 288, 0, 0, 0, 0,
ax_anim 2, 0, 288, 0, -1, 0, -1,
ax_anim 2, 0, 288, 0, 0, 0, 0,
ax_anim 2, 0, 288, 0, -1, 0, -1,
ax_anim 2, 1, 288, 0, 0, 0, 0,
ax_anim_terminator
sVolbeatAnims_12_4:
ax_anim 2, 0, 287, -1, -1, -1, -1,
ax_anim 2, 0, 287, 0, 0, 0, 0,
ax_anim 2, 0, 287, -1, -1, -1, -1,
ax_anim 2, 0, 287, 0, 0, 0, 0,
ax_anim 2, 0, 287, -1, -1, -1, -1,
ax_anim 2, 2, 287, 0, 0, 0, 0,
ax_anim 2, 0, 287, -1, -1, -1, -1,
ax_anim 2, 0, 287, 0, 0, 0, 0,
ax_anim 2, 0, 287, -1, -1, -1, -1,
ax_anim 2, 1, 287, 0, 0, 0, 0,
ax_anim_terminator
sVolbeatAnims_12_5:
ax_anim 2, 0, 286, 1, 0, 1, 0,
ax_anim 2, 0, 286, 0, 0, 0, 0,
ax_anim 2, 0, 286, 1, 0, 1, 0,
ax_anim 2, 0, 286, 0, 0, 0, 0,
ax_anim 2, 0, 286, 1, 0, 1, 0,
ax_anim 2, 2, 286, 0, 0, 0, 0,
ax_anim 2, 0, 286, 1, 0, 1, 0,
ax_anim 2, 0, 286, 0, 0, 0, 0,
ax_anim 2, 0, 286, 1, 0, 1, 0,
ax_anim 2, 1, 286, 0, 0, 0, 0,
ax_anim_terminator
sVolbeatAnims_12_6:
ax_anim 2, 0, 285, 1, -1, 1, -1,
ax_anim 2, 0, 285, 0, 0, 0, 0,
ax_anim 2, 0, 285, 1, -1, 1, -1,
ax_anim 2, 0, 285, 0, 0, 0, 0,
ax_anim 2, 0, 285, 1, -1, 1, -1,
ax_anim 2, 2, 285, 0, 0, 0, 0,
ax_anim 2, 0, 285, 1, -1, 1, -1,
ax_anim 2, 0, 285, 0, 0, 0, 0,
ax_anim 2, 0, 285, 1, -1, 1, -1,
ax_anim 2, 1, 285, 0, 0, 0, 0,
ax_anim_terminator
sVolbeatAnims_12_7:
ax_anim 2, 0, 284, 0, -1, 0, -1,
ax_anim 2, 0, 284, 0, 0, 0, 0,
ax_anim 2, 0, 284, 0, -1, 0, -1,
ax_anim 2, 0, 284, 0, 0, 0, 0,
ax_anim 2, 0, 284, 0, -1, 0, -1,
ax_anim 2, 2, 284, 0, 0, 0, 0,
ax_anim 2, 0, 284, 0, -1, 0, -1,
ax_anim 2, 0, 284, 0, 0, 0, 0,
ax_anim 2, 0, 284, 0, -1, 0, -1,
ax_anim 2, 1, 284, 0, 0, 0, 0,
ax_anim_terminator
sVolbeatAnims_12_8:
ax_anim 2, 0, 283, -1, -1, -1, -1,
ax_anim 2, 0, 283, 0, 0, 0, 0,
ax_anim 2, 0, 283, -1, -1, -1, -1,
ax_anim 2, 0, 283, 0, 0, 0, 0,
ax_anim 2, 0, 283, -1, -1, -1, -1,
ax_anim 2, 2, 283, 0, 0, 0, 0,
ax_anim 2, 0, 283, -1, -1, -1, -1,
ax_anim 2, 0, 283, 0, 0, 0, 0,
ax_anim 2, 0, 283, -1, -1, -1, -1,
ax_anim 2, 1, 283, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sVolbeatAnims_13_1:
ax_anim 2, 0, 290, 0, 0, 0, 0,
ax_anim 2, 0, 291, 0, 0, 0, 0,
ax_anim 2, 0, 292, 0, 0, 0, 0,
ax_anim 2, 0, 293, 0, 0, 0, 0,
ax_anim 2, 0, 294, 0, 0, 0, 0,
ax_anim 2, 0, 295, 0, 0, 0, 0,
ax_anim 2, 0, 296, 0, 0, 0, 0,
ax_anim 2, 0, 297, 0, 0, 0, 0,
ax_anim 2, 2, 290, 0, 0, 0, 0,
ax_anim_terminator
sVolbeatAnims_13_2:
ax_anim 2, 0, 297, 0, 0, 0, 0,
ax_anim 2, 0, 290, 0, 0, 0, 0,
ax_anim 2, 0, 291, 0, 0, 0, 0,
ax_anim 2, 0, 292, 0, 0, 0, 0,
ax_anim 2, 0, 293, 0, 0, 0, 0,
ax_anim 2, 0, 294, 0, 0, 0, 0,
ax_anim 2, 0, 295, 0, 0, 0, 0,
ax_anim 2, 0, 296, 0, 0, 0, 0,
ax_anim 2, 2, 297, 0, 0, 0, 0,
ax_anim_terminator
sVolbeatAnims_13_3:
ax_anim 2, 0, 296, 0, 0, 0, 0,
ax_anim 2, 0, 297, 0, 0, 0, 0,
ax_anim 2, 0, 290, 0, 0, 0, 0,
ax_anim 2, 0, 291, 0, 0, 0, 0,
ax_anim 2, 0, 292, 0, 0, 0, 0,
ax_anim 2, 0, 293, 0, 0, 0, 0,
ax_anim 2, 0, 294, 0, 0, 0, 0,
ax_anim 2, 0, 295, 0, 0, 0, 0,
ax_anim 2, 2, 296, 0, 0, 0, 0,
ax_anim_terminator
sVolbeatAnims_13_4:
ax_anim 2, 0, 295, 0, 0, 0, 0,
ax_anim 2, 0, 296, 0, 0, 0, 0,
ax_anim 2, 0, 297, 0, 0, 0, 0,
ax_anim 2, 0, 290, 0, 0, 0, 0,
ax_anim 2, 0, 291, 0, 0, 0, 0,
ax_anim 2, 0, 292, 0, 0, 0, 0,
ax_anim 2, 0, 293, 0, 0, 0, 0,
ax_anim 2, 0, 294, 0, 0, 0, 0,
ax_anim 2, 2, 295, 0, 0, 0, 0,
ax_anim_terminator
sVolbeatAnims_13_5:
ax_anim 2, 0, 294, 0, 0, 0, 0,
ax_anim 2, 0, 295, 0, 0, 0, 0,
ax_anim 2, 0, 296, 0, 0, 0, 0,
ax_anim 2, 0, 297, 0, 0, 0, 0,
ax_anim 2, 0, 290, 0, 0, 0, 0,
ax_anim 2, 0, 291, 0, 0, 0, 0,
ax_anim 2, 0, 292, 0, 0, 0, 0,
ax_anim 2, 0, 293, 0, 0, 0, 0,
ax_anim 2, 2, 294, 0, 0, 0, 0,
ax_anim_terminator
sVolbeatAnims_13_6:
ax_anim 2, 0, 293, 0, 0, 0, 0,
ax_anim 2, 0, 294, 0, 0, 0, 0,
ax_anim 2, 0, 295, 0, 0, 0, 0,
ax_anim 2, 0, 296, 0, 0, 0, 0,
ax_anim 2, 0, 297, 0, 0, 0, 0,
ax_anim 2, 0, 290, 0, 0, 0, 0,
ax_anim 2, 0, 291, 0, 0, 0, 0,
ax_anim 2, 0, 292, 0, 0, 0, 0,
ax_anim 2, 2, 293, 0, 0, 0, 0,
ax_anim_terminator
sVolbeatAnims_13_7:
ax_anim 2, 0, 292, 0, 0, 0, 0,
ax_anim 2, 0, 293, 0, 0, 0, 0,
ax_anim 2, 0, 294, 0, 0, 0, 0,
ax_anim 2, 0, 295, 0, 0, 0, 0,
ax_anim 2, 0, 296, 0, 0, 0, 0,
ax_anim 2, 0, 297, 0, 0, 0, 0,
ax_anim 2, 0, 290, 0, 0, 0, 0,
ax_anim 2, 0, 291, 0, 0, 0, 0,
ax_anim 2, 2, 292, 0, 0, 0, 0,
ax_anim_terminator
sVolbeatAnims_13_8:
ax_anim 2, 0, 291, 0, 0, 0, 0,
ax_anim 2, 0, 292, 0, 0, 0, 0,
ax_anim 2, 0, 293, 0, 0, 0, 0,
ax_anim 2, 0, 294, 0, 0, 0, 0,
ax_anim 2, 0, 295, 0, 0, 0, 0,
ax_anim 2, 0, 296, 0, 0, 0, 0,
ax_anim 2, 0, 297, 0, 0, 0, 0,
ax_anim 2, 0, 290, 0, 0, 0, 0,
ax_anim 2, 2, 291, 0, 0, 0, 0,
ax_anim_terminator
sVolbeatGfx1:
.incbin "baserom.gba", 0x12BED20, 0x200
sVolbeatSprites1:
ax_sprite sVolbeatGfx1, 0x200
ax_sprite_terminator
sVolbeatGfx2:
.incbin "baserom.gba", 0x12BEF30, 0x200
sVolbeatSprites2:
ax_sprite sVolbeatGfx2, 0x200
ax_sprite_terminator
sVolbeatGfx3:
.incbin "baserom.gba", 0x12BF140, 0x200
sVolbeatSprites3:
ax_sprite sVolbeatGfx3, 0x200
ax_sprite_terminator
sVolbeatGfx4:
.incbin "baserom.gba", 0x12BF350, 0x200
sVolbeatSprites4:
ax_sprite sVolbeatGfx4, 0x200
ax_sprite_terminator
sVolbeatGfx5:
.incbin "baserom.gba", 0x12BF560, 0x200
sVolbeatSprites5:
ax_sprite sVolbeatGfx5, 0x200
ax_sprite_terminator
sVolbeatGfx6:
.incbin "baserom.gba", 0x12BF770, 0x200
sVolbeatSprites6:
ax_sprite sVolbeatGfx6, 0x200
ax_sprite_terminator
sVolbeatGfx7:
.incbin "baserom.gba", 0x12BF980, 0x200
sVolbeatSprites7:
ax_sprite sVolbeatGfx7, 0x200
ax_sprite_terminator
sVolbeatGfx8:
.incbin "baserom.gba", 0x12BFB90, 0x200
sVolbeatSprites8:
ax_sprite sVolbeatGfx8, 0x200
ax_sprite_terminator
sVolbeatGfx9:
.incbin "baserom.gba", 0x12BFDA0, 0x200
sVolbeatSprites9:
ax_sprite sVolbeatGfx9, 0x200
ax_sprite_terminator
sVolbeatGfx10:
.incbin "baserom.gba", 0x12BFFB0, 0x200
sVolbeatSprites10:
ax_sprite sVolbeatGfx10, 0x200
ax_sprite_terminator
sVolbeatGfx11:
.incbin "baserom.gba", 0x12C01C0, 0x200
sVolbeatSprites11:
ax_sprite sVolbeatGfx11, 0x200
ax_sprite_terminator
sVolbeatGfx12:
.incbin "baserom.gba", 0x12C03D0, 0x200
sVolbeatSprites12:
ax_sprite sVolbeatGfx12, 0x200
ax_sprite_terminator
sVolbeatGfx13:
.incbin "baserom.gba", 0x12C05E0, 0x200
sVolbeatSprites13:
ax_sprite sVolbeatGfx13, 0x200
ax_sprite_terminator
sVolbeatGfx14:
.incbin "baserom.gba", 0x12C07F0, 0x200
sVolbeatSprites14:
ax_sprite sVolbeatGfx14, 0x200
ax_sprite_terminator
sVolbeatGfx15:
.incbin "baserom.gba", 0x12C0A00, 0x200
sVolbeatSprites15:
ax_sprite sVolbeatGfx15, 0x200
ax_sprite_terminator
sVolbeatGfx16:
.incbin "baserom.gba", 0x12C0C10, 0x40
sVolbeatGfx16_1:
.incbin "baserom.gba", 0x12C0C50, 0x100
sVolbeatGfx16_2:
.incbin "baserom.gba", 0x12C0D50, 0x40
sVolbeatSprites16:
ax_sprite 0, 0x20
ax_sprite sVolbeatGfx16, 0x40
ax_sprite 0, 0x20
ax_sprite sVolbeatGfx16_1, 0x100
ax_sprite 0, 0x20
ax_sprite sVolbeatGfx16_2, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sVolbeatGfx17:
.incbin "baserom.gba", 0x12C0DD0, 0x40
sVolbeatGfx17_1:
.incbin "baserom.gba", 0x12C0E10, 0x100
sVolbeatGfx17_2:
.incbin "baserom.gba", 0x12C0F10, 0x40
sVolbeatSprites17:
ax_sprite 0, 0x20
ax_sprite sVolbeatGfx17, 0x40
ax_sprite 0, 0x20
ax_sprite sVolbeatGfx17_1, 0x100
ax_sprite 0, 0x20
ax_sprite sVolbeatGfx17_2, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sVolbeatGfx18:
.incbin "baserom.gba", 0x12C0F90, 0x40
sVolbeatGfx18_1:
.incbin "baserom.gba", 0x12C0FD0, 0x100
sVolbeatGfx18_2:
.incbin "baserom.gba", 0x12C10D0, 0x40
sVolbeatSprites18:
ax_sprite 0, 0x20
ax_sprite sVolbeatGfx18, 0x40
ax_sprite 0, 0x20
ax_sprite sVolbeatGfx18_1, 0x100
ax_sprite 0, 0x20
ax_sprite sVolbeatGfx18_2, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sVolbeatGfx19:
.incbin "baserom.gba", 0x12C1150, 0x40
sVolbeatGfx19_1:
.incbin "baserom.gba", 0x12C1190, 0x100
sVolbeatGfx19_2:
.incbin "baserom.gba", 0x12C1290, 0x40
sVolbeatSprites19:
ax_sprite 0, 0x20
ax_sprite sVolbeatGfx19, 0x40
ax_sprite 0, 0x20
ax_sprite sVolbeatGfx19_1, 0x100
ax_sprite 0, 0x20
ax_sprite sVolbeatGfx19_2, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sVolbeatGfx20:
.incbin "baserom.gba", 0x12C1310, 0x40
sVolbeatGfx20_1:
.incbin "baserom.gba", 0x12C1350, 0x100
sVolbeatGfx20_2:
.incbin "baserom.gba", 0x12C1450, 0x40
sVolbeatSprites20:
ax_sprite 0, 0x20
ax_sprite sVolbeatGfx20, 0x40
ax_sprite 0, 0x20
ax_sprite sVolbeatGfx20_1, 0x100
ax_sprite 0, 0x20
ax_sprite sVolbeatGfx20_2, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sVolbeatGfx21:
.incbin "baserom.gba", 0x12C14D0, 0x40
sVolbeatGfx21_1:
.incbin "baserom.gba", 0x12C1510, 0x100
sVolbeatGfx21_2:
.incbin "baserom.gba", 0x12C1610, 0x40
sVolbeatSprites21:
ax_sprite 0, 0x20
ax_sprite sVolbeatGfx21, 0x40
ax_sprite 0, 0x20
ax_sprite sVolbeatGfx21_1, 0x100
ax_sprite 0, 0x20
ax_sprite sVolbeatGfx21_2, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sVolbeatGfx22:
.incbin "baserom.gba", 0x12C1690, 0x40
sVolbeatGfx22_1:
.incbin "baserom.gba", 0x12C16D0, 0x100
sVolbeatGfx22_2:
.incbin "baserom.gba", 0x12C17D0, 0x40
sVolbeatSprites22:
ax_sprite 0, 0x20
ax_sprite sVolbeatGfx22, 0x40
ax_sprite 0, 0x20
ax_sprite sVolbeatGfx22_1, 0x100
ax_sprite 0, 0x20
ax_sprite sVolbeatGfx22_2, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sVolbeatGfx23:
.incbin "baserom.gba", 0x12C1850, 0x40
sVolbeatGfx23_1:
.incbin "baserom.gba", 0x12C1890, 0x80
sVolbeatGfx23_2:
.incbin "baserom.gba", 0x12C1910, 0x60
sVolbeatGfx23_3:
.incbin "baserom.gba", 0x12C1970, 0x40
sVolbeatSprites23:
ax_sprite 0, 0x20
ax_sprite sVolbeatGfx23, 0x40
ax_sprite 0, 0x20
ax_sprite sVolbeatGfx23_1, 0x80
ax_sprite 0, 0x20
ax_sprite sVolbeatGfx23_2, 0x60
ax_sprite 0, 0x20
ax_sprite sVolbeatGfx23_3, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sVolbeatGfx24:
.incbin "baserom.gba", 0x12C1A00, 0x40
sVolbeatGfx24_1:
.incbin "baserom.gba", 0x12C1A40, 0x60
sVolbeatGfx24_2:
.incbin "baserom.gba", 0x12C1AA0, 0x60
sVolbeatGfx24_3:
.incbin "baserom.gba", 0x12C1B00, 0x60
sVolbeatSprites24:
ax_sprite 0, 0x20
ax_sprite sVolbeatGfx24, 0x40
ax_sprite 0, 0x40
ax_sprite sVolbeatGfx24_1, 0x60
ax_sprite 0, 0x20
ax_sprite sVolbeatGfx24_2, 0x60
ax_sprite 0, 0x20
ax_sprite sVolbeatGfx24_3, 0x60
ax_sprite_terminator
sVolbeatGfx25:
.incbin "baserom.gba", 0x12C1BA8, 0x40
sVolbeatGfx25_1:
.incbin "baserom.gba", 0x12C1BE8, 0x60
sVolbeatGfx25_2:
.incbin "baserom.gba", 0x12C1C48, 0x60
sVolbeatGfx25_3:
.incbin "baserom.gba", 0x12C1CA8, 0x60
sVolbeatSprites25:
ax_sprite 0, 0x20
ax_sprite sVolbeatGfx25, 0x40
ax_sprite 0, 0x40
ax_sprite sVolbeatGfx25_1, 0x60
ax_sprite 0, 0x20
ax_sprite sVolbeatGfx25_2, 0x60
ax_sprite 0, 0x20
ax_sprite sVolbeatGfx25_3, 0x60
ax_sprite_terminator
sVolbeatGfx26:
.incbin "baserom.gba", 0x12C1D50, 0x40
sVolbeatGfx26_1:
.incbin "baserom.gba", 0x12C1D90, 0x60
sVolbeatGfx26_2:
.incbin "baserom.gba", 0x12C1DF0, 0x60
sVolbeatGfx26_3:
.incbin "baserom.gba", 0x12C1E50, 0x40
sVolbeatSprites26:
ax_sprite 0, 0x20
ax_sprite sVolbeatGfx26, 0x40
ax_sprite 0, 0x40
ax_sprite sVolbeatGfx26_1, 0x60
ax_sprite 0, 0x20
ax_sprite sVolbeatGfx26_2, 0x60
ax_sprite 0, 0x20
ax_sprite sVolbeatGfx26_3, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sVolbeatGfx27:
.incbin "baserom.gba", 0x12C1EE0, 0x40
sVolbeatGfx27_1:
.incbin "baserom.gba", 0x12C1F20, 0x60
sVolbeatGfx27_2:
.incbin "baserom.gba", 0x12C1F80, 0x60
sVolbeatGfx27_3:
.incbin "baserom.gba", 0x12C1FE0, 0x40
sVolbeatSprites27:
ax_sprite 0, 0x20
ax_sprite sVolbeatGfx27, 0x40
ax_sprite 0, 0x40
ax_sprite sVolbeatGfx27_1, 0x60
ax_sprite 0, 0x20
ax_sprite sVolbeatGfx27_2, 0x60
ax_sprite 0, 0x20
ax_sprite sVolbeatGfx27_3, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sVolbeatGfx28:
.incbin "baserom.gba", 0x12C2070, 0x40
sVolbeatGfx28_1:
.incbin "baserom.gba", 0x12C20B0, 0x60
sVolbeatGfx28_2:
.incbin "baserom.gba", 0x12C2110, 0x60
sVolbeatGfx28_3:
.incbin "baserom.gba", 0x12C2170, 0x40
sVolbeatSprites28:
ax_sprite 0, 0x20
ax_sprite sVolbeatGfx28, 0x40
ax_sprite 0, 0x40
ax_sprite sVolbeatGfx28_1, 0x60
ax_sprite 0, 0x20
ax_sprite sVolbeatGfx28_2, 0x60
ax_sprite 0, 0x20
ax_sprite sVolbeatGfx28_3, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sVolbeatGfx29:
.incbin "baserom.gba", 0x12C2200, 0x40
sVolbeatGfx29_1:
.incbin "baserom.gba", 0x12C2240, 0x60
sVolbeatGfx29_2:
.incbin "baserom.gba", 0x12C22A0, 0x60
sVolbeatGfx29_3:
.incbin "baserom.gba", 0x12C2300, 0x40
sVolbeatSprites29:
ax_sprite 0, 0x20
ax_sprite sVolbeatGfx29, 0x40
ax_sprite 0, 0x40
ax_sprite sVolbeatGfx29_1, 0x60
ax_sprite 0, 0x20
ax_sprite sVolbeatGfx29_2, 0x60
ax_sprite 0, 0x20
ax_sprite sVolbeatGfx29_3, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sVolbeatGfx30:
.incbin "baserom.gba", 0x12C2390, 0x40
sVolbeatGfx30_1:
.incbin "baserom.gba", 0x12C23D0, 0x60
sVolbeatGfx30_2:
.incbin "baserom.gba", 0x12C2430, 0x60
sVolbeatGfx30_3:
.incbin "baserom.gba", 0x12C2490, 0x60
sVolbeatSprites30:
ax_sprite 0, 0x20
ax_sprite sVolbeatGfx30, 0x40
ax_sprite 0, 0x40
ax_sprite sVolbeatGfx30_1, 0x60
ax_sprite 0, 0x20
ax_sprite sVolbeatGfx30_2, 0x60
ax_sprite 0, 0x20
ax_sprite sVolbeatGfx30_3, 0x60
ax_sprite_terminator
sVolbeatGfx31:
.incbin "baserom.gba", 0x12C2538, 0x40
sVolbeatGfx31_1:
.incbin "baserom.gba", 0x12C2578, 0x60
sVolbeatGfx31_2:
.incbin "baserom.gba", 0x12C25D8, 0x60
sVolbeatGfx31_3:
.incbin "baserom.gba", 0x12C2638, 0x60
sVolbeatSprites31:
ax_sprite 0, 0x20
ax_sprite sVolbeatGfx31, 0x40
ax_sprite 0, 0x40
ax_sprite sVolbeatGfx31_1, 0x60
ax_sprite 0, 0x20
ax_sprite sVolbeatGfx31_2, 0x60
ax_sprite 0, 0x20
ax_sprite sVolbeatGfx31_3, 0x60
ax_sprite_terminator
sVolbeatGfx32:
.incbin "baserom.gba", 0x12C26E0, 0x40
sVolbeatGfx32_1:
.incbin "baserom.gba", 0x12C2720, 0x60
sVolbeatGfx32_2:
.incbin "baserom.gba", 0x12C2780, 0x60
sVolbeatGfx32_3:
.incbin "baserom.gba", 0x12C27E0, 0x40
sVolbeatSprites32:
ax_sprite 0, 0x20
ax_sprite sVolbeatGfx32, 0x40
ax_sprite 0, 0x40
ax_sprite sVolbeatGfx32_1, 0x60
ax_sprite 0, 0x20
ax_sprite sVolbeatGfx32_2, 0x60
ax_sprite 0, 0x20
ax_sprite sVolbeatGfx32_3, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sVolbeatGfx33:
.incbin "baserom.gba", 0x12C2870, 0x40
sVolbeatGfx33_1:
.incbin "baserom.gba", 0x12C28B0, 0x60
sVolbeatGfx33_2:
.incbin "baserom.gba", 0x12C2910, 0x60
sVolbeatGfx33_3:
.incbin "baserom.gba", 0x12C2970, 0x40
sVolbeatSprites33:
ax_sprite 0, 0x20
ax_sprite sVolbeatGfx33, 0x40
ax_sprite 0, 0x40
ax_sprite sVolbeatGfx33_1, 0x60
ax_sprite 0, 0x20
ax_sprite sVolbeatGfx33_2, 0x60
ax_sprite 0, 0x20
ax_sprite sVolbeatGfx33_3, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sVolbeatGfx34:
.incbin "baserom.gba", 0x12C2A00, 0x40
sVolbeatGfx34_1:
.incbin "baserom.gba", 0x12C2A40, 0x60
sVolbeatGfx34_2:
.incbin "baserom.gba", 0x12C2AA0, 0x60
sVolbeatGfx34_3:
.incbin "baserom.gba", 0x12C2B00, 0x40
sVolbeatSprites34:
ax_sprite 0, 0x20
ax_sprite sVolbeatGfx34, 0x40
ax_sprite 0, 0x40
ax_sprite sVolbeatGfx34_1, 0x60
ax_sprite 0, 0x20
ax_sprite sVolbeatGfx34_2, 0x60
ax_sprite 0, 0x20
ax_sprite sVolbeatGfx34_3, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sVolbeatGfx35:
.incbin "baserom.gba", 0x12C2B90, 0x40
sVolbeatGfx35_1:
.incbin "baserom.gba", 0x12C2BD0, 0x60
sVolbeatGfx35_2:
.incbin "baserom.gba", 0x12C2C30, 0x60
sVolbeatGfx35_3:
.incbin "baserom.gba", 0x12C2C90, 0x40
sVolbeatSprites35:
ax_sprite 0, 0x20
ax_sprite sVolbeatGfx35, 0x40
ax_sprite 0, 0x40
ax_sprite sVolbeatGfx35_1, 0x60
ax_sprite 0, 0x20
ax_sprite sVolbeatGfx35_2, 0x60
ax_sprite 0, 0x20
ax_sprite sVolbeatGfx35_3, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sVolbeatGfx36:
.incbin "baserom.gba", 0x12C2D20, 0x40
sVolbeatGfx36_1:
.incbin "baserom.gba", 0x12C2D60, 0x100
sVolbeatGfx36_2:
.incbin "baserom.gba", 0x12C2E60, 0x40
sVolbeatSprites36:
ax_sprite 0, 0x20
ax_sprite sVolbeatGfx36, 0x40
ax_sprite 0, 0x20
ax_sprite sVolbeatGfx36_1, 0x100
ax_sprite 0, 0x20
ax_sprite sVolbeatGfx36_2, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sVolbeatGfx37:
.incbin "baserom.gba", 0x12C2EE0, 0x40
sVolbeatGfx37_1:
.incbin "baserom.gba", 0x12C2F20, 0x100
sVolbeatGfx37_2:
.incbin "baserom.gba", 0x12C3020, 0x40
sVolbeatSprites37:
ax_sprite 0, 0x20
ax_sprite sVolbeatGfx37, 0x40
ax_sprite 0, 0x20
ax_sprite sVolbeatGfx37_1, 0x100
ax_sprite 0, 0x20
ax_sprite sVolbeatGfx37_2, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sVolbeatGfx38:
.incbin "baserom.gba", 0x12C30A0, 0x60
sVolbeatGfx38_1:
.incbin "baserom.gba", 0x12C3100, 0xE0
sVolbeatGfx38_2:
.incbin "baserom.gba", 0x12C31E0, 0x40
sVolbeatSprites38:
ax_sprite 0, 0x20
ax_sprite sVolbeatGfx38, 0x60
ax_sprite 0, 0x20
ax_sprite sVolbeatGfx38_1, 0xe0
ax_sprite 0, 0x20
ax_sprite sVolbeatGfx38_2, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sVolbeatGfx39:
.incbin "baserom.gba", 0x12C3260, 0x60
sVolbeatGfx39_1:
.incbin "baserom.gba", 0x12C32C0, 0xE0
sVolbeatGfx39_2:
.incbin "baserom.gba", 0x12C33A0, 0x40
sVolbeatSprites39:
ax_sprite 0, 0x20
ax_sprite sVolbeatGfx39, 0x60
ax_sprite 0, 0x20
ax_sprite sVolbeatGfx39_1, 0xe0
ax_sprite 0, 0x20
ax_sprite sVolbeatGfx39_2, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sVolbeatGfx40:
.incbin "baserom.gba", 0x12C3420, 0x60
sVolbeatGfx40_1:
.incbin "baserom.gba", 0x12C3480, 0x100
sVolbeatGfx40_2:
.incbin "baserom.gba", 0x12C3580, 0x40
sVolbeatSprites40:
ax_sprite sVolbeatGfx40, 0x60
ax_sprite 0, 0x20
ax_sprite sVolbeatGfx40_1, 0x100
ax_sprite 0, 0x20
ax_sprite sVolbeatGfx40_2, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sVolbeatGfx41:
.incbin "baserom.gba", 0x12C35F8, 0x60
sVolbeatGfx41_1:
.incbin "baserom.gba", 0x12C3658, 0x100
sVolbeatGfx41_2:
.incbin "baserom.gba", 0x12C3758, 0x40
sVolbeatSprites41:
ax_sprite sVolbeatGfx41, 0x60
ax_sprite 0, 0x20
ax_sprite sVolbeatGfx41_1, 0x100
ax_sprite 0, 0x20
ax_sprite sVolbeatGfx41_2, 0x40
ax_sprite 0, 0x20
ax_sprite_terminator
sVolbeatGfx42:
.incbin "baserom.gba", 0x12C37D0, 0x20
sVolbeatSprites42:
ax_sprite sVolbeatGfx42, 0x20
ax_sprite_terminator
sVolbeatGfx43:
.incbin "baserom.gba", 0x12C3800, 0x200
sVolbeatSprites43:
ax_sprite sVolbeatGfx43, 0x200
ax_sprite_terminator
sVolbeatGfx44:
.incbin "baserom.gba", 0x12C3A10, 0x200
sVolbeatSprites44:
ax_sprite sVolbeatGfx44, 0x200
ax_sprite_terminator
sVolbeatGfx45:
.incbin "baserom.gba", 0x12C3C20, 0x80
sVolbeatSprites45:
ax_sprite sVolbeatGfx45, 0x80
ax_sprite_terminator
sVolbeatGfx46:
.incbin "baserom.gba", 0x12C3CB0, 0x20
sVolbeatSprites46:
ax_sprite sVolbeatGfx46, 0x20
ax_sprite_terminator
sVolbeatGfx47:
.incbin "baserom.gba", 0x12C3CE0, 0x20
sVolbeatSprites47:
ax_sprite sVolbeatGfx47, 0x20
ax_sprite_terminator
sVolbeatGfx48:
.incbin "baserom.gba", 0x12C3D10, 0x100
sVolbeatSprites48:
ax_sprite sVolbeatGfx48, 0x100
ax_sprite_terminator
sVolbeatGfx49:
.incbin "baserom.gba", 0x12C3E20, 0x200
sVolbeatSprites49:
ax_sprite sVolbeatGfx49, 0x200
ax_sprite_terminator
sVolbeatGfx50:
.incbin "baserom.gba", 0x12C4030, 0x200
sVolbeatSprites50:
ax_sprite sVolbeatGfx50, 0x200
ax_sprite_terminator
sVolbeatGfx51:
.incbin "baserom.gba", 0x12C4240, 0x200
sVolbeatSprites51:
ax_sprite sVolbeatGfx51, 0x200
ax_sprite_terminator
sVolbeatGfx52:
.incbin "baserom.gba", 0x12C4450, 0x80
sVolbeatSprites52:
ax_sprite sVolbeatGfx52, 0x80
ax_sprite_terminator
sVolbeatGfx53:
.incbin "baserom.gba", 0x12C44E0, 0x20
sVolbeatSprites53:
ax_sprite sVolbeatGfx53, 0x20
ax_sprite_terminator
sVolbeatGfx54:
.incbin "baserom.gba", 0x12C4510, 0x20
sVolbeatSprites54:
ax_sprite sVolbeatGfx54, 0x20
ax_sprite_terminator
sVolbeatGfx55:
.incbin "baserom.gba", 0x12C4540, 0x100
sVolbeatSprites55:
ax_sprite sVolbeatGfx55, 0x100
ax_sprite_terminator
sAxPosesVolbeat:
.4byte sVolbeatPose1
.4byte sVolbeatPose2
.4byte sVolbeatPose3
.4byte sVolbeatPose4
.4byte sVolbeatPose5
.4byte sVolbeatPose6
.4byte sVolbeatPose7
.4byte sVolbeatPose8
.4byte sVolbeatPose9
.4byte sVolbeatPose10
.4byte sVolbeatPose11
.4byte sVolbeatPose12
.4byte sVolbeatPose13
.4byte sVolbeatPose14
.4byte sVolbeatPose15
.4byte sVolbeatPose16
.4byte sVolbeatPose17
.4byte sVolbeatPose18
.4byte sVolbeatPose19
.4byte sVolbeatPose20
.4byte sVolbeatPose21
.4byte sVolbeatPose22
.4byte sVolbeatPose23
.4byte sVolbeatPose24
.4byte sVolbeatPose25
.4byte sVolbeatPose26
.4byte sVolbeatPose27
.4byte sVolbeatPose28
.4byte sVolbeatPose29
.4byte sVolbeatPose30
.4byte sVolbeatPose31
.4byte sVolbeatPose32
.4byte sVolbeatPose33
.4byte sVolbeatPose34
.4byte sVolbeatPose35
.4byte sVolbeatPose36
.4byte sVolbeatPose37
.4byte sVolbeatPose38
.4byte sVolbeatPose39
.4byte sVolbeatPose40
.4byte sVolbeatPose41
.4byte sVolbeatPose42
.4byte sVolbeatPose43
.4byte sVolbeatPose44
.4byte sVolbeatPose45
.4byte sVolbeatPose46
.4byte sVolbeatPose47
.4byte sVolbeatPose48
.4byte sVolbeatPose49
.4byte sVolbeatPose50
.4byte sVolbeatPose51
.4byte sVolbeatPose52
.4byte sVolbeatPose53
.4byte sVolbeatPose54
.4byte sVolbeatPose55
.4byte sVolbeatPose56
.4byte sVolbeatPose57
.4byte sVolbeatPose58
.4byte sVolbeatPose59
.4byte sVolbeatPose60
.4byte sVolbeatPose61
.4byte sVolbeatPose62
.4byte sVolbeatPose63
.4byte sVolbeatPose64
.4byte sVolbeatPose65
.4byte sVolbeatPose66
.4byte sVolbeatPose67
.4byte sVolbeatPose68
.4byte sVolbeatPose69
.4byte sVolbeatPose70
.4byte sVolbeatPose71
.4byte sVolbeatPose72
.4byte sVolbeatPose73
.4byte sVolbeatPose74
.4byte sVolbeatPose75
.4byte sVolbeatPose76
.4byte sVolbeatPose77
.4byte sVolbeatPose78
.4byte sVolbeatPose79
.4byte sVolbeatPose80
.4byte sVolbeatPose81
.4byte sVolbeatPose82
.4byte sVolbeatPose83
.4byte sVolbeatPose84
.4byte sVolbeatPose85
.4byte sVolbeatPose86
.4byte sVolbeatPose87
.4byte sVolbeatPose88
.4byte sVolbeatPose89
.4byte sVolbeatPose90
.4byte sVolbeatPose91
.4byte sVolbeatPose92
.4byte sVolbeatPose93
.4byte sVolbeatPose94
.4byte sVolbeatPose95
.4byte sVolbeatPose96
.4byte sVolbeatPose97
.4byte sVolbeatPose98
.4byte sVolbeatPose99
.4byte sVolbeatPose100
.4byte sVolbeatPose101
.4byte sVolbeatPose102
.4byte sVolbeatPose103
.4byte sVolbeatPose104
.4byte sVolbeatPose105
.4byte sVolbeatPose106
.4byte sVolbeatPose107
.4byte sVolbeatPose108
.4byte sVolbeatPose109
.4byte sVolbeatPose110
.4byte sVolbeatPose111
.4byte sVolbeatPose112
.4byte sVolbeatPose113
.4byte sVolbeatPose114
.4byte sVolbeatPose115
.4byte sVolbeatPose116
.4byte sVolbeatPose117
.4byte sVolbeatPose118
.4byte sVolbeatPose119
.4byte sVolbeatPose120
.4byte sVolbeatPose121
.4byte sVolbeatPose122
.4byte sVolbeatPose123
.4byte sVolbeatPose124
.4byte sVolbeatPose125
.4byte sVolbeatPose126
.4byte sVolbeatPose127
.4byte sVolbeatPose128
.4byte sVolbeatPose129
.4byte sVolbeatPose130
.4byte sVolbeatPose131
.4byte sVolbeatPose132
.4byte sVolbeatPose133
.4byte sVolbeatPose134
.4byte sVolbeatPose135
.4byte sVolbeatPose136
.4byte sVolbeatPose137
.4byte sVolbeatPose138
.4byte sVolbeatPose139
.4byte sVolbeatPose140
.4byte sVolbeatPose141
.4byte sVolbeatPose142
.4byte sVolbeatPose143
.4byte sVolbeatPose144
.4byte sVolbeatPose145
.4byte sVolbeatPose146
.4byte sVolbeatPose147
.4byte sVolbeatPose148
.4byte sVolbeatPose149
.4byte sVolbeatPose150
.4byte sVolbeatPose151
.4byte sVolbeatPose152
.4byte sVolbeatPose153
.4byte sVolbeatPose154
.4byte sVolbeatPose155
.4byte sVolbeatPose156
.4byte sVolbeatPose157
.4byte sVolbeatPose158
.4byte sVolbeatPose159
.4byte sVolbeatPose160
.4byte sVolbeatPose161
.4byte sVolbeatPose162
.4byte sVolbeatPose163
.4byte sVolbeatPose164
.4byte sVolbeatPose165
.4byte sVolbeatPose166
.4byte sVolbeatPose167
.4byte sVolbeatPose168
.4byte sVolbeatPose169
.4byte sVolbeatPose170
.4byte sVolbeatPose171
.4byte sVolbeatPose172
.4byte sVolbeatPose173
.4byte sVolbeatPose174
.4byte sVolbeatPose175
.4byte sVolbeatPose176
.4byte sVolbeatPose177
.4byte sVolbeatPose178
.4byte sVolbeatPose179
.4byte sVolbeatPose180
.4byte sVolbeatPose181
.4byte sVolbeatPose182
.4byte sVolbeatPose183
.4byte sVolbeatPose184
.4byte sVolbeatPose185
.4byte sVolbeatPose186
.4byte sVolbeatPose187
.4byte sVolbeatPose188
.4byte sVolbeatPose189
.4byte sVolbeatPose190
.4byte sVolbeatPose191
.4byte sVolbeatPose192
.4byte sVolbeatPose193
.4byte sVolbeatPose194
.4byte sVolbeatPose195
.4byte sVolbeatPose196
.4byte sVolbeatPose197
.4byte sVolbeatPose198
.4byte sVolbeatPose199
.4byte sVolbeatPose200
.4byte sVolbeatPose201
.4byte sVolbeatPose202
.4byte sVolbeatPose203
.4byte sVolbeatPose204
.4byte sVolbeatPose205
.4byte sVolbeatPose206
.4byte sVolbeatPose207
.4byte sVolbeatPose208
.4byte sVolbeatPose209
.4byte sVolbeatPose210
.4byte sVolbeatPose211
.4byte sVolbeatPose212
.4byte sVolbeatPose213
.4byte sVolbeatPose214
.4byte sVolbeatPose215
.4byte sVolbeatPose216
.4byte sVolbeatPose217
.4byte sVolbeatPose218
.4byte sVolbeatPose219
.4byte sVolbeatPose220
.4byte sVolbeatPose221
.4byte sVolbeatPose222
.4byte sVolbeatPose223
.4byte sVolbeatPose224
.4byte sVolbeatPose225
.4byte sVolbeatPose226
.4byte sVolbeatPose227
.4byte sVolbeatPose228
.4byte sVolbeatPose229
.4byte sVolbeatPose230
.4byte sVolbeatPose231
.4byte sVolbeatPose232
.4byte sVolbeatPose233
.4byte sVolbeatPose234
.4byte sVolbeatPose235
.4byte sVolbeatPose236
.4byte sVolbeatPose237
.4byte sVolbeatPose238
.4byte sVolbeatPose239
.4byte sVolbeatPose240
.4byte sVolbeatPose241
.4byte sVolbeatPose242
.4byte sVolbeatPose243
.4byte sVolbeatPose244
.4byte sVolbeatPose245
.4byte sVolbeatPose246
.4byte sVolbeatPose247
.4byte sVolbeatPose248
.4byte sVolbeatPose249
.4byte sVolbeatPose250
.4byte sVolbeatPose251
.4byte sVolbeatPose252
.4byte sVolbeatPose253
.4byte sVolbeatPose254
.4byte sVolbeatPose255
.4byte sVolbeatPose256
.4byte sVolbeatPose257
.4byte sVolbeatPose258
.4byte sVolbeatPose259
.4byte sVolbeatPose260
.4byte sVolbeatPose261
.4byte sVolbeatPose262
.4byte sVolbeatPose263
.4byte sVolbeatPose264
.4byte sVolbeatPose265
.4byte sVolbeatPose266
.4byte sVolbeatPose267
.4byte sVolbeatPose268
.4byte sVolbeatPose269
.4byte sVolbeatPose270
.4byte sVolbeatPose271
.4byte sVolbeatPose272
.4byte sVolbeatPose273
.4byte sVolbeatPose274
.4byte sVolbeatPose275
.4byte sVolbeatPose276
.4byte sVolbeatPose277
.4byte sVolbeatPose278
.4byte sVolbeatPose279
.4byte sVolbeatPose280
.4byte sVolbeatPose281
.4byte sVolbeatPose282
.4byte sVolbeatPose283
.4byte sVolbeatPose284
.4byte sVolbeatPose285
.4byte sVolbeatPose286
.4byte sVolbeatPose287
.4byte sVolbeatPose288
.4byte sVolbeatPose289
.4byte sVolbeatPose290
.4byte sVolbeatPose291
.4byte sVolbeatPose292
.4byte sVolbeatPose293
.4byte sVolbeatPose294
.4byte sVolbeatPose295
.4byte sVolbeatPose296
.4byte sVolbeatPose297
.4byte sVolbeatPose298
sAxPositionsVolbeat:
.2byte   -1,   -8, 	  -8,   -4, 	   6,   -4, 	  -1,   -5
.2byte   -1,   -8, 	  -8,   -4, 	   6,   -4, 	  -1,   -5
.2byte   -1,   -8, 	  -8,   -4, 	   6,   -4, 	  -1,   -5
.2byte    2,   -9, 	   5,   -5, 	  -7,   -3, 	   1,   -5
.2byte    2,   -9, 	   5,   -5, 	  -7,   -3, 	   0,   -5
.2byte    2,   -9, 	   5,   -5, 	  -7,   -3, 	   0,   -5
.2byte    6,  -10, 	   3,   -5, 	   1,   -3, 	   0,   -4
.2byte    6,  -10, 	   3,   -5, 	   1,   -3, 	   0,   -4
.2byte    6,  -10, 	   3,   -5, 	   1,   -3, 	   0,   -4
.2byte    4,  -11, 	  -5,   -5, 	   6,   -4, 	  -1,   -3
.2byte    4,  -11, 	  -5,   -5, 	   6,   -4, 	  -2,   -4
.2byte    4,  -11, 	  -5,   -5, 	   6,   -4, 	  -2,   -3
.2byte   -1,   -9, 	   5,   -4, 	  -7,   -4, 	  -1,   -5
.2byte   -1,  -10, 	   5,   -4, 	  -7,   -4, 	  -1,   -6
.2byte   -1,   -9, 	   5,   -2, 	  -7,   -2, 	  -1,   -5
.2byte   -6,  -11, 	   3,   -5, 	  -8,   -4, 	  -1,   -3
.2byte   -6,  -11, 	   3,   -5, 	  -8,   -4, 	   0,   -4
.2byte   -6,  -11, 	   3,   -5, 	  -8,   -4, 	   0,   -3
.2byte   -8,  -10, 	  -5,   -5, 	  -3,   -3, 	  -2,   -4
.2byte   -8,  -10, 	  -5,   -5, 	  -3,   -3, 	  -2,   -4
.2byte   -8,  -10, 	  -5,   -5, 	  -3,   -3, 	  -2,   -4
.2byte   -4,   -9, 	  -7,   -5, 	   5,   -3, 	  -3,   -5
.2byte   -4,   -9, 	  -7,   -5, 	   5,   -3, 	  -2,   -5
.2byte   -4,   -9, 	  -7,   -5, 	   5,   -3, 	  -2,   -5
.2byte   -1,   -8, 	  -8,   -4, 	   6,   -4, 	  -1,   -5
.2byte   -1,   -8, 	  -8,   -4, 	   6,   -4, 	  -1,   -5
.2byte   -1,   -8, 	  -8,   -4, 	   6,   -4, 	  -1,   -5
.2byte   -1,   -7, 	  -8,   -5, 	   6,   -5, 	  -1,   -5
.2byte   -1,   -7, 	  -8,   -5, 	   6,   -5, 	  -1,   -5
.2byte   -1,   -8, 	  -8,   -4, 	   6,   -5, 	  -1,   -4
.2byte   -1,   -8, 	  -8,   -5, 	   6,   -4, 	  -1,   -4
.2byte    2,   -9, 	   5,   -5, 	  -7,   -3, 	   1,   -5
.2byte    2,   -9, 	   5,   -5, 	  -7,   -3, 	   0,   -5
.2byte    2,   -9, 	   5,   -5, 	  -7,   -3, 	   0,   -5
.2byte    3,   -8, 	   7,   -5, 	  -6,   -4, 	   0,   -6
.2byte    3,   -8, 	   7,   -5, 	  -6,   -4, 	   1,   -6
.2byte    3,   -9, 	   5,   -4, 	  -7,   -4, 	   1,   -4
.2byte    2,   -9, 	   5,   -5, 	  -7,   -2, 	   1,   -4
.2byte    6,  -10, 	   3,   -5, 	   1,   -3, 	   0,   -4
.2byte    6,  -10, 	   3,   -5, 	   1,   -3, 	   0,   -4
.2byte    6,  -10, 	   3,   -5, 	   1,   -3, 	   0,   -4
.2byte    7,   -8, 	   2,   -5, 	   2,   -3, 	  -3,   -6
.2byte    7,   -8, 	   2,   -5, 	   2,   -3, 	  -3,   -6
.2byte    6,  -10, 	   3,   -4, 	   0,   -3, 	   1,   -3
.2byte    6,  -10, 	   2,   -4, 	   0,   -3, 	   1,   -3
.2byte    6,   -9, 	   3,   -4, 	   1,   -3, 	  -1,   -3
.2byte    6,   -9, 	   2,   -4, 	   1,   -3, 	  -1,   -2
.2byte    4,  -11, 	  -5,   -5, 	   6,   -4, 	  -1,   -3
.2byte    4,  -11, 	  -5,   -5, 	   6,   -4, 	  -2,   -4
.2byte    4,  -11, 	  -5,   -5, 	   6,   -4, 	  -2,   -3
.2byte    4,   -9, 	  -3,   -6, 	   5,   -3, 	  -2,   -5
.2byte    4,   -9, 	  -5,   -6, 	   5,   -3, 	  -3,   -5
.2byte    4,  -11, 	  -5,   -6, 	   6,   -5, 	  -1,   -3
.2byte    4,  -11, 	  -5,   -6, 	   6,   -5, 	  -1,   -4
.2byte    4,   -9, 	  -6,   -6, 	   6,   -4, 	  -1,   -2
.2byte    4,   -9, 	  -6,   -6, 	   6,   -4, 	  -2,   -3
.2byte   -1,   -9, 	   5,   -4, 	  -7,   -4, 	  -1,   -5
.2byte   -1,  -10, 	   5,   -4, 	  -7,   -4, 	  -1,   -6
.2byte   -1,   -9, 	   5,   -2, 	  -7,   -2, 	  -1,   -5
.2byte   -1,  -11, 	   3,   -4, 	  -5,   -4, 	  -1,   -6
.2byte   -1,  -11, 	   3,   -4, 	  -5,   -4, 	  -1,   -6
.2byte    1,   -9, 	   5,   -4, 	  -4,   -6, 	  -2,   -4
.2byte    1,   -9, 	   5,   -4, 	  -4,   -6, 	  -2,   -4
.2byte   -5,   -9, 	   2,   -6, 	  -7,   -4, 	  -1,   -4
.2byte   -5,   -9, 	   2,   -6, 	  -7,   -4, 	  -1,   -4
.2byte   -6,  -11, 	   3,   -5, 	  -8,   -4, 	  -1,   -3
.2byte   -6,  -11, 	   3,   -5, 	  -8,   -4, 	   0,   -4
.2byte   -6,  -11, 	   3,   -5, 	  -8,   -4, 	   0,   -3
.2byte   -6,   -9, 	   1,   -6, 	  -7,   -3, 	   0,   -5
.2byte   -6,   -9, 	   3,   -6, 	  -7,   -3, 	   1,   -5
.2byte   -6,  -11, 	   3,   -6, 	  -8,   -5, 	  -1,   -3
.2byte   -6,  -11, 	   3,   -6, 	  -8,   -5, 	  -1,   -4
.2byte   -6,   -9, 	   4,   -6, 	  -8,   -4, 	  -1,   -2
.2byte   -6,   -9, 	   4,   -6, 	  -8,   -4, 	   0,   -3
.2byte   -8,  -10, 	  -5,   -5, 	  -3,   -3, 	  -2,   -4
.2byte   -8,  -10, 	  -5,   -5, 	  -3,   -3, 	  -2,   -4
.2byte   -8,  -10, 	  -5,   -5, 	  -3,   -3, 	  -2,   -4
.2byte   -9,   -8, 	  -4,   -5, 	  -4,   -3, 	   1,   -6
.2byte   -9,   -8, 	  -4,   -5, 	  -4,   -3, 	   1,   -6
.2byte   -8,  -10, 	  -5,   -4, 	  -2,   -3, 	  -3,   -3
.2byte   -8,  -10, 	  -4,   -4, 	  -2,   -3, 	  -3,   -3
.2byte   -8,   -9, 	  -5,   -4, 	  -3,   -3, 	  -1,   -3
.2byte   -8,   -9, 	  -4,   -4, 	  -3,   -3, 	  -1,   -2
.2byte   -4,   -9, 	  -7,   -5, 	   5,   -3, 	  -3,   -5
.2byte   -4,   -9, 	  -7,   -5, 	   5,   -3, 	  -2,   -5
.2byte   -4,   -9, 	  -7,   -5, 	   5,   -3, 	  -2,   -5
.2byte   -5,   -8, 	  -9,   -5, 	   4,   -4, 	  -2,   -6
.2byte   -5,   -8, 	  -9,   -5, 	   4,   -4, 	  -3,   -6
.2byte   -5,   -9, 	  -7,   -4, 	   5,   -4, 	  -3,   -4
.2byte   -4,   -9, 	  -7,   -5, 	   5,   -2, 	  -3,   -4
.2byte   -1,   -8, 	  -8,   -4, 	   6,   -4, 	  -1,   -5
.2byte   -1,   -8, 	  -8,   -4, 	   6,   -4, 	  -1,   -5
.2byte   -1,   -8, 	  -8,   -4, 	   6,   -4, 	  -1,   -5
.2byte   -1,   -7, 	  -8,   -5, 	   6,   -5, 	  -1,   -5
.2byte   -1,   -7, 	  -8,   -5, 	   6,   -5, 	  -1,   -5
.2byte   -1,   -8, 	  -8,   -4, 	   6,   -5, 	  -1,   -4
.2byte   -1,   -8, 	  -8,   -5, 	   6,   -4, 	  -1,   -4
.2byte    2,   -9, 	   5,   -5, 	  -7,   -3, 	   1,   -5
.2byte    2,   -9, 	   5,   -5, 	  -7,   -3, 	   0,   -5
.2byte    2,   -9, 	   5,   -5, 	  -7,   -3, 	   0,   -5
.2byte    3,   -8, 	   7,   -5, 	  -6,   -4, 	   0,   -6
.2byte    3,   -8, 	   7,   -5, 	  -6,   -4, 	   1,   -6
.2byte    3,   -9, 	   5,   -4, 	  -7,   -4, 	   1,   -4
.2byte    2,   -9, 	   5,   -5, 	  -7,   -2, 	   1,   -4
.2byte    6,  -10, 	   3,   -5, 	   1,   -3, 	   0,   -4
.2byte    6,  -10, 	   3,   -5, 	   1,   -3, 	   0,   -4
.2byte    6,  -10, 	   3,   -5, 	   1,   -3, 	   0,   -4
.2byte    7,   -8, 	   2,   -5, 	   2,   -3, 	  -3,   -6
.2byte    7,   -8, 	   2,   -5, 	   2,   -3, 	  -3,   -6
.2byte    6,  -10, 	   3,   -4, 	   0,   -3, 	   1,   -3
.2byte    6,  -10, 	   2,   -4, 	   0,   -3, 	   1,   -3
.2byte    6,   -9, 	   3,   -4, 	   1,   -3, 	  -1,   -3
.2byte    6,   -9, 	   2,   -4, 	   1,   -3, 	  -1,   -2
.2byte    4,  -11, 	  -5,   -5, 	   6,   -4, 	  -1,   -3
.2byte    4,  -11, 	  -5,   -5, 	   6,   -4, 	  -2,   -4
.2byte    4,  -11, 	  -5,   -5, 	   6,   -4, 	  -2,   -3
.2byte    4,   -9, 	  -3,   -6, 	   5,   -3, 	  -2,   -5
.2byte    4,   -9, 	  -5,   -6, 	   5,   -3, 	  -3,   -5
.2byte    4,  -11, 	  -5,   -6, 	   6,   -5, 	  -1,   -3
.2byte    4,  -11, 	  -5,   -6, 	   6,   -5, 	  -1,   -4
.2byte    4,   -9, 	  -6,   -6, 	   6,   -4, 	  -1,   -2
.2byte    4,   -9, 	  -6,   -6, 	   6,   -4, 	  -2,   -3
.2byte   -1,   -9, 	   5,   -4, 	  -7,   -4, 	  -1,   -5
.2byte   -1,  -10, 	   5,   -4, 	  -7,   -4, 	  -1,   -6
.2byte   -1,   -9, 	   5,   -2, 	  -7,   -2, 	  -1,   -5
.2byte   -1,  -11, 	   3,   -4, 	  -5,   -4, 	  -1,   -6
.2byte   -1,  -11, 	   3,   -4, 	  -5,   -4, 	  -1,   -6
.2byte    1,   -9, 	   5,   -4, 	  -4,   -6, 	  -2,   -4
.2byte    1,   -9, 	   5,   -4, 	  -4,   -6, 	  -2,   -4
.2byte   -5,   -9, 	   2,   -6, 	  -7,   -4, 	  -1,   -4
.2byte   -5,   -9, 	   2,   -6, 	  -7,   -4, 	  -1,   -4
.2byte   -6,  -11, 	   3,   -5, 	  -8,   -4, 	  -1,   -3
.2byte   -6,  -11, 	   3,   -5, 	  -8,   -4, 	   0,   -4
.2byte   -6,  -11, 	   3,   -5, 	  -8,   -4, 	   0,   -3
.2byte   -6,   -9, 	   1,   -6, 	  -7,   -3, 	   0,   -5
.2byte   -6,   -9, 	   3,   -6, 	  -7,   -3, 	   1,   -5
.2byte   -6,  -11, 	   3,   -6, 	  -8,   -5, 	  -1,   -3
.2byte   -6,  -11, 	   3,   -6, 	  -8,   -5, 	  -1,   -4
.2byte   -6,   -9, 	   4,   -6, 	  -8,   -4, 	  -1,   -2
.2byte   -6,   -9, 	   4,   -6, 	  -8,   -4, 	   0,   -3
.2byte   -8,  -10, 	  -5,   -5, 	  -3,   -3, 	  -2,   -4
.2byte   -8,  -10, 	  -5,   -5, 	  -3,   -3, 	  -2,   -4
.2byte   -8,  -10, 	  -5,   -5, 	  -3,   -3, 	  -2,   -4
.2byte   -9,   -8, 	  -4,   -5, 	  -4,   -3, 	   1,   -6
.2byte   -9,   -8, 	  -4,   -5, 	  -4,   -3, 	   1,   -6
.2byte   -8,  -10, 	  -5,   -4, 	  -2,   -3, 	  -3,   -3
.2byte   -8,  -10, 	  -4,   -4, 	  -2,   -3, 	  -3,   -3
.2byte   -8,   -9, 	  -5,   -4, 	  -3,   -3, 	  -1,   -3
.2byte   -8,   -9, 	  -4,   -4, 	  -3,   -3, 	  -1,   -2
.2byte   -4,   -9, 	  -7,   -5, 	   5,   -3, 	  -3,   -5
.2byte   -4,   -9, 	  -7,   -5, 	   5,   -3, 	  -2,   -5
.2byte   -4,   -9, 	  -7,   -5, 	   5,   -3, 	  -2,   -5
.2byte   -5,   -8, 	  -9,   -5, 	   4,   -4, 	  -2,   -6
.2byte   -5,   -8, 	  -9,   -5, 	   4,   -4, 	  -3,   -6
.2byte   -5,   -9, 	  -7,   -4, 	   5,   -4, 	  -3,   -4
.2byte   -4,   -9, 	  -7,   -5, 	   5,   -2, 	  -3,   -4
.2byte   -1,   -8, 	  -8,   -4, 	   6,   -4, 	  -1,   -5
.2byte   -4,   -9, 	  -7,   -5, 	   5,   -3, 	  -2,   -5
.2byte   -8,  -10, 	  -5,   -5, 	  -3,   -3, 	  -2,   -4
.2byte   -6,  -11, 	   3,   -5, 	  -8,   -4, 	   0,   -4
.2byte   -1,  -10, 	   5,   -4, 	  -7,   -4, 	  -1,   -6
.2byte    4,  -11, 	  -5,   -5, 	   6,   -4, 	  -2,   -4
.2byte    6,  -10, 	   3,   -5, 	   1,   -3, 	   0,   -4
.2byte    2,   -9, 	   5,   -5, 	  -7,   -3, 	   0,   -5
.2byte   -1,   -8, 	  -8,   -4, 	   6,   -4, 	  -1,   -5
.2byte   -1,   -8, 	  -8,   -4, 	   6,   -5, 	  -1,   -4
.2byte   -1,   -8, 	  -8,   -5, 	   6,   -4, 	  -1,   -4
.2byte    2,   -9, 	   5,   -5, 	  -7,   -3, 	   1,   -5
.2byte    3,   -9, 	   5,   -4, 	  -7,   -4, 	   1,   -4
.2byte    2,   -9, 	   5,   -5, 	  -7,   -2, 	   1,   -4
.2byte    6,  -10, 	   3,   -5, 	   1,   -3, 	   0,   -4
.2byte    6,  -10, 	   3,   -4, 	   0,   -3, 	   1,   -3
.2byte    6,  -10, 	   2,   -4, 	   0,   -3, 	   1,   -3
.2byte    6,   -9, 	   3,   -4, 	   1,   -3, 	  -1,   -3
.2byte    6,   -9, 	   2,   -4, 	   1,   -3, 	  -1,   -2
.2byte    6,  -10, 	   2,   -4, 	   0,   -3, 	   1,   -3
.2byte    6,   -9, 	   2,   -4, 	   1,   -3, 	  -1,   -2
.2byte    4,  -11, 	  -5,   -5, 	   6,   -4, 	  -1,   -3
.2byte    4,  -11, 	  -5,   -6, 	   6,   -5, 	  -1,   -3
.2byte    4,  -11, 	  -5,   -6, 	   6,   -5, 	  -1,   -4
.2byte    4,   -9, 	  -6,   -6, 	   6,   -4, 	  -1,   -2
.2byte    4,   -9, 	  -6,   -6, 	   6,   -4, 	  -2,   -3
.2byte    4,  -11, 	  -5,   -6, 	   6,   -5, 	  -1,   -4
.2byte    4,   -9, 	  -6,   -6, 	   6,   -4, 	  -2,   -3
.2byte   -1,   -9, 	   5,   -4, 	  -7,   -4, 	  -1,   -5
.2byte    1,   -9, 	   5,   -4, 	  -4,   -6, 	  -2,   -4
.2byte    1,   -9, 	   5,   -4, 	  -4,   -6, 	  -2,   -4
.2byte   -5,   -9, 	   2,   -6, 	  -7,   -4, 	  -1,   -4
.2byte   -5,   -9, 	   2,   -6, 	  -7,   -4, 	  -1,   -4
.2byte    1,   -9, 	   5,   -4, 	  -4,   -6, 	  -2,   -4
.2byte   -5,   -9, 	   2,   -6, 	  -7,   -4, 	  -1,   -4
.2byte   -6,  -11, 	   3,   -5, 	  -8,   -4, 	  -1,   -3
.2byte   -6,  -11, 	   3,   -6, 	  -8,   -5, 	  -1,   -3
.2byte   -6,  -11, 	   3,   -6, 	  -8,   -5, 	  -1,   -4
.2byte   -6,   -9, 	   4,   -6, 	  -8,   -4, 	  -1,   -2
.2byte   -6,   -9, 	   4,   -6, 	  -8,   -4, 	   0,   -3
.2byte   -6,  -11, 	   3,   -6, 	  -8,   -5, 	  -1,   -4
.2byte   -6,   -9, 	   4,   -6, 	  -8,   -4, 	   0,   -3
.2byte   -8,  -10, 	  -5,   -5, 	  -3,   -3, 	  -2,   -4
.2byte   -8,  -10, 	  -5,   -4, 	  -2,   -3, 	  -3,   -3
.2byte   -8,  -10, 	  -4,   -4, 	  -2,   -3, 	  -3,   -3
.2byte   -8,   -9, 	  -5,   -4, 	  -3,   -3, 	  -1,   -3
.2byte   -8,   -9, 	  -4,   -4, 	  -3,   -3, 	  -1,   -2
.2byte   -8,  -10, 	  -4,   -4, 	  -2,   -3, 	  -3,   -3
.2byte   -8,   -9, 	  -4,   -4, 	  -3,   -3, 	  -1,   -2
.2byte   -4,   -9, 	  -7,   -5, 	   5,   -3, 	  -3,   -5
.2byte   -5,   -9, 	  -7,   -4, 	   5,   -4, 	  -3,   -4
.2byte   -4,   -9, 	  -7,   -5, 	   5,   -2, 	  -3,   -4
.2byte   -3,   -8, 	  -6,   -5, 	   5,   -3, 	  -1,   -5
.2byte   -3,   -9, 	  -6,   -5, 	   5,   -3, 	  -1,   -5
.2byte    0,   -9, 	  -4,   -7, 	   4,   -7, 	   0,   -6
.2byte    2,   -9, 	   6,  -10, 	  -2,   -7, 	   1,   -5
.2byte    4,   -9, 	   6,   -9, 	   3,   -8, 	   0,   -4
.2byte    4,   -9, 	   2,  -12, 	   8,  -10, 	   1,   -3
.2byte    0,   -8, 	   6,   -6, 	  -6,   -6, 	   0,   -5
.2byte   -5,   -9, 	  -3,  -12, 	  -9,  -10, 	  -2,   -3
.2byte   -5,   -9, 	  -7,   -9, 	  -4,   -8, 	  -1,   -4
.2byte   -3,   -9, 	  -7,  -10, 	   1,   -7, 	  -2,   -5
.2byte   -1,   -8, 	  -8,   -4, 	   6,   -4, 	  -1,   -5
.2byte   -1,   -8, 	  -8,   -4, 	   6,   -5, 	  -1,   -4
.2byte   -1,   -8, 	  -8,   -5, 	   6,   -4, 	  -1,   -4
.2byte    2,   -9, 	   5,   -5, 	  -7,   -3, 	   1,   -5
.2byte    3,   -9, 	   5,   -4, 	  -7,   -4, 	   1,   -4
.2byte    2,   -9, 	   5,   -5, 	  -7,   -2, 	   1,   -4
.2byte    6,  -10, 	   3,   -5, 	   1,   -3, 	   0,   -4
.2byte    6,  -10, 	   2,   -4, 	   0,   -3, 	   1,   -3
.2byte    6,   -9, 	   2,   -4, 	   1,   -3, 	  -1,   -2
.2byte    4,  -11, 	  -5,   -5, 	   6,   -4, 	  -1,   -3
.2byte    4,  -11, 	  -5,   -6, 	   6,   -5, 	  -1,   -4
.2byte    4,   -9, 	  -6,   -6, 	   6,   -4, 	  -2,   -3
.2byte   -1,   -9, 	   5,   -4, 	  -7,   -4, 	  -1,   -5
.2byte    1,   -9, 	   5,   -4, 	  -4,   -6, 	  -2,   -4
.2byte   -5,   -9, 	   2,   -6, 	  -7,   -4, 	  -1,   -4
.2byte   -6,  -11, 	   3,   -5, 	  -8,   -4, 	  -1,   -3
.2byte   -6,  -11, 	   3,   -6, 	  -8,   -5, 	  -1,   -4
.2byte   -6,   -9, 	   4,   -6, 	  -8,   -4, 	   0,   -3
.2byte   -8,  -10, 	  -5,   -5, 	  -3,   -3, 	  -2,   -4
.2byte   -8,  -10, 	  -4,   -4, 	  -2,   -3, 	  -3,   -3
.2byte   -8,   -9, 	  -4,   -4, 	  -3,   -3, 	  -1,   -2
.2byte   -4,   -9, 	  -7,   -5, 	   5,   -3, 	  -3,   -5
.2byte   -5,   -9, 	  -7,   -4, 	   5,   -4, 	  -3,   -4
.2byte   -4,   -9, 	  -7,   -5, 	   5,   -2, 	  -3,   -4
.2byte   -1,   -7, 	  -8,   -5, 	   6,   -5, 	  -1,   -5
.2byte   -5,   -8, 	  -9,   -5, 	   4,   -4, 	  -2,   -6
.2byte   -9,   -8, 	  -4,   -5, 	  -4,   -3, 	   1,   -6
.2byte   -6,   -9, 	   1,   -6, 	  -7,   -3, 	   0,   -5
.2byte   -1,  -11, 	   3,   -4, 	  -5,   -4, 	  -1,   -6
.2byte    4,   -9, 	  -3,   -6, 	   5,   -3, 	  -2,   -5
.2byte    7,   -8, 	   2,   -5, 	   2,   -3, 	  -3,   -6
.2byte    3,   -8, 	   7,   -5, 	  -6,   -4, 	   0,   -6
.2byte   -1,   -7, 	  -8,   -5, 	   6,   -5, 	  -1,   -5
.2byte    3,   -8, 	   7,   -5, 	  -6,   -4, 	   0,   -6
.2byte    7,   -8, 	   2,   -5, 	   2,   -3, 	  -3,   -6
.2byte    4,   -9, 	  -3,   -6, 	   5,   -3, 	  -2,   -5
.2byte   -1,  -11, 	   3,   -4, 	  -5,   -4, 	  -1,   -6
.2byte   -6,   -9, 	   1,   -6, 	  -7,   -3, 	   0,   -5
.2byte   -9,   -8, 	  -4,   -5, 	  -4,   -3, 	   1,   -6
.2byte   -5,   -8, 	  -9,   -5, 	   4,   -4, 	  -2,   -6
.2byte   -1,   -8, 	  -8,   -4, 	   6,   -4, 	  -1,   -5
.2byte   -1,   -8, 	  -8,   -4, 	   6,   -4, 	  -1,   -5
.2byte   -1,   -8, 	  -8,   -4, 	   6,   -4, 	  -1,   -5
.2byte    2,   -9, 	   5,   -5, 	  -7,   -3, 	   1,   -5
.2byte    2,   -9, 	   5,   -5, 	  -7,   -3, 	   0,   -5
.2byte    2,   -9, 	   5,   -5, 	  -7,   -3, 	   0,   -5
.2byte    6,  -10, 	   3,   -5, 	   1,   -3, 	   0,   -4
.2byte    6,  -10, 	   3,   -5, 	   1,   -3, 	   0,   -4
.2byte    6,  -10, 	   3,   -5, 	   1,   -3, 	   0,   -4
.2byte    4,  -11, 	  -5,   -5, 	   6,   -4, 	  -1,   -3
.2byte    4,  -11, 	  -5,   -5, 	   6,   -4, 	  -2,   -3
.2byte    4,  -11, 	  -5,   -5, 	   6,   -4, 	  -2,   -4
.2byte   -1,   -9, 	   5,   -4, 	  -7,   -4, 	  -1,   -5
.2byte   -1,   -9, 	   5,   -2, 	  -7,   -2, 	  -1,   -5
.2byte   -1,  -10, 	   5,   -4, 	  -7,   -4, 	  -1,   -6
.2byte   -6,  -11, 	   3,   -5, 	  -8,   -4, 	  -1,   -3
.2byte   -6,  -11, 	   3,   -5, 	  -8,   -4, 	   0,   -3
.2byte   -6,  -11, 	   3,   -5, 	  -8,   -4, 	   0,   -4
.2byte   -8,  -10, 	  -5,   -5, 	  -3,   -3, 	  -2,   -4
.2byte   -8,  -10, 	  -5,   -5, 	  -3,   -3, 	  -2,   -4
.2byte   -8,  -10, 	  -5,   -5, 	  -3,   -3, 	  -2,   -4
.2byte   -4,   -9, 	  -7,   -5, 	   5,   -3, 	  -3,   -5
.2byte   -4,   -9, 	  -7,   -5, 	   5,   -3, 	  -2,   -5
.2byte   -4,   -9, 	  -7,   -5, 	   5,   -3, 	  -2,   -5
.2byte   -1,   -8, 	  -8,   -4, 	   6,   -4, 	  -1,   -5
.2byte   -4,   -9, 	  -7,   -5, 	   5,   -3, 	  -2,   -5
.2byte   -8,  -10, 	  -5,   -5, 	  -3,   -3, 	  -2,   -4
.2byte   -6,  -11, 	   3,   -5, 	  -8,   -4, 	   0,   -4
.2byte   -1,  -10, 	   5,   -4, 	  -7,   -4, 	  -1,   -6
.2byte    4,  -11, 	  -5,   -5, 	   6,   -4, 	  -2,   -4
.2byte    6,  -10, 	   3,   -5, 	   1,   -3, 	   0,   -4
.2byte    2,   -9, 	   5,   -5, 	  -7,   -3, 	   0,   -5
.2byte   -1,   -8, 	  -8,   -4, 	   6,   -4, 	  -1,   -5
.2byte   -4,   -9, 	  -7,   -5, 	   5,   -3, 	  -3,   -5
.2byte   -8,  -10, 	  -5,   -5, 	  -3,   -3, 	  -2,   -4
.2byte   -6,  -11, 	   3,   -5, 	  -8,   -4, 	  -1,   -3
.2byte   -1,   -9, 	   5,   -4, 	  -7,   -4, 	  -1,   -5
.2byte    5,  -11, 	  -4,   -5, 	   7,   -4, 	   0,   -3
.2byte    7,  -10, 	   4,   -5, 	   2,   -3, 	   1,   -4
.2byte    3,   -9, 	   6,   -5, 	  -6,   -3, 	   2,   -5
sVolbeatAnimTable1:
.4byte sVolbeatAnims_1_1
.4byte sVolbeatAnims_1_2
.4byte sVolbeatAnims_1_3
.4byte sVolbeatAnims_1_4
.4byte sVolbeatAnims_1_5
.4byte sVolbeatAnims_1_6
.4byte sVolbeatAnims_1_7
.4byte sVolbeatAnims_1_8
sVolbeatAnimTable2:
.4byte sVolbeatAnims_2_1
.4byte sVolbeatAnims_2_2
.4byte sVolbeatAnims_2_3
.4byte sVolbeatAnims_2_4
.4byte sVolbeatAnims_2_5
.4byte sVolbeatAnims_2_6
.4byte sVolbeatAnims_2_7
.4byte sVolbeatAnims_2_8
sVolbeatAnimTable3:
.4byte sVolbeatAnims_3_1
.4byte sVolbeatAnims_3_2
.4byte sVolbeatAnims_3_3
.4byte sVolbeatAnims_3_4
.4byte sVolbeatAnims_3_5
.4byte sVolbeatAnims_3_6
.4byte sVolbeatAnims_3_7
.4byte sVolbeatAnims_3_8
sVolbeatAnimTable4:
.4byte sVolbeatAnims_4_1
.4byte sVolbeatAnims_4_2
.4byte sVolbeatAnims_4_3
.4byte sVolbeatAnims_4_4
.4byte sVolbeatAnims_4_5
.4byte sVolbeatAnims_4_6
.4byte sVolbeatAnims_4_7
.4byte sVolbeatAnims_4_8
sVolbeatAnimTable5:
.4byte sVolbeatAnims_5_1
.4byte sVolbeatAnims_5_2
.4byte sVolbeatAnims_5_3
.4byte sVolbeatAnims_5_4
.4byte sVolbeatAnims_5_5
.4byte sVolbeatAnims_5_6
.4byte sVolbeatAnims_5_7
.4byte sVolbeatAnims_5_8
sVolbeatAnimTable6:
.4byte sVolbeatAnims_6_1
.4byte sVolbeatAnims_6_1
.4byte sVolbeatAnims_6_1
.4byte sVolbeatAnims_6_1
.4byte sVolbeatAnims_6_1
.4byte sVolbeatAnims_6_1
.4byte sVolbeatAnims_6_1
.4byte sVolbeatAnims_6_1
sVolbeatAnimTable7:
.4byte sVolbeatAnims_7_1
.4byte sVolbeatAnims_7_2
.4byte sVolbeatAnims_7_3
.4byte sVolbeatAnims_7_4
.4byte sVolbeatAnims_7_5
.4byte sVolbeatAnims_7_6
.4byte sVolbeatAnims_7_7
.4byte sVolbeatAnims_7_8
sVolbeatAnimTable8:
.4byte sVolbeatAnims_8_1
.4byte sVolbeatAnims_8_2
.4byte sVolbeatAnims_8_3
.4byte sVolbeatAnims_8_4
.4byte sVolbeatAnims_8_5
.4byte sVolbeatAnims_8_6
.4byte sVolbeatAnims_8_7
.4byte sVolbeatAnims_8_8
sVolbeatAnimTable9:
.4byte sVolbeatAnims_9_1
.4byte sVolbeatAnims_9_2
.4byte sVolbeatAnims_9_3
.4byte sVolbeatAnims_9_4
.4byte sVolbeatAnims_9_5
.4byte sVolbeatAnims_9_6
.4byte sVolbeatAnims_9_7
.4byte sVolbeatAnims_9_8
sVolbeatAnimTable10:
.4byte sVolbeatAnims_10_1
.4byte sVolbeatAnims_10_2
.4byte sVolbeatAnims_10_3
.4byte sVolbeatAnims_10_4
.4byte sVolbeatAnims_10_5
.4byte sVolbeatAnims_10_6
.4byte sVolbeatAnims_10_7
.4byte sVolbeatAnims_10_8
sVolbeatAnimTable11:
.4byte sVolbeatAnims_11_1
.4byte sVolbeatAnims_11_2
.4byte sVolbeatAnims_11_3
.4byte sVolbeatAnims_11_4
.4byte sVolbeatAnims_11_5
.4byte sVolbeatAnims_11_6
.4byte sVolbeatAnims_11_7
.4byte sVolbeatAnims_11_8
sVolbeatAnimTable12:
.4byte sVolbeatAnims_12_1
.4byte sVolbeatAnims_12_2
.4byte sVolbeatAnims_12_3
.4byte sVolbeatAnims_12_4
.4byte sVolbeatAnims_12_5
.4byte sVolbeatAnims_12_6
.4byte sVolbeatAnims_12_7
.4byte sVolbeatAnims_12_8
sVolbeatAnimTable13:
.4byte sVolbeatAnims_13_1
.4byte sVolbeatAnims_13_2
.4byte sVolbeatAnims_13_3
.4byte sVolbeatAnims_13_4
.4byte sVolbeatAnims_13_5
.4byte sVolbeatAnims_13_6
.4byte sVolbeatAnims_13_7
.4byte sVolbeatAnims_13_8
sAxAnimationsVolbeat:
.4byte sVolbeatAnimTable1
.4byte sVolbeatAnimTable2
.4byte sVolbeatAnimTable3
.4byte sVolbeatAnimTable4
.4byte sVolbeatAnimTable5
.4byte sVolbeatAnimTable6
.4byte sVolbeatAnimTable7
.4byte sVolbeatAnimTable8
.4byte sVolbeatAnimTable9
.4byte sVolbeatAnimTable10
.4byte sVolbeatAnimTable11
.4byte sVolbeatAnimTable12
.4byte sVolbeatAnimTable13
sAxSpritesVolbeat:
.4byte sVolbeatSprites1
.4byte sVolbeatSprites2
.4byte sVolbeatSprites3
.4byte sVolbeatSprites4
.4byte sVolbeatSprites5
.4byte sVolbeatSprites6
.4byte sVolbeatSprites7
.4byte sVolbeatSprites8
.4byte sVolbeatSprites9
.4byte sVolbeatSprites10
.4byte sVolbeatSprites11
.4byte sVolbeatSprites12
.4byte sVolbeatSprites13
.4byte sVolbeatSprites14
.4byte sVolbeatSprites15
.4byte sVolbeatSprites16
.4byte sVolbeatSprites17
.4byte sVolbeatSprites18
.4byte sVolbeatSprites19
.4byte sVolbeatSprites20
.4byte sVolbeatSprites21
.4byte sVolbeatSprites22
.4byte sVolbeatSprites23
.4byte sVolbeatSprites24
.4byte sVolbeatSprites25
.4byte sVolbeatSprites26
.4byte sVolbeatSprites27
.4byte sVolbeatSprites28
.4byte sVolbeatSprites29
.4byte sVolbeatSprites30
.4byte sVolbeatSprites31
.4byte sVolbeatSprites32
.4byte sVolbeatSprites33
.4byte sVolbeatSprites34
.4byte sVolbeatSprites35
.4byte sVolbeatSprites36
.4byte sVolbeatSprites37
.4byte sVolbeatSprites38
.4byte sVolbeatSprites39
.4byte sVolbeatSprites40
.4byte sVolbeatSprites41
.4byte sVolbeatSprites42
.4byte sVolbeatSprites43
.4byte sVolbeatSprites44
.4byte sVolbeatSprites45
.4byte sVolbeatSprites46
.4byte sVolbeatSprites47
.4byte sVolbeatSprites48
.4byte sVolbeatSprites49
.4byte sVolbeatSprites50
.4byte sVolbeatSprites51
.4byte sVolbeatSprites52
.4byte sVolbeatSprites53
.4byte sVolbeatSprites54
.4byte sVolbeatSprites55
sAxMainVolbeat:
ax_main sAxPosesVolbeat, sAxAnimationsVolbeat, 13, sAxSpritesVolbeat, sAxPositionsVolbeat
