.global gAxVoltorb
gAxVoltorb:
ax_siro sAxMainVoltorb
sVoltorbPose1:
ax_pose 0, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose2:
ax_pose 1, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose3:
ax_pose 2, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose4:
ax_pose 3, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose5:
ax_pose 4, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose6:
ax_pose 5, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose7:
ax_pose 6, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose8:
ax_pose 7, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose9:
ax_pose 8, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose10:
ax_pose 9, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose11:
ax_pose 10, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose12:
ax_pose 11, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose13:
ax_pose 12, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose14:
ax_pose 13, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose15:
ax_pose 14, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose16:
ax_pose 15, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose17:
ax_pose 16, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose18:
ax_pose 17, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose19:
ax_pose 18, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose20:
ax_pose 19, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose21:
ax_pose 20, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose22:
ax_pose 21, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose23:
ax_pose 22, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose24:
ax_pose 23, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose25:
ax_pose 0, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose26:
ax_pose 21, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose27:
ax_pose 18, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose28:
ax_pose 15, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose29:
ax_pose 12, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose30:
ax_pose 9, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose31:
ax_pose 6, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose32:
ax_pose 3, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose33:
ax_pose 0, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose34:
ax_pose 21, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose35:
ax_pose 18, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose36:
ax_pose 15, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose37:
ax_pose 12, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose38:
ax_pose 9, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose39:
ax_pose 6, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose40:
ax_pose 3, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose41:
ax_pose 0, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose42:
ax_pose 21, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose43:
ax_pose 18, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose44:
ax_pose 15, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose45:
ax_pose 12, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose46:
ax_pose 9, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose47:
ax_pose 6, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose48:
ax_pose 3, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose49:
ax_pose 0, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose50:
ax_pose 21, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose51:
ax_pose 18, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose52:
ax_pose 15, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose53:
ax_pose 12, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose54:
ax_pose 9, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose55:
ax_pose 6, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose56:
ax_pose 3, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose57:
ax_pose 24, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose58:
ax_pose 25, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose59:
ax_pose 26, 0x01e9, 0x80f0, 0x5c00
ax_pose_terminator
sVoltorbPose60:
ax_pose 27, 0x01e8, 0x90eb, 0x5c00
ax_pose_terminator
sVoltorbPose61:
ax_pose 28, 0x01ea, 0x90ec, 0x5c00
ax_pose_terminator
sVoltorbPose62:
ax_pose 29, 0x01eb, 0x90ed, 0x5c00
ax_pose_terminator
sVoltorbPose63:
ax_pose 30, 0x01ec, 0x80f0, 0x5c00
ax_pose_terminator
sVoltorbPose64:
ax_pose 29, 0x01eb, 0x80f3, 0x5c00
ax_pose_terminator
sVoltorbPose65:
ax_pose 28, 0x01ea, 0x80f4, 0x5c00
ax_pose_terminator
sVoltorbPose66:
ax_pose 27, 0x01e8, 0x80f5, 0x5c00
ax_pose_terminator
sVoltorbPose67:
ax_pose 0, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose68:
ax_pose 21, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose69:
ax_pose 18, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose70:
ax_pose 15, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose71:
ax_pose 12, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose72:
ax_pose 9, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose73:
ax_pose 6, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose74:
ax_pose 3, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose75:
ax_pose 0, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose76:
ax_pose 21, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose77:
ax_pose 18, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose78:
ax_pose 15, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose79:
ax_pose 12, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose80:
ax_pose 9, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose81:
ax_pose 6, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose82:
ax_pose 3, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose83:
ax_pose 0, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose84:
ax_pose 3, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose85:
ax_pose 6, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose86:
ax_pose 9, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose87:
ax_pose 12, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose88:
ax_pose 15, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose89:
ax_pose 18, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose90:
ax_pose 21, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose91:
ax_pose 0, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose92:
ax_pose 2, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose93:
ax_pose 1, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose94:
ax_pose 3, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose95:
ax_pose 5, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose96:
ax_pose 4, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose97:
ax_pose 6, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose98:
ax_pose 8, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose99:
ax_pose 7, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose100:
ax_pose 9, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose101:
ax_pose 11, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose102:
ax_pose 10, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose103:
ax_pose 12, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose104:
ax_pose 14, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose105:
ax_pose 13, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose106:
ax_pose 15, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose107:
ax_pose 17, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose108:
ax_pose 16, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose109:
ax_pose 18, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose110:
ax_pose 20, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose111:
ax_pose 19, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose112:
ax_pose 21, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose113:
ax_pose 23, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose114:
ax_pose 22, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose115:
ax_pose 0, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose116:
ax_pose 21, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose117:
ax_pose 18, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose118:
ax_pose 15, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose119:
ax_pose 12, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose120:
ax_pose 9, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose121:
ax_pose 6, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose122:
ax_pose 3, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose123:
ax_pose 0, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose124:
ax_pose 21, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose125:
ax_pose 18, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose126:
ax_pose 15, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose127:
ax_pose 12, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose128:
ax_pose 9, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose129:
ax_pose 6, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
sVoltorbPose130:
ax_pose 3, 0x01f1, 0x40f8, 0x5c00
ax_pose_terminator
.align 2
sVoltorbAnims_1_1:
ax_anim 6, 0, 0, 0, 0, 0, 0,
ax_anim 6, 0, 2, 0, -2, 0, -2,
ax_anim 10, 0, 2, 0, -3, 0, -3,
ax_anim 4, 0, 2, 0, -4, 0, -2,
ax_anim 4, 0, 0, 0, -1, 0, 1,
ax_anim 4, 0, 1, 0, 2, 0, 2,
ax_anim 6, 0, 1, 0, 1, 0, 1,
ax_anim 8, 0, 1, 0, 3, 0, 3,
ax_anim_terminator
sVoltorbAnims_1_2:
ax_anim 6, 0, 3, 0, 0, 0, 0,
ax_anim 6, 0, 5, -2, -2, -2, -2,
ax_anim 10, 0, 5, -3, -3, -3, -3,
ax_anim 4, 0, 5, -2, -3, -2, -2,
ax_anim 4, 0, 3, 2, 0, 2, 2,
ax_anim 4, 0, 4, 3, 3, 3, 3,
ax_anim 6, 0, 4, 4, 2, 4, 4,
ax_anim 8, 0, 4, 4, 4, 4, 4,
ax_anim_terminator
sVoltorbAnims_1_3:
ax_anim 6, 0, 6, 0, 0, 0, 0,
ax_anim 6, 0, 8, -3, 0, -3, 0,
ax_anim 10, 0, 8, -4, 0, -4, 0,
ax_anim 4, 0, 8, -2, -2, -2, 0,
ax_anim 4, 0, 6, 2, -3, 2, 0,
ax_anim 4, 0, 7, 3, 0, 3, 0,
ax_anim 6, 0, 7, 4, -1, 4, 0,
ax_anim 8, 0, 7, 4, 0, 4, 0,
ax_anim_terminator
sVoltorbAnims_1_4:
ax_anim 6, 0, 9, 0, 0, 0, 0,
ax_anim 6, 0, 11, -3, 3, -3, 3,
ax_anim 10, 0, 11, -4, 4, -4, 4,
ax_anim 4, 0, 11, -2, 0, -2, 2,
ax_anim 4, 0, 9, 1, -4, 1, -1,
ax_anim 4, 0, 10, 3, -3, 3, -3,
ax_anim 6, 0, 10, 4, -5, 4, -4,
ax_anim 8, 0, 10, 4, -4, 4, -4,
ax_anim_terminator
sVoltorbAnims_1_5:
ax_anim 6, 0, 12, 0, 0, 0, 0,
ax_anim 6, 0, 14, 0, 2, 0, 2,
ax_anim 10, 0, 14, 0, 4, 0, 4,
ax_anim 4, 0, 14, 0, -3, 0, 1,
ax_anim 4, 0, 12, 0, -4, 0, -2,
ax_anim 4, 0, 13, 0, -4, 0, -3,
ax_anim 6, 0, 13, 0, -6, 0, -4,
ax_anim 8, 0, 13, 0, -4, 0, -3,
ax_anim_terminator
sVoltorbAnims_1_6:
ax_anim 6, 0, 15, 0, 0, 0, 0,
ax_anim 6, 0, 17, 3, 3, 3, 3,
ax_anim 10, 0, 17, 4, 4, 4, 4,
ax_anim 4, 0, 17, 2, 0, 2, 2,
ax_anim 4, 0, 15, -1, -4, -1, -1,
ax_anim 4, 0, 16, -3, -3, -3, -3,
ax_anim 6, 0, 16, -4, -5, -4, -4,
ax_anim 8, 0, 16, -4, -4, -4, -4,
ax_anim_terminator
sVoltorbAnims_1_7:
ax_anim 6, 0, 18, 0, 0, 0, 0,
ax_anim 6, 0, 20, 3, 0, 3, 0,
ax_anim 10, 0, 20, 4, 0, 4, 0,
ax_anim 4, 0, 20, 2, -2, 2, 0,
ax_anim 4, 0, 18, -2, -3, -2, 0,
ax_anim 4, 0, 19, -3, 0, -3, 0,
ax_anim 6, 0, 19, -4, -1, -4, 0,
ax_anim 8, 0, 19, -4, 0, -4, 0,
ax_anim_terminator
sVoltorbAnims_1_8:
ax_anim 6, 0, 21, 0, 0, 0, 0,
ax_anim 6, 0, 23, 2, -2, 2, -2,
ax_anim 10, 0, 23, 3, -3, 3, -3,
ax_anim 4, 0, 23, 2, -3, 2, -2,
ax_anim 4, 0, 21, -2, 0, -2, 2,
ax_anim 4, 0, 22, -3, 3, -3, 3,
ax_anim 6, 0, 22, -4, 2, -4, 4,
ax_anim 8, 0, 22, -4, 4, -4, 4,
ax_anim_terminator
.align 2
sVoltorbAnims_2_1:
ax_anim 2, 0, 31, -1, 0, -1, 0,
ax_anim 2, 0, 30, -2, 0, -2, 0,
ax_anim 6, 0, 29, -3, 0, -3, 0,
ax_anim 1, 0, 30, -2, 0, -2, 0,
ax_anim 1, 0, 31, 0, 3, 0, 3,
ax_anim 2, 0, 24, 4, 8, 4, 8,
ax_anim 2, 2, 25, 4, 16, 4, 16,
ax_anim 2, 0, 26, 0, 21, 0, 21,
ax_anim 2, 1, 27, 1, 21, 1, 21,
ax_anim 2, 0, 28, 0, 21, 0, 21,
ax_anim 2, 0, 29, 1, 21, 1, 21,
ax_anim 2, 0, 30, 0, 21, 0, 21,
ax_anim 2, 0, 31, -4, 18, -4, 18,
ax_anim 2, 0, 24, -4, 8, -4, 8,
ax_anim_terminator
sVoltorbAnims_2_2:
ax_anim 2, 0, 30, -1, 1, -1, 1,
ax_anim 2, 0, 29, -2, 2, -2, 2,
ax_anim 6, 0, 28, -3, 3, -3, 3,
ax_anim 1, 0, 29, -2, 2, -2, 2,
ax_anim 1, 0, 30, 5, 3, 5, 3,
ax_anim 2, 0, 31, 13, 6, 13, 6,
ax_anim 2, 2, 24, 22, 12, 22, 12,
ax_anim 2, 0, 25, 21, 21, 21, 21,
ax_anim 2, 1, 26, 22, 20, 22, 20,
ax_anim 2, 0, 27, 21, 21, 21, 21,
ax_anim 2, 0, 28, 22, 20, 22, 20,
ax_anim 2, 0, 29, 21, 21, 21, 21,
ax_anim 2, 0, 30, 11, 20, 11, 20,
ax_anim 2, 0, 31, 1, 8, 1, 8,
ax_anim_terminator
sVoltorbAnims_2_3:
ax_anim 2, 0, 29, 0, 1, 0, 1,
ax_anim 2, 0, 28, 0, 2, 0, 2,
ax_anim 6, 0, 27, 0, 3, 0, 3,
ax_anim 1, 0, 28, 0, 0, 0, 0,
ax_anim 1, 0, 29, 5, -4, 5, -4,
ax_anim 2, 0, 30, 13, -4, 13, -4,
ax_anim 2, 2, 31, 22, 0, 22, 0,
ax_anim 2, 0, 24, 22, 1, 22, 1,
ax_anim 2, 1, 25, 22, 0, 22, 0,
ax_anim 2, 0, 26, 22, 1, 22, 1,
ax_anim 2, 0, 27, 22, 0, 22, 0,
ax_anim 2, 0, 28, 22, 1, 22, 1,
ax_anim 2, 0, 29, 13, 4, 13, 4,
ax_anim 2, 0, 30, 1, 4, 1, 4,
ax_anim_terminator
sVoltorbAnims_2_4:
ax_anim 2, 0, 28, 0, 1, 0, 1,
ax_anim 2, 0, 27, 0, 2, 0, 2,
ax_anim 6, 0, 26, 0, 3, 0, 3,
ax_anim 1, 0, 27, 2, -5, 2, -5,
ax_anim 1, 0, 28, 4, -12, 4, -12,
ax_anim 2, 0, 29, 13, -20, 13, -20,
ax_anim 2, 2, 30, 22, -22, 22, -22,
ax_anim 2, 0, 31, 22, -21, 22, -21,
ax_anim 2, 1, 24, 22, -22, 22, -22,
ax_anim 2, 0, 25, 22, -21, 22, -21,
ax_anim 2, 0, 26, 22, -22, 22, -22,
ax_anim 2, 0, 27, 22, -21, 22, -21,
ax_anim 2, 0, 28, 16, -8, 16, -8,
ax_anim 2, 0, 29, 7, -2, 7, -2,
ax_anim_terminator
sVoltorbAnims_2_5:
ax_anim 2, 0, 29, -1, 0, -1, 0,
ax_anim 2, 0, 30, -2, 0, -2, 0,
ax_anim 6, 0, 31, -3, 0, -3, 0,
ax_anim 1, 0, 30, -2, 0, -2, 0,
ax_anim 1, 0, 29, 0, -3, 0, -3,
ax_anim 2, 0, 28, 4, -8, 4, -8,
ax_anim 2, 2, 27, 4, -16, 4, -16,
ax_anim 2, 0, 26, 0, -21, 0, -21,
ax_anim 2, 1, 25, 1, -21, 1, -21,
ax_anim 2, 0, 24, 0, -21, 0, -21,
ax_anim 2, 0, 31, 1, -21, 1, -21,
ax_anim 2, 0, 30, 0, -21, 0, -21,
ax_anim 2, 0, 29, -4, -18, -4, -18,
ax_anim 2, 0, 28, -4, -8, -4, -8,
ax_anim_terminator
sVoltorbAnims_2_6:
ax_anim 2, 0, 28, 0, 1, 0, 1,
ax_anim 2, 0, 29, 0, 2, 0, 2,
ax_anim 6, 0, 30, 0, 3, 0, 3,
ax_anim 1, 0, 29, -2, -5, -2, -5,
ax_anim 1, 0, 28, -4, -12, -4, -12,
ax_anim 2, 0, 27, -13, -20, -13, -20,
ax_anim 2, 2, 26, -22, -22, -22, -22,
ax_anim 2, 0, 25, -22, -21, -22, -21,
ax_anim 2, 1, 24, -22, -22, -22, -22,
ax_anim 2, 0, 31, -22, -21, -22, -21,
ax_anim 2, 0, 30, -22, -22, -22, -22,
ax_anim 2, 0, 29, -22, -21, -22, -21,
ax_anim 2, 0, 28, -16, -8, -16, -8,
ax_anim 2, 0, 27, -7, -2, -7, -2,
ax_anim_terminator
sVoltorbAnims_2_7:
ax_anim 2, 0, 27, 0, 1, 0, 1,
ax_anim 2, 0, 28, 0, 2, 0, 2,
ax_anim 6, 0, 29, 0, 3, 0, 3,
ax_anim 1, 0, 28, 0, 0, 0, 0,
ax_anim 1, 0, 27, -5, -4, -5, -4,
ax_anim 2, 0, 26, -13, -4, -13, -4,
ax_anim 2, 2, 25, -22, 0, -22, 0,
ax_anim 2, 0, 24, -22, 1, -22, 1,
ax_anim 2, 1, 31, -22, 0, -22, 0,
ax_anim 2, 0, 30, -22, 1, -22, 1,
ax_anim 2, 0, 29, -22, 0, -22, 0,
ax_anim 2, 0, 28, -22, 1, -22, 1,
ax_anim 2, 0, 27, -13, 4, -13, 4,
ax_anim 2, 0, 26, -1, 4, -1, 4,
ax_anim_terminator
sVoltorbAnims_2_8:
ax_anim 2, 0, 26, 1, 1, 1, 1,
ax_anim 2, 0, 27, 2, 2, 2, 2,
ax_anim 6, 0, 28, 3, 3, 3, 3,
ax_anim 1, 0, 27, 2, 2, 2, 2,
ax_anim 1, 0, 26, -5, 3, -5, 3,
ax_anim 2, 0, 25, -13, 6, -12, 6,
ax_anim 2, 2, 24, -22, 12, -22, 12,
ax_anim 2, 0, 31, -21, 21, -21, 21,
ax_anim 2, 1, 30, -22, 20, -22, 20,
ax_anim 2, 0, 29, -21, 21, -21, 21,
ax_anim 2, 0, 28, -22, 20, -22, 20,
ax_anim 2, 0, 27, -21, 21, -21, 21,
ax_anim 2, 0, 26, -11, 20, -11, 18,
ax_anim 2, 0, 25, -1, 8, -1, 8,
ax_anim_terminator
.align 2
sVoltorbAnims_3_1:
ax_anim 2, 0, 39, -1, 0, -1, 0,
ax_anim 2, 0, 38, -2, 0, -2, 0,
ax_anim 6, 0, 37, -3, 0, -3, 0,
ax_anim 1, 0, 38, -2, 0, -2, 0,
ax_anim 1, 0, 39, 0, 3, 0, 3,
ax_anim 2, 0, 32, 4, 8, 4, 8,
ax_anim 2, 2, 33, 4, 16, 4, 16,
ax_anim 2, 0, 34, 0, 21, 0, 21,
ax_anim 2, 1, 35, 1, 21, 1, 21,
ax_anim 2, 0, 36, 0, 21, 0, 21,
ax_anim 2, 0, 37, 1, 21, 1, 21,
ax_anim 2, 0, 38, 0, 21, 0, 21,
ax_anim 2, 0, 39, -4, 18, -4, 18,
ax_anim 2, 0, 32, -4, 8, -4, 8,
ax_anim_terminator
sVoltorbAnims_3_2:
ax_anim 2, 0, 38, -1, 1, -1, 1,
ax_anim 2, 0, 37, -2, 2, -2, 2,
ax_anim 6, 0, 36, -3, 3, -3, 3,
ax_anim 1, 0, 37, -2, 2, -2, 2,
ax_anim 1, 0, 38, 5, 3, 5, 3,
ax_anim 2, 0, 39, 13, 6, 13, 6,
ax_anim 2, 2, 32, 22, 12, 22, 12,
ax_anim 2, 0, 33, 21, 21, 21, 21,
ax_anim 2, 1, 34, 22, 20, 22, 20,
ax_anim 2, 0, 35, 21, 21, 21, 21,
ax_anim 2, 0, 36, 22, 20, 22, 20,
ax_anim 2, 0, 37, 21, 21, 21, 21,
ax_anim 2, 0, 38, 11, 20, 11, 20,
ax_anim 2, 0, 39, 1, 8, 1, 8,
ax_anim_terminator
sVoltorbAnims_3_3:
ax_anim 2, 0, 37, 0, 1, 0, 1,
ax_anim 2, 0, 36, 0, 2, 0, 2,
ax_anim 6, 0, 35, 0, 3, 0, 3,
ax_anim 1, 0, 36, 0, 0, 0, 0,
ax_anim 1, 0, 37, 5, -4, 5, -4,
ax_anim 2, 0, 38, 13, -4, 13, -4,
ax_anim 2, 2, 39, 22, 0, 22, 0,
ax_anim 2, 0, 32, 22, 1, 22, 1,
ax_anim 2, 1, 33, 22, 0, 22, 0,
ax_anim 2, 0, 34, 22, 1, 22, 1,
ax_anim 2, 0, 35, 22, 0, 22, 0,
ax_anim 2, 0, 36, 22, 1, 22, 1,
ax_anim 2, 0, 37, 13, 4, 13, 4,
ax_anim 2, 0, 38, 1, 4, 1, 4,
ax_anim_terminator
sVoltorbAnims_3_4:
ax_anim 2, 0, 36, 0, 1, 0, 1,
ax_anim 2, 0, 35, 0, 2, 0, 2,
ax_anim 6, 0, 34, 0, 3, 0, 3,
ax_anim 1, 0, 35, 2, -5, 2, -5,
ax_anim 1, 0, 36, 4, -12, 4, -12,
ax_anim 2, 0, 37, 13, -20, 13, -20,
ax_anim 2, 2, 38, 22, -22, 22, -22,
ax_anim 2, 0, 39, 22, -21, 22, -21,
ax_anim 2, 1, 32, 22, -22, 22, -22,
ax_anim 2, 0, 33, 22, -21, 22, -21,
ax_anim 2, 0, 34, 22, -22, 22, -22,
ax_anim 2, 0, 35, 22, -21, 22, -21,
ax_anim 2, 0, 36, 16, -8, 16, -8,
ax_anim 2, 0, 37, 7, -2, 7, -2,
ax_anim_terminator
sVoltorbAnims_3_5:
ax_anim 2, 0, 37, -1, 0, -1, 0,
ax_anim 2, 0, 38, -2, 0, -2, 0,
ax_anim 6, 0, 39, -3, 0, -3, 0,
ax_anim 1, 0, 38, -2, 0, -2, 0,
ax_anim 1, 0, 37, 0, -3, 0, -3,
ax_anim 2, 0, 36, 4, -8, 4, -8,
ax_anim 2, 2, 35, 4, -16, 4, -16,
ax_anim 2, 0, 34, 0, -21, 0, -21,
ax_anim 2, 1, 33, 1, -21, 1, -21,
ax_anim 2, 0, 32, 0, -21, 0, -21,
ax_anim 2, 0, 39, 1, -21, 1, -21,
ax_anim 2, 0, 38, 0, -21, 0, -21,
ax_anim 2, 0, 37, -4, -18, -4, -18,
ax_anim 2, 0, 36, -4, -8, -4, -8,
ax_anim_terminator
sVoltorbAnims_3_6:
ax_anim 2, 0, 36, 0, 1, 0, 1,
ax_anim 2, 0, 37, 0, 2, 0, 2,
ax_anim 6, 0, 38, 0, 3, 0, 3,
ax_anim 1, 0, 37, -2, -5, -2, -5,
ax_anim 1, 0, 36, -4, -12, -4, -12,
ax_anim 2, 0, 35, -13, -20, -13, -20,
ax_anim 2, 2, 34, -22, -22, -22, -22,
ax_anim 2, 0, 33, -22, -21, -22, -21,
ax_anim 2, 1, 32, -22, -22, -22, -22,
ax_anim 2, 0, 39, -22, -21, -22, -21,
ax_anim 2, 0, 38, -22, -22, -22, -22,
ax_anim 2, 0, 37, -22, -21, -22, -21,
ax_anim 2, 0, 36, -16, -8, -16, -8,
ax_anim 2, 0, 35, -7, -2, -7, -2,
ax_anim_terminator
sVoltorbAnims_3_7:
ax_anim 2, 0, 35, 0, 1, 0, 1,
ax_anim 2, 0, 36, 0, 2, 0, 2,
ax_anim 6, 0, 37, 0, 3, 0, 3,
ax_anim 1, 0, 36, 0, 0, 0, 0,
ax_anim 1, 0, 35, -5, -4, -5, -4,
ax_anim 2, 0, 34, -13, -4, -13, -4,
ax_anim 2, 2, 33, -22, 0, -22, 0,
ax_anim 2, 0, 32, -22, 1, -22, 1,
ax_anim 2, 1, 39, -22, 0, -22, 0,
ax_anim 2, 0, 38, -22, 1, -22, 1,
ax_anim 2, 0, 37, -22, 0, -22, 0,
ax_anim 2, 0, 36, -22, 1, -22, 1,
ax_anim 2, 0, 35, -13, 4, -13, 4,
ax_anim 2, 0, 34, -1, 4, -1, 4,
ax_anim_terminator
sVoltorbAnims_3_8:
ax_anim 2, 0, 34, 1, 1, 1, 1,
ax_anim 2, 0, 35, 2, 2, 2, 2,
ax_anim 6, 0, 36, 3, 3, 3, 3,
ax_anim 1, 0, 35, 2, 2, 2, 2,
ax_anim 1, 0, 34, -5, 3, -5, 3,
ax_anim 2, 0, 33, -13, 6, -12, 6,
ax_anim 2, 2, 32, -22, 12, -22, 12,
ax_anim 2, 0, 39, -21, 21, -21, 21,
ax_anim 2, 1, 38, -22, 20, -22, 20,
ax_anim 2, 0, 37, -21, 21, -21, 21,
ax_anim 2, 0, 36, -22, 20, -22, 20,
ax_anim 2, 0, 35, -21, 21, -21, 21,
ax_anim 2, 0, 34, -11, 20, -11, 18,
ax_anim 2, 0, 33, -1, 8, -1, 8,
ax_anim_terminator
.align 2
sVoltorbAnims_4_1:
ax_anim 2, 0, 40, 1, 0, 1, 0,
ax_anim 2, 0, 40, 0, 0, 0, 0,
ax_anim 2, 0, 40, 1, 0, 1, 0,
ax_anim 2, 0, 40, 0, 0, 0, 0,
ax_anim 2, 0, 40, 1, 0, 1, 0,
ax_anim 2, 2, 40, 0, 0, 0, 0,
ax_anim 2, 0, 40, 1, 0, 1, 0,
ax_anim 2, 0, 40, 0, 0, 0, 0,
ax_anim 2, 0, 40, 1, 0, 1, 0,
ax_anim 2, 1, 40, 0, 0, 0, 0,
ax_anim_terminator
sVoltorbAnims_4_2:
ax_anim 2, 0, 47, 1, -1, 1, 0,
ax_anim 2, 0, 47, 0, 0, 0, 0,
ax_anim 2, 0, 47, 1, -1, 1, 0,
ax_anim 2, 0, 47, 0, 0, 0, 0,
ax_anim 2, 0, 47, 1, -1, 1, 0,
ax_anim 2, 2, 47, 0, 0, 0, 0,
ax_anim 2, 0, 47, 1, -1, 1, 0,
ax_anim 2, 0, 47, 0, 0, 0, 0,
ax_anim 2, 0, 47, 1, -1, 1, 0,
ax_anim 2, 1, 47, 0, 0, 0, 0,
ax_anim_terminator
sVoltorbAnims_4_3:
ax_anim 2, 0, 46, 0, -1, 0, -1,
ax_anim 2, 0, 46, 0, 0, 0, 0,
ax_anim 2, 0, 46, 0, -1, 0, -1,
ax_anim 2, 0, 46, 0, 0, 0, 0,
ax_anim 2, 0, 46, 0, -1, 0, -1,
ax_anim 2, 2, 46, 0, 0, 0, 0,
ax_anim 2, 0, 46, 0, -1, 0, -1,
ax_anim 2, 0, 46, 0, 0, 0, 0,
ax_anim 2, 0, 46, 0, -1, 0, -1,
ax_anim 2, 1, 46, 0, 0, 0, 0,
ax_anim_terminator
sVoltorbAnims_4_4:
ax_anim 2, 0, 45, -1, -1, -1, -1,
ax_anim 2, 0, 45, 0, 0, 0, 0,
ax_anim 2, 0, 45, -1, -1, -1, -1,
ax_anim 2, 0, 45, 0, 0, 0, 0,
ax_anim 2, 0, 45, -1, -1, -1, -1,
ax_anim 2, 2, 45, 0, 0, 0, 0,
ax_anim 2, 0, 45, -1, -1, -1, -1,
ax_anim 2, 0, 45, 0, 0, 0, 0,
ax_anim 2, 0, 45, -1, -1, -1, -1,
ax_anim 2, 1, 45, 0, 0, 0, 0,
ax_anim_terminator
sVoltorbAnims_4_5:
ax_anim 2, 0, 44, 1, 0, 1, 0,
ax_anim 2, 0, 44, 0, 0, 0, 0,
ax_anim 2, 0, 44, 1, 0, 1, 0,
ax_anim 2, 0, 44, 0, 0, 0, 0,
ax_anim 2, 0, 44, 1, 0, 1, 0,
ax_anim 2, 2, 44, 0, 0, 0, 0,
ax_anim 2, 0, 44, 1, 0, 1, 0,
ax_anim 2, 0, 44, 0, 0, 0, 0,
ax_anim 2, 0, 44, 1, 0, 1, 0,
ax_anim 2, 1, 44, 0, 0, 0, 0,
ax_anim_terminator
sVoltorbAnims_4_6:
ax_anim 2, 0, 43, 1, -1, 1, -1,
ax_anim 2, 0, 43, 0, 0, 0, 0,
ax_anim 2, 0, 43, 1, -1, 1, -1,
ax_anim 2, 0, 43, 0, 0, 0, 0,
ax_anim 2, 0, 43, 1, -1, 1, -1,
ax_anim 2, 2, 43, 0, 0, 0, 0,
ax_anim 2, 0, 43, 1, -1, 1, -1,
ax_anim 2, 0, 43, 0, 0, 0, 0,
ax_anim 2, 0, 43, 1, -1, 1, -1,
ax_anim 2, 1, 43, 0, 0, 0, 0,
ax_anim_terminator
sVoltorbAnims_4_7:
ax_anim 2, 0, 42, 0, -1, 0, -1,
ax_anim 2, 0, 42, 0, 0, 0, 0,
ax_anim 2, 0, 42, 0, -1, 0, -1,
ax_anim 2, 0, 42, 0, 0, 0, 0,
ax_anim 2, 0, 42, 0, -1, 0, -1,
ax_anim 2, 2, 42, 0, 0, 0, 0,
ax_anim 2, 0, 42, 0, -1, 0, -1,
ax_anim 2, 0, 42, 0, 0, 0, 0,
ax_anim 2, 0, 42, 0, -1, 0, -1,
ax_anim 2, 1, 42, 0, 0, 0, 0,
ax_anim_terminator
sVoltorbAnims_4_8:
ax_anim 2, 0, 41, -1, -1, -1, -1,
ax_anim 2, 0, 41, 0, 0, 0, 0,
ax_anim 2, 0, 41, -1, -1, -1, -1,
ax_anim 2, 0, 41, 0, 0, 0, 0,
ax_anim 2, 0, 41, -1, -1, -1, -1,
ax_anim 2, 2, 41, 0, 0, 0, 0,
ax_anim 2, 0, 41, -1, -1, -1, -1,
ax_anim 2, 0, 41, 0, 0, 0, 0,
ax_anim 2, 0, 41, -1, -1, -1, -1,
ax_anim 2, 1, 41, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sVoltorbAnims_5_1:
ax_anim 1, 0, 55, 5, 0, 5, 0,
ax_anim 1, 0, 54, 4, -2, 4, -2,
ax_anim 1, 0, 53, 2, -4, 2, -3,
ax_anim 1, 0, 52, 0, -4, 0, -3,
ax_anim 1, 0, 51, -2, -5, -2, -3,
ax_anim 1, 0, 50, -4, -4, -4, -2,
ax_anim 1, 0, 49, -5, -3, -5, 0,
ax_anim 1, 0, 48, -4, -1, -4, 2,
ax_anim 1, 0, 55, -2, -1, -2, 3,
ax_anim 1, 0, 54, 0, -1, 0, 3,
ax_anim 1, 0, 53, 2, -2, 2, 3,
ax_anim 1, 0, 52, 4, -3, 4, 2,
ax_anim 1, 0, 51, 5, -6, 5, 0,
ax_anim 1, 0, 50, 4, -8, 4, -2,
ax_anim 1, 0, 49, 2, -10, 2, -3,
ax_anim 6, 2, 48, 0, -10, 0, -3,
ax_anim 1, 0, 48, 0, -8, 0, -3,
ax_anim 1, 0, 48, 0, -4, 0, -2,
ax_anim 3, 1, 48, 0, 0, 0, 0,
ax_anim 1, 0, 48, 0, -2, 0, 0,
ax_anim 1, 0, 48, 0, -3, 0, 0,
ax_anim 1, 0, 48, 0, -2, 0, 0,
ax_anim 1, 0, 48, 0, 0, 0, 0,
ax_anim_terminator
sVoltorbAnims_5_2:
ax_anim 1, 0, 54, 5, 0, 5, 0,
ax_anim 1, 0, 53, 4, -2, 4, -2,
ax_anim 1, 0, 52, 2, -4, 2, -3,
ax_anim 1, 0, 51, 0, -4, 0, -3,
ax_anim 1, 0, 50, -2, -5, -2, -3,
ax_anim 1, 0, 49, -4, -4, -4, -2,
ax_anim 1, 0, 48, -5, -3, -5, 0,
ax_anim 1, 0, 55, -4, -1, -4, 2,
ax_anim 1, 0, 54, -2, -1, -2, 3,
ax_anim 1, 0, 53, 0, -1, 0, 3,
ax_anim 1, 0, 52, 2, -2, 2, 3,
ax_anim 1, 0, 51, 4, -3, 4, 2,
ax_anim 1, 0, 50, 5, -6, 5, 0,
ax_anim 1, 0, 49, 4, -8, 4, -2,
ax_anim 1, 0, 48, 2, -10, 2, -3,
ax_anim 6, 2, 55, 0, -10, 0, -3,
ax_anim 1, 0, 55, 0, -8, 0, -3,
ax_anim 1, 0, 55, 0, -4, 0, -2,
ax_anim 3, 1, 55, 0, 0, 0, 0,
ax_anim 1, 0, 55, 0, -2, 0, 0,
ax_anim 1, 0, 55, 0, -3, 0, 0,
ax_anim 1, 0, 55, 0, -2, 0, 0,
ax_anim 1, 0, 55, 0, 0, 0, 0,
ax_anim_terminator
sVoltorbAnims_5_3:
ax_anim 1, 0, 53, 5, 0, 5, 0,
ax_anim 1, 0, 52, 4, -2, 4, -2,
ax_anim 1, 0, 51, 2, -4, 2, -3,
ax_anim 1, 0, 50, 0, -4, 0, -3,
ax_anim 1, 0, 49, -2, -5, -2, -3,
ax_anim 1, 0, 48, -4, -4, -4, -2,
ax_anim 1, 0, 55, -5, -3, -5, 0,
ax_anim 1, 0, 54, -4, -1, -4, 2,
ax_anim 1, 0, 53, -2, -1, -2, 3,
ax_anim 1, 0, 52, 0, -1, 0, 3,
ax_anim 1, 0, 51, 2, -2, 2, 3,
ax_anim 1, 0, 50, 4, -3, 4, 2,
ax_anim 1, 0, 49, 5, -6, 5, 0,
ax_anim 1, 0, 48, 4, -8, 4, -2,
ax_anim 1, 0, 55, 2, -10, 2, -3,
ax_anim 6, 2, 54, 0, -10, 0, -3,
ax_anim 1, 0, 54, 0, -8, 0, -3,
ax_anim 1, 0, 54, 0, -4, 0, -2,
ax_anim 3, 1, 54, 0, 0, 0, 0,
ax_anim 1, 0, 54, 0, -2, 0, 0,
ax_anim 1, 0, 54, 0, -3, 0, 0,
ax_anim 1, 0, 54, 0, -2, 0, 0,
ax_anim 1, 0, 54, 0, 0, 0, 0,
ax_anim_terminator
sVoltorbAnims_5_4:
ax_anim 1, 0, 52, 5, 0, 5, 0,
ax_anim 1, 0, 51, 4, -2, 4, -2,
ax_anim 1, 0, 50, 2, -4, 2, -3,
ax_anim 1, 0, 49, 0, -4, 0, -3,
ax_anim 1, 0, 48, -2, -5, -2, -3,
ax_anim 1, 0, 55, -4, -4, -4, -2,
ax_anim 1, 0, 54, -5, -3, -5, 0,
ax_anim 1, 0, 53, -4, -1, -4, 2,
ax_anim 1, 0, 52, -2, -1, -2, 3,
ax_anim 1, 0, 51, 0, -1, 0, 3,
ax_anim 1, 0, 50, 2, -2, 2, 3,
ax_anim 1, 0, 49, 4, -3, 4, 2,
ax_anim 1, 0, 48, 5, -6, 5, 0,
ax_anim 1, 0, 55, 4, -8, 4, -2,
ax_anim 1, 0, 54, 2, -10, 2, -3,
ax_anim 6, 2, 53, 0, -10, 0, -3,
ax_anim 1, 0, 53, 0, -8, 0, -3,
ax_anim 1, 0, 53, 0, -4, 0, -2,
ax_anim 3, 1, 53, 0, 0, 0, 0,
ax_anim 1, 0, 53, 0, -2, 0, 0,
ax_anim 1, 0, 53, 0, -3, 0, 0,
ax_anim 1, 0, 53, 0, -2, 0, 0,
ax_anim 1, 0, 53, 0, 0, 0, 0,
ax_anim_terminator
sVoltorbAnims_5_5:
ax_anim 1, 0, 51, 5, 0, 5, 0,
ax_anim 1, 0, 50, 4, -2, 4, -2,
ax_anim 1, 0, 49, 2, -4, 2, -3,
ax_anim 1, 0, 48, 0, -4, 0, -3,
ax_anim 1, 0, 55, -2, -5, -2, -3,
ax_anim 1, 0, 54, -4, -4, -4, -2,
ax_anim 1, 0, 53, -5, -3, -5, 0,
ax_anim 1, 0, 52, -4, -1, -4, 2,
ax_anim 1, 0, 51, -2, -1, -2, 3,
ax_anim 1, 0, 50, 0, -1, 0, 3,
ax_anim 1, 0, 49, 2, -2, 2, 3,
ax_anim 1, 0, 48, 4, -3, 4, 2,
ax_anim 1, 0, 55, 5, -6, 5, 0,
ax_anim 1, 0, 54, 4, -8, 4, -2,
ax_anim 1, 0, 53, 2, -10, 2, -3,
ax_anim 6, 2, 52, 0, -10, 0, -3,
ax_anim 1, 0, 52, 0, -8, 0, -3,
ax_anim 1, 0, 52, 0, -4, 0, -2,
ax_anim 3, 1, 52, 0, 0, 0, 0,
ax_anim 1, 0, 52, 0, -2, 0, 0,
ax_anim 1, 0, 52, 0, -3, 0, 0,
ax_anim 1, 0, 52, 0, -2, 0, 0,
ax_anim 1, 0, 52, 0, 0, 0, 0,
ax_anim_terminator
sVoltorbAnims_5_6:
ax_anim 1, 0, 50, 5, 0, 5, 0,
ax_anim 1, 0, 49, 4, -2, 4, -2,
ax_anim 1, 0, 48, 2, -4, 2, -3,
ax_anim 1, 0, 55, 0, -4, 0, -3,
ax_anim 1, 0, 54, -2, -5, -2, -3,
ax_anim 1, 0, 53, -4, -4, -4, -2,
ax_anim 1, 0, 52, -5, -3, -5, 0,
ax_anim 1, 0, 51, -4, -1, -4, 2,
ax_anim 1, 0, 50, -2, -1, -2, 3,
ax_anim 1, 0, 49, 0, -1, 0, 3,
ax_anim 1, 0, 48, 2, -2, 2, 3,
ax_anim 1, 0, 55, 4, -3, 4, 2,
ax_anim 1, 0, 54, 5, -6, 5, 0,
ax_anim 1, 0, 53, 4, -8, 4, -2,
ax_anim 1, 0, 52, 2, -10, 2, -3,
ax_anim 6, 2, 51, 0, -10, 0, -3,
ax_anim 1, 0, 51, 0, -8, 0, -3,
ax_anim 1, 0, 51, 0, -4, 0, -2,
ax_anim 3, 1, 51, 0, 0, 0, 0,
ax_anim 1, 0, 51, 0, -2, 0, 0,
ax_anim 1, 0, 51, 0, -3, 0, 0,
ax_anim 1, 0, 51, 0, -2, 0, 0,
ax_anim 1, 0, 51, 0, 0, 0, 0,
ax_anim_terminator
sVoltorbAnims_5_7:
ax_anim 1, 0, 49, 5, 0, 5, 0,
ax_anim 1, 0, 48, 4, -2, 4, -2,
ax_anim 1, 0, 55, 2, -4, 2, -3,
ax_anim 1, 0, 54, 0, -4, 0, -3,
ax_anim 1, 0, 53, -2, -5, -2, -3,
ax_anim 1, 0, 52, -4, -4, -4, -2,
ax_anim 1, 0, 51, -5, -3, -5, 0,
ax_anim 1, 0, 50, -4, -1, -4, 2,
ax_anim 1, 0, 49, -2, -1, -2, 3,
ax_anim 1, 0, 48, 0, -1, 0, 3,
ax_anim 1, 0, 55, 2, -2, 2, 3,
ax_anim 1, 0, 54, 4, -3, 4, 2,
ax_anim 1, 0, 53, 5, -6, 5, 0,
ax_anim 1, 0, 52, 4, -8, 4, -2,
ax_anim 1, 0, 51, 2, -10, 2, -3,
ax_anim 6, 2, 50, 0, -10, 0, -3,
ax_anim 1, 0, 50, 0, -8, 0, -3,
ax_anim 1, 0, 50, 0, -4, 0, -2,
ax_anim 3, 1, 50, 0, 0, 0, 0,
ax_anim 1, 0, 50, 0, -2, 0, 0,
ax_anim 1, 0, 50, 0, -3, 0, 0,
ax_anim 1, 0, 50, 0, -2, 0, 0,
ax_anim 1, 0, 50, 0, 0, 0, 0,
ax_anim_terminator
sVoltorbAnims_5_8:
ax_anim 1, 0, 48, 5, 0, 5, 0,
ax_anim 1, 0, 55, 4, -2, 4, -2,
ax_anim 1, 0, 54, 2, -4, 2, -3,
ax_anim 1, 0, 53, 0, -4, 0, -3,
ax_anim 1, 0, 52, -2, -5, -2, -3,
ax_anim 1, 0, 51, -4, -4, -4, -2,
ax_anim 1, 0, 50, -5, -3, -5, 0,
ax_anim 1, 0, 49, -4, -1, -4, 2,
ax_anim 1, 0, 48, -2, -1, -2, 3,
ax_anim 1, 0, 55, 0, -1, 0, 3,
ax_anim 1, 0, 54, 2, -2, 2, 3,
ax_anim 1, 0, 53, 4, -3, 4, 2,
ax_anim 1, 0, 52, 5, -6, 5, 0,
ax_anim 1, 0, 51, 4, -8, 4, -2,
ax_anim 1, 0, 50, 2, -10, 2, -3,
ax_anim 6, 2, 49, 0, -10, 0, -3,
ax_anim 1, 0, 49, 0, -8, 0, -3,
ax_anim 1, 0, 49, 0, -4, 0, -2,
ax_anim 3, 1, 49, 0, 0, 0, 0,
ax_anim 1, 0, 49, 0, -2, 0, 0,
ax_anim 1, 0, 49, 0, -3, 0, 0,
ax_anim 1, 0, 49, 0, -2, 0, 0,
ax_anim 1, 0, 49, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sVoltorbAnims_6_1:
ax_anim 30, 0, 56, 0, 0, 0, 0,
ax_anim 35, 0, 57, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sVoltorbAnims_7_1:
ax_anim 2, 0, 58, 0, -2, 0, -2,
ax_anim 8, 0, 58, 0, -3, 0, -3,
ax_anim_terminator
sVoltorbAnims_7_2:
ax_anim 2, 0, 59, -2, -2, -2, -2,
ax_anim 8, 0, 59, -3, -3, -3, -3,
ax_anim_terminator
sVoltorbAnims_7_3:
ax_anim 2, 0, 60, -2, 0, -2, 0,
ax_anim 8, 0, 60, -3, 0, -3, 0,
ax_anim_terminator
sVoltorbAnims_7_4:
ax_anim 2, 0, 61, -2, 2, -2, 2,
ax_anim 8, 0, 61, -3, 3, -3, 3,
ax_anim_terminator
sVoltorbAnims_7_5:
ax_anim 2, 0, 62, 0, 2, 0, 2,
ax_anim 8, 0, 62, 0, 3, 0, 3,
ax_anim_terminator
sVoltorbAnims_7_6:
ax_anim 2, 0, 63, 2, 2, 2, 2,
ax_anim 8, 0, 63, 3, 3, 3, 3,
ax_anim_terminator
sVoltorbAnims_7_7:
ax_anim 2, 0, 64, 2, 0, 2, 0,
ax_anim 8, 0, 64, 3, 0, 3, 0,
ax_anim_terminator
sVoltorbAnims_7_8:
ax_anim 2, 0, 65, 2, -2, 2, -2,
ax_anim 8, 0, 65, 3, -3, 3, -3,
ax_anim_terminator
.align 2
sVoltorbAnims_8_1:
ax_anim 22, 0, 66, 0, 0, 0, 0,
ax_anim 6, 0, 66, 0, -3, 0, 0,
ax_anim 2, 0, 66, 0, -1, 0, 0,
ax_anim 6, 0, 66, 0, 0, 0, 0,
ax_anim 6, 0, 66, 0, -1, 0, 0,
ax_anim_terminator
sVoltorbAnims_8_2:
ax_anim 22, 0, 73, 0, 0, 0, 0,
ax_anim 6, 0, 73, 0, -3, 0, 0,
ax_anim 2, 0, 73, 0, -1, 0, 0,
ax_anim 6, 0, 73, 0, 0, 0, 0,
ax_anim 6, 0, 73, 0, -1, 0, 0,
ax_anim_terminator
sVoltorbAnims_8_3:
ax_anim 22, 0, 72, 0, 0, 0, 0,
ax_anim 6, 0, 72, 0, -3, 0, 0,
ax_anim 2, 0, 72, 0, -1, 0, 0,
ax_anim 6, 0, 72, 0, 0, 0, 0,
ax_anim 6, 0, 72, 0, -1, 0, 0,
ax_anim_terminator
sVoltorbAnims_8_4:
ax_anim 22, 0, 71, 0, 0, 0, 0,
ax_anim 6, 0, 71, 0, -3, 0, 0,
ax_anim 2, 0, 71, 0, -1, 0, 0,
ax_anim 6, 0, 71, 0, 0, 0, 0,
ax_anim 6, 0, 71, 0, -1, 0, 0,
ax_anim_terminator
sVoltorbAnims_8_5:
ax_anim 22, 0, 70, 0, 0, 0, 0,
ax_anim 6, 0, 70, 0, -3, 0, 0,
ax_anim 2, 0, 70, 0, -1, 0, 0,
ax_anim 6, 0, 70, 0, 0, 0, 0,
ax_anim 6, 0, 70, 0, -1, 0, 0,
ax_anim_terminator
sVoltorbAnims_8_6:
ax_anim 22, 0, 69, 0, 0, 0, 0,
ax_anim 6, 0, 69, 0, -3, 0, 0,
ax_anim 2, 0, 69, 0, -1, 0, 0,
ax_anim 6, 0, 69, 0, 0, 0, 0,
ax_anim 6, 0, 69, 0, -1, 0, 0,
ax_anim_terminator
sVoltorbAnims_8_7:
ax_anim 22, 0, 68, 0, 0, 0, 0,
ax_anim 6, 0, 68, 0, -3, 0, 0,
ax_anim 2, 0, 68, 0, -1, 0, 0,
ax_anim 6, 0, 68, 0, 0, 0, 0,
ax_anim 6, 0, 68, 0, -1, 0, 0,
ax_anim_terminator
sVoltorbAnims_8_8:
ax_anim 22, 0, 67, 0, 0, 0, 0,
ax_anim 6, 0, 67, 0, -3, 0, 0,
ax_anim 2, 0, 67, 0, -1, 0, 0,
ax_anim 6, 0, 67, 0, 0, 0, 0,
ax_anim 6, 0, 67, 0, -1, 0, 0,
ax_anim_terminator
.align 2
sVoltorbAnims_9_1:
ax_anim 2, 0, 74, 0, 0, 0, 0,
ax_anim 1, 0, 75, 6, 3, 6, 3,
ax_anim 2, 0, 76, 8, 9, 8, 9,
ax_anim 2, 0, 77, 7, 17, 7, 17,
ax_anim 3, 0, 78, 0, 21, 0, 21,
ax_anim 2, 3, 79, -7, 17, -7, 17,
ax_anim 2, 0, 80, -8, 9, -8, 9,
ax_anim 1, 0, 81, -6, 3, -6, 3,
ax_anim 1, 0, 74, 0, 0, 0, 0,
ax_anim_terminator
sVoltorbAnims_9_2:
ax_anim 2, 0, 81, 0, 0, 0, 0,
ax_anim 1, 0, 74, 8, 0, 8, 0,
ax_anim 2, 0, 75, 17, 3, 17, 3,
ax_anim 2, 0, 76, 21, 10, 21, 10,
ax_anim 3, 0, 77, 22, 21, 22, 21,
ax_anim 2, 3, 78, 13, 21, 13, 21,
ax_anim 2, 0, 79, 3, 15, 3, 15,
ax_anim 1, 0, 80, 0, 7, 0, 7,
ax_anim 1, 0, 81, 0, 0, 0, 0,
ax_anim_terminator
sVoltorbAnims_9_3:
ax_anim 2, 0, 80, 0, 0, 0, 0,
ax_anim 1, 0, 81, 3, -5, 3, -5,
ax_anim 2, 0, 74, 11, -6, 11, -6,
ax_anim 2, 0, 75, 18, -5, 18, -5,
ax_anim 3, 0, 76, 22, -2, 22, -2,
ax_anim 2, 3, 77, 18, 4, 18, 4,
ax_anim 2, 0, 78, 12, 5, 12, 5,
ax_anim 1, 0, 79, 4, 5, 4, 5,
ax_anim 1, 0, 80, 0, 0, 0, 0,
ax_anim_terminator
sVoltorbAnims_9_4:
ax_anim 2, 0, 79, 0, 0, 0, 0,
ax_anim 1, 0, 80, -1, -8, -1, -8,
ax_anim 2, 0, 81, 4, -16, 4, -16,
ax_anim 2, 0, 74, 13, -21, 13, -21,
ax_anim 3, 0, 75, 22, -22, 22, -22,
ax_anim 2, 3, 76, 22, -14, 22, -14,
ax_anim 2, 0, 77, 17, -6, 17, -6,
ax_anim 1, 0, 78, 7, -1, 7, -1,
ax_anim 1, 0, 79, 0, 0, 0, 0,
ax_anim_terminator
sVoltorbAnims_9_5:
ax_anim 2, 0, 78, 0, 0, 0, 0,
ax_anim 1, 0, 79, -8, -4, -8, -4,
ax_anim 2, 0, 80, -9, -12, -9, -12,
ax_anim 2, 0, 81, -7, -18, -7, -18,
ax_anim 3, 0, 74, 0, -22, 0, -22,
ax_anim 2, 3, 75, 7, -18, 7, -18,
ax_anim 2, 0, 76, 9, -10, 9, -10,
ax_anim 1, 0, 77, 8, -4, 8, -4,
ax_anim 1, 0, 78, 0, 0, 0, 0,
ax_anim_terminator
sVoltorbAnims_9_6:
ax_anim 2, 0, 77, 0, 0, 0, 0,
ax_anim 1, 0, 76, 1, -8, 1, -8,
ax_anim 2, 0, 75, -4, -16, -4, -16,
ax_anim 2, 0, 74, -13, -21, -13, -21,
ax_anim 3, 0, 81, -22, -22, -22, -22,
ax_anim 2, 3, 80, -22, -14, -22, -14,
ax_anim 2, 0, 79, -17, -6, -17, -6,
ax_anim 1, 0, 78, -7, -1, -7, -1,
ax_anim 1, 0, 77, 0, 0, 0, 0,
ax_anim_terminator
sVoltorbAnims_9_7:
ax_anim 2, 0, 76, 0, 0, 0, 0,
ax_anim 1, 0, 75, -3, -5, -3, -5,
ax_anim 2, 0, 74, -11, -6, -11, -6,
ax_anim 2, 0, 81, -18, -5, -18, -5,
ax_anim 3, 0, 80, -22, -2, -22, -2,
ax_anim 2, 3, 79, -18, 4, -18, 4,
ax_anim 2, 0, 78, -12, 5, -12, 5,
ax_anim 1, 0, 77, -4, 5, -4, 5,
ax_anim 1, 0, 76, 0, 0, 0, 0,
ax_anim_terminator
sVoltorbAnims_9_8:
ax_anim 2, 0, 75, 0, 0, 0, 0,
ax_anim 1, 0, 74, -8, 0, -8, 0,
ax_anim 2, 0, 81, -17, 3, -17, 3,
ax_anim 2, 0, 80, -21, 10, -21, 10,
ax_anim 3, 0, 79, -22, 21, -22, 21,
ax_anim 2, 3, 78, -13, 21, -13, 21,
ax_anim 2, 0, 77, -3, 15, -3, 15,
ax_anim 1, 0, 76, 0, 7, 0, 7,
ax_anim 1, 0, 75, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sVoltorbAnims_10_1:
ax_anim 2, 0, 82, 0, 0, 0, 0,
ax_anim 2, 0, 82, 6, 0, 6, 0,
ax_anim 2, 0, 82, -6, 0, -6, 0,
ax_anim 2, 0, 82, 10, 0, 10, 0,
ax_anim 2, 0, 82, -10, 0, -10, 0,
ax_anim 2, 0, 82, 12, 0, 12, 0,
ax_anim 3, 0, 82, -12, 0, -12, 0,
ax_anim 3, 0, 82, 13, 0, 13, 0,
ax_anim 3, 0, 82, -13, 0, -13, 0,
ax_anim 2, 0, 82, 12, 0, 12, 0,
ax_anim 3, 0, 82, -12, 0, -12, 0,
ax_anim 2, 0, 82, 10, 0, 10, 0,
ax_anim 2, 0, 82, -10, 0, -10, 0,
ax_anim 2, 0, 82, 6, 0, 6, 0,
ax_anim 2, 0, 82, -6, 0, -6, 0,
ax_anim 2, 0, 82, 0, 0, 0, 0,
ax_anim_terminator
sVoltorbAnims_10_2:
ax_anim 2, 0, 83, 0, 0, 0, 0,
ax_anim 2, 0, 83, 6, -6, 6, -6,
ax_anim 2, 0, 83, -6, 6, -6, 6,
ax_anim 2, 0, 83, 10, -10, 10, -10,
ax_anim 2, 0, 83, -10, 10, -10, 10,
ax_anim 2, 0, 83, 12, -12, 12, -12,
ax_anim 3, 0, 83, -12, 12, -12, 12,
ax_anim 3, 0, 83, 13, -13, 13, -13,
ax_anim 3, 0, 83, -13, 13, -13, 13,
ax_anim 2, 0, 83, 12, -12, 12, -12,
ax_anim 3, 0, 83, -12, 12, -12, 12,
ax_anim 2, 0, 83, 10, -10, 10, -10,
ax_anim 2, 0, 83, -10, 10, -10, 10,
ax_anim 2, 0, 83, 6, -6, 6, -6,
ax_anim 2, 0, 83, -6, 6, -6, 6,
ax_anim 2, 0, 83, 0, 0, 0, 0,
ax_anim_terminator
sVoltorbAnims_10_3:
ax_anim 2, 0, 84, 0, 0, 0, 0,
ax_anim 2, 0, 84, 0, -6, 0, -6,
ax_anim 2, 0, 84, 0, 6, 0, 6,
ax_anim 2, 0, 84, 0, -10, 0, -10,
ax_anim 2, 0, 84, 0, 10, 0, 10,
ax_anim 2, 0, 84, 0, -12, 0, -12,
ax_anim 3, 0, 84, 0, 12, 0, 12,
ax_anim 3, 0, 84, 0, -13, 0, -13,
ax_anim 3, 0, 84, 0, 13, 0, 13,
ax_anim 2, 0, 84, 0, -12, 0, -12,
ax_anim 3, 0, 84, 0, 12, 0, 12,
ax_anim 2, 0, 84, 0, -10, 0, -10,
ax_anim 2, 0, 84, 0, 10, 0, 10,
ax_anim 2, 0, 84, 0, -6, 0, -6,
ax_anim 2, 0, 84, 0, 6, 0, 6,
ax_anim 2, 0, 84, 0, 0, 0, 0,
ax_anim_terminator
sVoltorbAnims_10_4:
ax_anim 2, 0, 85, 0, 0, 0, 0,
ax_anim 2, 0, 85, -6, -6, -6, -6,
ax_anim 2, 0, 85, 6, 6, 6, 6,
ax_anim 2, 0, 85, -10, -10, -10, -10,
ax_anim 2, 0, 85, 10, 10, 10, 10,
ax_anim 2, 0, 85, -12, -12, -12, -12,
ax_anim 3, 0, 85, 12, 12, 12, 12,
ax_anim 3, 0, 85, -13, -13, -13, -13,
ax_anim 3, 0, 85, 13, 13, 13, 13,
ax_anim 2, 0, 85, -12, -12, -12, -12,
ax_anim 3, 0, 85, 12, 12, 12, 12,
ax_anim 2, 0, 85, -10, -10, -10, -10,
ax_anim 2, 0, 85, 10, 10, 10, 10,
ax_anim 2, 0, 85, -6, -6, -6, -6,
ax_anim 2, 0, 85, 6, 6, 6, 6,
ax_anim 2, 0, 85, 0, 0, 0, 0,
ax_anim_terminator
sVoltorbAnims_10_5:
ax_anim 2, 0, 86, 0, 0, 0, 0,
ax_anim 2, 0, 86, 6, 0, 6, 0,
ax_anim 2, 0, 86, -6, 0, -6, 0,
ax_anim 2, 0, 86, 10, 0, 10, 0,
ax_anim 2, 0, 86, -10, 0, -10, 0,
ax_anim 2, 0, 86, 12, 0, 12, 0,
ax_anim 3, 0, 86, -12, 0, -12, 0,
ax_anim 3, 0, 86, 13, 0, 13, 0,
ax_anim 3, 0, 86, -13, 0, -13, 0,
ax_anim 2, 0, 86, 12, 0, 12, 0,
ax_anim 3, 0, 86, -12, 0, -12, 0,
ax_anim 2, 0, 86, 10, 0, 10, 0,
ax_anim 2, 0, 86, -10, 0, -10, 0,
ax_anim 2, 0, 86, 6, 0, 6, 0,
ax_anim 2, 0, 86, -6, 0, -6, 0,
ax_anim 2, 0, 86, 0, 0, 0, 0,
ax_anim_terminator
sVoltorbAnims_10_6:
ax_anim 2, 0, 87, 0, 0, 0, 0,
ax_anim 2, 0, 87, 6, -6, 6, -6,
ax_anim 2, 0, 87, -6, 6, -6, 6,
ax_anim 2, 0, 87, 10, -10, 10, -10,
ax_anim 2, 0, 87, -10, 10, -10, 10,
ax_anim 2, 0, 87, 12, -12, 12, -12,
ax_anim 3, 0, 87, -12, 12, -12, 12,
ax_anim 3, 0, 87, 13, -13, 13, -13,
ax_anim 3, 0, 87, -13, 13, -13, 13,
ax_anim 2, 0, 87, 12, -12, 12, -12,
ax_anim 3, 0, 87, -12, 12, -12, 12,
ax_anim 2, 0, 87, 10, -10, 10, -10,
ax_anim 2, 0, 87, -10, 10, -10, 10,
ax_anim 2, 0, 87, 6, -6, 6, -6,
ax_anim 2, 0, 87, -6, 6, -6, 6,
ax_anim 2, 0, 87, 0, 0, 0, 0,
ax_anim_terminator
sVoltorbAnims_10_7:
ax_anim 2, 0, 88, 0, 0, 0, 0,
ax_anim 2, 0, 88, 0, -6, 0, -6,
ax_anim 2, 0, 88, 0, 6, 0, 6,
ax_anim 2, 0, 88, 0, -10, 0, -10,
ax_anim 2, 0, 88, 0, 10, 0, 10,
ax_anim 2, 0, 88, 0, -12, 0, -12,
ax_anim 3, 0, 88, 0, 12, 0, 12,
ax_anim 3, 0, 88, 0, -13, 0, -13,
ax_anim 3, 0, 88, 0, 13, 0, 13,
ax_anim 2, 0, 88, 0, -12, 0, -12,
ax_anim 3, 0, 88, 0, 12, 0, 12,
ax_anim 2, 0, 88, 0, -10, 0, -10,
ax_anim 2, 0, 88, 0, 10, 0, 10,
ax_anim 2, 0, 88, 0, -6, 0, -6,
ax_anim 2, 0, 88, 0, 6, 0, 6,
ax_anim 2, 0, 88, 0, 0, 0, 0,
ax_anim_terminator
sVoltorbAnims_10_8:
ax_anim 2, 0, 89, 0, 0, 0, 0,
ax_anim 2, 0, 89, -6, -6, -6, -6,
ax_anim 2, 0, 89, 6, 6, 6, 6,
ax_anim 2, 0, 89, -10, -10, -10, -10,
ax_anim 2, 0, 89, 10, 10, 10, 10,
ax_anim 2, 0, 89, -12, -12, -12, -12,
ax_anim 3, 0, 89, 12, 12, 12, 12,
ax_anim 3, 0, 89, -13, -13, -13, -13,
ax_anim 3, 0, 89, 13, 13, 13, 13,
ax_anim 2, 0, 89, -12, -12, -12, -12,
ax_anim 3, 0, 89, 12, 12, 12, 12,
ax_anim 2, 0, 89, -10, -10, -10, -10,
ax_anim 2, 0, 89, 10, 10, 10, 10,
ax_anim 2, 0, 89, -6, -6, -6, -6,
ax_anim 2, 0, 89, 6, 6, 6, 6,
ax_anim 2, 0, 89, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sVoltorbAnims_11_1:
ax_anim 2, 0, 90, 0, 0, 0, 0,
ax_anim 1, 0, 91, 0, -10, 0, 0,
ax_anim 2, 0, 91, 0, -16, 0, 0,
ax_anim 3, 0, 91, 0, -20, 0, 0,
ax_anim 4, 0, 91, 0, -21, 0, 0,
ax_anim 4, 0, 90, 0, -23, 0, 0,
ax_anim 3, 0, 92, 0, -22, 0, 0,
ax_anim 2, 0, 92, 0, -18, 0, 0,
ax_anim 1, 0, 92, 0, -12, 0, 0,
ax_anim 2, 2, 90, 0, 0, 0, 0,
ax_anim_terminator
sVoltorbAnims_11_2:
ax_anim 2, 0, 93, 0, 0, 0, 0,
ax_anim 1, 0, 94, 0, -10, 0, 0,
ax_anim 2, 0, 94, 0, -16, 0, 0,
ax_anim 3, 0, 94, 0, -20, 0, 0,
ax_anim 4, 0, 94, 0, -21, 0, 0,
ax_anim 4, 0, 93, 0, -23, 0, 0,
ax_anim 3, 0, 95, 0, -22, 0, 0,
ax_anim 2, 0, 95, 0, -18, 0, 0,
ax_anim 1, 0, 95, 0, -12, 0, 0,
ax_anim 2, 2, 93, 0, 0, 0, 0,
ax_anim_terminator
sVoltorbAnims_11_3:
ax_anim 2, 0, 96, 0, 0, 0, 0,
ax_anim 1, 0, 97, 0, -10, 0, 0,
ax_anim 2, 0, 97, 0, -16, 0, 0,
ax_anim 3, 0, 97, 0, -20, 0, 0,
ax_anim 4, 0, 97, 0, -21, 0, 0,
ax_anim 4, 0, 96, 0, -23, 0, 0,
ax_anim 3, 0, 98, 0, -22, 0, 0,
ax_anim 2, 0, 98, 0, -18, 0, 0,
ax_anim 1, 0, 98, 0, -12, 0, 0,
ax_anim 2, 2, 96, 0, 0, 0, 0,
ax_anim_terminator
sVoltorbAnims_11_4:
ax_anim 2, 0, 99, 0, 0, 0, 0,
ax_anim 1, 0, 100, 0, -10, 0, 0,
ax_anim 2, 0, 100, 0, -16, 0, 0,
ax_anim 3, 0, 100, 0, -20, 0, 0,
ax_anim 4, 0, 100, 0, -21, 0, 0,
ax_anim 4, 0, 99, 0, -22, 0, 0,
ax_anim 3, 0, 101, 0, -21, 0, 0,
ax_anim 2, 0, 101, 0, -17, 0, 0,
ax_anim 1, 0, 101, 0, -11, 0, 0,
ax_anim 2, 2, 99, 0, 0, 0, 0,
ax_anim_terminator
sVoltorbAnims_11_5:
ax_anim 2, 0, 102, 0, 0, 0, 0,
ax_anim 1, 0, 103, 0, -10, 0, 0,
ax_anim 2, 0, 103, 0, -16, 0, 0,
ax_anim 3, 0, 103, 0, -20, 0, 0,
ax_anim 4, 0, 103, 0, -21, 0, 0,
ax_anim 4, 0, 102, 0, -23, 0, 0,
ax_anim 3, 0, 104, 0, -22, 0, 0,
ax_anim 2, 0, 104, 0, -18, 0, 0,
ax_anim 1, 0, 104, 0, -12, 0, 0,
ax_anim 2, 2, 102, 0, 0, 0, 0,
ax_anim_terminator
sVoltorbAnims_11_6:
ax_anim 2, 0, 105, 0, 0, 0, 0,
ax_anim 1, 0, 106, 0, -10, 0, 0,
ax_anim 2, 0, 106, 0, -16, 0, 0,
ax_anim 3, 0, 106, 0, -20, 0, 0,
ax_anim 4, 0, 106, 0, -21, 0, 0,
ax_anim 4, 0, 105, 0, -22, 0, 0,
ax_anim 3, 0, 107, 0, -21, 0, 0,
ax_anim 2, 0, 107, 0, -17, 0, 0,
ax_anim 1, 0, 107, 0, -11, 0, 0,
ax_anim 2, 2, 105, 0, 0, 0, 0,
ax_anim_terminator
sVoltorbAnims_11_7:
ax_anim 2, 0, 108, 0, 0, 0, 0,
ax_anim 1, 0, 109, 0, -10, 0, 0,
ax_anim 2, 0, 109, 0, -16, 0, 0,
ax_anim 3, 0, 109, 0, -20, 0, 0,
ax_anim 4, 0, 109, 0, -21, 0, 0,
ax_anim 4, 0, 108, 0, -23, 0, 0,
ax_anim 3, 0, 110, 0, -22, 0, 0,
ax_anim 2, 0, 110, 0, -18, 0, 0,
ax_anim 1, 0, 110, 0, -12, 0, 0,
ax_anim 2, 2, 108, 0, 0, 0, 0,
ax_anim_terminator
sVoltorbAnims_11_8:
ax_anim 2, 0, 111, 0, 0, 0, 0,
ax_anim 1, 0, 112, 0, -10, 0, 0,
ax_anim 2, 0, 112, 0, -16, 0, 0,
ax_anim 3, 0, 112, 0, -20, 0, 0,
ax_anim 4, 0, 112, 0, -21, 0, 0,
ax_anim 4, 0, 111, 0, -23, 0, 0,
ax_anim 3, 0, 113, 0, -22, 0, 0,
ax_anim 2, 0, 113, 0, -18, 0, 0,
ax_anim 1, 0, 113, 0, -12, 0, 0,
ax_anim 2, 2, 111, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sVoltorbAnims_12_1:
ax_anim 2, 0, 114, 1, 0, 1, 0,
ax_anim 2, 0, 114, 0, 0, 0, 0,
ax_anim 2, 0, 114, 1, 0, 1, 0,
ax_anim 2, 0, 114, 0, 0, 0, 0,
ax_anim 2, 0, 114, 1, 0, 1, 0,
ax_anim 2, 2, 114, 0, 0, 0, 0,
ax_anim 2, 0, 114, 1, 0, 1, 0,
ax_anim 2, 0, 114, 0, 0, 0, 0,
ax_anim 2, 0, 114, 1, 0, 1, 0,
ax_anim 2, 1, 114, 0, 0, 0, 0,
ax_anim_terminator
sVoltorbAnims_12_2:
ax_anim 2, 0, 121, 1, -1, 1, 0,
ax_anim 2, 0, 121, 0, 0, 0, 0,
ax_anim 2, 0, 121, 1, -1, 1, 0,
ax_anim 2, 0, 121, 0, 0, 0, 0,
ax_anim 2, 0, 121, 1, -1, 1, 0,
ax_anim 2, 2, 121, 0, 0, 0, 0,
ax_anim 2, 0, 121, 1, -1, 1, 0,
ax_anim 2, 0, 121, 0, 0, 0, 0,
ax_anim 2, 0, 121, 1, -1, 1, 0,
ax_anim 2, 1, 121, 0, 0, 0, 0,
ax_anim_terminator
sVoltorbAnims_12_3:
ax_anim 2, 0, 120, 0, -1, 0, -1,
ax_anim 2, 0, 120, 0, 0, 0, 0,
ax_anim 2, 0, 120, 0, -1, 0, -1,
ax_anim 2, 0, 120, 0, 0, 0, 0,
ax_anim 2, 0, 120, 0, -1, 0, -1,
ax_anim 2, 2, 120, 0, 0, 0, 0,
ax_anim 2, 0, 120, 0, -1, 0, -1,
ax_anim 2, 0, 120, 0, 0, 0, 0,
ax_anim 2, 0, 120, 0, -1, 0, -1,
ax_anim 2, 1, 120, 0, 0, 0, 0,
ax_anim_terminator
sVoltorbAnims_12_4:
ax_anim 2, 0, 119, -1, -1, -1, -1,
ax_anim 2, 0, 119, 0, 0, 0, 0,
ax_anim 2, 0, 119, -1, -1, -1, -1,
ax_anim 2, 0, 119, 0, 0, 0, 0,
ax_anim 2, 0, 119, -1, -1, -1, -1,
ax_anim 2, 2, 119, 0, 0, 0, 0,
ax_anim 2, 0, 119, -1, -1, -1, -1,
ax_anim 2, 0, 119, 0, 0, 0, 0,
ax_anim 2, 0, 119, -1, -1, -1, -1,
ax_anim 2, 1, 119, 0, 0, 0, 0,
ax_anim_terminator
sVoltorbAnims_12_5:
ax_anim 2, 0, 118, 1, 0, 1, 0,
ax_anim 2, 0, 118, 0, 0, 0, 0,
ax_anim 2, 0, 118, 1, 0, 1, 0,
ax_anim 2, 0, 118, 0, 0, 0, 0,
ax_anim 2, 0, 118, 1, 0, 1, 0,
ax_anim 2, 2, 118, 0, 0, 0, 0,
ax_anim 2, 0, 118, 1, 0, 1, 0,
ax_anim 2, 0, 118, 0, 0, 0, 0,
ax_anim 2, 0, 118, 1, 0, 1, 0,
ax_anim 2, 1, 118, 0, 0, 0, 0,
ax_anim_terminator
sVoltorbAnims_12_6:
ax_anim 2, 0, 117, 1, -1, 1, -1,
ax_anim 2, 0, 117, 0, 0, 0, 0,
ax_anim 2, 0, 117, 1, -1, 1, -1,
ax_anim 2, 0, 117, 0, 0, 0, 0,
ax_anim 2, 0, 117, 1, -1, 1, -1,
ax_anim 2, 2, 117, 0, 0, 0, 0,
ax_anim 2, 0, 117, 1, -1, 1, -1,
ax_anim 2, 0, 117, 0, 0, 0, 0,
ax_anim 2, 0, 117, 1, -1, 1, -1,
ax_anim 2, 1, 117, 0, 0, 0, 0,
ax_anim_terminator
sVoltorbAnims_12_7:
ax_anim 2, 0, 116, 0, -1, 0, -1,
ax_anim 2, 0, 116, 0, 0, 0, 0,
ax_anim 2, 0, 116, 0, -1, 0, -1,
ax_anim 2, 0, 116, 0, 0, 0, 0,
ax_anim 2, 0, 116, 0, -1, 0, -1,
ax_anim 2, 2, 116, 0, 0, 0, 0,
ax_anim 2, 0, 116, 0, -1, 0, -1,
ax_anim 2, 0, 116, 0, 0, 0, 0,
ax_anim 2, 0, 116, 0, -1, 0, -1,
ax_anim 2, 1, 116, 0, 0, 0, 0,
ax_anim_terminator
sVoltorbAnims_12_8:
ax_anim 2, 0, 115, -1, -1, -1, -1,
ax_anim 2, 0, 115, 0, 0, 0, 0,
ax_anim 2, 0, 115, -1, -1, -1, -1,
ax_anim 2, 0, 115, 0, 0, 0, 0,
ax_anim 2, 0, 115, -1, -1, -1, -1,
ax_anim 2, 2, 115, 0, 0, 0, 0,
ax_anim 2, 0, 115, -1, -1, -1, -1,
ax_anim 2, 0, 115, 0, 0, 0, 0,
ax_anim 2, 0, 115, -1, -1, -1, -1,
ax_anim 2, 1, 115, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sVoltorbAnims_13_1:
ax_anim 2, 0, 122, 0, 0, 0, 0,
ax_anim 2, 0, 123, 0, 0, 0, 0,
ax_anim 2, 0, 124, 0, 0, 0, 0,
ax_anim 2, 0, 125, 0, 0, 0, 0,
ax_anim 2, 0, 126, 0, 0, 0, 0,
ax_anim 2, 0, 127, 0, 0, 0, 0,
ax_anim 2, 0, 128, 0, 0, 0, 0,
ax_anim 2, 0, 129, 0, 0, 0, 0,
ax_anim 2, 2, 122, 0, 0, 0, 0,
ax_anim_terminator
sVoltorbAnims_13_2:
ax_anim 2, 0, 129, 0, 0, 0, 0,
ax_anim 2, 0, 122, 0, 0, 0, 0,
ax_anim 2, 0, 123, 0, 0, 0, 0,
ax_anim 2, 0, 124, 0, 0, 0, 0,
ax_anim 2, 0, 125, 0, 0, 0, 0,
ax_anim 2, 0, 126, 0, 0, 0, 0,
ax_anim 2, 0, 127, 0, 0, 0, 0,
ax_anim 2, 0, 128, 0, 0, 0, 0,
ax_anim 2, 2, 129, 0, 0, 0, 0,
ax_anim_terminator
sVoltorbAnims_13_3:
ax_anim 2, 0, 128, 0, 0, 0, 0,
ax_anim 2, 0, 129, 0, 0, 0, 0,
ax_anim 2, 0, 122, 0, 0, 0, 0,
ax_anim 2, 0, 123, 0, 0, 0, 0,
ax_anim 2, 0, 124, 0, 0, 0, 0,
ax_anim 2, 0, 125, 0, 0, 0, 0,
ax_anim 2, 0, 126, 0, 0, 0, 0,
ax_anim 2, 0, 127, 0, 0, 0, 0,
ax_anim 2, 2, 128, 0, 0, 0, 0,
ax_anim_terminator
sVoltorbAnims_13_4:
ax_anim 2, 0, 127, 0, 0, 0, 0,
ax_anim 2, 0, 128, 0, 0, 0, 0,
ax_anim 2, 0, 129, 0, 0, 0, 0,
ax_anim 2, 0, 122, 0, 0, 0, 0,
ax_anim 2, 0, 123, 0, 0, 0, 0,
ax_anim 2, 0, 124, 0, 0, 0, 0,
ax_anim 2, 0, 125, 0, 0, 0, 0,
ax_anim 2, 0, 126, 0, 0, 0, 0,
ax_anim 2, 2, 127, 0, 0, 0, 0,
ax_anim_terminator
sVoltorbAnims_13_5:
ax_anim 2, 0, 126, 0, 0, 0, 0,
ax_anim 2, 0, 127, 0, 0, 0, 0,
ax_anim 2, 0, 128, 0, 0, 0, 0,
ax_anim 2, 0, 129, 0, 0, 0, 0,
ax_anim 2, 0, 122, 0, 0, 0, 0,
ax_anim 2, 0, 123, 0, 0, 0, 0,
ax_anim 2, 0, 124, 0, 0, 0, 0,
ax_anim 2, 0, 125, 0, 0, 0, 0,
ax_anim 2, 2, 126, 0, 0, 0, 0,
ax_anim_terminator
sVoltorbAnims_13_6:
ax_anim 2, 0, 125, 0, 0, 0, 0,
ax_anim 2, 0, 126, 0, 0, 0, 0,
ax_anim 2, 0, 127, 0, 0, 0, 0,
ax_anim 2, 0, 128, 0, 0, 0, 0,
ax_anim 2, 0, 129, 0, 0, 0, 0,
ax_anim 2, 0, 122, 0, 0, 0, 0,
ax_anim 2, 0, 123, 0, 0, 0, 0,
ax_anim 2, 0, 124, 0, 0, 0, 0,
ax_anim 2, 2, 125, 0, 0, 0, 0,
ax_anim_terminator
sVoltorbAnims_13_7:
ax_anim 2, 0, 124, 0, 0, 0, 0,
ax_anim 2, 0, 125, 0, 0, 0, 0,
ax_anim 2, 0, 126, 0, 0, 0, 0,
ax_anim 2, 0, 127, 0, 0, 0, 0,
ax_anim 2, 0, 128, 0, 0, 0, 0,
ax_anim 2, 0, 129, 0, 0, 0, 0,
ax_anim 2, 0, 122, 0, 0, 0, 0,
ax_anim 2, 0, 123, 0, 0, 0, 0,
ax_anim 2, 2, 124, 0, 0, 0, 0,
ax_anim_terminator
sVoltorbAnims_13_8:
ax_anim 2, 0, 123, 0, 0, 0, 0,
ax_anim 2, 0, 124, 0, 0, 0, 0,
ax_anim 2, 0, 125, 0, 0, 0, 0,
ax_anim 2, 0, 126, 0, 0, 0, 0,
ax_anim 2, 0, 127, 0, 0, 0, 0,
ax_anim 2, 0, 128, 0, 0, 0, 0,
ax_anim 2, 0, 129, 0, 0, 0, 0,
ax_anim 2, 0, 122, 0, 0, 0, 0,
ax_anim 2, 2, 123, 0, 0, 0, 0,
ax_anim_terminator
sVoltorbGfx1:
.incbin "baserom.gba", 0x948F04, 0x80
sVoltorbSprites1:
ax_sprite sVoltorbGfx1, 0x80
ax_sprite_terminator
sVoltorbGfx2:
.incbin "baserom.gba", 0x948F94, 0x80
sVoltorbSprites2:
ax_sprite sVoltorbGfx2, 0x80
ax_sprite_terminator
sVoltorbGfx3:
.incbin "baserom.gba", 0x949024, 0x80
sVoltorbSprites3:
ax_sprite sVoltorbGfx3, 0x80
ax_sprite_terminator
sVoltorbGfx4:
.incbin "baserom.gba", 0x9490B4, 0x80
sVoltorbSprites4:
ax_sprite sVoltorbGfx4, 0x80
ax_sprite_terminator
sVoltorbGfx5:
.incbin "baserom.gba", 0x949144, 0x80
sVoltorbSprites5:
ax_sprite sVoltorbGfx5, 0x80
ax_sprite_terminator
sVoltorbGfx6:
.incbin "baserom.gba", 0x9491D4, 0x80
sVoltorbSprites6:
ax_sprite sVoltorbGfx6, 0x80
ax_sprite_terminator
sVoltorbGfx7:
.incbin "baserom.gba", 0x949264, 0x80
sVoltorbSprites7:
ax_sprite sVoltorbGfx7, 0x80
ax_sprite_terminator
sVoltorbGfx8:
.incbin "baserom.gba", 0x9492F4, 0x80
sVoltorbSprites8:
ax_sprite sVoltorbGfx8, 0x80
ax_sprite_terminator
sVoltorbGfx9:
.incbin "baserom.gba", 0x949384, 0x80
sVoltorbSprites9:
ax_sprite sVoltorbGfx9, 0x80
ax_sprite_terminator
sVoltorbGfx10:
.incbin "baserom.gba", 0x949414, 0x80
sVoltorbSprites10:
ax_sprite sVoltorbGfx10, 0x80
ax_sprite_terminator
sVoltorbGfx11:
.incbin "baserom.gba", 0x9494A4, 0x80
sVoltorbSprites11:
ax_sprite sVoltorbGfx11, 0x80
ax_sprite_terminator
sVoltorbGfx12:
.incbin "baserom.gba", 0x949534, 0x80
sVoltorbSprites12:
ax_sprite sVoltorbGfx12, 0x80
ax_sprite_terminator
sVoltorbGfx13:
.incbin "baserom.gba", 0x9495C4, 0x80
sVoltorbSprites13:
ax_sprite sVoltorbGfx13, 0x80
ax_sprite_terminator
sVoltorbGfx14:
.incbin "baserom.gba", 0x949654, 0x80
sVoltorbSprites14:
ax_sprite sVoltorbGfx14, 0x80
ax_sprite_terminator
sVoltorbGfx15:
.incbin "baserom.gba", 0x9496E4, 0x80
sVoltorbSprites15:
ax_sprite sVoltorbGfx15, 0x80
ax_sprite_terminator
sVoltorbGfx16:
.incbin "baserom.gba", 0x949774, 0x80
sVoltorbSprites16:
ax_sprite sVoltorbGfx16, 0x80
ax_sprite_terminator
sVoltorbGfx17:
.incbin "baserom.gba", 0x949804, 0x80
sVoltorbSprites17:
ax_sprite sVoltorbGfx17, 0x80
ax_sprite_terminator
sVoltorbGfx18:
.incbin "baserom.gba", 0x949894, 0x80
sVoltorbSprites18:
ax_sprite sVoltorbGfx18, 0x80
ax_sprite_terminator
sVoltorbGfx19:
.incbin "baserom.gba", 0x949924, 0x80
sVoltorbSprites19:
ax_sprite sVoltorbGfx19, 0x80
ax_sprite_terminator
sVoltorbGfx20:
.incbin "baserom.gba", 0x9499B4, 0x80
sVoltorbSprites20:
ax_sprite sVoltorbGfx20, 0x80
ax_sprite_terminator
sVoltorbGfx21:
.incbin "baserom.gba", 0x949A44, 0x80
sVoltorbSprites21:
ax_sprite sVoltorbGfx21, 0x80
ax_sprite_terminator
sVoltorbGfx22:
.incbin "baserom.gba", 0x949AD4, 0x80
sVoltorbSprites22:
ax_sprite sVoltorbGfx22, 0x80
ax_sprite_terminator
sVoltorbGfx23:
.incbin "baserom.gba", 0x949B64, 0x80
sVoltorbSprites23:
ax_sprite sVoltorbGfx23, 0x80
ax_sprite_terminator
sVoltorbGfx24:
.incbin "baserom.gba", 0x949BF4, 0x80
sVoltorbSprites24:
ax_sprite sVoltorbGfx24, 0x80
ax_sprite_terminator
sVoltorbGfx25:
.incbin "baserom.gba", 0x949C84, 0x80
sVoltorbSprites25:
ax_sprite sVoltorbGfx25, 0x80
ax_sprite_terminator
sVoltorbGfx26:
.incbin "baserom.gba", 0x949D14, 0x80
sVoltorbSprites26:
ax_sprite sVoltorbGfx26, 0x80
ax_sprite_terminator
sVoltorbGfx27:
.incbin "baserom.gba", 0x949DA4, 0x200
sVoltorbSprites27:
ax_sprite sVoltorbGfx27, 0x200
ax_sprite_terminator
sVoltorbGfx28:
.incbin "baserom.gba", 0x949FB4, 0x200
sVoltorbSprites28:
ax_sprite sVoltorbGfx28, 0x200
ax_sprite_terminator
sVoltorbGfx29:
.incbin "baserom.gba", 0x94A1C4, 0x200
sVoltorbSprites29:
ax_sprite sVoltorbGfx29, 0x200
ax_sprite_terminator
sVoltorbGfx30:
.incbin "baserom.gba", 0x94A3D4, 0x200
sVoltorbSprites30:
ax_sprite sVoltorbGfx30, 0x200
ax_sprite_terminator
sVoltorbGfx31:
.incbin "baserom.gba", 0x94A5E4, 0x200
sVoltorbSprites31:
ax_sprite sVoltorbGfx31, 0x200
ax_sprite_terminator
sAxPosesVoltorb:
.4byte sVoltorbPose1
.4byte sVoltorbPose2
.4byte sVoltorbPose3
.4byte sVoltorbPose4
.4byte sVoltorbPose5
.4byte sVoltorbPose6
.4byte sVoltorbPose7
.4byte sVoltorbPose8
.4byte sVoltorbPose9
.4byte sVoltorbPose10
.4byte sVoltorbPose11
.4byte sVoltorbPose12
.4byte sVoltorbPose13
.4byte sVoltorbPose14
.4byte sVoltorbPose15
.4byte sVoltorbPose16
.4byte sVoltorbPose17
.4byte sVoltorbPose18
.4byte sVoltorbPose19
.4byte sVoltorbPose20
.4byte sVoltorbPose21
.4byte sVoltorbPose22
.4byte sVoltorbPose23
.4byte sVoltorbPose24
.4byte sVoltorbPose25
.4byte sVoltorbPose26
.4byte sVoltorbPose27
.4byte sVoltorbPose28
.4byte sVoltorbPose29
.4byte sVoltorbPose30
.4byte sVoltorbPose31
.4byte sVoltorbPose32
.4byte sVoltorbPose33
.4byte sVoltorbPose34
.4byte sVoltorbPose35
.4byte sVoltorbPose36
.4byte sVoltorbPose37
.4byte sVoltorbPose38
.4byte sVoltorbPose39
.4byte sVoltorbPose40
.4byte sVoltorbPose41
.4byte sVoltorbPose42
.4byte sVoltorbPose43
.4byte sVoltorbPose44
.4byte sVoltorbPose45
.4byte sVoltorbPose46
.4byte sVoltorbPose47
.4byte sVoltorbPose48
.4byte sVoltorbPose49
.4byte sVoltorbPose50
.4byte sVoltorbPose51
.4byte sVoltorbPose52
.4byte sVoltorbPose53
.4byte sVoltorbPose54
.4byte sVoltorbPose55
.4byte sVoltorbPose56
.4byte sVoltorbPose57
.4byte sVoltorbPose58
.4byte sVoltorbPose59
.4byte sVoltorbPose60
.4byte sVoltorbPose61
.4byte sVoltorbPose62
.4byte sVoltorbPose63
.4byte sVoltorbPose64
.4byte sVoltorbPose65
.4byte sVoltorbPose66
.4byte sVoltorbPose67
.4byte sVoltorbPose68
.4byte sVoltorbPose69
.4byte sVoltorbPose70
.4byte sVoltorbPose71
.4byte sVoltorbPose72
.4byte sVoltorbPose73
.4byte sVoltorbPose74
.4byte sVoltorbPose75
.4byte sVoltorbPose76
.4byte sVoltorbPose77
.4byte sVoltorbPose78
.4byte sVoltorbPose79
.4byte sVoltorbPose80
.4byte sVoltorbPose81
.4byte sVoltorbPose82
.4byte sVoltorbPose83
.4byte sVoltorbPose84
.4byte sVoltorbPose85
.4byte sVoltorbPose86
.4byte sVoltorbPose87
.4byte sVoltorbPose88
.4byte sVoltorbPose89
.4byte sVoltorbPose90
.4byte sVoltorbPose91
.4byte sVoltorbPose92
.4byte sVoltorbPose93
.4byte sVoltorbPose94
.4byte sVoltorbPose95
.4byte sVoltorbPose96
.4byte sVoltorbPose97
.4byte sVoltorbPose98
.4byte sVoltorbPose99
.4byte sVoltorbPose100
.4byte sVoltorbPose101
.4byte sVoltorbPose102
.4byte sVoltorbPose103
.4byte sVoltorbPose104
.4byte sVoltorbPose105
.4byte sVoltorbPose106
.4byte sVoltorbPose107
.4byte sVoltorbPose108
.4byte sVoltorbPose109
.4byte sVoltorbPose110
.4byte sVoltorbPose111
.4byte sVoltorbPose112
.4byte sVoltorbPose113
.4byte sVoltorbPose114
.4byte sVoltorbPose115
.4byte sVoltorbPose116
.4byte sVoltorbPose117
.4byte sVoltorbPose118
.4byte sVoltorbPose119
.4byte sVoltorbPose120
.4byte sVoltorbPose121
.4byte sVoltorbPose122
.4byte sVoltorbPose123
.4byte sVoltorbPose124
.4byte sVoltorbPose125
.4byte sVoltorbPose126
.4byte sVoltorbPose127
.4byte sVoltorbPose128
.4byte sVoltorbPose129
.4byte sVoltorbPose130
sAxPositionsVoltorb:
.2byte   -1,   -2, 	  -7,   -7, 	   6,   -7, 	  -1,   -8
.2byte   -1,   -1, 	  -7,   -6, 	   6,   -6, 	  -1,   -8
.2byte   -1,   -4, 	  -7,   -8, 	   6,   -8, 	  -1,   -8
.2byte    5,   -4, 	  -3,   -4, 	   4,  -11, 	  -1,   -7
.2byte    3,   -2, 	  -3,   -6, 	   5,  -10, 	  -1,   -7
.2byte    5,   -5, 	  -4,   -4, 	   4,  -10, 	  -1,   -6
.2byte    5,   -4, 	   0,   -4, 	   0,  -11, 	  -1,   -7
.2byte    3,   -2, 	  -1,   -5, 	   1,  -11, 	  -1,   -7
.2byte    6,   -6, 	  -1,   -4, 	  -1,  -11, 	  -1,   -6
.2byte    5,  -10, 	   3,   -5, 	  -2,  -12, 	  -1,   -7
.2byte    6,   -6, 	   3,   -4, 	  -1,  -10, 	  -1,   -6
.2byte    5,  -10, 	   2,   -5, 	  -4,  -10, 	  -1,   -7
.2byte   -1,  -11, 	   5,   -9, 	  -6,   -9, 	  -1,   -7
.2byte   -1,   -7, 	   6,   -8, 	  -6,   -9, 	  -1,   -8
.2byte   -1,  -14, 	   5,  -10, 	  -6,  -10, 	  -1,   -8
.2byte   -5,  -11, 	   3,  -12, 	  -4,   -8, 	  -1,   -8
.2byte   -3,   -7, 	   0,  -11, 	  -5,   -8, 	  -1,   -7
.2byte   -6,  -11, 	   4,  -10, 	  -3,   -6, 	  -1,   -7
.2byte   -5,   -3, 	  -2,  -12, 	  -1,   -5, 	  -1,   -7
.2byte   -4,   -2, 	  -6,   -9, 	  -2,   -4, 	  -1,   -7
.2byte   -6,   -6, 	  -4,  -12, 	  -1,   -5, 	  -1,   -7
.2byte   -5,   -3, 	  -5,  -11, 	   2,   -3, 	  -1,   -7
.2byte   -4,   -2, 	  -5,   -9, 	   2,   -2, 	  -1,   -8
.2byte   -5,   -5, 	  -3,  -12, 	   2,   -6, 	  -1,   -7
.2byte   -1,   -2, 	  -7,   -7, 	   6,   -7, 	  -1,   -8
.2byte   -5,   -3, 	  -5,  -11, 	   2,   -3, 	  -1,   -7
.2byte   -5,   -3, 	  -2,  -12, 	  -1,   -5, 	  -1,   -7
.2byte   -5,  -11, 	   3,  -12, 	  -4,   -8, 	  -1,   -8
.2byte   -1,  -11, 	   5,   -9, 	  -6,   -9, 	  -1,   -7
.2byte    5,  -10, 	   3,   -5, 	  -2,  -12, 	  -1,   -7
.2byte    5,   -4, 	   0,   -4, 	   0,  -11, 	  -1,   -7
.2byte    5,   -4, 	  -3,   -4, 	   4,  -11, 	  -1,   -7
.2byte   -1,   -2, 	  -7,   -7, 	   6,   -7, 	  -1,   -8
.2byte   -5,   -3, 	  -5,  -11, 	   2,   -3, 	  -1,   -7
.2byte   -5,   -3, 	  -2,  -12, 	  -1,   -5, 	  -1,   -7
.2byte   -5,  -11, 	   3,  -12, 	  -4,   -8, 	  -1,   -8
.2byte   -1,  -11, 	   5,   -9, 	  -6,   -9, 	  -1,   -7
.2byte    5,  -10, 	   3,   -5, 	  -2,  -12, 	  -1,   -7
.2byte    5,   -4, 	   0,   -4, 	   0,  -11, 	  -1,   -7
.2byte    5,   -4, 	  -3,   -4, 	   4,  -11, 	  -1,   -7
.2byte   -1,   -2, 	  -7,   -7, 	   6,   -7, 	  -1,   -8
.2byte   -5,   -3, 	  -5,  -11, 	   2,   -3, 	  -1,   -7
.2byte   -5,   -3, 	  -2,  -12, 	  -1,   -5, 	  -1,   -7
.2byte   -5,  -11, 	   3,  -12, 	  -4,   -8, 	  -1,   -8
.2byte   -1,  -11, 	   5,   -9, 	  -6,   -9, 	  -1,   -7
.2byte    5,  -10, 	   3,   -5, 	  -2,  -12, 	  -1,   -7
.2byte    5,   -4, 	   0,   -4, 	   0,  -11, 	  -1,   -7
.2byte    5,   -4, 	  -3,   -4, 	   4,  -11, 	  -1,   -7
.2byte   -1,   -2, 	  -7,   -7, 	   6,   -7, 	  -1,   -8
.2byte   -5,   -3, 	  -5,  -11, 	   2,   -3, 	  -1,   -7
.2byte   -5,   -3, 	  -2,  -12, 	  -1,   -5, 	  -1,   -7
.2byte   -5,  -11, 	   3,  -12, 	  -4,   -8, 	  -1,   -8
.2byte   -1,  -11, 	   5,   -9, 	  -6,   -9, 	  -1,   -7
.2byte    5,  -10, 	   3,   -5, 	  -2,  -12, 	  -1,   -7
.2byte    5,   -4, 	   0,   -4, 	   0,  -11, 	  -1,   -7
.2byte    5,   -4, 	  -3,   -4, 	   4,  -11, 	  -1,   -7
.2byte    0,   -2, 	  -7,   -8, 	   6,   -8, 	  -1,   -7
.2byte    0,   -1, 	  -7,   -7, 	   6,   -7, 	   0,   -7
.2byte   -1,   -8, 	  -7,   -7, 	   6,   -7, 	  -1,   -7
.2byte   -1,   -8, 	   1,  -13, 	  -8,   -5, 	  -3,   -9
.2byte    2,   -8, 	  -4,  -11, 	  -4,   -6, 	  -3,   -6
.2byte    2,   -9, 	  -8,   -9, 	  -1,   -6, 	  -4,   -5
.2byte   -1,   -9, 	   6,   -4, 	  -7,   -4, 	  -1,   -4
.2byte   -3,   -9, 	   7,   -9, 	   0,   -6, 	   3,   -5
.2byte   -3,   -8, 	   3,  -11, 	   3,   -6, 	   2,   -6
.2byte    0,   -8, 	  -2,  -13, 	   7,   -5, 	   2,   -9
.2byte   -1,   -2, 	  -7,   -7, 	   6,   -7, 	  -1,   -8
.2byte   -5,   -3, 	  -5,  -11, 	   2,   -3, 	  -1,   -7
.2byte   -5,   -3, 	  -2,  -12, 	  -1,   -5, 	  -1,   -7
.2byte   -5,  -11, 	   3,  -12, 	  -4,   -8, 	  -1,   -8
.2byte   -1,  -11, 	   5,   -9, 	  -6,   -9, 	  -1,   -7
.2byte    5,  -10, 	   3,   -5, 	  -2,  -12, 	  -1,   -7
.2byte    5,   -4, 	   0,   -4, 	   0,  -11, 	  -1,   -7
.2byte    5,   -4, 	  -3,   -4, 	   4,  -11, 	  -1,   -7
.2byte   -1,   -2, 	  -7,   -7, 	   6,   -7, 	  -1,   -8
.2byte   -5,   -3, 	  -5,  -11, 	   2,   -3, 	  -1,   -7
.2byte   -5,   -3, 	  -2,  -12, 	  -1,   -5, 	  -1,   -7
.2byte   -5,  -11, 	   3,  -12, 	  -4,   -8, 	  -1,   -8
.2byte   -1,  -11, 	   5,   -9, 	  -6,   -9, 	  -1,   -7
.2byte    5,  -10, 	   3,   -5, 	  -2,  -12, 	  -1,   -7
.2byte    5,   -4, 	   0,   -4, 	   0,  -11, 	  -1,   -7
.2byte    5,   -4, 	  -3,   -4, 	   4,  -11, 	  -1,   -7
.2byte   -1,   -2, 	  -7,   -7, 	   6,   -7, 	  -1,   -8
.2byte    5,   -4, 	  -3,   -4, 	   4,  -11, 	  -1,   -7
.2byte    5,   -4, 	   0,   -4, 	   0,  -11, 	  -1,   -7
.2byte    5,  -10, 	   3,   -5, 	  -2,  -12, 	  -1,   -7
.2byte   -1,  -11, 	   5,   -9, 	  -6,   -9, 	  -1,   -7
.2byte   -5,  -11, 	   3,  -12, 	  -4,   -8, 	  -1,   -8
.2byte   -5,   -3, 	  -2,  -12, 	  -1,   -5, 	  -1,   -7
.2byte   -5,   -3, 	  -5,  -11, 	   2,   -3, 	  -1,   -7
.2byte   -1,   -2, 	  -7,   -7, 	   6,   -7, 	  -1,   -8
.2byte   -1,   -4, 	  -7,   -8, 	   6,   -8, 	  -1,   -8
.2byte   -1,   -1, 	  -7,   -6, 	   6,   -6, 	  -1,   -8
.2byte    5,   -4, 	  -3,   -4, 	   4,  -11, 	  -1,   -7
.2byte    5,   -5, 	  -4,   -4, 	   4,  -10, 	  -1,   -6
.2byte    3,   -2, 	  -3,   -6, 	   5,  -10, 	  -1,   -7
.2byte    5,   -4, 	   0,   -4, 	   0,  -11, 	  -1,   -7
.2byte    6,   -6, 	  -1,   -4, 	  -1,  -11, 	  -1,   -6
.2byte    3,   -2, 	  -1,   -5, 	   1,  -11, 	  -1,   -7
.2byte    5,  -10, 	   3,   -5, 	  -2,  -12, 	  -1,   -7
.2byte    5,  -10, 	   2,   -5, 	  -4,  -10, 	  -1,   -7
.2byte    6,   -6, 	   3,   -4, 	  -1,  -10, 	  -1,   -6
.2byte   -1,  -11, 	   5,   -9, 	  -6,   -9, 	  -1,   -7
.2byte   -1,  -14, 	   5,  -10, 	  -6,  -10, 	  -1,   -8
.2byte   -1,   -7, 	   6,   -8, 	  -6,   -9, 	  -1,   -8
.2byte   -5,  -11, 	   3,  -12, 	  -4,   -8, 	  -1,   -8
.2byte   -6,  -11, 	   4,  -10, 	  -3,   -6, 	  -1,   -7
.2byte   -3,   -7, 	   0,  -11, 	  -5,   -8, 	  -1,   -7
.2byte   -5,   -3, 	  -2,  -12, 	  -1,   -5, 	  -1,   -7
.2byte   -6,   -6, 	  -4,  -12, 	  -1,   -5, 	  -1,   -7
.2byte   -4,   -2, 	  -6,   -9, 	  -2,   -4, 	  -1,   -7
.2byte   -5,   -3, 	  -5,  -11, 	   2,   -3, 	  -1,   -7
.2byte   -5,   -5, 	  -3,  -12, 	   2,   -6, 	  -1,   -7
.2byte   -4,   -2, 	  -5,   -9, 	   2,   -2, 	  -1,   -8
.2byte   -1,   -2, 	  -7,   -7, 	   6,   -7, 	  -1,   -8
.2byte   -5,   -3, 	  -5,  -11, 	   2,   -3, 	  -1,   -7
.2byte   -5,   -3, 	  -2,  -12, 	  -1,   -5, 	  -1,   -7
.2byte   -5,  -11, 	   3,  -12, 	  -4,   -8, 	  -1,   -8
.2byte   -1,  -11, 	   5,   -9, 	  -6,   -9, 	  -1,   -7
.2byte    5,  -10, 	   3,   -5, 	  -2,  -12, 	  -1,   -7
.2byte    5,   -4, 	   0,   -4, 	   0,  -11, 	  -1,   -7
.2byte    5,   -4, 	  -3,   -4, 	   4,  -11, 	  -1,   -7
.2byte   -1,   -2, 	  -7,   -7, 	   6,   -7, 	  -1,   -8
.2byte   -5,   -3, 	  -5,  -11, 	   2,   -3, 	  -1,   -7
.2byte   -5,   -3, 	  -2,  -12, 	  -1,   -5, 	  -1,   -7
.2byte   -5,  -11, 	   3,  -12, 	  -4,   -8, 	  -1,   -8
.2byte   -1,  -11, 	   5,   -9, 	  -6,   -9, 	  -1,   -7
.2byte    5,  -10, 	   3,   -5, 	  -2,  -12, 	  -1,   -7
.2byte    5,   -4, 	   0,   -4, 	   0,  -11, 	  -1,   -7
.2byte    5,   -4, 	  -3,   -4, 	   4,  -11, 	  -1,   -7
sVoltorbAnimTable1:
.4byte sVoltorbAnims_1_1
.4byte sVoltorbAnims_1_2
.4byte sVoltorbAnims_1_3
.4byte sVoltorbAnims_1_4
.4byte sVoltorbAnims_1_5
.4byte sVoltorbAnims_1_6
.4byte sVoltorbAnims_1_7
.4byte sVoltorbAnims_1_8
sVoltorbAnimTable2:
.4byte sVoltorbAnims_2_1
.4byte sVoltorbAnims_2_2
.4byte sVoltorbAnims_2_3
.4byte sVoltorbAnims_2_4
.4byte sVoltorbAnims_2_5
.4byte sVoltorbAnims_2_6
.4byte sVoltorbAnims_2_7
.4byte sVoltorbAnims_2_8
sVoltorbAnimTable3:
.4byte sVoltorbAnims_3_1
.4byte sVoltorbAnims_3_2
.4byte sVoltorbAnims_3_3
.4byte sVoltorbAnims_3_4
.4byte sVoltorbAnims_3_5
.4byte sVoltorbAnims_3_6
.4byte sVoltorbAnims_3_7
.4byte sVoltorbAnims_3_8
sVoltorbAnimTable4:
.4byte sVoltorbAnims_4_1
.4byte sVoltorbAnims_4_2
.4byte sVoltorbAnims_4_3
.4byte sVoltorbAnims_4_4
.4byte sVoltorbAnims_4_5
.4byte sVoltorbAnims_4_6
.4byte sVoltorbAnims_4_7
.4byte sVoltorbAnims_4_8
sVoltorbAnimTable5:
.4byte sVoltorbAnims_5_1
.4byte sVoltorbAnims_5_2
.4byte sVoltorbAnims_5_3
.4byte sVoltorbAnims_5_4
.4byte sVoltorbAnims_5_5
.4byte sVoltorbAnims_5_6
.4byte sVoltorbAnims_5_7
.4byte sVoltorbAnims_5_8
sVoltorbAnimTable6:
.4byte sVoltorbAnims_6_1
.4byte sVoltorbAnims_6_1
.4byte sVoltorbAnims_6_1
.4byte sVoltorbAnims_6_1
.4byte sVoltorbAnims_6_1
.4byte sVoltorbAnims_6_1
.4byte sVoltorbAnims_6_1
.4byte sVoltorbAnims_6_1
sVoltorbAnimTable7:
.4byte sVoltorbAnims_7_1
.4byte sVoltorbAnims_7_2
.4byte sVoltorbAnims_7_3
.4byte sVoltorbAnims_7_4
.4byte sVoltorbAnims_7_5
.4byte sVoltorbAnims_7_6
.4byte sVoltorbAnims_7_7
.4byte sVoltorbAnims_7_8
sVoltorbAnimTable8:
.4byte sVoltorbAnims_8_1
.4byte sVoltorbAnims_8_2
.4byte sVoltorbAnims_8_3
.4byte sVoltorbAnims_8_4
.4byte sVoltorbAnims_8_5
.4byte sVoltorbAnims_8_6
.4byte sVoltorbAnims_8_7
.4byte sVoltorbAnims_8_8
sVoltorbAnimTable9:
.4byte sVoltorbAnims_9_1
.4byte sVoltorbAnims_9_2
.4byte sVoltorbAnims_9_3
.4byte sVoltorbAnims_9_4
.4byte sVoltorbAnims_9_5
.4byte sVoltorbAnims_9_6
.4byte sVoltorbAnims_9_7
.4byte sVoltorbAnims_9_8
sVoltorbAnimTable10:
.4byte sVoltorbAnims_10_1
.4byte sVoltorbAnims_10_2
.4byte sVoltorbAnims_10_3
.4byte sVoltorbAnims_10_4
.4byte sVoltorbAnims_10_5
.4byte sVoltorbAnims_10_6
.4byte sVoltorbAnims_10_7
.4byte sVoltorbAnims_10_8
sVoltorbAnimTable11:
.4byte sVoltorbAnims_11_1
.4byte sVoltorbAnims_11_2
.4byte sVoltorbAnims_11_3
.4byte sVoltorbAnims_11_4
.4byte sVoltorbAnims_11_5
.4byte sVoltorbAnims_11_6
.4byte sVoltorbAnims_11_7
.4byte sVoltorbAnims_11_8
sVoltorbAnimTable12:
.4byte sVoltorbAnims_12_1
.4byte sVoltorbAnims_12_2
.4byte sVoltorbAnims_12_3
.4byte sVoltorbAnims_12_4
.4byte sVoltorbAnims_12_5
.4byte sVoltorbAnims_12_6
.4byte sVoltorbAnims_12_7
.4byte sVoltorbAnims_12_8
sVoltorbAnimTable13:
.4byte sVoltorbAnims_13_1
.4byte sVoltorbAnims_13_2
.4byte sVoltorbAnims_13_3
.4byte sVoltorbAnims_13_4
.4byte sVoltorbAnims_13_5
.4byte sVoltorbAnims_13_6
.4byte sVoltorbAnims_13_7
.4byte sVoltorbAnims_13_8
sAxAnimationsVoltorb:
.4byte sVoltorbAnimTable1
.4byte sVoltorbAnimTable2
.4byte sVoltorbAnimTable3
.4byte sVoltorbAnimTable4
.4byte sVoltorbAnimTable5
.4byte sVoltorbAnimTable6
.4byte sVoltorbAnimTable7
.4byte sVoltorbAnimTable8
.4byte sVoltorbAnimTable9
.4byte sVoltorbAnimTable10
.4byte sVoltorbAnimTable11
.4byte sVoltorbAnimTable12
.4byte sVoltorbAnimTable13
sAxSpritesVoltorb:
.4byte sVoltorbSprites1
.4byte sVoltorbSprites2
.4byte sVoltorbSprites3
.4byte sVoltorbSprites4
.4byte sVoltorbSprites5
.4byte sVoltorbSprites6
.4byte sVoltorbSprites7
.4byte sVoltorbSprites8
.4byte sVoltorbSprites9
.4byte sVoltorbSprites10
.4byte sVoltorbSprites11
.4byte sVoltorbSprites12
.4byte sVoltorbSprites13
.4byte sVoltorbSprites14
.4byte sVoltorbSprites15
.4byte sVoltorbSprites16
.4byte sVoltorbSprites17
.4byte sVoltorbSprites18
.4byte sVoltorbSprites19
.4byte sVoltorbSprites20
.4byte sVoltorbSprites21
.4byte sVoltorbSprites22
.4byte sVoltorbSprites23
.4byte sVoltorbSprites24
.4byte sVoltorbSprites25
.4byte sVoltorbSprites26
.4byte sVoltorbSprites27
.4byte sVoltorbSprites28
.4byte sVoltorbSprites29
.4byte sVoltorbSprites30
.4byte sVoltorbSprites31
sAxMainVoltorb:
ax_main sAxPosesVoltorb, sAxAnimationsVoltorb, 13, sAxSpritesVoltorb, sAxPositionsVoltorb
