.global gAxWeedle
gAxWeedle:
ax_siro sAxMainWeedle
sWeedlePose1:
ax_pose 0, 0x81eb, 0x80f8, 0x4c00
ax_pose_terminator
sWeedlePose2:
ax_pose 1, 0x81eb, 0x80f8, 0x4c00
ax_pose_terminator
sWeedlePose3:
ax_pose 2, 0x81eb, 0x80f8, 0x4c00
ax_pose_terminator
sWeedlePose4:
ax_pose 3, 0x01eb, 0x90ef, 0x4c00
ax_pose_terminator
sWeedlePose5:
ax_pose 4, 0x01eb, 0x90ef, 0x4c00
ax_pose_terminator
sWeedlePose6:
ax_pose 5, 0x01eb, 0x90ef, 0x4c00
ax_pose_terminator
sWeedlePose7:
ax_pose 6, 0x01ea, 0x90ed, 0x4c00
ax_pose_terminator
sWeedlePose8:
ax_pose 7, 0x01ea, 0x90ed, 0x4c00
ax_pose_terminator
sWeedlePose9:
ax_pose 8, 0x01ea, 0x90ed, 0x4c00
ax_pose_terminator
sWeedlePose10:
ax_pose 9, 0x01ea, 0x90ef, 0x4c00
ax_pose_terminator
sWeedlePose11:
ax_pose 10, 0x01ea, 0x90ef, 0x4c00
ax_pose_terminator
sWeedlePose12:
ax_pose 11, 0x01ea, 0x90ef, 0x4c00
ax_pose_terminator
sWeedlePose13:
ax_pose 12, 0x81ea, 0x80f8, 0x4c00
ax_pose_terminator
sWeedlePose14:
ax_pose 13, 0x81ea, 0x80f8, 0x4c00
ax_pose_terminator
sWeedlePose15:
ax_pose 14, 0x81ea, 0x80f8, 0x4c00
ax_pose_terminator
sWeedlePose16:
ax_pose 9, 0x01ea, 0x80f0, 0x4c00
ax_pose_terminator
sWeedlePose17:
ax_pose 10, 0x01ea, 0x80f0, 0x4c00
ax_pose_terminator
sWeedlePose18:
ax_pose 11, 0x01ea, 0x80f0, 0x4c00
ax_pose_terminator
sWeedlePose19:
ax_pose 6, 0x01ea, 0x80f2, 0x4c00
ax_pose_terminator
sWeedlePose20:
ax_pose 7, 0x01ea, 0x80f2, 0x4c00
ax_pose_terminator
sWeedlePose21:
ax_pose 8, 0x01ea, 0x80f2, 0x4c00
ax_pose_terminator
sWeedlePose22:
ax_pose 3, 0x01eb, 0x80f0, 0x4c00
ax_pose_terminator
sWeedlePose23:
ax_pose 4, 0x01eb, 0x80f0, 0x4c00
ax_pose_terminator
sWeedlePose24:
ax_pose 5, 0x01eb, 0x80f0, 0x4c00
ax_pose_terminator
sWeedlePose25:
ax_pose 0, 0x81eb, 0x80f8, 0x4c00
ax_pose_terminator
sWeedlePose26:
ax_pose 1, 0x81eb, 0x80f8, 0x4c00
ax_pose_terminator
sWeedlePose27:
ax_pose 2, 0x81eb, 0x80f8, 0x4c00
ax_pose_terminator
sWeedlePose28:
ax_pose 15, 0x81ed, 0x80f8, 0x4c00
ax_pose_terminator
sWeedlePose29:
ax_pose 16, 0x81eb, 0x80f8, 0x4c00
ax_pose 15, 0x81eb, 0x80f8, 0x4c08
ax_pose_terminator
sWeedlePose30:
ax_pose 3, 0x01eb, 0x90ef, 0x4c00
ax_pose_terminator
sWeedlePose31:
ax_pose 4, 0x01eb, 0x90ef, 0x4c00
ax_pose_terminator
sWeedlePose32:
ax_pose 5, 0x01eb, 0x90ef, 0x4c00
ax_pose_terminator
sWeedlePose33:
ax_pose 17, 0x41f5, 0x90ef, 0x4c00
ax_pose_terminator
sWeedlePose34:
ax_pose 6, 0x01ea, 0x90ed, 0x4c00
ax_pose_terminator
sWeedlePose35:
ax_pose 7, 0x01ea, 0x90ed, 0x4c00
ax_pose_terminator
sWeedlePose36:
ax_pose 8, 0x01ea, 0x90ed, 0x4c00
ax_pose_terminator
sWeedlePose37:
ax_pose 18, 0x41f2, 0x90ee, 0x4c00
ax_pose_terminator
sWeedlePose38:
ax_pose 9, 0x01ea, 0x90ef, 0x4c00
ax_pose_terminator
sWeedlePose39:
ax_pose 10, 0x01ea, 0x90ef, 0x4c00
ax_pose_terminator
sWeedlePose40:
ax_pose 11, 0x01ea, 0x90ef, 0x4c00
ax_pose_terminator
sWeedlePose41:
ax_pose 19, 0x01ef, 0x90ef, 0x4c00
ax_pose_terminator
sWeedlePose42:
ax_pose 12, 0x81ea, 0x80f8, 0x4c00
ax_pose_terminator
sWeedlePose43:
ax_pose 13, 0x81ea, 0x80f8, 0x4c00
ax_pose_terminator
sWeedlePose44:
ax_pose 14, 0x81ea, 0x80f8, 0x4c00
ax_pose_terminator
sWeedlePose45:
ax_pose 20, 0x81ee, 0x80f8, 0x4c00
ax_pose_terminator
sWeedlePose46:
ax_pose 9, 0x01ea, 0x80f0, 0x4c00
ax_pose_terminator
sWeedlePose47:
ax_pose 10, 0x01ea, 0x80f0, 0x4c00
ax_pose_terminator
sWeedlePose48:
ax_pose 11, 0x01ea, 0x80f0, 0x4c00
ax_pose_terminator
sWeedlePose49:
ax_pose 19, 0x01ef, 0x80f0, 0x4c00
ax_pose_terminator
sWeedlePose50:
ax_pose 6, 0x01ea, 0x80f2, 0x4c00
ax_pose_terminator
sWeedlePose51:
ax_pose 7, 0x01ea, 0x80f2, 0x4c00
ax_pose_terminator
sWeedlePose52:
ax_pose 8, 0x01ea, 0x80f2, 0x4c00
ax_pose_terminator
sWeedlePose53:
ax_pose 18, 0x41f2, 0x80f1, 0x4c00
ax_pose_terminator
sWeedlePose54:
ax_pose 3, 0x01eb, 0x80f0, 0x4c00
ax_pose_terminator
sWeedlePose55:
ax_pose 4, 0x01eb, 0x80f0, 0x4c00
ax_pose_terminator
sWeedlePose56:
ax_pose 5, 0x01eb, 0x80f0, 0x4c00
ax_pose_terminator
sWeedlePose57:
ax_pose 17, 0x41f5, 0x80f0, 0x4c00
ax_pose_terminator
sWeedlePose58:
ax_pose 0, 0x81eb, 0x80f8, 0x4c00
ax_pose_terminator
sWeedlePose59:
ax_pose 1, 0x81eb, 0x80f8, 0x4c00
ax_pose_terminator
sWeedlePose60:
ax_pose 2, 0x81eb, 0x80f8, 0x4c00
ax_pose_terminator
sWeedlePose61:
ax_pose 15, 0x81ed, 0x80f8, 0x4c00
ax_pose_terminator
sWeedlePose62:
ax_pose 16, 0x81ed, 0x80f8, 0x4c00
ax_pose 15, 0x81ec, 0x80f8, 0x4c08
ax_pose_terminator
sWeedlePose63:
ax_pose 3, 0x01eb, 0x90ef, 0x4c00
ax_pose_terminator
sWeedlePose64:
ax_pose 4, 0x01eb, 0x90ef, 0x4c00
ax_pose_terminator
sWeedlePose65:
ax_pose 5, 0x01eb, 0x90ef, 0x4c00
ax_pose_terminator
sWeedlePose66:
ax_pose 17, 0x41f5, 0x90ef, 0x4c00
ax_pose_terminator
sWeedlePose67:
ax_pose 21, 0x01eb, 0x90f0, 0x4c00
ax_pose 17, 0x41f5, 0x90ef, 0x4c10
ax_pose_terminator
sWeedlePose68:
ax_pose 6, 0x01ea, 0x90ed, 0x4c00
ax_pose_terminator
sWeedlePose69:
ax_pose 7, 0x01ea, 0x90ed, 0x4c00
ax_pose_terminator
sWeedlePose70:
ax_pose 8, 0x01ea, 0x90ed, 0x4c00
ax_pose_terminator
sWeedlePose71:
ax_pose 18, 0x41f2, 0x90ee, 0x4c00
ax_pose_terminator
sWeedlePose72:
ax_pose 22, 0x01ea, 0x90f0, 0x4c00
ax_pose 18, 0x41f2, 0x90ee, 0x4c10
ax_pose_terminator
sWeedlePose73:
ax_pose 9, 0x01ea, 0x90ef, 0x4c00
ax_pose_terminator
sWeedlePose74:
ax_pose 10, 0x01ea, 0x90ef, 0x4c00
ax_pose_terminator
sWeedlePose75:
ax_pose 11, 0x01ea, 0x90ef, 0x4c00
ax_pose_terminator
sWeedlePose76:
ax_pose 19, 0x01ef, 0x90ef, 0x4c00
ax_pose_terminator
sWeedlePose77:
ax_pose 23, 0x01ef, 0x90f0, 0x4c00
ax_pose 19, 0x01ef, 0x90ef, 0x4c10
ax_pose_terminator
sWeedlePose78:
ax_pose 12, 0x81ea, 0x80f8, 0x4c00
ax_pose_terminator
sWeedlePose79:
ax_pose 13, 0x81ea, 0x80f8, 0x4c00
ax_pose_terminator
sWeedlePose80:
ax_pose 14, 0x81ea, 0x80f8, 0x4c00
ax_pose_terminator
sWeedlePose81:
ax_pose 20, 0x81ee, 0x80f8, 0x4c00
ax_pose_terminator
sWeedlePose82:
ax_pose 24, 0x81ed, 0x80f8, 0x4c00
ax_pose 20, 0x81ee, 0x80f8, 0x4c08
ax_pose_terminator
sWeedlePose83:
ax_pose 9, 0x01ea, 0x80f0, 0x4c00
ax_pose_terminator
sWeedlePose84:
ax_pose 10, 0x01ea, 0x80f0, 0x4c00
ax_pose_terminator
sWeedlePose85:
ax_pose 11, 0x01ea, 0x80f0, 0x4c00
ax_pose_terminator
sWeedlePose86:
ax_pose 19, 0x01ef, 0x80f0, 0x4c00
ax_pose_terminator
sWeedlePose87:
ax_pose 23, 0x01ef, 0x80ef, 0x4c00
ax_pose 19, 0x01ef, 0x80f0, 0x4c10
ax_pose_terminator
sWeedlePose88:
ax_pose 6, 0x01ea, 0x80f2, 0x4c00
ax_pose_terminator
sWeedlePose89:
ax_pose 7, 0x01ea, 0x80f2, 0x4c00
ax_pose_terminator
sWeedlePose90:
ax_pose 8, 0x01ea, 0x80f2, 0x4c00
ax_pose_terminator
sWeedlePose91:
ax_pose 18, 0x41f2, 0x80f1, 0x4c00
ax_pose_terminator
sWeedlePose92:
ax_pose 22, 0x01ea, 0x80ef, 0x4c00
ax_pose 18, 0x41f2, 0x80f1, 0x4c10
ax_pose_terminator
sWeedlePose93:
ax_pose 3, 0x01eb, 0x80f0, 0x4c00
ax_pose_terminator
sWeedlePose94:
ax_pose 4, 0x01eb, 0x80f0, 0x4c00
ax_pose_terminator
sWeedlePose95:
ax_pose 5, 0x01eb, 0x80f0, 0x4c00
ax_pose_terminator
sWeedlePose96:
ax_pose 17, 0x41f5, 0x80f0, 0x4c00
ax_pose_terminator
sWeedlePose97:
ax_pose 21, 0x01eb, 0x80ef, 0x4c00
ax_pose 17, 0x41f5, 0x80f0, 0x4c10
ax_pose_terminator
sWeedlePose98:
ax_pose 0, 0x81eb, 0x80f8, 0x4c00
ax_pose_terminator
sWeedlePose99:
ax_pose 25, 0x81eb, 0x80f7, 0x4c00
ax_pose_terminator
sWeedlePose100:
ax_pose 26, 0x81eb, 0x80f7, 0x4c00
ax_pose_terminator
sWeedlePose101:
ax_pose 3, 0x01eb, 0x90ef, 0x4c00
ax_pose_terminator
sWeedlePose102:
ax_pose 27, 0x81ee, 0x90fb, 0x4c00
ax_pose_terminator
sWeedlePose103:
ax_pose 28, 0x81ee, 0x90fb, 0x4c00
ax_pose_terminator
sWeedlePose104:
ax_pose 6, 0x01ea, 0x90ed, 0x4c00
ax_pose_terminator
sWeedlePose105:
ax_pose 29, 0x81ec, 0x90f9, 0x4c00
ax_pose_terminator
sWeedlePose106:
ax_pose 30, 0x81ec, 0x90f9, 0x4c00
ax_pose_terminator
sWeedlePose107:
ax_pose 9, 0x01ea, 0x90ef, 0x4c00
ax_pose_terminator
sWeedlePose108:
ax_pose 31, 0x01eb, 0x90ea, 0x4c00
ax_pose_terminator
sWeedlePose109:
ax_pose 32, 0x01eb, 0x90ea, 0x4c00
ax_pose_terminator
sWeedlePose110:
ax_pose 12, 0x81ea, 0x80f8, 0x4c00
ax_pose_terminator
sWeedlePose111:
ax_pose 33, 0x81ed, 0x80f8, 0x4c00
ax_pose_terminator
sWeedlePose112:
ax_pose 34, 0x01ed, 0x80f8, 0x4c00
ax_pose_terminator
sWeedlePose113:
ax_pose 9, 0x01ea, 0x80f0, 0x4c00
ax_pose_terminator
sWeedlePose114:
ax_pose 31, 0x01eb, 0x80f5, 0x4c00
ax_pose_terminator
sWeedlePose115:
ax_pose 32, 0x01eb, 0x80f5, 0x4c00
ax_pose_terminator
sWeedlePose116:
ax_pose 6, 0x01ea, 0x80f2, 0x4c00
ax_pose_terminator
sWeedlePose117:
ax_pose 29, 0x81ec, 0x80f6, 0x4c00
ax_pose_terminator
sWeedlePose118:
ax_pose 30, 0x81ec, 0x80f6, 0x4c00
ax_pose_terminator
sWeedlePose119:
ax_pose 3, 0x01eb, 0x80f0, 0x4c00
ax_pose_terminator
sWeedlePose120:
ax_pose 27, 0x81ee, 0x80f6, 0x4c00
ax_pose_terminator
sWeedlePose121:
ax_pose 28, 0x81ee, 0x80f6, 0x4c00
ax_pose_terminator
sWeedlePose122:
ax_pose 0, 0x81eb, 0x80f8, 0x4c00
ax_pose_terminator
sWeedlePose123:
ax_pose 1, 0x81eb, 0x80f8, 0x4c00
ax_pose_terminator
sWeedlePose124:
ax_pose 2, 0x81eb, 0x80f8, 0x4c00
ax_pose_terminator
sWeedlePose125:
ax_pose 15, 0x81ed, 0x80f8, 0x4c00
ax_pose_terminator
sWeedlePose126:
ax_pose 16, 0x81ed, 0x80f8, 0x4c00
ax_pose 15, 0x81ec, 0x80f8, 0x4c08
ax_pose_terminator
sWeedlePose127:
ax_pose 3, 0x01eb, 0x90ef, 0x4c00
ax_pose_terminator
sWeedlePose128:
ax_pose 4, 0x01eb, 0x90ef, 0x4c00
ax_pose_terminator
sWeedlePose129:
ax_pose 5, 0x01eb, 0x90ef, 0x4c00
ax_pose_terminator
sWeedlePose130:
ax_pose 17, 0x41f5, 0x90ef, 0x4c00
ax_pose_terminator
sWeedlePose131:
ax_pose 21, 0x01eb, 0x90f0, 0x4c00
ax_pose 17, 0x41f5, 0x90ef, 0x4c10
ax_pose_terminator
sWeedlePose132:
ax_pose 6, 0x01ea, 0x90ed, 0x4c00
ax_pose_terminator
sWeedlePose133:
ax_pose 7, 0x01ea, 0x90ed, 0x4c00
ax_pose_terminator
sWeedlePose134:
ax_pose 8, 0x01ea, 0x90ed, 0x4c00
ax_pose_terminator
sWeedlePose135:
ax_pose 18, 0x41f2, 0x90ee, 0x4c00
ax_pose_terminator
sWeedlePose136:
ax_pose 22, 0x01ea, 0x90f0, 0x4c00
ax_pose 18, 0x41f2, 0x90ee, 0x4c10
ax_pose_terminator
sWeedlePose137:
ax_pose 9, 0x01ea, 0x90ef, 0x4c00
ax_pose_terminator
sWeedlePose138:
ax_pose 10, 0x01ea, 0x90ef, 0x4c00
ax_pose_terminator
sWeedlePose139:
ax_pose 11, 0x01ea, 0x90ef, 0x4c00
ax_pose_terminator
sWeedlePose140:
ax_pose 19, 0x01ef, 0x90ef, 0x4c00
ax_pose_terminator
sWeedlePose141:
ax_pose 23, 0x01ef, 0x90f0, 0x4c00
ax_pose 19, 0x01ef, 0x90ef, 0x4c10
ax_pose_terminator
sWeedlePose142:
ax_pose 12, 0x81ea, 0x80f8, 0x4c00
ax_pose_terminator
sWeedlePose143:
ax_pose 13, 0x81ea, 0x80f8, 0x4c00
ax_pose_terminator
sWeedlePose144:
ax_pose 14, 0x81ea, 0x80f8, 0x4c00
ax_pose_terminator
sWeedlePose145:
ax_pose 20, 0x81ee, 0x80f8, 0x4c00
ax_pose_terminator
sWeedlePose146:
ax_pose 24, 0x81ed, 0x80f8, 0x4c00
ax_pose 20, 0x81ee, 0x80f8, 0x4c08
ax_pose_terminator
sWeedlePose147:
ax_pose 9, 0x01ea, 0x80f0, 0x4c00
ax_pose_terminator
sWeedlePose148:
ax_pose 10, 0x01ea, 0x80f0, 0x4c00
ax_pose_terminator
sWeedlePose149:
ax_pose 11, 0x01ea, 0x80f0, 0x4c00
ax_pose_terminator
sWeedlePose150:
ax_pose 19, 0x01ef, 0x80f0, 0x4c00
ax_pose_terminator
sWeedlePose151:
ax_pose 23, 0x01ef, 0x80ef, 0x4c00
ax_pose 19, 0x01ef, 0x80f0, 0x4c10
ax_pose_terminator
sWeedlePose152:
ax_pose 6, 0x01ea, 0x80f2, 0x4c00
ax_pose_terminator
sWeedlePose153:
ax_pose 7, 0x01ea, 0x80f2, 0x4c00
ax_pose_terminator
sWeedlePose154:
ax_pose 8, 0x01ea, 0x80f2, 0x4c00
ax_pose_terminator
sWeedlePose155:
ax_pose 18, 0x41f2, 0x80f1, 0x4c00
ax_pose_terminator
sWeedlePose156:
ax_pose 22, 0x01ea, 0x80ef, 0x4c00
ax_pose 18, 0x41f2, 0x80f1, 0x4c10
ax_pose_terminator
sWeedlePose157:
ax_pose 3, 0x01eb, 0x80f0, 0x4c00
ax_pose_terminator
sWeedlePose158:
ax_pose 4, 0x01eb, 0x80f0, 0x4c00
ax_pose_terminator
sWeedlePose159:
ax_pose 5, 0x01eb, 0x80f0, 0x4c00
ax_pose_terminator
sWeedlePose160:
ax_pose 17, 0x41f5, 0x80f0, 0x4c00
ax_pose_terminator
sWeedlePose161:
ax_pose 21, 0x01eb, 0x80ef, 0x4c00
ax_pose 17, 0x41f5, 0x80f0, 0x4c10
ax_pose_terminator
sWeedlePose162:
ax_pose 35, 0x81eb, 0x80f7, 0x4c00
ax_pose_terminator
sWeedlePose163:
ax_pose 36, 0x81eb, 0x80f7, 0x4c00
ax_pose_terminator
sWeedlePose164:
ax_pose 37, 0x01e1, 0x80f1, 0x4c00
ax_pose_terminator
sWeedlePose165:
ax_pose 38, 0x01e2, 0x90ea, 0x4c00
ax_pose_terminator
sWeedlePose166:
ax_pose 39, 0x01e2, 0x90e9, 0x4c00
ax_pose_terminator
sWeedlePose167:
ax_pose 40, 0x01e5, 0x90ea, 0x4c00
ax_pose_terminator
sWeedlePose168:
ax_pose 41, 0x01e6, 0x80f1, 0x4c00
ax_pose_terminator
sWeedlePose169:
ax_pose 40, 0x01e5, 0x80f6, 0x4c00
ax_pose_terminator
sWeedlePose170:
ax_pose 39, 0x01e2, 0x80f7, 0x4c00
ax_pose_terminator
sWeedlePose171:
ax_pose 38, 0x01e2, 0x80f6, 0x4c00
ax_pose_terminator
sWeedlePose172:
ax_pose 0, 0x81eb, 0x80f8, 0x4c00
ax_pose_terminator
sWeedlePose173:
ax_pose 1, 0x81eb, 0x80f8, 0x4c00
ax_pose_terminator
sWeedlePose174:
ax_pose 2, 0x81eb, 0x80f8, 0x4c00
ax_pose_terminator
sWeedlePose175:
ax_pose 3, 0x01eb, 0x90ef, 0x4c00
ax_pose_terminator
sWeedlePose176:
ax_pose 4, 0x01eb, 0x90ef, 0x4c00
ax_pose_terminator
sWeedlePose177:
ax_pose 5, 0x01eb, 0x90ef, 0x4c00
ax_pose_terminator
sWeedlePose178:
ax_pose 6, 0x01ea, 0x90ed, 0x4c00
ax_pose_terminator
sWeedlePose179:
ax_pose 7, 0x01ea, 0x90ed, 0x4c00
ax_pose_terminator
sWeedlePose180:
ax_pose 8, 0x01ea, 0x90ed, 0x4c00
ax_pose_terminator
sWeedlePose181:
ax_pose 9, 0x01ea, 0x90ef, 0x4c00
ax_pose_terminator
sWeedlePose182:
ax_pose 10, 0x01ea, 0x90ef, 0x4c00
ax_pose_terminator
sWeedlePose183:
ax_pose 11, 0x01ea, 0x90ef, 0x4c00
ax_pose_terminator
sWeedlePose184:
ax_pose 12, 0x81ea, 0x80f8, 0x4c00
ax_pose_terminator
sWeedlePose185:
ax_pose 13, 0x81ea, 0x80f8, 0x4c00
ax_pose_terminator
sWeedlePose186:
ax_pose 14, 0x81ea, 0x80f8, 0x4c00
ax_pose_terminator
sWeedlePose187:
ax_pose 9, 0x01ea, 0x80f0, 0x4c00
ax_pose_terminator
sWeedlePose188:
ax_pose 10, 0x01ea, 0x80f0, 0x4c00
ax_pose_terminator
sWeedlePose189:
ax_pose 11, 0x01ea, 0x80f0, 0x4c00
ax_pose_terminator
sWeedlePose190:
ax_pose 6, 0x01ea, 0x80f2, 0x4c00
ax_pose_terminator
sWeedlePose191:
ax_pose 7, 0x01ea, 0x80f2, 0x4c00
ax_pose_terminator
sWeedlePose192:
ax_pose 8, 0x01ea, 0x80f2, 0x4c00
ax_pose_terminator
sWeedlePose193:
ax_pose 3, 0x01eb, 0x80f0, 0x4c00
ax_pose_terminator
sWeedlePose194:
ax_pose 4, 0x01eb, 0x80f0, 0x4c00
ax_pose_terminator
sWeedlePose195:
ax_pose 5, 0x01eb, 0x80f0, 0x4c00
ax_pose_terminator
sWeedlePose196:
ax_pose 15, 0x81ee, 0x80f8, 0x4c00
ax_pose_terminator
sWeedlePose197:
ax_pose 17, 0x41f6, 0x80f0, 0x4c00
ax_pose_terminator
sWeedlePose198:
ax_pose 18, 0x41f2, 0x80f1, 0x4c00
ax_pose_terminator
sWeedlePose199:
ax_pose 19, 0x01ee, 0x80f0, 0x4c00
ax_pose_terminator
sWeedlePose200:
ax_pose 20, 0x81ee, 0x80f8, 0x4c00
ax_pose_terminator
sWeedlePose201:
ax_pose 19, 0x01ee, 0x90ef, 0x4c00
ax_pose_terminator
sWeedlePose202:
ax_pose 18, 0x41f2, 0x90ee, 0x4c00
ax_pose_terminator
sWeedlePose203:
ax_pose 17, 0x41f6, 0x90ef, 0x4c00
ax_pose_terminator
sWeedlePose204:
ax_pose 25, 0x81eb, 0x80f7, 0x4c00
ax_pose_terminator
sWeedlePose205:
ax_pose 27, 0x81ee, 0x90fb, 0x4c00
ax_pose_terminator
sWeedlePose206:
ax_pose 29, 0x81ec, 0x90f9, 0x4c00
ax_pose_terminator
sWeedlePose207:
ax_pose 31, 0x01eb, 0x90ea, 0x4c00
ax_pose_terminator
sWeedlePose208:
ax_pose 33, 0x81ed, 0x80f8, 0x4c00
ax_pose_terminator
sWeedlePose209:
ax_pose 31, 0x01eb, 0x80f5, 0x4c00
ax_pose_terminator
sWeedlePose210:
ax_pose 29, 0x81ec, 0x80f6, 0x4c00
ax_pose_terminator
sWeedlePose211:
ax_pose 27, 0x81ee, 0x80f6, 0x4c00
ax_pose_terminator
sWeedlePose212:
ax_pose 1, 0x81eb, 0x80f8, 0x4c00
ax_pose_terminator
sWeedlePose213:
ax_pose 0, 0x81eb, 0x80f8, 0x4c00
ax_pose_terminator
sWeedlePose214:
ax_pose 15, 0x81ed, 0x80f8, 0x4c00
ax_pose_terminator
sWeedlePose215:
ax_pose 4, 0x01eb, 0x90ef, 0x4c00
ax_pose_terminator
sWeedlePose216:
ax_pose 3, 0x01eb, 0x90ef, 0x4c00
ax_pose_terminator
sWeedlePose217:
ax_pose 17, 0x41f5, 0x90ef, 0x4c00
ax_pose_terminator
sWeedlePose218:
ax_pose 7, 0x01ea, 0x90ed, 0x4c00
ax_pose_terminator
sWeedlePose219:
ax_pose 6, 0x01ea, 0x90ed, 0x4c00
ax_pose_terminator
sWeedlePose220:
ax_pose 18, 0x41f2, 0x90ee, 0x4c00
ax_pose_terminator
sWeedlePose221:
ax_pose 10, 0x01ea, 0x90ef, 0x4c00
ax_pose_terminator
sWeedlePose222:
ax_pose 9, 0x01ea, 0x90ef, 0x4c00
ax_pose_terminator
sWeedlePose223:
ax_pose 19, 0x01ef, 0x90ef, 0x4c00
ax_pose_terminator
sWeedlePose224:
ax_pose 13, 0x81ea, 0x80f8, 0x4c00
ax_pose_terminator
sWeedlePose225:
ax_pose 12, 0x81ea, 0x80f8, 0x4c00
ax_pose_terminator
sWeedlePose226:
ax_pose 20, 0x81ee, 0x80f8, 0x4c00
ax_pose_terminator
sWeedlePose227:
ax_pose 10, 0x01ea, 0x80f0, 0x4c00
ax_pose_terminator
sWeedlePose228:
ax_pose 9, 0x01ea, 0x80f0, 0x4c00
ax_pose_terminator
sWeedlePose229:
ax_pose 19, 0x01ef, 0x80f0, 0x4c00
ax_pose_terminator
sWeedlePose230:
ax_pose 7, 0x01ea, 0x80f2, 0x4c00
ax_pose_terminator
sWeedlePose231:
ax_pose 6, 0x01ea, 0x80f2, 0x4c00
ax_pose_terminator
sWeedlePose232:
ax_pose 18, 0x41f2, 0x80f1, 0x4c00
ax_pose_terminator
sWeedlePose233:
ax_pose 4, 0x01eb, 0x80f0, 0x4c00
ax_pose_terminator
sWeedlePose234:
ax_pose 3, 0x01eb, 0x80f0, 0x4c00
ax_pose_terminator
sWeedlePose235:
ax_pose 17, 0x41f5, 0x80f0, 0x4c00
ax_pose_terminator
sWeedlePose236:
ax_pose 1, 0x81eb, 0x80f8, 0x4c00
ax_pose_terminator
sWeedlePose237:
ax_pose 4, 0x01ec, 0x80f0, 0x4c00
ax_pose_terminator
sWeedlePose238:
ax_pose 7, 0x01eb, 0x80f4, 0x4c00
ax_pose_terminator
sWeedlePose239:
ax_pose 10, 0x01eb, 0x80f2, 0x4c00
ax_pose_terminator
sWeedlePose240:
ax_pose 13, 0x81eb, 0x80f8, 0x4c00
ax_pose_terminator
sWeedlePose241:
ax_pose 10, 0x01eb, 0x90ed, 0x4c00
ax_pose_terminator
sWeedlePose242:
ax_pose 7, 0x01eb, 0x90eb, 0x4c00
ax_pose_terminator
sWeedlePose243:
ax_pose 4, 0x01ec, 0x90ef, 0x4c00
ax_pose_terminator
sWeedlePose244:
ax_pose 0, 0x81eb, 0x80f8, 0x4c00
ax_pose_terminator
sWeedlePose245:
ax_pose 3, 0x01eb, 0x80f0, 0x4c00
ax_pose_terminator
sWeedlePose246:
ax_pose 6, 0x01ea, 0x80f2, 0x4c00
ax_pose_terminator
sWeedlePose247:
ax_pose 9, 0x01ea, 0x80f0, 0x4c00
ax_pose_terminator
sWeedlePose248:
ax_pose 12, 0x81ea, 0x80f8, 0x4c00
ax_pose_terminator
sWeedlePose249:
ax_pose 9, 0x01ea, 0x90ef, 0x4c00
ax_pose_terminator
sWeedlePose250:
ax_pose 6, 0x01ea, 0x90ed, 0x4c00
ax_pose_terminator
sWeedlePose251:
ax_pose 3, 0x01eb, 0x90ef, 0x4c00
ax_pose_terminator
.align 2
sWeedleAnims_1_1:
ax_anim 8, 0, 2, 0, 0, 0, 0,
ax_anim 10, 0, 0, 0, 0, 0, 0,
ax_anim 8, 0, 1, 0, 0, 0, 0,
ax_anim_terminator
sWeedleAnims_1_2:
ax_anim 8, 0, 5, 0, 0, 0, 0,
ax_anim 10, 0, 3, 0, 0, 0, 0,
ax_anim 8, 0, 4, 0, 0, 0, 0,
ax_anim_terminator
sWeedleAnims_1_3:
ax_anim 8, 0, 8, 0, 0, 0, 0,
ax_anim 10, 0, 6, 0, 0, 0, 0,
ax_anim 8, 0, 7, 0, 0, 0, 0,
ax_anim_terminator
sWeedleAnims_1_4:
ax_anim 8, 0, 11, 0, 0, 0, 0,
ax_anim 10, 0, 9, 0, 0, 0, 0,
ax_anim 8, 0, 10, 0, 0, 0, 0,
ax_anim_terminator
sWeedleAnims_1_5:
ax_anim 8, 0, 14, 0, 0, 0, 0,
ax_anim 10, 0, 12, 0, 0, 0, 0,
ax_anim 8, 0, 13, 0, 0, 0, 0,
ax_anim_terminator
sWeedleAnims_1_6:
ax_anim 8, 0, 17, 0, 0, 0, 0,
ax_anim 10, 0, 15, 0, 0, 0, 0,
ax_anim 8, 0, 16, 0, 0, 0, 0,
ax_anim_terminator
sWeedleAnims_1_7:
ax_anim 8, 0, 20, 0, 0, 0, 0,
ax_anim 10, 0, 18, 0, 0, 0, 0,
ax_anim 8, 0, 19, 0, 0, 0, 0,
ax_anim_terminator
sWeedleAnims_1_8:
ax_anim 8, 0, 23, 0, 0, 0, 0,
ax_anim 10, 0, 21, 0, 0, 0, 0,
ax_anim 8, 0, 22, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sWeedleAnims_2_1:
ax_anim 4, 0, 24, 0, 0, 0, 0,
ax_anim 2, 0, 24, 0, -1, 0, -1,
ax_anim 4, 0, 24, 0, -2, 0, -2,
ax_anim 2, 0, 25, 0, 0, 0, 0,
ax_anim 2, 0, 27, 0, 4, 0, 1,
ax_anim 2, 2, 27, 0, 10, 0, 7,
ax_anim 2, 0, 27, 0, 18, 0, 15,
ax_anim 2, 1, 27, 1, 18, 1, 15,
ax_anim 2, 0, 27, 0, 18, 0, 15,
ax_anim 2, 0, 27, 1, 18, 1, 15,
ax_anim 4, 0, 26, 0, 6, 0, 6,
ax_anim_terminator
sWeedleAnims_2_2:
ax_anim 4, 0, 29, 0, 0, 0, 0,
ax_anim 2, 0, 29, -1, -1, -1, -1,
ax_anim 4, 0, 29, -2, -2, -2, -2,
ax_anim 2, 0, 30, 0, -1, 0, 0,
ax_anim 2, 0, 32, 4, 4, 4, 4,
ax_anim 2, 2, 32, 10, 10, 10, 10,
ax_anim 2, 0, 32, 18, 18, 18, 18,
ax_anim 2, 1, 32, 19, 17, 19, 17,
ax_anim 2, 0, 32, 18, 18, 18, 18,
ax_anim 2, 0, 32, 19, 17, 19, 17,
ax_anim 4, 0, 29, 8, 8, 6, 6,
ax_anim_terminator
sWeedleAnims_2_3:
ax_anim 4, 0, 33, 0, 0, 0, 0,
ax_anim 2, 0, 33, -1, 0, -1, 0,
ax_anim 4, 0, 33, -2, 0, -2, 0,
ax_anim 2, 0, 34, 0, 0, 0, 0,
ax_anim 2, 0, 36, 4, 0, 4, 0,
ax_anim 2, 2, 36, 10, 0, 10, 0,
ax_anim 2, 0, 36, 18, 0, 18, 0,
ax_anim 2, 1, 36, 18, 1, 18, 1,
ax_anim 2, 0, 36, 18, 0, 18, 0,
ax_anim 2, 0, 36, 18, 1, 18, 1,
ax_anim 4, 0, 33, 6, 0, 6, 0,
ax_anim_terminator
sWeedleAnims_2_4:
ax_anim 4, 0, 37, 0, 0, 0, 0,
ax_anim 2, 0, 37, -1, 1, -1, 1,
ax_anim 4, 0, 37, -2, 2, -2, 2,
ax_anim 2, 0, 38, 0, -1, 0, -1,
ax_anim 2, 0, 40, 4, -4, 4, -4,
ax_anim 2, 2, 40, 10, -10, 10, -10,
ax_anim 2, 0, 40, 18, -18, 18, -18,
ax_anim 2, 1, 40, 19, -17, 19, -17,
ax_anim 2, 0, 40, 18, -18, 18, -18,
ax_anim 2, 0, 40, 19, -17, 19, -17,
ax_anim 4, 0, 37, 6, -6, 6, -6,
ax_anim_terminator
sWeedleAnims_2_5:
ax_anim 4, 0, 41, 0, 0, 0, 0,
ax_anim 2, 0, 41, 0, 1, 0, 1,
ax_anim 4, 0, 41, 0, 2, 0, 2,
ax_anim 2, 0, 42, 0, 0, 0, 0,
ax_anim 2, 0, 44, 0, -4, 0, -4,
ax_anim 2, 2, 44, 0, -10, 0, -10,
ax_anim 2, 0, 44, 0, -18, 0, -18,
ax_anim 2, 1, 44, 1, -18, 1, -18,
ax_anim 2, 0, 44, 0, -18, 0, -18,
ax_anim 2, 0, 44, 1, -18, 1, -18,
ax_anim 4, 0, 41, 0, -6, 0, -6,
ax_anim_terminator
sWeedleAnims_2_6:
ax_anim 4, 0, 45, 0, 0, 0, 0,
ax_anim 2, 0, 45, 1, 1, 1, 1,
ax_anim 4, 0, 45, 2, 2, 2, 2,
ax_anim 2, 0, 46, 0, 0, 0, -1,
ax_anim 2, 0, 48, -4, -4, -4, -4,
ax_anim 2, 2, 48, -10, -10, -10, -10,
ax_anim 2, 0, 48, -18, -18, -18, -18,
ax_anim 2, 1, 48, -19, -17, -19, -17,
ax_anim 2, 0, 48, -18, -18, -18, -18,
ax_anim 2, 0, 48, -19, -17, -19, -17,
ax_anim 4, 0, 45, -6, -6, -6, -6,
ax_anim_terminator
sWeedleAnims_2_7:
ax_anim 4, 0, 49, 0, 0, 0, 0,
ax_anim 2, 0, 49, 1, 0, 1, 0,
ax_anim 4, 0, 49, 2, 0, 2, 0,
ax_anim 2, 0, 50, 0, 0, 0, 0,
ax_anim 2, 0, 52, -4, 0, -4, 0,
ax_anim 2, 2, 52, -10, 0, -10, 0,
ax_anim 2, 0, 52, -18, 0, -18, 0,
ax_anim 2, 1, 52, -18, 1, -18, 1,
ax_anim 2, 0, 52, -18, 0, -18, 0,
ax_anim 2, 0, 52, -18, 1, -18, 1,
ax_anim 4, 0, 49, -6, 0, -6, 0,
ax_anim_terminator
sWeedleAnims_2_8:
ax_anim 4, 0, 53, 0, 0, 0, 0,
ax_anim 2, 0, 53, 1, -1, 1, -1,
ax_anim 4, 0, 53, 2, -2, 2, -2,
ax_anim 2, 0, 54, 0, 0, 0, 0,
ax_anim 2, 0, 56, -4, 4, -4, 4,
ax_anim 2, 2, 56, -10, 10, -10, 10,
ax_anim 2, 0, 56, -17, 19, -17, 19,
ax_anim 2, 1, 56, -18, 18, -18, 18,
ax_anim 2, 0, 56, -17, 19, -17, 19,
ax_anim 2, 0, 56, -17, 19, -17, 19,
ax_anim 4, 0, 53, -6, 6, -6, 6,
ax_anim_terminator
.align 2
sWeedleAnims_3_1:
ax_anim 4, 0, 57, 0, 0, 0, 0,
ax_anim 2, 0, 57, 0, -1, 0, -1,
ax_anim 4, 0, 57, 0, -2, 0, -2,
ax_anim 2, 0, 58, 0, 0, 0, 0,
ax_anim 2, 0, 60, 0, 4, 0, 1,
ax_anim 2, 2, 61, 0, 10, 0, 7,
ax_anim 2, 0, 60, 0, 18, 0, 15,
ax_anim 2, 1, 61, 1, 18, 1, 15,
ax_anim 2, 0, 60, 0, 18, 0, 15,
ax_anim 2, 0, 60, 1, 18, 1, 15,
ax_anim 4, 0, 59, 0, 6, 0, 6,
ax_anim_terminator
sWeedleAnims_3_2:
ax_anim 4, 0, 62, 0, 0, 0, 0,
ax_anim 2, 0, 62, -1, -1, -1, -1,
ax_anim 4, 0, 62, -2, -2, -2, -2,
ax_anim 2, 0, 63, 0, -1, 0, 0,
ax_anim 2, 0, 65, 4, 4, 4, 4,
ax_anim 2, 2, 66, 10, 10, 10, 10,
ax_anim 2, 0, 65, 18, 18, 18, 18,
ax_anim 2, 1, 66, 19, 17, 19, 17,
ax_anim 2, 0, 65, 18, 18, 18, 18,
ax_anim 2, 0, 65, 19, 17, 19, 17,
ax_anim 4, 0, 62, 8, 8, 6, 6,
ax_anim_terminator
sWeedleAnims_3_3:
ax_anim 4, 0, 67, 0, 0, 0, 0,
ax_anim 2, 0, 67, -1, 0, -1, 0,
ax_anim 4, 0, 67, -2, 0, -2, 0,
ax_anim 2, 0, 68, 0, 0, 0, 0,
ax_anim 2, 0, 70, 4, 0, 4, 0,
ax_anim 2, 2, 71, 10, 0, 10, 0,
ax_anim 2, 0, 70, 18, 0, 18, 0,
ax_anim 2, 1, 71, 18, 1, 18, 1,
ax_anim 2, 0, 70, 18, 0, 18, 0,
ax_anim 2, 0, 70, 18, 1, 18, 1,
ax_anim 4, 0, 67, 6, 0, 6, 0,
ax_anim_terminator
sWeedleAnims_3_4:
ax_anim 4, 0, 72, 0, 0, 0, 0,
ax_anim 2, 0, 72, -1, 1, -1, 1,
ax_anim 4, 0, 72, -2, 2, -2, 2,
ax_anim 2, 0, 73, 0, -1, 0, -1,
ax_anim 2, 0, 75, 4, -4, 4, -4,
ax_anim 2, 2, 76, 10, -10, 10, -10,
ax_anim 2, 0, 75, 18, -18, 18, -18,
ax_anim 2, 1, 76, 19, -17, 19, -17,
ax_anim 2, 0, 75, 18, -18, 18, -18,
ax_anim 2, 0, 75, 19, -17, 19, -17,
ax_anim 4, 0, 72, 6, -6, 6, -6,
ax_anim_terminator
sWeedleAnims_3_5:
ax_anim 4, 0, 77, 0, 0, 0, 0,
ax_anim 2, 0, 77, 0, 1, 0, 1,
ax_anim 4, 0, 77, 0, 2, 0, 2,
ax_anim 2, 0, 78, 0, 0, 0, 0,
ax_anim 2, 0, 80, 0, -4, 0, -4,
ax_anim 2, 2, 81, 0, -10, 0, -10,
ax_anim 2, 0, 80, 0, -18, 0, -18,
ax_anim 2, 1, 81, 1, -18, 1, -18,
ax_anim 2, 0, 80, 0, -18, 0, -18,
ax_anim 2, 0, 80, 1, -18, 1, -18,
ax_anim 4, 0, 77, 0, -6, 0, -6,
ax_anim_terminator
sWeedleAnims_3_6:
ax_anim 4, 0, 82, 0, 0, 0, 0,
ax_anim 2, 0, 82, 1, 1, 1, 1,
ax_anim 4, 0, 82, 2, 2, 2, 2,
ax_anim 2, 0, 83, 0, 0, 0, -1,
ax_anim 2, 0, 85, -4, -4, -4, -4,
ax_anim 2, 2, 86, -10, -10, -10, -10,
ax_anim 2, 0, 85, -18, -18, -18, -18,
ax_anim 2, 1, 86, -19, -17, -19, -17,
ax_anim 2, 0, 85, -18, -18, -18, -18,
ax_anim 2, 0, 85, -19, -17, -19, -17,
ax_anim 4, 0, 82, -6, -6, -6, -6,
ax_anim_terminator
sWeedleAnims_3_7:
ax_anim 4, 0, 87, 0, 0, 0, 0,
ax_anim 2, 0, 87, 1, 0, 1, 0,
ax_anim 4, 0, 87, 2, 0, 2, 0,
ax_anim 2, 0, 88, 0, 0, 0, 0,
ax_anim 2, 0, 90, -4, 0, -4, 0,
ax_anim 2, 2, 91, -10, 0, -10, 0,
ax_anim 2, 0, 90, -18, 0, -18, 0,
ax_anim 2, 1, 91, -18, 1, -18, 1,
ax_anim 2, 0, 90, -18, 0, -18, 0,
ax_anim 2, 0, 90, -18, 1, -18, 1,
ax_anim 4, 0, 87, -6, 0, -6, 0,
ax_anim_terminator
sWeedleAnims_3_8:
ax_anim 4, 0, 92, 0, 0, 0, 0,
ax_anim 2, 0, 92, 1, -1, 1, -1,
ax_anim 4, 0, 92, 2, -2, 2, -2,
ax_anim 2, 0, 93, 0, 0, 0, 0,
ax_anim 2, 0, 95, -4, 4, -4, 4,
ax_anim 2, 2, 96, -10, 10, -10, 10,
ax_anim 2, 0, 95, -17, 19, -17, 19,
ax_anim 2, 1, 96, -18, 18, -18, 18,
ax_anim 2, 0, 95, -17, 19, -17, 19,
ax_anim 2, 0, 95, -17, 19, -17, 19,
ax_anim 4, 0, 92, -6, 6, -6, 6,
ax_anim_terminator
.align 2
sWeedleAnims_4_1:
ax_anim 2, 0, 97, 0, 0, 0, 0,
ax_anim 2, 0, 97, 0, -1, 0, -1,
ax_anim 4, 0, 97, 0, -2, 0, -2,
ax_anim 4, 2, 98, 0, -2, 0, -2,
ax_anim 2, 0, 99, 0, -2, 0, -2,
ax_anim 2, 0, 99, 0, 0, 0, 0,
ax_anim 2, 1, 99, 0, 2, 0, 1,
ax_anim 2, 0, 99, 1, 2, 1, 1,
ax_anim 2, 0, 99, 0, 2, 0, 1,
ax_anim 2, 0, 99, 1, 2, 1, 1,
ax_anim 2, 0, 99, 0, 2, 0, 1,
ax_anim 2, 0, 99, 1, 2, 1, 1,
ax_anim 4, 0, 97, 0, 2, 0, 0,
ax_anim_terminator
sWeedleAnims_4_2:
ax_anim 2, 0, 100, 0, 0, 0, 0,
ax_anim 2, 0, 100, -1, -1, -1, -1,
ax_anim 4, 0, 100, -2, -2, -2, -2,
ax_anim 4, 2, 101, -2, -2, -2, -2,
ax_anim 2, 0, 102, -2, -2, -2, -2,
ax_anim 2, 0, 102, 0, 0, 0, 0,
ax_anim 2, 1, 102, 2, 2, 2, 2,
ax_anim 2, 0, 102, 1, 3, 1, 3,
ax_anim 2, 0, 102, 2, 2, 2, 2,
ax_anim 2, 0, 102, 1, 3, 1, 3,
ax_anim 2, 0, 102, 2, 2, 2, 2,
ax_anim 2, 0, 102, 1, 3, 1, 3,
ax_anim 4, 0, 100, 2, 2, 2, 2,
ax_anim_terminator
sWeedleAnims_4_3:
ax_anim 2, 0, 103, 0, 0, 0, 0,
ax_anim 2, 0, 103, -1, 0, -1, 0,
ax_anim 4, 0, 103, -2, 0, -2, 0,
ax_anim 4, 2, 104, -2, 0, -2, 0,
ax_anim 2, 0, 105, -2, 0, -2, 0,
ax_anim 2, 0, 105, 0, 0, 0, 0,
ax_anim 2, 1, 105, 2, 0, 2, 0,
ax_anim 2, 0, 105, 1, 0, 1, 0,
ax_anim 2, 0, 105, 2, 0, 2, 0,
ax_anim 2, 0, 105, 1, 0, 1, 0,
ax_anim 2, 0, 105, 2, 0, 2, 0,
ax_anim 2, 0, 105, 1, 0, 1, 0,
ax_anim 4, 0, 103, 2, 0, 2, 0,
ax_anim_terminator
sWeedleAnims_4_4:
ax_anim 2, 0, 106, 0, 0, 0, 0,
ax_anim 2, 0, 106, -1, 1, -1, 1,
ax_anim 4, 0, 106, -2, 2, -2, 2,
ax_anim 4, 2, 107, -2, 2, -2, 2,
ax_anim 2, 0, 108, -2, 2, -2, 2,
ax_anim 2, 0, 108, 0, 0, 0, 0,
ax_anim 2, 1, 108, 2, -2, 2, -2,
ax_anim 2, 0, 108, 1, -3, 1, -3,
ax_anim 2, 0, 108, 2, -2, 2, -2,
ax_anim 2, 0, 108, 1, -3, 1, -3,
ax_anim 2, 0, 108, 2, -2, 2, -2,
ax_anim 2, 0, 108, 1, -3, 1, -3,
ax_anim 4, 0, 106, 2, -2, 2, -2,
ax_anim_terminator
sWeedleAnims_4_5:
ax_anim 2, 0, 109, 0, 0, 0, 0,
ax_anim 2, 0, 109, 0, 1, 0, 1,
ax_anim 4, 0, 109, 0, 2, 0, 2,
ax_anim 4, 2, 110, 0, 2, 0, 2,
ax_anim 2, 0, 111, 0, 2, 0, 2,
ax_anim 2, 0, 111, 0, 0, 0, 0,
ax_anim 2, 1, 111, 0, -2, 0, -2,
ax_anim 2, 0, 111, 1, -2, 1, -2,
ax_anim 2, 0, 111, 0, -2, 0, -2,
ax_anim 2, 0, 111, 1, -2, 1, -2,
ax_anim 2, 0, 111, 0, -2, 0, -2,
ax_anim 2, 0, 111, 1, -2, 1, -2,
ax_anim 4, 0, 109, 0, -1, 0, -1,
ax_anim_terminator
sWeedleAnims_4_6:
ax_anim 2, 0, 112, 0, 0, 0, 0,
ax_anim 2, 0, 112, 1, 1, 1, 1,
ax_anim 4, 0, 112, 2, 2, 2, 2,
ax_anim 4, 2, 113, 2, 2, 2, 2,
ax_anim 2, 0, 114, 2, 2, 2, 2,
ax_anim 2, 0, 114, 0, 0, 0, 0,
ax_anim 2, 1, 114, -2, -2, -2, -2,
ax_anim 2, 0, 114, -1, -3, -1, -3,
ax_anim 2, 0, 114, -2, -2, -2, -2,
ax_anim 2, 0, 114, -1, -3, -1, -3,
ax_anim 2, 0, 114, -2, -2, -2, -2,
ax_anim 2, 0, 114, -1, -3, -1, -3,
ax_anim 4, 0, 112, -2, -2, -2, -2,
ax_anim_terminator
sWeedleAnims_4_7:
ax_anim 2, 0, 115, 0, 0, 0, 0,
ax_anim 2, 0, 115, 1, 0, 1, 0,
ax_anim 4, 0, 115, 2, 0, 2, 0,
ax_anim 4, 2, 116, 2, 0, 2, 0,
ax_anim 2, 0, 117, 2, 0, 2, 0,
ax_anim 2, 0, 117, 0, 0, 0, 0,
ax_anim 2, 1, 117, -2, 0, -2, 0,
ax_anim 2, 0, 117, -1, 0, -1, 0,
ax_anim 2, 0, 117, -2, 0, -2, 0,
ax_anim 2, 0, 117, -1, 0, -1, 0,
ax_anim 2, 0, 117, -2, 0, -2, 0,
ax_anim 2, 0, 117, -1, 0, -1, 0,
ax_anim 4, 0, 115, -2, 0, -2, 0,
ax_anim_terminator
sWeedleAnims_4_8:
ax_anim 2, 0, 118, 0, 0, 0, 0,
ax_anim 2, 0, 118, 1, -1, 1, -1,
ax_anim 4, 0, 118, 2, -2, 2, -2,
ax_anim 4, 2, 119, 2, -2, 2, -2,
ax_anim 2, 0, 120, 2, -2, 2, -2,
ax_anim 2, 0, 120, 0, 0, 0, 0,
ax_anim 2, 1, 120, -2, 2, -2, 2,
ax_anim 2, 0, 120, -1, 3, -1, 3,
ax_anim 2, 0, 120, -2, 2, -2, 2,
ax_anim 2, 0, 120, -1, 3, -1, 3,
ax_anim 2, 0, 120, -2, 2, -2, 2,
ax_anim 2, 0, 120, -1, 3, -1, 3,
ax_anim 4, 0, 118, -2, 2, -2, 2,
ax_anim_terminator
.align 2
sWeedleAnims_5_1:
ax_anim 4, 0, 121, 0, 0, 0, 0,
ax_anim 2, 0, 121, 0, -1, 0, -1,
ax_anim 4, 0, 121, 0, -2, 0, -2,
ax_anim 2, 0, 122, 0, 0, 0, 0,
ax_anim 2, 0, 124, 0, 4, 0, 1,
ax_anim 2, 2, 125, 0, 10, 0, 7,
ax_anim 2, 0, 124, 0, 18, 0, 15,
ax_anim 2, 1, 125, 1, 18, 1, 15,
ax_anim 2, 0, 124, 0, 18, 0, 15,
ax_anim 2, 0, 124, 1, 18, 1, 15,
ax_anim 4, 0, 123, 0, 6, 0, 6,
ax_anim_terminator
sWeedleAnims_5_2:
ax_anim 4, 0, 126, 0, 0, 0, 0,
ax_anim 2, 0, 126, -1, -1, -1, -1,
ax_anim 4, 0, 126, -2, -2, -2, -2,
ax_anim 2, 0, 127, 0, -1, 0, 0,
ax_anim 2, 0, 129, 4, 4, 4, 4,
ax_anim 2, 2, 130, 10, 10, 10, 10,
ax_anim 2, 0, 129, 18, 18, 18, 18,
ax_anim 2, 1, 130, 19, 17, 19, 17,
ax_anim 2, 0, 129, 18, 18, 18, 18,
ax_anim 2, 0, 129, 19, 17, 19, 17,
ax_anim 4, 0, 126, 8, 8, 6, 6,
ax_anim_terminator
sWeedleAnims_5_3:
ax_anim 4, 0, 131, 0, 0, 0, 0,
ax_anim 2, 0, 131, -1, 0, -1, 0,
ax_anim 4, 0, 131, -2, 0, -2, 0,
ax_anim 2, 0, 132, 0, 0, 0, 0,
ax_anim 2, 0, 134, 4, 0, 4, 0,
ax_anim 2, 2, 135, 10, 0, 10, 0,
ax_anim 2, 0, 134, 18, 0, 18, 0,
ax_anim 2, 1, 135, 18, 1, 18, 1,
ax_anim 2, 0, 134, 18, 0, 18, 0,
ax_anim 2, 0, 134, 18, 1, 18, 1,
ax_anim 4, 0, 131, 6, 0, 6, 0,
ax_anim_terminator
sWeedleAnims_5_4:
ax_anim 4, 0, 136, 0, 0, 0, 0,
ax_anim 2, 0, 136, -1, 1, -1, 1,
ax_anim 4, 0, 136, -2, 2, -2, 2,
ax_anim 2, 0, 137, 0, -1, 0, -1,
ax_anim 2, 0, 139, 4, -4, 4, -4,
ax_anim 2, 2, 140, 10, -10, 10, -10,
ax_anim 2, 0, 139, 18, -18, 18, -18,
ax_anim 2, 1, 140, 19, -17, 19, -17,
ax_anim 2, 0, 139, 18, -18, 18, -18,
ax_anim 2, 0, 139, 19, -17, 19, -17,
ax_anim 4, 0, 136, 6, -6, 6, -6,
ax_anim_terminator
sWeedleAnims_5_5:
ax_anim 4, 0, 141, 0, 0, 0, 0,
ax_anim 2, 0, 141, 0, 1, 0, 1,
ax_anim 4, 0, 141, 0, 2, 0, 2,
ax_anim 2, 0, 142, 0, 0, 0, 0,
ax_anim 2, 0, 144, 0, -4, 0, -4,
ax_anim 2, 2, 145, 0, -10, 0, -10,
ax_anim 2, 0, 144, 0, -18, 0, -18,
ax_anim 2, 1, 145, 1, -18, 1, -18,
ax_anim 2, 0, 144, 0, -18, 0, -18,
ax_anim 2, 0, 144, 1, -18, 1, -18,
ax_anim 4, 0, 141, 0, -6, 0, -6,
ax_anim_terminator
sWeedleAnims_5_6:
ax_anim 4, 0, 146, 0, 0, 0, 0,
ax_anim 2, 0, 146, 1, 1, 1, 1,
ax_anim 4, 0, 146, 2, 2, 2, 2,
ax_anim 2, 0, 147, 0, 0, 0, -1,
ax_anim 2, 0, 149, -4, -4, -4, -4,
ax_anim 2, 2, 150, -10, -10, -10, -10,
ax_anim 2, 0, 149, -18, -18, -18, -18,
ax_anim 2, 1, 150, -19, -17, -19, -17,
ax_anim 2, 0, 149, -18, -18, -18, -18,
ax_anim 2, 0, 149, -19, -17, -19, -17,
ax_anim 4, 0, 146, -6, -6, -6, -6,
ax_anim_terminator
sWeedleAnims_5_7:
ax_anim 4, 0, 151, 0, 0, 0, 0,
ax_anim 2, 0, 151, 1, 0, 1, 0,
ax_anim 4, 0, 151, 2, 0, 2, 0,
ax_anim 2, 0, 152, 0, 0, 0, 0,
ax_anim 2, 0, 154, -4, 0, -4, 0,
ax_anim 2, 2, 155, -10, 0, -10, 0,
ax_anim 2, 0, 154, -18, 0, -18, 0,
ax_anim 2, 1, 155, -18, 1, -18, 1,
ax_anim 2, 0, 154, -18, 0, -18, 0,
ax_anim 2, 0, 154, -18, 1, -18, 1,
ax_anim 4, 0, 151, -6, 0, -6, 0,
ax_anim_terminator
sWeedleAnims_5_8:
ax_anim 4, 0, 156, 0, 0, 0, 0,
ax_anim 2, 0, 156, 1, -1, 1, -1,
ax_anim 4, 0, 156, 2, -2, 2, -2,
ax_anim 2, 0, 157, 0, 0, 0, 0,
ax_anim 2, 0, 159, -4, 4, -4, 4,
ax_anim 2, 2, 160, -10, 10, -10, 10,
ax_anim 2, 0, 159, -17, 19, -17, 19,
ax_anim 2, 1, 160, -18, 18, -18, 18,
ax_anim 2, 0, 159, -17, 19, -17, 19,
ax_anim 2, 0, 159, -17, 19, -17, 19,
ax_anim 4, 0, 156, -6, 6, -6, 6,
ax_anim_terminator
.align 2
sWeedleAnims_6_1:
ax_anim 30, 0, 161, 0, 0, 0, 0,
ax_anim 35, 0, 162, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sWeedleAnims_7_1:
ax_anim 2, 0, 163, 0, -2, 0, -2,
ax_anim 8, 0, 163, 0, -3, 0, -3,
ax_anim_terminator
sWeedleAnims_7_2:
ax_anim 2, 0, 164, -2, -2, -2, -2,
ax_anim 8, 0, 164, -3, -3, -3, -3,
ax_anim_terminator
sWeedleAnims_7_3:
ax_anim 2, 0, 165, -2, 0, -2, 0,
ax_anim 8, 0, 165, -3, 0, -3, 0,
ax_anim_terminator
sWeedleAnims_7_4:
ax_anim 2, 0, 166, -2, 2, -2, 2,
ax_anim 8, 0, 166, -3, 3, -3, 3,
ax_anim_terminator
sWeedleAnims_7_5:
ax_anim 2, 0, 167, 0, 2, 0, 2,
ax_anim 8, 0, 167, 0, 3, 0, 3,
ax_anim_terminator
sWeedleAnims_7_6:
ax_anim 2, 0, 168, 2, 2, 2, 2,
ax_anim 8, 0, 168, 3, 3, 3, 3,
ax_anim_terminator
sWeedleAnims_7_7:
ax_anim 2, 0, 169, 2, 0, 2, 0,
ax_anim 8, 0, 169, 3, 0, 3, 0,
ax_anim_terminator
sWeedleAnims_7_8:
ax_anim 2, 0, 170, 2, -2, 2, -2,
ax_anim 8, 0, 170, 3, -3, 3, -3,
ax_anim_terminator
.align 2
sWeedleAnims_8_1:
ax_anim 40, 0, 171, 0, 0, 0, 0,
ax_anim 8, 0, 173, 0, 0, 0, 0,
ax_anim 8, 0, 171, 0, 0, 0, 0,
ax_anim 8, 0, 173, 0, 0, 0, 0,
ax_anim_terminator
sWeedleAnims_8_2:
ax_anim 40, 0, 174, 0, 0, 0, 0,
ax_anim 8, 0, 176, 0, 0, 0, 0,
ax_anim 8, 0, 174, 0, 0, 0, 0,
ax_anim 8, 0, 176, 0, 0, 0, 0,
ax_anim_terminator
sWeedleAnims_8_3:
ax_anim 40, 0, 177, 0, 0, 0, 0,
ax_anim 8, 0, 179, 0, 0, 0, 0,
ax_anim 8, 0, 177, 0, 0, 0, 0,
ax_anim 8, 0, 179, 0, 0, 0, 0,
ax_anim_terminator
sWeedleAnims_8_4:
ax_anim 40, 0, 180, 0, 0, 0, 0,
ax_anim 8, 0, 182, 0, 0, 0, 0,
ax_anim 8, 0, 180, 0, 0, 0, 0,
ax_anim 8, 0, 182, 0, 0, 0, 0,
ax_anim_terminator
sWeedleAnims_8_5:
ax_anim 40, 0, 183, 0, 0, 0, 0,
ax_anim 8, 0, 185, 0, 0, 0, 0,
ax_anim 8, 0, 183, 0, 0, 0, 0,
ax_anim 8, 0, 185, 0, 0, 0, 0,
ax_anim_terminator
sWeedleAnims_8_6:
ax_anim 40, 0, 186, 0, 0, 0, 0,
ax_anim 8, 0, 188, 0, 0, 0, 0,
ax_anim 8, 0, 186, 0, 0, 0, 0,
ax_anim 8, 0, 188, 0, 0, 0, 0,
ax_anim_terminator
sWeedleAnims_8_7:
ax_anim 40, 0, 189, 0, 0, 0, 0,
ax_anim 8, 0, 191, 0, 0, 0, 0,
ax_anim 8, 0, 189, 0, 0, 0, 0,
ax_anim 8, 0, 191, 0, 0, 0, 0,
ax_anim_terminator
sWeedleAnims_8_8:
ax_anim 40, 0, 192, 0, 0, 0, 0,
ax_anim 8, 0, 194, 0, 0, 0, 0,
ax_anim 8, 0, 192, 0, 0, 0, 0,
ax_anim 8, 0, 194, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sWeedleAnims_9_1:
ax_anim 2, 0, 195, 0, 0, 0, 0,
ax_anim 1, 0, 196, 8, 2, 8, 2,
ax_anim 2, 0, 197, 11, 11, 11, 11,
ax_anim 2, 0, 198, 9, 15, 9, 15,
ax_anim 3, 0, 199, 1, 16, 1, 16,
ax_anim 2, 3, 200, -9, 15, -9, 15,
ax_anim 2, 0, 201, -11, 11, -11, 11,
ax_anim 1, 0, 202, -8, 2, -8, 2,
ax_anim 1, 0, 195, 0, 0, 0, 0,
ax_anim_terminator
sWeedleAnims_9_2:
ax_anim 2, 0, 202, 0, 0, 0, 0,
ax_anim 1, 0, 195, 8, 0, 8, 0,
ax_anim 2, 0, 196, 20, 2, 20, 2,
ax_anim 2, 0, 197, 24, 9, 24, 9,
ax_anim 3, 0, 198, 23, 16, 23, 16,
ax_anim 2, 3, 199, 11, 19, 11, 19,
ax_anim 2, 0, 200, 1, 14, 1, 14,
ax_anim 1, 0, 201, -1, 7, -1, 7,
ax_anim 1, 0, 202, 0, 0, 0, 0,
ax_anim_terminator
sWeedleAnims_9_3:
ax_anim 2, 0, 201, 0, 0, 0, 0,
ax_anim 1, 0, 202, 3, -6, 3, -4,
ax_anim 2, 0, 195, 11, -7, 11, -6,
ax_anim 2, 0, 196, 18, -6, 17, -4,
ax_anim 3, 0, 197, 20, 1, 20, 1,
ax_anim 2, 3, 198, 17, 5, 17, 5,
ax_anim 2, 0, 199, 10, 8, 12, 7,
ax_anim 1, 0, 200, 2, 5, 4, 5,
ax_anim 1, 0, 201, 0, 0, 0, 0,
ax_anim_terminator
sWeedleAnims_9_4:
ax_anim 2, 0, 200, 0, 0, 0, 0,
ax_anim 1, 0, 201, -1, -6, 1, -6,
ax_anim 2, 0, 202, 2, -16, 4, -16,
ax_anim 2, 0, 195, 9, -20, 11, -20,
ax_anim 3, 0, 196, 16, -20, 16, -20,
ax_anim 2, 3, 197, 17, -13, 16, -15,
ax_anim 2, 0, 198, 14, -6, 14, -6,
ax_anim 1, 0, 199, 7, -1, 7, -1,
ax_anim 1, 0, 200, 0, 0, 0, 0,
ax_anim_terminator
sWeedleAnims_9_5:
ax_anim 2, 0, 199, 0, 0, 0, 0,
ax_anim 1, 0, 200, -6, -3, -6, -3,
ax_anim 2, 0, 201, -8, -9, -8, -8,
ax_anim 2, 0, 202, -7, -17, -7, -15,
ax_anim 3, 0, 195, 0, -18, 0, -16,
ax_anim 2, 3, 196, 7, -17, 7, -15,
ax_anim 2, 0, 197, 8, -9, 8, -8,
ax_anim 1, 0, 198, 6, -3, 6, -3,
ax_anim 1, 0, 199, 0, 0, 0, 0,
ax_anim_terminator
sWeedleAnims_9_6:
ax_anim 2, 0, 198, 0, 0, 0, 0,
ax_anim 1, 0, 197, 1, -6, -1, -6,
ax_anim 2, 0, 196, -2, -16, -4, -16,
ax_anim 2, 0, 195, -9, -20, -11, -20,
ax_anim 3, 0, 202, -16, -20, -16, -20,
ax_anim 2, 3, 201, -17, -13, -16, -15,
ax_anim 2, 0, 200, -14, -6, -14, -6,
ax_anim 1, 0, 199, -7, -1, -7, -1,
ax_anim 1, 0, 198, 0, 0, 0, 0,
ax_anim_terminator
sWeedleAnims_9_7:
ax_anim 2, 0, 197, 0, 0, 0, 0,
ax_anim 1, 0, 196, -3, -6, -3, -6,
ax_anim 2, 0, 195, -11, -7, -11, -7,
ax_anim 2, 0, 202, -18, -6, -18, -6,
ax_anim 3, 0, 201, -20, 1, -20, 1,
ax_anim 2, 3, 200, -17, 5, -17, 5,
ax_anim 2, 0, 199, -10, 8, -10, 8,
ax_anim 1, 0, 198, -2, 5, -2, 5,
ax_anim 1, 0, 197, 0, 0, 0, 0,
ax_anim_terminator
sWeedleAnims_9_8:
ax_anim 2, 0, 196, 0, 0, 0, 0,
ax_anim 1, 0, 195, -8, 0, -6, 0,
ax_anim 2, 0, 202, -20, 2, -17, 3,
ax_anim 2, 0, 201, -24, 9, -24, 9,
ax_anim 3, 0, 200, -23, 16, -23, 16,
ax_anim 2, 3, 199, -11, 19, -11, 16,
ax_anim 2, 0, 198, -1, 14, -4, 12,
ax_anim 1, 0, 197, 1, 7, -3, 7,
ax_anim 1, 0, 196, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sWeedleAnims_10_1:
ax_anim 2, 0, 203, 0, 0, 0, 0,
ax_anim 2, 0, 203, 6, 0, 6, 0,
ax_anim 2, 0, 203, -6, 0, -6, 0,
ax_anim 2, 0, 203, 10, 0, 10, 0,
ax_anim 2, 0, 203, -10, 0, -10, 0,
ax_anim 2, 0, 203, 12, 0, 12, 0,
ax_anim 3, 0, 203, -12, 0, -12, 0,
ax_anim 3, 0, 203, 13, 0, 13, 0,
ax_anim 3, 0, 203, -13, 0, -13, 0,
ax_anim 2, 0, 203, 12, 0, 12, 0,
ax_anim 3, 0, 203, -12, 0, -12, 0,
ax_anim 2, 0, 203, 10, 0, 10, 0,
ax_anim 2, 0, 203, -10, 0, -10, 0,
ax_anim 2, 0, 203, 6, 0, 6, 0,
ax_anim 2, 0, 203, -6, 0, -6, 0,
ax_anim 2, 0, 203, 0, 0, 0, 0,
ax_anim_terminator
sWeedleAnims_10_2:
ax_anim 2, 0, 204, 0, 0, 0, 0,
ax_anim 2, 0, 204, 6, -6, 6, -6,
ax_anim 2, 0, 204, -6, 6, -6, 6,
ax_anim 2, 0, 204, 10, -10, 10, -10,
ax_anim 2, 0, 204, -10, 10, -10, 10,
ax_anim 2, 0, 204, 12, -12, 12, -12,
ax_anim 3, 0, 204, -12, 12, -12, 12,
ax_anim 3, 0, 204, 13, -13, 13, -13,
ax_anim 3, 0, 204, -13, 13, -13, 13,
ax_anim 2, 0, 204, 12, -12, 12, -12,
ax_anim 3, 0, 204, -12, 12, -12, 12,
ax_anim 2, 0, 204, 10, -10, 10, -10,
ax_anim 2, 0, 204, -10, 10, -10, 10,
ax_anim 2, 0, 204, 6, -6, 6, -6,
ax_anim 2, 0, 204, -6, 6, -6, 6,
ax_anim 2, 0, 204, 0, 0, 0, 0,
ax_anim_terminator
sWeedleAnims_10_3:
ax_anim 2, 0, 205, 0, 0, 0, 0,
ax_anim 2, 0, 205, 0, -6, 0, -6,
ax_anim 2, 0, 205, 0, 6, 0, 6,
ax_anim 2, 0, 205, 0, -10, 0, -10,
ax_anim 2, 0, 205, 0, 10, 0, 10,
ax_anim 2, 0, 205, 0, -12, 0, -12,
ax_anim 3, 0, 205, 0, 12, 0, 12,
ax_anim 3, 0, 205, 0, -13, 0, -13,
ax_anim 3, 0, 205, 0, 13, 0, 13,
ax_anim 2, 0, 205, 0, -12, 0, -12,
ax_anim 3, 0, 205, 0, 12, 0, 12,
ax_anim 2, 0, 205, 0, -10, 0, -10,
ax_anim 2, 0, 205, 0, 10, 0, 10,
ax_anim 2, 0, 205, 0, -6, 0, -6,
ax_anim 2, 0, 205, 0, 6, 0, 6,
ax_anim 2, 0, 205, 0, 0, 0, 0,
ax_anim_terminator
sWeedleAnims_10_4:
ax_anim 2, 0, 206, 0, 0, 0, 0,
ax_anim 2, 0, 206, -6, -6, -6, -6,
ax_anim 2, 0, 206, 6, 6, 6, 6,
ax_anim 2, 0, 206, -10, -10, -10, -10,
ax_anim 2, 0, 206, 10, 10, 10, 10,
ax_anim 2, 0, 206, -12, -12, -12, -12,
ax_anim 3, 0, 206, 12, 12, 12, 12,
ax_anim 3, 0, 206, -13, -13, -13, -13,
ax_anim 3, 0, 206, 13, 13, 13, 13,
ax_anim 2, 0, 206, -12, -12, -12, -12,
ax_anim 3, 0, 206, 12, 12, 12, 12,
ax_anim 2, 0, 206, -10, -10, -10, -10,
ax_anim 2, 0, 206, 10, 10, 10, 10,
ax_anim 2, 0, 206, -6, -6, -6, -6,
ax_anim 2, 0, 206, 6, 6, 6, 6,
ax_anim 2, 0, 206, 0, 0, 0, 0,
ax_anim_terminator
sWeedleAnims_10_5:
ax_anim 2, 0, 207, 0, 0, 0, 0,
ax_anim 2, 0, 207, 6, 0, 6, 0,
ax_anim 2, 0, 207, -6, 0, -6, 0,
ax_anim 2, 0, 207, 10, 0, 10, 0,
ax_anim 2, 0, 207, -10, 0, -10, 0,
ax_anim 2, 0, 207, 12, 0, 12, 0,
ax_anim 3, 0, 207, -12, 0, -12, 0,
ax_anim 3, 0, 207, 13, 0, 13, 0,
ax_anim 3, 0, 207, -13, 0, -13, 0,
ax_anim 2, 0, 207, 12, 0, 12, 0,
ax_anim 3, 0, 207, -12, 0, -12, 0,
ax_anim 2, 0, 207, 10, 0, 10, 0,
ax_anim 2, 0, 207, -10, 0, -10, 0,
ax_anim 2, 0, 207, 6, 0, 6, 0,
ax_anim 2, 0, 207, -6, 0, -6, 0,
ax_anim 2, 0, 207, 0, 0, 0, 0,
ax_anim_terminator
sWeedleAnims_10_6:
ax_anim 2, 0, 208, 0, 0, 0, 0,
ax_anim 2, 0, 208, 6, -6, 6, -6,
ax_anim 2, 0, 208, -6, 6, -6, 6,
ax_anim 2, 0, 208, 10, -10, 10, -10,
ax_anim 2, 0, 208, -10, 10, -10, 10,
ax_anim 2, 0, 208, 12, -12, 12, -12,
ax_anim 3, 0, 208, -12, 12, -12, 12,
ax_anim 3, 0, 208, 13, -13, 13, -13,
ax_anim 3, 0, 208, -13, 13, -13, 13,
ax_anim 2, 0, 208, 12, -12, 12, -12,
ax_anim 3, 0, 208, -12, 12, -12, 12,
ax_anim 2, 0, 208, 10, -10, 10, -10,
ax_anim 2, 0, 208, -10, 10, -10, 10,
ax_anim 2, 0, 208, 6, -6, 6, -6,
ax_anim 2, 0, 208, -6, 6, -6, 6,
ax_anim 2, 0, 208, 0, 0, 0, 0,
ax_anim_terminator
sWeedleAnims_10_7:
ax_anim 2, 0, 209, 0, 0, 0, 0,
ax_anim 2, 0, 209, 0, -6, 0, -6,
ax_anim 2, 0, 209, 0, 6, 0, 6,
ax_anim 2, 0, 209, 0, -10, 0, -10,
ax_anim 2, 0, 209, 0, 10, 0, 10,
ax_anim 2, 0, 209, 0, -12, 0, -12,
ax_anim 3, 0, 209, 0, 12, 0, 12,
ax_anim 3, 0, 209, 0, -13, 0, -13,
ax_anim 3, 0, 209, 0, 13, 0, 13,
ax_anim 2, 0, 209, 0, -12, 0, -12,
ax_anim 3, 0, 209, 0, 12, 0, 12,
ax_anim 2, 0, 209, 0, -10, 0, -10,
ax_anim 2, 0, 209, 0, 10, 0, 10,
ax_anim 2, 0, 209, 0, -6, 0, -6,
ax_anim 2, 0, 209, 0, 6, 0, 6,
ax_anim 2, 0, 209, 0, 0, 0, 0,
ax_anim_terminator
sWeedleAnims_10_8:
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 2, 0, 210, -6, -6, -6, -6,
ax_anim 2, 0, 210, 6, 6, 6, 6,
ax_anim 2, 0, 210, -10, -10, -10, -10,
ax_anim 2, 0, 210, 10, 10, 10, 10,
ax_anim 2, 0, 210, -12, -12, -12, -12,
ax_anim 3, 0, 210, 12, 12, 12, 12,
ax_anim 3, 0, 210, -13, -13, -13, -13,
ax_anim 3, 0, 210, 13, 13, 13, 13,
ax_anim 2, 0, 210, -12, -12, -12, -12,
ax_anim 3, 0, 210, 12, 12, 12, 12,
ax_anim 2, 0, 210, -10, -10, -10, -10,
ax_anim 2, 0, 210, 10, 10, 10, 10,
ax_anim 2, 0, 210, -6, -6, -6, -6,
ax_anim 2, 0, 210, 6, 6, 6, 6,
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sWeedleAnims_11_1:
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 1, 0, 212, 0, -10, 0, 0,
ax_anim 2, 0, 212, 0, -16, 0, 0,
ax_anim 3, 0, 212, 0, -20, 0, 0,
ax_anim 4, 0, 212, 0, -21, 0, 0,
ax_anim 4, 0, 213, 0, -23, 0, 0,
ax_anim 3, 0, 213, 0, -22, 0, 0,
ax_anim 2, 0, 213, 0, -18, 0, 0,
ax_anim 1, 0, 213, 0, -12, 0, 0,
ax_anim 2, 2, 213, 0, -3, 0, 0,
ax_anim_terminator
sWeedleAnims_11_2:
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 1, 0, 215, 0, -10, 0, 0,
ax_anim 2, 0, 215, 0, -16, 0, 0,
ax_anim 3, 0, 215, 0, -20, 0, 0,
ax_anim 4, 0, 215, 0, -21, 0, 0,
ax_anim 4, 0, 216, 0, -23, 0, 0,
ax_anim 3, 0, 216, 0, -22, 0, 0,
ax_anim 2, 0, 216, 0, -18, 0, 0,
ax_anim 1, 0, 216, 0, -12, 0, 0,
ax_anim 2, 2, 214, 0, 0, 0, 0,
ax_anim_terminator
sWeedleAnims_11_3:
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 1, 0, 218, 0, -10, 0, 0,
ax_anim 2, 0, 218, 0, -16, 0, 0,
ax_anim 3, 0, 218, 0, -20, 0, 0,
ax_anim 4, 0, 218, 0, -21, 0, 0,
ax_anim 4, 0, 219, 0, -23, 0, 0,
ax_anim 3, 0, 219, 0, -22, 0, 0,
ax_anim 2, 0, 219, 0, -18, 0, 0,
ax_anim 1, 0, 219, 0, -12, 0, 0,
ax_anim 2, 2, 217, 0, 0, 0, 0,
ax_anim_terminator
sWeedleAnims_11_4:
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 1, 0, 221, 0, -10, 0, 0,
ax_anim 2, 0, 221, 0, -16, 0, 0,
ax_anim 3, 0, 221, 0, -20, 0, 0,
ax_anim 4, 0, 221, 0, -21, 0, 0,
ax_anim 4, 0, 222, 0, -22, 0, 0,
ax_anim 3, 0, 222, 0, -21, 0, 0,
ax_anim 2, 0, 222, 0, -17, 0, 0,
ax_anim 1, 0, 222, 0, -11, 0, 0,
ax_anim 2, 2, 220, 0, 0, 0, 0,
ax_anim_terminator
sWeedleAnims_11_5:
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 1, 0, 225, 0, -10, 0, 0,
ax_anim 2, 0, 225, 0, -16, 0, 0,
ax_anim 3, 0, 225, 0, -20, 0, 0,
ax_anim 4, 0, 225, 0, -21, 0, 0,
ax_anim 4, 0, 224, 0, -17, 0, 0,
ax_anim 3, 0, 224, 0, -16, 0, 0,
ax_anim 2, 0, 224, 0, -12, 0, 0,
ax_anim 1, 0, 224, 0, -6, 0, 0,
ax_anim 2, 2, 223, 0, 2, 0, 0,
ax_anim_terminator
sWeedleAnims_11_6:
ax_anim 2, 0, 226, 1, 0, 0, 0,
ax_anim 1, 0, 227, 1, -10, 0, 0,
ax_anim 2, 0, 227, 1, -16, 0, 0,
ax_anim 3, 0, 227, 1, -20, 0, 0,
ax_anim 4, 0, 227, 1, -21, 0, 0,
ax_anim 4, 0, 228, 1, -22, 0, 0,
ax_anim 3, 0, 228, 1, -21, 0, 0,
ax_anim 2, 0, 228, 1, -17, 0, 0,
ax_anim 1, 0, 228, 1, -11, 0, 0,
ax_anim 2, 2, 226, 1, 0, 0, 0,
ax_anim_terminator
sWeedleAnims_11_7:
ax_anim 2, 0, 229, 1, 0, 0, 0,
ax_anim 1, 0, 230, 1, -10, 0, 0,
ax_anim 2, 0, 230, 1, -16, 0, 0,
ax_anim 3, 0, 230, 1, -20, 0, 0,
ax_anim 4, 0, 230, 1, -21, 0, 0,
ax_anim 4, 0, 231, 1, -23, 0, 0,
ax_anim 3, 0, 231, 1, -22, 0, 0,
ax_anim 2, 0, 231, 1, -18, 0, 0,
ax_anim 1, 0, 231, 1, -12, 0, 0,
ax_anim 2, 2, 229, 1, 0, 0, 0,
ax_anim_terminator
sWeedleAnims_11_8:
ax_anim 2, 0, 232, 0, 0, 0, 0,
ax_anim 1, 0, 233, 0, -10, 0, 0,
ax_anim 2, 0, 233, 0, -16, 0, 0,
ax_anim 3, 0, 233, 0, -20, 0, 0,
ax_anim 4, 0, 233, 0, -21, 0, 0,
ax_anim 4, 0, 234, 0, -23, 0, 0,
ax_anim 3, 0, 234, 0, -22, 0, 0,
ax_anim 2, 0, 234, 0, -18, 0, 0,
ax_anim 1, 0, 234, 0, -12, 0, 0,
ax_anim 2, 2, 232, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sWeedleAnims_12_1:
ax_anim 2, 0, 235, 1, 0, 1, 0,
ax_anim 2, 0, 235, 0, 0, 0, 0,
ax_anim 2, 0, 235, 1, 0, 1, 0,
ax_anim 2, 0, 235, 0, 0, 0, 0,
ax_anim 2, 0, 235, 1, 0, 1, 0,
ax_anim 2, 2, 235, 0, 0, 0, 0,
ax_anim 2, 0, 235, 1, 0, 1, 0,
ax_anim 2, 0, 235, 0, 0, 0, 0,
ax_anim 2, 0, 235, 1, 0, 1, 0,
ax_anim 2, 1, 235, 0, 0, 0, 0,
ax_anim_terminator
sWeedleAnims_12_2:
ax_anim 2, 0, 242, 1, -1, 1, 0,
ax_anim 2, 0, 242, 0, 0, 0, 0,
ax_anim 2, 0, 242, 1, -1, 1, 0,
ax_anim 2, 0, 242, 0, 0, 0, 0,
ax_anim 2, 0, 242, 1, -1, 1, 0,
ax_anim 2, 2, 242, 0, 0, 0, 0,
ax_anim 2, 0, 242, 1, -1, 1, 0,
ax_anim 2, 0, 242, 0, 0, 0, 0,
ax_anim 2, 0, 242, 1, -1, 1, 0,
ax_anim 2, 1, 242, 0, 0, 0, 0,
ax_anim_terminator
sWeedleAnims_12_3:
ax_anim 2, 0, 241, 0, -1, 0, -1,
ax_anim 2, 0, 241, 0, 0, 0, 0,
ax_anim 2, 0, 241, 0, -1, 0, -1,
ax_anim 2, 0, 241, 0, 0, 0, 0,
ax_anim 2, 0, 241, 0, -1, 0, -1,
ax_anim 2, 2, 241, 0, 0, 0, 0,
ax_anim 2, 0, 241, 0, -1, 0, -1,
ax_anim 2, 0, 241, 0, 0, 0, 0,
ax_anim 2, 0, 241, 0, -1, 0, -1,
ax_anim 2, 1, 241, 0, 0, 0, 0,
ax_anim_terminator
sWeedleAnims_12_4:
ax_anim 2, 0, 240, -1, -1, -1, -1,
ax_anim 2, 0, 240, 0, 0, 0, 0,
ax_anim 2, 0, 240, -1, -1, -1, -1,
ax_anim 2, 0, 240, 0, 0, 0, 0,
ax_anim 2, 0, 240, -1, -1, -1, -1,
ax_anim 2, 2, 240, 0, 0, 0, 0,
ax_anim 2, 0, 240, -1, -1, -1, -1,
ax_anim 2, 0, 240, 0, 0, 0, 0,
ax_anim 2, 0, 240, -1, -1, -1, -1,
ax_anim 2, 1, 240, 0, 0, 0, 0,
ax_anim_terminator
sWeedleAnims_12_5:
ax_anim 2, 0, 239, 1, 0, 1, 0,
ax_anim 2, 0, 239, 0, 0, 0, 0,
ax_anim 2, 0, 239, 1, 0, 1, 0,
ax_anim 2, 0, 239, 0, 0, 0, 0,
ax_anim 2, 0, 239, 1, 0, 1, 0,
ax_anim 2, 2, 239, 0, 0, 0, 0,
ax_anim 2, 0, 239, 1, 0, 1, 0,
ax_anim 2, 0, 239, 0, 0, 0, 0,
ax_anim 2, 0, 239, 1, 0, 1, 0,
ax_anim 2, 1, 239, 0, 0, 0, 0,
ax_anim_terminator
sWeedleAnims_12_6:
ax_anim 2, 0, 238, 1, -1, 1, -1,
ax_anim 2, 0, 238, 0, 0, 0, 0,
ax_anim 2, 0, 238, 1, -1, 1, -1,
ax_anim 2, 0, 238, 0, 0, 0, 0,
ax_anim 2, 0, 238, 1, -1, 1, -1,
ax_anim 2, 2, 238, 0, 0, 0, 0,
ax_anim 2, 0, 238, 1, -1, 1, -1,
ax_anim 2, 0, 238, 0, 0, 0, 0,
ax_anim 2, 0, 238, 1, -1, 1, -1,
ax_anim 2, 1, 238, 0, 0, 0, 0,
ax_anim_terminator
sWeedleAnims_12_7:
ax_anim 2, 0, 237, 0, -1, 0, -1,
ax_anim 2, 0, 237, 0, 0, 0, 0,
ax_anim 2, 0, 237, 0, -1, 0, -1,
ax_anim 2, 0, 237, 0, 0, 0, 0,
ax_anim 2, 0, 237, 0, -1, 0, -1,
ax_anim 2, 2, 237, 0, 0, 0, 0,
ax_anim 2, 0, 237, 0, -1, 0, -1,
ax_anim 2, 0, 237, 0, 0, 0, 0,
ax_anim 2, 0, 237, 0, -1, 0, -1,
ax_anim 2, 1, 237, 0, 0, 0, 0,
ax_anim_terminator
sWeedleAnims_12_8:
ax_anim 2, 0, 236, -1, -1, -1, -1,
ax_anim 2, 0, 236, 0, 0, 0, 0,
ax_anim 2, 0, 236, -1, -1, -1, -1,
ax_anim 2, 0, 236, 0, 0, 0, 0,
ax_anim 2, 0, 236, -1, -1, -1, -1,
ax_anim 2, 2, 236, 0, 0, 0, 0,
ax_anim 2, 0, 236, -1, -1, -1, -1,
ax_anim 2, 0, 236, 0, 0, 0, 0,
ax_anim 2, 0, 236, -1, -1, -1, -1,
ax_anim 2, 1, 236, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sWeedleAnims_13_1:
ax_anim 2, 0, 243, 0, 0, 0, 0,
ax_anim 2, 0, 244, 0, 0, 0, 0,
ax_anim 2, 0, 245, 0, 0, 0, 0,
ax_anim 2, 0, 246, 0, 0, 0, 0,
ax_anim 2, 0, 247, 0, 0, 0, 0,
ax_anim 2, 0, 248, 0, 0, 0, 0,
ax_anim 2, 0, 249, 0, 0, 0, 0,
ax_anim 2, 0, 250, 0, 0, 0, 0,
ax_anim 2, 2, 243, 0, 0, 0, 0,
ax_anim_terminator
sWeedleAnims_13_2:
ax_anim 2, 0, 250, 0, 0, 0, 0,
ax_anim 2, 0, 243, 0, 0, 0, 0,
ax_anim 2, 0, 244, 0, 0, 0, 0,
ax_anim 2, 0, 245, 0, 0, 0, 0,
ax_anim 2, 0, 246, 0, 0, 0, 0,
ax_anim 2, 0, 247, 0, 0, 0, 0,
ax_anim 2, 0, 248, 0, 0, 0, 0,
ax_anim 2, 0, 249, 0, 0, 0, 0,
ax_anim 2, 2, 250, 0, 0, 0, 0,
ax_anim_terminator
sWeedleAnims_13_3:
ax_anim 2, 0, 249, 0, 0, 0, 0,
ax_anim 2, 0, 250, 0, 0, 0, 0,
ax_anim 2, 0, 243, 0, 0, 0, 0,
ax_anim 2, 0, 244, 0, 0, 0, 0,
ax_anim 2, 0, 245, 0, 0, 0, 0,
ax_anim 2, 0, 246, 0, 0, 0, 0,
ax_anim 2, 0, 247, 0, 0, 0, 0,
ax_anim 2, 0, 248, 0, 0, 0, 0,
ax_anim 2, 2, 249, 0, 0, 0, 0,
ax_anim_terminator
sWeedleAnims_13_4:
ax_anim 2, 0, 248, 0, 0, 0, 0,
ax_anim 2, 0, 249, 0, 0, 0, 0,
ax_anim 2, 0, 250, 0, 0, 0, 0,
ax_anim 2, 0, 243, 0, 0, 0, 0,
ax_anim 2, 0, 244, 0, 0, 0, 0,
ax_anim 2, 0, 245, 0, 0, 0, 0,
ax_anim 2, 0, 246, 0, 0, 0, 0,
ax_anim 2, 0, 247, 0, 0, 0, 0,
ax_anim 2, 2, 248, 0, 0, 0, 0,
ax_anim_terminator
sWeedleAnims_13_5:
ax_anim 2, 0, 247, 0, 0, 0, 0,
ax_anim 2, 0, 248, 0, 0, 0, 0,
ax_anim 2, 0, 249, 0, 0, 0, 0,
ax_anim 2, 0, 250, 0, 0, 0, 0,
ax_anim 2, 0, 243, 0, 0, 0, 0,
ax_anim 2, 0, 244, 0, 0, 0, 0,
ax_anim 2, 0, 245, 0, 0, 0, 0,
ax_anim 2, 0, 246, 0, 0, 0, 0,
ax_anim 2, 2, 247, 0, 0, 0, 0,
ax_anim_terminator
sWeedleAnims_13_6:
ax_anim 2, 0, 246, 0, 0, 0, 0,
ax_anim 2, 0, 247, 0, 0, 0, 0,
ax_anim 2, 0, 248, 0, 0, 0, 0,
ax_anim 2, 0, 249, 0, 0, 0, 0,
ax_anim 2, 0, 250, 0, 0, 0, 0,
ax_anim 2, 0, 243, 0, 0, 0, 0,
ax_anim 2, 0, 244, 0, 0, 0, 0,
ax_anim 2, 0, 245, 0, 0, 0, 0,
ax_anim 2, 2, 246, 0, 0, 0, 0,
ax_anim_terminator
sWeedleAnims_13_7:
ax_anim 2, 0, 245, 0, 0, 0, 0,
ax_anim 2, 0, 246, 0, 0, 0, 0,
ax_anim 2, 0, 247, 0, 0, 0, 0,
ax_anim 2, 0, 248, 0, 0, 0, 0,
ax_anim 2, 0, 249, 0, 0, 0, 0,
ax_anim 2, 0, 250, 0, 0, 0, 0,
ax_anim 2, 0, 243, 0, 0, 0, 0,
ax_anim 2, 0, 244, 0, 0, 0, 0,
ax_anim 2, 2, 245, 0, 0, 0, 0,
ax_anim_terminator
sWeedleAnims_13_8:
ax_anim 2, 0, 244, 0, 0, 0, 0,
ax_anim 2, 0, 245, 0, 0, 0, 0,
ax_anim 2, 0, 246, 0, 0, 0, 0,
ax_anim 2, 0, 247, 0, 0, 0, 0,
ax_anim 2, 0, 248, 0, 0, 0, 0,
ax_anim 2, 0, 249, 0, 0, 0, 0,
ax_anim 2, 0, 250, 0, 0, 0, 0,
ax_anim 2, 0, 243, 0, 0, 0, 0,
ax_anim 2, 2, 244, 0, 0, 0, 0,
ax_anim_terminator
sWeedleGfx1:
.incbin "baserom.gba", 0x5A1750, 0x100
sWeedleSprites1:
ax_sprite sWeedleGfx1, 0x100
ax_sprite_terminator
sWeedleGfx2:
.incbin "baserom.gba", 0x5A1860, 0x100
sWeedleSprites2:
ax_sprite sWeedleGfx2, 0x100
ax_sprite_terminator
sWeedleGfx3:
.incbin "baserom.gba", 0x5A1970, 0x100
sWeedleSprites3:
ax_sprite sWeedleGfx3, 0x100
ax_sprite_terminator
sWeedleGfx4:
.incbin "baserom.gba", 0x5A1A80, 0x200
sWeedleSprites4:
ax_sprite sWeedleGfx4, 0x200
ax_sprite_terminator
sWeedleGfx5:
.incbin "baserom.gba", 0x5A1C90, 0x200
sWeedleSprites5:
ax_sprite sWeedleGfx5, 0x200
ax_sprite_terminator
sWeedleGfx6:
.incbin "baserom.gba", 0x5A1EA0, 0x200
sWeedleSprites6:
ax_sprite sWeedleGfx6, 0x200
ax_sprite_terminator
sWeedleGfx7:
.incbin "baserom.gba", 0x5A20B0, 0x200
sWeedleSprites7:
ax_sprite sWeedleGfx7, 0x200
ax_sprite_terminator
sWeedleGfx8:
.incbin "baserom.gba", 0x5A22C0, 0x200
sWeedleSprites8:
ax_sprite sWeedleGfx8, 0x200
ax_sprite_terminator
sWeedleGfx9:
.incbin "baserom.gba", 0x5A24D0, 0x200
sWeedleSprites9:
ax_sprite sWeedleGfx9, 0x200
ax_sprite_terminator
sWeedleGfx10:
.incbin "baserom.gba", 0x5A26E0, 0x200
sWeedleSprites10:
ax_sprite sWeedleGfx10, 0x200
ax_sprite_terminator
sWeedleGfx11:
.incbin "baserom.gba", 0x5A28F0, 0x200
sWeedleSprites11:
ax_sprite sWeedleGfx11, 0x200
ax_sprite_terminator
sWeedleGfx12:
.incbin "baserom.gba", 0x5A2B00, 0x200
sWeedleSprites12:
ax_sprite sWeedleGfx12, 0x200
ax_sprite_terminator
sWeedleGfx13:
.incbin "baserom.gba", 0x5A2D10, 0x100
sWeedleSprites13:
ax_sprite sWeedleGfx13, 0x100
ax_sprite_terminator
sWeedleGfx14:
.incbin "baserom.gba", 0x5A2E20, 0x100
sWeedleSprites14:
ax_sprite sWeedleGfx14, 0x100
ax_sprite_terminator
sWeedleGfx15:
.incbin "baserom.gba", 0x5A2F30, 0x100
sWeedleSprites15:
ax_sprite sWeedleGfx15, 0x100
ax_sprite_terminator
sWeedleGfx16:
.incbin "baserom.gba", 0x5A3040, 0xC0
sWeedleSprites16:
ax_sprite sWeedleGfx16, 0xc0
ax_sprite 0, 0x40
ax_sprite_terminator
sWeedleGfx17:
.incbin "baserom.gba", 0x5A3118, 0x20
sWeedleGfx17_1:
.incbin "baserom.gba", 0x5A3138, 0xC0
sWeedleSprites17:
ax_sprite sWeedleGfx17, 0x20
ax_sprite 0, 0x20
ax_sprite sWeedleGfx17_1, 0xc0
ax_sprite_terminator
sWeedleGfx18:
.incbin "baserom.gba", 0x5A3218, 0x60
sWeedleGfx18_1:
.incbin "baserom.gba", 0x5A3278, 0x60
sWeedleSprites18:
ax_sprite sWeedleGfx18, 0x60
ax_sprite 0, 0x20
ax_sprite sWeedleGfx18_1, 0x60
ax_sprite 0, 0x20
ax_sprite_terminator
sWeedleGfx19:
.incbin "baserom.gba", 0x5A3300, 0x40
sWeedleGfx19_1:
.incbin "baserom.gba", 0x5A3340, 0x80
sWeedleSprites19:
ax_sprite sWeedleGfx19, 0x40
ax_sprite 0, 0x40
ax_sprite sWeedleGfx19_1, 0x80
ax_sprite_terminator
sWeedleGfx20:
.incbin "baserom.gba", 0x5A33E0, 0x40
sWeedleGfx20_1:
.incbin "baserom.gba", 0x5A3420, 0x60
sWeedleGfx20_2:
.incbin "baserom.gba", 0x5A3480, 0x60
sWeedleSprites20:
ax_sprite sWeedleGfx20, 0x40
ax_sprite 0, 0x40
ax_sprite sWeedleGfx20_1, 0x60
ax_sprite 0, 0x40
ax_sprite sWeedleGfx20_2, 0x60
ax_sprite 0, 0x80
ax_sprite_terminator
sWeedleGfx21:
.incbin "baserom.gba", 0x5A3518, 0x100
sWeedleSprites21:
ax_sprite sWeedleGfx21, 0x100
ax_sprite_terminator
sWeedleGfx22:
.incbin "baserom.gba", 0x5A3628, 0x60
sWeedleGfx22_1:
.incbin "baserom.gba", 0x5A3688, 0x60
sWeedleGfx22_2:
.incbin "baserom.gba", 0x5A36E8, 0x40
sWeedleSprites22:
ax_sprite 0, 0x80
ax_sprite sWeedleGfx22, 0x60
ax_sprite 0, 0x20
ax_sprite sWeedleGfx22_1, 0x60
ax_sprite 0, 0x20
ax_sprite sWeedleGfx22_2, 0x40
ax_sprite 0, 0x40
ax_sprite_terminator
sWeedleGfx23:
.incbin "baserom.gba", 0x5A3768, 0x40
sWeedleGfx23_1:
.incbin "baserom.gba", 0x5A37A8, 0x60
sWeedleGfx23_2:
.incbin "baserom.gba", 0x5A3808, 0x40
sWeedleSprites23:
ax_sprite sWeedleGfx23, 0x40
ax_sprite 0, 0x40
ax_sprite sWeedleGfx23_1, 0x60
ax_sprite 0, 0x20
ax_sprite sWeedleGfx23_2, 0x40
ax_sprite 0, 0xc0
ax_sprite_terminator
sWeedleGfx24:
.incbin "baserom.gba", 0x5A3880, 0x60
sWeedleGfx24_1:
.incbin "baserom.gba", 0x5A38E0, 0x60
sWeedleGfx24_2:
.incbin "baserom.gba", 0x5A3940, 0x60
sWeedleSprites24:
ax_sprite sWeedleGfx24, 0x60
ax_sprite 0, 0x20
ax_sprite sWeedleGfx24_1, 0x60
ax_sprite 0, 0x20
ax_sprite sWeedleGfx24_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sWeedleGfx25:
.incbin "baserom.gba", 0x5A39D8, 0xA0
sWeedleSprites25:
ax_sprite sWeedleGfx25, 0xa0
ax_sprite 0, 0x60
ax_sprite_terminator
sWeedleGfx26:
.incbin "baserom.gba", 0x5A3A90, 0xC0
sWeedleSprites26:
ax_sprite sWeedleGfx26, 0xc0
ax_sprite 0, 0x40
ax_sprite_terminator
sWeedleGfx27:
.incbin "baserom.gba", 0x5A3B68, 0x20
sWeedleGfx27_1:
.incbin "baserom.gba", 0x5A3B88, 0x80
sWeedleGfx27_2:
.incbin "baserom.gba", 0x5A3C08, 0x20
sWeedleSprites27:
ax_sprite sWeedleGfx27, 0x20
ax_sprite 0, 0x20
ax_sprite sWeedleGfx27_1, 0x80
ax_sprite 0, 0x20
ax_sprite sWeedleGfx27_2, 0x20
ax_sprite_terminator
sWeedleGfx28:
.incbin "baserom.gba", 0x5A3C58, 0xC0
sWeedleSprites28:
ax_sprite sWeedleGfx28, 0xc0
ax_sprite 0, 0x40
ax_sprite_terminator
sWeedleGfx29:
.incbin "baserom.gba", 0x5A3D30, 0xC0
sWeedleSprites29:
ax_sprite sWeedleGfx29, 0xc0
ax_sprite 0, 0x40
ax_sprite_terminator
sWeedleGfx30:
.incbin "baserom.gba", 0x5A3E08, 0xC0
sWeedleSprites30:
ax_sprite sWeedleGfx30, 0xc0
ax_sprite 0, 0x40
ax_sprite_terminator
sWeedleGfx31:
.incbin "baserom.gba", 0x5A3EE0, 0xC0
sWeedleSprites31:
ax_sprite sWeedleGfx31, 0xc0
ax_sprite 0, 0x40
ax_sprite_terminator
sWeedleGfx32:
.incbin "baserom.gba", 0x5A3FB8, 0x40
sWeedleGfx32_1:
.incbin "baserom.gba", 0x5A3FF8, 0x60
sWeedleGfx32_2:
.incbin "baserom.gba", 0x5A4058, 0x40
sWeedleSprites32:
ax_sprite sWeedleGfx32, 0x40
ax_sprite 0, 0x40
ax_sprite sWeedleGfx32_1, 0x60
ax_sprite 0, 0x20
ax_sprite sWeedleGfx32_2, 0x40
ax_sprite 0, 0xc0
ax_sprite_terminator
sWeedleGfx33:
.incbin "baserom.gba", 0x5A40D0, 0x20
sWeedleGfx33_1:
.incbin "baserom.gba", 0x5A40F0, 0x60
sWeedleGfx33_2:
.incbin "baserom.gba", 0x5A4150, 0x40
sWeedleSprites33:
ax_sprite 0, 0x20
ax_sprite sWeedleGfx33, 0x20
ax_sprite 0, 0x40
ax_sprite sWeedleGfx33_1, 0x60
ax_sprite 0, 0x20
ax_sprite sWeedleGfx33_2, 0x40
ax_sprite 0, 0xc0
ax_sprite_terminator
sWeedleGfx34:
.incbin "baserom.gba", 0x5A41D0, 0xC0
sWeedleSprites34:
ax_sprite sWeedleGfx34, 0xc0
ax_sprite 0, 0x40
ax_sprite_terminator
sWeedleGfx35:
.incbin "baserom.gba", 0x5A42A8, 0x20
sWeedleGfx35_1:
.incbin "baserom.gba", 0x5A42C8, 0x60
sWeedleGfx35_2:
.incbin "baserom.gba", 0x5A4328, 0x40
sWeedleSprites35:
ax_sprite 0, 0x20
ax_sprite sWeedleGfx35, 0x20
ax_sprite 0, 0x40
ax_sprite sWeedleGfx35_1, 0x60
ax_sprite 0, 0x20
ax_sprite sWeedleGfx35_2, 0x40
ax_sprite 0, 0xc0
ax_sprite_terminator
sWeedleGfx36:
.incbin "baserom.gba", 0x5A43A8, 0x100
sWeedleSprites36:
ax_sprite sWeedleGfx36, 0x100
ax_sprite_terminator
sWeedleGfx37:
.incbin "baserom.gba", 0x5A44B8, 0x100
sWeedleSprites37:
ax_sprite sWeedleGfx37, 0x100
ax_sprite_terminator
sWeedleGfx38:
.incbin "baserom.gba", 0x5A45C8, 0x200
sWeedleSprites38:
ax_sprite sWeedleGfx38, 0x200
ax_sprite_terminator
sWeedleGfx39:
.incbin "baserom.gba", 0x5A47D8, 0x200
sWeedleSprites39:
ax_sprite sWeedleGfx39, 0x200
ax_sprite_terminator
sWeedleGfx40:
.incbin "baserom.gba", 0x5A49E8, 0x200
sWeedleSprites40:
ax_sprite sWeedleGfx40, 0x200
ax_sprite_terminator
sWeedleGfx41:
.incbin "baserom.gba", 0x5A4BF8, 0x200
sWeedleSprites41:
ax_sprite sWeedleGfx41, 0x200
ax_sprite_terminator
sWeedleGfx42:
.incbin "baserom.gba", 0x5A4E08, 0x200
sWeedleSprites42:
ax_sprite sWeedleGfx42, 0x200
ax_sprite_terminator
sAxPosesWeedle:
.4byte sWeedlePose1
.4byte sWeedlePose2
.4byte sWeedlePose3
.4byte sWeedlePose4
.4byte sWeedlePose5
.4byte sWeedlePose6
.4byte sWeedlePose7
.4byte sWeedlePose8
.4byte sWeedlePose9
.4byte sWeedlePose10
.4byte sWeedlePose11
.4byte sWeedlePose12
.4byte sWeedlePose13
.4byte sWeedlePose14
.4byte sWeedlePose15
.4byte sWeedlePose16
.4byte sWeedlePose17
.4byte sWeedlePose18
.4byte sWeedlePose19
.4byte sWeedlePose20
.4byte sWeedlePose21
.4byte sWeedlePose22
.4byte sWeedlePose23
.4byte sWeedlePose24
.4byte sWeedlePose25
.4byte sWeedlePose26
.4byte sWeedlePose27
.4byte sWeedlePose28
.4byte sWeedlePose29
.4byte sWeedlePose30
.4byte sWeedlePose31
.4byte sWeedlePose32
.4byte sWeedlePose33
.4byte sWeedlePose34
.4byte sWeedlePose35
.4byte sWeedlePose36
.4byte sWeedlePose37
.4byte sWeedlePose38
.4byte sWeedlePose39
.4byte sWeedlePose40
.4byte sWeedlePose41
.4byte sWeedlePose42
.4byte sWeedlePose43
.4byte sWeedlePose44
.4byte sWeedlePose45
.4byte sWeedlePose46
.4byte sWeedlePose47
.4byte sWeedlePose48
.4byte sWeedlePose49
.4byte sWeedlePose50
.4byte sWeedlePose51
.4byte sWeedlePose52
.4byte sWeedlePose53
.4byte sWeedlePose54
.4byte sWeedlePose55
.4byte sWeedlePose56
.4byte sWeedlePose57
.4byte sWeedlePose58
.4byte sWeedlePose59
.4byte sWeedlePose60
.4byte sWeedlePose61
.4byte sWeedlePose62
.4byte sWeedlePose63
.4byte sWeedlePose64
.4byte sWeedlePose65
.4byte sWeedlePose66
.4byte sWeedlePose67
.4byte sWeedlePose68
.4byte sWeedlePose69
.4byte sWeedlePose70
.4byte sWeedlePose71
.4byte sWeedlePose72
.4byte sWeedlePose73
.4byte sWeedlePose74
.4byte sWeedlePose75
.4byte sWeedlePose76
.4byte sWeedlePose77
.4byte sWeedlePose78
.4byte sWeedlePose79
.4byte sWeedlePose80
.4byte sWeedlePose81
.4byte sWeedlePose82
.4byte sWeedlePose83
.4byte sWeedlePose84
.4byte sWeedlePose85
.4byte sWeedlePose86
.4byte sWeedlePose87
.4byte sWeedlePose88
.4byte sWeedlePose89
.4byte sWeedlePose90
.4byte sWeedlePose91
.4byte sWeedlePose92
.4byte sWeedlePose93
.4byte sWeedlePose94
.4byte sWeedlePose95
.4byte sWeedlePose96
.4byte sWeedlePose97
.4byte sWeedlePose98
.4byte sWeedlePose99
.4byte sWeedlePose100
.4byte sWeedlePose101
.4byte sWeedlePose102
.4byte sWeedlePose103
.4byte sWeedlePose104
.4byte sWeedlePose105
.4byte sWeedlePose106
.4byte sWeedlePose107
.4byte sWeedlePose108
.4byte sWeedlePose109
.4byte sWeedlePose110
.4byte sWeedlePose111
.4byte sWeedlePose112
.4byte sWeedlePose113
.4byte sWeedlePose114
.4byte sWeedlePose115
.4byte sWeedlePose116
.4byte sWeedlePose117
.4byte sWeedlePose118
.4byte sWeedlePose119
.4byte sWeedlePose120
.4byte sWeedlePose121
.4byte sWeedlePose122
.4byte sWeedlePose123
.4byte sWeedlePose124
.4byte sWeedlePose125
.4byte sWeedlePose126
.4byte sWeedlePose127
.4byte sWeedlePose128
.4byte sWeedlePose129
.4byte sWeedlePose130
.4byte sWeedlePose131
.4byte sWeedlePose132
.4byte sWeedlePose133
.4byte sWeedlePose134
.4byte sWeedlePose135
.4byte sWeedlePose136
.4byte sWeedlePose137
.4byte sWeedlePose138
.4byte sWeedlePose139
.4byte sWeedlePose140
.4byte sWeedlePose141
.4byte sWeedlePose142
.4byte sWeedlePose143
.4byte sWeedlePose144
.4byte sWeedlePose145
.4byte sWeedlePose146
.4byte sWeedlePose147
.4byte sWeedlePose148
.4byte sWeedlePose149
.4byte sWeedlePose150
.4byte sWeedlePose151
.4byte sWeedlePose152
.4byte sWeedlePose153
.4byte sWeedlePose154
.4byte sWeedlePose155
.4byte sWeedlePose156
.4byte sWeedlePose157
.4byte sWeedlePose158
.4byte sWeedlePose159
.4byte sWeedlePose160
.4byte sWeedlePose161
.4byte sWeedlePose162
.4byte sWeedlePose163
.4byte sWeedlePose164
.4byte sWeedlePose165
.4byte sWeedlePose166
.4byte sWeedlePose167
.4byte sWeedlePose168
.4byte sWeedlePose169
.4byte sWeedlePose170
.4byte sWeedlePose171
.4byte sWeedlePose172
.4byte sWeedlePose173
.4byte sWeedlePose174
.4byte sWeedlePose175
.4byte sWeedlePose176
.4byte sWeedlePose177
.4byte sWeedlePose178
.4byte sWeedlePose179
.4byte sWeedlePose180
.4byte sWeedlePose181
.4byte sWeedlePose182
.4byte sWeedlePose183
.4byte sWeedlePose184
.4byte sWeedlePose185
.4byte sWeedlePose186
.4byte sWeedlePose187
.4byte sWeedlePose188
.4byte sWeedlePose189
.4byte sWeedlePose190
.4byte sWeedlePose191
.4byte sWeedlePose192
.4byte sWeedlePose193
.4byte sWeedlePose194
.4byte sWeedlePose195
.4byte sWeedlePose196
.4byte sWeedlePose197
.4byte sWeedlePose198
.4byte sWeedlePose199
.4byte sWeedlePose200
.4byte sWeedlePose201
.4byte sWeedlePose202
.4byte sWeedlePose203
.4byte sWeedlePose204
.4byte sWeedlePose205
.4byte sWeedlePose206
.4byte sWeedlePose207
.4byte sWeedlePose208
.4byte sWeedlePose209
.4byte sWeedlePose210
.4byte sWeedlePose211
.4byte sWeedlePose212
.4byte sWeedlePose213
.4byte sWeedlePose214
.4byte sWeedlePose215
.4byte sWeedlePose216
.4byte sWeedlePose217
.4byte sWeedlePose218
.4byte sWeedlePose219
.4byte sWeedlePose220
.4byte sWeedlePose221
.4byte sWeedlePose222
.4byte sWeedlePose223
.4byte sWeedlePose224
.4byte sWeedlePose225
.4byte sWeedlePose226
.4byte sWeedlePose227
.4byte sWeedlePose228
.4byte sWeedlePose229
.4byte sWeedlePose230
.4byte sWeedlePose231
.4byte sWeedlePose232
.4byte sWeedlePose233
.4byte sWeedlePose234
.4byte sWeedlePose235
.4byte sWeedlePose236
.4byte sWeedlePose237
.4byte sWeedlePose238
.4byte sWeedlePose239
.4byte sWeedlePose240
.4byte sWeedlePose241
.4byte sWeedlePose242
.4byte sWeedlePose243
.4byte sWeedlePose244
.4byte sWeedlePose245
.4byte sWeedlePose246
.4byte sWeedlePose247
.4byte sWeedlePose248
.4byte sWeedlePose249
.4byte sWeedlePose250
.4byte sWeedlePose251
sAxPositionsWeedle:
.2byte   -1,   -8, 	  -3,   -5, 	   1,   -5, 	  -1,   -7
.2byte   -1,   -6, 	  -3,   -3, 	   1,   -3, 	  -1,   -5
.2byte   -1,   -7, 	  -3,   -4, 	   1,   -4, 	  -1,   -6
.2byte    7,  -10, 	   4,   -6, 	   1,   -5, 	   2,   -7
.2byte    8,   -8, 	   4,   -4, 	   1,   -3, 	   2,   -5
.2byte    7,   -9, 	   4,   -5, 	   1,   -4, 	   2,   -6
.2byte   10,  -13, 	   5,   -8, 	   4,   -6, 	   4,   -8
.2byte   11,  -11, 	   5,   -6, 	   4,   -4, 	   4,   -6
.2byte   10,  -12, 	   5,   -7, 	   4,   -5, 	   4,   -7
.2byte    8,  -16, 	   2,   -8, 	   5,   -7, 	   3,   -9
.2byte    8,  -14, 	   3,   -6, 	   5,   -5, 	   3,   -7
.2byte    9,  -15, 	   3,   -7, 	   5,   -6, 	   3,   -8
.2byte   -1,  -19, 	   1,   -9, 	  -3,   -9, 	  -1,   -9
.2byte   -1,  -17, 	   1,   -7, 	  -3,   -7, 	  -1,   -9
.2byte   -1,  -18, 	   1,   -7, 	  -3,   -7, 	  -1,   -9
.2byte  -10,  -16, 	  -4,   -8, 	  -7,   -7, 	  -5,   -9
.2byte  -10,  -14, 	  -5,   -6, 	  -7,   -5, 	  -5,   -7
.2byte  -11,  -15, 	  -5,   -7, 	  -7,   -6, 	  -5,   -8
.2byte  -12,  -13, 	  -7,   -8, 	  -6,   -6, 	  -6,   -8
.2byte  -13,  -11, 	  -7,   -6, 	  -6,   -4, 	  -6,   -6
.2byte  -12,  -12, 	  -7,   -7, 	  -6,   -5, 	  -6,   -7
.2byte   -9,  -10, 	  -6,   -6, 	  -3,   -5, 	  -4,   -7
.2byte  -10,   -8, 	  -6,   -4, 	  -3,   -3, 	  -4,   -5
.2byte   -9,   -9, 	  -6,   -5, 	  -3,   -4, 	  -4,   -6
.2byte   -1,   -8, 	  -3,   -5, 	   1,   -5, 	  -1,   -7
.2byte   -1,   -6, 	  -3,   -3, 	   1,   -3, 	  -1,   -5
.2byte   -1,   -7, 	  -3,   -4, 	   1,   -4, 	  -1,   -6
.2byte   -1,    3, 	  -3,   -2, 	   1,   -2, 	  -1,   -5
.2byte   -1,    1, 	  -3,   -4, 	   1,   -4, 	  -1,   -7
.2byte    7,  -10, 	   4,   -6, 	   1,   -5, 	   2,   -7
.2byte    8,   -8, 	   4,   -4, 	   1,   -3, 	   2,   -5
.2byte    7,   -9, 	   4,   -5, 	   1,   -4, 	   2,   -6
.2byte    7,    2, 	   2,   -1, 	   0,    0, 	  -1,   -3
.2byte   10,  -13, 	   5,   -8, 	   4,   -6, 	   4,   -8
.2byte   11,  -11, 	   5,   -6, 	   4,   -4, 	   4,   -6
.2byte   10,  -12, 	   5,   -7, 	   4,   -5, 	   4,   -7
.2byte   10,   -3, 	   2,   -4, 	   1,   -3, 	  -1,   -3
.2byte    8,  -16, 	   2,   -8, 	   5,   -7, 	   3,   -9
.2byte    8,  -14, 	   3,   -6, 	   5,   -5, 	   3,   -7
.2byte    9,  -15, 	   3,   -7, 	   5,   -6, 	   3,   -8
.2byte   10,   -6, 	   0,   -4, 	   2,   -3, 	  -2,   -2
.2byte   -1,  -19, 	   1,   -9, 	  -3,   -9, 	  -1,   -9
.2byte   -1,  -17, 	   1,   -7, 	  -3,   -7, 	  -1,   -9
.2byte   -1,  -18, 	   1,   -7, 	  -3,   -7, 	  -1,   -9
.2byte   -1,  -11, 	   1,   -5, 	  -3,   -5, 	  -1,   -4
.2byte  -10,  -16, 	  -4,   -8, 	  -7,   -7, 	  -5,   -9
.2byte  -10,  -14, 	  -5,   -6, 	  -7,   -5, 	  -5,   -7
.2byte  -11,  -15, 	  -5,   -7, 	  -7,   -6, 	  -5,   -8
.2byte  -12,   -6, 	  -2,   -4, 	  -4,   -3, 	   0,   -2
.2byte  -12,  -13, 	  -7,   -8, 	  -6,   -6, 	  -6,   -8
.2byte  -13,  -11, 	  -7,   -6, 	  -6,   -4, 	  -6,   -6
.2byte  -12,  -12, 	  -7,   -7, 	  -6,   -5, 	  -6,   -7
.2byte  -12,   -3, 	  -4,   -4, 	  -3,   -3, 	  -1,   -3
.2byte   -9,  -10, 	  -6,   -6, 	  -3,   -5, 	  -4,   -7
.2byte  -10,   -8, 	  -6,   -4, 	  -3,   -3, 	  -4,   -5
.2byte   -9,   -9, 	  -6,   -5, 	  -3,   -4, 	  -4,   -6
.2byte   -9,    2, 	  -4,   -1, 	  -2,    0, 	  -1,   -3
.2byte   -1,   -8, 	  -3,   -5, 	   1,   -5, 	  -1,   -7
.2byte   -1,   -6, 	  -3,   -3, 	   1,   -3, 	  -1,   -5
.2byte   -1,   -7, 	  -3,   -4, 	   1,   -4, 	  -1,   -6
.2byte   -1,    3, 	  -3,   -2, 	   1,   -2, 	  -1,   -5
.2byte   -1,    2, 	  -3,   -3, 	   1,   -3, 	  -1,   -6
.2byte    7,  -10, 	   4,   -6, 	   1,   -5, 	   2,   -7
.2byte    8,   -8, 	   4,   -4, 	   1,   -3, 	   2,   -5
.2byte    7,   -9, 	   4,   -5, 	   1,   -4, 	   2,   -6
.2byte    7,    2, 	   2,   -1, 	   0,    0, 	  -1,   -3
.2byte    7,    2, 	   2,   -1, 	   0,    0, 	  -1,   -3
.2byte   10,  -13, 	   5,   -8, 	   4,   -6, 	   4,   -8
.2byte   11,  -11, 	   5,   -6, 	   4,   -4, 	   4,   -6
.2byte   10,  -12, 	   5,   -7, 	   4,   -5, 	   4,   -7
.2byte   10,   -3, 	   2,   -4, 	   1,   -3, 	  -1,   -3
.2byte   10,   -3, 	   2,   -4, 	   1,   -3, 	  -1,   -3
.2byte    8,  -16, 	   2,   -8, 	   5,   -7, 	   3,   -9
.2byte    8,  -14, 	   3,   -6, 	   5,   -5, 	   3,   -7
.2byte    9,  -15, 	   3,   -7, 	   5,   -6, 	   3,   -8
.2byte   10,   -6, 	   0,   -4, 	   2,   -3, 	  -2,   -2
.2byte   10,   -6, 	   0,   -4, 	   2,   -3, 	  -2,   -2
.2byte   -1,  -19, 	   1,   -9, 	  -3,   -9, 	  -1,   -9
.2byte   -1,  -17, 	   1,   -7, 	  -3,   -7, 	  -1,   -9
.2byte   -1,  -18, 	   1,   -7, 	  -3,   -7, 	  -1,   -9
.2byte   -1,  -11, 	   1,   -5, 	  -3,   -5, 	  -1,   -4
.2byte   -1,  -11, 	   1,   -5, 	  -3,   -5, 	  -1,   -4
.2byte  -10,  -16, 	  -4,   -8, 	  -7,   -7, 	  -5,   -9
.2byte  -10,  -14, 	  -5,   -6, 	  -7,   -5, 	  -5,   -7
.2byte  -11,  -15, 	  -5,   -7, 	  -7,   -6, 	  -5,   -8
.2byte  -12,   -6, 	  -2,   -4, 	  -4,   -3, 	   0,   -2
.2byte  -12,   -6, 	  -2,   -4, 	  -4,   -3, 	   0,   -2
.2byte  -12,  -13, 	  -7,   -8, 	  -6,   -6, 	  -6,   -8
.2byte  -13,  -11, 	  -7,   -6, 	  -6,   -4, 	  -6,   -6
.2byte  -12,  -12, 	  -7,   -7, 	  -6,   -5, 	  -6,   -7
.2byte  -12,   -3, 	  -4,   -4, 	  -3,   -3, 	  -1,   -3
.2byte  -12,   -3, 	  -4,   -4, 	  -3,   -3, 	  -1,   -3
.2byte   -9,  -10, 	  -6,   -6, 	  -3,   -5, 	  -4,   -7
.2byte  -10,   -8, 	  -6,   -4, 	  -3,   -3, 	  -4,   -5
.2byte   -9,   -9, 	  -6,   -5, 	  -3,   -4, 	  -4,   -6
.2byte   -9,    2, 	  -4,   -1, 	  -2,    0, 	  -1,   -3
.2byte   -9,    2, 	  -4,   -1, 	  -2,    0, 	  -1,   -3
.2byte   -1,   -8, 	  -3,   -5, 	   1,   -5, 	  -1,   -7
.2byte    2,    1, 	  -4,   -3, 	  -1,   -3, 	   0,   -5
.2byte    2,    3, 	  -5,   -3, 	  -2,   -3, 	  -1,   -4
.2byte    7,  -10, 	   4,   -6, 	   1,   -5, 	   2,   -7
.2byte    5,    0, 	   3,   -4, 	   1,   -3, 	   0,   -4
.2byte    5,    2, 	   3,   -4, 	   1,   -3, 	   0,   -4
.2byte   10,  -13, 	   5,   -8, 	   4,   -6, 	   4,   -8
.2byte    7,   -5, 	  -1,   -7, 	  -2,   -5, 	  -3,   -6
.2byte    7,   -2, 	   0,   -7, 	  -1,   -5, 	  -2,   -6
.2byte    8,  -16, 	   2,   -8, 	   5,   -7, 	   3,   -9
.2byte    7,   -7, 	  -3,   -7, 	  -1,   -6, 	  -3,   -6
.2byte    7,   -5, 	  -3,   -6, 	  -1,   -5, 	  -3,   -5
.2byte   -1,  -19, 	   1,   -9, 	  -3,   -9, 	  -1,   -9
.2byte   -6,  -10, 	   2,   -2, 	   0,   -3, 	   1,   -4
.2byte   -6,   -7, 	   3,   -2, 	   1,   -3, 	   2,   -4
.2byte  -10,  -16, 	  -4,   -8, 	  -7,   -7, 	  -5,   -9
.2byte   -9,   -7, 	   1,   -7, 	  -1,   -6, 	   1,   -6
.2byte   -9,   -5, 	   1,   -6, 	  -1,   -5, 	   1,   -5
.2byte  -12,  -13, 	  -7,   -8, 	  -6,   -6, 	  -6,   -8
.2byte   -9,   -5, 	  -1,   -7, 	   0,   -5, 	   1,   -6
.2byte   -9,   -2, 	  -2,   -7, 	  -1,   -5, 	   0,   -6
.2byte   -9,  -10, 	  -6,   -6, 	  -3,   -5, 	  -4,   -7
.2byte   -5,    0, 	  -3,   -4, 	  -1,   -3, 	   0,   -4
.2byte   -5,    2, 	  -3,   -4, 	  -1,   -3, 	   0,   -4
.2byte   -1,   -8, 	  -3,   -5, 	   1,   -5, 	  -1,   -7
.2byte   -1,   -6, 	  -3,   -3, 	   1,   -3, 	  -1,   -5
.2byte   -1,   -7, 	  -3,   -4, 	   1,   -4, 	  -1,   -6
.2byte   -1,    3, 	  -3,   -2, 	   1,   -2, 	  -1,   -5
.2byte   -1,    2, 	  -3,   -3, 	   1,   -3, 	  -1,   -6
.2byte    7,  -10, 	   4,   -6, 	   1,   -5, 	   2,   -7
.2byte    8,   -8, 	   4,   -4, 	   1,   -3, 	   2,   -5
.2byte    7,   -9, 	   4,   -5, 	   1,   -4, 	   2,   -6
.2byte    7,    2, 	   2,   -1, 	   0,    0, 	  -1,   -3
.2byte    7,    2, 	   2,   -1, 	   0,    0, 	  -1,   -3
.2byte   10,  -13, 	   5,   -8, 	   4,   -6, 	   4,   -8
.2byte   11,  -11, 	   5,   -6, 	   4,   -4, 	   4,   -6
.2byte   10,  -12, 	   5,   -7, 	   4,   -5, 	   4,   -7
.2byte   10,   -3, 	   2,   -4, 	   1,   -3, 	  -1,   -3
.2byte   10,   -3, 	   2,   -4, 	   1,   -3, 	  -1,   -3
.2byte    8,  -16, 	   2,   -8, 	   5,   -7, 	   3,   -9
.2byte    8,  -14, 	   3,   -6, 	   5,   -5, 	   3,   -7
.2byte    9,  -15, 	   3,   -7, 	   5,   -6, 	   3,   -8
.2byte   10,   -6, 	   0,   -4, 	   2,   -3, 	  -2,   -2
.2byte   10,   -6, 	   0,   -4, 	   2,   -3, 	  -2,   -2
.2byte   -1,  -19, 	   1,   -9, 	  -3,   -9, 	  -1,   -9
.2byte   -1,  -17, 	   1,   -7, 	  -3,   -7, 	  -1,   -9
.2byte   -1,  -18, 	   1,   -7, 	  -3,   -7, 	  -1,   -9
.2byte   -1,  -11, 	   1,   -5, 	  -3,   -5, 	  -1,   -4
.2byte   -1,  -11, 	   1,   -5, 	  -3,   -5, 	  -1,   -4
.2byte  -10,  -16, 	  -4,   -8, 	  -7,   -7, 	  -5,   -9
.2byte  -10,  -14, 	  -5,   -6, 	  -7,   -5, 	  -5,   -7
.2byte  -11,  -15, 	  -5,   -7, 	  -7,   -6, 	  -5,   -8
.2byte  -12,   -6, 	  -2,   -4, 	  -4,   -3, 	   0,   -2
.2byte  -12,   -6, 	  -2,   -4, 	  -4,   -3, 	   0,   -2
.2byte  -12,  -13, 	  -7,   -8, 	  -6,   -6, 	  -6,   -8
.2byte  -13,  -11, 	  -7,   -6, 	  -6,   -4, 	  -6,   -6
.2byte  -12,  -12, 	  -7,   -7, 	  -6,   -5, 	  -6,   -7
.2byte  -12,   -3, 	  -4,   -4, 	  -3,   -3, 	  -1,   -3
.2byte  -12,   -3, 	  -4,   -4, 	  -3,   -3, 	  -1,   -3
.2byte   -9,  -10, 	  -6,   -6, 	  -3,   -5, 	  -4,   -7
.2byte  -10,   -8, 	  -6,   -4, 	  -3,   -3, 	  -4,   -5
.2byte   -9,   -9, 	  -6,   -5, 	  -3,   -4, 	  -4,   -6
.2byte   -9,    2, 	  -4,   -1, 	  -2,    0, 	  -1,   -3
.2byte   -9,    2, 	  -4,   -1, 	  -2,    0, 	  -1,   -3
.2byte   -6,   -6, 	   2,   -5, 	   1,   -4, 	   0,   -6
.2byte   -7,   -5, 	   2,   -5, 	   1,   -4, 	   0,   -6
.2byte   -1,  -12, 	  -3,   -7, 	   1,   -7, 	  -1,   -9
.2byte    0,  -14, 	   0,  -10, 	  -2,   -8, 	  -3,   -8
.2byte    3,  -17, 	   0,   -8, 	   0,   -7, 	  -2,   -8
.2byte    2,  -17, 	   1,   -8, 	   2,   -7, 	  -1,   -7
.2byte   -1,  -16, 	   1,   -5, 	  -3,   -5, 	  -1,   -6
.2byte   -3,  -17, 	  -2,   -8, 	  -3,   -7, 	   0,   -7
.2byte   -4,  -17, 	  -1,   -8, 	  -1,   -7, 	   1,   -8
.2byte   -1,  -14, 	  -1,  -10, 	   1,   -8, 	   2,   -8
.2byte   -1,   -8, 	  -3,   -5, 	   1,   -5, 	  -1,   -7
.2byte   -1,   -6, 	  -3,   -3, 	   1,   -3, 	  -1,   -5
.2byte   -1,   -7, 	  -3,   -4, 	   1,   -4, 	  -1,   -6
.2byte    7,  -10, 	   4,   -6, 	   1,   -5, 	   2,   -7
.2byte    8,   -8, 	   4,   -4, 	   1,   -3, 	   2,   -5
.2byte    7,   -9, 	   4,   -5, 	   1,   -4, 	   2,   -6
.2byte   10,  -13, 	   5,   -8, 	   4,   -6, 	   4,   -8
.2byte   11,  -11, 	   5,   -6, 	   4,   -4, 	   4,   -6
.2byte   10,  -12, 	   5,   -7, 	   4,   -5, 	   4,   -7
.2byte    8,  -16, 	   2,   -8, 	   5,   -7, 	   3,   -9
.2byte    8,  -14, 	   3,   -6, 	   5,   -5, 	   3,   -7
.2byte    9,  -15, 	   3,   -7, 	   5,   -6, 	   3,   -8
.2byte   -1,  -19, 	   1,   -9, 	  -3,   -9, 	  -1,   -9
.2byte   -1,  -17, 	   1,   -7, 	  -3,   -7, 	  -1,   -9
.2byte   -1,  -18, 	   1,   -7, 	  -3,   -7, 	  -1,   -9
.2byte  -10,  -16, 	  -4,   -8, 	  -7,   -7, 	  -5,   -9
.2byte  -10,  -14, 	  -5,   -6, 	  -7,   -5, 	  -5,   -7
.2byte  -11,  -15, 	  -5,   -7, 	  -7,   -6, 	  -5,   -8
.2byte  -12,  -13, 	  -7,   -8, 	  -6,   -6, 	  -6,   -8
.2byte  -13,  -11, 	  -7,   -6, 	  -6,   -4, 	  -6,   -6
.2byte  -12,  -12, 	  -7,   -7, 	  -6,   -5, 	  -6,   -7
.2byte   -9,  -10, 	  -6,   -6, 	  -3,   -5, 	  -4,   -7
.2byte  -10,   -8, 	  -6,   -4, 	  -3,   -3, 	  -4,   -5
.2byte   -9,   -9, 	  -6,   -5, 	  -3,   -4, 	  -4,   -6
.2byte   -1,    4, 	  -3,   -1, 	   1,   -1, 	  -1,   -4
.2byte   -9,    3, 	  -4,    0, 	  -2,    1, 	  -1,   -2
.2byte  -12,   -3, 	  -4,   -4, 	  -3,   -3, 	  -1,   -3
.2byte  -12,   -7, 	  -2,   -5, 	  -4,   -4, 	   0,   -3
.2byte   -1,  -11, 	   1,   -5, 	  -3,   -5, 	  -1,   -4
.2byte   10,   -7, 	   0,   -5, 	   2,   -4, 	  -2,   -3
.2byte   10,   -3, 	   2,   -4, 	   1,   -3, 	  -1,   -3
.2byte    7,    3, 	   2,    0, 	   0,    1, 	  -1,   -2
.2byte    2,    1, 	  -4,   -3, 	  -1,   -3, 	   0,   -5
.2byte    5,    0, 	   3,   -4, 	   1,   -3, 	   0,   -4
.2byte    7,   -5, 	  -1,   -7, 	  -2,   -5, 	  -3,   -6
.2byte    7,   -7, 	  -3,   -7, 	  -1,   -6, 	  -3,   -6
.2byte   -6,  -10, 	   2,   -2, 	   0,   -3, 	   1,   -4
.2byte   -9,   -7, 	   1,   -7, 	  -1,   -6, 	   1,   -6
.2byte   -9,   -5, 	  -1,   -7, 	   0,   -5, 	   1,   -6
.2byte   -5,    0, 	  -3,   -4, 	  -1,   -3, 	   0,   -4
.2byte   -1,   -6, 	  -3,   -3, 	   1,   -3, 	  -1,   -5
.2byte   -1,   -8, 	  -3,   -5, 	   1,   -5, 	  -1,   -7
.2byte   -1,    3, 	  -3,   -2, 	   1,   -2, 	  -1,   -5
.2byte    8,   -8, 	   4,   -4, 	   1,   -3, 	   2,   -5
.2byte    7,  -10, 	   4,   -6, 	   1,   -5, 	   2,   -7
.2byte    7,    2, 	   2,   -1, 	   0,    0, 	  -1,   -3
.2byte   11,  -11, 	   5,   -6, 	   4,   -4, 	   4,   -6
.2byte   10,  -13, 	   5,   -8, 	   4,   -6, 	   4,   -8
.2byte   10,   -3, 	   2,   -4, 	   1,   -3, 	  -1,   -3
.2byte    8,  -14, 	   3,   -6, 	   5,   -5, 	   3,   -7
.2byte    8,  -16, 	   2,   -8, 	   5,   -7, 	   3,   -9
.2byte   10,   -6, 	   0,   -4, 	   2,   -3, 	  -2,   -2
.2byte   -1,  -17, 	   1,   -7, 	  -3,   -7, 	  -1,   -9
.2byte   -1,  -19, 	   1,   -9, 	  -3,   -9, 	  -1,   -9
.2byte   -1,  -11, 	   1,   -5, 	  -3,   -5, 	  -1,   -4
.2byte  -10,  -14, 	  -5,   -6, 	  -7,   -5, 	  -5,   -7
.2byte  -10,  -16, 	  -4,   -8, 	  -7,   -7, 	  -5,   -9
.2byte  -12,   -6, 	  -2,   -4, 	  -4,   -3, 	   0,   -2
.2byte  -13,  -11, 	  -7,   -6, 	  -6,   -4, 	  -6,   -6
.2byte  -12,  -13, 	  -7,   -8, 	  -6,   -6, 	  -6,   -8
.2byte  -12,   -3, 	  -4,   -4, 	  -3,   -3, 	  -1,   -3
.2byte  -10,   -8, 	  -6,   -4, 	  -3,   -3, 	  -4,   -5
.2byte   -9,  -10, 	  -6,   -6, 	  -3,   -5, 	  -4,   -7
.2byte   -9,    2, 	  -4,   -1, 	  -2,    0, 	  -1,   -3
.2byte   -1,   -6, 	  -3,   -3, 	   1,   -3, 	  -1,   -5
.2byte  -10,   -7, 	  -6,   -3, 	  -3,   -2, 	  -4,   -4
.2byte  -11,  -10, 	  -5,   -5, 	  -4,   -3, 	  -4,   -5
.2byte   -8,  -13, 	  -3,   -5, 	  -5,   -4, 	  -3,   -6
.2byte   -1,  -16, 	   1,   -6, 	  -3,   -6, 	  -1,   -8
.2byte    6,  -13, 	   1,   -5, 	   3,   -4, 	   1,   -6
.2byte    9,  -10, 	   3,   -5, 	   2,   -3, 	   2,   -5
.2byte    8,   -7, 	   4,   -3, 	   1,   -2, 	   2,   -4
.2byte   -1,   -8, 	  -3,   -5, 	   1,   -5, 	  -1,   -7
.2byte   -9,  -10, 	  -6,   -6, 	  -3,   -5, 	  -4,   -7
.2byte  -12,  -13, 	  -7,   -8, 	  -6,   -6, 	  -6,   -8
.2byte  -10,  -16, 	  -4,   -8, 	  -7,   -7, 	  -5,   -9
.2byte   -1,  -19, 	   1,   -9, 	  -3,   -9, 	  -1,   -9
.2byte    8,  -16, 	   2,   -8, 	   5,   -7, 	   3,   -9
.2byte   10,  -13, 	   5,   -8, 	   4,   -6, 	   4,   -8
.2byte    7,  -10, 	   4,   -6, 	   1,   -5, 	   2,   -7
sWeedleAnimTable1:
.4byte sWeedleAnims_1_1
.4byte sWeedleAnims_1_2
.4byte sWeedleAnims_1_3
.4byte sWeedleAnims_1_4
.4byte sWeedleAnims_1_5
.4byte sWeedleAnims_1_6
.4byte sWeedleAnims_1_7
.4byte sWeedleAnims_1_8
sWeedleAnimTable2:
.4byte sWeedleAnims_2_1
.4byte sWeedleAnims_2_2
.4byte sWeedleAnims_2_3
.4byte sWeedleAnims_2_4
.4byte sWeedleAnims_2_5
.4byte sWeedleAnims_2_6
.4byte sWeedleAnims_2_7
.4byte sWeedleAnims_2_8
sWeedleAnimTable3:
.4byte sWeedleAnims_3_1
.4byte sWeedleAnims_3_2
.4byte sWeedleAnims_3_3
.4byte sWeedleAnims_3_4
.4byte sWeedleAnims_3_5
.4byte sWeedleAnims_3_6
.4byte sWeedleAnims_3_7
.4byte sWeedleAnims_3_8
sWeedleAnimTable4:
.4byte sWeedleAnims_4_1
.4byte sWeedleAnims_4_2
.4byte sWeedleAnims_4_3
.4byte sWeedleAnims_4_4
.4byte sWeedleAnims_4_5
.4byte sWeedleAnims_4_6
.4byte sWeedleAnims_4_7
.4byte sWeedleAnims_4_8
sWeedleAnimTable5:
.4byte sWeedleAnims_5_1
.4byte sWeedleAnims_5_2
.4byte sWeedleAnims_5_3
.4byte sWeedleAnims_5_4
.4byte sWeedleAnims_5_5
.4byte sWeedleAnims_5_6
.4byte sWeedleAnims_5_7
.4byte sWeedleAnims_5_8
sWeedleAnimTable6:
.4byte sWeedleAnims_6_1
.4byte sWeedleAnims_6_1
.4byte sWeedleAnims_6_1
.4byte sWeedleAnims_6_1
.4byte sWeedleAnims_6_1
.4byte sWeedleAnims_6_1
.4byte sWeedleAnims_6_1
.4byte sWeedleAnims_6_1
sWeedleAnimTable7:
.4byte sWeedleAnims_7_1
.4byte sWeedleAnims_7_2
.4byte sWeedleAnims_7_3
.4byte sWeedleAnims_7_4
.4byte sWeedleAnims_7_5
.4byte sWeedleAnims_7_6
.4byte sWeedleAnims_7_7
.4byte sWeedleAnims_7_8
sWeedleAnimTable8:
.4byte sWeedleAnims_8_1
.4byte sWeedleAnims_8_2
.4byte sWeedleAnims_8_3
.4byte sWeedleAnims_8_4
.4byte sWeedleAnims_8_5
.4byte sWeedleAnims_8_6
.4byte sWeedleAnims_8_7
.4byte sWeedleAnims_8_8
sWeedleAnimTable9:
.4byte sWeedleAnims_9_1
.4byte sWeedleAnims_9_2
.4byte sWeedleAnims_9_3
.4byte sWeedleAnims_9_4
.4byte sWeedleAnims_9_5
.4byte sWeedleAnims_9_6
.4byte sWeedleAnims_9_7
.4byte sWeedleAnims_9_8
sWeedleAnimTable10:
.4byte sWeedleAnims_10_1
.4byte sWeedleAnims_10_2
.4byte sWeedleAnims_10_3
.4byte sWeedleAnims_10_4
.4byte sWeedleAnims_10_5
.4byte sWeedleAnims_10_6
.4byte sWeedleAnims_10_7
.4byte sWeedleAnims_10_8
sWeedleAnimTable11:
.4byte sWeedleAnims_11_1
.4byte sWeedleAnims_11_2
.4byte sWeedleAnims_11_3
.4byte sWeedleAnims_11_4
.4byte sWeedleAnims_11_5
.4byte sWeedleAnims_11_6
.4byte sWeedleAnims_11_7
.4byte sWeedleAnims_11_8
sWeedleAnimTable12:
.4byte sWeedleAnims_12_1
.4byte sWeedleAnims_12_2
.4byte sWeedleAnims_12_3
.4byte sWeedleAnims_12_4
.4byte sWeedleAnims_12_5
.4byte sWeedleAnims_12_6
.4byte sWeedleAnims_12_7
.4byte sWeedleAnims_12_8
sWeedleAnimTable13:
.4byte sWeedleAnims_13_1
.4byte sWeedleAnims_13_2
.4byte sWeedleAnims_13_3
.4byte sWeedleAnims_13_4
.4byte sWeedleAnims_13_5
.4byte sWeedleAnims_13_6
.4byte sWeedleAnims_13_7
.4byte sWeedleAnims_13_8
sAxAnimationsWeedle:
.4byte sWeedleAnimTable1
.4byte sWeedleAnimTable2
.4byte sWeedleAnimTable3
.4byte sWeedleAnimTable4
.4byte sWeedleAnimTable5
.4byte sWeedleAnimTable6
.4byte sWeedleAnimTable7
.4byte sWeedleAnimTable8
.4byte sWeedleAnimTable9
.4byte sWeedleAnimTable10
.4byte sWeedleAnimTable11
.4byte sWeedleAnimTable12
.4byte sWeedleAnimTable13
sAxSpritesWeedle:
.4byte sWeedleSprites1
.4byte sWeedleSprites2
.4byte sWeedleSprites3
.4byte sWeedleSprites4
.4byte sWeedleSprites5
.4byte sWeedleSprites6
.4byte sWeedleSprites7
.4byte sWeedleSprites8
.4byte sWeedleSprites9
.4byte sWeedleSprites10
.4byte sWeedleSprites11
.4byte sWeedleSprites12
.4byte sWeedleSprites13
.4byte sWeedleSprites14
.4byte sWeedleSprites15
.4byte sWeedleSprites16
.4byte sWeedleSprites17
.4byte sWeedleSprites18
.4byte sWeedleSprites19
.4byte sWeedleSprites20
.4byte sWeedleSprites21
.4byte sWeedleSprites22
.4byte sWeedleSprites23
.4byte sWeedleSprites24
.4byte sWeedleSprites25
.4byte sWeedleSprites26
.4byte sWeedleSprites27
.4byte sWeedleSprites28
.4byte sWeedleSprites29
.4byte sWeedleSprites30
.4byte sWeedleSprites31
.4byte sWeedleSprites32
.4byte sWeedleSprites33
.4byte sWeedleSprites34
.4byte sWeedleSprites35
.4byte sWeedleSprites36
.4byte sWeedleSprites37
.4byte sWeedleSprites38
.4byte sWeedleSprites39
.4byte sWeedleSprites40
.4byte sWeedleSprites41
.4byte sWeedleSprites42
sAxMainWeedle:
ax_main sAxPosesWeedle, sAxAnimationsWeedle, 13, sAxSpritesWeedle, sAxPositionsWeedle
