.global gAxWooper
gAxWooper:
ax_siro sAxMainWooper
sWooperPose1:
ax_pose 0, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose2:
ax_pose 1, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose3:
ax_pose 2, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose4:
ax_pose 3, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose5:
ax_pose 4, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose6:
ax_pose 5, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose7:
ax_pose 6, 0x01ea, 0x80f0, 0x7c00
ax_pose_terminator
sWooperPose8:
ax_pose 7, 0x01ea, 0x80f0, 0x7c00
ax_pose_terminator
sWooperPose9:
ax_pose 8, 0x01ea, 0x80f0, 0x7c00
ax_pose_terminator
sWooperPose10:
ax_pose 9, 0x01ea, 0x80f2, 0x7c00
ax_pose_terminator
sWooperPose11:
ax_pose 10, 0x01ea, 0x80f2, 0x7c00
ax_pose_terminator
sWooperPose12:
ax_pose 11, 0x01ea, 0x80f2, 0x7c00
ax_pose_terminator
sWooperPose13:
ax_pose 12, 0x01ea, 0x80f0, 0x7c00
ax_pose_terminator
sWooperPose14:
ax_pose 13, 0x01ea, 0x80f0, 0x7c00
ax_pose_terminator
sWooperPose15:
ax_pose 14, 0x01ea, 0x80f0, 0x7c00
ax_pose_terminator
sWooperPose16:
ax_pose 15, 0x01eb, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose17:
ax_pose 16, 0x01eb, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose18:
ax_pose 17, 0x01eb, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose19:
ax_pose 18, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose20:
ax_pose 19, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose21:
ax_pose 20, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose22:
ax_pose 21, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose23:
ax_pose 22, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose24:
ax_pose 23, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose25:
ax_pose 0, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose26:
ax_pose 1, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose27:
ax_pose 2, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose28:
ax_pose 24, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose29:
ax_pose 3, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose30:
ax_pose 4, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose31:
ax_pose 5, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose32:
ax_pose 25, 0x01ea, 0x90ed, 0x7c00
ax_pose_terminator
sWooperPose33:
ax_pose 6, 0x01ea, 0x80f0, 0x7c00
ax_pose_terminator
sWooperPose34:
ax_pose 7, 0x01ea, 0x80f0, 0x7c00
ax_pose_terminator
sWooperPose35:
ax_pose 8, 0x01ea, 0x80f0, 0x7c00
ax_pose_terminator
sWooperPose36:
ax_pose 26, 0x81ea, 0x90f5, 0x7c00
ax_pose_terminator
sWooperPose37:
ax_pose 9, 0x01ea, 0x80f2, 0x7c00
ax_pose_terminator
sWooperPose38:
ax_pose 10, 0x01ea, 0x80f2, 0x7c00
ax_pose_terminator
sWooperPose39:
ax_pose 11, 0x01ea, 0x80f2, 0x7c00
ax_pose_terminator
sWooperPose40:
ax_pose 27, 0x81eb, 0x90f7, 0x7c00
ax_pose_terminator
sWooperPose41:
ax_pose 12, 0x01ea, 0x80f0, 0x7c00
ax_pose_terminator
sWooperPose42:
ax_pose 13, 0x01ea, 0x80f0, 0x7c00
ax_pose_terminator
sWooperPose43:
ax_pose 14, 0x01ea, 0x80f0, 0x7c00
ax_pose_terminator
sWooperPose44:
ax_pose 28, 0x01ea, 0x80f0, 0x7c00
ax_pose_terminator
sWooperPose45:
ax_pose 15, 0x01eb, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose46:
ax_pose 16, 0x01eb, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose47:
ax_pose 17, 0x01eb, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose48:
ax_pose 27, 0x81eb, 0x80fa, 0x7c00
ax_pose_terminator
sWooperPose49:
ax_pose 18, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose50:
ax_pose 19, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose51:
ax_pose 20, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose52:
ax_pose 26, 0x81ea, 0x80fc, 0x7c00
ax_pose_terminator
sWooperPose53:
ax_pose 21, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose54:
ax_pose 22, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose55:
ax_pose 23, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose56:
ax_pose 25, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose57:
ax_pose 0, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose58:
ax_pose 1, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose59:
ax_pose 2, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose60:
ax_pose 24, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose61:
ax_pose 3, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose62:
ax_pose 4, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose63:
ax_pose 5, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose64:
ax_pose 25, 0x01ea, 0x90ed, 0x7c00
ax_pose_terminator
sWooperPose65:
ax_pose 6, 0x01ea, 0x80f0, 0x7c00
ax_pose_terminator
sWooperPose66:
ax_pose 7, 0x01ea, 0x80f0, 0x7c00
ax_pose_terminator
sWooperPose67:
ax_pose 8, 0x01ea, 0x80f0, 0x7c00
ax_pose_terminator
sWooperPose68:
ax_pose 26, 0x81ea, 0x90f5, 0x7c00
ax_pose_terminator
sWooperPose69:
ax_pose 9, 0x01ea, 0x80f2, 0x7c00
ax_pose_terminator
sWooperPose70:
ax_pose 10, 0x01ea, 0x80f2, 0x7c00
ax_pose_terminator
sWooperPose71:
ax_pose 11, 0x01ea, 0x80f2, 0x7c00
ax_pose_terminator
sWooperPose72:
ax_pose 27, 0x81eb, 0x90f7, 0x7c00
ax_pose_terminator
sWooperPose73:
ax_pose 12, 0x01ea, 0x80f0, 0x7c00
ax_pose_terminator
sWooperPose74:
ax_pose 13, 0x01ea, 0x80f0, 0x7c00
ax_pose_terminator
sWooperPose75:
ax_pose 14, 0x01ea, 0x80f0, 0x7c00
ax_pose_terminator
sWooperPose76:
ax_pose 28, 0x01ea, 0x80f0, 0x7c00
ax_pose_terminator
sWooperPose77:
ax_pose 15, 0x01eb, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose78:
ax_pose 16, 0x01eb, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose79:
ax_pose 17, 0x01eb, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose80:
ax_pose 27, 0x81eb, 0x80fa, 0x7c00
ax_pose_terminator
sWooperPose81:
ax_pose 18, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose82:
ax_pose 19, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose83:
ax_pose 20, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose84:
ax_pose 26, 0x81ea, 0x80fc, 0x7c00
ax_pose_terminator
sWooperPose85:
ax_pose 21, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose86:
ax_pose 22, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose87:
ax_pose 23, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose88:
ax_pose 25, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose89:
ax_pose 0, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose90:
ax_pose 24, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose91:
ax_pose 29, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose92:
ax_pose 3, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose93:
ax_pose 25, 0x01ea, 0x90ed, 0x7c00
ax_pose_terminator
sWooperPose94:
ax_pose 30, 0x01ea, 0x90ed, 0x7c00
ax_pose_terminator
sWooperPose95:
ax_pose 6, 0x01ea, 0x80f0, 0x7c00
ax_pose_terminator
sWooperPose96:
ax_pose 26, 0x81ea, 0x90f5, 0x7c00
ax_pose_terminator
sWooperPose97:
ax_pose 31, 0x01ea, 0x90ed, 0x7c00
ax_pose_terminator
sWooperPose98:
ax_pose 9, 0x01ea, 0x80f2, 0x7c00
ax_pose_terminator
sWooperPose99:
ax_pose 27, 0x81eb, 0x90f7, 0x7c00
ax_pose_terminator
sWooperPose100:
ax_pose 32, 0x81eb, 0x90fa, 0x7c00
ax_pose_terminator
sWooperPose101:
ax_pose 12, 0x01ea, 0x80f0, 0x7c00
ax_pose_terminator
sWooperPose102:
ax_pose 28, 0x01ea, 0x80f0, 0x7c00
ax_pose_terminator
sWooperPose103:
ax_pose 33, 0x01ea, 0x80f0, 0x7c00
ax_pose_terminator
sWooperPose104:
ax_pose 15, 0x01eb, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose105:
ax_pose 27, 0x81eb, 0x80fa, 0x7c00
ax_pose_terminator
sWooperPose106:
ax_pose 32, 0x81eb, 0x80f7, 0x7c00
ax_pose_terminator
sWooperPose107:
ax_pose 18, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose108:
ax_pose 26, 0x81ea, 0x80fc, 0x7c00
ax_pose_terminator
sWooperPose109:
ax_pose 31, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose110:
ax_pose 21, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose111:
ax_pose 25, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose112:
ax_pose 30, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose113:
ax_pose 0, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose114:
ax_pose 24, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose115:
ax_pose 29, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose116:
ax_pose 3, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose117:
ax_pose 25, 0x01ea, 0x90ed, 0x7c00
ax_pose_terminator
sWooperPose118:
ax_pose 30, 0x01ea, 0x90ed, 0x7c00
ax_pose_terminator
sWooperPose119:
ax_pose 6, 0x01ea, 0x80f0, 0x7c00
ax_pose_terminator
sWooperPose120:
ax_pose 26, 0x81ea, 0x90f5, 0x7c00
ax_pose_terminator
sWooperPose121:
ax_pose 31, 0x01ea, 0x90ed, 0x7c00
ax_pose_terminator
sWooperPose122:
ax_pose 9, 0x01ea, 0x80f2, 0x7c00
ax_pose_terminator
sWooperPose123:
ax_pose 27, 0x81eb, 0x90f7, 0x7c00
ax_pose_terminator
sWooperPose124:
ax_pose 32, 0x81ec, 0x90fa, 0x7c00
ax_pose_terminator
sWooperPose125:
ax_pose 12, 0x01ea, 0x80f0, 0x7c00
ax_pose_terminator
sWooperPose126:
ax_pose 28, 0x01ea, 0x80f0, 0x7c00
ax_pose_terminator
sWooperPose127:
ax_pose 33, 0x01ea, 0x80f0, 0x7c00
ax_pose_terminator
sWooperPose128:
ax_pose 15, 0x01eb, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose129:
ax_pose 27, 0x81eb, 0x80fa, 0x7c00
ax_pose_terminator
sWooperPose130:
ax_pose 32, 0x81ec, 0x80f7, 0x7c00
ax_pose_terminator
sWooperPose131:
ax_pose 18, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose132:
ax_pose 26, 0x81ea, 0x80fc, 0x7c00
ax_pose_terminator
sWooperPose133:
ax_pose 31, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose134:
ax_pose 21, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose135:
ax_pose 25, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose136:
ax_pose 30, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose137:
ax_pose 34, 0x01ec, 0x80f5, 0x7c00
ax_pose_terminator
sWooperPose138:
ax_pose 35, 0x01ec, 0x80f5, 0x7c00
ax_pose_terminator
sWooperPose139:
ax_pose 36, 0x01e9, 0x80f0, 0x7c00
ax_pose_terminator
sWooperPose140:
ax_pose 37, 0x01e8, 0x90ed, 0x7c00
ax_pose_terminator
sWooperPose141:
ax_pose 38, 0x01eb, 0x90ec, 0x7c00
ax_pose_terminator
sWooperPose142:
ax_pose 39, 0x01eb, 0x90ee, 0x7c00
ax_pose_terminator
sWooperPose143:
ax_pose 40, 0x01e7, 0x80f0, 0x7c00
ax_pose_terminator
sWooperPose144:
ax_pose 39, 0x01eb, 0x80f2, 0x7c00
ax_pose_terminator
sWooperPose145:
ax_pose 38, 0x01eb, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose146:
ax_pose 37, 0x01e8, 0x80f3, 0x7c00
ax_pose_terminator
sWooperPose147:
ax_pose 0, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose148:
ax_pose 1, 0x01eb, 0x80f5, 0x7c00
ax_pose_terminator
sWooperPose149:
ax_pose 2, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose150:
ax_pose 3, 0x01ea, 0x80f3, 0x7c00
ax_pose_terminator
sWooperPose151:
ax_pose 4, 0x01ea, 0x80f6, 0x7c00
ax_pose_terminator
sWooperPose152:
ax_pose 5, 0x01eb, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose153:
ax_pose 6, 0x01ea, 0x80f0, 0x7c00
ax_pose_terminator
sWooperPose154:
ax_pose 7, 0x01ea, 0x80f1, 0x7c00
ax_pose_terminator
sWooperPose155:
ax_pose 8, 0x01eb, 0x80f1, 0x7c00
ax_pose_terminator
sWooperPose156:
ax_pose 9, 0x01ea, 0x80f2, 0x7c00
ax_pose_terminator
sWooperPose157:
ax_pose 10, 0x01ea, 0x80f2, 0x7c00
ax_pose_terminator
sWooperPose158:
ax_pose 11, 0x01eb, 0x80f2, 0x7c00
ax_pose_terminator
sWooperPose159:
ax_pose 12, 0x01ea, 0x80f0, 0x7c00
ax_pose_terminator
sWooperPose160:
ax_pose 13, 0x01ea, 0x80f0, 0x7c00
ax_pose_terminator
sWooperPose161:
ax_pose 14, 0x01eb, 0x80f0, 0x7c00
ax_pose_terminator
sWooperPose162:
ax_pose 15, 0x01eb, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose163:
ax_pose 16, 0x01ec, 0x80f5, 0x7c00
ax_pose_terminator
sWooperPose164:
ax_pose 17, 0x01eb, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose165:
ax_pose 18, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose166:
ax_pose 19, 0x01eb, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose167:
ax_pose 20, 0x01eb, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose168:
ax_pose 21, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose169:
ax_pose 22, 0x01eb, 0x80f3, 0x7c00
ax_pose_terminator
sWooperPose170:
ax_pose 23, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose171:
ax_pose 29, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose172:
ax_pose 30, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose173:
ax_pose 31, 0x01ea, 0x80f5, 0x7c00
ax_pose_terminator
sWooperPose174:
ax_pose 32, 0x81ec, 0x80f7, 0x7c00
ax_pose_terminator
sWooperPose175:
ax_pose 33, 0x01ea, 0x80f0, 0x7c00
ax_pose_terminator
sWooperPose176:
ax_pose 32, 0x81ec, 0x90fa, 0x7c00
ax_pose_terminator
sWooperPose177:
ax_pose 31, 0x01ea, 0x90ec, 0x7c00
ax_pose_terminator
sWooperPose178:
ax_pose 30, 0x01ea, 0x90ec, 0x7c00
ax_pose_terminator
sWooperPose179:
ax_pose 29, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose180:
ax_pose 30, 0x01ea, 0x90ec, 0x7c00
ax_pose_terminator
sWooperPose181:
ax_pose 31, 0x01ea, 0x90ec, 0x7c00
ax_pose_terminator
sWooperPose182:
ax_pose 32, 0x81ec, 0x90fa, 0x7c00
ax_pose_terminator
sWooperPose183:
ax_pose 33, 0x01ea, 0x80f0, 0x7c00
ax_pose_terminator
sWooperPose184:
ax_pose 32, 0x81ec, 0x80f7, 0x7c00
ax_pose_terminator
sWooperPose185:
ax_pose 31, 0x01ea, 0x80f5, 0x7c00
ax_pose_terminator
sWooperPose186:
ax_pose 30, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose187:
ax_pose 0, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose188:
ax_pose 24, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose189:
ax_pose 29, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose190:
ax_pose 21, 0x01ea, 0x90ec, 0x7c00
ax_pose_terminator
sWooperPose191:
ax_pose 25, 0x01ea, 0x90ed, 0x7c00
ax_pose_terminator
sWooperPose192:
ax_pose 30, 0x01ea, 0x90eb, 0x7c00
ax_pose_terminator
sWooperPose193:
ax_pose 18, 0x01ea, 0x90ed, 0x7c00
ax_pose_terminator
sWooperPose194:
ax_pose 26, 0x81ea, 0x90f6, 0x7c00
ax_pose_terminator
sWooperPose195:
ax_pose 31, 0x01ea, 0x90ea, 0x7c00
ax_pose_terminator
sWooperPose196:
ax_pose 15, 0x01eb, 0x90ed, 0x7c00
ax_pose_terminator
sWooperPose197:
ax_pose 27, 0x81eb, 0x90f7, 0x7c00
ax_pose_terminator
sWooperPose198:
ax_pose 32, 0x81eb, 0x90f9, 0x7c00
ax_pose_terminator
sWooperPose199:
ax_pose 12, 0x01ea, 0x80f0, 0x7c00
ax_pose_terminator
sWooperPose200:
ax_pose 28, 0x01ea, 0x80f0, 0x7c00
ax_pose_terminator
sWooperPose201:
ax_pose 33, 0x01ea, 0x80f0, 0x7c00
ax_pose_terminator
sWooperPose202:
ax_pose 15, 0x01eb, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose203:
ax_pose 27, 0x81eb, 0x80fa, 0x7c00
ax_pose_terminator
sWooperPose204:
ax_pose 32, 0x81eb, 0x80f7, 0x7c00
ax_pose_terminator
sWooperPose205:
ax_pose 18, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose206:
ax_pose 26, 0x81ea, 0x80fb, 0x7c00
ax_pose_terminator
sWooperPose207:
ax_pose 31, 0x01ea, 0x80f7, 0x7c00
ax_pose_terminator
sWooperPose208:
ax_pose 21, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose209:
ax_pose 25, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose210:
ax_pose 30, 0x01ea, 0x80f6, 0x7c00
ax_pose_terminator
sWooperPose211:
ax_pose 24, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose212:
ax_pose 25, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose213:
ax_pose 26, 0x81ea, 0x80fb, 0x7c00
ax_pose_terminator
sWooperPose214:
ax_pose 27, 0x81ea, 0x80fa, 0x7c00
ax_pose_terminator
sWooperPose215:
ax_pose 28, 0x01ea, 0x80f0, 0x7c00
ax_pose_terminator
sWooperPose216:
ax_pose 27, 0x81ea, 0x90f7, 0x7c00
ax_pose_terminator
sWooperPose217:
ax_pose 26, 0x81ea, 0x90f5, 0x7c00
ax_pose_terminator
sWooperPose218:
ax_pose 25, 0x01ea, 0x90ed, 0x7c00
ax_pose_terminator
sWooperPose219:
ax_pose 0, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose220:
ax_pose 21, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose221:
ax_pose 18, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose222:
ax_pose 15, 0x01eb, 0x80f4, 0x7c00
ax_pose_terminator
sWooperPose223:
ax_pose 12, 0x01ea, 0x80f0, 0x7c00
ax_pose_terminator
sWooperPose224:
ax_pose 9, 0x01ea, 0x80f2, 0x7c00
ax_pose_terminator
sWooperPose225:
ax_pose 6, 0x01ea, 0x80f0, 0x7c00
ax_pose_terminator
sWooperPose226:
ax_pose 3, 0x01ea, 0x80f4, 0x7c00
ax_pose_terminator
.align 2
sWooperAnims_1_1:
ax_anim 8, 0, 0, 0, 0, 0, 0,
ax_anim 6, 0, 1, 1, -1, 0, 0,
ax_anim 6, 0, 1, 1, -2, 0, 0,
ax_anim 6, 0, 1, 1, -1, 0, 0,
ax_anim 8, 0, 0, 0, 0, 0, 0,
ax_anim 6, 0, 2, -1, -1, 0, 0,
ax_anim 6, 0, 2, -1, -2, 0, 0,
ax_anim 6, 0, 2, -1, -1, 0, 0,
ax_anim_terminator
sWooperAnims_1_2:
ax_anim 8, 0, 3, 0, 0, 0, 0,
ax_anim 6, 0, 4, 1, -1, 1, -1,
ax_anim 6, 0, 4, 1, -2, 1, -1,
ax_anim 6, 0, 4, 1, -1, 1, -1,
ax_anim 8, 0, 3, 0, 0, 0, 0,
ax_anim 6, 0, 5, -1, -1, -1, 1,
ax_anim 6, 0, 5, -1, -2, -1, 1,
ax_anim 6, 0, 5, -1, -1, -1, 1,
ax_anim_terminator
sWooperAnims_1_3:
ax_anim 8, 0, 6, 0, 0, 0, 0,
ax_anim 6, 0, 7, 0, -1, 0, 0,
ax_anim 6, 0, 7, 0, -2, 0, 0,
ax_anim 6, 0, 7, 0, -1, 0, 0,
ax_anim 8, 0, 6, 0, 0, 0, 0,
ax_anim 6, 0, 8, 0, -1, 0, 0,
ax_anim 6, 0, 8, 0, -2, 0, 0,
ax_anim 6, 0, 8, 0, -1, 0, 0,
ax_anim_terminator
sWooperAnims_1_4:
ax_anim 8, 0, 9, 0, 0, 0, 0,
ax_anim 6, 0, 10, -1, -1, -1, -1,
ax_anim 6, 0, 10, -1, -2, -1, -1,
ax_anim 6, 0, 10, -1, -1, -1, -1,
ax_anim 8, 0, 9, 0, 0, 0, 0,
ax_anim 6, 0, 11, 1, -1, 1, 1,
ax_anim 6, 0, 11, 1, -2, 1, 1,
ax_anim 6, 0, 11, 1, -1, 1, 1,
ax_anim_terminator
sWooperAnims_1_5:
ax_anim 8, 0, 12, 0, 0, 0, 0,
ax_anim 6, 0, 13, 0, -1, 0, 0,
ax_anim 6, 0, 13, 0, -2, 0, 0,
ax_anim 6, 0, 13, 0, -1, 0, 0,
ax_anim 8, 0, 12, 0, 0, 0, 0,
ax_anim 6, 0, 14, 0, -1, 0, 0,
ax_anim 6, 0, 14, 0, -2, 0, 0,
ax_anim 6, 0, 14, 0, -1, 0, 0,
ax_anim_terminator
sWooperAnims_1_6:
ax_anim 8, 0, 15, 0, 0, 0, 0,
ax_anim 6, 0, 16, -1, -1, -1, 1,
ax_anim 6, 0, 16, -1, -2, -1, 1,
ax_anim 6, 0, 16, -1, -1, -1, 1,
ax_anim 8, 0, 15, 0, 0, 0, 0,
ax_anim 6, 0, 17, 1, -1, 1, -1,
ax_anim 6, 0, 17, 1, -2, 1, -1,
ax_anim 6, 0, 17, 1, -1, 1, -1,
ax_anim_terminator
sWooperAnims_1_7:
ax_anim 8, 0, 18, 0, 0, 0, 0,
ax_anim 6, 0, 19, 0, -1, 0, 0,
ax_anim 6, 0, 19, 0, -2, 0, 0,
ax_anim 6, 0, 19, 0, -1, 0, 0,
ax_anim 8, 0, 18, 0, 0, 0, 0,
ax_anim 6, 0, 20, 0, -1, 0, 0,
ax_anim 6, 0, 20, 0, -2, 0, 0,
ax_anim 6, 0, 20, 0, -1, 0, 0,
ax_anim_terminator
sWooperAnims_1_8:
ax_anim 8, 0, 21, 0, 0, 0, 0,
ax_anim 6, 0, 22, 1, -1, 1, 1,
ax_anim 6, 0, 22, 1, -2, 1, 1,
ax_anim 6, 0, 22, 1, -1, 1, 1,
ax_anim 8, 0, 21, 0, 0, 0, 0,
ax_anim 6, 0, 23, -1, -1, -1, -1,
ax_anim 6, 0, 23, -1, -2, -1, -1,
ax_anim 6, 0, 23, -1, -1, -1, -1,
ax_anim_terminator
.align 2
sWooperAnims_2_1:
ax_anim 2, 0, 24, 0, -1, 0, -1,
ax_anim 6, 0, 24, 0, -2, 0, -2,
ax_anim 1, 0, 26, 0, 0, 0, 0,
ax_anim 1, 2, 25, 0, 4, 0, 4,
ax_anim 1, 0, 26, 0, 10, 0, 10,
ax_anim 2, 0, 27, 0, 20, 0, 20,
ax_anim 2, 1, 27, 1, 20, 1, 20,
ax_anim 2, 0, 27, 0, 20, 0, 20,
ax_anim 2, 0, 27, 1, 20, 1, 20,
ax_anim 2, 0, 24, 0, 6, 0, 6,
ax_anim_terminator
sWooperAnims_2_2:
ax_anim 2, 0, 28, -1, -1, -1, -1,
ax_anim 6, 0, 28, -2, -2, -2, -2,
ax_anim 1, 0, 30, 0, 0, 0, 0,
ax_anim 1, 2, 29, 4, 4, 4, 4,
ax_anim 1, 0, 30, 11, 10, 11, 10,
ax_anim 2, 0, 31, 23, 20, 23, 20,
ax_anim 2, 1, 31, 24, 19, 24, 19,
ax_anim 2, 0, 31, 23, 20, 23, 20,
ax_anim 2, 0, 31, 24, 19, 24, 19,
ax_anim 2, 0, 28, 6, 6, 6, 6,
ax_anim_terminator
sWooperAnims_2_3:
ax_anim 2, 0, 32, -1, 0, -1, 0,
ax_anim 6, 0, 32, -2, 0, -2, 0,
ax_anim 1, 0, 34, 0, 0, 0, 0,
ax_anim 1, 2, 33, 4, 0, 4, 0,
ax_anim 1, 0, 34, 10, 0, 10, 0,
ax_anim 2, 0, 35, 24, 0, 24, 0,
ax_anim 2, 1, 35, 24, 1, 24, 1,
ax_anim 2, 0, 35, 24, 0, 24, 0,
ax_anim 2, 0, 35, 24, 1, 24, 1,
ax_anim 2, 0, 32, 6, 0, 6, 0,
ax_anim_terminator
sWooperAnims_2_4:
ax_anim 2, 0, 36, -1, 1, -1, 1,
ax_anim 6, 0, 36, -2, 2, -2, 2,
ax_anim 1, 0, 38, 0, -1, 0, -1,
ax_anim 1, 2, 37, 4, -4, 4, -4,
ax_anim 1, 0, 38, 10, -10, 10, -10,
ax_anim 2, 0, 39, 22, -23, 22, -23,
ax_anim 2, 1, 39, 23, -22, 23, -22,
ax_anim 2, 0, 39, 22, -23, 22, -23,
ax_anim 2, 0, 39, 23, -22, 23, -22,
ax_anim 2, 0, 36, 6, -6, 6, -6,
ax_anim_terminator
sWooperAnims_2_5:
ax_anim 2, 0, 40, 0, 1, 0, 1,
ax_anim 6, 0, 40, 0, 2, 0, 2,
ax_anim 1, 0, 42, 0, 0, 0, 0,
ax_anim 1, 2, 41, 0, -4, 0, -4,
ax_anim 1, 0, 42, 0, -11, 0, -11,
ax_anim 2, 0, 43, 0, -23, 0, -23,
ax_anim 2, 1, 43, 1, -23, 1, -23,
ax_anim 2, 0, 43, 0, -23, 0, -23,
ax_anim 2, 0, 43, 1, -23, 1, -23,
ax_anim 2, 0, 40, 0, -6, 0, -6,
ax_anim_terminator
sWooperAnims_2_6:
ax_anim 2, 0, 44, 1, 1, 1, 1,
ax_anim 6, 0, 44, 2, 2, 2, 2,
ax_anim 1, 0, 46, 0, -1, 0, -1,
ax_anim 1, 2, 45, -4, -4, -4, -4,
ax_anim 1, 0, 46, -10, -10, -10, -10,
ax_anim 2, 0, 47, -22, -23, -22, -23,
ax_anim 2, 1, 47, -23, -22, -23, -22,
ax_anim 2, 0, 47, -22, -23, -22, -23,
ax_anim 2, 0, 47, -23, -22, -23, -22,
ax_anim 2, 0, 44, -6, -6, -6, -6,
ax_anim_terminator
sWooperAnims_2_7:
ax_anim 2, 0, 48, 1, 0, 1, 0,
ax_anim 6, 0, 48, 2, 0, 2, 0,
ax_anim 1, 0, 50, 0, 0, 0, 0,
ax_anim 1, 2, 49, -4, 0, -4, 0,
ax_anim 1, 0, 50, -10, 0, -10, 0,
ax_anim 2, 0, 51, -24, 0, -24, 0,
ax_anim 2, 1, 51, -24, 1, -24, 1,
ax_anim 2, 0, 51, -24, 0, -24, 0,
ax_anim 2, 0, 51, -24, 1, -24, 1,
ax_anim 2, 0, 48, -6, 0, -6, 0,
ax_anim_terminator
sWooperAnims_2_8:
ax_anim 2, 0, 52, 1, -1, 1, -1,
ax_anim 6, 0, 52, 2, -2, 2, -2,
ax_anim 1, 0, 54, 0, 0, 0, 0,
ax_anim 1, 2, 53, -4, 4, -4, 4,
ax_anim 1, 0, 54, -11, 10, -11, 10,
ax_anim 2, 0, 55, -23, 20, -23, 20,
ax_anim 2, 1, 55, -24, 19, -24, 19,
ax_anim 2, 0, 55, -23, 20, -23, 20,
ax_anim 2, 0, 55, -24, 19, -24, 19,
ax_anim 2, 0, 52, -6, 6, -6, 6,
ax_anim_terminator
.align 2
sWooperAnims_3_1:
ax_anim 2, 0, 56, 0, -1, 0, -1,
ax_anim 6, 0, 56, 0, -2, 0, -2,
ax_anim 1, 0, 58, 0, 0, 0, 0,
ax_anim 1, 2, 57, 0, 4, 0, 4,
ax_anim 1, 0, 58, 0, 10, 0, 10,
ax_anim 2, 0, 59, 0, 20, 0, 20,
ax_anim 2, 1, 59, 1, 20, 1, 20,
ax_anim 2, 0, 59, 0, 20, 0, 20,
ax_anim 2, 0, 59, 1, 20, 1, 20,
ax_anim 2, 0, 56, 0, 6, 0, 6,
ax_anim_terminator
sWooperAnims_3_2:
ax_anim 2, 0, 60, -1, -1, -1, -1,
ax_anim 6, 0, 60, -2, -2, -2, -2,
ax_anim 1, 0, 62, 0, 0, 0, 0,
ax_anim 1, 2, 61, 4, 4, 4, 4,
ax_anim 1, 0, 62, 11, 10, 11, 10,
ax_anim 2, 0, 63, 23, 20, 23, 20,
ax_anim 2, 1, 63, 24, 19, 24, 19,
ax_anim 2, 0, 63, 23, 20, 23, 20,
ax_anim 2, 0, 63, 24, 19, 24, 19,
ax_anim 2, 0, 60, 6, 6, 6, 6,
ax_anim_terminator
sWooperAnims_3_3:
ax_anim 2, 0, 64, -1, 0, -1, 0,
ax_anim 6, 0, 64, -2, 0, -2, 0,
ax_anim 1, 0, 66, 0, 0, 0, 0,
ax_anim 1, 2, 65, 4, 0, 4, 0,
ax_anim 1, 0, 66, 10, 0, 10, 0,
ax_anim 2, 0, 67, 24, 0, 24, 0,
ax_anim 2, 1, 67, 24, 1, 24, 1,
ax_anim 2, 0, 67, 24, 0, 24, 0,
ax_anim 2, 0, 67, 24, 1, 24, 1,
ax_anim 2, 0, 64, 6, 0, 6, 0,
ax_anim_terminator
sWooperAnims_3_4:
ax_anim 2, 0, 68, -1, 1, -1, 1,
ax_anim 6, 0, 68, -2, 2, -2, 2,
ax_anim 1, 0, 70, 0, -1, 0, -1,
ax_anim 1, 2, 69, 4, -4, 4, -4,
ax_anim 1, 0, 70, 10, -10, 10, -10,
ax_anim 2, 0, 71, 22, -23, 22, -23,
ax_anim 2, 1, 71, 23, -22, 23, -22,
ax_anim 2, 0, 71, 22, -23, 22, -23,
ax_anim 2, 0, 71, 23, -22, 23, -22,
ax_anim 2, 0, 68, 6, -6, 6, -6,
ax_anim_terminator
sWooperAnims_3_5:
ax_anim 2, 0, 72, 0, 1, 0, 1,
ax_anim 6, 0, 72, 0, 2, 0, 2,
ax_anim 1, 0, 74, 0, 0, 0, 0,
ax_anim 1, 2, 73, 0, -4, 0, -4,
ax_anim 1, 0, 74, 0, -11, 0, -11,
ax_anim 2, 0, 75, 0, -23, 0, -23,
ax_anim 2, 1, 75, 1, -23, 1, -23,
ax_anim 2, 0, 75, 0, -23, 0, -23,
ax_anim 2, 0, 75, 1, -23, 1, -23,
ax_anim 2, 0, 72, 0, -6, 0, -6,
ax_anim_terminator
sWooperAnims_3_6:
ax_anim 2, 0, 76, 1, 1, 1, 1,
ax_anim 6, 0, 76, 2, 2, 2, 2,
ax_anim 1, 0, 78, 0, -1, 0, -1,
ax_anim 1, 2, 77, -4, -4, -4, -4,
ax_anim 1, 0, 78, -10, -10, -10, -10,
ax_anim 2, 0, 79, -22, -23, -22, -23,
ax_anim 2, 1, 79, -23, -22, -23, -22,
ax_anim 2, 0, 79, -22, -23, -22, -23,
ax_anim 2, 0, 79, -23, -22, -23, -22,
ax_anim 2, 0, 76, -6, -6, -6, -6,
ax_anim_terminator
sWooperAnims_3_7:
ax_anim 2, 0, 80, 1, 0, 1, 0,
ax_anim 6, 0, 80, 2, 0, 2, 0,
ax_anim 1, 0, 82, 0, 0, 0, 0,
ax_anim 1, 2, 81, -4, 0, -4, 0,
ax_anim 1, 0, 82, -10, 0, -10, 0,
ax_anim 2, 0, 83, -24, 0, -24, 0,
ax_anim 2, 1, 83, -24, 1, -24, 1,
ax_anim 2, 0, 83, -24, 0, -24, 0,
ax_anim 2, 0, 83, -24, 1, -24, 1,
ax_anim 2, 0, 80, -6, 0, -6, 0,
ax_anim_terminator
sWooperAnims_3_8:
ax_anim 2, 0, 84, 1, -1, 1, -1,
ax_anim 6, 0, 84, 2, -2, 2, -2,
ax_anim 1, 0, 86, 0, 0, 0, 0,
ax_anim 1, 2, 85, -4, 4, -4, 4,
ax_anim 1, 0, 86, -11, 10, -11, 10,
ax_anim 2, 0, 87, -23, 20, -23, 20,
ax_anim 2, 1, 87, -24, 19, -24, 19,
ax_anim 2, 0, 87, -23, 20, -23, 20,
ax_anim 2, 0, 87, -24, 19, -24, 19,
ax_anim 2, 0, 84, -6, 6, -6, 6,
ax_anim_terminator
.align 2
sWooperAnims_4_1:
ax_anim 2, 0, 88, 0, -1, 0, -1,
ax_anim 6, 2, 89, 0, -3, 0, -3,
ax_anim 1, 0, 90, 0, -2, 0, -2,
ax_anim 2, 0, 90, 0, 1, 0, 0,
ax_anim 2, 1, 90, -1, 1, -1, 0,
ax_anim 2, 0, 90, 0, 1, 0, 0,
ax_anim 2, 0, 90, -1, 1, -1, 0,
ax_anim 2, 0, 90, 0, 1, 0, 0,
ax_anim 2, 0, 90, -1, 1, -1, 0,
ax_anim 2, 0, 88, 0, 1, -1, 0,
ax_anim_terminator
sWooperAnims_4_2:
ax_anim 2, 0, 91, -1, -1, -1, -1,
ax_anim 6, 2, 92, -3, -3, -3, -3,
ax_anim 1, 0, 93, -2, -2, -2, -2,
ax_anim 2, 0, 93, 1, 1, 1, 1,
ax_anim 2, 1, 93, 0, 2, 0, 2,
ax_anim 2, 0, 93, 1, 1, 1, 1,
ax_anim 2, 0, 93, 0, 2, 0, 2,
ax_anim 2, 0, 93, 1, 1, 1, 1,
ax_anim 2, 0, 93, 0, 2, 0, 2,
ax_anim 2, 0, 91, 1, 1, 1, 1,
ax_anim_terminator
sWooperAnims_4_3:
ax_anim 2, 0, 94, -1, 0, -1, 0,
ax_anim 6, 2, 95, -3, 0, -3, 0,
ax_anim 1, 0, 96, -2, 0, -2, 0,
ax_anim 2, 0, 96, 1, 0, 1, 0,
ax_anim 2, 1, 96, 1, -1, 1, -1,
ax_anim 2, 0, 96, 1, 0, 1, 0,
ax_anim 2, 0, 96, 1, -1, 1, -1,
ax_anim 2, 0, 96, 1, 0, 1, 0,
ax_anim 2, 0, 96, 1, -1, 1, -1,
ax_anim 2, 0, 94, 1, 0, 1, 0,
ax_anim_terminator
sWooperAnims_4_4:
ax_anim 2, 0, 97, -1, 1, -1, 1,
ax_anim 6, 2, 98, -3, 3, -3, 3,
ax_anim 1, 0, 99, -2, 2, -2, 2,
ax_anim 2, 0, 99, 1, -1, 1, -1,
ax_anim 2, 1, 99, 0, -2, 0, -2,
ax_anim 2, 0, 99, 1, -1, 1, -1,
ax_anim 2, 0, 99, 0, -2, 0, -2,
ax_anim 2, 0, 99, 1, -1, 1, -1,
ax_anim 2, 0, 99, 0, -2, 0, -2,
ax_anim 2, 0, 97, 1, -1, 1, -1,
ax_anim_terminator
sWooperAnims_4_5:
ax_anim 2, 0, 100, 0, 1, 0, 1,
ax_anim 6, 2, 101, 0, 3, 0, 3,
ax_anim 1, 0, 102, 0, 2, 0, 2,
ax_anim 2, 0, 102, 0, -1, 0, 0,
ax_anim 2, 1, 102, -1, -1, -1, 0,
ax_anim 2, 0, 102, 0, -1, 0, 0,
ax_anim 2, 0, 102, -1, -1, -1, 0,
ax_anim 2, 0, 102, 0, -1, 0, 0,
ax_anim 2, 0, 102, -1, -1, -1, 0,
ax_anim 2, 0, 100, 0, -1, -1, 0,
ax_anim_terminator
sWooperAnims_4_6:
ax_anim 2, 0, 103, 1, 1, 1, 1,
ax_anim 6, 2, 104, 3, 3, 3, 3,
ax_anim 1, 0, 105, 2, 2, 2, 2,
ax_anim 2, 0, 105, -1, -1, -1, -1,
ax_anim 2, 1, 105, 0, -2, 0, -2,
ax_anim 2, 0, 105, -1, -1, -1, -1,
ax_anim 2, 0, 105, 0, -2, 0, -2,
ax_anim 2, 0, 105, -1, -1, -1, -1,
ax_anim 2, 0, 105, 0, -2, 0, -2,
ax_anim 2, 0, 103, -1, -1, -1, -1,
ax_anim_terminator
sWooperAnims_4_7:
ax_anim 2, 0, 106, 1, 0, 1, 0,
ax_anim 6, 2, 107, 3, 0, 3, 0,
ax_anim 1, 0, 108, 2, 0, 2, 0,
ax_anim 2, 0, 108, -1, 0, -1, 0,
ax_anim 2, 1, 108, -1, -1, -1, -1,
ax_anim 2, 0, 108, -1, 0, -1, 0,
ax_anim 2, 0, 108, -1, -1, -1, -1,
ax_anim 2, 0, 108, -1, 0, -1, 0,
ax_anim 2, 0, 108, -1, -1, -1, -1,
ax_anim 2, 0, 106, -1, 0, -1, 0,
ax_anim_terminator
sWooperAnims_4_8:
ax_anim 2, 0, 109, 1, -1, 1, -1,
ax_anim 6, 2, 110, 3, -3, 3, -3,
ax_anim 1, 0, 111, 2, -2, 2, -2,
ax_anim 2, 0, 111, -1, 1, -1, 1,
ax_anim 2, 1, 111, 0, 2, 0, 2,
ax_anim 2, 0, 111, -1, 1, -1, 1,
ax_anim 2, 0, 111, 0, 2, 0, 2,
ax_anim 2, 0, 111, -1, 1, -1, 1,
ax_anim 2, 0, 111, 0, 2, 0, 2,
ax_anim 2, 0, 109, -1, 1, -1, 1,
ax_anim_terminator
.align 2
sWooperAnims_5_1:
ax_anim 2, 0, 112, 0, -1, 0, -1,
ax_anim 6, 2, 113, 0, -3, 0, -3,
ax_anim 2, 0, 114, 0, 0, 0, 0,
ax_anim 3, 0, 117, 0, 0, 0, 0,
ax_anim 3, 1, 120, 0, 0, 0, 0,
ax_anim 3, 0, 123, 0, 0, 0, 0,
ax_anim 3, 0, 126, 0, 0, 0, 0,
ax_anim 3, 0, 129, 0, 0, 0, 0,
ax_anim 3, 0, 132, 0, 0, 0, 0,
ax_anim 3, 0, 135, 0, 0, 0, 0,
ax_anim_terminator
sWooperAnims_5_2:
ax_anim 2, 0, 115, -1, -1, -1, -1,
ax_anim 6, 2, 116, -3, -3, -3, -3,
ax_anim 2, 0, 117, 0, 0, 0, 0,
ax_anim 3, 0, 120, 0, 0, 0, 0,
ax_anim 3, 1, 123, 0, 0, 0, 0,
ax_anim 3, 0, 126, 0, 0, 0, 0,
ax_anim 3, 0, 129, 0, 0, 0, 0,
ax_anim 3, 0, 132, 0, 0, 0, 0,
ax_anim 3, 0, 135, 0, 0, 0, 0,
ax_anim 3, 0, 114, 0, 0, 0, 0,
ax_anim_terminator
sWooperAnims_5_3:
ax_anim 2, 0, 118, -1, 0, -1, 0,
ax_anim 6, 2, 119, -3, 0, -3, 0,
ax_anim 2, 0, 120, 0, 0, 0, 0,
ax_anim 3, 0, 123, 0, 0, 0, 0,
ax_anim 3, 1, 126, 0, 0, 0, 0,
ax_anim 3, 0, 129, 0, 0, 0, 0,
ax_anim 3, 0, 132, 0, 0, 0, 0,
ax_anim 3, 0, 135, 0, 0, 0, 0,
ax_anim 3, 0, 114, 0, 0, 0, 0,
ax_anim 3, 0, 117, 0, 0, 0, 0,
ax_anim_terminator
sWooperAnims_5_4:
ax_anim 2, 0, 121, -1, 1, -1, 1,
ax_anim 6, 2, 122, -3, 3, -3, 3,
ax_anim 2, 0, 123, 0, 0, 0, 0,
ax_anim 3, 0, 126, 0, 0, 0, 0,
ax_anim 3, 1, 129, 0, 0, 0, 0,
ax_anim 3, 0, 132, 0, 0, 0, 0,
ax_anim 3, 0, 135, 0, 0, 0, 0,
ax_anim 3, 0, 114, 0, 0, 0, 0,
ax_anim 3, 0, 117, 0, 0, 0, 0,
ax_anim 3, 0, 120, 0, 0, 0, 0,
ax_anim_terminator
sWooperAnims_5_5:
ax_anim 2, 0, 124, 0, 1, 0, 1,
ax_anim 6, 2, 125, 0, 3, 0, 3,
ax_anim 2, 0, 126, 0, 0, 0, 0,
ax_anim 3, 0, 129, 0, 0, 0, 0,
ax_anim 3, 1, 132, 0, 0, 0, 0,
ax_anim 3, 0, 135, 0, 0, 0, 0,
ax_anim 3, 0, 114, 0, 0, 0, 0,
ax_anim 3, 0, 117, 0, 0, 0, 0,
ax_anim 3, 0, 120, 0, 0, 0, 0,
ax_anim 3, 0, 123, 0, 0, 0, 0,
ax_anim_terminator
sWooperAnims_5_6:
ax_anim 2, 0, 127, 1, 1, 1, 1,
ax_anim 6, 2, 128, 3, 3, 3, 3,
ax_anim 2, 0, 129, 0, 0, 0, 0,
ax_anim 3, 0, 132, 0, 0, 0, 0,
ax_anim 3, 1, 135, 0, 0, 0, 0,
ax_anim 3, 0, 114, 0, 0, 0, 0,
ax_anim 3, 0, 117, 0, 0, 0, 0,
ax_anim 3, 0, 120, 0, 0, 0, 0,
ax_anim 3, 0, 123, 0, 0, 0, 0,
ax_anim 3, 0, 126, 0, 0, 0, 0,
ax_anim_terminator
sWooperAnims_5_7:
ax_anim 2, 0, 130, 1, 0, 1, 0,
ax_anim 6, 2, 131, 3, 0, 3, 0,
ax_anim 2, 0, 132, 0, 0, 0, 0,
ax_anim 3, 0, 135, 0, 0, 0, 0,
ax_anim 3, 1, 114, 0, 0, 0, 0,
ax_anim 3, 0, 117, 0, 0, 0, 0,
ax_anim 3, 0, 120, 0, 0, 0, 0,
ax_anim 3, 0, 123, 0, 0, 0, 0,
ax_anim 3, 0, 126, 0, 0, 0, 0,
ax_anim 3, 0, 129, 0, 0, 0, 0,
ax_anim_terminator
sWooperAnims_5_8:
ax_anim 2, 0, 133, 1, -1, 1, -1,
ax_anim 6, 2, 134, 3, -3, 3, -3,
ax_anim 2, 0, 135, 0, 0, 0, 0,
ax_anim 3, 0, 114, 0, 0, 0, 0,
ax_anim 3, 1, 117, 0, 0, 0, 0,
ax_anim 3, 0, 120, 0, 0, 0, 0,
ax_anim 3, 0, 123, 0, 0, 0, 0,
ax_anim 3, 0, 126, 0, 0, 0, 0,
ax_anim 3, 0, 129, 0, 0, 0, 0,
ax_anim 3, 0, 132, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sWooperAnims_6_1:
ax_anim 30, 0, 136, 0, 0, 0, 0,
ax_anim 35, 0, 137, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sWooperAnims_7_1:
ax_anim 2, 0, 138, 0, -4, 0, -4,
ax_anim 8, 0, 138, 0, -5, 0, -5,
ax_anim_terminator
sWooperAnims_7_2:
ax_anim 2, 0, 139, -4, -4, -4, -4,
ax_anim 8, 0, 139, -5, -5, -5, -5,
ax_anim_terminator
sWooperAnims_7_3:
ax_anim 2, 0, 140, -4, 0, -4, 0,
ax_anim 8, 0, 140, -5, 0, -5, 0,
ax_anim_terminator
sWooperAnims_7_4:
ax_anim 2, 0, 141, -4, 4, -4, 4,
ax_anim 8, 0, 141, -5, 5, -5, 5,
ax_anim_terminator
sWooperAnims_7_5:
ax_anim 2, 0, 142, 0, 4, 0, 4,
ax_anim 8, 0, 142, 0, 5, 0, 5,
ax_anim_terminator
sWooperAnims_7_6:
ax_anim 2, 0, 143, 4, 4, 4, 4,
ax_anim 8, 0, 143, 5, 5, 5, 5,
ax_anim_terminator
sWooperAnims_7_7:
ax_anim 2, 0, 144, 4, 0, 4, 0,
ax_anim 8, 0, 144, 5, 0, 5, 0,
ax_anim_terminator
sWooperAnims_7_8:
ax_anim 2, 0, 145, 4, -4, 4, -4,
ax_anim 8, 0, 145, 5, -5, 5, -5,
ax_anim_terminator
.align 2
sWooperAnims_8_1:
ax_anim 24, 0, 146, 0, 0, 0, 0,
ax_anim 16, 0, 147, 0, 0, 0, 0,
ax_anim_terminator
sWooperAnims_8_2:
ax_anim 24, 0, 149, 0, 0, 0, 0,
ax_anim 16, 0, 151, 0, 0, 0, 0,
ax_anim_terminator
sWooperAnims_8_3:
ax_anim 24, 0, 152, 0, 0, 0, 0,
ax_anim 16, 0, 154, 0, 0, 0, 0,
ax_anim_terminator
sWooperAnims_8_4:
ax_anim 24, 0, 155, 0, 0, 0, 0,
ax_anim 16, 0, 157, 0, 0, 0, 0,
ax_anim_terminator
sWooperAnims_8_5:
ax_anim 24, 0, 158, 0, 0, 0, 0,
ax_anim 16, 0, 160, 0, 0, 0, 0,
ax_anim_terminator
sWooperAnims_8_6:
ax_anim 24, 0, 161, 0, 0, 0, 0,
ax_anim 16, 0, 162, 0, 0, 0, 0,
ax_anim_terminator
sWooperAnims_8_7:
ax_anim 24, 0, 164, 0, 0, 0, 0,
ax_anim 16, 0, 166, 0, 0, 0, 0,
ax_anim_terminator
sWooperAnims_8_8:
ax_anim 24, 0, 167, 0, 0, 0, 0,
ax_anim 16, 0, 168, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sWooperAnims_9_1:
ax_anim 2, 0, 170, 0, 0, 0, 0,
ax_anim 1, 0, 171, 6, 3, 6, 3,
ax_anim 2, 0, 172, 8, 9, 8, 9,
ax_anim 2, 0, 173, 7, 17, 7, 17,
ax_anim 3, 0, 174, 0, 21, 0, 21,
ax_anim 2, 3, 175, -7, 17, -7, 17,
ax_anim 2, 0, 176, -8, 9, -8, 9,
ax_anim 1, 0, 177, -6, 3, -6, 3,
ax_anim 1, 0, 170, 0, 0, 0, 0,
ax_anim_terminator
sWooperAnims_9_2:
ax_anim 2, 0, 177, 0, 0, 0, 0,
ax_anim 1, 0, 170, 10, 1, 10, 1,
ax_anim 2, 0, 171, 19, 5, 19, 5,
ax_anim 2, 0, 172, 23, 13, 23, 13,
ax_anim 3, 0, 173, 21, 20, 21, 20,
ax_anim 2, 3, 174, 15, 21, 15, 21,
ax_anim 2, 0, 175, 6, 18, 6, 18,
ax_anim 1, 0, 176, 1, 9, 1, 9,
ax_anim 1, 0, 177, 0, 0, 0, 0,
ax_anim_terminator
sWooperAnims_9_3:
ax_anim 2, 0, 176, 0, 0, 0, 0,
ax_anim 1, 0, 177, 3, -5, 3, -5,
ax_anim 2, 0, 170, 12, -6, 12, -6,
ax_anim 2, 0, 171, 18, -5, 18, -5,
ax_anim 3, 0, 172, 21, -2, 21, -2,
ax_anim 2, 3, 173, 18, 4, 18, 4,
ax_anim 2, 0, 174, 13, 5, 13, 5,
ax_anim 1, 0, 175, 4, 5, 4, 5,
ax_anim 1, 0, 176, 0, 0, 0, 0,
ax_anim_terminator
sWooperAnims_9_4:
ax_anim 2, 0, 175, 0, 0, 0, 0,
ax_anim 1, 0, 176, -1, -8, -1, -8,
ax_anim 2, 0, 177, 4, -16, 4, -16,
ax_anim 2, 0, 170, 11, -23, 11, -23,
ax_anim 3, 0, 171, 21, -23, 21, -23,
ax_anim 2, 3, 172, 22, -15, 22, -15,
ax_anim 2, 0, 173, 17, -4, 17, -4,
ax_anim 1, 0, 174, 7, -1, 7, -1,
ax_anim 1, 0, 175, 0, 0, 0, 0,
ax_anim_terminator
sWooperAnims_9_5:
ax_anim 2, 0, 174, 0, 0, 0, 0,
ax_anim 1, 0, 175, -8, -4, -8, -4,
ax_anim 2, 0, 176, -9, -12, -9, -12,
ax_anim 2, 0, 177, -7, -19, -7, -19,
ax_anim 3, 0, 170, 0, -24, 0, -24,
ax_anim 2, 3, 171, 7, -19, 7, -19,
ax_anim 2, 0, 172, 9, -12, 9, -12,
ax_anim 1, 0, 173, 8, -4, 8, -4,
ax_anim 1, 0, 174, 0, 0, 0, 0,
ax_anim_terminator
sWooperAnims_9_6:
ax_anim 2, 0, 173, 0, 0, 0, 0,
ax_anim 1, 0, 172, 1, -8, 1, -8,
ax_anim 2, 0, 171, -4, -16, -4, -16,
ax_anim 2, 0, 170, -11, -23, -11, -23,
ax_anim 3, 0, 177, -21, -23, -21, -23,
ax_anim 2, 3, 176, -22, -15, -22, -15,
ax_anim 2, 0, 175, -17, -4, -17, -4,
ax_anim 1, 0, 174, -7, -1, -7, -1,
ax_anim 1, 0, 173, 0, 0, 0, 0,
ax_anim_terminator
sWooperAnims_9_7:
ax_anim 2, 0, 172, 0, 0, 0, 0,
ax_anim 1, 0, 171, -3, -5, -3, -5,
ax_anim 2, 0, 170, -12, -6, -12, -6,
ax_anim 2, 0, 177, -18, -5, -18, -5,
ax_anim 3, 0, 176, -21, -2, -21, -2,
ax_anim 2, 3, 175, -18, 4, -18, 4,
ax_anim 2, 0, 174, -13, 5, -13, 5,
ax_anim 1, 0, 173, -4, 5, -4, 5,
ax_anim 1, 0, 172, 0, 0, 0, 0,
ax_anim_terminator
sWooperAnims_9_8:
ax_anim 2, 0, 171, 0, 0, 0, 0,
ax_anim 1, 0, 170, -10, 1, -10, 1,
ax_anim 2, 0, 177, -19, 5, -19, 5,
ax_anim 2, 0, 176, -23, 13, -23, 13,
ax_anim 3, 0, 175, -21, 20, -21, 20,
ax_anim 2, 3, 174, -15, 21, -15, 21,
ax_anim 2, 0, 173, -6, 18, -6, 18,
ax_anim 1, 0, 172, -1, 9, -1, 9,
ax_anim 1, 0, 171, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sWooperAnims_10_1:
ax_anim 2, 0, 178, 0, 0, 0, 0,
ax_anim 2, 0, 178, 6, 0, 6, 0,
ax_anim 2, 0, 178, -6, 0, -6, 0,
ax_anim 2, 0, 178, 10, 0, 10, 0,
ax_anim 2, 0, 178, -10, 0, -10, 0,
ax_anim 2, 0, 178, 12, 0, 12, 0,
ax_anim 3, 0, 178, -12, 0, -12, 0,
ax_anim 3, 0, 178, 13, 0, 13, 0,
ax_anim 3, 0, 178, -13, 0, -13, 0,
ax_anim 2, 0, 178, 12, 0, 12, 0,
ax_anim 3, 0, 178, -12, 0, -12, 0,
ax_anim 2, 0, 178, 10, 0, 10, 0,
ax_anim 2, 0, 178, -10, 0, -10, 0,
ax_anim 2, 0, 178, 6, 0, 6, 0,
ax_anim 2, 0, 178, -6, 0, -6, 0,
ax_anim 2, 0, 178, 0, 0, 0, 0,
ax_anim_terminator
sWooperAnims_10_2:
ax_anim 2, 0, 179, 0, 0, 0, 0,
ax_anim 2, 0, 179, 6, -6, 6, -6,
ax_anim 2, 0, 179, -6, 6, -6, 6,
ax_anim 2, 0, 179, 10, -10, 10, -10,
ax_anim 2, 0, 179, -10, 10, -10, 10,
ax_anim 2, 0, 179, 12, -12, 12, -12,
ax_anim 3, 0, 179, -12, 12, -12, 12,
ax_anim 3, 0, 179, 13, -13, 13, -13,
ax_anim 3, 0, 179, -13, 13, -13, 13,
ax_anim 2, 0, 179, 12, -12, 12, -12,
ax_anim 3, 0, 179, -12, 12, -12, 12,
ax_anim 2, 0, 179, 10, -10, 10, -10,
ax_anim 2, 0, 179, -10, 10, -10, 10,
ax_anim 2, 0, 179, 6, -6, 6, -6,
ax_anim 2, 0, 179, -6, 6, -6, 6,
ax_anim 2, 0, 179, 0, 0, 0, 0,
ax_anim_terminator
sWooperAnims_10_3:
ax_anim 2, 0, 180, 0, 0, 0, 0,
ax_anim 2, 0, 180, 0, -6, 0, -6,
ax_anim 2, 0, 180, 0, 6, 0, 6,
ax_anim 2, 0, 180, 0, -10, 0, -10,
ax_anim 2, 0, 180, 0, 10, 0, 10,
ax_anim 2, 0, 180, 0, -12, 0, -12,
ax_anim 3, 0, 180, 0, 12, 0, 12,
ax_anim 3, 0, 180, 0, -13, 0, -13,
ax_anim 3, 0, 180, 0, 13, 0, 13,
ax_anim 2, 0, 180, 0, -12, 0, -12,
ax_anim 3, 0, 180, 0, 12, 0, 12,
ax_anim 2, 0, 180, 0, -10, 0, -10,
ax_anim 2, 0, 180, 0, 10, 0, 10,
ax_anim 2, 0, 180, 0, -6, 0, -6,
ax_anim 2, 0, 180, 0, 6, 0, 6,
ax_anim 2, 0, 180, 0, 0, 0, 0,
ax_anim_terminator
sWooperAnims_10_4:
ax_anim 2, 0, 181, 0, 0, 0, 0,
ax_anim 2, 0, 181, -6, -6, -6, -6,
ax_anim 2, 0, 181, 6, 6, 6, 6,
ax_anim 2, 0, 181, -10, -10, -10, -10,
ax_anim 2, 0, 181, 10, 10, 10, 10,
ax_anim 2, 0, 181, -12, -12, -12, -12,
ax_anim 3, 0, 181, 12, 12, 12, 12,
ax_anim 3, 0, 181, -13, -13, -13, -13,
ax_anim 3, 0, 181, 13, 13, 13, 13,
ax_anim 2, 0, 181, -12, -12, -12, -12,
ax_anim 3, 0, 181, 12, 12, 12, 12,
ax_anim 2, 0, 181, -10, -10, -10, -10,
ax_anim 2, 0, 181, 10, 10, 10, 10,
ax_anim 2, 0, 181, -6, -6, -6, -6,
ax_anim 2, 0, 181, 6, 6, 6, 6,
ax_anim 2, 0, 181, 0, 0, 0, 0,
ax_anim_terminator
sWooperAnims_10_5:
ax_anim 2, 0, 182, 0, 0, 0, 0,
ax_anim 2, 0, 182, 6, 0, 6, 0,
ax_anim 2, 0, 182, -6, 0, -6, 0,
ax_anim 2, 0, 182, 10, 0, 10, 0,
ax_anim 2, 0, 182, -10, 0, -10, 0,
ax_anim 2, 0, 182, 12, 0, 12, 0,
ax_anim 3, 0, 182, -12, 0, -12, 0,
ax_anim 3, 0, 182, 13, 0, 13, 0,
ax_anim 3, 0, 182, -13, 0, -13, 0,
ax_anim 2, 0, 182, 12, 0, 12, 0,
ax_anim 3, 0, 182, -12, 0, -12, 0,
ax_anim 2, 0, 182, 10, 0, 10, 0,
ax_anim 2, 0, 182, -10, 0, -10, 0,
ax_anim 2, 0, 182, 6, 0, 6, 0,
ax_anim 2, 0, 182, -6, 0, -6, 0,
ax_anim 2, 0, 182, 0, 0, 0, 0,
ax_anim_terminator
sWooperAnims_10_6:
ax_anim 2, 0, 183, 0, 0, 0, 0,
ax_anim 2, 0, 183, 6, -6, 6, -6,
ax_anim 2, 0, 183, -6, 6, -6, 6,
ax_anim 2, 0, 183, 10, -10, 10, -10,
ax_anim 2, 0, 183, -10, 10, -10, 10,
ax_anim 2, 0, 183, 12, -12, 12, -12,
ax_anim 3, 0, 183, -12, 12, -12, 12,
ax_anim 3, 0, 183, 13, -13, 13, -13,
ax_anim 3, 0, 183, -13, 13, -13, 13,
ax_anim 2, 0, 183, 12, -12, 12, -12,
ax_anim 3, 0, 183, -12, 12, -12, 12,
ax_anim 2, 0, 183, 10, -10, 10, -10,
ax_anim 2, 0, 183, -10, 10, -10, 10,
ax_anim 2, 0, 183, 6, -6, 6, -6,
ax_anim 2, 0, 183, -6, 6, -6, 6,
ax_anim 2, 0, 183, 0, 0, 0, 0,
ax_anim_terminator
sWooperAnims_10_7:
ax_anim 2, 0, 184, 0, 0, 0, 0,
ax_anim 2, 0, 184, 0, -6, 0, -6,
ax_anim 2, 0, 184, 0, 6, 0, 6,
ax_anim 2, 0, 184, 0, -10, 0, -10,
ax_anim 2, 0, 184, 0, 10, 0, 10,
ax_anim 2, 0, 184, 0, -12, 0, -12,
ax_anim 3, 0, 184, 0, 12, 0, 12,
ax_anim 3, 0, 184, 0, -13, 0, -13,
ax_anim 3, 0, 184, 0, 13, 0, 13,
ax_anim 2, 0, 184, 0, -12, 0, -12,
ax_anim 3, 0, 184, 0, 12, 0, 12,
ax_anim 2, 0, 184, 0, -10, 0, -10,
ax_anim 2, 0, 184, 0, 10, 0, 10,
ax_anim 2, 0, 184, 0, -6, 0, -6,
ax_anim 2, 0, 184, 0, 6, 0, 6,
ax_anim 2, 0, 184, 0, 0, 0, 0,
ax_anim_terminator
sWooperAnims_10_8:
ax_anim 2, 0, 185, 0, 0, 0, 0,
ax_anim 2, 0, 185, -6, -6, -6, -6,
ax_anim 2, 0, 185, 6, 6, 6, 6,
ax_anim 2, 0, 185, -10, -10, -10, -10,
ax_anim 2, 0, 185, 10, 10, 10, 10,
ax_anim 2, 0, 185, -12, -12, -12, -12,
ax_anim 3, 0, 185, 12, 12, 12, 12,
ax_anim 3, 0, 185, -13, -13, -13, -13,
ax_anim 3, 0, 185, 13, 13, 13, 13,
ax_anim 2, 0, 185, -12, -12, -12, -12,
ax_anim 3, 0, 185, 12, 12, 12, 12,
ax_anim 2, 0, 185, -10, -10, -10, -10,
ax_anim 2, 0, 185, 10, 10, 10, 10,
ax_anim 2, 0, 185, -6, -6, -6, -6,
ax_anim 2, 0, 185, 6, 6, 6, 6,
ax_anim 2, 0, 185, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sWooperAnims_11_1:
ax_anim 2, 0, 186, 0, 0, 0, 0,
ax_anim 1, 0, 187, 0, -10, 0, 0,
ax_anim 2, 0, 187, 0, -16, 0, 0,
ax_anim 3, 0, 187, 0, -20, 0, 0,
ax_anim 4, 0, 187, 0, -21, 0, 0,
ax_anim 4, 0, 186, 0, -23, 0, 0,
ax_anim 3, 0, 188, 0, -22, 0, 0,
ax_anim 2, 0, 188, 0, -18, 0, 0,
ax_anim 1, 0, 188, 0, -12, 0, 0,
ax_anim 2, 2, 188, 0, 0, 0, 0,
ax_anim_terminator
sWooperAnims_11_2:
ax_anim 2, 0, 189, 0, 0, 0, 0,
ax_anim 1, 0, 190, 0, -10, 0, 0,
ax_anim 2, 0, 190, 0, -16, 0, 0,
ax_anim 3, 0, 190, 0, -20, 0, 0,
ax_anim 4, 0, 190, 0, -21, 0, 0,
ax_anim 4, 0, 189, 0, -23, 0, 0,
ax_anim 3, 0, 191, 0, -22, 0, 0,
ax_anim 2, 0, 191, 0, -18, 0, 0,
ax_anim 1, 0, 191, 0, -12, 0, 0,
ax_anim 2, 2, 191, 0, 0, 0, 0,
ax_anim_terminator
sWooperAnims_11_3:
ax_anim 2, 0, 192, 0, 0, 0, 0,
ax_anim 1, 0, 193, 0, -10, 0, 0,
ax_anim 2, 0, 193, 0, -16, 0, 0,
ax_anim 3, 0, 193, 0, -20, 0, 0,
ax_anim 4, 0, 193, 0, -21, 0, 0,
ax_anim 4, 0, 192, 0, -23, 0, 0,
ax_anim 3, 0, 194, 0, -22, 0, 0,
ax_anim 2, 0, 194, 0, -18, 0, 0,
ax_anim 1, 0, 194, 0, -12, 0, 0,
ax_anim 2, 2, 194, 0, 0, 0, 0,
ax_anim_terminator
sWooperAnims_11_4:
ax_anim 2, 0, 195, 0, 0, 0, 0,
ax_anim 1, 0, 196, 0, -10, 0, 0,
ax_anim 2, 0, 196, 0, -16, 0, 0,
ax_anim 3, 0, 196, 0, -20, 0, 0,
ax_anim 4, 0, 196, 0, -21, 0, 0,
ax_anim 4, 0, 195, 0, -22, 0, 0,
ax_anim 3, 0, 197, 0, -21, 0, 0,
ax_anim 2, 0, 197, 0, -17, 0, 0,
ax_anim 1, 0, 197, 0, -11, 0, 0,
ax_anim 2, 2, 197, 0, 0, 0, 0,
ax_anim_terminator
sWooperAnims_11_5:
ax_anim 2, 0, 198, 0, 0, 0, 0,
ax_anim 1, 0, 199, 0, -10, 0, 0,
ax_anim 2, 0, 199, 0, -16, 0, 0,
ax_anim 3, 0, 199, 0, -20, 0, 0,
ax_anim 4, 0, 199, 0, -21, 0, 0,
ax_anim 4, 0, 198, 0, -23, 0, 0,
ax_anim 3, 0, 200, 0, -22, 0, 0,
ax_anim 2, 0, 200, 0, -18, 0, 0,
ax_anim 1, 0, 200, 0, -12, 0, 0,
ax_anim 2, 2, 200, 0, 0, 0, 0,
ax_anim_terminator
sWooperAnims_11_6:
ax_anim 2, 0, 201, 0, 0, 0, 0,
ax_anim 1, 0, 202, 0, -10, 0, 0,
ax_anim 2, 0, 202, 0, -16, 0, 0,
ax_anim 3, 0, 202, 0, -20, 0, 0,
ax_anim 4, 0, 202, 0, -21, 0, 0,
ax_anim 4, 0, 201, 0, -22, 0, 0,
ax_anim 3, 0, 203, 0, -21, 0, 0,
ax_anim 2, 0, 203, 0, -17, 0, 0,
ax_anim 1, 0, 203, 0, -11, 0, 0,
ax_anim 2, 2, 203, 0, 0, 0, 0,
ax_anim_terminator
sWooperAnims_11_7:
ax_anim 2, 0, 204, 0, 0, 0, 0,
ax_anim 1, 0, 205, 0, -10, 0, 0,
ax_anim 2, 0, 205, 0, -16, 0, 0,
ax_anim 3, 0, 205, 0, -20, 0, 0,
ax_anim 4, 0, 205, 0, -21, 0, 0,
ax_anim 4, 0, 204, 0, -23, 0, 0,
ax_anim 3, 0, 206, 0, -22, 0, 0,
ax_anim 2, 0, 206, 0, -18, 0, 0,
ax_anim 1, 0, 206, 0, -12, 0, 0,
ax_anim 2, 2, 206, 0, 0, 0, 0,
ax_anim_terminator
sWooperAnims_11_8:
ax_anim 2, 0, 207, 0, 0, 0, 0,
ax_anim 1, 0, 208, 0, -10, 0, 0,
ax_anim 2, 0, 208, 0, -16, 0, 0,
ax_anim 3, 0, 208, 0, -20, 0, 0,
ax_anim 4, 0, 208, 0, -21, 0, 0,
ax_anim 4, 0, 207, 0, -23, 0, 0,
ax_anim 3, 0, 209, 0, -22, 0, 0,
ax_anim 2, 0, 209, 0, -18, 0, 0,
ax_anim 1, 0, 209, 0, -12, 0, 0,
ax_anim 2, 2, 209, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sWooperAnims_12_1:
ax_anim 2, 0, 210, 1, 0, 1, 0,
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 2, 0, 210, 1, 0, 1, 0,
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 2, 0, 210, 1, 0, 1, 0,
ax_anim 2, 2, 210, 0, 0, 0, 0,
ax_anim 2, 0, 210, 1, 0, 1, 0,
ax_anim 2, 0, 210, 0, 0, 0, 0,
ax_anim 2, 0, 210, 1, 0, 1, 0,
ax_anim 2, 1, 210, 0, 0, 0, 0,
ax_anim_terminator
sWooperAnims_12_2:
ax_anim 2, 0, 217, 1, -1, 1, -1,
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 0, 217, 1, -1, 1, -1,
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 0, 217, 1, -1, 1, -1,
ax_anim 2, 2, 217, 0, 0, 0, 0,
ax_anim 2, 0, 217, 1, -1, 1, -1,
ax_anim 2, 0, 217, 0, 0, 0, 0,
ax_anim 2, 0, 217, 1, -1, 1, -1,
ax_anim 2, 1, 217, 0, 0, 0, 0,
ax_anim_terminator
sWooperAnims_12_3:
ax_anim 2, 0, 216, 0, -1, 0, -1,
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, -1, 0, -1,
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, -1, 0, -1,
ax_anim 2, 2, 216, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, -1, 0, -1,
ax_anim 2, 0, 216, 0, 0, 0, 0,
ax_anim 2, 0, 216, 0, -1, 0, -1,
ax_anim 2, 1, 216, 0, 0, 0, 0,
ax_anim_terminator
sWooperAnims_12_4:
ax_anim 2, 0, 215, -1, -1, -1, -1,
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 0, 215, -1, -1, -1, -1,
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 0, 215, -1, -1, -1, -1,
ax_anim 2, 2, 215, 0, 0, 0, 0,
ax_anim 2, 0, 215, -1, -1, -1, -1,
ax_anim 2, 0, 215, 0, 0, 0, 0,
ax_anim 2, 0, 215, -1, -1, -1, -1,
ax_anim 2, 1, 215, 0, 0, 0, 0,
ax_anim_terminator
sWooperAnims_12_5:
ax_anim 2, 0, 214, 1, 0, 1, 0,
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 2, 0, 214, 1, 0, 1, 0,
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 2, 0, 214, 1, 0, 1, 0,
ax_anim 2, 2, 214, 0, 0, 0, 0,
ax_anim 2, 0, 214, 1, 0, 1, 0,
ax_anim 2, 0, 214, 0, 0, 0, 0,
ax_anim 2, 0, 214, 1, 0, 1, 0,
ax_anim 2, 1, 214, 0, 0, 0, 0,
ax_anim_terminator
sWooperAnims_12_6:
ax_anim 2, 0, 213, 1, -1, 1, -1,
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 2, 0, 213, 1, -1, 1, -1,
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 2, 0, 213, 1, -1, 1, -1,
ax_anim 2, 2, 213, 0, 0, 0, 0,
ax_anim 2, 0, 213, 1, -1, 1, -1,
ax_anim 2, 0, 213, 0, 0, 0, 0,
ax_anim 2, 0, 213, 1, -1, 1, -1,
ax_anim 2, 1, 213, 0, 0, 0, 0,
ax_anim_terminator
sWooperAnims_12_7:
ax_anim 2, 0, 212, 0, -1, 0, -1,
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 2, 0, 212, 0, -1, 0, -1,
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 2, 0, 212, 0, -1, 0, -1,
ax_anim 2, 2, 212, 0, 0, 0, 0,
ax_anim 2, 0, 212, 0, -1, 0, -1,
ax_anim 2, 0, 212, 0, 0, 0, 0,
ax_anim 2, 0, 212, 0, -1, 0, -1,
ax_anim 2, 1, 212, 0, 0, 0, 0,
ax_anim_terminator
sWooperAnims_12_8:
ax_anim 2, 0, 211, -1, -1, -1, -1,
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 2, 0, 211, -1, -1, -1, -1,
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 2, 0, 211, -1, -1, -1, -1,
ax_anim 2, 2, 211, 0, 0, 0, 0,
ax_anim 2, 0, 211, -1, -1, -1, -1,
ax_anim 2, 0, 211, 0, 0, 0, 0,
ax_anim 2, 0, 211, -1, -1, -1, -1,
ax_anim 2, 1, 211, 0, 0, 0, 0,
ax_anim_terminator
.align 2
sWooperAnims_13_1:
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 2, 2, 218, 0, 0, 0, 0,
ax_anim_terminator
sWooperAnims_13_2:
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 2, 2, 225, 0, 0, 0, 0,
ax_anim_terminator
sWooperAnims_13_3:
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 2, 2, 224, 0, 0, 0, 0,
ax_anim_terminator
sWooperAnims_13_4:
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 2, 223, 0, 0, 0, 0,
ax_anim_terminator
sWooperAnims_13_5:
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 2, 222, 0, 0, 0, 0,
ax_anim_terminator
sWooperAnims_13_6:
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 2, 221, 0, 0, 0, 0,
ax_anim_terminator
sWooperAnims_13_7:
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 2, 220, 0, 0, 0, 0,
ax_anim_terminator
sWooperAnims_13_8:
ax_anim 2, 0, 219, 0, 0, 0, 0,
ax_anim 2, 0, 220, 0, 0, 0, 0,
ax_anim 2, 0, 221, 0, 0, 0, 0,
ax_anim 2, 0, 222, 0, 0, 0, 0,
ax_anim 2, 0, 223, 0, 0, 0, 0,
ax_anim 2, 0, 224, 0, 0, 0, 0,
ax_anim 2, 0, 225, 0, 0, 0, 0,
ax_anim 2, 0, 218, 0, 0, 0, 0,
ax_anim 2, 2, 219, 0, 0, 0, 0,
ax_anim_terminator
sWooperGfx1:
.incbin "baserom.gba", 0xD54758, 0x200
sWooperSprites1:
ax_sprite sWooperGfx1, 0x200
ax_sprite_terminator
sWooperGfx2:
.incbin "baserom.gba", 0xD54968, 0x200
sWooperSprites2:
ax_sprite sWooperGfx2, 0x200
ax_sprite_terminator
sWooperGfx3:
.incbin "baserom.gba", 0xD54B78, 0x200
sWooperSprites3:
ax_sprite sWooperGfx3, 0x200
ax_sprite_terminator
sWooperGfx4:
.incbin "baserom.gba", 0xD54D88, 0x200
sWooperSprites4:
ax_sprite sWooperGfx4, 0x200
ax_sprite_terminator
sWooperGfx5:
.incbin "baserom.gba", 0xD54F98, 0x200
sWooperSprites5:
ax_sprite sWooperGfx5, 0x200
ax_sprite_terminator
sWooperGfx6:
.incbin "baserom.gba", 0xD551A8, 0x200
sWooperSprites6:
ax_sprite sWooperGfx6, 0x200
ax_sprite_terminator
sWooperGfx7:
.incbin "baserom.gba", 0xD553B8, 0x200
sWooperSprites7:
ax_sprite sWooperGfx7, 0x200
ax_sprite_terminator
sWooperGfx8:
.incbin "baserom.gba", 0xD555C8, 0x200
sWooperSprites8:
ax_sprite sWooperGfx8, 0x200
ax_sprite_terminator
sWooperGfx9:
.incbin "baserom.gba", 0xD557D8, 0x200
sWooperSprites9:
ax_sprite sWooperGfx9, 0x200
ax_sprite_terminator
sWooperGfx10:
.incbin "baserom.gba", 0xD559E8, 0x200
sWooperSprites10:
ax_sprite sWooperGfx10, 0x200
ax_sprite_terminator
sWooperGfx11:
.incbin "baserom.gba", 0xD55BF8, 0x200
sWooperSprites11:
ax_sprite sWooperGfx11, 0x200
ax_sprite_terminator
sWooperGfx12:
.incbin "baserom.gba", 0xD55E08, 0x200
sWooperSprites12:
ax_sprite sWooperGfx12, 0x200
ax_sprite_terminator
sWooperGfx13:
.incbin "baserom.gba", 0xD56018, 0x200
sWooperSprites13:
ax_sprite sWooperGfx13, 0x200
ax_sprite_terminator
sWooperGfx14:
.incbin "baserom.gba", 0xD56228, 0x200
sWooperSprites14:
ax_sprite sWooperGfx14, 0x200
ax_sprite_terminator
sWooperGfx15:
.incbin "baserom.gba", 0xD56438, 0x200
sWooperSprites15:
ax_sprite sWooperGfx15, 0x200
ax_sprite_terminator
sWooperGfx16:
.incbin "baserom.gba", 0xD56648, 0x200
sWooperSprites16:
ax_sprite sWooperGfx16, 0x200
ax_sprite_terminator
sWooperGfx17:
.incbin "baserom.gba", 0xD56858, 0x200
sWooperSprites17:
ax_sprite sWooperGfx17, 0x200
ax_sprite_terminator
sWooperGfx18:
.incbin "baserom.gba", 0xD56A68, 0x200
sWooperSprites18:
ax_sprite sWooperGfx18, 0x200
ax_sprite_terminator
sWooperGfx19:
.incbin "baserom.gba", 0xD56C78, 0x200
sWooperSprites19:
ax_sprite sWooperGfx19, 0x200
ax_sprite_terminator
sWooperGfx20:
.incbin "baserom.gba", 0xD56E88, 0x200
sWooperSprites20:
ax_sprite sWooperGfx20, 0x200
ax_sprite_terminator
sWooperGfx21:
.incbin "baserom.gba", 0xD57098, 0x200
sWooperSprites21:
ax_sprite sWooperGfx21, 0x200
ax_sprite_terminator
sWooperGfx22:
.incbin "baserom.gba", 0xD572A8, 0x200
sWooperSprites22:
ax_sprite sWooperGfx22, 0x200
ax_sprite_terminator
sWooperGfx23:
.incbin "baserom.gba", 0xD574B8, 0x200
sWooperSprites23:
ax_sprite sWooperGfx23, 0x200
ax_sprite_terminator
sWooperGfx24:
.incbin "baserom.gba", 0xD576C8, 0x200
sWooperSprites24:
ax_sprite sWooperGfx24, 0x200
ax_sprite_terminator
sWooperGfx25:
.incbin "baserom.gba", 0xD578D8, 0x60
sWooperGfx25_1:
.incbin "baserom.gba", 0xD57938, 0x60
sWooperGfx25_2:
.incbin "baserom.gba", 0xD57998, 0x40
sWooperSprites25:
ax_sprite sWooperGfx25, 0x60
ax_sprite 0, 0x20
ax_sprite sWooperGfx25_1, 0x60
ax_sprite 0, 0x40
ax_sprite sWooperGfx25_2, 0x40
ax_sprite 0, 0xa0
ax_sprite_terminator
sWooperGfx26:
.incbin "baserom.gba", 0xD57A10, 0x60
sWooperGfx26_1:
.incbin "baserom.gba", 0xD57A70, 0x60
sWooperGfx26_2:
.incbin "baserom.gba", 0xD57AD0, 0x40
sWooperSprites26:
ax_sprite sWooperGfx26, 0x60
ax_sprite 0, 0x20
ax_sprite sWooperGfx26_1, 0x60
ax_sprite 0, 0x40
ax_sprite sWooperGfx26_2, 0x40
ax_sprite 0, 0xa0
ax_sprite_terminator
sWooperGfx27:
.incbin "baserom.gba", 0xD57B48, 0x100
sWooperSprites27:
ax_sprite sWooperGfx27, 0x100
ax_sprite_terminator
sWooperGfx28:
.incbin "baserom.gba", 0xD57C58, 0x100
sWooperSprites28:
ax_sprite sWooperGfx28, 0x100
ax_sprite_terminator
sWooperGfx29:
.incbin "baserom.gba", 0xD57D68, 0x40
sWooperGfx29_1:
.incbin "baserom.gba", 0xD57DA8, 0x80
sWooperGfx29_2:
.incbin "baserom.gba", 0xD57E28, 0x40
sWooperGfx29_3:
.incbin "baserom.gba", 0xD57E68, 0x20
sWooperSprites29:
ax_sprite 0, 0x20
ax_sprite sWooperGfx29, 0x40
ax_sprite 0, 0x20
ax_sprite sWooperGfx29_1, 0x80
ax_sprite 0, 0x20
ax_sprite sWooperGfx29_2, 0x40
ax_sprite 0, 0x40
ax_sprite sWooperGfx29_3, 0x20
ax_sprite 0, 0x40
ax_sprite_terminator
sWooperGfx30:
.incbin "baserom.gba", 0xD57ED8, 0x20
sWooperGfx30_1:
.incbin "baserom.gba", 0xD57EF8, 0x60
sWooperGfx30_2:
.incbin "baserom.gba", 0xD57F58, 0x60
sWooperSprites30:
ax_sprite 0, 0x20
ax_sprite sWooperGfx30, 0x20
ax_sprite 0, 0x40
ax_sprite sWooperGfx30_1, 0x60
ax_sprite 0, 0x20
ax_sprite sWooperGfx30_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sWooperGfx31:
.incbin "baserom.gba", 0xD57FF8, 0x40
sWooperGfx31_1:
.incbin "baserom.gba", 0xD58038, 0x60
sWooperGfx31_2:
.incbin "baserom.gba", 0xD58098, 0x60
sWooperSprites31:
ax_sprite sWooperGfx31, 0x40
ax_sprite 0, 0x40
ax_sprite sWooperGfx31_1, 0x60
ax_sprite 0, 0x20
ax_sprite sWooperGfx31_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sWooperGfx32:
.incbin "baserom.gba", 0xD58130, 0x40
sWooperGfx32_1:
.incbin "baserom.gba", 0xD58170, 0x60
sWooperGfx32_2:
.incbin "baserom.gba", 0xD581D0, 0x60
sWooperSprites32:
ax_sprite sWooperGfx32, 0x40
ax_sprite 0, 0x40
ax_sprite sWooperGfx32_1, 0x60
ax_sprite 0, 0x20
ax_sprite sWooperGfx32_2, 0x60
ax_sprite 0, 0xa0
ax_sprite_terminator
sWooperGfx33:
.incbin "baserom.gba", 0xD58268, 0xC0
sWooperSprites33:
ax_sprite sWooperGfx33, 0xc0
ax_sprite 0, 0x40
ax_sprite_terminator
sWooperGfx34:
.incbin "baserom.gba", 0xD58340, 0x40
sWooperGfx34_1:
.incbin "baserom.gba", 0xD58380, 0x80
sWooperGfx34_2:
.incbin "baserom.gba", 0xD58400, 0x40
sWooperSprites34:
ax_sprite 0, 0x20
ax_sprite sWooperGfx34, 0x40
ax_sprite 0, 0x20
ax_sprite sWooperGfx34_1, 0x80
ax_sprite 0, 0x20
ax_sprite sWooperGfx34_2, 0x40
ax_sprite 0, 0xa0
ax_sprite_terminator
sWooperGfx35:
.incbin "baserom.gba", 0xD58480, 0x200
sWooperSprites35:
ax_sprite sWooperGfx35, 0x200
ax_sprite_terminator
sWooperGfx36:
.incbin "baserom.gba", 0xD58690, 0x200
sWooperSprites36:
ax_sprite sWooperGfx36, 0x200
ax_sprite_terminator
sWooperGfx37:
.incbin "baserom.gba", 0xD588A0, 0x200
sWooperSprites37:
ax_sprite sWooperGfx37, 0x200
ax_sprite_terminator
sWooperGfx38:
.incbin "baserom.gba", 0xD58AB0, 0x200
sWooperSprites38:
ax_sprite sWooperGfx38, 0x200
ax_sprite_terminator
sWooperGfx39:
.incbin "baserom.gba", 0xD58CC0, 0x200
sWooperSprites39:
ax_sprite sWooperGfx39, 0x200
ax_sprite_terminator
sWooperGfx40:
.incbin "baserom.gba", 0xD58ED0, 0x200
sWooperSprites40:
ax_sprite sWooperGfx40, 0x200
ax_sprite_terminator
sWooperGfx41:
.incbin "baserom.gba", 0xD590E0, 0x200
sWooperSprites41:
ax_sprite sWooperGfx41, 0x200
ax_sprite_terminator
sAxPosesWooper:
.4byte sWooperPose1
.4byte sWooperPose2
.4byte sWooperPose3
.4byte sWooperPose4
.4byte sWooperPose5
.4byte sWooperPose6
.4byte sWooperPose7
.4byte sWooperPose8
.4byte sWooperPose9
.4byte sWooperPose10
.4byte sWooperPose11
.4byte sWooperPose12
.4byte sWooperPose13
.4byte sWooperPose14
.4byte sWooperPose15
.4byte sWooperPose16
.4byte sWooperPose17
.4byte sWooperPose18
.4byte sWooperPose19
.4byte sWooperPose20
.4byte sWooperPose21
.4byte sWooperPose22
.4byte sWooperPose23
.4byte sWooperPose24
.4byte sWooperPose25
.4byte sWooperPose26
.4byte sWooperPose27
.4byte sWooperPose28
.4byte sWooperPose29
.4byte sWooperPose30
.4byte sWooperPose31
.4byte sWooperPose32
.4byte sWooperPose33
.4byte sWooperPose34
.4byte sWooperPose35
.4byte sWooperPose36
.4byte sWooperPose37
.4byte sWooperPose38
.4byte sWooperPose39
.4byte sWooperPose40
.4byte sWooperPose41
.4byte sWooperPose42
.4byte sWooperPose43
.4byte sWooperPose44
.4byte sWooperPose45
.4byte sWooperPose46
.4byte sWooperPose47
.4byte sWooperPose48
.4byte sWooperPose49
.4byte sWooperPose50
.4byte sWooperPose51
.4byte sWooperPose52
.4byte sWooperPose53
.4byte sWooperPose54
.4byte sWooperPose55
.4byte sWooperPose56
.4byte sWooperPose57
.4byte sWooperPose58
.4byte sWooperPose59
.4byte sWooperPose60
.4byte sWooperPose61
.4byte sWooperPose62
.4byte sWooperPose63
.4byte sWooperPose64
.4byte sWooperPose65
.4byte sWooperPose66
.4byte sWooperPose67
.4byte sWooperPose68
.4byte sWooperPose69
.4byte sWooperPose70
.4byte sWooperPose71
.4byte sWooperPose72
.4byte sWooperPose73
.4byte sWooperPose74
.4byte sWooperPose75
.4byte sWooperPose76
.4byte sWooperPose77
.4byte sWooperPose78
.4byte sWooperPose79
.4byte sWooperPose80
.4byte sWooperPose81
.4byte sWooperPose82
.4byte sWooperPose83
.4byte sWooperPose84
.4byte sWooperPose85
.4byte sWooperPose86
.4byte sWooperPose87
.4byte sWooperPose88
.4byte sWooperPose89
.4byte sWooperPose90
.4byte sWooperPose91
.4byte sWooperPose92
.4byte sWooperPose93
.4byte sWooperPose94
.4byte sWooperPose95
.4byte sWooperPose96
.4byte sWooperPose97
.4byte sWooperPose98
.4byte sWooperPose99
.4byte sWooperPose100
.4byte sWooperPose101
.4byte sWooperPose102
.4byte sWooperPose103
.4byte sWooperPose104
.4byte sWooperPose105
.4byte sWooperPose106
.4byte sWooperPose107
.4byte sWooperPose108
.4byte sWooperPose109
.4byte sWooperPose110
.4byte sWooperPose111
.4byte sWooperPose112
.4byte sWooperPose113
.4byte sWooperPose114
.4byte sWooperPose115
.4byte sWooperPose116
.4byte sWooperPose117
.4byte sWooperPose118
.4byte sWooperPose119
.4byte sWooperPose120
.4byte sWooperPose121
.4byte sWooperPose122
.4byte sWooperPose123
.4byte sWooperPose124
.4byte sWooperPose125
.4byte sWooperPose126
.4byte sWooperPose127
.4byte sWooperPose128
.4byte sWooperPose129
.4byte sWooperPose130
.4byte sWooperPose131
.4byte sWooperPose132
.4byte sWooperPose133
.4byte sWooperPose134
.4byte sWooperPose135
.4byte sWooperPose136
.4byte sWooperPose137
.4byte sWooperPose138
.4byte sWooperPose139
.4byte sWooperPose140
.4byte sWooperPose141
.4byte sWooperPose142
.4byte sWooperPose143
.4byte sWooperPose144
.4byte sWooperPose145
.4byte sWooperPose146
.4byte sWooperPose147
.4byte sWooperPose148
.4byte sWooperPose149
.4byte sWooperPose150
.4byte sWooperPose151
.4byte sWooperPose152
.4byte sWooperPose153
.4byte sWooperPose154
.4byte sWooperPose155
.4byte sWooperPose156
.4byte sWooperPose157
.4byte sWooperPose158
.4byte sWooperPose159
.4byte sWooperPose160
.4byte sWooperPose161
.4byte sWooperPose162
.4byte sWooperPose163
.4byte sWooperPose164
.4byte sWooperPose165
.4byte sWooperPose166
.4byte sWooperPose167
.4byte sWooperPose168
.4byte sWooperPose169
.4byte sWooperPose170
.4byte sWooperPose171
.4byte sWooperPose172
.4byte sWooperPose173
.4byte sWooperPose174
.4byte sWooperPose175
.4byte sWooperPose176
.4byte sWooperPose177
.4byte sWooperPose178
.4byte sWooperPose179
.4byte sWooperPose180
.4byte sWooperPose181
.4byte sWooperPose182
.4byte sWooperPose183
.4byte sWooperPose184
.4byte sWooperPose185
.4byte sWooperPose186
.4byte sWooperPose187
.4byte sWooperPose188
.4byte sWooperPose189
.4byte sWooperPose190
.4byte sWooperPose191
.4byte sWooperPose192
.4byte sWooperPose193
.4byte sWooperPose194
.4byte sWooperPose195
.4byte sWooperPose196
.4byte sWooperPose197
.4byte sWooperPose198
.4byte sWooperPose199
.4byte sWooperPose200
.4byte sWooperPose201
.4byte sWooperPose202
.4byte sWooperPose203
.4byte sWooperPose204
.4byte sWooperPose205
.4byte sWooperPose206
.4byte sWooperPose207
.4byte sWooperPose208
.4byte sWooperPose209
.4byte sWooperPose210
.4byte sWooperPose211
.4byte sWooperPose212
.4byte sWooperPose213
.4byte sWooperPose214
.4byte sWooperPose215
.4byte sWooperPose216
.4byte sWooperPose217
.4byte sWooperPose218
.4byte sWooperPose219
.4byte sWooperPose220
.4byte sWooperPose221
.4byte sWooperPose222
.4byte sWooperPose223
.4byte sWooperPose224
.4byte sWooperPose225
.4byte sWooperPose226
sAxPositionsWooper:
.2byte    0,   -8, 	  -9,  -10, 	   8,  -11, 	   0,   -6
.2byte    0,   -9, 	  -9,  -14, 	   7,  -10, 	   0,   -7
.2byte    0,   -9, 	  -8,  -10, 	   8,  -14, 	   1,   -7
.2byte    3,   -8, 	  -6,   -9, 	   6,  -12, 	   0,   -6
.2byte    2,  -10, 	  -6,  -12, 	   7,  -12, 	   0,   -8
.2byte    2,  -10, 	  -7,  -10, 	   5,  -15, 	   0,   -8
.2byte    5,   -9, 	  -3,   -6, 	   0,  -11, 	   0,   -5
.2byte    6,  -13, 	  -2,  -12, 	   1,  -13, 	   0,   -8
.2byte    5,  -10, 	  -3,   -8, 	   1,  -15, 	   0,   -8
.2byte    2,  -10, 	   5,   -8, 	  -6,  -13, 	   0,   -6
.2byte    1,  -12, 	   4,  -12, 	  -7,  -14, 	   0,   -7
.2byte    2,  -12, 	   5,   -8, 	  -5,  -16, 	   1,   -8
.2byte    0,  -10, 	   8,  -10, 	  -8,  -10, 	   0,   -6
.2byte   -1,  -13, 	   7,  -14, 	  -9,  -11, 	  -1,   -8
.2byte    1,  -13, 	   9,  -11, 	  -7,  -14, 	   1,   -8
.2byte   -3,  -10, 	   7,  -14, 	  -4,   -8, 	   1,   -6
.2byte   -3,  -10, 	   5,  -16, 	  -5,   -8, 	   0,   -8
.2byte   -1,  -11, 	   8,  -14, 	  -4,  -12, 	   1,   -8
.2byte   -6,   -9, 	  -1,  -12, 	   3,   -7, 	   0,   -6
.2byte   -5,  -10, 	   1,  -14, 	   3,   -8, 	   0,   -8
.2byte   -6,  -13, 	  -1,  -13, 	   3,  -12, 	   0,   -8
.2byte   -3,   -8, 	  -7,  -13, 	   6,   -9, 	   0,   -6
.2byte   -2,  -10, 	  -5,  -15, 	   7,  -10, 	   1,   -8
.2byte   -2,  -10, 	  -7,  -11, 	   6,  -12, 	   0,   -8
.2byte    0,   -8, 	  -9,  -10, 	   8,  -11, 	   0,   -6
.2byte    0,   -9, 	  -9,  -14, 	   7,  -10, 	   0,   -7
.2byte    0,   -9, 	  -8,  -10, 	   8,  -14, 	   1,   -7
.2byte    0,  -10, 	  -8,  -12, 	   8,  -12, 	   0,   -7
.2byte    3,   -8, 	  -6,   -9, 	   6,  -12, 	   0,   -6
.2byte    2,  -10, 	  -6,  -12, 	   7,  -12, 	   0,   -8
.2byte    2,  -10, 	  -7,  -10, 	   5,  -15, 	   0,   -8
.2byte    2,  -10, 	   5,  -13, 	  -7,  -10, 	   0,   -7
.2byte    5,   -9, 	  -3,   -6, 	   0,  -11, 	   0,   -5
.2byte    6,  -13, 	  -2,  -12, 	   1,  -13, 	   0,   -8
.2byte    5,  -10, 	  -3,   -8, 	   1,  -15, 	   0,   -8
.2byte    3,  -11, 	  -4,  -12, 	  -6,   -8, 	  -2,   -7
.2byte    2,  -10, 	   5,   -8, 	  -6,  -13, 	   0,   -6
.2byte    1,  -12, 	   4,  -12, 	  -7,  -14, 	   0,   -7
.2byte    2,  -12, 	   5,   -8, 	  -5,  -16, 	   1,   -8
.2byte    1,  -10, 	  -7,  -12, 	   3,   -7, 	  -1,   -4
.2byte    0,  -10, 	   8,  -10, 	  -8,  -10, 	   0,   -6
.2byte   -1,  -13, 	   7,  -14, 	  -9,  -11, 	  -1,   -8
.2byte    1,  -13, 	   9,  -11, 	  -7,  -14, 	   1,   -8
.2byte    0,  -10, 	   8,  -11, 	  -8,  -11, 	   0,   -5
.2byte   -3,  -10, 	   7,  -14, 	  -4,   -8, 	   1,   -6
.2byte   -3,  -10, 	   5,  -16, 	  -5,   -8, 	   0,   -8
.2byte   -1,  -11, 	   8,  -14, 	  -4,  -12, 	   1,   -8
.2byte   -1,  -10, 	   7,  -12, 	  -3,   -7, 	   1,   -4
.2byte   -6,   -9, 	  -1,  -12, 	   3,   -7, 	   0,   -6
.2byte   -5,  -10, 	   1,  -14, 	   3,   -8, 	   0,   -8
.2byte   -6,  -13, 	  -1,  -13, 	   3,  -12, 	   0,   -8
.2byte   -3,  -11, 	   4,  -12, 	   6,   -8, 	   2,   -7
.2byte   -3,   -8, 	  -7,  -13, 	   6,   -9, 	   0,   -6
.2byte   -2,  -10, 	  -5,  -15, 	   7,  -10, 	   1,   -8
.2byte   -2,  -10, 	  -7,  -11, 	   6,  -12, 	   0,   -8
.2byte   -2,  -10, 	  -5,  -13, 	   7,  -10, 	   0,   -7
.2byte    0,   -8, 	  -9,  -10, 	   8,  -11, 	   0,   -6
.2byte    0,   -9, 	  -9,  -14, 	   7,  -10, 	   0,   -7
.2byte    0,   -9, 	  -8,  -10, 	   8,  -14, 	   1,   -7
.2byte    0,  -10, 	  -8,  -12, 	   8,  -12, 	   0,   -7
.2byte    3,   -8, 	  -6,   -9, 	   6,  -12, 	   0,   -6
.2byte    2,  -10, 	  -6,  -12, 	   7,  -12, 	   0,   -8
.2byte    2,  -10, 	  -7,  -10, 	   5,  -15, 	   0,   -8
.2byte    2,  -10, 	   5,  -13, 	  -7,  -10, 	   0,   -7
.2byte    5,   -9, 	  -3,   -6, 	   0,  -11, 	   0,   -5
.2byte    6,  -13, 	  -2,  -12, 	   1,  -13, 	   0,   -8
.2byte    5,  -10, 	  -3,   -8, 	   1,  -15, 	   0,   -8
.2byte    3,  -11, 	  -4,  -12, 	  -6,   -8, 	  -2,   -7
.2byte    2,  -10, 	   5,   -8, 	  -6,  -13, 	   0,   -6
.2byte    1,  -12, 	   4,  -12, 	  -7,  -14, 	   0,   -7
.2byte    2,  -12, 	   5,   -8, 	  -5,  -16, 	   1,   -8
.2byte    1,  -10, 	  -7,  -12, 	   3,   -7, 	  -1,   -4
.2byte    0,  -10, 	   8,  -10, 	  -8,  -10, 	   0,   -6
.2byte   -1,  -13, 	   7,  -14, 	  -9,  -11, 	  -1,   -8
.2byte    1,  -13, 	   9,  -11, 	  -7,  -14, 	   1,   -8
.2byte    0,  -10, 	   8,  -11, 	  -8,  -11, 	   0,   -5
.2byte   -3,  -10, 	   7,  -14, 	  -4,   -8, 	   1,   -6
.2byte   -3,  -10, 	   5,  -16, 	  -5,   -8, 	   0,   -8
.2byte   -1,  -11, 	   8,  -14, 	  -4,  -12, 	   1,   -8
.2byte   -1,  -10, 	   7,  -12, 	  -3,   -7, 	   1,   -4
.2byte   -6,   -9, 	  -1,  -12, 	   3,   -7, 	   0,   -6
.2byte   -5,  -10, 	   1,  -14, 	   3,   -8, 	   0,   -8
.2byte   -6,  -13, 	  -1,  -13, 	   3,  -12, 	   0,   -8
.2byte   -3,  -11, 	   4,  -12, 	   6,   -8, 	   2,   -7
.2byte   -3,   -8, 	  -7,  -13, 	   6,   -9, 	   0,   -6
.2byte   -2,  -10, 	  -5,  -15, 	   7,  -10, 	   1,   -8
.2byte   -2,  -10, 	  -7,  -11, 	   6,  -12, 	   0,   -8
.2byte   -2,  -10, 	  -5,  -13, 	   7,  -10, 	   0,   -7
.2byte    0,   -8, 	  -9,  -10, 	   8,  -11, 	   0,   -6
.2byte    0,  -10, 	  -8,  -12, 	   8,  -12, 	   0,   -7
.2byte    0,   -6, 	  -8,   -9, 	   8,   -9, 	   0,   -5
.2byte    3,   -8, 	  -6,   -9, 	   6,  -12, 	   0,   -6
.2byte    2,  -10, 	   5,  -13, 	  -7,  -10, 	   0,   -7
.2byte    5,   -8, 	   9,  -11, 	  -3,   -8, 	   1,   -5
.2byte    5,   -9, 	  -3,   -6, 	   0,  -11, 	   0,   -5
.2byte    3,  -11, 	  -4,  -12, 	  -6,   -8, 	  -2,   -7
.2byte    9,   -9, 	   2,  -12, 	   1,   -7, 	   2,   -6
.2byte    2,  -10, 	   5,   -8, 	  -6,  -13, 	   0,   -6
.2byte    1,  -10, 	  -7,  -12, 	   3,   -7, 	  -1,   -4
.2byte    4,  -10, 	  -4,  -14, 	   6,   -9, 	   1,   -7
.2byte    0,  -10, 	   8,  -10, 	  -8,  -10, 	   0,   -6
.2byte    0,  -10, 	   8,  -11, 	  -8,  -11, 	   0,   -5
.2byte    0,  -10, 	   9,  -10, 	  -8,  -10, 	  -1,   -6
.2byte   -3,  -10, 	   7,  -14, 	  -4,   -8, 	   1,   -6
.2byte   -1,  -10, 	   7,  -12, 	  -3,   -7, 	   1,   -4
.2byte   -4,  -10, 	   4,  -14, 	  -6,   -9, 	  -1,   -7
.2byte   -6,   -9, 	  -1,  -12, 	   3,   -7, 	   0,   -6
.2byte   -3,  -11, 	   4,  -12, 	   6,   -8, 	   2,   -7
.2byte   -9,   -9, 	  -2,  -12, 	  -1,   -7, 	  -2,   -6
.2byte   -3,   -8, 	  -7,  -13, 	   6,   -9, 	   0,   -6
.2byte   -2,  -10, 	  -5,  -13, 	   7,  -10, 	   0,   -7
.2byte   -5,   -8, 	  -9,  -11, 	   3,   -8, 	  -1,   -5
.2byte    0,   -8, 	  -9,  -10, 	   8,  -11, 	   0,   -6
.2byte    0,  -10, 	  -8,  -12, 	   8,  -12, 	   0,   -7
.2byte    0,   -6, 	  -8,   -9, 	   8,   -9, 	   0,   -5
.2byte    3,   -8, 	  -6,   -9, 	   6,  -12, 	   0,   -6
.2byte    2,  -10, 	   5,  -13, 	  -7,  -10, 	   0,   -7
.2byte    5,   -8, 	   9,  -11, 	  -3,   -8, 	   1,   -5
.2byte    5,   -9, 	  -3,   -6, 	   0,  -11, 	   0,   -5
.2byte    3,  -11, 	  -4,  -12, 	  -6,   -8, 	  -2,   -7
.2byte    9,   -9, 	   2,  -12, 	   1,   -7, 	   2,   -6
.2byte    2,  -10, 	   5,   -8, 	  -6,  -13, 	   0,   -6
.2byte    1,  -10, 	  -7,  -12, 	   3,   -7, 	  -1,   -4
.2byte    4,   -9, 	  -4,  -13, 	   6,   -8, 	   1,   -6
.2byte    0,  -10, 	   8,  -10, 	  -8,  -10, 	   0,   -6
.2byte    0,  -10, 	   8,  -11, 	  -8,  -11, 	   0,   -5
.2byte    0,  -10, 	   9,  -10, 	  -8,  -10, 	  -1,   -6
.2byte   -3,  -10, 	   7,  -14, 	  -4,   -8, 	   1,   -6
.2byte   -1,  -10, 	   7,  -12, 	  -3,   -7, 	   1,   -4
.2byte   -4,   -9, 	   4,  -13, 	  -6,   -8, 	  -1,   -6
.2byte   -6,   -9, 	  -1,  -12, 	   3,   -7, 	   0,   -6
.2byte   -3,  -11, 	   4,  -12, 	   6,   -8, 	   2,   -7
.2byte   -9,   -9, 	  -2,  -12, 	  -1,   -7, 	  -2,   -6
.2byte   -3,   -8, 	  -7,  -13, 	   6,   -9, 	   0,   -6
.2byte   -2,  -10, 	  -5,  -13, 	   7,  -10, 	   0,   -7
.2byte   -5,   -8, 	  -9,  -11, 	   3,   -8, 	  -1,   -5
.2byte   -1,   -6, 	  -6,  -10, 	   7,   -9, 	   1,   -5
.2byte   -1,   -4, 	  -7,   -9, 	   6,   -8, 	   1,   -4
.2byte    0,  -11, 	  -8,   -6, 	   7,   -6, 	   0,   -6
.2byte   -6,   -7, 	   1,   -6, 	  -7,   -2, 	  -3,   -6
.2byte   -6,  -11, 	  -5,   -6, 	  -1,   -6, 	   0,   -9
.2byte   -1,   -9, 	  -8,   -6, 	   2,   -2, 	   1,   -7
.2byte    0,   -7, 	   7,   -4, 	  -8,   -4, 	   0,   -9
.2byte    0,   -9, 	   7,   -6, 	  -3,   -2, 	  -2,   -7
.2byte    5,  -11, 	   4,   -6, 	   0,   -6, 	  -1,   -9
.2byte    5,   -7, 	  -2,   -6, 	   6,   -2, 	   2,   -6
.2byte    0,   -8, 	  -9,  -10, 	   8,  -11, 	   0,   -6
.2byte    1,   -8, 	  -8,  -13, 	   8,   -9, 	   1,   -6
.2byte    0,   -9, 	  -8,  -10, 	   8,  -14, 	   1,   -7
.2byte    2,   -8, 	  -7,   -9, 	   5,  -12, 	  -1,   -6
.2byte    4,  -10, 	  -4,  -12, 	   9,  -12, 	   2,   -8
.2byte    2,   -9, 	  -7,   -9, 	   5,  -14, 	   0,   -7
.2byte    5,   -9, 	  -3,   -6, 	   0,  -11, 	   0,   -5
.2byte    7,  -13, 	  -1,  -12, 	   2,  -13, 	   1,   -8
.2byte    6,   -9, 	  -2,   -7, 	   2,  -14, 	   1,   -7
.2byte    2,  -10, 	   5,   -8, 	  -6,  -13, 	   0,   -6
.2byte    1,  -12, 	   4,  -12, 	  -7,  -14, 	   0,   -7
.2byte    2,  -11, 	   5,   -7, 	  -5,  -15, 	   1,   -7
.2byte    0,  -10, 	   8,  -10, 	  -8,  -10, 	   0,   -6
.2byte   -1,  -13, 	   7,  -14, 	  -9,  -11, 	  -1,   -8
.2byte    1,  -12, 	   9,  -10, 	  -7,  -13, 	   1,   -7
.2byte   -3,  -10, 	   7,  -14, 	  -4,   -8, 	   1,   -6
.2byte   -2,   -9, 	   6,  -15, 	  -4,   -7, 	   1,   -7
.2byte   -1,  -11, 	   8,  -14, 	  -4,  -12, 	   1,   -8
.2byte   -6,   -9, 	  -1,  -12, 	   3,   -7, 	   0,   -6
.2byte   -5,   -9, 	   1,  -13, 	   3,   -7, 	   0,   -7
.2byte   -6,  -12, 	  -1,  -12, 	   3,  -11, 	   0,   -7
.2byte   -3,   -8, 	  -7,  -13, 	   6,   -9, 	   0,   -6
.2byte   -3,   -9, 	  -6,  -14, 	   6,   -9, 	   0,   -7
.2byte   -2,  -10, 	  -7,  -11, 	   6,  -12, 	   0,   -8
.2byte    0,   -6, 	  -8,   -9, 	   8,   -9, 	   0,   -5
.2byte   -5,   -8, 	  -9,  -11, 	   3,   -8, 	  -1,   -5
.2byte   -8,   -9, 	  -1,  -12, 	   0,   -7, 	  -1,   -6
.2byte   -4,   -9, 	   4,  -13, 	  -6,   -8, 	  -1,   -6
.2byte    0,  -10, 	   9,  -10, 	  -8,  -10, 	  -1,   -6
.2byte    4,   -9, 	  -4,  -13, 	   6,   -8, 	   1,   -6
.2byte    8,   -9, 	   1,  -12, 	   0,   -7, 	   1,   -6
.2byte    4,   -8, 	   8,  -11, 	  -4,   -8, 	   0,   -5
.2byte    0,   -6, 	  -8,   -9, 	   8,   -9, 	   0,   -5
.2byte    4,   -8, 	   8,  -11, 	  -4,   -8, 	   0,   -5
.2byte    8,   -9, 	   1,  -12, 	   0,   -7, 	   1,   -6
.2byte    4,   -9, 	  -4,  -13, 	   6,   -8, 	   1,   -6
.2byte    0,  -10, 	   9,  -10, 	  -8,  -10, 	  -1,   -6
.2byte   -4,   -9, 	   4,  -13, 	  -6,   -8, 	  -1,   -6
.2byte   -8,   -9, 	  -1,  -12, 	   0,   -7, 	  -1,   -6
.2byte   -5,   -8, 	  -9,  -11, 	   3,   -8, 	  -1,   -5
.2byte    0,   -8, 	  -9,  -10, 	   8,  -11, 	   0,   -6
.2byte    0,  -10, 	  -8,  -12, 	   8,  -12, 	   0,   -7
.2byte    0,   -6, 	  -8,   -9, 	   8,   -9, 	   0,   -5
.2byte    2,   -8, 	   6,  -13, 	  -7,   -9, 	  -1,   -6
.2byte    2,  -10, 	   5,  -13, 	  -7,  -10, 	   0,   -7
.2byte    3,   -8, 	   7,  -11, 	  -5,   -8, 	  -1,   -5
.2byte    6,   -9, 	   1,  -12, 	  -3,   -7, 	   0,   -6
.2byte    4,  -11, 	  -3,  -12, 	  -5,   -8, 	  -1,   -7
.2byte    6,   -9, 	  -1,  -12, 	  -2,   -7, 	  -1,   -6
.2byte    3,  -10, 	  -7,  -14, 	   4,   -8, 	  -1,   -6
.2byte    1,  -10, 	  -7,  -12, 	   3,   -7, 	  -1,   -4
.2byte    3,  -10, 	  -5,  -14, 	   5,   -9, 	   0,   -7
.2byte    0,  -10, 	   8,  -10, 	  -8,  -10, 	   0,   -6
.2byte    0,  -10, 	   8,  -11, 	  -8,  -11, 	   0,   -5
.2byte    0,  -10, 	   9,  -10, 	  -8,  -10, 	  -1,   -6
.2byte   -3,  -10, 	   7,  -14, 	  -4,   -8, 	   1,   -6
.2byte   -1,  -10, 	   7,  -12, 	  -3,   -7, 	   1,   -4
.2byte   -4,  -10, 	   4,  -14, 	  -6,   -9, 	  -1,   -7
.2byte   -6,   -9, 	  -1,  -12, 	   3,   -7, 	   0,   -6
.2byte   -4,  -11, 	   3,  -12, 	   5,   -8, 	   1,   -7
.2byte   -6,   -9, 	   1,  -12, 	   2,   -7, 	   1,   -6
.2byte   -3,   -8, 	  -7,  -13, 	   6,   -9, 	   0,   -6
.2byte   -2,  -10, 	  -5,  -13, 	   7,  -10, 	   0,   -7
.2byte   -3,   -8, 	  -7,  -11, 	   5,   -8, 	   1,   -5
.2byte    0,  -10, 	  -8,  -12, 	   8,  -12, 	   0,   -7
.2byte   -2,  -10, 	  -5,  -13, 	   7,  -10, 	   0,   -7
.2byte   -4,  -11, 	   3,  -12, 	   5,   -8, 	   1,   -7
.2byte   -1,  -11, 	   7,  -13, 	  -3,   -8, 	   1,   -5
.2byte    0,  -10, 	   8,  -11, 	  -8,  -11, 	   0,   -5
.2byte    1,  -11, 	  -7,  -13, 	   3,   -8, 	  -1,   -5
.2byte    3,  -11, 	  -4,  -12, 	  -6,   -8, 	  -2,   -7
.2byte    2,  -10, 	   5,  -13, 	  -7,  -10, 	   0,   -7
.2byte    0,   -8, 	  -9,  -10, 	   8,  -11, 	   0,   -6
.2byte   -3,   -8, 	  -7,  -13, 	   6,   -9, 	   0,   -6
.2byte   -6,   -9, 	  -1,  -12, 	   3,   -7, 	   0,   -6
.2byte   -3,  -10, 	   7,  -14, 	  -4,   -8, 	   1,   -6
.2byte    0,  -10, 	   8,  -10, 	  -8,  -10, 	   0,   -6
.2byte    2,  -10, 	   5,   -8, 	  -6,  -13, 	   0,   -6
.2byte    5,   -9, 	  -3,   -6, 	   0,  -11, 	   0,   -5
.2byte    3,   -8, 	  -6,   -9, 	   6,  -12, 	   0,   -6
sWooperAnimTable1:
.4byte sWooperAnims_1_1
.4byte sWooperAnims_1_2
.4byte sWooperAnims_1_3
.4byte sWooperAnims_1_4
.4byte sWooperAnims_1_5
.4byte sWooperAnims_1_6
.4byte sWooperAnims_1_7
.4byte sWooperAnims_1_8
sWooperAnimTable2:
.4byte sWooperAnims_2_1
.4byte sWooperAnims_2_2
.4byte sWooperAnims_2_3
.4byte sWooperAnims_2_4
.4byte sWooperAnims_2_5
.4byte sWooperAnims_2_6
.4byte sWooperAnims_2_7
.4byte sWooperAnims_2_8
sWooperAnimTable3:
.4byte sWooperAnims_3_1
.4byte sWooperAnims_3_2
.4byte sWooperAnims_3_3
.4byte sWooperAnims_3_4
.4byte sWooperAnims_3_5
.4byte sWooperAnims_3_6
.4byte sWooperAnims_3_7
.4byte sWooperAnims_3_8
sWooperAnimTable4:
.4byte sWooperAnims_4_1
.4byte sWooperAnims_4_2
.4byte sWooperAnims_4_3
.4byte sWooperAnims_4_4
.4byte sWooperAnims_4_5
.4byte sWooperAnims_4_6
.4byte sWooperAnims_4_7
.4byte sWooperAnims_4_8
sWooperAnimTable5:
.4byte sWooperAnims_5_1
.4byte sWooperAnims_5_2
.4byte sWooperAnims_5_3
.4byte sWooperAnims_5_4
.4byte sWooperAnims_5_5
.4byte sWooperAnims_5_6
.4byte sWooperAnims_5_7
.4byte sWooperAnims_5_8
sWooperAnimTable6:
.4byte sWooperAnims_6_1
.4byte sWooperAnims_6_1
.4byte sWooperAnims_6_1
.4byte sWooperAnims_6_1
.4byte sWooperAnims_6_1
.4byte sWooperAnims_6_1
.4byte sWooperAnims_6_1
.4byte sWooperAnims_6_1
sWooperAnimTable7:
.4byte sWooperAnims_7_1
.4byte sWooperAnims_7_2
.4byte sWooperAnims_7_3
.4byte sWooperAnims_7_4
.4byte sWooperAnims_7_5
.4byte sWooperAnims_7_6
.4byte sWooperAnims_7_7
.4byte sWooperAnims_7_8
sWooperAnimTable8:
.4byte sWooperAnims_8_1
.4byte sWooperAnims_8_2
.4byte sWooperAnims_8_3
.4byte sWooperAnims_8_4
.4byte sWooperAnims_8_5
.4byte sWooperAnims_8_6
.4byte sWooperAnims_8_7
.4byte sWooperAnims_8_8
sWooperAnimTable9:
.4byte sWooperAnims_9_1
.4byte sWooperAnims_9_2
.4byte sWooperAnims_9_3
.4byte sWooperAnims_9_4
.4byte sWooperAnims_9_5
.4byte sWooperAnims_9_6
.4byte sWooperAnims_9_7
.4byte sWooperAnims_9_8
sWooperAnimTable10:
.4byte sWooperAnims_10_1
.4byte sWooperAnims_10_2
.4byte sWooperAnims_10_3
.4byte sWooperAnims_10_4
.4byte sWooperAnims_10_5
.4byte sWooperAnims_10_6
.4byte sWooperAnims_10_7
.4byte sWooperAnims_10_8
sWooperAnimTable11:
.4byte sWooperAnims_11_1
.4byte sWooperAnims_11_2
.4byte sWooperAnims_11_3
.4byte sWooperAnims_11_4
.4byte sWooperAnims_11_5
.4byte sWooperAnims_11_6
.4byte sWooperAnims_11_7
.4byte sWooperAnims_11_8
sWooperAnimTable12:
.4byte sWooperAnims_12_1
.4byte sWooperAnims_12_2
.4byte sWooperAnims_12_3
.4byte sWooperAnims_12_4
.4byte sWooperAnims_12_5
.4byte sWooperAnims_12_6
.4byte sWooperAnims_12_7
.4byte sWooperAnims_12_8
sWooperAnimTable13:
.4byte sWooperAnims_13_1
.4byte sWooperAnims_13_2
.4byte sWooperAnims_13_3
.4byte sWooperAnims_13_4
.4byte sWooperAnims_13_5
.4byte sWooperAnims_13_6
.4byte sWooperAnims_13_7
.4byte sWooperAnims_13_8
sAxAnimationsWooper:
.4byte sWooperAnimTable1
.4byte sWooperAnimTable2
.4byte sWooperAnimTable3
.4byte sWooperAnimTable4
.4byte sWooperAnimTable5
.4byte sWooperAnimTable6
.4byte sWooperAnimTable7
.4byte sWooperAnimTable8
.4byte sWooperAnimTable9
.4byte sWooperAnimTable10
.4byte sWooperAnimTable11
.4byte sWooperAnimTable12
.4byte sWooperAnimTable13
sAxSpritesWooper:
.4byte sWooperSprites1
.4byte sWooperSprites2
.4byte sWooperSprites3
.4byte sWooperSprites4
.4byte sWooperSprites5
.4byte sWooperSprites6
.4byte sWooperSprites7
.4byte sWooperSprites8
.4byte sWooperSprites9
.4byte sWooperSprites10
.4byte sWooperSprites11
.4byte sWooperSprites12
.4byte sWooperSprites13
.4byte sWooperSprites14
.4byte sWooperSprites15
.4byte sWooperSprites16
.4byte sWooperSprites17
.4byte sWooperSprites18
.4byte sWooperSprites19
.4byte sWooperSprites20
.4byte sWooperSprites21
.4byte sWooperSprites22
.4byte sWooperSprites23
.4byte sWooperSprites24
.4byte sWooperSprites25
.4byte sWooperSprites26
.4byte sWooperSprites27
.4byte sWooperSprites28
.4byte sWooperSprites29
.4byte sWooperSprites30
.4byte sWooperSprites31
.4byte sWooperSprites32
.4byte sWooperSprites33
.4byte sWooperSprites34
.4byte sWooperSprites35
.4byte sWooperSprites36
.4byte sWooperSprites37
.4byte sWooperSprites38
.4byte sWooperSprites39
.4byte sWooperSprites40
.4byte sWooperSprites41
sAxMainWooper:
ax_main sAxPosesWooper, sAxAnimationsWooper, 13, sAxSpritesWooper, sAxPositionsWooper
