#ifndef GUARD_CONSTANTS_BG_MUSIC_H
#define GUARD_CONSTANTS_BG_MUSIC_H

enum MusicID
{
    MUS_RESCUE_TEAM_BASE = 1,
    MUS_FRIEND_AREA_SWAMP,
    MUS_FRIEND_AREA_CAVES,
    MUS_DREAM,
    MUS_BENEVOLENT_SPIRIT,
    MUS_LEGEND_OF_NINETALES,
    MUS_POKEMON_SQUARE,
    MUS_FILE_SELECT,
    MUS_RISING_FEAR,
    MUS_THERES_TROUBLE,
    MUS_BOSS_BATTLE,
    MUS_WELCOME_TO_THE_WORLD_OF_POKEMON,
    MUS_A_NEW_ADVENTURE, // Plays in Buried Relic and Southern Cavern
    MUS_THUNDERWAVE_CAVE,
    MUS_SINISTER_WOODS,
    MUS_FRIEND_AREA_POND,
    MUS_KECLEON_SHOP,
    MUS_STOP_THIEF,
    MUS_WORLD_CALAMITY, // GIANT_STAR_APPROACHING
    MUS_GREAT_CANYON,
    MUS_STORMY_SEA,
    MUS_SKY_TOWER,
    MUS_SKY_TOWER_SUMMIT,
    MUS_THE_ESCAPE,
    MUS_MT_BLAZE,
    MUS_RAYQUAZAS_DOMAIN,
    MUS_FRIEND_AREA_STRATOS_LOOKOUT,
    MUS_FRIEND_AREA_RAINBOW_PEAK,
    MUS_DREAM_EATER,
    MUS_FRIEND_AREA_DEEPSEA_CURRENT,
    MUS_FRIEND_AREA_SEAFLOOR_CAVE,
    MUS_BATTLE_WITH_RAYQUAZA,
    MUS_MT_BLAZE_PEAK,
    MUS_FRIEND_AREA_VOLCANIC_PIT,
    MUS_FRIEND_AREA_CRYPTIC_CAVE,
    MUS_ESCAPE_THROUGH_THE_SNOW,
    MUS_THE_OTHER_SIDE,
    MUS_THE_MOUNTAIN_OF_FIRE,
    MUS_FROSTY_GROTTO,
    MUS_INTRO,
    MUS_AFTERMATH,
    MUS_FAREWELL,
    MUS_TITLE_SCREEN,
    MUS_CREDITS,
    MUS_TIME_OF_REUNION,
    MUS_OPENING_TITLE,
    // 47 - 50 are blank/empty slots for BG Music
    MUS_DUNGEON_FAIL = 51,
    MUS_DUNGEON_COMPLETE,
    // 53 - 99 are blank/empty slots for BG Music
    MUS_FRIEND_AREA_UNUSED_1 = 100,
    MUS_HEARTWARMING,
    MUS_LAPIS_CAVE,
    MUS_A_SUCCESSFUL_RESCUE,
    MUS_FROSTY_FOREST,
    MUS_FRIEND_AREA_STEPPE,
    MUS_FRIEND_AREA_OCEANIC,
    MUS_FRIEND_AREA_FIELD,
    MUS_MAGMA_CAVERN,
    MUS_FRIEND_AREA_UNUSED_2,
    MUS_MAKUHITA_DOJO,
    MUS_MT_THUNDER,
    MUS_FRIEND_AREA_LAB,
    MUS_SILENT_CHASM,
    MUS_IN_THE_DEPTHS_OF_THE_PIT,
    MUS_MT_FREEZE,
    MUS_FRIEND_AREA_WILDS,
    MUS_FRIEND_AREA_LEGENDARY_ISLAND,
    MUS_FRIEND_AREA_SOUTHERN_ISLAND,
    MUS_FRIEND_AREA_ENCLOSED_ISLAND,
    MUS_MT_STEEL,
    MUS_FRIEND_AREA_FOREST,
    MUS_FRIEND_AREA_FINAL_ISLAND,
    MUS_MT_FREEZE_PEAK,
    MUS_MAGMA_CAVERN_PIT,
    MUS_TINY_WOODS,
    MUS_MT_THUNDER_PEAK,
    MUS_FRIEND_AREA_HEALING_FOREST,
    MUS_MONSTER_HOUSE
};
#define NUM_BG_SONGS MUS_MONSTER_HOUSE

enum DungeonMusicID
{
    DUNGEON_MUS_IN_THE_DEPTHS_OF_THE_PIT,
    DUNGEON_MUS_TINY_WOODS,
    DUNGEON_MUS_THUNDERWAVE_CAVE,
    DUNGEON_MUS_MT_STEEL,
    DUNGEON_MUS_SINISTER_WOODS,
    DUNGEON_MUS_SILENT_CHASM,
    DUNGEON_MUS_MT_THUNDER,
    DUNGEON_MUS_GREAT_CANYON,
    DUNGEON_MUS_LAPIS_CAVE,
    DUNGEON_MUS_MT_BLAZE,
    DUNGEON_MUS_FROSTY_FOREST,
    DUNGEON_MUS_MT_FREEZE,
    DUNGEON_MUS_MAGMA_CAVERN,
    DUNGEON_MUS_SKY_TOWER,
    DUNGEON_MUS_INDEX_14, // same as Tiny Woods
    DUNGEON_MUS_INDEX_15, // same as Tiny Woods
    DUNGEON_MUS_INDEX_17 = 17, // same as Tiny Woods
    DUNGEON_MUS_A_NEW_ADVENTURE,
    DUNGEON_MUS_STORMY_SEA,
    DUNGEON_MUS_MT_THUNDER_PEAK = 21,
    DUNGEON_MUS_MT_BLAZE_PEAK,
    DUNGEON_MUS_FROSTY_GROTTO,
    DUNGEON_MUS_MT_FREEZE_PEAK,
    DUNGEON_MUS_MAGMA_CAVERN_PIT,
    DUNGEON_MUS_SKY_TOWER_SUMMIT,
    DUNGEON_MUS_INDEX_32 = 32, // same as Tiny Woods
    DUNGEON_MUS_INDEX_37 = 37, // same as Tiny Woods
    DUNGEON_MUS_INDEX_40 = 40, // same as Rayquaza's Domain
    DUNGEON_MUS_MAKUHITA_DOJO,
    DUNGEON_MUS_SNOW_PATH, // same as Makuhita Dojo
    DUNGEON_MUS_INDEX_53 = 53, // same as Tiny Woods
    DUNGEON_MUS_SILVER_TRENCH_LUGIA = 73, // same as Tiny Woods
    DUNGEON_MUS_STORMY_SEA_KYOGRE // same as Tiny Woods
};

#endif //GUARD_CONSTANTS_BG_MUSIC_H
