#ifndef GUARD_BG_MUSIC_H
#define GUARD_BG_MUSIC_H 

#define MUS_TEAM_BASE 1
#define MUS_POKEMON_SQUARE 7
#define MUS_LOADING_SCREEN 8
#define MUS_THERES_TROUBLE 10
#define MUS_KECLEON_SHOP 17
#define MUS_STOP_THIEF 18
#define MUS_WORLD_CALAMITY 19
#define MUS_INTRO 40
#define MUS_TITLE_SCREEN 43
#define MUS_CREDITS 44
#define MUS_EPILOGUE 45
#define MUS_DUNGEON_FAIL 51
#define MUS_DUNGEON_COMPLETE 52

#define NUM_BG_SONGS 128

#endif //GUARD_BG_MUSIC_H
