#ifndef GUARD_CONSTANTS_BG_MUSIC_H
#define GUARD_CONSTANTS_BG_MUSIC_H

#define MUS_RESCUE_TEAM_BASE 1
#define MUS_FRIEND_AREA_SWAMP 2
#define MUS_FRIEND_AREA_CAVES 3
#define MUS_DREAM 4
#define MUS_BENEVOLENT_SPIRIT 5
#define MUS_LEGEND_OF_NINETALES 6
#define MUS_POKEMON_SQUARE 7
#define MUS_FILE_SELECT 8
#define MUS_RISING_FEAR 9
#define MUS_THERES_TROUBLE 10
#define MUS_BOSS_BATTLE 11
#define MUS_WELCOME_TO_THE_WORLD_OF_POKEMON 12
#define MUS_A_NEW_ADVENTURE 13 // Plays in Buried Relic and Southern Cavern
#define MUS_THUNDERWAVE_CAVE 14
#define MUS_SINISTER_WOODS 15
#define MUS_FRIEND_AREA_POND 16
#define MUS_KECLEON_SHOP 17
#define MUS_STOP_THIEF 18
#define MUS_WORLD_CALAMITY 19 // GIANT_STAR_APPROACHING
#define MUS_GREAT_CANYON 20
#define MUS_STORMY_SEA 21
#define MUS_SKY_TOWER 22
#define MUS_SKY_TOWER_SUMMIT 23
#define MUS_THE_ESCAPE 24
#define MUS_MT_BLAZE 25
#define MUS_RAYQUAZAS_DOMAIN 26
#define MUS_FRIEND_AREA_STRATOS_LOOKOUT 27
#define MUS_FRIEND_AREA_RAINBOW_PEAK 28
#define MUS_DREAM_EATER 29
#define MUS_FRIEND_AREA_DEEPSEA_CURRENT 30
#define MUS_FRIEND_AREA_SEAFLOOR_CAVE 31
#define MUS_BATTLE_WITH_RAYQUAZA 32
#define MUS_MT_BLAZE_PEAK 33
#define MUS_FRIEND_AREA_VOLCANIC_PIT 34
#define MUS_FRIEND_AREA_CRYPTIC_CAVE 35
#define MUS_ESCAPE_THROUGH_THE_SNOW 36
#define MUS_THE_OTHER_SIDE 37
#define MUS_THE_MOUNTAIN_OF_FIRE 38
#define MUS_FROSTY_GROTTO 39
#define MUS_INTRO 40
#define MUS_AFTERMATH 41
#define MUS_FAREWELL 42
#define MUS_TITLE_SCREEN 43
#define MUS_CREDITS 44
#define MUS_TIME_OF_REUNION 45
#define MUS_OPENING_TITLE 46
#define MUS_DUNGEON_FAIL 51
#define MUS_DUNGEON_COMPLETE 52

// 53 - 99 are blank/empty slots for BG Music

#define MUS_FRIEND_AREA_UNUSED_1 100
#define MUS_HEARTWARMING 101
#define MUS_LAPIS_CAVE 102
#define MUS_A_SUCCESSFUL_RESCUE 103
#define MUS_FROSTY_FOREST 104
#define MUS_FRIEND_AREA_STEPPE 105
#define MUS_FRIEND_AREA_OCEANIC 106
#define MUS_FRIEND_AREA_FIELD 107
#define MUS_MAGMA_CAVERN 108
#define MUS_FRIEND_AREA_UNUSED_2 109
#define MUS_MAKUHITA_DOJO 110
#define MUS_MT_THUNDER 111
#define MUS_FRIEND_AREA_LAB 112
#define MUS_SILENT_CHASM 113
#define MUS_IN_THE_DEPTHS_OF_THE_PIT 114
#define MUS_MT_FREEZE 115
#define MUS_FRIEND_AREA_WILDS 116
#define MUS_FRIEND_AREA_LEGENDARY_ISLAND 117
#define MUS_FRIEND_AREA_SOUTHERN_ISLAND 118
#define MUS_FRIEND_AREA_ENCLOSED_ISLAND 119
#define MUS_MT_STEEL 120
#define MUS_FRIEND_AREA_FOREST 121
#define MUS_FRIEND_AREA_FINAL_ISLAND 122
#define MUS_MT_FREEZE_PEAK 123
#define MUS_MAGMA_CAVERN_PIT 124
#define MUS_TINY_WOODS 125
#define MUS_MT_THUNDER_PEAK 126
#define MUS_FRIEND_AREA_HEALING_FOREST 127
#define MUS_MONSTER_HOUSE 128

#define NUM_BG_SONGS 128

#endif //GUARD_CONSTANTS_BG_MUSIC_H
