#ifndef GUARD_CONSTANTS_COLORS_H
#define GUARD_CONSTANTS_COLORS_H 

#define COLOR_WHITE 0
#define COLOR_BLUE 1
#define COLOR_RED 2
#define COLOR_BLACK 3
#define COLOR_GREEN 4
#define COLOR_CYAN 5
#define COLOR_YELLOW 6
#define COLOR_WHITE_2 7

#endif //GUARD_CONSTANTS_COLORS_H
