#ifndef GUARD_COMMON_STRINGS_MAKUHITA_DOJO_H
#define GUARD_COMMON_STRINGS_MAKUHITA_DOJO_H

enum MakuhitaDojoMode
{
    MAKUHITA_DOJO_MODE_AWAKE,
    MAKUHITA_DOJO_MODE_ASLEEP,
    MAKUHITA_DOJO_MODE_COUNT
};
enum MakuhitaDojoDialogue
{
    MAKUHITA_DLG_0,
    MAKUHITA_DLG_1,
    MAKUHITA_DLG_2,
    MAKUHITA_DLG_3,
    MAKUHITA_DLG_4,
    MAKUHITA_DLG_5,
    MAKUHITA_DLG_6,
    MAKUHITA_DLG_7,
    MAKUHITA_DLG_8,
    MAKUHITA_DLG_9,
    MAKUHITA_DLG_MAX
};

#endif // GUARD_COMMON_STRINGS_MAKUHITA_DOJO_H