#ifndef GUARD_COMMON_STRINGS_GULPIN_SHOP_H
#define GUARD_COMMON_STRINGS_GULPIN_SHOP_H

enum GulpinShopMode
{
    GULPIN_SHOP_MODE_AWAKE,
    GULPIN_SHOP_MODE_ASLEEP,
    GULPIN_SHOP_MODE_UNK2,
    GULPIN_SHOP_MODE_DIALOGUE_COUNT = 2
};
enum GulpinShopDialogue
{
    GULPIN_DLG_00,
    GULPIN_DLG_01,
    GULPIN_DLG_02,
    GULPIN_DLG_03,
    GULPIN_DLG_04,
    GULPIN_DLG_05,
    GULPIN_DLG_06,
    GULPIN_DLG_07,
    GULPIN_DLG_08,
    GULPIN_DLG_09,
    GULPIN_DLG_10,
    GULPIN_DLG_11,
    GULPIN_DLG_12,
    GULPIN_DLG_13,
    GULPIN_DLG_14,
    GULPIN_DLG_15,
    GULPIN_DLG_16,
    GULPIN_DLG_17,
    GULPIN_DLG_18,
    GULPIN_DLG_19,
    GULPIN_DLG_20,
    GULPIN_DLG_21,
    GULPIN_DLG_22,
    GULPIN_DLG_23,
    GULPIN_DLG_24,
    GULPIN_DLG_MAX
};

#endif // GUARD_COMMON_STRINGS_GULPIN_SHOP_H