#ifndef GUARD_COMMON_STRINGS_KECLEON_BROS_H
#define GUARD_COMMON_STRINGS_KECLEON_BROS_H

enum KecleonBrosMode
{
    KECLEON_BROS_MODE_ITEMS_AWAKE,
    KECLEON_BROS_MODE_ITEMS_ASLEEP,
    KECLEON_BROS_MODE_WARES_AWAKE,
    KECLEON_BROS_MODE_WARES_ASLEEP,
    KECLEON_BROS_MODE_COUNT
};
enum KecleonBrosDialogue
{
    KECLEON_DLG_00,
    KECLEON_DLG_01,
    KECLEON_DLG_02,
    KECLEON_DLG_03,
    KECLEON_DLG_04,
    KECLEON_DLG_05,
    KECLEON_DLG_06,
    KECLEON_DLG_07,
    KECLEON_DLG_08,
    KECLEON_DLG_09,
    KECLEON_DLG_10,
    KECLEON_DLG_11,
    KECLEON_DLG_12,
    KECLEON_DLG_13,
    KECLEON_DLG_14,
    KECLEON_DLG_15,
    KECLEON_DLG_16,
    KECLEON_DLG_17,
    KECLEON_DLG_18,
    KECLEON_DLG_19,
    KECLEON_DLG_20,
    KECLEON_DLG_21,
    KECLEON_DLG_22,
    KECLEON_DLG_MAX
};

#endif // GUARD_COMMON_STRINGS_KECLEON_BROS_H