// NOTE: all communications use the same error codes so we define them here

#define COMMS_GOOD  0
#define COMMS_NO_RESPONSE  2
#define COMMS_INCORRECT_NUM_SYSTEMS 3
#define COMMS_DIFFERENT_MODES 4
#define COMMS_NO_ROOM_STORAGE 6
#define COMMS_DUPLICATE_MAIL 7
#define COMMS_MAIL_SENT_ALREADY 8
#define COMMS_NOT_ELIGIBLE_1 9
#define COMMS_FRIEND_NOT_ELIGIBLE 10
#define COMMS_NOT_ELIGIBLE_2 11
#define COMMS_FRIEND_NOT_ELIGIBLE_2 12
#define COMMS_NO_ROOM_MAIL 13
#define COMMS_NOT_READY 15

