#ifndef GUARD_COMMON_STRINGS_WIGGLYTUFF_SHOP_H
#define GUARD_COMMON_STRINGS_WIGGLYTUFF_SHOP_H

enum WigglytuffShopMode
{
    WIGGLYTUFF_SHOP_MODE_AWAKE,
    WIGGLYTUFF_SHOP_MODE_ASLEEP,
    WIGGLYTUFF_SHOP_MODE_COUNT
};
enum WigglytuffShopDialogue
{
    WIGGLY_DLG_00,
    WIGGLY_DLG_01,
    WIGGLY_DLG_02,
    WIGGLY_DLG_03,
    WIGGLY_DLG_04,
    WIGGLY_DLG_05,
    WIGGLY_DLG_06,
    WIGGLY_DLG_07,
    WIGGLY_DLG_08,
    WIGGLY_DLG_09,
    WIGGLY_DLG_10,
    WIGGLY_DLG_11,
    WIGGLY_DLG_12,
    WIGGLY_DLG_13,
    WIGGLY_DLG_14,
    WIGGLY_DLG_15,
    WIGGLY_DLG_16,
    WIGGLY_DLG_17,
    WIGGLY_DLG_18,
    WIGGLY_DLG_19,
    WIGGLY_DLG_MAX
};

#endif // GUARD_COMMON_STRINGS_WIGGLYTUFF_SHOP_H