#ifndef GUARD_CONSTANTS_CUTSCENES_H
#define GUARD_CONSTANTS_CUTSCENES_H

enum CutsceneKind
{
    CUTSCENE_NONE,
    CUTSCENE_MT_STEEL_ATTEMPT1,
    CUTSCENE_MT_STEEL_ATTEMPT2,
    CUTSCENE_MT_STEEL_POSTSTORY,
    CUTSCENE_SINISTER_WOODS_ATTEMPT1,
    CUTSCENE_SINISTER_WOODS_ATTEMPT2,
    CUTSCENE_SINISTER_WOODS_POSTSTORY,
    CUTSCENE_MT_THUNDER_PEAK_ATTEMPT1,
    CUTSCENE_MT_THUNDER_PEAK_ATTEMPT2,
    CUTSCENE_MT_THUNDER_PEAK_POSTSTORY,
    CUTSCENE_MT_BLAZE_PEAK_ATTEMPT1,
    CUTSCENE_MT_BLAZE_PEAK_ATTEMPT2,
    CUTSCENE_MT_BLAZE_PEAK_POSTSTORY,
    CUTSCENE_FROSTY_GROTTO_ATTEMPT1,
    CUTSCENE_FROSTY_GROTTO_ATTEMPT2,
    CUTSCENE_FROSTY_GROTTO_POSTSTORY,
    CUTSCENE_MT_FREEZE_PEAK,
    CUTSCENE_MT_FREEZE_PEAK_POSTSTORY,
    CUTSCENE_MAGMA_CAVERN_PIT_ATTEMPT1,
    CUTSCENE_MAGMA_CAVERN_PIT_ATTEMPT2,
    CUTSCENE_MAGMA_CAVERN_PIT_POSTSTORY,
    CUTSCENE_MAGMA_CAVERN_MID,
    CUTSCENE_MAGMA_CAVERN_MID_POSTSTORY,
    CUTSCENE_SKY_TOWER_SUMMIT_ATTEMPT1,
    CUTSCENE_SKY_TOWER_SUMMIT_ATTEMPT2,
    CUTSCENE_SKY_TOWER_SUMMIT_POSTSTORY,
    CUTSCENE_UPROAR_FOREST_ATTEMPT1,
    CUTSCENE_UPROAR_FOREST_ATTEMPT2,
    CUTSCENE_UPROAR_FOREST_POSTSTORY,
    CUTSCENE_WESTERN_CAVE_ATTEMPT1,
    CUTSCENE_WESTERN_CAVE_ATTEMPT2,
    CUTSCENE_WESTERN_CAVE_POSTSTORY,
    CUTSCENE_FIERY_FIELD_ATTEMPT1,
    CUTSCENE_FIERY_FIELD_ATTEMPT2,
    CUTSCENE_FIERY_FIELD_POSTSTORY,
    CUTSCENE_LIGHTNING_FIELD_ATTEMPT1,
    CUTSCENE_LIGHTNING_FIELD_ATTEMPT2,
    CUTSCENE_LIGHTNING_FIELD_POSTSTORY,
    CUTSCENE_NORTHWIND_FIELD_ATTEMPT1,
    CUTSCENE_NORTHWIND_FIELD_ATTEMPT2,
    CUTSCENE_NORTHWIND_FIELD_POSTSTORY,
    CUTSCENE_MT_FARAWAY,
    CUTSCENE_MT_FARAWAY_POSTSTORY,
    CUTSCENE_NORTHERN_RANGE_ATTEMPT1,
    CUTSCENE_NORTHERN_RANGE_ATTEMPT2,
    CUTSCENE_NORTHERN_RANGE_POSTSTORY,
    CUTSCENE_REGIROCK,
    CUTSCENE_REGICE,
    CUTSCENE_REGISTEEL,
    CUTSCENE_JIRACHI,
    CUTSCENE_JIRACHI_POSTSTORY,
    CUTSCENE_SILVER_TRENCH,
    CUTSCENE_STORMY_SEA,
    CUTSCENE_METEOR_CAVE,
    CUTSCENE_PURITY_FOREST,
    CUTSCENE_MAZE_BOSS,
    CUTSCENE_MEDICHAM,
    CUTSCENE_MEDICHAM_POSTSTORY,
    CUTSCENE_HOWLING_FOREST,
    CUTSCENE_HOWLING_FOREST_POSTSTORY,

    NUM_CUTSCENES
};

enum CutsceneFlagID
{
    CUTSCENE_FLAG_MT_STEEL_REACHED,
    CUTSCENE_FLAG_MT_STEEL_COMPLETE,
    CUTSCENE_FLAG_SINISTER_WOODS_REACHED,
    CUTSCENE_FLAG_SINISTER_WOODS_COMPLETE,
    CUTSCENE_FLAG_MT_THUNDER_PEAK_REACHED,
    CUTSCENE_FLAG_MT_THUNDER_PEAK_COMPLETE,
    CUTSCENE_FLAG_MT_BLAZE_PEAK_REACHED,
    CUTSCENE_FLAG_MT_BLAZE_PEAK_COMPLETE,
    CUTSCENE_FLAG_FROSTY_GROTTO_REACHED,
    CUTSCENE_FLAG_FROSTY_GROTTO_COMPLETE,
    CUTSCENE_FLAG_MT_FREEZE_PEAK_COMPLETE,
    CUTSCENE_FLAG_MAGMA_CAVERN_PIT_REACHED,
    CUTSCENE_FLAG_MAGMA_CAVERN_PIT_COMPLETE,
    CUTSCENE_FLAG_MAGMA_CAVERN_MID_REACHED,
    CUTSCENE_FLAG_SKY_TOWER_SUMMIT_REACHED,
    CUTSCENE_FLAG_SKY_TOWER_SUMMIT_COMPLETE,
    CUTSCENE_FLAG_UPROAR_FOREST_REACHED,
    CUTSCENE_FLAG_UPROAR_FOREST_COMPLETE,
    CUTSCENE_FLAG_WESTERN_CAVE_REACHED,
    CUTSCENE_FLAG_WESTERN_CAVE_COMPLETE,
    CUTSCENE_FLAG_FIERY_FIELD_REACHED,
    CUTSCENE_FLAG_FIERY_FIELD_COMPLETE,
    CUTSCENE_FLAG_LIGHTNING_FIELD_REACHED,
    CUTSCENE_FLAG_LIGHTNING_FIELD_COMPLETE,
    CUTSCENE_FLAG_NORTHWIND_FIELD_REACHED,
    CUTSCENE_FLAG_NORTHWIND_FIELD_COMPLETE,
    CUTSCENE_FLAG_MT_FARAWAY_COMPLETE,
    CUTSCENE_FLAG_NORTHERN_RANGE_REACHED,
    CUTSCENE_FLAG_NORTHERN_RANGE_COMPLETE,
    // Written to when entering a Regi room:
    // If the Regi was recruited before, this is set to TRUE.
    // If the Regi "Part" or Music Box is in the inventory or held, this is set to TRUE.
    // Otherwise, this is set to FALSE.
    // If this is TRUE and the Regi is present, the Regi can be recruited.
    CUTSCENE_FLAG_REGI_ITEM_OBTAINED,
    CUTSCENE_FLAG_JIRACHI_COMPLETE,
    CUTSCENE_FLAG_FROSTY_FOREST_INTRUDED,
    CUTSCENE_FLAG_MEDICHAM_COMPLETE,
    CUTSCENE_FLAG_HOWLING_FOREST_COMPLETE,
    // Written to when entering a Regi room.
    // If the Regi was recruited before, this is set to TRUE.
    // Otherwise, this is set to FALSE.
    CUTSCENE_FLAG_REGI_RECRUITED,

    NUM_CUTSCENE_FLAGS = 64,

    CUTSCENE_FLAG_INVALID = 0xFF,
};

#define CUTSCENE_FLAGS_U32STORAGE 3 // No idea why this is larger than necessary

#endif // GUARD_CONSTANTS_CUTSCENES_H
