#ifndef GUARD_CONSTANTS_DIRECTION_H
#define GUARD_CONSTANTS_DIRECTION_H

#define DIRECTION_MASK 7

enum Direction
{
    DIRECTION_SOUTH,
    DIRECTION_SOUTHEAST,
    DIRECTION_EAST,
    DIRECTION_NORTHEAST,
    DIRECTION_NORTH,
    DIRECTION_NORTHWEST,
    DIRECTION_WEST,
    DIRECTION_SOUTHWEST,
    NUM_DIRECTIONS
};

#endif
