#ifndef GUARD_CONSTANTS_DUNGEON_EXIT_H
#define GUARD_CONSTANTS_DUNGEON_EXIT_H

// constants start at this value
#define DUNGEON_EXIT_REASON_START 500

// reasons after this value are considered successful exits
#define DUNGEON_EXIT_REASON_SUCCESS 550

enum DungeonExitReason
{
    DUNGEON_EXIT_TRANSFORMED_INTO_FRIEND = DUNGEON_EXIT_REASON_START,
    DUNGEON_EXIT_LEFT_WITHOUT_BEING_BEFRIENDED,
    DUNGEON_EXIT_FAINTED_FROM_DEBUG_ATTACK,
    DUNGEON_EXIT_MISSED_JUMP_KICK,
    DUNGEON_EXIT_MISSED_HI_JUMP_KICK,
    DUNGEON_EXIT_FAINTED_FROM_DESTINY_BOND,
    DUNGEON_EXIT_FAINTED_COVERED_IN_SLUDGE,
    DUNGEON_EXIT_UNUSED_507,
    DUNGEON_EXIT_UNUSED_508,
    DUNGEON_EXIT_FAINTED_FROM_RECOIL,
    DUNGEON_EXIT_FAINTED_FROM_DAMAGE_BOUNCING,
    DUNGEON_EXIT_DEFEATED_PENT_UP_ENERGY,
    DUNGEON_EXIT_UNUSED_512,
    DUNGEON_EXIT_UNUSED_513,
    DUNGEON_EXIT_UNUSED_514,
    DUNGEON_EXIT_UNUSED_515,
    DUNGEON_EXIT_UNUSED_516,
    DUNGEON_EXIT_UNUSED_517,
    DUNGEON_EXIT_FAINTED_FROM_SPIKES,
    DUNGEON_EXIT_DEBUG_DAMAGE,
    DUNGEON_EXIT_FAINTED_FROM_BURN,
    DUNGEON_EXIT_FAINTED_FROM_CONSTRICTION,
    DUNGEON_EXIT_FAINTED_FROM_POISON,
    DUNGEON_EXIT_FAINTED_FROM_WRAP,
    DUNGEON_EXIT_FELLED_BY_CURSE,
    DUNGEON_EXIT_DRAINED_BY_LEECH_SEED,
    DUNGEON_EXIT_FAINTED_FROM_PERISH_SONG,
    DUNGEON_EXIT_FAINTED_WHILE_IN_NIGHTMARE,
    DUNGEON_EXIT_FELLED_BY_THROWN_ROCK,
    DUNGEON_EXIT_FAINTED_FROM_HUNGER,
    DUNGEON_EXIT_DISAPPEARED_IN_EXPLOSION,
    DUNGEON_EXIT_TRIPPED_CHESTNUT_TRAP,
    DUNGEON_EXIT_FAINTED_DUE_TO_TRAP,
    DUNGEON_EXIT_FELL_INTO_PITFALL,
    DUNGEON_EXIT_DEFEATED_BLAST_SEED,
    DUNGEON_EXIT_FELLED_BY_THROWN_ITEM,
    DUNGEON_EXIT_TRANSFORMED_INTO_ITEM,
    DUNGEON_EXIT_FAINTED_FROM_BEING_KNOCKED,
    DUNGEON_EXIT_FELLED_BY_POKEMON_FLYING,
    DUNGEON_EXIT_GAVE_UP_EXPLORATION,
    DUNGEON_EXIT_DELETED_FOR_EVENT,
    DUNGEON_EXIT_WENT_AWAY,
    DUNGEON_EXIT_BLOWN_OUT_UNSEEN_FORCE,
    DUNGEON_EXIT_RETURNED_WITH_FALLEN_PARTNER,
    DUNGEON_EXIT_FAINTED_DUE_TO_WEATHER,
    DUNGEON_EXIT_WAS_POSSESSED,
    DUNGEON_EXIT_FAILED_TO_PROTECT_CLIENT,
    DUNGEON_EXIT_FAINTED_FROM_WONDER_ORB,
    DUNGEON_EXIT_FAINTED_FROM_ITEM,
    DUNGEON_EXIT_UNUSED_549,

    DUNGEON_EXIT_ESCAPED_MIDDLE_OF_EXPLORATION = DUNGEON_EXIT_REASON_SUCCESS,
    DUNGEON_EXIT_CLEARED_DUNGEON,
    DUNGEON_EXIT_SUCCEEDED_IN_RESCUE_MISSION,
    DUNGEON_EXIT_IMPRESSIVELY_COMPLETED_MISSION,
    DUNGEON_EXIT_BEFRIENDED_MEW,
};

#define NUM_DUNGEON_EXIT_REASONS 55

#endif
