#ifndef GUARD_CONSTANTS_EMOTIONS_H
#define GUARD_CONSTANTS_EMOTIONS_H

#define EMOTION_NORMAL 0
#define EMOTION_HAPPY 1
#define EMOTION_PAINED 2
#define EMOTION_ANGRY 3
#define EMOTION_WORRIED 4
#define EMOTION_SAD 5
#define EMOTION_CRYING 6
#define EMOTION_SHOUTING 7
#define EMOTION_TEARY_EYE 8
#define EMOTION_DETERMINED 9
#define EMOTION_JOYOUS 10
#define EMOTION_INSPIRED 11
#define EMOTION_SUPRISED 12
#define EMOTION_DIZZY 13
#define EMOTION_SIGH 16
#define EMOTION_STUNNED 17
#define MAX_EMOTIONS 20

#endif // GUARD_CONSTANTS_EMOTIONS_H
