#ifndef GUARD_CONSTANTS_EMOTIONS_H
#define GUARD_CONSTANTS_EMOTIONS_H

#define EMOTION_NORMAL 0
#define EMOTION_HAPPY 2
#define EMOTION_PAINED 4
#define EMOTION_ANGRY 6
#define EMOTION_WORRIED 8
#define EMOTION_SAD 10
#define EMOTION_CRYING 12
#define EMOTION_SHOUTING 14
#define EMOTION_TEARY_EYE 16
#define EMOTION_DETERMINED 18
#define EMOTION_JOYOUS 20
#define EMOTION_INSPIRED 22
#define EMOTION_SUPRISED 24
#define EMOTION_DIZZY 26
#define EMOTION_SIGH 32
#define EMOTION_STUNNED 34
#define MAX_EMOTIONS 40

#endif // GUARD_CONSTANTS_EMOTIONS_H
