#ifndef GUARD_CONSTANTS_EVOLUTION_STATUS_H
#define GUARD_CONSTANTS_EVOLUTION_STATUS_H


#define EVOLUTION_GOOD  1
#define EVOLUTION_LACK_LEVEL  1 << 1
#define EVOLUTION_NO_MORE  1 << 2
#define EVOLUTION_LACK_ITEM  1 << 3
#define EVOLUTION_LACK_IQ  1 << 4
#define EVOLUTION_LACK_FRIEND_AREA  1 << 5
#define EVOLUTION_LACK_ROOM  1 << 6

#endif // GUARD_CONSTANTS_EVOLUTION_STATUS_H
