#ifndef GUARD_CONSTANTS_EVOLVE_TYPE_H
#define GUARD_CONSTANTS_EVOLVE_TYPE_H

#define EVOLVE_TYPE_NONE 0
#define EVOLVE_TYPE_LEVEL 1
#define EVOLVE_TYPE_IQ 2
#define EVOLVE_TYPE_ITEM 3
#define EVOLVE_TYPE_LINK_CABLE 13

#endif
