#ifndef GUARD_CONSTANTS_FIXED_ROOMS_H
#define GUARD_CONSTANTS_FIXED_ROOMS_H

enum FixedRoomID
{
    // floorwide fixed rooms
    FIXED_ROOM_NONE,
    FIXED_ROOM_MT_STEEL_SKARMORY,
    FIXED_ROOM_SINISTER_WOODS_TEAM_MEANIES,
    FIXED_ROOM_MT_THUNDER_PEAK_ZAPDOS,
    FIXED_ROOM_MT_BLAZE_PEAK_MOLTRES,
    FIXED_ROOM_FROSTY_GROTTO_ARTICUNO,
    FIXED_ROOM_MT_FREEZE_PEAK_NINETALES,
    FIXED_ROOM_MAGMA_CAVERN_PIT_GROUDON,
    FIXED_ROOM_SKY_TOWER_SUMMIT_RAYQUAZA,
    FIXED_ROOM_WESTERN_CAVE_MEWTWO,
    FIXED_ROOM_WISH_CAVE_JIRACHI,
    FIXED_ROOM_UPROAR_FOREST_MANKEY,
    FIXED_ROOM_FIERY_FIELD_ENTEI,
    FIXED_ROOM_LIGHTNING_FIELD_RAIKOU,
    FIXED_ROOM_NORTHWIND_FIELD_SUICUNE,
    FIXED_ROOM_MT_FARAWAY_HO_OH,
    FIXED_ROOM_NORTHERN_RANGE_LATIOS,
    FIXED_ROOM_BURIED_RELIC_REGIROCK,
    FIXED_ROOM_BURIED_RELIC_REGICE,
    FIXED_ROOM_BURIED_RELIC_REGISTEEL,
    FIXED_ROOM_MAGMA_CAVERN_PIT_TYRANITAR_ALAKAZAM,
    FIXED_ROOM_SILVER_TRENCH_LUGIA,
    FIXED_ROOM_STORMY_SEA_KYOGRE,
    FIXED_ROOM_METEOR_CAVE_DEOXYS,
    FIXED_ROOM_HOWLING_FOREST_SMEARGLE,
    FIXED_ROOM_PURITY_FOREST_CELEBI,
    FIXED_ROOM_WISH_CAVE_MEDICHAM,
    // Mazes
    FIXED_ROOM_NORMAL_MAZE_BOSS,
    FIXED_ROOM_FIRE_MAZE_BOSS,
    FIXED_ROOM_WATER_MAZE_BOSS,
    FIXED_ROOM_GRASS_MAZE_BOSS,
    FIXED_ROOM_ELECTRIC_MAZE_BOSS,
    FIXED_ROOM_ICE_MAZE_BOSS,
    FIXED_ROOM_FIGHTING_MAZE_BOSS,
    FIXED_ROOM_GROUND_MAZE_BOSS,
    FIXED_ROOM_FLYING_MAZE_BOSS,
    FIXED_ROOM_PSYCHIC_MAZE_BOSS,
    FIXED_ROOM_POISON_MAZE_BOSS,
    FIXED_ROOM_BUG_MAZE_BOSS,
    FIXED_ROOM_ROCK_MAZE_BOSS,
    FIXED_ROOM_GHOST_MAZE_BOSS,
    FIXED_ROOM_DRAGON_MAZE_BOSS,
    FIXED_ROOM_DARK_MAZE_BOSS,
    FIXED_ROOM_STEEL_MAZE_BOSS,
    FIXED_ROOM_TEAM_SHIFTY_BOSS,
    FIXED_ROOM_TEAM_CONSTRICTOR_BOSS,
    FIXED_ROOM_TEAM_HYDRO_BOSS,
    FIXED_ROOM_TEAM_RUMBLEROCK_BOSS,
    FIXED_ROOM_RESCUE_TEAM_2_BOSS,
    FIXED_ROOM_RESCUE_TEAM_MAZE_BOSS,
    // Non-floorwide fixed rooms
    FIXED_ROOM_WYVERN_HILL_HM_FLY,
    FIXED_ROOM_SOLAR_CAVE_HM_DIVE,
    FIXED_ROOM_SOLAR_CAVE_HM_WATERFALL,
    FIXED_ROOM_SOLAR_CAVE_HM_SURF,
    FIXED_ROOM_FAR_OFF_SEA_TM_WIDE_SLASH,
    FIXED_ROOM_FAR_OFF_SEA_TM_VACUUM_CUT,
    FIXED_ROOM_MT_FARAWAY_FRIEND_BOW,
    FIXED_ROOM_WYVERN_HILL_SUN_RIBBON,
    FIXED_ROOM_NORTHWIND_FIELD_LUNAR_RIBBON,
    FIXED_ROOM_WESTERN_CAVE_BEAUTY_SCARF,
    FIXED_ROOM_BURIED_RELIC_HM_CUT,
    FIXED_ROOM_BURIED_RELIC_HM_STRENGTH,
    FIXED_ROOM_BURIED_RELIC_HM_FLASH,
    FIXED_ROOM_BURIED_RELIC_HM_ROCK_SMASH,
    FIXED_ROOM_GRAND_SEA_DEEPSEASCALE,
    FIXED_ROOM_WISH_CAVE_WISH_STONE,
    FIXED_ROOM_GRAND_SEA_DEEPSEATOOTH
};

#define FIRST_DOJO_MAZE_BOSS_ROOM FIXED_ROOM_NORMAL_MAZE_BOSS
#define LAST_DOJO_MAZE_BOSS_ROOM FIXED_ROOM_RESCUE_TEAM_MAZE_BOSS
#define NUM_MAZE_BOSS_ROOMS LAST_DOJO_MAZE_BOSS_ROOM - FIRST_DOJO_MAZE_BOSS_ROOM
#define LAST_FLOORWIDE_FIXED_ROOM FIXED_ROOM_RESCUE_TEAM_MAZE_BOSS
#define FIRST_NON_FLOORWIDE_FIXED_ROOM LAST_FLOORWIDE_FIXED_ROOM + 1

#endif