#ifndef GUARD_CONSTANTS_FRIEND_AREA_H
#define GUARD_CONSTANTS_FRIEND_AREA_H


#define NUM_FRIEND_AREAS 58

// Unlock Condition
#define UNLOCK_SHOP_STORY 0
#define UNLOCK_SHOP_POST_GAME 1
#define UNLOCK_WONDER_MAIL 2
#define UNLOCK_LEGENDARY_REQUEST 3

#define NONE 0
#define BOUNTIFUL_SEA 1
#define TREASURE_SEA 2
#define SERENE_SEA 3
#define DEEP_SEA_FLOOR 4
#define DEEP_SEA_CURRENT 5
#define SEAFLOOR_CAVE 6
#define SHALLOW_BEACH 7
#define MT_DEEPGREEN 8
#define MT_CLEFT 9
#define MT_MOONVIEW 10
#define RAINBOW_PEAK 11
#define WILD_PLAINS 12
#define BEAU_PLAINS 13
#define SKY_BLUE_PLAINS 14
#define SAFARI 15
#define SCORCHED_PLAINS 16
#define SACRED_FIELD 17
#define MIST_RISE_FOREST 18
#define FLYAWAY_FOREST 19
#define OVERGROWN_FOREST 20
#define ENERGETIC_FOREST 21
#define MUSHROOM_FOREST 22
#define HEALING_FOREST 23
#define TRANSFORM_FOREST 24
#define SECRETIVE_FOREST 25
#define RUB_A_DUB_RIVER 26
#define TADPOLE_POND 27
#define TURTLESHELL_POND 28
#define MYSTIC_LAKE 29
#define WATERFALL_LAKE 30
#define PEANUT_SWAMP 31
#define POISON_SWAMP 32
#define ECHO_CAVE 33
#define CRYPTIC_CAVE 34
#define DRAGON_CAVE 35
#define BOULDER_CAVE 36
#define JUNGLE 37
#define DECREPIT_LAB 38
#define MT_DISCIPLINE 39
#define THUNDER_MEADOW 40
#define POWER_PLANT 41
#define CRATER 42
#define FURNACE_DESERT 43
#define AGED_CHAMBER_AN 44
#define AGED_CHAMBER_O_EXCLAIM 45
#define ANCIENT_RELIC 46
#define DARKNESS_RIDGE 47
#define FRIGID_CAVERN 48
#define ICE_FLOE_BEACH 49
#define VOLCANIC_PIT 50
#define STRATOS_LOOKOUT 51
#define RAVAGED_FIELD 52
#define MAGNETIC_QUARRY 53
#define LEGENDARY_ISLAND 54
#define SOUTHERN_ISLAND 55
#define ENCLOSED_ISLAND 56
#define FINAL_ISLAND 57

#endif
