#ifndef GUARD_CONSTANTS_FRIEND_AREA_H
#define GUARD_CONSTANTS_FRIEND_AREA_H

// Unlock Condition
#define UNLOCK_SHOP_STORY 0
#define UNLOCK_SHOP_POST_GAME 1
#define UNLOCK_WONDER_MAIL 2
#define UNLOCK_LEGENDARY_REQUEST 3

#define FRIEND_AREA_NONE                    0
#define FRIEND_AREA_BOUNTIFUL_SEA           1
#define FRIEND_AREA_TREASURE_SEA            2
#define FRIEND_AREA_SERENE_SEA              3
#define FRIEND_AREA_DEEP_SEA_FLOOR          4
#define FRIEND_AREA_DEEP_SEA_CURRENT        5
#define FRIEND_AREA_SEAFLOOR_CAVE           6
#define FRIEND_AREA_SHALLOW_BEACH           7
#define FRIEND_AREA_MT_DEEPGREEN            8
#define FRIEND_AREA_MT_CLEFT                9
#define FRIEND_AREA_MT_MOONVIEW             10
#define FRIEND_AREA_RAINBOW_PEAK            11
#define FRIEND_AREA_WILD_PLAINS             12
#define FRIEND_AREA_BEAU_PLAINS             13
#define FRIEND_AREA_SKY_BLUE_PLAINS         14
#define FRIEND_AREA_SAFARI                  15
#define FRIEND_AREA_SCORCHED_PLAINS         16
#define FRIEND_AREA_SACRED_FIELD            17
#define FRIEND_AREA_MIST_RISE_FOREST        18
#define FRIEND_AREA_FLYAWAY_FOREST          19
#define FRIEND_AREA_OVERGROWN_FOREST        20
#define FRIEND_AREA_ENERGETIC_FOREST        21
#define FRIEND_AREA_MUSHROOM_FOREST         22
#define FRIEND_AREA_HEALING_FOREST          23
#define FRIEND_AREA_TRANSFORM_FOREST        24
#define FRIEND_AREA_SECRETIVE_FOREST        25
#define FRIEND_AREA_RUB_A_DUB_RIVER         26
#define FRIEND_AREA_TADPOLE_POND            27
#define FRIEND_AREA_TURTLESHELL_POND        28
#define FRIEND_AREA_MYSTIC_LAKE             29
#define FRIEND_AREA_WATERFALL_LAKE          30
#define FRIEND_AREA_PEANUT_SWAMP            31
#define FRIEND_AREA_POISON_SWAMP            32
#define FRIEND_AREA_ECHO_CAVE               33
#define FRIEND_AREA_CRYPTIC_CAVE            34
#define FRIEND_AREA_DRAGON_CAVE             35
#define FRIEND_AREA_BOULDER_CAVE            36
#define FRIEND_AREA_JUNGLE                  37
#define FRIEND_AREA_DECREPIT_LAB            38
#define FRIEND_AREA_MT_DISCIPLINE           39
#define FRIEND_AREA_THUNDER_MEADOW          40
#define FRIEND_AREA_POWER_PLANT             41
#define FRIEND_AREA_CRATER                  42
#define FRIEND_AREA_FURNACE_DESERT          43
#define FRIEND_AREA_AGED_CHAMBER_AN         44
#define FRIEND_AREA_AGED_CHAMBER_O_EXCLAIM  45
#define FRIEND_AREA_ANCIENT_RELIC           46
#define FRIEND_AREA_DARKNESS_RIDGE          47
#define FRIEND_AREA_FRIGID_CAVERN           48
#define FRIEND_AREA_ICE_FLOE_BEACH          49
#define FRIEND_AREA_VOLCANIC_PIT            50
#define FRIEND_AREA_STRATOS_LOOKOUT         51
#define FRIEND_AREA_RAVAGED_FIELD           52
#define FRIEND_AREA_MAGNETIC_QUARRY         53
#define FRIEND_AREA_LEGENDARY_ISLAND        54
#define FRIEND_AREA_SOUTHERN_ISLAND         55
#define FRIEND_AREA_ENCLOSED_ISLAND         56
#define FRIEND_AREA_FINAL_ISLAND            57

#define FRIEND_AREA_COUNT                   58

#endif
