#ifndef GUARD_CONSTANTS_GLOBAL_H
#define GUARD_CONSTANTS_GLOBAL_H

#define POKEMON_NAME_LENGTH 10
#define TEAM_NAME_LENGTH 10
#define MAX_TEAM_MEMBERS 4
#define MAX_TEAM_BODY_SIZE 6

#define MAX_MON_MOVES 4

#define MALE 0
#define FEMALE 1

#endif // GUARD_CONSTANTS_GLOBAL_H
