#ifndef GUARD_CONSTANTS_IQ_SKILL_H
#define GUARD_CONSTANTS_IQ_SKILL_H

enum IQSkillID
{
    IQ_NONE = 0x0,
    IQ_TYPE_ADVANTAGE_MASTER = 0x1,
    IQ_ITEM_CATCHER = 0x2,
    IQ_COURSE_CHECKER = 0x3,
    IQ_SURE_HIT_ATTACKER = 0x4,
    IQ_QUICK_DODGER = 0x5,
    IQ_PP_CHECKER = 0x6,
    IQ_NONTRAITOR = 0x7,
    IQ_STATUS_CHECKER = 0x8,
    IQ_EXP_GO_GETTER = 0x9,
    IQ_EFFICIENCY_EXPERT = 0xA,
    IQ_WEAK_TYPE_PICKER = 0xB,
    IQ_ALL_TERRAIN_HIKER = 0xC,
    IQ_SUPER_MOBILE = 0xD,
    IQ_TRAP_AVOIDER = 0xE,
    IQ_HOUSE_AVOIDER = 0xF,
    IQ_ENERGY_SAVER = 0x10,
    IQ_NONSLEEPER = 0x11,
    IQ_SELF_CURER = 0x12,
    IQ_TRAP_SEER = 0x13,
    IQ_LAVA_EVADER = 0x14,
    IQ_DEDICATED_TRAVELER = 0x15,
    IQ_ITEM_MASTER = 0x16,
    IQ_EXCLUSIVE_MOVE_USER = 0x17,
    NUM_IQ_SKILLS = 0x18
};

#endif
