#ifndef GUARD_CONSTANTS_IQ_SKILL_H
#define GUARD_CONSTANTS_IQ_SKILL_H

enum IQSkill
{
    IQ_SKILL_TYPE_ADVANTAGE_MASTER = 0x1,
    IQ_SKILL_ITEM_CATCHER = 0x2,
    IQ_SKILL_COURSE_CHECKER = 0x3,
    IQ_SKILL_SURE_HIT_ATTACKER = 0x4,
    IQ_SKILL_QUICK_DODGER = 0x5,
    IQ_SKILL_PP_CHECKER = 0x6,
    IQ_SKILL_NONTRAITOR = 0x7,
    IQ_SKILL_STATUS_CHECKER = 0x8,
    IQ_SKILL_EXP_GO_GETTER = 0x9,
    IQ_SKILL_EFFICIENCY_EXPERT = 0xA,
    IQ_SKILL_WEAK_TYPE_PICKER = 0xB,
    IQ_SKILL_ALL_TERRAIN_HIKER = 0xC,
    IQ_SKILL_SUPER_MOBILE = 0xD,
    IQ_SKILL_TRAP_AVOIDER = 0xE,
    IQ_SKILL_HOUSE_AVOIDER = 0xF,
    IQ_SKILL_ENERGY_SAVER = 0x10,
    IQ_SKILL_NONSLEEPER = 0x11,
    IQ_SKILL_SELF_CURER = 0x12,
    IQ_SKILL_TRAP_SEER = 0x13,
    IQ_SKILL_LAVA_EVADER = 0x14,
    IQ_SKILL_DEDICATED_TRAVELER = 0x15,
    IQ_SKILL_ITEM_MASTER = 0x16,
    IQ_SKILL_EXCLUSIVE_MOVE_USER = 0x17,
    NUM_IQ_SKILLS = 0x18
};

#endif
