#ifndef GUARD_CONSTANTS_ITEM_H
#define GUARD_CONSTANTS_ITEM_H

#define ITEM_TYPE_THROWABLE 0
#define ITEM_TYPE_ROCK 1
#define ITEM_TYPE_BERRY_SEED 2
#define ITEM_TYPE_APPLE_GUMMI 3
#define ITEM_TYPE_HOLD_ITEM 4
#define ITEM_TYPE_TM 5
#define ITEM_TYPE_MONEY 6
#define ITEM_TYPE_MISC 8
#define ITEM_TYPE_ORB 9
#define ITEM_TYPE_LINK_BOX 10
#define ITEM_TYPE_USED_TM 11

#define ITEM_CATEGORY_NOTHING 0
#define ITEM_CATEGORY_THROWABLE 1
#define ITEM_CATEGORY_ROCKS 2
#define ITEM_CATEGORY_RIBBONS 3
#define ITEM_CATEGORY_FOOD 4
#define ITEM_CATEGORY_HEALING 5
#define ITEM_CATEGORY_CHESTNUT 6
#define ITEM_CATEGORY_MONEY_WISH_STONE 7
#define ITEM_CATEGORY_MISC 8
#define ITEM_CATEGORY_TM 9
#define ITEM_CATEGORY_LINK_BOX 10
#define ITEM_CATEGORY_SPECS 11
#define ITEM_CATEGORY_SCARFS 12
#define ITEM_CATEGORY_ORBS 13

#endif
