#ifndef GUARD_CONSTANTS_MAILBOX_H
#define GUARD_CONSTANTS_MAILBOX_H

#define MAX_ACCEPTED_JOBS 8
#define NUM_MAILBOX_SLOTS 4

enum JOB_LIST_MAIL_TYPES
{
    MAIL_TYPE_NONE = 0,
    MAIL_TYPE_UNK1,
    MAIL_TYPE_UNK2,
    MAIL_TYPE_UNK3,
    MAIL_TYPE_UNK4,
    MAIL_TYPE_SUSPENDED_JOB = 5,
    MAIL_TYPE_TAKEN_JOB,
    MAIL_TYPE_UNK7,
    MAIL_TYPE_UNK8,
    MAIL_TYPE_UNK9,
};

#endif // GUARD_CONSTANTS_MAILBOX_H