#ifndef GUARD_CONSTANTS_MOVE_RANGE_H
#define GUARD_CONSTANTS_MOVE_RANGE_H

#define MOVE_RANGE_NONE 0
#define MOVE_RANGE_THREE_TILES_DIAGONALLY 1
#define MOVE_RANGE_ONE_TILE_FOE 2
#define MOVE_RANGE_CUTS_CORNERS_FOE 3
#define MOVE_RANGE_FLOOR_MEMBERS 4
#define MOVE_RANGE_FLOOR_MEMBERS_2 5
#define MOVE_RANGE_FLOOR_POKEMON 6
#define MOVE_RANGE_FLOOR_FOES 7
#define MOVE_RANGE_FLOOR_MEMBERS_3 8
#define MOVE_RANGE_SIDE_FOE 9
#define MOVE_RANGE_SPECIAL 10
#define MOVE_RANGE_FRONT_FOE 11
#define MOVE_RANGE_SIDE 12
#define MOVE_RANGE_TWO_TILES_FOE 13
#define MOVE_RANGE_STRAIGHT_LINE 14
#define MOVE_RANGE_ROOM_FOES 15
#define MOVE_RANGE_ROOM_ALLIES 16
#define MOVE_RANGE_ROOM 17
#define MOVE_RANGE_ROOM_EXCEPT_USER 18
#define MOVE_RANGE_USER 19
#define MOVE_RANGE_USER_2 20
#define MOVE_RANGE_USER_3 21
#define MOVE_RANGE_ROOM_ONLY 22
#define MOVE_RANGE_ITEMS 23
#define MOVE_RANGE_FLOOR 24
#define MOVE_RANGE_WALL 25
#define MOVE_RANGE_ONE_TILE 26
#define MOVE_RANGE_TWO_TILES 27
#define MOVE_RANGE_CUTS_CORNERS 28
#define MOVE_RANGE_FLOOR_2 29
#define MOVE_RANGE_FRONT 30

#endif
