#ifndef GUARD_CONSTANTS_RESCUE_DUNGEON_ID_H
#define GUARD_CONSTANTS_RESCUE_DUNGEON_ID_H

enum RescueDungeonId
{
    RESCUE_DUNGEON_INVALID = -1,

    RESCUE_DUNGEON_TINY_WOODS,
    RESCUE_DUNGEON_THUNDERWAVE_CAVE,
    RESCUE_DUNGEON_MT_STEEL,
    RESCUE_DUNGEON_SINISTER_WOODS,
    RESCUE_DUNGEON_SILENT_CHASM,
    RESCUE_DUNGEON_MT_THUNDER,
    RESCUE_DUNGEON_GREAT_CANYON,
    RESCUE_DUNGEON_LAPIS_CAVE,
    RESCUE_DUNGEON_MT_BLAZE,
    RESCUE_DUNGEON_FROSTY_FOREST,
    RESCUE_DUNGEON_MT_FREEZE,
    RESCUE_DUNGEON_MAGMA_CAVERN,
    RESCUE_DUNGEON_SKY_TOWER,
    RESCUE_DUNGEON_DUMMY,
    RESCUE_DUNGEON_UPROAR_FOREST,
    RESCUE_DUNGEON_HOWLING_FOREST,
    RESCUE_DUNGEON_STORMY_SEA,
    RESCUE_DUNGEON_SILVER_TRENCH,
    RESCUE_DUNGEON_METEOR_CAVE,
    RESCUE_DUNGEON_GREAT_CANYON_2,
    RESCUE_DUNGEON_FIERY_FIELD,
    RESCUE_DUNGEON_LIGHTNING_FIELD,
    RESCUE_DUNGEON_NORTHWIND_FIELD,
    RESCUE_DUNGEON_MT_FARAWAY,
    RESCUE_DUNGEON_WESTERN_CAVE,
    RESCUE_DUNGEON_NORTHERN_RANGE,
    RESCUE_DUNGEON_PITFALL_VALLEY,
    RESCUE_DUNGEON_BURIED_RELIC,
    RESCUE_DUNGEON_WISH_CAVE,
    RESCUE_DUNGEON_MT_FREEZE_2,
    RESCUE_DUNGEON_MURKY_CAVE,

    // Non-story rescues:

    RESCUE_DUNGEON_DESERT_REGION,
    RESCUE_DUNGEON_SOUTHERN_CAVERN,
    RESCUE_DUNGEON_WYVERN_HILL,
    RESCUE_DUNGEON_SOLAR_CAVE,
    RESCUE_DUNGEON_DARKNIGHT_RELIC,
    RESCUE_DUNGEON_GRAND_SEA,
    RESCUE_DUNGEON_WATERFALL_POND,
    RESCUE_DUNGEON_UNOWN_RELIC,
    RESCUE_DUNGEON_JOYOUS_TOWER,
    RESCUE_DUNGEON_FAR_OFF_SEA,
    RESCUE_DUNGEON_PURITY_FOREST,
    RESCUE_DUNGEON_ODDITY_CAVE,
    RESCUE_DUNGEON_REMAINS_ISLAND,
    RESCUE_DUNGEON_MARVELOUS_SEA,
    RESCUE_DUNGEON_FANTASY_STRAIT,

    RESCUE_DUNGEON_COUNT,
};

#define MAX_STORY_MISSION RESCUE_DUNGEON_MURKY_CAVE
#define NUM_STORY_MISSIONS (MAX_STORY_MISSION + 1)

#endif // GUARD_CONSTANTS_RESCUE_DUNGEON_ID_H
