#ifndef GUARD_CONSTANTS_RESIDUAL_DAMAGE_H
#define GUARD_CONSTANTS_RESIDUAL_DAMAGE_H

enum ResidualDamageType
{
    RESIDUAL_DAMAGE_REGULAR,
    RESIDUAL_DAMAGE_BURN,
    RESIDUAL_DAMAGE_CONSTRICT,
    RESIDUAL_DAMAGE_POISON,
    RESIDUAL_DAMAGE_UNUSED_4,
    RESIDUAL_DAMAGE_WRAP,
    RESIDUAL_DAMAGE_COUNTERATTACK,
    RESIDUAL_DAMAGE_CURSE,
    RESIDUAL_DAMAGE_NIGHTMARE,
    RESIDUAL_DAMAGE_LEECH_SEED,
    RESIDUAL_DAMAGE_SPIKES,
    RESIDUAL_DAMAGE_PERISH_SONG,
    RESIDUAL_DAMAGE_DESTINY_BOND,
    RESIDUAL_DAMAGE_LIQUID_OOZE,
    RESIDUAL_DAMAGE_HUNGER,
    RESIDUAL_DAMAGE_CHESTNUT_TRAP,
    RESIDUAL_DAMAGE_UNUSED_16,
    RESIDUAL_DAMAGE_PITFALL,
    RESIDUAL_DAMAGE_BAD_WEATHER,
    RESIDUAL_DAMAGE_MOVE_FAIL,
    RESIDUAL_DAMAGE_RECOIL,

    NUM_RESIDUAL_DAMAGE_TYPES
};

#endif
