#ifndef GUARD_CONSTANTS_STATUS_H
#define GUARD_CONSTANTS_STATUS_H

enum SleepStatus
{
    SLEEP_STATUS_SLEEP = 1,
    SLEEP_STATUS_SLEEPLESS = 2,
    SLEEP_STATUS_NIGHTMARE = 3,
    SLEEP_STATUS_YAWNING = 4,
    SLEEP_STATUS_NAPPING = 5
};

enum NonVolatileStatus
{
    NON_VOLATILE_STATUS_BURNED = 1,
    NON_VOLATILE_STATUS_POISONED = 2,
    NON_VOLATILE_STATUS_BADLY_POISONED = 3,
    NON_VOLATILE_STATUS_PARALYZED = 4
};

enum ImmobilizeStatus
{
    IMMOBILIZE_STATUS_FROZEN = 1,
    IMMOBILIZE_STATUS_IMMOBILIZED = 2,
    IMMOBILIZE_STATUS_WRAPPED_AROUND_FOE = 3,
    IMMOBILIZE_STATUS_WRAPPED_BY_FOE = 4,
    IMMOBILIZE_STATUS_INGRAIN = 5,
    IMMOBILIZE_STATUS_PETRIFIED = 6,
    IMMOBILIZE_STATUS_SQUEEZED = 7
};

enum ChargingStatus
{
    CHARGING_STATUS_BIDE = 0x1,
    CHARGING_STATUS_SOLARBEAM = 0x2,
    CHARGING_STATUS_SKY_ATTACK = 0x3,
    CHARGING_STATUS_RAZOR_WIND = 0x4,
    CHARGING_STATUS_FOCUS_PUNCH = 0x5,
    CHARGING_STATUS_SKULL_BASH = 0x6,
    CHARGING_STATUS_FLY = 0x7,
    CHARGING_STATUS_BOUNCE = 0x8,
    CHARGING_STATUS_DIVE = 0x9,
    CHARGING_STATUS_DIG = 0xA,
    CHARGING_STATUS_CHARGE = 0xB,
    CHARGING_STATUS_RAGE = 0xC
};

enum ProtectionStatus
{
    PROTECTION_STATUS_REFLECT = 0x1,
    PROTECTION_STATUS_SAFEGUARD = 0x2,
    PROTECTION_STATUS_LIGHT_SCREEN = 0x3,
    PROTECTION_STATUS_COUNTER = 0x4,
    PROTECTION_STATUS_MAGIC_COAT = 0x5,
    PROTECTION_STATUS_WISH = 0x6,
    PROTECTION_STATUS_PROTECT = 0x7,
    PROTECTION_STATUS_MIRROR_COAT = 0x8,
    PROTECTION_STATUS_ENDURE = 0x9,
    PROTECTION_STATUS_MINI_COUNTER = 0xA,
    PROTECTION_STATUS_MIRROR_MOVE = 0xB,
    PROTECTION_STATUS_CONVERSION_2 = 0xC,
    PROTECTION_STATUS_VITAL_THROW = 0xD,
    PROTECTION_STATUS_MIST = 0xE
};

enum WaitingStatus
{
    WAITING_STATUS_CURSED = 1,
    WAITING_STATUS_DECOY = 2,
    WAITING_STATUS_SNATCH = 3
};

enum LinkedStatus
{
    LINKED_STATUS_LEECH_SEED = 1,
    LINKED_STATUS_DESTINY_BOND = 2
};

enum MoveStatus
{
    MOVE_STATUS_SURE_SHOT = 1,
    MOVE_STATUS_WHIFFER = 2,
    MOVE_STATUS_SET_DAMAGE = 3,
    MOVE_STATUS_FOCUS_ENERGY = 4
};

enum ItemStatus
{
    ITEM_STATUS_LONG_TOSS = 1,
    ITEM_STATUS_PIERCE = 2
};

enum TransformStatus
{
    TRANSFORM_STATUS_INVISIBLE = 1,
    TRANSFORM_STATUS_TRANSFORMED = 2,
    TRANSFORM_STATUS_MOBILE = 3
};

enum EyesightStatus
{
    EYESIGHT_STATUS_BLINKER = 1,
    EYESIGHT_STATUS_CROSS_EYED = 2,
    EYESIGHT_STATUS_EYEDROPS = 3
};

enum VolatileStatus
{
    VOLATILE_STATUS_CRINGING = 1,
    VOLATILE_STATUS_CONFUSED = 2,
    VOLATILE_STATUS_PAUSED = 3,
    VOLATILE_STATUS_COWERING = 4,
    VOLATILE_STATUS_TAUNTED = 5,
    VOLATILE_STATUS_ENCORE = 6,
    VOLATILE_STATUS_INFATUATED = 7
};

enum TargetingDecoy
{
    TARGETING_DECOY_TEAM = 1,
    TARGETING_DECOY_WILD = 2
}

#endif
