#ifndef GUARD_CONSTANTS_STATUS_H
#define GUARD_CONSTANTS_STATUS_H

#define SLEEP_STATUS_NONE 0
#define SLEEP_STATUS_SLEEP 1
#define SLEEP_STATUS_SLEEPLESS 2
#define SLEEP_STATUS_NIGHTMARE 3
#define SLEEP_STATUS_YAWNING 4
#define SLEEP_STATUS_NAPPING 5

#define NON_VOLATILE_STATUS_BURNED 1
#define NON_VOLATILE_STATUS_POISONED 2
#define NON_VOLATILE_STATUS_BADLY_POISONED 3
#define NON_VOLATILE_STATUS_PARALYZED 4

#define IMMOBILIZE_STATUS_FROZEN 1
#define IMMOBILIZE_STATUS_IMMOBILIZED 2
#define IMMOBILIZE_STATUS_WRAPPED_AROUND_FOE 3
#define IMMOBILIZE_STATUS_WRAPPED_BY_FOE 4
#define IMMOBILIZE_STATUS_INGRAIN 5
#define IMMOBILIZE_STATUS_PETRIFIED 6
#define IMMOBILIZE_STATUS_SQUEEZED 7

#define CHARGING_STATUS_NONE 0x0
#define CHARGING_STATUS_BIDE 0x1
#define CHARGING_STATUS_SOLARBEAM 0x2
#define CHARGING_STATUS_SKY_ATTACK 0x3
#define CHARGING_STATUS_RAZOR_WIND 0x4
#define CHARGING_STATUS_FOCUS_PUNCH 0x5
#define CHARGING_STATUS_SKULL_BASH 0x6
#define CHARGING_STATUS_FLY 0x7
#define CHARGING_STATUS_BOUNCE 0x8
#define CHARGING_STATUS_DIVE 0x9
#define CHARGING_STATUS_DIG 0xA
#define CHARGING_STATUS_CHARGE 0xB
#define CHARGING_STATUS_RAGE 0xC

#define PROTECTION_STATUS_REFLECT 0x1
#define PROTECTION_STATUS_SAFEGUARD 0x2
#define PROTECTION_STATUS_LIGHT_SCREEN 0x3
#define PROTECTION_STATUS_COUNTER 0x4
#define PROTECTION_STATUS_MAGIC_COAT 0x5
#define PROTECTION_STATUS_WISH 0x6
#define PROTECTION_STATUS_PROTECT 0x7
#define PROTECTION_STATUS_MIRROR_COAT 0x8
#define PROTECTION_STATUS_ENDURE 0x9
#define PROTECTION_STATUS_MINI_COUNTER 0xA
#define PROTECTION_STATUS_MIRROR_MOVE 0xB
#define PROTECTION_STATUS_CONVERSION_2 0xC
#define PROTECTION_STATUS_VITAL_THROW 0xD
#define PROTECTION_STATUS_MIST 0xE

#define WAITING_STATUS_CURSED 1
#define WAITING_STATUS_DECOY 2
#define WAITING_STATUS_SNATCH 3

#define LINKED_STATUS_LEECH_SEED 1
#define LINKED_STATUS_DESTINY_BOND 2

#define MOVE_STATUS_SURE_SHOT 1
#define MOVE_STATUS_WHIFFER 2
#define MOVE_STATUS_SET_DAMAGE 3
#define MOVE_STATUS_FOCUS_ENERGY 4

#define ITEM_STATUS_LONG_TOSS 1
#define ITEM_STATUS_PIERCE 2

#define TRANSFORM_STATUS_INVISIBLE 1
#define TRANSFORM_STATUS_TRANSFORMED 2
#define TRANSFORM_STATUS_MOBILE 3

#define EYESIGHT_STATUS_BLINKER 1
#define EYESIGHT_STATUS_CROSS_EYED 2
#define EYESIGHT_STATUS_EYEDROPS 3

#define VOLATILE_STATUS_CRINGING 1
#define VOLATILE_STATUS_CONFUSED 2
#define VOLATILE_STATUS_PAUSED 3
#define VOLATILE_STATUS_COWERING 4
#define VOLATILE_STATUS_TAUNTED 5
#define VOLATILE_STATUS_ENCORE 6
#define VOLATILE_STATUS_INFATUATED 7

#define TARGETING_DECOY_NONE 0
#define TARGETING_DECOY_TEAM 1
#define TARGETING_DECOY_WILD 2

#endif
