#ifndef GUARD_CONSTANTS_TACTIC_H
#define GUARD_CONSTANTS_TACTIC_H

enum TacticID
{
    TACTIC_LETS_GO_TOGETHER,
    TACTIC_GO_THE_OTHER_WAY,
    TACTIC_GO_AFTER_FOES,
    TACTIC_AVOID_THE_FIRST_HIT,
    TACTIC_ALL_FOR_ONE, // Unused
    TACTIC_GROUP_SAFETY, // Unused
    TACTIC_AVOID_TROUBLE,
    TACTIC_BE_PATIENT,
    TACTIC_KEEP_YOUR_DISTANCE,
    TACTIC_WAIT_THERE,
    TACTIC_GET_AWAY,
    TACTIC_UNUSED,
    NUM_TACTICS
};

#endif // GUARD_CONSTANTS_TACTIC_H