#ifndef GUARD_CONSTANTS_TACTIC_H
#define GUARD_CONSTANTS_TACTIC_H

enum TacticID
{
    TACTIC_LETS_GO_TOGETHER = 0x0,
    TACTIC_GO_THE_OTHER_WAY = 0x1,
    TACTIC_GO_AFTER_FOES = 0x2,
    TACTIC_AVOID_THE_FIRST_HIT = 0x3,
    TACTIC_ALL_FOR_ONE = 0x4, // Unused
    TACTIC_GROUP_SAFETY = 0x5, // Unused
    TACTIC_AVOID_TROUBLE = 0x6,
    TACTIC_BE_PATIENT = 0x7,
    TACTIC_KEEP_YOUR_DISTANCE = 0x8,
    TACTIC_WAIT_THERE = 0x9,
    TACTIC_GET_AWAY = 0xA,
    TACTIC_UNUSED = 0xB,
    NUM_TACTICS = 0xC
};

#endif
