#ifndef GUARD_CONSTANTS_TARGETING_H
#define GUARD_CONSTANTS_TARGETING_H

#define DECOY_AI_NONE 0
#define DECOY_AI_TEAM 1
#define DECOY_AI_WILD 2

#define TREATMENT_TREAT_AS_ALLY 0
#define TREATMENT_TREAT_AS_ENEMY 1
#define TREATMENT_IGNORE 2

#endif
