#ifndef GUARD_CONSTANTS_TARGETING_H
#define GUARD_CONSTANTS_TARGETING_H

#define TARGETING_DECOY_NONE 0
#define TARGETING_DECOY_TEAM 1
#define TARGETING_DECOY_WILD 2

#define TARGET_CAPABILITY_CANNOT_ATTACK 0
#define TARGET_CAPABILITY_CAN_TARGET 1
#define TARGET_CAPABILITY_CAN_ATTACK_NOT_TARGET 2

#endif
