#ifndef GUARD_CONSTANTS_TRAP_H
#define GUARD_CONSTANTS_TRAP_H

enum TrapID
{
    TRAP_TRIP_TRAP,
    TRAP_MUD_TRAP,
    TRAP_STICKY_TRAP,
    TRAP_GRIMY_TRAP,
    TRAP_SUMMON_TRAP,
    TRAP_PITFALL_TRAP,
    TRAP_WARP_TRAP,
    TRAP_WHIRLWIND_TRAP,
    TRAP_SPIN_TRAP,
    TRAP_SLUMBER_TRAP,
    TRAP_SLOW_TRAP,
    TRAP_SEAL_TRAP,
    TRAP_POISON_TRAP,
    TRAP_SELFDESTRUCT_TRAP,
    TRAP_EXPLOSION_TRAP,
    TRAP_PP_ZERO_TRAP,
    TRAP_CHESTNUT_TRAP,
    TRAP_WONDER_TILE,
    TRAP_POKEMON_TRAP,
    TRAP_SPIKE_TRAP
};

#endif // GUARD_CONSTANTS_TRAP_H