#ifndef GUARD_CONSTANTS_TRAP_H
#define GUARD_CONSTANTS_TRAP_H

enum TrapID
{
    TRAP_TRIP_TRAP = 0x0,
    TRAP_MUD_TRAP = 0x1,
    TRAP_STICKY_TRAP = 0x2,
    TRAP_GRIMY_TRAP = 0x3,
    TRAP_SUMMON_TRAP = 0x4,
    TRAP_PITFALL_TRAP = 0x5,
    TRAP_WARP_TRAP = 0x6,
    TRAP_WHIRLWIND_TRAP = 0x7,
    TRAP_SPIN_TRAP = 0x8,
    TRAP_SLUMBER_TRAP = 0x9,
    TRAP_SLOW_TRAP = 0xA,
    TRAP_SEAL_TRAP = 0xB,
    TRAP_POISON_TRAP = 0xC,
    TRAP_SELFDESTRUCT_TRAP = 0xD,
    TRAP_EXPLOSION_TRAP = 0xE,
    TRAP_PP_ZERO_TRAP = 0xF,
    TRAP_CHESTNUT_TRAP = 0x10,
    TRAP_WONDER_TILE = 0x11,
    TRAP_POKEMON_TRAP = 0x12,
    TRAP_SPIKE_TRAP = 0x13
};

#endif
