#ifndef GUARD_CONSTANTS_TUTORIAL_ID_H
#define GUARD_CONSTANTS_TUTORIAL_ID_H

enum TutorialFlagID
{
    TUTORIAL_FLAG_STAIRS_AND_SURVIVE,
    TUTORIAL_FLAG_OPEN_MENU,
    TUTORIAL_FLAG_REGAIN_HP,
    TUTORIAL_FLAG_MANAGE_BELLY1,
    TUTORIAL_FLAG_ORAN_BERRY,
    TUTORIAL_FLAG_CHERI_BERRY,
    TUTORIAL_FLAG_BLAST_SEED,
    TUTORIAL_FLAG_GRAVELEROCK,
    TUTORIAL_FLAG_UNK8,
    TUTORIAL_FLAG_PECHA_BERRY,
    TUTORIAL_FLAG_SLEEP_SEED,
    TUTORIAL_FLAG_MONEY,
    TUTORIAL_FLAG_MOVES,
    TUTORIAL_FLAG_TEAM_MANAGEMENT,
    TUTORIAL_FLAG_MOVEMENT,
    TUTORIAL_FLAG_MANAGE_BELLY2,

    NUM_TUTORIAL_FLAGS = 31
};

#define TUTORIAL_FLAGS_U32STORAGE 1

#endif // GUARD_CONSTANTS_TUTORIAL_ID_H
