#ifndef GUARD_CONSTANTS_MOVEMENT_TYPE_H
#define GUARD_CONSTANTS_MOVEMENT_TYPE_H

#define MOVEMENT_TYPE_CHASM 2
#define MOVEMENT_TYPE_WALL 3
#define MOVEMENT_TYPE_LAVA 4
#define MOVEMENT_TYPE_WATER 5

#endif
