#ifndef GUARD_CONSTANTS_WALKABLE_TILE_H
#define GUARD_CONSTANTS_WALKABLE_TILE_H

#define WALKABLE_TILE_CHASM 2
#define WALKABLE_TILE_WALL 3
#define WALKABLE_TILE_LAVA 4
#define WALKABLE_TILE_WATER 5

#endif
