#ifndef GUARD_CONSTANTS_WEATHER_H
#define GUARD_CONSTANTS_WEATHER_H

enum WeatherID
{
    WEATHER_CLEAR,
    WEATHER_SUNNY,
    WEATHER_SANDSTORM,
    WEATHER_CLOUDY,
    WEATHER_RAIN,
    WEATHER_HAIL,
    WEATHER_FOG,
    WEATHER_SNOW,
    WEATHER_COUNT
};
#define WEATHER_RANDOM WEATHER_COUNT

#endif // GUARD_CONSTANTS_WEATHER_H
