gUnknown_80DD388:: @ 80DD388
	.string "You have chosen to say farewell\n"
	.string "to this Pokémon.#PThe Pokémon will leave its Friend Area.\n"
	.string "It will no longer be available for\n"
	.string "adventures. Is that OK?"
	.byte 0
	.align 2, 0

gUnknown_80DD420:: @ 80DD420
	.string "If you say farewell to this\n"
	.string "Pokémon~2c it will be gone forever.#PYou will never be able to get another one\n"
	.string "like it to join your team.\n"
	.string "Will you release it anyway?"
	.byte 0
	.align 2, 0

gUnknown_80DD4C4:: @ 80DD4C4
	.string "#+"
	.byte 0x24
	.string "m1 joined the\n"
	.string "#+rescue team for adventures!"
	.byte 0
	.align 2, 0

gUnknown_80DD4F4:: @ 80DD4F4
	.string "#+"
	.byte 0x24
	.string "m1 left the team to remain\n"
	.string "#+on standby in the Friend Area."
	.byte 0
	.align 2, 0

gUnknown_80DD534:: @ 80DD534
	.string "#+"
	.byte 0x24
	.string "m1 became the leader\n"
	.string "#+of the rescue team."
	.byte 0
	.align 2, 0

gUnknown_80DD564:: @ 80DD564
	.string "#+"
	.byte 0x24
	.string "m1 left\n"
	.string "#+the Friend Area.\n"
	.string "#+Bye-bye~2c "
	.byte 0x24
	.string "m1!"
	.byte 0
gUnknown_80DD594:: @ 80DD594
	.string "#+The #C4"
	.byte 0x24
	.string "i1#R was\n"
	.string "#+handed over. "
	.byte 0
	.align 2, 0

gUnknown_80DD5B8:: @ 80DD5B8
	.string "#+The #C4"
	.byte 0x24
	.string "i1#R was\n"
	.string "#+handed over.#P#+The #C4"
	.byte 0x24
	.string "i0#R was\n"
	.string "#+returned to the Toolbox."
	.byte 0
	.align 2, 0

gUnknown_80DD60C:: @ 80DD60C
	.string "#+The #C4"
	.byte 0x24
	.string "i0#R was\n"
	.string "#+returned to the Toolbox."
	.byte 0
	.align 2, 0

gUnknown_80DD63C:: @ 80DD63C
	.string "#+The #C4"
	.byte 0x24
	.string "i0#R was\n"
	.string "#+sent to storage."
	.byte 0
	.align 2, 0

gUnknown_80DD664:: @ 80DD664
	.string "Stand By"
	.byte 0
	.align 2, 0
gUnknown_80DD670:: @ 80DD670
	.string "Make Leader"
	.byte 0

gUnknown_80DD67C:: @ 80DD67C
	.string "Join Team"
	.byte 0
	.align 2, 0

gUnknown_80DD688:: @ 80DD688
	.string "Give Gummi"
	.byte 0
	.align 2, 0

gUnknown_80DD694:: @ 80DD694
	.string "Give"
	.byte 0
	.align 2, 0

gUnknown_80DD69C:: @ 80DD69C
	.string "Take"
	.byte 0
	.align 2, 0

gUnknown_80DD6A4:: @ 80DD6A4
	.string "Say Farewell"
	.byte 0
	.align 2, 0

gUnknown_80DD6B4:: @ 80DD6B4
	.string "Summary"
	.byte 0
	.align 2, 0

gUnknown_80DD6BC:: @ 80DD6BC
	.string "Moves"
	.byte 0
	.align 2, 0

gUnknown_80DD6C4:: @ 80DD6C4
	.string "Check IQ"
	.byte 0
	.align 2, 0

gUnknown_80DD6D0:: @ 80DD6D0
	.string "Item: #C4"
	.byte 0x24
	.string "i0#R "
	.byte 0
	.align 2, 0

gUnknown_80DD6E0:: @ 80DD6E0
	.string "%s"
	.byte 0
	.align 2, 0

	.string "pksdir0"
	.byte 0
	.align 2, 0
