gUnknown_80DEF04:: @ 80DEF04
	.string " ...Oh?\n"
	.string "Something~27s gone wrong."
	.byte 0
	.align 2, 0

gUnknown_80DEF28:: @ 80DEF28
	.string " ...Oh? The number of linked\n"
	.string "GBA systems is incorrect.\n"
	.string "Please try again from the start."
	.byte 0
	.align 2, 0

gUnknown_80DEF80:: @ 80DEF80
	.string " ...Oh? It looks like your\n"
	.string "friend chose a different mode.\n"
	.string "Please try again from the start."
	.byte 0
	.align 2, 0

gUnknown_80DEFDC:: @ 80DEFDC
	.string " ...Oh? It looks like your\n"
	.string "storage space is full. Please clear some\n"
	.string "space and try again from the start."
	.byte 0
	.align 2, 0

gUnknown_80DF044:: @ 80DF044
	.string " ...Oh?\n"
	.string "I think you~27ve received this mail before.\n"
	.string "You can~27t get the same mail twice."
	.byte 0
	.align 2, 0

gUnknown_80DF0A0:: @ 80DF0A0
	.string " ...Oh?\n"
	.string "I don~27t think you~27re eligible to receive\n"
	.string "this mail."
	.byte 0
	.align 2, 0

gUnknown_80DF0E0:: @ 80DF0E0
	.string " ...Oh?\n"
	.string "There is no room to receive new mail.\n"
	.string "Please delete some mail and try again."
	.byte 0
	.align 2, 0

gUnknown_80DF138:: @ 80DF138
	.string " ...Oh? Your friend didn~27t\n"
	.string "follow through on their side.\n"
	.string "Please try again from the start."
	.byte 0
	.align 2, 0

gUnknown_80DF194:: @ 80DF194
	.string " Your #CGThank-You Mail#R\n"
	.string "has been sent."
	.byte 0
	.align 2, 0

gUnknown_80DF1C0:: @ 80DF1C0
	.string " ...Oh?\n"
	.string "This password appears to be wrong.\n"
	.string "Would you like to try again?"
	.byte 0
	.align 2, 0

gUnknown_80DF208:: @ 80DF208
	.string " ...Oh? This password doesn~27t\n"
	.string "appear to be for a #CGThank-You Mail#R."
	.byte 0
	.align 2, 0

gUnknown_80DF250:: @ 80DF250
	.string ": This is the counter for\n"
	.string "#CGThank-You Mail#R.#P: Oh~2c hi~2c #CN%s#R.\n"
	.string "I~27ve been waiting for you. You wanted me\n"
	.string "to process a #CGThank-You Mail#R?#P: Let me get on it right away"
	.string "."
	.byte 0
	.align 2, 0

gUnknown_80DF304:: @ 80DF304
	.string " Is it OK to send this\n"
	.string "#CGThank-You Mail#R?"
	.byte 0
	.align 2, 0

gUnknown_80DF330:: @ 80DF330
	.string " Please choose the\n"
	.string "#CGThank-You Mail#R that you want to\n"
	.string "send to your friend."
	.byte 0
	.align 2, 0

gUnknown_80DF380:: @ 80DF380
	.string " OK. Please enter the\n"
	.string "#CGThank-You Mail password#R."
	.byte 0
	.align 2, 0

gUnknown_80DF3B4:: @ 80DF3B4
	.string " Please give this password\n"
	.string "to the friend that rescued your team.#P I also must save your\n"
	.string "adventure."
	.byte 0
	.align 2, 0

gUnknown_80DF418:: @ 80DF418
	.string " OK~2c here is your\n"
	.string "#CGThank-You Mail password#R."
	.byte 0
	.align 2, 0

gUnknown_80DF44C:: @ 80DF44C
	.string " I need to save your\n"
	.string "adventure."
	.byte 0
	.align 2, 0

gUnknown_80DF46C:: @ 80DF46C
	.string " There we go.\n"
	.string "I~27m all done.#P Doesn~27t it feel great to\n"
	.string "be appreciated for doing something good?\n"
	.string "Please keep up your rescue work!"
	.byte 0
	.align 2, 0

gUnknown_80DF4F4:: @ 80DF4F4
	.string " A #CGThank-You Mail#R has\n"
	.string "arrived from your friend for your rescue\n"
	.string "mission."
	.byte 0
	.align 2, 0

gUnknown_80DF544:: @ 80DF544
	.string "#+Communicating...\n"
	.string "#+Please wait with the power on.\n"
	.string "#+To cancel~2c press {B_BUTTON}."
	.byte 0
	.align 2, 0

gUnknown_80DF594:: @ 80DF594
	.string " There. I~27ve sent your\n"
	.string "#CGThank-You Mail#R.\n"
	.string "I need to save your adventure."
	.byte 0
	.align 2, 0

gUnknown_80DF5E4:: @ 80DF5E4
	.string " Please connect the GBA\n"
	.string "systems with a #CGGame Link cable#R.\n"
	.string "Is your friend also ready?"
	.byte 0
	.align 2, 0

gUnknown_80DF63C:: @ 80DF63C
	.string " There~2c all done.\n"
	.string "#CN%s#R~2c I hope your friend\n"
	.string "appreciates your sense of gratitude."
	.byte 0
	.align 2, 0

gUnknown_80DF694:: @ 80DF694
	.string " The item you~27ve chosen\n"
	.string "here can~27t be exchanged later.\n"
	.string "Are you certain this item is OK?"
	.byte 0
	.align 2, 0

gUnknown_80DF6F0:: @ 80DF6F0
	.string " I~27ve saved your adventure. "
	.byte 0
	.align 2, 0

gUnknown_80DF710:: @ 80DF710
	.string " OK~2c please choose\n"
	.string "the item to be sent."
	.byte 0
	.align 2, 0

gUnknown_80DF73C:: @ 80DF73C
	.string " ...Oh?\n"
	.string "Your storage space is empty.\n"
	.string "What would you like to do?"
	.byte 0
	.align 2, 0

gUnknown_80DF77C:: @ 80DF77C
	.string " Would you like to choose\n"
	.string "a #CGreward item#R from storage and\n"
	.string "send it with your mail?"
	.byte 0
	.align 2, 0

gUnknown_80DF7D4:: @ 80DF7D4
	.string " ...Oh?\n"
	.string "You~27ve already attached a #CGreward item#R\n"
	.string "to this mail.#P I~27m sorry~2c but once an item\n"
	.string "has been attached to mail~2c it can~27t be\n"
	.string "exchanged."
	.byte 0
	.align 2, 0

gUnknown_80DF870:: @ 80DF870
	.string " Would you like to send it\n"
	.string "again with the item you chose before?"
	.byte 0
	.align 2, 0

gUnknown_80DF8B4:: @ 80DF8B4
	.string " ...Oh?\n"
	.string "You don~27t seem to have a #CGThank-You Mail#R."
	.byte 0
	.align 2, 0

gUnknown_80DF8EC:: @ 80DF8EC
	.string " Hello.\n"
	.string "I handle #CGThank-You Mail#R.\n"
	.string "How may I serve you?"
	.byte 0
	.align 2, 0

gUnknown_80DF928:: @ 80DF928
	.string " May I help you with\n"
	.string "anything else?"
	.byte 0
	.align 2, 0

gUnknown_80DF94C:: @ 80DF94C
	.string " Please come see me\n"
	.string "anytime."
	.byte 0
	.align 2, 0

gUnknown_80DF96C:: @ 80DF96C
	.string " How would you like to send\n"
	.string "your #CGThank-You Mail#R?"
	.byte 0
	.align 2, 0

gUnknown_80DF9A4:: @ 80DF9A4
	.string " How would you like to\n"
	.string "receive your friend~27s #CGThank-You Mail#R?"
	.byte 0

	.string "pksdir0"
	.byte 0
	.align 2, 0

gUnknown_80DF9F0:: @ 80DF9F0
	.string "????"
	.byte 0
	.align 2, 0

gUnknown_80DF9F8:: @ 80DF9F8
	.string " Oh~2c hello!\n"
	.string "Your rescue mission went well~2c didn~27t it?\n"
	.string "I wouldn~27t expect any less~2c #CG%s#R!#P Well~2c well!\n"
	.string "Here is your reward from the Pokémon\n"
	.string "Rescue Organization!"
	.byte 0
	.align 2, 0

gUnknown_80DFAA8:: @ 80DFAA8
	.string " I hope you will keep on\n"
	.string "rescuing your friends in\n"
	.string "dire straits.#P And now~2c I must save\n"
	.string "your adventure."
	.byte 0
	.align 2, 0

gUnknown_80DFB14:: @ 80DFB14
	.string " Oh~2c yes~2c that~27s right.\n"
	.string "Please don~27t forget to send an #CGA-OK Mail#R\n"
	.string "to the friend you just rescued.#P Please give me a shout if\n"
	.string "you would like to send #CGA-OK Mail#R."
	.byte 0
	.align 2, 0

	.string "pksdir0"
	.byte 0
