gWonderMailClientThanksForRescuingMe:: @ 80E0184
	.string " Thank you for rescuing me!\0"
	.align 2, 0

gWonderMailClientThanksForRescuingThem:: @ 80E01A0
	.string " Thank you for rescuing\n"
	.string "{COLOR_1 CYAN}$m1{END_COLOR_TEXT_1}!\0"
	.align 2, 0

gWonderMailClientEscorted:: @ 80E01C4
	.string " Thank you for escorting me\n"
	.string "to {COLOR_1 CYAN}$m1{END_COLOR_TEXT_1}! \0"
	.align 2, 0

gWonderMailClientItemDelivered1:: @ 80E01F0
	.string " Thank you for delivering\n"
	.string "the {COLOR_1 GREEN}$i0{END_COLOR_TEXT_1}!\0"
	.align 2, 0

gWonderMailClientItemDelivered2:: @ 80E0218
	.string " Thank you for getting me\n"
	.string "the {COLOR_1 GREEN}$i0{END_COLOR_TEXT_1}!\0"
	.align 2, 0

	.string "pksdir0\0"
	.align 2, 0
