gUnknown_80DDBA8:: @ 80DDBA8
	.string " What you need to do is\n"
	.string "tell your friend--the one you rescued--\n"
	.string "this here password.\0"
	.align 2, 0

gUnknown_80DDBFC:: @ 80DDBFC
	.string " All righty!\n"
	.string "Here~27s your #CGA-OK Mail password#R.\0"
	.align 2, 0

gUnknown_80DDC30:: @ 80DDC30
	.string " Okeydoke! That~27s all done.\n"
	.string "Come around whenever you need.\0"
	.align 2, 0

gUnknown_80DDC70:: @ 80DDC70
	.string " Okeydoke! I sent off your\n"
	.string "#CGA-OK Mail#R.#P"
	.string " Let me save your adventure.\0"
	.align 2, 0

gUnknown_80DDCBC:: @ 80DDCBC
	.string "#+Please choose the Pokémon you want to\n"
	.string "#+send as a helper to your friend.\n"
	.string "#+(Its hold item will not be sent.)\0"
	.align 2, 0

gUnknown_80DDD2C:: @ 80DDD2C
	.string " ...Uh~2c no?\n"
	.string "There appear to be no Pokémon in your\n"
	.string "Friend Areas. What do you want to do?\0"
	.align 2, 0

gUnknown_80DDD88:: @ 80DDD88
	.string " You~27re sure you want to\n"
	.string "send this here Pokémon?\0"
	.align 2, 0

gUnknown_80DDDBC:: @ 80DDDBC
	.string " You~27re sure about this?\0"
	.align 2, 0

gUnknown_80DDDD8:: @ 80DDDD8
	.string " All righty. I need you to\n"
	.string "pick the #CGA-OK Mail#R you want to send.\0"
	.align 2, 0

gUnknown_80DDE20:: @ 80DDE20
	.string " ...Uh~2c no?\n"
	.string "I don~27t see any #CGA-OK Mail#R here.\0"
	.align 2, 0

gUnknown_80DDE58:: @ 80DDE58
	.string " Did you know? If you use\n"
	.string "a #CGGame Link cable#R~2c you can send\n"
	.string "a #CGhelper Pokémon#R to your friend.\0"
	.align 2, 0

gUnknown_80DDEC0:: @ 80DDEC0
	.string " Don~27t you worry. Sending\n"
	.string "a Pokémon doesn~27t mean it will go away.\n"
	.string "So! Want to send one to your friend?\0"
	.align 2, 0

gUnknown_80DDF2C:: @ 80DDF2C
	.string " ...Uh~2c no?\n"
	.string "There~27s no space at all to receive\n"
	.string "any more mail.#P"
	.string " Delete some old mail~2c\n"
	.string "and then come to me to receive\n"
	.string "your mail~2c OK?\0"
	.align 2, 0

gUnknown_80DDFB8:: @ 80DDFB8
	.string " All righty! Connect up\n"
	.string "the #CGGame Link cable#R~2c if you~27d please.\n"
	.string "Your friend ready~2c too?\0"
	.align 2, 0

gUnknown_80DE01C:: @ 80DE01C
	.string "#+Communicating...\n"
	.string "#+Please wait with the power on.\n"
	.string "#+To cancel~2c press {B_BUTTON}.\0"
	.align 2, 0

gUnknown_80DE06C:: @ 80DE06C
	.string " Okeydoke!\n"
	.string "I received your friend~27s #CGSOS Mail#R.#P"
	.string " Let me save your adventure.\0"
	.align 2, 0

gUnknown_80DE0C0:: @ 80DE0C0
	.string " Okeydoke! You~27re good to go.\n"
	.string "Just give me a shout when you~27d like\n"
	.string "to go rescue your friend.\0"
	.align 2, 0

gUnknown_80DE124:: @ 80DE124
	.string " OK~2c I need you to enter\n"
	.string "the #CGSOS Mail password#R that your\n"
	.string "friend gave you.\0"
	.align 2, 0

gUnknown_80DE178:: @ 80DE178
	.string " How do you want to receive\n"
	.string "your friend~27s #CGSOS Mail#R?\0"
	.align 2, 0

gUnknown_80DE1B4:: @ 80DE1B4
	.string " How do you want to send\n"
	.string "your #CGA-OK Mail#R?\0"
	.align 2, 0
