.global gKaoButterfree
gKaoButterfree:
kao_siro sPortraitsButterfree
sButterfreeNormalPal:
.incbin "baserom.gba", 0x1689734, 0x40
sButterfreeNormalGfx:
.string "AT4PX"
.incbin "baserom.gba", 0x1689779, 0x2E7
sPortraitsButterfree:
kao_portrait sButterfreeNormalPal, sButterfreeNormalGfx
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
