.global gKaoCharmander
gKaoCharmander:
kao_siro sPortraitsCharmander
sCharmanderNormalPal:
.incbin "baserom.gba", 0x1682600, 0x40
sCharmanderNormalGfx:
.string "AT4PX"
.incbin "baserom.gba", 0x1682645, 0x247
sCharmanderHappyPal:
.incbin "baserom.gba", 0x168288C, 0x40
sCharmanderHappyGfx:
.incbin "baserom.gba", 0x16828CC, 0x234
sCharmanderPainedPal:
.incbin "baserom.gba", 0x1682B00, 0x40
sCharmanderPainedGfx:
.string "AT4PX"
.incbin "baserom.gba", 0x1682B45, 0x253
sCharmanderAngryPal:
.incbin "baserom.gba", 0x1682D98, 0x40
sCharmanderAngryGfx:
.string "AT4PX"
.incbin "baserom.gba", 0x1682DDD, 0x27B
sCharmanderWorriedPal:
.incbin "baserom.gba", 0x1683058, 0x40
sCharmanderWorriedGfx:
.incbin "baserom.gba", 0x1683098, 0x254
sCharmanderSadPal:
.incbin "baserom.gba", 0x16832EC, 0x40
sCharmanderSadGfx:
.incbin "baserom.gba", 0x168332C, 0x254
sCharmanderCryingPal:
.incbin "baserom.gba", 0x1683580, 0x40
sCharmanderCryingGfx:
.string "AT4PX"
.incbin "baserom.gba", 0x16835C5, 0x263
sCharmanderShoutingPal:
.incbin "baserom.gba", 0x1683828, 0x40
sCharmanderShoutingGfx:
.incbin "baserom.gba", 0x1683868, 0x2A8
sCharmanderTearyEyePal:
.incbin "baserom.gba", 0x1683B10, 0x40
sCharmanderTearyEyeGfx:
.string "AT4PX"
.incbin "baserom.gba", 0x1683B55, 0x25B
sCharmanderDeterminedPal:
.incbin "baserom.gba", 0x1683DB0, 0x40
sCharmanderDeterminedGfx:
.string "AT4PX"
.incbin "baserom.gba", 0x1683DF5, 0x247
sCharmanderJoyousPal:
.incbin "baserom.gba", 0x168403C, 0x40
sCharmanderJoyousGfx:
.incbin "baserom.gba", 0x168407C, 0x2E0
sCharmanderInspiredPal:
.incbin "baserom.gba", 0x168435C, 0x40
sCharmanderInspiredGfx:
.incbin "baserom.gba", 0x168439C, 0x248
sCharmanderSurprisedPal:
.incbin "baserom.gba", 0x16845E4, 0x40
sCharmanderSurprisedGfx:
.incbin "baserom.gba", 0x1684624, 0x2A4
sPortraitsCharmander:
kao_portrait sCharmanderNormalPal, sCharmanderNormalGfx
kao_portrait sCharmanderHappyPal, sCharmanderHappyGfx
kao_portrait sCharmanderPainedPal, sCharmanderPainedGfx
kao_portrait sCharmanderAngryPal, sCharmanderAngryGfx
kao_portrait sCharmanderWorriedPal, sCharmanderWorriedGfx
kao_portrait sCharmanderSadPal, sCharmanderSadGfx
kao_portrait sCharmanderCryingPal, sCharmanderCryingGfx
kao_portrait sCharmanderShoutingPal, sCharmanderShoutingGfx
kao_portrait sCharmanderTearyEyePal, sCharmanderTearyEyeGfx
kao_portrait sCharmanderDeterminedPal, sCharmanderDeterminedGfx
kao_portrait sCharmanderJoyousPal, sCharmanderJoyousGfx
kao_portrait sCharmanderInspiredPal, sCharmanderInspiredGfx
kao_portrait sCharmanderSurprisedPal, sCharmanderSurprisedGfx
