.global gKaoGroudon
gKaoGroudon:
kao_siro sPortraitsGroudon
sGroudonNormalPal:
.incbin "baserom.gba", 0x16BAECC, 0x40
sGroudonNormalGfx:
.incbin "baserom.gba", 0x16BAF0C, 0x2F0
sPortraitsGroudon:
kao_portrait sGroudonNormalPal, sGroudonNormalGfx
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
