.global gKaoLatios
gKaoLatios:
kao_siro sPortraitsLatios
sLatiosNormalPal:
.incbin "baserom.gba", 0x16BA58C, 0x40
sLatiosNormalGfx:
.incbin "baserom.gba", 0x16BA5CC, 0x290
sLatiosHappyPal:
.incbin "baserom.gba", 0x16BA85C, 0x40
sLatiosHappyGfx:
.incbin "baserom.gba", 0x16BA89C, 0x29C
sPortraitsLatios:
kao_portrait sLatiosNormalPal, sLatiosNormalGfx
kao_portrait sLatiosHappyPal, sLatiosHappyGfx
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
