.global gKaoMeowth
gKaoMeowth:
kao_siro sPortraitsMeowth
sMeowthNormalPal:
.incbin "baserom.gba", 0x168D634, 0x40
sMeowthNormalGfx:
.string "AT4PX"
.incbin "baserom.gba", 0x168D679, 0x2CF
sMeowthHappyPal:
.incbin "baserom.gba", 0x168D948, 0x40
sMeowthHappyGfx:
.string "AT4PX"
.incbin "baserom.gba", 0x168D98D, 0x2DF
sMeowthPainedPal:
.incbin "baserom.gba", 0x168DC6C, 0x40
sMeowthPainedGfx:
.incbin "baserom.gba", 0x168DCAC, 0x2E8
sMeowthAngryPal:
.incbin "baserom.gba", 0x168DF94, 0x40
sMeowthAngryGfx:
.string "AT4PX"
.incbin "baserom.gba", 0x168DFD9, 0x2F3
sMeowthWorriedPal:
.incbin "baserom.gba", 0x168E2CC, 0x40
sMeowthWorriedGfx:
.incbin "baserom.gba", 0x168E30C, 0x2BC
sMeowthSadPal:
.incbin "baserom.gba", 0x168E5C8, 0x40
sMeowthSadGfx:
.incbin "baserom.gba", 0x168E608, 0x2D0
sMeowthCryingPal:
.incbin "baserom.gba", 0x168E8D8, 0x40
sMeowthCryingGfx:
.incbin "baserom.gba", 0x168E918, 0x2A8
sMeowthShoutingPal:
.incbin "baserom.gba", 0x168EBC0, 0x40
sMeowthShoutingGfx:
.incbin "baserom.gba", 0x168EC00, 0x2F0
sMeowthTearyEyePal:
.incbin "baserom.gba", 0x168EEF0, 0x40
sMeowthTearyEyeGfx:
.string "AT4PX"
.incbin "baserom.gba", 0x168EF35, 0x2AB
sMeowthDeterminedPal:
.incbin "baserom.gba", 0x168F1E0, 0x40
sMeowthDeterminedGfx:
.string "AT4PX"
.incbin "baserom.gba", 0x168F225, 0x2D3
sMeowthJoyousPal:
.incbin "baserom.gba", 0x168F4F8, 0x40
sMeowthJoyousGfx:
.incbin "baserom.gba", 0x168F538, 0x2CC
sMeowthInspiredPal:
.incbin "baserom.gba", 0x168F804, 0x40
sMeowthInspiredGfx:
.incbin "baserom.gba", 0x168F844, 0x2D4
sMeowthSurprisedPal:
.incbin "baserom.gba", 0x168FB18, 0x40
sMeowthSurprisedGfx:
.incbin "baserom.gba", 0x168FB58, 0x2F8
sPortraitsMeowth:
kao_portrait sMeowthNormalPal, sMeowthNormalGfx
kao_portrait sMeowthHappyPal, sMeowthHappyGfx
kao_portrait sMeowthPainedPal, sMeowthPainedGfx
kao_portrait sMeowthAngryPal, sMeowthAngryGfx
kao_portrait sMeowthWorriedPal, sMeowthWorriedGfx
kao_portrait sMeowthSadPal, sMeowthSadGfx
kao_portrait sMeowthCryingPal, sMeowthCryingGfx
kao_portrait sMeowthShoutingPal, sMeowthShoutingGfx
kao_portrait sMeowthTearyEyePal, sMeowthTearyEyeGfx
kao_portrait sMeowthDeterminedPal, sMeowthDeterminedGfx
kao_portrait sMeowthJoyousPal, sMeowthJoyousGfx
kao_portrait sMeowthInspiredPal, sMeowthInspiredGfx
kao_portrait sMeowthSurprisedPal, sMeowthSurprisedGfx
