.global gKaoPsyduck
gKaoPsyduck:
kao_siro sPortraitsPsyduck
sPsyduckNormalPal:
.incbin "baserom.gba", 0x1690234, 0x40
sPsyduckNormalGfx:
.string "AT4PX"
.incbin "baserom.gba", 0x1690279, 0x277
sPsyduckHappyPal:
.incbin "baserom.gba", 0x16904F0, 0x40
sPsyduckHappyGfx:
.string "AT4PX"
.incbin "baserom.gba", 0x1690535, 0x277
sPsyduckPainedPal:
.incbin "baserom.gba", 0x16907AC, 0x40
sPsyduckPainedGfx:
.incbin "baserom.gba", 0x16907EC, 0x280
sPsyduckAngryPal:
.incbin "baserom.gba", 0x1690A6C, 0x40
sPsyduckAngryGfx:
.incbin "baserom.gba", 0x1690AAC, 0x284
sPsyduckWorriedPal:
.incbin "baserom.gba", 0x1690D30, 0x40
sPsyduckWorriedGfx:
.string "AT4PX"
.incbin "baserom.gba", 0x1690D75, 0x267
sPsyduckSadPal:
.incbin "baserom.gba", 0x1690FDC, 0x40
sPsyduckSadGfx:
.incbin "baserom.gba", 0x169101C, 0x290
sPsyduckCryingPal:
.incbin "baserom.gba", 0x16912AC, 0x40
sPsyduckCryingGfx:
.incbin "baserom.gba", 0x16912EC, 0x288
sPsyduckShoutingPal:
.incbin "baserom.gba", 0x1691574, 0x40
sPsyduckShoutingGfx:
.incbin "baserom.gba", 0x16915B4, 0x28C
sPsyduckTearyEyePal:
.incbin "baserom.gba", 0x1691840, 0x40
sPsyduckTearyEyeGfx:
.string "AT4PX"
.incbin "baserom.gba", 0x1691885, 0x287
sPsyduckDeterminedPal:
.incbin "baserom.gba", 0x1691B0C, 0x40
sPsyduckDeterminedGfx:
.incbin "baserom.gba", 0x1691B4C, 0x28C
sPsyduckJoyousPal:
.incbin "baserom.gba", 0x1691DD8, 0x40
sPsyduckJoyousGfx:
.incbin "baserom.gba", 0x1691E18, 0x2CC
sPsyduckInspiredPal:
.incbin "baserom.gba", 0x16920E4, 0x40
sPsyduckInspiredGfx:
.incbin "baserom.gba", 0x1692124, 0x29C
sPsyduckSurprisedPal:
.incbin "baserom.gba", 0x16923C0, 0x40
sPsyduckSurprisedGfx:
.string "AT4PX"
.incbin "baserom.gba", 0x1692405, 0x297
sPortraitsPsyduck:
kao_portrait sPsyduckNormalPal, sPsyduckNormalGfx
kao_portrait sPsyduckHappyPal, sPsyduckHappyGfx
kao_portrait sPsyduckPainedPal, sPsyduckPainedGfx
kao_portrait sPsyduckAngryPal, sPsyduckAngryGfx
kao_portrait sPsyduckWorriedPal, sPsyduckWorriedGfx
kao_portrait sPsyduckSadPal, sPsyduckSadGfx
kao_portrait sPsyduckCryingPal, sPsyduckCryingGfx
kao_portrait sPsyduckShoutingPal, sPsyduckShoutingGfx
kao_portrait sPsyduckTearyEyePal, sPsyduckTearyEyeGfx
kao_portrait sPsyduckDeterminedPal, sPsyduckDeterminedGfx
kao_portrait sPsyduckJoyousPal, sPsyduckJoyousGfx
kao_portrait sPsyduckInspiredPal, sPsyduckInspiredGfx
kao_portrait sPsyduckSurprisedPal, sPsyduckSurprisedGfx
.incbin "baserom.gba", 0x1692704, 0x8
