.global gKaoRaikou
gKaoRaikou:
kao_siro sPortraitsRaikou
sRaikouNormalPal:
.incbin "baserom.gba", 0x16A7E5C, 0x40
sRaikouNormalGfx:
.incbin "baserom.gba", 0x16A7E9C, 0x2DC
sPortraitsRaikou:
kao_portrait sRaikouNormalPal, sRaikouNormalGfx
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
