.global gKaoSmeargle
gKaoSmeargle:
kao_siro sPortraitsSmeargle
sSmeargleNormalPal:
.incbin "baserom.gba", 0x16A7ADC, 0x40
sSmeargleNormalGfx:
.incbin "baserom.gba", 0x16A7B1C, 0x2C8
sPortraitsSmeargle:
kao_portrait sSmeargleNormalPal, sSmeargleNormalGfx
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
