.global gKaoXatu
gKaoXatu:
kao_siro sPortraitsXatu
sXatuNormalPal:
.incbin "baserom.gba", 0x16A5664, 0x40
sXatuNormalGfx:
.string "AT4PX"
.incbin "baserom.gba", 0x16A56A9, 0x277
sPortraitsXatu:
kao_portrait sXatuNormalPal, sXatuNormalGfx
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
kao_portrait 0, 0
