	.global gUnknown_80DD148
gUnknown_80DD148: @ 80DD148 (default friend area warp script)
        .byte 0x00, 0x00, 0x00, 0x00

        .byte 0x03, 0x00, 0x00, 0x00
        .byte 0x00, 0x00, 0x00, 0x00
        .byte 0x00, 0x00, 0x00, 0x00
        .byte 0x00, 0x00, 0x00, 0x00

        .byte 0x00, 0x00, 0x00, 0x00

	.global gUnknown_80DD160
gUnknown_80DD160: @ 80DD160 (Another friend area warp script)
        .byte 0x00, 0x00, 0x00, 0x00

        .byte 0x03, 0x00, 0x00, 0x00
        .byte 0x13, 0x00, 0x04, 0x00
        .byte 0x08, 0x00, 0x03, 0x00
        .byte 0x03, 0x00, 0x00, 0x00

        .byte 0x00, 0x00, 0x00, 0x00

	.global gUnknown_80DD178
gUnknown_80DD178: @ 80DD178 (Another friend area warp script)
        .byte 0x00, 0x00, 0x00, 0x00

        .byte 0x03, 0x00, 0x00, 0x00
        .byte 0x14, 0x00, 0x04, 0x00
        .byte 0x06, 0x00, 0x03, 0x00
        .byte 0x03, 0x00, 0x00, 0x00

        .byte 0x00, 0x00, 0x00, 0x00

	.global gUnknown_80DD190
gUnknown_80DD190: @ 80DD190 (seems to be Friend Area Warp Script)
        .byte 0x00, 0x00, 0x00, 0x00

        .byte 0x03, 0x00, 0x00, 0x00
        .byte 0x02, 0x00, 0x11, 0x00
        .byte 0x1A, 0x00, 0x02, 0x00
        .byte 0x02, 0x00, 0x00, 0x00

        .byte 0x00, 0x00, 0x00, 0x00

	.global gUnknown_80DD1A8
gUnknown_80DD1A8: @ 80DD1A8
        .string "Whom would you like to visit?\0"
        .align 2,0

	.global gUnknown_80DD1C8
gUnknown_80DD1C8: @ 80DD1C8
	.string "#+The #C4$i1#R was\n"
	.string "#+handed over. \0"
	.align 2,0

	.global gUnknown_80DD1EC
gUnknown_80DD1EC: @ 80DD1EC
	.string "#+The #C4$i1#R was\n"
	.string "#+handed over.#P"
	.string "#+The #C4$i0#R was\n"
	.string "#+returned to the Toolbox.\0"
	.align 2,0

	.global gUnknown_80DD240
gUnknown_80DD240: @ 80DD240
	.string "#+The #C4$i0#R was\n"
	.string "#+returned to the Toolbox.\0"
	.align 2,0

	.global gUnknown_80DD270
gUnknown_80DD270: @ 80DD270
        .string "#+$m1 left the team to remain\n"
        .string "#+on standby in the Friend Area.\0"
        .align 2,0

	.global gUnknown_80DD2B0
gUnknown_80DD2B0: @ 80DD2B0
        .string "Give\0"
        .align 2,0

	.global gUnknown_80DD2B8
gUnknown_80DD2B8: @ 80DD2B8
        .string "Take\0"
        .align 2,0

	.global gUnknown_80DD2C0
gUnknown_80DD2C0: @ 80DD2C0
        .string "Stand By\0"
        .align 2,0

	.global gUnknown_80DD2CC
gUnknown_80DD2CC: @ 80DD2CC
        .string "Visit\0"
        .align 2,0

	.global gUnknown_80DD2D4
gUnknown_80DD2D4: @ 80DD2D4
        .string "Name\0"
        .align 2,0

	.global gUnknown_80DD2DC
gUnknown_80DD2DC: @ 80DD2DC
        .string "Summary\0"
        .align 2,0

	.global gUnknown_80DD2E4
gUnknown_80DD2E4: @ 80DD2E4
        .string "Moves\0"
        .align 2,0

	.global gUnknown_80DD2EC
gUnknown_80DD2EC: @ 80DD2EC
        .string "Check IQ\0"
        .align 2,0

	.global gUnknown_80DD2F8
gUnknown_80DD2F8: @ 80DD2F8
        .string "Item: #C4$i0#R \0"
        .align 2,0
        .string "pksdir0\0"
        .align 2,0

	.global gUnknown_80DD310
gUnknown_80DD310: @ 80DD310 (default friend area script)
        .byte 0x00, 0x00, 0x00, 0x00

        .byte 0x03, 0x00, 0x00, 0x00
        .byte 0x00, 0x00, 0x00, 0x00
        .byte 0x00, 0x00, 0x00, 0x00
        .byte 0x00, 0x00, 0x00, 0x00

        .byte 0x00, 0x00, 0x00, 0x00

	.global gUnknown_80DD328
gUnknown_80DD328: @ 80DD328 (another friend area warp script)
        .byte 0x00, 0x00, 0x00, 0x00

        .byte 0x03, 0x00, 0x00, 0x00
        .byte 0x13, 0x00, 0x03, 0x00
        .byte 0x08, 0x00, 0x03, 0x00
        .byte 0x03, 0x00, 0x00, 0x00

        .byte 0x00, 0x00, 0x00, 0x00

	.global gUnknown_80DD340
gUnknown_80DD340: @ 80DD340
        .byte 0x00, 0x00, 0x00, 0x00

        .byte 0x03, 0x00, 0x00, 0x00
        .byte 0x14, 0x00, 0x04, 0x00
        .byte 0x06, 0x00, 0x03, 0x00
        .byte 0x03, 0x00, 0x00, 0x00

        .byte 0x00, 0x00, 0x00, 0x00

	.global gUnknown_80DD358
gUnknown_80DD358: @ 80DD358
        .byte 0x00, 0x00, 0x00, 0x00

        .byte 0x03, 0x00, 0x00, 0x00
        .byte 0x02, 0x00, 0x11, 0x00
        .byte 0x1A, 0x00, 0x02, 0x00
        .byte 0x02, 0x00, 0x00, 0x00

        .byte 0x00, 0x00, 0x00, 0x00

	.global gUnknown_80DD370
gUnknown_80DD370: @ 80DD370
        .byte 0x00, 0x00, 0x00, 0x00

        .byte 0x03, 0x00, 0x00, 0x00
        .byte 0x02, 0x00, 0x03, 0x00
        .byte 0x0F, 0x00, 0x02, 0x00
        .byte 0x02, 0x00, 0x00, 0x00

        .byte 0x00, 0x00, 0x00, 0x00
