#ifndef GUARD_DUNGEON_CUTSCENES_H
#define GUARD_DUNGEON_CUTSCENES_H

// TODO: Remove this file

#include "structs/dungeon_entity.h"

void ArticunoPostStoryPreFightDialogue(void);
void ArticunoPreFightDialogue(void);
void ArticunoReFightDialogue(void);
void CelebiJoinDialogue(void);
void DeoxysPreFightDialogue(void);
void DummyFightDialogue(void);
void EnteiPostStoryPreFightDialogue(void);
void EnteiPreFightDialogue(void);
void EnteiReFightDialogue(void);
void GroudonPostStoryPreFightDialogue(void);
void GroudonPreFightDialogue(void);
void GroudonReFightDialogue(void);
void HoOhPreFightDialogue(void);
void HoOhReFightDialogue(void);
void JirachiPreFightDialogue(void);
void JirachiReFightDialogue(void);
void KyogrePreFightDialogue(void);
void LatiosPreFightDialogue(void);
void LatiosReFightDialogue(void);
void LugiaPreFightDialogue(void);
void MagmaCavernMidDialogue(void);
void MedichamRescueDialogue(void);
void MewtwoPreFightDialogue(void);
void MewtwoReFightDialogue(void);
void MoltresPostStoryPreFightDialogue(void);
void MoltresPreFightDialogue(void);
void MoltresReFightDialogue(void);
void RaikouPostStoryPreFightDialogue(void);
void RaikouPreFightDialogue(void);
void RaikouReFightDialogue(void);
void RayquazaPostStoryPreFightDialogue(void);
void RayquazaPreFightDialogue(void);
void RayquazaReFightDialogue(void);
void RegicePreFightDialogue(void);
void RegirockPreFightDialogue(void);
void RegisteelPreFightDialogue(void);
void SkarmoryPreFightDialogue(void);
void SkarmoryReFightDialogue(void);
void SmeargleRescueDialogue(void);
void SuicunePostStoryPreFightDialogue(void);
void SuicunePreFightDialogue(void);
void SuicuneReFightDialogue(void);
void TeamMeaniesPreFightDialogue(void);
void TeamMeaniesReFightDialogue(void);
void ZapdosPostStoryPreFightDialogue(void);
void ZapdosPreFightDialogue(void);
void ZapdosReFightDialogue(void);
void HandleCelebiBossFaint(u8, u8, u8);
void sub_8086B14(void);
void sub_8086B94(void);
void HandleSkarmoryBossFaint(u8, u8);
void sub_8086E40(void);
void sub_8086E9C(void);
void sub_8086F00(void);
void HandleMeaniesBossFaint(u8, u8);
void sub_8087130(void);
void sub_8087230(void);
void sub_808729C(void);
void HandleZapdosBossFaint(u8, u8);
void sub_80877E8(void);
void sub_8087848(void);
void HandleMoltresBossFaint(u8, u8);
void sub_8087F54(void);
void sub_8087FB4(void);
void sub_8087FF8(void);
void HandleArticunoBossFaint(u8, u8);
void sub_80885A0(void);
void sub_80885C4(void);
void sub_8088608(void);
void sub_8088618(void);
void sub_808862C(void);
void sub_80886C4(void);
void sub_808875C(void);
void HandleGroudonBossFaint(u8, u8);
void sub_8088DC0(void);
void sub_8088E5C(void);
void sub_8089168(void);
void sub_80892C8(void);
void sub_8089328(void);
void HandleRayquazaBossFaint(u8, u8);
void sub_808970C(void);
void sub_808974C(void);
void HandleMankeyBossFaint(Entity *entity, u8, u8);
void sub_80897F0(void);
void sub_8089878(void);
void sub_80898E4(void);
void sub_8089914(void);
void sub_8089978(void);
void HandleMewtwoBossFaint(u8, u8);
void sub_8089C44(void);
void sub_8089C90(void);
void HandleEnteiBossFaint(u8, u8);
void sub_8089EFC(void);
void sub_8089F44(void);
void sub_8089F8C(void);
void HandleRaikouBossFaint(u8, u8);
void sub_808A264(void);
void sub_808A2C0(void);
void sub_808A308(void);
void HandleSuicuneBossFaint(u8, u8);
void sub_808A608(void);
void sub_808A668(void);
void HandleHoOhBossFaint(u8, u8);
void sub_808A9E4(void);
void sub_808AA3C(void);
void sub_808AA94(void);
void HandleLatiosBossFaint(u8, u8);
void sub_808AC3C(void);
void sub_808ACC0(void);
void sub_808AD48(void);
void sub_808ADCC(void);
void HandleRegirockBossFaint_Async(u8, u8, DungeonPos *pos);
void HandleRegiceBossFaint_Async(u8, u8, DungeonPos *pos);
void HandleRegisteelBossFaint_Async(u8, u8, DungeonPos *pos);
void sub_808AFB0_Async(u8);
void sub_808B030_Async(u8);
void sub_808B0B0_Async(u8);
void sub_808B2F4(void);
void sub_808B35C(void);
void HandleJirachiBossFaint_Async(u8 monsterBehavior, u8 cutscene, bool8 transformedIntoFriend);
void sub_808BDEC(void);
void HandleLugiaBossFaint(u8 monsterBehavior, u8 cutscene, bool8 transformedIntoFriend);
void sub_808C10C(void);
void HandleKyogreBossFaint(u8, u8, u8);
void sub_808C3A0(void);
void HandleDeoxysNormalBossFaint(u8, u8, u8);
void sub_808C5C0(void);
void sub_808C938(void);
void HandleMazeBossFaint(Entity *entity, u8);
void sub_808C998(void);
void sub_808C9C4(void);
void sub_808CB5C(void);
void sub_808CBB0(void);
void sub_808CD44(void);
void sub_808CD9C(void);

#endif /* ifndef GUARD_DUNGEON_CUTSCENES_H */
