#ifndef GUARD_FRIEND_AREA_DIALOGUE_H
#define GUARD_FRIEND_AREA_DIALOGUE_H

#define FRIEND_AREA_DIALOGUES_COUNT 18

extern const u8 *const gFriendAreaDialogue[FRIEND_AREA_DIALOGUES_COUNT];

#endif // GUARD_FRIEND_AREA_DIALOGUE_H
