#ifndef GUARD_GROUND_PLACE_H
#define GUARD_GROUND_PLACE_H

// Duplicate entries are most likely outdoors vs indoors. To verify which are which
enum GroundPlace {
    GROUND_PLACE_SQUARE,
    GROUND_PLACE_SQUARE_2,
    GROUND_PLACE_POKEMON_SQUARE,
    GROUND_PLACE_WHISCASH_POND,
    GROUND_PLACE_PELIPPER_POST_OFFICE,
    GROUND_PLACE_PELIPPER_POST_OFFICE_INSIDE,
    GROUND_PLACE_MAKUHITA_DOJO,
    GROUND_PLACE_MAKUHITA_DOJO_INSIDE, // unused
    GROUND_PLACE_LUMINOUS_CAVE,
    GROUND_PLACE_FRIEND_AREAS,
    GROUND_PLACE_TEAM_BASE,
    GROUND_PLACE_TEAM_BASE_INSIDE,
    GROUND_PLACE_DUNGEON,
    GROUND_PLACE_TINY_WOODS,
    GROUND_PLACE_THUNDERWAVE_CAVE,
    GROUND_PLACE_MT_STEEL,
    GROUND_PLACE_SINISTER_WOODS,
    GROUND_PLACE_SILENT_CHASM,
    GROUND_PLACE_MT_THUNDER,
    GROUND_PLACE_MT_THUNDER_MID,
    GROUND_PLACE_GREAT_CANYON,
    GROUND_PLACE_HILL_OF_THE_ANCIENTS,
    GROUND_PLACE_LAPIS_CAVE,
    GROUND_PLACE_LAPIS_CAVE_EXIT,
    GROUND_PLACE_MT_BLAZE,
    GROUND_PLACE_MT_BLAZE_MID,
    GROUND_PLACE_FROSTY_FOREST,
    GROUND_PLACE_FROSTY_CLEARING,
    GROUND_PLACE_MT_FREEZE,
    GROUND_PLACE_MT_FREEZE_MID,
    GROUND_PLACE_MAGMA_CAVERN,
    GROUND_PLACE_MAGMA_CAVERN_MID,
    GROUND_PLACE_SKY_TOWER,
    GROUND_PLACE_SKY_TOWER_MID,
    GROUND_PLACE_WESTERN_CAVE,
    GROUND_PLACE_DIRECTION, // Similarly to GROUND_PLACE_SCENE, used in the conversion table for bgs which are not maps.
    GROUND_PLACE_NEW_GAME,
    GROUND_PLACE_SCENE, // For all maps that aren't really maps, for example warning screen, personality test background, etc.
    GROUND_PLACE_INVALIDITY, // Probably marks the last entry, not used in-game.
};

const u8 *GetGroundPlaceName(s16 id);

#endif // GUARD_GROUND_PLACE_H
