enum MainMenuScreens
{
    MENU_MAIN_SCREEN = 1,
    MENU_CONTINUE = 7,
    MENU_DELETE_SAVE_PROMPT,
    MENU_ADVENTURE_LOG = 10,
    MENU_FRIEND_RESCUE,
    MENU_TRADE_ITEMS,
    MENU_WONDER_MAIL,
    MENU_DEBUG = 16,
    MENU_COMMUNICATION_1 = 19,
    MENU_COMMUNICATION_2,
    MENU_DISPLAY_RESCUE_PASSWORD = 33,
    MENU_RESCUE_PASSWORD_ENTRY,
    MENU_DELETE_SAVE = 46,
    MENU_DEBUG_UNKNOWN_0,
    MENU_DEBUG_UNKNOWN_1,
    MENU_DEBUG_UNKNOWN_2,
    MENU_DEBUG_UNKNOWN_3,
    MENU_DEBUG_UNKNOWN_4,
    MENU_DEBUG_UNKNOWN_5,
    MENU_NO_SCREEN_CHANGE = 0xffdc
};
