#ifndef GUARD_PORTRAIT_PLACEMENT_H
#define GUARD_PORTRAIT_PLACEMENT_H

#include "structs/str_position.h"

// Size: R=0x8 | B=0x5
struct PortraitPlacementInfo
{
    /* 0x0 */ DungeonPos pos;
    /* 0x4 */ bool8 flip;
};

// These are named like `PLACEMENT_X_Y` and `PLACEMENT_X_Y_FLIP`
enum PortraitPlacementID
{
    PLACEMENT_LEFT_BOTTOM_1,
    PLACEMENT_CENTERLEFT_CENTER,
    PLACEMENT_LEFT_BOTTOM_2, // Same as PLACEMENT_LEFT_BOTTOM_1
    PLACEMENT_RIGHT_BOTTOM_FLIP,
    PLACEMENT_MIDLEFT_BOTTOM,
    PLACEMENT_MIDRIGHT_BOTTOM_FLIP,
    PLACEMENT_CENTERRIGHT_CENTER_FLIP,
    PLACEMENT_LEFT_BOTTOM_FLIP,
    PLACEMENT_RIGHT_BOTTOM,
    PLACEMENT_MIDLEFT_BOTTOM_FLIP,
    PLACEMENT_MIDRIGHT_BOTTOM,
    PLACEMENT_CENTERLEFT_TOP,
    PLACEMENT_LEFT_MIDTOP,
    PLACEMENT_RIGHT_MIDTOP_FLIP,
    PLACEMENT_MIDLEFT_TOP,
    PLACEMENT_MIDRIGHT_TOP_FLIP,
    PLACEMENT_CENTERRIGHT_TOP_FLIP,
    PLACEMENT_LEFT_MIDTOP_FLIP,
    PLACEMENT_RIGHT_MIDTOP,
    PLACEMENT_MIDLEFT_TOP_FLIP,
    PLACEMENT_MIDRIGHT_TOP,

    PLACEMENT_COUNT
};

#endif // GUARD_PORTRAIT_PLACEMENT_H
