#include "global.h"
#include "globaldata.h"
#include "dungeon_strings.h"

// TODO: Give proper names to the strings
const ItemText gActions[] = {
    [0] = { _("{POKEMON_0} used\nthe {MOVE_ITEM_0}."), _("Use")},
    [1] = { _("{POKEMON_0} threw\nthe {MOVE_ITEM_0}."), _("Throw")},
    [2] = { _("{POKEMON_0} threw\nthe {MOVE_ITEM_0}."), _("Throw")},
    [3] = { _("{POKEMON_0} equipped\nthe {MOVE_ITEM_0}."), _("Equip")},
    [4] = { _("{POKEMON_0} ate\nthe {MOVE_ITEM_0}."), _("Eat")},
    [5] = { _("{POKEMON_0} swallowed\nthe {MOVE_ITEM_0}."), _("Ingest")},
    [6] = { _("{POKEMON_0} peeled\nthe {MOVE_ITEM_0}."), _("Peel")},
    [7] = { _("{POKEMON_0} used\nthe {MOVE_ITEM_0}."), _("Use")},
    [8] = { _("{POKEMON_0} used\nthe {MOVE_ITEM_0}."), _("Use")},
    [9] = { _("{POKEMON_0} used\nthe {MOVE_ITEM_0}."), _("Use")},
    [10] = { _("{POKEMON_0} used\nthe {MOVE_ITEM_0}."), _("Use")},
    [11] = { _("{POKEMON_0} put on\nthe {MOVE_ITEM_0}."), _("Equip")},
    [12] = { _("{POKEMON_0} put on\nthe {MOVE_ITEM_0}."), _("Equip")},
    [13] = { _("{POKEMON_0} used\nthe {MOVE_ITEM_0}."), _("Use")},
    [14] = { _("{POKEMON_0} used\nthe {MOVE_ITEM_0}."), _("Use")},
    [15] = { _("{POKEMON_0} used\nthe {MOVE_ITEM_0}."), _("Use")},
};

const struct Struct_80F7C50 gUnknown_80F7C50[] = {
    [0] = { _("???"), 0x0000000A},
    [1] = { _("Wait"), 0x0000000A},
    [2] = { _("Move"), 0x0000000A},
    [3] = { _("Move"), 0x0000000A},
    [4] = { _("Wait"), 0x0000000A},
    [5] = { _("Wait"), 0x0000000A},
    [6] = { _("Next"), 0x0000000A},
    [7] = { _("Prev."), 0x0000000A},
    [8] = { _("Place"), 0x0000000A},
    [9] = { _("Get"), 0x0000000A},
    [10] = { _("Switch"), 0x0000000A},
    [11] = { _("Throw"), 0x0000000A},
    [12] = { _("Info"), 0x0000005A},
    [13] = { _("X"), 0x0000000A},
    [14] = { _("X"), 0x0000000A},
    [15] = { _("X"), 0x0000000A},
    [16] = { _("X"), 0x0000000A},
    [17] = { _("X"), 0x0000000A},
    [18] = { _("X"), 0x0000000A},
    [19] = { _("Talk"), 0x0000000A},
    [20] = { _("Use"), 0x0000000A},
    [21] = { _("Use"), 0x0000000A},
    [22] = { _(""), 0x0000000A},
    [23] = { _("Struggle"), 0x0000000A},
    [24] = { _("$$$$"), 0x000003E7},
    [25] = { _("Moves"), 0x0000000A},
    [26] = { _("Tactics"), 0x0000000A},
    [27] = { _("Summary"), 0x0000000A},
    [28] = { _("Talk"), 0x0000000A},
    [29] = { _("Info"), 0x0000005A},
    [30] = { _("Set"), 0x0000000A},
    [31] = { _("Switch"), 0x0000000A},
    [32] = { _("Link"), 0x0000000A},
    [33] = { _("Delink"), 0x0000000A},
    [34] = { _("Forget"), 0x0000000A},
    [35] = { _("Use"), 0x0000000A},
    [36] = { _("Throw"), 0x0000000A},
    [37] = { _("Trigger"), 0x0000000A},
    [38] = { _("Proceed"), 0x0000000A},
    [39] = { _("Throw"), 0x00000005},
    [40] = { _("Switch"), 0x0000000A},
    [41] = { _("Farewell"), 0x0000000A},
    [42] = { _("Cancel"), 0x0000000A},
    [43] = { _("Quicksave"), 0x0000000A},
    [44] = { _("Use"), 0x0000000A},
    [45] = { _("Talk"), 0x0000000A},
    [46] = { _("Give Up"), 0x0000000A},
    [47] = { _("Switch"), 0x0000000A},
    [48] = { _("Check IQ"), 0x0000000A},
    [49] = { _("Use"), 0x0000000A},
    [50] = { _("Use"), 0x0000000A},
    [51] = { _("Deselect"), 0x0000000A},
    [52] = { _("Farewell"), 0x0000000A},
    [53] = { _("Use"), 0x0000000A},
    [54] = { _("Give"), 0x0000000A},
    [55] = { _("Take"), 0x0000000A},
    [56] = { _("Use"), 0x0000000A},
    [57] = { _(""), 0x0000000A},
    [58] = { _("Swap"), 0x0000000A},
    [59] = { _("Leader"), 0x0000000A},
    [60] = { _("Set"), 0x0000000A},
    [61] = { _("Deselect"), 0x0000000A},
    [62] = { _("Swap"), 0x0000000A},
    [63] = { _("Pick Up"), 0x0000000A},
    [64] = { _("Summary"), 0x0000000A},
    [65] = { _("Throw"), 0x00000005},
};

const u8 *const gUnknown_80F7F70[] = {
    [0] = _("Stairs leading to the next floor.\nIf you are on the final floor, you will\nescape from the dungeon."),
    [1] = _("The warp zone leading to the next floor.\nIf you are on the final floor, you will\nescape from the dungeon."),
    [2] = _("You reached the rescue spot where your\nfriend's team went down!\nSend an {color RED}A-OK Mail{reset} from the Pelipper Post\nOffice to let your friend know you've\nrescued the defeated team."),
};

const u8 *const gUnknown_80F8104[] = {
    [0] = _("Stairs"),
    [1] = _("Warp Zone"),
    [2] = _("Rescue Spot"),
};

const u8 *const gTrapDescriptions[NUM_TRAPS] = {
    [TRAP_TRIP_TRAP] = _("Stepping on this trap makes the Pokémon\ntrip and drop an item."),
    [TRAP_MUD_TRAP] = _("Stepping on this trap makes it blow\nmud that lowers the Pokémon's {color YELLOW}Attack{reset},\n{color YELLOW}Defense{reset}, {color YELLOW}Special Attack{reset}, or\n{color YELLOW}Special Defense{reset} by one level."),
    [TRAP_STICKY_TRAP] = _("Stepping on this trap makes a random\nitem become sticky and unusable."),
    [TRAP_GRIMY_TRAP] = _("Stepping on this trap makes it spew\nmuck that gums up food."),
    [TRAP_SUMMON_TRAP] = _("Stepping on this trap releases a sweet\naroma that attracts Pokémon from afar."),
    [TRAP_PITFALL_TRAP] = _("Stepping on this trap drops the Pokémon\nto the next floor, inflicting damage.\nIf it's not the team leader, the Pokémon\nfaints. If that happens, even a Reviver\nSeed can't help the fainted Pokémon."),
    [TRAP_WARP_TRAP] = _("Stepping on this trap instantly warps\nthe Pokémon to another spot on the floor."),
    [TRAP_WHIRLWIND_TRAP] = _("Stepping on this trap triggers a blast\nof some sort that sends the Pokémon\nflying."),
    [TRAP_SPIN_TRAP] = _("Stepping on this trap spins the Pokémon\naround dizzyingly, making it \n{color CYAN}confused{reset}."),
    [TRAP_SLUMBER_TRAP] = _("Stepping on this trap releases a sleeping\ngas that puts the Pokémon to\n{color CYAN}sleep{reset}."),
    [TRAP_SLOW_TRAP] = _("Stepping on this trap lowers the\nPokémon's {color YELLOW}Movement Speed{reset} by one level."),
    [TRAP_SEAL_TRAP] = _("Stepping on this trap disables one\nof the Pokémon's moves as long\nas it remains on the same floor."),
    [TRAP_POISON_TRAP] = _("Stepping on this trap looses poison\nspikes that leave the Pokémon {color CYAN}poisoned{reset}."),
    [TRAP_SELFDESTRUCT_TRAP] = _("Stepping on this trap makes it {color CYAN}explode{reset}.\nIts damage extends to other Pokémon,\nitems, and walls around the trap."),
    [TRAP_EXPLOSION_TRAP] = _("Stepping on this trap triggers a\n{color CYAN}huge explosion{reset}.\nIts damage extends to other Pokémon,\nitems, and walls. It has a bigger\nrange than a Selfdestruct Trap."),
    [TRAP_PP_ZERO_TRAP] = _("Stepping on this trap completely drains\nthe {color YELLOW}PP{reset} of a random move."),
    [TRAP_CHESTNUT_TRAP] = _("Stepping on this trap makes a spiky,\nunshelled Chestnut drop, inflicting\ndamage."),
    [TRAP_WONDER_TILE] = _("An odd floor tile seen in many dungeons.\nStepping on it resets the Pokémon's\n{color YELLOW}Attack{reset}, {color YELLOW}Defense{reset}, and so on, if\nthey are boosted or reduced."),
    [TRAP_POKEMON_TRAP] = _("Stepping on this trap transforms all\nitems in the room into hostile Pokémon."),
    [TRAP_SPIKE_TRAP] = _("Stepping on this trap inflicts damage.\nIt can be made using the move {color YELLOW}Spikes{reset}."),
};

const u8 *const gUnknown_80F8968 = _("{color YELLOW}Decoy{reset}");
const u8 *const gUnknown_80F8974 = _("Decoy");
const u8 *const gUnknown_80F8988 = _("{color YELLOW}Pokémon{reset}");
const u8 *const gUnknown_80F8994 = _("Pokémon");
const u8 *const gUnknown_80F89B4 = _("Your partner {POKEMON_0} fainted!");
const u8 *const gUnknown_80F89D4 = _("Your client {POKEMON_0} fainted!");
const u8 *const gUnknown_80F89D8 = _("Your client {POKEMON_0} fainted!");
const u8 *const gUnknown_80F89F4 = _("But nothing happened!");
const u8 *const gUnknown_80F8A0C = _("{POKEMON_0} was blown away!");
const u8 *const gUnknown_80F8A28 = _("No move has been set.");
const u8 *const gUnknown_80F8A4C = _("The set move can't be used.");
const u8 *const gUnknown_80F8A6C = _("You're being constricted!");
const u8 *const gUnknown_80F8A84 = _("You can't move!");
const u8 *const gUnknown_80F8AB0 = _("You can't move while you're rooted!");
const u8 *const gUnknown_80F8ADC = _("You can't move while wrapping a foe!");
const u8 *const gUnknown_80F8B0C = _("The foe has you wrapped! You can't move!");
const u8 *const gUnknown_80F8B24 = _("There are no items.");
const u8 *const gUnknown_80F8B40 = _("The move {MOVE_ITEM_0} was set.");
const u8 *const gUnknown_80F8B64 = _("The move {MOVE_ITEM_0} was deselected.");
const u8 *const gUnknown_80F8B68 = _("");
const u8 *const gUnknown_80F8B88 = _("The move {MOVE_ITEM_0} was delinked.");
const u8 *const gUnknown_80F8BB4 = _("The linked moves were left unchanged.");
const u8 *const gUnknown_80F8BE0 = _("It's all sticky and doesn't work!");
const u8 *const gUnknown_80F8BE4 = _("The {MOVE_ITEM_1} is all sticky!\nIt doesn't work!");
const u8 *const gItemStickyCannotMove1 = _("The {MOVE_ITEM_1} is all sticky!\nIt can't be moved.");
const u8 *const gItemStickyCannotMove2 = _("The {MOVE_ITEM_1} is all sticky!\nIt can't be moved.");
const u8 *const gItemStickyCannotMove3 = _("The {MOVE_ITEM_1} is all sticky!\nIt can't be moved.");
const u8 *const gItemStickyCannotEquip = _("The {MOVE_ITEM_0} is all sticky!\nIt can't be equipped.");
const u8 *const gMonTookAndReturnedItem = _("{POKEMON_1} took the {MOVE_ITEM_0}\nand returned the {MOVE_ITEM_1}.");
const u8 *const gUnknown_80F8CE4 = _("The {MOVE_ITEM_0} was set.\nHold {L_BUTTON} then press {R_BUTTON} to throw one.");
const u8 *const gUnknown_80F8CE8 = _("The {MOVE_ITEM_0} was set.\nHold {L_BUTTON} then press {R_BUTTON} to throw one.");
const u8 *const gUnknown_80F8D04 = _("Equipped the item {MOVE_ITEM_0}.");
const u8 *const gUnknown_80F8D20 = _("The {MOVE_ITEM_0} was deselected.");
const u8 *const gUnknown_80F8D44 = _("The item {MOVE_ITEM_0} was given\nto {POKEMON_1}.");
const u8 *const gUnknown_80F8D60 = _("The Toolbox is full.");
const u8 *const gUnknown_80F8D7C = _("{POKEMON_0} returned\nthe {MOVE_ITEM_0}.");
const u8 *const gUnknown_80F8DB4 = _("The {MOVE_ITEM_0} was exchanged for\nthe {MOVE_ITEM_1} in the Toolbox.");
const u8 *const gUnknown_80F8DB8 = _("{POKEMON_1} used the {MOVE_ITEM_0}\nit was holding!");
const u8 *const gUnknown_80F8DE0 = _("");
const u8 *const gUnknown_80F8E04 = _("It can't be put down here.");
const u8 *const gUnknown_80F8E28 = _("{POKEMON_0} put the {MOVE_ITEM_0}\non the ground.");
const u8 *const gUnknown_80F8E2C = _("");
const u8 *const gNoExchangesHere = _("Items can't be exchanged here.");
const u8 *const gNothingCanBePutDownHere = _("Nothing can be put down here.");
const u8 *const gSwappedGroundItem = _("Exchanged the {MOVE_ITEM_1} on the\nground with the {MOVE_ITEM_0}.");
const u8 *const gMonThrewItem1 = _("{POKEMON_0} threw the {MOVE_ITEM_0}!");
const u8 *const gMonThrewItem2 = _("{POKEMON_0} threw the {MOVE_ITEM_0}!");
const u8 *const gCannotTalk = _("You can't talk now.");
const u8 *const gCannotFarewell = _("You can't say farewell now.");
const u8 *const gMonCringing = _("{POKEMON_0} is cringing!");
const u8 *const gMonParalyzed = _("{POKEMON_0} is paralyzed!");
const u8 *const gMonSteppedOnItem = _("{POKEMON_0} stepped on\nthe {MOVE_ITEM_0}.");
const u8 *const gMonTerrifiedCouldntPickUpItem = _("{POKEMON_0} is terrified.\nIt didn't pick up the {MOVE_ITEM_0}.");
const u8 *const gMonCouldntPickUpItem = _("{POKEMON_0} couldn't pick up\nthe {MOVE_ITEM_0}.");
const u8 *const gPickedUpItem2 = _("Picked up the {MOVE_ITEM_0}.");
const u8 *const gPickedUpItemToolbox = _("Picked up the {MOVE_ITEM_0} and\nput it in the Toolbox.");
const u8 *const gPickedUpItem = _("Picked up the {MOVE_ITEM_0}.");
const u8 *const gMonPickedUpItem2 = _("{POKEMON_0} picked up\nthe {MOVE_ITEM_0}.");
const u8 *const gMonPickedUpItemToolbox = _("{POKEMON_0} picked up the\n{MOVE_ITEM_0} and put it in the Toolbox.");
const u8 *const gMonPickedUpItem = _("{POKEMON_0} picked up\nthe {MOVE_ITEM_0}.");
const u8 *const gSayFarewellQ = _("Say farewell to {POKEMON_0}?\nIt will be gone from the team forever.");
const u8 *const gSendMonBackWithItemQ = _("Send {POKEMON_0} back?\n{POKEMON_0}'s hold item will be lost.");
const u8 *const gSendMonBackQ = _("Send {POKEMON_0} back?");
const u8 *const gUnknown_80F9114 = _("Say farewell to {POKEMON_0} and dismiss\nit from the team?");
const u8 *const gUnknown_80F913C = _("{POKEMON_0} seemed disappointed and left.");
const u8 *const gMonWentBack = _("{POKEMON_0} went back.");
const u8 *const gMonDisappointedAndLeft = _("{POKEMON_0} seemed disappointed and left.");
const u8 *const gUnknown_80F9158 = _("{POKEMON_0} used\nthe {MOVE_ITEM_0}.");
const u8 *const gUnknown_80F9174 = _("$-Belly:{UNK_MACRO_3E M3E_147}{VALUE_0}/{VALUE_1}");
const u8 *const gUnknown_80F9190 = _("Money:{UNK_MACRO_3E M3E_147}{VALUE_0} {POKE}");
const u8 *const gUnknown_80F91A8 = _("Weather:{UNK_MACRO_3E M3E_159}{POKEMON_0}");
const u8 *const gUnknown_80F91C8 = _("Play:{UNK_MACRO_3E M3E_147}{VALUE_0}:$V12:$V22");
const u8 *const gUnknown_80F91E0 = _("{POKEMON_0}{UNK_MACRO_3E M3E_66}$v03/$v13");
const u8 *const gUnknown_80F91EC = _("Rescue");
const u8 *const gTrapNames[NUM_TRAPS] = {
    [TRAP_TRIP_TRAP] = _("Trip Trap"),
    [TRAP_MUD_TRAP] = _("Mud Trap"),
    [TRAP_STICKY_TRAP] = _("Sticky Trap"),
    [TRAP_GRIMY_TRAP] = _("Grimy Trap"),
    [TRAP_SUMMON_TRAP] = _("Summon Trap"),
    [TRAP_PITFALL_TRAP] = _("Pitfall Trap"),
    [TRAP_WARP_TRAP] = _("Warp Trap"),
    [TRAP_WHIRLWIND_TRAP] = _("Gust Trap"),
    [TRAP_SPIN_TRAP] = _("Spin Trap"),
    [TRAP_SLUMBER_TRAP] = _("Slumber Trap"),
    [TRAP_SLOW_TRAP] = _("Slow Trap"),
    [TRAP_SEAL_TRAP] = _("Seal Trap"),
    [TRAP_POISON_TRAP] = _("Poison Trap"),
    [TRAP_SELFDESTRUCT_TRAP] = _("Selfdestruct Trap"),
    [TRAP_EXPLOSION_TRAP] = _("Explosion Trap"),
    [TRAP_PP_ZERO_TRAP] = _("PP-Zero Trap"),
    [TRAP_CHESTNUT_TRAP] = _("Chestnut Trap"),
    [TRAP_WONDER_TILE] = _("Wonder Tile"),
    [TRAP_POKEMON_TRAP] = _("Pokémon Trap"),
    [TRAP_SPIKE_TRAP] = _("Spiked Tile"),
};

const u8 *const gUnknown_80F9364 = _("{POKEMON_1} is unaffected!");
const u8 *const gUnknown_80F9380 = _("The move missed {POKEMON_1}!");
const u8 *const gUnknown_80F9384 = _("The move missed {POKEMON_1}!");
const u8 *const gUnknown_80F93A4 = _("It had no effect on {POKEMON_1}!");
const u8 *const gUnknown_80F93C8 = _("The move {MOVE_ITEM_0} can't be used!");
const u8 *const gItemFellOnGround = _("The {MOVE_ITEM_0} fell on the ground.");
const u8 *const gItemFellInWater = _("The {MOVE_ITEM_0} fell in the water.");
const u8 *const gItemBuried = _("The {MOVE_ITEM_0} became buried.");
const u8 *const gItemLost = _("The {MOVE_ITEM_0} was lost!");
const u8 *const gAllItemsLost = _("All the items were lost!");
const u8 *const gSeveralItemsLost = _("Several items were lost!");
const u8 *const gItemFellOutOfSight = _("The {MOVE_ITEM_0} fell out of sight!");
const u8 *const gUnknown_80F94C4 = _("The {MOVE_ITEM_0} went flying\ntowards {POKEMON_0}!");
const u8 *const gUnknown_80F94D8 = _("It missed {POKEMON_0}!");
const u8 *const gUnknown_80F94F0 = _("{POKEMON_0} dodged the {MOVE_ITEM_0}!");
const u8 *const gUnknown_80F9510 = _("The {MOVE_ITEM_0} bounced off\n{POKEMON_0}!");
const u8 *const gUnknown_80F9530 = _("The {MOVE_ITEM_0} flew out of sight!");
const u8 *const gPtrFrozenMessage = _("{POKEMON_0} is frozen solid!");
const u8 *const gPtrWrappedAroundMessage = _("{POKEMON_0} has its foe wrapped!");
const u8 *const gPtrWrappedByMessage = _("{POKEMON_0} is wrapped by its foe!");
const u8 *const gPtrPausedMessage = _("{POKEMON_0} can't move!");
const u8 *const gPtrInfatuatedMessage = _("{POKEMON_0} is infatuated!");
const u8 *const gPtrBideMessage = _("{POKEMON_0} is storing energy!");
const u8 *const gUnknown_80F95EC = _("{POKEMON_0} is asleep!");
const u8 *const gUnknown_80F9600 = _("{POKEMON_1} is frozen!");
const u8 *const gUnknown_80F9614 = _("A critical hit!");
const u8 *const gUnknown_80F9630 = _("It has little effect...");
const u8 *const gUnknown_80F9654 = _("It's not very effective...");
const u8 *const gUnknown_80F9670 = _("It's super effective!");
const u8 *const gUnknown_80F9688 = _("{POKEMON_1} took no damage!");
const u8 *const gUnknown_80F96A8 = _("{POKEMON_1} took calamitous damage!");
const u8 *const gUnknown_80F96BC = _("{POKEMON_0} exploded!");
const u8 *const gUnknown_80F96EC = _("The damp conditions prevented\nan explosion!");
const u8 *const gUnknown_80F970C = _("{POKEMON_0} fell into the pitfall!");
const u8 *const gUnknown_80F9728 = _("Avoided the pitfall!");
const u8 *const gUnknown_80F9740 = _("{POKEMON_0} is famished.");
const u8 *const gUnknown_80F9760 = _("{POKEMON_0} is already famished.");

const u8 *const gResidualDamageMessages[NUM_RESIDUAL_DAMAGE_TYPES] = {
    [RESIDUAL_DAMAGE_REGULAR]       = _("{POKEMON_1} took {VALUE_0} damage!"),
    [RESIDUAL_DAMAGE_BURN]          = _("{POKEMON_1}'s burn inflicted\n{VALUE_0} damage!"),
    [RESIDUAL_DAMAGE_CONSTRICT]     = _("{POKEMON_1} was squeezed for\n{VALUE_0} damage!"),
    [RESIDUAL_DAMAGE_POISON]        = _("{POKEMON_1} took {VALUE_0} damage\nfrom poison!"),
    [RESIDUAL_DAMAGE_UNUSED_4]      = _("{POKEMON_1} took {VALUE_0} damage!"),
    [RESIDUAL_DAMAGE_WRAP]          = _("{POKEMON_1} was wrapped for\n{VALUE_0} damage!"),
    [RESIDUAL_DAMAGE_COUNTERATTACK] = _("{POKEMON_1} took {VALUE_0} damage\nfrom the counterattack!"),
    [RESIDUAL_DAMAGE_CURSE]         = _("{POKEMON_1} was cursed for\n{VALUE_0} damage!"),
    [RESIDUAL_DAMAGE_NIGHTMARE]     = _("{POKEMON_1} awoke from its nightmare\nand took {VALUE_0} damage!"),
    [RESIDUAL_DAMAGE_LEECH_SEED]    = _("{POKEMON_1} took {VALUE_0} damage\nfrom Leech Seed!"),
    [RESIDUAL_DAMAGE_SPIKES]        = _("{POKEMON_1} stepped on spikes for\n{VALUE_0} damage!"),
    [RESIDUAL_DAMAGE_PERISH_SONG]   = _("{POKEMON_1} took {VALUE_0} damage\nfrom Perish Song!"),
    [RESIDUAL_DAMAGE_DESTINY_BOND]  = _("{POKEMON_1} took {VALUE_0} damage\nfrom Destiny Bond!"),
    [RESIDUAL_DAMAGE_LIQUID_OOZE]   = _("{POKEMON_1} was showered with sludge\nfor {VALUE_0} damage!"),
    [RESIDUAL_DAMAGE_HUNGER]        = NULL,
    [RESIDUAL_DAMAGE_CHESTNUT_TRAP] = _("The Chestnut Trap hit {POKEMON_1}\nfor {VALUE_0} damage!"),
    [RESIDUAL_DAMAGE_UNUSED_16]     = _("The Chestnut Trap hit {POKEMON_1}\nfor {VALUE_0} damage!"),
    [RESIDUAL_DAMAGE_PITFALL]       = _("{POKEMON_1} took {VALUE_0} damage!"),
    [RESIDUAL_DAMAGE_BAD_WEATHER]   = _("The bad weather inflicted {VALUE_0} damage\non {POKEMON_1}!"),
    [RESIDUAL_DAMAGE_MOVE_FAIL]     = _("The move failed!\n{POKEMON_1} took {VALUE_0} damage!"),
    [RESIDUAL_DAMAGE_RECOIL]        = _("The recoil hit {POKEMON_1} for\n{VALUE_0} damage!"),
};

const u8 *const gWeatherNames[WEATHER_COUNT] = {
    [WEATHER_CLEAR] = _("Clear"),
    [WEATHER_SUNNY] = _("Sunny"),
    [WEATHER_SANDSTORM] = _("Sandstorm"),
    [WEATHER_CLOUDY] = _("Cloudy"),
    [WEATHER_RAIN] = _("Rain"),
    [WEATHER_HAIL] = _("Hail"),
    [WEATHER_FOG] = _("Fog"),
    [WEATHER_SNOW] = _("Snow"),
};

const u8 *const gUnknown_80F9ACC = _("{POKEMON_0}'s HP went up {VALUE_0}!");
const u8 *const gUnknown_80F9AEC = _("{POKEMON_0}'s Attack went up {VALUE_1}!");
const u8 *const gUnknown_80F9B10 = _("{POKEMON_0}'s Defense went up {VALUE_2}!");
const u8 *const gUnknown_80F9B34 = _("{POKEMON_0}'s Sp. Atk. went up {VALUE_3}!");
const u8 *const gUnknown_80F9B58 = _("{POKEMON_0}'s Sp. Def. went up $d4!");
const u8 *const gUnknown_80F9B74 = _("{POKEMON_0} didn't level up.");
const u8 *const gUnknown_80F9B94 = _("{POKEMON_0} didn't level down.");
const u8 *const gUnknown_80F9BB0 = _("{POKEMON_0} became the leader!");
const u8 *const gUnknown_80F9BD8 = _("The leader couldn't be switched!");
const u8 *const gUnknown_80F9C08 = _("You haven't paid for the merchandise yet!");
const u8 *const gUnknown_80F9C2C = _("A thief can't switch leaders!");
const u8 *const gUnknown_80F9C4C = _("...Something's stirring.");
const u8 *const gUnknown_80F9C70 = _("...Something's approaching.");
const u8 *const gUnknown_80F9C8C = _("It's getting closer!");
const u8 *const gUnknown_80F9CBC = _("It's right nearby! It's gusting hard!");
const u8 *const gUnknown_80F9CC0[] = {
    [0] = _("{POKEMON_1} was defeated!"),
    [1] = _("{POKEMON_1} fainted!"),
};

const u8 *const gUnknown_80F9CEC[] = {
    [0] = _("Oh, no! {POKEMON_1} was defeated!"),
    [1] = _("Oh, no! {POKEMON_1} fainted!"),
};

const u8 *const gUnknown_80F9D28[] = {
    [0] = _("{POKEMON_1} was defeated!\nIt left the rescue team!"),
    [1] = _("{POKEMON_1} fainted!\nIt left the rescue team!"),
};

const u8 *const gUnknown_80F9D84[] = {
    [0] = _("Oh, no! {POKEMON_1} was defeated!"),
    [1] = _("Oh, no! {POKEMON_1} fainted!"),
};

const u8 *const gUnknown_80F9D8C[] = {
    [0] = _("{POKEMON_1} went back for now!"),
    [1] = _("Oh, no! {POKEMON_1} fainted!"),
};

const u8 *const gUnknown_80F9DAC[] = {
    [0] = _("Your client {POKEMON_1} was defeated!"),
    [1] = _("Your client {POKEMON_1} fainted!"),
};

const u8 *const gUnknown_80F9DF0[] = {
    [0] = _("{POKEMON_1} was defeated while awaiting\nrescue!"),
    [1] = _("{POKEMON_1} fainted while awaiting\nrescue!"),
};

const u8 *const gUnknown_80F9E44 = _("{POKEMON_1} fainted!");
const u8 *const gUnknown_80F9E64 = _("{POKEMON_0} gained {VALUE_0} Exp. Points!");
const u8 *const gUnknown_80F9E80 = _("{POKEMON_0} grew to Level {VALUE_0}!");
const u8 *const gUnknown_80F9E84 = _("{POKEMON_0}'s level remained unchanged.");
const u8 *const gUnknown_80F9EC8 = _("{POKEMON_0} dropped to Level {VALUE_0}!");
const u8 *const gUnknown_80F9EEC = _("{POKEMON_0}'s level didn't go down.");
const u8 *const gUnknown_80F9F04 = _("{POKEMON_0} learned {MOVE_ITEM_0}!");
const u8 *const gUnknown_80F9F2C = _("{POKEMON_0} didn't learn the new move.");
const u8 *const gUnknown_80F9FA4 = _("This Pokémon learned a new move,\nso it must forget an old one. Moves can\nbe relearned at the Gulpin Link Shop.");
const u8 *const gUnknown_80F9FE8 = _("Yes! {POKEMON_0} wants to join the team!\nAccept {POKEMON_0} as a team member?");
const u8 *const gUnknown_80F9FEC = _("");
const u8 *const gUnknown_80FA004 = _("{POKEMON_0} went away...");
const u8 *const gUnknown_80FA030 = _("The Pokémon couldn't join the team...");
const u8 *const gUnknown_80FA058 = _("But it couldn't join the team.");
const u8 *const gUnknown_80FA090 = _("A new member joined the team!\nGive it a nickname?");
const u8 *const gUnknown_80FA0C8 = _("Please give your new team member\na proper nickname!");
const u8 *const gUnknown_80FA0F0 = _("{POKEMON_0} joined $t to\ngo on adventures!");
const u8 *const gUnknown_80FA120 = _("{POKEMON_0} gained access to\nthe Friend Area {FRIEND_AREA}.");
const u8 *const gUnknown_80FA124[] = {
    [0] = _("{POKEMON_0} was slowed!"),
    [1] = _("{POKEMON_0} returned to normal speed!"),
    [2] = _("{POKEMON_0}'s at double speed!"),
    [3] = _("{POKEMON_0}'s at triple speed!"),
    [4] = _("{POKEMON_0}'s at quadruple speed!"),
};

const u8 *const gUnknown_80FA260 = _("The Rescue Team Badge\nshone on {POKEMON_1}!\n{POKEMON_1} gained a magical power!\n{POKEMON_1}: Thank you!\nPlease come see me at the Pelipper\nPost Office later.\n{POKEMON_1} escaped from the dungeon!");
const u8 *const gUnknown_80FA2B0 = _("{POKEMON_1} happily accepted the item!\n\n\n{POKEMON_1}: Thank you!\n\n\n{POKEMON_1} left the dungeon!\n\n");
const u8 *const gUnknown_80FA2F0 = _("Yes! {POKEMON_1} was found!\nUse the Rescue Team Badge to save\n{POKEMON_1}?");
const u8 *const gUnknown_80FA32C = _("Yes! {POKEMON_1} was found!\nDeliver the requested item to\n{POKEMON_1}?");
const u8 *const gUnknown_80FA36C = _("A mission has been completed!\nWould you like to leave now?");
const u8 *const gUnknown_80FA370 = _("A mission has been completed!\nWould you like to leave now?");
const u8 *const gUnknown_80FA394 = _("Do you really want to leave?");
const u8 *const gUnknown_80FA3B8 = _("Continue with your adventure?");
const u8 *const gUnknown_80FA408 = _("You're holding a delivery item.\nReturn to the base without continuing?");
const u8 *const gUnknown_80FA448 = _("The {MOVE_ITEM_0} isn't in the Toolbox.\nIt couldn't be delivered.");
const u8 *const gUnknown_80FA464 = _("{POKEMON_1} can't talk now.");
const u8 *const gUnknown_80FA4D4 = _("Yes! {POKEMON_2} was successfully\nescorted!\n{POKEMON_2} is delighted!\n{POKEMON_2}: Thank you!\n\n\n{POKEMON_2}'s twosome left the dungeon!\n\n");
const u8 *const gUnknown_80FA4D8 = _("A mission has been completed!\nWould you like to leave now?");
const u8 *const gUnknown_80FA500 = _("{POKEMON_2} doesn't seem to be around.");
const u8 *const gUnknown_80FA52C = _("The mission can no longer be completed!");
const u8 *const gUnknown_80FA530 = _("{POKEMON_1} can't talk now.");
const u8 *const gUnknown_80FA54C = _("{POKEMON_2} can't talk now.");
const u8 *const gUnknown_80FA580 = _("Deoxys was a mirage!\nA set of stairs appeared!");
const u8 *const gUnknown_80FA5B4 = _("It's impossible to go down the stairs\nnow!");
const u8 *const gUnknown_80FA5B8 = _("");
const u8 *const gUnknown_80FA5F4 = _("No Pokémon will join the rescue team\nin this dungeon.");
const u8 *const gUnknown_80FA61C = _("There are no potential recruits.");
const u8 *const gUnknown_80FA638 = _("{POKEMON_0}'s Reflect faded.");
const u8 *const gUnknown_80FA658 = _("{POKEMON_0}'s Light Screen faded.");
const u8 *const gUnknown_80FA67C = _("{POKEMON_0}'s Counter effect faded.");
const u8 *const gUnknown_80FA69C = _("{POKEMON_0}'s Safeguard faded.");
const u8 *const gUnknown_80FA6BC = _("{POKEMON_0}'s Magic Coat faded.");
const u8 *const gUnknown_80FA6D4 = _("{POKEMON_0}'s Wish faded.");
const u8 *const gUnknown_80FA6E8 = _("{POKEMON_0} woke up!");
const u8 *const gUnknown_80FA708 = _("{POKEMON_0} is no longer sleepless!");
const u8 *const gUnknown_80FA70C = _("{POKEMON_0} woke up!");
const u8 *const gUnknown_80FA710 = _("{POKEMON_0} woke up!");
const u8 *const gUnknown_80FA734 = _("{POKEMON_0} got over its drowsiness!");
const u8 *const gUnknown_80FA758 = _("Water Sport's effect faded.");
const u8 *const gUnknown_80FA778 = _("Mud Sport's effect faded.");
const u8 *const gUnknown_80FA79C = _("{POKEMON_0}'s Leech Seed wore off.");
const u8 *const gUnknown_80FA7BC = _("{POKEMON_0} is no longer cursed!");
const u8 *const gUnknown_80FA7DC = _("{POKEMON_0}'s Snatch wore off!");
const u8 *const gUnknown_80FA800 = _("{POKEMON_0} recovered from confusion!");
const u8 *const gUnknown_80FA81C = _("{POKEMON_0} regained mobility!");
const u8 *const gUnknown_80FA820 = _("{POKEMON_0} regained mobility!");
const u8 *const gUnknown_80FA824 = _("{POKEMON_0} regained mobility!");
const u8 *const gUnknown_80FA844 = _("{POKEMON_0}'s Ingrain wore off!");
const u8 *const gUnknown_80FA868 = _("{POKEMON_0} recovered from paralysis!");
const u8 *const gUnknown_80FA888 = _("{POKEMON_0} recovered from a burn!");
const u8 *const gUnknown_80FA8A8 = _("{POKEMON_0} recovered from poison!");
const u8 *const gUnknown_80FA8BC = _("{POKEMON_0} thawed out!");
const u8 *const gUnknown_80FA8E0 = _("{POKEMON_0} lost its Sure Shot status!");
const u8 *const gUnknown_80FA90C = _("{POKEMON_0} recovered from its\nWhiffer status!");
const u8 *const gUnknown_80FA934 = _("{POKEMON_0}'s damage returned to normal!");
const u8 *const gUnknown_80FA95C = _("{POKEMON_0} lost its Focus Energy status!");
const u8 *const gUnknown_80FA97C = _("{POKEMON_0} is no longer cowering!");
const u8 *const gUnknown_80FA9A0 = _("The decoy Pokémon went away!");
const u8 *const gUnknown_80FA9C0 = _("{POKEMON_0}'s Protect wore off!");
const u8 *const gUnknown_80FA9DC = _("{POKEMON_0}'s Taunt wore off!");
const u8 *const gUnknown_80FA9F4 = _("{POKEMON_0} became visible!");
const u8 *const gUnknown_80FAA0C = _("{POKEMON_0} regained sight!");
const u8 *const gUnknown_80FAA2C = _("{POKEMON_0} can see normally again!");
const u8 *const gUnknown_80FAA48 = _("{POKEMON_0} returned to normal!");
const u8 *const gUnknown_80FAA68 = _("{POKEMON_0}'s Mirror Coat faded!");
const u8 *const gUnknown_80FAA8C = _("{POKEMON_0} gave up on Destiny Bond!");
const u8 *const gUnknown_80FAAAC = _("{POKEMON_0} recovered from Encore!");
const u8 *const gPtrMonStoppedEnduringMessage = _("{POKEMON_0} stopped enduring!");
const u8 *const gPtrMonMirrorMoveFadedMessage = _("{POKEMON_0}'s Mirror Move faded!");
const u8 *const gPtrMonConversion2FailedMessage = _("{POKEMON_0}'s Conversion 2 faded!");
const u8 *const gPtrMonGaveUpVitalThrowMessage = _("{POKEMON_0} gave up on Vital Throw!");
const u8 *const gUnknown_80FAB40 = _("{POKEMON_0}'s Mist faded!");
const u8 *const gUnknown_80FAB6C = _("{POKEMON_0}'s appearance returned to\nnormal!");
const u8 *const gUnknown_80FAB90 = _("{POKEMON_0} got over its infatuation!");
const u8 *const gUnknown_80FABBC = _("{POKEMON_0} can't go through walls\nanymore!");
const u8 *const gUnknown_80FABC0 = _("{POKEMON_0} returned to normal!");
const u8 *const gUnknown_80FABD8 = _("{POKEMON_0}'s rage faded!");
const u8 *const gPtrMonNoLongerPetrifiedMessage = _("{POKEMON_0} is no longer petrified!");
const u8 *const gPtrMonNoLongerCringingMessage = _("{POKEMON_0} is no longer cringing!");
const u8 *const gUnknown_80FAC38 = _("{POKEMON_0} is no longer paused!");
const u8 *const gUnknown_80FAC54 = _("{POKEMON_0} readies Razor Wind!");
const u8 *const gUnknown_80FAC74 = _("{POKEMON_0} began storing energy!");
const u8 *const gUnknown_80FAC88 = _("{POKEMON_0} is enraged!");
const u8 *const gUnknown_80FACA4 = _("{POKEMON_0} is focusing energy!");
const u8 *const gUnknown_80FACC4 = _("{POKEMON_0} is readying Sky Attack!");
const u8 *const gUnknown_80FACE4 = _("{POKEMON_0} is readying Solarbeam!");
const u8 *const gUnknown_80FACFC = _("{POKEMON_0} flew up high!");
const u8 *const gUnknown_80FAD10 = _("{POKEMON_0} bounced up!");
const u8 *const gUnknown_80FAD2C = _("{POKEMON_0} dove underwater!");
const u8 *const gUnknown_80FAD4C = _("{POKEMON_0} burrowed underground!");
const u8 *const gUnknown_80FAD6C = _("{POKEMON_0} began charging power!");
const u8 *const gUnknown_80FAD8C = _("Mud Sport came into effect!");
const u8 *const gUnknown_80FADB0 = _("Water Sport came into effect!");
const u8 *const gUnknown_80FADD8 = _("{POKEMON_1} used Flash Fire to absorb\nfire!");
const u8 *const gUnknown_80FAE00 = _("Fire moves won't become stronger!");
const u8 *const gUnknown_80FAE1C = _("{POKEMON_0} began using Wish!");
const u8 *const gUnknown_80FAE3C = _("{POKEMON_0} is already using Wish.");
const u8 *const gUnknown_80FAE58 = _("{POKEMON_0} took a leech seed!");
const u8 *const gUnknown_80FAE7C = _("{POKEMON_0} already has a leech seed!");
const u8 *const gUnknown_80FAEA0 = _("Item locations became evident!");
const u8 *const gUnknown_80FAEC8 = _("The stair location became clear!");
const u8 *const gUnknown_80FAEF0 = _("Item locations are already known.");
const u8 *const gUnknown_80FAF1C = _("The stair location is already known.");
const u8 *const gUnknown_80FAF3C = _("There are no stairs here.");
const u8 *const gUnknown_80FAF5C = _("{POKEMON_0} put up its magic coat!");
const u8 *const gUnknown_80FAF8C = _("{POKEMON_0} is already cloaked in its\nmagic coat!");
const u8 *const gUnknown_80FAFAC = _("{POKEMON_0} can locate foes now!");
const u8 *const gUnknown_80FAFD0 = _("Foes can already be located!");
const u8 *const gUnknown_80FAFF0 = _("{POKEMON_0} readies its Skull Bash!");
const u8 *const gUnknown_80FB004 = _("{POKEMON_0} was cursed!");
const u8 *const gUnknown_80FB01C = _("{POKEMON_0} readied Snatch!");
const u8 *const gUnknown_80FB048 = _("{POKEMON_0} gained the protection\nof Safeguard!");
const u8 *const gUnknown_80FB074 = _("{POKEMON_0} is already protected\nby Safeguard.");
const u8 *const gUnknown_80FB09C = _("{POKEMON_0} gained the protection\nof Mist!");
const u8 *const gUnknown_80FB0C4 = _("{POKEMON_0} is already protected\nby Mist.");
const u8 *const gUnknown_80FB0E0 = _("{POKEMON_0} is set to counter!");
const u8 *const gUnknown_80FB10C = _("{POKEMON_0} has been waiting to\ncounterattack!");
const u8 *const gUnknown_80FB130 = _("{POKEMON_0} put up its light screen!");
const u8 *const gUnknown_80FB160 = _("{POKEMON_0} is already protected\nby Light Screen.");
const u8 *const gUnknown_80FB17C = _("{POKEMON_0} put up its reflect!");
const u8 *const gUnknown_80FB1A8 = _("{POKEMON_0} is already protected by\nReflect.");
const u8 *const gUnknown_80FB1C4 = _("{POKEMON_0} recovered {VALUE_0} HP!");
const u8 *const gUnknown_80FB1E0 = _("{POKEMON_0} was fully healed!");
const u8 *const gUnknown_80FB204 = _("{POKEMON_0}'s HP remained unchanged.");
const u8 *const gUnknown_80FB21C = _("{POKEMON_0} has full HP.");
const u8 *const gUnknown_80FB240 = _("{POKEMON_0}'s max. HP rose by {VALUE_1}.");
const u8 *const gUnknown_80FB25C = _("{POKEMON_0} became confused!");
const u8 *const gUnknown_80FB27C = _("{POKEMON_0} is already confused!");
const u8 *const gUnknown_80FB2AC = _("{POKEMON_0} became paralyzed!\nIt can't attack!");
const u8 *const gUnknown_80FB2CC = _("{POKEMON_0} is already paralyzed!");
const u8 *const gUnknown_80FB2E0 = _("{POKEMON_0} cringed!");
const u8 *const gUnknown_80FB300 = _("{POKEMON_0} is already cringing!");
const u8 *const gUnknown_80FB318 = _("{POKEMON_0} fell asleep!");
const u8 *const gUnknown_80FB31C = _("{POKEMON_0} fell asleep!");
const u8 *const gUnknown_80FB338 = _("{POKEMON_0} is already asleep!");
const u8 *const gUnknown_80FB35C = _("{POKEMON_0} is locked in a nightmare!");
const u8 *const gUnknown_80FB360 = _("{POKEMON_0} is already asleep!");
const u8 *const gUnknown_80FB380 = _("{POKEMON_0} didn't become drowsy!");
const u8 *const gUnknown_80FB384 = _("{POKEMON_0} is already asleep!");
const u8 *const gUnknown_80FB388 = _("{POKEMON_0} didn't become drowsy!");
const u8 *const gUnknown_80FB3A4 = _("{POKEMON_0} had a nightmare!");
const u8 *const gUnknown_80FB3CC = _("{POKEMON_0} is already having\na nightmare!");
const u8 *const gUnknown_80FB3D0 = _("{POKEMON_0} didn't become drowsy!");
const u8 *const gUnknown_80FB3E0 = _("{POKEMON_0} yawned!");
const u8 *const gUnknown_80FB3F8 = _("{POKEMON_0} didn't yawn!");
const u8 *const gUnknown_80FB414 = _("{POKEMON_0} is already yawning!");
const u8 *const gUnknown_80FB418 = _("{POKEMON_0} is already asleep!");
const u8 *const gUnknown_80FB41C = _("{POKEMON_0} woke up!");
const u8 *const gUnknown_80FB43C = _("{POKEMON_0} is already sleepless!");
const u8 *const gUnknown_80FB458 = _("{POKEMON_0} became sleepless!");
const u8 *const gUnknown_80FB480 = _("{POKEMON_0} can't move on the next turn!");
const u8 *const gUnknown_80FB4B0 = _("{POKEMON_0} already can't move on\nthe next turn!");
const u8 *const gUnknown_80FB4D4 = _("{POKEMON_0} can't move for a while!");
const u8 *const gUnknown_80FB4F0 = _("{POKEMON_0} is already paused!");
const u8 *const gUnknown_80FB50C = _("{POKEMON_0} became infatuated!");
const u8 *const gUnknown_80FB52C = _("{POKEMON_0} is already infatuated!");
const u8 *const gUnknown_80FB548 = _("{POKEMON_0} sustained a burn!");
const u8 *const gUnknown_80FB564 = _("{POKEMON_0} already has a burn!");
const u8 *const gUnknown_80FB580 = _("But nothing happened.");
const u8 *const gUnknown_80FB598 = _("{POKEMON_0} was poisoned!");
const u8 *const gUnknown_80FB5B4 = _("{POKEMON_0} was badly poisoned!");
const u8 *const gUnknown_80FB5D4 = _("{POKEMON_0} is already poisoned!");
const u8 *const gUnknown_80FB5F8 = _("{POKEMON_0} is already badly poisoned!");
const u8 *const gUnknown_80FB610 = _("{POKEMON_0} became frozen!");
const u8 *const gUnknown_80FB628 = _("{POKEMON_0} was squeezed!");
const u8 *const gUnknown_80FB64C = _("{POKEMON_0} is already being squeezed!");
const u8 *const gUnknown_80FB668 = _("{POKEMON_0} became immobilized!");
const u8 *const gUnknown_80FB688 = _("{POKEMON_0} is already immobilized!");
const u8 *const gUnknown_80FB6A4 = _("{POKEMON_0} put down its roots!");
const u8 *const gUnknown_80FB6C0 = _("{POKEMON_0} is already rooted!");
const u8 *const gUnknown_80FB6D8 = _("{POKEMON_0} became wrapped!");
const u8 *const gUnknown_80FB6FC = _("{POKEMON_0} has a foe wrapped already!");
const u8 *const gUnknown_80FB718 = _("{POKEMON_0} is already wrapped!");
const u8 *const gUnknown_80FB73C = _("{POKEMON_0} attained Sure Shot status!");
const u8 *const gUnknown_80FB764 = _("{POKEMON_0} already has Sure Shot\nstatus!");
const u8 *const gUnknown_80FB780 = _("{POKEMON_0} became a whiffer!");
const u8 *const gUnknown_80FB7A0 = _("{POKEMON_0} is already a whiffer!");
const u8 *const gUnknown_80FB7BC = _("{POKEMON_0} became petrified!");
const u8 *const gUnknown_80FB7DC = _("{POKEMON_0} is already petrified!");
const u8 *const gUnknown_80FB7F4 = _("{POKEMON_0} was blinded!");
const u8 *const gUnknown_80FB810 = _("{POKEMON_0} is already blinded!");
const u8 *const gUnknown_80FB834 = _("{POKEMON_0}'s vision turned weird!");
const u8 *const gUnknown_80FB85C = _("{POKEMON_0}'s vision is already weird!");
const u8 *const gUnknown_80FB880 = _("{POKEMON_0}'s vision was restored!");
const u8 *const gUnknown_80FB89C = _("{POKEMON_0}'s vision is fine!");
const u8 *const gUnknown_80FB8BC = _("{POKEMON_0}'s damage was fixed!");
const u8 *const gUnknown_80FB8E4 = _("{POKEMON_0}'s damage is already fixed!");
const u8 *const gUnknown_80FB900 = _("{POKEMON_0} is getting pumped!");
const u8 *const gUnknown_80FB924 = _("{POKEMON_0} is already getting pumped!");
const u8 *const gUnknown_80FB940 = _("{POKEMON_0} cowered in fear!");
const u8 *const gUnknown_80FB960 = _("{POKEMON_0} is already cowering!");
const u8 *const gUnknown_80FB978 = _("{POKEMON_0} became a decoy!");
const u8 *const gUnknown_80FB994 = _("{POKEMON_0} is already a decoy!");
const u8 *const gUnknown_80FB9B0 = _("{POKEMON_0} protected itself!");
const u8 *const gUnknown_80FB9D8 = _("{POKEMON_0} is already protecting itself!");
const u8 *const gUnknown_80FB9F0 = _("{POKEMON_0} was taunted!");
const u8 *const gUnknown_80FBA14 = _("{POKEMON_0} has been taunted already!");
const u8 *const gUnknown_80FBA38 = _("{POKEMON_0} stored power {VALUE_0} time(s)!");
const u8 *const gUnknown_80FBA60 = _("{POKEMON_0} can't store any more power!");
const u8 *const gUnknown_80FBA80 = _("{POKEMON_0} disappeared from view!");
const u8 *const gUnknown_80FBAA0 = _("{POKEMON_0} is invisible already!");
const u8 *const gUnknown_80FBAC0 = _("{POKEMON_0} put up its mirror coat!");
const u8 *const gUnknown_80FBAE4 = _("{POKEMON_0} already has a mirror coat!");
const u8 *const gUnknown_80FBB04 = _("{POKEMON_0} heard the perish song!");
const u8 *const gUnknown_80FBB28 = _("{POKEMON_0} already heard that song!");
const u8 *const gUnknown_80FBB4C = _("{POKEMON_0} readied its Destiny Bond!");
const u8 *const gUnknown_80FBB78 = _("{POKEMON_0} already has Destiny Bond\nreadied!");
const u8 *const gUnknown_80FBB94 = _("{POKEMON_0} earned an encore!");
const u8 *const gUnknown_80FBBB8 = _("{POKEMON_0} is already doing encores!");
const u8 *const gUnknown_80FBBD4 = _("{POKEMON_0} won't do encores!");
const u8 *const gUnknown_80FBBF0 = _("{POKEMON_0} is set to endure!");
const u8 *const gUnknown_80FBC14 = _("{POKEMON_0} is already set to endure!");
const u8 *const gUnknown_80FBC38 = _("{POKEMON_0} readied its Mirror Move!");
const u8 *const gUnknown_80FBC5C = _("{POKEMON_0} already used Mirror Move!");
const u8 *const gUnknown_80FBC7C = _("{POKEMON_0} has Conversion 2 up!");
const u8 *const gUnknown_80FBCA4 = _("{POKEMON_0} already has Conversion 2 up!");
const u8 *const gUnknown_80FBCC8 = _("{POKEMON_0} readied its Vital Throw!");
const u8 *const gUnknown_80FBCF0 = _("{POKEMON_0} is already set for\nVital Throw!");
const u8 *const gUnknown_80FBD18 = _("{POKEMON_0}'s stats returned to normal.");
const u8 *const gUnknown_80FBD3C = _("{POKEMON_0}'s stats appear unchanged.");
const u8 *const gUnknown_80FBD58 = _("It psyched itself up!");
const u8 *const gUnknown_80FBD78 = _("{POKEMON_0}'s Belly went down.");
const u8 *const gUnknown_80FBD9C = _("{POKEMON_0}'s max. Belly size shrank!");
const u8 *const gUnknown_80FBDC4 = _("{POKEMON_0}'s max. Belly size increased!");
const u8 *const gUnknown_80FBDF0 = _("{POKEMON_0}'s Belly won't get any bigger!");
const u8 *const gUnknown_80FBE14 = _("{POKEMON_0}'s Belly didn't change!");
const u8 *const gUnknown_80FBE3C = _("{POKEMON_0}'s Belly size didn't change!");
const u8 *const gUnknown_80FBE40 = _("{POKEMON_0}'s Belly didn't change!");
const u8 *const gUnknown_80FBE64 = _("{POKEMON_0}'s Belly filled up full!");
const u8 *const gUnknown_80FBE84 = _("{POKEMON_0}'s Belly was filled!");
const u8 *const gUnknown_80FBEA0 = _("{POKEMON_0}'s Belly dropped!");
const u8 *const gUnknown_80FBEC0 = _("{POKEMON_0} transformed into\n{POKEMON_1}!");
const u8 *const gUnknown_80FBEE4 = _("{POKEMON_0}'s transformation failed!");
const u8 *const gUnknown_80FBF04 = _("{POKEMON_0} is already transformed.");
const u8 *const gUnknown_80FBF28 = _("{POKEMON_0} can go through walls now!");
const u8 *const gUnknown_80FBF50 = _("{POKEMON_0} can already go through walls!");
const u8 *const gUnknown_80FBF68 = _("{POKEMON_0} became muzzled!");
const u8 *const gUnknown_80FBF84 = _("{POKEMON_0} is already muzzled!");
const u8 *const gUnknown_80FBF9C = _("{POKEMON_0} was exposed!");
const u8 *const gUnknown_80FBFB8 = _("{POKEMON_0} is already exposed!");
const u8 *const gUnknown_80FBFD8 = _("{POKEMON_0} isn't a Ghost type!");
const u8 *const gUnknown_80FC000 = _("{POKEMON_0}'s Evasion returned to normal!");
const u8 *const gUnknown_80FC028 = _("Item holders are now identified!");
const u8 *const gUnknown_80FC054 = _("It can already identify item holders.");
const u8 *const gUnknown_80FC074 = _("{POKEMON_0} is already in a rage!");
const u8 *const gUnknown_80FC084 = _("Accuracy");
const u8 *const gUnknown_80FC090 = _("Evasion");
const u8 *const gUnknown_80FC09C = _("Defense");
const u8 *const gUnknown_80FC0AC = _("Sp. Def.");
const u8 *const gUnknown_80FC0B8 = _("Attack");
const u8 *const gUnknown_80FC0C8 = _("Sp. Atk.");
const u8 *const gUnknown_80FC0D4 = _("sharply");
const u8 *const gUnknown_80FC0E4 = _("slightly");
const u8 *const gUnknown_80FC0FC = _("{POKEMON_0}'s {MOVE_ITEM_0} rose!");
const u8 *const gUnknown_80FC114 = _("{POKEMON_0}'s {MOVE_ITEM_0} fell!");
const u8 *const gUnknown_80FC118 = _("{POKEMON_0}'s {MOVE_ITEM_0} rose!");
const u8 *const gUnknown_80FC11C = _("{POKEMON_0}'s {MOVE_ITEM_0} fell!");
const u8 *const gUnknown_80FC138 = _("{POKEMON_0}'s {MOVE_ITEM_0} rose\n{MOVE_ITEM_1}!");
const u8 *const gUnknown_80FC13C = _("{POKEMON_0}'s {MOVE_ITEM_0} rose\n{MOVE_ITEM_1}!");
const u8 *const gUnknown_80FC158 = _("{POKEMON_0}'s {MOVE_ITEM_0} fell\n{MOVE_ITEM_1}!");
const u8 *const gUnknown_80FC15C = _("{POKEMON_0}'s {MOVE_ITEM_0} fell\n{MOVE_ITEM_1}!");
const u8 *const gUnknown_80FC180 = _("{POKEMON_0}'s {MOVE_ITEM_0} remained\nunchanged!");
const u8 *const gUnknown_80FC184 = _("{POKEMON_0}'s {MOVE_ITEM_0} remained\nunchanged!");
const u8 *const gUnknown_80FC1A4 = _("{POKEMON_0}'s {MOVE_ITEM_0} fell\nslightly!");
const u8 *const gUnknown_80FC1C4 = _("{POKEMON_0}'s {MOVE_ITEM_0} rose\nslightly!");
const u8 *const gUnknown_80FC1F0 = _("{POKEMON_0}'s {MOVE_ITEM_0} won't\ngo down any more!");
const u8 *const gUnknown_80FC218 = _("{POKEMON_0}'s {MOVE_ITEM_0} won't\ngo up any more!");
const u8 *const gUnknown_80FC21C = _("{POKEMON_0}'s {MOVE_ITEM_0} won't\ngo up any more!");
const u8 *const gUnknown_80FC248 = _("{POKEMON_0}'s {MOVE_ITEM_0} won't\ngo down any more.");
const u8 *const gUnknown_80FC270 = _("{POKEMON_0}'s {MOVE_ITEM_0} won't\ngo up any more.");
const u8 *const gUnknown_80FC274 = _("{POKEMON_0}'s {MOVE_ITEM_0} won't\ngo down any more.");
const u8 *const gUnknown_80FC298 = _("{POKEMON_0}'s speed didn't change!");
const u8 *const gUnknown_80FC2B8 = _("{POKEMON_0} can't go any faster!");
const u8 *const gUnknown_80FC2D8 = _("{POKEMON_0} can't go any slower!");
const u8 *const gUnknown_80FC2FC = _("{POKEMON_0} is protected by Safeguard!");
const u8 *const gUnknown_80FC31C = _("{POKEMON_0} is protected by Mist!");
const u8 *const gUnknown_80FC33C = _("{POKEMON_0}'s Attack was boosted.");
const u8 *const gUnknown_80FC360 = _("{POKEMON_0}'s Attack didn't go up.");
const u8 *const gUnknown_80FC388 = _("{POKEMON_0}'s Special Attack was boosted.");
const u8 *const gUnknown_80FC3B4 = _("{POKEMON_0}'s Special Attack didn't go up.");
const u8 *const gUnknown_80FC3D8 = _("{POKEMON_0}'s Defense was boosted.");
const u8 *const gUnknown_80FC3FC = _("{POKEMON_0}'s Defense didn't go up.");
const u8 *const gUnknown_80FC428 = _("{POKEMON_0}'s Special Defense was\nboosted.");
const u8 *const gUnknown_80FC454 = _("{POKEMON_0}'s Special Defense didn't\ngo up.");
const u8 *const gUnknown_80FC458 = _("{POKEMON_0}'s Attack was weakened.");
const u8 *const gUnknown_80FC47C = _("{POKEMON_0}'s Attack didn't go down.");
const u8 *const gUnknown_80FC4A4 = _("{POKEMON_0}'s Special Attack was\nweakened.");
const u8 *const gUnknown_80FC4D0 = _("{POKEMON_0}'s Special Attack didn't go\ndown.");
const u8 *const gUnknown_80FC52C = _("The target's Magic Coat bounced it back!");
const u8 *const gUnknown_80FC558 = _("The target's Mirror Move returned it!");
const u8 *const gUnknown_80FC574 = _("{POKEMON_1} protected itself!");
const u8 *const gUnknown_80FC584 = _("{POKEMON_0} warped!");
const u8 *const gUnknown_80FC5A8 = _("A trap can't be laid here.");
const u8 *const gUnknown_80FC5CC = _("{POKEMON_0} was too hungry to use it!");
const u8 *const gUnknown_80FC5E0 = _("Weather: {POKEMON_0}");
const u8 *const gUnknown_80FC5F8 = _("A trap was laid!");
const u8 *const gUnknown_80FC5FC = _("A trap can't be laid here.");
const u8 *const gUnknown_80FC614 = _("Got {POKEMON_1}'s item!");
const u8 *const gUnknown_80FC654 = _("{POKEMON_0} has an item already.\nIt couldn't get another item.");
const u8 *const gUnknown_80FC678 = _("{POKEMON_1} doesn't have anything!");
const u8 *const gUnknown_80FC690 = _("The move failed!");
const u8 *const gUnknown_80FC6A4 = _("The Orb failed!");
const u8 *const gUnknown_80FC6A8 = _("{POKEMON_0} is paralyzed!");
const u8 *const gUnknown_80FC6D0 = _("But the move couldn't be used!");
const u8 *const gUnknown_80FC6FC = _("But Orbs are prevented from being used!");
const u8 *const gUnknown_80FC710 = _("{POKEMON_0} is muzzled!");
const u8 *const gUnknown_80FC714 = _("{POKEMON_0} is cringing!");
const u8 *const gUnknown_80FC718 = _("{POKEMON_0} is infatuated!");
const u8 *const gUnknown_80FC72C = _("{POKEMON_0} loosed {MOVE_ITEM_0}!");
const u8 *const gUnknown_80FC730 = _("But nothing happened.");
const u8 *const gUnknown_80FC734 = _("But nothing happened.");
const u8 *const gUnknown_80FC74C = _("Nothing happened.");
const u8 *const gUnknown_80FC770 = _("But no power had been stored!");
const u8 *const gUnknown_80FC790 = _("{POKEMON_0} traded items with\n{POKEMON_1}!");
const u8 *const gUnknown_80FC7AC = _("The item trade failed!");
const u8 *const gUnknown_80FC7C8 = _("{POKEMON_0}'s move missed!");
const u8 *const gUnknown_80FC7EC = _("{POKEMON_0} and {POKEMON_1} shared\ntheir HP!");
const u8 *const gUnknown_80FC81C = _("{POKEMON_0} copied the target's\nspecial ability!");
const u8 *const gUnknown_80FC854 = _("{POKEMON_0} couldn't copy the target's\nWonder Guard!");
const u8 *const gUnknown_80FC888 = _("{POKEMON_0} swapped special abilities\nwith the target!");
const u8 *const gUnknown_80FC8C0 = _("{POKEMON_0} couldn't swap the target's\nWonder Guard!");
const u8 *const gUnknown_80FC8F0 = _("All sticky, gummed-up items were cleaned!");
const u8 *const gUnknown_80FC920 = _("There were no sticky, gummed-up items.");
const u8 *const gUnknown_80FC924 = _("The target is a Ground type!\nMud-Slap didn't work!");
const u8 *const gUnknown_80FC97C = _("There's nowhere to warp!");
const u8 *const gUnknown_80FC9A0 = _("It's already on the stairs.");
const u8 *const gUnknown_80FC9C0 = _("It couldn't make a leap!");
const u8 *const gUnknown_80FC9E8 = _("It couldn't be knocked flying!");
const u8 *const gUnknown_80FCA10 = _("{POKEMON_0} couldn't be knocked flying!");
const u8 *const gUnknown_80FCA3C = _("It had no power stockpiled to spit up!");
const u8 *const gUnknown_80FCA60 = _("{POKEMON_0}'s {MOVE_ITEM_0} didn't\ngo down!");
const u8 *const gUnknown_80FCA64 = _("{POKEMON_0}'s {MOVE_ITEM_0} didn't\ngo down!");
const u8 *const gUnknown_80FCA90 = _("{POKEMON_1} is sturdy!\nIt withstood the move!");
const u8 *const gUnknown_80FCAC0 = _("{POKEMON_0} is anchored!\nIt won't switch places!");
const u8 *const gUnknown_80FCAE8 = _("{POKEMON_0} is anchored!\nIt won't warp!");
const u8 *const gUnknown_80FCB14 = _("But it dropped back at the same spot!");
const u8 *const gUnknown_80FCB40 = _("{POKEMON_0} is anchored!\nIt can't be thrown!");
const u8 *const gUnknown_80FCB70 = _("{POKEMON_0} couldn't be thrown for\nsome reason!");
const u8 *const gUnknown_80FCB98 = _("{POKEMON_0} is anchored!\nIt can't leap!");
const u8 *const gUnknown_80FCBCC = _("{POKEMON_0} is anchored!\nIt can't be knocked flying!");
const u8 *const gUnknown_80FCBF8 = _("{POKEMON_0} is limber!\nIt can't be paralyzed!");
const u8 *const gUnknown_80FCC18 = _("But {POKEMON_0} didn't cringe!");
const u8 *const gUnknown_80FCC4C = _("{POKEMON_0} is oblivious!\nIt doesn't get infatuated!");
const u8 *const gUnknown_80FCC7C = _("{POKEMON_0} traced the target's\nspecial ability!");
const u8 *const gUnknown_80FCCAC = _("{POKEMON_0}'s Color Change made it\nthe {MOVE_ITEM_0} type!");
const u8 *const gUnknown_80FCCB0 = _("");
const u8 *const gUnknown_80FCCE4 = _("But the target's item couldn't be taken!");
const u8 *const gUnknown_80FCCE8 = _("But the target's item couldn't be taken!");
const u8 *const gUnknown_80FCD0C = _("A Lightningrod took the move!");
const u8 *const gUnknown_80FCD28 = _("The move was snatched!");
const u8 *const gUnknown_80FCD54 = _("{POKEMON_0}'s Insomnia prevents\ndrowsiness!");
const u8 *const gUnknown_80FCD58 = _("{POKEMON_0}'s Insomnia prevents\ndrowsiness!");
const u8 *const gUnknown_80FCD88 = _("{POKEMON_0}'s Vital Spirit prevents\ndrowsiness!");
const u8 *const gUnknown_80FCDB4 = _("{POKEMON_0}'s Own Tempo prevents\nconfusion!");
const u8 *const gUnknown_80FCDE0 = _("{POKEMON_0}'s Magma Armor prevents\nfreezing!");
const u8 *const gUnknown_80FCE00 = _("{POKEMON_0} is an unfreezable type!");
const u8 *const gUnknown_80FCE34 = _("The magma's heat prevents {POKEMON_0}\nfrom freezing!");
const u8 *const gUnknown_80FCE5C = _("{POKEMON_0}'s Water Veil prevents burns!");
const u8 *const gUnknown_80FCE84 = _("{POKEMON_0}'s type doesn't get burns!");
const u8 *const gUnknown_80FCEB0 = _("{POKEMON_0}'s Immunity prevents\npoisoning!");
const u8 *const gUnknown_80FCEDC = _("{POKEMON_0}'s type doesn't get poisoned!");
const u8 *const gUnknown_80FCEFC = _("It had no effect on {POKEMON_0}!");
const u8 *const gUnknown_80FCF18 = _("Yes! {POKEMON_0} leveled up!");
const u8 *const gUnknown_80FCF38 = _("{POKEMON_0} uttered its sleep talk!");
const u8 *const gUnknown_80FCF50 = _("{POKEMON_0} loosed a snore!");
const u8 *const gUnknown_80FCF74 = _("The weather remained unchanged!");
const u8 *const gUnknown_80FCF78 = _("The weather remained unchanged!");
const u8 *const gUnknown_80FCF7C = _("The weather remained unchanged!");
const u8 *const gUnknown_80FCF80 = _("The weather remained unchanged!");
const u8 *const gUnknown_80FCFA4 = _("Its power was rebounded back!");
const u8 *const gUnknown_80FCFBC = _("{MOVE_ITEM_0} was tormented!");
const u8 *const gUnknown_80FCFE4 = _("The target couldn't be tormented!");
const u8 *const gUnknown_80FD018 = _("The target's HP can't be halved anymore!");
const u8 *const gUnknown_80FD040 = _("It became brighter on the floor!");
const u8 *const gUnknown_80FD05C = _("The floor was drained!");
const u8 *const gUnknown_80FD060 = _("But nothing happened.");
const u8 *const gUnknown_80FD08C = _("There is too much water to be drained!");
const u8 *const gUnknown_80FD0B4 = _("It filled in the ground in front!");
const u8 *const gUnknown_80FD0B8 = _("But nothing happened.");
const u8 *const gUnknown_80FD0BC = _("The stairs were located!");
const u8 *const gUnknown_80FD0DC = _("");
const u8 *const gUnknown_80FD0E0 = _("");
const u8 *const gUnknown_80FD0E4 = _("");
const u8 *const gUnknown_80FD104 = _("The barrier was shattered!");
const u8 *const gUnknown_80FD128 = _("It can only be used on water!");
const u8 *const gUnknown_80FD14C = _("It can only be used on land!");
const u8 *const gUnknown_80FD170 = _("{POKEMON_1}'s item was swatted down!");
const u8 *const gUnknown_80FD18C = _("The target has no item!");
const u8 *const gUnknown_80FD1B0 = _("Nearby traps were destroyed!");
const u8 *const gUnknown_80FD1CC = _("There were no traps.");
const u8 *const gUnknown_80FD1EC = _("It can't be used here.");
const u8 *const gUnknown_80FD20C = _("{POKEMON_1} can throw a long way!");
const u8 *const gUnknown_80FD22C = _("{POKEMON_1} can throw far already!");
const u8 *const gUnknown_80FD254 = _("{POKEMON_1}'s throws can pierce things!");
const u8 *const gUnknown_80FD27C = _("{POKEMON_1}'s throws can pierce already!");
const u8 *const gUnknown_80FD294 = _("{POKEMON_1} bears a grudge!");
const u8 *const gUnknown_80FD2B4 = _("{POKEMON_1} already bears a grudge!");
const u8 *const gUnknown_80FD2CC = _("It's a grudge!");
const u8 *const gUnknown_80FD2DC = _("Assist: {MOVE_ITEM_0}");
const u8 *const gUnknown_80FD2F8 = _("All traps were exposed!");
const u8 *const gUnknown_80FD320 = _("There appear to be no hidden traps.");
const u8 *const gUnknown_80FD350 = _("The last move used by {POKEMON_1} lost\nall its PP!");
const u8 *const gUnknown_80FD370 = _("Nothing happened to {POKEMON_1}.");
const u8 *const gUnknown_80FD3A0 = _("The walls crumbled, making one big room!");
const u8 *const gUnknown_80FD3C8 = _("This floor is already one big room!");
const u8 *const gUnknown_80FD3CC = _("It can't be used here.");
const u8 *const gUnknown_80FD3D0 = _("It can't be used here.");
const u8 *const gUnknown_80FD3F0 = _("It dug the wall in front!");
const u8 *const gUnknown_80FD40C = _("Can't use that here!");
const u8 *const gUnknown_80FD430 = _("Can't use that diagonally!");
const u8 *const gUnknown_80FD434 = _("{POKEMON_0} transformed into\n{POKEMON_1}!");
const u8 *const gUnknown_80FD450 = _("{POKEMON_0} can't transform!");
const u8 *const gUnknown_80FD454 = _("But nothing happened.");
const u8 *const gUnknown_80FD46C = _("{POKEMON_1} was revived!");
const u8 *const gUnknown_80FD484 = _("{POKEMON_0} possessed {POKEMON_1}!");
const u8 *const gUnknown_80FD4B0 = _("The target's stench is overwhelming!");
const u8 *const gUnknown_80FD4C4 = _("{POKEMON_0} escaped!");
const u8 *const gUnknown_80FD4DC = _("{POKEMON_0} can't escape!");
const u8 *const gUnknown_80FD500 = _("{POKEMON_0} was protected by its Band!");
const u8 *const gUnknown_80FD524 = _("{POKEMON_0} was protected by its Scarf!");
const u8 *const gUnknown_80FD548 = _("{POKEMON_0} was protected by its Scope!");
const u8 *const gUnknown_80FD54C = _("{POKEMON_0} was protected by its Scope!");
const u8 *const gUnknown_80FD550 = _("{POKEMON_0} was protected by its Band!");
const u8 *const gUnknown_80FD574 = _("{POKEMON_1} was protected by its Specs!");
const u8 *const gUnknown_80FD578 = _("{POKEMON_1} was protected by its Specs!");
const u8 *const gUnknown_80FD57C = _("{POKEMON_1} was protected by its Specs!");
const u8 *const gUnknown_80FD594 = _("Getting hungry...");
const u8 *const gUnknown_80FD5B8 = _("Getting dizzy from hunger...");
const u8 *const gUnknown_80FD5DC = _("Oh, no! Your Belly's empty!");
const u8 *const gUnknown_80FD608 = _("Hurry! You've got to eat something!");
const u8 *const gUnknown_80FD628 = _("You'll faint from hunger!");
const u8 *const gUnknown_80FD644 = _("Its IQ didn't change.");
const u8 *const gUnknown_80FD648[] = {
    [0] = _("It seems to love this Gummi!"),
    [1] = _("It seems to like this Gummi!"),
    [2] = _("It doesn't seem to dislike this Gummi."),
    [3] = _("It seemed to be somewhat satisfied."),
};

const u8 *const gUnknown_80FD6E8[] = {
    [0] = _("IQ rose sharply!"),
    [1] = _("IQ went up significantly!"),
    [2] = _("IQ went up somewhat!"),
    [3] = _("IQ went up slightly!"),
    [4] = _("IQ didn't change."),
};

const u8 *const gUnknown_80FD788 = _("A food item went bad.");
const u8 *const gUnknown_80FD7AC = _("Several food items went bad.");
const u8 *const gUnknown_80FD7D4 = _("Nothing particularly bad happened.");
const u8 *const gUnknown_80FD7F4 = _("Stepped on something weird!");
const u8 *const gSteppedOnTrapStrings[NUM_TRAPS] = {
    [0] = _("There was a {POKEMON_0} underfoot!"),
    [1] = _("Mud splashed up from the {POKEMON_0}!"),
    [2] = _("Stepped on a Sticky Trap!"),
    [3] = _("Sludge splashed up from the ground!"),
    [4] = _("A sweet, Pokémon-attracting aroma\nspread!"),
    [5] = _("{POKEMON_0}!"),
    [6] = _("Stepped on a {POKEMON_0}!"),
    [7] = _("A sudden gust blew!"),
    [8] = _("The trap spun around!"),
    [9] = _("Sleeping gas erupted!"),
    [10] = _("Stepped on a Slow Trap!"),
    [11] = _("Stepped on a Seal Trap!"),
    [12] = _("Poison spikes shot out!"),
    [13] = _("Stepped on a Selfdestruct Trap!"),
    [14] = _("Stepped on an Explosion Trap!"),
    [15] = _("Stepped on a PP-Zero Trap!"),
    [16] = _("Stepped on a Chestnut Trap!"),
    [17] = _("Stepped on a Wonder Tile!"),
    [18] = _("Stepped on a Pokémon Trap!"),
    [19] = _("Stepped on a Spiked Tile!"),
};

const u8 *const gUnknown_80FDA80 = _("The move {MOVE_ITEM_0} lost its PP!");
const u8 *const gUnknown_80FDAA0 = _("All PP are already gone!");
const u8 *const gUnknown_80FDACC = _("Unclaimed items turned into Pokémon!");
const u8 *const gUnknown_80FDAE4 = _("Nothing happened!");
const u8 *const gUnknown_80FDB04 = _("The move {MOVE_ITEM_0} was sealed!");
const u8 *const gUnknown_80FDB2C = _("All the moves are sealed already!");
const u8 *const gUnknown_80FDB5C = _("Its Scarf stopped the trap from\nspringing!");
const u8 *const gUnknown_80FDB7C = _("The trap failed to work!");
const u8 *const gUnknown_80FDBA0 = _("But there is no one in the way!");
const u8 *const gUnknown_80FDBB8 = _("{POKEMON_0} caught the {MOVE_ITEM_0}!");
const u8 *const gUnknown_80FDBD0 = _("{POKEMON_0} regained PP.");
const u8 *const gUnknown_80FDBF0 = _("{POKEMON_0} has full PP already!");
const u8 *const gUnknown_80FDC18 = _("The {MOVE_ITEM_0} became sticky and\nunusable!");
const u8 *const gUnknown_80FDC40 = _("But nothing happened in particular.");
const u8 *const gUnknown_80FDC7C = _("The No-Stick Cap prevented items from\ngetting sticky!");
const u8 *const gUnknown_80FDC9C = _("The used TM was recharged!");
const u8 *const gUnknown_80FDCA0 = _("But nothing happened.");
const u8 *const gUnknown_80FDCA4 = _("{POKEMON_0} is muzzled!");
const u8 *const gUnknown_80FDCC8 = _("{POKEMON_0} converted to\nthe {MOVE_ITEM_0} type!");
const u8 *const gUnknown_80FDCE4 = _("{POKEMON_0} mimicked its foe!");
const u8 *const gUnknown_80FDD00 = _("{POKEMON_0}'s Mimic failed!");
const u8 *const gUnknown_80FDD20 = _("The move was passed off!");
const u8 *const gUnknown_80FDD48 = _("There's no one to pass off to!");
const u8 *const gUnknown_80FDD88 = _("A mysterious force prevents moves\nfrom being passed off!");
const u8 *const gUnknown_80FDDA8 = _("The attack was passed off!");
const u8 *const gUnknown_80FDDAC = _("There's no one to pass off to!");
const u8 *const gUnknown_80FDDD0 = _("The closed corridor was opened!");
const u8 *const gUnknown_80FDDF0 = _("It can't be used here!");
const u8 *const gUnknown_80FDE18 = _("There is nothing at {POKEMON_0}'s feet.");
const u8 *const gUnknown_80FDE6C = _("Your adventure to this point will be saved\nin preparation for shutting down.");
const u8 *const gUnknown_80FDEB8 = _("Give up on this adventure?\nIf you do, it will be treated as a defeat.");
const u8 *const gUnknown_80FDF00 = _("Will the linked moves be forgotten,\nincluding the selected {MOVE_ITEM_0}?");
const u8 *const gUnknown_80FDF40 = _("Only four moves may be learned!\nWill a move be forgotten?");
const u8 *const gUnknown_80FDF70 = _("The move {MOVE_ITEM_0} will be\nforgotten.\nIs that OK?");
const u8 *const gUnknown_80FDFB8 = _("The chosen Pokémon will leave the Friend\nArea forever.\nIs that OK?");
const u8 *const gUnknown_80FDFE8 = _("{R_BUTTON} + {DPAD}: Shift moves\n{SELECT_BUTTON}: Switch set moves");
const u8 *const gUnknown_80FE008 = _("{POKEMON_0} can't talk just now.");
const u8 *const gUnknown_80FE034 = _("There are no items that can be trawled!");
const u8 *const gUnknown_80FE060 = _("All unclaimed items were drawn close!");
const u8 *const gUnknown_80FE0AC = _("There is no room on your team to accept\nthe guest rescue team's {POKEMON_0}.");
const u8 *const gUnknown_80FE0F4 = _("There is no room on your team to fit\nthe {POKEMON_0} that needs your help.");
const u8 *const gUnknown_80FE0F8 = _("There is no room on your team to fit\nthe {POKEMON_0} that needs your help.");
const u8 *const gUnknown_80FE134 = _("The guest rescue team's {POKEMON_0}\njoined your rescue team!");
const u8 *const gUnknown_80FE168 = _("Your client, {POKEMON_0}, joined\nyour rescue team!");
const u8 *const gUnknown_80FE1A4 = _("The Friend Area {MOVE_ITEM_0} is\nfull.\nA friend must be released.");
const u8 *const gUnknown_80FE20C = _("If you dismiss this Pokémon,\nit may never again join your rescue team.\nBid farewell to it anyway?");
const u8 *const gUnknown_80FE268 = _("Would you like to get help using a distress\ncall or get the password for getting\nhelp?");
const u8 *const gUnknown_80FE28C = _("A call for help will be issued.");
const u8 *const gUnknown_80FE2D0 = _("Your rescue team is not eligible to\nreceive any more rescues.");
const u8 *const gUnknown_80FE2EC = _("{POKEMON_0} evolved into {POKEMON_1}!");
const u8 *const gPtrItsaMonsterHouseMessage = _("It's a monster house!");
const u8 *const gUnknown_80FE330 = _("It became the move {MOVE_ITEM_0}'s type!");
const u8 *const gUnknown_80FE36C = _("There were no moves that could be used\nfor Conversion!");
const u8 *const gUnknown_80FE38C = _("The move {MOVE_ITEM_0} was sketched!");
const u8 *const gUnknown_80FE3BC = _("There were no moves that could be\nsketched!");
const u8 *const gItemStickyDoesntWorkText = _("{MOVE_ITEM_0} is all sticky!\nIt doesn't work!");
const u8 *const gUnknown_80FE3EC = _("{POKEMON_0} learned the move\n{MOVE_ITEM_0}.");
const u8 *const gUnknown_80FE40C = _("But nothing happened.");
const u8 *const gUnknown_80FE434 = _("Lucky! The move got a lot stronger!");
const u8 *const gUnknown_80FE454 = _("The set move got stronger!");
const u8 *const gUnknown_80FE458 = _("But nothing happened.");
const u8 *const gUnknown_80FE478 = _("{POKEMON_0} had second thoughts!");
const u8 *const gUnknown_80FE4B8 = _("Help! Thief! I've been robbed!\nHelp me catch the thief!");
const u8 *const gUnknown_80FE4D4 = _("Thank you so very much.");
const u8 *const gUnknown_80FE4F4 = _("Your patronage is valued.");
const u8 *const gUnknown_80FE520 = _("You don't seem to have enough money.");
const u8 *const gUnknown_80FE568 = _("The merchandise you have chosen\ncosts {VALUE_0} {POKE}.\nIs that acceptable?");
const u8 *const gUnknown_80FE5C0 = _("For the merchandise you have left me,\nI shall pay {VALUE_0} {POKE}.\nIs that acceptable?");
const u8 *const gUnknown_80FE5F0 = _("I'm looking forward to serving you again!");
const u8 *const gUnknown_80FE63C = _("That is very disappointing.\nPlease return any items\nbefore you leave...");
const u8 *const gUnknown_80FE65C = _("I await your next visit.");
const u8 *const gUnknown_80FE674 = _("Ah, welcome〜♪");
const u8 *const gUnknown_80FE690 = _("{POKEMON_0} was sent flying!");
const u8 *const gUnknown_80FE6B4 = _("But it didn't go anywhere.");
const u8 *const gUnknown_80FE6D4 = _("{POKEMON_0} can't throw items!");
const u8 *const gText_TheLastOuting = _("The Last Outing");
const u8 *const gUnknown_80FE6F4 = _("Someone");
const u8 *const gUnknown_80FE708 = _("Tile underfoot");
const u8 *const gUnknown_80FE70C = _("Stairs");
const u8 *const gUnknown_80FE720 = _("Rescue Point");
const u8 *const gUnknown_80FE724 = _("Warp Zone");
const u8 *const gOptionsDungeonTextPtr = _("Dungeon");
const u8 *const gOptionsOthersTextPtr = _("Others");
const u8 *const gUnknown_80FE748 = _("Default");
const u8 *const gUnknown_80FE764 = _("Speed{MOVE_X_POSITION_BY_80}Slow{MOVE_X_POSITION_BY_136}Fast");
const u8 *const gUnknown_80FE788 = _("Far-off pals{MOVE_X_POSITION_BY_80}Self{MOVE_X_POSITION_BY_136}Look");
const u8 *const gUnknown_80FE7A8 = _("Damage turn{MOVE_X_POSITION_BY_80}No{MOVE_X_POSITION_BY_136}Yes");
const u8 *const gUnknown_80FE7C0 = _("Grids{MOVE_X_POSITION_BY_80}Off{MOVE_X_POSITION_BY_136}On");
const u8 *const gUnknown_80FE7E4 = _("Map{MOVE_X_POSITION_BY_80}Off{MOVE_X_POSITION_BY_120}Clear{MOVE_X_POSITION_BY_160}Shade");
const u8 *const gOptionsWindowColorPtr = _("Windows{MOVE_X_POSITION_BY_80}Blue{MOVE_X_POSITION_BY_120}Red{MOVE_X_POSITION_BY_160}Green");
const u8 *const gDsTopScreenOptions[] = {
    [0] = _("Top screen: Team data"),
    [1] = _("Top screen: Team data"),
    [2] = _("Top screen: Team data"),
    [3] = _("Top screen: Message log"),
    [4] = _("Top screen: Message log"),
    [5] = _("Top screen: Message log"),
    [6] = _("Top screen: Map and team"),
};

const u8 *const gDsBottomScreenOptions[] = {
    [0] = _("Bottom screen: No map"),
    [1] = _("Bottom screen: Clear map"),
    [2] = _("Bottom screen: Shaded map"),
    [3] = _("Bottom screen: No map"),
    [4] = _("Bottom screen: Clear map"),
    [5] = _("Bottom screen: Shaded map"),
    [6] = _("Bottom screen: No map"),
};

const u8 *const gGameOptionsTextPtr = _("Game Options");
const u8 *const gUnknown_80FE8F4 = _("Quicksave");
const u8 *const gUnknown_80FE8F8 = _("Others");
const u8 *const gTeamToolboxAPtr = _("Team Toolbox A");
const u8 *const gTeamToolboxBPtr = _("Team Toolbox B");
const u8 *const gFieldItemMenuGroundTextPtr = _("Ground");
const u8 *const gUnknown_80FE940 = _("{POKEMON_0}'s item");
const u8 *const gWhichTextPtr1 = _("Which?");
const u8 *const gWhichTextPtr2 = _("Which?");
const u8 *const gUnknown_80FE954 = _("Tactics");
const u8 *const gUnknown_80FE95C = _("{MOVE_ITEM_0}");
const u8 *const gUnknown_80FE960 = _("{MOVE_ITEM_0}");
const u8 *const gUnknown_80FE964 = _("{MOVE_ITEM_0}");
const u8 *const gUnknown_80FE978 = _("{POKEMON_0}'s moves");
const u8 *const gFieldMenuMovesPtr = _("{UNK_MACRO_5F_1}Moves");
const u8 *const gFieldMenuItemsPtr = _("{UNK_MACRO_5F_2}Items");
const u8 *const gFieldMenuTeamPtr = _("{UNK_MACRO_5F_3}Team");
const u8 *const gFieldMenuOthersPtr = _("{UNK_MACRO_5F_4}Others");
const u8 *const gFieldMenuGroundPtr = _("{UNK_MACRO_5F_5}Ground");
const u8 *const gUnknown_80FE9CC = _("Game Options");
const u8 *const gUnknown_80FE9E8 = _("Quicksave or Give Up");
const u8 *const gUnknown_80FE9F8 = _("Message log");
const u8 *const gUnknown_80FEA10 = _("Mission objectives");
const u8 *const gUnknown_80FEA28 = _("Recruitment search");
const u8 *const gUnknown_80FEA44 = _("{COLOR RED}Recruitment search{RESET}");
const u8 *const gUnknown_80FEA50 = _("Hints");
const u8 *const gUnknown_80FEA68 = _("Potential recruits");
const u8 *const gUnknown_80FEA80 = _("Recruited Pokémon");
const u8 *const gUnknown_80FEA8C = _("None");
const u8 *const gUnknown_80FEAC4 = _("{POKEMON_0}'s IQ rose!\nIt learned the IQ skill\n“{MOVE_ITEM_0}”!");
const u8 *const gUnknown_80FEAE8 = _("It appears to be weak here...");
const u8 *const gUnknown_80FEB08 = _("{POKEMON_1} became the {MOVE_ITEM_0} type.");
const u8 *const gUnknown_80FEB30 = _("{POKEMON_1} took Perish Song's effect!");
const u8 *const gUnknown_80FEB60 = _("It can't lend a helping hand to itself!");
const u8 *const gUnknown_80FEB88 = _("Poor type match! It has no effect!");
const u8 *const gUnknown_80FEB8C = _("Poor type match! It has no effect!");
const u8 *const gUnknown_80FEB90 = _("Poor type match! It has no effect!");
const u8 *const gUnknown_80FEBBC = _("It avoided a burn by being on water!");
const u8 *const gUnknown_80FEBDC = _("It couldn't flop around!");
const u8 *const gUnknown_80FEBF8 = _("Change the settings?");
const u8 *const gUnknown_80FEC28 = _("Reset the options to their default setting?");
const u8 *const gUnknown_80FEC48 = _("Rescue chances left: {VALUE_0}");
const u8 *const gUnknown_80FEC7C = _("This team can't send out for help anymore!");
const u8 *const gUnknown_80FECA0 = _("Are you done with the Link Box?");
const u8 *const gUnknown_80FECBC = _("{POKEMON_0} waggled its finger!");
const u8 *const gUnknown_80FECE0 = _("{POKEMON_0} drew out nature's power!");
const u8 *const gUnknown_80FED00 = _("Pokémon were drawn close!");
const u8 *const gUnknown_80FED04 = _("But nothing happened!");
const u8 *const gUnknown_80FED08 = _("But nothing happened!");
const u8 *const gUnknown_80FED0C = _("But nothing happened!");
const u8 *const gUnknown_80FED30 = _("It bounced off the trick tile!");
const u8 *const gUnknown_80FED34 = _("{POKEMON_0} disappeared in the blast!");
const u8 *const gUnknown_80FED68 = _("{POKEMON_0} blinked.");
const u8 *const gUnknown_80FED88 = _("Overgrow boosted its power!");
const u8 *const gUnknown_80FEDA8 = _("Torrent boosted its power!");
const u8 *const gUnknown_80FEDC8 = _("Swarm boosted its power!");
const u8 *const gUnknown_80FEDE8 = _("Blaze boosted its power!");
const u8 *const gUnknown_80FEE04 = _("Guts boosted its power!");
const u8 *const gUnknown_80FEE2C = _("Its special ability boosted Attack!");
const u8 *const gUnknown_80FEE54 = _("Marvel Scale boosted its Defense!");
const u8 *const gUnknown_80FEE80 = _("Its special ability quickened attacks!");
const u8 *const gUnknown_80FEEA4 = _("Arena Trap prevents movement!");
const u8 *const gUnknown_80FEEC8 = _("Shadow Tag prevents movement!");
const u8 *const gUnknown_80FEEEC = _("Magnet Pull prevents movement!");
const u8 *const gUnknown_80FEF0C = _("Static caused paralysis!");
const u8 *const gUnknown_80FEF30 = _("Effect Spore scattered spores!");
const u8 *const gUnknown_80FEF4C = _("Poison Point struck!");
const u8 *const gUnknown_80FEF50 = _("Effect Spore scattered spores!");
const u8 *const gUnknown_80FEF54 = _("Effect Spore scattered spores!");
const u8 *const gUnknown_80FEF74 = _("Flame Body caused a burn!");
const u8 *const gUnknown_80FEF98 = _("Cute Charm caused infatuation!");
const u8 *const gUnknown_80FEFD0 = _("A horrid stench billowed out!\n{POKEMON_0} became terrified!");
const u8 *const gUnknown_80FEFF4 = _("Transform can't be used here!");
const u8 *const gUnknown_80FF01C = _("{POKEMON_0}'s Synchronize took effect!");
const struct TutorialFlagMsg gUnknown_80FF020 = {
    0x00, _("Head for the destination while attacking\nfoes with {A_BUTTON}.\nTry not to let a partner faint!")
};

const struct TutorialFlagMsg gUnknown_80FF080 = {
    0x01, _("Foes won't move until you do.\nOpen the menu with {B_BUTTON} and\nthink before you act!")
};

const struct TutorialFlagMsg gUnknown_80FF0D8 = {
    0x02, _("Your team regains HP as it moves.\nHold {B_BUTTON} then press {A_BUTTON} to recover\nHP quickly on the spot.")
};

const struct TutorialFlagMsg gUnknown_80FF13C = {
    0x0c, _("Defeat foes using moves instead of\n{A_BUTTON} attacks for more Exp. Points.\nChoose and set the move you want to use.")
};

const struct TutorialFlagMsg gUnknown_80FF1B4 = {
    0x0d, _("Choose a partner with the Team command\nand set its tactics and IQ skills.\nCooperation with partners is the key!")
};

const struct TutorialFlagMsg gMovementTutorial = {
    0x0e, _("Hold {B_BUTTON} then press {DPAD} to speed up\nmovement. Hold {R_BUTTON} then press {DPAD}\nto move only diagonally.")
};

const struct TutorialFlagMsg gHungerTutorial = {
    0x0f, _("Eat an Apple or Gummi when your Belly\ngoes down. Being famished can cause\nfainting, so check your Belly in the menu.")
};

const struct TutorialFlagMsg gFoodTutorial = {
    0x03, _("Eating an Apple or Gummi fills your Belly.\nChoose them under Items in the menu\nand eat one before your Belly gets empty.")
};

const struct TutorialFlagMsg gOranTutorial = {
    0x04, _("An Oran Berry restores HP.\nOpen the menu with {B_BUTTON} and\nselect it under Items.")
};

const struct TutorialFlagMsg gCheriTutorial = {
    0x05, _("A Cheri Berry heals paralysis.\nOpen the menu with {B_BUTTON} and\nselect it under Items.")
};

const struct TutorialFlagMsg gBlastSeedTutorial = {
    0x06, _("A Blast Seed flames the foe you\nare facing.\nTurn to face the foe, then use the item.")
};

const struct TutorialFlagMsg gUnknown_80FF4A0 = {
    0x07, _("Gravelerocks can be lobbed at distant foes.\nSet them for use under Items.\nHold {L_BUTTON} then press {R_BUTTON} to throw them.")
};

const struct TutorialFlagMsg gPechaTutorial = {
    0x09, _("A Pecha Berry heals any kind of poisoning.\nOpen the menu with {B_BUTTON} and\nselect it under Items.")
};

const struct TutorialFlagMsg gSleepSeedTutorial = {
    0x0a, _("Throw a Sleep Seed at a foe to put it\nto sleep for a little while.\nEating it will put you to sleep!")
};

const struct TutorialFlagMsg gMoneyTutorial = {
    0x0b, _("{POKE} is the money in this world.\nCollect and save it to buy useful\nitems.")
};

const u8 *const gUnknown_80FF674 = _("You're a thief!\nYou're not recognized as a rescuer!");
const u8 *const gUnknown_80FF678 = _("But nothing happened.");
const u8 *const gUnknown_80FF6A4 = _("You've reached a destination floor!");
const u8 *const gUnknown_80FF6F8 = _("You've reached a destination floor!\nBut the Pokémon you seek isn't here...");
const u8 *const gUnknown_80FF730 = _("{MOVE_ITEM_0} was added to\n{POKEMON_0}'s list of usable tactics.");
const u8 *const gUnknown_80FF76C = _("Items can't be thrown when a Pokémon's\nterrified!");
const u8 *const gText_Hints = _("Hints");

const u8 *const gHintsNames[HINTS_COUNT] = {
    [HINTS_CONTROLS] = _("Controls"),
    [HINTS_ORIENTATION] = _("Orientation"),
    [HINTS_SEEDS] = _("Seeds"),
    [HINTS_MOVES] = _("Moves"),
    [HINTS_RANGE] = _("Range"),
    [HINTS_LINKING_MOVES] = _("Linking moves"),
    [HINTS_POKEMON_TYPES] = _("Pokémon types"),
    [HINTS_TOUCH_SCREEN] = _("Touch Screen"),
};

const u8 *const gHintsDescriptions[2][HINTS_COUNT] = {
    [0] = {
        [HINTS_CONTROLS] = _("{L_BUTTON}+{A_BUTTON}: Use set move\n{L_BUTTON}+{B_BUTTON}: Display message log\n{L_BUTTON}+{R_BUTTON}: Throw set item\n{R_BUTTON}+{DPAD}: Move diagonally\n{SELECT_BUTTON}: Floor map\n{START_BUTTON}: Rotate mode\nSelect item/move + {START_BUTTON}: Description"),
        [HINTS_ORIENTATION] = _("Avoid attacks by moving diagonally.\nKeeping {R_BUTTON} pressed, press\n{DPAD} to move only diagonally.\nIt's also crucial to change the direction\nyou're facing without taking a step.\nJust tap {R_BUTTON}!"),
        [HINTS_SEEDS] = _("Seeds can be thrown.\nThey are usually for eating, but throw\nthem at foes to get the same effect.\nIf you have any Seeds you don't want\nto eat, try throwing them at foes.\nYou can also throw them at partners.\nIf they hit, their effects will be felt."),
        [HINTS_MOVES] = _("Normal-, Steel-, Poison-, Ground-,\nFlying-, Bug-, Rock-, Ghost-, and\nFighting-type moves are based on\nAttack and Defense. Fire-, Dark-,\nWater-, Grass-, Electric-, Ice-,\nPsychic-, and Dragon-type moves\nare based on Sp. Atk. and Sp. Def."),
        [HINTS_RANGE] = _("All moves have a range of effect.\nA move that affects a room, such as\nGrowl, reaches 2 tiles when in a\ncorridor. However, if the visibility is\nlimited to only 1 tile, the move's\nrange will be likewise restricted.\nCheck the descriptions of moves!"),
        [HINTS_LINKING_MOVES] = _("Moves can be linked at the Gulpin Link\nShop or by using a Link Box.\nTwo moves can be linked and used\nsimultaneously.\nIf they're used even once in defeating\na foe, you will earn more Exp. Points,\nbut your Belly will go down faster, too."),
        [HINTS_POKEMON_TYPES] = _("There are seventeen types of Pokémon\nand moves: Normal, Fire, Water, Grass,\nElectric, Ice, Fighting, Poison, Ground,\nFlying, Psychic, Bug, Rock, Ghost,\nDragon, Dark, and Steel. All Pokémon\nhave one or two types that determine\nthe damage they take and give."),
        [HINTS_TOUCH_SCREEN] = _("Press once: Push a foe to attack.\nTouch the floor to move. Advance text.\nCancel.\nPress twice: Use the set move.\nPress your Pokémon to move fast.\nKeep pressed to change directions\nwithout moving."),
    },
    [1] = {
        [HINTS_CONTROLS] = _("{L_BUTTON}+{A_BUTTON}: Use set move\n{L_BUTTON}+{B_BUTTON}: Display message log\n{L_BUTTON}+{R_BUTTON}: Throw set item\n{R_BUTTON}+{DPAD}: Move diagonally\n{NDS_Y_BUTTON}: Rotate mode\n{SELECT_BUTTON}: Floor map\nSelect item/move + {START_BUTTON}: Description"),
        [HINTS_ORIENTATION] = _("Avoid attacks by moving diagonally.\nKeeping {R_BUTTON} pressed, press\n{DPAD} to move only diagonally.\nIt's crucial to change the direction\nyou're facing without taking a step.\nHold {NDS_Y_BUTTON} to do so.\n"),
        [HINTS_SEEDS] = _("Seeds can be thrown.\nThey are usually for eating, but throw\nthem at foes to get the same effect.\nIf you have any Seeds you don't want\nto eat, try throwing them at foes.\nYou can also throw them at partners.\nIf they hit, their effects will be felt."),
        [HINTS_MOVES] = _("Normal-, Steel-, Poison-, Ground-,\nFlying-, Bug-, Rock-, Ghost-, and\nFighting-type moves are based on\nAttack and Defense. Fire-, Dark-,\nWater-, Grass-, Electric-, Ice-,\nPsychic-, and Dragon-type moves\nare based on Sp. Atk. and Sp. Def."),
        [HINTS_RANGE] = _("All moves have a range of effect.\nA move that affects a room, such as\nGrowl, reaches 2 tiles when in a\ncorridor. However, if the visibility is\nlimited to only 1 tile, the move's\nrange will be likewise restricted.\nCheck the descriptions of moves!"),
        [HINTS_LINKING_MOVES] = _("Moves can be linked at the Gulpin Link\nShop or by using a Link Box.\nTwo moves can be linked and used\nsimultaneously.\nIf they're used even once in defeating\na foe, you will earn more Exp. Points,\nbut your Belly will go down faster, too."),
        [HINTS_POKEMON_TYPES] = _("There are seventeen types of Pokémon\nand moves: Normal, Fire, Water, Grass,\nElectric, Ice, Fighting, Poison, Ground,\nFlying, Psychic, Bug, Rock, Ghost,\nDragon, Dark, and Steel. All Pokémon\nhave one or two types that determine\nthe damage they take and give."),
        [HINTS_TOUCH_SCREEN] = _("Touch once to attack a foe, walk,\nadvance text, cancel, or pick up \nan item off the ground.\nTouch twice to use the set move.\nTouch the leader twice to move fast.\nTouch and hold to change directions\nwithout taking a step."),
    }
};

const u8 *const gUnknown_8100208 = _("Switch places with your teammate?\nThis will cause the teammate to warp.");
const u8 *const gPtrMagnitudeMessage = _("It's Magnitude {VALUE_0}!");
const u8 *const gPtrSleepingTargetOnlyMessage = _("It only works on a sleeping target!");
const u8 *const gPtrFeralFoundItemMessage = _("{POKEMON_0} found an item somewhere.");
const u8 *const gPtrSelfHealPreventedHungerMessage = _("Its self-healing prevented hunger!");
const u8 *const gUnknown_81002B8 = _("Rescue challenges left: {VALUE_0}");
const u8 *const gPtrFinalChanceMessage = _("This is your final chance!");
const u8 *const gPtrLinkedMovesComeApartMessage = _("The linked moves came apart!");
const u8 *const gPtrLinkMoveOneUseWarningMessage = _("{color YELLOW}The linked moves are almost out of PP!{reset}\n{color YELLOW}Use them again and they will come apart!{reset}");
const u8 *const gPtrLinkMoveTwoUsesWarningMessage = _("{color YELLOW}The linked moves are almost out of PP!{reset}\n{color YELLOW}Use them twice and they will come apart!{reset}");
const u8 *const gPtrIcePartCrumbledMessage = _("The Ice Part crumbled away...");
const u8 *const gPtrRockPartCrumbledMessage = _("The Rock Part crumbled away...");
const u8 *const gPtrSteelPartCrumbledMessage = _("The Steel Part crumbled away...");
const u8 *const gPtrWishStoneCrumbledMessage = _("The Wish Stone crumbled away...");
const u8 *const gPtrMusicBoxPlayedCrumbledMessage = _("The Music Box played a beautiful melody,\nthen crumbled away...");
const u8 *const gPtrMysteriousPowerPreventedUseMessage = _("But a mysterious power prevented its use!");
const u8 *const gPtrCouldntBeUsedMessage = _("But it couldn't be used!");
const u8 *const gUnknown_81004E8 = _("But nothing happened.");
const u8 *const gUnknown_81004EC = _("But nothing happened.");
const u8 *const gUnknown_81004F0 = _("But nothing happened.");
const u8 *const gUnknown_8100524 = _("{POKEMON_1}'s Soundproof suppressed\nthe sound move!");
const u8 *const gUnknown_8100548 = _("The attack was barely endured!");
const u8 *const gUnknown_810056C = _("False Swipe prevented fainting!");
const u8 *const gUnknown_8100594 = _("Perish Song's effect wore off!");
const u8 *const gPtrExposedWoreOffMessage = _("The Exposed status wore off!");
const u8 *const gPtrSealedMoveReleasedMessage = _("The sealed move was released!");
const u8 *const gPtrCantLeechSeedSelfMessage = _("A leech seed can't be planted on the user!");
const u8 *const gPtrCantLeechSeedMonMessage = _("A leech seed couldn't be planted on\n{POKEMON_0}!");
const u8 *const gPtrMoveInterruptedMessage = _("The move was interrupted!");
const u8 *const gPtrClientFaintedMessage = _("Your client Pokémon has fainted!\nA rescue call can't be made!");
const u8 *const gPtrCantUseInDungeonMessage = _("It can't be used in a dungeon!");
const u8 *const gPtrForecastPreventsTypeSwitchMessage = _("Its Forecast prevents type switching!");
const u8 *const gPtrForecastPreventsConversion2Message = _("Its Forecast prevents Conversion 2!");
const u8 *const gPtrStenchWavedOffMessage = _("The stench was waved off!");
const u8 *const gPtrProtectSavedItMessage = _("Its Protect saved it!");
