#include "global.h"
#include "globaldata.h"
#include "ground_map_conversion_table.h"
#include "ground_place.h"
#include "map_files_table.h"
#include "constants/ground_map.h"

const GroundConversionStruct gGroundMapConversionTable[MAP_COUNT] = {
    [MAP_SQUARE] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_SQUARE,
        .mapFileTableId = MAP_FILE_ID_SQUARE,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00000"),
    },
    [MAP_POKEMON_SQUARE] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_POKEMON_SQUARE,
        .mapFileTableId = MAP_FILE_ID_POKEMON_SQUARE,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00001"),
    },
    [MAP_WHISCASH_POND] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_WHISCASH_POND,
        .mapFileTableId = MAP_FILE_ID_WHISCASH_POND,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00002"),
    },
    [MAP_WHISCASH_POND_OPEN] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_WHISCASH_POND,
        .mapFileTableId = MAP_FILE_ID_WHISCASH_POND_OPEN,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00003"),
    },
    [MAP_PELIPPER_POST_OFFICE] = {
        .unk0 = 5,
        .groundPlaceId = GROUND_PLACE_PELIPPER_POST_OFFICE,
        .mapFileTableId = MAP_FILE_ID_PELIPPER_POST_OFFICE,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00004"),
    },
    [MAP_PELIPPER_POST_OFFICE_INSIDE] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_PELIPPER_POST_OFFICE_INSIDE,
        .mapFileTableId = MAP_FILE_ID_PELIPPER_POST_OFFICE_INSIDE,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00005"),
    },
    [MAP_MAKUHITA_DOJO] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_MAKUHITA_DOJO,
        .mapFileTableId = MAP_FILE_ID_MAKUHITA_DOJO,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00006"),
    },
    [MAP_MAKUHITA_DOJO_INSIDE] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_MAKUHITA_DOJO_INSIDE,
        .mapFileTableId = MAP_FILE_ID_MAKUHITA_DOJO_INSIDE,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00007"),
    },
    [MAP_LUMINOUS_CAVE] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_LUMINOUS_CAVE,
        .mapFileTableId = MAP_FILE_ID_LUMINOUS_CAVE,
        .unk6 = 0,
        .text = _("__ground_amd_conversion_00008"),
    },
    [MAP_TEAM_BASE_PIKACHU_BASIC] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_PIKACHU_BASIC,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00010"),
    },
    [MAP_TEAM_BASE_PIKACHU_CONSTRUCTION] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_PIKACHU_CONSTRUCTION,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00011"),
    },
    [MAP_TEAM_BASE_PIKACHU_FINAL] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_PIKACHU_FINAL,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00012"),
    },
    [MAP_TEAM_BASE_INSIDE_PIKACHU_BASIC] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_INSIDE_PIKACHU_BASIC,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00013"),
    },
    [MAP_TEAM_BASE_INSIDE_PIKACHU_CONSTRUCTION] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_INSIDE_PIKACHU_CONSTRUCTION,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00014"),
    },
    [MAP_TEAM_BASE_INSIDE_PIKACHU_FINAL] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_INSIDE_PIKACHU_FINAL,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00015"),
    },
    [MAP_TEAM_BASE_MEOWTH_BASIC] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_MEOWTH_BASIC,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00016"),
    },
    [MAP_TEAM_BASE_MEOWTH_CONSTRUCTION] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_MEOWTH_CONSTRUCTION,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00017"),
    },
    [MAP_TEAM_BASE_MEOWTH_FINAL] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_MEOWTH_FINAL,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00018"),
    },
    [MAP_TEAM_BASE_INSIDE_MEOWTH_BASIC] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_INSIDE_MEOWTH_BASIC,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00019"),
    },
    [MAP_TEAM_BASE_INSIDE_MEOWTH_CONSTRUCTION] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_INSIDE_MEOWTH_CONSTRUCTION,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00020"),
    },
    [MAP_TEAM_BASE_INSIDE_MEOWTH_FINAL] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_INSIDE_MEOWTH_FINAL,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00021"),
    },
    [MAP_TEAM_BASE_EEVEE_BASIC] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_EEVEE_BASIC,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00022"),
    },
    [MAP_TEAM_BASE_EEVEE_CONSTRUCTION] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_EEVEE_CONSTRUCTION,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00023"),
    },
    [MAP_TEAM_BASE_EEVEE_FINAL] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_EEVEE_FINAL,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00024"),
    },
    [MAP_TEAM_BASE_INSIDE_EEVEE_BASIC] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_INSIDE_EEVEE_BASIC,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00025"),
    },
    [MAP_TEAM_BASE_INSIDE_EEVEE_CONSTRUCTION] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_INSIDE_EEVEE_CONSTRUCTION,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00026"),
    },
    [MAP_TEAM_BASE_INSIDE_EEVEE_FINAL] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_INSIDE_EEVEE_FINAL,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00027"),
    },
    [MAP_TEAM_BASE_SKITTY_BASIC] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_SKITTY_BASIC,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00028"),
    },
    [MAP_TEAM_BASE_SKITTY_CONSTRUCTION] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_SKITTY_CONSTRUCTION,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00029"),
    },
    [MAP_TEAM_BASE_SKITTY_FINAL] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_SKITTY_FINAL,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00030"),
    },
    [MAP_TEAM_BASE_INSIDE_SKITTY_BASIC] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_INSIDE_SKITTY_BASIC,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00031"),
    },
    [MAP_TEAM_BASE_INSIDE_SKITTY_CONSTRUCTION] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_INSIDE_SKITTY_CONSTRUCTION,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00032"),
    },
    [MAP_TEAM_BASE_INSIDE_SKITTY_FINAL] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_INSIDE_SKITTY_FINAL,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00033"),
    },
    [MAP_TEAM_BASE_SQUIRTLE_BASIC] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_SQUIRTLE_BASIC,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00034"),
    },
    [MAP_TEAM_BASE_SQUIRTLE_CONSTRUCTION] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_SQUIRTLE_CONSTRUCTION,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00035"),
    },
    [MAP_TEAM_BASE_SQUIRTLE_FINAL] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_SQUIRTLE_FINAL,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00036"),
    },
    [MAP_TEAM_BASE_INSIDE_SQUIRTLE_BASIC] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_INSIDE_SQUIRTLE_BASIC,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00037"),
    },
    [MAP_TEAM_BASE_INSIDE_SQUIRTLE_CONSTRUCTION] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_INSIDE_SQUIRTLE_CONSTRUCTION,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00038"),
    },
    [MAP_TEAM_BASE_INSIDE_SQUIRTLE_FINAL] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_INSIDE_SQUIRTLE_FINAL,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00039"),
    },
    [MAP_TEAM_BASE_TOTODILE_BASIC] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_TOTODILE_BASIC,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00040"),
    },
    [MAP_TEAM_BASE_TOTODILE_CONSTRUCTION] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_TOTODILE_CONSTRUCTION,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00041"),
    },
    [MAP_TEAM_BASE_TOTODILE_FINAL] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_TOTODILE_FINAL,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00042"),
    },
    [MAP_TEAM_BASE_INSIDE_TOTODILE_BASIC] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_INSIDE_TOTODILE_BASIC,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00043"),
    },
    [MAP_TEAM_BASE_INSIDE_TOTODILE_CONSTRUCTION] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_INSIDE_TOTODILE_CONSTRUCTION,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00044"),
    },
    [MAP_TEAM_BASE_INSIDE_TOTODILE_FINAL] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_INSIDE_TOTODILE_FINAL,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00045"),
    },
    [MAP_TEAM_BASE_MUDKIP_BASIC] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_MUDKIP_BASIC,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00046"),
    },
    [MAP_TEAM_BASE_MUDKIP_CONSTRUCTION] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_MUDKIP_CONSTRUCTION,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00047"),
    },
    [MAP_TEAM_BASE_MUDKIP_FINAL] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_MUDKIP_FINAL,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00048"),
    },
    [MAP_TEAM_BASE_INSIDE_MUDKIP_BASIC] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_INSIDE_MUDKIP_BASIC,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00049"),
    },
    [MAP_TEAM_BASE_INSIDE_MUDKIP_CONSTRUCTION] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_INSIDE_MUDKIP_CONSTRUCTION,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00050"),
    },
    [MAP_TEAM_BASE_INSIDE_MUDKIP_FINAL] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_INSIDE_MUDKIP_FINAL,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00051"),
    },
    [MAP_TEAM_BASE_PSYDUCK_BASIC] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_PSYDUCK_BASIC,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00052"),
    },
    [MAP_TEAM_BASE_PSYDUCK_CONSTRUCTION] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_PSYDUCK_CONSTRUCTION,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00053"),
    },
    [MAP_TEAM_BASE_PSYDUCK_FINAL] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_PSYDUCK_FINAL,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00054"),
    },
    [MAP_TEAM_BASE_INSIDE_PSYDUCK_BASIC] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_INSIDE_PSYDUCK_BASIC,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00055"),
    },
    [MAP_TEAM_BASE_INSIDE_PSYDUCK_CONSTRUCTION] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_INSIDE_PSYDUCK_CONSTRUCTION,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00056"),
    },
    [MAP_TEAM_BASE_INSIDE_PSYDUCK_FINAL] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_INSIDE_PSYDUCK_FINAL,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00057"),
    },
    [MAP_TEAM_BASE_CHARMANDER_BASIC] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_CHARMANDER_BASIC,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00058"),
    },
    [MAP_TEAM_BASE_CHARMANDER_CONSTRUCTION] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_CHARMANDER_CONSTRUCTION,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00059"),
    },
    [MAP_TEAM_BASE_CHARMANDER_FINAL] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_CHARMANDER_FINAL,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00060"),
    },
    [MAP_TEAM_BASE_INSIDE_CHARMANDER_BASIC] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_INSIDE_CHARMANDER_BASIC,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00061"),
    },
    [MAP_TEAM_BASE_INSIDE_CHARMANDER_CONSTRUCTION] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_INSIDE_CHARMANDER_CONSTRUCTION,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00062"),
    },
    [MAP_TEAM_BASE_INSIDE_CHARMANDER_FINAL] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_INSIDE_CHARMANDER_FINAL,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00063"),
    },
    [MAP_TEAM_BASE_TORCHIC_BASIC] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_TORCHIC_BASIC,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00064"),
    },
    [MAP_TEAM_BASE_TORCHIC_CONSTRUCTION] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_TORCHIC_CONSTRUCTION,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00065"),
    },
    [MAP_TEAM_BASE_TORCHIC_FINAL] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_TORCHIC_FINAL,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00066"),
    },
    [MAP_TEAM_BASE_INSIDE_TORCHIC_BASIC] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_INSIDE_TORCHIC_BASIC,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00067"),
    },
    [MAP_TEAM_BASE_INSIDE_TORCHIC_CONSTRUCTION] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_INSIDE_TORCHIC_CONSTRUCTION,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00068"),
    },
    [MAP_TEAM_BASE_INSIDE_TORCHIC_FINAL] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_INSIDE_TORCHIC_FINAL,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00069"),
    },
    [MAP_TEAM_BASE_CYNDAQUIL_BASIC] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_CYNDAQUIL_BASIC,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00070"),
    },
    [MAP_TEAM_BASE_CYNDAQUIL_CONSTRUCTION] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_CYNDAQUIL_CONSTRUCTION,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00071"),
    },
    [MAP_TEAM_BASE_CYNDAQUIL_FINAL] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_CYNDAQUIL_FINAL,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00072"),
    },
    [MAP_TEAM_BASE_INSIDE_CYNDAQUIL_BASIC] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_INSIDE_CYNDAQUIL_BASIC,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00073"),
    },
    [MAP_TEAM_BASE_INSIDE_CYNDAQUIL_CONSTRUCTION] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_INSIDE_CYNDAQUIL_CONSTRUCTION,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00074"),
    },
    [MAP_TEAM_BASE_INSIDE_CYNDAQUIL_FINAL] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_INSIDE_CYNDAQUIL_FINAL,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00075"),
    },
    [MAP_TEAM_BASE_CUBONE_BASIC] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_CUBONE_BASIC,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00076"),
    },
    [MAP_TEAM_BASE_CUBONE_CONSTRUCTION] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_CUBONE_CONSTRUCTION,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00077"),
    },
    [MAP_TEAM_BASE_CUBONE_FINAL] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_CUBONE_FINAL,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00078"),
    },
    [MAP_TEAM_BASE_INSIDE_CUBONE_BASIC] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_INSIDE_CUBONE_BASIC,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00079"),
    },
    [MAP_TEAM_BASE_INSIDE_CUBONE_CONSTRUCTION] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_INSIDE_CUBONE_CONSTRUCTION,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00080"),
    },
    [MAP_TEAM_BASE_INSIDE_CUBONE_FINAL] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_INSIDE_CUBONE_FINAL,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00081"),
    },
    [MAP_TEAM_BASE_MACHOP_BASIC] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_MACHOP_BASIC,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00082"),
    },
    [MAP_TEAM_BASE_MACHOP_CONSTRUCTION] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_MACHOP_CONSTRUCTION,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00083"),
    },
    [MAP_TEAM_BASE_MACHOP_FINAL] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_MACHOP_FINAL,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00084"),
    },
    [MAP_TEAM_BASE_INSIDE_MACHOP_BASIC] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_INSIDE_MACHOP_BASIC,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00085"),
    },
    [MAP_TEAM_BASE_INSIDE_MACHOP_CONSTRUCTION] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_INSIDE_MACHOP_CONSTRUCTION,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00086"),
    },
    [MAP_TEAM_BASE_INSIDE_MACHOP_FINAL] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_INSIDE_MACHOP_FINAL,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00087"),
    },
    [MAP_TEAM_BASE_BULBASAUR_BASIC] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_BULBASAUR_BASIC,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00088"),
    },
    [MAP_TEAM_BASE_BULBASAUR_CONSTRUCTION] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_BULBASAUR_CONSTRUCTION,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00089"),
    },
    [MAP_TEAM_BASE_BULBASAUR_FINAL] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_BULBASAUR_FINAL,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00090"),
    },
    [MAP_TEAM_BASE_INSIDE_BULBASAUR_BASIC] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_INSIDE_BULBASAUR_BASIC,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00091"),
    },
    [MAP_TEAM_BASE_INSIDE_BULBASAUR_CONSTRUCTION] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_INSIDE_BULBASAUR_CONSTRUCTION,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00092"),
    },
    [MAP_TEAM_BASE_INSIDE_BULBASAUR_FINAL] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_INSIDE_BULBASAUR_FINAL,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00093"),
    },
    [MAP_TEAM_BASE_CHIKORITA_BASIC] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_CHIKORITA_BASIC,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00094"),
    },
    [MAP_TEAM_BASE_CHIKORITA_CONSTRUCTION] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_CHIKORITA_CONSTRUCTION,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00095"),
    },
    [MAP_TEAM_BASE_CHIKORITA_FINAL] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_CHIKORITA_FINAL,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00096"),
    },
    [MAP_TEAM_BASE_INSIDE_CHIKORITA_BASIC] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_INSIDE_CHIKORITA_BASIC,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00097"),
    },
    [MAP_TEAM_BASE_INSIDE_CHIKORITA_CONSTRUCTION] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_INSIDE_CHIKORITA_CONSTRUCTION,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00098"),
    },
    [MAP_TEAM_BASE_INSIDE_CHIKORITA_FINAL] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_INSIDE_CHIKORITA_FINAL,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00099"),
    },
    [MAP_TEAM_BASE_TREECKO_BASIC] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_TREECKO_BASIC,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00100"),
    },
    [MAP_TEAM_BASE_TREECKO_CONSTRUCTION] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_TREECKO_CONSTRUCTION,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00101"),
    },
    [MAP_TEAM_BASE_TREECKO_FINAL] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_TREECKO_FINAL,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00102"),
    },
    [MAP_TEAM_BASE_INSIDE_TREECKO_BASIC] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_INSIDE_TREECKO_BASIC,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00103"),
    },
    [MAP_TEAM_BASE_INSIDE_TREECKO_CONSTRUCTION] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_INSIDE_TREECKO_CONSTRUCTION,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00104"),
    },
    [MAP_TEAM_BASE_INSIDE_TREECKO_FINAL] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_INSIDE_TREECKO_FINAL,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00105"),
    },
    [MAP_FRIEND_AREA_BOUNTIFUL_SEA] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = MAP_FILE_ID_FRIEND_AREA_BOUNTIFUL_SEA,
        .unk6 = 1,
        .text = _("__ground_amd_conversion_00106"),
    },
    [MAP_FRIEND_AREA_TREASURE_SEA] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = MAP_FILE_ID_FRIEND_AREA_TREASURE_SEA,
        .unk6 = 14,
        .text = _("__ground_amd_conversion_00108"),
    },
    [MAP_FRIEND_AREA_SERENE_SEA] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = MAP_FILE_ID_FRIEND_AREA_SERENE_SEA,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00109"),
    },
    [MAP_FRIEND_AREA_DEEP_SEA_FLOOR] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = MAP_FILE_ID_FRIEND_AREA_DEEP_SEA_FLOOR,
        .unk6 = 2,
        .text = _("__ground_amd_conversion_00110"),
    },
    [MAP_FRIEND_AREA_DEEP_SEA_CURRENT] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = MAP_FILE_ID_FRIEND_AREA_DEEP_SEA_CURRENT,
        .unk6 = 3,
        .text = _("__ground_amd_conversion_00112"),
    },
    [MAP_FRIEND_AREA_SEAFLOOR_CAVE] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = MAP_FILE_ID_FRIEND_AREA_SEAFLOOR_CAVE,
        .unk6 = 4,
        .text = _("__ground_amd_conversion_00114"),
    },
    [MAP_FRIEND_AREA_SHALLOW_BEACH] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = MAP_FILE_ID_FRIEND_AREA_SHALLOW_BEACH,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00116"),
    },
    [MAP_FRIEND_AREA_MT_DEEPGREEN] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = MAP_FILE_ID_FRIEND_AREA_MT_DEEPGREEN,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00117"),
    },
    [MAP_FRIEND_AREA_MT_CLEFT] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = MAP_FILE_ID_FRIEND_AREA_MT_CLEFT,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00118"),
    },
    [MAP_FRIEND_AREA_MT_MOONVIEW] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = MAP_FILE_ID_FRIEND_AREA_MT_MOONVIEW,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00119"),
    },
    [MAP_FRIEND_AREA_RAINBOW_PEAK] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = MAP_FILE_ID_FRIEND_AREA_RAINBOW_PEAK,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00120"),
    },
    [MAP_FRIEND_AREA_WILD_PLAINS] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = MAP_FILE_ID_FRIEND_AREA_WILD_PLAINS,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00121"),
    },
    [MAP_FRIEND_AREA_BEAU_PLAINS] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = MAP_FILE_ID_FRIEND_AREA_BEAU_PLAINS,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00122"),
    },
    [MAP_FRIEND_AREA_SKY_BLUE_PLAINS] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = MAP_FILE_ID_FRIEND_AREA_SKY_BLUE_PLAINS,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00123"),
    },
    [MAP_FRIEND_AREA_SAFARI] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = MAP_FILE_ID_FRIEND_AREA_SAFARI,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00124"),
    },
    [MAP_FRIEND_AREA_SCORCHED_PLAINS] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = MAP_FILE_ID_FRIEND_AREA_SCORCHED_PLAINS,
        .unk6 = 13,
        .text = _("__ground_amd_conversion_00125"),
    },
    [MAP_FRIEND_AREA_SACRED_FIELD] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = MAP_FILE_ID_FRIEND_AREA_SACRED_FIELD,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00126"),
    },
    [MAP_FRIEND_AREA_MIST_RISE_FOREST] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = MAP_FILE_ID_FRIEND_AREA_MIST_RISE_FOREST,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00127"),
    },
    [MAP_FRIEND_AREA_FLYAWAY_FOREST] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = MAP_FILE_ID_FRIEND_AREA_FLYAWAY_FOREST,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00128"),
    },
    [MAP_FRIEND_AREA_OVERGROWN_FOREST] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = MAP_FILE_ID_FRIEND_AREA_OVERGROWN_FOREST,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00129"),
    },
    [MAP_FRIEND_AREA_ENERGETIC_FOREST] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = MAP_FILE_ID_FRIEND_AREA_ENERGETIC_FOREST,
        .unk6 = 5,
        .text = _("__ground_amd_conversion_00130"),
    },
    [MAP_FRIEND_AREA_MUSHROOM_FOREST] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = MAP_FILE_ID_FRIEND_AREA_MUSHROOM_FOREST,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00132"),
    },
    [MAP_FRIEND_AREA_HEALING_FOREST] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = MAP_FILE_ID_FRIEND_AREA_HEALING_FOREST,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00133"),
    },
    [MAP_FRIEND_AREA_TRANSFORM_FOREST] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = MAP_FILE_ID_FRIEND_AREA_TRANSFORM_FOREST,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00134"),
    },
    [MAP_FRIEND_AREA_SECRETIVE_FOREST] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = MAP_FILE_ID_FRIEND_AREA_SECRETIVE_FOREST,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00135"),
    },
    [MAP_FRIEND_AREA_RUB_A_DUB_RIVER] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = MAP_FILE_ID_FRIEND_AREA_RUB_A_DUB_RIVER,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00136"),
    },
    [MAP_FRIEND_AREA_TADPOLE_POND] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = MAP_FILE_ID_FRIEND_AREA_TADPOLE_POND,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00137"),
    },
    [MAP_FRIEND_AREA_TURTLESHELL_POND] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = MAP_FILE_ID_FRIEND_AREA_TURTLESHELL_POND,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00138"),
    },
    [MAP_FRIEND_AREA_MYSTIC_LAKE] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = MAP_FILE_ID_FRIEND_AREA_MYSTIC_LAKE,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00139"),
    },
    [MAP_FRIEND_AREA_WATERFALL_LAKE] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = MAP_FILE_ID_FRIEND_AREA_WATERFALL_LAKE,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00140"),
    },
    [MAP_FRIEND_AREA_PEANUT_SWAMP] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = MAP_FILE_ID_FRIEND_AREA_PEANUT_SWAMP,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00141"),
    },
    [MAP_FRIEND_AREA_POISON_SWAMP] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = MAP_FILE_ID_FRIEND_AREA_POISON_SWAMP,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00142"),
    },
    [MAP_FRIEND_AREA_ECHO_CAVE] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = MAP_FILE_ID_FRIEND_AREA_ECHO_CAVE,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00143"),
    },
    [MAP_FRIEND_AREA_CRYPTIC_CAVE] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = MAP_FILE_ID_FRIEND_AREA_CRYPTIC_CAVE,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00144"),
    },
    [MAP_FRIEND_AREA_DRAGON_CAVE] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = MAP_FILE_ID_FRIEND_AREA_DRAGON_CAVE,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00145"),
    },
    [MAP_FRIEND_AREA_BOULDER_CAVE] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = MAP_FILE_ID_FRIEND_AREA_BOULDER_CAVE,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00146"),
    },
    [MAP_FRIEND_AREA_JUNGLE] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = MAP_FILE_ID_FRIEND_AREA_JUNGLE,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00147"),
    },
    [MAP_FRIEND_AREA_DECREPIT_LAB] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = MAP_FILE_ID_FRIEND_AREA_DECREPIT_LAB,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00148"),
    },
    [MAP_FRIEND_AREA_MT_DISCIPLINE] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = MAP_FILE_ID_FRIEND_AREA_MT_DISCIPLINE,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00149"),
    },
    [MAP_FRIEND_AREA_THUNDER_MEADOW] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = MAP_FILE_ID_FRIEND_AREA_THUNDER_MEADOW,
        .unk6 = 6,
        .text = _("__ground_amd_conversion_00150"),
    },
    [MAP_FRIEND_AREA_POWER_PLANT] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = MAP_FILE_ID_FRIEND_AREA_POWER_PLANT,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00152"),
    },
    [MAP_FRIEND_AREA_CRATER] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = MAP_FILE_ID_FRIEND_AREA_CRATER,
        .unk6 = 7,
        .text = _("__ground_amd_conversion_00153"),
    },
    [MAP_FRIEND_AREA_FURNACE_DESERT] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = MAP_FILE_ID_FRIEND_AREA_FURNACE_DESERT,
        .unk6 = 14,
        .text = _("__ground_amd_conversion_00155"),
    },
    [MAP_FRIEND_AREA_AGED_CHAMBER_AN] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = MAP_FILE_ID_FRIEND_AREA_AGED_CHAMBER_AN,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00156"),
    },
    [MAP_FRIEND_AREA_AGED_CHAMBER_O_EXCLAIM] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = MAP_FILE_ID_FRIEND_AREA_AGED_CHAMBER_O_EXCLAIM,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00157"),
    },
    [MAP_FRIEND_AREA_ANCIENT_RELIC] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = MAP_FILE_ID_FRIEND_AREA_ANCIENT_RELIC,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00158"),
    },
    [MAP_FRIEND_AREA_DARKNESS_RIDGE] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = MAP_FILE_ID_FRIEND_AREA_DARKNESS_RIDGE,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00159"),
    },
    [MAP_FRIEND_AREA_FRIGID_CAVERN] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = MAP_FILE_ID_FRIEND_AREA_FRIGID_CAVERN,
        .unk6 = 10,
        .text = _("__ground_amd_conversion_00160"),
    },
    [MAP_FRIEND_AREA_ICE_FLOE_BEACH] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = MAP_FILE_ID_FRIEND_AREA_ICE_FLOE_BEACH,
        .unk6 = 12,
        .text = _("__ground_amd_conversion_00161"),
    },
    [MAP_FRIEND_AREA_VOLCANIC_PIT] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = MAP_FILE_ID_FRIEND_AREA_VOLCANIC_PIT,
        .unk6 = 13,
        .text = _("__ground_amd_conversion_00162"),
    },
    [MAP_FRIEND_AREA_STRATOS_LOOKOUT] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = MAP_FILE_ID_FRIEND_AREA_STRATOS_LOOKOUT,
        .unk6 = 14,
        .text = _("__ground_amd_conversion_00163"),
    },
    [MAP_FRIEND_AREA_RAVAGED_FIELD] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = MAP_FILE_ID_FRIEND_AREA_RAVAGED_FIELD,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00164"),
    },
    [MAP_FRIEND_AREA_MAGNETIC_QUARRY] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = MAP_FILE_ID_FRIEND_AREA_MAGNETIC_QUARRY,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00165"),
    },
    [MAP_FRIEND_AREA_LEGENDARY_ISLAND] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = MAP_FILE_ID_FRIEND_AREA_LEGENDARY_ISLAND,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00166"),
    },
    [MAP_FRIEND_AREA_SOUTHERN_ISLAND] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = MAP_FILE_ID_FRIEND_AREA_SOUTHERN_ISLAND,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00167"),
    },
    [MAP_FRIEND_AREA_ENCLOSED_ISLAND] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = MAP_FILE_ID_FRIEND_AREA_ENCLOSED_ISLAND,
        .unk6 = 8,
        .text = _("__ground_amd_conversion_00168"),
    },
    [MAP_FRIEND_AREA_FINAL_ISLAND] = {
        .unk0 = 5,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = MAP_FILE_ID_FRIEND_AREA_FINAL_ISLAND,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00170"),
    },
    [MAP_PERSONALITY_TEST_CYAN] = {
        .unk0 = 9,
        .groundPlaceId = GROUND_PLACE_DIRECTION,
        .mapFileTableId = MAP_FILE_ID_PERSONALITY_TEST_CYAN,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00171"),
    },
    [MAP_PERSONALITY_TEST_PURPLE] = {
        .unk0 = 9,
        .groundPlaceId = GROUND_PLACE_DIRECTION,
        .mapFileTableId = MAP_FILE_ID_PERSONALITY_TEST_PURPLE,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00172"),
    },
    [MAP_FUGITIVES_FISSURE] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_DIRECTION,
        .mapFileTableId = MAP_FILE_ID_FUGITIVES_FISSURE,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00173"),
    },
    [MAP_FUGITIVES_FIRE] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_DIRECTION,
        .mapFileTableId = MAP_FILE_ID_FUGITIVES_FIRE,
        .unk6 = 13,
        .text = _("__ground_amd_conversion_00174"),
    },
    [MAP_FUGITIVES_LAPIS_CAVE] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_DIRECTION,
        .mapFileTableId = MAP_FILE_ID_FUGITIVES_LAPIS_CAVE,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00175"),
    },
    [MAP_FUGITIVES_VOLCANO] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_DIRECTION,
        .mapFileTableId = MAP_FILE_ID_FUGITIVES_VOLCANO,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00176"),
    },
    [MAP_FUGITIVES_SNOW_ROAD] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_DIRECTION,
        .mapFileTableId = MAP_FILE_ID_FUGITIVES_SNOW_ROAD,
        .unk6 = 10,
        .text = _("__ground_amd_conversion_00177"),
    },
    [MAP_FUGITIVES_SNOW_FOREST] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_DIRECTION,
        .mapFileTableId = MAP_FILE_ID_FUGITIVES_SNOW_FOREST,
        .unk6 = 10,
        .text = _("__ground_amd_conversion_00178"),
    },
    [MAP_FUGITIVES_BLIZZARD_ROAD] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_DIRECTION,
        .mapFileTableId = MAP_FILE_ID_FUGITIVES_BLIZZARD_ROAD,
        .unk6 = 12,
        .text = _("__ground_amd_conversion_00179"),
    },
    [MAP_SUMMIT_SUNSET] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_HILL_OF_THE_ANCIENTS,
        .mapFileTableId = MAP_FILE_ID_SUMMIT_SUNSET,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00180"),
    },
    [MAP_SKY_TOWER] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_DIRECTION,
        .mapFileTableId = MAP_FILE_ID_SKY_TOWER,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00181"),
    },
    [MAP_COMET] = {
        .unk0 = 9,
        .groundPlaceId = GROUND_PLACE_DIRECTION,
        .mapFileTableId = MAP_FILE_ID_COMET,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00182"),
    },
    [MAP_NIGHTMARE] = {
        .unk0 = 6,
        .groundPlaceId = GROUND_PLACE_DIRECTION,
        .mapFileTableId = MAP_FILE_ID_NIGHTMARE,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00183"),
    },
    [MAP_NIGHT_SKY_1] = {
        .unk0 = 9,
        .groundPlaceId = GROUND_PLACE_DIRECTION,
        .mapFileTableId = MAP_FILE_ID_NIGHT_SKY_1,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00184"),
    },
    [MAP_NIGHT_SKY_2] = {
        .unk0 = 4,
        .groundPlaceId = GROUND_PLACE_DIRECTION,
        .mapFileTableId = MAP_FILE_ID_NIGHT_SKY_2,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00185"),
    },
    [MAP_THE_END] = {
        .unk0 = 4,
        .groundPlaceId = GROUND_PLACE_DIRECTION,
        .mapFileTableId = MAP_FILE_ID_THE_END,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00186"),
    },
    [MAP_TINY_WOODS_ENTRY] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TINY_WOODS,
        .mapFileTableId = MAP_FILE_ID_TINY_WOODS_ENTRY,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00187"),
    },
    [MAP_TINY_WOODS_END] = {
        .unk0 = 10,
        .groundPlaceId = GROUND_PLACE_TINY_WOODS,
        .mapFileTableId = MAP_FILE_ID_TINY_WOODS_END,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00188"),
    },
    [MAP_THUNDERWAVE_CAVE_ENTRY] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_THUNDERWAVE_CAVE,
        .mapFileTableId = MAP_FILE_ID_THUNDERWAVE_CAVE_ENTRY,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00189"),
    },
    [MAP_THUNDERWAVE_CAVE_END] = {
        .unk0 = 10,
        .groundPlaceId = GROUND_PLACE_DUNGEON,
        .mapFileTableId = MAP_FILE_ID_THUNDERWAVE_CAVE_END,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00190"),
    },
    [MAP_MT_STEEL_ENTRY] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_MT_STEEL,
        .mapFileTableId = MAP_FILE_ID_MT_STEEL_ENTRY,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00191"),
    },
    [MAP_MT_STEEL_END] = {
        .unk0 = 11,
        .groundPlaceId = GROUND_PLACE_DUNGEON,
        .mapFileTableId = MAP_FILE_ID_MT_STEEL_END,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00192"),
    },
    [MAP_SINISTER_WOODS_ENTRY] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_SINISTER_WOODS,
        .mapFileTableId = MAP_FILE_ID_SINISTER_WOODS_ENTRY,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00193"),
    },
    [MAP_SINISTER_WOODS_END] = {
        .unk0 = 11,
        .groundPlaceId = GROUND_PLACE_DUNGEON,
        .mapFileTableId = MAP_FILE_ID_SINISTER_WOODS_END,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00194"),
    },
    [MAP_SILENT_CHASM_ENTRY] = {
        .unk0 = 6,
        .groundPlaceId = GROUND_PLACE_SILENT_CHASM,
        .mapFileTableId = MAP_FILE_ID_SILENT_CHASM_ENTRY,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00195"),
    },
    [MAP_SILENT_CHASM_END] = {
        .unk0 = 10,
        .groundPlaceId = GROUND_PLACE_DUNGEON,
        .mapFileTableId = MAP_FILE_ID_SILENT_CHASM_END,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00196"),
    },
    [MAP_MT_THUNDER_ENTRY] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_MT_THUNDER,
        .mapFileTableId = MAP_FILE_ID_MT_THUNDER_ENTRY,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00197"),
    },
    [MAP_MT_THUNDER_MID] = {
        .unk0 = 10,
        .groundPlaceId = GROUND_PLACE_MT_THUNDER_MID,
        .mapFileTableId = MAP_FILE_ID_MT_THUNDER_MID,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00198"),
    },
    [MAP_MT_THUNDER_END] = {
        .unk0 = 11,
        .groundPlaceId = GROUND_PLACE_DUNGEON,
        .mapFileTableId = MAP_FILE_ID_MT_THUNDER_END,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00199"),
    },
    [MAP_GREAT_CANYON_ENTRY] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_GREAT_CANYON,
        .mapFileTableId = MAP_FILE_ID_GREAT_CANYON_ENTRY,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00200"),
    },
    [MAP_HILL_OF_THE_ANCIENTS] = {
        .unk0 = 3,
        .groundPlaceId = GROUND_PLACE_HILL_OF_THE_ANCIENTS,
        .mapFileTableId = MAP_FILE_ID_HILL_OF_THE_ANCIENTS,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00201"),
    },
    [MAP_LAPIS_CAVE_ENTRY] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_LAPIS_CAVE,
        .mapFileTableId = MAP_FILE_ID_LAPIS_CAVE_ENTRY,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00202"),
    },
    [MAP_LAPIS_CAVE_END] = {
        .unk0 = 3,
        .groundPlaceId = GROUND_PLACE_LAPIS_CAVE_EXIT,
        .mapFileTableId = MAP_FILE_ID_LAPIS_CAVE_END,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00203"),
    },
    [MAP_MT_BLAZE_ENTRY] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_MT_BLAZE,
        .mapFileTableId = MAP_FILE_ID_MT_BLAZE_ENTRY,
        .unk6 = 13,
        .text = _("__ground_amd_conversion_00204"),
    },
    [MAP_MT_BLAZE_MID] = {
        .unk0 = 10,
        .groundPlaceId = GROUND_PLACE_MT_BLAZE_MID,
        .mapFileTableId = MAP_FILE_ID_MT_BLAZE_MID,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00205"),
    },
    [MAP_MT_BLAZE_END] = {
        .unk0 = 11,
        .groundPlaceId = GROUND_PLACE_DUNGEON,
        .mapFileTableId = MAP_FILE_ID_MT_BLAZE_END,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00206"),
    },
    [MAP_FROSTY_FOREST_ENTRY] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FROSTY_FOREST,
        .mapFileTableId = MAP_FILE_ID_FROSTY_FOREST_ENTRY,
        .unk6 = 10,
        .text = _("__ground_amd_conversion_00207"),
    },
    [MAP_FROSTY_FOREST_MID] = {
        .unk0 = 10,
        .groundPlaceId = GROUND_PLACE_FROSTY_CLEARING,
        .mapFileTableId = MAP_FILE_ID_FROSTY_FOREST_MID,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00208"),
    },
    [MAP_FROSTY_FOREST_END] = {
        .unk0 = 11,
        .groundPlaceId = GROUND_PLACE_DUNGEON,
        .mapFileTableId = MAP_FILE_ID_FROSTY_FOREST_END,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00209"),
    },
    [MAP_MT_FREEZE_ENTRY] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_MT_FREEZE,
        .mapFileTableId = MAP_FILE_ID_MT_FREEZE_ENTRY,
        .unk6 = 10,
        .text = _("__ground_amd_conversion_00210"),
    },
    [MAP_MT_FREEZE_MID] = {
        .unk0 = 10,
        .groundPlaceId = GROUND_PLACE_MT_FREEZE_MID,
        .mapFileTableId = MAP_FILE_ID_MT_FREEZE_MID,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00211"),
    },
    [MAP_MT_FREEZE_END] = {
        .unk0 = 11,
        .groundPlaceId = GROUND_PLACE_DUNGEON,
        .mapFileTableId = MAP_FILE_ID_MT_FREEZE_END,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00212"),
    },
    [MAP_MAGMA_CAVERN_ENTRY] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_MAGMA_CAVERN,
        .mapFileTableId = MAP_FILE_ID_MAGMA_CAVERN_ENTRY,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00213"),
    },
    [MAP_MAGMA_CAVERN_MID] = {
        .unk0 = 10,
        .groundPlaceId = GROUND_PLACE_MAGMA_CAVERN_MID,
        .mapFileTableId = MAP_FILE_ID_MAGMA_CAVERN_MID,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00214"),
    },
    [MAP_MAGMA_CAVERN_END] = {
        .unk0 = 11,
        .groundPlaceId = GROUND_PLACE_DUNGEON,
        .mapFileTableId = MAP_FILE_ID_MAGMA_CAVERN_END,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00215"),
    },
    [MAP_SKY_TOWER_ENTRY] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_SKY_TOWER,
        .mapFileTableId = MAP_FILE_ID_SKY_TOWER_ENTRY,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00216"),
    },
    [MAP_SKY_TOWER_MID] = {
        .unk0 = 10,
        .groundPlaceId = GROUND_PLACE_SKY_TOWER_MID,
        .mapFileTableId = MAP_FILE_ID_SKY_TOWER_MID,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00217"),
    },
    [MAP_SKY_TOWER_END] = {
        .unk0 = 11,
        .groundPlaceId = GROUND_PLACE_DUNGEON,
        .mapFileTableId = MAP_FILE_ID_SKY_TOWER_END,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00218"),
    },
    [MAP_D14] = {
        .unk0 = 11,
        .groundPlaceId = GROUND_PLACE_DUNGEON,
        .mapFileTableId = MAP_FILE_ID_D14,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00219"),
    },
    [MAP_D15] = {
        .unk0 = 11,
        .groundPlaceId = GROUND_PLACE_DUNGEON,
        .mapFileTableId = MAP_FILE_ID_D15,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00220"),
    },
    [MAP_D16] = {
        .unk0 = 10,
        .groundPlaceId = GROUND_PLACE_DUNGEON,
        .mapFileTableId = MAP_FILE_ID_D16,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00221"),
    },
    [MAP_D17] = {
        .unk0 = 10,
        .groundPlaceId = GROUND_PLACE_DUNGEON,
        .mapFileTableId = MAP_FILE_ID_D17,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00222"),
    },
    [MAP_D18] = {
        .unk0 = 10,
        .groundPlaceId = GROUND_PLACE_DUNGEON,
        .mapFileTableId = MAP_FILE_ID_D18,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00223"),
    },
    [MAP_D19] = {
        .unk0 = 11,
        .groundPlaceId = GROUND_PLACE_DUNGEON,
        .mapFileTableId = MAP_FILE_ID_D19,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00224"),
    },
    [MAP_D20] = {
        .unk0 = 10,
        .groundPlaceId = GROUND_PLACE_WESTERN_CAVE,
        .mapFileTableId = MAP_FILE_ID_D20,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00225"),
    },
    [MAP_D21] = {
        .unk0 = 11,
        .groundPlaceId = GROUND_PLACE_DUNGEON,
        .mapFileTableId = MAP_FILE_ID_D21,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00226"),
    },
    [MAP_D22] = {
        .unk0 = 3,
        .groundPlaceId = GROUND_PLACE_DUNGEON,
        .mapFileTableId = MAP_FILE_ID_D22,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00227"),
    },
    [MAP_D23] = {
        .unk0 = 10,
        .groundPlaceId = GROUND_PLACE_DUNGEON,
        .mapFileTableId = MAP_FILE_ID_D23,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00228"),
    },
    [MAP_D24_1] = {
        .unk0 = 3,
        .groundPlaceId = GROUND_PLACE_DUNGEON,
        .mapFileTableId = MAP_FILE_ID_D24_1,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00229"),
    },
    [MAP_D24_2] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_DUNGEON,
        .mapFileTableId = MAP_FILE_ID_D24_2,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00230"),
    },
    [MAP_D25] = {
        .unk0 = 10,
        .groundPlaceId = GROUND_PLACE_DUNGEON,
        .mapFileTableId = MAP_FILE_ID_D25,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00231"),
    },
    [MAP_PERSONALITY_TEST_MULTICOLOR] = {
        .unk0 = 9,
        .groundPlaceId = GROUND_PLACE_SCENE,
        .mapFileTableId = MAP_FILE_ID_PERSONALITY_TEST_MULTICOLOR,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00232"),
    },
    [MAP_TITLE_SCREEN] = {
        .unk0 = 9,
        .groundPlaceId = GROUND_PLACE_SCENE,
        .mapFileTableId = MAP_FILE_ID_TITLE_SCREEN,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00233"),
    },
    [MAP_INTRO] = {
        .unk0 = 4,
        .groundPlaceId = GROUND_PLACE_SCENE,
        .mapFileTableId = MAP_FILE_ID_INTRO,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00235"),
    },
    [MAP_LOGO_POKEMON_COMPANY] = {
        .unk0 = 4,
        .groundPlaceId = GROUND_PLACE_SCENE,
        .mapFileTableId = MAP_FILE_ID_LOGO_POKEMON_COMPANY,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00237"),
    },
    [MAP_LOGO_WARNING] = {
        .unk0 = 4,
        .groundPlaceId = GROUND_PLACE_SCENE,
        .mapFileTableId = MAP_FILE_ID_LOGO_WARNING,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00239"),
    },
    [MAP_TEAM_BASE_WALL_MAP] = {
        .unk0 = 4,
        .groundPlaceId = GROUND_PLACE_SCENE,
        .mapFileTableId = MAP_FILE_ID_TEAM_BASE_WALL_MAP,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00240"),
    },
};
