#include "global.h"
#include "globaldata.h"
#include "ground_map_conversion_table.h"
#include "ground_place.h"
#include "constants/ground_map.h"

const GroundConversionStruct gGroundMapConversionTable[MAP_COUNT] = {
    [MAP_SQUARE] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_SQUARE,
        .mapFileTableId = 0,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00000"),
    },
    [MAP_POKEMON_SQUARE] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_POKEMON_SQUARE,
        .mapFileTableId = 1,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00001"),
    },
    [MAP_WHISCASH_POND] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_WHISCASH_POND,
        .mapFileTableId = 2,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00002"),
    },
    [MAP_WHISCASH_POND_OPEN] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_WHISCASH_POND,
        .mapFileTableId = 3,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00003"),
    },
    [MAP_PELIPPER_POST_OFFICE] = {
        .unk0 = 5,
        .groundPlaceId = GROUND_PLACE_PELIPPER_POST_OFFICE,
        .mapFileTableId = 4,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00004"),
    },
    [MAP_PELIPPER_POST_OFFICE_INSIDE] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_PELIPPER_POST_OFFICE_INSIDE,
        .mapFileTableId = 5,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00005"),
    },
    [MAP_MAKUHITA_DOJO] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_MAKUHITA_DOJO,
        .mapFileTableId = 6,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00006"),
    },
    [MAP_MAKUHITA_DOJO_INSIDE] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_MAKUHITA_DOJO_INSIDE,
        .mapFileTableId = 7,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00007"),
    },
    [MAP_LUMINOUS_CAVE] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_LUMINOUS_CAVE,
        .mapFileTableId = 8,
        .unk6 = 0,
        .text = _("__ground_amd_conversion_00008"),
    },
    [MAP_TEAM_BASE_PIKACHU_BASIC] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = 10,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00010"),
    },
    [MAP_TEAM_BASE_PIKACHU_CONSTRUCTION] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = 11,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00011"),
    },
    [MAP_TEAM_BASE_PIKACHU_FINAL] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = 12,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00012"),
    },
    [MAP_TEAM_BASE_INSIDE_PIKACHU_BASIC] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = 13,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00013"),
    },
    [MAP_TEAM_BASE_INSIDE_PIKACHU_CONSTRUCTION] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = 14,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00014"),
    },
    [MAP_TEAM_BASE_INSIDE_PIKACHU_FINAL] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = 15,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00015"),
    },
    [MAP_TEAM_BASE_MEOWTH_BASIC] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = 16,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00016"),
    },
    [MAP_TEAM_BASE_MEOWTH_CONSTRUCTION] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = 17,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00017"),
    },
    [MAP_TEAM_BASE_MEOWTH_FINAL] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = 18,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00018"),
    },
    [MAP_TEAM_BASE_INSIDE_MEOWTH_BASIC] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = 19,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00019"),
    },
    [MAP_TEAM_BASE_INSIDE_MEOWTH_CONSTRUCTION] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = 20,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00020"),
    },
    [MAP_TEAM_BASE_INSIDE_MEOWTH_FINAL] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = 21,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00021"),
    },
    [MAP_TEAM_BASE_EEVEE_BASIC] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = 22,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00022"),
    },
    [MAP_TEAM_BASE_EEVEE_CONSTRUCTION] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = 23,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00023"),
    },
    [MAP_TEAM_BASE_EEVEE_FINAL] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = 24,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00024"),
    },
    [MAP_TEAM_BASE_INSIDE_EEVEE_BASIC] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = 25,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00025"),
    },
    [MAP_TEAM_BASE_INSIDE_EEVEE_CONSTRUCTION] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = 26,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00026"),
    },
    [MAP_TEAM_BASE_INSIDE_EEVEE_FINAL] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = 27,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00027"),
    },
    [MAP_TEAM_BASE_SKITTY_BASIC] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = 28,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00028"),
    },
    [MAP_TEAM_BASE_SKITTY_CONSTRUCTION] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = 29,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00029"),
    },
    [MAP_TEAM_BASE_SKITTY_FINAL] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = 30,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00030"),
    },
    [MAP_TEAM_BASE_INSIDE_SKITTY_BASIC] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = 31,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00031"),
    },
    [MAP_TEAM_BASE_INSIDE_SKITTY_CONSTRUCTION] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = 32,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00032"),
    },
    [MAP_TEAM_BASE_INSIDE_SKITTY_FINAL] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = 33,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00033"),
    },
    [MAP_TEAM_BASE_SQUIRTLE_BASIC] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = 34,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00034"),
    },
    [MAP_TEAM_BASE_SQUIRTLE_CONSTRUCTION] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = 35,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00035"),
    },
    [MAP_TEAM_BASE_SQUIRTLE_FINAL] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = 36,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00036"),
    },
    [MAP_TEAM_BASE_INSIDE_SQUIRTLE_BASIC] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = 37,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00037"),
    },
    [MAP_TEAM_BASE_INSIDE_SQUIRTLE_CONSTRUCTION] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = 38,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00038"),
    },
    [MAP_TEAM_BASE_INSIDE_SQUIRTLE_FINAL] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = 39,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00039"),
    },
    [MAP_TEAM_BASE_TOTODILE_BASIC] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = 40,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00040"),
    },
    [MAP_TEAM_BASE_TOTODILE_CONSTRUCTION] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = 41,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00041"),
    },
    [MAP_TEAM_BASE_TOTODILE_FINAL] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = 42,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00042"),
    },
    [MAP_TEAM_BASE_INSIDE_TOTODILE_BASIC] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = 43,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00043"),
    },
    [MAP_TEAM_BASE_INSIDE_TOTODILE_CONSTRUCTION] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = 44,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00044"),
    },
    [MAP_TEAM_BASE_INSIDE_TOTODILE_FINAL] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = 45,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00045"),
    },
    [MAP_TEAM_BASE_MUDKIP_BASIC] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = 46,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00046"),
    },
    [MAP_TEAM_BASE_MUDKIP_CONSTRUCTION] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = 47,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00047"),
    },
    [MAP_TEAM_BASE_MUDKIP_FINAL] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = 48,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00048"),
    },
    [MAP_TEAM_BASE_INSIDE_MUDKIP_BASIC] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = 49,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00049"),
    },
    [MAP_TEAM_BASE_INSIDE_MUDKIP_CONSTRUCTION] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = 50,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00050"),
    },
    [MAP_TEAM_BASE_INSIDE_MUDKIP_FINAL] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = 51,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00051"),
    },
    [MAP_TEAM_BASE_PSYDUCK_BASIC] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = 52,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00052"),
    },
    [MAP_TEAM_BASE_PSYDUCK_CONSTRUCTION] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = 53,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00053"),
    },
    [MAP_TEAM_BASE_PSYDUCK_FINAL] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = 54,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00054"),
    },
    [MAP_TEAM_BASE_INSIDE_PSYDUCK_BASIC] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = 55,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00055"),
    },
    [MAP_TEAM_BASE_INSIDE_PSYDUCK_CONSTRUCTION] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = 56,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00056"),
    },
    [MAP_TEAM_BASE_INSIDE_PSYDUCK_FINAL] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = 57,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00057"),
    },
    [MAP_TEAM_BASE_CHARMANDER_BASIC] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = 58,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00058"),
    },
    [MAP_TEAM_BASE_CHARMANDER_CONSTRUCTION] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = 59,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00059"),
    },
    [MAP_TEAM_BASE_CHARMANDER_FINAL] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = 60,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00060"),
    },
    [MAP_TEAM_BASE_INSIDE_CHARMANDER_BASIC] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = 61,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00061"),
    },
    [MAP_TEAM_BASE_INSIDE_CHARMANDER_CONSTRUCTION] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = 62,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00062"),
    },
    [MAP_TEAM_BASE_INSIDE_CHARMANDER_FINAL] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = 63,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00063"),
    },
    [MAP_TEAM_BASE_TORCHIC_BASIC] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = 64,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00064"),
    },
    [MAP_TEAM_BASE_TORCHIC_CONSTRUCTION] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = 65,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00065"),
    },
    [MAP_TEAM_BASE_TORCHIC_FINAL] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = 66,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00066"),
    },
    [MAP_TEAM_BASE_INSIDE_TORCHIC_BASIC] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = 67,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00067"),
    },
    [MAP_TEAM_BASE_INSIDE_TORCHIC_CONSTRUCTION] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = 68,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00068"),
    },
    [MAP_TEAM_BASE_INSIDE_TORCHIC_FINAL] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = 69,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00069"),
    },
    [MAP_TEAM_BASE_CYNDAQUIL_BASIC] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = 70,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00070"),
    },
    [MAP_TEAM_BASE_CYNDAQUIL_CONSTRUCTION] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = 71,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00071"),
    },
    [MAP_TEAM_BASE_CYNDAQUIL_FINAL] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = 72,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00072"),
    },
    [MAP_TEAM_BASE_INSIDE_CYNDAQUIL_BASIC] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = 73,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00073"),
    },
    [MAP_TEAM_BASE_INSIDE_CYNDAQUIL_CONSTRUCTION] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = 74,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00074"),
    },
    [MAP_TEAM_BASE_INSIDE_CYNDAQUIL_FINAL] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = 75,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00075"),
    },
    [MAP_TEAM_BASE_CUBONE_BASIC] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = 76,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00076"),
    },
    [MAP_TEAM_BASE_CUBONE_CONSTRUCTION] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = 77,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00077"),
    },
    [MAP_TEAM_BASE_CUBONE_FINAL] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = 78,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00078"),
    },
    [MAP_TEAM_BASE_INSIDE_CUBONE_BASIC] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = 79,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00079"),
    },
    [MAP_TEAM_BASE_INSIDE_CUBONE_CONSTRUCTION] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = 80,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00080"),
    },
    [MAP_TEAM_BASE_INSIDE_CUBONE_FINAL] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = 81,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00081"),
    },
    [MAP_TEAM_BASE_MACHOP_BASIC] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = 82,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00082"),
    },
    [MAP_TEAM_BASE_MACHOP_CONSTRUCTION] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = 83,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00083"),
    },
    [MAP_TEAM_BASE_MACHOP_FINAL] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = 84,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00084"),
    },
    [MAP_TEAM_BASE_INSIDE_MACHOP_BASIC] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = 85,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00085"),
    },
    [MAP_TEAM_BASE_INSIDE_MACHOP_CONSTRUCTION] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = 86,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00086"),
    },
    [MAP_TEAM_BASE_INSIDE_MACHOP_FINAL] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = 87,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00087"),
    },
    [MAP_TEAM_BASE_BULBASAUR_BASIC] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = 88,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00088"),
    },
    [MAP_TEAM_BASE_BULBASAUR_CONSTRUCTION] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = 89,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00089"),
    },
    [MAP_TEAM_BASE_BULBASAUR_FINAL] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = 90,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00090"),
    },
    [MAP_TEAM_BASE_INSIDE_BULBASAUR_BASIC] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = 91,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00091"),
    },
    [MAP_TEAM_BASE_INSIDE_BULBASAUR_CONSTRUCTION] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = 92,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00092"),
    },
    [MAP_TEAM_BASE_INSIDE_BULBASAUR_FINAL] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = 93,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00093"),
    },
    [MAP_TEAM_BASE_CHIKORITA_BASIC] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = 94,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00094"),
    },
    [MAP_TEAM_BASE_CHIKORITA_CONSTRUCTION] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = 95,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00095"),
    },
    [MAP_TEAM_BASE_CHIKORITA_FINAL] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = 96,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00096"),
    },
    [MAP_TEAM_BASE_INSIDE_CHIKORITA_BASIC] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = 97,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00097"),
    },
    [MAP_TEAM_BASE_INSIDE_CHIKORITA_CONSTRUCTION] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = 98,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00098"),
    },
    [MAP_TEAM_BASE_INSIDE_CHIKORITA_FINAL] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = 99,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00099"),
    },
    [MAP_TEAM_BASE_TREECKO_BASIC] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = 100,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00100"),
    },
    [MAP_TEAM_BASE_TREECKO_CONSTRUCTION] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = 101,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00101"),
    },
    [MAP_TEAM_BASE_TREECKO_FINAL] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE,
        .mapFileTableId = 102,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00102"),
    },
    [MAP_TEAM_BASE_INSIDE_TREECKO_BASIC] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = 103,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00103"),
    },
    [MAP_TEAM_BASE_INSIDE_TREECKO_CONSTRUCTION] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = 104,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00104"),
    },
    [MAP_TEAM_BASE_INSIDE_TREECKO_FINAL] = {
        .unk0 = 2,
        .groundPlaceId = GROUND_PLACE_TEAM_BASE_INSIDE,
        .mapFileTableId = 105,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00105"),
    },
    [MAP_FRIEND_AREA_BOUNTIFUL_SEA] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = 106,
        .unk6 = 1,
        .text = _("__ground_amd_conversion_00106"),
    },
    [MAP_FRIEND_AREA_TREASURE_SEA] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = 108,
        .unk6 = 14,
        .text = _("__ground_amd_conversion_00108"),
    },
    [MAP_FRIEND_AREA_SERENE_SEA] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = 109,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00109"),
    },
    [MAP_FRIEND_AREA_DEEP_SEA_FLOOR] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = 110,
        .unk6 = 2,
        .text = _("__ground_amd_conversion_00110"),
    },
    [MAP_FRIEND_AREA_DEEP_SEA_CURRENT] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = 112,
        .unk6 = 3,
        .text = _("__ground_amd_conversion_00112"),
    },
    [MAP_FRIEND_AREA_SEAFLOOR_CAVE] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = 114,
        .unk6 = 4,
        .text = _("__ground_amd_conversion_00114"),
    },
    [MAP_FRIEND_AREA_SHALLOW_BEACH] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = 116,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00116"),
    },
    [MAP_FRIEND_AREA_MT_DEEPGREEN] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = 117,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00117"),
    },
    [MAP_FRIEND_AREA_MT_CLEFT] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = 118,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00118"),
    },
    [MAP_FRIEND_AREA_MT_MOONVIEW] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = 119,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00119"),
    },
    [MAP_FRIEND_AREA_RAINBOW_PEAK] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = 120,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00120"),
    },
    [MAP_FRIEND_AREA_WILD_PLAINS] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = 121,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00121"),
    },
    [MAP_FRIEND_AREA_BEAU_PLAINS] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = 122,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00122"),
    },
    [MAP_FRIEND_AREA_SKY_BLUE_PLAINS] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = 123,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00123"),
    },
    [MAP_FRIEND_AREA_SAFARI] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = 124,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00124"),
    },
    [MAP_FRIEND_AREA_SCORCHED_PLAINS] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = 125,
        .unk6 = 13,
        .text = _("__ground_amd_conversion_00125"),
    },
    [MAP_FRIEND_AREA_SACRED_FIELD] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = 126,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00126"),
    },
    [MAP_FRIEND_AREA_MIST_RISE_FOREST] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = 127,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00127"),
    },
    [MAP_FRIEND_AREA_FLYAWAY_FOREST] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = 128,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00128"),
    },
    [MAP_FRIEND_AREA_OVERGROWN_FOREST] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = 129,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00129"),
    },
    [MAP_FRIEND_AREA_ENERGETIC_FOREST] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = 130,
        .unk6 = 5,
        .text = _("__ground_amd_conversion_00130"),
    },
    [MAP_FRIEND_AREA_MUSHROOM_FOREST] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = 132,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00132"),
    },
    [MAP_FRIEND_AREA_HEALING_FOREST] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = 133,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00133"),
    },
    [MAP_FRIEND_AREA_TRANSFORM_FOREST] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = 134,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00134"),
    },
    [MAP_FRIEND_AREA_SECRETIVE_FOREST] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = 135,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00135"),
    },
    [MAP_FRIEND_AREA_RUB_A_DUB_RIVER] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = 136,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00136"),
    },
    [MAP_FRIEND_AREA_TADPOLE_POND] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = 137,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00137"),
    },
    [MAP_FRIEND_AREA_TURTLESHELL_POND] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = 138,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00138"),
    },
    [MAP_FRIEND_AREA_MYSTIC_LAKE] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = 139,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00139"),
    },
    [MAP_FRIEND_AREA_WATERFALL_LAKE] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = 140,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00140"),
    },
    [MAP_FRIEND_AREA_PEANUT_SWAMP] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = 141,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00141"),
    },
    [MAP_FRIEND_AREA_POISON_SWAMP] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = 142,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00142"),
    },
    [MAP_FRIEND_AREA_ECHO_CAVE] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = 143,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00143"),
    },
    [MAP_FRIEND_AREA_CRYPTIC_CAVE] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = 144,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00144"),
    },
    [MAP_FRIEND_AREA_DRAGON_CAVE] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = 145,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00145"),
    },
    [MAP_FRIEND_AREA_BOULDER_CAVE] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = 146,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00146"),
    },
    [MAP_FRIEND_AREA_JUNGLE] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = 147,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00147"),
    },
    [MAP_FRIEND_AREA_DECREPIT_LAB] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = 148,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00148"),
    },
    [MAP_FRIEND_AREA_MT_DISCIPLINE] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = 149,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00149"),
    },
    [MAP_FRIEND_AREA_THUNDER_MEADOW] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = 150,
        .unk6 = 6,
        .text = _("__ground_amd_conversion_00150"),
    },
    [MAP_FRIEND_AREA_POWER_PLANT] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = 152,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00152"),
    },
    [MAP_FRIEND_AREA_CRATER] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = 153,
        .unk6 = 7,
        .text = _("__ground_amd_conversion_00153"),
    },
    [MAP_FRIEND_AREA_FURNACE_DESERT] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = 155,
        .unk6 = 14,
        .text = _("__ground_amd_conversion_00155"),
    },
    [MAP_FRIEND_AREA_AGED_CHAMBER_AN] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = 156,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00156"),
    },
    [MAP_FRIEND_AREA_AGED_CHAMBER_O_EXCLAIM] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = 157,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00157"),
    },
    [MAP_FRIEND_AREA_ANCIENT_RELIC] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = 158,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00158"),
    },
    [MAP_FRIEND_AREA_DARKNESS_RIDGE] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = 159,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00159"),
    },
    [MAP_FRIEND_AREA_FRIGID_CAVERN] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = 160,
        .unk6 = 10,
        .text = _("__ground_amd_conversion_00160"),
    },
    [MAP_FRIEND_AREA_ICE_FLOE_BEACH] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = 161,
        .unk6 = 12,
        .text = _("__ground_amd_conversion_00161"),
    },
    [MAP_FRIEND_AREA_VOLCANIC_PIT] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = 162,
        .unk6 = 13,
        .text = _("__ground_amd_conversion_00162"),
    },
    [MAP_FRIEND_AREA_STRATOS_LOOKOUT] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = 163,
        .unk6 = 14,
        .text = _("__ground_amd_conversion_00163"),
    },
    [MAP_FRIEND_AREA_RAVAGED_FIELD] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = 164,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00164"),
    },
    [MAP_FRIEND_AREA_MAGNETIC_QUARRY] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = 165,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00165"),
    },
    [MAP_FRIEND_AREA_LEGENDARY_ISLAND] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = 166,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00166"),
    },
    [MAP_FRIEND_AREA_SOUTHERN_ISLAND] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = 167,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00167"),
    },
    [MAP_FRIEND_AREA_ENCLOSED_ISLAND] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = 168,
        .unk6 = 8,
        .text = _("__ground_amd_conversion_00168"),
    },
    [MAP_FRIEND_AREA_FINAL_ISLAND] = {
        .unk0 = 5,
        .groundPlaceId = GROUND_PLACE_FRIEND_AREAS,
        .mapFileTableId = 170,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00170"),
    },
    [MAP_PERSONALITY_TEST_CYAN] = {
        .unk0 = 9,
        .groundPlaceId = GROUND_PLACE_DIRECTION,
        .mapFileTableId = 171,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00171"),
    },
    [MAP_PERSONALITY_TEST_PURPLE] = {
        .unk0 = 9,
        .groundPlaceId = GROUND_PLACE_DIRECTION,
        .mapFileTableId = 172,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00172"),
    },
    [MAP_FUGITIVES_FISSURE] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_DIRECTION,
        .mapFileTableId = 173,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00173"),
    },
    [MAP_FUGITIVES_FIRE] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_DIRECTION,
        .mapFileTableId = 174,
        .unk6 = 13,
        .text = _("__ground_amd_conversion_00174"),
    },
    [MAP_FUGITIVES_LAPIS_CAVE] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_DIRECTION,
        .mapFileTableId = 175,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00175"),
    },
    [MAP_FUGITIVES_VOLCANO] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_DIRECTION,
        .mapFileTableId = 176,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00176"),
    },
    [MAP_FUGITIVES_SNOW_ROAD] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_DIRECTION,
        .mapFileTableId = 177,
        .unk6 = 10,
        .text = _("__ground_amd_conversion_00177"),
    },
    [MAP_FUGITIVES_SNOW_FOREST] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_DIRECTION,
        .mapFileTableId = 178,
        .unk6 = 10,
        .text = _("__ground_amd_conversion_00178"),
    },
    [MAP_FUGITIVES_BLIZZARD_ROAD] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_DIRECTION,
        .mapFileTableId = 179,
        .unk6 = 12,
        .text = _("__ground_amd_conversion_00179"),
    },
    [MAP_SUMMIT_SUNSET] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_HILL_OF_THE_ANCIENTS,
        .mapFileTableId = 180,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00180"),
    },
    [MAP_SKY_TOWER] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_DIRECTION,
        .mapFileTableId = 181,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00181"),
    },
    [MAP_COMET] = {
        .unk0 = 9,
        .groundPlaceId = GROUND_PLACE_DIRECTION,
        .mapFileTableId = 182,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00182"),
    },
    [MAP_NIGHTMARE] = {
        .unk0 = 6,
        .groundPlaceId = GROUND_PLACE_DIRECTION,
        .mapFileTableId = 183,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00183"),
    },
    [MAP_NIGHT_SKY_1] = {
        .unk0 = 9,
        .groundPlaceId = GROUND_PLACE_DIRECTION,
        .mapFileTableId = 184,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00184"),
    },
    [MAP_NIGHT_SKY_2] = {
        .unk0 = 4,
        .groundPlaceId = GROUND_PLACE_DIRECTION,
        .mapFileTableId = 185,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00185"),
    },
    [MAP_THE_END] = {
        .unk0 = 4,
        .groundPlaceId = GROUND_PLACE_DIRECTION,
        .mapFileTableId = 186,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00186"),
    },
    [MAP_TINY_WOODS_ENTRY] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_TINY_WOODS,
        .mapFileTableId = 187,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00187"),
    },
    [MAP_TINY_WOODS_END] = {
        .unk0 = 10,
        .groundPlaceId = GROUND_PLACE_TINY_WOODS,
        .mapFileTableId = 188,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00188"),
    },
    [MAP_THUNDERWAVE_CAVE_ENTRY] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_THUNDERWAVE_CAVE,
        .mapFileTableId = 189,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00189"),
    },
    [MAP_THUNDERWAVE_CAVE_END] = {
        .unk0 = 10,
        .groundPlaceId = GROUND_PLACE_DUNGEON,
        .mapFileTableId = 190,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00190"),
    },
    [MAP_MT_STEEL_ENTRY] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_MT_STEEL,
        .mapFileTableId = 191,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00191"),
    },
    [MAP_MT_STEEL_END] = {
        .unk0 = 11,
        .groundPlaceId = GROUND_PLACE_DUNGEON,
        .mapFileTableId = 192,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00192"),
    },
    [MAP_SINISTER_WOODS_ENTRY] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_SINISTER_WOODS,
        .mapFileTableId = 193,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00193"),
    },
    [MAP_SINISTER_WOODS_END] = {
        .unk0 = 11,
        .groundPlaceId = GROUND_PLACE_DUNGEON,
        .mapFileTableId = 194,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00194"),
    },
    [MAP_SILENT_CHASM_ENTRY] = {
        .unk0 = 6,
        .groundPlaceId = GROUND_PLACE_SILENT_CHASM,
        .mapFileTableId = 195,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00195"),
    },
    [MAP_SILENT_CHASM_END] = {
        .unk0 = 10,
        .groundPlaceId = GROUND_PLACE_DUNGEON,
        .mapFileTableId = 196,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00196"),
    },
    [MAP_MT_THUNDER_ENTRY] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_MT_THUNDER,
        .mapFileTableId = 197,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00197"),
    },
    [MAP_MT_THUNDER_MID] = {
        .unk0 = 10,
        .groundPlaceId = GROUND_PLACE_MT_THUNDER_MID,
        .mapFileTableId = 198,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00198"),
    },
    [MAP_MT_THUNDER_END] = {
        .unk0 = 11,
        .groundPlaceId = GROUND_PLACE_DUNGEON,
        .mapFileTableId = 199,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00199"),
    },
    [MAP_GREAT_CANYON_ENTRY] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_GREAT_CANYON,
        .mapFileTableId = 200,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00200"),
    },
    [MAP_HILL_OF_THE_ANCIENTS] = {
        .unk0 = 3,
        .groundPlaceId = GROUND_PLACE_HILL_OF_THE_ANCIENTS,
        .mapFileTableId = 201,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00201"),
    },
    [MAP_LAPIS_CAVE_ENTRY] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_LAPIS_CAVE,
        .mapFileTableId = 202,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00202"),
    },
    [MAP_LAPIS_CAVE_END] = {
        .unk0 = 3,
        .groundPlaceId = GROUND_PLACE_LAPIS_CAVE_EXIT,
        .mapFileTableId = 203,
        .unk6 = 9,
        .text = _("__ground_amd_conversion_00203"),
    },
    [MAP_MT_BLAZE_ENTRY] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_MT_BLAZE,
        .mapFileTableId = 204,
        .unk6 = 13,
        .text = _("__ground_amd_conversion_00204"),
    },
    [MAP_MT_BLAZE_MID] = {
        .unk0 = 10,
        .groundPlaceId = GROUND_PLACE_MT_BLAZE_MID,
        .mapFileTableId = 205,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00205"),
    },
    [MAP_MT_BLAZE_END] = {
        .unk0 = 11,
        .groundPlaceId = GROUND_PLACE_DUNGEON,
        .mapFileTableId = 206,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00206"),
    },
    [MAP_FROSTY_FOREST_ENTRY] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_FROSTY_FOREST,
        .mapFileTableId = 207,
        .unk6 = 10,
        .text = _("__ground_amd_conversion_00207"),
    },
    [MAP_FROSTY_FOREST_MID] = {
        .unk0 = 10,
        .groundPlaceId = GROUND_PLACE_FROSTY_CLEARING,
        .mapFileTableId = 208,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00208"),
    },
    [MAP_FROSTY_FOREST_END] = {
        .unk0 = 11,
        .groundPlaceId = GROUND_PLACE_DUNGEON,
        .mapFileTableId = 209,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00209"),
    },
    [MAP_MT_FREEZE_ENTRY] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_MT_FREEZE,
        .mapFileTableId = 210,
        .unk6 = 10,
        .text = _("__ground_amd_conversion_00210"),
    },
    [MAP_MT_FREEZE_MID] = {
        .unk0 = 10,
        .groundPlaceId = GROUND_PLACE_MT_FREEZE_MID,
        .mapFileTableId = 211,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00211"),
    },
    [MAP_MT_FREEZE_END] = {
        .unk0 = 11,
        .groundPlaceId = GROUND_PLACE_DUNGEON,
        .mapFileTableId = 212,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00212"),
    },
    [MAP_MAGMA_CAVERN_ENTRY] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_MAGMA_CAVERN,
        .mapFileTableId = 213,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00213"),
    },
    [MAP_MAGMA_CAVERN_MID] = {
        .unk0 = 10,
        .groundPlaceId = GROUND_PLACE_MAGMA_CAVERN_MID,
        .mapFileTableId = 214,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00214"),
    },
    [MAP_MAGMA_CAVERN_END] = {
        .unk0 = 11,
        .groundPlaceId = GROUND_PLACE_DUNGEON,
        .mapFileTableId = 215,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00215"),
    },
    [MAP_SKY_TOWER_ENTRY] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_SKY_TOWER,
        .mapFileTableId = 216,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00216"),
    },
    [MAP_SKY_TOWER_MID] = {
        .unk0 = 10,
        .groundPlaceId = GROUND_PLACE_SKY_TOWER_MID,
        .mapFileTableId = 217,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00217"),
    },
    [MAP_SKY_TOWER_END] = {
        .unk0 = 11,
        .groundPlaceId = GROUND_PLACE_DUNGEON,
        .mapFileTableId = 218,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00218"),
    },
    [MAP_D14] = {
        .unk0 = 11,
        .groundPlaceId = GROUND_PLACE_DUNGEON,
        .mapFileTableId = 219,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00219"),
    },
    [MAP_D15] = {
        .unk0 = 11,
        .groundPlaceId = GROUND_PLACE_DUNGEON,
        .mapFileTableId = 220,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00220"),
    },
    [MAP_D16] = {
        .unk0 = 10,
        .groundPlaceId = GROUND_PLACE_DUNGEON,
        .mapFileTableId = 221,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00221"),
    },
    [MAP_D17] = {
        .unk0 = 10,
        .groundPlaceId = GROUND_PLACE_DUNGEON,
        .mapFileTableId = 222,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00222"),
    },
    [MAP_D18] = {
        .unk0 = 10,
        .groundPlaceId = GROUND_PLACE_DUNGEON,
        .mapFileTableId = 223,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00223"),
    },
    [MAP_D19] = {
        .unk0 = 11,
        .groundPlaceId = GROUND_PLACE_DUNGEON,
        .mapFileTableId = 224,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00224"),
    },
    [MAP_D20] = {
        .unk0 = 10,
        .groundPlaceId = GROUND_PLACE_WESTERN_CAVE,
        .mapFileTableId = 225,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00225"),
    },
    [MAP_D21] = {
        .unk0 = 11,
        .groundPlaceId = GROUND_PLACE_DUNGEON,
        .mapFileTableId = 226,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00226"),
    },
    [MAP_D22] = {
        .unk0 = 3,
        .groundPlaceId = GROUND_PLACE_DUNGEON,
        .mapFileTableId = 227,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00227"),
    },
    [MAP_D23] = {
        .unk0 = 10,
        .groundPlaceId = GROUND_PLACE_DUNGEON,
        .mapFileTableId = 228,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00228"),
    },
    [MAP_D24_1] = {
        .unk0 = 3,
        .groundPlaceId = GROUND_PLACE_DUNGEON,
        .mapFileTableId = 229,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00229"),
    },
    [MAP_D24_2] = {
        .unk0 = 1,
        .groundPlaceId = GROUND_PLACE_DUNGEON,
        .mapFileTableId = 230,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00230"),
    },
    [MAP_D25] = {
        .unk0 = 10,
        .groundPlaceId = GROUND_PLACE_DUNGEON,
        .mapFileTableId = 231,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00231"),
    },
    [MAP_PERSONALITY_TEST_MULTICOLOR] = {
        .unk0 = 9,
        .groundPlaceId = GROUND_PLACE_SCENE,
        .mapFileTableId = 232,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00232"),
    },
    [MAP_TITLE_SCREEN] = {
        .unk0 = 9,
        .groundPlaceId = GROUND_PLACE_SCENE,
        .mapFileTableId = 233,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00233"),
    },
    [MAP_INTRO] = {
        .unk0 = 4,
        .groundPlaceId = GROUND_PLACE_SCENE,
        .mapFileTableId = 234,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00235"),
    },
    [MAP_LOGO_POKEMON_COMPANY] = {
        .unk0 = 4,
        .groundPlaceId = GROUND_PLACE_SCENE,
        .mapFileTableId = 235,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00237"),
    },
    [MAP_LOGO_WARNING] = {
        .unk0 = 4,
        .groundPlaceId = GROUND_PLACE_SCENE,
        .mapFileTableId = 236,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00239"),
    },
    [MAP_TEAM_BASE_WALL_MAP] = {
        .unk0 = 4,
        .groundPlaceId = GROUND_PLACE_SCENE,
        .mapFileTableId = 237,
        .unk6 = -1,
        .text = _("__ground_amd_conversion_00240"),
    },
};
