#include "global.h"
#include "globaldata.h"
#include "map_files_table.h"

const struct MapFilesStruct gMapFilesTable[MAP_FILE_ID_COUNT] = {
    [MAP_FILE_ID_SQUARE] = {
        .bplFileName = "T00P01",
        .bpcFileName = "T00P01c",
        .bmaFileName = "T00P01m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_POKEMON_SQUARE] = {
        .bplFileName = "T01P01",
        .bpcFileName = "T01P01c",
        .bmaFileName = "T01P01m",
        .bpaFileNames = {"T01P011", NULL, NULL, NULL},
    },
    [MAP_FILE_ID_WHISCASH_POND] = {
        .bplFileName = "T01P02A",
        .bpcFileName = "T01P02c",
        .bmaFileName = "T01P02Am",
        .bpaFileNames = {"T01P021", NULL, NULL, NULL},
    },
    [MAP_FILE_ID_WHISCASH_POND_OPEN] = {
        .bplFileName = "T01P02B",
        .bpcFileName = "T01P02c",
        .bmaFileName = "T01P02Bm",
        .bpaFileNames = {"T01P021", NULL, NULL, NULL},
    },
    [MAP_FILE_ID_PELIPPER_POST_OFFICE] = {
        .bplFileName = "T01P03",
        .bpcFileName = "T01P03c",
        .bmaFileName = "T01P03m",
        .bpaFileNames = {"T01P031", NULL, NULL, NULL},
    },
    [MAP_FILE_ID_PELIPPER_POST_OFFICE_INSIDE] = {
        .bplFileName = "T01P04",
        .bpcFileName = "T01P04c",
        .bmaFileName = "T01P04m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_MAKUHITA_DOJO] = {
        .bplFileName = "T01P05",
        .bpcFileName = "T01P05c",
        .bmaFileName = "T01P05m",
        .bpaFileNames = {"T01P051", NULL, NULL, NULL},
    },
    [MAP_FILE_ID_MAKUHITA_DOJO_INSIDE] = {
        .bplFileName = "T01P06",
        .bpcFileName = "T01P06c",
        .bmaFileName = "T01P06m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_LUMINOUS_CAVE] = {
        .bplFileName = "T01P07",
        .bpcFileName = "T01P07c",
        .bmaFileName = "T01P07m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_UNK_9] = {
        .bplFileName = "T01P07W",
        .bpcFileName = "T01P07Wc",
        .bmaFileName = "T01P07Wm",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_PIKACHU_BASIC] = {
        .bplFileName = "B01P01A",
        .bpcFileName = "B01P01Ac",
        .bmaFileName = "B01P01Am",
        .bpaFileNames = {"B01P01A1", NULL, NULL, NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_PIKACHU_CONSTRUCTION] = {
        .bplFileName = "B01P01B",
        .bpcFileName = "B01P01Bc",
        .bmaFileName = "B01P01Bm",
        .bpaFileNames = {"B01P01B1", NULL, "B01P01B3", NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_PIKACHU_FINAL] = {
        .bplFileName = "B01P01C",
        .bpcFileName = "B01P01Cc",
        .bmaFileName = "B01P01Cm",
        .bpaFileNames = {"B01P01C1", NULL, NULL, NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_INSIDE_PIKACHU_BASIC] = {
        .bplFileName = "B01P02A",
        .bpcFileName = "B01P02c",
        .bmaFileName = "B01P02Am",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_INSIDE_PIKACHU_CONSTRUCTION] = {
        .bplFileName = "B01P02B",
        .bpcFileName = "B01P02c",
        .bmaFileName = "B01P02Bm",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_INSIDE_PIKACHU_FINAL] = {
        .bplFileName = "B01P02C",
        .bpcFileName = "B01P02Cc",
        .bmaFileName = "B01P02Cm",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_MEOWTH_BASIC] = {
        .bplFileName = "B02P01A",
        .bpcFileName = "B01P01Ac",
        .bmaFileName = "B01P01Am",
        .bpaFileNames = {"B01P01A1", NULL, NULL, NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_MEOWTH_CONSTRUCTION] = {
        .bplFileName = "B02P01B",
        .bpcFileName = "B01P01Bc",
        .bmaFileName = "B01P01Bm",
        .bpaFileNames = {"B01P01B1", NULL, "B02P01B3", NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_MEOWTH_FINAL] = {
        .bplFileName = "B02P01C",
        .bpcFileName = "B02P01Cc",
        .bmaFileName = "B02P01Cm",
        .bpaFileNames = {"B02P01C1", NULL, NULL, NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_INSIDE_MEOWTH_BASIC] = {
        .bplFileName = "B02P02A",
        .bpcFileName = "B01P02c",
        .bmaFileName = "B01P02Am",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_INSIDE_MEOWTH_CONSTRUCTION] = {
        .bplFileName = "B02P02B",
        .bpcFileName = "B01P02c",
        .bmaFileName = "B01P02Bm",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_INSIDE_MEOWTH_FINAL] = {
        .bplFileName = "B02P02C",
        .bpcFileName = "B01P02Cc",
        .bmaFileName = "B01P02Cm",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_EEVEE_BASIC] = {
        .bplFileName = "B03P01A",
        .bpcFileName = "B01P01Ac",
        .bmaFileName = "B01P01Am",
        .bpaFileNames = {"B01P01A1", NULL, NULL, NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_EEVEE_CONSTRUCTION] = {
        .bplFileName = "B03P01B",
        .bpcFileName = "B01P01Bc",
        .bmaFileName = "B01P01Bm",
        .bpaFileNames = {"B01P01B1", NULL, "B03P01B3", NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_EEVEE_FINAL] = {
        .bplFileName = "B03P01C",
        .bpcFileName = "B03P01Cc",
        .bmaFileName = "B03P01Cm",
        .bpaFileNames = {"B03P01C1", NULL, NULL, NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_INSIDE_EEVEE_BASIC] = {
        .bplFileName = "B03P02A",
        .bpcFileName = "B01P02c",
        .bmaFileName = "B01P02Am",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_INSIDE_EEVEE_CONSTRUCTION] = {
        .bplFileName = "B03P02B",
        .bpcFileName = "B01P02c",
        .bmaFileName = "B01P02Bm",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_INSIDE_EEVEE_FINAL] = {
        .bplFileName = "B03P02C",
        .bpcFileName = "B01P02Cc",
        .bmaFileName = "B01P02Cm",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_SKITTY_BASIC] = {
        .bplFileName = "B04P01A",
        .bpcFileName = "B01P01Ac",
        .bmaFileName = "B01P01Am",
        .bpaFileNames = {"B01P01A1", NULL, NULL, NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_SKITTY_CONSTRUCTION] = {
        .bplFileName = "B04P01B",
        .bpcFileName = "B01P01Bc",
        .bmaFileName = "B01P01Bm",
        .bpaFileNames = {"B01P01B1", NULL, "B04P01B3", NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_SKITTY_FINAL] = {
        .bplFileName = "B04P01C",
        .bpcFileName = "B04P01Cc",
        .bmaFileName = "B04P01Cm",
        .bpaFileNames = {"B04P01C1", NULL, NULL, NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_INSIDE_SKITTY_BASIC] = {
        .bplFileName = "B04P02A",
        .bpcFileName = "B01P02c",
        .bmaFileName = "B01P02Am",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_INSIDE_SKITTY_CONSTRUCTION] = {
        .bplFileName = "B04P02B",
        .bpcFileName = "B01P02c",
        .bmaFileName = "B01P02Bm",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_INSIDE_SKITTY_FINAL] = {
        .bplFileName = "B04P02C",
        .bpcFileName = "B01P02Cc",
        .bmaFileName = "B01P02Cm",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_SQUIRTLE_BASIC] = {
        .bplFileName = "B05P01A",
        .bpcFileName = "B05P01Ac",
        .bmaFileName = "B05P01Am",
        .bpaFileNames = {"B05P01A1", NULL, NULL, NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_SQUIRTLE_CONSTRUCTION] = {
        .bplFileName = "B05P01B",
        .bpcFileName = "B05P01Bc",
        .bmaFileName = "B05P01Bm",
        .bpaFileNames = {"B05P01B1", NULL, "B05P01B3", NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_SQUIRTLE_FINAL] = {
        .bplFileName = "B05P01C",
        .bpcFileName = "B05P01Cc",
        .bmaFileName = "B05P01Cm",
        .bpaFileNames = {"B05P01C1", NULL, NULL, NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_INSIDE_SQUIRTLE_BASIC] = {
        .bplFileName = "B05P02A",
        .bpcFileName = "B05P02c",
        .bmaFileName = "B05P02Am",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_INSIDE_SQUIRTLE_CONSTRUCTION] = {
        .bplFileName = "B05P02B",
        .bpcFileName = "B05P02c",
        .bmaFileName = "B05P02Bm",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_INSIDE_SQUIRTLE_FINAL] = {
        .bplFileName = "B05P02C",
        .bpcFileName = "B05P02Cc",
        .bmaFileName = "B05P02Cm",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_TOTODILE_BASIC] = {
        .bplFileName = "B06P01A",
        .bpcFileName = "B05P01Ac",
        .bmaFileName = "B05P01Am",
        .bpaFileNames = {"B05P01A1", NULL, NULL, NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_TOTODILE_CONSTRUCTION] = {
        .bplFileName = "B06P01B",
        .bpcFileName = "B05P01Bc",
        .bmaFileName = "B05P01Bm",
        .bpaFileNames = {"B05P01B1", NULL, "B06P01B3", NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_TOTODILE_FINAL] = {
        .bplFileName = "B06P01C",
        .bpcFileName = "B06P01Cc",
        .bmaFileName = "B06P01Cm",
        .bpaFileNames = {"B06P01C1", NULL, NULL, NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_INSIDE_TOTODILE_BASIC] = {
        .bplFileName = "B06P02A",
        .bpcFileName = "B05P02c",
        .bmaFileName = "B05P02Am",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_INSIDE_TOTODILE_CONSTRUCTION] = {
        .bplFileName = "B06P02B",
        .bpcFileName = "B05P02c",
        .bmaFileName = "B05P02Bm",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_INSIDE_TOTODILE_FINAL] = {
        .bplFileName = "B06P02C",
        .bpcFileName = "B05P02Cc",
        .bmaFileName = "B05P02Cm",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_MUDKIP_BASIC] = {
        .bplFileName = "B07P01A",
        .bpcFileName = "B05P01Ac",
        .bmaFileName = "B05P01Am",
        .bpaFileNames = {"B05P01A1", NULL, NULL, NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_MUDKIP_CONSTRUCTION] = {
        .bplFileName = "B07P01B",
        .bpcFileName = "B05P01Bc",
        .bmaFileName = "B05P01Bm",
        .bpaFileNames = {"B05P01B1", NULL, "B07P01B3", NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_MUDKIP_FINAL] = {
        .bplFileName = "B07P01C",
        .bpcFileName = "B07P01Cc",
        .bmaFileName = "B07P01Cm",
        .bpaFileNames = {"B07P01C1", NULL, NULL, NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_INSIDE_MUDKIP_BASIC] = {
        .bplFileName = "B07P02A",
        .bpcFileName = "B05P02c",
        .bmaFileName = "B05P02Am",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_INSIDE_MUDKIP_CONSTRUCTION] = {
        .bplFileName = "B07P02B",
        .bpcFileName = "B05P02c",
        .bmaFileName = "B05P02Bm",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_INSIDE_MUDKIP_FINAL] = {
        .bplFileName = "B07P02C",
        .bpcFileName = "B05P02Cc",
        .bmaFileName = "B05P02Cm",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_PSYDUCK_BASIC] = {
        .bplFileName = "B08P01A",
        .bpcFileName = "B05P01Ac",
        .bmaFileName = "B05P01Am",
        .bpaFileNames = {"B05P01A1", NULL, NULL, NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_PSYDUCK_CONSTRUCTION] = {
        .bplFileName = "B08P01B",
        .bpcFileName = "B05P01Bc",
        .bmaFileName = "B05P01Bm",
        .bpaFileNames = {"B05P01B1", NULL, "B08P01B3", NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_PSYDUCK_FINAL] = {
        .bplFileName = "B08P01C",
        .bpcFileName = "B08P01Cc",
        .bmaFileName = "B08P01Cm",
        .bpaFileNames = {"B08P01C1", NULL, NULL, NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_INSIDE_PSYDUCK_BASIC] = {
        .bplFileName = "B08P02A",
        .bpcFileName = "B05P02c",
        .bmaFileName = "B05P02Am",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_INSIDE_PSYDUCK_CONSTRUCTION] = {
        .bplFileName = "B08P02B",
        .bpcFileName = "B05P02c",
        .bmaFileName = "B05P02Bm",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_INSIDE_PSYDUCK_FINAL] = {
        .bplFileName = "B08P02C",
        .bpcFileName = "B05P02Cc",
        .bmaFileName = "B05P02Cm",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_CHARMANDER_BASIC] = {
        .bplFileName = "B09P01A",
        .bpcFileName = "B09P01Ac",
        .bmaFileName = "B09P01Am",
        .bpaFileNames = {"B09P01A1", NULL, NULL, NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_CHARMANDER_CONSTRUCTION] = {
        .bplFileName = "B09P01B",
        .bpcFileName = "B09P01Bc",
        .bmaFileName = "B09P01Bm",
        .bpaFileNames = {"B09P01B1", NULL, "B09P01B3", NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_CHARMANDER_FINAL] = {
        .bplFileName = "B09P01C",
        .bpcFileName = "B09P01Cc",
        .bmaFileName = "B09P01Cm",
        .bpaFileNames = {"B09P01C1", NULL, NULL, NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_INSIDE_CHARMANDER_BASIC] = {
        .bplFileName = "B09P02A",
        .bpcFileName = "B09P02c",
        .bmaFileName = "B09P02Am",
        .bpaFileNames = {"B09P021", NULL, NULL, NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_INSIDE_CHARMANDER_CONSTRUCTION] = {
        .bplFileName = "B09P02B",
        .bpcFileName = "B09P02c",
        .bmaFileName = "B09P02Bm",
        .bpaFileNames = {"B09P021", NULL, NULL, NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_INSIDE_CHARMANDER_FINAL] = {
        .bplFileName = "B09P02C",
        .bpcFileName = "B09P02Cc",
        .bmaFileName = "B09P02Cm",
        .bpaFileNames = {"B09P02C1", NULL, NULL, NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_TORCHIC_BASIC] = {
        .bplFileName = "B10P01A",
        .bpcFileName = "B09P01Ac",
        .bmaFileName = "B09P01Am",
        .bpaFileNames = {"B09P01A1", NULL, NULL, NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_TORCHIC_CONSTRUCTION] = {
        .bplFileName = "B10P01B",
        .bpcFileName = "B09P01Bc",
        .bmaFileName = "B09P01Bm",
        .bpaFileNames = {"B09P01B1", NULL, "B10P01B3", NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_TORCHIC_FINAL] = {
        .bplFileName = "B10P01C",
        .bpcFileName = "B10P01Cc",
        .bmaFileName = "B10P01Cm",
        .bpaFileNames = {"B10P01C1", NULL, NULL, NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_INSIDE_TORCHIC_BASIC] = {
        .bplFileName = "B10P02A",
        .bpcFileName = "B09P02c",
        .bmaFileName = "B09P02Am",
        .bpaFileNames = {"B09P021", NULL, NULL, NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_INSIDE_TORCHIC_CONSTRUCTION] = {
        .bplFileName = "B10P02B",
        .bpcFileName = "B09P02c",
        .bmaFileName = "B09P02Bm",
        .bpaFileNames = {"B09P021", NULL, NULL, NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_INSIDE_TORCHIC_FINAL] = {
        .bplFileName = "B10P02C",
        .bpcFileName = "B09P02Cc",
        .bmaFileName = "B09P02Cm",
        .bpaFileNames = {"B09P02C1", NULL, NULL, NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_CYNDAQUIL_BASIC] = {
        .bplFileName = "B11P01A",
        .bpcFileName = "B09P01Ac",
        .bmaFileName = "B09P01Am",
        .bpaFileNames = {"B09P01A1", NULL, NULL, NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_CYNDAQUIL_CONSTRUCTION] = {
        .bplFileName = "B11P01B",
        .bpcFileName = "B09P01Bc",
        .bmaFileName = "B09P01Bm",
        .bpaFileNames = {"B09P01B1", NULL, "B11P01B3", NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_CYNDAQUIL_FINAL] = {
        .bplFileName = "B11P01C",
        .bpcFileName = "B11P01Cc",
        .bmaFileName = "B11P01Cm",
        .bpaFileNames = {"B11P01C1", NULL, NULL, NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_INSIDE_CYNDAQUIL_BASIC] = {
        .bplFileName = "B11P02A",
        .bpcFileName = "B09P02c",
        .bmaFileName = "B09P02Am",
        .bpaFileNames = {"B09P021", NULL, NULL, NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_INSIDE_CYNDAQUIL_CONSTRUCTION] = {
        .bplFileName = "B11P02B",
        .bpcFileName = "B09P02c",
        .bmaFileName = "B09P02Bm",
        .bpaFileNames = {"B09P021", NULL, NULL, NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_INSIDE_CYNDAQUIL_FINAL] = {
        .bplFileName = "B11P02C",
        .bpcFileName = "B09P02Cc",
        .bmaFileName = "B09P02Cm",
        .bpaFileNames = {"B09P02C1", NULL, NULL, NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_CUBONE_BASIC] = {
        .bplFileName = "B12P01A",
        .bpcFileName = "B12P01Ac",
        .bmaFileName = "B12P01Am",
        .bpaFileNames = {"B12P01A1", NULL, NULL, NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_CUBONE_CONSTRUCTION] = {
        .bplFileName = "B12P01B",
        .bpcFileName = "B12P01Bc",
        .bmaFileName = "B12P01Bm",
        .bpaFileNames = {"B12P01B1", NULL, "B12P01B3", NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_CUBONE_FINAL] = {
        .bplFileName = "B12P01C",
        .bpcFileName = "B12P01Cc",
        .bmaFileName = "B12P01Cm",
        .bpaFileNames = {"B12P01C1", NULL, NULL, NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_INSIDE_CUBONE_BASIC] = {
        .bplFileName = "B12P02A",
        .bpcFileName = "B12P02c",
        .bmaFileName = "B12P02Am",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_INSIDE_CUBONE_CONSTRUCTION] = {
        .bplFileName = "B12P02B",
        .bpcFileName = "B12P02c",
        .bmaFileName = "B12P02Bm",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_INSIDE_CUBONE_FINAL] = {
        .bplFileName = "B12P02C",
        .bpcFileName = "B12P02Cc",
        .bmaFileName = "B12P02Cm",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_MACHOP_BASIC] = {
        .bplFileName = "B13P01A",
        .bpcFileName = "B12P01Ac",
        .bmaFileName = "B12P01Am",
        .bpaFileNames = {"B12P01A1", NULL, NULL, NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_MACHOP_CONSTRUCTION] = {
        .bplFileName = "B13P01B",
        .bpcFileName = "B12P01Bc",
        .bmaFileName = "B12P01Bm",
        .bpaFileNames = {"B12P01B1", NULL, "B13P01B3", NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_MACHOP_FINAL] = {
        .bplFileName = "B13P01C",
        .bpcFileName = "B13P01Cc",
        .bmaFileName = "B13P01Cm",
        .bpaFileNames = {"B13P01C1", NULL, NULL, NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_INSIDE_MACHOP_BASIC] = {
        .bplFileName = "B13P02A",
        .bpcFileName = "B12P02c",
        .bmaFileName = "B12P02Am",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_INSIDE_MACHOP_CONSTRUCTION] = {
        .bplFileName = "B13P02B",
        .bpcFileName = "B12P02c",
        .bmaFileName = "B12P02Bm",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_INSIDE_MACHOP_FINAL] = {
        .bplFileName = "B13P02C",
        .bpcFileName = "B12P02Cc",
        .bmaFileName = "B12P02Cm",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_BULBASAUR_BASIC] = {
        .bplFileName = "B14P01A",
        .bpcFileName = "B14P01Ac",
        .bmaFileName = "B14P01Am",
        .bpaFileNames = {"B14P01A1", NULL, NULL, NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_BULBASAUR_CONSTRUCTION] = {
        .bplFileName = "B14P01B",
        .bpcFileName = "B14P01Bc",
        .bmaFileName = "B14P01Bm",
        .bpaFileNames = {"B14P01B1", NULL, "B14P01B3", NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_BULBASAUR_FINAL] = {
        .bplFileName = "B14P01C",
        .bpcFileName = "B14P01Cc",
        .bmaFileName = "B14P01Cm",
        .bpaFileNames = {"B14P01C1", NULL, NULL, NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_INSIDE_BULBASAUR_BASIC] = {
        .bplFileName = "B14P02A",
        .bpcFileName = "B14P02c",
        .bmaFileName = "B14P02Am",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_INSIDE_BULBASAUR_CONSTRUCTION] = {
        .bplFileName = "B14P02B",
        .bpcFileName = "B14P02c",
        .bmaFileName = "B14P02Bm",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_INSIDE_BULBASAUR_FINAL] = {
        .bplFileName = "B14P02C",
        .bpcFileName = "B14P02Cc",
        .bmaFileName = "B14P02Cm",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_CHIKORITA_BASIC] = {
        .bplFileName = "B15P01A",
        .bpcFileName = "B14P01Ac",
        .bmaFileName = "B14P01Am",
        .bpaFileNames = {"B14P01A1", NULL, NULL, NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_CHIKORITA_CONSTRUCTION] = {
        .bplFileName = "B15P01B",
        .bpcFileName = "B14P01Bc",
        .bmaFileName = "B14P01Bm",
        .bpaFileNames = {"B14P01B1", NULL, "B15P01B3", NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_CHIKORITA_FINAL] = {
        .bplFileName = "B15P01C",
        .bpcFileName = "B15P01Cc",
        .bmaFileName = "B15P01Cm",
        .bpaFileNames = {"B15P01C1", NULL, NULL, NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_INSIDE_CHIKORITA_BASIC] = {
        .bplFileName = "B15P02A",
        .bpcFileName = "B14P02c",
        .bmaFileName = "B14P02Am",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_INSIDE_CHIKORITA_CONSTRUCTION] = {
        .bplFileName = "B15P02B",
        .bpcFileName = "B14P02c",
        .bmaFileName = "B14P02Bm",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_INSIDE_CHIKORITA_FINAL] = {
        .bplFileName = "B15P02C",
        .bpcFileName = "B14P02Cc",
        .bmaFileName = "B14P02Cm",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_TREECKO_BASIC] = {
        .bplFileName = "B16P01A",
        .bpcFileName = "B14P01Ac",
        .bmaFileName = "B14P01Am",
        .bpaFileNames = {"B14P01A1", NULL, NULL, NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_TREECKO_CONSTRUCTION] = {
        .bplFileName = "B16P01B",
        .bpcFileName = "B14P01Bc",
        .bmaFileName = "B14P01Bm",
        .bpaFileNames = {"B14P01B1", NULL, "B16P01B3", NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_TREECKO_FINAL] = {
        .bplFileName = "B16P01C",
        .bpcFileName = "B16P01Cc",
        .bmaFileName = "B16P01Cm",
        .bpaFileNames = {"B16P01C1", NULL, NULL, NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_INSIDE_TREECKO_BASIC] = {
        .bplFileName = "B16P02A",
        .bpcFileName = "B14P02c",
        .bmaFileName = "B14P02Am",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_INSIDE_TREECKO_CONSTRUCTION] = {
        .bplFileName = "B16P02B",
        .bpcFileName = "B14P02c",
        .bmaFileName = "B14P02Bm",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_INSIDE_TREECKO_FINAL] = {
        .bplFileName = "B16P02C",
        .bpcFileName = "B14P02Cc",
        .bmaFileName = "B14P02Cm",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_FRIEND_AREA_BOUNTIFUL_SEA] = {
        .bplFileName = "H01P01",
        .bpcFileName = "H01P01c",
        .bmaFileName = "H01P01m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_UNK_107] = {
        .bplFileName = "H01P01W",
        .bpcFileName = "H01P01Wc",
        .bmaFileName = "H01P01Wm",
        .bpaFileNames = {"H01P01W1", NULL, NULL, NULL},
    },
    [MAP_FILE_ID_FRIEND_AREA_TREASURE_SEA] = {
        .bplFileName = "H01P02",
        .bpcFileName = "H01P02c",
        .bmaFileName = "H01P02m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_FRIEND_AREA_SERENE_SEA] = {
        .bplFileName = "H01P03",
        .bpcFileName = "H01P03c",
        .bmaFileName = "H01P03m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_FRIEND_AREA_DEEP_SEA_FLOOR] = {
        .bplFileName = "H02P01",
        .bpcFileName = "H02P01c",
        .bmaFileName = "H02P01m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_UNK_111] = {
        .bplFileName = "H02P01W",
        .bpcFileName = "H02P01Wc",
        .bmaFileName = "H02P01Wm",
        .bpaFileNames = {"H02P01W1", NULL, NULL, NULL},
    },
    [MAP_FILE_ID_FRIEND_AREA_DEEP_SEA_CURRENT] = {
        .bplFileName = "H02P02",
        .bpcFileName = "H02P02c",
        .bmaFileName = "H02P02m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_UNK_113] = {
        .bplFileName = "H02P02W",
        .bpcFileName = "H02P02Wc",
        .bmaFileName = "H02P02Wm",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_FRIEND_AREA_SEAFLOOR_CAVE] = {
        .bplFileName = "H02P03",
        .bpcFileName = "H02P03c",
        .bmaFileName = "H02P03m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_UNK_115] = {
        .bplFileName = "H02P03W",
        .bpcFileName = "H02P03Wc",
        .bmaFileName = "H02P03Wm",
        .bpaFileNames = {"H02P03W1", NULL, NULL, NULL},
    },
    [MAP_FILE_ID_FRIEND_AREA_SHALLOW_BEACH] = {
        .bplFileName = "H03P01",
        .bpcFileName = "H03P01c",
        .bmaFileName = "H03P01m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_FRIEND_AREA_MT_DEEPGREEN] = {
        .bplFileName = "H04P01",
        .bpcFileName = "H04P01c",
        .bmaFileName = "H04P01m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_FRIEND_AREA_MT_CLEFT] = {
        .bplFileName = "H04P02",
        .bpcFileName = "H04P02c",
        .bmaFileName = "H04P02m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_FRIEND_AREA_MT_MOONVIEW] = {
        .bplFileName = "H05P01",
        .bpcFileName = "H05P01c",
        .bmaFileName = "H05P01m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_FRIEND_AREA_RAINBOW_PEAK] = {
        .bplFileName = "H05P02",
        .bpcFileName = "H05P02c",
        .bmaFileName = "H05P02m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_FRIEND_AREA_WILD_PLAINS] = {
        .bplFileName = "H06P01",
        .bpcFileName = "H06P01c",
        .bmaFileName = "H06P01m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_FRIEND_AREA_BEAU_PLAINS] = {
        .bplFileName = "H06P02",
        .bpcFileName = "H06P02c",
        .bmaFileName = "H06P02m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_FRIEND_AREA_SKY_BLUE_PLAINS] = {
        .bplFileName = "H06P03",
        .bpcFileName = "H06P03c",
        .bmaFileName = "H06P03m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_FRIEND_AREA_SAFARI] = {
        .bplFileName = "H06P04",
        .bpcFileName = "H06P04c",
        .bmaFileName = "H06P04m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_FRIEND_AREA_SCORCHED_PLAINS] = {
        .bplFileName = "H06P05",
        .bpcFileName = "H06P05c",
        .bmaFileName = "H06P05m",
        .bpaFileNames = {"H06P051", NULL, NULL, NULL},
    },
    [MAP_FILE_ID_FRIEND_AREA_SACRED_FIELD] = {
        .bplFileName = "H06P06",
        .bpcFileName = "H06P06c",
        .bmaFileName = "H06P06m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_FRIEND_AREA_MIST_RISE_FOREST] = {
        .bplFileName = "H07P01",
        .bpcFileName = "H07P01c",
        .bmaFileName = "H07P01m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_FRIEND_AREA_FLYAWAY_FOREST] = {
        .bplFileName = "H07P02",
        .bpcFileName = "H07P02c",
        .bmaFileName = "H07P02m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_FRIEND_AREA_OVERGROWN_FOREST] = {
        .bplFileName = "H07P03",
        .bpcFileName = "H07P03c",
        .bmaFileName = "H07P03m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_FRIEND_AREA_ENERGETIC_FOREST] = {
        .bplFileName = "H07P04",
        .bpcFileName = "H07P04c",
        .bmaFileName = "H07P04m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_UNK_131] = {
        .bplFileName = "H07P04W",
        .bpcFileName = "H07P04Wc",
        .bmaFileName = "H07P04Wm",
        .bpaFileNames = {"H07P04W1", NULL, NULL, NULL},
    },
    [MAP_FILE_ID_FRIEND_AREA_MUSHROOM_FOREST] = {
        .bplFileName = "H07P05",
        .bpcFileName = "H07P05c",
        .bmaFileName = "H07P05m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_FRIEND_AREA_HEALING_FOREST] = {
        .bplFileName = "H07P06",
        .bpcFileName = "H07P06c",
        .bmaFileName = "H07P06m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_FRIEND_AREA_TRANSFORM_FOREST] = {
        .bplFileName = "H07P07",
        .bpcFileName = "H07P07c",
        .bmaFileName = "H07P07m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_FRIEND_AREA_SECRETIVE_FOREST] = {
        .bplFileName = "H07P08",
        .bpcFileName = "H07P08c",
        .bmaFileName = "H07P08m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_FRIEND_AREA_RUB_A_DUB_RIVER] = {
        .bplFileName = "H08P01",
        .bpcFileName = "H08P01c",
        .bmaFileName = "H08P01m",
        .bpaFileNames = {"H08P011", NULL, NULL, NULL},
    },
    [MAP_FILE_ID_FRIEND_AREA_TADPOLE_POND] = {
        .bplFileName = "H09P01",
        .bpcFileName = "H09P01c",
        .bmaFileName = "H09P01m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_FRIEND_AREA_TURTLESHELL_POND] = {
        .bplFileName = "H09P02",
        .bpcFileName = "H09P02c",
        .bmaFileName = "H09P02m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_FRIEND_AREA_MYSTIC_LAKE] = {
        .bplFileName = "H10P01",
        .bpcFileName = "H10P01c",
        .bmaFileName = "H10P01m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_FRIEND_AREA_WATERFALL_LAKE] = {
        .bplFileName = "H10P02",
        .bpcFileName = "H10P02c",
        .bmaFileName = "H10P02m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_FRIEND_AREA_PEANUT_SWAMP] = {
        .bplFileName = "H11P01",
        .bpcFileName = "H11P01c",
        .bmaFileName = "H11P01m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_FRIEND_AREA_POISON_SWAMP] = {
        .bplFileName = "H12P01",
        .bpcFileName = "H12P01c",
        .bmaFileName = "H12P01m",
        .bpaFileNames = {"H12P011", NULL, NULL, NULL},
    },
    [MAP_FILE_ID_FRIEND_AREA_ECHO_CAVE] = {
        .bplFileName = "H13P01",
        .bpcFileName = "H13P01c",
        .bmaFileName = "H13P01m",
        .bpaFileNames = {"H13P011", NULL, NULL, NULL},
    },
    [MAP_FILE_ID_FRIEND_AREA_CRYPTIC_CAVE] = {
        .bplFileName = "H13P02",
        .bpcFileName = "H13P02c",
        .bmaFileName = "H13P02m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_FRIEND_AREA_DRAGON_CAVE] = {
        .bplFileName = "H13P03",
        .bpcFileName = "H13P03c",
        .bmaFileName = "H13P03m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_FRIEND_AREA_BOULDER_CAVE] = {
        .bplFileName = "H13P04",
        .bpcFileName = "H13P04c",
        .bmaFileName = "H13P04m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_FRIEND_AREA_JUNGLE] = {
        .bplFileName = "H14P01",
        .bpcFileName = "H14P01c",
        .bmaFileName = "H14P01m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_FRIEND_AREA_DECREPIT_LAB] = {
        .bplFileName = "H15P01",
        .bpcFileName = "H15P01c",
        .bmaFileName = "H15P01m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_FRIEND_AREA_MT_DISCIPLINE] = {
        .bplFileName = "H16P01",
        .bpcFileName = "H16P01c",
        .bmaFileName = "H16P01m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_FRIEND_AREA_THUNDER_MEADOW] = {
        .bplFileName = "H17P01",
        .bpcFileName = "H17P01c",
        .bmaFileName = "H17P01m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_UNK_151] = {
        .bplFileName = "H17P01W",
        .bpcFileName = "H17P01Wc",
        .bmaFileName = "H17P01Wm",
        .bpaFileNames = {"H17P01W1", NULL, NULL, NULL},
    },
    [MAP_FILE_ID_FRIEND_AREA_POWER_PLANT] = {
        .bplFileName = "H18P01",
        .bpcFileName = "H18P01c",
        .bmaFileName = "H18P01m",
        .bpaFileNames = {"H18P011", NULL, NULL, NULL},
    },
    [MAP_FILE_ID_FRIEND_AREA_CRATER] = {
        .bplFileName = "H19P01",
        .bpcFileName = "H19P01c",
        .bmaFileName = "H19P01m",
        .bpaFileNames = {"H19P011", NULL, NULL, NULL},
    },
    [MAP_FILE_ID_UNK_154] = {
        .bplFileName = "H19P01W",
        .bpcFileName = "H19P01Wc",
        .bmaFileName = "H19P01Wm",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_FRIEND_AREA_FURNACE_DESERT] = {
        .bplFileName = "H20P01",
        .bpcFileName = "H20P01c",
        .bmaFileName = "H20P01m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_FRIEND_AREA_AGED_CHAMBER_AN] = {
        .bplFileName = "H21P01",
        .bpcFileName = "H21c",
        .bmaFileName = "H21P01m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_FRIEND_AREA_AGED_CHAMBER_O_EXCLAIM] = {
        .bplFileName = "H21P02",
        .bpcFileName = "H21c",
        .bmaFileName = "H21P02m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_FRIEND_AREA_ANCIENT_RELIC] = {
        .bplFileName = "H22P01",
        .bpcFileName = "H22P01c",
        .bmaFileName = "H22P01m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_FRIEND_AREA_DARKNESS_RIDGE] = {
        .bplFileName = "H23P01",
        .bpcFileName = "H23P01c",
        .bmaFileName = "H23P01m",
        .bpaFileNames = {"H23P011", NULL, NULL, NULL},
    },
    [MAP_FILE_ID_FRIEND_AREA_FRIGID_CAVERN] = {
        .bplFileName = "H24P01",
        .bpcFileName = "H24P01c",
        .bmaFileName = "H24P01m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_FRIEND_AREA_ICE_FLOE_BEACH] = {
        .bplFileName = "H25P01",
        .bpcFileName = "H25P01c",
        .bmaFileName = "H25P01m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_FRIEND_AREA_VOLCANIC_PIT] = {
        .bplFileName = "H26P01",
        .bpcFileName = "H26P01c",
        .bmaFileName = "H26P01m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_FRIEND_AREA_STRATOS_LOOKOUT] = {
        .bplFileName = "H27P01",
        .bpcFileName = "H27P01c",
        .bmaFileName = "H27P01m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_FRIEND_AREA_RAVAGED_FIELD] = {
        .bplFileName = "H28P01",
        .bpcFileName = "H28P01c",
        .bmaFileName = "H28P01m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_FRIEND_AREA_MAGNETIC_QUARRY] = {
        .bplFileName = "H28P02",
        .bpcFileName = "H28P02c",
        .bmaFileName = "H28P02m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_FRIEND_AREA_LEGENDARY_ISLAND] = {
        .bplFileName = "H29P01",
        .bpcFileName = "H29P01c",
        .bmaFileName = "H29P01m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_FRIEND_AREA_SOUTHERN_ISLAND] = {
        .bplFileName = "H29P02",
        .bpcFileName = "H29P02c",
        .bmaFileName = "H29P02m",
        .bpaFileNames = {"H29P021", NULL, NULL, NULL},
    },
    [MAP_FILE_ID_FRIEND_AREA_ENCLOSED_ISLAND] = {
        .bplFileName = "H29P03",
        .bpcFileName = "H29P03c",
        .bmaFileName = "H29P03m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_UNK_169] = {
        .bplFileName = "H29P03W",
        .bpcFileName = "H29P03Wc",
        .bmaFileName = "H29P03Wm",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_FRIEND_AREA_FINAL_ISLAND] = {
        .bplFileName = "H29P04",
        .bpcFileName = "H29P04c",
        .bmaFileName = "H29P04m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_PERSONALITY_TEST_CYAN] = {
        .bplFileName = "A01P01",
        .bpcFileName = "A01P01c",
        .bmaFileName = "A01P01m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_PERSONALITY_TEST_PURPLE] = {
        .bplFileName = "A01P02",
        .bpcFileName = "A01P01c",
        .bmaFileName = "A01P01m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_FUGITIVES_FISSURE] = {
        .bplFileName = "A02P01",
        .bpcFileName = "A02P01c",
        .bmaFileName = "A02P01m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_FUGITIVES_FIRE] = {
        .bplFileName = "A02P02",
        .bpcFileName = "A02P02c",
        .bmaFileName = "A02P02m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_FUGITIVES_LAPIS_CAVE] = {
        .bplFileName = "A02P03",
        .bpcFileName = "A02P03c",
        .bmaFileName = "A02P03m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_FUGITIVES_VOLCANO] = {
        .bplFileName = "A02P04",
        .bpcFileName = "A02P04c",
        .bmaFileName = "A02P04m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_FUGITIVES_SNOW_ROAD] = {
        .bplFileName = "A03P01",
        .bpcFileName = "A03P01c",
        .bmaFileName = "A03P01m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_FUGITIVES_SNOW_FOREST] = {
        .bplFileName = "A03P02",
        .bpcFileName = "D10P01c",
        .bmaFileName = "D10P01m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_FUGITIVES_BLIZZARD_ROAD] = {
        .bplFileName = "A03P03",
        .bpcFileName = "A03P03c",
        .bmaFileName = "A03P03m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_SUMMIT_SUNSET] = {
        .bplFileName = "A04P01",
        .bpcFileName = "A04P01c",
        .bmaFileName = "A04P01m",
        .bpaFileNames = {"A04P011", NULL, NULL, NULL},
    },
    [MAP_FILE_ID_SKY_TOWER] = {
        .bplFileName = "A04P02",
        .bpcFileName = "A04P02c",
        .bmaFileName = "A04P02m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_COMET] = {
        .bplFileName = "A04P03",
        .bpcFileName = "A04P03c",
        .bmaFileName = "A04P03m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_NIGHTMARE] = {
        .bplFileName = "A04P04",
        .bpcFileName = "A04P04c",
        .bmaFileName = "A04P04m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_NIGHT_SKY_1] = {
        .bplFileName = "A05P01",
        .bpcFileName = "A05P01c",
        .bmaFileName = "A05P01m",
        .bpaFileNames = {"A05P011", NULL, NULL, NULL},
    },
    [MAP_FILE_ID_NIGHT_SKY_2] = {
        .bplFileName = "A05P02",
        .bpcFileName = "A05P02c",
        .bmaFileName = "A05P02m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_THE_END] = {
        .bplFileName = "A05P03",
        .bpcFileName = "A05P03c",
        .bmaFileName = "A05P03m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_TINY_WOODS_ENTRY] = {
        .bplFileName = "D01P01",
        .bpcFileName = "D01P01c",
        .bmaFileName = "D01P01m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_TINY_WOODS_END] = {
        .bplFileName = "D01P02",
        .bpcFileName = "D01P02c",
        .bmaFileName = "D01P02m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_THUNDERWAVE_CAVE_ENTRY] = {
        .bplFileName = "D02P01",
        .bpcFileName = "D02P01c",
        .bmaFileName = "D02P01m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_THUNDERWAVE_CAVE_END] = {
        .bplFileName = "D02P02",
        .bpcFileName = "D02P02c",
        .bmaFileName = "D02P02m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_MT_STEEL_ENTRY] = {
        .bplFileName = "D03P01",
        .bpcFileName = "D03P01c",
        .bmaFileName = "D03P01m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_MT_STEEL_END] = {
        .bplFileName = "D03P02",
        .bpcFileName = "D03P02c",
        .bmaFileName = "D03P02m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_SINISTER_WOODS_ENTRY] = {
        .bplFileName = "D04P01",
        .bpcFileName = "D04P01c",
        .bmaFileName = "D04P01m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_SINISTER_WOODS_END] = {
        .bplFileName = "D04P02",
        .bpcFileName = "D04P02c",
        .bmaFileName = "D04P02m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_SILENT_CHASM_ENTRY] = {
        .bplFileName = "D05P01",
        .bpcFileName = "D05P01c",
        .bmaFileName = "D05P01m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_SILENT_CHASM_END] = {
        .bplFileName = "D05P02",
        .bpcFileName = "D05P02c",
        .bmaFileName = "D05P02m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_MT_THUNDER_ENTRY] = {
        .bplFileName = "D06P01",
        .bpcFileName = "D06P01c",
        .bmaFileName = "D06P01m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_MT_THUNDER_MID] = {
        .bplFileName = "D06P02",
        .bpcFileName = "D06P02c",
        .bmaFileName = "D06P02m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_MT_THUNDER_END] = {
        .bplFileName = "D06P03",
        .bpcFileName = "D06P03c",
        .bmaFileName = "D06P03m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_GREAT_CANYON_ENTRY] = {
        .bplFileName = "D07P01",
        .bpcFileName = "D07P01c",
        .bmaFileName = "D07P01m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_HILL_OF_THE_ANCIENTS] = {
        .bplFileName = "D07P02",
        .bpcFileName = "A04P01c",
        .bmaFileName = "A04P01m",
        .bpaFileNames = {"A04P011", NULL, NULL, NULL},
    },
    [MAP_FILE_ID_LAPIS_CAVE_ENTRY] = {
        .bplFileName = "D08P01",
        .bpcFileName = "D08P01c",
        .bmaFileName = "D08P01m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_LAPIS_CAVE_END] = {
        .bplFileName = "D08P02",
        .bpcFileName = "D08P02c",
        .bmaFileName = "D08P02m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_MT_BLAZE_ENTRY] = {
        .bplFileName = "D09P01",
        .bpcFileName = "D09P01c",
        .bmaFileName = "D09P01m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_MT_BLAZE_MID] = {
        .bplFileName = "D09P02",
        .bpcFileName = "D09P02c",
        .bmaFileName = "D09P02m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_MT_BLAZE_END] = {
        .bplFileName = "D09P03",
        .bpcFileName = "D09P03c",
        .bmaFileName = "D09P03m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_FROSTY_FOREST_ENTRY] = {
        .bplFileName = "D10P01",
        .bpcFileName = "D10P01c",
        .bmaFileName = "D10P01m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_FROSTY_FOREST_MID] = {
        .bplFileName = "D10P02",
        .bpcFileName = "D10P02c",
        .bmaFileName = "D10P02m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_FROSTY_FOREST_END] = {
        .bplFileName = "D10P03",
        .bpcFileName = "D10P03c",
        .bmaFileName = "D10P03m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_MT_FREEZE_ENTRY] = {
        .bplFileName = "D11P01",
        .bpcFileName = "D11P01c",
        .bmaFileName = "D11P01m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_MT_FREEZE_MID] = {
        .bplFileName = "D11P02",
        .bpcFileName = "D11P02c",
        .bmaFileName = "D11P02m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_MT_FREEZE_END] = {
        .bplFileName = "D11P03",
        .bpcFileName = "D11P03c",
        .bmaFileName = "D11P03m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_MAGMA_CAVERN_ENTRY] = {
        .bplFileName = "D12P01",
        .bpcFileName = "D12P01c",
        .bmaFileName = "D12P01m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_MAGMA_CAVERN_MID] = {
        .bplFileName = "D12P02",
        .bpcFileName = "D12P02c",
        .bmaFileName = "D12P02m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_MAGMA_CAVERN_END] = {
        .bplFileName = "D12P04",
        .bpcFileName = "D12P04c",
        .bmaFileName = "D12P04m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_SKY_TOWER_ENTRY] = {
        .bplFileName = "D13P01",
        .bpcFileName = "D13P01c",
        .bmaFileName = "D13P01m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_SKY_TOWER_MID] = {
        .bplFileName = "D13P02",
        .bpcFileName = "D13P02c",
        .bmaFileName = "D13P02m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_SKY_TOWER_END] = {
        .bplFileName = "D13P03",
        .bpcFileName = "D13P03c",
        .bmaFileName = "D13P03m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_D14] = {
        .bplFileName = "D14P01",
        .bpcFileName = "D14P01c",
        .bmaFileName = "D14P01m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_D15] = {
        .bplFileName = "D15P01",
        .bpcFileName = "D15P01c",
        .bmaFileName = "D15P01m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_D16] = {
        .bplFileName = "D16P01",
        .bpcFileName = "D16P01c",
        .bmaFileName = "D16P01m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_D17] = {
        .bplFileName = "D17P01",
        .bpcFileName = "D17P01c",
        .bmaFileName = "D17P01m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_D18] = {
        .bplFileName = "D18P01",
        .bpcFileName = "D18P01c",
        .bmaFileName = "D18P01m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_D19] = {
        .bplFileName = "D19P01",
        .bpcFileName = "D19P01c",
        .bmaFileName = "D19P01m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_D20] = {
        .bplFileName = "D20P01",
        .bpcFileName = "D20P01c",
        .bmaFileName = "D20P01m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_D21] = {
        .bplFileName = "D21P01",
        .bpcFileName = "D21P01c",
        .bmaFileName = "D21P01m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_D22] = {
        .bplFileName = "D22P01",
        .bpcFileName = "D22P01c",
        .bmaFileName = "D22P01m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_D23] = {
        .bplFileName = "D23P01",
        .bpcFileName = "D23P01c",
        .bmaFileName = "D23P01m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_D24_1] = {
        .bplFileName = "D24P01",
        .bpcFileName = "D24P01c",
        .bmaFileName = "D24P01m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_D24_2] = {
        .bplFileName = "D24P02",
        .bpcFileName = "D24P02c",
        .bmaFileName = "D24P02m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_D25] = {
        .bplFileName = "D25P01",
        .bpcFileName = "D25P01c",
        .bmaFileName = "D25P01m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_PERSONALITY_TEST_MULTICOLOR] = {
        .bplFileName = "S01",
        .bpcFileName = "A01P01c",
        .bmaFileName = "A01P01m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_TITLE_SCREEN] = {
        .bplFileName = "S02",
        .bpcFileName = "S02c",
        .bmaFileName = "S02m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_INTRO] = {
        .bplFileName = "S03",
        .bpcFileName = "S03c",
        .bmaFileName = "S03m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_LOGO_POKEMON_COMPANY] = {
        .bplFileName = "S04",
        .bpcFileName = "S04c",
        .bmaFileName = "S04m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_LOGO_WARNING] = {
        .bplFileName = "S05",
        .bpcFileName = "S05c",
        .bmaFileName = "S05m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_TEAM_BASE_WALL_MAP] = {
        .bplFileName = "S06",
        .bpcFileName = "S06c",
        .bmaFileName = "S06m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_W01] = {
        .bplFileName = "W01",
        .bpcFileName = "W01c",
        .bmaFileName = "W01m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_W03_PO1] = {
        .bplFileName = "W03P01",
        .bpcFileName = "W03P01c",
        .bmaFileName = "W03P01m",
        .bpaFileNames = {"W03P011", NULL, NULL, NULL},
    },
    [MAP_FILE_ID_W03_PO2] = {
        .bplFileName = "W03P02",
        .bpcFileName = "W03P02c",
        .bmaFileName = "W03P02m",
        .bpaFileNames = {"W03P021", NULL, NULL, NULL},
    },
    [MAP_FILE_ID_W03_PO3] = {
        .bplFileName = "W03P03",
        .bpcFileName = "W03P03c",
        .bmaFileName = "W03P03m",
        .bpaFileNames = {"W03P031", NULL, NULL, NULL},
    },
    [MAP_FILE_ID_W04] = {
        .bplFileName = "W04",
        .bpcFileName = "W04c",
        .bmaFileName = "W04m",
        .bpaFileNames = {"W041", NULL, NULL, NULL},
    },
    [MAP_FILE_ID_W05] = {
        .bplFileName = "W05",
        .bpcFileName = "W05c",
        .bmaFileName = "W05m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
    [MAP_FILE_ID_W06] = {
        .bplFileName = "W06",
        .bpcFileName = "W06c",
        .bmaFileName = "W06m",
        .bpaFileNames = {NULL, NULL, NULL, NULL},
    },
};
