#include "global.h"
#include "globaldata.h"
#include "monster_gfx.h"

#include "data/ax/unowna.h"
#include "data/ax/unownb.h"
#include "data/ax/unownc.h"
#include "data/ax/unownd.h"
#include "data/ax/unowne.h"
#include "data/ax/unownf.h"
#include "data/ax/unowng.h"
#include "data/ax/unownh.h"
#include "data/ax/unowni.h"
#include "data/ax/unownj.h"
