#include "global.h"
#include "globaldata.h"
#include "monster_gfx.h"

#include "data/ax/cradily.h"
#include "data/ax/anorith.h"
#include "data/ax/armaldo.h"
#include "data/ax/feebas.h"
#include "data/ax/milotic.h"
#include "data/ax/castform.h"
#include "data/ax/castformsnowy.h"
#include "data/ax/castformsunny.h"
#include "data/ax/castformrainy.h"
#include "data/ax/kecleon.h"
