#include "global.h"
#include "globaldata.h"
#include "monster_gfx.h"

#include "data/ax/electrode.h"
#include "data/ax/exeggcute.h"
#include "data/ax/exeggutor.h"
#include "data/ax/cubone.h"
#include "data/ax/marowak.h"
#include "data/ax/hitmonlee.h"
#include "data/ax/hitmonchan.h"
#include "data/ax/lickitung.h"
#include "data/ax/koffing.h"
#include "data/ax/weezing.h"
