#include "global.h"
#include "globaldata.h"
#include "monster_gfx.h"

#include "data/ax/ampharos.h"
#include "data/ax/bellossom.h"
#include "data/ax/marill.h"
#include "data/ax/azumarill.h"
#include "data/ax/sudowoodo.h"
#include "data/ax/politoed.h"
#include "data/ax/hoppip.h"
#include "data/ax/skiploom.h"
#include "data/ax/jumpluff.h"
#include "data/ax/aipom.h"
