#include "global.h"
#include "globaldata.h"
#include "monster_gfx.h"

#include "data/ax/kabutops.h"
#include "data/ax/aerodactyl.h"
#include "data/ax/snorlax.h"
#include "data/ax/articuno.h"
#include "data/ax/zapdos.h"
#include "data/ax/moltres.h"
#include "data/ax/dratini.h"
#include "data/ax/dragonair.h"
#include "data/ax/dragonite.h"
#include "data/ax/mewtwo.h"
