#include "global.h"
#include "globaldata.h"
#include "monster_gfx.h"

#include "data/ax/nidoqueen.h"
#include "data/ax/nidoranm.h"
#include "data/ax/nidorino.h"
#include "data/ax/nidoking.h"
#include "data/ax/clefairy.h"
#include "data/ax/clefable.h"
#include "data/ax/vulpix.h"
#include "data/ax/ninetales.h"
#include "data/ax/jigglypuff.h"
#include "data/ax/wigglytuff.h"
