#include "global.h"
#include "globaldata.h"
#include "monster_gfx.h"

#include "data/ax/shuppet.h"
#include "data/ax/banette.h"
#include "data/ax/duskull.h"
#include "data/ax/dusclops.h"
#include "data/ax/tropius.h"
#include "data/ax/chimecho.h"
#include "data/ax/absol.h"
#include "data/ax/wynaut.h"
#include "data/ax/snorunt.h"
#include "data/ax/glalie.h"
