#include "global.h"
#include "globaldata.h"
#include "monster_gfx.h"

#include "data/ax/gulpin.h"
#include "data/ax/swalot.h"
#include "data/ax/carvanha.h"
#include "data/ax/sharpedo.h"
#include "data/ax/wailmer.h"
#include "data/ax/wailord.h"
#include "data/ax/numel.h"
#include "data/ax/camerupt.h"
#include "data/ax/torkoal.h"
#include "data/ax/spoink.h"
