#include "global.h"
#include "globaldata.h"
#include "monster_gfx.h"

#include "data/ax/seviper.h"
#include "data/ax/lunatone.h"
#include "data/ax/solrock.h"
#include "data/ax/barboach.h"
#include "data/ax/whiscash.h"
#include "data/ax/corphish.h"
#include "data/ax/crawdaunt.h"
#include "data/ax/baltoy.h"
#include "data/ax/claydol.h"
#include "data/ax/lileep.h"
