#include "global.h"
#include "globaldata.h"
#include "monster_gfx.h"

#include "data/ax/dugtrio.h"
#include "data/ax/meowth.h"
#include "data/ax/persian.h"
#include "data/ax/psyduck.h"
#include "data/ax/golduck.h"
#include "data/ax/mankey.h"
#include "data/ax/primeape.h"
#include "data/ax/growlithe.h"
#include "data/ax/arcanine.h"
#include "data/ax/poliwag.h"
