#include "global.h"
#include "globaldata.h"
#include "monster_gfx.h"

#include "data/ax/spearow.h"
#include "data/ax/fearow.h"
#include "data/ax/ekans.h"
#include "data/ax/arbok.h"
#include "data/ax/pikachu.h"
#include "data/ax/raichu.h"
#include "data/ax/sandshrew.h"
#include "data/ax/sandslash.h"
#include "data/ax/nidoranf.h"
#include "data/ax/nidorina.h"
