#include "global.h"
#include "globaldata.h"
#include "monster_gfx.h"

#include "data/ax/mew.h"
#include "data/ax/chikorita.h"
#include "data/ax/bayleef.h"
#include "data/ax/meganium.h"
#include "data/ax/cyndaquil.h"
#include "data/ax/quilava.h"
#include "data/ax/typhlosion.h"
#include "data/ax/totodile.h"
#include "data/ax/croconaw.h"
#include "data/ax/feraligatr.h"
