#include "global.h"
#include "globaldata.h"
#include "monster_gfx.h"

#include "data/ax/unownk.h"
#include "data/ax/unownl.h"
#include "data/ax/unownm.h"
#include "data/ax/unownn.h"
#include "data/ax/unowno.h"
#include "data/ax/unownp.h"
#include "data/ax/unownq.h"
#include "data/ax/unownr.h"
#include "data/ax/unowns.h"
#include "data/ax/unownt.h"
