#include "global.h"
#include "globaldata.h"
#include "monster_gfx.h"

#include "data/ax/magnemite.h"
#include "data/ax/magneton.h"
#include "data/ax/farfetchd.h"
#include "data/ax/doduo.h"
#include "data/ax/dodrio.h"
#include "data/ax/seel.h"
#include "data/ax/dewgong.h"
#include "data/ax/grimer.h"
#include "data/ax/muk.h"
#include "data/ax/shellder.h"
