#include "global.h"
#include "globaldata.h"
#include "monster_gfx.h"

#include "data/ax/breloom.h"
#include "data/ax/slakoth.h"
#include "data/ax/vigoroth.h"
#include "data/ax/slaking.h"
#include "data/ax/nincada.h"
#include "data/ax/ninjask.h"
#include "data/ax/shedinja.h"
#include "data/ax/whismur.h"
#include "data/ax/loudred.h"
#include "data/ax/exploud.h"
