#include "global.h"
#include "globaldata.h"
#include "monster_gfx.h"

#include "data/ax/zubat.h"
#include "data/ax/golbat.h"
#include "data/ax/oddish.h"
#include "data/ax/gloom.h"
#include "data/ax/vileplume.h"
#include "data/ax/paras.h"
#include "data/ax/parasect.h"
#include "data/ax/venonat.h"
#include "data/ax/venomoth.h"
#include "data/ax/diglett.h"
