#include "global.h"
#include "globaldata.h"
#include "monster_gfx.h"

#include "data/ax/rhyhorn.h"
#include "data/ax/rhydon.h"
#include "data/ax/chansey.h"
#include "data/ax/tangela.h"
#include "data/ax/kangaskhan.h"
#include "data/ax/horsea.h"
#include "data/ax/seadra.h"
#include "data/ax/goldeen.h"
#include "data/ax/seaking.h"
#include "data/ax/staryu.h"
