#include "global.h"
#include "globaldata.h"
#include "monster_gfx.h"

#include "data/ax/unownu.h"
#include "data/ax/unownv.h"
#include "data/ax/unownw.h"
#include "data/ax/unownx.h"
#include "data/ax/unowny.h"
#include "data/ax/unownz.h"
#include "data/ax/wobbuffet.h"
#include "data/ax/girafarig.h"
#include "data/ax/pineco.h"
#include "data/ax/forretress.h"
