#include "global.h"
#include "globaldata.h"
#include "monster_gfx.h"

#include "data/ax/teddiursa.h"
#include "data/ax/ursaring.h"
#include "data/ax/slugma.h"
#include "data/ax/magcargo.h"
#include "data/ax/swinub.h"
#include "data/ax/piloswine.h"
#include "data/ax/corsola.h"
#include "data/ax/remoraid.h"
#include "data/ax/octillery.h"
#include "data/ax/delibird.h"
