#include "global.h"
#include "globaldata.h"
#include "monster_gfx.h"

#include "data/ax/victreebel.h"
#include "data/ax/tentacool.h"
#include "data/ax/tentacruel.h"
#include "data/ax/geodude.h"
#include "data/ax/graveler.h"
#include "data/ax/golem.h"
#include "data/ax/ponyta.h"
#include "data/ax/rapidash.h"
#include "data/ax/slowpoke.h"
#include "data/ax/slowbro.h"
