#include "global.h"
#include "globaldata.h"
#include "monster_gfx.h"

#include "data/ax/makuhita.h"
#include "data/ax/hariyama.h"
#include "data/ax/azurill.h"
#include "data/ax/nosepass.h"
#include "data/ax/skitty.h"
#include "data/ax/delcatty.h"
#include "data/ax/sableye.h"
#include "data/ax/mawile.h"
#include "data/ax/aron.h"
#include "data/ax/lairon.h"
