#include "global.h"
#include "globaldata.h"
#include "monster_gfx.h"

#include "data/ax/lanturn.h"
#include "data/ax/pichu.h"
#include "data/ax/cleffa.h"
#include "data/ax/igglybuff.h"
#include "data/ax/togepi.h"
#include "data/ax/togetic.h"
#include "data/ax/natu.h"
#include "data/ax/xatu.h"
#include "data/ax/mareep.h"
#include "data/ax/flaaffy.h"
