#include "global.h"
#include "globaldata.h"
#include "monster_gfx.h"

#include "data/ax/lapras.h"
#include "data/ax/ditto.h"
#include "data/ax/eevee.h"
#include "data/ax/vaporeon.h"
#include "data/ax/jolteon.h"
#include "data/ax/flareon.h"
#include "data/ax/porygon.h"
#include "data/ax/omanyte.h"
#include "data/ax/omastar.h"
#include "data/ax/kabuto.h"
