#include "global.h"
#include "globaldata.h"
#include "monster_gfx.h"

#include "data/ax/dunsparce.h"
#include "data/ax/gligar.h"
#include "data/ax/steelix.h"
#include "data/ax/snubbull.h"
#include "data/ax/granbull.h"
#include "data/ax/qwilfish.h"
#include "data/ax/scizor.h"
#include "data/ax/shuckle.h"
#include "data/ax/heracross.h"
#include "data/ax/sneasel.h"
