#include "global.h"
#include "globaldata.h"
#include "monster_gfx.h"

#include "data/ax/salamence.h"
#include "data/ax/beldum.h"
#include "data/ax/metang.h"
#include "data/ax/metagross.h"
#include "data/ax/regirock.h"
#include "data/ax/regice.h"
#include "data/ax/registeel.h"
#include "data/ax/latias.h"
#include "data/ax/latios.h"
#include "data/ax/kyogre.h"
