#include "global.h"
#include "globaldata.h"
#include "monster_gfx.h"

#include "data/ax/metapod.h"
#include "data/ax/butterfree.h"
#include "data/ax/weedle.h"
#include "data/ax/kakuna.h"
#include "data/ax/beedrill.h"
#include "data/ax/pidgey.h"
#include "data/ax/pidgeotto.h"
#include "data/ax/pidgeot.h"
#include "data/ax/rattata.h"
#include "data/ax/raticate.h"
