#include "global.h"
#include "globaldata.h"
#include "monster_gfx.h"

#include "data/ax/taillow.h"
#include "data/ax/swellow.h"
#include "data/ax/wingull.h"
#include "data/ax/pelipper.h"
#include "data/ax/ralts.h"
#include "data/ax/kirlia.h"
#include "data/ax/gardevoir.h"
#include "data/ax/surskit.h"
#include "data/ax/masquerain.h"
#include "data/ax/shroomish.h"
