#include "global.h"
#include "globaldata.h"
#include "monster_gfx.h"

#include "data/ax/tyrogue.h"
#include "data/ax/hitmontop.h"
#include "data/ax/smoochum.h"
#include "data/ax/elekid.h"
#include "data/ax/magby.h"
#include "data/ax/miltank.h"
#include "data/ax/blissey.h"
#include "data/ax/raikou.h"
#include "data/ax/entei.h"
#include "data/ax/suicune.h"
