#include "global.h"
#include "globaldata.h"
#include "monster_gfx.h"

#include "data/ax/larvitar.h"
#include "data/ax/pupitar.h"
#include "data/ax/tyranitar.h"
#include "data/ax/lugia.h"
#include "data/ax/hooh.h"
#include "data/ax/celebi.h"
#include "data/ax/treecko.h"
#include "data/ax/grovyle.h"
#include "data/ax/sceptile.h"
#include "data/ax/torchic.h"
