#include "global.h"
#include "globaldata.h"
#include "monster_gfx.h"

#include "data/ax/silcoon.h"
#include "data/ax/beautifly.h"
#include "data/ax/cascoon.h"
#include "data/ax/dustox.h"
#include "data/ax/lotad.h"
#include "data/ax/lombre.h"
#include "data/ax/ludicolo.h"
#include "data/ax/seedot.h"
#include "data/ax/nuzleaf.h"
#include "data/ax/shiftry.h"
