#include "global.h"
#include "globaldata.h"
#include "monster_gfx.h"

#include "data/ax/sentret.h"
#include "data/ax/furret.h"
#include "data/ax/hoothoot.h"
#include "data/ax/noctowl.h"
#include "data/ax/ledyba.h"
#include "data/ax/ledian.h"
#include "data/ax/spinarak.h"
#include "data/ax/ariados.h"
#include "data/ax/crobat.h"
#include "data/ax/chinchou.h"
