#include "global.h"
#include "globaldata.h"
#include "monster_gfx.h"

#include "data/ax/starmie.h"
#include "data/ax/mrmime.h"
#include "data/ax/scyther.h"
#include "data/ax/jynx.h"
#include "data/ax/electabuzz.h"
#include "data/ax/magmar.h"
#include "data/ax/pinsir.h"
#include "data/ax/tauros.h"
#include "data/ax/magikarp.h"
#include "data/ax/gyarados.h"
