#include "global.h"
#include "globaldata.h"
#include "monster_gfx.h"

#include "data/ax/groudon.h"
#include "data/ax/rayquaza.h"
#include "data/ax/jirachi.h"
#include "data/ax/deoxysnormal.h"
#include "data/ax/unownemark.h"
#include "data/ax/unownqmark.h"
#include "data/ax/deoxysattack.h"
#include "data/ax/deoxysdefense.h"
#include "data/ax/deoxysspeed.h"
#include "data/ax/munchlax.h"
