#include "global.h"
#include "globaldata.h"
#include "monster_gfx.h"

#include "data/ax/grumpig.h"
#include "data/ax/spinda.h"
#include "data/ax/trapinch.h"
#include "data/ax/vibrava.h"
#include "data/ax/flygon.h"
#include "data/ax/cacnea.h"
#include "data/ax/cacturne.h"
#include "data/ax/swablu.h"
#include "data/ax/altaria.h"
#include "data/ax/zangoose.h"
