#include "global.h"
#include "globaldata.h"
#include "monster_gfx.h"

#include "data/ax/sunkern.h"
#include "data/ax/sunflora.h"
#include "data/ax/yanma.h"
#include "data/ax/wooper.h"
#include "data/ax/quagsire.h"
#include "data/ax/espeon.h"
#include "data/ax/umbreon.h"
#include "data/ax/murkrow.h"
#include "data/ax/slowking.h"
#include "data/ax/misdreavus.h"
