#include "global.h"
#include "globaldata.h"
#include "monster_gfx.h"

#include "data/ax/spheal.h"
#include "data/ax/sealeo.h"
#include "data/ax/walrein.h"
#include "data/ax/clamperl.h"
#include "data/ax/huntail.h"
#include "data/ax/gorebyss.h"
#include "data/ax/relicanth.h"
#include "data/ax/luvdisc.h"
#include "data/ax/bagon.h"
#include "data/ax/shelgon.h"
