#include "global.h"
#include "globaldata.h"
#include "monster_gfx.h"

#include "data/ax/combusken.h"
#include "data/ax/blaziken.h"
#include "data/ax/mudkip.h"
#include "data/ax/marshtomp.h"
#include "data/ax/swampert.h"
#include "data/ax/poochyena.h"
#include "data/ax/mightyena.h"
#include "data/ax/zigzagoon.h"
#include "data/ax/linoone.h"
#include "data/ax/wurmple.h"
