#include "global.h"
#include "globaldata.h"
#include "monster_gfx.h"

#include "data/ax/aggron.h"
#include "data/ax/meditite.h"
#include "data/ax/medicham.h"
#include "data/ax/electrike.h"
#include "data/ax/manectric.h"
#include "data/ax/plusle.h"
#include "data/ax/minun.h"
#include "data/ax/volbeat.h"
#include "data/ax/illumise.h"
#include "data/ax/roselia.h"
