#include "global.h"
#include "globaldata.h"
#include "monster_gfx.h"

#include "data/ax/bulbasaur.h"
#include "data/ax/ivysaur.h"
#include "data/ax/venusaur.h"
#include "data/ax/charmander.h"
#include "data/ax/charmeleon.h"
#include "data/ax/charizard.h"
#include "data/ax/squirtle.h"
#include "data/ax/wartortle.h"
#include "data/ax/blastoise.h"
#include "data/ax/caterpie.h"
