#include "global.h"
#include "globaldata.h"
#include "monster_gfx.h"

#include "data/ax/mantine.h"
#include "data/ax/skarmory.h"
#include "data/ax/houndour.h"
#include "data/ax/houndoom.h"
#include "data/ax/kingdra.h"
#include "data/ax/phanpy.h"
#include "data/ax/donphan.h"
#include "data/ax/porygon2.h"
#include "data/ax/stantler.h"
#include "data/ax/smeargle.h"
