#include "global.h"
#include "globaldata.h"
#include "monster_gfx.h"

#include "data/ax/cloyster.h"
#include "data/ax/gastly.h"
#include "data/ax/haunter.h"
#include "data/ax/gengar.h"
#include "data/ax/onix.h"
#include "data/ax/drowzee.h"
#include "data/ax/hypno.h"
#include "data/ax/krabby.h"
#include "data/ax/kingler.h"
#include "data/ax/voltorb.h"
