#include "global.h"
#include "globaldata.h"
#include "monster_gfx.h"

#include "data/ax/poliwhirl.h"
#include "data/ax/poliwrath.h"
#include "data/ax/abra.h"
#include "data/ax/kadabra.h"
#include "data/ax/alakazam.h"
#include "data/ax/machop.h"
#include "data/ax/machoke.h"
#include "data/ax/machamp.h"
#include "data/ax/bellsprout.h"
#include "data/ax/weepinbell.h"
