@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_516_grp, bank_026
	.equ	seq_516_pri, 127
	.equ	seq_516_rev, 0
	.equ	seq_516_mvl, 127
	.equ	seq_516_key, 0

	.section .rodata
	.global	seq_516
	.align	2

@*********************** Track 01 ***********************@

seq_516_0:
	.byte	KEYSH , seq_516_key+0
	.byte	TEMPO , 250/2
	.byte		VOICE , 43
	.byte		VOL   , 100*seq_516_mvl/mxv
	.byte		PAN   , c_v+0
	.byte	W01
	.byte		MOD   , 50
	.byte		BEND  , c_v-15
	.byte	W05
	.byte		BEND  , c_v-19
	.byte		N09   , Fn3 , v127
	.byte		N09   , An3 
	.byte	W01
	.byte		BEND  , c_v-22
	.byte	W01
	.byte		        c_v-25
	.byte	W01
	.byte		        c_v-28
	.byte	W05
	.byte		        c_v-19
	.byte	W01
	.byte		        c_v-1
	.byte	W01
	.byte		        c_v+17
	.byte		N07   , Gs3 , v060
	.byte		N07   , Cn4 
	.byte	W01
	.byte		BEND  , c_v+20
	.byte	W01
	.byte	W01
	.byte		        c_v+28
	.byte	W01
	.byte		        c_v+32
	.byte	W01
	.byte		        c_v+37
	.byte	W01
	.byte		        c_v+44
	.byte	W02
	.byte	GOTO
	 .word	seq_516_0 + 0x10
	.byte	FINE

@******************************************************@

	.align	2

seq_516:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_516_pri	@ Priority
	.byte	seq_516_rev	@ Reverb

	.word	seq_516_grp

	.word	seq_516_0

	.end
