@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_507_grp, bank_026
	.equ	seq_507_pri, 127
	.equ	seq_507_rev, 0
	.equ	seq_507_mvl, 127
	.equ	seq_507_key, 0

	.section .rodata
	.global	seq_507
	.align	2

@*********************** Track 01 ***********************@

seq_507_0:
	.byte	KEYSH , seq_507_key+0
	.byte	TEMPO , 200/2
	.byte	W03
	.byte	W09
	.byte		VOICE , 20
	.byte		MOD   , 15
	.byte		PAN   , c_v+0
	.byte	W01
	.byte		BENDR , 40
	.byte		LFOS  , 65
	.byte		MODT  , mod_pan
	.byte	W02
	.byte		VOL   , 0*seq_507_mvl/mxv
	.byte		BEND  , c_v-26
	.byte	W01
	.byte		TIE   , As2 , v127
	.byte	W01
	.byte		VOL   , 4*seq_507_mvl/mxv
	.byte	W03
	.byte		        5*seq_507_mvl/mxv
	.byte	W01
	.byte		BEND  , c_v-22
	.byte	W01
	.byte		VOL   , 7*seq_507_mvl/mxv
	.byte	W02
	.byte		        8*seq_507_mvl/mxv
	.byte	W03
	.byte		        11*seq_507_mvl/mxv
	.byte	W01
	.byte		BEND  , c_v-21
	.byte	W01
	.byte		VOL   , 12*seq_507_mvl/mxv
	.byte	W02
	.byte		        13*seq_507_mvl/mxv
	.byte	W03
	.byte		        16*seq_507_mvl/mxv
	.byte	W02
	.byte		        19*seq_507_mvl/mxv
	.byte		BEND  , c_v-15
	.byte	W02
	.byte		VOL   , 21*seq_507_mvl/mxv
	.byte		BEND  , c_v-14
	.byte	W01
	.byte		        c_v-13
	.byte	W01
	.byte		        c_v-12
	.byte	W01
	.byte		VOL   , 28*seq_507_mvl/mxv
	.byte		BEND  , c_v-11
	.byte	W01
	.byte		        c_v-10
	.byte	W01
	.byte		VOL   , 31*seq_507_mvl/mxv
	.byte	W01
	.byte		BEND  , c_v-9
	.byte	W01
	.byte		VOL   , 36*seq_507_mvl/mxv
	.byte		BEND  , c_v-8
	.byte	W01
	.byte		        c_v-7
	.byte	W01
	.byte		        c_v-6
	.byte	W01
	.byte		VOL   , 42*seq_507_mvl/mxv
	.byte		BEND  , c_v-5
	.byte	W02
	.byte		VOL   , 45*seq_507_mvl/mxv
	.byte		BEND  , c_v-4
	.byte	W01
	.byte		        c_v-3
	.byte	W01
	.byte		VOL   , 48*seq_507_mvl/mxv
	.byte		BEND  , c_v-2
	.byte	W01
	.byte		        c_v-1
	.byte	W01
	.byte		        c_v+0
	.byte	W01
	.byte		VOL   , 55*seq_507_mvl/mxv
	.byte		BEND  , c_v+1
	.byte	W02
	.byte		VOL   , 59*seq_507_mvl/mxv
	.byte		BEND  , c_v+2
	.byte	W01
	.byte		        c_v+3
	.byte	W01
	.byte		VOL   , 62*seq_507_mvl/mxv
	.byte		BEND  , c_v+4
	.byte	W01
	.byte		        c_v+5
	.byte	W01
	.byte		        c_v+6
	.byte	W01
	.byte		VOL   , 70*seq_507_mvl/mxv
	.byte	W01
	.byte		BEND  , c_v+7
	.byte	W01
	.byte		VOL   , 75*seq_507_mvl/mxv
	.byte		BEND  , c_v+8
	.byte	W01
	.byte		        c_v+9
	.byte	W01
	.byte		VOL   , 80*seq_507_mvl/mxv
	.byte		BEND  , c_v+10
	.byte	W01
	.byte		        c_v+11
	.byte	W02
	.byte		MOD   , 18
	.byte		VOL   , 90*seq_507_mvl/mxv
	.byte		BEND  , c_v+12
	.byte	W01
	.byte		        c_v+13
	.byte	W01
	.byte		VOL   , 95*seq_507_mvl/mxv
	.byte		BEND  , c_v+14
	.byte	W01
	.byte		        c_v+15
	.byte	W01
	.byte		VOL   , 103*seq_507_mvl/mxv
	.byte		BEND  , c_v+16
	.byte	W02
	.byte	W01
	.byte		VOL   , 118*seq_507_mvl/mxv
	.byte	W02
	.byte		        114*seq_507_mvl/mxv
	.byte	W02
	.byte		        111*seq_507_mvl/mxv
	.byte	W02
	.byte		MOD   , 20
	.byte		VOL   , 107*seq_507_mvl/mxv
	.byte	W02
	.byte		        104*seq_507_mvl/mxv
	.byte	W03
	.byte		        100*seq_507_mvl/mxv
	.byte	W03
	.byte		        96*seq_507_mvl/mxv
	.byte	W03
	.byte		        93*seq_507_mvl/mxv
	.byte	W01
	.byte		MOD   , 23
	.byte	W02
	.byte		VOL   , 89*seq_507_mvl/mxv
	.byte	W03
	.byte		        87*seq_507_mvl/mxv
	.byte	W03
	.byte		        83*seq_507_mvl/mxv
	.byte	W03
	.byte		        78*seq_507_mvl/mxv
	.byte	W01
	.byte		MOD   , 25
	.byte	W02
	.byte		VOL   , 74*seq_507_mvl/mxv
	.byte	W03
	.byte		        72*seq_507_mvl/mxv
	.byte	W03
	.byte		        69*seq_507_mvl/mxv
	.byte	W03
	.byte		        67*seq_507_mvl/mxv
	.byte	W02
	.byte		MOD   , 28
	.byte	W01
	.byte		VOL   , 64*seq_507_mvl/mxv
	.byte	W03
	.byte		        62*seq_507_mvl/mxv
	.byte	W03
	.byte		        60*seq_507_mvl/mxv
	.byte	W05
	.byte		MOD   , 31
	.byte	W01
	.byte		VOL   , 56*seq_507_mvl/mxv
	.byte	W03
	.byte	W03
	.byte		        51*seq_507_mvl/mxv
	.byte	W05
	.byte		MOD   , 33
	.byte	W01
	.byte		VOL   , 47*seq_507_mvl/mxv
	.byte	W03
	.byte	W03
	.byte		        45*seq_507_mvl/mxv
	.byte	W05
	.byte		MOD   , 36
	.byte	W01
	.byte		VOL   , 42*seq_507_mvl/mxv
	.byte	W03
	.byte	W03
	.byte		        39*seq_507_mvl/mxv
	.byte	W06
	.byte		MOD   , 39
	.byte		VOL   , 36*seq_507_mvl/mxv
	.byte	W03
	.byte	W03
	.byte		        33*seq_507_mvl/mxv
	.byte	W06
	.byte		MOD   , 41
	.byte		VOL   , 30*seq_507_mvl/mxv
	.byte	W03
	.byte	W03
	.byte		        27*seq_507_mvl/mxv
	.byte	W06
	.byte		MOD   , 44
	.byte		VOL   , 24*seq_507_mvl/mxv
	.byte	W03
	.byte	W03
	.byte		        21*seq_507_mvl/mxv
	.byte	W06
	.byte		MOD   , 46
	.byte		VOL   , 18*seq_507_mvl/mxv
	.byte	W03
	.byte	W03
	.byte		        15*seq_507_mvl/mxv
	.byte	W03
	.byte		        14*seq_507_mvl/mxv
	.byte	W03
	.byte		        13*seq_507_mvl/mxv
	.byte	W01
	.byte		MOD   , 49
	.byte	W02
	.byte		VOL   , 11*seq_507_mvl/mxv
	.byte	W03
	.byte		        10*seq_507_mvl/mxv
	.byte	W03
	.byte		        8*seq_507_mvl/mxv
	.byte	W03
	.byte		        7*seq_507_mvl/mxv
	.byte	W01
	.byte		MOD   , 52
	.byte	W02
	.byte		VOL   , 5*seq_507_mvl/mxv
	.byte	W03
	.byte		        4*seq_507_mvl/mxv
	.byte	W03
	.byte		        0*seq_507_mvl/mxv
	.byte	W06
	.byte	W02
	.byte		EOT
	.byte	FINE

@*********************** Track 02 ***********************@

seq_507_1:
	.byte	KEYSH , seq_507_key+0
	.byte		VOICE , 44
	.byte		MOD   , 60
	.byte		PAN   , c_v+0
	.byte	W01
	.byte		BENDR , 25
	.byte		LFOS  , 32
	.byte		MODT  , mod_pan
	.byte	W02
	.byte		VOL   , 4*seq_507_mvl/mxv
	.byte		BEND  , c_v-26
	.byte	W01
	.byte		N44   , Ds3 , v127
	.byte	W01
	.byte		VOL   , 15*seq_507_mvl/mxv
	.byte	W03
	.byte		        35*seq_507_mvl/mxv
	.byte	W01
	.byte		BEND  , c_v-22
	.byte	W01
	.byte		VOL   , 43*seq_507_mvl/mxv
	.byte	W02
	.byte		        50*seq_507_mvl/mxv
	.byte	W03
	.byte		        62*seq_507_mvl/mxv
	.byte	W01
	.byte		BEND  , c_v-21
	.byte	W01
	.byte		VOL   , 68*seq_507_mvl/mxv
	.byte	W02
	.byte		        74*seq_507_mvl/mxv
	.byte	W03
	.byte		        84*seq_507_mvl/mxv
	.byte	W01
	.byte		BEND  , c_v-20
	.byte	W01
	.byte		VOL   , 93*seq_507_mvl/mxv
	.byte	W02
	.byte		        98*seq_507_mvl/mxv
	.byte	W01
	.byte	W02
	.byte		        108*seq_507_mvl/mxv
	.byte	W01
	.byte		BEND  , c_v-18
	.byte	W01
	.byte		VOL   , 116*seq_507_mvl/mxv
	.byte	W02
	.byte		        122*seq_507_mvl/mxv
	.byte	W03
	.byte		        125*seq_507_mvl/mxv
	.byte	W01
	.byte		BEND  , c_v-17
	.byte	W01
	.byte		VOL   , 125*seq_507_mvl/mxv
	.byte	W01
	.byte	W01
	.byte		        125*seq_507_mvl/mxv
	.byte	W03
	.byte		        125*seq_507_mvl/mxv
	.byte	W02
	.byte		        125*seq_507_mvl/mxv
	.byte		BEND  , c_v-15
	.byte	W02
	.byte		VOL   , 125*seq_507_mvl/mxv
	.byte	W03
	.byte		        125*seq_507_mvl/mxv
	.byte	W01
	.byte		N44
	.byte	W01
	.byte		VOL   , 125*seq_507_mvl/mxv
	.byte		BEND  , c_v-10
	.byte	W11
	.byte	W12
	.byte	W12
	.byte	W12
	.byte		VOICE , 5
	.byte		MOD   , 15
	.byte		PAN   , c_v+0
	.byte	W01
	.byte		BENDR , 27
	.byte		LFOS  , 32
	.byte		MODT  , mod_pan
	.byte	W02
	.byte		VOL   , 3*seq_507_mvl/mxv
	.byte		BEND  , c_v-26
	.byte	W01
	.byte		TIE   , Ds2 
	.byte	W01
	.byte		VOL   , 4*seq_507_mvl/mxv
	.byte	W03
	.byte		        5*seq_507_mvl/mxv
	.byte	W01
	.byte		BEND  , c_v-21
	.byte	W01
	.byte		VOL   , 6*seq_507_mvl/mxv
	.byte	W02
	.byte		        7*seq_507_mvl/mxv
	.byte	W03
	.byte		        9*seq_507_mvl/mxv
	.byte	W01
	.byte		BEND  , c_v-19
	.byte	W01
	.byte		VOL   , 11*seq_507_mvl/mxv
	.byte	W02
	.byte		        13*seq_507_mvl/mxv
	.byte	W03
	.byte		        16*seq_507_mvl/mxv
	.byte	W01
	.byte		BEND  , c_v-15
	.byte	W01
	.byte		VOL   , 17*seq_507_mvl/mxv
	.byte	W02
	.byte		        20*seq_507_mvl/mxv
	.byte	W03
	.byte		        23*seq_507_mvl/mxv
	.byte	W01
	.byte		BEND  , c_v-12
	.byte	W01
	.byte		VOL   , 25*seq_507_mvl/mxv
	.byte	W02
	.byte		        27*seq_507_mvl/mxv
	.byte	W03
	.byte		        32*seq_507_mvl/mxv
	.byte	W01
	.byte		BEND  , c_v-9
	.byte	W01
	.byte		VOL   , 35*seq_507_mvl/mxv
	.byte	W02
	.byte		        39*seq_507_mvl/mxv
	.byte	W03
	.byte		        44*seq_507_mvl/mxv
	.byte	W02
	.byte		        50*seq_507_mvl/mxv
	.byte		BEND  , c_v-3
	.byte	W02
	.byte		VOL   , 56*seq_507_mvl/mxv
	.byte	W01
	.byte	W02
	.byte		        65*seq_507_mvl/mxv
	.byte	W02
	.byte		        74*seq_507_mvl/mxv
	.byte		BEND  , c_v+2
	.byte	W02
	.byte		VOL   , 83*seq_507_mvl/mxv
	.byte	W03
	.byte		        98*seq_507_mvl/mxv
	.byte	W02
	.byte		        102*seq_507_mvl/mxv
	.byte		BEND  , c_v+7
	.byte	W01
	.byte	W01
	.byte		VOL   , 115*seq_507_mvl/mxv
	.byte	W03
	.byte		        125*seq_507_mvl/mxv
	.byte	W01
	.byte		MOD   , 50
	.byte	W01
	.byte		BEND  , c_v+13
	.byte	W06
	.byte	W12
	.byte	W12
	.byte	W12
	.byte	W12
	.byte	W12
	.byte	W12
	.byte	W12
	.byte	W02
	.byte		EOT
	.byte	FINE

@******************************************************@

	.align	2

seq_507:
	.byte	2	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_507_pri	@ Priority
	.byte	seq_507_rev	@ Reverb

	.word	seq_507_grp

	.word	seq_507_0
	.word	seq_507_1

	.end
