@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_359_grp, bank_027
	.equ	seq_359_pri, 100
	.equ	seq_359_rev, 0
	.equ	seq_359_mvl, 127
	.equ	seq_359_key, 0

	.section .rodata
	.global	seq_359
	.align	2

@*********************** Track 01 ***********************@

seq_359_0:
	.byte	KEYSH , seq_359_key+0
	.byte	TEMPO , 150/2
	.byte		VOICE , 4
	.byte		VOL   , 90*seq_359_mvl/mxv
	.byte		PAN   , c_v+0
	.byte		N03   , Cn3 , v127
	.byte	W03
	.byte		        Dn3 
	.byte	W03
	.byte		        En3 
	.byte	W03
	.byte		        Gs3 
	.byte	W03
	.byte		VOICE , 1
	.byte		N06   , Fs3 
	.byte	W06
	.byte		N03   , Fs3 , v024
	.byte	W03
	.byte	FINE

@******************************************************@

	.align	2

seq_359:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_359_pri	@ Priority
	.byte	seq_359_rev	@ Reverb

	.word	seq_359_grp

	.word	seq_359_0

	.end
