@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_518_grp, bank_026
	.equ	seq_518_pri, 127
	.equ	seq_518_rev, 0
	.equ	seq_518_mvl, 127
	.equ	seq_518_key, 0

	.section .rodata
	.global	seq_518
	.align	2

@*********************** Track 01 ***********************@

seq_518_0:
	.byte	KEYSH , seq_518_key+0
	.byte	TEMPO , 160/2
	.byte		VOICE , 20
	.byte	W01
	.byte		VOL   , 32*seq_518_mvl/mxv
	.byte	W01
	.byte		PAN   , c_v+0
	.byte		VOL   , 37*seq_518_mvl/mxv
	.byte		TIE   , Fs3 , v120
	.byte	W01
	.byte		BENDR , 13
	.byte		TIE   , Gs2 
	.byte	W01
	.byte		VOL   , 37*seq_518_mvl/mxv
	.byte	W01
	.byte		        38*seq_518_mvl/mxv
	.byte	W01
	.byte		        39*seq_518_mvl/mxv
	.byte	W01
	.byte		        40*seq_518_mvl/mxv
	.byte	W01
	.byte		        41*seq_518_mvl/mxv
	.byte	W01
	.byte		        43*seq_518_mvl/mxv
	.byte	W01
	.byte		        44*seq_518_mvl/mxv
	.byte	W01
	.byte		        46*seq_518_mvl/mxv
	.byte	W01
	.byte		        48*seq_518_mvl/mxv
	.byte	W01
	.byte		        51*seq_518_mvl/mxv
	.byte	W01
	.byte		        53*seq_518_mvl/mxv
	.byte	W01
	.byte		        56*seq_518_mvl/mxv
	.byte	W01
	.byte		        59*seq_518_mvl/mxv
	.byte	W01
	.byte		        62*seq_518_mvl/mxv
	.byte	W01
	.byte		        66*seq_518_mvl/mxv
	.byte	W01
	.byte		        70*seq_518_mvl/mxv
	.byte	W01
	.byte		        73*seq_518_mvl/mxv
	.byte	W01
	.byte		        78*seq_518_mvl/mxv
	.byte	W04
	.byte		        76*seq_518_mvl/mxv
	.byte	W03
	.byte		        75*seq_518_mvl/mxv
	.byte	W01
	.byte		        74*seq_518_mvl/mxv
	.byte	W01
	.byte		        73*seq_518_mvl/mxv
	.byte	W01
	.byte		        71*seq_518_mvl/mxv
	.byte	W01
	.byte		        69*seq_518_mvl/mxv
	.byte	W01
	.byte		        66*seq_518_mvl/mxv
	.byte	W01
	.byte		        64*seq_518_mvl/mxv
	.byte	W01
	.byte		        62*seq_518_mvl/mxv
	.byte	W01
	.byte		        59*seq_518_mvl/mxv
	.byte	W01
	.byte		        52*seq_518_mvl/mxv
	.byte	W03
	.byte		        44*seq_518_mvl/mxv
	.byte	W01
	.byte		        45*seq_518_mvl/mxv
	.byte	W01
	.byte		        46*seq_518_mvl/mxv
	.byte	W01
	.byte		        48*seq_518_mvl/mxv
	.byte	W01
	.byte		        50*seq_518_mvl/mxv
	.byte	W01
	.byte		        52*seq_518_mvl/mxv
	.byte	W01
	.byte		        57*seq_518_mvl/mxv
	.byte	W03
	.byte		        56*seq_518_mvl/mxv
	.byte	W01
	.byte		        55*seq_518_mvl/mxv
	.byte	W01
	.byte		        55*seq_518_mvl/mxv
	.byte	W01
	.byte		        54*seq_518_mvl/mxv
	.byte	W01
	.byte		        52*seq_518_mvl/mxv
	.byte	W01
	.byte		        51*seq_518_mvl/mxv
	.byte	W01
	.byte		        48*seq_518_mvl/mxv
	.byte	W01
	.byte		        47*seq_518_mvl/mxv
	.byte	W01
	.byte		        44*seq_518_mvl/mxv
	.byte	W01
	.byte		        42*seq_518_mvl/mxv
	.byte	W01
	.byte		        40*seq_518_mvl/mxv
	.byte	W01
	.byte		        37*seq_518_mvl/mxv
	.byte	W01
	.byte		        31*seq_518_mvl/mxv
	.byte	W02
	.byte		        37*seq_518_mvl/mxv
	.byte	W03
	.byte		        38*seq_518_mvl/mxv
	.byte	W01
	.byte		        40*seq_518_mvl/mxv
	.byte	W01
	.byte		        40*seq_518_mvl/mxv
	.byte	W01
	.byte		        42*seq_518_mvl/mxv
	.byte	W01
	.byte		        44*seq_518_mvl/mxv
	.byte	W01
	.byte		        45*seq_518_mvl/mxv
	.byte	W01
	.byte		        47*seq_518_mvl/mxv
	.byte	W01
	.byte		        49*seq_518_mvl/mxv
	.byte	W01
	.byte		        51*seq_518_mvl/mxv
	.byte	W01
	.byte		        54*seq_518_mvl/mxv
	.byte	W01
	.byte		        73*seq_518_mvl/mxv
	.byte	W04
	.byte		        72*seq_518_mvl/mxv
	.byte	W01
	.byte		        71*seq_518_mvl/mxv
	.byte	W02
	.byte		        70*seq_518_mvl/mxv
	.byte	W01
	.byte		        69*seq_518_mvl/mxv
	.byte	W01
	.byte		        68*seq_518_mvl/mxv
	.byte	W01
	.byte		        66*seq_518_mvl/mxv
	.byte	W01
	.byte		        66*seq_518_mvl/mxv
	.byte	W01
	.byte		        64*seq_518_mvl/mxv
	.byte	W01
	.byte		        62*seq_518_mvl/mxv
	.byte	W01
	.byte		        61*seq_518_mvl/mxv
	.byte	W01
	.byte		        59*seq_518_mvl/mxv
	.byte	W01
	.byte		        55*seq_518_mvl/mxv
	.byte	W01
	.byte		        52*seq_518_mvl/mxv
	.byte	W01
	.byte		        50*seq_518_mvl/mxv
	.byte	W01
	.byte		        48*seq_518_mvl/mxv
	.byte	W01
	.byte		        45*seq_518_mvl/mxv
	.byte	W01
	.byte		        42*seq_518_mvl/mxv
	.byte	W01
	.byte		        39*seq_518_mvl/mxv
	.byte	W01
	.byte		        37*seq_518_mvl/mxv
	.byte	W01
	.byte		        32*seq_518_mvl/mxv
	.byte	W03
	.byte		        31*seq_518_mvl/mxv
	.byte	W02
	.byte		        32*seq_518_mvl/mxv
	.byte	W01
	.byte		        33*seq_518_mvl/mxv
	.byte	W01
	.byte		        35*seq_518_mvl/mxv
	.byte	W01
	.byte		        37*seq_518_mvl/mxv
	.byte	W01
	.byte		        40*seq_518_mvl/mxv
	.byte	W01
	.byte		        46*seq_518_mvl/mxv
	.byte	W04
	.byte		        57*seq_518_mvl/mxv
	.byte	W04
	.byte		        56*seq_518_mvl/mxv
	.byte	W02
	.byte		        55*seq_518_mvl/mxv
	.byte	W01
	.byte		        55*seq_518_mvl/mxv
	.byte	W01
	.byte		        54*seq_518_mvl/mxv
	.byte	W01
	.byte		        53*seq_518_mvl/mxv
	.byte	W01
	.byte		        52*seq_518_mvl/mxv
	.byte	W01
	.byte		        51*seq_518_mvl/mxv
	.byte	W01
	.byte		        50*seq_518_mvl/mxv
	.byte	W01
	.byte		        49*seq_518_mvl/mxv
	.byte	W01
	.byte		        48*seq_518_mvl/mxv
	.byte	W01
	.byte		        46*seq_518_mvl/mxv
	.byte	W01
	.byte		        45*seq_518_mvl/mxv
	.byte	W01
	.byte		        44*seq_518_mvl/mxv
	.byte	W01
	.byte		        42*seq_518_mvl/mxv
	.byte	W01
	.byte		        38*seq_518_mvl/mxv
	.byte	W01
	.byte		        37*seq_518_mvl/mxv
	.byte	W01
	.byte		        34*seq_518_mvl/mxv
	.byte	W01
	.byte		        33*seq_518_mvl/mxv
	.byte	W01
	.byte		        30*seq_518_mvl/mxv
	.byte	W01
	.byte		        29*seq_518_mvl/mxv
	.byte	W01
	.byte		        30*seq_518_mvl/mxv
	.byte	W03
	.byte		        31*seq_518_mvl/mxv
	.byte	W01
	.byte		        32*seq_518_mvl/mxv
	.byte	W01
	.byte		        33*seq_518_mvl/mxv
	.byte	W01
	.byte		        22*seq_518_mvl/mxv
	.byte	W01
	.byte		        20*seq_518_mvl/mxv
	.byte	W01
	.byte		        18*seq_518_mvl/mxv
	.byte	W01
	.byte		        17*seq_518_mvl/mxv
	.byte	W01
	.byte		        16*seq_518_mvl/mxv
	.byte	W01
	.byte		        14*seq_518_mvl/mxv
	.byte	W01
	.byte		        14*seq_518_mvl/mxv
	.byte	W01
	.byte		        12*seq_518_mvl/mxv
	.byte	W01
	.byte		        11*seq_518_mvl/mxv
	.byte	W01
	.byte		        11*seq_518_mvl/mxv
	.byte	W01
	.byte		        10*seq_518_mvl/mxv
	.byte	W01
	.byte		        9*seq_518_mvl/mxv
	.byte	W01
	.byte		        8*seq_518_mvl/mxv
	.byte	W01
	.byte		        7*seq_518_mvl/mxv
	.byte	W01
	.byte		        7*seq_518_mvl/mxv
	.byte	W01
	.byte		        6*seq_518_mvl/mxv
	.byte	W01
	.byte		        5*seq_518_mvl/mxv
	.byte	W01
	.byte		        4*seq_518_mvl/mxv
	.byte	W02
	.byte		        3*seq_518_mvl/mxv
	.byte	W01
	.byte		        2*seq_518_mvl/mxv
	.byte	W02
	.byte		        1*seq_518_mvl/mxv
	.byte	W03
	.byte		        0*seq_518_mvl/mxv
	.byte	W20
	.byte		EOT
	.byte	W01
	.byte		EOT   , Fs3 
	.byte	W01
	.byte	FINE

@******************************************************@

	.align	2

seq_518:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_518_pri	@ Priority
	.byte	seq_518_rev	@ Reverb

	.word	seq_518_grp

	.word	seq_518_0

	.end
