@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_302_grp, bank_027
	.equ	seq_302_pri, 100
	.equ	seq_302_rev, 0
	.equ	seq_302_mvl, 127
	.equ	seq_302_key, 0

	.section .rodata
	.global	seq_302
	.align	2

@*********************** Track 01 ***********************@

seq_302_0:
	.byte	KEYSH , seq_302_key+0
	.byte	TEMPO , 150/2
	.byte		VOICE , 60
	.byte		VOL   , 100*seq_302_mvl/mxv
	.byte		PAN   , c_v+0
	.byte		N02   , Gn4 , v120
	.byte		N02   , Fs5 , v080
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	FINE

@******************************************************@

	.align	2

seq_302:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_302_pri	@ Priority
	.byte	seq_302_rev	@ Reverb

	.word	seq_302_grp

	.word	seq_302_0

	.end
