@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_925_grp, bank_026
	.equ	seq_925_pri, 127
	.equ	seq_925_rev, 0
	.equ	seq_925_mvl, 127
	.equ	seq_925_key, 0

	.section .rodata
	.global	seq_925
	.align	2

@*********************** Track 01 ***********************@

seq_925_0:
	.byte	KEYSH , seq_925_key+0
	.byte	TEMPO , 220/2
	.byte		VOICE , 39
	.byte		VOL   , 94*seq_925_mvl/mxv
	.byte		PAN   , c_v+0
	.byte		BEND  , c_v+0
	.byte	W01
	.byte		BENDR , 24
	.byte	W01
	.byte		N03   , Ds2 , v120
	.byte	W06
	.byte		        An2 , v100
	.byte	W04
	.byte		VOL   , 95*seq_925_mvl/mxv
	.byte		N05   , As1 , v088
	.byte	W01
	.byte		VOL   , 94*seq_925_mvl/mxv
	.byte	W01
	.byte		        85*seq_925_mvl/mxv
	.byte	W01
	.byte		        77*seq_925_mvl/mxv
	.byte	W01
	.byte		        68*seq_925_mvl/mxv
	.byte	W01
	.byte		        55*seq_925_mvl/mxv
	.byte	W01
	.byte		MOD   , 40
	.byte		VOL   , 60*seq_925_mvl/mxv
	.byte		N05   , Cn3 
	.byte	W02
	.byte		VOL   , 62*seq_925_mvl/mxv
	.byte	W01
	.byte		        64*seq_925_mvl/mxv
	.byte		BEND  , c_v+0
	.byte	W01
	.byte		VOL   , 67*seq_925_mvl/mxv
	.byte		BEND  , c_v+1
	.byte	W01
	.byte		VOL   , 71*seq_925_mvl/mxv
	.byte		BEND  , c_v+1
	.byte	W01
	.byte		VOL   , 76*seq_925_mvl/mxv
	.byte		BEND  , c_v+2
	.byte		N05   , An3 
	.byte	W01
	.byte		VOL   , 82*seq_925_mvl/mxv
	.byte		BEND  , c_v+4
	.byte	W01
	.byte		VOL   , 88*seq_925_mvl/mxv
	.byte		BEND  , c_v+5
	.byte	W01
	.byte		VOL   , 96*seq_925_mvl/mxv
	.byte		BEND  , c_v+7
	.byte		N05   , Ds2 
	.byte	W01
	.byte		BEND  , c_v+9
	.byte	W01
	.byte		VOL   , 94*seq_925_mvl/mxv
	.byte		BEND  , c_v+11
	.byte	W01
	.byte		PAN   , c_v+0
	.byte		BEND  , c_v+14
	.byte		N03   , Gn3 , v120
	.byte	W01
	.byte		BENDR , 24
	.byte		VOL   , 92*seq_925_mvl/mxv
	.byte		BEND  , c_v+16
	.byte	W01
	.byte		VOL   , 89*seq_925_mvl/mxv
	.byte		BEND  , c_v+19
	.byte	W01
	.byte		VOL   , 81*seq_925_mvl/mxv
	.byte		BEND  , c_v+32
	.byte	W01
	.byte		VOL   , 75*seq_925_mvl/mxv
	.byte		BEND  , c_v+32
	.byte		N02   , Cs2 , v088
	.byte	W01
	.byte		VOL   , 69*seq_925_mvl/mxv
	.byte		BEND  , c_v+30
	.byte	W01
	.byte		VOL   , 96*seq_925_mvl/mxv
	.byte		BEND  , c_v+28
	.byte	W01
	.byte		        c_v+24
	.byte		N05   , Gs2 
	.byte	W01
	.byte		VOL   , 95*seq_925_mvl/mxv
	.byte		BEND  , c_v-6
	.byte	W01
	.byte		VOL   , 94*seq_925_mvl/mxv
	.byte		BEND  , c_v-4
	.byte	W01
	.byte		VOICE , 21
	.byte		VOL   , 100*seq_925_mvl/mxv
	.byte		PAN   , c_v+0
	.byte		VOL   , 62*seq_925_mvl/mxv
	.byte		BEND  , c_v+2
	.byte	W01
	.byte		VOL   , 62*seq_925_mvl/mxv
	.byte	W01
	.byte		        67*seq_925_mvl/mxv
	.byte		N22   , Fs3 , v120
	.byte	W01
	.byte		VOL   , 75*seq_925_mvl/mxv
	.byte		BEND  , c_v+0
	.byte	W01
	.byte		VOL   , 86*seq_925_mvl/mxv
	.byte	W01
	.byte		        100*seq_925_mvl/mxv
	.byte	W09
	.byte		        100*seq_925_mvl/mxv
	.byte	W01
	.byte		        99*seq_925_mvl/mxv
	.byte	W01
	.byte		        96*seq_925_mvl/mxv
	.byte	W01
	.byte		        90*seq_925_mvl/mxv
	.byte		BEND  , c_v+57
	.byte	W01
	.byte		VOL   , 83*seq_925_mvl/mxv
	.byte		BEND  , c_v+54
	.byte	W01
	.byte		VOL   , 74*seq_925_mvl/mxv
	.byte		BEND  , c_v+45
	.byte	W01
	.byte		VOL   , 62*seq_925_mvl/mxv
	.byte		BEND  , c_v+29
	.byte	W01
	.byte		VOL   , 48*seq_925_mvl/mxv
	.byte		BEND  , c_v+8
	.byte	W01
	.byte		VOL   , 32*seq_925_mvl/mxv
	.byte		BEND  , c_v-20
	.byte	W01
	.byte		VOICE , 39
	.byte		VOL   , 94*seq_925_mvl/mxv
	.byte		PAN   , c_v+0
	.byte		BEND  , c_v-58
	.byte	W01
	.byte		BENDR , 24
	.byte		BEND  , c_v+0
	.byte		N02   , Ds2 , v060
	.byte	W06
	.byte		        An2 , v032
	.byte	W05
	.byte		VOL   , 95*seq_925_mvl/mxv
	.byte		N04   , As1 , v052
	.byte	W01
	.byte		VOL   , 94*seq_925_mvl/mxv
	.byte	W01
	.byte		        91*seq_925_mvl/mxv
	.byte	W02
	.byte	FINE

@******************************************************@

	.align	2

seq_925:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_925_pri	@ Priority
	.byte	seq_925_rev	@ Reverb

	.word	seq_925_grp

	.word	seq_925_0

	.end
