@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_509_grp, bank_026
	.equ	seq_509_pri, 127
	.equ	seq_509_rev, 0
	.equ	seq_509_mvl, 127
	.equ	seq_509_key, 0

	.section .rodata
	.global	seq_509
	.align	2

@*********************** Track 01 ***********************@

seq_509_0:
	.byte	KEYSH , seq_509_key+0
	.byte	TEMPO , 160/2
	.byte		VOICE , 8
	.byte		VOL   , 125*seq_509_mvl/mxv
	.byte		PAN   , c_v+0
	.byte	W01
	.byte		BENDR , 41
	.byte		BEND  , c_v+2
	.byte	W01
	.byte		N36   , Dn2 , v120
	.byte	W01
	.byte	W01
	.byte		VOL   , 110*seq_509_mvl/mxv
	.byte	W01
	.byte		        98*seq_509_mvl/mxv
	.byte	W01
	.byte		        93*seq_509_mvl/mxv
	.byte	W01
	.byte		        88*seq_509_mvl/mxv
	.byte	W01
	.byte		        82*seq_509_mvl/mxv
	.byte	W01
	.byte		        77*seq_509_mvl/mxv
	.byte	W01
	.byte		        72*seq_509_mvl/mxv
	.byte	W01
	.byte		        66*seq_509_mvl/mxv
	.byte		BEND  , c_v-4
	.byte	W01
	.byte		VOL   , 62*seq_509_mvl/mxv
	.byte		BEND  , c_v-6
	.byte	W01
	.byte		VOICE , 16
	.byte		VOL   , 57*seq_509_mvl/mxv
	.byte		BEND  , c_v-7
	.byte	W01
	.byte		VOL   , 51*seq_509_mvl/mxv
	.byte		BEND  , c_v-9
	.byte	W01
	.byte		VOL   , 46*seq_509_mvl/mxv
	.byte		BEND  , c_v-11
	.byte	W01
	.byte		VOL   , 39*seq_509_mvl/mxv
	.byte		BEND  , c_v-13
	.byte	W01
	.byte		VOL   , 36*seq_509_mvl/mxv
	.byte		BEND  , c_v-15
	.byte	W01
	.byte		VOL   , 33*seq_509_mvl/mxv
	.byte		BEND  , c_v-16
	.byte	W01
	.byte		VOL   , 30*seq_509_mvl/mxv
	.byte		BEND  , c_v-18
	.byte	W01
	.byte		        c_v-20
	.byte	W01
	.byte		VOL   , 24*seq_509_mvl/mxv
	.byte		BEND  , c_v-22
	.byte	W01
	.byte		VOL   , 21*seq_509_mvl/mxv
	.byte		BEND  , c_v-26
	.byte	W01
	.byte		VOL   , 18*seq_509_mvl/mxv
	.byte		BEND  , c_v-28
	.byte	W01
	.byte		VOL   , 16*seq_509_mvl/mxv
	.byte		BEND  , c_v-32
	.byte	W01
	.byte		VOL   , 15*seq_509_mvl/mxv
	.byte		BEND  , c_v-34
	.byte	W01
	.byte		VOL   , 13*seq_509_mvl/mxv
	.byte		BEND  , c_v-38
	.byte	W01
	.byte		VOL   , 11*seq_509_mvl/mxv
	.byte		BEND  , c_v-40
	.byte	W01
	.byte		VOL   , 9*seq_509_mvl/mxv
	.byte	W01
	.byte		        7*seq_509_mvl/mxv
	.byte	W01
	.byte		        5*seq_509_mvl/mxv
	.byte	W01
	.byte		        3*seq_509_mvl/mxv
	.byte	W07
	.byte	FINE

@******************************************************@

	.align	2

seq_509:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_509_pri	@ Priority
	.byte	seq_509_rev	@ Reverb

	.word	seq_509_grp

	.word	seq_509_0

	.end
