@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_038_grp, bank_014
	.equ	seq_038_pri, 50
	.equ	seq_038_rev, 203
	.equ	seq_038_mvl, 127
	.equ	seq_038_key, 0

	.section .rodata
	.global	seq_038
	.align	2

@*********************** Track 01 ***********************@

seq_038_0:
	.byte	KEYSH , seq_038_key+0
	.byte	TEMPO , 124/2
	.byte		VOICE , 48
	.byte		MOD   , 37
	.byte		VOL   , 0*seq_038_mvl/mxv
	.byte	W01
	.byte		PAN   , c_v+0
	.byte		BENDR , 5
	.byte		LFOS  , 13
	.byte	W01
	.byte		MODT  , mod_pan
	.byte	W21
	.byte		VOL   , 0*seq_038_mvl/mxv
	.byte	W01
	.byte		TIE   , Gs1 , v120
	.byte	W02
	.byte		VOL   , 0*seq_038_mvl/mxv
	.byte	W01
	.byte		        2*seq_038_mvl/mxv
	.byte	W01
	.byte		        3*seq_038_mvl/mxv
	.byte	W01
	.byte		        4*seq_038_mvl/mxv
	.byte	W01
	.byte		        5*seq_038_mvl/mxv
	.byte	W01
	.byte		        7*seq_038_mvl/mxv
	.byte	W01
	.byte		        7*seq_038_mvl/mxv
	.byte	W01
	.byte		        9*seq_038_mvl/mxv
	.byte	W01
	.byte		        11*seq_038_mvl/mxv
	.byte	W01
	.byte		        11*seq_038_mvl/mxv
	.byte	W01
	.byte		        13*seq_038_mvl/mxv
	.byte	W01
	.byte		        14*seq_038_mvl/mxv
	.byte	W01
	.byte		        15*seq_038_mvl/mxv
	.byte	W01
	.byte		        16*seq_038_mvl/mxv
	.byte	W01
	.byte		        18*seq_038_mvl/mxv
	.byte	W01
	.byte		        19*seq_038_mvl/mxv
	.byte	W01
	.byte		        20*seq_038_mvl/mxv
	.byte	W01
	.byte		        22*seq_038_mvl/mxv
	.byte	W01
	.byte		        22*seq_038_mvl/mxv
	.byte	W01
	.byte		        24*seq_038_mvl/mxv
	.byte	W01
	.byte		        25*seq_038_mvl/mxv
	.byte	W01
	.byte		        26*seq_038_mvl/mxv
	.byte	W01
	.byte		        28*seq_038_mvl/mxv
	.byte	W01
	.byte		        29*seq_038_mvl/mxv
	.byte	W01
	.byte		        30*seq_038_mvl/mxv
	.byte	W01
	.byte		        31*seq_038_mvl/mxv
	.byte	W01
	.byte		        33*seq_038_mvl/mxv
	.byte	W01
	.byte		        33*seq_038_mvl/mxv
	.byte	W01
	.byte		        35*seq_038_mvl/mxv
	.byte	W01
	.byte		        36*seq_038_mvl/mxv
	.byte	W01
	.byte		        37*seq_038_mvl/mxv
	.byte	W01
	.byte		        39*seq_038_mvl/mxv
	.byte	W01
	.byte		        40*seq_038_mvl/mxv
	.byte	W01
	.byte		        41*seq_038_mvl/mxv
	.byte	W01
	.byte		        42*seq_038_mvl/mxv
	.byte	W01
	.byte		        44*seq_038_mvl/mxv
	.byte	W01
	.byte		        44*seq_038_mvl/mxv
	.byte	W01
	.byte		        46*seq_038_mvl/mxv
	.byte	W01
	.byte		        48*seq_038_mvl/mxv
	.byte	W01
	.byte		        48*seq_038_mvl/mxv
	.byte	W01
	.byte		        50*seq_038_mvl/mxv
	.byte	W01
	.byte		        51*seq_038_mvl/mxv
	.byte	W01
	.byte		        52*seq_038_mvl/mxv
	.byte	W01
	.byte		        53*seq_038_mvl/mxv
	.byte	W01
	.byte		        55*seq_038_mvl/mxv
	.byte	W48
	.byte	W02
	.byte	W96
	.byte		EOT
	.byte		TIE   , Bn1 , v120
	.byte	W96
	.byte	W96
	.byte		EOT
	.byte		TIE
	.byte	W96
	.byte	W96
	.byte		EOT
	.byte		TIE
	.byte	W96
	.byte	W96
	.byte		EOT
	.byte		TIE
	.byte	W96
	.byte	W96
	.byte		EOT
	.byte		TIE
	.byte	W96
	.byte	W96
	.byte		EOT
	.byte	GOTO
	 .word	seq_038_0 + 0x7A
	.byte	FINE

@*********************** Track 02 ***********************@

seq_038_1:
	.byte	KEYSH , seq_038_key+0
	.byte	W02
	.byte		VOICE , 48
	.byte		VOL   , 0*seq_038_mvl/mxv
	.byte	W01
	.byte		MOD   , 75
	.byte		PAN   , c_v+0
	.byte		LFOS  , 18
	.byte	W01
	.byte		MODT  , mod_tre
	.byte	W19
	.byte		MOD   , 75
	.byte		VOL   , 0*seq_038_mvl/mxv
	.byte	W01
	.byte		TIE   , Cn2 , v120
	.byte	W02
	.byte		VOL   , 0*seq_038_mvl/mxv
	.byte	W01
	.byte		        1*seq_038_mvl/mxv
	.byte	W01
	.byte		        3*seq_038_mvl/mxv
	.byte	W01
	.byte		        4*seq_038_mvl/mxv
	.byte	W01
	.byte		        6*seq_038_mvl/mxv
	.byte	W01
	.byte		        7*seq_038_mvl/mxv
	.byte	W01
	.byte		        10*seq_038_mvl/mxv
	.byte	W01
	.byte		        11*seq_038_mvl/mxv
	.byte	W01
	.byte		        13*seq_038_mvl/mxv
	.byte	W01
	.byte		        14*seq_038_mvl/mxv
	.byte	W01
	.byte		        16*seq_038_mvl/mxv
	.byte	W01
	.byte		        18*seq_038_mvl/mxv
	.byte	W01
	.byte		        20*seq_038_mvl/mxv
	.byte	W01
	.byte		        22*seq_038_mvl/mxv
	.byte	W01
	.byte		        23*seq_038_mvl/mxv
	.byte	W01
	.byte		        25*seq_038_mvl/mxv
	.byte	W01
	.byte		        27*seq_038_mvl/mxv
	.byte	W01
	.byte		        29*seq_038_mvl/mxv
	.byte	W01
	.byte		        30*seq_038_mvl/mxv
	.byte	W01
	.byte		        32*seq_038_mvl/mxv
	.byte	W01
	.byte		        34*seq_038_mvl/mxv
	.byte	W01
	.byte		        36*seq_038_mvl/mxv
	.byte	W01
	.byte		        37*seq_038_mvl/mxv
	.byte	W01
	.byte		        39*seq_038_mvl/mxv
	.byte	W01
	.byte		        40*seq_038_mvl/mxv
	.byte	W01
	.byte		        43*seq_038_mvl/mxv
	.byte	W01
	.byte		        44*seq_038_mvl/mxv
	.byte	W01
	.byte		        46*seq_038_mvl/mxv
	.byte	W01
	.byte		        48*seq_038_mvl/mxv
	.byte	W01
	.byte		        50*seq_038_mvl/mxv
	.byte	W01
	.byte		        51*seq_038_mvl/mxv
	.byte	W01
	.byte		        53*seq_038_mvl/mxv
	.byte	W01
	.byte		        55*seq_038_mvl/mxv
	.byte	W01
	.byte		        56*seq_038_mvl/mxv
	.byte	W01
	.byte		        59*seq_038_mvl/mxv
	.byte	W01
	.byte		        60*seq_038_mvl/mxv
	.byte	W01
	.byte		        62*seq_038_mvl/mxv
	.byte	W01
	.byte		        63*seq_038_mvl/mxv
	.byte	W01
	.byte		        65*seq_038_mvl/mxv
	.byte	W01
	.byte		        67*seq_038_mvl/mxv
	.byte	W01
	.byte		        69*seq_038_mvl/mxv
	.byte	W01
	.byte		        70*seq_038_mvl/mxv
	.byte	W01
	.byte		        72*seq_038_mvl/mxv
	.byte	W01
	.byte		        74*seq_038_mvl/mxv
	.byte	W48
	.byte	W02
	.byte		MOD   , 20
	.byte	W01
	.byte	W92
	.byte	W03
	.byte		        100
	.byte	W01
	.byte		EOT
	.byte		TIE   , Cn2 , v120
	.byte	W96
	.byte	W96
	.byte		EOT
	.byte		TIE
	.byte	W96
	.byte	W96
	.byte		EOT
	.byte		TIE
	.byte	W96
	.byte	W96
	.byte		EOT
	.byte		TIE
	.byte	W96
	.byte	W96
	.byte		EOT
	.byte		TIE
	.byte	W96
	.byte	W96
	.byte		EOT
	.byte	GOTO
	 .word	seq_038_1 + 0x7D
	.byte	FINE

@*********************** Track 03 ***********************@

seq_038_2:
	.byte	KEYSH , seq_038_key+0
	.byte	W04
	.byte		VOICE , 49
	.byte		VOL   , 55*seq_038_mvl/mxv
	.byte	W01
	.byte		PAN   , c_v+16
	.byte		BENDR , 24
	.byte		LFOS  , 100
	.byte	W01
	.byte		MODT  , mod_pan
	.byte	W18
	.byte	W96
	.byte	W96
	.byte		N36   , Cn3 , v120
	.byte	W36
	.byte		N24   , Fn2 , v060
	.byte	W60
	.byte	PEND
	.byte	W96
	.byte	W48
	.byte		N12   , Gn2 , v120
	.byte	W12
	.byte		N24   , Fn2 , v060
	.byte	W24
	.byte		N36   , Ds3 
	.byte	W12
	.byte	PEND
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_038_2 + 0x14
	.byte	W96
	.byte	PATT
	 .word	seq_038_2 + 0x1E
	.byte	W96
	.byte	W96
	.byte	GOTO
	 .word	seq_038_2 + 0x14
	.byte	FINE

@*********************** Track 04 ***********************@

seq_038_3:
	.byte	KEYSH , seq_038_key+0
	.byte	W06
	.byte		VOICE , 49
	.byte		VOL   , 39*seq_038_mvl/mxv
	.byte	W01
	.byte		PAN   , c_v-24
	.byte		LFOS  , 30
	.byte		MODT  , mod_vib
	.byte	W01
	.byte		BENDR , 12
	.byte	W16
	.byte	W96
	.byte		N48   , Gn3 , v120
	.byte	W48
	.byte		N24   , Gn4 , v060
	.byte	W48
	.byte	PEND
	.byte	W96
	.byte	W48
	.byte		N48   , Bn3 , v120
	.byte	W48
	.byte		N24   , Ds4 , v060
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_038_3 + 0x13
	.byte	W96
	.byte	W48
	.byte		N48   , Bn3 , v120
	.byte	W48
	.byte		N24   , Ds4 , v060
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_038_3 + 0x13
	.byte	GOTO
	 .word	seq_038_3 + 0x1C
	.byte	FINE

@******************************************************@

	.align	2

seq_038:
	.byte	4	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_038_pri	@ Priority
	.byte	seq_038_rev	@ Reverb

	.word	seq_038_grp

	.word	seq_038_0
	.word	seq_038_1
	.word	seq_038_2
	.word	seq_038_3

	.end
