@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_713_grp, bank_026
	.equ	seq_713_pri, 127
	.equ	seq_713_rev, 0
	.equ	seq_713_mvl, 127
	.equ	seq_713_key, 0

	.section .rodata
	.global	seq_713
	.align	2

@*********************** Track 01 ***********************@

seq_713_0:
	.byte	KEYSH , seq_713_key+0
	.byte	TEMPO , 150/2
	.byte		VOICE , 20
	.byte		VOL   , 127*seq_713_mvl/mxv
	.byte		PAN   , c_v+0
	.byte	W01
	.byte		MOD   , 80
	.byte	W01
	.byte		N10   , Cs2 , v032
	.byte	W07
	.byte		N09   , Ds2 , v068
	.byte	W07
	.byte		N11   , Fn2 , v127
	.byte	W06
	.byte		N10   , Ds2 , v100
	.byte	W09
	.byte		N11   , Fn2 , v080
	.byte	W11
	.byte	FINE

@******************************************************@

	.align	2

seq_713:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_713_pri	@ Priority
	.byte	seq_713_rev	@ Reverb

	.word	seq_713_grp

	.word	seq_713_0

	.end
