@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_927_grp, bank_026
	.equ	seq_927_pri, 127
	.equ	seq_927_rev, 0
	.equ	seq_927_mvl, 127
	.equ	seq_927_key, 0

	.section .rodata
	.global	seq_927
	.align	2

@*********************** Track 01 ***********************@

seq_927_0:
	.byte	KEYSH , seq_927_key+0
	.byte	TEMPO , 220/2
	.byte		VOICE , 39
	.byte		VOL   , 120*seq_927_mvl/mxv
	.byte		PAN   , c_v+0
	.byte	W01
	.byte		BENDR , 24
	.byte	W01
	.byte		N03   , Cs2 , v120
	.byte	W06
	.byte		N02   , Cs2 , v100
	.byte	W05
	.byte		N03   , Cs2 , v120
	.byte	W05
	.byte		MOD   , 40
	.byte	W02
	.byte		N04   , Cs2 , v100
	.byte	W01
	.byte		BEND  , c_v+0
	.byte	W01
	.byte		        c_v+1
	.byte	W01
	.byte		        c_v+1
	.byte	W01
	.byte		        c_v+2
	.byte	W01
	.byte		        c_v+4
	.byte	W01
	.byte		        c_v+5
	.byte		N24   , Cs2 , v092
	.byte	W01
	.byte		BEND  , c_v+7
	.byte	W01
	.byte		        c_v+9
	.byte	W01
	.byte		        c_v+11
	.byte	W01
	.byte		VOL   , 120*seq_927_mvl/mxv
	.byte		PAN   , c_v+0
	.byte		BEND  , c_v+14
	.byte	W01
	.byte		BENDR , 24
	.byte		BEND  , c_v+16
	.byte	W01
	.byte		        c_v+19
	.byte	W01
	.byte		        c_v+32
	.byte	W01
	.byte		        c_v+32
	.byte	W01
	.byte		        c_v+30
	.byte	W01
	.byte		        c_v+28
	.byte	W01
	.byte		VOL   , 119*seq_927_mvl/mxv
	.byte		BEND  , c_v+24
	.byte	W01
	.byte		VOL   , 118*seq_927_mvl/mxv
	.byte	W01
	.byte		        113*seq_927_mvl/mxv
	.byte	W01
	.byte		        104*seq_927_mvl/mxv
	.byte	W01
	.byte		        92*seq_927_mvl/mxv
	.byte	W01
	.byte		        72*seq_927_mvl/mxv
	.byte	W06
	.byte		MOD   , 40
	.byte	W02
	.byte	FINE

@******************************************************@

	.align	2

seq_927:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_927_pri	@ Priority
	.byte	seq_927_rev	@ Reverb

	.word	seq_927_grp

	.word	seq_927_0

	.end
