@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_515_grp, bank_027
	.equ	seq_515_pri, 127
	.equ	seq_515_rev, 0
	.equ	seq_515_mvl, 127
	.equ	seq_515_key, 0

	.section .rodata
	.global	seq_515
	.align	2

@*********************** Track 01 ***********************@

seq_515_0:
	.byte	KEYSH , seq_515_key+0
	.byte	TEMPO , 160/2
	.byte		VOICE , 80
	.byte		MOD   , 90
	.byte		VOL   , 35*seq_515_mvl/mxv
	.byte	W01
	.byte		PAN   , c_v+0
	.byte		BENDR , 13
	.byte		LFOS  , 70
	.byte	W01
	.byte		MODT  , mod_vib
	.byte	W03
	.byte		VOL   , 38*seq_515_mvl/mxv
	.byte		BEND  , c_v-26
	.byte	W01
	.byte		        c_v-16
	.byte		N24   , An2 , v127
	.byte	W01
	.byte		VOL   , 42*seq_515_mvl/mxv
	.byte		BEND  , c_v-5
	.byte	W01
	.byte		VOL   , 50*seq_515_mvl/mxv
	.byte		BEND  , c_v+6
	.byte	W01
	.byte		VOL   , 58*seq_515_mvl/mxv
	.byte		BEND  , c_v+16
	.byte	W01
	.byte		VOL   , 65*seq_515_mvl/mxv
	.byte		BEND  , c_v+27
	.byte	W01
	.byte		VOL   , 73*seq_515_mvl/mxv
	.byte		BEND  , c_v+38
	.byte	W01
	.byte		VOL   , 80*seq_515_mvl/mxv
	.byte		BEND  , c_v+49
	.byte	W01
	.byte		VOL   , 72*seq_515_mvl/mxv
	.byte	W01
	.byte		        63*seq_515_mvl/mxv
	.byte	W01
	.byte		        55*seq_515_mvl/mxv
	.byte	W01
	.byte		        46*seq_515_mvl/mxv
	.byte	W01
	.byte		        38*seq_515_mvl/mxv
	.byte	W01
	.byte	W12
	.byte		N03   , Cs3 , v116
	.byte	W03
	.byte		        As2 , v120
	.byte	W03
	.byte		        Gn2 
	.byte	W03
	.byte		        Ds2 , v116
	.byte	W03
	.byte		        Cn2 , v112
	.byte	W03
	.byte		        Gs1 , v104
	.byte	W03
	.byte		        En1 , v092
	.byte	W03
	.byte		        Bn0 , v072
	.byte	W03
	.byte	FINE

@******************************************************@

	.align	2

seq_515:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_515_pri	@ Priority
	.byte	seq_515_rev	@ Reverb

	.word	seq_515_grp

	.word	seq_515_0

	.end
