@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_888_grp, bank_026
	.equ	seq_888_pri, 127
	.equ	seq_888_rev, 0
	.equ	seq_888_mvl, 127
	.equ	seq_888_key, 0

	.section .rodata
	.global	seq_888
	.align	2

@*********************** Track 01 ***********************@

seq_888_0:
	.byte	KEYSH , seq_888_key+0
	.byte	TEMPO , 340/2
	.byte		VOICE , 22
	.byte		VOL   , 115*seq_888_mvl/mxv
	.byte		PAN   , c_v+0
	.byte	W01
	.byte		BENDR , 24
	.byte		BEND  , c_v+42
	.byte	W01
	.byte		N06   , An1 , v120
	.byte	W01
	.byte		BEND  , c_v+33
	.byte	W01
	.byte		        c_v+29
	.byte	W01
	.byte		        c_v+25
	.byte	W01
	.byte		        c_v+21
	.byte	W01
	.byte		        c_v+17
	.byte	W01
	.byte		N06   , En2 
	.byte	W01
	.byte		BEND  , c_v+10
	.byte	W01
	.byte		        c_v+7
	.byte	W01
	.byte		        c_v+4
	.byte	W01
	.byte		        c_v+1
	.byte	W01
	.byte		        c_v+0
	.byte	W01
	.byte		N06   , Cs2 
	.byte	W06
	.byte		        Fs2 
	.byte	W06
	.byte		        Bn1 
	.byte	W06
	.byte		        Fs2 
	.byte	W06
	.byte		        Ds2 
	.byte	W01
	.byte		BEND  , c_v+3
	.byte	W02
	.byte		        c_v+4
	.byte	W01
	.byte		        c_v+5
	.byte	W02
	.byte		N06   , Gs2 
	.byte	W01
	.byte		BEND  , c_v+7
	.byte	W05
	.byte		N06   , Cs2 
	.byte	W01
	.byte		BEND  , c_v+8
	.byte	W01
	.byte		        c_v+9
	.byte	W02
	.byte		        c_v+10
	.byte	W02
	.byte		N06   , Gs2 
	.byte	W01
	.byte		BEND  , c_v+12
	.byte	W02
	.byte		        c_v+13
	.byte	W01
	.byte		        c_v+14
	.byte	W02
	.byte		N09   , Bn2 
	.byte	W03
	.byte		BEND  , c_v+16
	.byte	W04
	.byte		        c_v+17
	.byte	W02
	.byte	FINE

@******************************************************@

	.align	2

seq_888:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_888_pri	@ Priority
	.byte	seq_888_rev	@ Reverb

	.word	seq_888_grp

	.word	seq_888_0

	.end
