@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_026_grp, bank_014
	.equ	seq_026_pri, 50
	.equ	seq_026_rev, 203
	.equ	seq_026_mvl, 127
	.equ	seq_026_key, 0

	.section .rodata
	.global	seq_026
	.align	2

@*********************** Track 01 ***********************@

seq_026_0:
	.byte	KEYSH , seq_026_key+0
	.byte	TEMPO , 114/2
	.byte	W02
	.byte		VOICE , 45
	.byte		VOL   , 0*seq_026_mvl/mxv
	.byte	W01
	.byte		MOD   , 25
	.byte		PAN   , c_v+0
	.byte		LFOS  , 70
	.byte	W01
	.byte		MODT  , mod_tre
	.byte	W13
	.byte		VOL   , 0*seq_026_mvl/mxv
	.byte	W07
	.byte		TIE   , Ds1 , v120
	.byte	W13
	.byte		VOL   , 0*seq_026_mvl/mxv
	.byte	W12
	.byte		        4*seq_026_mvl/mxv
	.byte	W10
	.byte		        7*seq_026_mvl/mxv
	.byte	W07
	.byte		        9*seq_026_mvl/mxv
	.byte	W08
	.byte		        12*seq_026_mvl/mxv
	.byte	W07
	.byte		        14*seq_026_mvl/mxv
	.byte	W07
	.byte		        17*seq_026_mvl/mxv
	.byte	W07
	.byte		        19*seq_026_mvl/mxv
	.byte	W08
	.byte		        22*seq_026_mvl/mxv
	.byte	W07
	.byte		        24*seq_026_mvl/mxv
	.byte	W07
	.byte		        26*seq_026_mvl/mxv
	.byte	W03
	.byte	W04
	.byte		        29*seq_026_mvl/mxv
	.byte	W08
	.byte		        31*seq_026_mvl/mxv
	.byte	W07
	.byte		        34*seq_026_mvl/mxv
	.byte	W07
	.byte		        36*seq_026_mvl/mxv
	.byte	W07
	.byte		        38*seq_026_mvl/mxv
	.byte	W08
	.byte		        41*seq_026_mvl/mxv
	.byte	W07
	.byte		        44*seq_026_mvl/mxv
	.byte	W07
	.byte		        46*seq_026_mvl/mxv
	.byte	W07
	.byte		        48*seq_026_mvl/mxv
	.byte	W08
	.byte		        51*seq_026_mvl/mxv
	.byte	W07
	.byte		        53*seq_026_mvl/mxv
	.byte	W07
	.byte		        56*seq_026_mvl/mxv
	.byte	W12
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W12
	.byte		        49*seq_026_mvl/mxv
	.byte	W03
	.byte		        48*seq_026_mvl/mxv
	.byte	W03
	.byte		        48*seq_026_mvl/mxv
	.byte	W02
	.byte		        47*seq_026_mvl/mxv
	.byte	W03
	.byte		        46*seq_026_mvl/mxv
	.byte	W02
	.byte		        46*seq_026_mvl/mxv
	.byte	W03
	.byte		        45*seq_026_mvl/mxv
	.byte	W02
	.byte		        44*seq_026_mvl/mxv
	.byte	W03
	.byte		        43*seq_026_mvl/mxv
	.byte	W02
	.byte		        43*seq_026_mvl/mxv
	.byte	W03
	.byte		        42*seq_026_mvl/mxv
	.byte	W02
	.byte		        41*seq_026_mvl/mxv
	.byte	W03
	.byte		        41*seq_026_mvl/mxv
	.byte	W02
	.byte		        40*seq_026_mvl/mxv
	.byte	W03
	.byte		        39*seq_026_mvl/mxv
	.byte	W02
	.byte		        38*seq_026_mvl/mxv
	.byte	W03
	.byte		        38*seq_026_mvl/mxv
	.byte	W02
	.byte		        37*seq_026_mvl/mxv
	.byte	W03
	.byte		        36*seq_026_mvl/mxv
	.byte	W02
	.byte		        36*seq_026_mvl/mxv
	.byte	W03
	.byte		        35*seq_026_mvl/mxv
	.byte	W02
	.byte		        34*seq_026_mvl/mxv
	.byte	W03
	.byte		        34*seq_026_mvl/mxv
	.byte	W02
	.byte		        33*seq_026_mvl/mxv
	.byte	W03
	.byte		        32*seq_026_mvl/mxv
	.byte	W02
	.byte		        31*seq_026_mvl/mxv
	.byte	W03
	.byte		        31*seq_026_mvl/mxv
	.byte	W02
	.byte		        30*seq_026_mvl/mxv
	.byte	W03
	.byte		        29*seq_026_mvl/mxv
	.byte	W02
	.byte		        29*seq_026_mvl/mxv
	.byte	W03
	.byte		        28*seq_026_mvl/mxv
	.byte	W02
	.byte		        27*seq_026_mvl/mxv
	.byte	W03
	.byte		        26*seq_026_mvl/mxv
	.byte	W02
	.byte		        26*seq_026_mvl/mxv
	.byte	W01
	.byte	W02
	.byte		        25*seq_026_mvl/mxv
	.byte	W02
	.byte		        24*seq_026_mvl/mxv
	.byte	W03
	.byte		        24*seq_026_mvl/mxv
	.byte	W02
	.byte		        23*seq_026_mvl/mxv
	.byte	W03
	.byte		        22*seq_026_mvl/mxv
	.byte	W02
	.byte		        21*seq_026_mvl/mxv
	.byte	W03
	.byte		        21*seq_026_mvl/mxv
	.byte	W02
	.byte		        20*seq_026_mvl/mxv
	.byte	W03
	.byte		        19*seq_026_mvl/mxv
	.byte	W02
	.byte		        19*seq_026_mvl/mxv
	.byte	W03
	.byte		        18*seq_026_mvl/mxv
	.byte	W02
	.byte		        17*seq_026_mvl/mxv
	.byte	W03
	.byte		        17*seq_026_mvl/mxv
	.byte	W02
	.byte		        16*seq_026_mvl/mxv
	.byte	W03
	.byte		        15*seq_026_mvl/mxv
	.byte	W02
	.byte		        14*seq_026_mvl/mxv
	.byte	W03
	.byte		        14*seq_026_mvl/mxv
	.byte	W02
	.byte		        13*seq_026_mvl/mxv
	.byte	W03
	.byte		        12*seq_026_mvl/mxv
	.byte	W02
	.byte		        12*seq_026_mvl/mxv
	.byte	W03
	.byte		        11*seq_026_mvl/mxv
	.byte	W02
	.byte		        10*seq_026_mvl/mxv
	.byte	W03
	.byte		        9*seq_026_mvl/mxv
	.byte	W02
	.byte		        9*seq_026_mvl/mxv
	.byte	W03
	.byte		        8*seq_026_mvl/mxv
	.byte	W02
	.byte		        7*seq_026_mvl/mxv
	.byte	W03
	.byte		        7*seq_026_mvl/mxv
	.byte	W02
	.byte		        6*seq_026_mvl/mxv
	.byte	W03
	.byte		        5*seq_026_mvl/mxv
	.byte	W02
	.byte		        4*seq_026_mvl/mxv
	.byte	W03
	.byte		        4*seq_026_mvl/mxv
	.byte	W02
	.byte		        3*seq_026_mvl/mxv
	.byte	W03
	.byte		        2*seq_026_mvl/mxv
	.byte	W02
	.byte		        2*seq_026_mvl/mxv
	.byte	W03
	.byte		        1*seq_026_mvl/mxv
	.byte	W02
	.byte		        0*seq_026_mvl/mxv
	.byte	W03
	.byte		        0*seq_026_mvl/mxv
	.byte	W04
	.byte		EOT
	.byte	GOTO
	 .word	seq_026_0 + 0x17
	.byte	FINE

@*********************** Track 02 ***********************@

seq_026_1:
	.byte	KEYSH , seq_026_key+0
	.byte		VOICE , 42
	.byte		VOL   , 0*seq_026_mvl/mxv
	.byte		PAN   , c_v-14
	.byte	W01
	.byte		MOD   , 0
	.byte		BENDR , 5
	.byte		LFOS  , 100
	.byte	W01
	.byte		MODT  , mod_pan
	.byte	W22
	.byte	W06
	.byte		TIE   , Ds0 , v120
	.byte	W02
	.byte		VOL   , 0*seq_026_mvl/mxv
	.byte	W03
	.byte		        2*seq_026_mvl/mxv
	.byte	W02
	.byte		        2*seq_026_mvl/mxv
	.byte	W03
	.byte		        4*seq_026_mvl/mxv
	.byte	W02
	.byte		        4*seq_026_mvl/mxv
	.byte	W03
	.byte		        6*seq_026_mvl/mxv
	.byte	W02
	.byte		        7*seq_026_mvl/mxv
	.byte	W03
	.byte		        9*seq_026_mvl/mxv
	.byte	W02
	.byte		        9*seq_026_mvl/mxv
	.byte	W03
	.byte		        11*seq_026_mvl/mxv
	.byte	W02
	.byte		        12*seq_026_mvl/mxv
	.byte	W03
	.byte		        14*seq_026_mvl/mxv
	.byte	W02
	.byte		        14*seq_026_mvl/mxv
	.byte	W03
	.byte		        16*seq_026_mvl/mxv
	.byte	W03
	.byte		        17*seq_026_mvl/mxv
	.byte	W02
	.byte		        19*seq_026_mvl/mxv
	.byte	W03
	.byte		        20*seq_026_mvl/mxv
	.byte	W02
	.byte		        21*seq_026_mvl/mxv
	.byte	W03
	.byte		        22*seq_026_mvl/mxv
	.byte	W02
	.byte		        24*seq_026_mvl/mxv
	.byte	W03
	.byte		        25*seq_026_mvl/mxv
	.byte	W02
	.byte		        26*seq_026_mvl/mxv
	.byte	W03
	.byte		        27*seq_026_mvl/mxv
	.byte	W02
	.byte		        28*seq_026_mvl/mxv
	.byte	W03
	.byte		        29*seq_026_mvl/mxv
	.byte	W02
	.byte		        31*seq_026_mvl/mxv
	.byte	W03
	.byte		        32*seq_026_mvl/mxv
	.byte	W02
	.byte		        33*seq_026_mvl/mxv
	.byte	W03
	.byte		        34*seq_026_mvl/mxv
	.byte	W03
	.byte		        36*seq_026_mvl/mxv
	.byte	W02
	.byte		        37*seq_026_mvl/mxv
	.byte	W03
	.byte		        38*seq_026_mvl/mxv
	.byte	W02
	.byte		        39*seq_026_mvl/mxv
	.byte	W03
	.byte		        41*seq_026_mvl/mxv
	.byte	W02
	.byte		        42*seq_026_mvl/mxv
	.byte	W02
	.byte	PEND
	.byte	W01
	.byte		VOL   , 43*seq_026_mvl/mxv
	.byte	W02
	.byte		        44*seq_026_mvl/mxv
	.byte	W03
	.byte		        46*seq_026_mvl/mxv
	.byte	W02
	.byte		        47*seq_026_mvl/mxv
	.byte	W03
	.byte		        48*seq_026_mvl/mxv
	.byte	W02
	.byte		        49*seq_026_mvl/mxv
	.byte	W03
	.byte		        51*seq_026_mvl/mxv
	.byte	W02
	.byte		        51*seq_026_mvl/mxv
	.byte	W03
	.byte		        53*seq_026_mvl/mxv
	.byte	W03
	.byte		        55*seq_026_mvl/mxv
	.byte	W02
	.byte		        55*seq_026_mvl/mxv
	.byte	W03
	.byte		        57*seq_026_mvl/mxv
	.byte	W02
	.byte		        58*seq_026_mvl/mxv
	.byte	W03
	.byte		        59*seq_026_mvl/mxv
	.byte	W02
	.byte		        60*seq_026_mvl/mxv
	.byte	W03
	.byte		        62*seq_026_mvl/mxv
	.byte	W02
	.byte		        63*seq_026_mvl/mxv
	.byte	W03
	.byte		        64*seq_026_mvl/mxv
	.byte	W02
	.byte		        65*seq_026_mvl/mxv
	.byte	W03
	.byte		        67*seq_026_mvl/mxv
	.byte	W02
	.byte		        68*seq_026_mvl/mxv
	.byte	W03
	.byte		        69*seq_026_mvl/mxv
	.byte	W32
	.byte		        65*seq_026_mvl/mxv
	.byte	W03
	.byte		        63*seq_026_mvl/mxv
	.byte	W06
	.byte		        58*seq_026_mvl/mxv
	.byte	W01
	.byte	PEND
	.byte	W04
	.byte		VOL   , 53*seq_026_mvl/mxv
	.byte	W05
	.byte		        49*seq_026_mvl/mxv
	.byte	W06
	.byte		        45*seq_026_mvl/mxv
	.byte	W05
	.byte		        41*seq_026_mvl/mxv
	.byte	W06
	.byte		        36*seq_026_mvl/mxv
	.byte	W05
	.byte		        31*seq_026_mvl/mxv
	.byte	W05
	.byte		        27*seq_026_mvl/mxv
	.byte	W06
	.byte		        23*seq_026_mvl/mxv
	.byte	W05
	.byte		        19*seq_026_mvl/mxv
	.byte	W06
	.byte		        14*seq_026_mvl/mxv
	.byte	W05
	.byte		        9*seq_026_mvl/mxv
	.byte	W05
	.byte		        6*seq_026_mvl/mxv
	.byte	W04
	.byte		        2*seq_026_mvl/mxv
	.byte	W03
	.byte		        0*seq_026_mvl/mxv
	.byte	W05
	.byte	PEND
	.byte		EOT   , Ds0 
	.byte	W01
	.byte		TIE   , FnM1, v120
	.byte	W05
	.byte		VOL   , 4*seq_026_mvl/mxv
	.byte	W05
	.byte		        8*seq_026_mvl/mxv
	.byte	W05
	.byte		        13*seq_026_mvl/mxv
	.byte	W05
	.byte		VOL   , 17*seq_026_mvl/mxv
	.byte	W05
	.byte		        21*seq_026_mvl/mxv
	.byte	W06
	.byte		        27*seq_026_mvl/mxv
	.byte	W05
	.byte		        32*seq_026_mvl/mxv
	.byte	W05
	.byte		        36*seq_026_mvl/mxv
	.byte	W05
	.byte		        41*seq_026_mvl/mxv
	.byte	W05
	.byte		        46*seq_026_mvl/mxv
	.byte	W06
	.byte		        51*seq_026_mvl/mxv
	.byte	W04
	.byte		        54*seq_026_mvl/mxv
	.byte	W05
	.byte		        59*seq_026_mvl/mxv
	.byte	W04
	.byte		        63*seq_026_mvl/mxv
	.byte	W05
	.byte		        67*seq_026_mvl/mxv
	.byte	W09
	.byte		        66*seq_026_mvl/mxv
	.byte	W05
	.byte		        62*seq_026_mvl/mxv
	.byte	W06
	.byte		        57*seq_026_mvl/mxv
	.byte	W04
	.byte		        53*seq_026_mvl/mxv
	.byte	W04
	.byte		        51*seq_026_mvl/mxv
	.byte	W04
	.byte		        47*seq_026_mvl/mxv
	.byte	W05
	.byte		        43*seq_026_mvl/mxv
	.byte	W04
	.byte	PEND
	.byte	W02
	.byte		VOL   , 38*seq_026_mvl/mxv
	.byte	W05
	.byte		        33*seq_026_mvl/mxv
	.byte	W05
	.byte		        29*seq_026_mvl/mxv
	.byte	W06
	.byte		        24*seq_026_mvl/mxv
	.byte	W05
	.byte		        19*seq_026_mvl/mxv
	.byte	W06
	.byte		        14*seq_026_mvl/mxv
	.byte	W05
	.byte		        10*seq_026_mvl/mxv
	.byte	W05
	.byte		        6*seq_026_mvl/mxv
	.byte	W06
	.byte		        1*seq_026_mvl/mxv
	.byte	W01
	.byte	PEND
	.byte		EOT   , FnM1
	.byte		VOL   , 0*seq_026_mvl/mxv
	.byte	W48
	.byte	W02
	.byte	W96
	.byte	W15
	.byte		TIE   , Dn0 , v120
	.byte	W07
	.byte		VOL   , 2*seq_026_mvl/mxv
	.byte	W08
	.byte		        5*seq_026_mvl/mxv
	.byte	W07
	.byte		        8*seq_026_mvl/mxv
	.byte	W08
	.byte		        11*seq_026_mvl/mxv
	.byte	W08
	.byte		        14*seq_026_mvl/mxv
	.byte	W07
	.byte		        17*seq_026_mvl/mxv
	.byte	W08
	.byte		        19*seq_026_mvl/mxv
	.byte	W08
	.byte		        22*seq_026_mvl/mxv
	.byte	W07
	.byte		        25*seq_026_mvl/mxv
	.byte	W08
	.byte		        28*seq_026_mvl/mxv
	.byte	W05
	.byte	PEND
	.byte	W03
	.byte		VOL   , 31*seq_026_mvl/mxv
	.byte	W07
	.byte		        34*seq_026_mvl/mxv
	.byte	W08
	.byte		        36*seq_026_mvl/mxv
	.byte	W06
	.byte		        38*seq_026_mvl/mxv
	.byte	W06
	.byte		        41*seq_026_mvl/mxv
	.byte	W14
	.byte		        41*seq_026_mvl/mxv
	.byte	W06
	.byte		        38*seq_026_mvl/mxv
	.byte	W05
	.byte		        36*seq_026_mvl/mxv
	.byte	W06
	.byte		        33*seq_026_mvl/mxv
	.byte	W05
	.byte		        30*seq_026_mvl/mxv
	.byte	W05
	.byte		        27*seq_026_mvl/mxv
	.byte	W06
	.byte		        24*seq_026_mvl/mxv
	.byte	W05
	.byte		        21*seq_026_mvl/mxv
	.byte	W06
	.byte		        19*seq_026_mvl/mxv
	.byte	W05
	.byte		        16*seq_026_mvl/mxv
	.byte	W03
	.byte	PEND
	.byte	W02
	.byte		VOL   , 13*seq_026_mvl/mxv
	.byte	W06
	.byte		        10*seq_026_mvl/mxv
	.byte	W05
	.byte		        7*seq_026_mvl/mxv
	.byte	W06
	.byte		        4*seq_026_mvl/mxv
	.byte	W05
	.byte		        2*seq_026_mvl/mxv
	.byte	W04
	.byte	PEND
	.byte		EOT   , Dn0 
	.byte		VOL   , 0*seq_026_mvl/mxv
	.byte	W68
	.byte	W66
	.byte		TIE   , Cn0 , v120
	.byte	W02
	.byte		VOL   , 2*seq_026_mvl/mxv
	.byte	W08
	.byte		        5*seq_026_mvl/mxv
	.byte	W07
	.byte		        8*seq_026_mvl/mxv
	.byte	W08
	.byte		        11*seq_026_mvl/mxv
	.byte	W05
	.byte	PEND
	.byte	W03
	.byte		VOL   , 14*seq_026_mvl/mxv
	.byte	W07
	.byte		        17*seq_026_mvl/mxv
	.byte	W08
	.byte		        19*seq_026_mvl/mxv
	.byte	W08
	.byte		        22*seq_026_mvl/mxv
	.byte	W07
	.byte		        25*seq_026_mvl/mxv
	.byte	W08
	.byte		        28*seq_026_mvl/mxv
	.byte	W08
	.byte		        31*seq_026_mvl/mxv
	.byte	W07
	.byte		        34*seq_026_mvl/mxv
	.byte	W08
	.byte		        36*seq_026_mvl/mxv
	.byte	W06
	.byte		        38*seq_026_mvl/mxv
	.byte	W06
	.byte		        41*seq_026_mvl/mxv
	.byte	W14
	.byte		        41*seq_026_mvl/mxv
	.byte	W06
	.byte	PEND
	.byte		VOL   , 38*seq_026_mvl/mxv
	.byte	W05
	.byte		        36*seq_026_mvl/mxv
	.byte	W06
	.byte		        33*seq_026_mvl/mxv
	.byte	W05
	.byte		        30*seq_026_mvl/mxv
	.byte	W05
	.byte		        27*seq_026_mvl/mxv
	.byte	W06
	.byte		        24*seq_026_mvl/mxv
	.byte	W05
	.byte		        21*seq_026_mvl/mxv
	.byte	W06
	.byte		        19*seq_026_mvl/mxv
	.byte	W05
	.byte		        16*seq_026_mvl/mxv
	.byte	W05
	.byte		        13*seq_026_mvl/mxv
	.byte	W06
	.byte		        10*seq_026_mvl/mxv
	.byte	W05
	.byte		        7*seq_026_mvl/mxv
	.byte	W06
	.byte		        4*seq_026_mvl/mxv
	.byte	W05
	.byte		        2*seq_026_mvl/mxv
	.byte	W04
	.byte		        0*seq_026_mvl/mxv
	.byte	W22
	.byte	PEND
	.byte		EOT   , Cn0 
	.byte	W88
	.byte		TIE   , Gs0 , v120
	.byte	W02
	.byte		VOL   , 2*seq_026_mvl/mxv
	.byte	W06
	.byte	PEND
	.byte	W02
	.byte		VOL   , 5*seq_026_mvl/mxv
	.byte	W07
	.byte		        8*seq_026_mvl/mxv
	.byte	W08
	.byte		        11*seq_026_mvl/mxv
	.byte	W08
	.byte		        14*seq_026_mvl/mxv
	.byte	W07
	.byte		        17*seq_026_mvl/mxv
	.byte	W08
	.byte		        19*seq_026_mvl/mxv
	.byte	W08
	.byte		        22*seq_026_mvl/mxv
	.byte	W07
	.byte		        25*seq_026_mvl/mxv
	.byte	W08
	.byte		        28*seq_026_mvl/mxv
	.byte	W08
	.byte		        31*seq_026_mvl/mxv
	.byte	W07
	.byte		        34*seq_026_mvl/mxv
	.byte	W08
	.byte		        36*seq_026_mvl/mxv
	.byte	W06
	.byte		        38*seq_026_mvl/mxv
	.byte	W04
	.byte	PEND
	.byte	W02
	.byte		VOL   , 41*seq_026_mvl/mxv
	.byte	W14
	.byte		        41*seq_026_mvl/mxv
	.byte	W06
	.byte		        38*seq_026_mvl/mxv
	.byte	W05
	.byte		        36*seq_026_mvl/mxv
	.byte	W06
	.byte		        33*seq_026_mvl/mxv
	.byte	W05
	.byte		        30*seq_026_mvl/mxv
	.byte	W05
	.byte		        27*seq_026_mvl/mxv
	.byte	W06
	.byte		        24*seq_026_mvl/mxv
	.byte	W05
	.byte		        21*seq_026_mvl/mxv
	.byte	W06
	.byte		        19*seq_026_mvl/mxv
	.byte	W05
	.byte		        16*seq_026_mvl/mxv
	.byte	W05
	.byte		        13*seq_026_mvl/mxv
	.byte	W06
	.byte		        10*seq_026_mvl/mxv
	.byte	W05
	.byte		        7*seq_026_mvl/mxv
	.byte	W06
	.byte		        4*seq_026_mvl/mxv
	.byte	W05
	.byte		        2*seq_026_mvl/mxv
	.byte	W04
	.byte	PEND
	.byte		EOT   , Gs0 
	.byte		VOL   , 0*seq_026_mvl/mxv
	.byte	W76
	.byte	W01
	.byte		TIE   , Cn1 , v120
	.byte	W01
	.byte		VOL   , 2*seq_026_mvl/mxv
	.byte	W08
	.byte		        5*seq_026_mvl/mxv
	.byte	W07
	.byte		        8*seq_026_mvl/mxv
	.byte	W03
	.byte	PEND
	.byte	W05
	.byte		VOL   , 11*seq_026_mvl/mxv
	.byte	W08
	.byte		        14*seq_026_mvl/mxv
	.byte	W07
	.byte		        17*seq_026_mvl/mxv
	.byte	W08
	.byte		        19*seq_026_mvl/mxv
	.byte	W08
	.byte		        22*seq_026_mvl/mxv
	.byte	W07
	.byte		        25*seq_026_mvl/mxv
	.byte	W08
	.byte		        28*seq_026_mvl/mxv
	.byte	W08
	.byte		        31*seq_026_mvl/mxv
	.byte	W07
	.byte		        34*seq_026_mvl/mxv
	.byte	W08
	.byte		        36*seq_026_mvl/mxv
	.byte	W06
	.byte		        38*seq_026_mvl/mxv
	.byte	W06
	.byte		        41*seq_026_mvl/mxv
	.byte	W10
	.byte	PEND
	.byte	W04
	.byte		VOL   , 41*seq_026_mvl/mxv
	.byte	W06
	.byte		        38*seq_026_mvl/mxv
	.byte	W05
	.byte		        36*seq_026_mvl/mxv
	.byte	W06
	.byte		        33*seq_026_mvl/mxv
	.byte	W05
	.byte		        30*seq_026_mvl/mxv
	.byte	W05
	.byte		        27*seq_026_mvl/mxv
	.byte	W06
	.byte		        24*seq_026_mvl/mxv
	.byte	W05
	.byte		        21*seq_026_mvl/mxv
	.byte	W06
	.byte		        19*seq_026_mvl/mxv
	.byte	W05
	.byte		        16*seq_026_mvl/mxv
	.byte	W05
	.byte		        13*seq_026_mvl/mxv
	.byte	W06
	.byte		        10*seq_026_mvl/mxv
	.byte	W05
	.byte		        7*seq_026_mvl/mxv
	.byte	W06
	.byte		        4*seq_026_mvl/mxv
	.byte	W05
	.byte		        2*seq_026_mvl/mxv
	.byte	W04
	.byte		        0*seq_026_mvl/mxv
	.byte	W12
	.byte	PEND
	.byte	W64
	.byte		EOT   , Cn1 
	.byte	W32
	.byte	W68
	.byte	W03
	.byte		TIE   , As0 , v120
	.byte	W01
	.byte		VOL   , 2*seq_026_mvl/mxv
	.byte	W08
	.byte		        5*seq_026_mvl/mxv
	.byte	W07
	.byte		        8*seq_026_mvl/mxv
	.byte	W08
	.byte		        11*seq_026_mvl/mxv
	.byte	W01
	.byte	PEND
	.byte	W07
	.byte		VOL   , 14*seq_026_mvl/mxv
	.byte	W07
	.byte		        17*seq_026_mvl/mxv
	.byte	W08
	.byte		        19*seq_026_mvl/mxv
	.byte	W08
	.byte		        22*seq_026_mvl/mxv
	.byte	W07
	.byte		        25*seq_026_mvl/mxv
	.byte	W08
	.byte		        28*seq_026_mvl/mxv
	.byte	W08
	.byte		        31*seq_026_mvl/mxv
	.byte	W07
	.byte		        34*seq_026_mvl/mxv
	.byte	W08
	.byte		        36*seq_026_mvl/mxv
	.byte	W06
	.byte		        38*seq_026_mvl/mxv
	.byte	W06
	.byte		        41*seq_026_mvl/mxv
	.byte	W14
	.byte		        41*seq_026_mvl/mxv
	.byte	W02
	.byte	PEND
	.byte	W04
	.byte		VOL   , 38*seq_026_mvl/mxv
	.byte	W05
	.byte		        36*seq_026_mvl/mxv
	.byte	W06
	.byte		        33*seq_026_mvl/mxv
	.byte	W05
	.byte		        30*seq_026_mvl/mxv
	.byte	W05
	.byte		        27*seq_026_mvl/mxv
	.byte	W06
	.byte		        24*seq_026_mvl/mxv
	.byte	W05
	.byte		        21*seq_026_mvl/mxv
	.byte	W06
	.byte		        19*seq_026_mvl/mxv
	.byte	W05
	.byte		        16*seq_026_mvl/mxv
	.byte	W05
	.byte		        13*seq_026_mvl/mxv
	.byte	W06
	.byte		        10*seq_026_mvl/mxv
	.byte	W05
	.byte		        7*seq_026_mvl/mxv
	.byte	W06
	.byte		        4*seq_026_mvl/mxv
	.byte	W05
	.byte		        2*seq_026_mvl/mxv
	.byte	W04
	.byte		        0*seq_026_mvl/mxv
	.byte	W18
	.byte	PEND
	.byte	W56
	.byte	W02
	.byte		EOT   , As0 
	.byte	W36
	.byte	W02
	.byte	PATT
	 .word	seq_026_1 + 0x13
	.byte	PATT
	 .word	seq_026_1 + 0x60
	.byte	PATT
	 .word	seq_026_1 + 0x95
	.byte		EOT   , Ds0 
	.byte	W01
	.byte		TIE   , FnM1, v120
	.byte	W05
	.byte		VOL   , 4*seq_026_mvl/mxv
	.byte	W05
	.byte		        8*seq_026_mvl/mxv
	.byte	W05
	.byte		        13*seq_026_mvl/mxv
	.byte	W05
	.byte	PATT
	 .word	seq_026_1 + 0xC2
	.byte	PATT
	 .word	seq_026_1 + 0xEA
	.byte		EOT   , FnM1
	.byte		VOL   , 0*seq_026_mvl/mxv
	.byte	W48
	.byte	W02
	.byte	W96
	.byte	PATT
	 .word	seq_026_1 + 0x106
	.byte	PATT
	 .word	seq_026_1 + 0x121
	.byte	PATT
	 .word	seq_026_1 + 0x142
	.byte		EOT   , Dn0 
	.byte		VOL   , 0*seq_026_mvl/mxv
	.byte	W68
	.byte	PATT
	 .word	seq_026_1 + 0x154
	.byte	PATT
	 .word	seq_026_1 + 0x163
	.byte	PATT
	 .word	seq_026_1 + 0x17E
	.byte		EOT   , Cn0 
	.byte	PATT
	 .word	seq_026_1 + 0x1A0
	.byte	PATT
	 .word	seq_026_1 + 0x1A9
	.byte	PATT
	 .word	seq_026_1 + 0x1C6
	.byte		EOT   , Gs0 
	.byte	PATT
	 .word	seq_026_1 + 0x1EB
	.byte	PATT
	 .word	seq_026_1 + 0x1FB
	.byte	PATT
	 .word	seq_026_1 + 0x216
	.byte	W64
	.byte		EOT   , Cn1 
	.byte	W32
	.byte	PATT
	 .word	seq_026_1 + 0x23D
	.byte	PATT
	 .word	seq_026_1 + 0x24D
	.byte	PATT
	 .word	seq_026_1 + 0x268
	.byte	W56
	.byte	W02
	.byte		EOT   , As0 
	.byte	W36
	.byte	W02
	.byte	PATT
	 .word	seq_026_1 + 0x13
	.byte	PATT
	 .word	seq_026_1 + 0x60
	.byte	PATT
	 .word	seq_026_1 + 0x95
	.byte		EOT   , Ds0 
	.byte	W01
	.byte		TIE   , FnM1, v120
	.byte	W05
	.byte		VOL   , 4*seq_026_mvl/mxv
	.byte	W05
	.byte		        8*seq_026_mvl/mxv
	.byte	W05
	.byte		        13*seq_026_mvl/mxv
	.byte	W05
	.byte	PATT
	 .word	seq_026_1 + 0xC2
	.byte	PATT
	 .word	seq_026_1 + 0xEA
	.byte		EOT   , FnM1
	.byte		VOL   , 0*seq_026_mvl/mxv
	.byte	W48
	.byte	W02
	.byte	W96
	.byte	PATT
	 .word	seq_026_1 + 0x106
	.byte	PATT
	 .word	seq_026_1 + 0x121
	.byte	PATT
	 .word	seq_026_1 + 0x142
	.byte		EOT   , Dn0 
	.byte		VOL   , 0*seq_026_mvl/mxv
	.byte	W68
	.byte	PATT
	 .word	seq_026_1 + 0x154
	.byte	PATT
	 .word	seq_026_1 + 0x163
	.byte	PATT
	 .word	seq_026_1 + 0x17E
	.byte		EOT   , Cn0 
	.byte	PATT
	 .word	seq_026_1 + 0x1A0
	.byte	PATT
	 .word	seq_026_1 + 0x1A9
	.byte	PATT
	 .word	seq_026_1 + 0x1C6
	.byte		EOT   , Gs0 
	.byte	PATT
	 .word	seq_026_1 + 0x1EB
	.byte	PATT
	 .word	seq_026_1 + 0x1FB
	.byte	PATT
	 .word	seq_026_1 + 0x216
	.byte	W64
	.byte		EOT   , Cn1 
	.byte	W32
	.byte	PATT
	 .word	seq_026_1 + 0x23D
	.byte	PATT
	 .word	seq_026_1 + 0x24D
	.byte	PATT
	 .word	seq_026_1 + 0x268
	.byte	W56
	.byte	W02
	.byte		EOT   , As0 
	.byte	W36
	.byte	W02
	.byte	PATT
	 .word	seq_026_1 + 0x13
	.byte	PATT
	 .word	seq_026_1 + 0x60
	.byte	PATT
	 .word	seq_026_1 + 0x95
	.byte		EOT   , Ds0 
	.byte	W01
	.byte		TIE   , FnM1, v120
	.byte	W05
	.byte		VOL   , 4*seq_026_mvl/mxv
	.byte	W05
	.byte		        8*seq_026_mvl/mxv
	.byte	W05
	.byte		        13*seq_026_mvl/mxv
	.byte	W05
	.byte	PATT
	 .word	seq_026_1 + 0xC2
	.byte	PATT
	 .word	seq_026_1 + 0xEA
	.byte		EOT   , FnM1
	.byte		VOL   , 0*seq_026_mvl/mxv
	.byte	W48
	.byte	W02
	.byte	W96
	.byte	PATT
	 .word	seq_026_1 + 0x106
	.byte	PATT
	 .word	seq_026_1 + 0x121
	.byte	PATT
	 .word	seq_026_1 + 0x142
	.byte		EOT   , Dn0 
	.byte		VOL   , 0*seq_026_mvl/mxv
	.byte	W68
	.byte	PATT
	 .word	seq_026_1 + 0x154
	.byte	PATT
	 .word	seq_026_1 + 0x163
	.byte	PATT
	 .word	seq_026_1 + 0x17E
	.byte		EOT   , Cn0 
	.byte	PATT
	 .word	seq_026_1 + 0x1A0
	.byte	PATT
	 .word	seq_026_1 + 0x1A9
	.byte	PATT
	 .word	seq_026_1 + 0x1C6
	.byte		EOT   , Gs0 
	.byte	PATT
	 .word	seq_026_1 + 0x1EB
	.byte	PATT
	 .word	seq_026_1 + 0x1FB
	.byte	PATT
	 .word	seq_026_1 + 0x216
	.byte	W64
	.byte		EOT   , Cn1 
	.byte	W32
	.byte	PATT
	 .word	seq_026_1 + 0x23D
	.byte	PATT
	 .word	seq_026_1 + 0x24D
	.byte	PATT
	 .word	seq_026_1 + 0x268
	.byte	W56
	.byte	W02
	.byte		EOT   , As0 
	.byte	W36
	.byte	W02
	.byte	PATT
	 .word	seq_026_1 + 0x13
	.byte	PATT
	 .word	seq_026_1 + 0x60
	.byte	PATT
	 .word	seq_026_1 + 0x95
	.byte		EOT   , Ds0 
	.byte	W01
	.byte		TIE   , FnM1, v120
	.byte	W05
	.byte		VOL   , 4*seq_026_mvl/mxv
	.byte	W05
	.byte		        8*seq_026_mvl/mxv
	.byte	W05
	.byte		        13*seq_026_mvl/mxv
	.byte	W05
	.byte	PATT
	 .word	seq_026_1 + 0xC2
	.byte	PATT
	 .word	seq_026_1 + 0xEA
	.byte		EOT   , FnM1
	.byte		VOL   , 0*seq_026_mvl/mxv
	.byte	W48
	.byte	W02
	.byte	W96
	.byte	PATT
	 .word	seq_026_1 + 0x106
	.byte	PATT
	 .word	seq_026_1 + 0x121
	.byte	PATT
	 .word	seq_026_1 + 0x142
	.byte		EOT   , Dn0 
	.byte		VOL   , 0*seq_026_mvl/mxv
	.byte	W68
	.byte	PATT
	 .word	seq_026_1 + 0x154
	.byte	PATT
	 .word	seq_026_1 + 0x163
	.byte	PATT
	 .word	seq_026_1 + 0x17E
	.byte		EOT   , Cn0 
	.byte	PATT
	 .word	seq_026_1 + 0x1A0
	.byte	PATT
	 .word	seq_026_1 + 0x1A9
	.byte	PATT
	 .word	seq_026_1 + 0x1C6
	.byte		EOT   , Gs0 
	.byte	PATT
	 .word	seq_026_1 + 0x1EB
	.byte	PATT
	 .word	seq_026_1 + 0x1FB
	.byte	PATT
	 .word	seq_026_1 + 0x216
	.byte	W64
	.byte		EOT   , Cn1 
	.byte	W32
	.byte	PATT
	 .word	seq_026_1 + 0x23D
	.byte	PATT
	 .word	seq_026_1 + 0x24D
	.byte	PATT
	 .word	seq_026_1 + 0x268
	.byte	W56
	.byte	W02
	.byte		EOT   , As0 
	.byte	W36
	.byte	W02
	.byte	PATT
	 .word	seq_026_1 + 0x13
	.byte	PATT
	 .word	seq_026_1 + 0x60
	.byte	PATT
	 .word	seq_026_1 + 0x95
	.byte		EOT   , Ds0 
	.byte	W01
	.byte		TIE   , FnM1, v120
	.byte	W05
	.byte		VOL   , 4*seq_026_mvl/mxv
	.byte	W05
	.byte		        8*seq_026_mvl/mxv
	.byte	W05
	.byte		        13*seq_026_mvl/mxv
	.byte	W05
	.byte	PATT
	 .word	seq_026_1 + 0xC2
	.byte	PATT
	 .word	seq_026_1 + 0xEA
	.byte		EOT   , FnM1
	.byte		VOL   , 0*seq_026_mvl/mxv
	.byte	W48
	.byte	W02
	.byte	W96
	.byte	PATT
	 .word	seq_026_1 + 0x106
	.byte	PATT
	 .word	seq_026_1 + 0x121
	.byte	PATT
	 .word	seq_026_1 + 0x142
	.byte		EOT   , Dn0 
	.byte		VOL   , 0*seq_026_mvl/mxv
	.byte	W68
	.byte	PATT
	 .word	seq_026_1 + 0x154
	.byte	PATT
	 .word	seq_026_1 + 0x163
	.byte	PATT
	 .word	seq_026_1 + 0x17E
	.byte		EOT   , Cn0 
	.byte	PATT
	 .word	seq_026_1 + 0x1A0
	.byte	PATT
	 .word	seq_026_1 + 0x1A9
	.byte	PATT
	 .word	seq_026_1 + 0x1C6
	.byte		EOT   , Gs0 
	.byte	PATT
	 .word	seq_026_1 + 0x1EB
	.byte	PATT
	 .word	seq_026_1 + 0x1FB
	.byte	PATT
	 .word	seq_026_1 + 0x216
	.byte	W64
	.byte		EOT   , Cn1 
	.byte	W32
	.byte	PATT
	 .word	seq_026_1 + 0x23D
	.byte	PATT
	 .word	seq_026_1 + 0x24D
	.byte	PATT
	 .word	seq_026_1 + 0x268
	.byte	W56
	.byte	W02
	.byte		EOT   , As0 
	.byte	W36
	.byte	W02
	.byte	PATT
	 .word	seq_026_1 + 0x13
	.byte	PATT
	 .word	seq_026_1 + 0x60
	.byte	PATT
	 .word	seq_026_1 + 0x95
	.byte		EOT   , Ds0 
	.byte	W01
	.byte		TIE   , FnM1, v120
	.byte	W05
	.byte		VOL   , 4*seq_026_mvl/mxv
	.byte	W05
	.byte		        8*seq_026_mvl/mxv
	.byte	W05
	.byte		        13*seq_026_mvl/mxv
	.byte	W05
	.byte	PATT
	 .word	seq_026_1 + 0xC2
	.byte	PATT
	 .word	seq_026_1 + 0xEA
	.byte		EOT   , FnM1
	.byte		VOL   , 0*seq_026_mvl/mxv
	.byte	W48
	.byte	W02
	.byte	W96
	.byte	PATT
	 .word	seq_026_1 + 0x106
	.byte	PATT
	 .word	seq_026_1 + 0x121
	.byte	PATT
	 .word	seq_026_1 + 0x142
	.byte		EOT   , Dn0 
	.byte		VOL   , 0*seq_026_mvl/mxv
	.byte	W68
	.byte	PATT
	 .word	seq_026_1 + 0x154
	.byte	PATT
	 .word	seq_026_1 + 0x163
	.byte	PATT
	 .word	seq_026_1 + 0x17E
	.byte		EOT   , Cn0 
	.byte	PATT
	 .word	seq_026_1 + 0x1A0
	.byte	PATT
	 .word	seq_026_1 + 0x1A9
	.byte	PATT
	 .word	seq_026_1 + 0x1C6
	.byte		EOT   , Gs0 
	.byte	PATT
	 .word	seq_026_1 + 0x1EB
	.byte	PATT
	 .word	seq_026_1 + 0x1FB
	.byte	PATT
	 .word	seq_026_1 + 0x216
	.byte	W64
	.byte		EOT   , Cn1 
	.byte	W32
	.byte	PATT
	 .word	seq_026_1 + 0x23D
	.byte	PATT
	 .word	seq_026_1 + 0x24D
	.byte	PATT
	 .word	seq_026_1 + 0x268
	.byte	W56
	.byte	W02
	.byte		EOT   , As0 
	.byte	W36
	.byte	W02
	.byte	PATT
	 .word	seq_026_1 + 0x13
	.byte	PATT
	 .word	seq_026_1 + 0x60
	.byte	PATT
	 .word	seq_026_1 + 0x95
	.byte		EOT   , Ds0 
	.byte	W01
	.byte		TIE   , FnM1, v120
	.byte	W05
	.byte		VOL   , 4*seq_026_mvl/mxv
	.byte	W05
	.byte		        8*seq_026_mvl/mxv
	.byte	W05
	.byte		        13*seq_026_mvl/mxv
	.byte	W05
	.byte	PATT
	 .word	seq_026_1 + 0xC2
	.byte	PATT
	 .word	seq_026_1 + 0xEA
	.byte		EOT   , FnM1
	.byte		VOL   , 0*seq_026_mvl/mxv
	.byte	W48
	.byte	W02
	.byte	W96
	.byte	PATT
	 .word	seq_026_1 + 0x106
	.byte	PATT
	 .word	seq_026_1 + 0x121
	.byte	PATT
	 .word	seq_026_1 + 0x142
	.byte		EOT   , Dn0 
	.byte		VOL   , 0*seq_026_mvl/mxv
	.byte	W68
	.byte	PATT
	 .word	seq_026_1 + 0x154
	.byte	PATT
	 .word	seq_026_1 + 0x163
	.byte	PATT
	 .word	seq_026_1 + 0x17E
	.byte		EOT   , Cn0 
	.byte	PATT
	 .word	seq_026_1 + 0x1A0
	.byte	PATT
	 .word	seq_026_1 + 0x1A9
	.byte	PATT
	 .word	seq_026_1 + 0x1C6
	.byte		EOT   , Gs0 
	.byte	PATT
	 .word	seq_026_1 + 0x1EB
	.byte	PATT
	 .word	seq_026_1 + 0x1FB
	.byte	PATT
	 .word	seq_026_1 + 0x216
	.byte	W64
	.byte		EOT   , Cn1 
	.byte	W32
	.byte	PATT
	 .word	seq_026_1 + 0x23D
	.byte	PATT
	 .word	seq_026_1 + 0x24D
	.byte	PATT
	 .word	seq_026_1 + 0x268
	.byte	W56
	.byte	W02
	.byte		EOT   , As0 
	.byte	W36
	.byte	W02
	.byte	PATT
	 .word	seq_026_1 + 0x13
	.byte	PATT
	 .word	seq_026_1 + 0x60
	.byte	PATT
	 .word	seq_026_1 + 0x95
	.byte		EOT   , Ds0 
	.byte	W01
	.byte		TIE   , FnM1, v120
	.byte	W05
	.byte		VOL   , 4*seq_026_mvl/mxv
	.byte	W05
	.byte		        8*seq_026_mvl/mxv
	.byte	W05
	.byte		        13*seq_026_mvl/mxv
	.byte	W05
	.byte	PATT
	 .word	seq_026_1 + 0xC2
	.byte	PATT
	 .word	seq_026_1 + 0xEA
	.byte		EOT   , FnM1
	.byte		VOL   , 0*seq_026_mvl/mxv
	.byte	W48
	.byte	W02
	.byte	W96
	.byte	PATT
	 .word	seq_026_1 + 0x106
	.byte	PATT
	 .word	seq_026_1 + 0x121
	.byte	PATT
	 .word	seq_026_1 + 0x142
	.byte		EOT   , Dn0 
	.byte		VOL   , 0*seq_026_mvl/mxv
	.byte	W68
	.byte	PATT
	 .word	seq_026_1 + 0x154
	.byte	PATT
	 .word	seq_026_1 + 0x163
	.byte	PATT
	 .word	seq_026_1 + 0x17E
	.byte		EOT   , Cn0 
	.byte	PATT
	 .word	seq_026_1 + 0x1A0
	.byte	PATT
	 .word	seq_026_1 + 0x1A9
	.byte	PATT
	 .word	seq_026_1 + 0x1C6
	.byte		EOT   , Gs0 
	.byte	PATT
	 .word	seq_026_1 + 0x1EB
	.byte	PATT
	 .word	seq_026_1 + 0x1FB
	.byte	PATT
	 .word	seq_026_1 + 0x216
	.byte	W64
	.byte		EOT   , Cn1 
	.byte	W32
	.byte	PATT
	 .word	seq_026_1 + 0x23D
	.byte	PATT
	 .word	seq_026_1 + 0x24D
	.byte	PATT
	 .word	seq_026_1 + 0x268
	.byte	W56
	.byte	W02
	.byte		EOT   , As0 
	.byte	W36
	.byte	W02
	.byte	PATT
	 .word	seq_026_1 + 0x13
	.byte	PATT
	 .word	seq_026_1 + 0x60
	.byte	PATT
	 .word	seq_026_1 + 0x95
	.byte		EOT   , Ds0 
	.byte	W01
	.byte		TIE   , FnM1, v120
	.byte	W05
	.byte		VOL   , 4*seq_026_mvl/mxv
	.byte	W05
	.byte		        8*seq_026_mvl/mxv
	.byte	W05
	.byte		        13*seq_026_mvl/mxv
	.byte	W05
	.byte	PATT
	 .word	seq_026_1 + 0xC2
	.byte	PATT
	 .word	seq_026_1 + 0xEA
	.byte		EOT   , FnM1
	.byte		VOL   , 0*seq_026_mvl/mxv
	.byte	W48
	.byte	W02
	.byte	W96
	.byte	PATT
	 .word	seq_026_1 + 0x106
	.byte	PATT
	 .word	seq_026_1 + 0x121
	.byte	PATT
	 .word	seq_026_1 + 0x142
	.byte		EOT   , Dn0 
	.byte		VOL   , 0*seq_026_mvl/mxv
	.byte	W68
	.byte	PATT
	 .word	seq_026_1 + 0x154
	.byte	PATT
	 .word	seq_026_1 + 0x163
	.byte	PATT
	 .word	seq_026_1 + 0x17E
	.byte		EOT   , Cn0 
	.byte	PATT
	 .word	seq_026_1 + 0x1A0
	.byte	PATT
	 .word	seq_026_1 + 0x1A9
	.byte	PATT
	 .word	seq_026_1 + 0x1C6
	.byte		EOT   , Gs0 
	.byte	PATT
	 .word	seq_026_1 + 0x1EB
	.byte	PATT
	 .word	seq_026_1 + 0x1FB
	.byte	PATT
	 .word	seq_026_1 + 0x216
	.byte	W64
	.byte		EOT   , Cn1 
	.byte	W32
	.byte	PATT
	 .word	seq_026_1 + 0x23D
	.byte	PATT
	 .word	seq_026_1 + 0x24D
	.byte	PATT
	 .word	seq_026_1 + 0x268
	.byte	W56
	.byte	W02
	.byte		EOT   , As0 
	.byte	W36
	.byte	W02
	.byte	PATT
	 .word	seq_026_1 + 0x13
	.byte	PATT
	 .word	seq_026_1 + 0x60
	.byte	PATT
	 .word	seq_026_1 + 0x95
	.byte		EOT   , Ds0 
	.byte	W01
	.byte		TIE   , FnM1, v120
	.byte	W05
	.byte		VOL   , 4*seq_026_mvl/mxv
	.byte	W05
	.byte		        8*seq_026_mvl/mxv
	.byte	W05
	.byte		        13*seq_026_mvl/mxv
	.byte	W05
	.byte	PATT
	 .word	seq_026_1 + 0xC2
	.byte	PATT
	 .word	seq_026_1 + 0xEA
	.byte		EOT   , FnM1
	.byte		VOL   , 0*seq_026_mvl/mxv
	.byte	W48
	.byte	W02
	.byte	W96
	.byte	PATT
	 .word	seq_026_1 + 0x106
	.byte	PATT
	 .word	seq_026_1 + 0x121
	.byte	PATT
	 .word	seq_026_1 + 0x142
	.byte		EOT   , Dn0 
	.byte		VOL   , 0*seq_026_mvl/mxv
	.byte	W68
	.byte	PATT
	 .word	seq_026_1 + 0x154
	.byte	PATT
	 .word	seq_026_1 + 0x163
	.byte	PATT
	 .word	seq_026_1 + 0x17E
	.byte		EOT   , Cn0 
	.byte	PATT
	 .word	seq_026_1 + 0x1A0
	.byte	PATT
	 .word	seq_026_1 + 0x1A9
	.byte	PATT
	 .word	seq_026_1 + 0x1C6
	.byte		EOT   , Gs0 
	.byte	PATT
	 .word	seq_026_1 + 0x1EB
	.byte	PATT
	 .word	seq_026_1 + 0x1FB
	.byte	PATT
	 .word	seq_026_1 + 0x216
	.byte	W64
	.byte		EOT   , Cn1 
	.byte	W32
	.byte	PATT
	 .word	seq_026_1 + 0x23D
	.byte	PATT
	 .word	seq_026_1 + 0x24D
	.byte	PATT
	 .word	seq_026_1 + 0x268
	.byte	W56
	.byte	W02
	.byte		EOT   , As0 
	.byte	W36
	.byte	W02
	.byte	PATT
	 .word	seq_026_1 + 0x13
	.byte	PATT
	 .word	seq_026_1 + 0x60
	.byte	PATT
	 .word	seq_026_1 + 0x95
	.byte		EOT   , Ds0 
	.byte	W01
	.byte		TIE   , FnM1, v120
	.byte	W05
	.byte		VOL   , 4*seq_026_mvl/mxv
	.byte	W05
	.byte		        8*seq_026_mvl/mxv
	.byte	W05
	.byte		        13*seq_026_mvl/mxv
	.byte	W05
	.byte	PATT
	 .word	seq_026_1 + 0xC2
	.byte	PATT
	 .word	seq_026_1 + 0xEA
	.byte		EOT   , FnM1
	.byte		VOL   , 0*seq_026_mvl/mxv
	.byte	W48
	.byte	W02
	.byte	W96
	.byte	PATT
	 .word	seq_026_1 + 0x106
	.byte	PATT
	 .word	seq_026_1 + 0x121
	.byte	PATT
	 .word	seq_026_1 + 0x142
	.byte		EOT   , Dn0 
	.byte		VOL   , 0*seq_026_mvl/mxv
	.byte	W68
	.byte	PATT
	 .word	seq_026_1 + 0x154
	.byte	PATT
	 .word	seq_026_1 + 0x163
	.byte	PATT
	 .word	seq_026_1 + 0x17E
	.byte		EOT   , Cn0 
	.byte	PATT
	 .word	seq_026_1 + 0x1A0
	.byte	PATT
	 .word	seq_026_1 + 0x1A9
	.byte	PATT
	 .word	seq_026_1 + 0x1C6
	.byte		EOT   , Gs0 
	.byte	PATT
	 .word	seq_026_1 + 0x1EB
	.byte	PATT
	 .word	seq_026_1 + 0x1FB
	.byte	PATT
	 .word	seq_026_1 + 0x216
	.byte	W64
	.byte		EOT   , Cn1 
	.byte	W32
	.byte	PATT
	 .word	seq_026_1 + 0x23D
	.byte	PATT
	 .word	seq_026_1 + 0x24D
	.byte	PATT
	 .word	seq_026_1 + 0x268
	.byte	W56
	.byte	W02
	.byte		EOT   , As0 
	.byte	W36
	.byte	W02
	.byte	PATT
	 .word	seq_026_1 + 0x13
	.byte	PATT
	 .word	seq_026_1 + 0x60
	.byte	PATT
	 .word	seq_026_1 + 0x95
	.byte		EOT   , Ds0 
	.byte	W01
	.byte		TIE   , FnM1, v120
	.byte	W05
	.byte		VOL   , 4*seq_026_mvl/mxv
	.byte	W05
	.byte		        8*seq_026_mvl/mxv
	.byte	W05
	.byte		        13*seq_026_mvl/mxv
	.byte	W05
	.byte	PATT
	 .word	seq_026_1 + 0xC2
	.byte	PATT
	 .word	seq_026_1 + 0xEA
	.byte		EOT   , FnM1
	.byte		VOL   , 0*seq_026_mvl/mxv
	.byte	W48
	.byte	W02
	.byte	W96
	.byte	PATT
	 .word	seq_026_1 + 0x106
	.byte	PATT
	 .word	seq_026_1 + 0x121
	.byte	PATT
	 .word	seq_026_1 + 0x142
	.byte		EOT   , Dn0 
	.byte		VOL   , 0*seq_026_mvl/mxv
	.byte	W68
	.byte	PATT
	 .word	seq_026_1 + 0x154
	.byte	PATT
	 .word	seq_026_1 + 0x163
	.byte	PATT
	 .word	seq_026_1 + 0x17E
	.byte		EOT   , Cn0 
	.byte	PATT
	 .word	seq_026_1 + 0x1A0
	.byte	PATT
	 .word	seq_026_1 + 0x1A9
	.byte	PATT
	 .word	seq_026_1 + 0x1C6
	.byte		EOT   , Gs0 
	.byte	PATT
	 .word	seq_026_1 + 0x1EB
	.byte	PATT
	 .word	seq_026_1 + 0x1FB
	.byte	PATT
	 .word	seq_026_1 + 0x216
	.byte	W64
	.byte		EOT   , Cn1 
	.byte	W32
	.byte	PATT
	 .word	seq_026_1 + 0x23D
	.byte	PATT
	 .word	seq_026_1 + 0x24D
	.byte	PATT
	 .word	seq_026_1 + 0x268
	.byte	W56
	.byte	W02
	.byte		EOT   , As0 
	.byte	W36
	.byte	W02
	.byte	GOTO
	 .word	seq_026_1 + 0x13
	.byte	FINE

@*********************** Track 03 ***********************@

seq_026_2:
	.byte	KEYSH , seq_026_key+0
	.byte	W04
	.byte		VOL   , 42*seq_026_mvl/mxv
	.byte		PAN   , c_v-40
	.byte	W01
	.byte		VOICE , 44
	.byte		BENDR , 12
	.byte		LFOS  , 30
	.byte	W01
	.byte		MODT  , mod_vib
	.byte	W18
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W52
	.byte		TIE   , EnM1, v100
	.byte	W01
	.byte		VOL   , 0*seq_026_mvl/mxv
	.byte	W04
	.byte		        3*seq_026_mvl/mxv
	.byte	W03
	.byte		BEND  , c_v+3
	.byte	W03
	.byte		        c_v+11
	.byte	W02
	.byte		VOL   , 9*seq_026_mvl/mxv
	.byte	W01
	.byte		BEND  , c_v+17
	.byte	W02
	.byte		        c_v+22
	.byte	W01
	.byte		VOL   , 11*seq_026_mvl/mxv
	.byte	W01
	.byte		BEND  , c_v+26
	.byte	W02
	.byte		VOL   , 13*seq_026_mvl/mxv
	.byte	W01
	.byte		BEND  , c_v+32
	.byte	W02
	.byte		VOL   , 15*seq_026_mvl/mxv
	.byte	W03
	.byte		        17*seq_026_mvl/mxv
	.byte		BEND  , c_v+37
	.byte	W02
	.byte		        c_v+41
	.byte	W01
	.byte		VOL   , 19*seq_026_mvl/mxv
	.byte	W02
	.byte		BEND  , c_v+45
	.byte	W01
	.byte		VOL   , 21*seq_026_mvl/mxv
	.byte	W02
	.byte		BEND  , c_v+48
	.byte	W01
	.byte		VOL   , 24*seq_026_mvl/mxv
	.byte	W02
	.byte		BEND  , c_v+53
	.byte	W01
	.byte		VOL   , 26*seq_026_mvl/mxv
	.byte	W02
	.byte		BEND  , c_v+58
	.byte	W01
	.byte		VOL   , 28*seq_026_mvl/mxv
	.byte	W01
	.byte		BEND  , c_v+60
	.byte	W02
	.byte	PEND
	.byte		BEND  , c_v+63
	.byte	W01
	.byte		VOL   , 31*seq_026_mvl/mxv
	.byte	W03
	.byte		        33*seq_026_mvl/mxv
	.byte	W01
	.byte		        34*seq_026_mvl/mxv
	.byte	W03
	.byte		        36*seq_026_mvl/mxv
	.byte	W03
	.byte		        38*seq_026_mvl/mxv
	.byte	W03
	.byte		        40*seq_026_mvl/mxv
	.byte	W03
	.byte		        42*seq_026_mvl/mxv
	.byte	W24
	.byte	W03
	.byte		BEND  , c_v+61
	.byte	W04
	.byte		        c_v+58
	.byte	W04
	.byte		        c_v+54
	.byte	W04
	.byte		        c_v+51
	.byte	W03
	.byte		        c_v+48
	.byte	W06
	.byte		        c_v+45
	.byte	W07
	.byte		        c_v+42
	.byte	W04
	.byte		        c_v+39
	.byte	W04
	.byte		        c_v+36
	.byte	W05
	.byte		        c_v+33
	.byte	W06
	.byte		        c_v+30
	.byte	W05
	.byte	PEND
	.byte	W01
	.byte		BEND  , c_v+27
	.byte	W03
	.byte		        c_v+24
	.byte	W04
	.byte		        c_v+21
	.byte	W06
	.byte		        c_v+18
	.byte	W06
	.byte		        c_v+15
	.byte	W03
	.byte		        c_v+12
	.byte	W05
	.byte		VOL   , 41*seq_026_mvl/mxv
	.byte	W01
	.byte		        41*seq_026_mvl/mxv
	.byte	W01
	.byte		        40*seq_026_mvl/mxv
	.byte	W01
	.byte		        39*seq_026_mvl/mxv
	.byte		BEND  , c_v+8
	.byte	W01
	.byte		VOL   , 38*seq_026_mvl/mxv
	.byte		BEND  , c_v+6
	.byte	W01
	.byte		VOL   , 38*seq_026_mvl/mxv
	.byte	W01
	.byte		        37*seq_026_mvl/mxv
	.byte		BEND  , c_v+3
	.byte	W01
	.byte		VOL   , 36*seq_026_mvl/mxv
	.byte	W01
	.byte		BEND  , c_v+1
	.byte	W01
	.byte		VOL   , 34*seq_026_mvl/mxv
	.byte	W01
	.byte		        34*seq_026_mvl/mxv
	.byte		BEND  , c_v+0
	.byte	W01
	.byte		VOL   , 33*seq_026_mvl/mxv
	.byte	W01
	.byte		        32*seq_026_mvl/mxv
	.byte	W01
	.byte		        31*seq_026_mvl/mxv
	.byte	W01
	.byte		        31*seq_026_mvl/mxv
	.byte	W01
	.byte		        30*seq_026_mvl/mxv
	.byte	W01
	.byte		        29*seq_026_mvl/mxv
	.byte	W01
	.byte		        29*seq_026_mvl/mxv
	.byte	W01
	.byte		        28*seq_026_mvl/mxv
	.byte	W01
	.byte		        27*seq_026_mvl/mxv
	.byte	W01
	.byte		        26*seq_026_mvl/mxv
	.byte	W01
	.byte		        25*seq_026_mvl/mxv
	.byte	W01
	.byte		        24*seq_026_mvl/mxv
	.byte	W01
	.byte		        24*seq_026_mvl/mxv
	.byte	W01
	.byte		        23*seq_026_mvl/mxv
	.byte	W01
	.byte		        22*seq_026_mvl/mxv
	.byte	W01
	.byte		        21*seq_026_mvl/mxv
	.byte	W01
	.byte		        21*seq_026_mvl/mxv
	.byte	W01
	.byte		        20*seq_026_mvl/mxv
	.byte	W01
	.byte		        19*seq_026_mvl/mxv
	.byte	W01
	.byte		        18*seq_026_mvl/mxv
	.byte	W01
	.byte		        17*seq_026_mvl/mxv
	.byte	W01
	.byte		        17*seq_026_mvl/mxv
	.byte	W01
	.byte		        16*seq_026_mvl/mxv
	.byte	W01
	.byte		        15*seq_026_mvl/mxv
	.byte	W01
	.byte		        14*seq_026_mvl/mxv
	.byte	W01
	.byte		        14*seq_026_mvl/mxv
	.byte	W01
	.byte		        13*seq_026_mvl/mxv
	.byte	W01
	.byte		        12*seq_026_mvl/mxv
	.byte	W01
	.byte		        12*seq_026_mvl/mxv
	.byte	W01
	.byte		        11*seq_026_mvl/mxv
	.byte	W01
	.byte		        10*seq_026_mvl/mxv
	.byte	W01
	.byte		        9*seq_026_mvl/mxv
	.byte	W01
	.byte		        8*seq_026_mvl/mxv
	.byte	W01
	.byte		        7*seq_026_mvl/mxv
	.byte	W01
	.byte		        7*seq_026_mvl/mxv
	.byte	W01
	.byte		        6*seq_026_mvl/mxv
	.byte	W01
	.byte		        5*seq_026_mvl/mxv
	.byte	W01
	.byte		        4*seq_026_mvl/mxv
	.byte	W01
	.byte		        4*seq_026_mvl/mxv
	.byte	W01
	.byte		        3*seq_026_mvl/mxv
	.byte	W01
	.byte		        2*seq_026_mvl/mxv
	.byte	W01
	.byte		        1*seq_026_mvl/mxv
	.byte	W01
	.byte		        0*seq_026_mvl/mxv
	.byte	W01
	.byte		        0*seq_026_mvl/mxv
	.byte	W01
	.byte	PEND
	.byte		EOT   , EnM1
	.byte	W13
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_2 + 0x15
	.byte	PATT
	 .word	seq_026_2 + 0x60
	.byte	PATT
	 .word	seq_026_2 + 0x8B
	.byte		EOT   , EnM1
	.byte	W13
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_2 + 0x15
	.byte	PATT
	 .word	seq_026_2 + 0x60
	.byte	PATT
	 .word	seq_026_2 + 0x8B
	.byte		EOT   , EnM1
	.byte	W13
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_2 + 0x15
	.byte	PATT
	 .word	seq_026_2 + 0x60
	.byte	PATT
	 .word	seq_026_2 + 0x8B
	.byte		EOT   , EnM1
	.byte	W13
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_2 + 0x15
	.byte	PATT
	 .word	seq_026_2 + 0x60
	.byte	PATT
	 .word	seq_026_2 + 0x8B
	.byte		EOT   , EnM1
	.byte	W13
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_2 + 0x15
	.byte	PATT
	 .word	seq_026_2 + 0x60
	.byte	PATT
	 .word	seq_026_2 + 0x8B
	.byte		EOT   , EnM1
	.byte	W13
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_2 + 0x15
	.byte	PATT
	 .word	seq_026_2 + 0x60
	.byte	PATT
	 .word	seq_026_2 + 0x8B
	.byte		EOT   , EnM1
	.byte	W13
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_2 + 0x15
	.byte	PATT
	 .word	seq_026_2 + 0x60
	.byte	PATT
	 .word	seq_026_2 + 0x8B
	.byte		EOT   , EnM1
	.byte	W13
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_2 + 0x15
	.byte	PATT
	 .word	seq_026_2 + 0x60
	.byte	PATT
	 .word	seq_026_2 + 0x8B
	.byte		EOT   , EnM1
	.byte	W13
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_2 + 0x15
	.byte	PATT
	 .word	seq_026_2 + 0x60
	.byte	PATT
	 .word	seq_026_2 + 0x8B
	.byte		EOT   , EnM1
	.byte	W13
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_2 + 0x15
	.byte	PATT
	 .word	seq_026_2 + 0x60
	.byte	PATT
	 .word	seq_026_2 + 0x8B
	.byte		EOT   , EnM1
	.byte	W13
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_2 + 0x15
	.byte	PATT
	 .word	seq_026_2 + 0x60
	.byte	PATT
	 .word	seq_026_2 + 0x8B
	.byte		EOT   , EnM1
	.byte	W13
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_2 + 0x15
	.byte	PATT
	 .word	seq_026_2 + 0x60
	.byte	PATT
	 .word	seq_026_2 + 0x8B
	.byte		EOT   , EnM1
	.byte	W13
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_2 + 0x15
	.byte	PATT
	 .word	seq_026_2 + 0x60
	.byte	PATT
	 .word	seq_026_2 + 0x8B
	.byte		EOT   , EnM1
	.byte	W13
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_2 + 0x15
	.byte	PATT
	 .word	seq_026_2 + 0x60
	.byte	PATT
	 .word	seq_026_2 + 0x8B
	.byte		EOT   , EnM1
	.byte	W13
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_2 + 0x15
	.byte	PATT
	 .word	seq_026_2 + 0x60
	.byte	PATT
	 .word	seq_026_2 + 0x8B
	.byte		EOT   , EnM1
	.byte	W13
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_2 + 0x15
	.byte	PATT
	 .word	seq_026_2 + 0x60
	.byte	PATT
	 .word	seq_026_2 + 0x8B
	.byte		EOT   , EnM1
	.byte	W13
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_2 + 0x15
	.byte	PATT
	 .word	seq_026_2 + 0x60
	.byte	PATT
	 .word	seq_026_2 + 0x8B
	.byte		EOT   , EnM1
	.byte	W13
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_2 + 0x15
	.byte	PATT
	 .word	seq_026_2 + 0x60
	.byte	PATT
	 .word	seq_026_2 + 0x8B
	.byte		EOT   , EnM1
	.byte	W13
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_2 + 0x15
	.byte	PATT
	 .word	seq_026_2 + 0x60
	.byte	PATT
	 .word	seq_026_2 + 0x8B
	.byte		EOT   , EnM1
	.byte	W13
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_2 + 0x15
	.byte	PATT
	 .word	seq_026_2 + 0x60
	.byte	PATT
	 .word	seq_026_2 + 0x8B
	.byte		EOT   , EnM1
	.byte	W13
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_2 + 0x15
	.byte	PATT
	 .word	seq_026_2 + 0x60
	.byte	PATT
	 .word	seq_026_2 + 0x8B
	.byte		EOT   , EnM1
	.byte	W13
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_2 + 0x15
	.byte	PATT
	 .word	seq_026_2 + 0x60
	.byte	PATT
	 .word	seq_026_2 + 0x8B
	.byte		EOT   , EnM1
	.byte	W13
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_2 + 0x15
	.byte	PATT
	 .word	seq_026_2 + 0x60
	.byte	PATT
	 .word	seq_026_2 + 0x8B
	.byte		EOT   , EnM1
	.byte	W13
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_2 + 0x15
	.byte	PATT
	 .word	seq_026_2 + 0x60
	.byte	PATT
	 .word	seq_026_2 + 0x8B
	.byte		EOT   , EnM1
	.byte	W13
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_2 + 0x15
	.byte	PATT
	 .word	seq_026_2 + 0x60
	.byte	PATT
	 .word	seq_026_2 + 0x8B
	.byte		EOT   , EnM1
	.byte	W13
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_2 + 0x15
	.byte	PATT
	 .word	seq_026_2 + 0x60
	.byte	PATT
	 .word	seq_026_2 + 0x8B
	.byte		EOT   , EnM1
	.byte	W13
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_2 + 0x15
	.byte	PATT
	 .word	seq_026_2 + 0x60
	.byte	PATT
	 .word	seq_026_2 + 0x8B
	.byte		EOT   , EnM1
	.byte	W13
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_2 + 0x15
	.byte	PATT
	 .word	seq_026_2 + 0x60
	.byte	PATT
	 .word	seq_026_2 + 0x8B
	.byte		EOT   , EnM1
	.byte	W13
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_2 + 0x15
	.byte	PATT
	 .word	seq_026_2 + 0x60
	.byte	PATT
	 .word	seq_026_2 + 0x8B
	.byte		EOT   , EnM1
	.byte	W13
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	GOTO
	 .word	seq_026_2 + 0x12
	.byte	FINE

@*********************** Track 04 ***********************@

seq_026_3:
	.byte	KEYSH , seq_026_key+0
	.byte	W06
	.byte		VOICE , 44
	.byte		VOL   , 21*seq_026_mvl/mxv
	.byte	W01
	.byte		PAN   , c_v+40
	.byte		LFOS  , 40
	.byte		MODT  , mod_pan
	.byte	W01
	.byte		MOD   , 0
	.byte	W16
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W78
	.byte		TIE   , Cn1 , v120
	.byte	W01
	.byte		VOL   , 0*seq_026_mvl/mxv
	.byte	W04
	.byte		        1*seq_026_mvl/mxv
	.byte	W02
	.byte		BEND  , c_v+3
	.byte	W02
	.byte		VOL   , 3*seq_026_mvl/mxv
	.byte	W01
	.byte		BEND  , c_v+11
	.byte	W03
	.byte		VOL   , 5*seq_026_mvl/mxv
	.byte		BEND  , c_v+17
	.byte	W02
	.byte		        c_v+22
	.byte	W02
	.byte		VOL   , 7*seq_026_mvl/mxv
	.byte		BEND  , c_v+26
	.byte	W01
	.byte	PEND
	.byte	W02
	.byte		BEND  , c_v+32
	.byte	W01
	.byte		VOL   , 9*seq_026_mvl/mxv
	.byte	W04
	.byte		        11*seq_026_mvl/mxv
	.byte		BEND  , c_v+37
	.byte	W04
	.byte		VOL   , 13*seq_026_mvl/mxv
	.byte		BEND  , c_v+43
	.byte	W03
	.byte		        c_v+46
	.byte	W01
	.byte		VOL   , 15*seq_026_mvl/mxv
	.byte	W02
	.byte		BEND  , c_v+51
	.byte	W02
	.byte		VOL   , 17*seq_026_mvl/mxv
	.byte	W01
	.byte		BEND  , c_v+55
	.byte	W03
	.byte		VOL   , 19*seq_026_mvl/mxv
	.byte		BEND  , c_v+60
	.byte	W02
	.byte		        c_v+63
	.byte	W02
	.byte		VOL   , 21*seq_026_mvl/mxv
	.byte	W04
	.byte		        24*seq_026_mvl/mxv
	.byte	W04
	.byte		        26*seq_026_mvl/mxv
	.byte	W04
	.byte		        28*seq_026_mvl/mxv
	.byte	W14
	.byte		        28*seq_026_mvl/mxv
	.byte	W04
	.byte		        26*seq_026_mvl/mxv
	.byte	W04
	.byte		        24*seq_026_mvl/mxv
	.byte	W04
	.byte		        22*seq_026_mvl/mxv
	.byte	W04
	.byte		        20*seq_026_mvl/mxv
	.byte		BEND  , c_v+61
	.byte	W04
	.byte		VOL   , 19*seq_026_mvl/mxv
	.byte	W01
	.byte		BEND  , c_v+58
	.byte	W03
	.byte		VOL   , 16*seq_026_mvl/mxv
	.byte		BEND  , c_v+55
	.byte	W04
	.byte		VOL   , 14*seq_026_mvl/mxv
	.byte		BEND  , c_v+51
	.byte	W04
	.byte		VOL   , 12*seq_026_mvl/mxv
	.byte	W01
	.byte		BEND  , c_v+47
	.byte	W03
	.byte		VOL   , 10*seq_026_mvl/mxv
	.byte	W04
	.byte		        8*seq_026_mvl/mxv
	.byte		BEND  , c_v+44
	.byte	W03
	.byte	PEND
	.byte	W01
	.byte		VOL   , 6*seq_026_mvl/mxv
	.byte	W02
	.byte		BEND  , c_v+41
	.byte	W02
	.byte		VOL   , 4*seq_026_mvl/mxv
	.byte	W01
	.byte		BEND  , c_v+38
	.byte	W05
	.byte		VOL   , 0*seq_026_mvl/mxv
	.byte	W01
	.byte		BEND  , c_v+35
	.byte	W03
	.byte		        c_v+32
	.byte	W06
	.byte		        c_v+29
	.byte	W06
	.byte		        c_v+26
	.byte	W04
	.byte		        c_v+23
	.byte	W07
	.byte		        c_v+19
	.byte	W06
	.byte		        c_v+16
	.byte	W05
	.byte		        c_v+11
	.byte	W07
	.byte		        c_v+8
	.byte	W04
	.byte		        c_v+3
	.byte	W03
	.byte		        c_v+0
	.byte	W32
	.byte	W01
	.byte	PEND
	.byte	W13
	.byte		EOT   , Cn1 
	.byte	W80
	.byte	W03
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_3 + 0x16
	.byte	PATT
	 .word	seq_026_3 + 0x36
	.byte	PATT
	 .word	seq_026_3 + 0x8E
	.byte	W13
	.byte		EOT   , Cn1 
	.byte	W80
	.byte	W03
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_3 + 0x16
	.byte	PATT
	 .word	seq_026_3 + 0x36
	.byte	PATT
	 .word	seq_026_3 + 0x8E
	.byte	W13
	.byte		EOT   , Cn1 
	.byte	W80
	.byte	W03
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_3 + 0x16
	.byte	PATT
	 .word	seq_026_3 + 0x36
	.byte	PATT
	 .word	seq_026_3 + 0x8E
	.byte	W13
	.byte		EOT   , Cn1 
	.byte	W80
	.byte	W03
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_3 + 0x16
	.byte	PATT
	 .word	seq_026_3 + 0x36
	.byte	PATT
	 .word	seq_026_3 + 0x8E
	.byte	W13
	.byte		EOT   , Cn1 
	.byte	W80
	.byte	W03
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_3 + 0x16
	.byte	PATT
	 .word	seq_026_3 + 0x36
	.byte	PATT
	 .word	seq_026_3 + 0x8E
	.byte	W13
	.byte		EOT   , Cn1 
	.byte	W80
	.byte	W03
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_3 + 0x16
	.byte	PATT
	 .word	seq_026_3 + 0x36
	.byte	PATT
	 .word	seq_026_3 + 0x8E
	.byte	W13
	.byte		EOT   , Cn1 
	.byte	W80
	.byte	W03
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_3 + 0x16
	.byte	PATT
	 .word	seq_026_3 + 0x36
	.byte	PATT
	 .word	seq_026_3 + 0x8E
	.byte	W13
	.byte		EOT   , Cn1 
	.byte	W80
	.byte	W03
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_3 + 0x16
	.byte	PATT
	 .word	seq_026_3 + 0x36
	.byte	PATT
	 .word	seq_026_3 + 0x8E
	.byte	W13
	.byte		EOT   , Cn1 
	.byte	W80
	.byte	W03
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_3 + 0x16
	.byte	PATT
	 .word	seq_026_3 + 0x36
	.byte	PATT
	 .word	seq_026_3 + 0x8E
	.byte	W13
	.byte		EOT   , Cn1 
	.byte	W80
	.byte	W03
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_3 + 0x16
	.byte	PATT
	 .word	seq_026_3 + 0x36
	.byte	PATT
	 .word	seq_026_3 + 0x8E
	.byte	W13
	.byte		EOT   , Cn1 
	.byte	W80
	.byte	W03
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_3 + 0x16
	.byte	PATT
	 .word	seq_026_3 + 0x36
	.byte	PATT
	 .word	seq_026_3 + 0x8E
	.byte	W13
	.byte		EOT   , Cn1 
	.byte	W80
	.byte	W03
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_3 + 0x16
	.byte	PATT
	 .word	seq_026_3 + 0x36
	.byte	PATT
	 .word	seq_026_3 + 0x8E
	.byte	W13
	.byte		EOT   , Cn1 
	.byte	W80
	.byte	W03
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_3 + 0x16
	.byte	PATT
	 .word	seq_026_3 + 0x36
	.byte	PATT
	 .word	seq_026_3 + 0x8E
	.byte	W13
	.byte		EOT   , Cn1 
	.byte	W80
	.byte	W03
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_3 + 0x16
	.byte	PATT
	 .word	seq_026_3 + 0x36
	.byte	PATT
	 .word	seq_026_3 + 0x8E
	.byte	W13
	.byte		EOT   , Cn1 
	.byte	W80
	.byte	W03
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_3 + 0x16
	.byte	PATT
	 .word	seq_026_3 + 0x36
	.byte	PATT
	 .word	seq_026_3 + 0x8E
	.byte	W13
	.byte		EOT   , Cn1 
	.byte	W80
	.byte	W03
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_3 + 0x16
	.byte	PATT
	 .word	seq_026_3 + 0x36
	.byte	PATT
	 .word	seq_026_3 + 0x8E
	.byte	W13
	.byte		EOT   , Cn1 
	.byte	W80
	.byte	W03
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_3 + 0x16
	.byte	PATT
	 .word	seq_026_3 + 0x36
	.byte	PATT
	 .word	seq_026_3 + 0x8E
	.byte	W13
	.byte		EOT   , Cn1 
	.byte	W80
	.byte	W03
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_3 + 0x16
	.byte	PATT
	 .word	seq_026_3 + 0x36
	.byte	PATT
	 .word	seq_026_3 + 0x8E
	.byte	W13
	.byte		EOT   , Cn1 
	.byte	W80
	.byte	W03
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_3 + 0x16
	.byte	PATT
	 .word	seq_026_3 + 0x36
	.byte	PATT
	 .word	seq_026_3 + 0x8E
	.byte	W13
	.byte		EOT   , Cn1 
	.byte	W80
	.byte	W03
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_3 + 0x16
	.byte	PATT
	 .word	seq_026_3 + 0x36
	.byte	PATT
	 .word	seq_026_3 + 0x8E
	.byte	W13
	.byte		EOT   , Cn1 
	.byte	W80
	.byte	W03
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_3 + 0x16
	.byte	PATT
	 .word	seq_026_3 + 0x36
	.byte	PATT
	 .word	seq_026_3 + 0x8E
	.byte	W13
	.byte		EOT   , Cn1 
	.byte	W80
	.byte	W03
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_3 + 0x16
	.byte	PATT
	 .word	seq_026_3 + 0x36
	.byte	PATT
	 .word	seq_026_3 + 0x8E
	.byte	W13
	.byte		EOT   , Cn1 
	.byte	W80
	.byte	W03
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_3 + 0x16
	.byte	PATT
	 .word	seq_026_3 + 0x36
	.byte	PATT
	 .word	seq_026_3 + 0x8E
	.byte	W13
	.byte		EOT   , Cn1 
	.byte	W80
	.byte	W03
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_3 + 0x16
	.byte	PATT
	 .word	seq_026_3 + 0x36
	.byte	PATT
	 .word	seq_026_3 + 0x8E
	.byte	W13
	.byte		EOT   , Cn1 
	.byte	W80
	.byte	W03
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_3 + 0x16
	.byte	PATT
	 .word	seq_026_3 + 0x36
	.byte	PATT
	 .word	seq_026_3 + 0x8E
	.byte	W13
	.byte		EOT   , Cn1 
	.byte	W80
	.byte	W03
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_3 + 0x16
	.byte	PATT
	 .word	seq_026_3 + 0x36
	.byte	PATT
	 .word	seq_026_3 + 0x8E
	.byte	W13
	.byte		EOT   , Cn1 
	.byte	W80
	.byte	W03
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_3 + 0x16
	.byte	PATT
	 .word	seq_026_3 + 0x36
	.byte	PATT
	 .word	seq_026_3 + 0x8E
	.byte	W13
	.byte		EOT   , Cn1 
	.byte	W80
	.byte	W03
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_3 + 0x16
	.byte	PATT
	 .word	seq_026_3 + 0x36
	.byte	PATT
	 .word	seq_026_3 + 0x8E
	.byte	W13
	.byte		EOT   , Cn1 
	.byte	W80
	.byte	W03
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_3 + 0x16
	.byte	PATT
	 .word	seq_026_3 + 0x36
	.byte	PATT
	 .word	seq_026_3 + 0x8E
	.byte	W13
	.byte		EOT   , Cn1 
	.byte	W80
	.byte	W03
	.byte	W96
	.byte	W96
	.byte	GOTO
	 .word	seq_026_3 + 0x12
	.byte	FINE

@*********************** Track 05 ***********************@

seq_026_4:
	.byte	KEYSH , seq_026_key+0
	.byte	W08
	.byte		VOICE , 22
	.byte		VOL   , 49*seq_026_mvl/mxv
	.byte	W01
	.byte		MOD   , 4
	.byte		PAN   , c_v+0
	.byte		LFOS  , 20
	.byte	W01
	.byte		BENDR , 2
	.byte		MODT  , mod_tre
	.byte		LFODL , 20
	.byte	W14
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W68
	.byte	W02
	.byte		BEND  , c_v+0
	.byte	W24
	.byte	W02
	.byte	PEND
	.byte	W24
	.byte		VOL   , 1*seq_026_mvl/mxv
	.byte		TIE   , Fs4 , v056
	.byte	W06
	.byte		VOL   , 2*seq_026_mvl/mxv
	.byte	W04
	.byte		        1*seq_026_mvl/mxv
	.byte	W04
	.byte		        2*seq_026_mvl/mxv
	.byte	W04
	.byte		        3*seq_026_mvl/mxv
	.byte	W04
	.byte		        4*seq_026_mvl/mxv
	.byte	W04
	.byte		        4*seq_026_mvl/mxv
	.byte	W04
	.byte		        6*seq_026_mvl/mxv
	.byte	W04
	.byte		        7*seq_026_mvl/mxv
	.byte	W04
	.byte		        7*seq_026_mvl/mxv
	.byte	W04
	.byte		        9*seq_026_mvl/mxv
	.byte	W04
	.byte		        9*seq_026_mvl/mxv
	.byte	W04
	.byte		        10*seq_026_mvl/mxv
	.byte	W04
	.byte		        12*seq_026_mvl/mxv
	.byte	W04
	.byte		        12*seq_026_mvl/mxv
	.byte	W04
	.byte		        14*seq_026_mvl/mxv
	.byte	W04
	.byte		        15*seq_026_mvl/mxv
	.byte	W04
	.byte		        17*seq_026_mvl/mxv
	.byte	W02
	.byte	PEND
	.byte	W02
	.byte		VOL   , 19*seq_026_mvl/mxv
	.byte	W04
	.byte		        21*seq_026_mvl/mxv
	.byte	W04
	.byte		        23*seq_026_mvl/mxv
	.byte	W04
	.byte		        25*seq_026_mvl/mxv
	.byte	W04
	.byte		        27*seq_026_mvl/mxv
	.byte	W04
	.byte		        29*seq_026_mvl/mxv
	.byte	W04
	.byte		        31*seq_026_mvl/mxv
	.byte	W04
	.byte		        34*seq_026_mvl/mxv
	.byte	W04
	.byte		        37*seq_026_mvl/mxv
	.byte	W04
	.byte		        40*seq_026_mvl/mxv
	.byte	W04
	.byte		        43*seq_026_mvl/mxv
	.byte	W04
	.byte		        46*seq_026_mvl/mxv
	.byte	W04
	.byte		        48*seq_026_mvl/mxv
	.byte	W04
	.byte		        55*seq_026_mvl/mxv
	.byte	W04
	.byte		        62*seq_026_mvl/mxv
	.byte	W04
	.byte		        68*seq_026_mvl/mxv
	.byte	W04
	.byte		        74*seq_026_mvl/mxv
	.byte		BEND  , c_v-2
	.byte	W02
	.byte		        c_v-5
	.byte	W02
	.byte		        c_v-5
	.byte	W02
	.byte		        c_v-6
	.byte	W02
	.byte		        c_v-6
	.byte	W02
	.byte		VOL   , 73*seq_026_mvl/mxv
	.byte		BEND  , c_v-7
	.byte	W02
	.byte		        c_v-8
	.byte	W02
	.byte		VOL   , 72*seq_026_mvl/mxv
	.byte		BEND  , c_v-8
	.byte	W02
	.byte		        c_v-9
	.byte	W02
	.byte		VOL   , 70*seq_026_mvl/mxv
	.byte	W02
	.byte		BEND  , c_v-10
	.byte	W02
	.byte		VOL   , 69*seq_026_mvl/mxv
	.byte		BEND  , c_v-11
	.byte	W04
	.byte		VOL   , 67*seq_026_mvl/mxv
	.byte		BEND  , c_v-16
	.byte	W02
	.byte		        c_v-17
	.byte	W02
	.byte	PEND
	.byte		VOL   , 65*seq_026_mvl/mxv
	.byte		BEND  , c_v-19
	.byte	W02
	.byte		        c_v-20
	.byte	W02
	.byte		VOL   , 62*seq_026_mvl/mxv
	.byte		BEND  , c_v-22
	.byte	W02
	.byte		        c_v-23
	.byte	W02
	.byte		VOL   , 53*seq_026_mvl/mxv
	.byte		BEND  , c_v-25
	.byte	W02
	.byte		        c_v-27
	.byte	W02
	.byte		VOL   , 43*seq_026_mvl/mxv
	.byte		BEND  , c_v-31
	.byte	W02
	.byte		        c_v-34
	.byte	W02
	.byte		VOL   , 34*seq_026_mvl/mxv
	.byte		BEND  , c_v-37
	.byte	W02
	.byte		        c_v-40
	.byte	W02
	.byte		VOL   , 24*seq_026_mvl/mxv
	.byte		BEND  , c_v-43
	.byte	W04
	.byte	PEND
	.byte		EOT   , Fs4 
	.byte	W72
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_4 + 0x1F
	.byte	W24
	.byte		VOL   , 1*seq_026_mvl/mxv
	.byte		TIE   , Gn4 , v056
	.byte	W06
	.byte		VOL   , 2*seq_026_mvl/mxv
	.byte	W04
	.byte		        1*seq_026_mvl/mxv
	.byte	W04
	.byte		        2*seq_026_mvl/mxv
	.byte	W04
	.byte		        3*seq_026_mvl/mxv
	.byte	W04
	.byte		        4*seq_026_mvl/mxv
	.byte	W04
	.byte		        4*seq_026_mvl/mxv
	.byte	W04
	.byte		        6*seq_026_mvl/mxv
	.byte	W04
	.byte		        7*seq_026_mvl/mxv
	.byte	W04
	.byte		        7*seq_026_mvl/mxv
	.byte	W04
	.byte		        9*seq_026_mvl/mxv
	.byte	W04
	.byte		        9*seq_026_mvl/mxv
	.byte	W04
	.byte		        10*seq_026_mvl/mxv
	.byte	W04
	.byte		        12*seq_026_mvl/mxv
	.byte	W04
	.byte		        12*seq_026_mvl/mxv
	.byte	W04
	.byte		        14*seq_026_mvl/mxv
	.byte	W04
	.byte		        15*seq_026_mvl/mxv
	.byte	W04
	.byte		        17*seq_026_mvl/mxv
	.byte	W02
	.byte	PEND
	.byte	PATT
	 .word	seq_026_4 + 0x51
	.byte	PATT
	 .word	seq_026_4 + 0xA0
	.byte		EOT   , Gn4 
	.byte	W72
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_4 + 0x1F
	.byte	PATT
	 .word	seq_026_4 + 0x26
	.byte	PATT
	 .word	seq_026_4 + 0x51
	.byte	PATT
	 .word	seq_026_4 + 0xA0
	.byte		EOT   , Fs4 
	.byte	W72
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_4 + 0x1F
	.byte	PATT
	 .word	seq_026_4 + 0xD7
	.byte	PATT
	 .word	seq_026_4 + 0x51
	.byte	PATT
	 .word	seq_026_4 + 0xA0
	.byte		EOT   , Gn4 
	.byte	W72
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_4 + 0x1F
	.byte	PATT
	 .word	seq_026_4 + 0x26
	.byte	PATT
	 .word	seq_026_4 + 0x51
	.byte	PATT
	 .word	seq_026_4 + 0xA0
	.byte		EOT   , Fs4 
	.byte	W72
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_4 + 0x1F
	.byte	PATT
	 .word	seq_026_4 + 0xD7
	.byte	PATT
	 .word	seq_026_4 + 0x51
	.byte	PATT
	 .word	seq_026_4 + 0xA0
	.byte		EOT   , Gn4 
	.byte	W72
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_4 + 0x1F
	.byte	PATT
	 .word	seq_026_4 + 0x26
	.byte	PATT
	 .word	seq_026_4 + 0x51
	.byte	PATT
	 .word	seq_026_4 + 0xA0
	.byte		EOT   , Fs4 
	.byte	W72
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_4 + 0x1F
	.byte	PATT
	 .word	seq_026_4 + 0xD7
	.byte	PATT
	 .word	seq_026_4 + 0x51
	.byte	PATT
	 .word	seq_026_4 + 0xA0
	.byte		EOT   , Gn4 
	.byte	W72
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_4 + 0x1F
	.byte	PATT
	 .word	seq_026_4 + 0x26
	.byte	PATT
	 .word	seq_026_4 + 0x51
	.byte	PATT
	 .word	seq_026_4 + 0xA0
	.byte		EOT   , Fs4 
	.byte	W72
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_4 + 0x1F
	.byte	PATT
	 .word	seq_026_4 + 0xD7
	.byte	PATT
	 .word	seq_026_4 + 0x51
	.byte	PATT
	 .word	seq_026_4 + 0xA0
	.byte		EOT   , Gn4 
	.byte	W72
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_4 + 0x1F
	.byte	PATT
	 .word	seq_026_4 + 0x26
	.byte	PATT
	 .word	seq_026_4 + 0x51
	.byte	PATT
	 .word	seq_026_4 + 0xA0
	.byte		EOT   , Fs4 
	.byte	W72
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_4 + 0x1F
	.byte	PATT
	 .word	seq_026_4 + 0xD7
	.byte	PATT
	 .word	seq_026_4 + 0x51
	.byte	PATT
	 .word	seq_026_4 + 0xA0
	.byte		EOT   , Gn4 
	.byte	W72
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_4 + 0x1F
	.byte	PATT
	 .word	seq_026_4 + 0x26
	.byte	PATT
	 .word	seq_026_4 + 0x51
	.byte	PATT
	 .word	seq_026_4 + 0xA0
	.byte		EOT   , Fs4 
	.byte	W72
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_4 + 0x1F
	.byte	PATT
	 .word	seq_026_4 + 0xD7
	.byte	PATT
	 .word	seq_026_4 + 0x51
	.byte	PATT
	 .word	seq_026_4 + 0xA0
	.byte		EOT   , Gn4 
	.byte	W72
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_4 + 0x1F
	.byte	PATT
	 .word	seq_026_4 + 0x26
	.byte	PATT
	 .word	seq_026_4 + 0x51
	.byte	PATT
	 .word	seq_026_4 + 0xA0
	.byte		EOT   , Fs4 
	.byte	W72
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_4 + 0x1F
	.byte	PATT
	 .word	seq_026_4 + 0xD7
	.byte	PATT
	 .word	seq_026_4 + 0x51
	.byte	PATT
	 .word	seq_026_4 + 0xA0
	.byte		EOT   , Gn4 
	.byte	W72
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_4 + 0x1F
	.byte	PATT
	 .word	seq_026_4 + 0x26
	.byte	PATT
	 .word	seq_026_4 + 0x51
	.byte	PATT
	 .word	seq_026_4 + 0xA0
	.byte		EOT   , Fs4 
	.byte	W72
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_4 + 0x1F
	.byte	PATT
	 .word	seq_026_4 + 0xD7
	.byte	PATT
	 .word	seq_026_4 + 0x51
	.byte	PATT
	 .word	seq_026_4 + 0xA0
	.byte		EOT   , Gn4 
	.byte	W72
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_4 + 0x1F
	.byte	PATT
	 .word	seq_026_4 + 0x26
	.byte	PATT
	 .word	seq_026_4 + 0x51
	.byte	PATT
	 .word	seq_026_4 + 0xA0
	.byte		EOT   , Fs4 
	.byte	W72
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_4 + 0x1F
	.byte	PATT
	 .word	seq_026_4 + 0xD7
	.byte	PATT
	 .word	seq_026_4 + 0x51
	.byte	PATT
	 .word	seq_026_4 + 0xA0
	.byte		EOT   , Gn4 
	.byte	W72
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_4 + 0x1F
	.byte	PATT
	 .word	seq_026_4 + 0x26
	.byte	PATT
	 .word	seq_026_4 + 0x51
	.byte	PATT
	 .word	seq_026_4 + 0xA0
	.byte		EOT   , Fs4 
	.byte	W72
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_4 + 0x1F
	.byte	PATT
	 .word	seq_026_4 + 0xD7
	.byte	PATT
	 .word	seq_026_4 + 0x51
	.byte	PATT
	 .word	seq_026_4 + 0xA0
	.byte		EOT   , Gn4 
	.byte	W72
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_4 + 0x1F
	.byte	PATT
	 .word	seq_026_4 + 0x26
	.byte	PATT
	 .word	seq_026_4 + 0x51
	.byte	PATT
	 .word	seq_026_4 + 0xA0
	.byte		EOT   , Fs4 
	.byte	W72
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_4 + 0x1F
	.byte	PATT
	 .word	seq_026_4 + 0xD7
	.byte	PATT
	 .word	seq_026_4 + 0x51
	.byte	PATT
	 .word	seq_026_4 + 0xA0
	.byte		EOT   , Gn4 
	.byte	W72
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_4 + 0x1F
	.byte	PATT
	 .word	seq_026_4 + 0x26
	.byte	PATT
	 .word	seq_026_4 + 0x51
	.byte	PATT
	 .word	seq_026_4 + 0xA0
	.byte		EOT   , Fs4 
	.byte	W72
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_4 + 0x1F
	.byte	PATT
	 .word	seq_026_4 + 0xD7
	.byte	PATT
	 .word	seq_026_4 + 0x51
	.byte	PATT
	 .word	seq_026_4 + 0xA0
	.byte		EOT   , Gn4 
	.byte	W72
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_4 + 0x1F
	.byte	PATT
	 .word	seq_026_4 + 0x26
	.byte	PATT
	 .word	seq_026_4 + 0x51
	.byte	PATT
	 .word	seq_026_4 + 0xA0
	.byte		EOT   , Fs4 
	.byte	W72
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_4 + 0x1F
	.byte	PATT
	 .word	seq_026_4 + 0xD7
	.byte	PATT
	 .word	seq_026_4 + 0x51
	.byte	PATT
	 .word	seq_026_4 + 0xA0
	.byte		EOT   , Gn4 
	.byte	W72
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_4 + 0x1F
	.byte	PATT
	 .word	seq_026_4 + 0x26
	.byte	PATT
	 .word	seq_026_4 + 0x51
	.byte	PATT
	 .word	seq_026_4 + 0xA0
	.byte		EOT   , Fs4 
	.byte	W72
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	GOTO
	 .word	seq_026_4 + 0x16
	.byte	FINE

@*********************** Track 06 ***********************@

seq_026_5:
	.byte	KEYSH , seq_026_key+0
	.byte	W11
	.byte		VOICE , 22
	.byte		VOL   , 49*seq_026_mvl/mxv
	.byte		PAN   , c_v+30
	.byte	W01
	.byte		MOD   , 4
	.byte		LFOS  , 20
	.byte		MODT  , mod_tre
	.byte	W01
	.byte		BENDR , 2
	.byte		LFODL , 20
	.byte	W11
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W22
	.byte		BEND  , c_v+0
	.byte	W48
	.byte	W02
	.byte		VOL   , 1*seq_026_mvl/mxv
	.byte		TIE   , Cs4 , v072
	.byte	W06
	.byte		VOL   , 2*seq_026_mvl/mxv
	.byte	W04
	.byte		        1*seq_026_mvl/mxv
	.byte	W04
	.byte		        2*seq_026_mvl/mxv
	.byte	W04
	.byte		        3*seq_026_mvl/mxv
	.byte	W04
	.byte		        4*seq_026_mvl/mxv
	.byte	W02
	.byte	PEND
	.byte	W02
	.byte		VOL   , 4*seq_026_mvl/mxv
	.byte	W04
	.byte		        6*seq_026_mvl/mxv
	.byte	W04
	.byte		        7*seq_026_mvl/mxv
	.byte	W04
	.byte		        7*seq_026_mvl/mxv
	.byte	W04
	.byte		        9*seq_026_mvl/mxv
	.byte	W04
	.byte		        9*seq_026_mvl/mxv
	.byte	W04
	.byte		        10*seq_026_mvl/mxv
	.byte	W04
	.byte		        12*seq_026_mvl/mxv
	.byte	W04
	.byte		        12*seq_026_mvl/mxv
	.byte	W04
	.byte		        14*seq_026_mvl/mxv
	.byte	W04
	.byte		        15*seq_026_mvl/mxv
	.byte	W04
	.byte		        17*seq_026_mvl/mxv
	.byte	W04
	.byte		        19*seq_026_mvl/mxv
	.byte	W04
	.byte		        21*seq_026_mvl/mxv
	.byte	W04
	.byte		        23*seq_026_mvl/mxv
	.byte	W04
	.byte		        25*seq_026_mvl/mxv
	.byte	W04
	.byte		        27*seq_026_mvl/mxv
	.byte	W04
	.byte		        29*seq_026_mvl/mxv
	.byte	W04
	.byte		        31*seq_026_mvl/mxv
	.byte	W04
	.byte		        34*seq_026_mvl/mxv
	.byte	W04
	.byte		        37*seq_026_mvl/mxv
	.byte	W04
	.byte		        40*seq_026_mvl/mxv
	.byte	W04
	.byte		        43*seq_026_mvl/mxv
	.byte	W04
	.byte		        46*seq_026_mvl/mxv
	.byte	W02
	.byte	PEND
	.byte	W02
	.byte		VOL   , 48*seq_026_mvl/mxv
	.byte	W04
	.byte		        55*seq_026_mvl/mxv
	.byte	W04
	.byte		        62*seq_026_mvl/mxv
	.byte	W04
	.byte		        68*seq_026_mvl/mxv
	.byte	W04
	.byte		        74*seq_026_mvl/mxv
	.byte		BEND  , c_v-2
	.byte	W02
	.byte		        c_v-5
	.byte	W02
	.byte		        c_v-5
	.byte	W02
	.byte		        c_v-6
	.byte	W02
	.byte		        c_v-6
	.byte	W02
	.byte		VOL   , 73*seq_026_mvl/mxv
	.byte		BEND  , c_v-7
	.byte	W02
	.byte		        c_v-8
	.byte	W02
	.byte		VOL   , 72*seq_026_mvl/mxv
	.byte		BEND  , c_v-8
	.byte	W02
	.byte		        c_v-9
	.byte	W02
	.byte		VOL   , 70*seq_026_mvl/mxv
	.byte	W02
	.byte		BEND  , c_v-10
	.byte	W02
	.byte		VOL   , 69*seq_026_mvl/mxv
	.byte		BEND  , c_v-11
	.byte	W04
	.byte		VOL   , 67*seq_026_mvl/mxv
	.byte		BEND  , c_v-16
	.byte	W02
	.byte		        c_v-17
	.byte	W02
	.byte		VOL   , 65*seq_026_mvl/mxv
	.byte		BEND  , c_v-19
	.byte	W02
	.byte		        c_v-20
	.byte	W02
	.byte		VOL   , 62*seq_026_mvl/mxv
	.byte		BEND  , c_v-22
	.byte	W02
	.byte		        c_v-23
	.byte	W02
	.byte		VOL   , 53*seq_026_mvl/mxv
	.byte		BEND  , c_v-25
	.byte	W02
	.byte		        c_v-27
	.byte	W02
	.byte		VOL   , 43*seq_026_mvl/mxv
	.byte		BEND  , c_v-31
	.byte	W02
	.byte		        c_v-34
	.byte	W02
	.byte		VOL   , 34*seq_026_mvl/mxv
	.byte		BEND  , c_v-37
	.byte	W02
	.byte		        c_v-40
	.byte	W02
	.byte		VOL   , 24*seq_026_mvl/mxv
	.byte		BEND  , c_v-43
	.byte	W04
	.byte	PEND
	.byte		EOT   , Cs4 
	.byte	W24
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W22
	.byte		BEND  , c_v+0
	.byte	W48
	.byte	W02
	.byte		VOL   , 1*seq_026_mvl/mxv
	.byte		TIE   , Dn4 , v072
	.byte	W06
	.byte		VOL   , 2*seq_026_mvl/mxv
	.byte	W04
	.byte		        1*seq_026_mvl/mxv
	.byte	W04
	.byte		        2*seq_026_mvl/mxv
	.byte	W04
	.byte		        3*seq_026_mvl/mxv
	.byte	W04
	.byte		        4*seq_026_mvl/mxv
	.byte	W02
	.byte	PEND
	.byte	PATT
	 .word	seq_026_5 + 0x36
	.byte	PATT
	 .word	seq_026_5 + 0x69
	.byte		EOT   , Dn4 
	.byte	W24
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_5 + 0x1F
	.byte	PATT
	 .word	seq_026_5 + 0x36
	.byte	PATT
	 .word	seq_026_5 + 0x69
	.byte		EOT   , Cs4 
	.byte	W24
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_5 + 0xD2
	.byte	PATT
	 .word	seq_026_5 + 0x36
	.byte	PATT
	 .word	seq_026_5 + 0x69
	.byte		EOT   , Dn4 
	.byte	W24
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_5 + 0x1F
	.byte	PATT
	 .word	seq_026_5 + 0x36
	.byte	PATT
	 .word	seq_026_5 + 0x69
	.byte		EOT   , Cs4 
	.byte	W24
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_5 + 0xD2
	.byte	PATT
	 .word	seq_026_5 + 0x36
	.byte	PATT
	 .word	seq_026_5 + 0x69
	.byte		EOT   , Dn4 
	.byte	W24
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_5 + 0x1F
	.byte	PATT
	 .word	seq_026_5 + 0x36
	.byte	PATT
	 .word	seq_026_5 + 0x69
	.byte		EOT   , Cs4 
	.byte	W24
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_5 + 0xD2
	.byte	PATT
	 .word	seq_026_5 + 0x36
	.byte	PATT
	 .word	seq_026_5 + 0x69
	.byte		EOT   , Dn4 
	.byte	W24
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_5 + 0x1F
	.byte	PATT
	 .word	seq_026_5 + 0x36
	.byte	PATT
	 .word	seq_026_5 + 0x69
	.byte		EOT   , Cs4 
	.byte	W24
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_5 + 0xD2
	.byte	PATT
	 .word	seq_026_5 + 0x36
	.byte	PATT
	 .word	seq_026_5 + 0x69
	.byte		EOT   , Dn4 
	.byte	W24
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_5 + 0x1F
	.byte	PATT
	 .word	seq_026_5 + 0x36
	.byte	PATT
	 .word	seq_026_5 + 0x69
	.byte		EOT   , Cs4 
	.byte	W24
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_5 + 0xD2
	.byte	PATT
	 .word	seq_026_5 + 0x36
	.byte	PATT
	 .word	seq_026_5 + 0x69
	.byte		EOT   , Dn4 
	.byte	W24
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_5 + 0x1F
	.byte	PATT
	 .word	seq_026_5 + 0x36
	.byte	PATT
	 .word	seq_026_5 + 0x69
	.byte		EOT   , Cs4 
	.byte	W24
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_5 + 0xD2
	.byte	PATT
	 .word	seq_026_5 + 0x36
	.byte	PATT
	 .word	seq_026_5 + 0x69
	.byte		EOT   , Dn4 
	.byte	W24
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_5 + 0x1F
	.byte	PATT
	 .word	seq_026_5 + 0x36
	.byte	PATT
	 .word	seq_026_5 + 0x69
	.byte		EOT   , Cs4 
	.byte	W24
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_5 + 0xD2
	.byte	PATT
	 .word	seq_026_5 + 0x36
	.byte	PATT
	 .word	seq_026_5 + 0x69
	.byte		EOT   , Dn4 
	.byte	W24
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_5 + 0x1F
	.byte	PATT
	 .word	seq_026_5 + 0x36
	.byte	PATT
	 .word	seq_026_5 + 0x69
	.byte		EOT   , Cs4 
	.byte	W24
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_5 + 0xD2
	.byte	PATT
	 .word	seq_026_5 + 0x36
	.byte	PATT
	 .word	seq_026_5 + 0x69
	.byte		EOT   , Dn4 
	.byte	W24
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_5 + 0x1F
	.byte	PATT
	 .word	seq_026_5 + 0x36
	.byte	PATT
	 .word	seq_026_5 + 0x69
	.byte		EOT   , Cs4 
	.byte	W24
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_5 + 0xD2
	.byte	PATT
	 .word	seq_026_5 + 0x36
	.byte	PATT
	 .word	seq_026_5 + 0x69
	.byte		EOT   , Dn4 
	.byte	W24
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_5 + 0x1F
	.byte	PATT
	 .word	seq_026_5 + 0x36
	.byte	PATT
	 .word	seq_026_5 + 0x69
	.byte		EOT   , Cs4 
	.byte	W24
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_5 + 0xD2
	.byte	PATT
	 .word	seq_026_5 + 0x36
	.byte	PATT
	 .word	seq_026_5 + 0x69
	.byte		EOT   , Dn4 
	.byte	W24
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_5 + 0x1F
	.byte	PATT
	 .word	seq_026_5 + 0x36
	.byte	PATT
	 .word	seq_026_5 + 0x69
	.byte		EOT   , Cs4 
	.byte	W24
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_5 + 0xD2
	.byte	PATT
	 .word	seq_026_5 + 0x36
	.byte	PATT
	 .word	seq_026_5 + 0x69
	.byte		EOT   , Dn4 
	.byte	W24
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_5 + 0x1F
	.byte	PATT
	 .word	seq_026_5 + 0x36
	.byte	PATT
	 .word	seq_026_5 + 0x69
	.byte		EOT   , Cs4 
	.byte	W24
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_5 + 0xD2
	.byte	PATT
	 .word	seq_026_5 + 0x36
	.byte	PATT
	 .word	seq_026_5 + 0x69
	.byte		EOT   , Dn4 
	.byte	W24
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_5 + 0x1F
	.byte	PATT
	 .word	seq_026_5 + 0x36
	.byte	PATT
	 .word	seq_026_5 + 0x69
	.byte		EOT   , Cs4 
	.byte	W24
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_5 + 0xD2
	.byte	PATT
	 .word	seq_026_5 + 0x36
	.byte	PATT
	 .word	seq_026_5 + 0x69
	.byte		EOT   , Dn4 
	.byte	W24
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_5 + 0x1F
	.byte	PATT
	 .word	seq_026_5 + 0x36
	.byte	PATT
	 .word	seq_026_5 + 0x69
	.byte		EOT   , Cs4 
	.byte	W24
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	GOTO
	 .word	seq_026_5 + 0x16
	.byte	FINE

@*********************** Track 07 ***********************@

seq_026_6:
	.byte	KEYSH , seq_026_key+0
	.byte	W13
	.byte		VOICE , 22
	.byte		BENDR , 2
	.byte		LFODL , 20
	.byte	W01
	.byte		MOD   , 4
	.byte		VOL   , 49*seq_026_mvl/mxv
	.byte		PAN   , c_v-30
	.byte	W01
	.byte		LFOS  , 20
	.byte		MODT  , mod_tre
	.byte	W09
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W92
	.byte	W02
	.byte		BEND  , c_v+0
	.byte	W02
	.byte	PEND
	.byte	W48
	.byte		VOL   , 1*seq_026_mvl/mxv
	.byte		TIE   , Gs3 , v072
	.byte	W06
	.byte		VOL   , 2*seq_026_mvl/mxv
	.byte	W04
	.byte		        1*seq_026_mvl/mxv
	.byte	W04
	.byte		        2*seq_026_mvl/mxv
	.byte	W04
	.byte		        3*seq_026_mvl/mxv
	.byte	W04
	.byte		        4*seq_026_mvl/mxv
	.byte	W04
	.byte		        4*seq_026_mvl/mxv
	.byte	W04
	.byte		        6*seq_026_mvl/mxv
	.byte	W04
	.byte		        7*seq_026_mvl/mxv
	.byte	W04
	.byte		        7*seq_026_mvl/mxv
	.byte	W04
	.byte		        9*seq_026_mvl/mxv
	.byte	W04
	.byte		        9*seq_026_mvl/mxv
	.byte	W02
	.byte	PEND
	.byte	W02
	.byte		VOL   , 10*seq_026_mvl/mxv
	.byte	W04
	.byte		        12*seq_026_mvl/mxv
	.byte	W04
	.byte		        12*seq_026_mvl/mxv
	.byte	W04
	.byte		        14*seq_026_mvl/mxv
	.byte	W04
	.byte		        15*seq_026_mvl/mxv
	.byte	W04
	.byte		        17*seq_026_mvl/mxv
	.byte	W04
	.byte		        19*seq_026_mvl/mxv
	.byte	W04
	.byte		        21*seq_026_mvl/mxv
	.byte	W04
	.byte		        23*seq_026_mvl/mxv
	.byte	W04
	.byte		        25*seq_026_mvl/mxv
	.byte	W04
	.byte		        27*seq_026_mvl/mxv
	.byte	W04
	.byte		        29*seq_026_mvl/mxv
	.byte	W04
	.byte		        31*seq_026_mvl/mxv
	.byte	W04
	.byte		        34*seq_026_mvl/mxv
	.byte	W04
	.byte		        37*seq_026_mvl/mxv
	.byte	W04
	.byte		        40*seq_026_mvl/mxv
	.byte	W04
	.byte		        43*seq_026_mvl/mxv
	.byte	W04
	.byte		        46*seq_026_mvl/mxv
	.byte	W04
	.byte		        48*seq_026_mvl/mxv
	.byte	W04
	.byte		        55*seq_026_mvl/mxv
	.byte	W04
	.byte		        62*seq_026_mvl/mxv
	.byte	W04
	.byte		        68*seq_026_mvl/mxv
	.byte	W04
	.byte		        74*seq_026_mvl/mxv
	.byte		BEND  , c_v-2
	.byte	W02
	.byte		        c_v-5
	.byte	W02
	.byte		        c_v-5
	.byte	W02
	.byte	PEND
	.byte		BEND  , c_v-6
	.byte	W02
	.byte		        c_v-6
	.byte	W02
	.byte		VOL   , 73*seq_026_mvl/mxv
	.byte		BEND  , c_v-7
	.byte	W02
	.byte		        c_v-8
	.byte	W02
	.byte		VOL   , 72*seq_026_mvl/mxv
	.byte		BEND  , c_v-8
	.byte	W02
	.byte		        c_v-9
	.byte	W02
	.byte		VOL   , 70*seq_026_mvl/mxv
	.byte	W02
	.byte		BEND  , c_v-10
	.byte	W02
	.byte		VOL   , 69*seq_026_mvl/mxv
	.byte		BEND  , c_v-11
	.byte	W04
	.byte		VOL   , 67*seq_026_mvl/mxv
	.byte		BEND  , c_v-16
	.byte	W02
	.byte		        c_v-17
	.byte	W02
	.byte		VOL   , 65*seq_026_mvl/mxv
	.byte		BEND  , c_v-19
	.byte	W02
	.byte		        c_v-20
	.byte	W02
	.byte		VOL   , 62*seq_026_mvl/mxv
	.byte		BEND  , c_v-22
	.byte	W02
	.byte		        c_v-23
	.byte	W02
	.byte		VOL   , 53*seq_026_mvl/mxv
	.byte		BEND  , c_v-25
	.byte	W02
	.byte		        c_v-27
	.byte	W02
	.byte		VOL   , 43*seq_026_mvl/mxv
	.byte		BEND  , c_v-31
	.byte	W02
	.byte		        c_v-34
	.byte	W02
	.byte		VOL   , 34*seq_026_mvl/mxv
	.byte		BEND  , c_v-37
	.byte	W02
	.byte		        c_v-40
	.byte	W02
	.byte		VOL   , 24*seq_026_mvl/mxv
	.byte		BEND  , c_v-43
	.byte	W04
	.byte	PEND
	.byte		EOT   , Gs3 
	.byte	W48
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_6 + 0x1E
	.byte	W48
	.byte		VOL   , 1*seq_026_mvl/mxv
	.byte		TIE   , An3 , v072
	.byte	W06
	.byte		VOL   , 2*seq_026_mvl/mxv
	.byte	W04
	.byte		        1*seq_026_mvl/mxv
	.byte	W04
	.byte		        2*seq_026_mvl/mxv
	.byte	W04
	.byte		        3*seq_026_mvl/mxv
	.byte	W04
	.byte		        4*seq_026_mvl/mxv
	.byte	W04
	.byte		        4*seq_026_mvl/mxv
	.byte	W04
	.byte		        6*seq_026_mvl/mxv
	.byte	W04
	.byte		        7*seq_026_mvl/mxv
	.byte	W04
	.byte		        7*seq_026_mvl/mxv
	.byte	W04
	.byte		        9*seq_026_mvl/mxv
	.byte	W04
	.byte		        9*seq_026_mvl/mxv
	.byte	W02
	.byte	PEND
	.byte	PATT
	 .word	seq_026_6 + 0x43
	.byte	PATT
	 .word	seq_026_6 + 0x7A
	.byte		EOT   , An3 
	.byte	W48
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_6 + 0x1E
	.byte	PATT
	 .word	seq_026_6 + 0x24
	.byte	PATT
	 .word	seq_026_6 + 0x43
	.byte	PATT
	 .word	seq_026_6 + 0x7A
	.byte		EOT   , Gs3 
	.byte	W48
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_6 + 0x1E
	.byte	PATT
	 .word	seq_026_6 + 0xD6
	.byte	PATT
	 .word	seq_026_6 + 0x43
	.byte	PATT
	 .word	seq_026_6 + 0x7A
	.byte		EOT   , An3 
	.byte	W48
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_6 + 0x1E
	.byte	PATT
	 .word	seq_026_6 + 0x24
	.byte	PATT
	 .word	seq_026_6 + 0x43
	.byte	PATT
	 .word	seq_026_6 + 0x7A
	.byte		EOT   , Gs3 
	.byte	W48
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_6 + 0x1E
	.byte	PATT
	 .word	seq_026_6 + 0xD6
	.byte	PATT
	 .word	seq_026_6 + 0x43
	.byte	PATT
	 .word	seq_026_6 + 0x7A
	.byte		EOT   , An3 
	.byte	W48
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_6 + 0x1E
	.byte	PATT
	 .word	seq_026_6 + 0x24
	.byte	PATT
	 .word	seq_026_6 + 0x43
	.byte	PATT
	 .word	seq_026_6 + 0x7A
	.byte		EOT   , Gs3 
	.byte	W48
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_6 + 0x1E
	.byte	PATT
	 .word	seq_026_6 + 0xD6
	.byte	PATT
	 .word	seq_026_6 + 0x43
	.byte	PATT
	 .word	seq_026_6 + 0x7A
	.byte		EOT   , An3 
	.byte	W48
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_6 + 0x1E
	.byte	PATT
	 .word	seq_026_6 + 0x24
	.byte	PATT
	 .word	seq_026_6 + 0x43
	.byte	PATT
	 .word	seq_026_6 + 0x7A
	.byte		EOT   , Gs3 
	.byte	W48
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_6 + 0x1E
	.byte	PATT
	 .word	seq_026_6 + 0xD6
	.byte	PATT
	 .word	seq_026_6 + 0x43
	.byte	PATT
	 .word	seq_026_6 + 0x7A
	.byte		EOT   , An3 
	.byte	W48
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_6 + 0x1E
	.byte	PATT
	 .word	seq_026_6 + 0x24
	.byte	PATT
	 .word	seq_026_6 + 0x43
	.byte	PATT
	 .word	seq_026_6 + 0x7A
	.byte		EOT   , Gs3 
	.byte	W48
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_6 + 0x1E
	.byte	PATT
	 .word	seq_026_6 + 0xD6
	.byte	PATT
	 .word	seq_026_6 + 0x43
	.byte	PATT
	 .word	seq_026_6 + 0x7A
	.byte		EOT   , An3 
	.byte	W48
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_6 + 0x1E
	.byte	PATT
	 .word	seq_026_6 + 0x24
	.byte	PATT
	 .word	seq_026_6 + 0x43
	.byte	PATT
	 .word	seq_026_6 + 0x7A
	.byte		EOT   , Gs3 
	.byte	W48
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_6 + 0x1E
	.byte	PATT
	 .word	seq_026_6 + 0xD6
	.byte	PATT
	 .word	seq_026_6 + 0x43
	.byte	PATT
	 .word	seq_026_6 + 0x7A
	.byte		EOT   , An3 
	.byte	W48
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_6 + 0x1E
	.byte	PATT
	 .word	seq_026_6 + 0x24
	.byte	PATT
	 .word	seq_026_6 + 0x43
	.byte	PATT
	 .word	seq_026_6 + 0x7A
	.byte		EOT   , Gs3 
	.byte	W48
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_6 + 0x1E
	.byte	PATT
	 .word	seq_026_6 + 0xD6
	.byte	PATT
	 .word	seq_026_6 + 0x43
	.byte	PATT
	 .word	seq_026_6 + 0x7A
	.byte		EOT   , An3 
	.byte	W48
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_6 + 0x1E
	.byte	PATT
	 .word	seq_026_6 + 0x24
	.byte	PATT
	 .word	seq_026_6 + 0x43
	.byte	PATT
	 .word	seq_026_6 + 0x7A
	.byte		EOT   , Gs3 
	.byte	W48
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_6 + 0x1E
	.byte	PATT
	 .word	seq_026_6 + 0xD6
	.byte	PATT
	 .word	seq_026_6 + 0x43
	.byte	PATT
	 .word	seq_026_6 + 0x7A
	.byte		EOT   , An3 
	.byte	W48
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_6 + 0x1E
	.byte	PATT
	 .word	seq_026_6 + 0x24
	.byte	PATT
	 .word	seq_026_6 + 0x43
	.byte	PATT
	 .word	seq_026_6 + 0x7A
	.byte		EOT   , Gs3 
	.byte	W48
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_6 + 0x1E
	.byte	PATT
	 .word	seq_026_6 + 0xD6
	.byte	PATT
	 .word	seq_026_6 + 0x43
	.byte	PATT
	 .word	seq_026_6 + 0x7A
	.byte		EOT   , An3 
	.byte	W48
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_6 + 0x1E
	.byte	PATT
	 .word	seq_026_6 + 0x24
	.byte	PATT
	 .word	seq_026_6 + 0x43
	.byte	PATT
	 .word	seq_026_6 + 0x7A
	.byte		EOT   , Gs3 
	.byte	W48
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_6 + 0x1E
	.byte	PATT
	 .word	seq_026_6 + 0xD6
	.byte	PATT
	 .word	seq_026_6 + 0x43
	.byte	PATT
	 .word	seq_026_6 + 0x7A
	.byte		EOT   , An3 
	.byte	W48
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_6 + 0x1E
	.byte	PATT
	 .word	seq_026_6 + 0x24
	.byte	PATT
	 .word	seq_026_6 + 0x43
	.byte	PATT
	 .word	seq_026_6 + 0x7A
	.byte		EOT   , Gs3 
	.byte	W48
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_6 + 0x1E
	.byte	PATT
	 .word	seq_026_6 + 0xD6
	.byte	PATT
	 .word	seq_026_6 + 0x43
	.byte	PATT
	 .word	seq_026_6 + 0x7A
	.byte		EOT   , An3 
	.byte	W48
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_6 + 0x1E
	.byte	PATT
	 .word	seq_026_6 + 0x24
	.byte	PATT
	 .word	seq_026_6 + 0x43
	.byte	PATT
	 .word	seq_026_6 + 0x7A
	.byte		EOT   , Gs3 
	.byte	W48
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_6 + 0x1E
	.byte	PATT
	 .word	seq_026_6 + 0xD6
	.byte	PATT
	 .word	seq_026_6 + 0x43
	.byte	PATT
	 .word	seq_026_6 + 0x7A
	.byte		EOT   , An3 
	.byte	W48
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_6 + 0x1E
	.byte	PATT
	 .word	seq_026_6 + 0x24
	.byte	PATT
	 .word	seq_026_6 + 0x43
	.byte	PATT
	 .word	seq_026_6 + 0x7A
	.byte		EOT   , Gs3 
	.byte	W48
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_6 + 0x1E
	.byte	PATT
	 .word	seq_026_6 + 0xD6
	.byte	PATT
	 .word	seq_026_6 + 0x43
	.byte	PATT
	 .word	seq_026_6 + 0x7A
	.byte		EOT   , An3 
	.byte	W48
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	seq_026_6 + 0x1E
	.byte	PATT
	 .word	seq_026_6 + 0x24
	.byte	PATT
	 .word	seq_026_6 + 0x43
	.byte	PATT
	 .word	seq_026_6 + 0x7A
	.byte		EOT   , Gs3 
	.byte	W48
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	GOTO
	 .word	seq_026_6 + 0x16
	.byte	FINE

@******************************************************@

	.align	2

seq_026:
	.byte	7	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_026_pri	@ Priority
	.byte	seq_026_rev	@ Reverb

	.word	seq_026_grp

	.word	seq_026_0
	.word	seq_026_1
	.word	seq_026_2
	.word	seq_026_3
	.word	seq_026_4
	.word	seq_026_5
	.word	seq_026_6

	.end
