@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_688_grp, bank_026
	.equ	seq_688_pri, 127
	.equ	seq_688_rev, 0
	.equ	seq_688_mvl, 127
	.equ	seq_688_key, 0

	.section .rodata
	.global	seq_688
	.align	2

@*********************** Track 01 ***********************@

seq_688_0:
	.byte	KEYSH , seq_688_key+0
	.byte	TEMPO , 180/2
	.byte		VOICE , 1
	.byte	W01
	.byte		VOL   , 120*seq_688_mvl/mxv
	.byte	W01
	.byte		PAN   , c_v+0
	.byte		N07   , Fs3 , v120
	.byte	W01
	.byte		BENDR , 13
	.byte		BEND  , c_v+1
	.byte	W01
	.byte		        c_v+4
	.byte	W01
	.byte		        c_v+9
	.byte	W06
	.byte		        c_v-1
	.byte		N06   , Gn4 , v088
	.byte	W01
	.byte		BEND  , c_v+2
	.byte	W01
	.byte		        c_v+15
	.byte	W19
	.byte		VOL   , 118*seq_688_mvl/mxv
	.byte	W02
	.byte		        117*seq_688_mvl/mxv
	.byte	W01
	.byte		        116*seq_688_mvl/mxv
	.byte	W01
	.byte		        114*seq_688_mvl/mxv
	.byte	W01
	.byte		        111*seq_688_mvl/mxv
	.byte	W01
	.byte		        108*seq_688_mvl/mxv
	.byte	W01
	.byte		        104*seq_688_mvl/mxv
	.byte	W01
	.byte		        99*seq_688_mvl/mxv
	.byte	W01
	.byte		        94*seq_688_mvl/mxv
	.byte	W01
	.byte		        82*seq_688_mvl/mxv
	.byte	W01
	.byte		        75*seq_688_mvl/mxv
	.byte	W01
	.byte		        67*seq_688_mvl/mxv
	.byte	W01
	.byte		        59*seq_688_mvl/mxv
	.byte	W01
	.byte		        50*seq_688_mvl/mxv
	.byte	W01
	.byte		        41*seq_688_mvl/mxv
	.byte	W01
	.byte		        31*seq_688_mvl/mxv
	.byte	W01
	.byte		        20*seq_688_mvl/mxv
	.byte	W01
	.byte		        9*seq_688_mvl/mxv
	.byte	W01
	.byte		        0*seq_688_mvl/mxv
	.byte	FINE

@******************************************************@

	.align	2

seq_688:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_688_pri	@ Priority
	.byte	seq_688_rev	@ Reverb

	.word	seq_688_grp

	.word	seq_688_0

	.end
