@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_499_grp, bank_028
	.equ	seq_499_pri, 127
	.equ	seq_499_rev, 0
	.equ	seq_499_mvl, 127
	.equ	seq_499_key, 0

	.section .rodata
	.global	seq_499
	.align	2

@*********************** Track 01 ***********************@

seq_499_0:
	.byte	KEYSH , seq_499_key+0
	.byte	TEMPO , 80/2
	.byte		VOICE , 24
	.byte		VOL   , 4*seq_499_mvl/mxv
	.byte		PAN   , c_v+0
	.byte	W01
	.byte		MOD   , 60
	.byte		LFOS  , 42
	.byte	W01
	.byte		BENDR , 60
	.byte		MODT  , mod_tre
	.byte		BEND  , c_v+0
	.byte	W01
	.byte		VOL   , 15*seq_499_mvl/mxv
	.byte		N44   , Cn3 , v127
	.byte	W02
	.byte		VOL   , 25*seq_499_mvl/mxv
	.byte		BEND  , c_v-3
	.byte	W01
	.byte		VOL   , 30*seq_499_mvl/mxv
	.byte	W01
	.byte		BEND  , c_v-3
	.byte	W01
	.byte		VOL   , 40*seq_499_mvl/mxv
	.byte	W01
	.byte		        45*seq_499_mvl/mxv
	.byte		PAN   , c_v+16
	.byte		BEND  , c_v-4
	.byte	W01
	.byte		VOL   , 50*seq_499_mvl/mxv
	.byte		BEND  , c_v-4
	.byte	W02
	.byte		VOL   , 60*seq_499_mvl/mxv
	.byte		PAN   , c_v-19
	.byte		BEND  , c_v-5
	.byte	W01
	.byte		VOL   , 64*seq_499_mvl/mxv
	.byte	W01
	.byte		        69*seq_499_mvl/mxv
	.byte		BEND  , c_v-6
	.byte	W01
	.byte		PAN   , c_v+16
	.byte		BEND  , c_v-6
	.byte	W01
	.byte		VOL   , 80*seq_499_mvl/mxv
	.byte	W01
	.byte		        85*seq_499_mvl/mxv
	.byte		BEND  , c_v-7
	.byte	W01
	.byte		VOL   , 90*seq_499_mvl/mxv
	.byte		PAN   , c_v-19
	.byte		BEND  , c_v-7
	.byte	W02
	.byte		VOL   , 100*seq_499_mvl/mxv
	.byte		BEND  , c_v-8
	.byte	W01
	.byte		VOL   , 105*seq_499_mvl/mxv
	.byte		PAN   , c_v+16
	.byte	W01
	.byte		VOL   , 110*seq_499_mvl/mxv
	.byte		BEND  , c_v-8
	.byte	W01
	.byte		        c_v-9
	.byte	W01
	.byte		VOL   , 120*seq_499_mvl/mxv
	.byte		PAN   , c_v-19
	.byte	W01
	.byte		VOL   , 125*seq_499_mvl/mxv
	.byte		BEND  , c_v-9
	.byte	W02
	.byte		PAN   , c_v+15
	.byte		BEND  , c_v-10
	.byte	W01
	.byte		        c_v-10
	.byte	W02
	.byte		PAN   , c_v-19
	.byte		BEND  , c_v-11
	.byte	W01
	.byte		        c_v-11
	.byte	W02
	.byte		PAN   , c_v+15
	.byte		BEND  , c_v-12
	.byte	W02
	.byte		        c_v-13
	.byte	W01
	.byte		PAN   , c_v-19
	.byte		BEND  , c_v-13
	.byte	W02
	.byte		        c_v-14
	.byte	W01
	.byte		PAN   , c_v+16
	.byte	W01
	.byte		BEND  , c_v-14
	.byte	W01
	.byte		        c_v-15
	.byte	W01
	.byte		PAN   , c_v-19
	.byte	W01
	.byte		BEND  , c_v-15
	.byte	W01
	.byte		        c_v-16
	.byte	W01
	.byte		PAN   , c_v+16
	.byte	W01
	.byte		BEND  , c_v-16
	.byte	W02
	.byte		PAN   , c_v+0
	.byte		BEND  , c_v-17
	.byte	W01
	.byte		        c_v-18
	.byte	W02
	.byte	W12
	.byte	W02
	.byte		VOICE , 32
	.byte		VOL   , 50*seq_499_mvl/mxv
	.byte	W01
	.byte		N06   , Ds3 , v092
	.byte	W01
	.byte		BEND  , c_v-18
	.byte	W01
	.byte		        c_v-12
	.byte	W01
	.byte		        c_v-6
	.byte	W01
	.byte		        c_v+0
	.byte	W01
	.byte		        c_v+6
	.byte	W02
	.byte		N06   , Fn2 , v040
	.byte	W02
	.byte	W05
	.byte		N13   , Fn2 , v020
	.byte	W07
	.byte	W06
	.byte	FINE

@*********************** Track 02 ***********************@

seq_499_1:
	.byte	KEYSH , seq_499_key+0
	.byte	W03
	.byte	W12
	.byte		VOICE , 24
	.byte		VOL   , 4*seq_499_mvl/mxv
	.byte		PAN   , c_v+0
	.byte	W01
	.byte		MOD   , 127
	.byte		LFOS  , 42
	.byte	W01
	.byte		BENDR , 60
	.byte		MODT  , mod_tre
	.byte		BEND  , c_v+0
	.byte	W01
	.byte		VOL   , 5*seq_499_mvl/mxv
	.byte		N48   , Dn4 , v127
	.byte	W02
	.byte		VOL   , 8*seq_499_mvl/mxv
	.byte		BEND  , c_v-3
	.byte	W01
	.byte		VOL   , 13*seq_499_mvl/mxv
	.byte	W01
	.byte		BEND  , c_v-3
	.byte	W01
	.byte		VOL   , 23*seq_499_mvl/mxv
	.byte	W01
	.byte		        29*seq_499_mvl/mxv
	.byte		PAN   , c_v+16
	.byte		BEND  , c_v-4
	.byte	W01
	.byte		VOL   , 34*seq_499_mvl/mxv
	.byte		BEND  , c_v-4
	.byte	W02
	.byte		VOL   , 44*seq_499_mvl/mxv
	.byte		PAN   , c_v-19
	.byte		BEND  , c_v-5
	.byte	W01
	.byte		VOL   , 50*seq_499_mvl/mxv
	.byte	W01
	.byte		        55*seq_499_mvl/mxv
	.byte		BEND  , c_v-6
	.byte	W01
	.byte		PAN   , c_v+16
	.byte		BEND  , c_v-6
	.byte	W01
	.byte		VOL   , 64*seq_499_mvl/mxv
	.byte	W01
	.byte		        70*seq_499_mvl/mxv
	.byte		BEND  , c_v-7
	.byte	W01
	.byte		VOL   , 75*seq_499_mvl/mxv
	.byte		PAN   , c_v-19
	.byte		BEND  , c_v-7
	.byte	W02
	.byte		VOL   , 85*seq_499_mvl/mxv
	.byte		BEND  , c_v-8
	.byte	W01
	.byte		VOL   , 91*seq_499_mvl/mxv
	.byte		PAN   , c_v+16
	.byte	W01
	.byte		VOL   , 96*seq_499_mvl/mxv
	.byte		BEND  , c_v-8
	.byte	W01
	.byte		        c_v-9
	.byte	W01
	.byte		VOL   , 106*seq_499_mvl/mxv
	.byte		PAN   , c_v-19
	.byte	W01
	.byte		VOL   , 112*seq_499_mvl/mxv
	.byte		BEND  , c_v-9
	.byte	W02
	.byte		PAN   , c_v+15
	.byte		BEND  , c_v-10
	.byte	W01
	.byte		        c_v-10
	.byte	W02
	.byte		PAN   , c_v-19
	.byte		BEND  , c_v-11
	.byte	W01
	.byte		        c_v-11
	.byte	W02
	.byte		PAN   , c_v+15
	.byte		BEND  , c_v-12
	.byte	W02
	.byte		        c_v-13
	.byte	W01
	.byte		PAN   , c_v-19
	.byte		BEND  , c_v-13
	.byte	W02
	.byte		        c_v-14
	.byte	W01
	.byte		PAN   , c_v+16
	.byte	W01
	.byte		BEND  , c_v-14
	.byte	W01
	.byte		        c_v-15
	.byte	W01
	.byte		PAN   , c_v-19
	.byte	W01
	.byte		BEND  , c_v-15
	.byte	W01
	.byte		        c_v-16
	.byte	W01
	.byte		PAN   , c_v+16
	.byte	W01
	.byte		BEND  , c_v-16
	.byte	W02
	.byte		PAN   , c_v+0
	.byte		BEND  , c_v-17
	.byte	W01
	.byte		        c_v-18
	.byte	W02
	.byte	FINE

@******************************************************@

	.align	2

seq_499:
	.byte	2	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_499_pri	@ Priority
	.byte	seq_499_rev	@ Reverb

	.word	seq_499_grp

	.word	seq_499_0
	.word	seq_499_1

	.end
