@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_691_grp, bank_026
	.equ	seq_691_pri, 127
	.equ	seq_691_rev, 0
	.equ	seq_691_mvl, 127
	.equ	seq_691_key, 0

	.section .rodata
	.global	seq_691
	.align	2

@*********************** Track 01 ***********************@

seq_691_0:
	.byte	KEYSH , seq_691_key+0
	.byte	TEMPO , 200/2
	.byte		VOICE , 12
	.byte		VOL   , 125*seq_691_mvl/mxv
	.byte		PAN   , c_v+0
	.byte	W01
	.byte		MOD   , 50
	.byte	W02
	.byte		BEND  , c_v+0
	.byte		N19   , Cs4 , v127
	.byte	W02
	.byte		BEND  , c_v-1
	.byte		N18   , As2 , v088
	.byte	W01
	.byte		BEND  , c_v-5
	.byte	W01
	.byte		        c_v-18
	.byte	W01
	.byte		        c_v-39
	.byte	W01
	.byte		        c_v-58
	.byte	W03
	.byte		        c_v-60
	.byte	W01
	.byte		        c_v-60
	.byte	W01
	.byte		VOL   , 122*seq_691_mvl/mxv
	.byte		BEND  , c_v-57
	.byte	W01
	.byte		VOL   , 112*seq_691_mvl/mxv
	.byte		BEND  , c_v-52
	.byte	W01
	.byte		VOL   , 101*seq_691_mvl/mxv
	.byte		BEND  , c_v-46
	.byte	W01
	.byte		VOL   , 89*seq_691_mvl/mxv
	.byte		BEND  , c_v-38
	.byte	W01
	.byte		VOL   , 77*seq_691_mvl/mxv
	.byte		BEND  , c_v-28
	.byte	W01
	.byte		VOL   , 65*seq_691_mvl/mxv
	.byte		BEND  , c_v-17
	.byte	W01
	.byte		VOL   , 54*seq_691_mvl/mxv
	.byte		BEND  , c_v-4
	.byte	W01
	.byte		VOL   , 42*seq_691_mvl/mxv
	.byte		BEND  , c_v+12
	.byte	W01
	.byte		VOL   , 30*seq_691_mvl/mxv
	.byte		BEND  , c_v+29
	.byte	W01
	.byte		        c_v+48
	.byte	FINE

@******************************************************@

	.align	2

seq_691:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_691_pri	@ Priority
	.byte	seq_691_rev	@ Reverb

	.word	seq_691_grp

	.word	seq_691_0

	.end
