@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_881_grp, bank_026
	.equ	seq_881_pri, 127
	.equ	seq_881_rev, 0
	.equ	seq_881_mvl, 127
	.equ	seq_881_key, 0

	.section .rodata
	.global	seq_881
	.align	2

@*********************** Track 01 ***********************@

seq_881_0:
	.byte	KEYSH , seq_881_key+0
	.byte	TEMPO , 134/2
	.byte		VOICE , 34
	.byte		VOL   , 127*seq_881_mvl/mxv
	.byte		PAN   , c_v+0
	.byte	W02
	.byte		VOL   , 102*seq_881_mvl/mxv
	.byte		BEND  , c_v+0
	.byte		N03   , An2 , v120
	.byte	W02
	.byte		MOD   , 30
	.byte		VOL   , 127*seq_881_mvl/mxv
	.byte	W03
	.byte		N32   , En2 , v127
	.byte		N32   , Cs4 
	.byte	W02
	.byte		BEND  , c_v-5
	.byte	W01
	.byte		        c_v-40
	.byte	W01
	.byte		        c_v-24
	.byte	W01
	.byte		        c_v-18
	.byte	W01
	.byte		        c_v-12
	.byte	W01
	.byte		VOL   , 127*seq_881_mvl/mxv
	.byte		BEND  , c_v-4
	.byte	W01
	.byte		        c_v-1
	.byte	W01
	.byte		        c_v+2
	.byte	W01
	.byte		VOL   , 126*seq_881_mvl/mxv
	.byte		BEND  , c_v+5
	.byte	W01
	.byte		VOL   , 124*seq_881_mvl/mxv
	.byte		BEND  , c_v+8
	.byte	W01
	.byte		VOL   , 120*seq_881_mvl/mxv
	.byte		BEND  , c_v+10
	.byte	W01
	.byte		VOL   , 118*seq_881_mvl/mxv
	.byte		BEND  , c_v+13
	.byte	W01
	.byte		VOL   , 114*seq_881_mvl/mxv
	.byte		BEND  , c_v+15
	.byte	W01
	.byte		VOL   , 111*seq_881_mvl/mxv
	.byte		BEND  , c_v+17
	.byte	W01
	.byte		VOL   , 107*seq_881_mvl/mxv
	.byte		BEND  , c_v+20
	.byte	W01
	.byte		VOL   , 103*seq_881_mvl/mxv
	.byte		BEND  , c_v+22
	.byte	W01
	.byte		VOL   , 98*seq_881_mvl/mxv
	.byte		BEND  , c_v+24
	.byte	W01
	.byte		VOL   , 93*seq_881_mvl/mxv
	.byte		BEND  , c_v+26
	.byte	W01
	.byte		VOL   , 88*seq_881_mvl/mxv
	.byte		BEND  , c_v+28
	.byte	W01
	.byte		VOL   , 82*seq_881_mvl/mxv
	.byte		BEND  , c_v+30
	.byte	W01
	.byte		VOL   , 75*seq_881_mvl/mxv
	.byte		BEND  , c_v+31
	.byte	W01
	.byte		VOL   , 69*seq_881_mvl/mxv
	.byte		BEND  , c_v+33
	.byte	W01
	.byte		VOL   , 62*seq_881_mvl/mxv
	.byte		BEND  , c_v+35
	.byte	W01
	.byte		VOL   , 54*seq_881_mvl/mxv
	.byte		BEND  , c_v+37
	.byte	W01
	.byte		VOL   , 46*seq_881_mvl/mxv
	.byte		BEND  , c_v+40
	.byte	W01
	.byte		VOL   , 38*seq_881_mvl/mxv
	.byte		BEND  , c_v+41
	.byte	W01
	.byte		VOL   , 29*seq_881_mvl/mxv
	.byte		BEND  , c_v+43
	.byte	W01
	.byte		VOL   , 20*seq_881_mvl/mxv
	.byte		BEND  , c_v+44
	.byte	W01
	.byte		VOL   , 10*seq_881_mvl/mxv
	.byte		BEND  , c_v+46
	.byte	W01
	.byte		VOL   , 0*seq_881_mvl/mxv
	.byte		BEND  , c_v+47
	.byte	W01
	.byte		        c_v+49
	.byte	W01
	.byte		        c_v+50
	.byte	W01
	.byte		        c_v+52
	.byte	W01
	.byte		        c_v+53
	.byte	W01
	.byte		        c_v+55
	.byte	FINE

@******************************************************@

	.align	2

seq_881:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_881_pri	@ Priority
	.byte	seq_881_rev	@ Reverb

	.word	seq_881_grp

	.word	seq_881_0

	.end
